### ISSUE TITLE
Connect to MySQL server over SSH

### ISSUE THREAD

**Issue by depsimon** [prisma/prisma#10019]
### Bug description

I have a MySQL database hosted on premise for a client and the only way to access it is over a SSH connection.

TablePlus gives me the following URL to connect to it :

```
mysql+ssh://{sshUser}:{sshPassword}@{sshHostname}:{sshPort}/{dbUser}:{dbPassword}@{dbHost}/{dbName}
```

But it seems that it doesn't work.

First I got the `Error: Unknown database type mysql+ssh:` error.

So I modified the type to `mysql`.

The next error is the following:

```
Datasource "db": MySQL database "{dbUser}:{dbPassword}@{dbHost}/{dbName}" at "{sshHostname}:{sshPort}"
Error: P1001: Can't reach database server at `{sshHostname}`:`{sshPort}`
```

So I'm wondering if this is possible at all?

I tried the URL in `mycli` but it doesn't recognize it.

The credentials (both the SSH & DB) are correct and work from multiple devices.

### How to reproduce

1. Have a DB accessible on a SSH-only server
2. Try to connect to the DB with a DB URL

### Expected behavior

I expect Prisma to connect to the DB via SSH with the given credentials.

### Environment & setup

- OS: Mac OS / Vercel
- Database: MySQL 5.7
- Node.js version: 16.3

### Prisma Version

```
prisma                  : 3.1.1
@prisma/client          : 3.1.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : c22652b7e418506fab23052d569b85d3aec4883f
Studio                  : 0.423.0
```

**Comment by janpio** [comment]
I don't think this is supported in Prisma right now.

You should be able to set up the SSH tunnel yourself though: https://linuxize.com/post/mysql-ssh-tunnel/ Does that work for you?

**Comment by depsimon** [comment]
Thanks for your reply.

This is actually how I connect to the DB from my machine.
But I don't know if this is applicable to a serverless Node.js application? (hosted on Vercel)

I suppose there should be a way to setup the tunnel in node as I saw some packages for that, but will Prisma use the tunnel?
Won't the performances be badly impacted?

**Comment by janpio** [comment]
Generally that is exactly what _any_ tool would need to do under the hood, so I am not sure if it would make a difference.

**Comment by depsimon** [comment]
I see. Thanks for your time!

I'll try and look for something to work with

**Comment by janpio** [comment]
Let us know if you figure out this works - or does not. I bet other people might be googling for similar things, so writing this down might be interesting.

**Comment by s875515** [comment]
@depsimon I have totally same issue.
We would like to connect to RDS postgresql via SSH tunnel which is an EC2 instance.
If you could share what you found that would be great, many thanks :)

**Comment by pacxiu** [comment]
Hi there, any success with that? @s875515 @depsimon .

I was playing so far with `ssh2` and `tunnel-ssh` but couldn't get those to be working inside `Node.js` but can connect if I setup tunnel in terminal.

**Comment by depsimon** [comment]
Nope, I ended up creating an API on a server that has access to the DB to expose it.

**Comment by s875515** [comment]
> Hi there, any success with that? @s875515 @depsimon .
> 
> I was playing so far with `ssh2` and `tunnel-ssh` but couldn't get those to be working inside `Node.js` but can connect if I setup tunnel in terminal.

Unfortunately, the only way I know is just create a tunnel-ssh so far.
Creating a new port for tunnel-ssh and connect to the port.
```
ssh -o ServerAliveInterval=60 -CfNg -i ./yourpemfile.pem -L 13306:{rds domain}:5432 ubuntu@{ip} -p22
```
