### ISSUE TITLE
A mysql comment (eg `-- some comment`) at the start of a migration causes a database error

### ISSUE THREAD

**Issue by luisgregson** [prisma/prisma#10017]
### Bug description

When a sql migration contains a comment in the first line, the migration fails because of a "SQL syntax" error.
This appears to be because the sql is being reformatted and the second line is appended to the end of the first, thereby becoming part of the comment.

This seems to be part of a wider issue that sql migrations are being processed / formatted before they are executed on the database.
I'd like to understand why the migrations are being changed at all; it seems like the easiest way to avoid errors is to send the sql exactly as it is in the migration so that developers can fix issues without having to understand the inner workings of the prisma-migrate code.

### How to reproduce

1. Create a mysql migration containing a comment in the first line, eg:
```sql
-- this migration backfills some data
UPDATE table1
SET column1 = 1;
```
2. Run `yarn prisma migrate dev` or `npm prisma migrate dev`

### Expected behavior

The migration to successfully apply without errors.

### Prisma information

The prisma schema doesn't matter, as the migration sql could be anything.

### Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: 14.16.1

### Prisma Version

```
2.28.0
```

**Comment by janpio** [comment]
A normal migration created by Prisma Migrate usually _has_ a comment in the first line:

```prisma
model Foo {
  id      Int                      @id @default(autoincrement())
  content Unsupported("tsvector")?
}
```

```sql
-- CreateTable
CREATE TABLE "Foo" (
    "id" SERIAL NOT NULL,
    "content" tsvector,

    CONSTRAINT "Foo_pkey" PRIMARY KEY ("id")
);

```

To double check I also manually created a new migration folder with a file similar to yours, and it works just fine with `prisma migrate dev` or `prisma migrate deploy`.

This is the version I am on:

```
λ npx prisma -v
Environment variables loaded from .env
prisma                  : 3.4.1
@prisma/client          : 3.4.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
```

Can you please try with this newer version or provide some more information what you are doing? Can you share the actual migration file you are using maybe? 
What output are you getting for the error message? Can you active `DEBUG=*` before running that? 
Thanks.

**Comment by janpio** [comment]
Ping @luisgregson

**Comment by janpio** [comment]
Can you take another look @luisgregson? Otherwise we will have to close this issue.
