### ISSUE TITLE
[Feedback] Introspection of embedded documents / composite types in MongoDB

### ISSUE THREAD

**Issue by floelhoeffel** [prisma/prisma#10016]
### Summary 

Introspection of embedded documents in MongoDB is available as a preview feature.

To use it, simply run
```
npx prisma db pull --force
```

> Note: we use the --force flag here as re-introspection is not supported with MongoDB. Just omit that if you run it only once.

against a MongoDB database and all embedded documents will be analyzed and added to the Prisma schema via `type {}`. The level of depth can be controlled or switched off via the option parameter:

```
--composite-type-depth=-1  // Inspect infinite levels of nesting (new default since 3.10.0)
--composite-type-depth=0   // Disable introspection of composite types (default from 3.4 to 3.9 included)
--composite-type-depth=N   // Inspect N levels of nesting

```

Please use this issue to report any feedback.

**Comment by Hitabis** [comment]
Thanks for this feature. It seems to work fine. The prisma cli seems to be confused with ports.

```
datasource db {
  provider = "mongodb"
  url      = "mongodb://testReadOnlyUser:****@db-rs-11:27017,db-rs-12:27017,db-rs-13:27017,db-rs-14:27017,db-rs-15:27017/default_default?replicaSet=dbMongoDB&maxPoolSize=1000"
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}
```

gives
`Error: invalid port number in database URL`

Using this without the ports works fine
`mongodb://testReadOnlyUser:****@db-rs-11,db-rs-12,db-rs-13,db-rs-14,db-rs-15/default_default?replicaSet=dbMongoDB&maxPoolSize=1000`

**Comment by janpio** [comment]
Thanks @Hitabis, can you open a standalone issue on this please? Thanks.

**Comment by Jolg42** [comment]
Note that the default just changed with 3.10.0 and the default depth is infinite.

**Comment by floelhoeffel** [comment]
Closing as Introspection of embedded documents is in GA
