### ISSUE TITLE
CI: Test on Node.js Active LTS v16

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#10022]
Since Node.js v16 is LTS since `2021-10-26` we want to add it to testing.

https://nodejs.org/en/about/releases/

**Comment by aqrln** [comment]
Re: command-line option, it might be easier to set it via an environment variable:

```
NODE_OPTIONS="--max-old-space-size=2048"
```

**Comment by Jolg42** [comment]
Done in https://github.com/prisma/prisma/pull/10020
