### ISSUE TITLE
Incorrect formatting of Postgres type money using type attribute @db.Money

### ISSUE THREAD

**Issue by TylerJNewman** [prisma/prisma#10045]
I am switching over from TypeORM to Prisma and I am having issues with the Postgres money type using type attribute @db.Money.  This is working correctly with TypeORM. I expect the output from the database query to use local currency formatting, such as '$1,000.00' but am instead receiving 1000'.  Can you please help?  Is this a bug or am I missing something?

"pg": "8.6.0",
 "@prisma/client": "3.0.2",
 "next": "^12.0.1",

node: v14.17.1 

<img width="531" alt="Screen Shot 2021-11-01 at 12 20 03 PM" src="https://user-images.githubusercontent.com/8213268/139728653-2a23ab27-d122-4360-897f-74687c647cd0.png">

**Comment by janpio** [comment]
Can you help us reproduce what you are seeing here? What is the minimal schema we would need to create here, and what code to executed (to add and read data I assume) to see this going wrong? Thanks.
