### ISSUE TITLE
Misleading 'We need to reset the PostgreSQL database' when using PostgreSQL _schemas_

### ISSUE THREAD

**Issue by chemicalkosek** [prisma/prisma#10043]
## Problem

When there's a database drift detected when doing `prisma migrate dev` there is a prompt like:
```bash
✔ We need to reset the PostgreSQL database "prisma" at "localhost:49153".
```
It implies that the whole database 'prisma' will be reset while in fact it just resets the PostgreSQL schema under the 'prisma' database.
It leaves other schemas under 'prisma' database intact.

## Suggested solution

Warn just about the PostgreSQL schema being reset, not the whole database.

**Comment by do4gr** [comment]
#Phrasing
