### ISSUE TITLE
Prisma migrate not reading from .env file.

### ISSUE THREAD

**Issue by jakegiri** [prisma/prisma#10061]
### Bug description

Everything was working fine in my local system. Then in my different server i cloned my repo and installed everything. 
Then i created .env file in the root folder as it should be and added the required variables. 

But when i did `prisma migrate deploy` or `prisma migrate dev --name init` i get the same error `error: Environment variable not found: DATABASE_URL`  

![image](https://user-images.githubusercontent.com/24270559/139871165-967a83f4-0552-4f5f-b0c9-b42d7a289dc0.png)

### Environment & setup

- OS: CentOS
- Database: PostgreSQL

### Prisma Version

```
prisma                  : 3.2.1
@prisma/client          : 3.2.1
Current platform        : rhel-openssl-1.1.x
Query Engine (Node-API) : libquery-engine b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/libquery_engine-rhel-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/migration-engine-rhel-openssl-1.1.x)
Introspection Engine    : introspection-core b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.1.x)
Format Binary           : prisma-fmt b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/prisma-fmt-rhel-openssl-1.1.x)
Default Engines Hash    : b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c
Studio                  : 0.435.0

```

**Comment by silkyland** [comment]
Replace
```env
DATABASE_URL:"....." 
```
With
```env
DATABASE_URL="...."
```

**Comment by jakegiri** [comment]
> Try to replace
> 
> ```shell
> DATABASE_URL:"....." 
> ```
> 
> With
> 
> ```shell
> DATABASE_URL="...."
> ```

Damn this is embarrasingly terrible silly error

**Comment by janpio** [comment]
It would be really nice if the library we are using, `dotenv` would detect this "wrong" definition and output an error or warning here somehow.

**Comment by jakegiri** [comment]
@janpio I agree too. That'd sound much logical and efficient
