### ISSUE TITLE
Support order by relevance

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#10066]
## Problem

Right now if you use full text search, the results are unordered. This wouldn't be a very good search engine if it doesn't order the results.

## Suggested solution

Given the following Prisma Schema

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Fruit {
  id Int @id @default(autoincrement())
  name String
}
```

Introduce a `_relevance` field, where you can order search fields by descending or ascending order .

```ts
  const results = await prisma.fruit.findMany({
    orderBy: {
      _relevance: {
        fields: ["name"],
        search: "Blue",
        sort: "desc",
      },
    },
  })
```

Note that we also support filtering search results:

```ts
  const results = await prisma.fruit.findMany({
    where: {
      name: {
        search: "Blue",
      },
    },
    orderBy: {
      _relevance: {
        fields: ["name"],
        search: "Blue",
        sort: "desc",
      },
    },
  })
```

These can be used together or separately.

- `where` filters the records (removes records with a relevance scores = 0), 
- `orderBy` orders the record by their relevance score

## Additional context

Implementation PRs:

- https://github.com/prisma/prisma-engines/pull/2203
- https://github.com/prisma/prisma/pull/9834
- https://github.com/prisma/prisma-client-go/pull/660

**Comment by MichalLytek** [comment]
@matthewmueller The DMMF is leaking the new `relevance` stuff in `v3.4.0` 😱 
This breaks generators like TypeGraphQL-Prisma or Nexus-Prisma 🙈 
![image](https://user-images.githubusercontent.com/10618781/140037202-6baf90a6-6b98-44e5-974a-4f678b9059f2.png)

It should be hidden by the `preview` flag like the other features used to be hidden (even in DMMF).

**Comment by aqrln** [comment]
@MichalLytek I believe it's currently hidden behind the `fullTextSearch` flag. Or do you mean a separate flag just for `_relevance`, like a preview feature of a preview feature?

**Comment by MichalLytek** [comment]
Ah right, my fault 😥 I had `fullTextSearch` in my experiment project, the tests for defaults (without flags) are passing. Sorry for the noise 😉

**Comment by abeaclark** [comment]
Is this feature in 3.5.0? Or getting added to 3.6.0?

Noticed it described in the release notes: https://github.com/prisma/prisma/releases/3.5.0

But I see this issue outstanding and doesn't seem to be working for me. 

Thanks for the hard work on this!

**Comment by janpio** [comment]
Are you adding the `fullTextSearch` preview feature flag? This mention might be missing in our release notes.

**Comment by abeaclark** [comment]
@janpio thanks for the tip! Working now!

**Comment by matthewmueller** [comment]
This has been implemented in https://github.com/prisma/prisma/releases/tag/3.5.0
