### ISSUE TITLE
Repeat generation “ ALTER COLUMN "rechargeAt" SET DEFAULT '2020-06-06 06:06:06 +00:00'; ” in migrations file

### ISSUE THREAD

**Issue by youxdd** [prisma/prisma#10077]
### Bug description

1、I added in the schema.prisma file  < rechargeAt   DateTime    @default("2020-06-06T06:06:06.000Z") >；
2、Every time it is executed < npx prisma migrate dev > will produce < ALTER TABLE "UserWealth" ALTER COLUMN "rechargeAt" SET DEFAULT '2020-06-06 06:06:06 +00:00'; > , But I did not modify  <rechargeAt>

### Prisma information

model UserWealth {
  id                String              @id
  rechargeAt        DateTime            @default("2020-06-06T06:06:06.000Z")
}

### Environment & setup

- OS: 
- Database: 
- Node.js version: 
Mac OS
PostgreSQL 12
node v14.17.3

### Prisma Version

```
3.4.0
```

**Comment by janpio** [comment]
Could this be a duplicate of https://github.com/prisma/prisma/issues/5892?

**Comment by youxdd** [comment]
> Could this be a duplicate of #5892?

Presumably yes
