### ISSUE TITLE
Index `name` validations

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#10082]
Currently we validate the `name` parameter uniqueness in indices per database settings. This variable is not part of the database, but the client, and should always be validated to be unique per model.

The issue should be to take this validation out from the scoped database constraint validations, and apply it to all connectors.

**Comment by Jolg42** [comment]
We should document the validations

**Comment by pimeys** [comment]
```prisma
model A {
  id Int
  id2 Int
  @@id([id, id2], name: "foo")
  @@unique([id, id2], map: "foo")
}
```
This should be ok and we should validate the indexes in different namespaces.
