### ISSUE TITLE
How to get random rows with Prisma?

### ISSUE THREAD

**Issue by TPME** [prisma/prisma#10090]
## Problem

I need a fundamental feature which is basically getting one or multiple rows sorted by random.

## Suggested solution

Add a new orderBy order and call it `random`

## Alternatives

There's not really any alternatives to this. Please add this much demanded feature 🙏

**Comment by yoni2356** [comment]
See these discussions.
The feature you've specified is missing.
There are some workarounds though.

https://github.com/prisma/prisma/discussions/5886
https://github.com/prisma/prisma/issues/5894

**Comment by TPME** [comment]
I've tried the "skip" workaround, unfortunately it didn't really work for me somehow.

It would be great to have the feature implemented.

**Comment by yoni2356** [comment]
@TPME notice you can use queryRaw from prisma api.
Stored procedure would do the trick to I presume.
