### ISSUE TITLE
Prisma not loading environment variables from .env file

### ISSUE THREAD

**Issue by arturenault** [prisma/prisma#10095]
### Bug description

I recently moved to a new machine. In my previous machine, we used several .env files along with serverless-offline to read and set environment variables from several .env files. Locally we use .env.local.

After moving to the new machine, all environment variables still work except those used within Prisma.

When using .env.local, I see Prisma failing to find the files:
```
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables not found at undefined +1ms
  prisma:tryLoadEnv No Environment variables loaded +0ms
```

When I try creating a symlink from .env to .env.local, Prisma is able to find the file:
```
  prisma:tryLoadEnv Environment variables loaded from /Users/artur/Developer/niftory/niftory-services/.env +0ms
``` 

However, none of the variables in that file get picked up by .env, because they're already set in `process.env`:
```
[dotenv][DEBUG] "POSTGRES_URL" is already defined in `process.env` and will not be overwritten
``` 

Our schema expects a POSTGRES_URL:
```
datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}
```

It's definitely set in the process. Here's a log right before the prisma call:
``` 
process.env.POSTGRES_URL: postgresql://postgres:<password-redacted>@localhost:5432/niftory-db
```

But the result is that Prisma connects to postgres on a random port:
```
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED ::1:50082
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '::1',
  prisma:engine     port: 50082
  prisma:engine   }
  prisma:engine } +5ms
 ```

I've tried regenerating the clients several times with .env files in all possible locations, this causes no change in the generated code.

Is this a known issue? Is there a known workaround for this?

Thanks in advance.

### How to reproduce

Start an app with a prisma client, with a .env file loaded by the environment and by Prisma itself (the same file).
Prisma doesn't load any of the environment variables.

### Expected behavior

Prisma should load the environment variables.

### Prisma information

``` 
datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
``` 

The rest of the schema is just models, which don't seem relevant to this problem. Please let me know if any other information would be helpful.

### Environment & setup

- OS: macOS Monterey (M1)
- Database: PostGresURL
- Node.js version: v17.01

### Prisma Version

```
❯ yarn prisma --version
yarn run v1.22.17
$ /Users/artur/Developer/niftory/niftory-services/node_modules/.bin/prisma --version
Environment variables loaded from .env
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : darwin
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

**Comment by arturenault** [comment]
I was actually just able to fix this by downgrading to node 16.13. Keeping this open so we can fix the behavior in 17.01.

**Comment by pinalbhatt** [comment]
strange is i am seeing this error in NodeJS 16.13.0 but works fine when i downgrade it to 16.12.0

**Comment by rockmanvnx6** [comment]
I'm experiencing the same thing on node `14.17.4`. Same node version but prisma can read environment on MacOS not Linux.

**Comment by janpio** [comment]
>   prisma:engine {
>   prisma:engine   error: Error: connect ECONNREFUSED ::1:50082
>   prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
>   prisma:engine     errno: -61,
>   prisma:engine     code: 'ECONNREFUSED',
>   prisma:engine     syscall: 'connect',
>   prisma:engine     address: '::1',
>   prisma:engine     port: 50082
>   prisma:engine   }
>   prisma:engine } +5ms

This is an _unrelated_, internal error message that has _nothing_ to do with PostgreSQL, the database or environment variables at all.

This is an issue about this problem: https://github.com/prisma/prisma/issues/9903

What in this issue is called `Query Engine engineType=binary` was the default engine type in Prisma 2.x. So the solution to this problem is to upgrade to Prisma 3.x or keep using an older version of Node and not the cutting edge right now.

@rockmanvnx6 That sounds unrelated, especially if it is influenced by the operating system you are using. Can you please open a new bug report for this and include all the information the bug issue asks for? Thanks. We want to handle that separately and definitively look into what is going on there.

**Comment by Jolg42** [comment]
I would think it's likely unrelated to 16.13 because there are no code changes in that version, it's the same code as 16.12 but promoted as LTS 
https://github.com/nodejs/node/compare/v16.12.0...v16.13.0
