### ISSUE TITLE
Add timing information to Migration CLI output

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10106]
## Problem

When the number of migrations files goes up, the duration of the Migration CLI processes also goes up. (Example: https://github.com/prisma/prisma/issues/9888) Right now users (and we) do not have a good way to measure what is taking how long during that process.

## Suggested solution

We should make sure to output timings in the logs that can be enabled. At the end you should be able to have a pretty good overview what happens during the migration process is running.

## Alternatives

None really. Maybe you could enable all logging and manually log the timestamps for each output and then do some match in your head what belongs together and then calculate timings for these units.

## Additional context

- https://github.com/prisma/prisma/issues/9888t the feature request here.

**Comment by tomhoule** [comment]
Decision: in the debug logs, when applying migrations, we output:

- The time each migration took to apply
- The total time for applying all migrations
