### ISSUE TITLE
Prisma not disconnecting after jest run (NestJs project)

### ISSUE THREAD

**Issue by Brendan-Stubbs** [prisma/prisma#10119]
### Bug description

I am running end to end tests against a psql database using Jest in a NestJs project. The test runner does not seem to be closing the Prisma connection upon completion.. I am seeing the following warning.

```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

If I add the --detectOpenHandles flag i see the following:
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

```
  TCPSERVERWRAP

      22 |   it('It should create a dummy org', async () => {
      23 |     const { body } = await request(app.getHttpServer())
    > 24 |       .post('/organizations')
         |        ^
      25 |       .expect(201);
      26 |     expect(body).toHaveProperty('organizationId');
      27 |   });

      at Test.Object.<anonymous>.Test.serverAddress (../node_modules/supertest/lib/test.js:61:33)
      at new Test (../node_modules/supertest/lib/test.js:38:12)
      at Object.obj.<computed> [as post] (../node_modules/supertest/index.js:27:14)
      at Object.<anonymous> (recreate.e2e-spec.ts:24:8)
```

This issue was not present when I was using TypeOrm, but after making the move to Prisma I started seeing it

_The below is just additional information of a side effect caused by this, and is not part of the reproduction steps so I am not including the stack trace_
I was getting around this issue by using the forceExit flag so that my CI pipeline could at least pass, however I have gotten to a point where there are too many connections, and my tests start throwing errors. The following error is what I am seeing:

`Error: Error querying the database: db error: FATAL: sorry, too many clients already
`

### How to reproduce

1. Clone the [repository](https://github.com/Brendan-Stubbs/prisma-connection-bug-reproduction): 
2. run `npm install`
3. run `docker-compose up -d`
4. run `npm run test:e2e`

### Expected behavior

The test runner should exit gracefully

### Prisma information

This is all in the docker file included in the repo

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v12.10.0

_The issue is also occurring on my circle ci build, using node: circleci/node@4.1 and image: ubuntu-1604:202007-01_

### Prisma Version

```
2.30.0
```

**Comment by TasinIshmam** [comment]
Hey @Brendan-Stubbs  :wave:  

I cloned your repository and was able to replicate the issue (jest hangs with unfinished asynchronous operations). I made two tweaks that seem to have fixed the problem, at least locally for me. Here's what I did:


1. Changed the definition of `prismaService` to this: 
```typescript
// prisma.service.ts
@Injectable()
export class PrismaService extends PrismaClient {
  constructor() {
    super();
  }
}
```
2. Initialized prisma and explicitly disconnected in afterAll  during teardown
```typescript
// recreate.e2e-spec.ts
describe('Recreate Bug', () => {
  let app: INestApplication;
  let prismaService: PrismaService;  // CHANGE

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
      providers: [PrismaService],

    }).compile();

    app = moduleFixture.createNestApplication();
    prismaService = moduleFixture.get(PrismaService);  // CHANGE: created an instance of prismaService

    await app.init();
  });

  afterAll(async () => {   
    await prismaService.$disconnect();  // CHANGE
    await app.close();
  });

  it('It should create a dummy org', async () => {
    const { body } = await request(app.getHttpServer())
      .post('/organizations')
      .expect(201);
    expect(body).toHaveProperty('organizationId');
  });
});
```

Would you please verify if this works for you?

**Comment by Brendan-Stubbs** [comment]
@TasinIshmam Yes these seems to have worked on my side too. Thanks
Would there be a way of doing this in a teardown file, to avoid repeating all that boilerplate in all my tests?

**Comment by TasinIshmam** [comment]
@Brendan-Stubbs  awesome, glad to hear it's working now :D 

> Would there be a way of doing this in a teardown file, to avoid repeating all that boilerplate in all my tests?

I just tried a few things with the `setupFilesAfterEnv` config in `Jest` but unfortunately without much luck. I think this _should_ be possible, but I can't speak with confidence at the moment as to how exactly without understanding the underlying problem a bit better. 

I'll be sure to let you know if I find something!

**Comment by Brendan-Stubbs** [comment]
@TasinIshmam I tried to incorporate this into my actual project, and it did not work. However I did see the notification to update to the new major version (To be precise ^3.4.2"). This seems to have fixed the problem 100% Without the need for your suggestion above.

Thanks very much for your help, I put this issue off for too long, and I am super happy I have finally overcome it.

**Comment by janpio** [comment]
Can you also reproduce this change in behavior @TasinIshmam with the most recent update?

**Comment by TasinIshmam** [comment]
>  However I did see the notification to update to the new major version (To be precise ^3.4.2"). This seems to have fixed the problem 100% Without the need for your suggestion above.

@Brendan-Stubbs  That's good to know! Please feel free to get back to us if you face this again. 


> Can you also reproduce this change in behavior @TasinIshmam with the most recent update?

Hey @janpio, yep can confirm. Issue no longer occurs in the reproduction repo provided after upgrading to `3.4.2`. Should I close this issue?

**Comment by janpio** [comment]
Yep, done.
