### ISSUE TITLE
"Query Engine" misreported as `0.1.0` in basic error reports from Prisma Client

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10125]
Recently the basic error reports we get via the generated GitHub link when something goes wrong in Prisma Client started misreporting the "Query Engine" version as `0.1.0`:

https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22topic%3A+basic+error+report%22+

https://github.com/prisma/prisma/issues/9933
https://github.com/prisma/prisma/issues/9896
https://github.com/prisma/prisma/issues/9875

That is unfortunate, as this information of course sometimes could be helpful to debug problems.

**Comment by dpetrick** [comment]
Example of old reporting using an engine hash: https://github.com/prisma/prisma/issues/5825
