### ISSUE TITLE
Applying migrations to MariaDB (running directly on macOS) unreasonably slow

### ISSUE THREAD

**Issue by floelhoeffel** [prisma/prisma#10130]
### Bug description

We have user reports of unusually slow migrations with MariaDB on OSX. We did investigate and found the following timings for working with 100 migrations:

**Linux**
- `migrate deploy` 22s
- `migrate dev` 1m30s
- single sql command to db, 6ms
 
**Mac**
- `migrate deploy` 3m25s
- `migrate dev` 10m34s
- single sql command to db 28ms

Napkin math: `deploy` issues 3 mysql commands under the hood, so 3 x 28ms X 100 migrations ~ 10s but what we see is > 600s on mac

### Environment & setup

- OS:  OSX 12.01
- Database:  MariaDB 10.6.4
- Node.js version: v17.0.1

### Prisma Version

```
prisma                  : 3.4.0
@prisma/client          : 3.4.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85
Studio                  : 0.438.0
```

**Comment by kepelrs** [comment]
Hi,

I came across this issue after a few hours struggling against the sudden slow down of my `prisma migrate dev` in MySQL.

Turns out in my case it was due to using the docker's "new Virtualization framework" setting, which currently seems to have very poor disk IO. Turning it off resolved it for me. Not sure you guys are running the test through docker though...

My environment:

M1 MacBook air
macOS 12.0.1 Monterey
Prisma 3.5.0
Node 14.17.5
MySQL 8.0.26

**Comment by amcjen** [comment]
@kepelrs Interesting. I don't run mine through any virtualization unfortunately--it's all on the machine directly (also an M1 Mac).

**Comment by floelhoeffel** [comment]
Interesting @kepelrs - thanks for sharing. My tests were neither running from a container and I don't have an M1 (yet 😅).

**Comment by floelhoeffel** [comment]
Summary: We spent some time on this and are fairly sure this is due to slow I/O on Mac with MariaDB. The easiest way to mitigate is to run MariaDB inside a docker container and make sure to **not** use the "Virtualization Framework" option.

The problem gets amplified as `migrate dev` does certain things multiple times and we are considering improving that in the future but we unfortunately don't have a timeline.

@amcjen would it be an option for you to give the docker workaround a go?

**Comment by amcjen** [comment]
@floelhoeffel Ah, interesting. Yes, I believe we can give the docker workaround a go. Will report back if we continue to have performance problems. Thank you for digging into this one for us!

**Comment by amcjen** [comment]
Moved over to a MariaDB Docker instance and indeed it is much much faster than before. We'll move ahead with this approach--thank you for all your help, glad migrations are back to about 10 seconds instead of 15 minutes!  🙌

**Comment by floelhoeffel** [comment]
That's quite the speed bump 😅 Glad that using docker is working for you.
