### ISSUE TITLE
Prisma not working with Doppler environment variables

### ISSUE THREAD

**Issue by kelvinzage** [prisma/prisma#10140]
Hey everyone, I have an issue with using Primsa ORM + Doppler secret management. To initialize my Postgres db via Prisma, I have to connect to the db via a schema.prisma file. You can either provide a raw URL string or an env variable with the env() command. Here's how my datasource looks:

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
```

This works if DATABASE_URL is defined in a .env file in my local repo. However, I'm using Doppler secret management to insert env variables in at runtime. If I remove the .env file then Prisma throws an `Environment variable not found` error because it can't fetch the env variable from Doppler. All my other Doppler env variables work in my other files by calling `process.env.ENV_VAR_NAME`, so I'm not sure how to load doppler env variables in before schema.prisma runs.

Here's my current package.json script, which runs doppler before prisma: `doppler run -- prisma generate --schema=./infrastructure/database/schema.prisma && prisma migrate dev --name=updateModel --schema=./infrastructure/database/schema.prisma`

**Comment by janpio** [comment]
If you get `Environment variable not found` for the `DATABASE_URL` env var from Prisma, then it is not set in the environment. Are you sue it is set correctly for when you call `prisma generate`? (You should be able to check and output with `echo` as an additional command before the `prisma` command)

**Comment by kelvinzage** [comment]
@janpio Thank you, I fixed it! The error was in a script I wrote called `updatePrisma` that handled generating the client and migrating db changes.

Original script:
`doppler run -- prisma generate --schema=./infrastructure/database/schema.prisma && prisma migrate dev --name=updateModel --schema=./infrastructure/database/schema.prisma`

New, working script:
`prisma generate --schema=./infrastructure/database/schema.prisma && doppler run -- prisma migrate dev --name=updateModel --schema=./infrastructure/database/schema.prisma`

**Comment by janpio** [comment]
Ohhhh, that first one only provided the env var to the `prisma generate` call, but not `migrate dev` that was then complaining. I missed that in the command you posted. Nice you figured it out!
