### ISSUE TITLE
JSONValue not accepting readonly array or objects

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma#10165]
### Bug description

Due to code bellow
```ts
export type InputJsonObject = {[Key in string]?: JsonValue}

export interface InputJsonArray extends Array<JsonValue> {}

export type InputJsonValue = string | number | boolean | InputJsonObject | InputJsonArray
```

```
Type 'readonly ImmutableObject<{ lat: number; lng: number; }>[]' is not assignable to type 'InputJsonValue'.
  Type 'readonly ImmutableObject<{ lat: number; lng: number; }>[]' is not assignable to type 'InputJsonArray'.ts(2322)
```

### How to reproduce

1. Create a model with JSON column
2. Try to create a row in it using read-only object/array
3. See error

### Expected behavior

The input of JSON definitely should accept read-only values.

If the JSON input types were read-only, then updating JSON columns of a table would accept read-write and read-only values!

```ts
export type InputJsonObject = {readonly [Key in string]?: JsonValue}

export interface InputJsonArray extends Readonlyarray<JsonValue> {}

export type InputJsonValue = string | number | boolean | InputJsonObject | InputJsonArray
```

### Environment & setup

- OS: Windows 11
- Database: MySQL
- Node.js version: v14.15.4

### Prisma Version

```
prisma                  : 3.4.1
@prisma/client          : 3.4.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
```

**Comment by janpio** [comment]
What error are you getting when exactly?

**Comment by Akxe** [comment]
The error is:

```
Type 'readonly ImmutableObject<{ lat: number; lng: number; }>[]' is not assignable to type 'InputJsonValue'.
  Type 'readonly ImmutableObject<{ lat: number; lng: number; }>[]' is not assignable to type 'InputJsonArray'.ts(2322)
```

But as said, if I make the changes in the index.d.ts in `prisma/client` it disappears :)

**Comment by matthewmueller** [comment]
I'm having a hard time reproducing this issue on 3.4.1. I'm not seeing any typescript errors. Do you mind sharing an example?

Given the following schema:

**Test Script**

```ts
import { PrismaClient } from "@prisma/client"
const prisma = new PrismaClient()

const meta: { readonly [Key in string]: string } = {
  a: "b",
}

async function main() {
  prisma.post.create({
    data: {
      id: "",
      title: "",
      userId: "10",
      meta: meta,
    },
  })
}

main().catch(console.error)
```

**Prisma Schema**

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  posts Post[]
  name  String
}

model Post {
  id     String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  author User   @relation(fields: [userId], references: [id], onDelete: Cascade)
  title  String
  userId String @db.ObjectId
  meta   Json
}
```

**Comment by Akxe** [comment]
@matthewmueller Did not expect object to work, but array is still a problem; `const meta = [{ a: "b" }] as const` will do the job (error)

**Comment by aqrln** [comment]
I also only checked `ReadonlyArray`s when reproducing, so thanks for noticing that. Not sure if it’s a bug or expected behavior in TypeScript, but I’m surprised this typechecks: https://www.typescriptlang.org/play?#code/C4TwDgpgBAsgrsAhgIwDYQMrAE5wMbBQC8UA3gFBRVQBuiqcEAXFAM44CWAdgObkC+5cqEhQAkgFsJCFOiy4CxMpWrYIiACYB7LqhC16jFu2zc+g8gDM4XAhx1Q4YDYmAQAFCfzAW8JGkwcbwBKZWo2IIIAOjoGaBIAcicXNw0EgSE8HXYoDikZAJZJaX85SMISCnDYoygEtU0dPXSLZNcPPJLZCGDyIA

**Comment by matthewmueller** [comment]
Got it, thanks! I'm able to reproduce the fix with

```ts
import { PrismaClient } from "@prisma/client"
const prisma = new PrismaClient()

const meta = [
  {
    a: "b",
  },
] as const

async function main() {
  prisma.post.create({
    data: {
      id: "",
      title: "",
      userId: "10",
      meta: meta,
    },
  })
}

main().catch(console.error)
```

Also TIL `as const` 🙌

**Comment by Akxe** [comment]
> I also only checked `ReadonlyArray`s when reproducing, so thanks for noticing that. Not sure if it’s a bug or expected behavior in TypeScript, but I’m surprised this typechecks: https://www.typescriptlang.org/play?#code/C4TwDgpgBAsgrsAhgIwDYQMrAE5wMbBQC8UA3gFBRVQBuiqcEAXFAM44CWAdgObkC+5cqEhQAkgFsJCFOiy4CxMpWrYIiACYB7LqhC16jFu2zc+g8gDM4XAhx1Q4YDYmAQAFCfzAW8JGkwcbwBKZWo2IIIAOjoGaBIAcicXNw0EgSE8HXYoDikZAJZJaX85SMISCnDYoygEtU0dPXSLZNcPPJLZCGDyIA

This must be a bug... It simple violates the contract of read only type...

**Comment by aqrln** [comment]
@Akxe 

> It simple violates the contract of read only type...

Yes, but also the type system in TypeScript isn't exactly sound by design. While this behavior isn't documented among other intentionally unsafe properties in https://www.typescriptlang.org/docs/handbook/type-compatibility.html, these passages from https://www.typescriptlang.org/docs/handbook/2/objects.html indicate that it's a known and expected behavior too:

> It’s important to manage expectations of what readonly implies. It’s useful to signal intent during development time for TypeScript on how an object should be used. TypeScript doesn’t factor in whether properties on two types are readonly when checking whether those types are compatible, so readonly properties can also change via aliasing.

(https://www.typescriptlang.org/docs/handbook/2/objects.html#readonly-properties)

> One last thing to note is that unlike the readonly property modifier, assignability isn’t bidirectional between regular Arrays and ReadonlyArrays.

(https://www.typescriptlang.org/docs/handbook/2/objects.html#the-readonlyarray-type)
