### ISSUE TITLE
Add option to skip loading `.env` file

### ISSUE THREAD

**Issue by remorses** [prisma/prisma#10162]
## Problem

I want to run `prisma studio` with environement variables defined in my shell instead of the ones defined in the `.env` file

I should be able to run `DATABASE_URL=... prisma studio` to overwrite the variables in .env file

## Suggested solution

Add a `--skip-env` option to the root prisma command to skip loading the `.env` file

**Comment by janpio** [comment]
That does not work? Usually the tooling we are using internally to load the `.env` file should not overwrite already existing env vars.

**Comment by remorses** [comment]
Yes, sorry it already works

My problem was that i wasn't loading the env in the shell, but actually you don't really want to load sensible env vars in the shell, so i changed my approach and ended up using this

```
dotenv -e ./.env.production `npm bin`/prisma studio
```

I feel like prisma could make this easier  adding a way to load a different `.env` file
