### ISSUE TITLE
Prisma does not support npm workspaces with multiples services with different databases

### ISSUE THREAD

**Issue by dborstelmann** [prisma/prisma#10170]
### Bug description

I can't have two services with separate prisma dbs in the same repo with npm workspaces.

TS Compiler only respects node_modules/.prisma which only has the latest generate (from whichever service was generated last) which means TS compilation fails on any resolver, etc.

I think I can get it to work in ci/cd by cleaning the .prisma folder all the time between deploying the different services but for development TS has no idea what to do.

Related to:
https://github.com/prisma/prisma/issues/9649

### How to reproduce

Make a new project with npm workspaces.

Note: `"generate": "prisma generate"` script in submodules
package.json
packages/foo/prisma/schema.prisma (foo service db)
packages/foo/package.json (prisma client installed here)
packages/bar/prisma/schema.prisma (bar service db)
packages/bar/package.json (prisma client installed here)
packages/baz/package.json (maybe some frontend service)

2 issues:
1. Run `npm run generate --workspaces`
    - This works, but node_modules/.prisma is just `bar` because it overwrote `foo`
2. Run `npm run generate` from a submodule (`cd packages/foo`)
    - This works too, but it creates a new packages/foo/node_modules/.prisma which is useless and not respected by TS compiler for example

### Expected behavior

.prisma node_module should respect multiple npm workspaces

### Prisma information

Any schema

### Environment & setup

- npm7 and above with workspaces

### Prisma Version

```
prisma                  : 3.4.1
@prisma/client          : 3.4.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
```

**Comment by pantharshit00** [comment]
Try using custom output if you want to have multiple clients: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#using-a-custom-output-path since only one client can live in `node_modules`.

I can't find `nohoist` option in npm workspaces docs which used to be available in yarn v1 workspaces which might be the solution here. If you know of any such option available, please let me know.

**Comment by dborstelmann** [comment]
Sounds good thanks I'll give this a shot and report back

**Comment by dborstelmann** [comment]
Ok this solved it for me, and is a fine solution for the long term.  Unless there is something else related to npm workspaces you want to leave this open for, then feel free to close this!  Thanks.

**Comment by SevInf** [comment]
@dborstelmann could you try with more recent prisma version? We fixed quite a lot of workspace issues in 4.x versions. Thank you!

**Comment by dborstelmann** [comment]
I'm no longer working on the project but I appreciate it thank you!
