### ISSUE TITLE
Suggestions/Recommendations for schema validation / VS Code extension

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#10173]
## Problem

An example where this could be useful is here:
> When `referentialIntegrity` is set to `prisma`, foreign keys are not created which means that no index is created for the relation scalar leading to table scans.

## Suggested solution

We could recommend to add an index on the relation scalars: 
https://github.com/prisma/prisma/issues/7292#issuecomment-963118192

In both in VS Code extension and Validation (`prisma validate` and `prisma format`)

## Alternatives

Documentation

## Additional context

This ended up costing $5000 in 5 days: https://briananglin.me/posts/spending-5k-to-learn-how-database-indexes-work/

**Comment by janpio** [comment]
This happened in 4.7.0 and we now have nice warnings, squiggly lines and even a quick fix: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/relation-mode#indexes
