### ISSUE TITLE
Typing for transaction doesn't include async function argument

### ISSUE THREAD

**Issue by jeremygottfried** [prisma/prisma#10188]
### Bug description

The following code is documented [here](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#example) 
```ts
await prisma.$transaction(async (prismaClient) => {
 ...
})
```

But typescript doesn't recognize it.

```sh
Argument of type '(prismaClient: any) => Promise<any>' is not assignable to parameter of type 'PrismaPromise<any>[]'. Type '(prismaClient: any) => Promise<any>' is missing the following properties from type 'PrismaPromise<any>[]': pop, push, concat, join, and 27 more.
Parameter 'prismaClient' implicitly has an 'any' type.

```

### Expected behavior

I expect typings to match all features offered by the library.

### Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["nativeTypes"]
  binaryTargets   = ["native", "rhel-openssl-1.0.x"]
}
```

### Environment & setup

- OS: MacOS Catalina 10.15.7
- Database: Postgresql
- Node.js version: 12.22.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.4.2
@prisma/client          : 3.4.2
Current platform        : darwin
```

**Comment by wma-alvin** [comment]
Have you enabled `interactiveTransactions`? https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions-in-preview

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}
```

**Comment by jeremygottfried** [comment]
Ah thank you! I knew I must have been missing something

**Comment by edwin177** [comment]
Future readers, make sure to generate types for Prisma Client after setting previewFeatures.
