### ISSUE TITLE
Prisma is loading `DATABASE_URL` from .env file even if `DATABASE_URL` is already in the shell environment

### ISSUE THREAD

**Issue by remorses** [prisma/prisma#10185]
### Bug description

Prisma is loading `DATABASE_URL` from .env file even if `DATABASE_URL` is already in the shell environment

### How to reproduce

https://github.com/remorses/prisma-overwrites-env

### Expected behavior

I should be able to overwrite `DATABASE_URL`

### Prisma information

Not relevant

### Environment & setup

- OS: Mac
- Database: 
- Node.js version: v16.13.0

### Prisma Version

```

Environment variables loaded from .env
prisma                  : 3.4.2
@prisma/client          : 3.4.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at ../../../.nvm/versions/node/v16.13.0/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at ../../../.nvm/versions/node/v16.13.0/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at ../../../.nvm/versions/node/v16.13.0/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at ../../../.nvm/versions/node/v16.13.0/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
```

**Comment by janpio** [comment]
Just a note if someone finds this later: Prisma's loading from `.env` file via `dotenv` would _not_ load already existing env vars but skip those.

**Comment by remorses** [comment]
Yes, i was really tired and mispelled the `.env` file name passed to `dotenv-cli`, notice that `dotenv-cli` will load the `.env` file if the file passed with `-e <file>` does not exist

**Comment by janpio** [comment]
That is pretty surprising (and bad) behavior from `dotenv-cli` 😢
