### ISSUE TITLE
Data Proxy Client should't need to be re-generated after modifying `.env` files

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#10187]
This behavior differs from the one of the regular Client runtime.

https://prisma-company.slack.com/archives/C016KUHB1R6/p1636376266020500

**Comment by pfried** [comment]
This issue clearly lacks context as non members cannot see the archived conversation

**Comment by millsp** [comment]
When using the `dataproxy`, we actually generate a special client that is is able to work in two kinds of runtime, a browser-like runtime like Cloudflare Workers as well as Node.js. Since they share the same runtime and since browsers don't have access to `fs`, the choice to embed the `env` and some other meta-data was made. While this is a pre-requisite at generation time, it is not at runtime. And since we are able to detect runtimes, this would be an improvement.

**Comment by pfried** [comment]
@millsp The issue with this is that it is not possible to inject the correct endpoint as of this bug (at least I think it is a bug): https://github.com/prisma/prisma/issues/11458

Baking in the environment raises security concerns if you package the prisma client (what we do for our aws-lambdas in a lambda layer)

A practical issue is that you cannot use the `prisma://` url for migrating and other stuff, so you will have an environment variable locally pointing directly to `postgres://` and a `prisma://` url in your functions pointing to dataproxy.

**Comment by millsp** [comment]
It is able to find environment variables though, if the env var is also available through `process.env` then it will load it.

**Comment by pfried** [comment]
afaik it does not, see #11458

**Comment by pfried** [comment]
Okay I have to revert that, it does, but the thing is it does on loading the module not on client instantiation

```
process.env['DATABASE_URL'] = "prisma://aws-eu-central-1.prisma-data.com/?api_key=ABC"
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({})
```

works, this does not:

```
import { PrismaClient } from '@prisma/client'
process.env['DATABASE_URL'] = "prisma://aws-eu-central-1.prisma-data.com/?api_key=ABC"
const prisma = new PrismaClient({})
```

**Comment by millsp** [comment]
Note for users finding this:

We have released some changes a few minutes ago in [prisma@3.15.0](https://github.com/prisma/prisma/releases). tl;dr;
* Instead of `PRISMA_CLIENT_ENGINE_TYPE`, use `prisma generate --data-proxy` to enable the Data Proxy
* `import { PrismaClient } from '@prisma/client/edge'` for a Workers compatible Prisma Client
* Please be aware that `.env` aren't bundled into the generated Prisma Client any longer ([see docs](https://www.prisma.io/docs/concepts/data-platform/data-proxy#edge-runtimes))
* You can also remove any package location aliasing from your build scripts
* Warnings around `eval` are now also fixed
