### ISSUE TITLE
Generate migrations without applying them

### ISSUE THREAD

**Issue by vincentrolfs** [prisma/prisma#10198]
## Problem

`prisma migrate dev` allows one to generate new migrations and apply them. But often one needs to manually modify the migrations, for example in order to deal with missing default values or other details.

## Suggested solution

There should be a command `prisma migrate generate` that only generates the migrations without applying them.

**Comment by janconc** [comment]
How about the existing `prisma migrate dev --create-only` ?

**Comment by pantharshit00** [comment]
Indeed you can create migrations without applying them using the `--create-only` flag as @janconc mentioned. 

I am going to close this. Comment if you don't think this covers your usecase.
