### ISSUE TITLE
PrismaClientValidationError thrown, but without an error Code, only message

### ISSUE THREAD

**Issue by gheorghemolnar** [prisma/prisma#10221]
### Bug description

I'm experiencing an issue concerning prisma client that throws an erorr message, when creating a record with a required field missing: the error is an object with constructor name = 'PrismaClientValidationError', it has an error message, but no code.

### How to reproduce

1. On the joined Prisma model
2. Calling db.companies.create in order to create a Company, like this:
	  ```
	  const response: Companies = await db.companies.create({
	              data: {
	                  ...companyCreateDto,
	              }
	          });`
	  ```

3. Run it with the following data: (Notice the missing 'company_name' which is required on the model, from the data):
	  ``` 
	  companyPayload {
	        company_test_name: 'test name Kling, Kohler and Schuppe',
	        company_child_id: [],
	        company_membership: 'IVORY,
	        company_order_id: [],
	        company_parent_id: [],
	        company_registration: 2011-10-07T02:58:29.760Z,
	        company_share_capital: 14430,
	        company_siren: '535662000',
	        company_siret: '535662000 32608',
	        company_tva: 'FRKN443449584',
	        company_type: 'SA',
	        company_is_visible: false,
	        company_is_retailer: false,
	        company_address_invoice: [],
	        company_address: [
	          {
	            address_name: 'June Road',
	            address_label: 'test label June Road',
	            address_housenumber: '75',
	            address_postcode: '19636',
	            address_citycode: '91047',
	            address_city: 'Lake Louie',
	            address_context: '12 etage',
	            address_type: 'c',
	            address_street: 'Velma Ramp',
	            address_coordinates: [Array],
	            address_district: '1e'
	          }
	        ]
	      }
	      ```
	  -->
	  <img width="1130" alt="Screenshot 2021-11-11 at 21 23 57" src="https://user-images.githubusercontent.com/12073002/141364004-7a7999bd-2241-44c8-bc3a-935ec35e6ece.png">

### Expected behavior

To throw an error PrismaClientValidationError, with a message AND an error code. The error 'PrismaClientValidationError' thrown does not have a error code !

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native","darwin"]
  previewFeatures = ["interactiveTransactions", "filterJson"]
  output = "../../../../node_modules/@prisma/client/company"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Companies {
  id                                         String   @id @default(uuid())
  company_test_name           String?
  company_name                   String
  company_address               Json[]
  company_address_invoice     Json[]
  company_membership          String?
  company_child_id            String[]
  company_order_id            String[]
  company_parent_id           String[]
  company_registration        DateTime?
  company_share_capital       Int?
  company_siren               String?
  company_siret               String?
  company_tva                 String?
  company_type                String?
  company_is_retailer         Boolean @default(false)
  company_is_visible         Boolean @default(false)
  company_created_at          DateTime @default(now())
  company_updated_at          DateTime @updatedAt
  authorization               Companies_Authz?
}


model Companies_Authz {
  id                        String   @id @default(uuid())
  access                    Json
  created_by                String
  updated_by                Json[]
  created_at                DateTime  @default(now())
  company_id               String    @unique
  company                  Companies @relation(fields: [company_id], references: [id], onDelete: Cascade)
}
```

### Environment & setup

- OS: Mac OS BigSur 11.6
- Database: PostgreSQL
- Node.js version: v16.6.1

### Prisma Version

```
prisma                  : 3.4.2
@prisma/client          : 3.4.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/.pnpm/@prisma+engines@3.4.1-2.57771c0558568c7d08bd34c7248af5244ae16bd9/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/.pnpm/@prisma+engines@3.4.1-2.57771c0558568c7d08bd34c7248af5244ae16bd9/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/.pnpm/@prisma+engines@3.4.1-2.57771c0558568c7d08bd34c7248af5244ae16bd9/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/.pnpm/@prisma+engines@3.4.1-2.57771c0558568c7d08bd34c7248af5244ae16bd9/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
```

**Comment by janpio** [comment]
Can you log the full error/err object you are getting please @gheorghemolnar? 
What is the easiest way to reproduce this?

**Comment by gheorghemolnar** [comment]
here you go:
![Screenshot 2021-11-16 at 09 53 12](https://user-images.githubusercontent.com/12073002/141954738-a3b2743b-e34b-4002-9e79-3dbf4a342505.png)

**Comment by janpio** [comment]
Hmm, reading our docs I don't think `PrismaClientValidationError` is _supposed_ to have an error code: https://www.prisma.io/docs/reference/api-reference/error-reference#prismaclientvalidationerror Those error types should usually be fixed on development time, and not reacted to during runtime of your app, so an error code is not really necessary there.

**Comment by gheorghemolnar** [comment]
Maybe I would have expected an error code like the other error messages ('Pxxx'). The documentation it's not very clear, in my opinion, as it is mentioned :
`
message | Error message associated with error code.

`

**Comment by janpio** [comment]
You are absolutely right! That is a bug in our documentation, probably copy/paste between the different exception types. Here is a PR fixing that: https://github.com/prisma/docs/pull/2530

This issue also started a discussion that we probably want to have better error messages, error types and possibly also error codes - but that is a long term project and not a current focus. If you want, go ahead and open a feature request for this topic though so we can track it and will not forget. Would appreciate it.
