### ISSUE TITLE
`undefined` in `where` query

### ISSUE THREAD

**Issue by ghost** [prisma/prisma#10220]
### Bug description

If `undefined` is specified in the where query, any record will be returned.

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["fullTextSearch", "interactiveTransactions"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  username String @id
  email String @unique
  password String
  balance Int @default(0)
  referrer String?
  authCode String?
  isAdmin Boolean @default(false)
  isBanned Boolean @default(false)
  isEmailVerified Boolean @default(false)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v16.13.0

### Prisma Version

```
prisma                  : 3.4.1
@prisma/client          : 3.4.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
Preview Features        : fullTextSearch, interactiveTransactions
```

**Comment by janpio** [comment]
Does this not match what is documented at https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined?

**Comment by JameelKhan9** [comment]
If undefined in a where clause returns all records, is there a value that can be used to return none?

**Comment by JameelKhan9** [comment]
@mcbethio if there are emails with empty strings your solution would return those empty email records.

**Comment by RamonSerraVasconcelos** [comment]
Can someone explain why this is the standard prisma behavior? In my vision when you try to find something undefined or empty the query should not return anything.

**Comment by mphill** [comment]
@RamonSerraVasconcelos I am new to Prisma, a web search brought me here because I was wondering how to do conditional queries. 

From a SQL perspective if you do `SELECT * FROM USERS WHERE EMAIL = ''` I think the empty string is legit.

There is no concept of `undefined` in SQL so this is a little confusing what the expected behavior is or if using `undefined` is the recommended way to do conditional `WHERE` statements.

**Comment by janpio** [comment]
> In my vision when you try to find something undefined or empty the query should not return anything.

Something being `undefined` is the same as it not being present in JS.
So when you search for all users with no filter, you will get all users.

We have an issue here to further improve the documentation here: https://github.com/prisma/docs/issues/5041

**Comment by vfernandes0408** [comment]
this solution solved for me


// this returns all records
    let emailSearchUndefined = undefined;
    const firstResults = await prisma.user.findMany({
        where: {
            email: emailSearchUndefined
        },
    })
    
    // this returns no records
    let emailSearch = "";
    const results = await prisma.user.findMany({
        where: {
            email: emailSearch || undefined || null
        },
    })
