### ISSUE TITLE
Prisma logo is Pyramid

### ISSUE THREAD

**Issue by ponWeb** [prisma/prisma#10242]
### Bug description

What the heck. Prisma logo is actually not Prisma at all. It is a pyramid!
Prisma definition:
a solid figure whose sides are parallel and whose two ends are the same in shape and size.
![723298FD-375C-4115-B5B8-79A961AB4C47](https://user-images.githubusercontent.com/88082374/141647674-2141812d-333b-42eb-aa7a-65d9cbc6836c.png)
And you definitely have pyramid on logo.

please fix 🙏

### How to reproduce

Open Prisma Logo

### Expected behavior

Prisma logo

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by rathax** [comment]
lol

**Comment by pantharshit00** [comment]
You are correct in your analogy here but having accurate prism in our logo is not essential for making a good database access tool. I think we are quite happy with our  logo and it is very recognisable which is important for any good logo. 

I would close this as "wontfix" :) 

Thank you so much for your issue!
