### ISSUE TITLE
This error has caused the process to crash！

### ISSUE THREAD

**Issue by youxdd** [prisma/prisma#10283]
### Bug description

This error has caused the process to crash！

```
}
meta: { target: [ 'visitorId', 'masterId' ] }
clientVersion: '3.4.2',
code: 'P2002',
at cb (/app/node_modules/@prisma/client/runtime/index.js:38502:17) {
PrismaClientKnownRequestError: Unique constraint failed on the fields: (`visitorId`,`masterId`)
2021-11-16T01:27:06.656798653Z stderr F 
throw new PrismaClientKnownRequestError(message, e.code, this.prisma._clientVersion, e.meta);
/app/node_modules/@prisma/client/runtime/index.js:38502
```

### How to reproduce

Appeared inexplicably

### Prisma information

```
model VisitorRecord {
  visitorId String
  visitor   User     @relation(fields: [visitorId], references: [id])
  masterId  String
  viewNum   Int
  read      Boolean
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@id([visitorId, masterId])
}
```

### Environment & setup

node 14.15.4

### Prisma Version

3.4.2

**Comment by youxdd** [comment]
![image](https://user-images.githubusercontent.com/17402720/142593421-301dc941-319e-4345-80ab-f3f182bcb06b.png)

Every time this error occurs, then the docker survival check fails, causing the nest.js service to restart！

**Comment by janpio** [comment]
The error message indicates there is already a data entry with the same values:
```
PrismaClientKnownRequestError: Unique constraint failed on the fields: (`visitorId`,`masterId`)
```
Is this not the case or does anything else not make sense?

**Comment by youxdd** [comment]
![image](https://user-images.githubusercontent.com/17402720/142710365-c6c6fa68-6bda-4e43-b5c6-224212b39a08.png)

When i simulate to deposit a unique value, The error log I get is like this.
The two error logs are different, the latter will not cause the process to exit.

**Comment by youxdd** [comment]
The same block of code, why there are two different abnormal output?

**Comment by youxdd** [comment]
@janpio  
The same block of code, why there are two different abnormal output?

**Comment by janpio** [comment]
I unfortunately do not understand. Prisma returns a `PrismaClientKnownRequestError` your application can handle. If it does that, nothing should crash at all. From the last screenshot you posted, it seems like one if on the GraphQL level (first line), then a direct output of the error message (line 2), and then a (probably higher level) exceptions handler does something again (line 3). If the last one makes the application crash, then that could be the configured default behavior of your application on uncaught exceptions. Catching it earlier, probably around the query where you expect possible errors like this, should fix this.

**Comment by youxdd** [comment]
@janpio 
Thank you for your answer. It doesn't seem to be a problem with prisma. I will try other solutions.
