### ISSUE TITLE
findMany() returning null where findFirst() works fine

### ISSUE THREAD

**Issue by thugzook** [prisma/prisma#10284]
### Bug description

Running a `findMany()`  query with a `UserWhereInput` returns a null object. The exact same query structured as a `findFirst()` works fine.

### How to reproduce

**RESOLVER**
```graphql
getTransactionsByUserId: (_, { userId }, ___) => prisma.transaction.findMany({
  where: {
    userId: userId,
  },
}),
```

**RESULT**
```graphql
{
  "data": {
    "getTransactionsByUserId": {
      "id": null,
      "userId": null
    }
  }
}
```

Let's try again with `findFirst()`:
```graphql
{
  "data": {
    "getTransactionsByUserId": {
      "id": "2338f8e2-ebc8-4b59-b8c1-b4859923bc3a",
      "userId": "befb1e17-70c7-42cc-9485-ca6d3138cc1a"
    }
  }
}
```

### Expected behavior

I expected an array with [Transaction] information. Is this expected behavior? I assume this happens because of the @unique field in `User`, but that's a wild guess.

### Prisma information

**SCHEMA**

```graphql
model User {
  id            String          @id @default(uuid())
  email         String          @unique
  transactions  Transaction[] 
}

model Transaction {
  id                    String              @id @default(uuid())
  user                  User                @relation(fields: [userId], references: [id])
  userId                String
}
```

**APOLLO SCHEMA**
```graphql
type User {
  id: String
  email: String
  transactions: [Transaction]
}

type Transaction {
  id: String
  user: User
  userId: String
}

type Query {
  getTransactionsByUserId(userId: String!): Transaction
}
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

OS: Windows
Database: PostgreSQL
Node.js: 14.17.6

### Prisma Version

```
3.3.0
```

**Comment by ArthurThornton** [comment]
@thugzook: This looks like it's due to your Apollo schema expecting to return _a single instance of a Transaction_ but you're actually returning an array; so it looks for the matching `id`, `user`, and `userId` properties from the array and finds they're null/undefined so it sets the response for those fields to `null`. Your response type should actually be `[Transaction]` in that instance.

**Comment by thugzook** [comment]
That's it! Thank you for helping me prisma a bit better.
