### ISSUE TITLE
Madharchod tumera app kam nahi kar raha hai

### ISSUE THREAD

**Issue by rameshchandraben** [prisma/prisma#10300]
### Bug description

ghobharchatta salla burbak log dhang se coding karena nahi aata hai ka tumko

hum jab isse download kiye to humko error bhej rha hai bahut baar kooshish karlia tha humne par tabbhi error mil raha hain npm humko keh raaha hai ki tum prisma ko download nahi kar sakata hai

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by pantharshit00** [comment]
The language you have used here is in complete violation of the [Code of Conduct](https://github.com/prisma/prisma/blob/main/CODE_OF_CONDUCT.md) of this repository so your issue will not be entertained. Please use respective language and learn to properly describe your problem. 

Further repetition of this kind of behavior will result a ban from this space. 

अपनी भाषा पर लगाम लगाए। ये एक ओपन सोर्स प्रोजेक्ट है और हम आपके किसी कर्ज मे नहीं है की आप गली से टिकट की शुरुआत करे। ऐसा वापिस करने पर रिपॉजिटरी इस्तेमाल करने से प्रतिबन्ध कर दिया जायेगा ।
