### ISSUE TITLE
prisma migrate dev: Generate types before seeding

### ISSUE THREAD

**Issue by j0nezz** [prisma/prisma#10350]
### Bug description

We have a seed script written in typescript. When we run `prisma migrate dev` and the DB has to be reset, the seed script fails, because `prisma generate` is executed after the seed script. After the seed fails in `prisma migrate dev`, the types are  generated successfully and the command `prisma db seed` afterwards works fine.

### How to reproduce

Use a typescript seed file, which relies on types from `@prisma/client` and run `prisma migrate dev` after schema changes that require the DB to be cleared (because the seed file will run automatically then).

### Expected behavior

`prisma migrate dev` **first** generates the types, if the DB has to be cleared, so that a typescript seed script does not fail.

### Prisma information

Not schema dependent.

### Environment & setup

Should not be dependent on the environment, because the order of commands is wrong in this case.

### Prisma Version

```
3.5.0
```

**Comment by janpio** [comment]
Potentially we already have a PR for this: https://github.com/prisma/prisma/pull/10343

**Comment by j0nezz** [comment]
Nice! I quickly created a reproduction repo for you: https://github.com/j0nezz/prisma-reproduce-10350

1. Run `prisma migrate dev` on branch `breaking-change`
2. Checkout branch `main`
3. Run `prisma migrate dev` and confirm db reset

Happy weekend and thanks!

**Comment by janpio** [comment]
This should be fixed now - can you please try again and let us know? Thanks.

**Comment by j0nezz** [comment]
yup, it works! Thanks!
