### ISSUE TITLE
`new PrismaClient()` can not find `schema.prisma` file when use with pnpm workspace

### ISSUE THREAD

**Issue by plimeor** [prisma/prisma#10361]
### Bug description

Here is a simple reproduction with [pnpm](https://pnpm.io).

```shell
- packages
  - server
    - index.mjs #  get PrismaClient from prisma-client
    - package.json 
 
  - prisma-client
    - dist # prisma generator output
    - prisma
      - schema.prisma
    - package.json

  - pnpm-workspace.yaml
  - package.json
```

When call `new PrismaClient` in `packages/server/index.mjs`, got an error:

```shell
Error: ENOENT: no such file or directory, open '~/prisma-path-issue/packages/server/node_modules/schema.prisma'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at new LibraryEngine (~/prisma-path-issue/packages/prisma-client/dist/runtime/index.js:36041:40)
    at PrismaClient.getEngine (~/prisma-path-issue/packages/prisma-client/dist/runtime/index.js:39247:16)
    at new PrismaClient (~/prisma-path-issue/packages/prisma-client/dist/runtime/index.js:39218:29)
    at getPrisma (file://~/prisma-path-issue/packages/server/index.mjs:4:18)
    at file://~/prisma-path-issue/packages/server/index.mjs:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '~/prisma-path-issue/packages/server/node_modules/schema.prisma',
  clientVersion: '3.5.0'
}
```

### How to reproduce

(Require global [pnpm](https://pnpm.io) installed)

1. Clone git `https://github.com/mervinjin/prisma-issue`
2. Run `pnpm install`
3. Run `pnpm start`

### Expected behavior

No Error

### Prisma information

Schema file:

```prisma
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}
generator client {
  provider = "prisma-client-js"
  output = "../dist"
}

model User {
  id Int @id @default(autoincrement())
}
```

Usage:
```js
import { PrismaClient } from 'prisma-client'

async function getPrisma(){
  const prisma = new PrismaClient()
  await prisma.$connect()
  return prisma
}

getPrisma().then(console.log)
```

### Environment & setup

- OS: Mac OS
- Database: SQLite
- Node.js version: 17.0.1

### Prisma Version

```
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at ../../node_modules/.pnpm/@prisma+engines@3.5.0-38.78a5df6def6943431f4c022e1428dbc3e833cf8e/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at ../../node_modules/.pnpm/@prisma+engines@3.5.0-38.78a5df6def6943431f4c022e1428dbc3e833cf8e/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at ../../node_modules/.pnpm/@prisma+engines@3.5.0-38.78a5df6def6943431f4c022e1428dbc3e833cf8e/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at ../../node_modules/.pnpm/@prisma+engines@3.5.0-38.78a5df6def6943431f4c022e1428dbc3e833cf8e/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
```

**Comment by andyjy** [comment]
workaround: generate into toplevel `/node_modules/` rather than package `../dist` (https://github.com/prisma/prisma/issues/9435#issuecomment-974576800)

working demo: https://github.com/andyjy/prisma-multiple-schemas-monorepo-demo

**Comment by janpio** [comment]
But the bug still exists with this workaround I assume? Then we should probably keep this issue open and try to get it fixed properly.

**Comment by andyjy** [comment]
@janpio yes, it would be nice to not need the workaround - i.e. be able to specify anywhere for the generator `output=` filesystem location without having the generated client fail unless the combination of generated client location and calling code happens to work with the internals of `syncFind() || __dirname`

**Comment by janpio** [comment]
Shouldn't the goal be that this just works as intended, without any further need to specify anything?

**Comment by millsp** [comment]
Hey @plimeor @andyjy I can confirm that this issue has been fixed. I just ran the repro with `@prisma/client@dev` which works now :). If you want, you can also try it, and please let us know if you find anything unexpected. Thanks!

**Comment by renatoaraujoc** [comment]
> Hey @plimeor @andyjy I can confirm that this issue has been fixed. I just ran the repro with `@prisma/client@dev` which works now :). If you want, you can also try it, and please let us know if you find anything unexpected. Thanks!



> Hey @plimeor @andyjy I can confirm that this issue has been fixed. I just ran the repro with `@prisma/client@dev` which works now :). If you want, you can also try it, and please let us know if you find anything unexpected. Thanks!

This works now, I was facing the same pnpm issue with schema.prisma location!

For now I'll use "@prisma/client@dev" version on package.json and will update later.

**Comment by renatoaraujoc** [comment]
> Hey @plimeor @andyjy I can confirm that this issue has been fixed. I just ran the repro with `@prisma/client@dev` which works now :). If you want, you can also try it, and please let us know if you find anything unexpected. Thanks!



> Hey @plimeor @andyjy I can confirm that this issue has been fixed. I just ran the repro with `@prisma/client@dev` which works now :). If you want, you can also try it, and please let us know if you find anything unexpected. Thanks!

This works now, I was facing the same pnpm issue with schema.prisma location!

For now I'll use "@prisma/client@dev" version on package.json and will update later.

**Comment by janpio** [comment]
Release is planned tomorrow, so shouldn't have to stay there long 👍 Thanks for confirming!
