### ISSUE TITLE
$queryRaw to Postgres failing to correctly insert/cast numeric parameters

### ISSUE THREAD

**Issue by thebend** [prisma/prisma#10424]
### Bug description

When inserting parameters Postgres is meant to interpret as int/float (and maybe others), any time the number is cast to or compared against a differing numeric type, Prisma either throws an error or the value is corrupted.  Trying to cast values explicitly to avoid the problem doesn't work either, in the case of a float parameter when it happens to be a whole number.

```
const [{ id }] = await db.$queryRaw`select ${1.5}::int id`
// Raw query failed. Code: `22P03`. Message: `db error: ERROR: incorrect binary data format in bind parameter 1`

const [{ id }] = await db.$queryRaw`select ${1}::float id`
// id === 5e-324 (MIN_VALUE)

const [{ id }] = await db.$queryRaw`select ${"1"}::float id`
// Raw query failed. Code: `08P01`. Message: `db error: ERROR: insufficient data left in message`
```

The only solution I've found is to convert all numeric types to strings in node, and then explicitly cast to text and then the relevant numeric type in Postgres so far, eg.

```
const [{ id }] = await db.$queryRaw`select ${"1"}::text::float id`
// id === 1
```

### How to reproduce

1. Generate a Prisma client to any Postgres database.
2. Import the client and execute client.$queryRaw\`select ${1.5}::int\`

### Expected behavior

```
const [{ id }] = await db.$queryRaw`select ${1.5}::int id`
// id === 2

const [{ id }] = await db.$queryRaw`select ${1}::float id`
// id === 1

const [{ id }] = await db.$queryRaw`select ${"1"}::float id`
// id === 1
```

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model asset {
  company_no           Int?
  asset_code           String                 @unique
  category_code        String?
  manufacturer         String?
  model                String?
  year                 Int?
  vin                  String?
  license_plate        String?
  description          String?
  active               Boolean?
  id                   Int                    @id @unique @default(autoincrement())
  @@index([active], name: "asset_active_idx")
}
```

### Environment & setup

- OS: Ubuntu 20.04.3 LTS running in WSL on Windows 11
- Database: Tested against both Postgres 12.8 and 13.4.1
- Node.js version: v16.11.1

### Prisma Version

```
3.5.0 and 2.30.3 both tried.
```

**Comment by rokoucha** [comment]
The same problem occurs with `TIME`.

```
const [{ time }] = await db.$queryRaw`select ${"12:34"}::time time`
// Raw query failed. Code: `08P01`. Message: `db error: ERROR: insufficient data left in message`
```

**Comment by Weakky** [comment]
Hey,

This issue was fixed by https://github.com/prisma/prisma-engines/pull/2847. It will be available in the next release under the `improvedQueryRaw` feature flag.

Beware that enabling `improvedQueryRaw` is a breaking change. Release notes will contain information as to how to upgrade (so will the documentation).

Thanks for reporting 🙏
