### ISSUE TITLE
Quickstart isn't working (no explanation of how to add DATABASE_URL to env)

### ISSUE THREAD

**Issue by ezalivadnyi** [prisma/prisma#10431]
### Bug description

I'm following the Quickstart example on the official site and get an error after running `npm run dev`

```

> script@ dev /prisma
> ts-node ./script.ts

(node:190106) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.user.findMany()` invocation in
/prisma/script.ts:7:40

   4 
   5 // A `main` function so that you can use async/await
   6 async function main() {
→  7     const allUsers = await prisma.user.findMany(
  error: Environment variable not found: **DATABASE_URL**.
  -->  schema.prisma:3
   | 
 2 |   provider = "sqlite"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at CB (/prisma/node_modules/@prisma/client/runtime/index.js:38681:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:190106) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:190106) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

### How to reproduce

1. curl -L https://pris.ly/quickstart | tar -xz --strip=2 quickstart-master/typescript/starter
2. cd starter && npm install
3. Write a query and view the results
4. npm run dev

### Expected behavior

A working example that returns all the users query result with explanation of how to add **DATABASE_URL** to env.

### Prisma information

```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

```

### Environment & setup

- OS: Linux Mint
- Database: SQLite
- Node.js version: v14.17.5

### Prisma Version

3.5.0

**Comment by janpio** [comment]
The quickstart project should include a `.env` file by default that defines the value of `DATABASE_URL` as `file:./dev.db`. That file is usually loaded on start of Prisma CLI or Client and puts the value into your local environment so it can be picked up from there. 

Are you missing that file?

**Comment by ezalivadnyi** [comment]
I downloaded the quickstarter archive again and I see .env file now.
The problem became because I moved files when "Show Hidden Files" (Ctrl+H) was disabled so .env file wasn't moved and missed.
@janpio Thanks!

**Comment by janpio** [comment]
No problem, that is indeed a very easy to make mistake. Unfortunately no way for us to avoid or prevent it. Good I could help you out so quickly.

**Comment by ezalivadnyi** [comment]
It would be great to add the folder structure description in Quickstart article.

**Comment by robjinman** [comment]
My problem was I made a directory for the starter project, and then tried to move the files up a level with mv, which didn't copy the hidden .env file. Doh!

```
mkdir prisma
cd prisma
curl -L https://pris.ly/quickstart | tar -xz --strip=2 quickstart-main/typescript/starter
mv ./starter/* ./
rm -r ./starter
```
