### ISSUE TITLE
Can't migrate

### ISSUE THREAD

**Issue by tomoueda** [prisma/prisma#10447]
I'm getting the following error:

```
npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "<our url>"

Error: P1017

Server has closed the connection.
```

**Comment by pantharshit00** [comment]
Please fill out the complete issue form. Just pasting the error message is not very helpful.

**Comment by pantharshit00** [comment]
This sounds very similar to https://github.com/prisma/prisma/issues/10001 so maybe you are using supabase. Please give another shot if that is the case.
