### ISSUE TITLE
Error: Error in migration engine. Reason: [libs\sql-schema-describer\src\walkers.rs:592:14] STATE ERROR BOOP 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#10454]
Command: `prisma db push`
Version: `3.5.0`
Binary Version: `78a5df6def6943431f4c022e1428dbc3e833cf8e`
Report: https://prisma-errors.netlify.app/report/13590 
OS: `x64 win32 10.0.19043`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [libs\sql-schema-describer\src\walkers.rs:592:14] STATE ERROR BOOP

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

    at handlePanic (<...>\build\index.js:100836:25)
    at ChildProcess.<anonymous> (F:\Websites\nodejs\htdocs\quanta-webapp\node_modules\prisma\build\index.js:100845:15)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Rust Stacktrace:
```
Starting migration engine RPC server
[libs\sql-schema-describer\src\walkers.rs:592:14] STATE ERROR BOOP
```

**Comment by janpio** [comment]
I just had this happen to me with a database from db-provision: https://prisma-errors.netlify.app/report/13651
I created the database, added a simple schema, used `migrate dev` successfully, then modified the schema, and the next `migrate dev` usage caused this error. Weird.
