### ISSUE TITLE
Cannot save entity with Cyrillic capital letter "И" (d0 98) into MariaDB

### ISSUE THREAD

**Issue by ishestakov** [prisma/prisma#10489]
### Bug description

While trying to save a Cyrillic capital letter "И" (d0 98) into MariaDB varchar field the following error appears:

` code: 'P2023',
  clientVersion: '3.5.0',
  meta: { message: "Conversion failed: Couldn't convert data to UTF-8" }
` 

For all the other letters seems it works OK. As the result no insert/update/delete queries may be executed on a record with a field that contains this letter. 

### Expected behavior

Data is properly saved into DB without any excaption and can be retreived from it as well.

### Prisma information

Schema example:
```
model Point {
  id             Int              @id @default(autoincrement())
  name           String
  @@map("point")
}
```
Query example
```
await prisma.point.create({
    data: {
      name: "И"
   }
});
```

### Environment & setup

- OS:  Windows 10
- Database: 10.3.32 MariaDB
- Node.js version: 16.13.0

### Prisma Version

```
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0

```

**Comment by janpio** [comment]
Hey @ishestakov, did this problem solve itself? I would be interested in knowing how you could fix this.
