### ISSUE TITLE
Setup and run confidence tooling for introspection of CockroachDB

### ISSUE THREAD

**Issue by floelhoeffel** [prisma/prisma#10496]

**Comment by Jolg42** [comment]
Suggestion: someone else than me could take the task to onboard, with my help

**Comment by Jolg42** [comment]
Looks like we could use the serverless offering as the remote database, the free plan might be enough

**Comment by janpio** [comment]
Update:
Server on Cockroach Cloud exists, databases imported (import threw a lot of errors), first Introspection run with `provider=postgresql` was ok but surfaced a few confusing things. Next up run with `provider=cockroachdb` and another look at result.

**Comment by Jolg42** [comment]
Done and continuous runs with https://github.com/prisma/migrations-ci/pull/42

**Comment by Jolg42** [comment]
I used this to import the SQLs
https://www.notion.so/prismaio/Manage-Introspection-CI-databases-1f6492a5b5d64b16b11e80a766ec626e
