### ISSUE TITLE
CDB: Exclude known unsupported APIs from client for CockroachDB provider

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#10493]
There's a running list of unsupported APIs in this PR: https://github.com/prisma/prisma-engines/pull/2423

We should not expose these in the Prisma Client when you have the `cockroachdb` provider set:

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["cockroachdb"]
}

datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}
```

**Comment by janpio** [comment]
Depends on https://github.com/prisma/prisma/issues/10514

**Comment by garrensmith** [comment]
The query-engine has implemented all of this. but it is not released in a prisma client yet.
