### ISSUE TITLE
MongoDB referentialActions in m-n relationships

### ISSUE THREAD

**Issue by dannysofftie** [prisma/prisma#10498]
### Bug description

@matthewmueller From the shared schema, deleting a document from model A doesn't remove its `id` from `a_ids` in model B

It occurs in m-n relationships, where each model keeps an array of referenced documents of the associated model.

### How to reproduce

Create two documents in model A and link to a document in model B. Delete one document from model A that has a relationship with B. Its `id` is left dangling in model B

### Expected behavior

Deleting a document from model A should remove its `id` from `a_ids` array in model B

### Prisma information

```prisma
model A {
    id  String  @id @map("_id") @db.ObjectId
    gql String?

    b_ids String[] @db.Array(ObjectId)
    bs    B[]      @relation(fields: [b_ids])
}

model B {
    id  String  @id @map("_id") @db.ObjectId
    gql String?

    a_ids String[] @db.Array(ObjectId)
    as    A[]      @relation(fields: [a_ids])
}
```

### Environment & setup

- OS:  Ubuntu 20.04
- Database:  MongoDB 4.4.1
- Node.js version:  v16.3.0

### Prisma Version

```
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
Preview Features        : mongoDb
```

**Comment by pantharshit00** [comment]
Hello, 

I updated the model to have `onDelete: Cascade` but I can still reproduce this. Thanks for reporting. 

```prisma
model A {
  id  String  @id @default(dbgenerated()) @map("_id") @db.ObjectId
  gql String?

  b_ids String[] @db.Array(ObjectId)
  bs    B[]      @relation(fields: [b_ids], onDelete: Cascade)
}

model B {
  id  String  @id @default(dbgenerated()) @map("_id") @db.ObjectId
  gql String?

  a_ids String[] @db.Array(ObjectId)
  as    A[]      @relation(fields: [a_ids], onDelete: Cascade)
}
```

**Comment by dannysofftie** [comment]
Thanks @pantharshit00 for taking the time to reproduce. Hopefully it gets fixed soon.

It's a huge blocker rn.

**Comment by dpetrick** [comment]
This is not a bug. Referential actions have no impact on m2m relations (this will not be "fixed"). The same is true for SQL connector m2m. The real solution is us reworking m2m relations in general, which will happen at some point.

**Comment by matthewmueller** [comment]
As a workaround, you can use an explicit "join table", then cascades work correctly.

Here's [some documentation](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#relation-tables).
