### ISSUE TITLE
where field's value match model field definition but throws P2009 error

### ISSUE THREAD

**Issue by Yuliang-Lee** [prisma/prisma#10525]
### Bug description

when query string type field prisma throw P2009 error

![企业微信截图_16383507378589](https://user-images.githubusercontent.com/6936358/144214456-b037cb8f-2577-4833-8d93-0fe7594fbb2e.png)

### How to reproduce

invoke findFirst method

### Prisma information

```
model t_user {
  user_id    String @unique(map: "user_id") @db.VarChar(64)
  id         Int    @id @default(autoincrement())
  user_name  String @default("") @db.VarChar(255)
  user_phone String @default("") @db.VarChar(255)

  @@index([user_name], map: "user_name")
  @@index([user_phone], map: "user_phone")
}
```

```js
prismaClient.t_user.findFirst({ where: { user_id: 'test_1' } })
```

### Environment & setup

- OS: CentOS
- Database: MySQL
- Node.js version: 16.13.0

### Prisma Version

```
prisma                  : 3.6.0
@prisma/client          : 3.6.0
```

**Comment by bigvisionmalachibazar** [comment]
@Yuliang-Lee Did you ever figure it out?
