### ISSUE TITLE
Specify the generator to use for sharing schema files in different environments

### ISSUE THREAD

**Issue by arika0093** [prisma/prisma#10527]
### What I want to do
prisma's schema structure is simple, clear, and brilliant!
I am planning to use prisma schema in several programming languages.

For example, let's assume the following case:
Nodejs will handle the web server functions, and python will handle the once-a-day batch aggregation from the database.
I want to use `prisma-client-js` to connect from node and `prisma-client-py` to connect from python.
I believe that the benefit gained is quite large if one schema can be shared by multiple environments and programming languages.
(For example, it could be a shared language for exchanging data such as `protocol-buffer`.)

### Current issues
There are three items living together in the `schema.prisma` file: `datasource`, `generator`, and `model`.
Of these, only `model` is an important part of the data handling schema.
The `datasource` part is useful for generating connection methods, but the `generator` part is more dependent on each environment.
For example, if you want to share a schema between the above two languages, a simple description would look like this.
```prisma
generator client-js {
  provider = "prisma-client-js"
}

generator client-py {
  provider = "prisma-client-py"
}
```

However, this will not work as expected, because one of the two `generator` will output an error if both are not installed.

## Suggested solution
I need a way to select and execute only what I need in the arguments.
For example :
```
prisma generate --schema ./schema/schema.prisma --generator client-js
```

It would also be great if you could specify multiple generators.
Alternatively, it may be better to have the generator part specified by each user as an add-on.

## Alternatives.
There is currently a way to force a workaround using environment variables.
```prisma
generator client {
  provider = env(PRISMA_CLIENT)
}
```

I have created a sample that uses this method.
https://github.com/arika0093/prisma-multi-language

However, the drawback is that there is a lot of work to specify, and it is a bit of a hack.

## Additional context

Creating a schema first, and then automatically creating the fetch code and database from there, will cause a paradigm shift in system development.
I think it would be pretty cool to have a system where only the `schema.prisma` is managed in git and each project can refer to it from there.
What are your thoughts on this? I'd appreciate your input.

**Comment by janpio** [comment]
Interesting problem! 

Just to make sure: What is preventing you from having both Clients installed at the same time in both systems?

**Comment by arika0093** [comment]
For example, if you install both `prisma-client-js` and `prisma-client-py`, you will have the following situation.

```
$ npm install prisma # install prisma-client-js
$ pip install prisma # install prisma-client-js
$ npx prisma generate # prisma-client-js installed by npm works.
$ prisma generate # prisma-client-py installed by pip works.
```

This simply makes it more difficult to figure out how to make it work.
Also, `npx prisma generate` succeeds, but `prisma generate` fails:
I think the reason is that the nodejs side cannot be executed without the `npx` command.


In addition, consider a use case where you want to build each environment inside a docker container.
In general, you will build the environment based on the `node` or `python` image.
If you need both language environments, the drawback is that the image building process becomes more complicated.

**Comment by Jolg42** [comment]
I believe from this 
>However, this will not work as expected, because one of the two generator will output an error if both are not installed.
That you would need Node.js to generate the js client and Python to generate the Python client?, and if you only have one of these installed then generate would fail.

the solution mentioned
>prisma generate --schema ./schema/schema.prisma --generator client-js
would make it possible to specify which generator to trigger, avoiding the problem

Is that what it is about?

**Comment by janpio** [comment]
Oh interesting, this is global Prisma CLI (`prisma generate`) vs local Prisma CLI from the project (`npx prisma generate`). Will have to look into `prisma-client-py` a bit to understand why that differentiation is necessary.

Your other point makes total sense to me - fundamentally this _should_ be possible for you in a nice way.

**Comment by RobertCraigie** [comment]
> Also, npx prisma generate succeeds, but prisma generate fails:

I can confirm this issue:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource client {
  provider = "sqlite"
  url      = "file:dev.db"
}

model Post {
  id     String @id @default(cuid())
  binary Bytes
}
```
```
$ python -m prisma generate

Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Error: Generator at /tmp/prisma-js-starter/node_modules/@prisma/client/generator-build/index.js could not start:

internal/modules/cjs/loader.js:967
  throw err;
  ^
Error: Cannot find module '/tmp/prisma-js-starter/--max-old-space-size=8096'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:964:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1459:46)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1488:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by janpio** [comment]
Thanks for jumping in here @RobertCraigie - I was missing the `pkg` context so will look at your new issue 👍

**Comment by RobertCraigie** [comment]
@arika0093 In the meantime, another alternative solution would be to automatically create the Prisma Schema file, this is also very hacky but would allow you to configure the generators. For example:

`python.prisma`
```prisma
generator py {
  provider             = "prisma-client-py"
  recursive_type_depth = -1
}
```

`node.prisma`
```prisma
generator js {
  provider = "prisma-client-js"
}
```

`models.prisma`
```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields:  [authorId], references: [id])
  authorId  Int?
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}
```

Then to automatically create the Prisma Schema file you can use the following script

`update_schema.sh`
```sh
#!/bin/bash

LANGUAGE="$1"
if [ -z "$LANGUAGE" ]; then
  echo "You must pass the target language as the first argument to the script"
  exit 1
fi

cat "$LANGUAGE.prisma" "models.prisma" > schema.prisma
```

And use it like so:
```
./update_schema.sh python
prisma generate
```

**Comment by partmor** [comment]
Hi!

I've also encountered a use case analogous to @arika0093, in which:
- `prisma-client-js` is used in the API layer of a Next.js app
- `prisma-client-py` is used in a microservice that performs some specific task on the data that would be cumbersome to do with node.js

To keep container images small, one would ideally avoid installing node for a python microservice:

> In general, you will build the environment based on the node or python image.
If you need both language environments, the drawback is that the image building process becomes more complicated.


As of today, is the following walkaround by @RobertCraigie still be the best approach?


> @arika0093 In the meantime, another alternative solution would be to automatically create the Prisma Schema file, this is also very hacky but would allow you to configure the generators. For example:
> 
> `python.prisma`
> 
> ```prisma
> generator py {
>   provider             = "prisma-client-py"
>   recursive_type_depth = -1
> }
> ```
> 
> `node.prisma`
> 
> ```prisma
> generator js {
>   provider = "prisma-client-js"
> }
> ```
> 
> `models.prisma`
> 
> ```prisma
> datasource db {
>   provider = "sqlite"
>   url      = env("DATABASE_URL")
> }
> 
> model Post {
>   id        Int     @id @default(autoincrement())
>   title     String
>   content   String?
>   published Boolean @default(false)
>   author    User?   @relation(fields:  [authorId], references: [id])
>   authorId  Int?
> }
> 
> model User {
>   id    Int     @id @default(autoincrement())
>   email String  @unique
>   name  String?
>   posts Post[]
> }
> ```
> 
> Then to automatically create the Prisma Schema file you can use the following script
> 
> `update_schema.sh`
> 
> ```shell
> #!/bin/bash
> 
> LANGUAGE="$1"
> if [ -z "$LANGUAGE" ]; then
>   echo "You must pass the target language as the first argument to the script"
>   exit 1
> fi
> 
> cat "$LANGUAGE.prisma" "models.prisma" > schema.prisma
> ```
> 
> And use it like so:
> 
> ```
> ./update_schema.sh python
> prisma generate
> ```

Thank you in advance!

**Comment by RobertCraigie** [comment]
Hey @partmor! Unfortunately the workaround I suggested is still the best solution to my knowledge.

Also a note about your point of not installing Node for a Python microservice, with the current architecture of the CLI the Python client in essence already installs Node through the packaged CLI which includes Node in the binary. The size of the packaged CLI is smaller than a standard install of Node but it is still not insignificant.

It should also be noted that I'm actively working on refactoring the way the Python CLI works so that it doesn't use the packaged CLI and instead downloads Node for you if you don't already have it installed, see https://github.com/RobertCraigie/prisma-client-py/pull/454. re size concerns, you will be able to install the python package with Node included which will result in equivalent storage requirements to the current packaged CLI.

**Comment by partmor** [comment]
> Hey @partmor! Unfortunately the workaround I suggested is still the best solution to my knowledge.
> 
> Also a note about your point of not installing Node for a Python microservice, with the current architecture of the CLI the Python client in essence already installs Node through the packaged CLI which includes Node in the binary. The size of the packaged CLI is smaller than a standard install of Node but it is still not insignificant.
> 
> It should also be noted that I'm actively working on refactoring the way the Python CLI works so that it doesn't use the packaged CLI and instead downloads Node for you if you don't already have it installed, see [RobertCraigie/prisma-client-py#454](https://github.com/RobertCraigie/prisma-client-py/pull/454). re size concerns, you will be able to install the python package with Node included which will result in equivalent storage requirements to the current packaged CLI.

Thanks @RobertCraigie!

**Comment by MadcowD** [comment]
cc @RobertCraigie to take a look at @yukukotani's new PR

**Comment by MadcowD** [comment]
Also @RobertCraigie (really naive question), but if prisma-client-py is actually using Node underneath the hood, why can't it use an existing JS client generated from a schema?

**Comment by RobertCraigie** [comment]
This is really cool @yukukotani! Thank you for working on this 💜

> if prisma-client-py is actually using Node underneath the hood, why can't it use an existing JS client generated from a schema?

@MadcowD I'm not sure I quite understand the question, are you referring to #10564?
