### ISSUE TITLE
Support for SQLite binary BLOB type

### ISSUE THREAD

**Issue by lambrospetrou** [prisma/prisma#10537]
## Problem

I am using SQLite for a few projects due to its simplicity and no need to maintain any infrastructure, but it seems that Prisma does not support its `BLOB` (binary) type.

I see that issue https://github.com/prisma/prisma/issues/1747 added support for the binary types in other database engines, but not SQLite. The [docs](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#bytes) also mention not supported.

![sqlite not supported](https://user-images.githubusercontent.com/2052105/143241191-57f5e62c-0c2c-44ef-99eb-1ba81a03d9a8.png)

## Suggested solution

Not sure what the solution would look like, but similar to other engines supporting `BLOB` would be nice.

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/6666

**Comment by RobertCraigie** [comment]
Is this a documentation mismatch?

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource client {
  provider = "sqlite"
  url      = "file:dev.db"
}

model Post {
  id     String @id @default(cuid())
  binary Bytes
}
```

Generated migration:
```sql
-- CreateTable
CREATE TABLE "Post" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "binary" BLOB NOT NULL
);
```

Client script:
```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const post = await prisma.post.create({
    data: {
      binary: Buffer.from([1, 2, 3]),
    },
  });
  console.log(post);
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```
```
{ id: 'ckwpirbh80000qb8zgww1aa6y', binary: <Buffer 01 02 03> }
```
