### ISSUE TITLE
assertion failed: self.remaining_mut() >= src.len()

### ISSUE THREAD

**Issue by dodas** [prisma/prisma#1053]
Prisma2 / photon version: `2.0.0-preview017.2`
Node version: `12.2.0`
DB: `Postgres 11.4`

Usually everything works fine, but sometimes I get this error and after that I cannot query anything anymore.
Restarting postrgres + my node server fixes this (not sure what exactly fixes it, maybe resetting connection to db?).

```
Error in Photonselect,bankAccounts: 
Error: undefined target="exit" timestamp="2019-12-05T12:10:34.315Z" fields={"message":"null"}
    at /home/node/app/packages/server/node_modules/@prisma/photon/runtime/index.js:5633:27
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

```
Reason: assertion failed: self.remaining_mut() >= src.len() in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.12/src/bytes.rs:1542:9
```

**Comment by pantharshit00** [comment]
Might be related to https://github.com/prisma/photonjs/issues/305.

If you somehow able to provide with a reproduction, that would be helpful as I unable to reproduce after many attempts.

**Comment by marcus-sa** [comment]
I can confirm that a similar error still occurs with `2.0.0-preview018.2`:
```sh
PhotonError: undefined target="exit" timestamp="2019-12-18T19:27:42.033Z" fields={"message":"1"}
    at NodeEngine.engineReady (examples/prisma/client/runtime/index.js:3533:23)
    at examples/prisma/client/runtime/index.js:3456:21

```

**Comment by marcus-sa** [comment]
I've narrowed it down to the fact that when defining datasource urls using `env()` and it's not available in the engine it'll throw that.

I've narrowed that above specifically down to when using `env()` in schema definitions and the environment variables not being inherited from NodeJS into the child process, then it'll throw that.

```js
// ...
this.child = child_process_1.spawn(prismaPath, [], {
  // Environment variables gets inherited here.
  env: Object.assign(Object.assign({}, process.env), env),
  cwd: this.cwd,
  stdio: ['pipe', 'pipe', 'pipe'],
});
``` 

I think the biggest issue here is that the engine provides zero useful errors at all.

**Comment by pantharshit00** [comment]
Oh yes, we are aware of this. Error is getting swallowed in the engine.

We are investigating and fixing this via https://github.com/prisma/photonjs/issues/357

**Comment by divyenduz** [comment]
@dodas Since #357 is fixed, can you please try this again and see what the actual error is? Thanks.

**Comment by pantharshit00** [comment]
@divyenduz I think you mean https://github.com/prisma/photonjs/issues/357
