### ISSUE TITLE
Preview feature feedback: `fullTextIndex` for MySQL and MongoDB

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10539]
Please share your feedback about the `fullTextIndex` preview feature released in [v3.6.0](https://github.com/prisma/prisma/releases/tag/3.6.0) in this issue.

- If you encounter a bug, please open a bug report in this repo.
- If the feature is working well for you, please share this in a comment below or leave a :+1: on this issue.

If you have any questions, don't hesitate to ask them in the [#product-feedback](https://app.slack.com/client/T0MQBS8JG/C01739JGFCM/thread/C01739JGFCM-1631633975.005200) channel in the [Prisma Slack](https://slack.prisma.io/).

**Comment by yubrot** [comment]
Hello, I am trying `fullTextSearch` and `fullTextIndex` with MySQL as the backend.

These features seem to work fine, and I haven't encountered any bugs, but I have a question about a feature that I have not been able to figure out or perhaps is not supported.

MySQL's `FULLTEXT INDEX` has a parser option that can be specified to change the behavior of the full-text search. ex. `FULLTEXT (title,body) WITH PARSER ngram`. Is there a way to specify this in `@@fulltext` attribute, like `@@fulltext([name], parser: "ngram")`?

Related documentation: https://dev.mysql.com/doc/refman/8.0/en/fulltext-search-ngram.html

**Comment by janpio** [comment]
No, that is not considered yet - so worth a small feature request issue @yubrot. Appreciate it, thanks.

**Comment by tmokmss** [comment]
We really need the parser configuration support. Without it, the feature is actually not usable with CJK languages at all.

**Comment by janpio** [comment]
Can you please open an feature issue for this @tmokmss (or search if one already exists and link it here)? Seems @yubrot back in the day didn't, so we have not standalone request for this that we could investigate and prioritize. Thanks!

**Comment by mcrstudio** [comment]
I just get an error `error: Error validating: This line is not a valid field or attribute definition.` when adding a full text index in the schema file...

```
  generator client {
    provider = "prisma-client-js"
    previewFeatures = ["fullTextIndex", "fullTextSearch"]
  }

  datasource db {
    provider     = "mysql"
    url          = env("DATABASE_URL")
    relationMode = "prisma"
  }

  @@fulltext([address_postal_code, address_line_one, address_line_two]);
```

**Comment by janpio** [comment]
The fulltext index still needs to be part of a model @mcrstudio. If it is, please open a new issue as a bug report and we can look into the details here. Thanks!

**Comment by janpio** [comment]
Did this solve the problem @mcrstudio?

**Comment by nikolasburk** [comment]
Hey everyone 👋 thanks for your feedback on this Preview feature! We just moved it to General Availability in the last week's [6.0.0 release](https://github.com/prisma/prisma/releases/tag/6.0.0), so this issue is being closed 🙏

**Comment by mcrstudio** [comment]
Sorry for the delay @janpio but yes it did
