### ISSUE TITLE
Prisma schema

### ISSUE THREAD

**Issue by rishabhraj291196** [prisma/prisma#10550]
## Problem

how can split prisma schema. its difficult to handle large schema file.

## Suggested solution

Provide some feature where we can split prisma schema. it can be automated or  manually

**Comment by HeavenOSK** [comment]
@rishabhraj291196 
I encountered the same problem. I took a workaround based on following comment.
https://github.com/prisma/prisma/issues/2377#issuecomment-974662122

**Comment by pantharshit00** [comment]
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #2377 as noted by @HeavenOSK
