### ISSUE TITLE
The prisma client is querying tables with wrong names (main. prefix)

### ISSUE THREAD

**Issue by LeoPenaguin** [prisma/prisma#10587]
### Bug description

Hey guys,

for some reason prisma is trying to access tables with prefixes, for exemple, I have this schema for my users :

```
model User {
  socketId    String    @id @unique
  name        String
  score       Int       @default(0)
  lobbyId     Int?
  lobby       Lobby?    @relation("LobbyUsers", fields: [lobbyId], references: [id], onDelete: Cascade)
  masterOf    Lobby?    @relation("LobbyMaster")
  answers     Answer[]  @relation("UserAnswers")
  messages    Message[]

  @@map("users")
}
```
And Prisma is showing me this error : 

```
PrismaClientKnownRequestError: 
Invalid `db.user.create()` invocation in
/home/lpenaguin/quizz-dev/quizz-server/src/lib/users.ts:7:64

   4 
   5 const db = new PrismaClient()
   6 
→  7 const createUser = (socketId: string, name: string) => db.user.create(
  The table `main.users` does not exist in the current database.
    at cb (/home/lpenaguin/quizz-dev/node_modules/@prisma/client/runtime/index.js:38675:17) {
  code: 'P2021',
  clientVersion: '3.5.0',
  meta: { table: 'main.users' }
```
The table should be `users`, and it was set correctly in the migration, but the client is trying to query on `main.users`

### How to reproduce

- I write the schema
- Migrate with `npx prisma migrate dev`
- And just in case I generate the client again `npx prisma generate`

### Prisma information

My datasource
```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}
```
My user model
```
model User {
  socketId    String    @id @unique
  name        String
  score       Int       @default(0)
  lobbyId     Int?
  lobby       Lobby?    @relation("LobbyUsers", fields: [lobbyId], references: [id], onDelete: Cascade)
  masterOf    Lobby?    @relation("LobbyMaster")
  answers     Answer[]  @relation("UserAnswers")
  messages    Message[]

  @@map("users")
}
```
A failing request
```
const createUser = (socketId: string, name: string) => db.user.create({
    data: {
        socketId,
        name,
    },
})
```
The error : 
```
/home/lpenaguin/quizz-dev/node_modules/@prisma/client/runtime/index.js:38675
          throw new PrismaClientKnownRequestError(message, e.code, this.prisma._clientVersion, e.meta);
                ^
PrismaClientKnownRequestError: 
Invalid `db.user.create()` invocation in
/home/lpenaguin/quizz-dev/quizz-server/src/lib/users.ts:7:64

   4 
   5 const db = new PrismaClient()
   6 
→  7 const createUser = (socketId: string, name: string) => db.user.create(
  The table `main.users` does not exist in the current database.
    at cb (/home/lpenaguin/quizz-dev/node_modules/@prisma/client/runtime/index.js:38675:17) {
  code: 'P2021',
  clientVersion: '3.5.0',
  meta: { table: 'main.users' }
}
```

### Environment & setup

- OS: Ubuntu 20.04.3 LTS
- Database: SQLite
- Node.js version: v16.13.0

### Prisma Version

```
prisma                  : 3.6.0
@prisma/client          : 3.5.0
```

**Comment by LeoPenaguin** [comment]
Ok this is caused by a version mismatch between prisma and prisma client.

**Comment by nemanjam** [comment]
I get this error while building Docker container, and only then, same thing on host works fine. Both prisma and client are `3.7.0`.

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: The table `main.Post` does not exist in the current database.
    at cb (/app/node_modules/@prisma/client/runtime/index.js:38688:17)
    at async getStaticProps (/app/.next/server/pages/index.js:78:18)
    at async renderToHTML (/app/node_modules/next/dist/server/render.js:388:20)
    at async /app/node_modules/next/dist/export/worker.js:273:36
    at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:74:20)
```

**Comment by janpio** [comment]
How is this related to the parent issue @nemanjam? Better open a new issue and provide all the information the issue template asks for.

**Comment by nemanjam** [comment]
No need, I solved it in meantime, it was my mistake, I copied schema file to wrong folder in multistage Dockerfile, and error message brought me to this page. I did:

```
COPY prisma package.json yarn.lock ./
```

instead of:

```
COPY package.json yarn.lock ./
COPY prisma ./prisma
```

**Comment by Ka0shi** [comment]
@nemanjam  I am in the same situation, the problem appears only when using docker and dynamic page, there are no problems with regular pages, but for some reason dynamic ones cannot take data from prisma. Can anyone help?

`
PrismaClientKnownRequestError: 
Invalid `prisma.type.findUnique()` invocation:


The table `main.Type` does not exist in the current database.
    at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:35024:13)
    at RequestHandler.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/index.js:34996:12)
    at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:34991:12)
    at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:36082:16)
    at async getTypeByName (/app/.next/server/chunks/719.js:43:22)
    at async TypePage (/app/.next/server/app/type/[type]/page.js:783:23) {
  code: 'P2021',
  clientVersion: '4.8.1',
  meta: { table: 'main.Type' },
  batchRequestIdx: undefined
}
undefined
TypeError: Cannot read properties of undefined (reading 'name')
    at TypePage (/app/.next/server/app/type/[type]/page.js:809:31)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.
`
`
model Type {
  id String @id @default(uuid())
  name String 
  body String
  img String
  @@unique([name])
}
`
`
# Install dependencies only when needed
FROM node:18-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY prisma package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi


# Rebuild the source code only when needed
FROM node:16-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN npm i 

# RUN npx prisma migrate deploy
RUN npx prisma generate
# RUN npm install next-auth @prisma/client @next-auth/prisma-adapter
# RUN npx prisma db pull

RUN npm run build --prod
# If using npm comment out above and use below instead
# RUN npm run build


# Production image, copy all the files and run next
FROM node:16-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/posts ./posts

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node", "server.js"]
`

**Comment by rinebi** [comment]
@nemanjam is correct. @Ka0shi you need to copy `prisma` folder into your `runner` stage by adding this line:
```
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Add this line below
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
```

**Comment by thanhhoa214** [comment]
@nemanjam is correct. @Ka0shi you need to copy `prisma` folder into your `runner` stage by adding this line:
```
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Add this line below
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
```
