### ISSUE TITLE
Bug: Create Project is BROKEN!

### ISSUE THREAD

**Issue by markief1** [prisma/prisma#10596]
### Bug description

I have been trying to create a project on many devices for a long time, it doesn't work.
Whenever I try to **create a project** it says:

``Unable to find Github App installation for currently logged in user [USERNAME]. This should never happen.``

Urgently fix.

### Expected behavior

1: Sign up w/ github.
2: Go to projects
3: Press create project

### Prisma information

NEW User created today.

### Environment & setup

OS - ChromeOS

### Prisma Version

```

```

**Comment by markief1** [comment]
``` Screenshot ```
![image](https://user-images.githubusercontent.com/95639799/144882933-b060c92f-42c4-479c-aa60-da8e7e0dbade.png)

**Comment by madebysid** [comment]
Hey @markief1, thanks for reporting this! Project creation was broken, but it should now be fixed, can you try again? 
BTW in the future, you can reach out to the Prisma Data Platform team directly via the Intercom messenger on the bottom right of the platform. That way, you’ll make sure we see it :)
