### ISSUE TITLE
Rollback not triggered in an interactive transaction when connection limit is high

### ISSUE THREAD

**Issue by AoiIsMine** [prisma/prisma#10622]
### Bug description

I try to execute multiple interactive transactions concurrently and find that when the number of connections is high, throwing an error will not trigger transaction rollback
When the number of connections is small, although there will be errors, it can still be rolled back
(on another computer,  connections 5 (CPU is 2) ,can be rolled back without an error.)  

I'm not sure what caused it or whether it can be reproduced on other computers

### How to reproduce
[code demo](https://github.com/AoiIsMine/test)

### Environment & setup

- OS:  Windows,
- Database: MySQL 8.0
- Node.js version: v14.16.0

### Prisma Version

```
3.6.0
```

**Comment by AoiIsMine** [comment]
two notebooks of the same model A(thinkpad e14(4cpu))  have problems 
and model B(4cpu) have problems 
In the model C(thinkpad e490(2cpu)) notebook test, there is no problem at all
i don't konw why

**Comment by AoiIsMine** [comment]
i use knex.js is will success, can rollback

**Comment by pantharshit00** [comment]
Thanks for the issue. I can reproduce this.
