### ISSUE TITLE
Support GiST Index type with Postgres

### ISSUE THREAD

**Issue by tmcw** [prisma/prisma#10634]
## Problem

I'm trying to use Prisma with geographic data in PostGIS. There's an issue to track actual PostGIS support (#1798) but this is a narrower concern - the support of GiST indexes. These were mentioned when index type support was introduced (#10080), but only BTree or Hash were implemented.

## Suggested solution

Allow GiST as an option to the `type` parameter for an index.

## Alternatives

This could be hacked in with an arbitrary migration, but that is not a clean solution.

**Comment by janpio** [comment]
Can you elaborate on the use cases of GiST indexes _outside_ of PostGIS or full text search?

**Comment by pimeys** [comment]
What about the GIN index?

**Comment by tmcw** [comment]
> Can you elaborate on the use cases of GiST indexes outside of PostGIS or full text search?

There are examples in the Postgres docs - [GiST](https://www.postgresql.org/docs/current/gist-examples.html) - but to summarize, besides Postgis, the you can use GiST for a different performance profile with [intarray columns, making them faster to reindex but slower to query](https://www.postgresql.org/docs/9.1/intarray.html), and the GiST index for [ltree values](https://www.postgresql.org/docs/9.1/ltree.html) supports additional operators that the GIN index doesn't.

However, besides the other use-cases:

- You can't use GIN indexes with geospatial data. They'll quickly fail and any attempts to push data in them will produce nearly-unindexed performance and warnings about the index overflowing.
- There are a lot of people using PostGIS and geospatial data in Postgres.

So, from that perspective, this is not a nice-to-have for handling geospatial data, it's a necessity.

**Comment by janpio** [comment]
> So, from that perspective, this is not a nice-to-have for handling geospatial data, it's a necessity.

This is what confuses me: We are definitely aware of that, mostly talking about GiST in context of PostGIS. But you created an issue for the usage of the index outside of the context of PostGIS work. I saw now "intarray" and "ltree" mentioned 👍

**Comment by tmcw** [comment]
Oh! Yeah - that’s because there are use cases (like mine) in which GiST index support alone would be enough to make Prisma usable without hacks. We can already specify geometry columns, but can’t load data into them until they have the right index type.

**Comment by janpio** [comment]
Internal note: https://github.com/prisma/database-schema-examples/search?q=%22USING+Gist%22

**Comment by renchris** [comment]
> This is now available in our `dev` version, so you can use `prisma@dev` and the `extendedIndexes` preview feature if you want to play with it. Optimally start with a `db pull` on your existing database that uses these, and see if they are added correctly to the introspected schema. Afterwards you can also play with adding additional ones and then migrate (with `db push` or `migrate dev`).
> 
> Let us know how it goes please!

Are geographic data queries supported in the `prisma@dev` version for other databases such as PlanetScale? I'm looking for Spatial Query support for PlanetScale. 

It looks like both MySQL and PlanetScale support Spatial Queries directly: https://planetscale.com/blog/how-do-database-indexes-work

However, it looks like Prisma doesn't support this per this other thread: https://github.com/prisma/prisma/issues/1798

**Comment by janpio** [comment]
Yes, this issue here only refers to GiST indexes.
