### ISSUE TITLE
$transaction does not work

### ISSUE THREAD

**Issue by danielenggaard1** [prisma/prisma#10630]
### Bug description

When executing a `$transaction(...)` I get the following error message:  _TypeError: Cannot read properties of undefined (reading '_hasPreviewFlag')_. This is both for interactive transactions and non-interactive. The stack call goes back to:
`...
at $transaction (node_modules/@prisma/client/runtime/index.js:39611:17)`. It dosent matter which query I am running inside the transaction. It always fails.

### How to reproduce

1. Create any transaction as follows: `prisma.$transaction([prisma.notes.findMany({})])`
2. The error should pop up

### Environment & setup

- OS: WSL2 running Ubuntu 20.04
- Database: MySQL
- Node.js version: v16.13.0

### Prisma Version

```
prisma                  : 3.6.0
@prisma/client          : 3.6.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at ../../.nvm/versions/node/v16.13.0/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at ../../.nvm/versions/node/v16.13.0/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at ../../.nvm/versions/node/v16.13.0/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at ../../.nvm/versions/node/v16.13.0/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : dc520b92b1ebb2d28dc3161f9f82e875bd35d727
Studio                  : 0.440.0
Preview Features        : interactiveTransactions
```

**Comment by Brendan-Stubbs** [comment]
@danielenggaard1 did you get to the bottom of this? I have just run into the same issue.

**Comment by danielenggaard1** [comment]
> @danielenggaard1 did you get to the bottom of this? I have just run into the same issue.

Yes, my problem was that I was object destructuring the prisma client as follows: 
`const client = new PrismaClient();`
`const { tableA, tableB, $transaction } = client;`
`$transaction([tableA.updateMany({...}), tableB.updateMany({...})]);`

I don't know why this only happened with `$transaction`, but it seemed like it was using the `tableA` type of the SQL table without all the CRUD methods. My solution was to not destructure the client but just to call the `client.tableA...` every time.
