### ISSUE TITLE
Simple migration fails

### ISSUE THREAD

**Issue by oyatek** [prisma/prisma#10658]
### Bug description

I'm using Blitz framework with Prisma.

Blitz is using SQLite by default and it worked well but I've decided to switch to Postgres.

I've deleted the old db migration files, updated configs.

When I run `blitz prisma migrate dev` I get the following error:
```
Environment variables loaded from .env
Prisma schema loaded from db/schema.prisma
Datasource "db": PostgreSQL database "DB_NAME", schema "public" at "127.0.0.1:5432"

Error: db error: ERROR: syntax error at or near "WITH ordinality"
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:354
   1: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:108
```

### How to reproduce

See above

### Expected behavior

The migration script should create new tables in the DB

### Prisma information

`schema.prisma`:

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

// --------------------------------------

model User {
  id             Int      @id @default(autoincrement())
  createdAt      DateTime @default(now())
  updatedAt      DateTime @updatedAt
  name           String?
  email          String   @unique
  hashedPassword String?
  role           String   @default("USER")

  tokens   Token[]
  sessions Session[]
}

model Session {
  id                 Int       @id @default(autoincrement())
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt
  expiresAt          DateTime?
  handle             String    @unique
  hashedSessionToken String?
  antiCSRFToken      String?
  publicData         String?
  privateData        String?

  user   User? @relation(fields: [userId], references: [id])
  userId Int?
}

model Token {
  id          Int      @id @default(autoincrement())
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  hashedToken String
  type        String
  // See note below about TokenType enum
  // type        TokenType
  expiresAt   DateTime
  sentTo      String

  user   User @relation(fields: [userId], references: [id])
  userId Int

  @@unique([hashedToken, type])
}
```

`env.local`:
```
DATABASE_URL=postgresql://USER:PASSWORD@127.0.0.1:5432/DB_NAME
```

### Environment & setup

- OS: Ubuntu 14.0
- Database: PostgreSQL 9.3.24
- Node.js version: 16.13.0

### Prisma Version

```
3.5.0
```

**Comment by oyatek** [comment]
I've Googled "postgres ordinality" and found that "WITH ORDINALITY" feature has been added in Postgres 9.4. Looks like this is the cause of the problem as my Postgres version is 9.3.24?

**Comment by janpio** [comment]
This is probably a regression of these two lines: https://github.com/prisma/prisma-engines/blame/48845f3893436777ad008b3764c57f93f2f61289/libs/sql-schema-describer/src/postgres.rs#L574-L575 This might have broken compatibility with Postgres <9.4 😢

**Comment by janpio** [comment]
We actually never really supported Postgres < 9.4, so this is mainly a documentation issue on our side.
Supporting these versions is considerable effort, and considering they are unmaintained and unsupported since multiple years we do not expect many people to still be on these versions.

@oyatek Is updating your PostgreSQL version an option for you?

Otherwise you can probably manually modify the migration by using `--create-only` first before executing the Migration.

**Comment by pantharshit00** [comment]
I will also recommend you to upgrade the database here.

**Comment by oyatek** [comment]
Thank you for your replies. 

I couldn't upgrade PostgreSQL because I had a really old Macbook (2011) which had a too old OS, which the latest version of PostgreSQL doesn't support. 

I've bought a new Macbook now because I could continue development on the old one. Installed the latest PostgeSQL. The problem is solved.

Yes, it would be good to update the docs and tell about the min. PostgreSQL version requirement.

**Comment by janpio** [comment]
(Documentation was updated in the meantime: https://www.prisma.io/docs/reference/database-reference/supported-databases)
