### ISSUE TITLE
Introspecting based on datasource defined in prisma/schema.prisma …

### ISSUE THREAD

**Issue by B3ns44d** [prisma/prisma#10669]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.15.5           | 
| Prisma CLI  | 2.24.1             | 
| Binary      | 18095475d5ee64536e2f93995e48ad800737a9e4| 

## Error
```
Error: [/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/af530a5/src/single.rs:159:18] not implemented: Supported url schemes: file or sqlite, mysql, postgresql or jdbc:sqlserver.
```

**Comment by janpio** [comment]
That is a pretty old version of the Prisma CLI @B3ns44d - you should see if this still happens with a newer version.
What is the datasource you have inside your `prisma/schema.prisma` and what is the protocol of that?

**Comment by B3ns44d** [comment]
Oh it works now with the new Prisma version, I totally forgot to update it because I was working with an old project using this version, thank you!!
