### ISSUE TITLE
[CockroachDb] Investigate Partial Indices

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#10667]
It seems like some partial indexes  e.g. `where x =5` do not seem to be correctly filtered out when introspected on CockroachDb vs on Postgres. 

Example: https://github.com/prisma/database-schema-examples/blob/8cea37d834f3effd6aad53e98c5bc865b4d85335/postgres/canvas-lms/schema.sql#L13216

**Comment by do4gr** [comment]
I am unable to reproduce this in the engines tests.

**Comment by janpio** [comment]
Current Migration-CI results: https://github.com/prisma/migrations-ci/blob/6e134c924ab53d80be509f7be2f83b6cd2ff3709/results/cockroachdb-serverless/canvas-lms/1-before-introspected.prisma#L31

Maybe the version uses (22.x on Engine tests, 21.x on Cockroach Cloud that migrations-ci uses) influences this?

**Comment by matthewmueller** [comment]
_(Disregard if unrelated)_

The current implementation of MongoDB uniques don't behave the same as SQL with nullability. We're currently trying to decide how to deal with this. One suggestion was to actually support partial indices in Prisma: https://github.com/prisma/prisma-engines/issues/2361

**Comment by janpio** [comment]
This would be the related issue for PostgreSQL: https://github.com/prisma/prisma/issues/3076

In this issue here we are confused why partial indexes, which are currently usually ignored, appearing in the schema as normal indexes. Should not happen (and also does not for PostgreSQL - but for CockraochDB)

**Comment by do4gr** [comment]
The reason for the difference on introspection Ci is that the hosted db version does not seem to include this fix https://github.com/cockroachdb/cockroach/pull/72870

**Comment by janpio** [comment]
Cockroach Cloud Serverless, which is showing this behavior, is currently running on a specific version that does not include the fix that Matthias mentioned. Next week it will be updated to a newer version, and we expect the problem to magically go away when that happens.
