### ISSUE TITLE
Broken formatting of the non-native binaryTargets warning

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#10670]
Lines 2, 3, 7 and 8 each have extra four spaces at the beginning:

```
Warning: Your current platform `darwin-arm64` is not included in your generator's `binaryTargets` configuration ["darwin"].
    To fix it, use this generator config in your schema.prisma:
    generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "darwin"]
}
    Note, that by providing `native`, Prisma Client automatically resolves `darwin-arm64`.
    Read more about deploying Prisma Client: https://github.com/prisma/prisma/blob/main/docs/core/generators/prisma-client-js.md
```

**Comment by janpio** [comment]
This might fix it, but code formatting is now rather weird: https://github.com/prisma/prisma/commit/7b43b4151f66d1cea0e94fe74b210fb2332f4e95
https://github.com/prisma/prisma/pull/10673

**Comment by aqrln** [comment]
> but code formatting is now rather weird

Yeah, it's often like that with multiline template strings, unfortunately. I think it's fine (or at least expected).

**Comment by janpio** [comment]
Optimally with my changes some (snapshot) tests would also be failing now, but they are not - so we have an error message with no test coverage here 😆
