### ISSUE TITLE
please add findMany with count api

### ISSUE THREAD

**Issue by SteveSuv** [prisma/prisma#10680]
```js
await prisma.user.findMany({
  where:{},
  count:true
})
```

**Comment by pantharshit00** [comment]
We already have this feature. Please refer to the docs here: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#count

**Comment by pantharshit00** [comment]
If you are asking to having the ability to do it all in one client call, then this is a duplicate of https://github.com/prisma/prisma/issues/7550
