### ISSUE TITLE
Windows reports a virus when attempting to install prisma or @prisma/client

### ISSUE THREAD

**Issue by jonrcrowell** [prisma/prisma#10717]
### Bug description

When I try to add prisma or @prisma/client as dependencies, it fails with an error message regarding index-browser.js.
Windows reports a virus.

```sh
error An unexpected error occurred: "UNKNOWN: unknown error, copyfile 'C:\\Users\\jon\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@prisma-client-3.6.0-68a60cd4c73a369b11f72e173e86fd6789939293-integrity\\node_modules\\@prisma\\client\\runtime\\index-browser.js' -> 'C:\\source\\repos\\clients\\fullstackfish\\double-barreled-prisma\\node_modules\\@prisma\\client\\runtime\\index-browser.js'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\source\\repos\\clients\\fullstackfish\\double-barreled-prisma\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### How to reproduce

1. Create a new folder
2. Open terminal
2. `npm init -y`
3. `yarn add -D prisma` or `yarn add @prisma/cilent`

### Expected behavior

The dependencies should be installed.
Windows should not report a virus.

### Environment & setup

- OS: Windows 11
- Database: n/a
- Node.js version: 14.8.1

### Prisma Version

```
n/a I don't get that far
```

**Comment by janpio** [comment]
What Antivirus software are you using?

Update: I can confirm this for our `index-browser.js` in 3.6.0: https://www.virustotal.com/gui/file/46d99903ad9af960a641ac3d9a8278d409e1a5fcf8ed0a6e49c56b9904e53fbf

As far as we are aware this file does _not_ contain a virus of course.

**Comment by jonrcrowell** [comment]
It's Windows Defender. I wonder why Microsoft is flagging it at malicious.

**Comment by janpio** [comment]
My guess (!) is that some actual malware, based on Javascript, uses a similar dependency or string or magic number as we are - and that triggers a false positive in their AI based detection heuristic. Usually those are fixed quite quickly, but sometimes not. We'll try to figure out if any other files are affected and if we can do anything to speed up the removal of this detection.

**Comment by jonrcrowell** [comment]
I think this means I need to get a Mac for Christmas.

**Comment by haotan19** [comment]
Same here, any suggestions?

![Screenshot 2021-12-16 080338](https://user-images.githubusercontent.com/80441177/146283866-d7dd47b5-d030-4752-a793-bfd1c045a40f.jpg)

**Comment by jlenik** [comment]
Just happened to me and search engines fail at connecting "Trojan:Script/Oneeva.A!ml" keyword with Prisma JS.

**Comment by janpio** [comment]
We are trying to remove this false positive in Windows Defender now.

Until then we recommend you removing the quarantine and choose "Allow on device" instead. 
If you don't want (or can't) do that, in 99.9% of all cases you probably do not need the file in your app and it not being there should not cause big problems.

**Comment by janpio** [comment]
Both my local Windows Defender and MS's cloud one, and also VirusTotal do not detect the file as malicious any more: https://www.virustotal.com/gui/file/46d99903ad9af960a641ac3d9a8278d409e1a5fcf8ed0a6e49c56b9904e53fbf
![image](https://user-images.githubusercontent.com/183673/146397246-06789f31-51a1-4b33-8918-52290c2bb094.png)

@jonrcrowell That is super weird and don't think I saw that before. Maybe check out your project into a different path? Or restart your Windows?

**Comment by aqrln** [comment]
We have received the confirmation from Microsoft that it was a false positive. Please follow the steps in their reply if you still run into any issues.

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.  1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender  2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures” 3. Run “MpCmdRun.exe -SignatureUpdate”  Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
