### ISSUE TITLE
`$app` path is not resolved inside a seed function

### ISSUE THREAD

**Issue by wvhulle** [prisma/prisma#10745]
### Bug description

Using the line 

```
import { dev } from '$app/env'
```

inside a database seed function, crashes. `ts-node` is unable to resolve the `$app` path.

The module  that is called:
```
import pkg, { PrismaClient } from '@prisma/client';
import { dev } from '$app/env';

declare global {
	var _prisma: PrismaClient; // eslint-disable-line
}

let prisma;
if (dev) {
	if (!global._prisma) {
		global._prisma = new PrismaClient();
	}
	prisma = global._prisma;
} else {
	const { PrismaClient } = pkg;
	prisma = new PrismaClient();
}

export default prisma as PrismaClient; // type assertion for shim
```

### How to reproduce

1. start a new svelte kit project
2. install ts-node and prisma
3. run the database seed function

Or test the minimal crashing repository https://github.com/wvhulle/-app-bug-report

### Expected behavior

I expect the database to be seeded and the $app path to be resolved.

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id  Int    @id @default(autoincrement())
  name String
}
```

### Environment & setup

- OS: Manjaro Linux
- Database: SQLite
- Node.js version: v16.13.1

### Prisma Version

```
prisma                  : 3.6.0
@prisma/client          : 3.6.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : dc520b92b1ebb2d28dc3161f9f82e875bd35d727
Studio                  : 0.440.0
```

**Comment by janpio** [comment]
Does it work if you run `node --experimental-specifier-resolution=node --loader ts-node/esm ./prisma/seed.ts` directly instead of via `prisma db seed`?

**Comment by wvhulle** [comment]
Hey, I fixed it. Your suggestion didn't work. The problem was that the $app
was only available in svelte kit, not a problem of prisma but I needed the
line to work around another Prisma svelte problem.

**Comment by janpio** [comment]
Ok thanks, so not Prisma at fault but just surfaced there - happens. Thanks for the update, I will close the issue then.

PS: If the other Prisma svelte problem is a common thing, make sure to create an issue as well for that please.
