### ISSUE TITLE
Support Firebird RDBMS

### ISSUE THREAD

**Issue by VIS-Repo** [prisma/prisma#10793]
[Firebird](https://firebirdsql.org/) is an excellent high performance database that is really easy to install and works right out of the box. We use it in a number of important projects via the [node-firebird](https://www.npmjs.com/package/node-firebird) package but we'd like to move to a common PRISMA ORM model.

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
