### ISSUE TITLE
Unhide `cockroachdb` provider and preview feature flag

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10808]
We should make the provider and preview feature flag visible when we want to launch the feature.

Caution: We can create a PR early, but the merge should only happen shortly before the release when CockroachDB support should be released and launched.

**Comment by Jolg42** [comment]
@janpio for making the provider visible it needs to happen in language-tools here https://github.com/prisma/language-tools/blob/main/packages/language-server/src/completion/completions.json#L429-L446

I think it will be good to do that before GA (note conversation that mongodb is still hidden here https://prisma-company.slack.com/archives/C013RMLGE72/p1641888985013500)

**Comment by janpio** [comment]
- TS: https://github.com/prisma/prisma/pull/10844
- Rust: https://github.com/prisma/prisma-engines/pull/2582
