### ISSUE TITLE
Expand tests around referential actions and referential integrity

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10806]
Right now we have minimal test coverage around referential actions:

- https://github.com/prisma/prisma/blob/main/packages/client/src/__tests__/integration/happy/referentialActions-onDelete-cascade-mysql/test.ts 
   => tests that cascading deletes work
- https://github.com/prisma/prisma/blob/main/packages/client/src/__tests__/integration/errors/referentialActions-onDelete-default-foreign-key-error-mysql/test.ts 
   => tests that restricting deletes works

(and equivalents for PostgreSQL, SQLite and SQL Server)

We should try to get full test coverage of all the referential actions and related settings like `referentialIntegrity=prisma`:

https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-integrity

Implementation Steps:

- [ ] Test all the supported referential actions (defaults and explicitly set)
	![image](https://user-images.githubusercontent.com/183673/146982756-e9581857-9a30-416f-bde1-fe749c3589a3.png)
- [ ] Duplicate all tests for `referentialIntegrity=prisma` and/or MongoDB

**Comment by Jolg42** [comment]
Current plan https://www.notion.so/prismaio/How-do-we-GA-the-referentialIntegrity-preview-feature-8a656fe445ae4a69ad19c5000e5c7191#8a3a59ebfddd4b50bb32aa5819a55b6e

**Comment by janpio** [comment]
Follow up issue when this is resolved: https://github.com/prisma/prisma/issues/15733

**Comment by Jolg42** [comment]
Done in https://github.com/prisma/prisma/pull/14221
Now merged to main
