### ISSUE TITLE
Stabilize `referentialIntegrity`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10807]
- [x] Make sure all issues are closed or understood: https://github.com/prisma/prisma/labels/topic%3A%20referentialIntegrity
- [x] https://github.com/prisma/prisma/issues/10806
- [ ] Combine documentation of [Referential Integrity](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-integrity) and [Referential Actions](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions)
- [ ] ...

**Comment by Jolg42** [comment]
The TODOs are done.
The combine todo docs is outdated.
