### ISSUE TITLE
Weird query on PlanetScale

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10822]
Earlier context: https://github.com/prisma/prisma/discussions/10720
 

> ```
>  prisma:client Prisma Client call: +29ms
>   prisma:client prisma.user.update({
>   prisma:client   where: {
>   prisma:client     id: 'ckx83iboo0008vjpgmjls82d1'
>   prisma:client   },
>   prisma:client   data: {
>   prisma:client     name: 'Dexter'
>   prisma:client   }
>   prisma:client }) +0ms
>   prisma:client Generated request: +0ms
>   prisma:client mutation {
>   prisma:client   updateOneUser(
>   prisma:client     where: {
>   prisma:client       id: "ckx83iboo0008vjpgmjls82d1"
>   prisma:client     }
>   prisma:client     data: {
>   prisma:client       name: "Dexter"
>   prisma:client     }
>   prisma:client   ) {
>   prisma:client     id
>   prisma:client     name
>   prisma:client     email
>   prisma:client     emailVerified
>   prisma:client     image
>   prisma:client     orgId
>   prisma:client     teamId
>   prisma:client     leadId
>   prisma:client   }
>   prisma:client }
>   prisma:client  +0ms
>   prisma:client:libraryEngine sending request, this.libraryStarted: true +29ms
>   prisma:client:fetcher Error: Error occurred during query execution:
>   prisma:client:fetcher ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol db.`User`.id not found", state: "HY000" })) })
>   prisma:client:fetcher     at prismaGraphQLToJSError (/Users/dexter/projects/next/tw-3/node_modules/@prisma/client/runtime/index.js:35958:10)
>   prisma:client:fetcher     at Object.request (/Users/dexter/projects/next/tw-3/node_modules/@prisma/client/runtime/index.js:36319:17)
>   prisma:client:fetcher     at async cb (/Users/dexter/projects/next/tw-3/node_modules/@prisma/client/runtime/index.js:38653:26)
>   prisma:client:fetcher     at async handler (webpack-internal:///./pages/api/welcome.js:26:9)
>   prisma:client:fetcher     at async Object.apiResolver (/Users/dexter/projects/next/tw-3/node_modules/next/dist/server/api-utils.js:102:9)
>   prisma:client:fetcher     at async DevServer.handleApiRequest (/Users/dexter/projects/next/tw-3/node_modules/next/dist/server/next-server.js:1064:9)
>   prisma:client:fetcher     at async Object.fn (/Users/dexter/projects/next/tw-3/node_modules/next/dist/server/next-server.js:951:37)
>   prisma:client:fetcher     at async Router.execute (/Users/dexter/projects/next/tw-3/node_modules/next/dist/server/router.js:222:32)
>   prisma:client:fetcher     at async DevServer.run (/Users/dexter/projects/next/tw-3/node_modules/next/dist/server/next-server.js:1135:29)
>   prisma:client:fetcher     at async DevServer.run (/Users/dexter/projects/next/tw-3/node_modules/next/dist/server/dev/next-dev-server.js:445:20) +1m
> error - Error: 
> Invalid `prisma.user.update()` invocation:
> 
> 
>   Error occurred during query execution:
> ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol db.`User`.id not found", state: "HY000" })) })
> ```

> After chatting to PlanetScale support it actually seems like Prisma was trying to execute a weird query, you can find the Gist here: https://gist.github.com/dextermb/2698971c153ba74b339879363295123b.
> 
> Here's an extract:
> ```
> Query: SELECT `db`.`User`.`id`, `db`.`OrgTeamAdmin`.`teamId`, `db`.`OrgTeamAdmin`.`userId` FROM `db`.`OrgTeamAdmin` WHERE 1=0
> Duration: 29ms
> Query: ROLLBACK
> Duration: 30ms
> ```
> 
> I've been able to re-produce why this is happening in my application. Here's a snippet of my schema:
> 
> ```prisma
> model User {
>   id String @id @default(cuid())
>   name String?
>   email String? @unique
>   emailVerified DateTime?
>   image String?
> 
>   accounts Account[]
>   sessions Session[]
> 
>   orgId String?
>   org Org? @relation(fields: [orgId], references: [id])
> 
>   teamId String?
>   team OrgTeam? @relation(fields: [teamId], references: [id])
> 
>   leadId String?
> }
> 
> model OrgTeamAdmin {
>   teamId String
>   team OrgTeam @relation(fields: [teamId], references: [id])
> 
>   userId String
>   // user User @relation(fields: [userId], references: [id])
> 
>   @@unique([teamId, userId])
> }
> ```
> 
> The `user` relation (currently commented out) on `OrgTeamAdmin` seems to make the weird select. Not sure why.

_Originally posted by @dextermb in https://github.com/prisma/prisma/discussions/10720#discussioncomment-1839206_

**Comment by janpio** [comment]
@dextermb Do you think this is a duplicate to https://github.com/prisma/prisma/issues/10758 and describes the same problem? (That issue has a simplified reproduction schema)

**Comment by dextermb** [comment]
> @dextermb Do you think this is a duplicate to https://github.com/prisma/prisma/issues/10758 and describes the same problem? (That issue has a simplified reproduction schema)

Seems so 👍🏻

**Comment by janpio** [comment]
Closing here then and keeping a comment over there for the record.

**Comment by steven-tey** [comment]
Ran into a similar issue (shown below) and can confirm that removing `referentialIntegrity = "prisma"` solved my issue!

```
prisma ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol  not found", state: "HY000" })) })```
