### ISSUE TITLE
in Elastic Beanstalk docker build environment when install @prisma/client barely error occurs

### ISSUE THREAD

**Issue by iamjaeholee** [prisma/prisma#10837]
### Bug description

Using Elastic Beanstalk
whenever deploy to the environment it starts docker build in inner process.

i am using dockerfile which includes `RUN npm ci --only=production` command.

so Elastic Beanstalk starts docker build 
and docker starts to install @prisma/client.

but somtimes docker build timeout error occurs.

![Screen Shot 2021-12-23 at 9 42 13 AM](https://user-images.githubusercontent.com/66099990/147171383-9111b62b-2708-4bc9-88b4-407d64e3a319.png)

I tried 
1. write .npmrc to give autorization
```
unsafe-perm=true
```

2. write .ebextensions to expand the timeout
```
option_settings:
  - namespace: aws:elasticbeanstalk:command
    option_name: Timeout
    value: 600
```

all of the methods doesn't help yet.

sometimes build done successfully then docker save cache about the npm install command
so deploy works few days with caches

after the cache expires the issue happens again.

I have no idea what to do more.

any ideas ?

### Environment & setup

- OS: 64bit Amazon Linux 2/3.2.2
- Database: PostgreSQL
- Node.js version: 14.18.0

### Prisma Version

```
^2.15.0
```

**Comment by janpio** [comment]
> 2.15.0

That is _really_ old, are you really using this version? If so, upgrading probably will solve the problem.

How long does a `npm install` or `npx prisma generate` usually take on your project?

**Comment by iamjaeholee** [comment]
Umm.. okay i will try update version.

well `npm install` takes just a minute on my machine.

I am really not sure about how long `npm install` takes on the AWS Elastic Beanstalk.
The EB shows docker build timeout error.

I guess it's not about @prisma/client, it's about EB docker build timeout option.

so i close this issue.

Thanks a lot.
