### ISSUE TITLE
Being able to modify names of Model when using `prisma db pull`

### ISSUE THREAD

**Issue by iamriajul** [prisma/prisma#10878]
## Problem
I've got an existing database (Generated using Laravel conventions) where table names follow **snake_case** pluralized pattern. (eg: 'voice_search_sessions', 'weather_city_translations', etc.).

And when I use `prisma db pull` then Prisma writes schema file with model name as it is with the table name. but when using `snake_case plurlaized` name in TypeScript it doesn't look good, such as writing: 
```ts
let session: voice_search_sessions = prisma.voice_search_sessions.findFirst();
// OR
let sessions: voice_search_sessions[] = prisma.voice_search_sessions.findMany();
```
What I want is to write something which looks good and meaningful, such as.
```ts
let session: VoiceSearchSession = prisma.VoiceSearchSession.findFirst();
// OR an Array of VoiceSearchSession which is meaningful.
let sessions: VoiceSearchSession[] = prisma.VoiceSearchSession.findMany();
```

## Suggested Solution
We can add a flag when running `prisma db pull` which will use the `PascalCase Singular` pattern with `@@map` for model naming (eg: --use-pascal-case-singular-model-naming).

Or we can give user flexibility of name resolving class which will extend user and implements two methods, one for database table name to model name and another for model name to database table name.

Thanks.

**Comment by janpio** [comment]
Similar requests are collected under the term "introspection configuration": https://github.com/prisma/prisma/labels/topic%3A%20introspection-configuration
