### ISSUE TITLE
Snapshot serializer in CLI tests doesn't replace time durations >= 1s with a placeholder

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#10896]
Snapshot serializer in CLI tests doesn't replace time durations greater than or equal to 1s with a placeholder.

Failed pipeline: https://github.com/prisma/prisma/runs/4657927865?check_suite_focus=true#step:15:662

```
  ● --schema from parent directory › --schema absolute path: should work

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `--schema from parent directory --schema absolute path: should work 1`

    - Snapshot  - 1
    + Received  + 1

      ↵
    - ✔ Generated Prisma Client (0.0.0 | TEST_ENGINE_TYPE) to ./subdirectory/@prisma/client in XXms
    + ✔ Generated Prisma Client (0.0.0 | TEST_ENGINE_TYPE) to ./subdirectory/@prisma/client in 3.34s
      You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```

Relevant code: https://github.com/prisma/prisma/blob/c1fdadf96c27509accf4e8d5c0c3ab91ff68afd4/packages/cli/src/__tests__/__helpers__/snapshotSerializer.ts#L37-L39

**Comment by Jolg42** [comment]
It does now so I'll close 

https://github.com/prisma/prisma/blob/main/packages/sdk/src/utils/jestSnapshotSerializer.js#L74

**Comment by aqrln** [comment]
Thanks!

**Comment by Jolg42** [comment]
Thanks! added in https://github.com/prisma/prisma/pull/11123
