### ISSUE TITLE
Prisma Migrate keeps dropping and adding Foreign Keys

### ISSUE THREAD

**Issue by tarazena** [prisma/prisma#10900]
### Bug description

Any time a new migration is created, prisma migrate will try to drop foreign keys and recreate them, all migrations are being deployed successfully, but it seems there is a logic issue regarding foreign keys.

### How to reproduce

1. Run `prisma migrate dev`, It will deploy the DB schema.
2. Run `prisma migrate dev`, A new migration will be created even though there is no changes in the Schema

### Expected behavior

It should not create a new migration since the previous one already applied the migration.

### Prisma information

```
model Issue {
  // hiding the rest of the fields
  id                        String             @id @default(uuid())
  Address                   String
  address                   Address            @relation(fields: [Address], references: [id])
  @@index([Address], name: "Address")
}

model Note {
 // hiding the rest of the fields
  id             String           @id @default(uuid())
  User           String
  user           User             @relation(fields: [User], references: [id])
  @@index([User], name: "User")
}

model PromotionReference {
  // hiding the rest of the fields
  id                String           @id @default(uuid())
  Promotion         String
  promotion         Promotion        @relation(fields: [Promotion], references: [id])
  
  @@index([Promotion], name: "Promotion")
}

model VerificationToken {
  id        String    @id @default(uuid())
  userId    String    @unique
  user      User?     @relation(fields: [userId], references: [id])
}

model Address {
  id             String           @id @default(uuid())
  issue          Issue[]
}

model User {
  id                      String               @id @default(uuid())
  notes                   Note[]
  verificationToken       VerificationToken?
}
```

and Migration SQL
```sql
-- DropForeignKey
ALTER TABLE `Issue` DROP FOREIGN KEY `Issue_Address_fkey`;

-- DropForeignKey
ALTER TABLE `Note` DROP FOREIGN KEY `Note_User_fkey`;

-- DropForeignKey
ALTER TABLE `PromotionReference` DROP FOREIGN KEY `PromotionReference_Promotion_fkey`;

-- DropForeignKey
ALTER TABLE `VerificationToken` DROP FOREIGN KEY `VerificationToken_userId_fkey`;

-- AddForeignKey
ALTER TABLE `Issue` ADD CONSTRAINT `Issue_Address_fkey` FOREIGN KEY (`Address`) REFERENCES `Address`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Note` ADD CONSTRAINT `Note_User_fkey` FOREIGN KEY (`User`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PromotionReference` ADD CONSTRAINT `PromotionReference_Promotion_fkey` FOREIGN KEY (`Promotion`) REFERENCES `Promotion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `VerificationToken` ADD CONSTRAINT `VerificationToken_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
```

### Environment & setup

- OS: OSX Monterey v12.1 (Intel)
- Database: MySQL v5.7.27
- Node.js version: 14.17.4

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
```

**Comment by janpio** [comment]
Is this the full schema or are you using any preview feature flags?

**Comment by tarazena** [comment]
@janpio I'm not using any feature flags, also this is not the entire schema.

```
datasource db {
  provider = "mysql"
  url      = env("DB_ENDPOINT")
}
```

**Comment by tarazena** [comment]
@janpio I think i found what's causing this, I've replaced `@@index([Promotion], name: "Promotion")` with `@@index([Promotion], map: "Promotion")` and now it's not causing the migration recreate anymore;

**Comment by tarazena** [comment]
Ok i've deleted all the migrations, started a new migration and the issue disappeared, must be something with the old migrations. I'll close this.

Thanks

**Comment by janpio** [comment]
Let us have a shot at reproducing this with the data you provided - if that does not go anywhere, we will just close this issue ourselves.

**Comment by pantharshit00** [comment]
I tried the reproduction and I wasn't able to reproduce. We will close this for now.

**Comment by paymog** [comment]
This is happening to me as well. Haven't been able to nail down why it's happening though

**Comment by alanwu4321** [comment]
Same -  just dropping and adding exactly the same foreign keys

**Comment by NMWijayasekara** [comment]
I still get this I created a new issue #19127 
I get this when I run a MySQL server locally and `npx prisma migrate dev` always creates a new migration for removing the foreign keys. I mean I can keep running `npx prisma migrate dev` and it still keeps on running the same migration stating that it is not synced with the database.

The major problem with this is I can't make any changes to the schema without prisma wanting to remove the foreign keys and trying to reset the database leading to all the data being lost.

**Comment by jpamdeth** [comment]
This is happening to me too.

**Comment by Mukeshkumar9787** [comment]
Nothing worked for me

**Comment by janpio** [comment]
If someone has a reproduction for this, please open a new issue and fill in the issue template. Maybe we can then reproduce and understand what is going on. Thank you.
