### ISSUE TITLE
How to push a new ObjectId to an array?

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma#10906]
### Discussed in https://github.com/prisma/prisma/discussions/10876

<div type='discussions-op-text'>

<sup>Originally posted by **AnthonyLzq** December 26, 2021</sup>
I have the following schema

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("MONGO_URI")
}

model Course {
  id          String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  description String
  teacher     String
  title       String
  topic       String
  students    String[] @db.Array(ObjectId)
}

model Student {
  id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  name  String
  email String
}
```

Want I want to achieve is to enroll new students to a course, so I want to push a new ObjectId to my students array, but Prisma fails with the following error:

```
The current database provider doesn't support a feature that the query used: Converting BSON to type String. Data: Array([ObjectId("61c8a8d2e2d9caa2a4f91638")])
```

This is the code I have:
```js
const enrollStudent = (courseId, studentId) => {
  return await prismaClient.course.update({
    where: {
      id: courseId
    },
    data: {
      students: {
        set: [studentId]
      }
    }
  })
}
```

According to the [docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#push) the push operation is only available for PostgreSQL, is there any plan to make it available for mongodb as well?</div>

**Comment by dpetrick** [comment]
Fixed with 3.8

**Comment by hamswaldenkv** [comment]
Hello

Can you try this ?
`const enrollStudent = (courseId, studentId, oldStudentIds) => {
  return await prismaClient.course.update({
    where: {
      id: courseId
    },
    data: {
      students: {
        set: [... oldStudentIds , studentId]
      }
    }
  })
}`

**Comment by hamswaldenkv** [comment]
Hello

Can you try this ?
```js example-good
const enrollStudent = (courseId, studentId, oldStudentIds) => {
  return await prismaClient.course.update({
    where: {
      id: courseId
    },
    data: {
      students: {
        set: [... oldStudentIds , studentId]
      }
    }
  })
}
```
