### ISSUE TITLE
findMany bug 

### ISSUE THREAD

**Issue by darwin808** [prisma/prisma#10904]
### Bug description

    const result = await prisma.thread.findMany(); // error 500 why? 
    const result = await prisma.$queryRaw`SELECT * FROM thread`; // success 

 it should be the same right or is something different ? im using aws lambda and prisma 3.7.0

### Environment & setup

- OS: Mint
- Database: Postgres
- Node.js version: 14.17

### Prisma Version

```
prisma 3.7.0
```

**Comment by sabinadams** [comment]
Can you give some more context into the code? A copy of the schema? 

Are you getting any more specific error message that might be helpful?

**Comment by darwin808** [comment]
`model thread {
  id Int @default(autoincrement()) @id
  title String 
  post String 
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  media String[]
  like Int? @default(0)
  dislike Int? @default(0)
  thread_id Int 
  page_id Int 

}`

this is the model

**Comment by janpio** [comment]
The real error message you are getting from Prisma Client (which then leads to the error 500 from the crashing application) would be very useful.

**Comment by darwin808** [comment]
`a7beb649-eda7-4add-ab86-33b38a137022	INFO	TypeError: Cannot read property 'findMany' of undefined`

logs from cloudwatch , I also use findMany in other routes working fine unti this schema

**Comment by janpio** [comment]
That sounds like if `prisma.thread` is generally not available. Can you use any other methods on that model?

**Comment by janpio** [comment]
A quick reproduction shows no problems:

```
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// A `main` function so that we can use async/await
async function main() {

  const result = await prisma.thread.findMany(); // error 500 why? 
  console.log("result", result)

  const result2 = await prisma.$queryRaw`SELECT * FROM thread`; // success 
  console.log("result2", result2)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

Gives:
```
C:\Users\Jan\Documents\throwaway\10904>ts-node script.ts
result []
result2 []
```

**Comment by darwin808** [comment]
i changed the model still error 

`model thread {
  id Int @default(autoincrement()) @id
  title String 

}`

`const result = await prisma.thread.findMany(); // error 500 why? 
const result = await prisma.$queryRaw`SELECT * FROM thread`; // success `

`package:
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
`

the config in serverless.yml does this affect ?

**Comment by pantharshit00** [comment]
@darwin808 If you share your serverless setup inside of a git repository, that would be helpful. Otherwise, we won't be able help you easily as we will need to guess most parts of your setup.

**Comment by darwin808** [comment]
`      - name: initialize the prisma`
`      run: yarn prisma:generate`

added this to my .github/workflow/main.yml and its returning 200 

its kinda weird why on my other routes its working , cached maybe? btw thanks you can close this now

**Comment by pantharshit00** [comment]
Yeah, it does seem old generated client was cached. I will close this.
