### ISSUE TITLE
libs/datamodel/connectors/dml/src/model.rs:338:29

### ISSUE THREAD

**Issue by HarbingerNight** [prisma/prisma#10921]
### Bug description

When testing `prisma db pull` on a database received an error:
 
```
[libs/datamodel/connectors/dml/src/model.rs:338:29] 
Hi there! We've been seeing this error in our error reporting backend, but cannot reproduce it in our own tests. …
```

Reporting as requested in error message.

### How to reproduce

This error is reproducable by doing a `prisma db pull` on an existing database with a table that has a primary key column that lacks any [a-zA-Z] characters in its name. It occurs both on single column primary key constraints, and table level composite primary key constraints if one of the columns.

It does not occur with columns that are not primary key columns.

```sql
CREATE TABLE "example" ( "имя" text primary key );

-- or --

CREATE TABLE "example" ( "_" int, "a" text, primary key ( "_", "a" ));
```

### Expected behavior

1. The same as when there are no [a-zA-Z] characters in other columns, comment out the key and add @@ignore to the table for lack of a primary key;
2. Auto-assign a column name such as column_1;
3. Better support for international languages and non [a-zA-Z] columns and table names.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource psql {
  provider          = "postgresql"
  url               = env("DATASTORE_URL")
  shadowDatabaseUrl = env("DATASTORE_DEV")
}
```

### Environment & setup

- OS: Ubuntu 20.04.3 LTS ( WSL 2 )
- Database: PostgreSQL
- Node.js version: 16.13.1

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/.pnpm/@prisma+engines@3.7.0-31.8746e055198f517658c08a0c426c7eec87f5a85f/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/.pnpm/@prisma+engines@3.7.0-31.8746e055198f517658c08a0c426c7eec87f5a85f/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/.pnpm/@prisma+engines@3.7.0-31.8746e055198f517658c08a0c426c7eec87f5a85f/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/.pnpm/@prisma+engines@3.7.0-31.8746e055198f517658c08a0c426c7eec87f5a85f/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
```

**Comment by jkomyno** [comment]
Here's a more recent error report for this issue: https://prisma-errors.netlify.app/report/14260

**Comment by pimeys** [comment]
Fixed in https://github.com/prisma/prisma-engines/pull/2898

I'd recommend updating to the latest version (4.7.1) due to it having a LOT of introspection crashes fixed.
