### ISSUE TITLE
Prisma generate missing on v2.8.0

### ISSUE THREAD

**Issue by izaacdb** [prisma/prisma#10929]
### Bug description

I'm regenerating a previously working prisma project from a schema and get this error:

```
server
Prisma schema loaded from schema.prisma
> Downloading Prisma engines for darwin-arm64 [ ] 0% Error: Not Found 
https://binaries.prisma.sh/all_commits/e6c9b4b2b7fa162d0d459d1863321f547498fcfe/darwin-arm64/query-engine.gz
error Command failed with exit code 1.
```

### How to reproduce

prisma generate

### Expected behavior

I'm not sure what would cause this. https://binaries.prisma.sh/all_commits/e6c9b4b2b7fa162d0d459d1863321f547498fcfe/darwin-arm64/query-engine.gz 
appears to be down - maybe my project was working because of a cache before?

### Prisma information

{ 
  "prisma": "2.28.0",
  "@prisma/client": "2.28.0"
}

### Environment & setup

- Mac 12.02
- PostgreSQL
- Node.js version: v16.2.0

### Prisma Version

```
2.28.0
```

**Comment by locnguyen** [comment]
How did you fix this? I am running into it now.

**Comment by izaacdb** [comment]
I think it was a network issue in my case. Started working again after a while
