### ISSUE TITLE
MongoDB: invalid port number in database URL

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10934]
> The prisma cli seems to be confused with ports.
> 
> ```
> datasource db {
>   provider = "mongodb"
>   url      = "mongodb://testReadOnlyUser:****@db-rs-11:27017,db-rs-12:27017,db-rs-13:27017,db-rs-14:27017,db-rs-15:27017/default_default?replicaSet=dbMongoDB&maxPoolSize=1000"
> }
> 
> generator client {
>   provider        = "prisma-client-js"
>   previewFeatures = ["mongoDb"]
> }
> ```
> 
> gives
> `Error: invalid port number in database URL`
> 
> Using this without the ports works fine
> `mongodb://testReadOnlyUser:****@db-rs-11,db-rs-12,db-rs-13,db-rs-14,db-rs-15/default_default?replicaSet=dbMongoDB&maxPoolSize=1000`
> 
> _Originally posted by @Hitabis in https://github.com/prisma/prisma/issues/10016#issuecomment-958753476_

**Comment by Jolg42** [comment]
Looks like a duplicate of the recently confirmed issue with same error here https://github.com/prisma/prisma/issues/11684

**Comment by janpio** [comment]
Closing as duplicate of https://github.com/prisma/prisma/issues/11684 as this indeed looks like a duplicate. Do you agree @Hitabis?
