### ISSUE TITLE
Studio CLI: `prisma studio` errors with `ENOENT: no such file or directory, open '/[...]/prisma/schema.prisma'` after opening when using a custom name for the Prisma schema file

### ISSUE THREAD

**Issue by eemmiillyy** [prisma/prisma#10939]
### Bug description

Related errors https://github.com/prisma/studio/issues/819 and https://github.com/prisma/prisma/issues/10936

errors with in Studio UI after opening via CLI

```
ENOENT: no such file or directory, open '/[...]/repro/prisma/schema.prisma'
```
Even though the file name is `schema1.prisma` 

### How to reproduce

- Rename a prisma schema to `schema1.prisma`
- run `npx prisma studio --schema prisma/schema1.prisma`

### Expected behavior

Passing `--schema=prisma/schema1.prisma` or any filename different than "schema.prisma" should work.

### Prisma information

```
datasource db {
  provider = "postgres"
  url      = "[...]"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id Int @id
}
```

### Environment & setup

OS: Mac OS
Database: PostgreSQL
Node.js version: 14

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
```

**Comment by eemmiillyy** [comment]
This seems to be the source of the issue `main/packages/client/src/runtime/getPrismaClient.ts#L388`

**Comment by Jolg42** [comment]
Note that Studio is calling `getPrismaClient()` directly from
https://github.com/prisma/studio-code/blob/main/packages/pcw/src/client.ts#L46

So like @eemmiillyy suggested we would likely need to pass an extra argument to it, probably `filename` (One argument used at the moment is `dirname`)
