### ISSUE TITLE
Add migrations to git automatically

### ISSUE THREAD

**Issue by kakserpom** [prisma/prisma#10944]
## Problem

I sometimes forget to add new migrations to git manually.

## Suggested solution

Run `git add` automatically for new migrations.

## Alternatives

1) Make an option for this particular case.

2) Allow hooks on "migrationCreated" event

3) I should take Memantine pills.

**Comment by pantharshit00** [comment]
I will keep this open for further input from other people but I am not in favour of this. If you will change or revert migrations, it will add unnecessary changes in the git history. I don't think we run any git commands in the cli right now.

**Comment by kakserpom** [comment]
@pantharshit00 I am not saying committing, just adding (i.e. tracking). Now you have to manually click on its checkbox in Unversioned Files in PHPStorm. If it's in .gitignore the action will have no effect.

**Comment by PanMan** [comment]
I don't think this makes sense: All files I create I have to add manually to Git - also Git is (sortof) unrelated from prisma. Perhaps your git tooling or editor can do this.

**Comment by kakserpom** [comment]
@PanMan There's usually an option called "automatically add new files to Git", if a file is not ignored in .gitignore it gets added automatically upon creation.  It would be nice to make a hook that runs when a new migration is added.

**Comment by PanMan** [comment]
this, to me, seems not a prisma issue but your local development workflow. You can always make a script that does `prisma migrate && git add .`

**Comment by janpio** [comment]
Interacting with `git` is outside of Prisma CLIs domain, we will not consider this.
