### ISSUE TITLE
fix(notion-prisma-generators): update outdated links

### ISSUE THREAD

**Issue by YassinEldeeb** [prisma/prisma#10959]
### Bug description

[Prisma Generators](https://prismaio.notion.site/Prisma-Generators-a2cdf262207a4e9dbcd0e362dfac8dc0) article on Notion has this link to the latest type definitions for `@prisma/generator-helper` which points to a 404 not found page.

Suggest updating it to https://github.com/prisma/prisma/blob/main/packages/generator-helper/src/types.ts
Instead of: https://github.com/prisma/prisma/blob/main/src/packages/generator-helper/src/types.ts

![Screenshot 2022-01-04 200720](https://user-images.githubusercontent.com/72823042/148103946-04590fd2-aec6-470e-b7cd-1cf8ba56c6f5.png)

Also this points to a 404 page.

Suggest updating it to https://github.com/prisma/prisma/blob/main/packages/generator-helper/src/GeneratorProcess.ts#L27
Instead of: https://github.com/prisma/prisma/blob/main/src/packages/generator-helper/src/GeneratorProcess.ts#L27

![Screenshot 2022-01-04 201703](https://user-images.githubusercontent.com/72823042/148105235-70ea4f5d-ab79-4c7c-9cfd-00a329040a0a.png)

### How to reproduce

Go to [Prisma Generators](https://prismaio.notion.site/Prisma-Generators-a2cdf262207a4e9dbcd0e362dfac8dc0).
check: 
1. The very end of the `The Generator Interface` section where It's linking to the latest type definitions
2. The `Implementation section` has a link labeled `a bunch of GeneratorProcess's `

click any of these, you'll get a 404 page.

### Expected behavior

The link to point to the latest type definitions file on github.

### Prisma information

Not related

### Environment & setup

Not related

### Prisma Version

Not related

**Comment by janpio** [comment]
Both links should be updated. Can you confirm?

**Comment by YassinEldeeb** [comment]
Yeah they're good now.
