### ISSUE TITLE
Downloading the Prisma Engine takes a long time from China

### ISSUE THREAD

**Issue by zxhycxq** [prisma/prisma#10986]
### Bug description

I am from China, in the project ,i run the `predev`,but after 10min ,it just 7%.how to deal with it?

![image](https://user-images.githubusercontent.com/11674203/148390598-b24bfeec-3652-43a1-a1a9-39e11776efe5.png)

### How to reproduce

just run yarn dev 

```bash
$ yarn run generate
$ yarn run generate:prisma && yarn run generate:nexus && yarn run generate:graphql-codegen
$ prisma generate
 > Downloading Prisma engines for windows [                    ] 1%

```

### Expected behavior

can run the project successful

### Prisma information

 "@prisma/client": "~2.23.0",
 "nexus-plugin-prisma": "~0.35.0",
 "next-prisma-plugin-webpack5": "^0.0.0-dripip",

### Environment & setup

window
node : v14.18.1

### Prisma Version

it show 

```
 Downloading Prisma engines for windows 
````

**Comment by pantharshit00** [comment]
Hello,

Our CDN is currently blocked in China. Please use a VPN to workaround and you can follow: https://github.com/prisma/prisma/issues/8886

**Comment by guog** [comment]
https://github.com/guog/download-prisma-engines
