### ISSUE TITLE
Simple MongoDB query takes over 30 seconds to execute

### ISSUE THREAD

**Issue by Maxson52** [prisma/prisma#10987]
### Bug description

I have GoogleOAuth authentication through Passport in my Express server, and I run the `.upsert()` function to check if a user exists, otherwise I create one. However it appears this query is taking upwards of 30 seconds, meaning the user is stuck on the OAuth consent screen for about that long waiting to be logged in. It seems this is happening on most queries I make, however I've only thoroughly tested with this scenario.

### How to reproduce

1. Set up basic auth template with [passport google oauth](www.passportjs.org/packages/passport-google-oauth20/) or copy from a [demo repo](https://github.com/Maxson52/sveltekit-express-google-auth) I made and adjust to use Prisma accordingly.
2. Navigate to the login route which will eventually execute the `upsert()` function
3. Wait....

### Prisma information

Schema file
```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

model User {
  id          String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  googleId    String @unique
  displayName String
  avatarUrl   String
  role        String @default("free")
}
```

```js
// query looks like this, however I've tried making a few adjustments with no success
      const user = await prisma.user.upsert({
        where: {
          googleId: profile.id, 
        },
        update: {},
        create: {
          googleId: profile.id,
          displayName: profile.displayName,
          avatarUrl: profile.photos[0].value,
        },
      });
```

### Environment & setup

- OS: Windows 11
- Database: MongoDB (Atlas)
- Node.js version: 16.13.1

### Prisma Version

```
3.7.0
```

**Comment by janpio** [comment]
Can you share same sample data that would we can use to create a reproduction without any additional software, just a simple route that executes exactly this query to confirm this is really just Prisma being slow? Thanks.

**Comment by Maxson52** [comment]
Here's a basic test just getting all users (of which there is only one):
```js
router.get("/test", async (req: Request, res: Response) => {
  try {
    const users = await prisma.user.findMany();

    return res.json(users);
  } catch (error) {
    return res.status(500).json({ message: "Failed to get users" });
  }
});
```

It took 21.92 seconds for a total size of 210 bytes.
With the response being:
```json
[
  {
    "id": "xxxxxxxxxxxxxxxxxxx",
    "googleId": "xxxxxxxxxxxxxxxxx",
    "displayName": "Max",
    "avatarUrl": "http://url.com",
    "role": "free"
  }
]
```

**Comment by janpio** [comment]
This looks _very_ much like our e2e test for Prisma and MongoDB Atlas which we run all the time: https://github.com/prisma/e2e-tests/tree/dev/databases/mongodb-atlas (Schema is a bit different, but that should not be a big deal)

Here is a PR that adds an explicit `findMany()` in there as well: https://github.com/prisma/e2e-tests/pull/2265
There is one of the test runs: https://github.com/prisma/e2e-tests/runs/4729668314?check_suite_focus=true#step:6:279
Here is the output of the database interactions with timestamps:
```
Thu, 06 Jan 2022 17:02:00 GMT $ ts-node ./script.ts
Thu, 06 Jan 2022 17:02:02 GMT before any action
Thu, 06 Jan 2022 17:02:03 GMT deleted all users
Thu, 06 Jan 2022 17:02:04 GMT user_created {
Thu, 06 Jan 2022 17:02:04 GMT  id: '6d795f757365725f69643030',
Thu, 06 Jan 2022 17:02:04 GMT  email: 'alice@prisma.io',
Thu, 06 Jan 2022 17:02:04 GMT  name: 'Alice'
Thu, 06 Jan 2022 17:02:04 GMT }
Thu, 06 Jan 2022 17:02:04 GMT users [
Thu, 06 Jan 2022 17:02:04 GMT  {
Thu, 06 Jan 2022 17:02:04 GMT  id: '6d795f757365725f69643030',
Thu, 06 Jan 2022 17:02:04 GMT  email: 'alice@prisma.io',
Thu, 06 Jan 2022 17:02:04 GMT  name: 'Alice'
Thu, 06 Jan 2022 17:02:04 GMT  }
Thu, 06 Jan 2022 17:02:04 GMT ]
Thu, 06 Jan 2022 17:02:04 GMT user {
Thu, 06 Jan 2022 17:02:04 GMT  id: '6d795f757365725f69643030',
Thu, 06 Jan 2022 17:02:04 GMT  email: 'alice@prisma.io',
Thu, 06 Jan 2022 17:02:04 GMT  name: 'Alice'
Thu, 06 Jan 2022 17:02:04 GMT }
```

Pretty instant to me for the `findMany` - as it should be.

I can't imagine Prisma and MongoDB are really behaving that differently for you. Are you sure it is the Prisma Client query taking that time and not some other logic happening in your application?

**Comment by Maxson52** [comment]
I guess it's possible that something else is causing the slowness, however after switching out _only_ the `/test` endpoint with the following, I get the same response in a rock solid 1.27 seconds.

```js
import { MongoClient } from "mongodb";
if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not set");
const client = new MongoClient(process.env.DATABASE_URL);

router.get("/test", async (req: Request, res: Response) => {
  try {
    await client.connect();
    const database = client.db("myFirstDatabase");
    const users = await database.collection("User").find({}).toArray();

    return res.json(users);
  } catch (error) {
    return res.status(500).json({ message: "Failed to get users" });
  } finally {
    client.close();
  }
});
```

**Comment by janpio** [comment]
Yep, that sounds much more realistic with creating a connection to the database and all - which indeed points to Prisma taking that time. Can you maybe add a timestamp logging before and after calling the `findMany` just to make sure it is really that line that takes so long? You can also enable logging in Prisma Client and use that and debugging to get log output which will allow similar things if you have output of timestamps for everything: https://pris.ly/d/logging + https://pris.ly/d/debugging

Alternatively: Can you maybe share the connection string of your MongoDB Atlas instance with us (in private of course, schemas@prisma.io) so we can reproduce this manually?

**Comment by Maxson52** [comment]
```js
    // generate timestamp
    const timestamp = new Date().toTimeString();
    const users = await prisma.user.findMany();

    // generate timestamp
    const timestamp2 = new Date().toTimeString();

    // log time
    console.log(`${timestamp} - ${timestamp2}`);
```

Logs: `14:09:29 GMT-0500 (Eastern Standard Time) - 14:10:00 GMT-0500 (Eastern Standard Time)`

I'll shoot over the connection string shortly!

**Comment by janpio** [comment]
Received and reproduced - something is definitely weird with that cluster. This is probably something to figure out together with MongoDB Atlas and nothing Prisma can influence.

**Comment by Maxson52** [comment]
Can confirm, the cluster was causing the problem. Thanks for the support in finding out the issue here!

**Comment by janpio** [comment]
Awesome, thanks for playing along and nice we could figure this out.
