### ISSUE TITLE
Migrate lock timeout on PlanetScale

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10997]
When using Migrate with PlanetScale, sometimes you get an error message like this:

```
Error querying the database: Server error: `ERROR 70100 (1317): held locks released: vttablet: rpc error: code = Aborted desc = transaction 1621634564893708666: ended at 2021-05-21 23:54:48.118 UTC (exceeded timeout: 20s) (CallerID: unsecure_grpc_client)'
```

Also see all the related reports here: https://github.com/planetscale/beta/discussions/34

Two possible causes we can think of:

1. Wait to long when CLI prompts your for migration name
2. Migrations take "to long" to run (Reproducible easily with https://stackoverflow.com/questions/4284524/how-and-when-to-use-sleep-correctly-in-mysql)

We should try to reproduce both so we know if we have something that needs fixing.
It might also be worth to investigate if something like this could happen on other database providers as well or if this is PlanetScale/Vitess specific.

(Potential solutions: Only lock after migration name is known, do not lock on PlanetScale at all, etc)

**Comment by jde** [comment]
I used `prisma migrate dev` as my primary workflow through the bootstrapping of my app and saw a gradual increase in the time it took. 

When I **reached 64 migrations** (most of these were attempts to debug #10758 issues) my migrate flow hit the 20s Planetscale timeout and I got the error above. 

This happened even if I pre-typed my migration name as the process started so that it immediately filled and didn't add any real time to the process.

I'm using `prisma db push` now, which executes in 1.1s. 

I'm planning creating fresh dbs locally and on planetscale and bringing myself to my current state with a single initial migration soon.

**Comment by tomhoule** [comment]
Starting with next tuesday's release, we won't be taking locks on planetscale anymore.

**Comment by Jolg42** [comment]
@keinsell 👀 with which version? Try `prisma -v` to check

**Comment by keinsell** [comment]
> @keinsell 👀 with which version? Try `prisma -v` to check

```
**prisma                  : 3.11.0
@prisma/client          : 3.11.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine b371888aaf8f51357c7457d836b86d12da91658b (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli b371888aaf8f51357c7457d836b86d12da91658b (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core b371888aaf8f51357c7457d836b86d12da91658b (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt b371888aaf8f51357c7457d836b86d12da91658b (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : b371888aaf8f51357c7457d836b86d12da91658b
Studio                  : 0.458.0
Preview Features        : referentialIntegrity, fullTextSearch, fullTextIndex
```

**Comment by janpio** [comment]
Just to confirm and make sure: You are also using PlanetScale as your database @keinsell?
We are asking so much here because in theory this code should not even run there any more, so even if you or your connection is slooooooow 🐢 this should not be able to happen 🤷

**Comment by keinsell** [comment]
> Just to confirm and make sure: You are also using PlanetScale as your database @keinsell? We are asking so much here because in theory this code should not even run there any more, so even if you or your connection is slooooooow 🐢 this should not be able to happen 🤷

Yes, I'm also using PlanetScale as database @janpio. Maybe it was just single outage on PlanetScale side, I don't really know mate.

**Comment by janpio** [comment]
Ok. Keep us updated if it happens again and we can take a look (and talk to PlanetScale about it).

**Comment by obibring** [comment]
@janpio, I'm experiencing the same issue w/ prisma 3.13.0. I've tried 20+ times to migrate my database and continue to see get the following error:
```
Error: held locks released: vttablet: rpc error: code = Aborted desc = transaction 1651614596363662552: ended at 2022-05-03 22:38:12.305 UTC (exceeded timeout: 20s) (CallerID: planetscale-admin)
   0: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:185
```

**Comment by janpio** [comment]
The `CallerID: planetscale-admin` in the error message is new. Can you please open a new issue and provide all the possible information? Then we can have a deeper look.

**Comment by obibring** [comment]
Sure, thanks for the quick reply @janpio
