### ISSUE TITLE
Error: [libs\sql-schema-describer\src\mssql.rs:315:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `create default d_password as 'D,73' `" 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#11010]
Command: `prisma db pull`
Version: `3.7.0`
Binary Version: `8746e055198f517658c08a0c426c7eec87f5a85f`
Report: https://prisma-errors.netlify.app/report/13615 
OS: `x64 win32 10.0.22000`

JS Stacktrace:
```
Error: [libs\sql-schema-describer\src\mssql.rs:315:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `create default d_password as 'D,73' `"
    at ChildProcess.<anonymous> (D:\developer\hello-prisma\node_modules\prisma\build\index.js:46262:30)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

Rust Stacktrace:
```
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: BaseThreadInitThunk
  27: RtlUserThreadStart

```

**Comment by janpio** [comment]
Note: This should be `dbgenerated` and not crash (when we fail to parse)

**Comment by janpio** [comment]
We still do not know how to make Introspection crash because of the existence of such an index. 
We need a SQL dump of a database that reproduces this behavior to replicate this behavior.

(For us the default is just ignored and not represented in the Prisma schema: https://github.com/prisma/prisma/issues/12150)

**Comment by janpio** [comment]
Reproduced: The line breaks cause this, see https://github.com/prisma/prisma/issues/24275
