### ISSUE TITLE
A generator provider should accept arbitrary commands

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#1101]
Generators can be any executable file, but currently this is limited to one single command, which means you can't provide any arguments to a generator:

```prisma
generator photon {
	provider = "/Users/prisma/go/bin/photongo"
	output = "./photon/photon_gen.go"
	package = "photon"
}
```

Providing arguments doesn't work:

```prisma
generator photon {
	provider = "/Users/prisma/go/bin/photongo --option=on"
	output = "./photon/photon_gen.go"
	package = "photon"
}
```

Instead, the `provider` should accept full commands with arguments.

For example, `provider` could accept specifying full commands:

```prisma
generator photon {
	provider = "go run github.com/prisma/photongo/generator"
	output = "./photon/photon_gen.go"
	package = "photon"
}
```

An alternative would be an array to specify the command with arguments:

```prisma
generator photon {
	provider = ["go", "run", "github.com/prisma/photongo/generator"]
	output = "./photon/photon_gen.go"
	package = "photon"
}
```

**Comment by robojones** [comment]
This is related to #934. Is there any progress on either of them?

**Comment by robojones** [comment]
Thanks :+1: 
I really needed this, so I can create a good project setup with [prisma-client-go](https://github.com/prisma/prisma-client-go).
How is it even possible that I can review changes in your PRs? :laughing:

**Comment by Jolg42** [comment]
@robojones You're welcome, and yes it's quite weird 🙃🤣

**Comment by pantharshit00** [comment]
@Jolg42 @robojones 

I think it is just a GitHub feature. You can contribute code reviews to repositories.

**Comment by janpio** [comment]
Some repositories and projects actually appreciate it - this way community members can also test the code and leave their feedback (and vote with their reputation). If you have required approvals activated on PRs though these will not count - only team members' approvals are taking into consideration there.

**Comment by steebchen** [comment]
This fails on the latest alpha:
prisma Error: ENOENT: no such file or directory, stat 'go run ../../..' +72ms

We should also add a test which covers this.
