### ISSUE TITLE
Error when looking up interactive transaction feature flag (Nestjs)

### ISSUE THREAD

**Issue by Brendan-Stubbs** [prisma/prisma#11036]
### Bug description

When attempting to use interactive transactions with nestjs, a type error is thrown when the feature flag lookup takes place.

The error is as follows:
```
[Nest] 38300   - 09/01/2022, 11:42:12   [ExceptionHandler] Cannot read properties of undefined (reading '_hasPreviewFlag')
TypeError: Cannot read properties of undefined (reading '_hasPreviewFlag')
    at $transaction (/Users/brendanstubbs/Personal/Reproduce/prisma-bug-reproduction/node_modules/@prisma/client/runtime/index.js:39631:17)
```

### How to reproduce

1. Clone the [repository](https://github.com/Brendan-Stubbs/prisma-interactive-trx-bug-reproduction)
2. run `docker-compose up -d`
3. Run the tests `npm run test:e2e`

### Expected behavior

For an empty interactive transaction to execute successfully

### Prisma information

This is all included in the repository

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v16.13.1

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : darwin
```

**Comment by millsp** [comment]
This happens because by assigning a class method, it has become unbound:

```ts
class C { log() { console.log('c', this) } };
const c = new C();
const log = c.log;

log(); // unbound
c.log(); // bound
log.bind(c) // bound
```

In essence, you should use the prisma calls this way:

```ts
this.prismaService.$transaction(...)
```

You can enable this in your project via [typescript eslint](https://typescript-eslint.io/rules/unbound-method/). I'm marking this issue as closed, but feel free to re-open if you can still reproduce this in some other ways. Thanks!
