### ISSUE TITLE
MDBGA: Prevent users from trying to use referential actions on inline m-n's

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#11087]
_(This issue is a follow-up to: https://github.com/prisma/prisma/issues/10498)_

Currently, the Prisma Schema allows:

```prisma
model A {
  id  String  @id @default(dbgenerated()) @map("_id") @db.ObjectId
  gql String?

  b_ids String[] @db.Array(ObjectId)
  bs    B[]      @relation(fields: [b_ids], onDelete: Cascade)
}

model B {
  id  String  @id @default(dbgenerated()) @map("_id") @db.ObjectId
  gql String?

  a_ids String[] @db.Array(ObjectId)
  as    A[]      @relation(fields: [a_ids], onDelete: Cascade)
}
```

But we don't support referential actions on m-ns for MongoDB. We should:

- Invalidate this in prisma format and provide a helpful error. Perhaps link to the documentation to learn how to workaround it.
- Document this limitation in [our documentation](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb). We can tell people to use an explicit join table as a workaround.

Later on, we can consider adding referential action support to this type of schema.

**Comment by matthewmueller** [comment]
This appears to already be the case:

<img width="1465" alt="CleanShot 2022-01-14 at 18 07 23@2x" src="https://user-images.githubusercontent.com/170299/149600146-95519dd5-ab5f-499a-8903-d37ce217835b.png">

**Comment by matthewmueller** [comment]
Just tested with combos of onUpdate, onDelete, Cascade and SetNull. The errors are correct.

**Comment by janpio** [comment]
Indeed via https://github.com/prisma/prisma-engines/pull/2561, unfortunately no issues were closed like this one or https://github.com/prisma/prisma/issues/10861.
