### ISSUE TITLE
Referential integrity is not preserved when updating foreign key (in "prisma" mode)

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma#11100]
## Overview

Consider this datamodel

```prisma
model User {
  id       Int       @id @map("_id")
  idd      Int       @unique
  comments Comment[]
}

model Comment {
  id          Int     @id @map("_id")
  name        String?
  writtenById Int
  writtenBy   User    @relation(fields: [writtenById], references: [idd], onUpdate: Cascade, onDelete: Cascade)
}
```

And this update mutation:

```graphql
mutation {
  updateOneComment(where: { id: 1 }, data: { writtenById: 2 }) {
    id
  }
}
```

This operation is currently allowed, _even_ when there's no existing user with `idd: 2`.

## Expected behavior

Before doing the update, we should do a read to ensure that the value of the foreign key it's about to be updated to actually refers to an existing record.

## Problems 😭

For `Int` ids, `update` supports multiple operations:

- Set (easy)
- Increment
- Decrement
- Divide
- Multiply

Even though it probably makes no sense to update an id by multiplying it, we have to decide what to do.

**Comment by dpetrick** [comment]
We decided this is expected behavior for now, additional measures to guarantee or emulate integrity in Mongo can backfire for certain use-cases, so we'll see if the above finds demand first before we include it.
