### ISSUE TITLE
@prisma/sdk v3.8.0:  Cannot find module 'fs-jetpack'

### ISSUE THREAD

**Issue by valentinpalkovic** [prisma/prisma#11126]
### Bug description

Updating from @prisma/sdk v.3.7.0 to @prisma/sdk v3.8.0 produces the following error while doing a simple import from `@prisma/sdk`

Code Example: 

```typescript
import { getDMMF } from '@prisma/sdk'
...
```

Error:
```
Cannot find module 'fs-jetpack' from 'node_modules/@prisma/sdk/dist/utils/jestContext.js'

Require stack:
      node_modules/@prisma/sdk/dist/utils/jestContext.js
      node_modules/@prisma/sdk/dist/index.js
      src/tests/generator.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/@prisma/sdk/dist/utils/jestContext.js:30:36)
```

I think the issue has something to do with the following change:
https://github.com/prisma/prisma/pull/10984/files#diff-7defdb66d87b1af98d5f3645f0da5fec53479a6f59a38af6fd2c9b619dd5f58cR72

`fs-jetpack` is not defined in the `dependencies`, but in the `devDependencies` section of the package.json, therefore fs-jetpack cannot be found.

### How to reproduce

1. Install latest @prisma/sdk (v. 3.8.0)
2. Import something from `@prisma/sdk` (e.g. `import { getDMMF } from '@prisma/sdk'`)
3. Run your program/test
4. See the mentioned error

### Expected behavior

Imports from @prisma/sdk shouldn't produce any errors.

### Prisma information

@prisma/sdk version 3.8.0
Repository: https://github.com/valentinpalkovic/prisma-json-schema-generator
Failing Test run: https://github.com/valentinpalkovic/prisma-json-schema-generator/runs/4781431974?check_suite_focus=true#step:9:11

### Environment & setup

- OS: Github Actions (Linux)
- Node.js version: 12,17

### Prisma Version

```
prisma                  : 3.8.0
@prisma/client          : 3.8.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
```

**Comment by thedavidprice** [comment]
@janpio confirming that we are seeing this on RedwoodJS Framework when attempting to upgrade to v3.8.0. See https://github.com/redwoodjs/redwood/pull/4118

Strangely, it throws when CI runs the lint check.

**Comment by millsp** [comment]
Hey folks, this has been fixed in the latest patch https://github.com/prisma/prisma/releases/tag/3.8.1
