### ISSUE TITLE
v3.7.0 and above immediately crashes Next.js app

### ISSUE THREAD

**Issue by gavrichards** [prisma/prisma#11128]
### Bug description

I've been using Prisma and Next.js together for quite a while.

When I upgrade Prisma to 3.7.0 or above, and then run my Next.js app, it immediately crashes the process when I load any page.

The console just gives:
```
zsh: killed     npm run dev
```

Is there any more useful logging I could get, to help debug this?
Has anything changed in 3.7.0 which could  cause this? I have tested with 3.8.0 too and it gives the same result.
I'm using the latest version of Next.js 12.0.8
Thanks

### Environment & setup

- OS: Mac OS
- Database: MySQL RDS
- Node.js version: 16.13.0

### Prisma Version

```
3.7.0 and above
```

**Comment by janpio** [comment]
> Is there any more useful logging I could get, to help debug this?

You can always enable logging and debugging for Prisma itself: https://pris.ly/d/logging + https://pris.ly/d/debugging But as your _application_ is crashing, that might not even give you much. Let's see.

**Comment by gavrichards** [comment]
Thanks, so with both those things enabled, I get this:

> Server started on https://local.dev:3000
wait  - compiling / (client and server)...
info  - Using external babel configuration from /Users/[redacted]/.babelrc
event - compiled client and server successfully in 516 ms (1195 modules)
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables loaded from /Users/[redacted]/prisma/.env +0ms
  prisma:tryLoadEnv Environment variables not found at null +1ms
  prisma:tryLoadEnv Environment variables loaded from /Users/[redacted]/prisma/.env +0ms
  prisma:client clientVersion: 3.8.0 +0ms
  prisma:client clientEngineType: library +0ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client:libraryEngine Searching for Query Engine Library in /Users/[redacted]/node_modules/.prisma/client +4ms
  prisma:client:libraryEngine loadEngine using /Users/[redacted]/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
zsh: killed     npm run dev

**Comment by janpio** [comment]
Can you show the comparison of the older version running?

**Comment by gavrichards** [comment]
Sure:
> Server started on https://local.dev:3000
wait  - compiling / (client and server)...
info  - Using external babel configuration from /Users/[redacted]/.babelrc
event - compiled client and server successfully in 599 ms (1195 modules)
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables loaded from /Users/[redacted]/prisma/.env +0ms
  prisma:tryLoadEnv Environment variables not found at null +1ms
  prisma:tryLoadEnv Environment variables loaded from /Users/[redacted]/prisma/.env +0ms
  prisma:client clientVersion: 3.6.0 +0ms
  prisma:client clientEngineType: library +1ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client:libraryEngine Search for Query Engine Library in /Users/[redacted]/node_modules/.prisma/client +4ms
  prisma:client:libraryEngine loadEngine using /Users/[redacted]/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
Refresh token with api
You are the first - lets start the new promise
wait  - compiling /api/auth/refresh-token...
event - compiled client and server successfully in 167 ms (1209 modules)
  prisma:client Prisma Client call: +393ms
  prisma:client prisma.refreshToken.findUnique({
  prisma:client   select: {
... etc ...
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findUniqueRefreshToken(where: {
  prisma:client     id: "....."
  prisma:client   }) {
... etc ...
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: false +393ms
  prisma:client:libraryEngine library starting +0ms
prisma:info Starting a mysql pool with 5 connections.
  prisma:client:libraryEngine library started +204ms
... etc

"Refresh token with api" is from my code.

**Comment by janpio** [comment]
So it seems between `new PrismaClient()` and your `console.log("Refresh token with api")` the application crashes. Can you share the code that is excecuted in between? (Is this all outside a request to the app, so all on startup?)

**Comment by gavrichards** [comment]
I totally appreciate why you've asked for that, but that's quite difficult to pin down.

I don't know if this helps, but this is how I initiate Prisma. It's based on [this comment](https://github.com/prisma/prisma-client-js/issues/228#issuecomment-618433162) for managing connections in a serverless environment.

```
import {PrismaClient} from '@prisma/client';

/**
 * @type PrismaClient
 */
let prisma;

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient();
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient();
  }

  prisma = global.prisma;
}

export default prisma;
```

**Comment by janpio** [comment]
Yep, that is fine - the question is where this gets executed and what code runs in between that and then the logging of the "Refresh token with api"?

As we have no other reports of Nextjs apps crashing, I have to act under the assumption that something between the first missing log output ("Refresh token with api") and where Prisma Client is instantiated (we know that still happens as we have related log output) is causing your app to crash. The more log outputs you can put there closer to the `new PrismaClient();` the better. Maybe just add it in the line after that one actually and see if it is output with 3.7.0+

**Comment by gavrichards** [comment]
Ok thanks, I'll get lots of console logs dropped in and see where we get to.

**Comment by gavrichards** [comment]
Ok, so console logs after `new PrismaClient()` appear. They're logged anywhere they're placed outside of functions, but any I place inside functions don't appear. This includes in the default export in `_app.js`.

**Comment by janpio** [comment]
Sorry, I don't fully understand. Which logs are working and which are not?

**Comment by gavrichards** [comment]
So as an example:

```
import Whatever from 'wherever';
console.log('This log appears');

function App() {
  console.log("This log doesn't appear");
};

export default App;
```

So this produces:

```
...
wait  - compiling / (client and server)...
event - compiled client and server successfully in 435 ms (1195 modules)
This log appears
zsh: killed     npm run dev
```

Logs before and after `new PrismaClient()` all appear.

**Comment by janpio** [comment]
Hm. Can you maybe create a minimal reproduction app with a new Next.js project?

**Comment by gavrichards** [comment]
Well I'm baffled. Without doing anything, it's just suddenly started working. I'm now on Prisma 3.8.0 and it's working perfectly. I can't explain it, and I'm never keen on behaviour changing without explanation but I'm not sure what else to say. Thank you for your assistance, I'll be back if the problem returns.

**Comment by janpio** [comment]
No worries, we like when things just solve itself magically :D Let us know if this ever happens again, and we can take another look. Probably some Node dependency cache thing or whatever. It's usually one of those.

**Comment by salockhart** [comment]
FWIW I ran into this exact same problem. Running `rm -rf node_modules; npm i` fixed it for me, so likely something strange being cached.

**Comment by idolize** [comment]
I just updated from Prisma `3.8.1` to `3.9.1` on an express application and saw, shortly after initializing the PrismaClient instance, my whole server process get killed via SIGKILL.

I reduced the application code more and more until it was basically doing nothing but initializing Prisma - and when commenting out the Prisma code or reverting back to the old version it would work fine.

After finding this thread I tried a `rm -rf node_modules; npm i` and it started working again. Maybe still worth looking into whatever kind of caching the prisma module is doing, especially after updates? Or even recommending a full node_modules wipe on every update in the Release notes? I know this would have saved me some time and headache.

I'm using `npm -v` 8.1.3 and `node -v` v16.13.0.

**Comment by xpressui** [comment]
Seeing the same thing that @idolize did at prisma 3.9.2, npm 8.3.1, and v17.4.0.

**Comment by ryanpag3** [comment]
I ran into this as well. I know it's not _technically_ in prisma's scope to account for weird node caching issues, but maybe this could be documented more clearly when performing an upgrade to the prisma library? This was a rather painful thing to figure out.

**Comment by okomarov** [comment]
Had the same issue upgrading from 3.7.0 -> 3.11.0, Node 16.3.0 and yarn 1.22.17: 
```
[INFO] 18:01:36 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.5)
Debugger listening on ws://127.0.0.1:9229/2faa48f9-b3ff-45e5-9040-55e5a15629bf
For help, see: https://nodejs.org/en/docs/inspector
  prisma:tryLoadEnv Environment variables loaded from /Users/okomarov/Documents/repo/api/.env +0ms
  prisma:tryLoadEnv Environment variables loaded from /Users/okomarov/Documents/repo/api/.env +755ms
  prisma:client clientVersion: 3.11.0 +0ms
  prisma:client clientEngineType: library +0ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client:libraryEngine Searching for Query Engine Library in /Users/okomarov/Documents/repo/api/node_modules/.prisma/client +36ms
  prisma:client:libraryEngine loadEngine using /Users/okomarov/Documents/repo/api/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
  ``` 
and solved by reinstalling node modules as in https://github.com/prisma/prisma/issues/11128#issuecomment-1019264372

**Comment by Wyctus** [comment]
I also had this issue (not in Next) right now on macOS. Removing the `./node_modules/.prisma` folder and running `prisma generate` again solved this issue. 

I hope it helps somebody.
