### ISSUE TITLE
`db pull` gives different schema on CockroachDB compared with PostgreSQL

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma#11158]
### Bug description

I'm writing a Getting Started guide for CockroachDB and I'm testing out creating a serverless cluster on Cockroach Cloud, adding some example SQL, and then using `db pull` to pull in the schema.

I'm using the same SQL as the [PostgreSQL Getting Started example](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/introspection-typescript-postgres) (see below), but when I pull I get a different Prisma schema to the one in the PostgreSQL example.

Raising an issue on @janpio's recommendation so this can be investigated further.

### How to reproduce

1. Create a CockroachDB serverless cluster and connect to it
2. Run the following SQL commands:
	  ```sql
	    CREATE TABLE "public"."User" (
	    id SERIAL PRIMARY KEY NOT NULL,
	    name VARCHAR(255),
	    email VARCHAR(255) UNIQUE NOT NULL
	  );
	  
	  CREATE TABLE "public"."Post" (
	    id SERIAL PRIMARY KEY NOT NULL,
	    title VARCHAR(255) NOT NULL,
	    "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
	    content TEXT,
	    published BOOLEAN NOT NULL DEFAULT false,
	    "authorId" INTEGER NOT NULL,
	    FOREIGN KEY ("authorId") REFERENCES "public"."User"(id)
	  );
	  
	  CREATE TABLE "public"."Profile" (
	    id SERIAL PRIMARY KEY NOT NULL,
	    bio TEXT,
	    "userId" INTEGER UNIQUE NOT NULL,
	    FOREIGN KEY ("userId") REFERENCES "public"."User"(id)
	  );
	  ```
3. Create a new Prisma project with the following schema file, and save the Cockroach connection string to the `.env` file:
	  ```prisma
	  generator client {
	    provider        = "prisma-client-js"
	    previewFeatures = ["cockroachdb"]
	  }
	  
	  datasource db {
	    provider = "cockroachdb"
	    url      = env("DATABASE_URL")
	  }
	  ```
4. Run `npx prisma db pull`

This gave me the following schema: 

```prisma
model Post {
  id        BigInt   @id(map: "primary") @default(autoincrement())
  title     String   @db.VarChar(255)
  createdAt DateTime @default(now()) @db.Timestamp(6)
  content   String?
  published Boolean  @default(false)
  authorId  BigInt
  User      User     @relation(fields: [authorId], references: [id], onDelete: NoAction, onUpdate: NoAction, map: "fk_authorId_ref_User")
}

model Profile {
  id     BigInt  @id(map: "primary") @default(autoincrement())
  bio    String?
  userId BigInt  @unique
  User   User    @relation(fields: [userId], references: [id], onDelete: NoAction, onUpdate: NoAction, map: "fk_userId_ref_User")
}

model User {
  id      BigInt   @id(map: "primary") @default(autoincrement())
  name    String?  @db.VarChar(255)
  email   String   @unique @db.VarChar(255)
  Post    Post[]
  Profile Profile?
}
```

### Expected behavior

I was expecting the schema from the PostgreSQL example instead:

```prisma
model Post {
  id        Int      @id @default(autoincrement())
  title     String   @db.VarChar(255)
  createdAt DateTime @default(now()) @db.Timestamp(6)
  content   String?
  published Boolean  @default(false)
  authorId  Int
  User      User     @relation(fields: [authorId], references: [id])
}

model Profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  userId Int     @unique
  User   User    @relation(fields: [userId], references: [id])
}

model User {
  id      Int      @id @default(autoincrement())
  name    String?  @db.VarChar(255)
  email   String   @unique @db.VarChar(255)
  Post    Post[]
  Profile Profile?
}
```

### Prisma information

My full Prisma schema after pulling is:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["cockroachdb"]
}

datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}

model Post {
  id        BigInt   @id(map: "primary") @default(autoincrement())
  title     String   @db.VarChar(255)
  createdAt DateTime @default(now()) @db.Timestamp(6)
  content   String?
  published Boolean  @default(false)
  authorId  BigInt
  author    User     @relation(fields: [authorId], references: [id], onDelete: NoAction, onUpdate: NoAction, map: "fk_authorId_ref_User")
}

model Profile {
  id     BigInt  @id(map: "primary") @default(autoincrement())
  bio    String?
  userId BigInt  @unique
  user   User    @relation(fields: [userId], references: [id], onDelete: NoAction, onUpdate: NoAction, map: "fk_userId_ref_User")
}

model User {
  id      BigInt   @id(map: "primary") @default(autoincrement())
  name    String?  @db.VarChar(255)
  email   String   @unique @db.VarChar(255)
  posts   Post[]
  profile Profile?
}
```

### Environment & setup

- OS: Mac OS
- Database: CockroachDB
- Node.js version: v16.13.0

### Prisma Version

```
3.8.0
```

**Comment by janpio** [comment]
The observed differences here are:
1. `Int` => `BigInt`
1. `@id` => `@id(map: "primary")`
1. `@relation(fields: [authorId], references: [id])` => `@relation(fields: [authorId], references: [id], onDelete: NoAction, onUpdate: NoAction, map: "fk_authorId_ref_User")`, so:
	a. additional `onDelete: NoAction, onUpdate: NoAction`
	b. additional `map: "fk_authorId_ref_User"`

**Comment by janpio** [comment]
SQL:
```sql
CREATE SEQUENCE table_name_id_seq3;
CREATE TABLE "int4_sequence" (
  id int4 NOT NULL DEFAULT nextval('table_name_id_seq3'),
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL
);
ALTER SEQUENCE table_name_id_seq3 OWNED BY "int4_sequence".id;

CREATE TABLE "serial" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL
);
```

Resulting schemas via Introspection:
```prisma
model int4_sequence {
  id    Int     @default(autoincrement())
  name  String? @db.VarChar(255)
  email String  @unique @db.VarChar(255)
}

model serial {
  id    BigInt  @id(map: "primary") @default(autoincrement())
  name  String? @db.VarChar(255)
  email String  @unique @db.VarChar(255)
}
```

**Comment by janpio** [comment]
Analysis:

> Int => BigInt
This is a default CockroachDB thing.

> @id => @id(map: "primary")
CockroachDB names their primary keys different than PostgreSQL (which is our standard that we do not render).

> @relation(fields: [authorId], references: [id]) => @relation(fields: [authorId], references: [id], onDelete: NoAction, onUpdate: NoAction, map: "fk_authorId_ref_User"), so:
> a. additional onDelete: NoAction, onUpdate: NoAction

This is actually outdated in our PostgreSQL schema in the docs and should be updated: https://github.com/prisma/docs/issues/2752

> b. additional map: "fk_authorId_ref_User"

CockroachDB names their foreign keys with a different pattern than PostgreSQL (which is our standard that we do not render).
 




https://github.com/prisma/docs/issues/2752

**Comment by Jolg42** [comment]
So not a bug in the end? (see labels)

**Comment by janpio** [comment]
Still figuring that out really, in the context of the docs it probably is but not for our actual implementation fortunately.

**Comment by Jolg42** [comment]
Also my understanding 👍🏼

**Comment by janpio** [comment]
To be documented as limitations here: https://github.com/prisma/docs/pull/2737/files#r789828158
