### ISSUE TITLE
Prisma not able to find tables in sqlite database

### ISSUE THREAD

**Issue by varora1406** [prisma/prisma#11159]
### Bug description

Prisma is trying to find "main.`tableName`, where as it should directly find "`tableName`".
I see no problem with models, or typescript errors.

But neither query runs dynamically, nor `prisma studio` is able to resolve this

### How to reproduce

Use https://github.com/varora1406/prisma-sqllite-example
Add `.env` file with sqlLite database URL. Example - `DATABASE_URL="file:./dev.db"`

Install dependencies - `yarn install`
Run prisma - `yarn prisma generate`
Run project file - `yarn dev`

Now to check if data is added, run `yarn prisma studio`
And open URL  and check no data is added. Moreover try to access `List` OR `Users` Table, you will see error popup

### Expected behavior

Prisma should be able to find Tables mentioned in prisma schema

### Prisma information

Prisma Schema - 

``` 
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model List {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  channelId String
  users     User[]
}

model User {
  id     String   @id
  List   List? @relation(fields: [listId], references: [id])
  listId Int?
}
```

Prisma Client queries - 
``` 
prisma.list.create({
    data: {
      channelId: 'C0G9J9Q9F',
      users: {
        create: [{ id: 'dcvds' }, { id: 'dvds' }]
      }
    }
  }) 
```

### Environment & setup

- OS: Mac OS
- Database: SQLite
- Node.js version: 14.18.1

### Prisma Version

```
prisma                  : 3.8.0
@prisma/client          : 3.8.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
```

**Comment by janpio** [comment]
Per `npx prisma db pull` the SQLite database included in the reproduction repository looks like this instead of the schema above (or in the repo):

```
model Post {
  authorId  Int?
  content   String?
  id        Int     @id @default(autoincrement())
  published Boolean @default(false)
  title     String
  User      User?   @relation(fields: [authorId], references: [id])
}

model User {
  email String  @unique(map: "User.email")
  id    Int     @id @default(autoincrement())
  name  String?
  Post  Post[]
}
```

**Comment by varora1406** [comment]
oh yes, you are right.

I didn't ran the `prisma db push`. it's working fine after that, thanks
