### ISSUE TITLE
MySQL, PlanetScale error: PrismaClientKnownRequestError: ... column `(not available)` ...

### ISSUE THREAD

**Issue by jde** [prisma/prisma#11160]
### Bug description

I am receiving this error: 
```
PrismaClientKnownRequestError: The column `(not available)` does not exist in the current database.
```
When trying to run a find query.

The challenge is that when I run this locally through a pscale tunnel to my production db, the error does _not_ occur. The error only occurs after I've deployed and am trying to run this query from my live domain.

It is hard to reason about this due to the obscurity of column '(not available)'.

I've checked and double checked that all my production db does indeed contain all the columns that are in my schema for these types. Also, the fact that I can run locally confirms this.

I understand that the variation in environments could point to something deployment side, but I have spent a good hour now trying to understand what that could be.

How can I interpret the Column ('not found')? Has there been any other reports of variations in behavior where a program is successful from a local environment but then gets these errors from a deployment in vercel?

Sorry for the fuzzy bug report, but my prod app is broken and I'm not able to reason about the issue due to the vague error message. 

Thanks in advance for any advice!

### How to reproduce

Challenging as I am seeing differing behavior locally and in production.

### Prisma information

```
prisma.trip.findMany({
        where: {
            organizerId: userId,
        },
        include: {
            organizer: true,
            property: true,
            services: true,
        }
    })
```

### Environment & setup

Local: osx
Prod: vercel

### Prisma Version

```
prisma                  : 3.8.0
@prisma/client          : 3.8.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
Preview Features        : referentialIntegrity
```

**Comment by janpio** [comment]
"not available" unfortunantely is limitation of PlanetScale/Vitess.

Can you try logging the query Prisma is trying to send via https://pris.ly/d/logging and send it via a raw query instead? If the problem stays the same, can you run it manually against the connection your application is using?

**Comment by jde** [comment]
When I came back to this hours later the problem no longer existed. If it comes up again I will log the queries and open a fresh issue.

Thanks!
