### ISSUE TITLE
Error on following the PostgreSQL 'Query your database' Getting Started Guide while using CockroachDB

### ISSUE THREAD

**Issue by keerlu** [prisma/prisma#11161]
### Bug description

This follows on from #11158 and uses the same setup.

The problem occurred after I pulled in the schema given in that issue, and while trying to follow the steps in the [Install Prisma Client](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/install-prisma-client-typescript-postgres) and [Query your database](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/querying-the-database-typescript-postgres) sections of the Postgres Getting Started guide.

### How to reproduce

1. Follow steps in #11158.
2. Install and generate Prisma Client:
```
npm install @prisma/client
npx prisma generate
```
3. Create a new `index.ts` file in the project and add the following query:
```
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.user.create({
    data: {
      name: 'Alice',
      email: 'alice@prisma.io',
      posts: {
        create: { title: 'Hello World' },
      },
      profile: {
        create: { bio: 'I like turtles' },
      },
    },
  })

  const allUsers = await prisma.user.findMany({
    include: {
      posts: true,
      profile: true,
    },
  })
  console.dir(allUsers, { depth: null })
}

main()
  .catch((e) => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```
4. Run `npx ts-node index.ts`. This gives the following output:

```
[
  {
    id: 727744126442897409n,
    name: 'Alice',
    email: 'alice@prisma.io',
    posts: [
      {
        id: 727744126657953793n,
        title: 'Hello World',
        createdAt: 2022-01-14T11:38:02.211Z,
        content: null,
        published: false,
        authorId: 727744126442897409n
      }
    ],
    profile: {
      id: 727744126875959297n,
      bio: 'I like turtles',
      userId: 727744126442897409n
    }
  }
]
```

5. Replace the `main` function with the following and then run `npx ts-node index.ts` again:
```
async function main() {
  const post = await prisma.post.update({
    where: { id: 1 },
    data: { published: true },
  })
  console.log(post)
}
```

This gives the following error:

```
/Users/keer/Documents/repos/cockroach-test/node_modules/@prisma/client/runtime/index.js:38692
          throw new PrismaClientKnownRequestError(message, e.code, this.prisma._clientVersion, e.meta);
                ^
PrismaClientKnownRequestError:
Invalid `prisma.post.update()` invocation in
/Users/keer/Documents/repos/cockroach-test/index.ts:6:34

  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   const post = await prisma.post.update(
  An operation failed because it depends on one or more records that were required but not found. Record to update not found.
    at cb (/Users/keer/Documents/repos/cockroach-test/node_modules/@prisma/client/runtime/index.js:38692:17) {
  code: 'P2025',
  clientVersion: '3.8.0',
  meta: { cause: 'Record to update not found.' }
```

### Expected behavior

I expected the `create` query in step 4 to create a record with an `id` of 1, as in the Postgres example, so that the `update` query would then succeed.

### Prisma information

See #11158

### Environment & setup

- OS: Mac OS
- Database: CockroachDB
- Node.js version: 16.13.0

### Prisma Version

```
3.8.0
```

**Comment by janpio** [comment]
The "problem" here seems to be that simple SQL that usually creates an `Int` colum with auto increment that by default starts with 1 on PostgreSQL, creates a `BigInt` column that starts with a very large BigInt value instead:

```sql
CREATE TABLE "User" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL
);

INSERT INTO "User" (name, email) VALUES
    ('foo', 'foo@example.org');
    
SELECT * FROM "User";
```

Leads to:
```sql
INSERT INTO user (id,"name",email) VALUES
	 (727883342170128386,'foo','foo@example.org');
```

**Comment by janpio** [comment]
This is indeed intended, as the schema is intended to be as described in https://github.com/prisma/prisma/issues/11158.

To make this work here anyway, the suggestion is to edit the `where` to be by something we created and know instead of the (magic) id which this time has a different value. Things to try @keerlu: Search by the `Post.title` or the `Post.author.email`. (Second might be easier as it is a unique column)
