### ISSUE TITLE
MongoDB Introspection Multiple Types warning message in CLI output does not differentiate models and embedded documents

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11179]
```
// The following fields had data stored in multiple types. The most common type was chosen. If loading data with a type that does not match the one in the data model, the client will crash. Please see the issue: https://github.com/prisma/prisma/issues/9654
// - Model "MoviesImdb", field: "rating", chosen data type: "Double"
// - Model "MoviesImdb", field: "votes", chosen data type: "Int32"
```

Actual affected `type` not `model`:
```
type MoviesImdb {
  id_    Int   @map("id")
  /// Multiple data types found: String: 0.1%, Double: 99.9% out of 1000 sampled entries
  rating Float
  /// Multiple data types found: String: 0.1%, Int32: 99.9% out of 1000 sampled entries
  votes  Int
}
```

via https://github.com/prisma/introspection-ci/commit/d52f2907214e969ab7720f40790e3f0633d3d322#diff-e53417a3309dc6c499451c73ca81cb52af9a635a3c2796494a18343f2be97890

**Comment by Jolg42** [comment]
This is done and tested in engines.

@pimeys Do you have an example of the new message that is printed now?

Needs to be added on TS side with a test
Example from the engine PR
```
    res.assert_affected(json!([{
        "compositeType": "CatAddress",
        "field": "number",
        "tpe": "String",
    }]));
```

**Comment by Jolg42** [comment]
Note the engine will be available with https://github.com/prisma/prisma/pull/11624

**Comment by pimeys** [comment]
I think the js side prints the message out of this data. I'd say if the data holds `compositeType` field, print:
```
- Type "MoviesImdb", field: "rating", chosen data type: "Double"
```
Otherwise
```
- Model "MoviesImdb", field: "rating", chosen data type: "Double"
```

**Comment by Jolg42** [comment]
Sounds good, thanks!

**Comment by Jolg42** [comment]
Comment from Julius

> This can also trigger warnings, they come in the same form as with the issue I'm commenting here
> https://github.com/prisma/prisma-engines/pull/2651
> so probably a good idea to check too
