### ISSUE TITLE
MongoDB: Collection with field with array content is not introspected with native type `@db.Array`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11187]
Take this collection:

```json
[{
  "_id": {
    "$oid": "61e20bbc7fef3b66f439373a"
  },
  "name": "Sports",
  "post_ids": [
    {
      "$oid": "61e20bbc7fef3b66f4393737"
    }
  ]
},{
  "_id": {
    "$oid": "61e20bbd7fef3b66f439373b"
  },
  "name": "Fashion",
  "post_ids": [
    {
      "$oid": "61e20bbc7fef3b66f4393737"
    }
  ]
},{
  "_id": {
    "$oid": "61e20bbd7fef3b66f439373c"
  },
  "name": "Programming",
  "post_ids": [
    {
      "$oid": "61e20bbc7fef3b66f4393737"
    },
    {
      "$oid": "61e20bbc7fef3b66f4393739"
    }
  ]
}]
```

Introspection result is:
```prisma
model Category {
  id       String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  name     String   @unique
  post_ids String[] @db.ObjectId
}
```

But should be:
```prisma
model Category {
  id       String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  name     String   @unique
  post_ids String[] @db.Array(ObjectId)
}
```

**Comment by janpio** [comment]
(This is not _really_ a bug, as this behavior does not exist anywhere else yet and is connected to the new MongoDB relation type we might be introducing)

**Comment by matthewmueller** [comment]
How do we handle scalar lists with native types in other databases? 

For example, in Postgres is it:

```prisma
money Decimal[] @db.Money
```

or 

```prisma
money Decimal[] @db.Array(Money)
```

If it's the latter, I'd consider it a bug. If it's the former, then we might want to adjust how we're doing it in MongoDB

**Comment by matthewmueller** [comment]
Interesting, looks like it's this in Postgres:

```
model moneys {
  id     Int       @id @default(autoincrement())
  moneys Decimal[] @db.Money
}
```

**Comment by matthewmueller** [comment]
Okay, so it turns out the way we're doing it in MongoDB is wrong right now. 

This is the correct syntax: `post_ids String[] @db.ObjectId`, I need to test that it works in the client.

**Comment by matthewmueller** [comment]
Closing this issue since introspection is working as expected. I'll link to another issue if there's more work to be done.

**Comment by janpio** [comment]
See related internal discussion @matthewmueller: https://www.notion.so/prismaio/Design-discussion-the-Array-native-type-on-MongoDB-c67615379df6453d88d5d7b7e9768966
