### ISSUE TITLE
PANIC: Expected record selection to contain required model ID fields.: ConversionFailure("\"c266149d-e045-4db5-bee4-3e49f3252e65\"", "Int") in query-engine/core/src/interpreter/interpreter.rs:68:26

### ISSUE THREAD

**Issue by edmbn** [prisma/prisma#11191]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.13.0           | 
| OS              | darwin-arm64       |
| Prisma Client   | 3.8.1              |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /Users/edmbn/Projects/remix/proc-app/.env
prisma:tryLoadEnv Environment variables loaded from /Users/edmbn/Projects/remix/proc-app/.env
prisma:client clientVersion: 3.8.1
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine Searching for Query Engine Library in /Users/edmbn/Projects/remix/proc-app/node_modules/.prisma/client
prisma:client:libraryEngine loadEngine using /Users/edmbn/Projects/remix/proc-app/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
  const organization = await db.organization.update({
    where: { id: organizationId },
    data: {
      name: organizationInformation.name,
    },
  });
```

## Schema
```prisma
model Organization {
  id                      Int                      @id @default(autoincrement())
  name                    String
  processes               Process[]
}

model Process {
  id             String               @id @default(uuid()) @db.VarChar(36)
  description    String?              @db.LongText
  organizationId Int
  organization   Organization         @relation(fields: [organizationId], references: [id], onDelete: Cascade, onUpdate: Cascade)

  @@index([organizationId])
}
```

## Generated SQL
```
CREATE TABLE `Organization` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
```
CREATE TABLE `Process` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci,
  `organizationId` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `Process_organizationId_idx` (`organizationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

## Used database
```
Planetscale
```

The error happens when updating any field of the Organization model.

I'm using `referentialIntegrity` preview feature with option `referentialIntegrity = "prisma"`
Same error happens with prisma studio.

**Comment by agent-ly** [comment]
Experiencing this same issue with MongoDB:
### Schema
```prisma
model User {
  id        Int        @id @map("_id")
  name      String     @unique
  balance   Int        @default(0)
  tags      UserTag[]
  roles     UserRole[]
  depAddrs  String[]
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
  messages  Message[]
}


model Message {
  id        String   @id @default(uuid()) @map("_id")
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
  content   String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

Code
```ts
await this.prisma.user.update({
      where: { id },
      data: {
        roles: {
          push: role,
        },
      },
    });
````

**Comment by agent-ly** [comment]
It should be noted that switching the user model's `id` type to `String` solves the issue.

**Comment by janpio** [comment]
> Experiencing this same issue with MongoDB, however I am not using referential integrity, just default settings for MongoDB

MongoDB has `referentialIntegrity = prisma` enabled implicitly and by default.

**Comment by BurntCaramel** [comment]
Also seeing this issue with MySQL (Planetscale)

**Comment by janpio** [comment]
Can you confirm that the posts above should have all the information necessary for a reproduction @BurntCaramel?

**Comment by edmbn** [comment]
I am having the same issues with onDelete, which is quite critical. Are you experiencing the same problems?

**Comment by justinwaite** [comment]
Also have the issue. I had a user model with an autoincrement id (Int), and a reset token model with a cuid as the ID (String). Changing the reset token id to an Int and using a separate field for the the actual token string fixed the problem for me.

Seems like referential integrity does not like mixing ID data types across entities.

**Comment by jferrettiboke** [comment]
>Seems like referential integrity does not like mixing ID data types across entities.

I can confirm this.

**Comment by janpio** [comment]
Nice, now that you understand the problem, does one of the comments above give a good, simple reproduction? If not, can you ass one please?
