### ISSUE TITLE
Can't find the schema when the project path contains the same name as the generated client folder

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#11206]
https://github.com/prisma/prisma/issues/9435#issuecomment-946414969 by @ykrop:

> I had the same problem after upgrading too. 
> In my case seems to be caused by this code from index.js produced by Prisma npx generate:
> 
> ```
> // folder where the generated client is found
> const dirname = findSync(process.cwd(), [
>   "generated\\admin",
>   "admin",
> ], ['d'], ['d'], 1)[0] || __dirname
> ```
> 
> As I have Prisma on a external folder and casually my project is in a path containing the same name given to generated scheme folder dirname var chose wrong path.
> ```
> Schema output: project/prisma/generated/admin
> Project: project/sites/admin/api
> ```
> 
> To solve it I just changed the generated prisma folder name.
> 
> ```
> Schema output: project/prisma/generated/adminSchema
> ``` 

Extracted from #9435 since it's a different bug than the one most people seem to be facing in the issue (and for which we have a fix in https://github.com/prisma/prisma/pull/10804), albeit both were uncovered at the same time by fixing another bug that used to mask these two in https://github.com/prisma/prisma/pull/9295.

**Comment by janpio** [comment]
Ok, to highlight the problem here as I did not instantly see it: 

The problem is that both `project/prisma/generated/admin` (Schema output path) and `project/sites/admin/api` (project path) include `admin` which makes the schema finding logic match on the wrong folder.
