### ISSUE TITLE
'Create bug report'

### ISSUE THREAD

**Issue by ThiagoMouro** [prisma/prisma#11217]
[](url)I have a bug in intgegration with Okta.

Authentication Failed!
We can’t log you in. Please review your SSO settings.

But, I used documentation: (https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/manage-prisma-cloud-administrators/setup-sso-integration-on-prisma-cloud/setup-sso-integration-on-prisma-cloud-for-okta.html#:~:text=To%20secure%20administrator%20access%20to,complete%20the%20setup%20on%20Okta.)))))

I need your help, please.

**Comment by ThiagoMouro** [comment]
My email is thiago.mouro@dock.tech.

My license is corporate.

**Comment by pantharshit00** [comment]
This is Prisma ORM project. We are not Palo Alto's Prisma Cloud offering. Please contact them and please do not report any issues regarding that product in this repository.
