### ISSUE TITLE
Change `@db.Array(ObjectId)` to `@db.ObjectId`

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#11226]
## Problem

The recommended way to model many-to-many's is with a list of ObjectIDs. Taken from [our documentation](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb):

```prisma
model Post {
  id          String     @id @default(dbgenerated()) @map("_id") @db.ObjectId
  categoryIDs String[]   @db.Array(ObjectId)
  categories  Category[] @relation(fields: [categoryIDs])
}

model Category {
  id      String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  postIDs String[] @db.Array(ObjectId)
  posts   Post[]   @relation(fields: [postIDs])
}
```

The `@db.Array(ObjectId)` doesn't align with our other databases, which would represent the native type as `@db.X` See [this comment](https://github.com/prisma/prisma/issues/11187#issuecomment-1014780857) for how other databases handle it. 

## Suggested solution

Align MongoDB with the other databases

```diff
model Post {
  id          String     @id @default(dbgenerated()) @map("_id") @db.ObjectId
- categoryIDs String[]   @db.Array(ObjectId)
+ categoryIDs String[]   @db.ObjectId
  categories  Category[] @relation(fields: [categoryIDs])
}

model Category {
  id      String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
- postIDs String[] @db.Array(ObjectId)
+ postIDs String[] @db.ObjectId
  posts   Post[]   @relation(fields: [postIDs])
}
```

Using [this example](https://github.com/matthewmueller/prisma-mongodb-relations) repository, I tried removing `@db.Array`, re-generating and running the Prisma Client, I get the following run-time error:

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', query-engine/connectors/mongodb-query-connector/src/root_queries/read.rs:112:74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientUnknownRequestError: 
Invalid `prisma.post.findMany()` invocation in
/Users/m/dev/src/github.com/prisma/prisma-mongodb-relations/index.ts:6:35

  3 
  4 async function main() {
  5   // From the post side
→ 6   const posts = await prisma.post.findMany(
  called `Option::unwrap()` on a `None` value
    at cb (/Users/m/dev/src/github.com/prisma/prisma-mongodb-relations/node_modules/@prisma/client/runtime/index.js:38695:17) {
  clientVersion: '3.9.0-dev.15'
```

Some additional todos:
- [x] Fix breaking behavior in Query Engine
- [x] Invalidate `@db.Array(...)` in schema validation (for `prisma format` etc)
	- [x] Consider the migration path from the internal document: https://www.notion.so/prismaio/Design-discussion-the-Array-native-type-on-MongoDB-c67615379df6453d88d5d7b7e9768966#0f2fc74fff0548cbb0265746d854f4ed
- [ ] Communicate this as a "breaking change" in the Release Notes. MongoDB is still in Preview though.
- [ ] Update the docs.

## Additional context

- Internal [design document](https://www.notion.so/prismaio/Design-discussion-the-Array-native-type-on-MongoDB-c67615379df6453d88d5d7b7e9768966)

**Comment by Jolg42** [comment]
I think it was closed by a mention involuntarily. So reopening as it seems some tasks are still to be done.

**Comment by Weakky** [comment]
Left to be done:
- Communicate as breaking change
- Update the docs

**Comment by matthewmueller** [comment]
Docs already has [an issue](https://github.com/prisma/docs/issues/2871) they're tracking and this will be in the release notes. Closing.

**Comment by sam-aydev** [comment]
i am having this same error, and nothing is working out

**Comment by janpio** [comment]
You definitely don't as that change was made years ago. Please open a new issue and describe the actual you are having by filling the issue template. Thank you.
