### ISSUE TITLE
Cannot pass Prisma.empty to $executeRaw function

### ISSUE THREAD

**Issue by mehdi-sp** [prisma/prisma#11233]
### Bug description

We have a function which generates raw queries based on its input. then the generated query will be passed to `$executeRaw` to run it. in some conditions, the function may return `Prisma.empty`. In this case Prisma throws a PrismaClientValidationError 

we had no problems in version 2.30.3, This happened after upgrading "prisma" & "@prisma/client" version  to 3.8.1 

### How to reproduce

`await db.$executeRaw(Prisma.empty);`

throws this error: 
```
    PrismaClientValidationError: `$executeRaw` is a tag function, please use it like the following:
    const result = await prisma.$executeRaw`UPDATE User SET cool = ${true} WHERE email = ${'user@email.com'};`
    
    Or read our docs at https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#executeraw
```

### Expected behavior

to run it without any errors. preferably don't issue any queries if the input is `Prisma.empty`

### Prisma information

N/A

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: 14.17.6

### Prisma Version

```
10.1.0
```

**Comment by janpio** [comment]
Did you try to use `$executeRaw` as tag function as suggested by the output? Between the versions you mentioned the raw queries were overhauled and that was one of the changes. The database page the error links to also spells out the difference between the methods and how they should be used.

**Comment by mehdi-sp** [comment]
> Did you try to use `$executeRaw` as tag function as suggested by the output?

Thanks, it works when I use it like this:
```
await prisma.$executeRaw`${Prisma.empty}`
```

But still
1. $executeRaw() accepts arguments with type `Prisma.Sql`
2. type of `Prisma.empty` is `Prisma.Sql`
from 1 & 2 I assume that it is safe to have this line in code: `await db.$executeRaw(Prisma.empty)`, but it throws an error

**Comment by pantharshit00** [comment]
@mehdi-sp `executeRaw()` (**only the function variant overload**) was renamed to `executeRawUnsafe` in the 3.0.1(https://github.com/prisma/prisma/releases/tag/3.0.1, see the `$queryRaw` API change section) update so please use that now.

**Comment by mehdi-sp** [comment]
As I understand `executeRawUnsafe()` is not exactly equivalent to `executeRaw()`. the first one only accepts string query, but return type of my query generator function is `Prisma.Sql`. it could generate a complex query with lots of `Prisma.join`s, `Prisma.raw`s & `Prisma.sql`s or just return a `Prisma.empty`.
```
function generateQuery(params): Prisma.Sql { 
   if(someCondition) return Prisma.empty;
   return Prisma.join...;
}

const [item] = await prisma.$transaction([
  prisma.items.create(...),
  prisma.$executeRaw(generateQuery(params))
]);
```
I can change `generateQuery`s return type to `Prisma.Sql | null` and conditionally run the returned query, but I think it would be nice to allow `await db.$executeRaw(Prisma.empty)` as it has no type errors (only runtime error)

**Comment by danstarns** [comment]
Also applies to $queryRaw.
