### ISSUE TITLE
[PSL] Do not allow `references` arg on Many2Many relations on SQL

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#11241]
The following datamodel passes validation and is treated as a M:N relation. Its fields and references args though suggest it is a 1:M relation. We should add a validation preventing this confusion and ask the user to either :

- remove the ~~fields and~~ references args to make clear it is a M:N relation
- make the email field singular to clarify that it is a 1:M relation

<img width="632" alt="Screen Shot 2022-01-18 at 10 56 51" src="https://user-images.githubusercontent.com/16278407/149914551-53facbcb-f8eb-42fb-ba13-ec56a1ae5e2d.png">

**Comment by pimeys** [comment]
This kind of is semi-done with https://github.com/prisma/prisma/issues/11553

So now if you add `fields` to any side of the relation, it becomes a 2-way embedded m:n and gives a validation error if not using MongoDb. What's still missing is validating against using `references` in implicit m:n.

**Comment by tomhoule** [comment]
TBD: we always allowed references as long as it points to the single-field id on the other side. Do we want to forbid it?

**Comment by janpio** [comment]
That would really tighten the PSL. It is all we document and support, so there is no benefit in allowing it (besides being laxer in schema creation). @do4gr?

**Comment by janpio** [comment]
`fields` is already disallowed since we introduced embedded m:n for MongoDB. Updated the title to reflect that.
