### ISSUE TITLE
1 to 1 relations get @unique applied. 

### ISSUE THREAD

**Issue by michaelbuller** [prisma/prisma#11272]
I am having an issue with Prisma 1 to 1 relationships,  prisma formats my relation with @unique which creates a unique constraint on the column.  This makes it to where the field can only have 1 null in it.  The opposite table is optional, I have set the relation with ? on them so that it reflects, but this @unique getting added prevents the data from saving after the first record is added to the system.

```
model Intake {
   legalCase    LegalCase?         @relation("LegalCase_intake")
}

model LegalCase {  
  ...
  intakeId     String?         
  intake       Intake?         @relation(name: "LegalCase_intake", fields: [intakeId], references: [id])
```

After I run prisma apply the intakeId looks like this ...
```
intakeId     String?         @unique
intake       Intake?         @relation(name: "LegalCase_intake", fields: [intakeId], references: [id])
```

**Comment by michaelbuller** [comment]
When I try to save... 
{
    "errors": [
        {
            "message": "\nInvalid `prisma.intake.create()` invocation:\n\n\n  Unique constraint failed on the constraint: `dbo.LegalCase`",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "created"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "code": "P2002",
                    "clientVersion": "3.8.1",
                    "meta": {
                        "target": "dbo.LegalCase"

**Comment by janpio** [comment]
Do you want to be able to use the same `intakeId` on multiple `LegalCase`s?

**Comment by michaelbuller** [comment]
No they are 1 to 1.  But the intake gets created first.

**Comment by janpio** [comment]
What is the query you are executing?
Can you turn on https://pris.ly/d/debugging and https://pris.ly/d/logging and post teh output here?

**Comment by michaelbuller** [comment]
legalCase:
          input.legalCase != null
            ? {} : undefined 
I ended up patching my prisma call to check if the legal case is included in the call, and if not, dont send it through.
