### ISSUE TITLE
Migration doesn't sync with database when using `@default(dbgenerated("CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)"))`

### ISSUE THREAD

**Issue by ebaer-payix** [prisma/prisma#11318]
### Bug description

I have been having an issue with the behavior of the @updatedAt, see: [Enhance @updatedAt Migration output DDL #7724](https://github.com/prisma/prisma/issues/7724)

Based on a conversation there, I tried alternative solution that looked promising.
Basically, using the `@default(dbgenerated("CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)"))` as a temporary workaround.  **I know this is a poor use of this feature, but the existing issue is truly becoming a risky problem.**

It turns out that it generates the correct SQL, and will solve my problem.

However, it has the side effect of never syncing with the Database.  ie: If another migration is run after successfully migrating with this syntax, it just keeps creating a new Migration with all of the same identical changes.

According to your support person, this should still be considered a bug, as it should identify that no changes have been made.

### How to reproduce

Change schema

From:

```
updatedAt           DateTime            @updatedAt
```

To:

```
updatedAt           DateTime            @default(dbgenerated("CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)"))
```

Then run

```
$ npx prisma migrate dev --create-only
$ npx prisma migrate dev
```

Then run

```
$ npx prisma migrate dev --create-only
$ npx prisma migrate dev
```

### Expected behavior

Generates

```
-- AlterTable
ALTER TABLE `SomeTable ` MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
```

One time before actually running the Migration.
Changes are made to the database when the Migration is run.
Additional migrations indicate no changes, and don't create any migration files.

### Prisma information

Old Table Structure

```
model SomeTable {
  id                  Int                 @unique
  createdAt           DateTime            @default(now())
  updatedAt           DateTime            @updatedAt
  deletedAt           DateTime?
}
```

Updated Table Structure

```
model SomeTable {
  id                  Int                 @unique
  createdAt           DateTime            @default(now())
  updatedAt           DateTime            @default(dbgenerated("CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)"))
  deletedAt           DateTime?
}
```

### Environment & setup

OS: Windows 10
Database: MySQL 5.7
Node: v14.15.3
npm/npx: 6.14.9

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
```

**Comment by janpio** [comment]
Can you share the SQL of that table before and after the first migration? Thanks. (`SHOW CREATE TABLE SomeTable`)

**Comment by ebaer-payix** [comment]
BEFORE
======

```
CREATE TABLE `Ach` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `batchIds` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `batchesDate` datetime(3) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deletedAt` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `Ach_batchesDate_idx` (`batchesDate`)
) ENGINE=InnoDB AUTO_INCREMENT=389 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```


AFTER 1st Migration
===================

**SQL Generated for Migration:**

-- AlterTable
ALTER TABLE `Ach` MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

**Resulting Table:**

```
CREATE TABLE `Ach` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `batchIds` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `batchesDate` datetime(3) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deletedAt` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `Ach_batchesDate_idx` (`batchesDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```


AFTER 2nd Migration (no changes made to schema.prisma)
===================

**SQL Generated for Migration:**

-- AlterTable
ALTER TABLE `Ach` MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

**Resulting Table:**

```
CREATE TABLE `Ach` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `batchIds` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `batchesDate` datetime(3) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deletedAt` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `Ach_batchesDate_idx` (`batchesDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

**Comment by janpio** [comment]
Is it correct that the "Before" already had `CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)`?

Besides that seems the first migration added `NOT NULL`, and then the 2nd migration just did exactly the same thing again.

**Comment by janpio** [comment]
Ok, here is a clean reproduction:

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model SomeTable {
  id                  Int                 @unique
  createdAt           DateTime            @default(now())
  updatedAt           DateTime            @updatedAt
  deletedAt           DateTime?
}
```

leads to this SQL via `migrate dev`:

```sql
-- CreateTable
CREATE TABLE `SomeTable` (
    `id` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    UNIQUE INDEX `SomeTable_id_key`(`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

```

Then changing model in schema to:

```schema
model SomeTable {
  id                  Int                 @unique
  createdAt           DateTime            @default(now())
  updatedAt           DateTime            @default(dbgenerated("CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)"))
  deletedAt           DateTime?
}
```

leads to this everytime I run `migrate dev`:
```sql
-- AlterTable
ALTER TABLE `SomeTable` MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
```

**Comment by janpio** [comment]
Possibly related to Introspection problems with this construct as well: https://github.com/prisma/prisma/issues/11374

**Comment by janpio** [comment]
Your problem is similar, but different enough to justify its own issue. Can you please create one @rojer95 and provide all the information the issue template asks for? Thanks.

**Comment by rojer95** [comment]
> Your problem is similar, but different enough to justify its own issue. Can you please create one @rojer95 and provide all the information the issue template asks for? Thanks.

#12574

**Comment by barrynorman** [comment]
Is this fixed?

**Comment by thelinuxlich** [comment]
it's not

**Comment by jkomyno** [comment]
Closing this as a duplicate in favour of https://github.com/prisma/prisma/issues/12574 (which despite being newer, has useful comments to avoid this issue).
