### ISSUE TITLE
Using Prisma adapter with next-auth on a mysql database doesnt work

### ISSUE THREAD

**Issue by anirbanchowdhury** [prisma/prisma#11330]
```
Please create an issue at https://github.com/prisma/prisma/issues/new
    at cb (/Users/aniamritapc/Desktop/with-tailwindcss-app/node_modules/@prisma/client/runtime/index.js:38697:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getUserByAccount (/Users/aniamritapc/Desktop/with-tailwindcss-app/node_modules/@next-auth/prisma-adapter/dist/index.js:11:29) {
  name: 'GetUserByAccountError',
  code: undefined


```
These are all my dependencies 
```

"dependencies": {
    "@heroicons/react": "^1.0.5",
    "@next-auth/prisma-adapter": "^1.0.1",
    "@prisma/client": "^3.8.1",
    "esm": "^3.2.25",
    "framer-motion": "^5.6.0",
    "next": "latest",
    "next-auth": "^4.1.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-hook-form": "^7.24.1",
    "react-hot-toast": "^2.2.0",
    "react-icons": "^4.3.1",
    "superjson": "^1.8.0"
  },
```

My next-auth login works perfectly on github/google if i comment out the 
adapter: PrismaAdapter(prisma), from [...nextauth].js

**Comment by anirbanchowdhury** [comment]
Please create an issue at https://github.com/prisma/prisma/issues/new Error: 
Invalid `p.account.findUnique()` invocation in
/Users/aniamritapc/Desktop/with-tailwindcss-app/node_modules/@next-auth/prisma-adapter/dist/index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
  Query engine library for current platform "darwin" could not be found.
You incorrectly pinned it to darwin

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/Users/aniamritapc/Desktop/with-tailwindcss-app/node_modules/@prisma/client/runtime/libquery_engine-darwin.dylib.node")

Searched Locations:

  /Users/aniamritapc/Desktop/with-tailwindcss-app/node_modules/.prisma/client
  /Users/aniamritapc/Desktop/with-tailwindcss-app/node_modules/@prisma/client
  /Users/aniamritapc/Desktop/with-tailwindcss-app/node_modules/@prisma/client
  /Users/aniamritapc/Desktop/with-tailwindcss-app/node_modules/.prisma/client
  /Users/aniamritapc/Desktop/with-tailwindcss-app/prisma
  /tmp/prisma-engines
  /Users/aniamritapc/Desktop/with-tailwindcss-app/node_modules/.prisma/client

**Comment by anirbanchowdhury** [comment]
Rerunning 
npm install @prisma/client
npx prisma generate
seems to solve it

**Comment by janpio** [comment]
So problem solved for you and issue can be closed?

**Comment by anirbanchowdhury** [comment]
No, the issue came back intermittently and i had to redo the steps again. So, not really sure if there is a non deterministic bug lurking somewhere
Thanks & Warm Regards,Anirban Chowdhury 

    On Sunday, January 23, 2022, 12:34:37 AM GMT+5:30, Jan Piotrowski ***@***.***> wrote:  
 
 


So problem solved for you and issue can be closed?

—
Reply to this email directly, view it on GitHub  , or unsubscribe  .
Triage notifications on the go with GitHub Mobile for iOS   or Android  .

**Comment by anirbanchowdhury** [comment]
Issue comes back every time i kill the server. 
Before i run npm run dev, i have to run 
npm install @prisma/client
npx prisma generate

**Comment by matthewmueller** [comment]
Just a guess, but it seems like the error is: "You incorrectly pinned it to darwin". What's your Prisma Schema look like? Are you setting the binary platform yourself?

**Comment by janpio** [comment]
(This error message is notoriously a red herring and misleading.)

**Comment by terose73** [comment]
I have a related error tripping up on provider_providerAccountId using Planetscale (MySQL) / Prisma / NextAuth. Fields exist in the prisma schema and have the right defaults based on the v4 documentation.

```
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error
Invalid `p.account.findUnique()` invocation in
C:\Users\teros\Desktop\transcript-geek\node_modules\@next-auth\prisma-adapter\dist\index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
  Failed to validate the query: `Field does not exist on enclosing type.` at `Query.findUniqueAccount` Error:
Invalid `p.account.findUnique()` invocation in
C:\Users\teros\Desktop\transcript-geek\node_modules\@next-auth\prisma-adapter\dist\index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
  Failed to validate the query: `Field does not exist on enclosing type.` at `Query.findUniqueAccount`
    at cb (C:\Users\teros\Desktop\transcript-geek\node_modules\@prisma\client\runtime\index.js:38691:17)
    at async getUserByAccount (C:\Users\teros\Desktop\transcript-geek\node_modules\@next-auth\prisma-adapter\dist\index.js:11:29) {
  name: 'GetUserByAccountError',
  code: 'P2009'
}

```

**Comment by janpio** [comment]
@terose73 That looks like a completely different error, although you have the same setup. Please open a new issue and provide all the information we could need to understand your problem.

**Comment by terose73** [comment]
Opened a new issue, originally thought it might be related to the misleading error message

https://github.com/prisma/prisma/issues/11487
