### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine\connectors\mongodb-query-connector\src\root_queries\read.rs:112:74

### ISSUE THREAD

**Issue by mshayan-ags** [prisma/prisma#11378]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.13.1           | 
| OS              | windows            |
| Prisma Client   | 3.8.1              |
| Query Engine    | 0.1.0              |
| Database        | mongodb            |

## Logs
```
Environment variables loaded from C:\Users\Office-PC\Desktop\100 days of I&A\.env  
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Office-PC\Desktop\100 days of I&A\.env  
  prisma:client clientVersion: 3.8.1  
  prisma:client clientEngineType: library  
  prisma:client:libraryEngine internalSetup  
  prisma:client:libraryEngine sending request, this.libraryStarted: false  
  prisma:client:libraryEngine Searching for Query Engine Library in C:\Users\Office-PC\Desktop\100 days of I&A\node_modules\.prisma\client  
  prisma:client:libraryEngine loadEngine using C:\Users\Office-PC\Desktop\100 days of I&A\node_modules\.prisma\client\query_engine-windows.dll.node  
  prisma:client:libraryEngine library starting  
  prisma:client:libraryEngine library started  +2s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +5s
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
  prisma:client:libraryEngine requestBatch  
```

## Schema

```
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

model Admin {
  id             String       @id @default(dbgenerated()) @map("_id") @db.ObjectId
  firstName      String?
  lastName       String?
  email          String       @unique
  password       String
  DateOfBirth    String?
  ProfilePicture Attachment[]
  createdAt      DateTime     @default(now())
  updatedAt      DateTime     @updatedAt
}

model User {
  id                  String             @id @default(dbgenerated()) @map("_id") @db.ObjectId
  //  Basic Info
  userType            Type               @default(PRIVATE)
  firstName           String?
  lastName            String?
  email               String             @unique
  password            String
  DateOfBirth         String?
  SubscriptionPackage UserSubscription[]
  Bio                 String?
  // Point
  PointsAchieved      Int?
  Tier                Tier?              @relation(fields: [tierId], references: [id])
  tierId              String?            @db.ObjectId
  // Hashtags
  Goal                UserGoal[]
  Interest            Interest[]
  // Profile Pictue
  ProfilePicture      Attachment[]
  // Workout Time
  WorkoutTimeFrom     String?
  WorkoutTimeTo       String?
  //  Friends
  Following           Friends[]          @relation("Following")
  Followers           Friends[]          @relation("Followers")
  RequestSent         FriendRequest[]    @relation("RequestBy")
  RequestReceived     FriendRequest[]    @relation("RequestTo")
  // Blocked And Report
  BlockedBy           BlockUser[]        @relation("BlockedBy")
  BlockedUser         BlockUser[]        @relation("BlockedUser")
  ReportedBy          ReportUser[]       @relation("ReportedBy")
  ReportedUser        ReportUser[]       @relation("ReportedUser")
  // Chat
  Conversation        Conversation[]
  // Time Off Toggle
  RelaxationDaysLeft  Int?
  TimeOffToggle       TimeOffToggle[]
  // Post
  Post                Post[]
  Comment             Comment[]
  CommentReplies      CommentReplies[]
  Like                Like[]
  Share               Share[]
  // Tag
  TaggedPost          Post[]             @relation("TagPost")
  TagComment          Comment[]          @relation("TagComment")
  TagCommentReplies   CommentReplies[]   @relation("TagCommentReplies")
  // Create update Records
  createdAt           DateTime           @default(now())
  updatedAt           DateTime           @updatedAt
}

enum Type {
  PRIVATE
  PUBLIC
}

model UserSubscription {
  id             String       @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Package        Subscription @relation(fields: [subscriptionId], references: [id])
  subscriptionId String       @db.ObjectId
  BankName       String
  EndDate        String
  User           User         @relation(fields: [userId], references: [id])
  userId         String       @db.ObjectId
  createdAt      DateTime     @default(now())
  updatedAt      DateTime     @updatedAt
}

model Subscription {
  id                String             @id @default(dbgenerated()) @map("_id") @db.ObjectId
  PackageName       String             @unique
  PackageTimePeriod String             @unique
  UserSubscription  UserSubscription[]
  Charges           Int
  createdAt         DateTime           @default(now())
  updatedAt         DateTime           @updatedAt
}

model Tier {
  id             String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Level          String?
  PointsAchieved Int?
  PointRequired  Int?
  User           User[]
  createdAt      DateTime @default(now())
  updatedAt      DateTime @updatedAt
}

model Goal {
  id        String      @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Goal      String      @unique
  Image     Attachment?
  UsersGoal UserGoal[]
  // Create update Records
  createdAt DateTime    @default(now())
  updatedAt DateTime    @updatedAt
}

model UserGoal {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Goal      Goal?    @relation(fields: [goalId], references: [id])
  goalId    String?  @db.ObjectId
  User      User     @relation(fields: [userId], references: [id])
  userId    String   @db.ObjectId
  // Create update Records
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Interest {
  id         String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  MyInterest String
  User       User?    @relation(fields: [userId], references: [id])
  userId     String?  @db.ObjectId
  // Create update Records
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}

model Location {
  id             String           @id @default(dbgenerated()) @map("_id") @db.ObjectId
  latitude       Int              @unique
  longitude      Int              @unique
  Post           Post[]
  Comment        Comment[]
  CommentReplies CommentReplies[]
  // Create update Records
  createdAt      DateTime         @default(now())
  updatedAt      DateTime         @updatedAt

  @@unique([latitude, longitude])
}

model HashTag {
  id               String          @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Text             String          @unique
  Post             Post?           @relation(fields: [postId], references: [id])
  postId           String?         @db.ObjectId
  Comment          Comment?        @relation(fields: [commentId], references: [id])
  commentId        String?         @db.ObjectId
  CommentReplies   CommentReplies? @relation(fields: [commentRepliesId], references: [id])
  commentRepliesId String?         @db.ObjectId
  // Create update Records
  createdAt        DateTime        @default(now())
  updatedAt        DateTime        @updatedAt
}

model Friends {
  id         String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Following  User     @relation("Following", fields: [userId], references: [id])
  userId     String   @db.ObjectId
  Followers  User     @relation("Followers", fields: [friendId], references: [id])
  friendId   String   @db.ObjectId
  isAccepted Boolean  @default(true)
  // Create update Records
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}

model BlockUser {
  id            String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  BlockedBy     User     @relation("BlockedBy", fields: [userId], references: [id])
  userId        String   @db.ObjectId
  BlockedUser   User     @relation("BlockedUser", fields: [blockedUserId], references: [id])
  blockedUserId String   @db.ObjectId
  // Create update Records
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
}

model ReportUser {
  id             String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  ReportedBy     User     @relation("ReportedBy", fields: [userId], references: [id])
  userId         String   @db.ObjectId
  ReportedUser   User     @relation("ReportedUser", fields: [ReportedUserId], references: [id])
  ReportedUserId String   @db.ObjectId
  Reason         String
  // Create update Records
  createdAt      DateTime @default(now())
  updatedAt      DateTime @updatedAt
}

model FriendRequest {
  id         String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  RequestBy  User     @relation("RequestBy", fields: [userId], references: [id])
  userId     String   @db.ObjectId
  RequestTo  User     @relation("RequestTo", fields: [friendId], references: [id])
  friendId   String   @db.ObjectId
  isAccepted Boolean  @default(true)
  // Create update Records
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}

model TimeOffToggle {
  id          String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Reason      String?
  Description String?
  TimePeriod  String?
  User        User?    @relation(fields: [userId], references: [id])
  userId      String?  @db.ObjectId
  // Create update Records
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}

model Post {
  id             String           @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Caption        String?
  Image          PostImages[]
  Comments       Comment[]
  Like           Like[]
  Share          Share[]
  CommentReplies CommentReplies[]
  User           User             @relation(fields: [userId], references: [id])
  userId         String           @db.ObjectId
  day            Int?
  // Location
  Location       Location?        @relation(fields: [locationId], references: [id])
  locationId     String?          @db.ObjectId
  // Mentions And Hastags
  TaggedPeople   User[]           @relation("TagPost")
  HashTags       HashTag[]
  // Create update Records
  createdAt      DateTime         @default(now())
  updatedAt      DateTime         @updatedAt
}

model Comment {
  id             String           @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Text           String
  PostComments   Post             @relation(fields: [postcommentId], references: [id])
  postcommentId  String           @db.ObjectId
  User           User             @relation(fields: [userId], references: [id])
  userId         String           @db.ObjectId
  CommentReplies CommentReplies[]
  // Location
  Location       Location?        @relation(fields: [locationId], references: [id])
  locationId     String?          @db.ObjectId
  // Mentions And Hastags
  TaggedPeople   User[]           @relation("TagComment")
  HashTags       HashTag[]
  // Create update Records
  createdAt      DateTime         @default(now())
  updatedAt      DateTime         @updatedAt
}

model CommentReplies {
  id                 String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Text               String
  Comment            Comment   @relation(fields: [commentId], references: [id])
  commentId          String    @db.ObjectId
  PostCommentReplies Post      @relation(fields: [postCommentReplyId], references: [id])
  postCommentReplyId String    @db.ObjectId
  User               User      @relation(fields: [userId], references: [id])
  userId             String    @db.ObjectId
  // Location
  Location           Location? @relation(fields: [locationId], references: [id])
  locationId         String?   @db.ObjectId

  // Mentions And Hastags
  TaggedPeople User[]    @relation("TagCommentReplies")
  HashTags     HashTag[]
  // Create update Records
  createdAt    DateTime  @default(now())
  updatedAt    DateTime  @updatedAt
}

model Like {
  id         String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  LikeType   Emoji    @default(Like)
  PostLikes  Post?    @relation(fields: [postLikeId], references: [id])
  postLikeId String?  @db.ObjectId
  User       User     @relation(fields: [userId], references: [id])
  userId     String   @db.ObjectId
  // Create update Records
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}

enum Emoji {
  Like
  Heart
  Haha
  Sad
  Angry
}

model Share {
  id         String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  PostShares Post?    @relation(fields: [shareId], references: [id])
  shareId    String?  @db.ObjectId
  User       User     @relation(fields: [userId], references: [id])
  userId     String   @db.ObjectId
  // Create update Records
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}

model PostImages {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  filename  String   @unique
  mimetype  String?
  encoding  String?
  Post      Post?    @relation(fields: [postId], references: [id])
  postId    String?  @db.ObjectId
  // Create update Records
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Conversation {
  id        String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  User      User[]
  Messages  Message[]
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
}

model Message {
  id             String        @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Text           String?
  Attachment     Attachment[]
  isSeenBy       String[]
  Conversation   Conversation? @relation(fields: [conversationId], references: [id])
  conversationId String?       @db.ObjectId
  createdAt      DateTime      @default(now())
  updatedAt      DateTime      @updatedAt
}

model Attachment {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  filename  String
  mimetype  String?
  encoding  String?
  User      User?    @relation(fields: [userId], references: [id])
  userId    String?  @db.ObjectId
  Message   Message? @relation(fields: [messageId], references: [id])
  messageId String?  @db.ObjectId
  Goal      Goal?    @relation(fields: [goalId], references: [id])
  goalId    String?  @unique @db.ObjectId
  Admin     Admin?   @relation(fields: [adminId], references: [id])
  adminId   String?  @db.ObjectId
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by mshayan-ags** [comment]
**Schema**

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

model User {
  id                  String             @id @default(dbgenerated()) @map("_id") @db.ObjectId
  //  Basic Info
  userType            Type               @default(PRIVATE)
  firstName           String?
  lastName            String?
  email               String             @unique
  password            String
  DateOfBirth         String?
  Bio                 String?
  ProfilePicture      Attachment[]
  // Post
  Post                Post[]
  Comment             Comment[]
  CommentReplies      CommentReplies[]
  Like                Like[]
  Share               Share[]
  // Tag
  TaggedPost          Post[]             @relation("TagPost")
  TagComment          Comment[]          @relation("TagComment")
  TagCommentReplies   CommentReplies[]   @relation("TagCommentReplies")
  // Create update Records
  createdAt           DateTime           @default(now())
  updatedAt           DateTime           @updatedAt
}

enum Type {
  PRIVATE
  PUBLIC
}

model HashTag {
  id               String          @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Text             String          @unique
  Post             Post?           @relation(fields: [postId], references: [id])
  postId           String?         @db.ObjectId
  Comment          Comment?        @relation(fields: [commentId], references: [id])
  commentId        String?         @db.ObjectId
  CommentReplies   CommentReplies? @relation(fields: [commentRepliesId], references: [id])
  commentRepliesId String?         @db.ObjectId
  // Create update Records
  createdAt        DateTime        @default(now())
  updatedAt        DateTime        @updatedAt
}
model Post {
  id             String           @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Caption        String?
  Image          PostImages[]
  Comments       Comment[]
  Like           Like[]
  Share          Share[]
  CommentReplies CommentReplies[]
  User           User             @relation(fields: [userId], references: [id])
  userId         String           @db.ObjectId
  day            Int?
  // Location
  Location       Location?        @relation(fields: [locationId], references: [id])
  locationId     String?          @db.ObjectId
  // Mentions And Hastags
  TaggedPeople   User[]           @relation("TagPost")
  HashTags       HashTag[]
  // Create update Records
  createdAt      DateTime         @default(now())
  updatedAt      DateTime         @updatedAt
}

model Comment {
  id             String           @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Text           String
  PostComments   Post             @relation(fields: [postcommentId], references: [id])
  postcommentId  String           @db.ObjectId
  User           User             @relation(fields: [userId], references: [id])
  userId         String           @db.ObjectId
  CommentReplies CommentReplies[]
  // Location
  Location       Location?        @relation(fields: [locationId], references: [id])
  locationId     String?          @db.ObjectId
  // Mentions And Hastags
  TaggedPeople   User[]           @relation("TagComment")
  HashTags       HashTag[]
  // Create update Records
  createdAt      DateTime         @default(now())
  updatedAt      DateTime         @updatedAt
}

model CommentReplies {
  id                 String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  Text               String
  Comment            Comment   @relation(fields: [commentId], references: [id])
  commentId          String    @db.ObjectId
  PostCommentReplies Post      @relation(fields: [postCommentReplyId], references: [id])
  postCommentReplyId String    @db.ObjectId
  User               User      @relation(fields: [userId], references: [id])
  userId             String    @db.ObjectId
  // Location
  Location           Location? @relation(fields: [locationId], references: [id])
  locationId         String?   @db.ObjectId

  // Mentions And Hastags
  TaggedPeople User[]    @relation("TagCommentReplies")
  HashTags     HashTag[]
  // Create update Records
  createdAt    DateTime  @default(now())
  updatedAt    DateTime  @updatedAt
}

model Like {
  id         String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  LikeType   Emoji    @default(Like)
  PostLikes  Post?    @relation(fields: [postLikeId], references: [id])
  postLikeId String?  @db.ObjectId
  User       User     @relation(fields: [userId], references: [id])
  userId     String   @db.ObjectId
  // Create update Records
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}

enum Emoji {
  Like
  Heart
  Haha
  Sad
  Angry
}

model Share {
  id         String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  PostShares Post?    @relation(fields: [shareId], references: [id])
  shareId    String?  @db.ObjectId
  User       User     @relation(fields: [userId], references: [id])
  userId     String   @db.ObjectId
  // Create update Records
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}

model PostImages {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  filename  String   @unique
  mimetype  String?
  encoding  String?
  Post      Post?    @relation(fields: [postId], references: [id])
  postId    String?  @db.ObjectId
  // Create update Records
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Attachment {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  filename  String
  mimetype  String?
  encoding  String?
  User      User?    @relation(fields: [userId], references: [id])
  userId    String?  @db.ObjectId
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}




**Code**



async function createPost(parent, args, context, info) {
	try {
		const { userId } = context;
		if (!userId) {
			return {
				success: false,
				message: "You must be Logged in"
			};
		} else {
			const files = args.Image
				? await Promise.all(
						args.Image.map(async (file) => {
							const img = await saveImageArray(file);
							return img;
						})
				  )
				: null;
			const User = prisma.user.findUnique({
				where: {
					id: userId
				}
			});

			const Days = moment((await User).createdAt).fromNow();
			const PostDay = Days.split(" ");

			const HashTags = ExtractHashTags(args.Caption);

			await prisma.post.create({
				data: {
					day: Number(PostDay[0]),
					Caption: args.Caption,
					User: {
						connect: {
							id: userId
						}
					},
					...(HashTags.length > 0
						? {
								HashTags: {
									connectOrCreate: [
										...HashTags.map((hash) => {
											return {
												where: {
													Text: hash
												},
												create: {
													Text: hash
												}
											};
										})
									]
								}
						  }
						: false),
					...(args.PeopleTagged && args.PeopleTagged.length > 0
						? {
								TaggedPeople: {
									connect: [
										...args.PeopleTagged.map((id) => {
											return {
												id: id
											};
										})
									]
								}
						  }
						: false),
					...(args.Location
						? {
								Location: {
									connectOrCreate: {
										where: {
											latitude_longitude: {
												latitude: args.Location.latitude,
												longitude: args.Location.longitude
											}
										},
										create: {
											longitude: args.Location.longitude,
											latitude: args.Location.latitude
										}
									}
								}
						  }
						: false),
					...(args.Image
						? {
								Image: {
									create: [
										...files.map((file) => {
											return {
												encoding: file.encoding,
												mimetype: file.mimetype,
												filename: file.secure_url
											};
										})
									]
								}
						  }
						: false)
				}
			});

			return {
				success: true,
				message: "Post Created successfully..."
			};
		}
	} catch (e) {
		return {
			success: false,
			message: "Post  Did'nt Created ...",
			debugMessage: e
		};
	}
}


**Whenever I try Anything related to post even fetch so this error occurs and my server crashes**

**Comment by janpio** [comment]
@mshayan-ags Can you please share the full error message you are getting? Seems right now we only have the snippet in the issue title but nothing in the description that would give more context on what is going on.

Are you sure the data in `Post` matches the Prisma schema you currently have?
How did you create the schema, Introspection or did you write it by hand?

**Comment by mshayan-ags** [comment]
Error: PANIC: called `Option::unwrap()` on a `None` value in query-engine/connectors/mongodb-query-connector/src/root_queries/read.rs:112:74\n\nThis is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.\n\nhttps://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v14.19.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-1.1.x%7C%0A%7C+Prisma+Client+++%7C+3.8.1++++++++++++++%7C%0A%7C+Query+Engine++++%7C+0.1.0++++++++++++++%7C%0A%7C+Database++++++++%7C+mongodb++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aprisma%3AtryLoadEnv+Environment+variables+loaded+from+%2Fapp%2F.env%0Aprisma%3AtryLoadEnv+Environment+variables+loaded+from+%2Fapp%2F.env%0Aprisma%3Aclient+clientVersion%3A+3.8.1%0Aprisma%3Aclient+clientEngineType%3A+library%0Aprisma%3Aclient%3AlibraryEngine+internalSetup%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+false%0Aprisma%3Aclient%3AlibraryEngine+Searching+for+Query+Engine+Library+in+%2Fapp%2Fnode_modules%2F.prisma%2Fclient%0Aprisma%3Aclient%3AlibraryEngine+loadEngine+using+%2Fapp%2Fnode_modules%2F.prisma%2Fclient%2Flibquery_engine-debian-openssl-1.1.x.so.node%0Aprisma%3Aclient%3AlibraryEngine+library+starting%0Aprisma%3Aclient%3AlibraryEngine+library+started%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=PANIC%3A+called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value+in+query-engine%2Fconnectors%2Fmongodb-query-connector%2Fsrc%2Froot_queries%2Fread.rs%3A112%3A74&template=bug_report.md\n\nIf you want the Prisma team to look into it, please open the link above 🙏\nTo increase the chance of success, please post your schema and a snippet of\nhow you used Prisma Client in the issue. \n

**Comment by matthewmueller** [comment]
Hey @mshayan-ags 

I just tried pulling in your original schema, but unfortunately there's quite a few syntax errors:

```sh
$ npx prisma format
Prisma schema loaded from prisma/schema.prisma
Error: Schema parsing
error: Error validating: Implicit many-to-many relations are not supported on MongoDB. Please use the syntax defined in https://pris.ly/d/document-database-many-to-many
  -->  schema.prisma:246
   | 
245 |   // Mentions And Hastags
246 |   TaggedPeople   User[]           @relation("TagPost")
247 |   HashTags       HashTag[]
   | 
error: Error validating: Implicit many-to-many relations are not supported on MongoDB. Please use the syntax defined in https://pris.ly/d/document-database-many-to-many
  -->  schema.prisma:68
   | 
67 |   // Tag
68 |   TaggedPost          Post[]             @relation("TagPost")
69 |   TagComment          Comment[]          @relation("TagComment")
   | 
error: Error validating: Implicit many-to-many relations are not supported on MongoDB. Please use the syntax defined in https://pris.ly/d/document-database-many-to-many
  -->  schema.prisma:265
   | 
264 |   // Mentions And Hastags
265 |   TaggedPeople   User[]           @relation("TagComment")
266 |   HashTags       HashTag[]
   | 
error: Error validating: Implicit many-to-many relations are not supported on MongoDB. Please use the syntax defined in https://pris.ly/d/document-database-many-to-many
  -->  schema.prisma:69
   | 
68 |   TaggedPost          Post[]             @relation("TagPost")
69 |   TagComment          Comment[]          @relation("TagComment")
70 |   TagCommentReplies   CommentReplies[]   @relation("TagCommentReplies")
   | 
error: Error validating: Implicit many-to-many relations are not supported on MongoDB. Please use the syntax defined in https://pris.ly/d/document-database-many-to-many
  -->  schema.prisma:286
   | 
285 |   // Mentions And Hastags
286 |   TaggedPeople User[]    @relation("TagCommentReplies")
287 |   HashTags     HashTag[]
   | 
error: Error validating: Implicit many-to-many relations are not supported on MongoDB. Please use the syntax defined in https://pris.ly/d/document-database-many-to-many
  -->  schema.prisma:70
   | 
69 |   TagComment          Comment[]          @relation("TagComment")
70 |   TagCommentReplies   CommentReplies[]   @relation("TagCommentReplies")
71 |   // Create update Records
   | 
error: Error validating: Implicit many-to-many relations are not supported on MongoDB. Please use the syntax defined in https://pris.ly/d/document-database-many-to-many
  -->  schema.prisma:338
   | 
337 |   id        String    @id @default(auto()) @map("_id") @db.ObjectId
338 |   User      User[]
339 |   Messages  Message[]
   | 
error: Error validating: Implicit many-to-many relations are not supported on MongoDB. Please use the syntax defined in https://pris.ly/d/document-database-many-to-many
  -->  schema.prisma:57
   | 
56 |   // Chat
57 |   Conversation        Conversation[]
58 |   // Time Off Toggle
   | 

Validation Error Count: 8
```

Do you mind posting a valid Prisma Schema so I can try reproducing? You might also consider upgrading to Prisma 3.11.0 to see if that fixes it. Thanks!

```
Environment variables loaded from .env
prisma                  : 3.11.0-dev.30
@prisma/client          : 3.11.0-dev.30
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 4cac12afbeef2fa3eedf1cb87c79bc15e2648836 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 4cac12afbeef2fa3eedf1cb87c79bc15e2648836
Studio                  : 0.458.0
Preview Features        : mongoDb
```
