### ISSUE TITLE
Studio version does not match that stated in Prisma Studio Releases

### ISSUE THREAD

**Issue by IrisMurray** [prisma/prisma#11397]
### Bug description

The version of studio stated to be included with Prisma 3.8.0 is 0.454.0.
Prisma 3.8.0 and 3.8.1 released with studio version 0.452.0 https://github.com/prisma/prisma/blob/d261cd7360542001bc714b0f1c5af6fe331a09e6/packages/cli/package.json#L75.

This means that Release 3.8.0 did not fix #802 "BigInt breaks studio".

On running studio and selecting a relation with a bigint identifier we get error `TypeError: BigInt value can't be serialized in JSON`

### How to reproduce

1. Install prisma 3.8.1.
2. Create a schema with two models with an implicit many-many between them
3. migrate database
4. run prisma studio
5. try to access the related model from the other

### Expected behavior

Expect to be able to use many-many in prisma studio with bigint ids

### Prisma information

```
model AppClient {
  id        BigInt   @id @default(autoincrement())
  clientId  String   @map("client_id") @unique
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @default(now()) @updatedAt @map("updated_at")
  scopes    Scope[]  @relation(name: "app_client_scope")

  @@map("app_client")
}

model Scope {
  id         BigInt      @id @default(autoincrement())
  scope      String      @unique
  createdAt  DateTime    @default(now()) @map("created_at")
  updatedAt  DateTime    @default(now()) @updatedAt @map("updated_at")
  appClients AppClient[] @relation(name: "app_client_scope")

  @@map("scope")
}
```

### Environment & setup

- OS: Ubuntu 20.04
- Database: PostgreSQL
- Node.js version: 16.13.12

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.8.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0

```

**Comment by IrisMurray** [comment]
This seems to be a deeper issue, that is related to the Many side of relations using BigInt ids. 

I tested another small schema with an update studio version and experienced similar issues.
```
model Animal {
  id           BigInt             @id @default(autoincrement())
  identifiers  AnimalIdentifier[]
  createdAt    DateTime           @default(now()) @map("created_at")
  updatedAt    DateTime           @default(now()) @updatedAt @map("updated_at")

  @@map("animal")
}

model AnimalIdentifier {
  id         BigInt   @id @default(autoincrement())
  scheme     String
  identifier String
  animalId   BigInt   @map("animal_id")
  animal     Animal   @relation(fields: [animalId], references: [id], onDelete: Cascade, onUpdate: NoAction)
  createdAt  DateTime @default(now()) @map("created_at")
  updatedAt  DateTime @default(now()) @updatedAt @map("updated_at")

  @@unique([scheme, identifier], map: "ix_animal_identifier_scheme_identifier")
  @@map("animal_identifier")
}

From the identifier side I can see the related animals, by clicking the animal link, if I then click `open in new tab` I get a popup error saying 

```
Prisma Client Error
Unable to run script
Message: BigInt value can't be serialized in JSON
  
Query:
[object Object]
```
If i then click on AnimalIdentifiers I get a fatal error.

Will report and reference this issue in a issue on prisma/studio

**Comment by janpio** [comment]
> The version of studio stated to be included with Prisma 3.8.0 is 0.454.0.

Where was this stated? Do we document this somewhere?

**Comment by IrisMurray** [comment]
The release statement is on the prisma studio releases page. https://github.com/prisma/studio/releases. Not directly in the prisma repository.

**Comment by janpio** [comment]
Those are the independent releases of Prisma Studio - and there the latest is 0.456.0. 
You can download the Electron version of Studio via the "Assets" list there. In Prisma CLI we usually include the latest of the time of the Prisma CLI and Client release - which in this case was 0.452.0. Or am I missing something here?

**Comment by IrisMurray** [comment]
Ok, that is slightly confusing because of the line 

> This version ships with Prisma v3.8.0

Is that the included prisma version with the electron build of studio?

**Comment by janpio** [comment]
Can you help me see this line? I do not see it on the page you linked to.

**Comment by janpio** [comment]
Ahhh, now I see it. It was hidden for me under all the internal drafts that exist. 
Seems someone made a mistake there and published the wrong draft.
I will double check.

**Comment by janpio** [comment]
We stopped publishing releases on `prisma/studio` as we ended support for the Electron builds of Prisma Studio: https://github.com/prisma/studio/issues/845
