### ISSUE TITLE
Support MongoDB "query" logging

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#11419]
## Problem

Right now we don't have a way to log the underlying querying run against a MongoDB database. This will be important because the Prisma way of querying is higher-level than the database query and often it's not clear how you'd map a Prisma query to the underlying query.

## Suggested Solution

We already support with other databases via

```ts
const prisma = new PrismaClient({
  log: ['query'],
})
```

We should investigate supporting this for MongoDB too. One possible suggestion would be to see how other ORMs like Mongoose do logging.

**Comment by matthewmueller** [comment]
Talked with @janpio a bit about it and there might be a simpler way that's more similar to what we currently do with logging SQL queries.

Before each of the mongodb driver calls, we serialize into a JSON log. Something like:

```js
logger.query(JSON.stringify({
  findOne: "Pets",
  document: document
})

// Actual driver call
driver.db("Pets").findOne(document)
```

This isn't going to be a standard MongoDB log, but they don't really have a standard. I think we could use the same format we have for $runCommandRaw.

**Comment by matthewmueller** [comment]
- [ ] Decide on the MongoDB format

**Comment by cprieto** [comment]
We will be using something that would be useful for the mongo shell. Other libraries (like Mongoose) use a similar approach.
