### ISSUE TITLE
Classes cannot be used as InputJsonValue

### ISSUE THREAD

**Issue by kwtech-dev** [prisma/prisma#11410]
### Bug description

We use NestJS, so we have DTOs defined as classes and used in request bodies.

When we put a class value to a json field, the follow typescript error occurs

```
Type 'MyDto' is not assignable to type 'InputJsonValue'.
  Type 'MyDto' is not assignable to type 'InputJsonObject'.
    Index signature for type 'string' is missing in type 'MyDto'.ts(2322)
```

### How to reproduce

Schema:

```prisma
model Model {
  id @id
  field Json
}
```

Code:
```ts
class MyDto {
  something: string
}
const dto = new MyDto();
prisma.model.create({
  data: {
    id: "id",
    field: dto // <-- error here
/*
Type 'MyDto' is not assignable to type 'InputJsonValue'.
  Type 'MyDto' is not assignable to type 'InputJsonObject'.
    Index signature for type 'string' is missing in type 'MyDto'.ts(2322)
*/
  }
})
```

### Expected behavior

Any objects can be put inside JSON field

### Prisma information

See above

### Environment & setup

- OS: MacOS 12.1
- Database: MySQL 8.0
- Node.js version: v16.13.0

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.8.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
```

**Comment by matthewmueller** [comment]
Hmm, I'm not so sure this should be allowed because not all classes can be serialized (e.g. classes with methods). 

I did just test it in JS and you can stringify classes:

```js
class A {}
JSON.stringify(new A()) // {}
```

Any reason you believe classes should be allowed?

**Comment by kwtech-dev** [comment]
After some research, I think `instanceToPlain` from `class-transformer` should be the way to go. It transform a class to a plain JS object (should be similar to serializing then deserializing it)
```ts
export declare function instanceToPlain<T>(object: T, options?: ClassTransformOptions): Record<string, any>;
```

I believed classes should be allowed as inputs simply because when we use DTO classes we are defining the object shape, and it is similar to an interface. 

You're right that methods cannot be serialized therefore should not be used as an object. 

I will close this issue as this is not a bug. Perhaps there will be some improvements to help people using DTOs in prisma but I'm currently fine with the `instanceToPlain` approach.

Thanks for your time!
