### ISSUE TITLE
Getting "Cannot find a fulltext index to use for the search, try adding a @@fulltext([Fields...]) to your schema" even though I've added fulltext indexes

### ISSUE THREAD

**Issue by BradyEdgar94** [prisma/prisma#11427]
### Bug description

I am trying to use the search feature for my MYSQL integration but am running into some issues. I've added `fullTextSearch` and `fullTextIndex` to my client like so:
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch", "fullTextIndex"]
}
```

Then I added my indexes to my User model like so:
```
model User {
  id                   String               @id @default(uuid())
  firstName            String?              @db.VarChar(255)
  lastName             String?              @db.VarChar(255)
 
  @@fulltext([firstName])
  @@fulltext([firstName, lastName])
  @@map(name: "users")
}
```

Then I try to execute the search on my users like so:
```
const members = await prisma.user.findMany({
      where: {
        firstName: { search: `+${search}` },
      },
});
```

Whenever I run my user's `findMany` query with the search key I get this error:
```
Error searching workspace PrismaClientKnownRequestError: 
Invalid `prisma.user.findMany()` invocation in
/Users/bradyedgar/_personal_development/mahi-api/src/controllers/workspaces/queries.ts:282:39

  279   },
  280 });
  281 
→ 282 const members = await prisma.user.findMany(
  Cannot find a fulltext index to use for the search, try adding a @@fulltext([Fields...]) to your schema
    at cb (/Users/bradyedgar/_personal_development/mahi-api/node_modules/@prisma/client/runtime/index.js:38691:17)
    at globalSearch (/Users/bradyedgar/_personal_development/mahi-api/src/controllers/workspaces/queries.ts:282:21)
    at WorkspaceResolver.globalSearch (/Users/bradyedgar/_personal_development/mahi-api/src/graphql/Workspace.ts:92:12)
    at dispatchHandler (/Users/bradyedgar/_personal_development/mahi-api/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)
    at /Users/bradyedgar/_personal_development/mahi-api/node_modules/type-graphql/dist/resolvers/helpers.js:83:26
    at dispatchHandler (/Users/bradyedgar/_personal_development/mahi-api/node_modules/type-graphql/dist/resolvers/helpers.js:82:24) {
  code: 'P2030',
  clientVersion: '3.8.1',
  meta: {}
}

```

I've updated my prisma package to ^3.8.0 and I get no errors in my editor or when I run a migrate or generate. So it seems like I've done all the steps in the documentation and I get no runtime errors but then when I execute the query, I always get the error above.

I'm a bit lost at this point.

### How to reproduce

- Use prisma with node version v14.18.1 and MYSQL
- Add `previewFeatures = ["fullTextSearch", "fullTextIndex"]` to the generator
- Add @@fulltext index to model
- Run a findMany query with the search key

### Expected behavior

I expected an array of the users who pass the validation, a simple search by name

### Environment & setup

- OS: Mac OS,
- Database: MySQL
- Node.js version: v14.18.1

Related packages
"@prisma/client": "^3.8.0",
"prisma": "^3.8.0",
"typegraphql-prisma": "^0.18.4",

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.8.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
Preview Features        : fullTextSearch, fullTextIndex

```

**Comment by janpio** [comment]
Did you migrate your database after making changes to your schema file?

**Comment by BradyEdgar94** [comment]
@janpio I did yes, I ran a database dev migration and then also re ran the generate command

**Comment by janpio** [comment]
Can you provide an export of the SQL schema of the database table this concerns? Thanks.

**Comment by BradyEdgar94** [comment]
@janpio Sure thing, here is the users table I am trying to search on
[users.csv](https://github.com/prisma/prisma/files/7953213/users.csv)

**Comment by janpio** [comment]
Sorry, we need basically this for that table: https://dev.mysql.com/doc/refman/8.0/en/show-create-table.html

**Comment by janpio** [comment]
Ping @BradyEdgar94

**Comment by floelhoeffel** [comment]
Hello everyone 👋

We are starting design work to improve Prisma's support for **Full Text Search (FTS)**!

If you would like to help, please help us learn about your needs via a short [FTS user research survey](https://prisma103696.typeform.com/fts-survey).

Thank you!

**Comment by Weakky** [comment]
Hey @BradyEdgar94,

As we haven't been able to reproduce this issue, we're now closing it. If you're still having this issue and you have updates that could help us, feel free to post them here and even re-open the issue.

Thank you 🙏
