### ISSUE TITLE
Is there any LSP implementation available for Prisma ? (Intellij)

### ISSUE THREAD

**Issue by SirMishaa** [prisma/prisma#11477]
Hi, I'm looking into writing a Kotlin plugin to support Prisma on Jetbrains IDEs via the [Language Server Protocol (LSP)](https://microsoft.github.io/language-server-protocol/)

Currently, the plugins that support Prisma are quite limited and have only a small amount of updates, which is a real sad and makes it difficult to improve them.

If Prisa offers an LSP implementation, I might consider making a plugin and maintaining it.

Regards.

**Comment by janpio** [comment]
Yep: https://github.com/prisma/language-tools/
