### ISSUE TITLE
MySQL does not support `onDelete: setDefault`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11498]
When trying to migrate a super simple schema to MySQL with an `onDelete: setDefault`, this happens:

```
C:\Users\Jan\Documents\throwaway\setdefault>npx prisma db push     
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "purple_kingfisher" at "mysql-db-provision.cm0mkpwj8arx.eu-central-1.rds.amazonaws.com:3306"
Error: Cannot add foreign key constraint
   0: sql_migration_connector::sql_database_step_applier::apply_migration
             at migration-engine\connectors\sql-migration-connector\src\sql_database_step_applier.rs:11
   1: migration_core::api::SchemaPush
             at migration-engine\core\src\api.rs:187
```

```prisma
model OnDeleteSetDefaultParent {
  id                Int                                @id @default(autoincrement())
  name              String                             @unique
  mandatoryChildren OnDeleteSetDefaultMandatoryChild[]
}

model OnDeleteSetDefaultMandatoryChild {
  id       Int                      @id @default(autoincrement())
  name     String                   @unique
  parent   OnDeleteSetDefaultParent @relation(fields: [parentId], references: [id], onDelete: SetDefault)
  parentId Int                      @default(1)
}
```

[Per our documentation](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions#types-of-referential-actions) this should fundamentally work (if maybe a bit different than expected):
[![image](https://user-images.githubusercontent.com/183673/151682947-a7a71e5d-6702-4df3-88d0-3ff1762286cd.png)](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions#types-of-referential-actions)

But looking at the MySQL docs, this does not seem to be supported at all:
> SET DEFAULT: This action is recognized by the MySQL parser, but both InnoDB and NDB reject table definitions containing ON DELETE SET DEFAULT or ON UPDATE SET DEFAULT clauses.
- https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html#:~:text=SET%20DEFAULT%3A%20This%20action%20is%20recognized%20by%20the%20MySQL%20parser%2C%20but%20both%20InnoDB%20and%20NDB%20reject%20table%20definitions%20containing%20ON%20DELETE%20SET%20DEFAULT%20or%20ON%20UPDATE%20SET%20DEFAULT%20clauses.
- https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html#:~:text=SET%20DEFAULT%3A%20This%20action%20is%20recognized%20by%20the%20MySQL%20parser%2C%20but%20both%20InnoDB%20and%20NDB%20reject%20table%20definitions%20containing%20ON%20DELETE%20SET%20DEFAULT%20or%20ON%20UPDATE%20SET%20DEFAULT%20clauses.
- 
Similar for MariaDB:
> The SET DEFAULT action is not supported.
- https://mariadb.com/kb/en/foreign-keys/#:~:text=The%20SET%20DEFAULT%20action%20is%20not%20supported.

We even mention similar in our engines comments:
https://github.com/prisma/prisma-engines/blob/ccf3dc944acdabb431947150e12b984b34c538cd/query-engine/connector-test-kit-rs/query-engine-tests/tests/new/ref_actions/on_delete/set_default.rs#L1
https://github.com/prisma/prisma-engines/blob/ccf3dc944acdabb431947150e12b984b34c538cd/migration-engine/migration-engine-tests/tests/migrations/relations.rs#L565-L566

We should adapt our validation to not allow this, and update our documentation afterwards as well. No need for our users to waste their time with this.

**Comment by janpio** [comment]
Seems to already be a validation with preview feature `referentialIntegrity` and configuration `referentialIntegrity = "foreignKeys"`.

**Comment by pimeys** [comment]
What exact MySQL version you are running?

**Comment by janpio** [comment]
My output was from a `5.7.33-log`, bit docs sound identical to 8.x.

**Comment by pimeys** [comment]
Yeah, whatever MySQL version we were using in the _time of the writing of our docs_ silently just did not use the given action. This might've changed in a point release, as we know MySQL does this between `x.x.x` releases. Also, `SetDefault` should work with MyISAM and other MySQL engines, just not with InnoDB.

**Comment by janpio** [comment]
Prisma supports only InnoDB, so essentially does not support `SET DEFAULT` (which is fine, we should just validate it properly and document it as well).

**Comment by pimeys** [comment]
If we say we only support InnoDB, I'm OK validating against using `SetDefault` on MySQL.

**Comment by janpio** [comment]
I think it's the current reality when you create a schema via Migrate. As we do not have the table engine information in the schema (yet, there might be an issue floating around) I think this is the easiest option right now.

**Comment by Jolg42** [comment]
TODO check if it works with MySQL 8 like mentioned in https://github.com/prisma/prisma-engines/pull/2957

**Comment by jkomyno** [comment]
Considering that we only support `InnoDB`, I confirm that `SET DEFAULT` only works from `mysql:8`, as shown [here](https://github.com/prisma/prisma/issues/14673#issuecomment-1269790213).

**Comment by janpio** [comment]
The linked issue is a different topic, please pull in the relevant information that describes the support of `SET DEFAULT` on MySQL in here.

**Comment by jkomyno** [comment]
I confirm that `ON DELETE: SET DEFAULT` is supported in `CREATE TABLE` statements for the following database versions:
- `mysql:8` and beyond
- `mariadb:10.9` and beyond (possibly earlier versions as well, but definitely not `mariadb:10.0`)

**Comment by Jolg42** [comment]
Decision: Document that `setDefault` does not work on older MySQL and MariaDB

**Comment by Jolg42** [comment]
Closing in favor of docs issue https://github.com/prisma/docs/issues/3885

**Comment by jkomyno** [comment]
I have just found out that `MySQL 8.0` docs report the following:

> `SET DEFAULT`: This action is recognized by the MySQL parser, but both [InnoDB](https://dev.mysql.com/doc/refman/8.0/en/innodb-storage-engine.html) and [NDB](https://dev.mysql.com/doc/refman/8.0/en/mysql-cluster.html) reject table definitions containing `ON DELETE SET DEFAULT` or `ON UPDATE SET DEFAULT` clauses.

**Comment by jkomyno** [comment]
I have summarised my findings in [this notion doc](https://www.notion.so/prismaio/SetDefault-referential-action-on-MySQL-68d7bdbe6fc947cf8829d7ca7dc2b001).

**Comment by jkomyno** [comment]
Starting from `prisma@4.6.0`, we have decided to remove support for the `SetDefault` referential action for the `mysql` provider, after realizing the MySQL never truly supported such action. This means that the following schema is no longer valid:

```prisma
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

model User {
  id    Int    @id @default(autoincrement())
  posts Post[]
}

model Post {
  id     Int   @id @default(autoincrement())
  user   User? @relation(fields: [userId], references: [id], onUpdate: SetDefault, onDelete: SetDefault)
  userId Int?  @default(3)
}
```

The MySQL [docs](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html#foreign-key-referential-actions) claim that table definitions with `SET DEFAULT` referential actions are rejected from InnoDB, which is the default storage engine and the only one supported by Prisma. In reality, `mysql:8` users can successfully create/alter tables with `SET DEFAULT` referential actions, but those referential actions would fail at runtime when triggered. They’d fail with a foreign key constraint error, as they're confusingly interpreted as `NO ACTION` referential actions. On the other hand, `mysql:5.6+` users can’t even create/alter tables containing `SET DEFAULT` referential actions, as they’d get a syntax error.

**Comment by jkomyno** [comment]
Closing this issue in favor of https://github.com/prisma/prisma/issues/16259, which will implement warnings in this issue's scenarios, as to avoid breaking changes.
