### ISSUE TITLE
Expose the type that is passed to the interactive $transaction function

### ISSUE THREAD

**Issue by albertorestifo** [prisma/prisma#11511]
## Problem

When using interactive transactions, the type passed to the `$transaction` function is different that the Prisma type:

```ts
prismaClient.$transaction(async (prisma) => {
  // The type of `prisma` here is what this issue refers to
})
```

## Suggested solution

Using the VSCode hover type, I was able to extract this as the type:

```ts
Omit<
   PrismaClient<Prisma.PrismaClientOptions, never, Prisma.RejectOnNotFound | Prisma.RejectPerOperation | undefined>,
   '$connect' | '$disconnect' | '$on' | '$transaction' | '$use'
 >;
```

I think this type should be exposed by the `@prisma/client` package.

**Comment by DamianGlowala** [comment]
Hi @janpio,

Is there a chance this issue could be added to the 3.11.0 milestone? Lack of typing for `$transaction()` doesn't provide a sleek DX for TypeScript users 🙌
