### ISSUE TITLE
Using `--url` for `db pull` ignored/overwrites `provider=cockroachdb`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11527]
With this schema:
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["cockroachdb"]
}

datasource db {
  provider = "cockroachdb"
  url      = "postgresql://jo_l:11...oud:26257/introspection-ci-5134.aragon-notification-service?sslmode=verify-full"
}
```

this is the output of `prisma db pull --url=postgresql://jo....cloud:26257/introspection-ci-5134.aragon-notification-service?sslmode=verify-full`:
```
λ npx prisma db pull --url=postgresql://jo_l:1...oud:26257/introspection-ci-5134.aragon-notification-service?sslmode=verify-full
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": CockroachDB database "introspection-ci-5134.aragon-notification-service", schema "public" at "free-tier...ud:26257"

Introspecting …

✔ Introspected 6 models and wrote them into prisma\schema.prisma in 6.80s

Run prisma generate to generate Prisma Client.
```
(which is great!)

but this the resulting schema:

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["cockroachdb"]
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://jo_l:11ekBxMQuUr07kHv@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/introspection-ci-5134.aragon-notification-service?sslmode=verify-full"
}

model eventsources {
  eventsource_id   BigInt          @id
  created_at       DateTime?       @default(now()) @db.Timestamptz(6)
  enabled          Boolean         @default(true)
  contract_address String          @db.VarChar(255)
```

Note how it says `provider = "postgresql"`  there.

I think it would be ok to keep ´provider=cockroachdb` around when already set in the original schema.

(Everything works fine when you just run `db pull` without `--url`)

Related: https://github.com/prisma/prisma/issues/11347

**Comment by tomhoule** [comment]
In the current implementation, it seems like we are converting the url passed to `--url` into a datasource, without taking into account the prisma schema (https://github.com/prisma/prisma/blob/34f122958be88d04c12377213c371838c104da5d/packages/migrate/src/commands/DbPull.ts#L160) — alternatively, the CLI could send both to the introspection engine, which would figure out the right provider naturally from parsing the prisma schema. If we do that in the typescript code, we will have to introduce more logic and more special cases, so I think ideally, we should handle this in the introspection engine.

**Comment by jkomyno** [comment]
> In the current implementation, it seems like we are converting the url passed to `--url` into a datasource, without taking into account the prisma schema (
> 
> https://github.com/prisma/prisma/blob/34f122958be88d04c12377213c371838c104da5d/packages/migrate/src/commands/DbPull.ts#L160
> 
> ) — alternatively, the CLI could send both to the introspection engine, which would figure out the right provider naturally from parsing the prisma schema. If we do that in the typescript code, we will have to introduce more logic and more special cases, so I think ideally, we should handle this in the introspection engine.

Exactly, I have realized the root cause yesterday afternoon, I will publish my local changes (which solve this issue) soon this morning :)
