### ISSUE TITLE
binaryTargets not generating all targets

### ISSUE THREAD

**Issue by tobewisebeforeiamold** [prisma/prisma#11522]
### Bug description

Using prisma 3.7.0 on Windows and Mac, `prisma generate` does not generate the Linux binaries.

### How to reproduce

1. the top of `prisma/schema.prisma` looks like this:
    ```
    generator client {
      provider      = "prisma-client-js"
      binaryTargets = ["native", "rhel-openssl-1.0.x"]
    }

    datasource db {
      provider = "mysql"
      url      = env("DATABASE_URL")
    }
    ```
2. Using Prisma v3.7.0, npm v6.13.4, node v12.16.1
3. run `npx prisma generate` and then look in `node_modules/@prisma/engines` and see only exe/dll.node in the case of Windows, or darwin in the case of OSX

### Expected behavior

Ideally, both native binaries AND linux binaries would exist

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: Windows 11 & OSX Monterey
- Database: MySQL
- Node.js version: 12.16.1

### Prisma Version

```
risma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
```

**Comment by janpio** [comment]
`node_modules/@prisma/engines` is a different package, you want to look into `node_modules/.prisma/client` which is where Prisma Client (which you configure via `binaryTargets = ["native", "rhel-openssl-1.0.x"]`) stores the engines available for its use.

If you need to configure the engines of Prisma CLI, you need to use this env var: https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#cli-binary-targets

**Comment by tobewisebeforeiamold** [comment]
Ah, interesting: the same place as the client generated types - that makes sense!
