### ISSUE TITLE
Using binary targets on Windows throws Unexpected end of JSON input

### ISSUE THREAD

**Issue by killjoy2013** [prisma/prisma#11520]
### Bug description

using prisma on Windows 10. I need to generate prisma in an offline mode. No internet access in pipeline. My `package.json` as below;

```js

{
  "name": "hello-prisma",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "@types/node": "^17.0.13",
    "prisma": "^3.8.1",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.5"
  }
}
```

and schema.prisma as follows;
```js
generator client {
  provider = "prisma-client-js"
  engineType="binary"
  binaryTargets=["native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

.env file as follows;

```js
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/countrydb?schema=auth
PRISMA_CLI_QUERY_ENGINE_TYPE=binary
PRISMA_QUERY_ENGINE_BINARY=node_modules/@prisma/engines/query_engine-windows.dll
PRISMA_MIGRATION_ENGINE_BINARY=node_modules/@prisma/engines/migration-engine-windows.exe
PRISMA_INTROSPECTION_ENGINE_BINARY=node_modules/@prisma/engines/introspection-engine-windows.exe
PRISMA_FMT_BINARY=node_modules/@prisma/engines/prisma-fmt-windows.exe
DEBUG="*"
```

when I run `npx prisma generate` below JSON input error happens;

```
$ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: Get config: SyntaxError: Unexpected end of JSON input
```

### How to reproduce

Just run `npx prisma generate`.  Above error happens.

### Expected behavior

Prisma Client is supposed to be generated and become ready to run `migration deploy` using only binaries without accessing any CDN.

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v14.17.2

### Prisma Version

```
prisma                : 3.8.1
@prisma/client        : 3.8.1
Current platform      : windows
```

**Comment by janpio** [comment]
Does removing `binaryTargets=["native"]` from the schema file make it succeed?

**Comment by killjoy2013** [comment]
> Does removing `binaryTargets=["native"]` from the schema file make it succeed?

@janpio thanks for the quick reply! Unfortunately it didn't make any difference...

**Comment by janpio** [comment]
Then I don't think this is related to binary targets. Can you figure out what is different in your project vs. a default one with no customizations?

**Comment by killjoy2013** [comment]
> Then I don't think this is related to binary targets. Can you figure out what is different in your project vs. a default one with no customizations?

Here's what I did;

- I restored prisma client generator back to original;
```js
generator client {
  provider = "prisma-client-js"
}
```

- removed all binary env variables from .env
- removed node_modules
- cleaned npm cache
- run npm install
- I observed that `.prisma/client` directory has been created with `query_engine-windows.dll.node` and `schema.prisma` like below 

![image](https://user-images.githubusercontent.com/6085821/151869735-136636d8-bc82-4e8f-bd97-6177af934324.png)

I guess, since my project already run prisma generate and contains `schema.prisma` before I deleted node_modules, when I run npm install, it could created .prisma/client correctly. 

- I turned wifi of my computer off and run `npx prisma generate` It runs OK without trying to call any CDN. 
- Eventually, I could run `npx prisma generate` & `npx migrate deploy` in `docker-entrypoint.sh` file.

- Thank you @janpio & best regards 👍
