### ISSUE TITLE
Preview feature feedback: `cockroachdb`

### ISSUE THREAD

**Issue by 2color** [prisma/prisma#11542]
Please share your feedback about the `cockroachdb` preview feature released in [v3.9.0](https://github.com/prisma/prisma/releases/tag/3.9.0) in this issue.

- If you encounter a bug, please open a bug report in this repo.
- If the feature is working well for you, please share this in a comment below or leave a :+1: on this issue.

If you have any questions, don't hesitate to ask them in the [#product-feedback](https://app.slack.com/client/T0MQBS8JG/C01739JGFCM/thread/C01739JGFCM-1631633975.005200) channel in the [Prisma Slack](https://slack.prisma.io/).

**Comment by Jolg42** [comment]
Note: Prisma Migrate now supports CockroachDB since `3.11.0`

**Comment by SebJansen** [comment]
When trying to create a project and entering a CockroachCloud serverless connection string, I get the following error: ```We were unable to create your project: Requested database check `reachable` failed```

Is there a solution for this? I have tested the connection string locally with both `psql` as well as `cockroach sql` , both working fine, indicating the problem may lie on Prisma's side

For reference, this is the connection string that I'm using: `postgresql://USER:PASSWORD@HOST:PORT/defaultdb?sslmode=require&options=CLUSTER_NAME`

Is there a way to get past this error?

**Comment by janpio** [comment]
That is super weird @SebJansen. Can you share the full error message including the context you get it? Optimally open a new issue so we can treat this as an independent bug and can ask you all the questions. Thanks.

**Comment by SebJansen** [comment]
Thank you, @janpio 

I have create an issue: https://github.com/prisma/prisma/issues/12451
