### ISSUE TITLE
migrate diff: --{from,to}-schema-datamodel should not error on missing env vars in datasource blocks 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#11544]
Command:

```
prisma migrate diff --preview-feature --from-empty --to-schema-datamodel ~/tmp/windows-stack-overflow/prisma/schema.prisma
```

Error:

```
Warning Precompiled binaries are not available for nixos.
Error: P1012

error: Environment variable not found: POSTGRES_URL.
  -->  schema.prisma:7
   | 
 6 |   provider  = "postgresql"
 7 |   url       = env("POSTGRES_URL")
   | 
```

**Comment by do4gr** [comment]
Ran into that one as well. I'd say that is pretty high priority.

**Comment by Jolg42** [comment]
The current workaround for this is to define the env var (it will not be used but needs to be valid) like:

`DATABASE_URL="connection url" npx prisma migrate diff [...]`

**Comment by Jolg42** [comment]
Reopening, I'll close once it's integrated

**Comment by Jolg42** [comment]
Out in `3.11.0-dev.13` and up, tests shows it works and @do4gr will check if that works manually too
