### ISSUE TITLE
Make migrations flat

### ISSUE THREAD

**Issue by rouzbehsbz** [prisma/prisma#11548]
Hi,
After a while, the number of magrites becomes very large and takes up space. Isn't it better to add a new feature that can make magrites that have no problems and have been checked,  flat (in one file) ?

**Comment by eduhenke** [comment]
Related to https://github.com/prisma/prisma/issues/5714 and https://github.com/prisma/prisma/issues/5226

**Comment by pantharshit00** [comment]
As pointed by @eduhenke, I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/5714.
