### ISSUE TITLE
Drift detected on first migration

### ISSUE THREAD

**Issue by luminous8** [prisma/prisma#11555]
### Bug description

Hi,

I'm getting issues when trying to setup prisma on an existing database (I've already setup prisma on a new db without any issues)

At first I thought it was from my existing db but I've tried on a simple one:
```
CREATE TABLE `collections` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` date NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `collections_slug_key` (`slug`),
  KEY `collection_slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


INSERT INTO `collections` (`id`, `title`, `created_at`, `slug`)
VALUES
	(1, 'test', '2022-02-01', 'test');
```

### How to reproduce

1. Install the db (above)
2. Run npx prisma db pull 
3. Run npx prisma generate
4. Run first migration npx prisma migrate dev  
4. Got this message saying that I have to reset my db
```
Drift detected: Your database schema is not in sync with your migration history.

The following is a summary of the differences between the expected database schema given your migrations files, and the actual schema of the database.

It should be understood as the set of changes to get from the expected schema to the actual schema.

If you are running this the first time on an existing database, please make sure to read this documentation page:
https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/troubleshooting-development

[+] Added tables
  - collections

? We need to reset the MySQL database "test" at "127.0.0.1:3306"
```

Which is exactly the same db as the one I've pulled data from.

### Expected behavior

Migrate without having to reset data

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model collections {
  id         Int      @id @default(autoincrement())
  title      String   @db.VarChar(255)
  created_at DateTime @db.Date
  slug       String   @unique @db.VarChar(255)

  @@index([slug], map: "collection_slug")
}
```

### Environment & setup

- OS: Mac Os
- Database: Mysql 8.0.22
- Node.js version: v16.13.0

### Prisma Version

```
prisma                  : 3.9.0
@prisma/client          : 3.9.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by pantharshit00** [comment]
Hello! This is expected. Migrate expects to baseline the migration history with the database and easiest way of doing that is a reset: https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/baselining

So if you already know that the database already reflect the state of schema(like in your case), you can do the following to baseline without performing the migration: 
```sh
npx prisma migrate dev --create-only
npx prisma migrate resolve --applied <name of the migration> # This is the full directory in which the migration was created
```

After this step, everything should be in sync.

**Comment by luminous8** [comment]
Thank you @pantharshit00.

As soon as I'm doing 
```
npx prisma migrate dev --create-only
```

I'm asked to reset the db
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "test" at "127.0.0.1:3306"

Drift detected: Your database schema is not in sync with your migration history.

The following is a summary of the differences between the expected database schema given your migrations files, and the actual schema of the database.

It should be understood as the set of changes to get from the expected schema to the actual schema.

If you are running this the first time on an existing database, please make sure to read this documentation page:
https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/troubleshooting-development

[+] Added tables
  - collections

? We need to reset the MySQL database "test" at "127.0.0.1:3306".
```


Is there a way to perfom the migration without reseting the db?
(I've updated to Prisma 3.9.0 if that change anything)

**Comment by pantharshit00** [comment]
Oh yeah sorry. I forgot that `--create-only` won't render the migration before it asks for reset. You can do the following instead.
```sh
mkdir -p prisma/migrations/init/migration.sql
npx prisma migrate diff --preview-feature --from-empty --to-schema-datamodel prisma/schema.prisma --script > prisma/migrations/init/migration.sql
npx prisma migrate resolve --applied init
npx prisma migrate dev # it should say everything is in sync
```

You should also add a lock file manually here since you will creating the migrations folder by hand in `prisma/migrations/migration_lock.toml`
```toml
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "mysql"
```

**Comment by luminous8** [comment]
Thanks so much, it worked!
I've spent the whole week-end trying to figure out what was wrong on my side.

For my knowledge, did I missed something in the doc?

**Comment by pantharshit00** [comment]
No, `migrate diff` was actually released today. Good timing :)

**Comment by mrunalhajare** [comment]
> ```shell
> npx prisma migrate resolve --applied init
> ```

Hi @pantharshit00,
I tried the same steps as you mentioned above, but getting the below error, any idea what I'm doing wrong?

`Error: P3017

The migration init could not be found. Please make sure that the migration exists, and that you included the whole name of the directory. (example: "20201207184859_initial_migration")`

**Comment by mytchallb** [comment]
> 
I wrote an article showing the steps involved to use these commands if it helps:
https://mytchall.dev/posts/2022/using-prisma-and-directus/

**Comment by simplypress** [comment]
Hi I'm facing the same issue as @mrunalhajare. Here is what I'm doing:

1. `npx prisma db pull` -- Populates schema.prisma correctly
2. `npx prisma generate` -- Success generating
3. `mkdir -p prisma/migrations/init`
4. `npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > prisma/migrations/init/migration.sql` -- Creates migration.sql file in prisma/migrations/init directory
5. `npx prisma migrate resolve --applied init` -- ERROR

> Error: P3017
> 
> The migration init could not be found. Please make sure that the migration exists, and that you included the whole name of the directory. (example: "20201207184859_initial_migration")

Anything I'm doing wrong?

**Comment by simplypress** [comment]
@pantharshit00 any thoughts? I am on the latest version of Prisma btw.

**Comment by Twillied** [comment]
I getting the same error after following the same steps as above - any suggestions?

**Comment by janpio** [comment]
Open new issues please and provide all the information the issue template asks for. Then we can take a look.

**Comment by rhiskey** [comment]
> 5\. npx prisma migrate resolve --applied init

Change encoding of .sql file
https://github.com/prisma/prisma/issues/14762#issuecomment-1493371892

**Comment by VictorDevCode21** [comment]
> Oh yeah sorry. I forgot that `--create-only` won't render the migration before it asks for reset. You can do the following instead.
> 
> mkdir -p prisma/migrations/init
> npx prisma migrate diff --preview-feature --from-empty --to-schema-datamodel prisma/schema.prisma --script > prisma/migrations/init/migration.sql
> npx prisma migrate resolve --applied init
> npx prisma migrate dev # it should say everything is in sync
> You should also add a lock file manually here since you will creating the migrations folder by hand in `prisma/migrations/migration_lock.toml`
> 
> # Please do not edit this file manually
> # It should be added in your version-control system (i.e. Git)
> provider = "mysql"

I have been dealing with the same problem and you just solved it. Thank you so much, it was hard to get an answer that actually works.

**Comment by davidcollazos21** [comment]
When Prisma migrations are out of sync with a database that already contains data and applying new migrations requires a reset, one approach is to realign Prisma with the current schema without losing data. First, remove the **`prisma/migrations`** folder and clear the `prisma_migrations` table (this does not delete table data, only the migration history). Then run `npx prisma db pull` to sync the schema with the existing database. Next, generate an initial SQL script from the current schema using 
`npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > prisma/migrations/init/migration.sql`. 
Create a new migration folder (e.g. `prisma/migrations/20260204123045_init`), copy the generated SQL into its `migration.sql`, delete the temporary `init` folder, and mark the migration as applied with
 `npx prisma migrate resolve --applied 20260204123045_init`. 
After verifying the status with 
`npx prisma migrate status`, 
Prisma is fully synchronized and you can continue modifying `schema.prisma` and running migrations normally with 
`npx prisma migrate dev`. 
Always back up the database before doing this, and use this approach only when a reset is not viable.
