### ISSUE TITLE
MongoDB: On ID fields, replace `@default(dbgenerated())` with `@default(auto())`

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#11552]
`dbgenerated()` without argument will be deprecated, and is not specific enough to communicate what it does. On MongoDB, we want to replace `@default(dbgenerated())` with `@default(auto())`. It will:

- Be a new default value that is only valid on `@id` fields on mongodb
- Specifically mean "auto-generated object-id, generated by the database"
- Disconnect the validation from native types
	- The current rule is: if any field has any native type, it has to have an @default(dbgenerated()) default.
	- The new rule will be: `@default(dbgenerated())` is not valid on MongoDB.  `@default(auto())` is valid on ID fields with a type of `String @db.ObjectId`.

Internal design doc: https://www.notion.so/prismaio/Design-discussion-default-dbgenerated-on-MongoDB-b00073e4e86d45afa501c30719b703d0

**Comment by matthewmueller** [comment]
<img width="1059" alt="CleanShot 2022-02-08 at 14 04 45@2x" src="https://user-images.githubusercontent.com/170299/153066822-56e61779-a835-4c62-8ef1-369597ded809.png">

Beautiful

**Comment by janpio** [comment]
We disabled `dbgenerated()`, which is a function without a parameter with the more precise `auto()` exactly to avoid that one would thing that something like `dbgenerated("ISODate()")` would be possibly, which it never was. If you want this feature it would need a new feature request issue.
