### ISSUE TITLE
Provide log output when `.env` file is used

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#1155]
When running `prisma2 generate` and a `.env` file is being used, the CLI should log this.

**Comment by steebchen** [comment]
We don't support .env files yet: https://github.com/prisma/specs/issues/343

**Comment by janpio** [comment]
Current `dotenv` handling lives here: https://github.com/prisma/prisma2/blob/9b09581ec1283026f4acee9d3fce930a84ea02bc/cli/prisma2/src/bin.ts#L42-L63

**Comment by Jolg42** [comment]
Indeed right now this is only visible from the debug output but this issue means visible in stdout so I will do that :)
