### ISSUE TITLE
MongoDB: The connection string format and parameters are defined by mongo-rust-driver

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#11567]
On MongoDB, the datasource URLs from user schemas are always passed verbatim to the Rust MongoDB driver (https://github.com/mongodb/mongo-rust-driver). 

By contrast, on all SQL connectors, the logic of parsing the connection strings and defining the parameters live in Prisma code.

This state of affairs exposes us to:

- Risk of breaking changes upstream that we may not notice and would be hard to mitigate
- Risk if we ever want to use another driver
- Risk that we may want to define parameters that have meaning for prisma but not the underlying driver, at some point.
- Inconsistency with the rest of our connection strings

:concerned:

**Comment by Jolg42** [comment]
See [internal thread](https://prisma-company.slack.com/archives/C013RMLGE72/p1643788778009759)

**Comment by tomhoule** [comment]
We came to a consensus that:

- We should be consistent in whether we introduce prisma specific formats / params in connection strings, and this is going in the opposite direction from the SQL connectors.
- We prefer the mongo direction. In the future, we should strive to introduce prisma-specific things in the datasource block, not in the connection strings.
