### ISSUE TITLE
migrate diff: Provide a reliable way to detect empty diffs / migrations

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#11566]
## Problem

Diff returns the difference between two schemas. While often, you assume that there is a difference, and you are interested in the content, an obvious extension of this functionality is to detect _whether two schemas are the same_.

Analogous to text diffs like `git diff`, `migrated diff` can tell us if two database schemas are in sync. The only way to detect this programmatically at the moment is to expect a specific empty migration message. This solution is not elegant and subject to potential breaking changes.

## Suggested solution

- An `--exit-code` command like flag that would work like git diff's `--exit code` flag

> --exit-code
> Make the program exit with codes similar to diff(1). That is, it exits with 1 if there were differences and 0 means no differences.

## Alternatives

This is a thought I just had, more research should go into the suggested solution before we rush into implementation.

**Comment by Jolg42** [comment]
Related https://github.com/prisma/prisma/issues/9707

**Comment by tomhoule** [comment]
We're going with this mapping suggested by @do4gr :

```
# normal exit code
0 = Succeeded
1 = Error

# --exit-code (this is how terraform plan does it)
0 = Succeeded with empty diff (no changes)
1 = Error
2 = Succeeded with non-empty diff (changes present)

# Interaction with other flags
no limits, flag should only change exit code behaviour
```
