### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by PeaceAntoHim** [prisma/prisma#11563]
### Bug description

 class PrismaClient {
  101 |   constructor() {
> 102 |     throw new Error(
  103 |       `PrismaClient is unable to be run in the browser.
  104 | In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues`,
  105 |     )

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by pantharshit00** [comment]
Can you please share the steps to reproduce this?

**Comment by millsp** [comment]
Hey @PeaceAntoHim I'll be closing this issue as it seems you did not generate the prisma client. Please feel free to reach out if the problem persists with more information.

**Comment by PeaceAntoHim** [comment]
Ok Thnks for your replay
