### ISSUE TITLE
Go through the existing iTX and explore what needs to be worked on

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#11574]
This involves:
* Looking at existing issues
* Evaluating their severity
* Eventually get a repro working
* Plan what should be tackled

**Comment by millsp** [comment]
Required:
* https://github.com/prisma/prisma/issues/8668

Worth taking a look:
 * https://github.com/prisma/prisma/issues/11565
 * https://github.com/prisma/prisma/issues/10615
 * https://github.com/prisma/prisma/issues/10886
 * https://github.com/prisma/prisma/issues/11036

 Nice to have:
 * https://github.com/prisma/prisma/issues/11511
 * https://github.com/prisma/prisma/issues/9073
 * https://github.com/prisma/prisma/issues/9083
 
Can probably be closed:
* https://github.com/prisma/prisma/issues/8739
* https://github.com/prisma/prisma/issues/9846
* https://github.com/prisma/prisma/issues/11107

Unknown:
* https://github.com/prisma/prisma/issues/8708

**Comment by garrensmith** [comment]
Required:
* https://github.com/prisma/prisma/issues/7918
* https://github.com/prisma/prisma/issues/6156

Unknown:
* https://github.com/prisma/prisma/issues/5729
