### ISSUE TITLE
Generating Prisma client without any model in its schema

### ISSUE THREAD

**Issue by pzaenger** [prisma/prisma#11582]
## Problem

We have a server template including Prisma, which works fine so far. However, we now have another server extending this template without the need of models - just raw queries. While generating the Prisma client, via `npx prisma generate`, it is complaining about not having at least one model.

```
$ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: 
You don't have any models defined in your schema.prisma, so nothing will be generated.
```

Obviously correct - but in this case not wanted. So, we would like to use Prisma with basically `$queryRaw` and `$queryRawUnsafe` only.

## Suggested solution

It should be allowed to generate the Prisma Client without existing models in its schema.

## Alternatives

First guess would be to add a dummy model.

**Comment by janpio** [comment]
Interesting and valid use case. If we remove this hard limitation, we should probably find a way to instead communicate the missing of models another way to point it out to first time users of Prisma.

**Comment by jUddinSazim** [comment]
Almost a year, still no solutions?

**Comment by Gaen** [comment]
Upvoting. Start with a flag maybe? Like `npx prisma generate --allow-no-models`

**Comment by adjamerson** [comment]
I'd also like support this suggestion. I'm in a very similar situation as the OP, working with a service template but some services don't need any models, just the client.

**Comment by IsraelDeAraujo** [comment]
Yeah! I want this feature too!

**Comment by QBoulanger** [comment]
Same for me.

**Comment by anaelChardan** [comment]
Same for me, I don't understand how to it possible to not have any types for at lease `$connect`, and doing raw queries. It is necessary for a standalone library :/

**Comment by trustieee** [comment]
Same. I find myself creating a dummy model just to be able to use raw queries that aren't tied to a model.

**Comment by simonramosb** [comment]
Yes! I'm really needing this feature too!

**Comment by rockingrohit9639** [comment]
@janpio I want to work on this issue, if you can guide me a little.

**Comment by janpio** [comment]
I would start searching our codebase for the error message string, and then try to understand how it is thrown - and how it could be avoided.

**Comment by rockingrohit9639** [comment]
> I would start searching our codebase for the error message string, and then try to understand how it is thrown - and how it could be avoided. (Note: The codebase is not only this repository, but also `prisma-engines` - so maybe is relates to that)

Thank you.

**Comment by Kivanval** [comment]
Hi, thought I'd make my first contribution to open source :D

**Comment by Kivanval** [comment]
Hi, thought I'd make my first contribution to open source :D
@janpio I see that people come to you with questions, so after PR I just have to wait for some kind of result?

**Comment by joeyaurel** [comment]
@janpio I like the @kivanval's PR #22046. What do you think?

**Comment by kivanval** [comment]
@joeyaurel, I've already forgotten for updating the branch, took too long to accept, then need to revisit the decision again as CI breaks. :)

**Comment by gutyerrez** [comment]
> @janpio Any further update on this?

The pr #24160 will close this issue
