### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by k2nneth** [prisma/prisma#11586]
I faced this error while > npx prisma init

Downloading Prisma engines for Node-API for windows [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/bcc2ff906db47790ee902e7bbc76d7ffb1893009/windows/introspection-engine.exe.gz.sha256 failed, reason: self signed certificate in certificate chain

If I click on the link, i able to download the file. 

Any advice?

**Comment by walidmourou** [comment]
I have the same issue here...

**Comment by k2nneth** [comment]
Try to switch off your anti-virus, it may work.

**Comment by janpio** [comment]
Can someone please describe the full setup they are trying to use that does not work in a new bug report issue? We are happy trying to reproduce when we have the data necessary to understand the problem.

**Comment by walidmourou** [comment]
Windows 10 Enterprise (Company network with proxy)

`> node --version` 
`v16.14.0`

`> npm -g ls --depth=0`
`+-- blitz@0.45.3`
`+-- create-react-app@5.0.0`
`+-- nodemon@2.0.15`
`+-- npm@8.5.1`
`+-- serve@11.3.2`
`-- yarn@1.22.17`

`~\blitz-task-list-demo> blitz prisma migrate dev`
`Loaded env from ~\blitz-task-list-demo\.env.local`
`Loaded env from ~\blitz-task-list-demo\.env`
`> Downloading Prisma engines for Node-API for windows [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/bcc2ff906db47790ee902e7bbc76d7ffb1893009/windows/prisma-fmt.exe.gz.sha256 failed, reason: self signed certificate in certificate chain`

**Comment by eric79** [comment]
@janpio I opened a new bug here:  https://github.com/prisma/prisma/issues/12162

**Comment by andrew-gagliostro** [comment]
> I have the same issue here... But when I use `> blitz prisma generate`

Could you please explain what exactly blitz is doing here?

**Comment by nirajaky** [comment]
You can add this in your .env file, to make it work
NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by fidelis** [comment]
Ok, it worked for me: on windows 10, dont use poweshell but cmd.
 set NODE_TLS_REJECT_UNAUTHORIZED=0
 npx prisma init
