### ISSUE TITLE
Prisma generate > unlink index.d.ts

### ISSUE THREAD

**Issue by luminous8** [prisma/prisma#11583]
### Bug description

When trying to generate the client on my product server I get this issue:
**EACCES: permission denied, unlink '/srv/PROJET_NAME/api/node_modules/.prisma/client/index.d.ts'**

Prisma migrate has worked just fined
I've tried to uninstall prisma + prisma/client but nothing has changed.

```
USERNAME@server:/srv/PROJET_NAME/api$ npx prisma generate
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv project root found at /srv/PROJET_NAME/api/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /srv/PROJET_NAME/api/.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: /srv/PROJET_NAME/api/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node +0ms
  prisma:getDMMF Using CLI Query Engine (Node-API) at: /srv/PROJET_NAME/api/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node +0ms
  prisma:generator prismaCLIDir /srv/PROJET_NAME/api/node_modules/prisma +0ms
  prisma:generator prismaClientDir /srv/PROJET_NAME/api/node_modules/@prisma/client +0ms
  prisma:generator baseDir /srv/PROJET_NAME/api/prisma +1ms
  prisma:generator typescriptPath undefined +3ms
  prisma:GeneratorProcess 2022-02-02T21:38:51.259Z prisma:client:generator requiredEngine: libqueryEngine +0ms
  prisma:getGenerators neededVersions {
  "bcc2ff906db47790ee902e7bbc76d7ffb1893009": {
    "engines": [
      "libqueryEngine"
    ],
    "binaryTargets": []
  }
} +0ms
  prisma:getGenerators {
  prisma:getGenerators   generatorBinaryPaths: {
  prisma:getGenerators     libqueryEngine: {
  prisma:getGenerators       'debian-openssl-1.1.x': '/srv/PROJET_NAME/api/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node'
  prisma:getGenerators     }
  prisma:getGenerators   }
  prisma:getGenerators } +306ms
  prisma:GeneratorProcess 2022-02-02T21:38:51.970Z prisma:loadEnv project root found at /srv/PROJET_NAME/api/package.json +709ms
  prisma:tryLoadEnv Environment variables loaded from /srv/PROJET_NAME/api/.env +0ms
Error: Error: 
Error: EACCES: permission denied, unlink '/srv/PROJET_NAME/api/node_modules/.prisma/client/index.d.ts'


    at Object.parse (/srv/PROJET_NAME/api/node_modules/prisma/build/index.js:105342:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/srv/PROJET_NAME/api/node_modules/prisma/build/index.js:106752:18)
USERNAME@server:/srv/PROJET_NAME/api$ 
```

fyi, I've prisma installed on another project on the same server and it works fine

### How to reproduce

1. Run `npx prisma generate`

### Expected behavior

Generate the client

### Prisma information

I've been able to migrate the schema without any issue

### Environment & setup

- OS: Ubuntu 16.04.7 LTS
- Database: 5.7.34
- Node.js version: v16.6.2

### Prisma Version

```
prisma                  : 3.9.1
@prisma/client          : 3.9.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by pantharshit00** [comment]
This is very hard to reproduce. Try checking the permission of `.prisma` folder inside of `node_modules`.

**Comment by luminous8** [comment]
By permission you mean the chmod?
if yes It's 755 (which is the same on the other project that I have with prisma and works fine)

**Comment by luminous8** [comment]
I've changed both ```.prisma``` and ```prisma``` folders inside ```/node_modules``` chmod to 777 and it worked but I'm not very comfortable with this workaround

**Comment by janpio** [comment]
Is your application maybe already/still running when you run `prisma generate`?
You mention multiple times you could migrate the database - with which command and which machine? Also this server?

**Comment by hubsmoke** [comment]
@luminous8 If you're using Docker take a look if you're mounting a volume for node_modules. If you're also using WSL, could be related to how permissions work in that environment vs the Docker container. I had this problem while using Docker, and the chmod OR simply not mounting a volume fixed it.

**Comment by tmp-friends** [comment]
@luminous8 
I was facing a similar error in WSL2 + Docker:
**EACCES: permission denied, unlink '/app/backend/node_modules/.prisma/client/index.js'**

In my case, it was because `/node_modules/.prisma/client/index.js` was created in a container and can only be run as root user.

As a solution.
1. grant execute permission to the file
  -> `chmod 777 /node_modules/.prisma/client/index.js`.
2. change user and group permission from `root` to `node`
  -> `chown node:node /node_modules/.prisma/client/index.js`

**Comment by RylanH** [comment]
I am still facing this issue on Github Actions, which runs as root. I've tried to do a few things, but it still won't proceed.

```
yarn config set unsafe-perm true --allow-root
yarn
chown -R $(whoami):$(whoami) node_modules/.prisma/client
chmod 777 node_modules/.prisma/client/index.js
npx prisma generate
```

```
Prisma schema loaded from prisma/schema.prisma
Error: 
EACCES: permission denied, unlink '/github/workspace/node_modules/.prisma/client/index.js'
```

**Comment by millsp** [comment]
I am marking this issue as closed, as it is likely not an issue with Prisma but rather a permission configuration problem. If you can reproduce this consistently, please provide us with a reproduction repro and we will look into it.
