### ISSUE TITLE
Can't order by when using queryRaw and interpolated variable.

### ISSUE THREAD

**Issue by Fractured2K** [prisma/prisma#11584]
### Bug description

I have a simple query I'm trying to run.

```
const column = 'id';
const users = await prisma.$queryRaw`SELECT * FROM "user" ORDER BY ${column} DESC LIMIT 5`
```

When I run this the results come back as if the order by wasn't present. However, if I were to simply hardcode the column as such.

```
const users = await prisma.$queryRaw`SELECT * FROM "user" ORDER BY id DESC LIMIT 5`
```
It works as expected.

I've tried using the prisma query event to see if some parameter malformation was occurring but everything seemed normal there. Any ideas?

**UPDATE**: after messing around with things. I'm pretty sure it's a sanitization issue. However, I still want my query to be sanitized. What should I do from here?

### How to reproduce

Run any query with a parameterized ORDER BY

```
const column = 'id';
const users = await prisma.$queryRaw`SELECT * FROM "user" ORDER BY ${column} DESC LIMIT 5`
```

### Expected behavior

I expect the results to come back in an ascending or descending order using the passed in column. Unfortunately my results just comeback with the default index in ascending order.

### Prisma information

N/A

### Environment & setup

- OS: Windows Version 10.0.22000 Build 22000
- Database: Postgres 12.4
- Node.js version: v14.3.0

### Prisma Version

```
prisma                  : 3.9.0
@prisma/client          : 3.9.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by Luke265** [comment]
Yes, all template parameters are escaped when using `$queryRaw` more about that: https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#queryraw . 

If you want dynamic sql queries instead use `$queryRawUnsafe` https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#queryrawunsafe

Anyway, the same result can be achieved by e.g:

```
const column = "id"; // your column name
prisma.user.findMany({
    orderBy: {
        [column]: 'desc'
    },
    take: 5
});
```

**Comment by Fractured2K** [comment]
> Yes, all template parameters are escaped when using `$queryRaw` more about that: https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#queryraw .
> 
> If you want dynamic sql queries instead use `$queryRawUnsafe` https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#queryrawunsafe
> 
> Anyway, the same result can be achieved by e.g:
> 
> ```
> const column = "id"; // your column name
> prisma.user.findMany({
>     orderBy: {
>         [column]: 'desc'
>     },
>     take: 5
> });
> ```

Thanks for the reply. Unfortunately, I can't use the generated Prisma client for this as the SQL is very complete. I opted for the query above to explain my problem instead.

I'm just curious though as to why I can do something like such.

```
            AND clicks <= ${where.clicks_filter_lte}
            AND impressions >= ${where.impressions_filter_gte}
            AND impressions <= ${where.impressions_filter_lte}
            AND sales >= ${where.sales_filter_gte}
            AND sales <= ${where.sales_filter_lte}
            AND total_cost >= ${where.spend_filter_gte}
            AND total_cost <= ${where.spend_filter_lte}
            AND orders >= ${where.orders_filter_gte}
            AND orders <= ${where.orders_filter_lte}
            AND acos >= ${where.acos_filter_gte}
            AND acos <= ${where.acos_filter_lte}
            AND ctr >= ${where.ctr_filter_gte}
            AND ctr <= ${where.ctr_filter_lte}
            AND cpc >= ${where.cpc_filter_gte}
            AND cpc <= ${where.cpc_filter_lte}
```
and
```
                WHEN cardinality(${where.campaign_filter } :: text[]) > 0 THEN
                        table.id = ANY (${where.campaign_filter})
                     ELSE true
                END
```

and it has no issue, but if I add in simple order by it doesn't work. I get that there is some sanitization going on but is there any further explanation as to why I can't dynamize the order by?

**Comment by aljadan** [comment]
Encapsulate the column name with the `Prisma.sql` function. Your code should look like this:
```js
const column = Prisma.sql`id`;
const users = await prisma.$queryRaw`SELECT * FROM "user" ORDER BY ${column} DESC LIMIT 5`;
```

With this change, the ordering should work correctly.

**Comment by fellmann** [comment]
Just found out there seems to be an easy solution, although it feels like a hack:

```typescript
const field = Prisma.sql(["Nachname"]);
const direction = Prisma.sql(["asc"]);
await prisma.$queryRaw`SELECT * FROM kontakt ORDER BY ${field} ${direction} LIMIT 10`;
```

This uses the way tagged templates work internally by calling the `Prisma.sql` function directly with an array of strings (or your own variable), bypassing the enforced escaping.

**Comment by franklinjavier** [comment]
@fellmann thank you. it worked better than using queryRawUnsafe
