### ISSUE TITLE
Allow `dataproxy` to have datasource overrides

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#11595]
### Bug description

https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#programmatically-override-a-datasource-url

This does not currently work with the client being generated with `dataproxy`.

### How to reproduce

Instantiate the Prisma Client with a datasource override as described in the docs. Generate, with `PRISMA_CLIENT_ENGINE_TYPE=dataproxy`

### Expected behavior

That should be handled by `DataProxyEngine`.

### Prisma Version

```
3.9.1
```

**Comment by janpio** [comment]
Next steps:
- @aqrln tests manually, PR is reviewed and merged, 🍾
