### ISSUE TITLE
Additions to the CLI

### ISSUE THREAD

**Issue by marcus-sa** [prisma/prisma#1160]
After having played around with creating Bazel rules for Prisma2 I've encountered the following features/issues that is a must have:

* `--schema` that lets the user specify a path (could be globs as discussed in other issues) to a Prisma schema definition.
* `--migrations` that can be used in conjunction with `--schema` flag when using `lift` for being able to define a specific directory to be used for writing/reading migration files.
* `--name` flag when using `prisma lift save --name hello` should have an option to not prepend the created migration directory name with a date like so `20191216225104-hello`
* Generators should not check if environment variables for datasources are set at build time, but rather it should be done at runtime.

<!--Here's the error being thrown when running `prisma lift save` under Bazel, which is where `--non-interactive` mode would come in handy: ~~
```
The above error occurred in the <TabIndexProvider> component:
    in TabIndexProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
 ERROR  Oops, an unexpected error occured!
Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry

    Yes            Send error report once
    No             Don't send error report
```-->

If PRs are being accepted, then I would gladly contribute.
I've managed to do everything above using https://github.com/ds300/patch-package, so it shouldn't be too hard to actually implement it in the source code.

**Comment by janpio** [comment]
Hey @marcus-sa, what made you close this issue again?

**Comment by marcus-sa** [comment]
@janpio must've clicked on the wrong button without noticing!

**Comment by janpio** [comment]
As usual with bigger projects like Prisma, we will have to make a decision in a larger context here which might take some time as our priorities are currently somewhere else. 

That being said, if you already have most of the code via `patch-package` (what an interesting tool!) and are willing to spend some time creating a few PRs knowing that the PRs might sit there for a while, we will gladly take a look at them when we get to it. Just make sure you separate the individual changes into their own PRs so we can accept them one by one. Please also include a description of the change and its goals in the PR description again so we have all the information to make a decision <3

**Comment by janpio** [comment]
An update:
- `--schema` has been added
- `--migrations` is tracked in https://github.com/prisma/migrate/issues/361
- `--name` does not have an issue yet
- The env vars not being checked on `prisma2 generate` should also be implemented soon

**Comment by matthewmueller** [comment]
Last (untracked) piece of this is:

The env vars not being checked on prisma2 generate should also be implemented soon

It looks like this was done in: https://github.com/prisma/prisma/issues/800

Closing.

**Comment by Zemnmez** [comment]
@marcus-sa got any tips on getting it working with Bazel?
