### ISSUE TITLE
`db execute` cannot resolve SQLite file path from schema

### ISSUE THREAD

**Issue by livthomas** [prisma/prisma#11626]
### Bug description

The new `db execute` command (https://github.com/prisma/prisma/issues/11514) is not able to properly resolve the path to an SQLite file specified in `prisma.schema` file. I have the `url` set to `file:../my.db`. It looks like it resolves this path as relative to the folder where `db execute` is run and not to the folder where `prisma.schema` file is located.

It only works if I set `url` to `file:./my.db` even though the actual DB file is in the parent directory. But this change breaks other scripts working with this file.

An easy workaround is to use `--url` parameter instead of `--schema`. But it would be better if I was able to use the schema file so there would only be a single source of truth for DB file location.

Another thing is that it is hard to detect this problem since the command doesn't even fail but creates another DB file two levels up in the folder structure and says `Script executed successfully`.

### How to reproduce

1. Create a simple schema pointing to an SQLite file in the parent directory.
2. Prepare SQL script that changes this database.
3. Execute the script using `db execute` command in the parent directory, e.g.:
    ```
    prisma db execute --preview-feature --schema prisma/schema.prisma --file "prisma/views/view1.sql"
    ```
4. See that the DB file in the parent directory hasn't been affected. Instead, the changes have been applied to a DB file that is located two levels up in the file system.

### Expected behavior

Prisma `db execute` command should resolve DB file path set in `schema.prisma` file relative to the schema file folder and not to the folder where the command has been executed.

### Prisma information

First lines of `prisma/schema.prisma` file:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:../my.db"
}
```

### Environment & setup

- OS: Linux 4.19.225-1-MANJARO
- Database: SQLite
- Node.js version: v17.3.0

### Prisma Version

```
prisma                  : 3.9.0
@prisma/client          : 3.9.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
Preview Features        : interactiveTransactions
```

**Comment by Jolg42** [comment]
### I can reproduce with the provided schema with `url      = "file:../my.db"`
```
❯ tree .
. (executing from here)
└── somefolder
    ├── main.ts
    ├── package.json
    ├── prisma
    │   ├── schema.prisma
    │   └── script.sql
    └── tsconfig.json

❯ prisma db execute --preview-feature --schema somefolder/prisma/schema.prisma --file somefolder/prisma/script.sql
Script executed successfully.

And `my.db` is created in the parent folder relative to where the command was executed.
```

### Replacing the url to `url      = "file:./my.db"`
```
❯ prisma db execute --preview-feature --schema somefolder/prisma/schema.prisma --file somefolder/prisma/script.sql
Script executed successfully.
```

`my.db` is created in the same folder as where the command is executed
```
❯ tree .
.
├── my.db
└── somefolder
    ├── main.ts
    ├── package.json
    ├── prisma
    │   ├── schema.prisma
    │   └── script.sql
    └── tsconfig.json
```
prisma CLI 3.9.1

**Comment by Jolg42** [comment]
And `db push` does it relative to the schema `url      = "file:../my.db"`

```
❯ tree .
. (executing from here)
└── somefolder
    ├── main.ts
    ├── package.json
    ├── prisma
    │   ├── schema.prisma
    │   └── script.sql
    └── tsconfig.json

❯ npx prisma@dev db push --schema=somefolder/prisma/schema.prisma
Prisma schema loaded from somefolder/prisma/schema.prisma
Datasource "db": SQLite database "my.db" at "file:../my.db"

SQLite database my.db created at file:../my.db

🚀  Your database is now in sync with your schema. Done in 22ms

And `my.db` is created in the parent of the prisma folder.

❯ tree .
.
├── package.json
└── somefolder
    ├── main.ts
    ├── my.db
    ├── package-lock.json
    ├── package.json
    ├── prisma
    │   ├── schema.prisma
    │   └── script.sql
    └── tsconfig.json
```

**Comment by Jolg42** [comment]
Thanks for your report, we will look into this! 💚

**Comment by tomhoule** [comment]
Hi @livthomas — the fix is merged, it will be in next tuesday's release :)

**Comment by livthomas** [comment]
Thanks @tomhoule! I can confirm it works as expected now.
