### ISSUE TITLE
Unique/Index keeps getting recreated

### ISSUE THREAD

**Issue by flipswitchingmonkey** [prisma/prisma#11631]
### Bug description

Following the schema defined below, prisma generates the following initial migration:

```
-- CreateTable
CREATE TABLE "authors" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "image_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "authors_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "documents" (
    "id" SERIAL NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "authors_name_key" ON "authors"("name");

-- CreateIndex
CREATE INDEX "documents_updated_at_idx" ON "documents"("updated_at" DESC);

```

So far so good.

Now I run `npx prisma migrate dev --create-only --name something` and make NO changes to the Author or Document model in the schema:

```
/*
  Warnings:

  - A unique constraint covering the columns `[name]` on the table `authors` will be added. If there are existing duplicate values, this will fail.

*/

-- DropIndex
DROP INDEX "authors_name_key";
-- DropIndex
DROP INDEX "documents_updated_at_idx";

-- CreateIndex
CREATE UNIQUE INDEX "authors_name_key" ON "authors"("name");
-- CreateIndex
CREATE INDEX "documents_updated_at_idx" ON "documents"("updated_at" DESC);
```

And it does this for all other similar models too in the schema! Which will obviously fail, since the index can't just be deleted on everything.

This happens again at every migration.

### How to reproduce

See description.

### Prisma information

This is just an excerpt...
```
datasource db {
  provider = "postgresql"
  url      = env("DB_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["extendedIndexes", "filterJson"]
}

model Author {
  id        Int                @id @default(autoincrement())
  name      String             @unique
  image     Asset?             @relation(fields: [imageId], references: [id])
  imageId   Int?               @map("image_id")
  contents  AuthorsToContent[]
  createdAt DateTime           @default(now()) @map("created_at")
  updatedAt DateTime           @default(now()) @updatedAt @map("updated_at")

  @@map("authors")
}

model Document {
  id              Int                           @id @default(autoincrement())
  createdAt       DateTime                      @default(now()) @map("created_at")
  updatedAt       DateTime                      @default(now()) @updatedAt @map("updated_at")

  @@index([updatedAt(sort: Desc)])
  @@map("documents")
}
```

### Environment & setup

- OS: Ubuntu 20.04
- Database: PostgreSQL
- Node.js version: 17.3.1

### Prisma Version

```
prisma                  : 3.9.1
@prisma/client          : 3.9.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
Preview Features        : extendedIndexes, filterJson
```

**Comment by pantharshit00** [comment]
Thanks for the detailed, I can confirm this issue.

**Comment by jerrywithaz** [comment]
I can also confirm this issue, I was just about to post the same thing

**Comment by recurrence** [comment]
Is there a version to downgrade to that does not have this problem?

**Comment by JoniBR** [comment]
any temporary solution for this?

**Comment by flipswitchingmonkey** [comment]
> any temporary solution for this?

only to manually remove the offending lines from the migration file. it works afterwards. (but has to be done every time a new migration is created)

**Comment by eakriulin** [comment]
Can confirm — just ran into the same issue 👍

**Comment by recurrence** [comment]
I've back resolved this by running a function that removes these lines and then updates the database migrations tables by recalculating the sha256 hashes.

**Comment by ydhn** [comment]
I'm struggling with the same issue, would be nice if this issue would be resolved quickly since `extendedIndexes` feature is very important to me for use at the production level  
everybody uses a lot of indexes, right? 😄

**Comment by trevoro** [comment]
Just chiming in here as I'm experiencing the same problem. Every re-run of the database creation from scratch results in a new migration being applied.

**Comment by ctsstc** [comment]
Thought I was doing something wrong, and tried cleaning up and resetting the schema and database from the initial interpolation and still ran into this issue. Glad to see it's not only me 😅

**Comment by janpio** [comment]
(Please keep posting more information about the schemas you have. The more variants we know, the more we can fix or confirm that our main fix also solved all other related problems. That would be very valuable.)

**Comment by ctsstc** [comment]
Note: this is what I'm seeing on a Postgres database with a fresh DB and an initial migration (only 1), while using PGAdmin to view the database.

## Simplified Example

With this on the model, shouldn't there be a constraint for it? I do see an index that's been created, but no constraint.

```prisma
model HouseholdTaxSettings {
  id               String    @id @default(uuid()) @db.Uuid
  householdId      String    @db.Uuid
  taxYear          Int
  household        Household @relation(fields: [householdId], references: [id])

  @@unique([householdId, taxYear])
  @@index([householdId])
}
```

<img width="360" alt="image" src="https://user-images.githubusercontent.com/416814/158714491-515cef57-12e2-4701-ad2c-6a984e39d5af.png">

## Another Simplified Example

The warnings are also coming from the `@unique` definitions too.
Seems like there should be a uniqueness constraint here which it seems to not exist.

```prisma
model User {
  id                           String                        @id @default(uuid()) @db.Uuid
  email                        String                        @unique @db.VarChar
}
```

<img width="175" alt="image" src="https://user-images.githubusercontent.com/416814/158714801-c6ff96c3-6163-4928-b7b2-832744e710dd.png">

**Comment by do4gr** [comment]
Thanks for reporting this everyone and sorry it took us so long to fix this!

**Comment by janpio** [comment]
You can try this temporarily now with `prisma@dev` - would be great if you could report back if the problem is fixed for you. This will be included in the next release on Tuesday, but early feedback would give us confidence and make us happy 😄

**Comment by ctsstc** [comment]
Awesome! I was afraid this wasn't going to make the upcoming release, glad to hear it's going to make it 🎉 

This is nice to see ^__^
It works!!!
Thanks :D 

```sql
-- This is an empty migration.
```

**Comment by richardwu** [comment]
> You can try this temporarily now with `prisma@dev` - would be great if you could report back if the problem is fixed for you. This will be included in the next release on Tuesday, but early feedback would give us confidence and make us happy 😄

Worked like a charm: literally ran into this just now, thanks for the fix!
