### ISSUE TITLE
Support opaque/branded IDs / types

### ISSUE THREAD

**Issue by nickluger** [prisma/prisma#11647]
## Problem

Using the [branded/opaque type pattern](https://medium.com/@KevinBGreene/surviving-the-typescript-ecosystem-branding-and-type-tagging-6cf6e516523d) is currently not possible with Prisma. For example we're not able to create a protected `UUID` or `Cuid` type, because the Prisma client will always use String, Number etc. in the generated client code.

## Suggested solution

Allow creating custom branded/opaque types in schema or via the `PrismaClient`-constructor. 

## Alternatives

Manual casting is impractical because Prisma returns deeply nested objects, and one would have to cast every occurrence within the object structure.

## Context
I know https://github.com/prisma/prisma/issues/7161 exists, but it is gravitating towards Active-record like ORM-building, which is something completely different. This here would not affect any runtime behavior. Closest is https://github.com/prisma/prisma/issues/6349, but I think the use case is more generic than FKeys.

**Comment by pantharshit00** [comment]
Hello,

Do you have an example snippet here which you can share on how this can look in the client?

**Comment by nickluger** [comment]
True
