### ISSUE TITLE
Migration dev error

### ISSUE THREAD

**Issue by luminous8** [prisma/prisma#11668]
### Bug description

Hi,

When doing a ```migrate dev``` after a successful migration I've got this error

```
Database error code: 1146

Database error:
Table 'prisma_migrate_shadow_db_530924f1-71bc-41c3-97ed-dc1a6a373b37.versions_old' doesn't exist
````

But I don't have this table in my db

Complete error log
````
Error: P3006

Migration `20220206213143_remove_versions_old` failed to apply cleanly to the shadow database. 
Error code: P3018
Error:
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20220206213143_remove_versions_old

Database error code: 1146

Database error:
Table 'prisma_migrate_shadow_db_530924f1-71bc-41c3-97ed-dc1a6a373b37.versions_old' doesn't exist

Please check the query number 1 from the migration file.
````

And the migration file looks like this 
```
/*
  Warnings:

  - You are about to drop the `versions_old` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE `versions_old` DROP FOREIGN KEY `versions_old_ibfk_2`;

-- DropForeignKey
ALTER TABLE `versions_old` DROP FOREIGN KEY `versions_old_ibfk_3`;

-- DropTable
DROP TABLE `versions_old`;
```

but has already been applied without any issue (I've removed a table)

### Expected behavior

Migrate without any issue

### Environment & setup

- OS: Mac Os
- Database: Mysql 8.0.22
- Node.js version: v16.13.0

### Prisma Version

```
prisma                  : 3.9.1
@prisma/client          : 3.9.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by luminous8** [comment]
I've done the migration manually with this command
```
npx prisma migrate resolve --applied "20220207181718_remove_versions_old"
```

It works but as soon as I'm doing a small change in the prisma schema and try to run ```npx prisma migrate``` I've got the same error as indicated above.

I'm really struggling to understand why I'm getting this message as the migration has been done

**Comment by Jolg42** [comment]
Hi @luminous8!

About 
```
npx prisma migrate resolve --applied "20220207181718_remove_versions_old"
```

`resolve` doesn't execute SQL migration files, and is only useful for a production database where `--applied` can be used to mark a migration as applied.
The common use-case for that would be that if a migration fails in production and you somehow fix it manually, you want `migrate deploy` to not try to reapply that migration you manually finished.

Could you try doing the following on your local database?
- `prisma migrate reset` (so we start clean, and get rid of the migration table which was latered by `migrate resolve`)
- `prisma migrate dev` (to create a new migration if needed)

**Comment by luminous8** [comment]
Thanks for your reply!

I've updated my db with a copy of the production (that hasn't been impacted by the migration that fails)

When doing ```prisma migrate reset```

I've got these errors 

```
npx prisma migrate reset
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "my-db" at "127.0.0.1:3306"

✔ Are you sure you want to reset your database? All data will be lost. … yes

Applying migration `20220202211900_`
Applying migration `20220207181718_remove_versions_old`
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20220207181718_remove_versions_old

Database error code: 1146

Database error:
Table 'my_db.versions_old' doesn't exist

Please check the query number 1 from the migration file.
```

I feel like in my stuck in a loop here 😅

**Comment by Jolg42** [comment]
Does that `versions_old` table exist in your production database? 

If not present, it looks like you could delete that migration directory and file `20220207181718_remove_versions_old` since it will not be possible to drop a non-existing table.

**Comment by luminous8** [comment]
Thanks @Jolg42 for your answer!

Yes the table ```versions_old```exist in my production database that's why I don't really understand why it fails.

When importing the production db (with the versions_old table) in local, doing the migration with ```prisma migrate dev``` I get an error but when doing ```npx prisma migrate deploy``` in local it works and the migration is applied successfully.

But then at soon as I'm doing a small change in the schema I'm getting this error again.

I have no idea how to fix this and I have been trying different things for a few days.

**Comment by luminous8** [comment]
i've tried something else

- used the production db in local
- do ```npx prisma db pull``` → Update the schema 
- do ```npx prisma db migrate dev``` → ✅ everything works fine
- add a new field in a table and do ```npx prisma db migrate dev``` → ✅ Migration works
- Delete versions_old table again (and the relations)
- do ```npx prisma db migrate dev```→ ❌ got this error:

```
Error: P3006

Migration `20220209213808_` failed to apply cleanly to the shadow database. 
Error code: P3018
Error:
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20220209213808_

Database error code: 1146

Database error:
Table 'prisma_migrate_shadow_db_77500137-2f6f-4a0b-9b6e-d152a2992bd1.versions' doesn't exist

Please check the query number 1 from the migration file.
```

**Comment by tomhoule** [comment]
The error message is different in your last comment. Would you be comfortable sharing the `20220209213808_` migration? (it's not the one about version_old).

**Comment by tomhoule** [comment]
That's very weird indeed. Are you sure you are dealing with a single database? Could the shadow database and the main database be the same?

**Comment by luminous8** [comment]
`Are you sure you are dealing with a single database?`
What do you mean exactly? 
I've only one db declared in my .env in the ```DATABASE_URL``` variable

`Could the shadow database and the main database be the same?`
I'm not even sure how that would be possible 😅. How can I check that?
On my side I've only my db in MYSQL (apart from other database but that don't have the same name and that are not declared in my project or in Prisma

**Comment by tomhoule** [comment]
`migrate dev` is applying the same migrations multiple times in the examples you gave, so successes and failures to apply migrations should be repeatable - unless something else changes, like the database the migrations are being applied to. But it doesn't seem to be that.

So to recap, you can do a clean `migrate reset`, but a subsequent `migrate dev` with the same migrations and the same database fails, right? If the `migrate reset` failed, it would point to a faulty migration, but if it succeeds, there's something I don't understand.

**Comment by luminous8** [comment]
I've started again with a copy of my database production in local

Here's the steps I followed:

- used the production db in local
- do ```npx prisma db pull``` → ✅ Update the schema 
- do ```npx prisma migrate dev``` → ✅
- delete ```versions_old``` table (and the relations)
- do ```npx prisma migrate dev```→ ✅
```
⚠️  Warnings for the current datasource:

  • You are about to drop the `versions_old` table, which is not empty (9112 rows).

✔ Are you sure you want create and apply this migration? … yes
✔ Enter a name for the new migration: … 
Applying migration `20220211073816_`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20220211073816_/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (3.9.1 | library) to ./node_modules/@prisma/client in 354ms
```

- Add a new random field → ✅
```tweet_id                String?                   @db.VarChar(20)```

- do ```npx prisma migrate dev``` → ❌
```
Error: P3006

Migration `20220211073816_` failed to apply cleanly to the shadow database. 
Error code: P3018
Error:
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20220211073816_

Database error code: 1146

Database error:
Table 'prisma_migrate_shadow_db_7d40e376-bc9d-41c0-912f-a4e4fd889018.versions_old' doesn't exist

Please check the query number 1 from the migration file.
```

> Here i don't understand why I got this error (```Table 'prisma_migrate_shadow_db_7d40e376-bc9d-41c0-912f-a4e4fd889018.versions_old' doesn't exist```) as I've delete it in the first migrate and had a success message

- Do ```npx prisma reset``` → ❌
```
✔ Are you sure you want to reset your database? All data will be lost. … yes

Applying migration `20220202211900_`
Applying migration `20220211073816_`
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20220211073816_

Database error code: 1146

Database error:
Table 'my_db.versions_old' doesn't exist

Please check the query number 1 from the migration file.
```

Once thing I've noticed is that compared to the other tests I've done, my first migration was to remove versions_old first and it work. I have the feeling that the first migration always works but then there's an issue on the second one. (I might be wrong tho)

**Comment by tomhoule** [comment]
I'm wondering whether it may be a migration ordering issue. The migrations are applied in alphanumeric order (so in practice, ordering of the timestamps) as they are found in the migrations directory. From what you posted, it looks like that's not the problem.

> delete versions_old table (and the relations)

In that step, you mean you do that in the prisma schema, not the database, right?

I'm not giving up on figuring this out, but I have to admit it's very puzzling, I can't see what could be going wrong yet.

**Comment by tomhoule** [comment]
Was the `versions_old` table created in one of your previous migrations? (do you still have the migration that created it in your migrations directory?)

**Comment by luminous8** [comment]
> > delete versions_old table (and the relations)
> In that step, you mean you do that in the prisma schema, not the database, right?
Yes indeed, my goal is really to use prisma for everything and stop doing changes in the database manually 

> I'm not giving up on figuring this out, but I have to admit it's very puzzling, I can't see what could be going wrong yet.
🙇

**Comment by luminous8** [comment]
> > delete versions_old table (and the relations)
> In that step, you mean you do that in the prisma schema, not the database, right?
Yes indeed, my goal is really to use prisma for everything and stop doing changes in the database manually 

> Was the versions_old table created in one of your previous migrations? (do you still have the migration that created it in your migrations directory?)
No, it was already in the existing db when I initialised prisma (I had [this error](https://github.com/prisma/prisma/issues/11555#issue-1121008301) but I don't think it's related)


> I'm not giving up on figuring this out, but I have to admit it's very puzzling, I can't see what could be going wrong yet.
Thank you so much! I hope it doesn't comes from a mistake from my side. It's annoying because I know how helpful prisma can be (using it on a project where I started from scratch)

**Comment by luminous8** [comment]
Quick sunday thought:
What if I restart from scratch the instation of Prisma? Would it break in prod where I have already made some migrations with Prisma?

**Comment by tomhoule** [comment]
So the problem is the `pull` ing from the production database with existing migrations that don't lead to the same point, so your databases have gone out of sync.

I can see at least two ways to get out of this situation:

1. Re-doing your migration history (squashing), and [baselining](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/baselining) your production database.
2. Use `prisma migrate diff --preview-feature --from-url $YOUR_PROD_DATABASE_URL` --to-schema-datamodel ./prisma/schema.prisma` (with and without `--script`) and see what is not matching. With the same command with `--script`, it would give you the SQL you need to bring your prod database in sync with your local schema. That will probably involve dropping `old_version`. I'd review that carefully before applying, of course, but then you can mark your migrations as applied in your production database and everything should be back in sync.

**Comment by luminous8** [comment]
I not really sure how to do the squashing part. Do you have an link to a tutorial?
I'm not comfortable doing the 2nd option (if I understand correctly it will do changes directly on my db in production?).

I've tried something else, deleted all migrations in the db and the whole prisma folder.

Started again with ```prisma init``` and followed [these steps](https://github.com/prisma/prisma/issues/11555#issuecomment-1027242342)
The first migration worked and the second failed again as on the other tests I've. I think I'll give up at that stage.

**Comment by tomhoule** [comment]
- For squashing, it would basically be deleting your migration files, generating a single new migration that takes the schema from empty to your current prisma schema, and then baselining with that migration.

- The `diff` command in the second option will just print SQL, it won't execute anything on your prod database (just read the schema) — so then you can read the SQL, review it, and if you are sure it is fine, then apply it to your prod database.

**Comment by luminous8** [comment]
I've tried both solutions and still got the same error message. 

```
npx prisma migrate resolve --applied 20220207181718_remove_versions_old
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "DB_NAME" at "127.0.0.1:3306"
Migration 20220207181718_remove_versions_old marked as applied.

npx prisma migrate dev                                                 
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "DB_NAME" at "127.0.0.1:3306"

Error: P3006

Migration `20220207181718_remove_versions_old` failed to apply cleanly to the shadow database. 
Error code: P3018
Error:
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20220207181718_remove_versions_old

Database error code: 1146

Database error:
Table 'prisma_migrate_shadow_db_29d10b53-61e1-4702-9cbe-aee78d423609.versions_old' doesn't exist

Please check the query number 1 from the migration file.
```

I might be doing something wrong but i have no idea what it is and even when starting from scratch I'm not able to fix this.

I'm desperate at this point

**Comment by tomhoule** [comment]
What does `prisma migrate diff --preview-feature --from-database <your prod database> --to-migrations ./prisma/migrations --script --shadow-database-url <a temporary db url>` return? (it won't write anything except to the shadow database)

It should return the same as `prisma migrate diff --preview-feature --from-database <your prod database> --to-schema-datamodel ./prisma/schema.prisma --script` (it will only read from the database)

**Comment by luminous8** [comment]
What does `prisma migrate diff --preview-feature --from-database <your prod database> --to-migrations ./prisma/migrations --script --shadow-database-url <a temporary db url>` return? (it won't write anything except to the shadow database)
> Error: 
> unknown or unexpected option: --from-database

It should return the same as `prisma migrate diff --preview-feature --from-database <your prod database> --to-schema-datamodel ./prisma/schema.prisma --script` (it will only read from the database)

> For this one I didn't succeed to access my prod database so I used a recent backup of my prod db (which is the same as my starting point)
>
>  mysql://root:pass@localhost:3306/my_db Do you confirm that to login to my db I need to replace localhost by my server ip? 
>
>When I'm doing that I have this error 
```
Error: P1001

Can't reach database server at `178.XX.XXX.XX`:`3306`

Please make sure your database server is running at `178.XX.XXX.XX`:`3306`.
```

**Comment by tomhoule** [comment]
> Do you confirm that to login to my db I need to replace localhost by my server ip?

Yep.

>  unknown or unexpected option: --from-database

Ah sorry, I think it's `--from-url`

**Comment by luminous8** [comment]
Last update and I'll close the ticket.

I've choose an another path (one that was accessible for me in term of knowledge).

- backed up my prod db content only
- delete all prisma migratation history and started over
- generated the db in local based on the schema
- imported the db content in local
- exported my local db to prod

And it worked.

It cost me a few minutes of downtime but it was way simpler for me.

I still cannot explain why I've had this issue but I'm glad this is over (🤞)

**Comment by xphonse** [comment]
This just happened to me, the problem was that I baselined my migrations with the name "init", then when a second migration was created it had  the current date as a prefix "2022121718162_..."
When the shadow database tried running the migrations, it started with the second one, thus not finding a table because it wasn't yet created.

Renaming the baseline with "2021_init" solved the problem.

**Comment by aqibgatoo** [comment]
> This just happened to me, the problem was that I baselined my migrations with the name "init", then when a second migration was created it had the current date as a prefix "2022121718162_..." When the shadow database tried running the migrations, it started with the second one, thus not finding a table because it wasn't yet created.
> 
> Renaming the baseline with "2021_init" solved the problem.

Wohooo, this is ridiculous, I had also named my initial baselined migration as init, and I was getting the shadow table error. Your comment has turned to be a saviour, Cheers!
