### ISSUE TITLE
Allow max number of PrismaClient's to be specified

### ISSUE THREAD

**Issue by blevine** [prisma/prisma#11660]
There is currently a warning issued by Prisma when more than 10 clients are created.  This was *very* helpful in alerting me to the fact that there was a bug in the way I was instantiating the Prisma client. In my case (and as is recommended by Prisma), I really want only one client to be created. I do that in a singleton class. 

What might be even more helpful would be to pass the max number of intended clients in the PrismaClientOptions so that the warning is issued even sooner.  In my case, I would set that to 1.  Others might have valid reasons for instantiating multiple clients and would set that value accordingly.

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
