### ISSUE TITLE
[MDB] Implement version and describe RPC calls for the error reporting backend

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#11691]
Those just have a default implementation atm. 

<img width="831" alt="Screen Shot 2022-02-08 at 10 46 34" src="https://user-images.githubusercontent.com/16278407/152961830-0b38f8bf-cbe0-4b28-b5ec-72c4c46b2171.png">

**Comment by matthewmueller** [comment]
Is this the same as https://github.com/prisma/prisma/issues/10060 ?

**Comment by janpio** [comment]
Is there a simple way to test this @do4gr?
