### ISSUE TITLE
Easing the migration to Prisma 2

### ISSUE THREAD

**Issue by frandiox** [prisma/prisma#117]
Hi. I like in general where the project is going, but I'm afraid of having a hard time migrating to Prisma 2. Here are some thoughts:

#### JSON type

Prisma 1 stored Json as strings in DB. How will these fields be migrated to a native Json type?

#### Schema delegation

There are still users that rely on schema delegation, as mentioned in #116 . Supporting that would make things easier for projects that started in early versions before Prisma Client was a thing. [Something like this](https://github.com/frandiox/graphql-info-transformer) could be interesting.

#### Using v1 and v2 in the same DB

If I understood correctly a conversation on Slack, I think the current Prisma 1 locks the database and won't allow Prisma 2 to use it at the same time. For example, in our case we have 3-4 applications in the same database (same Prisma service, different schemas).

This works quite well today but, since Prisma 2 won't be able to use the same DB because v1 is taking control of it, we would need to migrate all the apps to Prisma 2 at once, so we can remove v1 server. Also, we cannot develop new apps in that DB using v2 so we would need to prioritize migration.

Would it be possible to update the current v1 to make migrations like this smoother? Having both v2 and v1 working in the same DB -- in different schemas -- would allow migrating apps 1 by 1.

Thanks!

**Comment by alan345** [comment]
Same here. Prisma2 looks great. But 
-I could not see any documentation regarding the migration from primsa1 to prisma2 yet.
-it reminds me the angular1 to angular2 where they completely change the framework. It was such a bad experience for developers

**Comment by darrylyoung** [comment]
@pantharshit00 Is there some documentation showing how to migrate to Prisma 2? Migrate, not set up fresh (with Prisma 2). Thanks!

**Comment by stefanwalther** [comment]
Yes, same here ... I am starting with some new project and would like to understand whether it is better to choose Prisma (and then later migrate to Prisma2) or whether I should try to start using Prisma2 immediately (considering that I will anyhow probably not be in production within the upcoming 4-5 months).

Thanks!

**Comment by nikolasburk** [comment]
Hey @stefanwalther 👋  if you're getting started with a new project today and it's expected to launch in 4-5 months, it's a great time to get started with Prisma 2! 

While we're still in development, things are stabilizing quickly. We've also set out a launch timeline and are planning to release [Photon.js in Q1 and Lift in Q2 2020](https://www.prisma.io/blog/state-of-prisma-2-december-rcrwcqyu655e).

We also have a first [migration guide]
(https://github.com/prisma/prisma2/blob/master/docs/upgrading-from-prisma-1.md) that explains how to migrate from Prisma 1 to Prisma 2. More detailled guides that target specific upgrade scenarios, e.g. migrating from Prisma 1 with `prisma-binding` or with from `nexus-prisma` are going to follow! 

Please let me know if you have any further questions! 🙂

**Comment by janpio** [comment]
Internal Note: Dropping from current sprint, and picking up later.

**Comment by mitchhankins01** [comment]
@nikolasburk 
the migration guide link is broken

**Comment by alan345** [comment]
> @nikolasburk
> the migration guide link is broken

https://github.com/prisma/prisma/blob/master/docs/upgrade-guides/upgrading-from-prisma-1.md is the new link. 
But I guess the commands should be updated as they renamed prisma2 to prisma and prisma to prisma1

**Comment by janpio** [comment]
@nikolasburk is currently rewriting that document. The version you linked to very much is outdated as well unfortunately. Expect an update here soon.

**Comment by alan345** [comment]
Cool! Thanks @janpio let us know when it is done!

**Comment by janpio** [comment]
A first iteration: https://www.prisma.io/docs/guides/upgrade/upgrading-from-prisma-1

**Comment by alan345** [comment]
Thanks!

**Comment by terion-name** [comment]
@janpio this doesn't cover the delegation feature. My system for instance is heavilly using prisma-binding's forwarding and crud exposing, this feature was a deal breaker to choose Prisma. Now I don't see any possibility to replace `forwardTo` or direct forwarding of resolver `info` into client and this is horrible. It was the most useful feature of Prisma IMO

**Comment by janpio** [comment]
Is there a feature request issue that describes this usecase and functionality? If so, please link to it here for context - and if not please create one and link to it here as well. I can not promise we will be able to offer anything here, but we certainly want to understand and have a look.

**Comment by frandiox** [comment]
@janpio https://github.com/prisma/prisma/issues/116 is an issue about schema delegation in Prisma 2. Perhaps you can open it again if you think it's useful.

**Comment by janpio** [comment]
I did so for now - but still would prefer a proper feature request that explains the use case and describes the functionality. Reading #116 still does not give that to me, so makes it hard to pick up.

**Comment by frandiox** [comment]
@janpio I've modified the original issue to make it a bit more useful.

**Comment by janpio** [comment]
I think you can find the most recent information on how to upgrade to P2 in this issue: https://github.com/prisma/prisma/issues/1937 and specially comments like https://github.com/prisma/prisma/issues/1937#issuecomment-627493983

I am going to close this issue now, but please let us know here or in a new issue if there are still things you could use some support with. Thanks!
