### ISSUE TITLE
Prisma apparently forwards empty fields to db in `where` queries

### ISSUE THREAD

**Issue by ljosberinn** [prisma/prisma#11718]
### Bug description

I've run into the following scenario building a search:

```js
    const rawData = await prisma.fight.findMany({
      where: {
        chests: {
          gt: 0,
        },
        percent: {
          lte: maxPercent,
          gte: 100,
        },
        dungeonID,
        totalDeaths: {
          lte: maxDeaths,
        },
        keystoneLevel: keyLevel,
        PlayerFight: {
          every: {
            player: {
              itemLevel: {
                gte: minItemLevel,
                lte: maxItemLevel,
              },
            },
          },
          some: {
            player: {
              specID: {
                in: specQuery.length === 1 ? specQuery : undefined,
              },
            },
          },
        }
```        
Everything except `dungeonID` is optional. As such, it makes no sense to query the rest since.. it doesn't hold a value.

However, this query, even when _exclusively_ `dungeonID` is passed, takes over a **minute** to execute. Took me a while to figure out that apparently prisma forwards the empty fields in some way to the db.

### How to reproduce

Conditionally adding fields to the query based on presence however changes this drastically:

```js
    const rawData = await prisma.fight.findMany({
      where: {
        dungeonID,
        chests: {
          gt: 0,
        },
        percent: {
          ...(maxPercent ? { lte: maxPercent } : null),
          gte: 100,
        },
        ...(maxDeaths ? { totalDeaths: { lte: maxDeaths } } : null),
        ...(minItemLevelAvg || maxItemLevelAvg
          ? {
              averageItemLevel: {
                ...(minItemLevelAvg ? { gte: minItemLevelAvg } : null),
                ...(maxItemLevelAvg ? { lte: maxItemLevelAvg } : null),
              },
            }
          : null),
        ...(specQuery.length === 1
          ? {
              PlayerFight: {
                some: {
                  player: {
                    specID: {
                      in: specQuery,
                    },
                  },
                },
              },
            }
          : null),
```

as you can see, very granular but heavily increased complexity.

Yet, this query completes in less than three **seconds** on average, passing only `dungeonID`.

### Expected behavior

Prisma prunes `undefined` fields before forwarding them to the db.

### Prisma information

https://github.com/ljosberinn/keystone-heroes/blob/master/prisma/schema.prisma

### Environment & setup

- OS: irrelevant
- Database: PostgreSQL
- Node.js version: Vercel LTS

### Prisma Version

3.9.1

**Comment by millsp** [comment]
This is by design and working as intended, although admittedly a bit painful. What happens is when your value is `undefined`, the field is completely erased from the query. This in turn widens your query much more, as for instance with:

```ts
percent: {
  lte: maxPercent,
  gte: 100,
},
```

Would become this, if `maxPercent` is `undefined`:

```ts
percent: {
  gte: 100,
},
```

This is a much wider query. To fix that, you enforced a `null` check on the query like:
```ts
percent: {
  lte: null,
  gte: 100,
},
```

This in turn will create an unsatisfiable sql `AND` condition similar to:

```sql
percent IS NULL AND percent >= 100
```

That automatically filters any case where you are missing `maxPercent`.

I suggest that you conditionally run one query or another based on your input nullability instead.

**Comment by janpio** [comment]
I created a related docs issue about this: https://github.com/prisma/docs/issues/5135
