### ISSUE TITLE
Request : add Date type

### ISSUE THREAD

**Issue by bmichotte** [prisma/prisma#11734]
### Discussed in https://github.com/prisma/prisma/discussions/9809

<div type='discussions-op-text'>

<sup>Originally posted by **bmichotte** October 17, 2021</sup>
Hi there,

If I have the following model 
```
model Foo {
    id        String    @id @default(cuid())
    createdAt DateTime  @default(now())
}
```

I can, on my pgsql database, query all the `Foo` created on a certain date with 
```sql
select * from "Foo" where "createdAt"::date = '2021-10-17'
```
or with 
```sql
select * from "Foo" where CAST("createdAt" AS DATE) = '2021-10-17'
```

Is there any way to do it with prisma ?

Actually, the only way I found is 
```js
await prisma.foo.findMany({
   where: {
      AND: [
          { createdAt: { gte: new Date('2021-10-17 00:00:00') }},
          { createdAt: { lte: new Date('2021-10-17 23:59:59') }}
      ]
   }
})
```

which is not convenient and could lead to errors.

Is the only way to get that query is to create the model with another `DateTime @db.Date` field which will allow to use `{ theField: new Date() }` ?</div>

This could also be usefull for any birthdate, like we never store a birthdate as a datetime, but as a date 

So, is there any way to add a `Date` type ? And then, with that date field, make any `eq/lt/lte/gt/gte` queries which will accept a JS Date and do the query with `YYYY-MM-DD`  ?

**Comment by janpio** [comment]
Date exists as a native type for `DateTime` Prisma scalar, `@db.Date`: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#postgresql-6 Is that what you are looking for?

**Comment by bmichotte** [comment]
oh, I wasn't aware that `DateTime @db.Date` worked like that

```
const users = await prisma.user.findMany({
        where: {
            birthdate: { equals: new Date('1978-10-06') },
        },
    })
```

Works like a charm.
My bad and thank you for your response

**Comment by yassernasc** [comment]
It works but I would like to use date as string.

**Comment by CyanoFresh** [comment]
yes, date string (without time) would make more sense. Now I need to wrap all my Date fields with `new Date()`
