### ISSUE TITLE
Failed transactions trigger multipleResolves

### ISSUE THREAD

**Issue by leppaott** [prisma/prisma#11740]
### Bug description

We have prisma transactions running sequentially which fail and the try-catch logs the error.

```
try {
  await prisma.$transaction([multipleSequential]));
 } catch (error) {
 }
```

But as we listen to the event multipleResolves on node:
`process.on('multipleResolves', (type, promise, reason) => {
  console.error(type, promise, reason);
  setImmediate(() => process.exit(1));
});`

We also log for each transaction:
```
Multiple resolves. Type: reject Promise: Promise {
<rejected> PrismaClientKnownRequestError: 
Invalid `prisma.prismaNode.createMany()` invocation:
Unique constraint failed on the fields:
```

Is this a bug or why these are multiple times rejected?

### How to reproduce

Listen to https://nodejs.org/api/process.html#event-multipleresolves when transactions fail.

### Expected behavior

Expect no logging on multipleResolves but only the log inside try-catch for the transaction.

### Environment & setup

- OS: Fedora
- Database: PostgreSQL
- Node.js version: v16.13.2

### Prisma Version

also 3.9.2

**Comment by janpio** [comment]
Just to pinpoint: Is it correct that you are _not_ using the preview feature `interactiveTransactions` right now?

**Comment by leppaott** [comment]
@janpio correct. This was without the preview feature.

**Comment by millsp** [comment]
I am able to reproduce this on 3.9.2. I cannot reproduce this anymore on 4.3.0, but I found something else: the process exits without giving any error if you have the same query more than once in that array, I suspect that a promise-like is causing this.

**Comment by millsp** [comment]
Internal conversation https://prisma-company.slack.com/archives/C040N0UADF0/p1663110820780399
