### ISSUE TITLE
`findMany` stalls indefinitely

### ISSUE THREAD

**Issue by elie222** [prisma/prisma#11752]
### Bug description

We have a query that stalls indefinitely:
`await prisma.token.findMany({ take: 1, where: { collectionId: 2 } });`

All these queries work fine:
`await prisma.token.findMany({ take: 1, where: { collectionId: 1 } });`
`await prisma.token.findMany({ where: { collectionId: 2 } });`
`await prisma.token.findFirst({ where: { collectionId: 2 } });`
And this only happens with a production database.
Running the same query via DataGrip worked fine too.

In Prisma logs I see: DEALLOCATE ALL and then no more logs after that.

### How to reproduce

Steps described above.

### Expected behavior

I expect the query not to stall.

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v16.9.1

### Prisma Version

```
prisma                  : 3.9.2
@prisma/client          : 3.9.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by janpio** [comment]
Can you please post your complete logs?
Did this query work before in an older version of Prisma?

**Comment by elie222** [comment]
I don't know about previous versions of prisma. The bug is no longer present. Went away on its own after a few hours.
Seems like it had something to do with our database. But making the raw query in DataGrip worked just fine. We have called `token.findMany` many times in the past. First time ever encountering an error.

If it happens again I'll try running the same query with `prisma.$rawQuery`.
