### ISSUE TITLE
Improve binary downloading/distribution

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1176]
Current possible problems:

1. ~Hardcoded S3 URL~
2. No fallback when server unavailable
3. ~No CDN geolocation thing~
4. ~No alternative download location:~ https://github.com/prisma/prisma2/issues/1333

Notes:
off-site DA for S3, GH releases, CNAME

**Comment by pantharshit00** [comment]
I think GH releases should be a good option here. Many projects like election use it for binary distribution: https://github.com/electron/electron/releases

Also, you can get download stats using it:
![image](https://user-images.githubusercontent.com/22195362/71104810-6b9d0700-21e2-11ea-8e2b-55d8ac4b4816.png)

(these are enabled by refined github but you can also get them via API)

**Comment by pantharshit00** [comment]
Electron also has a package for this that we can use as an inspiration: https://github.com/electron/get

**Comment by timsuchanek** [comment]
Most of these problems are now tackled with https://github.com/prisma/prisma2/issues/1593
- We're using `binaries.prisma.sh`
- It's a CloudFront distribution in front of the S3 bucket

**Comment by Jolg42** [comment]
@janpio Maybe this can be closed.

We have this open https://github.com/prisma/prisma/issues/1841

**Comment by janpio** [comment]
> * No fallback when server unavailable

We should split this out into a separate issue as well, as that is currently a single point of failure. When that exists, we can close this for sure.

**Comment by janpio** [comment]
We now have fallback via DNS 🥳
