### ISSUE TITLE
@id @unique on id error should be highlighted when creating schemas  and db push should fail

### ISSUE THREAD

**Issue by borngraced** [prisma/prisma#11779]
### Bug description

I noticed Prisma doesn't reject or complain for error `"@unique": Fields that are marked as id should not have an additional"` until when the schema has been pushed to db then error would pop out in Prisma studio.
I think this can improved by letting developer know before hand!

### How to reproduce

example:

``` 
  model Payment {
  paymentId String   @id @unique
  date      DateTime @default(now())
  amount    Int
  success   Boolean  @default(true)
  order     Order[] 
                 }
```

with the schema, prisma db push is a success instead of failing because paymentId field has @id and @unique

### Expected behavior

Prisma should report this error "@unique": Fields that are marked as id should not have an additional" before prisma db push can be successful

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.16.1

### Prisma Version

```
prisma                  : 3.9.2
@prisma/client          : 3.9.2
```

**Comment by janpio** [comment]
Where are you getting that `"@unique": Fields that are marked as id should not have an additional"` error? For me I can successfully migration this schema and then open it in Prisma Studio via `npx prisma studio` and write data to that table:

```prisma
model Payment {
  paymentId String   @id @unique
  date      DateTime @default(now())
  amount    Int
  success   Boolean  @default(true)
}
```

**Comment by janpio** [comment]
Ping @borngraced

**Comment by borngraced** [comment]
Ok...sorry, I've been away.  I'm going to try to reproduce the error and share!

**Comment by janpio** [comment]
`Fields that are marked as id should not have an additional @unique` is not part of our codebase anymore, so we can close this issue. You probably had different versions running locally in some way, which meant that Studio used an older validation than the rest of the tooling.
