### ISSUE TITLE
Consider a repo consolidation - prisma-framework

### ISSUE THREAD

**Issue by ctrlplusb** [prisma/prisma#1178]
As discussed on Slack it can be difficult to navigate / establish where an issue belongs. There are so many repos which together encapsulate the Prisma Framework. I have seen issues that have cross cutting concerns too.

It would be great if you would consider creating a monorepo to consolidate all the repos.

https://github.com/prisma/prisma-framework

```
|-
| |- packages
| |  |- photon
| |  |- lift
| |  |- studio
| |
| |- specs
|
```

**Comment by janpio** [comment]
All issues can live in `prisma/prisma` in the meantime, only sometimes we move very specific things to `prisma/migrate` or `prisma/prisma-client-js`.
