### ISSUE TITLE
Docker with `pnpm install` hangs on `@prisma/client` postinstall 

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#11791]
### Bug description

See https://github.com/pnpm/pnpm/discussions/4329 and below

### How to reproduce

Create an empty directory with a `Dockerfile`
```
FROM node:16

WORKDIR /usr/src/app

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

RUN pnpm init -y

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store\
    pnpm add @prisma/client

CMD ["echo", "end"]
```

Run `docker build . --progress=plain --no-cache`

### Expected behavior

It should produce a Docker build.

### Environment & setup

pnpm 6.30.1

**Comment by Jolg42** [comment]
Workaround 

Set `ENV PRISMA_SKIP_POSTINSTALL_GENERATE=true` in the Dockerfile

Or a different target (seems that any value works there)
```
RUN --mount=type=cache,id=pnpm-virtual,target=doesnoexists \
    pnpm add @prisma/client
```

**Comment by anthonyshew** [comment]
I have this today with:
- prisma: 4.0.0
- pnpm: 7.25.1
- macOS

Possibly notable, I'm in a monorepo with an `.npmrc` of:
```
public-hoist-pattern[]=*prisma*
auto-install-peers=true
legacy-peer-deps=true
node-linker=hoisted
```

**Comment by grmkris** [comment]
same here

**Comment by millsp** [comment]
Hey folks, we have just improved our `pnpm` detection logic to fix this issue, and we will release this in our `4.13.0` release. That said, you can try it now by installing our `dev` version. `npm install prisma@dev`. Feedback welcome!

**Comment by gamedevsam** [comment]
Humm, still happening to me with `@prisma/client@4.15.0`.

Setting `ENV PRISMA_SKIP_POSTINSTALL_GENERATE=true` allowed me to work around the issue for now.

**Comment by WesleyYue** [comment]
For anyone else googling this issue that isn't pnpm. My post-install was getting stuck because I had @prisma/generator-helper with a mismatched version to the other prisma packages.

**Comment by erlangparasu** [comment]
`npm install` also hangs. `ENV PRISMA_SKIP_POSTINSTALL_GENERATE=true` does not works for me.

**Comment by millsp** [comment]
@gamedevsam @WesleyYue @erlangparasu please create a new issue with some reproduction steps. Also, you can try to debug by setting an environment variable before hand `DEBUG="prisma:*"`, this could give us valuable information.

**Comment by StinsonZhao** [comment]
![CleanShot 2023-12-09 at 01 11 20@2x](https://github.com/prisma/prisma/assets/6703905/f82de6ce-f0da-4089-8b72-5bd04709feca)

When I uncheck “Use Rosetta for x86/amd64 emulation on Apple Silicon” in my docker settings. It works!

**Comment by anzal1** [comment]
The main issue here is that the post-install script `(prisma generate)` blocks the installation
## What worked for me : 
```yml

FROM node:16

ARG DATABASE_URL

WORKDIR /app

COPY . .

# Install app dependencies

RUN yarn install  --ignore-scripts
RUN npx prisma generate
RUN yarn build
RUN apt-get install chromium -y
RUN apt-get install libreoffice -y


EXPOSE 8000
ENV PORT 8000

CMD [ "yarn", "start:prod" ]

```

**Comment by divyenduz** [comment]
> When I uncheck “Use Rosetta for x86/amd64 emulation on Apple Silicon” in my docker settings. It works!

Can confirm that this works
