### ISSUE TITLE
MongoDB type inference mismatch

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11808]
Via: https://github.com/prisma/introspection-ci/commit/99f4b38a6f71f338016542c1abab2d4ca8f1f695

The mismatch in names of the comment and the chosen type is a bit unfortunate:

```
/// Multiple data types found: String: 0.1%, Double: 99.9% out of 1000 sampled entries
rating Float
```
Double vs. Float

```
/// Multiple data types found: String: 0.1%, Int32: 99.9% out of 1000 sampled entries
votes  Int
```
Int vs. Int32

TODO: Can this be improved? Why are these different?  What makes sense?

**Comment by pimeys** [comment]
They are taken from the MongoDB data types. Mongo says it's Double, and they have separate Int32 and Int64 values. Therefore we output what exact types we see in the database...

**Comment by janpio** [comment]
This got fixed.
