### ISSUE TITLE
Unable to insert Buffer into Bytes pg field using $executeRaw

### ISSUE THREAD

**Issue by macrael** [prisma/prisma#11834]
### Bug description

We have a Bytes field in our Prisma schema and we are trying to write a raw query to do a two part query without needing a transaction. With a simple query that looks like this:

```typescript
const testBuffer = Buffer.from([1, 2, 3, 4, 5])
await prisma.$executeRaw`INSERT INTO "TestRecord" (name, "binData") 
                                            VALUES (${sessionName}, ${testBuffer})`
```
our testBuffer is not being encoded as bytea of [1, 2, 3, 4] but instead a base64 encoding of the testBuffer object is written: `{"type":"Buffer","data":[1,2,3,4,5]}` This comes out completely wrong. 

If you use the engine and a `.create({data: {...}})` the buffer is saved correctly, but not in rawQuery.

I understand from other issues like https://github.com/prisma/prisma/issues/4569 that it's expected that $queryRaw will return a base64 encoding of the data, but my issue is that I cannot figure out how to get it to write the data correctly. If I base64 encode the bytes before insertion then $queryRaw will store the base64 encoded version of _that_ base64 encoded string. 

### How to reproduce

I made a repro repo: https://github.com/macrael/prismaBinaryInsert

Should be pretty straightforward to reproduce this issue locally. 

This repo has the different things I've tried to make this work. Even $executeRawUnsafe exhibits this behavior. 

I tried passing some type parameters to $queryRaw but I think that only affects the return type, I couldn't figure out any way to influence how the query parser parsed my input variables. 

### Expected behavior

I expect that a binary field will correctly store a Bytes object in the database as a bytea. I even expect that it will come back to me as Bytes but for now I just want a way to write it reliably.

### Prisma information

Here's the Prisma schema for the example repo above:

```
// datasource requires a url. we override this with connection
// details from secrets manager in the application
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

// A model is required for prisma. Dummy model for our testing.
model TestRecord {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  name String
  binData Bytes
}
```

and some queries
```
    await prisma.$executeRaw`INSERT INTO "TestRecord" (name, "binData") 
                                            VALUES (${sessionName + '-raw'}, ${testBuffer})`
    // this encodes in base64 the string: `{"type":"Buffer","data":[1,2,3,4,5]}`

    await prisma.$executeRaw`INSERT INTO "TestRecord" (name, "binData") 
                                            VALUES (${sessionName + '-rawBase64'}, ${testBufferBase64})`
    // this encodes in base64, the base64 string.

    await prisma.$executeRawUnsafe(
        'INSERT INTO "TestRecord" (name, "binData") VALUES ($1, $2)',
        sessionName + '-rawUnsafe',
        testBuffer,
    )
    // this does the exact same as -raw.
```

### Environment & setup

- OS: MacOS
- Database: Postgres
- Node.js version: 14.17.6

### Prisma Version

```
prisma                  : 3.5.0
@prisma/client          : 3.6.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at ../../node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at ../../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at ../../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at ../../node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0

```

**Comment by macrael** [comment]
Let me know if there's any more info to give that would be useful, this bug is easily reproducible with the code I attached. I'm not sure where to even look at the code in the engine that might give me a pointer into how to do this myself.

**Comment by radoh** [comment]
I have a similar issue where I am simply unable to pass bytea / `Buffer` parameter to a `$queryRaw()` as prisma does some weird parameter processing. I've written down my findings in Stackoverflow question - https://stackoverflow.com/questions/71562794/bytea-parameter-in-a-prisma-raw-query - should I post them here as well, or create a new issue in github or is this sufficient?

**Comment by macrael** [comment]
That does look similar to this issue, to my eyes.

**Comment by Weakky** [comment]
Hey,

This issue was fixed by https://github.com/prisma/prisma-engines/pull/2847. It will be available in the next release under the `improvedQueryRaw` feature flag.

Beware that enabling `improvedQueryRaw` is a breaking change. Release notes will contain information as to how to upgrade (so will the documentation).

Thanks for reporting 🙏
