### ISSUE TITLE
MongoDB findRaw filter problem with ObjectId field.

### ISSUE THREAD

**Issue by casperibo** [prisma/prisma#11830]
### Bug description

Hi, I try to get items by its categories using findRaw method but I couldn't.

I think it's a type problem, I should write like ObjectId("categoryId");

I installed mongodb and try to use;

const catId = new ObjectId(categoryId);

$categoryId: { $eq: catId }

But It didn't work.

```
const [totalCount, items] = await Promise.all([
          ctx.prisma.store.count({ where: { isPublished: 1, categoryId } }),
          ctx.prisma.store
            .findRaw({
              filter: {
                location: {
                  $nearSphere: {
                    $geometry: {
                      type: "Point",
                      coordinates: [currentLng, currentLat],
                    },
                  },
                },
                isPublished: { $eq: 1 },
                categoryId: { $eq: categoryId }, // After I add this line, I'm getting empty array even though the category has items.
              },

              options: {
                skip: offset,
                limit: first,
              },
            })
        ]);
```

### Expected behavior

Filter items which has defined categoryId.

### Environment & setup

- OS: Mac OS
- Database: MongoDB
- Node.js version: 16.2.0

### Prisma Version

```
3.9.2
```

**Comment by matthewmueller** [comment]
Thanks @casperibo, I've confirmed this bug.

Reproduction: https://github.com/matthewmueller/prisma-issue-11830

**Comment by casperibo** [comment]
Hi @matthewmueller thank you for your interest.

I tried a few things like you said but unfortunately it didn't work.

I try to filter from MongoDb Atlas filter area and I got the result that I want.

```
{_id: ObjectId('620a7a90dd71db222fb2f371')}

{categoryId: ObjectId('620a7a32fee6919239264eb0')}
```

The schema looks like same but I saw your repository that you share, and the version doesn't have same version like my project.

**Is there any way you to try in version 3.9.2.** or Is there something I can do.

My Schema fields:
```
model Store {
...
id          String        @id @default(dbgenerated()) @map("_id") @db.ObjectId
category    StoreCategory @relation(fields: [categoryId], references: [id])
categoryId  String        @db.ObjectId()
...
}
```

```
const test = await ctx.prisma.store.findRaw({
          // filter: {
          //   _id: { $eq: new ObjectId("620a7a90dd71db222fb2f371") },
          // } as any,
          // filter: {
          //   _id: { $eq: "620a7a90dd71db222fb2f371" },
          // } as any,
          // filter: {
          //   id: { $eq: new ObjectId("620a7a90dd71db222fb2f371") },
          // } as any,
          // filter: {
          //   id: { $eq: "620a7a90dd71db222fb2f371" },
          // } as any,
          // filter: {
          //   _categoryId: { $eq: new ObjectId("620a7a32fee6919239264eb0") },
          // } as any,
          // filter: {
          //   _categoryId: { $eq: "620a7a32fee6919239264eb0" },
          // } as any,
          // filter: {
          //   categoryId: { $eq: new ObjectId("620a7a32fee6919239264eb0") },
          // } as any,
          // filter: {
          //   categoryId: { $eq: "620a7a32fee6919239264eb0" },
          // } as any,
        });

        console.log(test);
```

**Comment by millsp** [comment]
Hey @casperibo, since ids are represented with `ObjectId`s or `$oid` on the db level, you need to build your query like the following:

```ts
    const users = await prisma.user.findRaw({
        filter: {
            _id: { $eq: { $oid: "6202ec178be26d2b28adc075" } },
        },
    })
```

**Comment by millsp** [comment]
You're welcome :) Right now, I don't see any quick solution to that problem. The easiest would be for you to use middlewares to transform the returned objects to the shape you need https://www.prisma.io/docs/concepts/components/prisma-client/middleware.

**Comment by janpio** [comment]
(If you do, please share the resulting Middleware - others might benefit from it as well.)

**Comment by ghalibansari** [comment]
unable to do limit and skip in findRaw
