### ISSUE TITLE
Add Full-text search support

### ISSUE THREAD

**Issue by f2net** [prisma/prisma#1183]
I think it would be useful to have a way to do full-text search without using external services such as Algolia.

In a first step, it could be useful to have a "q" parameter which executes a "LIKE" query on all the fields of an entity (instead of doing OR(contains, contains, contains...).

Then it would be great to have real full-text search, configurable via the .yml file (which entities and fields to index) and have something like a "s" parameter which does the full-text query over the indexed fields, maybe using the Elastic Search service of AWS.

Thank you,
Matteo

**Comment by FluorescentHallucinogen** [comment]
Any progress?

**Comment by woss** [comment]
this is crazy, so old issue, so important issue, so little interest!

**Comment by Bartjuh4** [comment]
For our project we are also in a desperate need for full text search. Please implement this!

**Comment by jvlobo** [comment]
Any news on this??? 😞

**Comment by jvlobo** [comment]
Nothing?

**Comment by AndreiBacescu** [comment]
> For our project we are also in a desperate need for full text search. Please implement this!

Hi! You can use a custom sql: https://www.prisma.io/forum/t/how-to-use-custom-sql/3653

**Comment by nagman** [comment]
What can we do to help implement this really really needed feature?

**Comment by nagman** [comment]
Actually, we could implement something similar to `@id`, `@createdAt`, `@updatedAt`, and so forth.

It could be something like `@searchable` or `@searchIndex` or I don't know, with properties like `fields` and `separator`.

And by adding it to a field, prisma would automatically concatenate the given fields into one lowercased and unaccentuated string.

Then we could do a simple `field_contains` on this field.

The principle is not to be able to edit this field as it is automatically handled by prisma.

Simpler than implementing a whole full-text search support, which would take longer to execute.

What do you think?

**Comment by indreklasn** [comment]
+1

**Comment by Renaud009** [comment]
Any improvment on this? Is this planned to be supported anytime soon or not?

**Comment by zingerj** [comment]
Any plans to support this anytime soon? If not, are there any workarounds?

**Comment by yenicelik** [comment]
lol, 3 years? xD
