### ISSUE TITLE
Sensitive Data Leak

### ISSUE THREAD

**Issue by Steiner-254** [prisma/prisma#11844]
Hello, Please check out on the sensitive data leaked in the link: https://github.com/WinKoKoNaing/rms-admin/blob/cfec7a4d0de8bdacc4cfa77c09b8b53e49a2ea4b/.env.

DATABASE_URL=postgres://...
GOOGLE_CLIENT_ID="42475...om"
GOOGLE_CLIENT_SECRET="GO...WVd"

 Thanks, Regards Alvin Mwambi (@Steiner254)

**Comment by janpio** [comment]
I will try to make @WinKoKoNaing aware of this. Thanks for the report (which I edited and removed the history to not repeat these credentials here once more).

**Comment by Steiner-254** [comment]
Awesome :)
