### ISSUE TITLE
Confirm Azure CosmosDB for MongoDB support via the MongoDB connector

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11854]
[Azure Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/introduction) is a NoSQL database that also provides a [MongoDB wire protocol compatible API](https://docs.microsoft.com/en-us/azure/cosmos-db/choose-api#api-for-mongodb).

In theory supporting this in Prisma might be as simple as using the `mongodb` provider.

Obviously we will only really know after running our full test suite. As we learned in the past, running that against a Cloud service is not the best idea (as it takes aaaages because of the communication overhead). Cosmos DB offers a local emulator as a workaround for that, but it unfortunately is only available in a stable version for Windows, not Linux:

https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator?tabs=ssl-netstd21
https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21
https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator-on-docker-windows?tabs=cli

Via GitHub Actions we should be able to "simply" run these tests against an emulator on a Windows image.

**Comment by janpio** [comment]
From manual testing:

Seems that `deleteMany` fails for non existing databases and collections on Azure CosmosDB (which it does not for MongoDB):


```
$ ts-node ./script.ts
PrismaClientUnknownRequestError: 
Invalid `client.user.deleteMany()` invocation in
/home/runner/work/e2e-tests/e2e-tests/databases/mongodb-azure-cosmosdb/script.ts:7:21

   4 
   5 // A `main` function so that we can use async/await
   6 async function main() {
→  7   await client.user.deleteMany(
  Error in connector: Database error. error code: unknown, error message: Command failed (NamespaceNotFound): Database not found 'e2e-tests'.)
    at cb (/home/runner/work/e2e-tests/e2e-tests/databases/mongodb-azure-cosmosdb/node_modules/@prisma/client/runtime/index.js:39807:17) {
  clientVersion: '3.10.0-dev.49'
}
```

```
$ ts-node ./script.ts
PrismaClientUnknownRequestError: 
Invalid `client.user.deleteMany()` invocation in
/home/runner/work/e2e-tests/e2e-tests/databases/mongodb-azure-cosmosdb/script.ts:7:21

   4 
   5 // A `main` function so that we can use async/await
   6 async function main() {
→  7   await client.user.deleteMany(
  Error in connector: Database error. error code: unknown, error message: Command failed (NamespaceNotFound): Collection not found 'User'.)
    at cb (/home/runner/work/e2e-tests/e2e-tests/databases/mongodb-azure-cosmosdb/node_modules/@prisma/client/runtime/index.js:39807:17) {
  clientVersion: '3.10.0-dev.49'
}
```

**Comment by janpio** [comment]
And now a third GitHub action exists: https://github.com/janpio/azure-cosmos-db-emulator-github-action (Adds the ability to tart the emulator in MongoDB mode, and with a specific MongoDB API version)

That is used in the e2e test: https://github.com/prisma/e2e-tests/tree/dev/databases-windows/mongodb-azure-cosmosdb-emulator. It shows that talking to the emulator generally works.

Additional there is an e2e test talking to a Cloud Cosmos DB via the MongoDB API: https://github.com/prisma/e2e-tests/tree/dev/databases/mongodb-azure-cosmosdb

The differences between plain MongoDB and Azure Cosmos DB for MongoDB (emulator) that were discovered along the way are now tracked in https://github.com/prisma/prisma/issues/11921

Next step: Engines tests on Windows with this emulator.

**Comment by Jolg42** [comment]
The current test now fails, see https://github.com/prisma/prisma/issues/15083

**Comment by janpio** [comment]
Could not confirm, further attemps via other issues.
