### ISSUE TITLE
Unable to connect to local MongoDB (configured with replicaset)

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#11860]
### Bug description

I just ran into the following error while trying to setup a local MongoDB with replication (from [this comment](https://github.com/prisma/prisma/issues/8266#issuecomment-1013138234))

```
Prisma schema loaded from prisma/schema.prisma
Environment variables loaded from .env
Datasource "db"

Introspecting based on datasource defined in prisma/schema.prisma …

Error: Error in connector: Error querying the database: Server selection timeout: None of the available servers suitable for criteria Predicate. Topology: { Type: Unknown, Servers: [ { Address: localhost:27017, Type: RsGhost, Average RTT: 346.567µs, Last Update Time: DateTime(2022-02-16T20:00:59.552Z), Max Wire Version: 9, Min Wire Version: 0 }, ] }
```

Oddly, it works fine with TablePlus, but not with Prisma.

---

Steps to reproduce (OSX):

### How to reproduce

1. `brew install mongodb-community`
2. `vi /usr/local/etc/mongod.conf`
3. Add replication config in comment above
4. `brew services start mongodb-community`

Then, Create a new Prisma project, with the following:

**.env**

```
DATABASE_URL="mongodb://localhost:27017/mongo"
```

**prisma/schema.prisma**

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}
```

Lastly, run `npx prisma db pull`. After some time you should see:

```
Prisma schema loaded from prisma/schema.prisma
Environment variables loaded from .env
Datasource "db"

Introspecting based on datasource defined in prisma/schema.prisma …

Error: Error in connector: Error querying the database: Server selection timeout: None of the available servers suitable for criteria Predicate. Topology: { Type: Unknown, Servers: [ { Address: localhost:27017, Type: RsGhost, Average RTT: 346.567µs, Last Update Time: DateTime(2022-02-16T20:00:59.552Z), Max Wire Version: 9, Min Wire Version: 0 }, ] }
```

Then if you try TablePlus with the same connection string, it should work as expected.

### Expected behavior

It should connect in the same way it connects to TablePlus and pull existing collections.

### Environment & setup

- OS: OSX
- Database: MongoDB
- Node.js version: v14.18.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.10.0-dev.50
@prisma/client          : Not found
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 1e2a986858a8bc0ad185ac8baf19fb72b382b7ec (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 1e2a986858a8bc0ad185ac8baf19fb72b382b7ec (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 1e2a986858a8bc0ad185ac8baf19fb72b382b7ec (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 1e2a986858a8bc0ad185ac8baf19fb72b382b7ec (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 1e2a986858a8bc0ad185ac8baf19fb72b382b7ec
Studio                  : 0.458.0
```

**Comment by matthewmueller** [comment]
Marked it as a **Must Have** because:

1. We should offer a way to develop against MongoDB locally, not just with Atlas
2. It's a connection string that works in other places, it's annoying when the same connection string doesn't work with Prisma.

**Comment by matthewmueller** [comment]
Related issue [Improve error message on connection error Server selection timeout](https://github.com/prisma/prisma/issues/8966).

If there are still cases where this error can happen, even after fixing this issue, we should do a quick pass over the error message to make it more descriptive.

**Comment by Jolg42** [comment]
I can also reproduce this using our docker-compose setup on my local machine 
https://github.com/prisma/prisma/blob/main/docker/docker-compose.yml

With
```prisma
datasource db {
  provider = "mongodb"
  // note that the params authSource or retryWrites=true&w=majority don't affect the result.
  url      = "mongodb://root:prisma@localhost:27018/tests?authSource=admin"
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}
```

```
npx prisma db pull
Prisma schema loaded from prisma/schema.prisma
Datasource "db"

Introspecting based on datasource defined in prisma/schema.prisma …

Error: Error in connector: Error querying the database: Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: localhost:27018, Type: Unknown, Error: Connection refused (os error 61) }, ] }
```

**Comment by matthewmueller** [comment]
Yah, I know it works with the local Docker setup, but that requires our users to have Docker installed and understand how to use Docker Compose. 

I'd like us to also support: 

1. You get `mongod` on your machine *somehow*
2. You edit mongod.conf to configure the replica set
3. You try connecting with prisma

**Comment by janpio** [comment]
(Let's keep the issue unconfirmed until someone else could use the explicit reproduction steps to see the same error message. Can you take another look maybe @Jolg42?)

**Comment by Jolg42** [comment]
I could reproduce but I don't think it's a bug actually, but misconfiguration of the replica set, which needs to be initialized.

I could "connect" with TablePlus but found an empty view and MongoDB support there is in Beta (so buggy behavior?).
Using Robo 3T which I think is a better tool (solid and proven) for that, the connection would not work.

Also, the logs at `/usr/local/var/log/mongodb/mongo.log` show many entries with 
```
{"t":{"$date":"2022-02-18T15:03:32.828+01:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":8800}}
```

I could make it work by initiating the replica set with the additional commands:
- `mongo` opens a mongo shell
- `rs.initiate({_id: "rs0", members: [{_id: 0, host: "127.0.0.1:27017"}] })`
- optionally check on the status with `rs.status()`

After that `npx prisma db pull` will show
```
Prisma schema loaded from prisma/schema.prisma
Datasource "db"

Introspecting based on datasource defined in prisma/schema.prisma …
Error: 
P4001 The introspected database was empty: 

prisma db pull could not create any models in your schema.prisma file and you will not be able to generate Prisma Client with the prisma generate command.

To fix this, you have two options:

- manually create a table in your database.
- make sure the database connection URL inside the datasource block in schema.prisma points to a database that is not empty (it must contain at least one table).

Then you can run prisma db pull again. 
```

**Comment by Jolg42** [comment]
Note from a MongoDB person that `rs.initiate()` without parameters should also work.

**Comment by janpio** [comment]
Open a new issue of discussion about your problemt then please @marr

**Comment by HuakunShen** [comment]
Is there any update on deploying a local mongodb replica set that works with Prisma?

I still couldn't do it with docker.

**Comment by TongChia** [comment]
> 

https://github.com/prisma/prisma/issues/11860#issuecomment-1044695589
