### ISSUE TITLE
`The provided database string is invalid. Unable to parse URL. in database URL.` on invalid (?) connection string

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11883]
Something in this connection string seems to be weird, but the error message also does not make sense:

Connection string:
```
mongodb://localhost:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==@localhost:10255/e2e-tests?ssl=true
```

Error message:
```
D:\a\e2e-tests\e2e-tests\databases-windows\mongodb-azure-cosmosdb-emulator\script.ts:7:21

   4 
   5 // A `main` function so that we can use async/await
   6 async function main() {
→  7   await client.user.deleteMany(
  The provided database string is invalid. Unable to parse URL. in database URL. Please refer to the documentation in [prisma.io/docs/reference/database-reference/connection-urls](https://www.prisma.io/docs/reference/database-reference/connection-urls) for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.
    at cb (D:\a\e2e-tests\e2e-tests\databases-windows\mongodb-azure-cosmosdb-emulator\node_modules\@prisma\client\runtime\index.js:39809:17) {
  clientVersion: '3.10.0-dev.54',
  errorCode: undefined
}
```

**Comment by janpio** [comment]
Same grammar is present in other error messages around connection string: https://github.com/prisma/prisma/issues/11684

**Comment by matthewmueller** [comment]
Looks like the slashes in the password are the culprit. I'm tempted to close this since it's not a valid URL and the error message says that.

Looks like it's base64 encoded which can produce invalid URLs: https://en.wikipedia.org/wiki/Base64#The_URL_applications

Where did you get this URL?

**Comment by janpio** [comment]
It is the default connection string of Azure CosmosDB Emulator MongoDB API. It also needs to be escaped in the Mongo Node Client, so us needing that is fine I guess.

But that means we definitely need to update this message here which the error message links to: https://www.prisma.io/docs/reference/database-reference/connection-urls#special-characters

Also there is something weird going on in the error message: `Unable to parse URL. in database URL. `. That sentence looks broken to me.

**Comment by janpio** [comment]
https://github.com/prisma/docs/issues/3002

**Comment by stevemu** [comment]
for me, I had to define the "authentication database" to make it work, so:

this didn't work (in .env):
```
DATABASE_URL="mongodb+srv://user:password@prod.abc.mongodb.net/?retryWrites=true&w=majority"
```

this works:

```
DATABASE_URL="mongodb+srv://user:password@prod.abc.mongodb.net/my-db?retryWrites=true&w=majority"
```

**Comment by grantjayy** [comment]
@stevemu This worked for me - thank you for this

**Comment by janpio** [comment]
Please open a new bug report if you are still getting this issue and think you should not. Thanks.

**Comment by trishan9** [comment]
in my case, it was missing query value, I added `?connect_timeout `at end of url but forget to add value to it, Adding value to` ?connect_timeout` by doing `?connect_timeout=300`, it was resolved.

**Comment by LibenHailu** [comment]
Stop the server close all the traminal and on a new terminal run npx prisma mirgate dev or npx prisma db push

**Comment by AgileDisruptor** [comment]
This error also occurs even if your url is correct, but your directUrl has a mistake. It would be nice if the error message specified which field was incorrect.

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}
