### ISSUE TITLE
Confirm sharded MongoDB connection string is supported by MongoDB Rust Driver

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11899]
MongoDB has a specific connection string format for sharded setups which lists the hosts explicitly: `mongodb://user:password@my-shard-00.atlas.mongodb.net:27017,my-shard-01.atlas.mongodb.net:27017,my-shard-02.atlas.mongodb.net:27017/database?ssl=true&replicaSet=atlas-xxxxx-shard-0&authSource=admin&retryWrites=true` 

Although this is not super common, it is part of the MongoDB specification:

`mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]`

(via [Standard Connection String Format](https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format))

(The listing of the individual hosts can be avoided by using the "[DNS Seed List Connection Format](https://docs.mongodb.com/manual/reference/connection-string/#dns-seed-list-connection-format)", which uses `mongodb+srv://` instead and then executes some logic to get the individual hosts)

Currently you can not use Prisma with this format because of #11873

But that leaves the question open if, when #11873 is solved, this would actually work with the MongoDB Rust driver or if they also do not support this connection string format. We should confirm that, possibly before doing the work for #11873.

**Comment by pimeys** [comment]
Yes it works.

**Comment by janpio** [comment]
It is and works now.
