### ISSUE TITLE
Disable interactive transactions when using the Data Proxy

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#11913]
## Problem

Interactive transactions doesn’t work with the proxy and triggers errors. We are preventing these errors right now by detecting that both preview feature flags dataproxy and iTX are enabled and preventing generation. If this is promoted to GA and the flag is removed we might lose the ability to detect this is enabled?

## Next Steps

- [x] Discuss solution
- [ ] Decide on a solution in this [internal document](https://www.notion.so/prismaio/Interactive-Transactions-Data-Proxy-d08ab9b5eb5642c28a36999f823c945e?d=aa586cb60fe74efca986b393137c1043#c2036a2e5608477c9080b3a7f2af0236)

## Additional context

Internal discussion: https://prisma-company.slack.com/archives/C02FZENHD4N/p1645200596753649

**Comment by albertoperdomo** [comment]
I think this is a good solution. We are available for questions or to chat about this.

**Comment by tanberry** [comment]
Do you all agree this warrants mention in the Docs? Maybe just an admonition in the pages about ITX, to let people know that if they enable data proxy as a preview feature, then itx is automatically disabled? @albertoperdomo @matthewmueller

**Comment by matthewmueller** [comment]
We're still working on the design of this in this [internal document](https://www.notion.so/prismaio/Interactive-Transactions-Data-Proxy-d08ab9b5eb5642c28a36999f823c945e?d=aa586cb60fe74efca986b393137c1043#c2036a2e5608477c9080b3a7f2af0236).

It seems like we're settling on either 3.2 or 4.

**Comment by garrensmith** [comment]
I'm closing this since we have decided to not to implement it this way.
