### ISSUE TITLE
prisma optional fields are not optional

### ISSUE THREAD

**Issue by dcsan** [prisma/prisma#11927]
### Bug description

created a schema with some optional fields:

```
model Player {
    id        Int     @id @default(autoincrement())
    name      String?
    discordId String?
    px        Float?  @default(0)
    py        Float?  @default(0)
}
```

```
// create a method that takes an instance of the generated object
import { Prisma, PrismaClient, Player } from '@prisma/client'
static async findOrCreate(query: Player):  { ... } 

// and try to call it
const p = await CPlayer.findOrCreate({ name: 'alice' })
```

but the "optional" properties are actually required:

```
Argument of type '{ name: string; }' is not assignable to parameter of type 'Player'.
  Type '{ name: string; }' is missing the following properties from type 'Player': id, discordId, px, py
```

looking into the generated definitions the fields are null values are ok
but they are still *required* params.

```
export type Player = {
  id: number
  name: string | null
  discordId: string | null
  px: number | null
  py: number | null
}
```

so this means I can't really use optional params, all code has to define ALL possible properties.

### How to reproduce

create the functions as above.

### Expected behavior

a way to use truly optional params/properties in prisma objects

### Prisma information

```
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}

model Player {
    id        Int     @id @default(autoincrement())
    name      String?
    discordId String?
    px        Float?  @default(0)
    py        Float?  @default(0)

    // fish      PlayerFish[]
    // playerFish PlayerFish[]
}
```

### Environment & setup

macOS

this affects all versions

### Prisma Version

```
prisma                  : 3.9.2
@prisma/client          : 3.9.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by dcsan** [comment]
maybe I can use some other auto-generated type from the 1000s of lines of automagically generated code?

there's a `PlayerSelect` and `PlayerCreateArgs` defined, 
but somehow exported within the PrismaClient class in such a way I can't import. 

Any hints on how to get at them?

```
    /**
     * Player create
     */
    export type PlayerCreateArgs = {
```

and yet

`Module '"@prisma/client"' has no exported member 'PlayerSelect'.`

**Comment by dcsan** [comment]
this is even more of a headscratcher since `id` cannot be null, so you have to pass IDs to the create function, not let them auto-increment... >.<

**Comment by O4epegb** [comment]
```
import { Prisma } from '@prisma/client';

// then use like Prisma.PlayerCreateArgs
```

**Comment by dcsan** [comment]
Thanks for the hint @O4epegb 


```ts
    static async findOrCreate(query: Prisma.PlayerCreateArgs): Promise<CPlayer> {
        let data = await prisma.player.findFirst({ where: query })
```
> Type 'PlayerCreateArgs' has no properties in common with type 'PlayerWhereInput'.ts(2559)

so let's change the incoming param type, but then we have to do a hacky cast to create:

```ts
    static async findOrCreate(query: Prisma.PlayerWhereInput): Promise<CPlayer> {
        let data = await prisma.player.findFirst({ where: query })
        if (!data) {
            const input = query as Prisma.PlayerCreateInput
            data = await prisma.player.create({ data: query })
        }
        return new CPlayer(data)
    }
```

So that basically works. However, the prisma object is encapsulated, so none of the finder etc methods are exposed on the CPlayer class.


so final wrapper class looks like

```ts

export class CPlayer {
    data?: Player | null

    constructor(data?: Player | null) {
        this.data = data
    }

    static async findOrCreate(query: Prisma.PlayerWhereInput): Promise<CPlayer> {
        let data = await prisma.player.findFirst({ where: query })
        if (!data) {
            const input = query as Prisma.PlayerCreateInput
            data = await prisma.player.create({ data: input })
        }
        // construct object and return instance
        return new CPlayer(data)
    }

    // move a player
    async moveTo(px: number, py: number) {
        this.data = await prisma.player.update({
            where: { id: this.data!.id },
            data: { px, py },
        })
        console.log('new data', this.data)
    }

}
```

**Comment by O4epegb** [comment]
Do you have any more issues with Prisma client? If not, please close this one and or move it to the discussion section

**Comment by dcsan** [comment]
thought I'd give prisma a go a year later, hoping it was a bit more functional. 
And I found my own issue on searching for this problem.

is there still really no solution to optional fields?
schema:

```
model Auction {
  id          Int       @id @default(autoincrement())
  createdAt   DateTime? @default(now())
  name        String    @db.VarChar(255)
  lastBid     Int       @db.Int
  description String?
}
```

note `  description String?`

this generates a type of `    description: string | null; ` but it is NOT optional.

![image](https://github.com/prisma/prisma/assets/514002/27991c90-dcd9-4969-bc7e-4f44d7ba91f7)

**Comment by O4epegb** [comment]
The answer is still the same, you are probably using wrong types 😄

**Comment by davbyron** [comment]
Hi there, I'm experiencing the same issue. I can work around the problem (as @dcsan mentioned) by using `null` values when I import a type from Prisma (e.g., `import { User } from "@prisma/client"` to import the `User` table types), but it would be nice if they were truly optional.

The solution  @O4epegb suggested doesn't seem to be working for me. When I try to import `Prisma` from `@prisma/client` and try to reference my `User` table, I get the following error: `Namespace '"<my_path>/node_modules/.prisma/client/index".Prisma' has no exported member 'User'.ts(2694)`. In addition, it looks like the intent is to be able to import the model types directly from `@prisma/client`: https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#type-definitions.

**Comment by O4epegb** [comment]
> Hi there, I'm experiencing the same issue. I can work around the problem (as @dcsan mentioned) by using `null` values when I import a type from Prisma (e.g., `import { User } from "@prisma/client"` to import the `User` table types), but it would be nice if they were truly optional.

Your `User` type is what you are getting from the database, fields cannot be optional in the database, they either exist or equal null. So whatever you do with this type you are miss-using it. If you want to create a wrapper like OP you need `Prisma.UserCreateArgs` not `User`.

> The solution @O4epegb suggested doesn't seem to be working for me. When I try to import `Prisma` from `@prisma/client` and try to reference my `User` table, I get the following error: `Namespace '"<my_path>/node_modules/.prisma/client/index".Prisma' has no exported member 'User'.ts(2694)`. In addition, it looks like the intent is to be able to import the model types directly from `@prisma/client`: https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#type-definitions.

Of course you are, because db type is exported without a namespace, just as a named export. But it won't work for you, see my first point.

**Comment by davbyron** [comment]
Thanks for the help, @O4epegb. `Prisma.UserCreateArgs` was what I was looking for.

If anyone else ventures here have a look at Prisma's docs on generated types: https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety#what-are-generated-types. This is the solution to the problem that @dcsan and I were having.

**Comment by dcsan** [comment]
@davbyron thanks for taking time to link to this, it makes sense now!

**Comment by janpio** [comment]
So you are suggesting that the `User` type that Prisma provides should also take optionality into account, which in your experience it currently does not and hence blocks your use case??

**Comment by dcsan** [comment]
From my side i think it was just lack of knowledge that the `User` prisma type doesn't echo the optional fields in the `User` schema. You have to go digging for other types based on what your DB CRUD operation is.

That's for a DB write. For DB reading, if we want to create a typed object to match on, do we need to use `UserSelectArgs` ? It seems odd to type something with `UserCreateArgs` for a `find` operation.

**Comment by davbyron** [comment]
I would echo what dcsan said. Not an issue on Prisma's part, and it doesn't block my use case, just a lack of knowledge on my part.

**Comment by dcsan** [comment]
maybe you could use [partial](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) which would make all the fields optional? maybe its to do with the confusion between a typescript optional `?` and the prisma requirement for `<type> | null; ` cos of DB requirements.

**Comment by nicolasrenon** [comment]
> maybe you could use [partial](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) which would make all the fields optional? maybe its to do with the confusion between a typescript optional `?` and the prisma requirement for `<type> | null; ` cos of DB requirements.

Thanks for your response. I don't think that would help me, I was already using `Pick<Type, Keys>`.
I ended up create different variations of the model function like `createPartialArticle()` which scope down the type checking to the only fields that are expected in the payload. That's a fair workaround.

**Comment by dcsan** [comment]
yeah i basically end up re-typing everything that is done in prisma so I can share the types with the front-end. 
It's a really tedious process and means prisma doesn't really serve the needs for full stack development if you have to do all your own typing.

**Comment by davbyron** [comment]
@nicolasrenon Have you had a look in the `node_modules/.prisma/client/index.d.ts` file? That's where you should find the type for `ArticleCreateArgs`. For example, going off of what I had previously written, in my file `UserCreateArgs` looks like this:

```
  /**
   * User create
   */
  export type UserCreateArgs<ExtArgs extends $Extensions.Args = $Extensions.DefaultArgs> = {
    /**
     * Select specific fields to fetch from the User
     */
    select?: UserSelect<ExtArgs> | null
    /**
     * Choose, which related nodes to fetch as well.
     */
    include?: UserInclude<ExtArgs> | null
    /**
     * The data needed to create a User.
     */
    data: XOR<UserCreateInput, UserUncheckedCreateInput>
  }
```

When I do `import { Prisma } from "@prisma/client"`, I am able to declare a variable using the `Prisma.UserCreateArgs` type.

**Comment by lancerace** [comment]
[O4epegb](https://github.com/O4epegb)
> fields cannot be optional in the database, they either exist or equal null.

I agree, this make sense. Look like we have to end up redeclaring the type our own.

Hopefully there is a way that is less confusing/more code readable where we could infer the type without manually creating another type. exactly what [dcsan](https://github.com/dcsan) mentioned.

After reading all the comments, attempts such as `Prisma.UserCreateArgs` look confusing to me or [partial](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) that is not the ideal approach as it make all fields optional.

**Comment by Crusader4Christ** [comment]
Guys, why don't you use `Prisma.UserCreateInput`?
@lancerace @dcsan @davbyron

**Comment by dingshaohua-com** [comment]
i give a [new issue](https://github.com/prisma/prisma/issues/27914)
