### ISSUE TITLE
Ability to reference multiple model types using a single model column

### ISSUE THREAD

**Issue by xoldyckk** [prisma/prisma#11932]
## Problem

Can prisma have a feature where we can reference a column to multiple database models inside the prisma schema?
Right now I have to create three separate like objects for each of the Post, Comment, CommentReply.

```
model PostLike{
    likedOnId   String
    likedOn    Post   @relation( fields: [ likedOnId ], references: [ id ] )
}

model CommentLike{
    likedOnId   String
    likedOn    Comment    @relation( fields: [ likedOnId ], references: [ id ] )
}

model CommentReplyLike{
    likedOnId   String
    likedOn    CommentReply    @relation( fields: [ likedOnId ], references: [ id ] )
}
```

Other way I can think of doing this would be this schema :-

```
enum LikedOn {
  POST
  COMMENT
  COMMENTREPLY
}

{
model Like{
    likedOnId   String
    type           LikedOn
}
```

But then we lose the ability to reference Post, Comment, CommentReply inside prisma client.

## Suggested solution

Like the schema below. Post, Comment, CommentReply are different models and they all have a unique identifer called
id. All three of them can be associated to a single like object.  { Post, Comment, CommentReply } means this column is 
referencing exactly these three objects.

```
{
model Like{
    likedOnId   String
    likedOn    { Post, Comment, CommentReply }   @relation( fields: [ likedOnId ], references: [ id ] )
}

```

**Comment by xoldyckk** [comment]
I guess this isn't possible to do because in SQL databases one column can only reference one kind of table.

**Comment by janpio** [comment]
Using database provided features, correct. But in theory Prisma could store the data in a different way and hence offer this functionality to you - which is why I kept it as a feature request to be looked at in the future.

**Comment by xoldyckk** [comment]
Well, I guess I should reopen the feature request.

**Comment by 1infiniteloop** [comment]
this would be useful

**Comment by Heliodex** [comment]
Also believe this would be useful

**Comment by jannisstefanis** [comment]
+1 :-)

**Comment by philosofonusus** [comment]
would be really useful

**Comment by monochrome-yeh** [comment]
same considering with mongoDB

**Comment by generic-glitch** [comment]
Currently working on a website, would definitely love this as I need some sort of thing such as a 
```
model Files {

}
```
to be able to be used with several types of models such as Users, Customers, etc.

(Users can attach documents/files to almost anything, which needs supports for several types of models)

**Comment by mcmc101001** [comment]
+1

**Comment by romanhryts** [comment]
Completely agree it would be really useful. 

For instance,  I build an API which allows to create different polls (similar with Google Forms) and there are 4 types of question user can create.  `PollTemplate` table stores a bunch of questions and instead of doing something like this:
```prisma
model PollTemplate {
  questions [ChooseOneQuestion, ChooseManyQuestion, RangeQuestion, WrittenQuestion]
}
```

I need to create a single `PollQuestion` table which contains a lot of optional fields. Moreover, if some field is not null, then some other field must be null, so there will be a plenty of `if` statements and other checks I would like to avoid.

**Comment by janpio** [comment]
Is this effectively a request for polymorphism? If so, we can close this as a duplicate as we have a popular issue for that at https://github.com/prisma/prisma/issues/1644. Do you agree?
