### ISSUE TITLE
Running Prisma on Debian Ubuntu 22.04 [dev]

### ISSUE THREAD

**Issue by nikolicstjepan** [prisma/prisma#11948]
### Bug description

Running **any** Prisma command on new Ubuntu 22.04 [dev] results in this error:

```
prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt
prisma:download file /home/stjepan/code/Spika3/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node does not exist and must be downloaded +0ms

Error: Error: Unknown binaryTarget debian-openssl-3.0.x and no custom binaries were provided
    at /home/stjepan/code/Spika3/node_modules/@prisma/engines/dist/index.js:21277:15
    at async Promise.all (index 0)
    at async /home/stjepan/code/Spika3/node_modules/@prisma/engines/dist/index.js:6621:29
```

This new version of Ubuntu uses debian-openssl-3.0.x and that seems to cause the problem.

I know that this version of Ubuntu is not officially released yet, I just want to bring this to your attention :)

### How to reproduce

Try to use any Prisma command on Ubuntu 22.04

### Prisma information

-

### Environment & setup

- OS: Ubuntu 22.04

### Prisma Version

```
v3.9.2
```

**Comment by janpio** [comment]
See https://github.com/prisma/prisma/issues/11677 and https://github.com/prisma/prisma/issues/11356

**Comment by fomenkoyegor** [comment]
так что делать менять ос?????
