### ISSUE TITLE
Kotlin client

### ISSUE THREAD

**Issue by mCzolko** [prisma/prisma#11957]
## Problem

Kotlin doesn't have many options when it comes to ORM and very nice DB migrations that Prisma has.

## Suggested solution

Have client for Kotlin language.

## Alternatives

There is a possibility to use Java ORMs but it's not leveraging Kotlin features.
Flyway is maybe the main alternative with use of Exposed (JetBrains).

## Additional context

https://flywaydb.org/
https://github.com/JetBrains/Exposed
https://www.ktorm.org/

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
