### ISSUE TITLE
`@prisma/internals` (previously @prisma/sdk) uses deprecated dependencies `uuid@3.4.0` via `temp-write 4.0.0`

### ISSUE THREAD

**Issue by valerii15298** [prisma/prisma#11960]
### Bug description

@prisma/sdk uses outdated dependency `temp-write 4.0.0` which uses deprecated `uuid@3.4.0` which is I believe inappropriate to use in modern development. Know version `temp-write 5.0.0` is available to use.

```
@prisma/sdk 3.9.2
  ├─┬ checkpoint-client 1.1.20
  │ └── uuid 8.3.2
  └─┬ temp-write 4.0.0
    └── uuid 3.4.0
```

### How to reproduce

Use pnpm as package manager(at least i used pnpm to detect it)

`pnpm init -y`
`pnpm add @prisma/sdk`

and you will see:
WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

Run `pnpm why uuid` and you will see:
```
@prisma/sdk 3.9.2
  ├─┬ checkpoint-client 1.1.20
  │ └── uuid 8.3.2
  └─┬ temp-write 4.0.0
    └── uuid 3.4.0
```

### Expected behavior

No depreciation warning and no use of deprecated packages which have problems.

### Prisma information

`@prisma/sdk`

### Environment & setup

Windows 11, `pnpm` as package manager

### Prisma Version

`3.9.2`

**Comment by Jolg42** [comment]
Unfortunately, this attached PR is blocked by 
https://github.com/prisma/prisma/issues/7618

As of today, I am not aware of any problem caused by the uuid@3.4.0 used in temp-write@4.0.0 (only the theoretical part mentioned, that it's using `Math.random()`)

**Comment by Ustice** [comment]
`temp-write` is still included as a dependency, but it looks like it is [no longer used](https://github.com/search?q=repo%3Aprisma%2Fprisma%20temp-write&type=code). If so, can it be removed?
