### ISSUE TITLE
Expand --version command

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#1196]
Currently the version command just returns the CLI version and one commit hash for the binary which is hardcoded in the package.json - not the _actual_ hash that the binary returns when asked for it.

Ideally the CLI would request the version from all the binaries version endpoints and output something like this: 

```
prisma2@2.0.0-alpha.473
All binaries are on the same commit : 9sfhshfjdhfjsdhfs....` 
```
Or in the case they differ (due to the usage of env vars to point to local binaries)

```
prisma2@2.0.0-alpha.473
The binaries are on different commits: 
 Introspection-Engine : 9fadsfsdfsdf...
 Query-Engine : 5j245h45kk2hhgfsfsdf...
 Migration-Engine : 92047254hsfs7s8fs02f...
```

**Comment by timsuchanek** [comment]
In addition, we should adjust the `--version` command, to take into account, if an engine override env var is present.
If you e.g. provide `PRISMA_QUERY_ENGINE_BINARY`, the `--version` command should print information about the binary that is targeted by that env var, instead of just printing the shipped binary.

**Comment by timsuchanek** [comment]
Relevant https://github.com/prisma/prisma-engines/issues/521

**Comment by timsuchanek** [comment]
The new output will look as follows:
```
Prisma CLI Version   : prisma2@2.0.0-alpha.473
Current platform     : darwin
Query Engine         : version (at /.../.../, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : version (at /.../.../)
Introspection Engine : version (at /.../.../)
```

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by timsuchanek** [comment]
There is a corresponding PR https://github.com/prisma/prisma/pull/4458

**Comment by timsuchanek** [comment]
Fixed by https://github.com/prisma/prisma/pull/4458
