### ISSUE TITLE
MongoDB many to many: `PANIC: called Option::unwrap() on a None`

### ISSUE THREAD

**Issue by NickFoden** [prisma/prisma#11970]
### Bug description

If don't include proper mongodb many to many relation ids etc, there is a rust panic. 

If follow the [docs](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb) all is fine:

Creating this issue/reproduction for @janpio to analyze after I commented on https://github.com/prisma/prisma/issues/9795

### How to reproduce

I setup basic node express app and can see in the screenshots folder the Rust Panic.  

Steps:
- get a mongodb uri string
- clone https://github.com/NickFoden/404
- add an `.env` file in root with the mongodb uri string similar to `.env.example`
-  install deps, then run locally `npm run dev` 
- hit the `/example` route with a get request

### Expected:
-  _when running_: don't have Rust Panic, rather just throw more helpful error about missing mongodb relation ids `String[]  @db.Array(ObjectId)` etc 
- _when linting_: throw linting errors when running `prisma format` or `prisma generate`

### Prisma information

```
 "dependencies": {
    "@prisma/client": "^3.9.2",
},
 "devDependencies": {
    "prisma": "^3.9.2",
   }
```

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Team {
  id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  name  String
  users User[]
}

model User {
  id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  name  String
  teams Team[]
}
```

### Environment & setup

- OS: Mac
- Database: MongoDB
- Node.js version: 
```
    "node": "14.18.1",
    "npm": "7.24.1"
```

### Prisma Version

```
3.9.2

```

**Comment by pimeys** [comment]
Prisma 3.10.0 lints this with the following error:

![2022-03-02_12-03-1646220976](https://user-images.githubusercontent.com/34967/156354886-0a4404ce-7218-43bf-99b2-91cd4104e9ad.png)

Please reopen the issue if you still have trouble with the latest version!

**Comment by NickFoden** [comment]
Nice!
