### ISSUE TITLE
`Error parsing attribute "@default": The function auto is not a known function.`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11985]
> Sorry for replying to this but, I'm starting to have this issue.
> ![image](https://user-images.githubusercontent.com/70230904/155174266-77f25829-db38-41f5-86de-a4beb2b50e61.png)
> After using auto() I get the same error this thread is titled as.

_Originally posted by @ThatBlueDevil in https://github.com/prisma/prisma/issues/11771#issuecomment-1047969270_

**Comment by janpio** [comment]
What version of Prisma are you using @ThatBlueDevil?
What version of the Prisma extension do you have installed?
Is that screenshot from some CLI command or from the extension itself?

**Comment by ganesshkumar** [comment]
+1 I have started to see the same error. I am not able to use either `dbgenerated()` or `auto()` as of now.

**Comment by ganesshkumar** [comment]
Okay. Updating to `3.10.0' and using `auto()` fixed the error. 

```
"@prisma/client@^3.10.0":
  version "3.10.0"
  resolved "https://registry.yarnpkg.com/@prisma/client/-/client-3.10.0.tgz#4782fe6f1b0e43c2a11a75ad4bb1098599d1dfb1"
  integrity sha512-6P4sV7WFuODSfSoSEzCH1qfmWMrCUBk1LIIuTbQf6m1LI/IOpLN4lnqGDmgiBGprEzuWobnGLfe9YsXLn0inrg==
  dependencies:
    "@prisma/engines-version" "3.10.0-50.73e60b76d394f8d37d8ebd1f8918c79029f0db86"

"@prisma/engines-version@3.10.0-50.73e60b76d394f8d37d8ebd1f8918c79029f0db86":
  version "3.10.0-50.73e60b76d394f8d37d8ebd1f8918c79029f0db86"
  resolved "https://registry.yarnpkg.com/@prisma/engines-version/-/engines-version-3.10.0-50.73e60b76d394f8d37d8ebd1f8918c79029f0db86.tgz#82750856fa637dd89b8f095d2dcc6ac0631231c6"
  integrity sha512-cVYs5gyQH/qyut24hUvDznCfPrWiNMKNfPb9WmEoiU6ihlkscIbCfkmuKTtspVLWRdl0LqjYEC7vfnPv17HWhw==
  ```

**Comment by tronglongphung** [comment]
I just had this issue and updating worked for me

**Comment by pantharshit00** [comment]
`auto()` is only introduced in 3.10 for MongoDB. I think we can close this.

**Comment by vipinlahoti** [comment]
Issue still can be seen with 3.10.

<img width="896" alt="Screenshot 2022-02-24 at 17 29 34" src="https://user-images.githubusercontent.com/2918394/155519923-21f8848e-f6b5-43fb-b56b-a11415184729.png">

<img width="1027" alt="Screenshot 2022-02-24 at 17 27 59" src="https://user-images.githubusercontent.com/2918394/155519943-bfac862a-a034-4144-a12a-6f732b443d4f.png">

**Comment by tronglongphung** [comment]
> Issue still can be seen with 3.10.
> 
> 
> 
> <img width="896" alt="Screenshot 2022-02-24 at 17 29 34" src="https://user-images.githubusercontent.com/2918394/155519923-21f8848e-f6b5-43fb-b56b-a11415184729.png">
> 
> 
> 
> <img width="1027" alt="Screenshot 2022-02-24 at 17 27 59" src="https://user-images.githubusercontent.com/2918394/155519943-bfac862a-a034-4144-a12a-6f732b443d4f.png">
> 
> 

Have you tried updating the addons?

**Comment by vipinlahoti** [comment]
"@prisma/client": "^3.10.0",
"prisma": "^3.10.0",
"mongodb": "^4.4.0",
Yes settingup a project from scratch and dependencies are upto date

**Comment by tronglongphung** [comment]
@vipinlahoti I meant the VS code Prisma extension. Sorry I confused you.

**Comment by vipinlahoti** [comment]
My bad, it was an extension update issue. Thanks a ton @tronglongphung

**Comment by AlekseiKromski** [comment]
I have "@prisma/client": "^3.12.0" - and i can not use auto() or dbgenerated()

**Comment by alannaidon** [comment]
I'm having the same issue, but with prisma `5.2.0` in nestJs  
```
/home/node/app $ npx prisma -v
Environment variables loaded from .env
prisma                  : 5.2.0
@prisma/client          : 5.2.0
```  

Just installed the extension, so I don't think this needs update.  

Something changed to this new version?  
![image](https://github.com/prisma/prisma/assets/13774879/81e538f6-fc63-4511-9234-c927df6d260a)

Because I couldn't find anything on [Documentation](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model). I also don't have `@db.ObjectId`.  

I'm more than happy to use `uuid()`, just trying to understand. I'm following a tutorial using 5.1 version and this works there.  
Thanks!
