### ISSUE TITLE
`$on` argument type error when extending prisma client

### ISSUE THREAD

**Issue by smitssjors** [prisma/prisma#11986]
### Bug description

When extending the `PrismaClient` class it is not possible to pass the `query` event type to `prisma.$on()` even though the correct options are passed to the `PrismaClient` in the `super()` call.

```ts
class Test extends PrismaClient {
  constructor() {
    super({
      log: [
        {
          emit: "event",
          level: "query",
        },
      ],
    });

    this.$on("query", (e) => {
      console.log(e);
    });
  }
}
```
The code above produces the following error:
```
TS2345: Argument of type '"query"' is not assignable to parameter of type '"beforeExit"'.
```

### How to reproduce

1. Download the quick-start project
2. Paste in the above code snippet
3. Run `yarn dev`

### Expected behavior

The `query` parameter is valid.

### Prisma information

Nothing relevant

### Environment & setup

- OS: Ubuntu (WSL on Windows 11)
- Database: SQLite
- Node.js version: 16.14.0

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
```
Also happens on
```
prisma                  : 3.9.2
@prisma/client          : 3.9.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ../../node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ../../node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ../../node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at ../../node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by moljac024** [comment]
Also happens on 3.10.0

This is a bit of a blocker for us as it means we can't integrate prisma query logs into our pipeline.

**Comment by AmreeshTyagi** [comment]
Meanwhile I am trying to use something like this. Still need to test.

```js

prisma.$use(async (params, next) => {
  const before = Date.now();
  const result = await next(params);
  const after = Date.now();
  // eslint-disable-next-line no-console
  logQuery(`Query ${params.model}.${params.action} took ${after - before}ms`);
  return result;
});
```

**Comment by phil-r** [comment]
Can be worked around by following this: https://github.com/prisma/prisma/issues/4746#issuecomment-750949556

**Comment by SevInf** [comment]
Hey, @smitssjors you'll have to explicitly pass generic parameters to `PrismaClient` when extending it for this code to work:

```ts
class MyClient extends PrismaClient<Prisma.PrismaClientOptions, 'query'> {
  ...
}
```

This is the way extending generic classes works in TS, unfortunately, it can't infer the parameters from `super` call

**Comment by aqrln** [comment]
Upstream TS issue: https://github.com/microsoft/TypeScript/issues/36456

**Comment by smitssjors** [comment]
Hey @SevInf, unfortunately I only know the log levels at run time so I guess I'll wait for the issue mentioned by @aqrln to be fixed or dynamically create the class. Thanks for the help.

**Comment by SevInf** [comment]
@smitssjors in that case, I think, you should be able to specify all events during compile time and then just subscribe to the ones you need in run time:

```ts
class MyClient extends PrismaClient<Prisma.PrismaClientOptions, 'query' | 'info' | 'warn' | 'error'> {
  ...
}
```

**Comment by r1si** [comment]
I have the same issue.. please fix TS

**Comment by janpio** [comment]
What is the issue in your opinion @r1si? We think nothing is broken or to do here. Please describe your problem more extensive, optimally in a new bug report issue. Thanks.

**Comment by r1si** [comment]
Hi @janpio !
As you can see form this screen
the function $on accepted only event "beforeExit" the event "query" "error" or "info" goes into TS error.
I need to suppress to compile the code.
<img width="461" alt="image" src="https://user-images.githubusercontent.com/6353773/173114590-4c1d269f-7e9e-4391-bba1-9553167118c3.png">

**Comment by janpio** [comment]
Did you configure the constructor that `PrismaClient` should actually emit events on `warn`, `info` and `warn`? By default that is not the case, but setting like shown for `query` on https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging#event-based-logging should fix that.

**Comment by janpio** [comment]
Ok. Then please open a bug report report issue and provide all the information the issue template akss for. Thanks.

**Comment by r1si** [comment]
Thanks a lot @aqrln it works!

**Comment by aqrln** [comment]
@jeremyisatrecharm could you please open a new issue for this? It's a bit different case since it is related to Prisma Client Extensions, and we'd definitely like to look into it. Thank you!

**Comment by nikelborm** [comment]
Fixed in https://github.com/prisma/prisma/pull/24133
