### ISSUE TITLE
Can't get it to work using prisma wizard

### ISSUE THREAD

**Issue by joanofdart** [prisma/prisma#12017]
### Bug description

"We were unable to create your project with Heroku: Failed to scaffold prisma template in GitHub repository."

### How to reproduce

1. Go to Prisma.io
2. Try and get started.
3. Connect your github/heroku or planetscale account.
4. Grant access.
5. Check the error happening.

### Expected behavior

Everything is created and I'm able to go to the dashboard accordingly.

### Prisma information

Clean schema.

### Environment & setup

Edge, Web.

### Prisma Version

Whatever version is available through prisma.io

**Comment by janpio** [comment]
Please report this via the Chat feature on Prisma Data Platform directly, where our support team will be able to help you. Thanks.
