### ISSUE TITLE
findFirst always throws error ignoring rejectOnNotFound

### ISSUE THREAD

**Issue by umakantp** [prisma/prisma#12025]
### Bug description

My config for rejectOnNotFound is `rejectOnNotFound: { findUnique: true },`. This means when I make a call for `findFirst` it should return null & NOT throw error.

I was trying to see if the email is used and calling `db.user.findMany({ where: { email: { equals: 'myemail@gmail.com, mode: 'insensitive' } } })`. It is currently throwing error:-

```
[DATABASE_ERROR: Cannot read properties of null (reading 'createdAt')] {
  extensions: { code: 'DATABASE_ERROR' },
  clientVersion: '3.10.0'
}
```

This error shows up only when there is no result. Anyway if I change `rejectOnNotFound` to `rejectOnNotFound: { findUnique: true, findFirst: true },` just for debugging like what difference it makes. It comes with another error:-

```
[NOT_FOUND: No User found with email = {"equals":"myemail@gmail.com","mode":"insensitive"}] {
  extensions: { code: 'NOT_FOUND' },
  clientVersion: '3.10.0'
}
````

Did I miss something on docs? Docs say that keeping `findFirst` off, or not passing it should return null.

Just side node: I was using version 3.6.0 and it was working as expected. I have been seeing this behaviour after update to version 3.10.0.

### How to reproduce

1. npm init
2. npm install --save prisma primsa/client
3. vi demo.js
4. Paste the following code & save
```
import { PrismaClient } from '@prisma/client'

const db = new PrismaClient({
  rejectOnNotFound: { findUnique: true },
  log: [
    { level: 'warn', emit: 'stdout' },
    { level: 'error', emit: 'stdout' },
    { level: 'query', emit: 'event' },
  ],
  datasources: {
    db: { url: env.MY_DATABASE_URL },
  },
})

db.user.findFirst({ where: { email: { equals: 'someemail@gmail.com', mode: 'insensitive' } } })
```
5. Set env variable `MY_DATABASE_URL` to your Postgres db connect string.
6. node demo.js

### Expected behavior

When `rejectOnNotFound: { findUnique: true },` is set, on calling findFirst should not throw error and instead return null.

### Prisma information

```
model User {
  id                     String      @id @default(cuid())
  createdAt        DateTime    @default(now())
  updatedAt       DateTime    @updatedAt
  firstName        String
  lastName         String?
  email                String      @unique
  password         String
  salt                   String?
  timezone         String?
}
```

```
db.user.findMany({ where: { email: { equals: 'myemail@gmail.com, mode: 'insensitive' } } })
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v16.13.1

### Prisma Version

prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0

**Comment by pantharshit00** [comment]
I am unable to reproduce this:
<img width="992" alt="image" src="https://user-images.githubusercontent.com/22195362/155687429-63dda84d-49fa-4df5-a171-2035cb4f04bb.png">


I used the following code:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient({
    rejectOnNotFound: { findUnique: true },
    log: [
      { level: "warn", emit: "stdout" },
      { level: "error", emit: "stdout" },
      { level: "query", emit: "event" },
    ],
  });

  const data = await prisma.user.findFirst({
    where: { email: { equals: "someemail@gmail.com", mode: "insensitive" } },
  });
  console.log(data);
  prisma.$disconnect();
}

main();
```



Can you please confirm the callsites of the errors is the same as you are reporting and they are not coming from difference place in your source code?

**Comment by umakantp** [comment]
yes we close this. I in a isolation was able to remove this. Thanks
