### ISSUE TITLE
CLI method to invoke panic

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#12034]
This would help us in testing. For the error reporting backend for example.

**Comment by pantharshit00** [comment]
We already have this but not implemented for Node API: https://github.com/prisma/prisma/issues/7810

It got implemented for the exact reason you mentioned while I was building the error reporting system.

```ts
const db = new PrismaClient({
    __internal: {
      engine: {
        allowTriggerPanic: true,
      },
    },
    errorFormat: 'minimal',
  })
  
  db.__internal_triggerPanic(true)
 ```
