### ISSUE TITLE
Default UUID not working for my-sql

### ISSUE THREAD

**Issue by mastoltejr** [prisma/prisma#12055]
### Bug description

@default(uuid()) stopped working as expected in my model.
I've checked the migration sql file and there is no default clause for the column uuid.

### How to reproduce

prisma migrate dev --name testing

### Expected behavior

The table should generate a UUID by default if not provided

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model test {
  id   Int    @id @default(autoincrement())
  uuid String @unique @default(uuid())
}
```

migration file output

```
-- CreateTable
CREATE TABLE `test` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `test_uuid_key`(`uuid`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

```

### Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v14.15.5

### Prisma Version

```
3.8.1
```

**Comment by janpio** [comment]
Are you sure there ever was and this ever worked as you describe? `uuid()` is a Prisma level function, if you want something in the database you need to use `@default(dbgenerated(...))`. Is there anything else than it not appearing in the migration file that makes you say it stopped working?

**Comment by mastoltejr** [comment]
using @default(uuid()) has worked for me in the past. Maybe now it has changed with the latest update ?
but the docs still say it should work...

[docs](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#generato
<img width="709" alt="Screen Shot 2022-02-27 at 9 23 00 AM" src="https://user-images.githubusercontent.com/31829871/155890556-5db6483e-ea05-409c-aaaf-fe4d3e07c495.png">
r)

**Comment by mastoltejr** [comment]
I've found that there wasn't a problem at all. I was expecting the default statement to be in the migration sql but it's a prisma level function as @janpio mentioned so it won't show there.
#11747
