### ISSUE TITLE
Make Prisma2 Kubernetes Ready

### ISSUE THREAD

**Issue by MikeyUchiha** [prisma/prisma#1205]
Currently it is not possible to run prisma2 in Kubernetes which makes a CI/CD deployment pipeline difficult.

The recommended way to run prisma2 is in a Docker with interactive mode enabled. However, this isn't best practice and is not possible to do in a Kubernetes environment. The correct way to do this would be to allow us to use Docker without enabling interactive mode and this in turn will make Kubernetes work correctly.

Provided testing is here:
![70377727-e3675980-18e5-11ea-839f-9c0812ff78e4](https://user-images.githubusercontent.com/3036263/71312845-f3eafa00-23e4-11ea-86b1-6e2cf6236c74.png)
![70377737-0560dc00-18e6-11ea-80c3-1b083bca613e](https://user-images.githubusercontent.com/3036263/71312846-f6e5ea80-23e4-11ea-9191-6d0e64cd3854.png)
![70377759-40630f80-18e6-11ea-9dbf-78c86d147918](https://user-images.githubusercontent.com/3036263/71312847-f9484480-23e4-11ea-89db-c86d9fd92bad.png)

**Comment by janpio** [comment]
What `prisma2` commands do you need to run in a Kubernetes environment?

**Comment by MikeyUchiha** [comment]
@janpio I want to be able to run prisma2 dev so that my testers can easily create test data using the Prisma Studio.

**Comment by janpio** [comment]
Have you tried using `prisma2 studio`?

**Comment by MikeyUchiha** [comment]
@janpio this seems to work well. thank you!
How would I go about updating the studio after I change the schema?
Since it's not using the dev which watches for changes in the schema.

**Comment by pantharshit00** [comment]
You will likely restart it. Are you using kubernetes for development? I don't think it is ideal for development.

**Comment by MikeyUchiha** [comment]
@pantharshit00 I am currently using docker-compose. But what you said about restarting makes sense. If I restart and there were changes to my .prisma file the new docker build should get it.

**Comment by MikeyUchiha** [comment]
So then there won't be a list of migrations. Each time I spin up the docker image, it would introspect the .prisma file and create the schema as needed?

**Comment by MikeyUchiha** [comment]
@pantharshit00 after updating my .prisma file with changes, I'm not seeing any updates to the Docker container when I rebuild it.

**Comment by pantharshit00** [comment]
You will need to migrate your database either via `prisma2 lift save && prisma2 lift up` or via `prisma2 dev`.

If you want to execute `prisma2 dev` inside docker, run docker tty in interactive mode.

```
docker exec -it <container> prisma2 dev
```

`-i` tells docker to run in interactive and `-t` tells it to give you a pseudo tty. That will allow you to run `prisma2 dev` without that error.

**Comment by MikeyUchiha** [comment]
@pantharshit00 Let me start from the beginning on what I want to do.
In the following screenshot you can see that I have the automatically generated migrations folder.

![2019-12-27 08_27_32-Dockerfile - graphql-api-prisma2 - Visual Studio Code](https://user-images.githubusercontent.com/3036263/71524562-f89b2c80-2882-11ea-96d3-c44606bcdb40.png)

The pipeline that I want to have is to be able to run docker-compose build and docker-compose up and to be able to handle development locally.

![2019-12-27 08_31_49-docker-compose yml - graphql-api-prisma2 - Visual Studio Code](https://user-images.githubusercontent.com/3036263/71524675-67788580-2883-11ea-8c04-339936b33247.png)

Whenever I make a change to the schema, I want it to automatically update my migrations folder. Or at least, have some way to manually push the migration changes from the docker-compose Prisma2 container to my local migrations folder.

In addition, when the image is pushed via CI/CD pipeline such as CircleCI I want to provide an easy way for testers to be able to add data during the pull request when a test instance is spun up. Hence why I want to use prisma2 dev. The prisma2 studio works well for the testing use case but I can't use it for development when working on the schema in real-time.

Thanks so much for your help!

**Comment by pantharshit00** [comment]
For pipeline ususage, I will recommend you to use `prisma2 lift save` and `prisma2 lift up` workflow and running `prisma2 lift up` in the CI.

But we already have issues for related topics like CLI not support non tty terminals and NO_COLOR mode terminal enumlators so I think we would gradually address this.

Related issues: https://github.com/prisma/prisma2/issues/554,https://github.com/prisma/prisma2/issues/686

**Comment by RafaelKr** [comment]
Probably the `script` command can be used to work around the tty and color problems for now.

I discovered this as I wanted to run a cronjob in a docker container which needed tty and I also wanted to preserve colors in my log files.

My script which I'm calling from `crontab -e`:
```bash
#!/bin/bash

# http://xensoft.com/redirect-all-output-in-a-shell-script/
# test if fd 1 (STDOUT) is NOT associated with a terminal
if [ ! -t 1 ]; then
  NOW=$(date +"%Y%m%d_%H%M%S")

  # redirect STDOUT and STDERR to a file
  exec &> /app/logs/import/${NOW}_import_cron.log
fi

cd /app/packages/server

# run with script command to prevent docker-compose error "the input device is not a TTY" and to preserve colored output in log file
# "docker-compose exec -T" has discarded the colors
# https://stackoverflow.com/questions/1401002/how-to-trick-an-application-into-thinking-its-stdout-is-a-terminal-not-a-pipe
script --return --quiet -c "docker-compose -f docker-compose.yaml -f docker-compose.server.yaml exec service_1 yarn start:importer" /dev/null
```

**Comment by ManAnRuck** [comment]
`prisma2 dev` dev doesn't exist any more.

does someone have a currently working version to run Prisma in Kubernetes?

**Comment by Sytten** [comment]
@ManAnRuck I am honestly confused about what you mean by that, we have a production service running with prisma2 on kubernetes right now. Its just a docker container after all.

**Comment by pantharshit00** [comment]
I think this issue can be closed now. We don't have an interactive command like prisma dev in the latest version which was not properly rendered by non tty interface of kubernetes.

Closing this now, please open a new issue if you facing some issue.
