### ISSUE TITLE
`id` is ignored when provided at creation

### ISSUE THREAD

**Issue by guillaumervls** [prisma/prisma#12077]
### Bug description

Hi,

Looks that the `id` field (or the one specified with `@id`) gets ignored by Prisma Client upon item creation. Prisma generates an UUID anyway.

Is that intentional ? If so why does this field appears in the TypeScript data type for the `create` method ? And I can't find any doc that warns about this behavior...

Unless I'm missing something...

Cheers !

### How to reproduce

Just write a simple model with 

```prisma
model Model {
  id String @id @default(uuid())
}
```

and then

```js
prisma.model.create({data: {id: "foo"}});
```

The created object does not have `foo` as its `id`.

### Expected behavior

The created object should have `foo` as its `id`.

### Prisma information

Cf above

### Environment & setup

- OS: MacOS
- Database: MySql (Planetscale)
- Node.js version: 16.13

### Prisma Version

```
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0
Preview Features        : referentialIntegrity
```

**Comment by garrensmith** [comment]
@guillaumervls from what I can see, the Model field name is `bar` and then you trying to create a model with an id named `id`. 
I think you need to do:
```
prisma.model.create({data: {bar: "foo"}});
```

**Comment by guillaumervls** [comment]
Sorry, there was a typo in my issue. Fixed it. (It is indeed `id` not `bar`)

**Comment by janpio** [comment]
I can not reproduce this on PlanetScale, both with and without `referentialIntegrity = prisma` set:

```
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient()

async function main() {
    await prisma.model.create({data: {id: "foo"+Math.random().toString(16).slice(2) }});
    console.log("results", await prisma.model.findMany({}))
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

After a few calls:
```
PS C:\Users\Jan\Documents\throwaway\12077> node .\script.js
results [
  { id: 'foo2a916a3d849c' },
  { id: 'foo64bb42fc64ff6' },
  { id: 'foo83ae0c45f0597' },
  { id: 'fooc0e3eff3019ee' }
]
```  

What am I missing?

**Comment by guillaumervls** [comment]
Weird. I re-did it all from scratch and it works. I must have been very tired when I did it the first time.

Very sorry for the inconvenience.
