### ISSUE TITLE
PrismaClientKnownRequestError not thrown for `The provided value for the column is too long for the column's type.`

### ISSUE THREAD

**Issue by dycor** [prisma/prisma#12073]
### Bug description

In our application when we want to create a line myTable, we give a body with data. One attribute of the data does not respect the rule put in schema . We give an attribute with more than 20 characters in postgres database.

```prisma
model MyTable {
  // ...
  myAttribute         String    @db.VarChar(20)
 // ...
}
```

```ts   
async (req: Request, res: Response, next: NextFunction): Promise<void> => {
      try {
        const myResult = await prisma.myTable.create({
          data: {
            ...req.body,
          },
        });
        res.json({ myResult });
      } catch (error) {
        next(error);
      }
    }
  );
  ```

Then we have this log, but the catch block is not invoked

```
PrismaClientKnownRequestError:
 Invalid `prisma.myTable.create()` invocation:
   The provided value for the column is too long for the column's type. Column: (not available)
     at cb (/home/site/wwwroot/node_modules/@prisma/client/runtime/index.js:38675:17) {
     code: 'P2000',
     clientVersion: '3.5.0',
     meta: { column_name: '(not available)' }
 }
 ```

We have the same issue with 3.10.0 version.

### How to reproduce

Create a postgres database with a table with an attribut of type with a limit.
Try to create a line in this table with a data attribut over the limit

### Expected behavior

An error should bre throwed not just log

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```
```ts
declare global {
  // eslint-disable-next-line no-var
  var prisma:
    | PrismaClient<{ log: { emit: 'event'; level: 'query' }[] }, 'query', false>
    | undefined;
}
export const prisma =
  global.prisma ||
  new PrismaClient({
    log: [
      // 'query', // uncomment for default query only logs
      { emit: 'event', level: 'query' },
    ],
  });
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 
NodeJs 14.17.4
Postgres 10.3
OS : MacOS / Linux

### Prisma Version

```
3.10.0
3.5.0
```

**Comment by janpio** [comment]
So the error being thrown is fine, but it is now of the correct type you are expect with a documented error code, correct?

**Comment by drico** [comment]
@janpio, we see in the logs that an error is raised in prisma's internal code, but calling `await prisma.myTable.create(...)` returns undefined and does not throw an error, so it's impossible for us to catch the error.

**Comment by janpio** [comment]
Oh ok, that is worse. We'll see if this is reproducible for us.

**Comment by alexanderattar** [comment]
Seeing the same issue ➕

**Comment by alexanderattar** [comment]
Actually, my bad. I spoke too soon. In my case, I realized I was missing an await on the `create` call 🤦 
Thanks for looking into it anyways!

**Comment by siddharthsharma94** [comment]
I fixed this on a MySQL DB by adding a @db.Text() identifier to the field on the Prisma schema

```
publicData         String?   @db.Text()
```

**Comment by max-programming** [comment]
Thanks @siddharthsharma94! It helped!

**Comment by Weakky** [comment]
Hey folks, I'm unable to reproduce this issue, neither on 3.10.0 nor on the latest version (5.10.0). Here's the snippet I'm using:


```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient({
    log: [{ emit: "event", level: "query" }],
  });

  try {
    await prisma.model.create({
      data: {
        myAttribute: "a".repeat(30),
      },
    });
  } catch (e) {
    console.log("caught"); // logged
    console.error(e); // logged
  }
}

main()
  .then(() => console.log("Done!"))
  .catch((err) => console.error(err));
```

Is there anything I'm missing? Would you perhaps be able to provide a concise reproduction?

Thanks for your help 🙏

**Comment by apolanc** [comment]
Hi everyone, as pointed out earlier by @Weakky, we were unable to reproduce this issue. Due to the inactivity of this issue, we will now close it and advise to open a new issue if this problem or a similar one persists. Thank you all for your input and feedback!
