### ISSUE TITLE
CockroachDB session settings for migrations

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#12113]
In its current state, Migrate relies on the following session variables for diffing to function properly:

```sql
SET enable_experimental_alter_column_type_general = true;
SET default_int_size = 4;
SET serial_normalization = 'sql_sequence';
```

These are [session variables](https://www.cockroachlabs.com/docs/stable/set-vars.html) that are set on a per-connection basis and not persisted on the server. The same options can be set to the same or different values with [SET CLUSTER SETTING](https://www.cockroachlabs.com/docs/stable/set-cluster-setting.html).

Let's review what they do:

- `enable_experimental_alter_column_type_general` allows migrating the type of a column in an `ALTER TABLE` statement, with restrictions (depending on column types, and whether the column is indexed). It makes the experience better, and we count on this becoming the default behaviour, so this is fairly unproblematic.
- `default_int_size` makes `INTEGER` map to `INT4`, i.e. a 32-bit integer instead of the default 64 bit. This is enabled to align with postgresql, on which our diffing logic is based. We could change that, it's just more convenient for our tests and our internal diffing logic.
- `serial_normalization = 'sql_sequence'` ensures we can have `SERIAL` columns that are not `BigInt`, since that's implicit in the default value of `rowid`. Without this, the "traditional" Prisma `id Int @default(autoincrement())` is not possible (it will always be a `BigInt`).

## Open questions

- Do we want to handle any combination of server settings? For example in case of default_int_size, we would need to adjust the diffing logic based on default_int_size. More problematic, for serial_normalization, we would either reject valid schemas during prisma schema validation, or allow schemas that will not work on all servers (it depends on the server setting, which we don't know until we have connected).
- Assuming we do _not_ want to support any combination of server settings, we will use session variables like we do now. Is it significantly better to stick to the cockroachdb defaults in the value of these variables?
- Do we want to avoid ambiguous column types like `INTEGER` and always use the cockroach-specific `INT2`, `INT4` and `INT8` types for cockroachdb migrations?

**Comment by janpio** [comment]
Context:
https://github.com/prisma/prisma-engines/blob/fe68ee16ec7694924b82bf075382fa68e69989da/migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs#L29-L35

It seems `default_int_size` has already been removed via https://github.com/prisma/prisma-engines/commit/918d1424b90a447ebaba434af073401d5c158357
