### ISSUE TITLE
Custom ID Generator as an alternative to middleware

### ISSUE THREAD

**Issue by HommeSauvage** [prisma/prisma#12125]
## Problem

Prisma provides a way to autogenerate ids with `@default` however only few functions are available: `cuid` `uuid` and `autoincrement`. When using custom IDs, you'll have to manually provide the ID to the `create` function. This results in some unnecessary code that can be removed.

Using `middleware` is possible, however typescript will still required an `id` to be passed to the function.

Also, when generating ID's based on fields, this adds a bit more complications. The way I'm generating ID's is based on an `object` enum field with a single default value as such:

```prisma
enum UserObject {
  user
}
model User {
  id String @id @map("_id")
  object UserObject @default(user)
}
```

Then, I made a function so that I use it as such: `generateId('user')` typed to accept only objects from the schema which will return an generated id based on that object, for example: `usr_xxxxxxxxxxx`.

## Suggested solution

A way to achieve this is to allow `@default(customIdGenerator())` in the schema file and then set globally an ID generator on the Prisma object, maybe something like this:
```ts
Prisma.setIdGenerator((data) => {
   // this will return 
   return generateId(data?.object)
})
```

This should work with composite types as well

**Comment by janpio** [comment]
Would this request be covered by this very similar feature request here @HommeSauvage https://github.com/prisma/prisma/issues/6719?

**Comment by HommeSauvage** [comment]
Yes, that would be amazing. We can close this one.
