### ISSUE TITLE
errorFormat:"minimal" or other options not working

### ISSUE THREAD

**Issue by Varghese1987** [prisma/prisma#12130]
### Bug description

errorFormat:"minimal" or other options not working

**Comment by janpio** [comment]
Can you share some more information? What specific code? What version?

**Comment by Varghese1987** [comment]
version: "@prisma/client": "^3.9.2",

setup:

constructor() {
		super({ log: ["query"], errorFormat: "minimal" })
	}

expected error:
Unique constraint failed on the fields: (`Email`)

Received:
\nInvalid `this.prisma.user.create()` invocation in\n/app/dist/apps/core/main.js:3122:42\n\n  3119     this.utilsService = utilsService;\n  3120 }\n  3121 async create(args) {\n→ 3122     const request = this.prisma.user.create(args)\n  Unique constraint failed on the fields: (`Email`)

**Comment by Varghese1987** [comment]
Formatting levels
There are 3 error formatting levels:

Pretty Error (default): Includes a full stack trace with colors, syntax highlighting of the code and extended error message with a possible solution for the problem.
Colorless Error: Same as pretty errors, just without colors.
Minimal Error: The raw error message.
In order to configure these different error formatting levels, there are two options:

Setting the config options via environment variables
Providing the config options to the PrismaClient constructor

**Comment by Varghese1987** [comment]
above configuration is not working

**Comment by Varghese1987** [comment]
Reference doc:
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/error-formatting

setup not working based on the doc, let us know what is the way out

**Comment by pantharshit00** [comment]
I can confirm that error format did change from 3.8 so this is a regression.
