### ISSUE TITLE
Prisma `.count()` does not apply `where` clause on PostgreSQL

### ISSUE THREAD

**Issue by fwallacevt** [prisma/prisma#12158]
### Bug description

Prisma client `.count()` method does not apply `where` clause using PostgreSQL. I am trying to count the number of records in a table that abide by certain criteria. Instead, Prisma returns the count of all records in the table.

Example query and resulting SQL:
```js
const total = await prisma.myTable.count({
  where: { id: "myid" },
})
```

produces SQL
```sql
SELECT COUNT(*) FROM (SELECT "public"."my_table"."id" FROM "public"."my_table" WHERE 1=1 OFFSET $1) AS "sub"
```

### Expected behavior

Prisma should return an appropriate count of _*filtered records*_.

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.9.0
```

**Comment by luxaritas** [comment]
I think this was fixed in 3.9.1: https://github.com/prisma/prisma/issues/11645#issuecomment-1031391075
