### ISSUE TITLE
SQL Server: Introspection does not pick up legacy default objects (`CREATE DEFAUT ... AS ...`)

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#12150]
See also https://www.prisma.io/docs/orm/overview/databases/sql-server#shared-default-values-are-not-supported

### Bug description

With the following SQL:

```sql
CREATE DEFAULT [dbo].[valueZero] AS 0;

CREATE TABLE [dbo].[A] (
  id INT IDENTITY,
  val INT NOT NULL
);

sp_bindefault '[dbo].[valueZero]', '[dbo].[A].[val]'
```

(might need to run statement by statement)

Introspection returns the following data model:

```prisma
model A {
  id  Int @id(map: "PK__A__3213E83FB0AD5CC7") @default(autoincrement())
  val Int
}
```

The default value is not visible in the column `val`. We can try to `INSERT INTO [dbo].[A] DEFAULT VALUES`, and the default value of `0` gets inserted to the column correctly.

Note for discussion: [this way of defining default values is not recommended by Microsoft anymore](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-default-transact-sql?view=sql-server-ver15). There might be legacy databases using this feature though.

**Comment by janpio** [comment]
While these defaults are usually just skipped, they can also trigger a schema engine panic when the default is stored as a multi-line string, for example because of a leading comment, in the schema definition: https://github.com/prisma/prisma/issues/24275

**Comment by janpio** [comment]
Closing this issue, as we have properly documented this: https://www.prisma.io/docs/orm/overview/databases/sql-server#shared-default-values-are-not-supported
