### ISSUE TITLE
npx prisma init error

### ISSUE THREAD

**Issue by KKaranja** [prisma/prisma#12178]
Am getting the error below when I try to initiate prisma, any idea why am getting the error?   
> Downloading Prisma engines for Node-API for windows [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/73e60b76d394f8d37d8ebd1f8918c79029f0db86/windows/migration-engine.exe.gz.sha256 failed, reason: 
unable to get local issuer certificate
error Command failed with exit code 1.

**Comment by janpio** [comment]
Any local network configuration that is uncommon? The file is available for download, so this seems to be something in your setup that leads to a message when checking the SSL certificate chain.

**Comment by cassianomon** [comment]
I have similar issue when installing through keystone:

```   
'FetchError: request to https://binaries.prisma.sh/all_commits/2b0c12756921c891fec4f68d9444e18c7d5d4a6a/darwin-arm64/libquery_engine.dylib.node.gz.sha256 failed, reason: unable to get local issuer certificate\n' +
    '    at ClientRequest.<anonymous> (/Users/dev/backend/node_modules/@prisma/engines/dist/index.js:12769:16)\n' +
    '    at ClientRequest.emit (events.js:400:28)\n' +
    '    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n' +
    '    at TLSSocket.emit (events.js:400:28)\n' +
    '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
    '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:82:21) {\n' +
    "  type: 'system',\n" +
    "  errno: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',\n" +
    "  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'\n" +
    '}',
```
