### ISSUE TITLE
Use embedded documents attributes in where clause

### ISSUE THREAD

**Issue by tomaspozo** [prisma/prisma#12186]
## Problem

Support for embedded documents is great! But we are missing the option to filter by (query/where) an embedded field.

Let's take this schema as examples:

```prisma
model Item {
  name String
  metadata Metadata
}

type Metadata {
  size String
  color String
}
```

Currently there is no way to include `metadata.size` of `metadata.color` as attributes on the where clause like in MongoDB queries.

## Suggested solution

It would be nice to be able to use embedded attributes as filters, so we can use them like with `relations`

```typescript
this.prisma.document.findMany({ where: { metadata: { size: "XS" } } } )
```

## Alternatives

Use [raw queries](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#raw-queries-with-mongodb).

**Comment by matthewmueller** [comment]
Hey @tomaspozo, thanks for reaching out! Good news, we're actively working on this and it should be out next week.

**Comment by blueau** [comment]
@matthewmueller 
`this.prisma.document.findMany({ where: { metadata: { size: "XS" } } } )`
Is this function complete?

**Comment by janpio** [comment]
@blueau This issue was closed a year ago. Please consider opening a [new issue](https://github.com/prisma/prisma/issues/new/choose) or discussion instead of leaving a comment here.
