### ISSUE TITLE
ConnectorError Some(WasNull()) on `String[]` field with `NULL` entries

### ISSUE THREAD

**Issue by casey-chow** [prisma/prisma#12188]
### Bug description

When running Prisma in production I occasionally get this error:

```
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(6), cause: Some(WasNull) }) })
```

### How to reproduce

I cannot reproduce this reliably, but can provide DM a Sentry error for diagnosis.

### Expected behavior

No error should be thrown.

### Prisma information

Prisma Query:
```ts
  const user = await prisma.user.findUnique({
    where: { id: data.userId },
    rejectOnNotFound: true,
  });
```

Relevant schema:
```prisma
model User {
  id     Int     @id @default(autoincrement())
}
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

Running on Heroku with PostgreSQL 13 against Node.js v16.13.1.

### Prisma Version

```
prisma                  : 3.4.0
@prisma/client          : 3.4.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85
Studio                  : 0.438.0
```

**Comment by janpio** [comment]
Do I recall correctly that you wrote somewhere that `    rejectOnNotFound: true,´ is what causes this to happen?
Can you really reproduce this with this minimal schema?
What does "intermittent" mean here?
Does your Sentry error have more information on what query was executed?

**Comment by janpio** [comment]
My email is jan@prisma.io.

Do all these queries have something in common somehow? Similar data structure? Can you log these in cases of error?

I also just noticed that you are on a older Prisma version. Would it be possible for you to update to the most recent one?

**Comment by casey-chow** [comment]
I'll go ahead and email you the Sentry error!

> Do all these queries have something in common somehow? Similar data structure? Can you log these in cases of error?

All instances of the error are of this query. I've looked at the retry in a couple instances and it seems retrying works just fine.

> Would it be possible for you to update to the most recent one?

Yep! I'm on 3.10.0 now as of 4 days ago.

**Comment by casey-chow** [comment]
As a bit of an update, it appears this error isn't common to this one query, and happens in `findMany`. I get the following errors as well:
```
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(7), cause: Some(WasNull) }) })
```

This came from this query:

```ts
  await prisma.user.findMany({
    where: {
      lastSyncedAt: null,
      devices: {
        some: {
          buildNumber: { gte: minSupportedBuildNumber },
        },
      },
```

**Comment by casey-chow** [comment]
Okay, I figured out what was causing it! I had a field that was of type `String[]` but it had some `NULL` values in some results. When Prisma read those null values, it would throw this error. To fix, I ran the following migration to add a check constraint and ensure nulls don't make their way back in:

```sql
BEGIN;

UPDATE "user"
SET "emails" = array_remove("emails", NULL)
WHERE array_position("emails", NULL) IS NOT NULL;

ALTER TABLE "user"
ADD CONSTRAINT "user_email_check"
  CHECK (array_position("emails", NULL) IS NULL);

COMMIT;
```

**Comment by janpio** [comment]
Awesome! That should allow us to reproduce the error and then hopefully implement a better one in the future.

**Comment by westmark** [comment]
Hi! I started using Prisma today and after connecting to an existing database immediately ran into the issue above, i.e. having `NULL` values in a list. Is this supposed to actually work? I was looking at https://github.com/prisma/prisma/issues/847 but if I understand the discussion correctly that issue is more about not being able to store `NULL` instead of `[]`. Right?

**Comment by janpio** [comment]
Can you share a simplified schema you are having @westmark and the data that makes it crash? We still have to fully reproduce this here, and more concrete information is always helpful.

**Comment by westmark** [comment]
@janpio Gladly. You can have a full repro:

https://github.com/westmark/prisma-error-repro

**Comment by pantharshit00** [comment]
Thanks for the concise reproduction @westmark. I was able to reproduce the error.

**Comment by janpio** [comment]
@casey-chow Would this fit what you observed? https://github.com/westmark/prisma-error-repro/blob/main/seed.sql#L1

**Comment by casey-chow** [comment]
> @casey-chow Would this fit what you observed? https://github.com/westmark/prisma-error-repro/blob/main/seed.sql#L1

Yes!

**Comment by janpio** [comment]
New error message with Prisma 4.3.1:

```
gitpod /workspace/prisma-error-repro (main) $ yarn ts-node run.ts 
yarn run v1.22.19
$ /workspace/prisma-error-repro/node_modules/.bin/ts-node run.ts
/workspace/prisma-error-repro/node_modules/@prisma/client/runtime/index.js:29909
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.myModel.findMany()` invocation in
/workspace/prisma-error-repro/run.ts:6:37

  3 const prisma = new PrismaClient();
  4 
  5 async function main() {
→ 6   const data = await prisma.myModel.findMany(
Error converting field "intArray" of expected non-nullable type "Int", found incompatible value of "null".
    at RequestHandler.handleRequestError (/workspace/prisma-error-repro/node_modules/@prisma/client/runtime/index.js:29909:13)
    at RequestHandler.request (/workspace/prisma-error-repro/node_modules/@prisma/client/runtime/index.js:29892:12)
    at async PrismaClient._request (/workspace/prisma-error-repro/node_modules/@prisma/client/runtime/index.js:30864:16) {
  code: 'P2032',
  clientVersion: '4.3.1',
  meta: { field: 'intArray', expected_type: 'Int', found: 'null' }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
gitpod /workspace/prisma-error-repro (main) $ 
```

**Comment by Weakky** [comment]
Hey,

Given the clear error message we now have, is it acceptable to close this?

To be clear, Prisma unfortunately doesn't support nullable scalar lists at the moment but we already have a [feature request](https://github.com/prisma/prisma/issues/15886) here.

**Comment by Weakky** [comment]
I'll close this issue now at it's been stale for the past 3 months. Thanks again for the report 🙏
