### ISSUE TITLE
@updatedAt does not work with @default 

### ISSUE THREAD

**Issue by MichaelrMentele** [prisma/prisma#12189]
### Bug description

Say you have a table with existing rows and you'd like to add a new `@updatedAt` table with a default of either `null` or of `now()`. 

My assumption is that on save, prisms write to tables annotated in the schema with `@updatedAt`. I would expect if you then compose `@default(now()) @updatedAt` then it would have that default value be set and it would also update the field on save.

The problem is that when you have both set we always use the original default value and it never gets updated on save. 

### How to reproduce

1. copy this schema:
```
model Comment {
  id   Int    @id @default(autoincrement())
  body String

  // Standard Fields
  createdAt       DateTime @default(now())
```
2. migrate it
3. add a 1 row in prisma studio
4. woops, forgot the `updateAt` field -- we want that everywhere so update the schema:
```
model Comment {
  ...
  updatedAt Datetime @updatedAt
}
```
5. woops this doesn't work because we have no value in existing rows so add a default
```
model Comment {
  ...
  updatedAt Datetime @default(now()) @updatedAt
}
```
6. when you now go and save a new table row see that both are set to now, edit the body and observe `updatedAt` does NOT change -> we'd expect this to still work

Current workaround is run this, then drop the default. 

### Expected behavior

If you have a default set I'd still expect `@updateAt` to update the timestamp on save.

### Prisma information

```
model Comment {
  id   Int    @id @default(autoincrement())
  body String

  // Standard Fields
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
  testUpdatedAt DateTime @default @updatedAt
}
```

### Environment & setup

- OS: mac OS
- Database: postgres
- Node.js version: 14.17.4

### Prisma Version
```
➜  leftlane-app git:(master) ✗ yarn prisma -v
yarn run v1.22.17
$ /Users/michaelmentele/Dev/leftlane/LeftLaneDealerStack/leftlane-app/node_modules/.bin/prisma -v
Environment variables loaded from .env
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
```

**Comment by awinograd** [comment]
We are also experiencing this issue. Our table has two @updatedAt columns. One with @default(now()) and the other without a default. The default column fails to update as expected. The non-default column works as expected

**Comment by do4gr** [comment]
Exact problem described here: https://github.com/prisma/prisma/issues/15176
Reproduction: https://github.com/prisma/prisma-engines/pull/3168

**Comment by Malachite40** [comment]
Currently seeing this issue again

`"@prisma/client": "^5.4.2"`

`model CalendarEvents {
    id          String                  @id @default(uuid())
    ownerId     String
    ownerType   CalendarEventsOwnerType
    startTime   DateTime
    endTime     DateTime
    title       String
    description String?
    createdAt   DateTime                @default(now()) @db.Timestamptz
    updatedAt   DateTime                @default(now()) @updatedAt @db.Timestamptz

    @@index([ownerId])
}`

**Comment by janpio** [comment]
Then please open a new issue and fill the full issue template. Thanks.

**Comment by craigcosmo** [comment]
yep, this issue is still hrere. please fix

**Comment by kouakousjc** [comment]
Yeah, until this gets fixed this is what I use since my datasource provider is mysql.

`@default(dbgenerated("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))`

Hope this helps in the meantime.

**Comment by kkgf** [comment]
Yes, until this gets fixed this is what I use since my datasource is mysql

`@default(dbgenerated("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))`

Hope this helps

**Comment by BernalCarlos** [comment]
Happens on prisma 5

**Comment by frozenproof** [comment]
This issue happened again in  5.12.1 prisma

**Comment by janpio** [comment]
Please open a bug report issue then and provide the information the issue template asks for. Thanks.

**Comment by Doppon** [comment]
> Yes, until this gets fixed this is what I use since my datasource is mysql
> @default(dbgenerated("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
> Hope this helps

I'm also being trouble in this issue.
So, I thought about trying creating a new issue...

But, before creating that, I could find the same issue here. ↓
https://github.com/prisma/prisma/issues/12924

So, I hope it gets fixed. Thanks.

**Comment by mqliutie** [comment]
> Yes, until this gets fixed this is what I use since my datasource is mysql
> 
> `@default(dbgenerated("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))`
> 
> Hope this helps

Error: Invalid default value for 'updatedAt'
   0: sql_schema_connector::apply_migration::migration_step
           with step=CreateTable { table_id: TableId(0) }
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:21
   1: sql_schema_connector::apply_migration::apply_migration
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:10
   2: schema_core::state::SchemaPush
             at schema-engine/core/src/state.rs:434
It seems not work for me

**Comment by woss** [comment]
It's an old thread, but here is a new contribution. For the Postgres folk, you can create the migration and then edit it by adding this 
```psql
CREATE OR REPLACE FUNCTION update_file_updatedat_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW."updatedAt" = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_your_table_updatedat BEFORE UPDATE
ON "YourTable" FOR EACH ROW EXECUTE PROCEDURE
update_your_table_updatedat_column();

ALTER TABLE "YourTable"
ADD COLUMN "updatedAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
```

Change `YourTable` and `your_table` to the real table name. Also if you have different column name change it too. 


then run `prisma migrate dev` and you will get the `updatedAt` column automatically updated on any record update  on  the YourTable name

**Comment by nickheyer** [comment]
It's happening again, now in 2025. You'd think there would be unit tests to prevent this repeated regression....
