### ISSUE TITLE
Prisma crashes when pulling from database with readonly permissions on specific columns

### ISSUE THREAD

**Issue by thangpham7793** [prisma/prisma#12182]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull --schema prisma/schema.identity.prisma`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.17.3           | 
| Prisma CLI  | 3.10.0             | 
| Engine      | 73e60b76d394f8d37d8ebd1f8918c79029f0db86| 

## Error
```
Error: [libs/datamodel/connectors/dml/src/model.rs:363:66] called `Option::unwrap()` on a `None` value
```

Seems like this only worked when permission is granted at the table level, not at a column basis.

**Comment by janpio** [comment]
That makes sense.

> Seems like this only worked when permission is granted at the table level, not at a column basis.

Can you elaborate on that a bit maybe? What would be a simple way for us to reproduce this so we can implement a better error message or even avoid the error in the first place?

**Comment by janpio** [comment]
This should be fixed in the next version.
