### ISSUE TITLE
Count action ends up being called aggregate when checking in middleware

### ISSUE THREAD

**Issue by vuki656** [prisma/prisma#12222]
### Bug description

When you use `.count()` on any model, and try to intercept it in the middleware, the name of the action ends up being `aggregate` instead of `count`

### How to reproduce

I created a middlewere that would override the default `count` and count only entities where `isDeleted: false` like so:

```ts
orm.$use(async (parameters, next) => {
    // Override native `count` and only count non soft deleted entities
    if (parameters.action === 'count') {
        parameters.args = {
            where: {
                isDeleted: false,
            },
        }
    }

    return next(parameters)
})
```

Then I call the `count` like so: 
```ts
const foundSectionsCount = await orm.section.count()
```

What I am expecting to happen is the middleware will be triggered since we are calling `count` and it is checking if the action is named `count`.

Instead, it outputs the `action` as `aggregate`.

Here is the `parameters` log like so:

```
action:  {
  args: { select: { _count: [Object] } },
  dataPath: [],
  runInTransaction: false,
  action: 'aggregate',
  model: 'Section'
}
```

Im assuming `count` is using `aggreate` under the hood but I think the action should persist to be called `count` if we are calling `count`. Especially since the type for `action` specifies `count` exists: 

```ts
export type PrismaAction =
  | 'findUnique'
  | 'findMany'
  | 'findFirst'
  | 'create'
  | 'createMany'
  | 'update'
  | 'updateMany'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | '**count**'
  | 'runCommandRaw'
```

### Expected behavior

Since I am calling the `.count()` function, I'm expecting the action in the middleware to also be called `count`.

### Prisma information

This is the model im using in  this example

```prisma
model Section {
    name      String
    number    Int?
    createdAt DateTime @default(dbgenerated("timezone('utc'::text, now())")) @map("created_at") @db.Timestamp(6)
    isDeleted Boolean  @default(false) @map("is_deleted")
    id        String   @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
    items     Item[]

    @@map("sections")
}

```

### Environment & setup

- OS: Ubuntu 20.04
- Database: PostgreSQL
- Node.js version: 14.17.6

### Prisma Version

```
^3.10.0
```

**Comment by ramirorinaldi** [comment]
I have the exact same issue, added the middleware to handle soft deletes and wanted to prevent `count` giving a different number by including them, I hope it gets fixed!

**Comment by joe-giunti-kiefa** [comment]
@vuki656 @millsp I'm curious how you are handling other types of aggregate queries in your middleware, as I'm sure you would also want to exclude soft deleted entries there as well. Why did you think that count needs it's own special case? I think this is actually a bad change that was made because the inputs in the parameters of the middleware function are only valid for an aggregate action. If you try to reconstruct the prisma action from the model, argument, and parameter information like so it is now broken `prisma[modelName][params.action](params.args);`

**Comment by millsp** [comment]
You're right, the args are out of sync with the types. Would you mind creating an issue?
