### ISSUE TITLE
Update the Prisma 2.0 Beta article

### ISSUE THREAD

**Issue by ldub** [prisma/prisma#12228]
### Bug description

This article ranks really highly on SEO when searching for Prisma or Prisma 2 and should be updated near the top of the article to clarify that Prisma 2 is out of beta (and even on version 3 now), just so that people aren't confused when they land on it.

https://www.prisma.io/blog/prisma-2-beta-b7bcl0gd8d8e

### How to reproduce

Google "Prisma 2"

### Prisma information

N/A

### Environment & setup

N/A

### Prisma Version

N/A

**Comment by nikolasburk** [comment]
Hey @ldub, thanks a lot for raising this!

We just updated the intro text with a note that the Prisma ORM is ready for production and are linking to the new announcement article.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/4058327/157833222-32e9bcf6-9f61-44d1-a8a3-c298a82b5f31.png">
