### ISSUE TITLE
Prisma generate fails on big schema file

### ISSUE THREAD

**Issue by RodrigoRomero2308** [prisma/prisma#12221]
### Bug description

Hello, my team has found some problems when using prisma generate in our project. When we run `npx prisma generate` the client responds with an error when stringifying a JSON object, but we can't see much in the error stack.

We tried running prisma generate in the original version of the project (prisma 2.26.0) and with the latest version (3.10.0 at the day of publishing this issue) 

Output when running with version 2.26.0 and DEBUG="*":
```
Environment variables loaded from .env
prisma               : 2.26.0
@prisma/client       : 2.26.0
Current platform     : windows

C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify>dotenv npx prisma generate
  prisma:loadEnv project root found at C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\.env +0ms
[dotenv][DEBUG] "DEBUG" is already defined in `process.env` and will not be overwritten
Environment variables loaded from .env
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using Query Engine Binary at: C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\prisma\query-engine-windows.exe +0ms
  prisma:getDMMF Using Query Engine Binary at: C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\prisma\query-engine-windows.exe +0ms
  prisma:generator baseDir C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\prisma +0ms
  prisma:generator prismaClientDir C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\@prisma\client +1ms
  prisma:GeneratorProcess 2022-03-09T13:09:52.904Z prisma:client:generator requiredEngine: queryEngine +0ms
  prisma:getGenerators neededVersions {        
  "9b816b3aa13cc270074f172f30d6eda8a8ce867d": {
    "engines": [
      "queryEngine"
    ],
    "binaryTargets": []
  }
} +0ms
  prisma:getGenerators {
  prisma:getGenerators   generatorBinaryPaths: {
  prisma:getGenerators     queryEngine: {
  prisma:getGenerators       windows: 'C:\\Users\\Admin\\Desktop\\Proyectos\\tests\\test-prisma-stringify\\node_modules\\prisma\\query-engine-windows.exe'
  prisma:getGenerators     }
  prisma:getGenerators   }
  prisma:getGenerators } +180ms
  prisma:GeneratorProcess 2022-03-09T13:10:02.791Z prisma:loadEnv skipping package.json at C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\.prisma\package.json +10s
  prisma:GeneratorProcess 2022-03-09T13:10:02.792Z prisma:loadEnv skipping package.json at C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\package.json +0ms
  prisma:GeneratorProcess 2022-03-09T13:10:02.793Z prisma:loadEnv project root found at C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\package.json +1ms       
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\.env +0ms
[dotenv][DEBUG] "DEBUG" is already defined in `process.env` and will not be overwritten
Error: Error:
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at respond (C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\@prisma\client\generator-build\index.js:45985:24)
    at LineStream.<anonymous> (C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\@prisma\client\generator-build\index.js:45931:11)


    at _Generate.parse (C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\prisma\build\index.js:65473:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\prisma\build\index.js:110797:18)
```

Output running with version 3.10.0 with DEBUG="*":
```
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv project root found at C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\prisma\query_engine-windows.dll.node +0ms
  prisma:getDMMF Using CLI Query Engine (Node-API) at: C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\prisma\query_engine-windows.dll.node +0ms
  prisma:generator prismaCLIDir C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\prisma +0ms
  prisma:generator prismaClientDir C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\@prisma\client +0ms
  prisma:generator baseDir C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\prisma +1ms
  prisma:generator typescriptPath undefined +2ms
  prisma:GeneratorProcess 2022-03-09T13:17:40.083Z prisma:client:generator requiredEngine: queryEngine +0ms
  prisma:getGenerators neededVersions {        
  "73e60b76d394f8d37d8ebd1f8918c79029f0db86": {
    "engines": [
      "queryEngine"
    ],
    "binaryTargets": []
  }
} +0ms
  prisma:getGenerators {
  prisma:getGenerators   generatorBinaryPaths: {
  prisma:getGenerators     queryEngine: {
  prisma:getGenerators       windows: 'C:\\Users\\Admin\\Desktop\\Proyectos\\tests\\test-prisma-stringify\\node_modules\\prisma\\query-engine-windows.exe'
  prisma:getGenerators     }
  prisma:getGenerators   }
  prisma:getGenerators } +212ms
  prisma:GeneratorProcess 2022-03-09T13:17:49.699Z prisma:loadEnv project root found at C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\package.json +10s
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\.env +0ms
Error: Error: 
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at respond (C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\@prisma\client\generator-build\index.js:54245:22)
    at LineStream.<anonymous> (C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\@prisma\client\generator-build\index.js:54187:9)


    at Object.parse (C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\prisma\build\index.js:107298:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (C:\Users\Admin\Desktop\Proyectos\tests\test-prisma-stringify\node_modules\prisma\build\index.js:108740:18)
```

We will be glad to give you more information if you need it. Thanks for such an amazing ORM

### How to reproduce

1. Create a new npm project
2. Install prisma and prisma client (`npm i prisma` and `npm i -D @prisma/client`)
3. Run `npx prisma generate` with a big schema.prisma file (ours has more than 3400 lines and about 162k characters without spaces)

### Expected behavior

The prisma client should be able to generate the models from our schema

### Prisma information

Unfortunately we can't give you the schema.prisma that we area using right now. We think that with the information we are giving you, it should be possible to reproduce the same error.

The schema.prisma file has about 3400 lines and 162k characters with a total of 136 models in it.

### Environment & setup

We tried with different setups
- OS: Windows 64 bits and Linux (node image in docker)
- Database: PostgreSQL
- Node.js version: v14.17.1, v16.14.0 and v14.19.0

### Prisma Version

Executed npx prisma -v
The project originally uses prisma version 2, we tried with the latest version but we got the same results

Prisma 2.26.0:
```
prisma               : 2.26.0
@prisma/client       : 2.26.0
Current platform     : windows
Query Engine         : query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 9b816b3aa13cc270074f172f30d6eda8a8ce867d
Studio               : 0.408.0
```

Prisma 3.10.0:
```
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0
```

**Comment by janpio** [comment]
I assume this project worked before, correct? What changed about it? Did the schema just get bigger a bit?
We have much bigger schemas in our internal testing, so just creating a schema with this # of lines and models will unfortunately not be enough. Can you share the schema via email (and under NDA) maybe?

**Comment by RodrigoRomero2308** [comment]
Hi Janpio, yes it's correct the project worked before, we had to add new tables due to a use case requirement. It was not a big change, it was two models with few relations. We had the same problem before but the workaround was shortening the relation's names in some models. We can send you a NDA before sharing the schema, where can we send it?

**Comment by janpio** [comment]
Yes of course. I am jan@prisma.io, we can also start from a NDA on our side if that is easier - we have a common template for information sharing cases. Just let me know in the email.

**Comment by RodrigoRomero2308** [comment]
Awesome Jan, I'm sending you an email right now. Thank you

**Comment by RodrigoRomero2308** [comment]
Hi Jan, I've been trying to contact you via email about the NDA, do you have any updates on this?

**Comment by janpio** [comment]
Yes, that I am very bad with email obviously. Sorry, fixed and signed from our side.

**Comment by RodrigoRomero2308** [comment]
As to update the status of this issue, the NDA has been signed and the schema has been shared

**Comment by alexseguin** [comment]
Our team seems to also be getting the same error when running `prisma generate` . 

I just spent a bit of time trying to pinpoint the exact point of failure and I can get it to happen 2 ways:
- By attaching an additional relation to one of our tables that has a large amount of them (the model is almost 500 lines)
  - This is our "contacts" table and we link it to most entities in our system to know who created/updated an entity
- By being in the same state as above (minus the relation that causes a failure) and adding 2 extra models up until I can no longer add anymore models; then adding a few more columns.

Reproduction steps:
- Update DB schema in PSQL into one of the states outline above
- Run `prisma db pull`
- Run `prisma generate`
  - Error happens here

Error I get in both cases:
![image](https://user-images.githubusercontent.com/14806075/164077896-011d764c-0beb-4018-920f-ce972c3e17bd.png)

**Comment by janpio** [comment]
Our capacity to reproduce here currently is limited, but more data is usually better so feel free to email me at jan@prisma.io as well. I will get back to you as soon as possible.

**Comment by alexseguin** [comment]
@janpio 
I've sent you an email with the NDA.

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/8525

**Comment by janpio** [comment]
Hey @alexseguin @RodrigoRomero2308, we investigated this today and could perfectly reproduce the problem. 

We had an obvious presumption on what was going on (our internal representation of the schema was getting to big, and when we call `JSON.stringify` on it it hit some system limit and crashed) - and obviously that turned out to be wrong. Instead there was a surprising way how that representation was used during the `generate` process, where essentially even _more_ data was put to `JSON.stringify` - and that then crashed. So only semi wrong in the end.

Good news is two fold:
1. We know how to fix this. That data was not actually used in its completeness, so we can "just" remove or change it in a future Prisma version and fix this problem.
2. We saw that the Prisma Client **actually gets successfully generated on the file system!** So you should be able to just ignore the error message, and use Prisma Client as you did before. Can you please let us know if this works for you? (That would give us some time to find an elegant solution to the code changes.)

**Comment by alexseguin** [comment]
Thanks for the quick turnaround Jan, I'll run some tests and get back to you.

**Comment by RodrigoRomero2308** [comment]
Hi Jan, great news, we will check this out in a few days to confirm. Thank you so much for your help!

**Comment by janpio** [comment]
Okay, then just to reconfirm: In never versions that slighly modified and bigger schema fails with `Invalid string length` error but then still works, and on some older versions it does not fail and then also works. Correct?

What is happening here is that the length of some internal string (actually a big object of strings) becommes to big to be run through `JSON.stringify`. As we add features with versions, that internal string object also gets bigger - which is why it only fails on never versions. Now, the stringified version of the object is not _actually_ needed in normal cases - including yours, which is why it can still write the Client to disk successfully and then just fails at this additional step.

**Comment by RodrigoRomero2308** [comment]
It failed the generate in both the versions I tried (2.27.0 and 3.10.0). But on both the schema was succesfully generated

**Comment by millsp** [comment]
Hey @RodrigoRomero2308 @alexseguin, we have a fix that has been released on our `dev` npm tag. Would you mind giving it a try and let us know if this fixed your issue? You can try it via `npm i @prisma/client@dev`. Thank you.

**Comment by RodrigoRomero2308** [comment]
Of course! I'll have an update on this soon

**Comment by RodrigoRomero2308** [comment]
It worked! I installed `@prisma/client@dev` and `prisma@dev`

Screenshot:
![image](https://user-images.githubusercontent.com/31521843/167420589-5ae871b8-3d56-416c-b74b-1cdf9c8fb8e4.png)

Output of npx prisma-v:
![image](https://user-images.githubusercontent.com/31521843/167420725-c886b6aa-8a0a-4bde-8e1d-45c591b138eb.png)

**Comment by RodrigoRomero2308** [comment]
Thank you so much to everyone involved in this issue!
