### ISSUE TITLE
CockroachDB: support more autoincrementing integer primary key representations

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#12239]
The "Prisma way" — what we have been doing and documenting so far — of defining an autoincrementing integer primary key looks like this:

```prisma
model A {
  id Int @id @default(autincrement())
}
```

What the `@default(autoincrement())` means is connector-dependent, but usually not too ambiguous.

The CockroachDB connector started from the PostgreSQL connector. We would issue the following statement for the Prisma schema that was just given as an example:

```sql
CREATE TABLE "A" (
  id SERIAL4 NOT NULL PRIMARY KEY
);
```

The problem with this statement is that [SERIAL can mean four different things on cockroachdb](https://www.cockroachlabs.com/docs/v21.2/serial).

We use a session parameter to make sure that the primary keys we create are normalized as `sql_sequence`. There are two reasons behind this:

- It matches the postgresql behaviour,
- but more importantly, it makes sure we have the right size of integers. The other interpretations for `SERIAL` would implicitly make the `Int` (32 bit integer) a `BigInt` (64 bit integer), which breaks both diffing inside the migration engine and the contract represented by the Prisma schema.

Normalizing to a `sql_sequence` is not what is recommended by CockroachDB. In general, uuid primary keys are preferred, but for users who want an autoincrementing integer, [`rowid` is the preferred mechanism](https://www.cockroachlabs.com/docs/v21.2/serial).

## Proposal

We should be able to express at least two of the four ways to interpret `SERIAL`

- We keep the current behaviour for `Int @id @default(autoincrement())` and the session parameter.
- We add `@default(rowid())` with the following rules:
  - The field type must be `BigInt`
  - It must be a single field primary key

## Alternatives

- Do not use the `serial_normalization` session variable, and create sequences ourselves. The problem with that is that it is more complicated, and does not necessarily match what the database would do in the background (think cleaning up the sequence on default drop). The advantage is that we would not depend on a session variable for migrations to behave as expected.
- Go further and support all four types of autoincrementing integer defaults, without relying on the session variable. We may not be able to match exactly what the database normalises to, there, it needs more research.

Forcing the use of the recommended approach with a `BigInt` will not work, because we would not be able to introspect schemas using a sequence with 32 bit integers.

**Comment by rafiss** [comment]
If you would prefer not to rely on the `serial_normalization` setting, another option is to use the `GENERATED ... AS IDENTITY` syntax. That will _always_ result in a column backed by a sequence. 

See:
- https://www.cockroachlabs.com/docs/v21.2/create-table.html#identity-columns
- https://www.postgresql.org/docs/14/sql-createtable.html
