### ISSUE TITLE
Add a Prisma Ignore file to ignore certain tables

### ISSUE THREAD

**Issue by onuralpbicer** [prisma/prisma#12231]
## Problem
In our project we have temporary tables for daily logs before they're offloaded to file storage at the end of the day. Right now, when we do `prisma db pull`, it pulls those tables into the prisma schema as well even though we don't really care about those tables in code. These tables are created and dropped at the beginning and end of each day. 

## Suggested solution
We could have a `.prismaignore` or something file where we can specify a list of relations/items to be ignored when introspecting (and maybe migrating etc too? I haven't tried using prisma migrate so I'm not sure). All of our these types of tables have a consistent naming scheme where it's <tableName>-<todaysDate> format so we can use regex to distinguish those tables.

## Alternatives
I think this is a pretty clean solution tbh, I can't think of any other solutions off the top of my head.

## Additional context
N/A

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/807 + https://github.com/prisma/prisma/issues/8864

Your title refers to "relations" - do you mean tables or Prisma relations(hips)?

**Comment by onuralpbicer** [comment]
@janpio I mean tables, sorry

**Comment by janpio** [comment]
I am not trying to make you use the workarounds in these issues, but suggest that maybe the actual feature request in there is identical or similar to yours. I totally understand that the workarounds mentioned there have limitations and can only potentially be temporarily used until this feature is implemented proper.

If these issues do describe your problem, it might be better for you to leave a 👍 there and write a comment with your specific use case (which indeed is different with the daily created tables and has not been mentioned before!) and clsoe this one.

**Comment by onuralpbicer** [comment]
@janpio No absolutely, I know. I was just thinking out loud (well, over text) that the workarounds might indeed be useful, I did not mean it in a way to imply you were forcing me to use it that way. Apologies if it came across that way. 

And thanks, I will do that.

**Comment by janpio** [comment]
All good, just wanted to make sure you heard what I said and it seems oyu did 👍 Thanks.
