### ISSUE TITLE
Foreign key indexes are not well changed by prisma

### ISSUE THREAD

**Issue by bigTeethLi** [prisma/prisma#12287]
### Bug description

If I initially create a 1:1 relation and then need to change it to a many-to-many relation, the foreign key index does not change from unique to non-unique. And need to drop the table and then re-create, the foreign key index can be updated.

### How to reproduce

1. Create a `1:1 relation`
2. Run `prisma generate && prisma db push`
3. Change the `1:1 relation` to `Many-to-Many relation`
4. Run 'prisma generate && prisma db push'
5. See error, the foreign key is still a unique index
![image](https://user-images.githubusercontent.com/101170394/157794781-89fee53d-3aff-4e34-a49b-14855c000130.png)
6. Then I drop the table and run `prisma generate && prisma db push`, the foreign key can only be changed to non-unique indexes
![image](https://user-images.githubusercontent.com/101170394/157796436-a9cacf29-10ef-4aa1-bd07-ad991f90bf3e.png)

### Prisma information

1:1 relation(use [Official document example](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations))
```prisma
model Post {
  id         Int                 @id @default(autoincrement())
  title      String
  categories CategoriesOnPosts?
}

model Category {
  id    Int                 @id @default(autoincrement())
  name  String
  posts CategoriesOnPosts?
}

model CategoriesOnPosts {
  post       Post     @relation(fields: [postId], references: [id])
  postId     Int // relation scalar field (used in the `@relation` attribute above)
  category   Category @relation(fields: [categoryId], references: [id])
  categoryId Int // relation scalar field (used in the `@relation` attribute above)
  assignedAt DateTime @default(now())
  assignedBy String

  @@id([postId, categoryId])
}
```
Then change to `Many-to-Many relation`(only "?" to "[]")
```prisma
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by janpio** [comment]
How did you fix this problem @bigTeethLi?

**Comment by janpio** [comment]
Duplicate at https://github.com/prisma/prisma/issues/12288
