### ISSUE TITLE
Generator output `client` leads to `Error: ENOENT: no such file or directory, open '.../node_modules/@prisma/client/schema.prisma'`

### ISSUE THREAD

**Issue by xygengcn** [prisma/prisma#12295]
### Bug description

If you set the value of output, the following things will happen. If you do not set, the program is normal。

please  help

### How to reproduce

i can set output in new version

### Expected behavior

```
Error: ENOENT: no such file or directory, open '/Users/xxx/Program/prisma/node_modules/@prisma/client/schema.prisma'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at new LibraryEngine (/Users/xxx/Program/prisma/prisma/client/runtime/index.js:35468:41)
    at PrismaClient.getEngine (/Users/xxx/Program/prisma/prisma/client/runtime/index.js:40266:16)
    at new PrismaClient (/Users/xxx/Program/prisma/prisma/client/runtime/index.js:40241:29)
    at Object.<anonymous> (/Users/xxx/Program/prisma/src/models.ts:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/Users/xxx/Program/prisma/node_modules/ts-node/src/index.ts:1459:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/xxx/Program/prisma/node_modules/ts-node/src/index.ts:1462:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/xxx/Program/prisma/node_modules/@prisma/client/schema.prisma',
  clientVersion: '3.11.0-integration-mobc-fix.1'
}
```

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  output   = "client". // If not, it is normal
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: 
- Mac
- Database: 
- Mysql
- Node.js version: 
- 16.8.0

### Prisma Version

```
prisma                  : 3.11.0-integration-mobc-fix.1
@prisma/client          : 3.11.0-integration-mobc-fix.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine ca9fb922c8fd66aa105fe549629891efc4219ca3 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli ca9fb922c8fd66aa105fe549629891efc4219ca3 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core ca9fb922c8fd66aa105fe549629891efc4219ca3 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt ca9fb922c8fd66aa105fe549629891efc4219ca3 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : test-mobc-fix-ca9fb922c8fd66aa105fe549629891efc4219ca3
Studio                  : 0.458.0
```

**Comment by janpio** [comment]
Do I understand correctly that setting an `output` property for your `generator` block breaks something?
Where exactly do you get this error message?

**Comment by xygengcn** [comment]
@janpio   yes，3.10.0、3.11.0、3.9.0 also happen，this error message will appear after i run script `npm run dev`。

**Comment by janpio** [comment]
This is unexpected, as this functionality is probably used by many people and no one has reported this before.

Does this also happen when you create a new project with `npx prisma init`? If so, please put it on GitHub and post the link so we can reproduce.

**Comment by xygengcn** [comment]
> This is unexpected, as this functionality is probably used by many people and no one has reported this before.
> 
> Does this also happen when you create a new project with `npx prisma init`? If so, please put it on GitHub and post the link so we can reproduce.

here reproduce link  [https://github.com/xygengcn/prisma-demo](https://github.com/xygengcn/prisma-demo), thanks

**Comment by janpio** [comment]
I can confirm the problem:

```
C:\Users\Jan\Documents\throwaway\12295>npm install

added 21 packages, and audited 22 packages in 17s

found 0 vulnerabilities

C:\Users\Jan\Documents\throwaway\12295>npm run dev

> dev
> ts-node ./script.ts

Error: ENOENT: no such file or directory, open 'C:\Users\Jan\Documents\throwaway\12295\node_modules\.prisma\client\schema.prisma'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at new LibraryEngine (C:\Users\Jan\Documents\throwaway\12295\prisma\client\runtime\index.js:36082:40)
    at PrismaClient.getEngine (C:\Users\Jan\Documents\throwaway\12295\prisma\client\runtime\index.js:40406:16)
    at new PrismaClient (C:\Users\Jan\Documents\throwaway\12295\prisma\client\runtime\index.js:40377:29)
    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\12295\script.ts:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (C:\Users\Jan\Documents\throwaway\12295\node_modules\ts-node\src\index.ts:1459:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Jan\Documents\throwaway\12295\node_modules\ts-node\src\index.ts:1462:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Jan\\Documents\\throwaway\\12295\\node_modules\\.prisma\\client\\schema.prisma',
  clientVersion: '3.9.1'
}
```

(Also with 3.10.0)

**Comment by xygengcn** [comment]
> I can confirm the problem:
> 
> 
> 
> ```
> 
> C:\Users\Jan\Documents\throwaway\12295>npm install
> 
> 
> 
> added 21 packages, and audited 22 packages in 17s
> 
> 
> 
> found 0 vulnerabilities
> 
> 
> 
> C:\Users\Jan\Documents\throwaway\12295>npm run dev
> 
> 
> 
> > dev
> 
> > ts-node ./script.ts
> 
> 
> 
> Error: ENOENT: no such file or directory, open 'C:\Users\Jan\Documents\throwaway\12295\node_modules\.prisma\client\schema.prisma'
> 
>     at Object.openSync (node:fs:585:3)
> 
>     at Object.readFileSync (node:fs:453:35)
> 
>     at new LibraryEngine (C:\Users\Jan\Documents\throwaway\12295\prisma\client\runtime\index.js:36082:40)
> 
>     at PrismaClient.getEngine (C:\Users\Jan\Documents\throwaway\12295\prisma\client\runtime\index.js:40406:16)
> 
>     at new PrismaClient (C:\Users\Jan\Documents\throwaway\12295\prisma\client\runtime\index.js:40377:29)
> 
>     at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\12295\script.ts:3:16)
> 
>     at Module._compile (node:internal/modules/cjs/loader:1103:14)
> 
>     at Module.m._compile (C:\Users\Jan\Documents\throwaway\12295\node_modules\ts-node\src\index.ts:1459:23)
> 
>     at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
> 
>     at Object.require.extensions.<computed> [as .ts] (C:\Users\Jan\Documents\throwaway\12295\node_modules\ts-node\src\index.ts:1462:12) {
> 
>   errno: -4058,
> 
>   syscall: 'open',
> 
>   code: 'ENOENT',
> 
>   path: 'C:\\Users\\Jan\\Documents\\throwaway\\12295\\node_modules\\.prisma\\client\\schema.prisma',
> 
>   clientVersion: '3.9.1'
> 
> }
> 
> ```
> 
> 
> 
> (Also with 3.10.0)
> 
> 
> 
> 

yes，also 3.11.0 dev

**Comment by janpio** [comment]
I just saw that you updated `script.ts` to explicitly import from `.prisma/client` (the automated `output` location): https://github.com/xygengcn/prisma-demo/commit/d3e5db149a83d9b5042b29b2a9620028a5366bea#diff-c6eac5fc4d0b2420ef79cb73faa8d97d0842729c1292d60fa9e6c48e252d4818R1 If you undo that change, all `generator.output` values should work again. Can you please confirm?

**Comment by janpio** [comment]
This seems to be a special case when the `output` value is exactly `client`. When I set any other value (e.g. `foo`) and update the import in my `script.ts` to `import { PrismaClient } from './prisma/foo'` to reflect that, everything works as expected.

Can you confirm?

**Comment by xygengcn** [comment]
> 

Yeath！ Using foo instead of client，everything works as expected.

**Comment by janpio** [comment]
Thanks. We will treat this as a bug, I updated the issue title to make it easier to understand.

**Comment by millsp** [comment]
Closing as already fixed in latest releases.
