### ISSUE TITLE
Support SAP HANA DB (Cloud)

### ISSUE THREAD

**Issue by beejei** [prisma/prisma#12323]
Hello Prisma core contributors!

I'm so glad to see this super versatile framework. I develop applications against SAP HANA DB with Node.js.
Since SAP is enlarging enterprise business to the cloud (HANA Cloud), and most of SAP applications are running on Cloud landscape, we definitely requires a graceful way to define schema and maintain among multiple DB instances.

It would be really nice if Prisma will support an option to choose HANA DB as a Database even though the functionality is limited.
You could start from [HANA Client](https://www.npmjs.com/package/@sap/hana-client) and  [HANA Cloud Free-tier](https://developers.sap.com/tutorials/hana-cloud-mission-trial-1.html)

It would be also very thankful if you share any starting point when considering contribution for a new database.

Thanks and best regards,
Beejei

**Comment by beejei** [comment]
Just one more update. As HANA Client is based on native c++ build driver, and it doesn't support Apple Silicon M1 yet, [using node-hdb](https://github.com/SAP/node-hdb) might be better choice for ease of development.

**Comment by philipphaeusle** [comment]
Hello together!

Is there any progress or planned work on this feature? 

Best,
Philipp

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
