### ISSUE TITLE
Introspection: MongoDB: Warnings mention Native Types instead of PSL types (e.g. Document instead of Json)

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#12321]
Now that we use `Json` for properties with different types, we might want to tweak the language used in the comment and CLI warning:

Example 1, (since Json is picked as default with [engine PR](https://github.com/prisma/prisma-engines/pull/2763))
```
      // *** WARNING ***
      // 
      // The following fields had data stored in multiple types. Either use Json or normalize data to the wanted type.
      // - Model "users", field: "numberOrString1", chosen data type: "Document"
      // - Type "UsersHobbies", field: "numberOrString2", chosen data type: "Document"
      // - Type "UsersHobbiesObjects", field: "numberOrString3", chosen data type: "Document"
```

Here for the field `field: "numberOrString3"` the `chosen data type` is `Document` but the type in the `schema.prisma` file will be `Json`

See `db pull` test https://github.com/prisma/prisma/blob/755d81b2e290789bcb301e513044bd7d54e5d92f/packages/migrate/src/__tests__/DbPull.test.ts#L752-L807

Example 2 (Before the default changed to Json)
```
// *** WARNING ***
// 
// The following fields had data stored in multiple types. The most common type was chosen. If loading data with a type that does not match the one in the data model, the client will crash. Please see the issue: https://github.com/prisma/prisma/issues/9654
// - Model "shipwrecks", field: "depth", chosen data type: "Int32"
// 
```

Here for the field `field: "depth"` the `chosen data type` is `Int32` but the type in the `schema.prisma` file will be `Int`

See https://github.com/prisma/introspection-ci/blob/4c4b4f7aeaa5d0eea96d4a3d00630c8a52b3e3f9/introspection-analysis/output/mongodb_public/sample_geospatial_stderr.log

Internal thread https://prisma-company.slack.com/archives/C4GCG53BP/p1647246722174479

MongoDB data
```
[
  {
    "name": "Jane Smith",
    "email": "1@prisma.io",
    "admin": true,
    "numberOrString1": 1234,
    "hobbies": [
      {
        "name": "Swimming",
        "tags": ["tag"],
        "numberOrString2": 1234,
        "objects": [
          {
            "name": "Object 1",
            "tags": ["tag"],
            "numberOrString3": 1234
          }
        ]
      }
    ]
  },
  {
    "name": "John Smith",
    "email": "2@prisma.io",
    "admin": false,
    "numberOrString1": "567",
    "hobbies": [
      {
        "name": "Running",
        "tags": ["tag"],
        "numberOrString2": "567",
        "objects": [
          {
            "name": "Object 1",
            "tags": ["tag"],
            "numberOrString3": "567"
          }
        ]
      },
      {
        "name": "Coding",
        "tags": ["tag"]
      }
    ]
  }
]
```

Note: introspection-ci results when default changed to Json https://github.com/prisma/introspection-ci/commit/b362f3e9ab0361a9b9efa96c382359303273cc4d

**Comment by janpio** [comment]
We can probably remove the "chosen data type" inforamtion from the CLI warning completely, the introduction of the list mentions that already and can be improved to be more readable. (We can also create documentation how to proceed from there to fix the data and be able to change the schema to one of the existing data types.)

**Comment by Jolg42** [comment]
That would be very easy to change

**Comment by janpio** [comment]
I think that would fix the concrete problem in the CLI.
It would still leave the MongoDB types in the comment we render to the schema, but we should track that separately in a new issue (and also work on it, but independently)

**Comment by janpio** [comment]
Ok, seems we went with changing the actual returned data type string instead:
```diff
// The following fields had data stored in multiple types. Either use Json or normalize data to the wanted type.
- // - Type "MoviesImdb", field: "rating", chosen data type: "Document"
- // - Type "MoviesImdb", field: "votes", chosen data type: "Document"
+ // - Type "MoviesImdb", field: "rating", chosen data type: "Json"
+ // - Type "MoviesImdb", field: "votes", chosen data type: "Json"
```
