### ISSUE TITLE
naming a model `Datasource` breaks generated return types

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma#12332]
### Bug description

naming a model `Datasource` will conflict with the generated `Prisma.Datasource` type which I assume is related to the `datasource` block in the `schema.prisma`.

Query results of type `Prisma.Datasource` will only have `url` property.

### How to reproduce

generate a Prisma Client that has a `Datasource` model.

```prisma
model Datasource {
  id Int @id @default(autoincrement())
}
```

types generated incorrectly

<img width="617" alt="image" src="https://user-images.githubusercontent.com/32459922/158256669-d50955c9-8271-4a80-85b0-6cd037b916e7.png">

### Prisma information

```prisma
model Datasource {
  id Int @id @default(autoincrement())
}
```

generated model type
```ts
/**
 * Model Datasource
 * 
 */
export type Datasource = {
  id: number
}
```

generated type further down in `index.d.ts`
```ts
export type Datasource = {
  url?: string
 }
```

### Environment & setup

- OS: confirmed on MacOS 12.3
- Database: generated with Postgres provider
- Node.js version: 17.7.1

### Prisma Version

```
3.10
```

**Comment by austincrim** [comment]
theoretically, the same could happen with any of our generated, exported types, right? `Middleware`, `LogLevel`, etc.

**Comment by janpio** [comment]
That would be one solution, yes. But for now this issue just tracks the problem, and the Client team can look into if it is possible to remove this limitation and clash somehow. We did so in the past for some of the terms.

**Comment by Jolg42** [comment]
Note: We have a Denylist in 2 places, we could update them:
https://github.com/prisma/prisma/blob/main/packages/client/src/generation/generateClient.ts#L344-L421
https://github.com/prisma/prisma-engines/blob/main/libs/datamodel/parser-database/src/names/reserved_model_names.rs#L38-L87

**Comment by Jolg42** [comment]
Note that it would be better to avoid the conflict and not add more entries to the denylist
