### ISSUE TITLE
[CLI] Review exit code behaviour of CLI commands

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#12349]
Migrate status still returns a 0 exit code even though a clearly defined error is returned (P1000 failed to connect to db in my case). We should change the code to non-zero.

We should also review the behaviour of the other CLI commands.

**Comment by Jolg42** [comment]
Related issues so far
https://github.com/prisma/prisma/issues/9786
https://github.com/prisma/prisma/issues/10265

**Comment by AndrewSouthpaw** [comment]
Can confirm I just bumped into this issue as well. Here's my context:

I have a CLI I'm building with `oclif`, to add additional help for my team in interacting with the DB. We have our local DB, but we also have a test DB. In my `db:migrate` CLI command, I first want to migrate the local dev DB, and then reset the test DB. However, if the person cancels the local dev DB migration (e.g. they're prompted to reset and they decline), I don't want to proceed. I was expecting a cancelled reset to return an exit code of `1`, but it's `0`.

In case it's helpful to hear about use cases! I'm not sure what other workarounds would be present here.

**Comment by Jolg42** [comment]
Thank you @AndrewSouthpaw for your detailed feedback 👍🏼

**Comment by shayneczyzewski** [comment]
Hi gang! I will +1 this initiative. I work at Wasp, where we are building a simple DSL for developing full-stack web apps with less code. We use Prisma in our stack and really like it! :) We also use the Prisma CLI under the covers in our Wasp CLI. One thing we want to do next is to check the status of our users' DB when we generate the web app and warn them if they should migrate.

Some commands, like `prisma migrate diff` have an `--exit-code` flag, which is super helpful when programmatically invoking it. Other commands, like `prisma status`, do not offer this (nor does it even return 1 on error), which means we have to parse stdout output, making it both error-prone and fragile. (Aside: I would use diff to check if migrations needed to be applied, but I would rather not have to deal with the shadow database stuff.)

I'd love to see `--exit-code` make its way to other commands, (selfishly) starting with `prisma status`. But even just getting success/error (0/1) working for all commands would be a huge step in the right direction for programmatic invocation! :D

Thanks, and keep up the great work!

**Comment by Jolg42** [comment]
Tested with `4.3.0-dev.27`

| Command | Success | Error | Notes |
| --- | --- | --- |  --- |
| `format` | 0 | 1 (e.g. schema validation error) |
| `generate` | 0 | 1 (e.g. schema validation error) |
| `init` | 0 | 1 (e.g.: prisma folder already exists error) |
| `studio` | 0 | ? | after Studio starts the error is only printed, no process exit
| `validate` | 0 | 1 (e.g. schema validation error) |
| `version` | 0 | 1 (for E_CANNOT_RESOLVE_VERSION) |
| `db execute` | 0 | 1 (e.g. missing arg, file not found, error from Migrate) |
| `db pull` | 0 | 1 (e.g. can't connect, database is empty) | 
| `db push` | 0 | 1 | if interactive warning prompt is cancelled -> 0
| `db seed` | 0 | 1 (e.g. not configured or error in script) |
| `migrate deploy` | 0 | 1 (e.g. error from Migrate) |
| `migrate dev` | 0 | 1 (e.g. schema validation error, error during generate, error from Migrate) | if interactive reset prompt is cancelled -> 0. if seed errors -> 0. 
| `migrate diff` | 0 | 1 (e.g. missing arg, db doesn't exist, can't read schema) | Default: Success: 0, Error: 1. with `--exit-code`: Empty: 0, Error: 1, Not empty: 2.
| `migrate reset` | 0 | 1 (e.g. failed migration, error during seeding, error during generate) | if interactive reset prompt is cancelled -> 0. if seed errors -> 1. 
| `migrate resolve` | 0 | 1 (e.g. missing arg, error from Migrate, cannot find migration...) |
| `migrate status` | 0 | 1 (e.g. can't connect) | if failed migration found -> 0 & if auth error -> 0 ⚠️ 

Observations:
1. Studio, when an error occurs, does not exit.
1. We have a different behavior for the error exit code between `migrate dev` and `migrate reset`, dev will exit 0, while reset 1 if there is an error during seeding
1. `migrate status` returns 0 in unexpected situation like
	- when a failed migration is found
	- `P1000: Authentication failed against database server at localhost`

**Comment by shayneczyzewski** [comment]
This is a great table, @Jolg42! One area where adding `--exit-code` may make sense for `migrate status` (similar to `diff`) is communicating if there is nothing/something left to migrate. So you'd have success / failure / are all migrations applied? (or does DB == migrations dir, or something to that effect, but mainly a 3rd distinct piece of info that the command actually is trying to convey). And then success and failure are not overloaded and CLI invocation can determine the logical status like the user reading the text.

**Comment by Jolg42** [comment]
Here is 
- the issue about `migrate status` https://github.com/prisma/prisma/issues/14860
- the issue about `studio` https://github.com/prisma/prisma/issues/14861
- the issue about `migrate dev` https://github.com/prisma/prisma/issues/14862

**Comment by Jolg42** [comment]
@shayneczyzewski We decided to treat `migrate status` behavior as a bug fix, it now exits with an error code in our internal dev version `4.3.0-dev.56` and up, and will be part of the 4.3.0 release.
See details in https://github.com/prisma/prisma/issues/14860
Does that fully cover what you expected? Thanks for mentioning this :)

**Comment by shayneczyzewski** [comment]
> 

Hi @Jolg42 awesome, I think this should help with programmatic invocation, thanks! The only future improvement with adding `--exit-code` to commands like these is disambiguating connection errors and the like (ret 1) vs more specific contextual errors (like failed migrations ret 2, unapplied ret 3, unmanaged ret 4). But that could get tedious for ya'll is more of a nice to have, this is already a great step for our use case, so thanks! 👍🏻

**Comment by Jolg42** [comment]
Docs issue at https://github.com/prisma/docs/issues/3830

**Comment by Jolg42** [comment]
@shayneczyzewski I created this issue about having more exit codes
https://github.com/prisma/prisma/issues/15587

Feel free to add some use cases, it will definitely be interesting to have ✍🏼

**Comment by shayneczyzewski** [comment]
> @shayneczyzewski I created this issue about having more exit codes for `migrate status` #15587
> 
> Feel free to add some use cases, it will definitely be interesting to have ✍🏼

Sounds good, will add to it as time allows! Thanks for creating it!
