### ISSUE TITLE
Postgres fulltext search - Cannot query tsvector column with $queryRaw

### ISSUE THREAD

**Issue by joshribakoff-sm** [prisma/prisma#12344]
### Bug description

 Raw query failed. Code: `N/A`. Message: `error deserializing column 7: cannot convert between the Rust type `core::option::Option<alloc::string::String>` and the Postgres type `tsvector`

### How to reproduce

```ts
const res =
        await prisma.$queryRaw`SELECT * from products where label @@ to_tsquery(${search})`;
      console.log(res);
```

### Expected behavior

should work

### Prisma information

`label Unsupported("tsvector")? @default(dbgenerated("''::tsvector"))`

### Environment & setup

- OS: Mac
- Database: PostgreSQL
- Node.js version: 16

### Prisma Version

```
3.10
```

**Comment by joshribakoff-sm** [comment]
I also tried:

```ts
await prisma.$queryRaw`SELECT * from products where indexed_label @@ to_tsquery('${search}')`;
```

and now I get:

```
 Your raw query had an incorrect number of parameters. Expected: `0`, actual: `1`.',
  locations: [ { line: 2, column: 2 } ]
```

**Comment by joshribakoff-sm** [comment]
If I change `SELECT *` to `SELECT id` it does work :)

**Comment by Weakky** [comment]
Hey @joshribakoff-sm,

Am I understanding correctly that you were attempting to _select_ a column that was of type `tsvector`? If so, while we agree this is inconvenient, it is expected that it doesn't work since `tsvector` is not part of our officially supported types, [as documented here](https://www.prisma.io/docs/concepts/database-connectors/postgresql#native-type-mappings)

**Comment by Weakky** [comment]
Better documentation around `Unsupported` and query raw might be needed indeed! That being said, if having a `tsvector` as `string` is helpful in your case, nothing should prevent you from casting your column as `text`. This should bring you a similar behavior than `node-postgres`.

**Comment by Weakky** [comment]
Hey @joshribakoff-sm,

I'm closing your issue in favor of #13203 as it's not technically a bug + we had several duplicates.
This issue explains the available workarounds and proposes solutions.

Thanks for reporting 🙏
