### ISSUE TITLE
Prisma `migrate diff` just crashed. 

### ISSUE THREAD

**Issue by codymihai** [prisma/prisma#12351]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`migrate diff --from-schema-datamodel=prisma/schema.prisma --to-url=mysql://root:password@localhost:3306/covia --preview-feature --script`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v17.4.0            | 
| Prisma CLI  | 3.9.2              | 
| Engine      | bcc2ff906db47790ee902e7bbc76d7ffb1893009| 

## Error
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_renderer/mysql_renderer.rs:282:81] called `Option::unwrap()` on a `None` value

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by tomhoule** [comment]
Context: this unwrap is failing.

```rust
    fn render_drop_foreign_key(&self, foreign_key: &ForeignKeyWalker<'_>) -> String {
        format!(
            "ALTER TABLE {table} DROP FOREIGN KEY {constraint_name}",
            table = self.quote(foreign_key.table().name()),
            constraint_name = Quoted::mysql_ident(foreign_key.constraint_name().unwrap()),
        )
    }
```

So we have a foreign key without a constraint name. That should be possible for us to track and address.

**Comment by janpio** [comment]
Can you confirm this might be the case in your database @codymihai?

**Comment by tomhoule** [comment]
(note that the missing constraint name could be something wrong in Prisma code)

**Comment by codymihai** [comment]
@janpio what basically I want to do is:
I've migrated everything from prisma 1 to primsa 2 on my local machine and also on a dev env and now I dumped the production database which uses the primsa 1 and I want to get all sql queries necessary(or the diff) between the prisma 2 schema and the old prisma 1 database
