### ISSUE TITLE
`TypeError: at normalizeAndValidateHeaderValue` with data proxy in cloudflare workers/miniflare

### ISSUE THREAD

**Issue by clintonwoo** [prisma/prisma#12356]
### Bug description

Client is bugged in my closed source project but also in this open source project I found it so using that as an example.

When using Prisma Data Proxy in Cloudflare Workers with `prisma` 3.10.0 and `miniflare` 2.3.0 (also using `remix` 1.2.3 but probably not related) an error occurs when making any request since the `transactionId` header is passed as undefined in prisma causing a header normalization error (since undefined isn't a valid header).

### Workaround

I've managed to fix the error locally by modifying line 93 col 13582 of `node_modules/@prisma/client/runtime/proxy.js` to be `const headers={...n};if(typeof t=="string"&&r){headers.transactionId= t}return{inTx:typeof t=="number"&&r?!0:void 0,headers}` instead of `return{inTx:typeof t=="number"&&r?!0:void 0,headers:{transactionId:typeof t=="string"&&r?t:void 0,...n}` since in the bugged code the `transactionId` header will be undefined if not present, thus causing the `normalizeAndValidateHeaderValue` error.

### How to reproduce

1. Go to https://github.com/marcomafessolli/remix-prisma-cloudflare-workers/tree/d86bb949016ce35f805ab113f4df89f3e96b3644 (hard link for current point in time of master branch)
2. Git clone that project
3. Follow the steps to run the project (add an .env, `npm i`, `PRISMA_CLIENT_ENGINE_TYPE=dataproxy npx prisma generate` and create your prisma data proxy project if not already using one)
4. Run `npm run dev`
5. Open the root index page for the website (only one page exists).
6. See error

### Expected behavior

```
TypeError:
[dev:*worker]     at normalizeAndValidateHeaderValue (`<PATH>/remix-prisma-cloudflare-workers/node_modules/undici/lib/fetch/headers.js:42:11`)
[dev:*worker]     at HeadersList.append (`<PATH>/remix-prisma-cloudflare-workers/node_modules/undici/lib/fetch/headers.js:98:29`)
[dev:*worker]     at fill (`<PATH>/remix-prisma-cloudflare-workers/node_modules/undici/lib/fetch/headers.js:86:15`)
[dev:*worker]     at new Request (`<PATH>/remix-prisma-cloudflare-workers/node_modules/undici/lib/fetch/request.js:433:9`)
[dev:*worker]     at new Request (`<PATH>/remix-prisma-cloudflare-workers/node_modules/@miniflare/core/src/standards/http.ts:407:13`)
[dev:*worker]     at upgradingFetch (`<PATH>/remix-prisma-cloudflare-workers/node_modules/@miniflare/web-sockets/src/fetch.ts:20:19`)
[dev:*worker]     at WebSocketPlugin.<anonymous> (`<PATH>/remix-prisma-cloudflare-workers/node_modules/@miniflare/core/src/standards/http.ts:895:21`)
[dev:*worker]     at fetch (`<PATH>/remix-prisma-cloudflare-workers/node_modules/@miniflare/web-sockets/src/plugin.ts:51:28`)
[dev:*worker]     at request (`<PATH>/remix-prisma-cloudflare-workers/node_modules/@prisma/client/runtime/proxy.js:25:12296`)
[dev:*worker]     at Object.requestInternal (`<PATH>/remix-prisma-cloudflare-workers/node_modules/@prisma/client/runtime/proxy.js:27:285`)
```

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb", "dataProxy"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  id    String  @id @default(auto()) @map("_id") @db.ObjectId
  email String  @unique
  name  String?
}

model Log {
  id      String @id @default(auto()) @map("_id") @db.ObjectId
  level   Level
  message String
  meta    Json
}

enum Level {
  Info
  Warn
  Error
}
```

### Environment & setup

OS: Windows using Fedora 35 via wsl2
Database: PostgreSQL
Miniflare: 2.3.0
Prisma: 3.10.0

### Prisma Version

3.10.0

**Comment by juhanakristian** [comment]
I'm running into the same issue developing a Remix app with Cloudflare Pages, Prisma, and Planetscale.

**Comment by pantharshit00** [comment]
Thanks for the reproduction. I can reproduce the issue.

**Comment by Hebilicious** [comment]
Thanks @clintonwoo for providing a solution.  I banged my head against the wall for way too long before stumbling onto this repo https://github.com/BrunoAzzi/skeletor-cloudfare which referred to this issue.
The issue is still here in 3.12.0.

**Comment by mkuchak** [comment]
Same thing here. I also banged my head for a long time until I found this issue.

The problem has nothing to do with Remix, as I started an empty project and went through the same situation.

@clintonwoo's interim solution works fine locally.

**Comment by JoeMethven** [comment]
Is there any update on when a real fix might be available?

**Comment by ZetraDev** [comment]
I also having problem when using prisma@3.12.0 with remix@1.4.1, but with another error which is `Error: PrismaClient is unable to be run in the browser.`
but I already check that the client is only imported for server side (**.server.ts)

**Comment by aiji42** [comment]
@ZetraDev 
To use prisma with Remix with cloudflare as runtime, several steps need to be cleared in addition to the bug reported in this issue.
- Run `prisma generate` with environment variables (`PRISMA_CLIENT_ENGINE_TYPE=dataproxy`)
- Import cjs module for `@prisma/client` preferentially. (If you select cloudflare in remix, the bowser module is imported preferentially.)
- Polyfill global buffer

If you get past these three steps, you will get `TypeError: at normalizeAndValidateHeaderValue`.

https://github.com/aiji42/remix-esbuild-override/tree/main/examples/prisma-cloudflare

**Comment by ZetraDev** [comment]
after i follow the step, i get the same error, but wrangler start log a warning
```
[dev:*wrangler] Compiling worker to "C:\Users\Administrator\Local\Temp\functionsWorker.js"...
[dev:*wrangler] ▲ [WARNING] Using direct eval with a bundler is not recommended and may cause problems
[dev:*wrangler]
[dev:*wrangler]     functions/[[path]].js:17136:20:
[dev:*wrangler]       17136 │         let https = eval("require('https')"), request = https.r...
[dev:*wrangler]             ╵                     ~~~~
[dev:*wrangler]
[dev:*wrangler]   You can read more about direct eval and bundling here: https://esbuild.github.io/link/direct-eval
```
how can i solve it?

**Comment by aiji42** [comment]
@ZetraDev
https://github.com/remix-run/remix/issues/667#issuecomment-1103936222
Although it is bundled, it is code that is not actually executed and can be ignored.

**Comment by ZetraDev** [comment]
ok, thank you so much for helping me

**Comment by JoeMethven** [comment]
@ZetraDev you need to pull prisma through cloudflare context. This personexample helped me: 

```
import { getClient } from './app/utils/prisma.server';

const handleRequest = createPagesFunctionHandler({
	build,
	mode: process.env.NODE_ENV,
	getLoadContext: ({ data, env }) => {
            ...
            return {
			data: {
				sessionStorage, authenticator, prisma: getClient()
			},
			env
		}
         ...
```

**Comment by ZetraDev** [comment]
pull prisma through cloudflare context still getting error

**Comment by kettanaito** [comment]
This is still an issue, and it's related to Prisma violating the header value policy in Node.js.

As the error message suggests, Undici throws when a request header value is `undefined`. 

You can see this check implemented [here](https://github.com/nodejs/undici/blob/bf6d5a14617bc53a9d3a3b9f81ddaaa8a1247e13/lib/fetch/headers.js#L23-L25). `undefined` as a header value is considered unexpected as if you had a mistake of handling the value before assigning it to a header. 

I don't know about your case but when I inspect which header throws, I see that it's the `transactionId` header that Prisma sets conditionally. By allowing that header value to be `undefined`, Prisma is not complying with the header value policy set by Undici (and Node.js, when using `http`). 

https://github.com/prisma/prisma/blob/a7b02ca3f1d13467cdd3cc545249840d67c60791/packages/client/src/runtime/getPrismaClient.ts#L157

Internally, the transaction ID is a simple increment that increases with each transaction done by Prisma. Can we safely state that it cannot be `undefined` and provide a sensible initial value so this issue doesn't happen?

**Comment by millsp** [comment]
Hey @kettanaito, we have released this fix a few minutes ago in [3.15.0](https://github.com/prisma/prisma/releases). I can confirm that I could get the reproduction working again, and the warnings around `eval` are also gone. tl;dr;
* Instead of `PRISMA_CLIENT_ENGINE_TYPE`, use `prisma generate --data-proxy` to enable the Data Proxy
* `import { PrismaClient } from '@prisma/client/edge'` for a Workers-compatible Prisma Client

**Comment by kettanaito** [comment]
Thank you, @millsp, for such a quick response. 

I can confirm the issue is fixed with 3.15.0. I did, however, have to add some additional changes to the build pipeline of my Cloudflare worker for the newest version of Prisma to function:

```diff
alias({
// This resolves to "@prisma/client/runtime/index.js" which is not
// suitable for workers anymore (for some reason). It depends on Node
// standard library, which won't evaluate in the worker's context.
- '@prisma/client': require.resolve('@prisma/client'),
+ '@prisma/client': require.resolve('@prisma/client/edge.js'),
}),
```

Switching to the `/edge.js` import resolution seems to work.

**Comment by millsp** [comment]
You should be able to fully remove this alias and just replace your `@prisma/client` import with `@prisma/client/edge`.

**Comment by kettanaito** [comment]
Oh, I didn't know that. Thanks, will update the imports 👍
