### ISSUE TITLE
`prisma init --datasource-provider=cockroachdb --url ...` sets provider to `postgresql`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#12360]
Note: `--datasource-provider` is not read if `--url`  is passed.

There is an edge case not handled here for cockroachdb urls which will be added with `postgresql` provider (since they start with `postgresql://`)

Using `--datasource-provider=cockroachdb` will work, but with an example url instead of what is supplied via `--url`.

We should probably open that up to allow setting it.

Maybe also document that `--url` leads to it trying to auto detect.

**Comment by janpio** [comment]
Confirmed manually 🥳
