### ISSUE TITLE
MDBGA: Check that our queries separate a MongoDB `null` from a MongoDB `undefined`

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#12361]
Placeholder issue for a discussion around https://github.com/prisma/prisma/issues/7368.

We didn't really account for both undefined and null being possible values in a MongoDB database. We should go through our operations and make sure what's returned makes sense.

```ts
prisma.product.findMany({
  photos: {
    some: {
      url: undefined
    }
  }
})
```

vs. 

```ts
prisma.product.findMany({
  photos: {
    some: {
      url: null
    }
  }
})
```

For MongoDB, this may lead us to diverging from our previous pattern of `undefined` meaning not sent to the query engine.

**Comment by Weakky** [comment]
Closed by https://github.com/prisma/prisma-engines/pull/2767
