### ISSUE TITLE
Re-evaluate and -confirm supported native types on MongoDB

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#12382]
We do not have a consistent story on what native types we support on mongodb:

- We have two lists of native types in engines (the most relevant being [this one](https://github.com/prisma/prisma-engines/blob/main/libs/native-types/src/mongodb.rs))
- Something else in docs: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#mongodb-preview
- And that does not match our mental model of them.

## What should we do?

- [x] Examine the existing lists
- [x] Figure out what we actually want
- [ ] Propose and discuss changes (if necessary)
- [ ] Implement and document changes (if necessary)

**Comment by dpetrick** [comment]
The first list you linked (engines one) is the only one that matters, all others are simply wrong.

**Comment by janpio** [comment]
We should probably have an equivalent to https://www.prisma.io/docs/concepts/database-connectors/postgresql#type-mapping-between-postgresql-to-prisma-schema on https://www.prisma.io/docs/concepts/database-connectors/mongodb as well so people can find this.

**Comment by janpio** [comment]
Result of examining and figuring out, internal document: https://www.notion.so/prismaio/MongoDB-Native-Types-8c55fadc38a8413cb70948a3ed23ff20
