### ISSUE TITLE
Autogenerate DTO's or Support plugins from thirdpartys

### ISSUE THREAD

**Issue by Manugr21** [prisma/prisma#12399]
## Problem

It get's complex to create DTO's acordingly to  the prisma.schema.

## Suggested solution

Add more support or documentation based on existin plugins from frameworks,
For example in NestJs there is a plugin [vegardit](https://github.com/vegardit/prisma-generator-nestjs-dto)

## Alternatives

Document more examples of how to create DTO's based on schemas.

## Additional context
The current implementation doesn't always work and when you need to fix something or add more code to DTO's its horrible to generate and add code every time.

**Comment by janpio** [comment]
As you listed yourself, there are multiple DTO generators out there already (here is another issue that includes some newer options: https://github.com/prisma/prisma/issues/8334) - this is the way Prima suggests this to be handled in the future as well. 

If someone has concrete suggestions, we are of course happy to hear about those - just open a new issue or discussion. Thank you.
