### ISSUE TITLE
Specify value for Enum

### ISSUE THREAD

**Issue by Vallo** [prisma/prisma#12405]
## Problem

I want to add a custom value to my Enum types so I can easily provide my FE the key/value pairs for Enum types. 
My goal is to define an enum like this:

```
enum AlarmTypes { 
  FIRE_ALARM    @value("Fire alarm ringing")  @map("FIRE")
  SMOKE_VISIBLE @value("Smoke is visible")    @map("SMOKE_V")
  SMOKE_SMELL   @value("Smoke smell present") @map("SMOKE_S")
}
``` 
so it would generate js enums like this

```
export const AlarmTypes: {
  FIRE_ALARM: 'Fire alarm ringing',
  SMOKE_VISIBLE: 'Smoke is visible',
  SMOKE_SMELL: 'Smoke smell present',
}
```

and I will therefore send this const to the FE to pretty-print the options. Then FE during a `create` will send the key (eg: `FIRE_ALARM`) and my BE will do something like
```
import { AlarmTypes } from '@prisma/client'
....
async function createAlarm(body) {
  const key = body.key
  await prisma.alerts.create( { data: { type: AlarmTypes[key] } })
}
```

## Suggested solution

Add a way to set the value of the enums using @value or any decorator.

## Alternatives

I think my only alternative is to not use enums but create a new model `AlarmTypes` that will have a key and value, and seed them with my initial values. The benefit of this approach is that adding a new value does not require a new deploy but an insert. But for values I do not expect to change often, adding a new table per enum seems like an overkill.

## Additional context

If there is a more appropriate solution I am missing please let me know, thanks!
I tried using @map but it does not solve my problem. @map will update the value on DB, but the value on DB should match the key of the enum.

**Comment by janpio** [comment]
Is this maybe a duplicate of https://github.com/prisma/prisma/issues/273?

**Comment by Vallo** [comment]
yes, I missed it, sorry
