### ISSUE TITLE
[MDB] Validate valid field / key names in the datamodel

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#12410]
Mongo has some restrictions around what can be used in key names. We should validate those in the datamodel.

https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names

**Comment by tomhoule** [comment]
I think that's also the case on SQL connectors (there are rules for valid identifiers), where we don't validate either. Should we open issues for the SQL connectors?
