### ISSUE TITLE
MongoDB database, collections and indexes are not created if not exists

### ISSUE THREAD

**Issue by emimarz** [prisma/prisma#12432]
### Bug description

I can connect with an existent MongoDB database but if database doesn't exists prisma don't create it as it says, the same happens with collections also when you create unique fields indexes doesn't create. queries and update work fine but they are not created if exists

### How to reproduce

1. fresh install
2. create model
3. connect with an existent mongo db
4. use prisma
5. if i remove database or collection no error is given but don't create nothing

### Expected behavior

as documentation says database must be created or collection or indexes, or give some function to do that.

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["mongoDb", "extendedIndexes"]
}

datasource db {
  provider = "mongodb"
  url      = env("DSN")
}

model example {
  id String @id @default(auto()) @map("_id") @db.ObjectId
  name String
  code String
  @@unique([name, code])
}
```

### Environment & setup

- OS: severals Mac OS big sur version 11.6.2 (20G314) and centos for sure
- Database: MongoDB
- Node.js version: 12.8.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0
Preview Features        : mongoDb, extendedIndexes
```

**Comment by janpio** [comment]
What version of MongoDB are you using?
Are you getting an error message instead of things being created?
Are you trying to write data as well or how do you know that the database and collection was not created?

**Comment by matthewmueller** [comment]
@emimarz as @janpio mentioned we need a bit more information:

Collections are created in two ways by Prisma:
- Created using `prisma db push`
- Lazily when you first write data

**Comment by emimarz** [comment]
which mongo am I using
prismagraphql/mongo-single-replica:4.4.3-bionic
there is no error but no collection and index is created
yes, i can select insert and update data without any problem 
for mongo the documentation says that is not necessary do a "prisma db push"
ok, was that, you must update documentation for this

**Comment by janpio** [comment]
One thing I do not understand: How can you insert data if the collection does not exist?
