### ISSUE TITLE
Data Platform: Cannot connect Prisma to Cockroach Serverless `Requested database check `reachable` failed`

### ISSUE THREAD

**Issue by SebJansen** [prisma/prisma#12451]
### Bug description

Prisma won't accept the connection string, example: `postgresql://seb:rmhls-LrWm3I5oDi1aaGag@free-tier13.aws-eu-central-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require&options=--cluster%3Drose-warthog-619`

I have a strong suspicion on this being an SSL-related problem 

### Create CockroachCloud cluster

1. Go to `https://cockroachlabs.cloud/clusters`
2. Click on `Create Cluster`
3. Select `Serverless`
4. Select cloud provider `AWS`
5. Select region `Frankfurt (eu-central-1)`
6. Leave spend limit at `$0`
7. Enter cluster name `Test123`
8. Note down the connection string

### Create Prisma project

1. Go to `https://cloud.prisma.io/projects`
2. Click on `New Project`
3. Fill in project name as `Test123`
4. Select `Create a repository`
5. Fill in repository name as `Test123`
6. Click on `Next`
7. Select template `URL Shortener`
9. Click on `Next`
10. Select `Use my own database`
11. Enter connection string, in my case `postgresql://seb:rmhls-LrWm3I5oDi1aaGag@free-tier13.aws-eu-central-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require&options=--cluster%3Drose-warthog-619` [_I will delete this cluster as soon as this problem is resolved_]
12. Select location `eu-central-1 (Frankfurt)`
13. Leave static IPs on `Disabled`
14. I get a warning, the complete information of it being ```We were unable to create your project: Requested database check `reachable` failed```

### Check connection string with `psql`
1. Connect: `psql "postgresql://seb:rmhls-LrWm3I5oDi1aaGag@free-tier13.aws-eu-central-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require&options=--cluster%3Drose-warthog-619" -c "SHOW DATABASES"`

### Check connection string with `cockroach sql`
1. Download certs with `curl --create-dirs -o ~/.postgresql/root.crt -O https://cockroachlabs.cloud/clusters/32d83dc6-bfad-4146-9c1f-fbed298ce610/cert`
2. Connect: ```cockroach sql --url "postgresql://seb:rmhls-LrWm3I5oDi1aaGag@free-tier13.aws-eu-central-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require&options=--cluster=rose-warthog-619&sslrootcert='$HOME'/.postgresql/root.crt" -e "SHOW DATABASES"```

### Expected behavior

It should allow a new Prisma project to connect to CockroachDB's serverless offering

### Prisma information

No schema, just trying to create a new and blank project

### Environment & setup

- Fedora 35 locally
- Prisma Cloud
- CockroachDB serverless

### Prisma Version

```
prisma                  : 3.11.0
@prisma/client          : Not found
Current platform        : rhel-openssl-1.1.x
Query Engine (Node-API) : libquery-engine b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/libquery_engine-rhel-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/migration-engine-rhel-openssl-1.1.x)
Introspection Engine    : introspection-core b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.1.x)
Format Binary           : prisma-fmt b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/prisma-fmt-rhel-openssl-1.1.x)
Default Engines Hash    : b371888aaf8f51357c7457d836b86d12da91658b
Studio                  : 0.458.0
Preview Features        : cockroachdb
```

**Comment by Jolg42** [comment]
Thank you for the reproduction!

**Comment by Jolg42** [comment]
If I construct the connection with clusterName.databaseName like
```
postgresql://seb:rmhls-LrWm3I5oDi1aaGag@free-tier13.aws-eu-central-1.cockroachlabs.cloud:26257/rose-warthog-619.defaultdb
```

I get a different error
```
We were unable to create your project: An unknown error occurred while linking the database to the environment
```

**Comment by Jolg42** [comment]
It smells like it's something on our end, someone from the Data Platform will look into it. Thanks for testing!

**Comment by janpio** [comment]
So we can confirm that the Data Platform is currently not compatible with the `options=--cluster=` parameter CockroachDB is using by default. We will try to change this soon and will update you here. (If you can leave the connection string up until that happens, that would be neat as we have been using that one to test and reproduce 😆)

That the alterantive connection string that @Jolg42 crafted does not work, is a bit more of a mystery. There we do not know exactly what is going on yet but will also investigate.

Thanks for reporting this @SebJansen - this will make Prisma better for everyone. Unfortunately you will have to wait a bit.

**Comment by SebJansen** [comment]
Thank you for chasing this issue, and of course I'll leave the cluster/connstring up! :)

**Comment by janpio** [comment]
Hey @SebJansen, the team just deployed a change to Prisma Data Platform that fixes the problem that @Jolg42 described, that the `options=--cluster` connection string was leading to the `Requested database check reachable failed` error message.

Unfortunately now both connection strings get `We were unable to create your project: An unknown error occurred while linking the database to the environment`. So the problem is still not solved for you, and we are continuing to investigate. Will keep you updated.

**Comment by harshhhdev** [comment]
I talked to this with @martzoukos over on intercom at the Prisma cloud homepage. 

Spiros had suggested that I switch my provider to PostgreSQL in my schema which did indeed work, although I think it's important for it to work natively as well.

**Comment by janpio** [comment]
This should not be necessary today @harshhhdev. Can you test this again please?

**Comment by harshhhdev** [comment]
Hey @janpio, it's working now :champagne:. I'm able to access my CockroachDB schema inside of the cloud.

**Comment by janpio** [comment]
Yay.
