### ISSUE TITLE
(mysql) ORDER BY when building Prisma.sql string fails

### ISSUE THREAD

**Issue by ramin** [prisma/prisma#12456]
### Bug description

When executing a safe rawQuery, interpolating values for `ORDER BY` with msql fail to interpolate values if they are done from variable and ignored is the sort direction is supplied following a column variable.

### How to reproduce

1: execute a queryRawUnsafe and interpolate two variable to build an ORDER BY string (ORDER BY name DESC)
2: change to queryRaw and use Prisma.sql to build the Template
3: run again, see error 

```
Raw query failed. Code: `1064`. Message: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 6
```

### Expected behavior

executeRaw with a parsed Prisma.sql should generate valid sql and execute the query

### Prisma information

```typescript
model AdUnit {
    id                         Int                         @id @default(autoincrement())
    name                       String
}
```

```
const sort = "id";
const order = "DESC";
```

# Fails
```typescript
results = await prisma.$queryRaw(Prisma.sql`SELECT
        id,
        name
    FROM AdUnit
    ORDER BY ${sort} ${order};`);
```

# Working raw query
```typescript
 let results = await prisma.$queryRawUnsafe(`SELECT
        id,
        name
    FROM AdUnit
    ORDER BY ${sort} ${order};`);
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

OS X arm64
Docker image: mysql:5.7

### Prisma Version

```
prisma                  : 3.9.1
@prisma/client          : 3.9.1
```

**Comment by matthewmueller** [comment]
Hey @ramin, this is expected. You cannot use the `$queryRaw` syntax for dynamic columns or keywords. This is an underlying restriction in how prepared queries work:

Values are supported by prepared queries:

```sql
select name from user where id = $1
```

However column names (e.g. name) and keywords (e.g. asc) are not:

```sql
select $1 from user where id = $1
select name from user order by $1
```

I've opened an issue to get this documented better: https://github.com/prisma/docs/issues/3061. Closing.
