### ISSUE TITLE
[Mongo] Improve native type validations in composite types

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#12460]
Mongo supports BigInt as a Prisma type but errors when the Native type is provided stating that BigInt is not supported. If the annotation is unnecessary the error should state that instead. 

![Screen Shot 2022-03-21 at 16 51 22](https://user-images.githubusercontent.com/16278407/159350468-18aa442e-47ae-4273-b49e-0267dc4dc817.png)

Same for Json
![Screen Shot 2022-03-21 at 16 52 43](https://user-images.githubusercontent.com/16278407/159350917-ebbdc7fe-c7a9-43ca-bcec-c24571637f4f.png)

Invalid Prisma type and native type combinations pass validation. 
![Screen Shot 2022-03-21 at 16 36 31](https://user-images.githubusercontent.com/16278407/159350978-c86880ea-b454-4d5b-b0c6-6498eb3368e8.png)

**Comment by janpio** [comment]
"`@db.BigInt` is called `@db.Long` from MongoDB to reflect their naming convention. Use that instead." then for example.

**Comment by pimeys** [comment]
We do not have validations like that for other databases. Your autocomplete should help you out already.

**Comment by janpio** [comment]
Kepp open until manually confirmed.

**Comment by do4gr** [comment]
Confirmed fixed.
