### ISSUE TITLE
[Mongo] Too generic error messages in composite types

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#12462]
All these cases not passing validations are correct, but the errors are too cryptic. 

`@@map` does not make sense since the composite type name is not persisted in the database anyways. 

![Screen Shot 2022-03-21 at 16 09 29](https://user-images.githubusercontent.com/16278407/159351614-63ba2947-9453-4335-b649-4db6baa26574.png)

We do not allow `@id` attribute on composites currently. 
![Screen Shot 2022-03-21 at 16 13 25](https://user-images.githubusercontent.com/16278407/159351729-3930ab92-0d3a-430b-a61d-5308596dc7f9.png)

Same as above
![Screen Shot 2022-03-21 at 16 28 40](https://user-images.githubusercontent.com/16278407/159351826-b042ab1f-acc5-48b2-b420-2395697abbdd.png)

Relation attribute is not available on composites, they can only nest other composites currently which don't need `@relation`
![Screen Shot 2022-03-21 at 16 41 09](https://user-images.githubusercontent.com/16278407/159351872-d2c05de2-22c0-4b33-9041-f8922811f848.png)

**Comment by janpio** [comment]
Keep open until all cases manually confirmed.

**Comment by do4gr** [comment]
Confirmed fixed.
