### ISSUE TITLE
Allow to filter by undefined fields in MongoDB

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma#12478]
It should be possible to filter by fields that are not set (undefined) in MongoDB.

```graphql
{
    findManyModel(where: { field: { isSet: false } }) { id }
}
```

**Comment by dgradwell-ams** [comment]
Essentially, this would translate to something like `{ field: { $exists: false } }` in mongospeak .

**Comment by Weakky** [comment]
Closed by https://github.com/prisma/prisma-engines/pull/2767
