### ISSUE TITLE
Implement `getDmmf` as Wasm module that could be used in Prisma CLI

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12482]
Similar to how we build Wasm module verisons of Prisma Formatter and `getConfig` (https://github.com/prisma/prisma-fmt-wasm), we also want to have one (or add it to the existing module) that has the same functionality as what `getDmmf` from the Query Engine currently provides. This module as a Npm package could then potentially replace the (platform dependent, downloaded) Query Engine usage in Prisma CLI and parts of Prisma Client (generation) making the engine itself obsolete in many use cases (besides the generated Prisma Client itself of course).

**Comment by garrensmith** [comment]
Just to note, having a `getDmmf` would also be very useful for the client. We could use it to generate the dmmf instead of loading up the engine. It would be especially useful for when the client is connecting to the data proxy

**Comment by jkomyno** [comment]
Closed via https://github.com/prisma/prisma/pull/17533.
