### ISSUE TITLE
Implement `debugPanic` like functionality for `getConfig` and `getDmmf` of Query Engine

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12494]
To be able to implement and test Prisma's CLI engine crash reporting for `getConfig` and `getDmmf`, we need new functionality similar to `debugPanic` of Migration and Introspection Engines (https://prisma.github.io/prisma-engines/doc/migration_core/json_rpc/index.html#-debugpanic) that we can somehow trigger when we execute `getConfig` or `getDmmf`.

For `getConfig` we call in the CLI:
- For the Node-API library `NodeAPIQueryEngineLibrary.getConfig(...)`
- For the Binary `...engineArgs, 'cli', 'get-config', ...args`

For `getDmmf` we call in the CLI:
- For the Node-API library `NodeAPIQueryEngineLibrary.dmmf(datamodel)`
- For the Binary `'--enable-raw-queries', 'cli', 'dmmf'`

For all 4 we have 2 different options how to implement this:
1. We implement a separate function/endpoint `debugPanic` that we can [call instead of the intended function/endpoint](https://github.com/prisma/prisma/blob/cc5022f115f4843f4580a31f5bad2cf516a8e32f/packages/migrate/src/MigrateEngine.ts#L277-L280), and when we want to test the error reporting we would just call out to that instead of the actual one.
2. We use the existing function/endpoint but add a way to configure what happens inside (and then trigger the panic there). For Node-API library that could maybe be an environment variable, and for the Binary an additional parameter.

**Comment by janpio** [comment]
Query Engine _binary_ already has a similar mechanism for `queryRaw` (and potentially other endpoints): https://github.com/prisma/prisma/blob/a7e6db561c8439fb4da4898d021d0f561062c7ca/packages/client/src/runtime/getPrismaClient.ts#L881-L909 If that also applies to `cli dmmf` and `cli get-config`, the binary part might already be implemented there and can just be reused.

**Comment by janpio** [comment]
Suggestion:
- `NodeAPIQueryEngineLibrary.debugPanic()` for Node-API library
- `cli debug-panic` CLI command for binary

**Comment by dpetrick** [comment]
The binary already has a way of triggering errors: Fatal or non-fatal, based on included headers `x-debug-non-fatal` or `x-debug-fatal`. Fatal = engine exists, non-fatal: panic is thrown. That's only possible on the graphql endpoint right now, but not really a problem to expand that to other ones too.

The NodeAPI already has a `debug_panic` endpoint that simply errors.

**Comment by janpio** [comment]
That sounds good. @jkomyno who will use these, just needs to know how to trigger each.

What you describe for Node-API could be related to these issues (and the comments): https://github.com/prisma/prisma/issues/7810 + https://github.com/prisma/prisma/issues/11362

**Comment by jkomyno** [comment]
Close this via https://github.com/prisma/prisma-engines/pull/2869 and https://github.com/prisma/prisma-engines/pull/2870.
