### ISSUE TITLE
Implement "CLI engine crash reporting" for Formatter Engine and `getConfig` and `getDmmf` of Query Engine

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12495]
This relies on https://github.com/prisma/prisma/issues/12493 and https://github.com/prisma/prisma/issues/12494 being implemented. (Done)

We want to implement error reporting similar to how we already have it for Migration and Introspection Engine crashes for the Formatter Engine and QueryEngine (`getConfig` and `getDmmf` parts). Via the above mentioned issues the necessary mechanisms in the engines have been implemented, and can now be used here as well.

1. - [x] **Allow triggering the new debug functionality** (implemented via #12493 and #12494) [similar to e.g. in Migrations with an environment variable](https://github.com/prisma/prisma/blob/cc5022f115f4843f4580a31f5bad2cf516a8e32f/packages/migrate/src/MigrateEngine.ts#L277-L280). 
	- (Note that we want to be able to trigger `getConfig` and `getDmmf` crashes separately, so they need a different "trigger" on the CLI side as they are often called together or close to each other.)
	- If one of the issues is not implemented yet, just fake the code so pretend it was already there - and we can add the actual implementation later.
2. - [x] **Make sure errors are correctly thrown** so error handling UI can be triggered to start upload process etc (Internal documentation: https://www.notion.so/prismaio/CLI-Engine-Crash-Reporting-7bad95ea3c5a45f4a5a3250755a324a5#606a4379530c46e1bcd9cd12b107f221)
3. - [x] **Implement CLI Engine Error handling** for all uses of Formatter Engine and QueryEngine (`getConfig` and `getDmmf`)
4. - [x] **Add tests** similar to existing IE and ME error triggering to make sure this keeps working
5. - [x] To be documented at https://www.notion.so/prismaio/CLI-Engine-Crash-Reporting-7bad95ea3c5a45f4a5a3250755a324a5#a44d5d144e144d00920fb2e4d90dfac3 and https://github.com/prisma/prisma/pull/13359

**Comment by janpio** [comment]
Previous example of how to trigger it (might be fixed, but there should be workaround now): https://github.com/prisma/prisma/issues/10206 Also includes a link to https://github.com/prisma/prisma/pull/10205/files that could give ideas for the implementation.

**Comment by janpio** [comment]
Step 1, "Formatter Engine" part was already implemented: https://github.com/prisma/prisma/pull/12569

**Comment by jkomyno** [comment]
This issue depends on https://github.com/prisma/prisma/pull/12762 being merged.

**Comment by jkomyno** [comment]
I have locally added the `--enableTriggerPanic` flag to the `query-engine` `cli get-config` and `cli dmmf` commands. Here is an example @janpio:

![image](https://user-images.githubusercontent.com/12381818/164028486-5c7b274b-7763-45e8-810d-f4d30ed08917.png)

![image](https://user-images.githubusercontent.com/12381818/164029069-6dfe185f-71b6-4a9f-a5d0-4f864af2b5ac.png)

**Comment by janpio** [comment]
That seems to be a part of https://github.com/prisma/prisma/issues/12494 then. (Although the suggestions there was to also implement a separate `debug-panic` command in the CLI similar to how others are implemented)

**Comment by jkomyno** [comment]
The fancy error reporting (i.e., `handlePanic`) is only triggered whenever an error with a `rustStack` property is bubbled up in the `cli`. Locally, I have propagated the errors for `getConfig` and `dmmf` whenever either the `FORCE_PANIC_QUERY_ENGINE_GET_CONFIG=1` or the `FORCE_PANIC_QUERY_ENGINE_GET_DMMF=1` env variables are set. However, I still have to capture the Rust's stacktrace and embed them in an `Error` the way `@prisma/cli` wants it.

**Comment by jkomyno** [comment]
Another thing to note:
- the errors thrown by `query-engine cli get-config --enableTriggerPanic` and `query-engine cli dmmf --enableTriggerPanic` are slightly different
- the `debugPanic` RPC function in `query-engine-node-api` doesn't distinguish between whether the panic is triggered while accessing the `getConfig` or `getDmmf` function area of the query engine

Are we happy with this inconsistency in the panic simulations?

**Comment by jkomyno** [comment]
Closing this (as most contributions have already been merged to main) in favor of https://github.com/prisma/prisma/issues/13557
