### ISSUE TITLE
Add `@prisma/prisma-fmt-wasm` to CLI and output dependency version in `-v`, use instead of Formatter Engine binary

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12496]
[@prisma/prisma-fmt-wasm](https://www.npmjs.com/package/@prisma/prisma-fmt-wasm) exists and can replace the Formatter Engine binary usage in Prisma CLI already.

1. Add `@prisma/prisma-fmt-wasm` as dependency (requires CI changes)
2. Output dependency package version in `-v` output of Prisma CLI
3. Replace the `format` (and others) call of the Formatter Engine binary with a call to the Wasm module (in a separate PR)
4. Test CLI Engine Crash Reporting along the way to make sure it also works properly with the Wasm module
5. Profit 🚢

**Comment by jkomyno** [comment]
Note: currently, installing `@prisma/prisma-fmt-wasm` in `@prisma/cli` would fail because of this lines in `prisma_fmt_build.js`:

```javascript
                                       .---> this isn't compatible with a monorepo
                                       |
const path = require('path').join(__dirname, 'prisma_fmt_build_bg.wasm');
const bytes = require('fs').readFileSync(path);

const wasmModule = new WebAssembly.Module(bytes);
const wasmInstance = new WebAssembly.Instance(wasmModule, imports);
wasm = wasmInstance.exports;
module.exports.__wasm = wasm;
```

**Comment by jkomyno** [comment]
About extracting the version of `@prisma/prisma-fmt-wasm` to display in `prisma --version`, let's remind ourselves about this issue: https://github.com/prisma/prisma-fmt-wasm/issues/3

**Comment by janpio** [comment]
> Note: currently, installing @prisma/prisma-fmt-wasm in prisma CLI would fail because of these lines in prisma_fmt_build.js:

Something to work on with @tomhoule.

> About extracting the version of @prisma/prisma-fmt-wasm to display in prisma --version, let's remind ourselves about this issue: https://github.com/prisma/prisma-fmt-wasm/issues/3

We can either implement that, or maybe use the Npm package version as an adequate replacement if that has enough information.

**Comment by tomhoule** [comment]
>  Note: currently, installing @prisma/prisma-fmt-wasm in prisma CLI would fail because of these lines in prisma_fmt_build.js:

This part I don't understand, I don't see what is wrong.

**Comment by tomhoule** [comment]
For the version, we can implement something easily, if that's what we want. The package.json approach might be better, I don't know how JS projects do it usually.

**Comment by janpio** [comment]
The issue here asks for the dependency version, so the issue @jkomyno linked to is technically not relevant unless there is a good reason not to do it that way.

**Comment by jkomyno** [comment]
@Jolg42 suggests that we might fix the path issue following a similar approach to https://github.com/prisma/prisma/blob/main/helpers/compile/plugins/replaceWithPlugin.ts#L44

**Comment by 0gust1** [comment]
We have the same kind of error as @jkomyno posted, when trying to run `prisma migrate deploy` on our target server.

node: 16.14.2
prisma: 4.4.0 
env: Azure AppService ("classic" zip deploy)

```
Error: ENOENT: no such file or directory, open '/home/site/wwwroot/node_modules/.bin/prisma_fmt_build_bg.wasm'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at ../../node_modules/.pnpm/@prisma+prisma-fmt-wasm@4.4.0-66.f352a33b70356f46311da8b00d83386dd9f145d6/node_modules/@prisma/prisma-fmt-wasm/src/prisma_fmt_build.js (/home/site/wwwroot/node_modules/.bin/prisma:12337:31)
    at __require (/home/site/wwwroot/node_modules/.bin/prisma:14:50)
    at Object.<anonymous> (/home/site/wwwroot/node_modules/.bin/prisma:86202:38)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/site/wwwroot/node_modules/.bin/prisma_fmt_build_bg.wasm'
}
```
In `node_modules/@prisma/engines` we have the correct engines (`prisma-fmt-debian-openssl-1.1.x` in our case), but it keep searching for a wasm module, at the wrong place (`node_modules/.bin/prisma_fmt_build_bg.wasm`)

**Comment by jkomyno** [comment]
@0gust1 would you please report here what's your `prisma version` full output? Even though we're still shipping the formatter engine (`prisma-fmt-debian-openssl-1.1.x`), we've been using a WebAssembly module for `prisma format` for a few releases now. It'd be also awesome if you could provide more information about your project structure.
Is it a standalone project or a monorepo? Would you please have a minimally reproducible project we could look at to better understand/reproduce the issue?

**Comment by 0gust1** [comment]
@jkomyno Hi 👋 . Thanks for the follow-up! I'll open an issue (it's on my today's TODO) and/or post on #15881. Expect some news in the next 6 hours.

Very quickly (those elements will be in the issue):  
It's a standalone project; I suspect that the azure deployment could "do things" to the node_modules folder; I still can't completely rule out a problem on our own workflow. Reproductibility won't be easy (as it will need an Azure account/subscription), but I'll try.

**Comment by jkomyno** [comment]
@0gust1 that's great, thanks for the quick response! Please report that information directly in https://github.com/prisma/prisma/issues/15881, so we can keep track of the potential issue in a single place and keep things nice and tidy ☺️

**Comment by looppin** [comment]
i am using Azure app services and i solved this problem as bellow;

- update npm version `npm install npm@latest -g`
- install again prisma with npm `npm i prisma`

note: make sure you are in the main folder (like /home/site/wwwroot).
