### ISSUE TITLE
Custom queries based on a Google Sheet

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma#125]
**Idea**

Make it possible for non-technical users to create public apis by modifying data in a google sheet. This should plug into traditional Graphcool projects, but it should also be super easy to set up a standalone Sheets based project

ref https://twitter.com/floydophone/status/837258059713949698

prior art https://github.com/enkidevs/driveQL

**Comment by petehunt** [comment]
It would also be nice to be able to interact with other types of files in google drive (like getting a google doc as an html blob, sorting by recently updated files, etc)

**Comment by THook** [comment]
I believe GraphCMS is into that kind of thing right now

**Comment by sedubois** [comment]
How about integrating things like [Airtable](https://airtable.com/) or [Fieldbook](https://fieldbook.com/)?
