### ISSUE TITLE
Connections are not returned to the connection pool in certain cases leading to permanent "timed out fetching a new connection from the connection pool" until restart

### ISSUE THREAD

**Issue by Valerionn** [prisma/prisma#12510]
### Bug description

Under certain conditions, Prisma doesn't return connections to the connection pool leading to all subsequent queries to return "Timed out fetching a new connection from the connection pool.". This seems to happen if you simultaneously execute more queries than your connection pool limit (e.g. 2 queries with a connection pool size of 1) and those queries return an error (e.g. the database is not available). I managed to reproduce it locally with a connection pool size of 1-3, but it might also happen with bigger connection pool sizes. With a connection pool size of 1, it's 100% reproducible when using the example below, otherwise it might take multiple "runs" until all connections are unusable.

The easiest way to reproduce it is by running `Promise.all` (like in the reproduction script below), however, this also happens if multiple queries are running at the same time due to other reasons (e.g. because there are 2 incoming requests that will both query the database. This is reproducible by using two `setTimeout`s to launch two queries instead of `Promise.all` but it's not 100% reproducible).

This bug is especially problematic when using a serverless database (e.g. AWS Aurora) which sometimes rescales and might return "connection closed, please reconnect" due to this which then triggers this bug and exhausts the connection pool over time, requiring an application restart. However, I also encountered the permanent "timed out fetching a connection..." in other cases which might be related to this.

### How to reproduce

1. Add prisma to a node project, generate a `schema.prisma` using postgresql (I haven't tested other providers)
2. Create a model named User (to directly use the example below). It is enough if it just has an id field to satisfy prisma
3. specify `connection_limit=1` in your database connection string ([as described here](https://www.prisma.io/docs/concepts/database-connectors/postgresql#arguments))
4. Have a local postgres installation ready and make sure you have a way to quickly start/stop it (on Windows, you can use the "Services" tab in the task manager so you can right click on the postgresql service and click start/stop)
5. Run the following script and start/stop the database as instructed in the console (you can increase the timeout from 5000 to a different value if you need more time to start/stop the database server):

```typescript
  await prismaClient.$connect();
  while(true) {
    console.log('Stop your database server now!');
    await new Promise(r => setTimeout(r, 5000));
    console.log('Executing queries...');
    try {
      await Promise.all([
        // At least 2 for connection_pool=1. 5 seems to be enough to exhaust a pool of size 3 after 2 runs
        prismaClient.user.findMany(),
        prismaClient.user.findMany(),
        prismaClient.user.findMany(),
        prismaClient.user.findMany(),
        prismaClient.user.findMany(),
      ]);
    } catch(e) {
      // We expect errors here since the DB is down
    }
    console.log('Start your DB again');
    await new Promise(r => setTimeout(r, 5000));
    console.log('Executing test query...');
    await prismaClient.user.findMany();
    console.log('Success');
  }
```

The script will stop with an "Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 1)" error after trying to execute the test query. Otherwise, "Success" is logged and the script starts again. This is useful if you e.g. set the connection_limit=3, then it might take multiple runs until no connections are available.

Note that this script uses `Promise.all`, however you can also reproduce it without using `Promise.all` with the following script (only works with a connection_limit=1):
```typescript
  await prismaClient.$connect();
  while(true) {
    console.log('Stop your database server now!');
    await new Promise(r => setTimeout(r, 5000));
    console.log('Executing queries...');
    try {
      setTimeout(async () => {
        try {
          await prismaClient.user.findMany();
        } catch {}
      }, 0);
      setTimeout(async () => {
        try {
          await prismaClient.user.findMany();
        } catch {}
      }, 0);
    } catch(e) {
      // We expect errors here since the DB is down
    }
    await new Promise(r => setTimeout(r, 3000));
    console.log('Start your DB again');
    await new Promise(r => setTimeout(r, 5000));
    console.log('Executing test query...');
    await prismaClient.user.findMany();
    console.log('Success');
  }
```

### Expected behavior

Faulty connections should be removed from the pool and if I run a new query after some time, it should just create a new connection instead of always returning "timed out fetching a connection from the connection pool"

### Environment & setup

- OS: Windows
- Database:PostgreSQL
- Node.js version: v16.13.1

### Prisma Version

```
prisma                  : 3.11.0
@prisma/client          : 3.11.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine b371888aaf8f51357c7457d836b86d12da91658b (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli b371888aaf8f51357c7457d836b86d12da91658b (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core b371888aaf8f51357c7457d836b86d12da91658b (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt b371888aaf8f51357c7457d836b86d12da91658b (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : b371888aaf8f51357c7457d836b86d12da91658b
Studio                  : 0.458.0
Preview Features        : interactiveTransactions
```

**Comment by garrensmith** [comment]
@Valerionn thanks for testing and confirming the fix works.
