### ISSUE TITLE
Prisma panic on invalid int

### ISSUE THREAD

**Issue by paulbrickellmaven** [prisma/prisma#12526]
### Bug description

Prisma will panic and become unusable if I query for an Int value that is too large for int.

```
{
    "where": {
        "id": 456774575747645765674576
    }
}
```

### How to reproduce

Create the simplest schema possible with an int field and perform any query (e.g. count) with a where clause that includes an int that is larger than `Number.maxSafeInt()`.

### Expected behavior

Should not render Prisma client unusable.

### Prisma information

```
model User {
  id          Int      @id @default(autoincrement()) @db.Int
  name        String?  @db.VarChar(255)
}
```

### Environment & setup

Reproducible on Ubuntu and Centos
MariaDB
Node 14.17.5

### Prisma Version

```
3.11.1
```

**Comment by dpetrick** [comment]
3.15 will ship a change that returns a structured error instead of a panic.
