### ISSUE TITLE
Behaviour change: Prisma `create` ignores an explicitely passed id when it can be autogenerated since 3.10.0

### ISSUE THREAD

**Issue by floriantz** [prisma/prisma#12528]
### Bug description

The issue happened on mysql8+ and the behaviour changed somewhere between prisma `3.8.1` and `3.11.0`.

For a given table of this structure:
````sql
CREATE TABLE repro(
    `id` varchar(255) NOT NULL DEFAULT (UUID()),
    PRIMARY KEY(id)
)
````

When creating a new row with prisma create where we provide the id directly:
```typescript
    const created = await client.repro.create({data: {uuid()});
```

In `3.8.1`, the id will be the one we set explicitely
In `3.11.0`, prisma will ignore the id, and let the DB generate one.

I haven't seen anything in the changelogs documenting this change and this led to some hard to debug issues when bumping Prisma.

### How to reproduce

I have a made a minimal reproduction repo available here: https://github.com/floriantz/repro-prisma

Change the version between `3.8.1` and `3.11.0` and you'll see prisma starts ignoring the explicitely passed id in create in the latter version.

### Expected behavior

Either the explicitely passed id should not be ignored in favour of the default, or Prisma should not allow passing the id at all ?

I'm unsure what's the best behaviour should be but it looks to me like an uncaught regression.

### Prisma information

```
model repro {
  id String @id @default(dbgenerated("(uuid())")) @db.VarChar(255)
}
```

### Environment & setup

- OS: Reproducible on multiple OS, so it seems unrelated.
- Database: MySQL 8
- Node.js version: 16+

### Prisma Version

```
3.11.0
```

**Comment by FredericEspiau** [comment]
I think the issue was introduced by this PR: https://github.com/prisma/prisma-engines/pull/2643

**Comment by janpio** [comment]
If this is the PR causing the change, it would mean that 3.9.x still has the old behavior, and 3.10.x does not. Can you maybe confirm this? Would help speed up our reproduction and understanding. Thanks.

**Comment by FredericEspiau** [comment]
I can confirm the issue appeared starting with `3.10.0`

In the repo provided by @floriantz the two ids should be identical

# `3.9.2`

```
provided id: b22aaec4-80d0-4986-9fab-c0e6465bcdbf
created id: b22aaec4-80d0-4986-9fab-c0e6465bcdbf
```

# `3.10.0`

```
provided id: 020617ca-dce1-4e9c-a73a-d9345ddd8a01
created id: 3c613c35-ac49-11ec-9457-0242ac120002
```

**Comment by janpio** [comment]
I can confirm thanks to the excellent reproduction. Thanks @floriantz!
(MySQL 5.7 can not migrate that schema btw... 🙄)
