### ISSUE TITLE
Aggregate queries result in Unexpected `}[Punctuator]` issue

### ISSUE THREAD

**Issue by jamesyu** [prisma/prisma#12536]
### Bug description

Running a basic aggregate query like

```
await prisma.image_sets.aggregate({});
```

Throws a GraphQL query error:

```
Error parsing GraphQL query: query parse error: Parse error at 4:3
Unexpected `}[Punctuator]`
Expected `Name`

```

This seems related to [this issue](https://github.com/prisma/prisma/issues/5749) but I don't have any tables named Query.

### How to reproduce

Set up schema like so:

```
model image_sets {
  id               String  @id @default(cuid())
  created_at       DateTime? @default(now()) @db.Timestamptz(6)
  @@index([created_at])
}
```

And then do an aggregate query like so:

```
await prisma.image_sets.aggregate({});
```

### Prisma information

Schema:

```
model image_sets {
  id               String  @id @default(cuid())
  created_at       DateTime? @default(now()) @db.Timestamptz(6)
  @@index([created_at])
}
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.15.1

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.9.1
Current platform        : darwin
```

**Comment by jamesyu** [comment]
any thoughts on this?

**Comment by SevInf** [comment]
@jamesyu latest Prisma version shows this error:

```
Invalid `prisma.image_sets.aggregate()` invocation:

{
? _count?: true,
? _min?: true,
? _max?: true
}


The `select` statement for type AggregateImage_sets must not be empty. Available options are listed in green.
```

Which looks correct to me: you have to specify at least one aggregate function.  Could you try updating to prisma 3.13.0?

**Comment by SevInf** [comment]
I am going to close this right now since latest version exhibits correct behavior here. Feel free to reopen with more details if the result for you is different.
