### ISSUE TITLE
Many-to-one or One-way relationships

### ISSUE THREAD

**Issue by paulrostorp** [prisma/prisma#12552]
## Problem
I find it problematic that relations can only be modelled as one->many instead of many->one.

An example use case:
```prisma
model Post {
  id      String   @id
  User    User[]   @relation(fields: [userIds], references: [id])
  userIds String[]
}

model User {
  id           String   @id
  likes        Post[]   @relation(references: [id], fields: [likedPostIds])
  likedPostIds String[]
}
```
This simple data model would allow me to use prisma's nice Fluent API, and do things like `User.likes()`. However, this is not scalable at all, if a Post has a million likes, the `userIds` array is going to be huge.

## Suggested solution

Ideally, I would like to have the flexibility to decide for myself how the data is going to be structured. For my use case, I will never need to follow the relation from `Post=>User`, only `User=>Post`.

I wish the formatter would allow one-way relations, that way it could be as simple as:
```prisma
model Post {
  id String @id
}

model User {
  id           String   @id
  likes        Post[]   @relation(references: [id], fields: [likedPostIds])
  likedPostIds String[]
}
```

## Alternatives
The only alternative is to have a very granular "join table", such as this:
```prisma
model Post {
  id String @id @map("_id")

  LikesByUser LikesByUser[]
}

model LikesByUser {
  userId String
  post   Post   @relation(fields: [postId], references: [id])
  postId String
  User   User   @relation(fields: [userId], references: [id])

  @@id([userId, postId])
}

model User {
  id          String        @id @map("_id")
  LikesByUser LikesByUser[]
}
```

Other than inconvenience, the downside of doing this is that it isn't very storage efficient.

**Comment by janpio** [comment]
You are actually asking for a relation on a list type (`likedPostIds` in your example), correct? Do foreign keys work on that construct in any of our supported database?

**Comment by paulrostorp** [comment]
My main focus when writing this was mongo, but it seems the same applies to postgres, _unless using implicit relations_...

**Comment by jonschlinkert** [comment]
> 1. We do not allow one way relations. If you add a relation in one direction, we automatically also add the other direction.

We're currently looking for a way to add one-way relations as well. We call these "references". I'm not sure if this belongs on this issue, but consider a scenario where you might want to add "related items" to a post or product where it's not only unnecessary, but undesirable to create a corresponding "link" on the other side of the relation. This is a very common pattern, and ideally we would be able to support this in a first class way with prisma. Instead, we have a number of different one-to-many, or many-to-many relations where one side of the relation will never be used. 

An alternative would be to use array fields, or json, etc. But that defeats the purpose of using prisma for the fluent API, referential integrity, etc.

**Comment by paulrostorp** [comment]
Yes, that is correct @janpio 
But I would be more than happy with simple "one way relations".
I'm mostly concerned about having to store a list of id that may be very large. Following the example above, if a Post has 1 million "likes" that would quickly be a problem.

**Comment by JulianVallee** [comment]
I would like to second this issue, and also provide another real world example where simple one-way relations would be preferred. In my use case the relations will always be followed as `ApiKey=>Scopes`, but never as `Scope=>ApiKeys`. 

While I don't see it causing problems in my case, it still feels off to drag the unnecessary part of the relationship around.

## Schema
```diff
model ApiKey {
  id        Int             @id @default(autoincrement())
  name      String
  token     String
  scopes    ApiKeyScope[]
}

model Scope {
  id        Int             @id @default(autoincrement())
  name      String
-  apiKeys   ApiKeyScope[]
}

model ApiKeyScope {
  apiKey    ApiKey          @relation(fields: [apiKeyId], references: [id])
  apiKeyId  Int
  scope     Scope           @relation(fields: [scopeId], references: [id])
  scopeId   Int

  @@id([apiKeyId, scopeId])
}
```

I also found some earlier related issues which I will leave here for completeness sake:

- https://github.com/prisma/prisma/issues/2018
- https://github.com/prisma/prisma/issues/3045

**Comment by janpio** [comment]
This issue is now difficult to handle as it contains two feature requests:

- "Many to one" relations which imply the "foreign keys" are managed on the "many" side (instead of on the one side with normal one-to-many relations as they are used in relational databases)
- One-way relationsships where the "back relation" is not rendered in the schema and exposed in Prisma Client. It is not super clear to me if there is also an impact on the data modelling in the database.

We should probably split them apart, do you agree @paulrostorp @JulianVallee @jonschlinkert?
If so, optimally @paulrostorp could open two new issues that replace this one and then @JulianVallee and @jonschlinkert can reply again. If Paul prefers to only open the "many to one" issue, then Julian or Jon can maybe take care of the other one.

@JulianVallee @jonschlinkert Is you question also only in MongoDB context?

**Comment by JulianVallee** [comment]
@janpio Thanks for the quick response! Splitting this up into two separate issues is a good idea, absolutely.

I'll wait for @paulrostorps response before creating a separate issue for the "one-way" relationships. Judging from his proposed solution I believe he's actually after the "one-way" and not "many-to-one" relationships. 

I'm coming from MySQL, haven't noticed the MongoDB label at first.

**Comment by paulrostorp** [comment]
Hi @janpio @JulianVallee 

I apologize for writing a feature request that was not straightforward. As @JulianVallee points out, my primary is request if for "one-way relations". I'll create a separate issue for my one-way request.

@JulianVallee you can share your use case on it as well as part of that issue

**Comment by janpio** [comment]
Thanks, in your new issue it is clear that your feature request would only be possible on MongoDB and only makes sense as an evolution of the many to many design we have chosen for MongoDB where the foreign keys are stored in arrays on each sides. 

From how I understood @JulianVallee, he wants similar functionality, but in a different context. The PSL change might look similar, but the required changes are completely different from your suggested change in MongoDB context Paul. I think @JulianVallee should open a separate issue 🙇

**Comment by JulianVallee** [comment]
@janpio I don't even need to create an issue anymore. You already helped me to overcome my initial problem by providing additional context and making me think in a different way, thank you!

@paulrostorp I think our issues look similar on the surface, but are pretty different after all. I think it will lead to confusions if I jump in there with my MySQL stuff, but of course feel free to use my schema if you need another example case! 

Being new to Prisma I simply didn't see the obvious and was not used to "mandatory" two-way relationships. But since Prisma is able to return the correct type definitions even for elaborate queries, it's just more flexible when the relationship is defined on both models. I simply omit the unwanted relationship from my Scope model queries and everything comes out as expected. For my use case that means I can get a list of all scopes without having them polluted with arrays of API keys.

PS: Should I still create a separate issue and wrap up my solution? Might make it easier to discover for others.

**Comment by janpio** [comment]
That would indeed be nice @JulianVallee - then also others can chime in.

**Comment by harshitaneja** [comment]
Any update on this? One way relationships are integral for our schema design. Is there any way to achieve that currently in prisma till official support lands?

**Comment by shtse8** [comment]
I don't know how to do many to 1 mappings. any solution?

**Comment by janpio** [comment]
One-way embedded relations (sometimes also called one-way, or one-sided) as a feature request are now tracked in https://github.com/prisma/prisma/issues/12725

If you have a use case that is not covered by that issue, please open a new one. Thanks.

**Comment by dzcpy** [comment]
@janpio #12725 is about MongoDB isn't it? This issue is very important IMO. All other ORMs like TypeORM, MikroORM etc. support one way relationship. It's quite inconvinient to model one way relations in Prisma

**Comment by Raduc4** [comment]
@paulrostorp  have you solved this problem so far?
Your example gives me an error 
```
Error validating model "SavedByUser": The current connector does not support compound ids.
```

**Comment by barrynorman** [comment]
Why is this Issue closed?

**Comment by polotek** [comment]
I don't believe this issue should be closed. Another use case for one-way relationships is an image table. I have images stored in s3 with a record for each entry. Images can be attached to various other models in different contexts. It feels like overkill to have a backlink from the images table back to several different models. Here's a simplified example.

```
model User {
  avatarId: Int?
  avatar: Image?
}

model Post {
  heroImageId: Int?
  heroImage: Image?
}

model Image {
  bucket: String
  key: String
}
```

**Comment by janpio** [comment]
This issue is not about plain one-way relations, but about MongoDB one-way embedded relations, which Prisma does not support right now - but we track the feature request in https://github.com/prisma/prisma/issues/12725.
