### ISSUE TITLE
Migration engine error

### ISSUE THREAD

**Issue by azzazkhan** [prisma/prisma#12570]
### Bug description

An error is thrown while running migrations using `npx prisma migrate dev`

### How to reproduce

1. Install the Prisma library and client using `yarn add prisma @prisma/client`.
2. Initialize the prisma using `npx prisma init`
3. Add the prisma schema.
4. Run the migration using `npx prisma migrate dev`
 

### Expected behavior

Should run migrations without any errors.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  name     String
  email    String
  password String

}

model Bookmark {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  title       String
  description String?
  link        String
}
```

### Environment & setup

- OS: Ubuntu 20.04 (WSL)
- Database: MySQL
- Node.js version: 16.13.2

### Prisma Version

```bash
$ npx prisma -v
Error: Command failed with exit code 127: /home/azzazkhan/Documents/Development/books-api/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x --version
/home/azzazkhan/Documents/Development/books-api/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

```json
"dependencies": {
  "@prisma/client": "^3.11.1",
  "prisma": "^3.11.1"
},
```

**Comment by janpio** [comment]
Which error are you getting when running `prisma migrate dev`?
The same as when you run `prisma -v`?

**Comment by azzazkhan** [comment]
> Which error are you getting when running `prisma migrate dev`? The same as when you run `prisma -v`?

@janpio The one mentioned in title *Error: Migration engine error*

**Comment by janpio** [comment]
Can you please post the complete output or a screenshot of that when running `prisma migrate dev`?

**Comment by tomhoule** [comment]
Hi @azzazkhan , do you have openssl installed? (`sudo apt install openssl`). If it's there, in what version? It looks like the runtime path of the shared library isn't reachable.

**Comment by hubsmoke** [comment]
Running

`whereis openssl`

And removing/moving the anaconda version of openssl fixed my issue. Very annoying / hard to search blank error message for this bug!

```
$ npx prisma migrate dev # this also fails 
$ npx prisma db execute --stdin # this reliably creates a crash
Oops, an unexpected error occured!
Error in migration engine.
Reason: 

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new
```
