### ISSUE TITLE
MDBGA: Improve Data Browser error message

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#12573]
We won't have a chance to make it fully work before GA.

@janpio mentioned the following options in increasing complexity:
- Disable Studio completely for MongoDB
- Disable Studio for MongoDB with embedded documents
- Fail gracefully when hitting an embedded document
- Fix embedded documents properly

We'd just need one of them.

Internal context: https://prisma-company.slack.com/archives/C013RMLGE72/p1648554920518609

**Comment by janpio** [comment]
Another option came up: Fix embedded documents in a temporary way.
