### ISSUE TITLE
Issue with prisma failing to locate schema file in monorepo

### ISSUE THREAD

**Issue by SomeoneWeird** [prisma/prisma#12588]
### Bug description

New issue, but very similar to #10433.

Running a multi-package monorepo with one package exporting an instantiated prisma client, and another NextJS project requiring the first package and trying to use the prisma client results in an error:

```
error - Error: ENOENT: no such file or directory, open '/private/tmp/prisma-repro/packages/web/node_modules/.prisma/client/schema.prisma'
```

The correct location of `schema.prisma` is `/tmp/prisma-repro/packages/db/prisma/schema.prisma`.

Reproduction repository w/ instructions: https://github.com/SomeoneWeird/prisma-repro 

### How to reproduce

Listed in repository readme

### Prisma information

Listed in repository

### Environment & setup

Mac, Node 16

### Prisma Version

```
prisma                  : 3.11.1
@prisma/client          : 3.11.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 1a2506facaf1a4727b7c26850735e88ec779dee9 (at ../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 1a2506facaf1a4727b7c26850735e88ec779dee9 (at ../node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 1a2506facaf1a4727b7c26850735e88ec779dee9 (at ../node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 1a2506facaf1a4727b7c26850735e88ec779dee9 (at ../node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 1a2506facaf1a4727b7c26850735e88ec779dee9
Studio                  : 0.458.0
```

**Comment by janpio** [comment]
The Client is self contained and gets a copy on `generate`. When you edit your real `prisma/schema.prisma` file and do not `prisma generate` yet, the Client keeps working with the schema it got generated for.

**Comment by Cauen** [comment]
I've solved by adding `--schema ./src/prisma/schema.prisma` at you package.json

```
"scripts": {
    ...
    "migratedev": "prisma migrate dev --schema ./src/prisma/schema.prisma",
    ...
},
```

Then, `cd apps/other-backend` `yarn migratedev`

**Comment by millsp** [comment]
Thanks @SomeoneWeird for the reproduction, I created a PR with a workaround https://github.com/SomeoneWeird/prisma-repro/pull/1. cc @Cauen @system32uwu @soulchild

**Comment by millsp** [comment]
Hey guys, thanks for the feedback. We have been working on a simpler way to make things work for you, as the workaround we proposed had clear limitations for TS projects. We worked on an experimental webpack plugin that ensures your Prisma files are copied correctly. I'd love if you could give it a try (https://www.npmjs.com/package/experimental-prisma-webpack-plugin). We have tested it in many different scenarios, so we hope this works for you.

```ts
const { PrismaPlugin } = require('experimental-prisma-webpack-plugin')

module.exports = {
  output: 'standalone',
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.plugins = [...config.plugins, new PrismaPlugin()]
    }

    return config
  },
}
```

**Comment by millsp** [comment]
For those using multiple Prisma Clients, we are going to schedule follow-up work via https://github.com/prisma/prisma/issues/18069. Please upvote it if you need multi-client support, and don't hesitate to share more information there.
