### ISSUE TITLE
Query log event doesn't quote datetimes in query params

### ISSUE THREAD

**Issue by revmischa** [prisma/prisma#12591]
### Bug description

I was following this - https://medium.com/@lucas_18321/how-to-trace-sql-queries-in-prisma-with-xray-sdk-in-nodejs-8c6dc92df07f

Which works fine except for one thing - when it parses the query params
```js
      const paramsArr = JSON.parse(e.params)
```
e.params is JSON except when there is a Date object in there. or newlines.

Looks like:
```js
"params":"[2022-03-30 11:52:45.302 UTC,\"1.0\",\"0f8b1ad3-8c7a-4da9-bdfd-0f326e061caf\",\"467f19ec-3589-424f-b512-07e62003eee1\"]"
```

Here's how I'm working around it right now
```ts
      // parse parameters JSON
      // we need to fix quoting of datetimes
      // e.g. [2022-03-30 11:52:45.302 UTC,"1.0"]
      const paramsStr = e.params.replace(/(\d{4}-\d{2}-\d{2} \d+:\d+:\d+\.\d+ UTC)/g, '"$1"').replace(/\n/g, " ")
      let params: string[] = []
      try {
        params = JSON.parse(paramsStr)
      } catch (e) {
        console.warn("Failed parsing params JSON:", paramsStr, e)
      }
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by revmischa** [comment]
Also I think double-quotes are not escaped

**Comment by stanstrum** [comment]
This seems to still be an issue on 4.8.1.  I experience it when submitting a request using Prisma with a JsonObject.  I think it'd just be simpler to have the `e.params` value (in the logging callbacks) just be an array of values rather than a string representation of the parameters for the prepared statements.

The way I had been mitigating it was by using `JSON.parse` on the params value, except this time it's been throwing errors because the quotes in the JSON representation of my cookie object (the value I'm storing as a JsonObject) is not escaped properly and causes the JSON parsing to fail in my logging callback.

Here's a simplified example:

```ts
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient({
  log: {
    level: "query",
    emit: "event"
  }
});

function replacePreparedParams(query: string, params: string[]) {
  const replacer = () => JSON.stringify(parsed_params.shift())

  return query.replace(/\?/g, replacer);
}

prisma.$on("query", e => {
  // This is the line that causes the error:
  const parsed_params = JSON.parse(e.params);

  console.log(replacePreparedParams(e.query.trim(), parsed_params));
});
```

The error looks something like this (with some irrelevant data elided):

```
["...","{"cookie":{"originalMaxAge":86400000,"expires":"2023-01-09T09:13:35.195Z","httpOnly":true,"path":"/"},"passport":{"user":"..."}}","...","..."]
          ^

SyntaxError: Unexpected token c in JSON at position 34
    at JSON.parse (<anonymous>)
    at <anonymous> (/app/src/managers/PrismaManager.ts:36:34)
    at EventEmitter.<anonymous> (/app/node_modules/@prisma/client/runtime/index.js:35690:20)
    at EventEmitter.emit (node:events:513:28)
    at LibraryEngine.logger (/app/node_modules/@prisma/client/runtime/index.js:27758:23)
    at /app/node_modules/@prisma/client/runtime/index.js:27730:61
```

To supply as much information as possible, the original prepared statement looked like this:

```sql
UPDATE `xdash`.`Session` SET `expiresAt` = ?, `data` = ? WHERE (`xdash`.`Session`.`id` IN (?) AND (`xdash`.`Session`.`sid` = ? AND 1=1))
```

Running `npx prisma version` returns the following:

```
$ npx prisma version
Environment variables loaded from .env
prisma                  : 4.8.1
@prisma/client          : 4.8.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

Hope this helps.

**Comment by millsp** [comment]
This issue was fixed in the Prisma Client 4.3 and have a fix for it here https://github.com/prisma/prisma/pull/14876, so I am closing this issue. Thanks for the reports.

**Comment by millsp** [comment]
Sure. Do you agree that this belongs in a different issue as it is broader than the OP? If so, could you please open a new issue with the information we need and how you'd actually expect it to behave, maybe as a feature request or an improvement? Thanks.

**Comment by janpio** [comment]
Can you point us to these issues @revero-doug, please? 

Right now, none of them are cross-linked in this issue in any way (both comments or issue history) - so we fixed the datetime problem and consider this issue resolved, as it only asked for datetime. If there were links to other issues, we could probably have resolved these problems as well. 

Thank you.

(PRs welcome as well of course if that is a thing that is an option for you.)
