### ISSUE TITLE
Property 'code' does not exist on type 'PrismaClientUnknownRequestError'

### ISSUE THREAD

**Issue by azzazkhan** [prisma/prisma#12606]
### Bug description

The [documented way of handling Prisma client exceptions](https://www.prisma.io/docs/concepts/components/prisma-client/handling-exceptions-and-errors) is by checking whether the thrown error is of the `PrismaClientUnknownRequestError` type and then adding conditions on the `code` property available on the error object but in my case, the Typescript compiler is yelling that the property `code` does not exist on type `PrismaClientUnknownRequestError`. I'm using the Prisma client in Nest.js and here's my service code.

```typescript
import { Injectable } from '@nestjs/common';
import { PrismaService } from 'src/prisma/prisma.service';
import { registrationRequest } from './validations';
import { User } from '@prisma/client';
import { hash } from 'argon2';
import { PrismaClientUnknownRequestError } from '@prisma/client/runtime';

interface Service {
  register: (request: registrationRequest) => Promise<User>;
}

@Injectable()
export class AuthService implements Service {
  constructor(private prisma: PrismaService) {}

  async register({ name, email, ...request }: registrationRequest) {
    try {
      const password = await hash(request.password);
      const user = await this.prisma.user.create({
        data: {
          name,
          email,
          password,
        },
      });
      return user;
    } catch (error) {
      if (error instanceof PrismaClientUnknownRequestError) {
        // Property 'code' does not exist on type 'PrismaClientUnknownRequestError'.ts(2339)
        if (error.code === 'P2002') {}
      }
    }
  }
}
```

### How to reproduce

1. Throw a Prisma Client query error in an async function.
2. Catch the error and check if the error is an instance of `PrismaClientUnknownRequestError`.
3. If yes then check the available properties on the error object.
4. The property `code` will not be available on the error object.

### Expected Behaviour

A string property `code` should exist on the error object which is an instance of `PrismaClientUnknownRequestError`.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id         Int        @id @default(autoincrement())
  name       String
  email      String     @unique
  password   String
  created_at DateTime   @default(now())
  updated_at DateTime   @updatedAt
  bookmark   Bookmark[]

  @@map("users")
}

model Bookmark {
  id          Int      @id @default(autoincrement())
  title       String
  description String?
  link        String
  user_id     Int
  user        User     @relation(fields: [user_id], references: [id])
  created_at  DateTime @default(now())
  updated_at  DateTime @updatedAt

  @@map("bookmarks")
}
```

### Environment & setup

- OS: Ubuntu 20.04.4 LTS
- Database: MariaDB v10.3.34
- Node.js version: 16.14.2

### Prisma Version

```
prisma                  : 3.11.1
@prisma/client          : 3.11.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 1a2506facaf1a4727b7c26850735e88ec779dee9
Studio                  : 0.458.0
```

**Comment by IBRAHIMDANS** [comment]
I have same bug 
if i build my app bootstrap with nestJS
![image](https://user-images.githubusercontent.com/25392908/223406844-d4b51fed-4cbb-40a7-8e9a-dd71b2a9805c.png)

**Comment by hassan91199** [comment]
"PrismaClientUnknownRequestError" does not have any error property. Use PrismaClient**Known**RequestError. have a look at docs [here](https://www.prisma.io/docs/reference/api-reference/error-reference)

**Comment by XaydarovMarufjon** [comment]
`npx prisma migrate dev` or `prisma migrate dev`
### and 
prisma db pull **and** prisma db push
