### ISSUE TITLE
GitHub Actions workflow `update-studio-version.yml` only updated `@prisma/studio-server`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12626]
https://github.com/prisma/prisma/blob/main/.github/workflows/update-studio-version.yml

... and not `@prisma/studio` - no idea why. So right now that workflow is not a replacement for waiting for Renovate to learn about an Studio update and open a PR.

Manual workaround:
```
npm install --global pnpm@6
pnpm update -r @prisma/studio@latest @prisma/studio-server@latest
```

**Comment by Jolg42** [comment]
The action now updates both. Though Renovate also does that.
