### ISSUE TITLE
Prisma `migrate reset` + `seed` fails for Planetscale

### ISSUE THREAD

**Issue by timotius02** [prisma/prisma#12633]
### Bug description

Seed script fails after `prisma migrate reset` due the tables not existing as you query them. 

Right now this can be circumvented by running `prisma db push` after your seed script fails then re-run your script but it ruins the flow of development. 

### How to reproduce

1. `prisma migrate reset`
2. seed script triggers
3. prisma fails `The table (not available) does not exist in the current database.`

### Expected behavior

`prisma migrate reset` should reset the db, regenerate the tables, and then run seed script. 

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}
datasource db {
  provider = "mysql"
  url = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Video {
  id String @id
  lastUpdated DateTime @updatedAt
  name String
  viewCount String // Viewcount is string bc Youtube API returns string and I don't want to deal with BIGINTs
  thumbnail String
  playlist Playlist @relation(fields: [playlistId], references: [id])
  playlistId Int

  @@index([playlistId])
}

model Playlist {
  id Int @id @default(autoincrement()) 
  youtubeId String?
  name String
  createdAt DateTime
  thumbnail String
  type PLAYLIST_TYPE
  videos Video[]
}

enum PLAYLIST_TYPE {
  PLAYLIST
  CHANNEL
}
```

### Environment & setup

- OS:  Windows, Ubuntu (via WSL)
- Database: Planetscale
- Node.js version: 17.5.0

### Prisma Version

```
prisma                  : 3.11.1
@prisma/client          : 3.11.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 1a2506facaf1a4727b7c26850735e88ec779dee9
Studio                  : 0.458.0
Preview Features        : referentialIntegrity
```

**Comment by janpio** [comment]
`migrate reset` is a command meant to be used in combination with a `migrations` folder with individual migrations. On PlanetScale you usually do not use that, but `prisma db push`, to migrate your changes. So `reset` is removing your information, but can not recreate it as it is missing the information what to do.

**Comment by timotius02** [comment]
Yes after playing around I see that that's the current best practice for Planetscale. The problem then becomes when you are iterating on your schema or your seed script, how are you supposed to reset your DB to re-seed?

**Comment by timotius02** [comment]
I went over a bunch of resources from Prisma and Planetscale and it looks like the best way is to use `prisma db push --force-reset` then `prisma db seed` independently. Is this correct?
