### ISSUE TITLE
PostgreSQL Hstore Hash Maps or Wildcard Searches

### ISSUE THREAD

**Issue by klxu03** [prisma/prisma#12636]
## Problem

When using Prisma with PostgreSQL, there doesn't seem to be any support for using a hash map hstore data type. That would be nice to have. Likewise, there doesn't seem to be support for Wildcard searching like "aunt%" for aunt jeanne and aunt may both popping up. These would be nice features to have.

**Comment by janpio** [comment]
Can you please open two separate issues for this, one feature requests for the "hash map hstore data type" and one bug report for the unexpected behavior of wildcard search? Thanks.
