### ISSUE TITLE
Test for `DEBUG` logging

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12677]
You can use the `DEBUG` env var to enable debug logging for both Prisma CLI and Prisma Client (documented at https://www.prisma.io/docs/concepts/components/prisma-client/debugging). We should have tests, that makes sure that logging works and does not unintentionally change.

We need to test: 
- Different CLI commands
- Different `engineType`s
- Different Prisma Client queries and behaviors

**Comment by danielhoherd** [comment]
Tests would be great. Right now my team is trying to use the examples in the docs and the examples do not appear to work. So either they don't work, or we are misreading the docs. Having the tests available as a code reference would be one more point of reference, which would be helpful.
