### ISSUE TITLE
NonNullable JSON data type attribute

### ISSUE THREAD

**Issue by yss14** [prisma/prisma#12689]
## Problem

Columns with data type `Json` can technically be nullable, even thought they are defined as not nullable in the prisma schema.
However, it would be very helpful to mark `Json` columns as absolutely not nullable via a data type attribute.

This would prevent a lot of tedious logic in larger codebases which try to enforce a strict type-safety.

Example:

To please the typescript compiler that prisma queries really don't return a `null` value (because we enforce that on data write/update operations) for json columns, we have a lot places which look like this:

```typescript
const entity = await prisma.entity.findMany(...)

return {
      ...entity,
      entries: entity.entries.map((entry) => ({
        ...entry,
        someSubEntity: {
          ...entry.someSubEntity,
          attributes: entry.someSubEntity
            .attributes as Attributes, // we need to tell tsc that there are really no null values stored in the json column
        },
      })),
    }
```

## Suggested solution

Introduction of a `@jsonNotNullable` data type attribute which ensures that both for write / update operations on the model no `null` value is written to the column and that the generated `JsonValue` type does not contain `... | null`.
E.g. the generated type would be something like `JsonValueNotNullable = string | number | boolean | JsonObject | JsonArray`

## Alternatives

None.

## Additional context

None.

**Comment by janpio** [comment]
> Columns with data type Json can technically be nullable, even thought they are defined as not nullable in the prisma schema.

Can you elaborate on that a bit? Is this about the database preventing `foo = null` but not `foo = "null"` (as the second is valid json technically)?

**Comment by yss14** [comment]
While setting up a demo usecase repository I recognized that even with my proposed feature we would run into typescript issues, since json columns can't be typed yet in prisma.

So I guess we have to wait for https://github.com/prisma/prisma/issues/3219 and I think the problem described above would also be solved with typed json columns feature.

**Comment by janpio** [comment]
Can you still elaborate on the perceived problem right now that I quoted? We talked about this internally, but were not sure if this is _actually_ a problem right now that we missed.

**Comment by yss14** [comment]
Ok, so take the following schema:

```
model MyEntity {
  id           Int                @id @default(autoincrement())
  json_column  Json
}
```

The `json_column` is not marked as nullable in the prisma schema, but the generated type for that column is still `Prisma.JsonValue`, which boils down to `string | number | boolean | JsonObject | JsonArray | null`. So the generated type still includes `| null`, which is totally fine from a technical view, because `JSONB` columns in PostgreSQL which are marked as `NOT NULL` still can contain a `null` value since `null` is a valid json value.

So the idea of the `@jsonNotNullable` data type attribute was, that prisma enforces that no `null` value can the written to a column annotated by that attribute, and thus the generated type for the `json_column` column would also not contain the `null` value in the union type (e.g. `JsonValueNotNullable = string | number | boolean | JsonObject | JsonArray`).

**Comment by janpio** [comment]
So I understand correctly that `json_column Json` already makes sure there is not database level `NULL` value in that column (which is also backed by the types, as it requires a value to be set and the field is not optional), but both the database and the types allow a Json `null`. Correct? And you want a way to forbit that as well?

**Comment by aqrln** [comment]
To clarify: this isn't about Prisma incorrectly accepting JavaScript `null` value as the value of a non-optional `Json` field (which I just double-checked isn't the case), this is a feature request to be able to narrow the type of the value stored in a `Json` column so that the type of the result of read operations won't include `null`, and the write operations won't accept `Prisma.JsonNull`, right?

**Comment by janpio** [comment]
Yes that is how I understood you now, you want to disallow a Json `Null` or `Prisma.JsonNull` for a specific field to further clarify what is expected and wanted in a column. The database will not be able to express that constraint (without getting fancy), but Prisma could definitely do that in the types and via validations or similar.

I think that sounds like a valid feature request if you can describe it in a way the majority of my colleagues will understand :D

**Comment by yss14** [comment]
@aqrln Exactly! :)

**Comment by AnthonySLWhite** [comment]
I'm also really needing this :+1:
