### ISSUE TITLE
Prisma Engine Detects and Installs x86_64 Engines on Android ARM64

### ISSUE THREAD

**Issue by snuggs** [prisma/prisma#12695]
Hey was just testing `prisma generate` on my chromebook/android device and receive the following:

_Please let me know how I can help_ 🙏🏽  
_⚠️ paths edited in error messages_
```
% npx prisma generate
Environment variables loaded from db/.env
Prisma schema loaded from db/schema.prisma
Error: Unable to require(`<...>/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`)
 dlopen failed: "<...>/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node" is for EM_X86_64 (62) instead of EM_AARCH64 (183
```

```
├── @prisma/client@3.11.1
├── prisma@3.11.1
```

```
{
  npm: '8.5.2',
  node: '16.14.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1m',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}
```

**Comment by CanKolay3499** [comment]
It only happens on android devices I created a pr for it but they rejected. Also theres no engines build for android.

**Comment by aqrln** [comment]
Hi @snuggs! Could you clarify which platform are you running Prisma on? The title mentions Debian, however the issue description says Android and ChromeOS. Given both, I'd assume a Debian container or chroot environment, is that correct? Could you also check if the problem persists for you with the latest Prisma?
