### ISSUE TITLE
Bug Report: EP/0336 CANNOT ADD/DELETE PRISMA ESTIMATE INSERTIONS

### ISSUE THREAD

**Issue by Tiago139** [prisma/prisma#12721]
Hello,

I work at Starcom and help manage our Walmart account (Tiago Fernandes - tiago.fernandes@starcomww.com).

I have been trying to add insertions into Print Buy Tool Kit but I have been greeted by an error message that read:
"EP/0336 CANNOT ADD/DELETE PRISMA ESTIMATE INSERTIONS"

I have attached an image for reference as well.
![DDS Error Message](https://user-images.githubusercontent.com/103199905/162221860-dd14bd1f-2d23-434b-adc8-b64a5de5f5e0.png)

**Comment by janpio** [comment]
Hey @Tiago139, I don't think we are the correct Prisma for this. This Prisma here is a ORM for databases in the Node.js ecosystem. Sorry we can not help you with this request.
