### ISSUE TITLE
Coerce `Decimal` to `String` for MongoDB

### ISSUE THREAD

**Issue by aladinflux** [prisma/prisma#12749]
## Problem

We have built our project completely based on `Decimal` fields, we can't afford to change all the code which uses `Decimal` arithmetics functions back to JS arithmetic operators.

We tried using middleware, to convert back and forth, however, it won't work for deeply nested queries and it can become very quickly unmanageable if we try to do handle nesting in the middleware, because some fields are intended to be `Int` while others `Decimal`. We can't just run generic conversion and we have to specify fields.

## Suggested solution

Prisma Client should still accept `Decimal` field for Mongo DB and just call `toString` when inserting and create a `Decimal` when retrieving.

## Alternatives

The only alternative I can think of is https://github.com/prisma/prisma/issues/4211

**Comment by masterbater** [comment]
They will add it once mongodb rust driver will suppot Decimal128

**Comment by aladinflux** [comment]
Yeah, this is for an interim solution cause apparently, Decimal128 will be supported by May or June.

**Comment by janpio** [comment]
Additional information: https://github.com/prisma/prisma/issues/12749

**Comment by janpio** [comment]
Took a bit longer, but https://github.com/prisma/prisma/issues/12637 is now unblocked by the dependency from MongoDB supporting Decimal. That means we will definitely not support String coercion here, but really go all the way.

I'll close this issue because of that. Thanks anyway for the suggestion @aladinflux.
