### ISSUE TITLE
`PRISMA_CLI_BINARY_TARGET` not outputting specified binary types in `node_modules/.prisma/client`

### ISSUE THREAD

**Issue by rcbevans** [prisma/prisma#12744]
### Bug description

We build different flavors of our node project to deploy to different platforms.

I was specified all required platforms in the `binaryTargets` array in the schema client generator, but this was leading to bundles including query client binaries for other platforms when we deploy.

To try and reduce the size of the deployed bundle, I attempted to remove the `binaryTargets` array from the schema, and instead in CI specify the `PRISMA_CLI_BINARY_TARGETS` environment variable so that the output build artifact includes only the binaries required for the deployment target.

Unfortunately when specifying the environment variable, the package install isn't including the specified targets in `node_modules/.prisma/client`, only the native.

### How to reproduce

1. Create a prisma based project
2. Execute `PRISMA_CLI_BINARY_TARGETS=<non-native-platform> yarn install`
3. Observe that the non-native platform binaries are downloaded into `node_modules/@prisma/engines`, but that the non-native query engine is not installed into `node_modules/.prisma/client`

### Expected behavior

I expected `PRISMA_CLI_BINARY_TARGETS` to be a replacement to the schema `binaryTargets` to override the target platform.

### Prisma information

"@prisma/client": "^3.12.0",
"prisma": "^3.12.0",

### Environment & setup

Linux 5.16.15-76051615-generic
Node v16.14.0

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
Preview Features        : interactiveTransactions
```

**Comment by janpio** [comment]
`PRISMA_CLI_BINARY_TARGETS` only defined the binary targets for the _CLI_ (hence the `CLI` in the name 😆).

If you want to use an env var to define the binary targets of the client, you can do that via `binaryTargets = env(FOO)` (or slightly similiar in the `generator client` block of your Prisma schema file.

Please report back if that indeed works.

**Comment by janpio** [comment]
Ping @rcbevans - Can you please take a look at my response? Thanks.

**Comment by sarink** [comment]
It does seem odd that there is no way to override the `binaryTargets` functionality from `schema.prisma` with any sort of argument or environment variable. Furthermore, it's not really clear how `PRISMA_CLI_BINARY_TARGETS`, in its current implementation, is useful for deployment when the engine in `node_modules/.prisma/client` winds up being different than the one specified.

**Comment by janpio** [comment]
> Furthermore, it's not really clear how `PRISMA_CLI_BINARY_TARGETS`, in its current implementation, is useful for deployment when the engine in `node_modules/.prisma/client` winds up being different than the one specified.

It is not supposed to be useful for that use case. The environment variable influences the engine files downloaded for the _CLI_ (hence the `PRISMA_CLI...`) and not for Prisma Client.

As @rcbevans unfortunately did not respond, I am closing this issue.
