### ISSUE TITLE
Data Proxy: Client network socket disconnected

### ISSUE THREAD

**Issue by CruelMoney** [prisma/prisma#12778]
### Bug description

I'm using Mongodb Cloud with the Prisma data proxy. 

Every now and then I'll get the following error: `Client network socket disconnected before secure TLS connection was established` in production. 

It seems to only happen when using the client functions `runCommandRaw` or `aggregateRaw`.

The connection string I've entered for the data proxy looks like this: `mongodb+srv://<user>:<pass>@<host>/db?maxPoolSize=500`

You can see the only option is `maxPoolSize`. Maybe the proxy requires `retryWrites` to set and true?

### Prisma information

Prisma function:
```
 await prisma.$runCommandRaw({
    update: 'QuotaUsage',
    updates: [
      {
        q: {
          month: new Date().getUTCMonth(),
          year: new Date().getUTCFullYear(),
          userId: { $oid: userId },
        },
        u: {
          $inc: {
            usage: quotaUsage,
          },
        },
      },
    ],
  });
```

Relevant schema part
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["dataProxy"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

...

model QuotaUsage {
  id     String @id @default(auto()) @map("_id") @db.ObjectId
  userId String @db.ObjectId
  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
  usage  Int    @default(0)
  month  Int
  year   Int

  @@unique([userId, month, year])
}
```

### Environment & setup

- OS: Vercel Serverless (Ubuntu?)
- Database: MongoDB 5
- Node.js version: 14

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
Preview Features        : dataProxy
```

**Comment by garrensmith** [comment]
@CruelMoney could you mind opening up a ticket in intercom so that the data proxy support can help you.

**Comment by phillip-voidcloud** [comment]
Hi, I just started using Prisma Postgres client. I am using data proxy w/ Netlify functions. I have been seeing intermittent socket issues as well.

"Client network socket disconnected before secure TLS connection was established":

```
Apr 12, 04:05:29 PM: b3c9f9a7 ERROR  GET [products/:sku] Error responding: PrismaClientKnownRequestError: Apr 12, 04:05:29 PM: b3c9f9a7 Invalid `prisma.product.findUnique()` invocation:

Apr 12, 04:05:29 PM: b3c9f9a7   Client network socket disconnected before secure TLS connection was establishedApr 12, 04:05:29 PM: b3c9f9a7     at Object.request (/var/task/node_modules/@prisma/client/runtime/proxy.js:94:56)Apr 12, 04:05:29 PM: b3c9f9a7     at processTicksAndRejections (internal/process/task_queues.js:95:5)Apr 12, 04:05:29 PM: b3c9f9a7     at async t._request (/var/task/node_modules/@prisma/client/runtime/proxy.js:111:1462)Apr 12, 04:05:29 PM: b3c9f9a7     at async /var/task/netlify/functions/products.js:6550:21 {Apr 12, 04:05:29 PM: b3c9f9a7   code: 'ECONNRESET',Apr 12, 04:05:29 PM: b3c9f9a7   clientVersion: '3.12.0',Apr 12, 04:05:29 PM: b3c9f9a7   meta: undefinedApr 12, 04:05:29 PM: b3c9f9a7 }
```

And more commonly, I have been seeing this one which has been a bit disruptive. When it starts to happen, there doesnt appear to be anything I can do to fix it. It will just go away on its own after approx. 5-10minutes.

"socket hang up":

```
Apr 12, 07:15:16 PM: 1a65d2ee Invalid `prisma.product.findUnique()` invocation:

Apr 12, 07:15:16 PM: 1a65d2ee   socket hang upApr 12, 07:15:16 PM: 1a65d2ee     at Object.request (/var/task/node_modules/@prisma/client/runtime/proxy.js:94:56)Apr 12, 07:15:16 PM: 1a65d2ee     at async t._request (/var/task/node_modules/@prisma/client/runtime/proxy.js:111:1462)Apr 12, 07:15:16 PM: 1a65d2ee     at async /var/task/netlify/functions/products.js:6550:21 {Apr 12, 07:15:16 PM: 1a65d2ee   code: 'ECONNRESET',Apr 12, 07:15:16 PM: 1a65d2ee   clientVersion: '3.12.0',Apr 12, 07:15:16 PM: 1a65d2ee   meta: undefinedApr 12, 07:15:16 PM: 1a65d2ee }
```

What could be causing this? Should I also open a ticket w/ intercom?

**Comment by phillip-voidcloud** [comment]
I thought maybe I was hitting a connection limit with my Heroku hosted PostgreSQL database, but that does not appear to be the case. I am using their standard0 plan, which allows for 120 connections. I am currently seeing the issue with approx. 15-20 connections right now

**Comment by phillip-voidcloud** [comment]
Hm so actually the above doesn't appear to have helped for long. I started receiving more socket errors just now and the errors wouldn't go away. So I tried creating a new data proxy connection string on Prisma Cloud.. and the problem went away instantly.

So sounds like the node I had went into a bad state?

**Comment by phillip-voidcloud** [comment]
Any updates on this? Nothing I try seems to solve the socket errors. And it seems to be related to the AWS connection node that is being used going into a bad state of some sort.

Would disabling the data proxy work better? What are the consequences of disabling it and using serverless functions?

**Comment by janpio** [comment]
To report problems with the Data Proxy, best use the support channels in Prisma Data Platform - mainly the Intercom chat available there I think.

Your description of this being a server (Data Proxy) side problem sounds correct to me based on the error message. Without using the data proxy you would obviously avoid that problem, but then it would depend on how your application uses the serverless functions if you would hit the connection limit available on your database and would need to try to counteract that im some other way. Hard to evaluate from the outside.

**Comment by phillip-voidcloud** [comment]
Thanks @janpio I have turned off data proxy for now.

I found out [Heroku PostgreSQL has connection pooling already](https://devcenter.heroku.com/articles/postgres-connection-pooling). I know Heroku tends to be more restrictive on what you can/can not do, so wondering if that's the potential reason for this issue with Prisma data proxy?

But as of now, I have enabled the connection pooling the Heroku way, and am not noticing any issues anymore. I will message if I start to notice any issues again.

**Comment by janpio** [comment]
No, Heroku should not be a problem in any way for Prisma's Data Proxy as far as I am aware.

**Comment by millsp** [comment]
Hey everyone, I just wanted to let you know that we shipped [prisma@3.15.0](https://github.com/prisma/prisma/releases) with a `RequestError` that will be automatically retried in case of network errors. Only if the error is not recoverable after a few retries with backoff, it will throw an exception.

**Comment by eposha** [comment]
I have the same issue

**Comment by millsp** [comment]
Hey @eposha, please open a new issue with the necessary details for us to be able to look into it. Add as many information as you can collect so that we can better understand what is going on. Thanks.
