### ISSUE TITLE
[SQLite] Integers > Number.MAX_SAFE_INTEGER are rounded

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma#12784]
### Bug description

SQLite uses dynamic typings which enables storing pretty much any value inside a column, regardless of the column type. This lead to issues wrt. to integers.

Consider a column of type `Integer`, which traditionally, represents a 32-bit signed integer for most databases.
Now, manually store a 64-bit signed integer in that column. eg: `i64::MAX` == `9_223_372_036_854_775_807`.

The Query Engine will read that value as an `i64` (because that's how all `Integer`s are deserialized in the Query Engine) and pass it to our json serializer (`serde_json`), which will serialize it as a number.

```rust
serde_json::to_string_pretty("9223372036854775807")?; // "9223372036854775807"
```

The problem is that Javascript only supports number up to `2^53 - 1`. So when deserializing that JSON,  that number will get weirdly rounded. Try the following script below in your browser console 👇

```javascript
parseInt("9223372036854775807") // 9223372036854776000
``` 

This _does not_ happen for other SQL databases because they're all strongly typed and prevent `Int64` values to be inserted in `Int32` columns in the first place.

Pretty much the _same_ issue happens in MongoDB though, if you manually insert a `Bson::Int64` into your database and try to read it as a Prisma `Integer` field.

### Solutions (all breaking)

**1. Return a `BigInt` if the integer is too large**

We _could_ dynamically serialize integers as either `Number` (if value is in `i32` range) or `BigInt`. However, this would terribly downgrade the developer experience and potentially lead to bad issues.

First, we'd have to change the TS typings for all integers on SQLite to be: `number | BigInt`. This makes it very cumbersome to deal with client results since you'd always have to check whether a value is one or another.

Second, if you somehow ignore the typings, you might end up with a perfectly working code in dev that fails in production because of your dataset. If your dataset in prod contains a number > `i32::MAX`, we'd coerce it to `BigInt` and so any arithmetic operations done on this value with a value that's _not_ a `BigInt` would lead to a runtime error.

```js
1n + 1 // Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions
```

**2. Always return `BigInt`s**
To prevent the potential inconsistencies in the results, we could _always_ coerce SQLite integers to `BigInt`, just to ensure consistency and avoid weird JS rounding when values are > `Number.MAX_SAFE_INTEGER`. However, since `BigInt`s cannot be transparently used with "regular" JS numbers, it makes the experience pretty cumbersome, especially if you know none of your values are greater than an int32.

**3. Error out if a value > `i32::MAX` is read from a column of type `Integer`**
This option would ensure the "strictness" of the data that we return to the Client. The only way for users to read `BigInt` values from their db would be to migrate their column to `BigInt`, in which case we'd always coerce the values to `BigInt`.

### How to reproduce

1. Setup a SQLite db with the Prisma Schema below
2. Insert the following value in the int column: `9223372036854775807`
3. Execute the script below

```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient();

  console.log(await prisma.testModel.findMany());
}

main();
```

### Prisma information

```prisma
model TestModel {
  id Int @id
  int Int
}
```

**Comment by seth** [comment]
Is letting the user specify the behavior an option? For example, implement (3) and give the user a way when making the query to ask for (2). Do we have any examples in other areas of that sort of configurability?

**Comment by DeepDoge** [comment]
Yeah just realized this as well when i realized `unix time` im getting from the db was wrong.
I was expecting Int to be 64bit since there is no Long or etc and JS already supports bigger numbers
And I thought BigInt was for real numbers.

**Comment by janpio** [comment]
Prisma generally tries to avoid configuration and choose the correct behavior for all users. Hence we have almost no ways to configure how Prisma Client behaves regarding queries.

Here as well I would say that the Prisma schema does not match the data that is returned from the database, so (3) sounds like a valid choice. (Optionally but optimally with an error message that explains to the user how to circumvent this [replace `Int` with `BigInt` in the Prisma schema and optimally migrate the database]).

**Comment by dpetrick** [comment]
Note: We agree on option 3. It's the most correct and has a clear actionable way forward for the user.

**Comment by matthewmueller** [comment]
> Pretty much the same issue happens in MongoDB though, if you manually insert a Bson::Int64 into your database and try to read it as a Prisma Integer field.

Just curious. Does this code change also happen to fix the MongoDB issue?
