### ISSUE TITLE
Are there any api you can use to create a provider for a data base that prisma dosen't support yet???

### ISSUE THREAD

**Issue by David00154** [prisma/prisma#12809]
### Discussed in https://github.com/prisma/prisma/discussions/12805

<div type='discussions-op-text'>

<sup>Originally posted by **David00154** April 13, 2022</sup>
I want to create a custom provider that prisma dosen't support yet but I cant see any where in the docs on how to</div>

**Comment by janpio** [comment]
See response in the discussion you opened.
