### ISSUE TITLE
Look at and handle potential differences for index types to CockroachDB

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12818]
CockroachDB is similar to PostgreSQL but not the same.

Is this also the case for index types that we are planning to integrate via #12376? Do we have to differentiate in any way?

Good place to start:
https://www.cockroachlabs.com/docs/stable/indexes.html
https://www.cockroachlabs.com/docs/stable/schema-design-indexes.html
https://www.cockroachlabs.com/docs/stable/create-index.html
https://www.cockroachlabs.com/blog/index-selection-cockroachdb-2/

**Comment by pimeys** [comment]
Differences based on CDB's answer:

- Only GiST is supported
- No special opclasses, so only the ones without should work.

**Comment by pimeys** [comment]
Closing in favor of: https://github.com/prisma/prisma/issues/13065
