### ISSUE TITLE
Prisma connection limit is inconsistent with number of connections shown in AWS RDS

### ISSUE THREAD

**Issue by arcticmatt** [prisma/prisma#12855]
### Bug description

Recently, we ran into this issue:

```
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 300)
```

But if I look at the AWS RDS Postgres database that Prisma is using, the number of connections never goes over 100

<img width="888" alt="image" src="https://user-images.githubusercontent.com/4356178/163683829-00fcc59e-9080-4729-b8bb-e7b900f6179c.png">

Based on [Prisma's docs](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool), it seems like these numbers should match:

> If there are no idle connections available in the connection pool, the query engine opens additional database connections and adds them to the connection pool until the number of database connections reaches the limit defined by connection_limit.

So I'm searching for the source of inconsistency.

### How to reproduce

Reproduce by writing a script that uses `connection_limit=300`, and sending over > 300 queries concurrently.

Prisma gives me the error, but RDS doesn't show an increase in the number of connections

### Expected behavior

I would expect the Prisma `connection_limit` to be consistent with the number of connections that AWS RDS shows

### Prisma information

Not relevenant for this

### Environment & setup

- OS: MacOS and Ubuntu
- Database: PostgreSQL
- Node.js version: 16.7.0

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.8.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
Preview Features        : interactiveTransactions
```

**Comment by arcticmatt** [comment]
Going to open a new issue that is more accurate

**Comment by janpio** [comment]
Did you? That sounds indeed like an interesting problem we want to look into.

Although: One of the recent versions drastically improved the connection pool, so you might want to test with a newer version as well.

**Comment by janpio** [comment]
Ah, just found: https://github.com/prisma/prisma/issues/12858 👍
