### ISSUE TITLE
Some errors are obfuscated by interactive transactions when using `binary` engine

### ISSUE THREAD

**Issue by driimus** [prisma/prisma#12862]
### Bug description

Runtime errors such as `CHECK` constraint failures are obfuscated by interactive transactions when `engineType  = "binary"`, making it impossible to appropriately handle rejected transactions.

Only tested this with `postgres` so far. 

Note that the `library` engine does not seem to have the same issue. CI output comparing both engine types: https://github.com/driimus/prisma-interactive-tx-errors/actions/runs/2184082955

### How to reproduce

1. Clone https://github.com/driimus/prisma-interactive-tx-errors
2. Run the tests locally using a `binary` engine
3. Notice that the test using an interactive transaction fails due to a nondescript error.

### Expected behavior

The original error / error message should be surfaced, similar to the `library` engine's behavior.

Expected:

```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: \"ERROR\", parsed_severity: Some(Error), code: SqlState(\"23514\"), message: \"new row for relation \\\"Post\\\" violates check constraint \\\"Post_viewCount_check\\\"\", detail: Some(\"Failing row contains (1, 2022-04-18 12:42:07.239, 2022-04-18 12:42:07.239, Minima nulla ea., null, f, -1, 1).\"), hint: None, position: None, where_: None, schema: Some(\"public\"), table: Some(\"Post\"), column: None, datatype: None, constraint: Some(\"Post_viewCount_check\"), file: Some(\"execMain.c\"), line: Some(2003), routine: Some(\"ExecConstraints\") }) }) })"
```

Received:

```
 ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: \"ERROR\", parsed_severity: Some(Error), code: SqlState(\"25P02\"), message: \"current transaction is aborted, commands ignored until end of transaction block\", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some(\"postgres.c\"), line: Some(1718), routine: Some(\"exec_bind_message\") }) }) })"
```

### Prisma information

[Minimal reproduction repo](https://github.com/driimus/prisma-interactive-tx-errors)

```schema.prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
  engineType      = "binary"
}

datasource db {
  provider = "postgres"
  url      = "postgresql://postgres:example@localhost"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String
  content   String?
  published Boolean  @default(false)
  viewCount Int      @default(0)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}
```

### Environment & setup

- OS: `Ubuntu 20.04.4 LTS`
- Database: `PostgreSQL`
- Node.js version: `16.14.2`

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/.pnpm/@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/.pnpm/@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/.pnpm/@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/.pnpm/@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by janpio** [comment]
Thanks for the great reproduction @driimus (as usual 🙇), I can indeed reproduce this, both with the original version and with updated Prisma: https://github.com/driimus/prisma-interactive-tx-errors/pull/2

An additional note: 
Even the "expected" error above might not actually be fully expected, as it does not look like a known Prisma error but something far more unstructured. That would deserve additional investigation by running the tests from the reproduction manually and comparing from the output when you run this outside of transactions. (Of course the outcome of that might be that this _generally_ does not work as expected - which would be even more meh.)

**Comment by danstarns** [comment]
The reason this is happening is due to the fact that this: 

```
CHECK ("viewCount" >= 0),
```

Has been added to the migration file, and because of the fact that it's not something that Prisma generates we don't have the logic to handle it. 

We are looking into propagating all of those errors.
