### ISSUE TITLE
prisma.$transaction(async (prisma) => { ... }) not allowed by typescript definitions

### ISSUE THREAD

**Issue by isaacs** [prisma/prisma#12867]
### Bug description

The `prisma.$transaction(PrimsaPromise[])` method is included in the typescript definition for the client, but `prisma.$transaction((prisma: PrismaClient): Promise)` is not.

### How to reproduce

In any typescript project:

```typescript
prisma.$transaction(async (prisma) => {})
```

Run `tsc -d`

Result:

```
app/models/organization.server.ts:70:30 - error TS2345: Argument of type '(prisma: any) => Promise<any>' is not assignable to parameter of type 'PrismaPromise<any>[]'.
  Type '(prisma: any) => Promise<any>' is missing the following properties from type 'PrismaPromise<any>[]': pop, push, concat, join, and 28 more.

70   return prisma.$transaction(async (prisma) => {
                                ~~~~~~~~~~~~~~~~~~~
```

### Expected behavior

It should include the `prisma.$transaction: (prisma: PrismaClient): Promise` type in the type definition file, since it exists in the code as well.

### Prisma information

```js
Prisma.prismaVersion = {
  client: "3.11.1",
  engine: "1a2506facaf1a4727b7c26850735e88ec779dee9"
}
```

### Environment & setup

- OS: Darwin moxy.lan 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

- Database: PostgreSQL
- Node.js version: v16.14.2

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.11.1
@prisma/client          : 3.11.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 1a2506facaf1a4727b7c26850735e88ec779dee9
Studio                  : 0.458.0

```

**Comment by Ustice** [comment]
I have two different databases which for which I use Prisma. One of them has this typing error, and other one does not.

**Comment by Valerionn** [comment]
Interactive transactions are a preview feature that you have to explicitly enable in your `schema.prisma`. According to your Prisma Version you don't have them enabled, you can do this by adding this to your `generator client` block in your schema file:
```
generator client {
  // ...
  previewFeatures = ["interactiveTransactions"]
}
```

Then, after running `npx prisma generate`, the typings should exist.

**Comment by garrensmith** [comment]
@Ustice does adding `previewFeatures = ["interactiveTransactions"]` fix your issue?

**Comment by isaacs** [comment]
@garrensmith That seems to do it!  Thanks!  It would be helpful (ie, probably have prevented this issue) if the required preview feature was called out in the docs for that function signature.

**Comment by janpio** [comment]
What docs do you mean exactly @isaacs? In theory the API should only be available in Prisma Client when the preview feature is already enabled, and the documentation for it in our prisma.io/docs also should mention the appropriate preview feature flag. Did we miss anything?

**Comment by isaacs** [comment]
Ah, I see it is at https://www.prisma.io/docs/concepts/components/prisma-client/transactions#the-transaction-api, but buried a bit. I got as far as "there are two ways", tried one, it didn't work, so came here.

Could add a note on that second bullet like "This requires additional config to enable, see below."

**Comment by janpio** [comment]
See suggested changes in https://github.com/prisma/docs/pull/3093 @isaacs - thanks for the suggestion.

(Hopefully this will not be a preview feature much longer, and everyone can just use it by default.)

**Comment by isaacs** [comment]
Perfect, thanks @janpio!

**Comment by yanavery** [comment]
Regarding this new functionality, it looks like for transactions to work as expected, each DB operation within the $transaction block must be using the `prisma` parameter that's passed into the $transaction block function callback ... The problem I'm having with that approach is that I'm using NestJS where my PrismaClient gets injected into each of my Service and DAO classes, so when one of the DB operations goes through one of those, the PrismaClient it uses is not the same instance as the one that initiated the $transaction, and therefore, that DB operation doesn't get rolled back when one of the other subsequent DB operations within the $transaction block is failing. Is there anything that you see that could be done to overcome this problem? Basically, the transaction would need to be somewhat global for the entire request ...

**Comment by Valerionn** [comment]
@yanavery I don't know what this has to do with this issue, but the easiest way is to add a new parameter to your functions with the prisma client:

```typescript
import { Prisma } from '@prisma/client';

@Injectable()
class UserService {
  constructor(private readonly prismaService: PrismaService) {}

  async createUser(data: any, prismaClient: Prisma.TransactionClient = this.prismaService): Promise<User> {
    return prismaClient.user.create({ data });
  }
}
```
or something like this and then call it like this:
```typescript
await this.prismaService.transaction(prisma => {
  // Do stuff
  const newUser = await this.userService.createUser(data, prisma);
}
```

Otherwise, if you don't want the parameter, then you can take a look at [async local storage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) to store the active transaction in the current context and then you could [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) the prisma service and redirect calls to the active transaction in the current context if one is set. But that's probably a bit more complex to do than the parameter solution above.

**Comment by yanavery** [comment]
Yeah, I thought about the extra parameter but that's a bit too intrusive to my taste. Currently looking at an approach using `cls-hooked` and building a small transaction wrapper that will encapsulate $transaction. Thanks for getting back!
