### ISSUE TITLE
Document new Prisma Client Metrics

### ISSUE THREAD

**Issue by garrensmith** [prisma/prisma#12877]
We need to document the following:

- The metrics we store
- How to get the metrics
- How to use the metrics with Prometheus (example code)
- How to use the metrics with Statsd (example code)

Epic: https://github.com/prisma/client-planning/issues/2

Equivalent docs team issue: https://github.com/prisma/docs/issues/3175

**Comment by janpio** [comment]
Documented at https://www.prisma.io/docs/concepts/components/prisma-client/metrics
