### ISSUE TITLE
Possibility to merge & extend prisma models ?

### ISSUE THREAD

**Issue by Gomah** [prisma/prisma#1291]
As there is most likely a parser for .prisma files ([See #92](https://github.com/prisma/prisma2/issues/92)) coming soon, it would be nice to have the possibility to merge & extend existing models, like:

**post.prisma**

```prisma
model Post {
  title String @pg.varchar(42)
  body  String
}
```

**core.prisma**

```prisma
import "./post.prisma"

model User {
  posts Post[]
}
```

Use case: let's assume `core.prisma` & `post.prisma` are a package dependency and I'd like to extend and overwrite the `Post` model:

**schema.prisma**

```prisma
import "dependency/prisma/core.prisma"

extend model Post {
  title String @pg.varchar(50)
  slug String
}
```

**Comment by webnoob** [comment]
Type-graphql is working on a way of auto generating the prisma files based on your models. If you use that alongs type script it'll allow you to have inheritence on your models and would so what you required.

Not the same, I know, but thought it worth mentioning.

**Comment by richardwardza** [comment]
I think the use case of https://github.com/prisma/prisma/issues/2371 (closed above) is very similar but slightly different. It would be great if it could be added to this feature.

**Comment by pantharshit00** [comment]
Pasting your sugeested API here:
```prisma
snippet AuditRecords {
  createdAt     DateTime   @default(now())
  createdBy     String
  updatedAt     DateTime   @updatedAt
  updatedBy     String
}

snippet StandardId {
  id          String   @default(cuid()) @id
}

Model User {
  @snippet['StandardId']
  name String
  email String
  @snippet['AuditRecords']
}

Model SomethingElse {
  id         Int       @id @default(autoincrement())
  name String
  email String
  @snippet['AuditRecords']
}
```

The API suggested in the first post of this issue is not final or anything, it is just to showcase the idea but we appreciate your suggestion :)

**Comment by alexkrautmann** [comment]
I found just came across this while searching for a way to extend/import models.

I'm trying to make an accounts-js database adapter for prisma v2, and I think I would need model import support to do it properly (and fully type-safe in ts). The idea is that the accounts-js database adapter package exports the base user models (user, user email, user sessions etc), and the consumer can use these user models in their own models. They could also extend these models with more fields.

Without support for this, these are the only alternatives I can think of:

1) Create tooling in the adapter to generate the user types in prisma.schema. But generating a file that itself is used to generate a client doesn't seem right.
2) Basically tell the consumers of the adapter to copy+paste some models into their schema.prisma. This is bad for obvious reasons.

**Comment by matthewmueller** [comment]
I believe the extending models part would be solved by: https://github.com/prisma/prisma/issues/2506

I'm not sure we'll want to _merge_ models, but maybe as you said, _override_ the field. 

Can you describe why you'd like to override a field?

**Comment by Gomah** [comment]
Yup, interface field would be great

> Can you describe why you'd like to override a field?

If multiple models are treated as a dependency, being able to extend & override its original value would be ideal, e.g:

```prisma
# dependency/user.prisma
model User {
  id      String   @default(cuid()) @id
  email   String @unique
}
```

```prisma
# dependency/post.prisma
model Post {
  id       String   @default(cuid()) @id
  title    String    @pg.varchar(42)
  body     String
}
```

Vendor applications:

```prisma
import "package/user.prisma"
import "package/post.prisma"

extend model User {
  posts  Post[]
}

extend model Post {
  title    String @pg.varchar(50)
  user     User @relation(fields: [userId], references: [id])
  userId   String 
}
```

That way, I can easily compose my prisma schema from existing datamodels.

I came across an interesting project that could "solve" this issue: https://github.com/amplication/prisma-schema-dsl

**Comment by smcelhinney** [comment]
I literally had this use case today, could find nothing else, so I decided to write something. It's a bit rough and ready, but I'll take contributions if anyone wants to help? 

https://github.com/smcelhinney/prisma-merge-schema

💯 agree this should be part of the core framework though.

**Comment by rostislav-simonik** [comment]
I needed a little bit different, but huge thanks  @smcelhinney for inspiration.

I created an alternative I'd say ugly preprocessor, meantime it gets resolved in Prisma framework. Also based on RegExp than AST, so anytime it can break.

https://github.com/technology-studio/prisma-schema

based on 
@smcelhinney 's https://github.com/smcelhinney/prisma-merge-schema

his approach is more suitable if you are using introspection, and you don't want to pollute schema with decorators 

in my case, I don't need to use introspection (or just once), feel free to use any of them. 

similar issues: 
* https://github.com/prisma/prisma/issues/2371
* https://github.com/prisma/prisma/issues/3520

**Comment by Stringsaeed** [comment]
@alexkrautmann for accountjs adapter check out this https://github.com/accounts-js/accounts/discussions/1145

**Comment by janpio** [comment]
This feature request is now considered via https://github.com/prisma/prisma/issues/2377#issuecomment-821203725 - let's continue over there and make sure all concerns from here are considered.

**Comment by Ehbraheem** [comment]
@janpio Any luck with this particular feature?
