### ISSUE TITLE
Unable to catch error in query

### ISSUE THREAD

**Issue by puchm** [prisma/prisma#12911]
### Bug description

This is my query:

```ts
try {
  return await prisma.user.findUnique({
      where: {
          id: 'HQNsa'
      }
  })
} catch(e) { // this does not catch the error
  console.log(e);
}
```

The `id` column is of type `@db.Uuid` in Postgres so obviously this request will fail because it is not a valid UUID.
This is the error:

```
C:\Users\...\node_modules\@prisma\client\runtime\index.js:45578
        throw new PrismaClientKnownRequestError(message, e.code, this.client._clientVersion, e.meta);
              ^
PrismaClientKnownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


  Inconsistent column data: Error creating UUID, invalid length: expected one of [36, 32], found 5
    at Object.request (C:\Users\...\node_modules\@prisma\client\runtime\index.js:45578:15) {
  code: 'P2023',
  clientVersion: '3.12.0',
  meta: {
    message: 'Error creating UUID, invalid length: expected one of [36, 32], found 5'
  }
}
```

My problem is not that the error gets thrown. I completely understand what the problem is with my query. However, my problem is that **my try / catch block is unable to catch it**. I therefore think that the error gets thrown in another scope.

Is this intended? I tried many things (e.g. also wrapping the PrismaClient instantiation into a try / catch block or not putting await in front of the query) but nothing seems to work.

I know that I could check whether my input string is a UUID before querying but I would like to just catch the error.

### How to reproduce

1. Create a Prisma schema with a postgres datasource and create a simple model where the `@id` column is of type `@db.Uuid`.
2. Push the schema to the DB
3. Try running the following query (change model accordingly)
```ts
prisma.user.findUnique({
    where: {
        id: 'HQNsa'
    }
})
```
4. Try to catch the error that occurs to prevent the server from crashing. I wasn't able to.

### Expected behavior

I would like to be able to catch errors where they occur, not have them crash my server without me being able to catch them.

### Prisma information

E.g.:

```prisma
datasource db {
    provider = "postgresql"
    url = env("DATABASE_URL")
}

generator client {
    provider = "prisma-client-js"
}

model User {
    id String @id @db.Uuid
    name String
}
```

### Environment & setup

- OS: Windows 10
- Database: Postgres
- Node.js version: 16.14.2

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by ludovicgueth** [comment]
Hello,

I had the same problem, I think that when you return the promise, it's the level bellow your resolver that will catch the error.
In my case, it's my apollo-server formatError() plugin that catch it.
You can do this to throw the error on the try catch :

```javascript
try {
 const user = await ctx.prisma.user.findUnique({...})
 return user
} catch (e) {
 console.log(e)
}
```

**Comment by puchm** [comment]
Hi, I just did a few modifications. I changed my query to what you proposed and implemented the formatError() function. None of them seemed to be able to solve it. The `catch` block still does not catch the error. The `formatError()` function formats the error but I don't think I am able to ignore the error in there.

**Comment by ludovicgueth** [comment]
I just tried this two exemple :


returning directly the promise in the try catch :
```javascript
async function main() {
  try {
    return prisma.user.findUnique({
      where: {
        id: "HQNsa",
      },
    });
  } catch (e) {
    // this does not catch the error
    console.log("THE ERROR IS CATCHED");
  }
}
```
It display this in my console :
```bash
yarn run v1.22.17
$ /Users/ludovicgueth/Developer/github/node_modules/.bin/ts-node index.ts
(node:27141) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.user.findUnique()` invocation in
/Users/ludovicgueth/Developer/github/index.ts:7:24

   4 
   5 async function main() {
   6   try {
→  7     return prisma.user.findUnique(
  Inconsistent column data: Error creating UUID, invalid length: expected one of [36, 32], found 5
    at Object.request (/Users/ludovicgueth/Developer/github/node_modules/@prisma/client/runtime/index.js:45578:15)
    at async PrismaClient._request (/Users/ludovicgueth/Developer/github/node_modules/@prisma/client/runtime/index.js:46405:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27141) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 1.65s.
```
the error is not caught and crash the server



resolving the promise in the try catch and then returning the user 
```javascript
async function main() {
  try {
    const user = await prisma.user.findUnique({
      where: {
        id: "HQNsa",
      },
    });
    return user;
  } catch (e) {
    // this does not catch the error
    console.log("THE ERROR IS CATCHED");
  }
}
```

It display this in my console :
```bash
yarn run v1.22.17
$ /Users/ludovicgueth/Developer/github/node_modules/.bin/ts-node index.ts
THE ERROR IS CATCHED
✨  Done in 1.26s.
```

I can catch the error properly when I don't return the promise directly, it does not make my server crash

**Comment by puchm** [comment]
I have found my issue. I am using a middleware, like this:

```
prisma.$use((params, next) => {
    const res = next(params);
    return {
        ...res,
        __model: params.model
    }
})
```

When I remove it, I can catch the error just fine. I would prefer not to have to remove it though since I need it for some other parts of my code.

What can I do about this?

If we can find a good way to handle errors in the middleware I would propose adding a section about this to the Middleware API docs.

**Comment by janpio** [comment]
Your middleware would be missing an `await` in front of `next(params)`. Is that just a problem of your comment or also the case in your middleware? I understand correctly you have this middleware to "brand" the model name into the result?

**Comment by puchm** [comment]
```
I understand correctly you have this middleware to "brand" the model name into the result?
```

Yes, that is exactly what I am doing. I added the `await` and it works now so I am closing this. Thanks guys!

**Comment by janpio** [comment]
Still interesting how that made this happen exactly honestly.

**Comment by janpio** [comment]
Ok, an internal discussion lead to this summary: The middleware split of the execution of `next` into a background promise as the `await` was not present, and the main code never could handle a throw because there was none on that level. 

We are still unclear why changing the code in the try to store the data in a variable made a difference honestly.

**Comment by ludovicgueth** [comment]
@janpio yes I confirm that !

**Comment by xegulon** [comment]
@janpio I had an error of this kind today in a script (latest prisma version), where I use await prisma.create in a try catch block which is inside a for loop, and the error makes things so that the for loop is blocked
