### ISSUE TITLE
Redundant migration of date-time defaults

### ISSUE THREAD

**Issue by chrisj-back2work** [prisma/prisma#12915]
### Bug description

Prisma re-alters tables to apply the same, unchanged default value in every new migration.

I have fields with date-time defaults like this:

```prisma
something_ts DateTime? @default("3000-01-01T00:00:00Z") @db.Timestamptz(6)
```

The initial migration script works fine; the default itself works fine. However every time that I run a new `prisma migrate dev`, all such fields appear in the migration script with a re-statement of the existing default value:

```sql
ALTER TABLE "whatever" ALTER COLUMN "something_ts" SET DEFAULT '3000-01-01 00:00:00 +00:00';
```

Every time I create a new migration, the above is generated for all fields with date-time defaults.

I attempted changing how I specify the default in `schema.prisma`, changing the existing `"3000-01-01T00:00:00Z"` to `"3000-01-01 00:00:00 +00:00"` -- that results in a Prisma error: `... is not a valid rfc3339 datetime string`; which is OK.

### How to reproduce

With a Postgres target DB, define a Prisma model with this field:

```
test_ts DateTime?     @default("3000-01-01T00:00:00Z") @db.Timestamptz(6)
```

Do an initial `prisma migrate dev`. Observe a line in the 1st generated migration script:

```sql
"something_ts" TIMESTAMPTZ(6) DEFAULT '3000-01-01 00:00:00 +00:00',
```

Apply that migration to your dev-test DB.

Make some unrelated change in the Prisma schema file, e.g. add another model.

Run another `prisma migrate dev`. Observe a line in the 2nd generated migration script:

```sql
ALTER TABLE "whatever" ALTER COLUMN "something_ts" SET DEFAULT '3000-01-01 00:00:00 +00:00';
```

### Expected behavior

If the default hasn't been changed in the Prisma schema, there should be no `ALTER TABLE ... ALTER COLUMN ... SET DEFAULT` generated for that column.

Note I have observed the same issue with defaults for fields with other data types, e.g.:

```prisma
whatever_id String @default("00000000-0000-0000-0000-000000000000") @db.Uuid
```

I could imagine an approach in which the `migrate dev` operation compares the field-level default value from system tables in the target DB before the operation and the shadow DB after the operations, and if the value hasn't changed, can safely conclude that operation is a no-op and exclude that from the generated SQL. This would alleviate Prisma from having to interpret formats and other conventions -- the final value of information_schema.columns.column_default should be definitive.

### Environment & setup

PostgreSQL 14.1

### Prisma Version

```
prisma                  : 3.11.0
@prisma/client          : 3.11.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : b371888aaf8f51357c7457d836b86d12da91658b
```

**Comment by Valerionn** [comment]
Still happens with Prisma 3.15:
```
prisma                  : 3.15.2
@prisma/client          : 3.15.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 461d6a05159055555eb7dfb337c9fb271cbd4d7e
Studio                  : 0.462.0
```

with
```
field DateTime? @default("2199-12-31T00:00:00Z") @db.Timestamptz(0)
```

I also tried to specify the default value with
```
field DateTime? @default(dbgenerated("'2199-12-31 00:00:00+00'::timestamp with time zone")) @db.Timestamptz(0)
```

but this still causes an endless migration as well. Removing the `@db.Timestamptz(0)` (as suggested in https://github.com/prisma/prisma/issues/10795#issuecomment-1068272249) doesn't seem to fix the problem either.

**Comment by pimeys** [comment]
This exact issue is solved in commit https://github.com/prisma/prisma-engines/commit/a4c3d146f5e5c5d7821ede63ca8552ad918b2d0d and in version 4.0.0.

In general, it's not really "solved" until we really solve datetime defaults. We'll be coming back to that later, including a proper support for timezones.

Please open a new issue if you face more redundant migrations with datetimes!
