### ISSUE TITLE
returning wrong message error

### ISSUE THREAD

**Issue by meotimdihia** [prisma/prisma#12923]
### Bug description

When I run query on large dataset, for ex:
```javascript
await prisma.user.findMany({
  where: {
     id: {
        gt: 0,
        lt: 10000000
     }
  }
}
```
Returning a wrong message error: `PrismaClientKnownRequestError: Can't reach database server at `localhost`:`5432``
It takes one hour for me to understand the problem.

### How to reproduce

```js
await prisma.user.findMany({
  where: {
     id: {
        gt: 0,
        lt: 10000000
     }
  }
}
```
data must be large enough that server can't return.

### Prisma information

it is easy to reproduce.

### Environment & setup

- OS: Ubuntu 20.04
- Database: PostgreSQL
- Node.js version: 14

### Prisma Version

```
    "prisma": "^3.12.0",
```

**Comment by janpio** [comment]
Can you share the full error message you are getting?

**Comment by meotimdihia** [comment]
Hi, this is full error messenge: 
```js
Error: 
Invalid `prisma.mytable.findMany()` invocation:


  Can't reach database server at `localhost`:`5432`

Please make sure your database server is running at `localhost`:`5432`.
    at Object.request (/path/to/project/node_modules/@prisma/client/runtime/index.js:45578:15)
    at middleware (/path/to/project/prisma/prisma.ts:243:12)
    at MdChaptersMiddleware (/path/to/project/prisma/prisma.ts:105:20)
    at PrismaClient._request (/path/to/project/node_modules/@prisma/client/runtime/index.js:46405:18)
    at main (/path/to/project/src/examples/myscript.ts:25:26) {code: 'P1001', clientVersion: '3.12.0', meta: {…}, stack: 'Error: 
Invalid `prisma.mytable.findMany(…es/myscript.ts:25:26)', message: '
Invalid `prisma.mytable.findMany()` inv…ase server is running at `localhost`:`5432`.'}
```

**Comment by janpio** [comment]
Does the workaround posted there help?
https://github.com/prisma/prisma/issues/8878#issuecomment-1059920622

That issue is missing a simple reproduction so we can fully confirm the issue. Do you have one or can help produce one?

**Comment by meotimdihia** [comment]
Sorry, I am too busy to fix this problem, it isn't really critical for my application.
It is just a misleading message.
