### ISSUE TITLE
next.js ENOENT trying to open schema.prisma

### ISSUE THREAD

**Issue by SimonBerens** [prisma/prisma#12921]
### Bug description

In a monorepo, when exporting `PrismaClient` from one package and consuming it in a next.js api route, I get 
```
error - Error: ENOENT: no such file or directory, open 'C:\Users\sbere\Desktop\Projects\prisma-pnpm-workspace-test\apps\frontend\.next\server\pages\api\schema.prisma'
```

### How to reproduce

1. Git clone https://github.com/SimonBerens/prisma-pnpm-workspace-test
2. run
```bash
pnpm install
cd packages/prisma
pnpx prisma generate
cd ../../apps/frontend
pnpm run dev
```
3. send a GET request to `localhost:3000/api/hello` 

### Expected behavior

The api runs as expected

### Prisma information

```  
prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables not found at undefined +0ms
  prisma:tryLoadEnv No Environment variables loaded +1ms
  prisma:tryLoadEnv Environment variables not found at null +1ms
  prisma:tryLoadEnv Environment variables not found at undefined +0ms
  prisma:tryLoadEnv No Environment variables loaded +0ms
  prisma:client dirname C:\Users\sbere\Desktop\Projects\prisma-pnpm-workspace-test\apps\frontend\.next\server\pages\api +0ms
  prisma:client relativePath ..\..\..\..\..\..\packages\prisma +0ms
  prisma:client cwd C:\Users\sbere\Desktop\Projects\prisma-pnpm-workspace-test\packages\prisma +0ms
  prisma:client clientVersion: 3.12.0 +2ms
  prisma:client clientEngineType: library +0ms
```

### Environment & setup

- OS: Windows 11
- Database: PostgreSQL
- Node.js version: v16.14.2

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at ..\..\node_modules\.pnpm\@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at ..\..\node_modules\.pnpm\@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at ..\..\node_modules\.pnpm\@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at ..\..\node_modules\.pnpm\@prisma+engines@3.12.0-37.22b822189f46ef0dc5c5b503368d1bee01213980\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by nvsd** [comment]
I'm actually experiencing the same but it's not limited to nextjs it's everywhere I use prisma.

Yarn workspaces
Custom output path
Prisma output is a private package

**Comment by orbiteleven** [comment]
I think https://github.com/prisma/prisma/issues/13052 would address this.

**Comment by orbiteleven** [comment]
This does seem to be a PNPM thing. I can get @SimonBerens's repo running using Yarn3 and `nodeLinker: node-modules`: https://github.com/orbiteleven/prisma-yarn-workspace-test.

**Comment by orbiteleven** [comment]
Since this seems to be related to PNPM+Next.js, I've cross-posted this [here](https://github.com/vercel/next.js/issues/36697)

**Comment by wladiston** [comment]
Neither is a Next.js thing. I'm experiencing the same issue with Remix 1.4.3

**Comment by remorses** [comment]
I fixed this adding to `.npmrc` the following, this forces the prisma package to remain on top of the monorepo i think

```
public-hoist-pattern[]=*prisma*
```

**Comment by baptisteArno** [comment]
> public-hoist-pattern[]=*prisma*

That solves the issue thank you 👍

**Comment by mabdullahadeel** [comment]
> I fixed this adding to `.npmrc` the following, this forces the prisma package to remain on top of the monorepo i think
> 
> ```
> public-hoist-pattern[]=*prisma*
> ```

This worked!
Thanks

**Comment by ExiledNarwal28** [comment]
Currently having the same issue with pnpm workspaces (turborepo) + Next.js. `public-hoist-pattern[]=*prisma*` did not help :(

**Comment by ExiledNarwal28** [comment]
Currently getting the same error with pnpm workspaces, turborepo and Next.js. `public-hoist-pattern[]=*prisma*` did not do the trick :/

**Comment by vedantnn71** [comment]
> Currently getting the same error with pnpm workspaces, turborepo and Next.js. `public-hoist-pattern[]=*prisma*` did not do the trick :/

Try adding this to your .npmrc, this did the trick for me:
```npmrc
node-linker=hoisted
```

**Comment by ian** [comment]
Can confirm, this is still an issue.

**Comment by ExiledNarwal28** [comment]
> > Currently getting the same error with pnpm workspaces, turborepo and Next.js. `public-hoist-pattern[]=*prisma*` did not do the trick :/
> 
> Try adding this to your .npmrc, this did the trick for me:
> 
> ```ini-npmrc
> node-linker=hoisted
> ```

Also tried, still not helping 😢

**Comment by joelhooks** [comment]
> I fixed this adding to `.npmrc` the following, this forces the prisma package to remain on top of the monorepo i think
> 
> ```
> public-hoist-pattern[]=*prisma*
> ```

This worked for us since July and inexplicably stopped working for us this week.

**Comment by nickluger** [comment]
> This worked for us since July and inexplicably stopped working for us this week.

Ah... just fixed it that way, hope it will keep working for us. 😅

If you're using Next.js or some other framework bundling via Webpack you can try adding `@prisma/client` to `config.externals`. I tried that once and it worked, because it keeps Prisma out of the bundle (it's used server-side only anyways). Prisma is probably just `required` via Node resolution out of `node_modules`, so the schema file stays next to it.

**Comment by trentonsnyder** [comment]
prisma 4.2.0
@prisma/client 4.2.0
yarn@1.22.19
M1 mac

I think I'm running into the same thing. I have 2 "packages" in turborepo that use prisma (mongodb, postgres).
I've tried using a custom "output" path for both packages so that the schemas wouldn't overwrite each other in the shared @prisma monorepo `node_modules`. It seemed to work ok until I saw this error.
I have pivoted and now I'm trying to use the default behavior of importing from `@prisma/client` but not hoisting prisma deps to the monorepo `node_modules` a la
```
    "nohoist": [
      "**/prisma/**",
      "**/@prisma/client/**",
      "**/@prisma/**",
      "**/@prisma/engines/**"
    ]
```
but still seeing this same error
```
ditto:dev: error - Error: ENOENT: no such file or directory, open '/Users/trenton/Desktop/dev/polaris/apps/ditto/.next/server/pages/schema.prisma'
ditto:dev:     at Object.openSync (fs.js:498:3)
ditto:dev:     at Object.readFileSync (fs.js:394:35)
ditto:dev:     at new LibraryEngine (webpack-internal:///../../packages/blueprint/node_modules/@prisma/client/runtime/index.js:25308:41)
ditto:dev:     at PrismaClient.getEngine (webpack-internal:///../../packages/blueprint/node_modules/@prisma/client/runtime/index.js:29321:16)
ditto:dev:     at new PrismaClient (webpack-internal:///../../packages/blueprint/node_modules/@prisma/client/runtime/index.js:29293:29)
```

Is it a problem with `LibraryEngine.datamodel`? Just looking at the sourcecode it seems like `dirname` on this line might be going to the wrong place.
```
datamodelPath: path.join(config.dirname, config.filename ?? 'schema.prisma')
```

**Comment by jbranchaud** [comment]
Our stack is pretty specific, but here is what worked for us on pnpm v7 / turborepo v1.4.7 / vercel / prisma 4.4.0

Several of our builds were failing with this Prisma-related error: `error - Error: ENOENT: no such file or directory, open '/Users/jbranchaud/code/clients/egghead/products/apps/epic-web/.next/server/pages/api/skill/schema.prisma'`

This was originally fixed for us in July using `public-hoist-pattern[]=*prisma*` in `.npmrc` as @joelhooks pointed out:

> This worked for us since July and inexplicably stopped working for us this week.

Because it suddenly stopped working, I started look for what could have changed _most recently_. pnpm v7.13.5 was released just a couple days ago. That seemed worth exploring, especially since our codebase isn't controlling the pnpm version. The theory being that our builds would pass on an earlier version of pnpm, e.g. v7.13.2.

What we learned is that, as of right now, the only way [to control the specific version of pnpm that Vercel uses is to enable an experimental corepack feature](https://vercel.com/docs/concepts/deployments/configure-a-build#corepack).

With `ENABLE_EXPERIMENTAL_COREPACK` set to `1` as a Vercel environment variable, we noticed that our builds started respecting the `packageManager` config in the monorepo's root `package.json`.

So we set it to:

```json
{
  ...,
  "packageManager": "pnpm@7.13.2",
}
```

With those two things in place, we started seeing Vercel pin pnpm to that specific version and the above error went away again.

![image](https://user-images.githubusercontent.com/694063/196776441-c12eb097-ba86-4b88-9dc4-611972dfa2c4.png)


PR with more details: https://github.com/skillrecordings/products/pull/535

**Comment by Kubessandra** [comment]
Someone was able to make it work ?
Same issue with:

pnpm: 7.14.0
NextJS
Prisma 4.5.0

**Comment by Pong420** [comment]
> > This worked for us since July and inexplicably stopped working for us this week.
> 
> Ah... just fixed it that way, hope it will keep working for us. 😅
> 
> If you're using Next.js or some other framework bundling via Webpack you can try adding `@prisma/client` to `config.externals`. I tried that once and it worked, because it keeps Prisma out of the bundle (it's used server-side only anyways). Prisma is probably just `required` via Node resolution out of `node_modules`, so the schema file stays next to it.

This works for me.

1. output into project root node_modules
```
generator client {
  provider = "prisma-client-js"
  output   = "../../../node_modules/.prisma/client"
}
```

2. Add `@prisma/client` to externals in `next.config.js`
```
 defineNextConfig({
    webpack: config => {
      config.externals = [...(config.externals || []), '@prisma/client'];
      // Important: return the modified config
      return config;
    }
  })
```

**Comment by ExiledNarwal28** [comment]
@Pong420 this worked for me. Thank you so, so much!

**Comment by lottamus** [comment]
If you're using nextjs, try adding prisma to the `serverComponentsExternalPackages` in your config:

```js
// next.config.js
const nextConfig = {
  experimental: {
    appDir: true,
    serverComponentsExternalPackages: ['@prisma/client'],
  },
};
```

https://beta.nextjs.org/docs/api-reference/next.config.js#servercomponentsexternalpackages

<img width="781" alt="image" src="https://user-images.githubusercontent.com/7423098/200148019-afdf552a-73ee-4aa8-a9de-0cd2e90aa1c7.png">

**Comment by Hooman-studio** [comment]
Still having this issue with 
yarn version 1.22, 
prisma 4.8.1

setting the webpack config.externals works on dev, but on builds nextjs is complaining 

```
Unexpected character '@' (1:35)
--
 \| var __WEBPACK_NAMESPACE_OBJECT__ = @prisma/client;
while analyzing module external assign "@prisma/client" for concatenation
```

this all started for me after upgrading prisma from version 3 to 4, any help appreciated!

**Comment by janpio** [comment]
Thanks for the excellent reproduction @SimonBerens - it was super easy to reproduce the problem with it. We are testing a workaround, so we will hopefully have good news soon 🔜 .

---

Meanwhile:

@nvsd Can you maybe share a reproduction of a project not using Next.js where this is happening? Maybe even as a new issue as this is different enough for us to look at it separately. Thanks.

@wladiston Can you maybe share a reproduction of this problem with Remix? Maybe even as a new issue as this is different enough for us to look at it separately. Thanks.

Thanks everyone else who provided all their information about their projects. If you want, any additional reproduction can help us refine and test our potential solutions. Thanks.

@orbiteleven @remorses @baptisteArno @joelhooks Can you please describe your projects a bit? Monorepo? Next.js? Custom `output` or not? Package Manager? Thanks.

**Comment by millsp** [comment]
I have a workaround working for @SimonBerens's repro
https://github.com/SimonBerens/prisma-pnpm-workspace-test/pull/1

**Comment by baptisteArno** [comment]
> @orbiteleven @remorses @baptisteArno @joelhooks Can you please describe your projects a bit? Monorepo? Next.js? Custom `output` or not? Package Manager? Thanks.

https://github.com/baptisteArno/typebot.io. It's a monorepo powered by Turborepo. It uses pnpm and it's a Next.js app.

**Comment by remorses** [comment]
The best solution would be to embed the schema.prisma data in the generated code instead of reading the file from file system

**Comment by millsp** [comment]
@baptisteArno Would you be able to give us a reproduction? (Btw, amazing work on Typebot!)

**Comment by janpio** [comment]
@remorses Then the schema would load successfully, and it would fail for the Query Engine which is needed to run queries and can not be in the generated code. Unfortunately not a solution.

**Comment by baptisteArno** [comment]
> @baptisteArno Would you be able to give us a reproduction? (Btw, amazing work on Typebot!)

Thank you 🙏

Here is the most minimal reproduction I could get: https://github.com/baptisteArno/prisma-turbo-pnpm

**Comment by doums** [comment]
@Weakky you have to fix that buddy.

**Comment by janpio** [comment]
@baptisteArno Thanksfully the same workaround as for @SimonBerens also works for your minimal reproduction: https://github.com/baptisteArno/prisma-turbo-pnpm/pull/1/files Thanks for creating that, so we could confirm our workaround and will have another project later to confirm the proper fix!

**Comment by baptisteArno** [comment]
I made the change on Typebot, works perfectly 👌

**Comment by baptisteArno** [comment]
Whoops guys, my bad, it worked because I had a build cache. It didn't work when I triggered a rebuild of my app in production.

It crashed with the following error: `Cannot find module '@prisma/client'`

**Comment by janpio** [comment]
Can you shared the branch of that? Happy to look into it to see how to adapt our workarounds and understanding what is going on.

**Comment by baptisteArno** [comment]
So this fix won't work if deploying the application to Vercel because they will ignore

```
output: "standalone",
experimental: {
    outputFileTracingRoot: path.join(__dirname, "../../"),
  },
```

Because Vercel is deploying serverless functions.

I reproduced this on: https://github.com/baptisteArno/prisma-turbo-pnpm
The deployment is here: https://prisma-turbo-pnpm-web.vercel.app (check the console to see the api response failing)

There is maybe a way to detect in the webpack function whether we're building for serverless or standalone? 🤔

**Comment by millsp** [comment]
Hey guys, thanks for the feedback. We have been working on a simpler way to make things work for you, as the workaround we proposed had clear limitations for TS projects. We worked on an experimental webpack plugin that ensures your Prisma files are copied correctly. I'd love if you could give it a try (https://www.npmjs.com/package/experimental-prisma-webpack-plugin). We have tested it in many different scenarios, so we hope this works for you.

```ts
const { PrismaPlugin } = require('experimental-prisma-webpack-plugin')

module.exports = {
  output: 'standalone',
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.plugins = [...config.plugins, new PrismaPlugin()]
    }

    return config
  },
}
```

**Comment by baptisteArno** [comment]
@millsp It works for a ton of scenarios I tried. Thank you for this plugin 👏

However, it crashes in **dev mode** when you import multiple prisma clients. Only when it has compiled at least 1 folder deep in the `api` folder:

```
web:dev: error: Error validating: This line is invalid. It does not start with any known Prisma schema keyword.
web:dev:   -->  schema.prisma:15
web:dev:    | 
web:dev: 14 | }
web:dev: 15 |  String
web:dev: 16 | }
web:dev:    | 
web:dev: error: Error validating: This line is invalid. It does not start with any known Prisma schema keyword.
web:dev:   -->  schema.prisma:16
web:dev:    | 
web:dev: 15 |  String
web:dev: 16 | }
web:dev: 17 | 
web:dev:    | 
web:dev: 
web:dev: Validation Error Count: 2
web:dev:     at RequestHandler.handleRequestError (webpack-internal:///(api)/../../packages/db/prisma-clients/postgresql/runtime/index.js:32859:19)
web:dev:     at RequestHandler.handleAndLogRequestError (webpack-internal:///(api)/../../packages/db/prisma-clients/postgresql/runtime/index.js:32808:18)
web:dev:     at eval (webpack-internal:///(api)/../../packages/db/prisma-clients/postgresql/runtime/index.js:33351:35)
web:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web:dev:     at async PrismaClient._executeRequest (webpack-internal:///(api)/../../packages/db/prisma-clients/postgresql/runtime/index.js:33931:30)
web:dev:     at async PrismaClient._request (webpack-internal:///(api)/../../packages/db/prisma-clients/postgresql/runtime/index.js:33917:24)
web:dev:     at async handler (webpack-internal:///(api)/./pages/api/posts.ts:8:5)
web:dev:     at async Object.apiResolver (/Users/baptistearno/Dev/prisma-turbo-pnpm/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/api-utils/node.js:372:9)
web:dev:     at async DevServer.runApi (/Users/baptistearno/Dev/prisma-turbo-pnpm/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/next-server.js:488:9)
web:dev:     at async Object.fn (/Users/baptistearno/Dev/prisma-turbo-pnpm/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/next-server.js:751:37)
web:dev:     at async Router.execute (/Users/baptistearno/Dev/prisma-turbo-pnpm/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/router.js:253:36)
web:dev:     at async DevServer.run (/Users/baptistearno/Dev/prisma-turbo-pnpm/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/base-server.js:384:29)
web:dev:     at async DevServer.run (/Users/baptistearno/Dev/prisma-turbo-pnpm/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/dev/next-dev-server.js:743:20)
web:dev:     at async DevServer.handleRequest (/Users/baptistearno/Dev/prisma-turbo-pnpm/node_modules/.pnpm/next@13.1.6_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/server/base-server.js:322:20) {
web:dev:   clientVersion: '4.9.0',
web:dev:   errorCode: undefined,
web:dev:   page: '/api/another/hi'
web:dev: }
```

I managed to reproduce a minimalist issue here: https://github.com/baptisteArno/prisma-turbo-pnpm/pull/2

Can you think of a solution for this?

**Comment by johnschult** [comment]
> I'd love if you could give it a try (https://www.npmjs.com/package/experimental-prisma-webpack-plugin). We have tested it in many different scenarios, so we hope this works for you.

Yes! Thanks for this, it solved our problem, we are using `yarn`, and `turbo`, with a database package for Prisma. 🍻

**Comment by trentonsnyder** [comment]
I was testing out the plugin for my use case and ran into an issue. I tried to make an accurate reproduction of it [here](https://github.com/trentonsnyder/nextjs-prisma-repro)

It's a NextJS app. I think the issue is when I use prisma db functions in both an `/api` file and in a `getStaticProps` (maybe getServerSideProps too). I also tried to add a little more context in the Readme.

**Comment by millsp** [comment]
Thanks @trentonsnyder. I haven't looked in detail yet, so quick question for you: Have you tried removing `if (isServer) {` so that it is triggered at static build time too? I'm not sure if that is your problem 100% but maybe worth trying.

**Comment by trentonsnyder** [comment]
@millsp good suggestion. Seems to behave the same way though even with `isServer` removed.

**Comment by millsp** [comment]
Thanks, I'll take a look in the coming days

**Comment by millsp** [comment]
For those using multiple Prisma Clients, we are going to schedule follow-up work via https://github.com/prisma/prisma/issues/18069. Please upvote it if you need multi-client support, and don't hesitate to share more information there.

**Comment by rjay98** [comment]
It's unfortunately super flaky and happens even with the patch – I suspect when another package is importing our database `package` and both are being transpiled into Next.

- Prisma `4.14.0`
- `pnpm`
- `Next `13.4.2`
- Turborepo

**Comment by maxtechera** [comment]
@janpio - I'm having a very similar usecase but I cannot provide a reproduction right now. But I would like to share in case it sparks some ideas. 
I'm using Next 13 with the app dir, the monorepo workaround works for almost every usecase but it seems it hits some race conditions at times. 
When going to a route the "compiling" messages shows and as soon as it's ready the page loads and throws the error. I can see that during compilation the `.next/server/app/<example>` get's created and before the prisma files get copied the app tries to load and fails. 
Most times a refresh solves the issue and I can see the prisma files being copied into the newly created `.next` folder, where some other times it wont.

This happens a lot more consistently when doing client side navigation to a route which is not compiled yet, and needs to be compiled on the fly. 

I hope this information is useful, if there is a better format/place to add this I can attempt to do so.

**Comment by janpio** [comment]
Thanks @maxtechera, you can just open a new issue even with this limited information. The bug issues template asks for a few interesting bits that could help us understand this - and if you ever figure out _more_ you will have a place to add that information. Thanks!

**Comment by maxtechera** [comment]
> Thanks @maxtechera, you can just open a new issue even with this limited information. The bug issues template asks for a few interesting bits that could help us understand this - and if you ever figure out _more_ you will have a place to add that information. Thanks!

Here's the issue: https://github.com/prisma/prisma/issues/19784
