### ISSUE TITLE
Nested delete doesn't work with `onDelete: Restrict`

### ISSUE THREAD

**Issue by ArnaudBarre** [prisma/prisma#12927]
### Bug description

When using `{ delete: true }` with an optional relation configured with `onDelete: Restrict`, the query fails with `Foreign key constraint failed on the field` even if the current updated record is the only reference to the deleted entity

### How to reproduce

Use `{ delete: true }` during an update on an optional relation with `onDelete: Restrict`

(no action also doesn't work)

### Expected behavior

The column is set to null and the relation is deleted.

Looking at queries, I think the first update in the transaction should explicitly set the column to null instead of relaying on a default `SET NULL` behaviour.

### Prisma information

```
  hint       Label?            @relation("hint", fields: [hintUuid], references: [uuid], onDelete: Restrict)
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v17.8.0

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by dpetrick** [comment]
> Use { delete: true } during an update on an optional relation with onDelete: Restrict (no action also doesn't work)

This is expected behavior. You're telling the database that any delete of referenced side is supposed to fail, the optionality that Prisma introduces here on the relation doesn't matter, because the behavior of Postgres supersedes that here. An optional relation basically gives you that `onUpdate: Cascade` (or `SetNull`) and `onDelete: SetNull` work as referential actions, but you actually have to use them in order to get the desired effect.

Side note: `Restrict` and `NoAction` on SQL connectors have almost always the same behavior with nuances in the underlying semantics for the database implementations, bar some exceptions.

**Comment by ArnaudBarre** [comment]
My goal is to prevent `delete -> set null`, but I still want to do `set null then delete` in one "prisma call".

I currently use `{ disconnect: true }` and then use another prisma call to delete the previously referenced row.

If the update statement set the relation column to null (like with disconnect), then the delete statement sent just after will work.

**Comment by dpetrick** [comment]
And that's the correct way of solving it, you will need to do two separate calls, the current queries are not designed to solve this magically because it would be unexpected (and frankly, incorrect) for the majority of users.
