### ISSUE TITLE
  The table `(not available)` does not exist in the current database.

### ISSUE THREAD

**Issue by fwogo** [prisma/prisma#12938]
### Bug description

So im trying to run a code on my discord bot

```js
const { Client, Collection } = require('discord.js')
const client = new Client({ intents: 32767 })
module.exports = client;


client.config = require('../config.json')
client.slashCommands = new Collection();

//prisma
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
async function main() {
    const allUsers = await prisma.user.findMany()
    console.log(allUsers)
  }
  
  main()
    .catch((e) => {
      throw e
    })
    .finally(async () => {
      await prisma.$disconnect()
    })
require('./handler')(client);
client.login(client.config.token)
```

However, it gives me this error
```
        throw new PrismaClientKnownRequestError(message, e.code, this.client._clientVersion, e.meta);
              ^

PrismaClientKnownRequestError: 
Invalid `prisma.user.findMany()` invocation in
C:\Users\AriesAsAkshay\OneDrive\Documents\GitHub\PrismaFrog\src\index.js:13:40

  10 const { PrismaClient } = require('@prisma/client');
  11 const prisma = new PrismaClient();
  12 async function main() {
→ 13     const allUsers = await prisma.user.findMany(
  The table `(not available)` does not exist in the current database.
    at Object.request (C:\Users\AriesAsAkshay\OneDrive\Documents\GitHub\PrismaFrog\node_modules\@prisma\client\runtime\index.js:45578:15)
    at async PrismaClient._request (C:\Users\AriesAsAkshay\OneDrive\Documents\GitHub\PrismaFrog\node_modules\@prisma\client\runtime\index.js:46405:18)
    at async main (C:\Users\AriesAsAkshay\OneDrive\Documents\GitHub\PrismaFrog\src\index.js:13:22) {
  code: 'P2021',
  clientVersion: '3.12.0',
  meta: { table: '(not available)' }
}
```

So when i try to create the row manually Prisma gives me this
![image](https://user-images.githubusercontent.com/93356938/164895945-e77ac82d-748a-4e71-9f51-e08b00415113.png)

### How to reproduce

Create a empty project
create index.js
paste the code into it

and login with discord bot token. -> found here [https://discord.com/developers/applications](https://discord.com/developers/applications)

### Expected behavior

should return []

### Prisma information

model user {
  id String @unique
  Image String
  Blacklisted Boolean
  Developer Boolean
}

### Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: v16.6.0

### Prisma Version

prisma                  : 3.12.0
@prisma/client          : 3.12.0

**Comment by janpio** [comment]
The error message indicates that the table, probably `user`, does not exist in your database.
Did you migrate the database in any way?

**Comment by fwogo** [comment]
No, i haven't migrated the database at all, when i try to add a table manually. It gives me the error i showed.

**Comment by janpio** [comment]
After writing that schema, you need to migrate your database using `npx prisma migrate` or `npx prisma db push` so that the database tables are actually created. Otherwise you indeed will get this error message as the model in your schema does not exist as a table on your database server.

**Comment by fwogo** [comment]
Ohh, tysm that actually works
