### ISSUE TITLE
Best practices for DB connection in AWS Lambda

### ISSUE THREAD

**Issue by mruzekw** [prisma/prisma#1297]
What is the best way right now to connect to a DB in a serverless environment like AWS Lambda? 

Do we have the ability to create our own connectors yet?

Could we use [serverless-mysql](https://www.npmjs.com/package/serverless-mysql) somehow?

Common use cases I see are:

- DyanmoDB
- MySQL RDS (possibly with proxy)
- Postgres RDS (again, proxy)
- Aurora Serverless
- Aurora Serverless Data API

I'm mainly interested in MySQL and Postgres at this point.

Ideally there would be a way to efficiently connect without an additional service like PgBouncer.

Would appreciate your guidance. Thanks.

**Comment by divyenduz** [comment]
Hi @mruzekw 

Thanks for raising this issue, we have it documented here: https://github.com/prisma/prisma2/blob/master/docs/photon/deployment.md#photon-in-faas-environment-eg-aws-lambda-netlify-

Does that make sense? It generally lists out the pros and cons of different approaches.

**Comment by mruzekw** [comment]
Thanks for the reply, @divyenduz. 

Unfortunately that doc doesn't give me the full picture of what's needed.

> Container reuse

This point it clear.

> Zombie connections
>
> One potential solution is to use a lower idle connection timeout. Another solution can be to clean up the idle connections in a separate service. [1][2]
>
> 2. serverless-mysql is a library that implements this idea. 

Although serverless-mysql is mentioned, there's no indication on how to include it or the technique it uses with Photon. Is there someway to replace `mysql` with `serverless-mysql`, or are we expected to implement something like `serverless-mysql` ourselves? Even if we did include `serverless-mysql`, how would we use it with Photon given there's no way to make a custom connector at this point (at least there's no docs)?

Could we use `photon.disconnect()` to avoid zombie connections?

> Connection pooling issues
>
> Photon does not implement connection pooling right now. This can also be handled by limiting the concurrency levels of a Lambda function.

This answer is good enough for now. Though it would be nice to have a more auto-scalable solution. The works with both MySQL and Postgres in a serverless context.

**Comment by tre-dev** [comment]
There is a data API available for Aurora Serverless (MySQL & Postgres), which basically means making HTTP requests with queries if I'm correct. So that could be implemented with/into Photon, right?

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html

**Comment by seawatts** [comment]
> Hi @mruzekw
> 
> Thanks for raising this issue, we have it documented here: https://github.com/prisma/prisma2/blob/master/docs/photon/deployment.md#photon-in-faas-environment-eg-aws-lambda-netlify-
> 
> Does that make sense? It generally lists out the pros and cons of different approaches.

This link no longer works.

**Comment by nikolasburk** [comment]
@seawatts Good catch! You the `photon` directory was renamed to `prisma-client-js`, so the docs are now here: https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/deployment.md#photon-in-faas-environment-eg-aws-lambda-netlify-

**Comment by janpio** [comment]
> Ideally there would be a way to efficiently connect without an additional service like PgBouncer.

pgBouncer support is now part of Prisma and can be used. Until this is added to the official documentation, you can read about it on prisma/prisma-client-js#503 🚀

**Comment by brandonin** [comment]
> @seawatts Good catch! You the `photon` directory was renamed to `prisma-client-js`, so the docs are now here: https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/deployment.md#photon-in-faas-environment-eg-aws-lambda-netlify-

This link no longer works either :(

**Comment by divyenduz** [comment]
@brandonin Sorry about that, here is the correct link https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/deployment#serverless-faas

**Comment by musmanalibaloch** [comment]
https://muhammadusmanalibaloch.medium.com/aws-lambda-reuse-database-connection-and-save-around-200ms-response-time-2c50a445f464

**Comment by Jolg42** [comment]
For Serverless / PotsgreSQL definitely can recommend looking into these 2 blocks
https://www.prisma.io/docs/concepts/components/prisma-client/deployment#serverless-faas
https://www.prisma.io/docs/concepts/components/prisma-client/deployment#usage-with-pgbouncer

For a PgBouncer as a service check Heroku or DO
https://blog.heroku.com/connection-pooling
https://www.digitalocean.com/community/tutorials/managed-databases-connection-pools-and-postgresql-benchmarking-using-pgbench

**Comment by matthewmueller** [comment]
We just wrote some new documentation on how to use Prisma in serverless environments: https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#serverless-environments-faas

I'm going to close this issue because it's a bit broad, if you have more specific problems with your serverless deployments, please open new issues!

**Comment by pantharshit00** [comment]
I think this is covered well by docs as @matthewmueller mentioned so I am going to close this.
