### ISSUE TITLE
Deploying to Cloudflare Workers | "PrismaClient is unable to be run in the browser"

### ISSUE THREAD

**Issue by red-game-dev** [prisma/prisma#12981]
### Bug description

Hi hope you're all well,

I'm using cloudflare workers, and running to a strange issue, as it is implemented as the docs mentions below 
[Prisma deploying to Clouflare workers](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers)

The error mentioned is "Error: PrismaClient is unable to be run in the browser. In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues"

- We're using dataproxy client using the command "PRISMA_CLIENT_ENGINE_TYPE=dataproxy npx prisma generate"
- Rollup config which adds the part of alias "'@prisma/client$': require.resolve('@prisma/client'),"
- Prisma schema & Prisma Data Platform
- Env key for both shadow db & db url is there
- Locked ts loader at 8.3.0 as suggested

Any recommendations what else can it be the issue?

Didn't include this as within the existing issue of [Sveltekit + Cloudflare adapter - "PrismaClient is unable to be run in the browser."](https://github.com/prisma/prisma/issues/11712), since it is different setup, therefore is good to have dedicated issue for that. 

### Expected behavior

Should be working not in browser mode, since Cloudflare workers are not browser based.

### Prisma information

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema
// client & db https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#datasource

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialIntegrity", "dataProxy"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime
  title     String   @db.VarChar(255)
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int

  @@index([authorId])
}

model Profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique

  @@index([userId])
}

model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
}
```

### Environment & setup

- OS: Windows
- Database: MySQL,
- Node.js version: 16.13.0

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee012139
                                                                               980 (at ..\..\..\..\AppData\Roaming\nvm\v16.13.0\node_modules\prisma\node_modules
                                                                               s\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee0
                                                                               01213980 (at ..\..\..\..\AppData\Roaming\nvm\v16.13.0\node_modules\prisma\node_mo
                                                                               odules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee012
                                                                               213980 (at ..\..\..\..\AppData\Roaming\nvm\v16.13.0\node_modules\prisma\node_modu
                                                                               ules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (a
                                                                               at ..\..\..\..\AppData\Roaming\nvm\v16.13.0\node_modules\prisma\node_modules\@pri
                                                                               isma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by red-game-dev** [comment]
We've came up with a solution which potentially could help Prisma Team to sort it out, which it can be helpful as well for whoever is facing the issue at the moment.

**The sort this issue, just run the following command**
```
PRISMA_CLIENT_ENGINE_TYPE=dataproxy prisma generate && mv -f ./node_modules/.prisma/client/index.js ./node_modules/.prisma/client/index-browser.js && wrangler dev src/index.ts --env staging --local
```

Please mind that the command contains `src/index.ts` which should point to your entry point.

Should anyone have any questions, please feel free to tag us to any of your issues / reply to this if still open issue.

**Comment by cyriaque-ovaga** [comment]
Please where i put your code .

**Comment by millsp** [comment]
Since this workaround is not needed anymore, you need to import `@prisma/client/edge` for it to work on Cloudflare workers. The documentation has also been updated.
