### ISSUE TITLE
Migration failed to apply cleanly to the shadow database

### ISSUE THREAD

**Issue by jeremygottfried** [prisma/prisma#13018]
### Bug description

After manually correcting a broken migration and committing it to the DB, I'm now getting the following error when I try to create a new migration with `prisma migrate dev --create-only`

```
Error: P3006

Migration `20220425205658_add_reference_to_model` failed to apply cleanly to the shadow database.
Error:
insert or update on table "reference" violates foreign key constraint "reference_model_id_fkey"
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:354
   1: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:108
```

But when I run `prisma migrate status` it returns `Database schema is up to date!`, so it shouldn't be returning this error.

### Expected behavior

If a migration is successfully added to the DB, it shouldn't still be returning errors. 

### Prisma information

```

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["nativeTypes", "interactiveTransactions"]
  binaryTargets   = ["native", "rhel-openssl-1.0.x"]
}
```

### Environment & setup

- OS: MacOS 10.15.7
- Database: PostgreSQL
- Node.js version: v14.18.1

### Prisma Version

```
3.4.2
```

**Comment by jeremygottfried** [comment]
Looks like I'll be using `migrate diff` command from now on to manually create new migrations, since that still works. Is there any way to fix the shadow DB without resetting the actual DB?

**Comment by tomhoule** [comment]
The shadow database is brought to a clean, empty state everytime you use `migrate dev`. What the error is saying is that if you take an empty database, then apply all your migrations in order, it fails at "20220425205658_add_reference_to_model". It looks like data migration that may not be working on an empty database — one solution would be to fix that.

**Comment by jeremygottfried** [comment]
@tomhoule But it doesn't fail. Maybe the issue is the shadow DB can't handle INSERT commands? 

The original issue was that the migration was creating a required reference column but the reference table was also created in the same migration. So it failed because the default value didn't exist yet. 

So I fixed it by inserting one entry into the reference table with the default value and then adding the `reference_id` column.

```
INSERT INTO "reference_model" (
  token,name
) 
VALUES ('xxx.xxx.xxx.xxx','test');
```

The problem is that this works for fixing the migration, but causes all subsequent `migrate dev` commands to fail, so now my DB is stuck with this, though I can still create and deploy new migrations manually.

**Comment by janpio** [comment]
From the error message:
> insert or update on table "reference" violates foreign key constraint "reference_model_id_fkey"
And your query:

> ```
> INSERT INTO "reference_model" (
>   token,name
> ) 
> VALUES ('xxx.xxx.xxx.xxx','test');
> ```

Are those both correct? 
Note the difference `reference` and `reference_model`.

**Comment by jeremygottfried** [comment]
`reference_model` isn't the actual name of my model. It's just the name I'm using for examples. The names match in my actual migration

**Comment by janpio** [comment]
Per the error message, part of the `INSERT` seems to be for a foreign key on the `id` field of that table, and that is somehow causing an error to be thrown. Does that makes sense in any way? Can you maybe share the SQL of the actual table?

**Comment by jeremygottfried** [comment]
Yes `token` is the `@@id` for that model. Here's what it looks like in schema.

```prisma
model Product {
  id                    String        @unique
  createdAt             DateTime      @default(now()) @map(name: "created_at")
  updatedAt             DateTime      @updatedAt @map(name: "updated_at")
  collection            Collection @relation("ProductCollections", fields: [collectionId], references: [token])
  collectionId          String        @default("xxx.xxx.xxx.xxx") @map(name: "collection_id")
  name                  String
  description           String?

  @@id([id])
  @@map(name: "models")
}

model Collection {
  token     String
  name      String
  products   Product[]                @relation("ProductCollections")

  @@id([token])
  @@map(name: "collections")
}
```

Here's what it looks like in the migration
```sql
-- CreateTable
CREATE TABLE "collections" (
    "token" TEXT NOT NULL,
    "name" TEXT NOT NULL,

    CONSTRAINT "collections_pkey" PRIMARY KEY ("token")
);

-- CreateDefault
INSERT INTO "collections" (
  token,name
) 
VALUES ('xxx.xxx.xxx','test');

-- AlterTable
ALTER TABLE "products" ADD COLUMN     "collection_id" TEXT NOT NULL DEFAULT E'xxx.xxx.xxx'',

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "collections"("token") ON DELETE RESTRICT ON UPDATE CASCADE;
```

**Comment by janpio** [comment]
Hm, I can not reproduce this @jeremygottfried: https://github.com/janpio/13018/tree/master/prisma/migrations Created a new project, added the previous schema (without your new additions), modified the migration as you did, applied it, then added another field and migrated again - no problems for me.

Amy I missing something?

**Comment by jeremygottfried** [comment]
Ok here's my entire migration. I was trying to simplify it because I don't think the other parts are causing the issue, but maybe they are! Just to be clear the `token_id` on products and `token` on product_collections are unrelated.
```sql
/*
  Warnings:

  - A unique constraint covering the columns `[id]` on the table `products` will be added. If there are existing duplicate values, this will fail.
  - A unique constraint covering the columns `[token_id]` on the table `products` will be added. If there are existing duplicate values, this will fail.
  - Made the column `token_id` on table `products` required. This step will fail if there are existing NULL values in that column.

*/
-- CreateTable
CREATE TABLE "product_collections" (
    "token" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "creator_id" TEXT NOT NULL,

    CONSTRAINT "product_collections_pkey" PRIMARY KEY ("token")
);

-- CreateDefault
INSERT INTO "product_collections" (
  token,name,creator_id
) 
VALUES ('xxx.xxx.xxx','test','zzz.zzz.zzz');

-- AlterTable
ALTER TABLE "products" ADD COLUMN     "collection_id" TEXT NOT NULL DEFAULT E'xxx.xxx.xxx',
ALTER COLUMN "token_id" SET NOT NULL;



-- CreateTable
CREATE TABLE "product_collection_images" (
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "product_collection_id" TEXT NOT NULL,
    "image_id" TEXT NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "product_collection_images_pkey" PRIMARY KEY ("product_collection_id","image_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "product_collection_images_product_collection_id_image_id_key" ON "product_collection_images"("product_collection_id", "image_id");

-- CreateIndex
CREATE UNIQUE INDEX "products_id_key" ON "products"("id");

-- CreateIndex
CREATE UNIQUE INDEX "products_token_id_key" ON "products"("token_id");

-- AddForeignKey
ALTER TABLE "product_collections" ADD CONSTRAINT "product_collections_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "brands"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "product_collections"("token") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_collection_images" ADD CONSTRAINT "product_collection_images_product_collection_id_fkey" FOREIGN KEY ("product_collection_id") REFERENCES "product_collections"("token") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_collection_images" ADD CONSTRAINT "product_collection_images_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "images"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
```

**Comment by janpio** [comment]
Can you maybe also share the models for `product_collections`, `products` and `product_collection_images`? With that and the migration, it will be simple enough to assume the "before" state of the schema and try to reproduce again to see what is going on. (If not, we can of course also recreate from assumptions etc - but as this is just a slightly different version of the structure you already posted...)

**Comment by jeremygottfried** [comment]
It looks like the error is actually from adding `creator_id` in the `INSERT` statement, cause the error is showing 
```sh
insert or update on table "product_collections" violates foreign key constraint "product_collections_creator_id_fkey"
```
I was confused because the original error was caused by the other foreign key.

The following fixes the error, but unfortunately now I can't fix it because it says "the migration xxx.xxx.xxx was modified after it was applied. We need to reset the PostgreSQL database"
```sql
INSERT INTO "brands" (
  id,created_at,updated_at,name
)
VALUES ('zzz.zzz.zzz', NOW(), NOW(), 'test')
ON CONFLICT (id) DO NOTHING;
```

Is there a way to "trick" it into thinking I haven't changed the migration?

**Comment by janpio** [comment]
Ok, so you added another `INSERT` to your migration file to make the previously failing query not fail any more? And the error was caused by _another_ foreign key that got lost whe nyou simplified the error message and code for the issue here, right?

**Comment by janpio** [comment]
If you really can not reset the database, then you could probably manually delete the last entry in `_prisma_migrations` (which records the exeution with a file hash) and then use https://www.prisma.io/docs/guides/database/production-troubleshooting#option-2-manually-complete-migration-and-resolve-as-applied - this will update the file hash to the now current one and still record the migration as applied.

**Comment by jeremygottfried** [comment]
Ok I will try that.
I'm using migrate dev in a hosted staging environment with a bunch of test data that I don't want to lose. I could probably save a copy of my DB and then import it later, but I'd rather have an easier way to correct the issue (and any issues I face in the future).

**Comment by jeremygottfried** [comment]
Looks like that worked thanks!

**Comment by frckbrice** [comment]
@janpio Thanks. You save me from 5 hours searching how to solve this problem (2 years later).   
@jeremygottfried thanks for suggesting the issue.
