### ISSUE TITLE
BigQuery Connector

### ISSUE THREAD

**Issue by lloydrichards** [prisma/prisma#13010]
## Problem

I have a IoT data pipeline using BigQuery and CloudSQL for various parts of the architecture.  At the moment I'm building an internal dashboard for tracking errors and customer issues and would like to combine the data from BigQuery with CloudSQL.  Right now this is not possible with Prisma as a middleware to by DB and results in me needing to schedule data transfers to CloudSQL every now and then.  If I could get all my data from BigQuery (with the CloudSQL connected to it) then it would make my life that much easier.

## Suggested solution

Add a connector for BigQuery so I could connect to all the DB's there and have a central data lake.  There are already several SQL clients that can do this so there must be some groundwork already, but I don't how difficult this is.

**Comment by MarkBennett** [comment]
I'd be very keen to see this implemented for one of my client projects, as BigQuery would be a great fit as would Prisma.

Are there any directions or examples of how to write a data connector? Could this be done in a third-party repo?

**Comment by janpio** [comment]
Not right now unfortunately @MarkBennett. You can fork https://github.com/prisma/prisma-engines/, figure it out and run your own fork of that. Otherwise all options currently depend on Prisma wanting to invest the time and effort in a feature (or create a plugin system). Both is currently not top of priority list for BigQuery.

**Comment by MarkBennett** [comment]
> Not right now unfortunately @MarkBennett. You can fork https://github.com/prisma/prisma-engines/, figure it out and run your own fork of that. Otherwise all options currently depend on Prisma wanting to invest the time and effort in a feature (or create a plugin system). Both is currently not top of priority list for BigQuery.

Makes sense @janpio. I realize every connector is more work for your team, so I'd be in favour of moving towards a plugin system as there will always be people with needs that aren't part of the core. I realize that would be a large undertaking though, so probably not on the roadmap. Thanks for the reply!

If we were to implement our own fork, would it make sense to start by implementing the query and introspection engines first, assuming the migration engine would rely on those if/when it was done?

**Comment by janpio** [comment]
That is one of the problems: Everything depends on everything. (QE and IE tests use ME to boostrap the databases to act on). We'll need to figure that out sooner or later.

**Comment by nick-inkeep** [comment]
Any traction on the above? Does anybody have a fork?

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
