### ISSUE TITLE
Libquery Engine not working on AWS RHEL and CentOS 7 EC2 Images

### ISSUE THREAD

**Issue by okry** [prisma/prisma#13038]
### Bug description

Lately, whenever I try connecting to my MySQL database on my CentOS 7 and RHEL 7.0 EC2 images, the connection attempt fails and gives me the following error:
```
prisma:client:libraryEngine Searching for Query Engine Library in /snapshot/repo/node_modules/.prisma/client +55ms
  prisma:client:libraryEngine loadEngine using /snapshot/repo/node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node +0ms
 ✖ Validate database credentials

An unexpected error occurred:

  Error: Unable to load Node-API Library from /snapshot/repo/node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node, Library may be corrupt
    at Object.loadEngine (/snapshot/repo/node_modules/@prisma/client/runtime/index.js:41375:21)
    at async Object.instantiateLibrary (/snapshot/repo/node_modules/@prisma/client/runtime/index.js:41330:5)
    at async Object.start (/snapshot/repo/node_modules/@prisma/client/runtime/index.js:41480:5)
    at async we.connect (/snapshot/repo/packages/on-prem/dist/js/src/main.js)
    at async Object.nt [as task] (/snapshot/repo/packages/on-prem/dist/js/src/main.js)
    at async ye.runTask (/snapshot/repo/packages/on-prem/dist/js/src/main.js)
    at async ye.loop (/snapshot/repo/packages/on-prem/dist/js/src/main.js)
    at async ye.runChildren (/snapshot/repo/packages/on-prem/dist/js/src/main.js)
    at async ye.loop (/snapshot/repo/packages/on-prem/dist/js/src/main.js)
    at async ye.run (/snapshot/repo/packages/on-prem/dist/js/src/main.js)
```
This has been working on the same above environments since April 12, 2022 and earlier.
~~I've tried using one of our bundles from earlier successful releases and it hasn't worked, although, I was able to get it to connect and run on a non-AWS EC2 image with a local RHEL 7.9 box.~~ Edit: Was able to get it to work with a previous version of my installer. There must've been some kind of issue when I tried uploading the installer to test the production releases.

### How to reproduce

1. Create a CentOS 7 or RHEL 7.0 AWS EC2 image with a MySQL 8.0 database.
2. Attempt to connect to the database with `libquery_engine-rhel-openssl-1.0.x.so.node`.
3. See error

### Expected behavior

Prisma should be able to connect to the database and make successful queries.

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["rhel-openssl-1.0.x", "native"]
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Customer {
  id        Int              @id @default(autoincrement())
  name      String           @db.VarChar(255)
  clientId  String           @unique @map("client_id") @db.VarChar(255)
  createdAt DateTime         @default(now()) @map("created_at") @db.DateTime(6)
  updatedAt DateTime         @default(now()) @map("updated_at") @db.DateTime(6)
  projects  Project[]
  servers   ServerLocation[]

  @@map("customer")
}

...
```

### Environment & setup

- OS: CentOS 7, RHEL 7.0
- Database: MySQL 8.0
- Node.js version: 16.14.2

### Prisma Version

```
3.13.0
```

**Comment by janpio** [comment]
Which Prisma versions have been working, and which have not?
Do you have access to the filesystem on these boxes to potentially look at the files that are supposed to be corrupt?
Is this all the same machine, or different ones?

**Comment by okry** [comment]
So I've looked at it a bit more and tested with our latest production release and I was able to get it to run, so it looks like there actually _is_ a corrupt file.

**Comment by janpio** [comment]
Then the question is where the corrupt file is: Is it on that specific machine or situation, or when you use a specific Prisma version (3.13.0)?

**Comment by okry** [comment]
Yeah so I looked into it and it seems there was something non-prisma related that was causing the corrupt file problem. To solve that, I simply updated my `yarn.lock` to what was on our release branch. But, when I updated it and used `prisma@3.13.0` I was able to get it to work in CentOS 7, but not RHEL 7 where I was still having the corrupt file error. Once I reverted back to `prisma@3.10.0` it was able to run on all of our environments again.

**Comment by okry** [comment]
So, I've dug deeper into this problem. It looks like when we try running our installer, the corrupted one is not adding the right files to the `/tmp/pkg/725c0247147091f70e68f46f35b2d3e60e3ac7ca58f1316f1f933f4e35de4404/.prisma/client/` directory.

On a working installer, it creates it like this
```
index.js
libquery_engine-debian-openssl-1.1.x.so.node
libquery_engine-rhel-openssl-1.0.x.so.node
package.json
schema.prisma
```
On a corrupted installer though, it’s like this
```
index.js
package.json
```

There's a whole bunch of files like this.

**Comment by okry** [comment]
I managed to fix it by copying over the working `libquery_engine-rhel-openssl-1.0.x.so.node` file to the folder created by                                                                                                                                             the corrupted installer and replacing the text of the corrupted index file to "source-code-not-available".

**Comment by okry** [comment]
Something else I figured out, the `/tmp/pkg/725c0247147091f70e68f46f35b2d3e60e3ac7ca58f1316f1f933f4e35de4404/.prisma/client/` directory is created when I initialize Prisma constructor from `@prisma/client`.

**Comment by janpio** [comment]
What are you referring to by "our installer"?

**Comment by okry** [comment]
Sorry, "our installer" is a series of scripts bundled into an executable that my team uses to install our product onto on-prem environments over ssh. One of those scripts is responsible for applying prisma migrations.

**Comment by bakeruk** [comment]
+1

Although you have got around your problem, I am right in saying that this is still an outstanding Prisma issue which need to be fixed by the Prisma team/community?

**Comment by aqrln** [comment]
As far as I understood from the discussion above, this was not a problem in Prisma. I'll go ahead and close the issue, please let us know if there's still anything for us to do on our side.
