### ISSUE TITLE
Error: Unable to require(`/node_modules/prisma/libquery_engine-debian-openssl-3.0.x.so.node`)

### ISSUE THREAD

**Issue by AndreBLima** [prisma/prisma#13034]
"prisma": "^3.13.0",
"@prisma/client": "^3.13.0",
node v16.14.0
Ubuntu 22.04

comand: yarn prisma generate
response: 
```
yarn run v1.22.18
$ /node_modules/.bin/prisma generate
Environment variables loaded from .env
Prisma schema loaded from src/infra/repository/prisma/schema.prisma
Error: Unable to require(`/node_modules/prisma/libquery_engine-debian-openssl-3.0.x.so.node`)
 /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcrypto.so.3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mmillerbkg** [comment]
Similar issue

OS: Debian Bullseye [Kernel: 5.10.0-13-amd64]
Node.js : 16.14.2 & 16.15.0 (Tested on both)
openssl: 3.0.2
libssl-dev: 1.1.1n-0+deb11u1

Command: 
1. yarn prisma {generate, db pull}
2.  npx prisma {generate, db pull}

Output:
1. libssl.so.3: cannot open shared object file: No such file or directory
2. libcrypto.so.3: cannot open shared object file: No such file or directory
3.  /lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.0.0' not found

Tried: 
Linking libssl.so to libssl.so.3 ( Fixed first error )
Linking libcrypto.so to libcrypto.so.3 (Fixed second error)

Stuck on third error 
(I'm not the best with shared libraries & linking can get pretty nasty, but just trying to get back up and running)

**Comment by janpio** [comment]
@AndreBLima Anything special about your Ubuntu 22.04 or can we reproduce this with a simple Docker image?
@mmillerbkg How can we easiest get a system that is in the same state as yours for reproduction?

**Comment by mmillerbkg** [comment]
After a lot of troubleshooting, I found that conda installs the latest version of OpenSSL (3.0.x) as a part of its packages. My PATH was using conda's OpenSSL over Debian's version (1.1.1n). After deactivating the conda env, everything worked as expected. 
Thanks for the fast response & keep up the great work!

**Comment by prosperoking** [comment]
I get 
> Error: Not Found https://binaries.prisma.sh/all_commits/22b822189f46ef0dc5c5b503368d1bee01213980/debian-openssl-3.0.x/libquery_engine.so.node.gz

**Comment by prosperoking** [comment]
The link seems broken

**Comment by janpio** [comment]
@prosperoking I see you solved it over here: https://github.com/prisma/prisma/issues/11356#issuecomment-1113130734

**Comment by janpio** [comment]
@AndreBLima did not report back. It is unclear if they are still have the problem, or if it is resolved. That we are not getting _many more_ reports for Ubuntu 22.04 indicates this might be a custom situation though.

What @mmillerbkg describes seems like a custom situation, but I am not sure if Prisma not figuring out the right thing to do there  is a problem or not.

**Comment by gBusato** [comment]
I'm currently having the same issue on a Ubuntu 22.04 computer

**Comment by FRizZL** [comment]
For me it's fixed after upgrading @prisma/client to version 3.13.0 
`"@prisma/client": "3.13.0"`

**Comment by Frhazz** [comment]
I'm having the issue (Pop!_OS 22.04), tried to upgrade prisma and prisma client to `3.13.0` but still getting
`Error: Unknown binaryTarget debian-openssl-3.0.x and no custom binaries were provided`
when I run `prisma generate`

**Comment by gBusato** [comment]
For anyone who is still having the issue even with :
``"@prisma/client": "3.13.0"``
and 
``"prisma" : "3.13.0"``

I have simply followed the what was shared at this comment : [link](https://github.com/prisma/prisma/issues/11356#issuecomment-1106939907) . 

Here is what I have done :  

1. I havee downgraded my open ssl version to the latest available for me ( check this [link](https://answers.launchpad.net/ubuntu/jammy/+package/libssl1.1)  for me it was : libssl1.1 1.1.1l-1ubuntu1 in amd64 (Release)
2. I have followed all the steps in this tutorial : [How to install openssl in ubuntu](https://fedingo.com/how-to-install-openssl-in-ubuntu/), in this tutorial the guy reference libssl1.1.1c but I did replace it with the latest one libssl1.1.1l 
3. Once the tutorial completed, it was working ! 🔥

**Comment by janpio** [comment]
@Frhazz Sounds like you have a global `prisma` that is maybe an older version? Possible?

**Comment by Frhazz** [comment]
@janpio indeed my global prisma version was older, updated it and now everything's working like a charm. Thank you

**Comment by masterbater** [comment]
Sorry for asking this here but is ubuntu 16 still supported by prisma 3?

**Comment by AndreBLima** [comment]
@janpio, I used @gBusato solution and it worked

**Comment by dpetrick** [comment]
@masterbater 

This isn't really about platform support, it's about the libraries and runtimes we require. Node > 12 for example, and we have builds for OpenSSL 1.0.x, 1.1.x, 3.0.x, so you should be okay with 16.

**Comment by Cryme** [comment]
I had the same issue after upgrading to ubuntu 22 from 21, node was installed using snap! 
What helped: remove snap version, install with apt.

**Comment by gBusato** [comment]
> I had the same issue after upgrading to ubuntu 22 from 21, node was installed using snap! What helped: remove snap version, install with apt.

Wow ! This worked for me !

**Comment by VictorHugoDC1999** [comment]
Good Morning,
Just to be registered and so who knows can help more people...
I did what @gBusato did and it worked for me.
Apparently when installing the ssl version the problem was solved.
Thank you!

**Comment by Wanfadger** [comment]
Had same error, but following @gBusato steps and recommendation worked for me.

**Comment by jorgeeder** [comment]
I Had similar issue, but following @gBusato steps and recommendation worked for me.

**Comment by OmarSalah1911** [comment]
> For anyone who is still having the issue even with : `"@prisma/client": "3.13.0"` and `"prisma" : "3.13.0"`
> 
> I have simply followed the what was shared at this comment : [link](https://github.com/prisma/prisma/issues/11356#issuecomment-1106939907) .
> 
> Here is what I have done :
> 
>     1. I havee downgraded my open ssl version to the latest available for me ( check this [link](https://answers.launchpad.net/ubuntu/jammy/+package/libssl1.1)  for me it was : libssl1.1 1.1.1l-1ubuntu1 in amd64 (Release)
> 
>     2. I have followed all the steps in this tutorial : [How to install openssl in ubuntu](https://fedingo.com/how-to-install-openssl-in-ubuntu/), in this tutorial the guy reference libssl1.1.1c but I did replace it with the latest one libssl1.1.1l
> 
>     3. Once the tutorial completed, it was working ! fire

it worked for me (UBUNTU 22.04)

**Comment by martinpachecolink** [comment]
Facing similar issue in Pop!_os 22.04 LTS 64bit

**Prisma client error:** Unable to run script

> Message: Error in Prisma Client request: 
> 
> Invalid `prisma.model.count()` invocation:
> 
> /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcrypto.so.3)

I fix it by removing the snap version of nodejs

`sudo snap remove node`

and installing via PPA Version. 

`curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&sudo apt-get install -y nodejs`

**Comment by satarovbekzhan** [comment]
> Facing similar issue in Pop!_os 22.04 LTS 64bit
> 
> **Prisma client error:** Unable to run script
> 
> > Message: Error in Prisma Client request:
> > Invalid `prisma.model.count()` invocation:
> > /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcrypto.so.3)
> 
> I fix it by removing the snap version of nodejs
> 
> `sudo snap remove node`
> 
> and installing via PPA Version.
> 
> `curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt-get install -y nodejs`

Easiest way that worked for me!

**Comment by Nilesh-Vincent** [comment]
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x", "debian-openssl-3.0.x"]
}

Adding those to schema.prisma works for me as well
