### ISSUE TITLE
Solve "P1012 Introspection failed" errors on Windows CI

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#13077]
Currently, some test cases that deal with introspection are skipped on Windows machines, as they throw the following error:

```
Error: P1012 Introspection failed as your current Prisma schema file is invalid
```

We should understand why this is happening, and hopefully propose a fix. [Here's an example ](https://github.com/prisma/prisma/blob/f2391f23750c276a40732b199d7efe96d5bc9ba0/packages/migrate/src/__tests__/DbPull.test.ts#L45-L49)of such test case excluded from the Windows CI.

**Comment by Jolg42** [comment]
From https://github.com/prisma/prisma/pull/12910#discussion_r858492375

Here is how to reproduce:

- Initialize a new schema with e.g. the `mongodb` provider: `npx prisma init --datasource-provider mongodb`
- Ensure the schema is valid: `npx prisma validate`
- Run introspection with a URL having a different datasource protocol: `npx prisma db pull --url postgres://prisma:prisma@localhost:5432/tests`

You should see an error similar to the following:

```text
Prisma schema loaded from prisma/schema.prisma
Environment variables loaded from .env
Datasource "db"

✖ Introspecting

Error: P1012 Introspection failed as your current Prisma schema file is invalid

Please fix your current schema manually, use prisma validate to confirm it is valid and then run this command again.
Or run this command with the --force flag to ignore your current schema and overwrite it. All local modifications will be lost.
```

**Comment by Jolg42** [comment]
Potentially related https://github.com/prisma/prisma/issues/14732
