### ISSUE TITLE
Unable to create Prisma Docker image for AWS EC Graviton instance

### ISSUE THREAD

**Issue by friebetill** [prisma/prisma#13073]
### Bug description

After building a Prisma Docker image on a EC2 Graviton instance, I launched this image and get this error message
```
UnhandledPromiseRejectionWarning: Error: Unknown PRISMA_QUERY_ENGINE_LIBRARY undefined. Possible binaryTargets: darwin, darwin-arm64, debian-openssl-1.0.x, debian-openssl-1.1.x, rhel-openssl-1.0.x, rhel-openssl-1.1.x, linux-arm64-openssl-1.1.x, linux-arm64-openssl-1.0.x, linux-arm-openssl-1.1.x, linux-arm-openssl-1.0.x, linux-musl, linux-nixos, windows, freebsd11, freebsd12, openbsd, netbsd, arm, native or a path to the query engine library.
You may have to run prisma generate for your changes to take effect.
    at Object.getPlatform (/home/node/app/node_modules/@prisma/client/runtime/index.js:36103:13)
    at async Object.instantiateLibrary (/home/node/app/node_modules/@prisma/client/runtime/index.js:36094:21)
```
So apparently the Prisma engine cannot be found.

The odd thing is that the error should not occur because I am currently building the image directly on the EC2 Graviton instance and I have set the `build-target` to `native` in my schema:
```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native"]
}
```

When I set the build-target to `arm` only, it gave this error message:
```
Warning: Your current platform `linux-arm64-openssl-1.1.x` is not included in your generator's `binaryTargets` configuration ["arm"].
    To fix it, use this generator config in your schema.prisma:
    generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "arm"]
}
    Note, that by providing `native`, Prisma Client automatically resolves `linux-arm64-openssl-1.1.x`.
    Read more about deploying Prisma Client: https://github.com/prisma/prisma/blob/main/docs/core/generators/prisma-client-js.md
```
If I set the platform `linux-arm64-openssl-1.1.x` directly as build-target, it makes no difference. So the platform linux-arm64-openssl-1.1.x does not seem to work.

### How to reproduce

1. Get an AWS EC2 Graviton instance with Ubuntu 20.04
2. [Install docker](https://docs.docker.com/engine/install/ubuntu/) and follow the [postinstall](https://docs.docker.com/engine/install/linux-postinstall/)
3. Install docker-compose with `sudo apt install docker-compose`
4. Load the broken repository `git clone https://github.com/friebetill/nestjs-prisma-starter-debug-arm.git`
5. Copy the env file `cp .env.example .env`
6. Build the docker image `docker buildx build --platform linux/aarch64 --tag nestjs-prisma-starter-debug-arm_nest-api .`
7. Start the docker image `docker-compose up -d`
8. Take a look at the logs with `docker logs [id-of-container]`

### Expected behavior

I expected that the server would start and there would be no problems. Instead I see the following error message: 
```
(node:1) UnhandledPromiseRejectionWarning: Error: Unknown PRISMA_QUERY_ENGINE_LIBRARY undefined. Possible binaryTargets: darwin, darwin-arm64, debian-openssl-1.0.x, debian-openssl-1.1.x, rhel-openssl-1.0.x, rhel-openssl-1.1.x, linux-arm64-openssl-1.1.x, linux-arm64-openssl-1.0.x, linux-arm-openssl-1.1.x, linux-arm-openssl-1.0.x, linux-musl, linux-nixos, windows, freebsd11, freebsd12, openbsd, netbsd, arm, native or a path to the query engine library.
You may have to run prisma generate for your changes to take effect.
    at Object.getPlatform (/home/node/app/node_modules/@prisma/client/runtime/index.js:36111:13)
    at async Object.instantiateLibrary (/home/node/app/node_modules/@prisma/client/runtime/index.js:36102:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Prisma information

All the information is inside the repository

### Environment & setup

- OS: Ubuntu 20.04
- Database: PostgreSQL
- Node.js version: node:lts

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.8.1
@prisma/client          : 3.8.1
Current platform        : linux-arm64-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/prisma/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-linux-arm64-openssl-1.1.x)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-linux-arm64-openssl-1.1.x)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-linux-arm64-openssl-1.1.x)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
```

**Comment by friebetill** [comment]
As far as I understand it, it means that either
1. the binary of the Prisma engine does not exist for linux-arm64-openssl-1.1.x and therefore cannot be found when running the Prisma server or
2. that the engine exists, but is linked incorrectly.

My guess is that the binary does not exist precompiled, so I would have to compile the engine myself. I found [this post](https://github.com/prisma/prisma/issues/8478#issuecomment-1059559520) to compile the engine and adapted my Dockerfile accordingly:
```dockerfile
### Build the Prisma engine
FROM rust:1.58.1-alpine3.14 as prisma
ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk --no-cache add openssl direnv git musl-dev openssl-dev build-base perl protoc
RUN git clone --depth=1 --branch=3.9.0 https://github.com/prisma/prisma-engines.git /prisma
WORKDIR /prisma
RUN cargo build --release --jobs 1


# To reduce the image size we use a multi-stage build approach, see https://bit.ly/3vMZjNu.
### First stage ###
FROM node:lts AS builder

RUN apt-get install -y curl openssl

WORKDIR /app

ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
  PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
  PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
  PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
  PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
  PRISMA_CLIENT_ENGINE_TYPE=binary
COPY --from=prisma /prisma/target/release/query-engine /prisma/target/release/migration-engine /prisma/target/release/introspection-engine /prisma/target/release/prisma-fmt /prisma-engines/

COPY ./yarn.lock ./package.json ./

COPY . .

RUN yarn install --frozen-lockfile

RUN yarn prisma generate
RUN yarn build

RUN npm prune --production

####################

### Second stage ###
FROM alpine:3.14.0


RUN apk add --update nodejs

RUN addgroup -S node && adduser -S node -G node

USER node

WORKDIR /home/node/app

COPY --from=builder --chown=node:node /app ./

EXPOSE 3000

CMD ["node", "dist/main.js"]
```
But unfortunately at the step `RUN yarn prisma generate` the following error occurs:
```
> nestjs-prisma-client-starter@0.0.1 prisma:generate
> yarn prisma generate

yarn run v1.22.18
$ /app/node_modules/.bin/prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Get config: Error: Command failed with ENOENT: /prisma-engines/query-engine cli get-config --ignoreEnvVarErrors
spawn /prisma-engines/query-engine ENOENT
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Apparently there is some problem with the Prisma engine, which is why it won't start. But I don't really know how to get further, does anyone have a tip?

**Comment by janpio** [comment]
The error message `spawn /prisma-engines/query-engine ENOENT` indicates that no file `/prisma-engines/query-engine` exists. Are you sure the file was copied to that location correctly?

**Comment by friebetill** [comment]
Thanks for your tip @janpio. These files exist in `builder`s filesystem:
```
# ls -lha /prisma-engines
total 116M
drwxr-xr-x 1 root root 4.0K May  4 06:28 .
drwxr-xr-x 1 root root 4.0K May  4 06:25 ..
-rwxr-xr-x 1 root root  31M May  2 11:03 introspection-engine
-rwxr-xr-x 1 root root  33M May  2 10:59 migration-engine
-rwxr-xr-x 1 root root 8.9M May  2 10:49 prisma-fmt
-rwxr-xr-x 1 root root  44M May  2 11:15 query-engine
```

But something is strange, because I can't execute the binaries directly with e.g. `./query-engine cli get-config --ignoreEnvVarErrors`. It's not because I don't have access to it, because I am `root` (tested with `whoami`) and the binaries also have execute access.

According to [this stackoverflow response](https://askubuntu.com/a/133460/652996), it's probably because the binary is designed for 32 bit and I'm trying to run it on a 64 bit system. 

But when I examine the file with e.g. `file query-engine` I get the following output:
```
query-engine: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, with debug_info, not stripped
```
Based on this, it does indeed look like the binary is for 64 bit systems. But I noticed that the interpreter `/lib/ld-musl-aarch64.so.1` does not exist to execute the executable. Instead there is only the interpreter `ld-linux-aarch64.so.1` in the `/lib` folder.

Now I'm not sure if I can just reinstall the interpreter or if the file is already compiled incorrectly. But after I have installed the interpreter with:
```
apt-get update -y
apt-get install -y musl
```
I can run the binary with `./query-engine cli get-config --ignoreEnvVarErrors` and get the following error message:
```

**Comment by janpio** [comment]
> My guess is that the binary does not exist precompiled, so I would have to compile the engine myself.

We have a ecosystem-test that runs on AWS Graviton: https://github.com/prisma/ecosystem-tests/tree/dev/platforms/aws-graviton
It can successfully execute queries, using the `libquery_engine-linux-arm64-openssl-1.0.x.so.node` or `query-engine-linux-arm64-openssl-1.0.x` Query Engine:
https://github.com/prisma/ecosystem-tests/blob/b3e395f3ec54fcc7944eb13b78d57ed789353ad4/platforms/aws-graviton/code/index.test.js#L28-L46

So I think you took a wrong assumption and turn there, and the problem is actually a different one. Possible?

**Comment by friebetill** [comment]
Thanks I have now managed to get the server to start up 
- without Docker (simply with `yarn start`) and
- with Docker without the alpine image.

The server does not start with an Alpine image, but it looks like [many are having problems with it.](https://github.com/prisma/prisma/issues/7755#issuecomment-991403366). The Docker image is now 2.8GB without Alpine instead of 700MB, but I can live with that for now. Thanks for your tips @janpio!
