### ISSUE TITLE
Prisma + MongoDB many Relations not working

### ISSUE THREAD

**Issue by asyncfinkd** [prisma/prisma#13102]
### Bug description

Hello there, today i've got some problem. and idk this is bug or something else.

basically, i've got user model

```
model User {
  id            String   @id @default(auto()) @map("_id") @db.ObjectId
  wishlist      Products @relation(fields: [wishlistId], references: [id])
  wishlistId    String[] @unique @db.ObjectId
}
```

and products

```
model Products {
  id              String     @id @default(auto()) @map("_id") @db.ObjectId
  title           String
  User            User[]
}
```

Query i've got like this (for example):

```
await this.prisma.user.findMany({ include: { wishlist: true } }); 
```

MongoDB (for example):

wishlistId: [ "626cdd27e12f021cce54772f" -> ObjectID ]

any ideas? for fix this.

### Environment & setup

- OS: Mac OS
- Database: MongoDB
- Node.js version: 16.13.0

### Prisma Version

```
3.13.0
```

**Comment by janpio** [comment]
Many to many relations work differently with Prisma and MongoDB right now and require a list on both sides: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb

**Comment by asyncfinkd** [comment]
> Many to many relations work differently with Prisma and MongoDB right now and require a list on both sides: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb

Thanks, for this
