### ISSUE TITLE
Unable to create new project in Prisma data platform after GitHub username change

### ISSUE THREAD

**Issue by wlftuc** [prisma/prisma#13107]
### Bug description

I'm currently trying to make a new project on Prisma Data platform with an existing database, and I keep getting this error again and again. I believe this is happening because I recently changed my GitHub username.

My previous project, which uses the same exact database and schema, is unable to update its schema too. The last my schema updated was 22 days ago, which is odd considering that my last commit to the schema was just 20 minutes ago.

![image](https://user-images.githubusercontent.com/83243777/166119405-6d2515b4-d9d1-4759-8e5a-2169196f656e.png)

### Expected behavior

I should be able to create a new project.

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v16.15.0

### Prisma Version

```
prisma                  : 3.13.0
@prisma/client          : 3.13.0
Current platform        : darwin-arm64
Studio                  : 0.459.0
```

**Comment by janpio** [comment]
Please use the Intercom chat in Data Platform to contact support, they will be able to help you better. Thanks.

**Comment by wlftuc** [comment]
> Please use the Intercom chat in Data Platform to contact support, they will be able to help you better. Thanks.

Okay. I'll do that. Thanks.
