### ISSUE TITLE
`sudo prisma generate` returns error, not found libquery_engine.so.node.gz

### ISSUE THREAD

**Issue by snow-sr** [prisma/prisma#13106]
Hey there, I really don't know what's happening, was working last time I used it.

![Image](https://i.imgur.com/uhj0EBn.png)

It can't download the binaries for the openssl-3.0.x;
Tried using another versions (openssl-1.0 and others), not worked with none of them;

Using POP.os 22.04
GNOME 42.0

**Comment by janpio** [comment]
What version of Prisma are you using? Only 3.13.0 supports OpenSSL 3. (Remember to upgrade both CLI and Client)

**Comment by snow-sr** [comment]
Hey there!
I'm back at my workspace today;

Successfully update the dependencies, and it got back to work!
Thanks!

**Comment by BioSs54** [comment]
Hi @snow-sr !

I have same problem : > Downloading Prisma engines for Node-API for debian-openssl-3.0.x [                    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/34df67547cf5598f5a6cd3eb45f14ee70c3fb86f/debian-openssl-3.0.x/libquery_engine.so.node.gz

Can you telle me  how do you solve it ?
:)
