### ISSUE TITLE
[suport esm client due to new node ssr develop mod and ts 4.7 native esm support]

### ISSUE THREAD

**Issue by skimhugo** [prisma/prisma#13112]
Thansk to vite, we can easily using plugin like https://github.com/axe-me/vite-plugin-node to realize a HMR dev and test mod .

we can using vite ssr to realize:
- dev mod have HMR.(by vite ssr)
- test mod have HMR.(by vitest)
- use vite plugin ecosystem to do something
- prod mod have HMR(not yet)

but there are one caveat:
only support esm due to ssr

It's true we have some work around here,but it is better to have a native esm module for prisma.

**Comment by janpio** [comment]
Main issue for this: https://github.com/prisma/prisma/issues/5030
