### ISSUE TITLE
FindFirst returns the first item even if it is undefined

### ISSUE THREAD

**Issue by vladimiremi** [prisma/prisma#13116]
### Bug description

I was trying to find a user by email, then I realized that my input was sending undefined and even so the findFirst was returning the first user of my database.

### How to reproduce

1. Try searching for a user or anything
2.  Dentro do where, coloque um argumento como undefined, como where: {name: undefined}
3. make the request
4. See that it will return an item, even though it is undefined

### Expected behavior

I expected it to return the user according to the parameters, and in case of undefined it doesn't return any.

### Prisma information

```ks
  getUserByEmail: async ({email}) => {
    console.log({email});
    return await prisma.user.findFirst({
      where: {
        status: 1,
        email: email,
      },
    });
  },
```

### Environment & setup

- OS: Windows 
- Database: MySQL 
- Node.js version:  v16.13.2 

### Prisma Version

```


"@prisma/client": "3.6.0",
```

**Comment by garrensmith** [comment]
hi @vladimiremi we document here about undefined.  https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined#:~:text=Prisma%20Client%20differentiates%20between%20null,undefined%20means%20do%20nothing

I'm going to close this issue but feel free to open it again if the document doesn't help.
