### ISSUE TITLE
prisma generate failed due to file's missing

### ISSUE THREAD

**Issue by calidion** [prisma/prisma#13130]
### Bug description

npx prisma generate
Environment variables loaded from prisma/.env
> Downloading Prisma engines for debian-openssl-3.0.x [                    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/3c463ebd78b1d21d8fdacdd27899e280cf686223/debian-openssl-3.0.x/introspection-engine.gz (

### How to reproduce

execute `prisima generate`

### Prisma information

Irrelevant.

### Environment & setup

- OS:  Ubuntu
- Database:  Mysql
- Node.js version:  v14.18.1

### Prisma Version

```
npx prisma -v
Environment variables loaded from prisma/.env
> Downloading Prisma engines for debian-openssl-3.0.x [                    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/3c463ebd78b1d21d8fdacdd27899e280cf686223/debian-openssl-3.0.x/migration-engine.gz
```

**Comment by janpio** [comment]
You need to use Prisma 3.13.0 for OpenSSL 3 to be supported. 
(If `prisma -v` does not work, you can also figure out your version with `npm list prisma`.)

**Comment by calidion** [comment]
@janpio 
Thanks, seems caused by ubuntu OS version, My OS is Ubuntu is 22.04 now.

**Comment by janpio** [comment]
Yes, exactly. And we release Prisma 3.13.0 to support Ubuntu 22.04 which ships with OpenSSL 3.
Upgrade your Prisma version, and this will work.
