### ISSUE TITLE
Validation Error Thrown on Unique Subset of Foreign Key References

### ISSUE THREAD

**Issue by jpulec** [prisma/prisma#13132]
### Bug description

It seems that Prisma can't detect when a subset of a composite foreign key is unique. For example, if I have the following models:

```prisma
model Order {
  id Int @id
  customerId String
}

model CustomerOrder {
  orderId Int
  customerId String
  
  order Order @relation(references: [orderId, customerId], fields: [id, customerId])
}
```

In the above case, prisma throws a validation error:
```
Error validating: The argument `references` must refer to a unique criteria in the related model `Order`. But it is referencing the following fields that are not a unique criteria: id, customerId
```

However, since `id` is guaranteed to be a unique field on `Order` this should be considered fine.

### How to reproduce

1. Create the models as specified above.
2. Run any prisma command that performs validation, such as `prisma format`
3. See the error:
```
Error validating: The argument `references` must refer to a unique criteria in the related model `Order`. But it is referencing the following fields that are not a unique criteria: id, customerId
```

### Expected behavior

Prisma should not consider this a validation error.

### Prisma information

```prisma
model Order {
  id Int @id
  customerId String
}

model CustomerOrder {
  orderId Int
  customerId String
  
  order Order @relation(references: [orderId, customerId], fields: [id, customerId])
}
```

### Environment & setup

- OS: Linux
- Database: Postgres
- Node.js version: 17.9.0

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../.yarn/unplugged/@prisma-engines-npm-2.31.0-32.2452cc6313d52b8b9a96999ac0e974d0aedf88db-3b9ec476f7/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../.yarn/unplugged/@prisma-engines-npm-2.31.0-32.2452cc6313d52b8b9a96999ac0e974d0aedf88db-3b9ec476f7/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../.yarn/unplugged/@prisma-engines-npm-2.31.0-32.2452cc6313d52b8b9a96999ac0e974d0aedf88db-3b9ec476f7/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../.yarn/unplugged/@prisma-engines-npm-2.31.0-32.2452cc6313d52b8b9a96999ac0e974d0aedf88db-3b9ec476f7/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by janpio** [comment]
Then you should be able to replace `@id` with `@@id[orderId, customerId]` and satisfy the logic of Prisma as well?

**Comment by jpulec** [comment]
> Then you should be able to replace `@id` with `@@id[orderId, customerId]` and satisfy the logic of Prisma as well? Or just add an `@@unique[orderId, customerId]`?

This model is a bit simplified and the `CustomerOrder` object has some other fields, including a different Primary Key. But to your point, I can add `@@unique([ id, customer ])` on the `Order` model, which will satisfy Prisma, as a workaround. It's just not very nice because then when I generate migrations, it tries to add a new unique index that I don't want.

**Comment by tomhoule** [comment]
In this case, we are reflecting the postgres' criteria for deciding what is valid or not, so it still wouldn't be valid when you try to apply the schema to the database.
