### ISSUE TITLE
QueryRaw: Error serializing parameter

### ISSUE THREAD

**Issue by s-montigny-desautels** [prisma/prisma#13158]
### Bug description

When using `$executeRaw` or `$queryRaw`, it is impossible to insert an array containing `Integer` if the schema is of type `Float`.
Prisma seems to type check the values containing the array, since it never sends the query to the database. In fact, if I change the column name to a column that doesn't exist, Prisma send the query to the database, resulting in the expected error.

The error is the following:
```ts
{
  code: 'P2010',
    clientVersion: '3.13.0',
    meta: {
      code: 'N/A',
      message: "error serializing parameter 0: Conversion failed: Couldn't add value of type `Integer(Some(1))` into a double array."
  }
```

I am trying to use raw database access, since `PrismaClient` doesn't support `null` value in scalar list (#12086). However, it still won't let me insert scalar array with null value. I get the same kind of error as when using an `Integer`

```ts
{
  code: 'P2010',
    clientVersion: '3.13.0',
    meta: {
      code: 'N/A',
      message: "error serializing parameter 0: Conversion failed: Couldn't add value of type `Integer(None)` into a double array."
  }
```

If I change the type of the scalar array for **`Real @db.Real`**, I get this variation of the error message:
`message: "error serializing parameter 0: Conversion failed: Couldn't add value of type Integer(None) `**`into a float array`**.`

### How to reproduce

1. Clone https://github.com/s-montigny-desautels/prisma-raw-query-scalar-array
2. Start postgreSQL with `docker-compose up`
3. Run with `npm run start`
4. Toggle between `valuesWithInt` and `valuesWithNull` to see variation of the same error.

### Expected behavior

No error, Prisma doesn't look in the schema for input validation. The database should handle it.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Test {
  id Int @id @default(autoincrement())

  values Float[]
}
```

```ts
const values = [1, 1.2, 1.3]
await prisma.$executeRaw`
    INSERT INTO "Test" (values) VALUES (${values})
`;
```

### Environment & setup

- OS: Linux
- Database: PostgresSQL
- Node.js version: Node v18.0.0

### Prisma Version

```
prisma                  : 3.13.0
@prisma/client          : 3.13.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : efdf9b1183dddfd4258cd181a72125755215ab7b
Studio                  : 0.459.0
```

**Comment by s-montigny-desautels** [comment]
I tested with the release 3.14.0 and by enabling the `improvedQueryRaw` preview feature.

It now work with `null` values in the scalar list. I'm still having the error with `Integer` in `float array` though.

```
Raw query failed. Code: `N/A`. Message: `error serializing parameter 4: Conversion failed: Couldn't add value of type `Int64(Some(1))` into a float array.`
```

I have updated the repo with the reproduction.

**Comment by Jolg42** [comment]
Can reproduce in `4.0.0` and also our internal dev version `4.4.0-dev.30`
```
Raw query failed. Code: `N/A`. Message: `error serializing parameter 0: Conversion failed: Couldn't add value of type `Int64(Some(1))` into a float array.`
    at RequestHandler.handleRequestError (/Users/j42/Repros/14999/node_modules/@prisma/client/runtime/index.js:30850:13)
    at RequestHandler.request (/Users/j42/Repros/14999/node_modules/@prisma/client/runtime/index.js:30833:12)
    at async Proxy._request (/Users/j42/Repros/14999/node_modules/@prisma/client/runtime/index.js:31805:16)
    at async /Users/j42/Repros/14999/main.ts:73:27 {
  code: 'P2010',
  clientVersion: '4.4.0-dev.30',
  meta: {
    code: 'N/A',
    message: "error serializing parameter 0: Conversion failed: Couldn't add value of type `Int64(Some(1))` into a float array."
  }
}
```
