### ISSUE TITLE
Throw error on found request

### ISSUE THREAD

**Issue by rouzbehsbz** [prisma/prisma#13171]
Hi,
I think it's very useful if you add a feature for throwing an error when a query call is successful and returns found object.
just like `rejectOnNotFound`.

for example I want throw an error when user with these parameters are exists, and I can simply write this code:

```
		const {username} = req.body;

		await prisma.users.findFirst({
			where: {
				username: username
			},
			rejectOnFound: () => new Error('User is already exists. try another username')
		})
```

it may be handy and simplify code.

**Comment by janpio** [comment]
`rejectOnNotFound` does not exist as an API anymore, we removed this in Prisam 5.x and replaced it with two explicit API methods `findFirstOrThrow` or `findUniqueOrThrow`: https://www.prisma.io/docs/orm/more/upgrade-guides/upgrading-versions/upgrading-to-prisma-5/rejectonnotfound-changes#replacing-rejectonnotfound-enabled-at-the-query-level

Similarly adding a `rejectOnFound` on a query level would not be desirable. If you want to create such functionality, I suggest you implement `findFirst/UniqueAndThrow` (or similar, not the best name) with a Client Extension: https://www.prisma.io/docs/orm/prisma-client/client-extensions/model#add-a-custom-method-to-all-models-in-your-schema
