### ISSUE TITLE
Prisma+MongoDB+Docker Prisma needs to perform transactions, which requires your MongoDB server to be run as a replica set

### ISSUE THREAD

**Issue by Djamilson** [prisma/prisma#13183]
### Bug description

#prismaClient.ts
```
import { PrismaClient as PrismaClientMongoDb } from '../mongodb/generated/mongodb';
const mongodb = new PrismaClientMongoDb({
  log: ['query', 'info'],
});

export { postgres, mongodb };
```
Here schema-mongodb.prisma

```
generator clientMongoDb {
  provider = "prisma-client-js"
  output   = "./generated/mongodb"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL_MONGODB")
}

model PageAccessCounter {
  id         String   @id @default(auto()) @map("_id") @db.ObjectId
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt

  @@map("page_access_counters")
}
```

.env
```
DATABASE_URL_MONGODB="mongodb://root:tests123@127.0.0.1:27017/shoofertaecommerce?authSource=admin&retryWrites=true&w=majority&directConnection=true&ssl=false&&readPreference=primary&replicaSet=prefer"
```

follow error  code: 'P2031',
```await this.prismaRepository.pageAccessCounter.create(Prisma needs to perform transactions, which requires your MongoDB server to be run as a replica set.)```

### Prisma information

database credentials Prisma schema tests123

### Environment & setup

- OS: Ubuntu 20.04.4 LTS
- Docker: Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
- Database: MONGODB
- Node.js version: v16.15.0

### Prisma Version

```code: 'P2031',
  clientVersion: '3.13.0',
  meta: {}

```

**Comment by janpio** [comment]
What exactly are you reporting here @Djamilson - is your MongoDB server already running as a replica set?

**Comment by Djamilson** [comment]
Hi @janpio, how are you?

Yes, now I can't do the insert, I get the following error:
 ```
const newData = (await this.prismaRepository.pageAccessCounter.create(
  Prisma needs to perform transactions, which requires your MongoDB server to be run as a replica set.
```

mondodb is running on `Docker.`

**Comment by janpio** [comment]
Is it running as a replica set?

**Comment by Djamilson** [comment]
![Captura de tela de 2022-05-05 14-23-19](https://user-images.githubusercontent.com/10201661/166982095-e7e3afff-a1c0-4542-920c-2c70f467dfbc.png)

**Comment by janpio** [comment]
https://www.prisma.io/docs/concepts/database-connectors/mongodb#error-transactions-are-not-supported-by-this-deployment

**Comment by garrensmith** [comment]
Hi @Djamilson this isn't an issue with Prisma. I'm going to close this for now. The above documentation will help you fix this. Feel free to open this issue if the document doesn't help.

**Comment by Djamilson** [comment]
docker-compose.yml

version: '3.7'
services:
 
  mongodb_container:   
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

    ports:
      - 27017:27017

    volumes:
      - mongo:/var/lib/mongo

volumes:
  mongo:
`

**Comment by garrensmith** [comment]
@Djamilson could you give me a bit more context. Did that setup fix the issue or did you get another issue?
