### ISSUE TITLE
`thread '<unnamed>' panicked at 'Did not find a relation for model users and field editedmessages'`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#13193]
> ```
> generator client {
>   provider        = "prisma-client-js"
>   previewFeatures = ["mongoDb", "fullTextSearch"]
> }
> 
> datasource db {
>   provider = "mongodb"
>   url      = env("DATABASE_URL")
> }
> 
> model editedmessages {
>   id          String   @id @default(auto()) @map("_id") @db.ObjectId
>   userId String
>   oldMessage String
>   newMessage String
>   editDate String
>   messageID String
>   user   users   @relation("users", fields: [userId], references: [userId], onDelete: NoAction, onUpdate: NoAction)
>   users  users[]
> }
> 
> model stafftags {
>   id          String   @id @default(auto()) @map("_id") @db.ObjectId
>   v           Int      @map("__v")
>   fullMessage String
>   type        String[]
>   userId      String
> }
> 
> model statistics {
>   id    String @id @default(auto()) @map("_id") @db.ObjectId
>   v     Int    @map("__v")
>   date  String
>   total Int
>   type  String
> }
> 
> model users {
>   id               String           @id @default(auto()) @map("_id") @db.ObjectId
>   v                Int              @map("__v")
>   avatarURL        String
>   firstMessage     String
>   lastMessage String?
>   userId           String           @unique(map: "userId_1")
>   username         String           @unique(map: "username_1")
>   statistics       userstatistics   @relation(fields: [userId], references: [userId])
>   userstatistics   userstatistics[] @relation("users")
>   message       editedmessages   @relation(fields: [userId], references: [userId])
>   editedmessages   editedmessages[] @relation("users")
> }
> 
> model userstatistics {
>   id     String  @id @default(auto()) @map("_id") @db.ObjectId
>   v      Int     @map("__v")
>   total  Int
>   userId String
>   user   users   @relation("users", fields: [userId], references: [userId], onDelete: NoAction, onUpdate: NoAction)
>   users  users[]
> }
> 
> model webusers {
>   id       String  @id @default(auto()) @map("_id") @db.ObjectId
>   username String
>   password String
>   email    String
>   admin    Boolean
> }
> ```
> 
> Throws an error, 
> ```
> ❯ npx prisma format
> Prisma schema loaded from prisma\schema.prisma
> thread '<unnamed>' panicked at 'Did not find a relation for model users and field editedmessages', query-engine\prisma-models\src\builders\internal_dm_builder.rs:122:25
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Error: Unexpected token D in JSON at position 0
> ```
> 

_Originally posted by @schwarzsky in https://github.com/prisma/prisma/issues/4854#issuecomment-1117845073_

**Comment by schwarzsky** [comment]
Thanks. Any help apprecaited.

**Comment by janpio** [comment]
Here is a more minimal version of the schema that shows the same crash:

```prisma
generator client {
  provider        = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model editedmessages {
  id         String  @id @default(auto()) @map("_id") @db.ObjectId
  userId     String
  user       users   @relation("users", fields: [userId], references: [userId])
}

model users {
  id             String           @id @default(auto()) @map("_id") @db.ObjectId
  userId         String           @unique
  userstatistics userstatistics[] @relation("users")
  editedmessages editedmessages[] @relation("users")
}

model userstatistics {
  id     String  @id @default(auto()) @map("_id") @db.ObjectId
  userId String
  user   users   @relation("users", fields: [userId], references: [userId])
}
```

The problem that seems to be causing this is that both relations are called `users` - changing 2 connected instances if `users` to `users2` makes the schema pass validation:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model editedmessages {
  id     String @id @default(auto()) @map("_id") @db.ObjectId
  userId String
  user   users  @relation("users2", fields: [userId], references: [userId])
}

model users {
  id             String           @id @default(auto()) @map("_id") @db.ObjectId
  userId         String           @unique
  userstatistics userstatistics[] @relation("users")
  editedmessages editedmessages[] @relation("users2")
}

model userstatistics {
  id     String @id @default(auto()) @map("_id") @db.ObjectId
  userId String
  user   users  @relation("users", fields: [userId], references: [userId])
}
```

Was this schema created via Introspection @schwarzsky? It looks a bit like that. If so, can you open _another_ issue and post a minimal sample of the data to create that schema via Introspection? That both relations get the same name is a bug that needs to be fixed as well.

**Comment by schwarzsky** [comment]
Relations are done by hand according to docs. Schema created via introspection yes, thanks for reply. Do you still suggest creating a new issue with minimal data?

**Comment by janpio** [comment]
No, then you did the "wrong" thing based on the documentation and this crash here prevented you from getting a good and useful error message that could explan to you how to fix it. We should just fix that.

**Comment by tomhoule** [comment]
The error is coming from getDmmf, which we most likely use for schema validation but is unnecessary here. `prisma format` could just format and not validate, or use prisma-fmt-wasm to validate without the whole DMMF generation machinery.

**Comment by janpio** [comment]
Next steps for @jkomyno: Understand if this is really getDmmf and see if error reporting is triggered. If confirmed, we will see what to do next.

**Comment by janpio** [comment]
Both reproduction schemas above can now successfully execute `prisma format` and `prisma validate` (and the first one then returns some validation errors, while the second one validate succesfully).

Seems this got fixed along the way.
