### ISSUE TITLE
incorect default @prisma/client generate path when using pnpm@7 and monorepo

### ISSUE THREAD

**Issue by skimhugo** [prisma/prisma#13210]
### Bug description

```
✔ Generated Prisma Client (3.13.0 | library) to ./../../../node_modules/.pnpm/@prisma+client@3.13.0_prisma@3.13.0/node_modules/@prisma/client in 601ms
```

### How to reproduce

make a monorepo of pnpm, in a sub project run prisma generate

### Expected behavior

in the project's node_module

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```
3.13.0

**Comment by millsp** [comment]
Hey, this is definitely expected and correct since we respect `pnpm`'s symlinks, which is integral to get `@prisma/client` working with `pnpm`. You can change `pnpm`'s own behavior by creating an `.npmrc` file and change the `node-linker`:
```ts
node-linker=pnp
```

https://pnpm.io/npmrc#node-linker
