### ISSUE TITLE
Unable to use prisma client / generate inside a node module

### ISSUE THREAD

**Issue by cpt-n3mo** [prisma/prisma#13229]
### Bug description

if one uses prisma from within a node module ,
 prisma keeps complaining about needing prisma generate to run, even if this is done before hand..
it seems like prisma client is unable to find the generated stub, 

please allow a option in prisma client and prisma generate to add a custom location.. 
as this makes it unusable within a module.. 

### How to reproduce

1) create a node project with prisma,
2) create a module from this node project
3) use the module in a new / different project

prisma will install its deps in the new project. this is not the expected behavior   as it should stay in its module and not add it to dependencies of the new projects package.json 

running prisma generate from the module will not work  prisma client will only use .prisma/client of its own node modules
while prisma generate will only work on the local folder in the new project

### Expected behavior

it should be possible to use prisma client in a module without this infinite loop for installing and not finding the stubs

### Prisma information

does not matter

### Environment & setup

Arch Linux 5.15.33-1-lts
node -v v17.8.0
npm -v 8.5.5

### Prisma Version

```
"prisma": "^3.12.0"
"@prisma/client": "^3.12.0",

```

**Comment by janpio** [comment]
What do you mean by "create a module"? Can you share the exact step we need to execute to see the problem you are describing?

**Comment by cpt-n3mo** [comment]
good day!
thank u for your response.

ill try to be more clear..

1) create 2 folders folder A and B and run ` yarn init ` in bough
2) in folder A  ` touch index.js `
3) in folder B ` touch app,js `
4) in folder A ` yarn add prisma @prisma/client `
5) add the following to folder A package.json ` "main": "./index.js" `  and  ` "name": "myModuleName" `
6) add the following to index.js in folder A

``` javascript
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()


module.exports = prisma
```
from this point one can do 2 things link or ` yarn add "../A"  < from folder B`

7) in folder A run yarn link 
8) goto folder B and run yarn link "myModuleName"
9) from app.js in folder B ` const prisma = require('myModuleName') ` 
10) from folder B `node app.js` 

the above will fail as prisma generate hes not run. 
if one does a yarn add "../A"
prisma will now be installed as dependencies in folder B


changing ` index.js ` to the following
``` javascript
const {execSync} = require('child_process')
execSync(`npx prisma generate`, { cwd: __dirname, shell: true, stdio: "inherit" })

const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

``` 

now running app.js in folder B 
will still fail as prisma generate will wants to install its stuff inside ` B/node_module/.prisma/client ` this seems weird as it should go to `A/node_modules/.prisma/client` which is where prisma client in ` A/index.js ` is searching.. 
so there seems to be trouble in where prisma generate is generating its things and where prisma clients is searching for its things..

kind regards

**Comment by millsp** [comment]
Thanks for the report, I believe these two behaviors you are mentioning were both fixed, as I recall 1. Prisma Client could search in wrong locations (we recently fixed that), and 2. also could generate in wrong locations based on the resolution of `@prisma/client` (we fixed that too). If there is anything else, please provide us with a reproduction repo. Thanks :)
