### ISSUE TITLE
Error with custom output in NPM monorepo: `Error: ENOENT: no such file or directory, open 'schema.prisma'`

### ISSUE THREAD

**Issue by kn0ll** [prisma/prisma#13233]
### Bug description

When attempting to use a Prisma client with a custom output in an NPM monorepo, I get the following error:

`Error: ENOENT: no such file or directory, open 'schema.prisma'`

I do not get this error when I _don't_ provide a custom `output` path and use `@prisma/client` directly.

Seems related to https://github.com/prisma/prisma/issues/10512, https://github.com/prisma/prisma/issues/13052, https://github.com/prisma/prisma/issues/12921, etc.

Thank you!

### How to reproduce

1. Checkout the example repository: https://github.com/kn0ll/prisma-monorepo-output-bug
2. Follow steps in `README.md`

### Expected behavior

I expect there to be no error.

### Prisma information

See example repository.

### Environment & setup

```
- OS: Debian GNU/Linux 10 (buster)
- Database: postgres v13.1
- Node.js version: v16.15.0
- NPM version: v8.5.5
```

### Prisma Version

```
prisma                  : 0.0.0
@prisma/client          : 3.14.0-integration-tweak-ci.5
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine cbc216d31d31c3b722f24b03f68be12a595dfea6 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli cbc216d31d31c3b722f24b03f68be12a595dfea6 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core cbc216d31d31c3b722f24b03f68be12a595dfea6 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt cbc216d31d31c3b722f24b03f68be12a595dfea6 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : cbc216d31d31c3b722f24b03f68be12a595dfea6
Studio                  : 0.459.0
```

**Comment by Geebrox** [comment]
Facing the same issue.

### ENV
```
- OS: macOS Monterey v12.3.1
- Database: MongoDB
- Node: v16.13.0
- NPM: v8.1.3
- Yarn: v1.22.17
```

### Prisma:
```
- @prisma/client: v3.12.0
```

### Some description:
This issue started when I upgraded `@prisma/client` from `v3.10.0` to `v3.13.0`. I decided to find out starting from which version this issue started to happen. I downgraded `@prisma/client` to `v3.10.0` and started upgrading the minor version. Result: The issue happens starting from `v3.12.0`

### Reproduction
I have created a branch in one of my repos where this issue happens: https://github.com/Geebrox/next-nest-mono

Steps to reproduce:
1. Clone the repo
2. Checkout to the branch called `prisma-error` (`git checkout prisma-error`)
3. Install dependencies (`yarn install`)
4. Populate `.env` vars
5. Run dev command (`yarn dev`)


Hope this will help to resolve this issue. Thanks!

**Comment by remorses** [comment]
I fixed this adding to `.npmrc` the following, this forces the prisma package to remain on top of the monorepo i think

```
public-hoist-pattern[]=*prisma*
```

**Comment by nwidynski** [comment]
Just ran into this issue aswell in an nx monorepo.

```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at ../../../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at ../../../node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at ../../../node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at ../../../node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
```

**Comment by JUNIORCO** [comment]
Same issue in an npm repo running prisma 4.4.0.

**Comment by millsp** [comment]
@kn0ll I opened a PR with a workaround to make this work https://github.com/kn0ll/prisma-monorepo-output-bug/pull/1

**Comment by janpio** [comment]
@Geebrox Do you still have that branch `prisma-error` around somewhere? We would love to test our workaround there as well. Thanks!

@nwidynski @JUNIORCO Do you maybe have a project that can show the problem? We would love to be able to test your reproduction and then also see if our workaround helps with the problem. Thanks.

**Comment by Geebrox** [comment]
@janpio I think it is moved to `prisma-13052` branch. I cannot find `prisma-error` branch 😞

**Comment by janpio** [comment]
Thanks @Geebrox, now I could connect a few dots and learned a lot here. I will create a new issue for your original situation with a modified reproduction of yours.

**Comment by janpio** [comment]
Issue created and will now clean up a bit: https://github.com/prisma/prisma/issues/17630

**Comment by slimshreydy** [comment]
Hey @janpio just commenting here to give some context around my new issue (which you can see right above) -- I have a very similar setup to this, but my module is an ESM module rather than CJS and that breaks things.

You can see more details on my issue [here](https://github.com/prisma/prisma/issues/17687) and through my repro repo [here](https://github.com/slimshreydy/prisma-monorepo-esm-output-bug).

**Comment by millsp** [comment]
Hey guys, thanks for the feedback. We have been working on a simpler way to make things work for you, as the workaround we proposed had clear limitations for TS projects. We worked on an experimental webpack plugin that ensures your Prisma files are copied correctly. I'd love if you could give it a try (https://www.npmjs.com/package/experimental-prisma-webpack-plugin). We have tested it in many different scenarios, so we hope this works for you.

```ts
const { PrismaPlugin } = require('experimental-prisma-webpack-plugin')

module.exports = {
  output: 'standalone',
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.plugins = [...config.plugins, new PrismaPlugin()]
    }

    return config
  },
}
```

**Comment by millsp** [comment]
For those using multiple Prisma Clients, we are going to schedule follow-up work via https://github.com/prisma/prisma/issues/18069. Please upvote it if you need multi-client support, and don't hesitate to share more information there.
