### ISSUE TITLE
`findFirst(undefined)` returns without error

### ISSUE THREAD

**Issue by alexanderattar** [prisma/prisma#13234]
### Bug description

Calling `findFirst` on a model with an input for `id` of undefined returns the first row in the database for the table essentially failing silently. If undefined is passed in it should either return an error or return null.

### How to reproduce

```    
const item = await this.prisma.items.findFirst({
  where: { id, isActive: true },
});
```

### Expected behavior

If undefined is passed in it should either return an error or return null.

### Prisma information

model Item {
  id           String     @id @default(uuid())
}

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 

### Prisma Version

```
v16.13.2
```

**Comment by dpetrick** [comment]
This is not a bug. Please refer to [our docs](https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined) for an explanation how we interpret undefined.
