### ISSUE TITLE
Prisma memory leaks on Multitenant applications

### ISSUE THREAD

**Issue by TheVoid-0** [prisma/prisma#13232]
### Bug description

I believe this is a known issue ([#5050](https://github.com/prisma/prisma/issues/5050)), however I'm creating this issue to see if someone can help me  with any workaround.

This is what happens to ALL our applications currently using prisma: 
![image](https://user-images.githubusercontent.com/55706765/167197775-d7e29fca-0098-4bf6-b24d-2d660d4f2c1a.png)
In the image you can see the APIs are restarting once it reaches 600Mbs of memory, and without the memory cap they go on forever until the containers crash.

What have I tried?

I tried reading the prisma client code to see what could be the cause, only thing I found is an engines array on `LibraryEngine.ts` file that gets pushed everytime a new client is instantiated, considering a new client is instantiated each request on a multitenant application, that could clearly cause a memory leak, however I created a build slicing that array every time the client stops the engine to see what happens
```ts
// stop method from LibraryEngine
if (this.libraryStarted) {
      // eslint-disable-next-line no-async-promise-executor
      this.libraryStoppingPromise = new Promise(async (resolve, reject) => {
        try {
          await new Promise((r) => setTimeout(r, 5))
          debug('library stopping')
          await this.engine?.disconnect()
          this.libraryStarted = false
          this.libraryStoppingPromise = undefined
          // Next 3 lines were added;
          const engineIdx = engines.indexOf(this)
          engines.splice(engineIdx, 1)
          console.log(engines)

          debug('library stopped')
          resolve()
        } catch (err) {
          reject(err)
        }
      })
      return this.libraryStoppingPromise
    }
```
Well that clears the engines array, but it didn't solve the issue, even with this modified code the application still keeps draining memory. Wich means I couldn't understand all the code logic, the issue linked mentioned using only one query engine, but that would lock out the multitenancy, because prisma depends on the query engine to connect to each database, right? So a tenant application NEEDS several query engines to exist, but they need to be garbage collected

What can be done to avoid such memory leaks? Is there any workarounds even if it means creating slight modifications inside the prisma code, we could run a custom client built locally for now.

Any help on this is really apreciated!

### How to reproduce

1- Create a loop
2- Instantiate a PrismaClient inside the loop
3- Initialize (start the inner query engine) inside the loop
4- wait until your node process crashes you PC :)

### Expected behavior

Once the client is garbage collected, i.e the variable containing the PrismaClient instance goes out of scope, the memory allocated by that instance should be freed.

### Prisma information

Not necessary

### Environment & setup

- OS: All platforms
- Database: MySQL
- Node.js version: 16.1

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by TheVoid-0** [comment]
Thanks for the help @binary64 

Addressing your question, yes it is one database for each tenant, they are on multiple servers, and I can only know where each of them are on runtime, using authentication token.

I've tried several types of caching and disposing, but currently I'm holding no arrays in my code logic, every tenant call have an `await prisma.$disconnect()` after, I can assure you that we are holding no open connections, but the problem is the memory still grows event though the client disconnects, so even if I tried your proposed solutions I am pretty sure it would not solve complety the problem since it seems the memory usage comes from the prisma itself. But I'm quite curious, you said you are a multi-tenancy user as well, you haven't encountered any problems with memory? Or maybe all of your databases are on the same server, or do not require multiple prisma intances?

I've been with this problem quite a while now, our APIs that rely on multi-tenancy are restarting regularly because of the memory growth, we are currently switching this APIs to TYPEORM new version 0.3 since it seems to not hold the connections anymore, but prisma have some majors advantages over typoORM even on 0.3, I would prefer sticking to it if I could solve this issue

**Comment by mvisintin** [comment]
Hello,

we are experiencing this as well and it has been impacting our ability to run tests against our application.

when running tests in our Jest setup we do instantiate multiple Prisma clients (one per each test suite running). We made sure to properly `.$disconnect()` - still we saw the memory increase constantly.

Using `--detect-leaks` in Jest we managed to track this down to the instantiation of `PrismaClient`.

We are going to add a reproduction repository soon.

**Comment by pantharshit00** [comment]
Can you actually share a minimal reproduction in a small git repository that we can have a look at? It would be very hard to replicate the exact situation you are facing if we just go by the description.

**Comment by mvisintin** [comment]
Thank you for answering.

We have found a more appropriate issue and added more information there 
https://github.com/prisma/prisma/issues/12339#issuecomment-1138753702

**Comment by TheVoid-0** [comment]
#9041 Just now found this issue where @janpio tried "almost" the same thing a while back, so it is indeed a known issue, on this pull request  it looks like the problem was solved, strangely when I try a build slicing the engines array or setting it to undefined the memory continues to go up, I must be missing something because playing with the `engines` variable didn't made any notable difference on memory build up

**Comment by matthewmueller** [comment]
Closed by https://github.com/prisma/prisma/pull/14174

**Comment by janpio** [comment]
Hey @TheVoid-0 can you maybe take a look with 4.1.0 and see if you can still see the problem in any way? We are pretty confident we got most of it, but confirmation would of course be super helpful. Thanks!
