### ISSUE TITLE
Docker container don't restart after a prisma connection is opened

### ISSUE THREAD

**Issue by alexsro** [prisma/prisma#13236]
### Bug description

Hello, I am just starting to use prism and I face a problem when I save my file and my containers are restarted, if the connection to prism has not been established yet everything is fine, otherwise the container cannot restart.
Obs. The connection with database and the requests work well.

message:
Captura de tela de 2022-05-05 21-02-33

### How to reproduce

Create a node project using prisma with the information given below, after opening the connection with the prisma client, change a file and wait for the containers to restart

### Prisma information

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema
// CTRL + SHIFT + I PARA FORMATAR

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id       String @id @default(uuid())
  name     String
  email    String @unique
  password String
  created_at DateTime @default(now())
  updated_at DateTime @default(now())

  @@map("users")
}

### Environment & setup

Ubuntu
PostgreSQL
Node.js version: v16.15.0

My docker-compose.yml:

version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres-auth-api
    environment:
      - POSTGRES_USER=User
      - POSTGRES_PASSWORD=Pass
    ports:
      - 6432:5432
    volumes:
      - data_postgres

  data_postgres:
    image: cogniteev/echo
    command: echo 'Data Container for Postgres'
    volumes:
      - /var/lib/postgresql/data

  app:
    build: .
    command: yarn dev:server
    container_name: auth-api
    ports:
      - 3334:3334
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links: 
      - data_postgres
      - postgres
    restart: always
my database url :

DATABASE_URL="postgresql://User:Pass@172.25.0.2:5432/postgres?schema=public"

I created a network for communication between the containers with the following commands:

docker network create auth-api-network
docker network connect auth-api-network auth-api
docker network connect auth-api-network postgres-auth-api

### Prisma Version

3.11.1

**Comment by janpio** [comment]
Please stop creating issues that already exist as a discussion: https://github.com/prisma/prisma/discussions/13208
