### ISSUE TITLE
prisma2 doesn't support google cloud functions.

### ISSUE THREAD

**Issue by gaspan** [prisma/prisma#1324]
i try to deploy my prisma2 graph server to google cloud functions, but it's not supported.

**Comment by divyenduz** [comment]
Prisma does support GCF, we have an example for it as well https://github.com/prisma/prisma-examples/tree/master/deployment-platforms/google-cloud-functions

Please give it a go. If you run into an issue, please re-open a new issue using the bug template.

**Comment by ludusrusso** [comment]
Hi @divyenduz , the link you provided is not available! Do you have some other resources to check?

**Comment by divyenduz** [comment]
@ludusrusso Sorry about that, the examples moved around, here is an alternate link from our E2E tests https://github.com/prisma/e2e-tests/tree/master/platforms/gcp-functions
