### ISSUE TITLE
Unable to update with MongoDB in AWS DocumentDB

### ISSUE THREAD

**Issue by emimarz** [prisma/prisma#13247]
### Bug description

Hi everyone,

I have a typescript + node + prisma + mongo app
Locally works fine even working with mongo atlas. but when I deploy my solution on aws upsert and update fails and give me an unfriendly message

```
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "Command failed (): Feature not supported)" } })
    at Object.request (/var/www/somedir/node_modules/@prisma/client/runtime/index.js:45633:15) {
  clientVersion: '3.13.0'
}
```

export DEBUG="*"
don't provide more explanation

also add those 
```
new PrismaClient({
          log: [
            {
              emit: 'stdout',
              level: 'query',
            },
            {
              emit: 'stdout',
              level: 'error',
            },
            {
              emit: 'stdout',
              level: 'info',
            },
            {
              emit: 'stdout',
              level: 'warn',
            },
          ],
        });
```

nothing seems improve error

### How to reproduce

```
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({
          log: [
            {
              emit: 'stdout',
              level: 'query',
            },
            {
              emit: 'stdout',
              level: 'error',
            },
            {
              emit: 'stdout',
              level: 'info',
            },
            {
              emit: 'stdout',
              level: 'warn',
            },
          ],
        });
        
prisma.$connect();
let result = prisma.tabledata.upsert({
  where: {
    code_city: {
      code: 'bTKznB3ppPVQu8tOmW0DtA1DlfRloGFtCUW5C0',
      city: 'placeA'
    }
  },
  update: {
    phone: 'update phone'
  },
  create: {
    code: 'bTKznB3ppPVQu8tOmW0DtA1DlfRloGFtCUW5C0',
    city: 'placeA',
    address: 'another data',
  }
});
```
i tried also replace upsert with a select and a create and update but update fails but in both cases create work fine, from console I can do an update and upsert but not via prisma.

### Expected behavior

update data

### Prisma information

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["mongoDb", "extendedIndexes"]
}

datasource db {
  provider = "mongodb"
  url      = env("DSN")
}

model tabledata {
  id String @id @default(auto()) @map("_id") @db.ObjectId
  code String
  city String
  phone String?
  address String?
  @@unique([code,city])
}
```

### Environment & setup

- OS: Ubuntu 18.04.4 LTS
- Database: aws mongodb ~ documentdb
- Node.js version: v12.18.2  all version fails

### Prisma Version

```
prisma                  : 3.13.0
@prisma/client          : 3.13.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : efdf9b1183dddfd4258cd181a72125755215ab7b
Studio                  : 0.459.0
Preview Features        : mongoDb, extendedIndexes
```

if some one ask my dsn is something like this

`DSN="mongodb://user:pass@myserver.cluster.us-west-2.docdb.amazonaws.com:27017/mydatabase?authSource=mydatabase&retryWrites=false&tls=true&tlsCAFile=mypem.pem"
`

EDIT: I update prisma to the latest and that only improve the error a little
EDIT 2: After upgrade prisma version can not create but it was possible before with version 3.10.0

**Comment by janpio** [comment]
> prisma                  : 3.10.0
> @prisma/client          : 3.10.0

The first step here would be to update to the newest Prisma to make sure this is not a bug that we already fixed. Can you please do that and report back? Thanks.

**Comment by emimarz** [comment]
I already do it, that improve the message but not much

**Comment by emimarz** [comment]
the problem is that in 3.10.0 version of prisma allow insert but at 3.13.0 not
update can not be done in both, I think that this is something wrong with prisma not documentdb

**Comment by janpio** [comment]
This feature request has more information on why this is not working right now, and that we unfortunately do not plan to fix this any time soon: https://github.com/prisma/prisma/issues/13205
