### ISSUE TITLE
`migrate dev` errors with `The underlying table for model `_prisma_migrations` does not exist.` when using a non default PostgreSQL schema

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#13269]
### Bug description

Here the project is using a non default PostgreSQL schema `error-handling-prod` (i.e. not `public`) 

`npx prisma migrate dev` errors with 

```
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "mydb123", schema "error-handling-prod" at "localhost:5432"

PostgreSQL database mydb123 created at localhost:5432

Applying migration `20220510114355_baseline`
Error: P1014

The underlying table for model `_prisma_migrations` does not exist.
```

Screenshots from TablePlus, it seems the `_prisma_migrations` was created in the `error-handling-prod` schema but Prisma Migrate tries to find it in the `public` schema where it's missing maybe?
<img width="760" alt="Screen Shot 2022-05-10 at 15 15 51" src="https://user-images.githubusercontent.com/1328733/167637261-f3575bcb-8e33-4268-a29c-f94684066e25.png">
<img width="759" alt="Screen Shot 2022-05-10 at 15 15 44" src="https://user-images.githubusercontent.com/1328733/167637275-d90798f7-e5e0-4fc7-b452-131109f40a0a.png">

### How to reproduce

Clone https://github.com/Jolg42/repro-13269

- `yarn`
- check .env and add a valid connection string
- `yarn prisma migrate dev`

### Expected behavior

Should work

### Environment & setup

- OS: macOS
- Database: PostgreSQL 
- Node.js version: 16.10

### Prisma Version

```
3.14.0-dev.60
```

**Comment by tomhoule** [comment]
Can you share the contents of the migrations directory?

**Comment by Jolg42** [comment]
@tomhoule see full repro at https://github.com/Jolg42/repro-13269

**Comment by Jolg42** [comment]
The baselining using pg_dumo was successful after commenting out the following line from the migration.sql file
```
SELECT pg_catalog.set_config('search_path', '', false);
```
