### ISSUE TITLE
Netlify: `Query engine library for current platform "rhel-openssl-1.0.x" could not be found. You incorrectly pinned it to rhel-openssl-1.0.x`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#13266]
When naively deploying a local project with `netlify deploy`, you can end up with this error message:

```
Error: 
Invalid `prisma.player_scores.findMany()` invocation in
/var/task/netlify/functions/getScores.js:32:48

  29 var import_client = __toModule(require("@prisma/client"));
  30 var prisma = new import_client.PrismaClient();
  31 var handler = async (event, context) => {
â†’ 32   const allScores = await prisma.player_scores.findMany(
  Query engine library for current platform "rhel-openssl-1.0.x" could not be found.
You incorrectly pinned it to rhel-openssl-1.0.x

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/var/task/node_modules/@prisma/client/runtime/libquery_engine-rhel-openssl-1.0.x.so.node")

Searched Locations:

  /var/task/node_modules/.prisma/client
  C:\Users\Jan\Documents\throwaway\cockroachBlogPost\node_modules\@prisma\client
  /var/task/node_modules/@prisma/client
  /var/task/node_modules/.prisma/client
  /var/task/node_modules/.prisma/client
  /tmp/prisma-engines
  /var/task/node_modules/.prisma/client


To solve this problem, add the platform "rhel-openssl-1.0.x" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
    at Object.request (/var/task/node_modules/@prisma/client/runtime/index.js:39824:15)
    at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:40646:18)
    at async Runtime.handler (/var/task/netlify/functions/getScores.js:32:21)
``` 

<img width="719" alt="image" src="https://user-images.githubusercontent.com/183673/167626716-1b7f5956-ae5e-4cba-930f-0a42c904d114.png">

The schema I deployed here:
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["cockroachdb"]
}

datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}

model player_scores {
  id        BigInt  @id @default(autoincrement())
  player_id BigInt
  score     BigInt
  players   players @relation(fields: [player_id], references: [id], onDelete: NoAction, onUpdate: NoAction, map: "fk_player")

  @@index([score], map: "player_scores_score")
  @@index([player_id], map: "player_scores_player_id")
}

model players {
  id            BigInt          @id @default(autoincrement())
  name          String
  email         String
  player_scores player_scores[]
}
```

So it is _not_ pinned to `rhel-openssl-1.0.x` in `binaryTargets`.

Reproduction: 
- Clone https://github.com/cockroachdb/cockroachdb-typescript/tree/9d4a139def2c78d93b637e9a70472f122276f2ae
- `npm install`
- `npm run build`
- `npx netlify deploy`
- Open the deployment, then go to the (failing) functions URL

**Comment by millsp** [comment]
Hey, we wanted to give you an update about this. We have around 10 issues that we have identified to be in the "engine not found" category. Looking at these, we learned that there are four main categories responsible for these errors:

* Your client was generated with `native` (default) on one platform, but used on a different platform at runtime.
* You pinned `binaryTargets` incorrectly, and the correct engine was therefore not included at runtime.
* A bundler/framework changed the Prisma Client but did not copy the necessary engine for the runtime.
* Deployment/tooling did not copy the engine correctly so the correct engine was not included at runtime.

These cases were previously not detected. On top of that, the error messages were confusing and were neither helpful for you or us. With that, it is likely that many of the cases above overlapped each other. So while we cannot fix a missing engine, we can detect how and why it happened. Thanks to that, we now display more useful errors to help you out of trouble. And in some cases, we will ask some input from you to learn more about your project so we can further improve.

If something is still off for you, feel free to create a new issue.
