### ISSUE TITLE
findMany where id in: array returns randomly ordered results

### ISSUE THREAD

**Issue by zfoster** [prisma/prisma#13278]
### Bug description

Running findMany with in: [1, 2, 3, etc] returns values in non-deterministic order.

I have an array of IDs in the order I want my array of objects, but at seemingly large scale I run into connection pool issues from using `promise.all(object => prisma.object.findUnique)`

### How to reproduce

```
const ids = [uuid1, uuid2, uuid3, uuid4, ..., uuidn]

const thoughts = await prisma.thought.findMany({
    where: {
      thoughtId: {
        in: thoughtIds,
      },
    },
})

console.log(thoughts[0].id, ids[0])
=>  these are different
```

My objects sort logic is fairly complicated and more easily handled at query time in another db environment. 

### Expected behavior

Objects returned using `in: array` return in the array order or some well-defined order.

### Prisma information

```
const thoughts = await prisma.thought.findMany({
    where: {
      thoughtId: {
        in: thoughtIds,
      },
    },
})
```

this is the only query I'm running

### Environment & setup

- OS: mac OS
- Database: psql
- Node.js version: v14.17.6

### Prisma Version

```
3.3.0
```

**Comment by dpetrick** [comment]
This is not a bug - `in` operators on certain databases (PG included) doesn't guarantee any ordering and Prisma doesn't do (in 99% of cases anyway) automatic ordering. You'd need to specify an ordering (with `orderBy`) with your query to get a consistent ordering.
