### ISSUE TITLE
Update default behaviour when reading env variables

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma#13295]
### Bug description

When there's a `DATABASE_URL` environment variable set using `export` (global env), and a `.env` file in a project, the default of Prisma is reading the global env instead of using the variable in the `.env` file.

### How to reproduce

set a `DATABASE_URL` using export

```
export DATABASE_URL=""
```

Add a different `DATABASE_URL` variable in the `.env` file

```
# .env
export DATABASE_URL="sqlserver://localhost:1433;initialCatalog=sample;integratedSecurity=true;trustServerCertificate=true;"
```

Run `npx prisma db push` or `npx prisma db pull`

### Expected behavior

Read the `.env` variable values instead of the exported variable

### Environment & setup

- OS: Mac OS
- Database: SQL Server
- Node.js version: 16.13.4

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by janpio** [comment]
This is default behavior of `dotenv`, the library we use (https://github.com/motdotla/dotenv#override), and also the documented and expected behavior of such a setup. What might be suboptimal is that you are not explicitly told about this so it is hard to discover. You might want to open an issue to ask that this is surfaced to the user instead.
