### ISSUE TITLE
MongoDB - prisma db pull

### ISSUE THREAD

**Issue by nirnejak** [prisma/prisma#13294]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v16.14.0           | 
| Prisma CLI  | 3.14.0             | 
| Engine      | 2b0c12756921c891fec4f68d9444e18c7d5d4a6a| 

## Error
```
Error: [/rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/str/mod.rs:653:13] byte index 36 is not a char boundary; it is inside 'с' (bytes 35..37) of `TradeInValuationRequestSequelize.b2сMi`
```

**Comment by janpio** [comment]
Thanks for the report @nirnejak. Does `TradeInValuationRequestSequelize.b2сMi` give you any indication from which collection this could be? Can you maybe share the content of that collection with us (privately to schemas@prisma.io)? That would help us a lot to reproduce this crash.
