### ISSUE TITLE
Implement: Prisma.CreateOnTrasaction / DeleteOnTransaction

### ISSUE THREAD

**Issue by ltnscp9028** [prisma/prisma#13309]
## Problem
prisma create, delete method to use transaction.
Why use transaction to one insert or update??

for example, 
```
await this.prismaService.customer.create({
            data: {
                name: 'hello',
                email: 'ltnscp9028@gmail.com',
                password: 'password',
            },
        });
```
Code create this Query.

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/83194929/167987962-51e2651d-41e6-4b84-8be2-87899819b4b3.png">

## Suggested solution
Implement CreateOne, DeleteOne method and not use transaction.
OR,
Implement CreateOnTrasaction, DeleteOnTransaction method.

## Alternatives
Pass method Option.
```
await this.prismaService.customer.create({
            data: {
                name: 'hello',
                email: 'ltnscp9028@gmail.com',
                password: 'password',
            },
            //@TODO (true or false)
            transaction:Boolean 
        });
```

**Comment by janpio** [comment]
When possible Prisma now uses only 1 query, which makes the wrapping in a transaction obsolete.
