### ISSUE TITLE
Have a way to run or bypass a generator declared in the schema.prisma file

### ISSUE THREAD

**Issue by malko** [prisma/prisma#13327]
## Problem
When declaring multiple prisma generators in you schema.prisma you probably want some of them to not be run for production build.
For example using a doc or dbml generator is useful for developpers but we don't want them to be run at build time as we won't push the result to our production servers and we want to reduce our CI/CD pipelines build time.

## Suggested solution
- One solution would be to add a parameter in the generator config to run or bypass a the given generator. 
ex: 
```
generator client {
  generate = true
  provider = "prisma-client-js"
  binaryTargets = ["native"]
}

generator dbml {
  generate = env("USE_DBML_GENERATOR")
  provider = "prisma-dbml-generator"
  output     = "./"
  outputName = "maiasaura.dbml"
}
```

- Another solution which could bring more flexibility would be a way to include part of the schema dynamically 
```
include env("GENERATOR_INCLUDES_PATH")
```
(sorry if  an include already exists didn't find any reference about it)

- Finally a list of ignored generator declared as env variable before the build may be a simpler alternative to implement (less practical for end users)

## Alternatives

In the mean time the only way that came out of my head is to have a script to clean the schema before build

**Comment by danielkappelle** [comment]
+1

For now I fixed it with the following line in my Dockerfile

```
RUN perl -i -p0e 's/generator (docs|dbml) {[^}]*}//seg' ./prisma/schema.prisma
```

**Comment by capaj** [comment]
this should get prioritized

**Comment by senorscan** [comment]
+1 

Nice work around @danielkappelle. I don't have perl available in the docker image I am using so used `sed`. The following worked ok

```
RUN sed -i '/generator nestgraphql.*{/,/^}/d' ./prisma/schema.prisma
```

**Comment by janpio** [comment]
Potentially relevant: https://github.com/prisma/prisma/pull/16452

**Comment by janpio** [comment]
https://github.com/prisma/prisma/pull/16452 has been merged, which adds a `--generator` argument to `prisma generate` which you can use to specify one or multiple generators that you want to run (vs. the default that runs all of them). This should give you a CLI based way to achieve part of what this issue asks for. Do you agree @malko?

**Comment by malko** [comment]
It can do the trich thanks
