### ISSUE TITLE
Seeding fails

### ISSUE THREAD

**Issue by ekkis** [prisma/prisma#13342]
I've followed the instructions at: https://www.prisma.io/docs/guides/database/seed-database for Javascript (not Typescript) and when I run the command I get:

```
$ npx prisma db seed
Environment variables loaded from prisma/.env
Running seed command `node ./prisma/seed.js` ...
(node:75611) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/ekkis/dev/prisma/seed.js:1
import { PrismaClient } from '@prisma/client'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
```

what is wrong?

**Comment by janpio** [comment]
Your `seed.js` seems to include Tyypescript. The example seed script for Javascript uses `const { PrismaClient } = require('@prisma/client')`.

**Comment by ekkis** [comment]
ok.  that's embarrassing.  you're correct.  thank you
