### ISSUE TITLE
Export table column names as variables

### ISSUE THREAD

**Issue by reggi** [prisma/prisma#13349]
I'd like the ability to access prisma-defined variables for the table columns.

There's an example on this [page](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filter-on-exact-field-value)

As authored in the docs:

```
var json = { [{ name: 'Bob the dog' }, { name: 'Claudine the cat' }] }

const getUsers = await prisma.user.findMany({
  where: {
    extendedPetsData: {
      equals: json,
    },
  },
})
```

I'd like to pass in `extendedPetsData` as a variable defined in Prisma (possibly enum, or object).

```
var json = { [{ name: 'Bob the dog' }, { name: 'Claudine the cat' }] }

const getUsers = await prisma.user.findMany({
  where: {
    [prisma.user.keys.extendedPetsData]: {
      equals: json,
    },
  },
})
```

This would help code fail if someone changes the name of the column, and help keep track of what's queried where.

Just a thought, perhaps useful to others, or maybe workaround exists.

**Comment by Weakky** [comment]
Hey @reggi,

I think I'm missing what you're hoping to achieve here. The Prisma Client generates type definitions based on your Prisma Schema precisely to raise TS errors if your db migrations are breaking.

Suppose you rename the `extendedPetsData` column. In that case, type definitions will change and TS will let you know that `extendedPetsData` is not a valid key object in the `where` clause, which is what you seem to be hoping to achieve with the dynamic key.

Don't hesitate to elaborate if I've missed something

**Comment by reggi** [comment]
@Weakky  i suppose you're right the typings take care of this case, I still think a string for column names would be useful will close for now.
