### ISSUE TITLE
Prisma MongoDB - Connection timeout problem.

### ISSUE THREAD

**Issue by casperibo** [prisma/prisma#13346]
### Bug description

Hi, I'm using Prisma with MongoDB Atlas. I deployed my project with Heroku and if someone didn't visit my website for a while. My prisma apollo queries causes a problem because of prisma mongodb query inside of it.

For example: I visited the website and I saw error, I refresh the page and then error gone. After a few hours I revisited the website again I saw error after refresh the page the error gone.

A image while try to login:

[https://i.ibb.co/dgXrWsb/IMG-2387.jpg](https://i.ibb.co/dgXrWsb/IMG-2387.jpg)

My connection url:

DATABASE_URL="mongodb+srv://<user>:<pass>@serverlessinstance0.mongodb.net/<dbName>"

### Expected behavior

Connection shouldn't be closed even though no one request any query. At least they shouldn't see a error page.

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma: 3.13.0

@prisma/client: 3.13.0
```

**Comment by Weakky** [comment]
Hey @casperibo,

Would you mind sharing a simple query and the Prisma Schema used on the MongoDB instance you shared so that we could reproduce your bug?

Thank you 🙏

**Comment by casperibo** [comment]
Hi @Weakky 

This is the example query with pagination:

`const [totalCount, items] = await Promise.all([
          ctx.prisma.recipe.count({
            where: { isPublished: 1 },
          }),
          ctx.prisma.recipe.findMany({
            take: first,
            skip: offset,
            where: { isPublished: 1 },
            orderBy: { createdAt: "desc" },
          }),
        ]);

        return connectionFromArraySlice(
          items,
          { first, after },
          { sliceStart: offset, arrayLength: totalCount }
        );`

This is the example schema:

`model Recipe {
  id          String         @id @default(auto()) @map("_id") @db.ObjectId
  name        String
  slug        String         @unique
  description String
  cuisine     String
  image       String
  serving     String?        @default("0")
  prepTime    String?        @default("0")
  youtubeURL  String?
  content     String
  isPublished Int            @default(0)
  updatedAt   DateTime       @updatedAt
  createdAt   DateTime       @default(now())
}`

**Comment by pantharshit00** [comment]
Hey, can you please try again with a new mongo shard and latest version of Prisma. The problem seems here to be with timeouts and I wasn't able to reproduce with my attempt.

**Comment by IRediTOTO** [comment]
Look like I get this error too. Mine error appears when I update a row, after ~5 minutes, I query again, this error show in console log. Only MongoDB I think, Postgres has no error.
```
 PrismaClientUnknownRequestError: 
Invalid `prisma.page.update()` invocation:
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "An existing connection was forcibly closed by the remote host. (os error 10054)" } })
  clientVersion: '4.2.1'
}
```
I use mongo Atlas

**Comment by janpio** [comment]
@casperibo Did you try with the newer versions as @pantharshit00 suggested?

@IRediTOTO How do we reproduce this? Can you share the schema and query that we need to be able to look at this? Thanks.

**Comment by IRediTOTO** [comment]
> @casperibo Did you try with the newer versions as @pantharshit00 suggested?
> 
> 
> 
> @IRediTOTO How do we reproduce this? Can you share the schema and query that we need to be able to look at this? Thanks.

No i turn back to Postgres

**Comment by dikyarga** [comment]
hey @casperibo,  I also experience this issue while using Prisma 3 (3.15.2 precisely), also using MongoDB Atlas

I just upgraded it to the latest version (4.3.1), which seems to resolve the issue 🤞

**Comment by casperibo** [comment]
Hi @dikyarga Do you use MongoDB Atlas Serverless Instance?

I was using MongoDB Atlas Serverless Instance while I'm having this issuee. After I changed my instance, my problem solved too.

I didn't try to upgrade the Prisma because MongoDB Atlas Serverless Instances charged me too much money for using it.

I don't think to use Serverless Instances until I figure it out how I build Serverless Instances friendly queries.

**Comment by dikyarga** [comment]
Sorry @casperibo 

I was jumping to the conclusion too fast. It turns out the issue persists but takes a little longer to occur.

Yes, I also use a Serverless instance.

Oh, that was the issue. BRB changed it to the standard instance. 

Thank you so much @casperibo!

**Comment by janpio** [comment]
Might it be that the serverless instance takes to long to come back for the queries to properly be answered?
Can you help us to get to a reproduction of this easily? I think we would still like to understand this - maybe we can improve the behavior here.

**Comment by ItsJohnTheDeveloper** [comment]
I'm getting a `FUNCTION_INVOCATION_TIMEOUT` error in the serverless function deployed on Vercel. 
Long story short I'm fetching data using prisma client inside `getServerSideProps` 

**code block** 
```jsx
import prisma from "../prisma";

export const getServerSideProps = async ({ params }) => {
  const artist: ArtistDocument = await prisma.user.findUnique({
    where: { id: params.artist_id },
  });
  return {
    props: {
      data: {
        artist
      },
    },
  };
};
```

```js
// prisma.ts
import { PrismaClient } from "@prisma/client";

// add prisma to the NodeJS global type
type CustomGlobal = Global & {
  prisma: PrismaClient;
};

// Prevent multiple instances of Prisma Client in development
declare const global: CustomGlobal;
const prisma =
  global.prisma ||
  new PrismaClient({ log: ["query", "info", "warn", "error"] });

// re-use existing prisma client on consecutive hot reloads
if (process.env.NODE_ENV === "development") {
  global.prisma = prisma;
  console.log("Using cached connection.");
}

export default prisma;
```


A temporary workaround solution I found was to just query the data via client side, hitting a nextjs api endpoint I created (which 
just uses prisma).

_*please note this works fine in a LOCAL environment, but NOT in a SERVERLESS environment._

### Environment & setup
node 16
- package.json
"@next-auth/prisma-adapter": "^1.0.3",
"@prisma/client": "^3.13.0",
"prisma": "^3.13.0",
"mongodb": "^4.6.0",
"next": "12.0.10",
"next-auth": "^4.3.3",
"react": "17.0.2",

![Screenshot from 2022-10-22 18-36-39](https://user-images.githubusercontent.com/40045461/197368981-fc522b0e-cc2c-4c69-b3e0-ec0a718b5551.png)

log error from vercel (don't mind the test data uri lol)
![Screenshot from 2022-10-22 18-40-00](https://user-images.githubusercontent.com/40045461/197369062-e5cdd8b9-9f57-4de2-9d34-6521587d4b8c.png)

If anybodys got any ideas, lemme know :sunglasses:

**Comment by janpio** [comment]
The query you are trying to execute probably just takes longer than these 10s (including the creation of the database connection). I suggest you open a new discussion in this repository so we can discuss this and ask all teh questions - in an existing and closed issue that is not really appropriate as it notifies all the previous participants of the discussion on each comment.

**Comment by permlap-phola** [comment]
@janpio  
Hi Just to inform you that this problem is still showing up on "@prisma/client": "^5.14.0"
I got the same error saying 
```
PrismaClientKnownRequestError:
Invalid `this.prisma.user.findUnique()` invocation in
D:\Coding\TLO\server-tlo\src\auth\auth.repository.ts:63:43

  60
  61 async FindUserByEmail(input: InputFindUserByEmail): Promise<User> {
  62   try {
→ 63     const user = await this.prisma.user.findUnique(
Raw query failed. Code: `unknown`. Message: `Kind: I/O error: An existing connection was forcibly closed by the remote host. (os error 10054), labels: {}`
    at In.handleRequestError (D:\Coding\TLO\server-tlo\node_modules\@prisma\client\runtime\library.js:122:6877)      
    at In.handleAndLogRequestError (D:\Coding\TLO\server-tlo\node_modules\@prisma\client\runtime\library.js:122:6211)    at In.request (D:\Coding\TLO\server-tlo\node_modules\@prisma\client\runtime\library.js:122:5919)
    at l (D:\Coding\TLO\server-tlo\node_modules\@prisma\client\runtime\library.js:127:11167)
    at AuthRepository.FindUserByEmail (D:\Coding\TLO\server-tlo\src\auth\auth.repository.ts:63:20)
    at AuthService.SignIn (D:\Coding\TLO\server-tlo\src\auth\auth.service.ts:71:20)
    at D:\Coding\TLO\server-tlo\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at D:\Coding\TLO\server-tlo\node_modules\@nestjs\core\router\router-proxy.js:9:17
```

I use mongodb serverless hosting on mongodb Atlas.

**Comment by janpio** [comment]
@permlap-phola That sounds like a MongoDB Atlas side problem with them closing a connection. If this happens regularly and you have a reproduction, please open a new bug issue. Thanks!
