### ISSUE TITLE
Timed out fetching a new connection from the connection pool

### ISSUE THREAD

**Issue by nilkothari** [prisma/prisma#13353]
I am continuously facing below error while trying to run any query:
```
Invalid `prisma.user.findFirst()` invocation:


  Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 300)] {
  locations: [ { line: 1, column: 34 } ],
  path: [ 'login' ],
  extensions: { code: 'CUSTOM_ERROR' }
}
```

Below is the status of database matrix. There is not more than 15 active connection and CPU, memory are also in control.

![image](https://user-images.githubusercontent.com/78466812/168244748-6391137e-43d1-4ea1-831b-f3595550bd88.png)

From separate project with, querying same database, and it's working fine.

Database: PostgreSQL v12
Node.js version: v14.17.0
@prisma/client: 3.8.1
prisma: 3.8.1

Looks running prisma client instance rejecting requests, is there a way we can prevent this kind of scenario?

**Comment by janpio** [comment]
You should start by updating to a more recent Prisma version. We fixed a few things in the connection pool recently.

If you are still getting the error afterwards, what happens when you increase the pool timeout to a much higer value?

**Comment by garrensmith** [comment]
Hi @nilkothari we have made a lot of fixes to the connection pool to solve this. Could you upgrade to the latest version of Prisma and see if you still getting this issue. Could you also look at what hard limits your database has around connections.

I'm closing this. Please open this again if you still getting this issue.

**Comment by nilkothari** [comment]
As of now not facing issue after upgrading to prisma version 3.14.0
