### ISSUE TITLE
PANIC: no entry found for key in query-engine/prisma-models/src/record.rs:67:33

### ISSUE THREAD

**Issue by wiput1999** [prisma/prisma#13354]
### Bug description

```
Invalid `prisma.product.findFirst()` invocation:


  PANIC: no entry found for key in query-engine/prisma-models/src/record.rs:67:33

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

When query data from database at runtime

### How to reproduce

It's happen randomly to resolve I've to redeploy layer that contain Prisma engine

### Prisma information

Prisma query happen randomly

### Environment & setup

- OS: Linux on AWS Lambda
- Database: PostgreSQL
- Node.js version: 14 on Lambda

### Prisma Version

```
3.13.0
```

**Comment by janpio** [comment]
Can give us any additional information? What does the `product` model in the schema look like? Is there any weird data in the database?

**Comment by annibuliful** [comment]
Data Model

```
model Product {
  id                                           String                                        @id @default(uuid())
  shopId                                       String
  brandId                                      String?
  brand                                        ProductBrand?                                 @relation(fields: [brandId], references: [id])
  type                                         ProductType                                   @default(STOCK)
  internalId                                   String?
  accountingId                                 String?
  sku                                          String?
  titleId                                      String?                                       @unique
  title                                        Translation?                                  @relation(name: "Product.title", fields: [titleId], references: [id])
  descriptionId                                String?                                       @unique
  description                                  Translation?                                  @relation(name: "Product.description", fields: [descriptionId], references: [id])
  slugId                                       String?                                       @unique
  slug                                         Translation?                                  @relation(name: "Product.slug", fields: [slugId], references: [id])
  weight                                       Float?
  weightUnit                                   WeightUnit?
  availableFrom                                DateTime?
  productMedia                                 ProductMedia[]
  options                                      ProductOption[]
  optionValues                                 ProductOptionValue[]
  variants                                     ProductVariant[]
  productCollection                            ProductToCollection[]
  requestQuotationEnabled                      Boolean                                       @default(false)
  bulkOrderEnabled                             Boolean                                       @default(false)
  measurements                                 ProductMeasurement[]
  createdAt                                    DateTime                                      @default(now())
  updatedAt                                    DateTime                                      @updatedAt
  createdBy                                    String
  updatedBy                                    String
  deletedAt                                    DateTime?
  childProducts                                Product[]                                     @relation(name: "ProductToPackage", references: [id])
  parentProducts                               Product[]                                     @relation(name: "ProductToPackage", references: [id])
  salesChannelProducts                         SalesChannelProduct[]
  salesChannelProductPackages                  SalesChannelProductPackage[]
  productAttributes                            ProductAttribute[]
  inventory                                    ProductInventory[]
  productImagePlaceholderPositionAndDimensions ProductImagePlaceholderPositionAndDimension[]
  lastExportedCustomImage                      DateTime?
  meta                                         Json?
  salesChannelProductVariants                  SalesChannelProductVariant[]

  @@unique([id, shopId])
  @@index([brandId])
}
```

As I checked on Our DB, There is no any weird data.

For the time being, it seems work after we re-install prisma layer to AWS lambda function.

**Comment by annibuliful** [comment]
This is the simple query
```
this.db.product.findFirst({
      where: {
        id,
        shopId,
        deletedAt: null,
      },
    })
```

**Comment by wiput1999** [comment]
@janpio @annibuliful Added data model

**Comment by wiput1999** [comment]
@janpio @Weakky I have a question about this issue. Is it possible this error may cause by the pagination cursor?

**Comment by janpio** [comment]
Everything is possible - only when we looked at it in more detail we can potentially say more. Add as much information as you have available to make it as easy as possible for us to reproduce. Thanks.

**Comment by wiput1999** [comment]
@janpio Sure I'll try to collect more information and reproduce step if it happens again.

**Comment by wiput1999** [comment]
I've found I think it's a root clause `variants` relation that has ~7800 records inside of it. Not sure that can clause this issue to happen.

**Comment by Weakky** [comment]
Hey @wiput1999,

I'm unfortunately unable to reproduce your issue. Given where it panics it looks like it's related to some ordering, which might indeed be implicitly added because of some cursor pagination.

Your client snippet doesn't have such pagination though. Are you sure it is _this_ query that triggers the panic?

**Comment by wiput1999** [comment]
Hi @Weakky ,

Thank you for following up on this issue. It never happened again since that day not sure why. Other things come to my mind I would like to ask. Is it possible that AWS Lambda running out of memory on runtime can cause this?

**Comment by Weakky** [comment]
> Is it possible that AWS Lambda running out of memory on runtime can cause this?
This seems very very unlikely. You'd most likely get an OS error or something else if that was the case, not a user-created rust panic.

The panic happens because the QE tries to order by (in-memory) a field that does not exist. Given that we have no other issue with that panic and that you unfortunately can't reproduce it either, I'm gonna close your issue for now since there's not much more we can do.

If it ever happens again, please re-open that issue and let us know as much as you can.

Thanks for reporting 🙏
