### ISSUE TITLE
`upsert` returns `{ count: n }` on update

### ISSUE THREAD

**Issue by mermail** [prisma/prisma#13373]
### Bug description

`upsert` returns `{ count: n }` on update. Otherwise returns the created model (as expected).

**What is expected:** The call to `upsert` returns a model regardless of whether i it was created or updated.

### How to reproduce

```prisma
datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL_MYSQL")
  referentialIntegrity = "prisma"
}

model Thing {
  id         String   @id
  name    String?
}
```

```
yarn prisma generate
```

```js
(async () => {
  const thing = { id: "one", name: "Thing" };
  console.log(await prisma.thing.upsert({
    where: { id: "one" },
    update: thing,
    create: thing,
  }))
})()
```

The first time, when the model is created, the model will be returned. The second time, when updated, `{ count: 1 }` will be returned.

### Expected behavior

The model is returned for both update and create.

### Prisma information

Prisma 3.14.0. 
Using mysql.)

### Environment & setup

- OS: macos
- Database: mysql
- Node.js version: v16.13.2

### Prisma Version

```
3.14.0
```

**Comment by mermail** [comment]
My suspicion is that this has something to do with using mysql, as i've never run into this before. Checking the docs [here](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#upsert) it seems the expected behavior is as described above.

![CleanShot 2022-05-14 at 22 20 32@2x](https://user-images.githubusercontent.com/104778874/168454439-05f2c511-3d43-49ea-a407-61e5128f36c0.jpg)

**Comment by par6n** [comment]
Most probably an issue with your MySQL server. I couldn't reproduce this issue on MySQL v8. Maybe sharing which version of MySQL you're using helps?

<img width="502" alt="CleanShot 2022-05-15 at 15 44 19" src="https://user-images.githubusercontent.com/2109385/168476046-880178e5-01a2-4307-8227-937089f3eb34.png">

**Comment by mermail** [comment]
```
+-----------------------------------+------------------------------------------+
| Variable_name                     | Value                                    |
+-----------------------------------+------------------------------------------+
| innodb_version                    | 10.7.3                                   |
| protocol_version                  | 10                                       |
| slave_type_conversions            |                                          |
| system_versioning_alter_history   | ERROR                                    |
| system_versioning_asof            | DEFAULT                                  |
| tls_version                       | TLSv1.1,TLSv1.2,TLSv1.3                  |
| version                           | 10.7.3-MariaDB-1:10.7.3+maria~focal      |
| version_comment                   | mariadb.org binary distribution          |
| version_compile_machine           | aarch64                                  |
| version_compile_os                | debian-linux-gnu                         |
+-----------------------------------+------------------------------------------+
```

Thanks @par6n for the response. I'm running `mariadb`, which could potentially be an issue. I think of it as a drop-in replacement for mysql, but maybe there's something going on there. I'll try with a mysql image and see if the behavior changes.

**Comment by mermail** [comment]
```
+--------------------------+------------------------------+
| Variable_name            | Value                        |
+--------------------------+------------------------------+
| admin_tls_version        | TLSv1.2,TLSv1.3              |
| immediate_server_version | 999999                       |
| innodb_version           | 8.0.29                       |
| original_server_version  | 999999                       |
| protocol_version         | 10                           |
| replica_type_conversions |                              |
| slave_type_conversions   |                              |
| tls_version              | TLSv1.2,TLSv1.3              |
| version                  | 8.0.29                       |
| version_comment          | MySQL Community Server - GPL |
| version_compile_machine  | aarch64                      |
| version_compile_os       | Linux                        |
| version_compile_zlib     | 1.2.11                       |
+--------------------------+------------------------------+
```

Hm, that seems to have worked. Thank you for the suggestion @par6n .

As a note to anyone who stumbles upon this in the future, mariadb seems to be incompatible with prisma. However, it works _almost_ perfectly so this is not obvious.

---

What initially lead to this was trying to get a local db set up on m1 mac. The usual move (for postgres) would be docker compose. however the default mysql image doesn't work (as of this writing), so somewhere it was suggested to use mariadb instead. mysql does work with a different tag though.

In case it helps anyone else out:

```yaml
version: "3.9"

services:
  mysql:
    image: mysql:8.0-oracle
    ports:
      - "3306:3306"
    volumes:
      - db_data_mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test

volumes:
  db_data_mysql:
```
