### ISSUE TITLE
(An error occurred during DNS resolution: io error: Error parsing resolv.conf: ProtoError { kind: Msg("Malformed label: --") })

### ISSUE THREAD

**Issue by ihsankl** [prisma/prisma#13370]
### Bug description

I tried to connect do my atlas mongodb with quickstart guide provided by prisma documentation. But I can't get it working. Instead, I received the following message:

![image](https://user-images.githubusercontent.com/55323174/168404339-1dd22422-e80b-40b5-b6a0-18679f53f912.png)

### How to reproduce

1. Set .ENV DATABASE_URL="mongodb+srv://xxxx:xxxx@asuransi-kebakaran.wtor9.mongodb.net/myFirstDatabase?retryWrites=true&w=majority&ssl=true"
2. Run npx prisma generate
3. yarn start:dev

### Expected behavior

I can connect to my atlas mongodb

### Prisma information

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Users {
  id       String @id @default(auto()) @map("_id") @db.ObjectId
  name     String
  email    String
  password String
}
```

### Environment & setup

- OS: Manjaro Linux x86_64
- Database: mongodb
- Node.js version: v17.3.0

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0

```

**Comment by antiergit** [comment]
Were you able to solve this?

**Comment by janpio** [comment]
Any idea how we can reproduce this? We have tests running with MongoDB at Atlas, and that runs with no problems at all. Any idea what could be different between our systems?

**Comment by unalterable** [comment]
I have the same error.
I found a line `search --` in my `/etc/resolv.conf` file on my machine (ubuntu).
I tried everything to change the file automatically (because there is a warning in the file not to change it manually). However - eventually i commented out the line and prisma seemed fine again. All is fixed.

I have no idea why prisma is affected by this file - i have no idea why nothing else on my laptop has problems (only prisma) - but that's what worked for me.

my resolv.conf file:
```sh
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 127.0.0.53
# search --
options edns0 trust-ad
```

**Comment by janpio** [comment]
Context I did not know before:
> resolv.conf is the name of a computer file used in various operating systems to configure the system's Domain Name System resolver. The file is a plain-text file usually created by the network administrator or by applications that manage the configuration tasks of the system. (via Wikipedia)

Prisma itself certainly does not read that file, but it might be that the MongoDB driver somehow is confused by this in some way.

@unalterable @antiergit You are also all experiencing this with a MongoDB connection? With `mongodb+srv` in the connection string?

**Comment by unalterable** [comment]
yes - `+srv` is in the connection string.
It's worth noting that i have many applications using the same DB running locally and on other machines. 3 are node applications using the basic mongodb library or mongoose. Only the application using Prisma has this problem - and nothing fixes it except altering `resolv.conf` as above (which works every time). So while Prisma may not read the file directly - it certainly alters its behaviour based on its contents - and other mongodb libraries do not.

**Comment by ihsankl** [comment]
> Were you able to solve this?

Im sorry I didn't use prisma since this occur. I will try it again with same environtment ASAP.

**Comment by janpio** [comment]
We can probably try to reproduce this on Ubuntu, with such a `/etc/resolv.conf` file, talking to a MongoDB Atlas server with `mongodb+srv://` connection string. It might be that the MongoDB driver is reading that file under the hood and doing wrong things.

**Comment by Lagrafabdessalem** [comment]
> 

I can't edit it , it shows to me that Could not save the file /etc/resolv.conf and Unexpected error: Error opening file “/etc/resolv.conf”: Too many levels of symbolic links , How I fix it ?

**Comment by Lagrafabdessalem** [comment]
> I have the same error. I found a line `search --` in my `/etc/resolv.conf` file on my machine (ubuntu). I tried everything to change the file automatically (because there is a warning in the file not to change it manually). However - eventually i commented out the line and prisma seemed fine again. All is fixed.
> 
> I have no idea why prisma is affected by this file - i have no idea why nothing else on my laptop has problems (only prisma) - but that's what worked for me.
> 
> my resolv.conf file:
> 
> ```shell
> # Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
> #     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
> # 127.0.0.53 is the systemd-resolved stub resolver.
> # run "systemd-resolve --status" to see details about the actual nameservers.
> 
> nameserver 127.0.0.53
> # search --
> options edns0 trust-ad
> ```

I can't edit it , it shows to me that Could not save the file /etc/resolv.conf and Unexpected error: Error opening file “/etc/resolv.conf”: Too many levels of symbolic links , How I fix it ?

**Comment by thathurtabit** [comment]
I'm having the same problem connecting `Prisma` to `MongoDB` when in a shared cluster (everything works fine when running `docker-compose up --build` - i.e. it must have access to `resolv.conf` when not in the cluster).

My error:

```
Error retrieving acronyms: Error: 
Invalid `prisma.mydata.findMany()` invocation:


Error in connector: Error creating a database connection. (An error occurred during DNS resolution: io error: Error parsing resolv.conf: InvalidOption(2))
```
