### ISSUE TITLE
Running DB Pull on Remote MSSQL database

### ISSUE THREAD

**Issue by mentallabyrinth** [prisma/prisma#13372]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v16.13.1           | 
| Prisma CLI  | 3.14.0             | 
| Engine      | 2b0c12756921c891fec4f68d9444e18c7d5d4a6a| 

## Error
```
Error: [/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tiberius-0.9.0/src/client/tls_stream/rustls_tls_stream.rs:192:62] could not load platform certs: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }
```

**Comment by janpio** [comment]
This should be fixed in the next release 3.15.0 next Tuesday, or in `prisma@dev` right now. Can you please test with those versions again @mentallabyrinth and let us know if the problem is indeed fixed? Thanks.
