### ISSUE TITLE
Client should contain `Enum` even if not used by a model

### ISSUE THREAD

**Issue by okomarov** [prisma/prisma#13382]
### Bug description

Enum declared in the `prisma.schema`, but not used for any model field, is created in the migration but not in the client `index.d.ts`.

I want to use the `prisma.schema` as the source of truth and map my GraphQL codegen config to point to the generated Prisma enums.

### How to reproduce (all in https://github.com/okomarov/prisma)

Clone this [repo](https://github.com/okomarov/prisma), cd to the `/enum_not_generated` and then run:

```bash
docker compose up -d
```
after that you create a migration:

```bash
yarn prisma migrate dev -n 'Add enum'
```
and verify that it contains:

```sql
-- CreateEnum
CREATE TYPE "Color" AS ENUM ('RED', 'BLUE');
```

So it correctly detects the enum. Then generate the Prisma client:

```bash
yarn prisma generate
```
and check that `prisma/output/index.d.ts` does **NOT** contain:

```js
export const Color: {
  RED: 'RED',
  BLUE: 'BLUE'
};
```

This 'enum' will be added if we add it e.g. to our `Dummy` model like so:

```
model Dummy {
  id    String @id @db.Uuid
  color Color
}
```

### Expected behavior

Prisma generates the enum in the client's `index.d.ts` regardless wether it's used by a model.

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  output   = "./output"
}

datasource db {
  provider = "postgresql"
  url      = env("DB_URL")
}

model Dummy {
  id String @id @db.Uuid
}

enum Color {
  RED
  BLUE
}
```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL 14
- Node.js version: v16.14.0

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by okomarov** [comment]
> Can you shed some light on why you want this in your Prisma Schema?

From above "I want to use the prisma.schema as the source of truth and map my GraphQL codegen config to point to the generated Prisma enums." 

Effectively this lets me avoid casting database enums to graphql enums even in the case when they are exactly the same (Typescript issue). So, starting from this simplified codegen.yml (note the `enumValues` mapping):
```
overwrite: true
schema: http://localhost:3000/graphql
documents: null
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      enumValues:
        AssetType: ../../node_modules/.prisma/client/index#AssetType
```

This will generate an import at the top of `api/src/generated/graphql.ts`
```
import { AssetType } from '../../node_modules/.prisma/client/index';
...
```

Without the explicit mapping of the graphql enum value to the prisma one, it would create its own const (or enum, can't quite remember), and returning the prisma enum will error in typescript as it can't reconcile it with the graphql enum.

By pointing the AssetType to the one generated by prisma, I'll avoid casting. For example if my schema and resolvers are:
```
import AssetType from Prisma

{
  schema: `
    enum AssetType {
      A
      B
    }
    type Query {
      dummy: AssetType
  }
  `,

  resolvers: {
    Query: {
      dummy: ()=> AssetType.A  <- Typescript won't complain as the generated GraphQL enum maps directly to the Prisma one
  }
}
```

Now, without the mapping I would need to do dummy: `()=> AssetType.A as GqlAssetType`

Hope this clarifies. Ultimately, it's an edge case but it felt like it would not harm to drive db models from the schema and hence I expected it to create what I declare in the schema.

**Comment by oyed** [comment]
Mentioned this on the Prisma Slack, but I'd also like this for the same reason - especially in a monorepo, having enums defined in two different services can be difficult to maintain when they eventually get used via code generation (for GraphQL in my own case)

**Comment by abhay44** [comment]
Any update on this issue? 
In my case, I added the user roles enums(superadmin, admin, member etc..) to the database. But since the roles are present in meta rather than a specific field, client didn't pickup the enums and finally I landed on this issue. I can add these at a outer layer instead of importing from prisma client but I think more sophisticated approach would be from importing prisma client itself.

**Comment by rajivkr** [comment]
Any update on this? We are having JSON field as metadata, that uses values from ENUM in prisma model. Looking for ways to have this enums generated in such usecases.

**Comment by kleydon** [comment]
It is DEFINITELY useful to have enums that aren't included in models.

For example: Say you want an enum consisting of error codes to be defined in `schema.prisma` as your single source of truth, but accessible to your (generated) graphql schema, and in your javascript/typescript (server and client). You probably wouldn't want a particular error code to be included in any particular model, but you _would_ want the error code enum NOT to be silently removed simply because it happens not to be in any model.

**Comment by capaj** [comment]
I second this issue. Generating all enums should be easier than the dead code elimination that the generator is doing now.

**Comment by cellulosa** [comment]
Second this. I keep a single "source of truth" for enums, few of which are not directly used by Prisma, so would be good to have Prisma to keep all those typed in schema.prisma.

**Comment by dmasters19** [comment]
> Any update on this? We are having JSON field as metadata, that uses values from ENUM in prisma model. Looking for ways to have this enums generated in such usecases.

Same use case here

**Comment by cidylle** [comment]
Still no updates on this ?

**Comment by paolomatti01** [comment]
I would need this as well, any updates?

**Comment by drakedeatonuk** [comment]
Keen to see this too

**Comment by tjalil** [comment]
Just wrangled with this for a couple of hours before recognizing the pattern in my schema (not used in model -> not defined in generated prisma client), and now confirming with this thread. As mentioned above, my prisma.schema is my single source of truth for the db. It's very inconvenient, and unsafe, to maintain separate schemas at various layers.

**Comment by sejori** [comment]
Also want this... now I have to make a useless table just to store the enum in generated client... not ideal!

**Comment by rajczi** [comment]
We created a custom generator that takes in the model and outputs the "skipped" enum to the client.  Super hacky, but gets the job done.  I'd far prefer an "includeAllEnums" option on the prisma client generator so it would output them by default.

**Comment by nlsteers** [comment]
also came here looking for this, +1 to this feature request

**Comment by rajczi** [comment]
@nlsteers We ended up creating a custom generator that appended the missing types to the generated file for us.  It works well for now.

**Comment by daleobrien** [comment]
+1

**Comment by joelrb** [comment]
I need this too at the moment! I already have 10 enums in the Prisma schema but I need another two but won't be used by any table. For the same reason as the above, it's unnecessary to create another file (or add them somewhere in another file) just for the two enums to be reusable. Thanks!

**Comment by ColdDev** [comment]
I don't see why this would be something that's so bad to add - this would be a neat feature for a current project of mine, and would extra variables in my code to define these enums.

**Comment by Nagyman** [comment]
I similarly just discovered this issue after too much time troubleshooting about _why_ a declared enum was not available for import & use.

IMO, the principle of least surprise is at play here. Something is _explicitly_ defined using the framework and is recognized by Prisma to create the type in the DB, yet remains unavailable (presumably for performance reasons?).

Models don't have to be used to be created, but regardless of specific use cases to justify a change here, time might be saved for users by:

* documenting this exception (probably in [Defining Enums](https://www.prisma.io/docs/orm/prisma-schema/data-model/models#defining-enums))
* maybe output some warning that an unreferenced enum (in schemas) is being omitted \<because\>
* maybe don't generate the migration if it won't be available anyway

On my end, a temporary table will be used in the meantime, so at least there's a workaround.

Thanks!

**Comment by jkomyno** [comment]
Hey there, Prisma 6 is out: https://github.com/prisma/prisma/releases/tag/6.0.0!
It includes a fix to this issue.
