### ISSUE TITLE
upsert error when undefined field

### ISSUE THREAD

**Issue by charismanapriandi** [prisma/prisma#13385]
### Bug description

`prisma[table].upsert()` error when receive undefined value, example: 

```
prisma.post.upsert({
  where: {id},
  create: {name: 'john', age: 20},
  update: {name: 'jean', age: undefined} // will error
}) 
```

### How to reproduce

```
{,…}
error: {clientVersion: "3.13.0"}
message: "something went wrong - Error: 
Invalid `prisma.skill.upsert()` invocation:

{ 
 where: {
    id: 'cl3882yhh0115llgqp44yzt9f'
  },
  update: {
    imagePath: '/public/uploads/',
    imageName: undefined,
    name: 'Reed Daniel',
    url: 'https://www.duhoxykitobef.ws'
  },
  create: {
    imagePath: '/public/uploads/',
+   imageName: String,
    name: 'Reed Daniel',
    url: 'https://www.duhoxykitobef.ws',
    userId: 'cl37fhaqa1208vq3ttucls59v',
?   id?: String
  }
}

Argument imageName for create.imageName is missing.

Note: Lines with + are required, lines with ? are optional.
"
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v16.13.2

### Prisma Version

```
"prisma": "^3.13.0"
```

**Comment by okomarov** [comment]
The error is not about the undefined but is saying:

`Argument imageName for create.imageName is missing`

**Comment by janpio** [comment]
The `imageName` seems to be required, but is missing in the `create` - so it can not create the entry.

**Comment by charismanapriandi** [comment]
sorry, I got this. imageName field is required on my schema but got undefined when inserting data. 

and how about this? 
"Argument where of type SkillWhereUniqueInput needs at least one argument. Available args are listed in green.\n\nNote: Lines with ? are optional.\n"
I got the error when "where": undefined in upsert()

**Comment by charismanapriandi** [comment]
where: {
    id: !isUndefined(skillId) ? skillId as string : '-1',
 },

**Comment by janpio** [comment]
Are you suggesting to change the error message to make it easier to detect?

**Comment by janpio** [comment]
Ping @charismanapriandi - What error exactly did you get when although it was unexpected?

**Comment by janpio** [comment]
Closing this then, as from our perspective things are behaving as expected in both cases (missing required field in `create`, and whole where being `undefined`).
