### ISSUE TITLE
Add support for Persisted Queries

### ISSUE THREAD

**Issue by jvbianchi** [prisma/prisma#134]
This could help with performance and maybe security.

**Comment by marktani** [comment]
Thanks for the suggestion :slightly_smiling_face:

**Comment by jvbianchi** [comment]
as a example here is [how scaphold does it](https://docs.scaphold.io/persisted-queries/)

**Comment by kbrandwijk** [comment]
+1 for the suggestion for using `persistgraphql` (like Sc**h**d)

**Comment by sorenbs** [comment]
Apollo blog for reference: https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5

There are two ways to expose this functionality:

1. Use a tool like `persistgraphql` to generate a mapping file that can be added to the Graphcool project definition
2. Present a UI in the console listing all queries executed against the project and enable downloading a mapping of select queries

To me the two biggest benefits of persisted queries are:

1. Ability to lock down project to just the pre-approved persisted queries
2. Enabling network-level caching of specific queries

**Comment by johhansantana** [comment]
Allowing persistent queries would also help teams where the backend team focus on creating specific graphql query endpoints and the frontend team just query those without having them to recreate the queries each time.

Is this still being worked on? Does the `persistgraphql` tool works with graph.cool?

**Comment by raderio** [comment]
https://twitter.com/leeb/status/829434814402945026

**Comment by kbrandwijk** [comment]
Sorry, but I have to say this: I believe persisted queries are a huge anti-pattern, as they basically turn your flexible GraphQL api into an old REST-like api, by defining the queries on the server, and just sending over a query id or name. I strongly dislike the entire concept.

**Comment by schickling** [comment]
Persisted queries will be possible using the [new GraphQL gateway pattern](https://github.com/graphcool/framework/issues/1314). (There's an [open issue](https://github.com/graphcool/graphql-gateway-example/issues/5) to add an example for persisted queries.)

**Comment by johhansantana** [comment]
@kbrandwijk it's just a way to set up business logic, so you don't have to tell the different teams to create the query over and over again when you can just do it once, test it once and be done with it.

**Comment by raderio** [comment]
@kbrandwijk 
Dev mode. The GQL API is completely open. The front end dev creates the queries they needs in the dev environment.
    Once the app version/feature is finished, the queries are considered finalized and the API is locked. At that point, the queries are persisted and the app is moved to production, where the production GQL API looks up the persisted queries.

**Comment by raderio** [comment]
https://dev-blog.apollodata.com/improve-graphql-performance-with-automatic-persisted-queries-c31d27b8e6ea
