### ISSUE TITLE
Generated types are missing `$transaction<R>(fn: (prisma: PrismaClient) => R): R` signature

### ISSUE THREAD

**Issue by zdila** [prisma/prisma#13408]
### Bug description

Generated types are missing `$transaction<R>(fn: (prisma: PrismaClient) => R): R` typescript signature

### How to reproduce

this doesn't compile:
```
    await prisma.$transaction(async (prisma: PrismaClient) => {
      // ...
    });
```

### Expected behavior

it should compile

### Environment & setup

- OS: Debian
- Database: MariaDB
- Node.js version: v16.14.0

### Prisma Version

```
3.14.0
```

**Comment by Valerionn** [comment]
Do you have the `interactiveTransactions` preview feature enabled? (see #12867)

**Comment by zdila** [comment]
@Valerionn thank you, after enabling it the type appeared. Sorry for invalid bug-report.
