### ISSUE TITLE
prisma generate doesn't create client in default location

### ISSUE THREAD

**Issue by tombohub** [prisma/prisma#13413]
### Bug description

Following tutorial at the step `npx prisma generate` client doesn't appear at the default `.prisma/client` location.

Only if I specify in prisma.schema:

```
generator client {
  provider = "prisma-client-js"
  output   = "client"
}
```

it generates client.

EDIT: still the new client doesn't intellisense new schema. Still keeps the old user and posts:

![image](https://user-images.githubusercontent.com/3029412/169187185-2e7378cf-5401-44b1-8f35-234b0dbd4505.png)

EDIT2: New client is working after closing and reopening VSCode.

EDIT3: after changing schema and generating client, new client is not imported from `@prisma/client` . I have to import from `./prisma/client` to have new client.

### Environment & setup

- OS: Windows 10
- Database: PostgreSQL
- Node.js version: v16.13.1

### Prisma Version

```
3.12.0
```

**Comment by janpio** [comment]
All new Prisma users are using the default location in `node_modules/.prisma/client` to generate their client, and no one reported this not working so I highly doubt this is generally broken for everyone.

Which tutorial are you following?

**Comment by tombohub** [comment]
Hi, I was following this tutorial on how to add prisma to existing database: https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases-typescript-postgres

**Comment by tombohub** [comment]
@pantharshit00 I only put that because default behavior doesn't work

**Comment by janpio** [comment]
Following that tutorial you should have a newer Prisma version, currently 3.14.0. Can you please try again and see if the error persists if you follow exactly the steps in the tutorial? Thanks.

**Comment by tombohub** [comment]
I have tried again and all is normal. I think it's my mistake. I thought the client is generated in root prisma folder, not in node_modules/.prisma folder. 
Thank you
