### ISSUE TITLE
Error: [libs/sql-schema-describer/src/postgres.rs:1039:28] no entry found for key

### ISSUE THREAD

**Issue by WilliamFalci** [prisma/prisma#13418]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v16.0.0            | 
| Prisma CLI  | 3.14.0             | 
| Engine      | 2b0c12756921c891fec4f68d9444e18c7d5d4a6a| 

## Error
```
Error: [libs/sql-schema-describer/src/postgres.rs:1039:28] no entry found for key
```

**Comment by pantharshit00** [comment]
Sure we can keep this open for now.

**Comment by meotimdihia** [comment]
duplicated with the issue:
https://github.com/prisma/prisma/issues/13352

**Comment by meotimdihia** [comment]
I think we can close this issue: https://github.com/prisma/prisma-engines/pull/2939

**Comment by pantharshit00** [comment]
Thanks @meotimdihia
