### ISSUE TITLE
Improve CLI output when using `db push` with MongoDB

### ISSUE THREAD

**Issue by floelhoeffel** [prisma/prisma#13464]
### Problem
Migrations are not support with MongoDB. What we support is pushing of constraints and indexes via `db push`.

If `db push` is executed, it prompts the following confusing message:

```
🚀  Your database is now in sync with your schema. Done in 889ms
```

Which is actually not true.

### Suggestion
Change message to reflect what is in sync.

**Comment by janpio** [comment]
Suggestion `Indexes were created in your database. Done in ...`
