### ISSUE TITLE
Preview feature feedback: `improvedQueryRaw`

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma#13466]
Please share your feedback about the `improvedQueryRaw` preview feature released in [v3.14.0](https://github.com/prisma/prisma/releases/tag/3.14.0) in this issue.

- If you encounter a bug, please open a bug report in this repo.
- If the feature is working well for you, please share this in a comment below or leave a :+1: on this issue.

If you have any questions, don't hesitate to ask them in the [#product-feedback](https://app.slack.com/client/T0MQBS8JG/C01739JGFCM/thread/C01739JGFCM-1631633975.005200) channel in the [Prisma Slack](https://slack.prisma.io/).

**Comment by chriszrc** [comment]
@Weakky I'm using prisma v4.1.0, and with the following query, I was still getting the dreaded "incorrect binary data format in bind parameter 1":

```
const result = await this.prisma.$queryRaw<ReadTrafficStatsDto>(
      Prisma.sql`
        with buffer as (
          select ST_Buffer(ST_SetSRID(ST_MakePoint(${lng}, ${lat}), 4326)::geography, ${radius})::geometry as geom
        )
        select round(avg(aadt)) as avg_aadt, round(sum(aadt)) as sum_aadt, 
          round(sum(st_length(t.geom::geography))) sum_geom_length from 
        traffic t, buffer b
        where st_intersects(
          t.geom ,
          b.geom
        )
      `)
```

I tried various casting, but it didn't work either. However, I eventually tried using the `${Prisma.Decimal(lat)}` helper around the lat/lng and now I'm not getting the error anymore, but it was not clear to me whether this was to be expected at this point, and if so, where in the docs this usage is documented?

**Comment by zachgoll** [comment]
Using `v4.4.0` and also getting lots of these errors.  Per @chriszrc's solution, it seems that wrapping values in `Prisma.Decimal` fixes the error, but it is unclear to me _why_ this is required and what actually causes this error? 

The error happens sporadically and is not _consistently_ reproducible on our end (same exact input produces an error sometimes and not others).  This error has happened on versions `4.3.1` and `4.4.0` for us, but never in versions prior to those (we were not using the preview version of `improvedQueryRaw`).

**Comment by spaiz** [comment]
Using version 4.13.0
Spent half a day to understand what was going wrong here when I tried to copy data from MongoDB to PostgreSQL.

Minimal reproducible example

field1 is of type DECIMAL(5,2)

```
      const result = await prisma.$executeRaw`
 INSERT INTO t1 (
  field1
) VALUES (
  ${field1}
  )`;
```

I use $executeRaw to insert a NUMBER value (js) to DECIMAL(5,2) PostgreSQL.

Long story short, if your first query has the value of an integer, so prepared statement will be cached, and the next attempt to insert the value of float will fail and you will get

```
Raw query failed. Code: `22P03`. Message: `db error: ERROR: incorrect binary data format in bind parameter 1`
```

<img width="1085" alt="Screenshot 2023-05-01 at 14 47 40" src="https://user-images.githubusercontent.com/5892159/235447711-13ee7e19-6cd2-4ed3-acf9-ab8b0fe9a451.png">

If the first insert query has a float value, the next insert query with either integer or float will work.

<img width="510" alt="Screenshot 2023-05-01 at 14 45 56" src="https://user-images.githubusercontent.com/5892159/235447691-c8aa5d83-23cc-45b0-b5b6-e1077ec87465.png">

This is crazy...

**Comment by janpio** [comment]
This went GA in 4.0.0: https://github.com/prisma/prisma/releases/tag/4.0.0
