### ISSUE TITLE
@ignore on required fields disables create and update operations on model

### ISSUE THREAD

**Issue by jonsandg** [prisma/prisma#13467]
### Bug description

According to docs:

> You can manually add @ignore to a field that you want to exclude from the Prisma Client (for example, a field that you do not want Prisma users to update)

When you set `@ignore` on required fields the client generation does not create the functions for create, update, upsert, etc., for the model. I realize this might be intended behavior. If so the docs could probably use some clarifications on @ignore and I would love some pointers on how to get around the problem.

For context, I'm trying to get prisma working with temporal tables, which requires the table to have two non-nullable datetime fields which are set by the database. If I set the fields to be nullable with a `?` the client generation works as I expect but then prisma migrate will try to change the fields to be nullable. More [here](https://github.com/prisma/prisma/issues/3334#issuecomment-1136051910)

### How to reproduce

```prisma
datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model TestModel {
  id         String  @id @default(uuid())
  name       String
  ignorethis String @ignore
}

```

`npx prisma generate` and run:

```js
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

prisma.testModel
  .create({
    data: { name: 'lala' },
  })
  .then(res => console.log(res));
```

Gives error: `TypeError: prisma.testModel.create is not a function`

### Expected behavior

Be able to use functions like create, createMany, update, etc. on the model

### Environment & setup

- OS: Mac 
- Database: SQL server
- Node.js version: v16.13.2

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by pantharshit00** [comment]
`@ignore` will only disable the create/update operation on required fields so if you add a `?` to the field, it will re-enable the operation. I agree this feature requires some documentation improvement.

**Comment by garrensmith** [comment]
hey @jonsandg thanks for the error report. This is intended behaviour. 

@andrew-walford-prisma could you take a look at this. This is intended behaviour but I think we should improve the docs around this. @Weakky can help with the explanation

**Comment by tombohub** [comment]
I think you should allow @updatedAt field to have @ignore, without losing create etc. functions

**Comment by maxh** [comment]
We've added a rule `forbid-required-ignored-field` to [prisma-lint](https://github.com/loop-payments/prisma-lint) to detect this case:

https://github.com/loop-payments/prisma-lint/blob/main/RULES.md#forbid-required-ignored-field

This helps avoid confusion on our team.
