### ISSUE TITLE
Query engine library for current platform XXX could not be found

### ISSUE THREAD

**Issue by Geebrox** [prisma/prisma#13460]
### Bug description

This issue mostly happens with those users who use Prisma within monorepos. I faced the same problem when using yarn workspaces. I was able to fix the issue by providing external `node_modules` for my webpack config. I am creating this issue to search for or solve this issue on different platforms with different workspaces. I will pin the reproduction commit from one of my repositories and with a solution on how I fixed this issue. I want others to participate and comment on this issue to find out a universal method to solve the issue.

### How to reproduce

1. Clone [this](https://github.com/Geebrox/next-nest-mono) repo
`git clone https://github.com/Geebrox/next-nest-mono.git`
2. Checkout to https://github.com/Geebrox/next-nest-mono/commit/84bd3748518ecbbbf26bfe32a3408756639942c6
`git checkout 84bd3748518ecbbbf26bfe32a3408756639942c6`
3. Install dependencies
`yarn install`
4. Populate `.env`
5. Run dev command
`yarn dev`
6. See the error

### Expected behavior

I was able to solve the issue by adding the `additionalModuleDirs` option for `webpack-node-externals`
1. Checkout to https://github.com/Geebrox/next-nest-mono/commit/5baac0a6121717b8755c577b619d6b6a12d4e358
`git checkout 5baac0a6121717b8755c577b619d6b6a12d4e358`
2. Install dependencies
`yarn install`
3. Populate `.env`
4. Run dev command
`yarn dev`
5. The server should start without the error

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Todo {
  id          String  @id @default(auto()) @map("_id") @db.ObjectId
  title       String
  description String  @default("")
  completed   Boolean

  @@map("todos")
}
```

### Environment & setup

- OS: macOS Monterey v12.3.1
- Database: MongoDB
- Node: v16.13.0
- NPM: v8.1.3
- Yarn: v1.22.17

### Prisma Version

In the provided reproduction steps the version of the Prisma was `3.15.0-integration-fix-inline-schema.5`
I was testing the issue #13052 and changes made by @millsp

**Comment by janpio** [comment]
I can reproduce the problem you describe with your supplied reproduction:

```
...
 SERVER  [Nest] 2010  - 01/28/2023, 12:09:46 AM     LOG [RouterExplorer] Mapped {/api/todos/:id, PATCH} route +1ms
 SERVER  [Nest] 2010  - 01/28/2023, 12:09:46 AM     LOG [RouterExplorer] Mapped {/api/todos/:id, DELETE} route +1ms
 SERVER  [Nest] 2010  - 01/28/2023, 12:09:46 AM   ERROR [Bootstrap] Error: Query engine library for current platform "debian-openssl-1.1.x" could not be found.
 SERVER  You incorrectly pinned it to debian-openssl-1.1.x
 SERVER  
 SERVER  This probably happens, because you built Prisma Client on a different platform.
 SERVER  (Prisma Client looked in "/workspace/next-nest-mono/workspaces/server/dist/libquery_engine-debian-openssl-1.1.x.so.node")
 SERVER  
 SERVER  Searched Locations:
 SERVER  
 SERVER    /workspace/next-nest-mono/.prisma/client
 SERVER    /workspace/next-nest-mono/node_modules/@prisma/client
 SERVER    /workspace/next-nest-mono/workspaces/server
 SERVER    /workspace/next-nest-mono/workspaces/server/prisma
 SERVER    /tmp/prisma-engines
 SERVER    /workspace/next-nest-mono/workspaces/server/dist
 SERVER  
 SERVER  
 SERVER  To solve this problem, add the platform "debian-openssl-1.1.x" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
 SERVER  generator client {
 SERVER    provider      = "prisma-client-js"
 SERVER    binaryTargets = ["native"]
 SERVER  }
 SERVER  
 SERVER  Then run "prisma generate" for your changes to take effect.
 SERVER  Read more about deploying Prisma Client: https://pris.ly/d/client-generator
 ```
 
 This is the (hidden) output of `prisma generate`:
 
 ```
gitpod /workspace/next-nest-mono/workspaces/server ((84bd374...)) $ yarn prisma generate
yarn run v1.22.19
$ /workspace/next-nest-mono/node_modules/.bin/prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (3.15.0-integration-fix-inline-schema.5 | library) to ./../../node_modules/@prisma/client in 53ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
Done in 1.28s.
```

The Client is actually generated into `/node_modules/.prisma/client` which is also loaded and then loads the runtime from `/node_modules/@prisma/client/runtime/index.js`. 

What I _did_ notice in this error message is that it lists the correct path of `@prisma/client` inside `node_modules`, but for `.prisma/client` the `node_modules` is missing. When I edit the code manually to add that, it can find the Query Engine.

**Comment by janpio** [comment]
Note: Checkout to https://github.com/Geebrox/next-nest-mono/commit/84bd3748518ecbbbf26bfe32a3408756639942c6 from the reproduction already uses the Prisma version where the schema is inlined in the Client, so this is _not_ a universal problem that can currently happen with Prisma Client with _this_ error message.

**Comment by janpio** [comment]
This issue can be replaced by https://github.com/prisma/prisma/issues/17630 It does not use the integration version, so shows the _real_ underlying problem of the reproduction.
