### ISSUE TITLE
Cloudflare Workers with PlanetScale db

### ISSUE THREAD

**Issue by konradbjk** [prisma/prisma#13474]
I want to use prisma with Cloudflare workers and PlanetScale db using JS and not TS.

I have created the webpack config
```
module.exports = {
  entry: './src/index.js',
  target: 'webworker',
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
    // Alias for resolving the Prisma Client properly
    alias: {
      '@prisma/client$': require.resolve('@prisma/client'),
    },
  },
  devtool: 'none',
}

```

and schema

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialIntegrity", "dataProxy"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Test {
  id            Int      @id @default(autoincrement())
  name          String
  city          String
  www           String
```

Now it all trows pleny of errors. When I try to use `db push` I get:
```
% npx prisma db push           
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Get config: Schema Parsing P1012

error: Error validating datasource `db`: the URL must start with the protocol `mysql://`.
  -->  schema.prisma:11
   | 
10 |   provider = "mysql"
11 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
```

Next while using wrangler dev I have a ton of lines mostly around missing modules.

What is more there is a missing step of using npx prisma db push.

**Comment by SebJansen** [comment]
`the URL must start with the protocol mysql://`, I think it could be due to either of two reasons:
- Prisma client hasn't been generated with dataproxy, do `PRISMA_CLIENT_ENGINE_TYPE=dataproxy npx prisma generate`. A `mysql://...` connection string only works for non-dataproxy projects, and Cloudflare Workers needs the dataproxy because Workers can only connect through HTTP which requires a connection string resembling `prisma://...`.
- You have a space in your `DATABASE_URL` env var, it has happened often to me.

**Comment by pantharshit00** [comment]
You need to have `PRISMA_CLIENT_ENGINE_TYPE` set to `dataproxy` in order to generate a compatible client which would use data proxy which enables prisma to work with cloudflare workers.

**Comment by konradbjk** [comment]
@pantharshit00 but where do we set it? scheme.prisma

**Comment by pantharshit00** [comment]
It is an environment variable. So you can either do `export PRISMA_CLIENT_ENGINE_TYPE=dataproxy` or prefix you command with `PRISMA_CLIENT_ENGINE_TYPE=dataproxy <your command>`


You can use something like cross-env on windows to make your life easier: https://www.npmjs.com/package/cross-env
