### ISSUE TITLE
Critical Bug: Cannot create a new Prisma database

### ISSUE THREAD

**Issue by Devner-tour-guides-collective** [prisma/prisma#13511]
### Bug description

I made a vite app (from their react-ts template) and wanted to install Prisma into it. I did not modify what was inside that boilerplate. I went through the setup flow on Prisma.io, but encountered this error. The error appeared both on Heroku and PlanetScale. I cannot give you any more information about this bug because the error message I was given is not helpful. I did not do anything special with my setup -- I only followed the instructions on the site, but the Prisma website does not seem to be working.

EDIT: When I set this up, I manually added prisma/prisma.schema to my repo because the UX is telling me my repo needs it. Not sure if this info is helpful or not.

I am considering this a "critical bug" because it prevents the user from useing the software on any level. 

![image](https://user-images.githubusercontent.com/106288660/170514595-51e7df29-201e-4d6b-8242-83a383672945.png)

### How to reproduce

answered above

### Prisma information

do not have time to fill this out

### Environment & setup

do not have time to fill this out

### Prisma Version

do not have time to fill this out

**Comment by pantharshit00** [comment]
Hey @Devner-tour-guides-collective 

Can you please also send a message via intercom on the platform? That would be faster for the support team to respond there.
