### ISSUE TITLE
Using `findUnique()` with fields that have native database type `citext` are batched incorrectly

### ISSUE THREAD

**Issue by PabloSzx** [prisma/prisma#13534]
### Bug description

With any model that has a `citext` field:

```prisma
datasource db {
  provider = "postgresql"
  url      = "__"
}

model Test {
  id String @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid

  caseInsensitiveField String @unique @db.Citext
}
```

this happens:

![image](https://user-images.githubusercontent.com/8672915/170777379-19172cb1-34ec-4bad-af2f-13d7c59135c0.png)
![image](https://user-images.githubusercontent.com/8672915/170777425-f153dd29-f405-46f4-9fc9-a0dc37ceee93.png)

### How to reproduce

GitHub repo with the reproduction: https://github.com/PabloSzx/prisma-citext-find-unique-batch-issue

### Expected behavior

To findUnique to work as expected with any field

### Prisma information

```
model Test {
  id String @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid

  caseInsensitiveField String @unique @db.Citext
}
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 16.15.0

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/.pnpm/@prisma+engines@3.14.0-36.2b0c12756921c891fec4f68d9444e18c7d5d4a6a/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/.pnpm/@prisma+engines@3.14.0-36.2b0c12756921c891fec4f68d9444e18c7d5d4a6a/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/.pnpm/@prisma+engines@3.14.0-36.2b0c12756921c891fec4f68d9444e18c7d5d4a6a/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/.pnpm/@prisma+engines@3.14.0-36.2b0c12756921c891fec4f68d9444e18c7d5d4a6a/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by squareloop1** [comment]
Same is happening for `findMany()`. Before Prisma v4 it would work with Postgres `CITEXT` columns even without `mode: 'insensitive'` (as stated in the documentation). Now it does not find case insensitive. If I explicitly attach `mode: 'insensitive'` to the search query it works as expected. `mode` should be irrelevant on `CITEXT` columns as stated in the docs.

**Comment by Jolg42** [comment]
Related 
https://github.com/prisma/prisma/issues/14935
https://github.com/prisma/prisma/issues/14440

**Comment by Jolg42** [comment]
I can reproduce that on `3.15.2` `mode: "insensitive"` is not needed (but needed in version `4.0.0`) to have results so this looks like a regression here.
```
  const modeinsensitive = await prisma.user.findMany({
    where: {
      email: {
        contains: "tEsT",
        // mode: "insensitive", // is not needed in v3 but needed in v4
      },
    },
  });
  console.log({ modeinsensitive });
```

**Comment by janpio** [comment]
Internal Note: I don't think the issues @Jolg42 posted are strictly related. This one is probably a problem with the batching logic (queries are batched internally, then can not be split apart for the results at the end) and not with the "engine join".

**Comment by alecrobins** [comment]
thanks for working on this @janpio 🙏  we just ran into this issue and took us awhile to narrow down that `citext` was not behaving as expected
