### ISSUE TITLE
Prisma deletes additional indexes

### ISSUE THREAD

**Issue by Zauberbutter** [prisma/prisma#13562]
### Bug description

Prisma always wants to add a new migration where all additional indexes are getting deleted.

### How to reproduce

1. setup prisma
2. run `prisma migrate dev --create-only`
3. add an index on any column with this migration, for example: `CREATE INDEX gin_trgm_idx ON "Foo" USING gin ("bar" gin_trgm_ops);`
4. run `prisma migrate dev`

### Expected behavior

> You can continue using Prisma Migrate as you were before, it will ignore indexes that it doesn't know about.
https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search#adding-indexes

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}

model Foo {
  id Int @id @default(autoincrement())
  bar String
}
```

### Environment & setup

- OS: ArchLinux
- Database: PostgreSQL
- Node.js version: 16 LTS

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
Preview Features        : fullTextSearch
```

**Comment by janpio** [comment]
Take a look at https://www.prisma.io/docs/concepts/components/prisma-schema/indexes please - there currently is a preview feature that should make using GIN indexes much more stable and reliable. Thanks.

**Comment by Zauberbutter** [comment]
@janpio Thank you! That works like a charm. Maybe this information could be linked in the full text search chapter?

<details>
<summary>GIN index on column bar</summary>
<pre>
@@index([resolvedUrl(ops: raw("gin_trgm_ops"))], type: Gin)
</pre>
</details>

**Comment by Jolg42** [comment]
Note: we are making the preview feature `extendedIndexes` GA (so no need for a preview feature flag) in Prisma 4.0 planned next week.
