### ISSUE TITLE
DB Pull Error

### ISSUE THREAD

**Issue by fuergaosi233** [prisma/prisma#13563]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull --force`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v16.14.0           | 
| Prisma CLI  | 3.14.0             | 
| Engine      | 2b0c12756921c891fec4f68d9444e18c7d5d4a6a| 

## Error
```
Error: [introspection-engine/connectors/mongodb-introspection-connector/src/sampler/statistics/indices.rs:169:71] called `Option::unwrap()` on a `None` value
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by fuergaosi233** [comment]
I think the problem may be in my DB schema, which is very large and I can't seem to provide any more information.
