### ISSUE TITLE
Prisma not returning PrismaPromise

### ISSUE THREAD

**Issue by awinograd** [prisma/prisma#13570]
### Bug description

I'm upgrading from 3.8.0 to 3.14.0. I'm not able to test this on intermediate versions since other transaction bugs have been fixed in the meantime which fail our tests in other ways. Our test suite is now failing on usages of `$transaction([])` with

> All elements of the array need to be Prisma Client promises. Hint: Please make sure you are not awaiting the Prisma client calls you intended to pass in the $transaction function.

The issue happens both with or without interactiveTransactions enabled.

It appears that the check for whether or not something is a PrismaPromise changed in:

https://github.com/prisma/prisma/commit/3855438b964b40edeb72a3815c641d97f8c433c4

### How to reproduce

Unfortunately i haven't been able to construct a minimal repro that demonstrates this issue. I'm hoping to get a lead from the prisma team on where to look so that I may be able to create one.

The code I'm using in my app is pretty straightforward but if I try to recreate the same in an isolated repro I dont see the same behavior

```
    const [newUser] = await context.prisma.$transaction([
      context.prisma.user.create({
        data: {
          ...
        },
      }),
    ]);
```

In the above snipped, prisma.user.create returns a normal `Promise` object and if I log `promise[Symbol.toStringTag]` I dont get PrimsaPromise back out.

### Expected behavior

`user.create` returns a PrismaPromise such that $transaction succeeds without throwing error about "Prisma client promises"

### Prisma information

Not yet available. I know that makes it much harder to debug on your end. Just a lead in the right direction would be great if possible

### Environment & setup

- OS: MacOS/Linux
- Database: PostgreSQL
- Node.js version: 16.13.1

### Prisma Version

```
3.14.0
```

**Comment by awinograd** [comment]
Reporting back, this doesn't (unsurprisingly) appear to be an issue with prisma. We wrap some of our prisma properties in Proxy objects so it looks like we need to figure out how to replicate the PrismaProxy symbol behavior

**Comment by awinograd** [comment]
This is what we've come up with for the time being:

```ts
              let requestTransaction: Function;
              const res = auditFn({ model, action: prop2 as string, args }, (params) => {
                const prismaPromise = normalAction(params.args);
                requestTransaction = prismaPromise.requestTransaction;
                return prismaPromise;
              });

              // https://github.com/prisma/prisma/issues/13570
              // https://github.com/prisma/prisma/blob/3855438b964b40edeb72a3815c641d97f8c433c4/packages/client/src/runtime/core/request/createPrismaPromise.ts#L43
              return {
                then: (...args: any[]) => res.then(...args),
                requestTransaction: (...args: any[]) => requestTransaction(...args),
                finally: (...args: any[]) => res.finally(...args),
                catch: (e: any) => res.catch(e),
                [Symbol.toStringTag]: 'PrismaPromise',
              };
```

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by geoffreyhach** [comment]
Why is this issue closed? I had the same issue and had to use @awinograd's workaround
