### ISSUE TITLE
MongoDB composite index crashes

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#13618]
If having two index definitions like this:

```json
{
  "foo": 1,
  "foo.bar": 1
}
```

The introspection of this will crash.

**Comment by janpio** [comment]
Error reports for this: 
https://github.com/prisma/prisma/issues/13563
https://github.com/prisma/prisma/issues/12998

Ultimately fixed by:
https://github.com/prisma/prisma/issues/13332
