### ISSUE TITLE
Type NullableStringFieldUpdateOperationsInput must be an Object

### ISSUE THREAD

**Issue by Morriz** [prisma/prisma#13610]
### Bug description

AS title says. See below. I see errors about a string field not getting the correct shape input:
```
Type NullableStringFieldUpdateOperationsInput must be an Object.
```

### How to reproduce

Consider this query:
```gql
mutation UpdateUser($name: NullableStringFieldUpdateOperationsInput, $email: String!) {
    updateUser(where: { email: $email }, data: { name: $name }) {
      name
    }
  }
```
Which is only satisfied with the following shape variables:
```json
{"email": "not@ex.ists", "name": {"set": "some name"}}
```

### Expected behavior

I'd expect to be able to set the `name` string field with the following variables:
```json
{"email": "not@ex.ists", "name": "some name"}
```

### Prisma information

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
}

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 16.4

### Prisma Version

```
3.14.0
```

**Comment by Morriz** [comment]
Hmmm...wrong repo I guess

**Comment by janpio** [comment]
The GraphQL query indicates that indeed, yes. The schema on the other hand looks like a normal Prisma schema though. 

Should close this issue here in the Prisma repo? Or is there anything we can do here?
