### ISSUE TITLE
MySql connection string bug.

### ISSUE THREAD

**Issue by pDallastra** [prisma/prisma#13622]
### Bug description

I was trying to connect my application to a server just paid for, and after a long time trying to connect it, I realized Prisma was not recognizing the DATABASE_URL string properly.

```
DATABASE_URL=mysql://u522094498_dallastra:password@sql803.main-hosting.eu:3306/u522094498_impext
```

This is what happens when running DB push or "migrate dev".

```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "undefined" at "u522094498_dallastra:3306"

And this is the Error that comes with it:
Error: P1001: Can't reach database server at u522094498_dallastra:3306
Please make sure your database server is running at u522094498_dallastra:3306.
```

I am using NestJS to work on this Application, and the hoster is "Hostinger". Using the same values to connect to the DB using DBeaver and TypeORM, I was able to connect to the DB just fine.

If there is anything else I could say or do to help you guys out to fix this, I am willing to get it done :).

### How to reproduce

Set Up `DATABASE_URL=mysql://u522094498_dallastra:password@sql803.main-hosting.eu:3306/u522094498_impext`
then `yarn prisma db push` or `yarn prisma migrate dev`

### Prisma information

`DATABASE_URL=mysql://u522094498_dallastra:password@sql803.main-hosting.eu:3306/u522094498_impext
`
"prisma": "^3.14.0",
"@prisma/client": "3.14.0",

### Environment & setup

- OS: Both Windows 11 and Mac OS 12.4
- Database: MySQL
- Node.js version: v14.18.1

### Prisma Version

"prisma": "^3.14.0",
"@prisma/client": "3.14.0",

**Comment by janpio** [comment]
Hm, I get a normal authentication error with the output as expected:

```
PS C:\Users\Jan\Documents\throwaway\13622> npx prisma db pull
Prisma schema loaded from prisma\schema.prisma
Environment variables loaded from .env
Datasource "db": MySQL database "u522094498_impext" at "sql803.main-hosting.eu:3306"

✖ Introspecting based on datasource defined in prisma\schema.prisma

Error: P1000

Authentication failed against database server at `sql803.main-hosting.eu`, the provided database credentials for `u522094498_dallastra` are not valid.

Please make sure to provide valid database credentials for the database server at `sql803.main-hosting.eu`.

PS C:\Users\Jan\Documents\throwaway\13622> npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "u522094498_impext" at "sql803.main-hosting.eu:3306"

Error: P1000: Authentication failed against database server at `sql803.main-hosting.eu`, the provided database credentials for `u522094498_dallastra` are not valid.

Please make sure to provide valid database credentials for the database server at `sql803.main-hosting.eu`.
```

What does your password look like - just alphanumeric characters or maybe something "funny"? You might need to percent encode those: https://www.prisma.io/docs/reference/database-reference/connection-urls#special-characters

**Comment by pDallastra** [comment]
> 
Hi @janpio , I really appreciate your comment.

I won't lie to you, I have done that encode thing for the password since it does have special characters... But I swer it did not work the thousand times I tried it. But it i working now! So, thanks for somehow making it work again haha.

**Comment by janpio** [comment]
Ha, don't worry. It had actually a nice side effect: I started wondering if we can not get rid of that somehow and started a few inquiries about that internally... so maybe, one day in the future, it will not be possible to have that problem any more. Let's see.

**Comment by BastinRobin** [comment]
[Secure%40acloud%23%40%21123](https://www.url-encode-decode.com/) Helped me to encode the password. Its working perfectly fine. :) Thank you @janpio  @pDallastra

**Comment by BastinRobin** [comment]
https://www.url-encode-decode.com/ Helped me to encode the password. @pDallastra @janpio Thank you both
