### ISSUE TITLE
Database must be defined in the connection string

### ISSUE THREAD

**Issue by qWici** [prisma/prisma#13647]
### Bug description

Can't connect to mongoDB

### How to reproduce

I created new Nest.js project from scratch and got next error:
```bash
Error: Error parsing connection string: Database must be defined in the connection string
    at /api/node_modules/@prisma/client/runtime/index.js:41273:21
```

### Prisma information

```
datasource db {
  provider = "mongodb"
  url      = "mongodb+srv://api:g9ZP7c2qCOhUVtlm@cluster0.xnrtx.mongodb.net/?retryWrites=true&w=majority"
}

generator client {
  provider = "prisma-client-js"
}

model Hero {
  id    String @id @default(auto()) @map("_id") @db.ObjectId
}
```

### Environment & setup

- OS: Ubuntu 20.04
- Database: Atlas MongoDB Cluster
- Node.js version: 16.13.1

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
Done in 0.74s.

```

**Comment by janpio** [comment]
Your connection string is missing the database name before `?retryWrites...`. Prisma requires that you define the exact database you are connecting to, not just the database server.

**Comment by qWici** [comment]
> Your connection string is missing the database name before `?retryWrites...`. Prisma requires that you define the exact database you are connecting to, not just the database server.

Ok. I create a DB with name `api`

![image](https://user-images.githubusercontent.com/11472929/172021219-863066d4-4a69-47ec-a874-7b4e75b8b458.png)

And now my url next:
```
mongodb+srv://api:JK6JvKrGedYIZne9@cluster0.xnrtx.mongodb.net/api?retryWrites=true&w=majority
```

but I still get same error

**Comment by qWici** [comment]
Ok. I regenerate Prisma config with `yarn prisma generate` and now it works. Thanks!

**Comment by Reedam-Ranjan** [comment]
> Your connection string is missing the database name before `?retryWrites...`. Prisma requires that you define the exact database you are connecting to, not just the database server.

Thanks man for the support . Appreciated.
