### ISSUE TITLE
Unable to require ...  The specified module could not be found.

### ISSUE THREAD

**Issue by SHRUTIKALOKHANDE** [prisma/prisma#13648]
1. Prisma version (`prisma -v` or `npx prisma -v`):

2. Logs from Developer Tools Console or Command line, if any:
```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: Unable to require(`D:\nestjs\api-tutorial\node_modules\@prisma\engines\query_engine-windows.dll.node`)
 The specified module could not be found.
\\?\D:\nestjs\api-tutorial\node_modules\@prisma\engines\query_engine-windows.dll.node
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`)

4. Prisma schema (if relevant):
```

```

**Comment by janpio** [comment]
This looks a bit like a duplicate of https://github.com/prisma/prisma/issues/12203 which has the same error message.

**Comment by jkomyno** [comment]
I'd advise against tagging this issue as a duplicate, as the error in this issue is `The specified module could not be found.`, the error in #12203 is `is not a valid Win32 application.`
