### ISSUE TITLE
Array as value to Prisma.sql template string

### ISSUE THREAD

**Issue by richardwu** [prisma/prisma#13663]
### Bug description

Currently one cannot pass an array to `Prisma.sql` for [raw database access](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access). 

For example, passing an array of strings in order to perform an `IN` query.

### How to reproduce

For example, the following:
```
const foo = ["buy", "sell"];
prisma.$queryRaw(Prisma.sql`SELECT * FROM "Transaction" WHERE "txType" IN ${foo} LIMIT 1`);
```
will fail:
```
      SELECT * FROM "Transaction" WHERE "txType" IN $1 LIMIT 1
   [["buy", "sell"]]
/Users/richardwu/code/tensor-hq/tensor-infra/api/src/node_modules/@prisma/client/runtime/index.js:45405
        throw new PrismaClientKnownRequestError(message, e.code, this.client._clientVersion, e.meta);
              ^
PrismaClientKnownRequestError:
Invalid `prisma.$queryRaw()` invocation:


  Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "$1"`
    at Object.request (/Users/richardwu/code/tensor-hq/tensor-infra/api/src/node_modules/@prisma/client/runtime/index.js:45405:15)
    at async Proxy._request (/Users/richardwu/code/tensor-hq/tensor-infra/api/src/node_modules/@prisma/client/runtime/index.js:46301:18)
    at async getLstatsTxs (/Users/richardwu/code/tensor-hq/tensor-infra/api/src/lstats.ts:129:18)
    at async upsertHistLstats (/Users/richardwu/code/tensor-hq/tensor-infra/api/src/hist_listing_stats/index.ts:101:3)
    at async /Users/richardwu/code/tensor-hq/tensor-infra/api/src/hist_listing_stats/index.ts:338:13 {
  code: 'P2010',
  clientVersion: '3.14.0',
  meta: {
    code: '42601',
    message: 'db error: ERROR: syntax error at or near "$1"'
  }
```

### Prisma information

    "@prisma/client": "^3.14.0"

### Environment & setup

OS: Mac OS
Database: Postgres
Node.js version: 16.13.1

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by Jolg42** [comment]
This should work
```js
prisma.$queryRaw(Prisma.sql`SELECT * FROM "Transaction" WHERE "txType" IN ${Prisma.join(foo)} LIMIT 1`);
```

Let us know if it doesn't, so we can investigate. Maybe this is missing some documentation 🤔

**Comment by richardwu** [comment]
Amazing, that works!

Yes: documentation on this would be very nice :)

**Comment by Jolg42** [comment]
I found it documented here https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#tagged-template-helpers ✅

**Comment by christianlind99** [comment]
@Jolg42 

I am running into the same issue, and this still does not work

`        const categories = ["geometri", "algebra"];
        const randomKva = (await ctx.prisma
          .$queryRaw`SELECT * FROM Kva WHERE category in ${Prisma.join(
          categories
        )} ORDER BY RAND() LIMIT ${number};`) as unknown as PrismaPromise<
          Kva[]
        >;
`

**Comment by janpio** [comment]
Open a new issue please @christianlind99 and provide all information standalone. Thanks.

**Comment by christianlind99** [comment]
Will do, thanks.

**Comment by daweimau** [comment]
> This should work
> 
> ```js
> prisma.$queryRaw(Prisma.sql`SELECT * FROM "Transaction" WHERE "txType" IN ${Prisma.join(foo)} LIMIT 1`);
> ```
> 
> Let us know if it doesn't, so we can investigate. Maybe this is missing some documentation 🤔 (see examples [here](https://github.com/blakeembrey/sql-template-tag))

Needed braces, then worked

```
prisma.$queryRaw(Prisma.sql`SELECT * FROM "Transaction" WHERE "txType" IN (${Prisma.join(foo)}) LIMIT 1`);
```
