### ISSUE TITLE
`prisma generate`: Non-functional debounce mechanism for watch mode

### ISSUE THREAD

**Issue by Gnucki** [prisma/prisma#13677]
Watch mode only watch once on my setup.
This appears to me to be a simple typo in the code of the `simpleDebounce` method.
I will join a fix soon !

EDIT : Fix in #13678

**Comment by garrensmith** [comment]
@Gnucki we ready to merge this once you have signed the CLA.

**Comment by Jolg42** [comment]
@garrensmith did someone confirm the problem and fix? (labels shows unconfirmed)

**Comment by Gnucki** [comment]
> @Gnucki we ready to merge this once you [have signed the CLA. ](https://github.com/prisma/prisma/pull/13678#issuecomment-1148939944)

I did it, but the status don't show it.
