### ISSUE TITLE
Prisma connection not closing in Playwright test runner

### ISSUE THREAD

**Issue by arvindell** [prisma/prisma#13683]
### Bug description

Hello, Prisma team, thanks for your amazing work.

We use Playwright for running e2e tests against our web applications at my company. We are already using Prisma on the backend and would like to use it also for seeding (and tearing down) the data that is required for running the tests (creating a test user, deleting a post after creating it, etc).

So far Prisma works well for this purpose, speeding up my workflow a lot. However, some of the time, the playwright process gets stuck and It never exits. I suspect that it is related to the Prisma client connection because I see these logs over and over when the tests have been completed (using `DEBUG=*`):

![2022-06-06_12-32](https://user-images.githubusercontent.com/29064411/172473960-444ee735-6f3b-496b-80db-9b4509cf04c9.png)

This goes on forever and I have to manually Ctrl+C, which is not ideal for a CI environment

### How to reproduce

So far I have not reached a reliable reproduction. For every 5 tests that I run, 3 of them get stuck and never exit.

I'd like to know if you can give me any hints at what may be causing this problem or how to properly manage my connections. It might be useful to consider that Playwright runs tests in parallel using worker processes.

### Expected behavior

I expect the Playwright process to exit immediately after the tests have completed (either successful or unsuccessfully)

### Environment & setup

- OS: KDE Neon 5.24
- Database: MySQL 8
- Node.js version: 14.17.4

### Prisma Version

```
prisma                  : 3.13.0
@prisma/client          : 3.13.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : efdf9b1183dddfd4258cd181a72125755215ab7b
Studio                  : 0.459.0
Preview Features        : fullTextSearch, fullTextIndex
```

**Comment by janpio** [comment]
Is the log sequence repeating? Can you post a full "iteration" of that sequence as text (instead of screenshot)? Thanks.

**Comment by arvindell** [comment]
Sure, @janpio, here it is:

>   pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: '/home/alexrv/.cache/ms-playwright/chromium-1000/chrome-linux/chrome',
  pw:channel:event       name: 'chromium'
  pw:channel:event     },
  pw:channel:event     guid: 'browser-type@f74b5c965c6ef7df504f24ab3a245f00'
  pw:channel:event   }
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: '/home/alexrv/.cache/ms-playwright/firefox-1322/firefox/firefox',
  pw:channel:event       name: 'firefox'
  pw:channel:event     },
  pw:channel:event     guid: 'browser-type@18ba76dba19b322467cce041bd976e15'
  pw:channel:event   }
  pw:channel:event } +3ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: '/home/alexrv/.cache/ms-playwright/webkit-1630/pw_run.sh',
  pw:channel:event       name: 'webkit'
  pw:channel:event     },
  pw:channel:event     guid: 'browser-type@302788b257e2fb98f8dba0dded9d30aa'
  pw:channel:event   }
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Android',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'android@56bdc20f6990c78c062ff5acc5b28aac'
  pw:channel:event   }
  pw:channel:event } +1ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Electron',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'electron@f6d62861742e61fdabf2edabd4761ef2'
  pw:channel:event   }
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'LocalUtils',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'localUtils@e7dae7e82008aa79d77ee920fd592f07'
  pw:channel:event   }
  pw:channel:event } +1ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Selectors',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'selectors@688d465a25a225f2e3e18e618e57b105'
  pw:channel:event   }
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Playwright',
  pw:channel:event     initializer: {
  pw:channel:event       chromium: [Object],
  pw:channel:event       firefox: [Object],
  pw:channel:event       webkit: [Object],
  pw:channel:event       android: [Object],
  pw:channel:event       electron: [Object],
  pw:channel:event       utils: [Object],
  pw:channel:event       deviceDescriptors: [Array],
  pw:channel:event       selectors: [Object],
  pw:channel:event       preLaunchedBrowser: undefined,
  pw:channel:event       socksSupport: undefined
  pw:channel:event     },
  pw:channel:event     guid: 'Playwright'
  pw:channel:event   }
  pw:channel:event } +1ms
  prisma:tryLoadEnv Environment variables loaded from /home/alexrv/Projects/quentli/quentli/.env +0ms
  prisma:tryLoadEnv Environment variables loaded from /home/alexrv/Projects/quentli/quentli/.env +406ms
  prisma:client dirname /home/alexrv/Projects/quentli/quentli/node_modules/.prisma/client +0ms
  prisma:client relativePath ../../../prisma +0ms
  prisma:client cwd /home/alexrv/Projects/quentli/quentli/prisma +0ms
  prisma:client clientVersion: 3.13.0 +36ms
  prisma:client clientEngineType: library +0ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client:libraryEngine hookProcess received: exit +274ms
  prisma:client:libraryEngine runBeforeExit +0ms

**Comment by jkomyno** [comment]
@arvindell thank you for this issue, would you be able to run your e2e tests with `Node.js v18.3.0` (which might provide more insights and diagnostics about leaked promises/resources) and `prisma v3.15.0`, and see if you get the same issue?

**Comment by janpio** [comment]
How do we get to a reproduction of this @arvindell? Right now we are just guessing, but of course we would love to experience this ourselves so we can actually fix it. Thanks.

**Comment by arvindell** [comment]
> How do we get to a reproduction of this @arvindell? Right now we are just guessing, but of course we would love to experience this ourselves so we can actually fix it. Thanks.

Hi! Since I created this issue this is not a problem anymore. The tests are closing the connection correctly now. I'm guessing it was a Playwright bug that got fixed

Thanks!

**Comment by janpio** [comment]
Awesome, thanks for the update!
