### ISSUE TITLE
Support for composite string in default in the schema level

### ISSUE THREAD

**Issue by KevinEdry** [prisma/prisma#13687]
## Problem

We want to create a readable id for one of our data models such as "table_[uuid]". 

## Suggested solution

Be able to define a composite string in the schema such as:
`id             String               @unique @default(["table_", uuid()])`
or
`id             String               @unique @default("table_" +  uuid())`

it would be also nice to create custom types for those composite strings, such as "TableId" that will infer to a Typescript type or regex.

The current Typescript implementation for this will be:
`type TableId = ``table_${string}``;`

## Alternatives

The current alternative is to handle it in js and then send the composite string to the id field.

**Comment by janpio** [comment]
Do you think your request is adequately covered by https://github.com/prisma/prisma/issues/3391?
If not, maybe add a comment there - and then close this issue? Thanks.

**Comment by KevinEdry** [comment]
It does, closing this issue, thanks!
