### ISSUE TITLE
Prisma fails on Postgres query with findMany

### ISSUE THREAD

**Issue by KristijanS99** [prisma/prisma#13704]
I have the following query in Prisma that basically returns all users where campaign id is one from the array I provide and they are added to the system within the defined time range. Also I have another entity Click for each user that should be included in the response. 

      const users = await this.prisma.user.findMany({
        where: {
          campaign: {
            in: [
              ...campaigns.map((campaign) => campaign.id),
              ...campaigns.map((campaign) => campaign.name),
            ],
          },
          createdAt: {
            gte: dateRange.since,
            lt: dateRange.until,
          },
        },
        include: {
          clicks: true,
        },
      });

The problem is this query runs fine in localhost where I don't have much data, but in the production database there are nearly 500.000 users and 250.000 clicks in total, so I am not sure if that is the root case but the query fails with the following exception:

    Error: 
    Invalid `this.prisma.user.findMany()` invocation in
    /usr/src/app/dist/xyx/xyx.service.js:135:58
    
      132 }
      133 async getUsers(campaigns, dateRange) {
      134     try {
    → 135         const users = await this.prisma.user.findMany(
      Can't reach database server at `xyz`:`25060`
    
    Please make sure your database server is running at `xyz`:`25060`. 

Prisma error code is `P1001`.\

It is strange that if the `dateRange` is exactly 1 day it is working, it fails in case when the date range difference is > 1 day.

`xyz` replaced for obvious reasons in the paths and connection string to the DB.

**Comment by doomSDey** [comment]
@KristijanS99 Hi,
Can I know which database you are running on the backend? I had a similar issue where I was using Prisma in conjunction with psql. Turns out it was the limitation of psql which prevented the query of "findMany" with anything more than ~32000 params.

**Comment by KristijanS99** [comment]
> @KristijanS99 Hi, Can I know which database you are running on the backend? I had a similar issue where I was using Prisma in conjunction with psql. Turns out it was the limitation of psql which prevented the query of "findMany" with anything more than ~32000 params.

I am running Postgres, definitely it is more than 32.000 records to be returned in my case.

**Comment by doomSDey** [comment]
> > @KristijanS99 Hi, Can I know which database you are running on the backend? I had a similar issue where I was using Prisma in conjunction with psql. Turns out it was the limitation of psql which prevented the query of "findMany" with anything more than ~32000 params.
> 
> I am running Postgres, definitely it is more than 32.000 records to be returned in my case.

I was also using it for more that 32k records but I found through brute testing that it worked below 32k. Can you test for the same?

**Comment by RadekHavelka** [comment]
https://github.com/prisma/prisma/issues/8832

**Comment by aqrln** [comment]
Potentially related: https://github.com/prisma/prisma/issues/11950

**Comment by jkomyno** [comment]
Possibly related: https://github.com/prisma/prisma/issues/8878

**Comment by jkomyno** [comment]
Closing this in favour of https://github.com/prisma/prisma/issues/8832, please see [this comment](https://github.com/prisma/prisma/issues/8832#issuecomment-1237850099).
