### ISSUE TITLE
`generate` without first installing `@prisma/client` leads to strangeness, also mentions `@prisma/photon`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1371]
I used `prisma2 init` to create a schema (in a new, empty folder), then edited it manually and introspected the database successfully. Then:

```
C:\Users\Jan\Documents\throwaway\initTest
λ prisma2 generate
Error:
    Error: In order to use the "prisma-client-js" generator, you need to install @prisma/client to your project:
    npm install @prisma/client
        at C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:183583:23
        at Generator.next (<anonymous>)
        at C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:183554:71
        at new Promise (<anonymous>)
        at module.exports.9949.__awaiter (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:183550:12)
        at Object.prisma-client-js (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:183575:47)
        at Object.<anonymous> (C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:83452:114)
        at Generator.next (<anonymous>)
        at C:/ProgramData/nvm/v12.6.0/node_modules/prisma2/build/index.js:83369:71
        at new Promise (<anonymous>)

C:\Users\Jan\Documents\throwaway\initTest
λ npm install @prisma/client

> @prisma/client@2.0.0-alpha.538 postinstall C:\Users\Jan\Documents\throwaway\initTest\node_modules\@prisma\client
> node scripts/postinstall.js

undefined
Error: In order to use "@prisma/photon", please install prisma2. You can install it with "npm add -D prisma2".
    at main (C:\Users\Jan\Documents\throwaway\initTest\node_modules\@prisma\client\scripts\postinstall.js:22:9)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Jan\Documents\throwaway\initTest\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Jan\Documents\throwaway\initTest\package.json'
npm WARN @prisma/client@2.0.0-alpha.538 requires a peer of prisma2@* but none is installed. You must install peer dependencies yourself.
npm WARN initTest No description
npm WARN initTest No repository field.
npm WARN initTest No README data
npm WARN initTest No license field.

+ @prisma/client@2.0.0-alpha.538
added 1 package and audited 1 package in 6.135s
found 0 vulnerabilities


C:\Users\Jan\Documents\throwaway\initTest
λ prisma2 -v
prisma2@2.0.0-alpha.571, binary version: 1a0db4166ffce810428c731661582371d3ab88c4
```

Note that a `package-lock.json` got created, but a `package.json` did not.

**Comment by janpio** [comment]
Rerunning these steps with an existing `package.json`, I get a prompt to install `@prisma/client` instead of just the instructions I got before:

```
C:\Users\Jan\Documents\throwaway\initTest  (inittest@1.0.0)
λ prisma2 generate
In order to use the "prisma-client-js" generator, you need to install @prisma/client to your project.
? Do you want to install it now? » (Y/n)
```

**Comment by yovanoc** [comment]
There is no definition too
![image](https://user-images.githubusercontent.com/7302317/72660302-5b886b00-39cc-11ea-8fab-a2af800cd825.png)

**Comment by janpio** [comment]
That shouldn't be the case @yovanoc and also was not the case for me. Please create a new issue where you supply more information so we can look into this. Thanks.

**Comment by yovanoc** [comment]
@janpio I will wait for the preview release to see if I did something wrong, and if it's not the case I will create an issue. thanks

**Comment by yovanoc** [comment]
@janpio 

I found the problem, here in the package.json

```json
	"name": "@prisma/client",
	"version": "2.0.0-alpha.584",
	"main": "index.js",
	"types": "index.d.ts",
```

but look

![image](https://user-images.githubusercontent.com/7302317/72800916-b29a7400-3c48-11ea-958e-ecce5f744353.png)

these files are in the dist folder, so you should prepend dist/ before the main and types field in the package.json I guess.

**Comment by yovanoc** [comment]
@janpio I found the problem. In fact when I have not installed prisma2 globally and run `yarn prisma2 generate` it doesn't generate at all. I have to install it globally and run `prisma2 generate`

**Comment by janpio** [comment]
Looking forward to that issue then ;)

**Comment by pantharshit00** [comment]
Like the other issue, I am not able to reproduce this exact behaviour but still, I am stuck at this version mismatcher error:
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/22195362/72914124-3432f480-3d64-11ea-9cb2-f3fa6112b285.png">

**Comment by pantharshit00** [comment]
Marking as a confirmed bug as behaviour is unintended in both cases for now

**Comment by janpio** [comment]
Please open a new issue for the version mismatch and remove this observation (and this reply) as offtopic here.

**Comment by janpio** [comment]
This should be gone.
