### ISSUE TITLE
any alert on PrismaCloud should have flows to SNOW regardless integration time

### ISSUE THREAD

**Issue by leecholim** [prisma/prisma#13721]
## Problem

Do not when the design was changed.  As per current design , Prisma Cloud will send notifications to SNOW only when an alert status changes or a new alert is generated after turning on the integration.
Previously, we can enable the alerts in Prisma to flows to SNOW at anytime regardless status and integration time.
but now, any OPEN alert need to flow to SNOW after the integration time, will require status change else will not flow in SNOW.
example, integration with SNOW happened in Dec, 2019. on June, 2022, i wanted to have specify policy flows to SNOW and those alert status is OPEN. it will not flows to SNOW and those alert had pass integration time in Dec 2019.

this doesn't make sense as:
1. integration only happened once
2. we can choose with alerts/policy need to flow to SNOW time by time
3. If I have 12k alerts need to send to SNOW now, do you expect me to change the their status from OPEN to something else 12k times?

## Suggested solution

We shld able to send any alerts to SNOW at anytime we want without changing the alert status.

## Alternatives

No alternative

**Comment by jkomyno** [comment]
Closing this issue, as it's not associated with this repository and organization.
