### ISSUE TITLE
Generate cause a typescript error with exported enum

### ISSUE THREAD

**Issue by tomapp** [prisma/prisma#13730]
### Bug description

Hello,

I meet an issue while trying to build my project. I get this error

`prisma/generated/tsed/index.ts:3:1 - error TS2308: Module "./client" has already exported a member named 'MyEnum'. Consider explicitly re-exporting to resolve the ambiguity.`

Because of the index file generated :

`
export * from "./client";
export * from "./interfaces";
export * from "./enums";
export * from "./models";
export * from "./services/PrismaService";
export * from "./repositories";
`

### How to reproduce

1. `npm run build`

### Expected behavior

Having my `dist` folder compiled without any typescript error.

### Prisma information

I would like to keep it to myself as much as possible.

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: 16.14.2

### Prisma Version

```
3.15.0
```

**Comment by aqrln** [comment]
> Because of the index file generated :
>
> ```
> export * from "./client"; export * from "./interfaces"; export * from "./enums"; export * from "./models"; export * from "./services/PrismaService"; export * from "./repositories";
> ```

Could you please clarify what you mean here? This certainly doesn't look like a file generated by Prisma.

**Comment by tomapp** [comment]
Yes it is the one generated in the `prisma/generated` folder. So far it looks good, but the exports from the client and the enum are conflicted.

**Comment by Jolg42** [comment]
@tomapp Could you provide a (minimal) reproduction for this?

**Comment by aqrln** [comment]
Thanks for the additional details!

Unfortunately I don't see how we can help here. Should I go ahead and close the issue?
