### ISSUE TITLE
Cannot connect to Supabase database

### ISSUE THREAD

**Issue by habibullah-rezaie** [prisma/prisma#13807]
### Bug description

I cannot connect to my Supabase database with the URI. However on the other hand I can connect without prisma directly with `psql`.

This is the command with which I connected to my database:
```sh
psql -h db.nauqxqbyeqpccehwqegs.supabase.co -p 5432 -d postgres -U postgres
```

And this is my URI:
```env
DATABASE_URL="postgresql://postgres:[mypasswordhere]@db.nauqxqbyeqpccehwqegs.supabase.co:5432/postgres"
```

### Step to reproduce:
I have tried it a lot, and Every time regardless of changing my db password or restarting server. And when I ran `npx prisma db pull`. Nothing changes.

This is the error: 
```
Prisma schema loaded from prisma/schema.prisma
Environment variables loaded from .env
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.nauqxqbyeqpccehwqegs.supabase.co:5432"

✖ Introspecting based on datasource defined in prisma/schema.prisma

Error: P1001

Can't reach database server at `db.nauqxqbyeqpccehwqegs.supabase.co`:`5432`

Please make sure your database server is running at `db.nauqxqbyeqpccehwqegs.supabase.co`:`5432`.
```

### My Prisma Schema
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

```

### Environment & setup

- OS: MX LINUX 21 
- Database: Postgresql
- Node.js version: v16.13.2

### Prisma Version

```
npx prisma -v
Environment variables loaded from .env
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by matthewmueller** [comment]
Hey @habibullah-rezaie! I'm surprised to see this is not working. I found [another discussion](https://github.com/prisma/prisma/discussions/11190) that might offer some guidance though.

Please let us know if you get it working following what's in the discussion!

**Comment by habibullah-rezaie** [comment]
I discovered that the problem is that I have an empty database there.

So when I created a table there on Supabase, I was able to to get it connected to with Prisma. However, whenever I first wrote some schema declarations I  Prisma and then I ran ,`npx prisma db pull` I also got the sma e error. So I think the point is that always I first should update bring updates in Supabase and after that I should just pull those updates with Prisma. 

I believe that it's something that is related to Supabase maybe.

**Comment by matthewmueller** [comment]
Ah interesting, thanks for sharing your findings!

**Comment by habibullah-rezaie** [comment]
What you mean?
You mean you got this error for the first time?
I previously had some tables there.

**Comment by janpio** [comment]
Yeah, I had tried that before and in databases that had tables before but do not any more, I have no problem at all.
I thought your description could mean that it is a totally new database that never had content, but again no problem at all.

**Comment by developerGCGMMC** [comment]
?connect_timeout=300

Add connection timeout at the end of your database url..

**Comment by Olomelok** [comment]
Was having similar problem. When I ran  npx prisma migrate dev init, it was solved

**Comment by Olomelok** [comment]
$ npx prisma migrate dev init
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.xxxxxxxxxxxxxx.supabase.co:5432"

? Enter a name for the new migration: » home
√ Enter a name for the new migration: ... home
Applying migration `20230404214100_home`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20230404214100_home/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (4.12.0 | library) to .\node_modules\@prisma\client in
 12.79s

**Comment by ludbek** [comment]
Try creating db in another region.

**Comment by Ayush-gupta-dev** [comment]
Im also getting same errors, what shpuld i do?

![image](https://github.com/prisma/prisma/assets/137040550/3b08744e-6d97-4f16-a2bc-a67497ee1261)

![image](https://github.com/prisma/prisma/assets/137040550/70bfda94-1723-431e-b24b-87763dd8437a)

**Comment by janpio** [comment]
https://github.com/prisma/prisma/issues/13807#issuecomment-1457867408 most probably @Ayush-gupta-dev

**Comment by Afuhnwi-Afriitech** [comment]
each time i try connecting to postgresql via supabase edge, i get the error ConnectionParamsError: Missing connection parameters: database, user. here is my database url postgresql://postgres:[xxxxxxxxxxxx@db.teuvqgwnaocxxxxxxyq.supabase.co](mailto:xxxxxxxxxxxx@db.teuvqgwnaocxxxxxxyq.supabase.co):5432/postgres

**Comment by BhagabanGhadai** [comment]
superbase already addressed this issue

**step -1**
add to .env file
```
# Connect to Supabase via connection pooling with Supavisor.
DATABASE_URL="postgresql://postgres.dnnhtbehpfyusttyytfw:[YOUR-PASSWORD]@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true"

# Direct connection to the database. Used for migrations.
DIRECT_URL="postgresql://postgres.dnnhtbehpfyusttyytfw:[YOUR-PASSWORD]@aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
        
```
**step-2**
add  to schema.prisma
`
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}
        `

**Comment by irfandyj** [comment]
For my case, I was using VPN. I disconnected and boom.
Hopefully that helps some of your case after trying it all.

**Comment by hevink** [comment]
If your password contains special characters like @, $, or others, make sure to URL encode them. For example, replace @ with %40 to avoid connection issues.

@ - %40
:    - %3A
/   - %2F
?   - %3F
=  - %3D
&  - %26

**Comment by joseluiszamora** [comment]
Its a DNS problem, prisma cannot resolve domain, to resolve:

1. execute: nslookup aws-0-us-west-1.pooler.supabase.com, to check the supabase IP 
2. add result IP in /etc/hosts, example: 54.177.55.191 aws-0-us-west-1.pooler.supabase.com

try again

**Comment by bizk** [comment]
@developerGCGMMC you are the goat
