### ISSUE TITLE
TypeScript 'include' with nested 'select' produced very strict defined array type, even when it can be []

### ISSUE THREAD

**Issue by DrJume** [prisma/prisma#13845]
### Bug description

```ts
const customers = await prisma.customer.findMany({
    include: {
        staff: {
            select: {
                user: true,
            },
            take: 1,
        },
    },
})
```

`customers` has a type of:

```ts
const customers: (Customer & {
    staff: {
        user: User;
    }[];
})[]
```

The issue is that `customers.staff` can be `[]`. `customer.staff[0]` should be therefore `undefined`, but the above type lets it be always defined as `User`.

### How to reproduce

See above

### Expected behavior

Type type of `customer` should be:

```ts
const customers: (Customer & {
    staff: ({
        user: User;
    } | undefined)[];
})[]
```

`customers.staff` should be an array, whose items can be `undefined`.

### Environment & setup

- OS: macOS
- Database: MongoDB
- Node.js version: v16.15.1

### Prisma Version

```
3.15.2
```

**Comment by driimus** [comment]
@DrJume this is a general limitation with array (not tuple) signatures in TypeScript. 

You can enable [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) in your TypeScript settings to enfore stricter checks, here's an [example](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&target=7&jsx=0#code/MYewdgzgLgBAhgJwXAngLhgbwJYBMNgCuAtgEYCmCAvgNoC6MAvDPQLABQHokIANuQDpeIAOYAKRMhQ0ADHQF4AlF3AQ+g4eMmpZdAPwLcioA).

**Comment by matthewmueller** [comment]
Thanks @driimus! Going to close this issue since it seems to be working as expected.
