### ISSUE TITLE
CockroachDB: `push` method is not generated for scalar lists / array fields

### ISSUE THREAD

**Issue by FKLC** [prisma/prisma#13892]
## Problem

Current [push](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#push) functionality doesn't allow pushing multiple items. Both databases (postgres and mongo) support pushing multiple items.

## Suggested solution

A `concat` function or being able to pushing multiple items using the current push function.

## Alternatives

For MongoDB you can use [$runCommandRaw](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#runcommandraw) and on Postgresql you can just concat arrays and set it to field.

**Comment by matthewmueller** [comment]
Thanks @FKLC, I agree that it would make sense to support pushing an array, just like in JS.

**Comment by FKLC** [comment]
Okay so upon further digging down the code, I found push command for MongoDB uses $concatArrays. Mongo's query engine handles pushing multiple items whether it is an array or not. To test whether this was also the case on JS side, I wrote the following and it works and conforms to the current type system.
```js
prisma.someModel.update({
  where: {
    ...,
  },
  data: {
    someArrayField: {
      push: [ someObject, anotherObject ],
    },
  },
})
```
So, MongoDB supports pushing multiple items contrary to what is said on docs. Haven't tested it on PostgreSQL, but will try to when I have time.

**Comment by FKLC** [comment]
Upon further investigation I found postgresql's query engine supports pushing multiple items as well and verified using the same code snippet above. I assume CockroachDB should support it as well considering it's combability with postgres. I will make proper adjustments to the docs and make a pull request. Closing the issue for now as it is more related to prisma/docs.

**Comment by janpio** [comment]
If something works with PostgreSQL but not with CockroachDB (and is not documentated as a limitation at https://www.prisma.io/docs/concepts/database-connectors/cockroachdb) we consider this a bug of Prisma as well - so feel free to open a bug report here as well and explain what is going on.

**Comment by FKLC** [comment]
> If something works with PostgreSQL but not with CockroachDB (and is not documentated as a limitation at https://www.prisma.io/docs/concepts/database-connectors/cockroachdb) we consider this a bug of Prisma as well - so feel free to open a bug report here as well and explain what is going on.

So to test whether pushing multiple items works with cockroach works or not, I used the same code above (couldn't find anything related to cockroachdb query engine, just found `||` operator is marked as `Postgres only`). Current Prisma client generator doesn't generate `push` method for `<SomeModel>Update<SomeArrayField>Input`, only `set`. On [Limitations of CockroachDB](https://www.prisma.io/docs/concepts/database-connectors/cockroachdb#other-limitations) pushing enums is listed as not supported (meaning pushing, say, strings is possible), also on [Working with scalar lists
](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-scalar-lists-arrays#adding-items-to-a-scalar-list) it is noted pushing items is available in "CockroachDB in versions 3.9.0 and later". However, on [Prisma client's docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#push) it is said push method is "Available for PostgreSQL and MongoDB only". So, the API docs match with the client's behavior, though I'm not sure about the limitations and concepts page. If you want to test yourself, here is the small example I used:

schema.prisma
```
datasource db {
  provider = "cockroachdb"
  url      = "postgresql://username:password@free-tier-cockroachdb-on-aws:26257/defaultdb"
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  name         String   @unique
  tags         String[]
}
```

.prisma/client/index.d.ts
```ts
...
  /**
   * Post update
   */
  export type PostUpdateArgs = {
    /**
     * Select specific fields to fetch from the Post
     * 
    **/
    select?: PostSelect | null
    /**
     * The data needed to update a Post.
     * 
    **/
    data: XOR<PostUpdateInput, PostUncheckedUpdateInput>
    /**
     * Choose, which Post to update.
     * 
    **/
    where: PostWhereUniqueInput
  }
...
  export type PostUpdateInput = {
    name?: StringFieldUpdateOperationsInput | string
    tags?: PostUpdatetagsInput | Enumerable<string>
  }
...
  export type PostUpdatetagsInput = {
    set?: Enumerable<string>
  }
...
```

When I change `provider = "cockroachdb"` to `provider = "postgres"` or to `provider = "mongodb"`, `PostUpdateInput` becomes the following

```ts
  export type PostUpdatetagsInput = {
    set?: Enumerable<string>
    push?: string | Enumerable<string>
  }
```

So, from what I understand, it seems like CockroachDB doesn't support pushing items at all unlike what is said on concepts and limitations page. If both of them use the same prisma query engine (which I believe they do?), then the problem is more likely to be on client side. I'm reopening the issue for now.

**Comment by FKLC** [comment]
I generated client using `provider = "postgres"` and while using cockroachdb and pushing works on cockroachdb but the method is not generated when `provider = "cockroachdb"`. SQL Query engine handles appending item(s) for both cockroachdb and postgres. The problem is most likely on the client generation side.

**Comment by janpio** [comment]
> However, on [Prisma client's docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#push) it is said push method is "Available for PostgreSQL and MongoDB only"

This is most probably just a bug in the documentation. We added CockroachDB later, and it seems we did not update all the notes where we highlight PostgreSQL (and thus now also CockroachDB) support.

**Comment by RobertCraigie** [comment]
I can confirm that this is supported by the underlying query engine. The `push` operation works when `provider` is set to `postgresql`.

**Comment by janpio** [comment]
Do I understand the situation correctly @FKLC that CockroachDB does support `||`, but only for Strings and not for Enums types? Currently we seem to not be able to differentiate in our types and either support both or nothing.

**Comment by RobertCraigie** [comment]
@janpio Yeah I was talking to the Cockroach database.

I can't remember exactly what types I tested but I have a test suite that I use to run tests against all database providers and I was running it before the switch to an explicit `cockroachdb` provider and during that time I only had to disable tests for:
- JSON arrays
- [Atomic divide](https://github.com/prisma/prisma/issues/16511)
- [Enum push](https://github.com/prisma/prisma/issues/16511#issuecomment-1329901201)

So yes it looks like CockroachDB doesn't support `||` for Enums but from reading the error message `unsupported binary operator: <Role[]> || <anyelement>` I wonder if it's because it needs an explicit type cast? (I haven't read any documentation  so may be completely wrong)

**Comment by FKLC** [comment]
> Do I understand the situation correctly @FKLC that CockroachDB does support `||`, but only for Strings and not for Enums types? Currently we seem to not be able to differentiate in our types and either support both or nothing.
> 
> @RobertCraigie I assume you were talking to a Cockroach database? Did it work for both types or did you only test strings maybe?

It has been a while, so I don't remember, but looking back at my issue, it seems I only tried to use push method for strings. So, I'm not sure if enums are supported, but my original issue was about the client generator. Generated client doesn't include push method (in my case, I only tried with strings, not sure about other types) when provider is set to cockroachdb despite the query engine supporting it. It seems from my original issue with the following schema:
```
datasource db {
  provider = "cockroachdb"
  url      = "postgresql://username:password@free-tier-cockroachdb-on-aws:26257/defaultdb"
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  name         String   @unique
  tags         String[]
}
```

you get the following client

```
...
export type PostUpdatetagsInput = {
    set?: Enumerable<string>
}
```

and if the provider was set to postgres, you get the following client:
```
...
export type PostUpdatetagsInput = {
    set?: Enumerable<string>
    push?: string | Enumerable<string>
}
```
In the past, I tried creating the client using postgres while actually using cockroachdb, and used the push method and worked.

**Comment by janpio** [comment]
(Upon rereading this, I was confused how we went from scalar lists to enums. I found the explanation in the CRDB issue: "Prisma currently disables push for string types as well as we do not differentiate between enum and string - so only can disable both at the same time.")
