### ISSUE TITLE
Postgres integer column silently overflows to bad value

### ISSUE THREAD

**Issue by jajarzombek** [prisma/prisma#13913]
### Bug description

On inserting record into table with integer column a value that overflows postgres max integer value of 2147483647 no error message is returned and record with bad value is silently stored. 
E.g. `2265000000` is saved as `-2029967296`

### How to reproduce

1. Create table with int column
2. Insert record via Prisma with value that exceeds max postgres integer
3. Wrong value in table is stored

### Expected behavior

An error should be thrown

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["improvedQueryRaw"]
}

datasource db {
  provider = "postgresql"
}
```

### Prisma Version

```
3.15
```

**Comment by pimeys** [comment]
There was some prior work to fix this here: https://github.com/prisma/prisma/issues/10586

But, the default postgres type for ints is integer, and that's a 32-bit value. We should improve the validation here.
