### ISSUE TITLE
new PrismaClient() takes 3 seconds to connect to Db on AWS lambda

### ISSUE THREAD

**Issue by matart15** [prisma/prisma#13933]
### Bug description

As this docs suggest I create `new PrismaClient` outside handler

But Very first request takes 3 seconds to create prisma client. Then later requests use created prisma client. very fast.

This time does not include cold start time. as picture shows lambda logs are after lambda started.

Only difference and 3seconds execution in 1st request is `url: postgresql://...` line which is `new PrismaClient` code.

![Screen Shot 2022-06-21 at 14 42 26](https://user-images.githubusercontent.com/17027219/174726553-27ee58d8-69a6-4e39-9107-daa17cb2abdb.png)

getPrismaClient.ts
```ts
import { PrismaClient } from "@prisma/client";
import { SecretsManager } from 'aws-sdk'

const sm = new SecretsManager()
let prisma: PrismaClient
let url: string

export const getPrismaClient = async () => {
  if (prisma) return prisma

  const dbURL = {.....}
  const secretString = JSON.parse(dbURL.SecretString || '{}')
  url = `postgresql://${secretString.username}:${secretString.password}@${secretString.host}:${secretString.port}/${secretString.dbname}?connection_limit=1`
  console.log('url: ', url);
  prisma = new PrismaClient({
    datasources: {db:{url}}
  });
  return prisma
}
```

### How to reproduce

deploy simple todo app to aws lambda

### Prisma information

<details>
 <summary>Click to expand!</summary>
```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x", "linux-arm64-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum m_DoorOpenPermissionType {
  SHORT_OPEN // users allowed to user short open action
  LONG_OPEN // users allowed to use long open action
}

model u_DoorOpenPermission {
  createdAt       DateTime                 @default(now())
  updatedAt       DateTime                 @default(now())
  cognitoUsername String // cognito company id
  doorId          Int
  startTime       DateTime                 @default(now()) // rule apply start time
  endTime         DateTime? // rule end time
  type            m_DoorOpenPermissionType

  door m_Door @relation(fields: [doorId], references: [id])
  @@id([doorId, cognitoUsername])
}

model m_Door {
  id           Int                    @id @default(autoincrement())
  createdAt    DateTime               @default(now())
  updatedAt    DateTime               @default(now())
  name         String
  allowedUsers u_DoorOpenPermission[]
  imageUrl     String
  isOpenDaily  Boolean
  isHidden     Boolean                @default(false)
}

```

</details>

### Environment & setup

- OS: Mac
- Database: Postgres
- Node.js version: 16

### Prisma Version

```
3.14.0
```

**Comment by matthewmueller** [comment]
Hey @matart15, could you try deploying a Lambda that uses something like https://node-postgres.com/api/client and take note of the time it takes to connect? I'd like to narrow down whether it's a Prisma issue or a database / network / lambda issue.

**Comment by matart15** [comment]
@matthewmueller

By your suggestion I tried detailed console log and pg library.

1. It turned out `new PrismaClient` was not the problem.
```ts
  const secretString = JSON.parse(dbURL.SecretString || '{}')
  url = `postgresql://${secretString.username}:${secretString.password}@${secretString.host}:${secretString.port}/${secretString.dbname}?connection_limit=1`
  console.log('url: ', url);
  prisma = new PrismaClient({
    datasources: {db:{url}}
  });
  console.log("prisma client created")
  console.log("after prisma create")
  const door = await prisma.m_Door.findFirst({
    where: {
      id: doorId,
      createdAt: {
        lt:  utcToZonedTime( getDateNow(), "Asia/Tokyo")
      },
      allowedUsers: {
        some: {
          cognitoUsername,
          type: "LONG_OPEN",
        },
      },
    },
  });
  console.log("after find door")
```
this find method is takning 3 seconds.

![Screen Shot 2022-06-27 at 12 12 18](https://user-images.githubusercontent.com/17027219/175853035-92d5f21f-f570-409a-96d9-01e5f446bbc5.png)

here is my data. just 2 doors and 11 permissions.
Is it how it should be ?

![Screen Shot 2022-06-27 at 12 10 40](https://user-images.githubusercontent.com/17027219/175852916-1fb31bb1-8aea-4855-932a-8f04592c99cd.png)
![Screen Shot 2022-06-27 at 12 10 47](https://user-images.githubusercontent.com/17027219/175852925-4d90b2f5-a778-4bef-8027-c94fccac51f8.png)

**Comment by matart15** [comment]
I tried do same with `pg` library. But somehow I can't make `join` query work. this query works on DBeaver app.

![Screen Shot 2022-06-27 at 12 15 15](https://user-images.githubusercontent.com/17027219/175853392-739f20ac-bd4e-4899-8b3e-ff362f884eb7.png)

```ts
  const client = new Client({
    host: secretString.host,
    port: secretString.port,
    user: secretString.username,
    password: secretString.password,
  })
  try {
    const s = await client.connect()
    console.log("pg client connected", s)
  } catch(e: any) {
    console.log("pg client connect failed", e)
  }
  console.log("after pg client");
  const s = await client.query(`
  select * from "m_Door" md
  join "u_DoorOpenPermission" udop 
    ON udop."doorId" = md.id 
    and udop."cognitoUsername" = '2ac11922-2b85-4596-bc11-63b0474610b6'
    and udop.type='LONG_OPEN'
  where md.id = 1
  and md."createdAt" < NOW()
  `
  ) 
```
`"errorMessage": "relation \"m_Door\" does not exist",`

![Screen Shot 2022-06-27 at 12 15 15](https://user-images.githubusercontent.com/17027219/175853304-8bedac6d-8a8a-4e91-8a05-4f1e10dd3e06.png)

**Comment by matart15** [comment]
Problem is this query is slow on after first call.
then second and third calls are very fast

```ts
  const door = await prisma.m_Door.findFirst({
    where: {
      id: doorId,
      createdAt: {
        lt:  utcToZonedTime( getDateNow(), "Asia/Tokyo")
      },
      allowedUsers: {
        some: {
          cognitoUsername,
          type: "LONG_OPEN",
        },
      },
    },
  });
```


![Screen Shot 2022-06-27 at 12 19 07](https://user-images.githubusercontent.com/17027219/175853901-6f9594c7-6eb9-45a2-a3eb-5296177ba0e1.png)


I thought query might be cached if it is not changed. 
I added this code to query. But results are same.
```ts
      createdAt: {
        lt:  utcToZonedTime( getDateNow(), "Asia/Tokyo")
      },
```

**Comment by janpio** [comment]
The first query probably opens the connection to the database before executing the actual query.

**Comment by matart15** [comment]
Yeah. that is my assumption too. 

To keep my functions simple I implemented my mutations to separate lambdas. when user opens app first time, it sends multiple queries and mutations.

now user have to wait 3s multiplied by query count.
also each time user does new action it takes 3 or 6 secs to complete.

My app UX went down to toilet.

Is there any way to make it faster or keep connection open. 

How other people do it?

**Comment by cayter** [comment]
@matart15 You might wanna try setting up the AWS RDS proxy which maintains a connection pool similar to how PGBouncer works. The connection pool maintained by Prisma only works well with long running NodeJS process, i.e. a traditional server or container environment. With AWS Lambda, once the lambda VM goes into idle for a while, it will get terminated and the Prisma connection pool is gone.

**Comment by cayter** [comment]
@matart15 You might wanna try setting up the AWS RDS proxy which maintains a connection pool similar to how PGBouncer works. The connection pool maintained by Prisma only works well with long running NodeJS process as it is done in the memory, i.e. a traditional server or container environment. With AWS Lambda, once the lambda VM goes into idle for a while, it will get terminated and the Prisma connection pool in the memory is gone as well.

**Comment by matart15** [comment]
Thank you I will try this

https://www.prisma.io/docs/guides/performance-and-optimization/connection-management/configure-pg-bouncer

**Comment by cayter** [comment]
@matart15 Sorry for my incorrect information. As documented [here](https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#aws-rds-proxy), Prisma client pooling doesn't work with AWS RDS proxy.

**Comment by matart15** [comment]
Looks like prisa data proxy is only solution. 

:(
