### ISSUE TITLE
Handle where clauses correctly for records where the field is `null` or `not defined` - MongoDB

### ISSUE THREAD

**Issue by arthurfiorette** [prisma/prisma#13949]
## Problem

> All ID's removed for abrreviation

<br />

```prisma
model Test {
  /// mandatory
  id String @id @default(auto()) @map("_id") @db.ObjectId
  /// just to differentiate
  name String @unique 

  nullable Boolean? // <--- This
}
```

When you declare a model with a nullable field, let's say `Test` (as described above), we can end up with 3 possible documents in our MongoDB databases.

```js
// 1: `nullable` is optional but has a null value
PRISMA.test.create({ data: { name: 'with null', nullable: null } });
databaseRecord = { name: 'with null', nullable: null }
```

```js
// 2: `nullable` is optional but specified
PRISMA.test.create({ data: { name: 'with true', nullable: true } });
databaseRecord = { name: 'with true', nullable: true }
```

```js
// 3: `nullable` is optional and ignored
PRISMA.test.create({ data: { name: 'empty' } });
databaseRecord = { name: 'empty' }
```

And that should be the desired behaviour, as we can save bytes with these null optional fields.

But the problem occurs when we try to filter these documents. Simply by using `where: { nullable: { not: null } }` or `where: { nullable: null }`, the 3rd option gets filtered out.

```js
console.log({
  nulls: await PRISMA.test.findMany({ where: { nullable: null }, }),
  notNulls: await PRISMA.test.findMany({ where: { nullable: { not: null } }, }),
  all: await PRISMA.test.findMany(),
});

result = {
  nulls: [{ name: 'with null', nullable: null }],
  notNulls: [{ name: 'with true', nullable: true }],
  all: [
    { name: 'with null', nullable: null },
    { name: 'with true', nullable: true },
    // The nullable field is present here, instead of just a { name: 'empty' } object,
    // which would cause obj.nullable to return undefined.
    { name: 'empty', nullable: null }, 
  ],
};

```

## Suggested solution

As said before, I don't think that use `null` values instead of not setting fields is a good way. Because we can save up a lot of bytes if we take in comparison a multi million record collection.

This issue maybe should have been created in the rust side of this project, but I'm not familiar enought with prisma arquitecture. 

Anyways, I think that transforming the query to handle both options (not present & present and null) like [this stackoverflow post](https://stackoverflow.com/questions/10591543/mongodb-how-to-query-for-records-where-field-is-null-or-not-set) does for the native mongodb javascript driver is good enough.

## Alternatives

I don't mind any other alternative, as long it works as intended :) 

## Additional context

- MongoDB 5.0
- Prisma Client ^3.15.2
- Prisma ^3.15.2

MongoDB Compass Test collection screenshot:

![image](https://user-images.githubusercontent.com/47537704/174888402-35b35a40-97be-46c8-ae30-c52036246a3b.png)

**Comment by janpio** [comment]
Side question: Are you sure that `// 3: `nullable` is optional and ignored` really creates and returns the data in the form you specified? I would expect Prisma to set the not specified field to null/undefined regardless.

>  I don't think that use null values instead of not setting fields is a good way. Because we can save up a lot of bytes if we take in comparison a multi million record collection.

Also more out of interest: Do you have numbers for this available?

**Comment by arthurfiorette** [comment]
> Side question: Are you sure that `// 3: `nullable` is optional and ignored` really creates and returns the data in the form you specified? I would expect Prisma to set the not specified field to null/undefined regardless.

Yes, I'll create a simple reproductible repository for this issue.

> Also more out of interest: Do you have numbers for this available?

I don't... but it's more a matter of logic. The fewer fields with null (since the prism knows they are null), the fewer bytes are stored / less storage required. 

1M x `{ name: 'yay' }` requires less storage than 1M x `{ name: 'yay', data: null, otherField: null }`.

We're currently in a pre-launch phase at our company, so that's why I don't have any numbers to prove it right now.

**Comment by arthurfiorette** [comment]
https://github.com/arthurfiorette/prisma-issue-13949

**Comment by arthurfiorette** [comment]
@janpio https://github.com/arthurfiorette/prisma-issue-13949

**Comment by janpio** [comment]
> EDIT: the `result` field was a representation of the data in the mongodb collection. The returned json from the prisma client actually contains the field with `null`.

Does that mean, that as I assumed Prisma Client itself can not be used right now to create an entry without the `nullable` field set to either `null` or a value?

If that is the case, I think your request is actually a feature request to enable that Prisma can store models without some of the fields that are defined in the schema as you are afraid of the space storing empty/null fields will take.

**Comment by arthurfiorette** [comment]
Sorry, English is not my main language, I think you got it wrong...

The problem is that: when we create an entity without manually defining a null field (A.K.A: `{ field: undefined }`), prisma doesn't even include this field in the final document that goes to the database.

Thus, when using filters like `{ field: { not: null } }` or `{ field: null }` in queries, the document that does not have the field defined is never returned. As you can see in the repository that I created.

**Comment by arthurfiorette** [comment]
There can be two "main" different solutions to this problem:

1. It automatically defines all (non present) optional fields with nulls, this way all documents will have all fields.

2. It automatically includes, in your translated queries, a where clause for `null`s and another non present fields. (as [this stackoverflow post says an example of how to do it in nodejs](https://stackoverflow.com/a/10591601/14681561)) _(not a rust example XD)_

What I said about the nulls occupying space in the disk only applies to  number 1, because prisma will start to add a lot of null fields in every document possible, thus, from now on, generating more bytes per each document. Number 1 is also a bad option because it still won't work with previously created documents.

**Comment by dpetrick** [comment]
This is intended behavior.

You can filter these fields with `isSet: true/false`: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#isset

The null/undefined result discussion can be tracked here: https://github.com/prisma/prisma/issues/12555

**Comment by arthurfiorette** [comment]
> This is intended behavior.
> 
> You can filter these fields with `isSet: true/false`: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#isset
> 
> The null/undefined result discussion can be tracked here: #12555

Thanks!

**Comment by heymartinadams** [comment]
How would one query fields (for MySQL) that are either `null` or `undefined`?
