### ISSUE TITLE
Module "@prisma/client" has no exported member "PrismaClient"

### ISSUE THREAD

**Issue by SooditK** [prisma/prisma#13946]
### Bug description

![image](https://user-images.githubusercontent.com/50576944/174857412-830ac231-5586-4766-9bb4-26d72bd1bfd4.png)

The latest version of @prisma/client (3.15.2) has (In my opinion) made some changes, and PrismaClient is no longer being exported from "@prisma/client";

### How to reproduce

1. Go to the file, where you want to import & import { PrismaClient } from "@prisma/client"
2. See error

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model user {
  id             Int      @id @default(autoincrement())
  email          String   @unique
  First_Name     String   @map("First Name")
  Last_Name      String   @map("Last Name")
  Password       String
  created_at     DateTime @default(now())
  updated_at     DateTime
}
```

### Environment & setup

- OS: EndeavourOS Linux x86_64 (Arch Linux)
- Database: MySQL (Provisioned by PlanetScale)
- Node.js version: 18.3.0

### Prisma Version

```
3.15.2
```

**Comment by arthurfiorette** [comment]
did you ran `prisma generate` as the docs says?

**Comment by matthewmueller** [comment]
As @arthurfiorette mentioned, I think you're missing a `prisma generate`.

**Comment by SooditK** [comment]
> As @arthurfiorette mentioned, I think you're missing a `prisma generate`. Perhaps you cloned the repo?

I won't raise an Issue, without running the ``` prisma generate ``` command sir. I've done a ``` prisma db push ``` as well.
Restarted my TypeScript Server. And the weird thing here is, the Package Manager.

```pnpm``` is giving this error, But If I delete the ```node_modules/``` and re-install all the dependencies with ```npm``` It works fine.

In most of my Projects, I use ```pnpm``` and all of them when ran ```pnpm install``` gives the same error.

**Comment by thasmo** [comment]
Installing via `pnpm` and using `import { PrismaClient } from '@prisma/client';` the typescript server states:
> Cannot resolve symbol 'PrismaClient'

I've run `pnpx prisma generate` which created `node_modules/.prisma/client`; still it's not picked up for some reason.

**Comment by pgiovanni** [comment]
I'm having the same issue on endeavourOS. I've run `prisma generate` and tried to reinstall `node_modules` as well.

**Comment by SooditK** [comment]
> I'm having the same issue on endeavourOS. I've run `prisma generate` and tried to reinstall `node_modules` as well.

> Installing via `pnpm` and using `import { PrismaClient } from '@prisma/client';` the typescript server states:
> 
> > Cannot resolve symbol 'PrismaClient'
> 
> I've run `pnpx prisma generate` which created `node_modules/.prisma/client`; still it's not picked up for some reason.

I dont't know if it's the Operating System or the Package Manager, I've to use `npm` instead of `pnpm` everytime I use Prisma. With a TSServer Restart, It does the work.

**Comment by pgiovanni** [comment]
Try updating prisma. There apparently was a new major version update.

**Comment by tjmgregory** [comment]
Also facing the exact same issue with pnpm and prisma. The `node_modules/.prisma` dependency is generated correctly, but what's happening is `@prisma/client` points to `node_modules/.pnpm/@prisma+client@3.15.2_prisma@3.15.2/node_modules/@prisma/client/index.d.ts` - so the nested dependency approach of pnpm to avoid version conflicts is getting in the way.

**Comment by SooditK** [comment]
> Also facing the exact same issue with pnpm and prisma. The `node_modules/.prisma` dependency is generated correctly, but what's happening is `@prisma/client` points to `node_modules/.pnpm/@prisma+client@3.15.2_prisma@3.15.2/node_modules/@prisma/client/index.d.ts` - so the nested dependency approach of pnpm to avoid version conflicts is getting in the way.
> 
> Edit: Was using pnpm 7.5.2, upgrading to pnpm 7.8.0, deleting `node_modules` and running `PRISMA_SKIP_POSTINSTALL_GENERATE=true p install` fixed it for me. Which of those steps did the trick though shrug

As you mentioned, Sir, I updated pnpm to `7.8.0` and deleted the `node_modules`
ran, `PRISMA_SKIP_POSTINSTALL_GENERATE=true pnpm install`
This thing didn't worked for me.
I created a new project to test this out, But still the same issue occurred.

**Comment by thasmo** [comment]
> Edit: Was using pnpm 7.5.2, upgrading to pnpm 7.8.0, deleting node_modules and running PRISMA_SKIP_POSTINSTALL_GENERATE=true p install fixed it for me. Which of those steps did the trick though 🤷

Did not fix it for me either.

I've also set this in the project's `.npmrc` file:
```ini
node-linker=hoisted
symlink=false
package-import-method=copy
```
But even that didn't help.

**Comment by irg1008** [comment]
So, do we know something about this? Still happening, I don't have any types for prisma client. It works when exporting the client from the package base directory. Stops working when exporting from src. I am starting to wonder what the point of pnpm is really

**Comment by millsp** [comment]
Hey @irg1008, could you provide us with a simple reproduction?

**Comment by irg1008** [comment]
Sure,

I have a pnpm monorepo with turborepo.
My prisma schema output is in a "database" package:

Custom client output:
```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/.prisma/client" // We need to export the client to the root for production and to pnpm virtual store for development
}
```

So when I disable the custom output, the prisma client is built out to the .pnpm virtual store, and as so it works on both dev and prod in apps "database" is dependency of.

The issue is that when doing this, I am missing typing on dev. This happens because the TS server links to the package "database" (without generated prisma client) even when it actually is importing it from the virtual store.

Project tree:
- node_modules (root)
  - .pnpm
    - .prisma 
    > (default prisma client output). (Works when exporting here, no typing)
- apps
  - server (links types to database, consumes from virtual store)
- packages
  - database
    - node_modules (exporting here adds typings but prod fails)
    - prisma/schema

The solution to have both the correct build link and typing it's to generate the clients in both places.

This causes and immediate problem when updating the schema.You have to generate the client two times, etc etc

We can solve this if we automatically output the schema to both node_modules (root and package).

Or maybe I am missing some settings with pnpm.

Any help would be great!

**Comment by irg1008** [comment]
A basic fix is to point prisma client output to root node_modules like:

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../../../node_modules/.prisma/client" // Root of the monorepo
}
```

This works when building and in dev mode.

I see problems with this approach while deploying the app as a separate project and not as a monorepo; schema would point to a non existant folder

Additional info (.pnpm):
```properties
auto-install-peers = true
enable-pre-post-scripts=true
public-hoist-pattern[]=*prisma*
```

**Comment by ARMATAV** [comment]
Same issue here - it's searching for it in the wrong location

**Comment by millsp** [comment]
@ARMATAV @irg1008 @SooditK @pgiovanni @thasmo

Are you by any chance using `preserveSymlinks`?
I confirmed that this is causing issues with Prisma Client  and `pnpm`, setting it to `false` prevents type issues.

Have you tried to restart VSCode or the TS Server?
Some users have reported that after being generate, VSCode did not pick up the new generated types.

There are many issues interleaved, and so far we know my two mentions just above are things we need to fix.

Did any of these help? If not, could you please provide us with a small reproduction? We are not able to reproduce the issues mentioned in the comments, so we need your help :pray:  I'd appreciate if you could submit us some code.

**Comment by fdj0429** [comment]
This is how install works for me:

set NODE_OPTIONS="--preserve-symlinks"
pnpm install        // will emit error, no worry continue with next step
cd packages/hoppscotch-backend
rm -rf dist && pnpm prisma generate && pnpm install
cd -
pnpm install

**Comment by Chandraprakash-Darji** [comment]
> A basic fix is to point prisma client output to root node_modules like:
> 
> ```prisma
> generator client {
>   provider = "prisma-client-js"
>   output   = "../../../node_modules/.prisma/client" // Root of the monorepo
> }
> ```
> 
> This works when building and in dev mode.
> 
> I see problems with this approach while deploying the app as a separate project and not as a monorepo; schema would point to a non existant folder
> 
> Additional info (.pnpm):
> 
> ```ini
> auto-install-peers = true
> enable-pre-post-scripts=true
> public-hoist-pattern[]=*prisma*
> ```

It's been one year have you got the solution?

**Comment by cellulosa** [comment]
Anyone found a solution? The steps provided by [Prisma](https://www.prisma.io/docs/guides/turborepo) and [Turborepo](https://turbo.build/repo/docs/guides/tools/prisma) do not seem to work for me...

**Comment by Jjqcoder** [comment]
`node version`:`20.19.1`
`pnpm version`:`10.11.0`
my `package.json`:
```json
{
    "name": "my-home-server-express-ts",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "dev": "ts-node-dev --respawn src/app.ts",
        "build": "rimraf dist && tsc",
        "prod": "npm run build && pm2-runtime start ecosystem.config.js"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "packageManager": "pnpm@10.11.0",
    "dependencies": {
        "@prisma/client": "^6.8.2",
        "express": "^5.1.0",
        "pm2": "^6.0.6"
    },
    "devDependencies": {
        "@types/express": "^5.0.2",
        "@types/node": "^22.15.21",
        "prisma": "^6.8.2",
        "rimraf": "^6.0.1",
        "ts-node-dev": "^2.0.0",
        "typescript": "^5.8.3"
    }
}

```

I had the same problem at the beginning:

![Image](https://github.com/user-attachments/assets/945d6081-0406-4ea5-9cea-67bf9d8d65fd)

![Image](https://github.com/user-attachments/assets/47645605-14c2-4a4b-a079-941b3ddcd949)

However, after I changed the import method of PrismaClient, the error disappeared and the database could successfully obtain the data

As shown in the following figure, in the file generated by prisma (generated/prisma/index), there is an export of PrismaClient

![Image](https://github.com/user-attachments/assets/4d736120-e9ff-48cf-bfe5-f67c7bf1957c)
