### ISSUE TITLE
Code first Prisma schema API

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#1396]
Ideas for implementation of the code first part of https://github.com/prisma/prisma2/issues/227

**Comment by iddan** [comment]
Hey, what is the status of this issue? Is there a beta code that we can play with already or is it spec only?

**Comment by iddan** [comment]
In the midtime, we released a library implementing the proposed AST and code generator: https://github.com/amplication/prisma-schema-dsl

**Comment by matthewmueller** [comment]
Closing in favor of #227 since that has a lot more discussion on the topic.
