### ISSUE TITLE
List fields default to null instead of []

### ISSUE THREAD

**Issue by seanemmer** [prisma/prisma#13986]
### Bug description

When creating a new record with a list field, its value defaults to null instead of [] (or {} in PostgreSQL

### How to reproduce

DB: SQL
Prisma: Latest

Schema:

```
User {
  id: ID  @id
  names: String[]
}
```

In code:

`await prisma.user.create({data:{id: '123'}})`

This user will have the names field set to null instead of []

### Expected behavior

The list field should be set to []

### Prisma information

Demo schema listed above

### Environment & setup

Postgresql v14

### Prisma Version

3.13.0

**Comment by jkomyno** [comment]
Closing as @Weakky's answer solves the problem.

**Comment by seanemmer** [comment]
New default feature looks like the solution.  Thanks!
