### ISSUE TITLE
Allow developers to define custom types to validate JSON fields

### ISSUE THREAD

**Issue by Mr-M1M3** [prisma/prisma#13998]
## Problem
Currently prisma doesn't validate JSON fields, It would be better if developers could create custom types to validate JSON.

## Suggested solution
A new block can be introduced to define custom type. Like,
```prisma
type Media{
name String
since Int
}
```
Then, a new directive can be introduced to bind a JSON field with the type.
```prisma
model User{
name String
email String @unique
Pass String
social_media JSON @type(Media) // Could be an array of Media too
}
```

## Alternatives

The only alternative I con think of now is to create a custom validator to validate before injecting data to db

**Comment by JeromeDeLeon** [comment]
I tried it but it is only available for MongoDB, how would we do it for a relational database?
![image](https://user-images.githubusercontent.com/32805276/175774925-91fc99e7-8d26-4a8e-8245-00cf727a18e7.png)

**Comment by JeromeDeLeon** [comment]
Although there seems to be already an open [issue](https://github.com/prisma/prisma/issues/3219) for this

**Comment by Mr-M1M3** [comment]
So, The solution is to use composite types!! I'm using mongodb and hopefully, I won't face any problem. Thanks, I'm gonna close this issue..
