### ISSUE TITLE
Create CI worker without a proper `openssl` or `libc` installation to improve snapshot testing suite

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#14017]
Currently, we're unable to easily reproduce errors that only emerge in environments without version of `openssl` or `libc` that we support. The standard approach we take is to wait for users to report issues (which may simply be due to unclear error messages), spin up a VM droplet with flaky system libraries installations with @pantharshit00's help, reproduce the problem and try to fix it from there.

As we don't have such an environment accessible via CI, it's currently impossible to perform snapshot testing on the error messages we trigger in those situations. For instance, this resulted in https://github.com/prisma/prisma/pull/13736 getting merged without anyone noticing a missing space (`" "`) character after `"Details:"`.

![Screenshot 2022-06-27 at 12 55 40](https://user-images.githubusercontent.com/12381818/175928391-7202c993-90eb-484e-ac75-ff8a8a1b7a00.png)

## Proposed Solution

Here are two alternatives:

1. Create a dedicated CI worker that mirrors an improper `openssl` or `libc` installation (can this be done easily in Github Actions?)
2. Use a standard CI worker that opens an `ssh` connection to an existing VM droplet configured as above, and runs the test there (more convoluted and tricky to get right)

**Comment by jkomyno** [comment]
The simplest strategy would be to have a plain `linux:alpine` Docker image

**Comment by janpio** [comment]
We already have tests on Docker containers in ecosystem-tests, so this would fit in there as well I would say.
