### ISSUE TITLE
macOS 12 sometimes kills Node.js process when loading the QE library

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#14058]
When there's a fresh release that not a lot of people have run on their machines yet, macOS 12+ on Apple Silicon often kills the Node.js process when trying to load the library. This happens with dev builds all the time, and recently we started getting reports from people encountering it with public releases.

Logs in `/Applications/Utilities/Console.app` show it was killed because of "Invalid code signature".

When this happens, one can either:

* Sign the Query Engine with their own Apple Developer ID — this immediately fixes the issue locally.

  ```sh
  find . -name libquery_engine-darwin-arm64.dylib.node | xargs codesign -f -s '<YOUR NAME AS IN APPLE DEVELOPER ID CERT>'
  ```

  (for example, `find . -name libquery_engine-darwin-arm64.dylib.node | xargs codesign -f -s 'Oleksii Orlenko'`)

* Wait until the Query Engine hash is whitelisted by macOS Gatekeeper and the issue magically resolves itself. This usually takes up to a day.

* Try using the binary engine instead of the library. macOS is usually not as strict towards the standalone binary as it is towards a dynamic shared library loaded by the Node.js process. Perhaps also because Node.js binary itself is signed?

Ostensibly, this happens because we don't sign our binaries, and should be fixed by signing them with a valid Apple Developer ID.

---

Confirmed cases:

* https://github.com/prisma/prisma/issues/14057
* https://prisma-company.slack.com/archives/C016KUHB1R6/p1655233721657349
* https://prisma-company.slack.com/archives/CUXLS0Z6K/p1637144570062100?thread_ts=1637143821.061000&cid=CUXLS0Z6K

Suspected cases:

* https://www.reddit.com/r/node/comments/vj4atm/prisma_314_315_node_crash/

---

Some "keywords" to make this issue googleable and maybe gather more cases:

```
zsh: killed     npx prisma generate
```

```
zsh: killed     ts-node index.ts
```

```
zsh: killed     npm start
```

**Comment by aqrln** [comment]
More context:
* https://github.com/prisma/prisma/issues/12016#issuecomment-1050360310
* https://openradar.appspot.com/FB8914243

**Comment by janpio** [comment]
Per the Open Radar putting the engine file into a location that includes its version (either CLI or Engine should work) might avoid this problem as it seems to depend on being in the same location as a previous file.
