### ISSUE TITLE
Add mapped database field name in DMMF

### ISSUE THREAD

**Issue by dimaip** [prisma/prisma#14087]
## Problem

Original database field name is missing from DMMF for mapped fields.
E.g. a field `userId String @map("user") @db.ObjectId` would be represented in DMMF as
```
{
  name: 'userId',
  kind: 'scalar',
  isList: false,
  isRequired: true,
  isUnique: false,
  isId: false,
  isReadOnly: true,
  type: 'String',
  hasDefaultValue: false,
  isGenerated: false,
  isUpdatedAt: false
}
```
No mention of `user`, as you can see.

## Suggested solution

Add a property `dbName` and put the original @map'ed name there.

## Additional context

In my case I'm building a generator plugin that would take Prisma schema and generate $jsonSchema for Mongodb out of it. So I need original database field names.
There is already `dbName` for mapped collections, so omitting it for fields seems like an oversight to me.

**Comment by ruheni** [comment]
Hi 👋🏽

This issue seems similar to https://github.com/prisma/prisma/issues/3998. We're looking into this; however we can't give any timeline on how soon we'll ship this. 🙂

**Comment by dimaip** [comment]
Thanks for your response @ruheni!
Great that I'm not the only one who needs it and too bad it hasn't been fixed for so long, seems like trivial thing to fix.
Closing this as duplicate for now.
