### ISSUE TITLE
Import support for various data sources

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#1410]
[Importing data](#1299) into Graphcool requires two major steps:

1. transforming data to be imported into the normalized data format
2. uploading data to Graphcool

```
+--------------+                   +----------------+                 +------------+
| +--------------+                 |                |                 |            |
| |            | |                 |                |                 |            |
| | SQL        | |   transform     |      NDF       | chunked upload  |  Graphcool |
| | MongoDB    | | +----------->   |                | +-------------> |            |
| | JSON       | |                 |                |                 |            |
| |            | |                 |                |                 |            |
+--------------+ |                 +----------------+                 +------------+
  +--------------+
```

As of today, the `transform` step needs to be done manually by the developer. However, in the future, an **automatic transformation** from various data sources will be implemented for the Graphcool CLI's `graphcool import` command.

In this issue, you can keep track and vote of the different source mappers that will be available.

**To vote for a specific source mapper, just click on it in the poll below**:

[![](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/SQL)](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/SQL/vote)
[![](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/MongoDB)](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/MongoDB/vote)
[![](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/Firebase)](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/Firebase/vote)
[![](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/Scaphold)](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/Scaphold/vote)
[![](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/AWS%20AppSync)](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/AWS%20AppSync/vote)
[![](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/Realm)](https://api.gh-polls.com/poll/01C1N06Z4ZXDKGY1EDRGQKW49F/Realm/vote)

> The poll is powered by the awesome [GitHub polls](https://github.com/apex/gh-polls)

**Comment by RyuX51** [comment]
Has there ever something grown out of this?

**Comment by entrptaher** [comment]
This is such important feature and now I see this,
```
prisma export
Warning: The `prisma export` command will not be further developed in the future. Please use the native export features of your database for these workflows. 
    
More info here:
MySQL: https://dev.mysql.com/doc/refman/5.7/en/mysqlimport.html 
Postgres: https://www.postgresql.org/docs/10/app-pgrestore.html

Downloading nodes 1535ms
Downloading lists 120ms
Downloading relations 1349ms
Zipping export... ⡿
Zipping export 298ms

```

Does that mean we are close to the new import feature? :D
