### ISSUE TITLE
OpenSSL error message appearing while using query-engine has false positives

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#14104]
Currently, we print the error `It seems there is a problem with your OpenSSL installation!` even when the actual problem isn't related to `openssl`, but rather to executing an engine that either:
- hasn't been compiled to support `musl` (rather than `libc`), or
- hasn't been compiled to support the `aarch64` architecture on Linux (e.g., on a Docker container), or
- a combination thereof.

See [this comment](https://github.com/prisma/prisma/issues/14043#issuecomment-1172487886) by @janpio.

## Example 1 (wrong, false positive)

```
#21 2.546 Error: Get Config: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
#21 2.546 Details: Unable to require(`/app/node_modules/.pnpm/prisma@4.0.0/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node`)
#21 2.546  Error relocating /app/node_modules/.pnpm/prisma@4.0.0/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node: __res_init: symbol not found
```

## Example 2 (right)

```
Error: Get Config: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
Details: Unable to require(`/home/florian/zac-management/node_modules/.pnpm/prisma@4.0.0/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`)
 libssl.so.1.1: cannot open shared object file: No such file or directory
```

## Proposed solution

- Look for the `libssl` string in [here](https://github.com/prisma/prisma/blob/8e90f8a1ca12f9b596f92bae811d9d92266aab7a/packages/internals/src/engine-commands/queryEngineCommons.ts#L82-L88), rather than looking for `openssl`
- As a fallback, if we find the `Unable to require` string, we might emit an appropriate suggestion, like `It seems that the current architecture $architecture is not supported, or that libc is missing.` or something of the sort.

**Comment by kaykhan** [comment]
@jkomyno Im having some issues with this now and struggling to understand waht is the correct solution. https://github.com/prisma/prisma/discussions/14356
