### ISSUE TITLE
Add MindsDB datasource

### ISSUE THREAD

**Issue by ZoranPandovski** [prisma/prisma#14151]
## Problem

Add support to [MindsDB](https://github.com/mindsdb/mindsdb) open source in-database Machine Learning platform. https://github.com/mindsdb/mindsdb/issues/2361

## Suggested solution

MindsDB provides MySQL API so it will be quite simple to re-use the MySQL data source(which may already work by default).

**Comment by pimeys** [comment]
Is the information catalog the same too? It's never that easy even if the protocol is the same. Good first step would be to add a GitHub action that runs all our tests against MindsDB and sees if any tests fail.

**Comment by janpio** [comment]
Here is some documentation on what I think is the SQL API @ZoranPandovski mentioned. That does not look like actually having the information we would need unfortunately (like the proper information_schema).
At the same time, it seems that MindsDB can use MySQL/MariaDB as a backing storage: https://mariadb.com/kb/en/machine-learning-with-mindsdb/ We could probably interact with that database directly. 

A good test if Prisma will work with a MySQL API is to create a new project, run `prisma db pull` to get the current schema (which needs to exist of course), then switch to a different, empty database and run `prisma db push` to migrate the now existing Prisma schema file. If that works, it should indeed be simple enough to run the complete test suite and confirm full support.

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
