### ISSUE TITLE
db error: ERROR: cannot drop view geography_columns because extension postgis requires it

### ISSUE THREAD

**Issue by capaj** [prisma/prisma#14182]
### Bug description

this might have been reported here already #7764, but it's definitely still failing even on 4.0.0

```
Error: P3016

The fallback method for database resets failed, meaning Migrate could not clean up the database entirely. Original error: 
db error: ERROR: cannot drop view geography_columns because extension postgis requires it
HINT: You can drop extension postgis instead.
   0: sql_migration_connector::best_effort_reset
             at migration-engine/connectors/sql-migration-connector/src/lib.rs:288
   1: migration_core::state::Reset
             at migration-engine/core/src/state.rs:341
```

### How to reproduce

1. have postgres with PostGis enabled
2. Run prisma migrate dev

### Expected behavior

migrates

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: 18.4.0

### Prisma Version

```
4.0.0
```

**Comment by Kalo0m** [comment]
related to this issue, it seems that postgis has also raster_columns and raster_overviews

```
Error: P3016

The fallback method for database resets failed, meaning Migrate could not clean up the database entirely. Original error: 
db error: ERROR: must be owner of view raster_columns
   0: sql_migration_connector::best_effort_reset
             at migration-engine/connectors/sql-migration-connector/src/lib.rs:290
   1: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:250
``` 

## How to reproduce

 - have postgres with PostGis enabled
 - Run prisma migrate dev

## Expected behavior

migrates

## Prisma information

## Environment & setup

OS: MacOs
Database: PostgreSQL
Node.js version: 14.7.0

## Prisma version 

`4.3.1`
