### ISSUE TITLE
Error: [introspection-engine/connectors/sql-introspection-connector/src/re_introspection.rs:486:14] Could not find relation field employees on model Record. 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#14206]
https://prisma-errors.netlify.app/report/14113

**Comment by jkomyno** [comment]
Another example: https://prisma-errors.netlify.app/report/14261

**Comment by tomhoule** [comment]
New occurrence in error reporting on 4.3.1: https://prisma-errors.netlify.app/report/14338

Maybe something to do with relation mode prisma, based on this.

**Comment by pimeys** [comment]
This breaks on 4.0.0 (and 4.3.1) for all the given error reports. Does not break anymore with 4.7.0.

All these were fixed in the big introspection refactor.

**Comment by pimeys** [comment]
Fixed in commit [bffd935029e462592819b33a080e8f8953b58acb](https://github.com/prisma/prisma-engines/commit/bffd935029e462592819b33a080e8f8953b58acb) and version 4.6.0.
