### ISSUE TITLE
doing introspection on a SQL Server 2018 DB - for Dynamic GP get the following error.

### ISSUE THREAD

**Issue by briamib** [prisma/prisma#14200]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v16.14.0           | 
| Prisma CLI  | 4.0.0              | 
| Engine      | da41d2bb3406da22087b849f0e911199ba4fbf11| 

## Error
```
Error: [libs/sql-schema-describer/src/mssql.rs:338:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: ` create default dbo.GPS_INT AS 0    `"
```

**Comment by pimeys** [comment]
Hey. This is a bug we see sometimes in our error reporting backend. I'm the author of Prisma's SQL Server functionality, and I haven't found a way to reproduce this issue. Could you describe the steps how to create a schema that gets our introspection to crash in the following way? Would be really cool.

**Comment by briamib** [comment]
I don't know why my replay didn't make it to the portal.

This is a SQL Server as stated:

connection string : `"DB_SQL_URL2=sqlserver://X.X.X.80:1433;database=DYNAMICS;schema=dbo;user=REMOVED;password=REMOVEDtrustServerCertificate=true;encrypt=true;`

It fails right at the SQL Errors table for GP - I have attached that table for your review.
![Screen Shot 2022-07-07 at 4 22 12 PM](https://user-images.githubusercontent.com/105324234/177875357-2121a689-ad36-4e5a-be69-dc260324a0ac.png)

We just ran prisma db pull.

**Comment by briamib** [comment]
We are connecting to a Microsoft SQL Server with the following connection string (removed ip address username and password) - using Prisma Client:
DB_SQL_URL2=sqlserver://X.X.X.X:1433;database=DYNAMICS;schema=dbo;user=;password=";trustServerCertificate=true;encrypt=true;

We then simply run prisma db pull.

The table that causes the crash I took a screen shot - hope this helps you and all of us.

It would be very beneficial if you guys started to allow multiple schemas on the same db pull.  We often run into situations with legacy applications or large enterprise applications have differing schema's in the same DB - we connect to many different data sources.

Thanks in advance…

Chris Burd
Maxus Capital Group, LLC
________________________________

**Comment by janpio** [comment]
> It would be very beneficial if you guys started to allow multiple schemas on the same db pull. We often run into situations with legacy applications or large enterprise applications have differing schema's in the same DB - we connect to many different data sources.

This should be right up your alley then: https://github.com/prisma/prisma/issues/1122#issuecomment-1231773471

**Comment by janpio** [comment]
This should be fixed via https://github.com/prisma/prisma-engines/pull/4884, which will be included in the next release.
