### ISSUE TITLE
Only reachable with String types.

### ISSUE THREAD

**Issue by shtse8** [prisma/prisma#14239]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.16.0           | 
| OS              | windows            |
| Prisma Client   | 4.0.0              |
| Query Engine    | da41d2bb3406da22087b849f0e911199ba4fbf11|
| Database        | mongodb            |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from D:\project\.env
prisma:tryLoadEnv Environment variables loaded from D:\project\.env
prisma:client dirname D:\project\node_modules\.prisma\client
prisma:client relativePath ..\..\..
prisma:client cwd D:\themud
prisma:client clientVersion: 4.0.0
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine:loader Searching for Query Engine Library in D:\project\node_modules\.prisma\client
prisma:client:libraryEngine:loader loadEngine using D:\project\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by pimeys** [comment]
Could you maybe open up a bit what kind of data model you're using here. I see a query, but how did you call the client to trigger this panic. Stacktrace is missing, so it's very hard to locate the point where the client crashed.

**Comment by shtse8** [comment]
In vue, development mode, prisma needs to run in worker thread. while hot reload, the thread will be killed and cause prisma close suddenly, the node will crash. There is no solution to disconnect gracefully on vue and nuxt config.

**Comment by Weakky** [comment]
Hey @shtse8,

Thank you for the update. Is there any way you could provide us with your Prisma Schema and possibly a query that led to this error?

I understand vue's dev mode might interfere with Prisma but it's unlikely that this error comes from the thread crashing.

Thank you 🙏

**Comment by jharrell** [comment]
Hi again @shtse8 

Following up 😊 would you mind providing a prisma schema and query that causes this issue? We're unable to reproduce on our end. 

Thanks!
