### ISSUE TITLE
findUnique findFirst functions return non-nullable types

### ISSUE THREAD

**Issue by yanmarinich** [prisma/prisma#14243]
### Bug description

function findUnique returns non-nullable type

<img width="654" alt="Screenshot 2022-07-11 at 00 35 18" src="https://user-images.githubusercontent.com/21159971/178161262-77ab82b3-611a-4492-a6c9-95d4b6f1124f.png">

the result is broken typechecking

<img width="672" alt="Screenshot 2022-07-11 at 00 35 45" src="https://user-images.githubusercontent.com/21159971/178161278-62acc041-aabf-46fd-9e9b-77eb0aeb5c97.png">

### How to reproduce

1. use function findUnique or findFirst with any model
2. the return type is non-nullable

### Expected behavior

return type is User | null

### Prisma information

    "@prisma/client": "^4.0.0",
    "prisma": "^4.0.0",

### Environment & setup

    "typescript": "^4.7.4"

### Prisma Version

```
prisma                  : 4.0.0
@prisma/client          : 4.0.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : da41d2bb3406da22087b849f0e911199ba4fbf11
Studio                  : 0.465.0
Preview Features        : mongoDb
```

**Comment by yanmarinich** [comment]
@sabinadams seems it worked too on my another project this one has the issue. the difference is this one has mongo instead of postgresql and a newer version of prisma, cloned one more time from the scratch installed deps and ran generate now getting the same type, 

<img width="644" alt="Screenshot 2022-07-18 at 11 52 01" src="https://user-images.githubusercontent.com/21159971/179467218-4f59e5df-2c59-4a26-9b17-8764bedd57c3.png">


I can give you the access to the repo. You can check it yourself just installing deps and run generate

**Comment by yume-chan** [comment]
Make sure you have `"strict": true` or at least `"strictNullChecks": true` in your tsconfig.json.

**Comment by yanmarinich** [comment]
> Make sure you have `"strict": true` or at least `"strictNullChecks": true` in your tsconfig.json.

You're brilliant, thank you, that was my mistake I had     "strictNullChecks": false I have no idea why it was there.
