### ISSUE TITLE
Passing env variable values on CloudFlare workers

### ISSUE THREAD

**Issue by 0x3user** [prisma/prisma#14241]
### Bug description

I'm trying to use Prisma + SvelteKit + Cloudflare. So for that, I'm following the steps about data proxy here https://www.prisma.io/docs/data-platform/data-proxy, and I'm stuck on how to pass the database_url to schema.prisma. It's working when using an hardcoded url in schema.prisma and it is also working with the regular prisma client. But when using the edge version of prisma client it simply can't read the env variables. 

If I can't use the .env how should I pass the database_url? 

Thanks (and sorry if it's a stupid question but I found no help in docs or other issues). 

### Environment & setup

- OS: Mac OS 
- Database: planescale
- Node.js version: 16.14

### Prisma Version

```
prisma                  : 4.0.0
@prisma/client          : 4.0.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : da41d2bb3406da22087b849f0e911199ba4fbf11
Studio                  : 0.465.0
```

**Comment by janpio** [comment]
You set the value as an environment variable in your environment. Depending on where you are deploying, you do that in different ways.

**Comment by 0x3user** [comment]
Thanks!

But I have the issue locally (using sveltekit). I guess env(xxx) should work in the schema file? (as it is when not using edge prisma)

**Comment by SevInf** [comment]
Hi @0x3user!
Here are our [docs on how to set datasource URL explicitly](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#programmatically-override-a-datasource-url), rather than with `.env` file. Would that work for you?

**Comment by Jolg42** [comment]
Here is an example https://github.com/prisma/ecosystem-tests/blob/dev/dataproxy/cloudflare-workers-module/src/index.ts

**Comment by SevInf** [comment]
Hi @0x3user did you have a chance to try the suggestions we posted here? 
If we won't here back from you, we'll have to close the issue as resolved.
Thank you!

**Comment by SevInf** [comment]
Hi @0x3user,
Since we haven't heard back from you, we'll consider the issue resolved. Feel free to comment if you have any update.
Thank you!
