### ISSUE TITLE
GIN Index Throws Error

### ISSUE THREAD

**Issue by steven-tey** [prisma/prisma#14247]
### Bug description

Great work on the recent [4.0 release](https://github.com/prisma/prisma/releases/tag/4.0.0)! I was trying out the Gin index for Postgres but it keeps throwing this error:

```
Error: Get DMMF: Schema parsing - Error while interacting with query-engine-node-api library
Error code: P1012
error: Error parsing attribute "@index": The `type` argument can only be `BTree` or `Hash` you provided: Gin.
```

### How to reproduce

Set this for your prisma.schema file:

```
generator client {
  provider        = "prisma-client-js"
}

datasource db {
  provider             = "postgresql"
  url                  = env("DATABASE_URL")
}

model Table {
  id                    String              @id
  arr                  String[]

  @@index([arr], type: Gin)
}
```

Run `npx prisma db push`

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
4.0.0
```

**Comment by pimeys** [comment]
I cannot reproduce this. Here's my reproduction repo: https://github.com/pimeys/reproduction-14247

Version 4.0.0, PostgreSQL. Can push, pull and run queries just fine. Are you sure your `prisma` command is of version 4.0.0?

**Comment by janpio** [comment]
(I think a recent Prisma CLI version would actually report its own version in the validation error, so @steven-tey either cut that off or is indeed using an older Prisma version somehow.)

**Comment by steven-tey** [comment]
Ahhh, silly me – my `prisma` version was `4.0.0` but my `@prisma/client` version was still at `3.12.0`. Upgrading that to `4.0.0` solved it! :) 

Thanks for the prompt response guys!!
