### ISSUE TITLE
Prisma doesn't validate composite attributes correctly

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma#14252]
### Bug description

Prisma plugin is suggesting to accept a bunch of attributes on a composite field:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/4272382/178268738-b97e1bd3-7137-493a-88b9-2c0b7eeea804.png">

I only see `@ignore` to maybe be vaild here, the rest don't work at all. There's no valid default or relation you can define, so that's stopping you from running Prisma with that model definition. However, validation allows you to run with `@unique` on the field, which will result in a panic in the DML code.

### How to reproduce

1. Defined model like this (using Mongo!):
```prisma

model A {
  id  String  @id @default(auto()) @map("_id") @db.ObjectId
  test Test @unique
}

type Test {
  test String
}
```

2. Run the query engine / client. It will panic:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libs/datamodel/connectors/dml/src/model.rs:544:66`
```

### Expected behavior

None of the attributes (potentially only `@ignore`) should be suggested by Prisma in the vscode plugin. Additionally, validation should prevent the code from panicing instead of accepting an invalid attribute.

### Prisma information

-

### Environment & setup

Database: MongoDB

### Prisma Version

Tested on latest Prisma 4.0+ main engine branch.

**Comment by tomhoule** [comment]
There are two parts to this:

- Validation. This must have been on a commit where we weren't validating that yet, this test shows we are correctly rejecting `@unique` on fields of composite types: https://github.com/prisma/prisma-engines/pull/3092/commits/24175c035eb33bd0f0243435ce7b59a1511a926b#diff-1af861525f65625425bb3cefbdf3c98e2a38f4badf1cd18b46154476879d5c48
- Wrong completion options. This is tracked in https://github.com/prisma/language-tools/issues/1198
