### ISSUE TITLE
Unable to record rolled back migration after down migration has been applied.

### ISSUE THREAD

**Issue by vkro** [prisma/prisma#14286]
### Bug description

Unable to record rolling back a migration after down migration has been applied.

Generating and applying the down migration as per documentation is accomplished with no issues, until I come to the `npx prisma migrate resolve --rolled-back 20220713234002_some_migration` step. When this is run to record that the migration has been rolled back, an error returns as follows:
```
Error: P3012

Migration `20220713234002_some_migration` cannot be rolled back because it is not in a failed state.
```

### Expected behavior

Migration should be recorded as rolled back.

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  output        = "client"
  binaryTargets = ["native", "linux-musl"]
}

generator erd {
  provider = "prisma-erd-generator"
  output = "./erd.png"
  theme = "default"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id         String      @id @default(uuid()) @map("id")
  email      String      @unique @map("email")
  firstName  String      @map("first_name")
  lastName   String      @map("last_name")
  createdAt  DateTime    @default(now()) @map("created_at")
  updatedAt  DateTime    @updatedAt @map("updated_at")
  @@map("users")
}
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14.19.0

### Prisma Version

```
prisma                  : 4.0.0
@prisma/client          : 3.15.2
```

**Comment by pantharshit00** [comment]
Hello,

Can you please share the documentation page that you were following in order to perform the rollback. Also, can you please share the exact steps that you ran for a minimal reproduction. 


If you had some previous migrations in the `migrations` folder, can you please also provide those. That will help in triaging this issue.

**Comment by vkro** [comment]
@pantharshit00 this was the documentation I was following. I posted in Prisma's Slack, and got a response letting me know that the process outlined in the docs was not correct, and will be updated. Specifically, that `prisma mibrate resolve --rolled-back` is to be used for failed migrations only. So if you are merely rolling back a migration that hasn't failed, it won't work. After running the `down.sql` script, the next steps are to essentially create a new up migration so that the migration history will match the new state of the database.

The response was as follows:

> After running the down migration, the next step would be reverting the changes you made in your Prisma schema and creating an up migration using migrate dev
This is because your Prisma schema, migration history (/prisma/migrations folder), and migrations table in the database (_prisma_migrations) are one step ahead of the database schema.

> The migrate resolve --rolled-back command works with failed migrations. In this case, there isn’t a migration failure.

> Thanks for bringing this up; we’ll update the docs to clarify what migrate resolve --rolled-back does and the Down Migrations guide. :slightly_smiling_face:
