### ISSUE TITLE
non-existent cursor user experience

### ISSUE THREAD

**Issue by OmG3r** [prisma/prisma#14283]
## Problem

Right now, If we provide a `cursor` that does not exist in the table (and the table contains records) Prisma returns `null` even when though there are elements after and before the cursor and a `take` was specified.

```
this.prismaService.brand.findMany({
    cursor: {
        id: body.cursor,
    },
    take: body.take ? body.take : DEFAULT_TAKE,
    include: {
        pdf: true,
        variants: true,
    },
    orderBy: {
        id: 'asc',
    },
})
```
## Suggested solution

Update the docs, specifically the [cursor-based pagination guide](https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination) to indicate that supplying a non-existent `cursor` will yield `null`.

## Alternatives

Another possible behavior is to return the closest next elements to the cursor. here is an example implementation using `where`.

```
this.prismaService.brand.findMany({
    where: {
        id: {
            ...(body.take < 0 && {
                lt: body.cursor,
            }),
            ...(body.take > 0 && {
                gt: body.cursor,
            }),
        },
    },
    take: body.take ? body.take : DEFAULT_TAKE,
    include: {
        pdf: true,
        variants: true,
    },
}),
```

## Additional context

None.

**Comment by YandiBanyuKarimaWaly** [comment]
I think just mentioning it in the docs is enough so developer know what to expect as they are writing their code. Clear documentation of current behavior should take priority before discussing further implementation detail IMHO.
