### ISSUE TITLE
Prisma migrate returns can't reach database server sometimes

### ISSUE THREAD

**Issue by lberaldodev** [prisma/prisma#14290]
### Bug description

im building my containers and executing the migrate command inside the nodejs container, and sometimes it works and sometimes it returns `Error: P1001: Can't reach database server at db: 3306`

![Captura de Tela 2022-07-13 às 20 27 06](https://user-images.githubusercontent.com/45186203/178853925-d71da56d-f9b2-4f6a-8c02-8ea5f19d4f09.png)

### How to reproduce

1. Build the containers
2. Access the server container
3. Run 'npx prisma migrate deploy --schema=./src/infra/database/prisma/schema.prisma'
4. See error Error: P1001 Can't reach database server at db: 3306 Please make sure your database server is running at db:3306

### Expected behavior

I want that it work always, returning the same messsage.
`
1 migration found in prisma/migrations
No pending migrations to apply.
`

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url = env("SERVER_DATABASE_URL")
}

model Peoples {
  id      Int      @id @default(autoincrement())
  name    String
}
```

### Environment & setup

- OS: Mac OS M1
- Database: Mysql 5.7
- Node.js version: v16.16.0

### Prisma Version

```
prisma                  : 4.0.0
@prisma/client          : 4.0.0
Current platform        : linux-arm64-openssl-1.1.x
Query Engine (Node-API) : libquery-engine da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/migration-engine-linux-arm64-openssl-1.1.x)
Introspection Engine    : introspection-core da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/introspection-engine-linux-arm64-openssl-1.1.x)
Format Binary           : prisma-fmt da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/prisma-fmt-linux-arm64-openssl-1.1.x)
Default Engines Hash    : da41d2bb3406da22087b849f0e911199ba4fbf11
Studio                  : 0.465.0
```

**Comment by janpio** [comment]
The output indicates that you might have 2 `?` in your connection string. In a query string only the first parameter is with a `?`, the second one (and additional) needs to be with `&`: `.../database?schema=public=connection_timeout=300`.

**Comment by lberaldodev** [comment]
@janpio I did the changes about the query string and it's working fine now! tks
