### ISSUE TITLE
You cannot define an index on fields with native type `@db.VarChar(Max)` of SQL Server

### ISSUE THREAD

**Issue by DVGY** [prisma/prisma#14314]
### Bug description

```
model User {
  id @default(autoincrement())
  notes @db.VarChar(Max)


 @@index([Notes], map:"nci_wi_User_099fasfa")

}
```

### How to reproduce

Just paste the below schema in the prisma.schema

### Prisma information

```
model Ula {
  id Int  @id( ) @default(autoincrement())
  Notes String @db.VarChar(Max)
  Name String @db.VarChar(255)


 @@index([Notes,Name], map:"nci_wi_Ula_009AFCDDFASDFAF")

}
```

### Environment & setup

- OS: Windows
- Database: MS SQL Server
- Node.js version: 14.17.3

### Prisma Version

```
4.0.0
```

**Comment by janpio** [comment]
Oh wow, I was not even aware that `@db.VarChar(Max)` is a thing. We support nice things 😆 

I can confirm the validation error:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model Ula {
  id    Int    @id() @default(autoincrement())
  Notes String @db.VarChar(Max)
  Name  String @db.VarChar(255)

  @@index([Notes, Name], map: "nci_wi_Ula_009AFCDDFASDFAF")
}
```

```
PS C:\Users\Jan\Documents\throwaway\foo> npx prisma validate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: Get DMMF: Schema parsing - Error while interacting with query-engine-node-api library
Error code: P1012
error: You cannot define an index on fields with native type `VarChar(Max)` of SQL Server.
  -->  schema.prisma:15
   | 
14 | 
15 |   @@index([Notes, Name], map: "nci_wi_Ula_009AFCDDFASDFAF")
   | 

Validation Error Count: 1

Prisma CLI Version : 4.0.0
```

I guess on SQL Server side there is no reason why this column should not be able to be used in an index?

**Comment by DVGY** [comment]
@janpio also I get this error for `@db.NVarChar(Max)`

**Comment by DVGY** [comment]
@jkomyno hey guys any update on this ?

**Comment by janpio** [comment]
The reported scenario is confirmed to happen as described.

It is unclear if you _should_ be able to create an index on a field of `@db.VarChar(Max)` though, as it seems that this is an explicit validation we added.

**Comment by janpio** [comment]
And indeed:
https://www.linkedin.com/pulse/sql-server-nvarchar-max-index-compliant-workaround-guillaume-diamant/
https://learn.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver15#column

> Columns that are of the large object (LOB) data types ntext, text, **varchar(max)**, nvarchar(max), varbinary(max), xml, or image can't be specified as key columns for an index.

So this is unfortunately a limitation of SQL Server that Prisma has correctly implemented. Sorry.
