### ISSUE TITLE
Pass pg client to Prisma client

### ISSUE THREAD

**Issue by nick-kang** [prisma/prisma#14339]
## Problem

We'd like to pass a custom pg client to Prisma client. Noticed that Prisma client has a dependency on `pg` https://github.com/prisma/prisma/blob/main/packages/client/package.json, but am not sure how feasible this feature request is.

We'd like to pass our own pg client because:
* we instrument pg client to capture AWS X-Ray metrics
* we use AWS RDS IAM Authentication, which requires us to dynamically generate our password. `pg` already has support for passing a function to the `password` parameter.

## Suggested solution

Pass a pg client when instantiating Prisma client.

## Alternatives

None.

**Comment by aqrln** [comment]
We're not using `pg` in the Prisma Client. It is only used on our tests to setup databases. The communication with the databases happens in the [Query Engine](https://github.com/prisma/prisma-engines) written in Rust.
