### ISSUE TITLE
Unable to Nullify a many-to-one and Update a one-to-one at the Same Time

### ISSUE THREAD

**Issue by YaakovR** [prisma/prisma#14330]
### Bug description

I'd like to nullify a many-to-one relationship and update a one-to-one relationship in the same query.

Running the query below, produces the following error:
```Error: Unknown arg `team_id` in data.team_id for type PersonUpdateInput. Did you mean `team`?```

I'm unable to update `team` using `connect` due to it being a nullable field.

### How to reproduce

```
await prisma.person.update({
  where: {
    id: 1,
  },
  data: {
    team_id: null,
    personData: {
      update: {
        favorite_color: 'Purple',
      },
    },
  },
});
```

### Prisma information

```
model Person {
  id         Int    @id
  first_name String
  last_name  String
  team_id    Int?

  personData PersonData?
  team       Team?       @relation(fields: [team_id], references: [id])
}

model PersonData {
  person_id      Int    @id
  favorite_color String

  person Person @relation(fields: [person_id], references: [id])
}

model Team {
  id   Int    @id
  name String

  people Person[]
}
```

### Environment & setup

- OS: Ubuntu
- Database: SQL Server
- Node.js version: 18

### Prisma Version

```
3.15.2
```

**Comment by aqrln** [comment]
Would [`disconnect`](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#disconnect) work for you here?

**Comment by YaakovR** [comment]
Using `disconnect` has been working all along. My bad...
Thank you for looking into this!
