### ISSUE TITLE
Add duration to mongo logging

### ISSUE THREAD

**Issue by garrensmith** [prisma/prisma#14378]
### Bug description

With this code
```js
 const prisma = newPrismaClient({
        log: [
          {
            emit: 'event',
            level: 'info',
          },
          {
            emit: 'event',
            level: 'query',
          },
        ],
      })
prisma.$on('query', onQuery)
 await prisma.user.findMany()
```
when using mongo I get following event:
```js
{
      is_query: true,
      item_type: 'query',
      level: 'debug',
      module_path: 'mongodb_query_connector::query',
      params: '[]',
      query: 'db.User.aggregate([ { $project: { _id: 1, }, }, ])'
}
```
where with sqlite or any other provider I get someting along these lines:
```js
{
      duration_ms: 0,
      is_query: true,
      item_type: 'query',
      level: 'debug',
      module_path: 'quaint::connector::metrics',
      params: '[-1,0]',
      query: 'SELECT `main`.`User`.`id` FROM `main`.`User` WHERE 1=1 LIMIT ? OFFSET ?',
      result: 'success'
}
```

### Expected behavior

MongoDB logs should include the duration in the log event. 

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by Jolg42** [comment]
Should we add a test in prisma/prisma about MongoDB logs? I'm not sure if we have one.

**Comment by miguelff** [comment]
Some are being added to prisma in https://github.com/prisma/prisma/pull/15957

On the engine side, we have a couple of integration tests covering that logs are indeed being generated and that fields contain both a duration and a query string. Then we have a complete unit test suite for the log traces' query strings. I'm in favor of adding more tests that contribute to the client's robustness, but I will defer to @danstarns on the decision of which and how many of them would constitute _good enough_ coverage.

**Comment by danstarns** [comment]
Coverage added in this PR & commit: https://github.com/prisma/prisma/pull/15957/commits/65cdef6b3be0ce0e056cad77c81fa7d9f5bf62e4
