### ISSUE TITLE
Values stored in filed of type @db.timestamz are always converted back to GMT time when retrived from the db. (PostgresSQL)

### ISSUE THREAD

**Issue by angelinimattia** [prisma/prisma#14406]
### Bug description

I have a similar issue , but I can say something more detailed, however I tested only with postgress.
Prisma is correctly storing the dates with the timestamps inside PostgreSQL ( I have checked with a DB utility), however when they are loaded they are converted back in GMT+0:
What I have on postgress: 2022-07-18 15:38:14.804 +0300
What I revive from prisma : 2022-07-18T12:38:14.804Z
Field type:  @db.Timestamptz(5)
I have also a complex rawquery, and if I use it directly on postgress the date are keep as they are in the db, while if I use prisma.rawquery() they are converted back.

### How to reproduce

1.Generate a table with a field of type: @db.timestampz
2. store some timestamp with offsets (also manually directly on the db) (e.g. 2022-07-18 15:38:14.804 +0300)
3. request the raw with the offset date in any way (findMany or all or with an ID)

### Expected behavior

I expect to obtain the original dates with the ofset and not the GMT converted one 

### Environment & setup

- OS: Ubuntu 20.xx
- Database:  PostgreSQL
- Node.js version: v14.19.1

### Prisma Version

```
prisma                  : 4.1.0
@prisma/client          : 4.1.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.467.0
Done in 1.11s.
```

**Comment by garrensmith** [comment]
@angelinimattia sadly is a javascript issue. Javascript dates does not keep timezone information.

**Comment by angelinimattia** [comment]
I don't think this is the issue or how do you explain the fact that when I store the dates using the prisma client for NodeJs, the dates are stored with the correct timezone.
That said, then would be possible to specify custom data type so tell prisma to use to grant users more the ability to treat the loaded data as they seem fit?
