### ISSUE TITLE
Mongodb prisma pull crash

### ISSUE THREAD

**Issue by filipeGuerreiro** [prisma/prisma#14410]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull --force --schema [redacted]`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-3.0.x| 
| Node        | v16.16.0           | 
| Prisma CLI  | 3.14.0             | 
| Engine      | 2b0c12756921c891fec4f68d9444e18c7d5d4a6a| 

## Error
```
Error: [introspection-engine/connectors/mongodb-introspection-connector/src/sampler/statistics/indices.rs:169:71] called `Option::unwrap()` on a `None` value
```

**Comment by janpio** [comment]
Can you share the structure of your MongoDB database with us? We would optimally want to be able to reproduce this ourselves to then fix it - but need your help for that. (We can accept files privately via schemas@prisma.io)
Does this only happen when you supply an existing schema?

**Comment by filipeGuerreiro** [comment]
Alright, will send it over.

> Does this only happen when you supply an existing schema?

Happens with or without a schema

**Comment by tomhoule** [comment]
Does this still happen in recent versions? (latest, ideally). I think we fixed that.

**Comment by filipeGuerreiro** [comment]
> Does this still happen in recent versions? (latest, ideally). I think we fixed that.

Right, upgraded (was using prisma as a subdependency of redwoodjs).
The error no longer occurs on the latest (4.1.1 as of now).

Thanks for the help!
