### ISSUE TITLE
Prisma 4.1.0 (SQLite) - Cannot read properties of undefined (reading 'unref')

### ISSUE THREAD

**Issue by fernandes-dev** [prisma/prisma#14429]
### Bug description

I've executed my tests using prisma and sqlite3 and received the following error:

`"TypeError: Cannot read properties of undefined (reading 'unref')"`

The error occurring in `my-project\node_modules\@prisma\client\sqlite\runtime\index.js:8542:30)`

### How i Solved it
I've added the temporally solution with this code: 

**BEFORE:**

<details>

![image](https://user-images.githubusercontent.com/44908695/180302471-50676846-db07-40ca-8b68-9854458ce405.png)

</details>

**AFTER**

<details>

![image](https://user-images.githubusercontent.com/44908695/180302303-d08ed03b-961b-4ac1-bdc9-4a5914ea713d.png)

</details>

### How to reproduce

1. Import prisma
2. Create a new instance
3. Execute any query in database

### Prisma information

**Prisma Schema**

```
generator client {
  provider   = "prisma-client-js"
  engineType = "binary"
  output     = "../../node_modules/@prisma/client/sqlite"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL_SQLITE")
}

model surveys {
  id                 String      @id
  original_survey_id String      @unique(map: "UQ_0934c8326bd92522d5f99be15c8")
  title              String
  language           String
  category           String
  question_count     Int
  response_count     Int
  page_count         Int
  date_created       DateTime    @default(now())
  date_modified      DateTime    @default(now())
  nickname           String?
  file_name          String?
  survey_link        String?     @unique(map: "surveys_survey_link_uindex")
  payment_file       String?
}

```

My Class

<details>

![image](https://user-images.githubusercontent.com/44908695/180304197-a0eb6e82-94dc-4fd1-8597-94fe21c6cd25.png)

</details>

### Environment & setup

- OS: Windows
- Database: SQLite
- Node.js version: 14.19.0

### Prisma Version

**dependencies**
```json
"@prisma/client": "^4.1.0"

```

devDependencies

```json
"prisma": "^4.1.0"
```

**Comment by garrensmith** [comment]
@fernandes-dev thanks for reporting this. Could you provide us with a reproduction so we can test this further?

**Comment by mellson** [comment]
@garrensmith I experienced the same problem with 4.1.5, but it's gone in 4.2.1 - thanks 👍🏻
