### ISSUE TITLE
Query engine library for current platform "debian-openssl-1.1.x" could not be found

### ISSUE THREAD

**Issue by gspasov** [prisma/prisma#14434]
### Bug description

When running function from prisma I get the following error:

```
  Query engine library for current platform "debian-openssl-1.1.x" could not be found.
You incorrectly pinned it to debian-openssl-1.1.x

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/home/gspasov/personal-projects/docsfill/apps/server/dist/libquery_engine-debian-openssl-1.1.x.so.node")

Searched Locations:

  /home/gspasov/personal-projects/docsfill/.prisma/client
  /home/gspasov/personal-projects/docsfill/node_modules/@prisma/client
  /home/gspasov/personal-projects/docsfill/apps/server
  /home/gspasov/personal-projects/docsfill/apps/server/dist
  /home/gspasov/personal-projects/docsfill/apps/server/prisma
  /tmp/prisma-engines
  /home/gspasov/personal-projects/docsfill/apps/server/dist


To solve this problem, add the platform "debian-openssl-1.1.x" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file
```

I have tried to add ` "debian-openssl-1.1.x"` to `binaryTargets` but this doesn't change anything.

The interesting bit is that this was working few days ago, yet I haven't done anything interesting to expect such behavior. 
I tried updating `@prisma/client` and `prisma` to the latest version, that didn't help either.

I believe the issue stems from the fact that it picks the wrong location to look for the query language:
```
(Prisma Client looked in "/home/user/project-directory/apps/server/dist/libquery_engine-debian-openssl-1.1.x.so.node")

Searched Locations:

/home/user/project-directory/.prisma/client
/home/user/project-directory/node_modules/@prisma/client
/home/user/project-directory/apps/server
/home/user/project-directory/apps/server/dist
/home/user/project-directory/apps/server/prisma
/tmp/prisma-engines
/home/user/project-directory/apps/server/dist
```

From what I looked, the correct location should be `/home/user/project-directory/apps/server/prisma`, because there I have the engine.
Another place would be `/home/user/project-directory/node_modules/@prisma/engines`, but it doesn't even look there.

The project is setup as a monorepo.

### NOTE
If I copy the engine and paste it inside the `./dist` folder, everything is fine, yet this is not a solution for me.

### How to reproduce

My setup is the following:
1. I have a typescript file that uses the prisma client
2. This client is then build to JavaScript via `esbuild` like so -> `esbuild index.ts --bundle --platform=node --target=node14 --outdir=dist`
3. I copy the `schema.prisma` to `./dist` folder as well in order for the build .js file in ./dist folder to locate the schema
4. I run `node dist/index.js`

### Expected behavior

To not have issues locating the engine library

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
...
```

### Environment & setup

- OS: `Ubuntu on WSL2`
- Database: `PostgreSQL`
- Node.js version: `v16.14.2`

### Prisma Version

This is the output to `prisma -v`:
```
prisma                  : 4.1.0
@prisma/client          : 4.1.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.467.0
```

**Comment by gspasov** [comment]
It seems like `esbuild` has some issues with some node features when you bundle your build:
```
There are many node-specific features that esbuild doesn't support while bundling such as __dirname, import.meta.url, fs.readFileSync
```

To fix my issue I just had to externalize the `@prisma` dependency like so:
```
esbuild index.ts --bundle --platform=node --target=node14 --external:../../node_modules/@prisma/* --outdir=dist
```

Yet it would've been nice if there was some heads up about this potential issue when using tools like `esbuild`.

**Comment by SevInf** [comment]
When bundling prisma, you need to ensure that engine files are also copied over to your output location. Check out [our docs](https://www.prisma.io/docs/concepts/components/prisma-client/module-bundlers#overview) on bundling.
