### ISSUE TITLE
Support for exclusive migrations / prevent migration if one is currently underway

### ISSUE THREAD

**Issue by rickbatka** [prisma/prisma#14454]
## Problem
My web server is the only thing capable of triggering a prisma migration (it has the source code, the migrations folder, and the DB connection credentials to the production database).

When I make changes that require a migration, I have a few options:
1. Connect my local dev machine to the production database and run the migration manually (not recommended).
2. Have my CI / CD pipeline runner run the migration right before deploying the code (this is ideal, but in my case impossible - I can't access the database from the wider internet).
3. Have my webserver app run any pending migrations when restarted (this is my current workaround).

I'm using approach 3 currently, because it's the most convenient for me and I understand the tradeoffs (I understand that releases that contain a migration will block while the migration is running).

**The problem**, though, is when I release to a cluster of many containers all running my app. My deployment pipeline can't guarantee that I release to exactly one replica, wait for the migration, then release to the rest.

I fear that if I release to more than one replica, they will all race to run "prisma migrate deploy" and the database will get into a bad state.

## Suggested solution

The most DevEx-friendly way I can envision is for `prisma migrate` to take a "distributed lock" on the migration (perhaps by using "upsert" to only take the lock if there are no other migrations running currently). 

When an agent runs "primsa migrate deploy", it should attempt to get the lock. If it can't, it should block until it can get the lock.
When it finally gets the lock (meaning, the previous migration is finished), it should attempt to run `prisma migrate deploy`, and release the lock when it succeeds (or rolls back).

This way, if two agents called `prisma migrate deploy` at roughly the same time, the first one would get the lock and do the migration. The second would wait until the first was done, attempt a deployment, and see from the migrations table that there are no outstanding migrations, and also succeed.

Crucially, all agents running `migrate deploy` will block until the DB is up to date, and all will finish the command with success, even though only one agent *actually* did the migration.

## Alternatives

It could be possible to run `prisma migrate deploy` in a mode such that it will immediately fail if there is currently a migration running. This way, the first replica to attempt the migration would get the lock, and all the others would fail (I, as the application developer, will then have to write code that causes the replicas to decide what to do on migration failure - in this case, retry after some timeout). 

## Additional context

I'd also be happy to code this feature into my server's startup logic. I'm 90% confident that the information I need is already there, but I don't know if the `_prisma_migrations` table is documented / guaranteed stable for public consumption.

If the `_prisma_migrations` table structure is stable, I _think_ I could just look for outstanding migrations (`SELECT id FROM _prisma_migrations WHERE started_at IS NOT NULL AND finished_at IS NULL AND rolled_back_at IS NULL`)

Is that query logic sound? Is it always safe to assume that if there is a migration that has started, but not finished or rolled back, that there is a migration currently running? Is the _prisma_migrations table logic stable and would it be wise for me to build application functionality that looks at it?

## Additional questions
Is there perhaps a more mature deployment methodology that I haven't considered? I suppose I could keep a "task runner" instance of my application live, but never send it web traffic. When I release, I could release to that app first, call the app, and wait for a success response. Then I would know the DB has been migrated, and could release to the fleet of web apps.

**Comment by janpio** [comment]
I think we already have that: https://www.prisma.io/docs/orm/prisma-migrate/workflows/development-and-production#advisory-locking

Please let us know if this does not satisfy your use case and leave a comment or open a new issue about that. Thanks!
