### ISSUE TITLE
Sort by distance

### ISSUE THREAD

**Issue by EslamADahshan** [prisma/prisma#14464]
## Problem
I wanna make a sort by nearest location using the place stored latitude and longitude & my current location

**Comment by AlaaElrifaie** [comment]
I think the only way to do it is using raw queries as Prisma still doesn’t support geospatial queries.

**Comment by janpio** [comment]
It will though: https://github.com/prisma/prisma/issues/2789 Please have a look at that issue and make sure to leave a 👍 and optimally a comment with your use case if it has not been considered yet. Thanks.
