### ISSUE TITLE
Pretty easy fix on Prisma Studio to view all columns.

### ISSUE THREAD

**Issue by stephyswe** [prisma/prisma#14489]
## Problem

If we have columns overlapping they are invisible and isn't scrollable.

## Suggested solution

By changing height in Prisma studio on the div above ag-root-wrapper we can view all columns.

## Alternatives

For now, you can do the following. 
Install a stylesheet customizer. One that is recommended on *superuser is Styler Extension. It's minimal and easy to use. Available for [Firefox ](https://addons.mozilla.org/en-US/firefox/addon/styler-pro/) and [Chrome / Brave](https://chrome.google.com/webstore/detail/styler/hbhkfnpodhdcaophahpkiflechaoddoi). 

*<https://superuser.com/questions/560539/how-can-i-force-my-css-styles-when-i-visit-a-website>
Install extension and simply add the following 

```css
html { background: transparent; }
#root {	display: block!important; }
```

![image](https://user-images.githubusercontent.com/20955623/180962320-7bb378f4-a0fd-42f9-89c6-6c9b273b5e1b.png)

end result will be:

![image](https://user-images.githubusercontent.com/20955623/180962551-ba46951c-0668-46db-a938-216713bc9a9e.png)

## Additional context

It's pretty self-explanatory

"Height: 100%" - No scrollbar available. 
![image](https://user-images.githubusercontent.com/20955623/180958108-e3a94890-e0ff-4bdd-bfb1-2b31b0d291d9.png)

"Height 93%" - Scrollbar.
![image](https://user-images.githubusercontent.com/20955623/180958239-75c9ba5a-a37d-4087-b48c-3f0d98ed8834.png)

**Comment by janpio** [comment]
This should already have been fixed in Prisma 4.1.1 - can you confirm @stephyswe?
