### ISSUE TITLE
Large package size when compiling for lambda

### ISSUE THREAD

**Issue by cam-slyp** [prisma/prisma#14485]
### Bug description

Hi There,

I'm looking at using Prisma in a lambda environment and have noticed the package size is around `250Mb` when using the following generator:
```
generator client {
    provider      = "prisma-client-js"
    binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

I'm using the following package.json and am installing using `npm ci --omit=dev` (have also tried `npm ci --production`)
```
"devDependencies": {
    "prisma": "^4.1.0",
    "typescript": "~4.3.0"
  },
  "dependencies": {
    "@prisma/client": "^4.1.0"
  }
```

Wanted to check that this is the intended package size, and if it is, whether there are any files I can manually delete to minimise the package size.

I came across [this article](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda#7-deploy-the-app) however we use AWS SAM and don't want to introduce webpack solely to support prisma.

Thanks in advance for your help

### How to reproduce

1. Create an npm package with the above dependencies
2. Use the prisma generator config above
3. Run `npm ci --omit=dev` to install production dependencies
4. The `node_modules` package will be > 150Mb

### Expected behavior

The `node_modules` package is small enough (preferably < 30Mb) to deploy in a lambda function without using layers

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14.9
- npm: 8.14

### Prisma Version

```
^4.1.0
```

**Comment by janpio** [comment]
By defining two binaryTargets, unless you are already running the build step on `rhel-openssl-1.0.x`, you are already making sure that you get double the engine files than necessary to run your Lambda function. Frameworks like Serverless Framework and similar ensure that only the required engine files are bundled and uploaded.

Additionally, 250MB still sounds to large for production only dependencies. Can you list the files that are being included?

**Comment by cam-slyp** [comment]
@janpio 

Here's the output of `ls -Ralh node_modules/` after running `npm ci --production` against a schema.prisma file of:
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["rhel-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```
The total size of `node_modules` is `231.9MB`

[modules.txt](https://github.com/prisma/prisma/files/9256417/modules.txt)

**Comment by millsp** [comment]
Ideally, if you only need the Prisma Client, you could generate to a custom location and just upload that. You can definitely discard `@prisma/engines`. The generated client will have a copy of the engine.

**Comment by Jolg42** [comment]
@cam-slyp  If you are using AWS Lambda only, you could do the following 
1. Create a zip script that only zips what's needed, for example
https://github.com/prisma/ecosystem-tests/blob/dev/platforms-serverless/lambda/zip.sh
2. Then upload the zip 
```
aws lambda update-function-code --function-name my-function --zip-file "fileb://lambda.zip"
```

Note: In our docs we mention how to remove these unneeded artifacts but only when using the serveless framework, I think we could improve that and mention how to do that when using AWS Lambda alone.

**Comment by janpio** [comment]
Today's release 4.8.0 has _significantly_ (average 50%, on some platforms even more) decreased the size of our engine files:
> **Improved serverless experience — smaller engines size**
>
> In this release, we have decreased the size of our engine files by an average of 50%. The size of the Query Engine used on Debian, with OpenSSL 3.0.x, for example, went from 39MB to 14MB. We will also remove some smaller engines to decrease the total size in future versions.
>
> Additionally, we have started optimizing how the Prisma schema is loaded in Prisma Client. You should notice a considerable improvement when executing the first query if you're working with a bigger schema with many models and relations.
>
> We will continue investing in this direction in the next releases and further improve the experience with Prisma and serverless environments.

https://github.com/prisma/prisma/releases/tag/4.8.0

We know we still have duplicated engine files in multiple locations, and that we are including too many of our engine files - but this was the obvious place to start and we are happy how significantly we could improve the situation already. Expect more updated like this in the coming releases from us.

**Comment by janpio** [comment]
As written before, we have reduced the size of our engines a lot and as far as we know, this solved this problem for most our user and their use cases. Hence I am closing this issue for now.

If you and your project are still having problems because of the remaining size of our engines, please open a new issue and describe your situation - we are happy to take a look and hopefully fix that. Thanks!
