### ISSUE TITLE
Primary key in model using a missing column

### ISSUE THREAD

**Issue by DavidJSykes** [prisma/prisma#14511]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v16.13.1           | 
| Prisma CLI  | 4.1.0              | 
| Engine      | 8d8414deb360336e4698a65aa45a1fbaf1ce13d8| 

## Error
```
Error: [libs/datamodel/connectors/dml/src/model.rs:494:29] Hi there! We've been seeing this error in our error reporting backend, but cannot reproduce it in our own tests. The problem is that we have a primary key in the model `CUSTOMER_BRAND_LINK` that uses the column `DATE_UPDATED` which we for some reason don't have in our internal representation. If you see this, could you please file an issue to https://github.com/prisma/prisma so we can discuss about fixing this. -- Your friendly prisma developers. 
```

**Comment by DavidJSykes** [comment]
If I can help you guys with this I will. We have a **DATE_UPDATED** column in another table called **CUSTOMER_BRAND_LINK_META** and this error suggests it was expecting to find it on **CUSTOMER_BRAND_LINK**. I see another missing column issue (#14462) where the column is on another table **Product_Category_Mapping** but is expected on **Product**. I'm just guessing that it's something to do with searching for table names or underscores.

**Comment by DavidJSykes** [comment]
**DATE_UPDATE** is also not a primary key on the table. It is however used in an index.

**Comment by jkomyno** [comment]
Bug confirmed, it's been reported [here](https://prisma-errors.netlify.app/report/14162) as well.

**Comment by jkomyno** [comment]
Hi, I have tried reproducing this issue [here](https://github.com/jkomyno/reprod-14462/actions/runs/2760155558) but I haven't had luck so far. Would please share a SQL dump of your database, and your `schema.prisma` file? We understand you may not feel comfortable sharing this private info in public, so another option would be sending those files privately to `schemas@prisma.io`. We can also sign NDAs if necessary.

Moreover, could you please describe how the database was created and/or update? For instance, did you start from an existing SQL database that you introspected and maybe later modified via `prisma`?

**Comment by DavidJSykes** [comment]
I am looking forward to trying out the new version! I'm sorry I couldn't offer more info to help with this. I had a major family emergency and had to drop everything.

**Comment by janpio** [comment]
4.2.0 is out already, so let us know if you had the time to play with it and this indeed helps and fixes the problem 🚀
