### ISSUE TITLE
The findMany query fails silently when the array length passed through IN parameter exceeds 999

### ISSUE THREAD

**Issue by kkomelin** [prisma/prisma#14539]
### Bug description

The findMany query fails silently when the array length passed through IN parameter exceeds 999.

### How to reproduce

  ```typescript
  const tags999 = await prisma.tag.findMany({
    where: {
      id: {
        in: Array.from({length: 999}, () => Math.floor(Math.random() * 1000))
      }
    },
  }) 
  console.log(tags999)
  // Returns [{obj1}, {obj2}, ....] which is correct.
  const tags1000 = await prisma.tag.findMany({
    where: {
      id: {
        in: Array.from({length: 1000}, () => Math.floor(Math.random() * 1000))
      }
    },
  }) 
  console.log(tags1000)
  // Returns [] which is wrong.
  // We need a proper error message here, something like "You have reached the max length of array passed to IN parameter."
  ```
  
  A related bug occurs when we use relation queries with more than 1000 tags added to all posts in total:
  
  ```typescript
  const posts = await prisma.post.findMany({
    include: {
      postTags: {
        include: {
          tag: true
        }
      }
    }
  })
  ```
  
  Which causes the following error:
  > Invalid `prisma.post.findMany()` invocation:
  > Inconsistent query result: Field tag is required to return data, got `null` instead.
  
It probably happens because the relation query somehow uses IN subquery. It's my guess based on how this kind of relation query is implemented in another framework.

### Expected behavior

**Remove this hardcoded limit for < 1000 items in the IN array. Let user decide what's safe for them!**

Alternatively:
1. The shown IN query with more than 1000 items passed should fail with a clear error message.
2. The described relation query should produce a better error message.

### Prisma information

```prisma
model Post {
  id                      Int           @id @default(autoincrement()) @db.UnsignedInt
 
  postTags          PostTag[]

  @@map("posts")
}
model Tag {
  id                      Int             @id @default(autoincrement()) @db.UnsignedInt
  
  postTags           PostTag[]

  @@map("tags")
}

model PostTag {
  postId                 Int             @map("post_id") @db.UnsignedInt
  tagId                   Int             @map("tag_id") @db.UnsignedInt

  post                   Post           @relation(fields: [postId], references: [id], onDelete: Cascade)
  tag                     Tag             @relation(fields: [tagId], references: [id], onDelete: Cascade)

  @@id([postId, tagId])

  @@map("posts_tags")
}
```

### Environment & setup

- OS: Docker: node:16-alpine (Linux)
- Database: Docker: mariadb:10.7
- Node.js version: v16.14.2

### Prisma Version

```
    "@prisma/client": "^4.1.1"
    "prisma": "^4.1.1"
```

**Comment by kkomelin** [comment]
And I have to temporary switch to raw IN queries like this:
```typescript
 const allTags = await prisma.$queryRawUnsafe<Tag[]>(`
    SELECT * FROM tags
    WHERE id IN (${allTagsIds.join(',')})
`)
```

**Comment by kkomelin** [comment]
The worst things is you start working on your app and everything works perfectly. Data is displayed. Search filters are working. You happily deploy the app to production and sleep well... until one day everything breaks. Suddenly. The logs are clean.
No app should behave that unpredictable, so for me it's high priority.

**Comment by younes-alouani** [comment]
Is this bug confirmed ?

**Comment by kkomelin** [comment]
@younes-alouani Seems to be not but I would appreciate if you try to reproduce it and let us know.

**Comment by kkomelin** [comment]
I consider switching to another ORM because with this time bomb I can't be sure that tomorrow all my relation queries will continue working as expected.

**Comment by janpio** [comment]
I assume you can manually run the `IN` query with >1000 Ids manually against the database with no problems at all?

**Comment by kkomelin** [comment]
@janpio Confirmed. 

I've never had this issue with MySQL-based dbs. Laravel relation queries, for example, are also based on using `IN`.

Additionally made this synthetic test just now:

```bash
node -e "console.log(Array.from({length: 1500}, () => Math.floor(Math.random() * 1500)).join(','))"
```

```sql
SELECT * FROM posts WHERE id IN (...)
```

**Comment by jkomyno** [comment]
Hi @kkomelin, we have attempted reproduction of your issue with `prisma@4.1.1` and `mariadb:10.7`, with no success.
We're currently observing proper results even when there are `5000` arguments in `IN` clauses in the Prisma Client.

Could you please share a snippet of how `tag` and `post` are populated in your case (i.e., your `create`/`createMany` statements)?
That, or even a reproduction repo, would be very beneficial to tackle this issue.
Also, please consider that snippets using `Math.random()` are much harder to reproduce. Thank you!

**Comment by kkomelin** [comment]
Already. Thanks to your tests @jkomyno I have found the reason of the problem:
https://github.com/prisma/prisma/pull/15124#issuecomment-1233913074

**Comment by jkomyno** [comment]
I have found other issues that may be relevant:
- https://github.com/prisma/prisma/issues/12338

**Comment by kkomelin** [comment]
Thank you very much guys for your help. 

We've successfully identified and reproduced the bug https://github.com/kkomelin/prisma-in-issue-reproduction 

MariaDB itself caused the issue, and the bug has been fixed in newer versions of the db server. For those who are still seeking for a solution, please upgrade your MariaDB version to the latest available patch version (at least).

**Comment by janpio** [comment]
Just for bookkeeping: We consider this a duplicate of https://github.com/prisma/prisma/issues/14019
