### ISSUE TITLE
Prisma query on "notIn" and "in" cause process to exit without throwing any error

### ISSUE THREAD

**Issue by rouzbehsbz** [prisma/prisma#14577]
I find weird behavior in prisma when executing this query:
I simplified the query for better convenience

```
const friendsList = [1,1];

await db.test.count({
	where: {
		userId: userId,
		friendByUserId: {
			in: friendsList,
		},
	},
});
```

here if you use duplicate IDs in `friendsList` just like my example at above, Node.js process will exit without any error
I write a listener on `exit` event of current process and it exits on `code 0`
And also query execute with not duplicate elements in `friendsList`.

My prisma client version is: `3.14.0`

Is that a problem with my version ?
Thanks for your helping.

**Comment by Weakky** [comment]
Hey @rouzbehsbz,

Would you mind providing a complete reproduction script for us?

Thanks 🙏
