### ISSUE TITLE
TS2341: Property 'fetcher' is private and only accessible within class 'PrismaClient '.

### ISSUE THREAD

**Issue by shtse8** [prisma/prisma#14582]
### Bug description

I have a model called `Fetcher`.
while accessing in prisma client, an type error is shown:
```
TS2341: Property 'fetcher' is private and only accessible within class 'PrismaClient '.
```

It is because there is a private field called `fetcher`, and the name is the same.
```
GlobalReject = 'rejectOnNotFound' extends keyof T
    ? T['rejectOnNotFound']
    : false
      > {
      /**
       * @private
       */
      private fetcher;
      /**
       * @private
       */
      private readonly dmmf;
      /**
       * @private
       */
      private connectionPromise?;
      /**
       * @private
       */
      private disconnectionPromise?;
      /**
       * @private
       */
      private readonly engineConfig;
      /**
       * @private
       */
      private readonly measurePerformance;
```

Could prisma team add an underscore to private fields?

### How to reproduce

```
Model Fetcher {
    id     Int   @id
   // anything
}
```

```ts
const prisma = new PrismaClient()
await prisma.fetcher.fetchMany({})
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by Weakky** [comment]
Hey @shtse8,

Would you mind telling us what Prisma version you're using? Thanks 🙏

**Comment by shtse8** [comment]
any updates on this? it should be easy. I am wondering should I change my `Fetcher` model name to avoid collision with Prisma private property.

**Comment by janpio** [comment]
Right now that is the easiest solution for you of course. We will try to avoid this clash in the future, but that might take some time.

**Comment by shtse8** [comment]
> Right now that is the easiest solution for you of course. We will try to avoid this clash in the future, but that might take some time.

It's good to know prisma noticed the issue. As modifying model name is a tough work, it is not worth to do it for only typing.  I will wait for the change. Thanks!

**Comment by SevInf** [comment]
I think this has been fixed for a long time, I am going to close issue now.
