### ISSUE TITLE
Error parsing attribute "@@index": The Gin index field type `Uuid` has no default operator class.

### ISSUE THREAD

**Issue by shahinghasemi** [prisma/prisma#14587]
### Bug description

When I set a `GIN` index to a field of type array of UUIDs it throws error. However, as far as I can tell, the GIN operator for UUID has been added in postgres v10. 
 

### How to reproduce

This is the schema that reproduces the bug:
```
model Test {
  id                  String              @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  arrId               String[]            @db.Uuid
  @@index([arrId], map: "idx_Gin", type: Gin)
}
```
When hover on `@@index` it says: `Error parsing attribute "@@index": The Gin index field type 'Uuid' has no default operator class.`

### Expected behavior

Should index the field correctly. 

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version:v16.15.0

### Prisma Version

```
prisma                  : 4.1.1
@prisma/client          : 4.1.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.469.0

```

**Comment by Vija02** [comment]
Getting this when running `prisma generate`.
`Error parsing attribute "@@index": The Gin index field type `VarChar` has no default operator class.`

**Comment by pimeys** [comment]
It's a validation issue. A workaround until we fix the validation is to explicitly to define the operator class:

```prisma
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

model Test {
  id    String   @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  arrId String[] @db.Uuid

  @@index([arrId(ops: ArrayOps)], map: "idx_Gin", type: Gin)
}
```

**Comment by pimeys** [comment]
For the dev fixing this: The validation passes if you remove the native type from the field. We should allow the index without explicit ops definition here even if the native type is defined.

**Comment by blazestudios23** [comment]
I'm having the same issue with 
```
@db.VarChar(255)
```

How do I set a default for that?

**Comment by janpio** [comment]
Please open a new discussion for this @blazestudios23. Thanks.

**Comment by adrian-huminiuc** [comment]
@blazestudios23  
I found in https://github.com/prisma/prisma/issues/17518 a workaround 
`@@index([reference(ops: raw("gist_trgm_ops"))], type: Gist)`
