### ISSUE TITLE
Incorrect types when creating crud functions wrapper

### ISSUE THREAD

**Issue by ArtemKurtiak** [prisma/prisma#14595]
### **Wrong typescript behavior when using custom wrapper function for:**
- prisma.model.findFirst
- prisma.model.findUnique
- prisma.model.findMany
- prisma.model.findFirstOrThrow
- prisma.model.findUniqueOrThrow

### **Cases:**
```
async findOne(dto: Prisma.userFindUniqueArgs, auth: boolean) {
    return this.prisma.user.findUnique({
      ...dto,
      include: {
        auth,
      },
    });
  }

  async checkMethod(dto: Prisma.userWhereInput) {
    const user = await this.findOne(
      {
        where: {
          email: '',
        },
      },
      false,
    );

    console.log(user.auth); // HERE in typescipt response 'auth' property is available but in console.log is undefined
  }
```
![Screenshot from 2022-08-01 23-18-10](https://user-images.githubusercontent.com/68440435/182239089-efbaf77f-ea92-4156-a31b-97fe9a47327d.png)

```
  async findOne(dto: Prisma.userFindUniqueArgs) {
    return this.prisma.user.findUnique({
      ...dto,
    });
  }

  async checkMethod(dto: Prisma.userWhereInput) {
    const user = await this.findOne({
      where: {
        email: '',
      },
      include: {
        auth: true  
     }
    });

    console.log(user.auth); // HERE I don't get auth property at all and get typescript error
  }
```
![Screenshot from 2022-08-01 23-25-32](https://user-images.githubusercontent.com/68440435/182240938-6ad10d22-e481-49f1-8ce9-627139830725.png)

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

enum UserRoleEnum {
  OWNER
  ADMIN
  CUSTOMER
}

enum UserStatusEnum {
  ACTIVE
  INACTIVE
}

model user {
  id        Int            @id @default(autoincrement())
  firstName String
  lastName  String
  birthDate DateTime
  confirmed Boolean        @default(false)
  role      UserRoleEnum
  status    UserStatusEnum
  email     String         @unique
  password  String
  createdAt DateTime       @default(now())
  updatedAt DateTime       @updatedAt
  auth      auth[]
}

model auth {
  id        Int      @id @default(autoincrement())
  token     String
  user      user     @relation(fields: [userId], references: [id])
  userId    Int
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

```

### Environment & setup

- OS: Linux Ubuntu 20.04 LTS
- Database: PostgreSQL
- Node.js version: 16.15.1
- Nest version: 9.0.0
- Typescript version: ^4.3.5 
- Prisma client version: 4.1.1

### Prisma Version

```
4.1.1
```

**Comment by janpio** [comment]
I can totally do that if you want.

Besides that it has been categorized properly and as soon as someone is working on bugs about Client Types, they will spend time to reproduce and if they confirm there to be a problem, they can also try to fix it.

**Comment by ArtemKurtiakZenwayCode** [comment]
@janpio Thank you! Hope to quick fix)

**Comment by ArtemKurtiakZenwayCode** [comment]
Hi, any update on this? :)

**Comment by janpio** [comment]
Resolved or not interested in it anymore?
If the latter, we would definitely be interested in looking at it one day and hopefully being able to fix it - so we would appreciate it if you could keep the issue open.

**Comment by ArtemKurtiak** [comment]
It was actually my inexperience in typescript generics:(

Fixed by passing generic to my wrapper function and prisma method:
Based on: https://github.com/nehalist/prisma-func-wrapper

### Example:
```
async findOne<T extends Prisma.userFindUniqueArgs>(dto: Prisma.SelectSubset<T, Prisma.userFindUniqueArgs>) {
    return this.prisma.user.findUnique<T>(dto);
}
```
