### ISSUE TITLE
Prisma transaction does not work in case of error from prisma

### ISSUE THREAD

**Issue by rajesh1158** [prisma/prisma#14608]
### Bug description

I am using postgres database. When using the batch transaction API `prisma.$transaction`, when there are multiple queries to be run, and if there is a delete query for the same id present 2 times, then either the transaction does not get rolled back or the queries as part of triggers alone are not rolled back, leading to inconsistent data.

I have triggers created on the table to do certain other changes when INSERT or UPDATE queries are run.

### How to reproduce

1. Create a prisma transaction with an array of queries
2. Have an update query first, then a delete query, then another update query and then the same delete query as previous
3. Try to await on the `prisma.$transaction` so that the queries are executed
4. Prisma throws an error because the 2nd delete query fails
5. The transaction is either not rolled back or trigger queries alone are not rolled back, leading to inconsistent data

### Prisma information

Due to sensitive nature of my queries, I cannot share them.

### Environment & setup

- OS: centos 8
- Database: PostgreSQL 13
- Node.js version: v14.20.0

### Prisma Version

```prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : rhel-openssl-1.0.x
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/query-engine-rhel-openssl-1.0.x)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/migration-engine-rhel-openssl-1.0.x)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.0.x)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/prisma-fmt-rhel-openssl-1.0.x)
Studio               : 0.358.0
Preview Features     : createMany
```

The same issue happens on the latest prisma version 4.1.1

**Comment by outbreak** [comment]
Maybe it's a duplicate [#14548](https://github.com/prisma/prisma/issues/14548#issue-1321970653)

**Comment by Weakky** [comment]
Hey @outbreak,

Would you mind providing the error on the 2nd failing delete that you're seeing? Thanks 🙏

**Comment by rajesh1158** [comment]
I get the below error:

    An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.

**Comment by SevInf** [comment]
Hi @rajesh1158, thanks for the report.
I can not reproduce the issue with the provided steps. You can see the code in #15183, all updates are rolled back after failed delete. I also tried the same code with 50 and 100 concurrent updates and again, in both cases rollback have happened.

Could you provide the schema and the exact code snippet that causing the issue? That would greatly help with reproducing it.

**Comment by janpio** [comment]
Ping @rajesh1158, can you help us out here please? We would love to be able to reproduce, but need additional information before attempting this again. Without that we will have to close this issue as unreproducible unforunately.

**Comment by janpio** [comment]
Once more @rajesh1158, can you help us reproduce this? Thanks.

**Comment by janpio** [comment]
Closing then until someone provides more information. Please comment or open a new issue. Thanks!
