### ISSUE TITLE
Always put createdAt, updatedAt fields on top in introspection result after @id

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#1461]
Related issue: https://github.com/prisma/prisma2/issues/1364

Detecting created and updated at fields might need some heuristics. I suggest moving the following field names on top after the `@id` field, if it exists. 

`createdAt`, `updatedAt`, `created_at`, `updated_at`

**Comment by janpio** [comment]
I personally like to put the timestamps at the end of my tables 🤷‍♀

**Comment by divyenduz** [comment]
Internal note: dropping from current sprint

**Comment by janpio** [comment]
We now use the order of the columns in the database as the source of truth. You can control the order in the PSL via that.
