### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by mrLuisFer** [prisma/prisma#14626]
### Bug description

I recently upgrade to prisma *v4.1.1* using `yarn add prisma@latest`

But when I run my scripts for database and development mode I get the following error:
```bash
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\Users\\mrlui\\workspace\\next-chat-app\\app\\node_modules\\@prisma\\engines\\query_engine-windows.dll.node'".
```
I'm not sure if it's a problem with yarn or prisma, so that's why I'm making this issue
btw already run `yarn add next react react-dom` and it doesn't work

### How to reproduce

1. Upgrade prisma and prisma-client to v4.1.1
2. Run `yarn dev` or `npx next dev`

### Expected behavior

I'm waiting for Next to start compile the app in development mode.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model Messages {
  id        String      @default(uuid()) @id
  content   String?
  published DateTime    @default(now())
  author    User?       @relation(fields: [authorId], references: [id])
  authorId  String?
}

model Account {
  id                 String  @id @default(cuid())
  userId             String  @map("user_id")
  type               String
  provider           String
  providerAccountId  String  @map("provider_account_id")
  refresh_token      String?
  access_token       String?
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String?
  session_state      String?
  oauth_token_secret String?
  oauth_token        String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@map("accounts")
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique @map("session_token")
  userId       String   @map("user_id")
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@map("sessions")
}

model User {
  id            String    @id @default(uuid())
  name          String
  email         String    @unique
  password      String?
  image         String?
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  messages      Messages[]
  accounts      Account[]
  sessions      Session[]
  emailVerified DateTime?

  @@map(name: "users")
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
  @@map("verificationtokens")
}
```

### Environment & setup

- OS: Windows 10
- Database: SQLite
- Node.js version: 16.15.1

### Prisma Version

```bash
prisma                  : 4.1.1
@prisma/client          : 4.1.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.469.0
```

**Comment by janpio** [comment]
Does `C:\\Users\\mrlui\\workspace\\next-chat-app\\app\\node_modules\\@prisma\\engines\\query_engine-windows.dll.node'"` exist? Are you already running an app or e.g. Prisma Studio when running your development command?

**Comment by mrLuisFer** [comment]
> Does `C:\\Users\\mrlui\\workspace\\next-chat-app\\app\\node_modules\\@prisma\\engines\\query_engine-windows.dll.node'"` exist? Are you already running an app or e.g. Prisma Studio when running your development command?

`query_engine-windows.dll.node` already exists, and nope, I don't have another app running with prisma

![file exists](https://user-images.githubusercontent.com/65029792/183126740-6c3ca034-f749-4d06-892d-b694b5390fee.png)

One solution I had was to delete the `node_modules` and `yarn.lock.json` and reinstall all my dependencies and it works
But if I want to add a new dependency, the error appears again

**Comment by herzog0** [comment]
[+1]

**Comment by millsp** [comment]
This issue has been fixed, so I am marking it as closed. Please ping me or open an new issue if you get this again. Thanks.
https://github.com/prisma/prisma/issues/9184

**Comment by mizanmahi** [comment]
still getting the same issue prisma version 502.0

**Comment by janpio** [comment]
Then please open a new issue and fill the issue template with the information it asks for. Thanks.

**Comment by jhonanova3** [comment]
Hola, hablo solo español. 
En mi caso tiré la carpeta del proyecto al Escritorio, instalé Jest, y luego la volví a poner en donde la quería (SOLUCIONADO)

EXITOS

**Comment by gersooonn** [comment]
![image](https://github.com/prisma/prisma/assets/128495179/5d6bb061-e4da-490e-8d03-07997fd9b67a)

**Comment by cqthanh-zx** [comment]
The same, looks like this issue is specific to Windows machines

**Comment by K332** [comment]
> ![image](https://private-user-images.githubusercontent.com/128495179/285034198-5d6bb061-e4da-490e-8d03-07997fd9b67a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjAyNjUsIm5iZiI6MTcwODQxOTk2NSwicGF0aCI6Ii8xMjg0OTUxNzkvMjg1MDM0MTk4LTVkNmJiMDYxLWU0ZGEtNDkwZS04ZDAzLTA3OTk3ZmQ5YjY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQwOTA2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjM0MzI0ZWE0ZjI4ZTgxYjdkODIwNjQ1OWM5MTM5ZGFlNTI2NWI5ZTFiYTE5ZGY3ZGYzODI1MzlkZjk5NWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ThTwYB5l5XrIPfllpz8Mes6xyGcraaSoC6SgIZirxKg)

I have encountered this issue before. Simply stopping the current project's Node process and then reusing the Prisma migrate command resolved it.

**Comment by 2256184693** [comment]
I close my local express server and the problem fixed up. Maybe it's because the server has opened a prisma connection.

**Comment by alsyferr** [comment]
if you use any local running service like docker etc, stop the server and rerun the prisma migrate. It would work fine

**Comment by KhalilMeziane** [comment]
If you still have this issue, just stop the server, run the migration, and then restart the server app!
