### ISSUE TITLE
Prisma client is not auto-generated when using npm ci

### ISSUE THREAD

**Issue by arunrdd** [prisma/prisma#14656]
### Bug description

Github actions runs `npm ci` before running `npm run build` in one of the projects I'm working on. The Prisma client is not auto-generated as described in the documents, causing the build to fail.

### How to reproduce

1. Create a node project with Prisma schema setup
2. Have Github actions setup and run `npm ci` before the build step
3. Build fails with errors like so: `Module '"@prisma/client"' has no exported member ...`

### Expected behavior

Ideally a clean npm install should also generate the client just like normal npm install.

### Environment & setup

- OS: Ubuntu 20.04
- Database: PostgreSQL
- Node.js version: 16.16.0

### Prisma Version

```
4.1.1
```

**Comment by janpio** [comment]
Can you share a minimal project with a build step similar to yours that reproduces the problem?
What Npm version are you using?

**Comment by janpio** [comment]
PIng @arunrdd

**Comment by arunrdd** [comment]
@janpio I couldn't get to it sooner. As I tried to reproduce it today, to my surprise everything seemed to work fine. At this point I could not reproduce this issue. I have tested both the 4.1.1 and latest version of Prisma and i confirm everything is working as expected. You can find the repo I used [here](https://github.com/arunrdd/prisma-issue-14656). We can close this issue, unless if someone who gave a thumbs up is still experiencing this in their setup.
