### ISSUE TITLE
`npx prisma studio`: Error: Could not find a schema.prisma file that is required for this command.

### ISSUE THREAD

**Issue by tomjrtsmith** [prisma/prisma#14669]
### Bug description

```
Error: Could not find a schema.prisma file that is required for this command.
You can either provide it with --schema, set it as `prisma.schema` in your package.json or put it into the default location ./prisma/schema.prisma https://pris.ly/d/prisma-schema-location
```

### How to reproduce

When attempting to run Prisma Studio or Prisma from the CLI

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("..")
}

model Mev {
  id           Int      @id @default(autoincrement())
  chainId      Int
  type         Int
  timestamp    DateTime
  transactions String[]
  block        Int
  revenue      Float
  gasCost      Float
  searcher     String
  protocols    Int[]
  affected     String[]
```

### Environment & setup

MacOS Monterey 12.4
PostgreSQL
- Node.js version: 18.2

### Prisma Version

```
prisma                  : 4.1.1
@prisma/client          : 4.0.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.469.0
```

**Comment by janpio** [comment]
Where does your Prisma schema file live?
What other commands are you getting this error?

**Comment by tomjrtsmith** [comment]
Schema file is ./prisma/schema.prisma
It occurs when I've run npx prisma studio and npx prisma migrate dev

**Comment by janpio** [comment]
Did this resolve itself @tomjrtsmith?

**Comment by janpio** [comment]
@jessekrubin Can you share exactly when you are seeing this? What command are you running, what does your schema look like and what does your project setup look like?

**Comment by janpio** [comment]
Ok, then you are experiencing something different - this here is specific to `npx prisma studio`. Optimally open a new issue and provide _some_ information and we can take a look.

**Comment by Weakky** [comment]
Hey @tomjrtsmith,

Would you please be able to provide a small reproduction repository? This would help us a lot to fix your issue as it looks to be very dependant on how you've setup your project.

Thank you 🙏

**Comment by jharrell** [comment]
Hi @tomjrtsmith 

Following up: do you have a reproduction available? We're unable to reproduce on our end and are unable to move things forward without that. 

Thanks!

**Comment by jharrell** [comment]
Hi again,

Without a reproduction or further info we'll have to close this issue. As always please feel free to drop a comment or open a new issue!

**Comment by KlyDesign** [comment]
make sure you are in the root directory with the package.json then run it could be you are just initiating the command in a nested dir ie /src or /app it a directory issue find your schema file. 


`npx prisma version --json` 
verify studio is installed you should see: 
"studio": "0.494.0"} 
studio with a version number ending the object,
if not run `npm i prisma studio --save-dev`

then just make sure you run the command `npx prisma studio` from root directory with the package.json!!!!!! main fix i found 
also double check imports are correct on your api routes.  
in next js it wont work if you try to run studio in pages or src.

**Comment by Son1c-sound** [comment]
weirdly for me, this happens when you running localhost, if u turn off localhost and generate again it wont do same, so u have to kind turn on off localhost or something

**Comment by Sasnigs** [comment]
Had this issue but turns out i was running npx prisma generate from my root directory instead of my backend directory thats within my root directory where my schema was.

**Comment by pranay-dutta** [comment]
For me it was the config file which caused the issue

```tsx
export default defineConfig({
  schema: "prisma/schema/schema.prisma",  //Location of you main schema file
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
```
