### ISSUE TITLE
Validation fails to detect invalid `SetNull` referential action referencing non-optional fields

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#14673]
This missed validation triggers a migration error when using MySQL, SQL Server, SQLite, and CockroachDB, but not on Postgres.

Example with **MySQL**:

```prisma
// schema.prisma

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider = "mysql"
  url = env("DATABASE_URI_MYSQL") 
}

model User {
  id      String @id
  profile Profile?
}

model Profile {
  id       String @id
  user     User @relation(fields: [userId], references: [id], onUpdate: SetNull, onDelete: SetNull)
  
  // notice that this field should become optional in order to support `SetNull`
  userId   String @unique
}
```

We can see that the schema is wrongfully considered valid:

```text
❯  prisma validate
Prisma schema loaded from prisma/schema.prisma
The schema at /.../reprod/prisma/schema.prisma is valid 🚀
```

If we attempt a push, we get the following error:

```text
❯ prisma db push --skip-generate
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "PRISMA_DB_NAME" at "localhost:3306"

MySQL database PRISMA_DB_NAME created at localhost:3306
Error: Column 'userId' cannot be NOT NULL: needed in a foreign key constraint 'Profile_userId_fkey' SET NULL
   0: sql_migration_connector::apply_migration::migration_step
           with step=AddForeignKey { foreign_key_id: ForeignKeyId(0) }
             at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:21
   1: sql_migration_connector::apply_migration::apply_migration
             at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:10
   2: migration_core::state::SchemaPush
             at migration-engine/core/src/state.rs:384
```

If we try to create/update the `Profile` model via the Prisma client, we get the following migration error:

```ts
await prisma.$transaction([
  prisma.user.create({
    data: {
      id: '1'.
      profile: {
        create: { id }
      }
    }
  })
])
```

```text
    Column 'userId' cannot be NOT NULL: needed in a foreign key constraint 'Profile_userId_fkey' SET NULL
       0: sql_migration_connector::apply_migration::apply_migration
                 at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:10
       1: migration_core::state::SchemaPush
                 at migration-engine/core/src/state.rs:384
```

If we exclude the `onUpdate`/`onDelete` referential actions, the schema above generates the following `SQL` statements (we can check that via `prisma migrate dev`):

```sql
-- CreateTable
CREATE TABLE `User` (
    `id` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Profile` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Profile_userId_key`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Profile` ADD CONSTRAINT `Profile_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`);
```

On **Postgres**, oddly, `prisma db push` it doesn't fail, so migration error is thrown:

```text
❯ prisma db push --skip-generate
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "PRISMA_DB_NAME", schema "public" at "localhost:5432"

PostgreSQL database PRISMA_DB_NAME created at localhost:5432

🚀  Your database is now in sync with your Prisma schema. Done in 64ms
```

## `SetNull` on Valid Schema

If we want `prisma db push` to work on other databases like `mysql:8` when using the `SetNull` referential action, we'd need to change the schema above as:

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"] 
}

datasource db {
  provider = "mysql"
  url = env("TEST_MYSQL_URI_MIGRATE")
  referentialIntegrity = "foreignKeys"
}

model User {
  id      String @id
  profile Profile?
}

model Profile {
  id       String @id
  user     User? @relation(fields: [userId], references: [id], onUpdate: SetNull, onDelete: SetNull)
  userId   String? @unique
}
```

which generates the following `SQL` statements:

```sql
-- CreateTable
CREATE TABLE `User` (
    `id` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Profile` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NULL,

    UNIQUE INDEX `Profile_userId_key`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Profile` ADD CONSTRAINT `Profile_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE SET NULL;
```

**Comment by tomhoule** [comment]
Is this actually not valid at the database level? We should test first that a `CREATE TABLE` exhibiting that pattern is rejected by the databases we support before writing a PSL validation.

**Comment by jkomyno** [comment]
## MySQL

**Test SQL Statement**:

```sql
CREATE TABLE categories(
  categoryId INT AUTO_INCREMENT PRIMARY KEY,
  categoryName VARCHAR(100) NOT NULL
) ENGINE=INNODB;

CREATE TABLE products(
  productId INT AUTO_INCREMENT PRIMARY KEY,
  productName varchar(100) not null,
  categoryId INT,
  CONSTRAINT fk_category
  FOREIGN KEY (categoryId) 
      REFERENCES categories(categoryId)
      ON DELETE ${action}
      ON UPDATE ${action}
) ENGINE=INNODB;
```

with

```typescript
type Action
  = 'RESTRICT'
  | 'CASCADE'
  | 'SET NULL'
  | 'NO ACTION'
  | 'SET DEFAULT'

let action: Action
```

The following SQL referential actions work for both `ON UPDATE` and `ON DELETE` on `mysql:5.7` and `mysql:8`:
- `RESTRICT`
- `CASCADE`
- `SET NULL`
- `NO ACTION`

The following only works on `mysql:8`:
- `SET DEFAULT`

On `mysql:5.7`, it fails with:

```text
SqlError: (conn=22, no: 1215, SQLState: HY000) Cannot add foreign key constraint
```

**Comment by jkomyno** [comment]
# SQL Reproduction with one-to-one optional relations

## MySQL

- [Foreign key docs](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html)

**Test SQL Statement**:

```sql
CREATE TABLE User (
    id INTEGER PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE Profile (
    id INTEGER PRIMARY KEY,
    userId INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (userId) REFERENCES User(id)
      ON DELETE ${action}
      ON UPDATE ${action}
) ENGINE=InnoDB;
```

with

```typescript
type Action
  = 'RESTRICT'
  | 'CASCADE'
  | 'SET NULL'
  | 'NO ACTION'
  | 'SET DEFAULT'

let action: Action
```

The following SQL referential actions work for both `ON UPDATE` and `ON DELETE` on `mysql:8`:
- `RESTRICT`
- `CASCADE`
- `SET NULL`
- `NO ACTION`
- `SET DEFAULT`

The following does not work on `mysql:8`:
- `SET NULL`

On `mysql:8`, it fails with:

```text
SqlError: (conn=60, no: 1830, SQLState: HY000) Column 'userId' cannot be NOT NULL: needed in a foreign key constraint 'profile_ibfk_1' SET NULL
```

**Comment by jkomyno** [comment]
To recap, @tomhoule, the SQL database don't validate the `CREATE TABLE` statements when defining `SET NULL` referential actions, but I think `Prisma` should, in order to avoid panics at runtimes.

**Comment by tomhoule** [comment]
> but I think Prisma should, in order to avoid panics at runtimes.

Makes sense. One thing to keep in mind that could prevent us from going into that direction is the principle that we should be able to introspect a valid database schema to a valid prisma schema in as many cases as possible, so if it's valid at the database level, we may want to accept it. Maybe warn.

**Comment by Jolg42** [comment]
What we want to do ([from Notion](https://www.notion.so/prismaio/Validation-of-SET-NULL-referencing-non-optional-fields-71325e2c6d764e38aec94f16bf2db66f#8f962b20710f4de39427cf6a85b21d17))

Make schema with non-optional 1:1 relation and `SetNull` referential actions invalid.

Optional but nice DX: Add special error message for PostgreSQL that links to a documentation page that explains why some valid SQL for PostgreSQL can lead to an invalid Prisma schema via Introspection: While the CREATE TABLE works, the INSERT/UPDATE/DELETE on that table will all fail.

**Comment by jkomyno** [comment]
To summarise the output of the tests done in https://github.com/prisma/prisma/pull/15728 in relevant to this issue:

- For both 1:1 and 1:n relations:
  - `postgres` doesn't validate DDL statements that set a `SET NULL` referential action on a foreign key constraint whose referenced column (or one of the referenced columns) is `NOT NULL`, all other database throw a validation error in this case.
  - `postgres` fails at runtime with a not-null constraint violation error when `UPDATE` /  `DELETE` statements trigger the `SET NULL` referential action on a column defined as `NOT NULL`

Optional but nice DX: There's also an odd behavior that may be useful to document and/or validate against:
- `sqlserver` fails at runtime on 1:1 NULL relations because `NULL` conflicts with `UNIQUE` indexes in that particular database
