### ISSUE TITLE
Not compatible with OpenSSL version 3

### ISSUE THREAD

**Issue by vincent-thomas** [prisma/prisma#14681]
### Bug description

I get this error:
```
Error: Unknown binaryTarget debian-openssl-3.0.x and no custom binaries were provided
```

This error should have been fixed in prisma 3.3.1 i believe.

OpenSSL version 3.0.2

I'm on wsl 2, ubuntu 22.04

Prisma Schema

### How to reproduce

1. Be on windows
2. Install ubuntu 22.04 WSL 2 (maybe ubuntu 22.04 without wsl, may not work tho since i don't have access to a native-linux machine)
3. Bootstrap any project with `prisma@4.1.1` and `@prisma/client@4.1.1`
4. Run `prisma generate`
Then you should get something like this:
```
$ yarn dlx dotenv-cli -c local  prisma generate
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 3s 906ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 3s 989ms
// ^^ Why This? (Maybe bc i'm running yarn pnp?)

Error: Unknown binaryTarget debian-openssl-3.0.x and no custom binaries were provided
```

### Expected behavior

That prisma works without error.

### Prisma information

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  output = "../lib/prisma-client"
  binaryTargets = ["native"]

}


// Ignore this generator
generator typegraphql {
  provider = "typegraphql-prisma"
  output = "../lib/db-resolvers"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Animal {
  id Int @id @default(autoincrement())
  age String
  name String
}
```

### Environment & setup

- OS: Windows 11 (but error is happening on wsl 2 ubuntu 22.04)
- Database: mysql (but not relevant)
- Node.js version: v16.16.0

### Prisma Version

4.1.1

**Comment by janpio** [comment]
Are you sure you are running 4.1.1 in that setup? What does `prisma -v` output?

**Comment by janpio** [comment]
I can not reproduce the error with a plain install and new project:

```
root@Surface-Studio:~/14681# npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.1.1 | library) to ./node_modules/@prisma/client in 60ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
root@Surface-Studio:~/14681# npx prisma -v
Environment variables loaded from .env
prisma                  : 4.1.1
@prisma/client          : 4.1.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.469.0
root@Surface-Studio:~/14681#
```

**Comment by vincent-thomas** [comment]
`yarn dlx [command]` just executes dependencies bin file, and puts node_modules/.bin at path. 
`dotenv-cli -c local` just loads my environment variables.
I got the error with `prisma generate`, But for some weird reason it worked later, without any reinstall of deps 🤷🏼‍♂️

**Comment by janpio** [comment]
Well, seems this was just a fluke then. We like those "bugs" best - they are easiest to fix 😆 

Report if this ever comes back.

**Comment by vincent-thomas** [comment]
I now know the problem. Prisma is not compatable with yarn pnp (2+). It works though when you install `@yarnpkg/pnpify`. Its a cli command to help npm packages act like they are in an `node_modules` environment. Is there an idea to reopen this issue about yarn pnp support?

**Comment by janpio** [comment]
Optimally just open a new issue with a more targetted description of the problem.
