### ISSUE TITLE
Issues using db push to create indexes

### ISSUE THREAD

**Issue by jcampbell05** [prisma/prisma#14697]
### Bug description

I have a database on mongo atlas, I added a new index and used 'db push' to create the next index.

Instead I have ended up with a duplicate error.
<img width="1343" alt="Screenshot 2022-08-08 at 13 50 57" src="https://user-images.githubusercontent.com/1484989/183422539-928efe7f-4c34-4c5a-82d7-8d467fc43524.png">

### How to reproduce

1. Create an index
2. Use db push to create the index
3. 3. index is created or ignored if accepted.

### Prisma information

Client Version 4.1.1

Schema

```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}


model User {
  objectID  String @id @default(auto()) @map("_id") @db.ObjectId
  id String @unique
  email String
  keyID String
  chargebeeCustomerID String?
  chargebeePortalSessionID String?
  chargebeeSubscriptionID String?
  webhookUrl String?
  webhookAuthenticationValue String?
  onboarded Boolean

  @@index([keyID])
}

```

### Environment & setup

- OS: Big Sur
- Database: MongoDB running on Atlas
- Node.js version 14.19.3

### Prisma Version

```
4.1.1
```

**Comment by janpio** [comment]
Might this be helpful?
https://stackoverflow.com/a/24430345

**Comment by jcampbell05** [comment]
Yes, in the end I realised it was my fault and I wrote a script to sanatise the data which allowed prisma to work.
