### ISSUE TITLE
Support for INCLUDE clauses on index definitions

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#14699]
MSSQL: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver16#include-column---n--	
Postgres: https://www.postgresql.org/docs/14/sql-createindex.html

Suggested PSL representation:

```prisma
@@index([a, b], include: [c])
```

## Related issues

- https://github.com/prisma/prisma-engines/pull/3108

**Comment by nvanbenschoten** [comment]
Is this a duplicate of https://github.com/prisma/prisma/issues/8584?

**Comment by tomhoule** [comment]
Looks like it indeed, thanks for pointing it out. Let's close this one as duplicate.
