### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

### ISSUE THREAD

**Issue by sahil-ahuja-1** [prisma/prisma#14716]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v17.8.0            | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 3.11.1             |
| Query Engine    | 0.1.0              |
| Database        | postgresql         |

## Logs
```

```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by garrensmith** [comment]
@sahil-oval could you add your schema and the query you did to get this error. That will make it a lot easier to find out what is happening here.

**Comment by janpio** [comment]
Ping @sahil-ahuja-1

**Comment by janpio** [comment]
Once more, can you please help us by providing more information @sahil-ahuja-1? Thanks.

**Comment by janpio** [comment]
Closing then until someone provides more information. Please comment or open a new issue. Thanks!
