### ISSUE TITLE
BigInt conversion issue

### ISSUE THREAD

**Issue by giladv** [prisma/prisma#14724]
### Bug description

BigInt Id's returned from a cockroachdb query have an 'n' suffix added to them.

for instance 
```
BigInt(0786496040863662081)
```

problem is, when trying to reuse this id in a create query inside a ref connect prop it says the id doesn't exists.
doing the same in a normal query works with same id

### How to reproduce

1. query a row with 0786496040863662081 as id.
2. reuse that returned row.id in a create -> connect field
3. see it fail (row doesn't exist)

### Prisma information

specified above. will add more details if required

### Environment & setup

- OS: osx
- Database: cockroachdb
- Node.js version: 16.10

### Prisma Version

4.2.0

**Comment by janpio** [comment]
The `n` is how Javascript tells you that you are looking at a BigInt, not a normal Int/Number.

Can you share a minimal example code of the reuse example that is failing for you?

**Comment by giladv** [comment]
hello, the bug was my fault. i misused the connect prop. my bad.
