### ISSUE TITLE
Add more ways to configure `DATABASE_URL`, like `yaml`, `js`, `ts` instead of `.env` file

### ISSUE THREAD

**Issue by ellieot** [prisma/prisma#14729]
## Problem

I'm used to having all the configurations together, so a separate configuration file would make the program more complicated

## Suggested solution

Add more configuration file formats will surely help， this is an insignificant request, but thank you all

**Comment by janpio** [comment]
`.env` is just a convenience way to load some values into the environment. It is pretty JS/TS native and common, so that is what we support out of the box. If you want to use another format, please just handle the loading into the env yourself.

**Comment by DavidHancu** [comment]
Hi @ellieot!

I've recently launched Prisma Util and what you're asking is currently a proposal. Maybe you can help with suggesting a format at our issue? Prisma Util does a lot more than just this, including another proposal for code-generated schemas plus the built-in ability for model inheritance and multiple schema file usage.

Here are the links:
[Package Link](https://www.npmjs.com/package/prisma-util)
[YAML Proposal](https://github.com/DavidHancu/prisma-util/issues/2)

**Comment by DavidHancu** [comment]
Just a quick update for the YAML proposal in Prisma Util: It's confirmed to come for v1.4.0.

**Comment by janpio** [comment]
Closing this issue based on my original comment from 2022: https://github.com/prisma/prisma/issues/14729#issuecomment-1210292615
