### ISSUE TITLE
db pull --url with an invalid url produces a misleading error message

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#14732]
When you use `prisma db pull --url` and provide an invalid URL, the error message is the following:

```
✖ Introspecting

Error: P1012 Introspection failed as your current Prisma schema file is invalid

Please fix your current schema manually, use prisma validate to confirm it is valid and then run this command again.
Or run this command with the --force flag to ignore your current schema and overwrite it. All local modifications will be lost.
```

Even if your local Prisma schema is valid. The error message should instead say that the url passed through the `--url` argument is not valid.

### Steps to reproduce

In a project with a valid SQLite Prisma schema:

- Run `prisma validate` to confirm that the schema is valid
- Run `prisma db pull --url dev.db`. Observe the error above.
- Run `prisma db pull --url file:dev.db`. Observe introspection working fine.

**Comment by Jolg42** [comment]
Now `prisma db pull --url dev.db` errors with
```
Unknown protocol withoutfileprefix.db:
```
