### ISSUE TITLE
Migration continually recreated despite schema not changing - dbgenerated nextval

### ISSUE THREAD

**Issue by haneyman** [prisma/prisma#14788]
### Bug description

Schema is not changed but migration is continually recreated for a dbgenerated id:

`id                     String                   @id @default(dbgenerated("'policy_'|| nextval('policy_seq')"))`

I have tried various syntaxes to no avail.
Postgres shows it as:
    `id text COLLATE pg_catalog."default" NOT NULL DEFAULT ('policy_'::text || nextval('policy_seq'::regclass)),`

### How to reproduce

Add to schema with Postgres provider:
` id                     String                   @id @default(dbgenerated("'policy_'|| nextval('policy_seq')"))
`

### Expected behavior

Create an original migration but should not create any more subsequent migrations after the original one.  Unfortunately it continually creates a new migration on `prisma migrate dev`

### Prisma information

```
model Policy {
  id                     String                   @id @default(dbgenerated("'policy_'|| nextval('policy_seq')"))
  name               String                   @unique

  @@map("policy")
}

```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: 18

### Prisma Version

```
4.2.0
```

**Comment by janpio** [comment]
Can you try running `prisma db pull` to see if it updates your schema to a different syntax?

**Comment by haneyman** [comment]
That did actually fix the issue, thanks!

**Comment by janpio** [comment]
What syntax did you end up with in the end?

**Comment by haneyman** [comment]
***@***.***@default(dbgenerated("('policy_'::text || nextval('policy_seq'::regclass))"))
    
   
     
    
   
   
   
    On 08/15/2022 10:39 AM PDT Jan Piotrowski ***@***.***> wrote:
    
   
     
    
   
     
    
     
   What syntax did you end up with in the end? 
   —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***> 
   
  
    
   
   
   
     
    
   
     
    
   
     
    
   
     
    
   
    - Mark

**Comment by janpio** [comment]
Thanks. That is fortunately pretty close to what Postgres shows itself 👍
