### ISSUE TITLE
Prisma generate throwing error `2412 killed`

### ISSUE THREAD

**Issue by basitanwer** [prisma/prisma#14780]
### Bug description

Upgrading from prisma `3.3.0` to `4.2.1` running the same `npx prisma generate` throwing error 

```bash
/bin/sh: line 1:  2370 Killed: 9               prisma generate
error Command failed with exit code 137.
```

while running `npx prisma generate --schema prisma.ingestion/schema.prisma` throwing error

```bash
Environment variables loaded from .env
Prisma schema loaded from prisma.ingestion/schema.prisma

✔ Generated Prisma Client (3.3.0) to ./prisma.ingestion/generated/ingestion in 441ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from './prisma.ingestion/generated/ingestion'
const prisma = new PrismaClient()

[1]    2412 killed     npx prisma generate --schema prisma.ingestion/schema.prisma
```

Reverted back to `4.2.0` works fine though.

Happy to provide as much information i can and help this awesome software!

### How to reproduce

I am unable to reproduce it in a separate project even with the the duplicate settings.

### Prisma information

see above

### Environment & setup

Environment & setup

    OS:MacOs
    Database: Postgresql
    Node.js version: v16.9.0

### Prisma Version

```

prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by janpio** [comment]
> ```shell
> Environment variables loaded from .env
> Prisma schema loaded from prisma.ingestion/schema.prisma
> 
> ✔ Generated Prisma Client (3.3.0) to ./prisma.ingestion/generated/ingestion in 441ms
> You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
> 
> import { PrismaClient } from './prisma.ingestion/generated/ingestion'
> const prisma = new PrismaClient()
> 
> [1]    2412 killed     npx prisma generate --schema prisma.ingestion/schema.prisma
> ```

Are you sure you updated both CLI and Client package to 4.2.1? The output indicates the Client was still at 3.3.0. Although that should not really cause this error, it could indicate that generally something was off.

**Comment by basitanwer** [comment]
Yeah seems odd, i missed this part of the log but i did update it & that is confirmed. 
I think we can close this bug. Maybe something really specific to my machine.

**Comment by janpio** [comment]
Let us know if it pops up again - we really want to fix such kinds of problems of course.
