### ISSUE TITLE
Can the comment of the database be attached when generating the client? 

### ISSUE THREAD

**Issue by MineYuanlu** [prisma/prisma#14798]
## Problem

As the title goes, every `column` in the database can be attached with a comment (at least MySQL is like this)
Is it possible to bring this information into the `schema.prisma`?

Also, when generating `.prisma/client`, can this comment be brought into the type definition?

#### Current situation:
- schema.prisma:
```
model user {
  id      Int       @id
}
```
- Model:
```ts

/**
 * Model user
 * 
 */
export type user = {
  id: number
}
```
#### my sql
```sql
CREATE TABLE `user` (
  `id` int NOT NULL COMMENT 'the user id',
) COMMENT='the user datas';
```

#### I want
- schema.prisma:
```
/// the user datas
model user {
  /// the user id
  id      Int       @id
}
```
- Model:
```ts

/**
 * Model user
 * 
 * the user datas
 */
export type user = {
  /**the user id*/
  id: number
}
```

## Suggested solution

Improve the CLI tool: 
1. when using `prisma db pull`, the database comments can be written into the `schema.prisma` file together.
2. when using such as `prisma db push`, `prisma migrate deploy`, comments can be pushed into the database together.
3. when using `prisma generate`, The Model in the generated `.prisma/client` can also be attached with a comment as described above

## Additional context

[From: discussions/14333](https://github.com/prisma/prisma/discussions/14333)

**Comment by janpio** [comment]
No, that is currently not possible. Is there something about your request that is _not_ reflected in the multiple issues under https://github.com/prisma/prisma/labels/topic%3A%20comments yet? If not, best close this issue and leave 👍 on the ones that are close to what you are suggesting and maybe leave a comment with your specific use case there. Thanks.

**Comment by janpio** [comment]
See linked issues under label.
