### ISSUE TITLE
`SyntaxError: Unexpected end of JSON input` with Prisma 2.x and specific Node version(s)

### ISSUE THREAD

**Issue by ThalKod** [prisma/prisma#14834]
### Bug description

Since this morning all my call to _**model.findMany**_ are giving me this error when running on Heroku: 

![Screenshot 2022-08-16 at 15 04 31](https://user-images.githubusercontent.com/32584079/184887195-8860feb5-ccbf-4b8e-9100-5919e829ed92.png)

But it's working fine when i'm running my project locally. It's the same code on heroku but the findMany calls are not working...

This is the of code for the above error: 

```
    const pendingBets = await prisma.bet.findMany({
        where: {
            status: 0
        },
    });
```

### Environment & setup

- OS: MacOs
- Database: PostgreSQL
- Node.js version: 16.15.0

### Prisma Version

```
2.30.3
```

**Comment by wemersonpdev** [comment]
Hi, how are you?

I've some tips for you:

1 - Run script to generate build local, and run folder dist/build.

2 - Use npx prisma generate after run build.

3 - Verify if your migrations already run.

**Comment by morifuji-koudai** [comment]
me too

**Comment by morifuji-koudai** [comment]
@ThalKod 
I 'm in the same situation.
But I changed Node version to 17.x as below, then it just worked!

// package.json

```diff
  "engines": {
+    "node": "17.x"
  },
```

**Comment by bzuker** [comment]
I'm having the same issue, is it coming from a dependency? It works correctly locally

**Comment by ThalKod** [comment]
I updated from prisma 2 to prisma 4 and look like it’s working correctly again for me.

**Comment by trek** [comment]
This also started occurring for me this about 7 hours ago.

**Comment by chuckstock** [comment]
Just started happening for us as well on prisma@2.23

**Comment by trek** [comment]
@chuckstock @ThalKod @bzuker @morifuji-koudai are you also on Heroku? Or is this issue occurring on other hosts.

**Comment by trek** [comment]
Like @morifuji-koudai I was able bump my node to `17.x` for Heroku and this resolved the issue. I wasn't able to to do a Prisma 2 -> 4 upgrade as this would require some code changes we're not ready to make yet.

**Comment by chuckstock** [comment]
@trek We're on fly.io.

**Comment by trek** [comment]
@chuckstock so it doesn't seem to be related to a specific host and started happening for all of us suddenly. Is there possibly a dependency for prisma 2.x that wasn't locked to specific version and had a breaking change?

**Comment by trek** [comment]
@chuckstock and just to clarify, you're not using Fly.io's "turboku" offering? https://fly.io/blog/new-turboku/

**Comment by brettgrigsby** [comment]
@trek That's correct. (I work with @chuckstock )

**Comment by brettgrigsby** [comment]
Experiencing this same issue. We are using a Nexus plugin that prevents us from upgrading to v4. Anyone on the Prisma team have ideas related to the broken dependency?

**Comment by jonaldinger** [comment]
This broke for us (using Prisma v2.30.3) when upgrading from Node v16.16 to v16.17 (released Aug 16, 2022). Pinning Node to v16.16 fixed the issue. It appears Node updated its JSON escape sequences to align with the JSON spec (`\v`, specifically) and v2 of Prisma seems to reference that escape sequence in its code. 

Changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V16.md#16.17.0
PR: https://github.com/nodejs/node/pull/43206
Commit: https://github.com/nodejs/node/commit/486dcd7c69b3601252373cca7a132b67a0125fb8

**Comment by janpio** [comment]
Anything for us at Prisma to do here? If this is isolated to Prisma 2.x and a specific Node version, and upgrades work to avoid that I feel like we can't really do more than to make sure everyone that could be affected can find this issue and fine these workarounds you thankfully documented here?

**Comment by jonaldinger** [comment]
@janpio no, thanks, since this is isolated to specific version combinations of Prisma and Node, I wouldn’t expect anything to be done from Prisma other than keeping the issue discoverable for others who might run into it. It might help to make the issue title slightly more generic, as our issue wasn’t with “findMany” specifically. “Unexpected end of JSON input” is the bit that helped me locate this GitHub issue. We’ve already been planning to upgrade Prisma to a more recent version - this just provides some extra motivation 🙂

**Comment by janpio** [comment]
And closing the issue to signal that there is nothing for us to do. 

Everyone finding this via Google, please read above how to fix this (upgrade Prisma or change Node version). Thanks.

**Comment by hazzik** [comment]
For those who stuck on PrismaJS v2 it would be possible to mitigate the issue by enabling `napi` preview feature in the schema file:

```
previewFeatures = ["napi"]
```
