### ISSUE TITLE
Prisma's SQL Server Jest Tests Fails --> `my_db`: the URL must start with the protocol `sqlserver://`

### ISSUE THREAD

**Issue by bandinopla** [prisma/prisma#14851]
### Bug description

Working on the prisma source codes, i've opened the repo inside of a devcontainer. When trying to run the Jest tests of the migrate package i get this error when it gets to the SQLServer portions. But looking at the code at https://github.com/prisma/prisma/blob/main/TESTING.md **TEST_MSSQL_JDBC_URI_MIGRATE** does start with a "sqlserver://"

![console capture](https://i.imgur.com/fLuXgJs.jpeg)

### How to reproduce

1. open the prisma repo inside of a [devcontainer](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) sharing the same network as the host and [follow the steps to contribute guide](https://github.com/prisma/prisma/blob/main/CONTRIBUTING.md) to set it up. 
2. also, on the host, launch the [`docker/docker-compose.yml`](https://github.com/prisma/prisma/blob/main/docker/docker-compose.yml) container
3. on the devcontainer, open a terminal window in `/workspaces/prisma/packages/migrate`
4. run `pnpm run test -- MigrateDev.test -t "create first migration"`
5. everything will complete except the SQL Server tests... because it will say: 
 
```
Error validating datasource `my_db`: the URL must start with the protocol `sqlserver://
````

### Expected behavior

for the SQL Server tests to complete with no error.

### Environment & setup

- OS: Docker Image: https://github.com/prisma/prisma/blob/main/.devcontainer/Dockerfile
- Database: SQl Server
- Node.js version: v16.15.1
- Brand new clone of: https://github.com/prisma/prisma

### Prisma Version

- Brand new clone of: https://github.com/prisma/prisma
-Commit: 3398d4f9241bc4a0b25201eb3e81b877346d82a1

**Comment by janpio** [comment]
This has not popped up again, so we can definitely close this.
