### ISSUE TITLE
queryRaw SELECT COUNT - the letter n is added to the number

### ISSUE THREAD

**Issue by akylkb** [prisma/prisma#14883]
### Bug description

```
prisma.$queryRaw`SELECT COUNT(*) total FROM users`
```

Result:
```json
[ { total: 870n } ]
```

Because of this I get a serialization error: Do not know how to serialize a BigInt

### How to reproduce

prisma.$queryRaw`SELECT COUNT(*) total FROM users`

### Prisma information

prisma: 4.2.1
@prisma/client: 4.2.1

### Environment & setup

- OS: Mac os
- Database: Mysql
- Node.js version: v16.15.1

### Prisma Version

```
4.2.1
```

**Comment by apprat** [comment]
Using prisma.table.count() returns a number type, but using SQL returns a bigint
