### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by jdmelendez** [prisma/prisma#14897]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.15.1           | 
| OS              | windows            |
| Prisma Client   | 4.2.1              |
| Query Engine    | 2920a97877e12e055c1333079b8d19cee7f33826|
| Database        | sqlserver          |

## Logs
```
t dirname Cnode_modules\.prisma\client
prisma:client relativePath ..\..\..\prisma
prisma:client cwd C:\prisma
prisma:client clientVersion 4.2.1
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:tryLoadEnv Environment variables loaded \.env
prisma:client clientVersion 4.2.1
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup

prisma:client clientVersion 4.2.1
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by garrensmith** [comment]
@jdmelendez thanks for the error. Could you provide the query and the schema you used to create this panic. That will help us solve this issue.

**Comment by janpio** [comment]
Ping @jdmelendez

**Comment by janpio** [comment]
Can you help us out here @jdmelendez? With the current information we unfortunately will need to close the issue as it is not enough to understand what is going on and reproduce it. Thanks!

**Comment by janpio** [comment]
Closing then until someone provides more information. Please comment or open a new issue. Thanks!
