### ISSUE TITLE
UTF-8 Error: index is not a char boundary

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#14895]
Command: `prisma format`
Version: `4.1.1`
Binary Version: `8d8414deb360336e4698a65aa45a1fbaf1ce13d8`
Report: https://prisma-errors.netlify.app/report/14219 
OS: `arm64 darwin 21.6.0`

**Comment by tomhoule** [comment]
This is a very specific code path, multi-byte characters in comments in general are completely fine.
