### ISSUE TITLE
Prisma migrate incorrectly infers new migration needed when `dbgenerated` contains a string.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [prisma/prisma#14917]
### Bug description

Giving a default db generated value with a string in it leads Prisma Migrate to think a new migration is always needed:

```
datasource db {
  provider = "cockroachdb"
  // ...
}

model Test {
  id BigInt @id @default(autoincrement())
  foo Int
  bar String @default(dbgenerated("'hello world'"))
}
```

### How to reproduce

1. Use the schema above
2. Create new migration
3. Run `prisma migrate dev` again
4. See Prisma prompt for a new migration 🐞 

### Expected behavior

Prisma doesn't prompt to create a new migration after the first one is created.

### Prisma information

See above

### Environment & setup

- OS: macOS 12.4
- Database: Cockroach v22.1.5
- Node.js version: 14.17.6

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by AndrewSouthpaw** [comment]
Interestingly, I was able to work around the original non-repro example by casting my string literals as `STRING`:

```
  id String @id @default(dbgenerated("replace(substr(gen_random_uuid()::STRING, 0, 26), '-'::STRING, ''::STRING)"))
```

But that same fix doesn't work for my example case:

```
  bar String @default(dbgenerated("'hello world'::STRING")) // doesn't work
```

Looking at the table, I notice there's actually 3 colons:

```
root@:26257/gather> show  create table "Test";
  table_name |                    create_statement
-------------+----------------------------------------------------------
  "Test"     | CREATE TABLE public."Test" (
             |     id INT8 NOT NULL DEFAULT unique_rowid(),
             |     foo INT4 NOT NULL,
             |     bar STRING NOT NULL DEFAULT 'hello world':::STRING,
             |     CONSTRAINT "Test_pkey" PRIMARY KEY (id ASC)
             | )
```

but changing that in the schema prisma doesn't fix the issue either:

```
  bar String @default(dbgenerated("'hello world':::STRING")) // doesn't work either
```

**Comment by janpio** [comment]
Can you run `prisma db pull` and see what it replaces the `dbgenerated` string with? Usually that is a way to get it to tell you what it "expects" for the roundtrip to work.

**Comment by AndrewSouthpaw** [comment]
It replaces it with just a plain default string:

```ts
// original
  bar String @default(dbgenerated("'hello world'"))

// pulled
  bar String @default("hello world")
```

I did a slightly more complicated one because I was curious:

```ts
// original
  test String @default(dbgenerated("replace(substr(gen_random_uuid()::STRING, 0, 26), '-', '')"))

// pulled
  test String @default(dbgenerated("replace(substr(gen_random_uuid()::STRING, 0, 26), '-'::STRING, ''::STRING)"))
```

Good to know about the `pull` trick I'll try that next time I find myself in a situation where it keeps trying to migrate.

I think casting all the strings is an eyesore, but at least it works.

**Comment by AndrewSouthpaw** [comment]
Which is to say: I think the repro steps still technically illustrate a bug, and I definitely ran into confusion around the example with

```
  test String @default(dbgenerated("replace(substr(gen_random_uuid()::STRING, 0, 26), '-', '')"))
```

but I'm betting some notes in the docs somewhere might help. Maybe I could [contribute to the dbgenerated section](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#dbgenerated)?

**Comment by janpio** [comment]
We don't disagree that casting everthing is not pretty, but unfortunately that is how the database gives us back the values. In theory we could try to parse the SQL and detect that with and without cast might be the same, but... yeah we might better not. I can imagine a hundred ways how that could go wrong.

I _like_ solving this with documentation, but what would you add there? I am not sure we can properly explain this problem, especially not in the schema _reference_.

**Comment by AndrewSouthpaw** [comment]
> I can imagine a hundred ways how that could go wrong.

Yeah, agreed.

I think you raise a good question. I guess it depends on what tone or style you want in your docs. For me, I could see something like this fitting under the remarks:

> String values in `dbgenerated` may not match what the DB returns as the default value, because values such as strings may be explicitly cast (e.g. `'hello'::STRING`). When a mismatch is present, Prisma Migrate will indicate a migration is needed. You can use `prisma db pull` to infer the correct value to resolve the issue.

I definitely understand it feeling like it doesn't fit there. I think I bias toward docs that try to steer people out of stumbling blocks, perhaps at the expense of not being strictly a _reference_. The `db pull` trick is definitely a "once you know, you know", but it's very easy to not know. 

Thoughts?

**Comment by janpio** [comment]
Yeah, works for me and is definitely better than not having anything (and later someone from Docs might figure out how to better structure that hopefully) 👍 Go for it 🚀

**Comment by AndrewSouthpaw** [comment]
Thanks! Done 😄
