### ISSUE TITLE
Environment variables not available when using Wrangler 2

### ISSUE THREAD

**Issue by drzamich** [prisma/prisma#14924]
### Bug description

When using the Data Proxy feature on the Cloudflare Workers runtime I'm getting an error caused by what I think is inability of Prisma edge client to access env variables set by Wrangler.
What's important to note is that I'm using Wrangler 2 (what you get by default if you run `npm i wrangler`). It's different than what's used in the [ecosystem-tests](https://github.com/prisma/ecosystem-tests/tree/dev/dataproxy/cloudflare-workers) where the legacy Wrangler 1 is used.

```
Your worker has access to the following bindings:
- Vars:
  - CF_DATA_PROXY_URL: "..."

...

'Uncaught Error: InvalidDatasourceError: Datasource "db" references an environment
  variable "CF_DATA_PROXY_URL" that is not set\n'
```

### How to reproduce

1. `git clone git@github.com:prisma/ecosystem-tests.git`
2. `cd ecosystem-tests/dataproxy/cloudflare-workers`
3. `npm i `
4. `npm i -D wrangler`
5. `npm uninstall @cloudflare/wrangler`
6. `source ./prepare.sh`
7. Remove `usage_model = ''` line from `wrangler.toml`
8. `npx prisma generate --data-proxy`
9. `npx wrangler dev src/index.ts`

### Expected behavior

There's no error.

### Prisma information

As in the [example](https://github.com/prisma/ecosystem-tests/tree/dev/dataproxy/cloudflare-workers).

### Environment & setup

- OS: macOS Monterey 12.1
- Database: PostgreSQL
- Node.js version: 16.13.2

### Prisma Version

Experienced it in my project on `4.2.1`. Reproduced also on `4.3.0-dev.48`.

**Comment by drzamich** [comment]
I did some investigation on the issue and found out that the root cause is the different global object between Wrangler 1 (a.k.a `@cloudflare/wrangler`) and Wranger 2 (a.k.a. `wrangler`).

When trying to access env vars, Prisma does the following:

[`packages/client/src/generation/utils/buildInjectableEdgeEnv.ts#74`](https://github.com/prisma/prisma/blob/main/packages/client/src/generation/utils/buildInjectableEdgeEnv.ts#L74)
```ts
const cfwEnv = `typeof global !== 'undefined' && global['${envVarName}']`
```
This works for Wrangler 1. For Wrangler 2 however, `global` is `undefined`. I couldn't find any documentation on the matter but it seems that Wrangler 2's runtime is an actual service worker, because the global object referenced with `self`.

The fix couldn't be simpler - replacing `global` with `globalThis` on the above mentioned line does the job. `globalThis` is runtime-agnostic and will always return the global object.

**Comment by yamiteru** [comment]
Still doesn't work..

**Comment by yamiteru** [comment]
Still doesn't work.. 

```
ReferenceError: DATABASE_URL is not defined.
Attempted to access binding using global in modules.
You must use the 2nd `env` parameter passed to exported handlers/Durable Object constructors, or `context.env` with Pages Functions.
```

I generate with `prisma generate` and run dev with `wrangler dev --local`.

**Comment by janpio** [comment]
Please open a new issue with a full description of your problem. Thanks.
