### ISSUE TITLE
Postinstall script fails with PNPM workspaces due to npm ERR! Cannot read properties of null (reading 'matches')

### ISSUE THREAD

**Issue by ErlanBelekov** [prisma/prisma#14944]
### Bug description

When running `pnpm install` in a monorepo, with this structure
```
packages
    server
         prisma
               schema.prisma
    shared-utils
         package.json
    web
         package.json
pnpm-workspace.yaml
package.json
```

I get this error:
```
#0 2.239
#0 2.239 > @hub/shared-utils@1.0.0 generate /app/packages/shared-utils
#0 2.239 > pnpm prisma generate
#0 2.239
#0 36.80 Prisma schema loaded from ../server/prisma/schema.prisma
#0 451.1 npm ERR! Cannot read properties of null (reading 'matches')
#0 451.2
#0 451.2 npm ERR! A complete log of this run can be found in:
#0 451.2 npm ERR!     /root/.npm/_logs/2022-08-23T02_34_57_814Z-debug-0.log
#0 451.2 Error: Command failed with exit code 1: npm install -D prisma@3.15.2
#0 451.3 undefined
#0 451.3 /app/packages/shared-utils:
#0 451.3  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @hub/shared-utils@1.0.0 generate: `pnpm prisma generate`
#0 451.3 Exit status 1
```

my package `shared-utils` installs `prisma`, `web` depends on `shared-utils`

`shared-utils` has a custom `postinstall` script, which generates Prisma client from custom location(from `server` package).
This is `package.json` of `shared-utils`
```
{
  "name": "@example/shared-utils",
  "version": "1.0.0",
  "main": "dist/src/index.js",
  "types": "dist/src/index.d.ts",
  "private": true,
  "license": "MIT",
  "scripts": {
    "build": "rm -rf dist && tsc --build",
    "test": "jest",
    "precommit": "eslint --ext .ts \"*/**/*\" --fix && prettier --write .",
    "postinstall": "pnpm prisma generate"
  },
  "dependencies": {
    "currency.js": "^2.0.4",
    "@prisma/client": "3.15.2",
    "date-fns": "^2.28.0"
  },
  "devDependencies": {
    "@example/eslint-config": "1.0.0",
    "@example/prettier-config": "1.0.0",
    "prisma": "3.15.2"
  },
  "prisma": {
    "schema": "../server/prisma/schema.prisma"
  },
  "prettier": "@example/prettier-config",
  "jest": {
    "preset": "ts-jest",
    "roots": [
      "src"
    ],
    "modulePaths": [
      "src"
    ],
    "moduleDirectories": [
      "node_modules"
    ]
  }
}

```

### How to reproduce

1. Go to project root.
2. Run `pnpm install`
3. See error

### Expected behavior

`pnpm install` installs packages, and Prisma schema is generated automatically

### Environment & setup

- OS: Mac OS,
- Database: PostgreSQL
- Node.js version: 16.13.1

### Prisma Version

```
3.15.2
```

**Comment by ErlanBelekov** [comment]
works now magically

**Comment by janpio** [comment]
Can you maybe create a new project, and generate the minimal setup that is required to reproduce this and put it on GitHub? That would be best for us to reproduce - and then potentially fix the issue. Thanks.

**Comment by ErlanBelekov** [comment]
sure @janpio , I'll try to do this in next few days approx.

**Comment by whexy** [comment]
Same problem here.
A temporary workaround is to use `pnpm add @prisma/client` after `prisma generate`.

**Comment by ErlanBelekov** [comment]
@whexy could you show the full code for workaround please?

**Comment by ErlanBelekov** [comment]
@janpio when will Prisma support PNPM? 👀

seems like this is related to these issues, but I still haven't managed to make it work
https://github.com/prisma/prisma/issues/9848
https://github.com/prisma/prisma/discussions/12501

**Comment by ErlanBelekov** [comment]
adding `public-hoist-pattern[]=*prisma*` to `.npmrc` file fixed this issue, took the solution from here

https://github.com/prisma/prisma/issues/12921

**Comment by timmeade** [comment]
> Same problem here. A temporary workaround is to use `pnpm add @prisma/client` after `prisma generateor 

This worked for me

**Comment by heyfirst** [comment]
> Same problem here. A temporary workaround is to use pnpm add @prisma/client after `prisma generateor

This worked for me too

**Comment by millsp** [comment]
Hey folks, we have just improved our `pnpm` detection logic to fix this issue, and we will release this in our `4.13.0` release. That said, you can try it now by installing our `dev` version. `npm install prisma@dev`. Feedback welcome!

**Comment by jlemrond** [comment]
@millsp Some feedback for you.  Installed `prisma@dev` with `pnpm`, fixed the issue and worked like a charm.  Thanks.
