### ISSUE TITLE
prisma/client crashes when used with older versions of react-refresh

### ISSUE THREAD

**Issue by tmcw** [prisma/prisma#14953]
### Bug description

(this is summarizing https://github.com/prisma/prisma/discussions/14939 this discussion)

In my application in development I'm using `react-refresh`, unfortunately an older version. When I run this application with `@prisma/client`, I run into a conflict between Prisma, which defines this Proxy object with a getter that throws on any known access:

https://github.com/prisma/prisma/blob/6d7f68d4b3c52e90c909dde95a6638799fb9417b/packages/client/src/runtime/strictEnum.ts#L30-L42

and react-refresh, which freely accesses a property on any object it can find:

https://github.com/facebook/react/blob/37cb732c59863297e48f69ac1f6e2ba1aa1886f0/packages/react-refresh/src/ReactFreshRuntime.js#L324-L333

Newer versions of react-refresh are safer in this access, but it might be a more general issue that this sort of proxy can be dangerous.

### How to reproduce

1. Use an older version of react-fresh
2. Use prisma/client with at least one enum

### Expected behavior

There shouldn't be a conflict between these dependencies

### Prisma information

- @prisma/client@4.2.1

### Environment & setup

- OS: macOS
- Database: Postgres
- Node.js version: 18

### Prisma Version

```
4.2.1
```

**Comment by danstarns** [comment]
Please can you provide something we can run to reproduce?

**Comment by horsewin** [comment]
i was also encountered this problem.

In my case, other dependencies, blitz 1.x, haved used old `@prisma/sdk` internally and this was looks like root cause ( i know `@prisma/sdk` have already been deprecated).

I resolved this problem by updating `@prisma/sdk` version at once.
