### ISSUE TITLE
Prisma Website has a not working link to slack 

### ISSUE THREAD

**Issue by younes-alouani** [prisma/prisma#14961]
### Bug description

Many software and github libraries have slack or discord channels to disccus and help each other. I don't find something similar for prisma. 
Prisma Website has a not working link to slack 

### How to reproduce

Go to https://www.prisma.io/ 

In the footer, we find a link to slack : https://slack.prisma.io/ 

The link is broken ! 

### Expected behavior

Such as a mature open source solution should have a communcation channel for its community ! 

### Environment & setup

Go to https://www.prisma.io/ 

In the footer, we find a link to slack : https://slack.prisma.io/ 

The link is broken ! 

### Prisma Version

Go to https://www.prisma.io/ 

In the footer, we find a link to slack : https://slack.prisma.io/ 

The link is broken !

**Comment by danstarns** [comment]
<img width="944" alt="Screenshot 2022-08-24 at 08 42 29" src="https://user-images.githubusercontent.com/35999252/186360354-eb7aa8ea-7c66-44bd-b7da-83a452412f17.png">

Just visited this fine, both from your pasted link and from clicking the slack logo at the bottom of the site. Closing this - Please reopen If you're still experiencing an issue.
