### ISSUE TITLE
can't connect db in container (node 16)

### ISSUE THREAD

**Issue by Atsuyoshi-Funahashi** [prisma/prisma#14971]
### Discussed in https://github.com/prisma/prisma/discussions/14970

<div type='discussions-op-text'>

<sup>Originally posted by **Atsuyoshi-Funahashi** August 24, 2022</sup>
Hi. I am currently creating an application in Next.js and using mysql for the DB.
I am building the environment with docker. Originally I was using node version 17.6.0 and it was working fine.

## Problem
I have lowered my node version to 16.13.0 in order to install NextAuth.
After that, when I launch the container with `docker compose up --build`, the following error occurs during migration.

```
# error
Error: P1001: Can't reach database server at `mysql`:`3306`
Please make sure your database server is running at `mysql`:`3306`
```
Since this did not occur when node version was 17, I would like to know how to solve this problem.

## Version
```
node  16.13.0
prisma 4.2.1
mysql 5.7
```

## reproduction method
```
1  create next app
2 install and init prisma
3 Copy-paste the file below.
4 docker compose up --build
```

## File
Dockerfile, docker-compose.yml, run.sh, and .env are as follows
```
## Dockerfile
FROM node:17.6.0

RUN mkdir /test
WORKDIR /test
COPY . /test
RUN yarn add create-next-app
COPY run.sh /usr/bin/run
RUN chmod +x /usr/bin/run
EXPOSE 3000

CMD ["run"]
```

```
## docker-compose.yml
version: '3'
services:
  db:
    image: mysql:5
    platform: linux/x86_64
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./tmp/db:/var/lib/mysql
  app:
    build: .
    volumes:
      - .:/test
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - db

```

This is run.sh. Please set under the project root.
```
# run.sh
#!/bin/sh

bash -c "sleep 30 && yarn -s run prisma migrate dev --name init && yarn install && yarn dev "
```

This is .env
```
# .env
MYSQL_HOST = 'mysql'
MYSQL_DATABASE = 'database_name'
# MYSQL_USER = 'root'
MYSQL_ROOT_PASSWORD = ''
DATABASE_URL="mysql://root:@mysql:3306/database_name"

```</div>

**Comment by danstarns** [comment]
This looks like a docker networking issue. Try refrencing the docker service `db` directly in the `.env` file: 

```diff
MYSQL_HOST = 'mysql'
MYSQL_DATABASE = 'database_name'
# MYSQL_USER = 'root'
MYSQL_ROOT_PASSWORD = ''
- DATABASE_URL="mysql://root:@mysql:3306/database_name"
+ DATABASE_URL="mysql://root:@db:3306/database_name"
```

I am going to close this because I don't see it as a bug, please look into [docker networking](https://docs.docker.com/network/) for further info.

**Comment by Atsuyoshi-Funahashi** [comment]
Thank you for your comment.
I've tried this change, however it doesn't works.

**Comment by goda-kazuki** [comment]
@Atsuyoshi-Funahashi @danstarns 
I am experiencing the same problem.

I am using node:16.17.0 Docker container. 😢

**Comment by goda-kazuki** [comment]
I don't know if this is related, but I added connect_timeout and now I can connect stably.

```
DATABASE_URL="mysql://docker:docker@db:3306/docker?connect_timeout=30"
```

**Comment by Suniron** [comment]
Same error here.

If i run the prisma steps (generate & migrate) directly in a package.json's script (after docker compose build), it works!

I think also that is an internal docker network error...

**Comment by Suniron** [comment]
> I don't know if this is related, but I added connect_timeout and now I can connect stably.
> 
> ```
> DATABASE_URL="mysql://docker:docker@db:3306/docker?connect_timeout=30"
> ```

What is the equivalent in PostgreSQL?
