### ISSUE TITLE
Support fullTextSearch with MongoDB

### ISSUE THREAD

**Issue by mr0b0t0** [prisma/prisma#14984]
## Problem

To achieve like this with native mongo: MyModel.find({$text: {$search: searchString}})
Or, LIKE with SQL

It's now only possible with findRaw

... .findRaw({
    filter: {
      $text: {
        $search: "...,
      },
    },
  })

## Suggested solution

Support fullTextSearch with MongoDB (currently only MySQL and Postgres are supported, https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search)

**Comment by janpio** [comment]
Duplicate of https://github.com/prisma/prisma/issues/9413
