### ISSUE TITLE
findMany where condition - OR wrapped in a NOT changes to AND

### ISSUE THREAD

**Issue by cantoute** [prisma/prisma#14985]
### Bug description

I'm very new user of Prisma, so unless I've missed something big, OR wrapped in a NOT changes to AND.

If this is a desired behavior I'm missing the logic.

I've tried `NOT( ... AND ...)` it doesn't change to OR

I am testing on sqlite database with prisma 4.2.1

```ts
    const edgeRootIds = [1, 2];

    const edges = await this.prismaLog.edge
      .findMany({
        select: {
          nodeId: true,
        },
        where: {
          NOT: {
            nodeId: {
              in: edgeRootIds,
            },
            OR: {
              revNodeId: {
                in: edgeRootIds,
              },
            },
          // this works:
          // AND: {
          //   NOT: {
          //     revNodeId: {
          //       in: edgeRootIds,
          //     },
          //   },
          // },
          },
        },
      });

```

the generated sql.
```sql
SELECT `main`.`Edge`.`nodeId` FROM `main`.`Edge`
WHERE
  (NOT
    (
      `main`.`Edge`.`nodeId` IN (?,?)
      AND `main`.`Edge`.`revNodeId` IN (?,?)
    )
  )
LIMIT ? OFFSET ?
```

### Expected behavior

That the sql generated would have a `OR`

```sql
SELECT `main`.`Edge`.`nodeId` FROM `main`.`Edge`
WHERE
  (NOT
    (
      `main`.`Edge`.`nodeId` IN (?,?)
      OR `main`.`Edge`.`revNodeId` IN (?,?)
    )
  )
LIMIT ? OFFSET ?
```

### Prisma information

I was running this on a simple query on a single model.

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by cantoute** [comment]
seems I was not using the NOT write, if not passing it an array, it becomes an AND... but still I think it should not change a OR to AND.

```
        where: {
          NOT: [
            {
              nodeId: {
                in: edgeRootIds,
              },
            },
            {
              OR: {
                revNodeId: {
                  in: edgeRootIds,
                },
              },
            },
          ],
        }
```

And a much simpler way to write it...
```
where: {
  nodeId: {notIn: edgeRootIds},
  revNodeId: {notIn: edgeRootIds}
}
```

**Comment by danstarns** [comment]
> seems I was not using the NOT write, if not passing it an array, it becomes an AND... but still I think it should not change a OR to AND.
> 
> ```
>         where: {
>           NOT: [
>             {
>               nodeId: {
>                 in: edgeRootIds,
>               },
>             },
>             {
>               OR: {
>                 revNodeId: {
>                   in: edgeRootIds,
>                 },
>               },
>             },
>           ],
>         }
> ```
> 
> And a much simpler way to write it...
> 
> ```
> where: {
>   nodeId: {notIn: edgeRootIds},
>   revNodeId: {notIn: edgeRootIds}
> }
> ```

Does this fix your issue, can we close this?

**Comment by cantoute** [comment]
This fixes my issue.

Thanks.
