### ISSUE TITLE
[Introspection] "error: Field 'x' is already defined on model 'y'.", `@map` clashes

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1499]
Current logic to make field names safe is causing follow up problems:

```
"error: Field 'B' is already defined on model 'batting'.
  -->  schema.prisma:100
   | 
99 |   B         Int?    @map('2B')
100 |   B         Int?    @map('3B')
   | 
"
```

Here both `2B` and `3B` were mapped to `B`, which causes this clash and error message.

**Comment by janpio** [comment]
Similar error message can also be caused by relation naming, that problem is tracked here: https://github.com/prisma/prisma2/issues/1103

**Comment by sorenbs** [comment]
Just to clarify - the current rule is that if a column name starts with a number, we use the `@map` directive to map it, and we change the field name to a safe value by simply removing the number.

DECISION: I would like to either 

1. ignore this case (and accept this will cause trouble for some schemas), or 
2. simply comment out the first field that would cause such issue if we can handle the complexity. In this case we would comment out line 100

**Comment by janpio** [comment]
Parent decision: https://github.com/prisma/prisma2/issues/1520#issuecomment-581990070

**Comment by do4gr** [comment]
We should decide on a long term approach to handling naming conflicts. Moving this to product therefore.
