### ISSUE TITLE
Error in migration engine. SQLite timed out during query execution. 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#15015]
It could potentially be related to a [similar issue](https://github.com/prisma/prisma/issues/11789) that occurs in the `client`, rather than in the `cli`.

Command: `prisma migrate deploy`
Version: `4.2.1`
Binary Version: `2920a97877e12e055c1333079b8d19cee7f33826`
Report: https://prisma-errors.netlify.app/report/14247 
OS: `x64 linux 5.10.0-16-amd64`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/flavour/sqlite/connection.rs:29:57] Timed out during query execution.

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

    at handlePanic (/home/app/.local/share/pnpm/store/v3/tmp/dlx-409373/node_modules/.pnpm/prisma@4.2.1/node_modules/prisma/build/index.js:92130:25)
    at ChildProcess.<anonymous> (/home/app/.local/share/pnpm/store/v3/tmp/dlx-409373/node_modules/.pnpm/prisma@4.2.1/node_modules/prisma/build/index.js:92139:15)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

Rust Stacktrace:
```
Starting migration engine RPC server
[migration-engine/connectors/sql-migration-connector/src/flavour/sqlite/connection.rs:29:57] Timed out during query execution.
```

**Comment by janpio** [comment]
Note: there are multiple issues about this now all grouped under https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+Timed+out+during+query+execution%22 One of them is https://github.com/prisma/prisma/issues/10403 which points out that our error message here is currently highly misleading and should be changed/fixed.

**Comment by crimson-med** [comment]
I'm having the same issue. Is there any updates to get this fixed?

**Comment by dev-xo** [comment]
> I'm having the same issue. Is there any updates to get this fixed?

Same here.

**Comment by Nedi11** [comment]
Bump

**Comment by Jolg42** [comment]
While trying a reproduction for https://github.com/prisma/prisma/issues/11789, I found out that adding `?connection_limit=1` to the `url` made this error disappear.
Example
```
    generator client {
      provider = "prisma-client-js"
    }
    
    datasource db {
      provider = "sqlite"
      url      = "file:./dev.db?connection_limit=1"
    }
```

If you try that, let us know if that changes anything, I'm curious 👀

**Comment by jkomyno** [comment]
@Jolg42 I can confirm that `?connection_limit=1` does the trick, as also reported [here](https://github.com/prisma/prisma/issues/9562#issuecomment-1242491767).

**Comment by jkomyno** [comment]
Thanks @Jolg42. I'd try that, yet I'm not able to reproduce the problem above. And since this was an automatic error report, we don't really have anybody to ask for a reproduction to.

**Comment by apolanc** [comment]
After having an internal conversation, we decided to close this issue for now as it has been difficult or impossible to reproduce.

If anyone is affected in any way by this, please create a new issue with a reproduction of the problem.
