### ISSUE TITLE
EACCES error when deploying to Lambda functions

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma#15029]
> ### Bug description
> 
> Using Prisma with NestJS and PlanetScale, which is deployed to a Lambda. I have made the query engine binary available as a layer. The location of this layer is:
> 
> /opt/prisma-binary
> 
> I have set the above value as PRISMA_QUERY_ENGINE_BINARY. When I try to run a create request, I get the following error:
> 
> ```
> Invalid `this.prisma.user.create()` invocation in
> /var/task/src/lambda.js:482655:43
> 
>   482652     throw new Error("Not found. Proceeding to create!");
>   482653   }
>   482654 } catch (_a4) {
> → 482655   user = await this.prisma.user.create(
>   spawn /opt/prisma-binary EACCES
>     at RequestHandler.request (/var/task/src/lambda.js:123709:19)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async PrismaService._request (/var/task/src/lambda.js:124590:22)
>     at async AuthService.verifyOTP (/var/task/src/lambda.js:482655:20) {
>   code: 'EACCES',
>   clientVersion: '3.15.2',
>   meta: undefined
> }
> ```
> This works locally, but gives the above error on lambda.
> 
> Running it on ARM and not the x86 machines.
> 
> ### How to reproduce
> 
> Source Code: [core-feat-serverless.zip](https://github.com/prisma/prisma/files/9434976/core-feat-serverless.zip)
> 
> Execute: 
> `yarn install`
> 
> Change the serverless.yml file to any dummy org you create in your Serverless Dashboard. then run
> 
> `yarn sls deploy`
> 
> 
> 
> 
> ### Expected behavior
> 
> Lambda function should be deployed.
> 
> ### Prisma information
> 
> 
> 
> 
> ### Environment & setup
> 
> - OS: 
> - Database: 
> - Node.js version: 
> 
> 
> ### Prisma Version
> 
> Prisma version 3.15.2
>

**Comment by nurul3101** [comment]
Reported by @samrith-s

**Comment by samrith-s** [comment]
Hello @janpio I get the same error with the library, which is why I opted for the binary as I had gotten it working before.

**Comment by samrith-s** [comment]
I tried it with the library as well, but even that didn't work. I also updated the environment variable from:
```diff
- PRISMA_QUERY_ENGINE_BINARY
+ PRISMA_QUERY_ENGINE_LIBRARY
```

**Comment by samrith-s** [comment]
Any update on this? We are stuck with our deployment and release due to this issue. 😢

**Comment by janpio** [comment]
Not right now. As with all our issues, it has been categorized and is now waiting until someone has time to reproduce the issue and then potentially fix it.

**Comment by samrith-s** [comment]
@janpio I figured out the error and currently my app deploys properly. The issue was with the environment variable.

The `PRISMA_QUERY_ENGINE_LIBRARY` requires the *path to the actual library file* and not just the folder where it is. So changing the value accordingly, helped get it to work:
```diff
- PRISMA_QUERY_ENGINE_LIBRARY="/opt/prisma-binary"
+ PRISMA_QUERY_ENGINE_LIBRARY="/opt/prisma-binary/libquery_engine-linux-arm64-openssl-1.0.x.so.node"
```

I think the document can be a bit clearer to reflect the path to the actual binary, but so far everything works! 😄

**Comment by janpio** [comment]
Haha, nice! I wondered before why you chose such a weird filename, but 🤷 Should have asked.

Suggestions on how we could improve?
I see we could definitely add a check if the file exists and throw an error message. Can you maybe create a feature request issue for _that_? Thanks.

**Comment by samrith-s** [comment]
I think in the documentation we could mention that the path requires a file name. Current documentation example could be updated like so:
```diff
- PRISMA_QUERY_ENGINE_LIBRARY=custom/my-query-engine-unix
+ PRISMA_QUERY_ENGINE_LIBRARY=custom/my-query-engine-unix.so.node
```

Similar for binary target. Would make it much clearer. In the meanwhile, I will create a feature request for that!

**Comment by janpio** [comment]
That is a good suggestion. Open a PR maybe? https://github.com/prisma/docs/blob/main/content/400-reference/200-api-reference/300-environment-variables-reference.mdx

**Comment by samrith-s** [comment]
Will do. Here is the feature request #15289

**Comment by samrith-s** [comment]
@janpio Here is the PR for it [#3767](https://github.com/prisma/docs/pull/3767)
