### ISSUE TITLE
Remove `schema` property from prisma.yml file

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#1502]
* [x] remove from CLI
* [ ] remove from JSON-Schema
* [x] adjust docs

**Comment by timsuchanek** [comment]
Right now the schema property still is valuable if you don't want to include graphqlconfig, so I wouldn't remove it.

**Comment by marktani** [comment]
with the addition of post deployment hooks, I think we should remove this property :slightly_smiling_face:

**Comment by marktani** [comment]
`schema` has been removed in https://github.com/prismagraphql/prisma/releases/tag/1.7.0.

It is still referenced here: https://github.com/prismagraphql/prisma-json-schema/blob/master/src/schema.json
