### ISSUE TITLE
Extending `PrismaClient` in custom service in a Nest.js application yields wrong typings for `PrismaClient.$on`

### ISSUE THREAD

**Issue by ChristianIvicevic** [prisma/prisma#15020]
### Bug description

The [code example showing how to integrate Prisma with Nest.js](https://www.prisma.io/nestjs) on the Prisma homepage does not behave correctly when attempting to access `Prisma.$on('query', fn)` within the service. Since the `$on` method infers its own typing from the constructor using it to listen to query events works only as long as a client is created inline:
```ts
const client = new PrismaClient({
  log: [
    { emit: 'event', level: 'query' },
    { emit: 'event', level: 'info' },
    { emit: 'event', level: 'warn' },
    { emit: 'event', level: 'error' }
  ],
});
client.$on('query', event => {}); // typings only work for as long as there is at least one `event` in the log options above.
```
Unfortunately when extending the client within a Nest.js application there is no way at all to nudge the typings into the right direction since they are not inferable.
```ts
@Injectable()
export class PrismaService extends PrismaClient {
  public constructor() {
    super({
      log: [
        { emit: 'event', level: 'query' },
        { emit: 'event', level: 'info' },
        { emit: 'event', level: 'warn' },
        { emit: 'event', level: 'error' }
      ],
    });
    // TS2345: Argument of type '"query"' is not assignable to parameter of type '"beforeExit"'
    this.$on('query', (e) => {});
  }
}
```
This can only be silenced using `@ts-ignore` and manually supplementing the type `Prisma.QueryEvent` for `event` but is prone to breaking changes and it looks suspicious. I'd like to understand how to work around this issue, since using the client within the application directly it not an option due to a lack of support for dependency injection and not being idiomatic in terms of working with the Repository pattern. Wrapping the client is also not an option breaking design patterns and paradigms.

### How to reproduce

see above

### Prisma information

not relevant

### Environment & setup

not relevant

### Prisma Version

not relevant

**Comment by annibuliful** [comment]
Could you try this one?
```
export class PrismaService
  extends PrismaClient<{
    log: [
      { emit: 'event'; level: 'query' },
      { emit: 'stdout'; level: 'info' },
      { emit: 'stdout'; level: 'warn' },
      { emit: 'stdout'; level: 'error' }
    ];
    errorFormat;
  }>{}
```
As I checked on Prisma types it seems we have to pass a generic type to get it

<img width="924" alt="Screen Shot 2565-08-29 at 15 14 26" src="https://user-images.githubusercontent.com/5283709/187155850-53444ef2-61f3-4773-8ad3-e83636d702d3.png">

**Comment by ChristianIvicevic** [comment]
I can confirm that this works, even though it's a bit verbose and slight redundancy. But it ensures type-safety at least.

**Comment by ChristianIvicevic** [comment]
I was able to reduce a bit of the redundancy, especially using `typeof options` as the argument for the generic as follows:
```ts
const options = {
  log: [
    { emit: 'event' as const, level: 'query' as const },
    { emit: 'event' as const, level: 'info' as const },
    { emit: 'event' as const, level: 'warn' as const },
    { emit: 'event' as const, level: 'error' as const }
  ],
  errorFormat: process.env.NODE_ENV === 'production' ? ('minimal' as const) : ('pretty' as const)
};

@Injectable()
export class PrismaService extends PrismaClient<typeof options> {
  private readonly _logger = new Logger(PrismaService.name);

  public constructor() {
    super(options);

    this.$on('query', (e: Prisma.QueryEvent) => {
      this._logger.log(e.query);
    });
    this.$on('info', (e: Prisma.LogEvent) => {
      this._logger.log(e.message);
    });
    this.$on('warn', (e: Prisma.LogEvent) => {
      this._logger.warn(e.message);
    });
    this.$on('error', (e: Prisma.LogEvent) => {
      this._logger.error(e.message);
    });
  }

  public enableShutdownHooks(app: INestApplication) {
    this.$on('beforeExit', async () => {
      await app.close();
    });
  }
}
```

**Comment by annibuliful** [comment]
Thank you for sharing your solution to reduce redundant code block.

**Comment by millsp** [comment]
I think this is a TypeScript limitation, take a look at this [issue](https://github.com/microsoft/TypeScript/issues/36456) tracking this. I am therefore closing this issue, but do let me know if you need anything. @ChristianIvicevic's solution looks like a good workaround in the meantime.
