### ISSUE TITLE
introspection crashed

### ISSUE THREAD

**Issue by yashbothra-kointrack** [prisma/prisma#15055]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.15.1           | 
| Prisma CLI  | 4.2.1              | 
| Engine      | 2920a97877e12e055c1333079b8d19cee7f33826| 

## Error
```
Error: [introspection-engine\connectors\sql-introspection-connector\src\re_introspection.rs:489:14] Could not find relation field exchange_metadata on model Tags.
```

**Comment by janpio** [comment]
Do I understand correctly that you have a Prisma schema where you accidentally used the same relation name on two different relations in a model, and then when running (Re-)Introspection again you get this error message?

**Comment by jkomyno** [comment]
(Internal): This happens on `introspection` as well, according to [this report](https://prisma-errors.netlify.app/report/14527)

**Comment by tomhoule** [comment]
This is likely fixed, we should try to confirm that.

**Comment by Weakky** [comment]
Hey @yashbothra-kointrack,

Could you please confirm whether you're still experiencing this issue?

Thank you 🙏

**Comment by jharrell** [comment]
Closing as duplicate of #10453
