### ISSUE TITLE
Unable to run prisma cli in pnpm monorepo from workspace install

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#15081]
### Bug description
In the following screenshot, `p` is `pnpm`.

<img width="756" alt="CleanShot 2022-08-30 at 09 10 19@2x" src="https://user-images.githubusercontent.com/284476/187445411-d0104823-eefc-4a0f-b3ac-a4e19c22566d.png">

### How to reproduce

Create a pnpm monorepo with a few packages. Make them depend on one another such that there is a workspace protocol in their deps in their package json. Make one of those packages a prisma project. Install prisma cli into the workspace (not a specific package). In the prisma project try running `prisma generate` via a package script.

### Expected behavior

Works as if `prisma` were installed in the package rather than the workspace.

### Prisma information

This is just about the cli

### Environment & setup

- OS: n/a
- Database: n/a
- Node.js version: v16.15.1 

### Prisma Version

```
4.2
```

**Comment by U-Wen** [comment]
I have the same problem, but can't resolve until now, I need a handsome's help

**Comment by millsp** [comment]
This has been fixed, we were calling `npm` instead of `pnpm` under the hood.
