### ISSUE TITLE
Prisma 4.3.0 takes 100x more time to generate types

### ISSUE THREAD

**Issue by annibuliful** [prisma/prisma#15109]
### Bug description

V. 4.3.0
<img width="1033" alt="187598994-598fb1a8-ab77-4328-8cad-d986b8f75804" src="https://user-images.githubusercontent.com/5283709/187599235-54e80613-9271-4321-b16d-51bed337027b.png">

V.4.2.1
<img width="1012" alt="Screen Shot 2565-08-31 at 12 27 22" src="https://user-images.githubusercontent.com/5283709/187599096-1bee5420-e012-49e2-a23d-94f32413a798.png">

### How to reproduce

- Generate Prisma type

### Expected behavior

- Generate Prisma type time should be the same

### Environment & setup

- OS: Mac OS, Ubuntu
- Database: PostgreSQL
- Node.js version: 16

### Prisma Version

```
4.3.0
```

**Comment by phongkt-dev** [comment]
Same here, 74 models took 631.71s.
```
Generated Prisma Client (4.3.0 | library) to ./node_modules/@prisma/client in 631.71s
```

**Comment by capaj** [comment]
holey moley that could be why my yarn install is taking so long :scream:

**Comment by capaj** [comment]
Yes same here-with 4.2.1 it took under 3 seconds. 4.3.0 just took 418 seconds.

**Comment by capaj** [comment]
@annibuliful may I suggest you update the title to say `Prisma 4.3.0 takes 100x more time to generate types`, the title as it is does not do justice to the severity of this issue

**Comment by annibuliful** [comment]
@capaj Thank you very much

**Comment by annibuliful** [comment]
My Github Action exceed the limit now 😭 😭 😭 😭 😭

**Comment by jkomyno** [comment]
Hi @annibuliful, @phongkt-dev, @capaj, can you please share your schema with us? It'd be very useful for investigating this issue, thanks.

**Comment by capaj** [comment]
actually I tried with my schema that is open source and there is no slowdown on that schema. It's only the confidential schema where I have the problem.
I will ask my boss for a permission to send this over and get back to you @jkomyno

**Comment by jkomyno** [comment]
Thank you @capaj! You can even send the schema privately to [schemas@prisma.io](mailto:schemas@prisma.io).
We can also sign an NDA for confidentiality if that's deemed necessary.

**Comment by capaj** [comment]
Check you inbox.

**Comment by annibuliful** [comment]
@jkomyno  This is my schema 
https://gist.github.com/annibuliful/570135fd4d9726a2eff7d19de8c155e7

**Comment by janpio** [comment]
Just to make explicit: You did _not_ explicitly enable any of the new preview features we introduced in 4.3.0, correct?

**Comment by annibuliful** [comment]
Yes I used to same as V4.2.1

**Comment by capaj** [comment]
same here-I just have 
```
  previewFeatures = ["interactiveTransactions"]
```

**Comment by Jolg42** [comment]
Thanks for the report and schemas.
@SevInf is working on a fix 👨‍🔧

We'll keep you updated as we are thinking about doing a patch release for this.

**Comment by SevInf** [comment]
Hey everyone!
Fix is now have been merged into `main` branch. It will be released with 4.3.1 later.
If you are experiencing this issue, I'd suggest you hold off 4.3 update until patch is released. 
Alternatively, you can verify that the fix is working for you by used dev snapshot version `4.4.0-dev.14`, but we do not recommend using dev versions in production.

**Comment by capaj** [comment]
tested today with 4.3.1, problematic schema built in 3 seconds. Nicely done!

**Comment by Jolg42** [comment]
Thanks for the feedback!

`4.3.1` is now published https://github.com/prisma/prisma/releases/tag/4.3.1
