### ISSUE TITLE
This is a test (please ignore)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#15116]
Very serious problem!

(related to Correctness)

**Comment by garrensmith** [comment]
Hi, could you provide a schema or a way of reproducing this issue?

**Comment by janpio** [comment]
```prisma
Hi!
```

**Comment by SevInf** [comment]
I don't have a valid prisma schema, but maybe this picture of a duck on subway will work instead?

![image](https://user-images.githubusercontent.com/603056/187683895-4c481e95-db3a-4902-9baf-e2c0308ae496.png)

**Comment by sorenbs** [comment]
LGTM!
