### ISSUE TITLE
Optionally accept non-unique fields in unique CRUD operation methods

### ISSUE THREAD

**Issue by bayramkzk** [prisma/prisma#15143]
## Problem

Suppose I have a `Blog` model and every blog has an `author_id` field that specifies a relation named `author` to `Author` model. A user sends a request to UPDATE or DELETE some specific blog by providing id in the request params. I can perform operations in the unique field by using `where` and providing the blog id but I'd like to make sure the blog belongs to the authenticated user that sent the request. Because the methods for unique operations (`findUnique`, `update`) only accept unique fields to be given in the `where` parameter, I can not check that in a single prisma query. This is especially tedious for `update` and `delete` operations.

## Suggested solution

I think an optional parameter for unique-field operations (`update`, `delete`) alongside `where` such as `check` or `filter` would solve this tediousness. `where` parameter would still be required and accept unique fields whereas `check` would be optional and accept all fields even the non-unique ones. I suppose this approach is better than accepting all non-unique fields in `where` because it still ensures a unique identifier to be provided.

## Alternatives

I am currently using one of the two workarounds I found depending on the context for `update` and `delete`. If the returned data is not important I just use `updateMany` and `deleteMany` as they only return the `count` of fields (1 at most in this case). If the returned data is important I use multiple queries for first reading, then mutating the data with `update` or `delete` after checking if the selected field meets the criteria.

## Additional Context

This example doesn't have to be only about authentication. I could also check if the requested blog's `isDeleted` field set to false.

I suppose Row Level Security can solve this but I think this is something Prisma should provide nevertheless.

**Comment by janpio** [comment]
This has been implemented a while a go and is now generally available: https://www.prisma.io/docs/orm/reference/prisma-client-reference#filter-on-non-unique-fields-with-userwhereuniqueinput
