### ISSUE TITLE
Response time of prisma with mongodb hosted on GCP is very slow compared to mongoose

### ISSUE THREAD

**Issue by ArgekarStudios** [prisma/prisma#15148]
### Bug description

Mongo with mongoose on GCP(nestjs) :- 200ms
Mongo with Prisma on GCP(nestjs):-1345ms

This is the main reason for not using prisma

### Expected behavior

It should be fast

### Prisma information

prisma with monogb
with atlas

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

latest

**Comment by annibuliful** [comment]
I think Prisma team need more time to research and build it to be more compatible with MongoDB

Refs:
https://engineering.hashnode.com/how-did-we-choose-our-next-tech-stack-at-hashnode#heading-prisma

**Comment by garrensmith** [comment]
@ArgekarStudios could you supply your schema and the query you are doing. That would help us find out why this is so slow.

**Comment by kibertoad** [comment]
@ArgekarStudios could you please provide a reproduction? it is not possible to fix "something is slow, please fix" problem

**Comment by janpio** [comment]
Ping @ArgekarStudios - with no additional information we can only close this issue without getting the chance to improve anything.

**Comment by janpio** [comment]
One last time @ArgekarStudios, can you help us with more information? Right now we don't know what to do here.

**Comment by millsp** [comment]
Without your input, we could not reproduce this issue, I am therefore closing it. Please don't hesitate to ping us if you have more information to provide in the future and we will re-open this issue. Thanks.
