### ISSUE TITLE
Nicer Datamodel Type validation

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#15174]
If the provided typename only differs in casing from the allowed ones we should be able to point that out and add a `Did you mean ...`
to the error message. 
<img width="720" alt="Screen Shot 2022-09-04 at 18 36 33" src="https://user-images.githubusercontent.com/16278407/188323920-601c1e17-fa4d-4992-bf1c-820daa28e8eb.png">

**Comment by panoplied** [comment]
Could this be the issue with another repo's code? As far as I understand, this check happens somewhere in datamodel lib in prisma-engines.

https://github.com/prisma/prisma-engines/blob/8b4168996f71f9757ec7855ae603e255710a8fd1/libs/datamodel/diagnostics/src/error.rs#L263

**Comment by janpio** [comment]
Correct, this is functionality in our Rust Engine that is used to provide such functionality.

**Comment by shamim-io** [comment]
Hi @do4gr !
I am new to open-source. I want to contribute to this issue. 
As far as the issue is concerned and the comment by @panoplied , i could see that the validations are happening in `prisma-engines` repo. 
Shall i do the changes in the `prisma-engines` repo or I should write the validation in this repository itself? 
Thanks

**Comment by do4gr** [comment]
Hey, if you want to work on this issue, adapting the code in the prisma-engines repo that does the validation would be the right place.
We are just using the prisma/prisma repo to collect all issues concerning Prisma, but the Rust code lives in prisma/prisma-engines

**Comment by theWolf1198** [comment]
Hi @do4gr ! I am interested in taking up this issue. 
As far as I understand, the fix would be done in the prisma-engines repo, is there any GitHub issue which is already been created for tracking these changes? 
If any such ticket is there, could you please direct me to that ticket.

**Comment by pranayat** [comment]
Hi! I've created a PR for this https://github.com/prisma/prisma-engines/pull/4137
