### ISSUE TITLE
Bug with throwing formatted errors

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma#15180]
### Bug description

I was running a query like this:

```prisma
const res: any = await prisma.role.deleteMany({
      where: {
         organizationDomain: context.userDomain,
         name: role.name,
      },
 });
```

Now, this query violates a foreign constraint (since I have not enabled cascade delete in related model) and prisma is trying to throw an error for this which is valid.

But the issue is that, it fails in formatting the error thrown. I was getting `TypeError: Cannot read properties of undefined (reading 'length')` and when I was trying to debug, I noticed that it came from `node_modules/@prisma/client/runtime/index.js`

And I added some logs to the file and noticed that `invocationLine` was undefined

Just to confirm if this was fixed in latest version, I upgraded to `4.3.1` and I see it there as well.

Stack trace and logs below:
```
nvint-psql           | 2022-09-05 06:38:50.300 UTC [37] ERROR:  update or delete on table "Role" violates foreign key constraint "Assessment_roleOrganizationDomain_roleName_fkey" on table "Assessment"
convint-psql           | 2022-09-05 06:38:50.300 UTC [37] DETAIL:  Key (organizationDomain, name)=(convint.ai, React Test Role) is still referenced from table "Assessment".
convint-psql           | 2022-09-05 06:38:50.300 UTC [37] STATEMENT:  DELETE FROM "public"."Role" WHERE "public"."Role"."id" IN ($1) /* traceparent=00-00-00-00 */
 ---errr:: PrismaClientKnownRequestError: Foreign key constraint failed on the field: `Assessment_roleOrganizationDomain_roleName_fkey (index)`
     at prismaGraphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:20426:12)
     at LibraryEngine.buildQueryError (/app/node_modules/@prisma/client/runtime/index.js:26373:12)
     at LibraryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:26307:22)
     at async RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:29888:24)
     at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:30880:16)
     at async deleteRole (/app/src/modules/role/index.ts:689:23)
     at async field.resolve (/app/node_modules/@envelop/core/cjs/traced-schema.js:36:42)
     at async /app/node_modules/@envelop/core/cjs/orchestrator.js:380:27
     at async /app/node_modules/@pablosz/graphql-helix/process-request.js:161:27
     at async Object.processRequest (/app/node_modules/@pablosz/graphql-helix/process-request.js:66:18) {
   code: 'P2003',
   clientVersion: '4.3.1',
   meta: {
     field_name: 'Assessment_roleOrganizationDomain_roleName_fkey (index)'
   }
 } role.delete EnabledCallSite {
   _error: Error
       at new EnabledCallSite (/app/node_modules/@prisma/client/runtime/index.js:26893:19)
       at getCallSite (/app/node_modules/@prisma/client/runtime/index.js:26919:10)
       at Proxy.<anonymous> (/app/node_modules/@prisma/client/runtime/index.js:29505:22)
       at deleteRole (/app/src/modules/role/index.ts:689:47)
       at /app/node_modules/graphql-modules/index.cjs.js:1634:38
       at dispatch (/app/node_modules/graphql-modules/index.cjs.js:1457:40)
       at composed (/app/node_modules/graphql-modules/index.cjs.js:1463:16)
       at wrappedResolver (/app/node_modules/graphql-modules/index.cjs.js:1634:16)
       at field.resolve (/app/node_modules/@envelop/core/cjs/traced-schema.js:36:48)
       at async /app/node_modules/@envelop/core/cjs/orchestrator.js:380:27
 }
 ---invocationLine undefined
 --err:::: TypeError: Cannot read properties of undefined (reading 'length')
     at getIndent (/app/node_modules/@prisma/client/runtime/index.js:27625:28)
     at getTemplateParameters (/app/node_modules/@prisma/client/runtime/index.js:27588:34)
     at createErrorMessageWithContext (/app/node_modules/@prisma/client/runtime/index.js:27681:30)
     at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:29915:17)
     at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:29907:12)
     at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:30880:16)
     at async deleteRole (/app/src/modules/role/index.ts:689:23)
     at async field.resolve (/app/node_modules/@envelop/core/cjs/traced-schema.js:36:42)
     at async /app/node_modules/@envelop/core/cjs/orchestrator.js:380:27
     at async /app/node_modules/@pablosz/graphql-helix/process-request.js:161:27 {
   clientVersion: '4.3.1'
```

Because of this, I am not able to use `if (err instanceof Prisma.PrismaClientKnownRequestError)` to catch the error as well

### How to reproduce

- Just try violating a foreign constraint
- Use a query like above
- Try to catch and throw the error

### Expected behavior

Prisma throws a valid error

### Prisma information

```prisma
model Role {
  id              String       @id @default(uuid())
  organization    Organization @relation(fields: [organizationDomain], references: [domain])
  name            String
  description     String?
  skills          Json
  creator         User?        @relation(name: "createdRoles", fields: [creatorUsername], references: [username])
  createdDate     DateTime     @default(now())
  creatorUsername String?      @default("vignesh@convint.ai")
  isActive        Boolean      @default(true)
  assessments     Assessment[]
  metadata        Metadata[]

  organizationDomain String @default("convint.ai")

  @@unique([organizationDomain, name], name: "key")
}
```

```ts
const res: any = await prisma.role.deleteMany({
      where: {
         organizationDomain: context.userDomain,
         name: role.name,
      },
 });
```

### Environment & setup

- OS: Ubuntu 20.04
- Database: PostgresSQL
- Node.js version: 18.5.0

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
Preview Features        : interactiveTransactions, fullTextSearch
Done in 2.09s.
```

**Comment by pimeys** [comment]
So I did a quick simple reproduction that does not reproduce the error:

schema.prisma:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model A {
  id  Int     @id @default(autoincrement())
  b   B[]
}

model B {
  id  Int @id @default(autoincrement())
  aId Int
  a  A    @relation(fields: [aId], references: [id])
}
```

Then the script just creates two related records, and tries to delete the parent without a cascade:

```typescript
import { PrismaClient, Prisma } from '@prisma/client'

const prisma = new PrismaClient({
  log: ['query', 'info', 'warn', 'error'],
})

async function main() {
  const b = await prisma.b.create({
    data: {
      a: { }
    },
  })

  console.log(b)

  await prisma.b.delete({
    where: {
      id: b.id
    }
  })
}


main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    if (e instanceof Prisma.PrismaClientKnownRequestError) {
      console.log("IT WORKED")
    }

    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

I see `IT WORKED` in the console, so the basic error handling should work.

I think what might be the issue here is that the `deleteMany` hits the concurrency error currently solved by @garrensmith, which fails in the middle of the process sometimes. Could you maybe confirm @tvvignesh if you can just do a normal delete and catch the error correctly, and you have the issue only with `deleteMany`?

Also a reproduction repo would be super awesome for debugging this.

**Comment by tvvignesh** [comment]
@pimeys Actually it was a normal delete earlier and I faced the same issue, so I switched to deleteMany which again had the same issue. So, in conclusion both does have the issue at my end

**Comment by pimeys** [comment]
Did I miss something then in my reproduction code? Can you take a look and see if it does what it should?

**Comment by aqrln** [comment]
The specific query that triggers this error and the Prisma schema are most likely not relevant here (but thank you @tvvignesh for providing them — I'm saying this just to make sure everyone is on the same page, you did absolutely right by trying to provide as much information as possible in your report).

This looks like a purely client-side issue in the formatting code that would be triggered for any request error and even for client-side validation errors, which prints the error message in the context of the Prisma Client invocation and its surrounding code.

The relevant bits (e.g., the source file in question or perhaps the details about how the code is built and run) might be pretty hard to isolate.

Let's start by figuring out if it could be a regression after refactoring some code related to error handling in Prisma. Can you check if you face the same issue with Prisma 4.2.0?

Another thing to check (and a possible workaround for you until we can fix the problem): when using the latest Prisma, does constructing the client like this prevent the issue for you?

```ts
const prisma = new PrismaClient({
  errorFormat: 'minimal'
})
```

**Comment by aqrln** [comment]
Also, is there anything about your setup that might cause the line numbers in stack traces to be off?

Looking at this error:

```
TypeError: Cannot read properties of undefined (reading 'length')
     at getIndent (/app/node_modules/@prisma/client/runtime/index.js:27625:28)
...
```

The actual line in the runtime bundle of Prisma 4.3.1 where this happens must be `27610` and not `27625`:

```ts
  for (let i = 0; i < line.length; i++) {
```
(`:28` is correct though, it points exactly at `.length`).

`27625` is an unrelated line in other function, and it doesn't even have column 28.

Is the file modified by any chance (e.g., it also goes through the transpiler) or is the stack trace just incorrect?

Back to the original error that arises from your source files: are there source maps involved?

**Comment by aqrln** [comment]
Sorry for so many questions 😅
The one about Prisma 4.2.0 is the most important for now.

**Comment by tvvignesh** [comment]
@aqrln @pimeys Really sorry for the late reply. Just seeing your comments. @SevInf Thanks a lot for the fix. Will try it when the new version releases and update you
