### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by febymathews2022** [prisma/prisma#15193]
### Bug description

```
/home/sfm/Q/qw/node_modules/@prisma/client/runtime/index.js:29221
        data: JSON.parse(await getStream(response.body))
                   ^
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Connection.raw (/home/sfm/Q/qw/node_modules/@prisma/client/runtime/index.js:29221:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BinaryEngine.request (/home/sfm/Q/qw/node_modules/@prisma/client/runtime/index.js:29941:43)
    at async cb (/home/sfm/Q/qw/node_modules/@prisma/client/runtime/index.js:36464:26) {
  clientVersion: '2.30.3'
```

### Expected behavior

Whenever i run the files I get this Unexpected end of input.Why is this happening?

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: v16.17.0

### Prisma Version

```prisma                : 2.30.3
@prisma/client        : 2.30.3
Current platform      : debian-openssl-1.1.x
Query Engine (Binary) : query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at ../node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine      : migration-engine-cli b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at ../node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine  : introspection-core b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at ../node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary         : prisma-fmt b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at ../node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash  : b8c35d44de987a9691890b3ddf3e2e7effb9bf20
Studio                : 0.423.0

```

**Comment by danstarns** [comment]
Hi @febymathews2022 please can you share your Prisma schema and a query that causes this crash

**Comment by afeurra** [comment]
I had the same issue on Node 16.17.0, had to go back to 16.10.0 to avoid it.

**Comment by janpio** [comment]
The same problem does not exist in current versions of Prisma.

**Comment by febymathews2022** [comment]
> I had the same issue on Node 16.17.0, had to go back to 16.10.0 to avoid it.
> 
> Edit: using @prisma/client 2.26.0.

**Comment by febymathews2022** [comment]
I updated to Node v17 and it worked.The node v16 was causing the problem.

**Comment by febymathews2022** [comment]
> Hi @febymathews2022 please can you share your Prisma schema and a query that causes this crash

It wasnt the issue with the schema but the Nodev16.17.0

**Comment by alfredvaa** [comment]
@febymathews2022 If you got it working by changing node version I think this is still a bug and it should remain open. I had the same issue, trying with 16.15.1 instead for now.

**Comment by s-kris** [comment]
This error happens in 16.19.0.

I reverted back to 14.20.0.

**Comment by hazzik** [comment]
Duplicate of #14834

**Comment by hazzik** [comment]
For those who stuck on PrismaJS v2 it would be possible to mitigate the issue by enabling `napi` preview feature in the schema file:

```
previewFeatures = ["napi"]
```
