### ISSUE TITLE
50x slower than raw MySQL when joining tables

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma#15200]
### Bug description

Normal queries do have around 8% overhead from raw SQL, but in the case of a query with join (synonym), the overhead turns into an insane number. From my observations, the more rows I query for, the worst the problem is in the non-linear time scale. The number of joins does affect it greatly too, but there it makes much more sense since it results in more queries and many operations in the "user land".

### How to reproduce

1. Ask me for permission for https://github.com/Akxe/prisma-debug (it is a private repo, due to sensitive informations)
2. Clone https://github.com/Akxe/prisma-debug
3. Run `npm i`
4. Import `Dump20220810.sql` into your mysql
5. Set up `.env` file with your user and password for the generated DB schema/tables
6. Run `npm run start`
7. See the time it took to retrieve the rows
MySQL

### Expected behavior

Raw SQL takes 0,4s Prisma took 21,55s.

Some overhead is tolerable, but this is way too much.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions", "tracing"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model CarrierPhoto {
  carrierID Int     @map("nCis")
  order     Int     @default(autoincrement()) @map("verze") @db.TinyInt
  src       String  @map("fName") @db.VarChar(200)
  carrier   Carrier @relation(fields: [carrierID], references: [carrierID], onDelete: NoAction, onUpdate: NoAction, map: "fotorl_nosic")

  @@id([order, carrierID])
  @@index([carrierID], map: "nCis")
  @@map("fotorl")
}

model Carrier {
  carrierID       Int            @id @map("NCis")
  origin          CarrierOrigin  @default(others) @map("Zdroj")
  supplierID      Int            @map("idDod") @db.UnsignedSmallInt
  type            String         @map("Typ") @db.Char(1)
  city            String         @map("Mesto") @db.VarChar(80)
  street          String         @map("Ulice") @db.VarChar(80)
  description     String?        @map("Popis") @db.VarChar(250)
  dimensions      String         @map("Velikost") @db.VarChar(20)
  regionID        Int?           @map("idKraj") @db.UnsignedTinyInt
  /// Some supplier do have their own number system, we preserve it in this column
  supplierNumber  String?        @map("VCis") @db.VarChar(20)
  anguleToRoad    Int            @default(0) @map("Poloha") @db.TinyInt
  Osvetleni       Int            @default(0) @db.TinyInt
  Videt           Int            @default(0) @db.TinyInt
  NPozn           String?        @db.VarChar(500)
  lng             Float?
  lat             Float?
  orientation     Int?           @default(-1) @map("Azimut") @db.SmallInt
  GPSOverriten    Boolean        @default(false) @map("GpsNase")
  textOverriten   Boolean        @default(false) @map("TextNase")
  traffic         Int?           @map("Prujezd")
  size            Float          @default(0) @map("Plocha") @db.Float
  sizeCoef        Int?           @map("kVel") @db.TinyInt
  placeCoef       Int?           @map("kPol") @db.TinyInt
  lightCoef       Int?           @map("kOsv") @db.TinyInt
  visibilityCoef  Int?           @map("kVid") @db.TinyInt
  exclusivityCoef Int?           @map("kExkl") @db.TinyInt
  surroundingCoef Int?           @map("kOkolo") @db.TinyInt
  districtID      Int?
  photos          CarrierPhoto[]

  @@index([districtID], map: "district_idx")
  @@index([supplierID], map: "nosic_dodavatel_idx")
  @@index([regionID], map: "nosic_kraj_idx")
  @@map("nosice")
}

enum CarrierOrigin {
  old    @map("S")
  SVO    @map("V")
  others @map("O")
  extra  @map("X")
  rsFoto @map("R")

  @@map("nosice_Zdroj")
}

```

```ts
import { CarrierOrigin } from '@prisma/client';
import { prisma } from './prisma';


async function main() {
	console.time('findMany with filter');
	const r2 = await prisma.carrier.findMany({
		select: {
			carrierID: true,
			city: true,
			street: true,
			lat: true,
			lng: true,
			type: true,
			orientation: true,
			traffic: true,
			photos: {
				select: {
					src: true,
					order: true,
				},
			},
		},
		where: {
			type: {
				in: ['A', 'B', 'G'],
			},
			origin: {
				in: [
					CarrierOrigin.rsFoto,
					CarrierOrigin.others,
				],
			},
			lat: { gt: 0 },
			lng: { gt: 0 },
		},
	});
	console.timeEnd('findMany with filter');
	console.log(`Returned ${r2.length} results`);
}

main();
```

### Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: v16.13.2

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
Preview Features        : interactiveTransactions, tracing
```

**Comment by janpio** [comment]
(Can you invite @jkomyno please? Thanks.)

**Comment by Akxe** [comment]
@janpio Done, @jkomyno's invite is now pending

**Comment by jkomyno** [comment]
Thank you @Akxe, I have now access to your private repository. Will write back here once we have new updates on this!

**Comment by Akxe** [comment]
@jkomyno Any information on this? It have been long time

**Comment by janpio** [comment]
Unfortunately not @Akxe, query performance is not really our focus yet so we could not spend the time on reproducing this yet. I know that is not great, but are totally planning to get to that and then take a look and then hopefully reproduce and fix it.

**Comment by Akxe** [comment]
`Returned x results` and `findMany with filter` + a time. However, when you put the same query into MySQL workbench, you will get the same result orders of magnitudes faster...

**Comment by janpio** [comment]
Yeah, this number now looks much more than what I am seeing as well - not even close to 50x or the 20s+ mentioned in the original issue, fortunately.

My import ended up being 11733 results by the way - not sure where that difference comes from.

---

The query from the script (I enabled query logging and am also outputting the duration that is returned from the Prisma Engine):
```
Duration: 158ms
Duration: 191ms
findMany with filter: 608.195ms
Returned 11733 results
```

The same queries as `$queryRawUnsafe` in Prisma:
```
Duration: 91ms
Duration: 134ms
raw sql: 533.037ms
```

Same queries with the `mysql` Node library:

```
mysql: 347ms
```

And via Dbeaver, a database GUI:
```
Query 1: 30ms
Query 2: 88ms
```

Note that the Dbeaver numbers are only the raw database query, nothing at all about constructing that into a data structure or massaging the data into a certain type. That happens on the UI thread and is not measured. It would also just crash when it showed all rows at the same time, so it only loads 200 at a time from memory :D 

Prisma on the other hand needs to turn the resulting data into a Json of 131366 lines, roughly 6153kb (!), of data.

So from my perspective, Prisma is less than 2 times slower than the most barebones Node MySQL client that returns completely raw data. That is not great, and worth investigating if we can improve that with the amount of work we do on the data to bring it into a nice structure.

**Comment by janpio** [comment]
Or do you have a different "raw query" then the 2 that Prisma generates @Akxe? Prisma doesn't use a JOIN here by default, but does 2 queries and combines those manually. Maybe _that_ makes the difference you are describing.

**Comment by Akxe** [comment]
I don't get it; it was so consistent! It was always a problem. And now neither latest nor the fixed version in the private repo does reproduce the 20-second time...

Let's close this as it magically fixed itself. 

-----

I tested the production server, and the query that used to take 50 seconds now takes less than 1.
