### ISSUE TITLE
[Introspection] Guardrail: Comment out, avoid ripple effects

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1523]
What could be commented out?
- models
- fields
- enums
- relations

This will lead to a ripple effect of problems in other models and general usage.

What could be the logic to avoid the ripple effects?
1. required field => comment out model
2. commented out model => comment out relation fields

**Comment by janpio** [comment]
Easy way to start thinking about this: 
What happens if we comment out all the tables that we identify as `no-id-field-defined-without-unique-and-without-relations` right now? Start looking into only schemas in `mysql_public` and see what happens.

**Comment by janpio** [comment]
We took care of the `no-id-field-defined-without-unique-and-without-relations` things by commenting them out: https://github.com/prisma/prisma2/issues/1491

Other problems might need the same treatment.

**Comment by do4gr** [comment]
One ripple effect that is currently not handled is that fields with unsupported types could currently still be referenced by `@@index`, `@@id`, `@@unique`.
