### ISSUE TITLE
Builder pattern

### ISSUE THREAD

**Issue by Spartaques** [prisma/prisma#15272]
## Problem

there are no way how to build queries in prisma. I can’t find it in doc. I don’t know how people use prisma. For me, it’s raw product because of next problems:
1. I can’t build query using prisma. Let’s consider a query that consist from joining more that 10 tables and more than 20 filters that are optional. How can I build such a query using prisma? Maybe I don’t understand smth but how I can do it?2. 
You guys are not Orm, because prisma is Active Record pattern.

**Comment by annibuliful** [comment]
I'm not sure I understand you correctly. Do you need Prisma work as Query builder? If so I recommend you to use knexjs instead. Prisma is built as ORM to help us get data from DB easily.
I never use laravel before but I saw some examples that might be related to KnexJS 


<img width="655" alt="Screen Shot 2565-09-12 at 11 17 23" src="https://user-images.githubusercontent.com/5283709/189573025-8ca402a7-c640-47ca-b4af-24d71ebd13d9.png">

<img width="667" alt="Screen Shot 2565-09-12 at 11 17 17" src="https://user-images.githubusercontent.com/5283709/189573009-565b2671-b442-4e5a-a774-62626f98aae3.png">


You can see how does Knex work here => https://knexjs.org/guide/query-builder.html

**Comment by Spartaques** [comment]
hah. What i want from ORM (active record in this case):
1. Work with write part of app using models and oop approach
2. Work with read part by constructing queries with joins and conditions

What prisma provide for me:
1. works great
2. working with queries using relations and building queries using native objects

BUT
1.relations in always subquery, so if i have 10 relations it will be 10 sub queries.
2. i dont have any possibility to construct by query conditions using some conditional filters.

So, explain me please how to do thing like this in prisma:

`$this
            ->withoutGlobalScope('filterApp')
            ->select(
                \DB::raw('(SELECT count(*) FROM workers WHERE workflow_program_id = programs.id and status != 0) as analytics'),
                \DB::raw('(SELECT count(*) FROM workers WHERE workflow_program_id = programs.id) as number_of_version'),
                'users.name as user_name',
                'users.id as user_id',
                'programs.id',
                'programs.name',
                'programs.type as program_type',
                \DB::raw('(SELECT DATE_FORMAT(IFNULL(workers.cron_date, workers.start_date),"%Y-%m-%dT%TZ")) as start_date'),
                'programs.description',
                \DB::raw('(SELECT DATE_FORMAT(workers.created_at, "%Y-%m-%dT%TZ")) as created_at'),
                \DB::raw('(SELECT DATE_FORMAT(workers.updated_at, "%Y-%m-%dT%TZ")) as updated_at'),
                'workers.type as type',
                'workers.schedule as schedule',
                'workers.state as state',
                DB::raw('If (programs.published_workflow is Not null, workers.version, 0) as version'),
                \DB::raw("
                     CASE 
                     WHEN data_resources.resourcable_type = '".Segment::SHORTNAME."' 
                    THEN (SELECT name FROM segments WHERE id = data_resources.resourcable_id) 
                    END resource_name"),
                \DB::raw("
                     CASE 
                     WHEN programs.status = 0 THEN 'Archive' 
                     WHEN workers.status = 0 THEN 'Design' 
                     WHEN workers.status = 1 THEN 'Active' 
                     WHEN workers.status = 2 THEN 'Stop'
                     WHEN workers.status = 3 THEN 'Done'
                     ELSE 'Design'
                     END status
                     "),
                'data_resources.resourcable_type',
                'data_resources.resourcable_id',
                'data_resources.id as data_resources_id',
                'programs.tags as tags'
            )
            ->leftJoin(
                'workers',
                'workers.id',
                '=',
                DB::raw('CASE WHEN programs.published_workflow is not null
                    THEN programs.published_workflow
                    ELSE
                    (
                      Select id From workers WHERE workflow_program_id = programs.id order by version DESC limit 1
                   
                    )  
                    END')
            )
            ->leftJoin('worker_resources', \DB::raw('SUBSTRING(workers.start_node, 10)'), '=', 'worker_resources.id')
            ->leftJoin('data_resources', 'data_resources.id', '=', 'worker_resources.resource_id')
            ->leftJoin('users', 'users.id', '=', 'workers.user_id')
            ->where('programs.app_id', App::$APPID)
            ->orderBy($filters['order_col'] ?? 'updated_at', $filters['order_dir'] ?? 'desc');

        return DB::table(DB::raw("({$query->toSql()}) as sub"))
            ->mergeBindings($query->getQuery())
            ->when(isset($filters['status']), function (Builder $query) use ($filters) {
                $query->whereIn('status', $filters['status']);
            })->when(isset($filters['type']), function (Builder $query) use ($filters) {
                $query->where('type', $filters['type']);
            })->when(isset($filters['created_at']), function (Builder $query) use ($filters) {
                $query->whereDate('created_at', $filters['created_at']);
            })->when(isset($filters['id']), function (Builder $query) use ($filters) {
                $query->where('id', $filters['id']);
            })->when(isset($filters['search']), function (Builder $query) use ($filters) {
                $query->where(function (Builder $query) use ($filters) {
                    $fields = ['user_name','name','description','resource_name','status'];
                    foreach ($fields as $field) {
                        $query->orWhere($field, 'like', '%'.$filters['search'].'%');
                    }
                });
            })->when(isset($filters['start_date']), function (Builder $query) use ($filters) {
                $query->whereDate('created_at', '>=', Carbon::parse($filters['start_date']));
            })->when(isset($filters['end_date']), function (Builder $query) use ($filters) {
                $query->whereDate('created_at', '<=', Carbon::parse($filters['end_date']));
            })/*->when(isset($filters['resource']), function (Builder $query) use ($filters) {
                $query->where('resourcable_type', $filters['resource']);
            })*/->when(isset($filters['resource']), function (Builder $query) use ($filters) {
                $query->where('data_resources_id', $filters['resource']);
            })
            ->when(isset($filters['execution_range']), function (Builder $query) use ($filters) {
                $startDate = Carbon::parse($filters['execution_range'][0] ?? null);
                $endDate = Carbon::parse($filters['execution_range'][1] ?? null);
                $query->whereIn('type', [Worker::PERIODICAL,Worker::ONCE]);
                $query->whereDate('start_date', '>=', $startDate);
                $query->whereDate('start_date', '<=', $endDate);
            })->when(isset($filters['name']), function (Builder $query) use ($filters) {
                $query->where('name', 'like', '%'.$filters['name'].'%');
            })->when(isset($filters['user']), function (Builder $query) use ($filters) {
                $query->whereIn('user_id', $filters['user']);
            })->when(isset($filters['program_type']), function (Builder $query) use ($filters) {
                $query->where('program_type', $filters['program_type']);
            })->paginate($filters['per_page'] ?? static::PAGINATE);`

**Comment by annibuliful** [comment]
Oh I read your sample it's very complicated to use Prisma

**Comment by danstarns** [comment]
I don't think this is really an issue, bug, or feature request. Already mentioned in the replies to this, Prisma is an ORM and with that, we provide a different level of abstraction to that of a Query Builder. 

You may find that our interactive transactions feature can help you 'build' a query so to say and I suggest you check out that here: https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide#interactive-transactions-in-preview

I am going to close this but please feel free to comment with more ideas that you may have.

**Comment by Spartaques** [comment]
Ok guys, so you say that prisma is next generated solution, but i provide you with case that is similar for all apps, and you just say prisma can't solve this case. Please, use smth else. 
So maybe i will have knex.js with prisma in my project. 
But for me, it's better to create own solution that like prisma but with normal query Builder or pick TypeORM.

**Comment by Spartaques** [comment]
It's not completed, it's a open question without solution.

**Comment by annibuliful** [comment]
As you know Prisma is very new to provide us with type-safe. If you need comprehensive query builder functionality please create new feature request 😄
