### ISSUE TITLE
Feature request: Automatically read library or binary from folder

### ISSUE THREAD

**Issue by samrith-s** [prisma/prisma#15289]
## Problem

Currently, the documentation states that we can provide our own path for the query engine library or binary using the environment variables:
- `PRISMA_QUERY_ENGINE_LIBRARY`
- `PRISMA_QUERY_ENGINE_BINARY`

But if we provide the value to these variables as a path to a location in the disk where these files are stored rather than the file itself, then Prisma is unable to ratify that and throws an `UnhandledException`.

## Suggested solution

- Prisma should check the value for the above environment variables
- Determine if it is a directory or not 
- If it is a directory, then it should try to find one of the listed targets in the mentioned folder
- If not, directly try to consume the file

**Comment by janpio** [comment]
Figuring out the file is not possible and far to magic.
What we can do, is to throw an error if you point to a directory instead of a file - which will surface it to you that you should point to a file and not a directory.

Can you create a feature request for that error message instead? Thanks.

**Comment by samrith-s** [comment]
I don't understand why it is not possible since the current error message anyway tells me what my current OS target is, and whether it is a library or a binary that it couldn't find. 

This is simply an enhancement on it which is as simple as:
```ts
path.existsSync(config.resolvedQueryEngine)
```

**Comment by janpio** [comment]
The env var is supposed to point to a file, and that file can be named whatever you want. There is no need to follow the same naming pattern. So just assuming the name when the env var points to a folder might lead to unexpected files to be used instead of what was originally desired. As it would also be magic and behind the scenes, that would be a nightmare to debug.
