### ISSUE TITLE
[Introspection] Future handling of "Model does not have @id or @@id, it contains no unique and no possible relation" (`no-id-field-defined-without-unique-and-without-relations`)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1531]
If there is nothing we can use as an identifier, we have a hard time supporting a table. But we can offer some minimal version of support.

This is how PHPmyAdmin does it:
![image](https://user-images.githubusercontent.com/183673/73869063-e92bdd80-4849-11ea-91fb-58fecb842c9a.png)

**Comment by janpio** [comment]
Triage: While the API surface of this seems simple enough, it would still be a massive implementation effort in the Query Engine to make it work.

**Comment by tomhoule** [comment]
Introspection now supports models without identifiers thanks to `@@ignore` and `@ignore`.
