### ISSUE TITLE
Slightly improve error message `Error: Unknown database type slite:`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1533]
When you have a wrong protocol in your datasource, e.g. `slite:` instead of `sqlite:` you get this error message:

`Error: Unknown database type slite:`

This could be improved slightly:

`Error: Unknown database type 'slite:'`

(possibly replace ' by `)

**Comment by slomek** [comment]
As much as I would like to try to tackle it, I believe this has already been solved:

![Screenshot 2020-10-16 at 8 55 19 PM](https://user-images.githubusercontent.com/4399871/96298008-08425800-0ff2-11eb-8f57-a7efffe9a192.png)

Unless there is another way to reproduce the original issue, in which case please let me know 😉

**Comment by janpio** [comment]
Thanks for confirming the fix @slomek
