### ISSUE TITLE
Error querying the database: database disk image is malformed 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#15359]
Command: `prisma migrate dev --name dev --schema src/database/queue/schema.prisma`
Version: `4.2.1`
Binary Version: `2920a97877e12e055c1333079b8d19cee7f33826`
Report: https://prisma-errors.netlify.app/report/14295 
OS: `x64 win32 10.0.19044`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine\connectors\sql-migration-connector\src\flavour\sqlite\connection.rs:29:57] Error querying the database: database disk image is malformed

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new
```

Rust Stacktrace:
```
Starting migration engine RPC server
[migration-engine\connectors\sql-migration-connector\src\flavour\sqlite\connection.rs:29:57] Error querying the database: database disk image is malformed
```

**Comment by janpio** [comment]
Manually also reported at: https://github.com/prisma/prisma/issues/15372

**Comment by janpio** [comment]
Internal Note: @tomhoule thinks this might be related to how we do resets, so we should try to reproduce this.

**Comment by Jolg42** [comment]
Looks related https://github.com/prisma/prisma/issues/6366

Note: I closed this as part of the issue intake process
