### ISSUE TITLE
Additional seeding workflows

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#1536]
* [ ] `prisma reset` should reset the database and initiate seeding if a `seed` property is present (optionally provide `--no-seed` flag)
* [ ] `prisma import` should accept a `.graphql` file for seeding
* [x] `prisma seed` (optional): Run seed according to `seed` property in `prisma.yml`. This would be convenient, but developers needs to make sure to run `prisma reset` before (if she so wishes).
* [ ]  more ideas here: https://github.com/graphcool/prisma/issues/1181

Right now, the best workflow to "start from scratch" + seeding is this:

```sh
prisma seed --reset
```

**Comment by marktani** [comment]
Right now, the best workflow to "start from scratch" + seeding is this:

```sh
prisma delete
prisma deploy
```

I think the suggested behaviour of `prisma reset` above would be super cool.

**Comment by FredyC** [comment]
Yes, I just used `prisma reset` expecting it will seed data from `seed.graphql` only to find out it didn't. I think it doesn't make much sense to have seed file there as a part of initial boilerplate while its modification doesn't matter as it cannot be used anymore.

**Comment by gihrig** [comment]
@FredyC 

What's so hard about 

>prisma delete
>prisma deploy

It works fine for me.

**Comment by FredyC** [comment]
@gihrig It's not about hard, but about some sort of comfort and I bet it's even faster to just reset data then destroy and recreate the whole service. For automated tests having extra seconds does matter, especially if you need to reset several times to ensure a clean slate.

**Comment by steve-a-jones** [comment]
Really looking forward to this feature - destroying services each time for the sake of resetting seeds is overkill.

**Comment by marktani** [comment]
We added `prisma seed` in `1.7.1`:

```
prisma seed # seed data according to `seed` property in `prisma.yml`
prisma seed --reset # reset service before seeding.
```

**Comment by delta98** [comment]
@marktani great news on `prisma seed` would it be worth updating the documentation to show that this is now possible?

https://www.prisma.io/docs/reference/service-configuration/prisma.yml/yaml-structure-ufeshusai8#seed-(optional)

**Comment by 2rhop** [comment]
## Hello
I'm starting a new project for automating the seeding on multiples db with **_javascript_** and [knex.js](http://knexjs.org), please have a look at [this ](https://github.com/2rhop/knex-seeder)and let me hear your [**recommends**](https://github.com/2rhop/knex-seeder/issues), thanks

here is a code example:

```javascript
//creating and seeding process
ks.createAndSeed(userTableModel, 10).then(() => {
    //creating the table automatically & seeding ...
    ks.createAndSeed_close(roleTableModel, 10, (table) => { //closes the connection after process
        //creating the table with knex.js fn & and seeding ...
        table.increments(),
            table.string('name'),
            table.string('category'),
            table.timestamps(true, true)
    }).then(()) =>{
        //do something here...
  }
})
```

#### One code to seed them all!
<img src="https://raw.githubusercontent.com/2rhop/knex-seeder/master/assets/logo.png" height=120 /><img src="https://camo.githubusercontent.com/b2c7efaeb746c3fadea6796914a22e8d03bb43c8/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f72656c656173652f3272686f702f6b6e65782d7365656465722f616c6c2e737667" > <img src="https://camo.githubusercontent.com/44e55c99e870e355e1383829f99dc4ec4ff53075/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f6c6963656e73652f3272686f702f6b6e65782d7365656465722e737667" >

**Comment by marktani** [comment]
Thanks for sharing @2rhop, can you elaborate how this is relevant for Prisma? 🙂

**Comment by DamianPereira** [comment]
Is graphcool cli going to support this too?

I'm using graphcool-framework and not prisma, and I need to import a .graphql file for seed data. Should I open a new issue in the graphcool-framework repository?

**Comment by jasonleonhard** [comment]
If like me you wanted to clear the db and then re-seed:

    prisma reset
    y
    prisma seed

**Comment by viztor** [comment]
It was mentioned that we can supply a script for seeding, does that mean it is just a hook, and no method from prisma is injected?

**Comment by corysimmons** [comment]
@marktani It's not relevant. He's advertising his OSS (with logos and self-thumbs-up and everything)... 🤦‍♂️
