### ISSUE TITLE
findFirst type doesn't return null

### ISSUE THREAD

**Issue by jtmarmon** [prisma/prisma#15368]
### Bug description

Follow up from this slack discussion https://prisma.slack.com/archives/CA491RJH0/p1663004924546619

The types return from `findFirst` seem to not be nullable, which is incorrect. 

### How to reproduce

A reproduction can be found here (https://github.com/jtmarmon/prisma-types-repro). Follow the steps in the readme

### Expected behavior

That the returned type from `findFirst` would be `T | null` instead of `T`

### Prisma information

See repo

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v18.9.0

### Prisma Version

https://github.com/jtmarmon/prisma-types-repro/blob/main/yarn.lock
```
"@prisma/client@4.3.1":
...
"prisma@4.1.1:"
```

**Comment by annibuliful** [comment]
As far as I know Prisma officially introduced https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#findfirstorthrow. could you use it instead?

**Comment by SevInf** [comment]
Can not reproduce this using provided repo:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/603056/191036393-4f74cbf0-bc61-4cd9-b41e-c6e7fb25ec58.png">

Also note that the version of `prisma` and `@prisma/client` mismatch, which may lead to all kinds of unexpected behavior. We strongly advice to use the same version for both packages.

**Comment by jtmarmon** [comment]
@SevInf did you run `npx tsc main.ts`?

**Comment by jtmarmon** [comment]
Got it. Apparently I got tricked into thinking I had a repro because [calling tsc with a specific file causes the tsconfig to be ignored](https://stackoverflow.com/questions/52645072/why-does-the-tsc-command-not-show-compiling-errors-when-used-to-compile-a-specif). and I do get a compiler error as expected if I run `npx tsc`
