### ISSUE TITLE
Erro on migrate SQLite DB

### ISSUE THREAD

**Issue by paulolima1212** [prisma/prisma#15372]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`migrate dev`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.15.1           | 
| Prisma CLI  | 4.2.1              | 
| Engine      | 2920a97877e12e055c1333079b8d19cee7f33826| 

## Error
```
Error: Error in migration engine.
Reason: [migration-engine\connectors\sql-migration-connector\src\flavour\sqlite\connection.rs:29:57] Error querying the database: database disk image is malformed

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by janpio** [comment]
I think this is the submitted error report for this: https://github.com/prisma/prisma/issues/15359
