### ISSUE TITLE
Prisma isn't detecting Yarn as package manager

### ISSUE THREAD

**Issue by Xenfo** [prisma/prisma#15377]
### Bug description

My directory structure is 3 directories from `yarn.lock` so `./libs/db/prisma`. Prisma only checks for `yarn.lock` up to `../` so Prisma thinks I'm using NPM and tries to use it to install `@prisma/client`.

https://github.com/prisma/prisma/blob/27c038fa2b61161fb9164f826f0ef1b574dff445/packages/internals/src/predefinedGeneratorResolvers.ts#L169

### How to reproduce

* Create a Yarn workspace, add `libs/*` to workspace and run `yarn install`
* Make a project in `libs/db` and add Prisma
* Try and run `yarn prisma generate` from the `libs/db` dir

### Expected behavior

Prisma uses Yarn

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}

model Users {
  id   BigInt @id
  name String

  @@map("users")
}
```

### Environment & setup

- OS: WSL 2
- Database: CockroachDB
- Node.js version: 18.8.0

### Prisma Version

```
4.3.1
```

**Comment by Xenfo** [comment]
Would recursively going down directories and checking for a `yarn.lock` be a good option? We could also try checking the `workspaces` key to check if we reached root and stop there if there is no `yarn.lock`.

**Comment by macrozone** [comment]
its also broken for yarn-workspaces. So currently, `yarn` is more or less broken

**Comment by iangregsondev** [comment]
Yep this happens to me also, is there a workaround ?

I currently have a little protection in my package.json to ensure nobody uses NPM

```
  "engines": {
    "npm": "please-use-yarn",
    "yarn": ">= 1.22.0",
    "node": ">=16"
  }
```

"please-use-yarn"

So hence when it runs, it tries to use NPM and I get errors.

Is this an error on the latest version - can we downgrade ? Is it recommended ?

Thanks

**Comment by Xenfo** [comment]
For now I manually patched the package. It affects all versions I think.

```diff
diff --git a/build/index.js b/build/index.js
index 5ab351c719c45d7202b013954859cd61de0e5175..44d17104c29002725c26717559fccc1afa931cd8 100755
--- a/build/index.js
+++ b/build/index.js
@@ -90618,7 +90618,7 @@ Please try to install it with ${import_chalk13.default.bold.greenBright("npm ins
   }
 };
 function isYarnUsed(baseDir2) {
-  return (0, import_has_yarn.default)(baseDir2) || (0, import_has_yarn.default)(import_path13.default.join(baseDir2, ".."));
+  return (0, import_has_yarn.default)(baseDir2) || (0, import_has_yarn.default)(import_path13.default.join(baseDir2, "../../.."));
 }
 __name(isYarnUsed, "isYarnUsed");
 function getAddPackageCommandName(baseDir2, dependencyType) {
```

If you are going to use this make sure to change the path to the proper directory with `yarn.lock`.

**Comment by neongreen** [comment]
Hitting this as well. Is it possible to work around without patching? Maybe by creating a dummy yarn.lock or setting an env var?

**Comment by Xenfo** [comment]
I'm not sure, would having a dummy `yarn.lock` mess up monorepo root detection? As far as I know, the lock file for all package managers is in the root directory of the project so tools might just assume that the dummy lock file is the root directory. As for the environment variable, I don't think anything like that exists.

**Comment by millsp** [comment]
This was fixed recently, we now use `@antfu/ni` under the hood to do the detection for us.
