### ISSUE TITLE
Add the possibility to import schemas

### ISSUE THREAD

**Issue by devmanbr** [prisma/prisma#15389]
## Problem
Eventually, as the data grows, the number of models also increases. When relate to them is important, doing so in a single schema file can be stressful.

Some might argue that one could make separate files already in Prisma's current state, but with this it is not possible to guarantee consistency in relationships as currently, especially when considering the use of Prisma's VSCode extension (which helps a lot in this).

So, it would be very important to implement a method that makes importing schemas possible, maintaining consistency between everything.

## Suggested solution
The import could be done using something like `@import(filepath)`, present somewhere in the schema you are importing.

The way it works could be how is in SASS (or even CSS), where, in a way, we can establish the main file and even "omit" the files that should not be compiled.

**Comment by janpio** [comment]
Thanks for the suggestion, I think this is part of https://github.com/prisma/prisma/issues/2377 (where importing individual files is one of multiple approaches).
