### ISSUE TITLE
`Cannot fetch data from service: include is not a function` Error while using Next.js with Data Proxy

### ISSUE THREAD

**Issue by nurul3101** [prisma/prisma#15395]
#### As reported by the end user:

> We are using Prisma 4.2.1 and our database is publicly accessible. Prisma itself was working perfectly fine with the direct database url. It only started failing recently in production when trying to integrate Data Proxy. I have attached screenshots of our configuration. We are using **Nextjs with Prisma** and the attached files show a simple backend request fetching data using Data Proxy, which should be hitting our database. We created a simple lib file to have a single instance of Prisma that we can import into our backend calls. When running the app in a dev environment and running the build files locally, there are no issues with connecting to Data Proxy and fetching and inserting data into our database. Debugging on our end, we have identified that the error is P5010, but are having trouble finding info on how to resolve this issue.
>
> Since we are using Serverless js, we have tried using the prisma/client/edge, as opposed to prisma/client because our application gets deployed to **Cloudfront with Lambda@Edge**, but we have noticed no difference. We have a .env file that imports the variables and have confirmed that the backend call is using the correct Data Proxy url.
> 
> ![CloudwatchLogs](https://user-images.githubusercontent.com/13049676/191041048-d88154ab-de9a-4b3c-a99d-fd7255951a98.PNG)
> 

Message Link for Internal Slack: https://prisma-company.slack.com/archives/C02GF9J74SH/p1654854367720369 

### How to reproduce

> #### Reproduction code:
>
> [Sample-master.zip](https://github.com/prisma/prisma/files/9599800/Sample-master.zip)
> 
> Instructions to run the code are in the `README.md` file in zip folder.
>
> #### AWS Configuration Images:
>
> 1. ![database-config-sample](https://user-images.githubusercontent.com/13049676/191042154-04eebcd6-775f-48fc-aef4-11a37dde4a05.png)
> 2. ![database-config-sample-2](https://user-images.githubusercontent.com/13049676/191042147-fc7b52d9-05b4-493b-87a7-dcd20ab5a20c.png)
> 3. ![database-config-sample-3](https://user-images.githubusercontent.com/13049676/191042150-fb72013a-f3aa-46e2-a7a7-eb10b442c1d7.png)
> 4. ![database-config-sample-4](https://user-images.githubusercontent.com/13049676/191042144-d79fccb9-3542-4663-b7a2-463d379ce895.png)
> 5. ![database-config-sample-5](https://user-images.githubusercontent.com/13049676/191042138-bb37725b-f0dd-45d1-9ad8-4f72174418f9.png)
>
> #### Error Logs Images:
>
> 1. ![error-logs](https://user-images.githubusercontent.com/13049676/191042143-94b4403f-5d50-4ccf-8d0e-be6eef6f1581.png)
> 2. ![error-logs-2](https://user-images.githubusercontent.com/13049676/191042155-37ba1f7c-d694-47e3-a9fd-a20a1ddc5c31.png)

### Expected behavior

Should not get `include is not a function` error.

### Prisma information

The Schema file is in the attached zip folder.

### Environment & setup

- Next.js with AWS Lambda

### Prisma Version

Prisma Version `4.2.1`

**Comment by nurul3101** [comment]
For Internal Use: https://prisma1015.zendesk.com/agent/tickets/2510
This user reported the same error.

**Comment by janpio** [comment]
Another case, a bit older, internal link https://prisma-company.slack.com/archives/C02GF9J74SH/p1654854367720369

```
{
"errors": [
{
"message": "Cannot fetch data from service:\ninclude is not a function",
"locations": [
{
"line": 3,
"column": 5
}
],
"path": [
"factions"
],
"extensions": {
"code": "INTERNAL_SERVER_ERROR",
"exception": {
"code": "P5010",
"clientVersion": "3.15.1"
}
}
}
],
"data": null
}
```
This happens only in the latest prisma client version: 3.15.1
Working as expected on 3.14.0, It’s a **Next.js App on Vercel**

**Comment by nurul3101** [comment]
Reproduction Repository: https://github.com/prisma/issue-15395-reproduction

This error occurs when the output path in the generator is configured. Issue doesn't happen when PrismaClient is generated at default location.

And, Moving the location of `nodeFetch` to be declared above `buildResponse` in generated runtime file fixes this error.

<img width="842" alt="image (20)" src="https://user-images.githubusercontent.com/13049676/215169147-ba553b2b-c202-4d87-a205-9bb591df7c20.png">

**Comment by millsp** [comment]
Note: We will be able to remove our custom node fetch implementation as soon as we deprecate node 14.
