### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: ` \r\n CREATE DEFAULT DF__N_\r\n \tAS 'N'\r\n`"

### ISSUE THREAD

**Issue by leannelim** [prisma/prisma#15391]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.16.0           | 
| Prisma CLI  | 4.3.1              | 
| Engine      | c875e43600dfe042452e0b868f7a48b817b9640b| 

## Error
```
Error: [libs\sql-schema-describer\src\mssql.rs:317:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: ` \r\n CREATE DEFAULT DF__N_\r\n \tAS 'N'\r\n`"
```

**Comment by jkomyno** [comment]
Hi, can you please share your `schema.prisma` file and SQL dump with us? Thank you.
Moreover, which SQL Server version are you currently using exactly?

**Comment by leannelim** [comment]
Hi,

I only changed the `provider` of the `datasource` block in `schema.prisma` to `sqlserver` according to the "Next steps" that appeared when I ran `npx prisma init`.

`
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}
`

Then I ran `prisma db pull` to turn my database schema into a Prisma schema according to #3 of the "Next steps", then the error occurred, so I don't have the SQL dump.

I'm using Microsoft SQL Server Standard (64-bit) v12 in Microsoft Windows NT 6.3.

For your reference, below is the "Next steps" that I'm referring to:
1. Set the `DATABASE_URL` in the `.env` file to point to your existing database. If your database has no tables yet, read https://pris.ly/d/getting-started
2. Set the `provider` of the `datasource` block in `schema.prisma` to match your database: `postgresql`, `mysql`, `sqlite`, `sqlserver`, `mongodb` or `cockroachdb`.
3. Run `prisma db pull` to turn your database schema into a Prisma schema.
4. Run `prisma generate` to generate the Prisma Client. You can then start querying your database.

**Comment by pimeys** [comment]
SQL Server v12 is the same as 2012. Unfortunately we have no ways of testing with this version, especially due to the missing docker images, meaning we cannot test against that version on CI.

Therefore we [officially support](https://www.prisma.io/docs/reference/database-reference/supported-databases) SQL Server versions 2017 and 2019 only, because those have docker images available and we can guarantee them working with our CI.

**Comment by leannelim** [comment]
Thank you for your support. I guess I can't use prisma with SQL Server 2012 🥲
The database was created by other developers, so, I wish I knew. lol

Thanks!
