### ISSUE TITLE
Prisma and Heroku

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#1540]
The only way I could deploy to Heroku was by checking the Prisma client into the version control as done [here](https://github.com/prisma/prisma2-e2e-tests/tree/master/platforms/heroku). 

The alternatives that I tried were: 

1. Prisma client in `node_modules`
2. Prisma client not in `node_modules` but `.gitignored`

In both the cases, I ran into https://github.com/prisma/prisma-client-js/issues/390

This issue tracks investigating this further. 

Note that I already explored the nodejs build back and tried environment variables like `NODE_ENV=test` to skip any pruning (like documented [here](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/dependencies.sh#L94-L97)) with no success. 

This file seems to contain all the logic for bundling in Heroku, we should look at this closely: https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/dependencies.sh

**Comment by marcjulian** [comment]
I was able to deploy a Nestjs + prisma2 application to Heroku. You can find the repo here https://github.com/notiz-dev/notiz-api

**Comment by divyenduz** [comment]
We could make this work in E2E tests: https://github.com/prisma/prisma2-e2e-tests/tree/master/platforms/heroku

The trick was to remove `binaryTargets` from `schema.prisma` file and let the build run in the Heroku CI. 

Please let me know if this doesn't work for anyone by commenting here 🎉
