### ISSUE TITLE
Prisma does not work with Cloudflare Workers (for me)

### ISSUE THREAD

**Issue by yamiteru** [prisma/prisma#15408]
### Bug description

I wanted to use Prisma with Cloudflare Workers so I followed the official guide in docs. Didn't work (problems with env). Eventually I was able to resolve the issue after reading through issues here. But now Prisma shows ones of these errors:

1. `PrismaClient is unable to be run in the browser.`
2. `Datasource URL must use prisma:// protocol when --data-proxy is used` 

### How to reproduce

1. Clone [this reproduction repo](https://github.com/yamiteru/prisma-cloudflare-workers-reproduction)
2. Run `yarn install`

For normal (non-edge) version:
1. Run `yarn generate:normal`
2. Run `yarn dev:normal`
3. Go to `localhost:8787`

For edge version:
1. Run `yarn generate:edge`
2. Run `yarn dev:edge`
3. Go to `localhost:8787`

### Expected behavior

1. Should work locally without routing everything through the Data Proxy
2. Should not see Cloudflare Workers as browser

### Prisma information

Could be found inside the repo.

### Environment & setup

- OS: MacOS 12.6
- Database: PostgreSQL
- Node.js version: 18.7.0

### Prisma Version

```
4.3.1
```

**Comment by yamiteru** [comment]
1. & 2. yes

I'm developing an app that's gonna use Data Proxy in the production. Of course I need to develop it locally so I think I don't really need Data Proxy when developing (but it would be ideal to have some kind of local Data Proxy which would simulate the real one just like Wrangler simulates Cloudflare Workers). But either way with or without Data Proxy it throws an error.

**Comment by janpio** [comment]
Ok thanks for the clarification.

Currently there is no way to use the Edge / Data Proxy Client (which you need when you are using Wrangler) without the remote Data Proxy from Prisma Data Platform. There is (obviously) a feature request for this here: https://github.com/prisma/prisma/issues/14398

Until then I suggest you change your local testing strategy to also use `generate --data-proxy` and a separate Data Proxy connection string. If you set that up correctly, it should work fine with no errors at all.

**Comment by yamiteru** [comment]
Ok so it's exactly as I've feared. Well that sucks. Will try tomorrow and see how inconvenient it is. If it's too inconvenient I'll be forced in using a different setup not including Prisma which I don't wanna do because I really like Prisma. But I need to start working on the project and can't wait months for a better solution to be developed.

**Comment by janpio** [comment]
We understand.

I'll close this issue now, but please report back again if this does not (technically) work for you as I described. You can also leave a +1 on that feature request I linked to, or even share your use case (how you would want to set up your testing locally with wrangler vs. live).
