### ISSUE TITLE
Better error handling for Introspection when JSON-RPC doesn't have an id

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#1543]
See

https://github.com/prisma/migrate/blob/9eec2a09d3722e81b563e0f6afccb773948e9869/src/LiftEngine.ts#L108

and
https://github.com/prisma/prisma2/blob/b80e2028f0af6e7c45aa66645f2c37e8f6b1126c/cli/sdk/src/IntrospectionEngine.ts#L121

Current Example
```
      if (!result.id) {
        console.error(
          `Response ${JSON.stringify(
            result,
          )} doesn't have an id and I can't handle that (yet)`,
        )
      }
```

**Comment by tomhoule** [comment]
Probably not relevant anymore. Candidating for @Jolg42 to take a look.
