### ISSUE TITLE
re-open prisma optional fields are not optional #11927

### ISSUE THREAD

**Issue by joshribakoff-sm** [prisma/prisma#15448]
### Bug description

Same issue as prisma optional fields are not optional #11927

```prisma
model cache {
  id String @id
  build_id String
  expires DateTime
  data Json
}
```

```ts
const build_id = undefined
prisma.cache
    .upsert({
      where: { id: cacheId },
      update: {
        data: res as any,
        expires,
        build_id, // ok, as expected
      },
      create: {
        id: cacheId,
        data: res as any,
        expires,
        build_id, // type error, but expected it to be ok
      },
    })
```

### How to reproduce

Describe above.

### Expected behavior

Describe above.

### Prisma information

Describe above.

### Environment & setup

- OS:  macOS
- Database: PostgreSQL
- Node.js version: 16.14.2

### Prisma Version

3.15.2

**Comment by janpio** [comment]
Why? Please leave a comment in that issue. Thanks.
