### ISSUE TITLE
P1011 TLS error when connecting to AWS Aurora Postgres 11.3

### ISSUE THREAD

**Issue by alibi-tech** [prisma/prisma#15465]
### Bug description

Attempting to connect to AWS Aurora Cluster running Postgres 11.3 during `prisma migrate` results in TLS errors saying the dh key is too small.

The error seen is the following:
```
Error: Error: P1011: Error opening a TLS connection: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../ssl/statem/statem_clnt.c:2157:
    at ensureDatabaseExists (/builds/watchhabitat/habitat/packages/back-end/node_modules/prisma/build/index.js:92865:11)
```

Our AWS Aurora Postgres database cluster is a serverless v1 type with Postgres 11.3 and the default configuration from AWS.
We reproduced this error with Prisma versions 3.0.2 and 3.15.2.

We run the migration during our CICD pipeline inside a Gitlab runner spot instance. This instance uses OpenSSL 1.1.1 and runs node 16.14.2.

### How to reproduce

1. Set up an AWS Aurora Postgres DB with Serverless v1 type and Postgres 11.3. Use the default Postgres settings.
2. Use prisma 3.15.2 and node 16.14.2.
3. Add db url connection string of `postgresql://user:password@endpoint:port/db?schema=schemaName`
4. Run `npx prisma migrate deploy`
5. See error

### Expected behavior

Expect connection and migration with TLS.

### Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

### Environment & setup

Database: AWS Aurora Serverless v1  cluster with Postgres 11.3, default configuration

Node: 16.14.2

Prisma version output from inside CICD runner:
```
prisma                  : 3.15.2
@prisma/client          : 3.15.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 461d6a05159055555eb7dfb337c9fb271cbd4d7e
Studio                  : 0.462.0
```

### Prisma Version

```
prisma                  : 3.15.2
@prisma/client          : 3.15.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 461d6a05159055555eb7dfb337c9fb271cbd4d7e
Studio                  : 0.462.0
```

**Comment by millsp** [comment]
Hey @alibi-tech, could you please upgrade to the latest version of Prisma and tell us if this is still happening?

**Comment by millsp** [comment]
Hey @alibi-tech ,

Did you get a chance to have a look at my previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by kokokenada** [comment]
@millsp - I don't believe we are impacted by this anymore.  Go ahead and close.  We'll reopen if it surfaces again.

**Comment by petradonka** [comment]
Thanks for getting back to us @kokokenada! 🙏 

We'll close this issue now, but happy to reopen if new information surfaces.
