### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by nodevnolife** [prisma/prisma#15499]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.13.1           | 
| OS              | windows            |
| Prisma Client   | 4.3.1              |
| Query Engine    | c875e43600dfe042452e0b868f7a48b817b9640b|
| Database        | mysql              |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from D:\devnolife-perpus\backend\.env
prisma:tryLoadEnv Environment variables loaded from D:\devnolife-perpus\backend\.env
prisma:client dirname D:\devnolife-perpus\backend\node_modules\.prisma\client
prisma:client relativePath ..\..\..\prisma
prisma:client cwd D:\devnolife-perpus\backend\prisma
prisma:client clientVersion 4.3.1
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine:loader Searching for Query Engine Library in D:\devnolife-perpus\backend\node_modules\.prisma\client
prisma:client:libraryEngine:loader loadEngine using D:\devnolife-perpus\backend\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by janpio** [comment]
Can you help us pinpoint this @nodevnolife by providing a bit more information? What Client query are you executing? What MySQL version? What is your Prisma schema and the data that affects this? Thanks.

**Comment by janpio** [comment]
Can you help us out here @nodevnolife? With the current information we unfortunately will need to close the issue as it is not enough to understand what is going on and reproduce it.

**Comment by janpio** [comment]
Closing then until someone provides more information. Please comment or open a new issue. Thanks!
