### ISSUE TITLE
multi-dimensional arrays - PostgeSQL

### ISSUE THREAD

**Issue by bram209** [prisma/prisma#15515]
## Problem

PostgreSQL supports multi-dimensional arrays: https://www.postgresql.org/docs/current/arrays.html
Prisma however does not. I would not mind using raw queries for querying the data, but as far as I know, Prisma does not provide an easy way to support custom types or partially bypass the `schema.prisma`.

## Suggested solution
Add support for multi-dimensional arrays

## Alternatives

Make it possible to partially bypass the `schema.prisma` or support custom types (but I would assume this is more involved considering the code generation happening)

**Comment by bram209** [comment]
related https://github.com/prisma/prisma/issues/11582

**Comment by janpio** [comment]
Is that "related" issue correct?

I think this is actually a duplicate of https://github.com/prisma/prisma/issues/11120 - do you agree @bram209? Then please close this issue. Thanks.

**Comment by bram209** [comment]
> Is that "related" issue correct?
> 


It is related considering if you could partially bypass the schema, you could at least still use Prisma in combination with it's raw queries as a workaround for the lack of multi dimensional array support in Prisma itself

> I think this is actually a duplicate of #11120 - do you agree @bram209? Then please close this issue. Thanks.
This looks indeed like a duplicate, I searched through the issues but apparently not good enough, sorry for that 😅
