### ISSUE TITLE
Unknow PRISMA_QUERY_ENGINE_LIBARARY linux-arm64-openssl-undefined

### ISSUE THREAD

**Issue by tt-mohsen** [prisma/prisma#15574]
### Bug description

I was encountered with unknown query engine library error while I was trying to deploy my service on AWS
Here is the error I got

![MicrosoftTeams-image](https://user-images.githubusercontent.com/112756655/192711387-ed63e2bc-c676-4caf-8115-662aef1622d9.png)

Trying too much finding solution, but it seems Prisma can not detect proper query engine type

Setting binary target to native or arm does not solve the issue

### How to reproduce

1. Setup nestjs application with prisma
2. Setup prisma client provider and output file in schema.prisma file
3. Setup database source in schema.prisma file
4. Select proper binary target
5. Set PRISMA_QUERY_ENGINE_LIBRARY env variable pointing location of library engine
6. Set PRISMA_CLI_BINARY_TARGETS
7. Generate Prisma client
8. Create docker image
9. push and deploy docker image to AWS
10. And you will get the error

### Expected behavior

Prisma must specify right binary target it needs instead of displaying unknown

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "client"
  engineType = "library"
}

datasource db {
  provider = "mysql"
  url      = env("PRISMA_DB_URL")
}

// ... rest of my models
```

```ts
import { INestApplication, Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from './client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  async onModuleInit() {
    await this.$connect();
  }

  async enableShutdownHooks(app: INestApplication) {
    this.$on('beforeExit', async () => {
      await app.close();
    });
  }
}

// PrismaService is then used to query database inside the project
```

### Environment & setup

```
Setup Details
- OS: Amazon Linux 2
- Database: Aurora MySQL
- Node.js version: 16.16.0
- CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2
- Kernel: Linux 4.14.281-212.5.02.amzn2.aarch64
- Architecture: arm64
``` 

```.env
# Environment Variables
PRISMA_DB_URL=mysql://username:password@host:port/designtool?database
ENV PRISMA_QUERY_ENGINE_LIBRARY=/app/prisma/engines/linux-arm64-openssl-3.0.x
ENV PRISMA_CLI_BINARY_TARGETS=linux-arm64-openssl-3.0.x
```

### Prisma Version

```
# On development PC
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
```

**Comment by janpio** [comment]
Why are steps 4-6 necessary in your case? Usually Prisma should just do the right thing by default.
What AWS service are you using to run that container?

**Comment by tt-mohsen** [comment]
> Why are steps 4-6 necessary in your case? Usually Prisma should just do the right thing by default. What AWS service are you using to run that container?

I already tried without steps 4 and 6, It ended the same error I am getting now, but I though choosing right binary target and setting its location for Prisma may help out, but did not

for AWS service, its just my application I called, not a service of AWS.
Its just my application image containerized with docker to be deployed on AWS

**Comment by jkomyno** [comment]
It seems we're unable to detect the `openssl` version on your system.
We currently attempt the following (if the first option doesn't work, we fall back to the next ones):
- `openssl version -v`
- `ls -l /lib64 | grep ssl`
- `ls -l /usr/lib64 | grep ssl`

Would you please be able to connect via `ssh` to the AWS service you're currently using and trying to run the above commands? I'd assume you're running AWS ECS, right?

**Comment by tt-mohsen** [comment]
```
> openssl version -v
OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by tt-mohsen** [comment]
I am closing the issue, It's fixed by installing openssl
