### ISSUE TITLE
Multi-schema support for `db pull`

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#15583]
Within the `multiSchema` preview feature, `db pull` should by default introspect all schemas in the database.

**Comment by Jolg42** [comment]
We need some TS tests in prisma/prisma repo.

**Comment by Jolg42** [comment]
(working on it now)

**Comment by pimeys** [comment]
Missing: MySQL.

**Comment by Jolg42** [comment]
We'tracking the progress for MySQL for in https://github.com/prisma/prisma/issues/16943
