### ISSUE TITLE
Multi schema support for Migrate

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#15584]
Within the multiSchema preview feature, the `migrate` and `db push` commands should be aware of multiple schemas and diff accordingly.

**Comment by Jolg42** [comment]
We need some TS tests in prisma/prisma repo.

**Comment by jkomyno** [comment]
I believe multiSchema support for `postgres` and `sqlserver` is already included in the `migration-engine` shipped with `prisma@4.9.0`. The TS tests mentioned above have also been merged already. Am I missing something here? Can we close this issue? @tomhoule @Jolg42
