### ISSUE TITLE
Filters on hashed+salted string fails with mongodb

### ISSUE THREAD

**Issue by MrGuiMan** [prisma/prisma#15621]
### Bug description

I store hashed and salted values inside a mongo document. When trying to retrieve the document based on string equality of that hash+salted value, result is null. The same request using `findRaw` returns my result.

### How to reproduce

1. Store a document in a collection, with a field containing a hash+salted value (generated with bcrypt) such as `'$2a$10$Vs4PqpjnztASla9pPXtLNuAqWzEDJCaHmaA2M6IUqQRLehRsWFbMG` (value is "test", salted with '$2a$10$Vs4PqpjnztASla9pPXtLNu')
2. Try to find the document using `findFirst`, filtering on the hashed field
3. Nothing is returned

### Expected behavior

The corresponding document should be returned

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Client {
  id         String     @id @map("_id")
  name       String
  email      String
  date       String?
  details    String
  hashedId   String?

  @@map("clients")
}
```

```ts

db.client.findFirst({ where: { hashedId: { equals: '$2a$10$Vs4PqpjnztASla9pPXtLNuAqWzEDJCaHmaA2M6IUqQRLehRsWFbMG'}}})
```

### Environment & setup

- OS: macOS Monterey
- Database:  MongoDB
- Node.js version: 16.15.1

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
```

**Comment by xjahz** [comment]
Looks good on my end !
