### ISSUE TITLE
Support for session-dependent queries

### ISSUE THREAD

**Issue by BitPatty** [prisma/prisma#15630]
## Problem

Some queries depend on the session executing the query, such as [MariaDB/MySQL named locks](https://mariadb.com/kb/en/get_lock/).

Since there is currently no way to specify which connection from the connection pool a query should utilize when running queries, one might end up unintentionally distributing session-dependent queries across multiple connections.

In the example of named locks, the `RELEASE_LOCK()` must run on the same session as the `GET_LOCK()` statement to successfully release it.

## Suggested solution

It would be great if - for such scenarios - it were possible to either create a reserved connection or the possibility to target a specific connection when executing a query.

## Alternatives

Working with a secondary prisma client that has its pool size limited to `1` and using it for session-dependent queries.

**Comment by janpio** [comment]
You could probably also use a [transaction](https://www.prisma.io/docs/orm/prisma-client/queries/transactions) for that, or does that not satisfy your needs?

What could an API for this look like?

**Comment by BitPatty** [comment]
> You could probably also use a [transaction](https://www.prisma.io/docs/orm/prisma-client/queries/transactions) for that, or does that not satisfy your needs?

Not always, for example for the sample above:
- `GET_LOCK` and `RELEASE_LOCK` do not interact with transactions
- They are not automatically released on commit/rollback
- There's scenarios in which a lock should be held across multiple transactions

The main issue I see here is that if the transaction fails, there are no guarantees that a follow-up `RELEASE_LOCK` will be on the same connection. Therefore the lock might never be releaesd.

The lock statements could be in a separate transaction - but again, this relies on a proper timeout to be set, otherwise the lock might never be released.

> What could an API for this look like?

I am unsure and honestly haven't put a lot of thought into it. 

Since these are usually very specific statements that probably also vary a lot between the DBMS it might make sense to have it as a flag only on the raw queries.

Or alternatively, if an additional connection could be spawned on demand that can be freed after work has been completed. From what I understand there is currently no way to interact with the connection pool apart from the initial configuration.

**Comment by janpio** [comment]
Are there any other queries/commands than locking related ones that would fall into this category? Because we already have 2 locking related feature requests that then might be the better ones to track this: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+locking%22+sort%3Aupdated-desc

**Comment by BitPatty** [comment]
From the top of my head I don't have another use case that couldn't be solved with transactions. Unsure about other DBMS.

#17136 and #5983 don't reflect this one from my point of view however, since both of them are statement based locks and not session based.

**Comment by janpio** [comment]
This sounds related though, as those are also session dependent queries: https://github.com/prisma/prisma/issues/5128

**Comment by BitPatty** [comment]
> This sounds related though, as those are also session dependent queries: #5128

I agree, this looks like it would fall under the same or similar scope. I guess these two issues could be merged.

**Comment by janpio** [comment]
Thank you, done then - I'll close this issue here. See you over there.
