### ISSUE TITLE
Prisma many-to-many query not properly structuring data

### ISSUE THREAD

**Issue by demacericcardo** [prisma/prisma#15643]
I can't get the data from a many to many relation in a proper way. I got the relation: USER-EVENT

**Prisma query**:

`await this.prisma.event.findUnique({ where: { id: eventId }, include: { users: { select: { user: true } } } })
`

The data appears double nested:

![MTEWq](https://user-images.githubusercontent.com/86380053/193618249-cb1eea84-9415-437e-a65e-1a182d4ca057.png)

**Comment by millsp** [comment]
Hey @demacericcardo, could you please share the following with us?
* Your schema
* Node.js version
* Prisma version
* Some code for reproducing this

That would be helpful for us to be able to look into it. Thanks!

**Comment by demacericcardo** [comment]
**My schema:**

`generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  username     String @unique
  email        String
  passwordHash String

  name       String
  surname    String
  birthDate  DateTime
  profilePic String

  roles  Role[]
  events UsersOnEvents[]
}

model Event {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  eventDate   DateTime
  title       String
  description String?
  image       String?

  users UsersOnEvents[]
}

model UsersOnEvents {
  user       User     @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  userId     Int
  event      Event    @relation(fields: [eventId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  eventId    Int
  assignedAt DateTime @default(now())

  @@id([userId, eventId])
}

enum Role {
  User
  Admin
}`

**Node version:** 16.16.0

**Prisma version:** 
prisma                  : 4.3.0
@prisma/client     : 4.3.1

**The code is the same I already posted:**

`await this.prisma.event.findUnique({ where: { id: eventId }, include: { users: { select: { user: true } } } })`

**Comment by millsp** [comment]
Thanks. The result data/structure seems expected to me, why is it unexpected for you?

**Comment by demacericcardo** [comment]
I was expecting the query not including the data from the many to many table but just an array of the referenced users, how can i do that? if there's a way

**Comment by millsp** [comment]
If I understood well, you want the nested result as a top result? That's not possible. You'd need to get it yourself by accessing the nested properties.

**Comment by demacericcardo** [comment]
Ok, no problem. Thank you

**Comment by luminous8** [comment]
> If I understood well, you want the nested result as a top result? That's not possible. You'd need to get it yourself by accessing the nested properties.

What's the best way to achieve that when quering multiple times the same field with a many-to-many relationship?
Could a middleware work to achieve what's suggested [in this article](https://www.prisma.io/docs/guides/database/troubleshooting-orm/help-articles/working-with-many-to-many-relations) automatically?

I'm refering to this block of code
```
const result = posts.map((post) => {
  return { ...post, tags: post.tags.map((tag) => tag.tag) }
})

```

**Comment by demacericcardo** [comment]
> 

Yeah i was about to cycle the data and restructure the object before using it, my issue was about if there was a better way with just a single query.
Thank you anyway

**Comment by millsp** [comment]
> What's the best way to achieve that when quering multiple times the same field with a many-to-many relationship? @millsp
> Could a middleware work to achieve what's suggested [in this article](https://www.prisma.io/docs/guides/database/troubleshooting-orm/help-articles/working-with-many-to-many-relations) automatically?

Middleware can do that. However, be aware that you'd lose type-safety. That might be ok if that isn't a requirement.

**Comment by millsp** [comment]
@luminous8 @demacericcardo See https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#fluent-api
