### ISSUE TITLE
Consider running strip on published binaries

### ISSUE THREAD

**Issue by LinusU** [prisma/prisma#15651]
## Problem

When deploying to serverless environments, the size of the deployment is often quite limited. Prisma comes with quite large binary files, which can easily take up the majority of published payloads.

## Suggested solution

As part of our deployment, we ran the `strip` command on the `libquery_engine` node module, which resulted in ~30% savings on the file size:

```sh
strip --strip-all node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node
```

## Alternatives

It would also be very interesting to see what savings could be gained by building with `-Oz` or `-Os`.

## Additional context

n/a

**Comment by tomhoule** [comment]
We do this since https://github.com/prisma/prisma-engines/pull/3511 — measurements on size reduction in the PR description :)

**Comment by tomhoule** [comment]
(since https://github.com/prisma/prisma/releases/tag/4.8.0)
