### ISSUE TITLE
CI with self-hosted runners is hostile to forks

### ISSUE THREAD

**Issue by jsoref** [prisma/prisma#15653]
### Bug description

When one forks this repository and makes a pull request into that fork the CI will get stuck (it'll eventually time out and fail), e.g.:
https://github.com/check-spelling/prisma/actions/runs/3178120808

### How to reproduce

1. Fork this repo
2. Create a pull request into the fork
3. Check the actions view for the PR

### Expected behavior

Something like the logic in commercialhaskell/stack:
https://github.com/commercialhaskell/stack/blob/d18abe6beb20d6da090280f2ef0661e0047c626b/.github/workflows/integration-tests.yml#L98-L99

(It took us a couple of attempts to get a working set, but that workflow works and there's a PR or two that explains how we managed it. I gave the rough outline and the maintainer actually figured out the details.)

### Prisma information

https://github.com/prisma/prisma/blob/52f95cba0a5cb0088100cdbd365fa9140024298e/.github/workflows/test.yml#L120-L122

### Environment & setup

- OS: Linux

### Prisma Version

main

**Comment by janpio** [comment]
Thanks. As we are back on GH hosted runners, this is currently not needed anymore.
