### ISSUE TITLE
@default(now()) not saving DateTime in UTC

### ISSUE THREAD

**Issue by willdspd** [prisma/prisma#15671]
### Bug description

In my Prisma schema I have a model like so:

```
model SequenceContact {
  id String @id @default(cuid())
  sequenceId String @map("sequence_id")
  contactId String @map("contact_id")
  startedAt DateTime @map("started_at") @default(now())
  isActive Boolean @map("is_active") @default(true)
  delayId String? @map("delay_id")
  startedDelayAt DateTime? @map("started_delay_at")
  sentEmails SentEmail[]
  sequence Sequence @relation(fields: [sequenceId], references: [id], onDelete: Cascade)
  contact Contact @relation(fields: [contactId], references: [id], onDelete: Cascade)
  delay Delay? @relation(fields: [delayId], references: [id], onDelete: Cascade)

  @@map("sequence_contacts")
}
```

The Prisma docs say @default(now()) should save a DateTime using the UTC timezone in Postgres. However, it appears the startedAt field is being saved in my local timezone in my database. In the example image below, I had just created a new sequence_contact record, and as you can see, the started_at field is in my local time, not UTC.

<img width="1440" alt="Screenshot 2022-10-05 at 13 14 24" src="https://user-images.githubusercontent.com/60123802/194059407-fdc0008e-57d0-414c-91dc-5246ae3d03ca.png">

### How to reproduce

- Create Prisma Schema like above
- Connect Postgres
- npx prisma db push
- Create new sequence_contact record

### Expected behavior

The started_at should be saved in UTC timezone

### Prisma information

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model SequenceContact {
  id String @id @default(cuid())
  sequenceId String @map("sequence_id")
  contactId String @map("contact_id")
  startedAt DateTime @map("started_at") @default(now())
  isActive Boolean @map("is_active") @default(true)
  delayId String? @map("delay_id")
  startedDelayAt DateTime? @map("started_delay_at")
  sentEmails SentEmail[]
  sequence Sequence @relation(fields: [sequenceId], references: [id], onDelete: Cascade)
  contact Contact @relation(fields: [contactId], references: [id], onDelete: Cascade)
  delay Delay? @relation(fields: [delayId], references: [id], onDelete: Cascade)

  @@map("sequence_contacts")
}

...other models

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 16.9.1

### Prisma Version

4.3.1

**Comment by SevInf** [comment]
I could not reproduce the issue, even with non-utc postgres timezone. @willdspd can you share more information about your postgres configuration?

**Comment by willdspd** [comment]
Hi @SevInf, this issue seems to have resolved itself. I really have no explanation as to why it occurred, but as you can see from my screenshot, it definitely did. Maybe something to keep an eye on for the future.
