### ISSUE TITLE
Trying to pull from SQL Server

### ISSUE THREAD

**Issue by jhd-dev** [prisma/prisma#15675]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.17.1           | 
| Prisma CLI  | 4.4.0              | 
| Engine      | f352a33b70356f46311da8b00d83386dd9f145d6| 

## Error
```
Error: [libs\sql-schema-describer\src\mssql.rs:317:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `\r\ncreate default D_BIT_OFF\r\nas 0\r\n`"
```

**Comment by millsp** [comment]
Hey @jhd-dev, can you provider us with a schema, and optimally a reproduction of your problem? Thank you!

**Comment by miguelff** [comment]
Could you please @jhd-dev provide a schema dump (not the data, it's OK with just the schema) so we can attempt to reproduce the issue?

Closing for the moment as duplicate, as we are collecting ocurrences of this issue with [`create default` TRANSACT SQL ](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-default-transact-sql?view=sql-server-ver16) in https://github.com/prisma/prisma/issues/14208
