### ISSUE TITLE
@default(dbgenerated(...)) results in identical default values for all existing rows

### ISSUE THREAD

**Issue by cymen** [prisma/prisma#15682]
### Bug description

I have a table with an existing `id` column and I wanted to add a `shortId` column using nanoid values. I followed this example:

https://github.com/prisma/prisma/issues/6719#issuecomment-1178222554

I added the `shortId` field like so:

```
  shortId        String         @default(dbgenerated("(nanoid('p'))"))
```

And the problem was that after the migration was applied, all of the rows had the same identical `shortId` value. However, if I run an `UPDATE` query like so:

```sql
UPDATE "ModelName" SET "shortId" = nanoid('p');
```

I get a unique value in each row for `shortId`. I of course would add a `@unique` attribute to the `shortId` row above but doing so errors out due to the duplicate value issue.

### How to reproduce

1. Add the `nanoid` PostgreSQL function per the directions in the link above.
2. Add a new column to an existing model for which there are already rows in the database.
3. Run the migration.
4. Observe duplicate values.

### Expected behavior

I would expect a unique value for each row (assuming we haven't hit the very rare chance of a duplicate from the nanoid function).

### Prisma information

```prisma
model ModelName {
  id             String         @id
  shortId        String         @default(dbgenerated("(nanoid('p'))"))
  name           String
  createdAt      DateTime       @default(now())
  updatedAt      DateTime       @updatedAt
}
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.15.1

### Prisma Version

```
prisma                  : 4.4.0
@prisma/client          : 4.4.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.4.0-66.f352a33b70356f46311da8b00d83386dd9f145d6
Default Engines Hash    : f352a33b70356f46311da8b00d83386dd9f145d6
Studio                  : 0.474.0
Preview Features        : interactiveTransactions
```

**Comment by cymen** [comment]
To work around this, I'll add a non-`@unique` column, run the migration, run a query to update the existing rows and then add another migration to make the column `@unique`. I tested this approach on my dev environment and that seems to work fine.

**Comment by janpio** [comment]
What is the generated migration SQL when you add the @default to the field?
From the information I currently have, it seems like this might just generade the same value for all rows by default - while `UPDATE` does not as it iterates different over the rows.

**Comment by cymen** [comment]
It is:

```sql
-- AlterTable
ALTER TABLE "ModelName" ADD COLUMN     "shortId" TEXT NOT NULL DEFAULT (nanoid('p'));
```

I guess the way to go is to add the column to schema, run the migration but with `--create-only` and then modify the SQL migration to be something more like:

```sql
BEGIN;
ALTER TABLE "ModelName" ADD COLUMN     "shortId" TEXT;
UPDATE "ModelName" SET "shortId" = nanoid('p');
ALTER TABLE "ModelName" ALTER COLUMN "shortId" NOT NULL DEFAULTnanoid('p');
END;
```

Then run the migration. Then run another migration to add `@unique` to the column in the schema file.

**Comment by cymen** [comment]
I forgot to note two things:
- I tried this first on v3 and had the same problem so I upgraded to v4 to see if it was still present
- the extra parens around the function call were just testing -- just cruft at this point (ie `(nanoid(...))` vs `nanoid()`)

**Comment by cymen** [comment]
@janpio I discovered this is not due to any bug in Prisma but rather the function should have been marked as `VOLATILE` not `STABLE` -- I posted an updated on the thread I referenced above here:

https://github.com/prisma/prisma/issues/6719#issuecomment-1272411797

I discovered this after reading the PostgreSQL docs on Function Volatility Categories at https://www.postgresql.org/docs/current/xfunc-volatility.html -- I'll go ahead and close this issue. Thank you.

**Comment by janpio** [comment]
Thanks!
