### ISSUE TITLE
Schema: add deprecation warning for datasource property `referentialIntegrity` (renamed to `relationMode`)

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#15689]
## Problem

We renamed the datasource property `referentialIntegrity` to `relationMode` (first appearance will be in 4.5.0)

## Suggested solution

We might want to drop the datasource property `referentialIntegrity` in a next major version, adding a deprecation message would help.

**Comment by jkomyno** [comment]
Note: we plan on using warnings for this, but first we have to figure out how Prisma itself supports warnings.
