### ISSUE TITLE
Type clash in generated relation filter when naming models `Something` and `SomethingList`

### ISSUE THREAD

**Issue by ymc9** [prisma/prisma#15718]
### Bug description

It seems that the generated TS client code uses fixed naming conventions like:
- [Model]RelationFilter
- [Model]ListRelationFilter

Models can be named in certain ways to cause a naming collision and thus, incorrect typing.

### How to reproduce

1. Use a simple Todo List schema listed in "Prisma information" section
2. Run ```prisma generate```
3. Observe that ```todoList``` field in ```TodoWhereInput``` is wrongly typed because of type ```TodoListRelationFilter```
```ts
  export type TodoWhereInput = {
    AND?: Enumerable<TodoWhereInput>
    OR?: Enumerable<TodoWhereInput>
    NOT?: Enumerable<TodoWhereInput>
    id?: StringFilter | string
    content?: StringFilter | string
    todoList?: XOR<TodoListRelationFilter, TodoListWhereInput>
    todoListId?: StringFilter | string
  }

  export type TodoListRelationFilter = {
    every?: TodoWhereInput
    some?: TodoWhereInput
    none?: TodoWhereInput
  }
```

Field ```todoList``` of model ```Todo``` is on the "one" side of the relation, so the filter type should contain "is" and "isNot" instead of "every"/"some"/"none".

I suspect this is caused by the model name "TodoList", and some accidental type overwriting happened during generation.

### Expected behavior

Two separate relation filter types are generated, one for filtering "to-many" of ```Todo``` model, and another for filtering "to-one" of ```TodoList``` model.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model TodoList {
  id    String @id @default(uuid())
  title String
  todos Todo[]
}

model Todo {
  id         String   @id @default(uuid())
  content    String
  todoList   TodoList @relation(fields: [todoListId], references: [id])
  todoListId String
}
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v16.15.0

### Prisma Version

```
prisma                  : 4.4.0
@prisma/client          : 4.4.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.4.0-66.f352a33b70356f46311da8b00d83386dd9f145d6
Default Engines Hash    : f352a33b70356f46311da8b00d83386dd9f145d6
Studio                  : 0.474.0
```

**Comment by aqrln** [comment]
Fixed in https://github.com/prisma/prisma-engines/pull/5029.
