### ISSUE TITLE
Models that can be ignored by migration scripts (Support for views)

### ISSUE THREAD

**Issue by kings1ay3r** [prisma/prisma#15719]
## Problem

The lack of support for database views have already been discussed for quite long, and various work arounds have also been suggested in those discussions. The project I work on extensively uses views to roll-up data & the task of managing them, everytime there is a migration is frustrating and error prone.

## Suggested solution

Add support for viewModel or an annotation like `@view` or `@ignore` in the schema file so that the migrate script can create a view instead of a table/relationship using the corresponding syntax for the target DBMS where supported or throw an error if views arent supported. Client generation can generate only read methods / keep the other methods unexported. view defenitions can take references and aggregate methods.

## Alternatives

View defenitions can be done by manually editing the migration sql.

**Comment by TasinIshmam** [comment]
Hi folks 👋, 

Tasin from Prisma here. 

We are launching a [Design Partner Program](https://prismaio.notion.site/Prisma-Design-Partner-Program-a286c25e47fb44e199038ca71dce36a1) where external teams can collaborate with us to shape Prisma's future. In this program, we will collaborate with you on defining solutions to the following problems: 

- **Data projections for denormalization or data integration purposes**
- Caching
- Listening and reacting to database changes in real-time
- Serverless workflow orchestration

**If you’re struggling with data projections and/or database views, especially in a serverless environment, you might be a great fit for this program!**  Your team can take advantage of new Prisma features that you won’t have to build or maintain yourselves. As you invest time in partnering with us, we will also offer you free credits once anything coming out of this program reaches production.

**You can [check out the program in more detail](https://prismaio.notion.site/Prisma-Design-Partner-Program-a286c25e47fb44e199038ca71dce36a1) to see the kinds of activities we’re planning. To apply to this program, [fill out the form](https://docs.google.com/forms/d/e/1FAIpQLSdfadMO7qVOMlOgmeYevpM-olpjku2-3sVzMvVQiHITmZf4dA/viewform)**.

We’re looking forward to hearing from you!

**Comment by janpio** [comment]
This is now obsolete as we implemented a new `view` keyword behind that `views` preview feature, which is ignored in Migrations. Read more via the links in our preview feature feedback issue for Views: https://github.com/prisma/prisma/issues/17335
