### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine\connectors\sql-migration-connector\src\sql_renderer\mysql_renderer.rs:522:97] internal error: entered unreachable code 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#15789]
Command: `prisma db push`
Version: `4.4.0`
Binary Version: `f352a33b70356f46311da8b00d83386dd9f145d6`
Report: https://prisma-errors.netlify.app/report/14362 
OS: `x64 win32 10.0.22000`

**Comment by pimeys** [comment]
dupe: https://github.com/prisma/prisma/issues/16340
