### ISSUE TITLE
Check for nested sql query after `IN` keyword in the Prisma raw query.

### ISSUE THREAD

**Issue by HwangTaehyun** [prisma/prisma#15808]
## Problem

[Docs](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#tagged-template-helpers) about raw-database-access also guide to use of nested SQL query when using ```IN``` keyword, but in the other raw queries use js variables literally. So, many developers have been confused about when to use nested SQL or just js variables if they don't read the docs carefully. To use myself as an example, I didn't follow the docs and use them without nested queries and Prisma raw SQL not working in my project without errors, so I had to spend a lot of time fixing them. Obviously, It was my mistake. However, It is not easy to find what is an error in that case because there is no type checking and no error!

## Suggested solution

I would like to throw an error with the following message in the following case.

```
const ids = [1, 3, 5, 10, 20]
const result =
  await prisma.$queryRaw`SELECT * FROM User WHERE id IN (${ids})`
```

```
"Expected a value after 'IN' keyword should be the nested sql queries"
```

## Additional context

Prisma uses [sql-template-tag](https://github.com/blakeembrey/sql-template-tag) package for raw queries. Thus, to fix this issue, after adding this feature to sql-template-tag, Prisma should use the next updated sql-template-tag package. So, I asked about this feature to @blakeembrey, and he tell me his concerns about performance for adding this or additional checks. However, he also says additional checks may have to be executed under a development environment would be fine. 

https://github.com/blakeembrey/sql-template-tag/pull/32

Actually, having each logic depending on whether it is a development environment or production environment is the way many projects do.

Thus, checking this condition would be very helpful for debugging and finding errors easily for many developers using Prisma raw queries!

**Comment by janpio** [comment]
> use of nested SQL query when using `IN` keyword

What do you mean by that exactly? I am not sure I am following.

`Prisma.join` does note create a nested SQL query, but prepares the parameters in a way that they work in a prepared statement as we are using them in `$queryRaw`: https://github.com/blakeembrey/sql-template-tag#join

Are you suggesting that we find a way to check _if_ people correctly use `Prisma.join` instead of directly inputting the values?

**Comment by HwangTaehyun** [comment]
@janpio Yeah! That is what! And I want to say Sql instance in sql-template-tag instead of a nested SQL query. That makes more sense.
```
/**
 * Create a SQL query for a list of values.
 */
export function join(
  values: RawValue[],
  separator = ",",
  prefix = "",
  suffix = ""
) {
  if (values.length === 0) {
    throw new TypeError(
      "Expected `join([])` to be called with an array of multiple elements, but got an empty array"
    );
  }

  return new Sql(
    [prefix, ...Array(values.length - 1).fill(separator), suffix],
    values
  );
}
```

**Comment by HwangTaehyun** [comment]
@janpio What do you think? I want to fix this for other developers using the Prisma raw query.

**Comment by janpio** [comment]
I will raise this internally. Definitely sounds interesting.

**Comment by SevInf** [comment]
Hi @HwangTaehyun!
We understand that such warning would be a good improvement, however, I have to agree with `sql-template-tag` maintainers on implementation: simple substring match, similar to what you did in your PR likely will misfire  in some cases, (part of them mentioned in PR discussion). Properly parsing SQL without stumbling over specifics of different dialects is would be quite a difficult task and require constant maintenance, which is just not worth it for this feature.
We'd be fine with keeping this request open, but at the moment I am not sure how can we approach it without implementing fullu-featured SQL parser.

**Comment by HwangTaehyun** [comment]
@SevInf Oh, thank you for reviewing. I'm going to think about that point.

**Comment by HwangTaehyun** [comment]
@SevInf @janpio Do you guys have any other thoughts yet? I believe there's no problem except efficiency. Thus, it would be good only for dev mode.

**Comment by HwangTaehyun** [comment]
@SevInf @janpio I would like to get some re-feedback on my suggestion! Thank you!

**Comment by janpio** [comment]
I am unfortunately not sure what you are asking, and what the current suggestion is. Can you repeat and explain again please?

**Comment by HwangTaehyun** [comment]
@janpio 
I suggest Prisma always receives the raw query's array variable with Prisma.join like the following example.

```
const ids = [1, 3, 5, 10, 20]
const result =
  await prisma.$queryRaw`SELECT * FROM User WHERE id IN (${Prisma.join(ids)})`
```

Many developers have been confused about when to use nested SQL or just js variables if they don't read the docs carefully.
Moreover, Prisma does not throw any error when using js array variable only like the following example.

Prisma recognizes that **ids** variable like an empty array in Postgres
```
const ids = [1, 3, 5, 10, 20]
const result =
  await prisma.$queryRaw`SELECT * FROM User WHERE id IN (${ids})`
```

I suggest Prisma should check and throw an error message when using the js variable instead of Prisma.join return value. Because it causes error in runtime.

**Comment by SevInf** [comment]
@HwangTaehyun I don't quite understand. There are other usecases (not related to `IN`) where using array variable would be valid and expected. For example, PostgreSQL array types:

```ts
prisma.$queryRaw`SELECT * FROM SomeTable WHERE arrayField=${arrayVariable}`
```

Are you suggesting we'd require it to also be wrapped with `Prisma.join`? That at the very least would be a breaking change for `queryRaw`.

**Comment by HwangTaehyun** [comment]
@SevInf Oh, I suggest only the next variable of ```IN``` keyword should be used with ```Prisma.join```!

**Comment by SevInf** [comment]
@HwangTaehyun Let use circle back to my earlier point then. In order to implement this warning the way you suggest, we'll have to actually implement SQL parser and understand what's inside of the query - simple substring matches will have false positives in some cases. And that can't be generic SQL parser either - we have to support 5 different dialects for SQL databases we support now and update them with the new releases of the databases. And each time we add another SQL provider, we'll have to implement new parser as well. We are relatively small team and that's a huge amount of work and maintenance for one single warning we can't afford at the moment.

**Comment by HwangTaehyun** [comment]
@SevInf I got it! Thanks for your review.

**Comment by janpio** [comment]
Closing as this is currently not something we are considering.
