### ISSUE TITLE
Prisma migration fails with postgres

### ISSUE THREAD

**Issue by tareksalem** [prisma/prisma#15826]
### Bug description

I have the following schema

```prisma

generator db {
  provider = "prisma-client-js"
    previewFeatures = ["referentialIntegrity", "multiSchema"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  referentialIntegrity = "prisma"
  schemas = ["account", "server"]
}

model User{
  @@map("users")
  id String @id @default(uuid())
  firstName String @map("first_name")
  lastName String @map("last_name")
  username String
  email String @unique
  password String
  role String
  account Account @relation(fields: [accountId], references: [zacId])
  accountId String @map("account_id")
  verified Boolean? @default(false)
  active Boolean? @default(true)
  verificationCode String?
  createdAt DateTime? @default(now()) @map("created_at")
  updatedAt DateTime? @updatedAt @default(now()) @map("updated_at")
  @@index([id, email, verified, verificationCode])

  @@schema("account")
}

model Account {
  @@map("accounts")
  id String @id @default(uuid())
  zacId String @unique
  users User[]
  active Boolean? @default(false)
  paymentMethods PaymentMethod[]
  currentPlan Plan?
  createdAt DateTime? @default(now()) @map("created_at")
  updatedAt DateTime? @updatedAt @default(now()) @map("updated_at")

  @@schema("account")
}

model PaymentMethod {
  @@map("payment_methods")
  id String @id @default(uuid())
  account Account @relation(fields: [accountId], references: [zacId])
  primary Boolean? @default(true)
  accountId String @map("account_id")
  billingAddress BillingAddress @relation(fields: [billingAddressId], references: [id])
  billingAddressId String @unique @map("billing_address_id")
  createdAt DateTime? @default(now()) @map("created_at")
  updatedAt DateTime? @updatedAt @default(now()) @map("updated_at")

  @@schema("account")
}

model BillingAddress {
  @@map("billing_addresses")
  id String @id @default(uuid())
  email String
  address String
  postalCode String @map("postal_code")
  paymentMethod PaymentMethod?
  createdAt DateTime? @default(now()) @map("created_at")
  updatedAt DateTime? @updatedAt @default(now()) @map("updated_at")

  @@schema("account")
}

model Plan{
  @@map("plans")
  id String @id @default(uuid())
  originalId String
  price Decimal
  duration Int @default(0)
  title String
  account Account @relation(fields: [accountId], references: [zacId])
  accountId String @unique @map("account_id")
  features Json
  subscribedAt DateTime? @default(now()) @map("subscribed_at")
  createdAt DateTime? @default(now()) @map("created_at")
  updatedAt DateTime? @updatedAt @default(now()) @map("updated_at")

  @@schema("account")
}

model Project {
  @@map("projects")
  id String @id @default(uuid())
  name String
  accountId String @map("account_id")
  createdAt DateTime? @default(now()) @map("created_at")
  updatedAt DateTime? @updatedAt @default(now()) @map("updated_at")

  @@schema("server")
}

```

I run the first command to push my schema to db as the following:

```cmd
npx prisma db push
```

then I did an update on the following model:

```prisma
model Project {
  @@map("projects")
  id String @id @default(uuid())
  name String
  testId String?  // added this column
  accountId String @map("account_id")
  createdAt DateTime? @default(now()) @map("created_at")
  updatedAt DateTime? @updatedAt @default(now()) @map("updated_at")

  @@schema("server")
}
```

then I run the following command:

```cmd
npx prisma migrate dev
```

it fails with the following error:

```cmd
Error: P3006

Migration `20221016115041_project_update` failed to apply cleanly to the shadow database. 
Error:
db error: ERROR: relation "users" already exists
   0: sql_migration_connector::validate_migrations
             at migration-engine/connectors/sql-migration-connector/src/lib.rs:289
   1: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:251
```

when I looked on the generated migration script I found that prisma regenerates the migration for the whole schema even the not changed tables!

that's why it outputs this error

Also I don't know why the generated migration script doesn't have CREATE IF NOT EXIST instead of CREATE

because this may fail also!

### Prisma information

```
Error: P3006

Migration `20221016115041_project_update` failed to apply cleanly to the shadow database. 
Error:
db error: ERROR: relation "users" already exists
   0: sql_migration_connector::validate_migrations
             at migration-engine/connectors/sql-migration-connector/src/lib.rs:289
   1: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:251
```

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: 17

### Prisma Version

```
4.3.1
```

**Comment by janpio** [comment]
I think that is pretty much expected behavior. `db push` and `migrate dev` are two different systems. The first time you call `migrate dev` it will try to create the database from scratch. If you use `migrate dev` for the initial creation, the next time you run it, it should be able to just detect the necessary changes and create those into a file. (You can also of course keep using `db push` - but then you have no record of the individual migrations that were created and executed)

**Comment by tareksalem** [comment]
thank you for your comment, I actually tried to create my DB at first time with the `migrate dev` command but got the same result, Prisma doesn't record the migration, and everytime regenerate the whole SQL script

also as I mentioned, I don't know why Prisma doesn't add `CREATE IF NOT EXIST` instead of using directly `CREATE` to avoid such cases

**Comment by janpio** [comment]
Because that is exactly the job of `migrate`, to generate migrations that do not get into such situations.
Can you please try to recreate this again with `migrate dev` only and then report if you end up in the same situation again?
If so, can you please exactly describe the steps and commands you are running? Thanks.

**Comment by JosepAlacid** [comment]
So, if you created your DB with db push, you have to update your DB always using db push or your your data will get lost.
If you want to update your db as you go on with your coding, you need to start your db with prisma migrate.

**Comment by janpio** [comment]
You can also switch from `db push` to `migrate`, but then Prisma will treat it as a new start and you will need to use baselining to backfill the initial migration: https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/baselining Then the next one should properly create a diff for the next migration.

**Comment by tareksalem** [comment]
If you noticed, I am using `@@schema` to specify the related schema for each mode

I tried to remove the multiSchema option and added all models to the same schema and the migration is working fine,

the problem is related to multi schema option, it regenerates the whole sql schema again

**Comment by janpio** [comment]
Oh shoot, I indeed did _not_ notice.

From https://github.com/prisma/prisma/issues/1122#issuecomment-1231773471:
> ❗️Migrate and introspection are currently not supported with multiple schemas. If you rely on them, please do not try this preview feature in the main branch of your project or in production.

So unfortunately for now this is expected in this early preview feature.

**Comment by pimeys** [comment]
Ok, so this issue does not happen anymore with 4.7.1 or main.
