### ISSUE TITLE
crash when migration

### ISSUE THREAD

**Issue by waiting7777** [prisma/prisma#15856]
Hi Prisma Team! The following command just crashed.

## Command

`db push`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v16.14.0           | 
| Prisma CLI  | 4.3.1              | 
| Engine      | c875e43600dfe042452e0b868f7a48b817b9640b| 

## Error
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_renderer.rs:110:9] internal error: entered unreachable code

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by janpio** [comment]
What database are you using @waiting7777?
What command are you using when this happens?
Can you share some details of the schema that is causing this?

**Comment by waiting7777** [comment]
I tried to alter db to use multi-schema and I got this

**Comment by janpio** [comment]
Thanks.

What Prisma command did you use?
PostgreSQL?
What did you change?

**Comment by Jolg42** [comment]
Similar error was also reported in https://github.com/prisma/prisma/issues/15900

**Comment by jkomyno** [comment]
Hey @waiting7777, could you please share more info about this issue, as asked above? Otherwise we'll have to close this issue due to insufficient information. Thanks!

**Comment by jkomyno** [comment]
Hey @waiting7777, we're closing this issue for unresponsiveness, as we cannot proceed further with the information currently available. Should be able to collect and provide the information requested in previous messages, please leave a comment, and we will gladly re-open this issue :)
