### ISSUE TITLE
CI should send Slack message on NPM publish

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1585]
We are publishing to NPM quite often for the `alpha`s, which also triggers Integration and Introspection CI. I want to have a message in a channel each time we successfully published a new version to NPM.

Buildkite can probably send a Slack message somehow. 
Ping me for internal channel name.

**Comment by Jolg42** [comment]
@timsuchanek maybe with https://buildkite.com/changelog/88-new-pipeline-attribute-notify

**Comment by timsuchanek** [comment]
We would probably do that here https://github.com/prisma/prisma2-development-environment/blob/a4a31bbc6e34a36bf934a8b7597ceb0574634bf3/scripts/ci/publish.ts#L650

**Comment by janpio** [comment]
A (worse) alternative is being implemented in https://github.com/prisma/prisma2-e2e-tests/issues/162

**Comment by janpio** [comment]
Hopefully soon possible via Github Actions.

**Comment by janpio** [comment]
This is now implemented at https://prisma-company.slack.com/archives/C01NY6VFQAK
