### ISSUE TITLE
Investigate using a "virtual" `(@)@unique` as workaround on No-identifier-tables 

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1587]
We do not support No-identifier-tables (no PK, no UNIQUE) right now and thus have to comment them out in the schema for now.

One of the suggestions we could give users to fix or workaround this limitation (next to adding a PK column or UNIQUE constraint manually), would be to add a virtual `@unique` to one field or an `@@unique` to a combination of fields in the model.

- Does that actually help the Query Engine to be able to read data from these tables?
- What about writing or updating?
- What happens if there are actually 2 rows with the same content, thus failing this virtual constraint?
- What about relations _from_ these tables?
- What about relations _to_ these tables? (should not be possible/happen)

**Comment by janpio** [comment]
If this works, we have to reopen/recreate https://github.com/prisma/prisma2/issues/1588

**Comment by tomhoule** [comment]
The reflection around this has evolved a lot since `@@ignore` in introspection/migrate. Tables without identifiers are now fully supported in introspect/migrate. And these tables still couldn't be handled by the Client. So this issue can be moved over to the client side.

**Comment by janpio** [comment]
Not a big user problem any more, so we are not interested in this workaround any more and might just fix this underlying limitation one day - maybe.
