### ISSUE TITLE
Command failed with exit code 1: npm install @prisma/client@4.5.0

### ISSUE THREAD

**Issue by chengpengjava** [prisma/prisma#15908]
### Bug description

I have a database of mysql, and now I want to generate a table in the database,so I wrote schema and then run "npx prisma migrate dev --name init" but I received the following error:
![image](https://user-images.githubusercontent.com/33616855/196942190-2015a881-8dab-49d9-8a95-0007f4d9dcc1.png)

### How to reproduce

1.I created a MySQL database named mydatabase1
2.I created a prisma project refered to official documents like this(pn is pnpm,I used alias):
![image](https://user-images.githubusercontent.com/33616855/196943171-682ec95a-24cd-4292-ac39-50e670a552ec.png)
OK,I successfully created a prisma project and created a .env file and then I modified it like this:
![image](https://user-images.githubusercontent.com/33616855/196943833-bf693d20-c768-4664-b24c-bc6dacce5336.png)
3.I wrote a model like this:
![image](https://user-images.githubusercontent.com/33616855/196944020-4cecae0a-00ed-4306-aa56-b3c323349e9d.png)
4.I run "npx prisma migrate dev --name init"but received the following error:
![image](https://user-images.githubusercontent.com/33616855/196944714-9dd48d60-9009-4ed9-ab26-0ed5b03f4470.png)
What did I do wrong?Thanks.

### Expected behavior

It seems that it reminds me that I need "npm install npm install @prisma/client@4.5.0",but isn't it downloaded with prisma?And I didn't see it on the official website saying that additional downloads are needed about @prisma/client

### Prisma information

![image](https://user-images.githubusercontent.com/33616855/196945326-fac86c6b-3a5d-415f-ae0f-64ab16d330fe.png)

### Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: v16.15.1

### Prisma Version

![image](https://user-images.githubusercontent.com/33616855/196945627-a3c1af38-44ee-4700-bbf2-e1262e2d01bc.png)

**Comment by janpio** [comment]
Are you using an Npm mirror maybe?

Generally `prisma generate` (the command that is run in the background of `migrate dev` will auto install `@prisma/client` to your package.json. That sometimes fails with other package managers like `pnpm`, and then things explode. Maybe you can fix this by manually installing `@prisma/client` with `pn i @prisma/client` in your project and things will just work after.

**Comment by chengpengjava** [comment]
> Hey @chengpengjava, I was not able to reproduce this with the steps you provided. According to the error `@prisma/debug@4.5.0` was not found, although it is published. So maybe it's a caching issue. Could you try it again from the start (as you show in your reproduction steps)? If still unsuccessful, could you try `npm cache clean --force`?

I went through the process again but same error even if I executed npm cache clean --force.But I succeeded after run pn i @prisma/client because I did use npm mirror through @janpio reminder,thank you all

**Comment by Sharjeel-005** [comment]
Error coming from `npx prisma migrate deploy`

Command failed with exit code 1: npx prisma  
migrate deploy
(node:18088) ExperimentalWarning: CommonJS   
module C:\Users\BUZZ
TECH\AppData\Roaming\npm\node_modules\npm\node_modules\debug\src\node.js is loading ES    
Module C:\Users\BUZZ
TECH\AppData\Roaming\npm\node_modules\npm\node_modules\supports-color\index.js using      
require().
Support for loading ES Module in require() is an experimental feature and might change at 
any time
(Use `node --trace-warnings ...` to show     
where the warning was created)
Error: The "mongodb" provider is not         
supported with this command. For more info   
see https://www.prisma.io/docs/concepts/database-connectors/mongodb
   0: schema_core::state::ApplyMigrations    
             at
schema-engine\core\src\state.rs:226

Environment variables loaded from .env       
Prisma schema loaded from
prisma\schema.prisma
Datasource "db": MongoDB database
"shopify-app" at "127.0.0.1:27017"

1 migration found in prisma/migrations
