### ISSUE TITLE
`prisma2 generate --watch` exits when no models are defined in schema.prisma

### ISSUE THREAD

**Issue by peterp** [prisma/prisma#1592]
```
Error:
You don't have defined any model in your schema.prisma, so nothing will be generated.
You can define a model like this:

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}

More information in our documentation:
https://pris.ly/d/prisma-schema

error Command failed with exit code 1.
```

The error seems reasonable, but I don't think the process should exit, instead it could continue watching for changes.

Ideally it would also generate an empty client that can still be imported, since if I'm running a development-server (like we are doing in Redwood) it would fail to import the Prisma client and then fail to build.

**Comment by janpio** [comment]
Two different points here then:
1. Keep watching and generate
2. Generate even when schema is empty

I kind of agree with both, we'll discuss this.

**Comment by janpio** [comment]
Point 2) is now treated in https://github.com/prisma/prisma2/issues/1809 - this issues is only about not exiting on error during `generate --watch` now.
