### ISSUE TITLE
postgresqlExtensions fails on generating the prisma client

### ISSUE THREAD

**Issue by vleandersson** [prisma/prisma#15930]
### Bug description

When adding the new `postgresqlExtensions` and `extensions = [btree_gin, pg_trgm]` to the prisma schema, the migration works fine (`prisma migrate dev`) but the client generation fails afterward.

Error:
```
Schema validation error - Error (query-engine-node-api library)
Error code: P1012
error: The preview feature "postgresqlExtensions" is not known. Expected one of: referentialIntegrity, interactiveTransactions, fullTextSearch, fullTextIndex, tracing, metrics, orderByN
ulls, filteredRelationCount, fieldReference
  -->  schema.prisma:3
   |
 2 |     provider        = "prisma-client-js"
 3 |     previewFeatures = ["fullTextSearch", "postgresqlExtensions"]
   |
error: Property not known: "extensions".
  -->  schema.prisma:10
   |
 9 |     url        = env("DATABASE_URL")
10 |     extensions = [btree_gin, pg_trgm]
11 | }
   |

Validation Error Count: 2
```

### How to reproduce

1. Add `previewFeatures = ["fullTextSearch", "postgresqlExtensions"]` to your Prisma schema generator section
2. Add `extensions = [btree_gin, pg_trgm]` to your Prisma schema 
3. Run `prisma migrate dev`
4. The DB migration will pass, and then try to run generation of the Prisma Client - this fails

### Expected behavior

Prisma v. 4.5.0 are able to generate the client with extensions and `postgresqlExtensions` preview feature

### Prisma information

```prisma
generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["fullTextSearch", "postgresqlExtensions"]
    binaryTargets   = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
    provider   = "postgresql"
    url        = env("DATABASE_URL")
    extensions = [btree_gin, pg_trgm]
}
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.15.0

### Prisma Version

```
prisma                  : 4.5.0
@prisma/client          : 4.5.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../../node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../../node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../../node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../../node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.5.0-43.0362da9eebca54d94c8ef5edd3b2e90af99ba452
Default Engines Hash    : 0362da9eebca54d94c8ef5edd3b2e90af99ba452
Studio                  : 0.476.0
Preview Features        : fullTextSearch, postgresqlExtensions
```

**Comment by vleandersson** [comment]
Seeing that `prisma generate` prints out `Prisma CLI Version : 4.4.0` while `prisma -v` prints only as above, 4.5.0. Could this be the issue?

**Comment by janpio** [comment]
Yes, that certainly is an issue and should not be the case. Something is going wrong with the versions here.

What does your `package.json` look like re Prisma versions?
What package manager are you using?
Do you have a global installation of Prisma on your machine?
What is your project setup? The `../../..` in the engine paths indicate some deep project setup? Monorepo?

**Comment by Jolg42** [comment]
@vleandersson Additional question: are you using Turborepo?

**Comment by vleandersson** [comment]
@janpio @Jolg42 the package.json version is `4.5.0` but it looks like TypeGraphQLs prisma extension is enforcing `4.4.0` so I am gonna assume this is the issue.

It is indeed a monorepo, yarn berry.

Closing this issue as it looks like it is related to external packages

**Comment by Jolg42** [comment]
Indeed, it makes sense to me, as the latest version of https://github.com/MichalLytek/typegraphql-prisma requires `4.4.0`.
Usually the author keeps it up-to-date regularly, so wait and see or contribute a PR there is also welcome I think.

**Comment by humblecoder** [comment]
Apologies for the "post-closed" post, but I'm having a similar issue. I have a Docker configuration with Postgres in a separate container from the application. I receive could not open extension control file when attempting to enable extensions.

Does the existing capability assume everything is running on the same machine/instance?

Any chance we could get some sort of schema feature, or db push that allows for raw queries (e.g. CREATE EXTENSION IF NOT EXISTS...) before any actual table generation? 🤔

**Comment by janpio** [comment]
Best open a new issue @humblecoder - this sounds worth a dedicated look. The template will ask for the information we need.

**Comment by humblecoder** [comment]
> Best open a new issue @humblecoder - this sounds worth a dedicated look. The template will ask for the information we need.

Apologies, and correction.  This seems to **only** happen with the `postGIS` extension.  If I remove it and leave the others in place everything works correctly.  I'll do a deeper dive before I post a new issue.

Thanks.
