### ISSUE TITLE
Feature Request: Jetbrains Plugin Formatting

### ISSUE THREAD

**Issue by eighty4** [prisma/prisma#15947]
## Problem

Not formatting field name, field type and annotations in their own columns is hard to read. SQL names types and keywords and golang's struct tags are autoformatted to columns.

## Suggested solution

Format prisma schema files like IntelliJ does for SQL or golang's struct tags

## Alternatives

Take longer to read across a line of schema code

## Additional context

Formatted Prisma schema file

```prisma
model User {
    id Int @id
    email String @unique
    created_when DateTime
    last_login_when DateTime
}
```

Formatted SQL file

```sql
create table users
(
    user_id                 uuid                default uuid_generate_v4() primary key,
    email                    varchar           unique not null,
    created_when     timestamptz  not null default current_timestamp,
    last_login_when timestamptz
);
```

**Comment by Jolg42** [comment]
I think there are currently 2 community extensions but they only provide syntax highlighting of the Prisma Schema Language.
https://www.prisma.io/docs/guides/development-environment/editor-setup#jetbrains-ide

**Comment by Jolg42** [comment]
As an alternative, you could use Prettier with https://github.com/umidbekk/prettier-plugin-prisma

**Comment by eighty4** [comment]
Thanks for the alternative suggestion. Much obliged!
