### ISSUE TITLE
Running `yarn add dependency-name` removes prisma client

### ISSUE THREAD

**Issue by jrm2k6** [prisma/prisma#15945]
### Bug description

This is a follow up on https://github.com/prisma/prisma/discussions/15935.
After creating a new nextjs project, and setting up prisma for that project, everything works fine.

If I do a `yarn add lodash`, then the `@prisma/client` dependency is not recognized, and I have to run `npx prisma generate` to get it reinstalled.

If I do a `yarn remove lodash` then the `@prisma/client` dependency is reinstalled correctly, and no issue is to be noticed. 

cc @janpio 

### How to reproduce

1. Clone https://github.com/jrm2k6/prisma-client-test
3. Run `yarn install`
4. Create your .env with the correct DB credentials
5. Run `npx prisma migrate`
6. Run `npx prisma generate`
7. Run `yarn next dev`
8. You should be able to load the application in your browser
9. Run `yarn add lodash`
10. You should see an error about a missing schema file
11. Running `npx prisma generate` or `yarn remove lodash` should fix the error

### Expected behavior

When running `yarn add my-dependency`, the prisma client should still be available.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model TestEntity {
  id Int @id @default(autoincrement())

  @@map("test_entities")
}

```

```ts
import { PrismaClient } from '@prisma/client'


export async function getServerSideProps() {
  const prisma = new PrismaClient()
  const items = await prisma.testEntity.findMany({})

  return {
    props: {
      items: []
    }
  }
}

```

### Environment & setup

- OS: macOS
- Database: mysql
- Node.js version: v16.14.0

### Prisma Version

```
prisma@4.5.0
```

**Comment by Jolg42** [comment]
Which version of `yarn` are you using here? @jrm2k6

**Comment by jrm2k6** [comment]
@Jolg42 1.7.0

**Comment by Jolg42** [comment]
@jrm2k6 This version sounds very old.
From https://github.com/yarnpkg/yarn/releases it seems that it was released in 2018.
The latest version is `1.22.19`

Could you try upgrading yarn?
I think `npm install --global yarn` should do.
There is a good chance that this is already fixed.

**Comment by jrm2k6** [comment]
@Jolg42 Yeah good call. Seems to be fine after upgrading. Sorry for the trouble.
