### ISSUE TITLE
Introspection: improve schema order

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#1594]
Right now the schema is printed in alphabetical order, but many folks design their schemas with an order that makes sense to them.

My Order:

```sql
create table if not exists users (
  id serial primary key not null,
  email text not null unique
);
```

Prisma's Order:

```prisma
model users {
  email   String  @unique
  id      Int     @id
}
```

I know in Postgres, there's a column we can introspect (`attnum` in `pg_attribute`) that will give us the right order.

**Comment by do4gr** [comment]
This was implemented in 2.30. Introspection now follows the order determined by the db.
