### ISSUE TITLE
Error: Unable to establish a connection to query-engine-node-api library

### ISSUE THREAD

**Issue by dongnguyenvn** [prisma/prisma#15980]
### Bug description

```
Error: Unable to establish a connection to query-engine-node-api library. It seems that the current architecture x64 is not supported, or that libc is missing from the system.
```

 The specified module could not be found.

### How to reproduce

Run: prisma migrate dev

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS:  Win 11
- Database: PostgreSQL
- Node.js version: 19.0.0

### Prisma Version

```
4.5.0
```

**Comment by coderboysobuj** [comment]
I have same problem when I run Prisma generate on my local computer It's work but when I'm trying to run prisma generate on Shared host cpanel It's give a error 

Error: Unable to establish a connection to query-engine-node-api library. It seems that the current architecture x64 is not supported, or that libc is missing from the system.
Details: Unable to require(`/home/crafiebs/nodevenv/node_api/14/lib/node_modules/prisma/libquery_engine-debian-openssl-1.0.x.so.node`)
 /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/crafiebs/nodevenv/node_api/14/lib/node_modules/prisma/libquery_engine-debian-openssl-1.0.x.so.node)

I'm not able to fixed it. What should I do?

**Comment by Jolg42** [comment]
@coderboysobuj I see you opened a new issue, thanks! 
https://github.com/prisma/prisma/issues/17374

**Comment by aqrln** [comment]
Since there was no response from the OP and no additional details, and we already have other, more detailed issues about Windows, as well as a [new section in the system requirements page](https://www.prisma.io/docs/reference/system-requirements#windows-runtime-dependencies), I'm going to go ahead and close this issue.

Feel free to reopen the issue if your problem wasn't solved by the links above.
