### ISSUE TITLE
`prisma migrate reset --force` --force not applying in non-interactive

### ISSUE THREAD

**Issue by kieran-osgood** [prisma/prisma#16003]
### Bug description
EDIT: #9943 Discovered this that seems to be the same with NX

I have a mono-repo setup with the server included, and at the top level we compose our scripts together via [turborepo](https://turbo.build/).
In our `apps/server` package, we use a package.json script to run the integration tests, which is run against a docker database, I've simplified the script to the minimal example:
```sh
    "test": "dotenv -e .env.test prisma migrate reset --force"
```

Which works fine when run directly in the package, but when running through turborepo (non-interactive), I receive this output, despite using `--force` - #4773 

```
server-app:test: $ dotenv -e .env.test prisma migrate reset --force
server-app:test: Error: Prisma Migrate has detected that the environment is non-interactive. It is recommended to run this command in an interactive environment.
server-app:test: Use --force to run this command without user interaction.
server-app:test: See https://www.prisma.io/docs/reference/api-reference/command-reference#migrate-reset
```

### How to reproduce

Using turborepo apply a migration in a package with `prisma migrate reset --force`

### Expected behavior

The command should skip the interactive checks and force apply

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  name      String
}
```

```ts
n/a
```

### Environment & setup

- OS: MacOS
- Database: MySql
- Node.js version: 16.17.0

### Prisma Version

```
4.4.0
```

**Comment by kieran-osgood** [comment]
Interesting - changing the script to `dotenv -e .env.test prisma migrate reset -- --force` and it runs

**Comment by kieran-osgood** [comment]
> Using `dotenv-cli` indeed a bit unintuitively moves the parameters for the actual command one level down, so you need to do `-- ---` - otherwise you are telling `dotenv` to `--force` which of course Prisma can not handle or know about.

Doh - should really have realised that 😂 thanks for confirming

**Comment by pablomusumeci** [comment]
I confirm that ☝️  solves the issue. Thanks for sharing your solution!
