### ISSUE TITLE
Introspection: Automatic map columns to something sane

### ISSUE THREAD

**Issue by Notaduck** [prisma/prisma#16000]
## Problem

I'm working with multiple databases made by different people and the formatting of tables and columns is not consistent.

## Suggested solution

I know we have the `@map(.....` property, but it would be nice if we could set a default config for prisma so when we do an `prisma introspect` and it would automaticly map `SOME_TABLE` to `some_table` or `someTable` instead of doing that manually if the database has 100 tables and each table has +5 coulmns.

**Comment by Jolg42** [comment]
I think this request might be a duplicate of https://github.com/prisma/prisma/issues/1934 / https://github.com/prisma/prisma/issues/1705

What do you think @Notaduck ?

**Comment by itayperry** [comment]
+1
This would be an amazing feature!

**Comment by Notaduck** [comment]
@Jolg42 sorry for the VERY late reply, I totally missed it. But you are absolutely right! That is more or less what I asked for.

**Comment by janpio** [comment]
Let's track it via those issues then 👍
