### ISSUE TITLE
Argument of type '"query"' is not assignable to parameter of type '"beforeExit"'.

### ISSUE THREAD

**Issue by marceloverdijk** [prisma/prisma#16084]
### Bug description

Following the documentation to setup custom logging here https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging

I used: 

```
  prisma.$on('query', (e: Prisma.QueryEvent) => {
    console.log('Query: ' + e.query)
    console.log('Params: ' + e.params)
    console.log('Duration: ' + e.duration + 'ms')
  })
```

but this gives the following ts error:

`Argument of type '"query"' is not assignable to parameter of type '"beforeExit"'.ts(2345)`

### How to reproduce

Setup logging as mentioned above as per the docs.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: SQLite
- Node.js version: v18.4.0

### Prisma Version

```
❯ npx prisma -v
Environment variables loaded from .env
prisma                  : 4.5.0
@prisma/client          : 4.5.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.5.0-43.0362da9eebca54d94c8ef5edd3b2e90af99ba452
Default Engines Hash    : 0362da9eebca54d94c8ef5edd3b2e90af99ba452
Studio                  : 0.476.0
```

**Comment by SevInf** [comment]
@marceloverdijk could you please provide the full code of the setup, including `prisma` variable declaration and initialisation? This code snippet correctly typechecks on 4.5.0:

```ts
  const prisma = new PrismaClient({ log: [{ emit: 'event', level: 'query' }] })
  prisma.$on('query', (e: Prisma.QueryEvent) => {})
```

**Comment by marceloverdijk** [comment]
Hi @SevInf ,

Sure here is my full setup:

```
import { Prisma, PrismaClient } from '@prisma/client'

// PrismaClient is attached to the `global` object in development to prevent
// exhausting your database connection limit.
//
// Learn more:
// https://pris.ly/d/help/next-js-best-practices

declare global {
  var prisma: PrismaClient | undefined
}

let prisma = global.prisma

if (!prisma) {

  prisma = new PrismaClient({
    log: [
      {
        emit: 'event',
        level: 'query',
      },
      {
        emit: 'stdout',
        level: 'error',
      },
      {
        emit: 'stdout',
        level: 'info',
      },
      {
        emit: 'stdout',
        level: 'warn',
      },
    ],
  })

  if (process.env.NODE_ENV !== 'production') {

    // @ts-ignore (https://github.com/prisma/prisma/issues/16084)
    prisma.$on('query', (e: Prisma.QueryEvent) => {
      console.log('Query: ' + e.query)
      console.log('Params: ' + e.params)
      console.log('Duration: ' + e.duration + 'ms')
    })

    global.prisma = prisma
  }
}

export default prisma

```

Note for now I added a `// @ts-ignore` to get rid of the 
`Argument of type '"query"' is not assignable to parameter of type '"beforeExit"'.ts(2345)`

<img width="369" alt="image" src="https://user-images.githubusercontent.com/197004/199326670-07613ce8-d02d-4739-b36a-40759cb9f721.png">

It's interesting to know that you don't have this warning.

**Comment by SevInf** [comment]
Hi @marceloverdijk!
The problem is global variable declaration. Prisma types prevent you from adding event listener for `query` event unless you configure it in the constructor. Normally, type inference will do all the work, but since you have type declaration with explicit type annotation, you have to specify that 'query' even should be configured on this instance explicitly. If you change it to this code snippet, it will work:

```ts
declare global {
  var prisma: PrismaClient<'query'> | undefined
}
```

**Comment by marceloverdijk** [comment]
Thx @SevInf that's really helpful! I still have to learn some TypeScript parts ;-)

**Comment by marceloverdijk** [comment]
Hi @SevInf I just tried it on my project but unfortunately it does not help..

Changing the global declaration to:

```
declare global {
  var prisma: PrismaClient<'query'> | undefined
}
```

gives now: `Type '"query"' has no properties in common with type 'PrismaClientOptions'.ts(2559)` 

<img width="372" alt="image" src="https://user-images.githubusercontent.com/197004/199552352-01ca2e28-aa75-4845-8c90-8b4630779cbf.png">

**Comment by marceloverdijk** [comment]
Thx @herzog0 , adding `Prisma.PrismaClientOptions` did the trick!
