### ISSUE TITLE
Re-introspection should not remove relations when relationMode="prisma"

### ISSUE THREAD

**Issue by aaron-henselin** [prisma/prisma#16130]
### Bug description

Expectation based on #2221 is that the usage of relationMode="prisma" should prevent the removal of manually added relationships. This is necessary for Heroku Connect setups, where "sfid"-based relationships are not traditional FK.

However, manually added relationships appear to be automatically removed on prisma 4.5.0.

### How to reproduce

(1) Using this or similar schema before introspection:

	generator client {
	  provider = "prisma-client-js"
	  previewFeatures = ["referentialIntegrity"]
	}

	datasource db {
	  provider = "postgresql"
	  url      = env("DATABASE_URL")
	  relationMode = "prisma"
	}

	model Event {
	  id                               Int       @id @default(autoincrement())
	  sfid                             String?   @unique(map: "hcu_idx_event__c_sfid") @db.VarChar(18)
	  Track  Track[]
	  @@map("event__c")
	}

	model Track {
	  
	  parent         Event	       @relation(fields: [parentId], references: [sfid])
	  parentId       String        @map("event__c") @db.VarChar(18)
	  sfid           String?       @unique(map: "hcu_idx_track__c_sfid") @db.VarChar(18)
	  id             Int           @id @default(autoincrement())
	  @@index([parentId], map: "hc_idx_track__c_event__c")
	  @@map("track__c")
	}

(2) run `db pull` 
(3) schema has had its relations removed:

	generator client {
	  provider = "prisma-client-js"
	  previewFeatures = ["referentialIntegrity"]
	}

	datasource db {
	  provider = "postgresql"
	  url      = env("DATABASE_URL")
	  relationMode = "prisma"
	}

	model Event {
	  id                               Int       @id @default(autoincrement())
	  sfid                             String?   @unique(map: "hcu_idx_event__c_sfid") @db.VarChar(18)

	  @@map("event__c")
	}

	model Track {
	  
	  parentId       String        @map("event__c") @db.VarChar(18)
	  sfid           String?       @unique(map: "hcu_idx_track__c_sfid") @db.VarChar(18)
	  id             Int           @id @default(autoincrement())

	  @@index([parentId], map: "hc_idx_track__c_event__c")
	  @@map("track__c")
	}

### Expected behavior

Manually added @relations should never be removed when using relationMode="prisma"

### Prisma information

```prisma

	generator client {
	  provider = "prisma-client-js"
	  previewFeatures = ["referentialIntegrity"]
	}

	datasource db {
	  provider = "postgresql"
	  url      = env("DATABASE_URL")
	  relationMode = "prisma"
	}


	model Event {
	  id                               Int       @id @default(autoincrement())
	  sfid                             String?   @unique(map: "hcu_idx_event__c_sfid") @db.VarChar(18)
	  Track  Track[]
	  @@map("event__c")
	}

	model Track {
	  
	  parent         Event	       @relation(fields: [parentId], references: [sfid])
	  parentId       String        @map("event__c") @db.VarChar(18)
	  sfid           String?       @unique(map: "hcu_idx_track__c_sfid") @db.VarChar(18)
	  id             Int           @id @default(autoincrement())
	  @@index([parentId], map: "hc_idx_track__c_event__c")
	  @@map("track__c")
	}

```

### Environment & setup

- OS: Windows
- Database: PostgreSQL / Heroku Connect
- Node.js version: v16.15.0

### Prisma Version

```
4.5.0
```

**Comment by Jolg42** [comment]
Can reproduce, and it's already fixed via https://github.com/prisma/prisma/issues/11022

Note: fix will be available in next 4.6.0 release planned on Tuesday (November 8th).
