### ISSUE TITLE
Error opening a TLS connection: connection closed via error

### ISSUE THREAD

**Issue by chenhbc** [prisma/prisma#16175]
### Bug description

Prisma schema loaded from src/prisma/schema.prisma
Environment variables loaded from .env
Datasource "db": PostgreSQL database "xxx", schema "public" at "xx.xx.xx.xx:9005"

✖ Introspecting based on datasource defined in src/prisma/schema.prisma

Error: P1011

Error opening a TLS connection: connection closed via error

### How to reproduce

After running:
`npx prisma db pull`

### Expected behavior

pull all the tables out from database and populate `schema.prisma`

### Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

DATABASE_URL="postgresql://xx:xx@xx.xx.xx.xx:9005/DB?schema=public"

### Environment & setup

- OS: macOS
- Database: ClickHouse via Postgresql interface: https://clickhouse.com/docs/en/interfaces/postgresql
- Node.js version: v19.0.1

### Prisma Version

```
4.5.0
```

**Comment by SevInf** [comment]
ClickHouse is not supported in Prisma at the moment regardless of the wire protocol: I am going to close this issue in favor of other request for ClickHouse support you've opened #16174

**Comment by SevInf** [comment]
ClickHouse is not supported in Prisma at the moment regardless of the wire protocol: I am going to close this issue in favor of other request for ClickHouse support you've opened #16174
