### ISSUE TITLE
NodeJS + Docker | Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!

### ISSUE THREAD

**Issue by noah-haub** [prisma/prisma#16182]
### Bug description

I want to use docker compose with NodeJS and Prisma, but for some reason keep getting this error when running it on my Digital Ocean Droplet.

npx prisma generate

Prisma schema loaded from prisma/schema.prisma                                                         
Error: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!                                                                                   
Details: Unable to require(`/app/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`)    
libssl.so.1.1: cannot open shared object file: No such file or directory
[Context: getDmmf]

Prisma CLI Version : 4.6.0docker-compose

### How to reproduce

Create a simple NodeJS + Express application and use Prisma in it.

### Expected behavior

I excpected prisma generate to work. It works when developing locally, but not when I deploy it to my Digital Ocean Droplet.

### Prisma information

```prisma
generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["extendedWhereUnique"]
    binaryTargets   = ["native", "debian-openssl-1.1.x"]
}

datasource db {
    provider = "mongodb"
    url      = env("MONGODB_URI")
}
```

### Environment & setup

- OS: Ubuntu 20.04.2 LTS
- Database: MongoDB
- Node.js version: v16.15.1

### Prisma Version

```
4.6.0
```

**Comment by noah-haub** [comment]
Everything seems to work fine now.

All I changed was the node image I was pulling in my Dockerfile.

I was using this base image:
`node:16-slim`
Now it's working and I'm using this base image:
`node:18-slim`

Can't believe it was just the wrong version hahah.

**Comment by jkomyno** [comment]
Hi @noah-haub, I'm closing this issue as you've found a working solution: using `node:18-slim.
Let me give you (and future readers) a bit more context about this.

The `node:16-slim` Docker image is an alias of `node:16-buster-slim`, which uses Linux Debian 10.x (Buster) under the hood. The `slim`  variant of Debian Buster doesn't come with any version of `openssl` installed, which is a fundamental system library Prisma (and, in particular, its query engine used by `@prisma/client`) depends on. If you wanted to use `node:16-slim` and Prisma together, you'd need to manually install `openssl-1.1.x`, as shown [here](https://github.com/prisma/ecosystem-tests/blob/8e1eb547b78c2f5781e597838afb8d984c246c5e/docker/debian-buster-amd64-openssl-1.1.x/Dockerfile#L7-L10):

```Dockerfile
RUN apt-get update -y \
  && apt-get install -y openssl
```

`node:18-slim`, on the other hand, is an alias of `node:16-bullseye-slim`, which uses Linux Debian 11.x (Bullseye) and has `openssl-1.1.x` already installed.

**Comment by pimmesz** [comment]
Doesn't work for me. Still getting `Error: Not Found https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/linux-arm-openssl-1.1.x/libquery_engine.so.node.gz`

with `FROM node:18-slim`

**Comment by jkomyno** [comment]
Hi @pimmesz, could you please open a new issue using [this issue template](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&labels=team%2Fschema&template=bug_report.yml)? It looks like you're on an `arm32` linux machine, which should be supported by Prisma.

**Comment by pimmesz** [comment]
Thanks for your reply. I have an [open issue](https://github.com/prisma/prisma/issues/17284) at the moment. I'm running `Linux 5.15.84-v8+ aarch64`
