### ISSUE TITLE
Size of schema drastically spikes memory (RAM) usage

### ISSUE THREAD

**Issue by yharaskrik** [prisma/prisma#16184]
### Bug description

We are seeing high memory usage in our servers and I was able to track it down to including Prisma. Here are the stats:

Bare Nest server: 37.6MB
Bare Nest server with simple Schema: 48.7MB
Bare Nest server with our production PostgreSQL schema: 307.2MB

Production Schema Stats:

114 Models
32 enums

The memory spike seems to come from the size of our schema. Is this expected? a 250MB spike for running a production sized schema (non-trivial) seems massive.

### How to reproduce

Unfortunately I cannot share our production schema (for obvious reasons) ~but this should be reproducible by generating a prisma client for a large schema and including it in a Nest (or express) server.~

A plain Nest app can get generated with `npx create-nx-workspace --preset nest` and then just following the prisma setup instructions.

~Will gladly provide any additional information to help track it down, or if there is an open source "large" schema anyone knows of I can try and make a repro~

Reproduction:

This doesn't provide the exact same memory spike as the schema is smaller than ours ~35 models not 114 but it does demonstrate the issue of climbing memory based on schema size:

Repo: https://github.com/yharaskrik/plain-nest-prisma-mem-spike-demo

Steps:
1. `yarn install`
2. `yarn prisma generate`
3. `yarn nx build`
4. `node dist/apps/api/main.js`

Startup was about 115MB for me and idle is about 80MB

Without Prisma at all startup is about 35MB and idle is 24MB.

![image](https://user-images.githubusercontent.com/9469090/200873620-818ab0e5-cc67-4028-b60d-b2f1da231b2f.png)

### Expected behavior

Memory increases but not at such a drastic rate.

### Prisma information

```prisma
// cannot share our production schema, should be reproducible with any large schema, we have 114 models
```

Pretty standard PrismaClient implementation for Nest
```ts
@Injectable()
export abstract class BaseCorePrismaService<T extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions>
    extends PrismaClient
    implements OnModuleInit, OnModuleDestroy
{
    protected constructor(
        protected readonly config: BaseCorePrismaConfig,
        protected readonly optionsArg?: Prisma.Subset<T, Prisma.PrismaClientOptions>
    ) {
        super(optionsArg);
    }

    async onModuleInit(): Promise<void> {
        await this.$connect();
    }

    async onModuleDestroy(): Promise<void> {
        await this.$disconnect();
    }

    async enableShutdownHooks(app: INestApplication): Promise<void> {
        this.$on('beforeExit', async () => {
            await app.close();
        });
    }
}
```

### Environment & setup

- OS: Apple M1 Max, 32GB of RAM, Ventura 13.0 (We also see high mem on our deployed alpine linux docker containers)
- Database: Postgres
- Node.js version: 14.20.2

### Prisma Version

```
3.15.2
```

**Comment by yharaskrik** [comment]
Added a reproduction.

**Comment by jkomyno** [comment]
Hey @yharaskrik, could you please update the Prisma version in the issue description? I'm afraid we haven't yet released version `6.15.2` (the latest one is `4.6.0`). Maybe you meant `3.15.2`?

Moreover, would you be so gentle as to reproduce this memory benchmark with:
- `node:18.12.1`
- `prisma@4.6.1`

please?

**Comment by yharaskrik** [comment]
> Hey @yharaskrik, could you please update the Prisma version in the issue description? I'm afraid we haven't yet released version `6.15.2` (the latest one is `4.6.0`). Maybe you meant `3.15.2`?
> 
> Moreover, would you be so gentle as to reproduce this memory benchmark with:
> 
> * `node:18.12.1`
> * `prisma@4.6.1`
> 
> please?

Yes haha I definitely did mean `3.15.2`! Oops.

I will update and see if I am still seeing the memory issues.

**Comment by yharaskrik** [comment]
@jkomyno heres the results from prisma 4.6.0 and node 18

![image](https://user-images.githubusercontent.com/9469090/200902328-bbbdcff8-9f24-447b-a8d9-dbe03cae23ad.png)

**Comment by yharaskrik** [comment]
Ok so good news! I don't think this is an issue with Prisma (well for v4, for v3 there is something going on).

If I move our prod schema over to the repo i used for the reproduction i see numbers more in line with no prisma, one model and 35 models which is good! So that solves about 200-250MB of the RAM usage. Going to see if I can track down the rest of the delta, will report back as the reproduction in our repo using our schema is still running at 252/200MB numbers even though its a bare server with just prisma.

**Comment by yharaskrik** [comment]
Ok so in our repo with the bare Nest server (and no Prisma) its about 72/54MB (startup/idle) but when I add in our prisma services (114 models) its about 245/200. When I use this same schema in the reproduction repo it's only around 55/42. So it IS including Prisma that is doing it (just less of a problem with v4 it seems). Anything else I can do to try and debug this a bit more to see why including Prisma is taking up more RAM (albeit less than before!) in our repo?

**Comment by yharaskrik** [comment]
OK some more information, sorry if this is unhelpful. If I generate a new plain Nest server in our repo and include our prisma schema in it the Server sits idle at 113MB (which is lower than our other one with prisma).

(numbers `<startup>/<idle>`)

Fresh Nest Server w/o Prisma: 35MB/25MB
Fresh Nest Server w/ Prisma: 113Mb/113MB

Stripped down production server w/o Prisma: 62MB/43MB
Stripped down production server w/ Prisma: 123MB/98MB

So as we can see there is still quite a bit of memory being used once I include our production schema.

Node: 18.12.2
Prisma: 4.6.0

**Comment by sibeliuz** [comment]
Same situation. More than 100 models, memory footprint shown in kubernetes is more than 600Mb.

**Comment by yharaskrik** [comment]
Ok so we recently upgrades to Prisma 4.7.1 (latest as of this writing).

103MB startup
88MB idle

This is using a fresh Nest server with nothing else in it.

**Comment by SevInf** [comment]
Hey, @yharaskrik and all the others in this thread. May I ask you to try `prisma@4.12.0` with `jsonProtocol` feature enabled? This should improve memory situation somewhat and even if on larger schemas it will probably still won't be ideal, i still expect to be much better than with default protocol.

**Comment by yharaskrik** [comment]
Looks like tests are all passing now with 4.13.0

**Comment by janpio** [comment]
You might have seen that we recently published a quite extensive blog post on the work we have been doing to optimize the cold start of Prisma ORM: [How We Sped Up Serverless Cold Starts with Prisma by 9x](https://www.prisma.io/blog/prisma-and-serverless-73hbgKnZ6t).

While it was not mentioned explicitly in the blog post (as we did not really keep good track of the changes and wanted to focus on latency), this also _massively_ improved the memory usage during startup and the first query of Prisma Client. Some graphs:

![image](https://user-images.githubusercontent.com/183673/234358834-82747361-1048-47ca-a6b7-103e3e94b0ca.png)

So Resident set size of a massive schema (with 500 models) is down from 330MB to 107MB, and JS Heap size is down from 60MB to 15MB. You can see how the increase is most visible the bigger the schema is.

And we are not done, but will keep optimizing this to lower that number much more.

Note: This is improvement is currently only available with the `jsonProtocol` preview feature: https://github.com/prisma/prisma/issues/18095 We are still looking for more testers of that that can give us feedback.

**Comment by janpio** [comment]
I am closing this issue for now. 

We further improved the memory usage after our blog post and my comment here, and are now generally happy with it even with massive schemas. `jsonProtocol` will soon be promoted to GA, and with that the default experience of using Prisma in serverless environments should be comparable to any other database Clients.

If someone thinks their app still has bad memory characteristics, triggered by your Prisma schema size, please open a new issue and we will be happy to take a look and figure out what is happening. Thanks!
