### ISSUE TITLE
The name is a mixture of a collection and field names

### ISSUE THREAD

**Issue by yieldinov** [prisma/prisma#16191]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v12.22.12          | 
| Prisma CLI  | 4.6.0              | 
| Engine      | 2e719efb80b56a3f32d18a62489de95bb9c130e3| 

## Error
```
Error: [introspection-engine/datamodel-renderer/src/datamodel/composite_type/field.rs:240:17] internal error: entered unreachable code: The name is a mixture of a collection and field names. It should never be empty
```

**Comment by SevInf** [comment]
Hi @yieldinov!
Can you share more details?

1. What DB provider are you using?
2. What is your prisma schema?
3. What is your DB schema?

**Comment by yieldinov** [comment]
```
npx prisma db pull --composite-type-depth=0
```
worked for some reason

the initial config is 
```
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

**Comment by pimeys** [comment]
Is this still an issue with 4.7.0? We did lots of refactoring in this codebase, removing many panics.

**Comment by Weakky** [comment]
Hey @yieldinov,

Could you please confirm whether this is still an issue you're experiencing?

Thank you 🙏

**Comment by yieldinov** [comment]
Not relevant anymore
