### ISSUE TITLE
You already added the platforms "debian-openssl-1.1.x"

### ISSUE THREAD

**Issue by mrseankumar25** [prisma/prisma#16207]
Hello there,

I am getting this while deploying it to netlify
![image](https://user-images.githubusercontent.com/43328839/200920322-3997dd9b-ac94-4118-9bad-151d1212b72a.png)

this is my binaryTargets looks like in schema.prisma
![image](https://user-images.githubusercontent.com/43328839/200920527-4277de18-48c3-44f2-8eca-bc968033478d.png)

Thank you

**Comment by mrseankumar25** [comment]
Hi @Jolg42 

Thank you for the reply, I got this one error I tackled earlier

**Comment by janpio** [comment]
This might actually work without _any_ `binaryTargets` values. Have you tried that?

**Comment by mrseankumar25** [comment]
> This might actually work without _any_ `binaryTargets` values. Have you tried that?

I was tried it, however then it show "debian-openssl-1.1.x" missing issue

**Comment by mrseankumar25** [comment]
### Update
it worked after "Clear cache and deploy site"

![image](https://user-images.githubusercontent.com/43328839/205455079-d6540179-a6e2-4a75-82d5-dc1db09f6831.png)

**Comment by janpio** [comment]
It is possible that you got the error, then found `binaryTargets = ["native", "rhel-openssl-1.0.x"]` somewhere, committed that and thought that should be enough via a deployment - but only the "Clear cache and deploy site" actually took care of that properly and really deployed such a new Client?

**Comment by janpio** [comment]
Huh, is that close a confirmation @mrseankumar25 or is this just not relavant any more? 
If you can confirm, this is still a problem we want to solve properly.
