### ISSUE TITLE
Call for Suggestions - Category Name for Prisma Client

### ISSUE THREAD

**Issue by 2color** [prisma/prisma#1622]
Hey all 👋🏼,

As the Prisma 2.0 launch approaches, we're brainstorming a category name for Prisma Client and we'd love your feedback. Our main goal at Prisma is to make working with databases easy, and we see Prisma Client as central to that goal. Naming is an extension of that goal and the name should express its functionality.

### Prisma Client is not an ORM, but what is it?
Up until now, we've likened Prisma Client to Query Builders with the term *Advanced Query Builder*, but the term Query Builders is slightly misleading as it's used in the context of *SQL Query Builders*. While Prisma Client is compatible with SQL databases, its querying interface is more universal, given its database-agnostic nature and data-centric approach. We believe that the name should reflect that and ask for your input.

### Poll

To vote, click on one of the options below:

[![](https://api.gh-polls.com/poll/01E1A2DB0JSZYZKYVYHSTVGD84/Universal%20Query%20Builder)](https://api.gh-polls.com/poll/01E1A2DB0JSZYZKYVYHSTVGD84/Universal%20Query%20Builder/vote)
[![](https://api.gh-polls.com/poll/01E1A2DB0JSZYZKYVYHSTVGD84/Dynamic%20Query%20Builder)](https://api.gh-polls.com/poll/01E1A2DB0JSZYZKYVYHSTVGD84/Dynamic%20Query%20Builder/vote)
[![](https://api.gh-polls.com/poll/01E1A2DB0JSZYZKYVYHSTVGD84/Progressive%20Query%20Builder)](https://api.gh-polls.com/poll/01E1A2DB0JSZYZKYVYHSTVGD84/Progressive%20Query%20Builder/vote)
[![](https://api.gh-polls.com/poll/01E1A2DB0JSZYZKYVYHSTVGD84/Schema-based%20Query%20Builder)](https://api.gh-polls.com/poll/01E1A2DB0JSZYZKYVYHSTVGD84/Schema-based%20Query%20Builder/vote)
[![](https://api.gh-polls.com/poll/01E1A2DB0JSZYZKYVYHSTVGD84/Other%20-%20add%20suggestion%20as%20comment)](https://api.gh-polls.com/poll/01E1A2DB0JSZYZKYVYHSTVGD84/Other%20-%20add%20suggestion%20as%20comment/vote)

**Comment by dmfay** [comment]
hey, [Massive.js](https://massivejs.org) maintainer here! 👋 Prisma and Massive share some conceptual DNA such as API-style interactions, schema introspection, and so on. I've usually defaulted to calling this not-a-classical-O/RM category (also inclusive of tools like [MyBatis](https://blog.mybatis.org/)) "data mappers". It's a loose reading of Fowler to say the least, but then so's the common usage of "object/relational mapper" to mean active record or at least model-driven styles. I could get behind a sufficiently expressive new term, but what I think "data mapper" does well is to establish both a similarity of purpose and a difference of method vis-à-vis classical O/RMs.

Of the suggestions so far, "universal query builder" seems more concerned with vendor/flavor support than with the mode of interaction, and "dynamic" and "progressive" don't mean much. "Schema-based" has promise! "Schema-driven" pops a little more, but like you I think "query builder" sells the category a bit short. Query building is naturally involved, but to me the most important thing about these tools is that they present a holistic interface for data access and manipulation.

"Schema mapper", perhaps?

**Comment by steebchen** [comment]
I think Prisma client is more than a query builder, which is why I always liked the term “Typesafe Database Client”, since it’s basically a database client but typesafe regardless if you’re building a query (`where: { .. }`) or receiving data (`if (result.user.posts…)`).

**Comment by heymartinadams** [comment]
Prisma Client is a **Universal DPI** — a Universal Database Programming Interface (as opposed to an API) 😄 (I have no clue if this is an even remotely accurate description though).

**Comment by williamluke4** [comment]
Omnipotent Database Adapter

**Comment by heymartinadams** [comment]
Let’s just call it the _Force_ and be done with it. 😁

**Comment by flybayer** [comment]
“Database client” is really good. Type safe and universal database client.

“Query builder” is also good. Type safe and DB agnostic query builder.

“Advanced query builder” doesn’t tell me anything. Like, aren’t all query builders advanced? :sweat_smile:	

"Universal query builder" makes sense, but I prefer “db agnostic” since it’s more concrete. I.e universal query builder could also include a query builder for graphql

**Comment by 2color** [comment]
Thank you all for the feedback.

Based on the response to Prisma so far, we’ve decided to stick to **query builder**.

Ultimately, Prisma Client is a query builder with features that differentiate it from SQL query builders. 
Those features can be denoted before query builder depending on the context and the intended emphasis, e.g. “type-safe, auto-generated query builder” or "database agnostic query builder".
