### ISSUE TITLE
Generate types and enums into a separate truly isomorphic file

### ISSUE THREAD

**Issue by capaj** [prisma/prisma#16239]
## Problem

When I want to import an enum from prisma in a project with a vite.js frontend, the import fails with a message `PrismaClient is unable to be run in the browser` or similar

## Suggested solution

instead of generating the types into @prisma/client, how about having `@prisma/client/types`?

## Alternatives

I could write a custom generator which generates the enums into my custom file. This would not be ideal as I would basically have all my enums defined twice in the codebase.

## Additional context

https://twitter.com/capajj/status/1590995874012090368

**Comment by SevInf** [comment]
` PrismaClient is unable to be run in the browser` error happens only if you try to instantiate `PrismaClient`.  You should be able to import a generated enum inside browser builds. Please, make sure that `new PrismaClient()` is not called anywhere in your imports graph.
If you are absolutely sure that this is not the case, we'd like to see a reprorduction - some minimal setup where we would see this happening.

**Comment by capaj** [comment]
@SevInf you're right. I tested with latest vite 4.0.0 and it does work indeed fine.
```ts
import { MyEnum } from '@prisma/client'
```
![image](https://user-images.githubusercontent.com/1305378/207017908-f6e91495-ad1f-4a75-bc1a-afd5a49a0ad8.png)

 I must have had some issue with the import tree on my side. Will give this another go in in my repo where I bumped into it

**Comment by capaj** [comment]
works there too now. Not sure if it is the new vite or just my own graphq changed, but I definitely saw the problem. Anyway, happy to see this resolved :muscle:

**Comment by capaj** [comment]
I know what the problem was. It works on dev, but fails when bundling with vite for production. I will reopen this issue now and I will try to add a repro link in the next few days.

**Comment by capaj** [comment]
this is the error message I am getting today:
```
Uncaught TypeError: Failed to resolve module specifier ".prisma/client/index-browser". Relative references must start with either "/", "./", or "../".
```

**Comment by mankinchi** [comment]
@capaj can you share your working code with vite? I ran into the issue of Thee requested module '......../server/prisma/generated/index.js' does not provide an export named 'X'. With X being an enum. Types is fine, but enum doesn't like to work

**Comment by janpio** [comment]
PIng @capaj - did you have time to create that reproduction? We would still like to understand this better.

**Comment by Weakky** [comment]
Hey @capaj,

A reproduction would be really helpful for us to move that issue forward. Let us know if you got the chance to do it.

Thank you 🙏

**Comment by jharrell** [comment]
Hi @capaj 

Following up here: have you seen @janpio and @Weakky 's comments? We'd love a repro in order to dig into this further.

**Comment by janpio** [comment]
Closing as we are lacking information to further debug this. Please comment or open a new issue if you have the same problem.

(Closing as resolved as the original problem from the title and description indeed was resolved)
