### ISSUE TITLE
Prisma fails to build due to suddenly missing binaries (debian-openssl-3.0.x/prisma-fmt.gz)

### ISSUE THREAD

**Issue by judehunter** [prisma/prisma#16246]
### Bug description

Hello,
I am maintaining a project that uses a legacy version of Prisma from back in the day (`"@prisma/client": "^2.11.0", "@prisma/cli": "^2.11.0"`). Now I understand this is likely beyond the scope of any support, but I would still like to ask if anything could be done to solve the problem described below, as it seems to be an issue with some kind of CDN on the prisma side.

**Moreover, this error could be affecting newer versions of prisma as well.**

### The problem
`prisma generate` fails due to the following error:
```
Error: Not Found https://binaries.prisma.sh/all_commits/58369335532e47bdcec77a2f1e7c1fb83a463918/debian-openssl-3.0.x/prisma-fmt.gz
```
When trying to access the URL from the error,
https://binaries.prisma.sh/all_commits/58369335532e47bdcec77a2f1e7c1fb83a463918/debian-openssl-3.0.x/prisma-fmt.gz
I get the following error in my browser:
```
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>all_commits/58369335532e47bdcec77a2f1e7c1fb83a463918/debian-openssl-3.0.x/prisma-fmt.gz</Key>
  <RequestId>9CGQPAYQV9GCRY18</RequestId>
  <HostId>ztfIwmtu1KVgESDxXuj+OHuHlYZQF+05gkfxBMg9akoGbJlOeipwDfjz9luGaLReLTrEvrxgfJ4=</HostId>
</Error>
```

My guess is that for some reason these files were pruned from S3. Or the configuration for the bucket or CloudFront has changed.

In either case, it would be great to know if this could be resolved to maintain support for legacy versions of prisma.

### How to reproduce

I guess this problem could be reproduced by simply accessing
https://binaries.prisma.sh/all_commits/58369335532e47bdcec77a2f1e7c1fb83a463918/debian-openssl-3.0.x/prisma-fmt.gz
in your browser.

The `prisma generate` command fails because the file in question is unavailable or inaccessible.

Otherwise, for a more thorough reproduction, I believe simply following these steps should be enough:
- `yarn add @prisma/client@^2.11.0 @prisma/cli@^2.11.0`
- (use any existing project compatible with that version or create a simple boilerplate)
- `yarn prisma:generate`, run on Ubuntu 22.04.1 LTS. In my case, Github Actions.

### Expected behavior

The command should work without failing to access that file. Business as usual.

### Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

### Environment & setup

- OS: Ubuntu 22.04.1 LTS. In my case, Github Actions (image ubuntu-22.04, version 20221027.1)
- Database: Postgres
- Node.js version: v12.22.12

### Prisma Version

```
@prisma/client@^2.11.0 @prisma/cli@^2.11.0
```

**Comment by judehunter** [comment]
The cause of this might be related to #16233 although the "symptoms" are different. Maybe the cache invalidation on cloudfront caused this, but just guessing.

**Comment by janpio** [comment]
Did you maybe recently update your system to use a different OpenSSL version?

This old version does not have a build for OpenSSL 3:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/183673/201482042-2a6909c6-7b7c-4103-a761-a429f000fa9a.png">

You will have to update to one that does to use a system with OpenSSL 3.

**Comment by judehunter** [comment]
That was it! I had my GitHub actions set up to use ubuntu-latest. I locked the version to an older one and it works again! Thank you @janpio
