### ISSUE TITLE
Raise an error when no `openssl` version is detected

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#16256]
Prisma can only work properly in presence of an `openssl` library. Some "slim" Docker images do not ship SSL libraries by default, as they trade off versatility for smaller disk memory footprint.

In such "slim" Docker cases (here's an [example](https://github.com/prisma/prisma/issues/16232)),any `prisma` command using the engines fails with an error similar to:

> Error: Unknown binaryTarget `linux-arm64-openssl-undefined` and no custom engine files were provided                               

This happens e.g. when using:
- `prisma generate`
- `prisma init`
- `prisma db push`
- `prisma format`

Although `prisma format` itself uses a Wasm module that doesn't rely on library/binary engines, every CLI command is only executed after `ensureBinariesExist()` from `@prisma/engines` is called, which in turn calls the `download()` function from `@prisma/fetch-engines`, which triggers the `Unknown binaryTarget` error above.

Rather than silently returning an `undefined` openssl version number, we should explicitly raise an error stating that `openssl` is missing, and should be installed. In practice, the code block to modify is likely in [`getPlatform.ts`](https://github.com/prisma/prisma/blob/99487a798c892e634b82587c49e5397f4c1918b6/packages/get-platform/src/getPlatform.ts#L105-L130).

For additional context:
- [this comment](https://github.com/prisma/prisma/issues/16232#issuecomment-1313445886) on Github
- this [internal thread](https://prisma-company.slack.com/archives/C04AA3953B6/p1668072893966839) on Slack

**Comment by janpio** [comment]
> In practice, the code block to modify is in [`getPlatform.ts`](https://github.com/prisma/prisma/blob/99487a798c892e634b82587c49e5397f4c1918b6/packages/get-platform/src/getPlatform.ts#L105-L130).

Not that it might be ok and expected for some OS and platforms for this to return `undefined` - so we need to be careful, and possibly handle that on higher levels (`getPlatform()`).

**Comment by jkomyno** [comment]
Closing this in favor of https://github.com/prisma/prisma/issues/17154.
