### ISSUE TITLE
"Distinct" generated type throws a type error if a readonly input is provided 

### ISSUE THREAD

**Issue by toddtarsi** [prisma/prisma#16263]
### Bug description

Distinct throws a type error if its receives a readonly array.

This should be okay in the type system I feel. As it is, it discourages complex clause reuse via `as const` to maximize type narrowing. Okay, enough complaining. There is an easy enough workaround for now, simply coerce the type to it's non-readonly variant.

### How to reproduce

Look at a clause like this in an IDE. It can be any query at all as long as you type the variable via `as const`.
```
const queryBlock = {
  distinct: ['id'], // <-- will cause a type error
  where: {field: {equals: value}},
} as const;

await client.things.findMany(queryBlock);
```

Workaround for now is this:

```
const queryBlock = {
  distinct: ['id'] as ['id'],
  where: {field: {equals: value}},
} as const;

await client.things.findMany(queryBlock);
```

### Expected behavior

No type error for a valid distinct field.

### Prisma information

```prisma
model things {
  id                    Int                    @id @default(autoincrement())
  field                Int
}

```

```ts
const value = 3;
const queryBlock = {
  distinct: ['id'],
  where: {field: {equals: value}},
} as const;

await client.things.findMany(queryBlock);
```

### Environment & setup

- Node.js version: 16

### Prisma Version

```

```

**Comment by SevInf** [comment]
Hi @toddtarsi!
There is a [feature request](https://github.com/prisma/prisma/issues/5025) for readonly types as well as [an explanation](https://github.com/prisma/prisma/issues/5025#issuecomment-732248598) on why we didn't do it so far. I am going to close this issue as a duplicate, let's continue discussion there.

**Comment by toddtarsi** [comment]
Oh, whoops! My mistake, thought this was something I caught. Thanks for the explanation and providing a great OSS codebase!
