### ISSUE TITLE
Prisma allows same names for referencing different relations resulting in unknown errors

### ISSUE THREAD

**Issue by PriyavKaneria** [prisma/prisma#16264]
## Bug
Prisma allows same names for referencing different relations

## To reproduce
I have this Prisma schema (removed all unnecessary models and fields):
```
model User {
  id             Int       @id @default(autoincrement())
  email          String    @unique @db.VarChar(255)
  project        Project[] @relation("creator")
  projectUpdated Project[] @relation("updater")
  table          Table[]   @relation("creator")
  tableUpdated   Table[]   @relation("updater")
}

model Project {
  id    Int    @id @default(autoincrement())
  created_by   String
  updated_by   String
  creator      User         @relation("creator", fields: [created_by], references: [email])
  updater      User         @relation("updater", fields: [updated_by], references: [email])
}

model Table {
  id    Int    @id @default(autoincrement())
  created_by   String
  updated_by   String
  creator      User         @relation("creator", fields: [created_by], references: [email])
  updater      User         @relation("updater", fields: [updated_by], references: [email])
}
```
I then run `prisma generate` to generate Prisma Client.
It generates a client succesfully
Then when I write code typescripts prompts me to add created_by and updated_by for the create functions of prisma.project and prisma.table even is I have already added the connection objects as such
```js
await prisma.project.create({
  data: {
    creator: {
      connect: {
        email: req.user.email
     },
    created_by: ...       // Typescript errors force me to add this as well even though I have a connetion object above
  },
}
```

But the code runs after I add the line but when executing the statement it gives the error
```
Invalid `prisma.project.create()` invocation in
..\\project\\index.ts: xxx : xx
...
const project = await prisma.project.create(
Null constraint violation on the (not available)
```

The error does not suggest anything related to or which might suggest the actual issue (of having same relation names)

## Expected behavior

I expected an exception that could either guide me faster towards the fact that my relations had same names so it can not identify the relation
OR
It would be best if the formatter does not allow having same relation names in the `prisma.schema`

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.18.0           | 
| OS              | windows            |
| Prisma Client   | 4.3.1              |
| Query Engine    | c875e43600dfe042452e0b868f7a48b817b9640b|
| Database        | mysql              |

##

**Comment by SevInf** [comment]
@PriyavKaneria unfortunately, I can not reproduce this issue: neither on 4.3.1, nor on more recent versions. This is the code I am using:

```ts
async function main() {
  const prisma = new PrismaClient()

  const email = 'mail@example.com'

  await prisma.user.create({
    data: { email },
  })
  await prisma.project.create({
    data: {
      creator: {
        connect: {
          email,
        },
      },
      updater: {
        connect: { email },
      },
    },
  })
}
```

with the schema you've provided. For me, it doesn't produce TS errors you are mentioning and works correctly when executing. Could you share a reproduction repo where we would see it happen? Also, if it is possible, could you try more recent prisma version? There have been quite a lot of fixes since `4.3.1`

**Comment by PriyavKaneria** [comment]
Oh sure I'll test it out and share a reproduction repo and test out new versions
I'll update if the issue does or does not exist 😇 👍

**Comment by janpio** [comment]
Any updates @PriyavKaneria?

**Comment by PriyavKaneria** [comment]
I think I'm unable to reproduce this. I'll get back if I face it again.
Closing the issue for now
