### ISSUE TITLE
Migrate Dev CMD Issue

### ISSUE THREAD

**Issue by Gohary95** [prisma/prisma#16274]
Hi Prisma Team! The following command just crashed.

## Command

`migrate dev`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.18.1           | 
| Prisma CLI  | 4.5.0              | 
| Engine      | 0362da9eebca54d94c8ef5edd3b2e90af99ba452| 

## Error
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_renderer.rs:112:9] internal error: entered unreachable code

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by SevInf** [comment]
Hi @Gohary95!
Could you share the schema that causes it?

**Comment by Gohary95** [comment]
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions", "multiSchema"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  schemas  = ["new_products", "rider_management"]
}

model Driver {
  id                  Int                  @id @default(autoincrement())
  driverId            String               @map("driver_id")
  storeName           String               @map("store_id")
  name                String?              @db.VarChar(255)
  phone               String?              @db.VarChar(255)
  code                String?              @db.VarChar(255)
  isActive            Boolean?             @map("is_active")
  isEnabled           Boolean?             @map("is_enabled")
  vehicleType         String?              @map("vehicle_type")
  createdAt           DateTime?            @map("created_at")
  updatedAt           DateTime?            @map("updated_at")

  @@map(name: "driver")
  @@schema("new_products")
}

model Rider {
  id                  Int                   @id @default(autoincrement())
  name                String
  phone               String
  status              RiderStatus
  vehicleType         VehicleType           @map("vehicle_type")
  lastUpdatedBy       String                @map("last_updated_by")
  createdAt           DateTime              @map("created_at")
  updatedAt           DateTime              @map("updated_at")

  @@map(name: "rider")
  @@schema("rider_management")
}

enum RiderStatus {
  ONLINE              @map("online")
  OFFLINE             @map("offline")
}

enum VehicleType {
  BIKE                @map("bike")
  CYCLE               @map("cycle")
  CAR                 @map("car")
}

**Comment by Gohary95** [comment]
Any updates regarding this issue?

**Comment by tomhoule** [comment]
@Gohary95 this is because multiSchema is not implemented on MySQL. We'll improve the error message.
