### ISSUE TITLE
Test CockroachDB 22.2 in prisma/prisma and prisma/prisma-engines

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#16291]
Prompted by a notification about SCRAM authentication becoming the default (https://prisma-company.slack.com/files/USLACKBOT/F04AZJYMAHK/scram_password_authentication_is_now_the_default_in_cockroachdb).

> In the upcoming CockroachDB v22.2 release, [SCRAM](https://friends.cockroachlabs.com/MzUwLVFJTi04MjcAAAGIG9tSYuVkTLwzylaxbK3Nq7V-utnUQ1Xza3NmvJOYTEWVWImttZjMsv8jei0Mz_5Afwp84qs=) will become the default authentication protocol for CockroachDB.
> 
> SCRAM is the most secure password authentication we currently have to offer and has a number of benefits:
> 
> It prevents passwords from being sent in cleartext during authentication.
> It reduces the chance for server CPU(s) to be a bottleneck during a sudden increase in authentication attempts by offloading the encryption work to the client.
> For CockroachDB serverless customers, it reduces the number of request units (RU) consumed during the initial authentication to the database.
> 
> However, SCRAM authentication imposes additional computational load on your application servers, which need to compute the client proof for each authentication. Additional changes may be required to your application, such as limiting the number of connections in your application's connection pool or limiting the number of concurrent transactions that your client allows.
> 
> Prior to upgrading to 22.2, we recommend that you:
> 
> Test and adjust your workloads in batches when migrating to SCRAM authentication.
> Start by enabling SCRAM authentication in a testing environment, and test the performance of your client application against the types of workloads you expect it to handle in production before rolling the changes out to production.
> Limit the maximum number of connections in the client driver's connection pool.
> Limit the maximum number of concurrent transactions the client application can issue.
> For more information about this change, please refer to our [SCRAM documentation](https://friends.cockroachlabs.com/MzUwLVFJTi04MjcAAAGIG9tSYjR_RUskN9Yri9feoJvlgpa97sYiXu8mhzSYuJb8JP-2y3vkcjdGDm70P5xnxJcGWbk=).

**Comment by Jolg42** [comment]
Note: I asked on [Slack](https://prisma-company.slack.com/archives/C01CSQXTNJ3/p1669886236610179)

**Comment by Jolg42** [comment]
The release is coming soon (Dec 6th) we should try this soon.

**Comment by Jolg42** [comment]
22.2 is out and it has a launch page: https://www.cockroachlabs.com/22-2-launch/

**Comment by Jolg42** [comment]
Related issues mentioning 22.2
- https://github.com/prisma/prisma/issues/16909
- https://github.com/prisma/prisma/issues/17055

**Comment by tomhoule** [comment]
Dropping this.

**Comment by janpio** [comment]
First results via https://github.com/prisma/prisma-engines/pull/3707 + https://github.com/prisma/prisma-engines/actions/runs/4148391785/jobs/7176339714 in Introspection:
- float list defaults `0` are returned as `0.0` now
- sequence default now get a max value

**Comment by pimeys** [comment]
This needs still some tests for prisma/prisma after the engines tests are merged.

**Comment by Jolg42** [comment]
Note, we have a separate issue for 23.1: https://github.com/prisma/team-orm/issues/242
