### ISSUE TITLE
db error: ERROR: incorrect binary data format in bind parameter 3

### ISSUE THREAD

**Issue by muhammad-Osman** [prisma/prisma#16308]
### Bug description

i am trying to run the following quuery with date comparision and always getting this error

db error: ERROR: incorrect binary data format in bind parameter 3

and the query is 

const newToRoleResult: any = await prisma.$queryRaw`
        SELECT distinct on (p.id) p.id, count(*), p.start_date, a.grade, a.reviewed_at 
      FROM assessments a, people p WHERE (a.status = CAST('done' AS assessment_status) 
      AND a.reviewee_id = p.id AND 
      (p.institute_id = ${instituteId} 
        OR (p.institute_id in 
          (SELECT inst.id FROM institute inst WHERE inst.mat_id = ${instituteId}))))
          ${
            newToRole == "NTR"
              ? Prisma.sql`AND p.start_date => ${startDate} AND p.start_date =< ${endDate}` : Prisma.empty
          } 
          GROUP BY a.grade, p.id, a.reviewed_at ORDER BY p.id, a.reviewed_at DESC`;

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```const newToRoleResult: any = await prisma.$queryRaw`
        SELECT distinct on (p.id) p.id, count(*), p.start_date, a.grade, a.reviewed_at 
      FROM assessments a, people p WHERE (a.status = CAST('done' AS assessment_status) 
      AND a.reviewee_id = p.id AND 
      (p.institute_id = ${instituteId} 
        OR (p.institute_id in 
          (SELECT inst.id FROM institute inst WHERE inst.mat_id = ${instituteId}))))
          ${
            newToRole == "NTR"
              ? Prisma.sql`AND p.start_date => ${startDate} AND p.start_date =< ${endDate}` : Prisma.empty
          } 
          GROUP BY a.grade, p.id, a.reviewed_at ORDER BY p.id, a.reviewed_at DESC`;
```

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: v16.13.2

### Prisma Version
Prisma Version: 3.15.2

```

```

**Comment by janpio** [comment]
Internal Note: User also opened a discussion at https://github.com/prisma/prisma/discussions/16307 and commented on an old, related issue at https://github.com/prisma/prisma/issues/7194

**Comment by miguelff** [comment]
Asked for a schema file in the discussion.

**Comment by nurul3101** [comment]
Issue is resolved: https://github.com/prisma/prisma/discussions/16307#discussioncomment-4165858
