### ISSUE TITLE
Failed to download Prisma engines for darwin-arm64

### ISSUE THREAD

**Issue by johannchen2021** [prisma/prisma#16306]
### Bug description

> Downloading Prisma engines for Node-API for darwin-arm64 [====  ] 65%

it got stuck when I run `npx prisma -v`

### How to reproduce

 Run `npx prisma -v`

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS:  macOS 
- Database: SQLite 
- Node.js version: 18.11.0 

### Prisma Version

```
4.6.1
```

**Comment by johannchen2021** [comment]
After I downgraded prisma to 4.5.0, it does not show downloading prisma engines message. And it works as before. Did I do something wrong with updating primsa to the latest version?  (I ran `npm upgrade`)

**Comment by miguelff** [comment]
I haven't managed to reproduce the problem myself using the following `package.json`

```json
{
  "name": "hello-prisma",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^18.11.9",
    "prisma": "4.6.1",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.3"
  }
}
```

`npx prisma -v`

```sh
Environment variables loaded from .env
prisma                  : 4.6.1
@prisma/client          : Not found
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.6.1-3.694eea289a8462c80264df36757e4fdc129b1b32
Default Engines Hash    : 694eea289a8462c80264df36757e4fdc129b1b32
Studio                  : 0.476.0
```

I tried also downgrading and re-upgrading from 4.5.0 without problem.

Could have been a network glitch, or a downtime in the engines registry. Could you please try again?

**Comment by johannchen2021** [comment]
Thanks for the quick response. I tried again. Same problem happened while downing the prisma engines.  Here is the result this time (with different percentage)

 Downloading Prisma engines for Node-API for darwin-arm64 [========            ] 41%

It seemed that it started the download, but did not have enough time to finish the download. Not sure if my VPN get in the way for I need the VPN to reach npm.  Is there a workaround, i.e. manually download the prisma engines and put it somewhere in the node_module?

**Comment by jsdude0220** [comment]
> Thanks for the quick response. I tried again. Same problem happened while downing the prisma engines. Here is the result this time (with different percentage)
> 
> Downloading Prisma engines for Node-API for darwin-arm64 [======== ] 41%
> 
> It seemed that it started the download, but did not have enough time to finish the download. Not sure if my VPN get in the way for I need the VPN to reach npm. Is there a workaround, i.e. manually download the prisma engines and put it somewhere in the node_module?

Is there a solution to fix this issue? I got same issue as well.

**Comment by jsdude0220** [comment]
@GZLiew 
Could you please share me the download link which is working from your end?
Thanks in advance.

**Comment by GZLiew** [comment]
@jsdude0220 heres the link https://binaries.prisma.sh/all_commits/c875e43600dfe042452e0b868f7a48b817b9640b/darwin-arm64/prisma-fmt.gz.sha256

heres the full error output I got

```bash
> Downloading Prisma engines for Node-API for darwin-arm64 [] 0%Error: request to https://binaries.prisma.sh/all_commits/c875e43600dfe042452e0b868f7a48b817b9640b/darwin-arm64/prisma-fmt.gz.sha256 failed, reason: connect ETIMEDOUT 2001:d08:10:201:0:1:6356:b260:443

```

**Comment by jsdude0220** [comment]
Thanks for your sharing, I just tired to install on another pc and it seems to be worked.
Just still not sure why it is not downloading in my laptop.

**Comment by GZLiew** [comment]
@jsdude0220 just tried to downgrade my node to 16.18.1 and the download works now. Not sure it is the cause of a deprecated api from nodejs

**Comment by janpio** [comment]
This is all definitely a problem with your local connectivity, the URLs work fine globally. Check if your network is somehow blocking AWS, Cloudfront or similar.
