### ISSUE TITLE
Add tests for bundle sizes

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#1630]
Both the `prisma2` and `@prisma/client` packages should have tests, which check the bundle size to catch regressions in bundle size.

**Comment by Jolg42** [comment]
@timsuchanek Packagephobia has an API like this
`https://packagephobia.now.sh/api.json?p=prisma2@2.0.0-preview022`

For an offline version https://github.com/egoist/npm-size

**Comment by pantharshit00** [comment]
Yarn website uses the bundlephobia so I believe it should be reliable enough.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22195362/74935214-e4505780-540d-11ea-9d73-9763e35ea038.png">

**Comment by timsuchanek** [comment]
We can also measure `yarn pack`. We have a util function called `getPackedPackage` that we can use here.

**Comment by timsuchanek** [comment]
We now added [packwatch](https://github.com/mcataford/packwatch) to both packages. Please give them a star, they deserve it!
