### ISSUE TITLE
Query engine library for current platform "darwin" could not be found.

### ISSUE THREAD

**Issue by jhonadc** [prisma/prisma#16334]
Hi, I am getting an error when signing in using github oauth. It is really urgent, since this will be evaluated tomorrow.

The error is --

```
You already added the platforms "darwin", "darwin" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new Error: 
Invalid `p.session.findUnique()` invocation in
/Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/@next-auth/prisma-adapter/dist/index.js:24:52

  21     where: { provider_providerAccountId },
  22 }),
  23 async getSessionAndUser(sessionToken) {
→ 24     const userAndSession = await p.session.findUnique(
Query engine library for current platform "darwin" could not be found.
You incorrectly pinned it to darwin

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/@prisma/client/runtime/libquery_engine-darwin.dylib.node")

Searched Locations:

  /Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/.prisma/client
  /Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/@prisma/client
  /Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/@prisma/client
  /Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/.prisma/client
  /Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/prisma
  /tmp/prisma-engines
  /Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/.prisma/client

You already added the platforms "darwin", "darwin" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new
    at RequestHandler.handleRequestError (/Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/@prisma/client/runtime/index.js:34316:13)
    at /Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/@prisma/client/runtime/index.js:34737:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PrismaClient._executeRequest (/Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/@prisma/client/runtime/index.js:35301:22)
    at async PrismaClient._request (/Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/@prisma/client/runtime/index.js:35273:16)
    at async getSessionAndUser (/Users/jhonathanaugusto/Documents/CODE_UNIVERSITY/nextjs-familyt/node_modules/@next-auth/prisma-adapter/dist/index.js:24:36) {
  name: 'GetUserByAccountError',
  code: undefined
```

dependencies:

`"dependencies": {
    "@headlessui/react": "^1.6.6",
    "@heroicons/react": "^1.0.6",
    "@next-auth/prisma-adapter": "^1.0.5",
    "@prisma/client": "^4.1.0",
    "@radix-ui/react-icons": "^1.1.1",
    "@radix-ui/react-slot": "^1.0.1",
    "axios": "^1.1.3",
    "cloudinary": "^1.32.0",
    "clsx": "^1.2.1",
    "formidable": "^2.0.1",
    "next": "12.2.2",
    "next-auth": "^4.16.4",
    "postgres": "^3.3.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.36.1",
    "react-hot-toast": "^2.4.0",
    "react-icons": "^4.4.0",
    "typescript": "^4.7.4",
    "webpack": "^5.74.0"
  },
  "devDependencies": {
    "@swc/cli": "^0.1.57",
    "@swc/core": "^1.3.17",
    "@tailwindcss/forms": "^0.5.2",
    "@types/node": "^18.0.6",
    "@types/react": "^18.0.15",
    "autoprefixer": "^10.4.7",
    "cypress": "^11.0.1",
    "eslint": "8.20.0",
    "eslint-config-next": "12.2.2",
    "next": "12.2.2",
    "postcss": "^8.4.14",
    "prisma": "^4.6.1",
    "prisma-dbml-generator": "^0.9.1",
    "start-server-and-test": "^1.14.0",
    "tailwindcss": "^3.1.6"
  }
}
`

**Comment by miguelff** [comment]
There's not enough information to reproduce your bug. If this is code cloned from a remote repository, could you please ensure the instructions for running the particular project and ensure you are trying to [install prisma](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/mongodb/install-prisma-client-typescript-mongodb#install-and-generate-prisma-client) correctly?

**Comment by janpio** [comment]
What does your schema look like?
Where and how are you deploying or trying to run your app?

**Comment by christopherpickering** [comment]
This happens to me very frenquently - I remove my node_modules and npm install again to fix.

It seems to have started when I am working on several nextjs projects that use prisma and changing from running one project to running the other. For example, if I work project A in the morning and project B in the afternoon I need to remove node_modules and reinstall. 

In adition to the message above, I get this is the message 

```bash
- info Using wasm build of next-swc
- warn Attempted to load @next/swc-darwin-x64, but it was not installed
```

**Comment by janpio** [comment]
Can you please open a new issue @christopherpickering and provide the information standalone there? This sounds super weird, and definitely worth being investigated on its own. Thanks!

**Comment by christopherpickering** [comment]
Yeah, I can't get it to reproduce, next time it pops up I will try. Thanks!
