### ISSUE TITLE
May add a method `prisma.$executeParam(params: Params)` ? 

### ISSUE THREAD

**Issue by maslow** [prisma/prisma#16339]
## Problem

Just like `prisma.$executeRaw() for raw SQL` but for `Params`. 

The `Params` is prisma internal protocol struct which used in `prisma.$use(params, next)`. 

## Suggested solution

Add a method like this:

`async function prisma.$executeParams（params: Params);`

Returns what `next()` returns.

**Comment by maslow** [comment]
I  want implement  a  client sdk which can run in browser environment,  called "client-db sdk". 
The client-db sdk could build `prisma params` in any client (web, flutter, android, ios etc.) .

- prisma-client-ts
- prisma-client-flutter
- prisma-client-java

Then the client sdk could request with these `params`  to a server, called `prisma-proxy-server`. 
And use `prisma client for node` in `prisma proxy-server`  to `executeParam(params)` these params to prisma engines.

I want to add  a suite of `Client-database Policy`, to validate the `client database request` to ensure the security. 
(May like the firebase / supabase). 

Alternatively, maybe it doesn't have to be so troublesome, does prisma query engines support calling these params requests through http/tcp directly?

**Comment by janpio** [comment]
Prisma Client queries can pretty simply be expressed as JSON payloads, which can be for example be used as POST payloads for a HTTP based API. You still have to map that to the actual Prisma Client queries to be executed, but that should not be a big problem.

(Middlewares, which `Params` is used for, are deprecated and we will not invest any further into them.)
