### ISSUE TITLE
Error in migration engine. Reason: entered unreachable code 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#16340]
Command: `prisma db push`
Version: `4.6.1`
Binary Version: `694eea289a8462c80264df36757e4fdc129b1b32`
Report: https://prisma-errors.netlify.app/report/14435 
OS: `x64 win32 10.0.22000`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine\connectors\sql-migration-connector\src\sql_renderer\mysql_renderer.rs:521:97] internal error: entered unreachable code
```

Rust Stacktrace:
```
Starting migration engine RPC server
The migration was not applied because it triggered warnings and the force flag was not passed.
[migration-engine\connectors\sql-migration-connector\src\sql_renderer\mysql_renderer.rs:521:97] internal error: entered unreachable code
```

**Comment by pimeys** [comment]
- `relationMode: "prisma"`
- Latest `main`
- Push the data model in the error two times
- unreachable code

**Comment by pimeys** [comment]
Simplified data model that makes this bug to happen:

```prisma
model Class {
  id    Int      @id
  when  DateTime @default(dbgenerated()) @db.Time
}
```

Push this two times, the second one panics.
