### ISSUE TITLE
Better error message when our binaries do not support the OS they are running on

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1635]
When you are using an Alpine based docker image (e.g. `image: node:10-alpine`) you get this error message right now:

```
$ npx prisma2 generate
Error: Error: Command failed with ENOENT: /builds/myorg/myproj/node_modules/prisma2/query-engine-debian-openssl-1.1.x cli --dmmf
spawn /builds/myorg/myproj/node_modules/prisma2/query-engine-debian-openssl-1.1.x ENOENT
ERROR: Job failed: exit code 1
```

(via https://prisma.slack.com/archives/CKQTGR6T0/p1582043358493500)

We know we do not support Alpine (https://github.com/prisma/prisma2/issues/702). Can we provide a more helpful error message here?

(Another example of user reaction: https://github.com/prisma/prisma2/issues/899#issuecomment-551594015)

**Comment by esistgut** [comment]
Side (useless?) info: this is from a GitLab CI job.

**Comment by pantharshit00** [comment]
Related: https://github.com/prisma/prisma-client-js/issues/466

Maybe even a duplicate?

**Comment by janpio** [comment]
I would say this is one of the specific cases that should get their own error message there.

**Comment by harole** [comment]
@janpio Same problem. Have you fixed this issue? I will appreciate it if you could share the approach.

**Comment by janpio** [comment]
If you are getting this error message in an unexpected way (Alpine not working is expected, see https://github.com/prisma/prisma2/issues/702) please open a new issue and describe the whole problem. Thanks.

**Comment by Jolg42** [comment]
It works! 
<img width="508" alt="Screen Shot 2020-04-15 at 11 48 50" src="https://user-images.githubusercontent.com/1328733/79323904-1ca47b80-7f0f-11ea-8994-6d8762cfc500.png">
