### ISSUE TITLE
No way to catch error in `findUniqueOrThrow` via middleware

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#16354]
> Also their is no way to catch and massage the error (to change its message for example). 
> 
> With `findUniqueOrThrow`, in a middleware `result` is `null` and `params.action` is `findUnique`:
> 
> ```typescript
> prismaClient.$use(async (params, next) => {
>   try {
>     const result = await next(params);
>     return result;
>   } catch (error) {
>     // nothing to see here
>     throw error;
>   }
> });
> ```
> 
> With `rejectOnNotFound`, the un-exported error (treatable with `error.constructor.name === 'NotFoundError'` btw) was thrown inside.

_Originally posted by @bbenezech in https://github.com/prisma/prisma/issues/14209#issuecomment-1180183113_

**Comment by janpio** [comment]
> @bbenezech this sounds like a separate issue for me, is that right? If that's the case, could you please open a separate GitHub issue for this to avoid any confusion, and, most importantly, avoid your report being lost, since the issue @PatrikValkovic refers to has already been fixed, and someone might close it without looking at your comment.

_Originally posted by @aqrln in https://github.com/prisma/prisma/issues/14209#issuecomment-1183075537_

**Comment by miguelff** [comment]
Tracked in #16226
