### ISSUE TITLE
createMany returns a count and not the objects created like create does

### ISSUE THREAD

**Issue by rmzg-ll** [prisma/prisma#16362]
### Bug description

If you use `createMany` to insert multiple rows you can't return the values inserted (specifically the autogenerated IDs)

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by dbrxnds** [comment]
This isn't a bug. 

See: https://www.prisma.io/docs/concepts/components/prisma-client/crud#create-multiple-records

**Comment by soulninja-dev** [comment]
classic example of this is a feature not a bug

**Comment by Ludovicmanga** [comment]
You can now use createManyAndReturn to get the created records
