### ISSUE TITLE
DigitalOcean Postgres + PGBouncer Issues

### ISSUE THREAD

**Issue by Linktheoriginal** [prisma/prisma#1638]
Broken out from prisma2/#556 on request from @janpio .

Similar to specs/#386 and prisma2/#1438, we have been attempting to use Prisma2 against a Digital Ocean PostgreSQL 11 database service.

Operating without pgbouncer, the application initially runs fine, but eventually runs out of connections. When this happens, the query engine also seems to spin and use all available CPU.

Since this seems to be a connection release/starvation issue, we added pgbouncer in front of Postgres.  Digital Ocean offers pgbouncer-based pools with transaction, session, and statement settings. With a transactional pool in place, we receive errors with prepared statements, e.g. "prepared statement 's1599' does not exist."

We've also tested a session pool but it still ran out of connections eventually.

We are using the &connection_limit=15 argument in our connection string (without pgbouncer), but are still seeing the issue.  We're currently using preview21, and planning to update to preview22 shortly. We're hoping that using the flag discussed in specs/#386 plus a transactional pool will solve the issue against a Digital Ocean provided pgbouncer/postgres.

We're also exploring moving to mysql, but it's requiring additional work to get around some of the current limitations with how Prisma2 handles strings in mysql, along with some unrelated innodb issues.  Postgres is definitely our preferred technology for our project.

On recommendations from the Prisma team, we modified the client code to add the --always_force_transactions flag to the query engine invocation here: https://github.com/prisma/prisma-client-js/blob/7ee403f1b255e8506d92b675d53bf9a8b2bea097/packages/engine-core/src/NodeEngine.ts#L336

With this in place, the first query executed would work, but queries afterwards would fail with "Error in connector: Error creating a database connection."  I believe this is due to the Digital Ocean pgbouncer not having the settings mentioned here: https://github.com/prisma/prisma-engines/pull/403

Doing some research, it seems like these are uncommon settings, with pgbouncer defaulting them off and not recommending them.  This can be worked around, but might make it difficult for Prisma2 to work with some of the major providers: https://github.com/pgbouncer/pgbouncer/issues/110#issuecomment-182501545

I've worked on setting up a custom pgbouncer server in front of the Digital Ocean managed Postgres, but their SSL configuration looks like this may not be an option.

We're continuing to look for workarounds and configuration changes to get this working.

**Comment by janpio** [comment]
We can confirm this problem with DigitalOcean's PgBouncer (Connection Pool) feature as it unfortunately does not allow setting any configuration on PgBouncer. We are looking into finding a workaround that matches Prisma's connection behavior.

**Comment by MaxAst** [comment]
Hi @janpio, have you guys made any progress on this? If not, I'd look into migrating my database from Digital Ocean to AWS unless, of course, you guys are about to release a fix

**Comment by Linktheoriginal** [comment]
For anyone finding this, the connection leaks mentioned here ended up being a separate issue.  We corrected it and dropped pgbouncer from our configuration.

I didn't get this working, but I did spend a little time working on manually setting up a pgbouncer server in front of the DO postgres, which would have allowed me to configure the settings as recommended.  Not sure if that is any easier than switching services if you're able.

@MaxAst I think they're looking at other options in issue #2453

**Comment by MaxAst** [comment]
okay cool, thank you @Linktheoriginal!

**Comment by janpio** [comment]
We will probably soon release an updated pgBouncer mode: https://github.com/prisma/prisma/issues/2520. Will update this issue here as well when that happened.

(You can probably right now use `forceTransactions:true` in the PrismaClient constructor without the custom configuration and have a working setup in 99% of the cases - but these last 1% is what we can unfortunately only fix with this new release for DO's Connection Pool feature)

**Comment by janpio** [comment]
https://github.com/prisma/prisma/issues/2520 is now closed, we implemented a `?pgbouncer=true` query param for the connection string that you can use to enable PgBouncer mode.

Available in alpha now, and in the next beta soon.

**Comment by kanchangpr** [comment]
I have created PostgreSQL 12 database cluster in digital ocean, and using connection pool. in my java code Application.properties i have configured database properties as below:

`spring.datasource.url=jdbc:postgresql://private-db-postgresql-*********-*********.b.db.ondigitalocean.com:25061/*********?pgbouncer=true

spring.datasource.username=*********

spring.datasource.password=*********

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=*********`

when i am trying to run the application getting below error:

> Caused by: org.postgresql.util.PSQLException: ERROR: prepared statement "S_3" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:857) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:900) ~[postgresql-42.2.16.jar:42.2.16]
	at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:396) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java) ~[HikariCP-3.4.5.jar:na]
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:121) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	... 27 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: prepared statement "S_1" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114) ~[postgresql-42.2.16.jar:42.2.16]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.4.5.jar:na]

**Comment by janpio** [comment]
Please open a new issue @kanchangpr and fill the issue template - then we can take a look at the details and try to help you.

**Comment by kanchangpr** [comment]
> Please open a new issue @kanchangpr and fill the issue template - then we can take a look at the details and try to help you.

created new issue #4735. thanks for your response.

**Comment by muditgoel01** [comment]
Besides adding `&pgbouncer=true` also make sure that:

If you have created a new database user, make sure you have assigned proper permissions to it. 

Docs: https://www.digitalocean.com/docs/databases/postgresql/how-to/modify-user-privileges/
Video: https://youtu.be/tsOHw2T1HvI?t=596

But even after that, although DB connection pooling is working properly in most cases, it just does not work with **nextauth** (https://next-auth.js.org). I am getting various kinds of errors when I try to login using Google (via next-auth): 

- Callback error
- OAuthAccountNotLinked
- 504 Gateway Timeout
- Redirect back to login page, without logging in user.

It is working absolutely fine:

- locally
- without connection pool (on Digital Ocean Managed DB and Heroku)
- with & without connection pool (AWS, Digital Ocean Droplet)

**Comment by janpio** [comment]
Can you open a new issue about the problems you are experiencing please @muditgoel01? I see no way how this could really be connected to using PgBouncer, but we are happy to look into that (optimally with a small reproduction repository).
