### ISSUE TITLE
Prisma's Decimal is incompatible with decimal.js

### ISSUE THREAD

**Issue by lorenz-h** [prisma/prisma#16397]
### Bug description

Prisma client bundles decimal.js and exports the class Decimal. Unfortunately, that class cannot be used with the `Decimal` class imported directly from `decimal.js`, because both classes declare `toStringTag`.

Example:

```ts
import { Decimal } from "decimal.js"
import { Prisma } from "@prisma/client"

const test = new Decimal(new Prisma.Decimal("12.0"))
// FYI: const test2 = new Prisma.Decimal(new Decimal("12.0")) also gives a type error

```

Gives the following error 

> Argument of type 'Decimal' is not assignable to parameter of type 'Value'.
  Type 'import("****/node_modules/@prisma/client/runtime/index").Decimal' is not assignable to type 'import("***/node_modules/decimal.js/decimal").default'.
    Types have separate declarations of a private property 'toStringTag'.

### How to reproduce

1. Install decimal.js 10.4.2 and @prisma/client 4.6.1.
2. The following gives a type error in typescript (tested with 4.8.4): 

```ts
import { Decimal } from "decimal.js"
import { Prisma } from "@prisma/client"

const test = new Decimal(new Prisma.Decimal(12.0))
// FYI: const test2 = new Prisma.Decimal(new Decimal("12.0")) also gives a type error

```

### Expected behavior

The Decimals from Prisma and decimal.js should be compatible.

This issue is particularly painful when working with mathjs (which depends on decimal.js). The `BigNumber` type from mathjs (which is just reexported `Decimal` from `decimal.js`, is also incompatible with the Prisma's `Decimal`

### Environment & setup

- OS:  macOS Ventura
- Database: PostgreSQL
- Node.js version: 16.14

### Prisma information
```prisma
model Order {
  id     Int          @id @default(autoincrement())
  amount    Decimal
}
```

### Prisma Version

```
prisma                  : 4.6.1
@prisma/client          : 4.6.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 694eea289a8462c80264df36757e4fdc129b1b32 (at ../../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 694eea289a8462c80264df36757e4fdc129b1b32 (at ../../node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 694eea289a8462c80264df36757e4fdc129b1b32 (at ../../node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 694eea289a8462c80264df36757e4fdc129b1b32 (at ../../node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.6.1-3.694eea289a8462c80264df36757e4fdc129b1b32
Default Engines Hash    : 694eea289a8462c80264df36757e4fdc129b1b32
Studio                  : 0.476.0
Preview Features        : interactiveTransactions, metrics
```

**Comment by jon-ressio** [comment]
I'm running into this same issue.  My setup is a nextjs app, prisma -> trpc -> superjson -> react.

I'm registering a custom converter for Decimals with superjson and have added a Decimal.js package dependency (10.4.2 and 10.4.1 behave the same)

I initially tried using Decimal from my React components as:

`import { Decimal } from "@prisma/client/runtime";`

but the prisma client/runtime package seems to reference the 'fs' package so I get this error in the browser:

`Module not found: Can't resolve 'fs'`

It would be nice if the Decimal.js bundled with Prisma could be exported cleanly (from "@prisma/client/model" or whatever makes sense) so it can be imported from browser-side code.  Alternatively, if Decimal.js removes `toStringTag` from their typescript declaration then this problem goes away.

**Comment by jon-ressio** [comment]
I tested this out, created a quick PR to decimal.js linked above.  I've verified once I updated my direct dependency of Decimal.js and rebuild prisma with that new version, that I can mix and match `Decimal` instances and TypeScript is happy.

**Comment by lorenz-h** [comment]
> I'm running into this same issue. My setup is a nextjs app, prisma -> trpc -> superjson -> react.
> 
> I'm registering a custom converter for Decimals with superjson and have added a Decimal.js package dependency (10.4.2 and 10.4.1 behave the same)
> 
> I initially tried using Decimal from my React components as:
> 
> `import { Decimal } from "@prisma/client/runtime";`
> 
> but the prisma client/runtime package seems to reference the 'fs' package so I get this error in the browser:
> 
> `Module not found: Can't resolve 'fs'`
> 
> It would be nice if the Decimal.js bundled with Prisma could be exported cleanly (from "@prisma/client/model" or whatever makes sense) so it can be imported from browser-side code. Alternatively, if Decimal.js removes `toStringTag` from their typescript declaration then this problem goes away.

@jon-ressio thanks for putting together the PR  - Regarding your (I believe unrelated) import issue. Have you considered importing Decimal using:
``` ts
import { Prisma } from "@prisma/client"

const d: Prisma.Decimal = new Prisma.Decimal(12)

```

**Comment by jon-ressio** [comment]
> Regarding your (I believe unrelated) import issue. Have you considered importing Decimal using:

Thanks a lot for that!  That resolves my issue of importing Prisma's Decimal class from the browser.  I think I'm going to remove our explicit import for Decimal.js and just use it from Prisma.

I'll keep an eye on my PR though, it feels like it would be nice for any projects where they have multiple Decimal imports.

**Comment by jon-ressio** [comment]
Decimal.js 10.4.3 includes the PR removing toStringTag from the typescript type definition.  If Prisma can update their Decimal.js dependency and you can update the direct Decimal.js dependency, that should resolve this issue.

**Comment by bappy004** [comment]
hopefully the decimal.js version dependency will be upgraded soon to 10.4.3 by prisma team. I am also getting the error regarding the `private readonly toStringTag` issue in a reduxjs-reactjs project.

**Comment by Jolg42** [comment]
The version got updated a while ago now (since Prisma 4.10.0), and I can't reproduce in latest version
PR that updated the version to `10.4.3` https://github.com/prisma/prisma/pull/16290

**Comment by 127** [comment]
Looks like this bug is actual again at 6 versions

**Comment by vladinator1000** [comment]
I have this use-case where I want to use the same function both on server and browser. I had to install  `"decimal.js": "^10.5.0"` because I don't want to bundle Prisma for the browser.

When I try mixing `Prisma.Decimal` and `Decimal` to do multiplication (e.g. initial number comes from database) and then if I pass that number to a function that uses `Decimal` like this

```ts
function calculateSplit(net: Decimal, percentage: Decimal) {
  return percentage.div(100).mul(net) // one of these numbers comes from Prisma.Decimal, the other from Decimal
}
```


I get this error:
```
Error: [DecimalError] Invalid argument: 0
```

I'm on Prisma `v6.6.0`. I need this to be able to have consistent calculations on the server and on the client.

Is anyone also facing this issue?
