### ISSUE TITLE
fieldReference of "prisma": "^4.6.0" not working with "prisma-nestjs-graphql": "^14.6.0" in nestjs project

### ISSUE THREAD

**Issue by bozlurrahman** [prisma/prisma#16427]
i am using simple nestjs project. My schema.prisma file as follow:

> generator client {
>   provider        = "prisma-client-js"
>   previewFeatures = ["filteredRelationCount","fieldReference"]
>   binaryTargets   = ["debian-openssl-1.1.x", "rhel-openssl-1.0.x", "rhel-openssl-1.1.x", "native"]
> }
> 
> generator nestgraphql {
>   provider = "node node_modules/prisma-nestjs-graphql"
>   output   = "../src/@generated"
> }
> 
> datasource db {
>   provider = "mongodb"
>   url      = env("DB_URL")
> }
> 
> model User {
>   id          String   @id @default(auto()) @map("_id") @db.ObjectId
>   name        String  @default("")
>   email       String  @unique
>   device_id   String   @unique
>   enabled     Boolean  @default(true)
>   created_at  DateTime @default(now())
>   updated_at  DateTime @default(now())
> 
>   @@map("users")
> }

during run "npx prisma generate", I have got the following error:

> Prisma schema loaded from prisma/schema.prisma
> Error: 
> ✔ Generated Prisma Client (4.6.1 | library) to ./node_modules/@prisma/client in 72ms
> 
> ✔ Generated Prisma Joi Generator to ./src/@generated/joi-schemas in 567ms
> 
> TypeError: Cannot get matching input type from String, StringFieldRefInput
>     at getGraphqlInputType (/home/bozlur/quran-translation-web/node_modules/prisma-nestjs-graphql/index.js:551:9)
>     at AwaitEventEmitter.inputType (/home/bozlur/quran-translation-web/node_modules/prisma-nestjs-graphql/index.js:684:30)
>     at AwaitEventEmitter.<anonymous> (/home/bozlur/quran-translation-web/node_modules/await-event-emitter/lib/index.js:115:39)
>     at Generator.next (<anonymous>)
>     at /home/bozlur/quran-translation-web/node_modules/await-event-emitter/lib/index.js:12:71
>     at new Promise (<anonymous>)
>     at __awaiter (/home/bozlur/quran-translation-web/node_modules/await-event-emitter/lib/index.js:8:12)
>     at AwaitEventEmitter.emit (/home/bozlur/quran-translation-web/node_modules/await-event-emitter/lib/index.js:108:16)
>     at generate (/home/bozlur/quran-translation-web/node_modules/prisma-nestjs-graphql/index.js:2031:24)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by SevInf** [comment]
Hi @bozlurrahman!
Thank you for the bug report. `prisma-nestjs-graphql` is a third party package and not maintained by Prisma. Stacktrace you provided points to the problem in that package. Please, report this issue to `prisma-nestjs-graphql` maintainers [here](https://github.com/unlight/prisma-nestjs-graphql).

**Comment by bozlurrahman** [comment]
Hi,
Thanks for your reply,
i have reported there and they resolved it.
