### ISSUE TITLE
Using linuxbrew OpenSSL results in an error

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#16420]
Taken from https://github.com/prisma/prisma/discussions/14356#discussioncomment-4075604

> @vladi-stevanovic for anyone else who finds this discussion I was encountering the same issue when running `npx prism db pull`
I'm running Ubuntu 22.04 with Node 18.12 LTS installed via NVM. I noticed that my OpenSSL version was also 1.1.1q installed by Linuxbrew. 
Unlinking the Linuxbrew version so that the system version of OpenSSL (3.0.2) is used resolved the issue for me and I have been able to run the pull successfully.
```
brew unlink openssl@1.1
```
> In my case I had installed 1.1 trying to get a local MongoDB installation working on Ubuntu 22.04 unsuccessfully. Ended up using Atlas.

**Comment by pantharshit00** [comment]
https://github.com/prisma/prisma/discussions/14356#discussioncomment-4080136

> Can you describe a bit further how we could get our system into the same situation? We would like to be able to reproduce this and then hopefully find a better solution.

**Comment by pantharshit00** [comment]
https://github.com/prisma/prisma/discussions/14356#discussioncomment-4081116

> @jobyh thank you so much - been stuck with the same issue for weeks. I have no idea why I would have a duplicate (and outdated) version installed via homebrew, but gave it a last ditch attempt any way and sure enough it worked!

**Comment by pantharshit00** [comment]
https://github.com/prisma/prisma/discussions/14356#discussioncomment-4084681

> @John-Dennehy You’re welcome, I’m really pleased it has helped you too! Hoping it doesn’t break any other Homebrew packages which may have installed 1.1 as a dependency. Still, as you say, better not to be using the outdated version.

> Can you describe a bit further how we could get our system into the same situation? We would like to be able to reproduce this and then hopefully find a better solution.

>@janpio Yes, of course. In the context of Ubuntu 22.04 (LTS):

> Ensure OpenSSL toolkit is installed sudo apt-get install openssl
Check system OpenSSL is v3 openssl version
Install [Homebrew](https://brew.sh/)
Install NVM via Homebrew brew install nvm
Install Node LTS via NVM nvm install —lts
Install legacy OpenSSL via Homebrew brew install openssl@1.1
Check legacy OpenSSL is now being used openssl version
The above should recreate the system state into which I created a Next.js app and added Prisma which errored on npx prisma db pull. If you need detailed steps am happy to provide them.

> I don’t think Prisma is doing anything really wrong because the cause is an outdated version of OpenSSL overriding the system version for that user. The problem is very frustrating from a DX perspective as it's not clear what action to take based on the error message so I appreciate you wanting to look for an improvement 🙂

**Comment by pantharshit00** [comment]
https://github.com/prisma/prisma/discussions/14356#discussioncomment-4085894

> I did a reproduction on GitHub Actions Ubuntu 22.04 here https://github.com/prisma/ecosystem-tests/pull/3204
Though the error is different
```
[...]
Query engine library for current platform "debian-openssl-3.0.x" could not be found.
You incorrectly pinned it to debian-openssl-3.0.x
[...]
```

**Comment by pantharshit00** [comment]
https://github.com/prisma/prisma/discussions/14356#discussioncomment-4086099

> @Jolg42 I wonder if the difference in error message could be related to the fact that Homebrew overrides for a specific user on the system (not all users)? Is the action running the command which triggers the error as a different user than the one whos path includes Homebrew?

**Comment by aqrln** [comment]
This issue is reproducible with Prisma up to 4.8.1. Starting with Prisma 4.9.0, OpenSSL installed via Anaconda, Homebrew etc doesn't interfere with system OpenSSL library detection. I'm going to go ahead and close this issue.
