### ISSUE TITLE
prisma format does not work correctly

### ISSUE THREAD

**Issue by davidizac** [prisma/prisma#16449]
### Bug description

`prisma format` adds relations in the wrong model

### How to reproduce

Before saving
![Screen Shot 2022-11-24 at 11 15 43 PM](https://user-images.githubusercontent.com/34278628/203864265-93486807-edbb-4699-bc83-6818eb27de7d.png)
After Saving
![Screen Shot 2022-11-24 at 11 15 51 PM](https://user-images.githubusercontent.com/34278628/203864287-6b7c3249-6e74-4075-acc9-0ab774b4e291.png)

### Expected behavior

It suppose to be
![Screen Shot 2022-11-24 at 11 16 08 PM](https://user-images.githubusercontent.com/34278628/203864305-e17a32cf-7483-4657-91e4-dc0d226461e3.png)

### Prisma information

prisma                  : 4.6.1
@prisma/client          : Not found
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.6.1-3.694eea289a8462c80264df36757e4fdc129b1b32
Default Engines Hash    : 694eea289a8462c80264df36757e4fdc129b1b32
Studio                  : 0.476.0

### Environment & setup

- OS: macOS
- Database:PostgreSQL
- Node.js version: v16.14.2

### Prisma Version

```
4.6.1
```

**Comment by janpio** [comment]
How do you think `format` should know that you want the relation in the model, where currently no information about the relation is present?

**Comment by davidizac** [comment]
@janpio I understand what you are saying but at least, dont format in the wrong way....

**Comment by tomhoule** [comment]
Both ways are equally valid (or wrong), if I understand the situation right. You specified one side of the relation. There is not enough information for format to say whether this is the "forward" side (the model with the scalar field and the foreign key) or the "back" side (the other). `format` picks the first choice. In a sense, it is a bit more justified because if you specify only one side, `format` assumes it's the most significant/important side.

**Comment by davidizac** [comment]
@tomhoule how can you say that both are equally valid ? The "wrong" format created an array type 
I am agree that they are 2 choices when it comes to apply a 1 - 1 relation, in both of them, we dont create an array type.
I would expect (at least) to get something like `user User` in the `Profile` model.

**Comment by janpio** [comment]
Similar question then: How should Prisma know if you want to do a 1:1 or a 1:n relation? We seem to have made the decision that a 1:n is more probable and default to that.
