### ISSUE TITLE
multiSchema + introspection: add `--schemas` param to the `db pull` command

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#16455]
Currently, the only way to specify the array of namespaces to introspect is in the datasource block inside a Prisma schema.

This would be required for full support of multiSchema with `db pull --url`.

**Comment by jkomyno** [comment]
Note: the new `--schemas` param (which refers to the database schemas supported by the `multiSchema` preview feature) is incredibly similar to the currently existing `--schema` param (which refers to the location of a custom `prisma` schema).

How about we introduce a new `--multi-schemas` param instead of `--schemas`?

**Comment by jkomyno** [comment]
What should happen when the given Prisma schema already contains some database schemas? I think we should inform the user by printing a warning with the following templated message:

```typescript
`Introspecting with database schemas ${MULTISCHEMAS_FROM_CLI}, which override the database schemas defined in your Prisma schema: ${MULTISCHEMAS_FROM_PRISMA_SCHEMA}`.
```

Example when running `prisma db pull --multi-schemas public,something` with the following Prisma schema:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["multiSchema"]
}

datasource db {
  provider = "postgresql"
  url      = env("TEST_POSTGRES_URI")
  schemas  = ["base", "transactional"]
}
```

We should see the following warning:

```
Introspecting with database schemas `public`, `something`, which override the database schemas defined in your Prisma schema: `base`, `transactional`.
```

**Comment by jkomyno** [comment]
Docs note: we can pass multiple schemas to the `db pull` command in two ways:

1. Using commas without a space: `prisma db pull --multi-schemas public,something`
2. Using repetitions of the `--multi-schemas` param: `prisma db pull --multi-schemas public --multi-schemas something`

Both examples are equivalent to `const multiSchemas = ["public", "something"]`

**Comment by janpio** [comment]
> How about we introduce a new `--multi-schemas` param instead of `--schemas`?

No way to avoid that, unfortunately as "schema" just means multiple things in our space. We prefer to stay consistent in the naming - which means this should be `schemas`.

> What should happen when the given Prisma schema already contains some database schemas? I think we should inform the user by printing a warning with the following templated message [...]

Right now this can just override the existing values. Outputting a warning might be helpful, but should be handled as an additonal feature and not make the existing request more complex.

**Comment by jkomyno** [comment]
Closed via https://github.com/prisma/prisma/pull/17034.
