### ISSUE TITLE
multi-schema + introspection: rename models and enums to avoid name collisions

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#16454]
## Problem

When multiple enums/tables share a name, but are in different database schemas, we do _not_ apply any renaming logic in introspection, leading to name collisions. The reasoning is that users will fix them after introspection, and re-introspection will keep the new names.

The problem with that reasoning is that disambiguating can get complicated, since we produce models/enums with exactly the same name in the Prisma schema, meaning that **users need knowledge of the database schema that isn't expressed in the introspected schema in order to make the introspected schema correct**.

## Example

The following postgres catalog:

```sql
CREATE SCHEMA "first";
CREATE TYPE "first"."HappyMood" AS ENUM ('happy');
CREATE TABLE "first"."HappyPerson" (mood "first"."HappyMood" PRIMARY KEY);
CREATE SCHEMA "second";
CREATE TYPE "second"."HappyMood" AS ENUM ('veryHappy');
CREATE TABLE "second"."VeryHappyPerson" (mood "second"."HappyMood" PRIMARY KEY);
CREATE TABLE "second"."HappyPerson" (mood "first"."HappyMood" PRIMARY KEY);

```

introspects to the following schema:

```prisma
        generator client {
          provider        = "prisma-client-js"
          previewFeatures = ["multiSchema"]
        }
        datasource db {
          provider = "postgresql"
          url      = "env(TEST_DATABASE_URL)"
          schemas  = ["first", "second"]
        }
        model HappyPerson {
          mood HappyMood @id
          @@schema("first")
        }
        model HappyPerson {
          mood HappyMood @id
          @@schema("second")
        }
        model VeryHappyPerson {
          mood HappyMood @id
          @@schema("second")
        }
        enum HappyMood {
          happy
          @@schema("first")
        }
        enum HappyMood {
          veryHappy
          @@schema("second")
        }
```

**Comment by eviefp** [comment]
Would it be possible to detect name collisions and generate `@@map` attributes for those?

**Comment by ozkankirik** [comment]
+1
