### ISSUE TITLE
prisma-upgrade decline install

### ISSUE THREAD

**Issue by Druue** [prisma/prisma#16497]
## Problem
Running `npx prisma-upgrade` currently only provides `(y)` as an option when needing to install packages. This could be improved by allowing a user to back out with an `n`.

![image](https://user-images.githubusercontent.com/29753584/204295007-d0a5604b-d89e-49f3-bbe1-c0fccf8e9db1.png)

## Suggested solution
`Ok to proceed? (y/N)` -- The default can be noted by the letter being capitalised.

**Comment by janpio** [comment]
This is not Prisma UX, but `npx` that ships with Npm. Nothing we can do about that unfortunately.
