### ISSUE TITLE
`&sslcert=server-ca.pem` in PostgreSQL connection url throw `Error opening a TLS connection: One or more parameters passed to a function were not valid.`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#1651]
I created a PostgreSQL instance on Google Cloud

I followed https://github.com/prisma/prisma2/blob/master/docs/core/connectors/postgresql.md#configuring-an-ssl-connection created the .p12 with a password from the certificates downloaded from the Google project
`openssl pkcs12 -export -out client-identity.p12 -inkey client-key.pem -in client-cert.pem`

my `prisma/.env`
```
DATABASE_URL="postgresql://postgres:GDp1zlwDdrOm4GtM@35.184.106.230:5432/mydb?schema=public&sslmode=require&sslidentity=client-identity.p12&sslpassword=mysecurepass3728508&sslcert=server-ca.pem"
```

When doing `prisma2 introspect`

```
Error: P1011
Error opening a TLS connection: One or more parameters passed to a function were not valid.
```

When removing `&sslcert=server-ca.pem` it works without sslcert even with sslmode=require

**Comment by Jolg42** [comment]
Sidenote: The error could be more specific to help with which parameter(s) were not valid maybe?

**Comment by tomhoule** [comment]
I didn't manage to reproduce this exact error, it could be OSX specific. I'll keep investigating.

**Comment by tomhoule** [comment]
@Jolg42 I'm still not able to reproduce this :/ Do you think it is still happening?

**Comment by Jolg42** [comment]
I will try again soon then @tomhoule :)

**Comment by pachiraDIG** [comment]
This may be related to postgres user roles/privileges. I had an 'empty database' error that was fixed by adding privileges using GRANT, which you can find in the docs. I hope its the same issue you're facing.

**Comment by Jolg42** [comment]
So in the docs some values are missing, is it because they are not supported or that the documentation need to be updated?

In current Prisma doc
<img width="306" alt="Screen Shot 2020-05-19 at 18 24 49" src="https://user-images.githubusercontent.com/1328733/82352293-0ef68000-99fe-11ea-823c-13e777a77ef8.png">
https://www.prisma.io/docs/reference/database-connectors/postgresql#configuring-an-ssl-connection

In Postgres doc
<img width="89" alt="Screen Shot 2020-05-19 at 18 25 27" src="https://user-images.githubusercontent.com/1328733/82352387-2df51200-99fe-11ea-966b-df499ee18007.png">
See https://jdbc.postgresql.org/documentation/head/ssl-client.html

**Comment by Jolg42** [comment]
It looks like it works 🎊 

Example
DATABASE_URL="postgresql://postgres:password@4.71.20.10:5432/mydb?schema=public&sslmode=require&sslidentity=../client-identity.p12&sslpassword=dummypass&sslcert=../server-ca.pem"
