### ISSUE TITLE
Foreign key constraint not being created with @relation - mysql

### ISSUE THREAD

**Issue by VitorTheGreat** [prisma/prisma#16521]
### Bug description

Hello everyone!

I am totally new to prisma. I've searched but did not find an issue related to mine. I am creating a simple ROLE and USER tables but when pushing the DB or creating the migration, prisma is not creating the FK constraint reference. I just don't get any errors, the database is created successfully, just missing the FK constraint references. I followed the documentation step by step, but I just don't know if I am missing something or if this is really a bug.

### How to reproduce

1. Running "npx prisma db push" I got the following results in mysql DB

![mysql_result](https://user-images.githubusercontent.com/11010539/204502421-8521782b-f005-4cdd-842c-142eb601ee1d.PNG)

2. If I try running the migration, I got the following:
```
CREATE TABLE `Roles` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `role` VARCHAR(20) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Users` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(300) NOT NULL,
    `roleId` INTEGER NOT NULL,
    `status` BOOLEAN NOT NULL,

    UNIQUE INDEX `Users_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

### Expected behavior

I expected the prisma migration ou push to create this relation for me, something like:

`CONSTRAINT `fk_key` FOREIGN KEY (role_id`) REFERENCES `roles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE`

Or an Alter Table to create this FK for me.

### Prisma information

schema.prisma
```prisma
datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL_LOCAL")
  referentialIntegrity = "prisma"
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

model Roles {
  id    Int     @id @default(autoincrement())
  role  String  @db.VarChar(20)
  Users Users[]
}

model Users {
  id        Int      @id @default(autoincrement())
  uuid      String   @default(uuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name      String   @db.VarChar(255)
  email     String   @unique @db.VarChar(255)
  password  String   @db.VarChar(300)
  role      Roles    @relation(fields: [roleId], references: [id])
  roleId    Int      @db.Int
  status    Boolean  @db.TinyInt
}
```

prisma.client
```ts
import { PrismaClient } from '@prisma/client'

declare global {
    // allow global `var` declarations
    // eslint-disable-next-line no-var
    var prisma: PrismaClient | any
}

const prisma = global.prisma || new PrismaClient({ log: ['query'], errorFormat: 'pretty', })

// const prisma = global.prisma || new PrismaClient();

if (process.env.NODE_ENV !== 'production') global.prisma = prisma

export default prisma
```

### Environment & setup

- OS: Windows 10
- Database: MySQL
- Node.js version: v16.15.1

### Prisma Version

```
prisma : 4.6.0  
@prisma/client : 4.6.0  
Current platform : windows
Studio: 0.476.0
Preview Features: referentialIntegrity

```

**Comment by janpio** [comment]
You are using `referentialIntegrity = "prisma"` (which can be renamed to `relationMode = "prisma"` by the way!). The benefit of this feature is that Prisma can do relations on database without foreign keys: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/relation-mode By enabling this feature you are telling Prisma to _not_ use foreign keys. When you remove it, the next migration should create the necessary foreign keys.

**Comment by VitorTheGreat** [comment]
Hello @janpio!

Thank you very much for the answer and explanation! I'll give it a try, I apologize for the simple question as well, I'll pay more attention to the documentation from now on too!

**Comment by janpio** [comment]
Oh, missing something like that is totally expected - don't worry. Asking about it here was the right and obvious thing to do, and we are happy to help.

Please come back if it does not work.
