### ISSUE TITLE
Get rid of deprecated and redundant warnings in `getDmmf` 

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#16538]
discovered in https://github.com/prisma/prisma/pull/16501#issuecomment-1330739089

**Comment by jkomyno** [comment]
I've discussed about this issue with @millsp.
- [x] We won't be changing outdated warnings in `BinaryEngine.ts`, as basically no external user relies on the binary anyway
- [x] I've already removed outdated warnings in `getDmmf.ts` during the Wasm-ification process

We can thus close this issue.

**Comment by jkomyno** [comment]
Follow-up discussion on [Slack](https://prisma-company.slack.com/archives/C02A1646TBR/p1676546064139569).
