### ISSUE TITLE
Regression in relation field name deduplication

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#16547]
### Bug description

If a relation field would be named in a similar manner as a scalar field in the model, we used to deduplicate it and generate a name that hopefully would not clash with the scalar field in 4.6.0. In version 4.7.0 this feature was removed.

In version 4.6.0 we did:

```prisma
model A {
  id   Int @id
  b    Int
  aToB B   @relation(fields: [b], references: [id])
}

model B {
  id Int @id
  as A[]
}
```

And in version 4.7.0 we do:

```prisma
model A {
  id Int @id
  b  Int
  b  B   @relation(fields: [b], references: [id])
}

model B {
  id Int @id
  as A[]
}
```

As we can see, in the latter the relation and scalar field are named as `b`, leading to a validation error.

The PR in culprit that changed the behavior: https://github.com/prisma/prisma-engines/pull/3381

**Comment by tomhoule** [comment]
Implementation-wise, we can add this to relation_names.rs as an extra condition in which we consider the relation as ambiguous.

**Comment by pimeys** [comment]
I'm gathering the names of scalar fields in `IntrospectionMap` now...
