### ISSUE TITLE
Support OpenSSL 3.0 for Alpine Linux

### ISSUE THREAD

**Issue by carlocorradini** [prisma/prisma#16553]
`OpenSSL 3.0` is currently the default `OpenSSL` version in `Alpine Linux 3.17` (see [CHANGELOG](https://alpinelinux.org/posts/Alpine-3.17.0-released.html)).
For `Alpine Linux`, `Prisma` only supports `OpenSSL 1.X` at this time.
As a result, the following error is generated:
```sh
Error: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
Details: Unable to require(`OMITTED/node_modules/prisma/libquery_engine-linux-musl.so.node`)
 Error loading shared library libssl.so.1.1: No such file or directory (needed by OMITTED/node_modules/prisma/libquery_engine-linux-musl.so.node)
[Context: getDmmf]
```
## Suggested solution

Add `OpenSSL 3.0` support to `Alpine Linux`

## Workaround
Install `openssl1.1-compat`:
```sh
apk add openssl1.1-compat
```
Note that this is only a temporary fix until the `Prisma` team adds support for OpenSSL 3.0.

**Comment by rene-demonsters** [comment]
Running into the same issue here. Our gitlab-ci started failing because the docker:latest base image got updated to Alpine 3.17.

**Comment by rene-demonsters** [comment]
I probably need to swap out `docker:latest` for `docker:20.10.21-dind-alpine3.16` or `docker:20.10.21-alpine3.16`. Currently trying the former. Will update this message once I've figured it out but this might help people already in the mean time.

Tags from: https://hub.docker.com/_/docker/tags?page=1&name=alpine3.16

**Comment by carlocorradini** [comment]
Workaround, install `openssl1.1-compat`
```sh
apk add openssl1.1-compat
```

**Comment by claudiowilson** [comment]
Running into this as well!

**Comment by CooperBills** [comment]
We're hitting this as well. The official docker node image just bumped all their alpine images to Alpine v3.17 a few hours ago, which bundles OpenSSL 3.0 instead of 1.1

**Comment by solarisn** [comment]
> We're hitting this as well. The official docker node image just bumped all their alpine images to Alpine v3.17 a few hours ago, which bundles OpenSSL 3.0 instead of 1.1

Same issue here. This broke our CI today and took some time to track down. Now that the Alpine version of the official docker node image uses Alpine v3.17 (as of today) I think a lot of people are going to start running into this issue.

**Comment by tkuye** [comment]
Just ran into this as well.

**Comment by carlocorradini** [comment]
What I feared... 😅

**Comment by Martinsos** [comment]
Same here, some extra information for context:

```
Error: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
Details: Unable to require(`/app/server/node_modules/prisma/libquery_engine-linux-musl.so.node`)
 Error loading shared library libssl.so.1.1: No such file or directory (needed by /app/server/node_modules/prisma/libquery_engine-linux-musl.so.node)
[Context: getConfig]

Prisma CLI Version : 4.5.0
```

```
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
```

```
node:18-alpine
```

**Comment by dgreen-ledger** [comment]
Hit the same problem also today

**Comment by nilennoct** [comment]
Use `FROM node:XX-alpine3.16` to temporarily fix.

**Comment by Suniron** [comment]
Use `apk add openssl1.1-compat` In the **Dockerfile** or the **CI steps** fix the problem for me

**Comment by screamcha** [comment]
> Use apk add openssl1.1-compat In the Dockerfile or the CI steps fix the problem for me
This unfortunately didn't help, prisma performed migrations but threw error on attempt to call `prisma.$queryRaw(...)`. Binding alpine version to 3.16 fixed the issue for me.

**Comment by aqrln** [comment]
@screamcha 

> This unfortunately didn't help, prisma performed migrations but threw error on attempt to call prisma.$queryRaw(...). Binding alpine version to 3.16 fixed the issue for me.

Did you get the same error as in the original post when running `prisma.$queryRaw` after installing `openssl1.1-compat` or a different error?

**Comment by aqrln** [comment]
@screamcha also, which database are you using?

**Comment by bobbylkchao** [comment]
By adding `RUN apk add --update --no-cache openssl1.1-compat` to docker file, it works to us. Thanks @carlocorradini  👍 

prisma: `4.1.1`
@prisma/client: `4.1.1`
Docker image we are using: `FROM marketplace.gcr.io/google/centos7:latest`
Database: `postgresql`
Prisma configurations:
```
generator client {
  provider      = "prisma-client-js"
  output        = "client"
  binaryTargets = ["native", "linux-musl"]
}
datasource db {
  provider = "postgresql"
  url      = env("xx")
}
```

**Comment by jkomyno** [comment]
Hey everyone, Alberto from Prisma here.

Prisma currently needs OpenSSL 1.1.x being installed as a system library on Linux Alpine.
For many of you, Prisma suddenly stopped working when run on the `node:alpine` / `node:lts-alpine` Docker images. This is because these images are now based on `alpine:3.17` (which comes with OpenSSL 3.0.x) rather than `alpine:3.16` (which comes with OpenSSL 1.1.x).

You currently have two alternatives:

- Use a Node.js Docker image based on Alpine 3.16, like `node:alpine3.16`, `node:lts-alpine3.16`, `node:18.12.1-alpine3.16` (encouraged)

- Install OpenSSL 1.1.x via the `openssl1.1-compat` package, e.g., by adding
  ```Dockerfile
  RUN apk add --update --no-cache openssl1.1-compat
  ```
  to your Dockerfile before installing Prisma 

We're also working on a solution on our side to provide native compatibility with OpenSSL 3, which will close this issue altogether. We thank you for your patience.

About the original error listed at the top of this issue:

>
  ```
  Error: Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!
  Details: Unable to require(`OMITTED/node_modules/prisma/libquery_engine-linux-musl.so.node`)
   Error loading shared library libssl.so.1.1: No such file or directory (needed by OMITTED/node_modules/prisma/libquery_engine-linux-musl.so.node)
  [Context: getDmmf]
  ```

- The error `Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!` means that Prisma cannot interact with its own engines (which are compiled libraries or binaries compatible), most likely due to Prisma not being able to find OpenSSL on your system.
- The `Error loading shared library libssl.so.1.1`  error indeed shows that Prisma cannot find OpenSSL 1.1 in the system, which prevents commands like `prisma generate` and the Prisma Client from working as expected.

---

Here is a minimal `Dockerfile` example based on `node:alpine` you can use to run Prisma!

```Dockerfile
# Dockerfile for running Prisma on Linux Alpine 3.17+

# change with the Node.js version of your choice
ARG NODE_VERSION="18.12.1"

# change with the Linux Alpine version of your choice
ARG ALPINE_VERSION="3.17"

FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS base

# install OpenSSL 1.1.x, needed for Linux Alpine 3.17+
RUN apk update \
  && apk add openssl1.1-compat

ENV DATABASE_URL ""
WORKDIR /app

# install your project dependencies
COPY package.json ./
RUN npm i

# copy your project files and Prisma schema
COPY . ./

RUN npx prisma version
```

**Note**: we've noticed some comments in similar issues suggesting to install `libc` on Linux Alpine to fix the problem. Please **DON'T** do this, as it could cause other unexpected errors.

**Comment by mohamedelbalshy** [comment]
thanks  @jkomyno really appreciate your answer!

**Comment by aqrln** [comment]
Support for OpenSSL 3 in Alpine Linux will be released today (CET) in Prisma 4.8.0. Please let us know if you still run into any issues with 4.8.0!

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/releases/tag/4.8.0 is published on npm :shipit: 

Let us know if it solves your problems, if you still have a problem after upgrading create a new issue, we'll be interested to check that!

**Comment by EyadAlghamdi** [comment]
it worked perfectly for me,
but i had to add `linux-musl-openssl-3.0.x` to my binaryTargets to make it work.

**Comment by aqrln** [comment]
@EyadAlghamdi 
>  but i had to add linux-musl-openssl-3.0.x to my binaryTargets to make it work.

Do you generate the client on a different system before deploying it on Alpine?

**Comment by capaj** [comment]
@aqrln does that mean we can omit the openssl step like this in dockerfile now?

```dockerfile
# Dockerfile for running Prisma on Linux Alpine 3.17+

# change with the Node.js version of your choice
ARG NODE_VERSION="18.12.1"

# change with the Linux Alpine version of your choice
ARG ALPINE_VERSION="3.17"

FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS base

ENV DATABASE_URL ""
WORKDIR /app

# install your project dependencies
COPY package.json ./
RUN npm i

# copy your project files and Prisma schema
COPY . ./

RUN npx prisma version
```

**Comment by aqrln** [comment]
@capaj yes

**Comment by jkomyno** [comment]
@EyadAlghamdi could you please open a new issue posting your Prisma schema, describing the steps you took to run Prisma on your system, and why the `binaryTargets` attribute was needed?

**Comment by Geczy** [comment]
unfortunately still having this issue on macbook m1 and building on docker with node alpine @jkomyno 

https://github.com/dotabod/backend/blob/master/twitch-chat-listener/Dockerfile

https://github.com/dotabod/backend/blob/master/docker-compose.yml

https://github.com/dotabod/backend/blob/master/twitch-chat-listener/prisma/mongo.prisma


```js
 => CACHED [backend-web deps 2/7] RUN apk add yarn git python3 make g++                                                                          0.0s
 => CACHED [backend-web deps 3/7] WORKDIR /app                                                                                                   0.0s
 => CACHED [backend-twitch-chat-listener deps 4/7] COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./                            0.0s
 => [backend-twitch-chat-listener deps 5/7] COPY prisma ./prisma                                                                                 0.2s
 => CACHED [backend-web deps 4/7] COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./                                             0.0s
 => [backend-web deps 5/7] COPY prisma ./prisma                                                                                                  0.3s
 => ERROR [backend-twitch-chat-listener deps 6/7] RUN yarn --frozen-lockfile                                                                    20.2s
 => CANCELED [backend-web deps 6/7] RUN yarn --frozen-lockfile                                                                                  21.5s
------                                                                                                                                                
 > [backend-twitch-chat-listener deps 6/7] RUN yarn --frozen-lockfile:                                                                                
#0 0.449 yarn install v1.22.5                                                                                                                         
#0 0.536 [1/4] Resolving packages...                                                                                                                  
#0 0.725 [2/4] Fetching packages...                                                                                                                   
#0 10.11 info fsevents@2.3.2: The platform "linux" is incompatible with this module.                                                                  
#0 10.11 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.                              
#0 10.12 [3/4] Linking dependencies...                                                                                                                
#0 11.92 [4/4] Building fresh packages...                                                                                                             
#0 17.98 $ prisma generate --schema ./prisma/mongo.prisma && prisma generate --schema ./prisma/postgres.prisma                                        
#0 19.16 Prisma schema loaded from prisma/mongo.prisma                                                                                                
#0 19.43 Error: Unable to establish a connection to query-engine-node-api library. It seems that the current architecture arm64 is not supported, or that libc is missing from the system.
#0 19.43 Details: Unable to require(`/app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node`)
#0 19.43  Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node)
#0 19.43 [Context: getDmmf]
#0 19.43 
#0 19.43 Prisma CLI Version : 4.8.0
#0 19.49 error Command failed with exit code 1.
#0 19.49 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn --frozen-lockfile]: exit code: 1
error: Recipe `build` failed on line 27 with exit code 17
```

**Comment by aqrln** [comment]
@Geczy we only added support for OpenSSL 3.0 on x86_64 in 4.8.0, Alpine on ARM is still unfortunately not a platform we provide any binaries for yet.

**Comment by Geczy** [comment]
> @Geczy we only added support for OpenSSL 3.0 on x86_64 in 4.8.0, Alpine on ARM is still unfortunately not a platform we provide any binaries for yet. We only provide ARM64 binaries for Debian-based systems at this moment.

what do you recommend i do to solve this?

**Comment by aqrln** [comment]
@Geczy I left a comment in the issue: https://github.com/prisma/prisma/issues/16963#issuecomment-1361720478

**Comment by devdrqgon** [comment]
> Support for OpenSSL 3 in Alpine Linux for x86_64 will be released today (CET) in Prisma 4.8.0. Please let us know if you still run into any issues with 4.8.0!

Unfortunately still running in the same issu. I tried many node versions. I also tried `RUN apk add --update --no-cache openssl1.1-compat`

`Error: Unable to establish a connection to query-engine-node-api library. It seems that the current architecture arm64 is not supported, or that libc is missing from the system.
#9 1.651 Details: Unable to require(`/app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node`)
#9 1.651  Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node)
#9 1.651 [Context: getDmmf]
#9 1.651 
#9 1.651 Prisma CLI Version : 4.8.0`

**Comment by jkomyno** [comment]
Hey @devdrqgon, you're seeing that error because you're trying to run Prisma on Linux Alpine running on the `arm64` architecture. For Linux Alpine, only the `amd64` / `x86_64` architecture is supported natively.

You can still run Prisma by asking Docker to handle the architecture emulation for you, by running this command on your `arm64` system (which I guess is a macOS with M1/M2 CPU):

> `docker buildx build --load -f Dockerfile --platform=linux/amd64 .`

Please refer to [this comment](https://github.com/prisma/prisma/issues/8478#issuecomment-1355209706) for additional context.

**Comment by philaris** [comment]
https://github.com/prisma/prisma/issues/16553

**Comment by thewh1teagle** [comment]
> apk add openssl1.1-compat

```console
0.748 ERROR: unable to select packages:                                                                                                                                                                                                                                                                                                                                   
0.748   openssl1.1-compat (no such package):           
```
