### ISSUE TITLE
multiSchema: `migrate reset` only resets first schema

### ISSUE THREAD

**Issue by andyjy** [prisma/prisma#16561]
### Bug description

WIthout `multiSchema`, `migrate reset` drops all tables and starts from an empty schema.
With `multiSchema`, I observe it only "resets" the first schema in the list.

This causes subsequent resets to fail when migrations conflict with the end state of a secondary schema - e.g. you have a migration that renames a table in a schema that isn't the first schema.

### How to reproduce

```
previewFeatures = ["multiSchema"]

schemas  = ["first", "second"]

model Example {
  @@schema("second")
  ...
}
```

`migration.sql`:
```
ALTER TABLE "second"."Example" RENAME TO "NewName";
```

subsequent runs of `prisma migrate reset` fail with error `relation "NewName" already exists`

My impression is this issue is relatively straightforward (not yet implemented) - just let me know if a working reproduction is required.

### Prisma information

Prisma v4.7.0

### Environment & setup

- OS: macOs
- Database: PostgresQL
- Node.js version: 16

### Prisma Version

```
4.7.0
```

**Comment by tomhoule** [comment]
Related: https://github.com/prisma/prisma/issues/10043
