### ISSUE TITLE
Enum @map doesn't work in mongodb

### ISSUE THREAD

**Issue by kaminskypavel** [prisma/prisma#16616]
### Bug description

in mongodb driver the enums aren't transpiled into the correct casing

### How to reproduce

```
enum PlanNames {
  FREE     @map("free")
  SILVER   @map("silver")
  GOLD     @map("gold")
  PLATINUM @map("platinum")
}
```

this schema is transpiled into 

```
export const PlanNames: {
  FREE: 'FREE',
  SILVER: 'SILVER',
  GOLD: 'GOLD',
  PLATINUM: 'PLATINUM'
};
```

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: Win11
- Database: MongoDB
- Node.js version: v18.12.1

### Prisma Version

```
prisma                  : 4.7.1
@prisma/client          : 4.7.1
Current platform        : windows
```

**Comment by janpio** [comment]
Is the data stored as `free`, `silver`, `gold`, `platinum` in the MongoDB database?

**Comment by kaminskypavel** [comment]
> Is the data stored as `free`, `silver`, `gold`, `platinum` in the MongoDB database?

yes.

I didnt tried what happening if you `.create` but looking into `PrismaClient` it looks like it will be uppercased.
take a look in [typescript playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wAoBsCGyByOAtsKgFxwDeAUHHAGIBKAosxQOROvsA0tcAZQCSAGQBqzRh2HjJvfgHEA8iIAiHZWvl0MIgIIAVIfgCqAWQ67Dx8+2oBfANzVqoSLDgwAnmGBxseIQkqHAAvHAAFN6+EABm-rgExKQAlADaANbAXnGePsC5AUnBALoudG7Q8NF+RUoARgBWwAgwzACOAK44WACW3kLIYJ3w4TR0dMjJFEVBpPz21EA)


<img width="476" alt="image" src="https://user-images.githubusercontent.com/4253088/205589037-a37566cc-eef7-4d82-87cc-2538802bffef.png">

**Comment by janpio** [comment]
The Prisma schema defines that what is called `free` in the database should be known as `FREE` in the Client. If that is the case, `@map` does work as designed. I think your feedback is related to how the enum is handled in Prisma Client itself, where you expect not only `FREE` but also `free` to pop up in some way. Is that correct?

**Comment by janpio** [comment]
I think then you are asking for the same as https://github.com/prisma/prisma/issues/8446 and this issue can be closed?

**Comment by kaminskypavel** [comment]
yeah looks pretty similar.

as a workaround this is what I do :

- given that Platfrom is an enum
```
export type SiteKey = `${Platforms | Lowercase<keyof typeof Platforms>}-${string}`;
```
then force a type casting.

**Comment by daiho-nfq** [comment]
@kaminskypavel I have the same issue https://github.com/prisma/prisma/discussions/17062
