### ISSUE TITLE
[Introspection] Introspect `uuid_generate_v1()` and `uuid_v4()` as database level defaults

### ISSUE THREAD

**Issue by joshuaavalon** [prisma/prisma#1662]
Version: `2.0.0-preview022`

## Query
```sql
CREATE TABLE "public"."User" (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v1(),
  name VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);
```
## Excepted

```prisma
model User {
  email    String    @unique
  id       String    @id @default(uuid())
  name     String    @unique
  password String
}
```

## Result
```prisma
model User {
  email    String    @unique
  id       String    @id
  name     String    @unique
  password String
}
```

**Comment by janpio** [comment]
The problem here is that right now `@default(uuid())` is a Prisma level concept - the UUIDs are created by Prisma and written to the database by Prisma Client - and does not rely on the function.

Do you think this would still work to represent `DEFAULT uuid_generate_v1()`?

**Comment by do4gr** [comment]
On beta2 this is now introspected as

```prisma
model User {
  email    String @unique
  id       String @default(dbgenerated()) @id
  name     String @unique
  password String
}
```

The id is therefore optional in the input and if it is not provided the db will create the default value. At some point we will probably also display the function as `uuid()` but for now this should give the expected behaviour.

**Comment by pie6k** [comment]
I'm also interested in it. 

UUID also have special type in Postgres tables which makes sure that it's valid uuid. Currently it's just a string.

```prisma
model User {
  email    String @unique
  id       UUID @default(uuid_v4()) @id
  name     String @unique
}
```

Something like this would be useful. Also, UUID has various version, which can be very important, especially if someone with legacy data is migrating to prisma.

**Comment by mbrookson** [comment]
Second that. I use `uuid_v4()` in my database very frequently.

**Comment by tomhoule** [comment]
Candidating to confirm that this is now correctly represented.

**Comment by tomhoule** [comment]
They are now represented as `@default(dbgenerated("..."))`. Please open a new issue if that doesn't work for your use case.
