### ISSUE TITLE
`db pull` with `multiSchema` enabled and `schemas` defined, outputs `public` in CLI message anyway

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#16635]
```
PS C:\Users\Jan\Documents\throwaway\crossSchemaIntrospection\docker> npx prisma db pull    
Prisma schema loaded from prisma\schema.prisma
Environment variables loaded from .env
Datasource "db": PostgreSQL database "test1", schema "public" at "localhost:5438"

✔ Introspected 2 models and wrote them into prisma\schema.prisma in 1.46s

Run prisma generate to generate Prisma Clien ...
```

with this schema:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["multiSchema"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  schemas  = ["schema1", "schema2"]
}
```

(and a connection string that does not define the schema)

**Comment by tomhoule** [comment]
I don't know if we should consider this a bug, after reflection. The schema parameter from the URL / the default search path _is_ relevant, and that's what your SQL is going to apply to if you don't prefix anything with schemas. We should think about this carefully.

**Comment by janpio** [comment]
As `public` is not explicit, but `schema1` and `schema2` are, we at least need to surface those _as well_. 
Do we _actually_ introspect `public` even, so if there are tables, would those appear as models in the Prisma schema file?

**Comment by tomhoule** [comment]
> Do we actually introspect public even, so if there are tables, would those appear as models in the Prisma schema file?

No.

From an implementation perspective, this is not trivial because I don't think the CLI has the information it needs to print the right thing there.

**Comment by janpio** [comment]
Maybe it should not output any schema information for now then, and we need to figure out how `db pull` can properly represent what is being introspected.

**Comment by anle1991** [comment]
I have 2 schemas "public","commerce". When introspect, I actually just want to introspect on the commerce schema. When introspection is applied to the whole DB, I expect it should at least generate the right @@schema("commerce"). However, it always gens @@schema("public"). Is this an expected behavior? And is there anyway I can fix this currently?

**Comment by janpio** [comment]
Please open a new discussion instead of commenting on an old, close issue @anle1991. Thanks.
