### ISSUE TITLE
Prisma 4.7.0 and 4.7.1 relationMode throws Error code: P1012

### ISSUE THREAD

**Issue by jcohenho** [prisma/prisma#16641]
### Bug description

Following along with the release notes for [4.7.0](https://github.com/prisma/prisma/releases/tag/4.7.0), I tried to configure `relationMode` for a PlanetScale DB. After configuring the recommended lines in `schema.prisma` and running  `npx prisma generate` I get the following error:

```
Error: Prisma schema validation - (query-engine-node-api library)
Error code: P1012
error: Error validating datasource `db`: 
This option can only be set if the preview feature is enabled in a generator block.

Example:

generator client {
    provider = "prisma-client-js"
    previewFeatures = ["referentialIntegrity"]
}

  -->  schema.prisma:8
   | 
 7 |   url          = env("DATABASE_URL")
 8 |   relationMode = "prisma"
 9 | }
   | 

Validation Error Count: 1
[Context: getDmmf]

Prisma CLI Version : 4.7.1

```

Schema: 

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}
```

### How to reproduce

1. In `schema.prisma` remove `previewFeatures = ["referentialIntegrity"]` from the generator client block.
2. In datasource block, replace `referentialIntegrity = "prisma"` with `relationMode = "prisma"` 

Example schema after changes:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}
```

Run `npx prisma generate` and see the error. 

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}
```

### Environment & setup

- OS: macOS
- Database: PlanetScale
- Node.js version: v16.14.2

### Prisma Version

```
prisma                  : 4.7.1
@prisma/client          : 4.6.1
Current platform        : darwin-arm64
```

**Comment by ratasorin** [comment]
Any resolutions on this problem? I have issues with `relationMode` throwing errors as well!

**Comment by janpio** [comment]
For @jcohenho this was most probably a mismatch between versions of Prisma CLI and Prisma Client. When both are on 4.7.1 this should not happen.

**Comment by ratasorin** [comment]
This was the issue for me! Fixed it and everything works very smooth now! Thank you!

**Comment by jcohenho** [comment]
@ratasorin This was the issue for me as well, thank you!
