### ISSUE TITLE
Filtering on a model with a compound primary key giving weird SQL at the end

### ISSUE THREAD

**Issue by kingalione** [prisma/prisma#16747]
### Bug description

When filtering for specific models with a compound primary key Im getting a weird SQL and error:

When I do a filtering with this kind of where clause inside apollographql studio:

`query asd {
  projects(
    where: {
      CompressorCalculation: {
        some: {
          Compressor: {
            some: {
              CaseCompressor: { some: { CaseCompressorIndex: { gte: 0 } } }
            }
          }
        }
      }
    }
  ) {
    CompressorCalculation {
      Compressor {
        CaseCompressor {
          CaseCompressorIndex
        }
      }
    }
  }
}`

Im getting a SQL that starts with this:

`WITH [cte_0] AS (
    SELECT [t1].[OpportunityNumber],
        [t1].[Variant]
    FROM [machines].[CompressorCalculation] AS [t1]
        INNER JOIN [pm].[Compressor_en] AS [j1] ON (
            (
                [j1].[OpportunityNumber] = [t1].[OpportunityNumber]
                AND [j1].[Variant] = [t1].[Variant]
            )
        )
    WHERE (
            [j1].[OpportunityNumber] IN (
                SELECT [OpportunityNumber]
                FROM [cte_0]
                WHERE (
                        [Variant] = [j1].[Variant]
                        AND [Revision] = [j1].[Revision]
                    )
            )
            AND [t1].[OpportunityNumber] IS NOT NULL
            AND [t1].[Variant] IS NOT NULL
        )
),
[cte_0] AS (
    SELECT [t2].[OpportunityNumber],
        [t2].[Variant],
        [t2].[Revision]
    FROM [pm].[Compressor_en] AS [t2]
        INNER JOIN [machines].[Crankshaft] AS [j2] ON (([j2].[CrankshaftId] = [t2].[CrankshaftId]))
    WHERE (
            [j2].[CrankshaftId] LIKE @P1
            AND [t2].[OpportunityNumber] IS NOT NULL
            AND [t2].[Variant] IS NOT NULL
            AND [t2].[Revision] IS NOT NULL
        )
)
...
`

And a error like this:
`Recursive common table expression 'cte_0' does not contain a top-level UNION ALL operator.`

This happens only if the primary key is a compound key like in my case. 

The generated SQL also makes no real sense.

### Expected behavior

Prisma should generate a valid SQL and filter the data correctly

### Prisma information

```prisma
model Project {
  OpportunityNumber        String   @id(map: "PK_Project") @db.NVarChar(20)
  CompressorCalculation CompressorCalculation[]

  @@schema("machines")
}

model CompressorCalculation {
  OpportunityNumber String             @db.NVarChar(20)
  Variant           String             @db.NVarChar(10)

  Project    Project      @relation(fields: [OpportunityNumber], references: [OpportunityNumber], map: "FK_CompressorCalculation_Project")
  Compressor Compressor[]

  @@id([OpportunityNumber, Variant], map: "PK_CompressorCalculation")
  @@schema("machines")
}

model Compressor {
  id                                  String   @unique(map: "UQ_Compressor") @map("CompressorId") @db.UniqueIdentifier
  OpportunityNumber                   String   @db.NVarChar(20)
  Variant                             String   @db.NVarChar(10)
  Revision                            String   @db.NVarChar(10)
  
  CaseCompressor        CaseCompressor[]
  CompressorCalculation CompressorCalculation @relation(fields: [OpportunityNumber, Variant], references: [OpportunityNumber, Variant], onDelete: NoAction, onUpdate: NoAction, map: "FK_Compressor_CompressorCalculation")

  @@id([OpportunityNumber, Variant, Revision], map: "PK_Compressor")
  @@map("Compressor_en")
  @@schema("pm")
}

model CaseCompressor {
  id                                        String   @id(map: "PK_CaseCompressor") @map("CaseCompressorId") @db.UniqueIdentifier
  ParentCompressorId                        String   @db.UniqueIdentifier
  CaseCompressorIndex                       Int

  Compressor         Compressor          @relation(fields: [ParentCompressorId], references: [id], onDelete: Cascade, onUpdate: NoAction, map: "FK_CaseCompressor_Compressor")

  @@schema("machines")
}
```

### Environment & setup

- OS: Windows
- Database: SQL Server
- Node.js version: 18.12.1

### Prisma Version

```
"prisma": "4.7.1"
```

**Comment by kingalione** [comment]
> What does your Prisma Client query look like? The above `query asd` does not really look like Prisma Client query code.

Hi the corresponding prisma client query would look like this:

`const a = await pdbPrismaClient.project.findMany({
      take: 10,
      where: {
        CompressorCalculation: {
          some: {
            Compressor: {
              some: {
                CaseCompressor: { some: { CaseCompressorIndex: { gte: 0 } } }
              }
            }
          }
        }
      },
      select: {
        CompressorCalculation: {
          select: {
            Compressor: {
              select: {
                CaseCompressor: {
                  select: {
                    CaseCompressorIndex: true
                  }
                }
              }
            }
          }
        }
      }
    });`

**Comment by mcbethio** [comment]
I am trying to reproduce and I'm not quite there yet, but, I have noticed a broken link here that we probably need to fix.

An example error I hit
```
error: This schema is not defined in the datasource. Read more on `@@schema` at https://pris.ly/d/multi-schema
```

And then link https://pris.ly/d/multi-schema gives me a 404.

**Comment by mcbethio** [comment]
I've managed to reproduce this on 4.10.1 also.

**Comment by janpio** [comment]
Link should work now, fixed via https://github.com/prisma/pris.ly/pull/88 @mcbethio

**Comment by janpio** [comment]
I can confirm the problem with 4.7.1:
```
> node .\script.js
prisma:query WITH [cte_0] AS (SELECT [t1].[OpportunityNumber], [t1].[Variant] FROM [dbo].[CompressorCalculation] AS [t1] INNER JOIN [dbo].[Compressor_en] AS [j1] ON (([j1].[OpportunityNumber] = [t1].[OpportunityNumber] AND [j1].[Variant] = [t1].[Variant])) WHERE ([j1].[OpportunityNumber] IN (SELECT [OpportunityNumber] FROM [cte_0] WHERE ([Variant] = [j1].[Variant] AND [Revision] = [j1].[Revision])) AND [t1].[OpportunityNumber] IS NOT NULL AND [t1].[Variant] IS NOT NULL)), [cte_0] AS (SELECT [t2].[OpportunityNumber], [t2].[Variant], [t2].[Revision] FROM [dbo].[Compressor_en] AS [t2] INNER JOIN [dbo].[CaseCompressor] AS [j2] ON (([j2].[ParentCompressorId] = [t2].[CompressorId])) WHERE ([j2].[CaseCompressorIndex] >= @P1 AND [t2].[OpportunityNumber] IS NOT NULL AND [t2].[Variant] IS NOT NULL AND [t2].[Revision] IS NOT NULL)) SELECT [dbo].[Project].[OpportunityNumber] FROM [dbo].[Project] WHERE ([dbo].[Project].[OpportunityNumber]) IN (SELECT [t0].[OpportunityNumber] FROM [dbo].[Project] AS [t0] INNER JOIN [dbo].[CompressorCalculation] AS [j0] ON (([j0].[OpportunityNumber] = [t0].[OpportunityNumber])) WHERE ([j0].[OpportunityNumber] IN (SELECT [OpportunityNumber] FROM [cte_0] WHERE [Variant] = [j0].[Variant]) AND [t0].[OpportunityNumber] IS NOT NULL)) ORDER BY [dbo].[Project].[OpportunityNumber] ASC OFFSET @P2 ROWS FETCH NEXT @P3 ROWS ONLY
PrismaClientUnknownRequestError: 
Invalid `prisma.project.findMany()` invocation in
C:\Users\Jan\Documents\throwaway\19963\script.js:6:34

  3 const prisma = new PrismaClient({ log: ['query'] })
  4
  5 async function main() {
→ 6   const a = await prisma.project.findMany(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 252, state: 1, class: 16, message: "Recursive common table expression 'cte_0' does not contain a top-level UNION ALL operator.", server: "943cfde6df22", procedure: "", line: 1 }) })
    at RequestHandler.handleRequestError (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\index.js:34878:13)
    at RequestHandler.handleAndLogRequestError (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\index.js:34841:12)
    at RequestHandler.request (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\index.js:34836:12)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\index.js:35926:16)
    at async main (C:\Users\Jan\Documents\throwaway\19963\script.js:6:13) {
  clientVersion: '4.7.1',
  batchRequestIdx: undefined
}
```

With latest (5.14.0) though, the script succeeds:
```
```
