### ISSUE TITLE
Consider not abbreviating “Integer”

### ISSUE THREAD

**Issue by brandonweiss** [prisma/prisma#1675]
I just started trying Prisma and got to this code snippet in the Quickstart.

```
model Post {
  post_id    Int      @id @default(autoincrement())
  content    String?
  created_at DateTime @default(now())
  title      String
  author     User?
}
```

Why is “Integer” abbreviated to “Int”? I looked up the data types and it appears “Integer” is the only one that is abbreviated, which is unexpected/inconsistent.

If it’s too difficult to change it now to be consistent, could it be aliased so both “Int” and “Integer” work?

**Comment by macrozone** [comment]
its probably because in graphql the type is named `Int` and prisma1 used graphql language for the schema.

**Comment by brandonweiss** [comment]
@macrozone Oh, you’re right, I think I knew that and had forgotten. What a bizarre choice—I wonder if there was a good reason 🤔

This is sort of an interesting problem—on the one hand it totally makes sense to keep to the spec, but on the other hand, I’ve been using GraphQL for a not insignificant amount of time and I was confused by this. Also for many people Prisma might be their first experience with GraphQL 🤷🏼‍♂️ Aliasing it feels like a nice convenience for users but I can see the argument against it too.

**Comment by macrozone** [comment]
@brandonweiss in many languages its actually `int` ;- ) like in c. It's short and matches the short "float" as well, i am fine with it ;-)

**Comment by tomhoule** [comment]
That's not something we are considering right now.
