### ISSUE TITLE
binaries.prisma.sh not accessible via IPv6

### ISSUE THREAD

**Issue by ldpr** [prisma/prisma#16777]
> Example -> <https://dnschecker.org/#AAAA/binaries.prisma.sh>
> 
> Makes it unusable on IPv6 only machines.

_Originally posted by @ldpr in https://github.com/prisma/prisma/discussions/16763_

**Comment by ldpr** [comment]
cc @janpio @nurul3101

**Comment by janpio** [comment]
Can confirm this tool does not like this.

How does this show when using Prisma CLI and Client?

**Comment by janpio** [comment]
This should be fixed now (change is rolling out as I speak). Can you please confirm @ldpr? Thanks.

**Comment by ldpr** [comment]
> This should be fixed now (change is rolling out as I speak). Can you please confirm @ldpr? Thanks.

Works great @janpio thank you so much! 

Funny to think you guys had this super quick turnaround and we are _still_ waiting for oracle/mysql to make their `repo.mysql.com` available over IPv6 :)

All the best and thanks again!

**Comment by janpio** [comment]
Benefits of being a small company and working with AWS, where this was literally one missing entry in Route53, that did not point to a Cloudfront distribution :D
