### ISSUE TITLE
db pull adds redundant comment about ignored table

### ISSUE THREAD

**Issue by birgersp** [prisma/prisma#16796]
### Bug description

In my schema, one of the models has a `@@ignore` tag. When doing `db pull` the following comment is added on top of the model definition

```
/// The underlying table does not contain a valid unique identifier and can therefore currently not be handled by the Prisma Client.
```

If I do `db pull` again, another (identical) comment is added on top of the model, again.

In other words, after doing `db pull` three times, this is the result:

```
/// The underlying table does not contain a valid unique identifier and can therefore currently not be handled by the Prisma Client.
/// The underlying table does not contain a valid unique identifier and can therefore currently not be handled by the Prisma Client.
/// The underlying table does not contain a valid unique identifier and can therefore currently not be handled by the Prisma Client.
model MyTable {
    time        DateTime @db.Timestamptz(6)
    someColumn  String

    @@ignore
}
```

### How to reproduce

1. Create a table with "no valid unique identifier". E.g. in postgres `create table "SomeTable"(t timestamp);`
2. Run `prisma db pull` on the database
3. In the generated schema.prisma file, observe how the comment about "... table does not contain a valid unique identifier ..." appears on top of the model.
4. Run `prisma db pull` again
5. In the schema.prisma, observe how another (redundant) comment was added

### Expected behavior

The comment should not appear more than once per "model".

### Prisma information

(The issue is regarding the schema, no queries)

### Environment & setup

- OS: Linux Mint 20.3 Cinnamon
- Database: PostgreSQL (with timescale extension)
- Node.js version: v16.18.1

### Prisma Version

```
❯ npx prisma -v               
prisma                  : 4.7.1
@prisma/client          : 4.7.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.7.1-1.272861e07ab64f234d3ffc4094e32bd61775599c
Default Engines Hash    : 272861e07ab64f234d3ffc4094e32bd61775599c
Studio                  : 0.477.0
```

**Comment by birgersp** [comment]
Hmm, I actually can't reproduce the bug outside of my project. But it's definitely something added in 4.7.x. If I downgrade to 4.6.x then the comment is not added multiple times.

Issue could be removed I guess, perhaps someone else will run into it and give a better explanation about how to reproduce...

**Comment by janpio** [comment]
Anything special about the table/model this is happening for? 
Or its position in your file?
Have you looked at it with an editor that highlights unvisible characters like line endings? That might be interesting.

**Comment by rbourdon** [comment]
I'm also experiencing this since 4.7.x. Nothing special in the schema or models. Each db pull adds another comment to any ignored models.

**Comment by janpio** [comment]
Does this also happen when you create a new project and point it towards the same database, then run `db pull` a few times?

**Comment by birgersp** [comment]
> Does this also happen when you create a new project and point it towards the same database, then run `db pull` a few times?

Just tested. Yes, it does. Prisma 4.8.1.

**Comment by pimeys** [comment]
yup

**Comment by birgersp** [comment]
Still occuring for me, in prisma version 4.10.1

**Comment by janpio** [comment]
Then I would guess you have a partitioned table, and that this one is currently ignored in your schema (which it does not have to).

Can you help us reproduce this problem again?

**Comment by pimeys** [comment]
This is a new issue, introduced by the new feature. So when we reintrospect, we should not add the comment if the model is already in the PSL.

**Comment by birgersp** [comment]
> Then I would guess you have a partitioned table, and that this one is currently ignored in your schema (which it does not have to).
> 
> Can you help us reproduce this problem again?

FWIW my database has [timescaledb](https://www.timescale.com/).

The models I am getting the redundant info comment for, are "timescale hypertables".

The tables are created as with any psql table, and then I ran `SELECT create_hypertable('sometable', 'time');`.

**Comment by birgersp** [comment]
I figured since these issues may not be related, it warrants an issue of its own. See: https://github.com/prisma/prisma/issues/18103
