### ISSUE TITLE
[Cloudflare Workers] Error: Script startup exceeded CPU time limit.    [code: 10021]

### ISSUE THREAD

**Issue by proatwork** [prisma/prisma#16810]
### Bug description

When using the [guide](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers), wrangler2 (⛅️ wrangler 2.6.2) crashes with
```
notes: [
      {
        text: 'Error: Script startup exceeded CPU time limit.\n [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
```

### How to reproduce

 ⛅️ wrangler 2.6.2 
wrangler.toml
```
main = "src/index.ts"
compatibility_date = "2022-12-14"
account_id = ""
workers_dev = true
usage_model = "unbound"
```

src/index.ts
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient({
	datasources: {
		db: {
			url: 'prisma://[....]',
		},
	}
})

addEventListener('fetch', (event) => {
	return new Response('Hello world')
})
```

run `wrangler dev` or `wrangler publish`

### Expected behavior

No error :)

### Prisma information

not relevant

### Environment & setup

- OS: macOS
- Database: PostgreSQL with Data Proxy
- Node.js version: v16.17.0

### Prisma Version

```
prisma                  : 4.7.1
@prisma/client          : 4.7.1
Current platform        : darwin-arm64
```

**Comment by Jolg42** [comment]
Note: https://github.com/prisma/prisma/issues/85#issuecomment-986283068 looks like a similar issue from the past 

It looks like there is a limit of 200ms for the "Worker startup time"
>A Worker must be able to be parsed and execute its global scope (top-level code outside of any handlers) within 200 ms. Script size can impact startup because there’s more code to parse and evaluate. Avoiding expensive code in the global scope can keep startup efficient as well. You can request adjustments to limits that conflict with your project goals by contacting Cloudflare. To increase a limit, complete the [Limit Increase Request Form](https://forms.gle/ukpeZVLWLnKeixDu7).

https://developers.cloudflare.com/workers/platform/limits/#worker-startup-time

What's the output of `wrangler publish`?
Do you see something like this `Total Upload: x KiB / gzip: x KiB`? Could you share the numbers with us?

Do you know in which region the Worker is versus the region of the Data Proxy? It might be that it takes too long to connect to the Data Proxy. Also, you could check that your database and the Data Proxy are in the same region as well.

**Comment by proatwork** [comment]
Hello Joël, 
thanks for replying

publish output:
```Total Upload: 1314.53 KiB / gzip: 395.60 KiB
▲ [WARNING] Here are the 5 largest dependencies included in your script:

  - ../../node_modules/@prisma/client/runtime/edge.js - 410.19 KiB
  - ../../node_modules/.prisma/client/edge.js - 231.37 KiB
  - ../../node_modules/lodash/lodash.js - 217.55 KiB
  - ../../node_modules/luxon/src/datetime.js - 29.38 KiB
  - ../../node_modules/crypto-js/tripledes.js - 21.75 KiB
  If these are unnecessary, consider removing them



✘ [ERROR] A request to the Cloudflare API (/accounts/XXX/workers/scripts/api) failed.

  Error: Script startup exceeded CPU time limit.
   [code: 10021]

  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

My db and the prisma proxy are located in US-east and my worker (wrangler dev) is running in Eastern Europe, I believe

I will look into increasing the startup time, but that will incur additional costs

Thanks again
-Alex
