### ISSUE TITLE
`npx prisma init` can't download files (self-signed certificate)

### ISSUE THREAD

**Issue by mvictorl** [prisma/prisma#16840]
### Bug description

**Is there a simple and unambiguous instruction on what to do if the corporate gateway re-signs traffic?**

```
C:\Users\mvictorl\Documents\workspace\prisma>npx prisma init
> Downloading Prisma engines for Node-API for windows [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/272861e07ab64f234d3ffc4094e32bd61775599c/windows/query_engine.dll.node.sha256 failed, reason: write EPROTO B0090000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:922:
```

P.S. on another virtual machine helps `set NODE_TLS_REJECT_UNAUTHORIZED=0`,
but on another I can’t initiate Prisma in any way

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Windows 10
- Database:
- Node.js version: 18.12.1

### Prisma Version

```

```

**Comment by thomas-b-jackson** [comment]
fwiw I ran into this error as well on a WSL Ubuntu distro. to workaround I ran prisma init on a machine that was not subject to the corp gateway. i then zipped up the node_modules/@prisma/engines folder and unzipped it on the affected client.

**Comment by jkomyno** [comment]
Hi @mvictorl and @thomas-b-jackson, reproducing issues that only occur behind corporate gateways/proxies is particularly challenging as they are hard to reproduce, so we gently ask you for more information. 

For instance:
1. Which corporate gateway / proxy is your company using?
2. What steps do you do when you want to install Prisma for the first time in your systems?
3. What does your proxy do when Prisma pulls its binaries from https://binaries.prisma.sh/*?

Moreover, it's not clear to me whether setting `NODE_TLS_REJECT_UNAUTHORIZED=1` (which basically lets Node.js treat HTTPS connections as HTTP) fixes the issue at all.

Also, we're not even sure that re-signing traffic is even the problem, as we're simply pulling in some platform-aware binary files via plain Node.js APIs, which should be oblivious to the security of the transport protocol used for the download.

**Comment by jkomyno** [comment]
On a side note, we have recently changed the CDN we use for exposing the Prisma engines. Could you please both try again with `prisma@5.0.0`, and report back with the results? Thanks.

**Comment by janpio** [comment]
@mvictorl @thomas-b-jackson Did you see Alberto's questions? Having some more information would be really helpful here. Thanks.
