### ISSUE TITLE
Error 08S01 (1043) -> Bad Handshake. MySQL Connection with SSL certs

### ISSUE THREAD

**Issue by Xaohs** [prisma/prisma#16886]
### Bug description

Hi, I've been trying to set up SSL for my prisma connection but I'm getting a "Bad Handshake" error, even though on MySQL Workbench, tableplus... my connection works fine with certificates.
I've followed the guide on the prisma docs website [here](https://www.prisma.io/docs/concepts/database-connectors/mysql#configuring-an-ssl-connection). And placed both client-identity.p12 and rootca.cert inside my ./prisma folder. 
The connection string i'm using is:
`'mysql://user:password@ip:port/database?sslidentity=client-identity.p12&sslpassword=mypassword&sslcert=rootca.cart'`

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

Trying to connect to: MySQL Server V8.0.31 @ Ubuntu 22.04

### Prisma Version

```
prisma                  : 4.7.1
@prisma/client          : 4.7.1
```

**Comment by Jolg42** [comment]
This looks like the same issue as https://github.com/prisma/prisma/issues/14903

I tried to get a reproduction of this error, but so far could not.

One person reported the following workaround
- pin MySQL Server to v8.0.29

**Comment by Jolg42** [comment]
I did not reproduce with certificates but based on https://github.com/prisma/prisma/issues/14903 I think it's related

**Comment by shangzhipan** [comment]
@janpio Might be related to https://github.com/prisma/prisma/issues/14903 as well.

**Comment by Marcdj-02** [comment]
+1; Experiencing the same. Seems to be related to SQL v0.8.30.

**Comment by kapilvats** [comment]
I have encountered the same problem while using a MySQL database hosted on Azure. Is there any solution?

**Comment by Marcdj-02** [comment]
> I have encountered the same problem while using a MySQL database hosted on Azure. Is there any solution?

Reverting to an older version of SQL. (For azure managed plan this means creating an new database on v5.7) or configuring SSL properly?

**Comment by GuillaumeSarfati** [comment]
Same probleme here on Azure the database was in v 8.029 until this morning 9am when they upgrade it to 8.031 and now I am not able to connect anymore in production... the prisma team could watch this ?

**Comment by GuillaumeSarfati** [comment]
https://learn.microsoft.com/en-us/answers/questions/1179788/app-service-cannot-connect-to-database-error-08s01?page=1&orderby=Helpful#answers

**Comment by chris-simmons-9** [comment]
Anybody have any kind of workaround for this yet?

Microsoft automatically upgraded our mysql servers from 8.0.28 to 8.0.31 overnight and this took out all of our environments (including production).

**Comment by Marcdj-02** [comment]
> Anybody have any kind of workaround for this yet?
> 
> Microsoft automatically upgraded our mysql servers from 8.0.28 to 8.0.31 overnight and this took out all of our environments (including production).

Reverting to an older version of SQL. (For azure managed plan this means creating an new database on v5.7)

**Comment by AnimeAllstar** [comment]
Any news on the patch for this besides downgrading to MySQL v5.7? My azure production environment just crashed to Azure updating their MySQL server version. I can't connect to my azure MySQL server using prisma due to having to use `sslaccept=strict`.

**Comment by janpio** [comment]
This should now be fixed in our `dev` version which you can install via `npm install prisma@dev @prisma/client@dev`. Regenerate your Prisma Client and try again - and it should work. Woudl be very helpful if some of you could confirm this is indeed working now. Thanks!

**Comment by AnimeAllstar** [comment]
@janpio Works with Azure Database for MySQL.
