### ISSUE TITLE
I want short unique id. UUID, CUID are too long

### ISSUE THREAD

**Issue by Arc-Jung** [prisma/prisma#16914]
## Problem
- I make banner function in my project. Maximum number of banner is 10,000 or less. but cuid and uuid data type are too long.

## Suggested solution
- I want 10~12 byte of short unique id. Please make short unique id.

**Comment by janpio** [comment]
You can use any self-defined function that is available on your database in a default. 
Prisma offers the most common ones, uuid and cuid, but we will most probably not add support for others.

Does that answer your issue?

**Comment by Arc-Jung** [comment]
@janpio 

Could you please show me an example of self-defined  function?

**Comment by janpio** [comment]
One to create a `nanoid` with PostgreSQL: https://github.com/viascom/nanoid-postgres/blob/main/nanoid.sql

**Comment by Arc-Jung** [comment]
@janpio

Thank. I will make short uuid function.

**Comment by pimeys** [comment]
Done in https://github.com/prisma/prisma-engines/pull/3556
