### ISSUE TITLE
Support PlanetScale in Edge Client

### ISSUE THREAD

**Issue by davidthomasparks** [prisma/prisma#16926]
## Problem

Right now, the only way to use the Prisma Edge client (@prisma/client/edge) is by using the Data Proxy. I cannot use PlanetScale at the edge with Prisma at the moment. 

## Suggested solution

Support a PlanetScale mySQL connection string for the edge client

## Alternatives

I am forced to use Kysely Planetscale dialect to generate a typesafe client at the edge. I'd like to use Prisma, but this limitation is a huge blocker. 

## Additional context

It'd be nice to support PlanetScale at the edge and have a typesafe way to access a DB without having to use Kysely or other query builders. Prisma DX is unparalleled for schema and pushing schema updates, but I am forced to drop the helpful client at the edge in favor of other query builders.

**Comment by janpio** [comment]
You can totally use a Planetscale connection string with Data Proxy, and our Edge Client.
But you can not use the serverless driver from PlanetScale - which is a different way to talk to their database. Is that what you mean? If so, then this request is already tracked in https://github.com/prisma/prisma/issues/15265 and this issue can be closed.

**Comment by DavidTParks** [comment]
That issue describes what I need perfectly @janpio. I'd like to avoid having to use the Data Proxy if possible. So somehow landing support in the Prisma Edge Client to talk to the serverless driver directly would be ideal. 

We can go ahead and close.
