### ISSUE TITLE
Remove `prisma-fmt` formatter binary

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#16924]
We've been using the Wasm formatter for several releases already. It's time we stop downloading the `prisma-fmt` binary.
We should remove support for `prisma-fmt` for the same release that will get rid of `introspection-engine`.

**Comment by jkomyno** [comment]
Follow-up: stop publishing `prisma-fmt`

**Comment by Jolg42** [comment]
Note: 
https://packagephobia.com/result?p=prisma@4.9.0
12.4MB Publish Size
73.7MB Install Size
https://packagephobia.com/result?p=prisma@4.10.0-dev.2 (where this PR landed)
12.4MB Publish Size
69.3MB Install Size

So 4.4MB in this case (probably for linux here)
