### ISSUE TITLE
Incorrect file checksum comparison with previous rolled-back migration

### ISSUE THREAD

**Issue by yfyau** [prisma/prisma#16927]
### Bug description

When there is a rollback migration, the checksum seems to be compared to the oldest record in `_prisma_migrations`.

I think the root cause is that it's not filtering out failed migrations in
https://github.com/prisma/prisma-engines/blob/c1113c6285960eb54d71be971738abe600727268/migration-engine/core/src/commands/diagnose_migration_history.rs#L95-L97

### How to reproduce

1. Run `prisma migrate dev --create-only`
2. Modify the migration to cause it to fail
3. Run `prisma migrate dev`
4. Run `prisma migrate resolve --rolled-back`
5. Modify the migration to cause it to success
6. Run `prisma migrate dev`
7. Shows `The migration X was modified after it was applied.`

![Screen Shot 2022-12-20 at 1 06 33 PM](https://user-images.githubusercontent.com/37103700/208735799-dd27e007-16cc-44e6-86c6-b0b78ec47b44.png)

### Expected behavior

No error

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS 
- Database: PostgreSQL 
- Node.js version: v14.18.0 

### Prisma Version

```
prisma                  : 3.15.2
@prisma/client          : 3.15.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 461d6a05159055555eb7dfb337c9fb271cbd4d7e
Studio                  : 0.462.0
```

**Comment by jkomyno** [comment]
Hi, could you please share the Prisma schema and migrations folder with us, and try again with `prisma@4.8.0`?

**Comment by jkomyno** [comment]
Hi @yfyau, I will close this issue for now. Please leave a comment with your Prisma schema and migrations folder in case you'd like us to reproduce this issue. Also, please make sure you try using more recent Prisma versions, such as `4.16.2` and `5.0.0`. Thanks!
