### ISSUE TITLE
Types for Json when generating d.ts files.

### ISSUE THREAD

**Issue by ErdemGKSL** [prisma/prisma#16942]
## Problem (Requested Feature)

I want to get types in Json value of models while coding, because it is good to have types.

## Suggested solution

In `*.prisma` file syntax might be like this example: `jsonData Json<{ name: string }> @default("{}")`

**Comment by janpio** [comment]
Is this request covered by this existing issue https://github.com/prisma/prisma/issues/3219 maybe? Then we can close this one.

**Comment by ErdemGKSL** [comment]
Yup it covers thanks
