### ISSUE TITLE
`Cannot read properties of undefined` when running `npx prisma generate`

### ISSUE THREAD

**Issue by Tyrelosaur** [prisma/prisma#16955]
### Bug description

I've cloned a repo that uses prisma (specifically, `prisma` is a devDependency, and `@prisma/client` is a dependency). 

I run `npm install`, then `npx prisma generate`, and I get the following: 

```
➜  repo_name git:(main) npx prisma generate
Prisma schema loaded from prisma/schema.prisma
Error:
Cannot read properties of undefined (reading 'prisma')
```

Confusingly, this process works fine for both my coworker who set up the repo, as well as another coworker who followed the same process I did. We're all at a loss for what the issue could be, or how to go any further with debugging it.

We have tried: 
- deleting `node_modules`, rerunning steps above
- restarting VSCode, rerunning steps above
- deleting `node_modules`, restarting VSCode, rerunning steps above
- deleting the repo, restarting VSCode, cloning the repo, rerunning steps above

Even more confusingly, `npx prisma studio` works for me. 

### How to reproduce

Unknown

### Expected behavior

`npx prisma generate` should work

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id    Int    @id @default(autoincrement())
  email String @unique
  roles Role[]

  @@map("users")
}

model Role {
  id             Int             @id @default(autoincrement())
  name           String
  users          User[]
  authorizations Authorization[]

  @@map("roles")
}

model Resource {
  id              Int             @id @default(autoincrement())
  name            String
  authorizations Authorization[]

  @@map("resources")
}

model Authorization {
  id                     Int                      @id @default(autoincrement())
  role                   Role                     @relation(fields: [role_id], references: [id])
  role_id                Int
  resource               Resource                 @relation(fields: [resource_id], references: [id])
  resource_id            Int
  action                 Action                   @relation(fields: [action_id], references: [id])
  action_id              Int

  @@map("authorizations")
}

model Action {
  id                     Int                      @id @default(autoincrement())
  name                   String
  authorizations Authorization[]

  @@map("actions")
}

```

```ts
import { PrismaClient } from '@prisma/client';

let prisma = new PrismaClient();

export default prisma;
```

### Environment & setup

- OS: macOS
- Database: sqlite3
- Node.js version: node v16.16.0, npm 8.11.0

### Prisma Version

```
➜  repo_name git:(main) npx prisma -v
prisma                  : 4.2.1
@prisma/client          : 4.7.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by janpio** [comment]
Note the mismatch between Prisma CLI and Prisma Client version. Is that this way for your colleagues as well? I think you should upgrade both to the same, more recent version and try again.

**Comment by Tyrelosaur** [comment]
That's a good spot! Pinning both dependencies to 4.7.1 does fix the issue for me. 🎉 

My coworkers also have the mismatched dependencies though. 🤔  I guess it's some transitive dependency based on `npm`. 

That's good info to have though! We'll make sure to update those dependencies in tandem from now on. 

Thank you for the help!
