### ISSUE TITLE
Improved error messages on system library detection

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#16970]
Needed error messages:

- [x] No OpenSSL installed
	- (see https://github.com/prisma/prisma/issues/16182#issuecomment-1371283457 or https://github.com/prisma/prisma/issues/13060#issuecomment-1371292454)
- [x] No `libz` system library installed 
	- (see https://github.com/prisma/prisma/issues/16205#issuecomment-1371456830)
- ...

**Comment by mcbethio** [comment]
Folks, can we fix the milestone please. 4.9.0 has left the building already

**Comment by jkomyno** [comment]
Closed by https://github.com/prisma/prisma/pull/17762
