### ISSUE TITLE
`Cannot find name '$PrismaModel'` due to feature `extendedWhereUnique` with preview feature `fieldReference`

### ISSUE THREAD

**Issue by haimprecise** [prisma/prisma#16997]
### Bug description

Using the following ref:

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fieldReference", "extendedWhereUnique"]
}
```
With Prisma versions 4.5+ yields:
`node_modules/.prisma/client/index.d.ts:20937:43 - error TS2304: Cannot find name '$PrismaModel'.`
across the entire index.d.ts file

However, when either `fieldReference` or `extendedWhereUnique` are removed, the file compiles properly.

We cannot use both `fieldReference` and `extendedWhereUnique` but our code heavily relies on them.

### Expected behavior

Should properly compile

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fieldReference", "extendedWhereUnique"]
}
```

### Environment & setup

- OS: macOS, Azure DevOps Pipeline
- Database: PostgreSQL
- Node.js version: 18.3.1
- Typescript 4.7+

### Prisma Version

```
4.5+
```

Tested all versions

**Comment by VasiliyIsaichkin** [comment]
same problem

**Comment by haimprecise** [comment]
I have narrowed it down.

It works when I remove `extendedWhereUnique`. Somehow they are colliding.

**Comment by Jolg42** [comment]
@haimprecise @VasiliyIsaichkin Could you provide an example schema to reproduce this?
Does it error when running `tsc --noEmit`?

**Comment by haimprecise** [comment]
This an example:

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["extendedWhereUnique", "fieldReference"]
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

typescript: 4.7.4
prisma: 4.6.1
@client/prisma: 4.6.1

Happens for `tsc --noEmit`

**Comment by haimprecise** [comment]
Is this issue being reviewed by some team member?

In summary, `fieldReference` collides with `extendedWhereUnique`. Both features are gold for us!

**Comment by devcodeash** [comment]
Same issue with
typescript: 4.9.5
prisma: 4.10.1

**Comment by haimprecise** [comment]
As a feedback for Preview features,  `fieldReference` and `extendedWhereUnique` aren't working together.

typescript: 4.9.5
prisma: 4.13.0

**Comment by aqrln** [comment]
I can reproduce with latest Prisma, some types are missing the `$PrismaModel` generic type parameter on the type declaration although they use it in their fields, e.g:

```ts
  /**
   * User base type for findUnique actions
   */
  export type UserFindUniqueArgsBase = {
    /**
     * Select specific fields to fetch from the User
     */
    select?: UserSelect | null
    /**
     * Filter, which User to fetch.
     */
    where: UserWhereUniqueInput<$PrismaModel>
  }
```

Note that you need `skipLibCheck: false` in your tsconfig to see the compiler error.
