### ISSUE TITLE
@prisma/client did not initialize yet (forgot to run `prisma generate`)

### ISSUE THREAD

**Issue by guyzoum77** [prisma/prisma#16990]
### Bug description

i installed @prisma/client and then i want to run my nodejs project i give this error: 
**Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues**

### Prisma information

```prisma
// Add your schema.prisma
```
[schema.zip](https://github.com/prisma/prisma/files/10290710/schema.zip)

```ts
// Add your code using Prisma Client
```
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

**Ubuntu 22.04**
node version: **v16.17.0**

### Prisma Version

```
"prisma": "^4.4.0",
```

**Comment by guyzoum77** [comment]
![error](https://user-images.githubusercontent.com/48268288/209440737-91451a19-3030-4283-8e30-12fa2e713ca9.png)

this is the error that's occurred

**Comment by jkomyno** [comment]
Hi @guyzoum77, may you please try again with `prisma@4.7.1` and report back here?
Can you also run `prisma version`, first with `prisma@4.4.0` installed and later with `prisma@4.7.1` installed? Thanks

**Comment by y471n** [comment]
I had the same error on `"prisma": "^4.8.0"`

This are the details on `prisma version`:

```
root@2d047ac1ad19:/usr/src/app# npx prisma version
prisma                  : 4.8.0
@prisma/client          : 4.8.0
Current platform        : linux-arm64-openssl-1.1.x
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/migration-engine-linux-arm64-openssl-1.1.x)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/introspection-engine-linux-arm64-openssl-1.1.x)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/prisma-fmt-linux-arm64-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by jkomyno** [comment]
Hey @guyzoum77 and @y471n, happy new year. Have you tried running `prisma generate` as suggested by the error message?
If you did and it failed with an error, please paste such error and its stacktrace here.

**Comment by Jolg42** [comment]
Which package manager are you using? (npm, yarn, pnpm?)
Are you using a custom output for the generator?
Are you using "workspaces" with your package manager?

**Comment by guyzoum77** [comment]
i use npm.
I resolved the issue. After that I executed the prisma command: npx prisma
generate, I pasted this code : * const { PrismaClient } =
require('../../../../prisma/node_modules/.prisma/client');  *
and it works well for me.

Le mar. 3 janv. 2023 à 08:52, Joël Galeran ***@***.***> a
écrit :

**Comment by guyzoum77** [comment]
I resolved the issue. After that I executed the prisma command: npx prisma
generate, I pasted this code : * const { PrismaClient } =
require('../../../../prisma/node_modules/.prisma/client');  *
and it works well for me.

Le mar. 27 déc. 2022 à 11:50, Alberto Schiabel ***@***.***> a
écrit :

**Comment by guyzoum77** [comment]
I resolved the issue. After that I executed the prisma command: npx prisma
generate, I pasted this code : * const { PrismaClient } =
require('../../../../prisma/node_modules/.prisma/client');  *
and it works well for me.

**Comment by guyzoum77** [comment]
I resolved the issue. After that I executed the prisma command: npx prisma
generate, I pasted this code : * const { PrismaClient } =
require('../../../../prisma/node_modules/.prisma/client');  *
and it works well for me.

Le dim. 1 janv. 2023 à 20:57, Alberto Schiabel ***@***.***> a
écrit :

**Comment by jkomyno** [comment]
@guyzoum77 thanks for confirming that `prisma generate` was the missing step. Closing the issue as it's solved.

**Comment by stoand** [comment]
I had the issue because I had two `node_modules` directories. After I deleted one `node_modules` and ran `prisma generate` it worked!

**Comment by bmsptra24** [comment]
If you use docker compose try this:
1. add this to your Dockerfile

    COPY prisma ./prisma/ 

2. add the prisma directory to your volume in `docker-compose.yml` file

       volumes:
         - /app/prisma

in my case `docker-compose.yml` file will look like this

    version: "3"

    services:
      web:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: web
        restart: always
        volumes:
          - ./:/app
          - /app/node_modules
          - /app/.next
          - /app/prisma
        ports:
          - 3000:3000

**Comment by guyzoum77** [comment]
Greetings, I am grateful for the interest shown. Thanks for sharing this
piece of code.
Sincerely

Le lun. 18 sept. 2023 à 10:34, Bima Saputra ***@***.***> a
écrit :

**Comment by guyzoum77** [comment]
Greetings, i have this error : 
PrismaClientInitializationError: Unable to require(`/home/guy-serge/projects/backends/nodeJS/hairstylev2/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node`).
Prisma has detected an incompatible version of the `glibc` C standard library installed in your system. This probably means your system may be too old to run Prisma. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

**Comment by guyzoum77** [comment]
Thank you, I will do that.

Le mer. 4 oct. 2023 à 12:35, Jan Piotrowski ***@***.***> a
écrit :

**Comment by BOSSgua** [comment]
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/1
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/2
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/3
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/4
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/5
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/6
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/7
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/8
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/9
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/10
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/11
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/12
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/13
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/14
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/15
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/16
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/17
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/18
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/19
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/20
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/21
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/22
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/23
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/24
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/25
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/26
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/27
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/28
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/29
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/30
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/31
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/32
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/33
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/34
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/35
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/36
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/37
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/38
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/39
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/40
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/41
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/42
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/43
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/44
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/45
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/46
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/47
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/48
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/49
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/50
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/51
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/52
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/53
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/54
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/55
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/56
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/57
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/58
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/59
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/60
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/61
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/62
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/63
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/64
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/65
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/66
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/67
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/68
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/69
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/70
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/71
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/72
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/73
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/74
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/75
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/76
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/77
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/78
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/79
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/80
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/81
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/82
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/83
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/84
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/85
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/86
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/87
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/88
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/89
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/90
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/91
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/92
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/93
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/94
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/95
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/96
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/97
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/98
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/99
