### ISSUE TITLE
Neo4j connector

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#1700]
This feature requests serves as a central place to discuss development and progress for the [Neo4j](https://neo4j.com/) connector.

Please leave a 👍 and/or a comment in this issue if you'd like to see support for Neo4j soon.

**Comment by javaniecampbell** [comment]
#1575 Hi, I believe this issue is connected has some concerns and interest being voiced there

**Comment by pantharshit00** [comment]
That issue was transferred from the the old prisma1 repo. I am not sure why we did that. I am going to close this one as a duplicate though.

Closing as a duplicate of #1575
