### ISSUE TITLE
prisma deploy doesn't read env file correctly

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#1701]
When executing `prisma deploy -e database/.env.prod` from the parent directory of the `prisma.yml` while having a `.graphqlconfig` that points to `database/prisma.yml`, instead of the `.env.prod` being loaded, the `.env` file is used instead.

**Comment by stephenhandley** [comment]
I'm unable to get .env files working, even without the cli switch. When I create a new graphcool project via `graphcool-framework/0.11.5` and add the twilio template and then create a .env file with the following
```
TWILIO_ACCOUNT_SID=BLAH
TWILIO_AUTH_TOKEN=BLOOP
```

and then run `graphcool deploy` i see the following format of errors for TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN

```
/graphcool.yml: A valid environment variable to satisfy the declaration
 ▸    'env:TWILIO_ACCOUNT_SID' could not be found.
```

I've tried using -e and --env-file also with no luck there either.

**Comment by marktani** [comment]
Hey @stephenhandley, this repository is about Prisma 🙂 
Please report back [in this repository](https://github.com/graphcool/graphcool-framework/) with questions about Graphcool Framework. Thanks!

Here's a [comparison between Graphcool Framework and Prisma](https://www.graph.cool/forum/t/graphcool-framework-and-prisma/2237?u=nilan).

**Comment by stephenhandley** [comment]
@marktani https://github.com/graphcool/prisma/issues/1461

**Comment by jhalborg** [comment]
@stephenhandley - Facing same issue as you, so +1. Also wanted to say that the issue you referred to in your last comment is also on the `prisma` repo.

**Comment by Kisepro** [comment]
Any update ? 

dotenv still does not work

**Comment by Kisepro** [comment]
> Rename --dotenv to --env-file / -e 

Update the doc please : https://www.prisma.io/docs/1.0/reference/cli-command-reference/database-service/prisma-deploy-kee1iedaov/

**Comment by marktani** [comment]
You are linking the version `1.0` documentation, @Kisepro. This is correctly documented. Compare to the `1.10` documentation, where `--env-file` is used: https://www.prisma.io/docs/1.10/reference/cli-command-reference/database-service/prisma-deploy-kee1iedaov/.

**Comment by divyenduz** [comment]
I am able to reproduce this: https://github.com/divyenduz/prisma-1701

**Comment by divyenduz** [comment]
I don't think that this is resolved yet. Stale bot go away :)

**Comment by jhalborg** [comment]
What @divyenduz said 😂

**Comment by jahudka** [comment]
Might be related: I'm running `prisma deploy --env-file '/absolute/path/to/some/.env'` and it's telling me '--env-file path '/absolute/path/to/some/.env' does not exist`, even though I'm pretty sure it does.

**Comment by jahudka** [comment]
Actually I think the issue is with [this line](https://github.com/prisma/prisma/blob/master/cli/packages/prisma-cli-core/src/commands/deploy/deploy.ts#L74) - `path.join(this.config.cwd, envFile)` won't work properly for absolute paths - methinks you meant `path.resolve` rather than `path.join` ;-)

**Comment by harrisrobin** [comment]
I am having the same issue except it's that I cannot load any file that's not called `.env`. Using `.env.prod` doesn't work, whether it's moved to `/` or not @divyenduz .

I have tried:
`prisma deploy --env-file .env.prod`
`prisma deploy -e .env.prod`
None of those work and the .env.prod is never loaded, rather the .env file is always loaded and it only deploys locally.

I've ran into this issue before but somehow fixed it by commenting out https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/dotenv, but this workaround does not seem to work anymore.

I currently swap out the `.env.prod` to `.env` just to deploy to prod and vice versa since it still seems to read `.env` properly.

**Comment by divyenduz** [comment]
This is [not reproducible](https://github.com/divyenduz/prisma-1701/) anymore. Please open a new issue in case the problem persists for you.

**Comment by blazestudios23** [comment]
This happens when I run primsa generate, it can't read the env variables. 

```
prisma generate -p ./prisma/auth/prisma.yml -e ./config/.env
 ! A valid environment variable to satisfy the declaration 'env:PRISMA_AUTH_ENDPOINT' could not be found.
```
