### ISSUE TITLE
Deno `@prisma/client` is tied to 4.6.1

### ISSUE THREAD

**Issue by seanaye** [prisma/prisma#17017]
### Bug description

Running `deno run -A --unstable --reload npm:prisma@4.8 generate --data-proxy` even with empty deno.lock will install `prisma@4.8` but `@prisma/client@4.6.1`

The client install version should match the prisma version

### Expected behavior

The version of the generated `@prisma/client` should be `4.8`

### Prisma information

Section not relevant
```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: MacOS 12.6
- Database: Postgresql
- Node.js version: Deno v1.29.1

### Prisma Version

```
Prisma 4.8
@prisma/client 4.6
```

**Comment by janpio** [comment]
I can not reproduce this:

```
C:\Users\Jan\Documents\throwaway\17017>deno run -A --unstable --reload npm:prisma@4.8 generate --data-proxy
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
napi_add_env_cleanup_hook is currently not supported
✔ Created ./package.json

[...]

✔ Installed the @prisma/client and prisma packages in your project

✔ Generated Prisma Client (4.8.0 | dataproxy) to .\node_modules\@prisma\client in 143ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

...
```
```
C:\Users\Jan\Documents\throwaway\17017>deno run -A --unstable --reload npm:prisma@4.8 -v
napi_add_env_cleanup_hook is currently not supported
Environment variables loaded from .env
prisma                  : 4.8.0
@prisma/client          : ^4.8.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ..\..\..\AppData\Local\deno\npm\registry.npmjs.org\@prisma\engines\4.8.0\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ..\..\..\AppData\Local\deno\npm\registry.npmjs.org\@prisma\engines\4.8.0\migration-engine-windows.exe)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ..\..\..\AppData\Local\deno\npm\registry.npmjs.org\@prisma\engines\4.8.0\introspection-engine-windows.exe)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ..\..\..\AppData\Local\deno\npm\registry.npmjs.org\@prisma\engines\4.8.0\prisma-fmt-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

But, `generate` is installing Prisma Client via `npm install ...` here behind the scenes. That is not optimal (as obviously not Deno native) - so do you maybe have a `package.json` somewhere that Npm could read instead of the current project file that could lead it to use the wrong version?

**Comment by jkomyno** [comment]
Hi @seanaye, I wonder if you have seen @janpio's answer? If so, could you please report back whether that fixes this issue? Please be sure to test it with a recent version of Prisma as well (e.g., `5.0.0`). Thank you.

**Comment by jkomyno** [comment]
Hey @seanaye, can you please report back with answers to the questions above? They would help us investigating this issue. Thanks!

**Comment by jkomyno** [comment]
Hi @seanaye, as we were not able to get a response, we're closing this issue. Feel free to leave a comment asking to re-open it, should you have more info to share with us as per the comments above. Thanks!

**Comment by janpio** [comment]
Some more information here @seanaye:
- Deno uses will use a cached version for the CLI when you do not specify an exact version. You can force a new “latest” version by using `--reload=npm:prisma` or by specifying version explicitly (`deno run npm:prisma@4.9.0`). But you already do that.
- The version of `@prisma/client` actually comes from `package.json` file that was created in your project. Is it possible that you had that file with that content?
