### ISSUE TITLE
Support dynamic model names in the schema via `env()`

### ISSUE THREAD

**Issue by bozlurrahman** [prisma/prisma#17015]
I need to make dynamic collection names based on project environment. 
For example "local_users", "staging_users" or "live_users"

my schema.prisma code as follows: 

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["filteredRelationCount"]
  binaryTargets   = ["debian-openssl-1.1.x", "rhel-openssl-1.0.x", "rhel-openssl-1.1.x", "native"]
}

datasource db {
  provider = "mongodb"
  url      = env("DB_URL")
}

model User {
  id         String   @id @default(auto()) @map("_id") @db.ObjectId
  name       String   @default("")
  email      String   @unique
  enabled    Boolean  @default(true)
  created_at DateTime @default(now())
  updated_at DateTime @default(now())

  @@map(env("USER_COLLECTION_NAME"))    // <====== here i unable to use env
}
```
when i run `npx prisma generate` i have got the following error: 

```
> npx prisma generate; 

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Schema validation error - Error (query-engine-node-api library)
Error code: P1012
error: Expected a string value, but received functional value `env("USER_COLLECTION_NAME")`.
  -->  schema.prisma:25
   | 
24 | 
25 |   @@map(env("USER_COLLECTION_NAME"))
   | 

Validation Error Count: 1
[Context: getDmmf]

Prisma CLI Version : 4.6.1
```

**Comment by jkomyno** [comment]
Hi @bozlurrahman, dynamically renaming model names is not a feature Prisma supports at the moment, and is currently not in our planning. May I suggest an alternative approach that would work with the current version of Prisma? How about keeping the `@@map`'d model name static (e.g., `user_collection`), and preparing 3 different databases (one for local development, one for staging, one for live usage)? This way, you could keep the Prisma schema static, and you'd only need to update the `DB_URL` environment variable value in the `datasource` block.

Please let us know whether the proposed solution works for you, so we can close this issue :)

**Comment by bozlurrahman** [comment]
OK. 
no problem 
Thank you for your support with alternative planning.
