### ISSUE TITLE
connecting to local sql server on win11 pro

### ISSUE THREAD

**Issue by pookiepats** [prisma/prisma#17021]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.12.1           | 
| Prisma CLI  | 4.8.0              | 
| Engine      | d6e67a83f971b175a593ccc12e15c4a757f93ffe| 

## Error
```
Error: [libs\sql-schema-describer\src\mssql.rs:336:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `\n/****** Object:  User dbo    Script Date: 1/25/2006 11:12:28 AM ******/\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 1/25/2006 11:12:36 AM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 12/21/2005 10:54:26 AM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 12/1/2005 1:38:42 PM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/30/2005 3:07:59 PM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/30/2005 1:53:54 PM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/29/2005 2:32:03 PM ******/\r\ncreate default [Dflt_Blank] as ''\r\n\r\n\r\n\r\n\r\n\r\n`"
```

**Comment by jkomyno** [comment]
Hi @pookiepats, which SQL Server version are you using?
Could you please share your schema (at least the `datasource` block) and your database connection URL? Feel free to hide sensitive details as your database password.

**Comment by jkomyno** [comment]
Hey @pookiepats, can you please answer to this [previous question](https://github.com/prisma/prisma/issues/17021#issuecomment-1365828796)? Without that information, we can't investigate this issue. Thank you!

**Comment by jkomyno** [comment]
Hi @pookiepats, as we were not able to get a response, we're closing this issue. Feel free to leave a comment asking to re-open it, should you have more info to share with us as per the comments above. Thanks!
