### ISSUE TITLE
Prisma generated files exceed Vercel 50MB serverless function size limit

### ISSUE THREAD

**Issue by 6peterlu** [prisma/prisma#17043]
### Bug description

When creating a serverless function on Vercel with prisma, the generated prisma files exceed 50MB by themselves, making prisma incompatible with vercel serverless functions. Here is an example size table reported by Vercel:
```


Large Dependencies            Uncompressed size  Compressed size
--
17:47:40.610 | web/generated/prisma                  142.15 MB         51.99 MB
17:47:40.610 | web/node_modules/next                   2.19 MB         760.8 KB
17:47:40.610 | web/node_modules/react-dom              2.18 MB        546.37 KB
17:47:40.610 | web/.next/server                     1007.04 KB        247.88 KB
17:47:40.610 | web/node_modules/@nextui-org          803.96 KB        245.01 KB
17:47:40.610 | web/node_modules/iconv-lite           321.65 KB         175.1 KB
17:47:40.610 | web/node_modules/graphql              598.74 KB        147.53 KB
17:47:40.611 | web/node_modules/@react-aria          430.31 KB        109.37 KB
17:47:40.611 |  
17:47:40.611 | All dependencies                      153.51 MB         55.13 MB

```

### How to reproduce

Create a stub nextJS project and include prisma in the dependencies.

### Expected behavior

I'm not sure what is expected. Is this a bug or do I need to migrate off of prisma or off of vercel?

### Prisma information

@prisma/client 4.3.1
@prisma/engines 4.3.1

### Environment & setup

Vercel

### Prisma Version

```
4.3.1
```

**Comment by jkomyno** [comment]
Hi @6peterlu, can you please try again using `prisma@4.8.0`? As highlighted in the [release notes](https://github.com/prisma/prisma/releases/tag/4.8.0), we have shrunk the size of Prisma engines by ~50%.

**Comment by 6peterlu** [comment]
Oh thank you so much! Upgrading prisma and prisma client shrunk it enough. Awesome work by the prisma team 💪

**Comment by janpio** [comment]
Besides that, do you really need Prisma CLI in your serverless function?
Is Prisma CLI installed as a normal dependency or a dev dependency? As a dev dependency, it should usually not be included in the function archive.

**Comment by 6peterlu** [comment]
@janpio good question, I did not realize I was including the CLI in the function. is that the "prisma" package?

**Comment by janpio** [comment]
Yes, `prisma` is Prisma CLI, `@prisma/client` is the Prisma Client (runtime) and `.prisma/client` is the generated Client specific to your Prisma schema.

**Comment by 6peterlu** [comment]
@janpio got it, thanks. i was originally installing the CLI to run migrate during deployment, but I will now try running that in a separate step instead of bundling it into the prod server
