### ISSUE TITLE
`db pull` sometimes overrides manually added relation names

### ISSUE THREAD

**Issue by baptistemarchand** [prisma/prisma#17050]
### Bug description

When I run `prisma db pull`, it overrides my manually renamed relations fields.

### How to reproduce

1) Create a mysql database and run the following :
```sql
CREATE TABLE `User` (
  `id` char(25) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Profile` (
  `id` char(25) CHARACTER SET utf8 NOT NULL,
  `user` char(25) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user` (`user`),
  CONSTRAINT `Profile_ibfk_1` FOREIGN KEY (`user`) REFERENCES `User` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

2) Run `db pull`. It should create the following schema :
```prisma
model Profile {
  id   String  @id @default(cuid()) @db.Char(25)
  user String? @default(cuid()) @db.Char(25)
  User User?   @relation(fields: [user], references: [id], onUpdate: Restrict, map: "Profile_ibfk_1")

  @@index([user], map: "user")
}

model User {
  id      String    @id @default(cuid()) @db.Char(25)
  Profile Profile[]
}
```
3) In the schema, rename the field `Profile` to `profiles` and run `db pull`
4) The schema is unchanged, as expected
5) In the schema, rename the `User` field. The `Profile` model should now be :
```prisma
model Profile {
  id     String  @id @default(cuid()) @db.Char(25)
  userId String? @default(cuid()) @db.Char(25)
  user   User?   @relation(fields: [userId], references: [id], onUpdate: Restrict, map: "Profile_ibfk_1")

  @@index([userId], map: "user")
}
```
6) run `db pull` again. This time all our changes are overridden and the schema is reset to the state it was in at step 2.

### Expected behavior

At step 6 of my repro instructions, I expected my schema to be un-changed.

### Prisma information

See repro.

### Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: `v14.18.3`

### Prisma Version

```
prisma                  : 4.8.0
@prisma/client          : 4.0.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by pimeys** [comment]
I tried to reproduce this with latest main or 4.8.0. As expected, there were no changes in step 6. This might happen if passing the `--force` parameter, but not without.

**Comment by janpio** [comment]
@baptistemarchand Can you take another look if something is missing from that reproduction or if you can surely reproduce what you decsribe above? Thanks.

**Comment by baptistemarchand** [comment]
I reproduced the problem on 4.10.0 (same behaviour).

However I didn't hit this bug recently on my real app (as opposed to the minimal example I provided here).
I found out that there was a typo in one of my `@map` statement which caused `db pull` to erase all the custom fields.
For example if you have a model with `userId String? @map("uesr") @db.Char(25)`, prisma will not find the `uesr` field (it should be `user`) and ignore all the renamed fields in that relation.
I hope this can help somebody!

I still don't understand what's happening with my minimal example though.

**Comment by janpio** [comment]
The typo is an interesting clue. That might be able to influence things.

**Comment by pimeys** [comment]
Hey @baptistemarchand, could you maybe create us a repo for reproduction? I tried a few times to reproduce this, but it's a no go, it works as expected. The typo clue is a good one, but not really a bug then?

**Comment by baptistemarchand** [comment]
@pimeys I haven't experienced this bug again in the real world so I'm ok if this issue is closed for now.
