### ISSUE TITLE
Timed out fetching a new connection from the connection pool

### ISSUE THREAD

**Issue by theabhinavdas** [prisma/prisma#17057]
Might be related to #7249.

Over the past ~24 hours, our production application is inaccessible by our B2B partners. 

We are a product hosted on Heroku. Two web-app dynos to serve the product, one heartbeat dyno to run some background processing, data ingestion, etc. We connect to a Postgres database also managed by Heroku that should technically accept 500 connections (per Heroku). 

The error we see in our application logs are:

```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: Timed out fetching a new connection from the connection pool. (More info: http://pris.ly/d/connection-pool, Current connection limit: 9)
```

We opened a bug ticket with Heroku and were asked to add a `connection_limit` param in the connection string with a larger number. We were also asked to introduce a `pool_timeout`. We tried multiple variations of these parameters like:

1. `?connection_limit=300`
2. `?connection_limit=300&pool_timeout=20`
3. `?connection_limit=40&pool_timeout=60`

But none of these stopped the original error (mentioned above).

#7249 refers to upgrading prisma to a higher version and I joined the Prisma Slack channel to try to get some more help. @nikolasburk suggested opening up an issue and I really appreciate how friendly and responsive the Prisma team is.

### Versions
```
prisma               : 2.26.0
@prisma/client       : 2.26.0
Current platform     : Linux f7868fed-dfe6-4b3e-9c8f-4186a7bd4286 4.4.0-1104-aws #109-Ubuntu SMP Tue May 10 11:27:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux (Heroku Dyno)
Database server      : PostgreSQL 13.9 (Ubuntu 13.9-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
```

##### `heroku pg:info`
```
Plan:                  Standard 5
Status:                Available
Data Size:             103 GB
Tables:                10
PG Version:            13.9
Connections:           110/500
Connection Pooling:    Available
```

##### schema.prisma
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

##### Additional usage examples
```
const prisma = new PrismaClient({
  datasources: {
    db: {
      url: `${process.env.DATABASE_URL}?connection_limit=40&pool_timeout=60`,
    },
  },
  log: [
    "warn",
    "error",
    {
      level: "query",
      emit: "event",
    },
  ],
});
```

**Comment by jkomyno** [comment]
Hi @theabhinavdas, thanks for opening this issue. We don't have recent reports of connection pool timeouts for Prisma 4, so I think upgrading your Prisma version is the best course of action in this case. I would thus recommend keeping Prisma up to date as suggested in #7249.

I'd first try updating Prisma to `v3.0.1` following this [release notes](https://github.com/prisma/prisma/releases/tag/3.0.1), then to `v3.10.0` ([release notes](https://github.com/prisma/prisma/releases/tag/3.10.0)), and finally to `v4.7.1` (whose release notes are [here](https://github.com/prisma/prisma/releases/tag/4.7.0) and [here](https://github.com/prisma/prisma/releases/tag/4.7.1)).

Each release note linked above should guide you through the major Prisma changes that have occurred throughout the years. Please, let us know whether this helped!

**Comment by theabhinavdas** [comment]
@jkomyno Understood. I'll close this ticket as we work on updating our Prisma version. I will reopen this ticket if we continue to see these errors post updation.

**Comment by jkomyno** [comment]
Thank you @theabhinavdas!

**Comment by aaly00** [comment]
I am on Prisma 4.7.1 and my DB is hosted with PlanetScale and I am experiencing this issue.

**Comment by janpio** [comment]
Please open a new issue and describe your full setup @aaly0 - we need more inforamtion to understand what might be happening to you.

**Comment by masterkain** [comment]
this is still ongoing, on next.js 13 I'm having a lot of issues keeping the app up using also route handlers, it might be hard to put up a repro repo but I'll try if there's a chance somebody will look at it

**Comment by chris-snow** [comment]
Also experiencing this issue on Prisma 4.14.0.

RDS db.t3.medium MySQL. Have changed our connection_limit to 40 now in hopes of not experiencing it again, but was already bumped from 3 to 12 a few weeks ago.

**Comment by raulsanchez1024** [comment]
@aaly00, @masterkain - Did you all figure this out? Having the same issue using nextjs13, react-query, and Postgres.

The issue happens when a user initially logs in. The app calls four different APIs (no real load since it's only in dev with one user). Happening about 1/10 times which means I cannot move forward :(

**Comment by JClackett** [comment]
Im definitely getting this still, prisma version 5, on heroku

```
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 9)
```

any ideas how to increase the current pool timeout limit on heroku?

**Comment by janpio** [comment]
> any ideas how to increase the current pool timeout limit on heroku?

You can increase the connection pool timeout by setting the `pool_timeout` parameter to a value larger than the default (10 seconds) in your database connection URL. Here is an example:

```
datasource db {
	provider = "postgresql"
	url = "postgresql://johndoe:mypassword@localhost:5432/mydb?connection_limit=5&pool_timeout=20"
}
```

In this example, the pool timeout is set to 20 seconds. Adjust this value according to your needs.

From the link that is part of the error message: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool#connection-pool-timeout


> Im definitely getting this still

This is normal if your connection pool is at capacity.
