### ISSUE TITLE
Prisma 4.9.x (dev version) broke `openssl` detection for Linux distros besides Alpine and Debian-based distros, like RHEL

### ISSUE THREAD

**Issue by thiagodebastos** [prisma/prisma#17063]
### Bug description

```shell
➜ reacall-app git:(master) DEBUG="*" pn i
  corepack Reusing pnpm@7.21.0 +0ms
Lockfile is up to date, resolution step is skipped
Already up to date

> reacall@0.1.0 postinstall /home/thiago/dev/sandbox/reacall-app
> prisma generate

  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:download  file /home/thiago/dev/sandbox/reacall-app/node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-5.0.x.so.node does not exist and must be downloaded +0ms
Error: Error: Unknown binaryTarget debian-openssl-5.0.x and no custom engine files were provided
    at /home/thiago/dev/sandbox/reacall-app/node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/dist/index.js:23115:13
    at async Promise.all (index 0)
 ELIFECYCLE  Command failed with exit code 1.
```

#### Method 1: `npx prisma generate`

1. `npm init -y`
2. `npm i @prisma/client`
3. `npx prisma generate`
4. See error `Error: Unknown binaryTarget debian-openssl-5.0.x and no custom engine files were provided`

#### Method 2: `npx prisma init`

1. `npx prisma init` or `npx prisma@dev init` or `npx prisma@4.8 init`
2. See error `Error: Unknown binaryTarget debian-openssl-5.0.x and no custom engine files were provided`

#### Method 3: `npx prisma init` with latest and dev versions:

1. `npx prisma@latest init`:
1.1 `Error: Unknown binaryTarget debian-openssl-5.0.x and no custom engine files were provided`  
2. `npx prisma@dev init`:
2.1 `Error: Pattern matching error: no pattern matches value {"arch":"x64"}`

### Expected behavior

No errors

### Prisma information

N/A

### Environment & setup

- OS: openSUSE Tumbleweed x86_64
- Kernel: 6.0.12-1-default 
- Shell: zsh 5.9 
- WM: i3
- Database: default
- Node.js version: attempted on v19.3.0, v18.19.2, v16.18.1
- OpenSSL: 1.1.1s  1 Nov 2022

### Prisma Version

Attempting to install prisma globally and then running `prisma -v` results in the same error:

```
Error: Unknown binaryTarget debian-openssl-5.0.x and no custom engine files were provided
```

This happens using prisma versions 4.8 and 4.9.

__This does not happen using prisma@4.7__

## Workaround

1. `rm -rf node_modules`
4. `npm i -D prisma@4.7`
5. `npm i @prisma/client@4.7`

__Running prisma -v with prisma 4.7:__
```shell
➜  reacall-app git:(master) ✗ ./node_modules/.bin/prisma -v
prisma                  : 4.7.1
@prisma/client          : 4.7.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/.pnpm/@prisma+engines@4.7.1/node
_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/.pnpm/@prisma+engines@4.7.1
/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/.pnpm/@prisma+engines@4.7.1/n
ode_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/.pnpm/@prisma+engines@4.7.1/node_modu
les/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.7.1-1.272861e07ab64f234d3ffc4094e32bd61775599c
Default Engines Hash    : 272861e07ab64f234d3ffc4094e32bd61775599c
Studio                  : 0.477.0
```

**Comment by jkomyno** [comment]
Hi @thiagodebastos, happy new year and thanks for opening this issue. This is indeed a regression unintentionally introduced in `prisma@4.8.0` via https://github.com/prisma/prisma/pull/16965. While we work on a solution, can you please run the following commands in your `openSUSE` system, and report here with the output?

1. `ls -l /usr/lib/x64-linux-gnu/libssl.so.1.1*`
2. `openssl version`
3. `ldconfig -p | grep ssl`
4. `ls -l /lib64 | grep ssl`
5. `ls -l /usr/lib64 | grep ssl`

**Comment by Jolg42** [comment]
It looks like you used `prisma@dev` at some point, we indeed have the `Error: Pattern matching error: no pattern matches value {"arch":"x64"}` bug in this internal dev version we are working on.

Though, `4.8.0` should work. Could you try deleting your node_modules directory and installing `4.8.0`?
