### ISSUE TITLE
Error: called `Result::unwrap()` on an `Err` value: "Couldn't parse default value in SQL Server

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#17069]
Command: `prisma db pull`
Version: `4.8.0`
Binary Version: `d6e67a83f971b175a593ccc12e15c4a757f93ffe`
Report: https://prisma-errors.netlify.app/report/14485 
OS: `x64 win32 10.0.22621`

JS Stacktrace:
```
Error: [libs\sql-schema-describer\src\mssql.rs:336:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `\n/****** Object:  User dbo    Script Date: 1/25/2006 11:12:28 AM ******/\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 1/25/2006 11:12:36 AM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 12/21/2005 10:54:26 AM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 12/1/2005 1:38:42 PM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/30/2005 3:07:59 PM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/30/2005 1:53:54 PM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/29/2005 2:32:03 PM ******/\r\ncreate default [Dflt_Blank] as ''\r\n\r\n\r\n\r\n\r\n\r\n`"
```

**Comment by jkomyno** [comment]
Code context: https://github.com/prisma/prisma-engines/blob/e88b5dd70fddc391f9344ee8056dfd92f0f6fdef/libs/sql-schema-describer/src/mssql.rs#L328-L336

**Comment by Jolg42** [comment]
It looks like that user created an issue here https://github.com/prisma/prisma/issues/17104

**Comment by Jolg42** [comment]
We have 6 open issues with "Couldn't parse default" for SQL Server currently https://github.com/prisma/prisma/issues?q=Couldn%27t+parse+default+value+is%3Aopen
Could be worth checking them all

**Comment by janpio** [comment]
We still do not know how to make Introspection crash because of the existence of such an index. 
We need a SQL dump of a database that reproduces this behavior to replicate this behavior.

(For us the default is just ignored and not represented in the Prisma schema: https://github.com/prisma/prisma/issues/12150)

**Comment by janpio** [comment]
Reproduced: The line breaks cause this, see https://github.com/prisma/prisma/issues/24275
