### ISSUE TITLE
npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! prisma@4.8.0 preinstall: `node scripts/preinstall-entry.js` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the prisma@4.8.0 preinstall script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  npm ERR! A complete log of this run can be found in: npm ERR!     /root/.npm/_logs/2022-12-30T22_08_25_070Z-debug.log

### ISSUE THREAD

**Issue by ukcai696969** [prisma/prisma#17073]
### Bug description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prisma@4.8.0 preinstall: `node scripts/preinstall-entry.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prisma@4.8.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-30T22_08_25_070Z-debug.log

### How to reproduce

npm i 

### Expected behavior

install packages

### Prisma information

idk what this means

### Environment & setup

ubuntu 20.04

### Prisma Version

```
 "@prisma/client": "^4.7.1",
```

**Comment by annibuliful** [comment]
Please show the error log from `/root/.npm/_logs/2022-12-30T22_08_25_070Z-debug.log`

**Comment by ukcai696969** [comment]
[2023-01-01T22_03_44_983Z-debug.log](https://github.com/prisma/prisma/files/10329448/2023-01-01T22_03_44_983Z-debug.log)
there @annibuliful

**Comment by annibuliful** [comment]
Could you create small reproducible repo so I can check it

**Comment by ukcai696969** [comment]
if you mean what im making im using this https://github.com/ZynerOrg/xyter its a discord bot and the owner said he dont know the error so create a issue so thats it the bot works fine just this error

**Comment by Jolg42** [comment]
I found this in the logs
```
13154 verbose node v10.19.0
13155 verbose npm  v6.14.4
```

@ukcai696969 The minimum supported version is `14.17.X` https://www.prisma.io/docs/reference/system-requirements.
I can recommend installing [nvm](https://github.com/nvm-sh/nvm) for example and use v18 since it is now LTS

**Comment by Jolg42** [comment]
I'll close as this is an unsupported Node.js version, let us know if you find any other issues after upgrading.
