### ISSUE TITLE
Prisma creates a UNIQUE INDEX instead of UNIQUE CONSTRAINT when pushed from prisma to postgres db

### ISSUE THREAD

**Issue by bala0406** [prisma/prisma#17096]
### Bug description

when running `prisma db push`, instead of creating a unique constraint, a unique index is created in postgresql as seen in pgadmin4(Databases -> (DB name) -> (Table name) -> SQL tab).

### How to reproduce
1. Create a model in Prisma schema with a single or multiple unique constraint fields
2. Run `yarn prisma db push`
3. Open pgadmin4 and goto Databases -> (DB name) -> (Table name) -> SQL tab
4. See a `CREATE INDEX (...)` command at bottom instead of `CONSTRAINT UNIQUE(...)`

### Expected behavior

To create a UNIQUE CONSTRAINT in the table

### Prisma information

```prisma
model enrollments {
  student_id Int
  course_id  Int
  courses    courses  @relation(fields: [course_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
  students   students @relation(fields: [student_id], references: [id], onDelete: NoAction, onUpdate: NoAction)

  @@unique([student_id, course_id])
}
```

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: v16.18.1

### Prisma Version

```
prisma                  : 4.8.0
@prisma/client          : 4.8.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by jkomyno** [comment]
Hi @bala0406, Prisma uses `UNIQUE INDEX` on Postgres as intended, as a unique index implies a unique constraint, and
`UNIQUE INDEX` and `UNIQUE CONSTRAINT` have very similar semantics.

Is there a specific scenario you have encountered where Prisma using `UNIQUE INDEX` would be a limitation to your workflow?

**Comment by bala0406** [comment]
Thanks for responding. In terms of functionality, they both are identical. But their semantic differences introduced some confusion.
The `UNIQUE CONSTRAINT` is contained within the `CREATE` query for the particular table whereas the `UNIQUE INDEX` requires another CREATE COMMAND. Btw, it is not an issue.

**Comment by scottcollabai** [comment]
Hi, just hit this issue myself, and figured I'd comment on this as opposed to opening a new issue (though please let me know if that's preferred!)

It's true that `UNIQUE INDEX` and `UNIQUE CONSTRAINT` are semantically similar. However, there are a few resources that indicate `UNIQUE CONSTRAINT` is the preferred way to model uniqueness. Perhaps the best resource is the [PG docs directly](https://www.postgresql.org/docs/9.4/indexes-unique.html):

> Note: The preferred way to add a unique constraint to a table is ALTER TABLE ... ADD CONSTRAINT. The use of indexes to enforce unique constraints could be considered an implementation detail that should not be accessed directly. One should, however, be aware that there's no need to manually create indexes on unique columns; doing so would just duplicate the automatically-created index.

It's not _necessarily_ a bug for Prisma to do this, but it does appear that using `UNIQUE CONSTRAINT` would be more in line with PG best practices.

**Comment by janpio** [comment]
That indeed deserves a new issue @scottcollabai - will not be high priority, but maybe we can adapt our generated migrations in the future.

**Comment by scottcollabai** [comment]
Thanks! Filed a [new issue](https://github.com/prisma/prisma/issues/17732).

**Comment by tminard** [comment]
I am having an issue with this too as I actually want to take advantage of deferrable constraint (whereas the unique index variant is not and can never be deferrable)

**Comment by raphaeltm** [comment]
This has been causing me headaches because of this:

> Postgres's ON CONFLICT clause requires you to specify the name of the unique constraint, you cannot use the name of the unique index.

See:
https://github.com/hasura/graphql-engine/issues/3666#issuecomment-572419941

My assumption was that Prisma would create the constraint so I could use `ON CONFLICT`. Because it does not, I'm running into problems.

**Comment by janpio** [comment]
Please leave that comment on the linked https://github.com/prisma/prisma/issues/17732 from above. Thank you.
