### ISSUE TITLE
db pull errors on SQL Server with `Error: [libs\sql-schema-describer\src\mssql.rs:336:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: [...]`

### ISSUE THREAD

**Issue by nicosql** [prisma/prisma#17104]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.12.1           | 
| Prisma CLI  | 4.8.0              | 
| Engine      | d6e67a83f971b175a593ccc12e15c4a757f93ffe| 

## Error (original)
```
Error: [libs\sql-schema-describer\src\mssql.rs:336:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `\n/****** Object:  User dbo    Script Date: 1/25/2006 11:12:28 AM ******/\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 1/25/2006 11:12:36 AM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 12/21/2005 10:54:26 AM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 12/1/2005 1:38:42 PM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/30/2005 3:07:59 PM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/30/2005 1:53:54 PM ******/\r\n\r\n/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/29/2005 2:32:03 PM ******/\r\ncreate default [Dflt_Blank] as ''\r\n\r\n\r\n\r\n\r\n\r\n`"
```

## Error (with return spaces)
```
Error: [libs\sql-schema-describer\src\mssql.rs:336:30] called `Result::unwrap()` on an `Err` value: "
Couldn't parse default value: `
/****** Object:  User dbo    Script Date: 1/25/2006 11:12:28 AM ******/
/****** Object:  Default dbo.Dflt_Blank    Script Date: 1/25/2006 11:12:36 AM ******/
/****** Object:  Default dbo.Dflt_Blank    Script Date: 12/21/2005 10:54:26 AM ******/
/****** Object:  Default dbo.Dflt_Blank    Script Date: 12/1/2005 1:38:42 PM ******/
/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/30/2005 3:07:59 PM ******/
/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/30/2005 1:53:54 PM ******/
/****** Object:  Default dbo.Dflt_Blank    Script Date: 11/29/2005 2:32:03 PM ******/
create default [Dflt_Blank] as ''\r\n\r\n\r\n\r\n\r\n\r\n`"
```

**Comment by jkomyno** [comment]
Hi @pookiepats, could you please share which exact version of SQL Server you're using?
We provide support for SQL Server 2017 to 2022 ([docs](https://www.prisma.io/docs/reference/database-reference/supported-databases)).

Thank you.

**Comment by pookiepats** [comment]
Hi

It is 2017 but I wouldn't worry about it--I see others having this issue
but I looked into it on my side and we have inconsistencies within our
schema (specifically around DEFAULT keyword use - referring to objects
labeled [1] below).  The image on the left is just really old code, the DDL
create date is 2005; and this syntax has been deprecated.

You can ignore the other stuff it was intended for internal consumption.

Anyhow, I wouldn't expect an ORM to be able (nor should it IMO) to resolve
how it should treat a particular use case of the same keyword being used in
two different ways within the DDL.

If you guys can sort it out that'd be great but we have work to do too.

OH BUT!  I did see a fantastic idea from another user that would solve my
problem--they suggested there be a way to tell Prisma to ignore XYZ
database objects when running the introspection.

If that is possible please let me know otherwise that's all I got for ya,
thanks so much for checking in - that's fantastic response time.  I love
what you guys got going on over there.




[image: image.png]

**Comment by Jolg42** [comment]
@pookiepats I think the image didn't make it, so it's hard to know what is "labeled [1] below". Could you upload it again?

**Comment by pookiepats** [comment]
sure, here's a link instead:  https://share.getcloudapp.com/llugkejp

By the way, what is not shown here in the screenshot but also seems to
break Prisma's introspection step after inspecting the errors are any
comments that have many repeated "***************" e.g. /* objectid: arinvc
*********************************** */

**Comment by janpio** [comment]
Image embedded for the case the link goes away: 
![image](https://user-images.githubusercontent.com/183673/211101025-de7ee610-60ad-4cf7-8d58-568414d86239.png)

**Comment by janpio** [comment]
We still do not know how to make Introspection crash because of the existence of such an index. 
We need a SQL dump of a database that reproduces this behavior to replicate this behavior. Can you help @nicosql?

(For us the default is just ignored and not represented in the Prisma schema: https://github.com/prisma/prisma/issues/12150)

**Comment by janpio** [comment]
After investigating a bit further, this crash (and all the others listed under https://github.com/prisma/prisma/issues?q=label%3A%22topic%3A+CREATE+DEFAULT+...+AS+...%22) are possibly caused by an index definition like shown in the left screenshot from you @nicosql, `... DEFAULT [dbo].[Dflt_Blank] ...`.

Unfortunately we can not figure out how to create such a table, as for example this attempt is not accepted by SQL Server:
```
CREATE DEFAULT [dbo].[valueZero] AS 0;

CREATE TABLE [dbo].[A] (
    id INT IDENTITY ,
    [val] INT DEFAULT [dbo].[valueZero] NULL
);
```
As you say, defining the index in the table itself (right screenshot) works fine, as does using `sp_bindefault` to bind the default to the column. We are out of ideas here 😒

**Comment by janpio** [comment]
Ok, that was a red herring - the `sp_bindefault` way is the only way to actually set such an index for a column.

The problem is that the SQL of the default can be stored as a multi-line string, which our logic does not understands, see https://github.com/prisma/prisma/issues/24275

**Comment by BOSSgua** [comment]
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/1
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/2
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/3
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/4
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/5
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/6
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/7
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/8
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/9
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/10
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/11
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/12
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/13
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/14
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/15
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/16
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/17
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/18
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/19
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/20
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/21
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/22
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/23
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/24
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/25
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/26
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/27
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/28
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/29
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/30
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/31
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/32
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/33
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/34
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/35
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/36
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/37
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/38
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/39
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/40
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/41
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/42
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/43
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/44
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/45
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/46
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/47
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/48
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/49
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/50
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/51
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/52
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/53
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/54
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/55
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/56
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/57
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/58
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/59
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/60
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/61
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/62
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/63
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/64
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/65
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/66
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/67
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/68
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/69
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/70
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/71
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/72
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/73
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/74
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/75
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/76
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/77
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/78
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/79
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/80
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/81
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/82
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/83
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/84
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/85
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/86
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/87
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/88
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/89
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/90
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/91
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/92
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/93
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/94
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/95
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/96
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/97
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/98
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/99
