### ISSUE TITLE
Tracing: Detailed report and profiling informations

### ISSUE THREAD

**Issue by esistgut** [prisma/prisma#1711]
I am currently keeping track of and verifying SQL queries using `{debug: true, log: ['info', 'query'],}`.
While this provides useful informations my backend sometimes can spawn 20-30 database queries from a single HTTP request and so it can get pretty confusing even simply tracking the source of a specific query in my codebase.

Have you considered adding some more tracking / profiling tools? The most basic one would be printing the line generating the query alongside the query itself when using debug informations.

Of course this can be a lot more complex and feature rich: think of something like the Symfony Profiler (Doctrine part) or just the network/profiling tabs in Firefox or Chrome but with database/query related informations.

**Comment by janpio** [comment]
We now support some tools to gather that data:
- OpenTelemetry Tracing: https://www.prisma.io/docs/concepts/components/prisma-client/opentelemetry-tracing
- Metrics: https://www.prisma.io/docs/concepts/components/prisma-client/metrics

Read this blog post for more about Tracing: https://www.prisma.io/blog/tracing-tutorial-prisma-pmkddgq1lm2

**Comment by aqrln** [comment]
The `tracing` preview feature is going GA in Prisma 6.1. I'll go ahead and close this issue.
