### ISSUE TITLE
DeprecationWarning: Implicit coercion to integer for exit code is deprecated

### ISSUE THREAD

**Issue by dionsaur84** [prisma/prisma#17127]
### Bug description

i am running nodemon for an express server that uses prisma

every time nodemon restarts the server, i get this warning:

```console
(node:14591) [DEP0164] DeprecationWarning: Implicit coercion to integer for exit code is deprecated.
    at process.exit (node:internal/process/per_thread:200:7)
    at process.<anonymous> (/Users/dionsaur84/Sites/dio-framework/node_modules/@prisma/client/runtime/index.js:27577:17)
    at Object.onceWrapper (node:events:628:26)
    at process.emit (node:events:513:28)
```

this warning appears to be triggered by `@prisma/client/runtime/index.js:27577:17`:

```javascript
  installHook(event, shouldExit = false) {
    process.once(event, async (code) => {
      debug9(`exit event received: ${event}`);
      for (const listener of this.idToListenerMap.values()) {
        await listener();
      }
      this.idToListenerMap.clear();
      if (shouldExit && process.listenerCount(event) === 0) {
        process.exit(code); // <-- this line
      }
    });
  }
```

is there a way to surpress this? should i add an event listener for when my server closes to make sure prisma also disconects? how do i resolve this issue myself, or is it a prisma issue?

edit: i've added a `$disconnect` call to my server close listener and the warning still occurs:

```javascript
const server = app.listen(env.APP_PORT, () => {
    console.log(`app listening on http://localhost:${env.APP_PORT}`)
})

server.on('close', async () => {
    await prisma.$disconnect()
})
```

final edit: looks like this is only happening in node 19+ due to this change:

https://fossies.org/diffs/node/v19.2.0_vs_v19.3.0/lib/internal/process/per_thread.js-diff.html

**Comment by skyrina** [comment]
can confirm

**Comment by weedz** [comment]
Think this is a prisma issue. Can't seem to find documentation for this anywhere, and the type definitions for Node does not help either. The signal handler is typed as:

```typescript
type SignalsListener = (signal: Signals) => void;
```

But the handler for Signal-event (https://nodejs.org/api/process.html#signal-events) seems to take two arguments, `signal: string, code: number`. Tried the following with node 19, 18 and 16:

```javascript
// Begin reading from stdin so the process does not exit.
process.stdin.resume();

process.on("SIGINT", (signal, code) => {
  console.log("signal:", signal);
  console.log("code:", code);
  process.exit(128 + code);
});
```

`128` comes from https://nodejs.org/api/process.html#signal-events:
> 'SIGTERM' and 'SIGINT' have default handlers on non-Windows platforms that reset the terminal mode before exiting with code 128 + signal number

With this I guess the `installHook` function should be changed to:
```typescript
private installHook(event: string, shouldExit = false) {
    process.once(event, async (signal, code) => { // <-- `(code)` -> `(signal, code)`
        debug(`exit event received: ${event}`)
        for (const listener of this.idToListenerMap.values()) {
            await listener()
        }
        
        this.idToListenerMap.clear()
        
        // only exit, if only we are listening
        // if there is another listener, that other listener is responsible
        if (shouldExit && process.listenerCount(event) === 0) {
            process.exit(128 + code)  // <-- `code` -> `128 + code`
        }
    })
}
```

**Comment by Geczy** [comment]
i have this issue as well, any solution yet for us? its crashing a highly used production app

**Comment by SuperchupuDev** [comment]
This now throws on Node 20 instead of giving a deprecation warning

![image](https://user-images.githubusercontent.com/53496941/233797924-1f794f21-4c68-474c-a182-0c89ea3c1003.png)

related:
- nodejs/node#44711
- nodejs/node#43716

**Comment by kjenney** [comment]
Is the solution to use an older version of Node?

**Comment by kjenney** [comment]
> 

Downgrading to node 18 got me passed the error.

**Comment by SuperchupuDev** [comment]
@kjenney no, the solution is to upgrade to prisma 4.14.0 or newer

**Comment by torchsmith** [comment]
I have the same issue in 4.16.2
