### ISSUE TITLE
Fail Prisma installation / warn hard when needed system libraries are missing

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17154]
https://github.com/prisma/prisma/issues/16970 suggest to add a better warning message when needed system libraries are missing. I think we should fail or warn during Prisma installation already,  instead/additionally of failing when Prisma Client tries to execute and then shows a targetted error message.

This would apply for OpenSSL, libz and similar.

**Comment by jkomyno** [comment]
From Slack:

we should print warnings in those scenarios where we know Prisma will likely fail at runtime:
when the distro is Alpine (“musl”) but the arch is not `x86_64`, we should warn users that we don’t support that environment. We should recommend using `docker buildx build --platform linux/amd64` for their Alpine-based Dockerfile instead. We can detect if they’re running on Docker via `ls -la /.dockerenv`, or we can simply assume that each Alpine user is running Alpine on Docker
when `libssl` is undefined in `getPlatform()`, we should warn users that we didn’t find any libssl version installed, so we defaulted to the openssl-1.1.x binaryTargets, but Prisma may not work unless they manually install openssl 1.1.x. If they’re on Debian, we could also tell them that if they’re using Debian Buster or `node:16-slim` or `node:18-buster-slim` Prisma won’t work unless they install `openssl 1.1.x`. We could point them to this Github comment

**Comment by jkomyno** [comment]
Trying to detect the presence of `libz` at build time may be tricky and unreliable. Let's proceed with detecting `libssl` and have `distro / arch`-specific warnings and errors instead.

**Comment by jkomyno** [comment]
Closing this via https://github.com/prisma/prisma/pull/17334.
