### ISSUE TITLE
Netlify build fails with PrismaClientInitializationError

### ISSUE THREAD

**Issue by wadewegner** [prisma/prisma#17167]
I've got a Next.js app that uses prisma.

My `schema.prisma`:
```
generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["referentialIntegrity"]
    binaryTargets   = ["native", "debian-openssl-1.1.x"]
}

datasource db {
    provider             = "mysql"
    url                  = env("DATABASE_URL")
    referentialIntegrity = "prisma"
}
```

I'm doing development on Windows 11. Everything works great locally.

When I commit to Github, it kicks off a build in Netlify. I get the following error:
```
10:33:22 AM: /opt/build/repo/node_modules/@prisma/client/runtime/index.js:45007
10:33:22 AM:       throw new PrismaClientInitializationError(errorText, this.config.clientVersion);
10:33:22 AM:             ^
10:33:22 AM: PrismaClientInitializationError: Query engine library for current platform "debian-openssl-1.1.x" could not be found.
10:33:22 AM: You incorrectly pinned it to debian-openssl-1.1.x
10:33:22 AM: This probably happens, because you built Prisma Client on a different platform.
10:33:22 AM: (Prisma Client looked in "/opt/build/repo/node_modules/@prisma/client/runtime/libquery_engine-debian-openssl-1.1.x.so.node")
10:33:22 AM: Searched Locations:
10:33:22 AM:   /opt/build/repo/node_modules/.prisma/client
10:33:22 AM:   /opt/build/repo/node_modules/@prisma/client
10:33:22 AM:   /opt/build/repo/node_modules/@prisma/client
10:33:22 AM:   /opt/build/repo/node_modules/.prisma/client
10:33:22 AM:   /opt/build/repo/prisma
10:33:22 AM:   /tmp/prisma-engines
10:33:22 AM:   /opt/build/repo/node_modules/.prisma/client
10:33:22 AM: You already added the platforms "debian-openssl-1.1.x", "debian-openssl-1.1.x" to the "generator" block
10:33:22 AM: in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
10:33:22 AM: but something went wrong. That's suboptimal.
10:33:22 AM: Please create an issue at https://github.com/prisma/prisma/issues/new
10:33:22 AM:     at LibraryEngine.getLibQueryEnginePath (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:45007:13)
10:33:22 AM:     at async LibraryEngine.loadEngine (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:44666:33)
10:33:22 AM:     at async LibraryEngine.instantiateLibrary (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:44632:5) {
10:33:22 AM:   clientVersion: '3.15.2',
10:33:22 AM:   errorCode: undefined
10:33:22 AM: }
10:33:22 AM: info  - Generating static pages (0/5)
10:33:22 AM: /opt/build/repo/node_modules/@prisma/client/runtime/index.js:45007
10:33:23 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
10:33:22 AM:       throw new PrismaClientInitializationError(errorText, this.config.clientVersion);
10:33:22 AM:             ^
10:33:22 AM: PrismaClientInitializationError: Query engine library for current platform "debian-openssl-1.1.x" could not be found.
10:33:22 AM: You incorrectly pinned it to debian-openssl-1.1.x
10:33:22 AM: This probably happens, because you built Prisma Client on a different platform.
10:33:22 AM: (Prisma Client looked in "/opt/build/repo/node_modules/@prisma/client/runtime/libquery_engine-debian-openssl-1.1.x.so.node")
10:33:22 AM: Searched Locations:
10:33:22 AM:   /opt/build/repo/node_modules/.prisma/client
10:33:22 AM:   /opt/build/repo/node_modules/@prisma/client
10:33:22 AM:   /opt/build/repo/node_modules/@prisma/client
10:33:22 AM:   /opt/build/repo/node_modules/.prisma/client
10:33:22 AM:   /opt/build/repo/prisma
10:33:22 AM:   /tmp/prisma-engines
10:33:22 AM:   /opt/build/repo/node_modules/.prisma/client
10:33:22 AM: You already added the platforms "debian-openssl-1.1.x", "debian-openssl-1.1.x" to the "generator" block
10:33:22 AM: in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
10:33:22 AM: but something went wrong. That's suboptimal.
10:33:22 AM: Please create an issue at https://github.com/prisma/prisma/issues/new
10:33:22 AM:     at LibraryEngine.getLibQueryEnginePath (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:45007:13)
10:33:22 AM:     at async LibraryEngine.loadEngine (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:44666:33)
10:33:22 AM:     at async LibraryEngine.instantiateLibrary (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:44632:5) {
10:33:22 AM:   clientVersion: '3.15.2',
10:33:22 AM:   errorCode: undefined
10:33:22 AM: }
```

My current workaround is to force Netlify to `clear cache and deploy site` and then everything magically works.

**Comment by mcbethio** [comment]
Hey there,

Is it possible to try with the latest version of Prisma? I notice in your trace that you are using 3.15.2.

Also, could you give us a bit more detailed reproduction steps if you can. That would help us diagnose the root cause quicker. Thanks.

**Comment by evk-dev** [comment]
Hello, I'm having the same exact issue with the following setup:

- Custom docker image with (debian) node:lts as base (18)
- Prisma 4.8.1

I'm using a custom output for PrismaClient (setup according to your own documentation) but I don't think it's related to this error. The file "libquery_engine-debian-openssl-1.1.x.so.node" exists in the folder the error log displays.

**Comment by janpio** [comment]
Can you please create a separate issue @evk-dev and provide all the info the issue template asks for? The original here is Netlify specific and definitely has some differences in the error messages from what you are experiencing.

**Comment by millsp** [comment]
We will now display a hard error to prevent these pitfalls with caching in Vercel and Netlify. We will basically verify that you ran `prisma generate` on these platforms, because otherwise you would run into hard to debug caching issues.

**Comment by BOSSgua** [comment]
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/1
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/2
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/3
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/4
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/5
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/6
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/7
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/8
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/9
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/10
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/11
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/12
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/13
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/14
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/15
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/16
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/17
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/18
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/19
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/20
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/21
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/22
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/23
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/24
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/25
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/26
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/27
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/28
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/29
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/30
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/31
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/32
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/33
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/34
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/35
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/36
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/37
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/38
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/39
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/40
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/41
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/42
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/43
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/44
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/45
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/46
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/47
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/48
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/49
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/50
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/51
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/52
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/53
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/54
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/55
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/56
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/57
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/58
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/59
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/60
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/61
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/62
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/63
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/64
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/65
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/66
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/67
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/68
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/69
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/70
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/71
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/72
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/73
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/74
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/75
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/76
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/77
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/78
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/79
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/80
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/81
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/82
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/83
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/84
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/85
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/86
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/87
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/88
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/89
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/90
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/91
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/92
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/93
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/94
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/95
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/96
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/97
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/98
https://github.com/linbojuezhiming/linbojuezhiming.github.io/issues/99
