### ISSUE TITLE
Downloading Prisma engines for Node-API Fail Not Found

### ISSUE THREAD

**Issue by DylanDelobel** [prisma/prisma#17161]
### Bug description

Prisma is unable to download the engine

```shell
Downloading Prisma engines for Node-API for linux-arm-openssl-1.1.x [                    ] 
0%Error: Not Found https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/linux-arm-openssl-1.1.x/libquery_engine.so.node.gz
```
URL is not valid, open and show an XML file
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/linux-arm-openssl-1.1.x/libquery_engine.so.node.gz</Key>
<RequestId>6NW0A1EYDTQ51F3P</RequestId>
<HostId>15DdmL3/0g6Re5z9yWGZ0nzWhmlUH5Lq7GYOj7U0YAvuJr1tzs68rlppGcPi5J5cDxDmpj7CiBY=</HostId>
</Error>
```
I also have `debian-openssl-1.1.x` inside my `prisma/schema.prisma`, 
I also tried `native` and other one, still try the same URL

### How to reproduce

```
npx prisma init
```

### Expected behavior

Download the correct engine

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Application {
  id            Int               @id @default(autoincrement())
  discordId     String
  playerTag     String
  playerName    String
  townhallLevel Int
  threadId      String            @unique
  logEmbedId    String            @unique
  status        ApplicationStatus
}

```

```ts
export const prisma = new PrismaClient()
```

### Environment & setup

- OS: Raspberry Pi 3 (Debian 11 (Bullseye))
- Database: PostgreSQL
- Node.js version: v17.9.0

### Prisma Version

```
  "dependencies": {
    "@prisma/client": "^4.8.0",
    ....
  },
  "devDependencies": {
    "prisma": "^4.8.0",
    ....
  }
```

**Comment by janpio** [comment]
Internal: https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/debian-openssl-1.1.x/libquery_engine.so.node.gz exists, which means that `linux-arm-openssl-1.1.x` is not an existing engine file here.

**Comment by Jolg42** [comment]
Looks like someone else reported a similar issue https://github.com/prisma/prisma/issues/17284

@DylanDelobel Are you running Raspbian 64bit or 32bit?

**Comment by Jolg42** [comment]
Check also this https://github.com/prisma/prisma/issues/17284#issuecomment-1384110907
You might have Node.js 32bit installed

**Comment by DylanDelobel** [comment]
@Jolg42 32bit because it's a RPi2
![WhatsApp Image 2023-01-07 at 04 18 46](https://user-images.githubusercontent.com/5182186/212707041-98630e81-c44f-4208-b40a-ea8a771220f5.jpg)

I tested this with no success and many other issues
https://github.com/pantharshit00/prisma-rpi-builds

Tbh I gave up on this

**Comment by Jolg42** [comment]
@DylanDelobel Understandable!

Note: Support for Linux ARM 32bit is tracked in https://github.com/prisma/prisma/issues/5379
