### ISSUE TITLE
Unable to use Prisma in China

### ISSUE THREAD

**Issue by DaZiYuan** [prisma/prisma#17174]
### Bug description

Stuck forever when I execute Prisma command

### How to reproduce

- 1 run command:
```
yarn
```
stuck forever:
```
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⡀ @prisma/engines
[-/4] ⢀ waiting...
[-/4] ⢀ waiting...
[-/4] ⢀ waiting...
```

- 2 run command:
```
npx prisma version 
```
stuck forever:
```
Downloading Prisma engines for Node-API for windows [          ] 0%
```

-3 try to use VPN
```powershell
$ENV:HTTP_PROXY="http://localhost:10809"
$ENV:HTTPS_PROXY="http://localhost:10809"
```
run:
```
npx prisma version 
```
got error:
```
Downloading Prisma engines for Node-API for windows [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/0362da9eebca54d94c8ef5edd3b2e90af99ba452/windows/query_engine.dll.node.gz.sha256 failed, reason: connect ECONNREFUSED ::1:10809
```
-4 test curl   
```
curl https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/windows/migration-engine.exe.gz.sha256
```
it can be accessed normally
```
dc7dec961e57b49fa2f8c35b87149063083ebec60e31abdf75232d265d424739  migration-engine.exe.gz
```

### Expected behavior

When I set the proxy in the shell should be working. 
Many services cannot access directly on GitHub from China but after I set the proxy they work.

### Environment & setup

- OS: Win10
- Database: MongoDB
- Node.js version: v18.12.1

### Prisma Version

```
    "prisma": "^4.8.0",

```

**Comment by janpio** [comment]
This looks like a problem accessing your local Proxy via Node:

```
failed, reason: connect ECONNREFUSED ::1:10809
```

This seems to say that your local proxy did not accept the request coming from Prisma CLI.
