### ISSUE TITLE
Finish the implementation of `@default(nanoid())`

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#17199]
See https://github.com/prisma/prisma-engines/pull/3556 for context.

The missing pieces we identified:
- [x] Langage-tools completion https://github.com/prisma/language-tools/pull/1372
- [ ] Migrate support (engines-side) for diffing & special handling of prisma-level defaults re: warnings.
- [ ] A TS-side tests in prisma/prisma repo
	- [ ] add it to https://github.com/prisma/prisma/blob/c70940dabff16ce46365a8442b1af841fcfc48d2/packages/migrate/src/__tests__/fixtures/nativeTypes-postgresql/prisma/schema.prisma#L97
	- [ ] add it to  https://github.com/prisma/prisma/blob/c70940dabff16ce46365a8442b1af841fcfc48d2/packages/migrate/src/__tests__/fixtures/nativeTypes-cockroachdb/prisma/schema.prisma#L91
	- [ ] And a Client test, see https://github.com/prisma/prisma/blob/main/TESTING.md#functional-tests-for-the-client

Once these tasks are done, we need to:
- [ ] update / merge docs from https://github.com/prisma/docs/pull/4367
- [ ] merge language-tools https://github.com/prisma/language-tools/pull/1372
- [ ] mention `nanoid()` in our next release notes

Note: an improvement has been identified but is not planned for now -> https://github.com/prisma/prisma/issues/17294

**Comment by Jolg42** [comment]
Note: there is a docs issue at https://github.com/prisma/docs/issues/4363

**Comment by Jolg42** [comment]
For Language-tools 2 files need to be modified, basically copy what we do for cuid and rename to nanoid
https://github.com/search?q=repo%3Aprisma%2Flanguage-tools%20cuid&type=code

**Comment by rintaun** [comment]
@tomhoule For clarification, when you say

> special handling of prisma-level defaults re: warnings

are you talking about when you run `prisma db pull` it emits warnings saying `These models were enriched with ... information taken from the previous Prisma schema`-type messages?

If so, I'm not sure such warnings are actually emitted for `cuid()` and `uuid()` defaults right now, though I may be wrong. That's not to say I don't think it's a good idea, though.

**Comment by Jolg42** [comment]
Note: @tomhoule thinks he can point you to the functionality in the sql-destructive-change-checker you need to make work for this.
But he is quite busy today and would need to dive into the implementation again for the details and write a bunch of tests for diffing schemas with these defaults. They will be broken, and they will have to be fixed.

**Comment by rintaun** [comment]
I think I see where you're talking about ([warnings.rs](https://github.com/rintaun/prisma-engines/blob/c71fd52daf0c7a10c154d02e2a6ef791e4a792c3/introspection-engine/connectors/sql-introspection-connector/src/warnings.rs#L250-L256) and [scalar_field.rs](https://github.com/rintaun/prisma-engines/blob/c71fd52daf0c7a10c154d02e2a6ef791e4a792c3/introspection-engine/connectors/sql-introspection-connector/src/rendering/scalar_field.rs#L57-L64) seem relevant, among others in that call chain), but I don't see any warnings related to `cuid()` or `uuid()` except regarding Prisma 1.

**Comment by tomhoule** [comment]
For the warnings: it's about migration warnings in rather than introspection warnings, I'd follow the code around https://github.com/rintaun/prisma-engines/blob/c71fd52daf0c7a10c154d02e2a6ef791e4a792c3/migration-engine/connectors/sql-migration-connector/src/database_schema.rs#L8

For the implementation: adding a simple test with a schema with a nanoid default in https://github.com/rintaun/prisma-engines/tree/c71fd52daf0c7a10c154d02e2a6ef791e4a792c3/migration-engine/migration-engine-tests/tests/single_migration_tests should make the problem with migration generation visible.

**Comment by Jolg42** [comment]
@rintaun I update the TODO list at the top.

Did you have time to check for Migrate support and what @tomhoule mentioned? Do you need help?

Once the TODO tasks are complete in the description, we will officially add it as supported by Prisma in the next release.

**Comment by jkomyno** [comment]
Closing this, as it's done already.
