### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by steida** [prisma/prisma#1719]
Consider using it. Add `.prettierrc` file.

```js
{
  "singleQuote": true,
  "bracketSpacing": true,
  "semi": true,
  "trailingComma": "all"
}
```

**Comment by marktani** [comment]
Where do you want to add this?

**Comment by steida** [comment]
@marktani Everywhere where JavaScript is. Examples for example. Prettier is defacto standard.

**Comment by nikolasburk** [comment]
Changing the label to examples as this is where we're going to use it (rather than in docs)! I like the idea of enforcing some styling rules for all examples.
