### ISSUE TITLE
Data Platform: Unable to connect to public Cockroach

### ISSUE THREAD

**Issue by rainerhahnekamp** [prisma/prisma#17208]
### Bug description

Looks very similar to #12451. I create a new public cockroach database, can successfully connect to it from my local machine, but when I copy the connection string to Data Proxy, I am getting the error message:

```sh
Cannot connect to your database. Check your connection string or enable static IPs and configure your database to accept connections from them.
```

The connection string looks has the format **postgresql://[username]:[password]@[cluster]/[dbname]**.

Thank you very much.

### How to reproduce

Just create a new Cockroach instance within the free tier, use default values and try to connect to it in the Data Platform.

### Prisma information

-

### Environment & setup

-

### Prisma Version

-

**Comment by mcbethio** [comment]
Can you confirm that your data proxy ip address is whitelisted on the cockroachdb instance you are using. Thank you.

**Comment by mcbethio** [comment]
Some information on this page https://www.prisma.io/docs/data-platform/data-proxy/use-data-proxy might help.

**Comment by nurul3101** [comment]
Hey @rainerhahnekamp 👋 

Can you please open a support ticket by clicking on Support button on top right corner of Data Platform?

This would provide us with necessary project details needed for investigating this issue.

<img width="1501" alt="Screenshot 2023-01-11 at 2 09 13 PM" src="https://user-images.githubusercontent.com/13049676/211758143-0fdf7f43-c258-46e3-becc-ac030cf0b916.png">

**Comment by Jinsung-L** [comment]
I'm also struggling with this problem.
`Cannot connect to your database. Check your connection string or enable static IPs and configure your database to accept connections from them.`

I thought it was about `sslmode` but then I tried it with `sslmode=require` and it still didn't work.
I confirmed that I can connect to it on my local machine if `sslmode=require` even without CA file so maybe it's unrelated.

Currently have no idea on what's the cause.

**Comment by bfovez** [comment]
Same problem here. Is someone from Prisma is investigting?

**Comment by floelhoeffel** [comment]
Hey All - the error you are seeing is caused by how the platform runs introspections. That flow currently doesn't support CockroachDB. I ll check with the team what we could do about it and will report back.

**Comment by floelhoeffel** [comment]
We just shipped a workaround that should unblock you. You can now upload the schema manually. Would be great if someone could verify 🙌

**Comment by bfovez** [comment]
Hi,

A could go a step further, yes. Thank you.
A message says: "Your project was created but introspection failed and we
cannot generate a schema. Provide a schema to start using Data Browser and
Query Console.".

**Comment by bfovez** [comment]
Well... Sadly, I couldn't get much further. The Data Browser respond:
"Message: Error in Prisma Client request: Request to database timed out"
However, the database is positively ok.

Le jeu. 16 mars 2023 à 10:02, Bertrand Fovez ***@***.***> a
écrit :

**Comment by Jinsung-L** [comment]
> We just shipped a workaround that should unblock you. You can now upload the schema manually. Would be great if someone could verify raised_hands

Just checked it works fine. Thank you :+1:
