### ISSUE TITLE
Allow data proxy with local environments

### ISSUE THREAD

**Issue by reubenjh** [prisma/prisma#17218]
## Problem

I want to use the prisma data proxy but the fact the prisma environments are tied to github branches for their schema definition makes this hugely impractical. I have a dedicated local database with no static github branch associated to it for it to pull the schema.

I don't know whether this is on the roadmap or even possible to resolve. 

## Suggested solution

One option could be to use introspection against the database instance for the prisma data platform environment's schema definition, rather than the files hosted in github. Don't know if that's actually possible but i've seen some introspection stuff in your docs and I know it would be viable with graphql so 🤷 

## Alternatives

Another option would be manage whether data proxy is on or off via an environment variable rather than in the `prisma generate` command itself as this is the reason why i can't easily run my local environment with a direct connection and my deployed environments with the data proxy.

**Comment by reubenjh** [comment]
Hi @janpio, apologies, ill try again. I think i confused the issue by referring to the database as "local", i just mean it's the database I use for my development cycles. It's a fully fledged cloud hosted available database.

I have 3 databases, 1 for local development cycles (that i was calling my local database, ill call this development from here on out), 1 for a stable development environment (i'll call this staging from here on out to avoid confusion) and another for production.

The staging and production databases have stable schema files accessible in github by prisma data platform, but the development database doesnt as the schema file is in flux on my machine. For that reason, i can't connect a prisma data proxy to it. I would love to be able to as my database is in east US and i'm in New Zealand, so local development is painfully slow. Having the data proxy in east US speeds things up by miles in my testing.

I was enquiring after 2 things.
1. Is it possible to have the data proxy access the schema in more ways than a github branch, like introspection for instance, which would work with a database that gets used for local development cycles.
2. Failing that, manage whether the data proxy is on or off via an environment variable rather than a flag on the `prisma generate` command so I can have the same generate command across my environments and avoid the data proxy locally. i.e. `prisma generate` checks whether a PRISMA_ALLOW_DATA_PROXY env variable is set to decide whether it generates the stripped back or full blown query engine.

I know i could set option 2 up myself with a bash script or something but just suggesting it here as needing to figure it out yourself might be holding people back from using the data proxy? 

In my case, its not worth doing as my local environment is where I want the data proxy most 😆 However if it was just an env var or something I probably would adopt it for the benefits my staging and production environments would get.

**Comment by janpio** [comment]
> I think i confused the issue by referring to the database as "local", i just mean it's the database I use for my development cycles. It's a fully fledged cloud hosted available database.
>
> I have 3 databases, 1 for local development cycles (that i was calling my local database, ill call this development from here on out), 1 for a stable development environment (i'll call this staging from here on out to avoid confusion) and another for production.

Thanks, that indeed makes much more sense now 👍 

> The staging and production databases have stable schema files accessible in github by prisma data platform, but the development database doesnt as the schema file is in flux on my machine. For that reason, i can't connect a prisma data proxy to it. I would love to be able to as my database is in east US and i'm in New Zealand, so local development is painfully slow. Having the data proxy in east US speeds things up by miles in my testing.

Actually, the Data Proxy will not even use the Prisma Schema from your PDP account. It will upload the local version of the schema file when you start using it. I know, that is not super obvious, but the PDP Schema is actually only used for the functionality in there and not the Data Proxy.

Does that maybe already resolve your situation?

> * Is it possible to have the data proxy access the schema in more ways than a github branch, like introspection for instance, which would work with a database that gets used for local development cycles.

Yes, when you create a project you can finish the whole flow without actually connecting to a GitHub repository. That will use Introspection of the database instead of reading the file. Problem is that as soon as one environment is connected, all of them are. 
So maybe you could create _another_ project in PDP and to the Introspection only onboarding there and use your development database via that. Not optiomal, as you will have 2 projects, but maybe that is acceptable to you.

> Failing that, manage whether the data proxy is on or off via an environment variable rather than a flag on the prisma generate command so I can have the same generate command across my environments and avoid the data proxy locally. i.e. prisma generate checks whether a PRISMA_ALLOW_DATA_PROXY env variable is set to decide whether it generates the stripped back or full blown query engine.

Unfortunately not easily right now, as we run and generate different code based on the `--data-proxy` flag during `generate`. We will hopefully get there one day.

**Comment by janpio** [comment]
Nice. I'll close the issue for now, but please follow up if this works or not.

**Comment by reubenjh** [comment]
Hey there @janpio , thanks for the help. Yep it's worked nicely, i now have a hosted data browser and query tool for each of my environments, it's great :)

**Comment by jveldridge** [comment]
@reubenjh or @janpio, could you say a little bit more about the solution here? I'm having the same problem, but am not quite following the conversation on how to fix.

At, least I *think* I'm having the same problem, describing here to confirm...

In production, I have to use the data proxy because I want to use Vercel's edge runtime. But for local development, I have a database running on localhost that is not accessible to the internet and thus cannot be used with the data proxy.

Is there a way to say "use the data proxy in production, but not for local development?"

**Comment by reubenjh** [comment]
Hi @jveldridge , basically, I was wanting to use a dataproxy locally, but have it introspect my database's schema rather than read it from a schema file, since i change it during development of new features without committing. It turns out you can create a project /environment without connecting to a github account and it wont ask for the file or branch where the schema file exists, it will introspect instead.

So I ended up being able to use the data proxy locally. However, it turns out to be a terrible idea as the data proxy is on the other side of the world from me so local dev was too slow. I've since actually reverted off the data proxy entirely, I should probably be on it but I just ran out of time to think about it and it is so fast as is anyway that it didnt seem important anymore.

Good luck! No idea about edge stuff sorry

**Comment by janpio** [comment]
@jveldridge As Reuben already explained, your question is a different one.
In your case, we don't have a great answer yet - to run a _local_ DataProxy.

I would suggest to differentiate testing and deployment for both the Client import (normal vs. edge), the connection string, and how you generate the Client (`generate` vs. `generate --data-proxy`). I know that is not great, and we are working on improving this _right now_. Can't promise it will make the next release though, but hopefully the one after.

Can you maybe open a new issue @jveldridge? Then we can make sure we properly fix your use case. Thanks!

**Comment by jveldridge** [comment]
Thanks to you both for clarifying.

I'm going to hold off on opening a new issue since I'm going to be moving away from Prisma and don't want anything overindexed on my use case.
