### ISSUE TITLE
Error: ssl_ca_certs is an invalid option in database URL

### ISSUE THREAD

**Issue by robblovell** [prisma/prisma#17216]
### Bug description

When using a prisma client in a AWS context with Document DB (Essentially MongoDB), the connection url needs to have `ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem` in it. The connection requires a pem file to work. But when using ssl_ca_certs in a url string following error occurs: 

`ssl_ca_certs is an invalid option in database URL`. 

The full error is:
```
"Runtime.UnhandledPromiseRejection","errorMessage":"Error: The provided database string is invalid. MongoDB connection string error: ssl_ca_certs is an invalid option in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters."
```

The connection string is of the form: `mongodb://user:pass@clusteName-cluseterARN.docdb.amazonaws.com:27017/dbname?ssl=true&ssl_ca_certs=certFileName.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false`

This works in the context of other services we have using the node mongo client directly (not through Prisma). 

The error occurs in the context of using featherjs and a feathers-prisma adapter in my use case. This error has also been reported in the feathers-prisma repository as it is manifest in the adapter for prisma. But. I don't believe this is a problem with feathersjs or the feathers-prisma adapter as the PrismaClient is passed to the adapter directly by feathers. I believe it could be a problem with the prisma client used in the context of AWS Document DB.

### How to reproduce

Connect to a MongoDB database in AWS that requires a pem file and the `ssl_ca_certs` flag in the connection string.

### Expected behavior

Prisma connects to the database when given a connection string with a `ssl_ca_certs` flag.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "../client"
  binaryTargets   = ["native", "darwin", "rhel-openssl-1.0.x", "rhel-openssl-1.1.x"]
}
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}
...
```

```ts
// Add your code using Prisma Client
import { PrismaClient } from "../client";
import { Application } from "./declarations";

export default function (app: Application): void {
  const connectionString = app.get("database");
  const prisma = new PrismaClient({
    datasources: {
      db: {
        url: connectionString
      }
    }
  });
  prisma.$connect();
  app.set("prisma", prisma);
}

```

### Environment & setup

- OS: AWS lambda
- Database: MongoDB / AWS Document DB
- Node.js version: 16

### Prisma Version

```
Prisma 4.8.1
```

**Comment by janpio** [comment]
Our MongoDB support uses an official MongoDB Rust Client, which throws this error message. All connection string parameters on https://www.mongodb.com/docs/manual/reference/connection-string/ should be supported, and it seems `ssl_ca_certs` is not one of them.

I'll reach out to MongoDB to understand this situation better.

**Comment by janpio** [comment]
According to this StackOverflow response, maybe `tlsCAFile` is to be used here?
https://stackoverflow.com/a/73430442
Or `sslCA`?
https://stackoverflow.com/a/71923860

**Comment by janpio** [comment]
Confirmed, the correct parameter to use here is `tlsCAFile` which is also documented in the list of connection string parameters at https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.tlsCAFile So when you enable `tls` instead of `ssl` you should be able to use that with the provided `.pem` file.

Please let me know if you can confirm this works.

**Comment by robblovell** [comment]
Sorry for the very late reply: using `tlsCAFile` instead of `ssl_ca_certs` works.

**Comment by Vinayynn** [comment]
getting the below error while trying to establish a celery queue using document db , can anyone please help me with is

`Cannot connect to mongodb://cb_docdb:**@myhost.us-east-1.docdb.amazonaws.com:27017/mydb: Field 'size' is currently not supported, full error: {'ok': 0.0, 'code': 303, 'errmsg': "Field 'size' is currently not supported", 'operationTime': Timestamp(1702035015, 1)}.
`
