### ISSUE TITLE
Synchronization issues between database and migrations

### ISSUE THREAD

**Issue by LucasPreviato** [prisma/prisma#17217]
### Bug description

I'm using a docker-compose to generate a postgres image so connect to the prism at the time that I generate the migration it passes without problems, but when checking the database it can't find the _prisma_migrations table. When trying to enter a creation endpoint it returns a default data in the attributes (name: "hello worldd", email: "hello world")

![Captura de tela de 2023-01-09 22-20-36](https://user-images.githubusercontent.com/49683409/211440384-2bac4809-ed06-4f23-bd6e-b54257b7e88a.png)

![image](https://user-images.githubusercontent.com/49683409/211439845-8275c350-ffbd-4308-9117-a1072b5b3796.png)

![Captura de tela de 2023-01-09 22-16-34](https://user-images.githubusercontent.com/49683409/211439957-dee9e5a0-a3ce-445d-9a6a-6483db85ec7e.png)

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Unit{
  @@map("unit")

  id Int @id @default(autoincrement())
  name String @unique
  email String?
  createdAt DateTime @default(now())
}

```

```ts
 create({ name, email }: CreateTestisInput) {
    const testis = this.prisma.unit.create({ data: { name, email } });
    console.log(testis);

    return testis;
```

### Environment & setup

- OS: Linux <POPoS>
- Database: Postgres
- Node.js version: 18.13.0

### Prisma Version

```
prisma                  : 4.8.1
@prisma/client          : 4.8.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by mcbethio** [comment]
Hey, Please could you share your docker-compose file and also steps for us to reproduce this. That would make our life easier.

**Comment by LucasPreviato** [comment]
`version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: server
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres:
    name: server
  pgadmin-data:`
  
  `
POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
POSTGRES_DB=backend

DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?schema=public&sslmode=prefer
`

I beg your pardon, I had put the step by step in the opening. But come on I'll describe the step

1.  I go in and generate a docker compose up --build, and see if all the services are normal.
2. after I open a new terminal, and run the command docker logs <container_name> -f, I use the postgres database container to analyze only its logs
3. I open a new terminal and run yarn migrate dev --name sync, to generate the first migration or synchronize in an already created code, and check if there is any error when generating but as in the previous image it appears to generate normally
4. I see that in the docker logs terminal, it shows that error in postgres, so I enter pgadmin to check the database tables.
5. the tables appear there both the _prisma_migration and the prisma schema
6. when trying to use an endpoint either in rest or graphql creation it returns that mock data, and does not store it in the database

**Comment by janpio** [comment]
> 4. I see that in the docker logs terminal, it shows that error in postgres, so I enter pgadmin to check the database tables.

Can you share the error you are getting in your PostgreSQL logs? Is that what is contained in the screenshot?

> 5. the tables appear there both the _prisma_migration and the prisma schema

What do you mean by that? Are the tables and `_prisma_migration` successfully created or not?

> 6. when trying to use an endpoint either in rest or graphql creation it returns that mock data, and does not store it in the database

`hello world` is not something hardcoded in Prisma, so if your API returns that data it means your code that is being executed still contains that somewhere.

**Comment by LucasPreviato** [comment]
> > 4. I see that in the docker logs terminal, it shows that error in postgres, so I enter pgadmin to check the database tables.
> 
> Can you share the error you are getting in your PostgreSQL logs? Is that what is contained in the screenshot?
> 
> > 5. the tables appear there both the _prisma_migration and the prisma schema
> 
> What do you mean by that? Are the tables and `_prisma_migration` successfully created or not?
> 
> > 6. when trying to use an endpoint either in rest or graphql creation it returns that mock data, and does not store it in the database
> 
> `hello world` is not something hardcoded in Prisma, so if your API returns that data it means your code that is being executed still contains that somewhere.

another collaborator of my project is able to start without problem the endpoint only mine is having problems

**Comment by janpio** [comment]
Ok, then that can generally not be a Prisma problem when it generally works.

Still interested in your responses to my questions if you want further help.

**Comment by jkomyno** [comment]
Hi @LucasPreviato, I wonder whether you have more updates on this? We'd need more info on your side to investigate this problem. Thanks!

**Comment by jkomyno** [comment]
Hey @LucasPreviato, we're closing this issue for unresponsiveness, as we cannot proceed further with the information currently available. Should be able to collect and provide the information requested in previous messages, please leave a comment, and we will gladly re-open this issue :)
