### ISSUE TITLE
Prisma client segfault on Ubuntu 22.04

### ISSUE THREAD

**Issue by vovaklimov** [prisma/prisma#17223]
### Bug description

I'm trying to perform `node 16` to `node 18` migration and facing issues with prisma.

Basically any query I'm trying to run on a PostgreSQL DB  fails with `[1]    139600 segmentation fault` error message on my Ubuntu 22.04 environment.

### How to reproduce

1. Get a fresh Ubuntu 22.04 installation (in Docker or inside a VM) with Node v18
2. Set up a basic Prisma project using `npx prisma init` command or in any other way, use "postgresql" as a provider
3. Create any schema (it's shape doesn't matter) and sync it with your database schema
4. Create a simple script performing any query (for example `prisma.model.findMany()`) using a prisma client.
5. Get  a `segmentation fault` error while running the program.

### Expected behavior

Queries should run flawlessly and return corresponding results.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    String @id @default(uuid())
  email String @unique
  name  String
}

```

```ts
import { PrismaClient } from '@prisma/client';

const client = new PrismaClient();

console.log(await client.user.findMany());

```

### Environment & setup

- OS: Ubuntu 22.04 (inside WSL2)
- Database: PostgreSQL (hosted on Supabase)
- Node.js version: 18.13.0

### Prisma Version

```
prisma                  : 4.8.1
@prisma/client          : 4.8.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by ROOKA44** [comment]
same issue

**Comment by pitininja** [comment]
Same issue here when deploying our app with NodeJS v18. Got an error: `/usr/bin/wrap-command.sh: line 7:  1775 Segmentation fault (core dumped) node index.js`. When downgrading to NodeJS v16, it's working fine. Tested with Prisma v4.7.1 / v4.8.0 / v4.8.1 / v4.9.0

**Comment by vovaklimov** [comment]
It looks like the issue is caused by OpenSSL versioning issues. Ubuntu 22.04 has `OpenSSL 1.1.1s` and it causes Prisma to segfault on Node 18. I've tried to reproduce the issue on my Fedora 37 with OpenSSL 3.0.5 and the issue is gone.

So, basically, latest version of Prisma doesn't work properly with LTS version of Node on LTS version of Ubuntu because of OpenSSL 😅

**Comment by gtolarc** [comment]
same issue with node:lts-bullseye-slim

**Comment by do-kevin** [comment]
> It looks like the issue is caused by OpenSSL versioning issues. Ubuntu 22.04 has `OpenSSL 1.1.1s` and it causes Prisma to segfault on Node 18. I've tried to reproduce the issue on my Fedora 37 with OpenSSL 3.0.5 and the issue is gone.
> 
> So, basically, latest version of Prisma doesn't work properly with LTS version of Node on LTS version of Ubuntu because of OpenSSL 😅

Thank you. I was on Node 18.9.0. I reverted to Node 16.13.0 and the error was gone and Prisma was working again.

**Comment by aqrln** [comment]
Hi everyone! Could you check if updating `prisma` and `@prisma/client` to `4.12.0-integration-rtld-deepbind.3` fixes the issue for you? It would be very helpful to test this on more different systems.

This is an experimental dev version not intended for production but if it works as expected, we'll work on making this land in a stable release. Thank you!

**Comment by samielahi** [comment]
Updating both to `4.12.0-integration-rtld-deepbin.3` did the trick for me!

### My Setup

- OS: Ubuntu 22.04
- Database: PostgreSQL
- Node.js version: 18.13.0

**Comment by nikkhn** [comment]
> Hi everyone! Could you check if updating `prisma` and `@prisma/client` to `4.12.0-integration-rtld-deepbind.3` fixes the issue for you? It would be very helpful to test this on more different systems.
> 
> This is an experimental dev version not intended for production but if it works as expected, we'll work on making this land in a stable release. Thank you!

This worked for me as well thank you!!
