### ISSUE TITLE
db pull error

### ISSUE THREAD

**Issue by sg-maqib** [prisma/prisma#17235]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.18.1           | 
| Prisma CLI  | 4.8.1              | 
| Engine      | d6e67a83f971b175a593ccc12e15c4a757f93ffe| 

## Error
```
Error: [libs\sql-schema-describer\src\mssql.rs:290:33] called `Result::unwrap()` on an `Err` value: "Getting namespace from Resultrow ResultRow { columns: [\"column_name\", \"data_type\", \"character_maximum_length\", \"column_default\", \"is_nullable\", \"is_identity\", \"table_name\", \"constraint_name\", \"numeric_precision\", \"numeric_scale\", \"namespace\"], values: [Text(Some(\"ID\")), Text(Some(\"bigint\")), Int32(None), Text(None), Boolean(Some(false)), Int32(None), Text(None), Text(None), Int32(Some(19)), Int32(Some(0)), Text(None)] } as String failed"
```

**Comment by mcbethio** [comment]
Hey @sg-maqib, It would make our life easier to reproduce (and then fix) if you could possibly share your db schema with us and which database/version you are using. 

Thanks

**Comment by jkomyno** [comment]
Hey @sg-maqib, could you please share your Prisma schema and your database kind and version? Otherwise, we won't be able to investigate this issue. Thanks!

**Comment by jkomyno** [comment]
Hey @sg-maqib, did you happen to see the comment above? We would need more info to investigate this issue.
