### ISSUE TITLE
Issue properly keeping the prisma2 @prisma/client out of the client side bundle in Next.js

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#1725]
I'm just quoting's @flybayer's [message](https://prisma.slack.com/archives/CKQTGR6T0/p1582859798094200) from the Prisma Slack turning it into a public GitHub issue

> We’re currently having an issue properly keeping the prisma2 `@prisma/client` out of the client side bundle in Next.js, (using it from `getServerSideProps`).
> 
> The Blitz core and example code on the canary branch works properly in production, but not in development.
> - [Here’s the code](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/controller.ts#L12) where `@prisma/client` is required from blitz core
>
> [This blog post](https://arunoda.me/blog/ssr-and-server-only-modules) shows different ways to do this, but none of them are working when an npm package is requiring @prisma/client.
> 
> - [This comment describes our current issue.](https://github.com/blitz-js/blitz/issues/13#issuecomment-592287586)
> - [This PR shows the hack we have to use right now](https://github.com/blitz-js/blitz/pull/19/files) to get it working in development

![image](https://user-images.githubusercontent.com/4058327/75526289-c5575400-5a11-11ea-938a-9c650ef8c6ce.png)

**Comment by flybayer** [comment]
Good news: I found a good solution for this!

1. `yarn install null-loader`
2. Add the following to `next.config.js`

```
module.exports = {
  webpack(config, { isServer }) {
    if (!isServer) {
      // Ensure prisma client is not included in the client bundle
      config.module.rules.push({
        test: /@prisma\/client/,
        use: "null-loader",
      })
    }
    return config
  },
}

```

**Comment by pantharshit00** [comment]
Hey @flybayer,

Now that Next.js 9.3 is out, can you please confirm that you are able to still reproduce this. 

If yes, can you share a minimal reproduction in a Git repository? If you can also configure that reproduction with webpack bundle analyzer, that would be super nice.

**Comment by flybayer** [comment]
I'm no longer having this issue! It can be closed
