### ISSUE TITLE
Promise types are not unwrapped properly when using async/await in WebStorm

### ISSUE THREAD

**Issue by fubhy** [prisma/prisma#17266]
### Bug description

Return types on PrismaClient are not unwrapped unless you use `foo.then()` manually instead of `await foo` essentially making Prisma unusable in WebStorm.

WebStorm seems to do some custom Promise & async/await handling instead of using the standard TypeScript language service for that.

JetBrains issue: https://youtrack.jetbrains.com/issue/WEB-59004

PR for a hotfix within Prisma:  https://github.com/prisma/prisma/pull/17265

### How to reproduce

1. Check out https://github.com/prisma/prisma-examples
2. Install any of the typescript examples in that repository (with npm, pnpm, yarn, whatever you prefer)
4. Generate the prisma client (e.g. npx prisma generate)
5. Open the example project in webstorm
6. Any of the await'ed returns of any of the functions called on the PrismaClient instance returns the promise still instead of the underlying, unwrapped object

### Expected behavior

They are not unwrapped unless you use foo.then() manually instead of await foo essentially making Prisma unusable in WebStorm.

### Prisma information

Any example from `prisma/prisma-examples` works to reproduce this.

### Environment & setup

IDE: WebStorm or any other JetBrains IDE with TypeScript support

### Prisma Version

4.8.1

**Comment by H4mor** [comment]
I'm still having this problem. Was it really fixed?
I have prisma 5.15.1 and webstorm 2023.3.7

**Comment by dexsper** [comment]
I have prisma 5.22.0 and webstorm 2023.3.2
I'm still having this problem.
