### ISSUE TITLE
On Raspbian 64 bit (aarch64) tries to install linux-arm-openssl-1.1.x which cannot be found

### ISSUE THREAD

**Issue by pimmesz** [prisma/prisma#17284]
### Bug description

On Raspbian 64 bit (aarch64) tries to install linux-arm-openssl-1.1.x which cannot be found.

In your [release notes](https://newreleases.io/project/github/prisma/prisma/release/2.14.0) you've stated `binaryTargets = ["linux-arm-openssl-1.1.x"]`. However new I look for those binaries in your [documentation](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#binarytargets-options) I can only find `linux-arm64-openssl-1.1.x`.

Is there a solution which forces it to point to the correct binary?

### How to reproduce

1. Raspberry Pi with Raspbian 64 bit (aarch64)
2. Run any Prisma related command
3. See error `> Downloading Prisma engines for Node-API for linux-arm-openssl-1.1.x [                    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/linux-arm-openssl-1.1.x/prisma-fmt.gz`

### Expected behavior

It works

### Prisma information

```
> Downloading Prisma engines for Node-API for linux-arm-openssl-1.1.x [                    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/linux-arm-openssl-1.1.x/prisma-fmt.gz
```

### Environment & setup

- OS: Raspbian 64 bit
- Database: SQLite
- Node.js version: v18.12.0

``` schema.prisma
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["linux-arm64-openssl-1.1.x"]
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Video {
  id             String @id
  publishedAt    String
  title          String
  thumbnails     String
  viewCount      String
}
```

### Prisma Version

```
4.8.1
```

**Comment by jkomyno** [comment]
Hi @pimmesz, what happens if you remove the `binaryTargets` from your schema entirely?

**Comment by Jolg42** [comment]
This is a 404
https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/linux-arm-openssl-1.1.x/prisma-fmt.gz

This exists
https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/linux-arm64-openssl-1.1.x/prisma-fmt.gz

Not that the `binaryTargets = ["linux-arm64-openssl-1.1.x"]` property in the Prisma schema only affects the Query Engine download. So this property is unrelated to the `prisma-fmt` error here.


A workaround would be to set this env var before running `npm install`
```
PRISMA_CLI_BINARY_TARGETS=linux-arm64-openssl-1.1.x
```

Though it should normally not be needed and we want to investigate this, code is here https://github.com/prisma/prisma/blob/1a17fdf5520c287d926c4e92049a163adbe19877/packages/get-platform/src/getPlatform.ts#L289-L297

**Comment by Jolg42** [comment]
@pimmesz Could you confirm that the workaround I mentioned works?

**Comment by pimmesz** [comment]
@Jolg42 still getting the same.

``` schema.prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Video {
  id             String @id
  publishedAt    String
  title          String
  thumbnails     String
  viewCount      String
}
```
On `Linux 5.15.84-v8+ aarch64`
1) `echo $PRISMA_CLI_BINARY_TARGETS`returns `linux-arm64-openssl-1.1.x`. 
2) Removed `node_modules`
3) Run `npm install`
4) Run `npx prisma generate`
5) Receive error `Error: Not Found https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/linux-arm-openssl-1.1.x/prisma-fmt.gz`

**Comment by pimmesz** [comment]
`node -e 'console.log(process.arch)'` returns `arm`for me. Perhaps issue with `node` not correctly recognizing which arch is used?

**Comment by pimmesz** [comment]
But that still means that [linux-arm-openssl-1.1.x images on binaries.prisma.sh](https://github.com/prisma/ecosystem-tests/pull/3375) should be available I think.

**Comment by Jolg42** [comment]
@pimmesz Thanks for the additional info!
I think we got enough info to investigate with that 🙌🏼 

Could you try this workaround for now:
- download the engines manually from https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/linux-arm64-openssl-1.1.x/prisma-fmt.gz (change the name of the engine file at the end to get other engines)
- set the following env vars with the correct path to the related engines:
```
PRISMA_FMT_BINARY=folder/my-format-engine
# I think these below will also be needed (please confirm)
PRISMA_QUERY_ENGINE_LIBRARY=folder/libquery_engine-<target>.so.node
PRISMA_INTROSPECTION_ENGINE_BINARY=folder/my-introspection-engine
PRISMA_MIGRATION_ENGINE_BINARY=folder/my-migration-engine
```

**Comment by pimmesz** [comment]
Seems to get a bit further. Currently breaking on 

```
Error: Unable to establish a connection to query-engine-node-api library. It seems that the current architecture arm is not supported, or that libc is missing from the system.
Details: Unable to require(`/home/pi/prisma-binaries/libquery_engine.so.node`)
 /home/pi/prisma-binaries/libquery_engine.so.node: wrong ELF class: ELFCLASS64
[Context: getDmmf]
```

**Comment by Jolg42** [comment]
Note: adding support for Linux ARM 32bit is tracked in https://github.com/prisma/prisma/issues/5379

(Though since Raspbian has a 64 bit version, it's the one currently recommended.)

**Comment by pimmesz** [comment]
@Jolg42 thank you! After fully reinstalling 64 bit OS it finally detects well and it works! I think the issue for incorrect detection still stands but 64 bit works perfectly! Thank you.

**Comment by jkomyno** [comment]
Closing this as OP solved their problem with the provided suggestion.
