### ISSUE TITLE
Error: [libs\sql-schema-describer\src\mssql.rs:336:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `\r\ncreate default [va_nulla] as 0\r\n`" 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#17292]
Command: `prisma introspect`
Version: `4.8.1`
Binary Version: `d6e67a83f971b175a593ccc12e15c4a757f93ffe`
Report: https://prisma-errors.netlify.app/report/14503 
OS: `x64 win32 10.0.19045`

JS Stacktrace:
```
Error: [libs\sql-schema-describer\src\mssql.rs:336:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `\r\ncreate default [va_nulla] as 0\r\n`"
```

---

In [here](https://github.com/prisma/prisma-engines/blob/4.8.1-dev.1/libs/sql-schema-describer/src/mssql.rs#L329-L336), we have:

```rust
  let default_string = DEFAULT_NON_STRING
      .captures_iter(&default_string)
      .next()
      .or_else(|| DEFAULT_STRING.captures_iter(&default_string).next())
      .or_else(|| DEFAULT_DB_GEN.captures_iter(&default_string).next())
      .map(|cap| cap[1].to_string())
      .ok_or_else(|| format!("Couldn't parse default value: `{}`", default_string))
      .unwrap();
```

**Comment by jkomyno** [comment]
This was already happening in `prisma@3.15.2`: https://prisma-errors.netlify.app/report/14761

**Comment by jkomyno** [comment]
Other report (from a user): https://github.com/prisma/prisma/issues/19971

**Comment by janpio** [comment]
We still do not know how to make Introspection crash because of the existence of such an index. 
We need a SQL dump of a database that reproduces this behavior to replicate this behavior.

(For us the default is just ignored and not represented in the Prisma schema: https://github.com/prisma/prisma/issues/12150)

**Comment by janpio** [comment]
Reproduced: The line breaks cause this, see https://github.com/prisma/prisma/issues/24275
