### ISSUE TITLE
Prisma Client `metrics`: Undocumented Metric counter & gauge

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#17302]
### Bug description

When metrics are gotten via `$metrics.json()` there are two metrics that appear at runtime but not documented.

1. A `counter` called (the key) `prisma_pool_connections_open`.
2. A `gauge` called (the key) `prisma_pool_connections_opened_total`

It is not clear to me if the docs are wrong/out of date or if it is a bug with Prisma Client.

Note that the above names (the key) are already used in other metric types (`prisma_pool_connections_opened_total` is a `counter` and `prisma_pool_connections_open` is a `gauge`). The fact that there were duplicate key names is confusing. @rtbenfield and I also suspect it might be confusing HoneyComb (but not sure/confirmed).

### How to reproduce

AFAICT just try out `$metrics.json()` and you're going to see this happen right away.

### Expected behavior

Not sure actually.

### Prisma information

N/A

### Environment & setup

N/A

### Prisma Version

```
4.8
```

**Comment by barryhagan** [comment]
There is a bug causing the gauge and counter for open connections to be flipped in the connection manager, and that surfaces in the metrics.
https://github.com/prisma/mobc/blob/main/src/lib.rs#L544

**Comment by janpio** [comment]
That looks promising @barryhagan. Also means our tests in that area are not adequate :/

**Comment by janpio** [comment]
Metrics are still a preview feature: 
> We don't recommend using Preview features or products in production.
https://www.prisma.io/docs/about/prisma/releases#preview

**Comment by barryhagan** [comment]
This is resolved as of 5.3.0, as someone finally PR'd the typo bug in mobc.  https://github.com/prisma/prisma/issues/18761

> Also means our tests in that area are not adequate :/

The tests in that area remain inadequate.

**Comment by janpio** [comment]
> The tests in that area remain inadequate.

PRs welcome.
