### ISSUE TITLE
Schema should use OS style line breaks (instead of always `\n`)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1733]
When you run `introspect` on a Windows machine, the schema that is output still uses \n for line breaks. This could lead to problems for software that uses `os.EOL` to split lines (as e.g. `prisma-test-utils-automation` currently does, where I discovered this problem).

**Comment by pantharshit00** [comment]
Do we really need this? I will mark this as a feature though now after reading this again can be a part of introspection config if that becomes a thing in future.

**Comment by janpio** [comment]
On Windows the local file should be output with Windows line breaks - it can then be normalized by Git when committing it to the repo if normalization is wanted. But outputting just `\n` on Windows is technically not correct.
