### ISSUE TITLE
Deeply nested objects aren't typed when clientExtensions is enabled

### ISSUE THREAD

**Issue by TaylorFacen** [prisma/prisma#17349]
### Bug description

Originally, I ran into the `RangeError: Maximum call stack size exceeded` error when trying to build my application. Using prisma version `4.9.0-integration-feat-client-ext-generic-type-api.13` as mentioned in #16600 resolved that issue. However, I am now running into an issue where deeply nested objects aren't included in my object types. 

### How to reproduce

Using the schema and code listed below, run pnpm run build. The following error is logged to the console

```
Type error: Property 'item' does not exist on type '{ id: string;  name: string; plaidItemId: string; }'.
```

### Prisma information

```prisma
model PlaidInstitution {
  id                          String      @id
  name                        String
  logoUrl                     String?     @map("logo_url")
  items                       PlaidItem[]
  @@map("plaid_institutions")
}

model PlaidItem {
  id                          String      @id
  institutionId               String      @map("institution_id")
disabledAt                  DateTime?   @map("disabled_at")
  institution     PlaidInstitution        @relation(fields: [institutionId], references: [id], onDelete: Restrict)

  accounts                    PlaidAccount[]

  @@map("plaid_items")
  @@index([institutionId])
}

model PlaidAccount {
  id                          String      @id
  plaidItemId                 String      @map("plaid_item_id")
  name                        String
  destinations                Destination[] 
  item                        PlaidItem   @relation(fields: [plaidItemId], references: [id], onDelete: Cascade)
  @@map("plaid_accounts")
  @@index([plaidItemId])
}

model Destination {
  id                          String      @id @default(uuid())
  integration                 String
  name                        String
  accounts                    PlaidAccount[]
  
  @@map("destinations")
}
```

```ts
const destination = await db.destination.findFirst({ 
    include: { 
      accounts: { where: { item: { disabledAt: null } }, include: { item: { include: { institution: true }} }},
    }
  });
```

### Environment & setup

- OS: macOS
- Database: PlanetScale
- Node.js version: v16.17.0

### Prisma Version

```
10.1.0
```

**Comment by Multiply** [comment]
As [mentioned here](https://github.com/prisma/prisma/issues/16600#issuecomment-1368540419), I'm having the same issue.

**Comment by TaylorFacen** [comment]
By the way, I just downgraded my application back to v4.8.1 and removed clientExtensions and my app is able to build without an issue.

**Comment by millsp** [comment]
This has been fixed on `dev`, you can try it out by installing [4.9.0-dev.70](https://www.npmjs.com/package/@prisma/client/v/4.9.0-dev.70), or wait until the release tomorrow. Thanks for reporting this issue.

**Comment by TaylorFacen** [comment]
> This has been fixed on `dev`, you can try it out by installing [4.9.0-dev.70](https://www.npmjs.com/package/@prisma/client/v/4.9.0-dev.70), or wait until the `4.9.0` release tomorrow. Thanks for reporting this issue.

Hi, I just tried to install, but I'm running into the same error

**Comment by TaylorFacen** [comment]
I tried 4.9.0-dev.72 and that didn’t work either.

**Comment by ABitShift** [comment]
I am facing the exact same issue, the same version installed flow were tested

* `RangeError: Maximum call stack size exceeded` - on 4.8.1 with prisma extension preview enabled
* deeply select / includes type error - on 4.9.0 with prisma extension preview enabled

**Comment by jove4015** [comment]
@millsp  - This bug is marked resolved, however, client extensions still are not usable (see https://github.com/prisma/prisma/issues/17767).  Is there any progress on making this feature functionally available?

**Comment by millsp** [comment]
Hey @jove4015, the fix will be release tomorrow. If you want, you can install `@prisma/client@dev` to try it out. General availability for this feature will come once we have received enough feedback and fixed the bugs as well as missing features.
