### ISSUE TITLE
Nonsensical migration on partitioned tables

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17348]
> Given the following schema
> 
> ```prisma
> model User {
>   id             String          @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
>   username       String          
>   events         Event[]
>   myDomainEvents MyDomainEvent[]
> }
> 
> enum AggregateName {
>   MY_DOMAIN
> }
> 
> model Event {
>   id            Int           @default(autoincrement())
>   aggregateName AggregateName
>   type          String        @db.VarChar(100)
>   aggregateId   String        @db.Uuid
>   originatorId  String        @db.Uuid
>   originator    User          @relation(fields: [originatorId], references: [id])
> 
>   @@id([aggregateName, id])
> }
> 
> model MyDomainEvent {
>   id            Int           @default(autoincrement())
>   aggregateName AggregateName
>   type          String        @db.VarChar(100)
>   aggregateId   String        @db.Uuid
>   originatorId  String        @db.Uuid
>   originator    User          @relation(fields: [originatorId], references: [id])
> 
>   @@id([aggregateName, id])
> }
> ```
> 
> and the following manually (via `prisma migrate dev --create-only`) written migration that does create an SQL schema matching the prisma schema 
> 
> ```sql
> -- EnsureExtension
> CREATE EXTENSION IF NOT EXISTS pgcrypto;
> 
> -- CreateTable
> CREATE TABLE "User" (
>     "id" UUID NOT NULL DEFAULT gen_random_uuid(),
>     "username" TEXT NOT NULL,
> 
>     CONSTRAINT "User_pkey" PRIMARY KEY ("id")
> );
> 
> -- CreateEnum
> CREATE TYPE "AggregateName" AS ENUM ('MY_DOMAIN');
> 
> -- CreateTable
> CREATE TABLE "Event" (
>     "id" SERIAL NOT NULL,
>     "aggregateName" "AggregateName" NOT NULL,
>     "type" VARCHAR(100) NOT NULL,
>     "aggregateId" UUID NOT NULL,
>     "originatorId" UUID NOT NULL,
> 
>     CONSTRAINT "Event_pkey" PRIMARY KEY ("aggregateName","id")
> ) PARTITION BY LIST("aggregateName");
> 
> -- AddForeignKey
> ALTER TABLE "Event" ADD CONSTRAINT "Event_originatorId_fkey" FOREIGN KEY ("originatorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
> 
> -- CreatePartitionedTable
> CREATE TABLE "MyDomainEvent" PARTITION OF "Event" FOR VALUES IN ('MY_DOMAIN');
> 
> -- AddForeignKey
> ALTER TABLE "MyDomainEvent" ADD CONSTRAINT "MyDomainEvent_originatorId_fkey" FOREIGN KEY ("originatorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
> ```
> 
> prisma auto generates the following nonsensical migration that fails to execute because it cannot read the keys of the partitioned table correctly when trying to execute the above migration with `prisma migrate dev`
> 
> ```sql
> -- AlterTable
> ALTER TABLE "Event" ADD CONSTRAINT "Event_pkey" PRIMARY KEY ("aggregateName", "id");
> 
> -- RenameForeignKey
> ALTER TABLE "MyDomainEvent" RENAME CONSTRAINT "Event_originatorId_fkey" TO "MyDomainEvent_originatorId_fkey";
> ```
> 
> see reproduction here: https://github.com/MrLoh/prisma-partitioned-table-example/tree/master

_Originally posted by @MrLoh in https://github.com/prisma/prisma/issues/10870#issuecomment-1141554329_

**Comment by janpio** [comment]
Thanks for the excellent information @MrLoh. I quickly tried to reproduce this, but get a different result than you:

With your SQL from above I get the following Prisma schema via `db pull`:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model MyDomainEvent {
  id            Int           @default(autoincrement())
  aggregateName AggregateName
  type          String        @db.VarChar(100)
  aggregateId   String        @db.Uuid
  originatorId  String        @db.Uuid
  User          User          @relation(fields: [originatorId], references: [id], map: "Event_originatorId_fkey")

  @@id([aggregateName, id])
}

model User {
  id            String          @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  username      String
  MyDomainEvent MyDomainEvent[]
}

enum AggregateName {
  MY_DOMAIN
}
```

I then added the SQL as a migration and `migrate resolve --applied` it so the migration history knows about it. When I now run `migrate dev --create-only` I get the following drift warning:

```
Drift detected: Your database schema is not in sync with your migration history.

The following is a summary of the differences between the expected database schema given your migrations files, and the actual schema of the database.

It should be understood as the set of changes to get from the expected schema to the actual schema.

[*] Changed the `MyDomainEvent` table
  [*] Renamed the foreign key "MyDomainEvent_originatorId_fkey" to "Event_originatorId_fkey"
```

The underlying problem here seems to be the mismatch that is already visible above in the `MyDomainEvent` model: Prisma thinks its foreign key name (`map` in the `@relation`) to be `Event_originatorId_fkey` instead of the correct `MyDomainEvent_originatorId_fkey`. During `migrate dev` it then gets further confused somehow.

Generally this is not super surprising as partitioned tables are not supported yet at all (see feature request https://github.com/prisma/prisma/issues/1708), and as part of that the different parts of Prisma get confused and do things that just do not work. 

But for me it would now be interesting to understand why I am seeing different things than what you reported. Could you maybe give this another pass with a newer Prisma version?

**Comment by janpio** [comment]
Explanation is that I was using a different Prisma version than @MrLoh probably did back then: https://github.com/prisma/prisma/issues/10870#issuecomment-1384442453

**Comment by janpio** [comment]
But, even with version 3.7.0 from the original issue, I unfortunately can not get Prisma to produce any migration - as I always get a drift warning.

Assuming it would produce the migration from above, I could explain what is happening though: 
The initial introspection does not pick up the `@@id` on the table (for whatever reason) so it thinks it needs to add that when you manually added that to the schema. And the foreign key name that it tries to change is the same that triggers the drift warning for me - so it also thinks it to be different than it is.

**Comment by janpio** [comment]
We improved Introspection for partitioned tables in 4.10.0, optimally this would also have a positive impact on this. Please test it and let us know. Thanks!

**Comment by millsp** [comment]
Hey @MrLoh, as Jan pointed out, we have made some improvements to this. Could you please give it a try and let us know? Thanks.

**Comment by millsp** [comment]
Hey @MrLoh,

Did you get a chance to have a look at my previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by MrLoh** [comment]
It seems that Prisma can now ignore the partitioned table, allowing to have the `Event` model of the above example defined in the schema and a partitioned table to exist. Still, it is **not** possible to have the partitioned table accessible via Primsa yet. But that's some good progress for sure.

**Comment by janpio** [comment]
Can you describe the current state and problem with it a bit more again please @MrLoh?

We know that partitioned tables can not by default be created and managed by Prisma, which is why we have this feature request: https://github.com/prisma/prisma/issues/1708 But optimally that should not keep you from doing something that you already want to do with these in the meantime when they have been created manually. We just might need some more detail so we are sure we understand properly.

**Comment by MrLoh** [comment]
Yeah you can have the partitioned table in the prisma Schema and make a manual migration to create the partition that will be ignored by prisma. But there is no way to interact with a single partition of the table via prisma.

**Comment by MrLoh** [comment]
I think it's fine to close this issue since proper partition support is tracked in the other one.
