### ISSUE TITLE
[Stopgap] Introspect partitioned tables better: Only introspect main table in a valid way, ignore partitions

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17351]
Part of https://github.com/prisma/prisma/issues/16311

https://github.com/prisma/prisma/issues/10870 and https://github.com/prisma/prisma/issues/17348 showed that in the past Prisma introspected the main table and its partitions (main table was `@@ignore` as no primary key was picked up) at the same time. Reproduction of these issues showed that today only the partitions are introspected and the main table is actually missing. 
When running `migrate dev --create-only`  in the past it created nonsensical migrations, and today fails with a drift warning as it gets confused about the partitions and the main table and tries to change things into a state that it already has.

A clean stopgap solution for this would probably be:
1. Make sure to only introspect the main table with its foreign keys into a model and relations
2. Completely ignore the partitions and do not render them or their relations at all
3. Warn during Introspection that a partitioned tables was detected, but can not be represented in Prisma schema - so the partition information needs to be added manually when using `migrate dev` to generate a migration SQL
4. Because of 2) there should be no more problems when running `migate dev` and no drift should be detected

This way users should by default not have any breakage, and can add the partition information (and foreign keys etc) manually to the generated SQL to achieve the full functionality - without Prisma being able to express partitions in Prisma schema already (which will be covered via #1708 in the future).

**Comment by MrLoh** [comment]
I think ignoring the partition tables is also a good setup gap
