### ISSUE TITLE
[ClientExtensions, TypeScript] Fields of custom type aren't available when using the ClientExtensions preview-feature, unless `select`'d explicitly. 

### ISSUE THREAD

**Issue by ItzSiL3Nce** [prisma/prisma#17388]
### Bug description

Only when the `clientExtensions` preview-feature is enabled (just by enabling it, no need to define custom extensions), fields of a user-defined custom `type` aren't available after querying the model, unless `select`'d explicitly. 
Note: They are available at runtime, only TypeScript doesn't have them, I'm using the MongoDB as the db `provider`. Also, might be related to #17349, but not sure.

### How to reproduce

Simply create a Prisma `model` that has one or more fields of an user-defined `type`. That field won't be available (TypeScript's types only, it **is** available at runtime) unless it was explicitly `select`d. Full example shown below.

### Expected behavior

Every field (TypeScript) should be available after executing a query, including the ones of custom types. Just like it is when **not** using the `clientExtensions` preview-feature.

### Prisma information

# schema.prisma

```prisma
type CustomType {
  data         String
  otherThings  String
  // ...
}

model ExampleUser {
  id        String @id @default(auto()) @map("_id") @db.ObjectId
  username  String
  password  String
  // ...
  otherData CustomType?
}
```

# Using the prisma client
```typescript
import { PrismaClient } from '@prisma/client'

const client = new PrismaClient()

async function main() {
  await client.$connect()
  
  const userNotWorking = await client.exampleUser.findFirst({ 
    where: {
      username: 'test-user'
    } 
  })

 // @ts-expect-error : Here the `otherData` field is not present inside the `userNotWorking` object.
 const dataNotWorking = userNotWorking.otherData

 // To make it work, the query needs `select` to be added with all the fields wanted.
  const user = await client.exampleUser.findFirst({ 
    where: {
      username: 'test-user'
    },
   select: {
      otherData: true
   }
  })


 // Here the `otherData` field is present inside the `user` object.
 const data = user.otherData
}

main()
  .catch(console.error)
  .finally(() => {
    client.$disconnect()
  })
```

### Environment & setup

- OS: Ubuntu
- Database: MongoDB
- Node.js version: Both 14.20.0 and 18.13.0 (LTS)
- Preview Features: clientExtensions
- Typescript: 4.9.4

### Prisma Version

```
prisma                  : 4.9.0
@prisma/client          : 4.9.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at ../../node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at ../../node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at ../../node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at ../../node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.9.0-42.ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Default Engines Hash    : ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Studio                  : 0.479.0
Preview Features        : clientExtensions
```

**Comment by millsp** [comment]
Thanks for the report! I can confirm this as we were conscious that in this first iteration we wouldn't yet support MongoDB's composite types.

**Comment by pheuter** [comment]
This issue is currently preventing me from trying out my early access to Prisma Accelerate, looking forward to client extensions support composite types 👀
