### ISSUE TITLE
Regression: `get-platform` error for non-`amd64` Alpine introduced in `prisma@4.9.0` prevents using custom Prisma engines

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#17390]
As stated by [this comment](https://github.com/prisma/prisma/pull/17334#issuecomment-1386451802), the new error introduced for non-`amd64` Linux Alpine in https://github.com/prisma/prisma/pull/17334 prevents users from using their own custom engines, (which e.g. may be compiled explicitly for `arm64` to circumvent https://github.com/prisma/prisma/issues/8478).

From [Slack](https://prisma-company.slack.com/archives/C04DG9JL6TV/p1674029182666039):
> That isn’t something we’ve ever supported explicitly or told people to do, is it?

> I think it is, we have a page in documentation about using custom engines (although not about building them), and we also told people in that issue that building the engines themselves is one of the workarounds

**Comment by Jolg42** [comment]
@jkomyno I deleted the `4.9.1` milestone as we do not create milestones for patch releases
And I'm unsure this deserves a patch release too, we need to evaluate the number of impacted users for this first.
