### ISSUE TITLE
after install client (npm install @prisma/client) causing some windows file lock issue 

### ISSUE THREAD

**Issue by betimer** [prisma/prisma#17439]
### Bug description

I think I notice an issue (should be a bug)
Each project after running npm install @prisma/client
sam build will crash with the following.

I have tested many times that I keep getting this issue (via `sam build`) (sam is a aws serverless framework)
```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 
'C:\\Users\\betim\\AppData\\Local\\Temp\\tmpfvrgu56z'
```

If I remove the package, all works as before.

So I would like to know if the @prisma/client has some permission or lock file issue, and this should be a bug to fix.

Thank you.

### How to reproduce

1. `npm install @prisma/client`
2. `sam build` 

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Windows 11
- Database: PostgreSQL
- Node.js version: 18.13.0

### Prisma Version

```

```

**Comment by janpio** [comment]
Can you leave more information on how to produce the issue? How does the project have to look like before for this to be triggered?

**Comment by Weakky** [comment]
Hey @betimer,

Thanks for the additional info. Could you provide us with a reproduction repo? It'd be really helpful to move this issue forward.

Thank you 🙏

**Comment by jharrell** [comment]
Hi @betimer

Just following up. Could you provide a reproduction repo? We're more than happy to move this forward with a bit more info. 

Thanks!
