### ISSUE TITLE
`prisma generate --watch` generates only once, then hangs

### ISSUE THREAD

**Issue by dtnmr** [prisma/prisma#17453]
### Bug description

When running `prisma generate --watch` with the intent of having the client being rebuilt in the background when the schema changes, it seems like only the first edit to the schema triggers a rebuild, and then the script seems to hang indefinitely.

My OS is Linux (Arch) and I get the `prisma:warn Prisma failed to detect the Linux distro in use, and may not work as expected. Defaulting to "debian".` message.

### How to reproduce

1. Create a minimal repro using [step 1 of the getting started guide](https://www.prisma.io/docs/getting-started/quickstart#1-create-typescript-project-and-set-up-prisma).
2. Add a dummy model to the schema
	```
	model User {
	  id    Int     @id @default(autoincrement())
	  email String  @unique
	  name  String?
	}
	```
3. Run `DEBUG="*" npx prisma generate --watch `
4. Edit and save the schema, schema is rebuilt like expected
5. Edit and save the schema a second time, nothing happens

### Expected behavior

`prisma generate -- watch` should attempt to rebuild the client upon any meaningful edit.

### Prisma information

CLI Output with DEBUG="*", when making 4 edits to the schema ->  [repro.log](https://github.com/prisma/prisma/files/10469431/repro.log).

### Environment & setup

- OS: Linux 6.1.6 (Arch)
- Database: SQLite
- Node.js version: 18.12.1

### Prisma Version

```
prisma                  : 4.9.0
@prisma/client          : 4.9.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.9.0-42.ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Default Engines Hash    : ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Studio                  : 0.479.0
```

**Comment by souvikinator** [comment]
Facing a similar issue. It works fine while using with NextJs but when I use it with ExpressJs, it throws the same warning.

## Environment & setup
OS: Manjaro KDE Plasma
Database: MongoDB
Node.js version: v19.3.0

**Comment by dtnmr** [comment]
I ran https://github.com/mikesart/inotify-info to rule out inotify issues, and nothing seems wrong on that front since I am far from the limits before, while, and after running `prisma generate --watch`.

```  ------------------------------------------------------------------------------
INotify Limits:
  max_queued_events    16384
  max_user_instances   1024
  max_user_watches     524288
------------------------------------------------------------------------------
        Pid  App                        Watches   Instances
        5144 node                           149   1
        5174 node                            48   1
        5203 node                            39   1
        6409 systemd                         34   3
        6594 xdg-desktop-portal-gtk          26   1
        3206 node                            24   1
        7030 electron                        16   1
        5265 node                             9   1
       13820 firefox                          5   1
        6416 easyeffects                      4   1
        6547 Discord                          3   1
        6661 spotify                          3   1
        6548 slack                            3   1
        6544 electron                         3   1
        6419 wireplumber                      3   3
        6430 dbus-daemon                      2   1
        6873 spotify                          2   1
        7015 electron                         2   1
        7066 Discord                          2   1
        7194 slack                            2   1
        6528 xdg-desktop-portal               1   1
        6525 picom                            1   1
        6643 dbus-daemon                      1   1
        5267 node                             1   1
      588696 alacritty                        1   1
      591959 alacritty                        1   1
      592824 alacritty                        1   1
------------------------------------------------------------------------------
Total inotify Watches:   386
Total inotify Instances: 31
------------------------------------------------------------------------------
```

I should also add that on a fresh boot of my machine, I am able to generate the client about 10 times before the script stops reacting to changes.

**Comment by dtnmr** [comment]
Well, pack it up.

My editor's default backup strategy on file save was to rename the existing file effectively making it the backup, and create a new one for the "final changes", essentially changing the inode of the file that is watched, which is why inotify was not aware of any change.

This default behavior is based on heuristics which is why the number of attempts before changes were taken into account was varying.

If you encounter the same issue, I suggest you look into customizing the behavior of your editor in that regard.

In my case (nvim) I had to use `:set backupcopy=yes`.  (`vim.o.backupcopy = "yes"` in lua). 

Maybe this is your fix @souvikinator.
