### ISSUE TITLE
Client extensions incorrect typings when defined both specific model and all models methods

### ISSUE THREAD

**Issue by tekihei2317** [prisma/prisma#17458]
### Bug description

Prisma client produces a compile error when using `$allModels` method if I defined a specific model method too. It seems that a model which has specific model methods cannot use `$allModels` methods.

### How to reproduce

https://github.com/tekihei2317/prisma-pagination-example/blob/main/scripts/query.ts#L12

Here’s repro repo.

I defined a `signUp` method to the user model, and a `paginate` method to all models. `xprisma.post.paginate` works well but `xprisma.user.paginate` produces a compile error that the `paginate` property does not exist.

### Expected behavior

Models have both specific model methods and `$allModels` methods. In the previous example, `xprisma.user` has both `signUp` and `paginate`.

### Prisma information

```prisma
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int      @id @default(autoincrement())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
  createdAt DateTime @default(now())
}
```

```ts
import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export const xprisma = prisma.$extends({
  model: {
    user: {
      async signUp(email: string) {
        await prisma.user.create({ data: { email } });
      },
    },
    $allModels: {
      async paginate<T, A>(
        this: T,
        args: Prisma.Exact<A, Prisma.Args<T, "findMany">> & {
          page: number;
          perPage: number;
        }
      ): Promise<Prisma.Result<T, A, "findMany">> {
        const { page, perPage } = args;

        return await (this as any).findMany({
          ...omit(args, "page", "perPage"),
          skip: perPage * (page - 1),
          take: perPage,
        });
      },
    },
  },
});

// ok
const posts = await xprisma.post.paginate({
  where: { authorId: 1 },
  orderBy: { createdAt: "desc" },
  page: 1,
  perPage: 5,
});

// compile error
// Property 'paginate' does not exist on type 'GetModel<UserDelegate<RejectOnNotFound | RejectPerOperation | undefined, { result: {} & Record<string, {}>; model: {} & Record<string, { paginate: () => <T, A>(this: T, args: Exact<...> & { ...; }) => Promise<...>; }> & { ...; }; client: {}; query: {}; }>, { ...; }>'.ts(2339)
const users = await xprisma.user.paginate({
  page: 1,
  perPage: 5,
});
```

### Environment & setup

- OS: macOS
- Database: SQLite
- Node.js version: 16.18.0

### Prisma Version

```
4.9.0
```

**Comment by Jolg42** [comment]
@tekihei2317 Note: This is fixed in our main branch

If you want to try the `patch-dev` version `4.16.1-dev.7`, let us know if this version fixes the issues, we're curious to get any feedback 🙌🏼 

Note: do not use in production, wait for the official `4.16.1` patch for that, coming very soon!
