### ISSUE TITLE
Remove "Update available" notice from terminal

### ISSUE THREAD

**Issue by devklepacki** [prisma/prisma#17461]
## Problem

I'm always frustrated when there's an update to Prisma because you scream at me in my terminal.

I don't want to see that there's an update to Prisma every time I do something related to it. Maybe there's such an option but I haven't found it.

When I'm working on something (let's say a feature branch) and there's an update, I am constantly attacked with the notice. Devs know that they should keep their deps updated and once I have time, I can handle this myself.

There are specialized tools like `yarn outdated` and others, created especially for the purpose of checking if any dependency is outdated. We are not children who should be screamed at.

## Suggested solution

Add a config option or completely remove the aggressive
```
┌─────────────────────────────────────────────────────────┐
│  Update available 4.8.1 -> 4.9.0                        │
│  Run the following to update                            │
│    yarn add --dev prisma@latest                         │
│    yarn add @prisma/client@latest                       │
└─────────────────────────────────────────────────────────┘
```

notice from the terminal.

**Comment by janpio** [comment]
You might be looking for https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_hide_update_message

**Comment by devklepacki** [comment]
Thank you very much @janpio, sorry for making a little mess with opening the new issue, but I wasn't able to find this - somehow I was using wrong keywords in my searches.

Regarding aggressiveness, I always keep my terminal clean from all warnings and such, so this big of a message really is like screaming in my terminal. But yea I can see your point - similarly to popups on websites - people hate them, but they are still the most effective way to get data/attention from users.
