### ISSUE TITLE
I'm starting a project, where your database already exists, so in order not to create a new database, I chose to use the prism and when I run the npx prisma db pull command, to get the database tables it fails.

### ISSUE THREAD

**Issue by tecwagner** [prisma/prisma#17474]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v18.12.1           | 
| Prisma CLI  | 4.8.1              | 
| Engine      | d6e67a83f971b175a593ccc12e15c4a757f93ffe| 

## Error
```
Error: [libs/sql-schema-describer/src/mssql.rs:336:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `/*******************************************************************************\r\n  KPL SOLUÃiES LTDA\r\n  ------------------\r\n\r\n  Autor           : Anderson Vieira Duarte\r\n  Data da CriaþÒo : 09/2007\r\n  DescriþÒo       : Script SQL de alteraþ§es no DataBase utilizado pelo DATABASE\r\n  VersÒo          : 4.0.0120\r\n********************************************************************************/\r\n\r\nCREATE DEFAULT D_UM AS 1\r\n`"
```

**Comment by Jolg42** [comment]
@tecwagner Sorry for the delay, could you share a sql dump to we can attempt a reproduction?

**Comment by SevInf** [comment]
Hi @tecwagner, did you have a chance to look at @Jolg42  comment?

It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by SevInf** [comment]
Hey @tecwagner ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Comment by tecwagner** [comment]
Hello!
Regarding the problem, you can notice that the current database did not have migrations to be performed.
So to access the database tables it was necessary to use prisma.$queryRaw and write the script.
This was the way I solved the problem.
https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access

@SevInf  and @Jolg42
