### ISSUE TITLE
Support for binary type 

### ISSUE THREAD

**Issue by timgriffin89** [prisma/prisma#1747]
## Problem

PostgreSQL, MySQL and SQLite provide capabilities to store binary blobs:

* SQLite has a `BLOB` data type
* PostgreSQL has `bytea` and a _Large Object_ feature, which stores the binary data in a separate table in a special format, and refers to that table by storing a value of type OID in your table.
* MySQL has `BINARY` and `VARBINARY`

Prisma does not support these data types.

## Suggested solution

Add support for a binary type in PSL.

## Alternatives

@onmyflow describes a [workaround below](https://github.com/prisma/prisma/issues/1747#issuecomment-687239399).

## Additional context

* [MySQL 8 binary data type](https://github.com/prisma/prisma/issues/3040)
* [Supporting empty column type in SQLite during introspection](https://github.com/prisma/prisma/issues/3129)

## Original issue

Hi folks, I'm looking to store and access large arrays of binary data using PostgreSQL and Prisma, but it doesn't seem like the type that would make the most sense for my use case here (bytea) is supported by Prisma. Is there some possible workaround or plans to add this as a supported type?

**Comment by onmyflow** [comment]
Same question here. We need it for user avatars and it doesn't make sense to me to keep around a postgres (pg) connection just to fetch the avatars once in a while...

**Comment by albertoperdomo** [comment]
@onmyflow I think it's common practice to offload image storing to a filesystem, i.e. S3 and store the URL or file path in the DB. Is there any particular reason you have decided to store these images in the DB itself?

**Comment by albertoperdomo** [comment]
@timgriffin89 Is this data of a specific type, i.e. images? How large is this binary data? Have you considered storing this outside of the data? If you have discarded this option, can you expand on why?

**Comment by cappslock** [comment]
@albertoperdomo I can't speak to their use cases, but I can say that for quick prototypes or internal apps it can be convenient to centralize everything in postgres, particularly if file storage needs are limited and file sizes small and there are not many concurrent users. I'm not aware of any scenario where this is the _best_ thing to do, but there are places where it makes sense to save effort. It would be nice to have blobs as a supported type in Prisma.

**Comment by onmyflow** [comment]
@albertoperdomo what @cappslock  said. I'm aware of the implications that come with storing any kind of largish file in the db. But just because that might be a bad idea most of the times, the few times where one really needs to do stuff like this should be at least supported natively by just passing a Buffer to the field name and prisma handling the rest. My current solution is to base64 encode files, concatenate a raw query with that string and do a `decode()` inside of the SQL query. This solution, while working perfectly fine, has quite some performance overhead. That being said, i myself aren't too sure how one would implement it in a better way.

**Comment by albertoperdomo** [comment]
Thanks for following up with additional context @cappslock @onmyflow.

**Comment by albertoperdomo** [comment]
The workaround described by @onmyflow seems sensitive, albeit having performance overheads, for sure.
I think support for binary type could be covered by https://github.com/prisma/prisma/issues/3447. It's currently WIP, but I don't think it's in scope for the initial batch of native types we are adding.

**Comment by albertoperdomo** [comment]
Update: We actually consider #3447 the main issue to address native types. Will leave this issue around to track the request for binary especifically./

**Comment by Simonwep** [comment]
I second this, same case as @onmyflow's. Is this part of any roadmap? Or is this "included" in #3447 and supposed to be not be addressed in particular?

**Comment by mavilein** [comment]
@Simonwep @onmyflow : Binary types are available as part of the effort for native types. They have been shipped in Preview with the [2.11.0 release](https://github.com/prisma/prisma/releases/tag/2.11.0). Feedback is very much appreciated!

**Comment by albertoperdomo** [comment]
Binary types are now also supported in Prisma Migrate since 2.15.0 (in Preview). Documentation can be found [here](https://www.prisma.io/docs/concepts/components/preview-features/native-types/native-types-mappings#bytes).

**Comment by albertoperdomo** [comment]
Feedback for the native types feature can be shared here: https://github.com/prisma/prisma/issues/4045

**Comment by kentcdodds** [comment]
New URL for the byte type: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#bytes

**Comment by lambrospetrou** [comment]
Why is SQLite's `BLOB` not supported? I can see that it's the only one missing...
<img width="487" alt="Screenshot 2021-11-24 at 12 46 36" src="https://user-images.githubusercontent.com/2052105/143241191-57f5e62c-0c2c-44ef-99eb-1ba81a03d9a8.png">

**Comment by pantharshit00** [comment]
@lambrospetrou Please open a feature request for it. Then we can track that and add the mapping.

**Comment by lambrospetrou** [comment]
> @lambrospetrou Please open a feature request for it. Then we can track that and add the mapping.

I opened https://github.com/prisma/prisma/issues/10537 for tracking this. Thanks :)
