### ISSUE TITLE
`Type '"findUniqueOrThrow"' is not assignable to type 'PrismaAction'`

### ISSUE THREAD

**Issue by mejiaej** [prisma/prisma#17470]
### Bug description

Hey Guys,

I'm using the `Prisma.MiddlewareParams` type which contains an attribute `action` of type [PrismaAction](https://github.com/prisma/prisma/blob/731dce39919db180795fd923202a46d5ae833562/packages/client/src/generation/TSClient/PrismaClient.ts#L594-L610). Which is missing a couple of actions that actually exists `findUniqueOrThrow` and `findFirstOrThrow`

Because of that we get a ts error when using one of those missing types:
<img width="669" alt="Screen Shot 2023-01-22 at 19 32 25" src="https://user-images.githubusercontent.com/4699893/213948968-353d6273-fd3f-403c-b85e-3fc371d394a1.png">

### How to reproduce

Just add this code in a ts file and you'll see the error
```typescript
  const action : Prisma.PrismaAction = 'findUniqueOrThrow';
  console.log(action);
```

### Expected behavior

There shouldn't be a ts error because those actions do exists.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db" // env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}


model Planet {
  id        Int     @id @default(autoincrement())  
  name      String  
  diameter  String
  gravity   String
  terrain   String
  createdAt DateTime
  updatedAt DateTime?
  deletedAt DateTime?
}

```

```ts
import { Prisma } from '@prisma/client';

  const action : Prisma.PrismaAction = 'findUniqueOrThrow';
  console.log(action);
```

### Environment & setup

- OS: macOS
- Database: SQLite
- Node.js version: v16.14.0

### Prisma Version

```
 "@prisma/client": "^4.7.1",
```

**Comment by DoubleJ-G** [comment]
This is still an issue, any plan to add this? It seems like a simple fix in the type definitions

**Comment by shadoath** [comment]
I would second this. I ran into an issue now cause I thought I could count on this type as it said it would be.
