### ISSUE TITLE
`prisma2 generate` output message always says `You can now start using Prisma Client in your code:` with example

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#1750]
Is this issue a duplicate? I didn't find any.

So here the output is 
<img width="453" alt="Screen Shot 2020-03-03 at 10 56 26" src="https://user-images.githubusercontent.com/1328733/75764215-d53aa500-5d3d-11ea-8b8d-b4b119b797bd.png">

This makes sense on the first run or if you didn't use Prisma Client yet.
After that it's a really noisy message.

**Comment by Jolg42** [comment]
Related #1643

**Comment by janpio** [comment]
Note: Wait with implementation until https://github.com/prisma/specs/issues/427 is decided please.

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/3390

**Comment by janpio** [comment]
Duplicate of #3390
