### ISSUE TITLE
Database Connectors

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma#1751]
# Connector Types

Prisma supports two kinds of database connectors:

* Active connectors - manage and migrate the database schema
* Passive connectors - read and write data only

A connector supports at least one of the following GraphQL flavours:

* Relational
* Document
* Graph
* Key/Value
* Search
* Time series
* Analytical
* In Memory

# Contributing

The best way to ensure that a particular connector gets build is to contribute the following two things:

1. Very concrete use case description.
2. Initial suggestion for syntax for SDL and the generated GrpahQL API.

When we prioritise the connectors to build, community validation plays a big role, so the more you can contribute in the relevant Github issue the better.

# Scalar Types

https://github.com/graphcool/prisma/issues/1753 maps out scalar types supported by each database and attempts to map to a common set of GraphQL Scalar Types.

We need to decide if Prisma should support db specific types in addition to the generic types. The MySQL types `SMALLINT` and `INT` both map to the GraphQL type `Int`, but we could also allow mapping them to the GraphQL types `MySQL_SMALLINT` and `MySQL_INT` respectively for added control.

# Connectors

### MySQL
[Active: ✅](https://www.prismagraphql.com/docs/reference/service-configuration/data-modelling-(sdl)-eiroozae8u)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1749)

### PostgreSQL
[Active: ✅](https://github.com/graphcool/prisma/issues/1641)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1641)

### Ms SQL
[Active: ☑️](https://github.com/graphcool/prisma/issues/1642)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1642)

### Oracle
[Active: ☑️](https://github.com/graphcool/prisma/issues/1644)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1644)

### CockroachDB
[Active: ☑️](https://github.com/graphcool/prisma/issues/1705)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1705)

### MongoDB
[Active: ☑️](https://github.com/graphcool/prisma/issues/1643)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1643)

### ArangoDB
[Active: ☑️](https://github.com/graphcool/prisma/issues/1645)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1645)

### Neo4j
[Active: ☑️](https://github.com/graphcool/prisma/issues/1646)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1646)

### Dgraph
[Active: ☑️](https://github.com/graphcool/prisma/issues/1648)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1648)

### Neptune
[Active: ☑️](https://github.com/graphcool/prisma/issues/1752)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1752)

### Druid
[Active: ☑️](https://github.com/graphcool/prisma/issues/1647)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1647)

### Influx
[Active: ☑️](https://github.com/graphcool/prisma/issues/1857)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1857)

### Timescale
[Active: ☑️](https://github.com/graphcool/prisma/issues/1672)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1672)

### DynamoDB
[Active: ☑️](https://github.com/graphcool/prisma/issues/1655)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1655)

### Cassandra
[Active: ☑️](https://github.com/graphcool/prisma/issues/1750)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1750)

### Elastic Search
[Active: ☑️](https://github.com/graphcool/prisma/issues/1665)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1665)

### Redis
[Active: ☑️](https://github.com/graphcool/prisma/issues/1722)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/1722)

### SQLite
[Active: ☑️](https://github.com/graphcool/prisma/issues/2460)
[Passive: ☑️](https://github.com/graphcool/prisma/issues/2460)

**Comment by pranasblk** [comment]
Would you consider "Apache Ignite" ?

**Comment by nharlow89** [comment]
Any chance of a file-based db such as an `sqlite` connector?

**Comment by sorenbs** [comment]
@nharlow89 - that's a great idea. Could you open a separate issue and describe your use case in as much detail as possible? Thanks!

**Comment by cmcinroy** [comment]
@sorenbs could we update the original post to have the link for the passive MySQL connector point here:
https://github.com/prismagraphql/prisma/issues/2506

... just to reflect how the related issues have since evolved?

**Comment by mnlbox** [comment]
+1 for SQLite

**Comment by paul-go** [comment]
Another +1 for SQLite

**Comment by kevineger** [comment]
Any thoughts on Cosmos DB? I saw it referenced in [this older issue](https://github.com/prisma/prisma/issues/1663).

**Comment by cmdavinder** [comment]
Any news on Elastic search connector?

**Comment by adonig** [comment]
SQLite optionally stored in S3 like [this](https://pypi.org/project/django-s3-sqlite/).
