### ISSUE TITLE
Error: P1001 postgresql

### ISSUE THREAD

**Issue by JefferyHus** [prisma/prisma#17529]
### Bug description

I have this setup in my docker compose:

```shell
  database:
    image: postgres:alpine
    container_name: demo
    restart: always
    ports:
      - 5433:5432
    expose:
      - 5433
    env_file:
      - ./docker/database/.env.database.dev
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/postgresql/data
```

The connection string is `postgresql://manager:potato@database/demo?schema=public`

Everytime I run `npx prisma migration dev` inside the container it fails with Error: P1001, I know there have been multiple issues related to this, but none actually solves the issue. The only way for me to migrate the database is to change the host in the string alongside the port to `localhost` and `5433` respectivly, and run the `npx prisma migration dev` command outside the container, the weird thing is that everything else related to database querying is working as expected, this is only about running migrations.

### How to reproduce

- use the docker compose setup from my example
- log into your container or run the command using `docker exec`
- inside the container run either `npx prisma migration dev` or any other alternative you want to use
- using `docker exec` do this `docker exec [container] yarn prisma migrate dev`

### Expected behavior

I expect it to run migrations correctly within the container.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 16

### Prisma Version

```
prisma                  : 4.9.0
@prisma/client          : 4.9.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.9.0-42.ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Default Engines Hash    : ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Studio                  : 0.479.0
```

**Comment by JefferyHus** [comment]
I have tried one final solution that seems to do the trick, I changed my connection string to this `POSTGRES_URL=postgresql://manager:potato@database/demo?schema=public&connection_limit=5&pool_timeout=0`, I was sceptical that `prisma` error `P1001` in my case was mostly because of timeouts, it would be pretty cool to actually throw specific errors about timeouts instead of this broad error message

**Comment by janpio** [comment]
I created https://github.com/prisma/prisma/issues/17534 to pick up this suggestion.
