### ISSUE TITLE
MongoDb `aggregateRaw` $match's $lte or $gte operators not working for DateTime properties

### ISSUE THREAD

**Issue by arbassic** [prisma/prisma#17522]
### Bug description

When trying to fetch a document from MongoDb database using `aggregateRaw`, filtering with $match for DateTIme properties is not working for queries like:

```ts
date: {
  $gte: new Date('2023-01-201T00:00:00.000Z'),
}
```

Above example produces the error:

> Index signature for type 'string' is missing in type 'Date'.

The above problem might be mitigated by using 'string' or 'number'. So when date is converted to `string` (ISO string) or `number` (ms or sec since the unix epoch) - the function always returns an empty array. Also casting the date to 'any' (to just omit TS checks and pass the Date object to the function) generates a runtime error.

Although the issue title contains $lte and $gte operators only, the problem applies to all of them.

### How to reproduce

1. Create a model with DateTime field
2. Fill out the model with data, that should be returned within a query similar to that from the example above
3. Run query using aggregateRaw with `dateField: { $gte/lte:... }` $match instruction
4. See that result is always an empty array but should not

### Expected behavior

Matching results should be returned correctly

### Prisma information

An example model with a DateTime field:

```prisma
model News {
  id        String   @id @default(auto()) @map("_id") @db.ObjectId
  createdAt DateTime @default(now())
}
```

```ts
// 1. fill out the News model with data that should be returned within the below query
// then...
// 2. run query using aggregateRaw
const randomNews = await db.news.aggregateRaw({
    pipeline: [
      {
        $match: {
          createdAt: {
            $gte: new Date('2023-01-01T00:59:00.000Z').toISOString(),
          }
        },
      },
      {
        $sample: {
          size: 1,
        },
      },
    ],
  });

// 3. result is always empty
assert.ok(randomNews.length === 0);

// but there should be one random element returned by the aggregateRaw function
// » randomNews.length === 1
```

### Environment & setup

- OS: macOS
- Database: MongoDB
- Node.js version: 14

### Prisma Version

```
4.9.0
```

**Comment by technotip** [comment]
```
const randomNews = await db.news.aggregateRaw({
    pipeline: [
      {
        $match: {
          $expr: {
            $gte: [
              "$createdAt",
              {
                $dateFromString: {
                  dateString: new Date(
                    "2023-01-01T00:59:00.000Z"
                  ).toISOString(),
                },
              },
            ],
          },
        },
      },
      {
        $sample: {
          size: 1,
        },
      },
    ],
  });
  return randomNews;
```

**Comment by arbassic** [comment]
@technotip wow, thanks for sharing
your solution just works

So it looks like this is not a bug of prisma lib but the way raw queries for aggregate in mongodb works.

Closing the issue
