### ISSUE TITLE
Introspection: Do not show Prisma1->2 upgrade message when Introspection included functionality not available in Prisma 1

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17520]
Note the schema on the left that was introspected, vs. the message on the right:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/183673/214386344-f7e008be-64bc-440b-ac38-e4678ad0655b.png">
I don't think `@@index([name(ops: raw("gin_trgm_ops"))], type: Gin)` was possible in Prisma 1, so we can probably skip the message when advanced features like this are present in the Introspection result.

**Comment by do4gr** [comment]
We could even decide to remove the upgrade message completely at some point. It has been a while since Prisma1, and the message can and will show up as a false positive especially for small and simple data models.
