### ISSUE TITLE
Could not figure out an ID in create

### ISSUE THREAD

**Issue by MonHS** [prisma/prisma#17532]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v17.9.1            | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 4.5.0              |
| Query Engine    | 0362da9eebca54d94c8ef5edd3b2e90af99ba452|
| Database        | mysql              |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /home/container/.env
prisma:tryLoadEnv Environment variables loaded from /home/container/.env
prisma:client dirname /home/container/node_modules/.prisma/client
prisma:client relativePath ../../../src/prisma
prisma:client cwd /home/container/src/prisma
prisma:client clientVersion 4.5.0
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine:loader Searching for Query Engine Library in /home/container/node_modules/.prisma/client
prisma:client:libraryEngine:loader loadEngine using /home/container/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by janpio** [comment]
@MonHS Can you shared the schema and `create` that caused this error please? Thanks.
Did you try upgrading your Prisma to a more recent version to see if the error persists?

**Comment by MonHS** [comment]
@janpio hi, i didnt understand what you mean

**Comment by MonHS** [comment]
@janpio hi, if i am change the sql to sqlite its work.
but i want its will be in mysql

**Comment by MonHS** [comment]
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model DiscordAccounts {
  discordId     String          @id
  licenseCode   LicenseCodes    @relation(fields: [licenseCodeId], references: [id])
  licenseCodeId Int             @unique
  steamAccounts SteamAccounts[]
  createdAt     DateTime        @default(now())
  updatedAt     DateTime        @updatedAt

  @@map("discord_accounts")
}

model SteamAccounts {
  id             String          @id @default(cuid())
  discordOwner   DiscordAccounts @relation(fields: [discordOwnerId], references: [discordId])
  discordOwnerId String
  isRunning      Boolean         @default(false)
  username       String          @unique
  password       String
  loginKey       String
  sharedSecret   String
  onlineStatus   Boolean         @default(true)
  games          Bytes
  createdAt      DateTime        @default(now())
  updatedAt      DateTime        @updatedAt

  @@map("steam_accounts")
}

model LicenseType {
  id           String         @id
  name         String         @unique
  licenseCodes LicenseCodes[]
  createdAt    DateTime       @default(now())
  updatedAt    DateTime       @updatedAt

  @@map("license_type")
}

model LicenseCodes {
  id             Int              @id @default(autoincrement())
  code           String           @unique
  licenseType    LicenseType      @relation(fields: [licenseTypeId], references: [id])
  licenseTypeId  String
  isUsed         Boolean          @default(false)
  discordAccount DiscordAccounts?
  createdAt      DateTime         @default(now())
  updatedAt      DateTime         @updatedAt

  @@map("license_codes")
}

**Comment by MonHS** [comment]
I accidentally closed

**Comment by mcbethio** [comment]
Hey @MonHS, Thanks for sending in your schema.

It would also really help us if we understand what your create statement also looks like. Please can you send us a code snippet of that?

Thanks

**Comment by Weakky** [comment]
Hey @MonHS,

We unfortunately can't reproduce your issue without the actual Prisma Client query that led to your error. Could you provide it to us so that we can try fixing your issue?

Thank you 🙏
