### ISSUE TITLE
Naming a model `Promise` breaks types for `PrismaPromise`

### ISSUE THREAD

**Issue by Tenrys** [prisma/prisma#17542]
### Bug description

![](https://user-images.githubusercontent.com/3979239/213174877-0ab5ac04-4f08-4fda-b05b-f9c478946ed2.png)

This started happening since Prisma 4.9.0, seemingly since https://github.com/prisma/prisma/pull/17265.

### How to reproduce

Clone the linked reproduction repository, generate the Prisma schema, and open `index.ts` in VSCode. `await` will not work on the `findMany` query and trying to call `map` on the expected awaited array of `customers` will give an error.

### Prisma information

[Reproduction repository](https://github.com/Tenrys/prisma-4.9.0-await-prismapromise-repro)

### Environment & setup

- OS: Manjaro Linux
- Database: PostgreSQL
- Node.js version: v16.17.0

### Prisma Version

```
4.9.0
```

**Comment by Tenrys** [comment]
Same story if you have something in your schema called `PromiseType`, in this case an enum. In general it seems like if you're not careful, you could generate types overriding the ones required for the Prisma client types to work properly.

**Comment by SevInf** [comment]
This is fixed and the fix will be published as a part of 5.1 release. You can also check out `5.1.0-dev.25` dev snapshot - we do not recommend using dev snapshots in production, but it should be enough to verify the fix.
