### ISSUE TITLE
Wrong Parameterized Types Sent for SQL Server Queries

### ISSUE THREAD

**Issue by scvna** [prisma/prisma#17565]
### Bug description

We have been working to move an internal application over to using Prisma backed by SQL Server.  We have noticed that more often than not incorrect parameter types are used in the queries generated by Prisma.  For example:

- A prisma `String` field annotated with a specified varchar length, e.g., `Email         String    @unique(map: "AK_repro_User_Email") @db.VarChar(128)` is being parameterized into `nvarchar(4000)` on queries.  This causes inefficiencies when querying the db and if done in a hot loop can lead to db health issues.  Multiple examples of this can be seen in the screenshot below.  As far as I know there's no way to get access to the parameter types via any hooking into prisma metrics, etc... so these were gathered via [SQL Server Profiler extension](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-server-profiler-extension?view=sql-server-ver16)
- Frequently BigInt is used, for example when performing a findunique with the table's PK, despite the column type being defined as `Int`
<img width="1558" alt="Screenshot 2023-01-25 at 1 09 34 PM" src="https://user-images.githubusercontent.com/110245339/214915754-bd713b8f-9f7c-4302-83e6-03df6a0fe797.png">

### How to reproduce

I've created a repro repo where this issue can be seen at https://github.com/scvna/prisma_repro_nvarchar

Cloning that and running `./run.sh` will standup a sql server db and run the application via docker-compose.  The repo can also serve as a template for running this manually if you would like, the compose/standup process is fairly straightforward.  

### Expected behavior

I would expect the type of the parameter sent to SQL Server to match the declaration in `schema.prisma`

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

datasource db {
  provider = "sqlserver"
  url      = "sqlserver://localhost:1433;database=TestDB;user=sa;password=Prisma123@;encrypt=true;trustServerCertificate=true;connect_timeout=10;max_connection_lifetime=1200"
}

model Imperfection {
  ImperfectionId      Int      @id(map: "PK_Imperfection") @default(autoincrement())
  VehicleId           Int
  ContentFileId       Int?
  OverrideName        String?  @db.VarChar(200)
  OverrideDescription String?  @db.VarChar(500)
  CreatedAt           DateTime
  UpdatedAt           DateTime @updatedAt
  UpdatedBy           String?  @db.VarChar(100)
  IsHidden            Boolean?
  IsReviewed          Boolean?
  File                File?    @relation(fields: [ContentFileId], references: [FileId], onDelete: NoAction, onUpdate: NoAction, map: "FK_Imperfection_File")

  @@index([VehicleId], map: "IX_repro_Imperfection_VehicleId")
}

model User {
  UserId        Int       @id(map: "PK_repro_User") @default(autoincrement()) @db.SmallInt
  Email         String    @unique(map: "AK_repro_User_Email") @db.VarChar(128)
  Name          String    @db.VarChar(128)
  CreatedAt     DateTime
  UpdatedAt     DateTime  @updatedAt
  DeactivatedAt DateTime?
  File          File[]
}

model File {
  FileId             Int            @id(map: "PK_File") @default(autoincrement())
  Url                String?        @unique(map: "AK_File_Url") @db.VarChar(200)
  CreatedAt          DateTime
  UpdatedAt          DateTime       @updatedAt
  ThumbnailFileId    Int?
  PhotographerUserId Int?           @db.SmallInt
  ThumbnailFile      File?          @relation("FileToFile_ThumbnailFileId", fields: [ThumbnailFileId], references: [FileId], onDelete: NoAction, onUpdate: NoAction, map: "FK_File_ThumbnailFile")
  other_File         File[]         @relation("FileToFile_ThumbnailFileId")
  User               User?          @relation(fields: [PhotographerUserId], references: [UserId], onDelete: NoAction, onUpdate: NoAction, map: "FK_repro_File_User")
  Imperfection       Imperfection[]

  @@index([UpdatedAt], map: "IX_repro_File_UpdatedAt")
}

```

```ts
import { PrismaClient } from "@prisma/client";

const createdAt = (): Date => new Date();

type UpsertFileInput = {
  url: string;
  photographerUserId: number;
};
const upsertFile = async (
  prisma: PrismaClient,
  { url, photographerUserId }: UpsertFileInput
): Promise<Number> => {
  const { FileId, UpdatedAt } = await prisma.file.upsert({
    where: {
      Url: url,
    },
    create: {
      PhotographerUserId: photographerUserId,
      CreatedAt: createdAt(),
    },
    update: {},
    select: {
      FileId: true,
      UpdatedAt: true,
    },
  });

  return FileId;
};

const run = async () => {
  const prisma = new PrismaClient();

  const user = await prisma.user.upsert({
    where: {
      Email: "prisma@repro.com",
    },
    create: {
      Email: "prisma@repro.com",
      Name: "Hello",
      CreatedAt: createdAt(),
    },
    update: {},
  });
  console.log(`upserted user ${JSON.stringify(user)}`);

  const fileId = await upsertFile(prisma, {
    url: "https://google.com",
    photographerUserId: user.UserId,
  });
  console.log(`upserted file with id ${fileId}`);
};

try {
  run();
} catch (e) {
  console.log(e);
}

```

### Environment & setup

- OS: Present at least on macOS and whatever flavor of linux/amd64 serves as the base in the [node:18.12.0 image](https://hub.docker.com/layers/library/node/18.12.0/images/sha256-16258bac1617ed4456e7f540c4468478fd7341ffeed478ffba1920013efc1348?context=explore)
- Database: SQL Server
- Node.js version: present on v19.5.0 and v18.12.0

### Prisma Version

From macos:
```
prisma                  : 4.9.0
@prisma/client          : 4.9.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.9.0-42.ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Default Engines Hash    : ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Studio                  : 0.479.0
```

From docker image:
```
prisma                  : 4.9.0
@prisma/client          : 4.9.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.9.0-42.ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Default Engines Hash    : ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Studio                  : 0.479.0
```

**Comment by millsp** [comment]
Thanks for the report, I was also able to reproduce this. I need to install this then I was able to profile the query as you did:

https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&tabs=redhat-install%2Credhat-uninstall

https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-server-profiler-extension?view=sql-server-ver16


![image](https://github.com/prisma/prisma/assets/18401805/e9835eaa-13b0-453f-a923-3858af1315e5)

**Comment by Weakky** [comment]
Thanks for the report @scvna, this issue is now fixed.

Implicit conversions were happening on SQL Server which was causing indexes not to be properly used, which in turns caused the high CPU usage.

If you want to give the fix a try earlier than next release, you can update your Prisma CLI and Prisma Client to the following version:

```bash
npm install prisma@5.16.0-dev.37 @prisma/client@5.16.0-dev.37
npx prisma generate
```

We have noticed you are currently using version `4.9.0`, which means you may want to have a look at our `5.0.0` [upgrade guide](https://www.prisma.io/docs/orm/more/upgrade-guides/upgrading-versions/upgrading-to-prisma-5) as there is a few breaking changes that comes with that major version.

Let us know if this fixes your issue.

Thanks
