### ISSUE TITLE
index.d.ts file is huge and could benefit from being split up to improve ide performance

### ISSUE THREAD

**Issue by yharaskrik** [prisma/prisma#17562]
# Problem

While the types Prisma generate are fantastic, they are generated entirely into a single massive file (massive is obviously determined by the size of your DB schema). This means when IDEs need to index the file, auto complete (intellisense) or devs need to open the file to inspect the type definitions it is slow to do so.

We have 3 Prisma schemas in our repo, the generated index.d.ts files are:

1. 61,462 lines - 2.3MB
2. 44,957 lines - 1.6MB
3. 191,835 lines - 7.3MB

Definitely should not come to a surprised that navigating around a TS file with >190k lines that is over 7MB is a little slow.

# Proposed solution

Generate the type definitions into separate files, have the generic Prisma types that are unchanged between schemas separated out and potentially each model could be in it's own file. It obviously gets more granular this and is an implementation detail but in reality the organization of these files should not matter as the `index.d.ts` would still be the entry point so implementations of prisma usages would remain unchanged, but it would help with IDEs being bogged down.

**Comment by janpio** [comment]
Is this different than https://github.com/prisma/prisma/issues/4807?

**Comment by yharaskrik** [comment]
> Is this different than #4807?

Ah ya it seems like it is the same
