### ISSUE TITLE
`db pull`: add new codes for introspection warnings for views in the CLI

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#17578]
New codes were added after https://github.com/prisma/prisma-engines/commit/61863c7b1810c243ede42ae8ed40dc849b38c193

See https://github.com/prisma/prisma-engines/blob/main/introspection-engine/connectors/sql-introspection-connector/src/warnings/generators.rs#L405-L453

Codes 21, 22, 23, 24, 25, 26

They need to be added in
https://github.com/prisma/prisma/blob/main/packages/migrate/src/types.ts
and handled in
https://github.com/prisma/prisma/blob/main/packages/migrate/src/commands/DbPull.ts

**Comment by Druue** [comment]
Note: Just introspecting a view (no underlying tables) results in `Error P4001: the introspected database was empty`
