### ISSUE TITLE
Using .catch() for error handling instead of try catch

### ISSUE THREAD

**Issue by Mazeral** [prisma/prisma#17597]
## Problem

One of the things that upsets me when I face an error (besides the error itself) is how the server crashes and I should restart it every time.
One thing that  also that doesn't make me really happy is how I should the try catch blocks, it's annoying makes writing code harder that it should be since the data inside the try block is not accessible outside of it. 

## Suggested solution

What I want is a way to handle errors in a way that prevent errors from crashing the server and without the need of try catch blocks, thus I suggest adding .catch() for prisma queries.

## Alternatives

A nice alternative is making prisma client handle the errors automatically without crashing the server.

## Additional context
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

**Comment by Mazeral** [comment]
It appears that this issue was labeled as a bug
This issue was opened because whenever I  try to use  ```.catch() ``` with ```FindFirst``` function, it send `expecting try catch` error.
```FindMany``` function worked with ```.catch() ``` worked fine, although I didn't test how it does react to an error.

**Comment by M0Leo** [comment]
Any updates on this ?

**Comment by asevila** [comment]
Any updates on this?
