### ISSUE TITLE
crash db pull sqlserver

### ISSUE THREAD

**Issue by yakanet** [prisma/prisma#17601]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.12.1           | 
| Prisma CLI  | 4.9.0              | 
| Engine      | ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5| 

## Error
```
Error: Error in migration engine.
Reason: [libs\sql-schema-describer\src\mssql.rs:341:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `create default [ZERO] as 0\r\n\r\n`"

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by miguelff** [comment]
@yakanet Could you please send us a schema dump of the database, and the MsSQLVersion?

**Comment by millsp** [comment]
Hey @yakanet, could you please help us with the missing information? Without your help, we will not be able to fix this issue. Looking forward to your reply.

**Comment by millsp** [comment]
Hey @yakanet, I am closing this issue as we did not hear back from you. Just ping us and we can re-open it when we have the missing information. Thanks!
