### ISSUE TITLE
Figure out where getDMMF is used for validation

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#17618]
getDMMF is much heavier than just validation, we would benefit from doing just validation in these places. This issue is only about investigating _where_ we are currently doing that in our whole typescript codebase.

Output: Notion document with overview.

**Comment by jkomyno** [comment]
`getDMMF` is improperly used as a validation method in:

- `prisma format` ([here](https://github.com/prisma/prisma/blob/8d8a1ed62b11a8a98d2a6d104fe131d7347e405e/packages/cli/src/Format.ts#L57-L65))
- `prisma validate` ([here](https://github.com/prisma/prisma/blob/92d2d1c8ab6467ec9d43c52627a5c9590cc6bcfc/packages/cli/src/Validate.ts#L85-L93))
- `prisma migrate dev` ([here](https://github.com/prisma/prisma/blob/06c00b26803e5feff6cd7dec3d448c0f366986e1/packages/migrate/src/commands/MigrateDev.ts))

Will provide a Notion doc shortly
