### ISSUE TITLE
Load engine libquery_engine-rhel-openssl timeouts on Lambda 

### ISSUE THREAD

**Issue by mateeuswagner** [prisma/prisma#17651]
### Bug description

Hi Prisma Team, hope you're all good.

I have an application running on AWS Lambda using libquery_engine-rhel-openssl and intermittently the engine takes more than 30 seconds (my lambda timeout) to load.

**Logs - Failed**
|   timestamp   |                                                                                    message                                                                                     |
|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1675173398264 | START RequestId: 214c4313-de0b-48e2-a487-e92785e359cd Version: $LATEST                                                                                                         |
| 1675173398414 | 2023-01-31T13:56:38.414Z prisma:get-platform  Command "uname -m" successfully returned "x86_64                                                                                 |
| 1675173398414 | "                                                                                                                                                                              |
| 1675173398415 | 2023-01-31T13:56:38.415Z prisma:get-platform  Trying platform-specific paths for "rhel"                                                                                        |
| 1675173398430 | 2023-01-31T13:56:38.430Z prisma:get-platform  Command "ls /lib64 | grep libssl.so" successfully returned "libssl.so.10                                                         |
| 1675173398430 | libssl.so.1.0.2k                                                                                                                                                               |
| 1675173398430 | "                                                                                                                                                                              |
| 1675173398430 | 2023-01-31T13:56:38.430Z prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.10                                                                 |
| 1675173398430 | libssl.so.1.0.2k                                                                                                                                                               |
| 1675173398431 | 2023-01-31T13:56:38.431Z prisma:get-platform  The parsed libssl version is: 1.0.x                                                                                              |
| 1675173398435 | 2023-01-31T13:56:38.435Z prisma:get-platform  Command "uname -m" successfully returned "x86_64                                                                                 |
| 1675173398435 | "                                                                                                                                                                              |
| 1675173398436 | 2023-01-31T13:56:38.436Z prisma:get-platform  Trying platform-specific paths for "rhel"                                                                                        |
| 1675173398449 | 2023-01-31T13:56:38.448Z prisma:get-platform  Command "ls /lib64 | grep libssl.so" successfully returned "libssl.so.10                                                         |
| 1675173398449 | libssl.so.1.0.2k                                                                                                                                                               |
| 1675173398449 | "                                                                                                                                                                              |
| 1675173398449 | 2023-01-31T13:56:38.448Z prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.10                                                                 |
| 1675173398449 | libssl.so.1.0.2k                                                                                                                                                               |
| 1675173398449 | 2023-01-31T13:56:38.448Z prisma:get-platform  The parsed libssl version is: 1.0.x                                                                                              |
| 1675173398454 | 2023-01-31T13:56:38.454Z prisma:get-platform  Command "uname -m" successfully returned "x86_64                                                                                 |
| 1675173398454 | "                                                                                                                                                                              |
| 1675173398454 | 2023-01-31T13:56:38.454Z prisma:get-platform  Trying platform-specific paths for "rhel"                                                                                        |
| 1675173398464 | 2023-01-31T13:56:38.464Z prisma:get-platform  Command "ls /lib64 | grep libssl.so" successfully returned "libssl.so.10                                                         |
| 1675173398464 | libssl.so.1.0.2k                                                                                                                                                               |
| 1675173398464 | "                                                                                                                                                                              |
| 1675173398464 | 2023-01-31T13:56:38.464Z prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.10                                                                 |
| 1675173398464 | libssl.so.1.0.2k                                                                                                                                                               |
| 1675173398464 | 2023-01-31T13:56:38.464Z prisma:get-platform  The parsed libssl version is: 1.0.x                                                                                              |
| 1675173398465 | 2023-01-31T13:56:38.464Z prisma:client:libraryEngine:loader  Searching for Query Engine Library in /.prisma/client                                                             |
| 1675173398465 | 2023-01-31T13:56:38.465Z prisma:client:libraryEngine:loader  Searching for Query Engine Library in /opt/atlassian/pipelines/agent/build/node_modules/@prisma/client            |
| 1675173398465 | 2023-01-31T13:56:38.465Z prisma:client:libraryEngine:loader  Searching for Query Engine Library in /var/task                                                                   |
| 1675173398465 | 2023-01-31T13:56:38.465Z prisma:client:libraryEngine:loader  Searching for Query Engine Library in /var/task/dist                                                              |
| 1675173398465 | 2023-01-31T13:56:38.465Z prisma:client:libraryEngine:loader  loadEngine using /var/task/dist/libquery_engine-rhel-openssl-1.0.x.so.node                                        |
| 1675173428298 | 2023-01-31T13:57:08.298Z 214c4313-de0b-48e2-a487-e92785e359cd Task timed out after 30.03 seconds                                                                               |
| 1675173428298 | END RequestId: 214c4313-de0b-48e2-a487-e92785e359cd                                                                                                                            |
| 1675173428298 | REPORT RequestId: 214c4313-de0b-48e2-a487-e92785e359cd Duration: 30034.11 ms Billed Duration: 30000 ms Memory Size: 2048 MB Max Memory Used: 121 MB Init Duration: 551.23 ms   |

**Logs - Success**
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                  message                                                                                   |
|---------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1675173124592 | "                                                                                                                                                                          |
| 1675173124593 | 2023-01-31T13:52:04.592Z prisma:get-platform  Trying platform-specific paths for "rhel"                                                                                    |
| 1675173124612 | 2023-01-31T13:52:04.611Z prisma:get-platform  Command "ls /lib64 | grep libssl.so" successfully returned "libssl.so.10                                                     |
| 1675173124612 | libssl.so.1.0.2k                                                                                                                                                           |
| 1675173124612 | "                                                                                                                                                                          |
| 1675173124612 | 2023-01-31T13:52:04.611Z prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.10                                                             |
| 1675173124612 | libssl.so.1.0.2k                                                                                                                                                           |
| 1675173124612 | 2023-01-31T13:52:04.612Z prisma:get-platform  The parsed libssl version is: 1.0.x                                                                                          |
| 1675173124621 | 2023-01-31T13:52:04.621Z prisma:get-platform  Command "uname -m" successfully returned "x86_64                                                                             |
| 1675173124621 | "                                                                                                                                                                          |
| 1675173124621 | 2023-01-31T13:52:04.621Z prisma:get-platform  Trying platform-specific paths for "rhel"                                                                                    |
| 1675173124633 | 2023-01-31T13:52:04.633Z prisma:get-platform  Command "ls /lib64 | grep libssl.so" successfully returned "libssl.so.10                                                     |
| 1675173124633 | libssl.so.1.0.2k                                                                                                                                                           |
| 1675173124633 | "                                                                                                                                                                          |
| 1675173124633 | 2023-01-31T13:52:04.633Z prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.10                                                             |
| 1675173124633 | libssl.so.1.0.2k                                                                                                                                                           |
| 1675173124634 | 2023-01-31T13:52:04.634Z prisma:get-platform  The parsed libssl version is: 1.0.x                                                                                          |
| 1675173124650 | 2023-01-31T13:52:04.650Z prisma:get-platform  Command "uname -m" successfully returned "x86_64                                                                             |
| 1675173124650 | "                                                                                                                                                                          |
| 1675173124650 | 2023-01-31T13:52:04.650Z prisma:get-platform  Trying platform-specific paths for "rhel"                                                                                    |
| 1675173124658 | 2023-01-31T13:52:04.658Z prisma:get-platform  Command "ls /lib64 | grep libssl.so" successfully returned "libssl.so.10                                                     |
| 1675173124658 | libssl.so.1.0.2k                                                                                                                                                           |
| 1675173124658 | "                                                                                                                                                                          |
| 1675173124658 | 2023-01-31T13:52:04.658Z prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.10                                                             |
| 1675173124658 | libssl.so.1.0.2k                                                                                                                                                           |
| 1675173124658 | 2023-01-31T13:52:04.658Z prisma:get-platform  The parsed libssl version is: 1.0.x                                                                                          |
| 1675173124659 | 2023-01-31T13:52:04.659Z prisma:client:libraryEngine:loader  Searching for Query Engine Library in /.prisma/client                                                         |
| 1675173124659 | 2023-01-31T13:52:04.659Z prisma:client:libraryEngine:loader  Searching for Query Engine Library in /opt/atlassian/pipelines/agent/build/node_modules/@prisma/client        |
| 1675173124659 | 2023-01-31T13:52:04.659Z prisma:client:libraryEngine:loader  Searching for Query Engine Library in /var/task                                                               |
| 1675173124659 | 2023-01-31T13:52:04.659Z prisma:client:libraryEngine:loader  Searching for Query Engine Library in /var/task/dist                                                          |
| 1675173124659 | 2023-01-31T13:52:04.659Z prisma:client:libraryEngine:loader  loadEngine using /var/task/dist/libquery_engine-rhel-openssl-1.0.x.so.node                                    |
| 1675173124754 | 2023-01-31T13:52:04.753Z prisma:client:libraryEngine  library starting                                                                                                     |
| 1675173124818 | 2023-01-31T13:52:04.818Z prisma:client:libraryEngine  library started                                                                                                      |
| 1675173124849 | 2023-01-31T13:52:04.849Z prisma:client  Prisma Client call:                                                                                                                |
| 1675173124851 | 2023-01-31T13:52:04.851Z prisma:client  prisma.companyData.findFirst({                                                                                                     |
| 1675173124851 | where: {                                                                                                                                                                   |
| 1675173124851 | companyId: 'XXXX'                                                                                                                                   |
| 1675173124851 | }                                                                                                                                                                          |
| 1675173124851 | })                                                                                                                                                                         |
| 1675173124851 | 2023-01-31T13:52:04.851Z prisma:client  Generated request:                                                                                                                 |
| 1675173124851 | 2023-01-31T13:52:04.851Z prisma:client  query {                                                                                                                            |
| 1675173124851 | findFirstCompanyData(where: {                                                                                                                                              |
| 1675173124851 | companyId: "XXXX"                                                                                                                                   |
| 1675173124851 | }) {                                                                                                                                                                       |
| 1675173124851 | id                                                                                                                                                                         |
| 1675173124851 | companyId                                                                                                                                                                  |
| 1675173124851 | availableCredits                                                                                                                                                           |
| 1675173124851 | availableCreditsCurrency                                                                                                                                                   |
| 1675173124851 | emailNotificationsConfig                                                                                                                                                   |
| 1675173124851 | createdAt                                                                                                                                                                  |
| 1675173124851 | updatedAt                                                                                                                                                                  |
| 1675173124851 | }                                                                                                                                                                          |
| 1675173124851 | }                                                                                                                                                                          |
| 1675173124852 | 2023-01-31T13:52:04.851Z prisma:client:libraryEngine  sending request, this.libraryStarted: true                                                                           |
| 1675173124883 | END RequestId: 7efdd896-d614-4f6f-815a-d35ab1c9a92b                                                                                                                        |
| 1675173124883 | REPORT RequestId: 7efdd896-d614-4f6f-815a-d35ab1c9a92b Duration: 427.76 ms Billed Duration: 428 ms Memory Size: 2048 MB Max Memory Used: 138 MB Init Duration: 551.10 ms   |

It's the same lambda function, nothing is changed between each trigger.

I've also tried to increase lambda's timeout to 5min and the memory to 2 GB, but the problem remains. It freezes at the very same line.

### How to reproduce

I haven't found a way to reproduce this 100% of the time. It's intermittent. Sometimes making just one request is enough, but when making more like 10 parallel requests the error occurs more often.

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

```ts
import { Injectable } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

const prismaService = new PrismaClient();

@Injectable()
export class PrismaService {
  repository: PrismaClient = prismaService;

  async connect() {
    await this.repository.$connect();
  }

  async disconnect() {
    await this.repository.$disconnect();
  }
}

```

### Environment & setup

- OS: Rhel (AWS Lambda)
- Database: PostgreSQL
- Node.js version: 14.x

### Prisma Version

```
4.9.0
```

**Comment by janpio** [comment]
Quick question, are all the upvoters your friends or colleagues or is this a much more widespread issue?

This is the line behind that log and logic: https://github.com/prisma/prisma/blob/fe4442d6deaebc358c3b7d0ef463706d418af486/packages/engine-core/src/library/DefaultLibraryLoader.ts#L30-L56 There is unfortunately no log instantly after it was loaded, and also not in the code that comes afterwards so this might not be exactly the loading itself.

**Comment by mateeuswagner** [comment]
Hi @janpio, yes, they are my colleagues.

Do you know how I can investigate further?

**Comment by mateeuswagner** [comment]
@janpio @tomhoule This is still happening. Any idea on a startup point to investigate?

**Comment by beefancohen** [comment]
we are also seeing this issue fwiw

**Comment by mateeuswagner** [comment]
We've found the issue. 
The problem was that one of our Lambda function Subnets was Public. So every time Lambda was instantiated in that Subnet, our application wouldn't have an Internet connection and so the DB connection timed out.

> To access the internet from a public subnet you need a public IP or you need to route via a NAT that itself has a public IP. You also need an Internet Gateway (IGW). However, 1. Lambda function cannot have public IP addresses 2. The default route target in a VPC public subnet is the IGW, not a NAT

Therefore, as the Lambda function only has a private IP and its traffic is routed to the Internet Gateway rather than to a NAT, all packets to the internet from the Lambda function will be dropped at the Internet Gateway

@beefancohen please check if that's your case too.

I'll close the issue. Thank you guys

**Comment by beefancohen** [comment]
! i think we had the same issue, we were in the VPC but attached the wrong subnets (public instead of private).  maybe if possible if you can detect no network access, surfacing that error
