### ISSUE TITLE
Remove `latest` endpoint from `binaries.prisma.sh`

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#1766]
As of now, we still have a `latest` endpoint like so:

```
https://binaries.prisma.sh/master/latest/darwin/prisma.gz
```

However, we introduced caching on this, so it might have unexpected behavior. Even if we clear the cache properly, tools can easily break if they rely on this.
So instead they should use unique urls pointing to a commit hash.

We from now on stop using the url, however we should also remove this at some point to make sure, that nobody is accidentally using this.

**Comment by Jolg42** [comment]
It was removed.
