### ISSUE TITLE
Query validation messages reference color output even if colors are not enabled

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#17706]
![image](https://user-images.githubusercontent.com/603056/216360093-5f5ee355-6207-4f54-bd38-a131816510c3.png)

Error mentions that "available options are listed in green", even though default output is colorless. With `pretty` [errorFormat](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#errorformat) the message is displayed in color and makes a little bit more sense:

![image](https://user-images.githubusercontent.com/603056/216373936-de19dc55-919e-4fcd-9eca-b37ce5e4bb48.png)

Our options are:
- change error message to "available options are marked with ?" or something similar: works regardless of error format, better for colorblind users.
- change error message depending on error format, talk about color only when it is actually present. 
- make `pretty` default format so message would at least make more sense to the most users. Thing to mind: It is an `error.message` property, not some explicit terminal output and ANSI escape sequences for colors will be visible if it is rendered in anything other than terminal. We need at least check most popular frameworks 503 development pages to see how the message looks there.

**Comment by petradonka** [comment]
@quest-bot stash 50
