### ISSUE TITLE
Add support for Bun

### ISSUE THREAD

**Issue by Sandy-Garrido** [prisma/prisma#17715]
## Problem

Bun not yet supported.

## Suggested solution

I don't seem to see anything related to bun on search in this repository but it would be good to see Bun supported since it's gaining popularity in its early stages! I'm aware Bun also needs to support Prisma, though I can see it being a huge effort between the 2 development teams.

**Comment by toniMR** [comment]
I suggest you add the kind/features label, to see if it helps a little to make them see it.

Just today I'm trying bun for the first time and I was trying to use prisma.

In my case I get this error:
```bash
Cannot find package "async_hooks" from ".../node_modules/@prisma/client/runtime/index.js"
```
In these bun issues they comment that async_hooks is needed:
- https://github.com/oven-sh/bun/issues/158
- https://github.com/oven-sh/bun/issues/798
- https://github.com/oven-sh/bun/issues/1832

**Comment by Sandy-Garrido** [comment]
@toniMR unfortunately, the tags are not editable by the public. kind/bug are automatic when you add a bug & the others are added by repo mods/owners

Thanks for adding the additional links from Bun's perspective.

**Comment by Jarred-Sumner** [comment]
It is Bun's responsibility to make Prisma work. 

These are bugs in Bun:
- This breaks error messages: https://github.com/oven-sh/bun/issues/622
- A null ptr dereference caused by a bug in our napi implementation causes a crash: https://github.com/oven-sh/bun/issues/2078


Tracking issue in Bun's repository: https://github.com/oven-sh/bun/issues/2083

**Comment by Jolg42** [comment]
Thanks to https://github.com/cirospaciari is now closed and Prisma supported on Bun! 🎊 

Check out the latest Bun `0.6.7` release:
- https://github.com/oven-sh/bun/releases/tag/bun-v0.6.7
- https://bun.sh/blog/bun-v0.6.7

We're curious to know if it works smoothly for all of you ➡️ let us know here in comments if it worked after you tried it 🙌🏼

**Comment by Khamphay** [comment]
Hi @Jolg42 

I use Bun v0.6.9 and when i use command  ```npx prisma init --datasource-provider mysql``` have error ``` ReferenceError: Can't find variable: __dirname ``` at line:
```javascript
43540 : var childPath = path__default["default"].join(eval("__dirname"), "child");
```

Error detail:
``` bash
┌──(dev㉿dev)-[~/exp_api]
└─$ bun x prisma init --datasource-provider mysql
[0.02ms] ".env"
1 | __dirname
   ^
ReferenceError: Can't find variable: __dirname
      at ../../node_modules/.pnpm/checkpoint-client@1.1.24/node_modules/checkpoint-client/dist/index.js (/home/dev/exp_api/node_modules/prisma/build/index.js:43540:45)
      at __require (/home/dev/exp_api/node_modules/prisma/build/index.js:14:9)
      at /home/dev/exp_api/node_modules/prisma/build/index.js:99490:25
error: "prisma" exited with code 1 (SIGHUP)

```

**Comment by janpio** [comment]
Can you test if this worked with 0.6.7 @Khamphay? If not, this is probably just something that was overlooked initially (it's not the most common command...) and can be reported to bun in their GH repo.

**Comment by JonathanWilbur** [comment]
You can see all of the Bun-Node compatibilities here: https://bun.sh/docs/runtime/nodejs-apis

I don't know for sure, but I think a lot of those are going to be complete blockers until they are supported. `crypto` in particular is missing a lot of parity features.

**Comment by janpio** [comment]
Is it officially good enough for us to tick the box, everything works?
I guess we ourselves would need to run our (exteeeeensive) test suite to really confirm that.

**Comment by sacummings91** [comment]
Any chance someone could take a look at this issue in Bun's github and make sure that it's not a Prisma problem? Currently the prisma postinstall hook fails to execute on `bun install` and `bun run prisma generate` doesn't work either. https://github.com/oven-sh/bun/issues/5320
