### ISSUE TITLE
`prisma migrate dev --create-only` should not fail if `DATABASE_URL` is undefined

### ISSUE THREAD

**Issue by baptisteArno** [prisma/prisma#17724]
## Problem

Currently, when running `prisma migrate dev` with `--create-only`, it still tries to connect to the database and fails if the db URL is empty.

## Suggested solution

Would be nice if it would just create the migrations file without looking at the database at all

Would you accept a pull request for this?

**Comment by LeoAso** [comment]
In order to know what to actually put in a generated migration. Prisma has to run all the migrations before it on a database, and then see how the database differs from your `schema.prisma`. This is why `prisma migrate dev` needs access to a database, even when you are just creating a migration and not running ityet.

**Comment by baptisteArno** [comment]
> Prisma has to run all the migrations before it on a database

That's exactly what I try to disable with `--create-only`, it should not run the existing migrations

The command could also be based only on existing migration files, right?

**Comment by janpio** [comment]
Unfortunately not, as we then would need to somehow magically in memory go from "list of migration files" to "current state of the database" - which Prisma currently can not do. We need to run those migrations in a shadow database to get to that current state of the migration files - and then introspect that one to compare it to the schema, calculate the difference, and then come up with the SQL to overcome that difference - which becomes the SQL we put into the newly created `migration.sql`.

Or did I misunderstand your suggestion @baptisteArno?
