### ISSUE TITLE
Prisma init: allow setting generator provider value

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#17737]
## Problem

When you run `prisma init`, the generator value is always `prisma-client-js`. This will break if the user is using a different generator.

## Suggested solution

Add a CLI flag `--generator` or `--generator-value` to set the value programmatically.

This would even allow custom clients such as the Go client to override this for the user, so that running `prisma init` would just work for the end-user.

## Alternatives

Alternatively, custom generators could add some hack to manually replace the provider value after prisma init is executed. This is not a good solution tho.

## Additional context

https://github.com/prisma/prisma/blob/cc519a8ceefda50c842fa13400218e508373affe/packages/cli/src/Init.ts#L28

I'm happy to send a PR to add this feature if accepted!

**Comment by Jolg42** [comment]
Note: I created a follow up issue to update the docs here https://github.com/prisma/docs/issues/5359
