### ISSUE TITLE
UUID values are not automatically converted to their binary form on write on mysql and sqlite

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#1776]
Since prisma does not have the notion of an `UUID` or `Bytes` type yet, uuids are treated as strings, and inserted as strings. This is a problem in cases like https://github.com/prisma/prisma2/issues/1772, where we have a mysql `binary(16)` column holding UUIDs. On insert, the query engine will send the uuid as a string, and we get back an error because the size of the column and that of the string do not match.

**Comment by gregaou** [comment]
I'm really interested about this, this is my blocking point to migrate to prisma !
Actually my DB use UUID stored as varbinary and prisma can't handle them

**Comment by pimeys** [comment]
Cross-posting here:

This kind of changes with the native types. The database in the linked ticket is introspected as:

```prisma
datasource db {
  provider = "mysql"
  url      = "mysql://root:prisma@localhost:3307/prisma"
}

model ahoy_events {
  id         Bytes     @id @db.Binary(16)
  visit_id   Bytes?    @db.Binary(16)
  user_id    Int?
  name       String?   @db.VarChar(255)
  properties String?   @db.Text
  type       String?   @db.Text
  time       DateTime? @db.DateTime(0)
  created_at DateTime? @db.DateTime(0)
  updated_at DateTime? @db.DateTime(0)

  @@index([id], name: "index_ahoy_events_on_id")
  @@index([time], name: "index_ahoy_events_on_time")
  @@index([user_id], name: "index_ahoy_events_on_user_id")
  @@index([visit_id], name: "index_ahoy_events_on_visit_id")
}
```

So, now when inserting, the binary params must be sent as bytes and the bytes can be converted to and from with e.g. the [uuid library](https://www.npmjs.com/package/uuid):

```javascript
import { PrismaClient } from '@prisma/client'
import { parse as uuidParse } from 'uuid'

const prisma = new PrismaClient()

async function main() {
    let user = await prisma.ahoy_events.create({
        data: {
            id: Buffer.from(uuidParse('ba000471-eabd-55d2-8b42-8ac91ec57e13')),
        }
    });

    console.log(user)
}

main()
    .catch(e => {
        throw e
    })

    .finally(async () => {
        await prisma.$disconnect()
    })
```

Would this be enough to support `binary(16)` uuid values? If not, we might want to introduce a new type: `Uuid`.

**Comment by tomhoule** [comment]
Yes that should be enough, I think :+1: Can anybody confirm that this works?

**Comment by pimeys** [comment]
Yeah it works with the code I wrote above. Discussed with @matthewmueller and this is a solid solution.

**Comment by timsuchanek** [comment]
Just checked it out - works

**Comment by enheit** [comment]
@pimeys, 

Your approach shows an error

![image](https://user-images.githubusercontent.com/8645216/109960456-7792bd00-7cf1-11eb-8f4b-47162b189d31.png)

What I'm doing wrong?

**Comment by pantharshit00** [comment]
@enheit It is just a typescript error. Cast it to correct type to fix this:
```ts
  let user = await prisma.ahoy_events.create({
    data: {
      id: Buffer.from(
        uuidParse("ba000471-eabd-55d2-8b42-8ac91ec57e13") as Array<number>
      ),
    },
  });

```
