### ISSUE TITLE
Environment variable file or `.env` file

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#1777]
Right now many people are not happy with the decisions that we have made regarding the `.env` file support in Prisma. We need to address this.

Sub issues:
1. https://github.com/prisma/prisma2/issues/1255
2. https://github.com/prisma/prisma2/issues/998
3. https://github.com/prisma/prisma2/issues/221
4. https://github.com/prisma/prisma2/issues/1770

**Comment by matthewmueller** [comment]
Thanks for compiling this @pantharshit00. I've collected these into a topic: 

https://github.com/prisma/prisma/labels/topic%3A%20env
