### ISSUE TITLE
Fixed-size column types as part of identifiers do not work on MySQL

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#1778]
On mysql, models with an ID column of a fixed size type (like `binary(16)` or `char(16)`) will fail on create: we insert the record including the ID, and when trying to fetch it back we use the ID we inserted, but MySQL will have padded the value with null bytes for us, so the ID doesn't actually match.

We would need the type information to pad the value ourselves when fetching it back.

See https://github.com/prisma/prisma2/issues/1772 for a schema where that happens.

**Comment by pantharshit00** [comment]
This one is not stale.

**Comment by albertoperdomo** [comment]
Is this now done as part of native types? I think so.

**Comment by albertoperdomo** [comment]
Tom:

>If my understanding is correct, this is a different issue and independent from native types
>although with native types information, the query engine now has a chance to handle this
>it didn't before

**Comment by dpetrick** [comment]
Char types seem to be handled just fine in all DBs. Binary types are problematic and would require serious effort to get right. We settled on documenting pitfalls for fixed binary size types.
