### ISSUE TITLE
 Every RelationInfo should have a complementary RelationInfo on the opposite relation field

### ISSUE THREAD

**Issue by fer9nando9** [prisma/prisma#17825]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.16.0           | 
| Prisma CLI  | 3.15.2             | 
| Engine      | 461d6a05159055555eb7dfb337c9fb271cbd4d7e| 

## Error
```
Error: [libs\datamodel\connectors\dml\src\datamodel.rs:178:14] Every RelationInfo should have a complementary RelationInfo on the opposite relation field.
```

**Comment by mcbethio** [comment]
Hey @fer9nando9, Can you provide us with more information to help us diagnose the root cause. 

The schema you were using would be of a great help. Thanks

**Comment by jkomyno** [comment]
@mcbethio I'm pretty sure the corresponding schema is in this [error report](https://prisma-errors.netlify.app/report/14537).

**Comment by tomhoule** [comment]
`db pull` does not use DML anymore, it hasn't for a while, so I am 100% sure this cannot happen in recent Prisma versions.
