### ISSUE TITLE
Working example of a Generator Namespace Schema

### ISSUE THREAD

**Issue by jakeblaxon** [prisma/prisma#1782]
Hello,

I'm working on writing a custom generator that generates some dummy data for my database. I need a way to pass field-specific information to my generator so that it knows what values to use for certain fields (e.g. to generate email addresses or phone numbers).

I was reading through the [spec](https://github.com/prisma/specs/tree/master/schema#generator-block) and it seems like generator namespaces are the perfect solution for this. If I understand correctly, it seems that for a custom generator called `go`, I can use custom attributes under the `go` namespace in my prisma schema:

```
generator go {
  snakeCase = true
  provider  = "go"
}

type UUID String @go.type("uuid.UUID")

model User {
  id     UUID    @id
  email  String  @go.bytes(100)
}
```

The problem I'm facing is that when I run the generate command, I get an error saying `Attribute not known: "@go.type"`. How can I declare this as an attribute that my generator accepts? Is there a working example of a generator namespace schema that I can reference?

Thank you for the help!

**Comment by pantharshit00** [comment]
@jakeblaxon `@go.type` hasn't been implemented yet. It is part of the spec and might be implemented in the future.

If you want to follow the development of the Go client, please follow https://github.com/prisma/prisma-client-go

**Comment by nikolasburk** [comment]
Note that you can also find a sample generator here: https://github.com/pantharshit00/prisma-docs-generator (built by @pantharshit00 🎉 )

**Comment by janpio** [comment]
Right now we do not have plans to add this.

If we ever do, it will probably be via https://github.com/prisma/prisma/issues/7209
