### ISSUE TITLE
Migration engine error

### ISSUE THREAD

**Issue by md-nazim-Hossain** [prisma/prisma#17887]
when i run the command: `npx prisma migrate dev  --name init`,
Show the below error
```
Error: Migration engine exited. Error: Command failed with exit code 3221225781: E:\projects\Practice\prisma\prisma-3\node_modules\@prisma\engines\migration-engine-windows.exe cli --datasource <REDACTED> can-connect-to-database
```

**Comment by mcbethio** [comment]
Hey, Please can you send up your prisma schema and the version you are using. Thanks

**Comment by janpio** [comment]
The related issue https://github.com/prisma/prisma/issues/9940 actually includes the resolution to this: Your Windows is missing the Microsoft Visual C++ 2015 Redistributable. Install that, and the problem should be gone. We need a better error message here.

**Comment by reeveboy** [comment]
> The related issue #9940 actually includes the resolution to this: Your Windows is missing the Microsoft Visual C++ 2015 Redistributable. Install that, and the problem should be gone. We need a better error message here.

Thanks a lot! That worked for me.

Here's the download link. 
https://tinyurl.com/2e26jb57

**Comment by SamuelSousa1984** [comment]
Even after I installed Microsoft Visual C++ 2015 Redistributable, the error still persists
