### ISSUE TITLE
`Error: unreachable` trying to Make Either Field Required (but not voff)

### ISSUE THREAD

**Issue by manavm1990** [prisma/prisma#17889]
Hi Prisma Team! The following command just crashed.

## Command

`generate`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v19.4.0            | 
| Prisma CLI  | 4.10.1             | 
| Engine      | aead147aa326ccb985dcfed5b065b4fdabd44b19| 

## Error
```
Error: unreachable
```

---

```
location String?
  latLong  LatLong?
  @@unique([location, latLong])
```

Folks can give a location string or `LatLong`:

```
type LatLong {
  lat Float
  long Float
}
```

**Comment by janpio** [comment]
I can reproduce this with the following Prisma schema:

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Foo {
  id       Int      @id @map("_id") 
  name     String
  location String?
  latLong  LatLong?
  @@unique([location, latLong])
}

type LatLong {
  lat Float
  long Float
}
```

**Comment by janpio** [comment]
Probably also the same: https://prisma-errors.netlify.app/report/14542

**Comment by jkomyno** [comment]
@janpio I confirm the report you linked is the same.

The actual error on Rust is:

```
RuntimeError: panicked at 'called `Option::unwrap()` on a `None` value', query-engine/prisma-models/src/internal_data_model.rs:64:14
```
