### ISSUE TITLE
Unreachable code in generate

### ISSUE THREAD

**Issue by shaolinjr** [prisma/prisma#17881]
Hi Prisma Team! The following command just crashed.

## Command

`generate`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v18.12.1           | 
| Prisma CLI  | 4.10.1             | 
| Engine      | aead147aa326ccb985dcfed5b065b4fdabd44b19| 

## Error
```
Error: unreachable
```

**Comment by shaolinjr** [comment]
Discovered! I added @unique in a composite-type. The interpreter didn't complain to me, but once I removed and called the `generate` command it started working again

**Comment by janpio** [comment]
Can you share the schema _with_ the error that caused this? That error should never happen, and if we had the (part of the) schema for this, we could easily reproduce and then repair.

**Comment by jharrell** [comment]
Hello! 

Unfortunately, without further info we're going to have to close this issue. Please leave a comment or open a new issue with the info requested and we'll take another look!

Thank you
