### ISSUE TITLE
Filter conditions help needed

### ISSUE THREAD

**Issue by YannSuissa** [prisma/prisma#1789]
I'm using prisma2 for some weeks now, but i'm often stuck because of lack of documentation on some specifics points. I'm trying to do a simple query like `WHERE value > 1` I can't find any examples.
In prisma1 it's something with `<fieldnams>_gt` for greater than as explained here : 
[https://github.com/prisma/prisma/issues/1890](https://github.com/prisma/prisma/issues/1890)

That should look like this :

```
t.list.field('blocks_others', {
  type: 'Block',
  args: { 
    owner_address_exclude: stringArg({ nullable: true }),        
    value: intArg({ nullable: true }),        
  },
  resolve: (parent, { owner_address_exclude, value }, context) => {
    return context.prisma.block.findMany({
      where: { 
        NOT : {
          owner_address : owner_address_exclude
        },
        resale_price_gt : value
      },
      orderBy: { id: 'asc' },
    })
  },
})
```
And I get : 

```
Unknown arg `resale_price_gt` in where.resale_price_gt for type BlockWhereInput. Did you mean resale_price`? Available args: ...
```
Thanks for helping 
Best

**Comment by pantharshit00** [comment]
Filters are objects in Prisma 2. For example for the following schema:
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id String @id @default(cuid())
  value Int
}

```


You can perform `WHERE value > 1` like so:
```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const testData = await prisma.user.findMany({
    where: {
      value: {
        gte: 10
      }
    }
  });
  console.log(testData);
}

main();
```

I agree that we need to improve our current documentation for filters. Marking this as a docs issue.

**Comment by pantharshit00** [comment]
Also, if you are using Typescript, you can explore the API in your editor. That helps you writing your queries:
![image](https://user-images.githubusercontent.com/22195362/76620822-114ae280-6554-11ea-9933-e8095b65ab71.png)

**Comment by hatchli** [comment]
> Filters are objects in Prisma 2. For example for the following schema:
> 
> ```prisma
> // This is your Prisma schema file,
> // learn more about it in the docs: https://pris.ly/d/prisma-schema
> 
> datasource db {
>   provider = "sqlite"
>   url      = env("DATABASE_URL")
> }
> 
> generator client {
>   provider = "prisma-client-js"
> }
> 
> model User {
>   id String @id @default(cuid())
>   value Int
> }
> ```
> 
> You can perform `WHERE value > 1` like so:
> 
> ```ts
> import { PrismaClient } from "@prisma/client";
> 
> const prisma = new PrismaClient();
> 
> async function main() {
>   const testData = await prisma.user.findMany({
>     where: {
>       value: {
>         gte: 10
>       }
>     }
>   });
>   console.log(testData);
> }
> 
> main();
> ```
> 
> I agree that we need to improve our current documentation for filters. Marking this as a docs issue.

Does this filtering functionality only work on findMany? IDE is preventing its use on findOne.

**Comment by Sytten** [comment]
Yes currently only unique attributes can be used in the findOne, though there is any issue tracking that improvement.

**Comment by mhwelander** [comment]
Documentation now available: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering 📚

**Comment by oussamabouchareb** [comment]
I'm facing the same error except I'm not using any string filters
my schema:
```
model BlackListed {
  id     String  @default(uuid()) @id
  token  String?
  reason String?
}
```
and the code I'm executing is the following:
```
    const isBlackListed = await prisma.blackListed.findOne({
      where: {
        token: usertoken,
      },
    });
```
and it causes the following error:
```
Unknown arg `token` in where.token for type BlackListedWhereUniqueInput. Did you mean `id`? Available args:
type BLackListedWhereUniqueInput {
  id?: String
}
```

**Comment by oussamabouchareb** [comment]
a workaround I found for this is setting token as unique in schema.prisma and using:
```
    const isBanned = await prisma.banned.findMany({
      where: {
        token: usertoken,
      },
    });
```

**Comment by pantharshit00** [comment]
This is expected. `token` is not a unique property, there is always a chance the the when you query by `token` it will return more than one record. 

So will need to use `findMany` here `findOne` is meant to query one record identified by a unique identifier. Or you can make the `token` property unique but that doesn't make much sense in this case.

**Comment by oussamabouchareb** [comment]
thank you for taking the time to clarify
