### ISSUE TITLE
`prisma generate --generator` not an option when installing ONLY @prisma/client 4.10.1

### ISSUE THREAD

**Issue by PaulSearcy** [prisma/prisma#17916]
### Bug description

When installing _only_ `@prisma/client:4.10.1`, calling the `prisma` executable with `--generator` options results in error message. 

Running `prisma --version` gives. 
```
prisma                  : 4.8.1
@prisma/client          : 4.10.1
```

Since `--generator` is a new options for `generate` as of `4.10` my bug report. Is why doesn't installing `@prisma/client:4.10.[0|1]` also install `prisma:4.10.[0|1]` rather than `4.8.1`?

### How to reproduce

```
npm i @prisma/client
./node_modules/.bin/prisma generate --generator <client>
```

### Expected behavior

`--generate` is a valid options for `prisma generate`
Installing _only_ `@prisma/client:4.10.[0|1]` results in installing the same `prisma` version as  client version.  

### Prisma information

NA

### Environment & setup

- OS: macOS Monterey 12.6, Apple M1 Pro
- Database: NA
- Node.js version: v16.17.1

### Prisma Version

```
prisma                  : 4.8.1
@prisma/client          : 4.10.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by janpio** [comment]
Your project somehow decided to install `prisma@4.8.1` - that is not something Prisma controls. By default it would try to install the same version your are installing, or `latest` - but never an older version.

Did you already have `prisma` with that older version in your `package.json` before?
Do you have a global `prisma` installation?
What does `npm list prisma` output in that project?
Is `prisma@4.8.1` actually in your `package.json` now?

**Comment by Weakky** [comment]
Hey @PaulSearcy,

Did you get a chance to have a look at @janpio's comment? His questions might help us to move your issue forward.

Thank you 🙏

**Comment by jharrell** [comment]
Hi @PaulSearcy 

Following up: thank you for the info but we'd love if you followed @janpio 's comment and provide a bit more info. 

Thank you!
