### ISSUE TITLE
PrismaClientKnownRequestError is no longer identifiable

### ISSUE THREAD

**Issue by skworden** [prisma/prisma#17945]
### Bug description

Checking the instance of a Prisma error no longer works.  It worked for quite some time, however, it stopped working after we did package update to v4.

`error instanceof PrismaClientKnownRequestError`  will always return `false` even when it's a known error e.g. unique constraint violation - P2002.

This change prevents us from catching known Prisma errors as we used to with `error instanceof PrismaClientKnownRequestError`. It broke all of our server-side validation checks since we no longer have a guaranteed way to detect Prisma errors.

### How to reproduce

Try to perform Prisma.create on a unique constraint that already exists to trigger a prisma error code 2002.  I believe the problem persist on other error codes as well but I cannot confirm. 

### Expected behavior

Known Prima errors should be able to be caught with `error instanceof PrismaClientKnownRequestError`

### Prisma information

```prisma
model Link {
  companyId  String   @db.Uuid
  id         String   @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  type       String 

  @@unique([companyId, type])
  @@map("link")
}
```

```ts
await prisma.companyLink.create({data:{type:"TEST", companyId:"company-uuid"}}});
```

### Environment & setup

- OS: Windows WSL - Ubuntu 
- Database: PostgreSQL
- Node.js version: 16.15.0

### Prisma Version

```
prisma: 4.10.0
@prisma/client: 4.10.0
```

**Comment by kukuew** [comment]
I had the same. I have fixed it in a next way:
```typescript
import { Prisma } from '@prisma/client';

if (error instanceof Prisma.PrismaClientKnownRequestError) {
  // your code
}

```

Docs reference https://www.prisma.io/docs/concepts/components/prisma-client/handling-exceptions-and-errors

**Comment by SevInf** [comment]
@lifedup could you please share the full code snippet, including the imports. I mostly want to know where did you import `PrismaClientKnownRequestError`. The way @kukuew describes is the way it supposed to work. `@prisma/client` does not export `PrismaClientKnownRequestError` without `Prisma` namespace, so I am not sure where are you getting it from.

**Comment by leighman** [comment]
This seems to have been broken in 4.10 by the deprecation of `import { PrismaClientKnownRequestError } from '@prisma/client/runtime'`.
Is it now a different object entirely depending where it's imported from?

**Comment by SevInf** [comment]
Depending on the configuration, there was always (even pre 4.10) a possibility that import from `runtime` module will not match the one imported from `client`. `@prisma/client/runtime` is a private module and it is not supposed to be used in the app code. Future proof and supported way of handling errors is importing it from `Prisma` namespace from `@prisma/client` module as our [docs](https://www.prisma.io/docs/concepts/components/prisma-client/handling-exceptions-and-errors) suggest.

**Comment by andyjy** [comment]
> @prisma/client/runtime is a private module and it is not supposed to be used in the app code

There is a bit of a foot-gun here where VSCode (and I assume other editors) will auto-generate an import from `@prisma/client/runtime` if we type `PrismaClientKnownRequestError` (without the `Prisma.` namespace prefix) and hit enter to select from the autocompleted suggested imports.  This type-checks just fine so it's easy to miss this isn't the documented import of `Prisma.PrismaClientKnownRequestError` from the public namespace.

It would be nice if the exports from the internal/private `@prisma/client/runtime` module could be prevented from showing up in editor autocomplete. (I think this could be achieved by refactoring the "private" runtime module to export under it's own namespace, for example - there may be better ways to achieve this.)

**Comment by SevInf** [comment]
@andyjy @lifedup Thank you for the pointers, VS Code autocomplete is definitely a problem we'd like to address here.

**Comment by mbifenzi** [comment]
> I had the same. I have fixed it in a next way:
> 
> ```ts
> import { Prisma } from '@prisma/client';
> 
> if (error instanceof Prisma.PrismaClientKnownRequestError) {
>   // your code
> }
> ```
> 
> Docs reference https://www.prisma.io/docs/concepts/components/prisma-client/handling-exceptions-and-errors

l3ezz it works perfectly

**Comment by wickedknock** [comment]
This is working for me on localhost but not when I use docker.

**Comment by flan02** [comment]
I fixed the problem in this way. Until now it works well.
```ts
// imported
import { PrismaClientKnownRequestError } from "@prisma/client/runtime/react-native.js"
```

```ts
// coding inside try-catch
 if (error) {
      if (error instanceof PrismaClientKnownRequestError) {
        if (error.code === "P2002") {
          return {
            message: "Email already Exist in the DB",
          };
        }
      }
    }
```

**Comment by GustavoPAraujo** [comment]
Thank you, flan02, for your help! I'am almost a year late to the conversation, but you stil fixed my error ;)

**Comment by dingkai031** [comment]
> This is working for me on localhost but not when I use docker.

I know its late, but... I found a solution.
Im using docker and was following the instructions from freecodecamp with docker.
I change the import from 
`import { Prisma } from '@prisma/client';`
to
`import { Prisma } from '../../generated/prisma';`
and use it like this :
```
      if (
        error instanceof
        Prisma.PrismaClientKnownRequestError
      ) {
        if (error.code === 'P2002') {
          throw new ForbiddenException(
            'Email already exists',
          );
        }
      }
```

**Comment by IanGraingerGMSL** [comment]
Sorry, none of the above work for me. prisma@6.18.0 Tried each one in turn. As the bug title says - `PrismaClientKnownRequestError` appears to be no longer identifiable 😦 

This does work:
```
    const prismaError = error as
      | { code?: string; constructor?: { name?: string } }
      | undefined;

    if (
      prismaError?.code === "P2002" &&
      prismaError?.constructor?.name === "PrismaClientKnownRequestError"
    ) {
```

**Comment by sneakyteak** [comment]
This just bit me too. For whatever reason the runtime library import _used_ to work, which is what threw me off the scent. It's working correctly now that I'm importing the definition from the client namespaced to `Prisma`, but it was not obvious to me that the runtime library definition was no good.
