### ISSUE TITLE
[prisma-test-utils] PostgreSQL: `WrongType`

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#1794]
Some databases tested via `prisma-test-utils` (in Introspection CI) have a type not yet supported by Prisma. 

Errors looks like this (example `standup-slack-bot`):

```
2020-03-11T13:58:27.129Z prisma-client Prisma Client call:
2020-03-11T13:58:27.130Z prisma-client prisma.eventids.create({
  data: {
    created_at: new Date('2100-05-30T04:43:46.598Z'),
    event_id: '4c2cba28-f4c6-55aa-9680-dac0c4e43a1a'
  }
})
2020-03-11T13:58:27.130Z prisma-client Generated request:
2020-03-11T13:58:27.130Z prisma-client mutation {
  createOneeventids(data: {
    created_at: "2100-05-30T04:43:46.598Z"
    event_id: "4c2cba28-f4c6-55aa-9680-dac0c4e43a1a"
  }) {
    created_at
    event_id
  }
}

...

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(0), cause: Some(WrongType { postgres: Type(Timestamptz), rust: "core::option::Option<alloc::string::String>" }) }) })
    at PrismaClientFetcher.request (/home/runner/work/introspection-engine-output/introspection-engine-output/clients/postgresql_public_test_utils/standup-slack-bot/runtime/index.js:1:47203)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```prisma
model eventids {
  created_at DateTime
  event_id   String   @id
}
```

```sql
CREATE TABLE public.eventids (
    event_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
```

---

Internal notes: 

Specific type is listed in brackets next to the database log link. 

Test utils database(s) affected: 
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/postgresql_public_test_utils_niko-public-1_stderr.log (timestampz)
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/postgresql_public_test_utils_sonarqube_stderr.log  (bytea)
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/postgresql_public_test_utils_standup-slack-bot_stderr.log (timestampz)
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/postgresql_public_test_utils_odoo_stderr.log (bytea)

**Comment by tomhoule** [comment]
I did some manual testing - as of alpha 927 this is fixed, after the postgres types mapping work.

**Comment by janpio** [comment]
Can you confirm in test-utils @divyenduz?

**Comment by divyenduz** [comment]
As of 928. I can't see the `timestampz` error anymore but I can see see the ` bytea` error. As it stands: 

---

Internal notes:

Specific type is listed in brackets next to the database log link.

Test utils database(s) affected:

- https://github.com/prisma/introspection-engine-output/blob/test_utils_928/test-utils/results/postgresql_public_test_utils_sonarqube_stderr.log
-

**Comment by divyenduz** [comment]
This is not reproducible anymore with `2.1.0-dev.49`. Sonarqube now fails with https://github.com/prisma/prisma/issues/3007 instead.
