### ISSUE TITLE
Support openSUSE Tumbleweed

### ISSUE THREAD

**Issue by cubetastic33** [prisma/prisma#17947]
When running prisma on openSUSE Tumbleweed, it shows this warning:
```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "opensuse-tumbleweed". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
```

Can support be added for openSUSE?

**Comment by jkomyno** [comment]
Hi @cubetastic33, Alberto from Prisma here. I can confirm Prisma works on [OpenSuse Tumbleweed](https://github.com/prisma/ecosystem-tests/tree/dev/docker/opensuse-tumbleweed-amd64-openssl-3.0.x) on amd64 / x86_64.
We'll make sure you will no longer see this warning in the next Prisma release.
