### ISSUE TITLE
`prisma:engine` spans do not respect `suppressTracing()`

### ISSUE THREAD

**Issue by uhyo** [prisma/prisma#17953]
### Bug description

When using Prisma's `tracing` preview feature, `prisma:engine` spans do not respect parent context being [suppressTracing()](https://github.com/open-telemetry/opentelemetry-js/blob/279458e/packages/opentelemetry-core/src/trace/suppress-tracing.ts#L23)-ed.

### How to reproduce

See https://github.com/uhyo/prisma-trace-bug-repro for a complete reproduction.

#### Correctly Working Example
Suppose a Prisma query is run inside another span. Prisma-related spans become children of the span, which is expected behavior.

```ts
  await tracer.startActiveSpan("main-outer", async (span) => {
    try {
      await tracer.startActiveSpan("main-inner", async (span) => {
        try {
          const prisma = new PrismaClient();
          const count = await prisma.user.count();
          console.log({ count });
          await prisma.$disconnect();
        } finally {
          span.end();
        }
      });
    } finally {
      span.end();
    }
  });
```

Generated spans are visualized as follows, where we can see that Prisma-related spans are correctly placed below our `main-inner`span.

```
----- traceId = 2ad011bfec91f3dc46af7701e87c7484 -----
main-outer (dd2f5e0728196a28) sampled=true
  main-inner (c760fcd3b1fa373d) sampled=true
    prisma:client:operation (df101553ab91918a) sampled=true
      prisma:engine (9a1236432ce66c79) sampled=true
        prisma:engine:connection (bbfb416e35154346) sampled=true
        prisma:engine:db_query (85cae0bd1d1f746d) sampled=true
        prisma:engine:serialize (182fd59131b12f83) sampled=true
      prisma:client:connect (f3d1c10e9a91d985) sampled=true
      prisma:client:serialize (11d98ef1631251d0) sampled=true
    prisma:client:disconnect (2bfb1ab20b42b487) sampled=true
```

#### Buggy Example

Suppose we wrapped the Prisma operation with a context which is the result of `suppressTracing`. We expect any spans inside this context to be suppressed.

```ts
  await tracer.startActiveSpan("main-outer", async (span) => {
    try {
      await context.with(suppressTracing(context.active()), async () => {
        await tracer.startActiveSpan("main-inner", async (span) => {
          try {
            const prisma = new PrismaClient();
            const count = await prisma.user.count();
            console.log({ count });
            await prisma.$disconnect();
          } finally {
            span.end();
          }
        });
      });
    } finally {
      span.end();
    }
```

However, the results are as follows, which is not an expected behavior:

```
----- traceId = 6213818d0c6af646b6b0f33856ba95cc -----
prisma:engine (6eb3f82236027c35) sampled=true
  prisma:engine:connection (c6238593e8a4d3b1) sampled=true
  prisma:engine:db_query (b6df43690339ef65) sampled=true
  prisma:engine:serialize (e9a44dc6e66fbbf1) sampled=true
----- traceId = 2b328bd92ffd91b938adda78282e7c7e -----
main-outer (1f8f78bdd8513f05) sampled=true
```

Our `main-inner` span and also `prisma:client:*` spans correctly respect the suppression and have disappeared. However, `prisma:engine` spans started their own trace and remained.

### Expected behavior

`prisma:engine` spans should respect the suppression too.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["tracing"]
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

# (snip)
```

Note: the example uses SQLite but I also experienced this bug with PostgreSQL.

### Environment & setup

- OS: macOS, Linux
- Database: PostgreSQL, SQLite (other databases not tested)
- Node.js version: v16.19.0

### Prisma Version

```
prisma                  : 4.10.1
@prisma/client          : 4.10.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.10.1-1.80b351cc7c06d352abe81be19b8a89e9c6b7c110
Default Engines Hash    : aead147aa326ccb985dcfed5b065b4fdabd44b19
Studio                  : 0.481.0
Preview Features        : tracing
```

**Comment by JakeGinnivan** [comment]
I just hit this as well, for example I suppress the healthcheck route but the query I make to the database to ensure it has connectivity continues to be traced with no context of what triggered it.

**Comment by SevInf** [comment]
Can confirm with the repo, provided in original issue.
