### ISSUE TITLE
Prisma panics when `@id` field is marked with `@ignore`

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#17966]
Command: `prisma migrate dev`
Version: `4.10.0`
Binary Version: `ca7fcef713137fa11029d519a9780db130cca91d`
Report: https://prisma-errors.netlify.app/report/14532 
OS: `x64 linux 5.15.0-56-generic`

Rust Stacktrace:
```
RuntimeError: panicked at 'called `Option::unwrap()` on a `None` value', query-engine/prisma-models/src/builders/primary_key_builder.rs:17:79
```

Relevant part of the schema:

```prisma
model User {
  id      String   @id @ignore
  email   String   @unique
  name    String
}
```

**Comment by tomhoule** [comment]
This likely happens in `generate`, so QE code, the migration engine does not use prisma-models.

**Comment by jkomyno** [comment]
@tomhoule It happens on `getDMMF`

**Comment by jkomyno** [comment]
This error doesn't occur anymore, as of Prisma 6.
