### ISSUE TITLE
npx prisma db pull command error report 

### ISSUE THREAD

**Issue by yesj1234** [prisma/prisma#18016]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.14.1           | 
| Prisma CLI  | 4.10.1             | 
| Engine      | aead147aa326ccb985dcfed5b065b4fdabd44b19| 

## Error
```
Error: Error in migration engine.
Reason: 

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by jkomyno** [comment]
Hey @yesj1234, could you please share informations such as your Prisma schema, your OS version and architecture, your `prisma version` output, and describe which kind and version of database you're using? Without that info, we can't unfortunately understand and fix this issue. Thanks!

**Comment by jkomyno** [comment]
Hey @yesj1234, could you please reply to the question above? Thank you.

**Comment by yesj1234** [comment]
Hi jkomyno. 
The error report was made automatically while i was following some tutorial guide video on how to use prisma with nestjs.
Its been a while from the moment I made the report so I don't precisely remember the information you asked. sorry.

**Comment by yesj1234** [comment]
I will close this issue since it's no longer necessary. thank you.
