### ISSUE TITLE
Prisma unable to reconnect if initial connection fails

### ISSUE THREAD

**Issue by invakid404** [prisma/prisma#18071]
### Bug description

When letting Prisma connect lazily (i.e. by not calling `client.$connect()` explicitly, if the database is not running at the time of the initial connection, all subsequent attempts to connect fail as well.

### How to reproduce

1. Lose access to your database (e.g. by stopping it, disconnecting from a VPN, etc)
2. Start your Prisma application
3. Make the application run a query (e.g. by hitting some endpoint)
4. Observe the failure to connect
5. Regain access to your database (e.g. by restarting it, reconnecting to the VPN, etc)
6. Try running the query again
7. Observe that no matter how many times you try, Prisma still fails to connect, even with the database being accessible

Dummy HTTP application for reproduction purposes included below.

### Expected behavior

Prisma should be able to reconnect if a query is executed and the database is now available.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Dummy {
  id Int @id @default(autoincrement())
}
```

```ts
import * as http from "http";
import { PrismaClient } from "@prisma/client";

const client = new PrismaClient();

http
  .createServer(async (_req, res) => {
    try {
      const result = await client.$queryRaw`SELECT 1;`;

      res.write(JSON.stringify(result));
    } catch (err) {
      console.error(err);
    } finally {
      res.end();
    }
  })
  .listen(8080);
```

### Environment & setup

- OS: Funtoo Linux
- Database: PostgreSQL
- Node.js version: 18.14.0

### Prisma Version

```
prisma                  : 4.10.1
@prisma/client          : 4.10.1
Current platform        : debian-openssl-1.0.x
Query Engine (Node-API) : libquery-engine aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node)
Migration Engine        : migration-engine-cli aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.10.1-1.80b351cc7c06d352abe81be19b8a89e9c6b7c110
Default Engines Hash    : aead147aa326ccb985dcfed5b065b4fdabd44b19
Studio                  : 0.481.0
```

**Comment by invakid404** [comment]
Note that Prisma is able to reconnect just fine when the initial connection has succeeded, i.e. if the database dies after a connection had already been established, Prisma is able to reconnect properly when the database is restarted.

Attaching a video of me reproducing it using the code I posted above. As you can see, starting the application with the database stopped, running a query fails, hence the request doesn't output anything. Prisma refuses to reconnect even after starting the database. This doesn't happen if the database is up during the execution of the first query though. Prisma is able to reconnect just fine then.

https://user-images.githubusercontent.com/38114607/220995001-c2fdcd22-b4fc-4d5b-8258-647b2584a5f5.mp4

**Comment by dfoley112** [comment]
Seeing identical behavior on windows 10, SQL Server & Prisma 4.10

**Comment by josecastillog** [comment]
Seeing same behaviour on MacOS, SQL Server and Prisma 4.13

**Comment by janpio** [comment]
Alternative, simple reproduction in https://github.com/prisma/prisma/issues/19182

**Comment by Weakky** [comment]
Hey folks,

You can workaround this issue by enabling the `jsonProtocol` preview feature. If you can't switch to `jsonProtocol` just yet, the next release will contain a fix.

Thanks for bringing this to our attention 🙏
