### ISSUE TITLE
Prisma can't connect with an IPv6 host (on e.g. Fly.io)

### ISSUE THREAD

**Issue by Fenntasy** [prisma/prisma#18079]
### Bug description

In a `DATABASE_URL`, if the host is an IPv6, Prisma will throw an error, for instance, using this connection string 

```
postgresql://postgres:postgres@[::1]:5432/db
```
will result in this error

```
Can't reach database server at `[::1]`:`5433`
```

I know that locally I could always use `localhost` or `127.0.0.1` but the bug is more of a problem if you're using a service like Fly that has started populating `DATABASE_URL` with IPv6 addresses. It just doesn't work out of the box.

`psql` and the `pg` node package don't have a problem with them so it's a problem with Prisma.

### How to reproduce

Any local PG connection string looking like 
```
postgresql://postgres:postgres@[::1]:5432/db
```
will create the error

### Expected behavior

It should be able to connect.

### Prisma information

The schema or queries are irrelevant here since it just doesn't connect.

### Environment & setup

- OS: at least macOS and linux
- Database: PostgreSQL
- Node.js version: v18.12.1 (but it doesn't seem linked to that)

### Prisma Version

```
prisma                  : 4.10.1
@prisma/client          : 4.10.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.10.1-1.80b351cc7c06d352abe81be19b8a89e9c6b7c110
Default Engines Hash    : aead147aa326ccb985dcfed5b065b4fdabd44b19
Studio                  : 0.481.0
Preview Features        : tracing
```

**Comment by cinder-star** [comment]
I would like to investigate on this issue

**Comment by DAlperin** [comment]
Hello from fly.io! As @Fenntasy noted, this bug has an unfortunate effect on prisma apps running on our platform. We'd love to see this fixed. Let me know if any additional information would be useful, or any other way we can help.

**Comment by maticzav** [comment]
@janpio is there any workaround for this that we could use?

**Comment by cinder-star** [comment]
@maticzav if you are facing this issue on fly.io, you can attach an ipv4 address to your database and use that. Read [here](https://fly.io/docs/postgres/connecting/connecting-external/)

**Comment by maticzav** [comment]
@cinder-star sweet, thanks! 

And how can I find `user`, `password` and `dbname` of a running database?

**Comment by cinder-star** [comment]
The dbname, user and password are the same as the connection string with the ipv6 one. You just need to replace the hostname with the ipv4 host. @maticzav

**Comment by maticzav** [comment]
@cinder-star thanks! How can I find the original string though? Sorry for polluting this thread, though surely I can't be the only one with this problem.

I have crawled through all the docs and every page in my dashboard and can't find the full db connection string. 😅

**Comment by maticzav** [comment]
@cinder-star I tried setting up the IPv4 url and manually changing the `postgresql` url, but that didn't play well with the Prisma Migrate. I did manage to get it working though.

1. I checked the credentials, which I also found out are only displayed once when you create the PG instance (so you can't use the "automatically" created instance),
2. I replaced the IPv6 address with `myapp.internal` (e.g. `postgresql://postgres:password@myapp.internal:5432/dbname`).

Some useful links and code chunks that helped me figure out

- https://fly.io/docs/postgres/connecting/app-connection-examples/#connecting-with-prisma-node-js
- https://fly.io/docs/postgres/connecting/connecting-external/

```toml
[build]
  dockerfile = "server/Dockerfile"

[deploy]
  release_command = "pnpm migrate:db"
```

```json
{
  "scripts": {
    "migrate:db": "prisma migrate deploy --schema server/prisma/schema.prisma"
  }
}
```


Thanks again for helping me again 🙏 !

**Comment by cinder-star** [comment]
@maticzav i think you need to add sslmode to the url as well.
`postgresql://postgres:password@myapp.internal:5432/dbname?sslmode=disabled`
Something like that

**Comment by Fenntasy** [comment]
> @maticzav i think you need to add sslmode to the url as well.
> `postgresql://postgres:password@myapp.internal:5432/dbname?sslmode=disabled`
> Something like that

It's not needed for the `.internal` URL.

But in any case, this issue shouldn't be about how to fix the problem with Fly when the problem lies with Prisma.

**Comment by VyrekXD** [comment]
Is there any fix to this problem?

**Comment by alula** [comment]
This affects everything that uses IPv6 addresses in URLs directly, not just fly.io, old title was fine
