### ISSUE TITLE
imports from "@prisma/client/runtime" are deprecated.

### ISSUE THREAD

**Issue by bncal** [prisma/prisma#18101]
### Bug description

Hi. 
Today I have created a new repo and installed prisma in my app, then created my schema and yada yada, only to find that the imports are now deprecated.

`imports from "@prisma/client/runtime" are deprecated.
Use "@prisma/client/runtime/library",  "@prisma/client/runtime/data-proxy" or  "@prisma/client/runtime/binary"`

On NEXTJS 13 was working fine, updated to NEXTJS 13.2 (where they also updated the API routes) and now it's giving me these warnings. Running `npx prisma studio` throws these warnings as well but everything works fine. I have now tested on my old app (that is not on nextjs13.2) and i'm getting thrown the same warning.

my packages:

`  "dependencies": {
    "@types/node": "18.14.1",
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
    "next": "13.2.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.43.2",
    "typescript": "4.9.5"
  },
  "devDependencies": {
    "prisma": "^4.10.1"
  }
}` 

### Expected behavior

`Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Prisma Studio is up on http://localhost:5555
imports from "@prisma/client/runtime" are deprecated.
Use "@prisma/client/runtime/library",  "@prisma/client/runtime/data-proxy" or  "@prisma/client/runtime/binary"`

### Prisma information

```prisma
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "mysql"
    url      = env("DATABASE_URL")
}

model User {

    id          Int             @id @default(autoincrement())
    email       String          @unique
    username    String          @unique                                 // @username
    password    String
    fname       String                                                  // The displayed "full name" above @username
    posts       Post[]
    isOfficial  Boolean         @default(false)                         // Is this user an official account?
    isModerator Boolean         @default(false)                         // Is this user a moderator?
    isBanned    Boolean         @default(false)                         // Is this user banned?
    bannedUntil DateTime?                                               // If banned, when will the ban expire?
    createdAt   DateTime        @default(now())

}

model Post {

    id        Int     @id @default(autoincrement())
    text      String
    media     String?                                                   // The media file (image, video, etc.)
    author    User    @relation(fields: [authorId], references: [id])   // The author of the post
    authorId  Int
    createdAt DateTime @default(now())
}


```

```ts
import { PrismaClient } from "@prisma/client";
declare let global: { prisma: PrismaClient };

let prisma: PrismaClient

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient()
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient()
  }
  prisma = global.prisma
}
export default prisma
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
^4.10.1
```

**Comment by bncal** [comment]
I'd like to add that I can't do `prisma -v` or else I get an error, and can't everywhere I import PrismaClient, I get that the module cannot be found.

**Comment by bncal** [comment]
I tried removing the modules with `rm -r node_modules` then reinstalling them with `npm i`, ran prisma studio for testing and downloaded the engines (Downloading Prisma engines for node-API for windows), then throw `Use "@prisma/client/runtime/library",  "@prisma/client/runtime/data-proxy" or  "@prisma/client/runtime/binary"`

**Comment by janpio** [comment]
The problem of the unexpected warning message in `prisma studio` is known and will be fixed in the next version. 

Do you have any other problem besides this warning in `prisma studio`?

**Comment by bncal** [comment]
@janpio although I can't use commands such `prisma -v`, I don't have other problems to report.

**Comment by janpio** [comment]
What error are you getting on `npx prisma -v`? I don't see that mentioned before.

**Comment by bncal** [comment]
`Can't load file at C:\Users\alessandro\AppData\Roaming\npm\prisma.ps1. Script execution is disabled on your system
    + CategoryInfo          : Errore di protezione: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
`
but i believe it's more related to my computer than prisma itself. you can close the issue anyway

**Comment by janpio** [comment]
4.11.0 is out and should fix the Studio problem by the way.

**Comment by alukaszew** [comment]
Hi,
I have similar problem with **prisma** i NextJS13

```
./prisma/@prisma/client/index.js
Module not found: Can't resolve './runtime/library'
```

and the `runtime `folder is empty.

Any solution for this?

**Comment by bncal** [comment]
> Hi, I have similar problem with **prisma** and NextJS13
> 
> ```
> ./prisma/@prisma/client/index.js
> Module not found: Can't resolve './runtime/library'
> ```
> 
> and the `runtime` folder is empty.
> 
> Any solution for this?

Hi, a new update is available that seems to fix the issue.
Run the following to update                        
```
npm i --save-dev prisma@latest                   
npm i @prisma/client@latest  
```
