### ISSUE TITLE
[Cloudflare Workers] Error: Script startup exceeded CPU time limit. [code: 10021]

### ISSUE THREAD

**Issue by n3oney** [prisma/prisma#18104]
3### Bug description

I can't get my worker to deploy with Prisma.

I know that this issue is related to the amount of tables or relations I have. After debugging a bit, I believe it's caused by decompressing the `DMMF` from base64.
When looking in the source code, I can see that on the worker deploy it will do that every time. On my PC, in `miniflare`, it takes 50ms to run `decompressFromBase64`, and the Workers have a 200ms limit.

After manually decompressing the base64 string, it results in a 2MB object.

The only way I can get it to deploy is by removing some tables or relations,

### How to reproduce

1. Make a new project on Cloudflare Workers
2. Add a larger amount of tables (I have 15)
3. Add some relations between the tables
4. Try to deploy

### Environment & setup

- OS: Linux arch 6.1.12-zen1-1-zen
- Database: CockroachDB, with Prisma Data Proxy
- Node.js version: v18.1.0

### Prisma Version

```
4.10.1
```

**Comment by SevInf** [comment]
Hi @n3oney!
It happens that 4.11 release includes the feature addressing exactly this problem.  Could you try updating and enabling `jsonProtocol` preview feature. In you schema file, in `generator` block, add:

```prisma
previewFeatures = ["jsonProtocol"]
```

Enabling it would save you some cold start time as well as bundle size. The bigger the schema, the bigger the win should be. In particular, this whole decompression/base64 routine you describing in your issue should be gone. 

Be warned though, it is still an early preview and some things might not work correctly yet.  We'd like to hear your feedback though, here or in [dedicated feedback issue for this feature](https://github.com/prisma/prisma/issues/18095)

**Comment by n3oney** [comment]
Wow, that worked perfectly! -100kb off the gzipped bundle and a successful deploy on the first try. Thank you

**Comment by craigsc** [comment]
was just hitting this issue myself and the jsonProtocol preview feature fixed it, thanks @SevInf (and @n3oney for making the issue)!

**Comment by Ehesp** [comment]
I'm a bit confused, does prisma still only work with the data proxy on cloudflare workers/pages?

Ive just added the jsonProtocol option set and still run into this issue. I'm using Mongo with 3 collections, however use the edge client import.

The linked issue seems to suggest this doesn't work with the data proxy, but I didn't think it was possible to deploy to it without.

**Comment by Ehesp** [comment]
Yeah this still doesn't help me :( 

I'm using Remix, but my setup is:

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["jsonProtocol"]
}
```

This file imports the edge package, but uses the environment variables from Remix context (see https://github.com/prisma/prisma/issues/15958)

```ts
import { PrismaClient } from "@prisma/client/edge";

let db: PrismaClient;

declare global {
  var __db: PrismaClient | undefined;
}

export function getDb(args: DataFunctionArgs) {
  const options = {
    datasources: {
      db: {
        url: args.context.DATABASE_URL as string,
      },
    },
  };

  if (process.env.NODE_ENV === "production") {
    if (!db) {
      db = new PrismaClient(options);
    }
  } else {
    if (!global.__db) {
      global.__db = new PrismaClient(options);
    }
    db = global.__db!;
  }

  return db;
}
```

My build/start command:

```
  "scripts": {
    "build": "npm run prisma:generate && remix build",
    "start": "cross-env NODE_ENV=production npm run wrangler",
    "prisma:generate": "npx prisma generate --data-proxy"
  }
```

Log wise, everything is as expected, Prisma generates, assets upload, and then:

```
Error: Failed to publish your Function. Got error: Error: Script startup exceeded CPU time limit.
```

**Comment by Ehesp** [comment]
Ended up lazy loading the Prisma client, which seems to have worked.

Requires a double await: `await (await getDb(args)).user.etc`:

```js

let db: PrismaClient;

declare global {
  var __db: PrismaClient | undefined;
}

export async function getDb(args: DataFunctionArgs) {
  const options = {
    datasources: {
      db: {
        url: args.context.DATABASE_URL as string,
      },
    },
  };

  if (process.env.NODE_ENV === "production") {
    if (!db) {
      const { PrismaClient } = await import("@prisma/client/edge");
      db = new PrismaClient(options);
    }
  } else {
    if (!global.__db) {
      const { PrismaClient } = await import("@prisma/client/edge");
      global.__db = new PrismaClient(options);
    }
    db = global.__db!;
  }

  return db;
}
```

**Comment by janpio** [comment]
If you are still getting the error this issue was originally about, please open a new issue and describe the full problem. Thanks.
