### ISSUE TITLE
jsonProtocol doesn't query enum fields by default

### ISSUE THREAD

**Issue by n3oney** [prisma/prisma#18148]
### Bug description

When querying a table that has an enum field with the jsonProtocol feature enabled, the data won't include the enum field by default.

### How to reproduce

1. Enable the `jsonProtocol` preview feature
2. Query some table `await prisma.db.tableName.findMany();`

### Expected behavior

The returned data will be the same as without the jsonProtocol feature

With jsonProtocol
```js
const products = await prisma.db.productInfo.findMany();

/*
{
  "id": "01002ac5-0098-443f-84ac-3294b3169aae",
  "name": "Product one",
  "description": "Product number one",
}
*/
```

Without jsonProtocol
```js
const products = await prisma.db.productInfo.findMany();

/*
{
  "id": "01002ac5-0098-443f-84ac-3294b3169aae",
  "name": "Product one",
  "status": "Enabled",
  "description": "Product number one",
}
*/
```

Adding a `select` to the query and explicitly telling it to select that field seems to fix it.

With jsonProtocol
```js
const products = await prisma.db.productInfo.findMany({
      select: {
        status: true,
        id: true,
        name: true,
        description: true
      }
});


/*
{
  "id": "01002ac5-0098-443f-84ac-3294b3169aae",
  "name": "Product one",
  "status": "Enabled",
  "description": "Product number one",
}
*/
```

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["jsonProtocol"]
}

datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}

model ProductInfo {
  id                String             @id(map: "primary") @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  status            Status
  name              String
  description       String

  @@map("product_info")
}

enum Status {
  Enabled
  Disabled
  Hidden

  @@map("status")
}
```

### Environment & setup

- OS: Arch Linux
- Database: CockroachDB, with Data Proxy
- Node.js version: v19.7.0

### Prisma Version

```
4.11.0
```

**Comment by revmischa** [comment]
Confirmed this is happening for me after upgrading from 4.10.1 to 4.11.0

**Comment by revmischa** [comment]
Thanks for fixing this quickly! I would really love to be able to try out the rest of 4.11 so if there is any way you can release a patch version with this fix that would be quite nice

**Comment by janpio** [comment]
A patch is quite a big deal in what it signals to all our users. But via this PR https://github.com/prisma/prisma/pull/18165 it will be available in `prisma@dev` soon, which right now has pretty much no other differences to 4.11. So if you ping that specific version that will include #18165 you should have pretty much the same as a patch and can safely test.

**Comment by janpio** [comment]
Update: `prisma@4.12.0-dev.4` is out and should include the fix for this issue.

**Comment by SevInf** [comment]
`prisma@4.12.0-dev.9` contains fix for enum lists as well.
@veiico I can't reproduce the issue with `dev.8` - for me it works. Could you try with `dev.9`.

**Comment by revmischa** [comment]
I'm using dev.9 and the enum field is missing when calling findFirstOrThrow

Here you can see `status` is not present in the fetched object:
![image](https://user-images.githubusercontent.com/245131/225106670-259ea523-0fbc-4aac-acb1-cbc68aef4f13.png)

**Comment by SevInf** [comment]
@revmischa @veiico Could I see you `prisma --version` output? I am struggling to reproduce it locally. Also, couple of follow up question:
- Did you re-run `prisma generate` after updating to `dev.9`?
- Are you using DataProxy or normal prisma distribution?

**Comment by revmischa** [comment]
> @revmischa @veiico Could I see you `prisma --version` output? I am struggling to reproduce it locally. Also, couple of follow up question:
```
prisma                  : 4.12.0-dev.9
@prisma/client          : 4.12.0-dev.9
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine da9cbf177f656f6a0002c6749f5f689a1e3cc9e4 (at ../node_modules/.pnpm/@prisma+engines@4.12.0-dev.9/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli da9cbf177f656f6a0002c6749f5f689a1e3cc9e4 (at ../node_modules/.pnpm/@prisma+engines@4.12.0-dev.9/node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.12.0-14.da9cbf177f656f6a0002c6749f5f689a1e3cc9e4
Default Engines Hash    : da9cbf177f656f6a0002c6749f5f689a1e3cc9e4
Studio                  : 0.483.0
Preview Features        : fullTextSearch, orderByNulls, jsonProtocol
```


> * Did you re-run `prisma generate` after updating to `dev.9`?
Yes

> * Are you using DataProxy or normal prisma distribution?
Not using DataProxy
