### ISSUE TITLE
Missing `PrismaPromise` export after update from 4.9.0 to 4.11.0

### ISSUE THREAD

**Issue by wiput1999** [prisma/prisma#18143]
### Bug description

I got No `PrismaPromise` exported from Prisma generated client

### How to reproduce

1. Generate Prisma Client
2. Import `PrismaPromise` from generated client
3. Got no exported member

### Expected behavior

On 4.9.0 is working before upgrade not sure what change on code generator from 4.9.0 to 4.11.0

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
  binaryTargets   = ["native", "rhel-openssl-1.0.x", "linux-arm64-openssl-1.0.x"]
  output          = "../layers/prisma"
}
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.15.0
- TypeScript : 4.9.5

### Prisma Version

```
4.11.0
```

**Comment by s-montigny-desautels** [comment]
Since 4.10, the `PrismaPromise` type is under the `Prisma` namespace. 

```ts
import { Prisma } from "@prisma/client";

const queries: Prisma.PrismaPromise<any>[] = [];
```

I don't really know why it was moved, though... I didn't see it in the release notes.

**Comment by wiput1999** [comment]
@s-montigny-desautels I've no idea about this too since nothing mention about this in release note or breaking changes.

**Comment by brandonin** [comment]
Do we know if the expectation is that `Prisma.PrismaPromise` is going to be the new paradigm moving forward, was it a mistake moving this entirely, or will they add backward compatibility with newer versions and utilize both?

**Comment by s-montigny-desautels** [comment]
For reference, it was changed in this PR #17594.
