### ISSUE TITLE
Prisma should not fail if directUrl is set in schema but the env var is missing/empty

### ISSUE THREAD

**Issue by mmachatschek** [prisma/prisma#18155]
### Bug description

Adding the `directUrl` to the `datasource` block and not adding the env var leads to errors in the migration engine.

### How to reproduce

1. add prisma schema from below
2. set environment `DATABASE_URL`
3. run migration command
4. prisma errors and outputs `error: Environment variable not found: DIRECT_URL.`

### Expected behavior

I expect that prisma has the same behaviour as it has with the `shadowDatabaseUrl`

https://github.com/prisma/prisma-engines/pull/1672

### Prisma information

```prisma
datasource sqlite {
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
  directUrl         = env("DIRECT_URL")
  provider          = "sqlite"
}

generator client {
  provider = "prisma-client-js"
}

model Todo {
  id    String @id @default(cuid())
  title String @default("")
}
```

### Environment & setup

- OS: all
- Database: all
- Node.js version: all

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by janpio** [comment]
But running a migration command will try to use the value of `directUrl` - so you will run into an error anyway. What is your use case of having `directUrl`, using a `migrate` command but then expecting it not to validate the env var?
