### ISSUE TITLE
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.

### ISSUE THREAD

**Issue by chriskuech** [prisma/prisma#18170]
### Bug description

We have a NestJS app that uses Prisma. We have not modified our DevOps code nor our prisma integration code recently, yet our app suddenly crashes at startup only when running in our deployed Azure App Service environment.

The logs contain the following unexpected error, which is why I am reporting it 😄 :

```
 Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
 In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
     at new PrismaClient (/home/site/wwwroot/node_modules/.prisma/client/index.js:3:11)
     at new PrismaService (/home/site/wwwroot/dist/src/prisma/prisma.service.js:21:21)
     at Injector.instantiateClass (/home/site/wwwroot/node_modules/@nestjs/core/injector/injector.js:351:19)
     at callback (/home/site/wwwroot/node_modules/@nestjs/core/injector/injector.js:56:45)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async Injector.resolveConstructorParams (/home/site/wwwroot/node_modules/@nestjs/core/injector/injector.js:136:24)
     at async Injector.loadInstance (/home/site/wwwroot/node_modules/@nestjs/core/injector/injector.js:61:13)
     at async Injector.loadProvider (/home/site/wwwroot/node_modules/@nestjs/core/injector/injector.js:88:9)
     at async /home/site/wwwroot/node_modules/@nestjs/core/injector/instance-loader.js:49:13
     at async Promise.all (index 3)
```

We have a `prebuild` npm script that runs `prisma generate` and completes successfully. All of `node_modules` (confirmed this includes `node_modules/{.prisma,prisma,@prisma}/*` files) is then zipped with our app and deployed to our Azure App Service app.

### How to reproduce

I am unable to reproduce the issue outside of Azure App Service. The app runs fine locally.

### Expected behavior

The app starts as usual.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["multiSchema"]
}

generator dbml {
  provider = "prisma-dbml-generator"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  schemas  = ["app", "catalog", "public"]
}

// 650 lines of models are redacted
```

The boilerplate for integrating prisma into our NestJS app--
```ts
import { INestApplication, Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  async onModuleInit() {
    await this.$connect();
  }

  enableShutdownHooks(app: INestApplication) {
    this.$on('beforeExit', async () => {
      await app.close();
    });
  }
}
```

### Environment & setup

In Azure App Service

- OS: Debian (dockerized)
- Database: PostgreSQL
- Node.js version: v18.12.1

### Prisma Version

I unfortunately cannot run this on the server.  This is the output when running locally--

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
Preview Features        : multiSchema
```

**Comment by chriskuech** [comment]
Looks like removing this (and the packages it pulls in) resolved our issue. Not sure if that means this issue should move to another repo or not

```
generator dbml {
  provider = "prisma-dbml-generator"
}
```

**Comment by GugaAraujo** [comment]
I wasted a lot of time trying to solve this situation and I didn't find a good explanation for it, but installing the prism with the YARN manager solved my problem.

@chriskuech, did you manage to solve? Did you find another solution?

**Comment by chriskuech** [comment]
@GugaAraujo my only solution was to comment [this](https://github.com/prisma/prisma/issues/18170#issuecomment-1452324943) out

**Comment by Weakky** [comment]
Hey @chriskuech, moving this issue over to prisma-dbml-generator is likely a good idea as it looks like the bug is not on our side. We're closing now, thanks for reporting anyway 🙏

**Comment by chriskuech** [comment]
@Weakky Given you are a member of the prisma org in GitHub, can you transfer the ticket there? You should be able to see this button (I can only see the button on Issues in my org). 

<img width="405" alt="image" src="https://github.com/user-attachments/assets/528829d9-a2b7-4d10-84d2-596bb3dee146">
