### ISSUE TITLE
Invalid `prisma.***.upsert()` invocation in ...

### ISSUE THREAD

**Issue by chientrm** [prisma/prisma#18183]
### Bug description

Keep getting invalid invocation when using `upsert`

### Prisma information

```prisma
model Settings {
  sub      String  @id
  darkMode Boolean
}
```

```ts
const { sub } = res.locals.user as User,
  [settings] = await prisma.$transaction([
    prisma.settings.upsert({
      where: { sub },
      update: {},
      create: { sub, darkMode: false },
    }),
  ]);
```

### Environment & setup

- OS: Ubuntu 20.04 LTS
- Database: MySQL
- Node.js version: v16.18.0

### Prisma Version

```
4.10.1
```

**Comment by janpio** [comment]
Can you please share the full error message?

**Comment by chientrm** [comment]
> Can you please share the full error message?

This is all the logs that `sentry` recorded.

![Screenshot_20230303-071345.png](https://user-images.githubusercontent.com/70304839/222597980-3e68de48-e149-46ab-80e6-f14986f2667a.png)

![Screenshot_20230303-071434.png](https://user-images.githubusercontent.com/70304839/222597996-e10a0cf1-7275-4269-ac8c-454632f9a235.png)

![Screenshot_20230303-071518.png](https://user-images.githubusercontent.com/70304839/222598011-c82e0cfd-354a-4eb9-9e65-e97f9910d9b8.png)

**Comment by chientrm** [comment]
Here's my workaround till this bug get fixed:

```ts
const { sub } = res.locals.user as User;
await prisma.$queryRawUnsafe(
  `INSERT INTO Settings(sub, darkMode) 
  SELECT * FROM (SELECT '${sub}', false) AS tmp 
  WHERE NOT EXISTS (
    SELECT sub, darkMode FROM Settings WHERE sub = '${sub}'
  ) LIMIT 1`
);
const settings = await prisma.settings.findFirstOrThrow({ where: { sub } });
res.send({ settings });
```

Explain: `Create record if not exists via raw sql`.

**Comment by chientrm** [comment]
Nvm I still get the error, I figured it out that my client app sent 2 concurrent requests at the same time to that route (the same user `sub`) so that I just set the `connection_limit=5`.

**Comment by Weakky** [comment]
Hey @chientrm, we're now closing this issue since you figured it out. Thanks
