### ISSUE TITLE
`deleteMany` does not actually delete data for specific schemas

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#18185]
### Bug description

With this model:
```
model with_compound_unique {
  id   Int
  name String

  WART_id                 Int?                     @unique
  with_all_relation_types with_all_relation_types? @relation("WART_WCU", fields: [WART_id], references: [id])

  @@unique([id, name])
}
```

running `prismawith_compound_unique.deleteMany()` does not actually delete the data in the table.

### How to reproduce

https://github.com/janpio/prisma-broken-deleteMany

### Expected behavior

Table should be empty.

### Prisma information

see above

### Environment & setup

- OS: GitPod
- Database: PostgreSQL
- Node.js version: v16.19.0

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by technotip** [comment]
I think it is due to the relationship the collection has **@relation("WART_WCU")**;
You've to first delete the entry from **with_all_relation_types** and then run **prisma.with_compound_unique.deleteMany()** and it must probably just work.

**Comment by jkomyno** [comment]
This is no longer reproducible, I've tested it with Prisma 5.17.0.
