### ISSUE TITLE
4.11.0: `Unique constraint failed on the fields` on query that worked in 4.10.1

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#18186]
Reproduction repository: https://github.com/janpio/prisma-4.11-pdp-regression

**Comment by janpio** [comment]
Workaround: The problem is caused by the unique field `WART_id` in the example. When it is created not with `null` but a unique value (e.g. `i` form the loop) the code runs successfully.

**Comment by janpio** [comment]
My reproduction is unfortunately still failing with the latest `prisma@dev` and `@prisma/client@dev` which is currently `4.12.0-dev.13`. Did this maybe not get integrated and release into the CLI and Client yet?

**Comment by miguelff** [comment]
> Did this maybe not get integrated and release into the CLI and Client yet?

Exactly, the revision of prisma engines used in this version does not include https://github.com/prisma/prisma-engines/commit/2f443b14ed9aa025d84bac879ebc2fbe9979b7e1

From [npm](https://www.npmjs.com/package/prisma/v/4.12.0-dev.13?activeTab=versions) → Code → [Prisma commit 7893f1af](https://github.com/prisma/prisma/blob/7893f1af0ac6126570f70f596e3c404718adf85f/packages/fetch-engine/package.json#LL18C8-L18C8) → [prisma-engines @ 3b9f029a](https://github.com/prisma/prisma-engines/commits/3b9f029aeb9a91829e6648c61146b02f3646d1e7) (earlier than https://github.com/prisma/prisma-engines/commit/2f443b14ed9aa025d84bac879ebc2fbe9979b7e1)

**Comment by janpio** [comment]
I can now confirm that this is fixed in `4.12.0-dev.30` 🥳
