### ISSUE TITLE
DMMF : Include indicator of ObjectId when String. 

### ISSUE THREAD

**Issue by maxime4000** [prisma/prisma#18181]
## Problem
I'm working on a generator for factories, I'm using a MongoDB database and I have some composite type field including ObjectId value, until Composite Type relation work, I want to store some ObjectId with no relation. This error happen and there is no way to actually know the field is an ID, but if I try to insert data that isn't an ObjectId, I receive this error : 

```
Inconsistent column data: Malformed ObjectID: provided hex string representation must be exactly 12 bytes, instead got: "Customer Communications Liaison", length 31 for the field 'editBy'.
```
I'm using faker to generate this string, If I could know that this string is an ObjectId, I could generate an ObjectId instead of a string, but there is no way to know that in the DMMF.Field...

Let's said I have 2 field in my Composite Type : 
```prisma
type EditBy {
  userId String? @db.ObjectId
  appId String?
}
```
There is no way to know what is what! This is what the DMMF output : 
```json
{
  "name": "userId",
  "kind": "scalar",
  "isList": false,
  "isRequired": false,
  "isUnique": false,
  "isId": false,
  "isReadOnly": false,
  "hasDefaultValue": false,
  "type": "String"
},
{
  "name": "appId",
  "kind": "scalar",
  "isList": false,
  "isRequired": false,
  "isUnique": false,
  "isId": false,
  "isReadOnly": false,
  "hasDefaultValue": false,
  "type": "String"
}
```

I would like to know the field is a ID/ObjectId. There is no way to differentiate an Id from a String. 

## Suggested solution

I would like to have the property `"isObjectId": true,`in the field so I could detect this. 
```json
{
  "name": "userId",
  "kind": "scalar",
  "isList": false,
  "isRequired": false,
  "isUnique": false,
  "isId": false,
  "isReadOnly": false,
  "hasDefaultValue": false,
  "type": "String",
  "isObjectId": true,
},
{
  "name": "appId",
  "kind": "scalar",
  "isList": false,
  "isRequired": false,
  "isUnique": false,
  "isId": false,
  "isReadOnly": false,
  "hasDefaultValue": false,
  "type": "String",
  "isObjectId": false,
}
```

### Similar Issue : #3998

**Comment by janpio** [comment]
I think your request is actually a duplicate of https://github.com/prisma/prisma/issues/10252. `ObjectId` is a native type in our context that further refines the type. Do you agree? If so, please close this and post your use case in the other issue. Thanks.

**Comment by maxime4000** [comment]
It's a duplicate of 10252 and this PR would solve the issue here : https://github.com/prisma/prisma-engines/pull/2660
