### ISSUE TITLE
migration engine exited error on db push command in prisma

### ISSUE THREAD

**Issue by Jatin-D-Kumar** [prisma/prisma#18211]
Hi Prisma Team! The following command just crashed.

## Command

`npx prisma db push`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.17.0           | 
| Prisma CLI  | 4.11.0             | 
| Engine      | 8fde8fef4033376662cad983758335009d522acb| 

## Error
```
Error:  Migration engine exited. Error: Command failed with exit code 3221225781
Reason: 

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by janpio** [comment]
Solution to your problem: https://github.com/prisma/prisma/issues/9975#issuecomment-952944479

**Comment by Jatin-D-Kumar** [comment]
> Solution to your problem: [#9975 (comment)](https://github.com/prisma/prisma/issues/9975#issuecomment-952944479)

thanks its working now
