### ISSUE TITLE
Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1822]
This is a collection issue for all panics with this error message. As they may have different underlying problems, individual problem will be split off into their own issue (see link below).

Most likely coming from here: https://github.com/prisma/prisma-engines/blob/master/query-engine/core/src/response_ir/mod.rs#L281

---

Internal notes: 

Test utils database(s) affected: 

With individual issue:
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_allsquare_stderr.log => https://github.com/prisma/prisma2/issues/1772
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_drupal_stderr.log => https://github.com/prisma/prisma2/issues/1823
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_smf_stderr.log => https://github.com/prisma/prisma2/issues/1826

Without issues for now:
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_elgg_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_filerun_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_ghost_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_joomla_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_kanboard_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_limesurvey_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_mantis_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_mediawiki_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_opencart_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_oscommerce_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_phpbb_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_phpmyfaq_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_wikimedia_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_wordpress_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_xoops_stderr.log
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_yourls_stderr.log

**Comment by janpio** [comment]
Next step: Update with next test-utils run, and then use better links and also not version used to test.

**Comment by pantharshit00** [comment]
@divyenduz Is this still actionable?

**Comment by divyenduz** [comment]
This is still relevant, the issue was observed a lot in the last test-utils analysis. In essence, this is the issue https://github.com/prisma/prisma/issues/2687

It can happen when a type is stripped (string length), converted to another value (unsigned ints), padded with values (native binary type to fulfill the size requirement) and similar cases.

**Comment by pantharshit00** [comment]
Alright, I have candidated the other issue.
