### ISSUE TITLE
incorrect regex in function `parseLibSSLVersion` in file `prisma/packages/get-platform/src/getPlatform.ts` /libssl\.so\.(\d)(\.\d)?/

### ISSUE THREAD

**Issue by wvhulle** [prisma/prisma#18229]
### Bug description

Prisma identifies platform incorrectly if there are multiple versions of openssl installed. It just takes the first match to some regex, but it should take the one that is symlinked to.

https://github.com/prisma/prisma/blob/9e2a274dbeecba22496026ebcdd1b9071e4c735c/packages/get-platform/src/getPlatform.ts#L255
```
export function parseLibSSLVersion(input: string): GetOsResultLinux['libssl'] {
  const match = /libssl\.so\.(\d)(\.\d)?/.exec(input)
  if (match) {
    const partialVersion = `${match[1]}${match[2] ?? '.0'}.x`
    return sanitiseSSLVersion(partialVersion)
  }

  return undefined
}
```

Give input to parseLibSSLVersion:
```
libssl.so (symlinked to libssl.so.3)
libssl.so.1.1
libssl.so.3
```
Expected output
```
libssl.so.3
```
Real output
```
libssl.so.1.1
```
This code is incorrect. The output should be libssl.so.3. Just taking the first match is not deterministic. It may make Prisma break on upgrades unexpectedly. On my system for example openssl -v returns 3.0.8 and libssl.so is properly symlinked to libssl.so.3, but the regex currently in Prisma does not follow the symlink and eagerly takes the first match. Please resolve the symlink first if it exists or use another way than the filename that is more reproducible.

By the way, would it be possible to ship the unminified code? It would be more pleasant for the eye to debug and probably only have a minimal effect on performance.

### How to reproduce

- Install debian 11 openssl 1.1, 
- upgrade to debian unstable with openssl 3.0, 
- reboot, 
- prisma.$connect() or prisma._engine.start()

### Expected behavior

Correct openssl version if multiple versions are installed by following the symlink

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
binaryTargets = ["debian-openssl-3.0.x"]
}

datasource db {
  provider = "postgres"
  url      = "postgresql://inbiose:ealZptu93lJGj@localhost/dsp?schema=prisma"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int      @id @default(autoincrement())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}

```

```ts
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()





// A `main` function so that we can use async/await
async function main() {
  // Seed the database with users and posts
  const user1 = await prisma.user.create({
    data: {
      email: 'alice@prisma.io',
      name: 'Alice',
      posts: {
        create: {
          title: 'Watch the talks from Prisma Day 2019',
          content: 'https://www.prisma.io/blog/z11sg6ipb3i1/',
          published: true,
        },
      },
    },
    include: {
      posts: true,
    },
  })
  const user2 = await prisma.user.create({
    data: {
      email: 'bob@prisma.io',
      name: 'Bob',
      posts: {
        create: [
          {
            title: 'Subscribe to GraphQL Weekly for community news',
            content: 'https://graphqlweekly.com/',
            published: true,
          },
          {
            title: 'Follow Prisma on Twitter',
            content: 'https://twitter.com/prisma/',
            published: false,
          },
        ],
      },
    },
    include: {
      posts: true,
    },
  })
  console.log(
    `Created users: ${user1.name} (${user1.posts.length} posts) and ${user2.name} (${user2.posts.length} posts) `,
  )
  // Retrieve all published posts
  const allPosts = await prisma.post.findMany({
    where: { published: true },
  })
  console.log(`Retrieved all published posts: `, allPosts)

  // Create a new post (written by an already existing user with email alice@prisma.io)
  const newPost = await prisma.post.create({
    data: {
      title: 'Join the Prisma Slack community',
      content: 'http://slack.prisma.io',
      published: false,
      author: {
        connect: {
          email: 'alice@prisma.io', // Should have been created during initial seeding
        },
      },
    },
  })
  console.log(`Created a new post: `, newPost)

  // Publish the new post
  const updatedPost = await prisma.post.update({
    where: {
      id: newPost.id,
    },
    data: {
      published: true,
    },
  })
  console.log(`Published the newly created post: `, updatedPost)

  // Retrieve all posts by user with email alice@prisma.io
  const postsByUser = await prisma.user
    .findUnique({
      where: {
        email: 'alice@prisma.io',
      },
    })
    .posts()
  console.log(`Retrieved all posts from a specific user: `, postsByUser)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })

```

### Environment & setup

- OS: Debian unstable
- Database: Postgres
- Node.js version: anything between 17 and 19 which ships openssl 3

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/.pnpm/@prisma+engines@4.11.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/.pnpm/@prisma+engines@4.11.0/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by DennisVonDerBey** [comment]
When did this come up? I just now wanted to start our backend and it suddenly complained. For me the `telegram-desktop` package on Manjaro required the `openssl-1.1`. After switching to a binary version and removing the `1.1` package it detected correctly again.

**Comment by wvhulle** [comment]
This became an issue after rebooting because of a power crash. Maybe the 1.1 version was somehow automatically added on reboot even though I had upgraded to 3 before reboot and everything was working fine, but not completely sure. But I still think that regex is not a good idea.

**Comment by aqrln** [comment]
Is there a specific problem you are facing (i.e. something actually breaking because of Prisma using OpenSSL 1.1) or is your concern more of a theoretical one?

We did want to prefer the newest available version of OpenSSL, but had to change that in in https://github.com/prisma/prisma/pull/17241 because some serverless platforms have a range of different OpenSSL versions in their build image but only the oldest one in the runtime image, so the current behaviour is intentional.

We could make those heuristics a bit more complicated and platform-dependent if there's a good reason, but doing that just because using a newer version feels "cleaner" might be adding too much complexity for little gain.

**Comment by aqrln** [comment]
I'll go ahead and close the issue since there was no response and the issue is not actionable without additional details.

From the description it's not clear why should the current behavior be considered a bug. I will also still continue to be the case that Prisma Client might need to be regenerated after system configuration change or upgrade even with the suggested changes.

Please feel free to leave a comment or reopen if you think we misunderstood the issue and there is an actual problem to be fixed. Also please open a feature request if you want to have a way to override the detected platform (e.g. if you want to force Prisma to use one of the installed OpenSSL versions).

**Comment by wvhulle** [comment]
Ok, thanks for the feedback. So Debian 11 is unsupported by Prisma? 

A default install results in segfault because of the openssl problems. Installing a newer openssl still results in segfaults because of this regex. 

A solution is to manually move the openssl that prisma targets with this regex. But that means that the default postgres client stops working because it also needs the openssl version that makes prisma break. So I have to choose. Either prisma segfaults or I cannot do any SQL queries on the server anymore.

And if you didn't spend hours debugging this, then you don't know all of this. Maybe some info in the docs could help? For me switching distributions is not an option since our servers run on Debian. 

Is it difficult to just check on which distribution you are? Isn't every distribution different, so there should be checks for this stuff anyway? I don't think it would just be "cleaner" to add a check, current behaviour is a bug that affects all users of a major Linux distribution.

**Comment by janpio** [comment]
Is there an issue for that segfault you are describing? Can you link to it please?

**Comment by wvhulle** [comment]
Yes this is bug https://github.com/prisma/prisma/issues/16897 reported in december
