### ISSUE TITLE
Way to avoid loading values from `.env` file to Node's `process.env` when importing Prisma Client

### ISSUE THREAD

**Issue by NiciusB** [prisma/prisma#18239]
## Problem

In my nodejs project I use a `.env` file to store secrets, but I don't want to have them available in `process.env`.
Instead, I make them available from an object like so:

```typescript
// env.ts
import { z } from 'zod'
import * as dotenv from 'dotenv'
import fs from 'node:fs'

const env = z
  .object({
    DATABASE_URL: z.string(),
    // etc...
  })
  .parse({
    ...dotenv.parse(fs.readFileSync('.env')),
    ...process.env,
  })

export default env
```

I was puzzled that even when I was not putting the env values into `process.env`, they were being set anyways.

After testing I found that just importing the prisma client will cause that to happen, and it turns out it is a [documented feature](https://www.prisma.io/docs/guides/development-environment/environment-variables#how-does-prisma-use-environment-variables)
```typescript
import '@prisma/client'
console.log(process.env.MY_SECRET_KEY) // I want this to be undefined, but it's the value from .env
```

## Suggested solution

I have a couple of ideas:
- An environment variable that could tell Prisma Client to not load the env vars into `process.env`. For example: `NO_PRISMA_LOAD_ENV=1`
- Only actually loading the env vars when creating an instance of the PrismaClient class, and adding an option to it's constructor to disable the behaviour. This option doesn't seem super neat and would be a breaking change, tho.

## Alternatives

I understand that this is not super important, so if someone really wanted to stop this behaviour they could just create a patch to no-op this line https://github.com/prisma/prisma/blob/e18cb5d076ee4d5f7512681f2a29a55985e1f03f/packages/client/src/runtime/getPrismaClient.ts#L331

## Additional context

- https://www.trendmicro.com/en_us/research/22/h/analyzing-hidden-danger-of-environment-variables-for-keeping-secrets.html
- https://blog.diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/

**Comment by Ciboulette** [comment]
Same for us, I don't want to be rude, but for me it's a scandal that an ORM loads the secrets. In terms of security it feels completely broken. Just do a major update with a breaking change to stop using dotenv, it's not your job!

**Comment by pdeblanc** [comment]
This is a problem for me as well. I have a `.env` file as well as a `.env.test` used for testing.

Although I run my tests with `dotenv -e .env.test -- yarn jest`, the values from both files (`.env` and `.env.test`) are being loaded. Thankfully, the latter seems to have higher priority, but it feels like a dangerous state of affairs to me.

For example, some behaviors in my codebase will occur if a given API key is specified, but are skipped if it is blank. If I add the API key to my `.env` without an explicit override in `.env.test`, then it will be loaded and my tests will hit the paid service. This is how I noticed the issue!

**Comment by Mydayyy** [comment]
Although the above already mentions a related issue, I proceed to comment this here too since its very strongly related:

I created a minimal production repo for this issue as requested in the issue linked above: 
https://github.com/Mydayyy/nestjs-prisma-bug-repro

**Comment by NiciusB** [comment]
That looks like a duplicate issue, closing this one in favor of that one
