### ISSUE TITLE
DEBUG=* could also log the Client and Engine version by default

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1825]
When debugging stuff, I often use `DEBUG=*` to get a lot of output. It could be nice to have the available versions in that output by default, so you do not have to output stuff additionally.

**Comment by Jolg42** [comment]
Example output with latest alpha 
```
  prisma-client Client Version d7866d1a109b061d955254b078e58be2615d4e31 +0ms
  prisma-client Engine Version d7866d1a109b061d955254b078e58be2615d4e31 +1ms
  prisma-client {
  prisma-client   engineConfig: {
.....
```
