### ISSUE TITLE
Checksum the Engine binaries archive (download verification and mirrors)

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#1828]
When the CI stores binaries to the download storage, we should calculate SHA-256 sums for them. When the client downloads the binaries, it should download the SHA-256 sum and calculate again a sum for the binaries, comparing them to the stored sums.

If the sums differ, the client should either error out or try to re-download the binaries.

**Comment by janpio** [comment]
Possible complication here: We download a `.gz` of the engines, then unpack that locally. We might want to have checksums for both the archive (to check downloading) and the binary (to check unpacking). (The binary checksum could be part of the archive as well.)

**Comment by pimeys** [comment]
Now we need to compare the risk factors. The chance of Gzip corrupting the file is about once per 1 000 000 years, meaning you get solar wind just in the right moment when unzipping to flip a bit from the extracted binary. Gzip is also [calculating checksum](https://en.wikipedia.org/wiki/Gzip) for the files inside, so I wouldn't expect the output be corrupted. And Gzip has been in use almost everywhere since 1992, so I really wouldn't expect any bugs from the compressor.

And then we have the Internet, that can be anything from 10 Gbps fiber to a Deutsche Telekom DSL, and it is not that rare to get a corrupted file. How everybody else is doing this is they calculate a checksum for the ISO image or .gz archive, and if using an installation tool, it can automatically check the sum and the correctness of the archive.

Calculating the checksum is quite easy in the CI. Let's say we have a binary `query-engine-linux` we pack to `query-engine-linux.gz`. We call `sha256sum query-engine-linux.gz > query-engine-linux.gz.sha256` and upload both files to the S3 bucket. The downloader then downloads both files, calls `sha256sum query-engine-linux.gz` and compares the string to the string found in the `sha256` file.

**Comment by pimeys** [comment]
Then again... The binary corruption problem has only happened in macOs, so I wouldn't be surprised if some system service is doing things we don't know about. Maybe we should checksum the binary too... Although nobody else seems to do that.

**Comment by janpio** [comment]
Useful here: https://mxlinux.org/wiki/system/iso-download-mirrors/

**Comment by janpio** [comment]
![image](https://user-images.githubusercontent.com/183673/77446921-55a96e80-6def-11ea-8932-9df3e1c46967.png)

**Comment by timsuchanek** [comment]
Done in the latest version!
