### ISSUE TITLE
For self relation it is causing error

### ISSUE THREAD

**Issue by iamdeepta** [prisma/prisma#18291]
Hi Prisma Team! The following command just crashed.

## Command

`generate`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.21.2           | 
| Prisma CLI  | 4.10.1             | 
| Engine      | aead147aa326ccb985dcfed5b065b4fdabd44b19| 

## Error
```
Error: unreachable
```

**Comment by janpio** [comment]
Can you share the schema snippet with the self relation that is causing this? Then we might be able to reproduce and fix. Thanks.

**Comment by Weakky** [comment]
Hey @iamdeepta, with the lack of information, we're now closing your issue. Thanks
