### ISSUE TITLE
Wrong version resolution by npm/yarn on some occasions

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#1829]
This is due to the fact that according to semver, our `alpha` versions are *always* considered older than our `preview` versions.

Here's how a normal user would run into this:
1. They run `npm install @prisma/client@alpha prisma2@alpha` at some point
2. They find a bug, we fix it and ask them to update to alpha.XYZ
3. They manually update their `package.json`'s prisma2 version to 2.0.0-alpha.XYZ and run `npm i`
4. They actually get the *preview* version installed in their `node_modules`

Here's a way to simulate this:
1. Create a new npm repository: `mkdir abcd && cd abcd && npm init -y`
2. Run `npm i @prisma/client@alpha prisma2@alpha`
3. Check actual version of `prisma2` installed in your `node_modules` (Should be latest alpha)
4. Delete `node_modules` and `package-lock.json`
5. Run `npm i`
6. Check version of `prisma2` in `node_modules` again. It'll be the latest preview.
7. This is bad, because your `package.json` still says `"prisma2": "^2.0.0-alpha.XYZ"`.

This stems from the fact that our alphas and previews don't behave like we expect because of semver. If you head over to https://semver.npmjs.com, you'll be able to verify this.
<img width="1660" alt="Screenshot 2020-03-12 at 14 29 25" src="https://user-images.githubusercontent.com/7689783/76526495-e4bc9b00-646d-11ea-9ee9-51bf5124ab58.png">

I'm not sure what the solution to this problem would look like.

**Comment by madebysid** [comment]
Here's another (more accurate) simulation:

1. Create a new npm repository: `mkdir abcd && cd abcd && npm init -y`
2. Now I want you to install the alpha versions of `@prisma/client` & `prisma2` that are *just* shy of the latest version. As of this writing, latest alpha is 2.0.0-alpha.904, so I want to install 2.0.0-alpha.903. You can do this by EXPLICITLY defining versions in your package.json:
```
  "dependencies": {
    "@prisma/client": "2.0.0-alpha.903",
    "prisma2": "2.0.0-alpha.903"
  }
```
Notice there aren't any semver symbols (like `^`, or `~` here). Then run `npm i`
3. Verify that the versions of `@prisma/client` and `prisma2` inside your `node_modules` is alpha.903. This is important.
4. Now change your package.json's `dependencies` to:
```
  "dependencies": {
    "@prisma/client": "^2.0.0-alpha.903",
    "prisma2": "^2.0.0-alpha.903"
  }
```
And `npm i`
5. You're now in the same state as the user was when we ask them to update to the latest alpha.XYZ
6. So do that, update your dependency to alpha.904 and run `npm i`
7. Check your `node_modules` and you'll have the preview in there

**Comment by janpio** [comment]
What is actionable here?

**Comment by janpio** [comment]
This should only be a problem for the remaining time in that we use `2.0.0` as the base version.

https://docs.npmjs.com/misc/semver#prerelease-tags

> If a version has a prerelease tag (for example, 1.2.3-alpha.3) then it will only be allowed to satisfy comparator sets if at least one comparator with the same [major, minor, patch] tuple also has a prerelease tag.

This means, that as soon as we use 2.0.0, 2.0.1, 2.1.0 etc the prerelease versions will only possibly be upgraded to that version if available - and that should be expected behavior.

**Comment by pantharshit00** [comment]
I am going to close this now as `2.0.0` has been released.
