### ISSUE TITLE
Node hangs when `console.log(new PrismaClient())`

### ISSUE THREAD

**Issue by sc0ch** [prisma/prisma#18292]
### Bug description

Linux - node process hangs (stuck on prisma:client:libraryEngine  internalSetup +0ms)
Windows - javascript out of memory error.
Any schema. 
Affected versions of @prisma/client > 4.7.0

### How to reproduce

1. npx prisma init
2. npx prisma generate (npx prisma db push)
3. Create index.mjs with:
	```
	import { PrismaClient } from '@prisma/client'
	console.log(new PrismaClient())
	```
4. `export DEBUG="*" && node index.mjs` -> See error

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Session {
  id    Int    @id @default(autoincrement())
  key   String @unique
  value String

  @@map("sessions")
}
```

### Environment & setup

- OS: Windows 11, Ubuntu 22.04.2
- Database: MySQL
- Node.js version: 18.5.0, 19.7.0

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by janpio** [comment]
Why do you want to `console.log(new PrismaClient())`?

**Comment by AvIsBeastMC** [comment]
> Why do you want to `console.log(new PrismaClient())`?
fr

**Comment by entrptaher** [comment]
I did this and then whenever I wanted to console.log(prisma) anywhere for any reason, it hung the whole process.

```
import { PrismaClient } from "@prisma/client";
let prisma = new PrismaClient();
console.log(prisma)
```

**Comment by professor-l** [comment]
I've encountered this as well. I use a development repl in one of my projects, and though I can `const p = new PrismaClient()`, a subsequent `p` to check whether it's defined hangs the process.

**Comment by janpio** [comment]
I can actually log `new PrismaClient()` fine:
```
const { PrismaClient } = require('@prisma/client')

async function main() {
    console.log(new PrismaClient())
}

main()
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```
When I put the output of this into a file, it is 525 MB (551.039.534 bytes) big though - so I would not be surprised if that would crash in some environments.

The output looks recursive to me in 2 places:
```
{
  _middlewares: MiddlewareHandler { _middlewares: [] },
  _getDmmf: [Function (anonymous)],
  _getProtocolEncoder: [Function (anonymous)],
  '$extends': [Function: $extends],
  _extensions: MergedExtensionsList { head: undefined },
  _previewFeatures: [],
  _rejectOnNotFound: undefined,
  _clientVersion: '4.13.0',
  _activeProvider: 'postgresql',
  _dataProxy: false,
  _tracingConfig: { enabled: [Getter], middleware: [Getter] },
  _clientEngineType: 'library',
  _errorFormat: 'colorless',
  _baseDmmf: {
    datamodel: { enums: [], models: [Array], types: [] },
    datamodelEnumMap: {},
    modelMap: { User: [Object] },
    typeMap: {},
    typeAndModelMap: { User: [Object] },
    mappings: { modelOperations: [Array], otherOperations: [Object] },
    mappingsMap: { User: [Object] }
  },
  _engineConfig: {
    cwd: 'C:\\Users\\Jan\\Documents\\throwaway\\18292\\prisma',
    dirname: 'C:\\Users\\Jan\\Documents\\throwaway\\18292\\node_modules\\.prisma\\client',
    enableDebugLogs: false,
    allowTriggerPanic: undefined,
    datamodelPath: 'C:\\Users\\Jan\\Documents\\throwaway\\18292\\node_modules\\.prisma\\client\\schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    datasources: [],
    generator: {
      name: 'client',
      provider: [Object],
      output: [Object],
      config: [Object],
      binaryTargets: [],
      previewFeatures: []
    },
    showColors: false,
    logLevel: undefined,
    logQueries: undefined,
    env: {
      DATABASE_URL: 'postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public'
    },
    flags: [],
    clientVersion: '4.13.0',
    previewFeatures: [],
    activeProvider: 'postgresql',
    inlineSchema: undefined,
    inlineDatasources: undefined,
    inlineSchemaHash: undefined,
    tracingConfig: { enabled: [Getter], middleware: [Getter] },
    logEmitter: EventEmitter {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      [Symbol(kCapture)]: false
    },
    engineProtocol: 'graphql'
  },
  _engine: LibraryEngine {
    datamodel: '// This is your Prisma schema file,\n' +
      '// learn more about it in the docs: https://pris.ly/d/prisma-schema\n' +
      '\n' +
      'generator client {\n' +
      '  provider = "prisma-client-js"\n' +
      '}\n' +
      '\n' +
      'datasource db {\n' +
      '  provider = "postgresql"\n' +
      '  url      = env("DATABASE_URL")\n' +
      '}\n' +
      '\n' +
      'model User {\n' +
      '  id    Int     @id @default(autoincrement())\n' +
      '  email String  @unique\n' +
      '  name  String?\n' +
      '}\n',
    config: {
      cwd: 'C:\\Users\\Jan\\Documents\\throwaway\\18292\\prisma',
      dirname: 'C:\\Users\\Jan\\Documents\\throwaway\\18292\\node_modules\\.prisma\\client',
      enableDebugLogs: false,
      allowTriggerPanic: undefined,
      datamodelPath: 'C:\\Users\\Jan\\Documents\\throwaway\\18292\\node_modules\\.prisma\\client\\schema.prisma',
      prismaPath: undefined,
      engineEndpoint: undefined,
      datasources: [],
      generator: [Object],
      showColors: false,
      logLevel: undefined,
      logQueries: undefined,
      env: [Object],
      flags: [],
      clientVersion: '4.13.0',
      previewFeatures: [],
      activeProvider: 'postgresql',
      inlineSchema: undefined,
      inlineDatasources: undefined,
      inlineSchemaHash: undefined,
      tracingConfig: [Object],
      logEmitter: [EventEmitter],
      engineProtocol: 'graphql'
    },
    libraryStarted: false,
    logQueries: false,
    logLevel: 'error',
    libraryLoader: DefaultLibraryLoader {
      libQueryEnginePath: null,
      platform: null,
      config: [Object]
    },
    logEmitter: EventEmitter {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      [Symbol(kCapture)]: false
    },
    engineProtocol: 'graphql',
    datasourceOverrides: [Object: null prototype] {},
    libraryInstantiationPromise: Promise { <pending> }
  },
  _fetcher: RequestHandler {
    logEmitter: EventEmitter {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      [Symbol(kCapture)]: false
    },
    client: {
    ... RECURSION 1 HERE ...
        },
    dataloader: DataLoader { options: [Object], tickActive: false, batches: {} }
  },
  _metrics: MetricsClient {
    _engine: LibraryEngine {
      datamodel: '// This is your Prisma schema file,\n' +
        '// learn more about it in the docs: https://pris.ly/d/prisma-schema\n' +
        '\n' +
        'generator client {\n' +
        '  provider = "prisma-client-js"\n' +
        '}\n' +
        '\n' +
        'datasource db {\n' +
        '  provider = "postgresql"\n' +
        '  url      = env("DATABASE_URL")\n' +
        '}\n' +
        '\n' +
        'model User {\n' +
        '  id    Int     @id @default(autoincrement())\n' +
        '  email String  @unique\n' +
        '  name  String?\n' +
        '}\n',
      config: [Object],
      libraryStarted: false,
      logQueries: false,
      logLevel: 'error',
      libraryLoader: [DefaultLibraryLoader],
      logEmitter: [EventEmitter],
      engineProtocol: 'graphql',
      datasourceOverrides: [Object: null prototype] {},
      libraryInstantiationPromise: [Promise]
    }
  },
  user: {
    findUnique: [Function (anonymous)],
    findUniqueOrThrow: [Function (anonymous)],
    findFirst: [Function (anonymous)],
    findFirstOrThrow: [Function (anonymous)],
    findMany: [Function (anonymous)],
    create: [Function (anonymous)],
    createMany: [Function (anonymous)],
    delete: [Function (anonymous)],
    update: [Function (anonymous)],
    deleteMany: [Function (anonymous)],
    updateMany: [Function (anonymous)],
    upsert: [Function (anonymous)],
    aggregate: [Function (anonymous)],
    groupBy: [Function (anonymous)],
    count: [Function (anonymous)],
    name: 'User'
  },
  [Symbol()]: {
   ... RECURSION 2 HERE ...
   }
}
```

Both cases are roughly 100.000 lines long in my file.

Not optimal.

**Comment by jonschlinkert** [comment]
I experience this too. I've had to create work arounds everywhere in our application that might have `client` (an instance of prisma) on a class instance. Otherwise the server freezes anytime something logs out. 

To fix this, anywhere recursive information is added to the object I recommend using `Reflect.defineProperty` so that it can be made non-enumerable, instead of simple accessor assignment. 

Example:

```js
Reflect.defineProperty(prisma, Symbol(), {
  value: {...},
  enumerable: false
});
```

**Comment by janpio** [comment]
This seems to also happen when logging the `tx` inside an interactive `$transaction` - which makes sense as that is just another Client instance: https://github.com/prisma/prisma/issues/19137

**Comment by SD-Gaming** [comment]
I have met this issue too,

```
OS:  win10 x64

node: 18.15.4 x64

prisma: 4.16.1 client 4.16.1
```

**Comment by Xaliks** [comment]
+1

node 20.5.1
prisma 5.1.1

```javacript
const { PrismaClient } = require("@prisma/client");
const client = new PrismaClient();

console.log(client);
```

**Comment by janpio** [comment]
Duplicate: https://github.com/prisma/prisma/issues/19648

**Comment by Xaliks** [comment]
I also can't inspect client
![screenshot](https://i.xaliks.dev/S3h1M606.png)

**Comment by aqrln** [comment]
Also reproduced in https://github.com/prisma/prisma/issues/19648#issuecomment-1680908441, for me it was 152 MiB of output on Prisma 4.15.0 and the process hanging indefinitely on Prisma 5.2.0-dev.

**Comment by janpio** [comment]
Can you also confirm that it used to work fine in Prisma 4.7.0 and older @Druue? Then we have something to start looking into what changed.

**Comment by janpio** [comment]
It's art 🤣

**Comment by at-vpd** [comment]
this stumped me for 2 days - why does it happen?

**Comment by llimllib** [comment]
This issue prevents me from using prisma in the node REPL; I don't literally want to log the output of the client, but I do want to use it in a repl.

Here's a node REPL script that reproduces the issue:

```
const repl = require("node:repl");

const r = repl.start("> ");
r.context.prisma = new (require("@prisma/client").PrismaClient)();
```

run that script, type `pri`, node tries to autocomplete prisma and the process immediately hangs; it's not even responsive to ctrl+c interrupt at that point.

**Comment by wodCZ** [comment]
@llimllib you can work around the issue with this:

```ts
const repl = require("node:repl");

const r = repl.start("> ");
r.context.prisma = new (require("@prisma/client").PrismaClient)();
r.context.prisma[Symbol.for('nodejs.util.inspect.custom')] = 'PrismaClient';
```

as suggested here: https://github.com/prisma/prisma/issues/19648#issuecomment-1680911900

**Comment by newsaeta** [comment]
Hello, unfortunately I have the same problem. When instantiating prisma/client the execution stops.
console.log("before prisma");
const prisma = new PrismaClient();
console.log("after prisma")   // It never executes.


Environment variables loaded from .env
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0

**Comment by janpio** [comment]
Do you also do `console.log(new PrismaClient())` @newsaeta? If not, you don't have the same problem and should open a new issue.

**Comment by newsaeta** [comment]
I understand that the problem is the same. 
When PrismaClient() is instantiated and the value is sent to a variable or a console log, the execution stops. But if you think I should open another thread, I do.

Thanks

**Comment by janpio** [comment]
> the value is sent to a variable or a console log, the execution stops.

This issue here is _only_ about it being logged via `console.log`. The code you posted does not do that, so can not be the same problem. If it just stops when you do `new PrismaClient()` you have a new problem and should open a new issue. (Spoiler: We'll ask for a reproduction there)

**Comment by newsaeta** [comment]
ok, I will do it. Thanks

**Comment by newsaeta** [comment]
Hello,
there is an expression in Spanish that says:
"Donde dije digo digo y donde digo Diego", basically a way of saying that I was wrong.
Yesterday after some more time testing I discovered that the problem only occurs when creating a console.log("prismaclient instance"). So my apologies, and I encourage you to keep working as you have been doing with this great tool.
Regards

**Comment by entrata-brianpye** [comment]
I'm running into an issue that may be a different manifestation of this same issue. In Visual Studio Code, whenever I attempt to debug into a class that extends PrismaClient, the node process hangs. Also if I attempt to inspect the instance of this class before stepping into it, the node process hangs. I'm not able to debug any of my classes that extend PrismaClient because of this. I wonder if the debugging issue has something to do with the debugger inspecting the PrismaClient instance for a watch locals or something and this inspecting leads to the same error as logging the PrismaClient instance.

**Comment by MH15** [comment]
This is absurd I love this. I can confirm this doesn't actually stop stuff like `prisma.user.findMany` from working but `console.log(prisma)` hangs with no error. There's got to be a way around this.

**Comment by wodCZ** [comment]
> There's got to be a way around this.

There is, see https://github.com/prisma/prisma/issues/18292#issuecomment-1749123704.

**Comment by codeinearts** [comment]
> I'm running into an issue that may be a different manifestation of this same issue. In Visual Studio Code, whenever I attempt to debug into a class that extends PrismaClient, the node process hangs. Also if I attempt to inspect the instance of this class before stepping into it, the node process hangs. I'm not able to debug any of my classes that extend PrismaClient because of this. I wonder if the debugging issue has something to do with the debugger inspecting the PrismaClient instance for a watch locals or something and this inspecting leads to the same error as logging the PrismaClient instance.

I'm also experiencing this issue after upgrading form 4.11.0 to latest 5.9.1.

When attaching the debugger to some breakpoints while working on some [client extensions](https://www.prisma.io/docs/orm/prisma-client/client-extensions), it hangs the whole application (drove me crazy today, just in the middle of a deadline 🫠)

**Comment by codeinearts** [comment]
> @llimllib you can work around the issue with this:
> 
> ```ts
> const repl = require("node:repl");
> 
> const r = repl.start("> ");
> r.context.prisma = new (require("@prisma/client").PrismaClient)();
> r.context.prisma[Symbol.for('nodejs.util.inspect.custom')] = 'PrismaClient';
> ```
> 
> as suggested here: [#19648 (comment)](https://github.com/prisma/prisma/issues/19648#issuecomment-1680911900)

I can confirm this workaround also fixes my issue using the debugger when extending PrismaClient as a class in the context of a NestJS application 

```typescript
@Injectable()
export class PrismaService
  extends PrismaClient<PrismaClientOptions, "query" | "error">
  implements OnModuleInit, OnModuleDestroy
{
  private readonly logger = new Logger(PrismaService.name);

  constructor(private readonly configService: ApiConfigService) {
    super({
      log: [
        {
          emit: "event",
          level: "query",
        },
        {
          emit: "event",
          level: "error",
        },
        {
          emit: "stdout",
          level: "info",
        },
        {
          emit: "stdout",
          level: "warn",
        },
      ],
    });

    /**
     * new PrismaClient versions hangs debugger
     * https://github.com/prisma/prisma/issues/18292#issuecomment-1749123704
     */
    Object.assign(this, {
      [Symbol.for("nodejs.util.inspect.custom")]: "PrismaCLient",
    });

    this.$on("error", (event) => {
      this.logger.log(event.target);
    });

    this.$on<any>("query", (event: Prisma.QueryEvent) => {
      const { query, timestamp, duration } = event;
      const collection = query.split("(")[0];
      this.logger.log(
        { collection, timestamp, duration, query },
        "PRISMA QUERY DEBUG"
      );
    });

    this.$use(async (params, next) => {
      const before = Date.now();

      const result = await next(params);

      const after = Date.now();

      const duration = after - before;

      this.logger.log(
        { collection: params.model, operation: params.action, duration },
        `Query ${params.model}.${params.action} took ${duration} ms`
      );

      return result;
    });
  }

  async onModuleInit() {
    await this.$connect();
  }

  async onModuleDestroy() {
    await this.$disconnect();
  }
}

```

**Comment by janpio** [comment]
Hey everyone that commented in this issue before, could you please try to temporarily install `prisma@dev` and `@prisma/client@dev` in your project and see if this fixes the problem? https://github.com/prisma/prisma/pull/23228 should have fixed this and will be included in the next release, but of course a confirmation of it now working as intended would be nice.

**Comment by wodCZ** [comment]
@janpio I've just tested and can confirm that the `dev` version no-longer freezes REPL instance when the command would output anything with prisma instance on it.

With `5.10.2` it does freeze, so the fix must've addressed it correcly.

Can't wait for the release, thanks SevInf and team for the fix 🙌

**Comment by YoannBuzenet** [comment]
> Hey everyone that commented in this issue before, could you please try to temporarily install `prisma@dev` and `@prisma/client@dev` in your project and see if this fixes the problem? #23228 should have fixed this and will be included in the next release, but of course a confirmation of it now working as intended would be nice.

Sorry for the noob question, but how can I do it ?

I have this message if I change the import : 

![Screenshot from 2024-03-07 15-07-33](https://github.com/prisma/prisma/assets/28066290/ebd90393-5744-4a7c-88ba-52c42b51f875)

I must be doing it wrong ?

**Comment by YoannBuzenet** [comment]
It works with the dev version. Thank you !

**Comment by thw0rted** [comment]
Hi @janpio , since it looks like the actual fix in the PR is only a few lines (and the rest are tests...), would it be possible to get a backport for those of us still stuck on 4.x?  The `[Symbol.for...]` fix a few comments up is helpful, but has to be re-applied every time I launch the REPL.

**Comment by janpio** [comment]
Unfortunately not, we never maintain older versions by backporting changes or fixes. 
You would need to do that yourself in a fork and publish it under your own package name.
Probably you can achieve something similar using https://www.npmjs.com/package/patch-package

**Comment by divmgl** [comment]
Thanks for this fix. 

I want to add another case where this was problematic. We have a dependency injection container where we store our Prisma client for use in parts of the app that require it. Dependencies are lazily loaded, but we connect the Prisma client on app launch, so it's always loaded.

There have been moments where we need to inspect other parts of the container, so we'll `console.log` the container. This is probably a bad idea, but we would log out the full container to inspect it. This would unfortunately hang the entire process during development and we were never able to figure out why this was happening. So now we know!

So thank you for fixing this bug! Super helpful!
