### ISSUE TITLE
zeit now deployment error when using 'Field Selection'

### ISSUE THREAD

**Issue by xero0001** [prisma/prisma#1830]
https://github.com/xero0001/prisma2_bugreport

here is my repository. It's based on prisma-example/typescript/auth-example.

It seems kinda typescript error.

When you deploy, 

in Query.ts.
```
    t.field('lesson', {
      type: 'Lesson',
      args: {
        lessonId: idArg({ nullable: false }),
      },
      nullable: true,
      resolve: (_, { lessonId }, ctx) => {
        return ctx.prisma.lesson.findOne({
          where: {
            id: lessonId,
          },
          select: {
            id: true,
          },
        })
      },
    })
```

this throws error.

`[31mNowBuildError: src/types/Query.ts(26,7): error TS2322: Type '(_: {}, { lessonId }: { lessonId: string; }, ctx: Context) => LessonClient<{ id: string; } | null>' is not assignable to type 'FieldResolver<"Query", "lesson">'.`

I also tried this with 'async-await' method, and error is like following.

`[31mNowBuildError: src/types/Query.ts(26,7): error TS2322: Type '(_: {}, { lessonId }: { lessonId: string; }, ctx: Context) => Promise<{ id: string; } | null>' is not assignable to type 'FieldResolver<"Query", "lesson">'.`

Are these errors are actually supposed to be thrown out, and can't I just use 'Field Selection' for return value? If then this must not be an error.

+ I'm always appreciate of prisma team!

**Comment by pantharshit00** [comment]
Hi @xero0001,

In your `Query.ts` file, you are just selecting the `id` field of from the database using the Prisma client which in the Lesson graphql object which you have defined has all fields required. That is why it is throwing a type error when you try to compile your code. In development, you have configured ts-node-dev in a way that it doesn't check types.


In order to fix this, remove the select statement like so:
```ts
import { idArg, queryType, stringArg } from 'nexus'
// import { getUserId } from '../utils'

export const Query = queryType({
  definition(t) {
    // t.field('me', {
    //   type: 'User',
    //   nullable: true,
    //   resolve: (parent, args, ctx) => {
    //     const userId = getUserId(ctx)

    //     return ctx.prisma.user.findOne({
    //       where: {
    //         id: userId,
    //       },
    //     })
    //   },
    // })

    t.field('lesson', {
      type: 'Lesson',
      args: {
        lessonId: idArg({ nullable: false }),
      },
      nullable: true,
      resolve: (_, { lessonId }, ctx) => {
        // return null
        return ctx.prisma.lesson.findOne({
          where: {
            id: lessonId,
          },
        })
      },
    })

    t.list.field('lessons', {
      type: 'Lesson',
      args: {
        classId: idArg({ nullable: false }),
      },
      nullable: true,
      resolve: (_, { classId }, ctx) => {
        return ctx.prisma.lesson.findMany({
          where: {
            class: {
              id: classId,
            },
          },
        })
      },
    })
  },
})
```

Let me know if you have any other questions. Also, don't use sqlite in production in zeit now as it is not recommended for lambda use.

**Comment by xero0001** [comment]
Thank you for replying!

Then, what should I do if I want to restrict some field from being queried?

Let me explain this with the original 'typescript/graphql-auth' example.

From **Post.ts**,
```
export const Post = objectType({
  name: 'Post',
  definition(t) {
    t.model.id()
    t.model.published()
    t.model.title()
    t.model.content()
    t.model.author()
  },
})
```

And if I want to restrict 'author' and 'content', I thought I could do this with following.

From **Query.ts**
```
t.list.field('feed', {
      type: 'Post',
      resolve: async (parent, args, ctx) => {
        return ctx.prisma.post.findMany({
          select: {
            id: true,
            published: true,
            title: true,
          },
        })
      },
    })
```

And it's not proper.

Then what can I do?
Should I use another object like **RestrictedPost.ts**
```
export const Post = objectType({
  name: 'Post',
  definition(t) {
    t.model.id()
    t.model.published()
    t.model.title()
  },
})
```

Like this?

**Comment by janpio** [comment]
Is this still relevant 1 year later or can this be closed?

**Comment by pantharshit00** [comment]
I don't think this is relevant anymore
