### ISSUE TITLE
Add wolfy linux to supported OS

### ISSUE THREAD

**Issue by mts-dyt** [prisma/prisma#18329]
## Problem

We are using Node secure docker image from chainguard: [cgr.dev/chainguard/node](https://github.com/chainguard-images/images/tree/main/images/node)

The following message is displayed when using prisma:
```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "wolfi". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
```

## Suggested solution

Add chainguard secured OS as supported images

**Comment by dlorenc** [comment]
Thanks for tagging me, let me know if I can help at all.

**Comment by jbergstroem** [comment]
> Thanks for tagging me, let me know if I can help at all.

Do you think it would make sense to use `debian` as targetDistro seeing how users then get a binary that works well with glibc and openssl? As I understand it, the client looks at the running environment and downloads a suitable engine from https://github.com/prisma/prisma-engines

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
