### ISSUE TITLE
Order of relation fields influences generated input types

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#18338]
### Bug description

When a model has multiple one-to-many relationships to the same model, the generated `<ModelName>RelationFilter` input type only depends on the first relation field. If the fields differ in nullability, the generated types and the runtime behavior (validation) change depending on the order of those fields.

Minimal schema: https://github.com/tomhoule/-prisma-dmmf-relation-field-ordering-influences-input-type-arity-repro
Clonable repro that shows the problem in TypeScript: https://github.com/aqrln/prisma-relation-filter-input-type-arity-e2e-repro
Real-world schema: https://github.com/prisma/prisma/blob/main/packages/internals/src/__tests__/__fixtures__/odoo.prisma

### How to reproduce

1. Clone https://github.com/aqrln/prisma-relation-filter-input-type-arity-e2e-repro
2. Run `npm install && npx prisma generate`
3. Run `npx ts-node index.ts` or open `index.ts` in the editor and see that the first and second Prisma queries:

```ts
  await prisma.b1.findMany({
    where: {
      brf: {
        is: null,
      },
    },
  });

  await prisma.b1.findMany({
    where: {
      b2rf: {
        is: null,
      },
    },
  });
```

both type-check while the third and the fourth queries:

```ts
  await prisma.b2.findMany({
    where: {
      brf: {
        is: null,
      },
    },
  });

  await prisma.b2.findMany({
    where: {
      b2rf: {
        is: null,
      },
    },
  });
```

both fail type checking.

This is wrong in half of the cases: the first query incorrectly typechecks although `brf` is not nullable in the schema, while the fourth query is incorrectly rejected although `b2rf` relation field is nullable.

The same problems are reproducible with runtime validation when running the script with `ts-node-transpile-only` and ignoring TypeScript errors because the issue is in the DMMF.

### Expected behavior

* The first query in the repro should fail type checking and runtime validation
* The fourth query in the repro should pass type checking and runtime validation
* Generally, order of fields must not change the same input type (and consequently both generated TS types and runtime behaviour)

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.sqlite"
}

// B1 and B2 are identical except the order of relation fields.

// Nullable field first
model B1 {
  bid  Int  @id
  b2fk Int?
  b2rf A1?  @relation(name: "b1_to_a1_opt", fields: [b2fk], references: [aid])
  bfk  Int
  brf  A1   @relation(fields: [bfk], references: [aid])
}

model A1 {
  aid  Int  @id
  arf  B1[]
  arf2 B1[] @relation("b1_to_a1_opt")
}

// Non-nullable field first
model B2 {
  bid  Int  @id
  bfk  Int
  brf  A2   @relation(fields: [bfk], references: [aid])
  b2fk Int?
  b2rf A2?  @relation(name: "b2_to_a2_opt", fields: [b2fk], references: [aid])
}

model A2 {
  aid  Int  @id
  arf  B2[]
  arf2 B2[] @relation("b2_to_a2_opt")
}

```

```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient();

  await prisma.b1.findMany({
    where: {
      brf: {
        is: null,
      },
    },
  });

  await prisma.b1.findMany({
    where: {
      b2rf: {
        is: null,
      },
    },
  });

  await prisma.b2.findMany({
    where: {
      brf: {
        is: null,
      },
    },
  });

  await prisma.b2.findMany({
    where: {
      b2rf: {
        is: null,
      },
    },
  });
}

void main();
```

### Environment & setup

- OS: macOS, Linux
- Database: SQLite, PostgreSQL
- Node.js version: v19.8.0

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0

```

**Comment by laplab** [comment]
Closing the issue as "Gone away".

**Comment by apolanc** [comment]
I closed the issue as "Not planned" 👍
