### ISSUE TITLE
Implement `daterange` type for postgres

### ISSUE THREAD

**Issue by shadoath** [prisma/prisma#18337]
## Problem

When adding Prisma to a project via introspection (`prisma db pull`) I ended up with fields like the following:
```
during   Unsupported("daterange")
```
Which leads to requiring raw SQL to create or update. 
As [noted in the docs](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#unsupported-types):
> Note: If a model has mandatory Unsupported fields, the generated client will not include create or update methods for that model.

## Suggested solution

Expand schema to include `daterange` type or way to add it custom to a project.

Postgres has the full [rangeTypes](https://www.postgresql.org/docs/current/rangetypes.html) for int, timestamp and dates.

Notes about [Inclusive and Exclusive Bounds](https://www.postgresql.org/docs/current/rangetypes.html#8.17.3) of rangeType.

>Every non-empty range has two bounds, the lower bound and the upper bound. All points between these values are included in the range. An inclusive bound means that the boundary point itself is included in the range as well, while an exclusive bound means that the boundary point is not included in the range.

>In the text form of a range, an inclusive lower bound is represented by “[” while an exclusive lower bound is represented by “(”. Likewise, an inclusive upper bound is represented by “]”, while an exclusive upper bound is represented by “)”.
```
(lower-bound,upper-bound)
(lower-bound,upper-bound]
[lower-bound,upper-bound)
[lower-bound,upper-bound]
empty
```

## Alternatives

Create a Prisma Postgres extension that would add these features.

## Additional context

This missing feature has locked the project into using SQL and casting to `:TEXT` then extracting my values to use Prisma, or to stick with the current ORM that's not typed.

Thank you for the consideration of this request for `daterange` type in Prisma.

**Comment by janpio** [comment]
Is this request covered by https://github.com/prisma/prisma/issues/3287?

**Comment by shadoath** [comment]
@janpio  yes it does look like that request came first and has a similar goal.
