### ISSUE TITLE
Enums not added to select 

### ISSUE THREAD

**Issue by d-sooter** [prisma/prisma#18335]
### Bug description

When executing a findMany without specifying specific columns, my enum fields are not included in the select ( log running) 

`
 SELECT "transmuter"."Formatters"."id", "transmuter"."Formatters"."tenant", "transmuter"."Formatters"."name", "transmuter"."Formatters"."description", "transmuter"."Formatters"."script", "transmuter"."Formatters"."version", "transmuter"."Formatters"."active", "transmuter"."Formatters"."tags", "transmuter"."Formatters"."matchers", "transmuter"."Formatters"."created_at", "transmuter"."Formatters"."created_by", "transmuter"."Formatters"."updated_at", "transmuter"."Formatters"."updated_by" FROM "transmuter"."Formatters" WHERE "transmuter"."Formatters"."active" = $1 OFFSET $2
`

If i specify the colums in a select it works:

`
Query: SELECT "transmuter"."Formatters"."id", "transmuter"."Formatters"."language" FROM "transmuter"."Formatters" WHERE "transmuter"."Formatters"."active" = $1 OFFSET $2
`

I changed the schema to a string and the query works as expected.

### Prisma information

```prisma
// Add your schema.prisma
enum Language {
    JS
    TS

    @@schema("transmuter")
}

model Formatters {
    id          Int       @id @default(autoincrement())
    tenant      String    @default("default")
    name        String
    description String
    script      String
    language    Language  @default(JS)
    version     Int       @default(1)
    active      Boolean   @default(false)
    tags        Json?
    matchers    Json
    // Managed fields
    createdAt   DateTime? @default(now()) @map("created_at")
    createdBy   String?   @map("created_by")
    updatedAt   DateTime? @updatedAt @map("updated_at")
    updatedBy   String?   @map("updated_by")

    @@schema("transmuter")
    @@unique([name, version], name: "formatters_name_version_key")

```

```ts
        let client = new PrismaClient({
            datasources: {
                db: {
                    url: this.configService.get('prisma.url'),
                },
            },
            errorFormat: 'pretty',
            log: this.configService.get('debug')
                ? [
                      { emit: 'event', level: 'query' },
                      { emit: 'stdout', level: 'info' },
                      { emit: 'stdout', level: 'warn' },
                      { emit: 'stdout', level: 'error' },
                  ]
                : [],
        });
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: 16
- Prisma 4.11.0

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at ..\..\node_modules\.pnpm\@prisma+engines@4.11.0\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at ..\..\node_modules\.pnpm\@prisma+engines@4.11.0\node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acbStudio                  : 0.483.0
Preview Features        : fullTextSearch, fullTextIndex, metrics, multiSchema, clientExtensions, views, jsonProtocol
```

**Comment by janpio** [comment]
Can you share the actual `findMany` query you ran?

**Comment by d-sooter** [comment]
Sure here is the request 

`
   return this.prisma.client.messageHandler.findMany({
            where: {
                active: true,
            },
        });
`

**Comment by ebg1223** [comment]
I am having the same issue!

**Comment by ebg1223** [comment]
After some testing, it appears this is related to enabling jsonProtocol. For my example, disabling the jsonProtocol preview feature fixed the issue. @d-sooter, maybe you can confirm?

**Comment by d-sooter** [comment]
I can confirm that it works without the JsonProtocol feature

**Comment by janpio** [comment]
Ah, I missed that you were using the preview feature.

This should already be fixed in our development version. You can read more about it in these two issues: https://github.com/prisma/prisma/issues/18148 + https://github.com/prisma/prisma/issues/18200 If you can confirm this is fixed, please close this issue. Thanks!

**Comment by janpio** [comment]
ping @d-sooter
