### ISSUE TITLE
Checksum the Engine binaries (archive extraction verification)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1834]
We have a hard to reproduce problem in https://github.com/prisma/prisma2/issues/1819. Right now our understanding is, that somehow during the extraction process of our engine `.gz` files something goes wrong and the resulting binary is corrupted.

To be able to avoid that, it would be helpful to have the sha256 checksum of the binary. Then after extraction, the script could compare that stored checksum to the real file checksum and handle accordingly.

(This checksum could be stored next to the archive, or in the archive itself)

**Comment by dpetrick** [comment]
Done on my side. Each .gz archive now has a `*.gz.sig` and `*.gz.sha256` file next to it in the bucket.
