### ISSUE TITLE
Failed to fetch stable Prisma version (unpkg.com)

### ISSUE THREAD

**Issue by x052** [prisma/prisma#18340]
### Bug description

Currently, unpkg.com is offline (https://github.com/mjackson/unpkg/issues/352) when executing a query with the prisma data proxy on a cloudflare worker an error is thrown `Error: Failed to fetch stable Prisma version, unpkg.com status 520 , response body: <empty body>`

Why is the prisma client making a request to `https://unpkg.com/prisma@${e}/package.json` every time it gets initialized?

Should the prisma client be reliant on the uptime of a third party service to function as expected?

Offending code https://github.com/prisma/prisma/blob/main/packages/engine-core/src/data-proxy/utils/getClientVersion.ts#L44 (or minified):

```js
function Nm(e) {
    return encodeURI(`https://unpkg.com/prisma@${e}/package.json`);
}
...fetch
if (!b.ok)
    throw new Error(
        `Failed to fetch stable Prisma version, unpkg.com status ${
                  b.status
                } ${b.statusText}, response body: ${(await b.text()) ||
                  "<empty body>"}`
    );
let v = await b.text();
Vu("length of body fetched from unpkg.com", v.length);
let h;
try {
    h = JSON.parse(v);
} catch (A) {
    throw (console.error(
            "JSON.parse error: body fetched from unpkg.com: ",
            v
        ),
        A);
}
return h.version;
}
```

### How to reproduce

1. Block unpkg.com on DNS / MITM
2. Run a prisma data proxy client sample project
3. See error

### Expected behavior

Prisma client with the data proxy should not rely on the uptime of unpkg.com to function

### Prisma information

```prisma

```

```ts
new PrismaClient({ log: ["query", "info", "warn"] });
```

### Environment & setup

    OS: Cloudflare Worker
    Database: MongoDB
    Node.js version: V8 Runtime

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.8.0-dev.24
Current platform        : debian-openssl-1.0.x
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by janpio** [comment]
This functionality is only used when you are on a non production, non stable `@prisma/client` version, like for example `4.8.0-dev.24` as shown in your `prisma -v` output. The data proxy only supports stable versions of @prisma/client - so in other cases it uses unpkg to get the closest stable version.

In your case, you could either up- or downgrade to 4.9.0 or 4.8.0. Or actually upgrade to 4.11.0 as your CLI version.

**Comment by x052** [comment]
Would it be appropriate to add a warning on the generate step? I've not seen this behavior documented on the prisma site either.

Can create a PR if needed.

**Comment by janpio** [comment]
Yeah, we never thought anyone would experience that honestly.

When exactly are you getting the error message? When you run `prisma geneate`? Or would you "just" warn there as that would be the best development time place to fix it or become aware at least?

**Comment by x052** [comment]
This error was occurring every time a query was made during the unpkg downtime (effectively taking the application offline).

It might be better to do the stable version check during `prisma generate` or at least warn of the potential side effects of using an unstable version during `prisma generate`

**Comment by janpio** [comment]
Warning during `generate`is a totally fair and good idea. Happy to accept a PR that adds that.

Only doing the check during `generate` would also be nice, but is a lot of effort for a feature that was not supposed to be publicly used anyway. We would need to do the request and then hardcode the resulting value in the generated Client somehow. If you find an easy way to do it, again happy to take a PR. Would definitely improve the situation.

**Comment by miguelff** [comment]
Confirmed this to be a behavior that would benefit from better warning. For the moment we won't fix it, but if other users are bitten by this, we will consider reopening as an enhancement.  Thank you for reporting @x052
