### ISSUE TITLE
 Error parsing attribute "@default": The function auto is not a known function.

### ISSUE THREAD

**Issue by ramezj** [prisma/prisma#18357]
### Bug description

I'm trying to use prisma with mongodb, I'm setting up the User model and I'm trying to add an autoincremented id.

![image](https://user-images.githubusercontent.com/84419219/225790706-c3aa3e49-7afa-455b-8a2b-17052596425b.png)

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by ramezj** [comment]
![image](https://user-images.githubusercontent.com/84419219/225791289-414507a5-4b21-4323-8942-494d10ff8dff.png)
This is the error I'm getting.

**Comment by brunoagtforte** [comment]
how did you fixed it ?

**Comment by ramezj** [comment]
> how did you fixed it ?

I stopped using prisma with mongo and used prisma with postgres, lol
