### ISSUE TITLE
`Prisma.join` queries fail when the provided array has a length of 1

### ISSUE THREAD

**Issue by arthurfiorette** [prisma/prisma#18367]
### Bug description

When using raw queries within prisma client, we can use `Prisma.join` to build a "`1, 2, 3`" string inside our queries. When you call a Prisma.join but passing an array with only 1 item, it crashes with the following error:

```ts
ERROR: operator does not exist: integer = jsonb
    HINT: No operator matches the given name and argument types. You might need to add explicit type casts.
```

**Note: this error probably will vary according to your schema.**

### How to reproduce

Run any query that calls `Prisma.join` with a 1 item only array.

### Expected behavior

To work just fine as when we do:

```ts
prisma.model.queryRaw`SELECT * FROM model WHERE table.a IN (${array.lenth === 1 ? array[0] : Prisma.join(array)})` 

```

### Prisma information

```prisma
model model {
  a Int
}
```

```ts
prisma.model.queryRaw`SELECT * FROM model WHERE table.a IN (${Prisma.join(array)})`
```

### Environment & setup

- OS: WSL
- Database: Postgres
- Node.js version: 19

### Prisma Version

```
4.11.0
```

**Comment by garth** [comment]
In my case, this issue affects all array lengths when using `Prisma.join` from `$queryRaw`.

```sql
          WHERE id IN (${Prisma.join(array)})
```
returns
```
ERROR: operator does not exist: integer = jsonb
```

In the end I had to convert my query to use `$queryRawUnsafe` to work around the issue.

```sql
          WHERE in IN (${array.join(',')})
```

**Comment by garth** [comment]
I've isolated this problem to be related to `typescript@5.0.2`. Reverting back to `typescript@4.9.5` fixed the issue for me.

Maybe something to do with the new way that v5 handles enums?

**Comment by janpio** [comment]
Can you help us out with a minimal reproduction, optimally in a repository we can clone?

**Comment by why-el** [comment]
We are facing this issue as well and we are on TS 4.7.4. It's a pretty serious bug because it fails at runtime and defeats the purpose of reaching into Prisma utility functions. Someone else reproduced in [a similar issue](https://github.com/prisma/prisma/issues/19062), see it here: https://github.com/evandeininger/prisma-bug.

**Comment by evandeininger** [comment]
My bug mentioned by @why-el is closed now for the same reason @garth mentioned, this could probably be closed as well.

**Comment by talesmgodois** [comment]
Well, I cant just upgrade to version 5 of prisma right now. 

> I found that this problem is resolved with the latest prisma and typescript v5.1 and and was able go back to using `$queryRaw` with `Prisma.join(array)`.

Which version of prisma could you solved it? I cant upgrade to 5 right now, It could lead to breaking changes.

**Comment by evandeininger** [comment]
@talesmgodois try the latest 14.x, looks like 14.16.2 works:
```
********4.16.2********
Query:
    SELECT * FROM Post
    WHERE title IN (@P1,@P2)

Params: ["Hello World","My First Post"]
Duration: 2ms
***************
Posts with specified titles: [
  {
    id: 1,
    title: 'Hello World',
    content: 'This is my first post',
    authorId: 1
  },
  {
    id: 3,
    title: 'My First Post',
    content: 'Excited to start blogging!',
    authorId: 2
  }
]
✅ Success!
```

**Comment by arthurfiorette** [comment]
Seems to be working fine with latest prisma version!
