### ISSUE TITLE
TypeError: t.map is not a function when performing updateMany on nested model.

### ISSUE THREAD

**Issue by pranavkhapra** [prisma/prisma#18371]
### Bug description

The issue is that I am getting a "t.map is not a function" error when running the code. This error usually indicates that I am trying to use the map function on a value that is not an array. However, that may not be the case here as I have tried checks where I am validating the data.

I have found some issues, but most of the explanations are not clear. I want to update a project which contains an array of tasks, but I am having trouble updating them. I am able to create new tasks using the same syntax, but updating them seems to be problematic. Can you provide any insight into why this might be happening?

```ts
 const project = await db.project.update({
      where: {
        ownerId_id: {
          id: req.query.projectId as string,
          ownerId: validated.id,
        },
      },
      data: {
        name: req.body.name,
        due: req.body.due,
        description: req.body.description,
        tasks: {
          updateMany: {
            data: req.body.tasks,
            where: {
              projectId: req.query.projectId as string,
            },
          },
        },
      },
    });
```
I have tried using debug mode, but there doesn't seem to be much helpful information there.

```
2023-03-17T17:29:21.261Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
2023-03-17T17:29:24.529Z compression gzip compression
error - TypeError: t.map is not a function
```

### How to reproduce

You can use this code to reproduce the issue. Please let me know if anything is unclear.
```ts
 const project = await db.project.update({
      where: {
        ownerId_id: {
          id: req.query.projectId as string,
          ownerId: validated.id,
        },
      },
      data: {
        name: req.body.name,
        due: req.body.due,
        description: req.body.description,
        tasks: {
          updateMany: {
            data: req.body.tasks,
            where: {
              projectId: req.query.projectId as string,
            },
          },
        },
      },
    });
```

### Expected behavior

The expected behaviour is that the code will update the tasks of the projectID obtained from the query, whose owner ID is the current user.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum AVATAR {
  SAITAMA
  MARIO
  WALTER_WHITE
  HARRY_POTTER
  MANDO
}

model User {
  id        String    @id @default(uuid())
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  email     String    @unique
  password  String
  firstName String
  avatar    AVATAR    @default(SAITAMA)
  lastName  String
  projects  Project[]
  tasks     Task[]
}

model Project {
  id          String    @id @default(uuid())
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  name        String
  ownerId     String
  owner       User      @relation(fields: [ownerId], references: [id])
  description String
  due         DateTime?
  deleted     Boolean   @default(false)
  tasks       Task[]

  @@unique([ownerId, name])
  @@unique([ownerId, id])
  @@index([ownerId, id])
}

enum TASK_STATUS {
  NOT_STARTED
  STARTED
  COMPLETED
}

model Task {
  id        String   @id @default(uuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  ownerId String
  owner   User   @relation(fields: [ownerId], references: [id])

  projectId String
  project   Project @relation(fields: [projectId], references: [id])

  status      TASK_STATUS @default(NOT_STARTED)
  name        String
  description String

  due     DateTime?
  deleted Boolean   @default(false)

  @@index([ownerId])
}
```

### Environment & setup

- OS:  Windows
- Database: PostgreSQL
- Node.js version:  v16.8.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.10.1
@prisma/client          : 4.10.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.10.1-1.80b351cc7c06d352abe81be19b8a89e9c6b7c110
Default Engines Hash    : aead147aa326ccb985dcfed5b065b4fdabd44b19
Studio                  : 0.481.0

```

**Comment by sn0wst0rm** [comment]
I'm having the same problem in the same scenario with my project. How can I fix this? @pranavkhapra did you find a solution? Thanks

**Comment by thathurtabit** [comment]
I'm also seeing this with `updateMany`. Did you find a solution @pranavkhapra? I see @janpio added tags to try to reproduce but then you closed it? Ta!

**Comment by pranavkhapra** [comment]
fix - Hi, @thathurtabit . I never resolved the issue, as I chose a different approach to implement the function while working on my personal project. However, since there were similar issues addressing the same problem, I closed this one. P.S- I am re-opening the issue and planning to attempt to address/solve the problem through a pull request whenever I have the time to do so.

**Comment by WillPwn4Food** [comment]
Still having this issue, kind of seems like a big deal. I'm using MongoDB on latest Prisma version (4.13.0)

**Comment by camin-mccluskey** [comment]
Also facing this issue - same situation as OP. Nested `updateMany` inside `update`

**Comment by ymc9** [comment]
I met the problem when the "where" clause under the nested "updateMany" is an empty object (or undefined). Replacing it with an alternative "always-true" ```{AND: []}``` seems to resolve the problem.

**Comment by camin-mccluskey** [comment]
Another approach that I've tried is the following - using the `set` operator.  This does seem to do _something_ in that the update is received with no error but nothing appears to be persisted to the DB. I'm _was_ quite confused in this case because my impression of the `set` operator was that it simply overwrites the relation field with the passed in data. However I realised `set` actually **disconnects** the old relation records and **connects** the relations passed. i.e. you need to have created the child records first. Basically, once again, this isn't the functionality we're looking for.

![Screenshot 2023-08-05 at 01 56 41](https://github.com/prisma/prisma/assets/18604525/a4f1882f-5bc9-4a59-91ee-a6cd3a56a028)

**Comment by osvaguillen** [comment]
This is still an open issue right? @timsuchanek 
any update?

**Comment by janpio** [comment]
Do you have a reproduction we can use to understand what is going on @osvaguillen?

**Comment by janpio** [comment]
But you are asking for an update, so I assume you also have the problem? If so, can you provide a reproduction we can easily use to confirm the problem? That would be the most useful action to help us move forward here.

**Comment by ymc9** [comment]
It seems the problem doesn't happen in the latest V5 release anymore. I just tried 5.8.1.
