### ISSUE TITLE
Prisma with UOS or Deepin

### ISSUE THREAD

**Issue by githubrobinlu** [prisma/prisma#18374]
## Problem

Exec: npx prisma db push
```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "uos". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
```

## Suggested solution

Add 'uos' to distro.

## Additional context

哪位装了Deepin，也可以试试看prisma能否识别deepin发行版。

**Comment by Jolg42** [comment]
Note: related Deepin issue https://github.com/prisma/prisma/issues/19157

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
