### ISSUE TITLE
Prisma client for Data Proxy + Deno -> Unexpected Syntax Error

### ISSUE THREAD

**Issue by sliim35** [prisma/prisma#18389]
### Bug description

Followed the [example](https://deno.land/manual@v1.28.3/node/how_to_with_npm/prisma)
Prisma doesn't generate a proper client for data proxy.

### Prerequisites
- Postgres
- Need to [generate data proxy string](https://www.prisma.io/docs/data-platform/projects/create#optional-create-a-data-proxy-connection-string)

### Error

```bash
deno run -A prisma/example.ts
```
will throw
```
Sending fatal alert BadCertificate
```
If I suppress it like that
```bash
deno run -A --unsafely-ignore-certificate-errors prisma/example.ts
```
will throw
```
  error: SyntaxError: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON
    at parse (<anonymous>)
    at packageData (ext:deno_fetch/22_body.js:362:14)
```

I tried it with nodejs `v18.13.0`
```
node test.js
```
will throw
```
PrismaClientKnownRequestError:
Invalid `prisma.user.create()` invocation:

Cannot fetch data from service:
unable to verify the first certificate
```
suppress tls

```
NODE_TLS_REJECT_UNAUTHORIZED=0 node test.js
```
will throw
```
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
```

### Init new prisma project
`deno run --A --unstable npm:prisma init`

### Create prisma schema
```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["deno"]
  output = "../generated/client"
}

datasource db {
  provider = "postgresql"
  url      = env("DB_URL")
}

model User {
  id       Int    @id @default(autoincrement())
  name     String
  jobTitle String
}
```

### Generate a Prisma client for Data Proxy
`deno run -A --unstable npm:prisma generate --data-proxy`

### Use it
```ts
import { Prisma, PrismaClient } from "../generated/client/deno/edge.ts";
import { config } from "https://deno.land/std/dotenv/mod.ts";

const envVars = await config();

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: envVars.DATABASE_URL,
    },
  },
});

await prisma.user.create({ data: ... });
```
### Make sure that db works
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/26935057/226414363-61322099-1747-4dd6-a2c5-395e076c73fe.png">

### Expected behavior

It has to work as it works without a data proxy

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["deno"]
  output = "../generated/client"
}

datasource db {
  provider = "postgresql"
  url      = env("DB_URL")
}

model User {
  id       Int    @id @default(autoincrement())
  name     String
  jobTitle String
}
```

```ts
import { Prisma, PrismaClient } from "../generated/client/deno/edge.ts";
import { config } from "https://deno.land/std/dotenv/mod.ts";

const envVars = await config();

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: envVars.DATABASE_URL,
    },
  },
});

await prisma.user.create({ data: ... });
```

### Environment & setup

- OS: macOS 13.2.1 
- Database: Supabase PostgreSQL 
- Deno version: deno 1.31.3 (release, aarch64-apple-darwin)
                           v8 11.0.226.19
                           typescript 4.9.4 

### Prisma Version

```
4.11.0
```

**Comment by janpio** [comment]
Hey @sliim35, your schema uses `env("DB_URL")` but your code `url: envVars.DATABASE_URL,` - is that just a copy/paste error or oversight? 

Besides that, for me what you describe works fine in a Deno app. But you also report similar problems in a Node based script, is that correct? If so, this is probably not a Deno or Prisma problem, but something in your network setup.

Is there something special about the networking on your computer maybe?

**Comment by janpio** [comment]
Did you see my earlier message @sliim35?

**Comment by SevInf** [comment]
Hey @sliim35 ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
