### ISSUE TITLE
Automatically publish binaries of release as Github Release Assets

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1841]
Example see https://github.com/sass/node-sass/releases

Context see https://github.com/prisma/prisma2/issues/916#issue-520628639

Rough idea for how to implement this:

- New Github Actions workflow for releases/tags
- Check out current repository, and figure out the current Engines commit hash
- Download all binaries for all platforms
- Use an existing GH Action to add all these binaries to the release
- Profit!

**Comment by Jolg42** [comment]
Is it still relevant or can we close this @janpio ?

**Comment by janpio** [comment]
It would be one way how people could get all binaries to upload to their binary mirror to use for CLI and Client.
