### ISSUE TITLE
Typescript Error when using contains and mode: "insensitive" inside OR operator

### ISSUE THREAD

**Issue by rubek-joshi** [prisma/prisma#18413]
### Bug description

A bit weird but when I store my `where` query in a variable then Typescript complains whereas when I put my query directly it works. I am storing my `where` query in a variable because I use the same query to `count` the total as well.

In a nutshell, this doesn't work (here db is prisma):

![image](https://user-images.githubusercontent.com/33681318/226827527-5d362344-6dd7-417b-b27f-0eba7fffed80.png)

But this works:

![image](https://user-images.githubusercontent.com/33681318/226827678-36f7c05e-a9ce-4b68-9877-fbe768ddff9a.png)

### How to reproduce

1. Create a user model with `fullName` of type `String`.
2. Create a variable containing the following query:
```ts
const query = {
    OR: [
      { fullName: { contains: search, mode: "insensitive" } },
    ],
};
```
4. Place the above variable in the `where` attribute like so:
```ts
const data = await db.user.findMany({ where: query });
```
5. See error

### Expected behavior

Typescript should not be complaining.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["clientExtensions"]
}

datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}

model User {
  id           BigInt        @id @default(sequence())
  fullName     String
  phoneNumber  String        @unique
  createdAt    DateTime      @default(now())
  updatedAt    DateTime      @updatedAt

  @@map("users")
}
```

```ts

const search = "test";

const query = {
    OR: [
      { fullName: { contains: search, mode: "insensitive" } },
      { phoneNumber: { contains: search, mode: "insensitive" } },
    ],
};

const data = await prisma.user.findMany({
    where: query,
    select: {
      id: true,
      fullName: true,
      phoneNumber: true,
    },
    skip: 0,
    take: 10,
});

const total = await prisma.user.count({ where: query });
```

### Environment & setup

- OS: Windows
- Database: CockroachDB
- Node.js version: v18.12.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules\.pnpm\@prisma+engines@4.11.0\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules\.pnpm\@prisma+engines@4.11.0\node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb   
Studio                  : 0.483.0
Preview Features        : clientExtensions
```

**Comment by rubek-joshi** [comment]
@SevInf Unfortunately the 1st way doesn't work, I get this error:
![image](https://user-images.githubusercontent.com/33681318/228757929-f4b1e761-4270-435c-9a42-7a397e014056.png)

The 2nd way kind of works as in TS no longer complains, the code compiles **BUT** the `mode: "insensitive"` isn't working. The query results are still case sensitive.

**Comment by thanhtamha** [comment]
I am using Prisma in my JS project, hitting the same issue.
So any suggestion how can i bypass this issue ?

**Comment by thanhtamha** [comment]
Thanks, but my project is using Javascript 5-6 years ago. We don't use TS, so it dont have this Prisma.UserWhereInput
Thats why, i m thinking whether we can have some way to bypass or not.

**Comment by janpio** [comment]
Then you should not have TypeScript type errors, right?
Best open a new bug report issue with a full description of the problem you are hitting.

**Comment by thanhtamha** [comment]
With the mode: "insensitive", the query will hit this error below.
Without the mode: "insensitive", the query is working fine.
If i recall correctly, this query work fine before. It start to happen when i use later version of Prisma.

"
Invalid `prisma.image.findMany()` invocation:

{
  where: {
    code: {
      contains: "LOGO",
      mode: "insensitive",
      ~~~~
?     equals?: String | StringFieldRefInput,
?     in?: String[],
?     notIn?: String[],
?     lt?: String | StringFieldRefInput,
?     lte?: String | StringFieldRefInput,
?     gt?: String | StringFieldRefInput,
?     gte?: String | StringFieldRefInput,
?     startsWith?: String | StringFieldRefInput,
?     endsWith?: String | StringFieldRefInput,
?     not?: String | NestedStringFilter
    }
  },
  orderBy: {
    code: "asc"
  },
  skip: 0,
  take: 10
}

Unknown argument `mode`. Did you mean `lte`? Available options are marked with ?."

**Comment by janpio** [comment]
Then please open a new bug report issue, and provide all the information the issue template asks for. Optimally, provide a full reproduction as a GitHub project we can run ourselves. Thank you!
