### ISSUE TITLE
PrismaClientInitializationError: Query engine library for current platform "linux-musl-arm64-openssl-3.0.x" could not be found

### ISSUE THREAD

**Issue by rafael-jordao** [prisma/prisma#18473]
# Problem
You incorrectly pinned it to linux-musl-arm64-openssl-3.0.x. This probably happens, because you built Prisma Client on a different platform.

# Suggested solution
You already added the platforms "darwin-arm64", "linux-musl-arm64-openssl-3.0.x" to the "generator" block in the "schema.prisma" file as described in https://pris.ly/d/client-generator, but something went wrong. That's suboptimal. Please create an issue at https://github.com/prisma/prisma/issues/new.

# Additional context
I noticed that when I download Prisma using the `yarn add` prisma command, it is correctly installed in **node_modules**, with the **.prisma_fmt_build_bg.wasm** file inside the build folder. However, when I run `docker compose up -d` to create my containers, the connection to the database fails and we have the errors mentioned above, in addition to the .prisma_fmt_build_bg.wasm file changing its extension to .prisma_fmt_build_bg.wasm.icloud. 

I have already tried uninstalling and reinstalling Prisma.

I saw a similar issue in [#8478](https://github.com/prisma/prisma/issues/8478), and I noticed that the problem was solved in Prisma 4.10.0, but something seems to be going wrong.

**Comment by janpio** [comment]
> in addition to the .prisma_fmt_build_bg.wasm file changing its extension to .prisma_fmt_build_bg.wasm.icloud.

That is definitely not caused by Prisma itself.
