### ISSUE TITLE
Autocomplete mutation data with relation ID

### ISSUE THREAD

**Issue by sedubois** [prisma/prisma#185]
If I have User and Slug types, with a field slug on User (1-to-1 relation), I can create this mutation from Playground:

```
mutation {
  createUser(
    givenName: "Bart"
    familyName: "Simpson"
    slugId: 
  ) {
    givenName
  }
}
```

Thanks to GraphiQL all the types can be auto-completed, but for the `slugId` I'm forced to go to the data view and copy-paste manually the ID that needs to go there. It would be great to be able to auto-complete with alt-space just like for other GraphQL types.

**Comment by marktani** [comment]
What I'll usually do is this:

```graphl
query allSlugs {
  allSlugs {
    id
    name
  }
}

mutation createUser {
  createUser(
    givenName: "Bart"
    familyName: "Simpson"
    slugId: ""
  ) {
    givenName
  }  
}
```

then I run the query first and copy paste the fitting id from the right.

**Comment by sedubois** [comment]
Thanks I'll try the suggestion. 

Hmm ideally there would be a pop up where the node can be selected through a search, just like when linking a relation. (BTW that search system could also get some love, there it's also just a flat list (with a search box).)
