### ISSUE TITLE
Error: FUNCTION GET_LOCK does not exist

### ISSUE THREAD

**Issue by Lizhooh** [prisma/prisma#18508]
### Bug description

I will use a TDSQL like database `Oceanbase` that is fully compatible with MySQL, but there are some errors

1. mysql:// ...

![image](https://user-images.githubusercontent.com/19299088/227857091-6b569fb8-20af-4dfc-91bd-3c7486e4b981.png)

This may be the problem (  https://github.com/prisma/prisma/issues/6207 ), but:

2. mysql:// ... ?prefer_socket=false

I Close ` prefer_socket ` but this error occurred

![image](https://user-images.githubusercontent.com/19299088/227856156-4f864a4a-6b61-42df-9776-ff2fed38ec27.png)

### How to reproduce

1. mysql  url set ?prefer_socket=false
2. npx prisma migrate dev ...
3. out Error: FUNCTION GET_LOCK does not exist

### Expected behavior

Normal execution

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Debian
- Database: Oceanbase
- Node.js version: v16.19.0

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.2.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by Lizhooh** [comment]
Oceanbase does not support GET_ LOCK

**Comment by Lizhooh** [comment]
Fantastic and obscene techniques
奇淫技巧

/?refer_socket=false&a=.psdb.cloud

**Comment by dengfuping** [comment]
> Fantastic and obscene techniques 奇淫技巧
> 
> /?refer_socket=false&a=.psdb.cloud

@Lizhooh It doesn't work for me. Any solution else?

**Comment by dengfuping** [comment]
> Fantastic and obscene techniques 奇淫技巧
> 
> /?refer_socket=false&a=.psdb.cloud

The working principle of this workaround is as follows:

https://github.com/prisma/prisma-engines/blob/29bc8ca375232bc314ff30d684056b8c5a8f0583/schema-engine/connectors/sql-schema-connector/src/flavour/mysql.rs#L72-L89

https://github.com/prisma/prisma-engines/blob/29bc8ca375232bc314ff30d684056b8c5a8f0583/schema-engine/connectors/sql-schema-connector/src/flavour/mysql.rs#L555-L558

**Comment by dengfuping** [comment]
https://github.com/oceanbase/oceanbase/issues/1687
