### ISSUE TITLE
`Error: Schema parsing error: Argument "value" is missing in attribute "@default".` in `generate` for enum with empty string value

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#1852]
Happens in following schemas

- mysql_public/coppermine_stderr
- mysql_public/youngcart5
- mysql_public/rido

...

Full error from `prisma2 generate`
```
Error: Schema parsing
error: Argument "value" is missing in attribute "@default".
  -->  schema.prisma:228
   | 
227 |   user_email                   String                      @default("")
228 |   user_email_valid             copp_users_user_email_valid @default()
   | 

Validation Error Count: 1
```

Minimal reproduction (from schema after introspection)
```
model copp_users {
  user_email_valid             copp_users_user_email_valid @default()
}

enum copp_users_user_email_valid {
  YES  
}
```

Origin should be in introspection, see https://github.com/prisma/introspection-engine-output/blob/77ca4be2d8c6d6d4031ab796ef3c9838791eb91a/mysql_public/coppermine.log#L3

SQL exported from copp_users
```sql
-- -------------------------------------------------------------
-- TablePlus 3.1.2(296)
--
-- https://tableplus.com/
--
-- Database: coppermine
-- Generation Time: 2020-03-16 15:32:22.1270
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


CREATE TABLE `copp_users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_group` int(11) NOT NULL DEFAULT '2',
  `user_active` enum('YES','NO') COLLATE latin1_german2_ci NOT NULL DEFAULT 'NO',
  `user_name` varchar(25) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_password` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_password_salt` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_password_hash_algorithm` varchar(25) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_password_iterations` varchar(25) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_lastvisit` datetime NOT NULL DEFAULT '1000-01-01 00:00:00',
  `user_regdate` datetime NOT NULL DEFAULT '1000-01-01 00:00:00',
  `user_group_list` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_email` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_email_valid` enum('YES','') COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_profile1` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_profile2` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_profile3` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_profile4` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_profile5` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_profile6` text COLLATE latin1_german2_ci NOT NULL,
  `user_actkey` varchar(32) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  `user_language` varchar(40) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `user_name` (`user_name`),
  KEY `user_group` (`user_group`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci COMMENT='Used to store users, not used when bridged';



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
```

**Comment by Jolg42** [comment]
The original full SQL schema is here https://github.com/prisma/database-schema-examples/blob/master/mysql/coppermine/schema.sql

**Comment by janpio** [comment]
The enum definition in the model looks like this:

```
enum copp_users_user_email_valid {
  YES
  
}
```

which makes sense for this SQL:

```
enum('YES','')
```

and also is "correct" for the introspected @default then:

```
@default()
```

Not sure how this would correctly be represented :/

---

Same for `youngcart5`:

```
enum g5_board_bo_use_cert {
  
  cert
  adult
  hp_cert @map("hp-cert")
  hp_adult @map("hp-adult")
}
```

---

Same for `rido`:

enum gml_board_bo_use_cert {
  
  cert
  adult
  hp_cert @map("hp-cert")
  hp_adult @map("hp-adult")
}

**Comment by janpio** [comment]
Information from duplicate #1865:

> For example `mariadb/coppermine_stderr.log`:
> 
> ```
> "error: Argument 'value' is missing in attribute '@default'.
>   -->  schema.prisma:228
>    | 
> 227 |   user_email                   String                      @default('')
> 228 |   user_email_valid             copp_users_user_email_valid @default()
>    | 
> 
> Validation Error Count: 1
> "
> ```
> 
> Model and Enum:
> 
> ```
> model copp_users {
>   user_active                  copp_users_user_active      @default(NO)
>   user_actkey                  String                      @default("")
>   user_email                   String                      @default("")
>   user_email_valid             copp_users_user_email_valid @default()
>   user_group                   Int                         @default(2)
>   user_group_list              String                      @default("")
>   user_id                      Int                         @default(autoincrement()) @id
>   user_language                String                      @default("")
>   user_lastvisit               DateTime                    @default(dbgenerated())
>   user_name                    String                      @default("") @unique
>   user_password                String                      @default("")
>   user_password_hash_algorithm String                      @default("")
>   user_password_iterations     String                      @default("")
>   user_password_salt           String                      @default("")
>   user_profile1                String                      @default("")
>   user_profile2                String                      @default("")
>   user_profile3                String                      @default("")
>   user_profile4                String                      @default("")
>   user_profile5                String                      @default("")
>   user_profile6                String
>   user_regdate                 DateTime                    @default(dbgenerated())
> 
>   @@index([user_group], name: "user_group")
> }
> 
> enum copp_users_user_email_valid {
>   YES
>   
> }
> ```
> 
> SQL:
> 
> ```
> CREATE TABLE `copp_users` (
>   `user_id` int(11) NOT NULL AUTO_INCREMENT,
>   `user_group` int(11) NOT NULL DEFAULT '2',
>   `user_active` enum('YES','NO') COLLATE latin1_german2_ci NOT NULL DEFAULT 'NO',
>   `user_name` varchar(25) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_password` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_password_salt` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_password_hash_algorithm` varchar(25) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_password_iterations` varchar(25) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_lastvisit` datetime NOT NULL DEFAULT '1000-01-01 00:00:00',
>   `user_regdate` datetime NOT NULL DEFAULT '1000-01-01 00:00:00',
>   `user_group_list` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_email` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_email_valid` enum('YES','') COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_profile1` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_profile2` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_profile3` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_profile4` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_profile5` varchar(255) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_profile6` text COLLATE latin1_german2_ci NOT NULL,
>   `user_actkey` varchar(32) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   `user_language` varchar(40) COLLATE latin1_german2_ci NOT NULL DEFAULT '',
>   PRIMARY KEY (`user_id`),
>   UNIQUE KEY `user_name` (`user_name`),
>   KEY `user_group` (`user_group`)
> ) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci COMMENT='Used to store users, not used when bridged';
> ```

**Comment by do4gr** [comment]
Enum values are constant literals in the datamodel and are therefore not quoted. This leads to the schema above which follows all our existing rules from the introspection perspective. The enum declaration contains the value `""` (empty string) but without quoting it since it is a constant literal, same goes for the default value. 

We could also leave it as it is now and just allow an empty default in the validator, but that might be confusing to users. 

Alternatively, I could see placeholder for empty string fixing this.

``` prisma
model a {
  enum            B @default(EMPTY_STRING_PLACEHOLDER)
}

enum B {
  YES 
  EMPTY_STRING_PLACEHOLDER @map("")
}
```

**Comment by sorenbs** [comment]
I think @do4gr 's Alternative suggestion is correct, although I would phrase it differently:

The empty string is not a valid name in the Prisma schema (including for enum values). Therefore you need to pick a valid name (such as "EMPTY_STRING_PLACEHOLDER" or "_") and map it to the correct value in the database.

@janpio - does that mental model make sense to you?

**Comment by janpio** [comment]
I can follow it in the context of Prisma Schema where the values are also _identifiers_. Enums in SQL work differently in that you just provide a list of _values_ - so that mismatch would still catch me off guard and will probably many users. Probably no way around that though.
