### ISSUE TITLE
Version 4.11.0 onwards - `Prisma.empty` does not work for raw queries, treats as expected parameter (SQL Server)

### ISSUE THREAD

**Issue by PatricioNG** [prisma/prisma#18526]
### Bug description

I've created an example repository here: https://github.com/PatricioNG/prisma-mssql-error-reproduction

The issue:
When using `Prisma.empty` on the MSSQL provider, raw queries do not treat the empty string as a null value on version 4.11.0. This does work on 4.10.1, which seems to indicate a bug between releases. We're undergoing a database migration from MySQL to MSSQL and noticed this was an issue between the two database providers.

Attached in the example repository is a simple test to prove the bug, let me know if any other information is required!

### How to reproduce

1. Download repo and install deps
2. Spin up a MSSQL server instance, push migration up to create a user table
3. Add in some default values to the table
4. Test on 4.11.0 by running npm run dev notice the console output and invalid `@P1` for the second query
5. Install 4.10.1 and test again, notice both queries return results without issue.

### Expected behavior

`Prisma.empty` is treated as a null value on 4.11.0 onwards

### Prisma information

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  output   = "./generated/Example"
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model users {
  id   Int    @id @default(autoincrement())
  name String
}

```

Can be used as an example repo, instructions in github example repo.

### Environment & setup

- OS: Windows 10 and Windows server 2019
- Database: SQL Server
- Node.js version: 18.14.0

### Prisma Version

```
4.11.0 has the issue,
4.10.1 works
```

**Comment by truediogo** [comment]
Confirmed here!

A simple ternary by itself turns into a parameter, like:
` ${term ? '' : ''}`

Following the docs also: https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#tagged-template-helpers
`${term ? Prisma.sql`AND team.name LIKE '%${term}%'` : Prisma.empty}`

ill test with 4.10.1

**Comment by PatricioNG** [comment]
Can confirm this is still an issue on 4.14.0, as I've recently updated to that version

**Comment by janpio** [comment]
Can confirm with 4.14.0.

But at the same time everything works now with 5.14.0. Do you agree @PatricioNG and @truediogo that this has been fixed along the way?

**Comment by PatricioNG** [comment]
Ah, looks like it! I had just given up hope and have been working around it where possible since/haven't tried again 😆 but glad to know I can (and have been able to since 4.15) drop my workarounds and simplify things 👏👏 

Thanks for double-checking this old one, @janpio! One more SQL Server bug down, now just praying for the query chunking fix 🙏 😇
