### ISSUE TITLE
installation fails with 404 on NixOs

### ISSUE THREAD

**Issue by jankaifer** [prisma/prisma#18531]
### Bug description

This bug is related to #3026. I understand that explicitly supporting `nix` is out of scope for Prisma, but precisely for that reason, a lot of people use https://github.com/Mic92/nix-ld

So if installation downloaded generic binary, it would work out of the box. The playwright does something similar, they will fallback to ubuntu when on an unknown system, but they will print a warning that "This system is not explicitly supported, and you are on your own".

Original issue #3026 mentioned a workaround, but it's needlessly tedious.

### How to reproduce

Run `prisma generate` on NixOS
You will get this:
```
> prisma generate

Warning Precompiled engine files are not available for nixos.
> Downloading Prisma engines for Node-API for linux-nixos [    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a/linux-nixos/migration-engine.gz
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected behavior

It should just print a warning but continue.

### Prisma information

irrelevant

### Environment & setup

- OS: NixOs

### Prisma Version

```
prisma: 4.13.0
```

**Comment by janpio** [comment]
Can you please provide some more information on what error you are actually getting?
Can you please also try installation with a _newer_ version of Prisma? We fixed quite a few things recently - and 3.15.2 is really old.

**Comment by jankaifer** [comment]
So sorry. These issues are irritating, and I just made one <picture data-single-emoji=":sad_praying_cowboy:" title=":sad_praying_cowboy:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..QIPGmqM39XUMorRu.aBUXZmz0Y5XX2x3v11iUZRsOn1OXfjcB3l8JJs8fRp9xFm_j0gZX4cicBRfl7b_W2Na79y2ynKsH710vVGpyvQLiHsKABVQdA-KQ_44PqllXerlueu6F_FpSbRl5nssR2MqL.fvb9fG9BjoWwsJ0vMviKNA" alt=":sad_praying_cowboy:" align="absmiddle"></picture>.

It didn't work in the latest a few weeks ago. But I works now in `4.12.0`.

**Comment by janpio** [comment]
All good, happy it works now for you!

**Comment by Pauan** [comment]
@jankaifer How did you get it working? I'm trying to use prisma 4.13.0 on NixOS and I get this error on installation:

```
> prisma generate

Warning Precompiled engine files are not available for nixos.
> Downloading Prisma engines for Node-API for linux-nixos [    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a/linux-nixos/migration-engine.gz
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Weakky** [comment]
Hey @jankaifer,

Two things:
1. Since your issue was created, we've improved the error message and you're now asked to build your own engine for NixOS https://www.prisma.io/docs/orm/more/under-the-hood/engines#using-custom-engine-libraries-or-binaries. We know this isn't convenient.
2. If you still need a NixOS build, @aqrln started a PR above that you could contribute to, to get it over the finish line.

**Comment by jankaifer** [comment]
Thanks for those improvements. It's great to hear about them.

I think this issue can be closed as there is official workaround now (build your own thing).

**Comment by aqrln** [comment]
@jankaifer to add to that, you can also use https://github.com/VanCoding/nix-prisma-utils if you're using Nix flakes.
