### ISSUE TITLE
init: Parameter to configure what database is used for `provider` and `url` example

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1854]
If would save 2 (small) necessary changes for each project that should use MySQL or SQLite instead of the PostgreSQL default for these values.

Might also be a tiny undocumented internal feature for quicker reproductions etc if we want to keep the API clean.

**Comment by pantharshit00** [comment]
Small note: you can use this cli for reproductions: https://github.com/timsuchanek/auto

It basically does the same thing described but also install deps and setup a reproduction script.

**Comment by janpio** [comment]
More elaborate proposal: https://github.com/prisma/prisma/issues/7126
