### ISSUE TITLE
Warning: Linux distro "slackware"

### ISSUE THREAD

**Issue by trasherdk** [prisma/prisma#18547]
## Problem

```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "slackware". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
```

## Suggested solution

Add `slackware` to the list.

I'm currently running:
  `Slackware` `i686 (current)`
  ```sh
# node -v && npm -v
  v18.15.0
  9.6.2
  ```

  `Slackware64` `x86_64 14.2`
  ```sh
# node -v && npm -v
  v16.19.1
  9.6.1
  ```

  `Slackware64` `x86_64 15.0`
  ```sh
$ node -v && npm -v
  v18.15.0
  9.6.2
  ```
with `mysql  Ver 14.14 Distrib 5.7.40`

## Alternatives

Don't do anything, as default `debian` probably is okay :smile: 

## Additional context

Running `pnpm install -D prisma @prisma/client` overwrites existing `.env` as an extra annoyance, besides the above warning.

**Comment by TransAMrit** [comment]
+1 to this, I'm also recently using Prisma on Slackware. Thanks

**Comment by macgherl57** [comment]
+1 here too... works fine with debian, but the console is flooded by prisma:warning Prisma doesn't know etc.

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
