### ISSUE TITLE
Data type JSON

### ISSUE THREAD

**Issue by Errorname** [prisma/prisma#186]
When converting the following datamodel:
```
type A {
  id: ID! @unique

  text: String!

  meta: JSON!
}
```

Using the following method:
```
cat datamodel.graphql | prisma2 convert > schema.prisma
```

I get the following schema:
```
model A {
  id   String @default(cuid()) @id @unique
  text String
}
```

As we can see, the `meta: JSON` attribute is missing

**Comment by pantharshit00** [comment]
JSON type is currently not supported in the datamodel. We may support it via native database type. Marking this as a feature request.

**Comment by robmurtagh** [comment]
Would love to see this feature!

**Comment by pantharshit00** [comment]
We surely have an intent to support this via native database types we have introduced in the schema: https://github.com/prisma/specs/tree/master/schema#type-specifications

So the `JSON` type will be just another database-specific type:
```groovy
model User {
  id   String @id @default(uuid())
  misc String @pg.JSON
}
```

**Comment by nhuesmann** [comment]
@pantharshit00 Sounds promising! If you do implement this, could you guys make sure to provide examples of how it will work with Nexus?

**Comment by thimovss** [comment]
Any updates on if/when this feature will be implemented?

**Comment by chrisdrackett** [comment]
just ran into this while migrating from prisma 1 to 2. This has effectively stopped the migration process for us.

**Comment by nhuesmann** [comment]
@chrisdrackett I'm just storing the stringified JSON for now until they implement the JSON type.

**Comment by chrisdrackett** [comment]
yep, I'm doing the same. I have a bit more `JSON.parse` and `JSON.stringify` than I'd like, but its working :)

**Comment by aberbob** [comment]
Commenting to know when anything changes. I am trying to move from Sequelize and need the JSON data type in MySQL. Migration was a breeze (30 mins for 46 tables and relations in about every table) except for the JSON type. :)

**Comment by pantharshit00** [comment]
The spec work is still ongoing. Latest work can be tracked in this PR in the specs repository: https://github.com/prisma/specs/pull/291

**Comment by heymartinadams** [comment]
@chrisdrackett not that it matters much, but your approach might appear to have some advantages :) https://www.youtube.com/watch?v=ff4fgQxPaO0

**Comment by janpio** [comment]
Internal Note: Dropping from current sprint, and picking up later.

**Comment by namesphill** [comment]
Hey! Do you guys happen to have an ETA on this feature?

**Comment by homerjam** [comment]
Great to see this in the Beta 3 milestone. Does anyone have any suggestions for a quick and dirty workaround for upgrading a prisma1 project in the meantime?

**Comment by martinnirtl** [comment]
Hey!

You could use the string type and JSON.stringify your object or array for the time 😃

**Comment by homerjam** [comment]
Thanks - that's what I'm planning but hoped there was something "more smarter" 🤓

**Comment by airhorns** [comment]
Is this closed because this is a wontfix now? JSONB support would be really awesome to get in!

**Comment by martinnirtl** [comment]
its now supported in beta4 😃

**Comment by robmurtagh** [comment]
Ah, great. Where do you see documentation of JSON support for `beta4`?

I can't see anything in the release notes:
https://github.com/prisma/prisma/releases/tag/2.0.0-beta.4

**Comment by martinnirtl** [comment]
i just saw that the issue was closed and gave `Json`-type a shot with `prisma migrate`.

everything worked out and i got `jsonb` fields in postgres db 😬

**Comment by pantharshit00** [comment]
Please follow https://github.com/prisma/prisma/issues/2322 for documentation update for JSON support. Please note there is still ongoing work their like filtering support.

**Comment by hugohammarstrom** [comment]
When I try to run the following mutation I receive a Graphql parsing error. 

```js
const post = await client.post.create({
    data: {
      title: "Test",
      data: {
        version: 1,
        // ...some json data
      },
    }
  });
```

![image](https://user-images.githubusercontent.com/7461128/80862731-99598880-8c77-11ea-9cfe-dfaf734353a1.png)

**Comment by pantharshit00** [comment]
Hi @hugohammarstrom 

Please open a  new issue about this as this one tracks the implementation of JSON type. Thanks!

**Comment by mavilein** [comment]
Here is a summary of what we implemented so far:

**Prisma Schema**
The data type for JSON is called `Json` in the schema. It can be used like this:
```prisma
model Blog {
  id   Int @id
  json Json 
}
```

It is supported by the MySQL and Postgres connectors. It is not supported by SQLite.

**Introspection**
The `prisma introspect` command maps the following column types to `Json`:
* Postgres: `json` and `jsonb`
* MySQL: `JSON` 

**Migrations**
`prisma migrate` uses the following data type when creating a column for a field of type `Json`:
* Postgres: `jsonb`
* MySQL: `JSON`

**Important Details**
JSON support for MySQL is only supported for versions greater than 5.6. As we don't have version information available during schema validation no error is shown in this case. However we have version information available in `prisma migrate`. Therefore we error when a migration against MySQL 5.6 uses the `Json` data type.

**Comment by jwld** [comment]
Does this feature support saving arrays as JSON? e.g.
```
const newService = await prisma.service.create({
  data: { formula: [{ test: 'test' }] }
})
```

Made a full issue [here](https://github.com/prisma/prisma/issues/2432) for reference.

**Comment by thesunny** [comment]
@mavilein 

Thank you for the summary!

Should the field type be returned as a JSON object as opposed to a JavaScript `object`. This would be more accurate.

For example, my API type checks that the return values for an API method are valid JSON objects and returning an `object` would fail that test.

This is maybe not 100% a proper JSON value type (I'm unsure about `undefined`) but as a starting point:

```ts
export type JSONValue =
  | string
  | number
  | boolean
  | null
  | undefined
  | JSONArray
  | JSONObject

export type JSONArray = Array<JSONValue>

export type JSONObject = {
  [key: string]: JSONValue
}
```

If you think this is worthwhile, I will open a separate issue for it.

**Comment by pantharshit00** [comment]
@thesunny Can you please open an issue about this on the client repository(https://github.com/prisma/prisma-client-js)?

The typescript typing is unrelated to the engines implementation so it is better to track this separately. Also, better typing suggestions are always welcomed :)

**Comment by gustawdaniel** [comment]
How about JSON support in prisma v2?

**Comment by janpio** [comment]
@gustawdaniel Was added back in beta.4 already: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.4 So can be used now of course!

**Comment by gustawdaniel** [comment]
Thanks @janpio 

So I have rather problem with `nexus graphql framework` than with `prisma`, because of my version is `2.1.3`.

https://stackoverflow.com/questions/62730081/how-to-use-json-type-in-prisma-graphql-nexus-framework
