### ISSUE TITLE
Migration is always detected for @dbgenerated field

### ISSUE THREAD

**Issue by SlavenGrowy** [prisma/prisma#18610]
### Bug description

I have tried adding [a nanoid postgres function](https://github.com/viascom/nanoid-postgres) to my database via updating my `schema.prisma`, running `prisma migrate dev --create-only` ,updating the migration manually and then running `prisma migrate dev`. Which should apply the manually updated migration and stop. Instead it applies the migration and detects a new change. So if I run `prisma migrate dev`(without touching `schema.prisma`) any number of times a new migration gets detected every time.

### How to reproduce

I have created a repo with a dockerised Postgres instance to easily replicate the issue:

1. Clone repo https://github.com/SlavenGrowy/prisma-migrate-dbgenerated-bug
2. `npm i`
3.  `docker-compose up -d` to setup the database
4.  `prisma migrate dev` to apply the already created migration

And now you can run `prisma migrate dev` or `prisma migrate dev --create-only` as many times as you wish and every time it will detect a change and prompt you to give the new migration a name.

### Expected behavior

Prisma should not detect a migration.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Component {
  id String @id @unique @default(dbgenerated("nanoid(10,'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_-')"))
}

```

### Environment & setup

- OS: macOS
- Database:PostgreSQL
- Node.js version: 16.15.0

### Prisma Version

```
prisma                  : 4.12.0
@prisma/client          : 4.12.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at ../../../../.nvm/versions/node/v16.15.0/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at ../../../../.nvm/versions/node/v16.15.0/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.12.0-67.659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Default Engines Hash    : 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Studio                  : 0.483.0
```

**Comment by janpio** [comment]
> So if I run `prisma migrate dev`(without touching `schema.prisma`) any number of times a new migration gets detected every time.

What is the content of the migration that is generated each time?
What happens when you run `db pull` instead of `migrate dev` again?

**Comment by SlavenGrowy** [comment]
> > So if I run `prisma migrate dev`(without touching `schema.prisma`) any number of times a new migration gets detected every time.
> 
> What is the content of the migration that is generated each time? What happens when you run `db pull` instead of `migrate dev` again?

The content of the migration generated each time is the same:
```sql
-- AlterTable
ALTER TABLE "Component" ALTER COLUMN "id" SET DEFAULT nanoid(10,'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_-');
```

And if i run `db pull` the contents of `schema.prisma` gets updated from this:
```prisma
model Component {
id String @id @unique @default(dbgenerated("nanoid(10,'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_-')"))
}
```
To this:
```prisma
model Component {
  id String @id @unique @default(dbgenerated("nanoid(10, '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_-'::text)"))
}
```
Which seems to fix the issue. It doesn't detect new changes on `prisma migrate dev` .Thats weird. Do you have an idea why it didn't work without casting it to text?

**Comment by janpio** [comment]
Our diffing logic gets back the `...::text` and does not recognize that this is the same as without - hence tries to change it over and over to the version without.

**Comment by SlavenGrowy** [comment]
I see, after more searching in your docs, I saw that this is a known [issue](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#dbgenerated)
<img width="681" alt="Screenshot 2023-04-04 at 10 46 59" src="https://user-images.githubusercontent.com/104974346/229724231-1c984d2c-982e-497a-bc38-6bd2916fc2b3.png">

Thank you for the quick response! I will close the ticket.
