### ISSUE TITLE
Db pull not generating defaults or including unique field names

### ISSUE THREAD

**Issue by richardryangarcia** [prisma/prisma#18627]
### Bug description

When writing a schema.prisma file my table includes a default value and a unique field (combination of two fields). I run migrate and db is updated successfully. When I go to another project to db pull any updates, the pull runs successfully but it does not include the default value for the field and additionally does not include the unique field name even though it was defined in the original schema file. 

### How to reproduce

For default issue
1. create schema.prisma file 
2. define a table with default value some thing like `id String @default(uuid()) @id`
3. run migrate to update your db
4. go to a different repo set up to pull this schema and run `prisma db pull`
5. review changes to schema file. youll see the new table is pulled with all the correct column types but the default is not included. it shows up like `id String @id`

For unique field issue
1. create schema.prisma file 
2. define a table with unique value some thing like `@@unique([chainId, address], name: "chainIdAddress")`
3. run migrate to update your db
4. go to a different repo set up to pull this schema and run `prisma db pull`
5. review changes to schema file. youll see the new table is pulled with all the correct column types but the unique value name is not included. it shows up like `@@unique([chainId, address])`

### Expected behavior

I would expect the default values to be generated as well as the unique field's name. 

### Prisma information

Below is an example of a table schema that would be pull inconsistently using db pull 
```prisma
model Contract {
  id String @default(uuid()) @id
  createdAt DateTime @default(now())
  name String? 
  address String 
  factory Boolean
  tokenIds String[]
  chainId String
  @@unique([chainId, address], name: "chainIdAddress")
}
```

### Environment & setup

- OS: MacOS 12
- Database: PostgreSQL
- Node.js version: v18.14.2

### Prisma Version

```
4.11
```

**Comment by janpio** [comment]
Unfortunately that is currently how it is supposed to work:

- `uuid()` is a Prisma side default, it is not represented in the database and hence can not be introspected back. If you want to use a database side function, you need to use `@default(dbgenerated("..."))`.
- Similar for the name of an `@@unique` - that is only a value that is used in Prisma itself and is also not reflected in the database - so it can not be introspected back.

When you have the original issue around and run `db pull` it will keep both pieces around, as we understand that they are not reflected in the database and will not come back via Introspection. If you just introspect a migrated database with no schema file - nothing we can do right now.
