### ISSUE TITLE
PrismaPromise doesn't have prototype chain with Promise. #18632

### ISSUE THREAD

**Issue by industriously** [prisma/prisma#18664]
### Bug description

PrismaPromise interface extends Promise interface.

but PrismaPromise object (created by createPrismaPromise function) is not extended Promise.

So, I thought that PrismaPromise needs to form a prototype chain with Promise.

this is my solution. #18632

```typescript
// const a:PrismaPromise = ... ;
// before
a instanceof Promise // false
// after
a instanceof Promise // true
```

### How to reproduce

```typescript
const client = new PrismaClient();

const promise = client.user.findMany();

if(promise instanceof Promise) console.log("promise is Promise");
else console.log("promise is not Promise");
```

### Expected behavior

logged: "promise is Promise"

(but now prisma version, logged "promise is not Promise")

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: MySql
- Node.js version: 18

### Prisma Version

```
4.1.2
```

**Comment by janpio** [comment]
Does this help as explanation how Prisma uses a special "thenable" instead of a normal Promise?
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#prismapromise-behavior

**Comment by industriously** [comment]
oh i see, thenable is lazy query excutation!! right?

**Comment by janpio** [comment]
Yes, pretty much. We need it for our transaction feature: https://www.prisma.io/docs/concepts/components/prisma-client/transactions#sequential-prisma-client-operations Those are only "started" together inside a transaction.

**Comment by industriously** [comment]
thank you very much!

**Comment by ScreamZ** [comment]
@janpio could this https://www.prisma.io/docs/orm/reference/prisma-client-reference#prismapromise-behavior cause issue with react 19 `use` ?

**Comment by fanismahmalat** [comment]
New to prisma here. How can I do subsequent queries using the returned value of a model's `findFirst`?
