### ISSUE TITLE
Error with nullable relation in the `is` and `isNot` clauses

### ISSUE THREAD

**Issue by Zenoo** [prisma/prisma#18670]
### Bug description

There is a type generation error when you have multiple models referencing another model, one with a nullable relation, one without.
The relation becomes non nullable for all.

We can't use `where: { xxx: { isNot: null } }` anymore.

![image](https://user-images.githubusercontent.com/7151485/230720290-7b483144-1346-4968-a62c-2644c5557117.png)

### How to reproduce

I made a minimal reproducible example here: https://github.com/Zenoo/prisma-null-bug

### Expected behavior

We should still be able to use null in those clauses.

### Prisma information

```prisma
model User {
  id   String @unique @db.Uuid
  name String @unique @db.VarChar(255)
  foos Foo[]
  bars Bar[]
}

model Foo {
  id     Int     @id @default(autoincrement())
  name   String  @db.VarChar(255)
  user   User?   @relation(fields: [userId], references: [id])
  userId String? @db.Uuid
  bars   Bar[]
}

model Bar {
  id     Int     @id @default(autoincrement())
  name   String  @db.VarChar(255)
  foo    Foo?    @relation(fields: [fooId], references: [id])
  fooId  Int?
  user   User   @relation(fields: [userId], references: [id])
  userId String @db.Uuid
}
```

```ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const foosWithoutUser = await prisma.foo.findMany({
    where: {
      user: { isNot: null }, // Error here
    },
  });

  console.log(foosWithoutUser);
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v16.13.1

### Prisma Version

```
4.12.0
```

**Comment by Weakky** [comment]
Hey @Zenoo, this bug is no longer reproducible with the latest Prisma version. We're closing it now. Thanks for reporting.
