### ISSUE TITLE
All npx prisma CLI commands fail

### ISSUE THREAD

**Issue by frankolson** [prisma/prisma#18677]
### Bug description

Any `npx prisma` command I run results in the following error message:

```
npx prisma generate
node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/will/Documents/projects/plating-ai/node_modules/prisma/build/prisma_fmt_build_bg.wasm'
    at Object.openSync (node:fs:591:3)
    at Object.readFileSync (node:fs:459:35)
    at ../../node_modules/.pnpm/@prisma+prisma-fmt-wasm@4.12.0-67.659ef412370fa3b41cd7bf6e94587c1dfb7f67e7/node_modules/@prisma/prisma-fmt-wasm/src/prisma_fmt_build.js (/Users/will/Documents/projects/plating-ai/node_modules/prisma/build/index.js:12449:31)
    at __require (/Users/will/Documents/projects/plating-ai/node_modules/prisma/build/index.js:14:50)
    at Object.<anonymous> (/Users/will/Documents/projects/plating-ai/node_modules/prisma/build/index.js:91437:38)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/will/Documents/projects/plating-ai/node_modules/prisma/build/prisma_fmt_build_bg.wasm'
}

Node.js v18.2.0
```

I saw [this comment](https://github.com/prisma/prisma/issues/15881#issuecomment-1287204196) and found that there is indeed no `node_modules/prisma/build/prisma_fmt_build_bg.wasm` next to `node_modules/prisma/build/index.js`.

What I have tried so far to try and resolve the bug:
1. Uninstall and reinstall `prisma` and `@prisma/client` npm packages
2. `npm i`
3. use `node node_modules/prisma/build/index.js migrate deploy` instead of `npx prisma migrate deploy`, [recommendation source](https://github.com/prisma/prisma/issues/15881#issuecomment-1289420222)

None of that has worked so far and this issue just seemingly randomly popped up yesterday. Please help, I can make any modifications to my database!

### How to reproduce

1. Run any `npx prisma` CLI command

### Prisma information

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id                  String    @default(cuid()) @id
  email               String    @unique
  emailVerified       DateTime?
  isAdmin             Boolean   @default(false)
  accounts            Account[]
  sessions            Session[]
  images              Image[]
  recipes             Recipe[]
  conversations       Conversation[]
  stripeCustomerId    String?   @unique
  stripeSubscribedAt  DateTime?
  isActive            Boolean   @default(false)
  createdAt           DateTime  @default(now()) @map(name: "created_at")
  updatedAt           DateTime  @updatedAt @map(name: "updated_at")
  @@map(name: "users")
}

model Account {
  id                 String   @id @default(cuid())
  userId             String
  type               String
  provider           String
  providerAccountId  String
  refresh_token      String?  @db.Text
  access_token       String?  @db.Text
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String?  @db.Text
  session_state      String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

model Image {
  id          String    @default(cuid()) @id
  imageKey    String
  description String?
  style       String?
  owner       User      @relation(fields: [ownerId], references: [id])
  ownerId     String
  recipe      Recipe?   @relation(fields: [recipeId], references: [id])
  recipeId    String?
  isPublic    Boolean   @default(false)
  createdAt   DateTime  @default(now()) @map(name: "created_at")
  updatedAt   DateTime  @updatedAt @map(name: "updated_at")
}

model Recipe {
  id            String    @default(cuid()) @id
  owner         User      @relation(fields: [ownerId], references: [id])
  ownerId       String
  name          String
  time          String
  difficulty    String
  tools         String[]
  ingredients   String[]
  instructions  String[]
  isPublic      Boolean   @default(false)
  images        Image[]
  createdAt     DateTime  @default(now()) @map(name: "created_at")
  updatedAt     DateTime  @updatedAt @map(name: "updated_at")
}

model Conversation {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  owner     User     @relation(fields: [ownerId], references: [id])
  ownerId   String
  messages  Message[]
  title     String
}

model Message {
  id              String   @default(cuid()) @id
  createdAt       DateTime @default(now())
  updatedAt       DateTime @updatedAt
  conversation    Conversation @relation(fields: [conversationId], references: [id])
  conversationId  String
  role            String
  text            String
}

### Environment & setup

- OS: macOS Monterey
- Database: PostgreSQL 12.14
- Node.js version: 18.2.0

### Prisma Version

```json
{
  "devDependencies": {
    "prisma": "^4.12.0"
  }
}
```

`npx prisma -v` commands are not working, so I retrieved the information from my package.json file.

**Comment by frankolson** [comment]
**Update**
I created a nextjs test project and added prisma as outlined in this tutorial: https://vercel.com/guides/nextjs-prisma-postgres. Result: no issues.

Maybe something uninstalling/reinstall prisma in the original project didn't actually clear and reinstall the node_module files 🤔

**Comment by frankolson** [comment]
I now have it working. After uninstalling/reinstalling `@next-auth/prisma-adapter` as well as `prisma` and `@prisma/client`, `npx prisma` CLI commands are now working again.

My best guess is that some weird stuff was going on in the dependency management coordination between those semi-related packages 🤷

**Comment by imWildCat** [comment]
found the reason of my case:

```diff
- ENV NODE_OPTIONS='-r @newrelic/next'
```

this new relic option must be removed before running prisma

**Comment by KrishnaGupta0405** [comment]
in my case deleting the generated, node_modules, prisma folder and then 
npm uninstall -g prisma          -> to delete prisma from global if installed
npm cache clean --force          -> to make a fresh start
npm i prisma                           -> made everything worked properly

One more thing, just before this error i got stuck at another error, were if i run prisma cli like `npx prisma init` no error and no successs message was shown, after 2 hours of debugging, i found that somehow all my project were saved inside the opendrive (windows), that were the problems were coming, so simple remove the project to normal c drive, and yeah everything worked properly....
