### ISSUE TITLE
Introspect `on change` directive to `@updatedAt`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1868]
...

**Comment by do4gr** [comment]
Our current thinking is to clearly split Prisma level and db level features. In this case we see @updatedAt as a Prisma level feature that is available across all databases and which does not get written to DDL. We also already followed this logic when working on re-introspection. 

The DDL level `on change`  would be detected as a db level feature and therefore stay in `@default` . Currently as `dbgenerated()` maybe later as a description of the actual statement in DDL.

Separating these two concepts will make it clearer for migrate and introspect to decide what happened when encountering changes in the schema / the db.
