### ISSUE TITLE
, 

### ISSUE THREAD

**Issue by devinjelliot** [prisma/prisma#18681]
Hi Prisma Team! The following command just crashed.

## Command

`migrate dev`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v18.15.0           | 
| Prisma CLI  | 4.12.0             | 
| Engine      | 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7| 

## Error
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_destructive_change_checker.rs:199:84] internal error: entered unreachable code

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by jkomyno** [comment]
Hi! Closing this as a duplicate, please refer to [this comment](https://github.com/prisma/prisma/issues/18682#issuecomment-1501629633).
