### ISSUE TITLE
Error I Need The Help

### ISSUE THREAD

**Issue by ElsayedRapaa** [prisma/prisma#18686]
Hi Prisma Team! The following command just crashed.

## Command

`db pull --force`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.15.0           | 
| Prisma CLI  | 4.12.0             | 
| Engine      | 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7| 

## Error
```
Error: Error in migration engine.
Reason: 

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by Weakky** [comment]
Hey @ElsayedRapaa,

Could you provide more information so that we could reproduce your issue? The Prisma Schema you're using would be a good start.

**Comment by jharrell** [comment]
Hi! 

Without further info we'll have to close this issue. If you have the same issue, please leave a comment or open a new issue. Thank you!
