### ISSUE TITLE
db pull error

### ISSUE THREAD

**Issue by pabl-o-ce** [prisma/prisma#18680]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v19.8.1            | 
| Prisma CLI  | 4.12.0             | 
| Engine      | 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7| 

## Error
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/mssql.rs:348:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `create default [dbo].[UW_ZeroDefault] as 0\r\n\r\n\r\n\r\n\r\n\r\n`"

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by Weakky** [comment]
Hey @pabl-o-ce,

Would you mind sharing a minimal Prisma Schema so that we can reproduce this panic?

Thank you!

**Comment by pabl-o-ce** [comment]
Hi @Weakky 
Let me tell you a little more about this issue:
- Using a large DB in SQL Server
- my prisma schema is:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}
```
The thing is that (correct me if I'm wrong) with `npx prisma db pull` get create the `model` in `schema.prisma` of a existent `db`.

That is how I get this error.

Because I don't want to create it manually de `model` in `schema.prisma`

Is there is other way to achieve this you can guide me. I'm very welcome receive feedback :)

**Comment by janpio** [comment]
Can you share the SQL that defines the table around `[dbo].[UW_ZeroDefault]`? That seems to be the thing causing the error right now.

**Comment by pabl-o-ce** [comment]
Hello @janpio 

Sorry for the late response I create manually because I need to finish a project.

Now I'm reviewing the problem.

Oh I check it `UW_ZeroDefault` is a default type that can have a field... mmm I would need to check every field on the tables who has this and remove it to make it work?

**Comment by pabl-o-ce** [comment]
Thanks @janpio @Weakky 

Love prisma ❤️‍🔥

The problem was resolved

I remove this old mssql type `UW_ZeroDefault` and works.

**Comment by Santis636** [comment]
Hello, how did you remove UW_ZeroDefault?
