### ISSUE TITLE
Support Linux Gentoo

### ISSUE THREAD

**Issue by Norbiros** [prisma/prisma#18698]
## Problem

Prisma works correctly, but I get this warning:
```
Prisma doesn't know which engines to download for the Linux distro "gentoo". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
```
## Suggested solution

Add [Gentoo](https://www.gentoo.org/) to list of supported distros

## Additional context
![Screenshot from 2023-04-11 10-37-43](https://user-images.githubusercontent.com/89837724/231103963-bdd8ce14-e04f-406f-925a-4649c0b683b6.png)

**Comment by chrismurtagh** [comment]
Same here with prisma 4.14.1

**Comment by systemadmax** [comment]
the probleme still exist in 4.15.0

**Comment by timovolkmer** [comment]
Same here. Prisma 4.16.0 works with gentoo.

**Comment by Baconing** [comment]
prisma 5.0.0 aswell

**Comment by eugenmihailescu** [comment]
Same here. Prisma 5.10.2 works in my Gentoo Linux 2.14.

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
