### ISSUE TITLE
Stop ignoring and suggesting to ignore generated code in version control

### ISSUE THREAD

**Issue by bnoctis** [prisma/prisma#18726]
### Bug description

Quote, `010-generating-prisma-client.mdx`, [at the time of writing this](https://github.com/prisma/docs/blob/d656c659bec29a2fbf60dc6d8abe472242f8054d/content/200-concepts/100-components/02-prisma-client/000-working-with-prismaclient/010-generating-prisma-client.mdx):

> #### Keeping the query engine out of version control by default
>
> Prisma Client uses a [_query engine_](/concepts/components/prisma-engines/query-engine) to run queries against the database. This query engine is downloaded when `prisma generate` is invoked and stored in the `output` path together with the generated Client.
>
> By generating Prisma Client into `node_modules`, the query engine is usually kept out of version control by default since `node_modules` is typically ignored for version control.
When using a custom `output` path for the generated Prisma Client, it is advised to exclude it from your version control. For Git, this means adding the `output` path to your `.gitignore` file.

The industry's standard practice is to lock down dependencies with their versions and checksums in lock files and to check in everything including the lock files in source control, to make sure what is running in production is what we saw in development. Sometimes people generate code. They call that codegen and treat generated code as an integral part of the codebase.

Now you suggest *_ignoring_* generated code. Are you that confident of your code quality and security and supply chain security that you think neither bug nor compromise would happen to you or users? Then you were wrong. It's definitely possible, if not easy, to make the codegen, quote, "download", a malicious version of the "query engine".

And then you have a _"query engine"_. That means Prisma connects _directly_ to users' databases. A single line of code gone haywire can wipe an entire database clean.

Learn how others, including Google who built protobuf, do this. Put the damn code along with users' and let them check it in.

### How to reproduce

It's in the code and doc.

### Prisma information

Irrelevant.

### Environment & setup

Every.

### Prisma Version

Current and maybe quite some previous versions.

**Comment by janpio** [comment]
> Put the damn code along with users' and let them check it in.

We let you check it in. You are quoting words from our documentation that give _advice_ not to do it. You can - and should - do whatever you find the correct solution for your use case.

If you consider this advice unacceptable, maybe Prisma is not for you.
If you want to suggest we change it, the repository for our documentation is at https://github.com/prisma/docs, I see you found the exact file that contains this information already so you might also submit a Pull Request if you want.
