### ISSUE TITLE
Semver checks for yarn and typescript could potentially fail

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#18751]
### Bug description

As pointed out in this [review comment](https://github.com/prisma/prisma/pull/18646#discussion_r1166402270), we are comparing semver numbers from strings and not as numbers, which could cause unexpected results.

The goals is to make these numbers instead of string and add a unit test. Also for `yarn`, I propose to check if `engines` can be a reliable replacement in the `package.json` instead of a runtime check. Similarly, `typescript` could be an optional peer dependency instead.

### How to reproduce

Write a unit test with a semver string that will cause a wrong comparison.

### Expected behavior

Semver parts should be compared as numbers, not strings.

### Prisma information

n/a

### Environment & setup

- n/a

### Prisma Version

```
dev
```

**Comment by icanipa** [comment]
@quest-bot embark
