### ISSUE TITLE
The prisma metrics `prisma_pool_connections_open` has a bug where it goes negative

### ISSUE THREAD

**Issue by Raynos** [prisma/prisma#18761]
### Bug description

![image](https://user-images.githubusercontent.com/479538/232225565-da67d594-8e3b-4fff-9737-a27cbabdcb23.png)

### How to reproduce

Turn on prisma metrics preview

### Prisma information

Turn on prisma metrics preview

### Environment & setup

- OS: Linux
- Database: postgres
- Node.js version: 16

### Prisma Version

```
4.9
```

**Comment by ebaer-payix** [comment]
BTW, this is also happening with MySQL.
Any status on this ?

**Comment by Raynos** [comment]
I'm pretty sure all the experimental metrics are buggy / unmaintaned.

**Comment by Arbaaz27** [comment]
Facing this as well

**Comment by neilmtan** [comment]
Seeing this also!

**Comment by Raynos** [comment]
The whole metrics feature is unmaintained because it's experimental; see https://github.com/prisma/prisma/issues/18760

**Comment by alencardc** [comment]
I took some time this weekend to investigate this issue and discovered that the problem is on the mobc library used by the Prisma Engine to manage the connection pool. I opened this PR importcjj/mobc#74 that should fix issues #18760 and #18761.

**Comment by janpio** [comment]
PR is merged at mobc (thanks @garrensmith!), so now it's our turn.

**Comment by Jolg42** [comment]
Closing this because https://github.com/prisma/prisma-engines/pull/4193 was merged

**Comment by Raynos** [comment]
Which new version of prisma will have this fix in and how long do we have to wait :D
