### ISSUE TITLE
Prisma crashes with GraphQL queries of nested one-to-many relationship

### ISSUE THREAD

**Issue by MEnnabah** [prisma/prisma#18787]
### Bug description

Hi there

We are experiencing a crash when triggering a GraphQL nested query with many-to-many database tables. We have demonstrated the crash only is triggered when:

- It's a nested query, and
- It's a one-to-many relationship, and
- It uses `findFirst`, `findUnique` or `$transaction`.

Note: Using `findUnique` doesn't crash the app, but this can't be used because it a one-to-many relationship.

The app is built with Nest.js and uses Apollo GraphQL driver.
The app also uses Postgres, and it crashes silently. The only reason we know it crashes because of a log from Postgres:
`LOG:  could not receive data from client: Connection reset by peer`

We have tried to `export DEBUG="*"` to watch out for help logs. However, the last log before the app crashes is:
`prisma:client:libraryEngine  sending request, this.libraryStarted: true`

This bug report contains a standalone repository with reproducing steps documented in README.md file. [The repo can be found here](https://github.com/MEnnabah/nested-queries-prisma).

### How to reproduce

1. Clone the standalone reproduction repo (it uses Docker for the app and the database).
2. `yarn install`
3. Run `docker compose up`, and wait for the app to run by observing the logs.
4. Now you need to run the migration file within the container, that will also seed the database with data. Run `docker exec -it main /bin/sh` to get a container shell.
5. Run the migration file: `npx prisma migrate dev`.

The app is now running on `http:localhost:8080` with data in the database. We need to query these data to trigger the bug.

1. Open `http:localhost:8080/graphql` and run the following query:
```graphql
query {
  cat(id: 1) {
    name
    age
    legs {
      color
      claws {
        length
      }
    }
  }
}
```

The query has a one-to-many relationship in the `legs` and `claws` part.

Now to confirm this only happens when the query uses any of the previously mentioned methods, open `src/claws/claws.service.ts` and try the methods that are commented at the bottom of the file.

Make sure the app was hot reloaded by observing Docker logs, once hot reloaded, trigger the same query again. Works fine!

### Expected behavior

The query doesn't crash Prisma.

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl-arm64-openssl-3.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Cat {
  id   Int    @id @default(autoincrement())
  name String
  age  Int

  owner   Owner? @relation(fields: [ownerId], references: [id])
  ownerId Int?

  legs Leg[]
}

model Leg {
  id    Int    @id @default(autoincrement())
  color String

  cat   Cat? @relation(fields: [catId], references: [id])
  catId Int?

  claws Claw[]
}

model Claw {
  id     Int    @id @default(autoincrement())
  length String

  leg   Leg? @relation(fields: [legId], references: [id])
  legId Int?
}

model Owner {
  id   Int    @id @default(autoincrement())
  name String

  Cat   Cat[]
  House House[]
}

model House {
  id      Int    @id @default(autoincrement())
  address String

  owner   Owner? @relation(fields: [ownerId], references: [id])
  ownerId Int?
}
```

### Environment & setup

- OS: macOS, with Docker
- Database: PostgreSQL
- Node.js version: v19.9.0

### Prisma Version

```
prisma                  : 4.12.0
@prisma/client          : 4.12.0
Current platform        : linux-musl-arm64-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at node_modules/@prisma/engines/libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at node_modules/@prisma/engines/migration-engine-linux-musl-arm64-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.12.0-67.659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Default Engines Hash    : 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Studio                  : 0.483.0
```

### Revisions 

Edit 1: The app crashes only when querying a nested one-to-many relations.
Edit 2: I have updated the reproduction repo to include a more concrete example.
Edit 3: Title update to mention "one-to-many relationship", and add a description of the relationship in the query.

**Comment by MEnnabah** [comment]
I have generated a full log when this happens:

```text
2023-04-17T17:16:39.729Z prisma:client  Prisma Client call:
2023-04-17T17:16:39.730Z prisma:client  prisma.cat.findUnique({
  where: {
    id: 1
  }
})
2023-04-17T17:16:39.730Z prisma:client  Generated request:
2023-04-17T17:16:39.731Z prisma:client  query {
  findUniqueCat(where: {
    id: 1
  }) {
    id
    name
    age
    parentId
  }
}
2023-04-17T17:16:39.731Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
2023-04-17T17:16:39.736Z prisma:client  Prisma Client call:
2023-04-17T17:16:39.736Z prisma:client  prisma.cat.findMany({
  where: {
    parentId: 1
  }
})
2023-04-17T17:16:39.736Z prisma:client  Generated request:
2023-04-17T17:16:39.736Z prisma:client  query {
  findManyCat(where: {
    parentId: 1
  }) {
    id
    name
    age
    parentId
  }
}
2023-04-17T17:16:39.737Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
2023-04-17T17:16:39.739Z prisma:client  Prisma Client call:
2023-04-17T17:16:39.739Z prisma:client  prisma.cat.findMany({
  where: {
    parentId: 2
  }
})
2023-04-17T17:16:39.739Z prisma:client  Generated request:
2023-04-17T17:16:39.739Z prisma:client  query {
  findManyCat(where: {
    parentId: 2
  }) {
    id
    name
    age
    parentId
  }
}
2023-04-17T17:16:39.739Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
2023-04-17T17:16:39.740Z prisma:client  Prisma Client call:
2023-04-17T17:16:39.740Z prisma:client  prisma.cat.findMany({
  where: {
    parentId: 3
  }
})
2023-04-17T17:16:39.740Z prisma:client  Generated request:
2023-04-17T17:16:39.740Z prisma:client  query {
  findManyCat(where: {
    parentId: 3
  }) {
    id
    name
    age
    parentId
  }
}
2023-04-17T17:16:39.740Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
2023-04-17T17:16:39.740Z prisma:client  Prisma Client call:
2023-04-17T17:16:39.740Z prisma:client  prisma.cat.findMany({
  where: {
    parentId: 4
  }
})
2023-04-17T17:16:39.740Z prisma:client  Generated request:
2023-04-17T17:16:39.740Z prisma:client  query {
  findManyCat(where: {
    parentId: 4
  }) {
    id
    name
    age
    parentId
  }
}
2023-04-17T17:16:39.740Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
```

**Comment by MEnnabah** [comment]
I think I need to articulate myself better here to be specific when the crash happens. I'll use the following gql schema to demonstrate:

```gql
type Cat {
  id: ID!
  name: String!
  age: Int!
  
  owner: Owner!
  legs: [Leg!]!
}

type Owner {
  id: ID!
  name: String!
  houses: [House!]!
}

type House {
  id: ID!
  address: String!
  ownerId: Int!
}

type Leg {
  id: ID!
  color: String!
  catId: Int!
  claws: [Claw!]!
}

type Claw {
  id: ID!
  length: String!
  legId: Int!
}

type Query {
  cat(id: Int!): Cat!
  ownerById(id: Int!): Owner!
  house(id: Int!): House!
}
```

The query path `cat.owner.houses` has a one-to-many relationship between `owner` and `houses`. However, if you use `findFirst`, `findUnique` or `$transaction` it will NOT crash.

The query path `cat.legs.claws` has a relationship between `legs` and `claws`. Prisma crashes when `legs` is an array, and each one has an array of `claws`.

This is still a one-to-many relationship, but the "one" part of the relationship is part of an array, and this is the exact trigger of the crash. The minimal reproduction repo has this implemented for anyone to take a look. 

I hope I saved you time to hunt this one down!

**Comment by MEnnabah** [comment]
Thanks Jan for taking a look into this issue.

> As you know Prisma itself does not support GraphQL.

The way we use Prisma is when we receive a GraphQL query, each path of the query gets executed against our database using Prisma.

I totally understand Prisma is a generic ORM, and we don't expect Prisma to support GraphQL natively.

> Look inefficient, but in no way broken.

Would this be an issue, running multiple inefficient requests asynchronously in the same connection, at the same time?

If you look at the reproduction repo, [specifically this file (src/claws/claws.service.ts)](https://github.com/MEnnabah/nested-queries-prisma/blob/main/src/claws/claws.service.ts), it's very weird that Prisma crashes if we use `findMany`, `findFirst`, or `$transaction`. But if we used `findUnique` it works just fine, even though `findUnique` was triggered by a GraphQL query!

> Can you reproduce the issue with just the Prisma Client queries that your GraphQL library generates and executes?

I guess this can be done by simply translating the queries listed in [#18787 (comment)](https://github.com/prisma/prisma/issues/18787#issuecomment-1511776432) into a Prisma Client API and executing them all at once. Some of these would run in parallel, but others would have to wait for dependencies. Is that right? If yes, I'll give it a shot.

But I'm hoping someone from Prisma team could run the reproduction repo and comment/uncomment the methods in [src/claws/claws.service.ts](https://github.com/MEnnabah/nested-queries-prisma/blob/main/src/claws/claws.service.ts) to get a feeling of the issue. The project is in Docker, no external dependencies needed :)

**Comment by janpio** [comment]
We are unfortunately pretty much at capacity regarding reproductions with user apps that have more than just Prisma Client queries, which is why I by default now always ask for reproductions _without_ too much around the usage of Prisma Client. Often, while producing these, you, our users, already find out waht might or is going wrong and we can start with much better information.

> Would this be an issue, running multiple inefficient requests asynchronously in the same connection, at the same time?

Running multiple queries in parallel should not be a problem - and definitely not result in it just silently dying.
Do you understand how your library or code runs things "in parallel"?

> Is that right? If yes, I'll give it a shot.

Yes exactly. Reproduce the Prisma Client queries as your app sends them, but with less of your app around it that could influence what is happening.

**Comment by MEnnabah** [comment]
That makes lots of sense. I'll definitely give it a shot and post the updates here.

> Do you understand how your library or code runs things "in parallel"?

What I meant by "in parallel" is from a single GraphQL query. For example, if the query says:

```gql
query {
  cat(id: 1) {
    name
    age
    owner {
      name
    }
    legs {
      color
      claws {
        length
      }
    }
  }
}
```

The database queries is
at t=0, `cat` is queried.
at t=1, both `owner` and `legs` are queried.
at t=2, for each item in `legs`, `claws` is queried.

This is how our code basically runs things when it received a request.

**Comment by MEnnabah** [comment]
We spent the day trying to hunt this one down. Eventually we enabled Postgres logs, triggered the query mentioned in previous comment, and saw only these:

```log
2023-04-19 16:31:22.196 UTC [30] LOG:  statement: SELECT 1;
2023-04-19 16:31:25.429 UTC [46] LOG:  statement: SELECT 1
2023-04-19 16:31:25.429 UTC [46] LOG:  execute s0: SELECT "public"."Cat"."id", "public"."Cat"."name", "public"."Cat"."age", "public"."Cat"."ownerId" FROM "public"."Cat" WHERE ("public"."Cat"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
2023-04-19 16:31:25.429 UTC [46] DETAIL:  parameters: $1 = '1', $2 = '1', $3 = '0'
2023-04-19 16:31:25.436 UTC [49] LOG:  statement: SELECT 1
2023-04-19 16:31:25.440 UTC [49] LOG:  execute s3: SELECT "public"."Leg"."id", "public"."Leg"."color", "public"."Leg"."catId" FROM "public"."Leg" WHERE "public"."Leg"."catId" = $1 OFFSET $2
2023-04-19 16:31:25.440 UTC [49] DETAIL:  parameters: $1 = '1', $2 = '0'
2023-04-19 16:31:25.451 UTC [50] LOG:  statement: SELECT 1
2023-04-19 16:31:25.465 UTC [50] LOG:  could not receive data from client: Connection reset by peer
```

As you can see, not all of queries are received by the database.

We later have identified a potential root cause. Using `node:alpine` based docker image triggers the issue. We switched to `node:18` and this works for us for now. This probably is better if it goes to Prisma docs, as this wasn't the first issue trying to find the ideal docker image.

I'll monitor the behaviour in the next few days, and post an update here again.
If you're interested in closing this issue, please do. Otherwise, I'll post an update in and close it.

**Comment by janpio** [comment]
> Using `node:alpine` based docker image triggers the issue.

It shouldn't generally, hence there is nothing to document. We should understand what is going on and hopefully fix it.

**Comment by jdtzmn** [comment]
I'm still troubleshooting so I cannot say for certain that I'm experiencing the same issue, but I am seeing similar random inexplicable random crashing with my GraphQL in Docker application that uses `prisma.findMany` and from my preliminary debugging it appears to happen immediately after the `prisma:client:libraryEngine  sending request, this.libraryStarted: true` code.

I should have some additional information soon. Unfortunately, using `node:18` did not solve the issue in my case.

**Comment by MEnnabah** [comment]
> Unfortunately, using node:18 did not solve the issue in my case.
I'm actually not sure why it works for us. janpio mentioned that it shouldn't be the case, but for some reason it worked for us, and because we were trying to reduce our image size, when we tried `node:20-alpine3.17` it worked too.

While it might be unrelated, our binary targets are defined as the following if you want to try it with that `node:20-alpine3.17`
```
binaryTargets   = ["native", "linux-musl-openssl-3.0.x", "debian-openssl-1.1.x", "linux-musl-arm64-openssl-3.0.x", "linux-arm64-openssl-3.0.x"]
```

**Comment by MEnnabah** [comment]
Looking at #18510, I think it's possible the issue is related under the condition that the platforms are `linux-musl-arm64-openssl-3.0.x`. I understand that this issue doesn't mention `Segmentation fault (core dumped)`, but the underlying issue might be related.

**Comment by MEnnabah** [comment]
Possibly fixed by: https://github.com/prisma/engine-images/pull/75

**Comment by aqrln** [comment]
@MEnnabah yep, I can reproduce this issue using your repo, but everything works with `5.3.0-integration-arm-openssl-5-2-0.1`: 

<img width="1240" alt="image" src="https://github.com/prisma/prisma/assets/4923335/8cb90efe-4fb6-4c44-acb7-db769fcf394e">

Can you confirm it on your side as well?

(fyi: you're using the deprecated `beforeExit` event which was removed in Prisma 5, and I just removed the whole custom `enableShutdownHooks` method from your `PrismaService` as it was just dead code that did nothing as it has no special meaning for NestJS and you didn't call it yourself in the application root, however if you were to actually enable the shutdown hooks in NestJS, there's no need for any special integration with Prisma, you can just use built-in `app.enableShutdownHooks()`)

**Comment by MEnnabah** [comment]
@aqrln just tested with `5.3.0-integration-arm-openssl-5-2-0.1` and it works too - on I'm on M1 (ARM).

> you're using the deprecated beforeExit event which was removed in Prisma 5
Thanks for the reminder! Yes, on our production code we're on Prisma 5.x, and it we're no longer using these hooks as they're deprecated. This repo predates Prisma 5.

Thank you very much for taking the time and effort to fix this issue - it massively improves the DX.

Not sure if you prefer closing this issue or once 5.3.0 is released, I'll keep it up to Prisma team 👍

**Comment by aqrln** [comment]
@MEnnabah let's close it so that it ends up in the changelog. Thank you for testing!
