### ISSUE TITLE
What is this error? How do I solve it?

### ISSUE THREAD

**Issue by Unicodist** [prisma/prisma#18790]
Hi Prisma Team! The following command just crashed.

## Command

`generate`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v19.8.1            | 
| Prisma CLI  | 4.12.0             | 
| Engine      | 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7| 

## Error
```
Error: RuntimeError: panicked at 'internal error: entered unreachable code: No unsupported field should reach that path', query-engine/schema-builder/src/input_types/mod.rs:28:40
```

**Comment by janpio** [comment]
This is an unexpected error that should never happen. Can you share the Prisma schema that causes this? We would love to be able to reproduce this - and then fix it. Thanks!

**Comment by janpio** [comment]
ping @Unicodist Can you provide some more information please so we can possibly reproduce this? Thanks.
