### ISSUE TITLE
[Introspection] Guardrail against tables with unique index, where at least one column is nullable ("PANIC: Unable to resolve a primary identifier for model foo")

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1880]
```sql
CREATE TABLE IF NOT EXISTS `foo` (
  `one` int(11) DEFAULT NULL,
  `two` int(11) NOT NULL,
  UNIQUE KEY `Index 1` (`one`,`two`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

This table is currently introspected as:

```prisma
model foo {
  one Int?
  two Int

  @@unique([one, two], name: "Index 1")
}
```

But when trying to run a `findMany()` against it, you get a panic: `PANIC: Unable to resolve a primary identifier for model foo.`

This is because the Query Engine currently only supports tables with a unique index that has only no nullable columns.

### Guardrail

The whole table is commented out (similar to tables with no unique identifier), and relations to it are disabled.

**Comment by pantharshit00** [comment]
This is still present in ` 2.0.0-alpha.1076`
