### ISSUE TITLE
[Introspection] Guardrail against tables with @id/@@id and @unique/@@unique (if only identifier) on semi supported types

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1881]
Some types do not work as model identifiers (`@id`/`@@id` and `@unique`/`@@unique` (if only identifier)). We need to comment out tables with such values to avoid causing problems to our users.

More information in the Engines implementation issue: https://github.com/prisma/prisma-engines/issues/592

**Comment by tomhoule** [comment]
Note: this also applies to `@unique/@@unique` if it is the only identifier for the model.
