### ISSUE TITLE
Client Extension: Make `.prismaVersion.client` available on "@prisma/client/scripts/default-index"

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#18829]
If I `import { Prisma as PrismaForVersion } from "@prisma/client"` I have `Prisma.prismaVersion.client` available in the extension. If I use  `import { Prisma } from "@prisma/client/scripts/default-index"` then I don't. So currently I use two imports.

**Comment by Jolg42** [comment]
Note from @millsp `import { Prisma } from "@prisma/client/scripts/default-index"` is only used because there is a `postinstall` cache with pnpm.
-> When creating an extension, `@prisma/client` is added as a peer dependency and already shared

**Comment by Jolg42** [comment]
⚠️ This is a blocker for writing a how to publish an extension guide.
