### ISSUE TITLE
Introspect default value with backslashes causes problem when generating client

### ISSUE THREAD

**Issue by kldzj** [prisma/prisma#1888]
## Bug description
Backslashes in SQL default values are not escaped properly and consequently return an invalid schema when introspecting.

## How to reproduce
1. Create table with one or more columns containing backslashes in the default value
```sql
CREATE TABLE test (
    `model_name_space` VARCHAR(255) NOT NULL DEFAULT 'xyz\\Datasource\\Model'
)
```
2. Introspect the database schema (`prisma2 introspect`)
3. Generate client (`prisma2 generate` fails)

---

The generated schema will look like this:
```prisma
model test {
    model_name_space    String    @default("xyz\Datasource\Model")
}
```

The following error is thrown when generating the client:
```
➜  prisma npx prisma2 generate  
Error: Schema parsing
error: Unexpected token. Expected one of: string interpolation start
  -->  schema.prisma:1552
     | 
1552 |   model_name_space                 String                          @default("xyz\Datasource\Model")
     |                                                                                 ^ Unexpected token.
     |
```

## Expected behavior
Backslashes in the default value should be escaped.

```prisma
model test {
    model_name_space    String    @default("xyz\\Datasource\\Model")
}
```

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Prisma version: prisma2@2.0.0-preview024
- Node.js version: v10.16.3

**Comment by tomhoule** [comment]
We are aware of this and will work on it soon: https://github.com/prisma/prisma-engines/issues/691

**Comment by tomhoule** [comment]
I just merged

**Comment by kldzj** [comment]
Hi @tomhoule, I am still able to reproduce the issue on @prisma/cli 2.0.0-alpha.1213. Backslashes aren't escaped properly. But the error changed and the issue now is harder to identify, as every row of the model containing backslashes in the default value now has an error like this: 
`Error validating: This line is invalid. It does not start with any known Prisma schema keyword.`
