### ISSUE TITLE
Prisma unable to handle long transaction with planet scale

### ISSUE THREAD

**Issue by jakeleventhal** [prisma/prisma#18909]
### Bug description

Similar to #13136

I am trying to perform a large transaction that must be atomic. My use case is user's need to make bulk updates to their inventory in my application via a CSV upload. It needs to be an atomic write for hundreds of rows. Here is how my code is setup:

```typescript
await prisma.transaction(async tx => {
	await Promise.all(rows.map(async row => {
		/** all pseudo code here
    		   // see if exists
                    await tx.col.findunique();

                    // create new record
                    await tx.col.create();

                    // create new record for other collection
                    await tx.col2.create();
		*/
	}));
})
```

When running this locally, this operation takes ~1s for me. When connected to planet scale, it hangs and then times out after 20s.
```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "target: test-db.-.primary: vttablet: rpc error: code = Aborted desc = transaction 1682305339595512410: ended at 2023-04-24 20:22:08.207 UTC (exceeded timeout: 20s) (CallerID: mmixrh8z5nl9v49zo787)", state: "HY000" })), transient: false })
```

### How to reproduce

See above

### Expected behavior

Have some workaround for bypassing transaction timeout in planet scale

### Prisma information

See above

### Environment & setup

- OS: macOS
- Database: PlanetScale
- Node.js version: `v18.9.1`

### Prisma Version

```
4.10.1
```

**Comment by janpio** [comment]
Planetscale generally limits transactions to 20s: https://planetscale.com/docs/reference/planetscale-system-limits#:~:text=Per%2Dtransaction%20timeout
<img width="806" alt="image" src="https://user-images.githubusercontent.com/183673/234124159-056dc63a-1b34-4727-b0ac-e206f0ec66eb.png">

To understand why this is fast locally, but not when talking to the online database you will have to understand what queries you are running. Many small queries locally with <1ms easily take ~100ms when talking to an online database if for example you are on the other side of the atlantic ocean, and still ~50 for your local internet provider to reach PlanetScale. That adds up quickly.

**Comment by jkomyno** [comment]
Hi @jakeleventhal, would you perhaps be able to share the Prisma schema you're using, and the actual `prisma.transaction` code with us? Thanks.
