### ISSUE TITLE
jsonProtocol: array shortcut is missing for `distinct` field

### ISSUE THREAD

**Issue by Raynos** [prisma/prisma#18906]
```
    → 335 const newReleaseArtistIds = await prisma.release.findMany({␊
            distinct: "artistId",␊
                      ~~~~~~~~~~␊
            where: {␊
              id: {␊
                in: [␊
                  "c0cd718c-996a-43d7-9dd6-36e3d07d162f",␊
                  "8b81a20a-9cad-401d-8ce5-7edf0c442b05",␊
                  "50693f3a-0a67-44aa-86fb-db9abb411f1c"␊
                ]␊
              }␊
            },␊
            select: {␊
              artistId: true␊
            }␊
          })␊
    ␊
    Argument \`distinct\`: Invalid value provided. Expected ReleaseScalarFieldEnum[], provided String.`,
  }

  › Argument `distinct`: Invalid value provided. Expected ReleaseScalarFieldEnum[], provided String.
  › <anonymous> (src/graphql/schema/types/activityFeed.spec.ts:1241:3)
```

When using the `distinct` parameter for `findMany()` the generated typescript says `string | string[]` but the runtime behavior of `jsonProtocol` says `string[]`

Can you update the typescript definition to be `string[]` ?

**Comment by jkomyno** [comment]
Hi @Raynos, thank you for this issue. Could you please also share with us the `schema.prisma` file you're working with and the version of Prisma you're using (`prisma --version`), so we can try reproducing and fixing this? Thank you.

**Comment by Jolg42** [comment]
I could reproduce by tweaking this test `./packages/client/src/__tests__/integration/happy/distinct/test.ts`
