### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#18907]
## Problem

We have a codebase where most application code resides in `/app`. Except `prisma/`. That doesn't work optimally for us.

## Suggested solution

Allow a configuration like `prisma.config.ts` and/or `prisma` field within `package.json` that permits setting the location of the schema:

```ts
import config from '@prisma/config'

export default config({
  schemaFilePath: './app/prisma/schema.prisma'
})
```

## Alternatives

None I could think of.

## Additional context

The current work around is to abstract the Prisma CLI in npm scripts. This leads to a maintenance burden because any part of the CLI wishing to be used in the project technically then needs a npm script wrapping it in order to pass `--schema ...`. Matters are made worse/harder by the fact that `--schema` is not a root CLI flag but per sub-command meaning this pattern in the `package.json` scripts does _not_ work:

```json
{
  "scripts": {
    "prisma": "prisma --schema './app/prisma/schema.prisma'"
  }
}
```

**Comment by jkomyno** [comment]
Hi @jasonkuhrt! I believe this is already solved via the `prisma`.`schema` key in `package.json`, as specified via [the docs](https://www.prisma.io/docs/concepts/components/prisma-schema#prisma-schema-file-location), wouldn't you agree?
I will close the issue for now, but feel free to re-open it in case this answer is not sufficient :)

**Comment by jasonkuhrt** [comment]
@janpio @jkomyno it would be nice to have something type safe.

**Comment by jasonkuhrt** [comment]
https://github.com/prisma/prisma/issues/18960
