### ISSUE TITLE
docs(deno deploy): `TypeError: context.digest is not a function at Hash.flush`

### ISSUE THREAD

**Issue by AdditionAddict** [prisma/prisma#18911]
Following the guide here:
https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-deno-deploy

This fails at the first step
```
> mkdir prisma-deno-deploy 
> cd prisma-deno-deploy
> deno run -A --unstable npm:prisma init
> Downloading Prisma engines for Node-API for windows [=================== ] 96%error: Uncaught (in promise) TypeError: context.digest is not a function
    at Hash.flush [as _flush] (ext:deno_node/internal/crypto/hash.ts:47:35)
    at Hash.Ot [as _final] (ext:deno_node/_stream.mjs:11:59823)
    at Fa (ext:deno_node/_stream.mjs:11:51130)
    at Ua (ext:deno_node/_stream.mjs:11:51274)
    at mt (ext:deno_node/_stream.mjs:11:51350)
    at Hash.S.end (ext:deno_node/_stream.mjs:11:50523)
    at he.u (ext:deno_node/_stream.mjs:11:36397)
    at Object.onceWrapper (ext:deno_node/_events.mjs:502:28)
    at he.emit (ext:deno_node/_events.mjs:391:35)
    at Ea (ext:deno_node/_stream.mjs:11:43461)

> deno --version
deno 1.32.5 (release, x86_64-pc-windows-msvc)
v8 11.2.214.9
typescript 5.0.3
```

The guide here: https://deno.com/manual@v1.29.2/node/how_to_with_npm/prisma
has `deno run --allow-read --allow-env --allow-write npm:prisma@^4.5 init` and this has the same issue

**Comment by Druue** [comment]
I can confirm that this happens with commands other than init:
`deno run -A npm:prisma@(version doesn't seem to matter) db push` (| pull | generate) have the same issue.
Downgrading to deno --version `1.31.3` seems to have fixed this

---

Okay, so, I did more testing with managing deno versions (I thought there could have maybe been a regression with the latest deno update) but I'm now back on 1.32.5 (from incrementally bumping up versions) and it isn't re-producing this error (--unstable isn't required anymore btw! [per 1.28](https://deno.com/manual@v1.28.0/node/npm_specifiers))

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/29753584/234564349-2acb7fe5-242e-4e7b-a1a5-9714ef8d2ca7.png">

**Comment by janpio** [comment]
I can also not reproduce this anymore. Can you take another look @AdditionAddict? 
Otherwise we should probably close this issue.
