### ISSUE TITLE
Prisma Client Extension: support `Prisma.validator`

### ISSUE THREAD

**Issue by KATT** [prisma/prisma#18943]
> I got asked to make a feature request by @millsp https://github.com/prisma/prisma/issues/15074#issuecomment-1384354061            

I always define a `select:` when doing queries (because otherwise we get the equivalent of `select *`), and want to do the equivalent to the below but with my default prisma client:

```ts
const postSelect = Prisma.validator<Prisma.PostSelect>()({
  // ..
})
```

_Originally posted by @KATT in https://github.com/prisma/prisma/issues/15074#issuecomment-1382089974_

**Comment by janpio** [comment]
Internal Note: This can not happen like this, but needs a workaround via an extension - which we should document.

**Comment by millsp** [comment]
We've worked on a [PR](https://github.com/prisma/prisma/pull/19698) that expands the capabilities of `Prisma.validator` to bring a more natural API while also working with any client (be it extended or non-extended). Feedback welcome :)
