### ISSUE TITLE
[Introspection] No @default attribute when introspecting on PostgreSQL from Prisma V1

### ISSUE THREAD

**Issue by pguilbault** [prisma/prisma#1897]
## Bug description
I am trying to migrate from Prisma1 to Prisma2.
When I introspect the database, default values are not generated in the output schema.

## How to reproduce
Here is my database schema:

```
CREATE TABLE "default$default"."User"
(
    id character varying(25) COLLATE pg_catalog."default" NOT NULL,
    isActive boolean NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY (id)
)
```

Database schema has no `DEFAULT` constraint defined for the column `isActive` so it seems logical that there is no `@default` attribute in the datamodel after the introspection (Prisma2).

However, it works fine with the Prisma1 introspection where the generated datamodel has the `@default` attributes.

The introspected schema:
```
model User {
  id                        String                      @id
  isActive                  Boolean
}
```

## Expected behavior

I was expecting the following Prisma2 schema:
```
model User {
  id                        String                      @id                      @default(cuid())
  isActive                  Boolean                      @default(true)
}
```

Same behaviour with the `@createdAt` and `@updatedAt` directives.

Where are defined (or stored) these constraints in the underlying database when using Prisma1 ?

## Environment & setup

- OS: Ubuntu 18.04 LTS
- Database: PostgreSQL in Docker (image: postgres:10.3)
- Prisma1 version: prisma@1.34.10
- Prisma2 version: prisma2@2.0.0-preview024
- Node.js version: 8.16.0

**Comment by janpio** [comment]
Hey @pguilbault, can you share the P1 schema that you used to create that Prisma 1 database in the first place? Then we can fully understand what is going on here. Thanks!

**Comment by pguilbault** [comment]
Hi @janpio, yes, sure !

Here is the P1 schema for the `User` type : 
```
type User {
  id: ID! @id
  isActive: Boolean! @default(value: true)
}
```

**Comment by janpio** [comment]
Thanks - interesting problem we have there. We are talking internally what the best way to fix that is. As the data is missing in the database and the default enforce on the Prisma level, we can not really do much with Introspection here.

We'll come up with something. Thanks for reporting!

**Comment by janpio** [comment]
> However, it works fine with the Prisma1 introspection where the generated datamodel has the `@default` attributes.

I tried to reproduce this, but got a different P1 schema:

```
type User {
  id: ID! @id
  isactive: Boolean!
}
```

What version of P1 are you using? (I tested with Prisma CLI version: prisma/1.34.10 (windows-x64) node-v12.6.0)

This makes total sense as the `value` really is not present on the database level and there is no way to "infer" it as you can have written anything into your schema.

**Comment by pguilbault** [comment]
Hi @janpio, I tested with Prisma CLI 1.34.10 / Node: 8.16

It seems that the Prisma1 introspection looks into the DB first, then in the local datamodel in order to generate the output datamodel. When I introspect in the database only (in removing the local model), the default value is obviously not present.

**Comment by janpio** [comment]
So it is introspecting the datamodel based on the datamodel... interesting ;) Thanks for the clarification. We understand the need for a better solution than just P2 introspection and will work on something before GA of P2.

**Comment by janpio** [comment]
FYI: This will be tackled via https://github.com/prisma/prisma/issues/2499

**Comment by janpio** [comment]
This should be solved via https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1
