### ISSUE TITLE
Improve error message when linux distribution is not supported

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#1898]
## Bug description
Right now if we don't support a specific linux distribution like alpine linux we fallback to debian as of https://github.com/prisma/prisma-client-js/blob/ab201b4307203991d53f1709fa45b725974afded/packages/get-platform/src/getPlatform.ts#L158.

That produces this very unreadable error message: 
```
Error: Error: Command failed with ENOENT: /prisma-boilerplate/web/node_modules/prisma2/query-engine-debian-openssl-1.1.x --enable-raw-queries cli dmmf
spawn /prisma-boilerplate/web/node_modules/prisma2/query-engine-debian-openssl-1.1.x ENOENT
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'server' failed to build: The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

## How to reproduce
Try using Prisma 2 on alpine linux

## Expected behavior
A better error like `Current platform is unrecognised and not supported` should be thrown.

## Version
prisma2@2.0.0-preview024, binary version: 377df4fe30aa992f13f1ba152cf83d5770bdbc85

**Comment by janpio** [comment]
We have a much better error message now.
