### ISSUE TITLE
ERROR: schema "pgtle" does not exist when using postgres extensions with prisma

### ISSUE THREAD

**Issue by 596050** [prisma/prisma#18991]
### Bug description

On running `npx prisma migrate dev` with primsa version:`4.13.0` and datasource configured with:
```
datasource db {
  provider   = "postgresql"
  url        = env("PRISMA_DATABASE_URL")
  extensions = [pgcrypto, pg_graphql, pg_stat_statements, pgvector, pgjwt, pgsodium]
}
```

and generator client configured with:

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["postgresqlExtensions"] // Enable the postgresqlExtensions. Currently in preview
  // https://github.com/prisma/prisma/issues/13396
  engineType      = "binary"
  binaryTargets   = ["native", "debian-openssl-3.0.x", "linux-musl", "linux-musl-openssl-3.0.x", "debian-openssl-1.1.x", "rhel-openssl-1.0.x"]
}
```

I'm, receiving this error:

```bash
Error: P3006

Migration `20230428083458_` failed to apply cleanly to the shadow database. 
Error:
db error: ERROR: schema "pgtle" does not exist
   0: sql_schema_connector::validate_migrations
           with namespaces=None
             at schema-engine/connectors/sql-schema-connector/src/lib.rs:309
   1: schema_core::state::DevDiagnostic
             at schema-engine/core/src/state.rs:266
```

<img width="416" alt="Screenshot 2023-04-28 at 09 38 06" src="https://user-images.githubusercontent.com/19141517/235098858-39e02cc1-bd9c-4520-96db-5299435b0c5e.png">

I've tried the suggestions in https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate/enable-native-database-functions
namely "Use the --create-only" and copying the generated create statements which are:
```sql
-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pg_graphql";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pgjwt";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pgsodium";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pgvector";
```

### How to reproduce

Run `npx prisma migrate dev` with the attached config

### Prisma information

primsa version:`4.13.0`

datasource configured with:
```
datasource db {
  provider   = "postgresql"
  url        = env("PRISMA_DATABASE_URL")
  extensions = [pgcrypto, pg_graphql, pg_stat_statements, pgvector, pgjwt, pgsodium]
}
```

and generator client configured with:

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["postgresqlExtensions"] // Enable the postgresqlExtensions. Currently in preview
  // https://github.com/prisma/prisma/issues/13396
  engineType      = "binary"
  binaryTargets   = ["native", "debian-openssl-3.0.x", "linux-musl", "linux-musl-openssl-3.0.x", "debian-openssl-1.1.x", "rhel-openssl-1.0.x"]
}
```

### Environment & setup

- OS:  macOS
- Database: PostgreSQL
- Node.js version: v16.15.1

### Prisma Version

```
4.13.0
```

**Comment by janpio** [comment]
Which of these extensions require and interact with `pgtle`? Quick google brings up https://github.com/aws/pg_tle and https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL_trusted_language_extension.html, but I don't understand the connection of that to the extensions you are using.

**Comment by 596050** [comment]
> Which of these extensions require and interact with `pgtle`? Quick google brings up https://github.com/aws/pg_tle and https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL_trusted_language_extension.html, but I don't understand the connection of that to the extensions you are using.

@janpio I've had another try with each extension individually and it seems to occur specifically with `pgvector`
