### ISSUE TITLE
Cannot dynamically create database with $queryRaw

### ISSUE THREAD

**Issue by valerii15298** [prisma/prisma#19019]
### Bug description

When trying to create database using `$queryRaw` I get an error in response.

### How to reproduce

```ts
const databaseName = "some_database_1";
await prisma.$queryRaw`CREATE DATABASE ${databaseName};`;
```

### Expected behavior

I expect the database to be created.

### Prisma information

But I get an error:
```
Raw query failed. Code: `1064`. Message:
You have an error in your SQL syntax; check
the manual that corresponds to your MariaDB server
version for the right syntax to use near '?' at line 1
```

### Environment & setup

- OS: **Windows**
- Database: **MariaDB**
- Node.js version: **19.7.0**

### Prisma Version

```
prisma                  : 4.12.0
@prisma/client          : 4.12.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at node_modules\.pnpm\@prisma+engines@4.12.0\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at node_modules\.pnpm\@prisma+engines@4.12.0\node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.12.0-67.659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Default Engines Hash    : 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Studio                  : 0.483.0
```

**Comment by Weakky** [comment]
Hey @valerii15298,

I wouldn't be surprised if parameterizing the database name is something that's not supported. Could you try with:

```js
const databaseName = "some_database_1";
await prisma.$queryRawUnsafe`CREATE DATABASE ${databaseName};`;
```

You might need to escape quotes depending on your database name.

**Comment by valerii15298** [comment]
@Weakky thanks, yes, I already using it like that. Just thought maybe it is possible to do it with regular `$queryRaw`

**Comment by Weakky** [comment]
Unfortunately, you can't use query parameters for identifiers (database, table, or column names).

I'll close this now if it's fixed. Thank you 🙏
