### ISSUE TITLE
`findUniqueOrThrow` not getting batched by Prisma dataloader

### ISSUE THREAD

**Issue by cdimino** [prisma/prisma#19059]
### Bug description

Over in https://github.com/MichalLytek/typegraphql-prisma/issues/383 we've been able to repro an issue where it looks like `findUniqueOrThrow` doesn't get batched the same way `findUnique` does.

### How to reproduce

Easiest way would be to follow the repro steps in the typegraphql-prisma issue, this issue also has valid repro steps: https://github.com/prisma/prisma/issues/18838

### Expected behavior

Would expect `findUniqueOrThrow` to follow the same batching behaviors as `findUnique` within the Prisma dataloader.

### Prisma information

Seeing this with Prisma 4.13.0, but possibly earlier as well.

### Environment & setup

- OS: Amazon Linux 2
- Database: PostgreSQL
- Node.js version: v18.12.0

### Prisma Version

Prisma 4.13.0.

**Comment by andresribeiro** [comment]
duplicated #16625

**Comment by cdimino** [comment]
That ticket has had no action in half a year...

**Comment by janpio** [comment]
Adding more issues to our workload will unfortunately not _help_ with that, but make it worse @cdimino.
Can you please post a comment on the other issue with the information you included in your issue description? That is a worthwhile addition to #16625 via a comment. Thanks.

**Comment by cdimino** [comment]
Blaming me for a bug is probably not productive either, but sure I can copy/paste this content over for you to ignore there as well.
