### ISSUE TITLE
Remove enum usage from docs where sqlite is used

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#1906]
Original Ref: https://github.com/prisma/prisma2/issues/1860 

## Documentation error description
Right now certain sections of the docs are using enums with sqlite.

For example: https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#example

We have removed the shim for sqlite that used to create enums via a join and table and now we fallback to native database features for other supported databases. We should remove all usage of sqlite with enum from the docs as that can mislead our users.

Related: https://github.com/prisma/migrate/issues/377

**Comment by nikolasburk** [comment]
I believe all instances where enums were used with SQLite have been adjusted, please let me know if you still find any and we can reopen this issue 👍

**Comment by shvamabps** [comment]
How can one use this feature as this helps to provide multiple values at once to a certain field and not create a new table and insert the data in that table and use a FOREIGN KEY to link the field to the respective table. Any possible way that you'd suggest to implement this without creating a new table while using sqlite and prisma.
