### ISSUE TITLE
Prisma version >= 4.10 performance decreases.

### ISSUE THREAD

**Issue by Tilendor** [prisma/prisma#19094]
### Bug description

Increased CPU consumption when upgrading from Prisma 4.7.1

We wanted to take advantage of the client extensions and are currently on version 4.7.1

We need to use at least Prisma 4.10.0 to be compatible with TypeScript and use nested includes.

Our attempts to upgrade and deploy to production have resulted in decreased throughput and increased CPU usage.  It exceeded our performance limits, and we needed to roll back.

We attempted both 4.12 and 4.10.  

In order to make sure the Prisma upgrade is the only difference, we isolated the Upgrade commit and tested it using https://github.com/mcollina/autocannon in our staging environment using an expensive query.

We slowly ramped up the number of concurrent connections and requests until the AWS health-check failed twice in 10 seconds with a 5 second timeout.

I configured the test to have each connection send 10 requests sequentially, and scaled up the number of connections until we got failure messages.

I did these tests over the weekend with no other usage.

The 4.7.1 code could handle 14 concurrent connections 
Prisma 4.9.0 could handle 13 concurrent connections (7.2% worse)
Prisma 4.10.0 could handle 12 concurrent connections (14.3% worse)
Prisma 4.12.0 could handle 9 concurrent connections. (55.8% worse)

We do have a lot of optimization to do.  The graphql query we used is to present a list of accounts to a user, so it gets hit a lot in production.  However we would hope the behavior wouldn't degrade so significantly with only upgrading Prisma versions.

The graphql query in particular has 265 properties, with 35 different types, so it looks like there is probably a significant amount of serialization work to do from the database result, and I wonder if something has changed there.

### How to reproduce

Currently reporting on our production and staging environments.  I don't have a concise way to test yet.

### Expected behavior

A Prisma upgrade shouldn't result in a significant decrease in performance and throughput

### Prisma information

Versions 4.9, 4.10, and 4.12.  I'm checking if I can share the query directly.

### Environment & setup

- OS: Amazon Linux 2 AMI
- Database: PostgreSQL
- Node.js version: v16.16.0

### Prisma Version

```
prisma                  : 4.10.0
@prisma/client          : 4.10.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine ca7fcef713137fa11029d519a9780db130cca91d (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli ca7fcef713137fa11029d519a9780db130cca91d (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.10.0-84.ca7fcef713137fa11029d519a9780db130cca91d
Default Engines Hash    : ca7fcef713137fa11029d519a9780db130cca91d
Studio                  : 0.481.0

```

**Comment by janpio** [comment]
If performance of recent Prisma versions was generally 50% worse, we would have had a lot of reports of this in the last few months. Our own performance testing also point in the opposite direction - things got generally faster.

Can you provide any additional information that would help us pinpoint what could be going on for you? Are individual queries slower? Can you isolate the CPU impact in any way?

**Comment by Tilendor** [comment]
The issue was with logging library incompatibility that killed our AWS sidecar, which then took down our AWS task.  This was not a prisma issue

**Comment by janpio** [comment]
Thanks for the update <3
