### ISSUE TITLE
Error when run `npx prisma db pull` with DeepinOS 20.9GNU/LInux

### ISSUE THREAD

**Issue by babually** [prisma/prisma#19157]
### Bug description

HI there, I'm using Deepin OSas my primary OS fro develepment but i got an error when using Prisma. I got this error many times:

```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "deepin". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Prisma schema loaded from prisma/schema.prisma
Environment variables loaded from .env
Datasource "db": PostgreSQL database "todo-trpc", schema "public" at "localhost:6500"

⠋ Introspecting based on datasource defined in prisma/schema.prismaprisma:warn Prisma doesn't know which engines to download for the Linux distro "deepin". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
✖ Introspecting based on datasource defined in prisma/schema.prisma
```

Can you help to fix this bug from Prisma..! Thak you

### Prisma information

prisma:warn Prisma doesn't know which engines to download for the Linux distro "deepin". Falling back to Prisma engines built "debian"

### Environment & setup

- OS: DeepinOS 20.9
- Database: <!--[PostgreSQL,
- Node.js version: 18

### Prisma Version

```

```
prisma:  4.14.0

**Comment by Jolg42** [comment]
Hi @babually,

So this is only a warning message but I think everything should work normally since https://en.wikipedia.org/wiki/Deepin is based on Debian?

If so, we could silence this warning if we detect Deepin in the future.

**Comment by spcbfr** [comment]
@Jolg42 I am getting a very similar warning on PopOS. everything is working here, so if we could get rid of warning that would be amazing

```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "org.freedesktop.platform". Falling back to Prisma engines built "debian"
```

**Comment by Jolg42** [comment]
Note: `cat /etc/os-release` looks like

For Deepin
https://github.com/linuxdeepin/wiki.deepin.org/blob/57757edc7e78084121081107d6aa5265a7aef5b5/en/About_Deepin/Deepin_FAQ.md?plain=1#L16
```
    $ cat /etc/os-release
    PRETTY_NAME="Deepin 20.6"
    NAME="Deepin"
    VERSION_ID="20.6"
    VERSION="20.6"
    VERSION_CODENAME="apricot"
    ID=Deepin
    HOME_URL="https://www.deepin.org/"
    BUG_REPORT_URL="https://bbs.deepin.org/"    
```

For PopOS (from https://github.com/pop-os/pop/issues/2887)
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com/"
SUPPORT_URL="https://support.system76.com/"
BUG_REPORT_URL="[https://github.com/pop-os/pop/issues](https://github.com/pop-os/pop/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by cnikolov** [comment]
how can i get rid of the warning got the pop os as mentioned above by @Jolg42

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
