### ISSUE TITLE
Long delay before querying table with many unique relations

### ISSUE THREAD

**Issue by mattkindy** [prisma/prisma#19160]
### Bug description

Recently changed a large number of relations between two models from 1-to-many to 1-to-1 with unique keys
Since then, when we query this table (with all the unique foreign keys) with the prisma client

```bash
2023-05-05T17:05:49.460-05:00	[34mdebug[39m: {
2023-05-05T17:05:49.460-05:00	"query": "...",
2023-05-05T17:05:49.460-05:00	"params": "[\"ckzpxf3g7066w0704yxf4bzsr\"]",
2023-05-05T17:05:49.460-05:00	"duration": "4 ms"
2023-05-05T17:05:49.460-05:00	}

2023-05-05T17:05:53.900-05:00	[34mdebug[39m: Flushing 2 events

2023-05-05T17:05:55.927-05:00	[34mdebug[39m: {
2023-05-05T17:05:55.927-05:00	"query": "SELECT ... WHERE (... = $1 AND ... IN ($2)) OFFSET $3",
2023-05-05T17:05:55.927-05:00	"params": "[\"NA\",\"ckzpxf3g7066w0704yxf4bzsr\",0]",
2023-05-05T17:05:55.927-05:00	"duration": "20 ms"
2023-05-05T17:05:55.927-05:00	}
```

I see a significant amount of empty time between the end of the previous query and the beginning of the next. The only clue I have is this "Flushing [N] events" (nearly always N=2), which doesn't appear anywhere that I can find in the Prisma source code. It doesn't affect any other table, and the SQL statement when run directly seems reasonably performant.
  
- I was able to see a huge spike in memory. We run on AWS Lambda instances with 4GB of RAM available. Normally we are closer to 500MB during these queries. With the client generated by the modified schema, we maxed out at 4GB.
- I was able to reproduce this with against a local database instance
- After reverting the changes, performance went back to normal

### How to reproduce

1. Modify a model A to have many (10+?) unique relations to another model B (with differently named relations, etc)
2. Regenerate the Prisma client with this schema change
3. Attempt to query model A, not referencing any of the relations
5. See slow response

### Expected behavior

There is not a >100ms delay consistently before querying a specific table that happens to have many `@unique` properties

### Prisma information

Will not share the entire schema but 

# Models
## QuoteRequest
This is just a subset of the model to give a sense of the setup.

### Relations
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/35696388/236581666-cc124b8d-9418-4c03-a91a-f20f324825ec.png">

### Foreign keys
<img width="777" alt="image" src="https://user-images.githubusercontent.com/35696388/236581792-cf2b5f9b-336c-4771-b96d-8d3cc09d7521.png">

## RangeSpecMinMax
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/35696388/236581722-332a57c2-e4eb-43f3-a5e5-4be367a1c2b6.png">

# Queries
Reproducible with a simple query:
```ts
await client.quoteRequest.findUniqueOrThrow({ where: { id: someId }, select: { id: true } });
```

# Additional Information
- JSON Protocol preview feature enabled (both with and without change)
- **Schema**: 142 models, many relations
- Lambda built using webpack

### Environment & setup

- **OS**: macOS, Amazon Linux 2
- **Database**: PostgreSQL
- **Database connection configuration**: 
  - Using pgbouncer for connection pooling to Postgres RDS. 
  - In this snapshot 5 connections for the client used in this lambda
- **Node.js version**: 16.19.0
- **Build**: Webpack

### Prisma Version

```
4.13.0
```

**Comment by janpio** [comment]
Hey, can you provide us some information that allows us to reproduce what you are seeing? Can you share your schema? How does your app work, what tooling does it use? What does this `Flushing x events` logging come from - because it does indeed not come from Prisma? Can you maybe even create a small reproduction app that displays the same behavior?

**Comment by mattkindy** [comment]
- I would share the whole schema but let me confirm that's possible. I think setting up a minimal reproduction would be more helpful, all in all.
- More that you've mentioned that it doesn't come from Prisma, I suspect the logs I mentioned are a result of the following on our Prisma client. This hasn't changed recently. 

```ts
  client.$on('query', ({ query, params, duration, target, timestamp }) => { 
     logger.debug(JSON.stringify({ query, params, duration: `${duration} ms` }, undefined, 2)); 
  
     // periodic query prisma uses to hold onto connections 
     if (query === 'SELECT 1') { 
       return; 
     } 
  
     Sentry.getCurrentHub().withScope((scope) => { 
       const querySpan = ( 
         scope.getSpan() ?? Sentry.startTransaction({ name: 'prisma.client' }) 
       ).startChild({ 
         op: 'db.query', 
         data: { 
           query, 
           params, 
           target, 
           duration, 
           timestamp 
         } 
       }); 
  
       const endTime = querySpan.startTimestamp; 
       querySpan.startTimestamp -= duration / 1000; 
       querySpan.finish(endTime); 
     }); 
   });
```

- I will try to get a minimal reproduction together, or at least see if by removing things the problem goes away and when

**Comment by mattkindy** [comment]
@janpio What can I provide exactly in answer to this?
> How does your app work, what tooling does it use?

It's a very broad question, but I can create this behaviour independently of our app, generally by spinning up a local apollo server running typegrahpql-prisma. Third party tooling we use includes AWS SDK (e.g. parameter store), LaunchDarkly, Sentry, winston logger.

**Comment by mattkindy** [comment]
Sorry, I am still working on getting a minimal reproduction of this, just other demands at the moment

**Comment by mattkindy** [comment]
Ended up not being in a position to create a reproduction for this

**Comment by janpio** [comment]
Thanks for the update @mattkindy.

"Good" news: Another user did! https://github.com/prisma/prisma/issues/20799 helped us understand the problem (many `@unique` are bad) and then fix it: https://github.com/prisma/prisma-engines/pull/4179 This will be part of Prisma 5.3.0 on September 12th most probably. As soon as the change are in our `dev` version, we will also post the version to test in #20799 to try out.
