### ISSUE TITLE
Client is bricked from connecting to DB if first attempt fails.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [prisma/prisma#19182]
### Bug description

If the Prisma Client is unable to connect to the DB on its first query, all subsequent attempts to make a query will also fail.

### How to reproduce

Application code:

```ts
const prismaDb = new PrismaClient({
  datasources: { db: { url: "postgresql://root@localhost:26257/gather" } },
});

const run = async () => {
  try {
    const message = await prismaDb.$executeRaw`SELECT 1`;
    console.log(message);
  } catch (e) {
    console.log("e", e);
  }
  setTimeout(run, 1000);
};

run()
```

Then, walk through these two scenarios:

**Scenario 1**

1. Start with DB off
2. Start running script 
3. Turn DB on

Observe how it will never successfully connect even after DB is on.

**Scenario 2**

1. Start with DB on
2. Start running script 
3. Turn DB off
4. Turn DB on

Observe how it will reconnect successfully.

### Expected behavior

Client is able to connect to a DB on subsequent calls even if the first one fails.

### Prisma information

Not relevant, any schema will do.

### Environment & setup

- OS: macOS 12.4
- Database: CRDB 22.8
- Node.js version: v16.10

### Prisma Version

```
prisma                  : 4.13.0
@prisma/client          : 4.13.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.13.0-50.1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Default Engines Hash    : 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Studio                  : 0.484.0
Preview Features        : tracing, extendedWhereUnique
```

**Comment by AndrewSouthpaw** [comment]
Oh I realize this overlaps with https://github.com/prisma/prisma/issues/18071, but this provides a simpler repro that's just a script rather than an http server, in case that helps.

**Comment by janpio** [comment]
This might be a regression from this older issue: https://github.com/prisma/prisma/issues/9420#issuecomment-1543038643

**Comment by jkomyno** [comment]
I have reproduced this issue on both `postgres` and `mysql` with `prisma` versions `4.12.0`, `4.14.0`, and `4.8.0`. It's a general re-connection problem, not a connector-specific one.

`prisma@4.7.1` seems to be the most recent version that doesn't suffer from this problem.

**Comment by AndrewSouthpaw** [comment]
This is our workaround for right now, which recreates the client on failure. We have the constraint where we're exporting a static constant, `prismaDb`, which is top level. So I needed to create a proxy to be able to swap out the underlying instance.

```ts
export const createClient = (url: string) => new PrismaClient({ datasources: { db: { url } } });

// variable to hold the current client. May be re-created if initialization fails
let instance: PrismaClient;

const createAndSetUpNewClient = () => {
  const client = createClient('postgresql://someurl');
  /* add any middleware here... */
  connectToDbOrRecreateClient(client);
  return client;
};

const getPrismaClient = () => (instance ??= createAndSetUpNewClient());

export const resetPrismaClient = () => {
  console.log("[prisma:init] Resetting Prisma client");
  instance = createAndSetUpNewClient();
};

const connectToDbOrRecreateClient = (client: PrismaClient) => {
  // We can't have a top-level await to trigger the connect, so this is done out of band. If the
  // client is unable to connect on init, it will be permanently stuck and never able to connect
  // to the DB. Related: https://github.com/prisma/prisma/issues/19182. A workaround for now is
  // to create a new client.
  console.log("[prisma:init] Initializing client");
  client
    .$connect()
    .then(() => {
      console.log("[prisma:init] Initialized client successfully");
    })
    .catch(async (e) => {
      console.log("[prisma:init] Client failed on initialization", e);
      await new Promise(res => setTimeout(res, 5_000))
      resetPrismaClient();
    });
};

// Wrapping the export with a proxy allows us to lazily instantiate the prisma client, which is
// important because we may need to re-create the client if the initial connection fails.
// eslint-disable-next-line @typescript-eslint/consistent-type-assertions
export const prismaDb = new Proxy({} as PrismaClient, {
  // there's never a good way safely make a proxy with TS, just ignore where required, we're
  // just passing along to the original object
  // @ts-ignore
  get: (target, name) => getPrismaClient()[name],
});
```

One issue is that the check for connectivity happens out of band from the event loop. We run on k8s, so we might do something like set up a readiness probe that runs the `$connect` logic and verifies everything is good, in case that gives inspiration to others. 😄

**Comment by Weakky** [comment]
Hey @AndrewSouthpaw,

You can workaround this issue by enabling the `jsonProtocol` preview feature. If you can't switch to `jsonProtocol` just yet, the next release will contain a fix.

Thanks for bringing this to our attention 🙏
