### ISSUE TITLE
Integration tests for libraries

### ISSUE THREAD

**Issue by hayes** [prisma/prisma#19180]
## Problem

4.13 broke Pothos and required a small patch to get things working again (this has happened a couple times in the past as well).

Pothos uses the internal _dmmf/_baseDmmf/_runtimeDatamodel property on the Prisma client (depending on the prisma version).  This is obviously a private method and probably shouldn't be relied on, but for backwards compatibility and to keep the devex as simple as possible this is still used by Pothos.

Expecting Prisma to keep backwards compatiblity for private/internal APIs is obviously not reasonable, but it would be great if we could add some basic smoke tests for Pothos and other libraries that build on top of Prisma to get an early warning about incompatibilities before they are published.  

## Suggested solution

Create some very basic tests that use Prisma with Pothos that get run against some sort of pre-release builds.  

I'm not sure exactly where these should live, and they shouldn't be blockers for Prisma releases.

Ideally test failures would automatically open issues on the corresponding library so they can fix any issues before the release

**Comment by Jolg42** [comment]
Hi @hayes!

So what can be done is to test against the "dev" version on npm, all Prisma packages are published for each commit on main to this "dev" tag, for example the current version is `[4.15.0-dev.8](https://www.npmjs.com/package/@prisma/client/v/4.15.0-dev.8)`

We already have a setup to test many different things in our "ecosystem-tests"
https://github.com/prisma/ecosystem-tests

I think we could add it here (note that failures are not blockers here):
https://github.com/prisma/ecosystem-tests/tree/dev/community-generators

If you want to contribute and add it, I'll be happy to help and review.

What do you think?

**Comment by janpio** [comment]
Look who had a similar thought 2 years ago 😆 https://github.com/prisma/ecosystem-tests/issues/2049
Would be amazing if you could take a look and maybe start a PR. We're happy to help along, and maybe use this opportunity to add some documentation on how ecosystem-tests works (if we don't have that yet).

**Comment by hayes** [comment]
Nice, that's exactly what I was looking for!
