### ISSUE TITLE
`@updateAt` doesn't work as expected

### ISSUE THREAD

**Issue by UncleVic** [prisma/prisma#19216]
### Bug description

Columns with @updatedAt are not automatically updated when the record is updated, but the value is set on insert.

### How to reproduce

1. Run migrations and generate a prisma client
2. Create a new record. You can see that fields `created_at` and `update_at` have the same value - it's ok.
3. Update the record one more time.  The fields `created_at` and `update_at` have the same value after any update. The value of  `update_at` wasn't changed.

### Expected behavior

Columns with @updatedAt has a new value of current time after each update.

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Test {
  id            String   @id @default(dbgenerated("public.uuid_generate_v4()")) @db.Uuid
  name          String
  createdAt     DateTime @default(now()) @map("created_at") @db.Timestamptz(3)
  updatedAt     DateTime @updatedAt @map("updated_at") @db.Timestamptz(3)
}
```

```ts
await prisma.test.usert({
  where: { name: 'test' },
  update: { name: 'test1' },
  create: { name: 'test' },
});
```

### Environment & setup

- OS: macOS, Ubuntu
- Database: PostgreSQL
- Node.js version: v19.8.1

### Prisma Version

```
prisma                  : 4.14.0
@prisma/client          : 4.14.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.14.0-67.d9a4c5988f480fa576d43970d5a23641aa77bc9c
Default Engines Hash    : d9a4c5988f480fa576d43970d5a23641aa77bc9c
Studio                  : 0.484.0
```

**Comment by janpio** [comment]
Could you try out if this also happens when the field with `@updatedAt` is not mapped via `@map` to a different name? Maybe that is where this bug stems from. Thanks!

**Comment by LutherTS** [comment]
I have the exact same issue. UpdatedAt is stuck at the same time as createdAt's @default(now()).

**Comment by UncleVic** [comment]
> I have the exact same issue. UpdatedAt is stuck at the same time as createdAt's @default(now()).

You should remove any assignments to updatedAt in your code, except for @default(now()). Don't touch it at all. It'll be managed by ORM

**Comment by VLahodnyi** [comment]
I have the exact same issue. UpdatedAt is stuck at the same time as createdAt's @default(now()).

**Comment by xRiku** [comment]
> > I have the exact same issue. UpdatedAt is stuck at the same time as createdAt's @default(now()).
> 
> Here's the right syntax: `updatedAt DateTime @updatedAt @default(now())` This is what eventually worked out for me.

it worked for me thank you

**Comment by khalvai** [comment]
I am having the same problem in 2025, I was relying on Prisma but suddenly find out that it actually do not work as I expected.
