### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by ShyamHarode** [prisma/prisma#19235]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.16.0           | 
| Prisma CLI  | 4.13.0             | 
| Engine      | 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a| 

## Error
```
Error: Error in migration engine.
Reason: 

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by janpio** [comment]
Can you maybe provide more information on what you were doing, and what full error you got @ShyamHarode? The current information will not be enough for us to understand, reproduce and fix any potential problem.

**Comment by ShyamHarode** [comment]
@janpio Thanks for asking, the error has been resolved. This error was caused by a mismatch between the version of the globally installed prisma (4.14.0) and the package.json prisma version (4.13.0).
