### ISSUE TITLE
TypeScript 5.x import from @prisma/client error

### ISSUE THREAD

**Issue by Aliaksandr-Kasko-JazzTeam** [prisma/prisma#19232]
### Bug description

When I switch to TypeScript 5.x then I can't use type definitions from `@prisma/client` in IntelliJ Idea.
IDE shows me an error `Cannot resolve symbol 'PrismaClient'`
But building a project with `tsc` is successfull and shows no error.
When I downgrade TypeScript to 4.9.5 then all start working fine. I dunno, maybe this bug related to TypeScript itself, not Prisma.

### How to reproduce

1. Create sample prisma project with typescript 5.x.
2. Generate client using `npx prisma generate`
3. Try to import something from `@prisma/client`

### Prisma information

```prisma
// Add your schema.prisma
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "linux-musl-openssl-3.0.x"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Data {
  id Int @id @default(autoincrement())
}
```

```ts
// Add your code using Prisma Client
import {PrismaClient} from "@prisma/client";

export class Repository {
  private prisma: PrismaClient;
  
  constructor() {
    this.prisma = new PrismaClient();
  }
//...
}
```

### Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: v16.13.2

### Prisma Version

```
4.14.0
```

**Comment by aqrln** [comment]
@Aliaksandr-Kasko-JazzTeam given the information you provided, this sounds like a bug in IntelliJ Idea (or maybe they don't have full support for TypeScript 5 yet), have you already reported it in https://youtrack.jetbrains.com/issues/IDEA?

Does the issue persist if you reload your project after generating the client? Also, does it happen when generating the client into a custom location outside of node_modules?

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
@aqrln maybe you're right. I'm using 2022.2 and I think that it have no TS 5 support.

When I reload project or even IDE, I still facing the issue. When I generate the client to other location, e.g. `/generated/`, I can import client with no errors.

It's noteworthy that I facing the problem only with Prisma

**Comment by AndriyCh1** [comment]
@Aliaksandr-Kasko-JazzTeam I use the same version of the IDE and recently faced this issue. Have you fixed it somehow back then?
Could you explain how you generated the client to another location? I'm new to Prisma

**Comment by AndriyCh1** [comment]
Still can't figure out how I managed to fix it and what exactly resolved the issue. But I'll describe what I did for that.

First, I deleted node_modules and then installed dependencies using the "PRISMA_SKIP_POSTINSTALL_GENERATE=true npm install" command (found about it here: [](`https://github.com/prisma/prisma/issues/13946`)). 
However, when I ran the prisma generate command, I encountered the following error multiple times:
`Downloading Prisma engines for Node-API for Windows [ ] 0% Error: The request to https://binaries.prisma.sh/all_commits/6b0aef69b7cdfc787f822ecd7cdc76d5f1991584/windows/schema-engine.exe.gz.sha256 failed, and the reason given was: getaddrinfo ENOTFOUND binaries.prisma.sh.`
Interestingly, after encountering this error several times, it suddenly disappeared, and the Prisma Client was successfully generated. I also updated npm to the last version (9.8.0) and invalidated cache in Webstorm before those all.

**Comment by Weakky** [comment]
Hey folks,

Is this still an issue for you? If so, would you mind providing us a reproduction repository that we could load with IntelliJ and observe the symbols not being found? Thanks

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
@Weakky hi there.
There's no more issue for me

**Comment by AndriyCh1** [comment]
Hi @Weakky 
I don't have any more issues either

**Comment by Weakky** [comment]
Thank you for letting us know folks 🙏

**Comment by nikfakel** [comment]
I installed prisma 5.18 with typescript 5.1.3 and I have absolutely the same issue. Generate prisma to other folder works, build works, just WebStorm give this error "Cannot resolve symbol "PrismaClient"

<img width="562" alt="image" src="https://github.com/user-attachments/assets/d485314b-59fb-48b9-a160-edc1f1a1f69f">
