### ISSUE TITLE
Error: PrismaClient is unable to be run in the browser.

### ISSUE THREAD

**Issue by rajanshresth** [prisma/prisma#19238]
### Bug description

OS: Linux Ubuntu 22.04.2 LTS
Browser: Microsoft Edge
Text Editor: vs-code

![image](https://github.com/prisma/prisma/assets/76089000/59ead0ba-e7f5-4398-a75f-8960de501296)

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by GwaraDon** [comment]
![image](https://github.com/prisma/prisma/assets/30464789/ae3a6c60-19ff-4ad6-aa35-ba379e21add0)

**Comment by janpio** [comment]
Please don't open issues _and_ discussions for the same problem, but give us some time to actually respond to your discussion: https://github.com/prisma/prisma/discussions/19239
