### ISSUE TITLE
Prisma `info` log level doesn't emit `event` 

### ISSUE THREAD

**Issue by AndrewSouthpaw** [prisma/prisma#19256]
### Bug description

When setting the client log level, if you set `{ emit: 'event', level: 'info' }` you won't get a log about the pool initializing with connections. If you set `{ emit: 'stdout', level: 'info' }`, you do.

### How to reproduce

Omitting some boilerplate, this will emit a log event when initializing:

```ts
const client =   new PrismaClient({
  datasources: { db: { url: '...' } },
  log: [{ emit: "stdout", level: "info" }]
})

await client.$connect()

// emits this log:
// prisma:info Starting a postgresql pool with 21 connections.
```

While setting it up to emit as an event, we don't get that log about the pool starting:

```ts
const client =   new PrismaClient({
  datasources: { db: { url: '...' } },
  log: [{ emit: "event", level: "info" }]
})

client.$on('info', (e) => {
  console.log('info event', e)
})

await client.$connect()

// no event is emitted
```

### Expected behavior

Get the same info printout about the connection pool starting when emitting `info` levels as events.

### Prisma information

Schema not relevant

### Environment & setup

- OS: macOS
- Database: CRDB v22.8
- Node.js version: 16.20

### Prisma Version

```
prisma                  : 4.13.0
@prisma/client          : 4.13.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.13.0-50.1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Default Engines Hash    : 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Studio                  : 0.484.0
Preview Features        : tracing, extendedWhereUnique
```

**Comment by mwanago** [comment]
I'm experiencing the same issue.

**Comment by Jolg42** [comment]
I could not reproduce with the information you provided 🤔 (and could not either with the latest version)

Is this still an issue for you @AndrewSouthpaw?

**Comment by AndrewSouthpaw** [comment]
Can confirm this is fixed now (or I was just completely wrong originally, who knows)!
