### ISSUE TITLE
BUG with findmany on nextjs

### ISSUE THREAD

**Issue by nitlott** [prisma/prisma#19268]
### Bug description

after more investigation it seams it is prismas findmany in combination with nextjs, it does not mather if its on vercel or not.
if i npm run build and npm run start locally i get same results.
but if i run npm run dev it works.

this findmany caches forever after first run (even if you try other devices it still shows the data from first run and deleted posts are still there also new prompts is **not** there)
here is my /api/prompt route
`const prompts = await prisma.prompt.findMany({ include: { creator: true }, });`

and this one works without a problem everytime :
here is my /api/users/[id]/prompt route
`const prompts = await prisma.prompt.findMany({ where: { creatorId: params.id, }, include: { creator: true }, });`

i have tried many different aproaches solving this but nothing seams to work. this problem started when i implemented prisma instead of using mongoose/mongodb.

i now use postgres database (atm supabase if that mathers for investigation) 

### How to reproduce

Use nextjs 13 with appfolder and no src folder, create 2 different routes that uses findmany as above, and setup prisma to supabase postgres. load the feed to fetch all prompsts,. and make a profile page that can list its own prompts with params that contain id to filter in findmany

### Expected behavior

expected behavior is that the feed page should update with current prompts in database, not showing deleted prompts and showing new prompts. which it does not.

in profile page it works flawlesly

only difference is this part in findMany:

`where: { creatorId: params.id, }`

### Prisma information

generator client {
  provider = "prisma-client-js"
  seed     = "node prisma/seed.ts"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

### Environment & setup

- OS: 
archlinux (same results on vercel production tho)

- Database: 
postgres (same results on vercel production tho)

- Node.js version: 
v19.9.0 (same results on vercel production tho)

### Prisma Version

```
"prisma": "^4.14.0",
```

**Comment by aqrln** [comment]
@nitlott thank you for the report, however at least to me it's a bit hard to understand it since you refer to the concepts and entities from your project which we cannot see, and it feels like there's some missing context. Could you please provide at least the schema, or, even better, a full reproduction if it's possible?

Also, what do you mean by "after more investigation"? Is there's another relevant issue or discussion that should be linked here?
