### ISSUE TITLE
Prisma Client generator: remove creation of a package.json

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19306]
Code: https://github.com/prisma/prisma/blob/0fe45ca9e013e607fe5d3cf0852ea9aca341466c/packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts#L39

I don't think it was documented anywhere.

Instead, we could output a warning message?

**Comment by aqrln** [comment]
@Jolg42 I think the linked issue (https://github.com/prisma/prisma/issues/13999) is unrelated.

The code you linked to that we planned to remove creates `package.json` in the user's project (i.e. where the dependency on `prisma` and `@prisma/client` will be added), while https://github.com/prisma/prisma/issues/13999 is about the `package.json` created in the generated client.

**Comment by Jolg42** [comment]
Indeed, I removed it from the description ✅
