### ISSUE TITLE
Drop support for Node.js v14

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19304]
- [x] Bump tested versions, so we test 16, 18, 20
	- [x] https://github.com/prisma/ecosystem-tests/pull/3462
	- [x] https://github.com/prisma/prisma/pull/19798
	- [x] https://github.com/prisma/engines-wrapper/pull/449
	- [x] https://github.com/prisma/checkpoint-client/pull/213
	- [x] https://github.com/prisma/mini-proxy/pull/46
- [ ] Update docs (https://www.prisma.io/docs/reference/system-requirements)
	- [ ] https://github.com/prisma/docs/pull/4928 
- [x] Update CLI https://github.com/prisma/prisma/blob/d43cfff9e9135b2a2c641dede4efa4ebf1914461/packages/cli/scripts/preinstall.js#L47
- [ ] examples https://github.com/prisma/prisma-examples/pull/4750
- [x] Release notes draft
- [ ] Anything else?

**Comment by janpio** [comment]
Context: Version 4.14.0 has <5% of usage of Node 14.

**Comment by jkomyno** [comment]
Is that linked snippet of `preinstall.js` still useful? I believe most Node.js packages declare the minimal supported Node.js version via the `engines` property in package.json: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines

**Comment by Jolg42** [comment]
@jkomyno  [npm](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines) does not enforce anymore the `engines` property by default since "a long time", so we had to have this preinstall check.
