### ISSUE TITLE
Prisma Client: remove `rejectOnNotFound`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19315]
We deprecated this option in 4.0.0 and introduced new APIs as the replacement.

The deprecation warning printed at run time currently states that the feature will be removed in Prisma 5:

```tsx
prisma:warn `rejectOnNotFound` option is deprecated and will be removed in Prisma 5. Please use `prisma.model.findUniqueOrThrow` method instead
```

- [ ] Remove code
- [ ] Remove warning
- [ ] Remove tests
- [ ] prisma/docs#4999
- [ ] Rename issue about update and delete (see [slack](https://prisma-company.slack.com/archives/C03MRGP7WLB/p1686155501856429)) https://github.com/prisma/prisma/issues/10142
- [ ] Release notes draft, see https://github.com/prisma/prisma/releases/tag/4.0.0

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/12159

**Comment by Jolg42** [comment]
This is now complete. (Except for docs which are tracked in their own issue)

Note that this was split from the PR and not included in Prisma 5
https://github.com/prisma/prisma/pull/20097
