### ISSUE TITLE
Prisma Client: remove "beforeExit" hook from LibraryEngine/DataProxyEngine

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19312]
```tsx
prisma.$on('beforeExit', () => {
   doSomething()
})
```

Notes:
Binary engine uses process exit hooks to shut down child process automatically and exposes `beforeExit` event so users still have an opportunity to handle process exit.
Library engine does not need to subscribe to signals/process exit events to function, but still does so it can expose this event. If this event is used, engine instance can not be GCed correctly. Since there is no need to listen to process exit for our own needs, we can remove this event from our API and ask users to setup process handlers themselves instead - data proxy engine already does that.

- [ ] prisma/docs#4998
- [ ] Remove code from LibraryEngine
- [ ] Also remove TODO & `NotImplementedYetError` from DataProxyEngine: see `./packages/engine-core/src/data-proxy/DataProxyEngine.ts`
- [ ] Replace by "only implemented in Binary engine"?
- [ ] Remove/update tests
- [ ] Release notes draft
- [ ] Anything else?

**Comment by aqrln** [comment]
It's a bit unclear to me what behaviour we want on the type level. We know which engine type was specified in the schema at generation time, but it can be changed without regenerating the client (and the types) by setting an environment variable.

So, do we keep the event in the types regardless of the engine type and just make this a no-op (or a warning) at run time for the library engine?

**Comment by Jolg42** [comment]
Indeed, that sounds like a good option to make it a warning at run time to me.
