### ISSUE TITLE
Simplify setup for TypeScript project

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1931]
When writing reproductions or testing stuff, I usually fall back to use .js because I never know exactly what I need to create for TS to work.

Is there a CLI to simplify that? Or did we document that somewhere? (Should we maybe add a command to our CLI to add that? Maybe a (undocumented) param to init?)

**Comment by pantharshit00** [comment]
Personally, right now I create this `tsconfig.json`:
```
{
  "compilerOptions": {
    "lib": ["esnext"]
  }
}
``` 

and add `@type/node` to dependencies and run scripts using `ts-node` for reproductions.

**Comment by pantharshit00** [comment]
But I agree if CLI can do these things for us, that would make my life a bit easier. I was already planning to write a bash script for personal use but this would solve the problem in a better way.

**Comment by janpio** [comment]
Does not seem to be a problem for users.
