### ISSUE TITLE
Prisma schema type names can conflict in some specific case, producing unexpected results

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19320]
The Schema Builder in the Query Engine is responsible for generating output & input types that will eventually be rendered as TS types. All types are given a name. We’re unfortunately sometimes running into name conflicts which breaks the schema and makes the Client generate an incorrect API.

See https://www.notion.so/prismaio/Schema-type-names-conflicts-6ed243a56ac4455f876c28bc5dcd4a74

## Problem 1: Field names are case-sensitive
```
model User {
  user_id    Int     @id @default(autoincrement())
  // --- This is the issue below ---
  posts Post[]
  Posts Test[]
}

model Post {
  post_id Int @id
  author   User   @relation(fields: [authorId], references: [id])
  authorId Int
}

model Test {
  test_id Int @id
  author   User @relation(fields: [authorId], references: [id])
  authorId Int
}
```

Notice the fields User.posts and User.Posts and how they point to different models (Post & Test respectively). Yet, because we capitalize field names, both fields will have, for instance, the following type generated: UserUpdateWithoutPostsInput (this is not the only one).

## Problem 2: Model names are case-sensitive 

Examples

**********************1 Distinct**********************
Type name: `{Model}ScalarFieldEnum`

```tsx
model test {
  id Int @id
  a String
}

model Test {
  id Int @id
  b String
}
```

```tsx
await prisma.Test.findMany({ distinct: [id, a] })
//                                    ^^^^^^^
//                                    error: expects fields from `test` model
```

******2 To-many filters******

Type name: `{Model}ListRelationFilter`

```tsx
model User {
  id Int @id

  Tests Test[]
  tests test[]
}

model Test {
  id Int    @id
  a  String

  userId Int?
  user   User? @relation(fields: [userId], references: [id])
}

model test {
  id Int    @id
  b  String

  userId Int?
  user   User? @relation(fields: [userId], references: [id])
}
```

```tsx
await prisma.user.findMany({
  where: {
    tests: { every: { b: "hello!" } }
    //              ^^^^^^^^^^^^^^^
    //              error: expects fields from `Test` model
  }
})
```

**********************************3 To-one filters**********************************

Type name: `{Model}RelationFilter`

```tsx
model User {
  id Int @id

  Test Test?
  tests test?
}

model Test {
  id Int    @id
  a  String

  userId Int? @unique
  user   User? @relation(fields: [userId], references: [id])
}

model test {
  id Int    @id
  b  String

  userId Int? @unique
  user   User? @relation(fields: [userId], references: [id])
}
```

```tsx
await prisma.user.findMany({
  where: {
    tests: { is: { b: "hello!" } }
    //           ^^^^^^^^^^^^^^^
    //           error: expects fields from `Test` model
  }
})
```

****************************************4 To-one & to-many **********composite********** filters (same as above)**

Type names: `{Composite}CompositeFilter` & `{Composite}ListFilter`

******************************5 And more…******************************

## Solution

TODO
- [ ] Add schema validation errors and tests

Related: https://github.com/prisma/prisma/issues/6446

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
