### ISSUE TITLE
Error with Requesting Prisma engine file: `reason: unable to get local issuer certificate`

### ISSUE THREAD

**Issue by johnbumgardner** [prisma/prisma#19323]
### Bug description

Trying to run npx prisma generate and getting 

Error: request to https://binaries.prisma.sh/all_commits/c875e43600dfe042452e0b868f7a48b817b9640b/linux-musl/libquery_engine.so.node.gz.sha256 failed, reason: unable to get local issuer certificate

### How to reproduce

`npx prisma generate`

get 
```
#0 3.688 Error: request to https://binaries.prisma.sh/all_commits/d9a4c5988f480fa576d43970d5a23641aa77bc9c/linux-musl/libquery_engine.so.node.gz.sha256 failed, reason: unable to get local issuer certificate
------
failed to solve: process "/bin/sh -c npx prisma generate" did not complete successfully: exit code: 1
```

### Expected behavior

would expect npx prisma generate to work correctly and generate mappings

### Prisma information

```generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v17.6.0

### Prisma Version

```
4.14.1
```

**Comment by janpio** [comment]
Can you download that file manually via your browser?
Did you install Prisma successfully on that machine before?
Can you run this command when you set the env var `PRISMA_ENGINES_MIRROR=https://downloads.prisma.sh/`?

**Comment by johnbumgardner** [comment]
yes,
yes, on both my local computer and the staging environment this was caught on
thus didnt resolve it.

**Comment by miguelff** [comment]
This is an issue validating the SSL certificate from node, which is rejecting the certificate as invalid. This happens most frequently when certificates are self-signed.

However, the certificate for `binaries.prisma.sh` is valid and signed by a trusted CA authority.

The main reason why the validation error you are seeing might be happening is that node cannot verify the authenticity of the certificate, this can happen if either (to my knowledge):

* there’s a proxy/firewall in the middle, is there one? or are you accessing through a VPN?
 (see https://stackoverflow.com/a/65833968/320151)

* Node is not picking up correct certificates location (see https://stackoverflow.com/a/73535165/320151)

A momentary workaround is to disable SSL validation in node using: `export NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by johnbumgardner** [comment]
i included the following lines in our dockerfile for anyone experiencing the same issues.

this resolved our issue

```dockerfile
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN npm config set strict-ssl false
```

**Comment by khanmsalman** [comment]
i also stuck in this type error
