### ISSUE TITLE
Sequential and interactive transactions have different limits on number of statements allowed.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [prisma/prisma#19345]
### Bug description

Experimentally, I've noticed that the interactive `$transaction` API limits the amount of queries before it'll forcefully end the transaction. Roughly pseudocoding:

```ts
const arrayWith3000Records = [...Array(3000)].map(i => i)
await db.$transaction(async (tx) => {
  for (const i of arrayWith3000Records) {
    await tx.someModel.upsert({
      where: { id: i },
      update: { text: i },
      create: { text: i },
    });
  }
});
```

This will error out: 

```
  code: 'P2028',
  clientVersion: '4.13.0',
  meta: { error: 'Transaction already closed: Could not perform operation.' }
```

Doing this with a sequential transaction (`$transaction([...])`) does not seem to have this limit, it was fine with 3000 records, it was doing fine with 10k (didn't test beyond that).

Is this expected? If so, what do you think about me adding a note to the docs clarifying that nuance?

### How to reproduce

See example above

### Expected behavior

Both approaches have the same behavior: either they're ok with X records, or they both error out and close the transaction early.

### Prisma information

Not really relevant, but a basic case:

```
model SomeModel {
  id String @id
  text String
}
```

### Environment & setup

- OS: macOS 12.4
- Database: CRDB 22.2
- Node.js version: 16.20

### Prisma Version

```
prisma                  : 4.13.0
@prisma/client          : 4.13.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.13.0-50.1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Default Engines Hash    : 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Studio                  : 0.484.0
Preview Features        : tracing, extendedWhereUnique
```

**Comment by andyjy** [comment]
> there is a limit of time your interactive transaction takes, which is 2000 ms by default, although you can change and increase it by passing the `maxWait` option in the second argument of `prisma.$transaction` (see https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions).

@aqrln when you mentioned `maxWait` above, did you mean `timeout`?

from https://www.prisma.io/docs/concepts/components/prisma-client/transactions#transaction-timing-issues:
> `maxWait`: The maximum amount of time Prisma Client will wait to acquire a transaction from the database. The default value is 2 seconds.
> `timeout`: The maximum amount of time the interactive transaction can run before being canceled and rolled back. The default value is 5 seconds.

Ultimately I struggle to understand what is meant by "acquire a transaction from the database" - potentially something to clarify in https://github.com/prisma/docs/issues/4786

(Also unclear to me how `maxWait` overlaps with / differs from the connection `pool_timeout` for the wait to retrieve a connection from the Prisma connection pool, unrelated to the use of transactions).

Happy to create another docs issue if helpful. First checking whether I'm just mistaken about your comment above. Thanks!

**Comment by aqrln** [comment]
@andyjy 

> @aqrln when you mentioned maxWait above, did you mean timeout?

Yes, absolutely, thanks for catching this and sorry for the confusion.

> Also unclear to me how maxWait overlaps with / differs from the connection pool_timeout for the wait to retrieve a connection from the Prisma connection pool, unrelated to the use of transactions

This is a good question which I can’t immediately answer off the top of my head — perhaps people working on the query engine could though. This would be very nice to clarify and document.
