### ISSUE TITLE
@prisma/client/edge does not support other databases protocols

### ISSUE THREAD

**Issue by rkacenski** [prisma/prisma#19344]
### Bug description

Hi, while setting up a test project with cloudflare workers + prisma + supabase, I've been unsuccessful using the client/edge.
Only `primsa://` protocol is allowed, preventing the use of `postgres://` with PgBouncer.

This was done following the guides:
https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers
https://www.prisma.io/docs/guides/database/supabase

The issues I encountered: 
`Datasource URL must use prisma:// protocol when --data-proxy is used`
Tried removing that conditional and got this:
`No valid API key found in the datasource URL`

Thanks!

### How to reproduce

1. `npx wrangler init` - setup cloudflare workers project via [guide](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers)
2. `npx prisma init`
3. `npx prisma generate --data-proxy` - only way to generate edge runtime
4. Set db url in wrangler vars following [guide](https://www.prisma.io/docs/guides/database/supabase#specific-considerations)
```
# Connect to Supabase with PgBouncer.
DATABASE_URL="postgres://postgres:__PASSWORD__@db.__YOUR_SUPABASE_PROJECT__.supabase.co:6543/postgres?pgbouncer=true"
# Direct connection to the database. Used for migrations.
DIRECT_URL="postgres://postgres:__PASSWORD__@db.__YOUR SUPABASE_PROJECT__.supabase.co:5432/postgres"
```
5. `npx wrangler dev`
 
Error: `Datasource URL must use prisma:// protocol when --data-proxy is used`

### Expected behavior

Edge runtime should except any connection string, and not parse for api key in url.
Or another runtime should be generated for this use case.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}

model File {
  id Int @id @default(autoincrement())
  companyId Int    @unique
  createdAt DateTime   @default(now())
  fileName String
  displayName String
  fileUrl String
  savedToCloud Boolean   @default(true)
  storageProvider String
  fileType String
  fileSize Int
}
```

```ts
import { PrismaClient } from '@prisma/client/edge'
const prismaConnect = (db_url: string) => new PrismaClient({
	datasources: {
		db: {
			url: db_url,
		}
	}
});

// now let's create a router (note the lack of "new")
const router = Router();

// GET collection index
router.get('/api/files', async (request, env: Env) => { 
	const prisma = prismaConnect(env.DATABASE_URL)
	const files = await prisma.file.findMany()
	return json(files)
})
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL via Supabase
- Node.js version: node 16

### Prisma Version

```
prisma                  : 4.14.1
@prisma/client          : 4.13.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.14.0-67.d9a4c5988f480fa576d43970d5a23641aa77bc9c
Default Engines Hash    : d9a4c5988f480fa576d43970d5a23641aa77bc9c
Studio                  : 0.484.0
```

**Comment by aqrln** [comment]
Please follow the guide at https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers and create a Data Proxy connection string. You need to insert the Supabase URL in your Prisma Data Platform project settings, and use the `prisma://` connection string as the `DATABASE_URL` for your edge client. The `postgres://` connection string that goes to the `DIRECT_URL` env var can only be used by `prisma migrate` (or by the regular Node.js client when not using Cloudlfare Workers).

**Comment by aqrln** [comment]
Actually, on the second thought, now that TCP sockets support in Cloudlfare Workers was announced a few days ago, this could be a valid feature request, so I'll go ahead and mark it as such.

In the meantime, please let us know if you have any questions or help regarding the existing edge client and Data Proxy and their usage with Cloudlfare Workers!

**Comment by rkacenski** [comment]
Thanks @aqrln I ended up using the Data Proxy for the time being, no issue there... and thanks for pushing this feature request. Using TCP sockets on Cloudlfare Workers will be great.

**Comment by morpig** [comment]
```Using TCP sockets on Cloudlfare Workers will be great.```

hope the prisma team will consider direct TCP support for cf workers (considering that data proxy is their revenue-machine business...)

currently data proxy doesn't work for my use case as my postgres DB is hosted way far than the supported data proxy regions.

**Comment by janpio** [comment]
We'll track the request for support of `connect()` to use Cloudflare's TCP sockets directly over at https://github.com/prisma/prisma/issues/19488 now.

I don't anything else from this issue here is needed to be tracked standalone, agree?
