### ISSUE TITLE
Nested Select not working

### ISSUE THREAD

**Issue by shawshankkumar** [prisma/prisma#19347]
### Bug description

This should work:

<img width="506" alt="image" src="https://github.com/prisma/prisma/assets/74819565/8d71e4f7-0001-4710-adac-aa3d7fd20ce2">

But it throws an error like this:

<img width="1221" alt="image" src="https://github.com/prisma/prisma/assets/74819565/b97b24bd-40d5-41f4-869f-27d038a4406e">

### How to reproduce

Try to run a nested select query.

### Expected behavior

It should run, according to the docs.

### Prisma information

  inventory_order_details    Json?   @default("{}") @db.Json

### Environment & setup

- OS: macOS
- Database: postgreSQL
- Node.js version: 14.21.2

### Prisma Version

@prisma/client": "^4.14.0

**Comment by shawshankkumar** [comment]
> Hi @shawshankkumar. I don't think this is supposed to work, and I just double checked our documentation for Json fields and I don't see anything in there that would suggest it should — on the contrary, [it states that it's not currently possible](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#can-you-select-a-subset-of-json-keyvalues-to-return) and links to this feature request: #2431. If there's anything specific in the docs that caused confusion, please let us know so that we could fix that!
> 
> The syntax you tried to use exists for selecting the fields of the other side of a relationship. Is there any reason why the data in `inventory_order_details` is in a Json field and not in its own table? You could make it a table and use one-to-one relation instead, and then this query would work. See https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-one-relations for more details.

Hey @aqrln thanks for the quick reply. It is a json field and not a table because we are not sure of its content and we are not going to run any queries on it, it is just going to be a json dump. Other than that I saw this and thought nested select would work (chat gpt said the same :p)

So I'll tell you the thought process, so I have been using prisma for more than 6 months now but I've never needed to select partial keys in an object, but today I did. So I thought I would just try object.key : true which works in mongo projections. But it didn't work, so I ran a chat gpt query , the result wasn't satisfactory : 
<img width="926" alt="image" src="https://github.com/prisma/prisma/assets/74819565/c2196118-cb4c-403c-a30e-86602e98d76c">


But it gave me an idea that nested select might work. So I google and it took me to this prisma doc page: https://www.prisma.io/docs/concepts/components/prisma-client/select-fields

<img width="742" alt="image" src="https://github.com/prisma/prisma/assets/74819565/cb6d2fcc-45d9-449a-aeed-11821ef1d25e">

I ran with it and it didn't work.

**Comment by aqrln** [comment]
@shawshankkumar 

> But it gave me an idea that nested select might work. So I google and it took me to this prisma doc page: https://www.prisma.io/docs/concepts/components/prisma-client/select-fields

I think this section is pretty clear that it is talking about relations.

It's also possible that it was what ChatGPT "assumed" you meant since that's what people usually mean when they are talking about nested select in the context of Prisma. But, of course, it's also ChatGPT, it often hallucinates the APIs that don't even exist 😄

Please leave an upvote in https://github.com/prisma/prisma/issues/2431 if you need this functionality. In the meanwhile, you can select the whole JSON object and only use the fields in the response you need.

**Comment by shawshankkumar** [comment]
Yessss. I got it pretty late. :P

Thanks for the clarification.
