### ISSUE TITLE
Remove `type` keyword from data model

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#1935]
As we don't _officially_ support type aliases with the `type` keyword at the moment, we should remove the keyword from the data model. Otherwise this can lead to confusions as [here](https://prisma.slack.com/archives/CKQTGR6T0/p1585195048046500).

**Comment by Sytten** [comment]
My bad, I was digging the AST parser. I don't think its highlighted in vscode anyway?

**Comment by pantharshit00** [comment]
This will be a breaking change as I have seen many people using type alias like `type CUID = String @id @default(cuid())`

We should proceed with caution here.

**Comment by janpio** [comment]
This has happened, and `type` is now used for MongoDB composite types / embedded documents: https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/composite-types
