### ISSUE TITLE
Allow setting generator provider via env var

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#19368]
## Problem

Dynamically setting the generator provider is not supported. It can be useful when trying use the Prisma schema as a source of truth and then trying to generate clients from it.

```prisma
datasource db {
  // could be postgresql or mysql
  provider = "sqlite"
  url      = "file:dev.db"
}

generator client {
  provider = env(PROVIDER)
}
```

```
❯ npx prisma generate
Prisma schema loaded from schema.prisma
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Expected a string value, but received literal value `PROVIDER`.
  -->  schema.prisma:8
   |
 7 | generator go {
 8 |   provider = env(PROVIDER)
   |

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 4.14.1
```

## Suggested solution

Support dynamic generator providers by allowing env vars (this would be resolved at generation-time)

## Alternatives

`sed` 😁

## Additional context

https://github.com/prisma/prisma-client-go/issues/835

**Comment by tomhoule** [comment]
What does `env("PROVIDER")` produce? I think it's still not allowed, but the error should be different.

**Comment by steebchen** [comment]
Ah, it does actually work with quotes... thanks 😂
