### ISSUE TITLE
prisma-fmt binary for neovim

### ISSUE THREAD

**Issue by tihomirovkirillcom** [prisma/prisma#19361]
### Discussed in https://github.com/prisma/prisma/discussions/19360

<div type='discussions-op-text'>

<sup>Originally posted by **snikoletopoulos** May 21, 2023</sup>
How can I download or add prisma-fmt to $PATH in order to use it inside NeoVim?</div>

**Comment by CrisDgrnu** [comment]
How did you solved this? I don't know where to find this package too
