### ISSUE TITLE
Is the postgresql 'security_invoker' property supported on views?

### ISSUE THREAD

**Issue by muzzsteak** [prisma/prisma#19384]
I am trying to run this migration but I get the error below. Is security_invoker not supported? Or do I perhaps have the syntax wrong?
```
ALTER VIEW IF EXISTS view_xxxx
SET (security_invoker = true);
```
Error: P3006

```
Migration `20230522152040_alter_view_xxxx` failed to apply cleanly to the shadow database. 
Error:
db error: ERROR: unrecognized parameter "security_invoker"
   0: sql_migration_connector::validate_migrations
           with namespaces=None
             at migration-engine\connectors\sql-migration-connector\src\lib.rs:301
   1: migration_core::state::DevDiagnostic
             at migration-engine\core\src\state.rs:269
```

**Comment by Jolg42** [comment]
After a quick search, I've found that this is a new feature of PostgreSQL v15
https://www.cybertec-postgresql.com/en/view-permissions-and-row-level-security-in-postgresql/
https://mydbops.wordpress.com/2023/03/29/security-invoker-views-in-postgresql-15/

@muzzsteak Could you share your Prisma schema? (at least the datasource and generator blocks).
Do you know which version of PostgreSQL you are using at the moment?

**Comment by Jolg42** [comment]
@muzzsteak Could you try using PostgreSQL v15 since this feature doesn't seem implemented in older versions of PostgreSQL?

**Comment by muzzsteak** [comment]
@Jolg42 yes definitely, will try v15 and report back.
