### ISSUE TITLE
@default(autoincrement())  not working on non id integer fields

### ISSUE THREAD

**Issue by AmitGutpa** [prisma/prisma#1938]
I am having an id field in my model that is not primary but I want it to be a autoincrement field. So, for this, I just added `@default(autoincrement())` in the front of my id field. But this is not working id is not autoincrementing and even I am not able to create if I did not explicitly pass the id filed. 
This is my model. 

```prisma
model Mail {
    id Int   @default(autoincrement())
    createdAt  DateTime   @default(now())
    updatedAt  DateTime   @updatedAt
    body String
    to String
    from String
    subject String
    messageId String @id
    date DateTime
    attachments Attachment[]
}
````

**Comment by ChristophDietrich** [comment]
You should use it like:
```
model User {
    id                      Int                 @id @default(autoincrement())
    email                   String              @unique
    name                String
}
```

**Comment by AmitGutpa** [comment]
@ChristophDietrich That's the issue. I don't want to use id as a primary key. If you see in my model I want to use messageId as the primary key. In the docs, it is mentioned that without @id we can use @default(autoincrement()) but without @id @default(autoincrement()) is not working.

**Comment by ChristophDietrich** [comment]
@AmitGutpa 

Try this:

```
model Mail {
    id Int   @id @default(autoincrement())
    createdAt  DateTime   @default(now())
    updatedAt  DateTime   @updatedAt
    body String
    to String
    from String
    subject String
    messageId String @unique
    date DateTime
    attachments Attachment[]
}
```

Then you are sure id is auto increment and messageId is like the primary key, because its unique.
But the generation of the messageId is on your site ... or your mail server then.

**Comment by AmitGutpa** [comment]
@ChristophDietrich I cannot use messageId like this because I want to use messageId as foreign keys in another relation.

**Comment by pantharshit00** [comment]
I can confirm this bug. Right now you are unable to use sequences in the query engine for any non id integer field even though migrate enforces it on a database level: 
<img width="697" alt="image" src="https://user-images.githubusercontent.com/22195362/77668902-09565e00-6faa-11ea-9dc3-80baf38b27ed.png">


Reproduction:
1. Migrate the following datamodel using migrate:
```prisma
model Mail {
    nonId Int   @default(autoincrement())
    createdAt  DateTime   @default(now())
    updatedAt  DateTime   @updatedAt
    body String
    to String
    from String
    subject String
    messageId String @id
    date DateTime
}	
```
2. Generate the client and run the following query:
```ts
const { PrismaClient } = require("@prisma/client");
const crypto = require("crypto");

const prisma = new PrismaClient();

async function main() {
  const data = await prisma.mail.create({
    data: {
      body: "test",
      to: "string",
      from: "string",
      subject: "string",
      date: new Date().toISOString(),
      messageId: crypto.randomBytes(10).toString("hex"),
    },
  });
}

main();
```

**Comment by pantharshit00** [comment]
Error thrown:
```
(node:95571) UnhandledPromiseRejectionWarning: Error:
Invalid `const data = await prisma.mail.create()` invocation in
/Users/harshit/code/reproductions/issue-1938/index.js:7:34

   3
   4 const prisma = new PrismaClient();
   5
   6 async function main() {
→  7   const data = await prisma.mail.create(

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: NullConstraintViolation { constraint: Fields(["id"]) } })
    at PrismaClientFetcher.request (/Users/harshit/code/reproductions/issue-1938/node_modules/@prisma/client/runtime/index.js:1:47490)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:95571) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:95571) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by mohe2015** [comment]
Does anybody have a workaround?

**Comment by mohe2015** [comment]
I know most of you do work on this in their free-time but is there any change this gets fixed soon? It's really annoying as there is no real practical workaround AFAIK. I could also add a bug bounty if you can provide me a recommended platform (if there is one). It won't be much but may still help resolve this more quickly.

**Comment by pantharshit00** [comment]
We have added the candidate label so this will considered for next release now. Please wait here now.

**Comment by tomhoule** [comment]
Linking corresponding engines issue: https://github.com/prisma/prisma-engines/issues/903

**Comment by do4gr** [comment]
As per the linked investigation issue (https://github.com/prisma/prisma-engines/issues/903), this would work on Postgres and MySQL but would not work on SQLite. On MySQL the auto_increment column would also need to have an index defined. 

We need to decide whether we should allow this if a supporting db is specified.

**Comment by jg-coetzee** [comment]
I still have this issue on version 4

sort            Int          @default(autoincrement())

please help,

**Comment by daniel-nagy** [comment]
I just experienced a similar problem. I have a column defined like this:

```prisma
model Foo {
  index Int @unique @default(autoincrement())
}
```

When using prisma client to create a new row I get a unique index constrain violation.

```typescript
await client.foo.create({
  data: {
    ...
  }
});
```

```
PrismaClientKnownRequestError: 
Invalid `prisma.post.create()` invocation:


Unique constraint failed on the fields: (`index`)
```

I have to manually specify the `index` field, it is not auto-incremented. I am using Postgres 15.

**Comment by wiemann** [comment]
+1

**Comment by LuzPerezM** [comment]
I have the same issue as  @daniel-nagy  

`Invalid `prisma.tablename.create()` invocation:

Unique constraint failed on the fields: (`code`)`

and in the model:

` code    Int          @unique @default(autoincrement())`
