### ISSUE TITLE
bug: `PrismaClient` v4.13+ breaks `process.emit("SIGINT")`

### ISSUE THREAD

**Issue by DannyNemer** [prisma/prisma#19387]
### Bug description

Initializing `PrismaClient` v4.13 adds an event listener for `"SIGINT"` and `"SIGTERM"` that does not correctly handle the signals when emitted, yielding the following error:
  ```
  RangeError [ERR_OUT_OF_RANGE]: The value of "code" is out of range. It must be an integer. Received NaN
  ```

Prisma's failed handling of these signals interferes with other signal handlers in our system because the above Prisma error kills the process before other handlers run for the same signal.

### How to reproduce

```ts
import { PrismaClient } from "@prisma/client";
new PrismaClient();
process.emit("SIGINT");
```

### Expected behavior

Running a script with the following code improperly kills the process:

```ts
import { PrismaClient } from "@prisma/client";
new PrismaClient();
process.emit("SIGINT");
```

<img width="780" alt="image" src="https://github.com/prisma/prisma/assets/170023/7ac30564-24b2-44f1-b575-33a0584a3107">

---

But if you swap the two lines, you see that the error only occurs after `PrismaClient` is instantiated and adds its signal handlers.

```ts
import { PrismaClient } from "@prisma/client";
process.emit("SIGINT");
new PrismaClient();
```

<img width="692" alt="image" src="https://github.com/prisma/prisma/assets/170023/d05ae471-b7f6-49bb-97ce-52ac5334c95c">

### Prisma information

This issue is independent of the schema.

### Environment & setup

- OS: macOS: 13.3.1
- Database: PostgresSQL 15.3
- Node.js version: v20.1.0

### Prisma Version

```
prisma                  : 4.14.1
@prisma/client          : 4.14.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.14.0-67.d9a4c5988f480fa576d43970d5a23641aa77bc9c
Default Engines Hash    : d9a4c5988f480fa576d43970d5a23641aa77bc9c
Studio                  : 0.484.0
```

**Comment by SevInf** [comment]
Prisma expects system signal events to obey the contract, described in [Node documentation](https://nodejs.org/api/process.html#signal-events), in particular, receive a signal as first argument. If you hijacking those events and emitting them manually instead of relying on Node emitting the event, make sure to do it in exactly the same way Node itself does it:

```js
process.emit('SIGINIT', 'SIGINT')
```

**Comment by DannyNemer** [comment]
@SevInf Thank you! This fixed our issue. If you are curious, we only use this code in our tests for our event handling. We rely on Node to emit the event in production.
