### ISSUE TITLE
prisma client throws issues

### ISSUE THREAD

**Issue by Prasiddhidahal** [prisma/prisma#19395]
### Bug description

error in auth 

### Expected behavior

when i am about to login prisma client throws error

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```
@prisma/client@4.14.0

**Comment by tomhoule** [comment]
Hi! Thank you for opening an issue. Do you have more details on what errors you are running into? Is it unexpected because you are sure of the login credentials?

**Comment by rajanshresth** [comment]
Hey, Can you provide more information about the issue?

**Comment by millsp** [comment]
Gentle ping @Prasiddhidahal, could you please provide us with the missing information so we can take a look? Thanks.

**Comment by millsp** [comment]
We haven't heard back about this issue, so we'll close it for now as we need a few more details to be able to dig into this problem. Don't hesitate to add more details in a new comment, and we'll be happy to reopen the issue. Thank you! :pray:
