### ISSUE TITLE
Support datasource-specific attributes

### ISSUE THREAD

**Issue by newtack** [prisma/prisma#194]
**Problem**

Databases like Postgres are incredibly feature-rich. Exposing all of those features would clutter up the schema for databases that do not support these features.

**Possible Solution**

We introduce datasource-specific attributes `@pg.check(...)`, which allow more advanced features while making it clear that this is datasource-specific and may make it harder to switch databases.

> **Original Question**
> 
> Where are the pg attributes documented? For example I want to specify the maximum length of a string or customize the type definition for postgres, it's hard to find out what is available.

**Comment by pantharshit00** [comment]
We have this in the datamodel specification but this is yet to be implemented.

You can find the specification: https://github.com/prisma/specs/tree/master/prisma-schema#type-specifications

**Comment by michalchmura** [comment]
> We have this in the datamodel specification but this is yet to be implemented.
> 
> You can find the specification: [prisma/specs:prisma-schema@`master`#type-specifications](https://github.com/prisma/specs/tree/master/prisma-schema#type-specifications) [](/prisma/specs/tree/HEAD@{2019-07-22T09:28:18Z}/prisma-schema#type-specifications)

The updated link is: [prisma/specs:prisma-schema-language@`master`#type-specifications](https://github.com/prisma/specs/tree/master/prisma-schema-language#type-specifications) 👍

**Comment by janpio** [comment]
What is the `docs` part here @pantharshit00? Isn't this just a feature request for a feature that is already specced, but didn't get implemented yet?

**Comment by pantharshit00** [comment]
@janpio 

The specific directives are also not documented(https://github.com/prisma/prisma2/tree/master/docs) so I added that label as well so that once they are implemented we need to document them as well.

**Comment by matthewmueller** [comment]
Stepping back to address the problem for newcomers.

**Problem:**

Databases like Postgres are incredibly feature-rich. Exposing all of those features would clutter up the schema for databases that do not support these features.

**Possible Solution**

We introduce datasource-specific attributes `@pg.check(...)`, which allow more advanced features while making it clear that this is datasource-specific and may make it harder to switch databases.

**Comment by albertoperdomo** [comment]
This is now supported via native types, including a catch-call notation for types we don't yet support.
The feature request described in this issue is pretty generic, so I am closing it.

For native types beyond the supported ones, we would like to have specific types requested (Postgis, Interval, etc.). for other features, e.g. database views, or stored procedures specific feature requests also welcome.

Make sure to check out https://www.prisma.io/docs/concepts/components/preview-features/native-types
