### ISSUE TITLE
Support for Neon Serverless Driver for Postgres

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#19409]
> our serverless PostgreSQL driver, [@neondatabase/serverless](https://www.npmjs.com/package/@neondatabase/serverless), connects to Neon databases from Cloudflare Workers and other environments supporting WebSockets, such as web browsers.

https://neon.tech/blog/serverless-driver-for-postgres
https://www.npmjs.com/package/@neondatabase/serverless

**Comment by immjs** [comment]
Hello, it's been a month, is there anything new yet? also hoping to bump through this comment

**Comment by janpio** [comment]
No. If there were news, there would be a comment about news - we wouldn't hide it. Sorry.

**Comment by janpio** [comment]
Hey, we at Prisma have been working on this for the past few weeks. Soon, we'll have something to share and test!
If you are interested in helping us, please respond to this super short survey and leave your email address so we can get in touch with instructions: https://pris.ly/survey/driver-adapter-neon Thanks.

**Comment by ludalex** [comment]
I'm wondering if using the Neon or Plantescale drivers will allow us to run Prisma on edge functions. 

I did a little experiment and it's not working. Neon driver is working great though, on regular serverless functions.

**Comment by janpio** [comment]
Not quite yet, but is indeed a building block. We are actively working on it though, so expect news soon.

 (If you have not yet, respond to our survey I linked above and select the Edge Function providers you are interested in - we'll send out an Early Access version when we have something useful.)

**Comment by janpio** [comment]
I have good news: 

We released support for using Neon's serverless driver with Prisma Client with our [latest release 5.4.0](https://github.com/prisma/prisma/releases/tag/5.4.0) and just published a blog post that introduces and explains how it works and can be used: https://www.prisma.io/blog/serverless-database-drivers-KML1ehXORxZV! 

[![image](https://github.com/prisma/prisma/assets/183673/c5ded781-a05d-4548-b08b-ed07268db9db)](https://www.prisma.io/blog/serverless-database-drivers-KML1ehXORxZV)


If you try it, as it's behind the preview feature flag `driverAdapters` you can leave feedback in this discussion: https://github.com/prisma/prisma/discussions/21346

**Comment by andrelandgraf** [comment]
Are Serverless Database Drivers also coming to Prisma's edge client?

**Comment by janpio** [comment]
Yes @andrelandgraf: https://github.com/prisma/prisma/issues/21394 And [more](https://github.com/prisma/prisma/issues/19488), depending on the edge function platform you are using.
