### ISSUE TITLE
Wrong versions of binaries are downloaded during generation

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#1942]
## Bug description
Wrong versions of binaries are downloaded during generation

## How to reproduce
I've set up a repository with a detailed README that precisely describes and demonstrates the problem. It is a fairly long, but the problem is pretty hard to describe, so please read through the whole thing and let me know if anything is unclear:
https://github.com/madebysid/prisma2-client-binaries

## Expected behavior
A proposed solution is included in the README.

## Prisma information 
Irrelevant

## Environment & setup
Irrelevant

Also, here is this problem demonstrated in the wild: https://github.com/prisma/studio/issues/391

**Comment by janpio** [comment]
The solution here seems easy enough: The SDK (`@prisma/sdk`) needs to pin the binary the same way the CLI does. There might be parameters to override that if really wanted - but probably not necessary to implement that until someone asks. Agree?

**Comment by madebysid** [comment]
@janpio That's exactly right. Basically move the pinning down the stack from `prisma2` to `@prisma/sdk`.

I agree that once that is implemented, overriding this version will not be useful (or required even) for most cases, so we can sideline that until a use case arises.

> Maybe just a bug that this is not being used correctly when downloading the binaries?

Hmm, perhaps, I'll let the authors take a look though, I don't know about SDK internals too much!

**Comment by janpio** [comment]
> Basically move the pinning down the stack from `prisma2` to `@prisma/sdk`.

To me CLI and SDK were two parallel things for now - maybe that was a misunderstanding.

**Comment by timsuchanek** [comment]
Thanks for reporting! We already pinned the version for a part of the sdk, but forgot to pin all parts of it. I just fixed it, you can try it out in the latest alpha.
