### ISSUE TITLE
 PrismaClient is unable to be run in the browser.

### ISSUE THREAD

**Issue by Prasiddhidahal** [prisma/prisma#19425]
### Bug description

Error: PrismaClient is unable to be run in the browser. //   prisma = global.prisma;
  12 | // }
> 13 | prisma = new PrismaClient();
     |         ^
  14 | 
  15 | export default prisma;

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by morpig** [comment]
it's not possible to run prisma in frontend/browser

**Comment by Jolg42** [comment]
@Prasiddhidahal It looks like you didn't provide most information in the description template in this issue. Without more information, we won't be able to help you. Could you fill the info in the description?

**Comment by rickyl3aks** [comment]
ive got the same problem, ive created a file named db.ts for using prisma globally, thats whats inside
```
 import { PrismaClient } from "@prisma/client";

const globalForPrisma = global as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: ["query"],
  });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;

```
i am trying to get the data back in my browser with
```
 export const getServiceSideProps: GetServerSideProps = async () => {
  const notes = await prisma.note.findMany({
    select: {
      title: true,
      id: true,
      content: true,
    },
  });

  return {
    props: {
      notes,
    },
  };
};
```
 but im receiving the same error **Error: PrismaClient is unable to be run in the browser.**

#Environment & setup

- OS: Linux
- database: sqlite
- Node: v18.16.0

**Comment by Jaival** [comment]
I am having the same issue with NextJS 13 app router.
![image](https://github.com/prisma/prisma/assets/34303559/8d5ce60b-48fc-44a9-b4f2-35fadc20077c)

schema.prisma
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

model User {
  id         String  @id @default(cuid())
  name       String
  email      String? @unique
  url        String?
  contact    Int?
  aboutMe    String
  image      String?
  clerk_id   String  @unique
  attributes Json?
}
```

client.ts (same folder as schema.prisma)
```
import { PrismaClient } from '@prisma/client';
const globalForPrisma = global as unknown as { prisma: PrismaClient };
export const prisma = globalForPrisma.prisma || new PrismaClient();
if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;
```

createUser.ts
```
import { prisma } from '@/prisma/client';
import { Prisma } from '@prisma/client';

export async function createUser(user: Prisma.UserCreateInput){
  try {
    await prisma.user.create({ data: user })
    console.log('try')
  } catch (error) {
    console.log(error)
  }
}
```

**Comment by rajanshresth** [comment]
Why don't you create an API endpoint first and then use it in a client component or server component?

**Comment by Jaival** [comment]
@rajanshresth your idea worked. Thank you.

**Comment by janpio** [comment]
Closing for now. If you can provide more information @Prasiddhidahal, please open a new issue. Thank you.
