### ISSUE TITLE
The solution to the discussion gives a "Foreign key constraint failed on the field: ..." error when I try to connect an existing record referenced by the bookId field. Connecting a book while creating a Like object gives me a "Foreign key constraint failed on the field: like_comment_fk (index)`" error and vice-versa

### ISSUE THREAD

**Issue by aca123321** [prisma/prisma#19430]
### Discussed in https://github.com/prisma/prisma/discussions/11108

<div type='discussions-op-text'>

<sup>Originally posted by **shiminjia** January 12, 2022</sup>
```prisma
model Like {
  id        String   @id @default(cuid())
  userId    String
  bookId    String  
  ...
  book      Book?     @relation(fields: [bookId], references: [id], name: "book") 
  comment   Comment?  @relation(fields: [bookId], references: [id], name: "comment") 

  @@index([slug])
}
```
please notice this. there are two relationships about `bookId`
```prisma
  book      Book?     @relation(fields: [bookId], references: [id], name: "book") 
  comment   Comment?  @relation(fields: [bookId], references: [id], name: "comment") 
```

ERROR：Error parsing attribute "@relation": The given constraint name `Like_bookId_fkey` has to be unique in the following namespace: global for foreign keys. Please provide a different name using the `map` argument.

Is it possible to create multiple relationships  to the same field `bookId` ?</div>

**Comment by tomhoule** [comment]
I haven't looked into this super in depth, but have you tried

```prisma
  comment   Comment?  @relation(fields: [bookId], references: [id], name: "comment", map: "comment")
```

(the map argument, at the end)

?

**Comment by aca123321** [comment]
yep, using two or more such relations which reference the same field gives you a foreign key constraint error when you try to create/connect a comment, book.

**Comment by tomhoule** [comment]
Ah, sorry did not understand that at first.

**Comment by SevInf** [comment]
@aca123321 Could you share Prisma Client query you execute when you are getting this error? Thank you!

**Comment by SevInf** [comment]
Hey @aca123321 ,

Did you get a chance to have a look at my previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by SevInf** [comment]
Hey @aca123321 ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
