### ISSUE TITLE
Update Prisma 1 docs to link to Prisma 2 docs 

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1948]
The existing Prisma 1 docs need an entry "Prisma 2" in the dropdown.

At the same time it would make sense to replace "Prisma" with "Prisma 1" in the normal docs content.

**Comment by 2color** [comment]
That's tricky based on the way the dropdown works now. Besides, local builds don't really work and this will require rebuilding all old versions which takes an hour. 

We added a banner at the top for Prisma 2 docs in addition to a header link:

<img width="1124" alt="Screenshot 2020-04-23 at 11 37 51" src="https://user-images.githubusercontent.com/1992255/80084279-f27a3b80-8556-11ea-81e4-324cfd6eec80.png">


Out of pragmatism, I'd suggest dropping this.

**Comment by janpio** [comment]
Yeah, with the header link and the banner that should be prominent enough.
