### ISSUE TITLE
`Error: PrismaClient is unable to be run in the browser.`

### ISSUE THREAD

**Issue by hohogpb** [prisma/prisma#19500]
### Bug description

use prisma in next.js 13.4.4 middleware. give this error
**Error: PrismaClient is unable to be run in the browser.**
![微信截图_20230529214419](https://github.com/prisma/prisma/assets/6960725/4ef9676d-e03d-4269-bb8c-1b03adbdd87a)

### How to reproduce

create a next.js (13.4.4) project
init prisma 
create a middleware.ts file, import prisma 
see error

### Prisma information

```prisma
// Add your schema.prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

// 用户
model User {
  id       Int       @id @default(autoincrement())
  username String    @unique
  password String
  disable  Boolean?
  realname String?
  avtar    String?
  gender   String?
  email    String?
  phone    String?
  birthday DateTime?
}
```

```ts
// prisma.ts
import { PrismaClient } from "@prisma/client";

console.log("what fuck");

const globalForPrisma = global as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ?? new PrismaClient({ log: ["query"] });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;

```

```ts
// middleware.ts
import { NextResponse } from "next/server";
import type { NextRequest, NextFetchEvent } from "next/server";
import { prisma } from "./prisma/prisma";

export function middleware(request: NextRequest, event: NextFetchEvent) {
  const aUser = prisma.user.findFirst();
  console.log(aUser);

  return NextResponse.next();
}

export const config = {
  matcher: ["/admin/:path*"],
};
```

### Environment & setup

- OS: Window11 
- Database: SQlite 
- Node.js version:v18.16.0 

### Prisma Version

```
prisma                  : 4.14.1
@prisma/client          : 4.14.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.14.0-67.d9a4c5988f480fa576d43970d5a23641aa77bc9c
Default Engines Hash    : d9a4c5988f480fa576d43970d5a23641aa77bc9c
Studio                  : 0.484.0
```

**Comment by rajanshresth** [comment]
First create API endpoint and use it the client component.

**Comment by hohogpb** [comment]
> 

no effect

**Comment by hohogpb** [comment]
> First create API endpoint and use it the client component.

no effect

**Comment by rajanshresth** [comment]
Can you provide a GitHub project repo link if it is public??

**Comment by VictorhMalheiro** [comment]
I have the same problem, I tried to follow a solution presented in the documentation but it didn't work for me either.
Possible solution link (which didn't work): [Best practice for instantiating PrismaClient with Next.js](https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices)

## Error presented to me:
![image](https://github.com/prisma/prisma/assets/38863412/4d2dae7e-0a27-4d67-b66a-1f6a916b7771)

## My code with Next
```ts
export const getServerSideProps: GetServerSideProps = async () => {
  const usuarios = await prisma.usuario.findMany()

  const dataUsers = usuarios.map((usuario) => {
    return {
      nome: usuario.nome,
      email: usuario.email,
      senha: usuario.senha,
      tipo: usuario.tipo,
    }
  })

  return {
    props: {
      dataUsers,
    },
  }
}
```

## Recommended solution in Prisma documentation - [Link](https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices)

```ts
import { PrismaClient } from '@prisma/client'

const globalForPrisma = global as unknown as {
  prisma: PrismaClient | undefined
}

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: ['query'],
  })

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma

```

**Comment by poison** [comment]
Looks like https://github.com/vercel/next.js/discussions/40416#discussioncomment-3613207, where [icyJoseph](https://github.com/icyJoseph) explains you can't use prisma in the middleware. I solved it myself by creating an API call that does the database interaction, and returns the data as a JSON response, and use fetch() to that API call in the middleware

**Comment by hohogpb** [comment]
> Looks like [vercel/next.js#40416 (comment)](https://github.com/vercel/next.js/discussions/40416#discussioncomment-3613207), where [icyJoseph](https://github.com/icyJoseph) explains you can't use prisma in the middleware. I solved it myself by creating an API call that does the database interaction, and returns the data as a JSON response, and use fetch() to that API call in the middleware

can't call prisma or other dbtool like sequelize in middleware is really feel bad!

**Comment by VictorhMalheiro** [comment]
> Looks like [vercel/next.js#40416 (comment)](https://github.com/vercel/next.js/discussions/40416#discussioncomment-3613207), where [icyJoseph](https://github.com/icyJoseph) explains you can't use prisma in the middleware. I solved it myself by creating an API call that does the database interaction, and returns the data as a JSON response, and use fetch() to that API call in the middleware

Did you make an API, still internally in NextJS as a Monorepo or did you have to make an external API?

**Comment by poison** [comment]
> > Looks like [vercel/next.js#40416 (comment)](https://github.com/vercel/next.js/discussions/40416#discussioncomment-3613207), where [icyJoseph](https://github.com/icyJoseph) explains you can't use prisma in the middleware. I solved it myself by creating an API call that does the database interaction, and returns the data as a JSON response, and use fetch() to that API call in the middleware
> 
> Did you make an API, still internally in NextJS as a Monorepo or did you have to make an external API?

I created a file in `src/app/api/user/route.ts` which contains something like this:
```
import { notFound } from 'next/navigation'
import { NextRequest, NextResponse } from 'next/server'
import { getToken } from 'next-auth/jwt'

import { db } from '@web/registry'

export const GET = async (request: NextRequest) => {
  const token = await getToken({ req: request })
  if (!token || !token.sub) {
    return new NextResponse('Unauthorized', { status: 403 })
  }

  const user = await db().user.findUnique({ where: { id: BigInt(token.sub) } })
  if (!user) {
    return notFound()
  }

  return NextResponse.json({
    user: {
      id: user.id.toString(),
      name: user.name,
      email: user.email,
      image: user.image,
    },
  })
}
```

I have a file `registry.ts` which contains my singleton to fetch my prisma adapter (so I only have 1 connection). This is what the db() function does, it returns my database adapter (`= new PrismaClient()`), but YMMV.

Then simply call the `fetch()` function in your middleware to request this API route and get the data.

**Comment by Aleksey-Danchin** [comment]
So, that we can't use PrismaClient in the middleware.ts file becaouse of prisma or NextJS?

**Comment by Hyukay** [comment]
I got the same issue with next.js 13.4.4 as well and I am not using prisma in my middleware.ts. Even if I did and removed it I would still encounter the issue.

**Comment by hohogpb** [comment]
> So, that we can't use PrismaClient in the middleware.ts file because of prisma or NextJS?

it seems to be the next.js use edge runtime in middleware, but the prisma has not fully compatible the edge runtime!

**Comment by altechzilla** [comment]
Any plans to add support for edge runtime?

**Comment by PublicTrades** [comment]
Hello all,
I am having the same issue, and not running PrismaClient on the frontend. I have a file in the `/api/file`, and when I tried making a POST request I got this error:
```Server Error
Error: PrismaClient is unable to be run in the browser.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues```

Is there a solution to this issue?


<img width="519" alt="Screen Shot 2023-06-24 at 2 11 38 AM" src="https://github.com/prisma/prisma/assets/8324290/a1888e24-eebe-48ab-ad5f-f0e4708232c8">

**Comment by AlecKriebel** [comment]
+1 to this

Due to this issue, Prisma is seemingly entirely incompatible with Next.js [deployed on Cloudflare pages](https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/#2-configure-the-application-to-use-the-edge-runtime)

**Comment by niwatoro** [comment]
Hi everyone,

Does anyone have any ideas about how difficult it is to support Edge Runtime? If I can be of any assistance, I would like to contribute to this issue. I'm currently experiencing the same issue.

**Comment by hohogpb** [comment]
after a due while, there has not a new idea, it seem's will be a long road wait... 
i change my mind, use fetch to do auth instead of directlly use prisma function in middleware, change the prisma part code from middleware to api, 
i have create a template project for it :
[https://github.com/hohogpb/next-prisma-auth-starter](https://github.com/hohogpb/next-prisma-auth-starter)
online demo : 
[https://next-prisma-auth-starter.vercel.app/](https://next-prisma-auth-starter.vercel.app/)

**Comment by VinceERS** [comment]
I am having the same error, although I am not using nextjs.  My tech stack looks different but I suspect there might be some commonalities here.

I am using prisma in astro with ssr and the deno adapter.  Running the app in local dev does not throw this error, api endpoints which call prisma are correctly running server side.

However when running the production build of the app, these same endpoints will show errors in the console, not in the browser.  I do not know if using the deno adapter for astro is running prisma as middleware or something like that, but I am following the documentation: [Best practice for instantiating PrismaClient with Next.js](https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices).

**Comment by janpio** [comment]
I think your setup is different enough that it would be worth to have a full issue for it @VinceERS. This error message here mostly "just" means that the app is trying to use an export of Prisma that is meant for browsers - where Prisma does not work obviously. So in a separate issue we could understand your setup better, and hopefully figure out a way to avoid this wrong usage. Thanks.

**Comment by reanzi** [comment]
Run into this few days back, Problem is calling Prisma on the client;
use native ```fetch``` or even better use ```axios``` to call api endpoint,, **Access prisma in the api routes**.
Happy coding. :)

**Comment by amplicity** [comment]
I also get this issue when calling prisma from a 'server component'.

IE server component imports a lib function that uses prisma:
```
// My server component
import { auth } from '@/lib/auth' <--- contains prisma reference

export default async function IndexPage() {
  const session = await auth() <--- this does not work.

  // redirect to home if user is already logged in
  if (session?.user) {
    redirect('/app')
  }
  return (
    <>
    </>
  )
}
```

**Comment by janpio** [comment]
Can you share a reproduction @amplicity?

**Comment by kamigerami** [comment]
Similar issue here.  Ultimately I chose to go with an api route and posting the data to it however it would be great to just use server components.

simple example below:

middleware.ts
```ts
import { authMiddleware } from "@clerk/nextjs";
import { createUser } from "./lib/database/createUser";

export default authMiddleware({
  publicRoutes: ["/", "/api/auth/public(.*)"],
  ],
  async afterAuth(auth, req, evt) {
    if (!auth.userId) {
      return;
    }
    try {
      if (auth.user) {
        const userData: UserData = {
          clerkId: auth.userId,
          email: auth.user.emailAddresses?.[0].emailAddress,
          name: `${auth.user.firstName} ${auth.user.lastName}`,
          profileImageUrl: auth.user.profileImageUrl,
        };
        const res = await createUser(userData);
        const responseData = await res.json();
        if (!responseData.ok) {
          console.error("Error creating user", responseData.error);
          throw new Error(`User creation failed: ${responseData.error}`);
        }
      }
    } catch (error) {
      console.error("Error in afterAuth:", error);
    }
  },
});

export const config = {
  matcher: ["/((?!.*\\..*|_next).*)", "/(api|trpc)(.*)"],
};
```
lib/database/createUser.ts
```ts
"use server";
import { NextResponse } from "next/server";
import { UserData } from "@/typings";
import { prisma } from "./prisma-client";
import { User } from "@prisma/client";

type UserCreationResponse =
  | { ok: true; data: User }
  | { ok: false; error: string };

export async function createUser(
  userData: UserData,
): Promise<NextResponse<UserCreationResponse>> {
  try {
    const dbUser = await prisma.user.create({
      data: {
        externalId: userData.clerkId,
        email: userData.email,
        name: userData.name,
        profileImageUrl: userData.profileImageUrl,
      },
    });

    if (!dbUser) {
      return NextResponse.json({
        ok: false,
        error: "Error creating user",
      });
    }

    return NextResponse.json({
      ok: true,
      data: dbUser,
    });
  } catch (error) {
    throw error;
  }
}
```

//prisma-client.ts
```ts
"use server";
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
```

**Comment by amplicity** [comment]
@janpio I ended up resolving this. The issue was that the server component was an edge server component. I updated my comment to include the edge runtime declaration, which caused the prisma error.

**For people running into this error with next.js**
Prisma _does_ alert you that it can't run in edge. I specifically did not get this error because my next cache was out of date. A seriously frustrating issue IMO. I had to `rm -rf .next` and `rm -rf node_modules`, then `npm i` and `npm run dev` to get the updated error, which alerted me to look for a component inheriting the code block referencing prisma that was running on `edge`.

**Comment by janpio** [comment]
Thanks for the update @amplicity - we'll try to surface this better (and of course then also handle when we actually properly support the edge runtime).

**Comment by Jolg42** [comment]
@hohogpb and others: the error should be gone now if you upgrade to `5.2.0`, could you try that and let us know?

**Comment by levelingup** [comment]
For some reason I'm still getting a similar error message even with 5.2.0.

However, I'm running prisma in useEffect

```
useEffect(() => {
        const predictions = await prisma.prediction.findMany({
          where: {
            userId: userId,
          },
        });
}, []);
```

**Comment by janpio** [comment]
Can you provide more information, so we can reproduce this? Optimally open a new bug issue and fill the full template and provide a reproduction we can run.

**Comment by janpio** [comment]
Hey, we at Prisma have been working on the foundations for Edge Functions support for the past few weeks. If you got this error in context of trying to deploy an edge function or middleware, this could be interesting fo you.

If you are interested in helping us, please respond to this super short survey and leave your email address so we can get in touch with instructions: https://pris.ly/survey/driver-adapter-browser Thanks.

**Comment by amanrathore48** [comment]
> Can you provide more information, so we can reproduce this? Optimally open a new bug issue and fill the full template and provide a reproduction we can run.

Hello i am using prisma + supabase + next 14  but i am getting same type of errors as listed above 

--> my Queries file queries.ts
```
import { workspace } from "./supabase.types";
import { UUID } from "crypto";
import { prisma } from "@/lib/supabase/db";
import { validate } from "uuid";
import { Workspace } from "@prisma/client";

export const createWorkspace = async (workspace: any) => {
  try {
    console.log("workspace creating... :", workspace);
    const response = await prisma.workspace.create({ data: workspace });
    console.log("response :", response);
    return { data: response, error: null };
  } catch (error) {
    console.log(error);
    return { data: null, error: "Error" };
  }
};
```

and the db file   --> db.ts

```
import { PrismaClient } from "@prisma/client";

declare const global: Global & { prisma?: PrismaClient };

export let prisma: PrismaClient;

if (typeof window === "undefined") {
  if (process.env["NODE_ENV"] === "production") {
    prisma = new PrismaClient();
  } else {
    if (!global.prisma) {
      global.prisma = new PrismaClient();
    }
    prisma = global.prisma;
  }
}
```

i am getting error as :- 

> TypeError: Cannot read properties of undefined (reading 'workspace')
>     at createWorkspace (queries.ts:23:35)
>     at onSubmit (dashboard-setup.tsx:90:65)
>     at eval (index.esm.mjs:2196:19)

**Comment by hohogpb** [comment]
this problem is clearly now，it's reason is mainly on the runtime of next.js ! not because of prisma, so i want to close this issue!
some more detail you might want to see!
[https://github.com/vercel/next.js/discussions/46722#discussioncomment-7781935](url)
