### ISSUE TITLE
Wrong import suggestion when using output in generator client

### ISSUE THREAD

**Issue by jacobakkerboom** [prisma/prisma#19520]
### Bug description

When using the output field of generator client in schema.prisma, after running `npx prisma generate`, the suggestion for how to import the prisma client is wrong.

### How to reproduce

package.json:
```
{
  "type": "module",
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "@prisma/client": "^4.14.1",
    "prisma": "^4.14.1"
  }
}
```

Steps:
1. `npm install`
2. `npx prisma generate`
3. Make an app.js file containing only the import statement that `npx prisma generate` logs (i.e. `import { PrismaClient } from './prisma/generated-client'`)
4. `npm start`

### Expected behavior

Expected behaviour is that the code will run without an error. Actual behaviour is that an error is thrown:

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '~/services/prisma-test3/prisma/generated-client' is not supported resolving ES modules imported from ~/services/prisma-test3/app.js
Did you mean to import ../prisma/generated-client/index.js?
```

### Prisma information

prisma/schema.prisma
```
generator client {
  provider = "prisma-client-js"
  output = "generated-client"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL_MAIN")
}

model Locations {
  LocationID                   Int                            @id
  LocationName                 String                         @db.VarChar(45)
}
```

### Environment & setup

- OS: Mac
- Database: MySQL
- Node.js version: v16.20.0

### Prisma Version

```
prisma                  : 4.15.0
@prisma/client          : 4.15.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 8fbc245156db7124f997f4cecdd8d1219e360944 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 8fbc245156db7124f997f4cecdd8d1219e360944 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.15.0-28.8fbc245156db7124f997f4cecdd8d1219e360944
Default Engines Hash    : 8fbc245156db7124f997f4cecdd8d1219e360944
Studio                  : 0.484.0
```

**Comment by janpio** [comment]
Does changing the import as the error message suggests make it work as expected?

**Comment by jkomyno** [comment]
Hi @jacobakkerboom and @vladfaust. We've recently changed the output we display on `prisma generate`'s success.
Can you please try again via a recent Prisma version (e.g., 5.18+, the latest one is currently 5.21.0), and report back? Thanks!

**Comment by jacobakkerboom** [comment]
@jkomyno I have tried it and there is no longer a suggestion for an import statement in the message, so that certainly resolves the issue of there being a wrong import suggestion. Linking the documentation instead makes sense to me.

A minor point is that one of the two links in the message has http and the other has https.

Maybe the documentation behind the link could also be slightly improved. It says: "The import path will depend on the custom output specified in Prisma Client's [generator](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#fields-1) block in your Prisma schema."

Maybe "the custom output" could be replaced by *any* custom output or something, just to make it clearer that using the output field is something that is optional which won't affect most users.

More importantly documentation doesn't say anything about directory imports and why that wouldn't work and that you need to import index.js from the folder in this case.

Anyway, thanks for addressing the issue

**Comment by jkomyno** [comment]
Hi @jacobakkerboom, thanks, [http://pris.ly/d/importing-client](http://pris.ly/d/importing-client) accidentally slipped through.
I'm pushing a fix now.
