### ISSUE TITLE
Ability to set length of text field / document the process if it already exists.

### ISSUE THREAD

**Issue by webnoob** [prisma/prisma#1952]
## Problem
No way to set the length of a string field / or not documented

## Solution
A way to set the length or documentation update to provide info on how to.

## Additional context
I've looked in the scaler types and can't see the info.

For instance, the following model:
```
model Book {
  id Int  @default(autoincrement()) @id
  title String?
}
```
In MySQL DB the title field will be a `varchar(191)` datatype. We need to be able to configure the length.

I initially posted this as a discussion item but after trawling the docs, thought a feature request was at least required for the docs to contain this info (if the functionality exists): https://github.com/prisma/prisma2/discussions/1940

**Comment by webnoob** [comment]
I've looked through other issues related to this tag and notice this https://github.com/prisma/prisma2/issues/623 might be the same / related.

**Comment by pantharshit00** [comment]
Answered here: https://github.com/prisma/prisma2/discussions/1940

**Comment by pantharshit00** [comment]
Quoting answer from discussion:
This is something that will get covered via #446

Right now you can get around this by setting the data type yourself manually in the database and then introspecting it using prisma2 introspect

**Comment by matthewmueller** [comment]
You can now limit the text length with native database types and `@db.VarChar(n)`.

https://www.prisma.io/docs/concepts/components/preview-features/native-types/native-types-mappings#string
