### ISSUE TITLE
No error for arg in `connect` possibly undefined

### ISSUE THREAD

**Issue by igorschechtel** [prisma/prisma#19567]
When using the connect parameter, I get a runtime error if it resolves to `connect: { id: undefined }`. The error is the following:

```
Argument `connect` of type ... needs at least one argument.
```

So, if `connect: { id: undefined }` is not valid, it should give a type error as well, not only in runtime.

Searching about this, I found [this blog post](https://ruheni.dev/writing/skipping-connect-fields-for-unique-fields/) from Feb 2023, where the writer says it does give you the following type error:

```
PrismaClientValidationError:
Invalid `prisma.post.create()` invocation in
/project_path/index.ts:8:37

  5 async function main() {
  6   const authorId = undefined
  7
→ 8   const newPost = await prisma.post.create({
        data: {
          title: 'New Post with undefined authorId',
          author: {
          ~~~~~~
            connect: {
              id: authorId
            }
          }
        },
        include: {
          author: true
        }
      })

Unknown arg `author` in data.author for type PostUncheckedCreateInput. Did you mean `authorId`? Available args:
type PostUncheckedCreateInput {
  id?: Int
  createdAt?: DateTime
  updatedAt?: DateTime
  title: String
  content?: String | Null
  isPublished?: Boolean
  authorId?: Int | Null
}


    at Yn.validate (/project_path/node_modules/@prisma/client/src/runtime/query.ts:249:19)
    at Ur.createMessage (//project_path/node_modules/@prisma/client/src/runtime/core/protocol/graphql.ts:81:14)
    at cb (/Users/ruheni/project_path/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1078:27)
    at runInChildSpan (/project_path/node_modules/@prisma/engine-core/src/tracing/runInChildSpan.ts:20:41)
    at t._executeRequest (/project_path/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1077:31)
    at async t._request (/project_path/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1036:14) {
  clientVersion: '4.10.1'
}
```

I tried rolling back to version 4.10.1 (as in the post) to test this, but I still get no errors from this case.

![image](https://github.com/prisma/prisma/assets/21978920/e59bc1a7-81c3-49cc-9835-68d83a0e8525)

What am I missing? Is this something that used to work, or is it a long time issue?

PS: I'm using Prisma 4.13.0 with typescript strict

**Comment by miguelff** [comment]
Are you by chance using the [`jsonProtocol` preview feature](https://github.com/prisma/prisma/issues/18095)?

**Comment by igorschechtel** [comment]
@miguelff yes, we are using `jsonProtocol` in production. But it is set on the `Dockerfile`, and the issue also happens locally.
