### ISSUE TITLE
All Prisma related tooling should have source maps per default

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#1956]
If you run into any kind of error, Prisma shows Javascript stack traces of a single file instead of the correct location of the typescript code:

```
*some error*
    at PrismaClientFetcher.request (/Users/runner/runners/2.165.2/work/prisma2-e2e-tests/prisma2-e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:1:51487)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This needs to be fixed so that debugging errors is easier instead of trying to guess where in the codebase that error happened. It'll save everyone a lot of time.

**Comment by timsuchanek** [comment]
Update: The Prisma Client now ships source maps.
https://github.com/prisma/prisma-client-js/issues/533#issuecomment-607139681

There are still some tools like `@prisma/cli` missing.

**Comment by Jolg42** [comment]
CLI doesn’t ship source map file today
https://github.com/prisma/prisma/blob/631a71f0dd2125d810623df882ad41d289b76f22/src/packages/cli/package.json#L140
`--source-map  is missing`

**Comment by steebchen** [comment]
I can confirm this works now. Should we close the issue?

**Comment by pantharshit00** [comment]
If this works we should close it :)
