### ISSUE TITLE
Support for multiple database 

### ISSUE THREAD

**Issue by tech16-hub** [prisma/prisma#19589]
## Problem
No support for multi-tenant app that requires multiple database connection

## Suggested solution
I suggest we add a variable with a name databases which will hold array of database url or provider.

Now in Model you can now add @db[db1,db2] that will mean that the model belongs to db1 and db2 and default db. User can add @skipDefaultDb to exclude default db

Api access will be PrismaClient.model if accessing default and PrismaClient.databases.model

**Comment by petradonka** [comment]
Thanks for the suggestion. We have an open issue where I think your idea fits into: https://github.com/prisma/prisma/issues/2443 or https://github.com/prisma/prisma/issues/12420

If you think that there's anything you'd add to that feature request, please leave a comment there.
