### ISSUE TITLE
`prisma.model.count` does not type `distinct` correctly

### ISSUE THREAD

**Issue by jharlowuk** [prisma/prisma#19598]
### Bug description

Eager to see a more concrete solution to the `count` `distinct` issue raised by #4228, however in the meantime, I can see that [a conscious decision has been made](https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing#distinct-under-the-hood) not to support `distinct` filtering in `.count` or `.aggregate` queries.

In `.aggregate` queries, a typing error is thrown when using the `distinct` key, however `.count` will allow you to add `distinct` and only throw an error at runtime. This can be quite confusing!

### How to reproduce

1. Make a prisma `.count` query and add a `distinct` key with a value that is valid in a `.findMany` query.
2. Look for typing errors
3. Run query to see failure

### Expected behavior

All `distinct` keys inside of `.count` queries should throw a typing error.

### Prisma information

`schema.prisma`
```schema.prisma
model User {
  id                 String       @id @default(cuid())
  idempotenceId      String
  name               String?
}
```

`user.ts`
```user.ts
prisma.user.count({
  // no error thrown (until runtime)
  distinct: ["idempotenceId"],
});
```

### Environment & setup

- OS: macOS 13.4 (22F66)
- Database: PostgreSQL
- Node.js version: 18

### Prisma Version

```
prisma                  : 4.5.0
@prisma/client          : 4.5.0
```

**Comment by janpio** [comment]
I can confirm that we do not filter out `distinct`.

**Comment by jharlowuk** [comment]
Thank you!
