### ISSUE TITLE
Calling typeof on extended PrismaClient is extremely slow

### ISSUE THREAD

**Issue by anton-g** [prisma/prisma#19605]
### Bug description

We have a very basic field extension to one of our models which works great, but we noticed that our TypeScript performance took a massive hit after implementing it.

It's a Next-project and we have file called `db.ts` that looks like this:

```ts
import { PrismaClient } from '@prisma/client'

type ExtendedPrismaClient = ReturnType<typeof getExtendedClient>

let prisma: ExtendedPrismaClient

declare global {
  var __db__: ExtendedPrismaClient
}

// this is needed because in development we don't want to restart
// the server with every change, but we want to make sure we don't
// create a new connection to the DB with every change either.
// in production we'll have a single connection to the DB.
try {
  if (process.env.NODE_ENV === 'production') {
    prisma = getExtendedClient()
    prisma.$connect()
  } else {
    if (!global.__db__) {
      global.__db__ = getExtendedClient()
    }

    prisma = global.__db__

    prisma.$connect()
  }
} catch (error) {
  console.log('Error connecting to db', error)
}

function getExtendedClient() {
  return new PrismaClient().$extends({
    result: {
      animal: {
        favorite: {
          needs: {
            name: true,
          },
          compute(animal) {
            return animal.name === 'Rufus'
          },
        },
      },
    },
  })
}

export { prisma }
```

The problem is that `ReturnType<typeof getExtendedClient>` is extremely slow. According to a TS trace it takes 25 *seconds* to compile, increasing the length of our entire TS compilation by 2-300% and making VS Code struggle with basic intellisense. Might be sligthly related to #17843 but it's not only Code that is slow.

### Prisma Version

```
4.15.0
```

**Comment by anton-g** [comment]
Hm, in my attempt to refactor our code to avoid this issue I discovered that it doesn't seem related to `ReturnType<typeof getExtendedClient>` at all, but rather that just the extension makes TypeScript compilation very slow. Closing this and commenting in the other issue instead.

**Comment by alexwork1611** [comment]
This is not fixed @prisma-bot. Extended clients are still very slow from a type perspective.
