### ISSUE TITLE
Rename `prisma2` GitHub repository to `prisma`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#1960]

**Comment by schickling** [comment]
I agree your proposed step feels like the logical conclusion considering we've also just renamed the NPM package from `prisma2` to `@prisma/cli`. However, I think it's important to still have a "main repository" for Prisma (e.g. for people googling "Prisma") which IMO as `prisma/prisma` feels more "idiomatic".

Do you have thoughts on a solution that would satisfy this goal?

**Comment by MichalLytek** [comment]
@schickling Maybe `prisma2` repo should contain the docs and be some kind of router to other Prisma 2 ecosystem packages/modules?

CLI could be moved to separate repository if needed.

**Comment by janpio** [comment]
Although I like the thought, I do not think that this is the right way to go. Repo structure does not map cleanly onto npm package structure and vice versa. There are other ecosystems (Rust, Golang etc) that we care about. Also in a semi mono repo world this clashes with the goal of that - so I think we are much better off with keeping a non CLI related name for the "main" repo.

**Comment by Jolg42** [comment]
I changed the title of the issue @janpio 😉

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma2-development-environment/pull/18

https://github.com/prisma/prisma2/pull/2001

https://github.com/prisma/prisma-client-js/pull/613

https://github.com/prisma/migrate/pull/388
