### ISSUE TITLE
Improve version output

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#1961]
## Problem

Currently the version CLI output (when running `prisma2 -v`) is quite "overwhelming".

![image](https://user-images.githubusercontent.com/1567498/77776900-01042e80-704f-11ea-964b-78ac917c3b9f.png)

## Solution

1. I suggest to reformat the output by "segmenting" the output into two blocks. e.g.

```
@prisma/cli: 2.0.0-preview025

Current platform:     darwin
Query Engine:         prisma 8814060fa684793b73d07dbfccd4b7777b3361ae (at /usr/local/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine:     migration-engine-cli 8814060fa684793b73d07dbfccd4b7777b3361ae (at /usr/local/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine: introspection-core 8814060fa684793b73d07dbfccd4b7777b3361ae (at /usr/local/lib/node_modules/@prisma/cli/introspection-engine-darwin)
```

2. Additionally I'd print the "key" of the key/value-pairs (e.g. `@prisma/cli`) in **bold**.

## Additional context

- Related issue: https://github.com/prisma/prisma2/issues/981

**Comment by ChristophDietrich** [comment]
What about to do it like node:
`node -v`

Output:
`v12.16.1`

----
Prisma2 (short version)
`prisma2 -v`

Output:
`@prisma/cli: 2.0.0-preview025`

----
Prisma2 (long version)
`prisma2 -v -full`

Output:
```
@prisma/cli: 2.0.0-preview025

Current platform:     darwin
Query Engine:         prisma 8814060fa684793b73d07dbfccd4b7777b3361ae (at /usr/local/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine:     migration-engine-cli 8814060fa684793b73d07dbfccd4b7777b3361ae (at /usr/local/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine: introspection-core 8814060fa684793b73d07dbfccd4b7777b3361ae (at /usr/local/lib/node_modules/@prisma/cli/introspection-engine-darwin)
```

**Comment by janpio** [comment]
👍 on splitting the output.

> 1. Additionally I'd print the "key" of the key/value-pairs (e.g. `@prisma/cli`) in **bold**.

This would unfortunately lead to problems when you do string comparison as the bolding would be invisible control characters in the string, so you need to use [`strip-ansi`](https://www.npmjs.com/package/strip-ansi) first :/

**Comment by schickling** [comment]
@janpio for programmatic comparisons we should have a `--json` option anyway. I don't think this was so far a stated requirement/design goal for the CLI.

**Comment by steebchen** [comment]
A --json flag would be super valuable

**Comment by steebchen** [comment]
created https://github.com/prisma/prisma/issues/2071 for a --json feature request

**Comment by DavidHancu** [comment]
Comment from @janpio:
> One thing is that it needs to be easily copy and pasted to GitHub.

I also suggest a more spacious layout, with colors and additional data needed for debugging (such as package manager and version and the architecture of the system).

```
Platform
Current platform        : windows
Node.js version         : 0.0.0
Package manager         : 0.0.0 (NPM)
Architecture            : x64

Prisma
prisma                  : 0.0.0
@prisma/client          : 0.0.0 
Studio                  : 0.479.0      

Prisma Engines
Query Engine (Node-API) : libquery-engine c9e863f2d8de6fa0c4bcd609df078ea2dde3c2b2 (at ..\..\packages\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli c9e863f2d8de6fa0c4bcd609df078ea2dde3c2b2 (at ..\..\packages\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core c9e863f2d8de6fa0c4bcd609df078ea2dde3c2b2 (at ..\..\packages\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt c9e863f2d8de6fa0c4bcd609df078ea2dde3c2b2 (at ..\..\packages\engines\prisma-fmt-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-51.cb66a7dac27b38cbc5dc34b27cf389f4be35d5e2
Default Engines Hash    : c9e863f2d8de6fa0c4bcd609df078ea2dde3c2b2

Generated Prisma Client
client                  : 0.0.0 (at ..\node_modules\.prisma\client)
```

As for the colors, there are 3 rules:
- All section titles would be colored in blue and bolded
- All text on the left side would be white
- All text on the right side would be gray

**Comment by janpio** [comment]
Go for it @DavidHancu From internal vote: 
<img width="52" alt="image" src="https://user-images.githubusercontent.com/183673/212441391-03b5ff5d-a7b6-4c66-a26a-e07137764046.png">

**Comment by jkomyno** [comment]
Hi everyone, I'm closing this issue as it has already been addressed over the years via `prisma version --json` by:
- https://github.com/prisma/prisma/commit/7b4ad300788cb3d0bd012bef991fa7ba92dc3d96
- https://github.com/prisma/prisma/pull/21625

Thanks!
