### ISSUE TITLE
Prisma Migrate just crashed

### ISSUE THREAD

**Issue by singyichen** [prisma/prisma#19628]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v14.18.0           | 
| Prisma CLI  | 4.1.0              | 
| Engine      | 8d8414deb360336e4698a65aa45a1fbaf1ce13d8| 

## Error
```
Error: [libs\datamodel\connectors\dml\src\model.rs:494:29] Hi there! We've been seeing this error in our error reporting backend, but cannot reproduce it in our own tests. The problem is that we have a primary key in the model `COPTF` that uses the column `TG001` which we for some reason don't have in our internal representation. If you see this, could you please file an issue to https://github.com/prisma/prisma so we can discuss about fixing this. -- Your friendly prisma developers. 
```

**Comment by petradonka** [comment]
Hey @singyichen: could you please add a bit more details on the steps you took?

**Comment by singyichen** [comment]
Hi Prisma Team,
The following are details I used.
- prisma：v4.1.0
- @prisma/client：v4.0.0
- db：sql server 2008
- script：npx prisma db pull
It is strange that our table COPTF does not have column TG001...

**Comment by SevInf** [comment]
Hey @singyichen ,


Did you get a chance to have a look at @Jolg42  comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by singyichen** [comment]
hi team,
Thanks for information, it work ,thanks!
