### ISSUE TITLE
Prisma2 wrong type form geometry

### ISSUE THREAD

**Issue by zifahm** [prisma/prisma#1963]
Error due to geometry type 
```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(3), cause: Some(WrongType { postgres: Other(Other { name: \"geometry\", oid: 113659, kind: Simple, schema: \"public\" }), rust: 
```

In tyeporm Entity
```javascript
@Column("geometry", {
    nullable: true,
    spatialFeatureType: "Point",
    srid: 4326
  })
  @Index({ spatial: true })
  geom: Point;

```
schema
```javascript
model User{

 geom    String?

@@index([geom], name: "IDX_dea7391c740609c9ba44ea0791")

}
```

workaround currently was  by removing  geom in the schema

**Comment by janpio** [comment]
Type `geometry` is currently not supported.

How did you create your schema and what version of Prisma did you use? In `preview025` this field should have automatically been commented out by `prisma2 introspect`, to avoid running into this error.

**Comment by zifahm** [comment]
I installed the alpha version of prisma2 and it commented it out, not in the preview025 version tho.
Thanks

**Comment by pantharshit00** [comment]
I am going to close this in favor of #1798. We will tackle further support there now.
