### ISSUE TITLE
`console.log(prisma)` freezes and does not return

### ISSUE THREAD

**Issue by fohanist** [prisma/prisma#19648]
### Bug description

Set prisma in the root model. Subsequently, the prisma is received from the sole model and the user model is created through the proxy object. When you try to output an instance of the user model, the console recursively invokes an object and freezes the terminal. I'm very curious about the reason.

![image](https://github.com/prisma/prisma/assets/76135061/26b6e979-f1fd-4d9e-b851-1113588ee048)

### How to reproduce

$ npm init -y
$ npm install typescript ts-node prisma

...create prisma schema
...user create success

Problem code run
```js
import { PrismaClient, User as UserSchema } from "@prisma/client";

class RootModel {
  public prisma: PrismaClient;

  constructor() {
    this.prisma = new PrismaClient();
  }

  public proxyWrapper<T>(object: T | null) {
    const innerObj = object || {};
    return new Proxy(innerObj as any, {
      get: (target, prop) => {
        return target[prop];
      },
      set: (target, prop, value) => {
        target[prop] = value;
        return true;
      },
    });
  }
}

class User extends RootModel {
  public data: UserSchema | {} = {};

  constructor(userData: UserSchema | null = null) {
    super();
    this.data = this.proxyWrapper<UserSchema>(userData);
  }
}

async function main() {
  const user = new User();
  console.log(user);
}

main();
```

### Expected behavior

I wanted to use it like the active record I use on Ruby on Rails. I thought I could create a user model object and then access user data through a proxy object. Wanted to avoid writing all the user properties to model objects.

### Prisma information

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User    @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

### Environment & setup

- OS: windows wsl2
- Database: sqlite, postgresql
- Node.js version: v18.16

### Prisma Version

```
"@prisma/client": "^4.15.0",
"prisma": "^4.15.0",
"ts-node": "^10.9.1",
"typescript": "^5.1.3"
```

**Comment by aqrln** [comment]
Minimal reproduction:

```ts
const prisma = new PrismaClient()
console.log(prisma)
```

On Prisma 4.15.0 (the version from the report) this prints 152 MiB of output and exits, on latest Prisma from `main` this freezes indefinitely.

A workaround for you @fohanist is to either make `prisma` a private field (as in a real private field in JS, `#prisma`, not TypeScript's `private prisma`), or implement [`util.inspect.custom`](https://nodejs.org/api/util.html#utilinspectcustom) in a way that would skip `prisma`.

**Comment by aqrln** [comment]
(and we should definitely implement `Symbol.for('nodejs.util.inspect.custom')` on `PrismaClient` on our side)

**Comment by janpio** [comment]
Duplicate: https://github.com/prisma/prisma/issues/18292

**Comment by janpio** [comment]
Can we close this one maybe @aqrln @fohanist and move all the additional information over to #18292?
