### ISSUE TITLE
Deploying to an offline environment fails because it tries to download a Prisma engine checksum file 

### ISSUE THREAD

**Issue by Secret1007** [prisma/prisma#19666]
### Bug description

![image](https://github.com/prisma/prisma/assets/87068106/707e4b1f-8dca-4f9c-86fb-222406ffe4fd)

i am trying to deploy my server on an  offline service system, and i met this, anyone can give me a favour

### How to reproduce

npx prisma db seed

### Prisma information

```prisma
![image](https://github.com/prisma/prisma/assets/87068106/3e1288e1-1924-4102-bd13-6d8f3cb14e5a)

```

```ts
npx prisma db seed
```

### Environment & setup

- OS: 
- 
![1686118725516_C21BF071-4716-471e-B5FB-56EB9DACA7FD](https://github.com/prisma/prisma/assets/87068106/02eec17c-a6d5-413a-8da0-fc79cd63f0af)

- Database: mysql
- Node.js version: v20.2.0

### Prisma Version

![image](https://github.com/prisma/prisma/assets/87068106/69270cc2-5a8e-43a9-8835-b4d274f64f9e)

**Comment by Jolg42** [comment]
Note: we have this related issue that blocks this that we want to review for this release https://github.com/prisma/prisma/issues/12230

**Comment by Jolg42** [comment]
@Secret1007 This will be part of the official `4.16.0` release planned, Tuesday 20th.
It's now possible to try it in our `4.16.0-dev.63` dev version, which is not recommended to use in production.
Set the following environment variable
```
PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
```
If you try it, we're curious to hear about any feedback on how it worked out for you.
