### ISSUE TITLE
create_at value is not set default follow config.

### ISSUE THREAD

**Issue by baroxdev** [prisma/prisma#19665]
### Bug description

**Description:**
I encountered an error while attempting to create a new Stuff record using Prisma. The error message indicates an issue with the create_at field, specifically the conversion of its value to the expected non-nullable type "DateTime". The error message suggests that an incompatible value of "null" was found.

**Expected Behavior:**
I expected the create_at field to be automatically populated with the current timestamp as specified in the Prisma model definition: create_at DateTime @default(now()).

But the previous day it still work nicely.

### Expected behavior

create_at field to be automatically populated with the current timestamp as specified in the Prisma model definition: create_at DateTime @default(now()).

### Prisma information

```prisma
model Stuff {
  id              String              @id @default(auto()) @map("_id") @db.ObjectId
  // ... other fields
  create_at DateTime @default(now())
  update_at DateTime @updatedAt

  @@map("stuff")
}
```

```ts
const createStuffSchema = {
          name: input.name,
          description: input.description,
          category: { connect: { slug: input.category } },
          type: { connect: { slug: input.type } },
          condition: input.condition,
          media: fileUrls,
          payment_type: {
            connect: {
              slug: input.payment_type,
            },
          },
          author: { connect: { id: input.author_id } },
          tags: {},
          price: input?.custom_fields?.price,
          auction: {},
        };

        if (input.type === 'auction') {
          createStuffSchema.auction = {
            create: {
              initial_price: input.custom_fields.price,
              step_price: input.custom_fields.step,
            },
          };
        }

        if (input.tags && input.tags.length > 0) {
          createStuffSchema.tags = {
            createMany: {
              data: input.tags,
            },
          };
        }

        const createdStuff = await prisma.stuff.create({
          data: {
            ...createStuffSchema,
          },
          include: {
            author: {
              ...ruleReturnAuthorInfo,
            },
            category: true,
            type: true,
            auction: true,
            payment_type: true,
            tags: true,
          },
        });
```

### Environment & setup

- OS: Windows
- Database: MongoDB
- Node.js version: v18.16.0

### Prisma Version

```
@prisma/client": "^4.15.0",
 "prisma": "^4.15.0",
```

**Comment by petradonka** [comment]
Hey @baroxdev: could you share the specific error message you received?

You also mentioned "But the previous day it still work nicely." - do you mean that this has worked in the past, or that if you set the date value for this field on the new record to a different date, it works and you don't get the error?

**Comment by SevInf** [comment]
Hey @baroxdev 
In Prisma, `created_at: null` does not mean "set `create_at` to it's default value", it means  "set `created_at` to `null`". Since it is not nullable field in your schema, it is not possible and that's why you get a validation error. If you want to set it to default value, use `undefined` instead. See also our docs on [`null` vs `undefined`](https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined).

**Comment by jharrell** [comment]
Hello again!

Unfortunately we don't have the info we need to reproduce and move forward, so we will have to close. If you have a similar issue, please leave a comment or open a new issue. Thank you!
