### ISSUE TITLE
Error format for missing type on field is broken

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#1967]
```
model myModel {
      id  @id
}
```
The type `Int` is missing here
So this is expected to error but the actual error format is wrong see:

```
 Error in datamodel: ErrorCollection { errors: [ParserError { expected: ["field type"], expected_str: "field type", span: Span { start: 168, end: 168 } }] }
```

**Comment by mavilein** [comment]
@Jolg42 : What's the right error format in this case?

**Comment by Jolg42** [comment]
Looks like it works now :)
![Uploading Screen Shot 2020-04-01 at 15.38.49.png…]()
