### ISSUE TITLE
Error format for enum field declaration broken

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#1968]
Could be related https://github.com/prisma/prisma2/issues/1967

```
enum hello {
      1
}
```

Is it possible to have numbers in enums?

Anyway the actual error format is wrong see:
```
Error in datamodel: ErrorCollection { errors: [ParserError { expected: ["End of block (\"}\")", "documentation comment", "block level directive", "enum field declaration"], expected_str: "End of block (\"}\"), documentation comment, block level directive, enum field declaration", span: Span { start: 112, end: 112 } }] }
```

**Comment by janpio** [comment]
This is a clunky error message that should tell you that pure numbers are indeed not allowed in enum value names. Here is a fixed version of the datamodel snippet:

```
enum hello {
  one @map("1")
}
```

The error message could use some improvement though (or we relax our requirements for enum field value names).

**Comment by Jolg42** [comment]
Looks like the error works as well here 
<img width="686" alt="Screen Shot 2020-04-01 at 15 40 13" src="https://user-images.githubusercontent.com/1328733/78143883-21593200-742f-11ea-8c77-6a2dcf5fdc40.png">
