### ISSUE TITLE
Adapt `generate` success output

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1974]
Every time I post the successful output of a `generate` call this happens:

```
C:\Users\Jan\Downloads\prismachinookmastercli-demo>npx prisma2 generate
✔ Generated Prisma Client to .\node_modules\@prisma\client in 248ms

You can now start using Prisma Client in your code:

```
import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
```

Explore the full API: http://pris.ly/d/client
```

=> GitHub code formatting breaks because the output itself contains 3 backticks - that do not even do anything. We could replace it with single backticks, 3 normal ticks, or highlight the code some other way to avoid that.

**Comment by vadistic** [comment]
Just a thought - when using cutom output path - those instructions aren't exactly accurate, are they? :man_shrugging: 

Maybe hide them?

**Comment by janpio** [comment]
That is a good point and should be taken into account! Can you please create a new issue though @vadistic - as this is one is about something quite different it will not be taken into account here (as we can not schedule it). Thanks!

**Comment by janpio** [comment]
Using ```` is the solution.
