### ISSUE TITLE
Repeated alter migrations in MySQL on Boolean data type

### ISSUE THREAD

**Issue by basicdays** [prisma/prisma#19790]
### Bug description

Hi there,

I'm in the process of seeing if I can get Prisma to work on our legacy database that has been built on over the years. In the process of pulling the schema and running some migrations, I'm finding various Prisma data types to native DB types are causing issues on subsequent migrations. In the following schema, the `BooleanGood` model does not cause repeated alter SQL statements in new migrations. However `BooleanBug` will cause endless alter statements whenever you run `prisma migrate dev`.

This is similar to issue https://github.com/prisma/prisma/issues/19791, but I figured I'd post this separately to reduce complexity. I can merge them if that's more helpful.

### How to reproduce

1. Add the provided prisma schema
2. Run `npx prisma migrate dev`
3. Run `npx prisma migrate dev` again. The second migration will cause another SQL migration file repeating alter fields from `BooleanBug` model.

### Expected behavior

The fields from `BooleanBug` should not cause additional migrations when they're not changed in the schema.

### Prisma information

```prisma
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "mysql"
    url      = env("DATABASE_URL")
}

model BooleanGood {
    id Int @id @default(autoincrement())

    bool1_1 Boolean
    bool1_2 Boolean  @default(true)
    bool1_3 Boolean  @default(false)
    bool1_4 Boolean?
    bool1_5 Boolean? @default(true)
    bool1_6 Boolean? @default(false)

    bool2_1 Boolean  @db.TinyInt
    bool2_2 Boolean  @default(true) @db.TinyInt
    bool2_3 Boolean  @default(false) @db.TinyInt
    bool2_4 Boolean? @db.TinyInt
    bool2_5 Boolean? @default(true) @db.TinyInt
    bool2_6 Boolean? @default(false) @db.TinyInt

    bool3_1 Boolean  @db.Bit(1)
    bool3_6 Boolean? @db.Bit(1)

    bool4_1 Boolean  @db.UnsignedTinyInt
    bool4_4 Boolean? @db.UnsignedTinyInt
}

model BooleanBug {
    id Int @id @default(autoincrement())

    bool3_2  Boolean  @default(true) @db.Bit(1)
    bool3_3  Boolean  @default(dbgenerated("b'1'")) @db.Bit(1)
    bool3_4  Boolean  @default(false) @db.Bit(1)
    bool3_5  Boolean  @default(dbgenerated("b'0'")) @db.Bit(1)
    bool3_7  Boolean? @default(true) @db.Bit(1)
    bool3_8  Boolean  @default(dbgenerated("b'1'")) @db.Bit(1)
    bool3_9  Boolean? @default(false) @db.Bit(1)
    bool3_10 Boolean  @default(dbgenerated("b'0'")) @db.Bit(1)

    bool4_2 Boolean  @default(true) @db.UnsignedTinyInt
    bool4_3 Boolean  @default(false) @db.UnsignedTinyInt
    bool4_5 Boolean? @default(true) @db.UnsignedTinyInt
    bool4_6 Boolean? @default(false) @db.UnsignedTinyInt
}
```

### Environment & setup

- OS: Debian Bullseye 11.7
- Database: MariaDB 10.2
- Node.js version: 18.16.0

### Prisma Version

```
prisma                  : 4.15.0
@prisma/client          : 4.15.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8fbc245156db7124f997f4cecdd8d1219e360944 (at ../../node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8fbc245156db7124f997f4cecdd8d1219e360944 (at ../../node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.15.0-28.8fbc245156db7124f997f4cecdd8d1219e360944
Default Engines Hash    : 8fbc245156db7124f997f4cecdd8d1219e360944
Studio                  : 0.484.0
```

**Comment by janpio** [comment]
Two issues is perfect - thank you.

What happens when you run `prisma db pull` in this reproduction? 
Does the schema file change in any way?
If so, does the next `migrate dev` now cleanly _not_ create further migrations?

**Comment by basicdays** [comment]
Actually yeah, there's a fair amount of changes that occurred. Doing a subsequent `migrate dev` now _does not_ create another migration. A couple things I guess I could call out here.

1. It seems `@db.UnsignedTinyInt` will cause the `Boolean` data type to remap to `Int`, losing the original data type.
2. Having the the `@default(true)` getting converted to `@default(dbgenerated("(b'1')"))` is also unexpected. I would have assumed that the `@default` attribute would have accepted the data type literal and not require `dbgenerated`.

Here's the schema after pull:

```prisma
model BooleanGood {
    id      Int      @id @default(autoincrement())
    bool1_1 Boolean
    bool1_2 Boolean  @default(true)
    bool1_3 Boolean  @default(false)
    bool1_4 Boolean?
    bool1_5 Boolean? @default(true)
    bool1_6 Boolean? @default(false)
    bool2_1 Boolean
    bool2_2 Boolean  @default(true)
    bool2_3 Boolean  @default(false)
    bool2_4 Boolean?
    bool2_5 Boolean? @default(true)
    bool2_6 Boolean? @default(false)
    bool3_1 Boolean  @db.Bit(1)
    bool3_6 Boolean? @db.Bit(1)
    bool4_1 Int      @db.UnsignedTinyInt
    bool4_4 Int?     @db.UnsignedTinyInt
}

model BooleanBug {
    id       Int      @id @default(autoincrement())
    bool3_2  Boolean  @default(dbgenerated("(b'1')")) @db.Bit(1)
    bool3_3  Boolean  @default(dbgenerated("(b'1')")) @db.Bit(1)
    bool3_4  Boolean  @default(dbgenerated("(b'0')")) @db.Bit(1)
    bool3_5  Boolean  @default(dbgenerated("(b'0')")) @db.Bit(1)
    bool3_7  Boolean? @default(dbgenerated("(b'1')")) @db.Bit(1)
    bool3_8  Boolean  @default(dbgenerated("(b'1')")) @db.Bit(1)
    bool3_9  Boolean? @default(dbgenerated("(b'0')")) @db.Bit(1)
    bool3_10 Boolean  @default(dbgenerated("(b'0')")) @db.Bit(1)
    bool4_2  Int      @default(1) @db.UnsignedTinyInt
    bool4_3  Int      @default(0) @db.UnsignedTinyInt
    bool4_5  Int?     @default(1) @db.UnsignedTinyInt
    bool4_6  Int?     @default(0) @db.UnsignedTinyInt
}
```

**Comment by janpio** [comment]
Thank you. All this is definitely not intentional.

Here is a visual representation of the changes:
<img width="1009" alt="image" src="https://github.com/prisma/prisma/assets/183673/049f51c8-4d3f-4dc3-9975-f79ef278877a">

- The first block of dropping the `@db.TinyInt` is probably fine - `Boolean` already implies that
- The second diff that changes `Boolean` to `Int` is pretty uncool, I guess we have no logic that code `db.UnsignedTinyInt` to `Boolean` as we seem to have for just `@db.TinyInt`.
- In the second model, the changes to the default are indeed weird - if at all I would expect us to switch to `true/false` based on the `Boolean` type - on the other hand the `@db.Bit` fits the now provided default
- And finally again the `Boolean`=>`Int` switch, but this time also affecting the related default.

The fundamental problem is that in MySQL of course `BOOLEAN` is really just an alias to `TINYINT(1)` and it seems our logic here is not super clean, especially when taking defaults into account.

**Comment by basicdays** [comment]
So upon looking at this a bit more while updating my real schema, I noticed a pattern. Any database literal that is in the `@dbgenerated` attribute is getting wrapped in parenthesis to make it an expression. What's interesting is the `db pull` correctly created the Prisma schema without making them an expression since that was what was originally in the database schema.

In my case, I would get them on the following:

* bit literals: `b'1'` => `(b'1')`
* boolean literals in bit columns: `true` => `(b'1')`
* date/time/timestamp literals: `'2000-01-01 00:00:00'` => `('2000-01-01 00:00:00')`

After this investigation, I sorta see three issues:

1. `Boolean @db.UnsignedTinyInt` gets remapped to `Int @db.UnsignedTinyInt`. This causes endless migrations and even worse the fix removes the ability to use the column as a Boolean in Prisma Client.
2. All literals in the `@dbgenerated` attribute will get wrapped in an expression. For folks that pull their schema from an existing database, this will cause endless migrations. I also think that expression syntax in the default clause is not supported in MySQL 5.6 or 5.7, so it may cause them to fail.
3. Using a Prisma boolean literal or `@dbgenerated` with a database boolean literal as a default in a `@db.Bit(1)` column will always cause it to get remapped to a `@dbgenerated` default with a database bit literal. I _think_ this will also cause endless migrations.

**Comment by marceloavf** [comment]
Any workaround on this?

**Comment by jkomyno** [comment]
Closing this in favour of https://github.com/prisma/prisma/issues/25046.
This issue is a specialisation of the general problem witnessed in #25046.
