### ISSUE TITLE
Prisma Client: fixing type name clashes from generated client

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#19811]
[Internal Slack 🧵](https://prisma-company.slack.com/archives/C03MRGP7WLB/p1686657414481429)
[Internal Notion doc](https://www.notion.so/prismaio/Fix-type-name-clashes-in-TS-Client-9e9bbdee13f94a818ece060e55465267)

During type generation, we create many different TS types based on a schema. Sometimes, generated type clashes with some other model type or internal helper type we are using. In that case, generated client usually becomes unusable.

[List of open issues with type-clash) topic label](https://github.com/prisma/prisma/labels/topic%3A%20type-clash)

1. Introduce `$Model` namespace for user-defined models, enums and composites
2. Introduce sub-namespaces for generated types
3. Move all helpers into the runtime module

Notes
- No changes required from the users for the most part. For the types that might actually be used on their projects, we keep an alias with a short name as an export if it does not conflict with other models. We remove it if it has a conflict, but that’s already broken. So, I don’t think it is possible to get from working project to non-working one with this change.
- We should at least mention that `Prisma.SomeModelArgs` is now available as `Prisma.$SomeModel.Args` as well. If we decide that we want to recommend it (since it would never conflict with anything) we might specify that too and deprecate the old thing.
- in order for it to work, we need to ensure that only fully-qualified names are used by the client itself.

**Comment by SevInf** [comment]
All clashes except #15718 should be fixed in 5.1. That one can not be fixed in backward-compatible manner and have to wait until next major release.
