### ISSUE TITLE
Incorrect generated "StoryWhereUniqueInput" generated for the child model of a one-to-many relationship

### ISSUE THREAD

**Issue by craigmcc** [prisma/prisma#19830]
### Bug description

I have a not-unusual one-to-many relationship between a Library parent, and a Story child.  In schema.prisma, the Library includes the following (relevant) parts:

```prisma
model Library {
  id Int @id @default(autoincrement())
  ...
  name String @unique
  ...
  stories Story[]
  ...
}

model Story {
  id Int @id @default(autoincrement())
  ...
  libraryId Int
  ...
  library Library @relation(fields: [libraryId], references: [id], onDelete: Cascade)
  ...

  @@unique([libraryId, name])
}
```

The intent is that a Story name MUST be unique within the specific Library that Story belongs to, but the same name in different Libraries is fine.  (This all works great in the Sequelize based app I'm looking to convert to use Prisma.)

The problem comes when I want to perform a *prisma.story.findUnique()* call.  The *StoryWhereUniqueInput* that is generated looks like this:

```prisma
  export type StoryWhereUniqueInput = {
    id?: number
    libraryId_name?: StoryLibraryIdNameCompoundUniqueInput
  }
```

So, what is that *StoryLibraryNameCompoundUniqueInput* (with the made up *libraryId_name*) thing?  It looks like this:

```prisma
  export type StoryLibraryIdNameCompoundUniqueInput = {
    libraryId: number
    name: string
  }
```

(It generated a corresponding unique constraint in the database schema as well).

Now, let's try to do a findUnique call for a Story, based on the models described above.  What I *want* to be able to do is:

```ts
  const result = await prisma.story.findUnique({
    where: {
      id: storyId,
      libraryId: libraryId
  }
});
```

to make sure that the storyId the client requested really belongs to the specified libraryId.  This matters because particular users have access to the contents of particular libraries.  The query I want to do lets me check for both conditions at once.

BUT:  the generated *StoryWhereUniqueInput* doesn't let me do that.  It requires (in effect, knowing both the *libraryId* of the parent Library, **AND** the *name* of the Story I am trying to look that up.  I won't know that *name* if the Library and Story IDs are coming from some other relationship from some other models.

I consider that to be either a bug or a serious limitation.

### How to reproduce

The above description should allow you to create a small schema that mimics this behavior.

### Expected behavior

The generated *StoryWhereUniqueInput* should look like this:

```prisma
export type StoryWhereUniqueInput = {
  id?: number,
  libraryId: number,
  name?: string
```

With some sort of requirement that EITHER *id* or *name* of the Story should be required.  In all cases, *libraryId* should be required because if the relationship.

### Prisma information

See the description above for both the relevant schema.prisma excerpts and the TS code that I'd like to use.

### Environment & setup

- OS: macOS
- Database: Postgres
- Node.js version: 18.14.1 (but this is not likely to be relevant)
- 

### Prisma Version

```
4.15.0
```

**Comment by SevInf** [comment]
Hi @craigmcc!
The correct way to perform the query you want is:

```ts
  await prisma.story.findUnique({
    where: {
      libraryId_name: {
        libraryId: 123,
        name: 'Some name',
      },
    },
  })
```

See examples in [our documentation](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#get-the-user-record-with-firstname-of-alice-and-lastname-of-smith-unique). You can also [customize the name of the unique attribute](https://www.prisma.io/docs/concepts/components/prisma-schema/names-in-underlying-database#related-naming-indexes-and-primary-keys-for-prisma-client).
Hope it helps!

**Comment by craigmcc** [comment]
> Hi @craigmcc! The correct way to perform the query you want is:
> 
> ```ts
>   await prisma.story.findUnique({
>     where: {
>       libraryId_name: {
>         libraryId: 123,
>         name: 'Some name',
>       },
>     },
>   })
> ```
> 
> See examples in [our documentation](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#get-the-user-record-with-firstname-of-alice-and-lastname-of-smith-unique). You can also [customize the name of the unique attribute](https://www.prisma.io/docs/concepts/components/prisma-schema/names-in-underlying-database#related-naming-indexes-and-primary-keys-for-prisma-client). Hope it helps!

Thanks for the reply, but that is exactly what I do **not** want to do.  I want to query on a combination of libraryId+storyId, not libraryId+name.  Since storyId is also unique (it is the primary key), this will identify the story I want *and* guarantee that it belongs to the correct library.

The input in my API call (from the client) looks like:
```
GET /api/stories/:libraryId/:storyId
```

so I would have to go look up the name as an extra step.

**Comment by SevInf** [comment]
Apologies, I did not read your issue correctly. 
To do it you need [`extendedWhereUnique` preview feature](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#enable-the-ability-to-filter-on-non-unique-fields-with-userwhereuniqueinput). It will allow to have any other fields, unique or not, within `where` as long as you use at least one unique field. 
This feature also goes into GA in the next release and will be available without a flag starting from 4.16.

Let me know if that helps.

**Comment by craigmcc** [comment]
Thanks ... I will try that out later today.

**Comment by craigmcc** [comment]
Forgot to mention -- the extendedWhereUnique feature is exactly what I needed, so this issue can be closed.
