### ISSUE TITLE
Using model name `Key` and `Keys` results in incorrect inferring.

### ISSUE THREAD

**Issue by is-it-ayush** [prisma/prisma#19848]
### Bug description

If you write a model with name such as `Key` and `Keys` as in the following snippet 
```ts
model Key {
// ...
}

// or

model Keys {
// ...
}
```
and generate the types. It'll result in incorrect inferring ie. `Prisma.Prisma__KeysClient<any, never>` instead of the expected `Prisma.Prisma__KeysClient<Keys | null, never>`.  

Upon further investigation. I found that prisma has an internal type called `Key`, `Keys` that are also exported from the same `Prisma` namespace from where the generated types are exported. Now, this means this problem expands beyond just `Key` and `Keys` type and It would be impossible for anyone to use those names such as with my case where I tried to use `Key/Keys`. Internal Types essentially act as reserved keywords.

My sugesstion is the following:
- Shift internal types to a different namespace that isn't exported instead of Prisma. I'm not sure about the possibility of it as I'm not that good at global namespace's and libraries although I'll still present the suggestion to you.
- Move them to a sub namespace inside Prisma namespace. So, instead of `Prisma.Key`. It'll be `Prisma.Internal.Key`.

These are my best suggestions as I have no idea of prisma under the hood. Let me know if this helps. 😅

### How to reproduce

1. Clone the following [repro repository](https://github.com/is-it-ayush/repro-prisma-type-gen).
2. Install the packages via `pnpm install` and generate the types via `npx prisma generate`.
3. Goto [./src/server/api/routers/example.ts](https://github.com/is-it-ayush/repro-prisma-type-gen/blob/05b4c726a4be74366a0e22320ad71e982fe7e74c/src/server/api/routers/example.ts#L23).
4. On Line 17, hover over `record`. It'll work as expected where the type is `Example`.
5. On Line 23, hover over `keyrecord`. It'll result in `any`, instead of expected `Key` type.

### Expected behavior

The `keyrecord` type should be `Key` instead of `any`.

### Prisma information

Below is the `prisma/schema.prisma`. It can also be viewed in it's original place [here](https://github.com/is-it-ayush/repro-prisma-type-gen/blob/05b4c726a4be74366a0e22320ad71e982fe7e74c/prisma/schema.prisma).
<details>

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["jsonProtocol"]
}

datasource db {
    provider = "sqlite"
    // NOTE: When using mysql or sqlserver, uncomment the @db.Text annotations in model Account below
    // Further reading:
    // https://next-auth.js.org/adapters/prisma#create-the-prisma-schema
    // https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#string
    url      = env("DATABASE_URL")
}

model Keys {
    id        String   @id @default(cuid())
    name      String
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
}

model Example {
    id        String   @id @default(cuid())
    name      String
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
}

// Necessary for Next auth
model Account {
    id                String  @id @default(cuid())
    userId            String
    type              String
    provider          String
    providerAccountId String
    refresh_token     String? // @db.Text
    access_token      String? // @db.Text
    expires_at        Int?
    token_type        String?
    scope             String?
    id_token          String? // @db.Text
    session_state     String?
    user              User    @relation(fields: [userId], references: [id], onDelete: Cascade)

    @@unique([provider, providerAccountId])
}

model Session {
    id           String   @id @default(cuid())
    sessionToken String   @unique
    userId       String
    expires      DateTime
    user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
    id            String    @id @default(cuid())
    name          String?
    email         String?   @unique
    emailVerified DateTime?
    image         String?
    accounts      Account[]
    sessions      Session[]
}

model VerificationToken {
    identifier String
    token      String   @unique
    expires    DateTime

    @@unique([identifier, token])
}
```

</details>

Below is `src/server/db.ts`. It can also be viewed in it's original place [here](https://github.com/is-it-ayush/repro-prisma-type-gen/blob/05b4c726a4be74366a0e22320ad71e982fe7e74c/src/server/db.ts).

<details>

```ts
import { PrismaClient } from "@prisma/client";
import { env } from "~/env.mjs";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log:
      env.NODE_ENV === "development" ? ["query", "error", "warn"] : ["error"],
  });

if (env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
```

</details>

### Environment & setup

- OS: Tested on WSL running Debian 11.
- Database: SQLite
- Node.js version: v18.16.0

### Prisma Version

```
prisma                  : 4.14.0
@prisma/client          : 4.14.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/.pnpm/@prisma+engines@4.14.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/.pnpm/@prisma+engines@4.14.0/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.14.0-67.d9a4c5988f480fa576d43970d5a23641aa77bc9c
Default Engines Hash    : d9a4c5988f480fa576d43970d5a23641aa77bc9c
Studio                  : 0.484.0
Preview Features        : jsonProtocol
```

The github discussion that took place before I filed this issue is [here](https://github.com/prisma/prisma/discussions/19841).

**Comment by SevInf** [comment]
Hi @is-it-ayush.
We track type clashes in #12469 and a plan to fix them in #19811.
I am going to close this issue as a duplicate. You can follow the progress in both of the issues I mentioned.
