### ISSUE TITLE
Throw when passing in bogus filters

### ISSUE THREAD

**Issue by mmkal** [prisma/prisma#19847]
## Problem

I just spent about an hour debugging a confusing problem that ultimately turned out to be me running a `findFirstOrThrow` query with effectively no `where` filter.

I was doing this:

```ts
const thing = await prisma.thing.findFirstOrThrow({
  where: { id: input.thingId },
})
```

But because of an upstream bug, with a subtle accidental cast to `any`, `input` looked like `{ payload: { thingId: '...' } }` rather than `{ thingId: '...' }`. Nothing in the application failed, because `findFirstOrThrow` just ran with `where:  { id: undefined }` which is, I think, no filter at all, and just an instruction to turn the first arbitrary result.

## Suggested solution

Throw an error when passing in `undefined` to `where` filters. `undefined` doesn't correspond to anything valid in SQL, so it's not clear whether someone passing it in wants `where foo is null` or just no filter at all. In most cases, I think - like mine, it's just a mistake.

## Alternatives

Log a warning instead. Or make it configurable since I guess this is a breaking change.

## Additional context

I should also have been using `findUniqueOrThrow`, in this case. But that won't always be true.

**Comment by SevInf** [comment]
Hi @mmkal 
As unfortunate as it might've been in your case, in current Prisma version [`null vs undefined`](https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined) behaviour is intentional and documented. We might reconsider it for future major versions, but for now this not a bug.
