### ISSUE TITLE
Cannot generate in 4.16.0

### ISSUE THREAD

**Issue by jakeleventhal** [prisma/prisma#19863]
### Bug description

```
> prisma generate

Prisma schema loaded from prisma/schema.prisma
Error: 
✔ Generated Prisma Client (4.16.0 | library) to ./../../../node_modules/@prisma/client/ecominate in 227ms

Provided object is not a type literal: runtime.Types.DefaultSelection<AppDataPayload>
```

### How to reproduce

4.16.0

Run generate

### Expected behavior

Generates just fine

### Prisma information

```prisma
model AppData {
  id String @id @default(uuid())

  /// Whether or not the app is in maintenance mode.
  maintenance    Boolean @default(false)
  /// [StripeCustomerPortalConfig]
  /// The Stripe customer portal config.
  customerPortal Json?
  /// [StripeWebhookConfig]
  /// The Stripe webhook config.
  stripeWebhook  Json?
}
```

```ts
import './prismaJsonTypesNamespace';

import { Prisma, PrismaClient } from '@prisma/client/ecominate';

const client = (url: string | undefined) =>
  new PrismaClient(url ? { datasources: { db: { url } } } : undefined).$extends({
    model: {
      $allModels: {
        async exists<T>(this: T, where: Prisma.Args<T, 'findFirst'>['where']): Promise<boolean> {
          const context = Prisma.getExtensionContext(this);
          const result = await (context as any).count({ where });
          return result > 0;
        }
      }
    }
  });

export type ExtendedPrismaClient = ReturnType<typeof client>;

// Export the prisma client
export const getPrismaClient = (url?: string): ExtendedPrismaClient => {
  // @ts-ignore
  if (typeof window === 'undefined') {
    return client(url);
  }

  // @ts-ignore
  return null;
};

const prisma = getPrismaClient();
export default prisma;

export * from './types';
export * from '@prisma/client/ecominate';
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 18.12.0

### Prisma Version

```
4.16.0
```

**Comment by janpio** [comment]
Thanks for opening an issue this quickly.

Did you upgrade both `prisma` and `@prisma/client` to that version?
What does `prisma -v` output?

**Comment by aqrln** [comment]
Could you please also post the `generator` block of you schema? Are there any preview features enabled?

**Comment by SevInf** [comment]
I can not reproduce the issues with the provided data.
Also, "Provided object is not a type literal" error is not emitted by either Prisma or TS compiler itself. 
Search over Github tells me that it comes from [json-types-generator](https://github.com/arthurfiorette/prisma-json-types-generator) so I'd ask following question:

- Are you using `prisma-json-types-generator` on your project?
- If you, does error disapper if you comment it out in your schema?

If the answer to both of these questions is yes I'd suggest you'd [open an issue for the generator instead](https://github.com/arthurfiorette/prisma-json-types-generator/issues) - this is a third party package, not developed by our team.

**Comment by jakeleventhal** [comment]
> Thanks for opening an issue this quickly.
> 
> Did you upgrade both `prisma` and `@prisma/client` to that version? What does `prisma -v` output?

Both are 4.16.0

> Could you please also post the `generator` block of you schema? Are there any preview features enabled?

```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "../../../../node_modules/@prisma/client/ecominate"
  previewFeatures = ["fullTextSearch", "jsonProtocol"]
  binaryTargets   = ["native", "rhel-openssl-1.0.x"]
}
```

> I can not reproduce the issues with the provided data. Also, "Provided object is not a type literal" error is not emitted by either Prisma or TS compiler itself. Search over Github tells me that it comes from [json-types-generator](https://github.com/arthurfiorette/prisma-json-types-generator) so I'd ask following question:
> 
> * Are you using `prisma-json-types-generator` on your project?
> * If so, does error disappear if you comment it out in your schema?
> 
> If the answer to both of these questions is yes I'd suggest you'd [open an issue for the generator instead](https://github.com/arthurfiorette/prisma-json-types-generator/issues) - this is a third party package, not developed by our team.

Yes, issue is that. I will open an issue there. Thanks all.

**Comment by jakeleventhal** [comment]
P.S. @SevInf @aqrln @janpio I hope this feature gets implemented at least as a preview feature in prisma :)

**Comment by arthurfiorette** [comment]
Hahaha seems out that I need to update the generator 🤡

**Comment by janpio** [comment]
@jakeleventhal Yep, tracked in https://github.com/prisma/prisma/issues/3219 but not currently worked on - so no ETA. But will definitely happen one day.

**Comment by arthurfiorette** [comment]
To historical purposes, anyone coming here from the future, just update your `prisma-json-types-generator` to `^2.5.0`.
