### ISSUE TITLE
4.16.0 - release notes, invalid date of the live stream

### ISSUE THREAD

**Issue by michalbundyra** [prisma/prisma#19869]
### Bug description

In [release notes of 4.16.0](https://github.com/prisma/prisma/releases/tag/4.16.0)

![image](https://github.com/prisma/prisma/assets/7423207/230adeb8-e6af-48d3-b883-db80b917e977)

### How to reproduce

unless I've missed and it already was on the 1st of June.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
4.16.0
```

**Comment by janpio** [comment]
Thanks, fixed the date in the release notes to June 22nd based on the Youtube description.
