### ISSUE TITLE
4.16.0 Count query is not returning the right type when in a transaction

### ISSUE THREAD

**Issue by jakeleventhal** [prisma/prisma#19867]
### Bug description

When i use a transaction with an array arg, it doesnt return the correct type. It seems to be mixing up the types from both items in the transaction

### How to reproduce

Use prisma 4.16.0. This doesn't occur on earlier versions:
![image](https://github.com/prisma/prisma/assets/15133828/79fd13d8-57f4-4137-b12e-84b74f5bc53a)

### Expected behavior

Returned type for total is `number`

### Prisma information

See above

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 18.12.0

### Prisma Version

```
4.16.0
```

**Comment by Jolg42** [comment]
@jakeleventhal Thanks for the bug issue!

It's now published in our `patch-dev` version `4.16.1-dev.4`.

Let us know if this version fixes the issues, we're curious to get any feedback 🙌🏼 

Note: do not use in production, wait for the official `4.16.1` patch for that.

**Comment by millsp** [comment]
Hey @jakeleventhal, the version that is currently projected to be released is `4.16.1-dev.9`, could you please try that one?

**Comment by Jolg42** [comment]
@jakeleventhal If `4.16.1-dev.9` still causes some issues, please create a new bug issue with more information including your TypeScript & Next.js versions, so we can investigate this. (Thanks a lot for the reports 🙌🏼)

**Comment by millsp** [comment]
Are you perhaps using `query` `$allModels.$allOperations`?

**Comment by jakeleventhal** [comment]
`4.16.1-dev.9` seems to be working for me

but no, im not using that. im using this
```ts
const client = (url: string | undefined) =>
  new PrismaClient(url ? { datasources: { db: { url } } } : undefined).$extends({
    model: {
      $allModels: {
        async exists<T>(this: T, where: Prisma.Args<T, 'findFirst'>['where']): Promise<boolean> {
          const context = Prisma.getExtensionContext(this);
          const result = await (context as any).count({ where });
          return result > 0;
        }
      }
    }
  });
```

**Comment by Jolg42** [comment]
[`4.16.1`](https://github.com/prisma/prisma/releases/tag/4.16.1) patch release just happened.

Let us know if this version works as expected 🙌🏼

**Comment by jakeleventhal** [comment]
```
 Tasks:    102 successful, 102 total
Cached:    102 cached, 102 total
  Time:    5.7s >>> FULL TURBO
```

good to go :)
