### ISSUE TITLE
Prisma DMMF parses comments as fields docs

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma#1987]
## Bug description

I'm using latest alpha.980 and I've discovered that it now parses the comments `//` as docs for the fields:

```json
{
  "name": "author",
  "kind": "object",
  "dbNames": [],
  "isList": false,
  "isRequired": true,
  "isUnique": false,
  "isId": false,
  "type": "User",
  "relationName": "PostToUser",
  "relationToFields": [
    "id"
  ],
  "relationOnDelete": "NONE",
  "isGenerated": false,
  "isUpdatedAt": false,
  "documentation": "coAuthor  User?\r"
},
```

Even worse, it also parse whole comments of model/enum field as base level docs:

```json
{
  "name": "Role",
  "values": [
    {
      "name": "USER",
      "dbName": null
    },
    {
      "name": "ADMIN",
      "dbName": null
    }
  ],
  "dbName": null,
  "documentation": "/ Role enum comment\r\nUSER = \"User\"\r\nADMIN = \"Admin\"\r"
}
```

## Expected behavior

It should parse the docs and comments just like in `preview024`.

## Prisma information 

```prisma
model Post {
  uuid      String    @default(uuid()) @id
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  published Boolean
  title     String
  content   String?
  // coAuthor  User?
  author    User
  kind      PostKind?
}
```
```prisma
/// Role enum comment
enum Role {
  // USER = "User"
  USER
  // ADMIN = "Admin"
  ADMIN
}
```

## Environment & setup

- OS: [e.g. Mac OS, Windows, Debian, CentOS, ...] Win 10 x64
- Database: [PostgreSQL, MySQL, MariaDB or SQLite] ---
- Prisma version: [Run `prisma2 -v` to see your Prisma version] alpha 980
- Node.js version: [Run `node -v` to see your Node.js version] 13.11

**Comment by Sytten** [comment]
Yeah I saw that when working on https://github.com/prisma/prisma-engines/pull/615

**Comment by janpio** [comment]
Is that causing actual problems or just an inconvenience?

**Comment by Sytten** [comment]
This is also needed to keep the comments inline when using formatter.

**Comment by MichalLytek** [comment]
> Is that causing actual problems or just an inconvenience?

Yes, it causes a blocking problem as the TypeGraphQL integration uses the `documentation` property to emit GraphQL description as well as JSDoc description.

**Comment by MichalLytek** [comment]
I still can reproduce that on `beta.1` release 😞 

Also, looks like it has unwanted chars in the string too:
![image](https://user-images.githubusercontent.com/10618781/78111329-cad30000-73fc-11ea-806e-e77c66341ac2.png)

Is there any ETA for fixing the regression? Or am I forced to disable docs functionality for now to release new `typegraphql-prisma` version?

**Comment by mavilein** [comment]
This was a conscious change on our side. Before we had a differentiation between normal comments `//` and documentation comments `///`. We simplified this to only `//` which is treated as documentation.
The reason for this change was https://github.com/prisma/specs/issues/348
This was a big internal change to reformatting that would have lead to the loss of normal comments. Reintroducing this differentiation would be a complicated effort.

**Comment by MichalLytek** [comment]
> We simplified this to only // which is treated as documentation.

This makes no sense at all for me 😕 
Now when I want to disable some field during development by using `CTRL + /` in VSCode, the field definition is printed as the docs for the following field?

And as enum members does not support documentation feature, it extracts them to the enum name definition level description? 😱

**Comment by mavilein** [comment]
This is fixed in latest master.

**Comment by MichalLytek** [comment]
@mavilein This might be related - in `alpha.1236` the enum doc are not available in DMMF. It's listed in typings so I assume it's a bug, not a decission.

![image](https://user-images.githubusercontent.com/10618781/82794427-c06c3a00-9e72-11ea-8165-92556cc0929d.png)

![image](https://user-images.githubusercontent.com/10618781/82794450-c8c47500-9e72-11ea-8d85-65d6ca7ed7db.png)

![image](https://user-images.githubusercontent.com/10618781/82794464-cf52ec80-9e72-11ea-9f96-118bfe5095b8.png)

**Comment by pantharshit00** [comment]
@MichalLytek Opened https://github.com/prisma/prisma/issues/2549 so this doesn't get lost

**Comment by mavilein** [comment]
This is fixed now.
