### ISSUE TITLE
Prisma Schema Type inside a Type not generating a right Payload

### ISSUE THREAD

**Issue by Dsantosjaime** [prisma/prisma#19890]
### Bug description

Hi,

My file.dto:

```
import type { SiteInfosPayload } from '.prisma/client'

class ClientDto {
    @ApiProperty()
    role: ClientRole

    @ApiProperty()
    @ValidateIf(o => o.client.role === ClientRoleValue.MANAGER || o.client.role === ClientRoleValue.USER)
    @IsNotEmpty({ message: `'sites' doit être rempli quand le userType est ${ClientRoleValue.MANAGER} ou ${ClientRoleValue.USER}` })
    sites: SiteInfosPayload[]

    @ApiProperty()
    group: GroupInfos
}

export class CreateUserDto {
    [...]
    @ApiProperty()
    userType: UserType;

    @ApiProperty()
    @ValidateIf(o => o.userType === UserTypeValue.CLIENT)
    @IsNotEmpty({ message: `'client' doit être rempli quand le userType est ${UserTypeValue.CLIENT}` })
    client: ClientDto;
}
```

And here is the problem inside my service:
`async create(createUserDto: CreateUserDto) {
        return this.prisma.user.create({ data: createUserDto });
    }`
    
  The error: 
```
  error TS2322: Type 'CreateUserDto' is not assignable to type '(Without<UserCreateInput, UserUncheckedCreateInput> & UserUncheckedCreateInput) | (Without<...> & UserCreateInput)'.
  Type 'CreateUserDto' is not assignable to type 'Without<UserUncheckedCreateInput, UserCreateInput> & UserCreateInput'.
    Type 'CreateUserDto' is not assignable to type 'UserCreateInput'.
      Types of property 'client' are incompatible.
        Type 'ClientDto' is not assignable to type '(Without<ClientNullableCreateEnvelopeInput, ClientCreateInput> & ClientCreateInput) | (Without<...> & ClientNullableCreateEnvelopeInput)'.
          Type 'ClientDto' is not assignable to type 'Without<ClientNullableCreateEnvelopeInput, ClientCreateInput> & ClientCreateInput'.
            Type 'ClientDto' is not assignable to type 'ClientCreateInput'.
              Types of property 'sites' are incompatible.
                Type 'SiteInfosPayload[]' is not assignable to type 'Enumerable<SiteInfosCreateInput>'.
                  Type 'SiteInfosPayload[]' is not assignable to type 'SiteInfosCreateInput[]'.
                    Type 'SiteInfosPayload' is missing the following properties from type 'SiteInfosCreateInput': id, name, siret

22         return this.prisma.user.create({ data: createUserDto });
                                            ~~~~

  node_modules/.prisma/client/index.d.ts:3026:5
    3026     data: XOR<UserCreateInput, UserUncheckedCreateInput>
             ~~~~
    The expected type comes from property 'data' which is declared here on type '{ select?: UserSelect<DefaultArgs>; include?: UserInclude<DefaultArgs>; data: (Without<UserCreateInput, UserUncheckedCreateInput> & UserUncheckedCreateInput) | (Without<...> & UserCreateInput); }'
```
    
  If I'm understanding: the "SiteInfosPayload" is generated by Prisma but it miss my fields 'id', 'name', 'siret' but as you can see it's well declared on the Schema ...

### How to reproduce

During run time, typescript throw me the previous error .

### Expected behavior

Obviously I want my DTO working with my Schema.

### Prisma information

Here is my Schema :
```
model User {
  id         String      @id @default(auto()) @map("_id") @db.ObjectId
 [...]
  userType   UserType
  client     Client?

  @@map("staffUser")
}

type Client {
  [...]
  sites SiteInfos[]
}

type SiteInfos {
  id    String
  name  String
  siret String
}
```

### Environment & setup

NestJs / TypeScript
Database: MongoDb
nodeJs: v16.20.0

### Prisma Version

prisma                  : 4.16.0
@prisma/client          : 4.16.0

**Comment by Dsantosjaime** [comment]
FYI, if I remove `sites SiteInfos[] ` from my schema it's working well again.
But I want it here, and I want to put some decorator on this field on my file.DTO.

**Comment by Dsantosjaime** [comment]
I'm just starting this project. I can't tell you, would you want me to try to downgrade ?

**Comment by millsp** [comment]
You could try that yes, I am trying to narrow down if it is related to a recently fixed issue https://github.com/prisma/prisma/issues/19880

**Comment by millsp** [comment]
Could I also please ask you to give it a try with `@prisma/client@4.16.1-dev.7`, which contains the fix?

**Comment by Dsantosjaime** [comment]
Yes I don't have the error either on this version

**Comment by millsp** [comment]
Great! Thanks for the help. We will be publishing a patch soon. Let me know if everything worked with your project.

**Comment by Dsantosjaime** [comment]
```
class ClientDto {
    @ApiProperty()
    role: ClientRole

    @ApiProperty()
    @ValidateIf(o => o.client.role === ClientRoleValue.MANAGER || o.client.role === ClientRoleValue.USER)
    @ArrayNotEmpty({ message: `'sites' doit être rempli quand le userType est ${ClientRoleValue.MANAGER} ou ${ClientRoleValue.USER}` })
    sites: SiteInfos[]

    @ApiProperty()
    group: GroupInfos
}
```

Thanks to your fix, I'm trying to add this to my DTO. But It's not seem to work. I don't know if you could see the problem.
It's more a NestJs / Typescript problem maybe.

**Comment by millsp** [comment]
Not sure what the error is. If this is also not working on `4.15.0`, would you mind creating a conversation for your questions, with more context on the failures. Then I can close this issue and we help you from there?

**Comment by Viriatto** [comment]
I'm also experiencing the same issue, only started happening after updating to `4.16.0`

**Comment by millsp** [comment]
Thanks for the confirmations, I'll mark this issue as fixed.

**Comment by Jolg42** [comment]
[`4.16.1`](https://github.com/prisma/prisma/releases/tag/4.16.1) patch release just happened.

Let us know if this version works as expected 🙌🏼

**Comment by mayerlench** [comment]
This is still broken

**Comment by mayerlench** [comment]
> [`4.16.1`](https://github.com/prisma/prisma/releases/tag/4.16.1) patch release just happened.
> 
> Let us know if this version works as expected 🙌🏼

This is still broken in 14.16.1

**Comment by Jolg42** [comment]
@mayerlench Could you open a new bug issue and provide more information?
We will need to reproduce your issue to fix it.
