### ISSUE TITLE
'Type instantiation is excessively deep and possibly infinite.' when using Json field

### ISSUE THREAD

**Issue by allansson** [prisma/prisma#19905]
### Bug description

When accessing a Json field in the generated client typescript reports a type error with the message 'Type instantiation is excessively deep and possibly infinite.'.

<img width="818" alt="image" src="https://github.com/prisma/prisma/assets/2014167/1b1fb9cd-5781-4a31-b877-f044e1d4e9a7">

I've tested it in typescript 4.8, 4.9 and 5.1 with the same result.

### How to reproduce

1. Create a model with a Json field
2. Generate a new client
3. Access the field in code

### Expected behavior

Accessing the field should not generate a type error.

### Prisma information

Schema:

```prisma
model Release {
  id Int @id @default(autoincrement())

  rollout  Rollout[]
}

model Rollout {
  id Int @id @default(autoincrement())

  condition Json?

  release   Release @relation(fields: [releaseId], references: [id])
  releaseId Int
}
```

Code:

```ts
const release = await prisma.release.findUnique({
  where: { id: Number(params.id) },
  include: {
    rollout: true,
  },
});

const conditions = release.rollout.map(rollout => rollout.condition);
```

### Environment & setup

- OS: macOS 
- Database: PostgreSQL 
- Node.js version: v16.19.0 

### Prisma Version

```
prisma                  : 4.16.0
@prisma/client          : 4.16.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/migration-engine-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.0-66.b20ead4d3ab9e78ac112966e242ded703f4a052c
Default Engines Hash    : b20ead4d3ab9e78ac112966e242ded703f4a052c
Studio                  : 0.484.0
```

**Comment by allansson** [comment]
The problem appears to be this type definition: https://github.com/prisma/prisma/blob/785905e7e86b8d94627fb18e3d09d860a710dc46/packages/client/src/runtime/core/types/Utils.ts#L52

The problem disappears if I change it to the following in my generated client:

```ts
export type JsonObject = { [key: string]: JsonValue } 
```

I think the problem is that `Key in string` means each value in the union of every possible string, causing typescript to try to infinitely expand the type.

**Comment by SevInf** [comment]
Hi @allansson.
I can not reproduce the issue with the info you provided. Schema I am using:

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/.prisma/client"
}

datasource db {
  provider = "postgres"
  url      = env("TEST_POSTGRES_URI")
}

model User {
  id    String  @id
  name  String
  things Thing[]
}

model Thing {
  id     String @id
  userId String
  data   Json

  user User @relation(fields: [userId], references: [id])
}
```

Code:
```ts
  const user = await prisma.user.findUnique({
    where: {
      id: '1'
    },
    include: {
      things: true
    }
  })
  return user?.things.map(thing => thing.data)
```

typechecks correctly. Could you please provide a reproduction repo where we could see it happenening?

**Comment by allansson** [comment]
I dug a bit deeper while trying to set up a reproduction repo. 

Seems like my issue actually comes from the way that [remix](https://remix.run) is inferring types. I only thought that it was an issue with prisma because I found [this comment](https://github.com/prisma/prisma/issues/17061#issuecomment-1583835608). 

Also, it turned out that my fix wasn't a fix at all so there's nothing that can be done here.

I will close this and raise an issue in the remix repo instead.

**Comment by vatheara** [comment]
<img width="751" alt="image" src="https://github.com/prisma/prisma/assets/18604920/63f67d3a-fc67-4168-96ef-75b9b2997352">

I still face this issue when using Json field.
seem the issues relate to this was closed but I still can't find any resolution. do I miss something or this is not yet solved?

**Comment by CNLHC** [comment]
> Error: Type instantiation is excessively deep and possibly infinite. <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/18604920/299986282-63f67d3a-fc67-4168-96ef-75b9b2997352.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDM4MDQsIm5iZiI6MTcwOTA0MzUwNCwicGF0aCI6Ii8xODYwNDkyMC8yOTk5ODYyODItNjNmNjdkM2EtZmM2Ny00MTY4LTk2ZWYtNzViOWIyOTk3MzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE0MTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MmU1ZmQ0ODQ4M2Q3ODQzY2ZhYmZjY2U1NDYzYWEwNmRhZDFiY2MxMGQ1NTM1ZjYzMjc3MGY2NjIyZjRjNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CGucJe4WN7XUixjFBxFwbnPTvjm_LaXj12itctfa7dw">
> 
> I still face this issue when using Json field. seem the issues relate to this was closed but I still can't find any resolution. do I miss something or this is not yet solved?

Same issue. I think this problem may be related to the https://github.com/microsoft/TypeScript/issues/34933#issuecomment-1934949228

**Comment by diegoag64** [comment]
I am having this issue too, any updates?

**Comment by CNLHC** [comment]
> I am having this issue too, any updates?

Are you using trpc or other library that could possibily touch the Prisma generated type?

I encountered a similary problem and found that Prisma's Json type is not the root cause.

**Comment by diegoag64** [comment]
> trpc or other libraries that could possibily touch the Prisma g

Yeah Im using trpc aswell, but the issue is def related to the prisma json fields

**Comment by CNLHC** [comment]
> > trpc or other libraries that could possibily touch the Prisma g
> 
> Yeah Im using trpc aswell, but the issue is def related to the prisma json fields

No, the root cause of this problem is "Using trpc to infer Prisma json fields" , not Prisma Json field type itself, I think you can easily test it.

If you are using trpc, I think we are facing the same problem. After struggling with this error for about one or two weeks, I found two solution

1. Avoiding return Json Field type directly from trpc, use `unknown` or `any` instead. It makes sense because trpc can not ensure the methods associated with `JsonField` type can be serialized.
2. Using [prisma-json-types-generator](https://github.com/arthurfiorette/prisma-json-types-generator): if strong type is really important to you, you can try this library and substitute the `JsonValue` with some simple and deterministic types, which can be handled by the trpc type system.

**Comment by vendramini** [comment]
> 1. Avoiding return Json Field type directly from trpc, use `unknown` or `any` instead. It makes sense because trpc can not ensure the methods associated with `JsonField` type can be serialized.
> 2. Using [prisma-json-types-generator](https://github.com/arthurfiorette/prisma-json-types-generator): if strong type is really important to you, you can try this library and substitute the `JsonValue` with some simple and deterministic types, which can be handled by the trpc type system.

Hey guys.

How do you do to make trpc return unknown and to not infer prisma types in a basic `return prisma.etc()'?

**Comment by Craig1f** [comment]
This still needs to be fixed. Something as simple as, the ability in the schema to mark the field as "any" or "unknown" so TS doesn't try to interpret what it is. Our use-case is that we're storing the document json from a Prosemirror document that we're editing, and we want to use jsonb to do it.

**Comment by inker-kuo** [comment]
Any plan to fix tRPC+prisma with JSON type case? Or its discussion is in a separate thread?

**Comment by piscopancer** [comment]
still broken when used with trpc

**Comment by tonybruess** [comment]
Still broken for me. Relevant related issue: https://github.com/trpc/trpc/issues/6804

**Comment by monarchwadia** [comment]
I just add explicit output validation and type inference on the TRPC route, as a workaround. It's ugly as sin, I admit.

```ts
    list: publicProcedure
    // explicit output validation. probably not strictly necessary.
    .output(z.array(RepositoryOutput)).query(async () => {
      const repositories = await prismaClient.repository.findMany();
      // z.infer to cast the type. this is definitely necessary.
      return repositories as z.infer<typeof RepositoryOutput>[];
    }),
```

**Comment by sidwebworks** [comment]
Using typed fields was a good enough solution for me https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/working-with-json-fields#typed-json-fields
