### ISSUE TITLE
Use constraint names to name relation fields

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1990]
Assume SQL (Postgres) like this:

```sql
CREATE TABLE "public"."User" (
  id SERIAL PRIMARY KEY,
  name TEXT
);

CREATE TABLE "public"."Post" (
  id SERIAL PRIMARY KEY,
  title TEXT,
  "authorId" INTEGER,
  CONSTRAINT author FOREIGN KEY ("authorId") REFERENCES "public"."User" (id)
);
```

This is currently introspected to:

```prisma
model Post {
  authorId Int?
  id       Int     @default(autoincrement()) @id
  title    String?
  User     User?   @relation(fields: [authorId], references: [id])
}

model User {
  id   Int     @default(autoincrement()) @id
  name String?
  Post Post[]
}
```

The `author` constraint name is not used in the resulting Prisma schema. 

It could influence how we name the relation field:

```diff
model Post {
  authorId Int?
  id       Int     @default(autoincrement()) @id
  title    String?
- User     User?   @relation(fields: [authorId], references: [id])
+ author   User?   @relation(fields: [authorId], references: [id])
}

model User {
  id   Int     @default(autoincrement()) @id
  name String?
  Post Post[]
}
```

(In the other direction Migrate should make sure to use this as well of course.)

**Comment by janpio** [comment]
Well, for MySQL the name seems to be unique _per database_:

> The CONSTRAINT symbol value, if defined, must be unique in the database.

https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html#foreign-key-identifiers

That will only work if each of the relation names are unique :/

**Comment by albertoperdomo** [comment]
The idea itself is interesting.

>That will only work if each of the relation names are unique :/

That limitation indeed makes this less valuable or less likely valuable.


I also don't know if many people use custom names for constraints, I intuitively think it's common to just let the DB use its [defaults](https://til.cybertec-postgresql.com/post/2019-09-02-Postgres-Constraint-Naming-Convention/).

For Postgres, these defaults are not very pretty: `{tablename}_{columnname(s)}_{suffix}` with the suffix being `fkey` for foreign keys.

Example:

```
test=> CREATE TABLE users (
test(>   id integer primary key
test(> );
CREATE TABLE
test=>
test=> CREATE TABLE posts (
test(>   user_id integer references users
test(>
test(> );
CREATE TABLE
test=> \d
       List of relations
 Schema | Name  | Type  | Owner
--------+-------+-------+-------
 public | posts | table | test
 public | users | table | test
(2 rows)

test=> \d posts
                Table "public.posts"
 Column  |  Type   | Collation | Nullable | Default
---------+---------+-----------+----------+---------
 user_id | integer |           |          |
Foreign-key constraints:
    "posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id)

test=>
```

So using the constraint name to name the relation in this case would yield an API like `post.posts_user_id_fkey`.
