### ISSUE TITLE
Setting Collation when Creating Migration Files Using Prisma

### ISSUE THREAD

**Issue by Sangun-Kang** [prisma/prisma#19916]
## Overview
Method to set Collation when creating migration files using Prisma

## Details
Migration files made with Prisma led to production issues. A year back, I migrated from TypeORM to Prisma. I made new tables using Prisma for additional features which worked fine locally. However, running `prisma migrate deploy` in production resulted in an error related to foreign key constraints.

Here's the error from the _prisma_migrations table:

```
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20230614082944_init

Database error code: 3780

Database error:
Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'user_detail_user_id_fk' are incompatible.

Please check the query number 2 from the migration file.

   0: sql_migration_connector::apply_migration::apply_script
           with migration_name="20230614082944_init"
             at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:105
   1: migration_core::commands::apply_migrations::Applying migration
           with migration_name="20230614082944_init"
             at migration-engine/core/src/commands/apply_migrations.rs:91
   2: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:200
```

Investigating the DB, I noticed the existing tables used `utf8mb4_0900_ai_ci` collation, whereas Prisma's generated query set `utf8mb4_unicode_ci` as the default.

Example query by Prisma:
```sql
-- CreateTable
CREATE TABLE `user_details` (
    ...
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
...
```
Is utf8mb4_unicode_ci Prisma's default charset collation? If yes, why?

I modified the generated migration file to fix this issue, but it doesn't seem like the best solution. Also, I couldn't find any information regarding collation settings in the official documentation.

Any advice for future resolution?

**Comment by janpio** [comment]
Hey @Sangun-Kang, that is indeed the default collation Prisma uses when generating migration files - and the only way to influence that is to modify the migration files after the fact. Sorry.

We have a bunch of issue about changing that here: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+collation%22+sort%3Areactions-%2B1-desc Please add a 👍 to the ones that are relevant to you. Thank you.

**Comment by Sangun-Kang** [comment]
Thanks for your comment!!!
