### ISSUE TITLE
Command to export SQL schema

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1992]
To debug a problem it is often beneficial to have a SQL schema of the underlying database instead of just the Prisma schema (which would need to be migrated manually, which could be another source of errors).

Maybe we could build a command that outputs the full SQL schema of the connected database, to avoid having to tell people to use a command line or GUI tool to do the same.

(Yes, our own exporter might be another source for errors, but that should be easy enough to validate during development of this command)

**Comment by schickling** [comment]
Same idea as for Nexus: https://github.com/graphql-nexus/nexus-future/issues/527

**Comment by janpio** [comment]
Internal note: Explain how to use `diff` to achieve this.
