### ISSUE TITLE
Command to test connection string and help debug

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1993]
Getting the connection string of your database right can be quite a challenge if you never had to deal with that in the past. Typical problems are the hostnames, the general syntax of the connection string, and especially special settings for SSL and similar.

We could build a command that just tries to connect to the database and tries to help debug the connection string. It could check for: Protocol, Hostname, Port, correct format of query string (`?..=..?..=..` vs `?..=..&..=..`), correct usage of SSL query strings, missing schema etc.

**Comment by schickling** [comment]
This should be a part of `prisma status` (see https://github.com/prisma/specs/issues/400)

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/1994

**Comment by anishagg17** [comment]
@janpio If I have not mistaken, is https://github.com/prisma/prisma/blob/master/src/packages/client/src/utils/setupMSSQL.ts the correct file to operate? I'm new to the codeBase and if you could guide me to fix this issue, I would be very happy.

**Comment by janpio** [comment]
What I described above, is probably not super interesting to us any more - it does not seem to be a big problem to users after all.
