### ISSUE TITLE
Prisma requires to install bun when generating client library 

### ISSUE THREAD

**Issue by Coder246** [prisma/prisma#19945]
### Bug description

When running `npx prisma generate` it outputs:

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
[ni] Detected bun but it doesn't seem to be installed.

✔ Would you like to globally install bun (​https://bun.sh​)? … no

Than the execution will terminates

### Expected behavior

Generate the client libraries

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native", "darwin-arm64", "linux-musl", "linux-arm64-openssl-1.1.x"]
  previewFeatures = ["extendedWhereUnique"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

...
```

### Environment & setup

- OS: macOS Ventura
- Database: PostgreSQL
- Node.js version: v16.18.0

### Prisma Version

```
prisma                  : 4.16.1
@prisma/client          : Not found
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.0-66.b20ead4d3ab9e78ac112966e242ded703f4a052c
Default Engines Hash    : b20ead4d3ab9e78ac112966e242ded703f4a052c
Studio                  : 0.484.0
Preview Features        : extendedWhereUnique
```

**Comment by janpio** [comment]
Uh, that is a surprising side effect of the package manager detection logic we are using I think.
Do you have anything in that project that could indicate to it that you want to use bun?

**Comment by Coder246** [comment]
When installing the package directly it works. Thanks a lot.

But I'm curious where does this message come from. When searching for the error it seems no one has ever encountered this issue.

I never installed bun on this machine. This something wrong with my project configuration? Unter which circumstances is bun required?

**Comment by janpio** [comment]
That is the big question - it definitely should not be at all.

We recently switch to a package called `ni` that should help us with detecting the correct package manager (npm, yarn, pnpm etc) and it somehow seems to think yours should be bun - and then even suggests to install it globally. I don't think we anticipated that behavior, and I think we should not do that - so I raised it internally and we will figure out what is going on.

Can you potentially put your project in a GitHub repo so we can try to reproduce?
Does it happen as well when you create a new project (`mkdir foo && cd foo && npm init -y && npx prisma init`)?

**Comment by Coder246** [comment]
Unfortunately I cannot disclose the source code. After investigating the `ni` source code I found out how the detection works. Based on the lockfile the package manager is selected. Than I saw that several months ago someone committed a bun.lockb to the repository. Likely for testing. Because `ni` handles `bun` with prio 1 this issue occurs. 

See here:
https://github.com/antfu/ni/blob/main/src/agents.ts#L88

Thanks for helping me out.

btw when I agree to bun installation it says -D is an unknown option, but that is likely another issue

**Comment by janpio** [comment]
I'll reopen this, so we can investigate removing this prompt and replacing it with a warning or info message maybe - that feels more appropriate in this case.

The `-D` problem indeed sounds unrelated, probably `ni` is using an invalid installation command or something. If you are really motivated, you could report that in their repo.
