### ISSUE TITLE
[Introspection] Do not print `@default("")` for String fields

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1995]
Right now we introspect an empty string default for String fields that are NOT NULL. It might be worth investigating if this is always the database behavior and skip this instead of really printing it to the schema.

PostgreSQL example:
```prisma
model Post {
  id        String   @id
  title     String   @default("")
  content   String?
}
```

**Comment by matthewmueller** [comment]
Hmm, from a database perspective, these are different cases:

```
model Post {
  title     String // implies a required string
}
```

```
model Post {
  title     String? // implies string or null
}
```

```
model Post {
  title     String @default("") // implies string or null (with "" filled in by the database)
}
```

Because defaults are Prisma-level, does that change these cases?

**Comment by do4gr** [comment]
I just checked this again, and this does not happen anymore. Migrate used to always set default values on the db level even if they were not specified in the schema. These were then picked up by introspection. I assume this is what you ran into. Migrate does not do this anymore and introspection never had logic to add defaults that are not present in the db. Closing this therefore.

**Comment by matthewmueller** [comment]
Does introspection still pick this up if `DEFAULT ''` is in the database?
