### ISSUE TITLE
deleteMany generates double WHERE filter

### ISSUE THREAD

**Issue by anton-johansson** [prisma/prisma#19950]
### Bug description

I'm running a `deleteMany` in a transaction, like this:
```typescript
    await client.$transaction(async transaction => {
        const rowsToDelete = [1, 2, 3];
        await transaction.myTable.deleteMany({
            where: {
                myId: {
                    in: rowsToDelete,
                },
            },
        });

        // more calls within the transaction (but not relevant to the issue)
    });
```

I can see that Prisma generates the following query:

```
Executed query (37 ms): DELETE FROM [dbo].[MyTable] WHERE ([dbo].[MyTable].[myId] IN (@P1,@P2,@P3) AND [dbo].[MyTable].[myId] IN (@P4,@P5,@P6)), with parameters: [1,2,3,1,2,3]
```

I also see two identical `SELECT` statements before the `DELETE`:

```sql
Executed query (58 ms): SELECT [dbo].[MyTable].[myId] FROM [dbo].[MyTable] WHERE [dbo].[MyTable].[myId] IN (@P1,@P2,@P3), with parameters: [9,10,11]
Executed query (10 ms): SELECT [dbo].[MyTable].[myId] FROM [dbo].[MyTable] WHERE [dbo].[MyTable].[myId] IN (@P1,@P2,@P3), with parameters: [9,10,11]
```

I don't see why any of those select statements are needed?

### How to reproduce

Simply run `deleteMany` with an array of IDs.

### Expected behavior

The double filter doesn't really cause any problems, but it feels redundant and wasteful (doubt it has any direct performance impact, though). I expect the query to be just:

```sql
DELETE FROM [dbo].[MyTable] WHERE ([dbo].[MyTable].[myId] IN (@P1,@P2,@P3)), with parameters: [1,2,3]
```

And I also expect it to generate zero `SELECT` statements before the actual `DELETE`, because it's not really needed, right?

### Prisma information

```prisma
model MyTable {
    myId                 Int                 @id @default(autoincrement())
    myName               String              @unique @db.NVarChar(20)
}
```

### Environment & setup

- OS: Ubuntu 23.04
- Database: Microsoft SQL Server
- Node.js version: v18.1.0

### Prisma Version

```
4.9.0
```

I have also tried the latest, `4.16.1`.

**Comment by TestSubject06** [comment]
Chiming in here to +1 this issue. This is somewhat wasteful for users attached to databases that charge on row reads, as this can multiply the rows being read.

**Comment by Weakky** [comment]
Hey, we've just [fixed](https://github.com/prisma/prisma-engines/pull/4249) this issue! It'll be available in the next release of Prisma.

Thanks for reporting 🙏
