### ISSUE TITLE
User questions: Engine not found (tooling)

### ISSUE THREAD

**Issue by immjs** [prisma/prisma#19961]
### Have you tried to copy the engine in the suggested location? Did that work?
The file has already been copied when the error appeared

### Which package manager are you using?
`npm` - version 9.2.0

### Is your workspace a monorepo setup?
My setup is hosting multiple packages in a single workspace

### Is a bundler in use? If yes, which one?
No

### Is a framework in use? If yes, which one?
No

### Your project uses TypeScript or just JavaScript?
My project is currently fully running on typescript

### When you saw our message, did it happen locally or in deployment?
*The message was "Please help us by answering a few questions".*

### Where is your project deployed?
On a VPS running ubuntu on openstack nova

**Comment by jkomyno** [comment]
Hi @immjs, I'd love to help but I'm missing quite a lot of context on this issue. Could you please close this issue in favor of a new one following [this template](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml)? In particular, details about the exact error message you're facing (with a related stacktrace), the version of Prisma you have installed, and the exact version of your Node.js instance and operating system is particularly important for us to understand and solve this problem. Thank you!

**Comment by immjs** [comment]
Hi,
Turns out, it was a UNIX permission issue on my part.
The program would setuid to a user that was different from the one in which the node_modules was set to allow
Apologies for any time wasted 😅

On the template, I followed the one that was indicated to me by the prisma CLI:
https://pris.ly/engine-not-found-tooling-investigation
I thought since the discussion was empty I should have used [issue from discussion]

**Comment by janpio** [comment]
Interesting, we have not considered that - the UI is indeed not super clear.
Just for the record, it would have been fine to comment on the discussion and just copy-paste the questions so you can answer them in a comment.
