### ISSUE TITLE
Strategy to fix old existing Prisma Schemas (for new relations since alpha 978)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1996]
Existing schemas with relations do not work since alpha 978 any more, they need to be reintrospected and/or adapted.

Example:
```prisma
model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
  age   Int?
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(true)
  title     String
  content   String?
  author    User?
}
```
becomes
```prisma
model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
  age   Int?
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(true)
  title     String
  content   String?

  authorId  String?  @map("author")
  author    User?    @relation(fields: [authorId], references: [id])
}

```

This is the diff:
```diff
model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
  age   Int?
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(true)
  title     String
  content   String?
- author    User?
+
+ authorId  String?  @map("author")
+ author    User?    @relation(fields: [authorId], references: [id])
}
```

This could be generalized into a script:

For an old invalid schema (forward relation without `@relation`, or with `@relation` that does not have a `fields` array) 
- add a relation scalar field with 
  - name `foo` (above: `authorId`),
  - the same type as the `references` field (above `User.id`, so `String`), 
  - the same arity as the existing relation field (above optional, so `?`)
  - and `@map` to the column with the same name as the relation field (above `@map("author")`)
- add a `@relation` attribute to the existing relation field
  - with a `fields` array that uses the new relation scalar field `foo` (above `fields: [authorId]`)
  - and `references` the correct field (optional)

**Comment by schickling** [comment]
Whenever we'll introduce a breaking change like this, we should help user to upgrade. I'd like to introduce a command `prisma upgrade` for this purpose.
