### ISSUE TITLE
Could not retrieve alloc::string::String from Value

### ISSUE THREAD

**Issue by jhd4tmr** [prisma/prisma#19977]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v17.3.0            | 
| Prisma CLI  | 4.16.1             | 
| Engine      | b20ead4d3ab9e78ac112966e242ded703f4a052c| 

## Error
```
RustPanic: Error in migration engine.
Reason: [/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mysql_common-0.29.2/src/value/convert/mod.rs:175:23] Could not retrieve alloc::string::String from Value

```

**Comment by jkomyno** [comment]
Thanks @jhd4tmr, closing this as a duplicate in favor of https://github.com/prisma/prisma/issues/19576.
Could you please add some comments [there](https://github.com/prisma/prisma/issues/19576) about what triggered this error? Thanks.
