### ISSUE TITLE
Execute $queryRaw query from a variable

### ISSUE THREAD

**Issue by Kukunin** [prisma/prisma#19970]
## Problem

I have a SQL query stored in a variable (it's kept outside of the source code files).
I need a way to execute an arbitrary SQL query with the support of variables (special characters escaping, security, etc).

For example: 

```javascript
  const query = "SELECT * FROM tasks WHERE user_id = $1"
  const variables = ["123"]
  await result = await prisma.$queryRaw(query, variables) // this is impossible
```

The irony is that the original `postgres` interface is exactly what I need. Prisma uses the [sql-template-tag](https://github.com/blakeembrey/sql-template-tag) library to convert the template tag to the format I have.

```javascript
const query = sql`SELECT * FROM books WHERE id = ${id}`;

query.sql; //=> "SELECT * FROM books WHERE id = ?"
query.text; //=> "SELECT * FROM books WHERE id = $1"
query.values; //=> [id]

pg.query(query); // Uses `text` and `values`.
mysql.query(query); // Uses `sql` and `values`.
```

## Suggested solution

It would be cool to have either an overloaded signature for `prisma.$queryRaw` function that accepts a query with values. Or to have another method that has the signature.

## Alternatives

As an alternative, if I could get access to the original `pg` object so I can run `pg.query` directly, it would solve my need. But I doubt it's possible because of the nature of Prisma architecture (interprocess communication AFAIK). I don't want to create another connection and just re-use one from the existing pool. 

As today's workaround, I'm trying to convert the query with variables into `TemplateStringsArray` and mimic the tag template function call, so then `sql-template-tag` would convert it back to the same, hopefully, shape. But this looks like an obvious hack.

## Additional context

I use PostgreSQL.

**Comment by Kukunin** [comment]
For anyone who has the same issue, I was able to workaround this by this code:

```typescript
const toTemplateStringsArray = (array: string[]): TemplateStringsArray => {
  const stringsArray: any = [...array]
  stringsArray.raw = array
  return stringsArray as TemplateStringsArray
}

// @see https://github.com/prisma/prisma/issues/19970
export const query = async (query: string, variables: any[] = []) => {
  return prisma.$queryRaw(toTemplateStringsArray(query.split('?')), ...variables)
}

it('runs simple queries', async () => {
  // this is discouraged syntax
  const result = await query(`SELECT * FROM commie.journeys WHERE id = '${journey.id}'`)
  expect(result).toEqual([expect.objectContaining({ id: journey.id, name: journey.name })])
})

it('returns query result', async () => {
  const result = await query('SELECT * FROM commie.journeys WHERE id = ?::uuid', [journey.id])
  expect(result).toEqual([expect.objectContaining({ id: journey.id, name: journey.name })])
})
```

here I pick MySQL's syntax with `?` instead of `$1`. Once the right solution will be there, it's easy to convert from one format to another.

**Comment by SevInf** [comment]
Hi @Kukunin!
I think what you want is [`$queryRawUnsafe`](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#queryrawunsafe). It has the exact interface you need `(string, variables)`.

Let me know if it helps, I am gonna close this issue meanwhile.

**Comment by Kukunin** [comment]
@SevInf thank you for the answer. why is it `unsafe` then? I mean, if it does the interpolation and escaping.
