### ISSUE TITLE
$queryRaw/$queryRawUnsafe is modifying query string and causing DB error

### ISSUE THREAD

**Issue by cjscheller** [prisma/prisma#19991]
### Discussed in https://github.com/prisma/prisma/discussions/19637

<div type='discussions-op-text'>

<sup>Originally posted by **cjscheller** June  6, 2023</sup>
I am trying to execute the following query as a raw database query due to some limitations of the Prisma client related to groupBy. The database is a [Planetscale](https://planetscale.com)/Vitess MySQL v8 instance.

```sql
SELECT OrderItem.productId, Product.name, Product.description, Product.price, Product.imageUrl, SUM(OrderItem.quantity) as quantity
FROM Invoice
INNER JOIN \`Order\` on Invoice.id = \`Order\`.invoiceId
INNER JOIN OrderItem on \`Order\`.id = OrderItem.orderId
INNER JOIN Product on OrderItem.productId = Product.id
WHERE Invoice.id = ${invoiceId}
GROUP BY OrderItem.productId;
```

Whenever I execute this query through a `$query` or `$queryRaw`, I am receiving the following error (with added formatting):

```js
Invalid `prisma.$queryRawUnsafe()` invocation:

Raw query failed. 
Code: `1055`. 
Message: `target: {db_name}.-.primary: vttablet: rpc error: code = InvalidArgument desc = Expression #2 of SELECT
list is not in GROUP BY clause and contains nonaggregated column 'Product.name' which is not functionally dependent 
on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (errno 1055) (sqlstate 42000) (CallerID: ...: 
Sql: "select OrderItem.productId, Product.`name`, Product.description, Product.price, Product.imageUrl, sum(OrderItem.quantity
 as quantity from Invoice join `Order` on Invoice.id = `Order`.invoiceId join OrderItem on `Order`.id = OrderItem.orderId join
Product on OrderItem.productId = Product.id where 1 != 1 group by OrderItem.productId", 
BindVars: {REDACTED}`
```

I have attempted: 
- Disabling `ONLY_FULL_GROUP_BY` in MySQL
- Using `$queryRaw` with templated variables
- Using `$queryRawUnsafe` with a plain string (no variables)
- Using `$queryRawUnsafe` with a [parameterized query](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access?query=update%20prisma&page=1#parameterized-queries). 
- Updating Prisma to 4.15.0

No matter what I do, I can not figure out how/where/why the WHERE clause of the query is updated from `WHERE Invoice.id = ${invoiceId}` to `where 1 != 1`. The query works when I run it manually in a MySQL client (with a WHERE clause such as `WHERE Invoice.id = 5`, and the MySQL 1055 error is only thrown when the where clause is set as `1 != 1`. </div>

Can anyone help me figure out what is going on? Thanks!</div>

**Comment by fated-x** [comment]
@cjscheller I was struggling with this for hours this evening and finally solved it by wrapping one of my column names that happens to be a keyword in MySQL in backticks. The error message made it seem like my issue was somewhere else in the query completely, but ultimately this was my fix.

`prisma.$executeRaw`INSERT INTO mytable(..., \`condition\`, ...;`;`

**Comment by cjscheller** [comment]
@fated-x I appreciate the reply; unfortunately, that did not fix the issue for me. I even took it to the extreme and wrapped all table and column names in backticks, but I am still receiving the same error message. 

<details>

<summary>Query</summary>

```typescript
  const query: Prisma.Sql = Prisma.sql`
        SELECT \`OrderItem\`.\`productId\`, \`Product\`.\`name\`, \`Product\`.\`description\`, \`Product\`.\`price\`, \`Product\`.\`imageUrl\`, SUM(\`OrderItem\`.\`quantity\`) as quantity
        FROM \`Invoice\`
        INNER JOIN \`Order\` on \`Invoice\`.\`id\` = \`Order\`.\`invoiceId\`
        INNER JOIN \`OrderItem\` on \`Order\`.\`id\` = \`OrderItem\`.\`orderId\`
        INNER JOIN \`Product\` on \`OrderItem\`.\`productId\` = \`Product\`.\`id\`
        WHERE \`Invoice\`.\`id\` = ${invoiceId}
        GROUP BY \`OrderItem\`.\`productId\`;`;
```

</details>

I remain the most confused about the fact that even if I hardcode the variable directly into the query (`WHERE Invoice.id = 5`), I still receive the error and the error indicates that the WHERE clause was rewritten as `WHERE 1 != 1`. The original query (with hardcoded variable) works when run directly against the Vitess database.

**Comment by janpio** [comment]
Did you use Prisma's query logging already to double-check the exact query that is executed against the database to confirm it should be valid?
Also: Have you asked PlanetScale about this error message yet? They might hopefully know better why Vitess is unhappy about it.

**Comment by cjscheller** [comment]
@janpio I've double-checked the query that Prisma is executing via the query logger, and confirmed that when ran directly against the Planetscale database via a MySQL client/console the query works successfully. 

<details>

<summary>Query log output</summary>

```
prisma:query 
        SELECT OrderItem.productId, Product.name, Product.description, Product.price, Product.imageUrl, SUM(OrderItem.quantity) as quantity
        FROM Invoice
        INNER JOIN `Order` on Invoice.id = `Order`.invoiceId
        INNER JOIN OrderItem on `Order`.id = OrderItem.orderId
        INNER JOIN Product on OrderItem.productId = Product.id
        WHERE Invoice.id = ?
        GROUP BY OrderItem.productId;
```
</details>

I have also opened a support ticket with Planetscale, and will provide updates here as I receive them.

**Comment by janpio** [comment]
(Weird)

**Comment by SevInf** [comment]
@cjscheller would it be possible to provide an isolated reproduction for the issue if it still happening to you?

**Comment by SevInf** [comment]
Hey @ChristianJacobsen  ,

Did you get a chance to have a look at my previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by ChristianJacobsen** [comment]
> Hey @ChristianJacobsen  ,
> 
> 
> 
> Did you get a chance to have a look at my previous comment? It'd be helpful for us to move your issue forward.
> 
> 
> 
> Without further information, we'll have to close this issue. Thank you 🙏

cc @cjscheller

**Comment by cjscheller** [comment]
Just attempted to reproduce the issue on Prisma versions v4.15 (where issue was originally occuring) v5.9.1 (latest), and was unable to recreate the error. Closing issue as completed. 

For some added context, I was originally able to workaround the issue by adding all columns to the GROUP_BY clause. I worked with Planetscale support to try and isolate where the query was being transformed to specify `WHERE 1 != 1`. After viewing their Vitess error logs, their support team confirmed that the query was arriving or being processed with that where clause modification.

**Comment by tsulatsitamim** [comment]
![Screenshot 2024-07-15 at 22 07 22](https://github.com/user-attachments/assets/0eef4c33-4718-4710-9c9e-4d823821fd40)
Also got error when use $queryRaw, the error gone if i remove order by query, or hardcode order by query parameter.
