### ISSUE TITLE
BigInt and Number - SQL Server

### ISSUE THREAD

**Issue by tiagomol1** [prisma/prisma#20005]
### Discussed in https://github.com/prisma/prisma/discussions/20004

<div type='discussions-op-text'>

<sup>Originally posted by **tiagomol1** June 29, 2023</sup>
I have a doubt. In my project I use SQL SERVER, and I generate the mapping structure of database with prisma generate command.
After that, all schemas are mapping and I really can see and use the models.
But when I have a BigInt field the Typescript don't understood like a Number and throw many errors by not found data types. How can adjust this?</div>

**Comment by Jolg42** [comment]
I'll close this as a discussion is already happening. Please continue the discussion in https://github.com/prisma/prisma/discussions/20004
