### ISSUE TITLE
Nested composite types breaks TS types

### ISSUE THREAD

**Issue by Ehesp** [prisma/prisma#20002]
### Bug description

In `4.16.0` onwards of Prisma, nested composite types generate incorrect TypeScript types, compared to `4.15.0` where they are correct. This is using MongoDB.

### How to reproduce

Create a schema like so:

```prisma
model User {
  details Details
}

type Details {
  address Address
}

type Address {
  zipCode String
}
```

When types are generated, they are as follows:

```ts
export type DetailsPayload = {
  objects: {}
  scalars: {}
  composites: {
    address: AddressSourcePayload | null
  }
}

export type AddressSourcePayload = {
  objects: {}
  scalars: {
    zipCode: string
  }
  composites: {}
}
```

When accessing data from a query, before it worked like expected:

```ts
document.details.address.zipCode;
```

Now it fails, and expects:

```ts
document.details.address.scalars.zipCode;
```

### Expected behavior

The type of `Details` is generated as:

```
export type Details = {
   address: Address; 
}

export type Address = {
  zipCode: string;
}
```

### Prisma information

See above for example schema.

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["jsonProtocol"]
}
```

### Environment & setup

- OS: MacOS
- Database: MongoDB
- Node.js version: v18.13.0

### Prisma Version

```
prisma                  : 4.16.0
@prisma/client          : 4.16.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.0-66.b20ead4d3ab9e78ac112966e242ded703f4a052c
Default Engines Hash    : b20ead4d3ab9e78ac112966e242ded703f4a052c
Studio                  : 0.484.0
Preview Features        : jsonProtocol
```

**Comment by ramiel** [comment]
I can confirm I have the same issue. I couldn't fine any breaking changes in the release notes

**Comment by Ehesp** [comment]
I think based on the single level nested working as expected, it's probably a bug rather than expected.

**Comment by ramiel** [comment]
Sorry, I probably don't understand. Are you saying this behavior is expected?

**Comment by Ehesp** [comment]
I was referring to your comment:

>  I couldn't fine any breaking changes in the release notes

I highly doubt this is an intended change, given the fact types work correctly for a single-level of composite types. So it should probably be fixed :)

**Comment by SevInf** [comment]
@Ehesp could you check if `4.16.2-dev.2` dev snapshot version fixes the issue for you? We don't recommend using dev snapshots in production, but it should be enough to verify the fix and it will evebntually be published as stable `4.16.2`

**Comment by Jolg42** [comment]
Note: most likely a duplicate of https://github.com/prisma/prisma/issues/19880 (to be checked)

**Comment by Ehesp** [comment]
Looks like 4.16.2 fixes the issue, thanks.
