### ISSUE TITLE
Migrating to release:  4.16.2 throws typescript error:  "TS1005: '?' expected".

### ISSUE THREAD

**Issue by iurylippo** [prisma/prisma#20024]
### Bug description

There is any breaking change for release 4.16.2 ? 

I tried to migrate my prisma version from 4.9.0 to 4.16.2 and now it's not building my project.

Full Console error:

```
#0 0.674 yarn run v1.22.18
#0 0.701 $ rimraf dist
#0 0.959 $ nest build
#0 39.66 node_modules/@prisma/client/runtime/index.d.ts:2992:182 - error TS1005: '?' expected.
#0 39.66
#0 39.66 2992     [K in keyof P]: P[K] extends Payload[] ? UnwrapPayload<P[K]> : P[K] extends Payload ? P[K]['scalars'] & UnwrapPayload<P[K]['composites']> : P[K] extends (infer O extends Payload) | null ? (O['scalars'] & UnwrapPayload<O['composites']>) | null : P[K];
#0 39.66
                                                                                       ~
#0 39.66
#0 39.66 Found 1 error(s).
#0 39.66
#0 39.80 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 39.80 error Command failed with exit code 1.
```

### Expected behavior

Build project without prisma typescrit error.

### Prisma information

```
generator client {
    provider        = "prisma-client-js"
    previewFeatures = []
    binaryTargets   = ["native", "linux-musl"]
}

datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: linux alpine (DOCKER) image => node:16.14.2-alpine3.15
- Database: PostgreSQL
- Node.js version: 16.14.2

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
Done in 1.48s.
```

**Comment by Jolg42** [comment]
@iurylippo This is unexpected 🤔 

Could you maybe try your reproduction steps on `4.16.1`, then if that still errors on `4.16.0` and then `4.15.0`? I'm curious to know which version(s) works, this looks like a recent change to me.

I'm also interested to know which version of TypeScript you are running here?

Also, if you could help us by providing a git repository as a minimal reproduction, it would help a lot to get to a reproduction on our side and fix it.

**Comment by iurylippo** [comment]
> @iurylippo This is unexpected 🤔
> 
> Could you maybe try your reproduction steps on `4.16.1`, then if that still errors on `4.16.0` and then `4.15.0`? I'm curious to know which version(s) works, this looks like a recent change to me.
> 
> I'm also interested to know which version of TypeScript you are running here?
> 
> Also, if you could help us by providing a git repository as a minimal reproduction, it would help a lot to get to a reproduction on our side and fix it.

I confirm that the problem is just with 4.16.2, version 4.16.1 and bellow is not showing this error.

typescript version: ^4.3.5

 I am in working hour, unfortunately I can't provide a reproduction environment at this moment.

**Comment by Jolg42** [comment]
@luanvdw So you said you are using TypeScript `^4.3.5`, which looks like a version taken from a package.json to me.
Could you give me the actual installed version? (Because here it could be anything between that version and v5).
-> You can find the exact version by executing `npx tsc -v` if you have `typescript` as a dependency in your `package.json` (or by looking into your lock file or executing `npm list typescript --depth=0`)

Also, could you try upgrading your TypeScript version and see if that changes anything here?

**Comment by iurylippo** [comment]
> @luanvdw So you said you are using TypeScript `^4.3.5`, which looks like a version taken from a package.json to me.
> Could you give me the actual installed version? (Because here it could be anything between that version and v5).
> -> You can find the exact version by executing `npx tsc -v` if you have `typescript` as a dependency in your `package.json` (or by looking into your lock file or executing `npm list typescript --depth=0`)
> 
> Also, could you try upgrading your TypeScript version and see if that changes anything here?

It's exactly 4.6.2

**Comment by iurylippo** [comment]
Yeah, it's definitively typescript, version 5.1.6 of recent release fix it.

**Comment by Jolg42** [comment]
Note: We are investigating this, so far @SevInf found out that `4.16.2` requires TypeScript version `4.7.0` or up at the moment.
