### ISSUE TITLE
Prisma generate command crashes with `RustPanic: RuntimeError: panicked at 'internal error: entered unreachable code', query-engine/prisma-models/src/field/scalar.rs:93:50`

### ISSUE THREAD

**Issue by shalomsam** [prisma/prisma#20037]
Hi Prisma Team! The following command just crashed.

## Command

`generate`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-3.0.x| 
| Node        | v18.16.0           | 
| Prisma CLI  | 4.16.2             | 
| Engine      | 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81| 

## Error
```
RustPanic: RuntimeError: panicked at 'internal error: entered unreachable code', query-engine/prisma-models/src/field/scalar.rs:93:50
```

**Comment by Jolg42** [comment]
@shalomsam Could you share your Prisma schema with us so we could reproduce this?

**Comment by shalomsam** [comment]
@Jolg42 - This was the version of the [file](https://github.com/shalomsam/storebuilder/blob/7bde2f738c1ef18efa596885141763a6a3b9462a/prisma/schema.prisma) with the issue. I managed to fix, the issue seems to have been an incorrect reference in the `@unique(...)` helper method (Unless I am mistaken). But the prisma vscode plugin didn't highlight it as an error.

**Comment by Jolg42** [comment]
Thanks!

This is the minimal schema that I could come up that shows the same issue
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = "mongodb://localhost:27017/ecommerce"
}

model Post {
  id         String      @id @default(auto()) @map("_id") @db.ObjectId
  author     User        @relation(fields: [authorId], references: [id])
  authorId   String      @db.ObjectId
  attributes Attribute[]

  @@unique([authorId, attributes])
}

model User {
  id   String @id @default(auto()) @map("_id") @db.ObjectId
  Post Post[]
}

type Attribute {
  name  String
  value String
  group String
}
```

**Comment by Tristan31415926535897932384626433832795** [comment]
> @Jolg42 - This was the version of the [file](https://github.com/shalomsam/storebuilder/blob/7bde2f738c1ef18efa596885141763a6a3b9462a/prisma/schema.prisma) with the issue. I managed to fix it, the issue seems to have been an incorrect reference in the `@unique(...)` helper method (Unless I am mistaken). But the prisma vscode plugin didn't highlight it as an error.

I had the same issue and was able to find the cause. You get this error when you try to reference the whole composite type instead of a composite type field in the attributes `@unique` or `@@unique`
in the example above, the following line causes the error:
> @@unique([authorId, attributes])

@shalomsam I read most of your schema and you have multiple models with this problem
@Jolg42 it would be helpful if the error message could actually reflect that

**Comment by petradonka** [comment]
@quest-bot stash 150

**Comment by onichandame** [comment]
@quest-bot embark

**Comment by jaysaadana19** [comment]
@quest-bot embark

**Comment by jaysaadana19** [comment]
@quest-bot loot #20037
