### ISSUE TITLE
Using `Prisma.XyzFindManyArgs` breaks `findMany` typing in v4.16.0+

### ISSUE THREAD

**Issue by Valerionn** [prisma/prisma#20093]
### Bug description

We sometimes generate find options dynamically and use the `Prisma.UserFindManyArgs` type for this, e.g. in a case like this:

```ts
    const userFindMany: Prisma.UserFindManyArgs = {};

    if(true) { // Some condition is met
      userFindMany.where = { email: 'mail@example.com' };
      userFindMany.take = 1;
    }

    const users = await prismaClient.user.findMany({
      ...userFindMany,
      include: {
        userRoles: true,
      },
    });

    console.log(users[0].email); // This works
    console.log(users[0].userRoles); // But this doesn't
```

Starting with Prisma v4.16.0, the code above throws a typing error: `TS2339: Property 'userRoles' does not exist on type [...]`. I think this is probably caused by the new typing because of client extensions - but in my opinion, the code above should still work.

As a workaround, it's possible to write a custom type for `userFindManyArgs`, e.g. `const userFindMany: { where?: Prisma.UserWhereInput; take?: number } = {};`, but that's only a workaround for a breaking change.

### How to reproduce

Use the code above, check if `users[0].userRoles` throws a typescript error.

### Expected behavior

Same behavior as before - adding an include should always include the relations in the result typing.

### Prisma information

```prisma
// Add your schema.prisma
model User {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  userRoles               UserRole[]
}

model UserRole {
  id        Int      @id @default(autoincrement())
}
```

```ts
// Add your code using Prisma Client
const prismaClient = new PrismaClient();
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v16.17.1
- Typescript version: v5.1.6

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
```

**Comment by Valerionn** [comment]
Probably related/duplicated to #19962 (seems like I didn't go back far enough when checking if this issue already exists, sorry)

**Comment by Jolg42** [comment]
@Valerionn Are you using a client extension? If so, could you share it with us?

**Comment by millsp** [comment]
Hey, thanks for the report. We have worked on a fix and would appreciate if you could give it a try. If you have some time, install `@prisma/client@5.1.0-integration-fix-client-types-mixed-input-types.1` and `prisma@5.1.0-integration-fix-client-types-mixed-input-types.1` and let me know how it went. Thanks.

**Comment by Valerionn** [comment]
Looks good to me, there are now no more typing errors with this version, thanks for the quick fix!
