### ISSUE TITLE
🐛 `Timed out fetching a new connection from the connection pool` (pgbouncer, cloud run)

### ISSUE THREAD

**Issue by Durisvk** [prisma/prisma#20111]
### Bug description

The connection limit is exceeded and every once in a while we receive the following error in our Sentry:

```
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 3)
```

We've updated our setup and introduced a PgBouncer in front of the database to make the error less frequent (however it still occurs). We've also enabled `pgbouncer=true` in our `DATABASE_URL`

We've introduced monitoring to our split API services that runs every 5 minutes and executes the new `prisma.$metrics.json()` feature. We're obtaining gauges (not counters) that should not increase indefinitely over time. We're logging those gauges into Google Cloud Monitoring. Here's an example graph of 2 days (not cumulative) logging `prisma_pool_connections_opened_total`, `prisma_pool_connections_busy`, `prisma_pool_connections_idle` for each of the services.

<img width="1592" alt="image" src="https://github.com/prisma/prisma/assets/8467003/2604765a-5670-415d-9eac-13da4f0c7a76">

Here is the histogram of the Prisma connection pool error occurring over past two days:

<img width="1534" alt="image" src="https://github.com/prisma/prisma/assets/8467003/3e828529-7a0d-43f3-bd86-b5b074e85ac2">

I also opened [an issue a while ago about a memory leak in our production](https://github.com/prisma/prisma/issues/18934) Cloud Run service and I suspected Prisma. Back then it looked like I was wrong but if the connections are mismanaged in the pool just like they are shown in the graph above (more than 350 connections open by one of the services) then I believe it might also explain the following graph:

7 days memory utilization of one of our services:
<img width="584" alt="image" src="https://github.com/prisma/prisma/assets/8467003/b0c7356c-bd39-42d9-aea2-4a3aebfd1993">

Extra Info: We're making sure to not create new PrismaClient instances using a globally cached single instance. Though the Prisma instances can be created because of the Cloud Run nature of autoscaling however the monitoring is always reaching out to only one of those instances which subsequently runs `prisma.$metrics.json()`. Meaning the autoscaling should not affect the monitoring graph growing to 350+ connections. In our DATABASE_URL we do not specify any connection pool limits meaning the default should be applied. The docker image we're using on the Cloud Run service is based on `node:18-alpine`

I've also left some code snippets in the [issue here](https://github.com/prisma/prisma/issues/20019#issuecomment-1619819121) and @imwexpex mentions he experiences [similar problem here](https://github.com/prisma/prisma/issues/20019#issuecomment-1620440323)

### How to reproduce

I am going to try to provide a repo for reproduction but as you can imagine at this moment I only experience the issue from error logs and the Prisma metrics monitoring.

### Prisma information

Irrelevant

### Environment & setup

- OS: Docker `node:18-alpine`
- Database: PostgreSQL on Cloud SQL using PgBouncer (but even before PgBouncer)
- Node.js version: 18

### Prisma Version

```
prisma                  : 4.16.0
@prisma/client          : 4.16.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/migration-engine-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.0-66.b20ead4d3ab9e78ac112966e242ded703f4a052c
Default Engines Hash    : b20ead4d3ab9e78ac112966e242ded703f4a052c
Studio                  : 0.484.0
Preview Features        : fullTextSearch, metrics, views
```

Ignore darwin part - the code is actually running in Docker on Cloud Run so I'm unable to execute prisma -v there.

**Comment by janpio** [comment]
> The connection limit is exceeded

What do you mean by that exactly? Do you get an error message saying so from Prisma, or is that happening on your database?

**Comment by Durisvk** [comment]
Hey @janpio thanks for the prompt reply,

> What do you mean by that exactly? Do you get an error message saying so from Prisma, or is that happening on your database?

Yes, we're getting errors on Prisma's end multiple times per day mainly during rush hours:
<img width="1732" alt="image" src="https://github.com/prisma/prisma/assets/8467003/026633e5-6dbd-47f2-89d9-b6235d0b45fd">


> [Prisma Metrics are a preview feature](https://www.prisma.io/docs/concepts/components/prisma-client/metrics) that is not production ready yet. It might have bugs, and looking at https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+metrics%22+sort%3Aupdated-desc I can for example see https://github.com/prisma/prisma/issues/18760 which could match you case maybe? There might also additional unreported bugs.
>
> Can you actually confirm the Prisma metrics on the database side?

Okay, I see, if the #18760 is right then the graph makes sense. we're gonna change the metric and observe it for a little bit to see if the graph gets corrected.

> So your application is configured with a connection pool size / limit of 3.

I cannot confirm that - some of the logs claim the limit is set to 5, some claim that it's 3. We didn't set up any configuration regarding limit so I guess the default one is being applied (`num_of_physical_cpus * 2 + 1`). Our services are all running on single CPU but the database is set up with 2 CPUs.

> How many queries does your application usually run in parallel?

We avoid running `await Promise.all([query1, query2, ...])` however there's a possibility that the nature of [expressjs server](https://expressjs.com/) might handle two or more requests sort of "concurrently" when one of the requests is awaiting a response from database and the other executes a query at the same time.

> How long do queries roughly take?

On average even our "worst performing" queries do not exceed 1 second:

<img width="716" alt="image" src="https://github.com/prisma/prisma/assets/8467003/7b566a47-9179-4f40-8e45-07ce9000f494">


> How many containers are you running in parallel?

At any single point in time even during rush hours our number of instances do not exceed 14:

<img width="1189" alt="image" src="https://github.com/prisma/prisma/assets/8467003/2c1e3845-94c9-4ffa-997e-2fb4a1affe6a">


> How often do you replace the containers with new ones (that need to open new connections)?

This is really difficult to estimate. Cloud run is an abstraction over kubernetes that makes it easier to configure and the only settings we affect are: minimum instances, maximum instances and [maximum concurrency](https://cloud.google.com/run/docs/about-concurrency)

in our case we have various settings of minimum and maximum instances but we keep the maximum concurrency at default value: 80.

> How is your database configured to close open connections after they are not used?

As mentioned this should be handled by PgBouncer. We have a `pool_mode = transaction` setup as [recommended here](https://www.prisma.io/docs/guides/performance-and-optimization/connection-management/configure-pg-bouncer#set-pgbouncer-to-transaction-mode).

Let me know if there is any more info needed apart from changing the metric based [on this issue](https://github.com/prisma/prisma/issues/18760) and tracking how the connections are changing over time.

**Comment by janpio** [comment]
> some of the logs claim the limit is set to 5, some claim that it's 3.

This is indeed weird. The application server CPUs should define that number if not customized. Are you running different configurations at the same time?

> Yes, we're getting errors on Prisma's end multiple times per day mainly during rush hours:
> <img alt="image" width="1732" src="https://user-images.githubusercontent.com/8467003/252358027-026633e5-6dbd-47f2-89d9-b6235d0b45fd.png">

Knowing the connection limit on one of these servers is 5, and knowing the length of the queries that are run and then how many queries it tries to execute you should be able to understand if Prisma running into this problem is actually reasonable. A query will return this error, if it had to wait longer than 10s for getting a free connection that could have handled it. A query will need to wait if there are already more than 5 queries being actively run.

A super simplified example: If all queries _would_ take 1s, then you can only start a total of 50 (5 connection * 10 seconds) queries successfully at the same time. If you try to start more, one of them will run into the timeout. If they take longer, you run into the timeout.

---

With PgBouncer in front of your database, I think you can actually try 2 different things:

1. Increase that pool timeout value beyond 10s. Does this get rid of the errors at the cost of longer response times? Then:
2. Increase the number of connections you give your applications, and increase the pool size by increaseing the `connection_limit` value. PgBouncer should be able to handle the incoming questions just fine, and usually properly manage the connections of the actual database.

**Comment by janpio** [comment]
Any update, did you have success @Durisvk?

**Comment by jkomyno** [comment]
Hey @Durisvk, could you please report back here any results on your latest experiment regarding this issue? Thanks.

**Comment by Durisvk** [comment]
Hey guys, sorry for the late reply - the recommendations you gave me fixed the issue
