### ISSUE TITLE
"prisma local start" takes up to ~30 minutes to run

### ISSUE THREAD

**Issue by ashtonsix** [prisma/prisma#2013]
# Feature Request

`prisma local start` takes **forever**, maybe because of my internet speed?

I spent about 6 hours cancelling & restarting the installation before figuring out it just needed to be left alone. Using `DEBUG="*"` didn't help either, looks like a hung process unless you watch for ages.

Think https://github.com/graphcool/prisma/issues/1946 might be the same issue.

**What feature are you missing?**

Progress indicator

**How could this feature look like in detail? Tradeoffs?**

_quick solution_

print `This can take up to ~30 minutes. Maybe grab coffee while it downloads MySQL?`

_ideal solution_

copy UX from `create-react-app`, but print current progress for any downloads precisely eg, `13.56 MB / 64 MB`

**Comment by marktani** [comment]
`prisma local start` does not exist anymore, hence this feature is not applicable anymore.
