### ISSUE TITLE
password altered the database_url functionality

### ISSUE THREAD

**Issue by Firgrep** [prisma/prisma#20156]
### Bug description

I was having issues trying to locally connect to a Google Cloud MySQL db with Prisma. I was using the Cloud SQL Proxy to create a connection between my local machine and the cloud for Prisma to use but I kept getting the error  

> P1001: Can't reach database server at `userdb`:`3306``

I installed mysql workbench and gave that a try and it successfully connected to the db instance, so I thought the problem had to be with the URL. I also saw that the proxy would log to the terminal if there were any requests being made, and as I was trying prisma, it was silent so no requests were being made. After spending a day looking through various stackoverflow posts and interrogating chatgpt, I noticed that it was peculiar that the error gave me the message that it couldn't connect to "userdb" since that's not the database, but the user. I then tried to put in a faulty <user> and <pass> and ran the connection. The proxy reacted! And prisma returned an authentication error. So now at least the connection was happening correctly but with the wrong user and pass. I put the correct user and pass back in and the old problem resurfaced. I noticed the pass included lots of funny symbols so I decided to change it and I put in the new pass - lo and behold, prisma connected immediately successfully and the proxy had lots of reaction. Something in the previous passworld altered the functionality of the url or how it was being parsed.

This was really hard to pick up on, but I guess I should've noticed that something must've been fishy given the error pointed to the username rather than the actual db name. I'm adding it here in case anyone else is struggling with it or if something could be done to improve the error message. 

### How to reproduce

Prior password included `#` , `)` , `&` , `(` `|` 

It started with `#)`

### Expected behavior

Attempting to run `npx prisma migrate dev --name init` 
Expected database connection but received misleading error message. 

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: Windows.
- Database: MySQL
- Node.js version: v18.13.0

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
```

**Comment by millsp** [comment]
Hey @Firgrep, have you tried to escape the special characters in your password?
https://www.prisma.io/docs/reference/database-reference/connection-urls#special-characters

**Comment by Firgrep** [comment]
Ah! I just tried that now and it worked! I learned something new today. Thank you so much, @millsp ! I'll remember this in future development. Cheers
