### ISSUE TITLE
Intermitent error on OSX 

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#2015]
## Bug description
I get this error sometimes since switching to the latest alpha:
```
(node:2510) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.user.findOne()` invocation:

Query engine binary for current platform "darwin" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/Users/Sytten/Projects/******/packages/graphql/node_modules/@prisma/client/runtime/query-engine-darwin")

To solve this problem, add the platform "darwin" to the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
    at PrismaClientFetcher.request (/Users/Sytten/Projects/******/packages/graphql/node_modules/@prisma/client/runtime/index.js:1:51672)
(node:2510) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2510) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I have to delete the database and start over.

## How to reproduce
Hard to tell, I don't see a particular pattern.

## Environment & setup
```
@prisma/cli          : 2.0.0-alpha.989
Current platform     : darwin
Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/Sytten/Projects/******/packages/graphql/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/Sytten/Projects/******/packages/graphql/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/Sytten/Projects/******/packages/graphql/node_modules/@prisma/cli/introspection-engine-darwin)
```

**Comment by Sytten** [comment]
Looking at it, it does seems like the query engine is not there. Some code deleted it?

**Comment by janpio** [comment]
> I get this error sometimes since switching to the latest alpha:

Any idea what "sometimes" is connected to? Do you do something specific?
File file `/Users/Sytten/Projects/******/packages/graphql/node_modules/@prisma/client/runtime/query-engine-darwin` it is looking for is indeed not there?

**Comment by Sytten** [comment]
No yet, I will investigate more in the next few days to try to find a pattern. My first hypothesis is that it might be linked to a new alpha is being released, is there an auto updater in place? The file seems to be deleted at some point.

**Comment by Sytten** [comment]
I seems to happen sometimes when I generate the database, it doesnt seem to a be runtime issue.

**Comment by divyenduz** [comment]
@Sytten Some questions:
- Are you installing other packages in the meantime, when this happens?
- Are you using `npm` or `yarn`

**Comment by Sytten** [comment]
- Yarn
- No, but I have this script
```
#!/bin/bash
docker rm -f my_db
docker run --name my_db -p 5432:5432 -e POSTGRES_USER=dev  -d postgres:alpine
sleep 5

npx prisma2 migrate save --name 'init' --experimental
npx prisma2 migrate up --experimental
rm -rf prisma/migrations

npx prisma2 generate

yarn seed
```

**Comment by Sytten** [comment]
Ha I found the issue, this is dumb of me not thinking about that.
Its when I do a `yarn install`, it deletes the engine. I guess its a no fix.

**Comment by pantharshit00** [comment]
@Sytten Yarn has some postinstall caching issues which we have reported: https://github.com/yarnpkg/yarn/issues/7762

That results sometimes binary not being downloaded. They pointed us to yarn 2 release but that hasn't seen much adoption.

**Comment by timsuchanek** [comment]
@pantharshit00 I think this is even unrelated to yarnpkg/yarn#7762, because the caching only doesn't generate a new Client, but it shouldn't delete a binary.

The problem here is really, that yarn sometimes deletes the artifacts we create. We have seen this before, also with the `yarn install` that you reported, but couldn't reliably reproduce.
I'm looking forward to the day when we get a reliable reproduction 🙂

**Comment by Overdozed** [comment]
i fixed it by removing prismas output path form schema file and importing client from @prisma/client directly. In my case prisma created platform code inside prisma output path and this caused simmilar problems. Inside node_modules it works like a charm.

**Comment by pantharshit00** [comment]
@Sytten Can you still reproduce this in the latest version? If not, please close this issue 🙏

**Comment by Sytten** [comment]
I think its fine now, didnt get any error lately.
