### ISSUE TITLE
Internal error: Attempted to serialize empty result.

### ISSUE THREAD

**Issue by trandat-09** [prisma/prisma#20160]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.20.0           | 
| OS              | windows            |
| Prisma Client   | 4.16.2             |
| Query Engine    | 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81|
| Database        | mongodb            |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from D:\TD\RISENS\risens_data_sync\.env
prisma:client checkPlatformCaching:postinstall true
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from D:\TD\RISENS\risens_data_sync\.env
prisma:client dirname D:\TD\RISENS\risens_data_sync\node_modules\.prisma\client
prisma:client relativePath ../../../prisma
prisma:client cwd D:\TD\RISENS\risens_data_sync\prisma
prisma:client protocol graphql
prisma:client clientVersion 4.16.2
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath D:\TD\RISENS\risens_data_sync\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by millsp** [comment]
Hey @trandat-09, could you please provide us with extra information like a copy of your schema, the error you are facing, and possibly a minimal reproduction of your problem? Thanks.

**Comment by petradonka** [comment]
Hello, @trandat-09. could you help us with the details outlined above? This will help us in in reproducing and addressing the issue. Thank you!

**Comment by SevInf** [comment]
Hey @trandat-09 ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
