### ISSUE TITLE
Prsima Client Rust

### ISSUE THREAD

**Issue by pasha-vuiko** [prisma/prisma#20170]
## Problem

Hi! Didn't you think about creating of an official Prisma Client for Rust? I know, that you already had the failure with Prisma Client Go, that the Go community did not give warm welcome for this approach, but I think with the Rust Prisma Client everything may go much better! The existing ORMs in Rust are awful, and I think in such circumstances the official Prisma Client Rust can shine like a diamond and achieve a lot of support form the Rust community!

## Suggested solution

Create an official Prisma Client for Rust with up to date Prisma features

## Alternatives

I know, that https://github.com/Brendonovich/prisma-client-rust exists, but unfortunately, as I guess, the author does not have enough time to keep it up to date with all important Prisma features such as native type support and choosing transaction level.

**Comment by janpio** [comment]
We did in the context of https://github.com/prisma/prisma/issues/5790, but we don't have the capacity to do so. We have more than enough work (look at the issues) for the Node.js client and will not be able to change that considerably in the near future. 

Brendon's Client is usually also pretty well received. If you are missing something, I am sure he will be willing to accept contributions to help him out.
