### ISSUE TITLE
prisma group by support group_concat  

### ISSUE THREAD

**Issue by hanlong1230** [prisma/prisma#20204]
prisma group by support group_concat

**Comment by millsp** [comment]
Hey @hanlong1230, it seems like you are missing functionality from us. Would you mind filling the template of the issue please so we can maybe track this as an improvement or a feature request. Thanks.

**Comment by hanlong1230** [comment]
when i use group by function, i need to trace back source data by id , so i hope to support group_concat

**Comment by millsp** [comment]
Could you please take the time to fill this template?

```
## Problem

<!-- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] -->

## Suggested solution

<!-- A clear and concise description of what you want to happen. -->

## Alternatives

<!-- A clear and concise description of any alternative solutions or features you've considered. -->

## Additional context

<!-- Add any other context or screenshots about the feature request here. -->
```

**Comment by janpio** [comment]
Closing because unclear what functionality is actually needed. Please open a new issue if we do not have an issue for that this referred to. Thank you.
