### ISSUE TITLE
Prisma does not serialize BigInt on create/update

### ISSUE THREAD

**Issue by adrianwix** [prisma/prisma#20205]
### Bug description

Prisma does not know how to serialize it's own BigInt

### How to reproduce

1. Create a table that have a JSON column
2. Try to store a json there that have a property of BigInt type
3. Prisma crashes

### Expected behavior

Prisma client should follow its own advice and use this https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields#serializing-bigint

### Prisma information

```prisma
CAN'T SHARE
```

```ts
// Add your code using Prisma Client
await prisma.suppliers.upsert({
        where: { domain },
        create: {
          name: name,
          domain: domain,
          cache: rawData, // This breaks
        },
        update: {
          cache: stringifyJSON(rawData), // This works because I use the JSON.stringify function recommended by Prisma docs
        },
```

### Environment & setup

- OS: macOS
- Database:PostgreSQL
- Node.js version: 16.20

### Prisma Version

```
4.17
```

**Comment by millsp** [comment]
Thanks for the report @adrianwix. Could you please share the error that you are seeing with us? Also if you have the time, could you please try our latest version? I'd also appreciate if you could share a minimal schema and query showing the undesired behavior. Thanks.

**Comment by Jolg42** [comment]
@adrianwix Did you see our last 2 messages? We're waiting for you and in "a few days" we'll close this issue if we don't hear back.

**Comment by janpio** [comment]
Hey @adrianwix, I am closing this issue now as we unfortunately didn't have enough information to reproduce it. If you can add this information, we are happy to take a shot at reproducing, understanding and potentially fixing this problem. Please just comment here again. Thanks.

**Comment by abdo20010dx** [comment]
error in prisma and prisma don't want handle it sooo, it gives a message with 
oh dear programmer you can't serialize a bigint.

**Comment by millsp** [comment]
@abdo20010dx could you please create a new issue with some reproduction steps?
