### ISSUE TITLE
Update Composite Type

### ISSUE THREAD

**Issue by Dsantosjaime** [prisma/prisma#20210]
### Bug description

I want to update part of one composite type without erasing the data already there.

I tried this [(as the documentation recommend)  ](https://www.prisma.io/docs/concepts/components/prisma-client/composite-types#changing-a-single-composite-type)

But:

```
return this.prisma.user.update({
                where: { id },
                data: { specialist: { update: { firebaseMessagingToken: "test" } } }
            });
```

Raise an error because the keyword "update" isn't part of my schema and If I update without the keyword, it erase the "skills" already in my object.

### How to reproduce

Try to update part of a composite type

### Expected behavior

Update part of my composite type "specialist" without erasing all the other data of the composite already in the db.

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  id         String      @id @default(auto()) @map("_id") @db.ObjectId
  readableId Int         @unique
  email      String      @unique
  firstname  String
  lastname   String
  phone      String?
  specialist Specialist?
  createdAt  DateTime    @default(now()) @map("created_at")
  updatedAt  DateTime    @updatedAt @map("updated_at")

  @@map("staffUser")
}

type SkillInfos {
  id    String
  label String
}

type Specialist {
  firebaseMessagingToken String?
  skills                 SkillInfos[]
}
```

### Environment & setup

NodeJs: `v16.20.0`
NestJs:
```
"@nestjs/cli": "^9.0.0",
"@nestjs/common": "^9.0.0",
"@nestjs/core": "^9.0.0",
"@nestjs/platform-express": "^9.0.0",
"@nestjs/swagger": "^6.3.0",
```

### Prisma Version
```
Prisma:4.16.0
Prisma/Client:4.16.1-dev.7
```

**Comment by millsp** [comment]
Thanks for the report @Dsantosjaime. Could you please share the error that you are seeing with us? Also if you have the time, could you please try our latest version?

**Comment by Dsantosjaime** [comment]
My IDE print error in French ...

If I try to translate:

Impossible to assign type '{ update: { firebaseMessagingToken: string; }; }' to ''(Without<SpecialistNullableUpdateEnvelopeInput, SpecialistCreateInput> & SpecialistCreateInput) | (Without<...> & SpecialistNullableUpdateEnvelopeInput)'.'

**Comment by Dsantosjaime** [comment]
I also have the problem with this line of code:

`await this.prisma.user.updateMany({ where: { client: { is: { group: { is: { readableId } } } } }, data: { client: { group: { update: { name: updateGroupDto.name, readableId: 0, id: "0" } } } } })`

('Is' working well)

Currently I can't continue to use Prisma with mongoDb and composite types.

**Comment by millsp** [comment]
Since your composite type is optional, I think you should be using an `upsert` instead. (Also, I speak French if that can help :smile:). Could you give that a try?

**Comment by Dsantosjaime** [comment]
I tried it:

But I can't use the "where" option as I wanted to, "is" isn't working in "upsert".
Even If I write a "where" condition working, "update" isn"t working either.
Thanks, here is the errors in french:

```
Les types de la propriété 'group' sont incompatibles.
        Impossible d'assigner le type '{ name: string; readableId: number; id: string; }' au type 'never'.ts(2322)
```

for :

`this.prisma.user.updateMany({ where: { client: { is: { group: { is: { readableId } } } } }, data: { client: { group: { name: updateGroupDto.name, readableId: 0, id: "0" } } } })`

**Comment by millsp** [comment]
Oh you want to discriminate the result based on a property in the result, eg. the model name or something similar?

**Comment by millsp** [comment]
I am not sure I got you fully, but I think a simple code example with a schema and some code would help me. Also, is [this](https://github.com/prisma/prisma/issues/5315#issuecomment-1447116621) something that would solve your use-case?

**Comment by Dsantosjaime** [comment]
Here is my schema:

```
model User {
  id         String      @id @default(auto()) @map("_id") @db.ObjectId
    ...
  userType   UserType
  specialist Specialist?
  client     Client?
    ...
  @@map("staffUser")
}
```

If "userType" === "CLIENT" , I know I got some data in "Client", if it's equal to "SPECIALIST" I know I got data in "specialist".
If I want to do:

```
this.prisma.user.updateMany({
        where: { client: { is: { group: { is: { id } } } } },
        data: {
          client: {
            update: { group: { update: { name: "SomeName } } }

          }
        }
      })
```

I can't cause client is optional.

**Comment by millsp** [comment]
Right now, if you want to make this optional you have to use a nested `upsert` because it is optional. You could first retrieve the `userType`, then conditionally run the right upsert as a second query. It's not efficient but that should work.

Maybe this is what you need? https://github.com/prisma/prisma/issues/2505

**Comment by Jolg42** [comment]
@Dsantosjaime Did you see the message from @millsp, without any activity on this issue we would later close it as part of our issue process.

**Comment by millsp** [comment]
Hey @Dsantosjaime, without your input we cannot move this issue forward, so I am closing this issue. Please provide us with the missing information so we understand how to treat this, and we will happily re-open this.
