### ISSUE TITLE
Allow Relations in Model Extension `needs` Dependencies

### ISSUE THREAD

**Issue by defrex** [prisma/prisma#20211]
## Problem

The new extensions feature is great! My team is already using it for a few things.

However, we'd love to add computed props based on relationships.

Here is a simple example. Given these models

```prisma
model Account {
  id           Int           @id @default(autoincrement())
  transactions Transaction[]
}

model Transaction {
  id        Int      @id @default(autoincrement())
  amount    Int
  account   Account? @relation(fields: [accountId], references: [id])
  accountId Int?
}
```

I'd like to add `balance` as a computed property of `Account`

```ts
prisma.$extends({
  result: {
    account: {
      balance: {
        needs: {
          transactions: true, // <- Type 'boolean' is not assignable to type 'never'.
        },
        compute(account) {
          return sumBy(account.transactions, "amount");
        },
      },
    },
  },
});
```

## Suggested solution

Allow requiring certain relations to be `include`'d in order to compute a prop.

## Alternatives

The alternative I'm currently considering is overwriting `query` to dynamically add the fields (or maybe a wrapper-class) if the relations are present. 

The problem with that approach is that the types won't be correct.

**Comment by SevInf** [comment]
Hi @defrex!
Thank you for kind words and for opening this request. We plan to eventually implement it (sorry, no ETA yet) and we already have [a separate issue for tracking that](https://github.com/prisma/prisma/issues/20091). I am going to close this as a duplicate. You can follow the progress in #20091
