### ISSUE TITLE
@@unique is no longer allowed for relations in vscode plugin

### ISSUE THREAD

**Issue by macrozone** [prisma/prisma#2021]
## Problem

i had a model like this:

```
model TeamChallengeVote {
  id           String              @default(uuid()) @id
  user      User      @relation(references: [id])
  challenge Challenge @relation(references: [id])
  team      Team?     @relation(references: [id])
  score     Int

  @@unique([user, challenge, team])
}
```

until yesterday, this was valid. But since today, vscode complains about the @@unique annotation:

```
Error validating model "TeamChallengeVote": The unique index definition refers to the relation fields user, challenge, team. Index definitions must reference only scalar fields.
```

i guess this is of the new beta which unfortunatly requires additional scalar fields. So the formatter already threats the schema as beta, altough we still use preview

## Solution

maybe the formatter just needs to know the prisma version for the time being and treat at as preview schema. Its very very hard for the moment to know how to migrate properly, everything seems to fall apart.

## Alternatives

Have the formatter automatically update every schema in a way that it works both for preview version and beta. Maybe release another preview that supports the new scalar fields and have the migration handle this gracefully. Or get rid of the scalar-fields again on beta.

**Comment by Sytten** [comment]
You need to switch to the new relation (with the scalar relation field) and use those scalars instead.

**Comment by pantharshit00** [comment]
Yes, please refer to https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations and apply foreign key fields according to your datamodel.

**Comment by macrozone** [comment]
> You need to switch to the new relation (with the scalar relation field) and use those scalars instead.

i want to avoid that until prisma figured out to do it without the scalar field. So my hope was that prisma would keep the formatter compatible for the preview version.

Also, it seemed that there is no migration to the new scalar fields yet, so until this is available, preview users are stuck with preview version.

**Comment by pantharshit00** [comment]
In that case I think you should wait as we plan to revisit the syntax

**Comment by macrozone** [comment]
@pantharshit00 i noticed that the prisma vscode plugin was not updated, but the error still came from one day to the other. It seems that the plugin takes the grammar form somewhere else?

is it possible that it would respect the local installed prisma version in the project?

**Comment by janpio** [comment]
> In that case I think you should wait as we plan to revisit the syntax

There is no time frame for that at all - staying on preview is not advisable here.

> i noticed that the prisma vscode plugin was not updated, but the error still came from one day to the other. It seems that the plugin takes the grammar form somewhere else?

The VSCode extension downloads a binary on installation and then uses that until another version of the extension is installed, that again downloads a new binary. Unless you modified the files, there is no change in what the binary and thus the extension do. (VSCode auto updates extensions though).

> is it possible that it would respect the local installed prisma version in the project?

Not yet, but it was requested as a feature that we might develop one day: https://github.com/prisma/vscode/issues/66

**Comment by do4gr** [comment]
Closing this now since the syntax change was completed more than 6 months ago.

**Comment by macrozone** [comment]
👍 

the good formatter in vscode really helped to adopt anyway as it adds missing pieces
