### ISSUE TITLE
Error: [schema-engine/connectors/sql-schema-connector/src/sql_schema_calculator.rs:196:32] no entry found for key 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#20222]
Command: `prisma db push`
Version: `5.0.0`
Binary Version: `6b0aef69b7cdfc787f822ecd7cdc76d5f1991584`
Report: https://prisma-errors.netlify.app/report/14827 
OS: `arm64 darwin 22.5.0`

JS Stacktrace:
```
RustPanic: Error in Schema engine.
Reason: [schema-engine/connectors/sql-schema-connector/src/sql_schema_calculator.rs:196:32] no entry found for key
```

Rust Stacktrace:
```
[EXIT_PANIC]
Starting schema engine RPC server
[schema-engine/connectors/sql-schema-connector/src/sql_schema_calculator.rs:196:32] no entry found for key
   0: backtrace::capture::Backtrace::new
   1: schema_engine::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_failed
   8: sql_schema_connector::sql_schema_calculator::calculate_sql_schema
   9: <sql_schema_connector::SqlSchemaConnector as schema_connector::schema_connector::SchemaConnector>::database_schema_from_diff_target::{{closure}}
  10: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  11: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  12: schema_core::state::EngineState::with_connector_for_schema::{{closure}}::{{closure}}::{{closure}}
  13: schema_core::state::EngineState::with_connector_for_schema::{{closure}}::{{closure}}
  14: tokio::runtime::task::raw::poll
  15: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  16: tokio::runtime::task::raw::poll
  17: tokio::runtime::task::UnownedTask<S>::run
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: std::sys::unix::thread::Thread::new::thread_start
  21: __pthread_joiner_wake

```

**Comment by jkomyno** [comment]
Internal note: this is likely on PlanetScale, as the user had  `relationMode = "prisma"` in their schema.

**Comment by Jolg42** [comment]
Potentialy related (similar error message)
https://github.com/prisma/prisma/issues/19115
https://github.com/prisma/prisma/issues/19951
https://github.com/prisma/prisma/issues/19249 note that this one is confirmed.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
