### ISSUE TITLE
Error in migration engine. Reason: [sql-schema-describer\src\walkers\column.rs:74:61] called `Option::unwrap()` on a `None` value 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#20221]
Command: `prisma migrate diff --from-url postgresql://***?sslmode=verify-full --to-schema-datamodel prisma\\schema.prisma --script`
Version: `4.11.0`
Binary Version: `8fde8fef4033376662cad983758335009d522acb`
Report: https://prisma-errors.netlify.app/report/14818 
OS: `x64 win32 10.0.19044`

Rust Stacktrace:
```
Starting migration engine RPC server
[sql-schema-describer\src\walkers\column.rs:74:61] called `Option::unwrap()` on a `None` value
```

**Comment by janpio** [comment]
Does the error report have enough information to reproduce this?

**Comment by jkomyno** [comment]
> Does the error report have enough information to reproduce this?

The report doesn't have any actionable information, unfortunately, not even the Prisma schema. We only know the problem happened on Windows when running `prisma migrate diff --from-url postgresql://***?sslmode=verify-full --to-schema-datamodel` against a cloud CockroachDB instance.
