### ISSUE TITLE
Add dedicated documentation about working with multiple environments

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2022]
It's about the following and similar questions:

> How to work with different environments (dev, staging, prod) with Prisma and .env files?

Existing resources:

* https://www.graph.cool/forum/t/1-0-different-environments-different-graphcool-yml-files/2105/2?u=nilan
* https://www.prismagraphql.com/docs/reference/cli-command-reference/database-service/prisma-deploy-kee1iedaov

We should add

* [ ] a dedicated section in the documentation
* [ ] an example [here](https://github.com/graphcool/prisma/tree/master/examples).

**Comment by kenigbolo** [comment]
If this is still up for grabs I'd have to problem with working on this tomorrow.
