### ISSUE TITLE
Weird error message on `db push` with invalid connection string: Connection string redacted, weird grammar

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#20230]
### Bug description

With this schema:
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["jsonProtocol"]
}

datasource db {
  provider = "sqlite"
  url = "./dev.db"
}

model Answer {
  answerId Int     @id @default(autoincrement())
  cardId   Int
  known    Boolean @default(false)
  mastered Boolean @default(false)
}

```

and `db push` you get:
```
PS C:\Users\Jan\Documents\throwaway\14757> npx prisma@5.0.0 db push
Prisma schema loaded from schema.prisma
Datasource "db": SQLite database

Error: P1013: The provided database string is invalid. `<REDACTED>` is not a known connection URL scheme. Prisma cannot determine the connector. in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.
```

Note the two problems:
1. The error message tries to spell out the connection string, but it is replaced by `<REDACTED>`. If we are uncomfortable printing the connection string, we should just adapt the error message.
2. `Prisma cannot determine the connector. in database URL.`

### Prisma Version

```
5.0.0
```

**Comment by petradonka** [comment]
@quest-bot stash 50

**Comment by obaraelijah** [comment]
@quest-bot embark

**Comment by obaraelijah** [comment]
@quest-bot embark

**Comment by fiznool** [comment]
Looks like this error message comes from somewhere in https://github.com/prisma/prisma-engines/

**Comment by petradonka** [comment]
@fiznool - I see you're already on a path here! If the solution needs a PR in `prisma-engines`, you can simply open an empty PR on this repo to still claim the loot, in addition to the actual solution PR in `prisma-engines` 👀 It's a temporary solution for now, as indeed some the relevant code lives in `prisma-engines`.

**Comment by fiznool** [comment]
Thank you for the information @petradonka! Sadly I don't know any Rust so can't contribute to the other project in any meaningful way.

**Comment by jaysaadana19** [comment]
@quest-bot embark

**Comment by jaysaadana19** [comment]
@quest-bot loot #20230

**Comment by onichandame** [comment]
@quest-bot embark

**Comment by petradonka** [comment]
@quest-bot reward @onichandame

**Comment by beshur** [comment]
What has happened here?
