### ISSUE TITLE
P4001 The introspected database was empty for MongoDB Atlas

### ISSUE THREAD

**Issue by elledienne** [prisma/prisma#20249]
### Bug description

I am trying to introspect a MongoDB database hosted on Atlas but it's not working: despite the DB having several tables, the introspection returns the following error

```
Prisma schema loaded from prisma/schema.prisma
Environment variables loaded from .env
Datasource "db": MongoDB database "<removed>" at "<removed>.mongodb.net"

✖ Introspecting based on datasource defined in prisma/schema.prisma
Error:
P4001 The introspected database was empty:

prisma db pull could not create any models in your schema.prisma file and you will not be able to generate Prisma Client with the prisma generate command.

To fix this, you have two options:

- manually create a table in your database.
- make sure the database connection URL inside the datasource block in schema.prisma points to a database that is not empty (it must contain at least one table).

Then you can run prisma db pull again.
```

### How to reproduce

Run `npx prisma db pull`

### Expected behavior

I'd expect the `schema.prisma` to be populated with models resulting from the DB introspection

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: `macOS`
- Database: `MongoDB`
- Node.js version: `v18.3.0`

### Prisma Version

```
v5.0.0 (but also tried 4.16.2 and 4.13.0 with the same result)
```

**Comment by masterbater** [comment]
Your db is empty thats the error cause by it. Just add the database name in DATABASE_URL

**Comment by elledienne** [comment]
> Your db is empty thats the error cause by it. Just add the database name in DATABASE_URL

Not sure that's the problem. When I run the introspection the command correctly identifies the db

> Datasource "db": MongoDB database "<removed>" at "<removed>.mongodb.net"

**Comment by janpio** [comment]
Do you actually have data in these MongoDB collections @elledienne? Our MongoDB introspection needs data to be able to infer the desired types.

**Comment by elledienne** [comment]
Never mind, the issue was caused by a typo in the DB name, sorry for the useless issue! I'm just a bit surprised that Prisma was able to connect anyway without any warning, that threw me off

**Comment by janpio** [comment]
That is indeed not super useful, but not surprising with MongoDB - everything is more dynamic there.
