### ISSUE TITLE
npm install of Prisma CLI fails on preinstall with no logs when Node.js version is lower than minimum

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#20260]
> I create the project with npx prisma init and uploaded to Render with different error, i link you the github repo to check it out (im using neon.tech as DB provider)
>
> https://github.com/Dominguezd01/PrismaTest
>
> I hope this helps, peace

_Originally posted by @Dominguezd01 in https://github.com/prisma/prisma/issues/20193#issuecomment-1637046919_

**Comment by Jolg42** [comment]
@Dominguezd01 I believe your problem here is that you are trying to install Prisma 5 CLI which requires Node.js v16.13 at minimum.

And in your screenshot, it says your deployment is using v14.17
![renderError](https://github.com/prisma/prisma/assets/1328733/e84f9b3a-bef7-4bd9-8504-29f25029408b)

Could you upgrade your Node.js version? (We recommend to upgrade to v18 when possible).

**Comment by Jolg42** [comment]
Why this happened?
Because we have this code to check the Node.js version during preinstall:
https://github.com/prisma/prisma/blob/main/packages/cli/scripts/preinstall.js#L9

I think we can keep this issue to see how we can make it better.

**Comment by janpio** [comment]
Are we missing the actual error message output there @Jolg42 or is this a Render problem?

**Comment by Jolg42** [comment]
The "box" seems to be truncated here, but a quick local test show the same 🙈 
I'll try a quick fix 
```
npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'prisma@5.0.0',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v15.14.0', npm: '7.7.6' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /Users/j42/Repros/node14/node_modules/prisma
npm ERR! command failed
npm ERR! command sh -c node scripts/preinstall-entry.js
npm ERR! ┌─┐
npm ERR! │   …│
npm ERR! └┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/j42/.npm/_logs/2023-07-17T14_21_08_241Z-debug.log
```

**Comment by janpio** [comment]
@Joel created a PR at https://github.com/prisma/prisma/pull/20263

Sorry that this is so hidden in Prisma 5 @Dominguezd01. It will be fixed in 5.1.0. Can you upgrade your Node version on Render to Node 16?

**Comment by okechukwu26** [comment]
Aug 27 01:46:17 AM  ==> It looks like we don't have access to your repo, but we'll try to clone it anyway.
Aug 27 01:46:17 AM  ==> Cloning from https://github.com/okechukwu26/prisma...
Aug 27 01:46:17 AM  ==> Checking out commit 94b103264027bf395f2c71979aad139efcb6df34 in branch main
Aug 27 01:46:21 AM  ==> Using Node version 14.17.0 (default)
Aug 27 01:46:21 AM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Aug 27 01:46:21 AM  ==> Running build command 'npm install && npm run build'...
Aug 27 01:46:37 AM  
Aug 27 01:46:37 AM  > prisma@5.2.0 preinstall /opt/render/project/src/node_modules/prisma
Aug 27 01:46:37 AM  > node scripts/preinstall-entry.js
Aug 27 01:46:37 AM  
Aug 27 01:46:37 AM  ┌──────────────────────────────────────────────┐
Aug 27 01:46:37 AM  │    Prisma only supports Node.js >= 16.13.    │
Aug 27 01:46:37 AM  │    Please upgrade your Node.js version.      │
Aug 27 01:46:37 AM  └──────────────────────────────────────────────┘
Aug 27 01:46:38 AM  npm ERR! code ELIFECYCLE
Aug 27 01:46:38 AM  npm ERR! errno 1
Aug 27 01:46:38 AM  npm ERR! prisma@5.2.0 preinstall: `node scripts/preinstall-entry.js`
Aug 27 01:46:38 AM  npm ERR! Exit status 1
Aug 27 01:46:38 AM  npm ERR!
Aug 27 01:46:38 AM  npm ERR! Failed at the prisma@5.2.0 preinstall script.
Aug 27 01:46:38 AM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug 27 01:46:38 AM  
Aug 27 01:46:38 AM  npm ERR! A complete log of this run can be found in:
Aug 27 01:46:38 AM  npm ERR!     /opt/render/.cache/_logs/2023-08-27T00_46_38_319Z-debug.log
Aug 27 01:46:38 AM  ==> Build failed 😞


i got this error while deploying on render and my node version is 20

**Comment by Jolg42** [comment]
@okechukwu26 I think the code is right here as you can see in your logs `Using Node version 14.17.0` so it looks like you need to switch to a newer version on Render.

**Comment by okechukwu26** [comment]
Thanks....I have been able to resolve it render was automatically using node 14.3 to build the app so I have to tell it to using the latest version while building

**Comment by mmoh-i** [comment]
> Thanks....I have been able to resolve it render was automatically using node 14.3 to build the app so I have to tell it to using the latest version while building

kindly  help on how you did it

**Comment by okechukwu26** [comment]
I created an environment variable on called render node version and input in the value the the node version type 20.5

**Comment by JeversonMisaelDaCruz** [comment]
I have a old project in nextJs my node is update but he keeps sendo me a error!
Prisma only supports Node.js >= 16.13.    │
npm ERR! │    Please upgrade your Node.js version.
