### ISSUE TITLE
Connection Limit Exceeded and CPU Burnout Issues

### ISSUE THREAD

**Issue by kashif-trailfive** [prisma/prisma#20272]
### Bug description

I hope this message finds you well. As part of the critical project team, I am reporting two urgent issues that require immediate attention.

Connection Limit Exceeded:
Our application has encountered instances where the connection limit has been exceeded, significantly impacting the user experience. It is crucial to address this matter urgently to ensure the seamless operation of the system.

CPU Burnout:
Additionally, our server is experiencing CPU burnout, leading to performance degradation and potential downtime. We must promptly resolve this problem to ensure the stability and reliability of our project.

As we prepare for significant growth, it is essential to address these challenges to maintain a smooth user experience and ensure the overall success of the project. I will create detailed issue reports for each problem and keep everyone informed about the progress.

Technical Details:
Our project utilizes Prisma ORM with a GraphQL API and is built on Node.js/TypeScript. We are running on GCP-k8 with six pods, each having 24 GB of RAM and 8 CPU. After careful consideration, we have set a connection pool limit of 16 with a 20-second timeout. Despite these configurations, we are still facing connection pool limit exceedance, leading to unresponsive queries and extended response times.

Additionally, we have noticed instances where the Database CPU experiences burnout, negatively affecting overall performance. We have attached graphs for reference.

In the past, we encountered heap memory burning issues, which improved after removing the promise.all function. However, there is still room for further stability enhancement.

We highly appreciate your immediate attention to these issues to ensure the smooth functioning of our project. Your support is vital as we work towards resolving these challenges.

![Screenshot 2023-07-18 at 1 52 19 PM](https://github.com/prisma/prisma/assets/69708599/83f8563f-de20-4aa9-8444-80c2e7aba74e)
![Screenshot 2023-07-18 at 1 52 33 PM](https://github.com/prisma/prisma/assets/69708599/0573f497-98be-4975-bff3-31221a572922)
![Screenshot 2023-07-18 at 1 52 46 PM](https://github.com/prisma/prisma/assets/69708599/1e5a2e1c-519e-4390-8777-11a3d49def57)
![Screenshot 2023-07-18 at 1 52 58 PM](https://github.com/prisma/prisma/assets/69708599/2c12c8ea-0296-4b14-abee-7604a9088f0f)
![Screenshot 2023-07-18 at 1 50 59 PM](https://github.com/prisma/prisma/assets/69708599/5c5113fe-e479-4adb-90b0-0361fe3a5445)

![Screenshot 2023-07-18 at 1 50 43 PM](https://github.com/prisma/prisma/assets/69708599/3c269a98-ab60-4489-a0d4-73c98bbb012b)

### How to reproduce

NA

### Expected behavior

- The application should be able to handle an increasing number of users without encountering connection limit issues or experiencing CPU burnout.

### Prisma information

schema.prisma
```generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["metrics"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

enum enumName {} 

model modelName {} 

...
...
...

model modelTwoName {}

```

utils.ts
```
import { PrismaClient } from '@prisma/client';

export interface Context {
  user: () => Promise<User | null | undefined>
  prisma: PrismaClient
  request: any
}

...
...
...
```

genre.ts

```
import { Context } from '../../utils'
import { GraphQLResolveInfo } from 'graphql'
import { genreReturnType } from '../ReturnType'
import { errorName } from '../../error/error'

export const genreMethods = {
    query: {
        async genre(_parent, args, ctx: Context, _info: GraphQLResolveInfo) {
            try {
                const item = await ctx.prisma.genre.findUnique({ ...args, include: genreReturnType })
                return item
            } catch (err) {
                console.log(err)
                throw err
            }
        },
    }
}

export default genreMethods

```

### Environment & setup

- Docker Image: node:16-alpine
- Database: MySQL/CloudSQL
- Node.js version: 16.16.0

### Prisma Version

```
4.1.0

```

**Comment by Jolg42** [comment]
Hi @kashif-trailfive, I noticed you are using a relatively old version, 4.1.0 is now 1 year old.
Did you consider upgrading, maybe? (Are they any blockers to upgrade the Prisma version?) 

On the performance side, we introduced `jsonProtocol` in `4.11.0` and made it generally available in `5.0.0`, many users sent us positive feedback, though this is not about database performance.

I also noticed that you top SELECT query return on average 10k rows.
You could try running these queries with EXPLAIN and see what is slow and maybe discover a missing index https://dev.mysql.com/doc/refman/8.0/en/explain.html

**Comment by janpio** [comment]
Some questions for clarification:

> Connection Limit Exceeded:
> Our application has encountered instances where the connection limit has been exceeded, significantly impacting the user experience. It is crucial to address this matter urgently to ensure the seamless operation of the system.

What kind of connection limit exactly? From Prisma or your database? What error message _exactly_ did you get?

> CPU Burnout:
> Additionally, our server is experiencing CPU burnout, leading to performance degradation and potential downtime. We must promptly resolve this problem to ensure the stability and reliability of our project.

Do I understand correctly that you have 1 database server, and that the available resources on that one are being fully utilized while you are running your application? Is that normal traffic or testing?

**Comment by kashif-trailfive** [comment]
Hi, 

Thank you for your responses and your deep analysis. We will diligently follow all the guidelines. Below are our answers to some questions.

Regarding the Prisma version, it has already been deployed on staging with the latest 5.x version. However, we need to thoroughly test it, as the Apollo Server version also requires an upgrade. We are upgrading it slowly to ensure backward compatibility. The next upgrade will be to the latest version.

Yes, this is normal production traffic.
> Is this normal production traffic or some load testing?
> 

Yes , The CPU/Memory usage on pods is generally normal and under the limit. However, sometimes when the connection pool limit is exceeded, servers/pods keep running, but queries stop responding. To address this, we have implemented a script that detects such issues and automatically restarts them. It may sound funny, but this patch was necessary to ensure minimal disruption and keep our users' experience uninterrupted.
> All the graphs you shared are from the database, correct? What does CPU look like on the pods/servers?
> 
The connection limit issue arises from Prisma. The error message we received is related to exceeding the connection pool limit. Additionally, when the database CPU is overloaded, users may experience unexpected logouts.
> What kind of connection limit exactly? From Prisma or your database? What error message _exactly_ did you get?
> 

Our server can handle up to 10,000 connections, and this limit has never been reached or exceeded.
![Screenshot 2023-07-19 at 12 51 49 PM](https://github.com/prisma/prisma/assets/69708599/744d4e5b-eb2f-4190-a771-d2b0758a1d4a)
![Screenshot 2023-07-19 at 12 52 31 PM](https://github.com/prisma/prisma/assets/69708599/ce69d77d-1edd-4c04-a94a-6d4790b6746d)

> > CPU Burnout:
> > Additionally, our server is experiencing CPU burnout, leading to performance degradation and potential downtime. We must promptly resolve this problem to ensure the stability and reliability of our project.
> 
> Do I understand correctly that you have 1 database server, and that the available resources on that one are being fully utilized while you are running your application? How many connections and queries should that database server be able to handle?
> 
> > Our project utilizes Prisma ORM with a GraphQL API and is built on Node.js/TypeScript. We are running on GCP-k8 with six pods, each having 24 GB of RAM and 8 CPU. After careful consideration, we have set a connection pool limit of 16 with a 20-second timeout.
> 

Yes, that's correct. The number of connections is calculated using the formula: Number of CPU * 2 + 1.
> So you are running 6 "servers" that are each running your application? The connection pool of Prisma is set to 16 connections (with 20 second timeout) on each of those "servers"?
> 
10000 connections 
> What does the database set up and configuration look like? What CPU and memory? How many connections does your database server allow at a time?
> 
> > Despite these configurations, we are still facing connection pool limit exceedance, leading to unresponsive queries and extended response times.
> 

From Prisma, we are getting this error 
```
Error: Timed out fetching a new connection from the connection pool. (More info: http://pris.ly/d/connection-pool, Current connection limit: 16)
```
 time to time , even without database CPU 100%

> What exactly do you mean by that? The same "connection limit exceeded" or something else? What is the exact error message you are getting?
> 
> > Additionally, we have noticed instances where the Database CPU experiences burnout, negatively affecting overall performance. We have attached graphs for reference.
> 

We can disregard this issue for now since it was related to the heap memory crash, which occurred due to the use of promise.all(). While addressing the connection timeout issue, we replaced promise.all() with a loop to fetch results, which also improved the heap memory situation to some extent. However, we are now facing a separate concern with the CPU reaching 100% utilization. It might be related or unrelated; we are not entirely sure at the moment.
> Is this the same "CPU Burnout" described above or something else?
> 
> > In the past, we encountered heap memory burning issues, which improved after removing the promise.all function. However, there is still room for further stability enhancement.
> 
 We were unsure of the exact number of promises/queries executed in the past, especially with the sudden increase in user traffic. As a result, we might need to conduct a reindexing of the database or explore other optimization measures to address the performance issues. Currently, we are closely monitoring the system and implementing scripts to automatically restart the servers/pods when connection pool limit exceedance occurs, which helps to maintain smoother operation during high traffic periods.
> How many promised/queries were you trying to executed in the past? How are you running them now instead?
> 
> > ![Screenshot 2023-07-18 at 1 50 43 PM](https://user-images.githubusercontent.com/69708599/254211633-3c269a98-ab60-4489-a0d4-73c98bbb012b.png)
> 
Yes, we believed that Prisma has indexed the queries. Currently, we are not fetching millions of results, but the small query execution is still taking an excessive amount of time. Moreover, we doubted that when one query is in execution, another one comes in and congests the system, leading to performance issues. We are unsure whether this is a code-related problem or another factor affecting the performance.
> If I read this table correctly, you have a small number of queries that produce most of the load on your system. They all run for a full second or (a lot!) longer. They are frequently called, and return a _lot_ of rows.
> 

Do you know which code triggers these queries?
Yes, we are aware of the code that triggers these queries. As GraphQL has the N+1 problem, we are actively working on optimization efforts to mitigate its impact. Despite the database size not being in the millions, we are still facing performance issues, which suggests that there might be some inefficient code parts causing these challenges.

Do these queries have appropriate indexes defined or do they really have to be that slow?
Yes, we are actively checking the indexes. As indicated in the image, the tables with the prefix '_tablename' are indexed tables, and Prisma handles the indexing. However, we are currently investigating whether these indexes are functioning optimally, as certain indexing algorithms may not work effectively with MySQL.

Can you share the relevant schema, Prisma Client query and then the full generated SQL query for any query >1s?

```
model User {
 ...
 favoriteGenres   Genre[]     @relation(name: "UserFavoriteGenre")
 ...
}
model Genre {
 ...
 users   User[]    @relation(name: "UserFavoriteGenre")
 ...
}

```

```
Query:  {
  query: 'query User($where: UserWhereUniqueInput!) {\n' +
    '  user(where: $where) {\n' +
    '    id\n' +
    '    name\n' +
    '    email\n' +
    '    favoriteGenres {\n' +
    '      id\n' +
    '      name\n' +
    '      projects {\n' +
    '        id\n' +
    '        name\n' +
    '      }\n' +
    '    }\n' +
    '  }\n' +
    '}',
  variables: { where: { id: 'cl74mncks00041q22520h2da7' } },
  operationName: 'User'
}
Query: SELECT `prisma-prod2`.`User`.`id`, `prisma-prod2`.`User`.`updatedAt`, `prisma-prod2`.`User`.`createdAt`, `prisma-prod2`.`User`.`email`, `prisma-prod2`.`User`.`name`, `prisma-prod2`.`User`.`status`, `prisma-prod2`.`User`.`artistName`, `prisma-prod2`.`User`.`password`, `prisma-prod2`.`User`.`secretHash`, `prisma-prod2`.`User`.`role`, `prisma-prod2`.`User`.`facebookId`, `prisma-prod2`.`User`.`googleId`, `prisma-prod2`.`User`.`korgId`, `prisma-prod2`.`User`.`avatarUrl`, `prisma-prod2`.`User`.`bio`, `prisma-prod2`.`User`.`headerImage`, `prisma-prod2`.`User`.`emailConfirmToken`, `prisma-prod2`.`User`.`emailConfirmExpires`, `prisma-prod2`.`User`.`joinedAt`, `prisma-prod2`.`User`.`inviteAccepted`, `prisma-prod2`.`User`.`emailConfirmed`, `prisma-prod2`.`User`.`deletedAt`, `prisma-prod2`.`User`.`lastLogin`, `prisma-prod2`.`User`.`lastLoginIp`, `prisma-prod2`.`User`.`isSuper`, `prisma-prod2`.`User`.`resetToken`, `prisma-prod2`.`User`.`resetExpires`, `prisma-prod2`.`User`.`magicLinkToken`, `prisma-prod2`.`User`.`magicLinkExpires`, `prisma-prod2`.`User`.`age`, `prisma-prod2`.`User`.`gender`, `prisma-prod2`.`User`.`musicTaste`, `prisma-prod2`.`User`.`typeOfMusician`, `prisma-prod2`.`User`.`recordingsCount`, `prisma-prod2`.`User`.`timelineItemsCount`, `prisma-prod2`.`User`.`relatedTimelineItemsCount`, `prisma-prod2`.`User`.`followsCount`, `prisma-prod2`.`User`.`followedByCount`, `prisma-prod2`.`User`.`projectsCount`, `prisma-prod2`.`User`.`tracksOwnedCount`, `prisma-prod2`.`User`.`devicesCount`, `prisma-prod2`.`User`.`notificationsCount`, `prisma-prod2`.`User`.`clapsCount`, `prisma-prod2`.`User`.`commentsCount`, `prisma-prod2`.`User`.`allProjectsCount`, `prisma-prod2`.`User`.`isDeveloper`, `prisma-prod2`.`User`.`dummy`, `prisma-prod2`.`User`.`isValidated`, `prisma-prod2`.`User`.`validatedAt`, `prisma-prod2`.`User`.`fileId`, `prisma-prod2`.`User`.`userId`, `prisma-prod2`.`User`.`phoneNumber`, `prisma-prod2`.`User`.`phoneNumberConfirmed`, `prisma-prod2`.`User`.`likedId`, `prisma-prod2`.`User`.`deactivateReason`, `prisma-prod2`.`User`.`isDeactivated`, `prisma-prod2`.`User`.`fcm_token`, `prisma-prod2`.`User`.`facebookLink`, `prisma-prod2`.`User`.`instagramLink`, `prisma-prod2`.`User`.`location`, `prisma-prod2`.`User`.`soundCloudLink`, `prisma-prod2`.`User`.`clappedProjectsCount`, `prisma-prod2`.`User`.`deleteAfter` FROM `prisma-prod2`.`User` WHERE `prisma-prod2`.`User`.`id` = ? LIMIT ? OFFSET ?
Params: ["cl74mncks00041q22520h2da7",1,0]
Duration: 158ms
Query: SELECT `prisma-prod2`.`_UsersClappedProject`.`B`, `prisma-prod2`.`_UsersClappedProject`.`A` FROM `prisma-prod2`.`_UsersClappedProject` WHERE `prisma-prod2`.`_UsersClappedProject`.`B` IN (?)
Params: ["cl74mncks00041q22520h2da7"]
Duration: 418ms
Query: SELECT `prisma-prod2`.`_MusicalInstrumentUser`.`B`, `prisma-prod2`.`_MusicalInstrumentUser`.`A` FROM `prisma-prod2`.`_MusicalInstrumentUser` WHERE `prisma-prod2`.`_MusicalInstrumentUser`.`B` IN (?)
Params: ["cl74mncks00041q22520h2da7"]
Duration: 364ms
Query: SELECT `prisma-prod2`.`_UserFavoriteGenre`.`B`, `prisma-prod2`.`_UserFavoriteGenre`.`A` FROM `prisma-prod2`.`_UserFavoriteGenre` WHERE `prisma-prod2`.`_UserFavoriteGenre`.`B` IN (?)
Params: ["cl74mncks00041q22520h2da7"]
Duration: 457ms
Query: SELECT `prisma-prod2`.`Genre`.`id`, `prisma-prod2`.`Genre`.`name`, `prisma-prod2`.`Genre`.`createdAt`, `prisma-prod2`.`Genre`.`updatedAt`, `prisma-prod2`.`Genre`.`description`, `prisma-prod2`.`Genre`.`rank` FROM `prisma-prod2`.`Genre` WHERE `prisma-prod2`.`Genre`.`id` IN (?,?,?,?)
Params: ["cl82wppz4125841p1swti93jdp","clbuyambj0015zk1nqz6anopz","clbuyambj0019zk1nen7vwej0","clbw67x0700090v1nb6gy6jyj"]
Duration: 406ms
Query: SELECT `prisma-prod2`.`Geolocation`.`id`, `prisma-prod2`.`Geolocation`.`createdAt`, `prisma-prod2`.`Geolocation`.`updatedAt`, `prisma-prod2`.`Geolocation`.`userId`, `prisma-prod2`.`Geolocation`.`latitude`, `prisma-prod2`.`Geolocation`.`longitude` FROM `prisma-prod2`.`Geolocation` WHERE `prisma-prod2`.`Geolocation`.`userId` IN (?)
Params: ["cl74mncks00041q22520h2da7"]
Duration: 411ms

```

It appears that the problem might be related to the IN part of the query, but we are not entirely certain at this point.

Do they really need to return that many rows? 
This is indeed a valid question. The frontend team is responsible for deciding how much data they need to fetch from the endpoint. In GraphQL, when they include more data points with 'include,' it generates additional SQL statements in the final query. As a result, the number of rows returned can increase significantly based on their requirements.

Could these query results maybe be cached, even in a local variable?
Yes, we attempted to maintain a local cache, but due to the nature of the project data, the cache kept increasing in size. Nonetheless, we successfully implemented the cache with the help of Apollo Server, and we believe it is functioning effectively.
> Do you know which code triggers these queries? Do these queries have appropriate indexes defined or do they really have to be that slow? Can you share the relevant schema, Prisma Client query and then the full generated SQL query for any query >1s? Do they really need to return that many rows? Could these query results maybe be cached, even in a local variable?

**Comment by Jolg42** [comment]
Note: A colleague mentioned that you could check Query Insights to see the CPU consumption of your queries: https://cloud.google.com/sql/docs/mysql/using-query-insights#specific-query

**Comment by kashif-trailfive** [comment]
> Note: A colleague mentioned that you could check Query Insights to see the CPU consumption of a specific query: https://cloud.google.com/sql/docs/mysql/using-query-insights#specific-query

Yes, we have identified two queries causing problems. It's challenging to locate them in the code as the ORM is generating the queries, and the frontend is handling data inclusion. Therefore, we are extensively working to find the bottleneck. Here is the screenshot from our Query insight.

![254211633-3c269a98-ab60-4489-a0d4-73c98bbb012b](https://github.com/prisma/prisma/assets/69708599/e6a6dec4-8f7c-49a4-a5c8-c23c81035d84)

**Comment by kashif-trailfive** [comment]
Some POST method latency as well: 
![Screenshot 2023-07-19 at 3 24 03 PM](https://github.com/prisma/prisma/assets/69708599/5ff19971-8924-4d76-970b-c1a8dbf3c619)

**Comment by janpio** [comment]
@kashif-trailfive Your comment https://github.com/prisma/prisma/issues/20272#issuecomment-1641681226 was formatted a bit confusingly for me (you put the responses first, and then the quote what you were responding to), so I quickly went through your post and moved that around (I did not delete any text). Please double check if I got it all correct. I will follow up later.

**Comment by kashif-trailfive** [comment]
@janpio  Thanks for your reply, it's very helpful!

> If I was you @kashif-trailfive, I would do 3 things now:
> 

We have an endpoint called 'AllProjects' that also retrieves information about users associated with each project, so many to many. When the frontend calls this endpoint with 20 projects, it generates 66 underlying queries to retrieve users(right now), which involve many-to-many joins with 'genre' and 'musical instrument' tables. As a result, so if you see making 5000 calls to the 'AllProjects' endpoint in an hour leads to 64000-74000 calls to the 'users' endpoint, and this number increases proportionally for further queries. The reason for this behavior is due to the use of GraphQL Prisma API 'include' feature. The more data we include, the more queries are built up. We are currently optimizing this process to reduce the query load as much as possible.
![Screenshot 2023-07-21 at 4 37 40 PM](https://github.com/prisma/prisma/assets/69708599/f9a1130a-fd54-4983-a341-029945aef5e3)


> 1. Really focus on understanding the top queries (or even just start with the top one) and make them/it disappear from that list. I can't think of any reason why a query would need to return avg >10.000 results and take avg 12 seconds to do that- and still be useful in an app.
>    Can you share the full query from the top queries?
>    Usually, it is possible to go back to understand what Prisma Client query would create this SQL query. From the leading underscore of the table `_UserFavoriteGenre` I can already know that this is part of a [many-to-many relation of Prisma](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations) for example, indeed the one between `User` and `Genre` you shared above. Why would such a query ever return >10.000 results? Do you know where you run a Prisma Client query that would query that relation?

Now, this is interesting. We are not entirely sure what will happen if we increase the connection pool size, as there is no clear documentation available on the topic. Currently, we have set the maximum connections to 1024, and it seems to be working fine. However, I would like to understand what would be an optimal size for a large pool of connections. Can we use Prisma DataProxy with a long-running server instead of a serverless setup, and would it be beneficial for performance?

> 2. Your database connections are bored. CPU and memory of your pods also seem to be bored. On the other hand you are getting connection pool timeouts. That error indicates a _capacity_ and _saturation_ problem - in that the queries an application tries to perform, can not be performed in the available time (the pool timeout) - so you get an error. This happens very quickly if you have some queries that are very slow, as they "hog" connections for a long time and then the queue gets to long - and the error explodes in your face.
>    What happens if you double or triple the connection limit of each pod? If CPU and memory are fine, you should be able to use a _lot_ more of those available 10.000 connections from your database! (Unfortunately the slow queries will probably still take over _all_ connections in the connection pool sooner or later. So you might need to increase further, or do the following:

max_execution_time is seems to be very helpful. Let me share an interesting thing with you: we had a conversation with the Google team, and they mentioned that we have all options available in MYSQL. However, we discovered that query caching was only accessible for Enterprise Plus users. Despite having an Enterprise Plus version (we have Enterprise) we decided to update our database version from 8.26 to 8.35, and to our surprise, everything started functioning smoothly. The CPU usage dropped significantly to just 0.5%, and the query response times improved to milliseconds. Honestly, I can't pinpoint the exact reason for this improvement, but we should investigate further to understand the underlying cause. It's essential to figure it out, as any potential issue could arise again in the future.

You see, 5000 project queries triggered 79000 user queries. We have also requested our FE team to analyze this in detail. Additionally, we are currently working on implementing New Relic for our backend with Kubernetes (k8s).
![Screenshot 2023-07-21 at 4 37 40 PM](https://github.com/prisma/prisma/assets/69708599/9956546b-157f-45a0-9d2c-1a348ffa2647)
![Screenshot 2023-07-21 at 4 38 09 PM](https://github.com/prisma/prisma/assets/69708599/02d49e9a-0ddd-4419-9905-d94592b21d92)


> 3. What happens if you configure your database server to kill queries that take longer than xxx ms? That could ensur that no queries can hog any connection to long (MySQL has a setting `max_execution_time`). Not that this will of course make parts of your application explode - but then you can figure out where exactly that is and why these queries are so slow.
> 
> So to recap, in our opinion you have some bad database queries that kill your database CPU, and also block the Prisma connection pool and lead to timeouts there.

**Comment by janpio** [comment]
> We have an endpoint called 'AllProjects' that also retrieves information about users associated with each project, so many to many. When the frontend calls this endpoint with 20 projects, it generates 66 underlying queries to retrieve users(right now), which involve many-to-many joins with 'genre' and 'musical instrument' tables. As a result, so if you see making 5000 calls to the 'AllProjects' endpoint in an hour leads to 64000-74000 calls to the 'users' endpoint, and this number increases proportionally for further queries. The reason for this behavior is due to the use of GraphQL Prisma API 'include' feature. The more data we include, the more queries are built up. We are currently optimizing this process to reduce the query load as much as possible.

Less queries with less data returned is always better, so really make sure you _need_ all that data (also all the fields being returned, not just the rows) and then make sure all the queries really are fast by using indexes. Any query you can avoid, can not cause a problem. Any query that needs to return less, will allow you servers to handle more requests.

> ![Screenshot 2023-07-21 at 4 37 40 PM](https://user-images.githubusercontent.com/69708599/255166057-f9a1130a-fd54-4983-a341-029945aef5e3.png)

This new screenshot of the queries being executed already looks _much_ better. The throughput of queries in the connection pool should be seriously unblocked with that, as they are all _much_ faster than before.


> > 1. Really focus on understanding the top queries (or even just start with the top one) and make them/it disappear from that list. I can't think of any reason why a query would need to return avg >10.000 results and take avg 12 seconds to do that- and still be useful in an app.
> >    Can you share the full query from the top queries?
> >    Usually, it is possible to go back to understand what Prisma Client query would create this SQL query. From the leading underscore of the table `_UserFavoriteGenre` I can already know that this is part of a [many-to-many relation of Prisma](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations) for example, indeed the one between `User` and `Genre` you shared above. Why would such a query ever return >10.000 results? Do you know where you run a Prisma Client query that would query that relation?
> 
> Now, this is interesting. We are not entirely sure what will happen if we increase the connection pool size, as there is no clear documentation available on the topic. Currently, we have set the maximum connections to 1024, and it seems to be working fine. However, I would like to understand what would be an optimal size for a large pool of connections. 

That is one of the big questions of database usage - and it depends on a million different considerations.

Generally, we recommend we start with a pretty low number (hence our really conservative default), and only play with that if the traffic volume you get can not be handled - as is the case for you! Then you can increase it step by step and observer what that does to your app. If you have a bigger pool, that means Prisma can open and then use more connections at a time. This comes at a cost - opening a connection is slow, and managing them takes CPU and memory. So you have to watch the resource usage of your pods. A higher connection pool liit/size should lead to more resources being used. But when they are open, you have more "pipes" through which you can execute queries, which means that a "connection pool timeout" is less probable.

> Can we use Prisma DataProxy with a long-running server instead of a serverless setup, and would it be beneficial for performance?

You can absolutely use it with a long running server as well. As your database can handle a _lot_ of connections though, and your application servers also seem to be pretty happy and underutilized, I would not necessarily recommend that route right now yet. I think you can get this under control with easier measures.

> > 3\. Your database connections are bored. CPU and memory of your pods also seem to be bored. On the other hand you are getting connection pool timeouts. That error indicates a _capacity_ and _saturation_ problem - in that the queries an application tries to perform, can not be performed in the available time (the pool timeout) - so you get an error. This happens very quickly if you have some queries that are very slow, as they "hog" connections for a long time and then the queue gets to long - and the error explodes in your face.
> >     What happens if you double or triple the connection limit of each pod? If CPU and memory are fine, you should be able to use a _lot_ more of those available 10.000 connections from your database! (Unfortunately the slow queries will probably still take over _all_ connections in the connection pool sooner or later. So you might need to increase further, or do the following:
> 
> max_execution_time is seems to be very helpful. 

It's one of those things that can _really_ protect your from some bad queries (as you had them in the overview before) killing your whole application. It's like a kill switch that prevents bad queries from causing too much trouble. (Unless of course these queries are the core functionality of your app - but then you are motivated to fix that quickly as well 😆 )

> Let me share an interesting thing with you: we had a conversation with the Google team, and they mentioned that we have all options available in MYSQL. However, we discovered that query caching was only accessible for Enterprise Plus users. Despite having an Enterprise Plus version (we have Enterprise) we decided to update our database version from 8.26 to 8.35, and to our surprise, everything started functioning smoothly. The CPU usage dropped significantly to just 0.5%, and the query response times improved to milliseconds. Honestly, I can't pinpoint the exact reason for this improvement, but we should investigate further to understand the underlying cause. It's essential to figure it out, as any potential issue could arise again in the future.

Wow, that is pretty amazing. We would be _really_ interested to hear from you when/if you figure out what is/was going on there with 8.26. Mayyyybe some index previously was not used accidentally, and this was fixed - that would be the most simple explanation really. For now I am just happy for you! 🥳 

 
> You see, 5000 project queries triggered 79000 user queries. We have also requested our FE team to analyze this in detail. Additionally, we are currently working on implementing New Relic for our backend with Kubernetes (k8s). ![Screenshot 2023-07-21 at 4 37 40 PM](https://user-images.githubusercontent.com/69708599/255164699-9956546b-157f-45a0-9d2c-1a348ffa2647.png) ![Screenshot 2023-07-21 at 4 38 09 PM](https://user-images.githubusercontent.com/69708599/255164708-02d49e9a-0ddd-4419-9905-d94592b21d92.png)

Both very good ideas. 

(From my own experience: Be careful with New Relic, using an APM like that is usually so impressive that you will want to use it on every project in the future and optimize all the things it points out 😄. Flipside is that the cost can be pretty heavy sometimes.)

**Comment by kashif-trailfive** [comment]
Thank you for your suggestion, which was very helpful. Yes, I think the table index somehow got blocked or encountered an issue, but now it's back in action. We will investigate the indexing in more detail, as we are currently relying on manual indexes in Prisma.

**Comment by kashif-trailfive** [comment]
@janpio We are currently facing a heap memory leak at a very minute level (as well). After running in production for 20 or more hours, our pods keep restarting. Any idea what might be causing this? We have already addressed some areas in the code where we suspect Promise.all could be causing issues in old space. If you have any quick suggestions or specific areas to look into, we would greatly appreciate it.

**Comment by janpio** [comment]
Unfortunately nothing directly comes to mind, there are far to many reasons why this could be happening - connected to Prisma or not.

Back to the original problem, do I understand correctly that the situations is now generally under control? The database CPU is not eaten up any more, and the connection pool can now also handle the load you are putting at it?

**Comment by kashif-trailfive** [comment]
@janpio Thank you for the update. Yes, I understand that there might not be a straightforward solution for this heap issue, considering the various possible reasons behind it.  It seems that one of the causes could be query overloading with data to fetch.

Regarding the original problem, The situation is now generally under control. It's a positive outcome that the database CPU is no longer overwhelmed, and the connection pool is effectively handling the workload.

With the successful resolution of the problem, I am going to close this issue with thanks :)

**Comment by janpio** [comment]
Thanks for the update. 

If there are any other things you think Prisma is involved or influencing, please let us know. It was a pleasure to debug this together with your from the distance, and as you provided all the information you had (including diagrams and logs) we could really dive deep here and get to real conclusions. Thanks, and all the best!
