### ISSUE TITLE
Error Code P3006 with Error Code: P1014

### ISSUE THREAD

**Issue by SyahmiRafsan** [prisma/prisma#20303]
### Bug description

Hi there, I'd like to add a new column to my User model but when I want to migrate dev, it gives me this error:

```
Error: P3006

Migration `20230621052236_product_purchase_purchaseproduct` failed to apply cleanly 
to the shadow database.
Error code: P1014
Error:
The underlying table for model `users` does not exist.
```

I have a  `@@map(name: "users") ` for my User model.

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id              String            @id @default(cuid())
  bio             String?
  name            String?
  phone           String?
  email           String?           @unique
  createdAt       DateTime          @default(now()) @map(name: "created_at")
  updatedAt       DateTime          @updatedAt @map(name: "updated_at")
  posts           Post[]
  likes           Like[]
  emailVerified   DateTime?
  image           String?
  accounts        Account[]
  sessions        Session[]
  purchases       Purchase[]
  products        Product[]
  PurchaseProduct PurchaseProduct[]

  @@map(name: "users")
}

model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? @db.Text
  access_token      String? @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.Text
  session_state     String?
  user              User    @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

model Post {
  id        String   @id @default(cuid())
  title     String?
  content   String
  published Boolean  @default(true)
  author    User     @relation(fields: [authorId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  // likes     Int?     @default(0) 
  // replies   Int?     @default(0)
  authorId  String
  slug      String
  createdAt DateTime @default(now()) @map(name: "created_at")
  updatedAt DateTime @updatedAt @map(name: "updated_at")
  likes     Like[]
  parentId  String?
  parent    Post?    @relation("PostReplies", fields: [parentId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  replies   Post[]   @relation("PostReplies")
  category  Int
}

model Like {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now()) @map(name: "created_at")
  authorId  String
  author    User     @relation(fields: [authorId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  postId    String
  post      Post     @relation(fields: [postId], references: [id], onDelete: Cascade, onUpdate: Cascade)
}

model Product {
  id              String            @id @default(cuid())
  name            String
  features        Int
  price           Int
  priceDiscount   Int
  createdAt       DateTime          @default(now()) @map(name: "created_at")
  updatedAt       DateTime          @updatedAt @map(name: "updated_at")
  creatorId       String
  creator         User              @relation(fields: [creatorId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  purchaseProduct PurchaseProduct[]
}

model Purchase {
  id            String            @id @default(cuid())
  createdAt     DateTime          @default(now()) @map(name: "created_at")
  purchaserId   String
  purchaser     User              @relation(fields: [purchaserId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  products      PurchaseProduct[]
  transactionId String
  status        String
}

model PurchaseProduct {
  id            String   @id @default(cuid())
  name          String
  features      Int
  price         Int
  priceDiscount Int
  createdAt     DateTime @default(now()) @map(name: "created_at")
  updatedAt     DateTime @updatedAt @map(name: "updated_at")
  productId     String
  product       Product  @relation(fields: [productId], references: [id])
  purchaseId    String
  purchase      Purchase @relation(fields: [purchaseId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  purchaserId   String
  purchaser     User     @relation(fields: [purchaserId], references: [id], onDelete: Cascade, onUpdate: Cascade)
}

```

Here is my migration SQL:

```
-- CreateTable
CREATE TABLE "Product" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "features" INTEGER NOT NULL,
    "price" INTEGER NOT NULL,
    "priceDiscount" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "creatorId" TEXT NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Purchase" (
    "id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "purchaserId" TEXT NOT NULL,
    "transactionId" TEXT NOT NULL,
    "status" TEXT NOT NULL,

    CONSTRAINT "Purchase_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PurchaseProduct" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "features" INTEGER NOT NULL,
    "price" INTEGER NOT NULL,
    "priceDiscount" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "productId" TEXT NOT NULL,
    "purchaseId" TEXT NOT NULL,
    "purchaserId" TEXT NOT NULL,

    CONSTRAINT "PurchaseProduct_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Purchase" ADD CONSTRAINT "Purchase_purchaserId_fkey" FOREIGN KEY ("purchaserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PurchaseProduct" ADD CONSTRAINT "PurchaseProduct_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PurchaseProduct" ADD CONSTRAINT "PurchaseProduct_purchaseId_fkey" FOREIGN KEY ("purchaseId") REFERENCES "Purchase"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PurchaseProduct" ADD CONSTRAINT "PurchaseProduct_purchaserId_fkey" FOREIGN KEY ("purchaserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

```

### Environment & setup

- OS: Windows 10
- Database: PostgreSQL
- Node.js version: v18.14.2

### Prisma Version

```
    "@prisma/client": "^5.0.0",
  "prisma": "^5.0.0",
```

I tried upgrading to 5.0 from 4.15 for both packages in order to solve this error.

**Comment by janpio** [comment]
The error message indicates that when executing `20230621052236_product_purchase_purchaseproduct` it tries to reference a table `users` that does not exist. Do you have earlier/previous migrations that indeed do a `CREATE TABLE "users"`? If not, the error message is fully correct.

**Comment by SyahmiRafsan** [comment]
> The error message indicates that when executing the migration `20230621052236_product_purchase_purchaseproduct` it tries to reference a table `users` that does not exist. (We can see in the SQL you shared above, that it indeed tries to create foreign keys that reference that table.)
> 
> Do you have earlier/previous migrations that indeed do a `CREATE TABLE "users"`? If not, the error message is fully correct and your migration history is somehow messed up.

Yes, I did have an init migration with CREATE TABLE "users". 

```
-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "bio" TEXT,
    "name" TEXT,
    "email" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "emailVerified" TIMESTAMP(3),
    "image" TEXT,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Account" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);

-- CreateTable
CREATE TABLE "Post" (
    "id" TEXT NOT NULL,
    "title" TEXT,
    "content" TEXT NOT NULL,
    "published" BOOLEAN NOT NULL DEFAULT true,
    "authorId" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "parentId" TEXT,
    "category" INTEGER NOT NULL,

    CONSTRAINT "Post_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Like" (
    "id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "authorId" TEXT NOT NULL,
    "postId" TEXT NOT NULL,

    CONSTRAINT "Like_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

-- AddForeignKey
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Post"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Like" ADD CONSTRAINT "Like_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Like" ADD CONSTRAINT "Like_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE CASCADE ON UPDATE CASCADE;
```

**Comment by janpio** [comment]
Hmm, there goes my theory. Can you maybe share a zipped up version of your `prisma/migrations` folder and a full copy of your schema? That would allow us to reproduce this ourselves.

(I now also notice that the error message you are getting is probably different from what a migration file that references a non existent table would be getting.)

**Comment by SyahmiRafsan** [comment]
> Hmm, there goes my theory. Can you maybe share a zipped up version of your `prisma/migrations` folder and a full copy of your schema? That would allow us to reproduce this ourselves.
> 
> (I now also notice that the error message you are getting is probably different from what a migration file that references a non existent table would be getting.)

It is alright @janpio, thanks for replying!

FYI, I tried changing the latest migration SQL file from `REFERENCES "users"("id")` to `REFERENCES "User"("id")` but to no avail.

Please find attached the whole prisma folder which includes /migrations and also my full schema:
[prisma.zip](https://github.com/prisma/prisma/files/12142731/prisma.zip)

I am using railway's managed PostgreSQL instance (in case it somehow did had any effect)

Thanks once again!

**Comment by SyahmiRafsan** [comment]
Hi, @janpio sorry for bugging you. 

Is everything alright for my schema files?

**Comment by janpio** [comment]
Looks like it to me, but we will only really know when someone has the time to reproduce this problem.

**Comment by SyahmiRafsan** [comment]
> Looks like it to me, but we will only really know when someone has the time to reproduce this problem.

I see, thanks for having a look at my files. 

Is there a possible workaround for me to add more fields to my schema without using migrate?

**Comment by Druue** [comment]
Okay, so downloading your schema and migrations history, I can reproduce the p1014
<img width="770" alt="image" src="https://github.com/prisma/prisma/assets/29753584/db3955f9-8bbe-403d-ba18-886db41d2fd6">

This is because your init migration is called just that: `init`. `migrate dev` is just not picking it up. Migrations are expected to run in order based on when they were created and therefore your `init` migration needs to have some sort of date representation that is older than `product_purchase_purchaseproduct`
<img width="625" alt="image" src="https://github.com/prisma/prisma/assets/29753584/cb1638d6-a762-4f1b-b133-47815ec57996">

**Comment by janpio** [comment]
@SyahmiRafsan Although this is marked as a confirmed bug now, there is nothing really wrong: You can just give your `init` migration a different name by renaming that folder, for example, `0_init` - and you should be good.

But of course we could improve that behavior, and for example warn about the migration without a leading number that would lead to it being applied last.

**Comment by Drunkss** [comment]
I experienced the problem too. to fix it, I deleted my migrations folder, then made a new one with  `npx prisma migrate dev`, wouldn't  recommend if your in prod though

**Comment by metacop** [comment]
> I experienced the problem too. to fix it, I deleted my migrations folder, then made a new one with `npx prisma migrate dev`, wouldn't recommend if your in prod though

I was coming to comment on the same thing. after a thousand failed attempts. delete the migrations folder. execute

1. npx prism migrate developer

2. generate npx prism

and this in production. Of course I have a dev branch that has all the migration files.

Conclusion: npx prism deploy not working

**Comment by sfratini** [comment]
Another potential issue. I was getting the "The underlying table for model `_prisma_migrations` does not exist". I was trying to change the permissions for that table for RLS in another migration. I commented that statement and running migrate dev again told me the 0_Init could not be implemented. I copied the SQL code into a DB Client and it marked that I had a weird char in the SQL. I guess by mistake a modified the Init SQL without realising it and my local migrations were not running. My bad on this but hopefully it could help others.

**Comment by gsusI** [comment]
> Okay, so downloading your schema and migrations history, I can reproduce the p1014 <img alt="image" width="770" src="https://private-user-images.githubusercontent.com/29753584/262387753-db3955f9-8bbe-403d-ba18-886db41d2fd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzQ1NjIsIm5iZiI6MTcyNjU3NDI2MiwicGF0aCI6Ii8yOTc1MzU4NC8yNjIzODc3NTMtZGIzOTU1ZjktOGJiZS00MDNkLWJhMTgtODg2ZGI0MWQyZmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDExNTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NTE3ZmZjNWJhOTM0MzEwYzRlNWNjMTg1ZGI4NzU3OWY0MTU4OWQyNjQ0YTA4ZTUxMWY0MGNhMmE5NjYwOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ci8s72olYQYDA7JRr3_HzhS5W25_JET7h7FNJQtnuEI">
> 
> This is because your init migration is called just that: `init`. ~`migrate dev` is just not picking it up~¹. Migrations are expected to run in order based on when they were created and therefore your `init` migration needs to have some sort of date representation that is older than `product_purchase_purchaseproduct` <img alt="image" width="625" src="https://private-user-images.githubusercontent.com/29753584/262388693-cb1638d6-a762-4f1b-b133-47815ec57996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzQ1NjIsIm5iZiI6MTcyNjU3NDI2MiwicGF0aCI6Ii8yOTc1MzU4NC8yNjIzODg2OTMtY2IxNjM4ZDYtYTc2Mi00ZjFiLWIxMzMtNDc4MTVlYzU3OTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDExNTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwOTg2YjFjZGZlMTliNzZhMjhiMDg0ZGU3ZmYyM2E4NzZlYjg1YjcwZTIwYjM4MjNkMjEzN2ZlNTQ4ZDljZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.15Yp6mjlvKCtOZgOsFCPffqcsM-wh5WW8DlODsMU1m0">
> 
> ¹ I went back and checked this and it _is_ being picked up, it's just sorted _after_ the migration that depends on it which effectively yields the same result ![image](https://private-user-images.githubusercontent.com/29753584/264683569-1db2540f-0036-491f-9f94-b3c248195c32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzQ1NjIsIm5iZiI6MTcyNjU3NDI2MiwicGF0aCI6Ii8yOTc1MzU4NC8yNjQ2ODM1NjktMWRiMjU0MGYtMDAzNi00OTFmLTlmOTQtYjNjMjQ4MTk1YzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDExNTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MzYxNmY1OTBlZWRhZjJhNTc3ZGZkNWJiYmNjY2YzMzQwNTE4ZjdkMzMxMjNjMzM1NGEyNTIwODRlYzFhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.INjqP3RDcctT06N3t2MDkhfRr0uYxbr_9UOJDJREBkc)

If you decide to manually change the name of any migration, remember that you'll need to change it both in your filesystem and in the database, within _prisma_migrations

**Comment by gauravvgat** [comment]
1 year post this and I'm facing this issue. How did you solve the issue? deleting migration folder and running it again doesn't feel like a good way.
