### ISSUE TITLE
Workflow for renaming fields in client

### ISSUE THREAD

**Issue by jhalborg** [prisma/prisma#2033]
## Problem
Congrats on the beta release! :tada:

I saw the videos on YouTube, and have a question.

Here (https://youtu.be/NK2p6WNs7EY?t=74) and here (https://youtu.be/IEg68UqgNBA?t=37), the narrator manually updates and then re-updates the field names for relations between two models, which will be reflected in the client API. This is great to be able to do, and I'd gladly do it once - but is this the finished workflow, meaning that you'll have to redo these changes every time you update your schema and hence client?

## Solution
To be able to provide names for specific fields once, and not have to do it again ever regardless of the number of introspections/generations of the client.

**Comment by janpio** [comment]
Hey, we will indeed implement something that keeps these changes if possible across Introspection runs: https://github.com/prisma/prisma/issues/2503 We call this "Re-Introspection" and will implement all kinds of details to hopefully make this awesome: https://github.com/prisma/prisma/labels/topic%3A%20re-introspection

I will close this issue now as the other one explicitly tracks the solution we are thinking of 🚀
