### ISSUE TITLE
MongoDB: Using a composite type as a Primary Key is not supported

### ISSUE THREAD

**Issue by bokukpark** [prisma/prisma#20345]
Hi Prisma Team! The following command just crashed.
I used mongodb.

## Schema
```
type BuyAccountId {
  username  String
  storeCode StoreCode
}

enum StoreCode {
  AMAZON
  EBAY
}

model BuyAccount {
  id       BuyAccountId @id @map("_id")
  password String
}
```

## Command

`generate --schema [redacted]`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v18.15.0           | 
| Prisma CLI  | 4.16.2             | 
| Engine      | 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81| 

## Error
```
RustPanic: RuntimeError: panicked at 'where objects cannot be empty', query-engine/schema/src/build/input_types/objects/filter_objects.rs:195:9
```

**Comment by janpio** [comment]
I just tried to reproduce this @bokukpark, but could not:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

type BuyAccountId {
  username  String
  storeCode StoreCode
}

enum StoreCode {
  AMAZON
  EBAY
}

model BuyAccount {
  id       BuyAccountId @id @map("_id")
  password String
}
```

`npx prisma generate` works successfully.

Did you do something else to get this error?

**Comment by bokukpark** [comment]
@janpio 
Thank you for reply.

I tried the Prisma 5.0.0 version, and it worked.
So, I will close this issue.
