### ISSUE TITLE
"PrismaClient is unable to be run in the browser" from NextJS Route Handler

### ISSUE THREAD

**Issue by YourAverageTechBro** [prisma/prisma#20347]
### Bug description

I am using the NextJS 13 App directory with Prisma as my ORM, but I am running into an issue where it says "PrismaClient is unable to be run in the browser" but PrismaClient is defined in a NextJS route handler (a server-side API route). It is defined at the path  `app/api/researchPaper/route.ts` and has a post request defined like so:

```ts
export async function POST(req: NextRequest) {
  const body = await req.json();
  try {
    const { userId } = postRequestValidator.parse(body);
    console.log("userId", userId);
    const { id } = await prisma.researchProject.create({ data: { userId } });
    const response: postResponse = {
      researchPaperId: id,
    };
    return NextResponse.json(response);
  } catch (error) {
    return new Response("Invalid request body", { status: 422 });
  }
}
```

I then call this endpoint from a client component with 

```ts
await fetch("/api/researchPaper", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });
```

I should not be getting the error because Prisma is not being used in a client component and it is correctly being run in the server. I am invoking the API endpoint that contains the Prisma client, and this should not cause any issues.

### How to reproduce

1. Create a route handler in NextJS 13 which calls prisma
2. Create a client component that calls the route handler that contains prisma reference
3. Error should appear

### Expected behavior

I expect the `PrismaClient is unable to be run in the browser` to not appear as it is not running in the browser.

### Environment & setup

- OS: macOS
- Database :MySQL
- Node.js version: v20.2.0

### Prisma Version

```
prisma                  : 5.0.0
@prisma/client          : 5.0.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Default Engines Hash    : 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Studio                  : 0.487.0

```

**Comment by L-Steinmacher** [comment]
Commenting for bug exposure.  Same error with a very similar setup.

**Comment by L-Steinmacher** [comment]
I found that I had a util function that I was exporting from my prisma seed that made it's way into a front end file.  I moved it to a util file and it seemed to fix the issue.  Hope that helps. @YourAverageTechBro

**Comment by YourAverageTechBro** [comment]
Yup, same thing was happening on my end. Moving it to a util file fixed the issue. Thanks @L-Steinmacher
