### ISSUE TITLE
PANIC: Could not retrieve alloc::string::String from Value

### ISSUE THREAD

**Issue by moling1234** [prisma/prisma#20373]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.12.0           | 
| OS              | darwin             |
| Prisma Client   | 5.0.0              |
| Query Engine    | 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584|
| Database        | mysql              |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /Users/Documents/workSpace/template/hello-prisma/.env
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from /Users/Documents/workSpace/template/hello-prisma/.env
prisma:client dirname /Users//Documents/workSpace/template/hello-prisma/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /Users/Documents/workSpace/template/hello-prisma/prisma
prisma:client clientVersion 5.0.0
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath /Users/Documents/workSpace/template/hello-prisma/node_modules/.prisma/client/libquery_engine-darwin.dylib.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```

```

**Comment by moling1234** [comment]
It is correct when I use local mysql, but it will report an error when using Alibaba cloud mysql, error msg is `
PANIC: Could not retrieve alloc::string::String from Value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
`

**Comment by janpio** [comment]
Can you share the schema of your project and what code was being executed when this error happened?
Can you maybe even create a reproduction repository that would help us just experience the problem? That would be optimal. Thanks!

**Comment by SevInf** [comment]
Hey @moling1234  ,

Did you get a chance to have a look at @janpio's previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment]
Hey @moling1234, could you please reply to the the [comment above](https://github.com/prisma/prisma/issues/20373#issuecomment-1657176166)? Thank you.

**Comment by miguelff** [comment]
Closing as stale
