### ISSUE TITLE
Error prisma db pull

### ISSUE THREAD

**Issue by guavila31** [prisma/prisma#20370]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull --force`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v14.20.1           | 
| Prisma CLI  | 4.1.0              | 
| Engine      | 8d8414deb360336e4698a65aa45a1fbaf1ce13d8| 

## Error
```
Error: [libs\datamodel\connectors\dml\src\model.rs:494:29] Hi there! We've been seeing this error in our error reporting backend, but cannot reproduce it in our own tests. The problem is that we have a primary key in the model `TBOPENP003` that uses the column `CODGROUP` which we for some reason don't have in our internal representation. If you see this, could you please file an issue to https://github.com/prisma/prisma so we can discuss about fixing this. -- Your friendly prisma developers. 
```

**Comment by janpio** [comment]
What database were you talking to @guavila31? Can you provide any other information that might be helpful for us to understand this like for example your SQL database schema that you tried to introspect with `db pull`? Thanks.

**Comment by SevInf** [comment]
Hey @guavila31  ,

Did you get a chance to have a look at @janpio's comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by guavila31** [comment]
I managed to solve the problem, it was a bug in Prisma 4.1.0. To resolve I updated to version 4.2.0

**Comment by SevInf** [comment]
Thank you! I am going to close this issue then.
