### ISSUE TITLE
Let's try if Prisma 2 works on glitch.com

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#2037]
See https://glitch.com/

Maybe a sqlite version would be nice to start.

Could be useful for mini-hackathons too!

**Comment by pantharshit00** [comment]
It works! https://glitch.com/~titanium-aspiring-alarm :) 


Not the best experience as I didn't get any autocompletion and glitch also doesn't list files generated by cli but it works. I will recommend codesandbox instead of glitch

**Comment by Jolg42** [comment]
Indeed I found that there is an official VS Code Glitch extension to get the best code experience with the free hosting:
https://marketplace.visualstudio.com/items?itemName=glitch.glitch
