### ISSUE TITLE
Duplicate expression index comment whenever db pull is run

### ISSUE THREAD

**Issue by jamesmacfie** [prisma/prisma#20386]
### Bug description

I have a database where some indexes result in the comment `This model contains an expression index which requires additional setup for migrations. Visit https://pris.ly/d/expression-indexes for more info.` when  `db pull` is run. Each time this is run _another_ comment gets added to that model which means you end up with as many comments as the number of times that `db pull` is run.

![image](https://github.com/prisma/prisma/assets/1654201/8c165b23-7776-4753-8b91-de41d5a4bc09)

You can see the Postgres SQL needed to duplicate this in this repo here: https://github.com/jamesmacfie/prisma_expression_index

Noting that the SQL [here](https://github.com/prisma/prisma/issues/2504) does not reproduce the comment bug but the SQL [here](https://github.com/prisma/prisma/issues/13184) does.

### How to reproduce

1. Clone down https://github.com/jamesmacfie/prisma_expression_index, setup the DB and run the setup SQL script (outside of Prisma)
2. Run `npx prisma pull`
3. See the comment added to your schema file
4. Run `npx prisma pull`again
5. Note that the comment has been added again

### Expected behavior

The comment only gets added once, if it does already exist. Else it does not add any more copies of it

### Prisma information

```prisma
// Add your schema.prisma
```

### Environment & setup

- OS: macOS, can also replicate on a Linux CI machine
- Database: PostgreSQL
- Node.js version: 18.16.1

### Prisma Version

```
5.0.0
```

**Comment by SevInf** [comment]
Can confirm on 5.1.1 with the provided reproduction.

**Comment by fnimick** [comment]
Found the offending code: https://github.com/prisma/prisma-engines/blob/9fe3fe474102fcbb680f0079a028fe304b7bf3f0/schema-engine/connectors/sql-schema-connector/src/introspection/rendering/models.rs#L130C40-L130C40

It looks like other tests check for the *addition* of elements requiring documentation, while the expression index check simply checks for presence, and ignores whether it previously existed (and therefore had the generated comment).
