### ISSUE TITLE
Only reachable with String types.

### ISSUE THREAD

**Issue by zahraamumtaz** [prisma/prisma#20404]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.20.0           | 
| OS              | darwin             |
| Prisma Client   | 4.16.1             |
| Query Engine    | b20ead4d3ab9e78ac112966e242ded703f4a052c|
| Database        | mongodb            |

## Logs
```
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```
async findUserProject(userDetail: User, companyId: string) {
    const response = await this.prisma.project.findMany({
      where: {
        companyId: companyId,
        users: {
          some: {
            id: {
              contains: userDetail.id,
            },
          },
        },
      },
    });

    console.log('query response', response);
    return response;
  }
```

## Schema
```prisma
model Project {
  id               String        @id @default(auto()) @map("_id") @db.ObjectId
  name             String?
  projectUrl       String?
  description      String?
  clientName       String?
  company          Company?      @relation(fields: [companyId], references: [id])
  companyId        String?       @db.ObjectId
  userIDs          String[]      @db.ObjectId
  users            User[]        @relation(fields: [userIDs], references: [id])
  projectRoleIDs   String[]      @db.ObjectId
  projectRoles     ProjectRole[] @relation(fields: [projectRoleIDs], references: [id])
  timePerSlot      TimePerSlot[]
  offlineSlot      OfflineSlot[]
  timePerHour      TimePerHour?
  tasks            Task[]
  isActive         Boolean       @default(false)
  isArchived       Boolean       @default(false)
  projectStartDate DateTime?
  projectEndDate   DateTime?
  createdAt        DateTime      @default(now())
  updatedAt        DateTime      @updatedAt

  @@map("projects")
}
```

## Prisma Engine Query
```
query getUserProjectList($companyId:String!){
	getUserProjectList(companyId: $companyId){
		id,
		projectUrl
	}
}
```

**Comment by janpio** [comment]
Can you share the data that the query should be returning? It is very probable that Prisma does not understand what is being returned there, and hence explodes unfortunately. Without the data, it will be super hard for us to reproduce this - as if we add data ourselves, it will certainly be valid and not trigger this crash. Thanks!

**Comment by SevInf** [comment]
Hey @zahraamumtaz  ,

Did you get a chance to have a look at @janpio's comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment]
Hey @zahraamumtaz, could you please reply to the comments above? Thank you.

**Comment by aqrln** [comment]
Hi @zahraamumtaz, unfortunately we can not reproduce the issue without more details, and we could not reach out to you asking for the missing information. We have to close the issue as it's not currently actionable, but please leave a comment at any point should you have more details, and we will reopen it and move it forward.
