### ISSUE TITLE
Relative file path in sqlite datasource url should be relative to project root

### ISSUE THREAD

**Issue by vadistic** [prisma/prisma#2040]
Imo path in sqlite url path should be relative to project root, not .prisma file

My reasoning:
- if I need db path for something else (eg. to copy test database with some script before tests) I need to keep two config variables (root relative and prisma relative paths)
- there's an issue https://github.com/prisma/prisma/issues/1738 ("Generator: `output` is relative to `./prisma`"). I think that relative paths in prisma file should have uniform behaviour - from prisma or from project root.
- not sure if it's valid argument, but thats a convention in eg. TypeORM's connectionOptions for sqlite

I know it's not a showstopper for anyone. I would just like to discuss what expected bahaviour should be since it would be unwise to change it later.

## Current behavior

```prisma
// prisma/deep/nested.schema.prisma
datasource db {
  provider = "sqlite"
  url      = "file:../../../temp/dev.db"
}
```

```console
// $tree
.
├── temp
│   └── dev.db
├── prisma
│   └── deep
│       └── nested
│           └── schema.prisma
...
```

## Expected behavior

```prisma
// prisma/deep/nested.schema.prisma
datasource db {
  provider = "sqlite"
  url      = "file:temp/dev.db"
}
```

```console
// $tree
.
├── temp
│   └── dev.db
├── prisma
│   └── deep
│       └── nested
│           └── schema.prisma
...
```

## Environment & setup
```console
@prisma/cli          : 2.0.0-beta.1
Current platform     : debian-openssl-1.1.x
```

**Comment by vadistic** [comment]
I'm guessing no many people have any opinions about this detail :man_shrugging: 

I've proposed this few months ago, since prisma 2.0 was in beta.

Now, after official release, it would be quite a breaking change. Imo this small detail is not worth disorienting everyone.

@janpio @divyenduz  If there is no considerations about this from prisma team, feel free to close this - there are enough open issuess here :)

**Comment by divyenduz** [comment]
Thanks for raising this again @vadistic, I will raise this internally again :)
