### ISSUE TITLE
Skip option for preinstall hook

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2042]
Cases like https://github.com/prisma/prisma/issues/2041 show that we need a way for people to skip the preinstall if it somehow breaks on their system. Super special case, but there is no other way for them to fix this (besides manually creating a folder... meh). 

Can one actually give input to preinstall hooks? If not, probably and ENV var is the easiest way.

**Comment by Sytten** [comment]
This is also important for the weird issue we see with yarn deleting the engine sometimes.

**Comment by janpio** [comment]
That is not connected, that is run via `postinstall` and needs to be fixed properly.
