### ISSUE TITLE
Know engines to download for Void Linux

### ISSUE THREAD

**Issue by danielgaban** [prisma/prisma#20434]
## Problem

from terminal when pnpm prisma init

> prisma:warn Prisma doesn't know which engines to download for the Linux distro "void". Falling back to Prisma engines built "debian".

## Suggested solution

Add which engine will be downloaded when user is using Void LInux.

## Alternatives

Remove warning and stay with the falling back engine "debian".

**Comment by Jolg42** [comment]
I didn't know about this distribution yet, link: https://voidlinux.org/

@danielgaban If you run `cat /etc/os-release`, I guess it looks like this?
https://github.com/prisma/prisma/issues/17545#issuecomment-1419758462

Also, could you tell me which version of Prisma you are using here?

**Comment by danielgaban** [comment]
@Jolg42 Yes it looks exactly. Prisma versions used:

> @prisma/client 4.16.2
> prisma 4.16.2

**Comment by cy1der** [comment]
+1 on this, got this warning when setting up RedwoodJS.

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
