### ISSUE TITLE
Unable to Create Optional One-to-Many Self Relation

### ISSUE THREAD

**Issue by seanemmer** [prisma/prisma#2044]
## Bug description

Unable to create optional One-to-Many self relation.  The docs describe how to do this, but the example only shows a "required" scenario.  The section is also confusing, where it subsequently states "Note that you can also require each user to have a teacher by making the teacher field required."

https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#one-to-many-self-relations

## How to reproduce

Add the following to your your prisma schema:

```
model Person {
  id                    Int      @id @default(autoincrement())
  name                  String?
  parent                Person?  @relation(name: "ParentChild", fields: [id], references: [id])
  children              Person[] @relation(name: "ParentChild")
}
```

Results in the following error message:

Error validating: The relation field `parent` uses the scalar fields id. The arity of those fields must be the same. The relation field is optional but the scalar fields are required.

It is possible to handle this scenario by creating a separate parentId scalar field, but this seems at odds with what the documentation says.

## Expected behavior

Schema is Valid

## Prisma information

Prisma 2 Beta 1

## Environment & setup

Mac OSX

**Comment by ranjan-purbey** [comment]
Create a second scalar field called parentId, so that the model looks like:
```
model Person {
  id                    Int      @id @default(autoincrement())
  name                  String?
  parent                Person?  @relation(name: "ParentChild", fields: [parenId], references: [id])
  parentId             Int?
  children              Person[] @relation(name: "ParentChild")
}
```

**Comment by seanemmer** [comment]
@ranjan-purbey I understand that this is an option, but it is not what the documentation says to do (https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#one-to-many-self-relations):

```
model User {
  id       Int      @id @default(autoincrement())
  name     String?
  teacher  User     @relation("TeacherStudents", fields: [id], references: [id])
  students User[]   @relation("TeacherStudents")
}
```

I'm trying to figure out whether the docs are wrong or the use of a second scalar field is necessary for optional relations.

**Comment by Sytten** [comment]
You definitely need a new field here the documentation needs to be updated. If you were to model that in raw SQL you would create a new column so thats what is needed here too.

**Comment by ranjan-purbey** [comment]
@Sytten is right. The second field will be used as the foreign key that establishes the relation. Thanks for pointing out the relevant documentation. I will create an issue for that.

If your issue is resolved after adding the second field, please close the issue.

**Comment by ranjan-purbey** [comment]
@seanemmer did you too encounter the issue mentioned here https://github.com/prisma/prisma/issues/2072#issuecomment-608632799 ?

**Comment by seanemmer** [comment]
@ranjan-purbey I did not encounter this, but I have not tested all of the client methods, the bug on this issue was from attempting to generate the client.
