### ISSUE TITLE
prisma not found for prisma2cli

### ISSUE THREAD

**Issue by Arieg419** [prisma/prisma#2047]
**package.json for prisma2 cli is wrong**

* https://github.com/prisma/prisma/blob/master/cli/prisma2/package.json

![image](https://user-images.githubusercontent.com/8246234/78178465-ae02f080-742d-11ea-83f6-f9a5d358228f.png)

files are thrown into a `dist` dir and not `build` dir. this causes an error bc the pkg json specifies the cmd for that script to be resolved in build/index.js

**Comment by janpio** [comment]
Can you please post the error your are getting so we can understand what is going wrong? Many people are currently using the CLI you are linking to, so it would be surprising if something would really be wrong here. But we are happy to investigate what is going on.

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/78535693-386e9a00-780a-11ea-9ae2-98bd462dcddf.png)


The entry point is indeed inside the build folder.

There is an additional step after typescript has compiled the CLI where we package the javascript via ncc: https://github.com/prisma/prisma/blob/9e7ca902599d3aa5cde40b6d661423e5bab8a072/cli/prisma2/package.json#L113

Cli executes without any error in the latest version.
