### ISSUE TITLE
Save database in memory instead of actual SQL server for Unit Testing?

### ISSUE THREAD

**Issue by ThalesC** [prisma/prisma#2050]
## Problem
I'm trying to test my application without the need to fetch data from an actual SQL server to improve speed.

## Solution
Saving to memory or any other similar solution would do the trick.

## Alternatives
Saving to memory as an array or something should be fine.

## Additional context
I'm not testing the interface that reaches the SQL database, just my interface between my front-end and the prisma-client.

**Comment by ranjan-purbey** [comment]
Why not use a sqlite db? It stores everything in a single file and you do not need to run a server separately

**Comment by ThalesC** [comment]
You got a good point, will the MySQL implementation already on prisma work for this? If so, should I access the file directly or will the `prisma-client` run any faster? I can’t test it right now, but I’ll do in a few hours, it’s 10:00 pm for me, maybe when it’s 09:00 am (11h from now) i can do this and give any feedback.

**Comment by ranjan-purbey** [comment]
An sqlite db is basically a collection of SQL statements and yes you can open the file directly. But I prefer to use a GUI tool like DBeaver to view the contents

**Comment by divyenduz** [comment]
@ThalesC Thank you for raising this, this is a very peculiar use case. What you are looking for is a MySQL stub. I am not sure if that belongs in Prisma land. 

Moreover in modern CI systems like Circle and Bitbucket, you should be able to get an instance of MySQL per CI run (via docker maybe?). 

You can also choose using SQLite as an option. Note that SQLite also has an "inmemory" option. However, we don't support that yet: https://github.com/prisma/prisma/issues/732

With this answer, I will close this issue. Please let me know if you do not agree and want to reopen this discussion by commenting here. 

Thank you 🙌
