### ISSUE TITLE
Multiplying Read/Writes for persistent PM2 services running longer than 3-5 days on MongoDB Serverless connections.

### ISSUE THREAD

**Issue by Swertin** [prisma/prisma#20518]
### Bug description

So, this is a bit bizarre, but my average reads per second for my MongoDB serverless instance is ~275 on a fresh start (rebooted server). However, every 24 hours, around 11pm-12am (for the server), the reads per second doubles and then holds for the next 24hours, until it doubles and holds again.

The server runs Nginx, PM2, and Prisma 4.14.0, on a NextTS stack with tRPC. It's also running on an expressTS microservice that cranks every 5 minutes.

### How to reproduce

1. Run application with ```pm2 start```
2. Let the application run for 24-48 hours
3. Watch the mongoDB serverless monitoring logs.
4. To reset, you need to reboot the server.

### Expected behavior

I expect the reads to stay consistent around the average of 275 per second.

### Prisma information

```
/**
 * Instantiates a single instance PrismaClient and save it on the global object.
 * @link https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices
 */
import { PrismaClient } from '@prisma/client'

const globalForPrisma = global as unknown as { prisma: PrismaClient }

export const prisma =
  globalForPrisma.prisma ||
  // new PrismaClient({
  //   log: ['query'],
  // }  
  new PrismaClient()

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma
```

### Environment & setup
- OS: Ubuntu 20.04.6 LTS
- Database: MongoDB Serverless
- Node.js version: v18.12.1
- Typescript version: v4.7.4

### Prisma Version

Application:
```
prisma                  : 4.14.1
@prisma/client          : 4.14.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.14.0-67.d9a4c5988f480fa576d43970d5a23641aa77bc9c
Default Engines Hash    : d9a4c5988f480fa576d43970d5a23641aa77bc9c
Studio                  : 0.484.0
```

Microservice:
```
prisma                  : 4.15.0
@prisma/client          : 4.15.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8fbc245156db7124f997f4cecdd8d1219e360944 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8fbc245156db7124f997f4cecdd8d1219e360944 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.15.0-28.8fbc245156db7124f997f4cecdd8d1219e360944
Default Engines Hash    : 8fbc245156db7124f997f4cecdd8d1219e360944
Studio                  : 0.484.0
```

**Comment by janpio** [comment]
What kind of traffic is your application handling? The level of that is constant through all this time?

**Comment by Swertin** [comment]
> What kind of traffic is your application handling? The level of that is constant through all this time?

Traffic is around 300 unique visitors a day, but around that time (midnight), activity should be or is near dead. The microservice cranks regardless every 5 minutes, and the table sizes don't move around too often. Nothing that would make sense as to a literal 2x in reads that sustains for the entire 24h until the next 2x in reads, which resets back to expected levels once the server is rebooted. Connections also increases by 3 every time that it multiplies and holds. Without understanding exactly what would dictate a new connection (NextJS Server worker, client, etc), I don't know if this is relevant.

**Comment by masterbater** [comment]
Whats your benchmark tool or is it from atlas?

**Comment by masterbater** [comment]
> > What kind of traffic is your application handling? The level of that is constant through all this time?
> 
> Traffic is around 300 unique visitors a day, but around that time (midnight), activity should be or is near dead. The microservice cranks regardless every 5 minutes, and the table sizes don't move around too often. Nothing that would make sense as to a literal 2x in reads that sustains for the entire 24h until the next 2x in reads, which resets back to expected levels once the server is rebooted. Connections also increases by 3 every time that it multiplies and holds. Without understanding exactly what would dictate a new connection (NextJS Server worker, client, etc), I don't know if this is relevant.

Is this really prisma relevant issue? You said in midnight there should be no traffic but your microservice still runs and doing some reads. It should be your microservice or you have continuous backup from atlas

**Comment by janpio** [comment]
If there is no traffic, and not scheduled jobs, then there should be no queries at all. Prisma does not run any queries by itself in general. 

> The microservice cranks regardless every 5 minutes

What does that mean, "crank"? What is triggering the microservice to do things if there is no traffic on the application?

**Comment by Swertin** [comment]
> If there is no traffic, and not scheduled jobs, then there should be no queries at all. Prisma does not run any queries by itself in general.
> 
> > The microservice cranks regardless every 5 minutes
> 
> What does that mean, "crank"? What is triggering the microservice to do things if there is no traffic on the application?

Every 5 minutes, there's a scheduled job to run through the database and perform actions. This increases the load and traffic to a normal, expected level of "burst." The average, over hours of this cranking every 5 minutes and the application running, is around 275-300 sustained reads per second, with a 5 minute granularity. There are periods of time where this sustains for 24-48 hours without issue.

The issue is that this average literally doubles at specific times, so that the average sustained becomes 600, and then 1200, and then 2400, reads per second.

However, after taking a look at MongoDB monitoring dashboard, I've realized that the timezone is not set to local time. Therefore, it appears as though the "duplication" events are closer, time-wise, with when I push updates to the code and rebuild.

With this information, it seems as though the "duplication" events are occurring when I run pm2 stop [ID] and pm2 start [ID]. For some reason, this doesn't seem to kill whatever worker thread/process that the prisma client is running on. I don't really know it is possible that prisma could have multiple "duplicated" clients running the same exact reads when only 1, not stale, client should be getting triggered.

**Comment by janpio** [comment]
Prisma only runs with your code. Each time you call `new PrismaClient()` you get a new instance. When the code stops running, Prisma also stops running.

This sounds a bit like the old "deployment" still running while a new one is added, is that possible somehow?
We often see similar problems in serverless deployments. A new version of the app is deployed, but the old one keeps running and keeps connections open. Fortunately there is usually no traffic routed to the old ones any more, but that seems to be different in your case as the scheduled job seems to keep going.

**Comment by Swertin** [comment]
Unfortunately, this isn’t a serverless application, only a serverless mongoDB collection. The application (and microservice) run on a hosted server, with Nginx and PM2. I also wanted to check and see if there were multiple processes that got duplicated on the hosted server (i.e. two next applications when running pm2 stop and start). However, there is only ever 1 nextJS process and 1 microservice process.

**Comment by SevInf** [comment]
@Swertin as @janpio, prisma does not run any queries unless you tell it to. 

Do you maybe know what kind of queries are send out to mongo instance in that time frame? Do they correspond to any queries in your application. The fact that it happens around 0pm also looks suspicious: could it be that some scheduling code somewhere does not handle 0 hour correctly? 

In any case, as @janpio mentioned, Prisma does not run any queries unless instructed to. I am sorry, but so far it does not seem like there is a problem with Prisma in this case, but rather that something within your application/deployment goes wrong and causes the spike.

If you still beleive Prisma is the culprit, we'd like to ask you to provide an isolated example that we could run, if possible. 

Thank you!

**Comment by Jolg42** [comment]
@Swertin Did you see the message from @SevInf? Without any activity on this issue, we would later close it as part of our issue process.

**Comment by millsp** [comment]
Hey @Swertin, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it.

**Comment by Swertin** [comment]
hey @Jolg42 @millsp, apologize for missing this, the issue in my case was due to a bug where tRPC would initialize our local cache logic on the frontend, as it was a singleton class. The solution was to separate the cache logic away from Next, and run it as an express API, then just call the API routes rather than directly calling the methods.
