### ISSUE TITLE
Mssql: delete a field with a default constraint fails

### ISSUE THREAD

**Issue by Giarry156** [prisma/prisma#20531]
### Bug description

When I try to delete a model field where I applied a default constraint, this creates a conflict. Others suggest modifying the migration file on StackOverflow, but it isn't a best practice. Is there any way to solve this?

Note: I tried on a Postgres DB, and this operation has no problem.

### How to reproduce

Prerequisites: You have to work on an mssql db.
1) Create a model with a field that has a default constraint.
	Ex.
	```
	model Person {
		id Int @id @default(autoincrement())
		name String?
		age Int? @default(50)
	}
	```
2) Create migration.
3) Delete the entire field.
Ex. In this case, delete `age Int? @default(50)`
4) Try to migrate again.

Note:
If you want to have the same issue by doing all the migrations, do this:
1) Create a model with a field that has a default constraint.
2) Create migration.
3) Delete the default constraint first.
4) Create migration.
5) Delete the field.
6) Create migration.
7) Try to pull not on the shadow database.

The error is the same but on the not shadow database.

### Expected behavior

Deleting a field with a default constraint must first create a drop constraint and then delete the field. Deleting a field with a default constraint.

### Prisma information

You can do it by yourself with a fake model. Try with the Person example.

### Environment & setup

- OS: Windows 11
- Database: SQL Server
- Node.js version: 16.15.0

### Prisma Version

```
prisma                  : 4.4.0
@prisma/client          : 5.0.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine f352a33b70356f46311da8b00d83386dd9f145d6 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli f352a33b70356f46311da8b00d83386dd9f145d6 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core f352a33b70356f46311da8b00d83386dd9f145d6 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt f352a33b70356f46311da8b00d83386dd9f145d6 (at ..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\prisma-fmt-windows.exe)  
Format Wasm             : @prisma/prisma-fmt-wasm 4.4.0-66.f352a33b70356f46311da8b00d83386dd9f145d6
Default Engines Hash    : f352a33b70356f46311da8b00d83386dd9f145d6
Studio                  : 0.474.0
```

**Comment by janpio** [comment]
What migration is being created in your step 4? Can you share the generated SQL?
What kind of error our failure are you getting when you execute that migration? Can you please share that?

I also notice that you are running Prisam Client 5.0.0 but Prisma CLI 4.4.0. Optimally those are the same version, so I suggest you upgrade your CLI with `npm install prisma@5.0.0` to make sure you are using a more recent version that matches your Prisma Client.

**Comment by SevInf** [comment]
Hey @Giarry156  ,

Did you get a chance to have a look at @janpio's comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by Druue** [comment]
Hey @Giarry156, 
 
As there's been no further responses or information provided, we'll be closing this issue now. If you have any further updates, please feel free to comment.
 
Cheers!
