### ISSUE TITLE
findUnique "where" clause allows every key of a model, not only unique keys.

### ISSUE THREAD

**Issue by sheraznabimirza** [prisma/prisma#20533]
The findUnique method now allows every key inside the model to be looked up instead of only the unique keys.

```
model Customer {
  customerId   Int           @id @default(autoincrement())
  userMasterId Int           @unique
  fullName     String
  phone        String
  userMaster   UserMaster    @relation(fields: [userMasterId], references: [userMasterId])
  userAddress  UserAddress[]
}
```

``` 
const customer = await this._dbService.customer.findUnique({
      where: {
        customerId: 1,
        fullName: 'david',
        phone: '22111'
      }
    })
```

Is this intentional or a known bug?

**Comment by Nickersoft** [comment]
Pretty sure this is a new feature of the [5.x release](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#filter-on-non-unique-fields-with-userwhereuniqueinput).

**Comment by janpio** [comment]
Indeed intentional and what was known as the `extendedWhereUnique` preview feature: 

> You must specify at least one unique field in your where statement [outside of boolean operators](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#boolean-operators-with-userwhereuniqueinput), and you can specify any number of additional unique and non-unique fields. You can use this to add filters to any operation that returns a single record.

https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#filter-on-non-unique-fields-with-userwhereuniqueinput

Is this causing problems for you in any way or was it just surprising?

**Comment by sheraznabimirza** [comment]
I was a little surprised to see non unique fields being suggested, considering that’s what we initially used findFirst for if we needed a combination of unique and non unique values. Thanks guys
