### ISSUE TITLE
TypeScript: Prisma.Decimal valid in 5.0.0 but not in 5.1.0, 5.1.1, 5.2.0-dev.12

### ISSUE THREAD

**Issue by raix** [prisma/prisma#20543]
### Bug description

Seems like theres a regression in 5.1.0 and 5.1.1 regarding runtime/index.js being removed vs mounting e.g. `Decimal` on `Prisma.Decimal`

### How to reproduce

```ts
import { Prisma } from "@prisma/client";

export const Test = Prisma.Decimal.clone({ precision: 2 });

// In 5.0.0 TypeScript is happy, in 5.1.0, 5.1.1 and 5.2.0-dev.12:
// Property 'Decimal' does not exist on type 'typeof Prisma'. ts(2339)
```

### Expected behavior

Code above should work as in 5.0.0 and accordingly to https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#removal-of-runtimeindexjs-from-generated-client

### Prisma information

-

### Environment & setup

- OS: macOS
- Database: Postgres
- Node.js version: v19.7.0

### Prisma Version

5.0.0
5.1.0
5.1.1
5.2.0-dev.12

**Comment by raix** [comment]
Might be an issue in emitting typings for the package, if adding `// @ts-nocheck` on the file it still seem to work

**Comment by SevInf** [comment]
Hi @raix!
I can not reproduce this issue. The code:

```ts
import { Prisma } from "@prisma/client";

const Foo = Prisma.Decimal.clone({ precision: 2 });
```

typechecks correctly for me for all versions you mentioned and works in runtime. 

Just to be sure: are you running `prisma generate` after updating? If that does not help or you are already doing it, could you provide a reporduction repo where we could see it happening?

Thank you!

**Comment by raix** [comment]
Thank you @SevInf for the fast response and sorry for waisting your time - running `prisma generate` fixed the issue 😊
