### ISSUE TITLE
Managable results

### ISSUE THREAD

**Issue by bwarre471** [prisma/prisma#20541]
I know, that request returns Objects, with table rows and coll's.

But we could add clause to request that it'll return smart objects, which could be editable.

```js
prisma.users.findOne(...).then((x)=>{
    x.email="new@mail.example"
    x.save()
})
```

This can work like wonders, if you have to e.g. fetch url from db, and then insert fetched data once you fetch url, or some other edgy use case.

```js
prisma.users.findOne(...).then((x)=>{
    x.articles.create({...data...})
    x.save()
})
```

**Comment by bwarre471** [comment]
The parameter for resulting fetches like this could be called return smart objects or so.

**Comment by janpio** [comment]
Is this similar to https://github.com/prisma/prisma/issues/17512, implementing an Active Record pattern?

**Comment by bwarre471** [comment]
Yes, it is simillar.

**Comment by janpio** [comment]
I'll close this issue then to simplify things here. If you want to add something, please comment over at #17512. Thanks! And thanks for opening this issue here originally.

**Comment by bwarre471** [comment]
Yes, it's completely active report. But find a way, that it automatically
saves debounced using proxy javascript contstruct, so it's autosaved.
