### ISSUE TITLE
Could not retrieve alloc::string::String from Value

### ISSUE THREAD

**Issue by jhd4tmr** [prisma/prisma#20596]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v18.16.0           | 
| Prisma CLI  | 5.1.1              | 
| Engine      | 6a3747c37ff169c90047725a05a6ef02e32ac97e| 

## Error
```
RustPanic: Error in Schema engine.
Reason: [/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mysql_common-0.29.2/src/value/convert/mod.rs:175:23] Could not retrieve alloc::string::String from Value

```

**Comment by Jolg42** [comment]
I'll close this and mention it in https://github.com/prisma/prisma/issues/19342
