### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by ivan-d-van** [prisma/prisma#20603]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.16.1           | 
| OS              | darwin-arm64       |
| Prisma Client   | 4.16.2             |
| Query Engine    | 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81|
| Database        | postgresql         |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /Users/ivan/sharpdev/chatbot-app/.env
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from /Users/ivan/sharpdev/chatbot-app/.env
prisma:client dirname /Users/ivan/sharpdev/chatbot-app/node_modules/.prisma/client
prisma:client relativePath ../../..
prisma:client cwd /Users/ivan/sharpdev/chatbot-app
prisma:client protocol graphql
prisma:client clientVersion 4.16.2
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath /Users/ivan/sharpdev/chatbot-app/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
export const GetLastUnprocessedReviews = (take: number, clientId?: string) => {
  return prisma.review.findMany({
    where: { param1: false, param2: { param3: true } },
    orderBy: {
      param4: "desc",
    },
    include: {
      listing: {
        select: {
****
        },
      },
      reservation: {
        select: { 
****
        },
      },
    },
    take,
  });
};

```

## Schema
```prisma
Not possible, it is under NDA
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by Jolg42** [comment]
Note: Could be related to https://github.com/prisma/prisma/issues/19968

@ivan-d-van are you using any preview features maybe?

**Comment by millsp** [comment]
@ivan-d-van  did you see the message from @Jolg42 ? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by SevInf** [comment]
Hey @ivan-d-van ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
