### ISSUE TITLE
Not able to perform query/Mutation to database usnig prisma beta version

### ISSUE THREAD

**Issue by SameerChorge94** [prisma/prisma#2061]
**Description**
I had updated the prisma to the beta version by uninstalling the earlier version from local project and globally installed. And tried deploying below datamodel with prisma beta version.

**Datamodel**
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  output   = "./generated/client"
}

model User {
    UserId              String   @default(cuid()) @id
    FirstName           String
    LastName            String?
    Address             String?
    Email               String?
    posts               Post[]
}

model Post {
    PostId              String   @default(cuid()) @id
    title               String
    User                User
}

```
After Migrating the database first of all As specified by datamodel, **model relationship does not get created** in empty database.
And then genarated the prisma client by prisma2 generate command.

**Expected Result:**
1. Model relationship should get created in database after migration
2. I should be able to perform query and mutation using generated prisma client

**Actual Result:**
1. Model relationship does not get created in database after migration
2. By using generated prisma client, not able to perform the query and mutation It returns the below error
```

Error occurred during query execution:
InterpretationError("Error for binding \'1\': DomainError(ConversionFailure(\"record identifier\", \"assimilated record identifier\"))")
    at PrismaClientFetcher.request (D:\Sameer_Chorge\Projects\Demos\Multi_tenant_pkg\prisma\generated\client\runtime\index.js:1:51485)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I performed the simple Mutation on post model :
```
const { PrismaClient } = require('./prisma/generated/client');
const prisma = new PrismaClient();
prisma.post.create({
    data: {
        title :"User1 First Post",
        User : {
            create: {
                FirstName : "user2"
            }
        }
    }
}).then((createdPost) => {
    console.log("createdPost");
    console.dir(createdPost);
    
}).catch((err) => {
    console.log("createPost Err");
    console.dir(err);
});
```

**System:**
@prisma/cli: ^2.0.0-beta.1
@prisma/client: ^2.0.0-beta.1

**Comment by janpio** [comment]
This datamodel is not valid (and our validation is unfortunately not telling you yet. This will be fixed soon.) Check the release notes for instructions and explanation: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.1

**Comment by SameerChorge94** [comment]
Thank You @janpio 
Closing this issue, After changing the datamodel as per suggested in release documents, I was able to perform the query and mutation without any problem.
