### ISSUE TITLE
`db pull` errored with `ERROR: prepared statement "s10" does not exist` when using a neon connection string with a pooled connection with pgbouncer=true

### ISSUE THREAD

**Issue by Cariaga** [prisma/prisma#20612]
### Bug description

```
 > [build 14/18] RUN npx prisma db pull:
1.179 Prisma schema loaded from prisma/schema.prisma
1.187 Datasource "db": PostgreSQL database "neondb", schema "public" at "someurl-pooler.aws.neon.tech"
1.208
1.210 - Introspecting based on datasource defined in prisma/schema.prisma
2.815 ✖ Introspecting based on datasource defined in prisma/schema.prisma
2.815
2.816 Error: db error: ERROR: prepared statement "s10" does not exist
2.816    0: sql_schema_connector::flavour::postgres::connection::describe_schema
2.816            with namespaces=None
2.816              at schema-engine/connectors/sql-schema-connector/src/flavour/postgres/connection.rs:48
2.816
```

the` Error: db error: ERROR: prepared statement "s10" does not exist` will sometimes be s10, s1,s3 etc... but it has the same error

### How to reproduce

`package.json`

3. Change '....'
`"prisma": "^5.1.0", to "prisma": "^5.1.1",
`
5. Run '....'
```
# Stage 1: Build stage
FROM node:bullseye-slim AS build

# Set the working directory to /app
WORKDIR /app

# Install NestJS CLI globally
RUN npm install -g @nestjs/cli

# Copy files
COPY package.json ./package.json 
COPY tsconfig.json ./tsconfig.json
COPY src ./src
COPY prisma ./prisma
COPY pnpm-lock.yaml ./pnpm-lock.yaml

RUN npx pnpm install 
# Install dependencies
RUN npm install -g pnpm


RUN pnpm install prisma --save-dev

#RUN pnpm install
RUN pnpm install --save-dev  @types/jest 

RUN npx prisma db pull 
RUN npx prisma generate

# Build the NestJS application
RUN nest build

# Set the global bin directory explicitly
RUN pnpm config set global-bin-dir /usr/local/bin



#optimize require 
#-p is intentional
RUN pnpm install -p


# Stage 2: Runtime stage
FROM node:bullseye-slim AS runtime

# Set the working directory to /app

# Copy the built application from the build stage
#COPY --from=build /app ./app

COPY --from=build /app/dist ./app/dist

COPY --from=build /app/node_modules ./app/node_modules
WORKDIR /app
ENV PORT 3000
EXPOSE $PORT

# Set the command to start the application
CMD ["node","./dist/main.js"] 
```

### Expected behavior

I expect it to be able to build,
originally it builds on 5.1.0 after upgrading to` 5.1.1` it does not build i went back to `5.0.0`  it also occurs in `5.1.0` when tried a short rollback, but i can make it work if i remove -pooler when using neon.tech so its direct connection the pooler would still be better though

### Prisma information

i'm using neon.tech and enabled pooler based on https://neon.tech/docs/connect/connection-pooling 
though direct connection is fine but bugged when -pooler is being used

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextIndex", "fullTextSearch"]
  binaryTargets   = ["native"]
  engineType      = "binary"
}

datasource db {
  provider = "postgresql"
  url      = "postgres://user:pass@someurl-pooler.ap/neondb?schema=public&connect_timeout=15&pool_timeout=15&pgbouncer=true"
}
```

### Environment & setup

- OS: Windows 11, Debian
- Database: PostgreSQL,Neon.Tech
- Node.js version: `20.5.0`

### Prisma Version

```
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 6a3747c37ff169c90047725a05a6ef02e32ac97e (at ..\..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 6a3747c37ff169c90047725a05a6ef02e32ac97e (at ..\..\..\..\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\schema-engine-windows.exe) 
Schema Wasm             : @prisma/prisma-schema-wasm 5.1.1-1.6a3747c37ff169c90047725a05a6ef02e32ac97e
Default Engines Hash    : 6a3747c37ff169c90047725a05a6ef02e32ac97e
Studio                  : 0.492.0
Preview Features        : fullTextIndex, fullTextSearch
```

**Comment by Cariaga** [comment]
Update it seams not specific to the version but prisma and neon.tech having issue connecting in general repeatedly calling 
`build on docker build -t myapp .` or `just npx prisma db pull` will repeatedly fail but succeed at some point

**Comment by Jolg42** [comment]
When using the Prisma CLI, a direct connection to the database should be used (without pgbouncer)
Could you try that?

```
datasource db {
  provider = "postgresql"
  url           =  env("DATABASE_URL")
  directUrl = env("DIRECT_DATABASE_URL")
}
```
Environment variables would look like this (The pooled and direct connection string can be found in Neon's UI by checking or unchecking the "Pooled connection" checkbox)
```
DATABASE_URL="postgres://user:pass@something-pooler.someregion.aws.neon.tech/neondb?schema=public&connect_timeout=15&pool_timeout=15&pgbouncer=true"
DIRECT_DATABASE_URL="postgres://user:pass@something.someregion.aws.neon.tech/neondb?schema=public&connect_timeout=15&pool_timeout=15"
```

See docs: https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#external-connection-poolers

Note: for security reasons, using an environment variable is recommended.

**Comment by Jolg42** [comment]
Unrelated: You can probably remove these now, or is there a special reason to have this set? 
```
  binaryTargets   = ["native"]
  engineType      = "binary"
```

**Comment by Cariaga** [comment]
> ```prisma
>   binaryTargets   = ["native"]
>   engineType      = "binary"
> ```

originally I had this  inside binaryTargets due to incompatibilities against platforms such as circleCI and gcp i had it on "prisma": "^4.12.0",
 ```
 "debian-openssl-1.1.x",
  "debian-openssl-3.0.x",
```

after switching to two stage dockerfile i.e the build stage and runtime stage
after that i upgraded prisma to 5.x.x
```
  binaryTargets   = ["native"]
  engineType      = "binary"
```
but I haven't tested without it.

**Comment by Jolg42** [comment]
@Cariaga Could you confirm that adding a `directUrl` like mentioned before solved your issue?

**Comment by Cariaga** [comment]
> @Cariaga Could you confirm that adding a `directUrl` like mentioned before solved your issue?

yes i as of now everything is working fine after changing.. issue can be closed thank you.
