### ISSUE TITLE
Connection with AWS IAM Authentication always returns invalid credentials

### ISSUE THREAD

**Issue by MohamedAkl1** [prisma/prisma#20620]
### Bug description

I am trying to connect Prisma with AWS RDS, My company is using AWS IAM Authentication to connect to the RDS. I create the authentication token with [RDS.signer](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS/Signer.html) and then escape the special characters as mentioned in the docs. 

The unescaped authentication token itself is working correctly when using mysql in terminal with `mysql --host=$RDS_HOST --port=$RDS_PORT --ssl-ca=$SSL_PATH --enable-cleartext-plugin --user=$RDS_USER --password=${TOKEN}`. Also the previous command works when unescaping the authentication token after escaping it. 

The authentication always fails even when attempting to try different tokens always yields the same results.
Attached is a screenshot of the error.
<img width="1152" alt="Screenshot 2023-08-09 at 14 44 00" src="https://github.com/prisma/prisma/assets/19689243/9e94d3b7-dc90-475b-9120-7bab93948974">

### Expected behavior

Prisma should connect to RDS and pull data from it.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = "mysql://${username}:${encodeURIComponent(token)}@${hostname}:${port}"
}```


### Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: 20.5.0


### Prisma Version

```
5.1.1
```

**Comment by Jolg42** [comment]
@MohamedAkl1 Thanks for this issue, it looks like a duplicate of https://github.com/prisma/prisma/issues/10304

Though in your case, the error message does not mention "Unknown authentication plugin" 🤔 

Did you execute `prisma db pull` here to get this error message?

**Comment by MohamedAkl1** [comment]
Hello @Jolg42 thanks for your response, yes i execute `prisma db pull` to get this error.

**Comment by MohamedAkl1** [comment]
Closing this because I realized I was missing a ssl certificate path and now the error is the same as #10304. So this is now a duplocate

**Comment by Jolg42** [comment]
(closed as duplicate)
