### ISSUE TITLE
migrate deploy failed by adding new field

### ISSUE THREAD

**Issue by mxq7854687** [prisma/prisma#20638]
Hi Prisma Team! The following command just crashed.

## Command

`db push`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin-arm64       | 
| Node        | v18.16.1           | 
| Prisma CLI  | 4.13.0             | 
| Engine      | 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a| 

## Error
```
Error: Error in migration engine.
Reason: [schema-engine/sql-schema-describer/src/mysql.rs:295:21] called `Result::unwrap()` on an `Err` value: "Getting create_options from Resultrow ResultRow { columns: [\"table_name\", \"create_options\", \"table_comment\"], values: [Bytes(Some([85, 115, 101, 114, 80, 114, 111, 102, 105, 108, 101])), Text(None), Text(Some(\"Table 'userprofile' is marked as crashed and should be repaired\"))] } as String failed"

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by Jolg42** [comment]
@mxq7854687 `Table 'userprofile' is marked as crashed and should be repaired\` makes me think that there is something broken in your database now.

Which version of MySQL are you using? It could be linked to the version you are using.

Also, we would need more details to be able to reproduce this
- What was your schema before
- What's the change that triggered the crash
- any detail you might find relevant

**Comment by Jolg42** [comment]
See 
- https://stackoverflow.com/questions/4357270/table-is-marked-as-crashed-and-should-be-repaired
- https://www.stellarinfo.com/blog/fix-mysql-is-marked-as-crashed-and-should-be-repaired/

For how to repair the database.
Note from the previous article
>Low disk space could be a reason for MySQL table being marked as “crashed”. When you have low space on your disk, some of the tables in the database may get crashed. It usually happens when you get space issues on the part of the hard disk where your database is stored.

**Comment by millsp** [comment]
@mxq7854687  did you see the message from @Jolg42 ? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by mxq7854687** [comment]
I am sorry for the late reply on this issue. The suggest here did help on my issue. Thank you so much on the response.
