### ISSUE TITLE
Prisma doesn't recover `Timed out` error - Planetscale + Fly.io

### ISSUE THREAD

**Issue by typytypytypy** [prisma/prisma#20631]
### Bug description

I'm running a remix app on Fly.io, DB is planetscale.  When I run load tests (K6) it ramps up usage and I'm not surprised to encounter an occasional error, but the prisma client doens't seem to recover after it hits this:

```Timed out fetching a new connection from the connection pool```

I have to restart the machines before anything will work. 

Is this a configuration issue? 

### How to reproduce

Happy to provide steps, all I am doing is a load test with K6 on a remix app

```
stages: [
        { duration: "50s", target: 10 },
        { duration: "50s", target: 20 },
        { duration: "50s", target: 40 },
        { duration: "50s", target: 60 },
        { duration: "50s", target: 80 },
        { duration: "50s", target: 0 },
      ],
```

### Expected behavior

I expect this is a transient error, one that will not inhibit a web-server from continuing to serve requests. 

### Prisma information

```
//schema.prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}
```

```
//prisma client
import { PrismaClient } from "@prisma/client";

let db: PrismaClient;

declare global {
  var __db: PrismaClient | undefined;
}

if (process.env.NODE_ENV === "production") {
  db = new PrismaClient();
} else {
  if (!global.__db) {
    global.__db = new PrismaClient();
  }
  db = global.__db;
}

export { db };
```

### Environment & setup

- OS: Debian
- Database: PlanetScale
- Node.js version: 18

### Prisma Version

```
5.0.0
```

**Comment by janpio** [comment]
Any further information that lets us experimentally reproduce this would be welcome.

**Comment by typytypytypy** [comment]
I will work on a repo for reproducing. I can say that I have adjusted the connection_limit and pool_timeout to try to resolve the error, neither of which seems to make much impact.

**Comment by janpio** [comment]
Did you have time for that repro @typytypytypy?

**Comment by millsp** [comment]
@typytypytypy  did you see the message from @janpio ? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by SevInf** [comment]
Hey @typytypytypy,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
