### ISSUE TITLE
Schemas with incomplete @relation annotations should be rejected during Client generation

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#2064]
## Bug description

The following schema is considered valid, when in fact it isn't.

## How to reproduce

Try this schema:

```
model User {
  id    Int    @id
  posts Post[]
}

model Post {
  id     Int  @id
  author User @relation(references: [id])
}
```

Running `prisma2 generate` works without errors.

This leads to issues when you run a query against this schema. This is invalid, since the `@relation` annotation does not have a `field` attribute, and there is no scalar field in `Post` to define the `author` relation on.

## Expected behavior

`prisma generate` (& the VSCode plugin) should reject this schema, saying that the `@relation` annotation is incorrectly defined: it needs a `field` attribute.

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- Prisma version: 
```
@prisma/cli          : 2.0.0-alpha.1024
Current platform     : darwin
Query Engine         : prisma 15b42f2c499c65576f47fa77108e39d86645242b
Migration Engine     : migration-engine-cli 15b42f2c499c65576f47fa77108e39d86645242b
Introspection Engine : introspection-core 15b42f2c499c65576f47fa77108e39d86645242b
```
- Node.js version: 13.10.1

**Comment by mavilein** [comment]
This is fixed in: https://github.com/prisma/prisma-engines/pull/624
