### ISSUE TITLE
`@relation` annotation's `field` attribute should not be able to accept scalar lists

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#2065]
## Bug description

Scalar lists are not allowed inside an `@relation` annotation's `field` attribute as far as I know, but our validators (in the VSCode plugin & in `prisma2 generate`) do not error out.

## How to reproduce

Use this schema:
```
model User {
  id     Int    @id
  postId Int[]
  posts  Post[] @relation(fields: [postId], references: [id])
}

model Post {
  id   Int   @id
  user User?
}
```

## Expected behavior

The VSCode extension and `prisma2 generate` should warn me that scalar lists are not allowed in `@relation.fields`, since they are not supposed to work (even in Postgres)

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- VSCode extension version: 0.30.0
- Prisma version:
```
@prisma/cli          : 2.0.0-alpha.1024
Current platform     : darwin
Query Engine         : prisma 15b42f2c499c65576f47fa77108e39d86645242b
Migration Engine     : migration-engine-cli 15b42f2c499c65576f47fa77108e39d86645242b
Introspection Engine : introspection-core 15b42f2c499c65576f47fa77108e39d86645242b
```
- Node.js version: v13.10.1

**Comment by mavilein** [comment]
fixed in: https://github.com/prisma/prisma-engines/pull/673
