### ISSUE TITLE
Oops, an unexpected error occurred! unreachable

### ISSUE THREAD

**Issue by Mukeshkumar9787** [prisma/prisma#20669]
Hi Prisma Team! The following command just crashed.

## Command

`migrate dev --schema [redacted]`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.16.1           | 
| Prisma CLI  | 4.10.0             | 
| Engine      | ca7fcef713137fa11029d519a9780db130cca91d| 

## Error
```
Error: unreachable
```

**Comment by janpio** [comment]
Duplicate of https://github.com/prisma/prisma/issues/20668
