### ISSUE TITLE
Prisma `migrate dev`: `Error: not reachable`

### ISSUE THREAD

**Issue by Mukeshkumar9787** [prisma/prisma#20668]
Hi Prisma Team! The following command just crashed.

## Command

`migrate dev --schema [redacted]`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.16.1           | 
| Prisma CLI  | 4.10.0             | 
| Engine      | ca7fcef713137fa11029d519a9780db130cca91d| 

## Error
```
Error: unreachable
```

**Comment by Jolg42** [comment]
@Mukeshkumar9787 Could you provide a reproduction for this? 

Also, did you try using `4.16.2` or the latest version `5.1.1` to see if that's already fixed maybe?

**Comment by millsp** [comment]
@Mukeshkumar9787  did you see the message from @Jolg42 ? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by SevInf** [comment]
Hey @Mukeshkumar9787 ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
