### ISSUE TITLE
Missing Relationship Generation for Join Tables During Prisma DB Pull

### ISSUE THREAD

**Issue by jhd4tmr** [prisma/prisma#20679]
## Problem

When performing a ```db pull``` operation with Prisma to synchronize the database schema with the defined data models, it appears that the relationships involving join tables are not being generated as expected.

## Suggested solution

Example
```prisma
model posts {
  id               BigInt             @id(map: "Post_pkey") @default(autoincrement())
  posts_tags       posts_tags[]
  @@schema("public")
}

model posts_tags {
  post_id    BigInt
  tag_id     BigInt
  posts      posts    @relation(fields: [post_id], references: [id], onDelete: Cascade, onUpdate: NoAction)
  tags       tags     @relation(fields: [tag_id], references: [id], onDelete: Cascade, onUpdate: NoAction)

  @@id([post_id, tag_id])
  @@schema("public")
}

model tags {
  id                            BigInt       @id @default(autoincrement())
  posts_tags                    posts_tags[]
  @@schema("public")
}
```

better into

```prisma
model posts {
  id               BigInt             @id(map: "Post_pkey") @default(autoincrement())
  posts_tags       posts_tags[]
  tags             tags[] @relation("posts_tags")
  @@schema("public")
}

model posts_tags {
  post_id    BigInt
  tag_id     BigInt
  posts      posts    @relation(fields: [post_id], references: [id], onDelete: Cascade, onUpdate: NoAction)
  tags       tags     @relation(fields: [tag_id], references: [id], onDelete: Cascade, onUpdate: NoAction)

  @@id([post_id, tag_id])
  @@schema("public")
}

model tags {
  id                            BigInt       @id @default(autoincrement())
  posts_tags                    posts_tags[]
  posts                         posts[] @relation("posts_tags")
  @@schema("public")
}
```

**Comment by jhd4tmr** [comment]
@Jolg42 

- Prisma 5.1.1
- PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

I attempted the simplest join table logic, but it didn't work as expected. The relationship between the 'tags' and 'posts' tables from the following table structure wasn't automatically established as expected. The result after running 'db pull' is also provided below. This issue is unrelated to the '-force' option; the scheme.prisma was empty during my testing.
```
create table
  public.posts (
    id BIGSERIAL PRIMARY KEY
  ) tablespace pg_default;

create table
  public.tags (
    id BIGSERIAL PRIMARY KEY
  ) tablespace pg_default;

create table
  public.posts_tags (
    post_id bigint not null,
    tag_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint posts_tags_pkey primary key (post_id, tag_id),
    constraint posts_tags_tag_id_fkey foreign key (tag_id) references tags (id) on delete cascade,
    constraint posts_tags_post_id_fkey foreign key (post_id) references posts (id) on delete cascade
  ) tablespace pg_default;
```

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model posts {
  id         BigInt       @id @default(autoincrement())
  posts_tags posts_tags[]
}

model posts_tags {
  post_id    BigInt
  tag_id     BigInt
  created_at DateTime @default(now()) @db.Timestamptz(6)
  posts      posts    @relation(fields: [post_id], references: [id], onDelete: Cascade, onUpdate: NoAction)
  tags       tags     @relation(fields: [tag_id], references: [id], onDelete: Cascade, onUpdate: NoAction)

  @@id([post_id, tag_id])
}

model tags {
  id         BigInt       @id @default(autoincrement())
  posts_tags posts_tags[]
}
```

**Comment by janpio** [comment]
@jhd4tmr I don't think that is a supported feature in Prisma.

Prisma supports explicit many to many relations between `Foo` and `Bar`, where there is a manual "join table" in between as in your example, but then there is not direct connection between `Foo` and `Bar` in the schema: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#explicit-many-to-many-relations 

And it supports implicit many to many relations where the join table has to follow very specific rules to be picked up: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#implicit-many-to-many-relations In that case the join table is not rendered in your Prisma schema and it is harder to add additional data like the `created_at` you want in your `posts_tags`.

I think there are multiple feature requests for making the implicit many to many relations more flexible, or offer a more flexible DX for explicit many to many under this label: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+relations%22+sort%3Aupdated-desc

Do you agree?
If so, I think this is not a valid bug report and can be closed.

**Comment by jhd4tmr** [comment]
@janpio 
I know. Will you consider generating the join table relationship in scheme.prisma according to composite pk during db pull? In other words, there is a join table specification for db pull. Otherwise, it is very troublesome to manually modify scheme.prisma to clarify the join table relationship every time.

**Comment by janpio** [comment]
Implicit many to many relations need the join tables to be with these conventions: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#conventions-for-relation-tables-in-implicit-m-n-relations Or are you asking for something else?
