### ISSUE TITLE
@migrate annotation

### ISSUE THREAD

**Issue by joarwilk** [prisma/prisma#207]
Let's say I have this schema
```
type Item {
  id
  title
}
```

But I would like it to look like this instead
```
type Item {
  id
  name
}
```

Just straight renaming the field would crash every application out there using the schema, but maybe something like this would come in handy:
```
type Item {
  id
  title @deprecated @migrate("name")
  name
}
```
Now using `title` will issue a deprecation warning (assuming graph.cool supports that?), and both `name` and `title` will point to the same data source. Then, later on when I know that all clients that refer to the `title` field are out of production use, I can remove the `title` field.

Not a super urgent thing at all, but I think it would be a nice tool to have.

**Comment by schickling** [comment]
I really like this idea and think it's a great primitive to have available helping you to more easily evolve the database schema of your backend.

Would be great if this feature would get a few more eyeballs 👀  and someone could propose a concrete spec. Implementing this feature should be quite straightforward.
