### ISSUE TITLE
Nextjs 13 + AWS Amplify + Supabase: `Timed out fetching a new connection from the connection pool.`

### ISSUE THREAD

**Issue by chris-mashmash** [prisma/prisma#20711]
### Bug description

Our production setup continually hits this issue where we get 
`Timed out fetching a new connection from the connection pool.`

This usually happens after a few days of everything running fine, but then everything just suddenly breaks and doesn't recover. We have some important webhooks that updates with the status of long running jobs which stop working. There are numerous people facing the same issue: [17057](https://github.com/prisma/prisma/issues/17057) [20631](https://github.com/prisma/prisma/issues/20631) [20111](https://github.com/prisma/prisma/issues/20111)

Our setup:
Nextjs 13 + Graphql Yoga,
Prisma 5.1.1
AWS Amplify Hosting
Supabase

We have checked with Supabase support and they do not see any issue with availability or overloading with the number of connections. In fact, we were previously using pgbouncer and the max number of connections used was 2 at any given point. 

### How to reproduce

Really not sure how to reproduce this error.

I think if you launch a Nextjs 13 setup on AWS Amplify this error will eventually show up.

### Prisma information

```ts
import { PrismaClient } from '@prisma/client'
import { isDevelop } from "./next"

declare global {
  // allow global `var` declarations
  // eslint-disable-next-line no-var
  var prisma: PrismaClient | undefined
}

export const prisma =
  global.prisma ||
  new PrismaClient({
    log: isDevelop() ? ['query', 'info', 'warn', 'error'] : ['info', 'error'],
  })

if (isDevelop()) global.prisma = prisma
```

### Environment & setup

- OS: Amazon Linux
- Database: Postgres 15.1.0.88
- Node.js version: node 16

### Prisma Version

```
5.1.1
```

**Comment by janpio** [comment]
`Timed out fetching a new connection from the connection pool.` happens to every user in the case that their connection pool is exhausted and can not handle the volume of queries that it is being asked to handle - or something goes wrong with that code.

Can you help us by creating a reproduction of your problem in a standalone project that you can put on GitHub? We would happily deploy that project to see if we can get the same behavior you are seeing. Right now we are lacking any information on how to do that though. Thanks.

**Comment by tgensol** [comment]
@janpio Do you see any way to catch this error so that we can implement a retry policy (with backoff, for reconnecting the client and retrying the query ?) ? I have the same issue with `Server has closed the connection` thanks

**Comment by janpio** [comment]
Either in your application yourself of course, or both [middlewares](https://www.prisma.io/docs/concepts/components/prisma-client/middleware) and [Client Extensions](https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions) should be able to catch a failing query and execute it again.

Note that this does not actually make too much sense in the case that @chris-mashmash reported, as the pool will probably still be overloaded. In case of the error message you posted @tgensol, `Server has closed the connection`, it might work better though.

By the way, do you maybe want to open a separate issue for your problem and describe what is going on? We want to understand these cases better and hopefully solve some of them. Thanks!

**Comment by AugustDev** [comment]
I can reproduce the issue. Application works fine locally and Vercel, but fails on Amplify. Did you manage to solve @chris-mashmash ?

**Comment by janpio** [comment]
Can you share some more information so we can possibly reproduce @AugustDev ? Thanks.

**Comment by Jolg42** [comment]
@AugustDev Did you see the message from @janpio? Without more information to reproduce this, we would later close it as part of our issue process.

**Comment by millsp** [comment]
Hey @chris-mashmash, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it.
