### ISSUE TITLE
High CPU usage when using generated Types

### ISSUE THREAD

**Issue by Sashkan** [prisma/prisma#20722]
### Bug description

I'm using the generated types from `@prisma-client` in a form in a Next.js app.

The form is initialised as per `react-hook-form` documentation:

```tsx
	type Inputs = {
		example: string;
 		exampleRequired: string;
	};

	const {
		register,
		handleSubmit,
		watch,
		formState: { errors },
	} = useForm<Inputs>();
```
This works just fine, CPU usage is almost 0

### How to reproduce

If we replace our `Input` type by a type generated by Prisma, as seen in [the documentation](https://www.prisma.io/docs/concepts/components/prisma-client/crud#create-a-single-record-using-generated-types), CPU usage skyrockets.

```tsx
	import { Prisma } from '@prisma/client'

	const {
		register,
		handleSubmit,
		watch,
		formState: { errors },
	} = useForm<Prisma.CompanyCreateInput>();
```

Using the `code --status` command displays a 99% CPU usage, coming from `.vscode/extensions/ms-vscode.vscode-typescript-next-5.3.20230816/node_modules/typescript/lib/tsserver.js`

When switching back to initial code, a TS server restart is needed to lower down CPU usage.

### Expected behavior

I'd simply like to use the generated types in my form

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id        Int       @id @default(autoincrement())
  email     String    @unique
  name      String?
  createdAt DateTime  @default(now())
  role      String    @default("user")
  updatedAt DateTime  @updatedAt
  Account   Account[]
  Company   Company?  @relation(fields: [companyId], references: [id])
  companyId Int?
}

model Account {
  id         Int      @id @default(autoincrement())
  userId     Int
  user       User     @relation(fields: [userId], references: [id])
  provider   String
  providerId String
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
}

model Company {
  id        Int      @id @default(autoincrement())
  name      String
  description String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  User      User[]
}
```
I'm not using any query for now

### Environment & setup

Running on Mac M1, with node `18.17.0`

### Prisma Version

```
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/.pnpm/@prisma+engines@5.1.1/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/.pnpm/@prisma+engines@5.1.1/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.1.1-1.6a3747c37ff169c90047725a05a6ef02e32ac97e
Default Engines Hash    : 6a3747c37ff169c90047725a05a6ef02e32ac97e
Studio                  : 0.492.0
```

**Comment by SevInf** [comment]
Hi @Sashkan.
From your message it appears that nightly TS build is used in your case:

>ms-vscode.vscode-typescript-next-5.3.20230816

Do you also get the same problem on stable TS version? If not, I'd suggest to report the problem to TS team instead.

**Comment by Sashkan** [comment]
Hi @SevInf , thanks for the quick answer,

I tried both with stable TS (5.1.3) and Nightly, the issue occurred all the same

**Comment by Sashkan** [comment]
## Noteworthy information:
It only happens with the types linked to the `Prisma` object:
```ts
import { Book } from '@prisma/client' // this won't reduce performances

import { Prisma } from '@prisma/client'
const myBookinput: Prisma.BookCreateInput = ... // this will immediately cause CPU usage to rise

```

**Comment by Sashkan** [comment]
@SevInf Unfortunately I can not share the repo, but I managed to dig a bit more: it only happens when used to type the `useForm` hook

```tsx
const {
    register,
    handleSubmit,
  } = useForm<Prisma.CompanyCreateForm>(); // this will cause high CPU usage

const input: Prisma.CompanyCreateForm = {
	...
} // this won't

```

**Comment by janpio** [comment]
https://react-hook-form.com/docs/useform?

**Comment by Sashkan** [comment]
Thanks all, I finally found the culprit.

This was caused by a recursive resolution, due to a poorly configured NX monorepo.

If anyone ever faces this issue, make sure that you do not duplicate imports throughout your NX apps `tsconfig.json` files
