### ISSUE TITLE
Client throws when Model has One-to-Many Self Relation

### ISSUE THREAD

**Issue by five07** [prisma/prisma#2072]
## Bug description

Client throws when Model has One-to-Many Self Relation

## How to reproduce

1. `git clone https://github.com/five07/prisma-self-relation.git`
2. `cd prisma-self-relation`
3. `npm install`
4. `npm run dev`

## Expected behavior

An object should be created when the parent connection is made

## Prisma information

@prisma/cli          : 2.0.0-beta.1
Current platform     : darwin
Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203
Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203
Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203

## Environment & setup

- OS: Mac OS
- Database: SQLite
- v12.16.0

**Comment by five07** [comment]
I wanted to confirm that this did work in preview025. 

1. Update package.json to use preview025
2. Remove fields & references from schema
3. `rm -r prisma/migrations  prisma/data.db`
4. `npx prisma2 generate`
5. `npx prisma2 migrate save --experimental`
6. `npx prisma2 migrate up --experimental`
7. `npm run dev`

Migrate creates the "parentOrg" column as expected and records are created correctly.

<img width="676" alt="Screen Shot 2020-04-02 at 8 39 10 PM" src="https://user-images.githubusercontent.com/612469/78322160-c3a61200-7522-11ea-8031-4a910eb464dd.png">

I also observed that in beta.1, migrate created `parentID` as a Unique index on the database, but the schema does not require that and would cause additional issues if more that one child was connected to a parent.

BTW, thanks for all of the hard work! Despite the noise right now, the community appreciates your diligence.

**Comment by pguilbault** [comment]
> I also observed that in beta.1, migrate created parentID as a Unique index on the database, but the schema does not require that and would cause additional issues if more that one child was connected to a parent.

I can confirm this.

`npx prisma2 migrate save --experimental` creates a SQL statement in order to create a unique index as follows (taken from the migration's Readme) : 
```
CREATE UNIQUE INDEX "Location_parent" ON "Location"("parent")
```

Which throws an error when doing `migrate up` because I already have many rows linked to the same parent.

My One-to-Many self relation : 
```
model Location {
  id        String      @id @default(cuid())
  parent    Location?   @relation("LocationToLocation_parent", fields:[parentId], references: [id])
  parentId  String?     @map("parent")
  children  Location[]  @relation("LocationToLocation_parent")
}
```

**Comment by janpio** [comment]
(Beta 1 has both `prisma` and `prisma2` commands 👍 )

**Comment by five07** [comment]
@ranjan-purbey - thanks for the tip. I removed the "references" arg from the child field and it works as expected so long as I manually remove the UNIQUE INDEX.

Only outstanding issue: Migrate adds erroneous UNIQUE INDEX for One-to-Many Self Relations.

**Comment by ranjan-purbey** [comment]
@pguilbault You are right, I can confirm this. Instead of adding a foreign key index, migrate adds a unique key, which is obviously wrong. Can you please create a new issue here https://www.github.com/prisma/migrate ?

**Comment by nickreynke** [comment]
Can confirm this. Here's my schema just for reference:

```
model WorkspaceTask {
  id                String           @default(cuid()) @id
  title             String

  parentTask        WorkspaceTask?   @relation(name: "WorkspaceTaskToSubTask", fields: [parentTaskId], references: [id])
  parentTaskId      String?
  subTasks          WorkspaceTask[]  @relation(name: "WorkspaceTaskToSubTask")

  @@index([title])
}
```

Which generates following database steps:

```
CREATE TABLE "public"."WorkspaceTask" (
    "id" text  NOT NULL ,
    "parentTaskId" text   ,
    "title" text  NOT NULL ,
    PRIMARY KEY ("id")
) 

CREATE UNIQUE INDEX "WorkspaceTask_parentTaskId" ON "public"."WorkspaceTask"("parentTaskId")

ALTER TABLE "public"."WorkspaceTask" ADD FOREIGN KEY ("parentTaskId")REFERENCES "public"."WorkspaceTask"("id") ON DELETE SET NULL  ON UPDATE CASCADE
```

Where the `CREATE UNIQUE INDEX` for `parentTaskId` is not wanted.
