### ISSUE TITLE
Add model info to PrismaClientKnownRequestError

### ISSUE THREAD

**Issue by EizFeren** [prisma/prisma#20724]
## Problem

I have global exception filter for NestJS, and it's catcher only have error instance of `PrismaClientKnownRequestError`. This execption filter needs somehow to know, what model is related to this error, e.g. to provide custom error message, related to model name.

Real example - trying to create user, but user with provided email exists in database. Exception filter uses error code (`P2002`) to detect this is unique constraint error or something else, but it still doesn't know what model it's related for.

## Suggested solution

Add model name to error metadata, e.g.:
```js
{
  meta: {
    model: 'User',
    target: [
      'email'
    ]
  }
}
```
## Alternatives

Imho best approach will be attaching custom metadata for any query, e.g.:
```js
prismaClient.user.create({
  data: {
    ...
  },
  customMetadata: {
    ... // any data engineer wants to attach
  },
});
```
Idk how it's possible and/or type safe, but this grants far more flexibility than current usage.

**Comment by SevInf** [comment]
Hi @EizFeren.
In meantime, instead of deprecated middleware, you can use query extension:

```

const prisma = new PrismaClient().$extends({
  query: {
    $allModels: {
      async $allOperations({ query, args, model }) {
        try {
          return await query(args)
        } catch (error) {
           if (error instanceof PrismaClientKnownError) {
              error.meta.model = model
           }
           throw error;
        }
    }
  }
})
```

**Comment by AikoRamalho** [comment]
Hey!

I would love to work on it.

**Comment by SevInf** [comment]
@AikoRamalho sure. [This place in our code](https://github.com/prisma/prisma/blob/main/packages/client/src/runtime/RequestHandler.ts#L213) would probably be a good starting point. You can find our dev environment setup instructions [here](https://github.com/prisma/prisma/blob/main/CONTRIBUTING.md) and testing instructions [here](https://github.com/prisma/prisma/blob/main/TESTING.md).
Looking forward to your contribution and let me know if you need help at any point.
