### ISSUE TITLE
Prisma Accelerate - Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by prashantchothani** [prisma/prisma#20743]
### Bug description

I am using Prisma Client with Accelerate in Nextjs 13.4.12 with Mongodb for Edge Runtime but getting null response with the following error:

```
- warn ./node_modules/@prisma/extension-accelerate/dist/esm/node-fetch.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@prisma/extension-accelerate/dist/esm/node-fetch.js
./node_modules/@prisma/extension-accelerate/dist/esm/index.js
./app/api/home/route.js
./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fhome%2Froute&page=%2Fapi%2Fhome%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fhome%2Froute.js&appDir=C%3A%5CGithubRepos%5Ctravelxp-b2c-service%5Capp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=C%3A%5CGithubRepos%5Ctravelxp-b2c-service&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/api/home/route.js?__next_edge_ssr_entry__       
- warn ./node_modules/@prisma/extension-accelerate/dist/esm/node-fetch.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@prisma/extension-accelerate/dist/esm/node-fetch.js
./node_modules/@prisma/extension-accelerate/dist/esm/index.js
./app/api/home/route.js
./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fhome%2Froute&page=%2Fapi%2Fhome%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fhome%2Froute.js&appDir=C%3A%5CGithubRepos%5Ctravelxp-b2c-service%5Capp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=C%3A%5CGithubRepos%5Ctravelxp-b2c-service&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/api/home/route.js?__next_edge_ssr_entry__       
- wait compiling /favicon.ico/route (client and server)...
- warn ./node_modules/@prisma/extension-accelerate/dist/esm/node-fetch.js
Critical dependency: the request of a dependency is an expression
```

### Prisma information

```
datasource db {
  provider = "mongodb"
  url      = env("PRISMA_URI")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    String  @id @default(auto()) @map("_id") @db.ObjectId
  email String  @unique
  name  String?
  mobile String?
}

```

```
export const runtime = 'edge'

import { PrismaClient } from '@prisma/client/edge';
import { withAccelerate } from '@prisma/extension-accelerate';

const prismaWithAccelerate = new PrismaClient().$extends(withAccelerate());

 const user = await prismaWithAccelerate.user.findUnique({
            where: {
                email: "xxxxxx@gmail.com",
              },
  });

```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
"@prisma/client": "^5.1.1",
"@prisma/extension-accelerate": "^0.5.0",
Operating System : Windows 11
Node Version : 20.2
```

**Comment by Compositr** [comment]
Experiencing the same issue with Postgres

**Comment by jkomyno** [comment]
Hey @prashantchothani, which Node.js version and OS are you using? Could you please add them to the `Environment & Setup` section of your issue? Thanks.

**Comment by prashantchothani** [comment]
> Hey @prashantchothani, which Node.js version and OS are you using? Could you please add them to the `Environment & Setup` section of your issue? Thanks.

@jkomyno Done. It is Windows 11 and Node Version is 20.2.

**Comment by prashantchothani** [comment]
Apologies forgot to add the following and corrected in the above as well :

`export const runtime = 'edge'`

**Comment by itsmitul** [comment]
Experiencing the same issue on nodejs v16

**Comment by rtbenfield** [comment]
Hi everyone 👋🏻  I just wanted to share an update that we're investigating this and will follow-up soon. Thank you for the additional runtime information, that will be super helpful in reproducing this.

**Comment by samtgarson** [comment]
If runtime info is helpful, I can add that I'm also getting this on a different setup:

- MacOS 13.3
- Node 18
- prisma 5.2.0
- in regular Server Actions in Next.js App Dir (not edge runtime)

```
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../node_modules/@prisma/extension-accelerate/dist/esm/node-fetch.js
../node_modules/@prisma/extension-accelerate/dist/esm/index.js
../packages/database/index.ts
...
```

**Comment by rtbenfield** [comment]
Hi again 👋🏻  We just deployed version 0.6.0 of `@prisma/extension-accelerate` 🚀 This version should resolve the Next.js build warning.

This was caused by our fallback use of `node:https` to support Node 16. Generally, Accelerate will prefer to use the global `fetch` function from the runtime. Node 16 doesn't have `fetch` available without an experimental flag though, so if we don't find `fetch` we will make a wrapper for `node:https` to look like fetch (rather than pull in an entire library for the implementation, we can get away with a minimal version). However, some bundlers fail when they detect the `node:https` import during static analysis and don't consider that it is conditional and likely unused. We used a workaround to hide the import from the bundlers, but then Next.js starting detecting it as an import of an arbitrary string. 

We corrected this by using `package.json#exports` to provide separate entrypoints for Node and non-Node runtimes. This eliminated the need to conditionally import `node:https` since we can do so safely within the Node-only entrypoint.

**Comment by samtgarson** [comment]
This has fixed it for me. Thanks 🙌

**Comment by collinversluis** [comment]
This solved my issue as well with mysql! Thanks @rtbenfield

**Comment by rtbenfield** [comment]
Since you're all here trying Accelerate 🙂  I'll mention again that we really appreciate your feedback; good and bad. If you have a moment, drop us a note in [Discord](https://discord.com/channels/937751382725886062/1118229675668410368) or [Slack](https://prisma.slack.com/archives/C04KTN0V2Q0) and let us know what you think. I'd love to hear more about what you're building and how we can help 🤝

**Comment by prashantchothani** [comment]
@rtbenfield This solved for me as well for Nextjs, Node 20.2, Node 18 and on Vercel as well.

**Comment by diwasdhungana** [comment]
> Hi again 👋🏻 We just deployed version 0.6.0 of `@prisma/extension-accelerate` 🚀 This version should resolve the Next.js build warning.
> 
> This was caused by our fallback use of `node:https` to support Node 16. Generally, Accelerate will prefer to use the global `fetch` function from the runtime. Node 16 doesn't have `fetch` available without an experimental flag though, so if we don't find `fetch` we will make a wrapper for `node:https` to look like fetch (rather than pull in an entire library for the implementation, we can get away with a minimal version). However, some bundlers fail when they detect the `node:https` import during static analysis and don't consider that it is conditional and likely unused. We used a workaround to hide the import from the bundlers, but then Next.js starting detecting it as an import of an arbitrary string.
> 
> We corrected this by using `package.json#exports` to provide separate entrypoints for Node and non-Node runtimes. This eliminated the need to conditionally import `node:https` since we can do so safely within the Node-only entrypoint.

i could only grasp half of the things mentioned above. maybe it's a simple fix but i have this error. 
this error is actually produced in Middleware.js file while checking user Credentials on edge. i am using prismaClient imported from prisma/client/edge then extends withAcclerate(). this error persists without the /edge part as well.

Environment : {
  node : v20.5.0 
  "@prisma/client": "^5.2.0" 
  "@prisma/extension-accelerate": "^0.6.0" 
   "next": "13.3.1" }

Error : 
error - node:https
Module build failed: UnhandledSchemeError: Reading from "node:https" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:https
./node_modules/@prisma/extension-accelerate/dist/esm/node-fetch.js
./node_modules/@prisma/extension-accelerate/dist/esm/entry.node.js
./utils/prisma.js

**Comment by janpio** [comment]
@diwasdhungana If you don't have the `Critical dependency: the request of a dependency is an expression` error, then this is unrelated and it would be better for you to open a new issue with a full description. Thanks.

**Comment by jessaleks** [comment]
I have the same error.  "next": "14.0.3", "@prisma/client": "^5.6.0", "@prisma/extension-accelerate": "^0.6.2", "@prisma/instrumentation": "^4.16.2".

MacOS 14, Node 18.19.0.

**Comment by jessaleks** [comment]
├── @axiomhq/axiom-node@0.12.0
├── @babel/core@7.23.5
├── @emnapi/runtime@0.44.0 extraneous
├── @headlessui/react@1.7.17
├── @heroicons/react@2.0.18
├── @jsdevtools/rehype-toc@3.0.2
├── @ladle/react@2.17.2
├── @mdi/svg@7.3.67
├── @next/bundle-analyzer@14.0.3
├── @next/eslint-plugin-next@13.5.6
├── @playwright/test@1.40.1
├── @prisma/client@5.6.0
├── @prisma/extension-accelerate@0.6.2
├── @prisma/instrumentation@4.16.2
├── @radix-ui/react-avatar@1.0.4
├── @radix-ui/react-dialog@1.0.5
├── @sentry/nextjs@7.84.0
├── @tailwindcss/aspect-ratio@0.4.2
├── @tailwindcss/typography@0.5.9
├── @testing-library/dom@9.3.3
├── @testing-library/jest-dom@5.17.0
├── @testing-library/react@14.1.2
├── @testing-library/user-event@14.5.1
├── @types/node@20.10.1
├── @types/react-dom@18.2.6
├── @types/react@18.2.14
├── @typescript-eslint/eslint-plugin@6.13.1
├── @typescript-eslint/parser@6.13.1
├── @uidotdev/usehooks@2.4.1
├── @vercel/analytics@1.1.1
├── autoprefixer@10.4.14
├── babel-eslint@10.1.0
├── babel-loader@9.1.3
├── class-variance-authority@0.7.0
├── clsx@2.0.0
├── cors@2.8.5
├── critters@0.0.20
├── cssnano-preset-lite@3.0.0
├── cssnano@6.0.1
├── cypress@13.0.0
├── dotenv@16.3.1
├── encoding@0.1.13
├── eslint-config-next@13.4.4
├── eslint@8.54.0
├── framer-motion@10.16.9
├── graphql-request@6.1.0
├── graphql@16.8.1
├── hastscript@7.2.0
├── jest-environment-jsdom@29.7.0
├── jest@29.5.0
├── logrocket-react@6.0.3
├── logrocket@7.0.0
├── lru-cache@5.1.1 extraneous
├── lucide-react@0.294.0
├── meilisearch@0.36.0
├── next@14.0.3
├── node-ts@6.0.1
├── postcss-load-config@4.0.1
├── postcss@8.4.31
├── prettier@2.7.1
├── prisma@5.6.0
├── prop-types@15.8.1
├── react-dom@18.2.0
├── react-intersection-observer@9.5.3
├── react-is@18.2.0
├── react-schemaorg@2.0.0
├── react-share@5.0.3
├── react-solid-state@0.27.3
├── react-wrap-balancer@1.1.0
├── react@18.2.0
├── redis@4.6.11
├── rehype-autolink-headings@6.1.1
├── rehype-raw@6.1.1
├── rehype-sanitize@5.0.1
├── rehype-slug@5.1.0
├── rehype-stringify@9.0.4
├── remark-gfm@3.0.1
├── remark-parse@10.0.2
├── remark-rehype@10.1.0
├── request@2.88.2
├── rss-parser@3.13.0
├── sanitize@2.1.2
├── schema-dts@1.1.2
├── server-only@0.0.1
├── sharp@0.33.0
├── start-server-and-test@2.0.3
├── tailwind-merge@2.0.0
├── tailwindcss-animate@1.0.7
├── tailwindcss@3.3.1
├── ts-jest@29.1.1
├── ts-node@10.9.1
├── tslib@2.5.3
├── typescript@5.3.2
├── unified@10.1.2
├── validator@13.11.0
├── virtua@0.17.4
├── vitest@0.32.4
├── winston@3.11.0
└── zod@3.22.4
