### ISSUE TITLE
@default(now()) and @updatedAt during introspection

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma#2075]
Hi. The syntax for defining default dates as given here (https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/prisma-schema-file) are `@default(now())` and `@updatedAt`

But when you have this in the schema file and you introspect the db, they change to `@default(dbgenerated())` - shouldn't this be preserved during introspection as well?

Not sure if this was intended.

**Comment by janpio** [comment]
No it is not.

Can you please share your schema and the SQL that was created based on that, maybe also the second_ introspected schema? Thanks.

**Comment by tvvignesh** [comment]
@janpio Shared with you in slack. Hope its ok.

**Comment by tvvignesh** [comment]
PS: I used migrate to apply the schema and introspect to get back the schema which gave this issue.

**Comment by janpio** [comment]
Internally persisted at https://github.com/prisma/prisma2-private/issues/37 for reproduction

**Comment by pantharshit00** [comment]
I can confirm this.

**Comment by divyenduz** [comment]
Note: This happens when default is a specific date like 

```sql
CREATE TABLE `post` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP DEFAULT '2020-07-17 10:08:23'
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

```prisma
model post {
  id Int @id @default(autoincrement())
  created_at DateTime @default(degenerated())
}
```

When the default is `CURRENT_TIMESTAMP`, the introspection yields @default(now())

```sql
CREATE TABLE `post` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

```prisma
model post {
  id Int @id @default(autoincrement())
  created_at DateTime @default(now())
}
```

So, this is probably not an introspection bug but a mismatch between schema and database SQL. In this case, it looks like the database had the default from a Prisma migrate migration, which creates a default (can you please confirm @tvvignesh) and that was a migrate bug: https://github.com/prisma/migrate/issues/291 (we should reconfirm this as this issue is pretty recent)

**Comment by tvvignesh** [comment]
@divyenduz Haven't tried the latest builds of prisma, but when this was reported, it was a greenfield deployment. So, I applied the schema with prisma setting `@default(now())` in the schema file, it updated the DB appropriately, then I introspected the same DB and I got  `@default(dbgenerated())`

So, in this case, there was no manual intervention. Prisma applied it as `@default(now())` and introspects it as `@default(dbgenerated())` which was the issue here.

Hope it clarifies.

**Comment by janpio** [comment]
@tvvignesh To recap: You started a new project and wrote a schema with `@default(now())` and `@updatedAt`, then you introspected that database again and both were gone from the resulting schema - correct? Anything else that might be relevant for us to reproduce this?

**Comment by tvvignesh** [comment]
> @tvvignesh To recap: You started a new project and wrote a schema with `@default(now())` and `@updatedAt`, then you introspected that database again and both were gone from the resulting schema - correct? Anything else that might be relevant for us to reproduce this?

@janpio Exactly! The migrations were applied using prisma migrate and introspection was also done using prisma. The database in use was postgres. Had checked the db using pgadmin as well and was able to see the same change there as well.

PS: Long time since this happened. Not sure if this will be the case with new builds as well.

**Comment by janpio** [comment]
Yep, we will confirm with the schema you provided back then and see if there is still anything we need to do.

**Comment by divyenduz** [comment]
We tested this internally and the issue with `@default(now())` is not reproducible anymore. However, `@updatedAt` is still reproduced. Tracking that here https://github.com/prisma/prisma/issues/3335
