### ISSUE TITLE
Do not force to use prisma:// protocol

### ISSUE THREAD

**Issue by emircanerkul** [prisma/prisma#20764]
Cloudflare workers now support TCP https://blog.cloudflare.com/workers-tcp-socket-api-connect-databases

https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/

We no longer need to use data proxy.

<img width="858" alt="image" src="https://github.com/prisma/prisma/assets/11430795/7c5a8353-a347-4534-ab49-6575f7597cc0">

**Comment by janpio** [comment]
Unfortunately, it's not that easy. 

Cloudflare's TCP sockets are only available in Node.js land, not to our Rust drivers that Prisma's Query Engine uses to talk to databases by default. Hence we need to change much more than to skip forcing the `prisma://` protocol. Concretely we plan to support using Node-based database drivers like `pg`, which already has support for Cloudflare's socket implementation.

This is being tracked here: https://github.com/prisma/prisma/issues/19488 Please leave a 👍 on that issue to indicate your interest. Thanks.
