### ISSUE TITLE
Support MongoDB Plugins (for Secure encryption)

### ISSUE THREAD

**Issue by Ahmadre** [prisma/prisma#20761]
## Problem

I wanted to use field level encryption with: https://www.npmjs.com/package/mongoose-field-encryption

But I cannot find any solution with prisma to load plugins for my schema.

## Suggested solution

I should be possible to apply plugins for mongo.

**Comment by janpio** [comment]
Prisma does not use Mongoose under the hood, so it is technically impossible for us to apply any Mongoose plugins. Sorry.
