### ISSUE TITLE
Why my prisma client always tries to connect to 127.0.0.1 in docker?

### ISSUE THREAD

**Issue by rantiev** [prisma/prisma#20772]
### Discussed in https://github.com/prisma/prisma/discussions/20765

<div type='discussions-op-text'>

<sup>Originally posted by **rantiev** August 21, 2023</sup>
### Question

This is docker config I have 
https://stackoverflow.com/questions/76940883/nestjs-cant-connect-to-mongo-while-running-in-docker 

Two containers are there: mongo container, and nestjs container. 

Nest.js (I assume prisma client by saying it) always tries to connect to 127.0.0.1 whatever I put to my scheme.prisma and env varialbes in .env file, or env variables in docker configs. 

I always regenerate prisma client with 'pnpm exec prisma generate'

### Expected behavior (optional)

Nestjs prisma client respect database url config IP address.

### Information about Prisma Schema, Client Queries and Environment (optional)
```prisma
<!-- Paste your Prisma schema below. Do not include your database credentials when sharing your Prisma schema! -->
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = "mongodb://root:prisma@mongo:27018/bookmeon?authSource=admin"
}

enum OrderStatus {
  pending
  confirmed
  completed
  cancelled
}
...
```

```ts
// Add any relevant Prisma Client queries here
```

- OS: 
- Database: 
- Node.js version: 

- Run `prisma -v` to see your Prisma version and paste it
</div>

**Comment by jkomyno** [comment]
Hi @rantiev, this looks like a Docker configuration issue rather than a Prisma issue, but here is something that hopefully will help fixing the issue you're facing:
- Prisma only uses the database URL from a local `.env` file when `url = env("...")` is used in the `datasource db` block of the `schema.prisma` file. Based on your Docker config, you may want to replace your `datasource db` block with:
  ```prisma
  datasource db {
    provider = "mongodb"
    url           = env("DATABASE_URL")
  }
  ```

- Docker-compose doesn't enable network visibility by default between its services, so you may want to define [custom networks ](https://docs.docker.com/compose/networking/#specify-custom-networks) in your docker-compose.yaml file

**Comment by janpio** [comment]
See ongoing discussion: https://github.com/prisma/prisma/discussions/20765#discussion-5541995

**Comment by rantiev** [comment]
Thanks @jkomyno I will try both suggestions. But I think earlier I had `env("DATABASE_URL")` and as It didn't work started to use real URL. 

On other hand I thought that by defaultt docker-compose shares network between all services in one docker-compose config (as I understood from their docs, you are saying that I understood them wrong). Also tried already using networks, but probably I added them wrong way. 

Will anyway try again everythign.

**Comment by rantiev** [comment]
Looks like Prisma client substitutes `mongo:27018` with `127.0.0.1:27018` but if I do ping my docker mongo from another container as usual I get address kinda `172.x.x.x`

So looks like client takes wrong IP always and as a result nestjs can't connect to it using generated client.
