### ISSUE TITLE
Suspected memory leak in Lambda function after upgrading from 4.10.1

### ISSUE THREAD

**Issue by fshuman-a** [prisma/prisma#20799]
### Bug description

We recently came across `VT13001: [BUG] in scatter query` whilst trying to run the db:push and other similar commands. Based on [this](https://github.com/prisma/prisma/issues/19645) ticket, we decided to upgrade our prisma version. The issue disappeared after upgrade but we started noticing our lambda functions crashing. From the lambda function logs: 
```
Error: Runtime exited with error: signal: killed Runtime.ExitError
REPORT RequestId: xx Duration: 6174.19 ms Billed Duration: 6175 ms Memory Size: 850 MB Max Memory Used: 850 MB 
```
The lambda function has always been configured to use 512 MB so we decided to upgrade to 850 MB in case the upgrade required more memory. But that didn't help.

Pls see below for more info. We're kind of in a limbo now; we cannot make any more schema changes due to the **VT13001** bug above and we cannot upgrade to v5 due the lambda crashes. We do **not** need to upgrade to v5. If we have a fix for the **VT13001** bug, we're happy to stay on v4.10.1 for now.

Thank you.

### How to reproduce

Upgrade to 4.15.0, 5.0.0 or 5.1.1 and create tables similar to the ones provided below.

### Expected behavior

We expect it to work like it did in v4.10.1.

### Prisma information

```
generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["filteredRelationCount"]
    binaryTargets   = ["rhel-openssl-1.0.x", "native"]
}

datasource db {
    provider     = "mysql"
    url          = env("DATABASE_URL")
    relationMode = "prisma"
}
```
Not all queries/tables cause it to crash. Some queries are ok but others just crash. An example of such table:

```
model Foo {
    id                                   Int                                 @id @default(autoincrement())
    uid                                  String                              @unique @db.Char(26)
    name                                 String                              @db.VarChar(100)
    createdDate                          DateTime                            @default(now())
    deleted                              Boolean                             @default(false)
    deletedDate                          DateTime?
    tableAMapping                        TableAMapping[]
    tableBMapping                        TableBMapping[]
    owner                                User                                @relation(fields: [ownerId], references: [id], onDelete: Cascade)
    ownerId                              Int
    fooType                              FooType                             @relation(fields: [fooTypeId], references: [id])
    fooTypeId                            Int
    anotherTableCredentials              anotherTableCredentials?            @relation(fields: [anotherTableCredentialsId], references: [id])
    anotherTableCredentialsId            Int?
    ## MORE FIELDS: Another 19 fields similar to anotherTableCredentials and anotherTableCredentialsId

    @@index([name])
    @@index([ownerId])
    @@index([fooTypeId])
    @@index([anotherTableCredentialsId])
    ## MORE INDEX: corresponding to the 19 fields mentioned above
    
    @@index([uid])
}

```

A query such as: 
```
await prisma.foo.findMany({
    where: {
        fooType: {
            uid: request.fooTypeUid,
        },
        ownerId: user.id,
        deleted: false,
        name,
    },
}),
```
or even:
```
await prisma.foo.count({
    where: {
        ownerId: user.id,
        deleted: false,
    },
}),
```

would fail.

Some other queries that use `findMany` seem to be ok.

### Environment & setup

- OS: Amazon Linux 2 x86_64
- Database: MySQL
- Node.js version: 16.18

### Prisma Version

It affects multiple versions **4.15.0, 5.0.0 & 5.1.1**. 
```
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.1.1-1.6a3747c37ff169c90047725a05a6ef02e32ac97e
Default Engines Hash    : 6a3747c37ff169c90047725a05a6ef02e32ac97e
Studio                  : 0.492.0
```

**Comment by janpio** [comment]
> and we cannot upgrade to v5 due the lambda crashes

Is that specific to Prisma 5.x or also affect `4.15.0` as you wrote in other places?

Does this 

> `Error: Runtime exited with error: signal: killed Runtime.ExitError`

Does this happen on the first function invocation?
If so, what are the queries it executes?
If not, how many invocations does it take to run into the problem?

> relationMode = "prisma"

I assume you are using PlanetScale as your database?
If so, can you still try to remove this line from your schema and see if the function then works successfully? (Note that this could lead to data inconsistencies, so best make sure to use this on a copy of your database instead of your real one)

**Comment by fshuman-a** [comment]
> Is that specific to Prisma 5.x or also affect 4.15.0 as you wrote in other places?

It happens in 4.15.0 too.

> I assume you are using PlanetScale as your database?

Yes.

I tried removing the `relationMode` and I get the following error:
```
Error: VT10001: foreign key constraints are not allowed
   0: sql_schema_connector::apply_migration::migration_step
           with step=AddForeignKey { foreign_key_id: ForeignKeyId(0) }
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:21
   1: sql_schema_connector::apply_migration::apply_migration
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:10
   2: schema_core::state::SchemaPush
             at schema-engine/core/src/state.rs:436
```
I noticed from [this](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/relation-mode#how-to-set-the-relation-mode-in-your-prisma-schema) page that the `relationMode` is necessary if I'm using MySQL on PlanetScale.

---

It doesn't matter when it's run or how many times. It still fails. An example of such a query (affects multiple tables not just Foo):
```
await prisma.foo.findMany({
    where: {
        fooType: {
            uid: request.fooTypeUid,
        },
        ownerId: user.id,
        deleted: false,
        name,
    },
    select: {
        id: true,
     },
}),
```
and the corresponding db query:
```
  {
    query: 'SELECT `ourDatabase`.`Foo`.`id` FROM `ourDatabase`.`Foo` WHERE ((`ourDatabase`.`Foo`.`id`) IN (SELECT `t0`.`id` FROM `ourDatabase`.`Foo` AS `t0` INNER JOIN `ourDatabase`.`FooType` AS `j0` ON (`j0`.`id`) = (`t0`.`connectionTypeId`) WHERE (`j0`.`uid` = ? AND `t0`.`id` IS NOT NULL)) AND `ourDatabase`.`Foo`.`ownerId` = ? AND `ourDatabase`.`Foo`.`deleted` = ? AND `ourDatabase`.`Foo`.`name` = ?)',
    params: '["01H8GRXMMS0XB2QJRFR3QDYZ7G",7,false,"SomeAwesomeName"]',
    duration: 82
  },
```

The crash seems to happen before the query is logged so even with `DEBUG = ['*']`, I don't see the query. It doesn't even appear in the PlanetScale insights (where I can see queries run against the database). The above query was obtained when running the same process in 4.10.1.

Thank you.

**Comment by janpio** [comment]
> I tried removing the `relationMode` and I get the following error:
> 
> ```
> Error: VT10001: foreign key constraints are not allowed
>    0: sql_schema_connector::apply_migration::migration_step
>            with step=AddForeignKey { foreign_key_id: ForeignKeyId(0) }
>              at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:21
>    1: sql_schema_connector::apply_migration::apply_migration
>              at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:10
>    2: schema_core::state::SchemaPush
>              at schema-engine/core/src/state.rs:436
> ```
> 
> I noticed from [this](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/relation-mode#how-to-set-the-relation-mode-in-your-prisma-schema) page that the `relationMode` is necessary if I'm using MySQL on PlanetScale.

Sorry I was unclear here. You would need to migrate the database when `relationMode = prisma` is present (so it creates it in a way that PlanetScale likes), and then remove the `relationMode` when you run your app so it will not try to run additional queries.

---

> It doesn't matter when it's run or how many times. It still fails. [...] The crash seems to happen before the query is logged so even with DEBUG = ['*'], I don't see the query.

Just to make sure I understand: 
You deploy your Lambda function, then send 1 request and instead of returning the result of that simple query, it kills the function invocation with `signal: killed Runtime.ExitError ... Memory Size: 850 MB Max Memory Used: 850 MB ` after a few seconds because it runs out of memory!? That would be wild.

**Comment by fshuman-a** [comment]
We have an ongoing scheduled process that runs a query (every minute) against a different table. Even though it also uses `findMany`, it doesn't cause any crashes. Normally, this scheduled process would have run once before I attempt to test the queries that fail.

I just noticed that some of the debug message didn't appear earlier but I see them now (might have misconfigured earlier):

```
2023-08-23T08:52:37.889Z prisma:client:libraryEngine library started

<First query to get the user is run successfully>

<After the first query, I log the process.memoryUsage(): rss 91.8 MB, heapTotal 37.95 MB, heapUsed 20.25 MB, external 3.55 MB & arrayBuffers 0.05 MB >

2023-08-23T08:52:37.930Z prisma:client Prisma Client call:
2023-08-23T08:52:37.930Z prisma:client Generated request:
2023 -08 - 23T08: 52: 37.930Z prisma:client {
    "modelName": "Foo",
    "action": "findMany",
    "query": {
    "arguments": {
    "where": {
    "fooType": {
    "uid": "01H8GRXMMS0XB2QJRFR3QDYZ7G"
    },
    "ownerId": 1,
    "deleted": false,
    "name": "SomeAwesomeName"
    }
    },
    "selection": {
    "id": true
    }
    }
}
2023-08-23T08:52:37.930Z prisma:client:libraryEngine sending request, this.libraryStarted: true
```

It is very strange indeed. I'm going to do the migrate on a test database and I'll let you know how it goes.

**Comment by fshuman-a** [comment]
@janpio - I have run `migrate dev` (I had to create a separate shadow database). The migration folder was created and I can see the migration sql. If I just kick off the tests (for those failed queries), the lambda function crashes.
Have I missed a step perhaps?

Thank you.

**Comment by janpio** [comment]
You can also use `db push` to skip the shadow database and the migration folder - it will directly create the SQL for your schema in the database. If you did remove `relationMode = prisma` before you `prisam generate` for the Client you deployed to talk to that database, it just means that my theory is debunked and it had no influence.

Can you maybe shared your Prisma schema and the relevant, failing code with me (in a way that I can easily deploy)? I have access to Planetscale databases and Lambda, so might be able to reproduce this easily and directly - which means I can poke myself, instead of having to ask you via GitHub. (If schema is nothing for public eyes, I am my first name @prisma.io)

**Comment by fshuman-a** [comment]
Thanks @janpio - I will drop you a test email then share the rest of the details there.

**Comment by janpio** [comment]
Internal note: Reproduction is attempted via https://github.com/prisma/20799 + email conversation.

**Comment by janpio** [comment]
Can you elaborate on "same bug" please? What exactly is happening for you? Is it reproducible?

**Comment by janpio** [comment]
I can reproduce the problem you describe @fshuman-a with the data you provided:

```
2023-08-25T20:21:49.637Z	02dec914-d647-4174-aa4e-3921e9631c09	INFO	Before connection.findMany process.memoryUsage() in MB:  { rss: 122, heapUsed: 20, heapTotal: 55, arrayBuffers: 0, external: 1 }
RequestId: 02dec914-d647-4174-aa4e-3921e9631c09 Error: Runtime exited with error: signal: killed
Runtime.ExitError
END RequestId: 02dec914-d647-4174-aa4e-3921e9631c09
REPORT RequestId: 02dec914-d647-4174-aa4e-3921e9631c09	Duration: 24633.40 ms	Billed Duration: 24634 ms	Memory Size: 1280 MB	Max Memory Used: 1280 MB	Init Duration: 230.72 ms	
```

Okay...

**Comment by janpio** [comment]
And I can also reproduce this isolated and locally with the query you identified:

```
gitpod /workspace/20799/simple-test (main) $ node repro.js 
Before connection.findMany process.memoryUsage() in MB:  { rss: 50, heapUsed: 9, heapTotal: 12, arrayBuffers: 0, external: 1 }
After connection.findMany process.memoryUsage() in MB:  { rss: 129, heapUsed: 21, heapTotal: 57, arrayBuffers: 0, external: 1 }

gitpod /workspace/20799/simple-test (main) $ npm install prisma@5.2.0 @prisma/client@5.2.0

changed 4 packages, and audited 28 packages in 4s

gitpod /workspace/20799/simple-test (main) $ node repro.js 
Before connection.findMany process.memoryUsage() in MB:  { rss: 48, heapUsed: 7, heapTotal: 9, arrayBuffers: 0, external: 1 }
After connection.findMany process.memoryUsage() in MB:  { rss: 1666, heapUsed: 8, heapTotal: 9, arrayBuffers: 0, external: 1 }
```

Something in your schema really throws newer Prisma versions off. We'll look into that obviously.

**Comment by janpio** [comment]
I could isolate the problem: Somehow the many `@unique` columns in the model `Connection` lead to this problem.

**Comment by janpio** [comment]
This is now available as `prisma@5.3.0-dev.32` and `@prisma/client@5.3.0-dev.32`, and can be tested locally. Optimally you (and @mattkindy) can confirm that this solves the problem, and then this will be shipped as part of 5.3.0 on September 12th.

**Comment by mattkindy** [comment]
> This is now available as `prisma@5.3.0-dev.32` and `@prisma/client@5.3.0-dev.32`, and can be tested locally. Optimally you (and @mattkindy) can confirm that this solves the problem, and then this will be shipped as part of 5.3.0 on September 12th.

Unfortunately, we are not *yet* on 5.x, so might be difficult for us to verify at this time.

**Comment by fshuman-a** [comment]
Thanks @janpio - we will test this today or latest Monday and update you.

**Comment by fshuman-a** [comment]
Hi @janpio - I no longer see the memory leak in this new version. Thanks for your help. We look forward to the release 👍
