### ISSUE TITLE
Internal error: Attempted to serialize empty result.

### ISSUE THREAD

**Issue by fajarnurprasetyo** [prisma/prisma#20796]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.16.1           | 
| OS              | debian-openssl-3.0.x|
| Prisma Client   | 5.1.1              |
| Query Engine    | 6a3747c37ff169c90047725a05a6ef02e32ac97e|
| Database        | mongodb            |

## Logs
```
prisma:client:libraryEngine library started
```

## Client Snippet
```ts
  const data = JSON.parse(req.body);
  let { id, ...update } = data;

  const district = await prisma.district.upsert({
    where: { id },
    create: { ...update, id },
    update: { ...update, updatedAt: new Date() },
  });
```

## Schema
```prisma
model District {
  id        Int     @id @map("_id")
  name      String  @unique
  centralId Int?
  address   String?
  lng       Float?
  lat       Float?

  leaderId    String?
  coLeaderId  String?
  secretaryId String?
  treasurerId String?

  createdAt DateTime  @default(now())
  updatedAt DateTime?
}
```

**Comment by janpio** [comment]
Does this `upsert` always crash this way?
Was this a case where it executed the `create` or the `update` case?
What was `req.body`?

**Comment by millsp** [comment]
@fajarnurprasetyo  did you see the message from @janpio and @jkomyno? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by SevInf** [comment]
Hey @fajarnurprasetyo ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
