### ISSUE TITLE
Migration Crash

### ISSUE THREAD

**Issue by cmklundt** [prisma/prisma#20806]
Hi Prisma Team! The following command just crashed.

## Command

`migrate dev`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v20.5.0            | 
| Prisma CLI  | 5.0.0              | 
| Engine      | 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584| 

## Error
```
RustPanic: RuntimeError: panicked at 'internal error: entered unreachable code: No unsupported field should reach that path', query-engine/schema/src/build/input_types/mod.rs:26:40
```

**Comment by Jolg42** [comment]
@cmklundt Did you see the message from @jkomyno? Without any activity on this issue, we would later close it as part of our issue process.

**Comment by millsp** [comment]
Hey @cmklundt, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it.
