### ISSUE TITLE
Bad cli output

### ISSUE THREAD

**Issue by yantakus** [prisma/prisma#2081]
When I put .env file in the wrong directory (`/` instead or `/prisma`) I got the following error when running `npx prisma migrate up --experimental`:

```
Error: Unknown database type dummy:
```

My db connection looks like this:
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

When I moved .env file to `/prisma` directory the error went away.

P.S. Also, one more tiny issue, here: https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project#prerequisites the link `connection URL` is broken.

**Comment by janpio** [comment]
Ok, seems the missing environment variable leads to a not optimal error message.

**Comment by mavilein** [comment]
@timsuchanek : Can you tell me which rpcs `migrate up` is calling exactly?

**Comment by mavilein** [comment]
Internal Note: It seems that an RPC is called where env var errors are ignored. Internally we insert for `dummy://url` for for urls than can not be resolved.

**Comment by timsuchanek** [comment]
These are the RPCs we're calling:

## `migrate save`
1. `listMigrations`
2. `inferMigrationSteps`

## `migrate up`
1. `listMigrations`
2. `calculateDatabaseSteps`
3. `applyMigration`

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
