### ISSUE TITLE
Extends Type

### ISSUE THREAD

**Issue by Fi1osof** [prisma/prisma#2083]
# Feature Request

**What feature are you missing?**
Extend generated types in server/src/schema.graphql

**How could this feature look like in detail? Tradeoffs?**
Example in apollo: https://www.apollographql.com/docs/graphql-tools/generate-schema.html#extend-types
```
const typeDefs = [`
  schema {
    query: Query
  }
  type Query {
    bars: [Bar]!
  }
  type Bar {
    id
  }
  `, `
  type Foo {
    id: String!
  }
  extend type Query {
    foos: [Foo]!
  }
`]
```

**Comment by marktani** [comment]
I see no reason why this wouldn't work. Have you tried it?

**Comment by Fi1osof** [comment]
Yes, i tried and it does not work. No errors, just no extends.

**Comment by marktani** [comment]
Can you share a minimal setup that showcases the unexpected behaviour?

**Comment by Fi1osof** [comment]
@marktani 
In prisma schema
`type Extended {
  id: ID! @unique
  field1: String
}

extend type Extended {
  field2: String
}`

Expected Extended.field2 too, but got only
`type Extended
implements Node {
  id: ID!
  field1: String
}`

In src/schema.graphql it does not works too.

**Comment by danielmahon** [comment]
*prisma.graphql*
```graphql
type Player implements Node {
  id: ID!
  firstName: String!
}
```
*schema.graphql*
```graphql
# import Player from "./generated/prisma.graphql"

type Query {
  players: [Player!]!
}

extend type Player {
  signedByUser: Boolean
}
```

Query returns 400 error
```graphql
query PlayersQuery {
  players {
    id
    firstName
    signedByUser
  }
}
```

**Comment by Phenominal** [comment]
Running into the same issue:

```
# import Query, User from "./generated/prisma.graphql"

type Query {
  me: User
}

extend type User {
  authToken: String
}
```

Trying to add on `authToken` to the `User` type, but then when I try to grab it I get the message of `Cannot query field "authToken" on type "User". Did you mean "{similar field here}"?`

**Comment by Fi1osof** [comment]
Still actual

**Comment by marktani** [comment]
This is a feature request to the respective GraphQL server library you're using, not to Prisma.
Please open a new feature request at the corresponding GitHub repository.

Thanks! 🙌

**Comment by gkTim** [comment]
This issue still happens. The extension of the type is not included in the generated graphql schema when running `prisma generate`
