### ISSUE TITLE
Comments in schema file cause JSON error

### ISSUE THREAD

**Issue by srisub1** [prisma/prisma#2084]
Upgraded to Beta.1, and my comments in schema file seem to be causing a JSON error.
Unexpected token 
 in JSON at position 337

This happens only if there is a comment with NO text that follows in that one line.

Smallest test case to reproduce:

1. Create schema.prisma:

	```
	generator client {
	  provider = "prisma-client-js"
	}
	
	// Models
	// 
	model Default {
	  id String @default(cuid()) @id
	}
	``` 

2. create a file testbug.ts:

	```
	import { PrismaClient } from '@prisma/client'
	new PrismaClient()
	```

3. Run:
	`npx prisma generate; npx ts-node src/types/testbug.ts`

	```
	Unexpected token 
	 in JSON at position 337
	```

4. Change schema.prisma as follows - remove empty comment

	```
	generator client {
	  provider = "prisma-client-js"
	}
	
	// Models
	model Default {
	  id String @default(cuid()) @id
	}
	```

5. npx prisma generate; npx ts-node src/types/testbug.ts
	=> No Errors

**Comment by srisub1** [comment]
One more reproducable example:

```
// Models

// Website

model Website {
id    String      @default(cuid()) @id
}
```

Outputs: 
Failed to import prisma client package at @prisma/client. The following error occured while trying:
        SyntaxError: Unexpected token 
 in JSON at position 1049
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/...User/node_modules/@prisma/client/index.js:711:19)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.exports.getPhotonDmmf (.../User/node_modules/nexus-prisma/src/dmmf/utils.ts:8:12)
    at Object.exports.getTransformedDmmf (.../User/node_modules/nexus-prisma/src/dmmf/transformer.ts:19:30)

But this works!

```
// Models

model Website {
  id    String      @default(cuid()) @id
}
```

Something going on with parsing of comments in schema file..

**Comment by srisub1** [comment]
I am now getting this error pretty much every time i introduce any // Comment as a separate line, in the schema file.

**Comment by pantharshit00** [comment]
I am unable to reproduce both of the cases.
![image](https://user-images.githubusercontent.com/22195362/78747161-56610980-7986-11ea-8d57-075036385faf.png)

Version used:
```
@prisma/cli          : 2.0.0-beta.1
Current platform     : darwin
Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/introspection-engine-darwin)
```


I think might be OS-specific. Can you please tell me which operating system are you using?

**Comment by srisub1** [comment]
Darwin / Mac.

**Comment by pantharshit00** [comment]
Hi again @srisub1,

Can you please try this with the latest version of the client(which is `2.0.0-beta.2` right now)? 


If you are still able to reproduce this, please send me the code to reproduce this problem in a git repository. Without a working reproduction, we won't be able to resolve this.

**Comment by pantharshit00** [comment]
I am going to close this due to inactivity now. If you can still reproduce this, please comment here and we can another look.
