### ISSUE TITLE
App with Prisma compiled by vercel/pkg get "UNEXPECTED-15" error in Windows 10

### ISSUE THREAD

**Issue by xpcn2015** [prisma/prisma#20841]
### Bug description

I'm using `pkg` to compile my code for Windows 10. 
But after compiled and running .exe file, I get an `UNEXPECTED-15` error and don't know how to pinpoint this error
Without using Prisma, the exe file run without error. but when using Prisma, the exe file throw error, please help.

### Error output
This is error when running .exe file, with environment variable `$env:DEBUG="*"`
```
  prisma:tryLoadEnv  Environment variables not found at C:\snapshot\tr\.env +0ms
  prisma:tryLoadEnv  Environment variables not found at C:\snapshot\tr\.env +1ms
  prisma:tryLoadEnv  No Environment variables loaded +1ms
  prisma:client  checkPlatformCaching:postinstall false +0ms
  prisma:client  checkPlatformCaching:ciName undefined +1ms
  prisma:tryLoadEnv  Environment variables not found at C:\snapshot\tr\.env +1ms
  prisma:tryLoadEnv  Environment variables not found at C:\snapshot\tr\.env +0ms
  prisma:tryLoadEnv  No Environment variables loaded +1ms
  prisma:client  dirname C:\snapshot\tr\node_modules\.prisma\client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd C:\snapshot\tr\node_modules\.prisma\client +0ms
  prisma:client  clientVersion 5.2.0 +1ms
  prisma:client:libraryEngine  internalSetup +0ms
Begin
  prisma:client  Prisma Client call: +1ms
  prisma:client  prisma.user.findFirst({}) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "User",
  "action": "findFirst",
  "query": {
    "arguments": {},
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +4ms
  prisma:client:engines:resolveEnginePath  enginePath C:\snapshot\tr\node_modules\.prisma\client\query_engine-windows.dll.node +0ms
  prisma:client:request_handler  PrismaClientInitializationError: Unable to require(`C:\snapshot\tr\node_modules\.prisma\client\query_engine-windows.dll.node`).
The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: UNEXPECTED-15
    at dn.loadLibrary (C:\snapshot\tr\node_modules\@prisma\client\runtime\library.js:112:9956)    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:64:3)       
    at Function.runMain (pkg/prelude/bootstrap.js:1980:13)
    at node:internal/main/run_main_module:17:47
    at async pr.loadEngine (C:\snapshot\tr\node_modules\@prisma\client\runtime\library.js:114:447)
    at async pr.instantiateLibrary (C:\snapshot\tr\node_modules\@prisma\client\runtime\library.js:113:1762)
    at async pr.start (C:\snapshot\tr\node_modules\@prisma\client\runtime\library.js:114:2166)    at async pr.request (C:\snapshot\tr\node_modules\@prisma\client\runtime\library.js:114:3828)
    at async Object.singleLoader (C:\snapshot\tr\node_modules\@prisma\client\runtime\library.js:123:5246) {
  clientVersion: '5.2.0',
  errorCode: undefined
} +0ms
}
```
### Similar Issue
#17173

### What I had tried
- test from: https://github.com/prisma/ecosystem-tests/tree/dev/binaries/pkg 
after running exe file, it show help info:
![image](https://github.com/prisma/prisma/assets/76277169/530a905c-01d0-4181-9a48-6d21fa7eb4ff)
I think this mean Prisma engine is ok, but I don't know how to use this test to run some query for testing Prisma client.
- rename `query_engine-windows.dll.node` file in `node_modules\.prisma\client` to `query_engine-windows.dll.no` to test pkg does or doesn't include `query_engine-windows.dll.node` file
after run command `yarn pkg .` and run exe file, it shows this error：
![image](https://github.com/prisma/prisma/assets/76277169/bd1a5fb1-f75c-4897-8870-27c163d51027)
It shows different error output, so I think current problem might came from this file.
- remove some code in `index.js` like this:
![image](https://github.com/prisma/prisma/assets/76277169/5f11a4f2-b54a-4149-bef8-4a9d3e4eb86f)
after run command `yarn pkg .` and run exe file, it is no error：
![image](https://github.com/prisma/prisma/assets/76277169/6653a241-a4c4-4c14-9ec0-f38d3bb1cdd0)

### How to reproduce

Clone [This repository](https://github.com/xpcn2015/Prisma-issue-pkg-unexpected-15).
Or following these steps:
1. create `package.json` file
```sh
yarn init -y
```
2. install `pkg`  and `prisma` package
```sh
yarn add -D pkg prisma
yarn add @prisma/client
```
3. make test file `index.js` 
```js
//index.js
const prisma = require('@prisma/client')
const client = new prisma.PrismaClient()
console.log('Begin')

client.user.findFirst().then(v => {     
    console.log(v)
 })
```
4. create `prisma schema`
```sh
yarn prisma init 
```
5. edit `schema.prisma` file
```prisma
//schema.prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```
6. generate Prisma client
```sh
yarn prisma generate
```
7. add Prisma query engine binary path to `packege.json` (https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/pkg-issue#solution)

```sh
npm pkg set pkg.assets="node_modules/.prisma/client/*node"
```
8. add `pkg` config to `packege.json` 
```sh
npm pkg set bin="index.js"
npm pkg set pkg.targets[]="node18-win-x64"
```
9. create .exe file
```sh
yarn pkg .
```
10. run .exe file in Powershell

### Expected behavior

exe file should run without error.

### Prisma information

```prisma

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}

```

```ts
// main.js
const prisma = require("@prisma/client")
const client = new prisma.PrismaClient()
console.log("Begin")

client.user.findFirst().then(v => {
    console.log(v)
})
```

### Environment & setup

- OS: Windows 10 with `Microsoft Visual C++ Redistributable 2015` installed
- Database: Mysql
- Node.js version: 18.16.0

### Prisma Version

```
prisma                  : 5.2.0
@prisma/client          : 5.2.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.2.0-25.2804dc98259d2ea960602aca6b8e7fdc03c1758f
Default Engines Hash    : 2804dc98259d2ea960602aca6b8e7fdc03c1758f
Studio                  : 0.494.0

```

**Comment by xpcn2015** [comment]
I can make it work now. 
In short, add `node_modules/.prisma/client/index.js` to pkg assets in `package.json` file:
![image](https://github.com/prisma/prisma/assets/76277169/f3e28f36-29c9-4480-85a6-6b5b9ae5726e)

I try to search error "UNEXPECTED-15" in many package, and it's in pkg (node_modules/pkg/prelude/bootstrap.js line 943)
I check some variables, and found the `STORE_CONTENT` number is not in `entity`, and it throw "UNEXPECTED-15" 
![image](https://github.com/prisma/prisma/assets/76277169/f87c231a-ff77-4098-bd2d-839370958ac6)

After some search in google, I found this: https://github.com/vercel/pkg/discussions/1623#discussioncomment-2729625 
So I tried to add `node_modules/.prisma/client/index.js` in assets, and it's working now.
![image](https://github.com/prisma/prisma/assets/76277169/f3737fa9-00cb-488e-b750-65f9aa900028)

**Comment by janpio** [comment]
Any idea why defining that file in `assets` is necessary?
https://github.com/vercel/pkg#assets
Wasn't it included before?

**Comment by xpcn2015** [comment]
> Any idea why defining that file in `assets` is necessary? https://github.com/vercel/pkg#assets Wasn't it included before?

without defining assets , pkg will include `\node_modules\.prisma\client\index.js` as bytecode.
According to https://github.com/vercel/pkg#other-considerations, the project that aren't explicitly marked as public by the license in their package.json will only be included as bytecode

Using command `yarn pkg . --public-packages ".prisma/client"` without defining `\node_modules\.prisma\client\index.js` in assets to make exe file will work, too. The files in `.prisma/client` will be included as DISCLOSED code (with sources)

Still don't know why including file as bytecode throw "UNEXPECTED-15" error, I need to dig a little deeper in pkg...

**Comment by janpio** [comment]
Interesting. So we could also fix that by adding a license to the generated Client? 

Of course I am not sure if we should do that, as the generated code technically is _ours_, but _yours_ as it is customized with your Prisma schema. Interesting problem.

**Comment by mikeseese** [comment]
@janpio apparently the workarounds suggested by @xpcn2015, while still working (and required) to get a normal setup working, they do not fix the issue when using a custom `output` for the Prisma client. I created a reproduction repo that demonstrates this: https://github.com/mikeseese/prisma-pkg-test

This is currently blocking me from releasing my product, and I'm happy to do more legwork to help figuring out a solution. I'm also happy to open a new issue if you'd like

**Comment by mikeseese** [comment]
Well I'm not sure why I had issues the first time using @xpcn2015's strategy for for determining the file that needed to get included in the `assets` array for `pkg`, but I was able to get it to work.

I needed to also include `runtime/library.js`, so the below works for me:

``` json
{
  "pkg": {
    "assets": [
      "node_modules/my-custom-prisma/index.js"
      "node_modules/my-custom-prisma/runtime/library.js"
    ],
}
```

for my custom `output` schema:

``` prisma
generator client {
  provider = "prisma-client-js"
  output = "../node_modules/my-custom-prisma"
}
```
