### ISSUE TITLE
Data Loss When Running prisma migrate dev on Vercel PostgreSQL

### ISSUE THREAD

**Issue by spiderakm** [prisma/prisma#20842]
### Bug description

When executing prisma migrate dev on a Vercel project with PostgreSQL, all data was deleted in less than 1 second before the command completed.

### How to reproduce

1. Create a Vercel project.
2. Set up a PostgreSQL database as the data store.
3. Use Prisma with your Vercel project.
4. Run the prisma migrate dev command.
5. Observe the data loss

### Expected behavior

I expected that running prisma migrate dev on Vercel PostgreSQL would perform database migrations without any data loss.

### Prisma information

```prisma
model Address {
  id            Int      @id @default(autoincrement())
  address_line1 String
  address_line2 String?


  @@unique([customer_id, address_line1])
}
model Customer {
  id           Int       @id @default(autoincrement())
  first_name   String?
  last_name    String?
  addresses    Address[]
}
]

```
just modifying the relationship

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL on Vercel
- Node.js: version: v18.16.1
- Nextjs: latest

### Prisma Version

```
4.16.2
```

**Comment by masterbater** [comment]
Expected behavior, they also put a warning bro

**Comment by spiderakm** [comment]
not any warning just command enter

**Comment by jkomyno** [comment]
Hi @spiderakm, that's very odd to hear. Just like @masterbater stated, the `prisma` CLI displays a confirmation warning stating:

> Do you want to continue? All data will be lost. › (y/N)

![Screenshot 2023-08-25 at 11 47 55](https://github.com/prisma/prisma/assets/12381818/29723790-ffca-4499-9365-f28b05309ae3)

Pressing the "ENTER" key results in:
> Do you want to continue? All data will be lost. … no
> 
> Reset cancelled.

Could you please try again in a separate, non-production project (where data loss would be acceptable) and report back with whether the message is visible or not, and whether pressing "ENTER" actually prevents you from running the destructive action? Thanks.

**Comment by janpio** [comment]
I don't expect this was drift or reset related.

Can you please share your `datasource` block from your schema @spiderakm?
Do you by chance have a `shadowDatabaseUrl` property, that is set to the same value as `url`?

**Comment by spiderakm** [comment]
OK Guys let me explain more about
Firstly in my case, I am using Prisma with Postgres SQL on Vercel 
So I was working  I had to change some relations so I had to run the migration command

 Upon executing the migration command, I did not receive any warnings, unlike the warning illustrated by @jkomyno
All data will be lost

This warning typically states that all data will be lost during the migration. However, in my case, this warning was conspicuously absent, leaving me with the impression that the migration would proceed smoothly. Unfortunately, this was not the case.

Before the prisma migrate dev command could complete, my Vercel database was entirely purged of data, although the tables remained intact. I had approximately 510 records that were vital to my application, all of which were lost in this process.

I have only a Vercel Pro account provided by where I am working So I can't do it again 
before everything was fine and came to data loss I had to face these warnings and I am aware of it.
But in my case there is no warning and my 510 orders data has been lost.

In an effort to understand the situation better, I decided to recreate the data and rerun the command. To my dismay, the same catastrophic data loss occurred within less than a second, leaving me in a situation where I can no longer experiment with this process, as I have only one Vercel Pro account provided by my employer.

But now I cant do it because I have only one account

But I don't know if this is a Prisma issue or vercel db issue

Here is Data source
@janpio 
```generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["jsonProtocol"]
}

datasource db {
  provider          = "postgresql"
  url               = env("POSTGRES_PRISMA_URL") // uses connection pooling
  directUrl         = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
  shadowDatabaseUrl = env("POSTGRES_URL_NON_POOLING") // used for migrations
}
```

I am reaching out to bring this issue to your attention and seek guidance on whether it is indeed a Prisma or Vercel database issue. Additionally, I aim to highlight the importance of data backup practices, as I have learned the hard way.

Thank you for your prompt responses and assistance. Moving forward, I will ensure that I maintain regular backups of my database to mitigate such unfortunate incidents.

Once again thank you Guys

**Comment by janpio** [comment]
> url               = env("POSTGRES_PRISMA_URL") // uses connection pooling
>   directUrl         = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
>   shadowDatabaseUrl = env("POSTGRES_URL_NON_POOLING") // used for migrations

That is just wrong. You do not need a `shadowDatabaseUrl`, and you definitely should not set it to the same database than `directUrl` (which `migrate dev` uses. Just deleted the `shadowDatabaseUrl` from your Prisma schema, that is not necessary with Vercel PostgreSQL.

Is this still documented somewhere on the internet? If so, we want to fix that.
