### ISSUE TITLE
User questions: Engine not found (tooling)

### ISSUE THREAD

**Issue by sarahec** [prisma/prisma#20864]
### Discussed in https://github.com/prisma/prisma/discussions/19498

<div type='discussions-op-text'>

<sup>Originally posted by **millsp** May 26, 2023</sup>
Hi, you have been directed to this issue because we want to learn more about your project setup. Thanks to your answers, we will be able to make better design decisions in the future.

We'd appreciate it if you could take 5 minutes to answer a few questions for us. You can write your reply directly in this issue as a comment. Copy and paste these questions in your answer, and leave the answer blank if you don't know.

---

### Have you tried to copy the engine in the suggested location? Did that work?
I"m running nixos, so thos would copy the engine into a locked execute-only package.

I've installed nodeModules.prisma and prisma-engines from the nixos packages.

`prisma --version` returns:

```sh
prisma:warn Both PRISMA_SCHEMA_ENGINE_BINARY and PRISMA_MIGRATION_ENGINE_BINARY are specified, PRISMA_SCHEMA_ENGINE_BINARY takes precedence. PRISMA_MIGRATION_ENGINE_BINARY is deprecated.
prisma:warn Both PRISMA_SCHEMA_ENGINE_BINARY and PRISMA_MIGRATION_ENGINE_BINARY are specified, PRISMA_SCHEMA_ENGINE_BINARY takes precedence. PRISMA_MIGRATION_ENGINE_BINARY is deprecated.
Environment variables loaded from .env
prisma:warn Both PRISMA_SCHEMA_ENGINE_BINARY and PRISMA_MIGRATION_ENGINE_BINARY are specified, PRISMA_SCHEMA_ENGINE_BINARY takes precedence. PRISMA_MIGRATION_ENGINE_BINARY is deprecated.
prisma                  : 5.0.0
@prisma/client          : 5.0.0
Current platform        : linux-nixos
Query Engine (Node-API) : libquery-engine  (at ../../../../nix/store/990y1nyq6xxdix2pqyn7dp9w1cqzhvny-prisma-engines-5.0.0/lib/libquery_engine.node, resolved by PRISMA_QUERY_ENGINE_LIBRARY)
Schema Engine           : schema-engine-cli  (at ../../../../nix/store/990y1nyq6xxdix2pqyn7dp9w1cqzhvny-prisma-engines-5.0.0/bin/schema-engine, resolved by PRISMA_SCHEMA_ENGINE_BINARY)
Schema Wasm             : @prisma/prisma-schema-wasm 4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Default Engines Hash    : 2804dc98259d2ea960602aca6b8e7fdc03c1758f
Studio                  : 0.487.0
```

See the sample repo at https://github.com/sarahec/hello-prisma and execute it with `nx serve prisma-hello`.

### Which package manager are you using?
*For instance `npm`, `pnpm`, or `yarn`. Please attach the version if you know it.*

npm 9.6.7 on nixos 

### Is your workspace a monorepo setup?
Yes, using Nx
### Is a bundler in use? If yes, which one?
*Are you using `webpack`, `swc`, `esbuild`, `rollup`, or any other bundler?*

### Is a framework in use? If yes, which one?
*Are you using `Next.js`, `Next`, or any other framework?*

None

### Your project uses TypeScript or just JavaScript?

This has Typescript.

### When you saw our message, did it happen locally or in deployment?

Locally. 

```sh
sec@dervish:~/scratch/hello-prisma]$ nx serve hello-prisma

> nx run hello-prisma:serve:development

[ watch ] build succeeded, watching for changes...
Debugger listening on ws://localhost:9229/cda52ad8-5bcc-44de-8de8-4480da4df108
Debugger listening on ws://localhost:9229/cda52ad8-5bcc-44de-8de8-4480da4df108
For help, see: https://nodejs.org/en/docs/inspector

PrismaClientInitializationError: 
Invalid `prisma.user.create()` invocation in
/home/sec/scratch/hello-prisma/src/main.ts:6:34

  3 const prisma = new PrismaClient()
  4 
  5 async function main() {
→ 6   const user = await prisma.user.create(
Prisma Client could not locate the Query Engine for runtime "linux-nixos".

This is likely caused by tooling that has not copied "libquery_engine-linux-nixos.so.node" to the deployment folder.
Ensure that you ran `prisma generate` and that "libquery_engine-linux-nixos.so.node" has been copied to "node_modules/.prisma/client".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-tooling-investigation

The following locations have been searched:
  /home/sec/scratch/hello-prisma/node_modules/.prisma/client
  /home/sec/scratch/hello-prisma/node_modules/@prisma/client
  /tmp/prisma-engines
  /home/sec/scratch/hello-prisma/prisma
    at zr.handleRequestError (/home/sec/scratch/hello-prisma/node_modules/@prisma/client/runtime/library.js:122:8581)
    at zr.handleAndLogRequestError (/home/sec/scratch/hello-prisma/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/home/sec/scratch/hello-prisma/node_modules/@prisma/client/runtime/library.js:122:7307)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (/home/sec/scratch/hello-prisma/src/main.ts:6:16) {
  clientVersion: '5.0.0',
  errorCode: undefined
}


>  NX  Process exited with code 1, waiting for changes to restart...
```

### Where is your project deployed?

This is local, to evaluate Prisma.

**Comment by sarahec** [comment]
Aha! The error was in my flake.nix not exporting the required environment variables. Once I fixed that, it worked.

However, could we get a Nix example in your examples repo?

**Comment by janpio** [comment]
Can you please post this as a comment to https://github.com/prisma/prisma/discussions/19498 instead of opening an issue? Thanks.

**Comment by JonathanLorimer** [comment]
@sarahec what environment variables did you need to export from your flake?

**Comment by sarahec** [comment]
It needed several. See sarahec/hello-prisma for the flake settings.

**Comment by JonathanLorimer** [comment]
Thank you @sarahec , nice to see another NixOS user in js / ts issues
