### ISSUE TITLE
Shadow db is not getting deleted.

### ISSUE THREAD

**Issue by hughyyyy** [prisma/prisma#20863]
### Bug description

I found out that we have two copies of shadow db. I followed the doc and it states that in the doc that shadow db should be deleted automatically.
![2023-08-26 15_21_52-Window](https://github.com/prisma/prisma/assets/43278254/018b588b-a831-4656-a750-87ff95f78950)

### Expected behavior

Shadow db is deleted.

### Prisma information

```prisma
// Add your schema.prisma
```

```
// Add your code using Prisma Client
```

### Environment & setup

- OS: Windows
- Database: Azure MySQL
- Node.js version: v19.8.1

### Prisma Version

```

```
prisma 4.14.0

**Comment by yxre** [comment]
Is it possible that you had a process exit unexpectedly and couldn't clean up

**Comment by Jolg42** [comment]
Random old memory that sounds related but about SQL Server https://github.com/prisma/prisma/issues/6371

**Comment by hughyyyy** [comment]
> Is it possible that you had a process exit unexpectedly and couldn't clean up

possible

**Comment by hughyyyy** [comment]
> Hey @hughyyyy, we're going to need some more information to be able to look into this properly. Could you:
> 
> * elaborate as to what your workflow was that caused you to run into this issue?
> * share any logs; as yxre mentioned
> * share your schema;
>   
>   * this _could_ be a permissions thing : [shadow db permissions docs](https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database#shadow-database-user-permissions)
> 
> On quick test, I can't immediately reproduce this by just creating a migration -> `prisma migrate dev` with
> 
> ```prisma
> generator client {
>   provider = "prisma-client-js"
> }
> 
> datasource db {
>   provider = "mysql"
>   url      = env("DATABASE_URL")
> }
> 
> model A {
>   id  Int    @id
>   foo String
> }
> ```

This is not a on the spot thing. I logged into azure portal after a while and discovered these shadow db. I couldn't reproduce either but I am just wondering in this case, is it safe to manually delete them? 

I feel like yxre could be right on that but I don't wanna try on my end tho. 

Feels like some check function here would be handy and safe for `prisma migrate dev`

**Comment by Jolg42** [comment]
@hughyyyy It is safe to manually delete the `prisma_migrate_shadow_db` 👍🏼 

I thought the pricing was per database only for SQL Server, is it the same for Azure MySQL?

**Comment by hughyyyy** [comment]
It's by usage I think

**Comment by millsp** [comment]
Hey @hughyyyy, as we have seen no further activity on the issue, we are closing it. Let us know if you need anything else. Thanks!
