### ISSUE TITLE
Never ending postinstall when using prisma with pnpm

### ISSUE THREAD

**Issue by willruggiano** [prisma/prisma#20870]
### Bug description

When using prisma with pnpm, running `prisma generate` enters a never ending postinstall cycle. My repository includes a postinstall script to run `prisma generate`, but this problem occurs even without this (i.e. by running `prisma generate` directly)

### How to reproduce

My repository is a large monorepo, so I haven't been able to determine if this is something specific to my repo or a general bug in Prisma and/or pnpm. I've tried upgrading pnpm to latest (8.7.0 at time of writing) and also various interim pnpm versions between 8.6.2 and 8.7.0

![screenshot-2023-08-28T11:39:14-06:00](https://github.com/prisma/prisma/assets/11872440/08aac5cc-14cd-4168-884f-7bc2839649b1)

### Expected behavior

`prisma generate` successfully runs

### Prisma information

Nothing special

### Environment & setup

- OS: NixOS
- Database: Postgresql
- nodejs, pnpm, etc:
```
❯ pnpm --version
8.6.2

❯ pnpm version
{
  npm: '9.5.1',
  node: '18.16.1',
  acorn: '8.8.2',
  ada: '1.0.4',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '6.0.11',
  modules: '108',
  napi: '8',
  nghttp2: '1.52.0',
  openssl: '3.0.9',
  simdutf: '3.2.2',
  tz: '2023c',
  undici: '5.21.0',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.15',
  v8: '10.2.154.26-node.26',
  zlib: '1.2.13'
}
```

### Prisma Version

```
Warning Precompiled engine files are not available for nixos.
prisma                  : 5.0.0
@prisma/client          : 5.0.0
Current platform        : linux-nixos
Query Engine (Node-API) : libquery-engine  (at ../../../../../../nix/store/2inas0751dx3z4a429r4fia7d573azng-prisma-engines-5.0.0/lib/libquery_engine.node, resolved by PRISMA_QUERY_ENGINE_LIBRARY)
Schema Engine           : schema-engine-cli  (at ../../../../../../nix/store/2inas0751dx3z4a429r4fia7d573azng-prisma-engines-5.0.0/bin/schema-engine, resolved by PRISMA_SCHEMA_ENGINE_BINARY)
Schema Wasm             : @prisma/prisma-schema-wasm 4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Default Engines Hash    : 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Studio                  : 0.487.0
Preview Features        : views
```

**Comment by willruggiano** [comment]
This actually wasn't a problem previously when using pnpm@8.6.2

Only after attempting to upgrade pnpm did we start seeing this problem. And now this morning after giving pnpm@8.7.0 a try, even the previously stable 8.6.2 exhibits this problem

**Comment by willruggiano** [comment]
Hmm. For some reason, `prisma generate` created a package.json and node_modules directory _inside_ the directory containing my schema.prisma file.

So the repository structure looks something like this:
```
package.json
node_modules/
prisma/
  package.json
  node_modules/
  prisma/       <-- `prisma generate` created a package.json and node_modules directory in here
    schema.prisma
```

**Comment by willruggiano** [comment]
Removing the incorrectly created package.json and node_modules directory resolved the infinite postinstall step

**Comment by Druue** [comment]
Hey @willruggiano, is this something you're capable of reproducing on a more minimal repo?
I'm glad that removing the incorrect `package.json` and `node_modules` was able to resolve the issue tho I'm entirely not sure as to how those would be generated into the `prisma` folder

**Comment by willruggiano** [comment]
It's been hard to reproduce in my own repository so unlikely. It seems related to the version of pnpm however I was not able to consistently reproduce it

**Comment by janpio** [comment]
Did you maybe run one of the Prisma CLI commands in your `prisma` directory? Instead of the project root?

**Comment by willruggiano** [comment]
Nope @janpio all commands were run from either the repository root or the workspace root.

I will try to repo it with a minimal monorepo setup and various versions of pnpm when I have time.

Part of me wonders whether doing `pnpm --filter <package> exec prisma generate` is to blame, meaning: perhaps this only a problem when run within a pnpm workspace... but like I said, no evidence to corroborate that idea.

**Comment by Druue** [comment]
Just to also add back to this, I converted my local prisma-debug repo to use pnpm and executing `pnpx prisma generate` works just fine

**Comment by willruggiano** [comment]
I actually figured this one out kinda randomly. In my pnpm-workspace.yaml, I had `prisma/**` ("prisma" was also the name of my workspace package: e.g. `@my/prisma`) so my hypothesis is that the glob was somehow also including <root>/prisma/prisma as a workspace project. In any case, renaming my workspace package resolved this problem.
