### ISSUE TITLE
SQL Server: `@default(now())` didn't work and put `null` in the database

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#20884]
via https://github.com/prisma/prisma/issues/12729 from @max-programming;

> ## Problem
> In SQL Server with Prisma, when I used `@default(now())` it didn't work and put `null` in the database. More at #12705
> 
> ## Suggested solution
> It would be good if the default function in the prisma schema works fine

**Comment by janpio** [comment]
I can not confirm this, both of these schemas (with and without native typewould successfully generate a date when inserting a row:
```prisma
model Foo {
  id        Int       @id() @default(autoincrement())
  createdAt DateTime? @default(now()) @db.DateTime
}

```
```prisma
model Foo {
  id   Int      @id() @default(autoincrement())
  date DateTime @default(now())
}
```

![image](https://github.com/prisma/prisma/assets/183673/ca1c4efe-2cac-4a1f-b9a2-bbf5e6f7483e)

What am I missing @max-programming?

**Comment by max-programming** [comment]
Looks like it works then. Since then I haven't used sql server. That was a rare occassion. Also it's been a long time so this might have been patched by now ✌️

**Comment by janpio** [comment]
Ok, closing then. If this happens to anyone else, they will open another bug issue report. Thanks!
