### ISSUE TITLE
Prisma not reading system environment variables

### ISSUE THREAD

**Issue by agscala** [prisma/prisma#20894]
### Bug description

I'm building a dockerfile for a nextjs server which uses prisma internally.

I've set the environment variable DATABASE_URL to the url of my postgres database.
I can confirm that the environment variable is set correctly inside the container.

When I start up the application, I'm told that DATABASE_URL is not set.

```
PrismaClientInitializationError:
Invalid `prisma.$queryRaw()` invocation:


error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:12
   |
11 |   provider          = "postgresql"
12 |   url               = env("DATABASE_URL")
```

Inspecting `process.env.DATABASE_URL` in one of my server endpoints shows the correct value.

I'm not using any `.env` files.  This server will be deployed in k8s, and the database url won't be known until runtime.

Is there a configuration step I'm missing, or does prisma really not read the system environment variables?

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by Jolg42** [comment]
@agscala Did you see the message from @Druue? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by millsp** [comment]
Hey @agscala, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it. Thanks.

**Comment by ako-v** [comment]
In my nextjs, I want to use sqlite as my database, here is my docker file:

```
# Start from the official Node.js Alpine base image

FROM node:20.10.0-alpine as base
WORKDIR /app

# Install dependencies
FROM base AS deps
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json* ./
RUN npm ci

# Build the source code
FROM deps AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED 1
ENV DATABASE_URL file:./production.db
RUN npx prisma migrate deploy
RUN npx prisma generate
RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD HOSTNAME="0.0.0.0" node server.js
```
and this is my schema.prisma file:

```
generator client {
  provider      = "prisma-client-js"
  output        = "./generated/client"
  binaryTargets = ["native", "linux-musl-openssl-3.0.x"]
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
```
 but when docker image is built without error, but I am getting this error when I am using the app:
 ```
2024-04-17 15:07:15 error: Environment variable not found: DATABASE_URL.
2024-04-17 15:07:15   -->  schema.prisma:9
2024-04-17 15:07:15    | 
2024-04-17 15:07:15  8 |   provider = "sqlite"
2024-04-17 15:07:15  9 |   url      = env("DATABASE_URL")
2024-04-17 15:07:15    |
```

how can I resolve this issue?
