### ISSUE TITLE
`prisma init --with-model`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#20915]
When testing things, it is often needed that after `prisma init` you add a trivial model to your `schema.prisma` file. It would be amazing if there was a simple CLI argument that adds a model to the generated file by default, making that step obsolete.

Model can be as simple as our suggestion on `prisma generate` without a model:
```
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

**Comment by fool1280** [comment]
Hi @janpio, I'd love to take on this issue.

**Comment by Kayoshi-dev** [comment]
Hello guys, @fool1280 did you start working on this issue ? If not, can I do the PR ? I worked on it !

Thanks!

**Comment by dhayaleswaran** [comment]
Can I step on this if its not taken yet ?.

**Comment by Pankaj-SinghR** [comment]
Hey @Kayoshi-dev , I saw you have raised the PR for this issue, which having merge conflicts, can you plz resolve those, or let me know if i can take over this issue and raise a PR. 👍

**Comment by nikolasburk** [comment]
Opened a PR to make the required docs changes for this: https://github.com/prisma/docs/pull/5951
