### ISSUE TITLE
Prisma Query Engine Creating large number of prepared statements.

### ISSUE THREAD

**Issue by stephenprater** [prisma/prisma#20913]
We're having an ongoing issue with Prisma's Query Engine creating a large number of prepared statements.

Our "DATABASE_URL" includes the "statement_cache_size=0" parameter.   Our engine is set to "binary".  We know that it is creating additional prepared statements - we're using MySQL.

We are _NOT_ using the opentelemetry package, which is known to have this problem.

This is after about 5 minutes of single user operation:

```
mysql> show global status like '%prepared_stmt%';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| Prepared_stmt_count | 0     |
+---------------------+-------+
1 row in set (0.04 sec)
mysql> show global status like '%prepared_stmt%';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| Prepared_stmt_count | 38    |
+---------------------+-------+
1 row in set (0.04 sec)
mysql> show global status like '%prepared_stmt%';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| Prepared_stmt_count | 195   |
+---------------------+-------+
1 row in set (0.03 sec)
mysql> 
```

Our site is fairly high traffic and when this exceeds the `max_prepared_statements` parameter our NodeJS clients start crashing.

We did manage to trace the `prepare` to a section of the Rust client and added some logging there.  We logged all "cache_misses" to one file and "cache_hits" to another.  If the cache was working correctly there should be a single copy of each unique query in the `cache_miss` file - but we found multiple duplicates.

While we seem to be able to curtail creating prepared statements locally by setting `statement_cache_size` to 0 - it doesn't seem to "take" when we do this in production.  I can verify that the environment variable `DATABASE_URL` includes the `statement_cache_size=0` directive by looking in `/proc`

I'm kind of at a loss for what's happening here.

**Comment by stephenprater** [comment]
This is an anonymized sample from queries appearing in my `cache_miss` log file.

```
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
SELECT `my_db`.`table`.`ag`, `my_db`.`table`.`b`, `my_db`.`table`.`c` WHERE 1=1
```

I anonymized this by doing a "find and replace" on the table names and such in the file.  The thing is - should this file _ever_ contain multiple copies of the same query, much less 15 of them?

**Comment by janpio** [comment]
If the cache is disabled, _all_ queries would be a cache miss, right?
(I actually have no real idea how that cache works right now, so that would needed to be looked up)

**Comment by stephenprater** [comment]
@janpio if cache is disable the execution path through the rust binary doesn't touch the place where this is logged:  [here](https://github.com/prisma/prisma-engines/blob/main/quaint/src/connector/mysql.rs#L440-L473) (I added the logging in this method locally so it's not in Github.  Separate issue:  RUST_LOG doesn't trace back to the node `debug` logger if you leave the process management to node - you have to start it yourself.)

I just added a file out to the "miss" option branch.  Actually - I'm looking at the upstream branch for if `statement_cache_size=0` - and I notice that it [unconditionally prepares every statement](https://github.com/prisma/prisma-engines/blob/main/quaint/src/connector/mysql.rs#L410-L433) sent and doesn't free it - so the question of "Why doesn't this work in production" is now "Why _does_ this work locally?"

Feels like an interaction between two settings that isn't obvious and I'm not sure which two settings they would be.

**Comment by stephenprater** [comment]
Wait wait:  there's a drop for [execute_raw](https://github.com/prisma/prisma-engines/blob/main/quaint/src/connector/mysql.rs#L518-L529) but not for [query_raw](https://github.com/prisma/prisma-engines/blob/main/quaint/src/connector/mysql.rs#L484-L507) - I'm not sure what the path to get to those two functions are.

**Comment by janpio** [comment]
> Feels like an interaction between two settings that isn't obvious and I'm not sure which two settings they would be.

Which two settings are you referring to here? `statement_cache_size` and ...?

It would be optimal if we could somehow reproduce this behavior. Do we need to run any special queries, or does _any_ query satisfy this? What else do we need to know to understand what is going on here? Optimally, you would send me a link to a minimal app using Prisma, that I can easily close and run myself to experience the actual problem you are seeing.

**Comment by Jolg42** [comment]
@stephenprater Did you see the message from @janpio? Without any activity on this issue, we would later close it as part of our issue process.

**Comment by millsp** [comment]
Hey @stephenprater, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it. Thanks.
