### ISSUE TITLE
Delete to use the include attribute to cascade deletes

### ISSUE THREAD

**Issue by kokokenada** [prisma/prisma#2092]
## Problem
When cleaning up data, with delete, you may get a relationship error such as:
````
 console.error src/services/UserService.db.spec.ts:263
    PrismaClientUnknownRequestError: 
    Invalid `prisma.user.delete()` invocation:
    
    Error occurred during query execution:
    InterpretationError("Error for binding \'4\': RelationViolation(RelationViolation { relation_name: \"CouponUseToUser\", model_a_name: \"CouponUse\", model_b_name: \"User\" })")
        at PrismaClientFetcher.request (/Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/client/runtime/index.js:1:51636)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
````

## Solution
It would be good if the following worked (typescript likes it as is)
````
      await ctx.prisma.user.delete({
        where: { email_brandId: { email: uniqueEmail2, brandId: 'habitat' } },
        include: {couponUse: true}
      });
````

## Alternatives
You can work around the problem now, by deleting the relations with a separate preceding command, but that could get dicey on a busy instance as different connections maybe used and ideally both deletes should be done in the same transaction.

**Comment by mrwade** [comment]
@kokokenada I was having this same issue and found this other thread that may be worth following: #2057

**Comment by pimeys** [comment]
Fixed in https://github.com/prisma/prisma-engines/pull/1947
Proposal that's implemented is in https://github.com/prisma/prisma/issues/6996

**Comment by janpio** [comment]
This has now been released as a preview feature behind a preview feature flag. You can read about it in the release notes for 2.26.0: https://github.com/prisma/prisma/releases/tag/2.26.0 If you have any feedback, please use this issue: https://github.com/prisma/prisma/issues/7816
