### ISSUE TITLE
Engine does not support Linux distro "openeuler"

### ISSUE THREAD

**Issue by desonyuan** [prisma/prisma#20937]
## Problem
Prisma doesn't know which engines to download for the Linux distro "openeuler". Falling back to Prisma engines built "debian".

# cat /etc/os-release
NAME="openEuler"
VERSION="23.03"
ID="openEuler"
VERSION_ID="23.03"
PRETTY_NAME="openEuler 23.03"
ANSI_COLOR="0;31

This os compatible with CentOS. 
website https://www.openeuler.org/en/
Please add support for this os thanks!

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
