### ISSUE TITLE
How to use Prisma Enum in Nest JS

### ISSUE THREAD

**Issue by coder-Aayush** [prisma/prisma#20998]
### Bug description

I am using prisma with nestjs for my backend. I have written enum in prisma which is working correctly in debug mode. but when i generate prisma client along with nest build, I am getting error.
```javascript
Object.values(client_1.RoomSharingType).join(', '),
                    ^
TypeError: Cannot convert undefined or null to object
```
The type generated by prisma client should work on nestjs end in production build file.

### How to reproduce

In Nestjs application, `schema.prisma` create a enum name `RoomType`, generate with `yarn prisma generate`.
Now use the enum generated by prisma generate with class-validator, code sample below.

Prisma Schema
```dart
enum RoomSharingType {
  TYPE1
  TYPE2
}
```

the DTO, I am defining is:-

```typescript
import {
  RoomSharingType,
} from '@prisma/client';

export class ValidationDemo {
  @IsEnum(RoomSharingType, {
    message:
      'OTP Type must be one of these values: ' +
      Object.values(RoomSharingType).join(', '),
  })
  @IsString()
  type: RoomSharingType;
}
```

Then generate a build for nestjs using `yarn build`. When you upload it, it throw the error.

### Prisma information

```prisma
enum RoomSharingType {
  TYPE1
  TYPE2
}
```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js: version: 20.5.0
- YARN Version    : 1.22.19 

### Prisma Version

```
prisma                  : 5.2.0
@prisma/client          : 5.1.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.2.0-25.2804dc98259d2ea960602aca6b8e7fdc03c1758f
Default Engines Hash    : 2804dc98259d2ea960602aca6b8e7fdc03c1758f
Studio                  : 0.494.0
```

**Comment by aqrln** [comment]
Thanks for opening the issue @coder-Aayush. I'm not entirely sure if it's enough information for reproduction (maybe it is but then it would take time for the person reproducing this to piece everything together which is not optimal). Is there any chance you could create a small clonable repo with minimal reproduction? Thank you!

**Comment by coder-Aayush** [comment]
@aqrln sure i'll provide you with repo.

**Comment by aqrln** [comment]
Thank you!

**Comment by coder-Aayush** [comment]
@aqrln 
https://github.com/coder-Aayush/nest-prisma
Here is the repo, you can use docker to run `docker compose up --build`

**Comment by coder-Aayush** [comment]
@aqrln got the issue, i need to copy the prisma file too and run `prisma generate`. I thought the build file contains all generated code
