### ISSUE TITLE
TypeError: _prisma_client__WEBPACK_IMPORTED_MODULE_1__.Prisma.sql is not a function

### ISSUE THREAD

**Issue by PegeDev** [prisma/prisma#20992]
![image](https://github.com/prisma/docs/assets/89503020/8e3804d8-e48c-40d4-9eb6-f26f00387963)

Bug or Error if run in ubuntu

any solve this problem ?

**Comment by Jolg42** [comment]
@PegeDev Did you see the message from @ruheni? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by millsp** [comment]
Hey @PegeDev, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it. Thanks.
