### ISSUE TITLE
Yarn install stuck on "@prisma/client" when upgraded to node 18

### ISSUE THREAD

**Issue by ykhedher** [prisma/prisma#21008]
### Bug description

I am using Prisma and @prisma/client both version 4.10.0, when I upgraded to node 18 and ran yarn, it get stuck on 
```
[5/5] 🔨  Building fresh packages...
[6/9] ⠈ @prisma/client
```

I tried removing node_modules, tried removing prisma then install it again, tried v5, none worked. always stuck in that part. 

### How to reproduce

1. Upgraded node to "18.17.1"
2. run "yarn"

### Expected behavior

when running yarn, it should finish successfully. 

### Prisma information

not applicable

### Environment & setup

- OS:  macOS
- Database: PostgreSQL
- Node.js version: 18.7.1

### Prisma Version

```
4.10.0

```

**Comment by aqrln** [comment]
@ykhedher which version of yarn are you using? Could you run `yarn --verbose` to see what it is stuck on?

**Comment by ykhedher** [comment]
> @ykhedher which version of yarn are you using? Could you run `yarn --verbose` to see what it is stuck on?

Using `1.22.10`

I tried that, nothing helpful

```
verbose 17.436139625
verbose 17.523634458
verbose 17.58972875
[6/9] ⠐ @prisma/client
```

**Comment by celiolatorraca** [comment]
Hey there!

I am also facing something similar...
Did anyone get any update on this?

**Comment by Lurtroxx** [comment]
Same.

**Comment by ykhedher** [comment]
@Lurtroxx @celiolatorraca @aqrln 

In my case the issue is solved by changing this from `npx run zod-prisma-types` to `yarn run zod-prisma-types`
