### ISSUE TITLE
Restart engine on panic

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#2100]
## Problem
As I understand it, if the engine panics during a request, the client will be rendered nonoperational. Since I only create one client for my application (shared via the Context in an Apollo server), it would mean that the service would need to be restarted. This is problematic for uptime since it would affect other customers that have queries that work. 

## Solution
It would be best if the client would restart the engine automatically. Otherwise it would be best to document that we need to create a client or call connect for each request.

## Additional context
This is needed for a production deployment since errors will happen and they need to be not catastrophic.

**Comment by Sytten** [comment]
I dig a bit and I have some findings:
- For each test, I killed the engine process manually (simulating a panic)
- Calling connect on the client for each request did not restart the process
- Creating a new client for each request starts a new process

**Comment by entrptaher** [comment]
I just tested the `prisma.connect()` for each request and it has a heavy burden of 15-25ms in any given case. Here is a random case for just one request. It's already half slow than the prisma 1 in that case just because we have to avoid the panic.

```
connect: 33.606ms
promises:push(user.create): 4.610ms
promises:Promise.all: 20.313ms
disconnect: 2.312ms
```

**Comment by mavilein** [comment]
@Sytten : If there's a panic during request execution the engine process will not die. The only panics that may kill the process are the ones that happen before the server has finished starting.

**Comment by Sytten** [comment]
@mavilein I was discussing it with @timsuchanek and he explain that, but my whole premise is based on the experience I had on a panic that crashed the rust process. It is probably fixed now, but I still think that it can happen until the Neon binding is implemented. Meaning that if the child dies in the JS code, it should be restarted (if the client wants that).
So the way we are currently planning would be:
1. In the async intercept in NodeEngine, we know if the process died/exited/crashed
2. We have to bubble that to the PrismaClient and remove the `connectPromise`
3. The client can then call connect on each request in a middleware to restart the engine
4. Requests will wait for the engine to restart

**Comment by wSedlacek** [comment]
I am running into an issue with limited memory with a large database and exposing queries pubically. The result is the query engine dieing when memory runs out which is to be expected then all future request failing due to the query engine being dead. While I should limit request so they don't end up this large of someone does find a request that kills the engine it would be nice if that engine didn't require a manual restart of the application.

**Comment by kindywu** [comment]
engine crash and never come back

findMany(
            {
                skip: -1,
                first: 1
            }
        )

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by entrptaher** [comment]
Oh very interesting. Gonna test out.

**Comment by Sytten** [comment]
Will test it too this weekend.
