### ISSUE TITLE
`Prisma has no exported member named OrderByWithRelationInput. Did you mean OrderByWithAggregationInput?`

### ISSUE THREAD

**Issue by thedevdavid** [prisma/prisma#21017]
### Bug description

When previewFeatures = ["fullTextSearch"] is enabled, all of my previously working `Prisma.ModelnameOrderByWithRelationInput` types became unusable.

I guess this is the intended working considering that full-text search & indexing change how the orderBy works, but it looks like this is undocumented.

### How to reproduce

1. add `previewFeatures = ["fullTextSearch", "fullTextIndex"]` to a mySQL schema
2. try using `Prisma.ModelnameOrderByWithRelationInput` type

### Prisma information

```prisma
datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl"]
}
```

```ts
protected buildOrderBy(sortParams: QuerySortDTO | undefined): Prisma.AlbumOrderByWithRelationInput {
    if (!sortParams) {
      return {};
    }

    switch (sortParams.fieldName || '') {
      case 'name':
        return { name: sortParams.direction };
      default:
        return {};
    }
  }
```

### Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: v18.16.0

### Prisma Version

```
5.2.0
```

**Comment by SupertigerDev** [comment]
I also have this issue when i just try to enable fullTextSearch
![image](https://github.com/prisma/prisma/assets/8193841/bd5b6e7f-7961-4065-a2e6-0c14dae54a8e)

**Comment by janpio** [comment]
Is this a new problem in a recent Prisma version or a general problem?

**Comment by SupertigerDev** [comment]
Not sure since I've never tried this preview feature before

**Comment by pitzelalex** [comment]
Just ran into this issue as well. Adding the `previewFeatures = ["fullTextSearch"]` changes the generated type from `ModelOrderByWithRelationInput` to `ModelOrderByWithRelationAndSearchRelevanceInput`. This breaks any references to that type when that preview feature is changed.

**Comment by Weakky** [comment]
Hey folks,

While I understand the frustration, we have no choice but to include this breaking change.

The reason is that we do not include `_relevance` in all `orderBy` types, such as in operations like `aggregate` or `groupBy`.

As such, we _have_ to differentiate both types by breaking one of the two variants. A PR is on the way to update the docs and make that explicit https://github.com/prisma/docs/pull/6102.

For now though, I'll close this issue. Thanks 🙏

**Comment by SupertigerDev** [comment]
I don't get it. Will we not fix the type errors?

**Comment by janpio** [comment]
Can you elaborate @SupertigerDev? 

As far as I understood Flavian (who is now in his well-deserved evening), we thought the problem only was that users now would have to import and use a slightly differently named type. Breaking change for sure, but harmless - and will only be rolled out as default with a future major version. We have preview features so we can test such changes before any major version.

Is the problem different?

**Comment by SupertigerDev** [comment]
Oh never mind. Initially, When I tried to enable `fullTextSearch` preview feature, I used to get errors, even if made no other change. but it seems like those error doesn't happen anymore for me.

https://github.com/prisma/prisma/issues/21017#issuecomment-1712827147

**Comment by Weakky** [comment]
Hey @thedevdavid,

After careful re-inspection of your issue, we have found that when `fullTextSearch` is enabled, `OrderByWithRelationInput` is, as suggested by myself above, renamed to `OrderByWithRelationAndSearchRelevanceInput`, but `OrderByWithRelationInput` is gone entirely.

That means we don't need `OrderByWithRelationAndSearchRelevanceInput` at all.

To avoid unnecessary breaking changes when we later release `fullTextSearch` as GA, we have decided to remove the `OrderByWithRelationAndSearchRelevanceInput` entirely and added the `_relevance` field back to the `OrderByWithRelationInput` type.

This is a breaking change for the `fullTextSearch` preview feature and it should be release tomorrow as part of the new version.

Apologies for the confusion & inconvenience of that breaking change, and thanks for reporting that issue 🙏

**Comment by museadam** [comment]
> Hey @thedevdavid,
> 
> After careful re-inspection of your issue, we have found that when `fullTextSearch` is enabled, `OrderByWithRelationInput` is, as suggested by myself above, renamed to `OrderByWithRelationAndSearchRelevanceInput`, but `OrderByWithRelationInput` is gone entirely.
> 
> That means we don't need `OrderByWithRelationAndSearchRelevanceInput` at all.
> 
> To avoid unnecessary breaking changes when we later release `fullTextSearch` as GA, we have decided to remove the `OrderByWithRelationAndSearchRelevanceInput` entirely and added the `_relevance` field back to the `OrderByWithRelationInput` type.
> 
> This is a breaking change for the `fullTextSearch` preview feature and it should be release tomorrow as part of the new version.
> 
> Apologies for the confusion & inconvenience of that breaking change, and thanks for reporting that issue 🙏

Im on prisma version 5.21.1 running my postgres db on cockroach and I get an error on _relevance. It does not seem to be included in the types. 

I get this error:
`orderBy: {
    _relevance: {
    ~~~~~~~~~~
      fields: [
        "name",
        "description",
        "workType",
        "type",
        "payOption",
        "businessName"
      ],
      search: "",
      sort: "desc"
    },
?   id?: SortOrder,
?   postDate?: SortOrder,
?   businessName?: SortOrder,
?   type?: SortOrder,
?   workType?: SortOrder,
?   email?: SortOrder,
?   name?: SortOrder,
?   expirationDate?: SortOrder | SortOrderInput,
?   logo?: SortOrder,
?   applicationLink?: SortOrder,
?   companyWebsite?: SortOrder,
?   directApply?: SortOrder,
?   description?: SortOrder,
?   payRate?: SortOrder,
?   payOption?: SortOrder,
?   spokenLanguages?: SortOrder,
?   qualifications?: SortOrder,
?   education?: SortOrder,
?   benefits?: SortOrder,
?   requirements?: SortOrder,
?   slug?: SortOrder,
?   addressId?: SortOrder | SortOrderInput,
?   editors?: SortOrder,
?   updatedAt?: SortOrder,
?   published?: SortOrder,
?   publishedDate?: SortOrder | SortOrderInput,
?   template?: SortOrder,
?   authorId?: SortOrder,
?   jobManifesto?: SortOrder | SortOrderInput,
?   theme?: SortOrder | SortOrderInput,
?   subUserId?: SortOrder | SortOrderInput,
?   googleId?: SortOrder | SortOrderInput,
?   archive?: SortOrder,
?   eeoQuestions?: SortOrder | SortOrderInput,
?   applicants?: ApplicationOrderByRelationAggregateInput,
?   address?: AddressOrderByWithRelationInput,
?   author?: UserOrderByWithRelationInput,
?   messages?: MessageOrderByRelationAggregateInput,
?   tags?: TagOrderByRelationAggregateInput
  }
}

Unknown argument `_relevance`. Available options are marked with ?.`

this is my prisma call: 

` await prisma.jobPost.findMany({
		take: takeAmount,
		where: {
			published: true,
			OR: [
				{
					address: {
						city: {
							contains: location
						}
					}
				},
				{
					address: {
						state: {
							contains: location
						}
					}
				},
				{
					address: {
						country: {
							contains: location
						}
					}
				}
			]
		},
		// include: {

		// },
		orderBy: {
			_relevance: {
				fields: [
					'name',
					'description',
					'workType',
					'type',
					'payOption',
					'businessName'
					// 'locationName',
					// 'addressProvState',
					// 'addressCity',
					// 'addressCountry'
				],
				search: s,
				sort: 'desc'
			}
			// postDate: 'desc'
		}
	});`
