### ISSUE TITLE
Suggestion: introduce nominal types for IDs (aka tagged/branded/opaque types) 

### ISSUE THREAD

**Issue by olalonde** [prisma/prisma#21024]
## Problem

Let's take this model as a (made-up) example, where users have a list of posts and an optional FacebookAccount.

```prisma
model User {
  id              Int              @id @default(autoincrement())
  username        String
  facebookAccount FacebookAccount?
  posts           Post[]
}

model FacebookAccount {
  id     Int  @id
  user   User @relation(fields: [id], references: [id])
  // This is an external facebook user id
  userId Int
}

model Post {
  id      Int    @id @default(autoincrement())
  userId  Int
  user    User   @relation(fields: [userId], references: [id])
  content String
}
```

Now let's say you this function:

```typescript
import { PrismaClient } from "@prisma/client";

async function connectFacebookApi(apiKey: string): Promise<{ userId: number }> {
  // do something
  return { userId: 1 };
}

export async function createUser(
  prisma: PrismaClient,
  username: string,
  facebookApiKey: string,
) {
  const { userId } = await connectFacebookApi(facebookApiKey);
  const user = await prisma.user.create({ data: { username } });

  // some more code here...

  // some more code here...

  // oops, I forgot that userId referred to the facebook userId 
  const firstPost = prisma.post.create({
    data: {
      userId, // No type error :(
      // This should have been:
      // userId: user.id,
      content: "Hello world!",
    },
  });
  return { user, firstPost };
}

```

Since TypeStrict is structurally typed, it will accept any variable with a number type in the Post data, whereas it should only accept User IDs.

## Suggested solution

There is a way to simulate nominal typing in TypeScript:

```typescript
type UserId = number & { readonly __brand: unique symbol };

function makeUserId(n: number) {
  return n as UserId;
}
``` 

If Prisma returned such types for IDs, it could potentially catch bugs at compile time (instead of getting a foreign key error at runtime or even worse, have no error at all because the facebookId corresponds to a user id in our database!). In the above example, TypeScript would issue an error because the types would be incompatible. One downside is that IDs coming from outside the code must be internally converted to the appropriate ID type (e.g. `const userId = makeUserId(userInput.userId)` or `const userId = userInput.userId as UserId`).

This would be a breaking change for TypeScript users but wouldn't affect JavaScript users as it's all just type level.

## Alternatives

There are different approaches to simulate nominal typing in TypeScript and it's possible that there will be an official method eventually. See

- [Microsoft/TypeScript#202](https://github.com/microsoft/TypeScript/issues/202)
- [Microsoft/TypeScript#15408](https://github.com/Microsoft/TypeScript/issues/15408)
- [Microsoft/TypeScript#15807](https://github.com/Microsoft/TypeScript/issues/15807)

**Comment by janpio** [comment]
Related or even duplicate of https://github.com/prisma/prisma/issues/5315 or https://github.com/prisma/prisma/issues/12860?

**Comment by olalonde** [comment]
Oops. And I hope @ludralph feels a little bad for letting me write this 🤣

**Comment by janpio** [comment]
Well, it _is_ well written so I suggest you find a way to leave a comment on the best other one.
