### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by devjayprakash** [prisma/prisma#21035]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.16.1           | 
| OS              | darwin-arm64       |
| Prisma Client   | 4.16.2             |
| Query Engine    | 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81|
| Database        | postgresql         |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /Users/jayprakashpathak/learn/learn-prisma/.env
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from /Users/jayprakashpathak/learn/learn-prisma/.env
prisma:client dirname /Users/jayprakashpathak/learn/learn-prisma/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /Users/jayprakashpathak/learn/learn-prisma/prisma
prisma:client protocol graphql
prisma:client clientVersion 4.16.2
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath /Users/jayprakashpathak/learn/learn-prisma/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
 const data = await client.covid_data.groupBy({
    by: ["name_of_state"],
    having: {
      death: {},
    },
  });
```

## Schema
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model covid_data {
  serial_number   Int      @id
  date            DateTime @db.Date
  lat             Float
  long            Float
  confirmed_cases Float
  death           Float
  migrated        Float
  new_cases       Float
  new_deaths      Float
  recovered       Float
  name_of_state   String
}

```

## Prisma Engine Query
```
{
    by: ["name_of_state"],
    having: {
      death: {},
    },
  }
```

**Comment by janpio** [comment]
Thanks @devjayprakash for opening this issue. Can you share the data of `covid_data` with us? That might be useful and necessary for reproduction here. Or can you also reproduce this with an empty table?

**Comment by millsp** [comment]
@devjayprakash did you see the message from @janpio? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by SevInf** [comment]
Hey @devjayprakash ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
