### ISSUE TITLE
Expected parent IDs to be set when ordering by parent ID.

### ISSUE THREAD

**Issue by jacobcwright** [prisma/prisma#21048]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.16.0           | 
| OS              | darwin-arm64       |
| Prisma Client   | in-memory          |
| Query Engine    | 6a3747c37ff169c90047725a05a6ef02e32ac97e|
| Database        | mysql              |

## Logs
```
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine library starting
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
```

## Client Snippet
```ts
npx prisma studio
```

## Schema
```prisma
model Company {
  id                 String      @id @unique @default(cuid())
  name               String
  phone              String
  email              String
  address            String
  city               String
  state              String
  zipCode            String
  processingFee      Float
  createdAt          DateTime    @default(now())
  updatedAt          DateTime    @updatedAt
  users              User[]
  projects         Project[]
}
```

## Prisma Engine Query
```
{"X":true}}}}}
```

**Comment by janpio** [comment]
Uh interesting, Studio crashing like that is unexpected.
Does this happen just when you open Studio, or when you open a specific model in there?
Can you share the data of the underlying table (and related tables)?

**Comment by Jolg42** [comment]
@jacobcwright Did you see the message from @janpio? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by millsp** [comment]
Hey @jacobcwright, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it. Thanks.
