### ISSUE TITLE
Error in migration engine

### ISSUE THREAD

**Issue by mumarse** [prisma/prisma#21054]
Hi Prisma Team! The following command just crashed.

## Command

`migrate deploy`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.16.0           | 
| Prisma CLI  | 4.16.2             | 
| Engine      | 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81| 

## Error
```
RustPanic: Error in migration engine.
Reason: 

```

**Comment by janpio** [comment]
Can you provide some more information @mumarse that might help us reproduce this?
What state was the database in? What migration should `deploy` have deployed?
Is this reproducible?

**Comment by Jolg42** [comment]
@mumarse Did you see the message from @janpio? Without any activity on this issue, we would later close it as part of our issue process.

**Comment by millsp** [comment]
Hey @mumarse, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it. Thanks.
