### ISSUE TITLE
Null Constraint Violation on 'id' UUID Field When Creating a New Record

### ISSUE THREAD

**Issue by bricekams** [prisma/prisma#21053]
### Bug description

I am encountering a `null constraint violation error` on field `id` when attempting to create a new record using Prisma. It seems to be related to the autogenerated id field in my Prisma schema.

### How to reproduce

1. Create a model with: `id String @id @default(uuid()) @db.Uuid` as `id`
2. Run `npx prisma migrate dev --name init && npx prisma genrate`
3. Try to create a new entity without passing the `id`

### Expected behavior

I expected Prisma to generate a valid UUID for the id field when creating a new record, as specified in my schema.

### Prisma information

Model:
```prisma
model Product {
  id               String          @id @default(uuid()) @db.Uuid
  name             String          @unique
  code             String          @unique
  description      String?
  price            Int
  categories       Category[]
  hero             String?
  images           String[]
  tags             String[]
  brand            String
  colors           Color[]
  sizes            Size[]
  createdBy        User            @relation(fields: [createdById], references: [id])
  createdById      String          @db.Uuid
  metrics          ProductMetrics?
  stock            Int
  createdAt        DateTime        @default(now()) @db.Timestamp(6)
  updatedAt        DateTime        @updatedAt @db.Timestamp(6)
  inOrderItem      OrderItem[]
  productMetricsId String?         @db.Uuid
}

```

service:
```typescript
async create(creatorId: string, dto: NewProductDto) {
        let code: string
        do {
            code = generateRandomString(7).toUpperCase()
        } while (await this.prismaService.product.findUnique({ where: { code } }))
        const stockColor = dto.colors.reduce((acc, curr) => acc + curr.stock, 0)
        const stockSize = dto.sizes.reduce((acc, curr) => acc + curr.stock, 0)
        if (stockColor !== stockSize) { throw new BadRequestException("Stocks does not match") }
        return await this.prismaService.product.create({
            data: {
                name: dto.name,
                code,
                stock: stockColor,
                description: dto.description,
                price: parseInt(dto.price),
                brand: dto.brand,
                categories: {
                    connectOrCreate: dto.categories.map((category) => ({ where: { name: category }, create: { name: category } }))
                },
                colors: {
                    create: dto.colors.map((color) => ({
                        color: color.color,
                        stock: color.stock
                    }))
                },
                sizes: {
                    create: dto.sizes.map((size) => ({
                        size: size.size,
                        stock: size.stock
                    }))
                },
                createdBy: {
                    connect: { id: creatorId }
                }
            }

        })
    }
```
Error: 
```error
  4616 if (stockColor !== stockSize) {
  4617     throw new common_2.BadRequestException("Stocks does not match");
  4618 }
→ 4619 return await this.prismaService.product.create(
Null constraint violation on the fields: (`id`)

{
  "constraint": [
    "id"
  ]
}

[Nest] 22557  - 12/09/2023, 15:53:07   ERROR PrismaClientKnownRequestError: 
Invalid `this.prismaService.product.create()` invocation in
/home/quickdo/brice/Eshop/backend/dist/main.js:4620:49

  4617 if (stockColor !== stockSize) {
  4618     throw new common_2.BadRequestException("Stocks does not match");
  4619 }
→ 4620 return await this.prismaService.product.create(
Null constraint violation on the fields: (`id`)
    at vn.handleRequestError (/home/quickdo/brice/Eshop/backend/node_modules/@prisma/client/runtime/library.js:123:6730)
    at vn.handleAndLogRequestError (/home/quickdo/brice/Eshop/backend/node_modules/@prisma/client/runtime/library.js:123:6119)
    at vn.request (/home/quickdo/brice/Eshop/backend/node_modules/@prisma/client/runtime/library.js:123:5839)
    at l (/home/quickdo/brice/Eshop/backend/node_modules/@prisma/client/runtime/library.js:128:9763)
    at ProductsService.create (/home/quickdo/brice/Eshop/backend/dist/main.js:4620:16)
    at /home/quickdo/brice/Eshop/backend/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /home/quickdo/brice/Eshop/backend/node_modules/@nestjs/core/router/router-proxy.js:9:17


[Nest] 15049  - 12/09/2023, 11:42:39   ERROR [LoggerMiddleware] 127.0.0.1 - POST - /api/products/ - 500 insomnia/2023.2.0
```

### Environment & setup

- OS: [docker postgres:15](https://github.com/docker-library/postgres/blob/1a73ab671b5f0f18313726e734c76bf171385c32/15/bookworm/Dockerfile)
- Database: postgres
- Node.js version: v18.17.1

### Prisma Version

- prisma version: ^5.2.0
- prisma client version: ^5.2.0

**Comment by janpio** [comment]
Can you turn on [query logging](https://pris.ly/d/logging) and check if the SQL query that it executes is somehow unexpected? What happens if you run the query manually?

**Comment by bricekams** [comment]
The relations are  marked as not found in `psql`. I don't know why?
Note that I make it register an User, and save notifications but I can't see them in `psql`

![Screenshot from 2023-09-13 13-38-49](https://github.com/prisma/prisma/assets/120424696/7166ac57-74d9-4c17-b564-3eb33882aa0f)
![Screenshot from 2023-09-13 13-40-58](https://github.com/prisma/prisma/assets/120424696/d5dedf55-0259-4b7c-9d80-6c7bf4294b3c)
![Screenshot from 2023-09-13 13-35-04](https://github.com/prisma/prisma/assets/120424696/6faf87e2-46fe-450b-b96d-7beec40fdf74)

**Comment by bricekams** [comment]
And I am having error using $on... saying type string can't be assigned to type never
```typescript
@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  private readonly logger = new Logger(PrismaService.name)
  constructor() {
    super({
      log: [
        { level: 'info', emit: 'event' },
        { level: 'query', emit: 'event' },
        { level: 'warn', emit: 'event' },
      ],
    });

    this.$on('query', e => {
      this.logger.debug('Query: ' + e);
    })
    this.$on('info', e => {
      this.logger.debug('Query: ' + e);
    })
    this.$on('warn', e => {
      this.logger.debug('Query: ' + e);
    })
  }

    async onModuleInit() {
      await this.$connect();
    }
}

```

**Comment by janpio** [comment]
> The relations are marked as not found in `psql`. 

What do you mean with that? I can't connect that info to anything I see in the screenshot.

The product data not existing I would say that is expected, because the actual query fails when you are trying to execute it via Prisma.

> And I am having error using $on... saying type string can't be assigned to type never

Can you maybe just use the simple `const prisma = new PrismaClient({ log: ['query', 'info', 'warn', 'error'], })` to enable logging to the console so you can see all the queries there?

**Comment by bricekams** [comment]
```
prisma:query SELECT "public"."User"."id", "public"."User"."otp", "public"."User"."code", "public"."User"."username", "public"."User"."firstName", "public"."User"."lastName", "public"."User"."phone", "public"."User"."phones", "public"."User"."email", "public"."User"."hash", "public"."User"."picture", "public"."User"."role", "public"."User"."verified", "public"."User"."suspended", "public"."User"."settingId", "public"."User"."emailVerified", "public"."User"."phoneVerified", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Product"."id", "public"."Product"."name", "public"."Product"."code", "public"."Product"."description", "public"."Product"."price", "public"."Product"."hero", "public"."Product"."images", "public"."Product"."tags", "public"."Product"."brand", "public"."Product"."createdById", "public"."Product"."stock", "public"."Product"."createdAt", "public"."Product"."updatedAt", "public"."Product"."productMetricsId" FROM "public"."Product" WHERE ("public"."Product"."code" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query BEGIN
prisma:query SELECT "public"."User"."id" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1) OFFSET $2
prisma:query INSERT INTO "public"."Product" ("id","name","code","price","brand","createdById","stock","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING "public"."Product"."id"
prisma:query SELECT "public"."Category"."id", "public"."Category"."productId" FROM "public"."Category" WHERE ("public"."Category"."name" = $1 AND 1=1) OFFSET $2
prisma:query INSERT INTO "public"."Category" ("name","createdAt","updatedAt","productId") VALUES ($1,$2,$3,$4) RETURNING "public"."Category"."id"
prisma:query ROLLBACK
prisma:error 
Invalid `this.prismaService.product.create()` invocation in
/home/quickdo/brice/Eshop/backend/dist/main.js:4628:49

  4625 if (stockColor !== stockSize) {
  4626     throw new common_2.BadRequestException("Stocks does not match");
  4627 }
→ 4628 return await this.prismaService.product.create(
Null constraint violation on the fields: (`id`)

```

**Comment by bricekams** [comment]
> > The relations are marked as not found in `psql`.
> 
> What do you mean with that? I can't connect that info to anything I see in the screenshot.
> 
> The product data not existing I would say that is expected, because the actual query fails when you are trying to execute it via Prisma.
> 
> > And I am having error using $on... saying type string can't be assigned to type never
> 
> Can you maybe just use the simple `const prisma = new PrismaClient({ log: ['query', 'info', 'warn', 'error'], })` to enable logging to the console so you can see all the queries there?

My bad, Excuse me I am not really good at english. I made it to create a user. But I can't see him in the postgresql command line interface in my docker container. there are users and notifications (In prisma studio)... but when i try to execute `select * from AppNotification` i get error AppNotification is not an existing table.

**Comment by janpio** [comment]
> But I can't see him in the postgresql command line interface in my docker container. there are users and notifications (In prisma studio)... but when i try to execute `select * from AppNotification` i get error AppNotification is not an existing table.

In PostgreSQL ou need to put `"` around your identifiers like table names: `SELECT * FROM "AppNotification";` should work.

**Comment by janpio** [comment]
> ```
> prisma:query SELECT "public"."User"."id", "public"."User"."otp", "public"."User"."code", "public"."User"."username", "public"."User"."firstName", "public"."User"."lastName", "public"."User"."phone", "public"."User"."phones", "public"."User"."email", "public"."User"."hash", "public"."User"."picture", "public"."User"."role", "public"."User"."verified", "public"."User"."suspended", "public"."User"."settingId", "public"."User"."emailVerified", "public"."User"."phoneVerified", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
> prisma:query SELECT "public"."Product"."id", "public"."Product"."name", "public"."Product"."code", "public"."Product"."description", "public"."Product"."price", "public"."Product"."hero", "public"."Product"."images", "public"."Product"."tags", "public"."Product"."brand", "public"."Product"."createdById", "public"."Product"."stock", "public"."Product"."createdAt", "public"."Product"."updatedAt", "public"."Product"."productMetricsId" FROM "public"."Product" WHERE ("public"."Product"."code" = $1 AND 1=1) LIMIT $2 OFFSET $3
> prisma:query BEGIN
> prisma:query SELECT "public"."User"."id" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1) OFFSET $2
> prisma:query INSERT INTO "public"."Product" ("id","name","code","price","brand","createdById","stock","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING "public"."Product"."id"
> prisma:query SELECT "public"."Category"."id", "public"."Category"."productId" FROM "public"."Category" WHERE ("public"."Category"."name" = $1 AND 1=1) OFFSET $2
> prisma:query INSERT INTO "public"."Category" ("name","createdAt","updatedAt","productId") VALUES ($1,$2,$3,$4) RETURNING "public"."Category"."id"
> prisma:query ROLLBACK
> prisma:error 
> Invalid `this.prismaService.product.create()` invocation in
> /home/quickdo/brice/Eshop/backend/dist/main.js:4628:49
> ```


This shows that your actual error comes from the `INSER INTO "Category"`. Can you shared that part of your Prisma schem as well please?

**Comment by bricekams** [comment]
> Can you share that part of your Prisma schema as well please? 

```prisma
model Category {
  id          String     @id @default(uuid()) @db.Uuid
  name        String     @unique
  description String?
  hero        String?
  createdAt   DateTime   @default(now()) @db.Timestamp(6)
  updatedAt   DateTime   @updatedAt @db.Timestamp(6)
  children    Category[] @relation("category_to_category")
  product     Product?   @relation(fields: [productId], references: [id])
  productId   String?    @db.Uuid
  parent      Category?  @relation("category_to_category", fields: [id], references: [id])
}

model Product {
  id               String          @id @default(uuid()) @db.Uuid
  name             String          @unique
  code             String          @unique
  description      String?
  price            Int
  categories       Category[]
  hero             String?
  images           String[]
  tags             String[]
  brand            String
  colors           Color[]
  sizes            Size[]
  createdBy        User            @relation(fields: [createdById], references: [id])
  createdById      String          @db.Uuid
  metrics          ProductMetrics?
  stock            Int
  createdAt        DateTime        @default(now()) @db.Timestamp(6)
  updatedAt        DateTime        @updatedAt @db.Timestamp(6)
  inOrderItem      OrderItem[]
  productMetricsId String?         @db.Uuid
}
```

**Comment by bricekams** [comment]
In fact categories can't be created. the query fails throwing null constraint violation:
service:
```typescript
    async createCategory(dto: NewCategoryDto) {
        let category = await this.prismaService.category.create({
            data: { ...dto,parent: undefined }
        })
        if (dto.parent) {
            category = await this.prismaService.category.update({
                where: { id: category.id },
                data: { parent: { connect: { id: dto.parent } } }
            })
        }
        return category
    }
```
![Screenshot from 2023-09-13 16-47-58](https://github.com/prisma/prisma/assets/120424696/bd60ea77-4de6-4a42-af18-8141b6d25a40)

**Comment by janpio** [comment]
That is weird with this field definition `id          String     @id @default(uuid()) @db.Uuid`, right? That should generate a `uuid` on insert if no other value is provided for `id`.
Can you further simplify and isolate this maybe some way?

**Comment by bricekams** [comment]
Hopefully the error wasn't from prisma.
It was in my schema definition. changing
```prisma
model Category {
  id          String     @id @default(uuid()) @db.Uuid
  name        String     @unique
  description String?
  hero        String?
  createdAt   DateTime   @default(now()) @db.Timestamp(6)
  updatedAt   DateTime   @updatedAt @db.Timestamp(6)
  children    Category[] @relation("category_to_category")
  product     Product?   @relation(fields: [productId], references: [id])
  productId   String?    @db.Uuid
  parent      Category?  @relation("category_to_category", fields: [id], references: [id])
}
```
to
```prisma
model Category {
  id          String     @id @default(uuid()) @db.Uuid
  name        String     @unique
  description String?
  hero        String?
  createdAt   DateTime   @default(now()) @db.Timestamp(6)
  updatedAt   DateTime   @updatedAt @db.Timestamp(6)
  children    Category[] @relation("category_to_category")
  products    Product[]
  parent      Category?  @relation("category_to_category", fields: [parentId], references: [id])
  parentId    String?     @db.Uuid
}
```
```prisma
parent      Category?  @relation("category_to_category", fields: [parentId], references: [id])
parentId    String?     @db.Uuid
```
solved my issues when creating a new category.
