### ISSUE TITLE
raw: COALESCE/IFNULL returns `MA==`

### ISSUE THREAD

**Issue by jamespotz** [prisma/prisma#2107]
## Bug description
Prisma2 returns not numeric value for COALESCE/IFNULL

## How to reproduce
```js
const result = await prisma.raw(`
SELECT COALESCE(SUM(SaleProduct.qty - SaleProduct.qtyInFulfilments),0) as total
FROM SaleProduct
LEFT JOIN Sale ON SaleProduct.ownerCuid = Sale.cuid
LEFT JOIN Product On SaleProduct.productId = Product.id
LEFT JOIN Organisation ON Organisation.id = Sale.orgId
WHERE Organisation.cuid = 'ck8nyod3s00018ssqre2ked2w' AND Sale.status <> 'DRAFT' AND Product.cuid IN ("ck8o07uxr00002z60c7fbfme8","ck8o07v9000012z60qj2d81a8","ck8o07vhs00022z60of43n2ye")
`);
```

## Expected behavior
Should Return `0` but got `total='MA=='`

COALESCE
![image](https://user-images.githubusercontent.com/4239625/78528077-1c222b80-7811-11ea-9b7b-9c55fcd59f31.png)

IFNULL
![image](https://user-images.githubusercontent.com/4239625/78528150-4c69ca00-7811-11ea-96d9-1b069189044d.png)

## Prisma information
prisma-2.0.0.beta.1

## Environment & setup

- OS: Manjaro 19
- Database: MySQL
- Prisma version: 2.0.0-beata.1
- Node.js version: 12.16.1

**Comment by pantharshit00** [comment]
I can reproduce this issue.

Here is a minimal reproduction for internal use: https://github.com/harshit-test-org/prisma2-2107

**Comment by pimeys** [comment]
The only thing we do with the query is we just see if it's a `SELECT` or not. No special treatment for `COALESCE`. Tried it in my database with a query:

```sql
SELECT COALESCE(id - NULL, 0) AS total From User
```

And got a list of zeroes back as expected.

**Comment by matthewmueller** [comment]
Did you try @pantharshit00's repro? It sounds like it could be either during the protocol transfer or in TS land.

**Comment by pimeys** [comment]
MySQL COALESCE casts the default value as a string by default (for some reason). Maybe cast the coalesced value as a number in the query. We just return whatever MySQL gives us.

**Comment by matthewmueller** [comment]
![Uploading image.png…]()

**Comment by pimeys** [comment]
Ah, it casts it as binary then by default!

**Comment by pimeys** [comment]
We base64 binary data returned from the database. Explicit cast should fix this.

**Comment by matthewmueller** [comment]
Feels like typescript should decode base64 then? Or do we need to do this in Rust? If it works properly using a MySQL client, it should work properly in our client.

**Comment by pimeys** [comment]
Not in this case though. What helps here is just modifying the query.

If we have binary data (such as pictures and so on), base64 is needed.

**Comment by matthewmueller** [comment]
It's not a binary blob though, it's an integer: 

https://github.com/harshit-test-org/prisma2-2107/blob/master/prisma/schema.prisma

**Comment by pimeys** [comment]
But the coalesce returns something wrong!

**Comment by pantharshit00** [comment]
I don't know about the implementation but coalesce returns 4 when I run the SQL query:
![image](https://user-images.githubusercontent.com/22195362/78903065-46394f00-7a98-11ea-830a-cce4a1ec2bff.png)


But the client returns it as base64 encoded which is not expected to me:
![image](https://user-images.githubusercontent.com/22195362/78903206-6e28b280-7a98-11ea-8fbd-27969494da67.png)

**Comment by pimeys** [comment]
Actually it's the sum that returns something weird.

**Comment by pimeys** [comment]
As you see it comes out as bytes from the database:

```rust
[query-engine/connectors/sql-query-connector/src/query_ext.rs:51] &p_value = Bytes(
    [
        54,
    ],
)
```

**Comment by matthewmueller** [comment]
Hmm... how does TablePlus properly cast this then? 

![image](https://user-images.githubusercontent.com/170299/78903632-b685a780-7a7b-11ea-8153-ae9b5c3dbb54.png)

**Comment by pimeys** [comment]
It doesn't care about the type information the database gives us. We do due to the json conversion. Here's a patch for @pantharshit00 repo that fixes the issue:

```
diff --git a/index.js b/index.js
index a11a2de..eb996dc 100644
--- a/index.js
+++ b/index.js
@@ -1,6 +1,6 @@
 const { PrismaClient } = require("@prisma/client");

-const prisma = new PrismaClient();
+const prisma = new PrismaClient({debug: true});

 async function main() {
   const test = await prisma.cart.create({
@@ -12,7 +12,7 @@ async function main() {
   console.log(test);

   const data = await prisma.raw`
-    SELECT COALESCE(SUM(Cart.qty - Cart.qtyAvl)) as total from Cart
+    SELECT COALESCE(CONVERT(SUM(Cart.qty - Cart.qtyAvl), UNSIGNED)) as total from Cart
   `;

   console.log(data);
```

**Comment by pimeys** [comment]
We get column data from the database and we need to be able to map that to the corresponding JSON datatype. For some reason MySQL 5.7 tells us the return type of the `SUM` function is binary. We can of course force MySQL to give us the type we need.

**Comment by pimeys** [comment]
https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html#function_convert

**Comment by matthewmueller** [comment]
I understand the solution you're suggesting. I just don't think it's a great experience to have to customize your queries in some arbitrary way that can't be properly tested using your existing database tools. 

Here's an example just using the node.js client:

```js
var mysql = require('mysql')
var connection = mysql.createConnection({
  host: 'localhost',
  user: 'root',
  database: 'issue_2107',
  password: '',
})

connection.connect()

connection.query(
  'SELECT COALESCE(SUM(Cart.qty - Cart.qtyAvl)) as total from Cart',
  function (error, results) {
    if (error) throw error
    console.log('The solution is: ', results[0].total) // 10
  }
)

connection.end()
```

It's able to properly coerce this into a `10` with a `number` type.

**Comment by pimeys** [comment]
We cannot fix all the weirdness that the database does. In this case the database tells us we got binary data back. We can either just pass it as-is, and in some cases break the JSON standard by just producing lots of garbage, or we can trust the database and encode anything that looks like binary for not introducing bugs.

MySQL 5.7 is what it is. And we must follow the JSON standards.

**Comment by matthewmueller** [comment]
Though I doubt it makes a difference, @jamespotz didn't say MySQL 5.7. Personally, I'm testing with MySQL 8.x.

If our protocol doesn't support passing binary data back from Rust => Typescript, it's probably a bad protocol. 

If we can't get around this, then Rust is correct to use a base64 encoding. We'll need to  decode this properly in Typescript-land. Right now we don't.

**Comment by pimeys** [comment]
I suppose JSON doesn't support binary data...

We can of course pass what kind of data we want when we have direct bindings to the v8 in the future. For now we have whatever boundaries JSON gives us.

**Comment by pimeys** [comment]
And in normal Prisma queries we know the types of the columns beforehand. When you pass the raw query we do not, and we don't even touch the queries (excl. trim). What type information exists in this point except the data MySQL tells us?

**Comment by matthewmueller** [comment]
Not super familiar with the mysql protocol, but I'm guessing they use something like `oid` to determine what datatype they returned. Maybe we need to include this information in the JSON response back to Typescript.

**Comment by pimeys** [comment]
So MySQL returns the number as string with charset indicating binary for sum function. But also gives a hint it might be NUMERIC. Now we use this information to parse the binary string as Decimal. 

Of course MySQL has a normal Decimal type too but here it returns a binary. Quaint now checks this value and converts correctly. There might be other weird return types we don't handle yet.

**Comment by pantharshit00** [comment]
This is fixed in alpha @jamespotz 

Try using `npm install @prisma/cli@alpha`

**Comment by jamespotz** [comment]
Thanks @pantharshit00 will check the alpha

**Comment by jamespotz** [comment]
Confirmed. `@prisma/cli@alpha` fixed the issue. I'll be closing this issue.
