### ISSUE TITLE
Self relations generated children types are wrong

### ISSUE THREAD

**Issue by Zebnastien** [prisma/prisma#21106]
### Bug description

Using sqlite default prisma provider...
Consider the following model with self relation...

![image](https://github.com/prisma/prisma/assets/64729974/9df667b0-c278-4c3d-9d8b-21f85e934248)

Here is the generated type...

![image](https://github.com/prisma/prisma/assets/64729974/7246a97c-9b98-49c7-a9b3-e3a66a93ae4e)

=> Type of children should be **mvp_data[ ]** and not **string**.

### How to reproduce

1. Create this above model in Prisma schema.

2. Import generated type in your project with
`import type { mvp_data } from "@prisma/client"`

4. Notice how children type is **string** instead of **mvp_data[ ]**

### Expected behavior

Type should be
`mvp_data = {
    id: string;
    label: string;
    status: number;
    progress: number;
    children: mvp_data[ ];
}`

### Prisma information

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model mvp_data {
  id       String     @id @default(uuid())
  label    String
  status   Int        @default(0)
  progress Float      @default(0)
  parentId String?
  parent   mvp_data?  @relation("ParentChild", fields: [parentId], references: [id])
  children mvp_data[] @relation("ParentChild")
}
```ts
```

### Environment & setup

- OS: Windows
- Database: SQLite
- Node.js version: 20.5.1

### Prisma Version

```
5.3.1
```

**Comment by SevInf** [comment]
I can not reproduce the issue with the provided schema, neither on `5.3.1` nor on `5.9.0-dev`.
Generated type for me is:


![Image](https://github.com/prisma/prisma/assets/603056/3e3e3036-b708-45f2-9167-b559b3eb4440)

It is expected that relationships are not included in generated types by default, so `mvp_data` should not include field `children` at all.

@Zebnastien could you provide a reproduction repository where we could see it happen? 
Thank you!

**Comment by SevInf** [comment]
Hey @Zebnastien  ,

Did you get a chance to have a look at my previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by Zebnastien** [comment]
Hi, sorry for the delay.
I will try this weekend.

**Comment by Zebnastien** [comment]
Ok, I tried all my best to reproduct this bug but I did not success.
I got same result of you:
![image](https://github.com/prisma/prisma/assets/64729974/be151238-b0a3-4498-a58c-2c53fcc3e1dd)

So I guess it was my fault. I think we can close this issue.
Sorry for the time and thank you for your consideration 👍🏼
