### ISSUE TITLE
Error "n.match is not a function" | "Function value could not be deserialized"

### ISSUE THREAD

**Issue by mel-habip** [prisma/prisma#21100]
### Bug description

![image](https://github.com/prisma/prisma/assets/82610380/690c8cd0-5dcd-4ae2-939f-ce4c4b61a50c)

I get this when starting my app. The command runs `npx nodemon src/app.ts`.

I'm not certain what triggerred this as I don't think I changed any Prisma related settings.

I use a file where I create the Prisma Client and then import that in all other locations as needed. It looks like this 
![image](https://github.com/prisma/prisma/assets/82610380/e5050e83-bbd4-4d2e-afeb-6c70b19d4db8)

I have verified that the DB to which Prisma attempts to connect is up and running and available. I am able to connect and execute via MySQL Workbench. 

### How to reproduce

:/ not too sure
- start your app that uses Prisma?

### Expected behavior

the App starts up as usual.

### Prisma information

```prisma
// My prisma schema is quite huge
```

When my server starts up, I run this function to check the connection.
```ts
async function verifyDatabaseConnection() {
    const prisma = new PrismaClient();
    try {
        await prisma.$connect();
        console.log('Database connected successfully.');
    } catch (error) {
        console.error('Error connecting to the database:', error);
        process.exit(0);
    } finally {
        await prisma.$disconnect();
    }
};
```

### Environment & setup

- OS: Windows 11 Home (Version 10.0.22621 Build 22621)
- Database: MySQL Engine 8.0.34
- Node.js version: v20.5.0

### Prisma Version

```
prisma                  : 5.3.1
@prisma/client          : 5.3.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.1-2.61e140623197a131c2a6189271ffee05a7aa9a59
Default Engines Hash    : 61e140623197a131c2a6189271ffee05a7aa9a59
Studio                  : 0.494.0
```

**Comment by mel-habip** [comment]
After changing the `verifyDatabaseConnection` function to use the prisma client I initialize elsewhere (SS in issue), I started getting this error when running the `verifyDatabaseConnection` function 
![image](https://github.com/prisma/prisma/assets/82610380/e5f2c13d-d45a-4e02-aa81-5856d423fdf2)

**Comment by mel-habip** [comment]
After some digging and testing, I found that this declaration I had made was the source of the error. 

```ts
declare global {
    interface Object {
        at(key: string): any;
    }
}

Object.prototype.at = function (key) {
    if (this.hasOwnProperty(key)) return this[key as keyof Object];
    let [keyPartOne, ...keyRest] = key.split('.');


    if (this.hasOwnProperty(keyPartOne)) {
        return this[keyPartOne as keyof Object].at(keyRest.join('.'));
    }
};
```

changing the `at` to something else (like `specialAt`) to avoid a possible conflict did not yield any improvements.

**Comment by janpio** [comment]
So your change in the `at` prototype lead to multiple things breaking, including something that looked like code in Prisma Client - but it was not Prisma's fault?

Good you figured it out. I guess we can close this issue then?

**Comment by Jolg42** [comment]
Closing, based on last comments from @janpio.
Let us know if this needs to be re-opened.
