### ISSUE TITLE
Make the relation scalar to be writable

### ISSUE THREAD

**Issue by gfpacheco** [prisma/prisma#2111]
## Problem
It sucks when you receive an input in this format: `{ data: { authorId: 1 } }` and have to map to this one: `{ data: { author: { connect: { id: 1 } } } }` because we can't write to relation fields directly. That makes it harder to reuse code.

## Solution
Make the relation scalar to be writable from Prisma Client.

## Alternatives
Map each entity's input before sending to Prisma (must be done differently for each entity).

## Additional context
https://github.com/prisma/prisma/discussions/2097

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/2152

**Comment by pantharshit00** [comment]
@gfpacheco This is implemented with `uncheckedScalarInputs`: https://github.com/prisma/prisma/issues/4209
