### ISSUE TITLE
Prisma Client extension with method override and `jest-mock-extended` or `vitest-mock-extended` expects `never` input 

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#21136]
### Bug description

When using Prisma Client for instance with Accelerate or any other extension that overrides the original client methods, and mocking this extended client with either `jest-mock-extended` or `vitest-mock-extended` will in turn make that `mockResolvedValue` expects an input of type `never`.

[Slack thread](https://prisma-company.slack.com/archives/C05SCP1DG8Z/p1695071134806409?thread_ts=1694726613.081089&cid=C05SCP1DG8Z)

### How to reproduce

```ts
import { mockDeep } from "vitest-mock-extended";
import type { PrismaClient } from "@prisma/client";
import { withAccelerate } from "@prisma/extension-accelerate"

const prismaMock = mockDeep<PrismaClient>().$extends(withAccelerate());

prismaMock.booking.count.mockResolvedValue(0) // see red squiggly line under `0`
```

### Expected behavior

The expected input should not be `never`, it should be the type of the result (in this case, a `number` for `.count`).

However, due to limitations, we can not properly infer `this` in the extension ahead of time and within the mocking library, which is necessary for the mocking library to preserve type safety (see slack thread). Instead, when `this` cannot be inferred, we could default to `any` instead of never.

### Prisma information

n/a

### Environment & setup

n/a

### Prisma Version

```
5.3.1
```

### Explanation

When you look at this line: `prismaMock.booking.count.mockResolvedValue(0);`, the value 0 is underlined with a squiggly, and TypeScript complains that the value should not be a number, but never.

So first, let's unpack how this vistest mocking library works. First of all, Calcom enables the mocking. What this enables, is that you can call method utilities for mocking on methods to be mocked. See count, originally it's a simple method, but after mocking it has methods available on the method itself.

To achieve this, the mocking library add the new properties at runtime, and on the other hand it also does so on the type level. It does so deeply and on any method sitting on the mocked object, in this case the prisma client. To achieve this on the type level, it uses recursive mapped types to make the added methods available on top of each prisma client operation. That's where things go wrong.

This library (and probably other mocking libraries) override, or re-create if you will, the mocked prisma client operation. In this process, it uses inference on the ...args and the return types of the operation. This is what causes the loss of types.

Going a bit deeper into why: Accelerate is a dynamic/generic extension, and as you may know, this dynamicity is made possible by Prisma.Args and Prisma.Result which respectively get the arguments and result types available on any client, dynamically via the underlying this (in this example, this would be the booking model). When mockResolvedValue is called, its internal infer forces the resolution of arg and result types while the underlying model is not yet known.

In theory I believe that this could have been known by the compiler, actually. However, this would make no sense for generic paramaters targeting this to behave differently than other generic parameters. So it is consistent, and this must be a reasonable design limitation in the compiler, totally understandable. So the conclusion is that in turn this forces Prisma.Args and Prisma.Result to return never. This only affects methods that are overrides or make use of generic parameters bound to this, Accelerate does both.

**Comment by daniel-smyth** [comment]
I am also experiencing this. 

Is this in all Prisma v5 versions?

**Comment by millsp** [comment]
Hey @daniel-smyth, I'd appreciate if you could give it a try, update your current prisma versions to the branch version `5.4.0-integration-fix-client-extension-mock.5`, install, and re-generate your client.

**Comment by daniel-smyth** [comment]
Hey @millsp, thanks for looking at this! This is blocking us from upgrading to v5 unfortunately.  

I am still experiencing the same issue on that branch:

My Prisma mock:
![image](https://github.com/prisma/prisma/assets/102957749/43711a19-8aa4-44f7-a64a-47e245856359)

My `package.json`:
![image](https://github.com/prisma/prisma/assets/102957749/195836d0-7817-4ff3-9b8a-73180d37928b)

The error (`where` is still of type `never`):
<img width="636" alt="image" src="https://github.com/prisma/prisma/assets/102957749/335ef382-37ce-470a-ab54-1632b57a8771">

**Comment by millsp** [comment]
Thanks for the repro, could you also please share your schema (or part of it)? With that I can be sure to reproduce your code.

**Comment by daniel-smyth** [comment]
All good. Here is a minimal version of our schema. 

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator zod {
  provider                         = "zod-prisma-types"
  output                           = "../../core-js/src/model"
  useMultipleFiles                 = true
  writeBarrelFiles                 = false
  createInputTypes                 = false
  createModelTypes                 = false
  addInputTypeValidation           = false
  addIncludeType                   = false
  addSelectType                    = false
  validateWhereUniqueInput         = false
  createOptionalDefaultValuesTypes = true
  createRelationValuesTypes        = true
  createPartialTypes               = true
  useDefaultValidators             = false
  coerceDate                       = true
  writeNullishInModelTypes         = true
}

model Profile {
  id String @id @default(cuid())

  cards Card[]
}

model Card {
  id String @id @default(cuid())

  properties      CardProperty[]

  profile_id String?
  profile    Profile? @relation(fields: [profile_id], references: [id])
}

model CardProperty {
  id String @id @default(cuid())

  value String?

  card_id String
  card    Card   @relation(fields: [card_id], references: [id], onDelete: Cascade)

  created_at DateTime  @default(now())
  updated_at DateTime  @updatedAt
  deleted_at DateTime?

  @@index([card_id, deleted_at])
}
```

**Comment by millsp** [comment]
Thanks, I am able to reproduce with an empty extension.

**Comment by millsp** [comment]
Hey @daniel-smyth, could you please give `5.4.0-integration-fix-client-extension-mock.7` a try?

**Comment by daniel-smyth** [comment]
Hey @millsp, that seems to have worked great. Looking forward to upgrading to V5.

Thank you!
