### ISSUE TITLE
prisma 2 no longer generates prisma.graphql

### ISSUE THREAD

**Issue by mitchhankins01** [prisma/prisma#2115]
## Problem
prisma 1 generated "/generated/prisma.graphql" which allowed us to import types into the apollo scheme, prisma 2 no longer generates this file

## Solution
have prisma 2 generate the file as well, or is there a better way?

**Comment by notrab** [comment]
@mitchhankins01 Prisma 2 is no longer just a GraphQL ORM but more abstract ORM. I'd look at Nexus for generating such schemas.
