### ISSUE TITLE
Use SSL variables feature

### ISSUE THREAD

**Issue by darkenedsoul2k1** [prisma/prisma#2116]
# Feature Request

**What feature are you missing?**
"Use SSL" environment variables for both Client/Internal MySQL connections instead of hard coding useSSL=false in the program's JDBC connection strings.

**How could this feature look like in detail? Tradeoffs?**
In affected application.conf's in the source code it could look like this:
`url = "jdbc:mysql://"${SQL_CLIENT_HOST}":"${SQL_CLIENT_PORT}"/?autoReconnect=true&useSSL="${SQL_CLIENT_USE_SSL}"&serverTimeZone=UTC&useUnicode=true&characterEncoding=UTF-8&usePipelineAuth=false"`

Swapping SQL_CLIENT_USE_SSL for SQL_INTERNAL_USE_SSL as needed on the conf.

Minor modification of connectors\deploy-connector-msyql\src\main\scala\com\prisma\deploy\connector\mysql\InternalDatabaseDefs.scala would also be necessary to match.

**Comment by leebenson** [comment]
Does this mean it's currently not possible to connect to an external MySQL DB via SSL?

**Comment by dpetrick** [comment]
Controlling SSL is possible in Prisma via the config file. Use the optional config key `ssl: true` to enable SSL on the connection string level.
Postgres already works, and I just merged a fix that allows to enable SSL for MySQL as well, as soon as it hits master in the next releases.
