### ISSUE TITLE
prisma:warn In production, we recommend using `prisma generate --no-engine` (See: `prisma generate --help`)

### ISSUE THREAD

**Issue by swizzmagik** [prisma/prisma#21169]
### Bug description

![image](https://github.com/prisma/prisma/assets/3955528/514e7bb3-131b-457d-9410-4bd1ec89f0c7)

Recieving this warning when running locally. However, `prisma generate --no-engine` command does not exist.

![image](https://github.com/prisma/prisma/assets/3955528/a150d154-464b-45f3-bd03-87c788421fc8)

![image](https://github.com/prisma/prisma/assets/3955528/c2567f42-0cf4-4f13-aac4-a8c8b8b0b37e)

### Expected behavior

the command it is recommending should exist

### Prisma information

```prisma
// Add your schema.prisma
datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_DATABASE_URL")
  // shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native", "windows"]
  previewFeatures = ["fullTextSearch"]
}
```

```ts
// Add your code using Prisma Client
/* eslint-disable @typescript-eslint/no-namespace */
import { PrismaClient } from '@prisma/client';
import { withAccelerate } from '@prisma/extension-accelerate';

// https://github.com/prisma/prisma/issues/6219#issuecomment-840676092

declare global {
  namespace NodeJS {
    interface Global {
      prisma: PrismaClient;
    }
  }
}

let prisma;

if (typeof window === 'undefined') {
  if (process.env.NODE_ENV === 'production') {
    prisma = new PrismaClient().$extends(withAccelerate());
  } else {
    if (!global.prisma) {
      global.prisma = new PrismaClient().$extends(withAccelerate());
    }

    prisma = global.prisma;
  }
} else {
  throw new Error('Attempt to use prisma in client');
}

export default prisma;

```

### Environment & setup

- OS: windows
- Database: PostgreSQL (supabase)
- Node.js version: v18.15.0

### Prisma Version

```

```
 "@prisma/client": "^5.2.0",
 "@prisma/extension-accelerate": "^0.6.2",
    "prisma": "^5.2.0",
```
```

**Comment by janpio** [comment]
What output do you get on `npx prisma -v`? And on `prism -v`?

**Comment by swizzmagik** [comment]
The problem was i was running WSL and had 5.3.0 installed in project but 4.15.0 globally installed. i fixed it by running `npm i -g prisma@latest` thanks for your help.
