### ISSUE TITLE
Inconsistent relationMode = "prisma" Warning Based on @@index Field Order

### ISSUE THREAD

**Issue by greedybrain** [prisma/prisma#21181]
### Bug description

I've noticed an unusual behavior in Prisma where the warning for `relationMode = "prisma"` appears or disappears based on the order of fields in an `@@index` directive.

```
model EntityTag {
    id          String      @id @default(uuid())
    MainEntity  MainEntity  @relation(fields: [mainEntityId], references: [id])
    mainEntityId String
    Tag         Tag         @relation(fields: [tagId], references: [id])
    tagId       String

    @@unique([mainEntityId, tagId])
    @@index([mainEntityId, tagId])
}
```

### How to reproduce

1. With the @@index in the above format (@@index([mainEntityId, tagId])), I receive a warning: "With relationMode = "prisma", no foreign keys are used, so relation fields will not benefit from the index usually created by the relational database under the hood."
2. If I reverse the fields like this: @@index([tagId, mainEntityId]), the warning goes away.

### Expected behavior

**Expected Behavior**
The warning related to relationMode = "prisma" should not depend on the order of fields within an @@index.

**Actual Behavior**
The warning seems to appear or disappear based on the order of the fields within the @@index.

### Prisma information

```prisma
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider     = "mysql"
    url          = env("DATABASE_URL")
    relationMode = "prisma"
}

model SampleModel {
    id        String     @id @default(uuid())
    createdAt DateTime   @default(now())
    updatedAt DateTime   @updatedAt
}

// OAuth Account
model AuthAccount {
    id                  String  @id @default(uuid())
    userId              String
    thirdPartyType      String
    thirdPartyProvider  String
    thirdPartyAccountId String
    refreshToken        String? @db.Text
    accessToken         String? @db.Text
    user                Person  @relation(fields: [userId], references: [id], onDelete: Cascade)
    @@unique([thirdPartyType, thirdPartyAccountId])
    @@index([userId])
}

// Main entity
model MainEntity {
    id              String           @id @default(uuid())
    attributes      String
    relatedEntities RelatedEntity[]
    SpecialInfo     SpecialInfo?     @relation(fields: [specialInfoId], references: [id], onDelete: Cascade)
    Tags            EntityTag[]

    specialInfoId   String? @unique
}

// Join Table for many-to-many relationship
model EntityTag {
    id         String     @id @default(uuid())
    MainEntity MainEntity @relation(fields: [mainEntityId], references: [id])
    mainEntityId String
    Tag        Tag        @relation(fields: [tagId], references: [id])
    tagId      String

    @@unique([mainEntityId, tagId])
    @@index([mainEntityId, tagId])
}

// Associated entities
model RelatedEntity {
    id          String     @id @default(uuid())
    MainEntity  MainEntity @relation(fields: [mainEntityId], references: [id], onDelete: Cascade)
    mainEntityId String

    @@index([mainEntityId])
}

// Additional info entity
model SpecialInfo {
    id            String          @id @default(uuid())
    details       String
    MainEntity    MainEntity?
    specialField  String

    specialFieldId String? @unique

    @@index([specialFieldId])
}

// OAuth Session
model Session {
    id           String  @id @default(uuid())
    sessionToken String  @unique
    userId       String
    expires      DateTime
    user         Person @relation(fields: [userId], references: [id], onDelete: Cascade)
    
    @@index([userId])
}

// Tags
model Tag {
    id        String     @id @default(uuid())
    name      String
    EntityTag EntityTag[]
}

// User
model Person {
    id            String      @id @default(uuid())
    name          String?
    email         String?     @unique
    emailVerified DateTime?
    image         String?
    accounts      AuthAccount[]
    sessions      Session[]
}

// Verification Token
model VerificationToken {
    identifier String
    token      String @unique
    expires    DateTime

    @@unique([identifier, token])
}

```

### Environment & setup

- OS: macOs
- Database: PlanetScale (MySQL)
- Node.js version: 20.5.0

### Prisma Version

```
5.3.1
```

**Comment by greedybrain** [comment]
So I found that "When working with Planetscale, you will need to create the index on multiple relation scalar fields on a separate line instead of using multi-column index."

**Source**
https://github.com/prisma/prisma/discussions/18718

**Comment by janpio** [comment]
`@@index` for two columns das not have the same effect as 1 `@index` each. That is why the validation is not happy with just one combined index.

**Comment by greedybrain** [comment]
> `@@index` for two columns das not have the same effect as 1 `@index` each. That is why the validation is not happy with just one combined index.

But at the same time the @index attribute doesn't seem to be working for a single field. I get a warning in VSCode that shows the following:

![no-@index](https://github.com/prisma/prisma/assets/51010236/68d2f772-dccb-4936-963d-154b75da8cd5)

And this occurs with or without the @@index([userId]) commented out

**Comment by janpio** [comment]
Ahm yes.
I meant `@index[userId])` indeed. For complicated reasons, we do not have the direct attribute `@index`. Sorry for the confusion.

**Comment by greedybrain** [comment]
No worries, and thank you 🙏🏽
