### ISSUE TITLE
FindMany include throws error

### ISSUE THREAD

**Issue by marcjulian** [prisma/prisma#2119]
## Bug description

`this.prisma.nationalPark.findMany({ include: { country: true } });` used to return all `NationalPark`s including the `Country` using prisma in version `preview024`.

After updating from `preview024` to `beta.1` the call `this.prisma.nationalPark.findMany({ include: { country: true } });` using `include` throws the error below. Without `include` the error is not thrown. 

```
Invalid `return this.prisma.nationalPark.findMany()` invocation in
/Users/m/Dev/notiz/repo-posts/nestjs-prisma-heroku/src/app.controller.ts:20:37

  16 }
  17 
  18 @Get('nationalParks')
  19 getNationalParks() {
→ 20   return this.prisma.nationalPark.findMany(

Expected at most 1 item for 'country', got 4 +27614ms
Error: 
Invalid `return this.prisma.nationalPark.findMany()` invocation in
/Users/m/Dev/notiz/repo-posts/nestjs-prisma-heroku/src/app.controller.ts:20:37

  16 }
  17 
  18 @Get('nationalParks')
  19 getNationalParks() {
→ 20   return this.prisma.nationalPark.findMany(

Expected at most 1 item for 'country', got 4
    at PrismaClientFetcher.request (/Users/m/Dev/notiz/repo-posts/nestjs-prisma-heroku/node_modules/@prisma/client/runtime/index.js:1:47490)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
## How to reproduce

1. Go to [https://github.com/notiz-dev/deploy-nestjs-prisma-heroku](https://github.com/notiz-dev/deploy-nestjs-prisma-heroku)
2. `src/app.controller.ts` line 20
2. Run `npm run start:dev`
3. Visit `http://localhost:3000/nationalParks`

## Expected behavior

`this.prisma.nationalPark.findMany({ include: { country: true } });` should return all NationalParks including Country.

## Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model NationalPark {
  id      Int     @id @default(autoincrement())
  name    String
  country Country
}

model Country {
  id   Int    @id @default(autoincrement())
  name String @unique
}
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.1
- Node.js version: v12.16.1

**Comment by asciant** [comment]
It appears that your data model implies (or defines) a 1-1 relationship between NationalPark and Country. Whereas your data returns more than one record when the query completes.

If a `NationalPark` has many `Countries`, then you should update the data model to be a 1-n relationship.

There were some relational changes to the data model as part of the 2.0.0-beta.1 release, it might pay to check them out as a first point of call.

```
model NationalPark {
  id      Int     @id @default(autoincrement())
  name    String
  country Country[]
}

model Country {
  id   Int    @id @default(autoincrement())
  name String @unique
  parks   NationalPark  @relation(fields: [parkId], references: [id])
  parkId  Int
}
```

[Prisma2 Relations Documentation](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#one-to-many-relations)

**Comment by marcjulian** [comment]
@asciant thanks for your feedback. I will look into the relationship of my model.
I think my relationship should be indeed a 1-n relationship like: 

```prisma
model NationalPark {
  id      Int     @id @default(autoincrement())
  name    String
  country Country @relation(fields: [countryId], references: [id])
  countryId Int
}

model Country {
  id   Int    @id @default(autoincrement())
  name String @unique
  parks   NationalPark[] 
}
```

**Comment by marcjulian** [comment]
That work! Thanks. 

One thing I notice as I am just returning the Prisma object in the REST Response that it now includes the `countryId`

Before:

```json
[
  {
    "id": 1,
    "name": "Tongariro",
    "country": {
      "id": 1,
      "name": "New Zealand"
    }
  }
]
```

Now:

```json
[
  {
    "id": 1,
    "name": "Tongariro",
    "countryId": 1,
    "country": {
      "id": 1,
      "name": "New Zealand"
    }
  }
]
```
