### ISSUE TITLE
Operation 'createOne' for model '..' does not match any query. SQLite

### ISSUE THREAD

**Issue by mamqek** [prisma/prisma#21202]
### Bug description

Hello, I am new to Prisma and I have encountered this bug which confuses me completely. 
I am new to GIthub discussions overall, so if something isnt clear, elt me know. 

While trying to create a new record in the table, Prisma returns this strange error. 

Operation 'createOne' for model 'Session' does not match any query.

I have checked the syntax in invocation and model, but everything seems correct.
I have tried deleting cache, renaming and recreating, it keeps happening.

### Expected behavior

Successfully created record in the session table

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.sqlite"
}

model User {
  id        Int     @id @default(autoincrement())
  name      String? //for some reason It must in this model
  email     String  @unique
  username  String
  password  String
}

model Session {
  sessionID   String @unique
  userID      Int    
  expiration  Int? 
}

```

```js
        try {
            const user = await prisma.user.findUnique({
                where: {
                  email,
                },
            });

            if (user.password == password) {
                console.log("Authorized");

                const userID = user.id
                const sessionID = generateSessionID()

                await prisma.session.create({       //save sessionID in db
                    data: {
                        sessionID,
                        userID
                    },
                })

            } else {
                //goes to catch block
            }

        } catch (err) {
            console.log(err)
            return fail(401, {message: 'Authorization failed.'})
        }
```

PrismaClientUnknownRequestError: 
Invalid `prisma.session.create()` invocation:

Operation 'createOne' for model 'Session' does not match any query.
    at wn.handleRequestError (C:\study\cocktailApp\node_modules\@prisma\client\runtime\library.js:123:6902)
    at wn.handleAndLogRequestError (C:\study\cocktailApp\node_modules\@prisma\client\runtime\library.js:123:6119)
    at wn.request (C:\study\cocktailApp\node_modules\@prisma\client\runtime\library.js:123:5839)
    at async l (C:\study\cocktailApp\node_modules\@prisma\client\runtime\library.js:128:9763)
    at async login (C:/study/cocktailApp/src/routes/login/+page.server.js:39:17)
    at async Module.handle_action_json_request (C:/study/cocktailApp/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:57:16)
    at async resolve (C:/study/cocktailApp/node_modules/@sveltejs/kit/src/runtime/server/respond.js:415:18)
    at async Object.handle (C:/study/cocktailApp/src/hooks.server.js:13:22)
    at async Module.respond (C:/study/cocktailApp/node_modules/@sveltejs/kit/src/runtime/server/respond.js:282:20)
    at async file:///C:/study/cocktailApp/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:505:22 {
  clientVersion: '5.3.1'
}

### Environment & setup

- OS: Windows
- Database: SQLite
- Node.js version: v16.16.0

### Prisma Version

```
prisma                  : 5.3.1
@prisma/client          : 5.3.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.1-2.61e140623197a131c2a6189271ffee05a7aa9a59
Default Engines Hash    : 61e140623197a131c2a6189271ffee05a7aa9a59
Studio                  : 0.494.0
```

**Comment by Jolg42** [comment]
This is strange, and we need to try to reproduce it 🤔 

Are you sure your schema and generated client are in sync? Run `npx prisma generate` again and try again to see if that's the case.

**Comment by mamqek** [comment]
Yes, they are synced I believe. 
After each change in schema I run npx prisma db push and npx prisma generate
However I also get this error every time EPERM: operation not permitted, unlink 'C:\study\cocktailApp\node_modules\.prisma\client\query_engine-windows.dll.node'

Also I have tried reinstalling , nothing changed

I tried changing from sqlite to supabase, and cahnged the schema by an example from youtube, now it doesnt even recognize commands
TypeError: Cannot read properties of undefined (reading 'findMany')
TypeError: Cannot read properties of undefined (reading 'create')

I have checked User table works correctly, besides I dont see data in the Supabase webclient.

## New schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  // url      = "file:./dev.mysql"
}

model User {
  id        Int     @id @default(autoincrement())
  name      String? //for some reason It must in this model
  email     String  @unique
  username  String
  password  String
  session Session[]

  @@map("user")
}

model Session {
  id          String @id @unique
  userID      Int    
  // active_expires BigInt
  // idle_expires BigInt
  user User @relation(references: [id], fields : [userID], onDelete : Cascade)

  @@index([userID])
  @@map("session")
}

## Code to crash
        try {

            await prisma.user.create({
                data: {
                    email, 
                    username, 
                    password
                },
            })
            console.log("here");
            console.log(await prisma.session.findMany())        //this line doesnt work


            const userID = 1
            console.log(userID);
            const id = generateSessionID()

            await prisma.session.create({       //save sessionID in db           //and ofc this one
                data: {
                    id,
                    userID, 
                    
                },
            })

        } catch (err) {
            console.log(err)
            if (err.code === 'P2002') {
                return fail(409, {message: 'User with this email already exists'})
            }
            return fail(500, {message: 'Could not create the user.'})
        }

## Loading 

I do this project in Sveltekit and load prisam client in lib folder, mb thats the issue 
import { PrismaClient } from "@prisma/client";

const prisma = global.prisma || new PrismaClient()

if (process.env.Node_ENV === "development") {
    global.prisma = prisma
}

export { prisma }

**Comment by mamqek** [comment]
I tried reproducing, however it just worked there. 
I tried literally same proccess on the main project and now it works. 

My proccess:
1. Delete prisma folder
2. npm install @prisma/client
3. Insert db url in schema
4. prisma db pull
5. prisma generate

If I would do the same without deleting the folder it wouldn't work.

**Comment by cubu** [comment]
I have the same error for a slightly different use case. When i changed from SQLite to PostgreSQL, the error was gone. Seem that it only happens with SQLite. So, if someone is stuck with this case, consider using the real database instead of SQLite.

**Comment by amirhosseinkhoobru** [comment]
Hi is there anyone that can help me? 
.......
 ⨯ PrismaClientUnknownRequestError: 
Invalid `prisma.product.create()` invocation:


Operation 'createOne' for model 'Product' does not match any query.
    at Cn.handleRequestError (C:\Users\javad\OneDrive\Desktop\next-js\next-mosh\node_modules\@prisma\client\runtime\library.js:123:6989)
    at Cn.handleAndLogRequestError (C:\Users\javad\OneDrive\Desktop\next-js\next-mosh\node_modules\@prisma\client\runtime\library.js:123:6206)
    at Cn.request (C:\Users\javad\OneDrive\Desktop\next-js\next-mosh\node_modules\@prisma\client\runtime\library.js:123:5926)
    at async l (C:\Users\javad\OneDrive\Desktop\next-js\next-mosh\node_modules\@prisma\client\runtime\library.js:128:9968)
    at async POST (webpack-internal:///(rsc)/./app/api/products/route.ts:25:24)
    at async C:\Users\javad\OneDrive\Desktop\next-js\next-mosh\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:62499 {
  clientVersion: '5.5.2'
}
 ⨯ PrismaClientUnknownRequestError: 
Invalid `prisma.product.findMany()` invocation:


Operation 'findMany' for model 'Product' does not match any query.
    at Cn.handleRequestError (C:\Users\javad\OneDrive\Desktop\next-js\next-mosh\node_modules\@prisma\client\runtime\library.js:123:6989)
    at Cn.handleAndLogRequestError (C:\Users\javad\OneDrive\Desktop\next-js\next-mosh\node_modules\@prisma\client\runtime\library.js:123:6206)
    at Cn.request (C:\Users\javad\OneDrive\Desktop\next-js\next-mosh\node_modules\@prisma\client\runtime\library.js:123:5926)
    at async l (C:\Users\javad\OneDrive\Desktop\next-js\next-mosh\node_modules\@prisma\client\runtime\library.js:128:9968)
    at async GET (webpack-internal:///(rsc)/./app/api/products/route.ts:14:22)
    at async C:\Users\javad\OneDrive\Desktop\next-js\next-mosh\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:62499 {
  clientVersion: '5.5.2'
}
.......

idk why this happend
prisma worked for the other model for me but the new one that i created has this problem
btw im using MySQL as the database
please help me...

**Comment by Jolg42** [comment]
@amirhosseinkhoobru please create a new issue about this since this issue is now closed.
What you could try is to run `npx prisma generate` to make sure you generated Prisma Client is updated. Let us know if that didn't help in the new issue.

**Comment by amirhosseinkhoobru** [comment]
Heyyyy!!!
It worked...
as soon as i run that command it worked 
thanks a lot!
