### ISSUE TITLE
Document AWS lambda configuration to avoid timeouts

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#2121]
We should document https://github.com/prisma/prisma/issues/1754#issuecomment-601271228
Maybe in https://www.prisma.io/docs/guides/deployment/deploying-to-aws-lambda and in nexus too?

In the issue above the solution was to do this:
```
// Set to false to send the response right away when the callback executes, instead of waiting for the Node.js event loop to be empty.
context.callbackWaitsForEmptyEventLoop = false;
```

**Comment by matthewmueller** [comment]
context: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html
