### ISSUE TITLE
`prisma_pool_connections_idle` reports misleading number

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#21221]
https://github.com/importcjj/mobc/issues/82

**Comment by janpio** [comment]
https://github.com/importcjj/mobc/pull/86 happened 👀

**Comment by silentroach** [comment]
after upgrade to 5.6.0 our idle counter looks like this (with connection_limit = 10):

```
prisma_pool_connections_busy{app="xxx"} 0
prisma_pool_connections_idle{app="xxx"} 201
prisma_pool_connections_open{app="xxx"} 10
```

**Comment by janpio** [comment]
Hmm, are you seeing a regression or continued bug here @silentroach? If so, could you open a _new_ issue so we can potentially reproduce this and figure out what is going on? (WIth a new issue, others are also more probably to chime in.) Thanks!
