### ISSUE TITLE
`db pull --force` errors with `error: Key \"fileNamingStyle\" is already defined in generator \"nestjsDto\"...`

### ISSUE THREAD

**Issue by HaeMinJ** [prisma/prisma#21226]
Hi Prisma Team! The following command just crashed.

## Command

`db pull --force`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v18.12.1           | 
| Prisma CLI  | 5.0.0              | 
| Engine      | 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584| 

## Error
```
RustPanic: Error in Schema engine.
Reason: [schema-engine/connectors/schema-connector/src/introspection_context.rs:51:76] called `Result::unwrap()` on an `Err` value: "error: Key \"fileNamingStyle\" is already defined in generator \"nestjsDto\".\n  -->  schema.prisma:19\n   | \n18 |   entitySuffix                    = \"\"\n19 |   fileNamingStyle                 = \"camel\"\n   | \n"

```

**Comment by Jolg42** [comment]
Hi @HaeMinJ 
Could you share your Prisma schema so we can try a reproduction?

**Comment by HaeMinJ** [comment]
@Jolg42 
Sorry for my late check.
Because I'm using prisma for real-time business, I can't share our schema. ( security issue.. )
But, it would be generator issue becuase I am using custom generator library.

So now, we're fine. Thank you for your effort.
