### ISSUE TITLE
error in migration engine when running `npx prisma migrate dev`

### ISSUE THREAD

**Issue by gabrielforster** [prisma/prisma#21245]
Hi Prisma Team! The following command just crashed.
While running the migration it fails, but when running a migration again it applies the failed one. Kinda strange.
## Command

`migrate dev`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-3.0.x| 
| Node        | v14.18.3           | 
| Prisma CLI  | 4.5.0              | 
| Engine      | 0362da9eebca54d94c8ef5edd3b2e90af99ba452| 

## Error
```
Error: Error in migration engine.
Reason: [/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/89d208e/src/connector/result_set/result_row.rs:59:64] index out of bounds: the len is 1 but the index is 10

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by aqrln** [comment]
Hi @gabrielforster, could you please provide more information for reproduction? What is the database that you are using? Does the issue happen consistently or did it happen just once? Any chance you could provide us a reproduction?

**Comment by gabrielforster** [comment]
Im using a MySQL database and it happens every time I try to run a migration.

Every time I try to run a migration, this migration fails. Then, if I try to run a new migration, the failed one is applied correctly to the database and the new one fails just like the other one.

**Comment by gabrielforster** [comment]
Hi @aqrln. Im using a MySQL database and it happens every time I try to run a migration.

Every time I try to run a migration, this migration fails. Then, if I try to run a new migration, the failed one is applied correctly to the database and the new one fails just like the other one.

**Comment by aqrln** [comment]
@gabrielforster could you provide your schema for reproduction? Also, what MySQL version are you using?

**Comment by gabrielforster** [comment]
@aqrln Actually I cant provide the schema. But the MySQL version is the 5.7.0

**Comment by Jolg42** [comment]
Thanks, unfortunately without the schema we would not have enough to try a reproduction.

If this still happens on a recent version of Prisma, let us know via a new issue, if sharing the schema publicly is an issue, we can arrange a private exchange.

**Comment by gabrielforster** [comment]
@Jolg42 sure mate. Thanks.

If it happens again I'll let u know
