### ISSUE TITLE
Document multiple filters are joined via `AND` on top level

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#2126]
Consider the following query:
```js
prisma.table.findMany({
    where: { AND: [{ startNum: { lte: 1000 } }, { endNum: { gte: 1000 } }] },
  });
```

It can be simplified to the following:
```js
prisma.table.findMany({
  where: { startNum: { lte: 1000 }, endNum: { gte: 1000 } },
});
```

It is because logical `AND` is the default behaviour to combine multiple filters.

We should document this.

**Comment by mhwelander** [comment]
Documented with an example (same query, two different formats) + in the reference table : https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering#combine-multiple-filter-conditions
