### ISSUE TITLE
[Beta1]Optional value with foreign key failed to create

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/prisma#2131]
Env:
Beta1, Win10 WSL2, Mysql

![image](https://user-images.githubusercontent.com/3894825/78748102-b4e5b200-799d-11ea-83ee-c6d542165206.png)
VSCode Hints: 
Error validating: The relation field `user` uses the scalar fields userId. The arity of those fields must be the same. The relation field is optional but the scalar fields are required.

Removing the "?" everything just fine.

**Comment by Sytten** [comment]
Add a `?` to the userId, if ou want an optional relation your column in SQL also needs to be nullable ;)

**Comment by pantharshit00** [comment]
Yes, the relational scalar `userId` also needs to be nullable as pointed out by @Sytten.

Try installing `beta.2`, that should give you a proper validation error for this.

**Comment by zzyyzz1992** [comment]
@Sytten  @pantharshit00  Thanks a lot!
