### ISSUE TITLE
Official Prisma support for Serverless Aurora

### ISSUE THREAD

**Issue by jonthewayne** [prisma/prisma#2133]
## Problem
I'd like to use AWS' Serverless Aurora, but it is only available with MySQL 5.6.10a compatibility and Prisma doesn't support that officially.

Also, Serverless Aurora can only be run behind a VPC, so when you are writing AWS Lambda functions for instance, they need to be in the same VPC to access the database. Example: https://hackernoon.com/a-crash-course-on-serverless-with-aws-building-apis-with-lambda-and-aurora-serverless-49885c46e37a

We don't have good guidance for how to connect to and manage Serverless Aurora with Prisma.

## Solution
Full tests and official support for Serverless Aurora's MySQL 5.6.10a, and specifically good docs on how to connect to Serverless Aurora.

**Comment by schickling** [comment]
Related: https://github.com/prisma/prisma/issues/1964

**Comment by tomhoule** [comment]
I worked on this, and now the engines should work fine with serverless aurora mysql.

Details of what I did:

- Added MySQL 5.6 to our CI tests and fixed what did not work (https://github.com/prisma/prisma-engines/pull/660)
-  Sadly there is no serverless aurora docker image we could spin up in CI, but we did create an instance and I ran the test suite there

So from the prisma engines side, we are pretty confident it will work now. Ideally someone would confirm this the whole prisma-client stack :)

**Comment by jonthewayne** [comment]
Seriously amazing work, thank you!

**Comment by jonthewayne** [comment]
Would I need to wait for an official release in the prisma cli to use this?

**Comment by tomhoule** [comment]
@prisma/cli@alpha has the fixes, and but not yet `beta.2`. It will be in `beta.3`.

**Comment by jonthewayne** [comment]
@tomhoule were you able to connect to your aurora serverless db with a normal connection url per the usual? Or did it require a custom setup? Lack of a normal connection url has been a problem in the past.

**Comment by tomhoule** [comment]
It was with a normal mysql connection URL - it had to be done from a VM inside the VPC though, it wasn't exposed to the internet.

**Comment by janpio** [comment]
`2.0.0-beta.3` was released today 🚀

**Comment by jonthewayne** [comment]
@tomhoule quick followup about connecting to serverless aurora from a VM inside the VPC: is there a way to do this and still be able to use the CLI and Prisma Studio from my local machine?

**Comment by tomhoule** [comment]
I haven't done very in-depth research, but from the [AWS docs](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html#aurora-serverless.limitations),

>  You can't give an Aurora Serverless DB cluster a public IP address. You can access an Aurora Serverless DB cluster only from within a virtual private cloud (VPC) based on the Amazon VPC service.

So you would have to run the CLI from inside the VPC. I imagine tunneling through a VPN would also work.

**Comment by PerfectedApp** [comment]
As @Tomhoule suggested is more of less what we have done. We created a bastion server where we SSH tunnel into the box mapping the RDS instance locally. We then able to run all prisma commands and work locally. Production db endpoint is just updated to the VPC network we deploying.

**Comment by jonthewayne** [comment]
@PerfectedApp This sounds awesome, do you by any chance have notes on how exactly to set this up?

**Comment by PerfectedApp** [comment]
@johannesschobel, notes on how to set up the bastion server on AWS are probably a case-by-case situation of how the VPC is setup and levels of security one wishes to enforce.

If you have a Ubuntu box for the bastion server, you can just tunnel into the box with port mapping.

First, download the PEM key from AWS

**Linux/Mac:** 

1. chmod 600 thePemFile.pem
2. ssh  -i /path/to/bastion.pem ubuntu@ipOfBastionBox -L3307:someaddress.rds.amazonaws.com:3306 -N


**Windows:** 

1. You need to convert the pem file into ppk format for PuTTY. Please see here or other Google search sources (https://tecadmin.net/convert-pem-to-ppk-via-putty/)
2. (plink via Putty):
plink.exe -i "bastion.ppk" ubuntu@ipOfBastionBox -L 3307:someaddress.rds.amazonaws.com:3306 -N

**Comment by janpio** [comment]
We should reproduce the setup @PerfectedApp described in https://github.com/prisma/prisma/issues/2133#issuecomment-623294910 and document this.

**Comment by medv** [comment]
We are using Serverless Aurora Data API, which can be used from outside of the database VPC. This allows us to deploy lambda@edge functions to all 160+ CloudFront locations with server logic that can serve from the closest Serverless Aurora available (lambda@edge functions cannot be placed in a VPC, and funneling requests through an additional machine are extra points of failure).

Resources:
lambda@edge server-side logic deployments - https://github.com/danielcondemarin/serverless-next.js
vanilla data-api-client - https://www.npmjs.com/package/data-api-client
typeorm + data-api-client driver - https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver

**Comment by jonthewayne** [comment]
@medv using lambda at the edge is a really good reason to use a solution that doesn't require a VPC, I didn't consider that! I believe I've heard that supporting the data API is on the Prisma roadmap. Like you, I'm hoping that happens soon!

**Comment by janpio** [comment]
@medv We are tracking the Aurora Data API support in https://github.com/prisma/prisma/issues/1964 You might want to add your use case in there as well for completeness (or link to your comment here over there).

**Comment by matthewmueller** [comment]
Closing in favor of #1964.
