### ISSUE TITLE
5.4.0 subquery has too many columns

### ISSUE THREAD

**Issue by ShoppasGit** [prisma/prisma#21356]
### Bug description

After I updated to 5.4.0 I am now getting the error below.

```
return this.prisma.serviceVisit.findMany(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42601", message: "subquery has too many columns", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
```

### How to reproduce

Run find first with many related objects.

### Prisma information

```
return this.prisma.serviceVisit.findFirst({
      where: {
        tenantId,
        serviceVisitWorkers: {
          some: {
            statusRef: {
              inProcess: true,
            },
            workerId,
          },
        },
      },
      include: {
        statusRef: true,
        customer: true,
        timeSheets: {
          include: {
            worker: true,
            activityCode: true,
            workOrderSegment: true,
          },
        },
        serviceVisitWorkers: {
          include: {
            statusRef: {
              include: {
                activityCodeRef: true,
              },
            },
            worker: {
              include: {
                user: true,
              },
            },
          },
        },
        serviceVisitWorkOrders: {
          include: {
            workOrder: {
              include: {
                WorkOrderSegments: true,
              },
            },
          },
        },
      },
    });
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
5.4.0
```

**Comment by millsp** [comment]
Hey @ShoppasGit could you please share your schema and a reproducible piece of code, thanks.

**Comment by janpio** [comment]
Thanks for opening the issue @ShoppasGit. This looks quite severe, especially if it worked fine in 5.3.x - so we are eager to reproduce and understand.

Can you please also enable [query logging](https://pris.ly/d/logging) so the affected query is output?
You are using PostgreSQL (according to the error message), but which version?
Most important and relevant for us would be to have the underlying Prisma Schema that you run this query against. Can you share that with us?

**Comment by ShoppasGit** [comment]
> Thanks for opening the issue @ShoppasGit. This looks quite severe, especially if it worked fine in 5.3.x - so we are eager to reproduce and understand.
> 
> Can you please also enable [query logging](https://pris.ly/d/logging) so the affected query is output? You are using PostgreSQL (according to the error message), but which version? Most important and relevant for us would be to have the underlying Prisma Schema that you run this query against. Can you share that with us?

Thank you for the quick response!
I am using AWS RDS Postgres 13.10.
My current Prisma schema is 2.7k lines long. Is that something I should post here in its entirety?

**Comment by benweissmann** [comment]
I'm also experiencing this in 5.4 -- it popped up in our unit tests on a PR to upgrade prisma, so I'm pretty confident it's related to the new version (since there were no code changes in that branch, just a prisma update). Our schema is also pretty long, but the query that's failing is using a `where` clause filtering on a relation, and that relation is using a composite foreign key. The generated SQL has a subquery along the lines of:

```sql
SELECT * FROM source_table
WHERE (tenantId, id) IN (
  SELECT id FROM target_table WHERE ...
)
```

And there is a foreign key from `source_table(tenantId, id) -> target_table(tenantId, id)`. The issue is that the subquery is selecting just `id`, rather than the `tenantId, id` required for the join on the composite key.

**Comment by pmuens** [comment]
As another data point I'm also seeing this (using PostgreSQL via AWS RDS).

I downgraded to `5.3.1` which solved the problem for now.

**Comment by millsp** [comment]
Hey @ShoppasGit, @benweissmann, @pmuens, the fix has been published as part of https://github.com/prisma/prisma/releases/tag/5.4.2. Please give it a try and let us know if anything is off. Thanks!
