### ISSUE TITLE
Prisma client still looks for query engine when using planetscale serverless driver

### ISSUE THREAD

**Issue by arturenault** [prisma/prisma#21376]
So excited that you guys added support for the planetscale serverless driver! We hope this can help us kill the cold start issues we've been hitting with prisma.

However when I deployed to AWS Lambda (not @Edge) I get an error because it looks like prisma is still looking for the query engine for the rhel runtime.

Here's the relevant part of my schema.prisma:
```
datasource db {
    provider     = "mysql"
    url          = env("PLANETSCALE_URL")
    relationMode = "prisma"
}

generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["driverAdapters"]
}
```

Here's the error I'm getting:
```
  /home/circleci/project/node_modules/.pnpm/@prisma+client@5.4.1_prisma@5.4.1/node_modules/@prisma/client
  /tmp/prisma-engines","reason":{"errorType":"PrismaClientInitializationError","errorMessage":"Prisma Client could not locate the Query Engine for runtime \"rhel-openssl-1.0.x\".

This happened because Prisma Client was generated for \"debian-openssl-3.0.x\", but the actual deployment required \"rhel-openssl-1.0.x\".
Add \"rhel-openssl-1.0.x\" to `binaryTargets` in the \"schema.prisma\" file and run `prisma generate` after saving it:

generator client {
  provider      = \"prisma-client-js\"
  binaryTargets = [\"native\", \"rhel-openssl-1.0.x\"]
}

The following locations have been searched:
  /var/task/node_modules/.prisma/client
  /var/task/node_modules/@prisma/client
```

Let me know if I'm missing something or if I'm misunderstanding this feature

**Comment by janpio** [comment]
Hi @arturenault, the query engine is still required as it turns your Prisma Client query into the SQL query - and then transforms the returned data into a shape that Prisma Client can understand and return to your application. (We will change in the future what kind of Query Engine that is, and for example, make it smaller and lightweight).

If you have any "cold start problems", then we would love to know about them and help you understand what is going on. Our Query Engine itself is most probably not the problem (although it is pretty big). Usually, the creation of the database connection itself is what takes a lot of time on the first start of your application and first query. (Depending on how you see it, you can also wrap that into the "cold start".) With the PlanetScale Serverless Driver, Prisma will not handle any connections any more and hence that will not be a concern at all. PlanetScale manages the connections on their (proxy) server that sits in front of the database.

**Comment by arturenault** [comment]
Ah I understand the feature better now - this definitely still sounds like an improvement. However I'm not sure it'll be enough to fix our cold start issues. 

For context, we're developing a Discord integration, and Discord requires responses within 3 seconds or the user will see an error.

Here's a datadog trace from yesterday, before we had the planetscale driver enabled:
<img width="1294" alt="Screenshot 2023-10-05 at 12 26 18 PM" src="https://github.com/prisma/prisma/assets/2919473/e7c59693-4962-45d8-bdf4-9d17ba18260c">

Total trace time: 3.66s
Lambda cold start: 1.98s
Lambda execution: 1.03s

And here's one from today, with the planetscale driver:
<img width="1306" alt="Screenshot 2023-10-05 at 12 28 40 PM" src="https://github.com/prisma/prisma/assets/2919473/8ed29f91-2519-4511-acaf-fb0b55a7e862">

Total trace time: 3.44s
Lambda cold start: 1.82s
Lambda execution: 557ms

It does look like the Planetscale driver cut down the execution time (which is when the connection would happen) in half. But most of the time is coming from the Lambda cold start itself. 

Definitely need a bit more investigation to blame it squarely on the execution engine size - but I do know that we didn't have cold start issues before switching to Prisma (from drizzle with the serverless driver). 

I can rearchitect the service to not have to use Prisma at the beginning, but was hoping the driver would help me avoid this :) 

Thanks for your help!

**Comment by janpio** [comment]
Awesome, important that it works now.
We'll figure out any potential cold start problems in another channel and create an issue if we find a problem.
