### ISSUE TITLE
Migration using jsonb_set fails

### ISSUE THREAD

**Issue by vedantroy** [prisma/prisma#21406]
### Bug description

Valid SQL (according to ChatGPT) is failing when put into a prisma migration.

### How to reproduce

Add the following to a migration:
```
-- This is an empty migration.
UPDATE user SET data = jsonb_set(data, '{tier}', '"free"') WHERE NOT data ? 'tier';
UPDATE user SET credits = 2000;
```

### Expected behavior

It should succeed

### Prisma information

Relevant subset
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["metrics"]
  // previewFeatures = ["metrics", "tracing"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  data           Json
  credits      Int
}
```

### Environment & setup

PostgreSQL, Ubuntu, Node 20

### Prisma Version

```
prisma                  : 5.3.1
@prisma/client          : 5.3.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.1-2.61e140623197a131c2a6189271ffee05a7aa9a59
Default Engines Hash    : 61e140623197a131c2a6189271ffee05a7aa9a59
Studio                  : 0.494.0
Preview Features        : metrics
```

**Comment by janpio** [comment]
What error do you get?
Did you try to run the SQL against a database manually?

**Comment by millsp** [comment]
@vedantroy  did you see the message from @janpio ? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by SevInf** [comment]
Hey @vedantroy ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
