### ISSUE TITLE
Enum migration guide

### ISSUE THREAD

**Issue by Huvik** [prisma/prisma#2141]
# Enum migration guide

**What feature are you missing?**
Enum migration guide, because when you have some enum in Prisma and rename it. Prisma get stuck on this record, you can't read or update the only possibility is to delete this record. 

**How could this feature look like in detail? Tradeoffs?**
Provide some information in docs. For example first you add new enum -> deploy -> update -> remove old enum

**Comment by marktani** [comment]
This also sounds like an underlying problem that is either a bug or a feature. How could we make enum migration better?

**Comment by nikolasburk** [comment]
Is this still a valid issue @Huvik and @marktani?

**Comment by Huvik** [comment]
I didn't test it, but in migration https://www.prisma.io/docs/data-model-and-migrations/migrations-asdf/ there is nothing about it

**Comment by nikolasburk** [comment]
Ok then, I just tested renaming an Enum using the `@rename` directive and it worked without problems. Will close the issue, thanks a lot @Huvik 🙌
