### ISSUE TITLE
Query by unique constraint missing included properties

### ISSUE THREAD

**Issue by larry-yarian-traction** [prisma/prisma#2141]
## Bug description

I recently upgrade from 2.0.0-beta.1 to 2.0.0-beta.2 and I'm now running into a Typescript compilation issue after re-generating the client (prisma-client-js generator).

The error occurs when using a unique constraint defined on a model to perform a query, including some relations in the result.  If I use the `@id` of the model to perform the query, the error is not observed.  (Both are provided in the attached sample).

## How to reproduce

See the attached for a [sample](https://github.com/prisma/prisma/files/4453095/sample.zip).

1.  `yarn install && yarn gen`
2.  Open the `permissions.ts` file or the _Problems_ window in VS Code
3.  See error (line 18 of the file)

## Expected behavior

The generated Typescript type definition file is correct given the `include` specified in the query

## Prisma information

See [sample](https://github.com/prisma/prisma/files/4453095/sample.zip) for schema and queries

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.2
- Node.js version: 13.11.0

**Comment by pantharshit00** [comment]
I can confirm this. This is a regression possibly caused by https://github.com/prisma/prisma-client-js/issues/607

Schama from the zip:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("POSTGRESQL_URL")
}

model tenant {
  id         String       @default(dbgenerated()) @id
  name       String
  ownerId    String
  tenantUser tenantUser[]
}

model tenantUser {
  id              String           @default(dbgenerated()) @id
  isActive        Boolean          @default(true)
  tenantId        String
  userId          String
  tenant          tenant           @relation(fields: [tenantId], references: [id])
  user            user             @relation(fields: [userId], references: [id])
  userPermissions userPermission[]

  @@unique([tenantId, userId], name: "authorizedUser")
}

model user {
  emailAddress String         @unique
  firstName    String
  id           String         @default(dbgenerated()) @id
  lastName     String
  tenant       tenant[]
  tenantUser   tenantUser[]
}

model userPermission {
  permission   String
  tenantUserId String
  tenantUser   tenantUser @relation(fields: [tenantUserId], references: [id])

  @@id([tenantUserId, permission])
}

```

Code that reproduces the issue:
```js
  const user = await client.tenantUser.findOne({
    where: {
      authorizedUser: {
        tenantId: '',
        userId: ''
      }
    },
    include: {
      userPermissions: true
    }
  })

  return user.userPermissions.map(perm => perm.permission)

```

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

For the record: This issue originated in the same bug as what has been reported in https://github.com/prisma/prisma/issues/2141
