### ISSUE TITLE
prisam:warn Prisma doesn't know which engines to download for the Linux distro "deepin". Falling back to Prisma engines built "debian".

### ISSUE THREAD

**Issue by James-Wuguoqing** [prisma/prisma#21426]
### Bug description

prisma:warn Prisma doesn't know which engines to download for the Linux distro "deepin". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by janpio** [comment]
Reported before: https://github.com/prisma/prisma/issues/18374
