### ISSUE TITLE
[Feature request] Prisma Accelerate Automatic Cache Re-validation

### ISSUE THREAD

**Issue by ihadabs** [prisma/prisma#21442]
Automatic cache re-validation

**Our use case is:**

We have a very expensive query
```ts
/// ttl = 5 mins, swr = 1 day
cacheStrategy: { ttl: 60 * 5, swr: 60 * 60 * 24 }

/// note that swr could be infinity; as long as Accelerate will try to re-validate it after ttl expires
```

but the problem is when the user revisits the query  lets say 2 hours later they will get data that is 2 hours old (becuase of `swr =  1 day`)

i know that we can set swr to a smaller value but we don't want the user to wait :)

so what Prisma Accelerate could have:
1. Option to make swr = infinity
2. Automatic re-validation every some time (like Next ISR)
3. Option to skip cache / force compute

new:
```ts
{
  cacheStrategy: {
     ttl: 60 * 5 // 5 mins

     /// Cache can be served forever
     swr: 'forever'
     
     /// This is handled in Accelerate infra
     /// cron every 10 mins
     revalidate: 60 * 10
     /// In case user was no active anymore
     /// we don't revalidate forever
     /// stop if no visits for 10 days
     revalidateStop: 60 * 60 * 24 * 10

     /// In case we want to force call to db
     skipCache: true | undefined
  }
}
```

This way the user will never wait after first call :rocket:

*Teams can have their own logic to avoid even first call; and call perform the query before the user actually needs it*

This way the user will never wait :rocket::birdyes:
```[tasklist]
### Tasks
```

**Comment by nurul3101** [comment]
Hello @ihadabs 👋 

Thank you for trying out Prisma Accelerate and for conveying your feature request to us.

Your suggestion has been relayed to our product team. We will ensure to get in touch with you as soon as we have an update on this. However, I'll be closing this GitHub Issue as this repository primarily caters to Prisma ORM issues and feature requests rather than concerns pertaining to Prisma Accelerate.

**Comment by bambrose24** [comment]
It's worth noting that Nextjs ISR actually doesn't do what you're describing — if SWR is 1 day, and 2 days later it's requested, it'll server the stale data and start rebuilding. But I do wish that both Nextjs and Prisma Accelerate would be able to manage this for us!
