### ISSUE TITLE
Regression for MongoDB introspection in 5.4.0

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#21441]
### Bug description

Regression introduced by https://github.com/prisma/prisma-engines/pull/4253 (for bounty issue https://github.com/prisma/prisma/issues/20037) in MongoDB Introspection highlighted in the following [commit](https://github.com/prisma/introspection-ci/commit/a195529619a0e86a429f86b0ecbc8908cdb0647e#diff-c501b366526ef45fef1b41bd31ec3fe538f6e0f7dbdfd95bd14344f116514294)
A formerly valid introspected Prisma schema for MongoDB is now considered invalid.

### How to reproduce

- `npx prisma db pull --force` on
	- [sample_mflix.log](https://github.com/prisma/introspection-ci/blob/a195529619a0e86a429f86b0ecbc8908cdb0647e/introspection-analysis/output/mongodb_public/sample_mflix.log)
	- [sample_airbnb.log](https://github.com/prisma/introspection-ci/blob/a195529619a0e86a429f86b0ecbc8908cdb0647e/introspection-analysis/output/mongodb_public/sample_airbnb.log)	

See [errors](https://github.com/prisma/introspection-ci/commit/a195529619a0e86a429f86b0ecbc8908cdb0647e#diff-c501b366526ef45fef1b41bd31ec3fe538f6e0f7dbdfd95bd14344f116514294)
```
Error: Prisma schema validation - (validate wasm)
Error code: P1012
error: Error parsing attribute "@@index": Indexes can only contain scalar attributes. Please remove "location" from the argument list of the indexes.
  -->  schema.prisma:125
   | 
124 |   @@index([name], map: "name_1")
125 |   @@index([address.location], map: "address.location_2dsphere")
   | 
```

```
Error: Prisma schema validation - (validate wasm)
Error code: P1012
error: Error parsing attribute "@@index": Indexes can only contain scalar attributes. Please remove "geo" from the argument list of the indexes.
  -->  schema.prisma:113
   | 
112 | 
113 |   @@index([location.geo], map: "geo index")
   | 
```

### Prisma Version

```
5.4.0
```

**Comment by Druue** [comment]
Yep, I can confirm this is the case.

## Example schema with bare Composite Type
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

type TheatersLocationGeo {
  coordinates Float[]
  type        String
}

model theaters {
  id        String           @id @default(auto()) @map("_id") @db.ObjectId
  locationGeo  TheatersLocationGeo
  theaterId Int

  @@index([locationGeo], map: "geo index")
}
```

## VSCode Error
Viewing this schema with the extension for `v5.3.0` yields no squiggly
Updating the extension to be aligned with `v5.5.2` yields the following error:
```prisma
model theaters {
  id        String           @id @default(auto()) @map("_id") @db.ObjectId
  locationGeo  TheatersLocationGeo
  theaterId Int

  @@index([locationGeo], map: "geo index")
  //      ^^^^^^^^^^^^
  // Error parsing attribute "@@index":
  // Indexes can only contain scalar attributes.
  // Please remove "locationGeo" from the argument list of the indexes.
  // ! This error only shows up on v5.5.2 !
}
```

## Generate
This can also be confirmed with `npx prisma generate` (or `npx prisma db push` as it uses `generate` under the hood)
`npx prisma -v` : `v5.3.0`
![image](https://github.com/prisma/prisma/assets/29753584/756c3abe-0cfe-4e53-901b-7dd1410d79b3)
`npx prisma -v` : `v5.5.2`
![image](https://github.com/prisma/prisma/assets/29753584/6ae14917-9b82-40e5-b39c-59fa14f7d1bc)

---

## Alternate Example Schema with nested Composite Type
The same can _also_ be seen with the following example schema
```prisma
type TheatersLocation {
  address TheatersLocationAddress
  geo     TheatersLocationGeo
}

type TheatersLocationAddress {
  city    String
  state   String
  street1 String
  street2 String?
  zipcode String
}

type TheatersLocationGeo {
  coordinates Float[]
  type        String
}

model theaters {
  id        String           @id @default(auto()) @map("_id") @db.ObjectId
  location  TheatersLocation
  theaterId Int

  @@index([location.geo], map: "geo index")
  //       ^^^^^^^^^^^^
  // Error parsing attribute "@@index":
  // Indexes can only contain scalar attributes.
  // Please remove "geo" from the argument list of the indexes.
}
```

---

[notion doc](https://www.notion.so/prismaio/Regression-for-MongoDB-in-5-4-0-3a8040b3a2544ec1b9db72a3a47fb1c7)

**Comment by Druue** [comment]
Note: I used `@@index()` in my message above however, looking at the original crash report, this error on `generate` only triggers in an `@@unique()` _not_ an `@@index()`
i.e.

This crashes
```prisma
model Post {
  id         String      @id @default(auto()) @map("_id") @db.ObjectId
  author     User        @relation(fields: [authorId], references: [id])
  authorId   String      @db.ObjectId
  attributes Attribute[]

  @@unique([authorId, attributes])
}

model User {
  id   String @id @default(auto()) @map("_id") @db.ObjectId
  Post Post[]
}

type Attribute {
  name  String
  value String
  group String
}
```

This does _not_
```diff
model Post {
  id         String      @id @default(auto()) @map("_id") @db.ObjectId
  author     User        @relation(fields: [authorId], references: [id])
  authorId   String      @db.ObjectId
  attributes Attribute[]

-  @@unique([authorId, attributes])
+  @@index([authorId, attributes])
}

model User {
  id   String @id @default(auto()) @map("_id") @db.ObjectId
  Post Post[]
}

type Attribute {
  name  String
  value String
  group String
}
```
