### ISSUE TITLE
Prisma CLI built as binary with pkg download binary behaviour

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#2148]
I'm setting custom engine paths using environment variables. However, it seems that Prisma is still downloading binaries.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/5013932/78909636-07ae8f00-7aae-11ea-826b-6fb9786dcb71.png">

## How to reproduce

prisma/schema.prisma

```schema.prisma
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

generator client {
  provider = "go run github.com/prisma/prisma-client-go"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

Download Go: `brew install go`

```
mkdir test
cd test

go mod init test
go get github.com/prisma/prisma-client-go
go run github.com/prisma/prisma-client-go generate
```

**Comment by janpio** [comment]
Are we sure this is only in pkg context? I could imagine that it always downloads the binaries, no matter if the ENV vars are set or not.

**Comment by steebchen** [comment]
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/5013932/81000433-7a721680-8e70-11ea-878f-7fbd8a03367c.png">

**Comment by pantharshit00** [comment]
@steebchen Is this still an issue?

**Comment by steebchen** [comment]
It looks like this doesn't happen anymore. I'll close for now.
