### ISSUE TITLE
The preview feature "driverAdapters" is not known

### ISSUE THREAD

**Issue by sylvainbaronnet** [prisma/prisma#21501]
### Bug description

Using : 

```
    "prisma": "^5.4.2",
    "@prisma/client": "^5.4.2",
 ```
 
 When I tried to activate the feature "driverAdapters", I have the following message : 
 `The preview feature "driverAdapters" is not known. Expected one of: fullTextSearch, fullTextIndex, tracing, metrics, multiSchema, fieldReference, postgresqlExtensions, deno, extendedWhereUnique, views, jsonProtocol`
 
 and if I ignore it and just try to use adapter I have this error : 
 
 ```
 PrismaClientConstructorValidationError: "adapter" property can only be provided to PrismaClient constructor when "driverAdapters" preview feature is enabled.
 ```
 
 
 

### How to reproduce

1. add feature "driverAdapters"
2. error message "The preview feature "driverAdapters" is not known"

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}
```

### Environment & setup

- OS: macOS
- Database: PlanetScale
- Node.js version: Bun 1.05

### Prisma Version

```
    "prisma": "^5.4.2",
    "@prisma/client": "^5.4.2",
```

**Comment by janpio** [comment]
> When I tried to activate the feature "driverAdapters", I have the following message :

Where exactly do you have this message? When running a CLI command? Or in the VS Code extension? Or somewhere else?

What is your `prisma -v` output? Use the same way to run the command you used when you got the error message.

**Comment by sylvainbaronnet** [comment]
> Where exactly do you have this message? 

in VS Code extension

<img width="522" alt="image" src="https://github.com/prisma/prisma/assets/1569516/4fd81cb8-e095-4b0d-8733-ebb2deee6583">

<img width="1277" alt="image" src="https://github.com/prisma/prisma/assets/1569516/eff33d1c-28af-4d45-8da4-84e50fe0e811">

Although it seems to work now using PS adapter so I can ignore that warning probably.

I don't understand why I need to set the full connection url in prisma if I use planetscale adapter, is it normal ?

**Comment by janpio** [comment]
Which version of the VS Code extension do you have installed? It might be that this is not 5.4.x and hence does not know about the `driverAdapters` preview feature yet.

> I don't understand why I need to set the full connection url in prisma if I use planetscale adapter, is it normal ?

What exactly do you mean? Why you also have to provide a connection string in `schema.prisma`?

**Comment by sylvainbaronnet** [comment]
ok I understand it's because I'm not using the correct extension, sorry about that 
<img width="611" alt="image" src="https://github.com/prisma/prisma/assets/1569516/3ba2d853-95d1-40e6-880a-4e4b7551c5ed">


> Why you also have to provide a connection string in schema.prisma?

yes, since credentials are in adapter config I don't understand why we need also that connection string

**Comment by janpio** [comment]
> yes, since credentials are in adapter config I don't understand why we need also that connection string

We are also still figuring that out. Right now, it is just because the validation does not _know_ that you are using a driver adapter in your code. Migrations and Introspection also still use the connection string from the schema file. We'll try to revisit this and figure out a solution that makes sense for everyone.

**Comment by inhanbyeol94** [comment]
@janpio I'm using the PrismaORM plugin in Webstorm and have recently updated all of my versions to version 5.15.0, but prismaSchemaFolder is not included.

**Comment by janpio** [comment]
Yes, we are trying to work with the IntelliJ team to get their extension updated.
