### ISSUE TITLE
Prisma CLI not instaling properly

### ISSUE THREAD

**Issue by AliSajid** [prisma/prisma#21564]
### Bug description

I am trying to use Prisma in a Sveltekit project. I've added prisma to devDependencies using `pnpm add --save-dev prisma`. However, when I try to run the CLI I see the following error:

```
WARN  Failed to create bin at /Users/aimami/experiments/RepeaterIQ/RepeaterIQ-Core/node_modules/.pnpm/prisma@5.4.2/node_modules/prisma/node_modules/.bin/prisma. ENOENT: no such file or directory, open '/Users/aimami/experiments/RepeaterIQ/RepeaterIQ-Core/node_modules/.pnpm/prisma@5.4.2/node_modules/prisma/build/index.js'
node_modules/.pnpm/prisma@5.4.2/node_modules/prisma: Running preinstall script, done in 50ms
 WARN  Failed to create bin at /Users/aimami/experiments/RepeaterIQ/RepeaterIQ-Core/node_modules/.pnpm/prisma@5.4.2/node_modules/prisma/node_modules/.bin/prisma. ENOENT: no such file or directory, open '/Users/aimami/experiments/RepeaterIQ/RepeaterIQ-Core/node_modules/.pnpm/prisma@5.4.2/node_modules/prisma/build/index.js'
 WARN  Failed to create bin at /Users/aimami/experiments/RepeaterIQ/RepeaterIQ-Core/node_modules/.bin/prisma. ENOENT: no such file or directory, open '/Users/aimami/experiments/RepeaterIQ/RepeaterIQ-Core/node_modules/prisma/build/index.js'
```

### How to reproduce

1. Create new sveltekit project
2. Add prisma to dependencies
3. run `pnpm dlx prisma`

### Expected behavior

CLI should work.

### Prisma information

I do not even get to that part.

### Environment & setup

- OS: macOS
- Database: Supabase/Postgres
- Node.js version: v18.18.2

### Prisma Version

```
5.4.2
```

Of course, I can't see it from `prisma -v`.

**Comment by jkomyno** [comment]
Hi @AliSajid, is your Sveltekit project a monorepo? Could you please share the exact commands you've used to generate your Sveltekit project in the first place? Thanks.

Also, can you try `npx prisma`?

**Comment by AliSajid** [comment]
Hi @jkomyno, Thank you for the prompt response.

1. My project is not a monorepo. You can see the current state of the project here: [https://github.com/alisajid/repeateriq-core/tree/supabase](https://github.com/alisajid/repeateriq-core/tree/supabase). I am currently working on the `supabase` branch.
2. The exact command used to generate the project was `pnpm create svelte@latest RepeaterIQ-Core`
3. `npx prisma` gives me `sh: prisma: command not found`.

**Comment by Jolg42** [comment]
I could not reproduce in your project on Codespaces,
<img width="1236" alt="Screenshot 2023-10-24 at 10 43 09" src="https://github.com/prisma/prisma/assets/1328733/d648d5d5-952c-464b-b549-ea51a28ddb1e">

What's your versions?
```
npx -v
10.1.0
npm -v
10.1.0
node -v
v20.8.0
pnpm -v
8.8.0
```

Maybe 
- check if you have the prisma CLI installed globally with `npm -g list` and then remove it if so.
- try to delete all `node_modules` folders around maybe.

**Comment by AliSajid** [comment]
Deleting the node_modules folder and clearing the pnpm cache worked. I'm unsure why this problem happened and I appreciate all your help.

For future reference, these were the versions I was working with:

```
 ➜ npx -v
9.8.1
 ➜ npm -v
9.8.1
 ➜ node -v
v18.18.2
 ➜ pnpm -v
8.9.2
```
