### ISSUE TITLE
Prisma installation failure

### ISSUE THREAD

**Issue by sharonpatta** [prisma/prisma#21565]
### Bug description

I have node version 18.18.2. However, when I try to run `npm install`, it fails saying that I need node version >= 16.13. I have attached the log.
[2023-10-19T21_10_10_343Z-debug-0.log](https://github.com/prisma/prisma/files/13047824/2023-10-19T21_10_10_343Z-debug-0.log)

### How to reproduce
1. Check node version using `node -v` and verify that it is >= 16.13
2. Run `npm i` or `npm install prisma@5.4.2`

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: 18.18.2

**Comment by chrisvire** [comment]
@sharonpatta is a student working on a [senior capstone project](https://github.com/sillsdev/appbuilder-usercontent-management).  I started working with them yesterday getting the project setup with SvelteKit and Prisma.

This is only happening on her computer, but it is very odd that the log clearly shows that version of node as 18.18.2:

```
404 verbose stack Error: command failed
404 verbose stack     at ChildProcess.<anonymous> (/Users/sharonpatta1/.volta/tools/image/node/18.18.2/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
404 verbose stack     at ChildProcess.emit (node:events:517:28)
404 verbose stack     at maybeClose (node:internal/child_process:1098:16)
404 verbose stack     at Socket.<anonymous> (node:internal/child_process:450:11)
404 verbose stack     at Socket.emit (node:events:517:28)
404 verbose stack     at Pipe.<anonymous> (node:net:350:12)
405 verbose pkgid prisma@5.4.2
406 verbose cwd /Users/sharonpatta1/cps491/appbuilder-usercontent-management
407 verbose Darwin 21.6.0
408 verbose node v18.18.2
409 verbose npm  v9.8.1
410 error code 1
411 error path /Users/sharonpatta1/cps491/appbuilder-usercontent-management/node_modules/prisma
412 error command failed
413 error command sh -c node scripts/preinstall-entry.js
414 error ┌──────────────────────────────────────────────┐
414 error │    Prisma only supports Node.js >= 16.13.    │
414 error │    Please upgrade your Node.js version.      │
414 error └──────────────────────────────────────────────┘
415 verbose exit 1
```

**Comment by chrisvire** [comment]
FYI, we tried installing node via nvm and https://volta.sh and both had the same failure.

**Comment by jkomyno** [comment]
Hi @sharonpatta, this is indeed odd, as I'm routinely using Prisma on Node.js 18.x.x.
Maybe this has to do with how Node.js or Prisma were installed on your device?

Could you please report back with the output of:
1. `which node`
2. `npm version`

Please run these commands in the same directory of the project in which the Prisma initialisation failed. Thanks!

**Comment by sharonpatta** [comment]
Update: after running ` npm exec -c 'node -e "console.log(process.execPath)"' `, we found that there was a node_modules folder in my home directory (potentially due to accidentally running `npm i`  in my home directory) , and node was running from that folder. Removing the old node_modules folder resolved the issue.
