### ISSUE TITLE
ETIMEDOUT when installing Prisma

### ISSUE THREAD

**Issue by xshadowbringer** [prisma/prisma#21586]
### Bug description

Error: request to https://binaries.prisma.sh/all_commits/ac9d7041ed77bcc8a8dbd2ab6616b39013829574/rhel-openssl-1.0.x/libquery_engine.so.node.gz.sha256 failed, reason: connect ETIMEDOUT 2606:4700:10::6816:176d:443

### How to reproduce

By executing any prisma command, it tries to download the prisma engines and it fails with that error

### Prisma information

doesnt matter

### Environment & setup

- OS: CentOS 8 Stream
- Database: PostgreSQL
- Node.js version: 18.18.2

### Prisma Version

latest

**Comment by jkomyno** [comment]
Hi @xshadowbringer, this seems similar to https://github.com/prisma/prisma/issues/15968 and [others](https://github.com/prisma/prisma/issues?q=is%3Aissue+connect+ETIMEDOUT+is%3Aclosed).
Can you please try installing Prisma on a different network, and report back with the results?

Also, may we ask the country in which you are connecting to the internet to (some countries may block requests to our servers)? Alternatively: are you installing Prisma from a corporate proxy, by any chance? Thanks.

**Comment by xshadowbringer** [comment]
I tried installing this on a VPS server CentOS 8 Stream, on my local computer the application worked perfectly, my country is Romania

**Comment by jkomyno** [comment]
Thanks, and do you also know where that VPS is hosted? Could you maybe try contacting their support team, and ask them why connections to the URL above (https://binaries.prisma.sh/...) are blocked? There is unfortunately not much that we can do from our end for this kind of problem.

**Comment by jkomyno** [comment]
Sure, we'll keep it open and wait for your reply. Thanks!

**Comment by xshadowbringer** [comment]
I connected through their Virtual Terminal and it worked. However this is not a general solution as I remember that I tried this the day before and it didn't work

**Comment by Jolg42** [comment]
Note that currently the engines are hosted on Cloudflare, on their R2 storage.

With the lack of information and our inability to reproduce this issue, we're now closing it.

Thank you 🙏
