### ISSUE TITLE
Transaction API error: Transaction not found when calling `prisma.$disconnect()`

### ISSUE THREAD

**Issue by jakowenko** [prisma/prisma#21633]
### Bug description

I am using Prisma in a production environment with horizontally scaling read replicas on AWS Aurora Serverless v2. I've recently incorporated the extension-read-replicas package to use a reader/writer for better performance. I'm having issues with the extension not using new readers as they scale up with the issue described her: https://github.com/prisma/extension-read-replicas/issues/26

One solution I was trying to incorporate was to call `$disconnect()` after each API request to close the connection and hopefully establish a new one with one of the scaled up replicas. This seems to work except when calling it after a transaction. I get this following error. I found a similar issue [here](https://github.com/prisma/prisma/issues/16050), but the answer was to simply not call `$disconnect()` which isn't a solution for me.

```
Transaction API error: Transaction not found. Transaction ID is invalid, refers to an old closed transaction Prisma doesn't have information about anymore, or was obtained before disconnecting.
PrismaClientKnownRequestError: Transaction API error: Transaction not found. Transaction ID is invalid, refers to an old closed transaction Prisma doesn't have information about anymore, or was obtained before disconnecting.
    at mr.transaction (/api/generated/prisma-client/runtime/library.js:113:1497)
    at async Proxy._transactionWithCallback (/api/generated/prisma-client/runtime/library.js:128:8665)
    at <anonymous> (/api/src/api/user/router.ts:98:3)
```

### How to reproduce

I have a transaction similar to this.

```ts
await prisma.$transaction(async (tx) => {
    const user = await tx.user.findUnique({
      where: { id },
      select: {
        id: true,
        name: true,
      },
    });

await prisma.$disconnect();
```

### Expected behavior

The connection is closed.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["clientExtensions", "fullTextSearch", "fullTextIndex", "filteredRelationCount", "orderByNulls"]
  output          = "../generated/prisma-client"
}

generator zod {
  provider = "prisma-zod-generator"
  output   = "../generated/schemas"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id                        String                     @id @default(cuid())
  name                      String
```

### Environment & setup

- OS: macOS, Amazon Linux 2
- Database: MySQL 8
- Node.js version: v18.16.0

### Prisma Version

```
prisma                  : 5.4.2
@prisma/client          : 5.4.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine ac9d7041ed77bcc8a8dbd2ab6616b39013829574 (at node_modules/.pnpm/@prisma+engines@5.4.2/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli ac9d7041ed77bcc8a8dbd2ab6616b39013829574 (at node_modules/.pnpm/@prisma+engines@5.4.2/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.4.1-2.ac9d7041ed77bcc8a8dbd2ab6616b39013829574
Default Engines Hash    : ac9d7041ed77bcc8a8dbd2ab6616b39013829574
Studio                  : 0.494.0
Preview Features        : clientExtensions, filteredRelationCount, fullTextIndex, fullTextSearch, orderByNulls
```

**Comment by janpio** [comment]
What do we need to reproduce this? Is it as simple as putting your snippet into a script?

**Comment by millsp** [comment]
@jakowenko  Did you see the message from @janpio? Without additional information to be able to reproduce, we would later close this issue as part of our issue process.

**Comment by SevInf** [comment]
Hey @jakowenko.
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Comment by mike-rambil** [comment]
been running into this same issue..

**Comment by mike-rambil** [comment]
> Hey [@jakowenko](https://github.com/jakowenko).
> 
> With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
> 
> Thank you 🙏

He has given enough information and context here... it is all there is to it. 

What doesn't make sense is - Not knowing why the transaction is getting lost(which is the same case for me)

**Comment by gharezlak** [comment]
When this happens to me, it's normally because the amount of work I'm doing in the transaction exceeds the fairly short default timeout that prisma transactions have (5000ms I think?). Consequently, I need to increase the timeout for the transaction so the tx is still valid at the end.

```
const result = await prisma.$transaction(async (tx) => {
    //do work
  }, {
    timeout: 30000 // 30 seconds
});
```
