### ISSUE TITLE
Usage of deprecated punycode module

### ISSUE THREAD

**Issue by RDIL** [prisma/prisma#21644]
### Bug description

Hi Prisma team,

It seems somewhere in the engines package, the `punycode` package is used, which was recently runtime-deprecated by the Node.js team.
<img width="1400" alt="Screenshot 2023-10-26 at 22 00 27" src="https://github.com/prisma/prisma/assets/34555510/2d81abcf-1eaa-4f81-ae8a-c9456260cf3b">

Just opening this to put it on the radar.

### How to reproduce

Here's where it was detected:
<img width="1384" alt="Screenshot 2023-10-26 at 22 01 49" src="https://github.com/prisma/prisma/assets/34555510/252f44d1-0506-4c2c-a001-43bd1471d996">

### Expected behavior

The error should not be raised.

### Prisma information

Prisma schema is not relevant to the issue.

### Environment & setup

`yarn dlx envinfo`:

```
  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 42.22 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - /private/var/folders/db/rxww00gx78q985zjbd22p0rw0000gn/T/xfs-a83cbd08/node
    Yarn: 4.0.0 - /private/var/folders/db/rxww00gx78q985zjbd22p0rw0000gn/T/xfs-a83cbd08/yarn
    npm: 10.2.0 - /opt/homebrew/bin/npm
  Managers:
    Cargo: 1.73.0 - ~/.cargo/bin/cargo
    Homebrew: 4.1.17 - /opt/homebrew/bin/brew
    pip3: 23.2.1 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    CMake: 3.27.7 - /opt/homebrew/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.42.0 - /opt/homebrew/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    FFmpeg: 6.0 - /opt/homebrew/bin/ffmpeg
    Curl: 8.1.2 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Docker: 24.0.6 - /opt/homebrew/bin/docker
  IDEs:
    Emacs: 29.1 - /opt/homebrew/bin/emacs
    VSCode: 1.78.0 - /opt/homebrew/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.21.3 - /opt/homebrew/bin/go
    Java: 17.0.8.1 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Protoc: 24.4 - /opt/homebrew/bin/protoc
    Python3: 3.11.6 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.73.0 - /Users/reece/.cargo/bin/rustc
  Databases:
    PostgreSQL: 14.9 - /opt/homebrew/bin/postgres
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Safari: 17.0
```

### Prisma Version

```
5.5.2
```

**Comment by Jolg42** [comment]
Note: I think this is currently blocked as we depend on an old version of `node-fetch`, because we still support Node.js v16, and that will be unblocked by https://github.com/prisma/prisma/pull/20857

**Comment by Jolg42** [comment]
I randomly found out this PR in Yarn where they bundle `punycode`
https://github.com/yarnpkg/yarn/pull/9009

**Comment by RDIL** [comment]
@Jolg42 yeah, it's also to remedy this issue, however the warning does come from Prisma itself here.

**Comment by Jolg42** [comment]
@RDIL Sorry for the confusion, I found it interesting that Yarn solved this issue like this and indeed that does not solve the problem with Prisma.

**Comment by Jolg42** [comment]
There are similar issues in projects that are still using node-fetch v2
https://github.com/getsentry/sentry-cli/issues/1810
This issue describes the problem I found
>v2.x.x of [node-fetch/node-fetch](https://github.com/node-fetch/node-fetch/blob/v2.6.11/package.json?rgh-link-date=2023-11-07T05%3A01%3A04Z#L40) depend on a version of [jsdom/whatwg-url](https://github.com/jsdom/whatwg-url/blob/v5.0.0/src/url-state-machine.js?rgh-link-date=2023-11-07T05%3A01%3A04Z#L2) that uses punycode

https://github.com/serverless/serverless/issues/12237

**Comment by Jolg42** [comment]
You can now try the dev version `5.14.0-dev.30`. If you do, let us know how it goes, it's always appreciated to get some positive feedback/confirmation.

This will be part of the next official release planned for May 14th.

**Comment by bligneri** [comment]
Just tested `5.14.0-dev.30` and the warning is gone and everything works fine.
🚀🚀🚀
