### ISSUE TITLE
Prisma >= 4.13 causes TS1005 error

### ISSUE THREAD

**Issue by mitre-tm** [prisma/prisma#21665]
### Bug description

Any version of Prisma greater than 4.12.0 that I tried (4.13.0 and 5.5.2 for sure) produce the following error:
```
prisma-client/prisma/dist/runtime/library.d.ts:1298:35 - error TS1005: '?' expected.

1298     select: infer S extends object;
```

I reproduced the issue with TS 4.7.4, 5.0.0, and 5.2.2, so it is not a matter of using an old TS version as reported in related issues (see below).

Related issues:
- https://github.com/prisma/prisma/issues/5732
- https://github.com/prisma/prisma/issues/20024

### How to reproduce

Generate the client and build the application. The source files are sensitive and I did not yet have the opportunity to invest time shrinking to produce a minimal example that exposes the bug.

### Expected behavior

Compile without errors.

### Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URI")
}

generator client {
  provider        = "prisma-client-js"
  output          = "./dist"
  previewFeatures = ["tracing"]
}

// [...] sensitive and I did not yet have the opportunity to invest time shrinking to produce a minimal example that exposes the bug
```

```ts
// [...] sensitive and I did not yet have the opportunity to invest time shrinking to produce a minimal example that exposes the bug
```

### Environment & setup

- OS: Ubuntu 22.04.3 LTS 64 bits (`Linux <hostname> 6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`)
- Database: PostgreSQL 15.3
- Node.js version: Node.js v18.18.0

### Prisma Version

The bug is present in 4.13.0 and 5.5.2. I have not tested all versions in between, but I believe all are affected. The bug is absent from version 4.12.0.

**Comment by janpio** [comment]
Are you sure you are using a recent version of Typescript?

**Comment by mitre-tm** [comment]
> Are you sure you are using a recent version of Typescript?

Yes, as explicitly stated in the issue description:
> I reproduced the issue with TS 4.7.4, 5.0.0, and 5.2.2, so it is not a matter of using an old TS version as reported in related issues (see below).

**Comment by Jolg42** [comment]
@mitre-tm without more information to be able to reproduce, we won't be able to help here.

Please give steps to reproduce (the exact command and tooling versions) along with your `tsconfig.json` file for example.

I just tried the following with `5.5.2` and everything works as expected.

```schema
datasource db {
  provider = "postgresql"
  url      = "postgresql://prisma:prisma@localhost:5432/21665"
}

generator client {
  provider        = "prisma-client-js"
  output          = "./dist"
  previewFeatures = ["tracing"]
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model Profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
}
```

tsconfig
```js
{
  "compilerOptions": {
    "target": "es2017" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
    "module": "commonjs" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */,
    "strict": true /* Enable all strict type-checking options. */,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */
  }
}
```

main.ts
```ts
import { PrismaClient } from '@prisma/client'

async function main() {
  const prisma = new PrismaClient()

  const data = await prisma.user.findMany()
  console.log(data)
  prisma.$disconnect()
}

main()
```

**Comment by mitre-tm** [comment]
I solved the issue by deleting the lockfiles (`package-lock.json`) and recreating them with `npm install`. In this process, some dependencies were auto-updated, which I believe solved the issue. In the build (CI), we use [npm clean-install](https://docs.npmjs.com/cli/v10/commands/npm-ci), for reproducibility and security.

By the way, our `tsconfig.json` was already consistent with the one provided in the example, with the difference that `target` was set to `ES2022`, as [recommended for Node 18](https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping#node-18).

**Comment by brooke1220** [comment]
node_modules/@prisma/client/runtime/library.d.ts:1299:1 - error TS1005: '?' expected.

1299 } & Record<string, unknown> | {
     ~

node_modules/@prisma/client/runtime/library.d.ts:1301:1 - error TS1005: '?' expected.

1301 } & Record<string, unknown> ? {
     ~





Error! You can try adding the -V parameter for more information output.




Error: TS Error: '?' expected.(node_modules/@prisma/client/runtime/library.d.ts)

**Comment by brooke1220** [comment]
ts config

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "ES2021",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "inlineSourceMap":true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "stripInternal": true,
    "skipLibCheck": true,
    "pretty": true,
    "declaration": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "preserve",
    "esModuleInterop": true,
    "typeRoots": [ "./typings", "./node_modules/@types"],
    "outDir": "dist",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./web/*"],
      "~src/*": ["./src/*"] 
    }
  },
  "exclude": [
    "dist",
    "node_modules",
    "test",
    "web"
  ]
}
```

**Comment by Jolg42** [comment]
@brooke1220 Please open a new issue and fill up the template, we'll need more information to be able to help you.
Make sure to check your `typescript` package version installed.

**Comment by suryaelidanto** [comment]
> I solved the issue by deleting the lockfiles (`package-lock.json`) and recreating them with `npm install`. In this process, some dependencies were auto-updated, which I believe solved the issue. In the build (CI), we use [npm clean-install](https://docs.npmjs.com/cli/v10/commands/npm-ci), for reproducibility and security.
> 
> By the way, our `tsconfig.json` was already consistent with the one provided in the example, with the difference that `target` was set to `ES2022`, as [recommended for Node 18](https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping#node-18).

thank you bro, you solved my problem, i love you
