### ISSUE TITLE
'prisma-client' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by rChaoz** [prisma/prisma#21673]
### Bug description

I followed the [instructions](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/mongodb/connect-your-database-node-mongodb) for setting up Prisma, and `prisma generate` fails with the following output:

```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: spawn prisma-client ENOENT
```

This, on its own, is not very helpful. Luckily the github issue template suggests using DEBUG=*, which produces this:
```
  prisma:GeneratorProcess  'prisma-client' is not recognized as an internal or external command, +0ms
  prisma:GeneratorProcess  operable program or batch file. +0ms
  prisma:GeneratorProcess  Error: spawn prisma-client ENOENT
```

### How to reproduce

1. Fresh setup
2. yarn add -D prisma
3. prisma init --datasource-provider mongodb
4. Write some model into the schema
5. yarn add @prisma/client
6. prisma generate

### Expected behavior

Better error handling, it should tell me that prisma-client wasn't found.

There should be `prisma-client.cmd` / `prisma-client` files in the 'node_modules/.bin' directory, just like there are for the normal prisma CLI tool. Or it should execute `node <path-to-prisma-client>` instead.

### Prisma information

```prisma
generator client {
  provider = "prisma-client"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Board {
  id String @id @default(auto()) @map("_id") @db.ObjectId
}
```

### Environment & setup

- OS: Windows 10
- Database: MongoDB
- Node.js version: v20.8.0
- Yarn: 1.22.19

### Prisma Version

```
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
```

**Comment by janpio** [comment]
Can you share your Prisma schema as the issue template asks for?
There should be no `prisma-client` string anywhere, as that is - as you figured out, not a known command.

**Comment by rChaoz** [comment]
I have updated the issue.

**Comment by janpio** [comment]
The `generator client` should look like this:
```
generator client {
  provider = "prisma-client-js"
}
```

**Comment by rChaoz** [comment]
That is odd. I didn't even notice that the generator provider was set incorrectly, and I was pretty sure I didn't touch the '.prisma' file besides adding a basic model, either.

Not quite sure how that happened, but thanks a lot for the very swift help! :) And sorry but the bad question.
