### ISSUE TITLE
Support "one" underscore at the beginning of field names

### ISSUE THREAD

**Issue by ezsper** [prisma/prisma#2167]
##  Bug description

There are a couple of issues on this

* #259 

But **notice** that `id String @map('_id')` is not enough in our use case

Prisma2 does not accept (one) underscore at beginning of field names, consider:

```javascript
/^([a-zA-Z_][a-zA-Z0-9]|[a-zA-Z])[a-zA-Z0-9_]+/
```

It's unpractical for us to keep doing aliases, right now it messes our whole experience with prisma, this should be supported.

## How to reproduce

Just put a an underscore at beginning of field names. Ex.: `_id String`

## Expected behavior

It should support at least one underscore at beginning of field names and only one - as GraphQL itself does not support double underscore - in our use case we use two types of ids:

```graphql
type User {
  """
  The user object id
  """
  _id: ObjectId
  """
  The user global id followed by Relay spec
  """
  id: ID
}
```

and we follow this pattern for relations

```graphql
type Post {
  # ...
  """
  The user object id
  """
  _userId: ObjectId
  """
  The user global id followed by Relay spec
  """
  userId: String
}
```

It acceptable to have this 

```graphql
model PostAuthor {
   type String
   _id String
  @@id([type, _id])
}

```

an do queries with 

```json
{ "type__id": { "type": "Organization", "_id": "1" } }
```

## Environment & setup

- OS: Mac OS
- Database: SQLite
- Prisma version: 2.0.0-beta.2
- Node.js version: v12.13.0

**Comment by dodas** [comment]
Prisma is not GraphQL-specific anymore, so anything related to GraphQL is irrelevant.

**Comment by ezsper** [comment]
I know that, but we use with GraphQL, you have also Nexus plugin that would support double underscore but one underscore should be considered. 🙂

**Comment by janpio** [comment]
Prisma's implementation of this will unfortunately not be able to change as this is deeply ingrained. If a tool like Nexus (or some plugin) does not help with this, that would be a feature request or even bug report to that tool.
