### ISSUE TITLE
Too many idle connections and too little active connections in high traffic

### ISSUE THREAD

**Issue by cryptrr** [prisma/prisma#21701]
### Bug description

Hello, 
I'm using Google Cloud Run to connect to Cloud SQL Postgres instance with Prisma through Auth Proxy.

Using connection_limit=2 since serverless.

Still too many connections are created and are in the idle state.

Even when 10 cloud run instances are active and 8 are idle, GCP Cloud SQL shows only 2 connections as active and 21 connections as idle.

Tested with 100 concurrent connections to the cloud run endpoint for 60 seconds.

Is using external connection pooling the only solution here? 

PS: This is a NestJS app and the Prisma Client is used as a NestJS service.

Cloud SQL connections chart

<img width="1018" alt="Screenshot 2023-10-31 at 7 03 43 AM" src="https://github.com/prisma/prisma/assets/135767626/5ec984c7-b82d-4036-bd34-7d81a1f0a491">

Cloud Run instances chart
 
<img width="1008" alt="Screenshot 2023-10-31 at 7 06 22 AM" src="https://github.com/prisma/prisma/assets/135767626/39b19f4f-0b2b-454d-a83b-160d9ff1b40a">
a376-0722663cbdc1">

### How to reproduce

Using a serverless service like Cloud Run and Cloud SQL with Prisma

### Expected behavior

Prisma should't be creating 20 idle connections for 2 active connections

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
@Injectable()
export class PrismaService implements OnModuleDestroy, OnModuleInit {

  constructor(private config: ConfigService) {
    logger.debug("Initializing Prisma on startup")
  }

  db : PrismaClient = new PrismaClient({
    datasources: {
      db: {
        url: this.config.get('DATABASE_URL'),
      },
    }
  })

 
  async onModuleInit() {
    this.initializeDb()
  }

  async initializeDb(){
    try {
      logger.debug("initializing prisma db")
      this.db.$connect().catch(async (e) => {
        logger.debug(`Error while connecting to db: ${process.env.DATABASE_URL}`)
        logger.debug("Trying again")
        await new Promise((resolve) => setTimeout(resolve, 10000));
        this.initializeDb()
      })
    } catch (error) {
      logger.error(`Error while connecting to db: ${process.env.DATABASE_URL}`)
      logger.error("Trying again")
      await new Promise((resolve) => setTimeout(resolve, 10000));
      this.initializeDb()
    }
  }

  async onModuleDestroy() {
    await this.db.$disconnect();
  }

  async enableShutdownHooks(app: INestApplication) {
    //@ts-ignore
    this.db.$on("beforeExit", async () => {
      await app.close();
    });
  }

}
```

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: 20

### Prisma Version

```
5.4.0
```

**Comment by cryptrr** [comment]
<img width="1018" alt="Screenshot 2023-10-31 at 7 03 43 AM" src="https://github.com/prisma/prisma/assets/135767626/631c5879-9a94-40e3-bf10-dc6edc29e5e8">

The connections come down after traffic subsides but still 10 idle connections for 2 active connections.

**Comment by cryptrr** [comment]
Seems like the event "beforeExit" got removed from Prisma.

**Comment by cryptrr** [comment]
Still the same behaviour is seen.

Is this normal?

<img width="1018" alt="Screenshot 2023-10-31 at 10 00 20 AM" src="https://github.com/prisma/prisma/assets/135767626/b5db9329-709c-466f-aa0d-40e51469b9f6">

**Comment by Jolg42** [comment]
@cryptrr What do you mean by "out of total 13000 requests, 400 fails."? What error do you get?

**Comment by Jolg42** [comment]
@cryptrr I think it would be interesting if you could use the `metrics` preview feature and log the metrics before shutdown for example.

```
const metrics = await prisma.$metrics.json()
console.log(metrics)
```
See https://www.prisma.io/docs/concepts/components/prisma-client/metrics for how to use it.

**Comment by janpio** [comment]
> Even when 10 cloud run instances are active and 8 are idle, 

What do you mean here?
Do you have 10 instances total? Or 18 total?
What does "are idle" mean? Did they not handle any traffic at all?

> GCP Cloud SQL shows only 2 connections as active and 21 connections as idle.

So there are a total of 23 connections open, and 2 are active and 21 are shown as idle, correct?

---

Generally, when a Prisma Client instance handles at least 1 query it will open one connection.
If it has to handle multiple queries at the same time, it will open as many connections as needed until the connection limit is hit.
It will then keep those connections open (and not just close them again).
When the instance does not run any queries, all of these connections will be idle and waiting.
When there are queries, it will use these existing connections.

So if you have 18 "servers" with a Prisma Client instance each, it would be normal for at least 18 connections to be open, or even 36 when those instances all handled traffic that made it necessary to open connections up to your connection limit.

**Comment by cryptrr** [comment]
The problem here is that even at the peak 10 cloud run max instances that I set, the active connections from prisma does not go higher than 2.

This might be probably causing the socket errors when under load.

Note that the 8 idle cloud run instances are some kind of GCP internal to keep containers warm. I set the max instances to 10.

**Comment by cryptrr** [comment]
@Jolg42 The errors are mostly timeouts and rest are connection refusal errors.

```
Running 1m test 
  2 threads and 80 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   949.04ms  547.67ms   2.00s    56.74%
    Req/Sec    36.29     18.81   100.00     69.53%
  4112 requests in 1.00m, 59.24MB read
  Socket errors: connect 18, read 0, write 0, timeout 446
Requests/sec:     68.45
Transfer/sec:      0.99MB

```

**Comment by cryptrr** [comment]
The issue was with cloud run scaling. Closing now.

**Comment by jbeurel** [comment]
Hello @cryptrr 
I have the same issue with the same stack (Cloud Run + Cloud SQL + Prisma).
I'm searching a solution aroung prisma pool_size and I see your posts.
Could you share you cloud run scaling solution ?

**Comment by jieey1140** [comment]
Hi @cryptrr  

I am experiencing the same issue in the same environment. 
Can you share how you adjusted the scaling or if you solved the problem? 
Thanks

**Comment by skakac** [comment]
@cryptrr Please share your solution

**Comment by Mateusvaz89** [comment]
@cryptrr I have the same problem, could you share the solution?

**Comment by zirkler** [comment]
I'm also interested. @cryptrr what actually was the problem with "cloud run scaling"?

**Comment by cryptrr** [comment]
This is in fact a problem with SQL itself with serverless. Connections are gonna add up unnecessarily. Completely preventing it is kinda impossible if not using pooler like pgbouncer or prisma's own hosted connection pooling service.

**Comment by iurylippo** [comment]
Hello guys, I was facing this problem in my RDS Postgre and couldn't find a solution from prisma itself. So, I run that script programmatically:

```
WITH inactive_connections AS (
    SELECT
        pid,
        rank() over (partition by client_addr order by backend_start ASC) as rank
    FROM 
        pg_stat_activity
    WHERE
        -- Exclude the thread owned connection (ie no auto-kill)
        pid <> pg_backend_pid( )
    AND
        -- Exclude known applications connections
        application_name !~ '(?:psql)|(?:pgAdmin.+)'
    AND
        -- Include connections to the same database the thread is connected to
        datname = current_database() 
    AND
        -- Include connections using the same thread username connection
        usename = current_user 
    AND
        -- Include inactive connections only
        state in ('idle', 'idle in transaction', 'idle in transaction (aborted)', 'disabled') 
    AND
        -- Include old connections (found with the state_change field)
        current_timestamp - state_change > interval '5 minutes' 
)
SELECT
    pg_terminate_backend(pid)
FROM
    inactive_connections 
WHERE
    rank > 1 
```

**Comment by Spoutnik97** [comment]
What does the script do ?

**Comment by iurylippo** [comment]
> What does the script do ?

Close the idles connections
