### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by bolloAgrrey** [prisma/prisma#2171]
## Environment & setup

- OS: [e.g. Mac OS, Windows, Debian, CentOS, ...]
- Database: [PostgreSQL, MySQL, MariaDB or SQLite]
- Prisma version: [Run `prisma -v` to see your Prisma version]
- Node.js version: [Run `node -v` to see your Node.js version]

**Comment by janpio** [comment]
Thanks @bolloAgrrey, seems you forgot to include any text in your issue. Please just create a new one with the description of your problem. Thanks.
