### ISSUE TITLE
`db pull` can't connect to supabase when using "[...].pooler.supabase.com:5432"

### ISSUE THREAD

**Issue by RoyJumah** [prisma/prisma#21740]
### Bug description

I've been trying to connect Prisma with Supabase for a while now but I keep getting an error whenever I try to run these commands:
`npx prisma db pull`
 `npx prisma migrate dev --name init`
 
 
 
 this is the error:
 `User postgres.[id] was denied access on the database postgres.public`
 
 Database Url:
`DATABASE_URL="postgres://postgres[.id]:[password]@aws-0-us-east-1.pooler.supabase.com:5432/postgres"`
 
 I've been tinkering with the database Url to try to find a way through this error by using a username in  the database url but I get this error when i run `npx prisma db pull` :

```
✖ Introspecting based on datasource defined in prisma\schema.prisma
 Error: FATAL: Tenant not found
```

 

### How to reproduce

I have tried deleting the database, granting the user connect and usage privileges but I keep getting the same error.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS:  Windows 10 Pro
- Database:  PostgreSQL
- Node.js version:  v20.7.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
```

**Comment by Jolg42** [comment]
@RoyJumah I think this might be a new error message, though it's actually expected that Migrate and Introspection have issues with the pooled connection string.

You must use a direct connection string for Introspection & Migrate.
Example
```
# Connect to Supabase with PgBouncer.
DATABASE_URL="postgres://postgres.__YOUR_SUPABASE_PROJECT__:__PASSWORD__@daws-0-eu-central-1.pooler.supabase.co:6543/postgres?pgbouncer=true"

# Direct connection to the database. Used for migrations.
DIRECT_URL="postgres://postgres:__PASSWORD__@db.__YOUR SUPABASE_PROJECT__.supabase.co:5432/postgres"
```

See https://www.prisma.io/docs/guides/database/supabase#commonalities-with-other-database-providers

Could you try that and let us know how it goes?

**Comment by RoyJumah** [comment]
Thanks, @Jolg42 .This fixed it 😀. I will take my time to go through the documentation.

**Comment by Jolg42** [comment]
Nice, thanks for the confirmation!

**Comment by Jolg42** [comment]
Note I tried to reproduce to see the error message

```
npx prisma@latest db pull --url="postgres://postgres.imfuuhzoslsteprqxzdj:PASSWORD@aws-0-eu-central-1.pooler.supabase.com:6543/postgres"
✖ Introspecting
Error: ERROR: prepared statement "s0" does not exist
```

```
npx prisma@latest db pull --url="postgres://postgres.imfuuhzoslsteprqxzdj:PASSWORD@aws-0-eu-central-1.pooler.supabase.com:5432/postgres"
✖ Introspecting
Error: P1010
User `postgres.imfuuhzoslsteprqxzdj` was denied access on the database `postgres.public`
```

I could reproduce by changing the port, the default port for the pooler is `6543`. It's also the same value in this project on Supabase.
When changing it to `5432` in the connection string only, then the error message is the same as this issue.

**Comment by RoyJumah** [comment]
@Jolg42 Sorry for bringing this issue again but i get this error

```
$  npx prisma db seed
Environment variables loaded from .env
Running seed command `node prisma/seed.js` ...
PrismaClientInitializationError: 
Invalid `prisma.products.create()` invocation in
C:\Users\Hp\Desktop\kilimo-connect\prisma\seed.js:5:27

  2 const prisma = new PrismaClient();
  3 async function seedProducts() {
  4   try {
→ 5     await prisma.products.create(
Error querying the database: FATAL: Tenant or user not found
    at Cn.handleRequestError (C:\Users\Hp\Desktop\kilimo-connect\node_modules\@prisma\client\runtime\library.js:123:7090)
    at Cn.handleAndLogRequestError (C:\Users\Hp\Desktop\kilimo-connect\node_modules\@prisma\client\runtime\library.js:123:6206)
    at Cn.request (C:\Users\Hp\Desktop\kilimo-connect\node_modules\@prisma\client\runtime\library.js:123:5926)
    at async l (C:\Users\Hp\Desktop\kilimo-connect\node_modules\@prisma\client\runtime\library.js:128:9968)
    at async seedProducts (C:\Users\Hp\Desktop\kilimo-connect\prisma\seed.js:5:5) {
  clientVersion: '5.5.2',
  errorCode: undefined
}

The seed command has been executed.
```
when i run the seed command. 

seed.js
```
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();
```

I have also already added this to the `package.json`
```
"prisma": {
    "seed": "node prisma/seed.js"
  },
```

**Comment by janpio** [comment]
What connection string are you using when you receive this message @RoyJumah? Does it include `pooler`? What is the port, `5432` or `6543`? Are you using `pgbouncer=true` in your connection string for Prisma?

**Comment by Jolg42** [comment]
+1

To me, `FATAL: Tenant or user not found` sounds like you want to verify your connection string to your database, there is probably a typo hiding in there.
Check the Supabase dashboard and set them again.

**Comment by RoyJumah** [comment]
These are the connections string that I'm currently using
```
DIRECT_URL="postgres://postgres:[password]@db.aigdooxkrussptkeikqq.supabase.co:5432/postgres"
DATABASE_URL="postgres://postgres:[password]@aws-0-us-east-1.pooler.supabase.com:6543/postgres"
```
I'm able to run ` npx prisma db pull` and `npx prisma migrate dev --name init` without any errors but when I try to seed that is when the error pops up.

**Comment by janpio** [comment]
Add `?pgbouncer=true` to the `DATABASE_URL` to enable Prisma's (now misnamed) connection pooler mode. That might help.
If not, let us know.

**Comment by RoyJumah** [comment]
Thanks. Adding the `PROJECT_ID` and  pg bouncer to the `DATABASE_URL` solved the error

**Comment by janpio** [comment]
> Adding the `PROJECT_ID`

What do you mean by that?

**Comment by Cybortex** [comment]
I found out for me it was a problem with the DATABASE_URL for some reason it wasn't corresponding with the right url.
I compared the url copied from the connection string with that of the tutorial i was using and found a couple of differences with the url format.
After changing the url I was successfully able to run  'npx prisma migrate dev --name init'
here is the url from the connection string i got from prisma - postgres://postgres.eorfsjriyrbbtiztjwfn:[YOUR-PASSWORD]@aws-0-eu-west-2.pooler.supabase.com:6543/postgres
here's what i change it to - postgres://postgres:[YOUR-PASSWORD]@db.eorfsjriyrbbtiztjwfn.supabase.co:5432/postgres

**Comment by janpio** [comment]
Where does Prisma give you a Supabase connection string @Cybortex?

**Comment by Cybortex** [comment]
Sorry I meant supabase

**Comment by janpio** [comment]
Supabase usually gives you both of these strings, one as the direct one and one as the connection pooled on. Both are on the same "Database" screen.

**Comment by Wingrammer** [comment]
Making sure IP is unbanned and changing the pool mode from transaction solved the problem. They said both the transaction mode should take care of both 5432 and 6543 but it did not for me.

**Comment by abshirahmed** [comment]
> These are the connections string that I'm currently using
> 
> ```
> DIRECT_URL="postgres://postgres:[password]@db.aigdooxkrussptkeikqq.supabase.co:5432/postgres"
> DATABASE_URL="postgres://postgres:[password]@aws-0-us-east-1.pooler.supabase.com:6543/postgres"
> ```
> 
> I'm able to run ` npx prisma db pull` and `npx prisma migrate dev --name init` without any errors but when I try to seed that is when the error pops up.

I've experiencing the same issue even with the additional `pgbouncer=true` field. I was able to run migrate the first time, but I get the following error for all subsequent requests to the db
```bash
Error: P1001: Can't reach database server at `db.xxxxxxxxxxx.supabase.co`:`5432`
Please make sure your database server is running at `db.xxxxxxxxxxx.supabase.co`:`5432`.
```

**Comment by terehov** [comment]
> > These are the connections string that I'm currently using
> > ```
> > DIRECT_URL="postgres://postgres:[password]@db.aigdooxkrussptkeikqq.supabase.co:5432/postgres"
> > DATABASE_URL="postgres://postgres:[password]@aws-0-us-east-1.pooler.supabase.com:6543/postgres"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm able to run ` npx prisma db pull` and `npx prisma migrate dev --name init` without any errors but when I try to seed that is when the error pops up.
> 
> I'm experiencing the same issue, even with the additional `pgbouncer=true` field. I was able to run migrate the first time, but I get the following error for all subsequent requests to the db
> 
> ```shell
> Error: P1001: Can't reach database server at `db.xxxxxxxxxxx.supabase.co`:`5432`
> Please make sure your database server is running at `db.xxxxxxxxxxx.supabase.co`:`5432`.
> ```

I get the same issue. Probably since Supabase changed their pooler and removed IPv4.

**Comment by abshirahmed** [comment]
> I was getting a similar error
> 
> > Error querying the database: FATAL: Tenant or user not found
> 
> I was using Supabase as my provider and I found the issue to be with the connection URL that Supabase provides.
> 
> On [https://supabase.com/dashboard/project/[your-supabase-project]](https://supabase.com/dashboard/project/%5Byour-supabase-project%5D), Supabase has a `Connect` button that opens a modal which gives you info on how to connect to your Supabase. Under `ORM` tab in that modal, the value of `DATABASE_URL` is incorrect. Specifically the AWS region. Whatever region you chose when you created the project, the region in `DATABASE_URL` is always `aws-0-eu-central-1` which is incorrect. I changed this region to the region I was using and stopped getting this error.

This was really helpful 👍🏾  in addition to this, I had to replace the `DIRECT_URL` referenced in the `ORMs` tab:

<img width="1075" alt="Screenshot 2024-02-25 at 00 15 17" src="https://github.com/prisma/prisma/assets/10318770/483f81cf-d9ab-4642-a56a-cc4adbacc074">

with the one referenced in the `Connection String` tab:

<img width="1096" alt="Screenshot 2024-02-25 at 00 14 10" src="https://github.com/prisma/prisma/assets/10318770/1d98e760-ce52-4e48-8138-02a4919765bf">

Now everything is working ✅
