### ISSUE TITLE
Prisma Accelerate Cache Bust 

### ISSUE THREAD

**Issue by eglove** [prisma/prisma#21751]
Prisma docs lead me here for a feature request and I am on mobile, I apologize if anything is out of place or missing. I can update if needed.

I really love Prisma Accelerate, I'm using it with CloudFlare pages right now on an Astro project. The TTL and SWR options are amazing. But...

## Problem

If I programatically set TTL I get inconsistent results. This isn't entirely surprising and not quite what I want to do anyway.

Let's say the user uses a form to update a record on a database. When they're redirected to the page to show that data it should reflect those updates. Otherwise if there has been no change, retrieve cached results.

I can use something like a search param to set TTL to 0, but I'd rather not expose this ability to users. And it's not a guarantee that visiting this page without the search param later will show the updated results.

## Suggested solution

Have the ability to explicitly cache bust on updates.

I think the best way to do this all server-side is to allow a Prisma update to reference a find.

```
prisma.update({
  cacheBust: [prisma.findUnique(...)]
  ...
})
```

## Alternative Solution

Or maybe it would make sense to have a simple function that could programmatically invalidate a specific query. Pulling a little inspiration from TanStack Query and NextJS here.

`cacheBust(['queryKey1', 'queryKey2']) `

`invalidate(['queryKey1', 'queryKey2'])`

**Comment by nurul3101** [comment]
Hi @eglove 👋 

Thank you for trying out Accelerate and sharing the feature request. 
We have noted this in our internal tool for managing Accelerate feedback and feature requests.
We will get back to you once we have an update.

I'll close the GitHub Issue here, as this repository is for managing our open-source product: Prisma ORM and not our commercial products.

Thank you so much for taking the time to share this request! 🙏
