### ISSUE TITLE
Prisma Accelerate is down

### ISSUE THREAD

**Issue by azuy212** [prisma/prisma#21753]
### Bug description

I am unable to query my database using Prisma Client which is using Accelerate. Each db request is giving the following error

`Unknown server error: {\"type\":\"UnknownJsonError\",\"body\":{\"code\":\"P6000\",\"message\":\"QE-Agent returned a malformed JSON response\"}} (The request id was: 81fed75b4f1e0628)`

I went `console.prisma.io` and when try to open Manage Accelerate it shows the following error:

<img width="1000" alt="Screenshot 2023-11-03 at 12 41 34 AM" src="https://github.com/prisma/prisma/assets/31723896/8d1752df-28e6-4fde-bbe8-16d7875b6d71">

Seems like Accelerate is down.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 16.20.0

### Prisma Version

```
5.4.2
```

**Comment by frederichoule** [comment]
Same problem here.

**Comment by iqbal125** [comment]
Same, thanks, I thought I was doing something wrong.

**Comment by dshongphuc** [comment]
I got the same problem, this is the log
![Screenshot from 2023-11-03 10-23-54](https://github.com/prisma/prisma/assets/19908411/244fbf1e-db41-4f4a-b0da-95e945a98010)

**Comment by nnennajohn** [comment]
I got the same error.

<img width="1189" alt="Screenshot 2023-11-03 at 1 01 58 AM" src="https://github.com/prisma/prisma/assets/1761197/932c3144-e51e-4ec5-a143-f3b3c84cea86">

**Comment by peaushrai** [comment]
![Screenshot 2023-11-03 111138](https://github.com/prisma/prisma/assets/134382066/42bad41e-c8df-4d96-b6c6-92e9b7b57a08)

**Comment by amitav13** [comment]
Happening with 5.5.2 as well

**Comment by dshongphuc** [comment]
Cloudflare has some issues: https://www.cloudflarestatus.com/
I guess this issue was probably affected, so I tried disabling the ipV6 on my computer, after that, this issue was solved. 
I'm not 100% sure about this, but you can give it a try or also try to use a VPN

**Comment by nurul3101** [comment]
As @dshongphuc mentioned, Prisma Accelerate is affected by the Cloudflare outage: https://www.cloudflarestatus.com/incidents/hm7491k53ppg

Our services should be restored as soon as the Cloudflare outage is resolved.
Our status page shows the current status of the incident: https://www.prisma-status.com/

We have started an investigation on our end to prevent our services from being affected by these kinds of 3rd party outages.

I am closing this issue as this repository is for Prisma ORM and not our commercial products. Please feel free to send an email to support@prisma.io for any queries related to Prisma Accelerate.

We appreciate your patience while we deal with this issue 🙏
