### ISSUE TITLE
Error: P1010: User `postgres.$HOST` was denied access on the database `postgres.public`

### ISSUE THREAD

**Issue by Armadillidiid** [prisma/prisma#21777]
### Bug description

I get the following error when I try to migrate to my database provided by supabase.

Error: P1010: User `postgres.$HOST` was denied access on the database `postgres.public`

Here is my `DATABASE_URL` and `DIRECT_URL`: 
```env
DATABASE_URL="postgresql://postgres:$PASSWORD@db.$HOST.supabase.co:5432/postgres?schema=sample"

DIRECT_URL="postgres://postgres.$HOST:$PASSWORD@aws-0-us-east-1.pooler.supabase.com:5432/postgres?pgbouncer=true"
```

Dependency version:

### How to reproduce

1. Run `prisma migrate dev --name init` in project folder

### Expected behavior

To be able to run `prisma migrate dev --name init` without P1010 error when the user has all the correct permissions.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider     = "postgresql"
  url          = env("DATABASE_URL")
  directUrl    = env("DIRECT_URL")
  relationMode = "prisma"
}
```

### Environment & setup

- OS: Arch Linux x86_64 
- Database: PostgreSQL
- Node.js version: v19.7.0

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/.pnpm/@prisma+engines@4.16.2/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/.pnpm/@prisma+engines@4.16.2/node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.
```

**Comment by janpio** [comment]
> `pooler.supabase.com:5432`

I think the pooler URL should have port 6543 and will not work as the direct URL.
Did you construct this URL yourself or did you copy from the Supabase UI?

**Comment by Armadillidiid** [comment]
Yes, you're correct. I had changed it in response to this [post](https://stackoverflow.com/questions/74876237/cant-migrate-schema-using-prisma-with-supabase) but I've reverted it. Now, I get this error with connection pool port `6543`:

```
✖ Introspecting based on datasource defined in prisma/schema.prisma

Error: db error: ERROR: prepared statement "s0" does not exist
```

**Comment by janpio** [comment]
If you use a connection pooler, you need to use (the now misnamed) pgbouncer mode: https://www.prisma.io/docs/guides/performance-and-optimization/connection-management/configure-pg-bouncer
(Note that for migrations and introspection, so the `directUrl`, you can not used a connection pooled connection string.)

**Comment by Armadillidiid** [comment]
Thanks for sharing the resource. I've updated my `DATABASE_URL` to use `pgBouncer` mode and `DIRECT_URL` to a  normal connection string. Migrations are perfectly working fine

```env
DATABASE_URL="postgresql://postgres:$PASSWORD@db.$HOST.supabase.co:5432/postgres?pgbouncer=true"

DIRECT_URL="postgresql://postgres:$PASSWORD@db.$HOST.supabase.co:5432/postgres"

```
