### ISSUE TITLE
Unable to bundle Prisma with `bun build`

### ISSUE THREAD

**Issue by marvinruder** [prisma/prisma#21785]
### Bug description

When bundling code that uses the Prisma Client using Bun, running the bundle with Bun shows the fatal error

```
ReferenceError: Can't find variable: __dirname
```

The error occurs at the bundled version of this line of code: https://github.com/prisma/prisma/blob/b56d18ac4aa892ea91db0549d2836b01fe52d017/packages/client/src/runtime/core/engines/common/resolveEnginePath.ts#L90

### How to reproduce

The following works in a blank GitHub codespace:

```bash
# Follow the Prisma quickstart guide
mkdir hello-prisma
cd hello-prisma
npm init -y
npm install typescript ts-node @types/node --save-dev
npx tsc --init
npm install prisma --save-dev
npx prisma init

# # Fill the Prisma schema with some models, e.g.
# model User {
#   id    Int     @id @default(autoincrement())
#   email String  @unique
#   name  String?
# }


# Install Bun
curl -fsSL https://bun.sh/install | bash
source ~/.bashrc

# Create example code file
touch script.ts 
# # Add the following content into `script.ts`:
# import { PrismaClient } from '@prisma/client'
# const prisma = new PrismaClient()

# Run `prisma generate`
bunx prisma generate

# Bundle example code file
bun build script.ts --outdir=./bun --target=bun

# Run bundle
bun ./bun/script.js
```

### Expected behavior

The created bundle runs without errors and is able to connect to a database.

### Prisma information

```prisma
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

```ts
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

### Environment & setup

Run on GitHub Codespace:

- OS: 
  - `NAME="Ubuntu"`
  - `VERSION="20.04.6 LTS (Focal Fossa)"`
- Database: N/A
- Node.js version: 20.8.1
- Bun version: 1.0.9

### Prisma Version

```
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
```

**Comment by janpio** [comment]
Did you also open an issue with bun? That line of code is fine for all other bundlers, so I would start figuring out if Bun is of the opinion that they are doing all the right things there.

**Comment by marvinruder** [comment]
I checked again today and found a more general issue https://github.com/oven-sh/bun/issues/5094 that also contains a workaround specifically for Prisma. I will use this for the moment and wait until Bun adresses the issue.
