### ISSUE TITLE
Side effect of casting enums to text on max aggregates

### ISSUE THREAD

**Issue by Dam-Buty** [prisma/prisma#21789]
### Bug description

Ever since we migrated to 5.4.2 we have noticed a bug on a script that depends on the "_max" aggregate function.

The `_max` aggregate on an ENUM column used to return "the highest enum value for this column" (highest in the ENUM's order), but now that ENUMs are cast to TEXT, `_max` returns the alphabetically last value.

We noticed that, at least in our case, the `orderBy` clause still gives the expected result of sorting the column by ENUM order.

### How to reproduce

* create an ENUM column on a table
* use the `aggregate` method on your table, specifically the `_max` function
  * the "max" returned by this query is the alphabetically last value, not the highest in terms of ENUM order
* use a `findFirst` with `orderBy` on the same column
  * the value returned is indeed the highest in the ENUM order

### Expected behavior

One would expect that both methods give the same result. Furthermore, i guess one would expect that a function such as `_max` respects the order of the ENUM.

### Prisma information

**Consider the following schema**

```prisma

enum EmployeeLevel {
  MANAGER
  VP
  C_LEVEL
}

model Employee {
  id                   Int  @id @default(autoincrement())
  companyId  Int
  level              EmployeeLevel
}
```

:red_circle:  **The method using _max will return VP as the max level (alphabetically)**

```ts
const aggregate = await prisma.employee.aggregate({
  _max: { level: true },
  where: { companyId: company.id },
});
```

> `SELECT MAX("level") FROM (SELECT "public"."Employee"."level"::text FROM "public"."Employee" WHERE "public"."Employee"."companyId" = $2 OFFSET $3) AS "sub"`

:green_circle: **The method using orderBy will return C_LEVEL as the max level (enum order)**

```ts
  const maxLevelEmployee = await prisma.employee.findFirst({
    where: { companyId: company.id },
    orderBy: { level: "desc" },
  });
```

> `SELECT "public"."Employee"."level" [...] FROM "public"."Employee" WHERE "public"."Employee"."companyId" = $2 ORDER BY "public"."Employee"."level" DESC`

### Environment & setup

- OS: Linux
- Database: PostgreSQL
- Node.js version: 18.17.1

### Prisma Version

spotted on 5.4.2, also present on 5.5.2

**Comment by janpio** [comment]
Thanks for the report @Dam-Buty, your analysis sounds valid. We'll reproduce and then figure out what to do here. Sorry for the regression here, definitely not intentional.

**Comment by Dam-Buty** [comment]
> Thanks for the report @Dam-Buty, your analysis sounds valid. We'll reproduce and then figure out what to do here. Sorry for the regression here, definitely not intentional.

That must be the fastest non-automated Github response in history. Thanks Jan your work is very much appreciated :metal:

**Comment by janpio** [comment]
I can reproduce what you describe, with your schema:

Code:
```
await prisma.employee.deleteMany()
await prisma.employee.createMany({
  data: [
    { companyId: 1, level: 'MANAGER' },
    { companyId: 1, level: 'VP' },
    { companyId: 1, level: 'C_LEVEL' },
    { companyId: 2, level: 'MANAGER' },
    { companyId: 2, level: 'VP' },
    { companyId: 2, level: 'C_LEVEL' },
  ]
})

const broken = await prisma.employee.aggregate({
  _max: { level: true },
  where: { companyId: 1 },
});
console.log({ broken })

const working = await prisma.employee.findFirst({
  where: { companyId: 1 },
  orderBy: { level: "desc" },
});
console.log({ working })
```

leads to this in 4.3.1:
```
prisma:query SELECT MAX("level") FROM (SELECT "public"."Employee"."level" FROM "public"."Employee" WHERE "public"."Employee"."companyId" = $1 OFFSET $2) AS "sub"
{ broken: { _max: { level: 'C_LEVEL' } } }
prisma:query SELECT "public"."Employee"."id", "public"."Employee"."companyId", "public"."Employee"."level" FROM "public"."Employee" WHERE "public"."Employee"."companyId" = $1 ORDER BY "public"."Employee"."level" DESC LIMIT $2 OFFSET $3
{ working: { id: 9, companyId: 1, level: 'C_LEVEL' } }
```

but then in 5.5.2:
```
prisma:query SELECT MAX("level") FROM (SELECT "public"."Employee"."level"::text FROM "public"."Employee" WHERE "public"."Employee"."companyId" = $1 OFFSET $2) AS "sub"
{ broken: { _max: { level: 'VP' } } }
prisma:query SELECT "public"."Employee"."id", "public"."Employee"."companyId", "public"."Employee"."level"::text FROM "public"."Employee" WHERE "public"."Employee"."companyId" = $1 ORDER BY "public"."Employee"."level" DESC LIMIT $2 OFFSET $3
{ working: { id: 15, companyId: 1, level: 'C_LEVEL' } }
```

The `::text` cast definitely changed the result here.
