### ISSUE TITLE
Prisma misbehaving with mongodb

### ISSUE THREAD

**Issue by ranjanmangla1** [prisma/prisma#21781]
Hi Prisma Team! The following command just crashed.

## Command

`db pull --force`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-3.0.x| 
| Node        | v20.2.0            | 
| Prisma CLI  | 5.5.2              | 
| Engine      | aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a| 

## Error
```
RustPanic: Error in Schema engine.
Reason: [schema-engine/connectors/schema-connector/src/introspection_context.rs:51:76] called `Result::unwrap()` on an `Err` value: "error: The generator \"client\" cannot be defined because a generator with that name already exists.\n  -->  schema.prisma:8\n   | \n 7 | }\n 8 | generator client {\n   | \n"

```

**Comment by janpio** [comment]
> `The generator \"client\" cannot be defined because a generator with that name already exists`

Is it possible that you have two `generator "client"` in your Prisma schema file?

What does your current Prisma schema file look like?

**Comment by SevInf** [comment]
Hey @ranjanmangla1  ,

Did you get a chance to have a look at @janpio comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment]
As we've tried to reach @ranjanmangla1 twice without success, we're now closing this issue.
Please leave a comment below with the [required information](https://github.com/prisma/prisma/issues/21781#issuecomment-1794476544) if you see this issue, and we'll reopen it. Thanks!
