### ISSUE TITLE
Reset command for Prisma2 CLI

### ISSUE THREAD

**Issue by sashman** [prisma/prisma#2180]
## Problem

Prisma 1 has the `reset` command which is incredibly handy for rapidly iterating your DB schema. 

## Solution

Add an equivalent command to Prisma 2 cli.

## Alternatives

An option is to drop the database and run:

```
prisma migrate save --experimental
```

**Comment by pantharshit00** [comment]
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/742

**Comment by riezahughes** [comment]
Is there any word on this at all?
