### ISSUE TITLE
Introspection Regression "Error validating: The argument `references` must refer to a unique criteria in the related model `pages_language`. But it is referencing the following fields that are not a unique criteria: page_id"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2182]
Internal discussion: https://prisma-company.slack.com/archives/CGLQ50TK2/p1586365212104400

**Comment by mavilein** [comment]
Internal Note: This is a specialty of MySQL. It allows to reference non unique columns in a foreign key. It is not recommended practice though. Hence we will loosen validation only for this connector.

**Comment by mavilein** [comment]
fixed in: https://github.com/prisma/prisma-engines/pull/673
