### ISSUE TITLE
Expected parent IDs to be set when ordering by parent ID.

### ISSUE THREAD

**Issue by zoelesv** [prisma/prisma#21821]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.17.1           | 
| OS              | darwin-arm64       |
| Prisma Client   | in-memory          |
| Query Engine    | 61e140623197a131c2a6189271ffee05a7aa9a59|
| Database        | mysql              |

## Logs
```
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library already starting, this.libraryStarted: false
prisma:client:libraryEngine library started
```

## Prisma Engine Query
```
Query:
{
  "modelName": "Group",
  "operation": "findMany",
  "args": {
    "take": 100,
    "skip": 0,
    "select": {
      "id": true,
      "createdAt": true,
      "updatedAt": true,
      "name": true,
      "entries": {
        "select": {
          "id": true
        }
      },
      "analyses": {
        "select": {
          "id": true
        }
      },
      "description": true,
      "userId": true,
      "user": true
    }
  }
}
  
```
Please let me know how to fix this problem, it was working fine 2 weeks ago with the same query.

**Comment by millsp** [comment]
Hey @zoelesv could you please help us with a reproduction? Did this happen while using Prisma Studio?

**Comment by zoelesv** [comment]
Yes, this happened while using Prisma Studio.

**Comment by millsp** [comment]
Could you please provide more context. Can you try to run Studio with the `DEBUG="prisma:*"` environment variable?

**Comment by SevInf** [comment]
Hey @zoelesv  ,

Did you get a chance to have a look at @millsp  previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment]
As we've tried to reach @zoelesv twice without success, we're now closing this issue.
Please leave a comment below with a reply to [this message](https://github.com/prisma/prisma/issues/21821#issuecomment-1799353125) if you see this issue, and we'll reopen it. Thanks!
