### ISSUE TITLE
Proposal: Enhance Prisma `upsert` Method with Callback Support

### ISSUE THREAD

**Issue by tak0m0** [prisma/prisma#21841]
# Proposal: Enhance Prisma `upsert` Method with Detailed Status Object

## Problem

Prisma's `upsert` method currently lacks the ability to provide detailed status information, such as whether an existing row was updated.

## Suggested solution

Enhance Prisma's `upsert` functionality to return a status object containing detailed information about the operation's outcome, specifically indicating whether an existing row was updated.

```javascript
const upsertResult = prisma.modelName.upsert({
  where: { /* conditions */ },
  create: { /* data for new row */ },
  update: { /* data for update */ },
});

// upsertResult contains detailed status information
const statusString = JSON.stringify({ updated: upsertResult.updated });
console.log(statusString);
// Output: '{"updated":true}' (if an existing row was updated) or '{"updated":false}' (if no existing row was updated)
```

## Alternatives

The current alternatives involve using transactions or subsequent queries to determine whether the `upsert` operation resulted in an update. Developers may manually execute a separate query to check if the target row exists before calling `upsert` to infer whether the operation was an update or creation. However, these alternatives are not as streamlined or intuitive as having a built-in detailed status return mechanism.

Another alternative is to use the existing `upsert` method and handle the differentiation between creation and update outside of Prisma, potentially leading to less organized and more error-prone code.

The proposed enhancement simplifies the workflow for developers by providing a direct and clear way to determine the outcome of the `upsert` operation, eliminating the need for additional queries or manual checks. This approach enhances the developer experience and ensures a more straightforward handling of create/update operations.

## Additional Considerations

Returning the `updated` status as a boolean value allows developers to easily stringify the status object for logging or other purposes. This simple and structured status information enhances the debugging process and aids in monitoring the application's behavior, providing valuable insights into the database interactions.

Moreover, the clear status reporting is particularly useful in scenarios involving complex business logic or multiple `upsert` operations within a transaction. Developers can make informed decisions based on the outcome of each individual `upsert` operation, ensuring data integrity and consistency.

By incorporating detailed status information directly into the `upsert` response, Prisma empowers developers to write cleaner, more efficient, and error-resistant code, aligning with the framework's goal of providing a seamless and developer-friendly ORM experience.

**Comment by millsp** [comment]
Hey, have you considered using a field in order to emulate that? For instance, I could imagine setting a unique ID in the `update` section and checking whether that was updated or created via the result. This could give you more granularity for nested relations for instance.

**Comment by tak0m0** [comment]
@millsp 
Thanks for your response and suggestion. Using a field to emulate the update status is a creative workaround, and I appreciate the idea of setting a unique ID in the update section for differentiation.

While this approach could work in certain scenarios, it might not cover all use cases, especially when dealing with more complex business logic or situations where multiple fields could be updated. Relying on a specific field to indicate the update status might not be as straightforward or flexible as having a dedicated status object.

Having a detailed status object directly returned by the upsert method would still provide a more streamlined and intuitive experience for developers. It would eliminate the need for additional checks or workarounds and ensure a consistent and clear way to determine the outcome of the upsert operation.

I understand that there might be different perspectives on this enhancement, and I'm open to further discussion or adjustments based on the team's considerations. The goal is to enhance the developer experience by providing a clean and direct mechanism for handling upsert outcomes.
