### ISSUE TITLE
Handling Unsupported Type Dimensions Error for HNSW Index with pgvector in Prisma Migrations

### ISSUE THREAD

**Issue by IchiharaGaku** [prisma/prisma#21850]
### Bug description

I am using pgvector as an extension with Prisma. 
With pgvector now at version 0.5.1, I want to use HNSW indexes. 
Since such definitions are not supported in the schema, I manually created a migration file and wrote the create index.

```sql
CREATE INDEX ON "Vector" USING hnsw (embedding vector_cosine_ops);
```

However, when I tried to migrate, the shadow database did not recognize that the embedding column of the unsupported type has dimensions, resulting in an error.

```yaml
npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "sample", schema "public" at "localhost:5432"

Error: P3006

Migration `20231107144953_hogehoge` failed to apply cleanly to the shadow database.
Error:
ERROR: column does not have dimensions
   0: schema_core::state::DevDiagnostic
             at schema-engine/core/src/state.rs:270
```

It's urgent for me to use HNSW, and I'd like to skip the shadow database check.
Is there any way to do this?

### Prisma information

```prisma
// Add your schema.prisma
model Vector {
  id                Int                          @id @default(autoincrement())
  ...
  embedding         Unsupported("vector(1536)")?
  embedding_content String
  metadata          Json?
  ...
}
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v18.16.1

### Prisma Version

```prisma
^5.5.2
```

**Comment by IchiharaGaku** [comment]
@janpio 
I have opened a new issue!

https://github.com/prisma/prisma/issues/13719#issuecomment-1801708962

**Comment by janpio** [comment]
Should the column have these dimension according to the migration history SQL?
If yes, that is what we need to figure out - why applying all the migrations from the migration history does not put the shadow database into the state where this SQL statement to add the index can succeed.

**Comment by IchiharaGaku** [comment]
Hi, @janpio 

To reproduce the error, I created a new repository, set up PostgreSQL and pgAdmin4 using docker-compose, installed Prisma via npm, and then proceeded to define the schema, manually create migration files, and manually create an index as before.

```sql
CREATE INDEX ON "Vector" USING hnsw (embedding vector_cosine_ops);
```

When I ran `npx migrate dev` in this new setup, surprisingly, the index creation succeeded.

So, I revisited the past migration.sql files. 
Upon comparing the migration.sql in the new repository with the previous ones, I noticed that the definition of the embedding column did not have dimensions assigned to it.

```sql
-- Column definition that caused the error
"embedding" vector,
```

```sql
// Column definition when the index creation succeeded
"embedding" vector(1536),
```

**Comment by janpio** [comment]
Yay, thanks for digging in here and figuring out the difference.

I have no explanation why the dimensions were missing on the field. Maybe you iterated on the schema and the migration file that was committed in the end was from an earlier version? I have not heard about anyone having the problem that Prisma drops that value, so I would guess it was something on your side.

Anayway, if someone else has the same problem they will probably find this issue now and can comment on it. I'll close the issue in the meantime.
