### ISSUE TITLE
OCC does not work with `relationMode=prisma`

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#21867]
Schema:

```prisma
datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

generator client {
  provider        = "prisma-client-js"
}

model Stuff {
  id      String @id @default(uuid())
  version Int    @default(0)
}

```

Code:

```ts
async function main() {
  await prisma.stuff.deleteMany()
  await prisma.stuff.create({
    data: {},
  })

  const doStuff = async () => {
    const resource = await prisma.stuff.findFirstOrThrow()
    await prisma.stuff.updateMany({
      where: { version: resource?.version },
      data: {
        version: { increment: 1 },
      },
    })
  }

 await Promise.all([
    doStuff(),
    doStuff(),
    doStuff(),
    doStuff(),
  ])

  console.log(await prisma.stuff.findFirst())
}

main()
```

This is expected to output `{ version: 1 }`, but the `version` in actual output is anywhere between 1 and 4. 

See also #21854 for failing test.

The fix, implemented in prisma/prisma-engines#3175 applied only to `relationMode = "foreignKeys"`, update queries, executed for `prisma` relation mode still use only primary keys of a fetched entity and do not cary over other filters:

```
prisma:query SELECT `tests`.`Stuff`.`id` FROM `tests`.`Stuff` WHERE `tests`.`Stuff`.`version` = ?
prisma:query UPDATE `tests`.`Stuff` SET `version` = (`tests`.`Stuff`.`version` + ?) WHERE (`tests`.`Stuff`.`id` IN (?) AND 1=1)
```

Correct variant with `relationMode = "foreignKeys":

```
UPDATE `tests`.`Stuff` SET `version` = (`tests`.`Stuff`.`version` + ?) WHERE `tests`.`Stuff`.`version` = ?
```

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
