### ISSUE TITLE
Default filters on a query

### ISSUE THREAD

**Issue by LarsKuijlenburg** [prisma/prisma#2187]
## Problem
I'm trying to implement some sort of default query on one of my objects, but can't seem to find a way to do this in the docs.

## Solution
Have a way to supply a query with a default filter (e.g. I only want to retrieve people with birth dates in a specific range). When querying for an object, this filter would be automatically applied without having to use a `where: {}` in the query.

## Alternatives
This can already be done by using a `where` in the query itself, supplying the date range

## Additional context
A use case where this functionality would be useful: 
I have a `Challenge` object which has the fields `startDate` and `stopDate`.

Only a single active challenge can be active at a time, this is determined by this date range (if the current date is between the startDate and stopDate). 

I'd prefer to return the active challenge only by default, supplying a different date range whenever we need something other than the active challenge.

 To return anything else than the active challenge, a different date could be passed using the `where` in the query

**Comment by thebiglabasky** [comment]
Hi @LarsKuijlenburg 
Unless I'm missing something, this is something we would advise you to centralize simply using a utility function returning your default settings. 
While this workaround isn't 100% ideal, and that default criteria could be interesting, I don't see us tackling this in the near future given what is currently envisioned: we want to expand support of certain standard SQL capabilities which aren't currently represented in the Prisma Client API (e.g. distinct, aggregations...)

I will now close this issue, but feel free to re-open if I misinterpreted something.
Thank you
