### ISSUE TITLE
Drop support for `Buffer` when using `bytes`, use `Uint8Array` instead

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#21895]
## Breaking change proposal

I propose the following breaking change, to drop support of `Buffer` when using `bytes` and return a `Uint8Array` instead.

> The [Buffer](https://nodejs.org/api/buffer.html) type has been the cornerstone for binary data handling in Node.js since the beginning. However, these days we have [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array), which is a native JavaScript type and works cross-platform. While Buffer is an instance of Uint8Array, it introduces numerous methods that are not available in other JavaScript environments. Consequently, code leveraging Buffer-specific methods needs polyfilling, preventing many valuable packages from being browser-compatible.

We are depending on an old `buffer` polyfill that is not really maintained anymore. This is necessary because we return `Buffer` for responses containing `bytes`. While this enables compatibility on Cloudflare Workers, it also adds around 30KB of bundle size. This library is based on an old version of the real `Buffer` implementation, and some tests are not passing anymore, or some things have diverged. Given these downsides, I suggest to move to a better standard.

## Migration path

> If you absolutely need to convert a Uint8Array to a Buffer, you can use Buffer.from(uint8Array) (copies the data) or Buffer.from(uint8Array.buffer, uint8Array.byteOffset, uint8Array.byteLength) (does not copy). However, there is usually a better way.

This provides an easy and clear way to migrate.

At the same time `bytes` is perhaps not the most common schema type, so that reduces the scope of the breaking change.

https://sindresorhus.com/blog/goodbye-nodejs-buffer

**Comment by jkomyno** [comment]
We current have a custom extension to overwrite model fields, and add custom fields as well. We may create a new extension that re-enables `Buffer` fields for those people who may still want to use them after upgrading to Prisma 6.
This would reduce the impact on this breaking change. Would this effort be worth it?

**Comment by jkomyno** [comment]
Other alternative to ease the breaking change: https://github.com/sindresorhus/uint8array-extras

**Comment by jkomyno** [comment]
We've done this already for Prisma 6.

**Comment by aqrln** [comment]
@jkomyno one thing this issue also talks about and we didn't do yet is dropping the `Buffer` polyfill. In Prisma 6 we changed the public API so that we could drop Buffer completely without a major release, but we still need to remove all internal `Buffer` usage (in particular, for base64 encoding/decoding), ensure none of our dependencies use `Buffer` internally too, and then drop the polyfill.
