### ISSUE TITLE
Error when inserting record with array enum column after `TRUNCATE`ing the table on CockroachDB: `placeholder $1 already has type string, cannot assign Color`

### ISSUE THREAD

**Issue by AndrewSouthpaw** [prisma/prisma#21901]
### Bug description

If you create a record that has an enum array column, then run `TRUNCATE`, then create another record, it produces an error. This is using the `TRUNCATE` code [recommended by Prisma for clearing test data](https://www.prisma.io/docs/concepts/components/prisma-client/crud#deleting-all-data-with-raw-sql--truncate).

This worked previously in v5.0.0, so my suspicion is there were some clever tricks used in the performance improvements of 5.1.0 ~ 5.5.0 and one of them causes this issue.

### How to reproduce

Visit https://github.com/AndrewSouthpaw/prisma-crdb-array-enum-bug-2023-11-11 to pull down a repro, instructions in the README.

### Expected behavior

You can truncate and then add more data.

### Prisma information

See the repro for more details, here's the basics in a condensed form:

```
model Test {
  id          String    @id @db.Uuid @default(dbgenerated("gen_random_uuid()"))
  colors       Color[] @default([])
}

enum Color {
  red
  blue
  green
}
```

And in test:

```ts
const resetData = async () => {
  // TRUNCATE code from https://www.prisma.io/docs/concepts/components/prisma-client/crud#deleting-all-data-with-raw-sql--truncate
};


it("breaks when using array enum type and truncate", async () => {
  await prisma.test.create({ data: { colors: ['blue'] }, });
  await resetData();
  await prisma.test.create({ data: { colors: ['red'] }, });  // <-- 💥 
});
```

### Environment & setup

- OS: macOS
- Database: CRDB v22 or v23
- Node.js version: 18.17.0

### Prisma Version

```
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
```

**Comment by janpio** [comment]
Reproduced with the provided queries.

Interestingly, just running the generated queries manually against CockroachDB does not cause the same error:

```sql
CREATE TYPE "Color" AS ENUM ('red', 'blue', 'green');

CREATE TABLE "Test" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "colors" "Color"[] DEFAULT ARRAY[]::"Color"[],

    CONSTRAINT "Test_pkey" PRIMARY KEY ("id")
);

INSERT INTO "public"."Test" ("colors") VALUES (ARRAY['blue']::"public"."Color"[]) RETURNING "public"."Test"."id", "public"."Test"."colors"::text[];

TRUNCATE TABLE "public"."Test" CASCADE;

INSERT INTO "public"."Test" ("colors") VALUES (ARRAY['blue']::"public"."Color"[]) RETURNING "public"."Test"."id", "public"."Test"."colors"::text[]:
```

Combined with the error message that speaks of a "placeholder", I think this is connected to the prepared statement that is created for the query. The placeholder is marked as type string for the first query, but somehow not for the second one. We might be missing a cast or similar in the query.
