### ISSUE TITLE
prisma TransientTransactionError in mongodb

### ISSUE THREAD

**Issue by debasispanigrahi** [prisma/prisma#21934]
I am using $transaction of prisma in mongodb using Nest. After performing two read operations for count and find many results are coming satisfactory. But after some duration of 1 minute, when i rehit that url TransientTransactionError error is coming. I have checked all my database security. there are no issue with these. Can u tell me Why this error is coming. This error is only coming when using transaction. After this error, when i rehit the url the error vanish and results are coming. What is the error code of this.
May be after comitting a transaction that session was not closed. Thanks in advance. Please fix the underlying bug.
![TransientTransactionError](https://github.com/prisma/prisma/assets/68457648/de9d4950-1c07-4dd2-b464-7b55d0b73b41)

**Comment by janpio** [comment]
Also exists as discussion: https://github.com/prisma/prisma/discussions/21933
