### ISSUE TITLE
Fail to migrate to remote postgresql server(aws ec2)

### ISSUE THREAD

**Issue by 2013-11390** [prisma/prisma#2194]
## Bug description

report id 3740

When I try to migrate to remote postgresql server in aws ec2 server.
It fails migration with message:
Environment variables loaded from ./prisma/.env
Response "Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: db error: ERROR: syntax error at or near \"NOT\")"
Got result for unknown id undefined
Error in migration engine: Apr 16 10:21:44.389  INFO migration_engine: Starting migration engine RPC server git_hash
="***"
Apr 16 10:21:44.415  INFO quaint::single: Starting a postgresql pool with 1 connections.
'When I try to migrate to local postgresql server. It works without an error.

## How to reproduce

1. Create a postgresql server in aws ec2 server. (I created with an elastic beanstalk)
2. Run prisma migrate save --experimental with remote postgresql server in .env
3. See error

## Expected behavior

Migration success

## Prisma information

datasource postgresql {
provider = "postgresql"
url = env("DATABASE_URL")
}

## Environment & setup

aws instance os:

NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

Database: POSTGRESQL9.2

**Comment by 2013-11390** [comment]
When I changed postgresql version with 9.5 in ec2. It success to migrate.

**Comment by pantharshit00** [comment]
Yep, we use the `ON CONFLICT` sql contruct which was added in pg 9.5 so that is expected.

I am going to close this.
