### ISSUE TITLE
Prisma Doesn't Recognize Crystal Linux distro

### ISSUE THREAD

**Issue by Imna29** [prisma/prisma#21955]
## Problem

Prisma doesn't recognize Crystal Linux. 

## Suggested solution

Add Crystal Linux to the list of known distros. 
[https://getcryst.al/site](https://getcryst.al/site)

## Additional context

Warning when running on Crystal:
```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "crystal". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
```

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
