### ISSUE TITLE
Generating client to custom location with Next.js is broken

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma#2195]
## Bug description

I'm using a custom schema location and custom prisma client location. And it's failing.

- Schema: `db/schema.prisma`
- Client: `db/.generated-prisma-client`

```
(node:1879) UnhandledPromiseRejectionWarning: Error: Query engine binary for current platform "darwin" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/query-engine-darwin")
Files in /:
  .DS_Store
  .VolumeIcon.icns
  .file
  .fseventsd
  .vol
  Applications
  Library
  Preboot
  System
  Users
  Volumes
  bin
  cores
  dev
  etc
  home
  opt
  private
  sbin
  tmp
  usr
  var
You already added the platform "native" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.
Please create an issue at https://github.com/prisma/prisma-client-js/issues/new
```

## How to reproduce

1. Check out https://github.com/blitz-js/blitz/pull/124: `git clone -b prisma-gen git@github.com:blitz-js/blitz.git`
2. `yarn`
3. `yarn build`
4. `cd examples/store`
5. Set your `DATABASE_URL` environment variable for postgres
6. `yarn blitz db migrate`
7. `yarn blitz start`
8. Open [http://localhost:3000/admin/products](http://localhost:3000/admin/products)
9. See error in console.

## Expected behavior

Should work

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- Prisma version: 2.0.0-alpha.1081"
- Node.js version: 12.6.1

**Comment by timsuchanek** [comment]
Update: I didn't look into this particular setup yet, but just tried out an isolated minimal project with a custom output path. That works.
So this is probably related to how Next/Blitz resolves paths / has to copy assets.

**Comment by flybayer** [comment]
@timsuchanek ok interesting... Blitz is compiling all the files into `.blitz/`. With this custom prisma client location, that means the prisma client files are getting moved into .blitz too, whereas it wasn't when inside node_modules.

I can look into this more, but not sure where to start in relation to debugging prisma client. Any ideas on where to look?

The prisma error message is about not finding the native engine in root, but maybe that's masking a more important thing?

**Comment by flybayer** [comment]
So looks like it is indeed an issue with us moving the prisma client files inside .blitz. I used a REPL to use prisma client in it's original location at `db/.generated-prisma-client` and that works correctly.

Any ideas why moving it is causing an issue?

**Comment by timsuchanek** [comment]
Interesting. I'm also seeing right now, that it's looking in `/`.
Sounds like moving the files is breaking our logic to find the engine.
One related problem can be this: https://github.com/zeit/next.js/issues/8251

**Comment by timsuchanek** [comment]
Yes, so after a bit more investigation: `__dirname` is set to `/`. Therefore Prisma looks in `/` for the binaries.
So you need to find out, how to set the `__dirname` properly with Next.js.

**Comment by timsuchanek** [comment]
If you need any option to override it, let us know, as it could be, that you have to use a custom solution like described here: https://github.com/zeit/next.js/issues/8251#issuecomment-605805766

**Comment by flybayer** [comment]
Ok, bummer..

We probably need some way to override it, but I'll see what I can do. Looks like it _might_ can be fixed with some webpack wizardry.

**Comment by flybayer** [comment]
So I think the solution may be to configure webpack to not transpile Prisma client. Usually by default anything in node_modules is not transpiled. 

Webpack transpilation is what is messing up __dirname

**Comment by pantharshit00** [comment]
@flybayer That is most like the issue. I also noticed if you add `mode: "serverless"` to next.config.js, next js tried to rewrite `__dirname` to root for some reason. Maybe try avoiding that if you are doing that somewhere in your code.

The core issue is with this webpack plugin which next js uses: https://github.com/zeit/webpack-asset-relocator-loader

There is a pending PR in there but it never got merged: https://github.com/zeit/webpack-asset-relocator-loader/pull/69

**Comment by hatchli** [comment]
Where can we follow updates on this? I can't proceed any further, not even by downgrading to earlier betas it seems. Is a fix coming in Beta 5?

**Comment by pantharshit00** [comment]
@hatchli This is something that Next.js will need to fix on their end. We are trying to investigate a workaround but no promises there.

**Comment by hatchli** [comment]
@pantharshit00 Oh! I understand. Okay, well thank you pantharshit00 for the update! As of Beta 5, I am able to deploy to Now successfully without this error, btw, using["native"] generator. The dev environment now --dev is the only place throwing the issue now, but that's not a breaking issue like the production failing was. Keep up the good work!

**Comment by pantharshit00** [comment]
That's great to hear that it worked for you :)

**Comment by vriad** [comment]
I solved this issue for myself by doing a couple things:

First, overriding the `node.__dirname` Webpack setting inside `next.config.js`.

```ts
// node.config.js

const CopyWebpackPlugin = require('copy-webpack-plugin'); // npm install copy-webpack-plugin
const path = require('path');

module.exports = {
  // stuff here
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {

    // copy binary into the appropriate locations within `.next/serverless`
    config.plugins.push(
      new CopyWebpackPlugin({
        patterns: [
          {

            // the custom location the binary is generated to
            from: path.join(
              __dirname,
              'path/to/binary/query-engine*', // glob pattern that matches all query-engines
            ),

            to: path.join(__dirname, '.next/serverless/pages/api'),
          },
        ],
      }),
    );

    // set to false
    config.node.__dirname = false;
    return config;
  },
};
```

This solution was first proposed [here](https://github.com/prisma/docs/issues/841). 

Related issues: 
- https://github.com/prisma/prisma/issues/2303
- https://github.com/prisma/prisma-client-js/issues/616
- https://github.com/prisma/prisma/issues/2195

**Comment by flybayer** [comment]
Perhaps that config could be added to https://github.com/prisma-labs/next-prisma-plugin?

**Comment by williamluke4** [comment]
WIP https://github.com/prisma-labs/next-prisma-plugin/pull/19

**Comment by williamluke4** [comment]
Hey @vriad could you share your setup? I'm having some difficulty getting this to work with `next` in dev mode

**Comment by vriad** [comment]
Hm I can't get this to work in dev mode either. I didn't think anything I did would have messed up the dev server...go figure. I keep getting this error:

```
Invalid `prisma.user.findOne()` invocation in\nwebpack-internal:///./api/getMe.ts:14:74\n\n\n  spawn generated/query-engine-darwin ENOENT"
```

I played around with this for some time and couldn't get both dev and prod to both work :/

**Comment by timsuchanek** [comment]
The fix did not yet work. There are some pieces left to fix for the Vercel platform.

**Comment by timsuchanek** [comment]
Update: We got most of this running now, the Vercel related bug is being tracked in https://github.com/vercel/nft/issues/159

**Comment by timsuchanek** [comment]
This will be fixed in https://github.com/vercel/vercel/pull/5455

**Comment by timsuchanek** [comment]
Just tried it out - I can confirm that this is fixed in the latest version.
Let me know if you face any further issues @colinhacks and @flybayer 🙂
