### ISSUE TITLE
Default name for migration folder shown but not used when no name is entered

### ISSUE THREAD

**Issue by olivierlacan** [prisma/prisma#21981]
### Bug description

If you create a schema change then run `prisma migrate dev` the prompt offers a migration directory name suggestion that isn't used if you press Enter despite appearing to be a default inferred name.

Instead it creates a directory with only the timestamp and and underscore as the name.

### How to reproduce

1. add new model to schema
2. run `prisma migrate dev`
3. enter `y`, press `Enter`
4. press `Enter` again instead of entering a migration name

```
✔ We need to reset the following schemas: "public" at "localhost:5432"
Do you want to continue? All data will be lost. … yes

Applying migration `0_init`
Applying migration `20231115075202_new_table`

The following migration(s) have been applied:

migrations/
  └─ 0_init/
    └─ migration.sql
  └─ 20231115075202_new_table/
    └─ migration.sql

✔ Enter a name for the new migration: …
Applying migration `20231115235133_`


The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20231115235133_/
    └─ migration.sql

Your database is now in sync with your schema.
```

### Expected behavior

It should default to using the default directory name shown in the prompt: `20231115075202_new_table`.

### Prisma information

N/A

### Environment & setup

prisma                  : 5.6.0
@prisma/client          : 5.6.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v18.16.0
Query Engine (Node-API) : libquery-engine e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at ../../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at ../../node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.6.0-32.e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Default Engines Hash    : e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Studio                  : 0.495.0
Preview Features        : multiSchema

### Prisma Version

5.6.0

**Comment by janpio** [comment]
Isn't `20231115075202_new_table` the name of an existing, previous migration?

**Comment by olivierlacan** [comment]
@janpio Sorry that wasn’t super clear, that’s the value I type along with the command but I think I’m just figuring out there’s no default positional arg assumption without the —name flag.

**Comment by olivierlacan** [comment]
Going to close this since I can't exactly remember in which circumstances it occurred. I'll reopen if I encounter it again.

**Comment by janpio** [comment]
As far as I know we indeed to not support any positional arguments, although the way this went bad is indeed weird. Please do come back to this if this ever happens again. Thanks.
