### ISSUE TITLE
Allow .dotfiles for `prisma init`

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#2198]
If you e.g. have a `.DS_Store` file in the folder, `prisma init` will not work.
We should probably allow all `.files`.

**Comment by Jolg42** [comment]
I guess it was an old thing as we check for the folder now
<img width="606" alt="Screen Shot 2020-04-16 at 16 01 01" src="https://user-images.githubusercontent.com/1328733/79465374-89953f80-7ffb-11ea-9d7a-61e0fc3c4bda.png">
