### ISSUE TITLE
Support `exactOptionalPropertyTypes`

### ISSUE THREAD

**Issue by leighman** [prisma/prisma#21985]
### Bug description

When I have `exactOptionalPropertyTypes` enabled in `tsconfig.json` there is difficulty interacting with prisma generated types.
The type generated for an id field in a `where` for example is
```
id?: string
```
and my id has type `string | undefined`
With `exactOptionalPropertyTypes` this means that I have to do
```
...(id ? {id} : undefined)
```

If the generated type was generated as `id?: string | undefined` then it would work

### How to reproduce

Enable `exactOptionalPropertyTypes` and write a `findUnique` using a `where`

### Prisma information

5.3

### Environment & setup

OSX, node 18

### Prisma Version

```

```

**Comment by VanCoding** [comment]
This is a duplicate of #10894
