### ISSUE TITLE
Can not generate MsSql schema

### ISSUE THREAD

**Issue by tddat15** [prisma/prisma#22033]
Hi Prisma Team! The following command just crashed.

## Command

`generate --schema=[redacted]`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.17.0           | 
| Prisma CLI  | 5.5.2              | 
| Engine      | aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a| 

## Error
```
RustPanic: RuntimeError: panicked at library/alloc/src/raw_vec.rs:534:5:
capacity overflow
```

**Comment by SevInf** [comment]
Hi @tddat15.
Could you share a schema you trying to generate the client from? We'll need this information in order to reproduce, and eventually, fix the issue.

Thank you!

**Comment by fabriciomoeller** [comment]
Hi, @SevInf 
[schema.zip](https://github.com/prisma/prisma/files/14104906/schema.zip)


I had the same error with sqlServer.

I attached the schema for you to analyze.

This schema was generated with the command

prism introspects

Thank you !

**Comment by janpio** [comment]
Just to make sure we understand.
You had the same problem as reported above, `RustPanic: RuntimeError: panicked at library/alloc/src/raw_vec.rs:534:5: capacity overflow` with the schema you attached, via `db pusll`? But then you succeeded in creating a Prisma schem anyway? How?

**Comment by Jolg42** [comment]
@tddat15 Did you have a chance to take a look at @janpio's comment above?

**Comment by tddat15** [comment]
sorry for this late response, the mail was sent to spam mail, I already fixed it
I was trying to pull schema from a MSSQL database with many schemas related to each other and this error appears
and the syntax of the schema is not correctly
then this table of warnings appears in the command line
and in the end, I fixed the syntax of the schema and problem-solved
that's all about my problem
cc: @Jolg42

**Comment by Jolg42** [comment]
Thanks @tddat15, happy that things are working for you now.
I'll close this for now, as it's unclear how we can reproduce this.

If someone is still experiencing this same issue, please open a new issue and provide all details to get to a reproduction.
