### ISSUE TITLE
Expose a logger interface

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#2204]
## Problem
Currently there are a lot of `console.error` calls in the `NodeEngine` and prisma client. This is problematic since it will not forward those logs to the proper transports.

## Solution
It would be better off to have a general logging interface with a default implementation to `console` that users can override to provider their own logger like winston.

## Alternatives
Collect logs from STDOUT and send them.

**EDIT1:**
Another alternative is to use the `.on` method ad explained here:  https://github.com/prisma/specs/tree/master/prisma-client-js#logging

**Comment by timsuchanek** [comment]
Thanks for creating the issue. This should probably just tie into the existing log levels have defined here:  https://github.com/prisma/specs/tree/master/prisma-client-js#logging

Note, that right now you can already do `prisma.on('info', e => logger.log(e.message))`

**Comment by Sytten** [comment]
@timsuchanek Should I open an issue to document that?
