### ISSUE TITLE
prisma generate is crashed 

### ISSUE THREAD

**Issue by BekturMuratov** [prisma/prisma#22044]
Hi Prisma Team! The following command just crashed.

## Command

`generate`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v18.17.1           | 
| Prisma CLI  | 5.6.0              | 
| Engine      | e95e739751f42d8ca026f6b910f5a2dc5adeaeee| 

## Error
```
RustPanic
```

**Comment by SevInf** [comment]
Hi @BekturMuratov.
Could you provide the schema and full command you were using when this happened? Thank you.

**Comment by janpio** [comment]
Hey @BekturMuratov, did you see Serhii's message? We need your help here. Thanks!

**Comment by BekturMuratov** [comment]
I pulled all the tables from a ready-made database that was developed in Java and there were about a thousand tables and when I tried to generate it it crashed

**Comment by BekturMuratov** [comment]
and I can’t show the database schema that was pulled together with the npx prisma db pull command because it’s too huge

**Comment by SevInf** [comment]
@BekturMuratov could you try to reduce the schema to the smallest amount where we could reproduce an issue? Without a reproduction, we won't be able to fix an issue.

**Comment by BekturMuratov** [comment]
> @BekturMuratov could you try to reduce the schema to the smallest amount where we could reproduce an issue? Without a reproduction, we won't be able to fix an issue.

I tried to create an API from a previously created huge database with about a thousand tables, and when I tried to launch the project and created a service in NESTJS that interconnected with prisma, I could not launch the project and it gave this error
