### ISSUE TITLE
CockroachDB: `virtual schema table not implemented: pg_catalog.pg_sequences`

### ISSUE THREAD

**Issue by swxtz** [prisma/prisma#22042]
Error on using connection URL for CockroachDB in insecure mode, I think this error can be an exception of the Rust itself or some other lib used in Prisma Engine

.env  -> `DATABASE_URL="postgresql://root@localhost:26257?sslmode=disable"`

command -> `pnpm prisma migrate dev`

prisma version -> `~5.6.0`

@prisma/client version -> `~5.6.0`

![image](https://github.com/prisma/prisma-engines/assets/82668127/842859ec-d9c4-4870-b404-78fe6491bd1d)

**Comment by janpio** [comment]
That is actually an error message from CockroachDB that `prisma migrate dev` just surfaces to you verbatim.
What version of CockroachDB are you talking to?

**Comment by swxtz** [comment]
v23.1.12 LTS via Docker on Arch Linux x64

**Comment by janpio** [comment]
That should not happen. What database do you want to talk to? Maybe add that as the path of your connection string `postgresql://root@localhost:26257/foo?sslmode=disable` - maybe that helps already.

**Comment by swxtz** [comment]
I was trying to use `defaultdb` on cockroachdb, I've already tried using this connection string, but it keeps giving me an error

**Comment by janpio** [comment]
Did you overcome this problem somehow @swxtz in the last few months or is this still happening?

Generally this is a direct error message from CockroachDB. If this is indeed universally the case that `pg_catalog.pg_sequences` is not implemented, we might need to skip that one query. Usually I can find an issue about missign support for these tables with CockroachDB, but not this time - so I am a bit confused.

**Comment by swxtz** [comment]
I changed the version of Prisma to 5.8.0, and it worked normally, but before changing I tested CockroachDB with another language (golang) and it worked normally, when I did the test I was still using Prisma 5.6.0 and the error connection persisted.

I didn't change the version of CockroachDB so I honestly don't know what I did to fix it

**Comment by janpio** [comment]
Ok, although this does not fully make sense to me, the important bit is that it now works for you. Thank you!

If anyone else has this problem, please open a new issue or comment here and we can reopen this with the additional information. Thanks!
