### ISSUE TITLE
Prisma `@@index` is creating a unique constraint instead of a normal index key

### ISSUE THREAD

**Issue by JefferyHus** [prisma/prisma#22059]
### Bug description

I am trying to index one column in my table using the keyword `@@index`, when I run the migration Prisma instead create another unique constraint on top of that index.

### How to reproduce

Create 2 models with an 1-to-N relationship, then index the foreignkey in the child table. Run prisma migrations and you should see a unique constraint. (NB: Use MySQL)

### Expected behavior

It should just do as described in the schema and not add anything else not mentioned out of the blue.

### Prisma information

```prisma
model users {
  id                  Int              @id @default(autoincrement())
  Credit              Credit[]

  @@map("users")
}

model Credit {
  id          Int       @id @default(autoincrement())
  userId      Int
  user        users     @relation(fields: [userId], references: [id])

  @@index(fields: [userId], map: "userID")
  @@map("credit")
}
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Ubuntu
- Database: MySQL
- Node.js version: 18

### Prisma Version

```
4.13.0
```

**Comment by janpio** [comment]
That is highly unlikely, that would have been noticed in the last few years that code has not been changed.

Can you reproduce this behavior and show us the SQL migration that `migrate dev` creates for this?
You are using a pretty old Prisma version though, can you please upgrade to a more recent first?

**Comment by SevInf** [comment]
@JefferyHus I can not reproduce the issue, neither on Prisma 5.6.0 nor on Prisma 4.13.0 that you reported. Generated SQL does not contain `UNIQUE INDEX` line unless I add `@unique` attribute on `userId`. Are you sure it was not the case when migration file was created?
If you, we'd ask you to provide clean repo where we can see that happening?

**Comment by JefferyHus** [comment]
I can confirm this to you. I have tried to remove the @@index from that model and it did not drop the index key nor the unique one. I will try to update to latest prisma and test.

**Comment by janpio** [comment]
Any update here @JefferyHus? It sounds a bit like you are looking at a different schema file than from what is used to create the SQL.

**Comment by JefferyHus** [comment]
I still have the issue, this must be due to the fact that I had to generate a schema from an existing database then edit the schema afterwards. We can close this issue for now as it might be affecting me alone.
