### ISSUE TITLE
Prisma queries very slow on AWS Lambda 

### ISSUE THREAD

**Issue by chrisfougner** [prisma/prisma#22071]
### Bug description

Queries are executing very slowly when using AWS lambda / Aurora (Postgres). I'm finding that even very basic findUnique queries take 600ms+ and often up to 2500ms. The same queries using Kysely takes ~150ms (and even that feels long to me).

I instrumented the query, and as far as I can tell the time is spent in building up the connection. 

<img width="404" alt="image" src="https://github.com/prisma/prisma/assets/30043591/a958c49b-7930-40ac-b530-7505edbc1b2d">

Note that the wall-clock time is the time to execute the prisma query (doesn't include any serverless cold-start latencies)

### How to reproduce

1. Create a simple endpoint on AWS lambda
2. Insert 10 records into the DB
3. Query the endpoint
4. See that the query execution is hundreds of ms.

### Expected behavior

Query execution time is around 4x faster

### Prisma information

```prisma
model Account {
  id       BigInt @id @default(autoincrement())
  publicId String @unique @db.VarChar(10)

  createdAt       DateTime         @default(now()) @map("created_at")
  members         Member[]
  status          String           @default("PENDING") // PENDING, ACTIVE, DISABLED
  timezone        String
}

model Member {
  id       BigInt @id @default(autoincrement())
  publicId String @unique @db.VarChar(10)

  accountId      BigInt        @map("account_id")
  avatar         String?
  createdAt      DateTime      @default(now()) @map("created_at")
  email          String        @unique
  firstName      String?       @map("first_name")
  isAccountOwner Boolean       @default(false) @map("is_account_owner")
  lastActivity   DateTime?     @map("last_activity")
  lastName       String?       @map("last_name")
  referralCode   String?       @unique @map("referral_code")

  @@index([accountId], name: "memberAccountIndex")
}
```

```ts
const member = await prisma.member.findUnique({
  where: {
    email,
  },
  select: {
    accountId: true,
    account: {
      select: {
        publicId: true,
      },
    },
  },
})
```

### Environment & setup

- OS: amd64 (AWS Lambda)
- Database: PostgreSQL
- Node.js version: 18

### Prisma Version

NB: This isn't quite accurate since it gets built for amd64 when deployed.

```
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at ../../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at ../../node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
Preview Features        : tracing
```

**Comment by SevInf** [comment]
Hi @chrisfougner.
When it comes to establishing connection, difference between `kysley`/`pg` and `prisma` is that prisma does ssl handshake by default where `pg` does not.  Could you try adding [`sslmode=disable`](https://www.prisma.io/docs/concepts/database-connectors/postgresql#arguments) to your connection string and see if it helps?

Thank you!

**Comment by janpio** [comment]
ping @chrisfougner

**Comment by jkomyno** [comment]
Hi @chrisfougner, as we couldn't get an answer the past two times, we're closing this issue.
Please leave a comment below with an answer to [this comment](https://github.com/prisma/prisma/issues/22071#issuecomment-1824077072), so that we can consider re-opening this issue again. Thanks!
