### ISSUE TITLE
Support MySQL SET type

### ISSUE THREAD

**Issue by tmokmss** [prisma/prisma#22087]
## Problem

Currently Prisma does not support [MySQL SET type ](https://dev.mysql.com/doc/refman/8.0/en/set.html).

## Suggested solution

Support `Set` type in `prisma.schema`.

```prisma
model SomeModel {
   someField Set('value1','value2',...)
}
```

## Additional context

Sorry if I'm missing any existing feature requests, or if it's already supported!

**Comment by SevInf** [comment]
Duplicate of #10620
