### ISSUE TITLE
User Credential field must be excluded by default when  recevie key user include true from any other table

### ISSUE THREAD

**Issue by hassan-debug** [prisma/prisma#22097]
### Bug description

I have role table when i use prisma.role.findMany({include:{user:true});
it return me its password field also 
same i try with other tables findmany method and add include user: true in query it exposes password

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by SevInf** [comment]
Closing in favor of existing feature request for `exclude` feature - #5042.
