### ISSUE TITLE
Choose database by env

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma#221]
When we follow this part of the website:

![image](https://user-images.githubusercontent.com/7302317/61719009-638c8880-ad64-11e9-8f23-299ef8caeac2.png)

we have that error because apparently we have to define both env variables

https://gist.github.com/yovanoc/a89db13c7e655e38866b815bc170ceb2

**Comment by sorenbs** [comment]
I am closing this as a duplicate of https://github.com/prisma/prisma/issues/1487

Please let me know if you feel these issues address different use cases. Thanks 🙏
