### ISSUE TITLE
schema.prisma comment with double quote occurs error

### ISSUE THREAD

**Issue by Q00** [prisma/prisma#2210]
## Bug description

```

/Users/kyu/Desktop/hakhak/hakhak/node_modules/@prisma/client/index.js:210
const dmmf = JSON.parse(dmmfString)
                  ^
SyntaxError: Unexpected token 앞 in JSON at position 4899
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/kyu/Desktop/hakhak/hakhak/node_modules/@prisma/client/index.js:210:19)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/kyu/Desktop/hakhak/hakhak/src/services/prisma.service.ts:62:16)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
```

A comment with double quote in schema.prisma occurs error about JSON parsing like below

- schema.prisma
```
// fin : 
// "앞으로
// 좋겠다!"

```

- @prisma/client/index.js
```
const dmmf = JSON.parse(dmmfString)
```

## How to reproduce

run my project ( ts-node main.ts )

## Expected behavior

In documentation properties, Prisma should escape quote or double quote.

## Prisma information

@prisma/cli          : 2.0.0-beta.2

## Environment & setup

- OS: [e.g. Mac OS, Windows, Debian, CentOS, ...]
- Database: [PostgreSQL, MySQL, MariaDB or SQLite]
- Prisma version: [Run `prisma -v` to see your Prisma version]
- Node.js version: [Run `node -v` to see your Node.js version]

**Comment by pantharshit00** [comment]
Hi,

Can you please provide a complete reproduction inside of a Git repository? I was unable to reproduce this in my reproduction attempt as shown below:
![image](https://user-images.githubusercontent.com/22195362/79684559-07518900-8250-11ea-834e-c5a0cb67f57b.png)

**Comment by Q00** [comment]
```
prisma generate
yarn dev
```
schema.prisma
![image](https://user-images.githubusercontent.com/31264094/79720369-65976e00-831b-11ea-8e8f-4178ba41aa1b.png)

prisma generate
![image](https://user-images.githubusercontent.com/31264094/79720401-75af4d80-831b-11ea-9d13-b4f4eb918bb7.png)

ts-node main.ts
![image](https://user-images.githubusercontent.com/31264094/79720424-8069e280-831b-11ea-9be4-942414e1657f.png)

when I delete double quote in schema.prisma, error disappears

**Comment by pantharshit00** [comment]
I am still unable to reproduce this:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/22195362/79729159-b358aa00-830c-11ea-8737-9386fc602ae8.png">

Can you please tell me which OS you are using and please paste the datamodel here once instead of the screenshot :pray:?

**Comment by Q00** [comment]
My prisma/client version was preview025.
I think that was the reason why I got error.
