### ISSUE TITLE
NixOS not recognised as a Linux distribution

### ISSUE THREAD

**Issue by GetPsyched** [prisma/prisma#22145]
## Problem

Prisma doesn't recognise NixOS as a GNU/Linux distribution yet.

## Suggested solution

Detect NixOS as a GNU/Linux distribution.

## Additional context

```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
```

**Comment by janpio** [comment]
Does it work with the fallback?

**Comment by GetPsyched** [comment]
I don't think so. I remember it erroring out but I fail to remember if it was Prisma's fault or unrelated. I've not gotten back to this yet; I'll mention here if I pick it back up.

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.

**Comment by ndom91** [comment]
Heads up NixOS folks, if you're having truoble, there's also a `prisma-engines` nixpkg that's helped me tons: https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=prisma-engines

For example, this is my `languages/node.nix` file: 
```nix
{ pkgs, input, unstablePkgs, ... }:
{
  home.packages = with pkgs; [
    nodejs_20
    unstablePkgs.nodePackages.pnpm
    unstablePkgs.bun
    openssl
    pkg-config
    vips # for sharp
    unstablePkgs.prisma-engines
    unstablePkgs.chromium
  ];

  # Prisma:
  programs.bash.sessionVariables.PRISMA_QUERY_ENGINE_LIBRARY = "${pkgs.prisma-engines}/lib/libquery_engine.node";
  programs.bash.sessionVariables.PRISMA_QUERY_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/query-engine";
  programs.bash.sessionVariables.PRISMA_SCHEMA_ENGINE_BINARY = "${pkgs.prisma-engines}/bin/schema-engine";
  programs.bash.sessionVariables.PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING = "1";
}
```

**Comment by GetPsyched** [comment]
Dropping in a shorter version that I use in my `flake.nix`:
```nix
devShell.${system} = with pkgs; mkShell {
  buildInputs = [ ... ];
  env = {
    PRISMA_QUERY_ENGINE_LIBRARY = "${prisma-engines}/lib/libquery_engine.node";
    PRISMA_QUERY_ENGINE_BINARY = "${prisma-engines}/bin/query-engine";
    PRISMA_SCHEMA_ENGINE_BINARY = "${prisma-engines}/bin/schema-engine";
  };
```
