### ISSUE TITLE
Document Prisma JS API (equivalent of Prisma CLI API but for JS)

### ISSUE THREAD

**Issue by crubier** [prisma/prisma#2214]
Hi, 

Here is my use case:

I want to automate tests, using the Jest framework. Before each test I can run a JS file to setup the graphql database. I would like, in this JS file, to be able to run commands such as `prisma reset` and `prisma import`. 

Of course I could do it using `exec` to run the CLI command from JS. but this is dirty.

I believe it is possible to access `prisma-cli-core` functions (or similar) from JS without having to spawn new processes. However there is no documentation related to that. I tried reading files such as https://github.com/graphcool/prisma/blob/master/cli/packages/prisma-cli-core/src/commands/reset/reset.ts but I am not sure this will work properly, and there is not documentation to call this function programmatically from js, as opposed to from the CLI.

**Comment by brikou** [comment]
I believe a good documentation should include testing part, and this feature is required when writing functional tests :+1:

**Comment by brikou** [comment]
@crubier for now instead of calling `exec()` I'm using `fetch`:

```js
await fetch("http://prisma:4466/private", {
    body: JSON.stringify({ query: "mutation { resetData }" }),
    headers: { "content-type": "application/json" },
    method: "post",
});
```

hope it helps
