### ISSUE TITLE
Significant increase in WriteIOPS on upgrading to Prisma 5.5.2

### ISSUE THREAD

**Issue by aliabbasrizvi** [prisma/prisma#22140]
### Bug description

After updating from Prisma 4.12.0 to 5.5.2 we noticed a significant increase in our WriteIOPS. We are using RDS with Postgres on AWS.

A few days after updating we started noticing a number of operations taking too long or timing out. On taking a closer look we saw a significant increase in our WriteIOPS during the time our code was deployed with Prisma 5.5.2 (see between November 15 to November 21). After reversing the change prior performance was restored

We had followed the migration guide: https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5 

Just wondering if there is a known issue or if we should try something different. 

<img width="1773" alt="Screenshot 2023-11-27 at 1 40 29 PM" src="https://github.com/prisma/prisma/assets/1548776/249f8555-ecc7-4de6-8d4f-3e3a22cad220">

### How to reproduce

Update from 4.12.0 to 5.5.2

### Prisma information

We used Prisma 5.5.2

Prisma is made available via a [NestJS module](https://docs.nestjs.com/modules)

```
import {
  Injectable,
  Logger,
  OnModuleDestroy,
  OnModuleInit,
} from '@nestjs/common'
import { PrismaClient } from '@prisma/client'

@Injectable()
export class PrismaService
  extends PrismaClient
  implements OnModuleInit, OnModuleDestroy
{
  private readonly logger: Logger = new Logger(PrismaService.name)
  loggingInterval = null
  constructor() {
    super({
      log: [
        {
          emit: 'event',
          level: 'query',
        },
        {
          emit: 'stdout',
          level: 'error',
        },
        {
          emit: 'stdout',
          level: 'warn',
        },
      ],
    })
  }
  async onModuleInit() {
    await this.$connect()
  }

  async onModuleDestroy() {
    await this.$disconnect()
  }
}
```

### Environment & setup

- OS: Alpine
- Database: Postgres
- Node.js version: 18.18.2

### Prisma Version

```
5.5.2
```

**Comment by janpio** [comment]
That does not look to good.

Could you maybe try to pinpoint it a bit further?
Does just upgrading to Prisam 5.0.0 already cause that problem?
Or just a further version? If so, which one?
That would let us figure out what might be going on here.

**Comment by aliabbasrizvi** [comment]
Ok, we are a bit reluctant to go to Prisma 5.x at the moment given it severely affected our production system. We will update to 4.16.2 and see if the issue exists there. 

Also open to recommendations on tools that might help us debug this locally.

**Comment by aliabbasrizvi** [comment]
We'll definitely like to update to the latest package because we want to be able to use read replicas. Would appreciate if there are any recommendations on tools we could use to see locally what is contributing to write IOPS increase?

**Comment by Weakky** [comment]
Hey @aliabbasrizvi,

We unfortunately can hardly reproduce your issue without further information. If there's anything you can do to help us, please let us know 🙏

**Comment by aliabbasrizvi** [comment]
We recently updated to 5.16.0 and things have been fine so far. Since our last update we have also updated how we query as well as updated indexes on our tables. I think a combination of things might have worked.

Going to close this issue out. Thank you.
