### ISSUE TITLE
Wrong Type after `isNot: null` `where` clause, still includes `| null`

### ISSUE THREAD

**Issue by PauloMolarinhoMattos** [prisma/prisma#22174]
### Bug description

I am using a findMany in table x, in the select i am including the table b, that has a fk to my table x. In the where clause i wrote that the table i am selecting cannot be null, using the isNot: null.

But the type generated is giving me that even with the isNot: null, the data from table b can be null "| null"

### Expected behavior

should consider table B as not being null

### Prisma information

```prisma
// Add your schema.prisma
I cant
```

```ts
// Add your code using Prisma Client
i cant
```

### Environment & setup

- OS: Debian
- Database: MySQL
- Node.js version: 18

### Prisma Version

```

```    "@prisma/client": "^5.6.0",
    "prisma": "^5.6.0",

**Comment by Weakky** [comment]
Hey @PauloMolarinhoMattos, we're closing this duplicate issue in favor of https://github.com/prisma/prisma/issues/20348
