### ISSUE TITLE
Count of related list

### ISSUE THREAD

**Issue by dborstelmann** [prisma/prisma#2217]
## Problem
Cannot get count of related field without querying all of their models.

## Solution
Something like model.relatedList().count();

## Additional context
I have a lot of models where I have many related lists on one model and I have a screen where I show the total counts of those related models.  When you click on the count you get the actual list.  So it would be nice to be able to use an aggregate function on a related list.  Then I can actually go fetch the list of models separately when they click on the total.

**Comment by Sytten** [comment]
Without knowing your schema, I can propose what we do:
1. Fetch from your `model` the relation scalar (if you don't already have it)
2. Issue a `count` with  a `where` clause that uses the relation scalar

**Comment by dborstelmann** [comment]
```prisma
model User {
  id             Int      @default(autoincrement()) @id
  createdAt      DateTime @default(now())
  followers      User[]   @relation("Follows", references: [id])
  following      User[]   @relation("Follows", references: [id])
}
```

here is my model, it's a self many to many relation.  How would you get follower count?

**Comment by Sytten** [comment]
Well this seems to be an old schema because there is not scalar field for the relation, so first you should upgrade to that and then it would be pretty easy to do.

**Comment by dborstelmann** [comment]
Sorry I pulled this right out of the docs: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#many-to-many-self-relations

Did I miss something about a better way to do this?

**Comment by Sytten** [comment]
Ha the problem is that its an implicit n-n relation, so under the hood it maintains another table. I am afraid this is a limitation right now. Creating an explicit relation would allow you to query it directly and do the count. So something like:
```prisma
model Follows {
  follower    User @relation("follower", fields: [followerId], references: [id])
  followerId  Int
  following   User @relation("following", fields: [followingId], references: [id])
  followingId Int

  @@id([followerId, followingId])
}

model User {
  id        Int       @default(autoincrement()) @id
  createdAt DateTime  @default(now())
  followers Follows[] @relation("follower")
  following Follows[] @relation("following")
}
```
With that you can do a query like:
```typescript
prisma.follows.count({ where: { followingId: 1 }})
```
That will give you all the Users who follow that User.

Might be good to add that example in the doc @nikolasburk

**Comment by dborstelmann** [comment]
Thanks a bunch!  I will do it.

**Comment by pantharshit00** [comment]
Yes, @Sytten's answer is correct here. You can't query an implicity self relation if you don't specify a join table. 


I going to mark this as a docs issue as I can see this example being quite useful.

**Comment by dborstelmann** [comment]
@Sytten Count doesn't take a where parameter, here is part of the type:

```
  upsert<T extends FollowsUpsertArgs>(
    args: Subset<T, FollowsUpsertArgs>
  ): CheckSelect<T, FollowsClient<Follows>, FollowsClient<FollowsGetPayload<T>>>
  /**
   * 
   */
  count(): Promise<number>
```

Any idea how to resolve?

**Comment by dborstelmann** [comment]
Nevermind, I just needed to update versions

**Comment by mhwelander** [comment]
Parameterized `count` docs now available here: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud#count

And I've added a `count` example on the filtering overview page that matches the answer here (get total # of posts for a particular user)
