### ISSUE TITLE
Postgres pool setting not taking into account when schema uses env variable

### ISSUE THREAD

**Issue by Tirke** [prisma/prisma#22177]
### Bug description

In our schema we use
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

Where DATABASE_URL=postgres://<user>:<password>@<db-url>:5432/<db_name>?connection_limit=10 set in our ECS task definition accessible in the env of the container containing the builded app.
**The builded app has no .env files included.**
We can still see errors like that in our app:
`Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 3)` Indicating that the increase is not effective.

### Expected behavior

We can set connection pool params using an env variable without using .env files.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native"]
  output          = "../../../../node_modules/@prisma/main-database"
  previewFeatures = ["tracing"]
}

datasource db {
  provider = "postgresql"
  url      = env("MAIN_DATABASE_URL")
}
```

```ts
import { type OnModuleInit, Injectable } from '@nestjs/common'
import { PrismaClient } from '@prisma/main-database'

@Injectable()
export class MainDatabaseService extends PrismaClient implements OnModuleInit {
  async onModuleInit() {
    await this.$connect()
  }
```

### Environment & setup

- OS: debian container
- Database: PostgreSQL
- Node.js version: v18.18.2

### Prisma Version

```
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules/.pnpm/@prisma+engines@5.5.2/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules/.pnpm/@prisma+engines@5.5.2/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
```

**Comment by janpio** [comment]
That would be very surprising, as this is the mechanism almost all Prisma users use to configure the `connection_limit`. I don't think your described problem can be true, or we would be drowning in issues about this problem. Maybe something else is going on?

Can you `console.log(process.env.MAIN_DATABASE_URL)` in your code to confirm that it _really_ outputs the correct connection string that you expect?

**Comment by Tirke** [comment]
We succeeded to make it work in the end, was surely a blip from our side, forgot to close sorry.
