### ISSUE TITLE
Emit an error event when the database connection is interrupted

### ISSUE THREAD

**Issue by queicherius** [prisma/prisma#2218]
## Bug description

Right now, when a live database connection is interrupted (e.g. the database is shut down), Prisma (Client) does not emit any events, or I can't find a way of getting an event.

## How to reproduce

- Connect with the client
- Shutdown the database

## Expected behavior

I want an event immediately when a connection fails, so I can kill the process (since in my environment often time it's just a network issue and restarting works).

Instead, it waits until the next database command comes in, then errors that one, but still doesn't emit any events

## Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Prisma version: 

```
@prisma/cli          : 2.0.0-beta.2
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /projects/nest-graphql/node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /projects/nest-graphql/node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /projects/nest-graphql/node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x
```

- Node.js version: v13.9.0

**Comment by queicherius** [comment]
Also on a side-note `prisma.connect()` does not actually initiate a database connection. I dont get an error when I call it and no DB is running. Instead I have to run `prisma.raw()` with a simple select.

**Comment by Sytten** [comment]
This could be combined with https://github.com/prisma/prisma/issues/2100#issuecomment-614701734
