### ISSUE TITLE
Allow to run whole client test suite with force-enabled preview features

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#22187]
At the moment for enabling a preview feature in a test suite we have to manually add it to each schema file. In the past, we have big overarching preview features where it would be very useful to be able to easily run the whole suite with them enabled. 
Additionally. we had conflicting preview features that worked when tested individually, but broke when used together.

We should implement the mechanism that would allow us to:

- Run test suite or particular test with the preview feature enabled, even if it is not explicitly specified in the tests schema
- Run whole test suite with all available preview features enabled
- Add CI job, running client suite with all preview features enabled, either as regular job or as nightly job that could also be triggered on PR on demand.

**Comment by millsp** [comment]
Next steps:
* Get a list of all preview features dynamically
* Update CI

**Comment by apolanc** [comment]
Since we're not actively working on this, I moved it to the backlog. Note that there's an open PR and this was previously in Review.
