### ISSUE TITLE
Prisma Accelerate - Prisma client runtime causes "Critical dependency" warning in Webpack 

### ISSUE THREAD

**Issue by timpetri** [prisma/prisma#22181]
### Bug description

`@prisma/client/scripts/default-index.js` triggers a Webpack warning

> Warning: in ../../node_modules/@prisma/client/scripts/default-index.js 31:32-39
>  Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
  
> in ../../node_modules/@prisma/client/scripts/default-index.js 33:41-67
>  Critical dependency: the request of a dependency is an expression

This is due the implementation of `getVersion` which calls `require` using a variable. 

```typescript
 get prismaVersion() {
      const atPrismaClientDir = path.dirname(require.resolve('@prisma/client/package.json'))
      const enginesVersionDir = require.resolve('@prisma/engines-version', { paths: [atPrismaClientDir] })
      const { version: client } = require('@prisma/client/package.json')
      const { enginesVersion: engine } = require(enginesVersionDir)

      return { client, engine }
    },
```

This is then in turned used by `withAccelerate > makeAccelerateExtension` in `/@prisma/extension-accelerate`.

A version of this has happened several times in the past: #6106, and #6327 

### How to reproduce

I'm using this in a setup that involves a monorepo (turborepo) using yarn workspaces and the following structures:
```
/node_modules
/packages/database/...{schema, exported client.ts, package.json}
/apps/backend/...{package.json,index.ts}
```

where the backend is a Serverless Framework application, and bundling/packaging is done using the `serverless-webpack` plugin.

### Prisma information

```typescript
import { PrismaClient } from '@prisma/client'
import { withAccelerate } from '@prisma/extension-accelerate'
import { fieldEncryptionExtension } from 'prisma-field-encryption'

declare global {
  // eslint-disable-next-line no-var
  var prisma: PrismaClient | undefined
}

export const prisma = global.prisma || new PrismaClient()

prisma.$extends(fieldEncryptionExtension()).$extends(withAccelerate())

if (process.env.NODE_ENV !== 'production') global.prisma = prisma
```

### Environment & setup

- OS: macOS
- Database: PostgresSQL 
- Node.js version: v16.14.2

### Prisma Version

```
4.16.2
```

### Accelerate version

```
0.6.0
```

**Comment by timpetri** [comment]
Updating to the latest version solved this problem for us.

**Comment by nurul3101** [comment]
Thank you for confirming! 🙏
