### ISSUE TITLE
Suggestions on the improvement of data model relationship writing

### ISSUE THREAD

**Issue by lglie** [prisma/prisma#2220]
## Problem
When the data model is large, the file becomes very large, and the corresponding maintenance becomes very inconvenient, especially for the writing of relational fields, which is easy to be confused

## Alternatives
It is recommended to only annotate the relation on one side and annotated  dot field name Following the data type, to the relation to represent the field name on the other side of the relations, In this way, @relation args such as name and foreign key can also be omitted,  Even @relation directive can be omitted if no args。like this:

```
model User {
  id      Int      @id @default(autoincrement())
}
model Profile {
  id      Int     @id @default(autoincrement())
  user    User.profile?
}
model Post {
  id         Int         @id @default(autoincrement())
  author     User.posts[]
}
model Category {
  id     Int     @id @default(autoincrement())
  posts  Post[].categories[]
}
```

This can reduce a lot of code and make the model look more concise and clear
## Additional context
Unique constraints can use object fields (Corresponds to the unique fields in the model), not just scalar fields. In this way, the name of the foreign key can be omitted

**Comment by thebiglabasky** [comment]
Hi @lglie 
We prefer to defer looking at relations syntax until we start designing support for NoSQL databases like Mongo. The implicit relations syntax comes with a lot of tradeoffs and implications for migrate and introspections, which means we prefer to stick to explicit relations expressions for the time being.
I'll keep this open to have your suggestion as input once we re-open that topic.
Thanks

**Comment by pantharshit00** [comment]
I am going to close this discussion as introducing this syntax would be a big breaking change now.
