### ISSUE TITLE
npm registry not found Prisma

### ISSUE THREAD

**Issue by toshits** [prisma/prisma#22216]
### Bug description

I am trying to run ```npx primsa migrate dev``` but I am facing below error

```
PS C:\D\LNode\prisma> npx primsa migrate dev
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/primsa - Not found
npm ERR! 404
npm ERR! 404  'primsa@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: C:\Users\msi\AppData\Local\npm-cache\_logs\2023-12-02T10_31_43_605Z-debug-0.log
```

Trying visiting to this URL -> https://registry.npmjs.org/primsa
The API response from the endpoint is not found. 

Note: The migrate command was working fine 8-9 hours ago

### How to reproduce

1. Install Prisma
2. Make a basic prisma schema
3. Try running ```npx primsa migrate dev```
4. The error will pop

Alternatively Visit - https://registry.npmjs.org/primsa

### Prisma information

```prisma

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User{
  id Int @id @default(autoincrement())
  name String
}
```

```ts
// Add your code using Prisma Client
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

### Environment & setup

- OS:  Windows 
- Database: MySQL 
- Node.js version:  v18.17.1

### Prisma Version

```
5.6.0
```

**Comment by jensengbg-michele-carmagnani** [comment]
I had the same issue and it was exactly a typo! thx

**Comment by Sajal0208** [comment]
OMg is this a bug or something. I had the bug with the exact samy typo too @jensengbg-michele-carmagnani

**Comment by asamad35** [comment]
> You have a typo there. It's `prisma`, not `primsa`. Note the switched `s` and `m`.

I had the same error. Thanks

**Comment by akhil-dignizant** [comment]
successfully wasted 2 hours on this damn typo. 😓

**Comment by arellak** [comment]
Ladies and gentlemen, it is an honor for me that we are all gathered here today. I made the same mistake.

**Comment by Keifeh** [comment]
Yep, me 2. ta.

**Comment by rrandrews** [comment]
Yep, that's why I'm here.

**Comment by kingwrcy** [comment]
Same here,thanks google search engine.

**Comment by YahiaBadr** [comment]
I can't imagine that too many people have fallen for this, take me beside you guys 😂

**Comment by sumrender** [comment]
+1 guys 😭
Had the same typo

**Comment by ashrafulislambd** [comment]
Welcome to the typo club

**Comment by beardedhorseman** [comment]
Welp, got the same error , typo mistake too

**Comment by vim-diesel** [comment]
so hasty to google that I didn't even read what I entered.

**Comment by calvincolton** [comment]
People of Primsa! I gather you here today...

**Comment by Bope142** [comment]
Prisma😂😂 I got some errors, just because I blindly trusted VS Code's terminal autocomplete. Lesson learned! 😅

**Comment by mohammed-almassri** [comment]
same error here 😁

**Comment by rishi5565** [comment]
Hey guys! New member here, guess I'm welcome to this club now :)

**Comment by Ankit1478** [comment]
successfully wasted 3 hours on this..

**Comment by HodeonArtz** [comment]
I even asked ChatGPT and still couldn't find the mistake 😂

**Comment by learykara** [comment]
no one here is crazy... clicking to copy the `npx prisma` command on [the getting started docs](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases-typescript-postgresql) copies the command with the typo, even tho its displayed without it 🙃

**Comment by zensyh** [comment]
im here because of the damn typo too :D

**Comment by itssduy** [comment]
the typo brought me here
