### ISSUE TITLE
Add FreeBSD 14 as a new platform

### ISSUE THREAD

**Issue by tinola** [prisma/prisma#22228]
### Bug description

After upgrade to FreeBSD 14-RELEASE I can build new engines, but client is failing:

`PrismaClientInitializationError: Unknown PRISMA_QUERY_ENGINE_LIBRARY freebsd14`

or

`Error: Unknown binary target freebsd14 in generator client.`

### Expected behavior

Please add "freebsd14" string to those files:

```
packages/fetch-engine/src/download.ts
packages/get-platform/src/getPlatform.ts
packages/get-platform/src/platforms.ts
```

### Prisma information

-

### Environment & setup

- OS: FreeBSD 14-RELEASE
- Database: PostgreSQL
- Node.js version: v18.18.2

### Prisma Version

```
5.5.2
```

**Comment by aqrln** [comment]
Thanks for the issue @tinola, would you mind opening a quick a PR? I think it probably just needs to be added in these places:
* https://github.com/prisma/prisma/blob/a55078557b1c529f67e6640a0e35650386ad20c4/packages/get-platform/src/platforms.ts#L27
* https://github.com/prisma/prisma/blob/a55078557b1c529f67e6640a0e35650386ad20c4/packages/get-platform/src/platforms.ts#L57
* https://github.com/prisma/prisma/blob/a55078557b1c529f67e6640a0e35650386ad20c4/packages/fetch-engine/src/download.ts#L79
It would be really cool if you could try that and check if it works on your system.

**Comment by tinola** [comment]
Hi, I've created [https://github.com/prisma/prisma/pull/22300](url).

I'd like to test, but I don't know how to do it.
`prisma` is one of many dependencies of https://github.com/sinamics/ztnet project, so I think  prisma client is downloading during `npm build` process straight from here.
