### ISSUE TITLE
Netlify deployment with Node 20 break Prisma (`Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x"`)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#22244]
As reported here: https://answers.netlify.com/t/new-builds-are-breaking-in-runtime-with-prisma-errors/107755/16

```
Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x".
This happened because Prisma Client was generated for "debian-openssl-1.1.x", but the actual deployment required "rhel-openssl-3.0.x".
Add "rhel-openssl-3.0.x" to binaryTargets in the "schema.prisma" file and run prisma generate after saving it:
\n\ngenerator client {\n provider = "prisma-client-js"\n binaryTargets = ["native", "rhel-openssl-3.0.x"]\n}
```

> We tried adding more binary targets to the schema file binaryTargets = [“native”, “rhel-openssl-3.0.x”] but then the error changes to

```
Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x".
\n\nThis is likely caused by tooling that has not copied "libquery_engine-rhel-openssl-3.0.x.so.node" to the deployment folder.
```
-----
When deploying on Netlify with Node 20 configured, the serverless function after deployment can not find the required query engine file. This is because the underlying image changed, and Prisma now defaults to OpenSSL3 instead of OpenSSL1.

**Comment by janpio** [comment]
Until we release a fix for this problem, please stay on Node 18 or lower with your Serverless Functions. That should avoid the problem.

**Comment by Jolg42** [comment]
I have a fix in progress, I am still working on it, more details will follow later/tomorrow.

You can try out this special work in progress version: 
```
npm install prisma@5.7.0-integration-netlify-node20.1
```
If you try it out let us know if it works, or not, any feedback will be appreciated!

**Comment by Jolg42** [comment]
If you want to try the fix that will be included in the release tomorrow, you can try out this version: `5.7.0-integration-netlify-node20.4` and let us know how it works for you.

**Comment by Jolg42** [comment]
Note: I'll write some details here tomorrow for alternative options for those who can't upgrade the Prisma version right away.

**Comment by JavascriptMick** [comment]
5.7.0 didn't work for me, so I did what it said in my prisma.schema file...
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-3.0.x"]
}
```

**Comment by Jolg42** [comment]
@JavascriptMick Could you open a new issue and provide the information we would need to help you in the issue template?

**Comment by mandado** [comment]
I'm have the same problema using version 5.7.0. but using aws lambda with layers.

I'm copying all `libquery_engine-*` from prisma to the layer following this path `tmp/prisma-engines`.

**Comment by janpio** [comment]
Then you don't really have the same problem if you are not using Netlify. Please open a new issue and fill the issue template @mandado. Thanks.

**Comment by PinkaminaDianePie** [comment]
does Prisma just throw away `binaryTargets` and tries to guess the query engine based on it's CI environment?
I've tried to set it to `binaryTargets = ["linux-arm64-openssl-3.0.x", "native"]`, but in the `.prisma/client` i have only `libquery_engine-rhel-openssl-1.0.x.so.node`. Is there any way to force Prisma to download query engines I've specified in schema?

**Comment by PinkaminaDianePie** [comment]
to anyone else with the same issue, if you deploy to multiple places from Netlify builds but Prisma doesn't respect your configs, like `binaryTargets` - run the build with `NETLIFY` unset, like this `NETLIFY= yarn prisma generate`. Prisma performs some black magic under the hood, so it won't respect your configs when you run it on Netlify.
