### ISSUE TITLE
`{ not: true }` doesn't return `null` results

### ISSUE THREAD

**Issue by alessiocancian** [prisma/prisma#22262]
### Bug description

I have a nullable boolean field with some null values on db, when I do a findMany with `{ not: true }` I only get false values and not the null ones.

### How to reproduce

![image](https://github.com/prisma/prisma/assets/18497523/7ab0f4cd-9bed-463e-9b0f-42b8c597cf02)

### Expected behavior

As stated on #9087 it should return null results

### Prisma information

```prisma
model Scan {
    id             String           @id @default(cuid())
    unconfirmed    Boolean?
}
```

```ts
await ctx.prisma.scan.findMany({
   where: {
      unconfirmed: { not: true },
   },
});
```

### Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: 18.16

### Prisma Version

```
5.6.0
```

**Comment by alessiocancian** [comment]
This is probably because of MySQL behavior: https://stackoverflow.com/questions/60352613/mysql-is-not-returning-records-with-null-value
So considering #9087 is Prisma result different for different databases?

**Comment by sebastiankade** [comment]
Yep confirming, same issue with postgres, to do with how `NOT unconfirmed = true` is different from `unconfirmed IS NOT true` and other variations... 

https://stackoverflow.com/questions/71791433/prisma-not-equal-to-true-filtering-incorrectly

**Comment by zolbayars** [comment]
It was working as expected in [the mentioned discussion](https://github.com/prisma/prisma/discussions/9087), so it got changed somewhere between 2021 and 2023? 🤔

**Comment by Weakky** [comment]
Hey folks, we're closing this issue in favor of https://github.com/prisma/prisma/issues/24252
