### ISSUE TITLE
Prisma Client's postinstall script might use a global installation of prisma1

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#2233]
## Bug description

If I have prisma1 installed globally (perhaps on an old machine) and I `npm install @prisma/client`, its postinstall script attempts to use the global `prisma` binary (from /usr/bin), if it exists, to generate Client. This leads to this error:

```
> @prisma/client@2.0.0-alpha.1107 postinstall /Users/siddhant/Code/studio/packages/server/node_modules/@prisma/client
> node scripts/postinstall.js

 ▸    Couldn’t find `prisma.yml` file. Are you in the right directory?
```

Looking at the `postinstall` script this error originated from, it looks like it attempts to run a global installation of `prisma` (albeit after some tests/conditions).

Note that I explicitly do not have @prisma/cli installed (or listed in my dependencies)

## How to reproduce

Have a global installationof prisma 1.
Run `npm install @prisma/client` in any directory.

## Expected behavior

I suppose the `postinstall` script should verify that the global installation of `prisma` is version 2 before it issues the `generate` command. If the postinsall script fails (as in my case), the entire installation process halts and I'm left with an incomplete `node_modules` directory.

## Prisma information

@prisma/client: 2.0.0-alpha.1107

## Environment & setup

- OS: macOS
- Database: Irrelevant
- Prisma version: 2.0.0-alpha.1107
- Node.js version: v13.10.1

**Comment by Sytten** [comment]
This is the repository for prisma 2. Head to https://github.com/prisma/prisma1 for prisma1 questions.

**Comment by madebysid** [comment]
@Sytten Oh maybe I wasn't clear enough, the issue is that the postinstall script of `prisma2` (@prisma/client) *might* try to use a global version of `prisma1` as if it was `prisma2` (if `prisma1` is installed globally)

**Comment by pantharshit00** [comment]
@madebysid I guess you have an outdated version. You need to globally install prisma 1 using `npm install -g prisma1` and it will install binary named `prisma1`

But I agree that we can improve the check and I can also reproduce this.

**Comment by timsuchanek** [comment]
Thanks for reporting @madebysid! This is indeed a bug in the postinstall code of Prisma 2, not Prisma 1.

I just fixed it and added a better error message
![image](https://user-images.githubusercontent.com/1094804/79853715-b0bb8a80-83c8-11ea-82b0-fe33324be069.png)
