### ISSUE TITLE
[PSL] Request: reuse `struct` definitions within  models

### ISSUE THREAD

**Issue by brandfactoryitalia** [prisma/prisma#22348]
It would be very useful in my opinion, the possibility of extending models in a way similar to this:

```prisma
struct BaseConnection {
    apiKey        String
    apiSecret   String
} 


model TelegramConnection {
    ...BaseConnection
    username    String
}

model WhatsappConnection {
    ...BaseConnection
    phone    String
}
```

In this way you can create models that have common fields without having to repeat them every time

**Comment by janpio** [comment]
This sounds like a duplicate of https://github.com/prisma/prisma/issues/2371, so I am closing this for now. If you feel your syntax suggestion adds something to the discussion there, please leave a comment. Thanks!
