### ISSUE TITLE
Prisma Warning on Ubuntu 20.04

### ISSUE THREAD

**Issue by saremeskandary** [prisma/prisma#22347]
### Bug description

When running a Next.js 13 app that utilizes Prisma on an Ubuntu 20.04 environment, a recurring warning is displayed in the console. The warning message is as follows:

``` bash
prisma:warn Prisma doesn't know which engines to download for the Linux distro "". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
```

### How to reproduce

1. Set up a Next.js 13 application with Prisma integration on an Ubuntu 20.04 environment.
2. Run the development server using the configured Prisma setup.
3. Observe the console output for the mentioned warning message.

### Expected behavior

The Prisma setup should identify the Linux distribution correctly and download the appropriate engines without displaying a warning.

### Prisma information

The warning message indicates that Prisma is unable to determine the Linux distribution and falls back to using Prisma engines built for "debian."

### Environment & setup

   ``` ts
// lib/prisma.ts
   import { PrismaClient } from "@prisma/client";

declare global {
  let prisma: PrismaClient | undefined;
}

const globalForPrisma = global as unknown as { prisma: PrismaClient };

export const prisma = globalForPrisma.prisma || new PrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;

export default prisma;

   ```
   
    "@next-auth/prisma-adapter": "^1.0.7",
    "@prisma/client": "^5.1.1",
    "prisma": "^5.7.0",

### Prisma Version

"prisma": "^5.7.0",

**Comment by jkomyno** [comment]
Hi @saremeskandary, I just wanted to highlight that the warning above doesn't impact Prisma's featutes: everything you are already familiar with is still available. We will take a look at why that warning appears, and remove it in future versions. 

Can you please report back the output you're getting from `cat /etc/os-release`?

Thanks!

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
