### ISSUE TITLE
Inconsistent column data: Malformed ObjectID: provided hex string representation must be exactly 12 bytes, instead got: "companionId", length 11.

### ISSUE THREAD

**Issue by dhanubalde** [prisma/prisma#22388]
Mongodb  Malformed ObjectID: provided hex string representation must be exactly 12 byte

**Comment by jkomyno** [comment]
Hi @dhanubalde, can you please provide more information about this? I would recommend opening a new issue directly via [this bug report template](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml), filling all the gaps and providing the info required therein. Thanks!

**Comment by bkmahapatra27** [comment]
(D:\Projects\remixxx\secure-cod\node_modules\@remix-run\router\router.ts:4011:16) {
13:53:47 │ remix │   code: 'P2023',
13:53:47 │ remix │   clientVersion: '4.16.2',
13:53:47 │ remix │   meta: {
13:53:47 │ remix │     message: 'Malformed ObjectID: provided hex string representation must 
be exactly 12 bytes, instead got: "offline_cod-app-testing.myshopify.com", length 37.'       
13:53:47 │ remix │   }

having the same issue

**Comment by janpio** [comment]
What is the connected schema for this @bkmahapatra27?

It look like you have a field defined as `@db.ObjectId` but the data returned is a normal string, `offline_cod-app-testing.myshopify.com` - and Prisma can not handle that of course as it does not find into an ObjectId.

**Comment by Jolg42** [comment]
@bkmahapatra27 Did you have a chance to take a look at @janpio's comment above?

**Comment by SevInf** [comment]
Hey @bkmahapatra27 ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Comment by huykon** [comment]
how to fix this issue?

**Comment by johnmoke** [comment]
> how to fix this issue?
Inconsistent column data: Malformed ObjectID: provided hex string representation must be exactly 12 bytes, instead got: "companionId", length 11.

Whatever schema you are trying to update , the issue here is that you have provided a 11 bytes hex string but this should be a 12 bytes hex String for example : ObjectID = "424003faba2a1bc851036b53" . So please ensure that you provide 12 bytes hex string the issue should go
