### ISSUE TITLE
`query` extensions are only called for top level models

### ISSUE THREAD

**Issue by Xetoxyc** [prisma/prisma#22396]
### Bug description

When updating or creating a model with nested objects (For example, Client > Person > Address) the extension is only called for the top level which causes unexpected behaviour.

It does not matter if you use $allModels or specify all models separately

The example is a pretty easy variant just to demonstrate the problem. This would happen whenever using a nested update/create/etc... which basically, if you want to use extension, make it impossible for you to use nested create/update/etc...

### How to reproduce

use following extension

```
const extendedClient =  prismaClient.$extends({
      query: {
        $allModels: {
          create: async ({ query, args }) => {
           
            args.data.extensionTestField = "super crazy calculated value";

            return query(args);
          },
        },
      },
    });
```

### Expected behavior

After a calling

```
extendedClient.testClient.create({
      data: {
        description: "test",
        testPersons: {
          create: {
            firstName: "test",
            testAddresses: {
              create: [
                {
                  street: "test",
                },
              ],
            },
          },
        },
      },
    });
```

every table should have `super crazy calculated value` set in field `extensionTestField`

### Prisma information

```prisma
model TestClient {
  id String @id @default(uuid())

  description String

  extensionTestField String?

  testPersons TestPerson[]

  @@map("client_test")
}

model TestPerson {
  id String @id @default(uuid())

  firstName String

  clientId String
  client   TestClient @relation(fields: [clientId], references: [id])

  extensionTestField String?

  testAddresses TestAddress[]

  @@map("person_test")
}

model TestAddress {
  id String @id @default(uuid())

  street String

  personId String     @map("person_id")
  person   TestPerson @relation(fields: [personId], references: [id])

  extensionTestField String?

  @@map("address_test")
}
```

### Environment & setup

nestJS with Prisma

### Prisma Version

```
5.6.0
```

**Comment by Xetoxyc** [comment]
@janpio could you test this behaviour and verify the bug ? Is my usage even the intended usage ?

In my opinion it should my expected behaviour should be the intended use. Otherwise it would completely strike the usage of nested updates.

**Comment by janpio** [comment]
Probably related: https://github.com/prisma/prisma/issues/24525

**Comment by Weakky** [comment]
Hey @Xetoxyc,

As @janpio mentioned, this behavior is expected and we already have a feature request opened. As such, we're closing this issue now in favor of https://github.com/prisma/prisma/issues/24525
