### ISSUE TITLE
Add the possibility of create or connect on update

### ISSUE THREAD

**Issue by dpilarsk** [prisma/prisma#2239]
## Problem
I'm updating a user with a list of hobbies, some can already exists and other none.

## Solution
When I'm update the hobbies, I want to have the possibility to connect when the hobby is in DB or create when it's not.

## Alternatives
Check for every hobbies and create them in the case they aren't in DB.

**Comment by pantharshit00** [comment]
This functionality is possible with the `upsert` query.

Please read the docs here about that: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud#upsert

**Comment by dpilarsk** [comment]
That's not what @ryands17 said me

**Comment by pantharshit00** [comment]
Wouldn't the following query work for your use case:
```js
 const hobbyData = [{ id: 'something' }] // get it from your source
  const user = { id: 'ck99o6i7r00003dycgyapg4cb' } // get this also from your source
  const test = await prisma.user.update({
    data: {
      hobby: {
        upsert: hobbyData.map((d) => ({
          create: d,
          update: d,
          where: { id: d.id },
        })),
      },
    },
    where: {
      id: user.id,
    },
  })
```

**Comment by captainko** [comment]
Hi @pantharshit00 is there any way we can save a list of hobbies with insert/update/delete at the same time.
