### ISSUE TITLE
SourceValidationError should be pretty printed

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#2240]
## Bug description

```
Error: Error: Error in datamodel: ErrorCollection { errors: [SourceValidationError { message: "The URL for datasource `db` must start with the protocol `sqlite://`.", source: "db", span: Span { start: 55, end: 73 } }] }
```

<img width="767" alt="Screen Shot 2020-04-20 at 16 28 07" src="https://user-images.githubusercontent.com/1328733/79763132-f114fd00-8323-11ea-9d9a-b94c739bf8c3.png">

## How to reproduce

prisma/schema.prisma file
```prisma
datasource db {
    provider = "sqlite"
    url      = "sqlite:./1093.db"
}

generator client {
    provider = "prisma-client-js"
}
```
Run `npx @prisma/cli@alpha introspect`

Enjoy!

## Expected behavior

The error should be pretty printed with a cursor pointing to the line.

## Environment & setup

- OS: Mac OS
- Database: SQLite
- Prisma version: 2.0.0-alpha.1108 (latest)

**Comment by hanfengcan** [comment]
the same as this issues， when I follow `Set up Prisma`

Error: Error in datamodel: ErrorCollection { errors: [SourceValidationError { message: "The URL for datasource `db` must start with the protocol `mysql://`.", source: "db", span: Span { start: 155, end: 174 } }] }
