### ISSUE TITLE
Prisma2 CLI setup message invisible in light terminal themes

### ISSUE THREAD

**Issue by emilyaviva** [prisma/prisma#2244]
## Bug description

Upon running `npm i -g prisma2`, the user is presented with an instructional message saying "The package prisma2 has been renamed to @prisma/cli" with instructions about what to do to install Prisma 2.0—but the message is not visible to users with light terminal profiles.

For example, Solarized Light, iTerm2 on macOS:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/12450261/79795583-03357200-8309-11ea-9f06-5beb8276edbd.png">

## How to reproduce
Change your terminal to a light theme and run `npm i -g prisma2`. You might get nothing visible, or you might get it in very faint gray. The text shows up ("bolded") when you select over it, like so:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/12450261/79795786-527ba280-8309-11ea-81ce-9e0004e554fc.png">

## Expected behavior
The message should be readable by users in light theme terminals.

## Environment & setup

- OS: macOS Catalina (10.15.4), using iTerm2 3.3.9 with Solarized Light theme built-in
- Database: n/a
- Prisma version: n/a
- Node.js version: 13.13.0 (npm 6.14.4)

**Comment by pantharshit00** [comment]
Thanks for reporting this! I can confirm this issue.

**Comment by pantharshit00** [comment]
Candidating this as it's been quite a while now and this seems to be an easy fix.

**Comment by janpio** [comment]
We are not changing the transition package any more.
