### ISSUE TITLE
[feature] Multiple sequences per table with autoincrement()

### ISSUE THREAD

**Issue by hornta** [prisma/prisma#22440]
## Problem
A great example of this is how GitHub issues & PR's get their own unique id starting from 1 and is incremented by 1 for each new issue/PR. If I were to implement this in Prisma by having all repositories issues & PR in the same table each issue & PR would be uniquely identifable with this id that is auto incremented across the whole table.

What I would want to do is to have the id for an issue/PR be a composite key [repository_id, issue_id] where the issue_id is a sequence unique for this repository id.

This schema would only get two sequences, one for repository and one for issue. I want multiple "issue id sequences" for each repository.

```prisma
model Repository {
  id        Int      @id @default(autoincrement())
  name      String
  createdAt DateTime @default(now())
  issues    Issue[]
}

model Issue {
  id           Int        @id @default(autoincrement())
  bio          String
  repository   Repository @relation(fields: [repositoryId], references: [id], onDelete: Cascade)
  repositoryId Int
}
```

## Suggested solution
Maybe one could specify the composite keys in autoincrement so Prisma can know to use which sequence when an insertion is happening.

```prisma
model Issue {
  id           Int        @default(autoincrement([repositoryId]))
  bio          String
  repository   Repository @relation(fields: [repositoryId], references: [id], onDelete: Cascade)
  repositoryId Int

  @@id([repositoryId, id])
}
```

I'm open to suggestions to implement this unique sequence in some other way than using Postgres sequences. Maybe this is already supported in Prisma but I have not been able to find it?

**Comment by janpio** [comment]
How does one actually solve this with PostgreSQL sequences, what would the SQL need to look like?
