### ISSUE TITLE
Error when adding the data to the table with one to many relation from prisma studio

### ISSUE THREAD

**Issue by Antenna00** [prisma/prisma#22441]
### Bug description

I encounter the error when adding data to the table with one to many relationship via prisma studio.

Here is data I have in category table:
![image](https://github.com/prisma/prisma/assets/85468264/4196efbf-3c82-4395-8a64-efa6c8ff3f38)

Here is what I am trying to commit to PostTest table
![image](https://github.com/prisma/prisma/assets/85468264/e6aef477-f772-4046-984f-6e4484502423)

### How to reproduce

1. Open prisma studio
2. Commit data tto PostTest table
3. Save Change

The way error shown in screen is as below.
![image](https://github.com/prisma/prisma/assets/85468264/6c474019-99cf-42d7-a287-a0facee7b789)

Error snippet extracted from inspecting html (I just extracted the first bit)

Failed to commit changes: 
Invalid `f=e.match(J2t)?.[1]??"",g=e.match(Q2t)?.[1]??null,v=e.match(Z2t)?.[1]??null,{getPrismaClient:E,PrismaClientKnownRequestError:x,PrismaClientRustPanicError:S,PrismaClientInitializationError:C,PrismaClientValidationError:A}=require(`${c.prismaClient}/runtime/${u}`),O=Buffer.from(e,"utf-8").toString("base64"),I=(0,GN.createHash)("sha256").update()` invocation in
...
...
Argument `connect` of type CategoryWhereUniqueInput needs at least one of `id` or `slug` arguments. Available options are marked with ?.

### Prisma information

```prisma

model Category {
  id    String  @id @default(cuid())
  slug  String  @unique
  title String
  img   String?
  Posts Post[]
  PostTest PostTest[]
}

model PostTest {
  id           String   @id @default(cuid())
  createdAt DateTime @default(now())
  slug         String   @unique
  title        String
  descMD       String
  thumbImgUrl  String?
  view         Int      @default(0)
  likes        Int
  userEmail    String

  cat  Category @relation(fields: [catSlug], references: [slug]) //When I delete this I can commit the data just fine.
  catSlug      String
  
  comments Comment[]
}
```

### Environment & setup

- OS: windows
- Database: PostgreSQL
- Node.js version: v18.17.1

### Prisma Version

```
prisma                  : 5.7.0
@prisma/client          : 5.7.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v18.17.1
Query Engine (Node-API) : libquery-engine 79fb5193cf0a8fdbef536e4b4a159cad677ab1b9 (at node_modules\@prisma\engines\query_engine-windows.dll.node)   
Schema Engine           : schema-engine-cli 79fb5193cf0a8fdbef536e4b4a159cad677ab1b9 (at node_modules\@prisma\engines\schema-engine-windows.exe)     
Schema Wasm             : @prisma/prisma-schema-wasm 5.7.0-41.79fb5193cf0a8fdbef536e4b4a159cad677ab1b9
Default Engines Hash    : 79fb5193cf0a8fdbef536e4b4a159cad677ab1b9
Studio                  : 0.495.0
```

**Comment by MattTrilsbach** [comment]
Hi, did you find a fix for this? I'm also experiencing a similar issue

**Comment by Antenna00** [comment]
@MattTrilsbach 

Yeah.
When entering the record with a foreign key, you have to explicitly pick which record it is relates to. 

In my case, apparently entering "coding" in catSlug wasn't enough but instead i had to click on cat{} column which opens up another table where you can tick a box and explicitly choose which record you want the record to be related with.
![image](https://github.com/prisma/prisma/assets/85468264/6193b72c-f7a5-4829-9e33-3c8815ba0384)

 I'm not sure if this is the case for you but hope this helps :)

**Comment by 0xrishavsharma** [comment]
Hey @Antenna00, thanks for the solution!
It worked and saved me a ton of time :)

This makes perfect sense. We have to explicitly mention which "category" this particular post belongs to and which "user" is publishing it. So, in my case I had two accounts logged in so had to select the user as well.

**Comment by winterdelta** [comment]
> Hey @Antenna00, thanks for the solution! It worked and saved me a ton of time :)
> 
> This makes perfect sense. We have to explicitly mention which "category" this particular post belongs to and which "user" is publishing it. So, in my case I had two accounts logged in so had to select the user as well.

A related issue for me was caused by **existing** data in a model that I wanted to associate with another model - what I did was set an existing field to optional? as a temp fix, my guess is that if I wipe that model of data it should map fine.

**Comment by sjkadali** [comment]
@Antenna00 , thanks for the fix.
