### ISSUE TITLE
The filters are strange, using some or every

### ISSUE THREAD

**Issue by adrianoresende** [prisma/prisma#2245]
## Bug description

In Slack someone helped me, but it looks like there is a bug.

I don't know how `some` and` every` work but I don't know what I'm doing wrong and I have no idea what is the best for this solution.

### Goal
Return nested items until a `type` is published, check the query below.

```js
return prisma.category.findMany({
  where: {
    componentGroup: {
      some: {
        components: {
          some: {
            published: true
          }
        }
      }
    }
  },
  include: {
    componentGroup: {
      include: {
        components: true
      }
    }
  }
})
```

## Result and expected behavior

With the specific filter (`where`) it should be with the result below, without empty items as I commented on the side.

```js
{
  "data": {
    "getComponentsType": [
      {
        "id": "8",
        "componentGroup": [
          {
            "id": "2", // It should not appear
            "components": []
          },
          {
            "id": "3",
            "components": [
              {
                "published": true
              },
              {
                "published": true
              },
              {
                "published": false // It should not appear
              }
            ]
          },
          {
            "id": "4", // It should not appear
            "components": [] 
          },
          {
            "id": "1",
            "components": [
              {
                "published": true
              },
              {
                "published": true
              },
              {
                "published": false // It should not appear
              }
            ]
          }
        ]
      },
      {
        "id": "6",
        "componentGroup": [
          {
            "id": "5",
            "components": [
              {
                "published": true
              },
              {
                "published": true
              }
            ]
          },
          {
            "id": "6", // It should not appear
            "components": []
          }
        ]
      }
    ]
  }
}
```

When I change `some` to` every`, the result is stranger and everything is wrong.

```js
{
  "data": {
    "getComponentsType": [
      {
        "id": "6",
        "componentGroup": [
          {
            "id": "5",
            "components": [
              {
                "published": true
              },
              {
                "published": true
              }
            ]
          },
          {
            "id": "6",
            "components": []
          }
        ]
      },
      {
        "id": "7", // I don't know why he appeared, don't exists any item, It should not appear
        "componentGroup": []
      }
    ]
  }
}
```

## Model information

```gql
type Component {
  id: ID!
  title: String!
  group: ComponentGroup!
  groupId: Int!
  published: Boolean
  updatedAt: String!
  createdAt: String!
}

type ComponentGroup {
  id: ID!
  title: String!
  category: Category!
  categoryId: Int!
  components: [Component]
}

type Category {
  id: ID!
  title: String!
  type: Type!
  componentGroup: [ComponentGroup]
}
```

## Environment & setup

- OS: MacOS 10.15.4
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.1
- Node.js version: v13.3.0

**Comment by pantharshit00** [comment]
You can perform the following query:
```
  const test = await prisma.category.findMany({
    include: {
      componentGroup: {
        where: {
          components: {
            some: {
              published: true,
            },
          },
        },
        include: {
          components: {
            where: {
              published: true,
            },
          },
        },
      },
    },
  })
```


`some` returns elements when any one of them matches the condition while `every` returns elements when all of them matches the condition. Problem with your query is you are including all of the components in the include so what have filtered so first it grabs the component group according to the condition then gets the internal items without any filter. So you will need to move the where to the includes instead.

**Comment by pantharshit00** [comment]
@adrianoresende The one that I post should already hide empties as already filters that.

Anyways, I opened a documentation issue about this here: https://github.com/prisma/prisma/issues/2264

**Comment by adrianoresende** [comment]
> The one that I post should already hide empties as already filters that.

But with the suggestion that you posted shows a type empty, where don't exist a component:

```js
{
  "data": {
    "getComponentsType": [
      {
        "id": "6",
        "componentGroup": [
          {
            "id": "5",
            "components": [
              {
                "published": true
              },
              {
                "published": true
              }
            ]
          }
        ]
      },
      {
        "id": "7",
        "componentGroup": [] // It should not appear
      },
      {
        "id": "8",
        "componentGroup": [
          {
            "id": "3",
            "components": [
              {
                "published": true
              },
              {
                "published": true
              }
            ]
          },
          {
            "id": "1",
            "components": [
              {
                "published": true
              },
              {
                "published": true
              }
            ]
          }
        ]
      }
    ]
  }
}
```

When I add that `where`, it solves.

**Comment by adrianoresende** [comment]
@pantharshit00  Still, is there a bug that shouldn't show an empty item where there is no object?
Are you going to adjust anything about that?

**Comment by pantharshit00** [comment]
I am pretty sure that code doesn't fetch empty records.

See I have the following data in the database. g 2 is the empty group:
![image](https://user-images.githubusercontent.com/22195362/80184983-376ea280-8629-11ea-9158-348b9eb3f823.png)
![image](https://user-images.githubusercontent.com/22195362/80184993-3b022980-8629-11ea-83f8-3ca1886dd254.png)
![image](https://user-images.githubusercontent.com/22195362/80185004-3e95b080-8629-11ea-96e4-dde3a33cac99.png)


I am using the following code:
```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient({
  log: ['query'],
})

async function main() {
  const test = await prisma.category.findMany({
    include: {
      componentGroup: {
        where: {
          components: {
            some: {
              published: true,
            },
          },
        },
        include: {
          components: {
            where: {
              published: true,
            },
          },
        },
      },
    },
  })
  console.dir(test, { depth: Infinity })
}
```

The result I get back:
![image](https://user-images.githubusercontent.com/22195362/80185049-566d3480-8629-11ea-81ef-0aed4b387db3.png)


So maybe try again with the latest version, otherwise, please send me a SQL dump of your database so that I can try reproducing this issue.

**Comment by adrianoresende** [comment]
@pantharshit00 

https://gist.github.com/adrianoresende/550a20e88e5faa889e99f95792b8672f

**Comment by pantharshit00** [comment]
@adrianoresende Sorry for a bit of a late response here. I further investigated this and I get it why you are getting a different response. You posted a GQL syntax in the first comment in the issue and I derived a datamodel from it in order to reproduce this and my datamodel doesn't match with your. Yes, you will need to add the `where` in order skip empty groups according to your datamodel.

**Comment by adrianoresende** [comment]
Thanks for the investigation and patience, fly Prisma ;)

**Comment by jelmd** [comment]
The documentation for 'some' and 'every' are still absolutely confusing. Behavior of `some` is like `OR` and `every` is like `AND`? If so, why isn't it named like this? Or does `some` return not all records, which match the where clause? If so, how many records will it return by default and why isn't it documented?

IMHO good documentation should explain the difference between both w/o self-referencing words, and if it is that confusing, examples should be shown, which return different results for the **same** relationship or/and show the resulting SQL statement/query.

**Comment by jharrell** [comment]
@jelmd thank you for the feedback! Could you [open a docs issue](https://github.com/prisma/docs/issues/new?assignees=&labels=docs&projects=&template=doc_request.md) so that we can improve the docs? Definitely want to make this experience better.
