### ISSUE TITLE
Next.js transpilation breaks neon driver adapter

### ISSUE THREAD

**Issue by mmachatschek** [prisma/prisma#22469]
### Bug description

Next.js seems to break the prisma driver adapters when package transpilation is used.

I created a reproduction repo (see below) that shows the issue.

I specifically added `@neondatabase/serverless` to transpiledPackages in the nextjs.config.js.

My usecase is that we export prisma in a monorepo workspace (in a different project) that is transpiled by nextjs. In that process webpack and prisma lose the configured type parser from here: https://github.com/prisma/prisma/blob/main/packages/adapter-neon/src/conversion.ts#L265-L338

In order to workaround this issue one can readd these parser functions like I do here: https://github.com/mmachatschek/repro_nextjs_neon_driveradapter_issue/blob/main/nextjs/src/pages/api/prisma.ts#L19-L23 and make everything work again

the error looks like this:
```
Inconsistent column data: Conversion failed: expected a string in column 'createdAt', found {}
    at si.handleRequestError (/Users/markus/repro_esm_cjs_neondb_issue/nextjs/node_modules/@prisma/client/runtime/library.js:125:6817)
    at si.handleAndLogRequestError (/Users/markus/repro_esm_cjs_neondb_issue/nextjs/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/Users/markus/repro_esm_cjs_neondb_issue/nextjs/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/Users/markus/repro_esm_cjs_neondb_issue/nextjs/node_modules/@prisma/client/runtime/library.js:130:9805)
    at async handler (webpack-internal:///(api)/./src/pages/api/prisma.ts:36:22)
```

### How to reproduce

Clone the repo https://github.com/mmachatschek/repro_nextjs_neon_driveradapter_issue

1. Spin up postgres with a neon proxy for local testing: `docker compose up -d`
1. Install deps `cd nextjs && npm install`
1. Migrate `DATABASE_URL=postgres://postgres:postgres@localhost:5432/db npm run migrate`
1. Add a record in the database on the `Article` table
1. Start nextjs dev server `DATABASE_URL=postgres://postgres:postgres@localhost:5432/db npm run dev`
1. Call the nextjs route `POST http://localhost:3000/api/prisma`
1. See error in console

### Expected behavior

The query is correctly executed and the database records are returned.

### Prisma information

Reproduction repo https://github.com/mmachatschek/repro_nextjs_neon_driveradapter_issue

### Environment & setup

- OS: independent
- Database: postgres 15 with ws proxy or neon database
- Node.js version: node 20

### Prisma Version

```
prisma                  : 5.8.0-dev.38
@prisma/client          : 5.8.0-dev.38
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.9.0
Query Engine (Node-API) : libquery-engine e78ce01346936f624c1ca1f087385a25ee17b5bb (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli e78ce01346936f624c1ca1f087385a25ee17b5bb (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.8.0-21.e78ce01346936f624c1ca1f087385a25ee17b5bb
Default Engines Hash    : e78ce01346936f624c1ca1f087385a25ee17b5bb
Studio                  : 0.497.0
Preview Features        : driverAdapters
```

**Comment by mmachatschek** [comment]
If needed I can cross post this issue on the next.js repo too.

**Comment by mmachatschek** [comment]
@andyjy  I added the `transpiledModules` for the sake of reproduction. We have a internal package (in our codebase) that exports a CMS which uses prisma. That internal package is used in the nextjs project so that internal package needs to transpiled. 

you would need to replace `@neondatabase/serverless` with that internal package that consumes that package and you will get the same error as I described

**Comment by andyjy** [comment]
> We have a internal package (in our codebase) that exports a CMS which uses prisma. That internal package is used in the nextjs project so that internal package needs to transpiled.

I see - I'm doing what sounds the same (internal package that uses Prisma and is imported into Next.js package). 

Does your project not work if you don't use `transpileModules` at all, or are you trying to achieve some other effect via `transpileModules`?  Asking since `transpileModules` is not required for internal packages within my monorepo - I simply import the typescript source from my internal package from within my Next.js project and it all works.

**Comment by mmachatschek** [comment]
@andyjy we use turbo repo with nextjs and the internal packages and when we are not transpiling our modules we run into the issue that is described here: https://turbo.build/repo/docs/handbook/sharing-code/internal-packages#5-try-running-the-app

not using `transpileModules` basically doesn't work for us.

**Comment by andyjy** [comment]
All I can say is I'm also using turborepo with nextjs + internal packages in a monorepo + Neon driverAdapter and not getting any error - so I assume we're doing something different in our setup. 

Maybe some of the below might help resolve it for you:

I have `transpileModules: []` - yes, empty array[^1]

I'm importing internal packages into my Next.js package using relative `file:../` references ([`npm install <folder>`](https://docs.npmjs.com/cli/v10/commands/npm-install)):

```
"dependencies": {
    "internal-package": "file:../internal-package"
}
```

Finally I'm using [npm workspaces](https://docs.npmjs.com/cli/v8/using-npm/workspaces) with a top-level package.json in my monorepo - not sure if that affects any of the above but mentioning as your reproduction repo does not.

[^1]: The Next.js docs are definitely light on this, without it set at all I get the error you linked above - as far as I can remember I landed on the empty array almost by accident. (I was previously transpiling an external package, and discovered the empty array worked after trying to remove it entirely.)

**Comment by janpio** [comment]
Result of reproduction changed when upgrading to newest versions of everything:
```
 ⨯ TypeError: PrismaNeon must be initialized with an instance of Pool:
import { Pool } from '@neondatabase/serverless'
const pool = new Pool({ connectionString: url })
const adapter = new PrismaNeon(pool)
```
![image](https://github.com/prisma/prisma/assets/183673/8b035800-1fe1-4a84-9871-8dd1d469f5f9)
Code at https://github.com/mmachatschek/repro_nextjs_neon_driveradapter_issue/pull/1

**Comment by jkomyno** [comment]
Hello @mmachatschek, since https://github.com/prisma/prisma/pull/24434, Prisma Driver Adapters no longer tamper with the globally unique `pg` type parser object.

You should thus now be able to use the Neon Driver Adapter without requiring transpilation at all :)
Can you please give it a try with `prisma@5.16.1`? (Please remember to re-run `prisma generate`). Thanks!

---

Getting back to the issue at hand, we tend to discourage Next.js transpilation because it can get yield very unpredictable results.

**Comment by jkomyno** [comment]
Hi @mmachatschek, any chance you saw [the comment above](https://github.com/prisma/prisma/issues/22469#issuecomment-2200024646)?

Would that fix this issue for you? Thanks.

**Comment by mmachatschek** [comment]
Hi @jkomyno I'm currently unable to test this in combination with our keystone-js codebase as it depends on some internal changes in the framework I can further test that as soon as these topics were solved.

Based on your comment and the linked PR it looks like my initial issue is solved and it aligns with the findings I had while debugging it.

So we can close this issue. If I happen to encounter the issue again or with a different error, I'll rise another issue
