### ISSUE TITLE
ERROR: could not read block XX in file "X/X/X"

### ISSUE THREAD

**Issue by norberto-e-888** [prisma/prisma#22484]
### Bug description

My Postgres instance seems to be stuck in a corrupted state where I get this error whenever I try to generate a new migration

![Screenshot 2023-12-20 at 7 07 11 PM](https://github.com/prisma/prisma/assets/58429780/d994a548-3090-49b8-ac3a-3c731b83eda2)

### How to reproduce

The issue poped up with no particularly discernable action on my part. I don't know how one would reproduce it.

### Prisma information

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["postgresqlExtensions", "metrics", "tracing"]
}

datasource db {
  provider   = "postgresql"
  url        = env("DATABASE_URL")
  extensions = [postgis]
}

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 20.10.0

### Prisma Version

5.7.0

**Comment by janpio** [comment]
I assume this was a purely database side problem @norberto-e-888 that you could fix on the database side?
