### ISSUE TITLE
Disable "Start using Prisma Client" hint logs on `prisma generate`

### ISSUE THREAD

**Issue by BrennanColberg** [prisma/prisma#22513]
## Problem

This log is appended to the log of every `prisma generate` call:

```
Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
\`\`\`
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
\`\`\`
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
\`\`\`
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
\`\`\`
```

...and there is no way to turn it off, even in config. In mature repositories I have alreadyb configured Prisma Client and am confident in how to use it, and this just spams the logs.

## Suggested solution / Alternatives

A configuration option somewhere that disables this. Either:

- setting an environment variable e.g. `PRISMA_DISABLE_HINT`
- an option in `package.json` under the `"prisma": { "hint": false }` key
- a flag to `prisma generate` e.g. `prisma generate --no-hint`
- some configuration option in `schema.prisma`

...or something similar. As far as I can tell, Prisma has no standard config file (e.g. `prisma.config.json` or `.prismarc`, which would otherwise be the optimal place to put something like this.

## Additional context

The code that logs the text question is located in `packages/cli/src/Generate.ts`:
https://github.com/prisma/prisma/blob/1eacb61c495b2e82ba8d8c77e2189c3df632a335/packages/cli/src/Generate.ts#L263-L283

**Comment by JClackett** [comment]
And also, please remove the huge accelerate box

**Comment by incompletude** [comment]
any update on this? the last place where i want to see ads is in my terminal window. for Christ sake.

**Comment by nickcarnival** [comment]
@BrennanColberg how about something like this:
![Screenshot 2024-05-23 at 12 01 16 PM](https://github.com/prisma/prisma/assets/36806704/94ec2c22-7e76-4068-860f-a42ee19108ad)

**Comment by BrennanColberg** [comment]
That looks fantastic, would love to have it.

**Comment by nickcarnival** [comment]
@BrennanColberg I have a PR up, let me know if you see anything you'd like changed.

**Comment by BrennanColberg** [comment]
@nickcarnival not at a computer to test, but I read all the code, and if those tests pass it should be good. Thank you!

**Comment by FrankHassanabad** [comment]
This looks great @nickcarnival, I hope your PR is merged soon above. It looks like a feature everyone has been requesting for quite a while.

**Comment by nickcarnival** [comment]
The argument is `--no-hints` is released. Enjoy @BrennanColberg

**Comment by davecarlson** [comment]
> The argument is `--no-hints` is released. Enjoy @BrennanColberg

Can the release notes to updated to show this? I know that it's in the change log, but feels that this should be signposted a bit more in the bit above

**Comment by fvilers** [comment]
IMHO, it'd have been better to be able to set the flag with multiple possibility. A CLI flag is fine until you have to type it twice. Maybe a `.prismarc` file could have been a good solution for permanent CLI flags?

**Comment by Ehbraheem** [comment]
> IMHO, it'd have been better to be able to set the flag with multiple possibility. A CLI flag is fine until you have to type it twice. Maybe a `.prismarc` file could have been a good solution for permanent CLI flags?

Having an env option will be good too. I can't imagine how annoying doing this multiple times will be
