### ISSUE TITLE
Possibility of comparing columns of the same row.

### ISSUE THREAD

**Issue by LucaStefan112** [prisma/prisma#22523]
Pretty explanatory... Example:

select * from users where first_name = last_name;

**Comment by jkomyno** [comment]
Hi @LucaStefan112, this is already possible as of `prisma@5.0.0`. I recommend you to try with the latest Prisma following [this documentation](https://www.prisma.io/docs/orm/reference/prisma-client-reference#compare-columns-in-the-same-table).

I'm closing this issue for now, but please leave another comment, should you find problems with this feature. Thanks!

**Comment by LucaStefan112** [comment]
Hi Alberto, thank you for the clarification, I wasn't aware of the
feature... Have a nice day!
