### ISSUE TITLE
Let Prisma detect Artix Linux distro

### ISSUE THREAD

**Issue by alaidine** [prisma/prisma#22522]
I get this error message:
"prisma:warn Prisma failed to detect the Linux distro in use, and may not work as expected. Defaulting to "debian"."

OS: Artix Linux

**Comment by jkomyno** [comment]
Hi @alaidine, thanks for the report.
Does Prisma still run in your case? If so, then you can safely ignore this warning.

---

In the future, we might explicitly check for Artix Linux as well.
Can you please share the output of:

- `cat /etc/os-release`

**Comment by alaidine** [comment]
output of cat /etc/os-release:

NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
