### ISSUE TITLE
Check constraint in a transaction error is hidden

### ISSUE THREAD

**Issue by dstoyanoff** [prisma/prisma#22536]
### Bug description

Given an operation is executed in a transaction, if a check constraint fails in the middle, it is not immediately thrown, but we only get a generic error on the next operation that tries to execute.

```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E25P02), message: "current transaction is aborted, commands ignored until end of transaction block", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("postgres.c"), line: Some(1438), routine: Some("exec_parse_message") }) }), transient: false })
```

### Expected behavior

Prisma should show the error clearly in the logs (the error is visible in the db logs)

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS, Debian
- Database: PostgreSQL
- Node.js version: 

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.0.0
@prisma/client          : 5.0.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at ../../node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at ../../node_modules/prisma/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Default Engines Hash    : 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Studio                  : 0.487.0
Preview Features        : tracing
```

Note: also reproducible with 5.7.0

**Comment by jkomyno** [comment]
Hi @dstoyanoff, could you please share with us a minimally reproducible example, with the `schema.prisma`, `seed.ts` files, and a code snippet using `@prisma/client`? This would be very useful for us to investigate this issue. Thanks!

**Comment by dstoyanoff** [comment]
Hi @jkomyno, I created an empty project, but I can't reproduce it yet. I will need to play around to see at what condition it breaks in our app.
