### ISSUE TITLE
couldn't identify clear-linux-os

### ISSUE THREAD

**Issue by jdu211171** [prisma/prisma#22539]
## Problem
`
prisma:warn Prisma doesn't know which engines to download for the Linux distro "clear-linux-os". Falling back to Prisma engines built "debian".
`

Could you please add Clear Linux OS to your supported distro list?

**Comment by jkomyno** [comment]
Hi @jdu211171, thanks for the report.
Does Prisma still run in your case? If so, then you can safely ignore this warning.

---

In the future, we might explicitly check for Clear Linux as well.
Can you please share the output of:

- `cat /etc/os-release`

**Comment by jdu211171** [comment]
yes, it works without problem so far. Thanks for developing such a amazing project, it's the best ORM I found in whole registery.

here is output of `cat /etc/os-release`:
`
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=40600
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
BUILD_ID=40600
`

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
