### ISSUE TITLE
`prisma db push` not dropping unique index when changing relationship from 1-to-1 to 1-to-many

### ISSUE THREAD

**Issue by lajerca** [prisma/prisma#22550]
### Bug description

after removing the `@unique` attribute from a column in the schema and running `prisma db push` I receive the message:
> The database is already in sync with the Prisma schema.

which shouldn't be.

### How to reproduce

1. create a blank db like this
```prisma
model TableA {
  id         Int @id @default(autoincrement())
  table_b_id Int @unique

  Season TableB @relation(fields: [table_b_id], references: [id], onDelete: Restrict, onUpdate: Cascade)
}

model TableB {
  id   Int     @id @default(autoincrement())
  name String? @db.VarChar(255)

  TableA TableA?
}
```
3. prisma db push
4. change the schema like this

```diff
model TableA {
  id         Int @id @default(autoincrement())
- table_b_id Int @unique
+ table_b_id Int

  Season TableB @relation(fields: [table_b_id], references: [id], onDelete: Restrict, onUpdate: Cascade)
}

model TableB {
  id   Int     @id @default(autoincrement())
  name String? @db.VarChar(255)

- TableA TableA?
+ TableA TableA[]
}

```
5. prisma db push

### Expected behavior

It should drop the index in the db, or at least remove the unique attribute from it

### Prisma information

the schema is in the steps to reproduce

### Environment & setup

- OS:  Ubuntu
- Database: mysql 8

### Prisma Version

```
5.7.1
```

**Comment by SevInf** [comment]
Can reproduce with the provided schema on latest `main` (5.11.0-dev)

**Comment by naveen-bharathi** [comment]
+1
