### ISSUE TITLE
cockroachdb: sql: support apply joins with subqueries in both "inner" and "outer" contexts

### ISSUE THREAD

**Issue by nabhanh** [prisma/prisma#22553]
Currently cockroachdb does not support joins with both inner and outer contexts but prisma does construct these queries
```
prisma_1.default.person.findMany(\nError occurred during query execution:\nConnectorError(ConnectorError { 
user_facing_error: None, kind: QueryError(PostgresError { code: \"0A000\", message: \"unimplemented: apply joins
with subqueries in the \\\"inner\\\" and \\\"outer\\\" contexts are not supported\", severity: \"ERROR\", detail: None, column: None, hint: Some(\"You have attempted to use a feature that is not yet implemented.\\n
See: https://go.crdb.dev/issue-v/66447/v23.1\") }), transient: false })","target":"person.findMany"} | 2024-01-03T14:53:09.294Z f4705e37-f518-44fe-8894-442ab494cb29

```

[Link to CRDB Issue](https://github.com/cockroachdb/cockroach/issues/66447?version=v23.1)

I am not 100% sure in what scenarios Prisma constructs these queries so I am not a 100% sure how to reproduce

**Comment by millsp** [comment]
Hey @nabhanh could you please provide us with a small reproduction? Ideally a schema and the failing query. Thanks!

**Comment by SevInf** [comment]
Hey @nabhanh ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
