### ISSUE TITLE
Partial Unique Index (Postgres) aren't introspected as normal unique indexes 

### ISSUE THREAD

**Issue by jove4015** [prisma/prisma#22567]
## Problem

I'm trying to work with a partial unique index and prisma.  Unfortunately, once I add a where clause to an index, Prisma stops seeing this index.  I've discovered now that this happens only because [someone requested that it work that way.](https://github.com/prisma/prisma/issues/3373)

Well, I'm here with the opposite problem.  I need Prisma to work the way it did before - where it treated the partial index as if it was a full index.  Without the ability to do this, I can't deploy any partial unique indexes AND also have those indexes declared in my schema (and therefore make use of them), because Prisma tries to create it when it's already there.

Is there any way to make this optional so that developers can elect to have this work either way?    I understand the original request's purpose but we are not using introspection for anything other than verifying that our schema is up to date with the database and vice-versa (ie, we never use db pull and would never try to recreate our schema from the DB, because we are also using RLS and a variety of other features that Prisma would eradicate otherwise).  I don't need Prisma to support the partial unique index - I just need Prisma to stop stumbling over it.  Were it not for the previous feature request, this would already be possible, so clearly it can be done.

## Suggested solution

Add a feature flag to the schema generator to allow it to treat partial indexes as full indexes, as it used to do.  This doesn't have to be the default behavior - it just needs to be an option.

## Alternatives

Alternatively, add an option to ignore a portion of the schema for the purposes of introspection.  In this case, the Prisma engine would simply ignore that index and not try to create it, nor bother to look for it in the existing database.   We would take on the responsibility for ensuring that it's there.    This could be a flag like "@ignore" placed on the line with the index:

@@unique([name, categoryType, tenantId]) @ignore

Or whatever implementation you think is appropriate.

## Additional context

The goal here is to make soft deletes of models with unique indexes possible.  Right now, soft delete is not possible because deleted records would prevent new records with the same keys from being created.

We flag soft deletes with a field "deletedAt", which contains the timestamp when the field was deleted.  When this field is null, the record is considered to be not deleted - once the record has a value in this field, it's considered deleted.  

We first considered adding the deletedAt column to the unique index, but Prisma doesn't support this - there's no way to pass NULL as part of a unique constraint, and even in Postgres you would have to enable extra flags in order to support this.  

Simply using a boolean field like "deleted" is also problematic, because then multiple deleted records with the same set of keys couldn't exist - so basically you couldn't delete a record with the same keys twice, which users will definitely run into.

Partial unique indexes are a far better, more precise approach to the problem, allowing any number of deleted records with the same keys to exist as long as there is only one not-deleted record with those keys.

If the unique index is not listed in the prisma schema, then we can't use features like findUnique, connectOrCreate, or upsert, but once the index is included there, prisma migrate will keep trying to create the field over and over again, creating problems for CI and for the developer workflow.

**Comment by janpio** [comment]
Partial unique indexes are not the same as unique indexes, so representing them as such was wrong and broke many workflows.
The current state is less wrong, even if it makes some other workflows - like yours - not work anymore either.

We are not going to change this back, or invest additional design and implementation effort to add an option, but will implement support for partial unique indexes some time: https://github.com/prisma/prisma/issues/6974 Sorry.

(As a temporary workaround, and if I really, really needed to automate this, I personally would implement an additional step after introspection via a script that adds the missing indexes to the Prisma schema file. Alternatively you can also try to use the old Prisma version just to introspect your database - maybe there are not other bugs that will make this impossible.)

**Comment by jove4015** [comment]
I don't really see how this works as a temporary workaround - introspection is something that the prisma migrate command is doing internally, I am not running introspection myself - in our CI environment, any unmigrated Prisma changes result in failure (since any change in the schema should always be accompanied by a migration and the migrate command should essentially always return clean). This is just standard practice I've followed with any ORM that has migrations.  It's a pretty important, basic CI check I wouldn't want to do without:

```
npx prisma migrate diff --to-schema-datamodel prisma/schema.prisma --from-schema-datasource prisma/schema.prisma --exit-code
```

On top of that, any time any dev runs migrate dev to introspect new changes, they will also be forced to reset their database and have to recreate it, and then modify the generated migration file to remove the extra lines removing and creating the index again.  So it's very inconvenient for the developer trying to maintain the project and prone to having the developer make big mistakes (like, deleting the index).

My temporary workaround right now is not to use a partial unique index, or any unique index, at all but to do all the checks for uniqueness at the application layer instead.  So, a core feature is basically just unavailable to me.

On the [issue](https://github.com/prisma/prisma/issues/3373) where you made the original change, the OP got a response and a fix within a day.  At that time, you told him "making sure developers are not blocked is our highest priority besides actually implementing that functionality".   I'm just not sure why it mattered so much for that person but not for me.

**Comment by trc-clin** [comment]
I have the same issue, are there any workarounds for this?

**Comment by jove4015** [comment]
The workaround is pretty simple - don't use unique indexes.  Write all the code to ensure uniqueness in your application layer.  This is what we're doing (referencing the same model from my earlier:

```
// before create
    const existingCategory = await this.prisma.category.findFirst({
      where: {
        name: validatedParams.name,
        categoryType: validatedParams.categoryType,
        deletedAt: null,
      },
      select: defaultCategoryObject,
    });

    if (existingCategory) {
      throw new KiefaError({
        code: "CONFLICT",
        message: `A ${validatedParams.categoryType.toLowerCase()} category with the name ${
          validatedParams.name
        } already exists`,
      });
    }

// before update

    if (
      existingCategory.name !== params.name ||
      existingCategory.categoryType !== params.categoryType
    ) {
      const existingCategory = await this.prisma.category.findFirst({
        where: {
          name: params.name,
          categoryType: params.categoryType,
          deletedAt: null,
          id: {
            not: id,
          },
        },
      });
      if (existingCategory) {
        throw new KiefaError({
          code: "CONFLICT",
          message: `A ${params.categoryType.toLowerCase()} category with the name ${
            params.name
          } already exists`,
        });
      }
    }
```

Obviously this has drawbacks.  It's very easy for any bad actor to ignore this API,

With Prisma, RLS and unique indexes are essentially incompatible.  You can use one or the other with any one table, but not both.  If you want to associate records, you have to look up the primary-key-id and then connect that - there's no connectOrCreate.
