### ISSUE TITLE
ensure: could not fetch query engine: could not download

### ISSUE THREAD

**Issue by Southclaws** [prisma/prisma#2256]
## Bug description

The generated client is trying to download the engine but it doesn't exist.

```
ensure: could not fetch query engine: could not download https://binaries.prisma.sh/master/76857c35ba1e1764dd5473656ecbbb2f739e1822/windows/query-engine.gz to C:\Users\SOUTHC~1\AppData\Local\Temp/prisma/binaries/engines/76857c35ba1e1764dd5473656ecbbb2f739e1822/prisma-query-engine-windows: received code 404 from https://binaries.prisma.sh/master/76857c35ba1e1764dd5473656ecbbb2f739e1822/windows/query-engine.gz: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>master/76857c35ba1e1764dd5473656ecbbb2f739e1822/windows/query-engine.gz</Key><RequestId>517A9A9B721A73CB</RequestId><HostId>CeVTFi5GOtr2e0PLJ/kq30yxo2Sxg4i+JAA6BK+yeZ68H3tbVrcTjTs7deu2BlRqUcUI03jWi2E=</HostId></Error>
```

That URL is: https://binaries.prisma.sh/master/76857c35ba1e1764dd5473656ecbbb2f739e1822/windows/query-engine.gz

## How to reproduce

Just try and use prisma.

## Expected behavior

It to download the binary to a temp directory and run I suppose (is there any way of specifying the target directory?)

## Prisma information

I don't think the schema etc is relevant to this.

## Environment & setup

- OS: Windows
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.2

**Comment by pantharshit00** [comment]
This is very weird. CLI is not prefixing `.exe` to the url to make `query-engine.exe.gz` which is the correct URL. 

Correct url is https://binaries.prisma.sh/master/76857c35ba1e1764dd5473656ecbbb2f739e1822/windows/query-engine.exe.gz

Can you please tell me which version of windows you are using and which terminal emulator you are using?

**Comment by steebchen** [comment]
@Southclaws Can you please share the exact command you're running?

**Comment by Jolg42** [comment]
For info this to work the `binaryTarget` here needs to be === to `windows` https://github.com/prisma/prisma/blob/87e51402fdc659b225c376153b22b32959ca9fb4/src/packages/fetch-engine/src/download.ts#L397

**Comment by Southclaws** [comment]
Command: `npx prisma generate`
Shell: PowerShell (latest version, though the shell shouldn't change how the command operates)
Emulator: VS Code integrated terminal, Windows Terminal (also shouldn't affect anything)

Is there any way I can download this manually? I've been blocked for the last week and Prisma 1 is also not working properly so at this point I'm considering just converting all my code back to raw SQL.

**Comment by pantharshit00** [comment]
Yes, you can download the engine from the following link: https://binaries.prisma.sh/master/76857c35ba1e1764dd5473656ecbbb2f739e1822/windows/query-engine.exe.gz
https://binaries.prisma.sh/master/76857c35ba1e1764dd5473656ecbbb2f739e1822/windows/migration-engine.exe.gz
https://binaries.prisma.sh/master/76857c35ba1e1764dd5473656ecbbb2f739e1822/windows/introspection-engine.exe.gz


Then you can paste the engines at: `node_modules/@prisma/cli` and paste query-engine at `node_modules/@prisma/client/runtime`



But this should now happen in the first place, please try running `npx @prisma/cli generate` before manually pasting the engines.

**Comment by steebchen** [comment]
@Southclaws Are you using our [Go client](https://github.com/prisma/prisma-client-go) in some way? The original error you posted [looks a lot](https://github.com/search?q=org%3Aprisma+%22could+not+fetch+query+engine%22&type=Code) like it. I could also reproduce the error with the Go client.

**Comment by Southclaws** [comment]
Yes, my project is written entirely in Go. So there's no `node_modules` directory to paste into.

**Comment by Southclaws** [comment]
Using `@prisma/cli` got me past that problem, and now I have a more confusing one. Worth a new issue? Not sure if it's Go specific or just Prisma in general:

```
❯ npx @prisma/cli generate
(node:7656) ExperimentalWarning: The fs.promises API is experimental
Environment variables loaded from ./prisma/.env
(node:17228) ExperimentalWarning: The fs.promises API is experimental
C:\Users\Southclaws\AppData\Roaming\npm-cache\_npx\17228\node_modules\@prisma\cli\build\index.js:2
module.exports=function(e,t){"use strict";var r={};function __webpack_require__(t){if(r[t]){return r[t].exports}var n=r[t]={i:t,l:false,exports:{}};e[t].call(n.exports,n,n.exports,__webpack_require__);n.l=
true;return n.exports}__webpack_require__.ab=__dirname+"/";function startup(){return __webpack_require__(1280)}t(__webpack_require__);return startup()}({2:function(e,t,r){"use strict";Object.defineProperty
(t,"__esModule",{value:true});var n=r(5622);var i=r(9250);var o=r(21);var s=r(8356);var a=function(){function Reader(e){this.options=e;this.micromatchOptions=this.getMicromatchOptions();this.entryFilter=ne
w o.default(e,this.micromatchOptions);this.deepFilter=new i.default(e,this.micromatchOptions)}Reader.prototype.getRootDirectory=function(e){return n.resolve(this.options.cwd,e.base)};Reader.prototype.getRe
aderOptions=function(e){return{basePath:e.base==="."?"":e.base,filter:this.entryFilter.getFilter(e.posi

Error: EPERM: operation not permitted, unlink 'C:\Users\Southclaws\AppData\Roaming\npm-cache\_npx\17228\node_modules\@prisma\cli\query-engine-windows.exe'
    at Object.unlinkSync (fs.js:956:3)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:211:13)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:311:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:334:7)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:209:5)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:311:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:5
```

**Comment by steebchen** [comment]
Ok, so the original problem is definitely related to the Go client. I have fixed a few windows-related bugs recently – can you please try upgrading to the master branch using Go modules?
For your last comment, I think this one might not be Go relevant, so if you're still experiencing this one after upgrading and try running generate (with `go run ...`, not with npx) then please create a new issue for the new problem.

**Comment by Southclaws** [comment]
I downloaded the file manually into the temp dir but got the following error when trying to boot up my program:

```
ensure: version check failed: exec: \"C:\\\\Users\\\\SOUTHC~1\\\\AppData\\\\Local\\\\Temp/prisma/binaries/engines/76857c35ba1e1764dd5473656ecbbb2f739e1822/prisma-query-engine-windows\": file does not exist
```

(escaped double-quotes are due to a JSON logging engine)

**Comment by Southclaws** [comment]
Alright, force updating the Go library seems to have worked! I think I can get to work using Prisma 2 now, which is great. I'll report any issues I run into on the Go client repo. Thanks!

**Comment by steebchen** [comment]
Cool, thanks for the update!

**Comment by cholasimmons** [comment]
Hello Lads, I'm from the future,
Im using Prisma 6.11.0 with BetterAuth on ElysiaJS, everything latest.
So I was running a separate instance of prisma dev while running my server and i realized when i make a betterAuth call, it clearly attempts to write to the DB and `prisma dev` throws this.

```
Error: Couldn't download engine. URL: https://binaries.prisma.sh/all_commits/9c30299f5a0ea26a96790e13f796dc6094db3173/windows/query-engine.gz, status code: 404
    at #a (file:///C:/Users/chola/AppData/Local/Temp/@prisma/cli-dev@latest-1751407200000/node_modules/@prisma/dev/dist/chunk-IKAJO6YD.js:3:1894)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async #o (file:///C:/Users/chola/AppData/Local/Temp/@prisma/cli-dev@latest-1751407200000/node_modules/@prisma/dev/dist/chunk-IKAJO6YD.js:3:1107)
    at async r.start (file:///C:/Users/chola/AppData/Local/Temp/@prisma/cli-dev@latest-1751407200000/node_modules/@prisma/dev/dist/chunk-IKAJO6YD.js:1:3781)
    at async r.get (file:///C:/Users/chola/AppData/Local/Temp/@prisma/cli-dev@latest-1751407200000/node_modules/@prisma/dev/dist/chunk-IKAJO6YD.js:1:2660)
    at async y (file:///C:/Users/chola/AppData/Local/Temp/@prisma/cli-dev@latest-1751407200000/node_modules/@prisma/dev/dist/accelerate-6Y3KVRYK.js:1:3607)
    at async file:///C:/Users/chola/AppData/Local/Temp/@prisma/cli-dev@latest-1751407200000/node_modules/@prisma/dev/dist/accelerate-6Y3KVRYK.js:1:2096
    at async dispatch (file:///C:/Users/chola/AppData/Local/Temp/@prisma/cli-dev@latest-1751407200000/node_modules/hono/dist/compose.js:22:17)
    at async file:///C:/Users/chola/AppData/Local/Temp/@prisma/cli-dev@latest-1751407200000/node_modules/hono/dist/validator/validator.js:81:5
    at async dispatch (file:///C:/Users/chola/AppData/Local/Temp/@prisma/cli-dev@latest-1751407200000/node_modules/hono/dist/compose.js:22:17)
```

I'm using 2 instances of Windows Powershell, 1 for Elysia 1 for prisma dev, Windows 11,

**Comment by steebchen** [comment]
@cholasimmons please create a new issue
