### ISSUE TITLE
I get the following Error when runing prisma migrate

### ISSUE THREAD

**Issue by amine-tayani** [prisma/prisma#22566]
### Bug description

```Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database

Error: Prisma schema validation - (get-config wasm) 
Error code: P1012
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:6
   | 
 5 |   provider = "postgresql"
 6 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
[Context: getConfig]

```

### How to reproduce

1. Run ```pnpm dlx prisma migrate dev``` or ```pnpm dlx prisma db push```
2. terminal shows the error above.

### Expected behavior

should run the migrations and supabase should show the tables

### Prisma information

Schema.prisma file

```
 datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

enum ApplicationStatus {
  APPLIED
  INTERVIEW
  REJECTED
  OFFER
  CLOSED
}

model Account {
  id                 String    @id @default(cuid())
  userId             String
  providerType       String
  providerId         String
  providerAccountId  String
  refreshToken       String?
  accessToken        String?
  accessTokenExpires DateTime?
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt
  user               User      @relation(fields: [userId], references: [id])

  @@unique([providerId, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  userId       String
  expires      DateTime
  sessionToken String   @unique
  accessToken  String   @unique
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  user         User     @relation(fields: [userId], references: [id])
}

model UserLink {
  id        String   @id @default(uuid())
  user      User[]
  url       String   @db.VarChar(256)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model ImageUpload {
  id        String   @id @default(uuid())
  userId    String
  user      User     @relation(fields: [userId], references: [id])
  url       String   @db.VarChar(256)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@index([userId])
}

model User {
  id             String        @id @default(cuid())
  hashedPassword String?
  email          String?       @unique
  emailVerified  DateTime?
  name           String?
  bio            String?       @default("") @db.VarChar(1000)
  image          String?
  location       String?
  experience     Int?
  skills         String[]
  createdAt      DateTime      @default(now())
  updatedAt      DateTime      @updatedAt
  accounts       Account[]
  sessions       Session[]
  socialLinks    UserLink[]
  imageUpload    ImageUpload[]
}

model Application {
  id           Int               @id @default(autoincrement())
  company      String
  title        String
  description  String            @db.Text
  location     String
  Url          String?
  datePosted   DateTime
  deadlineDate DateTime?
  status       ApplicationStatus @default(APPLIED)
}

model VerificationRequest {
  id         String   @id @default(cuid())
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt

  @@unique([identifier, token])
}

```

### Environment & setup

- OS: Windows 10
- Database: Supabase / PostgreSQL
- Node.js version: 20.10.0 

### Prisma Version

prisma@5.7.1
@prisma/client@5.7.1

**Comment by millsp** [comment]
Hey @amine-tayani, did you place your environment variable in a `.env` file or exported it in your shell first?

**Comment by amine-tayani** [comment]
hey @millsp i have already setup the .env.local file with DATABASE_URL variable

**Comment by amine-tayani** [comment]
i setup like this : ```  DATABASE_URL=postgresql://postgres................... ``` without double quotes or anything

**Comment by millsp** [comment]
Prisma will only load `.env` files so `.env.local` is not loaded. You can either rename your `.env.local` to `.env`, or create a `.env`. Alternatively, you can use the `dotenv` cli instead, for example:

```
dotenv -e .env.local -- npx prisma generate
```

**Comment by amine-tayani** [comment]
Seems to have worked.
Thanks @millsp

**Comment by hamizjafari** [comment]
SOLVED -> remove prisma.config.ts (or other conf file of prisma) and enjoy it !

**Comment by maykon-oliveira** [comment]
But it's recommend to use prisma.config.ts, isn't it? @hamizjafari

**Comment by daanhegger** [comment]
> Accordion to [docs of new Prisma config](https://www.prisma.io/docs/orm/reference/prisma-config-reference#using-environment-variables):
> 
> > When using `prisma.config.ts`, environment variables from **`.env` files are not automatically loaded**. You'll need to:
> > 
> > 1. Install the dotenv package:
> > 
> >  npm install dotenv
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Import dotenv/config in your config file:
> > 
> > import "dotenv/config";
> > import type { PrismaConfig } from "prisma";
> > 
> > export default {
> >  // now you can use process.env variables
> > } satisfies PrismaConfig;

The docs only recommend using `dotenv` when using a Node release before v20. Shouldn't the docs recommend that for any version of NodeJS, if you want to use `.env` files? Otherwise, there is no easy way to run e.g. `npx prisma migrate reset` while loading the variables from `.env`.
