### ISSUE TITLE
`upsert()` evaluates `create` object when updating

### ISSUE THREAD

**Issue by negativems** [prisma/prisma#22591]
### Bug description

When I use upsert and pass the three required params (where, create and update), if I am updating and only passing the params I want to update, prisma throws an error on all the params in the create object that are not nullable.

### How to reproduce

1. Create a database with a table called "test"
2. The structure is:
   - name: varchar
   - surname: varchar
   - phone: varchar (not nullable)

The code using express is the next one:

*I am using a router that read files on folders, to make this route use app.get in the file app.ts (on the Prisma Information)*
```typescript
// route.ts
import { Request, Response, Router } from "express";
import { Logger } from "../utils/logger.js";
import { prisma } from "../app.js";

const router = Router();

// Here the problem is that the upsert interprets the phone as null when the request is updating (not passing the phone and passing a name that exists)
router.get('/', async (req: Request, res: Response) => {
  const { name, surname, phone } = req.body; // phone is not nullable and does not have default property
  const testSQL = await prisma.test.findFirst({ where: { name: "name1" } });

  if (!testSQL && !req.body.phone) {
    Logger.error(`The record with name ${name} does not exists or tried to create a record without phone`);
    res.sendStatus(400);
    return;
  }

  await prisma.test
    .upsert({
      where: { id: testSQL?.id ?? -1 },
      create: { name, surname, phone },
      update: { name, surname, phone },
    });

  Logger.success(`Record ${name} ${testSQL ? 'updated' : 'created'} successfully`);
  res.sendStatus(200);
});

export default router;
```

The solution I found is passing on the create object default values that will never be used and make a condition to make sure never will create a record without the non-nullable params.

### Expected behavior

If I am updating with upsert, I expected it to update the record without validate the create object because the create object in the most cases will be wrong if there is columns non-nullable and I am updating other columns.

Maybe one solution is find the record before the upsert and fill the create object with the current values if it is updating, just to make it not crash in the create object.

### Prisma information

```prisma
model test {
  id         Int      @id @default(autoincrement()) @db.UnsignedInt
  created_at DateTime @default(now()) @db.Timestamp(0)
  name       String?  @db.VarChar(255)
  surname    String?  @db.VarChar(255)
  phone      String   @db.VarChar(255)
}
```

```ts
// app.ts
import { PrismaClient } from '@prisma/client';
import env from 'dotenv';
import express from 'express';
import { getRoutePrefixEnv, loadRouter } from './router.js';
env.config();

const PORT = process.env.APP_PORT || 0;

export const app = express();

export const prisma = new PrismaClient();

// Test prisma connection
prisma.$connect()
  .then(() => console.log("Conexión a la base de datos establecida correctamente"))
  .catch((error: any) => console.error("Error al conectar con la base de datos: " + error));

app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
```

### Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: v18.19.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.7.1
@prisma/client          : 5.7.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v18.19.0
Query Engine (Node-API) : libquery-engine 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5 (at ../../.bun/install/global/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5 (at ../../.bun/install/global/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.7.1-1.0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5
Default Engines Hash    : 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5
Studio                  : 0.495.0
```

**Comment by Weakky** [comment]
Hey @negativems,

I'm unsure if I understand your problem. `update` allows you to choose which field to update. This is not the case for `create` because you _need_ to pass in the required fields that don't have a default value.

Now, your title suggests that upsert is trying to create a record when it should update. Could you expand on that? What is the error you're seeing exactly? Is it a type error? Is it a runtime error?

Thank you

**Comment by negativems** [comment]
Hello @Weakky, thanks for the quick response.

The error I am seeing is a runtime error:
![image](https://github.com/prisma/prisma/assets/20746840/f0002851-3456-4dcd-9102-c0055cb03f44)

But it shouldn't give me an error on the create object because the record exists and shouldn't evaluate create right?

Or this is not possible to make it work like this? Should I always check if exists and use .create and .update in other case?

**Comment by janpio** [comment]
If you don't have all the values for a potential `create`, you can not use `upsert()` indeed. Our types ensure that your `upsert()` can be fully executed, which in your case seems to inclide providing a `phone` value.
