### ISSUE TITLE
Could not figure out an ID in create

### ISSUE THREAD

**Issue by iamargentum** [prisma/prisma#22619]
Hi Prisma Team! My Prisma Client just crashed. This is the report:

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.17.0           | 
| OS              | rhel-openssl-3.0.x |
| Prisma Client   | 5.6.0              |
| Query Engine    | e95e739751f42d8ca026f6b910f5a2dc5adeaeee|
| Database        | mysql              |

## Logs
```
lient:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.6.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```js
        const data = {
            name: name,
            status: STATUS_PENDING,
            parameters: {...someParameters},
            repeatCount: repeatCount,
            note: note,
            product: {
                connect: {
                    id: productId
                }
            },
            user: {
                connect: {
                    id: user.id
                }
            }
        };

        const job = await prisma.jobs.create({
            data: data
        });
```

## Schema
```prisma

model User {
  id              String        @id @default(cuid())
  name            String?
  email           String?       @unique
  emailVerified   DateTime?     @map("email_verified")
  image           String?

  accounts        Account[]
  sessions        Session[]
  jobs      jobs[]

  @@map("users")
}

model products {
    id               Int                @id @default(autoincrement())
    name             String
    product_class    String
    product_keyword  String
    notes            String?
    created_at       DateTime           @default(now())
    updated_at       DateTime           @updatedAt

    jobs       jobs[]
}

model jobs {
    id                Int                 @id @default(autoincrement())
    name              String
    status            String
    product_id        Int
    parameters        Json
    repeatCount       Int
    created_by        String
    created_at        DateTime            @default(now())
    updated_at        DateTime            @updatedAt
    note              String              @default("")

    user              User?               @relation(fields: [created_by], references: [id])
    product           products            @relation(fields: [product_id], references: [id], onDelete: Cascade)
}

```

## Prisma Engine Query
```
not sure what this is
```

this has been happening for quite some time now, along with other errors like this -
```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1210, message: "Incorrect arguments to mysqld_stmt_execute", state: "HY000" })), transient: false })
```
i am unable to reproduce these errors consistently.
would appreciate some help.

thanks!

**Comment by jkomyno** [comment]
This bug is possibly similar to something observed elsewhere: https://github.com/sidorares/node-mysql2/issues/1239#issuecomment-718827355. 
Can you please share what version of MySQL are you using, exactly? Thanks!

**Comment by iamargentum** [comment]
hi @jkomyno !
thanks for the info
i'll check the linked issue
we are on version 5.7 of MySQL
![image](https://github.com/prisma/prisma/assets/51338731/c354d325-4a95-4ee3-85b0-5076397d13a4)

**Comment by Jolg42** [comment]
Hi @iamargentum 

It would be interesting if you could upgrade your Aurora version and see if the problem persists.
From what I see in https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.20Updates.html the latest version is `2023-12-28 (version 2.12.1, compatible with MySQL 5.7.40)`

I also found that StackOverflow question which looks similar https://stackoverflow.com/questions/56946707/aws-aurora-auto-scaling-causes-incorrect-arguments-to-mysqld-stmt-execute
Do you know if this happens when your cluster is auto-scaling?

**Comment by Jolg42** [comment]
Another finding is in https://bugs.mysql.com/bug.php?id=95984, that it could be related to a `Json` field.
Could you try to see if the problem disappears with an empty `Json` field? 
Replacing `parameters: {...someParameters},` by `parameters: {},` for example.

**Comment by Jolg42** [comment]
Also, it would be interesting if you could post the full output from your terminal with `DEBUG=prisma*` when this error happens.

**Comment by iamargentum** [comment]
hi @Jolg42 

> It would be interesting if you could upgrade your Aurora version and see if the problem persists.
i think that is the only thing we haven't tried yet
will let you know the findings if we decide to upgrade

> Do you know if this happens when your cluster is auto-scaling?

we did suspect that the error could be somehow related to autoscaling events, but couldn't really find a solid pattern
the stackoverflow issue that you've linked seems to be promising
do you happen to know how we could disable prepared statement caching? i can see a query param in connection string url for Postgres in the Prisma docs related to prepared statement caching, but nothing for MySQL
also tried searching for this configuration on RDS, but it doesn't seem to have anything like that
we did find a way to disable it in MySQL, as an admin
we'll try that for sure

> Another finding is in https://bugs.mysql.com/bug.php?id=95984, that it could be related to a Json field.
possible, can check that out
i'm a bit confused about it though, since the same query runs fine after some time

> Also, it would be interesting if you could post the full output from your terminal with DEBUG=prisma* when this error happens.
```
PrismaClientUnknownRequestError:
Invalid `prisma.products.findMany()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1210, message: "Incorrect arguments to mysqld_stmt_execute", state: "HY000" })), transient: false })
    at ni.handleRequestError (/home/ec2-user/application/node_modules/@prisma/client/runtime/library.js:124:6989)
    at ni.handleAndLogRequestError (/home/ec2-user/application/node_modules/@prisma/client/runtime/library.js:124:6206)
    at ni.request (/home/ec2-user/application/node_modules/@prisma/client/runtime/library.js:124:5926)
    at l (/home/ec2-user/application/node_modules/@prisma/client/runtime/library.js:129:10023) {
  clientVersion: '5.6.0'
}
```
:arrow_up: this is the entire error that i see whenever something like this happens

thank you so much for all the info!
i'll post updates in this thread

**Comment by Jolg42** [comment]
>do you happen to know how we could disable prepared statement caching? i can see a query param in connection string url for Postgres in the Prisma docs related to prepared statement caching, but nothing for MySQL
also tried searching for this configuration on RDS, but it doesn't seem to have anything like that

I'm also not sure for MySQL, I found this https://dev.mysql.com/doc/refman/5.7/en/query-cache.html
>The query cache is deprecated as of MySQL 5.7.20, and is removed in MySQL 8.0. 
>...
>The query cache is used for prepared statements under the conditions described in [Section 8.10.3.1, “How the Query Cache Operates”](https://dev.mysql.com/doc/refman/5.7/en/query-cache-operation.html).

So it looks like it was removed in MySQL 8 to me 🤔

**Comment by iamargentum** [comment]
yes, it seems it was deprecated in MySQL 5.7.20 and removed in MySQL 8
i found a way to set it in RDS
it is a _dynamic_ value in the parameter group
also, found [this blog](https://aws.amazon.com/fr/blogs/database/best-practices-for-configuring-parameters-for-amazon-rds-for-mysql-part-1-parameters-related-to-performance/) from AWS helpful
this is what it has to say about query cache -
> The query cache is so problematic that it was deprecated in MySQL 5.7.20 and removed in MySQL 8.0. Therefore, we recommend not to use it
on querying `global variables` in our db cluster, i can see that query cache is operational
![image](https://github.com/prisma/prisma/assets/51338731/bfaa9cf3-5d60-49e8-92df-32bbc29a14ce)
we will be observing errors this week and make this change on the weekend, then see if this error goes away next week
fingers crossed!

**Comment by iamargentum** [comment]
so, tried setting `query_cache_size` in Group Parameters in RDS to 0, that didn't work
then tried setting `query_cache_type` to 0, as mentioned [here](https://dev.mysql.com/doc/refman/5.7/en/query-cache-configuration.html)
that didn't work as well

will now upgrade MySQL version and post updates

**Comment by janpio** [comment]
Any update @iamargentum?

**Comment by iamargentum** [comment]
i was meaning to post an update, but it kept slipping out of my mind
we moved to MySQL version 8.0.28 2 weeks ago and all the issues got resolved
it was so nice to see a clean Sentry dashboard! :)
thanks @Jolg42 and @jkomyno for your inputs and @janpio for reminding!
