### ISSUE TITLE
Document filters on select and Include

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#2264]
Right now we don't document that select and include select all sort of filters for relational fields.

See https://github.com/prisma/prisma/issues/2245 for additional context.

**Comment by mhwelander** [comment]
Filtering with `include` and `select` now documented here:

* https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering#filter-within-include
* https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering#filter-within-select
