### ISSUE TITLE
Accelerate cached structure stale after new db pushed (schema mismatch)

### ISSUE THREAD

**Issue by isalgadof** [prisma/prisma#22659]
### Bug description

Whenever a db schema modification is pushed to the server, Accelerate should regenerate to avoid schema mismatch.

Currently, the old schema remains clearly in a stale status (since the db push command is already given) and the cache is not only worthless, it's dangerous and stability breaking (or at least, making it difficult to predict behavior) and slows down development and forces to switch constantly in between connections instead of just regenerating as it should. 

### How to reproduce

1. Configure a database cached using Prisma Accelerate (I'm using it with Vercel Storage)
2. Program an endpoint to consume the data (I'm using server components @ App Router, Next v14) with cache. I'm using 10 minutes TTL, 10 minutes SWR.
3. Modify the schema and endpoint to use the new column as a filter or modify the name of some of the already used columns/filters
4. Push the new schema and attempt to use the app/page.

### Expected behavior

The app will either fail (throw Prisma validation error) or will obtain no records since the filter is incompatible with the available models properties. 

I'm getting no error, it just appears blank until the revalidation and update happens and suddently it's fine. 

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  directUrl = env("DIRECT_DATABASE_URL")
  relationMode = "prisma"
}
model Post {
  id   Int   @id @default(autoincrement())
  content Json?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  images Media[]
  url String @unique
}

model Media{
  id   Int   @id @default(autoincrement())
  url String?
  tipo String?
  hosting String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  post Post @relation(fields: [postId], references: [id])
  postId Int
}
```

### Environment & setup

- Host: Vercel
- Next.js: 14.0.4
- Database: Vercel Postgres
- Node.js version: 20.x (can't specify, it's automatic)

### Prisma Version

```
prisma                  : 5.8.0  
@prisma/client          : 5.8.0 
```

**Comment by nurul3101** [comment]
Hello @isalgadof 👋 

Thank you for trying out Accelerate and sharing this feature request.

If I understand correctly, at the moment, whenever a schema change is pushed with `prisma db push`, it is required to regenerate the `PrismaClient` and deploy this updated PrismaClient to the server in order to work correctly.

This feature request aims to remove this step, and Accelerate should automatically regenerate the PrismaClient whenever a schema change is pushed, correct?

**Comment by isalgadof** [comment]
No, the user's Prisma Client is not a problem since it regenerates on app rebuild (as in: prisma generate --no-engine && next build).

The problem is the cached schema/accelerate client/accelerate schema that ends up stale and won't update until TTL even if a new db schema push is received

**Comment by nurul3101** [comment]
Ah, Okay, now I get it. So essentially the cache should automatically be invalidated if the underlying schema for the model is changed.

**Comment by isalgadof** [comment]
That's a much better way to explain it haha, but yes. That's the underlying request.

**Comment by nurul3101** [comment]
Thanks for confirming. It makes sense!

I have noted this in the internal tool that we use to keep track of feature requests related to our commercial products (Accelerate and Pulse). Our product team will triage these requests and plan them. I'll add a comment here when there is an update.

I'll close this GitHub Issue as this repository is for our open-source product - Prisma ORM. Thank you for taking the time to share this request. 🙏
