### ISSUE TITLE
Prisma "Update available" notification shouldn't suggest global installation

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma#2268]
When generating the client with an older version of Prisma, an update is suggested.  But I suppose it shouldn't tell me to install Prisma globally when I use a local installation.

<img width="394" alt="Screenshot 2020-04-22 at 14 31 22" src="https://user-images.githubusercontent.com/7753942/79953546-3b25ec00-84a6-11ea-8626-756322753dc8.png">

**Comment by janpio** [comment]
Context:
- Code is here: https://github.com/prisma/prisma/blob/8d00f9f75563bcc654aa5cd4372b3b3fbdccf709/src/packages/cli/src/bin.ts#L178-L195
- Command currently comes as string from Checkpoint

We will probably have to change completely how this works and give control about the command to the CLI.

**Comment by pantharshit00** [comment]
Candidating this as this is an easy fix and it's been over 3 months now.

**Comment by janpio** [comment]
Until recently this was _not_ an easy fix, as the full message came from the update notification server.

We recently introduced the individual pieces of the message to the response to support this though: https://github.com/prisma/checkpoint-client/pull/12

Here is the improvement issue that will also close this bug report then: https://github.com/prisma/prisma/issues/2416

**Comment by janpio** [comment]
This should be fixed.
