### ISSUE TITLE
postgres check is not included in generated database migration

### ISSUE THREAD

**Issue by alexmilde** [prisma/prisma#22696]
### Bug description

Thanks for prisma! Amazing software.

I stumbled upon a problem / bug:

If i edit the check field in my database and generate a migration its not reflected.

### How to reproduce

1. Add check

![Bildschirmfoto 2024-01-18 um 00 01 22](https://github.com/prisma/prisma/assets/2182118/8d0570db-f0b8-4b11-bf60-6616bab2869a)

2. `npx prisma migrate dev --name add-check`

3. migration should look sth like this:

```
-- CreateTable
CREATE TABLE "user" (
    "email" TEXT NOT NULL AND CHECK (email <> ''),
);

```

But its not reflected at all.

### Expected behavior

```
-- CreateTable
CREATE TABLE "user" (
    "email" TEXT NOT NULL AND CHECK (email <> ''),
);

```

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model user {
  id        Int         @id @default(autoincrement())
  email     String
  password  String
  user_role user_role[]
}

model role {
  id        Int         @id @default(autoincrement())
  name      String
  user_role user_role[]
}

model user_role {
  user_id Int
  role_id Int
  role    role @relation(fields: [role_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
  user    user @relation(fields: [user_id], references: [id], onDelete: NoAction, onUpdate: NoAction)

  @@unique([user_id, role_id], map: "unique_index")
}

```

### Environment & setup

- OS:macOS
- Database:PostgreSQL
- Node.js version: v20.11.0

### Prisma Version

```
prisma                  : 5.8.1
@prisma/client          : 5.8.1
Computed binaryTarget   : darwin
Operating System        : darwin
Architecture            : x64
Node.js                 : v20.11.0
```

**Comment by SevInf** [comment]
Hi @alexmilde.
`CHECK` is something we do not currently support, unfortunately. I am going to close the issue in favor of existing feature request  #3388, you can follow the updates there. 

Thank you!

**Comment by janpio** [comment]
Hey @alexmilde, @SevInf already explained why this is happening, but I want to add something to that:

Prisma Migrations bring the database to the state that your Prisma Schema represents. If you change your database manually, as you did in the GUI you are using, you effectively lead to the migration history of Prisma breaking and being out of sync. This time this was not detected by `migrate dev` as it is a not supported feature, but usually you would get what we call a "drift message" and would need to _fix_ your database manually. 
The normal workflow for migrations is that you modify your `schema.prisma` file, run `migrate dev` to generate the migration and update your development database, then apply the same database via `migrate deploy`.

**Comment by alexmilde** [comment]
Hey. Thanks for the detailed explanation. I knew this. I just prefer modeling my database in a gui and generate schema and migrations afterwards locally. 

Thanks again for your work in prisma. It's really nice!
