### ISSUE TITLE
PostGIS extension causes detected changes

### ISSUE THREAD

**Issue by okonon** [prisma/prisma#22705]
### Bug description

I am running into an issue where PostGIS extension is causing weird changes that are detected and resulting in Prisma wanting reset whole database:
```
Drift detected: Your database schema is not in sync with your migration history.

The following is a summary of the differences between the expected database schema given your migrations files, and the actual schema of the database.

It should be understood as the set of changes to get from the expected schema to the actual schema.

[-] Removed extensions
`
[+] Added extensions
  - postgis

? We need to reset the "test" schema at "localhost:5432"
Do you want to continue? All data will be lost. › (y/N)
```

What is weird as you can see in the CLI output it has a backtick character on next line after `[-] Removed extensions` line.

### How to reproduce

install PostGIS to public schema and run `dotenv -e env/local.env -- prisma migrate dev --create-only --preview-feature` on existing schema with PostGIS added. 

### Expected behavior

there should not be any changes detected around removed/added extensions.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["postgresqlExtensions"]
}

generator nestjsDto {
  provider                        = "prisma-generator-nestjs-dto"
  output                          = "../src/common/generated"
  outputToNestJsResourceStructure = "true"
  flatResourceStructure           = "false"
  exportRelationModifierClasses   = "true"
  reExport                        = "true"
  createDtoPrefix                 = "Create"
  updateDtoPrefix                 = "Update"
  dtoSuffix                       = "Dto"
  entityPrefix                    = ""
  entitySuffix                    = ""
  classValidation                 = "true"
  fileNamingStyle                 = "camel"
  noDependencies                  = "false"
  outputType                      = "class"
  definiteAssignmentAssertion     = "true"
  prettier                        = "true"
}

datasource db {
  provider   = "postgresql"
  url        = env("DATABASE_URL")
  extensions = [postgis(schema: "public"), pgcrypto(schema: "public")]
}

// ****************************
// START Enums
// ****************************

enum Role {
  ADMIN
  USER
  SYS_ADMIN
}

// ****************************
// END Enums
// ****************************

model User {
  id          String    @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  email       String    @unique @db.VarChar(200)
  userName    String    @unique
  firstName   String    @db.VarChar(50)
  lastName    String    @db.VarChar(50)
  fullName    String    @db.VarChar(100)
  lastLoginAt DateTime? @db.Timestamp(6)
  roles Role[] @default([USER])

  // **************** SYSTEM FIELDS ****************
  isActive  Boolean  @default(true)
  updatedBy String?  @db.Uuid
  updatedAt DateTime @default(dbgenerated("timezone('UTC'::text, now())")) @updatedAt @db.Timestamp(6)
  createdBy String?  @db.Uuid
  createdAt DateTime @default(dbgenerated("timezone('UTC'::text, now())")) @db.Timestamp(6)

  // **************** RELATIONS ****************
  // Self-referential relations
  CreatedByUser User? @relation("CreatedByRelation", fields: [createdBy], references: [id])
  UpdatedByUser User? @relation("UpdatedByRelation", fields: [updatedBy], references: [id])
}
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.10.0

### Prisma Version

```
prisma                  : 5.8.0
@prisma/client          : 5.8.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine 0a83d8541752d7582de2ebc1ece46519ce72a848 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 0a83d8541752d7582de2ebc1ece46519ce72a848 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.8.0-37.0a83d8541752d7582de2ebc1ece46519ce72a848
Default Engines Hash    : 0a83d8541752d7582de2ebc1ece46519ce72a848
Studio                  : 0.497.0
Preview Features        : postgresqlExtensions
```

**Comment by janpio** [comment]
Did I understand correctly that you have a migrated database schema with a matching Prisma schema, then install the PostGIS extension manually, run `migrate dev` and up in the situation you describe above where it tells you that you are removing an extension `, and adding `postgis`?

I think generally it is expected that Prisma is unhappy in that case - you are supposed to _add_ the extension manually to your Prisma schema, and then let `migrate dev` create the SQL to active it on your schema, see https://www.prisma.io/docs/orm/prisma-schema/postgresql-extensions#how-to-migrate-postgresql-extensions Does it work that way?

But the single backtick is still weird of course.

**Comment by okonon** [comment]
@janpio thanks for quick reply! Hmm... here is what i am thinking. I added PostGIS using Prisma.schema like you described above in one application. However i am seeing the above issue in a different app that is connecting to same DB server but using different postgre user and schema. Could that be a problem ?

**Comment by janpio** [comment]
Yes, it is possible that the migration history include schema names in the generated SQL for example. Those migration files are used by `migrate dev` to understand the _expected_ current state of the database by running all of them on a temporary database.

So on the main database everything is fine, but when you switch to one with another schema name you get the problem reported above?

**Comment by okonon** [comment]
Ok here is what i did just now. One schema that i am working with. Connecting to AWS Aurora PostgreSQL serverless. Ran `dotenv -e env/dev.env -- prisma migrate dev --preview-feature` got the warding about data will be lost -> accepted and let the DB reset. Then i restored from schema backup to same schema and now the All data will be lost is back again. I think i am missing something in my workflow.

**Comment by janpio** [comment]
Prisma is telling you in that error message that your schema history (the .sql files on your disk) does not lead to the current state of the database - drift. Before Prisma executes a new migration, it makes sure the database is actually in the state it should be. So whatever state your database schema is in, is not what the sum of your migration files would be. By restoring the database schema, you basically turned it back into the drifted state.

**Comment by janpio** [comment]
If your migration history (sum of migration files) does not reflect the state of the database, and you get a drift warning because of that - yes. That is one way to solve that.

**Comment by okonon** [comment]
Thanks a lot for your time.

**Comment by georgemoon** [comment]
I'm observing the same problems that @okonon has with the mysterious backtick.

```
Drift detected: Your database schema is not in sync with your migration history.

…

[-] Removed extensions
`
[+] Added extensions
  - postgis
```

In this case someone modified a dev database outside of the prisma migrate structure (added a column), and I've managed to fix the migrations but continue to receive this error.

I've noticed that the error goes away if I comment out the following in `schema.prisma`
```
// previewFeatures = ["postgresqlExtensions"]
…
// extensions = [postgis]
```

Which is odd, because the schema still has geometry fields and the postgis extension enabled in the database.

**Comment by georgemoon** [comment]
After a lot of puzzling and digging it appears that the error message might be if the version of postgis provided by the server (in our case, a managed SQL database hosting service) is different from the version currently running on the database.

In our case updating postgis with `SELECT postgis_extensions_upgrade();` seemed to stop the weird error messages about drift. I think the more sustainable solution in the longer run is fixing the version of postgis in the extensions configuration.

**Comment by je-movers-market** [comment]
@georgemoon Definitely what's going on. In my case, I had upgraded my local DB version and began to get the migration error from Prisma, upgrading PostGIS itself fixed it. Thanks.

**Comment by johannsonic** [comment]
@georgemoon you are my hero

**Comment by CaitW** [comment]
In my case, doing the initial `prisma db pull` populated my schema with postgis version `3.4.2` when in reality it was `3.4.4`. 

Upgrading the postgis version solved my issue.

Edit: since posting this, the issue has happened twice more when doing unrelated migrations (despite my schema not specifying a version number for PostGIS?). Each time, running `SELECT postgis_extensions_upgrade();` causes the error to go away.
