### ISSUE TITLE
Renamed enum values crash at runtime when updated from Prisma 5.5.0 to 5.8.1

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma#22715]
### Bug description

I have multiple tables with renamed enums. I use introspection 

### How to reproduce

1. Create a database, fill logo table with all types of enum
2. Try query in 5.5.0
3. Update Prisma
4. Try query and observe the error

### Expected behavior

No error on the update

### Prisma information

As it seems this error is caused by non-`UTF8` collations. I use `cp1250_czech_cs`.

```prisma
model Logo {
  logoID        Int             @id @default(autoincrement()) @map("idLogo") @db.UnsignedSmallInt
  category      LogoCategory?   @map("skupina")

  @@map("loga")
}

enum LogoCategory {
  food      @map("potraviny")
  furniture @map("nábytek")
  hobby

  @@map("loga_skupina")
}
```

```ts
await prisma.logo.findMany();
```

### Environment & setup

- OS: Windows, Linux
- Database: MySQL
- Node.js version: v20.10.0

### Prisma Version

```
prisma                  : 5.8.1
@prisma/client          : 5.8.1
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine 78caf6feeaed953168c64e15a249c3e9a033ebe2 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 78caf6feeaed953168c64e15a249c3e9a033ebe2 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.8.1-1.78caf6feeaed953168c64e15a249c3e9a033ebe2
Default Engines Hash    : 78caf6feeaed953168c64e15a249c3e9a033ebe2
Studio                  : 0.497.0
Preview Features        : tracing
```

```
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
Preview Features        : tracing
```

**Comment by janpio** [comment]
What crash or error are you getting, when exactly?

**Comment by Akxe** [comment]
`PrismaClientUnknownRequestError` and details:

```
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(MysqlError { code: 3988, message: "Conversion from collation utf8mb4_general_ci into cp1250_czech_cs impossible for parameter", state: "HY000" })), transient: false })
    at si.handleRequestError (node_modules/@prisma/client/runtime/library.js:125:7007)
    at si.handleAndLogRequestError (node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (node_modules/@prisma/client/runtime/library.js:130:9805)
    at async /data/rita/apps/server/main.js:10138:19 {
  clientVersion: '5.8.1'
}
```

It occurred for every table (4 as observed from Sentry, during the short period it ran in prod) with a renamed enum.

**Comment by janpio** [comment]
The mention of the collation `cp1250_czech_cs` implies that the database is customized some way that Prisma would not do.

Can you maybe log the query that is triggering this error with both versions of Prisma so we can see the difference?

And just to be sure, you did not "rename" the enum between the Prisma versions, but this was "mapped" with `@map` before and after the upgrade, correct?

**Comment by Akxe** [comment]
@janpio It is true; all of my databases use `cp1250_czech_cs`, but it was not a problem until now. I did not change anything in DB during the upgrade nor downgrade.

The program crashed before logging the error and I cannot enable logs on the DB.

**Comment by Akxe** [comment]
To be honest, I forgot I had almost the same issue last year. It is why I got stuck to 5.5.x build... #21967

------

I have moved your finding there and I am closing this issue.
