### ISSUE TITLE
Prisma Client errors on SQLite with `internal error: entered unreachable code` when running 2 concurrent `upsert`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#22725]
### Bug description

When running 2 `upsert` concurrently:

In our functional tests (see PR https://github.com/prisma/prisma/pull/22723/)
- locally for me (macOS) it errors with `ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.), transient: false })]`
- in CI with `internal error: entered unreachable code`

### How to reproduce

See
- reproduction in functional tests https://github.com/prisma/prisma/pull/22723/ 
- isolated reproduction https://github.com/prisma/reproductions/tree/main/gh-22725

### Expected behavior

Something different from "internal error: entered unreachable code"

### Environment & setup

- OS: macOS
- Database: SQLite
- Node.js version: v20.9.0

### Prisma Version
```
Environment variables loaded from prisma/.env
prisma                  : 5.9.0-dev.25
@prisma/client          : 5.9.0-dev.25
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.9.0
Query Engine (Node-API) : libquery-engine 9c3f205e267265347308a10c5883579abb8361e1 (at ../node_modules/.pnpm/@prisma+engines@5.9.0-dev.25/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 9c3f205e267265347308a10c5883579abb8361e1 (at ../node_modules/.pnpm/@prisma+engines@5.9.0-dev.25/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-14.9c3f205e267265347308a10c5883579abb8361e1
Default Engines Hash    : 9c3f205e267265347308a10c5883579abb8361e1
Studio                  : 0.497.0
```

**Comment by jkomyno** [comment]
This issue was solved via https://github.com/prisma/prisma-engines/pull/4907.
