### ISSUE TITLE
Table `PDF` is generated as  `prisma.pDF.findMany`

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma#22749]
## Problem

The `prisma generate` command creates a weird prisma property name for tables whose name starts with multiple uppercase letters.

## Suggested solution

If the second letter in the table name is also uppercase, keep the first letter uppercase too.

## Alternatives

Rename all of it to lowercase, not necessarily nice.

## Additional context

Table `PDF` generates as `pDF`, using it then looks like this: `prisma.pDF.findMany(...)`

**Comment by janpio** [comment]
Prisma currently lowercases the first letter of each model in Prisma Client. If that is awkward, for now we indeed suggest you lowercase the whole model name in your Prisma schema already.

**Comment by Akxe** [comment]
@janpio  Is this something I could do as PR and have a chance at it being merged?

**Comment by janpio** [comment]
No chance of this being merged, no. Not lowercasing would also change `prisma.team` to `prisma.Team` if the model is capitalized, which is _very_ common.

**Comment by Akxe** [comment]
I want to not lowercase the name **only** if the second letter of the model name is uppercased too. 

Example:
```
team => team
Team => team
TEAM => TEAM

pdfHeader => pdfHeader
PDFHeader => PDFHeader
```

**Comment by janpio** [comment]
That would avoid the most common cases, but most probably still lead to unwanted changes for some users - similar to how they current behavior also leads to unwanted lowercasing for _some_ users.

Sorry.
