### ISSUE TITLE
Query using `orderBy` with `after` not giving expected results.

### ISSUE THREAD

**Issue by jana-uoft** [prisma/prisma#2274]
## Bug description

Cursor based ordering not working as expected. 
I have a use case of fetching more items from the backend on page scroll.
I do that by using the `after` argument giving it the last item from my current list of items.
However, I am not getting the correct results when combining it with `orderBy`.

## How to reproduce
* Section of my `shcema.prisma` file:
```
model media {
  id               Int             @default(autoincrement()) @id
  uploaded   DateTime?
  title            String?
  filename     String?   @unique
}
```
* Controller logic to handle my graphql query
```
prisma.media.findMany({
    ..._args,
    first: 20
  })
```
I limit the results to 20.

`args` is basically all fields that prisma-client supports
```
    getAllMyMedia(
      after: MediaCursorInput
      before: MediaCursorInput
      skip: Int
      last: Int
      where: MediaWhereInput
      orderBy: MediaOrderByInput
    ): [Media!]!
```

* Graphql query I use to get data
```
query {
  getAllMyMedia (
    orderBy: {title: asc}
  ){
    id
    title
  }
}
```
and get results like:
```
[
  { "id": 119521, "title": null },
  { "id": 119992, "title": null },
  { "id": 120008, "title": null },
  ........
]
```
* But, when combing with `after`
```
query {
    getAllMyMedia (
        orderBy: {title: asc}
        after: {id: 119992}
    ){
        id
        title
  }
}
```
, I get an empty array `[ ]`, instead I expect to get
```
[
 { "id": 120008, "title": null }
]
```

## Expected behavior

Is the `orderBy` happening at the end of query execution? I believe when combined with after, the `orderBy` should be done first and then apply the after.

Instead of an empty array, it should be:
```
[
 { "id": 120008, "title": null }
]
```

## Prisma information

Prisma info related to query without `after`
```
mymedia-dev | {
mymedia-dev |   timestamp: 2020-04-22T16:01:17.441Z,
mymedia-dev |   query: 'SELECT `mymedia`.`media`.`id`, `mymedia`.`media`.`uploaded`, `mymedia`.`media`.`originalFilename`, `mymedia`.`media`.`filename`, `mymedia`.`media`.`extension`, `mymedia`.`media`.`title`, `mymedia`.`media`.`description`, `mymedia`.`media`.`filesize`, `mymedia`.`media`.`resolution`, `mymedia`.`media`.`duration`, `mymedia`.`media`.`uoftOnly`, `mymedia`.`media`.`downloadable`, `mymedia`.`media`.`discoverable`, `mymedia`.`media`.`status`, `mymedia`.`media`.`systemMessage`, `mymedia`.`media`.`createdAt`, `mymedia`.`media`.`updatedAt`, `mymedia`.`media`.`userID` FROM `mymedia`.`media` WHERE 1=1 ORDER BY `mymedia`.`media`.`title` ASC, `mymedia`.`media`.`id` ASC LIMIT ? OFFSET ?',
mymedia-dev |   params: '[21,0]',
mymedia-dev |   duration: 0,
mymedia-dev |   target: 'quaint::connector::metrics'
mymedia-dev | }
```

With `after` 
```
mymedia-dev |   timestamp: 2020-04-22T16:02:50.535Z,
mymedia-dev |   query: 'SELECT `mymedia`.`media`.`id`, `mymedia`.`media`.`uploaded`, `mymedia`.`media`.`originalFilename`, `mymedia`.`media`.`filename`, `mymedia`.`media`.`extension`, `mymedia`.`media`.`title`, `mymedia`.`media`.`description`, `mymedia`.`media`.`filesize`, `mymedia`.`media`.`resolution`, `mymedia`.`media`.`duration`, `mymedia`.`media`.`uoftOnly`, `mymedia`.`media`.`downloadable`, `mymedia`.`media`.`discoverable`, `mymedia`.`media`.`status`, `mymedia`.`media`.`systemMessage`, `mymedia`.`media`.`createdAt`, `mymedia`.`media`.`updatedAt`, `mymedia`.`media`.`userID` FROM `mymedia`.`media` WHERE ((((`mymedia`.`media`.`title`) = (SELECT `mymedia`.`media`.`title` FROM `mymedia`.`media` WHERE (`mymedia`.`media`.`id`) = (?)) AND (`mymedia`.`media`.`id`) > (?)) OR (`mymedia`.`media`.`title`) > (SELECT `mymedia`.`media`.`title` FROM `mymedia`.`media` WHERE (`mymedia`.`media`.`id`) = (?))) AND 1=1) ORDER BY `mymedia`.`media`.`title` ASC, `mymedia`.`media`.`id` ASC LIMIT ? OFFSET ?',
mymedia-dev |   params: '[119992,119992,119992,21,0]',
mymedia-dev |   duration: 43,
mymedia-dev |   target: 'quaint::connector::metrics'
```

## Environment & setup

My entire setup is in Docker.

Using `node:12` as the base node image.
Using `mariadb:10.4` as the database image.
"@prisma/cli": "2.0.0-beta.2"

**Comment by richardwardza** [comment]
Although this is solved with the latest beta and using `take` and `cursor`, wouldn't your specific problem be that you have no data in `title` so the db doesn't 'order' the `null`s the same way every time?

I think this may have something to do with databases and the way they order nulls.

**Comment by pantharshit00** [comment]
@jana-uoft Please try again with the latest version and see if this is resovled for you.

We have changed the pagination API a bit.

**Comment by jana-uoft** [comment]
Hi guys, yes! 

I did update my code to use the latest release and started using `take` and `skip`. 
It works as intended now 👍  

Also as @richardwardza pointed out, it also might have to do with some values being `null`. 

But all is good now and thank you for the great work you guys are doing here 🙌
