### ISSUE TITLE
Rethink our generator approach

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#2279]
Generators have been introduced a long time ago, but not a lot has changed since then. Since the work on our [Go client](https://github.com/prisma/prisma-client-go) has started, we have discovered a [few things](https://github.com/prisma/prisma/issues/974) which might not be optimal. We want to make building things on top of Prisma as easy as possible, but it also should be endlessly customisable and powerful.

The idea of the initial generators is simple. Install the Prisma CLI, and specify any binary in the "generator" section in the schema.prisma file. That binary will receive information and can then handle generating the client by its own.

However, because of versioning, you'll end up wanting to bundle the Prisma CLI with the generator, since there's no better way when you have a different language than the CLI is written in (NodeJS). That means, for example, the Go client now has to first **bundle the Prisma CLI** in binaries (we can do that for our users in the future, though). The Go client **hardcodes the Prisma version** used in the code and **downloads the Prisma CLI** as well as the engines in a global cache folder. Now the fun begins: when you run the generation process from the go client (which is a Go command, since the user most likely wants to work with Go tools, plus this ensures proper versioning), the **Go command invokes the Prisma CLI**, which **invokes the Go generator** (which lives in the same repository), **returns the data to the Prisma CLI**, which **returns the data to the Go client**.

With the realisation of how other languages want to implement generators we may need to rethink our complete approach here, since the process above is overly complicated and probably not useful anymore.

Of course this is a tricky problem and other solutions might have different disadvantages, so I'm not saying we should change this immediately at all costs – but we should definitely think about it.

---

For example:

When we assume that generators provide the Prisma CLI, the Prisma CLI doesn't have to invoke the generator anymore. Instead, the generator could provide the schema file (or content) to the `prisma2 generate` command (or a new command), and that command would return the dmmf which can then be parsed by the generator.

**Comment by janpio** [comment]
Currently we are ok with the way our custom generators interact with Prisma CLI.
