### ISSUE TITLE
Add --no-telemetry flag for CLI commands

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#228]
The Prisma CLI is using Sentry to generate error reports. We should allow the user to opt-out of using this kind of telemetry by adding a dedicated option to the CLI commands, e.g. `--no-telemetry`. We also need to ensure that users are properly educated about anything that potentially concerns their data and are aware of the opt-out mechanisms.

**Comment by janpio** [comment]
Note: I recently noticed several CLIs separating their telemetry collection from error collection. (Of course currently can't remember which ones, so no link.) Makes the API a bit more complicated, but might make more people actually transmit the errors.

**Comment by matthewmueller** [comment]
We currently support the environment `CHECKPOINT_DISABLE=1` to disable telemetry. 

I don't have an opinion if we should additionally support this flag, but it is already possible. Unless `--no-telemetry` is a standard, I'd suggest we close this.

**Comment by pantharshit00** [comment]
Prior art: https://www.gatsbyjs.org/docs/telemetry/

**Comment by matthewmueller** [comment]
Thanks @pantharshit00. Closing as we already have this feature and it doesn't look like there's a standard.

**Comment by Mugane** [comment]
how do I disable it? it is attempting to send telemetry in spite of both these flags set 
      DISABLE_PRISMA_TELEMETRY: true
      CHECKPOINT_DISABLE: 1
Log: (failing because on dev and blocked by network firewall):
2024-02-08 23:47:09 [Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.
2024-02-08 23:48:10 [Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.
2024-02-08 23:49:10 [Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.

**Comment by janpio** [comment]
Your question is about Prisma 1 @Mugane, which has not been supported for a few years now. Sorry.

**Comment by Mugane** [comment]
@janpio Is there a more recent community version of Prisma?

**Comment by Mugane** [comment]
@janpio Ah, thanks. I figured since there were no docker images for versions > 1 that they had taken features closed-source or something which is so common these days.

**Comment by janpio** [comment]
No, Prisma ORM just is a normal Node package now that does not need a Docker package anymore. You install it via `npm install` and then can just use it without a server-side component in your app. We have no intention to go closed source any time soon 😆
