### ISSUE TITLE
Run button on Playground disappeared

### ISSUE THREAD

**Issue by franva** [prisma/prisma#22806]
### Bug description

![image](https://github.com/prisma/prisma/assets/5151146/cef1488b-d33f-4b9f-ac29-5362eea5fcd8)

The green run button is replaced with Loading... forever.

How to

### How to reproduce

1. Open a browser
2. Access this url: https://playground.prisma.io/examples/reading/filter/or

### Expected behavior

Expect to see the Green Run button

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by janpio** [comment]
Is this still a problem @franva?

For me it seems to be working:
<img width="1637" alt="image" src="https://github.com/prisma/prisma/assets/183673/b449147d-bc2d-401b-8087-fe2ecfa6fb40">

**Comment by franva** [comment]
The service is back. 
So what was the issue?

**Comment by janpio** [comment]
I don't have the slightest idea, but I internally asked the people that could find out. Most probably just a fluke on the service we are using for the playground.
