### ISSUE TITLE
Cannot return linked relations with update when using @@unique field

### ISSUE THREAD

**Issue by webnoob** [prisma/prisma#2280]
## Bug description

Given the following schema (excerpt):

```
model PenName {
  id Int  @default(autoincrement()) @id
  createdDate DateTime @default(now())
  isDraft Boolean @default(true)
  name String

  followers User[] @relation("followers", references: [id])
  
  user User @relation(fields: [userId], references: [id])
  userId Int

  @@unique([id, userId], name: "penName_id_userId")
}

model User {
  id Int  @default(autoincrement()) @id
  createdDate DateTime @default(now())

  emailAddress String @unique

  following PenName[] @relation("followers", references: [id])
}
```

When updating the penName model using **just** the id, I can `include: { followers: true }` and my returned model has followers available. When updating the penName using : `penName_id_userId: { id, userId }` the returned model from prisma doesn't include followers.

Example (sorry for screenshots but the red squigglies help identify the issue):

Not working with @@unique usage
![image](https://user-images.githubusercontent.com/10404747/80071824-32342980-853d-11ea-8908-09a600cb06bb.png)

Working with just the id:
![image](https://user-images.githubusercontent.com/10404747/80071879-49731700-853d-11ea-8128-65eefe6191db.png)

Am I expecting too much? The reason for the `@@unique` is so I can avoid another query before the updating to ensure the user owns the entity they're trying to update.

## How to reproduce
See above and also this code:

```ts
async update (userId: number, dto: UpdatePenNameDto): Promise<PenNameDto> {
    const model = await this.photonService.penName.update({
      include: {
        followers: true
      },
      where: {
        penName_id_userId: {
          id: dto.id,
          userId
        }
      },
      data: {
        name: dto.name,
        updatedDate: new Date()
      }
    })

    return {
      ...model,
      followers: []
      // TODO: Pending - https://github.com/prisma/prisma/issues/2280
      // followers: model.followers.
    }
  }
```
Changing
```
penName_id_userId: {
          id: dto.id,
          userId
        }
```
to
```
id: dto.id
```
will then allow `model.followers` to work.

## Expected behavior

I would expect followers to be available in both cases.

## Prisma information
See above.

## Environment & setup

- OS: Windows
- Database: MySQL 8.0
- Prisma version: beta.2
- Node.js version: 12

**Comment by webnoob** [comment]
If a schema is required for this, I've sent the full schema to schema@prisma.io in relation to another ticket: https://github.com/prisma/migrate/issues/373

**Comment by pantharshit00** [comment]
Hey sorry for the late reply on this one but can you please also paste the queries here. It is very pleasant to copy them from the screenshot 🙏

**Comment by webnoob** [comment]
Oh, my bad. I thought I added that as well.

Updated OP.

**Comment by webnoob** [comment]
I wonder if this is related to: https://github.com/prisma/prisma/issues/2141 which has just been fixed in beta.4. I will test.
