### ISSUE TITLE
Prisma console(prisma.console.io) with elements overlapping each other.

### ISSUE THREAD

**Issue by RicardoGEsteves** [prisma/prisma#22817]
### Bug description

![prisma-console-bug](https://github.com/prisma/prisma/assets/30535937/654ffd31-cf7c-44ed-b247-b52fb69cbe81)

On your prisma console in plans section you have elements overlapping each other.
Check the provided image.

### Prisma information

Not related to Prisma client schema, models or queries.

### Environment & setup

no ref.

### Prisma Version

no ref.

**Comment by nurul3101** [comment]
Hey @RicardoGEsteves 👋 

Thank you for taking the time to raise this issue. 🙏 

We have tracked it internally and will resolve it.

I'll mark this GitHub Issue as closed as this repository is for managing issues of Prisma ORM and not for our commercial product Prisma Data Platform.

**Comment by RicardoGEsteves** [comment]
> Hey @RicardoGEsteves 👋
> 
> Thank you for taking the time to raise this issue. 🙏
> 
> We have tracked it internally and will resolve it.
> 
> I'll mark this GitHub Issue as closed as this repository is for managing issues of Prisma ORM and not for our commercial product Prisma Data Platform.

@nurul3101 For future issues or bugs with console.prisma.io where should I report it? I mean in which repo?

**Comment by nurul3101** [comment]
@RicardoGEsteves We do not have a public repository for Prisma Data Platform (console.prisma.io). You can report issues in our [Discord](https://pris.ly/discord) or send an email to support@prisma.io

**Comment by RicardoGEsteves** [comment]
> @RicardoGEsteves We do not have a public repository for Prisma Data Platform (console.prisma.io). You can report issues in our [Discord](https://pris.ly/discord) or send an email to [support@prisma.io](mailto:support@prisma.io)

Ok, thanks for your reply.
