### ISSUE TITLE
PrismaClientInitializationError on AWS Lambda Node 20 Runtime

### ISSUE THREAD

**Issue by hffmnn** [prisma/prisma#22828]
### Bug description

When trying to run the prisma client on the AWS-provided Lambda Node 20 Runtime the prisma client fails to initialize and errors with a `PrismaClientInitializationError`.

Note: Switching back to the Node 18 runtime and everything works as expected.

Note: There seem to be some pretty big changes between the Node 18 runtime and the Node 20 runtime (including the underlying OS version) so I guess it has to do something with this:
https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/

### How to reproduce

1. Have a running AWS lambda function on Node 18 runtime
2. Change the runtime to Node 20
3. Run the lambda function
4. See the error (somewhere in cloudwatch) and in my case a 500 Internal Server Error. Sadly the error logging prisma is creating is so huge that important parts are missing. Maybe this would be another good issue?)

### Expected behavior

The same response I got when using the Node 18 runtime.

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  // x86
  binaryTargets = ["rhel-openssl-1.0.x"]
  // problem exists for arm64 also
  // binaryTargets = ["native", "linux-arm64-openssl-1.0.x"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Profile {
  id        String    @id @default(auto()) @map("_id") @db.ObjectId
}
```

```ts
// Doesn't really matter here. Any call to prisma will do. Because the logs are too big for cloudwatch, I don't know where it is happening exactly
```

### Environment & setup

- OS: AWS lambda node 20 runtime with Amazon Linux 2023
- Database: MongoDB (but I guess it is a general problem)
- Node.js version: Can't because it is in the cloud

### Prisma Version

Note: The query engine is (obviously) my local one
```
prisma                  : 5.8.1
@prisma/client          : Not found
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v18.19.0
Query Engine (Node-API) : libquery-engine 78caf6feeaed953168c64e15a249c3e9a033ebe2 (at service/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 78caf6feeaed953168c64e15a249c3e9a033ebe2 (at service/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.8.1-1.78caf6feeaed953168c64e15a249c3e9a033ebe2
Default Engines Hash    : 78caf6feeaed953168c64e15a249c3e9a033ebe2
Studio                  : 0.497.0
```

**Comment by janpio** [comment]
We have a test for running Prisma Client on Node 20 on Lambda https://github.com/prisma/ecosystem-tests/tree/dev/platforms-serverless/lambda-node-20 which is passing https://github.com/prisma/ecosystem-tests/actions/runs/7670430436/job/20906748565 - so I am pretty sure this is not a universal problem.

> `binaryTargets = ["rhel-openssl-1.0.x"]`

This might be the problem. I think the newer OS that AWS is running requires `libquery_engine-rhel-openssl-3.0.x.so.node`, so `rhel-openssl-3.0.x` as the `binaryTarget` value.

**Comment by hffmnn** [comment]
Wow.

thanks a lot for your quick response.

I can confirm that it runs with `rhel-openssl-3.0.x` on `x86_64` (and `linux-arm64-openssl-3.0.x` on `arm64`).

Maybe an update to the [docs](https://www.prisma.io/docs/orm/prisma-client/deployment/serverless/deploy-to-aws-lambda) would be nice, because there is no info about the newer runtime.

**Comment by janpio** [comment]
Absolutely, I raise this internally. I honestly was under the impression we had updated the docs, so thanks for the link that shows this not being the case.
