### ISSUE TITLE
Introspect should normalize naming conventions

### ISSUE THREAD

**Issue by krzkaczor** [prisma/prisma#2283]
## Problem
My Postgres database design follows Postgres naming conventions, so my tables have names like `project` or `external_project`. (snake case, singular noun). I want it to stay this way to follow standards, easily write SQL queries by hand etc.

After running the introspection, `schema.prisma` uses exactly the same names for model names which results in a very not idiomatic code in TypeScript (models named like `external_projct`.

## Solution
Introspect should normalize entity's names to PascalCase.
 
## Alternatives
Introspect can support custom name mapper function as an input that would provide a -> b mapping for all ids (table names, column names etc).

## Additional context
The current workaround for me is to manually edit schema file: tweak names and add `@@map(name: "Project")` where needed. But this gets overwritten every time I `introspect` again :(

**Comment by TLadd** [comment]
I'm doing the same thing with postgres. For now, I'm running a script after running introspection that applies the necessary changes: https://github.com/prisma/prisma/issues/1934#issuecomment-618063631. This works pretty well. However, I have run into an issue with mapping foreign key columns (https://github.com/prisma/prisma/issues/2294).

**Comment by albertoperdomo** [comment]
Already covered by https://github.com/prisma/prisma/issues/1934

**Comment by janpio** [comment]
> The current workaround for me is to manually edit schema file: tweak names and add `@@map(name: "Project")` where needed. But this gets overwritten every time I `introspect` again :(

The overwrite behavior should be fixed with 2.6.0 that is going to be released next week @krzkaczor
