### ISSUE TITLE
Overriding types

### ISSUE THREAD

**Issue by dstoyanoff** [prisma/prisma#22843]
## Problem
Everywhere in our application we support 2 custom types, which are transmitted over frontend and backend and automatically serialized through GraphQL. Those types are **Dayjs** instead of the system Date as well as **Decimal.js** for numbers. Since Prisma also uses **Decimal**, the issue there is not so important, but the lack of a way to use **Dayjs** forces us to remap types just to change this type, which is tedious. 

## Suggested solution
Prisma should provide a way to be able to adjust the generated types.

## Additional context
GraphQL scalars can be taken as an example. We are able to create scalars with custom parse/serialize functions which know how to translate the type.

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
