### ISSUE TITLE
Running `prisma generate` on Litespeed Web Server cPanel with ssh

### ISSUE THREAD

**Issue by markbrn1a** [prisma/prisma#22857]
### Bug description

I am opening this issue as the error message prompted me to report the experience, even though the application is functioning correctly after the generator configuration change. Please feel free to close if this is not a valid concern.

### How to reproduce

run npx generate on a LiteSpeed Web Server

### Prisma information

```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "                                                                                                                                                             undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/                                                                                                                                                             prisma/issues so we can add your distro to the list of known supported distros.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
```

and I got this error log too:

```
Prisma Client could not locate the Query Engine for runtime "debian-openssl-1.0.x".

This happened because Prisma Client was generated for "debian-openssl-1.1.x", but the actual deployment required "debian-openssl-1.0.x".
Add "debian-openssl-1.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.0.x"]
}
```

### Environment & setup

- OS: LiteSpeed Web Server
- Database: PostgreSQL
- Node.js version: 

### Prisma Version

```
"prisma": "^5.8.1",
```

**Comment by aqrln** [comment]
We should really just remove this warning now that there's no difference between `rhel` and `debian` binaries since they are built for the same minimal glibc version.

That said, do you know what your actual OS is that we failed to detect? I'm afraid "LiteSpeed Web Server" doesn't tell much. It's fine if you don't (e.g. your hosting provider doesn't provide this information).

**Comment by markbrn1a** [comment]
I'ts CloudLinux v7.9.0

**Comment by Jolg42** [comment]
Hi @markbrn1a 

I'll close this, as the fallback/default engine should work as expected, like you mentioned, so only a report would be needed if there is an issue.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
