### ISSUE TITLE
Error validating datasource db: the URL must start with the protocol prisma://

### ISSUE THREAD

**Issue by yuzakki** [prisma/prisma#22874]
### Question

Iam working on a nextjs 14 project using nextAuth and mongodb in the database Iam trying to create new user in sign up page this is my sign up action :

```
'use server';

import bcrypt from 'bcryptjs';

import { db } from '@/lib/db';
import { SignUpSchema, SignUpSchemaType } from '@/schemas/auth';
import { getUserByEmail } from '@/data/user';

export async function signup(data: SignUpSchemaType) {
  const validateFields = SignUpSchema.safeParse(data);

  if (!validateFields.success) {
    return { error: 'Invalid fields!' };
  }

  const { username, email, password } = validateFields.data;
  const hashedPassword = await bcrypt.hash(password, 10);

  try {
    const existingUser = await getUserByEmail(email);
    if (existingUser) return { error: 'Email already in use!' };

    await db.user.create({
      data: {
        username,
        email,
        password: hashedPassword,
      },
    });


    return { success: 'Sign Up Success!' };
  } catch (error: any) {
    if (error.code === 11000) {
      return { error: 'This username already in use!' };
    } else {
      throw new Error(`Failed: ${error.message}`);
    }
  }
}

```

and this is my prisma schema

```
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

enum Gender {
  male
  female
  unspecified
}

model User {
  id         String    @id @default(auto()) @map("_id") @db.ObjectId
  username   String    @unique()
  name       String?
  email      String    @unique()
  image      String?   @default("default.jpg")
  password   String
  gender     Gender?   @default(unspecified)
  birthday   DateTime? @db.Date
  bio        String?
  dateJoined DateTime? @db.Date
  Account    Account[]
}

model Account {
  id                String  @id @default(cuid()) @map("_id")
  userId            String  @db.ObjectId
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}
```

and my DATABASE_URL in .env looks something like this 
```
DATABASE_URL=mongodb+srv://username:password@host:port/friends?retryWrites=true&w=majority
```

what is causing the issue here can anyone help me on this

This is the error am encoutering :

```
Unhandled Runtime Error Error: Failed: Invalid prisma.user.create() invocation:

Error validating datasource db: the URL must start with the protocol prisma://

Source
actions\signup.ts (37:12) @ signup

  35 |     return { error: 'This username already in use!' };
  36 |   } else {
> 37 |     throw new Error(`Failed: ${error.message}`);
     |          ^
  38 |   }
  39 | }


  40 | }
```
i tried to delete node_modules and reinstall them but didn't worked for me

### Information about Prisma Schema, Client Queries and Environment (optional)

my prisma version: 
"prisma": "^5.9.0",
 

### How to reproduce

![screen](https://github.com/prisma/prisma/assets/81341137/6d6ad210-9a14-4f9e-8341-2991c89d9ff5)

### Prisma information

prisma schema: 

```
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

enum Gender {
  male
  female
  unspecified
}

model User {
  id         String    @id @default(auto()) @map("_id") @db.ObjectId
  username   String    @unique()
  name       String?
  email      String    @unique()
  image      String?   @default("default.jpg")
  password   String
  gender     Gender?   @default(unspecified)
  birthday   DateTime? @db.Date
  bio        String?
  dateJoined DateTime? @db.Date
  Account    Account[]
}

model Account {
  id                String  @id @default(cuid()) @map("_id")
  userId            String  @db.ObjectId
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}
```

### Environment & setup

database:     "mongodb": "^6.3.0",

### Prisma Version

```
 "prisma": "^5.9.0",

```

**Comment by janpio** [comment]
Did this work in 5.8.x or is this the first time you are trying this?

**Comment by yuzakki** [comment]
> Did this work in 5.8.x or is this the first time you are trying this? What does your `@/lib/db` look like? What does the output of `(npx) prisma -v` look like for you?

this is first time I work with prisma (with mongodb) and Iam using version latest version of it (5.9.0v)

my lib/db.ts file looks like this 

```
import { PrismaClient } from '@prisma/client/edge';

export const db = new PrismaClient();
```
the third question I didn't get it, im using 
npm version 10.2.4 v
nextjs 14.1.0 v

**Comment by yuzakki** [comment]
> Did this work in 5.8.x or is this the first time you are trying this? What does your `@/lib/db` look like? What does the output of `(npx) prisma -v` look like for you?

the problem is when i try to run this function on the signup page 

```
export async function signup(data: SignUpSchemaType) {
  const validateFields = SignUpSchema.safeParse(data);

  if (!validateFields.success) {
    return { error: 'Invalid fields!' };
  }

  const { username, email, password } = validateFields.data;
  const hashedPassword = await bcrypt.hash(password, 10);

  try {
    const existingUser = await getUserByEmail(email);
    if (existingUser) return { error: 'Email already in use!' };

    await db.user.create({
      data: {
        username,
        email,
        password: hashedPassword,
      },
    });


    return { success: 'Sign Up Success!' };
  } catch (error: any) {
    if (error.code === 11000) {
      return { error: 'This username already in use!' };
    } else {
      throw new Error(`Failed: ${error.message}`);
    }
  }
}
```

I get the following error 
![Uploading screen.png…]()

**Comment by yuzakki** [comment]
> Did this work in 5.8.x or is this the first time you are trying this? What does your `@/lib/db` look like? What does the output of `(npx) prisma -v` look like for you?

![screen](https://github.com/prisma/prisma/assets/81341137/c186dd7c-c648-4539-b82b-a2415a18a815)

**Comment by janpio** [comment]
You are importing `@prisma/client/edge`, which would be the way to import Prisma Client for Prisma Accelerate. Is that intentional?
If not, just remove the `/edge` and Prisma should work with a local MongoDB with a `mongodb://` protocol in the connection string.

**Comment by yuzakki** [comment]
> You are importing `@prisma/client/edge`, which would be the way to import Prisma Client for Prisma Accelerate. Is that intentional? If not, just remove the `/edge` and Prisma should work with a local MongoDB with a `mongodb://` protocol in the connection string.

I can't, 
when import `{ PrismaClient } from "@prisma/client"`

I get an error saying that "Prisma Client is unable to run in an edge runtime. As an alternative"

![scre](https://github.com/prisma/prisma/assets/81341137/c05a20ee-4a10-4ec1-bf5d-dc7d51e0d913)

**Comment by janpio** [comment]
Where are you trying to deploy Prisma to? 

Vercel Edge Functions for example are not supported yet with using Prisma directly . You can follow this issue: https://github.com/prisma/prisma/issues/21394 (But note that using MongoDB will not be possible in that context, as there is no edge function compatible client for MongoDB)

You can have a look at Prisma Accelerate if you want to use MongoDB in an edge function context today: https://www.prisma.io/data-platform/accelerate This will give you the `prisma://` connection string the error message tells you about.

**Comment by yuzakki** [comment]
> Where are you trying to deploy Prisma to?
> 
> Vercel Edge Functions for example are not supported yet with using Prisma directly . You can follow this issue: #21394 (But note that using MongoDB will not be possible in that context, as there is no edge function compatible client for MongoDB)
> 
> You can have a look at Prisma Accelerate if you want to use MongoDB in an edge function context today: https://www.prisma.io/data-platform/accelerate This will give you the `prisma://` connection string the error message tells you about.

I think im gonna change the database to postgress to work without edge I tried so many solutions however I do tried prisma accelerate but did not worked for me
anyway thanks mate 👍.
