### ISSUE TITLE
[5.9.0 Bug] `Prisma.TransactionClient` appears to be missing types

### ISSUE THREAD

**Issue by pheuter** [prisma/prisma#22870]
### Bug description

<img width="958" alt="image" src="https://github.com/prisma/prisma/assets/92698/22d87b7f-97e8-4880-81d1-917bf6559f74">

### How to reproduce

Update client to latest 5.9.0 and rerun `prisma generate`

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 5.9.0
@prisma/client          : 5.9.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.11.0
Query Engine (Node-API) : libquery-engine 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-32.23fdc5965b1e05fc54e5f26ed3de66776b93de64
Default Engines Hash    : 23fdc5965b1e05fc54e5f26ed3de66776b93de64
Studio                  : 0.497.0
```

**Comment by Druue** [comment]
Hey, I took a look and I can't confirm this.

I used the following schema:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```
and the following TS code:

```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({
  log: ["query"],
});

await prisma.$transaction(async (tx) => {
  const user = await tx.user.findFirst();
});
```

Note that `user` is available

<img width="981" alt="image" src="https://github.com/prisma/prisma/assets/29753584/de8a73ff-8f8b-40c9-b73d-51fd8b57d83d">

**Comment by pheuter** [comment]
We use functions that add some indirection, so we have code like the following:

```ts
import type { Prisma } from '@prisma/client';

export async function createEmployees(txn: Prisma.TransactionClient) {
  // ...
}
```

Can you confirm that the types still work when directly typing via `Prisma.TransactionClient` instead of letting the types flow from a `prisma.$transaction()` call?

/cc @Druue

**Comment by Druue** [comment]
Yeah, I still see types with the following @pheuter. I also double checked with Driver Adapters (you didn't specify whether you were using them or not), but that didn't make a difference either

```ts
async function indirection(txn: Prisma.TransactionClient) {
  const user = await txn.user.findFirst();
}

async function test() {
  const user = await prisma.$transaction(async (tx) => indirection(tx));
  console.log(user);
}
```

<img width="660" alt="image" src="https://github.com/prisma/prisma/assets/29753584/76f4db5e-9fc2-4e48-8d60-326741cd7102">

**Comment by pheuter** [comment]
```prisma
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "mongodb"
    url      = env("MONGODB_URI")
}
```

**tsconfig.json:**

```json
"verbatimModuleSyntax": true,
"isolatedModules": true,
"lib": [
	"esnext",
	"DOM",
	"DOM.Iterable"
],
"moduleResolution": "bundler",
"module": "esnext",
"noEmit": true,
"target": "esnext",
"allowJs": true,
"checkJs": true,
"esModuleInterop": true,
"forceConsistentCasingInFileNames": true,
"resolveJsonModule": true,
"skipLibCheck": true,
"sourceMap": true,
"strict": true
```

**Comment by Druue** [comment]
I have no `tsconfig.json` in my local repro set up but I can immediately say that just switching from `postgres` to `mongodb` makes no difference to the generated types. I'll try with the tsconfig now 👍

**Comment by Druue** [comment]
This currently causes no issues for me
```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "lib": [
      "ESNext",
      "DOM"
    ],
    "esModuleInterop": true,
    "noUnusedLocals": false
  }
}
```

Okay, yeah, on adding
```
 "moduleResolution": "bundler",
 "module": "esnext",
 ```
 I can confirm the lack of types 👍 
 
<img width="669" alt="image" src="https://github.com/prisma/prisma/assets/29753584/a3520317-0492-4990-b2fd-e31609f4f163">

indirection is not relevant
<img width="613" alt="image" src="https://github.com/prisma/prisma/assets/29753584/0f49846a-35ab-47f1-affc-264c060a2237">

**Comment by logiqui** [comment]
just change "moduleResolution" to "Node", works fine for me

**Comment by Druue** [comment]
Can also confirm that this causes types to be picked up for me :)
```json
"moduleResolution": "node",
"module": "esnext"
```

**Comment by pheuter** [comment]
I understand that changing `moduleResolution` works, but that shouldn't be required, and works fine with `moduleResolution: "bundler"` for Prisma 5.8.1. The latest version of SvelteKit requires `moduleResolution: "bundler"`.

**Comment by Jolg42** [comment]
@pheuter We are investigating this, we want to fix this in a patch release.
We'll keep you updated, and thanks for the report!

In the meantime, stay on `5.8.1`, until we release `5.9.1`

**Comment by darthmaim** [comment]
Just adding another issue that might be related:
Importing an Enum from the generated prisma client (`import { Language } from '@prisma/client'`) doesn't work anymore inside Next.js middleware (middleware uses the vercel edge runtime) after upgrading to 5.9.0.

**Comment by darthmaim** [comment]
My issue is still present even with `5.10.0-integration-fix-nodenext.2`, I will create a reproduction later today

**Comment by millsp** [comment]
@darthmaim Thanks for the report, I can see how this could impact you. I will be looking into this today, but feel free to share your repro anyways. Thanks!

**Comment by Jolg42** [comment]
I'll reopen this for now. We will close it once we have the patch published on npm as `5.9.1` later.

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.

**Comment by sorodrigo** [comment]
Has there been a regression on this? I'm using v5.15.0 and I'm experiencing the same issue:
<img width="863" alt="Screenshot 2024-09-28 at 11 52 43" src="https://github.com/user-attachments/assets/980a5fb5-1c83-4556-bb65-1bb71c739d3f">
