### ISSUE TITLE
[5.9.0] `@prisma/client` in Next.js middleware

### ISSUE THREAD

**Issue by darthmaim** [prisma/prisma#22877]
### Bug description

Using `@prisma/client` at runtime in a Next.js middleware is not working anymore after updating to 5.9.0.

### How to reproduce

Follow the instructions in this minimal reproduction:
https://github.com/darthmaim-reproductions/prisma-prisma-22877

### Expected behavior

I should be able to use `@prisma/client` in a Next.js middleware.

This was working in 5.8.1, which can be verified by changing the prisma version in the `package.json` of the reproduction and following the reproduction steps. Now `User` ist logged in the terminal, instead of the error occuring in 5.9.0

### Prisma information

See repository for prisma setup

### Environment & setup

- OS: Ubuntu inside WSL 2
- Database: doesn't matter
- Node.js version v20.7.0

### Prisma Version

```
prisma                  : 5.9.0
@prisma/client          : 5.9.0
Computed binaryTarget   : debian-openssl-1.1.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.7.0
Query Engine (Node-API) : libquery-engine 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-32.23fdc5965b1e05fc54e5f26ed3de66776b93de64
Default Engines Hash    : 23fdc5965b1e05fc54e5f26ed3de66776b93de64
Studio                  : 0.497.0
```

**Comment by darthmaim** [comment]
cc @millsp

This is the reproduction of the issue I reported in https://github.com/prisma/prisma/issues/22870#issuecomment-1917577291

**Comment by jdhenry08** [comment]
What error are you getting? Trying to track whether mine is the same.

**Comment by darthmaim** [comment]
Basically all imports are `undefined`. The error depends on what you are doing with the undefined value.

In this specific reproduction this is the error:

```
 ⨯ middleware.ts (4:23) @ ModelName
 ⨯ Cannot read properties of undefined (reading 'ModelName')
  2 |
  3 | export default function() {
> 4 |     console.log(Prisma.ModelName.User)
    |                       ^
  5 | }
```

**Comment by Jolg42** [comment]
@darthmaim Thanks a lot for opening this issue and providing a reproduction 🙌🏼 

I could reproduce with `5.9.0`, and this is a regression, since it was working in `5.8.1`.

@millsp already worked on a fix in https://github.com/prisma/prisma/pull/22880 and when trying the most recent version `5.10.0-integration-fix-client-exports-map.10` from this work in progress PR, I can confirm the issue is fixed.

Stay tuned for the official patch release 📻

**Comment by adamchipperfield** [comment]
I might be missing something, but how is this working even in 5.8.1? I thought Edge was a no-go with Prisma right now, and that support is actively being worked on?

**Comment by darthmaim** [comment]
> I might be missing something, but how is this working even in 5.8.1? I thought Edge was a no-go with Prisma right now (except with Accelerate), and that support is actively being worked on?

I'm not making any queries from Edge, only accessing the generated client. For example to use generated enums.

**Comment by adamchipperfield** [comment]
> > I might be missing something, but how is this working even in 5.8.1? I thought Edge was a no-go with Prisma right now (except with Accelerate), and that support is actively being worked on?
> 
> I'm not making any queries from Edge, only accessing the generated client. For example to use generated enums.

Ah, gotcha. Thanks for clearing that up!

**Comment by janpio** [comment]
(@adamchipperfield you might also see some issues from people that are part of the Early Access for edge functions support. See https://github.com/prisma/prisma/issues/21394 for the survey to sign up for that if you haven't yet.)

**Comment by adamchipperfield** [comment]
> (@adamchipperfield you might also see some issues from people that are part of the Early Access for edge functions support. See #21394 for the survey to sign up for that if you haven't yet.)

Thanks, @janpio! I believe I have signed up for this, but haven't had any Early Access just yet. Got a prime use case for this so would love to try out.

**Comment by LexaPetrov** [comment]
Hey, I also had this error message, most interesting that I`m not using prisma in middleware, but on matching routes I was having this error. The solution was to add runtime check in in globalThis in prisma initializer

![image](https://github.com/prisma/prisma/assets/26141816/8492510a-a13c-4581-adfe-9bfa2a9860c7)

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.

**Comment by darthmaim** [comment]
Thanks for the fast responses and release ❤️
