### ISSUE TITLE
please how i cant fix this message issues

### ISSUE THREAD

**Issue by truongit2701** [prisma/prisma#22885]
```
Server Error
Error: Prisma Client is unable to run in an edge runtime. As an alternative, try Accelerate: https://pris.ly/d/accelerate.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues/new

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
lib/db.ts (7:39) @ eval

   5 | }
   6 |
>  7 | export const db = globalThis.prisma || new PrismaClient();
     |                                       ^
   8 |
   9 | if (process.env.NODE_ENV !== 'production') globalThis.prisma = db;
  10 |
  ```

**Comment by aqrln** [comment]
@truongit2701 could you provide more details? What is your Prisma version? Do you get this error locally or on deployment? In the former case, are you using Node.js or other runtime? In the latter case, where are you deploying? Are you using any frameworks, bundlers, etc? It would be very helpful for us to resolve your problem if you could provide the information requested by the bug report template and a reproduction we can run.

Note that if get this error when actually deploying to the edge, it is currently expected as Prisma Client support on the edge is currently work in progress (https://github.com/prisma/prisma/issues/21394). However, given the multiple issues opened about this today, I suspect the error might not be expected for you, and we'd appreciate if you could help us provide the information necessary for us to help you. Thank you!

**Comment by millsp** [comment]
Hey @truongit2701 could you please give `5.10.0-integration-fix-client-exports-map.12` a try?

Update your `package.json` with:
* `"@prisma/client": "5.10.0-integration-fix-client-exports-map.12"`
* `"prisma": "5.10.0-integration-fix-client-exports-map.12"`

Install the packages (eg `npm install`), then run `prisma generate`, and give it a try again.

Can you please let us know if this fixed your issue?

**Comment by truongit2701** [comment]
thanks guys!
this is my db.ts file
```
import { PrismaClient } from '@prisma/client';

declare global {
   var prisma: PrismaClient | undefined;
}

export const db = globalThis.prisma || new PrismaClient();

if (process.env.NODE_ENV !== 'production') globalThis.prisma = db;
```

this is my env 
```
DATABASE_URL="postgresql://truongvovan.it2701:QvUZDLl28bsa@ep-dry-hat-a1qploi8-pooler.ap-southeast-1.aws.neon.tech/nextauth-v5?sslmode=require&pgbouncer=true"
DIRECT_URL="postgresql://truongvovan.it2701:QvUZDLl28bsa@ep-dry-hat-a1qploi8.ap-southeast-1.aws.neon.tech/nextauth-v5?sslmode=require"

AUTH_SECRET="Br9AUDNqpY3qOAqmzo5ulb8wCe6EYfKH7NxOx7SJZr0="
```

and this my pk.json
```
"dependencies": {
    "@auth/prisma-adapter": "^1.1.0",
    "@hookform/resolvers": "^3.3.4",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-slot": "^1.0.2",
    "bcrypt": "^5.1.1",
    "bcryptjs": "^2.4.3",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "next": "14.1.0",
    "next-auth": "^5.0.0-beta.5",
    "react": "^18",
    "react-dom": "^18",
    "react-hook-form": "^7.49.3",
    "react-icons": "^5.0.1",
    "tailwind-merge": "^2.2.1",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@prisma/client": "^5.9.0",
    "@types/bcrypt": "^5.0.2",
    "@types/bcryptjs": "^2.4.6",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.1.0",
    "postcss": "^8",
    "prisma": "^5.9.0",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
```

i use node v20 

i write next use nextauth-v5 
I made that mistake when i start next source

**Comment by truongit2701** [comment]
> @truongit2701 could you provide more details? What is your Prisma version? Do you get this error locally or on deployment? In the former case, are you using Node.js or other runtime? In the latter case, where are you deploying? Are you using any frameworks, bundlers, etc? It would be very helpful for us to resolve your problem if you could provide the information requested by the bug report template and a reproduction we can run.
> 
> Note that if get this error when actually deploying to the edge, it is currently expected as Prisma Client support on the edge is currently work in progress (#21394). However, given the multiple issues opened about this today, I suspect the error might not be expected for you, and we'd appreciate if you could help us provide the information necessary for us to help you. Thank you!

thanks guys!
this is my db.ts file
```
import { PrismaClient } from '@prisma/client';

declare global {
   var prisma: PrismaClient | undefined;
}

export const db = globalThis.prisma || new PrismaClient();

if (process.env.NODE_ENV !== 'production') globalThis.prisma = db;
```

this is my env 
```
DATABASE_URL="postgresql://truongvovan.it2701:QvUZDLl28bsa@ep-dry-hat-a1qploi8-pooler.ap-southeast-1.aws.neon.tech/nextauth-v5?sslmode=require&pgbouncer=true"
DIRECT_URL="postgresql://truongvovan.it2701:QvUZDLl28bsa@ep-dry-hat-a1qploi8.ap-southeast-1.aws.neon.tech/nextauth-v5?sslmode=require"

AUTH_SECRET="Br9AUDNqpY3qOAqmzo5ulb8wCe6EYfKH7NxOx7SJZr0="
```

and this my pk.json
```
"dependencies": {
    "@auth/prisma-adapter": "^1.1.0",
    "@hookform/resolvers": "^3.3.4",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-slot": "^1.0.2",
    "bcrypt": "^5.1.1",
    "bcryptjs": "^2.4.3",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "next": "14.1.0",
    "next-auth": "^5.0.0-beta.5",
    "react": "^18",
    "react-dom": "^18",
    "react-hook-form": "^7.49.3",
    "react-icons": "^5.0.1",
    "tailwind-merge": "^2.2.1",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@prisma/client": "^5.9.0",
    "@types/bcrypt": "^5.0.2",
    "@types/bcryptjs": "^2.4.6",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.1.0",
    "postcss": "^8",
    "prisma": "^5.9.0",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
```

i use node v20 

i write next use nextauth-v5 
I made that mistake when i start next source

**Comment by truongit2701** [comment]
> Hey @truongit2701 could you please give `5.10.0-integration-fix-client-exports-map.12` a try?
> 
> Update your `package.json` with:
> 
> * `"@prisma/client": "5.10.0-integration-fix-client-exports-map.12"`
> * `"prisma": "5.10.0-integration-fix-client-exports-map.12"`
> 
> Install the packages (eg `npm install`), then run `prisma generate`, and give it a try again.
> 
> Can you please let us know if this fixed your issue?

hey @millsp ! thankyou , i trired with npm i -g @prisma/client and then run prisma generate, but it still error:((

**Comment by truongit2701** [comment]
my shec prisma
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema


// prisma/schema.prisma
datasource db {
  provider  = "postgresql"
  url  	    = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}

generator client {
  provider = "prisma-client-js"
}


model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  password      String?
  accounts      Account[]
}

model Account {
  id                 String  @id @default(cuid())
  userId             String
  type               String
  provider           String
  providerAccountId  String
  refresh_token      String?  @db.Text
  access_token       String?  @db.Text
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String?  @db.Text
  session_state      String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}
```

**Comment by pavelbe** [comment]
Next.js Load Failure After Today's Prisma Update and Subsequent Database Interaction Issue After Applying Workaround 🚨🛠️

Today, I updated Prisma to the latest version in my Next.js application and faced a significant issue. Initially, the app failed to load, showing a browser error: "Error: Prisma Client is unable to run in an edge runtime. As an alternative, try Accelerate: https://pris.ly/d/accelerate. If this error is unexpected, please report it at https://github.com/prisma/prisma/issues/new."

Workaround Attempt:
After discovering the initial problem, I tried a workaround by changing the import statement from import { PrismaClient } from '@prisma/client' to import { PrismaClient } from '@prisma/client/edge'. This change allowed the application to load successfully in the browser. However, this led to a new issue when attempting to add a user to the database.

New Browser Error:

javascript
Copy code
Error: Invalid `prisma.user.create()` invocation:

Error validating datasource `db`: the URL must start with the protocol `prisma://`

Source
src\actions\register.ts (31:2) @ async register

 29 | }
 30 |
> 31 | await db.user.create({
     | ^
 32 |   data: {
 33 |     email,
 34 |     name,
This error highlights a problem with the datasource URL format, specifically when invoking prisma.user.create(). It indicates that the URL must start with the protocol prisma://, which is an unexpected requirement and unclear how to resolve within the current setup.

Seeking Guidance:
I am looking for any assistance or guidance on how to address both the initial app loading issue post-update and the subsequent database interaction problem. Your support would be greatly appreciated 🙏. Thank you for your help!

**Comment by janpio** [comment]
Stay on 5.8.1 until we release a path for 5.9.x in the form of 5.9.1 very soon @pavelbe

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.
