### ISSUE TITLE
`Error: Prisma Client is unable to run in an edge runtime. As an alternative, try Accelerate: https://pris.ly/d/accelerate.`

### ISSUE THREAD

**Issue by satyaprakash-yadav** [prisma/prisma#22889]
![Screenshot 2024-01-31 123922](https://github.com/prisma/prisma/assets/94888678/54412292-3f03-462d-9108-c3846052bf4b)

**Comment by aqrln** [comment]
Hi @satyaprakash-yadav! As the error message says, the stable version of Prisma Client currently only works in edge environments via Prisma Accelerate. We are actively working on making Prisma Client work in edge runtimes natively without requiring Accelerate and it's a high priority for us: we have already released driver adapters support in preview, which enables the usage of serverless and edge compatible database drivers, and we are currently working hard towards a public preview release of the feature that enables running the full Prisma Client on the edge soon. Please see the following issue: https://github.com/prisma/prisma/issues/21394.

If this error is unexpected for you and you don't actually deploy on the edge, then please open a new issue with more details and a reproduction. I'll go ahead and close this issue for now. Thank you!

**Comment by LexaPetrov** [comment]
Hey, I had this error message on matching routes from middleware, most interesting that I`m not using any prisma`s things in middleware, but on matching routes I was having this error. The solution was to add runtime check in globalThis in prisma initializer. 
![image](https://github.com/prisma/prisma/assets/26141816/62625bb9-cac8-4317-a9e0-8d0f221a123c)

**Comment by millsp** [comment]
Hey @satyaprakash-yadav @LexaPetrov, could you please give `5.10.0-integration-fix-client-exports-map.12`?

Update your `package.json` with:
* `"@prisma/client": "5.10.0-integration-fix-client-exports-map.12"`
* `"prisma": "5.10.0-integration-fix-client-exports-map.12"`

Install the packages (eg `npm install`), then run `prisma generate`, and give it a try again.

Can you please let us know if this fixed your issue?

**Comment by LexaPetrov** [comment]
> Hey @satyaprakash-yadav @LexaPetrov, could you please give `5.10.0-integration-fix-client-exports-map.12` a try?
> 
> Update your `package.json` with:
> 
> * `"@prisma/client": "5.10.0-integration-fix-client-exports-map.12"`
> * `"prisma": "5.10.0-integration-fix-client-exports-map.12"`
> 
> Install the packages (eg `npm install`), then run `prisma generate`, and give it a try again.
> 
> Can you please let us know if this fixed your issue?

Yes, all works

**Comment by satyaprakash-yadav** [comment]
![Screenshot 2024-02-01 135546](https://github.com/prisma/prisma/assets/94888678/b503875a-6ad7-4006-bd28-66dd7dbc5c57)
this my prisma and nodejs version

**Comment by janpio** [comment]
@satyaprakash-yadav Please open a new issue instead of distributing your comments across 4 different issues. Include _all_ information you can shared with us in that issue.

**Comment by Jolg42** [comment]
@satyaprakash-yadav you can also set this the version for Prisma packages to "5.9.1-dev.2" and try again, then let us know if that's fixed. I got a confirmation from someone using Next.js and Next-Auth v5 that this fixed the issue for them.

We will later release an official patch version.

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.
