### ISSUE TITLE
[v5.9.0] `$extends` always return `any`

### ISSUE THREAD

**Issue by mwskwong** [prisma/prisma#22884]
### Bug description

Basically the title. `$extends` will always return `any` instead of the generated `PrismaClient` type. This issue is not reproducible on v5.8.1.

### How to reproduce

[![Edit Prisma extends always return any type](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/prisma-extends-always-return-any-type-dwx89z?file=%2Fpackage.json&embed=1)

### Expected behavior

`$extends` should return a valid `PrismaClient` type.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Test {
  id   String @id
}
```

```ts
import { PrismaClient } from "@prisma/client";
import { readReplicas } from "@prisma/extension-read-replicas";

// this has the generated type
const client = new PrismaClient();

// this will always in type `any`
const clientWithExtends = new PrismaClient().$extends();

// same applies with a valid extension specified
const clientWithExtends = new PrismaClient().$extends(
  readReplicas({ url: "" }),
);
```

### Environment & setup

- OS: Code Sandbox
- Database: PostgreSQL
- Node.js version: 20.9.0

### Prisma Version

```
prisma                  : 5.9.0
@prisma/client          : 5.9.0
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.9.0
Query Engine (Node-API) : libquery-engine 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/.pnpm/@prisma+engines@5.9.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/.pnpm/@prisma+engines@5.9.0/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-32.23fdc5965b1e05fc54e5f26ed3de66776b93de64
Default Engines Hash    : 23fdc5965b1e05fc54e5f26ed3de66776b93de64
Studio                  : 0.497.0
```

**Comment by millsp** [comment]
Hey @mwskwong, maybe your issue is related to this one https://github.com/prisma/prisma/issues/22870? Could you please try the integration version shared [here](https://github.com/prisma/prisma/issues/22870#issuecomment-1917587412) and let me know if that helped?

**Comment by alabdulaal** [comment]
I was having the same issue using `5.10.0-integration-fix-nodenext.2` solved it for me.

**Comment by mwskwong** [comment]
> Hey @mwskwong, maybe your issue is related to this one #22870? Could you please try the integration version shared [here](https://github.com/prisma/prisma/issues/22870#issuecomment-1917587412) and let me know if that helped? Thanks.

No, the client does have a type now, except it is `DynamicClientExtensionThis<Prisma.TypeMap<any>, Prisma.TypeMapCb, any>`. So, it's still buggy.

**Comment by butadpj** [comment]
I also got this issue just so recently after updating my prisma from `5.8.1` -> `5.9.0`. Im also using `$extends` and now it returns any instead of the actual types

**Comment by Jolg42** [comment]
@mwskwong Thanks for opening this issue and providing a reproduction 🙌🏼 

I could reproduce with `5.9.0`, and this is a regression, since it was working in `5.8.1`.

@millsp already worked on a fix in https://github.com/prisma/prisma/pull/22880 and when trying the most recent version `5.10.0-integration-fix-client-exports-map.10` from this work in progress PR, I can no longer reproduce the issue 🎊 .

Stay tuned for the official patch release 📻
