### ISSUE TITLE
Prisma edge runtime error

### ISSUE THREAD

**Issue by MuhammadAhsaanAbbasi** [prisma/prisma#22886]
`Error: Prisma Client is unable to run in an edge runtime. As an alternative, try Accelerate`

 when I write auth.config,ts file so it's shown me this error

**Comment by aqrln** [comment]
@MuhammadAhsaanAbbasi could you provide more details? What is your Prisma version? Do you get this error locally or on deployment? In the former case, are you using Node.js or other runtime? In the latter case, where are you deploying? Are you using any frameworks, bundlers, etc? It would be very helpful for us to resolve your problem if you could provide the information requested by the bug report template and a reproduction we can run.

Note that if get this error when actually deploying to the edge, it is currently expected as Prisma Client support on the edge is currently work in progress (https://github.com/prisma/prisma/issues/21394). However, given multiple issues opened about this today, I suspect the error might not be expected for you, and we'd appreciate if you could help us provide the information necessary for us to help you.

**Comment by Jolg42** [comment]
@MuhammadAhsaanAbbasi Could you try the following version `5.10.0-integration-fix-client-exports-map.11` and let us know if that fixes the issue?

(Note: related to https://github.com/prisma/prisma/pull/22880)

This will be part of the official `5.9.1` patch release soon.

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.

**Comment by MuhammadAhsaanAbbasi** [comment]
> @MuhammadAhsaanAbbasi Could you try the following version `5.10.0-integration-fix-client-exports-map.11` and let us know if that fixes the issue?
> 
> (Note: related to #22880)
> 
> This will be part of the official `5.9.1` patch release soon.

I Don't try this version bro

**Comment by MuhammadAhsaanAbbasi** [comment]
> @MuhammadAhsaanAbbasi could you provide more details? What is your Prisma version? Do you get this error locally or on deployment? In the former case, are you using Node.js or other runtime? In the latter case, where are you deploying? Are you using any frameworks, bundlers, etc? It would be very helpful for us to resolve your problem if you could provide the information requested by the bug report template and a reproduction we can run.
> 
> Note that if get this error when actually deploying to the edge, it is currently expected as Prisma Client support on the edge is currently work in progress (#21394). However, given multiple issues opened about this today, I suspect the error might not be expected for you, and we'd appreciate if you could help us provide the information necessary for us to help you.

Brother  I use latest version and I get this error on locally currently I stop my project and using node js and want to deploy on vercel and Next.js framework is using
