### ISSUE TITLE
[5.9.0] All queries result in any type

### ISSUE THREAD

**Issue by ksturtzkopf** [prisma/prisma#22888]
### Bug description

Hey :)

When migrating to v5.9.0, all types in my project are now being returned as any. 
Or  `$Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "upsert">` for the variable I declared as the result of the query and `any` for any subsequent operations on said variable, to be more precise.

(This issue is highly related to #22884, though it seems to be a larger issue?)

The workaround, for the time being, is to simply migrate back to 5.8.1.

### How to reproduce

Simply change the `@prisma/client` version to 5.9.0 and generate the types.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS:  macOS
- Database: PostgreSQL
- Runtime: bun

### Prisma Version

```
prisma                  : 5.9.0
@prisma/client          : 5.9.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.8.0
Query Engine (Node-API) : libquery-engine 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-32.23fdc5965b1e05fc54e5f26ed3de66776b93de64
Default Engines Hash    : 23fdc5965b1e05fc54e5f26ed3de66776b93de64
Studio                  : 0.497.0
```

**Comment by kolserdav** [comment]
+1

**Comment by aqrln** [comment]
@ksturtzkopf @kolserdav could you please check if the pre-release intergration version `5.10.0-integration-fix-nodenext.2` solves the issue for you by any chance? (Install it as an exact version without `^` and re-generate the client)

**Comment by ksturtzkopf** [comment]
@aqrln that seems to solve it! Thank you :)

**Comment by aqrln** [comment]
@ksturtzkopf awesome, thanks for checking. Then the upcoming 5.9.1 patch should solve the problem for you.

**Comment by millsp** [comment]
Closing this issue, as it is fixed by https://github.com/prisma/prisma/pull/22876.

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.
