### ISSUE TITLE
[5.9.0] Error: Prisma Client is unable to run in an edge runtime. As an alternative, try Accelerate: https://pris.ly/d/accelerate.

### ISSUE THREAD

**Issue by mohe22** [prisma/prisma#22893]
I'm using Next Auth with next.js 14

![Screenshot 2024-01-31 213240](https://github.com/prisma/prisma/assets/158163162/901d4fda-2274-4af1-bc8f-37e2aa11ab9d)
![Uploading Screenshot 2024-01-31 213307.png…]()

**Comment by mohe22** [comment]
no I'm getting the error locally
"@prisma/client": "^5.9.0",    "@auth/prisma-adapter": "^1.1.0",
and I'm using node v 18.18.0.

**Comment by Jolg42** [comment]
@mohe22 Could you try the following version `5.10.0-integration-fix-client-exports-map.11` and let us know if that fixes the issue?

(Note: related to https://github.com/prisma/prisma/pull/22880)

**Comment by mohe22** [comment]
I changed the version "prisma": "^5.10.0-integration-fix-client-exports-map.11", however still have the issue

**Comment by Jolg42** [comment]
@mohe22 Make sure to remove the caret `^` and put `5.10.0-integration-fix-client-exports-map.11` as the version and try again.

Note, you can do the following
- update the version
- `npm install`
- `npx prisma generate`
- Try what was not working before.

If there is still a problem after that, please provide a minimal reproduction, here is recent one as an example: https://github.com/darthmaim-reproductions/prisma-prisma-22877

**Comment by millsp** [comment]
Hey @mohe22, could you please try with both as the following, install, then run `prisma generate`:
`"prisma": "5.10.0-integration-fix-client-exports-map.11"`
and
`"@prisma/client": "^5.10.0-integration-fix-client-exports-map.11"`

(Notice the removal of the caret `^`)

**Comment by mohe22** [comment]
I solved the error by 
1- "prisma": "^5.8.1",
2- and change import { PrismaClient } from "@prisma/client" to import { PrismaClient } from "@prisma/client/edge";
thank you.

**Comment by millsp** [comment]
Hey @mohe22 great to hear! That said, we shouldn't break anything really. Could you please try both `@prisma/client` and `prisma` with the version share by my colleague [above](https://github.com/prisma/prisma/issues/22893#issuecomment-1919442941)? Thanks

**Comment by mohe22** [comment]
I tried the above ones it did not work with me.
when i changed the versions to 
   "prisma": "^5.8.1",
    "@prisma/client": "5.8.1",
    it works without any errors

**Comment by Jolg42** [comment]
@mohe22 It would help us if you can provide a minimal reproduction of your problem, like I mentioned earlier, here is recent one as an example: https://github.com/darthmaim-reproductions/prisma-prisma-22877

With that we would then try to reproduce on our side, and optimally we can see with that reproduction:
- that everything works in `5.8.1`
- something breaks in `5.9.0`
And then, based on that, we can find a fix and confirm it.

Is that something you could send us today maybe?

**Comment by BernardinoOtais** [comment]
> I tried the above ones it did not work with me. when i changed the versions to "prisma": "^5.8.1", "@prisma/client": "5.8.1", it works without any errors

Hi, I confirm that this works, had the same problem, so changed to 5.8.1, the issue is in version 5.9.0

**Comment by Jolg42** [comment]
@BernardinoOtais So you are also using Next.js and Next Auth v5?

Could you set the version for Prisma packages to "5.9.1-dev.2" and try again, then let us know if that's fixed?

This would help to confirm that everything is fixed for our patch release planned later today.

**Comment by Jolg42** [comment]
@BernardinoOtais Thanks! Then please wait for the official `5.9.1` patch release later today.
In the meantime, you can stay on the previous version `5.8.1`

**Comment by BernardinoOtais** [comment]
Thanks @Jolg42

**Comment by pavelbe** [comment]
Next.js Load Failure After Today's Prisma Update and Subsequent Database Interaction Issue After Applying Workaround 🚨🛠️

Today, I updated Prisma to the latest version in my Next.js application and faced a significant issue. Initially, the app failed to load, showing a browser error: "Error: Prisma Client is unable to run in an edge runtime. As an alternative, try Accelerate: https://pris.ly/d/accelerate. If this error is unexpected, please report it at https://github.com/prisma/prisma/issues/new."

Workaround Attempt:
After discovering the initial problem, I tried a workaround by changing the import statement from import { PrismaClient } from '@prisma/client' to import { PrismaClient } from '@prisma/client/edge'. This change allowed the application to load successfully in the browser. However, this led to a new issue when attempting to add a user to the database.

New Browser Error:

javascript
Copy code
Error: Invalid prisma.user.create() invocation:

Error validating datasource db: the URL must start with the protocol prisma://

Source
src\actions\register.ts (31:2) @ async register

29 | }
30 |

31 | await db.user.create({
| ^
32 | data: {
33 | email,
34 | name,
This error highlights a problem with the datasource URL format, specifically when invoking prisma.user.create(). It indicates that the URL must start with the protocol prisma://, which is an unexpected requirement and unclear how to resolve within the current setup.

Seeking Guidance:
I am looking for any assistance or guidance on how to address both the initial app loading issue post-update and the subsequent database interaction problem. Your support would be greatly appreciated 🙏. Thank you for your help!

**Comment by janpio** [comment]
No need to post the same message in multiple issues @pavelbe, I already replied to your message here: https://github.com/prisma/prisma/issues/22885#issuecomment-1921053924

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.
