### ISSUE TITLE
Downloading Prisma Engines for Node-API for debian-openssl-3.0.x Error on Ubuntu 22.04

### ISSUE THREAD

**Issue by laduniestu** [prisma/prisma#22906]
### Bug description

```
npx prisma generate
> Downloading Prisma engines for Node-API for debian-openssl-3.0.x [] 0%Error: request to https://binaries.prisma.sh/all_commits/23fdc5965b1e05fc54e5f26ed3de66776b93de64/debian-openssl-3.0.x/libquery_engine.so.node.gz.sha256 failed, reason:
```

### How to reproduce
1. Run npx prisma generate

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

enum UserRole {
  ADMIN
  USER
}

model User {
  id                    String                 @id @default(cuid())
  name                  String?
  email                 String?                @unique
  emailVerified         DateTime?
  image                 String?
  password              String?
  role                  UserRole               @default(USER)
  accounts              Account[]
  sessions              Session[]
  isTwoFactorEnabled Boolean @default(false)
  twoFactorConfirmation TwoFactorConfirmation?
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? @db.Text
  access_token      String? @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.Text
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model VerificationToken {
  id      String   @id @default(cuid())
  email   String
  token   String   @unique
  expires DateTime

  @@unique([email, token])
}

model PasswordResetToken {
  id      String   @id @default(cuid())
  email   String
  token   String   @unique
  expires DateTime

  @@unique([email, token])
}

model TwoFactorToken {
  id      String   @id @default(cuid())
  email   String
  token   String   @unique
  expires DateTime

  @@unique([email, token])
}

model TwoFactorConfirmation {
  id     String @id @default(cuid())
  userId String
  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([userId])
}
```

### Environment & setup

- OS: buntu 22.04 lts
- Database: Mysql
- Node.js version: 20.11.0

### Prisma Version

```
not installed
```

**Comment by aqrln** [comment]
Does this happen to you consistently or was this a random network failure?

**Comment by agangdi** [comment]
I have the same problem and it seems consistent, curl //binaries.prisma.sh/all_commits/4bc8b6e1b66cb932731fb1bdbbc550d1e010de81/debian-openssl-3.0.x/libquery_engine.so.node.gz.sha256 is okay, but npx prisma generate keeps failed. Is there any way to install debian-openssl-3.0.x manually ?

**Comment by aqrln** [comment]
@agangdi 

> Is there any way to install debian-openssl-3.0.x manually ?

Technically you could use the [`PRISMA_QUERY_ENGINE_LIBRARY`](https://www.prisma.io/docs/orm/more/under-the-hood/engines#using-custom-engine-libraries-or-binaries) environment variable to point it at a manually downloaded binary.

That said, it shouldn't be necessary of course and it would be better to solve the underlying issue. Do you have any idea why `curl` works while Node.js doesn't? Could please you paste the full error message here? And maybe also the output of `npx prisma debug`.

**Comment by agangdi** [comment]
@aqrln Thanks for your advice.
I used the docker environment to downgrade to OpenSSL 1.0 to temporarily run the service. But the problem with 3.0 still exists. Here are my usage logs and npx prisma debug logs. Hope this helps.
```
npx prisma migrate deploy
> Downloading Prisma engines for Node-API for debian-openssl-3.0.x [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/23fdc5965b1e05fc54e5f26ed3de66776b93de64/debian-openssl-3.0.x/libquery_engine.so.node.gz.sha256 failed, reason:
```
```
 npx prisma debug
Environment variables loaded from .env
-- Prisma schema --
Path: /home/www/tour-app2/prisma/schema.prisma

-- Local cache directory for engines files --
Path: /home/www/.cache/prisma

-- Environment variables --
When not set, the line is dimmed and no value is displayed.
When set, the line is bold and the value is inside the `` backticks.

For general debugging
- CI:
- DEBUG:
- NODE_ENV:
- RUST_LOG:
- RUST_BACKTRACE:
- NO_COLOR:
- TERM: `xterm-256color`
- NODE_TLS_REJECT_UNAUTHORIZED: `1`
- NO_PROXY:
- http_proxy:
- HTTP_PROXY:
- https_proxy:
- HTTPS_PROXY:

For more information about Prisma environment variables:
See https://www.prisma.io/docs/reference/api-reference/environment-variables-reference

For hiding messages
- PRISMA_DISABLE_WARNINGS:
- PRISMA_HIDE_PREVIEW_FLAG_WARNINGS:
- PRISMA_HIDE_UPDATE_MESSAGE:

For downloading engines
- PRISMA_ENGINES_MIRROR:
- PRISMA_BINARIES_MIRROR (deprecated):
- PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING:
- BINARY_DOWNLOAD_VERSION:

For configuring the Query Engine Type
- PRISMA_CLI_QUERY_ENGINE_TYPE:
- PRISMA_CLIENT_ENGINE_TYPE:

For custom engines
- PRISMA_QUERY_ENGINE_BINARY:
- PRISMA_QUERY_ENGINE_LIBRARY:
- PRISMA_SCHEMA_ENGINE_BINARY:
- PRISMA_MIGRATION_ENGINE_BINARY:

For the "postinstall" npm hook
- PRISMA_GENERATE_SKIP_AUTOINSTALL:
- PRISMA_SKIP_POSTINSTALL_GENERATE:
- PRISMA_GENERATE_IN_POSTINSTALL:

For "prisma generate"
- PRISMA_GENERATE_DATAPROXY:
- PRISMA_GENERATE_NO_ENGINE:

For Prisma Client
- PRISMA_SHOW_ALL_TRACES:
- PRISMA_CLIENT_NO_RETRY (Binary engine only):

For Prisma Migrate
- PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK:
- PRISMA_MIGRATE_SKIP_GENERATE:
- PRISMA_MIGRATE_SKIP_SEED:

For Prisma Studio
- BROWSER:

-- Terminal is interactive? --
true

-- CI detected? --
false
```
Weirdly, OpenSSL 1.0 goes well but OpenSSL 3.0 keeps getting errors. I already upgraded Prisma to the latest version.

**Comment by janpio** [comment]
@laduniestu What about your case, can you provide some additional information for us? Could you fix it? Can you download the file manually by copy-öasting the URL into your browser?

**Comment by laduniestu** [comment]
sorry for replying late. My issue was solved by reinstalling my server OS. Thanks

**Comment by haseebkhan9081** [comment]
just use a vpn ,it worked for me

**Comment by Wepa121** [comment]
I encountered the same issue when I was using Node.js version `v20.12.2`. The problem was resolved after downgrading to version `v18.20.2`.

**Comment by badJaguar** [comment]
[Wepa121](https://github.com/Wepa121) My issue was when I am using `v22.2.0` on my linux machene but resolved the `v18.20.2` as well.

**Comment by Tosinkoa** [comment]
> I encountered the same issue when I was using Node.js version `v20.12.2`. The problem was resolved after downgrading to version `v18.20.2`.

Thank you for this, it fix the issue

**Comment by ujjwalmathur** [comment]
Thanks, @Wepa121 ! Switching to version 18.20.5 worked for me too, and I didn’t need to use the VPN.

**Comment by aryomuzakki** [comment]
I'm in node 24, and downgrading to 18 worked, it is just to download it. No issue after using node 24 again to run prisma generate, db push, or db seed

**Comment by nihat-js** [comment]
I solved problem by  manually downloading

cd /tmp
wget https://cdn.prisma.io/direct/master/ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba/debian-openssl-3.0.x/schema-engine.gz
gunzip schema-engine.gz
cd ~/sites/mysite.az
mkdir -p node_modules/.prisma/client
cp /tmp/schema-engine node_modules/.prisma/client/
chmod +x node_modules/.prisma/client/schema-engine
PRISMA_SKIP_DOWNLOAD=true npx prisma generate

**Comment by afsuyadi** [comment]
I have tried above all of the solutions, but none work in my local. I did try this and it's successful :

sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1

This works by disabling IPv6 networking on my system. Hope it helps .

**Comment by Chadrack00** [comment]
run this : "sudo apt-get update && sudo apt-get install -y openssl ca-certificates" in linux and reload your IDE if you install it in IDE.
Don't thank me :)
