### ISSUE TITLE
`Internal error: Attempted to serialize empty result.` on `upsert()` for `update` case in different databases (when using `relationMode=prisma` explicitly or implicitly [MongoDB])

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#22916]
We have multiple reports of a crash with `Internal error: Attempted to serialize empty result.` on `upsert`, in MySQL, MongoDB and SQLite. Most probably those are related to each other. 

Convenient searches:
- https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+upsert%22+sort%3Aupdated-desc
- https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+%22Attempted+to+serialize+empty+result%22

And the current list of issues:
- https://github.com/prisma/prisma/issues/20561
- https://github.com/prisma/prisma/issues/17982
- https://github.com/prisma/prisma/issues/20527
- https://github.com/prisma/prisma/issues/18285
- https://github.com/prisma/prisma/issues/22562
- https://github.com/prisma/prisma/issues/19868
- https://github.com/prisma/prisma/issues/20042
- https://github.com/prisma/prisma/issues/21612
- https://github.com/prisma/prisma/issues/18393
- https://github.com/prisma/prisma/issues/23359

**Comment by laplab** [comment]
The issue is confirmed on Postgres, SQLite, MySQL and MongoDB.

**Comment by laplab** [comment]
This issue was fixed in [Prisma 5.13.0](https://github.com/prisma/prisma/releases/tag/5.13.0).
