### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by reddevilprasun** [prisma/prisma#22911]
<img width="960" alt="gggit" src="https://github.com/prisma/prisma/assets/130187393/4fd2e063-06f1-4b1f-9647-8fd5c2388ed8">

**Comment by aqrln** [comment]
@reddevilprasun are you using Prisma 5.9.0? Could you confirm if `5.9.1-dev.2` fixes the issue for you?

**Comment by reddevilprasun** [comment]
Yes I use Prisma 5.9.0 and use in my code that
```
import { PrismaClient } from ***@***.***/client";
declare global{
    var prisma: PrismaClient | undefined;
}
export const db = globalThis.prisma || new PrismaClient();
if(process.env.NODE_ENV !== "production")globalThis.prisma = db;


```
the line number 5 show me error
________________________________

**Comment by reddevilprasun** [comment]
Yes I use Prisma 5.9.0 and use in my code that
```
import { PrismaClient } from "@prisma/client";
declare global{
    var prisma: PrismaClient | undefined;
}
export const db = globalThis.prisma || new PrismaClient();
if(process.env.NODE_ENV !== "production")globalThis.prisma = db;


```
this show me error in line number five

**Comment by Jolg42** [comment]
@reddevilprasun Please set this the version for Prisma packages to `"5.9.1-dev.2"` and try again, then let us know if that's fixed.
We will later release an official patch version.

Also, could you share your package.json? I guess you are using Next.js and Next-Auth v5?

**Comment by reddevilprasun** [comment]
Yes I use Next.js and Next-Auth v5
[package.json](https://github.com/prisma/prisma/files/14123559/package.json)

**Comment by reddevilprasun** [comment]
Thank you sooo much error resolved

**Comment by millsp** [comment]
https://github.com/prisma/prisma/releases/tag/5.9.1 is now available with the fix ✨ 

Please create [a new issue](https://github.com/prisma/prisma/issues/new/choose) if you find a bug.
