### ISSUE TITLE
Connection_limit in connection string has no effect

### ISSUE THREAD

**Issue by 86label** [prisma/prisma#2291]
While performance testing our stack, I tried changing different aspects of test environment in order to find bottle necks.

The environment is fully hosted in kubernetes, and consists of 3 parts.
1. Data loading applications
2. Graphql-yoga server with prisma2 (2.0.0-preview024) (will refer to this as "prisma")
3. Postgres cluster

For the purpose of loadtesting, we made a custom app that doesnt actually do any data manipulation, it just generates data and makes http calls to an endpoint (upserts to the graphql api), it's able to push data at high volumes and thread safe, so we can scale the load indefinitely by simply adding more replicas.

For prisma I tried hosting the following:
1 - 10 prisma instances (5 CPU limit, 3Gi mem limit)
With 10 instances and full load from apps prisma cpu usage was around 230m CPU (0.23) and 800mb mem

With 1 instance around 2000m (2) CPU was used and around 800mb mem.

Tried the following connection strings set (for both the singe and the 10 instance scenario):
postgresql://postgres:pw@perftestenv/prisma?schema=public&sslmode=prefer
postgresql://postgres:pw@perftestenv/prisma?schema=public&sslmode=prefer?connection_limit=10
postgresql://postgres:pw@perftestenv/prisma?schema=public&sslmode=prefer?connection_limit=100
But this seemed to have no impact on active sessions to postgres at all. There would be a constant 4-15 number of active sessions
![image](https://user-images.githubusercontent.com/12380024/80189601-36327b00-8613-11ea-9c3f-66debf51bacf.png)

My question is: Is it expected the connection_limit has no effect on the number of connections prisma has to the database?

**Comment by pantharshit00** [comment]
You are not using the property properly in the connection string. You will need to append it using `&` instead of `?` if it is not the first property. It works browser query parameters.

Use the following ones:
```
postgresql://postgres:pw@perftestenv/prisma?schema=public&sslmode=prefer&connection_limit=10
postgresql://postgres:pw@perftestenv/prisma?schema=public&sslmode=prefer&connection_limit=100
```

Also, I tested them out just to make sure and the property work as expected.

**Comment by 86label** [comment]
Thanks @pantharshit00 
I have changed it and doesnt seem to make much of a difference. What is the expected outcome - more active connections, more active+idle connections?

I tried with 10 prismas with limit=15 (left side of image), and 1 prisma with limit=100 (right side of image.
![image](https://user-images.githubusercontent.com/12380024/80207375-4c9a0000-862e-11ea-9fe9-c542a5b7625b.png)

complete string env var for connection:
POSTGRES_URL=postgresql://postgres:<pw>@edh-perftest01/prisma?schema=public&sslmode=prefer&connection_limit=100

**Comment by pimeys** [comment]
The limit is the maximum. If the pool can handle the requests with less connections, it will. You really need to blast it with huge amount of requests per prisma instance to get to the higher limits, and I don't think nodejs is able to do that...

**Comment by 86label** [comment]
Not quite sure what you mean with nodejs not being able to push enough requests.
We have both 20+ real java apps pushing data. Then to make sure the issue is not them being slow, added 10 replicas of a python app that sends upsert requests as fast as it can. Each can generate 1 million requests in 100 seconds (without sending the request).
When we were using prisma1 (same DB, same apps, except schema evolved) there was seemingly no bottleneck in prisma, the bottleneck then was the IOPS supported by the disk of the postgres.

**Comment by pantharshit00** [comment]
@86label The connection_limit is per instance of Prisma Client. In the original comment, you are saying that you spawning 10 prisma instances so each server instance will spawn a connection pool with a max limit of 10 connections.


Can you please tell what exact behaviour you are expecting from the pool here?

**Comment by 86label** [comment]
@pantharshit00 Since the database is not maxed out on CPU, memory or disk IOPS, I would expect that if 1 prisma instance can make use of x connections, 10 should result in 10x active postgres connections, or up until DB exhaustion on CPU/memory/IOPS

In the image above I don't see any change in active sessions, if you look at Active Sessions the left side of that is 10 prismas running in parallel and there are approx 4 active sessions. I then shut down 9 of them and on the right hand side you can see there's still approx 4 active connections.

**Comment by 86label** [comment]
Fx now, we just tried making an app that does random inserts and spawned 10 of them:
![image](https://user-images.githubusercontent.com/12380024/80363165-1b1a7200-8884-11ea-9aa4-b22503f3a77b.png)

And we can now see 10 active connections, and we get around 2700 transactions/sec, where with prisma it is 4 active connections regardless of having 10 or 1 prisma, and around 600 net transactions.

**Comment by pantharshit00** [comment]
@86label I believe this can be closed now, right? This was addressed via meetings as far as I know.

**Comment by matthewmueller** [comment]
Closing. Please re-open if you're still running into this @86label!
