### ISSUE TITLE
PANIC: internal error: entered unreachable code

### ISSUE THREAD

**Issue by ImaginativeWork** [prisma/prisma#22918]
### Bug description

```
Unhandled Runtime Error
Error: Invalid `prisma.$queryRaw()` invocation:

PANIC: internal error: entered unreachable code
This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

Call Stack
<unknown>
https://github.com/prisma/prisma/issues/new
ai.handleRequestError
webpack-internal:///(ssr)/./node_modules/@prisma/client/runtime/library.js (127:7136)
ai.handleAndLogRequestError
webpack-internal:///(ssr)/./node_modules/@prisma/client/runtime/library.js (127:6109)
ai.request
webpack-internal:///(ssr)/./node_modules/@prisma/client/runtime/library.js (127:5817)
async l
webpack-internal:///(ssr)/./node_modules/@prisma/client/runtime/library.js (132:9654)
async getCurrentUser
webpack-internal:///(rsc)/./app/pages/about/page.js (72:19)
async about
webpack-internal:///(rsc)/./app/pages/about/page.js (32:16)
```

### Expected behavior

About Page
[{"":"DOMAIN-NAME\\jsmith"}]
Welcome to [Home](http://localhost:3000/) Page
Home

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}
```

**File: top-level/app/pages/about/page.js**
```javascript
// Add your code using Prisma Client
// 'use client'

// import prisma from '../../../lib/prisma';

// import PageComponent from '../../../components/Page'

// const about = () => {

//   const cu = getCurrentUser();
//   // console.log("cu", cu);

//   return (
//     <>
//       <h1>About Page</h1>
//       <PageComponent title="Home" linkTo={{ path: '/', page: 'Home' }} />
//       { cu }
//     </>
//   )
// }

// export default about

// const getCurrentUser = async () => {

//   let dataSet = await prisma.$queryRaw`EXEC [uspDMTGetCurrentUser]`

//   return dataSet;

// }

import PageComponent from '../../../components/Page'

import prisma from "../../../lib/prisma";

const about = async () => {

  const cu = await getCurrentUser();

  console.log("cu", cu);
  // console.log("cu-string", JSON.stringify(cu));

  // const accessDB = () => {} // btn click won't work on a server component

  return (
    <>
      <h1>About Page</h1>
      <div style={{ backgroundColor:"green"}}>{ JSON.stringify(cu) }</div>
      {/* { JSON.stringify(cu) } */}
      <PageComponent title="Home" linkTo={{ path: '/', page: 'Home' }} />
    </>
  )
}

export default about

const getCurrentUser = async () => {
  // Execute stored procedure
  let dataSet = await prisma.$queryRaw`
  EXEC [storedProcedure]`

  return dataSet;
}
```

**File: top-level/components/Page.js**
```
import Link from 'next/link'

const Page = ({ title, linkTo }) => {

  return (
    <>
      <h1>Welcome to {title} Page</h1>
      <Link href={linkTo.path}>{linkTo.page}</Link>
    </>
  )
}

export default Page
```

### Environment & setup

- OS: Windows 10
- Database: SQL Server
- Node.js version: 20.9.0
- Web Server: IIS version 10

```json
{
  "name": "next-iis-deploy",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "node server.js",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.0.1",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}
```

### Prisma Version

```
$ prisma -v
bash: prisma: command not found
```

**Comment by ImaginativeWork** [comment]
I used this to get started: https://www.fullstackfish.com/posts/2021-09-04-sql-server-to-react-with-prisma/

**Comment by ImaginativeWork** [comment]
Can I add a bounty to my issue? Will that move it up the list?

**Comment by janpio** [comment]
No.

The most productive way to get an answer, is to have a reproducible project that you put on GitHub that anyone can just download and try to see the error you are getting.

(You should also make sure to add the Prisma version you are talking about in your text)

**Comment by aqrln** [comment]
Hello @ImaginativeWork. As @janpio said above, a clonable reproduction as a git repo is always optimal and easiest to deal with, and you can also even not try to minimize it too much if you'd prefer, as long as it's easy enough to run.

But in the absence of that, if you include snippets code as part of your issue report instead that are not runnable anyway, it would be much appreciated if the included snippet was related to your issue; irrelevant React code only makes it harder to understand what the problem is.

From what I understand, the only relevant part is this:
```ts
  let dataSet = await prisma.$queryRaw`
  EXEC [storedProcedure]`
```

I believe we will need the stored procedure in question and the Prisma schema (or, equivalently, the database schema) to reproduce the issue. Any chance you could provide those?

**Comment by ImaginativeWork** [comment]
@aqrln Gigantic thanks for getting back to me on this issue. Would it be ok if I created a separate issue with a GitHub repository that excludes the .env file?

**Comment by aqrln** [comment]
@ImaginativeWork sure! Thanks so much for following up. There's technically no need for a separate issue, you could post the link to the repository here as well, but it's fine too if you prefer! Just post a link to the new issue here and close the old one if you decide that way.

**Comment by ImaginativeWork** [comment]
New Issue with Streamlined GitHub Repo (attached): https://github.com/prisma/prisma/issues/22978
