### ISSUE TITLE
Missing export @prisma/client/generator-build

### ISSUE THREAD

**Issue by frontendphil** [prisma/prisma#22927]
### Bug description

Hey there, I'm not sure whether this is a `nexus-prisma` or `@prisma/client` issue. So, I've decided to post it here first. Please let me know if I should better file an issue over at `nexus-prisma`.

Starting with version `5.9.0`, we're seeing this issue that the `nexus-prisma` generator fails to run. It seems like `generator-build` isn't a thing anymore. 

![CleanShot 2024-02-02 at 08 46 44](https://github.com/prisma/prisma/assets/187786/71657c89-cf4f-44f5-8354-158a6cd7893e)

### How to reproduce

Run `prisma generate` with the `nexus-prisma`.

### Prisma information

![CleanShot 2024-02-02 at 08 50 02](https://github.com/prisma/prisma/assets/187786/3f7ffd05-3488-416d-8619-ec42079111bd)

### Environment & setup

- Database: Postgres
- Node.js version: Latest (21.6.1)

### Prisma Version

Starting from 5.9.0

**Comment by feupeu** [comment]
I'm also running into this issue. Downgrading to `@prisma/client@5.8.0`seems to do the trick for now

**Comment by hbingen** [comment]
Whats the progress on this one? This prevents me from upgrading @prisma/client above 5.8.1

**Comment by Jolg42** [comment]
I opened a PR for `nexus-prisma` at https://github.com/graphql-nexus/nexus-prisma/pull/985 to change the import there.

**Comment by millsp** [comment]
Hey @frontendphil @feupeu @hbingen, thanks to @Kuhave's for providing a fix, it is merged and the fix is now available on our `dev` version via `@prisma/client@dev` and `prisma@dev`. If you want, please install this version to give it a try (and re-generate your client) and let us know how it went. Thanks!

**Comment by Kuhave** [comment]
FYI I've checked with version `5.10.0-dev.48`, and it works on me. :)

**Comment by frontendphil** [comment]
I guess I'll wait for renovate to update the update MR, then :)

**Comment by hbingen** [comment]
@millsp Sorry for the late response.
5.10.0-dev.48 works like a charm
Thank you @kuhave and @millsp
