### ISSUE TITLE
Error messages and DX with SQlite

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#2295]
## Exploration of Developer Experience
- I started the write a SQLite project from scratch using `npx @prisma/cli@2.0.0-alpha.1136 init`
- `tsc --init` and changed `"target": "es5",` to `"target": "es2020",`
- `yarn add @types/node` to add Node types
- I run my first query (and forgot to create the sqlite db) and got my first error message
<img width="798" alt="Screen Shot 2020-04-24 at 14 55 57" src="https://user-images.githubusercontent.com/1328733/80214802-b967c700-863b-11ea-957e-5220477f0cdd.png">

`SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: dev.User")))`
so here the useful part is `no such table: dev.User`, maybe this could be better formatted / clearer?

- `npx @prisma/cli@2.0.0-alpha.1136 migrate save --experimental` and named my migration 

It looks like the highlighting is doing something weird on the comments
<img width="644" alt="Screen Shot 2020-04-24 at 15 21 37" src="https://user-images.githubusercontent.com/1328733/80217033-4fe9b780-863f-11ea-9fc7-bb2c2c5eca82.png">

- `npx @prisma/cli@2.0.0-alpha.1136 migrate up --experimental` 
<img width="627" alt="Screen Shot 2020-04-24 at 15 23 19" src="https://user-images.githubusercontent.com/1328733/80217177-8cb5ae80-863f-11ea-8390-827b5d9e4d7b.png">
It looks like it would be more useful to me to have the real path of the README migration: ie to replace 
`Or read about them in the ./migrations/MIGRATION_ID/README.md`
by 
`./migrations/20200424152036-setup-db/README.md` 

- `ts-node index.ts` it works!

- I changed schema id to `id    Int     @default(autoincrement()) @id` ran generate and code (without migrating)
<img width="916" alt="Screen Shot 2020-04-24 at 15 40 56" src="https://user-images.githubusercontent.com/1328733/80218876-08185f80-8642-11ea-8f29-98e394aea52d.png">
Ok so autoincrement doesn't accept the id (I knew it 🙃)

- Changed schema id to just `id    Int     @id` and it worked! (storage in SQLite is in the TEXT datatype because I didn't migrate)

- Decided it was time to migrate the db (ran save and up)
<img width="856" alt="Screen Shot 2020-04-24 at 15 45 01" src="https://user-images.githubusercontent.com/1328733/80219376-a0aedf80-8642-11ea-856d-1d7acc9554c4.png">
It's warning me that there will be data-loss, I'm ok with that I continue and 💥 I didn't expect this to fail 🙃 

<details>
	<summary>migrate up output</summary>

```
model User {
  id String @default(cuid()) @id
  id Int @id
  email String @unique
  name String?
}

Checking the datasource for potential data loss...


⚠️  There will be data loss:

  • You are about to alter the column `id` on the `User` table, which still contains 6 non-null values. The data in that column will be lost.

✔ Are you sure you want to apply this change? … yes

Database Changes:

Migration          Database actions                                                 Status

20200424154350-id  4 RawSql, 1 DropTable, 1 RenameTable, 1 CreateTable statements.  

You can get the detailed db changes with prisma migrate up --experimental --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md
 ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: datatype mismatch
   0: migration_core::api::ApplyMigration
           with migration_id="20200424154350-id"
             at migration-engine/core/src/api.rs:77)
Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry
```
</details>

- Submitted the error report
```
We successfully received the error report
To help us even more, please create an issue at https://github.com/prisma/prisma/issues/new
mentioning the report id 4275.
```

- Deleted the db (kept migrations folder) and ran migrate up again with --verbose
<img width="654" alt="Screen Shot 2020-04-24 at 15 51 13" src="https://user-images.githubusercontent.com/1328733/80219945-727dcf80-8643-11ea-8f63-516cc66149cd.png">

I can see many `"quaint".` in the SQL, what is that? (I know it's from the Rust engine, but it's not familiar for me, looks like black magic, it doesn't end up in the db just in this output, it's mysterious).

- everything works like expected 

- I decide to revert back to cuid change id to `id    String  @default(cuid()) @id` and intentionally forget to generate but TS catches it
<img width="935" alt="Screen Shot 2020-04-24 at 15 56 48" src="https://user-images.githubusercontent.com/1328733/80220521-41ea6580-8644-11ea-9ae6-2a88489177e9.png">

- I add `// @ts-ignore` to id to see and runtime catches it too
<img width="972" alt="Screen Shot 2020-04-24 at 15 58 23" src="https://user-images.githubusercontent.com/1328733/80220653-73fbc780-8644-11ea-930d-14257ec03bb2.png">

- I generate and get an error from engine / SQLite (I intentionally forgot to migrate my column from int to string and I'm passing a string here so it's expected)
 
<img width="734" alt="Screen Shot 2020-04-24 at 15 59 16" src="https://user-images.githubusercontent.com/1328733/80220836-bb825380-8644-11ea-8af7-4359f5c5e1c9.png">

The error useful part of the error is `QueryError(SqliteFailure(Error { code: TypeMismatch, extended_code: 20 }, Some("datatype mismatch")))` but it doesn't say where it went wrong just one type is wrong, could this be clearer maybe? 

- migrate save & up successfully (accept data-loss again) and everything works again!

## Prisma information

```ts
import shortid from "shortid";
import { PrismaClient } from "@prisma/client";
const client = new PrismaClient();

const id = shortid.generate();
const email = `${shortid.generate()}@hello.world`;

async function main() {
  console.log("Creating user");
  const createUser = await client.user.create({
    data: {
      id,
      name: "Alice",
      email,
    },
  });
  console.log(createUser);
  process.exit();
}

main();
```

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    String  @default(cuid()) @id
  // id    Int     @default(autoincrement()) @id
  //id    Int     @id
  email String  @unique
  name  String?
}
```

## Environment & setup

- OS: Mac OS
- Database: SQLite
- Prisma version: 2.0.0-alpha.1136
- Node.js version: v12.14.1

**Comment by Jolg42** [comment]
I didn't expect the migration from `id    String  @default(cuid()) @id` to `id Int @id` to fail
<img width="856" alt="Screen Shot 2020-04-24 at 15 45 01" src="https://user-images.githubusercontent.com/1328733/80222009-74955d80-8646-11ea-9af4-f5cc4318d186.png">

Also the sqlite error messages are not the best, they are not colorized and it's either kind of hidden or doesn't tell you what went wrong in details.

First one
<img width="808" alt="Screen Shot 2020-04-24 at 15 19 24" src="https://user-images.githubusercontent.com/1328733/80221817-1d8f8880-8646-11ea-8b10-11a6fb087ca7.png">

Second one
<img width="734" alt="Screen Shot 2020-04-24 at 15 59 16" src="https://user-images.githubusercontent.com/1328733/80221846-27b18700-8646-11ea-8d59-e967b213d367.png">

**Comment by Jolg42** [comment]
Also the sqlite error messages are not the best, they are not colorized and it's either kind of hidden or doesn't tell you what went wrong in details.

First one
<img width="808" alt="Screen Shot 2020-04-24 at 15 19 24" src="https://user-images.githubusercontent.com/1328733/80221817-1d8f8880-8646-11ea-8b10-11a6fb087ca7.png">

Second one
<img width="734" alt="Screen Shot 2020-04-24 at 15 59 16" src="https://user-images.githubusercontent.com/1328733/80221846-27b18700-8646-11ea-8d59-e967b213d367.png">

**Comment by Jolg42** [comment]
It looks like it would be more useful to me to have the real path of the README migration: ie to replace the CLI output
`Or read about them in the ./migrations/MIGRATION_ID/README.md`
by 
`./migrations/20200424152036-setup-db/README.md`

**Comment by Jolg42** [comment]
And It looks like the highlighting is doing something weird on the comments 
<img width="513" alt="Screen Shot 2020-04-24 at 16 27 56" src="https://user-images.githubusercontent.com/1328733/80223433-9263c200-8648-11ea-9c2a-13f182571e97.png">

**Comment by pantharshit00** [comment]
Issue regarding having quaint text in the sql migration is tracked via https://github.com/prisma/migrate/issues/354

Opened regarding the migration error: https://github.com/prisma/migrate/issues/430

Other small details are still tracked by this issue like error messages. I guess you will be implementing them ;)

**Comment by Jolg42** [comment]
Thank you @pantharshit00 :)
