### ISSUE TITLE
Breaking changes - `prisma upgrade`

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#2296]
This issue is about the question, how we can best navigate breaking changes in Prisma.
It is inevitable that breaking changes will come if we want to evolve the product.
However, at the same time, we want every Prisma user to have the best possible experience when upgrading from one version to another.

One possible way to make the upgrade experience as seamless as possible would be the introduction of a `prisma upgrade` command.

In the following, I'll discuss how such a `prisma upgrade` command could work in various scenarios.

## Responsibilities of `prisma upgrade`
Possible responsibilities of `prisma upgrade` include:
1. `npm install @prisma/client@latest @prisma/cli@latest`
2. Check if the latest version introduced any breaking changes. If yes, guide the user through these changes

## Scenario 1: Breaking Prisma Schema change

In version [2.0.0-beta.1](https://github.com/prisma/prisma/releases/tag/2.0.0-beta.1) we introduced a breaking change in the schema, which now requires you to provide the concrete fields used to implement a relation on database level.

We asked the user to manually fix their `schema.prisma` file, which caused friction. Instead, the `prisma upgrade` command could have a look into the underlying database and determine that way, which field should be used for the relation, while preserving the current `schema.prisma` file as much as possible.

## Scenario 2: Breaking change in Prisma Client API
Let's say we introduce a breaking change in the Prisma Client API.
A common way to solve such a situation in an automated fashion is using https://github.com/facebook/jscodeshift.
`prisma generate` could already ship the necessary transforms and run `npx codeshift --transforms` to transform the users code.

## Scenario 3: Breaking change in Prisma migrate
Prisma migrate has certain filesystem artifacts, e.g. a so-called `steps.json`.
If we would introduced new field in the `steps.json`, `prisma upgrade` could update the `steps.json`.

These are just a few examples to show-case, how `prisma upgrade` could look like.

You probably have many ideas, how to make breaking changes as seamless as possible, so let's exchange some thoughts!

**Comment by thebiglabasky** [comment]
Hey,

I like the idea! However I wonder if this wouldn't add a bit of product surface and friction in releases at this point. I would likely consider this further down the road.

In the meantime, I would very much love to have two separate packages or versions available
 1. Experimental, where we merge all changes, and document breaking changes we may introduce
 2. Stable, where we only merge non-breaking changes and non-experimental updates to the product

This would involve two different release cycles:
 1. The experimental cycle, fast, where people can try out the all of upcoming ideas
 2. The stable, slower but reliable, for production running projects

Over time, we would follow semver to update the major version number whenever we introduce breaking changes from the experimental version, which would be in any case an upgrade activity for people going beyond Prisma alone (e.g. through Redwood or Blitz, etc.).
At that point, that would likely highlight further (or not) the need for automating parts of these upgrades.

Does that make sense?

**Comment by timsuchanek** [comment]
I agree @thebiglabasky, that we can also go with a simpler solution.
As long as don't have any breaking change, this is not relevant anyway.
I'll close this, as we don't need this solution for now.
