### ISSUE TITLE
Query engine binary not found in NextJS with custom output

### ISSUE THREAD

**Issue by emckay** [prisma/prisma#2299]
## Bug description

When specifying a custom output in prisma.schema

```
generator client {
  provider      = "prisma-client-js"
  output        = "generated/client"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}
```

Prisma client is unable to find the query engine binary when used in a NextJS server-side function. It is looking for the binary in the root of my filesystem (!) instead of in the generated prisma client directory.

```
Invalid `prisma.event.findMany()` invocation in
/home/.../.next/server/static/development/pages/index.js:317:45

  313 };
  314 
  315 const getStaticProps = async context => {
  316   const prisma = new _prisma_generated_client__WEBPACK_IMPORTED_MODULE_3__["PrismaClient"]();
→ 317   const featuredEvents = await prisma.event.findMany(Query engine binary for current platform "debian-openssl-1.1.x" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/query-engine-debian-openssl-1.1.x")

Files in /:

  bin
  boot
  cdrom
  dev
  etc
  home
  ...

You already added the platforms "native", "debian-openssl-1.1.x" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.
```

If I remove the custom output directory and import from `@prisma/client`, everything works as expected.

I suspect this is due to webpack resolving `__dirname` to `/` (see: https://github.com/webpack/webpack/issues/1599)

## How to reproduce

I can probably put together a full repro if needed, but at a high level:

1. Create new NextJS project
2. Add prisma with custom output directory
3. Write prisma query in `getStaticProps` or `getServerSideProps` after importing `PrismaClient` from custom output directory
4. Note error when page renders
5. Remove custom output directory and run `prisma generate`
6. Change import to `import {PrismaClient} from '@prisma/client`
7. Note there is no longer an error

## Expected behavior

Expect to be able to import from my custom output directory

## Prisma information

```
generator client {
  provider      = "prisma-client-js"
  output        = "generated/client"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}
```

## Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.3
- Node.js version: v12.16.2

**Comment by pantharshit00** [comment]
This is a known issue. See https://github.com/prisma/prisma/issues/2195

Explanation for this can be found here: https://github.com/prisma/prisma/issues/2195#issuecomment-615584757

As, we have labelled that one as a question I am going to keep this open as the other issue is kinda specific to blitz framework.

**Comment by pantharshit00** [comment]
Closing as outdated. This was resolved.
