### ISSUE TITLE
Forbid properties in types that can cause runtime failures

### ISSUE THREAD

**Issue by chriskuech** [prisma/prisma#23017]
## Problem

Prisma Client's killer feature is the quality of its types. However, while the types can prevent runtime failures due to omission of a property, Prisma Client still fails at runtime if you specify an additional property. Prisma Client types should be robust enough to prevent runtime failures related to object structure. 

## Suggested solution

Use this utility type around prisma client arg types to ensure that only supported properties can be specified.  

```ts
type DisallowExtraProperties<T> = T & {
  [P in keyof any]: P extends keyof T ? T[P] : never;
};
```

## Alternatives

Ignore additional properties instead of erroring at runtime. 

## Additional context

N/a

**Comment by SevInf** [comment]
Do you have a specific example? We strive to match runtime and compile-time validation as closely as possible, however, we but we might miss some things on accident and deliberately  omit compile-time checks in some other cases (for performance or diagnostic quality reasons). Without knowing what cases do you mean specifically, we don't know in which category the issue falls.

**Comment by chriskuech** [comment]
Sorry im on vacation for a few weeks so cant make a repro until then (let me know if still desired). 

However, this isnt a bug with prisma client types. TypeScript structural typing inherently doesnt block you from adding additional properties to a type--its usually a nice feature of the language. So this is a feature request to make the types go beyond normal idiomatic typing. 

To repro, you should be able to add bad properties to any value of a findMany input (select, where, etc. objects)

**Comment by SevInf** [comment]
>To repro, you should be able to add bad properties to any value of a findMany input (select, where, etc. objects)

This is simply not true on a basic reproduction:
<img width="417" alt="image" src="https://github.com/prisma/prisma/assets/603056/71756dd8-5d22-4554-8f54-9791c504bd03">

Looking forward for a proper reproduction from your side.

**Comment by Jolg42** [comment]
@chriskuech please take a look at my colleague's comment above, without an answer we would close this issue later.

**Comment by SevInf** [comment]
Hey @chriskuech ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏

**Comment by chriskuech** [comment]
Sorry for the delay and noise here. I believe the only times I've hit this issue is due to typescript--spread/indexing silently adding invalid properties without validation or the typescript type being wrong.
