### ISSUE TITLE
Introspection does not generate correct relation

### ISSUE THREAD

**Issue by joshuaavalon** [prisma/prisma#2301]
## Bug description

```
npx prisma introspect
```

Does not produce relation in [documentation](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#many-to-many-relations).

## How to reproduce

1. Initialize database
```sql
CREATE TABLE "Category" (
    id SERIAL PRIMARY KEY
);
CREATE UNIQUE INDEX "Category_pkey" ON "Category"(id int4_ops);
CREATE TABLE "Post" (
    id SERIAL PRIMARY KEY
);
CREATE UNIQUE INDEX "Post_pkey" ON "Post"(id int4_ops);
CREATE TABLE "_CategoryToPost" (
    id SERIAL PRIMARY KEY,
    "A" integer NOT NULL REFERENCES "Category"(id) ,
    "B" integer NOT NULL REFERENCES "Post"(id)
);
CREATE INDEX "_CategoryToPost_B_index" ON "_CategoryToPost"("B" int4_ops);
```

2. Run `npx prisma introspect`

## Expected behavior

Result similar to documentation.

```prisma
model Post {
  id         Int        @id @default(autoincrement())
  categories Category[] @relation(references: [id])
}
model Category {
  id    Int    @id @default(autoincrement())
  posts Post[] @relation(references: [id])
}
```

## Actual behavior

```prisma
model Category {
  id             Int              @default(autoincrement()) @id
  CategoryToPost CategoryToPost[] @relation("CategoryTo_CategoryToPost")
}

model Post {
  id             Int              @default(autoincrement()) @id
  CategoryToPost CategoryToPost[] @relation("PostTo_CategoryToPost")
}

model CategoryToPost {
  A        Int
  B        Int
  id       Int      @default(autoincrement()) @id
  Category Category @relation("CategoryTo_CategoryToPost", fields: [A], references: [id])
  Post     Post     @relation("PostTo_CategoryToPost", fields: [B], references: [id])

  @@index([B], name: "_CategoryToPost_B_index")
  @@map("_CategoryToPost")
}
```
## Environment & setup

- OS: Windows
- Database: PostgreSQL
- Prisma version: @prisma/cli: 2.0.0-beta.3
- Node.js version: v12.13.0

**Comment by TLadd** [comment]
If you look at https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#conventions-for-relation-tables-in-implicit-m-n-relations, one of the requirements for prisma to pick up the implicit many to many relationship is `A unique index defined on both foreign key columns`. What you've posted doesn't have that and instead has an id column in `_CategoryToPost`. It should work if you remove the id column and add the unique index.

**Comment by joshuaavalon** [comment]
@TLadd I get this warning instead

```
*** WARNING ***

These models do not have a unique identifier or id and are therefore commented out.
- "CategoryToPost"
```

**Comment by janpio** [comment]
> It should work if you remove the id column and add the unique index.

You also need to "add the unique index" as in the documentation, then the join table should be converted into an implicit relation between these two tables.

**Comment by joshuaavalon** [comment]
Ok, I finally make it works. Also, is UNIQUE constraint not design to work?

```sql
UNIQUE("A", "B") /* Not work */
CREATE UNIQUE INDEX "_CategoryToPost_AB_unique" ON "_CategoryToPost"("A" int4_ops,"B" int4_ops) /* Work */
```
