### ISSUE TITLE
Prisma doesn't know which engines to download for the Linux distro "guttaos"

### ISSUE THREAD

**Issue by RobertoModeneziNeto** [prisma/prisma#23031]
### Bug description

Prisma doesn't know which engines to download for the Linux distro "guttaos". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```"
^5.9.1
"
```

**Comment by Jolg42** [comment]
Hi @RobertoModeneziNeto 

I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
