### ISSUE TITLE
Ability to disable hooks for an environment

### ISSUE THREAD

**Issue by FredyC** [prisma/prisma#2306]
# Feature Request

**What feature are you missing?**

The barely documented `hooks` in `prisma.yml` are always executed despite the environment. For example, When deploying to a local server, I get my graphql schema and bindings updated. However, I want to avoid running the same thing when deploying to other environments. It's just unnecessary holdup even though it correctly identifies there are no changes.

**How could this feature look like in detail? Tradeoffs?**

It would probably require an expanded structure than the current one so the flag to disable can be added, eg. based on environment variable can be specified.

However, I think that these hooks shouldn't be in `prisma.yml` at all. It feels like an ad-hoc solution as there are no other hooks at the moment. Instead of removing the automatic execution of this generation process, it would make much more sense to have a flat boolean variable for disabling it if anyone needs it. I am not sure why this was removed in the first place, perhaps to increase customization level, but I think both solutions can live peacefully together and for anyone who doesn't need customize it, there won't be anything extra to be done.

**Comment by FredyC** [comment]
One more reason to actually handle this differently. If the service is secured, it's necessary to generate token and use it within `.graphqlconfig`. Attempting to generate schema from a different environment fails because token is wrong.

```yml
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: src/database/prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
      endpoints:
        default:
          url: "ENDPOINT"
          headers:
            Authorization: "TOKEN"
```

**Comment by marktani** [comment]
> The barely documented hooks in prisma.yml

Thanks for your feedback. The [upgrade guide to 1.7](https://www.prisma.io/docs/1.7/reference/upgrade-guides/upgrading-prisma/upgrade-to-1.7-iquaecuj6b) includes explanations and examples for post deployment hooks. We'll soon add general documentation about post deployment hooks, check [this](https://github.com/graphcool/prisma/issues/2311).

> are always executed despite the environment

Yup, that's right! we should investigate how to improve this feature to allow for conditional or environment specific hooks.

> However, I think that these hooks shouldn't be in prisma.yml at all. It feels like an ad-hoc solution as there are no other hooks at the moment.

Where do you suggest these hooks to live instead?

> Instead of removing the automatic execution of this generation process [...] I am not sure why this was removed in the first place

The automatic behaviour caused a lot of confusion and questions. The new way of handling post deployment hooks is way more open and allows for more control and flexibility, as well as [visibility](#1927).

---

> If the service is secured, it's necessary to generate token and use it within .graphqlconfig.

Please read https://github.com/graphcool/prisma/issues/2268.

**Comment by FredyC** [comment]
> If the service is secured, it's necessary to generate token and use it within .graphqlconfig.
> 
> Please read #2268.

That's not what I mean. Imagine I have 3 different environments where I am deploying: DEV, STAGE, PROD. Now I would leave DEV unsecured, no harm there. Then I would have generated token for STAGE, place it in `.graphqlconfig` and it works. Later I want to deploy to PROD and suddenly I am getting error that token is invalid obviously. I certainly do not want to. This could be obviously solved if you can have hooks per environment, but right now it's broken approach.

I tried using env variables in the `.graphqlconfig`, but for some reason, those are not available when deploy is finished and it just spills warning and dies.

There is also another problem with this approach. On a first time deployment, you cannot even generate token yet (server does not have the secret) so you are getting errors right at the start which are a good way to scare of beginners.

---

Honestly, how many people needs to adjust this process? What I was suggesting above is to keep both ways where by default it will generate schema/bindings as it was before, but you can disable this with boolean flag in `prisma.yml` and use hooks if you like. Please, don't make things unnecessarily harder for majority of people.

**Comment by marktani** [comment]
1) 

> That's not what I mean.

Please read the entirety of #2268, in particular [1. from this comment](https://github.com/graphcool/prisma/issues/2268#issuecomment-384539740). As far as I can see, the approach described there solves your situation in an elegant way.

2) 

> Honestly, how many people needs to adjust this process?

Everyone that downloaded the schema before, is upgrading to `1.7` and still wants to download the schema needs to add this to their `prisma.yml`:

```yml
hooks:
  post-deploy:
    - graphql get-schema --project db
    - graphql prepare
```

This is also mentioned in [the upgrade guide](https://www.prisma.io/docs/1.7/reference/upgrade-guides/upgrading-prisma/upgrade-to-1.7-iquaecuj6b).

> Please, don't make things unnecessarily harder for majority and saying it's for greater good.

I hear you, but I genuinely believe that adding more visibility into the previously automatic & magic schema generation workflows is super beneficial. Whether or not you agree with this, what changes do you suggest?

---

It would be great if you could add a separate feature request or discussion if you have further points to talk about, as this issue is for the feature request to disable hooks for specific environments.

**Comment by FredyC** [comment]
> Please read the entirety of #2268, in particular 1. from this comment. As far as I can see, the approach described there solves your situation in an elegant way.

I am sorry, but I don't see anything _elegant_ there if you mean this. 

```yml
hooks:
  post-deploy:
    - TOKEN=$(prisma token)
    - yarn graphql get-schema --header "{\"Authorization\": \"Bearer $TOKEN\"}"
```

Yea sure, I can put token from env variable there, but honestly, this is just weird piece of boilerplate that everyone needs to copy to have a basic functionality available. I hope it will at least be available in a newly initialized project.

What might make things more clean is to have those commands in npm scripts instead of abusing "config file". In my opinion it's way easier to read and people are more used to it. This could get even better if `graphql-cli` would just accept token argument, but that's a different story :)

```json
"scripts": {
  "get-schema": "graphql get-schema --header "{\"Authorization\": \"Bearer $TOKEN\"}",
  "deploy": "prisma deploy",
  "postdeploy": "if-env ENV=dev && yarn get-schema"
}
```

> It would be great if you could add a separate feature request or discussion if you have further points to talk about, as this issue is for the feature request to disable hooks for specific environments.

It feels like these are overlapping concerns so I don't see much of the benefit of splitting discussion.

**Comment by marktani** [comment]
> I am sorry, but I don't see anything elegant there if you mean this:
> ```yml
> hooks:
>  post-deploy:
>    - TOKEN=$(prisma token)
>   - yarn graphql get-schema --header "{\"Authorization\": \"Bearer $TOKEN\"}"
> ```

No, that's not what I mean. I  meant [this comment](https://github.com/graphcool/prisma/issues/2268#issuecomment-384539740). I'll quote the relevant part here:

> 1. Use the `.graphqlconfig.yml`
> If you have defined your prisma endpoint in the `.graphqlconfig.yml`, just providing `--project` should be enough and the `graphql-config-extension-prisma` should provide the auth headers. If that's not the case, it's a bug.

---

> This could get even better if graphql-cli would just accept token argument, but that's a different story :)

The same comment also reveals this approach: 


> 2. Provide the headers as params as you tried, but with the `Param=Value` syntax
> ```bash
> graphql get-schema --project db --header Authorization="Bearer $TOKEN"
> ```

---

> It feels like these are overlapping concerns so I don't see much of the benefit of splitting discussion.

Ok 🙂

**Comment by FredyC** [comment]
Btw, have you noticed that with npm scripts I have essentially solved this issue of choosing environment? I suppose it would work same way in the hooks, but probably more verbose. The [if-env](https://www.npmjs.com/package/if-env) is a real npm package :)

**Comment by marktani** [comment]
No, I haven't caught that actually! Thanks for sharing, that's a great approach 👌

**Comment by JensMadsen** [comment]
would be very nice with a boolean in `prisma deploy` determing whether to run post hooks or not. For our use case we need to start a prisma container for our tests and builds. In many cases we do not need to generate the client and would like to disable the clinet generation in order to speed up things :-)

**Comment by divyenduz** [comment]
This can be achieved by implementing a `--hook`/`--no-hook` flag (defaulting to --hook i.e. true). 

After implementation of this spec, the following behavior would be observed:-

1. `prisma deploy` would run hooks. 
1. `prisma deploy --no-hook` will deploy and not run hooks.
1. `prisma deploy --hook` (same as 1) will run hooks.
