### ISSUE TITLE
After adding a prisma client extension it is not possible anymore to define event based logging handlers

### ISSUE THREAD

**Issue by avan2s** [prisma/prisma#23108]
### Bug description

It is not possible (since version >=5.0.0) to define a handler for [event based logging](https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/logging#event-based-logging) after adding an extension to the prisma client. The `$on` method is missing and was working in the 4 major release even with extensions.
`prismaClientWithSomeExtension.$on("query", (event) => queryEvents.push(event));`

### How to reproduce

1. Create a prisma client of your choice and instantiate it using log events (like in the docs):
```typescript 
const prisma = new PrismaClient({
  log: [
    {
      emit: 'event',
      level: 'query',
    },
    {
      emit: 'stdout',
      level: 'error',
    },
    {
      emit: 'stdout',
      level: 'info',
    },
    {
      emit: 'stdout',
      level: 'warn',
    },
  ],
}).$extends({}); // I just add an empty extension, the issue will be reproducable with any extension

// define the event handler
prisma.$on("query", (event) => console.log(event)); // ERROR $on!

prisma.$on('query', (e) => {
  console.log('Query: ' + e.query)
  console.log('Params: ' + e.params)
  console.log('Duration: ' + e.duration + 'ms')
});
```

3. The error is: `Property '$on' does not exist on type 'DynamicClientExtensionThis<TypeMap<InternalArgs & { result: {}; model: {}; query: {}; client: { $begin: () => (txOptions?: TransactionOptions | undefined) => Promise<FlatTransactionClient>; }; }>, TypeMapCb, { ...; }>'.ts(2339)` 

### Expected behavior

The $on method can still be used in order to handle logging events, after adding an extension. This is especially useful when writing integration tests in order to asserting queries, that are running against the database.

### Prisma information

You can use any schema, i use:
```prisma
generator client {
  provider        = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model AppUser {
  id        BigInt @id @default(autoincrement())
  firstname String
  lastname  String
  email     String
  posts     Post[]

  @@map("app_user")
}

model Post {
  id             BigInt       @id @default(autoincrement())
  comment        String
  userId         BigInt
  user           AppUser      @relation(fields: [userId], references: [id])

  @@map("post")
}
```

Tyoescript code reproducing this issue:

```typescript
const prisma = new PrismaClient({
  log: [
    {
      emit: 'event',
      level: 'query',
    },
    {
      emit: 'stdout',
      level: 'error',
    },
    {
      emit: 'stdout',
      level: 'info',
    },
    {
      emit: 'stdout',
      level: 'warn',
    },
  ],
}).$extends({}); // I just add an empty extension, the issue will be reproducable with any extension

// define the event handler
prisma.$on("query", (event) => console.log(event)); // ERROR $on!

prisma.$on('query', (e) => {
  console.log('Query: ' + e.query)
  console.log('Params: ' + e.params)
  console.log('Duration: ' + e.duration + 'ms')
});
```

### Environment & setup

- OS: macOS, Debian
- Database: PostgreSQL
- Node.js version: v20.10.0

### Prisma Version

All versions >=5
```
^5.0.0
```

**Comment by jkomyno** [comment]
Hi @avan2s, the behavior you're describing is working as designed (see [Docs](https://www.prisma.io/docs/orm/prisma-client/client-extensions#usage-of-on-and-use-with-extended-clients)).

Can you please share with us whether you had found the linked docs page before, and whether the provided explanation is easy to follow? We're happy to hear feedback to potentially make Prisma easier to use :)

**Comment by avan2s** [comment]
Hi @jkomyno ,

thanks for your answer and the doc link. This helps. It is easy to follow. Maybe prisma could add the `$on` example, not only the `$use one. But just to be complete :) I was looking in the event based logging [section](https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/logging#event-based-logging) . If there would be a hint, that $on and $use should be handled before extending a prisma client, this would be awesome. I was there several month ago, when client extensions were a previewFeature. Maybe this redesign was happening, when it goes into the release.

Thanks again!
