### ISSUE TITLE
no encoding of .env URLs 

### ISSUE THREAD

**Issue by JamesKyburz** [prisma/prisma#23125]
### Bug description

prisma handles it's own vendored version of [dotenv-expand](https://github.com/motdotla/dotenv-expand), however URL encoding is not taken care of.

Given the following .env

```sh
DB_USER="user"
DB_PASSWORD="@ !+?//"
DB_PORT="8080"
DB_DATABASE="default"
DB_SCHEMA="schema"
DB_HOST="localhost"
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?schema=${DB_SCHEMA}"
```

Would mean that the DATABASE_URL is not invalid

invalid: `postgresql://user:@ !+?//@localhost:8080/default?schema=schema`

correctly encoded: `postgresql://user:%40%20!+%3F%2F%2F@localhost:8080/default?schema=schema`

### How to reproduce

Have both DB_PASSWORD containing characters that need url encoding.

DB_PASSWORD="@ !+?//"
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?schema=${DB_SCHEMA}"

### Expected behavior

For the URLs to be correctly encoded, or for there to be no variable expansion support.

### Prisma information

n/a

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.11.0

### Prisma Version

```
prisma@5.9.1
```

**Comment by janpio** [comment]
Prisma ORM expects you to provide the encoded parts for the connection string. Variable expansion is just about combining different strings to another string - additional logic like encoding certain parts would overload that behavior.

Is that something against some standard or common way of doings things in your opinion?

**Comment by JamesKyburz** [comment]
Ok thanks. The two scenarios where it becomes an issue for us are the following.

* values come from a some secret store where they aren't url encoded.
* values are used as both part of a URL and a non URL.

Yes one could have multiple keys containing both url encoded, and non url encoded; but this just becomes over complicated.

**Comment by janpio** [comment]
After talking about this internally, I think we can close this issue as we will not consider changing the behavior here.

- Prisma schema's `env()` is built to get a value of an environment variable, and then directly use it in Prisma Client or other Prisma tools. It should behave equivalently to writing a value as a string into the schema file.
- Similarly `.env` tooling is expected to just read the values as they are in that file and provide them as environment variables. Variable expansion is a defined extension of that, which allows to concatenate strings and other environment variables together.
- If your values in `.env`, or other environment variables, are not in a format that the can be used directly as a connection string, that is a problem we understand but can not do anything about with the two features above as they are currently implemented.

If you have a use case where it is expected (and not just a problem in that system) that an environment variable is a state that is not usable for Prisma, please open a new issue and describe that a bit. We can then treat _that_ as a feature request to fix that problem _somehow_. Encoding environment variable values by default will not be the solution.
