### ISSUE TITLE
Emacs integration

### ISSUE THREAD

**Issue by OliverEvans96** [prisma/prisma#2312]
As instructed by https://www.prisma.io/docs/reference/more/editor-setup, I'm requesting emacs support for Prisma2 :)

**Comment by pantharshit00** [comment]
@pimeys Language server was just released: https://github.com/prisma/vscode/issues/112. Just fyi :)

**Comment by pimeys** [comment]
Then this is just a matter of time...

**Comment by nimms** [comment]
just adding a +1 to this.  Syntax highlighting and LSP integration would be amazing.

**Comment by AYM1607** [comment]
Would be great to see this!

**Comment by pimeys** [comment]
Yep.

**Comment by pimeys** [comment]
So, I'm spending a bit of time from the release day to make something that might be useful for me as an emacs user. I'm pushing this to a repo later, so all of you using emacs can experience with it, make changes, make nice PRs (please, I don't have that much time to spend on this) and so on. My aim for today is two things I'm really needing every day when working here: basic syntax highlight and automatic indentation after `{`. LSP I'll leave as an exercise for people who really think they need that, I probably don't have time for that.

**Comment by pimeys** [comment]
So, this should cover all the basics:

https://github.com/pimeys/emacs-prisma-mode

Have fun!

**Comment by jplindstrom** [comment]
Awesome, will try this out! :+1: 

Do you think you could add it to https://melpa.org/ please so it's convenient to install?

**Comment by jplindstrom** [comment]
You could mention it here as well: https://www.prisma.io/docs/concepts/more/editor-setup 

I only found this after searching in the issues.

**Comment by janpio** [comment]
It is now mentioned in https://www.prisma.io/docs/guides/development-environment/editor-setup

**Comment by pimeys** [comment]
LSP and syntax highlighting works for me very well in emacs for some time already. No need to keep this issue open.
