### ISSUE TITLE
`prisma list` should show all services (connected servers + cloud)

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#2313]
Right now `prisma list` just lists all cloud services but should also list all services from the following sources:

- Server configured via `endpoint` in `prisma.yml` (might require `PRISMA_MANAGEMENT_API_SECRET` env var)
- All servers configured in `~/.prisma/config.yml`
- Prisma Cloud

## Steps

- [ ] Please propose a CLI design for the list output before implementing @timsuchanek 
- [ ] Implement new output

**Comment by timsuchanek** [comment]
Closing this in favor of #2764
