### ISSUE TITLE
Prisma introspect: extra field for self-relations

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma#2313]
## Bug description

`prisma introspect` adds an extra field for self relations

## How to reproduce

1. Create a schema as follows and create migrations with `prisma migrate`

```prisma
model User {
  id        Int      @default(autoincrement()) @id
  name      String
  parent    User?    @relation("UserToUser", fields: [parent_id], references: [id])
  parent_id Int?     @unique
  createdAt DateTime @default(now())
}
```

2. Now drop all tables and create the same table via SQL generated by `prisma migrate up --experimental` (taken from the migrations `README.md`)

```sql
create table "User" (
  createdAt timestamp default now(),
  "id" serial primary key,
  "name" varchar not null,
  parent_id int unique,
  foreign key (parent_id) references "User"("id") on delete set null on update cascade
)
```

3. Run `prisma introspect`

The model gives an extra field as below

```prisma
model User {
  createdat  DateTime? @default(now())
  id         Int       @default(autoincrement()) @id
  name       String
  parent_id  Int?      @unique
  User       User?     @relation("UserToUser_parent_id", fields: [parent_id], references: [id])
  other_User User?     @relation("UserToUser_parent_id")
}
```

## Expected behavior

The model should remain the same and not generate an extra field

## Environment & setup

- OS: Debian
- Database: PostgreSQL
- Prisma version: `2.0.0-beta.2`
- Node.js version: `10.20.0`

**Comment by pantharshit00** [comment]
I can confirm this. Step 2 of the reproduction is unnecessary here, you can skip it as `prisma introspect` doesn't care if the database was bootstrapped by `prisma migrate`.

**Comment by do4gr** [comment]
This is intentional. We require both sides of every relation to be present. If Prisma Format would run on the initial schema (through the VS Code plugin for example) it should add the second field.
