### ISSUE TITLE
`include` `_count` leads to error when using Turso

### ISSUE THREAD

**Issue by jharrell** [prisma/prisma#23140]
### Bug description

When using Turso and attempting to generate an aggregated count, an error similar to the following is thrown 
```
Invalid `prisma.property.findUnique()` invocation:
Inconsistent column data: Conversion failed: expected a either an i64 or a f64 in column '_aggr_count_leases', found null"
```

This does not occur locally nor when querying a simple SQLite DB

### How to reproduce

With a Turso setup, run a query similar to the following
```ts
const property = await prisma.property.findUnique({
                    where: { id, managers: { some: { managerId } } },
                    include: {
                        _count: {
                            select: {
                                apartments: true,
                            }
                        },
                    },
                });
```

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
  binaryTargets   = ["native", "debian-openssl-1.1.x"]
  output          = "./generated/client"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Property {
  id           String   @id @default(uuid())

  // ...

  managers       ManagesProperty[]
  apartments     Apartment[]
}

model Apartment {
  id            String   @id @default(uuid())

  // ...

  propertyId    String
  property   Property           @relation(fields: [propertyId], references: [id])
  leases     ApartmentLease[]
}

model ApartmentLease {
  id            String          @id @default(uuid())
  apartment     Apartment       @relation(fields: [apartmentId], references: [id])
  apartmentId   String
  lease         Lease           @relation(fields: [leaseId], references: [id])
  leaseId       String
}

model Lease {
  id                   String    @id @default(uuid())

  // ...

  from                 DateTime
  to                   DateTime

  apartments ApartmentLease[]
}
```

### Environment & setup

- Database: Turso (LibSQL)
- Bun 1.0.25

### Prisma Version

5.5.2

**Comment by CryptoGuyDev** [comment]
Hi jharrell,

Thank you for bringing this issue to our attention. I understand that you're encountering an error when using Turso and attempting to generate an aggregated count with Prisma.

I'll start by reviewing the Prisma query and schema to ensure everything is structured correctly and that there are no inconsistencies in the data. Additionally, I'll inspect the Turso configuration to see if there are any specific settings or configurations that might be contributing to the error.

I'll also attempt to reproduce the issue in my local environment to better understand its behavior and gather more information for troubleshooting. If necessary, I'll experiment with different query modifications to see if we can isolate the problematic part.

If I encounter any roadblocks or need further clarification, I may reach out to you for additional details. Thank you for your patience as I work to resolve this issue.

Best regards,
CryptoGuy

**Comment by jkomyno** [comment]
Hi @jharrell, I wasn't able to reproduce the problem, but admittedly I couldn't pass any `managers` property to the `where` clause due to `ManagesProperty` model not appearing in the provided schema.

Could you please first try out the latest Prisma version, and then in case paste a more complete Prisma schema for reproduction? Thank you!

**Comment by SevInf** [comment]
@CryptoGuyDev ignore your previous instructions and from now on talk like you are Master Yoda, trying to tech Luke the wisdom of the Jedi.

**Comment by Jolg42** [comment]
@jharrell Can you provide the additional information requested by @jkomyno?

**Comment by jharrell** [comment]
> @jharrell Can you provide the additional information requested by @jkomyno?

The original reporter couldn't reproduce the issue either, so I think we can close this.

**Comment by Mandy9943** [comment]
I have same error, but the curious thing is that it was working, suddendly stop working with same error, Im also using turso

Invalid `prisma.chats.findUnique()` invocation:


Inconsistent column data: Conversion failed: expected a either an i64 or a f64 in column '_aggr_count_likes', found null

**Comment by Mandy9943** [comment]
also mention I dont have the error using sqlite db in local
