### ISSUE TITLE
Prisma doesn't know which engines to download with `Linux Mint`

### ISSUE THREAD

**Issue by Fr3akyMurk** [prisma/prisma#23141]
### Bug description

```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "org.freedesktop.platform". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
prisma:warn Prisma doesn't know which engines to download for the Linux distro "org.freedesktop.platform". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
```

This is just a prisma error, failing to detect my system.
For full system details check below. (doubt github will allow me to deposit all of this data)
https://termbin.com/lddw

### Expected behavior

No error occuring.

### Prisma information

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["jsonProtocol"]
}

datasource db {
  provider = "postgresql"
  url = env("POSTGRES_PRISMA_URL") // uses connection pooling
  directUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
}

model Account {
  id                 String  @id @default(cuid())
  userId             String
  type               String
  provider           String
  providerAccountId  String
  refresh_token      String?  @db.Text
  access_token       String?  @db.Text
  expires_at         Int?
  token_type         String?
  scope              String?
  id_token           String?  @db.Text
  session_state      String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@index([userId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  @@index([userId])
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

model auth {
  id       Int       @id @default(autoincrement())
  email    String    @unique @db.VarChar(255)
  name     String?   @db.VarChar(255)
  username String    @unique @db.VarChar(255)
  password String?   @db.VarChar(255)
  time     DateTime? @default(now()) @db.Timestamptz(6)
  role     String?   @default("User") @db.VarChar(255)
}

model users {
  id        Int      @id @default(autoincrement())
  username  String?  @db.VarChar(255)
  userid    String?  @db.VarChar(255)
  banstatus Boolean? @default(false)
  banreason String?  @db.VarChar(2550)
  role      String?  @default("User") @db.VarChar(255)
}

### Environment & setup

- OS: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy
- Database: Postgres
- Node.js version: 20.9.0

### Prisma Version

```
4.16.2
```

**Comment by jkomyno** [comment]
Hi @Fr3akyMurk, this warning indicates that wasn't able to detect your Linux Mint distro as distro belonging to a "well-known" Linux family, and thus it fell back to downloading the Prisma Engines compiled for Debian.

Thankfully, the Debian-built engines should be completely compatible with your system, so you should be able to run Prisma without any problem, despite that warning (which we acknowledge).
Could you please report back whether the rest of Prisma functionality works well for your use case? Thanks

**Comment by Fr3akyMurk** [comment]
Hi @jkomyno , Sorry, i forgot to respond.
Yes, the Debian built-in engines work flawlessly, at least to my current knowledge.
I can report to you if something happens, this issue was opened mainly so you could see if an update can be pushed to prevent this error from appearing again; at least on mint distros. (it can get pretty flooded and i prefer error-less consoles for in case i need debug statements or error logs.)

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
