### ISSUE TITLE
Case insensitive findMany querying

### ISSUE THREAD

**Issue by cr101** [prisma/prisma#2316]
## Problem
The argument `contains` in the `findMany` query is case sensitive.

## Solution
There needs to be an option to make the `contains` argument case insensitive.

## Alternatives
Currently to get around this issue is to use raw SQL like so:
`const posts = await prisma.raw(`SELECT * FROM Post WHERE LOWER(title) LIKE '%${search}%' OR LOWER(content) LIKE '%${search}%';`);`

**Comment by Sytten** [comment]
You can also use an `ILIKE` if using PostgresDB

**Comment by pantharshit00** [comment]
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma-client-js/issues/343
