### ISSUE TITLE
Incorrect syntax during $queryRawUnsafe

### ISSUE THREAD

**Issue by Ryxuu** [prisma/prisma#23178]
### Bug description

I am trying to write a prisma raw query to install a trigger in database on NodeJS server startup. The used database is MSSQL. But when I run this code:

```
const sql =
    "CREATE OR ALTER TRIGGER OnUserProfileTrigger
    ON UserProfile
    AFTER UPDATE
    AS
    BEGIN
        UPDATE UserProfile
            SET isActive = 1
    END"
;

await prisma.$queryRawUnsafe(sql);
```

I get **Incorrect syntax near the keyword 'OR'.**. If I use SQL Server Management Studio and run the trigger pasted above it run and inserted into database without any issue and works fine on update operations.

What could be the problem?

### How to reproduce

Run the following code (also mentioned above):

```
const sql =
    "CREATE OR ALTER TRIGGER OnUserProfileTrigger
    ON UserProfile
    AFTER UPDATE
    AS
    BEGIN
        UPDATE UserProfile
            SET isActive = 1
    END"
;

await prisma.$queryRawUnsafe(sql);
```

### Expected behavior

The trigger is inserted into database without any issue like it happens in SQL Server Manegement Studio manually.

### Prisma information

-

### Environment & setup

Windows 11 Pro
MSSQL
NodeJS 20.10.0 version

### Prisma Version

Version: 5.8.1
Error code: P2010

**Comment by miguelff** [comment]
@Ryxuu FWIW I have been able to create a trigger in a local mssql database, although it doesn't seem to be related, would you please send us the schema file you are using? 

Thank you.

**Comment by SevInf** [comment]
Hey @Ryxuu ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
