### ISSUE TITLE
Vercel - Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.

### ISSUE THREAD

**Issue by joeydotdev** [prisma/prisma#23187]
### Bug description

I'm running into the following error after deploying my website to vercel with prisma 5.9.1

`Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.`

### How to reproduce

1. Add a `postinstall` script of `prisma generate`
2. Update prisma schema to point to right output path
3. Verified on vercel end that prisma client was generated in build step
![image](https://github.com/prisma/prisma/assets/9088799/04164a4f-334a-496d-9303-fda2182e90ce)
4. Receive error in vercel runtime logs when trying to access my website
![image](https://github.com/prisma/prisma/assets/9088799/9aea9ffd-2ee7-49d2-830b-f325838e6d75)

### Expected behavior

no errors

### Prisma information

Prisma schema config
```prisma

generator client {
  provider = "prisma-client-js"
  output   = "./generated/client"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

Prisma client file used in application (sourced from [this guide](https://vercel.com/guides/nextjs-prisma-postgres))

```typescript
// @ts-nocheck
import { PrismaClient } from '@prisma/client';

let prisma: PrismaClient;

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient();
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient();
  }
  prisma = global.prisma;
}

export default prisma;
```

### Environment & setup

Vercel production environment

### Prisma Version

5.9.1

**Comment by janpio** [comment]
You are generating to a custom `output` location according to your `prisma generate` output, but importing from the default `@prisma/client`. After updating that to use the correct path, it should work.

**Comment by joshxfi** [comment]
Same issue here. I had to downgrade to `5.8.1` to make it work again.

For some reason, it had no problem building on my `preview` (dev) deployment but gave an error when I merged it to my `production` (main) deployment:

### `dev` branch

![image](https://github.com/prisma/prisma/assets/69457996/05f9a72c-4d53-496e-9246-c9bc85ad9f33)

### `main` branch

![image](https://github.com/prisma/prisma/assets/69457996/089a785e-9c4f-4ed6-a9c4-ec79e520fad4)
![image](https://github.com/prisma/prisma/assets/69457996/9331eba2-c6d7-41ca-aaf6-d4cee2a73be9)

NOTE: They both have the same commits/changes

**Comment by joeydotdev** [comment]
@janpio thanks for the quick reply. The issue was referencing the library import instead of the output path in my prisma client file. I can confirm that it is working in the vercel environment on prisma 5.9.1

**Comment by janpio** [comment]
Wonderful, so problem all solved and issue can be closed?

@joshxfi That sounds super weird does not really make sense. Please open a new discussion or bug issue and fill the full issue template so we can try to reproduce this with all the information we need for that. Thank you.

**Comment by joeydotdev** [comment]
> Wonderful, so problem all solved and issue can be closed?
> 
Yup closing this out now 🙏
