### ISSUE TITLE
Unable to set `@default` with `Json` data type (PostgreSQL)

### ISSUE THREAD

**Issue by naeem-qv** [prisma/prisma#23184]
### Bug description

I wanted to give a @default value to a  property but its showing this error `Error validating: This line is not a valid field or attribute definition.` 

### How to reproduce

1: create a new prisma.schema file.
2: define a model with some Json data type properties.
3: give @default value to it.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String     @id @default(cuid())
  email     String     @unique
  name      String
  password  String
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
  location  Location?
}
model Location {
  locationId   String @id @default(cuid())
  lat   Json[]
  long   Json[]
  merch Json[]
  seller Json[]
  dimension    Json   //@default()
  user         User   @relation(fields: [locationId], references: [id])
}
```

### Environment & setup

OS: windows 10 64x
Database: PostgreSQL
Node.js version: v20.9.0

### Prisma Version

```
prisma                  : 5.9.1
@prisma/client          : 5.9.1
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.9.0
```

**Comment by miguelff** [comment]
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

...
model Location {
...
  dimension  Json   @default("{}")
...
}
```

This line on the dimension field os the schema, worked for me. May you please try it out? The argument to `@default` has to be a valid JSON string between double quotes.

**Comment by naeem-qv** [comment]
> ```
> generator client {
>   provider = "prisma-client-js"
> }
> 
> datasource db {
>   provider = "postgresql"
>   url      = env("DATABASE_URL")
> }
> 
> ...
> model Location {
> ...
>   dimension  Json   @default("{}")
> ...
> }
> ```
> 
> This line on the dimension field os the schema, worked for me. May you please try it out? The argument to `@default` has to be a valid JSON string between double quotes.

Tried it but still getting same error

**Comment by janpio** [comment]
What exactly is showing the error? When you run `prisma validate`? Or are you using the Prisma VS Code extension?

I can confirm that any valid JSON inside double quotes works as `@default` values.

**Comment by marcalj** [comment]
I spotted this issue (on MySQL DB) when doing a migration. Adding a field like `Photos Json @default("[]")` it generates a migration without default value on it:

```sql
ALTER TABLE `Route` ADD COLUMN `Photos` JSON NOT NULL;
```

I had to add next line in the migration file to avoid data conflicts expecting empty arrays.

```sql
UPDATE Route SET `Photos` = "[]";
```

**Comment by janpio** [comment]
Interesting observation @marcalj. Can you please open a new issue for that? It seems unrelated to me - but of course also problematic.

**Comment by jkomyno** [comment]
Following @miguelff's suggestion, I'm not able to reproduce OP's issue with neither Prisma `5.9.1` nor the latest `5.10.2`.
Here's my `schema.prisma`:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String     @id @default(cuid())
  email     String     @unique
  name      String
  password  String
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
  location  Location?
}
model Location {
  locationId   String @id @default(cuid())
  lat   Json[]
  long   Json[]
  merch Json[]
  seller Json[]
  dimension    Json   @default("{}")
  user         User   @relation(fields: [locationId], references: [id])
}
```

- `prisma validate` confirms this is a valid schema
- `prisma migrate dev` (from before `@default("{}")` was added to after) results into:
  ```sql
  ALTER TABLE "Location" ALTER COLUMN "dimension" SET DEFAULT E'{}';
  ```
- using `@prisma/client` (e.g., `await prisma.location.findMany()`) works as intended.

---

On the other hand, running `prisma validate` on the original uncommented schema (with `dimension Json @default()`), results in the following error:

```
❯ pnpm prisma validate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

Error: Prisma schema validation - (validate wasm)
Error code: P1012
error: Argument "value" is missing.
  -->  schema.prisma:25
   | 
24 |   seller Json[]
25 |   dimension    Json   @default()
   | 

Validation Error Count: 1
[Context: validate]

Prisma CLI Version : 5.9.1
```

**Comment by jkomyno** [comment]
@marcalj's comment about MySQL made me realise the following:
- Changing a `mysql` schema field from `dimension Json` to `dimension Json @default("{}")` has no impact on the migrations. Specifically, running `pnpm prisma migrate dev --name add-default` results in the "Already in sync, no schema change or pending migration was found." message, with no SQL migration emitted from this change:
  ```
  Environment variables loaded from .env
  Prisma schema loaded from prisma/schema.prisma
  Datasource "db": MySQL database "tests" at "localhost:3306"
  
  Already in sync, no schema change or pending migration was found.
  
  ✔ Generated Prisma Client (v5.9.1) to ./node_modules/.pnpm/@prisma+client@5.9.1_prisma@5.9.1/node_modul
  es/@prisma/client in 40ms
  ```
- The `@default("[]")` problem reported above by @marcalj is likely related to Prisma not supporting the JSON list type (`Json[]`) on MySQL. For instance, running `prisma validate` on the following schema results in an error message:
  ```prisma
  generator client {
    provider = "prisma-client-js"
  }
  
  datasource db {
    provider = "mysql"
    url      = env("DATABASE_URL")
  }
  
  model Location {
    locationId   String @id @default(cuid())
    lat   Json[]
    dimension    Json
  }
  ```

  ```
  ❯ pnpm prisma validate
  Environment variables loaded from .env
  Prisma schema loaded from prisma/schema.prisma
  
  Error: Prisma schema validation - (validate wasm)
  Error code: P1012
  error: Error validating field `lat` in model `Location`: Field `lat` in model `Location` can't be of type Json[]. The current connector does not support the Json List type.
    -->  schema.prisma:12
     | 
  11 |   locationId String @id @default(cuid())
  12 |   lat        Json[]
  13 |   dimension  Json
     | 
  error: Field "lat" in model "Location" can't be a list. The current connector does not support lists of primitive types.
    -->  schema.prisma:12
     | 
  11 |   locationId String @id @default(cuid())
  12 |   lat        Json[]
  13 |   dimension  Json
     | 
  
  Validation Error Count: 2
  [Context: validate]
  
  Prisma CLI Version : 5.9.1
  ```

**Comment by chenpercy** [comment]
Same issue with @marcalj 

Default value not set in migration file even default value already set in schema
```
...
caseStatuses       Json                @default("[]") @map("case_statuses")
```

```
-- AlterTable
ALTER TABLE `schedule` ADD COLUMN `case_statuses` JSON NOT NULL;  // not see DEFAULT ('[]') in the end
```

**Comment by janpio** [comment]
The problem with `[]` is tracked over here @chenpercy: https://github.com/prisma/prisma/issues/23250

**Comment by naeem-qv** [comment]
> @jkomyno @miguelff I think we can close this issue as the original report was about `@default()` not being allowed, which is absolutely correct for a `Json` type field, isn't it?

Yes @janpio sorry for the delayed response.
I'm closing it. 😊
