### ISSUE TITLE
Prisma generates duplicate type in `node_modules/.prisma/client/index.d.ts`

### ISSUE THREAD

**Issue by QuentinGaladrim** [prisma/prisma#23190]
### Bug description

I've been upgrading the packages of one of my NestJS projects recently, and went from Prisma 3.13 to version 5.9. But when I run `pnpm run start:dev`. I get TS errors inside this file `node_modules/.pnpm/@prisma+client@5.9.1_prisma@5.9.1/node_modules/.prisma/client/index.d.ts`. I went and check and there are indeed duplicates types.
I tried recreating a reproduction repository, but when I put the content of my `schema.prisma` in the reproduction repo, everything worked well.

I can provide my schema but wouldn't share it publicly.

I also tried downgrading, and it finally worked when I reached v4.12 (which probably means that something changed between v4.12 and v4.13 and up). Furthermore, I want to highlight that every time I tried downgrading, I removed `node_modules` reinstalled them and re-generate Prisma.

It also seems some generated types differ only on plural (like a 's') 
![image](https://github.com/prisma/prisma/assets/112630508/4abf0023-1701-4688-97bc-b3ac96f365ae)

### How to reproduce

Upgrade Prisma from v3.13 to v5.9

### Prisma information

```prisma
Can provide it
```

```ts
Classical NestJS Prisma Client
```

### Environment & setup

- OS: MacOS
- Database: MySQL
- Node.js version: Node 18 and tried Node 16 too

### Prisma Version

```
Tried for versions from 4.13 up to 5.9 and doesn't work
```

**Comment by millsp** [comment]
Hey @QuentinGaladrim could you please try our latest release? If it's still broken, you can send your schema at `schemas@prisma.io`.

**Comment by SevInf** [comment]
Hey @QuentinGaladrim ,

Did you get a chance to have a look at collegues previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by QuentinGaladrim** [comment]
Hey ! 
Sorry, I didn't had the time to try to update to latest release lately, but kinda managed to work around :
I have two models in my schema, one named `Order` and the other `Others`, this is probably where the duplicate types come from (plural making generated types ambiguous and duplicates)
Plus, as far as I saw (didn't test it all out in my app) but adding `"skipLibCheck": true` in my `tsconfig.json` fixed the problem when committing and starting my app.

I'll close the issue as it seems there is no problem.
Thanks for your attention 🙏
