### ISSUE TITLE
`Error:  Invalid character` when `schema.prisma` includes Chinese characters in a comment

### ISSUE THREAD

**Issue by zfjhui** [prisma/prisma#23201]
### Bug description
```bash
> prisma generate

Prisma schema loaded from schema.prisma
Error: 
Invalid character
```
### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = "mysql://test@127.0.0.1:3306/test"
}

model cache {
  key        String @unique @db.VarChar(128)
  val        Json   @db.Json //数据
  expiration Int    @db.UnsignedInt
}

```

### Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version:21.6.2

### Prisma Version

```
"@prisma/client": "5.10.0",
 "prisma": "5.10.0"
```

**Comment by janpio** [comment]
Is this a new problem in 5.10.0 or is this the first version you are trying?

**Comment by zfjhui** [comment]
Historical version,no problem

**Comment by janpio** [comment]
I can reproduce this:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = "mysql://test@127.0.0.1:3306/test"
}

model foo {
  bar String @unique //据
}
```

leads to
```
PS C:\Users\Jan\Documents\throwaway\23201> npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: 
Invalid character
```

This fails back to at least 5.0.0, so definitely not a new problem :/

**Comment by zfjhui** [comment]
Try again.
only 5.10.0  ,historical version,no problem

**Comment by janpio** [comment]
You are correct, no idea how I messed that up:

````
C:\Users\Jan\Documents\throwaway\23201>npx prisma -v
Environment variables loaded from .env
prisma                  : 5.9.1
@prisma/client          : 5.9.1
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-32.23fdc5965b1e05fc54e5f26ed3de66776b93de64
Default Engines Hash    : 23fdc5965b1e05fc54e5f26ed3de66776b93de64
Studio                  : 0.497.0

C:\Users\Jan\Documents\throwaway\23201>npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (v5.9.1) to .\node_modules\@prisma\client in 55ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client
````

But then:
````
C:\Users\Jan\Documents\throwaway\23201>npm install prisma@5.10.0 @prisma/client@5.10.0

changed 7 packages, and audited 8 packages in 5s

found 0 vulnerabilities

C:\Users\Jan\Documents\throwaway\23201>npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error:
Invalid character
````

**Comment by janpio** [comment]
The problem seems to be related to the Prisma Client version you are using when running `prisma generate` specifically. When using CLI 5.10.0 it works with the older Client, but not with the matching current one:

````
C:\Users\Jan\Documents\throwaway\23201>npm install @prisma/client@5.9.1

changed 1 package, and audited 8 packages in 3s

found 0 vulnerabilities

C:\Users\Jan\Documents\throwaway\23201>npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (v5.9.1) to .\node_modules\@prisma\client in 53ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

warn Versions of prisma@5.10.0 and @prisma/client@5.9.1 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
```` 

But:
```
C:\Users\Jan\Documents\throwaway\23201>npm install @prisma/client@5.10.0

changed 1 package, and audited 8 packages in 2s

found 0 vulnerabilities

C:\Users\Jan\Documents\throwaway\23201>npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error:
Invalid character



C:\Users\Jan\Documents\throwaway\23201>
```

**Comment by zfjhui** [comment]
I @prisma/client and  prisma same version
`json
"@prisma/client": "5.10.0",
"prisma": "5.10.0"
`
fallback to 5.9.1

**Comment by kingfishx23** [comment]
I also have the same problem, however in my prisma schema I didnt use any chinese characters. before it works, now it doesnt. i use 5.10.0. i tried 5.9.1 and 5.4.1 and error persists

**Comment by janpio** [comment]
Any other non western characters in your schema as comments maybe @kingfishx23? Might not be limited to concretely Chinese.

Besides that: We have reproduced this internally and are working on a fix, which will most probably be released as 5.10.1 soon.

**Comment by kingfishx23** [comment]
> Any other non western characters in your schema as comments maybe @kingfishx23? Might not be limited to concretely Chinese.
> 
> Besides that: We have reproduced this internally and are working on a fix, which will most probably be released as 5.10.1 soon.

I tried using vscode find with this regex [^\x00-\x7F]+, 

I did have comments on the prisma.schema for aesthetics purpose like this

//  ┌────────────────────────────────────────────────────────────────────────────┐
//  │ SOME_TEXT                                                                                                                                                                                 │
//  └────────────────────────────────────────────────────────────────────────────┘

Could this be the problem?

**Comment by janpio** [comment]
Yes, in this fault version it might indeed be. It should not be in the patch that we will release - so just wait with upgrading until that is out. Thank you.

**Comment by kingfishx23** [comment]
> Yes, in this fault version it might indeed be. It should not be in the patch that we will release - so just wait with upgrading until that is out. Thank you.

Weirdly i tried downgrading the version and the problem still exists. Is the only solution to wait for the patch?

**Comment by janpio** [comment]
If you downgrade `@prisma/client` it should work again next time you run `prisma generate`: `npm install @prisma/client@5.9.1`. If that does not work, maybe something is cached by your package manager. Nuke your `node_modules` and run `npm install` again.

**Comment by millsp** [comment]
Hey @zfjhui @kingfishx23, we have issued a fix for this issue in our latest patch version [5.10.1](https://github.com/prisma/prisma/releases/tag/5.10.1). Thanks for the report!
