### ISSUE TITLE
Prisma generate requires nonempty URL environment for the datasource

### ISSUE THREAD

**Issue by marcjulian** [prisma/prisma#2321]
## Bug description

After updating from prisma 2.0.0-beta.2 to 2.0.0-beta.3 the following error occurs for an empty `POSTGRESQL_URL`. 

```
npx prisma generate
Error: Schema parsing
error: Error validating source `db`: You must provide a nonempty URL for the datasource `db`. The environment variable `POSTGRESQL_URL` resolved to an empty string.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("POSTGRESQL_URL")
   |
```

Error occured on GitHub actions https://github.com/fivethree-team/nestjs-prisma-starter/runs/625154458?check_suite_focus=true

## How to reproduce

1. Go to https://github.com/fivethree-team/nestjs-prisma-starter
2. Add `prisma/.env` with `POSTGRESQL_URL=`
3. Run `npx prisma generate`

## Expected behavior

In prisma 2.0.0-beta.2 `npx prisma generate` generates the client with an empty URL environment without an error.

## Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("POSTGRESQL_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  email     String   @unique
  password  String
  firstname String?
  lastname  String?
  posts     Post[]
  role      Role
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  String?
}

enum Role {
  ADMIN
  USER
}
```

## Environment & setup

- OS: Mac OS Catalina, GitHub Actions
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.3
- Node.js version: v12.16.1

**Comment by marcjulian** [comment]
If I don't setup the `POSTGRESQL_URL` in `.env` than `npx prisma generate` works fine without error.

**Comment by mavilein** [comment]
@marcjulian : Can you elaborate why you need this behavior? To me it seems intuitive that you run into this error if you choose to provide the environment variable.

**Comment by marcjulian** [comment]
With `2.0.0-preview024` I received an error in `npx prisma2 generate` without an environment variable: `Environment variable not found` (https://github.com/fivethree-team/nestjs-prisma-starter/runs/539009046). Then I added an empty environment variable as this was required for  prisma client generation. This seems to work until `2.0.0-beta.2`.

**Comment by pantharshit00** [comment]
@marcjulian Right now environment variables are not required for code generation. You can omit the work around completely.

**Comment by matthewmueller** [comment]
Closing via https://github.com/prisma/prisma/issues/800. Environment variables are no longer required at generation time.
