### ISSUE TITLE
Add "Peppermint OS" to list of supported distros

### ISSUE THREAD

**Issue by qlmoffat** [prisma/prisma#23237]
## Problem

I received the following trying to do `npx prisma init`

> prisma:warn Prisma doesn't know which engines to download for the Linux distro "peppermint". Falling back to Prisma engines built "debian".
> Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.

## Suggested solution

Peppermint is a fork of Debian, shipped with XFCE and less default software. https://peppermintos.com/

**Comment by Jolg42** [comment]
I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message will be part of the next release `5.11.0`, next week.
