### ISSUE TITLE
Cannot update a column value to null?

### ISSUE THREAD

**Issue by ShehabSN** [prisma/prisma#2324]
I have a foreign key column in my table, call it parentId, when parentId is null, i know that the current row has no parent. If it is not null then I can use that foreign key to connect with the corresponding parent. When trying to use update in prisma, i run into a few issues:

First, I cannot directly update the value of parentId or any foreign key for that matter, and instead an error is thrown and I am basically told that parentId field doesnt exist and instead what im looking for is the relation field parent. So the below does not work
```
db.folder.update({
    data: {
      parentId: obj.id
    },
    where: { id },
  })
```
So when i try to instead update the relation field parent like this: 
```
db.folder.update({
    data: {
      parent:
         {
              connect: {
                id: obj.id,
              },
            },
    },
    where: { id },
  })
```
Then if obj.id is null, an error is thrown because you cant connect with a null id, so instead i add a conditional, 
```
db.folder.update({
    data: {
      parent:
        obj.id == null
          ? null
          : {
              connect: {
                id: obj.id,
              },
            },
    },
    where: { id },
  })
```
And this does not work either, instead every time i pass in null, the value in the db is not changed, which i guess is a safeguard so that if no parameter is passed in, it doesnt nullify the value. However, I need to update the value of parentId to be null in certain cases... How can i do that??

**Comment by pantharshit00** [comment]
Hi @ShehabSN,

Can you please share your schema with us?

**Comment by ShehabSN** [comment]
> Hi @ShehabSN,
> 
> Can you please share your schema with us?

This is the relevant folder schema with relevant columns

```
model Folder {
  id Int @id @default(autoincrement())
  name String

  parentFolderId Int?
  parentFolder Folder? @relation("ParentSubFolders", fields: [parentFolderId], references: [id])
  subFolders Folder[] @relation("ParentSubFolders")
}
```

**Comment by ShehabSN** [comment]
> Hi @ShehabSN,
> 
> Can you please share your schema with us?


Hi @pantharshit00 
This is the relevant folder schema with relevant columns

```
model Folder {
  id Int @id @default(autoincrement())

  parentId Int?
  parent Folder? @relation("ParentFolder", fields: [parentId], references: [id])
  subFolders Folder[] @relation("ParentFolder")
}
```

**Comment by pantharshit00** [comment]
I can confirm this. I tested it out with `2.0.0-alpha.1174`
 
Query sent to the engine:
```graphql
   mutation {
     updateOneFolder(
       data: {
         parent: {
           connect: {
             id: null
           }
         }
       }
       where: {
         id: 2
       }
     ) {
       id
       parentId
     }
   }

```

Client call:
```
prisma.folder.update({
     data: {
       parent: {
         connect: {
           id: null
         }
       }
     },
     where: {
       id: 2
     }
  })
```

Data in the database:
```sql
INSERT INTO "Folder" ("id", "parentId") VALUES
('1', NULL),
('2', '1');
```

Schema:
```prisma
model Folder {
  id Int @id @default(autoincrement())

  parentId Int?
  parent Folder? @relation("ParentFolder", fields: [parentId], references: [id])
  subFolders Folder[] @relation("ParentFolder")
}
```

**Comment by dpetrick** [comment]
This is not a but, but by design. If you want to `null` the relation, use `disconnect`. If you want to set the relation, use `connect`.

**Comment by pantharshit00** [comment]
Thanks @dpetrick, I missed that detail.

@ShehabSN You can use the following client attain the required result:
```js
prisma.folder.update({
     data: {
       parent: {
         disconnect: true
       }
     },
     where: {
       id: 2
     }
  })
```

**Comment by VladislavShapoval** [comment]
if anybody is still looking for answer:

`
prisma.yourTable.update({
   data: {
      yourFieldName: Prisma.NullableJsonNullValueInput.DbNull,
   },
   where: {
     id: 1,
   }
});
`

**Comment by lucroch** [comment]
@VladislavShapoval doing this disconnects the relation automatically as well?

**Comment by VladislavShapoval** [comment]
@lucroch have no idea. but it definitely works if you wanna set some field to null
