### ISSUE TITLE
prisma generate with python on m1 not working

### ISSUE THREAD

**Issue by oskargbc** [prisma/prisma#23283]
### Bug description

When trying to run prisma generate this error occures everytime, tried to multiple times to reinstall with pip, from binary and reinstalling pip3:

> prisma generate

Prisma schema loaded from prisma/schema.prisma
Error: Generator "prisma-client-py" failed:

Traceback (most recent call last):
  File "/Users/test/PycharmProjects/pythonProject/venv/bin/prisma-client-py", line 5, in <module>
    from prisma.cli import main
  File "/Users/test/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/prisma/__init__.py", line 11, in <module>
    from ._config import config as config
  File "/Users/test/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/prisma/_config.py", line 12, in <module>
    from ._compat import (
  File "/Users/test/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/prisma/_compat.py", line 9, in <module>
    from pydantic import BaseModel
  File "/Users/test/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/pydantic/__init__.py", line 383, in __getattr__
    module = import_module(module_name, package=package)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/test/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/pydantic/main.py", line 12, in <module>
    import pydantic_core
  File "/Users/test/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/pydantic_core/__init__.py", line 6, in <module>
    from ._pydantic_core import (
ImportError: dlopen(/Users/test/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/pydantic_core/_pydantic_core.cpython-310-darwin.so, 0x0002): tried: '/Users/test/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/pydantic_core/_pydantic_core.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/test/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/pydantic_core/_pydantic_core.cpython-310-darwin.so' (no such file), '/Users/test/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/pydantic_core/_pydantic_core.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

### How to reproduce

prisma generate

### Prisma information

```prisma```
// Add your schema.prisma
```
generator client {
  provider             = "prisma-client-py"
  previewFeatures      = ["multiSchema"]
  recursive_type_depth = "5"
}

datasource db {
  provider  = "postgresql"
  url       = env("DB_URL")
  directUrl = env("DB_DIRECT_URL")
  schemas   = ["public"]
}

/// This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
model Test {
  id                 String   @id @default(cuid())
  test String   @unique

  @@schema("public")
}


### Environment & setup

- OS: <!--[e.g. macOS, Windows, Debian, CentOS, ...]--> macOS (14.2.1) (m1 pro chip)
- Database: <!--[PostgreSQL, MySQL, PlanetScale, MariaDB, SQL Server, SQLite, MongoDB or CockroachDB]--> PostgreSQl
- Node.js version: <!--[Run `node -v` to see your Node.js version]--> v16.13.1 


### Prisma Version

```
Environment variables loaded from .env
prisma                : 5.8.0
@prisma/client        : Not found
Computed binaryTarget : darwin
Operating System      : darwin
Architecture          : x64
Node.js               : v16.13.1
Query Engine (Binary) : query-engine 0a83d8541752d7582de2ebc1ece46519ce72a848 (at ../../../.cache/prisma-python/binaries/5.8.0/0a83d8541752d7582de2ebc1ece46519ce72a848/node_modules/@prisma/engines/query-engine-darwin)
Schema Engine         : schema-engine-cli 0a83d8541752d7582de2ebc1ece46519ce72a848 (at ../../../.cache/prisma-python/binaries/5.8.0/0a83d8541752d7582de2ebc1ece46519ce72a848/node_modules/@prisma/engines/schema-engine-darwin)
Schema Wasm           : @prisma/prisma-schema-wasm 5.8.0-37.0a83d8541752d7582de2ebc1ece46519ce72a848
Default Engines Hash  : 0a83d8541752d7582de2ebc1ece46519ce72a848
Studio                : 0.497.0
Preview Features      : multiSchema
```

**Comment by janpio** [comment]
Please open an issue over at https://github.com/RobertCraigie/prisma-client-py - we can't help much with the Python Client. Thanks.
