### ISSUE TITLE
Add MySql POINT DataType To Prisma

### ISSUE THREAD

**Issue by michael-paradis** [prisma/prisma#23302]
## Problem

MySql POINT Datatype is an unsupported type for prisma to map to. At least convert the value to string type?

## Suggested solution

Convert it to a string using ST_AsText(point)

## Alternatives

Currently i am using raw sql which somewhat defeats the purpose of using an ORM.

```
type Test = {
coordinates: string
}
const test:Test = await client.$queryRaw`select ST_AsText(coordinates) as coordinates from test_table`

OR 

let temp = await client.$queryRaw`SELECT ST_X(coordinates) AS longitude, ST_Y(coordinates) AS latitude FROM test_table`
```

This gets me around the issues for now but its nice to have the orm updated when my tables are changed instead of having to update this raw select query. 

## Additional context

I am using Prisma with MySql and Next.js application.

**Comment by janpio** [comment]
Is this covered by https://github.com/prisma/prisma2/issues/1798?

**Comment by michael-paradis** [comment]
Ah so its planned to be implemented according to what you linked me to

**Comment by janpio** [comment]
Not necessarily "planned", but it is a highly requested feature already that we track in that issue. I'll close this one then. Thanks!
