### ISSUE TITLE
MongoDB: Allow filtering with `gte`, `lte` etc on composite types

### ISSUE THREAD

**Issue by sbamniya** [prisma/prisma#23310]
## Problem

I have been using Prisma for a while and it works pretty fine with `postgresql`. In one of my project I am using MongoDB and wanted to use Prisma as ORM, so I started a project, but the now I am stuck with couple of things.

- Can't make nested schema within the same collection.
- Search by composite key with operations like `gte`, `lte`, `lt` etc.
- Can't reference composite key to a different collection.

```
type Leaves {
  id: String @db.ObjectId @map(_id)
  leaveTypeId String
  startDate Date
  endDate Date
}

model User {
 id String @db.ObjectId @map(_id)
 leaves: Leaves[]
}
```

Now, for all these, first, I want to create a reference to the `leaveTypeId` with `LeaveType` collection(I didn't mention here), and I want to filter all the users who are on leave between two dates, for example from 28th Feb to 5th March.

## Suggested solution

It should allow us to define nested schema without creating multiple collections, should also allow us to apply the filter on the composite keys, and should also allow to create relation from nested component with any of the collection.

## Alternatives

I have to go back to mongoose to achieve this, since it allows to do that, and now we are maintaining schemas at two places.

**Comment by millsp** [comment]
Hey @sbamniya thanks for the suggestions. Could you please open 3 different issues for the different improvements? This will help with discoverability for other user. Ideally if you can also add API ideas that would be nice. Thanks!

**Comment by sbamniya** [comment]
@millsp Sure, closing this and will create new.
