### ISSUE TITLE
Batching of `findUnique()` queries fails for certain parameters

### ISSUE THREAD

**Issue by eliasnorrby** [prisma/prisma#23313]
### Bug description

[The docs on query optimization](https://www.prisma.io/docs/orm/prisma-client/queries/query-optimization-performance#solving-n1-in-graphql-with-findunique-and-prisma-clients-dataloader) state that

> The Prisma Client dataloader automatically batches findUnique queries that ✔ occur in the same tick and ✔ have the same `where` and `include` parameters.

I find this is not always true, especially when `where` includes either `OR` or `AND`. 

[Here's an example project](https://github.com/prisma/prisma-examples/blob/b8c3614714e77d2060296ef1654bbb99ec616028/typescript/graphql-nestjs/src/resolvers.user.ts#L45-L53) leveraging batching of `findUnique` queries in a resolved graphql field:

```ts
  async posts(@Root() user: User, @Context() ctx): Promise<Post[]> {
    return this.prismaService.user
      .findUnique({
        where: {
          id: user.id,
        },
      })
      .posts()
  }
```

Changing it to 

```diff
  async posts(@Root() user: User, @Context() ctx): Promise<Post[]> {
    return this.prismaService.user
      .findUnique({
        where: {
          id: user.id,
+         AND: [],
        },
      })
      .posts()
  }
```

results in batching not working.

## Background – the real world use case

For context, we're using [`@casl/prisma`](https://casl.js.org/v5/en/package/casl-prisma) to control user permissions. This means we transform a set of access rules into where args for the relevant model, so we can e.g. list all posts a user can see by implementing `allPosts` something like:

```ts
async allPosts(@Ability() ability: PrismaAbility) {
  const where = accessibleBy(ability).Posts
  return await this.prismaService.posts.findMany({
    where
  })
}
```

We're also leveraging Prisma's data loaders, which means we'll be running things like:

```ts
    const whereAccessible = accessibleBy(ability).Posts 
    return this.prismaService.user
      .findUnique({
        where: {
          id: user.id,
          AND: whereAccessible
        }
      })
      .posts()
```

and this is where batching breaks down. Despite the parameters being identical, batching fails.

I've set up a reproduction repository based on the [graphql nestjs example](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-nestjs).

### Video demonstration

https://github.com/prisma/prisma/assets/11960052/2d3119dc-31a7-47ac-b3d4-ba7236260c52

### How to reproduce

1. Go to [eliasnorrby/prisma-dataloader-issue-reproduction](https://github.com/eliasnorrby/prisma-dataloader-issue-reproduction)
2. Follow the reproduction instructions

### Prisma information

See reproduction repository.

### Environment & setup

- OS: macOS
- Database: PostgreSQL, SQLite
- Node.js version: v18.16.1

### Prisma Version

```
prisma                  : 5.10.2
@prisma/client          : 5.10.2
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v18.16.1
Query Engine (Node-API) : libquery-engine 5a9203d0590c951969e85a7d07215503f4672eb9 (at node_modules/.pnpm/@prisma+engines@5.10.2/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 5a9203d0590c951969e85a7d07215503f4672eb9 (at node_modules/.pnpm/@prisma+engines@5.10.2/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.10.0-34.5a9203d0590c951969e85a7d07215503f4672eb9
Default Engines Hash    : 5a9203d0590c951969e85a7d07215503f4672eb9
Studio                  : 0.499.0
```

**Comment by eliasnorrby** [comment]
I can add that I've done some troubleshooting of the prisma client already. I found the [DataLoader implementation](https://github.com/prisma/prisma/blob/main/packages/client/src/runtime/DataLoader.ts) and suspected that `batchBy` would compute different hashes for my `findUnique` calls, but that was not the case. I also added some debug logging to the [`batchLoader`](https://github.com/prisma/prisma/blob/772876704f91474088ed7a5d10e8923de28386c6/packages/client/src/runtime/RequestHandler.ts#L75) to verify the queries were being submitted in a proper batch, and they were. Still, the engine did not execute a single query, but one for each request.

**Comment by Druue** [comment]
Note: we don't seem to have this explicitly stated anywhere in our docs

**Comment by janpio** [comment]
Do you want us to add some more batching, and see a way how that could work @eliasnorrby? If so, that is definitely worth a feature request. Thanks.
