### ISSUE TITLE
Exception: Prisma binary query engine not ready

### ISSUE THREAD

**Issue by Vietdq-dev** [prisma/prisma#23317]
### Bug description

Exception: Prisma binary query engine not ready

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version 5.10.2
![Uploading Screenshot 2024-02-29 at 13.04.36.png…]()

```

```

**Comment by millsp** [comment]
Hey @Vietdq-dev could you please share a reproduction with us? In the current state, I don't think anything is actionable and we would end up closing the issue. Could you please provide us with more info? Thanks!

**Comment by SevInf** [comment]
Hey @Vietdq-dev  ,

Did you get a chance to have a look at my colleagues comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by jkomyno** [comment]
Hi @Vietdq-dev, we're closing this issue as we didn't receive the reproduction we needed to investigate this.
Please leave a comment whenever you manage to provide such reproduction, so we can re-open this issue. Thanks!
