### ISSUE TITLE
Make downloading of prisma client can resume from last break point

### ISSUE THREAD

**Issue by wxfred** [prisma/prisma#23325]
## Problem
```
Downloading Prisma engines for Node-API for windows [========            ] 42%node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: read ECONNRESET
  code: 'ECONNRESET',
  syscall: 'read',
  attemptNumber: 1,
  retriesLeft: 2
}
```
With the break above, I restart the init command, and it downloads the engine from the very beginning! I think I can never finish it cause my bad internet condition.
Please add a break point resuming functionality!

**Comment by janpio** [comment]
Sorry, but that is not worth the effort on our side. The engine file is only a few megabytes, so downloading this is almost never a problem and almost none of our users are impacted by that. Trying to figure out how to make this download resumable would be major engineering effort.
