### ISSUE TITLE
MongoDB: Allow creating nested schema within single collection

### ISSUE THREAD

**Issue by sbamniya** [prisma/prisma#23329]
## Problem
Continuing https://github.com/prisma/prisma/issues/23310 as different issues. 
Can't make nested schema within the same collection.

## Suggested solution

It should be possible to allow creating nested schema within the same collection without creating new collection in MongoDB

```prisma
model LeaveType {
  id String @db.ObjectId @map(_id)
  
  @@map('leave_types')
}
model UserLeaveType {
  id String @db.ObjectId @map(_id)
  leaveTypeId String
  startDate Date
  endDate Date
  leaveType LeaveType @relation(fields: [leaveTypeId], references: [id])

  @@ignore(); // or similar API
}
model Users {
 id String @db.ObjectId @map(_id)
 leaves UserLeaveType[]

 @@map('users')
}
```

## Alternatives

Mongoose allows to created nested schema, and only creates the schema, if schema is passed as arg of `model()`

## Additional context
We don't necessarily need to create new collection for each model. There is `type` that can be used to create composite keys, but it has it's own limitations.

**Comment by janpio** [comment]
Does https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/composite-types satisfy your request?

**Comment by sbamniya** [comment]
Thank you for your reply @janpio, this does satisfies a lot of cases, but it has some restrictions, and one of them is the one I mentioned in this issue https://github.com/prisma/prisma/issues/23331 we can't create references and there are restrictions on the filtering as well.

**Comment by janpio** [comment]
Yes, #23331 indeed is missing in our composite types. (I think we actually have an existing issue for this, I'll sooner or later triage that and hopefully find it) 

Anything else that is covered by this issue that is not in any other? Otherwise I think we should close this here.

**Comment by sbamniya** [comment]
Yes, it can be closed. Thank you for your prompt response.
