### ISSUE TITLE
prisma.table.create not working when vector column exists.

### ISSUE THREAD

**Issue by 03hgryan** [prisma/prisma#23345]
### Bug description

It seems like create is not supported for tables with vector type column. Other functions like findMany() are fine.
Currently, I am using $executeRaw function,
`await prisma.$executeRaw`INSERT INTO your_table (embedding) VALUES (${embedding}::vector)`;`
but it'd be great if prisma support insert sql with create function.

### How to reproduce

1. Go to schema.prisma
2. Add vector type column to your_table
3. Run post api (create function) to the your_table

Invalid `prisma.your_table.create()` invocation:

Operation 'createOne' for model 'your_table' does not match any query."'

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["postgresqlExtensions"]
}

datasource db {
  provider   = "postgresql"
  url        = env("DATABASE_URL")
  extensions = [pg_trgm, pgvector(map: "vector", schema: "extensions")]
}

model your_table {
  id        Int                       @id @default(autoincrement())
  embedding Unsupported("vector(3)")?
}
```

```ts
await prisma.your_table.create({
    data: {
      embedding: embedding,
    },
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 18.11.0

### Prisma Version

```
5.10.2
```

**Comment by shrugs** [comment]
for future searchers: making the vector property optional seems to do the trick
