### ISSUE TITLE
Prisma Schema: Add .prisma syntax highlighting for Sublime Text

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#2336]
## Problem

While we already have syntax highlighting for VSCode and GitHub, we should also add syntax highlighting to [Sublime Text](https://www.sublimetext.com).

## Solution

We can re-use https://github.com/prisma/vscode/blob/master/syntaxes/prisma.tmLanguage.json
in Sublime Text https://www.sublimetext.com/docs/3/syntax.html

But we'd still need an extension for this.

**Comment by carmenberndt** [comment]
Since SublimeText only accepts  .sublime-syntax and .tmLanguage files for syntax highlighting, we have to convert our .tmLanguage.json to a .tmLanguage file.

**Comment by carmenberndt** [comment]
I created a repo here: 
https://github.com/prisma/sublimeText3
Currently waiting for the PR to be merged: https://github.com/wbond/package_control_channel/pull/7928

**Comment by janpio** [comment]
What a nice fight with "Package Control Bot" ⚔️

**Comment by carmenberndt** [comment]
**Update:** PR got merged. Closing this issue.

**Comment by janpio** [comment]
How does this work for users of Sublimetext now?

**Comment by carmenberndt** [comment]
![sublimeText](https://user-images.githubusercontent.com/30771368/82811554-53b46800-9e91-11ea-9c07-765a137d7508.gif)

Users only have to change 'Plain Text' to 'Prisma' when they open a file. If users want to automatically detect .prisma files, they have to set this option (https://stackoverflow.com/questions/27454555/how-do-i-set-sublime-text-to-auto-detect-a-file-type-after-setting-it-once/27456902#27456902)

**Comment by janpio** [comment]
Awesome!
