### ISSUE TITLE
PANIC: internal error: entered unreachable code after password change on sql server

### ISSUE THREAD

**Issue by redthorx** [prisma/prisma#23384]
### Bug description

When the password on MS sql server is changed on Azure SQL, prisma appears to reuse the connection to the SQL server, which raises a panic similar to https://github.com/prisma/prisma/issues/23182, even when the credentials on `url` for schema.prisma is changed.

### How to reproduce

1. Setup a DB on [Azure SQL](https://azure.microsoft.com/en-us/products/azure-sql/database)
2. Set the connection string to the SQL db on schema.prisma
```
datasource db {
  provider          = "sqlserver"
  url               = "sqlserver://someserver.database.windows.net:1433;database=exampledatabase;user=admin@someserver;password=password;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
}
```
3. Run the server with `npm run dev`
4. Quit the server with ctrl-c, and [change the db admin password on the platform](https://microsoft.github.io/AzureTipsAndTricks/blog/tip145.html)
5. Change schema.prisma with the new password
6. Start the server again
7. perform any query or mutation

Output from logs:
```
thread 'tokio-runtime-worker' panicked at libs/user-facing-errors/src/quaint.rs:125:18:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERR PrismaClientRustPanicError: 
Invalid `context.prisma.user.findMany()` invocation in
/home/.../src/resolvers.ts:14:34

  11 export const resolvers = {
  12   Query: {
  13     allUsers: (_parent, _args, context: Context) => {
→ 14       return context.prisma.user.findMany(
PANIC: internal error: entered unreachable code

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider          = "sqlserver"
  url               = "sqlserver://someserver.database.windows.net:1433;database=exampledatabase;user=user@someserver;password=password;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
}

model User {
  id            Int       @id @default(autoincrement())
  username      String    @unique
  password_hash String
}
```

### Environment & setup

- OS: Ubuntu 22.04.4 LTS
- Database: SQL Server
- Node.js version: 20.11.1

### Prisma Version

```
5.9.1
```

**Comment by Jolg42** [comment]
@redthorx I think what's happening here is that because you have the connection string in the schema, you will need to run `npx prisma generate` again to have the connection string updated in the generated Prisma Client.

Could you try to generate and see if that fixes your issue?

The better solution is to not use a connection string in your schema, instead use an environment variable so you don't need to re-generate the Prisma Client.

**Comment by redthorx** [comment]
hi @Jolg42,

Thanks for your help

I did fix it eventually with `npx prisma generate`, after trying multiple other methods.

Due to the panic error giving no debug output, i wasn't aware that changing  `url` to `env('DB_URL')`  without running `npx prisma generate` would have no effect, maybe a tip to re-run `prisma generate` on an auth error would be helpful.

thanks

**Comment by Jolg42** [comment]
@redthorx When running `prisma generate` this should be in the output `🛑 Hardcoding URLs in your schema poses a security risk: https://pris.ly/d/datasource-env` but I found that the link is not going where it should, I'll check if I can fix that 😄
