### ISSUE TITLE
Add .prisma syntax highlighting for IntelliJ

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#2339]
## Problem

While we already have syntax highlighting for VSCode and GitHub, we should also add syntax highlighting to [IntelliJ](https://www.jetbrains.com/idea/)

**Comment by beeman** [comment]
Related issue: https://github.com/prisma/prisma/issues/1788

**Comment by pantharshit00** [comment]
Closing as a duplicate of #1788. This issue got opened when we split #2335 but issue about this already exists
