### ISSUE TITLE
Prisma Schema: Add .prisma syntax highlighting for WebStorm

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#2340]
## Problem

While we already have syntax highlighting for VSCode and GitHub, we should also add syntax highlighting to [WebStorm](https://www.jetbrains.com/webstorm/).

**Comment by steebchen** [comment]
This is probably superseded by #2339 since the plugins are cross-JetBrains products.

**Comment by matthewmueller** [comment]
Thanks. Tracking in #2339
