### ISSUE TITLE
Wrong type of compound unique with optional fields

### ISSUE THREAD

**Issue by kracas** [prisma/prisma#23416]
### Bug description

When using compound uniques with optional fields, Prisma generates types of compound unique that does not allow for the optional fields to be optional.

### How to reproduce

1. Create Prisma schema:
```
model Test {
  id        Int      @id @default(autoincrement())
  optional1 String?
  optional2 String?
  required  String

  @@unique([optional1, optional2, required])
}
```
2. Generate client.
3. Type `TestOptionalRequiredCompoundUniqueInput` in `node_modules/.prisma/client/index.d.ts` is going to be:
```
  export type TestOptionalRequiredCompoundUniqueInput = {
    optional1: string
    optional2: string
    required: string
  }
```

### Expected behavior

I would expect `TestOptionalRequiredCompoundUniqueInput` to be something like
```
  export type TestOptionalRequiredCompoundUniqueInput = {
    optional1?: string
    optional2?: string
    required: string
  }
```

### Prisma information

model Test {
  id       Int     @id @default(autoincrement())
  optional1 String?
  optional2 String?
  required  String

  @@unique([optional1, optional2, required])
}

### Environment & setup

- OS: Ubuntu 22.04
- Database: Postgres
- Node.js version: 20.10.0

### Prisma Version

```
5.10.2
```

**Comment by SevInf** [comment]
This is done because `NULL` in SQL is not unique: for you example, it is possible to have multiple `{ optional1:"something", optional2: null, optional3: null }` entries in the database, which would break the contract of `findUnique`, `delete`, `upsert`  and other methods using unique inputs.
If you need to handle `null` values in those cases, please, use non-unique version of a method.

**Comment by kracas** [comment]
Yes, but this can be changed with `NULLS NOT DISTINCT` in Postgres, in which case `null` would be unique. But I guess that would need an additional feature where Prisma would support `NULLS NOT DISTINCT`

**Comment by janpio** [comment]
Are https://github.com/prisma/prisma/issues/3387 and https://github.com/prisma/prisma/issues/3197 related maybe?

**Comment by kracas** [comment]
Thanks @janpio, https://github.com/prisma/prisma/issues/3197 is the same issue I have. I somehow missed it when searching, but I think I was searching for bugs. In any case, I'll just follow that.
