### ISSUE TITLE
Prisma cli not available with yarn workspaces in latest release.

### ISSUE THREAD

**Issue by nnennajohn** [prisma/prisma#2341]
## Bug description

I updated to the latest version @^2.0.0-beta.4 to test out if the yarn workspace issue has been fixed, as there was a comment in the release notes about it. 

The issue still persist. Yarn does not recognize the prisma cli command. and throws an error when you try to use any prisma commands.

## Expected behavior

Running `yarn bin` as seen in the image below should show prisma in the list of executables.
Running any prisma command should work, and should not need to be done with npx.

## Prisma information

Not specific to query. Any prisma cli command should reproduce the above.

## Environment & setup

- OS: => Mac OS
- Database: => PostgreSQL
- Prisma version: => v2.0.0-beta.4
- Node.js version: => v12.14.1
- Yarn version => v2.0.0-rc.32

***Not available in `yarn bin`.***
<img width="1285" alt="Screen Shot 2020-04-30 at 9 49 47 AM" src="https://user-images.githubusercontent.com/1761197/80739644-a8033c80-8acb-11ea-85a2-ef77bf52af5c.png">

***Fails to find prisma script in bin***
<img width="1668" alt="Screen Shot 2020-04-30 at 10 04 55 AM" src="https://user-images.githubusercontent.com/1761197/80739767-d8e37180-8acb-11ea-9c9e-605f074c7f2e.png">

**Comment by jgeschwendt** [comment]
Ran into this today. Seems like Yarn2 (berry) has an issue resolving the binary without explicitly listing the `prisma`/`prisma2` dependency. Adding resolutions to the root `package.json` should restore those binaries to the `yarn bin` list.

```
"resolutions": {
    "@prisma/cli": "2.0.0-beta.5",
    "@prisma/client": "2.0.0-beta.5",
    "prisma": "@prisma/cli@2.0.0-beta.5",
    "prisma2": "@prisma/cli@2.0.0-beta.5"
  }
```

**Comment by nnennajohn** [comment]
Thanks so much @jgeschwendt . That worked. Also thanks for specifying that it should be in the root package.json, as I initially had it in the workspace package.json, and that does not work. 

Closing this. Maybe a note should be added to readme about this problem.
Thanks again. 

<img width="693" alt="Screen Shot 2020-05-12 at 2 54 01 PM" src="https://user-images.githubusercontent.com/1761197/81749491-9709e200-9460-11ea-944d-378a2444e7b9.png">
