### ISSUE TITLE
Major Bug - Connection Size Ignored In Postgres

### ISSUE THREAD

**Issue by Oliver-Bagin** [prisma/prisma#23423]
### Bug description

I am trying to set the connection limit for my database which is obviously very important. I need to increase the connections to properly leverage the DB. 

When I set the connection info prisma ignores the request.

### How to reproduce

My database connection url is set like this:
``` export DATABASE_URL="postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?connection_limit=10" ```

And this is passed through to Prisma as the following:
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Expected behavior

I create my client using the following:
```
import { PrismaClient } from '@prisma/client'
export const prisma = new PrismaClient({
  log: ['info']
})
```
And I get the following output:
```prisma:info Starting a postgresql pool with 21 connections.```
Which is clearly defaulting to the Prisma formula 2*10+1 for my 10 core m1 ignoring the set value. This is a really big problem as it means my one cpu  workers that do parallel work can be scaled to take advantage of the DB.

### Prisma information

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "linux-arm64-openssl-3.0.x"]
  previewFeatures = ["fullTextSearch", "metrics"]
}

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v18.17.1

### Prisma Version

```
"@prisma/client": "^5.10.2",
"prisma": "^5.10.2",
```

I updated to lastest today

**Comment by jkomyno** [comment]
Hi @Oliver-Bagin, I can't reproduce this. Here's my attempt.

## Files

- `.env` file:
  ```bash
  DATABASE_URL="postgres://prisma:prisma@localhost:5432/tests?connection_limit=10"
  ```

- `./prisma/schema.prisma` file
  ```prisma
  generator client {
    provider = "prisma-client-js"
  }
  
  datasource db {
    provider     = "postgres"
    url          = env("DATABASE_URL")
  }
  
  model test_model {
    id Int @id
  }
  ```

- `reprod-23423.mjs` file
  ```javascript
  import { PrismaClient } from '@prisma/client'
  
  export async function main() {
    // prisma automatically reads `DATABASE_URL` from `.env`, if it exists
    const prisma = new PrismaClient({ log: ['info'] })
    await prisma.$connect()
    await prisma.$disconnect()
  }
  
  main()
  ```

## Setup

- Push Prisma schema + generate `@prisma/client`
  ```bash
  pnpm prisma db push
  ```
  
  Output:
  ```bash
  ❯ pnpm prisma db push
  Environment variables loaded from .env
  Prisma schema loaded from prisma/schema.prisma
  Datasource "db": PostgreSQL database "tests" at "localhost:5432"
  
  The database is already in sync with the Prisma schema.
  
  ✔ Generated Prisma Client (v5.10.2) to <path...>
  ```

- Run `@prisma/client`

  ```bash
  node ./reprod-23423.mjs
  ```
  
  Output:
  ```bash
  prisma:info Starting a postgresql pool with 10 connections.
  ```

May I ask, where did you set your `DATABASE_URL` environment variable? Are you sure the environment variable is up to date?

**Comment by Oliver-Bagin** [comment]
I understand after looking at your response to the problem what was going on. The way the docs read I was under the impression that connection_limit was set when prisma cleint was generated eg in my pipline with `prisma build`. I see now that this is overridden by the variable in the environment present when the client runs.
