### ISSUE TITLE
prisma init - assumes PG

### ISSUE THREAD

**Issue by ORESoftware** [prisma/prisma#23447]
When I ran `prisma init` it just created a pretty empty prisma.schema file with datasource as postgres.
Shouldn't we have a dialog session where it asks us a series of questions about what kind of datasource etc?

Doesn't seem like a huge issue, but an interactive system to init prisma would be nice.

**Comment by janpio** [comment]
PostgreSQL is the most popular database of Prisma users, so our default choice is correct for most of our users. 
To change the created Prisma schema, you can use `prisma init --datasource-provider mysql` for example - or of course just edit the file after it was created.

We had an interactive `prisma init` in the long forgotten past, but that had quite a few downsides and we decided to remove most interactivity from our CLI and use options instead.
