### ISSUE TITLE
Simple filtering for JSON

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2345]
Follow up to https://github.com/prisma/prisma/issues/186

**Comment by tomhoule** [comment]
We are working on implementing filtering (equality and non equality) on JSON fields in Postgres and MySQL (5.7 and 8). As far as I am aware, we don't have consensus on the implementation yet but we have multiple ways to implement it. One PR in this direction: https://github.com/prisma/prisma-engines/pull/725

**Comment by tomhoule** [comment]
To clarify what we are currently looking into: this is only `equals` and `not equals` comparisons, so you would only be able to filter `Json` fields by comparing with an identical JSON value.

**Comment by radicand** [comment]
@tomhoule - so that I understand, if the DB has a row with a JSON field value of `{"field":1, "anotherfield":2}`, is this tracking just checking if the field is exactly that, or would something like checking if `field1=1` be covered / match the row?

**Comment by tomhoule** [comment]
For the first version no, we would only be comparing against the whole JSON value. We definitely want to enable more operations like comparing specific paths in JSON objects, like your example, but that will come later.

**Comment by tomhoule** [comment]
I created an issue for more advanced JSON filtering: https://github.com/prisma/prisma/issues/2444

**Comment by do4gr** [comment]
Closing this since simple equality filtering for the complete Json is now implemented.
