### ISSUE TITLE
Using Prisma in a Next.js middleware via `next dev` has misleading error message (says "Vercel Edge ... Middleware" instead of just "Edge Runtime" or "Next.js middleware"))

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#23459]
The error message references "Vercel Edge Functions or Edge Middleware" although this is just a local `yarn dev` that seems to run the middleware in a local Edge Runtime:

Reproduction: 
- https://github.com/janpio/next-prisma-repro/tree/prisma-5.11.0-no-driveradapters
- `yarn`
- `yarn dev`

<img width="765" alt="image" src="https://github.com/prisma/prisma/assets/183673/3043c24b-ce6d-47d1-8402-7da27680ab59">

---

Information about Next.js middleware using Edge Runtime locally:

> ### [Runtime](https://nextjs.org/docs/app/building-your-application/routing/middleware#runtime)
> Middleware currently only supports the [Edge runtime](https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes). The Node.js runtime can not be used.

https://nextjs.org/docs/app/building-your-application/routing/middleware#runtime

**Comment by liuhuapiaoyuan** [comment]
Yes, how can the problem of local development and local database be solved?

**Comment by janpio** [comment]
That is offtopic for this issue @liuhuapiaoyuan. Can you please open a new discussion and ask there? Thank you. (Please make sure to describe the problem a bit more and give some context what you are asking about. Thanks.)
