### ISSUE TITLE
`db pull` can't parse script setting default value

### ISSUE THREAD

**Issue by Alicia-bites** [prisma/prisma#23453]
### Bug description

When I try to introspect the database, I get an error about a script that sets a default value for a column as 'Non'. 

Here is the script :
```
/****** Object:  Default dbo.Non    Script Date: 21/12/98 09:42:22 ******/
/****** Object:  Default dbo.Non    Script Date: 03/12/98 14:41:54 ******/
/****** Object:  Default dbo.Non    Script Date: 20/10/98 14:23:35 ******/
/****** Object:  Default dbo.Non    Script Date: 19/10/98 09:48:52 ******/
/****** Objet:  valeur par défaut: dbo.Non    Date de script: 16/10/98 18:26:53 ******/
create default Non as 'Non'
```

### How to reproduce

npx prisma db pull

### Expected behavior

The introspection get all the tables from the database and translate them into models in schema.prisma

### Prisma information

npx prisma db pull

schema :

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["views"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: Ubuntu
- Database: SQL Server
- Node.js version: v20.11.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.10.2
@prisma/client          : 5.10.2
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux

```

**Comment by janpio** [comment]
What error are you getting?
How can we reproduce this?

**Comment by Alicia-bites** [comment]
Hello! Thank you for the answer :)

Here is the error:

➜  backend git:(talking_to_neoler) ✗ npx prisma db pull              talking_to_neoler ✱ ◼
Prisma schema loaded from prisma/schema.prisma
Environment variables loaded from .env
Datasource "db": SQL Server database

✖ Introspecting based on datasource defined in prisma/schema.prisma

Oops, an unexpected error occurred!
Error in Schema engine.
Reason: [schema-engine/sql-schema-describer/src/mssql.rs:348:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `/****** Object:  Default dbo.Non    Script Date: 21/12/98 09:42:22 ******/\r\n/****** Object:  Default dbo.Non    Script Date: 03/12/98 14:41:54 ******/\r\n/****** Object:  Default dbo.Non    Script Date: 20/10/98 14:23:35 ******/\r\n/****** Object:  Default dbo.Non    Script Date: 19/10/98 09:48:52 ******/\r\n/****** Objet:  valeur par défaut: dbo.Non    Date de script: 16/10/98 18:26:53 ******/\r\ncreate default Non as 'Non'\r\n`"

To reproduce it you would need to connect to my database.

**Comment by Weakky** [comment]
Hey @Alicia-bites, is there any chance you could share with us your sql database schema? Even privately if needed. That would help us a lot to reproduce your issue. Thank you 🙏

**Comment by janpio** [comment]
(For us the default is just ignored and not represented in the Prisma schema: https://github.com/prisma/prisma/issues/12150)

**Comment by janpio** [comment]
@Alicia-bites I investigated this problem a bit further, and it seem that the error message is slightly misleading. The `CREATE DEFAULT ... AS ...` itself is not the problem, it is how that default is used in some tables. We can not figure out how to create a database that triggers this error, so it would be _really_ helpful if you could help us out here. Can you please also shared which SQL Server version you were using here?

**Comment by janpio** [comment]
I actually figured it out: https://github.com/prisma/prisma/issues/24275 The comment before the actual SQL is the problem.
