### ISSUE TITLE
Nexus root types not working properly with last Beta

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma#2346]
After updating to the last Beta 3, root types in Nexus are not working properly:
 
<img width="642" alt="Screenshot 2020-05-01 at 12 08 25" src="https://user-images.githubusercontent.com/7753942/80783686-bbcea180-8ba4-11ea-8b06-703bef11ef9a.png">
<img width="947" alt="Screenshot 2020-05-01 at 12 08 41" src="https://user-images.githubusercontent.com/7753942/80783692-bf622880-8ba4-11ea-8a34-733b7a9ba51e.png">

**Comment by pantharshit00** [comment]
Please open this issue here: https://github.com/prisma-labs/nexus-prisma

Then someone from the labs team can have a look. I can't transfer it as GitHub doesn't allow cross org transfers.
