### ISSUE TITLE
Prisma migrate diff failed from url pointing to crdb to schema

### ISSUE THREAD

**Issue by sastry-v** [prisma/prisma#23506]
Hi Prisma Team! The following command just crashed.

## Command

`migrate diff --from-url [redacted] --to-schema-datamodel [redacted] --script`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v20.11.1           | 
| Prisma CLI  | 4.11.0             | 
| Engine      | 8fde8fef4033376662cad983758335009d522acb| 

## Error
```
Error: Error in migration engine.
Reason: [/Users/runner/work/prisma-engines/prisma-engines/libs/sql-schema-describer/src/walkers/column.rs:74:61] called `Option::unwrap()` on a `None` value

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by sastry-v** [comment]
Please let me know if you need additional information. I can reproduce this.

**Comment by SevInf** [comment]
Hi @sastry-v.
Thanks for opening the issue. First of all, version of Prisma you are reporting is almost 1 year old. Could you verify it on a newer version?
If it still happens on 5.11, we'd need following things to reproduce it:
- SQL dump of DB schema `--from-url` point to
- Prisma schema `--to-schema-datamodel` points to.

Thank you!

**Comment by sastry-v** [comment]
Thanks for the prompt response. I am no longer able to generate this issue after:
- Upgrading prisma
- Specifying `provider = "cockroachdb"` in Prisma schema

**Comment by sastry-v** [comment]
Seems like the issue was due to user error. Closing..
