### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by thingsneverchange** [prisma/prisma#23528]
### Bug description

This happens with one to many relations that refer UUID on a parent table. Funny thing is that if I enable previewFeatures = ["relationJoins"], it works fine. 

### How to reproduce
```
await Prisma.assetDownload.findUnique({
      where: {
        file_name: filename
      },
      include: {
        asset: {
        }
      }
    })
```

### Prisma information

```
model Asset {
  id                                          Int @id @default(autoincrement())
  name                                        String @db.VarChar(80)
  description                                 String @db.VarChar(500)
  uuid                                        String @db.VarChar(80) @unique
  slug                                        String @db.VarChar(250) @unique
}

model AssetDownload {
  id                                         Int     @id @default(autoincrement())
  user_id                                    Int     @unique
  user                                       User?    @relation(fields: [user_id], references: [id])
  user_agent                                 String  @db.VarChar(500)
  file_name                                  String  @db.VarChar(200) @unique
  asset_uuid                                 String  @db.VarChar(80) @unique
  asset                                      Asset?   @relation(fields: [asset_uuid], references: [uuid])
}


model User {
  id                                         Int @id @default(autoincrement())
  username                                   String @db.VarChar(255) @unique
  email                                      String @db.VarChar(255) @unique
  password                                   String @db.VarChar(255)
}
```
A simple  schema. I deleted some columns just to make this minimal.

### Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: 21.6.2

### Prisma Version

```
5.11
```

**Comment by SevInf** [comment]
Hi @thingsneverchange.
Will you be able to share a sample of the data you are querying, for both `asset` and `assetDownload` models? 
Thank you!

**Comment by jkomyno** [comment]
Hey @thingsneverchange, can you please reply to the [comment](https://github.com/prisma/prisma/issues/23528#issuecomment-2006562510) above? That would help our attempts to fix this issue. Thanks!

**Comment by SevInf** [comment]
Hey @thingsneverchange ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
