### ISSUE TITLE
Prisma Schema Error with Json Type

### ISSUE THREAD

**Issue by its-kyle-yo** [prisma/prisma#2354]
## Bug description

When upgrading to beta.4 and changing a value from `String` to `Json` the error 

`Type "Json" is neither a built-in type, nor refers to another model, custom type, or enum`

## How to reproduce

1. Use beta.4
2. Change any previous data type to `Json`
3. See error

## Expected behavior

`Json` to be a recognized and auto-completable field for `schema.prisma`

## Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id              String       @default(cuid()) @id
  twitterUserID   String       @unique
  twitterHandle   String
  isSubscribed    Boolean      @default(false)
  isNewUser       Boolean      @default(true)
  profileImageUrl String
  name            String
  commitments     Commitment[]
  posts           Post[]
  createdAt       DateTime     @default(now())
}

model Commitment {
  id           String @default(cuid()) @id
  text         String
  type         String
  duration     Int
  durationType String
  author       User   @relation(fields: [authorID], references: [id])
  authorID     String
}

model Post {
  id                String   @default(cuid()) @id
  twitterPostID     String   @unique
  createdAt         String
  deconstructedDate Json
  text              String
  source            String
  hashtags          String[]
  media             Media[]
  author            User     @relation(fields: [authorID], references: [id])
  authorID          String
}

model Media {
  id             String  @default(cuid()) @id
  post           Post    @relation(fields: [postID], references: [id])
  postID         String
  twitterMediaID String  @unique
  imageUrl       String?
  videoUrl       String?
  type           String
}

model Webhook {
  id               String  @default(cuid()) @id
  twitterWebhookID String  @unique
  url              String
  valid            Boolean
  createdAt        String
  environment      String
}
```

## Environment & setup

`@prisma/cli          : 2.0.0-beta.1`
`Current platform     : darwin`
`Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/kyle/.nvm/versions/node/v13.3.0/lib/node_modules/@prisma/cli/query-engine-darwin)`
`Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/kyle/.nvm/versions/node/v13.3.0/lib/node_modules/@prisma/cli/migration-engine-darwin)`
`Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/kyle/.nvm/versions/node/v13.3.0/lib/node_modules/@prisma/cli/introspection-engine-darwin)`

**Comment by its-kyle-yo** [comment]
Relevant Screenshot: 
![Screen Shot 2020-05-02 at 10 06 40 AM](https://user-images.githubusercontent.com/10294100/80867925-a0bf6880-8c5c-11ea-97d5-de3317cf68fa.png)

**Comment by janpio** [comment]
> `@prisma/cli : 2.0.0-beta.1`

This indicates you are not actually using beta.4!?

Are you getting this error message only in the VS Code extension or also somewhere else?
What version of the VSCode extension are you using?

**Comment by its-kyle-yo** [comment]
Looks as if I overlooked that and was given a false positive that I was using beta.4 due to it correctly running and showing the difference in Postgres

**Comment by cesarve78** [comment]
I update to node 16 and now is working.
