### ISSUE TITLE
Unable to set data on Json field

### ISSUE THREAD

**Issue by hugohammarstrom** [prisma/prisma#2355]
## Bug description
When trying to set JSON data on a field that is of type `JSON` I'm receiving the following error message. 

```
Error parsing GraphQL query: query parse error: Parse error at 17:7
Unexpected `"version"[StringValue]`
Expected `Name`, `:` or `}`
```
And if I set data to an empty object ({}) I get this error:
```
Failed to validate the query `Error occurred during query validation & transformation:
Mutation (object)
  ↳ createOnePost (field)
    ↳ data (argument)
      ↳ PostCreateInput (object)
        ↳ data (field)
          ↳ Value types mismatch. Have: Object({}), want: Scalar(Json)` at `.Mutation.createOnePost.data.PostCreateInput.data`
```

## Prisma information

```
...
model Post {
  id         Int    @default(autoincrement()) @id
  author     User   @relation(fields: [authorId], references: [id])
  authorId   Int    @map("author")
  title      String
  data       Json
}
...
```

```js
//This generates the first error message
const post = await client.post.create({
  data: {
    author: {
      connect: {
        id: 1
      }
    }
    data: {
      version: 1,
    },
  },
});

//This generates the second error message
const post = await client.post.create({
  data: {
    author: {
      connect: {
        id: 1
      }
    }
    data: {},
  },
});
```
## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.4
- Node.js version: v12.14.1

**Comment by anton62k** [comment]
Hi, I have such problem. Here what I found.

If we create the field as String (not Object) it works.

`data: '{ "version": 1 }'`

and then findOne / findMany returns the field as String too: `data: '{ "version": 1 }'`
I think the problem is related to the typescript type.

Is it expected behaviour when we should create and get the field as String instead of Object?

**Comment by hugohammarstrom** [comment]
This seems to be fixed in the latest release so closing this issue
