### ISSUE TITLE
Binary targets for FreeBSD in Beta4 no longer working

### ISSUE THREAD

**Issue by jaredwolff** [prisma/prisma#2357]
## Bug description

Previously an environment variable could be set to point to a binary compiled for FreeBSD. Like so:

`export PRISMA_QUERY_ENGINE_BINARY=/usr/home/downloads/bin/query-engine`

Now, with Beta 4 I get the following error:

```
Warning Precompiled binaries are not available for freebsd.
Warning Precompiled binaries are not available for freebsd.
Error: Unknown binaryTargets freebsd
```

## How to reproduce

Here is the simple Bash script I'm running on FreeBSD 12.1:

```
#!/bin/sh
export PRISMA_QUERY_ENGINE_BINARY=/usr/home/downloads/bin/query-engine
export PRISMA_MIGRATION_ENGINE_BINARY=/usr/home/downloads/bin/migration-engine
export PRISMA_INTROSPECTION_ENGINE_BINARY=/usr/home/downloads/bin/introspection-engine
cd /usr/home/downloads/
prisma generate
```

## Expected behavior

I expect the CLI is able to compile.

## Prisma information

All 2.0-Beta4

## Environment & setup

- OS: FreeBSD 12.1
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.4
- Node.js version: v13.3.0
- Query engine: afd294205618b1c825b013ba6f5a6ebe4aa4a514

```
yarn global list
yarn global v1.19.1
info "@prisma/cli@2.0.0-beta.4" has binaries:
   - prisma
   - prisma2
```

**Comment by pantharshit00** [comment]
I can confirm this issue: 

Version used:
```
Warning Precompiled binaries are not available for freebsd.
Warning Precompiled binaries are not available for freebsd.
@prisma/cli          : 2.0.0-alpha.1188
Current platform     : freebsd
Query Engine         : query-engine fc45fde2be3f39a089ade64c5c480b7ac30af461 (at /home/harshit/test/query-engine, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : migration-engine-cli fc45fde2be3f39a089ade64c5c480b7ac30af461 (at /home/harshit/test/migration-engine, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine : introspection-core fc45fde2be3f39a089ade64c5c480b7ac30af461 (at /home/harshit/test/introspection-engine, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
```

```
FreeBSD freebsd-s-1vcpu-1gb-blr1-01 12.1-RELEASE-p2 FreeBSD 12.1-RELEASE-p2 GENERIC  amd64
```

Internal note: I have left the setup that I used to reproduce this in digitalocean so that we can easily reproduce it again while fixing this without having to spin up a freebsd vm again.

**Comment by Jolg42** [comment]
Thanks a lot for reporting :pray:

This issue is fixed in the latest alpha version of `@prisma/cli` 2.0.0-alpha.1196

You can try it out with `npm i -g @prisma/cli@alpha`.
