### ISSUE TITLE
You are able to add fields of type ID

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2358]
# Bug Report

**Current behavior**

You can deploy this datamodel:

```graphql
type User {
  id: ID! @unique
  name: String!
  test: ID! @unique
  test2: ID!
}

```

But then, you cannot create a user because `test` and `test2` cannot be set with `createUser` and are also not autogenerated.

**Expected behavior?**

* either: You are not able to deploy fields of type `ID`, `ID!`, `ID @unique`, `ID! @unique`. Instead, you should be prompted to use `String` or `Int` instead.
* or: You can deploy these fields (as of now), and _also_ are able to set them with `createUser` or they are autogenerated

**Comment by mavilein** [comment]
I just tried this and i can actually set those fields successfully in a create mutation. Therefore i am closing this now. Will reopen if this turns out to be the wrong thing.
