### ISSUE TITLE
Transactions for multiple write-operations

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#2358]
**TLDR**: Have a way to run multiple write-operations, if one of them fails, all is rolled back

**Longer version**:
The Prisma Client API should provide a way to send multiple write-operations within the same query. The result of the request can be one of two cases:

- All write-operations succeeded
- No write-operations succeeded

Here is what a possible API for this feature could look like:

```ts
const write1 = prisma.user.create()
const write2 = prisma.order.update()

await prisma.transaction([write1, write2])
```

Note that this feature is not the same as [long-running transactions where the submitted mutations _depend on each other_](https://github.com/prisma/prisma/issues/1844).

**Comment by schickling** [comment]
Closing in favor of https://github.com/prisma/prisma-client-js/issues/667

**Comment by janpio** [comment]
Ping @nikolasburk about a comment that was posted in the replacing issue: https://github.com/prisma/prisma-client-js/issues/667#issuecomment-643750802
