### ISSUE TITLE
Next.js app build fails when using Prisma with DB driver in Server Action

### ISSUE THREAD

**Issue by nzws** [prisma/prisma#23600]
### Bug description

When building a Next.js application using Prisma on the edge runtime with the Database driver, the build fails with the following error. This problem seems to occur when using Prisma client on the server action imported by the client component. Also, this problem did not occur with Prisma v5.10.2 (in Early Access), and occurred with v5.11.0.

```
Failed to compile.

app/page.js from Terser
  x await isn't allowed in non-async function
       ,-[26410:1]
 26410 | /* harmony export */ __webpack_require__.d(__webpack_exports__, {
 26411 | /* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
 26412 | /* harmony export */ });
 26413 | /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ((await Promise.resolve(/* import() */).then(__webpack_require__.t.bind(__webpack_require__, 9737, 23))).default);
       :                                                                         ^^^^^^^
 26414 | 
 26415 | /***/ }),
       `----

Caused by:
    0: failed to parse input file
    1: Syntax Error
Error: 
  x await isn't allowed in non-async function
       ,-[26410:1]
 26410 | /* harmony export */ __webpack_require__.d(__webpack_exports__, {
 26411 | /* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
 26412 | /* harmony export */ });
 26413 | /* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ((await Promise.resolve(/* import() */).then(__webpack_require__.t.bind(__webpack_require__, 9737, 23))).default);
       :                                                                         ^^^^^^^
 26414 | 
 26415 | /***/ }),
       `----

Caused by:
    0: failed to parse input file
    1: Syntax Error


> Build failed because of webpack errors
```

### How to reproduce

1. `git clone https://github.com/nzws/prisma-with-nextjs-edge-import-problem-repro`
2. `cd prisma-with-nextjs-edge-import-problem-repro`
3. `yarn install`
4. `yarn build`
5. See error

### Expected behavior

The build passes normally and the application can run.

### Prisma information

I created a repository that can reproduce this issue: https://github.com/nzws/prisma-with-nextjs-edge-import-problem-repro (https://github.com/nzws/prisma-with-nextjs-edge-import-problem-repro/commit/cc513a74a2fc5235409db82e46c51ddf84be4b07)

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

```ts
// ./app/lib/prisma.ts

import { Pool } from "@neondatabase/serverless";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "@prisma/client";

export function createPrismaClient() {
  const neon = new Pool({ connectionString: process.env.DATABASE_URL });
  const adapter = new PrismaNeon(neon);
  const prisma = new PrismaClient({ adapter: adapter });

  return prisma;
}
```

```ts
// ./app/actions.ts

"use server";

import { createPrismaClient } from "./lib/prisma";

export async function onCreate() {
  const prisma = createPrismaClient();

  await prisma.user.create({
    data: {
      email: "john@example.com",
      name: "John Doe",
    },
  });
}
```

```ts
// ./app/client-component.tsx: imported by page.tsx

"use client";

import { onCreate } from "./actions";

export function ClientComponent() {
  const handleCreate = () => {
    void (async () => {
      await onCreate();
    })();
  };

  return (
    <div>
      <h1>Hello, World!</h1>

      <button onClick={handleCreate}>Create User</button>
    </div>
  );
}
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.10.0

### Prisma Version

```
prisma                  : 5.11.0
@prisma/client          : 5.11.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine efd2449663b3d73d637ea1fd226bafbcf45b3102 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli efd2449663b3d73d637ea1fd226bafbcf45b3102 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.11.0-15.efd2449663b3d73d637ea1fd226bafbcf45b3102
Default Engines Hash    : efd2449663b3d73d637ea1fd226bafbcf45b3102
Studio                  : 0.499.0
Preview Features        : driverAdapters
```

**Comment by nzws** [comment]
The top-level-await used by the wasm-worker-loader seems to be causing problems. https://github.com/prisma/prisma/blob/0c29ecf2e5f2543bc72d3bbee38d32e130d7727c/packages/client/src/generation/generateClient.ts#L190-L191

I have not submitted a pull request because I cannot evaluate the impact of this fix, but the following patch to the Prisma client generator builds successfully.

```patch
diff --git a/generator-build/index.js b/generator-build/index.js
index c66a69ee7783e69352da18aa5f0ac2ee28bc76cd..68b6c11fd61a9c663bdf9aad5359d7a2a4c6a83c 100644
--- a/generator-build/index.js
+++ b/generator-build/index.js
@@ -16644,7 +16644,7 @@ function buildQueryEngineWasmModule(wasm, copyEngine, runtimeNameJs) {
     return `config.engineWasm = {
   getRuntime: () => require('./query_engine_bg.js'),
   getQueryEngineWasmModule: async () => {
-    return (await import('#wasm-engine-loader')).default
+    return (await (await import('#wasm-engine-loader')).default).default
   }
 }`;
   }
@@ -18320,8 +18320,8 @@ async function buildClient({
   if (generator.previewFeatures.includes("driverAdapters")) {
     fileMap["default.js"] = await JS(trampolineTsClient);
     fileMap["default.d.ts"] = await TS(trampolineTsClient);
-    fileMap["wasm-worker-loader.js"] = `export default (await import('./query_engine_bg.wasm')).default`;
-    fileMap["wasm-edge-light-loader.js"] = `export default (await import('./query_engine_bg.wasm?module')).default`;
+    fileMap["wasm-worker-loader.js"] = `export default import('./query_engine_bg.wasm')`;
+    fileMap["wasm-edge-light-loader.js"] = `export default import('./query_engine_bg.wasm?module')`;
     pkgJson["browser"] = "default.js";
     pkgJson["imports"] = {
       // when `import('#wasm-engine-loader')` is called, it will be resolved to the correct file
```

**Comment by WoetDev** [comment]
I believe I'm having the same issue when trying to run Prisma + Neon Serverless Driver from the edge runtime, I'm receiving the error:
```
SyntaxError: Unexpected identifier 'Promise'
    at (action-browser)/./node_modules/.prisma/client/wasm-edge-light-loader.js
    at __webpack_require__
```

And I think this post on Stackoverflow describes the same issue as well: https://stackoverflow.com/questions/78192413/next-js-application-with-prisma-orm-and-neon-datasource/78213174#78213174

**Comment by smorimoto** [comment]
Same issue here.

**Comment by samtgarson** [comment]
I've been receiving this as well, but only when the Edge runtime is enabled in Next.

The fact that this works in the Nodejs runtime (for me), and that other "top level awaits" (unrelated to Prisma) also throw an error when used in the Edge runtime suggests that this is a Next.js issue, rather than a Prisma one?

(although if the patch works, it'd be great to get it in in the meantime)

**Comment by DannyNemer** [comment]
We are having the same issue.

**Comment by vegandiet705** [comment]
Hello, I'm also having this problem since I updated from Next 14.1.4 to 14.2.1. My setup is pretty similar to @DannyNemer .  The problem only appears in Edge runtime.

**Comment by morgs32** [comment]
There's a PR to fix this: https://github.com/prisma/prisma/pull/23754

You can resolve it for now by patching `@prisma/client`. I used pnpm so `pnpm patch @prisma/client`. Then make these changes: https://github.com/prisma/prisma/pull/23754/files

**Comment by jkomyno** [comment]
@nzws I confirm that using the `5.14.0-integration-static-wasm-worker-loader.5` version of Prisma (not released officially yet), I can build and run [your project](https://github.com/nzws/prisma-with-nextjs-edge-import-problem-repro).

Can you please try as well? @vegandiet705 @morgs32 @DannyNemer 
Thank you!

**Comment by nzws** [comment]
Thank you for the response. I checked that version, but I encountered the following error in the calling Prisma function:

```
 ⨯ ReferenceError: wasm_262ccad897196f9ab2ade3f9f1444a4c7ab39a50 is not defined
    at __webpack_require__ (/Users/nzws/ghq/github.com/nzws/prisma-with-nextjs-edge-import-problem-repro/.next/server/edge-runtime-webpack.js:37:33)
    at fn (/Users/nzws/ghq/github.com/nzws/prisma-with-nextjs-edge-import-problem-repro/.next/server/edge-runtime-webpack.js:318:21)
    at __webpack_require__.t (/Users/nzws/ghq/github.com/nzws/prisma-with-nextjs-edge-import-problem-repro/.next/server/edge-runtime-webpack.js:115:38)
digest: "3648476947"
```

It seems different error, I don't know where this problem from.

(When creating the sample repository, I made an incorrect implementation related to Next.js. [It has been fixed now.](https://github.com/nzws/prisma-with-nextjs-edge-import-problem-repro/commit/7c34ddfa8ec12701dce0406734c7f448f1311f42) Sorry about that.)

**Comment by vegandiet705** [comment]
[jkomyno](https://github.com/jkomyno) It works for me as well, thanks. Hope it gets in an official release soon

**Comment by jkomyno** [comment]
Hey, I'm back at this issue again!
@vegandiet705, great to hear that such version works for you. Unfortunately, that fixed some problems but caused some others in edge cases, as reported by @nzws.

May you please another new unofficial version of Prisma, and report back if it keeps working for your scenario? `5.15.0-integration-client-dynamic-wasm-imports.1`

You can quickly install it via:

```sh
pnpm add -D prisma@5.15.0-integration-client-dynamic-wasm-imports.1;
pnpm update "@prisma/*" 5.15.0-integration-client-dynamic-wasm-imports.1
```

(please double check that `prisma generate` has run before retrying).
Thanks!

cc @morgs32

**Comment by jkomyno** [comment]
Closed via https://github.com/prisma/prisma/pull/24312.
