### ISSUE TITLE
Record resolving in vcs system

### ISSUE THREAD

**Issue by corporal9736** [prisma/prisma#23612]
## Problem

I have multiple databases initialized at the same baseline state (with docker, used for ci&test). If I want to correctly apply migrations after baseline, as I understand, I need to run `npx prisma migrate resolve --applied 0_init` for every database.

## Suggested solution

Based on the assumption that all database should be in the same state, can we just add something like "applied migrations" in migration_lock.toml, so that resovling can be recorded in vcs like git and easily applied among different databases?

**Comment by janpio** [comment]
Ongoing discussion: https://github.com/prisma/prisma/discussions/23610 Please don't create both discussion and issue.
