### ISSUE TITLE
Prisma CLI is throwing segmentation fault with node 14

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#2361]
## Bug description
Prisma CLI is throwing Segmentation fault when I try running it with node 14. 
![image](https://user-images.githubusercontent.com/22195362/80975089-48948c00-8e3f-11ea-8567-bb1dee67863d.png)

I further investigated this and looks like our download script is failing:

```
╰─ npm install -g @prisma/cli                                                                                             ─╯

> @prisma/cli@2.0.0-beta.4 preinstall /Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli
> node preinstall/index.js

  preinstall { installedGlobally: null } +0ms
/Users/harshit/.nvm/versions/node/v14.1.0/bin/prisma -> /Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli/build/index.js
/Users/harshit/.nvm/versions/node/v14.1.0/bin/prisma2 -> /Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli/build/index.js

> @prisma/cli@2.0.0-beta.4 install /Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli
> node download-build/index.js

  prisma:download TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1588600217460)
  prisma:download     at Object.writeFileSync (fs.js:1380:5)
  prisma:download     at createLockFile (/Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli/download-build/index.js:1:56155)
  prisma:download     at main (/Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli/download-build/index.js:1:55861)
  prisma:download     at Object.197 (/Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli/download-build/index.js:1:56314)
  prisma:download     at __webpack_require__ (/Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli/download-build/index.js:1:154)
  prisma:download     at startup (/Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli/download-build/index.js:1:291)
  prisma:download     at module.exports.3 (/Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli/download-build/index.js:1:346)
  prisma:download     at Object.<anonymous> (/Users/harshit/.nvm/versions/node/v14.1.0/lib/node_modules/@prisma/cli/download-build/index.js:1:356)
  prisma:download     at Module._compile (internal/modules/cjs/loader.js:1176:30)
  prisma:download     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10) +0ms
+ @prisma/cli@2.0.0-beta.4
updated 1 package in 0.517s`
```

I narrowed down this error to https://github.com/prisma/prisma/blob/54e8f9e4bb6ad3d9afbc64ca1e47b239de74b463/src/packages/cli/scripts/download.js#L44 call. The API indeed got a change in version 14:
![image](https://user-images.githubusercontent.com/22195362/80973956-ae801400-8e3d-11ea-9636-61f86f30c8b7.png)

So now node doesn't automatically convert number into string which `Date.now()` returns.

## How to reproduce

1. Install node 14
2. Run `npm install -g @prisma/cli` to install Prisma CLI globally
3. Run `prisma -v`

## Expected behavior

Prisma CLI should not return segmentation fault

## Environment & setup

- OS: MacOS 10.15.4
- Database: Postgresql
- Prisma version: 
- Node.js version: 14.1.0

**Comment by Jolg42** [comment]
@pantharshit00 now I get `DEBUG="*" npm i -g @prisma/…' terminated by signal SIGSEGV (Address boundary error)`

With `env DEBUG="*" npm i -g @prisma/cli@2.0.0-alpha.1184` v14.1.0.

**Comment by Jolg42** [comment]
It looks like the `terminated by signal SIGSEGV (Address boundary error)` is because Node 14 has a bug 🙈

**Comment by pantharshit00** [comment]
Yes, looks like segfault is actually coming from nodejs

**Comment by Jolg42** [comment]
So we added a workaround for this but the underlying bug in Node still exists 
I tried to get a stack trace but nothing worked 🤷‍♂️ 

So the easiest reproduction so far is
``` 
mkdir repro-node-14
cd repro-node-14
node -v # should be v14 (for me v14.1.0)
npm init -y
npm i @prisma/sdk@2.0.0-alpha.1185
# Sometimes you have to repeat the install 🤷‍♂️ 
npm i @prisma/sdk@2.0.0-alpha.1185
npm i @prisma/sdk@2.0.0-alpha.1185
```

Output
```
> @prisma/sdk@2.0.0-alpha.1185 postinstall /Users/j42/Dev/repro/node-SIGSEGV-ddownload/node_modules/@prisma/sdk
> node scripts/download.js

version: f401775ef1c681c705db8fd8d6cecaa5a4eb44fd
fish: 'npm i @prisma/sdk@2.0.0-alpha.1…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by Jolg42** [comment]
Related issue (same? SIGSEGV)
https://github.com/prisma/prisma/issues/1819

**Comment by pantharshit00** [comment]
> Related issue (same? SIGSEGV) #1819

No, that issue was tracking Redwood segfault issue. @AhmedElywa reported the segfault in that issue thinking it was related but it is a separate issue so I opened this one.

**Comment by janpio** [comment]
Do we have an issue that tracks the Node 14 problem on our side so we can close it when Node fixed it? Do we have a node issue to point people to?

**Comment by timsuchanek** [comment]
https://github.com/nodejs/node/issues/33263

**Comment by lifedup** [comment]
I ran into this problem today.  It worked with node 18 versions before 18.1.0. However, it started throwing this error again today with node v18.1.0.   I downgraded to LTS 16.15.0 using `nvm` (`nvm use v16`), and it works again.

**Comment by janpio** [comment]
We have tests running with Node `18.2.0` - and passing - so if you have a way to reproduce this, please open a new issue so we can investigate. Something not working is problematic and should be looked at.
