### ISSUE TITLE
In Field Relation same Table

### ISSUE THREAD

**Issue by Daniel1228** [prisma/prisma#23632]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v20.11.0           | 
| OS              | darwin-arm64       |
| Prisma Client   | 5.11.0             |
| Query Engine    | efd2449663b3d73d637ea1fd226bafbcf45b3102|
| Database        | postgresql         |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /Users/jota/dev/Lummy/medidatos/.env
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from /Users/jota/dev/Lummy/medidatos/.env
prisma:client dirname /Users/danielmontanez/dev/Lummy/medidatos/generated/prisma
prisma:client relativePath ../../prisma
prisma:client cwd /Users/jota/dev/Lummy/medidatos/prisma
prisma:client clientVersion 5.11.0
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath /Users/jota/dev/Lummy/medidatos/generated/prisma/libquery_engine-darwin-arm64.dylib.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending req

**Comment by Druue** [comment]
Hey @Daniel1228,

Could you please provide us with your Prisma Schema (or a subset of it), the query that led to your Prisma client crashing, and the exact error message? I don't see any error messages in the logs in your post.

We won't be able to reproduce your issue without this information, unfortunately.
Thank you 🙏

**Comment by SevInf** [comment]
Hey @Daniel1228  ,

Did you get a chance to have a look at my colleagues comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏
