### ISSUE TITLE
Uncaught Error: PrismaClientValidationError: PrismaClient failed to initialize because it wasn't configured to run in this environment (Cloudflare Workers).

### ISSUE THREAD

**Issue by cayblood** [prisma/prisma#23644]
### Bug description

I've created a simple Cloudflare worker trying to get a remix app to connect with a supabase db using Prisma ORM. I'm running prisma 5.11.0. I've followed the Cloudflare steps documented [here](https://www.prisma.io/docs/orm/prisma-client/deployment/edge/deploy-to-cloudflare#postgresql-traditional). My schema file and client exports are shared below.

When I run `pnpx wrangler dev`, I get this:

```
 WARN  2 deprecated subdependencies found: rollup-plugin-inject@3.0.2, sourcemap-codec@1.4.8
Packages: +74
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 99, reused 74, downloaded 0, added 74, done
 ⛅️ wrangler 3.39.0
-------------------
▲ [WARNING] Enabling Node.js compatibility mode for built-ins and globals. This is experimental and has serious tradeoffs. Please see https://github.com/ionic-team/rollup-plugin-node-polyfills/ for more details.


Using vars defined in .dev.vars
Your worker has access to the following bindings:
- Vars:
  - SOME_VAR: "hello"
  - DATABASE_URL: "(hidden)"
⎔ Starting local server...
[wrangler:inf] Ready on http://localhost:8787
✘ [ERROR] service core:user:crescendo: Uncaught Error: PrismaClientValidationError: PrismaClient failed to initialize because it wasn't configured to run in this environment (Cloudflare Workers).

  In order to run Prisma Client in an edge runtime, you will need to configure one of the following
  options:
  - Enable Driver Adapters: https://pris.ly/d/driver-adapters
  - Enable Accelerate: https://pris.ly/d/accelerate
    at null.<anonymous> (server.js:49351:15) in _i
    at null.<anonymous> (server.js:50497:1791) in t
    at null.<anonymous> (server.js:53016:14)


✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

It is as though it's not actually using `driverAdapters`, even though it is being told to. Any suggestions would be greatly appreciated.

### How to reproduce

Reproduction steps listed above are sufficient.

### Expected behavior

I expect wrangler dev not to report a PrismaClientValidationError.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

```ts
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const connectionString = `${process.env.DATABASE_URL}`

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

export { prisma };
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 20.11.1

### Prisma Version

```
5.11.0
```

**Comment by cayblood** [comment]
Further investigation seems to indicate that this is a problem with how vite tries to bundle the node-postgres (`pg`) library.

**Comment by cayblood** [comment]
I've managed to get further while troubleshooting this error, to the point where I think it would be best to close this issue, as I don't believe it is prisma-related.

**Comment by janpio** [comment]
Can you share how you "solved" the problem for anyone reading this in the future?

**Comment by kiransilwal1** [comment]
Oops! Me having the same issue and can't solve it since 4 hours :(

**Comment by space1worm** [comment]
Have same issue

**Comment by ayush-goyal** [comment]
+1, do you have any fix?
