### ISSUE TITLE
Connecting to database via windows integrated security

### ISSUE THREAD

**Issue by mmilardic** [prisma/prisma#23647]
Hey! I moved this to issues in hope that someone could steer me in the right direction. 😄 

### Discussed in https://github.com/prisma/prisma/discussions/23614

<div type='discussions-op-text'>

<sup>Originally posted by **mmilardic** March 25, 2024</sup>
### Question

I'm trying to connect to our database with the following options:
```
datasource db {
  provider = "sqlserver"
  url      = "sqlserver://serverName:port;integratedSecurity=true;trustServerCertificate=true;encrypt=true;"
}
```

I'm getting:
`Error: Schema engine error:
Performing a TLS handshake
Trusting the server certificate without validation.
TLS handshake successful
Login failed for user ''.
[libs/user-facing-errors/src/quaint.rs:125:18] internal error: entered unreachable code
`

It is a SQL Server 15 (2019)

I'm on macOs and I have a Kerberos ticket.

I have no problems connecting to the DB server via Azure Data Explorer and TypeOrm .

TypeOrm using the following options:
` type: 'mssql',
  host: db.host,
  port: db.port,
  database: db.database,
  authentication: {
      type: 'ntlm',
      options: {
          userName: db.username,
          password: db.password,
          domain: db.domain,
      },
  },`

### How to reproduce (optional)

1. Create schema.prisma with the minimum requirements
2. Run: `a) npx prisma generate, b) npx prisma migrate dev`
3. See error:
`Error: Schema engine error:
Performing a TLS handshake
Trusting the server certificate without validation.
TLS handshake successful
Login failed for user ''.
[libs/user-facing-errors/src/quaint.rs:125:18] internal error: entered unreachable code
`

### Expected behavior (optional)

Should connect to the DB

### Information about Prisma Schema, Client Queries and Environment (optional)

```prisma
`generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlserver"
  url      = "sqlserver://serverName:port;integratedSecurity=true;trustServerCertificate=true;encrypt=true;"
}`
```

- OS: macOS
- Database: SQL Server 15 (2019)
- Node.js version: 20.9.0
- Prisma version: 5.11.0</div>

**Comment by janpio** [comment]
Please don't just open an issue for an active discussion. If the problem can not be resolved in the discussion, you will be told to open a feature or bug request issue. (Having the same problem in two places will just waste our time and focus by having multiple people trying to help you solve the same problem.)
