### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by zreiss** [prisma/prisma#23654]
Hi Prisma Team%21 My Prisma Client just crashed. This is the report%3A%0A%23%23 Versions%0A%0A%7C Name            %7C Version            %7C%0A%7C-----------------%7C--------------------%7C%0A%7C Node            %7C v20.11.0           %7C %0A%7C OS              %7C debian-openssl-3.0.x%7C%0A%7C Prisma Client   %7C 5.11.0             %7C%0A%7C Query Engine    %7C efd2449663b3d73d637ea1fd226bafbcf45b3102%7C%0A%7C Database        %7C mysql              %7C%0A%0A%0A%0A%23%23 Logs%0A%60%60%60%0Aprisma%3AtryLoadEnv Environment variables not found at null%0Aprisma%3AtryLoadEnv Environment variables loaded from %2Fhome%2Fyakov%2Fdev%2Fplay%2Fimpecca-ratings%2F.env%0Aprisma%3Aclient checkPlatformCaching%3Apostinstall false%0Aprisma%3Aclient checkPlatformCaching%3AciName %0Aprisma%3AtryLoadEnv Environment variables not found at null%0Aprisma%3AtryLoadEnv Environment variables loaded from %2Fhome%2Fyakov%2Fdev%2Fplay%2Fimpecca-ratings%2F.env%0Aprisma%3Aclient dirname %2Fhome%2Fyakov%2Fdev%2Fplay%2Fimpecca-ratings%2Fnode_modules%2F.prisma%2Fclient%0Aprisma%3Aclient relativePath ..%2F..%2F..%2Fsrc%2Fprisma%0Aprisma%3Aclient cwd %2Fhome%2Fyakov%2Fdev%2Fplay%2Fimpecca-ratings%2Fsrc%2Fprisma%0Aprisma%3Aclient clientVersion 5.11.0%0Aprisma%3Aclient%3AlibraryEngine internalSetup%0Aprisma%3Aclient checkPlatformCaching%3Apostinstall false%0Aprisma%3Aclient checkPlatformCaching%3AciName %0Aprisma%3AtryLoadEnv Environment variables not found at null%0Aprisma%3AtryLoadEnv Environment variables loaded from %2Fhome%2Fyakov%2Fdev%2

**Comment by jkomyno** [comment]
Hi @zreiss, unfortunately we cannot act on unreproducible issues like this.
Please open a new issue filling in details using [this bug report template](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml). Thank you!
