### ISSUE TITLE
 npx prisma generate  403 Forbidden

### ISSUE THREAD

**Issue by luozhang002** [prisma/prisma#23667]
### Bug description

Failed to fetch sha256 checksum at https://binaries.prisma.sh/all_commits/5a9203d0590c951969e85a7d07215503f4672eb9/darwin-arm64/libquery_engine.dylib.node.gz.sha256 - 403 Forbidden

### How to reproduce

 npx prisma generate 

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
5.10.2
```

**Comment by janpio** [comment]
Download is working fine for me (and most users).

Can you download this file in your browser or does it also fail? What message are you getting, if it does?

**Comment by Jolg42** [comment]
I guess this works now? I'm closing this since it's old, let us know if you still experience this problem.

**Comment by jonnysamps** [comment]
This is happening again today with: https://binaries.prisma.sh/all_commits/605197351a3c8bdd595af2d2a9bc3025bca48ea2/linux-musl-arm64-openssl-3.0.x/schema-engine.sha256

**Comment by theturtle32** [comment]
Getting the same thing today with https://binaries.prisma.sh/all_commits/8047c96bbd92db98a2abc7c9323ce77c02c89dbc/debian-openssl-3.0.x/schema-engine.sha256

**Comment by nsheaps** [comment]
That is being tracked here: https://github.com/prisma/prisma/issues/27700
The devs are aware: https://x.com/MarcHessDev/status/1946280102431486152

**Comment by theturtle32** [comment]
Looks like their AWS S3 bucket is most likely misconfigured.

**Comment by fearedbliss** [comment]
Same here: https://binaries.prisma.sh/all_commits/acc0b9dd43eb689cbd20c9470515d719db10d0b0/linux-musl-arm64-openssl-3.0.x/libquery_engine.so.node.gz.sha256

I also figured that was the case @theturtle32 since the error happened between a deployment between our `develop` to `production` environment (and it had passed CI in `develop`).
