### ISSUE TITLE
extends->result->compute dones  not support async

### ISSUE THREAD

**Issue by Marshal-S** [prisma/prisma#23683]
example: 
{
        result: {
            file: {
                url: {
                    async compute(file) {
                        return await minio.presignedUrl(file.filename)
                    },
                },
            },
        },
    }

**Comment by jkomyno** [comment]
Hello @Marshal-S, unfortunately we cannot act on unreproducible issues without context like this one.
Please open a new issue filling in details using [this bug report template](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml). Thank you!
