### ISSUE TITLE
Remove or change `This is the 10th instance of Prisma Client being started. Make sure this is intentional.` warning

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#23736]
The warning is not as important anymore as when we ran the query engine as a binary, potentially not relevant anymore at all. 
Let's figure that out and remove or change it.

Relevant code:
- https://github.com/search?q=repo%3Aprisma%2Fprisma+%22This+is+the+10th+instance+of+Prisma+Client%22&type=code
- https://github.com/prisma/prisma/blob/1a4f3618f7381ece356667b11af579ce81248d74/packages/client/src/runtime/core/engines/library/LibraryEngine.ts#L113

**Comment by jkomyno** [comment]
This issue follows up https://github.com/prisma/team-orm/issues/1094

**Comment by Saeid-Za** [comment]
Isn't there an option to enable this warning? This was useful for debugging the connection leak in my case when my connection handler wasn't working properly.
