### ISSUE TITLE
Spawn E2BIG

### ISSUE THREAD

**Issue by WellFail** [prisma/prisma#2373]
I am using Prisma with nexus and nexus Prisma and sometimes when I create many requests at the one time to my endpoint on lambda I can get that problem:

`Invalid `prisma.post.findMany()` invocation in↵/var/task/node_modules/nexus-prisma/dist/builder.js:180:97↵↵spawn E2BIG`

This problem does not depend on the scheme or the number of models and fields in it, but it exactly depends on the number of requests at the same time executed to my endpoint.

## Environment & setup

- OS: AWS Lambda
- Database: PostgreSQL
- Prisma version: prisma: 2.0.0-beta.4, nexus: 0.12.0, nexus-prisma: 0.11.1
- Node.js version: 12

**Comment by pantharshit00** [comment]
Hi @WellFail ,

Can you please share a reproduction of this inside of a git repository? Also, please make sure you are using the latest version of Prisma and nexus. Thanks!

**Comment by WellFail** [comment]
@pantharshit00 

https://github.com/WellFail/prisma-2373

I am update nexus and nexus-prisma to the latest versions, prisma 2.0.0-beta.4

This problem occurs with 2-3 simultaneous requests. Queries simply request all available fields. Sometimes such a problem is not observed at all.
I don’t even know what this behavior can be associated with.

**Comment by WellFail** [comment]
@pantharshit00 I have a small update about this issue. This problem manifests itself only with 10+ models in the circuit, although in theory this should not affect the query the fields of a particular model.

**Comment by pantharshit00** [comment]
Hey @WellFail, Can you please try this again with latest version of `nexus-prisma` and prisma

**Comment by WellFail** [comment]
Hi @pantharshit00, 

I updated the prisma to version 2.0.0-beta.5 and nexus-prisma to 0.13.0.
Despite this, the problem remained the same.

**Comment by WellFail** [comment]
@janpio 
Sure, I can share with you whats I did.

In my case, I need to have a query that returns the `dmmf` of the current server.
Code what I use very old and I think I can find better solution, but currently I have something like this:
```
           if (!process.env.ENGINE_PORT) {
              await photon.connect();
              //@ts-ignore
              process.env.ENGINE_PORT = photon.fetcher.prisma.engine.port;
            }
            
            dmmf = await new Promise((resolve, reject) => {
              http.get('http://localhost:'+ process.env.ENGINE_PORT + '/dmmf', (resp) => {
                let data = '';
                resp.on('data', (chunk) => { data += chunk; });
                resp.on('end', () => { resolve(data) });
              }).on("error", (err) => { reject(err) });
            })
```

My mistake was that I called `prisma.connect()` every request and after all this code I called `prisma.disconnect()`. Currently, I removed 'disconnect' and only invoke `connect()` only the first time.

**Comment by janpio** [comment]
That reproduction should be enough for us to figure out what is going on there and possibly fix it.

**Comment by WellFail** [comment]
@janpio 
Great, I updated my code in comment for reproduce the problem.

Also, would be nice to be able to get dmmf without such twists.

**Comment by pantharshit00** [comment]
You can get the dmmf using the Prisma SDK
```js
import { getDMMF } from '@prisma/sdk'
const dmmf = getDMMF()
```

Please note that this library is subject to change without any notice so use with your own discretion. 

You example deployment that you have shared is throwing a 403 for me when I am trying to query it. 

Can you please update the dependencies of this project to the latest and please try again. I see that you have used Prisma version `2.0.0` with nexus-prisma `0.14.0` but version `0.15.0` is the one which supports Prisma 2.0.0 so there might be a version conflict.

**Comment by WellFail** [comment]
Thanks!
I know about prisma/sdk, but in my case I can't use many dependencies.

My example deployment works fine for me.
![image](https://user-images.githubusercontent.com/46130993/85024301-9579bb00-b17e-11ea-8f08-5680a753f1dc.png)

I will try the updated nexus version, but I think that this problem does not depend by nexus.

**Comment by pantharshit00** [comment]
I think my IP is blocked:

**Comment by matthewmueller** [comment]
Hey @WellFail did you have a chance to upgrade nexus and try again?

**Comment by WellFail** [comment]
Hey @matthewmueller 
I was updated Prisma and nexus and I cannot reproduce this error. I think we can close this issue. 😃
