### ISSUE TITLE
Prisma does not recognize partial index at all and wants to recreate it everytime

### ISSUE THREAD

**Issue by jansedlon** [prisma/prisma#23734]
### Bug description

I have a table that has this index 
```prisma
@@index([postId, createdAt(sort: Desc)])
```

Which generates this migration
```sql
CREATE INDEX "PostComment_postId_createdAt_idx" ON "PostComment"("postId", "createdAt" DESC);
```

When I edit manually the migration to support partial (filtered) index like this
```sql
CREATE INDEX "PostComment_postId_createdAt_idx" ON "PostComment"("postId", "createdAt" DESC) WHERE "parentCommentId" IS NULL;
```
and then run the migration, Prisma won't recognize that the index exists and wants to recreate it again with a new migration, which fails, because it exists by then.

This is quite urgent since I cannot create an efficient index now.

### How to reproduce

Create table

```prisma
model PostLike {
  id       String @id @default(cuid())
  postId   String
  post     Post   @relation(fields: [postId], references: [id])
  memberId String
  member   Member @relation(fields: [memberId], references: [id])

  createdAt DateTime @default(now())

  @@index([postId, createdAt(sort: Desc)])
}
```
Create a new migration, don't apply it immediately and add this in line where index is created
```sql
WHERE "parentCommentId" IS NULL
```

Run `prisma migrate dev`

### Expected behavior

It should ignore the statement and recognize the index

### Prisma information

I'd rather not share my whole database schema :D 

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: 20

### Prisma Version

```
prisma                  : 5.12.0
@prisma/client          : 5.12.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.11.1
Query Engine (Node-API) : libquery-engine 473ed3124229e22d881cb7addf559799debae1ab (at node_modules/.pnpm/@prisma+engines@5.12.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 473ed3124229e22d881cb7addf559799debae1ab (at node_modules/.pnpm/@prisma+engines@5.12.0/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.12.0-21.473ed3124229e22d881cb7addf559799debae1ab
Default Engines Hash    : 473ed3124229e22d881cb7addf559799debae1ab
Studio                  : 0.499.0
```

**Comment by janpio** [comment]
If you change the migration to not be a normal index, you should also remove the `@@index` in Prisma schema.

This is because Prisma does not support partial indexes yet: https://github.com/prisma/prisma/issues/6974

**Comment by jansedlon** [comment]
Thank makes sense, sorry!
