### ISSUE TITLE
Add more filter possibilities to the single entity CRUD queries

### ISSUE THREAD

**Issue by MickaelOth** [prisma/prisma#2376]
## Problem
In some projects, I'm using workspaces. For some evident security reason, I'm using tokens to know in which workspace the user making a request is in. It could be great if it was possible to make single entity queries filterable, and not only on `UniqueInput`. For example, I would like to update a user, with his ID and his workspace to be sure that he has the rights to update it, with the following code, but actually it's not possible because workspace is not a `UniqueInput` type.
```js
const updateUser = await prisma.user.updateMany({
  data: {
    name: "Hey, I'm user 1 in workspace 2",
  },
  where: {
    id: 1,
    workspace: 2 // Found in token
  },
});
```

## Solution
Maybe it could be good to add, like the `@@unique` attribute in Prisma schema, a new attribute called `@@filter` or `@@filterable` (or if you've a better idea) which takes an array of filterable columns or just an attribute to the line in question, like so:

Example: 
```js
model User {
  id        Int       @default(autoincrement()) @id
  name      String

  workspace Workspace @filterable
  // or
  workspace Workspace
  @@filterable([workspace])
}

```

## Alternatives
Perhaps it could also be great to do it more generics and be able to filter whatever on a single entity query (findOne, update, upsert, delete).

**Comment by pantharshit00** [comment]
Internal note: https://prisma-company.slack.com/archives/CEYCG2MCN/p1588689822228800

**Comment by janpio** [comment]
I think this case is covered by this existing preview feature `extendedWhereUnique`: 

> From version 4.5.0, the generated type `UserWhereUniqueInput` on [where](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#where) exposes all fields on the model, not just unique fields.

https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#filter-on-non-unique-fields-with-userwhereuniqueinput

That should let you cover both your `id` and `workspace` in the `where` clause of any query.
