### ISSUE TITLE
"PrismaClient is not configured to run in Vercel Edge Functions or Edge Middleware." with extension in Next.js application

### ISSUE THREAD

**Issue by nucks** [prisma/prisma#23793]
### Bug description

Shows error: "Error: PrismaClient is not configured to run in Vercel Edge Functions or Edge Middleware. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters

If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report"

<img width="1289" alt="image" src="https://github.com/prisma/prisma/assets/18559697/edfdd531-f02d-4765-8093-22d30ec6952e">

### Expected behavior

It's expected that the page will load like normal and the hooks to be called when certain tables were updated or created. I also tried running this with Prisma Accelerate and Driver Adapters with no luck.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider          = "postgresql"
  url               = env("DATABASE") // uses connection pooling
  directUrl         = env("DATABASE_NON_POOLING") // uses a direct connection
  shadowDatabaseUrl = env("DATABASE_NON_POOLING") // used for migrations
}
```

```ts
import { PrismaClient } from "@prisma/client";

declare global {
  var prisma: PrismaClient | undefined;
}

const prisma =
  global.prisma ||
  new PrismaClient()
    .$extends({
      query: {
        conversation: {
          async create({ model, operation, args, query }) {
            const updatedX = await query(args);

            await updateCompletionPercentage(updatedX);

            return updatedX;
          },
          async update({ model, operation, args, query }) {
            const updatedX = await query(args);

            await updateCompletionPercentage(updatedX);

            return updatedX;
          },
        },
      },
    })

async function updateCompletionPercentage() {
  await prisma.x.findUnique({
    where: { id: id },
    include: {
      y: {
        select: {
          id: true,
          completionPercentage: true,
        },
      },
    },
  });
}

if (process.env.NODE_ENV === "development") global.prisma = prisma;

export default prisma;

```

### Environment & setup

- OS: `macOS`
- Database: `PostgreSQL`
- Node.js version: `18.18.2`

### Prisma Version

```
5.12.1
```

**Comment by janpio** [comment]
Can you please share a reproduction, optimally as a GitHub repository that we can try? There are many, many ways how this can go wrong and without your code we will have no way to figure it out. Thanks.

**Comment by nucks** [comment]
The bug was on my end. It was related to some middleware for a different set of routes that was causing the issue.

**Comment by itsHTK** [comment]
> The bug was on my end. It was related to some middleware for a different set of routes that was causing the issue.

Can you explain further on how you solved this issue?
