### ISSUE TITLE
For JSON columns in postres the prisma client returns a string instead of an object for that column when performing update operation

### ISSUE THREAD

**Issue by andreasvh-conceto** [prisma/prisma#23856]
### Bug description

When a json column in postgres is defined, the prisma client correctly returns for the json column an object on read operations, but returns a string on update operations for that column. This is not consistent and enforces the developer to execute `JSON.parse((await prisma.entity.update(...)).jsonprop)` just for update operations. For read operations it seems to be fine and returns an object.

### How to reproduce
1. Create a model with a json type column in postgres and create the prisma client
2. Perform an find operation on the entity and access the json property
3. Perform an update operation on the entity and access the json property of the returned entity
4. Compare the type of the json column. Find operations return an object, update operations return a string

### Expected behavior

Prisma returns an object type after read and also after update operation. Both operations should be consistent related to the json column and return an  object type.

### Prisma information

```prisma
model ExtractedDocument {
  id BigInt @id(map: "pk_extracted_doc") @default(autoincrement())
  document_body Json @db.Json

  @@map("extracted_document")
}
```

```ts
// returns for json are inconsistent. object in all cases is expected
// object
typeof (await prisma.extractedDocument.findFirst()).document_body
// string
typeof (await prisma.extractedDocument.update({where: {id:10}, data: {foo: "bar"}})).document_body
// string
typeof (await prisma.extractedDocument.update({where: {id:10}, data: JSON.stringify({foo: "bar"})})).document_body

```

### Environment & setup

- OS: macOS, Windows, Ubuntu-->
- Database: PostgreSQL ( on  my side version 15, but will be every version, where the json column datatype is supported)
- Node.js version: 18.20.1

### Prisma Version

```
prisma                  : 5.12.1
@prisma/client          : 5.12.1
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.20.1
Query Engine (Node-API) : libquery-engine 473ed3124229e22d881cb7addf559799debae1ab (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 473ed3124229e22d881cb7addf559799debae1ab (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.12.0-21.473ed3124229e22d881cb7addf559799debae1ab
Default Engines Hash    : 473ed3124229e22d881cb7addf559799debae1ab
Studio                  : 0.499.0

```

**Comment by andreasvh-conceto** [comment]
Hi @SevInf ,

i tried it again today and investigated the issue. It comes out, that the postgres db is supporting for the jsonb column a `'{}'` and also `'"{}"'`. Therefore i assume prisma is also supporting strings and also plain object `{ foo: "bar"}` and also `JSON.stringify({ foo: "bar"})` as a valid value when saving jsonb column . At the end our db client did not show the difference between `'{}'` and `'"{}"'`. It was displayed just as `{}`. And we saved both kind of formats in the database and did not saw any difference, when reading the values out - it was kind of random getting object or string type from the query. And since it was represented the same in the db client, we thought prisma can only be the issue (some caching or whatever). Therefore prisma did it absolutely correct - for jsonb column it reads  `'{}'`  as an object and `'"{}"'` as a string.

It was the db client and the display issue, which caused the issue. Sorry about the circumstances. 

This issue can be closed :)

**Comment by SevInf** [comment]
Thank you for getting back to use, I'll close the issue then!
