### ISSUE TITLE
`vitest`: Prisma 5.12.1 client has errors accessing postgress db when using with cloudflare workers and the new `{ previewFeatures = ["driverAdapters"] }`

### ISSUE THREAD

**Issue by alexdoan102** [prisma/prisma#23855]
### Bug description

Prisma 5.12.1 client has errors accessing postgress db when using with cloudflare workers and the new { previewFeatures = ["driverAdapters"] }.  All queries using the PrismaClient() will fail with error:

```
Cannot find module './query_engine_bg.js'
```
![Image](https://github.com/prisma/prisma/assets/183673/07bd2c23-eb9c-4a74-a424-43305505cc5e)

**NOTE:** the root cause of the bug is that there are 2 files: [query_engine_bg.js] & [query_engine_bg.wasm] that are missing from the directory [\node_modules.prisma\client]

_(if you copy the 2 missing files into this directory, then the PrismaClient() will work, and be able to query the database)_

### How to reproduce
1. create cloudflare project and use Prisma 5.12.1
2. Use the previewFeatures = ["driverAdapters"] 
3. use the PrismaClient and run a query:   
       await client.sponsor.findUnique({where: { id: 'c6861cb6-e9ad-47f6-a39c-170dd53ee2e2' },

### Expected behavior

you should be able to query the database with PrismaClient

### Prisma information
```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model sponsor{
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}

```

```
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
import pg from 'pg';

const { Pool } = pg; 

export const getPrismaClient = (databaseConfig: Config['database']): PrismaClient => {
	types.setTypeParser(types.builtins.NUMERIC, value => Number(value));
	const pool = new Pool({
		connectionString: databaseConfig.url,
	});
	const adapter = new PrismaPg(pool);
	return new PrismaClient({ adapter });
};

==========================================

const client = getPrismaClient(config.database);

describe('raw test1', () => {
	it('get Study for study_id: 9ecfbc52-c475-40a9-9a15-f91c4a64766e', async () => {
		const retrievedStudy = await client.sponsor.findUnique({
		 	where: { id: '9ecfbc52-c475-40a9-9a15-f91c4a64766e' },
		});

```

### Environment & setup

- OS: windows 10
- Database: [PostgreSQL]
- Node.js version: v18.16.0

### Prisma Version

```
prisma 5.12.1
@prisma/client 5.12.1
@prisma/adapter-pg  5.12.1

```

![image](https://github.com/prisma/prisma/assets/73307/f61942ba-ac8a-4cda-9abf-dc4c41be9207)

**Comment by alexdoan102** [comment]
**_NOTE: there are 2 related issues on why the 2 files:  [query_engine_bg.js] & [query_engine_bg.wasm] are missing from the directory [\node_modules\.prisma\client]_**

- https://github.com/prisma/prisma/issues/23600     ==> (same root cause these 2 files not found)
   ==> there is a potential fix here:  https://github.com/prisma/prisma/pull/23754

- https://github.com/unjs/unwasm/issues/21 ==> 
   ==> there is bug in the package [unwasm] that prisma uses 
        ==> there is an upcoming fix for this: https://github.com/unjs/unwasm/pull/24

**Comment by Jolg42** [comment]
Hi @alexdoan102 

Did you follow the instructions from https://www.prisma.io/docs/orm/prisma-client/deployment/edge/deploy-to-cloudflare#postgresql-traditional ?

For example, did you set `node_compat = true` in `wrangler.toml`? (see the [Cloudflare docs](https://developers.cloudflare.com/workers/wrangler/configuration/#add-polyfills-using-wrangler))

**Comment by Jolg42** [comment]
It looks like this happens during development here?
I'm thinking that this is only affecting development but not deploying, is that right?

I think you are using this https://blog.cloudflare.com/workers-vitest-integration?

**Comment by alexdoan102** [comment]
@Jolg42  yes., cloudflare/postgres was working using kysely orm and pg driver.
        ==> Im trying to switch to prisma on cloudlfare.   

yes. Im using vitest.
 But Im also using prisma seed with tsnode script.
    => this was working with native pg driver running locally (to see the database during dev)

 BOTH VITEST and Prisma-Seed-Tsnode-scripts are failing with same error.
  **_==> however if you copy the 2 missing files above, then it will work._**
        
        
**here is a small snippet of the [wrangler toml]*: 
name = "demoapi"
main = 'src/index.ts'
node_compat = true

**Comment by alexdoan102** [comment]
@Jolg42  i just deployed to cloudflare worker, and there is an error: (i dont have the specific error, but its uncaught error  because of the same low-levek PrismaClient error above.
 => essentially this proves the error happens in the deployed Cloudflare worker environment also.


![image](https://github.com/prisma/prisma/assets/73307/0a37d223-f558-4433-8d3d-386d495cb314)

**Comment by steebchen** [comment]
I'm deploying a NextJS app on CF pages with D1 and I'm running into the same issue (locally, haven't tested in prod).


```
 ⚠ ./node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/.prisma/client/wasm-edge-light-loader.js
The generated code contains 'async/await' because this module is using "topLevelAwait".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.

Import trace for requested module:
./node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/.prisma/client/wasm-edge-light-loader.js
./node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/.prisma/client/wasm.js
./node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/.prisma/client/default.js
./node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/@prisma/client/default.js
./lib/cf.ts
./actions/create.ts
```



```
Unhandled Runtime Error
Error: Unexpected identifier 'Promise'

Call Stack
(action-browser)/./node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/.prisma/client/wasm-edge-light-loader.js
/Users/steebchen/projects/polls/.next/server/app/page.js (4816:1)
Next.js
async Object.getQueryEngineWasmModule
node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/.prisma/client/wasm.js (169:1)
async eval
node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/@prisma/client/runtime/wasm.js (11:700)
async Object.loadLibrary
node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/@prisma/client/runtime/wasm.js (11:979)
async gt.loadEngine
node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/@prisma/client/runtime/wasm.js (11:3126)
async gt.instantiateLibrary
node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/@prisma/client/runtime/wasm.js (11:2713)
```

**Comment by leedavidcs** [comment]
@steebchen Thank you for posting this. This describes exactly what I am also experiencing (the same exact errors) on `prisma@5.12.1`, `@prisma/client@5.12.1`, `next@14.1.0`, `@cloudflare/workers-types@4.20240419.0` and `@cloudflare/next-on-pages@1`.

**Comment by steebchen** [comment]
@janpio You are right, I might have confused this one with another and posted a comment. Anyway I have created a new issue https://github.com/prisma/prisma/issues/23929 which also links to the reproduction repo https://github.com/steebchen/next-cf-prisma-d1.

**Comment by Jolg42** [comment]
@alexdoan102 Could you provide us a reproduction as a repository? That would help a lot.

Because I tried to reproduce this, but I only get this error:
```
Error: No such module "[...]/23855-vitest/hello-world/node_modules/.prisma/client/#wasm-engine-loader".
``` 
tracked in https://github.com/prisma/prisma/issues/23911

**Comment by alexdoan102** [comment]
@Jolg42   I found the problem.   

when the  -->  provider = "**postgresql**",  this works.    
     ==> (the 2 missing files are copied query_engine_bg.js ;query_engine_bg.wasm

when the  -->  provider = "**cockroachdb**",  this does NOT WORK. (missing 2 files.)
  ==> the root cause is in the [prisma\prisma-client\runtime] directory, you are missing [**query_engine_bg.cockroachdb.js**]
            _==> i'm, assuming it looks for the correct provider, and generates the 2 missing files._
                          => you need to copy [ query_engine_bg.postgresql.js], and create a duplicate file called [**query_engine_bg.cockroachdb.js**]
                        

![image](https://github.com/prisma/prisma/assets/73307/85fb55aa-d1f8-4ac8-870d-1b698681acca)


=====================================================

` 
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
`

**Comment by janpio** [comment]
> query_engine_bg.cockroachdb.js

This file does not exist. CockroachDB just uses the PostgreSQL one.

**Comment by alexdoan102** [comment]
@Jolg42 @janpio Ok.. so the problem is the "logic" for it to know to use PostgreSQL one.
 => if you change the provider = cockroachdb ==> the files wont get copied from the runtime folder.

**Comment by janpio** [comment]
How can we reproduce this? Can you provide us a repository with code and exact instructions what to do to get into this situation?

**Comment by alexdoan102** [comment]
@janpio  @Jolg42  you can use your own example: 
https://github.com/prisma/ecosystem-tests/tree/dev/driver-adapters-wasm/pg-cf-basic

change the provider to "cockroachdb", and the 2 missing files will not get produced

![image](https://github.com/prisma/prisma/assets/73307/9af52886-fcf9-452a-b809-5abd587c7415)

**Comment by alexdoan102** [comment]
i have tested with your example, and i can confirm that this is the issue.

**Comment by janpio** [comment]
Your original issue description contained `provider = "postgresql"` - was that a mistake then?
If so, can you please close this issue and just create a new one that focusses on describing the actual problem?
Then we should easily be able to reproduce this. Thanks!

**Comment by alexdoan102** [comment]
@janpio @Jolg42  as per your request, I am closing this ticket and i created new ticket: https://github.com/prisma/prisma/issues/24475

to be clear the provider = "postgresql" does work,

the provider = "cockroachdb" doe NOT work.
