### ISSUE TITLE
D1: `BigInt` not supported, but doesn't error in `schema.prisma`

### ISSUE THREAD

**Issue by lifeiscontent** [prisma/prisma#23865]
### Bug description

using the D1 adapter the SQL migration in this blog article swapping out Int for BigInt for ids generates invalid SQL

https://www.prisma.io/blog/build-applications-at-the-edge-with-prisma-orm-and-cloudflare-d1-preview

### Expected behavior

either show an error in prisma.schema or generate proper SQL migration

### Prisma information

all info is in blog post

### Environment & setup

- OS: MacOS
- Database: Sqlite + D1
- Node.js version: 20.12.2

### Prisma Version

```
5.12.1
```

**Comment by janpio** [comment]
Thanks for the issue @lifeiscontent, but I can not reproduce this. The following schema uses a `BigInt` as a normal field, or as the `@id` of the model, and I could successfully create a SQL migration and then apply it to a local D1:

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model BigIntTable1 {
  id Int @id @default(autoincrement())
  test BigInt
}

model BigIntTable2 {
  id BigInt @id @default(autoincrement())
  name  String?
}
```

The migrations look like this:
```sql
-- CreateTable
CREATE TABLE "BigIntTable1" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "test" BIGINT NOT NULL
);
```

```sql
-- CreateTable
CREATE TABLE "BigIntTable2" (
    "id" BIGINT NOT NULL PRIMARY KEY,
    "name" TEXT
);
```

Am I missing something?

**Comment by lifeiscontent** [comment]
@janpio when I tried to apply a migration to my D1 instance in production it failed.

**Comment by lifeiscontent** [comment]
I also noticed when apply migrations between local / remote I had to individually break each SQL statement into separate files

**Comment by janpio** [comment]
So applying the migrations created above to the remote D1 database should fail?

**Comment by janpio** [comment]
I tried again, and I could migrate the following Prisma schema both against a local and a remote D1 database:
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    BigInt  @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

That had created the following SQL migration:
```
-- CreateTable
CREATE TABLE "User" (
    "id" BIGINT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "name" TEXT
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
```

It could be applied with a simple `npx wrangler d1 migrations apply` as documented in the blog post.

What am I missing?

**Comment by janpio** [comment]
That being said, adding _data_ to this table with `BigInt` will indeed not work as the `id` column is not defined as `AUTOINCREMENT` when it is of type `Bigint`. This problem is known and tracked at https://github.com/prisma/prisma/issues/20449 and https://github.com/prisma/prisma/issues/13178.

But that does not match what you describe above, so I still want to figure out what is happening for you.

**Comment by Jolg42** [comment]
@lifeiscontent Did you get a chance to take a look at Jan's comment? It'd be helpful for us to move your issue forward.

**Comment by lifeiscontent** [comment]
@Jolg42 I've been on vacation, I plan to take a look once I'm back next week.

**Comment by SevInf** [comment]
Hey @lifeiscontent  ,

Do you have any update? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by fzn0x** [comment]
Hi @janpio  @Jolg42 

I tried the following model for SQLite for example:

```prisma
model Member {
  id              Int      @default(autoincrement()) @id
  code            String
  name            String
  penalizedAt     DateTime?
  createdAt       DateTime @default(now())
  updatedAt       DateTime @updatedAt
  borrowers       BorrowedBook[] @relation("getBorrowers")
}

model Book {
  id              Int @default(autoincrement()) @id
  code            String    
  title           String
  author          String?
  stock           BigInt @default(0)
  createdAt       DateTime @default(now())
  updatedAt       DateTime @updatedAt
  borrowers       BorrowedBook[] @relation("getBorrowedBooks")
}

// Many to Many
model BorrowedBook {
  id              BigInt      @id @default(autoincrement())
  borrowedAt      DateTime    @default(now())
  book Book[] @relation("getBorrowedBooks")
  member Member[] @relation("getBorrowers")
}
```

And try to do this:

```ts
const borrowed = await this.prisma.borrowedBook.create({
  data: {
    book: {
      connect: {
        id: bookId,
      },
    },
    member: {
      connect: {
        id: memberId,
      },
    },
  },
});
```

Expected: could create borrowedBook data and connect the book and member.
Actual: 
```sh
nInvalid `prisma.borrowedBook.create()` invocation:\n\n\nNull constraint violation on the fields: (`id`)
```

**Comment by fzn0x** [comment]
This only happens when you use BIGINT as datatype.

**Comment by lifeiscontent** [comment]
@fzn0x that's a good point, I had forgotten to include that as a part of the report

**Comment by Druue** [comment]
Hey folks, @fzn0x @lifeiscontent 

Looking at the schema and code snippet you provided @fzn0x, this seems to me to be the autoincrement bug that @janpio highlighted [here](https://github.com/prisma/prisma/issues/23865#issuecomment-2088099011).

The following schema
```prisma
model Member {
  id          Int            @id @default(autoincrement())
  code        String
  name        String
  penalizedAt DateTime?
  createdAt   DateTime       @default(now())
  updatedAt   DateTime       @updatedAt
  borrowers   BorrowedBook[] @relation("getBorrowers")
}

model Book {
  id        Int            @id @default(autoincrement())
  code      String
  title     String
  author    String?
  stock     BigInt         @default(0)
  createdAt DateTime       @default(now())
  updatedAt DateTime       @updatedAt
  borrowers BorrowedBook[] @relation("getBorrowedBooks")
}

// Many to Many
model BorrowedBook {
  id         BigInt   @id @default(autoincrement())
  borrowedAt DateTime @default(now())
  book       Book[]   @relation("getBorrowedBooks")
  member     Member[] @relation("getBorrowers")
}
```

Generates the following SQL

```SQL
-- CreateTable
CREATE TABLE "Member" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "penalizedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Book" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "code" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "author" TEXT,
    "stock" BIGINT NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "BorrowedBook" (
    "id" BIGINT NOT NULL PRIMARY KEY,
    "borrowedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "_getBorrowedBooks" (
    "A" INTEGER NOT NULL,
    "B" BIGINT NOT NULL,
    CONSTRAINT "_getBorrowedBooks_A_fkey" FOREIGN KEY ("A") REFERENCES "Book" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_getBorrowedBooks_B_fkey" FOREIGN KEY ("B") REFERENCES "BorrowedBook" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "_getBorrowers" (
    "A" BIGINT NOT NULL,
    "B" INTEGER NOT NULL,
    CONSTRAINT "_getBorrowers_A_fkey" FOREIGN KEY ("A") REFERENCES "BorrowedBook" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_getBorrowers_B_fkey" FOREIGN KEY ("B") REFERENCES "Member" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "_getBorrowedBooks_AB_unique" ON "_getBorrowedBooks"("A", "B");

-- CreateIndex
CREATE INDEX "_getBorrowedBooks_B_index" ON "_getBorrowedBooks"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_getBorrowers_AB_unique" ON "_getBorrowers"("A", "B");

-- CreateIndex
CREATE INDEX "_getBorrowers_B_index" ON "_getBorrowers"("B");
```

Note the lack of `AUTOINCREMENT` on `BorrowedBook` (this is expected as sqlite does not support `AUTOINCREMENT` on `BIGINT`, only `INTEGER`)
```SQL
-- CreateTable
CREATE TABLE "BorrowedBook" (
    "id" BIGINT NOT NULL PRIMARY KEY,
    "borrowedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
```

If I update your query like so:
```diff
await prisma.borrowedBook.create({
	data: {
+		id: borrowedBookId, // e.g. 0
		book: { connect: { id: bookId } },
		member: { connect: { id: memberId } },
	},
});
```

Then this correctly creates.

---

I cannot confirm the issue you outlined [here](https://github.com/prisma/prisma/issues/23865#issuecomment-2081186939), @lifeiscontent, where migrations failed to apply. Can you please provide the snippet of the migration (schema & generated SQL) that failed to apply.

**Comment by lifeiscontent** [comment]
@Druue I am busy this weekend, but I will setup a D1 project and do a full reproduction (if I can reproduce it) of the issue next weekend.

**Comment by jkomyno** [comment]
> @Druue I am busy this weekend, but I will setup a D1 project and do a full reproduction (if I can reproduce it) of the issue next weekend.

Hi @lifeiscontent, any chance you found the time for that reproduction? :)

**Comment by lifeiscontent** [comment]
@jkomyno nope, because apparently what I was seeing previously has been fixed in a later version of wrangler CLI, so I guess this can be closed! 🎉
