### ISSUE TITLE
Why is Prisma Migrate detecting a drift

### ISSUE THREAD

**Issue by machhindra10** [prisma/prisma#23869]
### Discussed in https://github.com/prisma/prisma/discussions/23868

<div type='discussions-op-text'>

<sup>Originally posted by **machhindra10** April 16, 2024</sup>
### Question

While creating from second migration and when "relationMode=foreignKey" then Why is Prisma Migrate detecting a drift and explaining it as foreign keys were removed and then the same foreign keys were added again? and saying data loss message do you want to proceed, if yes then prisma applies all the migrations with data loss 

### Expected behavior (optional)

expected behavior should be create migration and apply only one migration that is created

### Information about Prisma Schema, Client Queries and Environment (optional)

```prisma
// Add your schema.prisma
```

```ts
// Add any relevant Prisma Client queries here
```

- OS: 
- Database: 
- Node.js version: 

- Run `prisma -v` to see your Prisma version and paste it
</div>

**Comment by janpio** [comment]
See ongoing discussion: https://github.com/prisma/prisma/discussions/23868
