### ISSUE TITLE
An empty array is considered null when inserting data into a column with the Int[] type

### ISSUE THREAD

**Issue by reynaldiRepo** [prisma/prisma#23894]
### Bug description

There is a strange behavior when using Prisma for upserts, where an empty array is considered null when performing an upsert on a column that has an array of integers data type.

### How to reproduce

Create a PostgreSQL database with a schema like this:

```prisma
model A {
  social_key String?
  fav_series Int[] @default([])
}
```

Perform an upsert with this payload where fav_series is empty:

```ts
{
....
fav_series: []
....
}
```
![image](https://github.com/prisma/prisma/assets/38524172/dc6f7656-9006-4b0d-8b6b-4d99660824b1)
![image](https://github.com/prisma/prisma/assets/38524172/1413e0fa-cff5-4447-a321-a6858c3cef97)

`Error: Argument `fav_series`: Invalid value provided. Expected Testfav_seriesInput or Testfav_seriesInput, provided (Null).`

### Expected behavior

Created successfully on DB with empty int array

### Prisma information

```prisma
model Test {
  createdAt           DateTime  @default(now())
  updatedAt           DateTime?
  email               String
  sid                 String    @id
  tableNum            Int
  state               String
  lastMigratedAt      DateTime?
  tableName           String
  pulledFrom          Int
  error               String?
  validation_score    Int?
  validation_logs     Json?
  migrationStep       String?
  // additional field for user tracker based on v4 table
  ip                  String?
  city                String?
  country             String?
  mobile              String?
  gender              String?
  fav_series          Int[]     @default([])
  subscription_type   String?
  subscription_id     String?
  user_id             Int?
}
```
```ts
// upsert with empty fav_series
```

### Environment & setup

- OS: macOs
- Database: PostgreSQL
- Node.js version: v19.6.0

### Prisma Version

```
"@prisma/client": "^4.7.1",
```

**Comment by janpio** [comment]
Does this also happen with `create()` or `update()`, or is it only `upsert()` that is affected?
Can you try with a more recent version of Prisma maybe, to make sure this has not been fixed in the meantime?

**Comment by reynaldiRepo** [comment]
@janpio Thank you for your response. I think the problem lies in the Prisma error log when I perform an upsert inside a $transaction. However, it's possible that my terminal truncates some text. When I execute the commands one by one, the error logs display the correct message, revealing a null value within the array. Therefore, the original problem originates from my code. Nevertheless, I hope Prisma can address this logging issue, as it would greatly assist developers.

**Comment by Weakky** [comment]
Hey @reynaldiRepo,

Would you mind trying with a newer version of Prisma and confirm whether the bug is still present?

Thank you 🙏

**Comment by Druue** [comment]
Hey @reynaldiRepo, I've took a look at this.
I cannot confirm the case where an `[]` is treated as `null` and was consistently able to retrieve data:
```ts
{ id: 1, fav_series: [] }
```

When _explicitly_ passing in `null` to the query

```
Invalid `prisma.a.upsert()` invocation in
/src/prisma_debug/index.ts:11:14

   8 
   9 async function test() {
  10   let [up, ff] = await prisma.$transaction([
→ 11     prisma.a.upsert({
           create: {
             fav_series: null
                         ~~~~
           },
           update: {
             fav_series: null
                         ~~~~
           },
           where: {
             id: 0
           }
         })

Argument fav_series for create.fav_series must not be null. Please use undefined instead.
Argument fav_series for update.fav_series must not be null. Please use undefined instead.


    at Document.validate (/src/prisma_debug/node_modules/@prisma/client/runtime/index.js:32409:20)
    at serializationFn (/src/prisma_debug/node_modules/@prisma/client/runtime/index.js:35993:19)
    at runInChildSpan (/src/prisma_debug/node_modules/@prisma/client/runtime/index.js:25431:12)
    at PrismaClient._executeRequest (/src/prisma_debug/node_modules/@prisma/client/runtime/index.js:36000:31)
    at async PrismaClient._request (/src/prisma_debug/node_modules/@prisma/client/runtime/index.js:35926:16) {
  clientVersion: '4.7.1'
}
```

Note: this only lead to any messaging at _runtime_, there was no information in editor about this.

---

> Thank you for your response. I think the problem lies in the Prisma error log when I perform an upsert inside a $transaction. However, it's possible that my terminal truncates some text. When I execute the commands one by one, the error logs display the correct message, revealing a null value within the array. Therefore, the original problem originates from my code. Nevertheless, I hope Prisma can address this logging issue, as it would greatly assist developers.

I'm trying to understand your message here. It seems like you're implying a difference in messaging from upserts when wrapped in a `$transaction` like in the following code snippet. Can you please elaborate your logging setup or even more ideally, provide a full minimal reproduction for your issue?

```ts
await prisma.$transaction([
    prisma.a.upsert({
      create: {
        fav_series: [],
      },
      update: {
        fav_series: [],
      },
      where: {
        id: 0,
      },
    }),
  ]);
```

Cheers! 🙏

**Comment by reynaldiRepo** [comment]
> I'm trying to understand your message here. It seems like you're implying a difference in messaging from upserts when wrapped in a `$transaction` like in the following code snippet. Can you please elaborate your logging setup or even more ideally, provide a full minimal reproduction for your issue?
> 
> ```ts
> await prisma.$transaction([
>     prisma.a.upsert({
>       create: {
>         fav_series: [],
>       },
>       update: {
>         fav_series: [],
>       },
>       where: {
>         id: 0,
>       },
>     }),
>   ]);
> ```

@Druue In my case, the upsert process is like this:

```ts
await prisma.$transaction([
    prisma.a.upsert({
      create: {
        fav_series: [1,2,3,null,1,2],
      },
      update: {
        fav_series: [1,2,3,null,2],
      },
      where: {
        id: 0,
      },
    }),
  ]);
  ```
  
As I reported, the error logs show fav_series as an empty array, and it should not be.

i run my code using [warp](https://www.warp.dev/), i will try to run on my original terminal.

**Comment by Druue** [comment]
Hey @reynaldiRepo, this is still not something I am able to reproduce, the logging looks perfectly fine. So this seems like an issue in your logging set-up.

Can you please provide a minimal reproduction, thank you 🙏 

```ts
const fav_series = [1, 2, 3, null, 1, 2];
  const [a] = await prisma.$transaction([
    prisma.a.upsert({
      create: { id: 0, fav_series },
      update: { fav_series },
      where: { id: 0 },
    }),
  ]);
```

```
PrismaClientValidationError: 
Invalid `prisma.a.upsert()` invocation in
/src/prisma_debug/index.ts

  22 //     id: 0,
  23 //   },
  24 // }),
→ 25 prisma.a.upsert({
       create: {
         id: 0,
         fav_series: [
           1,
           2,
           3,
           null,
           1,
           2
         ]
         ~~~~~~
       },
       update: {
         fav_series: [
           1,
           2,
           3,
           null,
           1,
           2
         ]
       },
       where: {
         id: 0
       }
     })

Argument `fav_series`: Invalid value provided. Expected ACreatefav_seriesInput, provided (Int, Int, Int, Null, Int, Int).
    at ... {
  clientVersion: '5.15.0'
}
```

**Comment by SevInf** [comment]
@reynaldiRepo I am pretty sure we fixed the original error when we went from Prisma 4 to 5. We'd be grateful if you could confirm it does not happen to you on 5.0.0 or greater.

**Comment by Druue** [comment]
Hey @reynaldiRepo 

With the lack of update and our inability to reproduce this issue, we're now closing it.
If you get the chance to try again on Prisma V5, please feel free to comment with any updates!

Thank you 🙏
