### ISSUE TITLE
 routines:ssl_choose_client_version:unsupported 

### ISSUE THREAD

**Issue by gmkseta** [prisma/prisma#23895]
### Bug description

While attempting to connect to a legacy MSSQL server (Microsoft SQL Server 2014 - 12.0.4100.1) using TLSv1 through Prisma Client, I encountered a TLS connection error. The error message suggests that the TLS settings do not support the protocol required by the server, preventing the connection from being established.

```
Error opening a TLS connection: The TLS settings didn't allow the connection to be established. Please review your connection string. (error: error:0A000102:SSL routines:ssl_choose_client_version:unsupported protocol:ssl/statem/statem_lib.c:1947:)
PrismaClientInitializationError: 

```

### How to reproduce

1. Set up Prisma to connect to an MSSQL server (Microsoft SQL Server 2014 - 12.0.4100.1) that uses TLSv1.
2. Configure the Prisma schema to use the following connection string: 'sqlserver://username:password@host:port/database'.
3. Attempt to perform a query using Prisma Client.
4. Encounter the TLS error stating that the connection could not be established due to an unsupported protocol.

### Expected behavior

I expected Prisma Client to successfully establish a connection with the MSSQL server, managing the TLSv1 protocol without any errors, allowing me to perform queries and operations as usual.

### Prisma information

```prisma
datasource db {
  provider = "sqlserver"
  url      = "sqlserver://username:password@host:port/database"
}
async function main() {
  const allUsers = await prisma.user.findMany();
  console.log(allUsers);
}
main();


### Environment & setup

- OS: macOS 14.3 on M1 Mac
- Database: Microsoft SQL Server 2014 - 12.0.4100.1 (Standard Edition, 64-bit) on Windows NT 6.3 (Build 17763: ) (Hypervisor)
- Node.js version: v20.12.2
- "next": "^13.0.6",


### Prisma Version

```
@prisma/client: 5.8.1
prisma: 5.8.1

```

**Comment by janpio** [comment]
Prisma only supports Microsoft SQL Server 2017 or newer: https://www.prisma.io/docs/orm/reference/supported-databases

**Comment by gmkseta** [comment]
@janpio Thank you for your answer. I have no choice but to use the 2014 version, but is there a way to do something like monkey patching? Is there a way

**Comment by janpio** [comment]
No, that is most probably not possible - sorry. 

We use a Rust library, https://github.com/prisma/tiberius, and most probably it just does not support this old version of SQL Server. You would need to fix that first, and then we could potentially introduce this to our codebase. But I am pretty sure you would just find other things that we use that are not present in this old SQL Server version, which would then often be impossible to overcome.

**Comment by blobgetblob** [comment]
Any chance to support 2014 version, the tiberius doc said 2014 version should work

**Comment by blobgetblob** [comment]
Any chance to support 2014 version, the tiberius doc said 2014 version should work
