### ISSUE TITLE
README: Information about CLI is missing

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2390]
The current `README.md` generally tries to steer users to the documentation and its quickstart, but also gives a nice overview of the parts of Prisma:

- What is Prisma?
- Getting started
- How does Prisma work
  * The Prisma schema
  * The Prisma data model
  * Accessing your database with Prisma Client

The one thing missing is information about the CLI, and how to install it. I think "How does Prisma work" should also contain that information, so people e.g. executing the commands from the "Prisma Client" section will not only learn of it through a warning message that they need to install the CLI.

**Comment by mohitmohlia** [comment]
@janpio can you assign this to me, I can work on this

**Comment by janpio** [comment]
Please open a PR if you have a suggestion. A README change that explains Prisma is usually not the best candidate for community contributions though, so be warned.
