### ISSUE TITLE
Vercel Zeit dev serverless on windows with git bash

### ISSUE THREAD

**Issue by marcdavi-es** [prisma/prisma#2395]
Hi. Thanks for any help you can give me.

## Bug description

I'm trying to get the vercel/zeit dev environment running on a windows machine for a friend.

When running `vercel dev` with git bash, I get the following error...

```
bundle.esm.js:63 Uncaught (in promise) Error: GraphQL error: 
Invalid `prisma.user.findOne()` invocation in
C:\Users\BillGates\AppData\Local\Temp\zeit-fun-0508e4b1a3ca4\apollo-server\resolvers\login.js:5:34

Query engine binary for current platform "windows" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "C:\Users\BillGates\AppData\Local\Temp\zeit-fun-0508e4b1a3ca4\node_modules\@prisma\client\runtime\query-engine-windows.exe")

Files in C:\Users\Huw\AppData\Local\Temp\zeit-fun-0508e4b1a3ca4\node_modules\@prisma\client\runtime:

  index.js

You already added the platforms "native", "windows" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma-client-js/issues/new
```

I can see that a fresh `C:\Users\BillGates\AppData\Local\Temp\zeit-fun-0508e4b1a3ca4` directory is created each time I run `vercel dev`. In that directory, there is a partially complete `node_modules` directory. Specifically, `node_modules/@prisma/client` looks like this...

```
$ ll node_modules/@prisma/client
total 156
-rw-r--r-- 1 Huw 197121 146676 May  8 16:05 index.js
-rw-r--r-- 1 Huw 197121   4643 May  8 16:05 package.json
drwxr-xr-x 1 Huw 197121      0 May  8 16:05 runtime/
-rw-r--r-- 1 Huw 197121   1638 May  8 16:05 schema.prisma
```

and `node_modules/@prisma/client/runtime` has nothing but the `index.js` file. 

So... it's clear that my `postinstall` prisma generate command isn't being run after these partial node modules have been installed.

My next step was to trying generating the prisma client manually inside the temporary directory. This 'works' and creates all the `.d.ts` files but it fails to create either of the `query-engine-*` binaries in `runtime/`.

In the real project directory, the `query-engine-windows.exe` file is generate fine. My next step was to manually move that file to the temporary directory. That still doesn't work. I get the same error telling me the only file in the `runtime` directory is `index.js`.

For comparison, when I run `vercel dev` on my Mac, everything is fine and the query engine binaries for both darwin and windows are generated and put in the right place.

## Prisma information

Prisma schema

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "windows"]
}

...my model
```

## Environment & setup
- OS: Windows
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.2
- Node.js version: v12.16.3

**Comment by pantharshit00** [comment]
Hi @marcdavi-es 

Sorry for late reply here. This issue got buried in my notifications.

Can you please try this again with the latest version? Let me know if that didn't help you.

**Comment by Shelob9** [comment]
I had the same issue with 2.0.0 beta 9.

I am using Windows. 

I think what I need do is run prisma generate inside of a docker container built from node base image (?) so prisma client will be generated native, not with Windows.

**Comment by pantharshit00** [comment]
Try adding all the platforms that you are using in the generator so we grab all the required binaries. Here is how you will do that:

```prisma

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x", "windows"]
}
```

You might need to change `debian-openssl-1.1.x` to `linux-musl` if you are using alpine.

**Comment by pantharshit00** [comment]
After adding this run `prisma generate`

**Comment by janpio** [comment]
I am going to close this now. Happy to take a look again if we get more information.
