### ISSUE TITLE
How to exclude fields from method return value based on query parameters?

### ISSUE THREAD

**Issue by ludralph** [prisma/prisma#23990]
### Discussed in https://github.com/prisma/prisma/discussions/23947

<div type='discussions-op-text'>

<sup>Originally posted by **Cat7373** April 24, 2024</sup>
### Question

My model is defined as follows:

```prisma
model User {
  id       Int      @id @default(autoincrement())
  name     String   @unique
  password String
  regionId Int
  role     Role
  addtime  DateTime
  regUid   Int?
  lock     Boolean
}
```

When querying using findMany, the return value is defined as follows:

```typescript
const r = await prisma.user.findMany({ omit: { password: true } })
```

![image](https://github.com/prisma/prisma/assets/9296576/91727dca-6bfa-44b7-b34b-4cab20e2289a)

As you can see, there is no password field.

---

I'm trying to write a general utility method whose return value is deduced as follows:

```typescript
async function testQuery<M, A extends Prisma.Args<M, 'findMany'>>(model: M, queryParams: A) {
  return await (model as any).findMany({ ...queryParams }) as Result<M, A, 'findMany'>
}

const r = await testQuery(usePrisma().user, { omit: { password: true } })
```

![image](https://github.com/prisma/prisma/assets/9296576/97c47913-c03f-43a3-a0b9-de415133a78b)

As you can see, the password field was not successfully excluded.

Please help, how to define the parameters and return values of testQuery so that parameter exclusion can be handled correctly, thank you.

### Information about Prisma Schema, Client Queries and Environment (optional)

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["omitApi"]
}

datasource db {
  provider          = "mysql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}

enum Role {
  ADMIN
  USER
}

model User {
  id       Int      @id @default(autoincrement())
  name     String   @unique
  password String
  regionId Int
  role     Role
  addtime  DateTime
  regUid   Int?
  lock     Boolean
}
```

- OS: MacOS
- Database: MySQL
- Node.js version: v21.7.3

```
Environment variables loaded from .env
prisma                  : 5.13.0
@prisma/client          : 5.13.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.7.3
Query Engine (Node-API) : libquery-engine b9a39a7ee606c28e3455d0fd60e78c3ba82b1a2b (at node_modules/.pnpm/@prisma+engines@5.13.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli b9a39a7ee606c28e3455d0fd60e78c3ba82b1a2b (at node_modules/.pnpm/@prisma+engines@5.13.0/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.13.0-23.b9a39a7ee606c28e3455d0fd60e78c3ba82b1a2b
Default Engines Hash    : b9a39a7ee606c28e3455d0fd60e78c3ba82b1a2b
Studio                  : 0.500.0
Preview Features        : omitApi
```
</div>

**Comment by ludralph** [comment]
@Cat7373 also mentioned that setting the `select field` is valid:

```typescript
const r = await testQuery(usePrisma().user, { select: { id: true, name: true } })
```

<img width="331" alt="image" src="https://github.com/prisma/prisma/assets/9296576/78f3e3f4-df3f-4369-9f4f-9661cff2c287">

In other words, it may be that the new omit has not been adapted yet.

@SevInf  shared a workaround show below

First, I can confirm the issue on our side. The problem seems to be TS infering type of `A` to be broader that it actually is. Second, I have a workaround for you until the problem is fixed from our side. You need to add a `const` modifier to `A` in your `testQuery` definition, like this:

```ts
async function testQuery<M, const A extends Prisma.Args<M, 'findMany'>>(model: M, queryParams: A) {
  return (await (model as any).findMany({ ...queryParams })) as Prisma.Result<M, A, 'findMany'>
}
```

**Comment by aqrln** [comment]
I'm going to close this issue. Here the problem was not in Prisma but in user's types (or arguably perhaps TypeScript) which we don't control and have no way to influence. Either marking the `A` generic in the `testQuery` function as `const`, or adding `as const` to the object with query params make TypeScript infer the exact type and prevent it from widening. The best we could do is make this code not type check at all rather than falling back to the default selection, but I don't believe we could change anything on our side to make it work the way the user expected.

Please don't hesitate to re-open the issue if you think this is wrong and we could have done something, or if you'd prefer this to be an error as I suggested above.
