### ISSUE TITLE
class based schema design, like typeorm

### ISSUE THREAD

**Issue by MrSharpp** [prisma/prisma#24003]
## Problem

The .schema file has its own problems, like 
1) its painful to manage more than 10tables in single file, cross referencing itself.
2) in order to create dto, we cannot utilize/extend the table schmea, instead having to write some ninja types to get the type of the table, but still it wont be a class

## Suggested solution

if we design schema through classes.
it would be neat and clean, can be put anywhere, can be easily extended to make models like dto.

**Comment by SevInf** [comment]
Hi @MrSharpp.
Both problems you are rising already have an open issue:

#2377 for splitting schema files
#5998 for classes

I am going to close this issue for now. You can follow the progress on both of those issues using the links I've posted. 
Thank you!
