### ISSUE TITLE
Feature request: Override generated SQL

### ISSUE THREAD

**Issue by anton-johansson** [prisma/prisma#24013]
## Problem

This problem is related to multi-tenant set up with Prisma. A few Microsoft SQL servers with a lot of databases in each server. The problem can be described in various places:
* #2077
  * See last comment made by me here to get a more in-depth description of the problem and explored options.
* #20375

## Suggested solution

I would love to extend how the SQL is generated. My specific use case feels relatively easy, however it might have different impacts depending on which database type you are using. I'm using Microsoft SQL server. I would love something like this:
```typescript:
    const extendedClient = client.$extends({
        sql: {
          getTableName(tableName: string) {
            return `${databaseName}..${tableName}`;
          },
        },
    });
```

## Alternatives

As you can see in my comment in #2077, I've tried some workarounds, but none of them are efficient enough.

## Additional context

I'm using Microsoft SQL server and I understand that the suggested solution might not work for all types of databases and dialects.

**Comment by janpio** [comment]
Prisma Client is unfortunately not directly responsible for the generation of the SQL, but the Query Engine that is used under the hood is. That architecture does not allow calling back to a Client extension to get the table name to be used in a SQL query.

Your problem will need to be solved via proper multi-tenancy support in Prisma, with taking the specific way how SQL Server works (that you can use a connection for different databases) into account.

**Comment by anton-johansson** [comment]
@janpio Thank you for the reply.

I understand. If the Query Engine is not controlled by Prisma, is there something else we can do to get around this problem? If you look at my workaround from my comment in this issue:
https://github.com/prisma/prisma/issues/2077#issuecomment-2082647249

You can see that I get it working by wrapping it in a transaction. But I don't want a transaction for each query. Would there be an alternative to have a function similar to the `$transaction` function that just ensures that the same connection pool is being used (and reserved during it's time), for example `$reserveConnection`? Then I could do something like this:

```typescript
    // Extend Prisma so that we can switch database on the fly. This allows us to use one single connection pool for each SQL server.
    // In order to avoid leaking connections, we must do these two calls within a transaction.
    // This is far from optimal.
    const extendedClient = client.$extends({
        query: {
            async $allOperations({query, operation, args}) {
                const [, result] = await client.$reserveConnection([
                    client.$executeRawUnsafe(`USE [${databaseName}]`),
                    query(args),
                ]);

                return result;
            },
        },
    });
```

Looking forward to your response!

**Comment by janpio** [comment]
Not yet, but we have this feature request that is for exactly that: https://github.com/prisma/prisma/issues/5128
Maybe post your use case and suggested API over there, I think you can mostly just copy/paste what you wrote here <3

**Comment by anton-johansson** [comment]
Thank you, @janpio, this seem to be exactly what I'm looking for! :partying_face: I've posted my use case and suggested API there as well and we can continue the discussion there!
