### ISSUE TITLE
Prisma query using `contains` and `mode: "insensitive"` errors

### ISSUE THREAD

**Issue by thanhtamha** [prisma/prisma#24014]
### Bug description

I am using Prisma in Express Javascript project.

Prisma version 5.12.1 (both prisma and @prisma/client)

Schema

```
model Image {
  id   String @id @unique
  code String @unique

  name String
  path String

  @@index([code])
}
```

Query in Express

	const query = {
		name: { contains: search, mode: 'insensitive' },
	};

	const results = await prisma.images.findMany({
		where: query,
		orderBy: {code: 'asc'},
		skip: 0,
		take: 10,
	});

Without the mode: "insensitive", the query is working fine.
With the mode: "insensitive", the query will hit this error below.

```
Invalid prisma.image.findMany() invocation:

{
where: {
code: {
contains: "LOGO",
mode: "insensitive",
~~~~
? equals?: String | StringFieldRefInput,
? in?: String[],
? notIn?: String[],
? lt?: String | StringFieldRefInput,
? lte?: String | StringFieldRefInput,
? gt?: String | StringFieldRefInput,
? gte?: String | StringFieldRefInput,
? startsWith?: String | StringFieldRefInput,
? endsWith?: String | StringFieldRefInput,
? not?: String | NestedStringFilter
}
},
orderBy: {
code: "asc"
},
skip: 0,
take: 10
}

Unknown argument mode. Did you mean lte? Available options are marked with ?.
```

Similar issue have been raised here https://github.com/prisma/prisma/issues/18413
However, that is TypeScript project. so i am thinking if this still able to work on Javascript project.

**Comment by SevInf** [comment]
Hi @thanhtamha.
I'll kindly ask you to follow our issue template and provide all information it requests. In particualr, your report is missing the schema and the exact versions of `prisma` and `@prisma/client` packages. Without this information, we will not be able to proceed with reporoduction. Thank you!

**Comment by thanhtamha** [comment]
Sorry, i tried to keep it simple, straight to the point.
I have updated with Schema and Prisma version.

**Comment by Weakky** [comment]
Hey @thanhtamha, could you tell us what database are you using? Thank you

**Comment by thanhtamha** [comment]
@Weakky Thanks for clarify.
I have checked again. it works on MongoDB and Postgres
Error is on Sqlite3 DB
