### ISSUE TITLE
Performance issue with clustered server with uWebSockets.js

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma#2403]
Hello, i'm running into some prisma issues. I'm running a clustered server with uWebSockets.js.
I've added for every connected clients, every 30 seconds a "ping" message and write in database the last ping date and ms. Very quickly even if prisma run too on my 16 cpu, all prisma requests are blocked, I think because he can't handle too much or I don't know but its really breaking for production things for now! thanks

**Comment by pantharshit00** [comment]
Hi, Can you please share a minimal reproduction here? It is very easy to replicate the exact condition without a minimal reproduction.

Also, please absolutely make sure that you are not instantiating the prisma client per request. Otherwise, that will crash your CPU.

**Comment by yovanoc** [comment]
I've investigate deeper, and I will try to make a reproduction but its "hard". It's a private project with a lot of tables and relations. And the problem appear to lock a cpu for 50 mins when this large .update() come... and if it comes more than the cpu number so this ping can't update db anymore

**Comment by Sytten** [comment]
You can debug what queries it does with DEBUG=*. Prisma is indeed not very optimized but I have not had any issue even with big updates unless you start returning a bunch of data (because it goes through a JSON de/serilizalize phase because its still a separate process.

**Comment by yovanoc** [comment]
I have a 5 depth update call.. with a total of 34 updates/relations... Its nearly impossible to follow the DEBUG so I send by email the schema to help them optimize that

**Comment by pantharshit00** [comment]
Yeah, we have received the email, @yovanoc. I am investigating this to make sure it is not a problem with any other layer. Be patient :)

**Comment by yovanoc** [comment]
Yes no problem! Hope you will find in futures releases how to make this better :)

**Comment by janpio** [comment]
Is this still relevant @yovanoc? Seems this got forgotten along the way, and I am wondering if it is worth to revive and for Harshit to look at this again.

**Comment by yovanoc** [comment]
Yes, my queries still very slow

**Comment by pantharshit00** [comment]
Sorry this got buried in my notifications. I will look into this now.

Sorry again :pray:

**Comment by yovanoc** [comment]
No problem you are doing amazing work!

**Comment by janpio** [comment]
Happy to open this again if we get more information.
