### ISSUE TITLE
MongoDB: Suboptimal query for `some` and composite types with `type`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#24034]
> i also have found a `some` query which leads to another colscan
> 
> ```
> 
> // prisma.schema
> 
> 
> model Company {
>   id                   String                    @id @map("_id")
>   // ... 
>   participations       CompaniesParticipations[]
> 
>   @@map("companies")
> }
> 
> type CompaniesParticipations {
>   campaignId    String
>   createdAt     DateTime?                           @db.Date
>   employeeCount Int
>   months        String
>   //....
> }
> 
> 
> // this query 
> await prisma.company.count({
>           where: {
>             participations: {
>               some: {
>                 campaignId: campaign.id,
>               },
>             },
>           },
>         });
> ```
> 
> this creates an overly complicated query:
> 
> ```
> "$match" : {
>                         "$expr" : {
>                             "$and" : [
>                                 {
>                                     "$gt" : [
>                                         {
>                                             "$size" : {
>                                                 "$filter" : {
>                                                     "input" : {
>                                                         "$ifNull" : [
>                                                             "$participations",
>                                                             [
> 
>                                                             ]
>                                                         ]
>                                                     },
>                                                     "as" : "elem",
>                                                     "cond" : {
>                                                         "$and" : [
>                                                             {
>                                                                 "$eq" : [
>                                                                     "$$elem.campaignId",
>                                                                     {
>                                                                         "$literal" : "EuFvdM5yy747QGxxx"
>                                                                     }
>                                                                 ]
>                                                             },
>                                                             {
>                                                                 "$ne" : [
>                                                                     "$$elem.campaignId",
>                                                                     "$$REMOVE"
>                                                                 ]
>                                                             }
>                                                         ]
>                                                     }
>                                                 }
>                                             }
>                                         },
>                                         NumberInt(0)
>                                     ]
>                                 },
>                                 {
>                                     "$ne" : [
>                                         "$participations",
>                                         "$$REMOVE"
>                                     ]
>                                 }
>                             ]
>                         }
>                     }
>                 },
>                 {
>                     "$group" : {
>                         "_id" : null,
>                         "count_all" : {
>                             "$sum" : NumberInt(1)
>                         }
>                     }
>                 }
>             ],
> ```
> 
> this bypasses any index. The correct query would be trivial in mongodb.

_Originally posted by @macrozone in https://github.com/prisma/prisma/issues/21453#issuecomment-2060533829_

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
