### ISSUE TITLE
Less restrictive JSON types on create/insert

### ISSUE THREAD

**Issue by raclettes** [prisma/prisma#24054]
## Problem

When using the Prisma client (with Postgres in my case) to update data in the database, I've frequently been slowed down by the more restrictive types of the insert and create functions. For example, given the model

```prisma
model MyModel {
  id String  @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  myData    Json?   @db.Json
}
```

And attempting to insert data that follows the type

```typescript
interface CustomData {
    customKey: number
}

interface MyCustomModelInterface {
    id?: string;
    myData: CustomData;
}
```

You are often met with a message like
```
Types of property 'myData' are incompatible.
        Type 'CustomData' is not assignable to type 'NullableJsonNullValueInput | InputJsonValue'.
          Type 'CustomData' is not assignable to type 'InputJsonObject'.
            Index signature for type 'string' is missing in type 'CustomData'
```

Even though CustomData _does_ satisfy the requirements for the JSON field (on retrieval/return I understand there is no guarantee of the structure, but on insert there should be a guarantee)

## Suggested solution

If possible, `.insert` and `.create` (along with the types `MyModelCreateWithout...` etc) should ideally be able to allow types that satisfy the requirements of the JSON field instead of strictly requiring that it matches every possible JSON type. While I understand this is likely a TypeScript limitation, potentially there could be investigation into alternative solutions?

## Alternatives

Potentially allow declaration and/or validation of JSON fields coming from the database (although this could contradict the goal of the Json field type).

## Additional context

N/A

**Comment by jkomyno** [comment]
Hi @raclettes, what version of Prisma are you using?

**Comment by jkomyno** [comment]
Huh, I've found something curious. Looks like rewriting `CustomData` as a `type` rather than an `interface` works well:

```typescript
import { PrismaClient } from '.prisma/client'

type CustomData = {
  customKey: number
}

interface MyCustomModelInterface {
  readonly id?: string;
  readonly myData: CustomData;
}

async function main() {
  const prisma = new PrismaClient()

  const myCustomModel: MyCustomModelInterface = {
    myData: {
      customKey: 1,
    },
    id: '1',
  }


  const myModel = await prisma.myModel.create({
    data: {
      id: myCustomModel.id,
      myData: myCustomModel.myData,
    },
  })

  console.dir(myModel, { depth: null })
}

void main().catch((e) => {
  console.log(e.message)
  process.exit(1)
})

```

**Comment by raclettes** [comment]
Hey, sorry for the very long delay. I'll be honest I had forgotten about this.

Just tested myself and using `type` works where `interface` does not. 

Prisma 5.16.1

**Comment by jkomyno** [comment]
> Hey, sorry for the very long delay. I'll be honest I had forgotten about this.
> 
> Just tested myself and using `type` works where `interface` does not.
> 
> Prisma 5.16.1

Great! If using `type` solves the issue for you, can we close this ticket?

**Comment by raclettes** [comment]
Sure, would just be curious to know if you had any idea why this occurs? I'm not 100% knowledgable on how Typescript treats interfaces and types differently.

Otherwise yes, this can be closed.
