### ISSUE TITLE
Requesting Default Select "false" for different Field

### ISSUE THREAD

**Issue by rajan-marasini** [prisma/prisma#24053]
Feature Request: Default "select" attribute to "false" for a specific field.
Reason: Enhance user experience and prevent unintended selections/actions.
Current Behavior: Currently, the field's "select" attribute defaults to "true," leading to automatic selection or highlighting.
Proposed Behavior: Set the default value of the "select" attribute to "false" for the specified field.
Impact: This change is expected to positively impact user interaction by reducing accidental selections or actions, thereby improving overall usability and user satisfaction.
Additional Context: Examples or scenarios illustrating instances where the current behavior causes issues or confusion can be provided to further support this request.

**Comment by janpio** [comment]
Please have a look at the comments in https://github.com/prisma/prisma/issues/5042, is this covered by the request to add a global way to exclude certain fields from the default selection that is part of that issue?

**Comment by SevInf** [comment]
I beleive that's exactly "global exclude" we are talking about in #5042. I'm going to close this request in favor of already existing one, you can follow the progress in #5042
