### ISSUE TITLE
Broken `ModelCreateArgs` being generated for relations in `data`

### ISSUE THREAD

**Issue by Druue** [prisma/prisma#24066]
### Bug description
[Internal Reproduction](https://github.com/prisma/reproductions/tree/main/broken-nested-relation-query)

the create arg type for `b` is brokenly generated as undefined rather than actually something along the lines of:
```ts
b: { connect | connectOrCreate | create }

// where
connect: { ...fields }

connectOrCreate: { ...fields }

create: { ...fields }
```

### How to reproduce

1. Generate the mentioned schema
2. Try to complete `b` in the `create` for `a`

4. See undefined

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model A {
  id Int @id
  b  B   @relation(fields: [id], references: [id])
}

model B {
  id Int @id
  a  A?
}

```

```ts
import { PrismaClient } from '.prisma/client'

async function main() {
  const prisma = new PrismaClient()

  await prisma.a.create({
    data: {
      id: 1,
      // ! For some reason, the types for b aren't generated correctly
      // ! on a very simple 1:1 relation.
      // ! <|> -> b: undefined
      // ! b: {
      // !   <|> nothing is offered here, no create, connectOrCreate, or connect
      // ! }
    },
  })
}

void main().catch((e) => {
  console.log(e.message)
  process.exit(1)
})

```

### Environment & setup

- OS: MacOS
- Database: This happens for all databases
- Node.js version: v21.7.3 (this doesn't seem to matter)

### Prisma Version

```
❯ pnpm prisma -v

prisma                  : 0.0.0
@prisma/client          : 0.0.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.7.3
Query Engine (Node-API) : libquery-engine 612a7f7142ab73baf44704be23cbac7b7df1f7fc (at ../../../packages/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 612a7f7142ab73baf44704be23cbac7b7df1f7fc (at ../../../packages/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.14.0-9.612a7f7142ab73baf44704be23cbac7b7df1f7fc
Default Engines Hash    : 612a7f7142ab73baf44704be23cbac7b7df1f7fc
Studio                  : 0.500.0
```

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
