### ISSUE TITLE
Prisma incorrectly parses CRDB's FK constraint error as `not available`

### ISSUE THREAD

**Issue by evangeline** [prisma/prisma#24072]
### Bug description

We are seeing errors like 
```
Foreign key constraint failed on the field: `(not available)`
```
and was wondering whether it’s possible to surface which FK is causing this error. Some tables have multiple FKs, and `(not available)` makes it harder to narrow down which FK is throwing. 

When running the query manually, CRDB throws the following error, which suggests that Prisma is not parsing the FK name correctly. 
```
ERROR: insert on table "WearablePart" violates foreign key constraint "WearablePart_wearableId_fkey" Detail: Key (wearableId)=('foo') is not present in table "Wearable".
```

### How to reproduce

1. Create a table with a FK constraint in CRDB
2. Insert data with an invalid foreign key via Prisma
3. Insert the same data via `cockroach sql` or any other DB client

### Expected behavior

I would expect to see the error
```
Foreign key constraint failed on the field: `WearablePart_wearableId_fkey`
```

### Prisma information

Fails on any schema, repro steps above.

### Environment & setup

- OS: macOS
- CockroachDB
- Node.js version: v18.17.0

### Prisma Version

```
v5.9.1
```

**Comment by janpio** [comment]
Can you maybe create a reproduction repository that we can just run to experience this problem? Thanks.

**Comment by leighman** [comment]
Can confirm. Any model with a relation where you try to delete the parent without deleting the child (without cascade).

**Comment by leighman** [comment]
https://github.com/search?q=repo%3Aprisma%2Fprisma%20oreign%20key%20constraint%20failed%20on%20the%20field%3A%20%60(not%20available)&type=code presumably these cases
