### ISSUE TITLE
error Command "up" not found.

### ISSUE THREAD

**Issue by fahimahammed** [prisma/prisma#24137]
### Bug description

I am encountering difficulties while attempting to upgrade Prisma ORM to version 5 from an earlier version. Following the documentation provided, I executed the command yarn up prisma@5 @prisma/client@5. However, I encountered an error stating "Command 'up' not found."

### How to reproduce

1. Navigate to a project using an earlier version of Prisma ORM.
2. Execute the command yarn up prisma@5 @prisma/client@5.

### Expected behavior

The command should upgrade both the prisma and @prisma/client packages to version 5 as documented, without throwing an error.

### Prisma information

Prisma Version : 4

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 20..10.0

### Prisma Version

```
Prisma Version: 4
```

**Comment by SevInf** [comment]
This error comes from `yarn` and not `prisma`. Please, double check their documentation and ensure it is set up correctly and if you think it is `yarn` bug, open an issue with them.
Thank you!
