### ISSUE TITLE
prisma init should not ask for existing schema when choosing "no existing data"

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma#2413]
(https://github.com/graphcool/prisma/issues/new?template=bug.md)
![image](https://user-images.githubusercontent.com/281337/39971686-9750b48c-56ff-11e8-84d4-2a8dde8d5f20.png)

When choosing existing database, but no existing data, the CLI should not ask for existing schema

**Comment by wieseljonas** [comment]
#2407 linked

**Comment by marktani** [comment]
This is now available at `1.13-beta`.

**Comment by marktani** [comment]
Fixed in `1.13`.
