### ISSUE TITLE
Improve update notifier message

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2416]
Right now the update notifier always tells users to update their global (after Beta 5: local) installation of Prisma CLI. This might or might not be correct. The message also always assumes you are using npm instead of considering yarn and others.

We should modify check for the _type of installation_ (local vs. global) and _package manager used_ (npm, yarn, other) and create the optimal update message for that user.

Checkpoint-Client already returns the individual pieces that are required to construct our own message: https://github.com/prisma/checkpoint-client/pull/12 (`previous_version`, `package` and `release_tag`)

**Comment by Jolg42** [comment]
<img width="365" alt="Screen Shot 2020-08-12 at 17 19 57" src="https://user-images.githubusercontent.com/1328733/90034477-f924ee00-dcc0-11ea-80b7-2bf1e34be61d.png">
<img width="359" alt="Screen Shot 2020-08-12 at 17 27 40" src="https://user-images.githubusercontent.com/1328733/90034947-8bc58d00-dcc1-11ea-9917-553de0e028b1.png">
<img width="355" alt="Screen Shot 2020-08-12 at 17 27 05" src="https://user-images.githubusercontent.com/1328733/90034954-8e27e700-dcc1-11ea-91a4-f6eef543fa93.png">

If you have a global package from yarn:
```
		// It's not possible to detect when it's the global package 
        // because the command is just `prisma`, yarn is not executing it
        // so it will output the npm global command
```

**Comment by janpio** [comment]
> 		// It's not possible to detect when it's the global package 
>         // because the command is just `prisma`, yarn is not executing it
>         // so it will output the npm global command

Can we not check for a yarn.lock vs. package-json.lock file for example? https://www.npmjs.com/package/has-yarn probably (although that might false positive)

**Comment by Jolg42** [comment]
Yes but yarn.lock means local install, not global 🤷‍♂️

**Comment by janpio** [comment]
Oh. That is true, in theory they could have a local yarn installation but use a global yarn installation.
But I think using a local yarn is still fine to assume they are using a global yarn? Can we maybe look at the global installation path to be sure?

**Comment by Jolg42** [comment]
I can maybe try something let's see

**Comment by Jolg42** [comment]
Works with both npm and yarn global
<img width="367" alt="Screen Shot 2020-08-14 at 14 19 01" src="https://user-images.githubusercontent.com/1328733/90255938-44680980-de45-11ea-873c-5c5c35e258a4.png">
<img width="395" alt="Screen Shot 2020-08-14 at 14 18 14" src="https://user-images.githubusercontent.com/1328733/90255943-46ca6380-de45-11ea-9501-56a497fd5c54.png">
