### ISSUE TITLE
Hello @bso-oo 👋

### ISSUE THREAD

**Issue by Rakesh-99** [prisma/prisma#24161]
Hello @bso-oo 👋 

Once you set the environment variable in the Linux machine, can you check if the value of `DATABASE_URL` is correct at runtime?
You can use the dotenv package to load the environment variable as specified here: https://www.prisma.io/docs/guides/development-environment/environment-variables#using-environment-variables-in-your-code

_Originally posted by @nurul3101 in https://github.com/prisma/prisma/discussions/19107#discussioncomment-5834437_

**Comment by belgattitude** [comment]
Might help… I generally plug this https://github.com/belgattitude/httpx/tree/main/packages/dsn-parser somewhere. You’ll find recipes with zod or t3-env.

**Comment by janpio** [comment]
Please move the discussion back to https://github.com/prisma/prisma/discussions/19107#discussioncomment-5834437
