### ISSUE TITLE
Support PostgreSQL type `Timestamptz` (TIMESTAMP WITH TIME ZONE)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2417]
## Problem
Currently Prisma does not handle the PostgreSQL type `timestamptz`, which leads to it not being introspected appropriately (https://github.com/prisma/prisma/issues/552) or queries against fields using it failing (https://github.com/prisma/prisma-client-js/issues/90)

## Suggested solution
Prisma should support these types.

## Alternatives
None really.

**Comment by tomhoule** [comment]
I just saw this issue pop up in my notifications, and I'm a bit suprised. Are we sure this doesn't work? We have tests that check can introspect (to DateTime), read, write and filter on timestamptz columns in the prisma-engines repo, I just double checked.

**Comment by janpio** [comment]
No, this replaced an older feature request that was open and formulated poorly. If you are confident enough we are doing all the right things here, please just close the issue 🚀  Thanks.

**Comment by tomhoule** [comment]
I'm quite sure, but I'll check again that it's already supported :)

**Comment by lights0123** [comment]
But as far as I'm aware, migrate doesn't, and will create `timestamp` columns instead. Should that issue belong in https://github.com/prisma/migrate?

**Comment by pantharshit00** [comment]
@lights0123 Support for `timrstampz` or any other type for migrate will come in future via #443

Right now if you start a greenfield (basically from scratch) with migrate, it is a bit opinionated about database type mapping

**Comment by tomhoule** [comment]
We do test this type in the query engine test suite, so I think we can consider it supported. This topic will come up again as we work on native types support in the near future.

**Comment by chrissisura** [comment]
Hey guys, I getting this error for all my timestamptz with prisma 2.11 after introspecting my postgres database.

*** WARNING ***

These fields were commented out because Prisma currently does not support their types.
- Model "Company", field: "createdAt", original data type: "timestamptz"

**Comment by giraffesyo** [comment]
> Hey guys, I getting this error for all my timestamptz with prisma 2.11 after introspecting my postgres database.
> 
> *** WARNING ***
> 
> These fields were commented out because Prisma currently does not support their types.
> 
> * Model "Company", field: "createdAt", original data type: "timestamptz"

Same problem here, this completely broke my project. Reverting back to 2.10.2 and regenerating fixed it.

**Comment by devuxer** [comment]
Still broken in @prisma/client 2.26.0.

I get:

> *** WARNING ***
>
> These fields are not supported by the Prisma Client, because Prisma currently does not support their types.
> - Model "KnowledgeAid", field: "whenCreated", original data type: "timestamptz"
> - Model "KnowledgeAid", field: "whenUpdated", original data type: "timestamptz"

Do we need to open a new issue for this, @tomhoule?

**Comment by pantharshit00** [comment]
We do have support for this now: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#postgresql-6

Please open a new issue if you encountering any bugs with a minimal reproduction.

**Comment by devuxer** [comment]
@pantharshit00 , My mistake, I just realized the project I was experimenting with was SQLite not Postgres.
