### ISSUE TITLE
Include `@prisma/client` in update notifier

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#2419]
@janpio just mentioned this idea in Slack:

While we right now already notify Prisma users about an available update of `@prisma/cli`, we should do the same for `@prisma/client`.

The cli could just read the `package.json` and check if the latest version of `@prisma/client` is installed.

**Comment by janpio** [comment]
Depends on return payload changes in Checkpoint that need to happen first.

**Comment by janpio** [comment]
This work in Checkpoint happened, so we can now easily adapt the update notifier message to also include `@prisma/client` in the Npm CLI command the user should run.
