### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: Any { .. }

### ISSUE THREAD

**Issue by smg-helenyemima** [prisma/prisma#24225]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.18.0           | 
| OS              | windows            |
| Prisma Client   | 5.13.0             |
| Query Engine    | b9a39a7ee606c28e3455d0fd60e78c3ba82b1a2b|
| Database        | sqlserver          |

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from D:\Learn\NestJS\api-gateway\.env
prisma:client checkPlatformCaching:postinstall 
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from D:\Learn\NestJS\api-gateway\.env
prisma:client dirname D:\Learn\NestJS\api-gateway\node_modules\.prisma\client
prisma:client relativePath ../../../prisma
prisma:client cwd D:\Learn\NestJS\api-gateway\prisma
prisma:client clientVersion 5.13.0
prisma:client:libraryEngine internalSetup
prisma:client:engines:resolveEnginePath enginePath D:\Learn\NestJS\api-gateway\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client prisma.$queryRaw(UPDATE Item SET @P1 WHERE id = @P2, [["name = 'Laptop'","quantity = 2000"],"2"])
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}}
```

**Comment by jkomyno** [comment]
Hi @smg-helenyemima, can you please share the contents of `schema.prisma`? Can you paste the Prisma Client code that made your app crash, with explicit input arguments values that we can copy from the snippet and run internally to verify this issue? 

Ideally, we kindly ask you to fill all the information requested in this [bug template](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml), to allow us to attempt a reproduction.

Thanks!

**Comment by Jolg42** [comment]
Hey @smg-helenyemima,

Did you get a chance to take a look at the previous comment?

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by SevInf** [comment]
Hey @smg-helenyemima ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
