### ISSUE TITLE
Customize Introspection

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#2425]
## Context

Since Prisma Migrate is currently experimental, users need to migrate their DB with plain SQL or another migration tool. They can then introspect the DB schema to obtain their Prisma schema, which can in turn be used to generate Prisma Client.

The main issue with this workflow is that any changes to the Prisma schema get overwritten with each introspection run. However, changes to the Prisma schema are often desirable to ensure the Prisma Client API is consistent (e.g. wrt to uppercasing and lowercasing) and its semantics make sense (e.g. wrt to pluralization).

Consider this SQL schema:

```sql
CREATE TABLE "public"."users" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE "public"."posts" (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  content TEXT,
  published BOOLEAN NOT NULL DEFAULT false,
  "authorId" INTEGER NOT NULL,
  FOREIGN KEY ("authorId") REFERENCES "public"."users"(id)
);

CREATE TABLE "public"."profiles" (
  id SERIAL PRIMARY KEY NOT NULL,
  bio TEXT,
  "userId" INTEGER UNIQUE NOT NULL,
  FOREIGN KEY ("userId") REFERENCES "public"."users"(id)
);
```

After introspection, it looks as follows (fields reordered for better readability):

```prisma
model posts {
  id        Int      @default(autoincrement()) @id
  createdAt DateTime @default(now())
  title     String
  content   String?
  published Boolean  @default(false)
  users     users    @relation(fields: [authorId], references: [id])
  authorId  Int
}

model profiles {
  id     Int     @default(autoincrement()) @id
  bio    String?
  users  users   @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model users {
  id       Int       @default(autoincrement()) @id
  email    String    @unique
  name     String?
  posts    posts[]
  profiles profiles?
}
```

There are several issues with this data model:

- model names don't adhere to the Prisma convention of PascalCasing and singular form
- the `users` field on `Posts` is pluralized although it refers to a single `User` record, not a list; same for the type which is called `users`
- it would also be nice if the field was called `author` to express more semantic about the API
- similar issues/inconsistencies arise for there `profiles` and `users` models

To fix this, I can manually change the Prisma schema and thus ensure the generated Prisma Client API feels consistent and nicer to use:

```diff
model Post {
  id        Int      @default(autoincrement()) @id
  createdAt DateTime @default(now())
  title     String
  content   String?
  published Boolean  @default(false)
+ author    User     @relation(fields: [authorId], references: [id])
  authorId  Int

+ @@map("posts")
}

model Profile {
  id     Int     @default(autoincrement()) @id
  bio    String?
+ user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique

+ @@map("profiles")
}

model User {
  id      Int      @default(autoincrement()) @id
  email   String   @unique
  name    String?
+ posts   Post[]
+ profile Profile?

+ @@map("users")
}
```

I can now run `prisma generate` and the Prisma Client API feels nice and adheres to all naming conventions.

## Problem

Once I change my database schema with SQL and re-introspect, all my manual changes will be gone again and I need to manually add them again. For bigger projects, this manual effort quickly gets out of hand.

## Suggested solutions

This is an extremely hard problem, product- and engineringwise. From my very naive point of view, I could see two different approaches:

- Introduce an **_introspection_ config** that allows me to do certain configurations, e.g. turning snake_case into PascalCase on table names, and into camelCase on column names. Enable or disable pluralization. A similar feature has been requested for `migrate` [here](https://github.com/prisma/migrate/issues/424).
- While this approach would solve already most of the problems above, it's not as flexible as trying to somehow **preserve manual changes** across different introspection runs. I imagine this is very difficult though and we might potentially end up in pretty weird state, so that option seems a bit scary but could be magical if it works properly.

## Related discussions/issues

- https://github.com/prisma/prisma/discussions/2530#discussioncomment-17535
- https://github.com/prisma/prisma/discussions/2655

**Comment by janpio** [comment]
> * Introduce an **_introspection_ config** that allows me to do certain configurations, e.g. turning snake_case into PascalCase on table names, and into camelCase on column names. Enable or disable pluralization. A similar feature has been requested for `migrate` [here](https://github.com/prisma/migrate/issues/424).

Issues related to Introspection Configuration are collected at https://github.com/prisma/prisma/labels/topic%3A%20introspection-configuration

> * While this approach would solve already most of the problems above, it's not as flexible as trying to somehow **preserve manual changes** across different introspection runs. I imagine this is very difficult though and we might potentially end up in pretty weird state, so that option seems a bit scary but could be magical if it works properly.

Issues related to Re-Introspection are collected at https://github.com/prisma/prisma/labels/topic%3A%20re-introspection

**Comment by pbelbin** [comment]
I am using MySQL database, and I have a need to have camel-case column names (and @map to the underlying kebab case column name in the database.

I *also* need to keep the list of column names in the .schema matching the order of those in the database!

I am happy to work with you on this, if it seems like a good match with what you're wanting to achieve.

**Comment by pbelbin** [comment]
hey folks: here is an idea for you:

let the column names in the `schema.prisma` always be a certain standard, and let the client generators handle emitting column names that conform to a particular standard?

Typically, the standard for names varies quite a bit with the language, and this seems like a better alignment with having various client generators that already know how to emit code for those languages.

That way, you can more easily support one schema being used across different languages in the same project, and each language getting the results they need.

**Comment by janpio** [comment]
> I am using MySQL database, and I have a need to have camel-case column names (and @Map to the underlying kebab case column name in the database. I am using the javascript client generator.

Your camel-case/kebap-case use case should be covered by this functionality behind a feature flag now @pbelbin: https://github.com/prisma/prisma/issues/2829#issuecomment-649203862 Would be great if you could try it out and comment in that issue.

> I _also_ need to keep the list of column names in the .schema matching the order of those in the database!

We are planning to look into this very soon over at https://github.com/prisma/prisma/issues/2554 - subscribe to or comment at this issue for notifications.

**Comment by janpio** [comment]
@nikolasburk The database you posted above is currently introspected as:

```prisma
model posts {
  authorId  Int
  content   String?
  createdAt DateTime @default(now())
  id        Int      @default(autoincrement()) @id
  published Boolean  @default(false)
  title     String
  users     users    @relation(fields: [authorId], references: [id])
}

model profiles {
  bio    String?
  id     Int     @default(autoincrement()) @id
  userId Int     @unique
  users  users   @relation(fields: [userId], references: [id])
}

model users {
  email    String    @unique
  id       Int       @default(autoincrement()) @id
  name     String?
  posts    posts[]
  profiles profiles?
}
```

When I apply your manual changes, I get to this:

```prisma
model Post {
  authorId  Int
  content   String?
  createdAt DateTime @default(now())
  id        Int      @default(autoincrement()) @id
  published Boolean  @default(false)
  title     String
  author    User     @relation(fields: [authorId], references: [id])

  @@map("posts")
}

model Profile {
  bio    String?
  id     Int     @default(autoincrement()) @id
  userId Int     @unique
  user   User    @relation(fields: [userId], references: [id])

  @@map("profiles")
}

model User {
  email   String   @unique
  id      Int      @default(autoincrement()) @id
  name    String?
  posts   Post[]
  profile Profile?

  @@map("users")
}
```

When using `prisma introspect` these manual changes are reset again, and we are back to the initial schema.

But we now have an initial version of Re-Introspection support: https://github.com/prisma/prisma/issues/2829#issuecomment-649044648

If we activate that feature with the feature flag and run `prisma introspect --experimental-reintrospection`, the modified schema stays unchanged (! - besides that the trailing new line at the end of the file is removed for me) and this is output on the command line:

```
C:\Users\Jan\Documents\throwaway\reinstrospection>prisma introspect --experimental-reintrospection
Environment variables loaded from prisma\.env

Introspecting based on datasource defined in prisma\schema.prisma …

✔ Introspected 3 models and wrote them into prisma\schema.prisma in 958ms

*** WARNING ***

These models were enriched with @@map information taken from the previous Prisma schema.
- Model "Post"
- Model "Profile"
- Model "User"

Run prisma generate to generate Prisma Client.
```

Pretty sweet 🚀

**Comment by nikolasburk** [comment]
That's amazing, re-introspection of `@map`, `@@map` and relation fields also works for me!

**Comment by janpio** [comment]
Great - I consider the Re-Introspection part of this done then and removed the label. Introspection Configuration will be tackled at a later time when Re-Introspection is in a good place for everyone.

**Comment by albertoperdomo** [comment]
Since 2.6.0, any manual changes should be kept by default when introspecting with an existing schema.
For out of the box mapping of lower case to camel casing,  singularization/pluralization I'd like to discuss these feature requests, so this very high-level issue is less useful.

https://github.com/prisma/prisma/issues/2502 (also from @nikolasburk) already covers these topics.
