### ISSUE TITLE
`@prisma/instrumentation` Type Error: `'InstrumentionNodeModuleDefintion' is not generic`

### ISSUE THREAD

**Issue by zhiyan114** [prisma/prisma#24285]
### Bug description

Installing latest Prisma cause TS type error: `'InstrumentionNodeModuleDefintion' is not generic`

Here's the definition inside the installed package (`..../PrismaInstrumentation.d.ts`):
```ts
declare class PrismaInstrumentation extends InstrumentationBase {
    constructor(config?: Config);
    init(): InstrumentationNodeModuleDefinition<unknown>[];
    enable(): void;
    disable(): void;
    isEnabled(): boolean;
}
```

### How to reproduce

Installation step from https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/opentelemetry-tracing should be sufficient:

```bash
npm install prisma@latest --save-dev
npm install @prisma/client@latest --save
npm install @prisma/instrumentation@latest --save
```
and ensure `skipLibCheck` inside tsconfig are set to false.
### Expected behavior

either `InstrumentationNodeModuleDefinition` class implements a generic type or the init() type should not have `unknown` as its type declaration

### Prisma information

N/A

### Environment & setup

OS: Windows 11 + Ubuntu 20.04

### Prisma Version

```
prisma                  : 5.14.0
@prisma/client          : 5.14.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.12.2
Query Engine (Node-API) : libquery-engine e9771e62de70f79a5e1c604a2d7c8e2a0a874b48 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli e9771e62de70f79a5e1c604a2d7c8e2a0a874b48 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.14.0-25.e9771e62de70f79a5e1c604a2d7c8e2a0a874b48
Default Engines Hash    : e9771e62de70f79a5e1c604a2d7c8e2a0a874b48
Studio                  : 0.500.0
Preview Features        : tracing
```

**Comment by Jolg42** [comment]
Thanks for the issue!

I can confirm the problem. I think it originates from https://github.com/open-telemetry/opentelemetry-js/pull/4598

I think we need to wait for https://github.com/open-telemetry/opentelemetry-js/pull/4677 to be published.

**Comment by unflxw** [comment]
@Jolg42 It has been published now.

**Comment by ihorkazmin1988** [comment]
@Jolg42 It's a breaking changes, more details here https://github.com/open-telemetry/opentelemetry-js/releases/tag/experimental%2Fv0.51.0
