### ISSUE TITLE
`createManyAndReturn()` not getting recognized/available

### ISSUE THREAD

**Issue by imoby** [prisma/prisma#24294]
### Bug description

When I try to implement createManyAndReturn in my code after updating to 5.14.0 the ts types and autocomplete is not available. When I looked at the compiled code I do see references to it but its not available to me.

I have tried to wipe my node_modules and restarted my vscode and everything and still not available. All the other methods work.

<img width="731" alt="image" src="https://github.com/prisma/prisma/assets/6380855/12362d41-3751-4d70-a512-646510cce130">

### How to reproduce

1. Setup a nodejs serverless project
2. Install prisma 5.14.0
3. Create a model and run generate
4. Attempt to do a createAndMany and notice vscode is not showing it. Even other editors I tried like intellij didnt find it

### Expected behavior

It should find createManyAndReturn

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
export async function createInventoryDevices(devices: any): Promise<any> {
  const createdCount = await prisma.deviceInventory.createManyAndReturn({})
}
```

### Environment & setup

- OS: macOS
- Database: postgres
- Node.js version: 18.16.0

### Prisma Version

```
5.14.0
```

**Comment by iceniveth** [comment]
Same here:

![image](https://github.com/prisma/prisma/assets/16744414/f8cdc61f-0f13-4eb6-a61b-15c4accd58e2)

using @prisma/client 5.14.0 and NodeJS 20.9

**Comment by iceniveth** [comment]
@Jolg42 Thanks for the help, was able to see the issue from `npx prisma -v` was using prisma@5.13 but @prisma/client@5.14.

```
npm i prisma@^5.14 @prisma/client@^5.14
npx prisma generate
```

Did fix it 🙏

**Comment by imoby** [comment]
I think I found out the issue I am using the preview of joins that might be why

**Comment by Jolg42** [comment]
@imoby `createManyAndReturn()` is indeed not supported with `relationLoadStrategy: join`

**Comment by Weakky** [comment]
@imoby It shouldn't have anything to do with the `relationJoins` preview feature. Can you confirm that when re-enabling that preview feature `createManyAndReturn` is gone again? Your bug _has_ to be about something else.

**Comment by SevInf** [comment]
I've confirmed that `createManyAndReturn` is still there when `relationJoins` preview feature is enabled. We are also running our test suite on this combination.

One more thing to try: put `// @ts-ignore` above the TS error and try to run the code. Do you get a runtime error?

**Comment by jelmd** [comment]
Wondering, why MySQL and MariaDB are not supported ...
