### ISSUE TITLE
Make sure `db.statement` attribute doesn't include the `traceparent` comment

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#24375]
> It would be great if the db.statement tag didn't include any trailing comments, see https://github.com/DataDog/dd-trace-js/issues/1244#issuecomment-1691856305

_Originally posted by @alandotcom in https://github.com/prisma/prisma/issues/14640#issuecomment-1691863547 on Aug 24, 2023_
            
Check if it's still the case, fix and/or add tests.

**Comment by stubinubin** [comment]
Can confirm this is happening, we use otel-collector to send onto elastic-apm.
@prisma/client: 5.14.0
@prisma/instrumentation: 5.14.0
