### ISSUE TITLE
Introduce `connectOrSkip` for optional `connect` operations

### ISSUE THREAD

**Issue by ajmnz** [prisma/prisma#24404]
## Problem

When dealing with user input or other non-controlled sources, there are times when you cannot ensure a `connect` operation will succeed since you don't know if the key provided belongs to an existing record. If you don't want to create a record with `connectOrCreate`, the alternative is to first check if the record exists (ie. `prisma.foo.findUnique`) and then do the connect operation only if the record exists (ie. `connect: foo ? { id: foo.id } : undefined`).

## Suggested solution

If Prisma introduces the `connectOrSkip` operation, things could be simplified to just

```ts
await prisma.customer.update({
  where: { id: 3 },
  data: {
    orders: {
      connectOrSkip: { id: 36 } // model Customer { orders Order[] }
    },
  }
});
```

instead of the following

```ts
const order = await prisma.order.findUnique({ where: { id: 36 } });
await prisma.customer.update({
  where: { id: 3 },
  data: {
    orders: {
      connect: order ? { id: order.id } : undefined // model Customer { orders Order[] }
    },
  }
});
```

## Additional context

I believe there's no native way to do this on Postgres, but easily achievable via subqueries.

**Comment by janpio** [comment]
Look like a duplicate of https://github.com/prisma/prisma/issues/21606.
Does your suggestion add anything? If so, comment over there and close this issue please. Thanks!

**Comment by ajmnz** [comment]
> Look like a duplicate of #21606. Does your suggestion add anything? If so, comment over there and close this issue please. Thanks!

yep, didn't find it initially. thanks
