### ISSUE TITLE
Insert or update an item without returning it

### ISSUE THREAD

**Issue by sebastiansandqvist** [prisma/prisma#24418]
## Problem

Currently, `prisma.example.create(...)` will perform both an `INSERT` write and `SELECT` read. For performance sensitive large writes, it would be nice to be able to perform just the write without the subsequent read operation.

## Suggested solution

Maybe a new option in the `create` params?

```ts
// `doc1` is of type { foo: string }
const doc1 = await prisma.example.create({
  data: { foo: 'bar' },
  returnResult: true, // the default, so it can remain unspecified
});

// `doc2` is undefined
const doc2 = await prisma.example.create({
  data: { foo: 'bar' },
  returnResult: false,
});
```

Alternatively, the existing `select` option could include a special value to add this behavior.

```ts
// `doc3` is undefined
const doc3 = await prisma.example.create({
  data: { foo: 'bar' },
  select: { [prisma.NONE]: true }
});
```

The same option would also make sense to include in `.update(...)` and `.upsert(...)`.

## Alternatives

Currently, I'll add `select: { id: true }` to my `create()` calls in order to return as little data as I can, but it still performs an unnecessary `SELECT`.

**Comment by janpio** [comment]
What database/`provider` are you using? Most `create()` should not actually do an additional `SELECT` query any more.

These are probably duplicates of what you are asking for: https://github.com/prisma/prisma/issues/4246 or https://github.com/prisma/prisma/issues/9301

**Comment by sebastiansandqvist** [comment]
> What database/`provider` are you using? Most `create()` should not actually do an additional `SELECT` query any more.
> These are probably duplicates of what you are asking for: #4246 or #9301

@janpio Apologies for missing #4246 which is the same problem. I really like the proposed `{ select: false }` there. This issue is present in MySQL / PlanetScale dbs. I will close this thread as it is a duplicate, but it'd be great to see this make its way onto the roadmap eventually, as the extra `SELECT` does needlessly slow down most `create`/`update` operations in practice.

**Comment by janpio** [comment]
Yes, I understand and fully agree.
