### ISSUE TITLE
JSON-specific filtering

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#2444]
## Problem

When working with `Json` fields, some databases (like [postgres](https://www.postgresql.org/docs/current/functions-json.html)) let you manipulate the JSON value. This is useful for filtering, for example if you want to filter a model with a Json field where one _object field_ (or a specific path) inside the json column matches a provided value. There are other operations like "object contains", "path exists", etc. that would be useful.

## Additional context

This issue is the prolongation of https://github.com/prisma/prisma/issues/2345 - which is about simple filtering by Json field by equality, treating it as a scalar.

**Comment by luxaritas** [comment]
Few notes:
- Django is shipping JSONField support to all DBs in 3.1 - might be worthwhile taking a peek at what they've done
- If I understand correctly, you should be able to perform any typical filtering operation on a JSON value - ie in a where clause, you could verify `myjson.some.value > 5`
- At least in Postgres, you can also index on individual keys

Would also just like to mention that as I'm evaluating Prisma as a possibility for our future amend rewrite, this is quite important for us. We have data that is simply not viable to store relationally, but still needs to be queryable - and in some cases that dataset could be quite large. If it's helpful at any point, I'm happy to describe more about our use cases for this

**Comment by luxaritas** [comment]
Another thought - it might be nice to have built-in support, or at least a recommended approach, for validating a JSON schema when updating a JSON field

**Comment by JoniBR** [comment]
This feature would be really helpful! For example, we have a column `integrations` on our User table which holds a JSON with some external ids. A lot of times we need to filter the users by having a certain key inside that JSON.

**Comment by tre-dev** [comment]
Can this please get pushed on the priority list? 🙏

**Comment by tradical-allstripes** [comment]
+1

This feature would be immensely helpful for me and my team

**Comment by xiaoyu-tamu** [comment]
really want this feature

**Comment by kladnik** [comment]
This is really needed and also PostgreSQL supports this naturally with queries. Can we get this soon?

**Comment by dpetrick** [comment]
This is finished and released in 2.23, integration is done.

**Comment by matthewmueller** [comment]
Take a look at JSON filtering with the example in the [Release Notes](https://github.com/prisma/prisma/releases/tag/2.23.0)

If you run into anything, let us know in https://github.com/prisma/prisma/issues/7135!
