### ISSUE TITLE
Prisma (v5.12 & v5.14 & v5.15) client has errors accessing `cockroachdb` when using with cloudflare workers and the new `driverAdapter` preview feature

### ISSUE THREAD

**Issue by ad6025b** [prisma/prisma#24475]
### Bug description

Prisma (v5.12 & v5.14 & v5.15 client has errors accessing cockroachdb when using with cloudflare workers and the new { previewFeatures = ["driverAdapters"] }.  All queries using the PrismaClient() will fail with error:

```
Cannot find module './query_engine_bg.js'
```
![Image](https://github.com/prisma/prisma/assets/183673/07bd2c23-eb9c-4a74-a424-43305505cc5e)

**NOTE:** the root cause of the bug is that there are 2 files: [query_engine_bg.js] & [query_engine_bg.wasm] that are missing from the directory [\node_modules.prisma\client]

_(if you copy the 2 missing files into this directory, then the PrismaClient() will work, and be able to query the database)_

### How to reproduce

You can use your own example: 
https://github.com/prisma/ecosystem-tests/tree/dev/driver-adapters-wasm/pg-cf-basic

change the provider to "cockroachdb", and the 2 missing files will not get produced (in the .prisma/client directory)

![image](https://github.com/prisma/prisma/assets/73307/9af52886-fcf9-452a-b809-5abd587c7415)

### Expected behavior

the 2 file below should appear in the direcotry .[..\pg-cf-basic\node_modules\.prisma\client]

**query_engine_bg.js
query_engine_bg.wasm**

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: windows 10
- Database: [PostgreSQL]
- Node.js version: v18.16.0

### Prisma Version

```
prisma 5.12.1   (or 51.4 or 5.15)
@prisma/client 5.12.1   (or 51.4 or 5.15)
@prisma/adapter-pg  5.12.1   (or 51.4 or 5.15)
```

**Comment by ad6025b** [comment]
@Jolg42  @janpio  what is the status of this ticket? has there been any movement here?

**Comment by ad6025b** [comment]
@SevInf  @Jolg42  i found the problem. its in the function generateClient  in file generateClient.ts
  => since the postgres and cockroachdb essentially uses the same postgres driver, there is a lot of code that does [ postgres or cockroachdb then use postgres ] in the codebase.
  
  Line 461, needs to check for both  [ postgres or cockroachdb ]  (see screenshot below
   => the workaround is to do this manually for now (copy the postgres wasm files for cockroachdb. (which works now)

![image](https://github.com/user-attachments/assets/8cc8a7e1-f4dd-499f-918e-e1e174c3012e)

![image](https://github.com/user-attachments/assets/182d09b1-e570-4eb9-abf6-89e2e43deb24)

**Comment by jkomyno** [comment]
Hi @ad6025b, thanks for mentioning this issue in https://github.com/prisma/prisma/issues/24996.
[As I've shared there](https://github.com/prisma/prisma/issues/24996#issuecomment-2284545104), `provider = "cockroachdb"` is currently not supported by the `driverAdapters` preview feature, due to other database drivers and features currently having more priority. 

We thank you for expressing interest in a fully CockroachDB-compatible Driver Adapter, though! Thanks.
