### ISSUE TITLE
Accelerate breaks "PrismaClient is unable to run in this browser environment, or has been bundled for the browser"

### ISSUE THREAD

**Issue by walterdiazesa** [prisma/prisma#24472]
### Bug description

Hi, I have a **Next.js** application using the **pages router**, prisma has been working delightfully until this date, I'm a big fan of it, but now that I'm implementing **@prisma/extension-accelerate**, it's breaking one single route, an ISR route, which is odd as I have almost the same implementation for a route alike

`lib/prisma.ts`:
```
import { PrismaClient } from "@prisma/client";

const prismaClientSingleton = () => {
  return new PrismaClient({ log: ["info", "warn"] });
};

type PrismaClientSingleton = ReturnType<typeof prismaClientSingleton>;

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClientSingleton | undefined;
};

export const prisma = globalForPrisma.prisma ?? prismaClientSingleton();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;

export default prisma;
```

With the previous prisma implementation, `http://localhost:3000/users/22` it's working fine, everything loads as expected, but if I add Accelerate to the Prisma Client [as recommended by Prisma](https://github.com/prisma/accelerate-nextjs-starter/blob/main/lib/db.ts), then run `pnpm prisma generate` and `pnpm dev`, the same route it's breaking somehow

`lib/prisma.ts` (with Accelerate):
```
import { PrismaClient } from "@prisma/client";
import { withAccelerate } from "@prisma/extension-accelerate";

const prismaClientSingleton = () => {
  return new PrismaClient({ log: ["info", "warn"] }).$extends(withAccelerate()); // <-- Accelerate
};

type PrismaClientSingleton = ReturnType<typeof prismaClientSingleton>;

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClientSingleton | undefined;
};

export const prisma = globalForPrisma.prisma ?? prismaClientSingleton();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;

export default prisma;
```

<img width="1452" alt="image" src="https://github.com/prisma/prisma/assets/58494087/bd48c14e-2726-4a90-bf18-0fec87dfc54e">

`pages/users/[slug].tsx`:
```
import React from "react";
import Head from "next/head";
import prisma from "@/lib/prisma";
import UserPreview, { getPublicUser } from "@/components/User/Preview";

const slug = ({
  user,
}: {
  user: Awaited<ReturnType<typeof getPublicUser>>;
}) => {
  return (
    // ...
    <UserPreview user={user} />
  );
};

export async function getStaticProps({ params }: { params: { slug: string } }) {
  const id = parseInt(params.slug, 16);

  if (Number.isNaN(id) || !id.isUnsignedInt())
    return {
      props: {
        user: null,
      },
    };

  const user = await getPublicUser({
    id,
    works: { some: { viewInBase: true } },
  });

  return {
    // * revalidate onDemand
    props: {
      user,
    },
  };
}

export async function getStaticPaths() {
  const usersWithWorks = await prisma.user.findMany({
    where: { works: { some: { viewInBase: true } } },
    select: { id: true },
  });

  const paths = usersWithWorks.map(({ id }) => ({
    params: { slug: id.toString(16) },
  }));

  return { paths, fallback: "blocking" };
}

export default slug;
```

`components/User/Preview/index.tsx` (getPublicUser functionality):
```
// ...
import { Prisma } from "@prisma/client";
import prisma from "@/lib/prisma";
// ...

const UserPreview = ({
  user,
}: {
  user?: Awaited<ReturnType<typeof getPublicUser>>;
}) => {
  const { data: session } = useSession();
  // ...
};

export const getPublicUser = async (where: Prisma.userWhereUniqueInput) => {
  const userUnique = prisma.user.findUniqueOrThrow({
    where,
    include: {
      entries: {
        take: -1,
        where: {
          OR: [{ needsVerification: false }, { approvedAt: { not: null } }],
        },
        // ...
  });
  
  // ...
  
  const [userPromise, workCountPromise, userRatingPromise] =
    await Promise.allSettled([
      userUnique,
      prisma.works.count({ where: { userId: where.id, viewInBase: true } }),
      userRating,
    ]);
    
  let user = null as unknown as Record<
    keyof Exclude<Awaited<typeof userUnique>, null>,
    any
  > & { rating?: BaseUserRating<number>; workCount: number };
  // * Sanitize non-serializable data, we could be using https://www.npmjs.com/package/superjson but for now vanilla is fine, no extra bundle size
  if (userPromise.status === "fulfilled") {
    user = userPromise.value as typeof user;
    user.createdAt = user.createdAt!.toISOString();
    // ...
    
  return user as
    | (Omit<
        NonNullable<Awaited<typeof userUnique>>,
        "id" | "isActive" | "isAdmin" | "isBanned" | "isStaff"
      > & {
        workCount?: number | null;
        rating?: (typeof user)["rating"];
      })
    | null;
};

export default UserPreview;
```

The weird thing for me, is that **I also have a page that's using the same functionality** `(http://localhost:3000/works/1t-Rust_Senior_Developer),` **but without being split into two files** (I need to do that for [slug]/user because there's also a profile page), and that **instead of being `pages/users/[slug].tsx` is `pages/works/[slug]/index.tsx`**, the works one **it's working just fine with or without Accelerate**

`pages/works/[slug]/index.tsx`
```
// ...
import prisma from "@/lib/prisma";
import { Prisma } from "@prisma/client";
// ...

const index = ({ work }: InferGetStaticPropsType<typeof getStaticProps>) => {
  // ...
};

export async function getStaticProps({ params }: { params: { slug: string } }) {
  const id = parseInt(params.slug.split("-")[0], 36);

  if (Number.isNaN(id) || !id.isUnsignedInt())
    return {
      props: {
        work: null,
      },
    };

  const workUnique = prisma.works.findUniqueOrThrow({
    where: { id, viewInBase: true },
    include: {
      entries: {
        take: -1,
        select: {
          // ...
        },
        where: {
          OR: [{ needsVerification: false }, { approvedAt: { not: null } }],
        },
      },
      // ...
      
    // ...
    const [workPromise, userRatingPromise, userFeedbackPromise] =
    await Promise.allSettled([workUnique, userRating, userFeedback]);
    
    if (workPromise.status === "fulfilled") {
    work = workPromise.value as typeof work;
    // * Sanitize non-serializable data, we could be using https://www.npmjs.com/package/superjson but for now vanilla is fine, no extra bundle size
    (work as any).createdAt = work.createdAt!.toISOString();
    // ...
    
  return {
    // * Revalidate OnDemand
    props: {
      work,
    },
  };
}

export async function getStaticPaths() {
  const works = await prisma.works.findMany({
    where: { viewInBase: true },
    select: { id: true },
  });

  // Get the paths we want to pre-render based on posts
  const paths = works.map(({ id }) => ({
    params: { slug: `${id.toString(36)}` },
  }));

  // We'll pre-render only these paths at build time.
  // { fallback: 'blocking' } will server-render pages
  // on-demand if the path doesn't exist.
  return { paths, fallback: "blocking" };
}

export default index;
```

**Dependencies**:
- "next": "13.4.17",
- "@prisma/client": "5.15.0",
- "@prisma/extension-accelerate": "1.1.0",

### How to reproduce

1. Create a Next.js project **with pages router**
2. Copy the implementation of PrismaClient **without Accelerate** 
3. Run `prisma generate`
4. Test a page with the same implementation as `/users/22` (pages/users/[slug].tsx)
5. Expect no issues
6. Replace the PrismaClient implementation **with Accelerate**
7. Run `prisma generate`
8. Test the same `/users/22` (pages/users/[slug].tsx) page
9. Expect to see the `PrismaClient is unable to run in this browser environment, or has been bundled for the browser` modal

### Expected behavior

Should work properly just as `/works/1t-Rust_Senior_Developer` (pages/works/[slug]/index.tsx)

### Prisma information

`schema.prisma`
```
datasource db {
  provider  = "mysql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["tracing"]
}

generator photos {
  provider = "prisma-pothos-types"
}
```

### Environment & setup

- OS: macOS (But also happening on Ubuntu)
- Database: MySQL
- Node.js version: >= 21

### Prisma Version

```
prisma                  : 5.16.0-dev.16
@prisma/client          : 5.15.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.5.0
Query Engine (Node-API) : libquery-engine 9ee8c029573a3ce47bd5f103da9feaf8b6f62c53 (at node_modules/.pnpm/@prisma+engines@5.16.0-dev.16/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 9ee8c029573a3ce47bd5f103da9feaf8b6f62c53 (at node_modules/.pnpm/@prisma+engines@5.16.0-dev.16/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-3.9ee8c029573a3ce47bd5f103da9feaf8b6f62c53
Default Engines Hash    : 9ee8c029573a3ce47bd5f103da9feaf8b6f62c53
Studio                  : 0.501.0
Preview Features        : tracing
```

**Comment by nurul3101** [comment]
Hey @walterdiazesa 👋 

Thank you for raising this.

If I understand this correctly, Prisma Accelerate works as expected for your one route (`pages/works/[slug]/index.tsx`) but it doesn't for the other route (`pages/users/[slug].tsx`) correct?

I see that in your `users/[slug].tsx` you are importing a component called `UserPreview` which I assume returns some JSX?
Could you temporarily comment usage of `UserPreview` in the `users/[slug].tsx` file and check if you still get the error? My assumption is that the error is caused in `components/User/Preview/index.tsx` file.

**Comment by walterdiazesa** [comment]
@nurul3101 Your understanding is correct. Not only that, but **I also tested your hypothesis, and it's right**.

I commented out `UserPreview ` in `users/[slug].tsx` and no error was thrown. I started to debug and noticed that nothing inside that JSX component was the problem.

The problem was that I had `import prisma from "@/lib/prisma";` and
```
export const getPublicUser = async (where: Prisma.userWhereUniqueInput) => {
  const userUnique = prisma.user.findUniqueOrThrow({
  ...
```
in the same file where the `UserPreview` component was defined (`components/User/Preview/index.tsx`)

So I used `components/User/Preview/index.tsx` only for the JSX and moved `getPublicUser` to another file, and the error is gone, **fixed**!

I'm just wondering, **why isn't the behavior the same between using Accelerate and not using it**? Even though the problem is fixed, should I expect any changes in how Accelerate affects the """bundle""" (I'm unaware of the correct term as I'm ignorant of what's actually happening under the hood) to be able to use my original code, or is this code refactoring expected when using Accelerate?

**Comment by nurul3101** [comment]
I am glad to hear that the hypothesis was correct. I believe the code refactoring is expected, because UserPreview component - `components/User/Preview/index.tsx` is rendered on client side and is not server side rendered. The database interactions need to happen on the server side. Previously you were doing database calls in `getPublicUser` function which was on client side, which caused the error. As soon as you changed the location of the function to be outside the client rendered component, the issue was resolved.

**Comment by edi** [comment]
To be mentioned that, you don't have to import anything specific into a client component in order for the error to be thrown. 

If, in a client component you import any other methods exported from the same file which exports the prisma client, the error is thrown.

Unlike the `default client` which triggers a `browser environment` error whenever you execute code in the browser, the `accelerated` client throws an error directly on mount, regardless if you imported or executed anyc ode related to client itself.

It's enough to import anything from the file that exports the accelerated file, it'l automatically throw an error on mount.
