### ISSUE TITLE
Missing generated Enum in typescript definition when Enum isn't used in Prisma table

### ISSUE THREAD

**Issue by Joshua-Zou** [prisma/prisma#24510]
### Bug description

Normally, you can simply import Prisma enums as a typescript type like below:
```typescript
import type { MyEnum } from "@prisma/client"
```
However, if the Enum isn't used in any Prisma table column, Prisma doesn't generate the typescript definitions for it. 

### How to reproduce

Using the attached Prisma schema file, or any Prisma file containing an Enum that isn't referenced by a table, run `npx prisma generate`.

Lastly, try importing both the Enum1 and Enum2 types 
```typescript
import { Enum1, Enum2 } from "@prisma/client"
```
Enum2 will not exist in the typescript definition, and typescript will throw an error. 

<img width="804" alt="Screenshot 2024-06-11 at 3 57 47 PM" src="https://github.com/prisma/prisma/assets/77520157/3001eee5-83ab-49e0-88ae-6c5df34c743f">

### Expected behavior

Both Enum1 and Enum2 should exist in the Prisma typescript definition file, and both be able to be imported into my project, even though Enum2 was never used by any table defined in Prisma. 

### Prisma information

```prisma
generator client {
    provider      = "prisma-client-js"
    binaryTargets = ["native"]
}

datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}

model MyTable {
    id      String @id
    column1 Enum1
}

enum Enum1 {
    value1
}

enum Enum2 {
    value2
}

```

```ts
import { Enum1, Enum2 } from "@prisma/client"
```

### Environment & setup

- OS: Linux
- Database: PostgreSQL
- Node.js version: Node 20

### Prisma Version

```
v5.15.0
```

**Comment by Digital39999** [comment]
This is still the issue in v5.19.0.

**Comment by jkomyno** [comment]
Hey there, Prisma 6 is out: https://github.com/prisma/prisma/releases/tag/6.0.0!
It includes a fix to this issue.
