### ISSUE TITLE
prisma-cli should correctly prompt the current loaded ENV file

### ISSUE THREAD

**Issue by Crownico** [prisma/prisma#24551]
### Bug description

![image](https://github.com/prisma/prisma/assets/41910836/a169a53d-69e2-4e5c-9a7c-0a196ed67d22)
As shown in the screenshot above, I want to load the .env.development file, but the cli prompts that the .env file is being loaded. I thought there was an error, but in fact, the .env.development file was correctly loaded. I believe that this inconsistency can easily confuse many people. 

### How to reproduce

package.json
```json
{
  "scripts": {
      "migrate:dev": "dotenv -e .env.development -- npx prisma migrate dev"
    }
}
```
.env
```env
DATABASE_URL="mysql://xxx/prisma-test?schema=public"
```
.env.development
```env
DATABASE_URL="mysql://xxx/prisma-test-dev?schema=public"
```
```bash
pnpm run migrate:dev 
```

### Expected behavior

I hope the cli can correctly prompt the currently loaded env file.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: v20.12.2

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.15.0
@prisma/client          : 5.15.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.12.2
Query Engine (Node-API) : libquery-engine 12e25d8d06f6ea5a0252864dd9a03b1bb51f3022 (at node_modules\.pnpm\@prisma+engines@5.15.0\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 12e25d8d06f6ea5a0252864dd9a03b1bb51f3022 (at node_modules\.pnpm\@prisma+engines@5.15.0\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.15.0-29.12e25d8d06f6ea5a0252864dd9a03b1bb51f3022
Default Engines Hash    : 12e25d8d06f6ea5a0252864dd9a03b1bb51f3022
Studio                  : 0.501.0
```

**Comment by SevInf** [comment]
Hi @Crownico 
In your example, Prisma is not the one doing the file loading - you are loading it manually with `dotenv`, before even starting prisma cli. So, at that point, we have no knowledge of what happened before `prisma generate` invocation and what files third-party tools are loading.

**Comment by Crownico** [comment]
> Hi @Crownico In your example, Prisma is not the one doing the file loading - you are loading it manually with `dotenv`, before even starting prisma cli. So, at that point, we have no knowledge of what happened before `prisma generate` invocation and what files third-party tools are loading.

Would it be feasible to consider amending the prompt message, such as revising from .env to from environment file? This adjustment would, at the very least, aid in alleviating the present ambiguity.

**Comment by SevInf** [comment]
Hey @Crownico.
There is no ambiguity in this message. Both files exist, so first you load `.env.devlopment` with `dotenv`, then we load `.env`. Logging message tells you about second part of that and we don't know that first happened.

We have a feature request for supporting multiple `.env` files natively - #11050.  You can follow for updates there.

Since there is no bug with Prisma in this case, I am going to close this issue.
Thank you!
