### ISSUE TITLE
transaction: bulk ops already in a transaction should not be executed in a new sub transaction

### ISSUE THREAD

**Issue by jelmd** [prisma/prisma#24565]
## Problem

Since prisma does not not support `createManyAndReturn()` for MySQL, one needs to find its own workaround. Reading the cluttered, really awefull transaction docs, one intentionally comes up with something like this:
```typescript
export async function createEvents(entry: NewEvent[]): Promise<number[]> {
...
	const getNewIds =
		'SELECT JSON_ARRAYAGG(id) AS val FROM event WHERE id >= LAST_INSERT_ID()';
	return prisma.$transaction(
		async (tx) => prisma.event.createMany({ data: entry }).then(bp => {
			if (bp.count === 0)
				return [];

			return tx.$queryRawUnsafe<{val: number[]}[]>(getNewIds)
				.then(res =>  res ? res[0]!.val : []);
		}),
		{ isolationLevel: Prisma.TransactionIsolationLevel.RepeatableRead }
	).catch((e: Error) => { throw normalizeException(e); });
}
```
This doesn't work because the `createMany()` gets executed in a different transaction and thus the intended transaction does not see the inserts. Therefore the result of `LAST_INSERT_ID()` stays the same and the related query `getNewIds` returns the wrong IDs.

To circumvent the shortcomings of `createMany()` I finally came up with the following pretty bloated solution:
```typescript
export async function createEvents(entry: NewEvent[]): Promise<number[]> {
...
	const getNewIds =
		'SELECT JSON_ARRAYAGG(id) AS val FROM event WHERE id >= LAST_INSERT_ID()';

	const values = new Array<string|null>(entry.length * 3);
	const query = new Array<string>(1 + entry.length * 3);
	var idx = 0;
	query[idx] = 'INSERT INTO `event` '
		+ "(`sid`, `startAt`, `endAt`, `location`, `name`, `desc`) VALUES ";
	for (let i=0; i < entry.length; i++) {
		let e = entry[i]!;
		query[idx] += "(" + e.sid + ",'" + date2mysqlStr(e.startAt) + "',"
			+ (e.endAt ? date2mysqlStr(e.endAt) + "'," : "NULL,");
		values[idx] = e.location;
		query[++idx] = ",";
		values[idx] = e.name;
		query[++idx] = ",";
		values[idx] = e.desc;
		query[++idx] = "),";
	}
	query[entry.length * 3] = ")";

	return prisma.$transaction(async tx => {
			return tx.$executeRaw(Prisma.sql(query, ...values)).then(rows => {
				if (rows === 0)
					return [];

				return tx.$queryRawUnsafe<{val: number[]}[]>(getNewIds).then(res => {
					return res ? res[0]!.val : [];
				});
			});
		},
		{ isolationLevel: Prisma.TransactionIsolationLevel.RepeatableRead }
	).catch((e: Error) => { throw normalizeException(e); });
}
```

## Suggested solution
If a bulk operation gets invoked within a `Prisma.$transaction(...)`, it should not start a new transaction, but exec directly within the current transaction. This avoids a lot of pain and time wrt. finding a safe solution to "emulate" the bulk ops and finally may safe more or less resources when actually running the code. 

## Alternatives
Hmmm, perhaps provide a hook, which executes within the bulk op itself. But this sounds bad and probably increases the complexity of transactions even more as well as the shallow documented helpers around it.

Exposing a SQL safe string escape function would probably also help to make the use of prisma more safe.

## Additional context
Current behavior:
```
prisma:query SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
prisma:query BEGIN
prisma:query SELECT 1
prisma:query BEGIN
prisma:query INSERT INTO `event` (`location`,`name`,`sid`,`desc`,`endAt`,`startAt`) VALUES (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?)
prisma:query COMMIT
prisma:query SELECT JSON_ARRAYAGG(id) AS val FROM event WHERE id >= LAST_INSERT_ID()
prisma:query COMMIT
```

but should be:
```
prisma:query SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
prisma:query BEGIN
prisma:query INSERT INTO `event` (`location`,`name`,`sid`,`desc`,`endAt`,`startAt`) VALUES (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?), (?,?,?,?,?,?)
prisma:query SELECT JSON_ARRAYAGG(id) AS val FROM event WHERE id >= LAST_INSERT_ID()
prisma:query COMMIT
```

**Comment by SevInf** [comment]
> Reading the cluttered, really awefull transaction docs

Pull requests to improve our docs are always welcome. 

>This doesn't work because the createMany() gets executed in a different transaction

Because you tell it to. `tx` is the transaction, `prisma` is a pooled client. It should be `tx.event.createMany`. 

There is no bug here, so I am going to close this issue.

**Comment by jelmd** [comment]
Uhhhm, yes - you are right, missed this one :( .

Wrt. docs: Yes, would do, but for doing it right, I would need to understand/know all those things in depth, which I don't ... :(
