### ISSUE TITLE
Schema enum Support Chinese

### ISSUE THREAD

**Issue by ZhangGuangHuiCoder** [prisma/prisma#24564]
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Error validating: This line is not an enum value definition.
  -->  schema.prisma:115
   | 
114 | enum Grade {
115 |   小学
116 | }
   |

**Comment by SevInf** [comment]
Hi @zfjhui!
What's your usecase? Do you want to use Chinese identifiers in JS code or just the names in your database?
If that's just about  the database and you are fine with using latin characters in your code, you can use `@map`:

```prisma
enum Grade {
  MyVariant @map("小学")
}
```

**Comment by zfjhui** [comment]
> Hi @zfjhui!
> What's your usecase? Do you want to use Chinese identifiers in JS code or just the names in your database?
> If that's just about  the database and you are fine with using latin characters in your code, you can use `@map`:
> 
> ```prisma
> enum Grade {
>   MyVariant @map("小学")
> }
> ```

Some Chinese do not have the right english
Some    Friends  don't know english
It would be nice to have direct support for non-Latin🙏

**Comment by zfjhui** [comment]
<img width="1232" alt="Snipaste_2024-06-21_07-47-52" src="https://github.com/prisma/prisma/assets/40257170/8dbc112e-7aa7-4ea7-8966-90951680baa2">

**Comment by yeliex** [comment]
Not a good idea. database is designed for storage, not human-read friendly. provide a client for human operations/reads rather than read direct from db

**Comment by zfjhui** [comment]
> Not a good idea. database is designed for storage, not human-read friendly. provide a client for human operations/reads rather than read direct from db
这个问题不冲突，就像我现在发中文你看了不一定习惯。

**Comment by jkomyno** [comment]
Closed via https://github.com/prisma/prisma-engines/pull/4959, which will be part of Prisma's next release (ETA: tomorrow).
