### ISSUE TITLE
Generalize and Enhance Readability of "RecordNotFound" Error Message in Prisma Client

### ISSUE THREAD

**Issue by fahimahammed** [prisma/prisma#24580]
# **Generalize and Enhance Readability of "RecordNotFound" Error Message in Prisma Client**

**Description:**
Currently, when using Prisma Client's `findUniqueOrThrow` and other methods and no record is found, the error message returned is "RecordNotFound". While this message is functional, it could be more generalized and readable to improve the developer experience and aid in debugging.

**Request:**
Enhance the error message returned by Prisma Client in cases where no record is found. Instead of the specific "RecordNotFound" message, consider providing a more generalized and readable message such as "No matching record found" or "Requested record not found". This change would improve the clarity and usability of error messages.

**Impact:**
- **Improved Developer Experience:** More readable error messages help developers quickly understand and resolve issues.
- **Clarity and Generalization:** A generalized message is applicable to various contexts, making it more useful across different use cases.
- **Ease of Debugging:** Clear and concise error messages reduce the time required to diagnose and fix problems.

**Example:**

```typescript
const userData = await prisma.user.findUniqueOrThrow({
    where: {
        userId: payload.id,
        status: UserStatus.ACTIVE
    }
});
```

**Current Error Message:**
```
RecordNotFound
```

**Proposed Error Message:**
```
No matching record found
```

or

```
Requested record not found
```

or

```
User not found
```

**Additional Context:**
Generalizing the error message to something like "No matching record found" provides a clearer, more universal message that can be understood quickly. This is particularly useful in environments where rapid troubleshooting is necessary.

**Comment by SevInf** [comment]
Hi @fahimahammed.
Error message returned by `*OrThrow` is is "No <ModelName> found". For example:

```
    await prisma.account.findFirstOrThrow()
    ^
NotFoundError [PrismaClientKnownRequestError]: No Account found
```

almost exactly like the one you ask for. Not sure where are you getting `RecordNotFound` from, but it's not Prisma. Please, double check surrounding code and make sure that nothing in it catches and re-wraps Prisma errors into `RecordNotFound`. Your framework and client extensions would be one of the places to check.

If you won't find the problem in your code, please, provide a runnable reproduction where we could see `RecordNotFound` error from `Prisma`.

**Comment by SevInf** [comment]
Hey @fahimahammed  ,

Did you get a chance to have a look at my previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by fahimahammed** [comment]
Hi @SevInf ,

Thank you for your response and for providing the clarification regarding the error message behavior in Prisma Client.

I double-checked the surrounding code and confirmed that there are no custom error wrappers or framework-level overrides that would transform Prisma errors into a "RecordNotFound" message. It appears I was mistaken in my initial observation. The default Prisma error message "No <ModelName> found" is indeed suitable for our use case.

I appreciate your prompt and helpful feedback. If I encounter any further issues or need additional assistance, I'll provide a runnable reproduction for more detailed troubleshooting.

Thank you for your support.

Best regards,
Fahim Ahammed Firoz
