### ISSUE TITLE
2D Array Support

### ISSUE THREAD

**Issue by Nik-Novak** [prisma/prisma#24586]
## Problem
Prisma lacks a way of representing 2D arrays (Mongo and Postgres support these)

## Suggested solution
Add support for Float[][] for GeoJSON for example. It sucks to not have validation using Json

**Comment by Nik-Novak** [comment]
```
enum GeometryType {
  Polygon
}
type Geometry {
  type          GeometryType
  coordinates   Float[][]
}
```

**Comment by SevInf** [comment]
Hi @Nik-Novak.
There is already a feature request for diminutional arrays. Please, follow issue #15676 issue for updates, i am going to close this one as a duplicate.
Thank you!
