### ISSUE TITLE
[@prisma/instrumentation] Version 15.14.0 onwards using non existing generic in InstrumentationNodeModuleDefinition form @opentelemetry/instrumentation Library

### ISSUE THREAD

**Issue by Marlrus** [prisma/prisma#24599]
### Bug description

When adding `@prisma/instrumentation` to a repository and using esbuild I was getting failed to bundle errors. The error message was the following:

```
node_modules/@prisma/instrumentation/dist/PrismaInstrumentation.d.ts:8:13 - error TS2315: Type 'InstrumentationNodeModuleDefinition' is not generic.

8     init(): InstrumentationNodeModuleDefinition<unknown>[];
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in node_modules/@prisma/instrumentation/dist/PrismaInstrumentation.d.ts:8
```

The `@opentelemtry/<PACKAGE>` packages in the `package.json` dependencies are the following:

```
  "dependencies": {
    "@opentelemetry/api": "^1.8",
    "@opentelemetry/instrumentation": "^0.49 || ^0.50 || ^0.51 || ^0.52.0",
    "@opentelemetry/sdk-trace-base": "^1.22"
  },
```

Looking at the definitions directly in the `@opentelemetry/instrumentation` package, there is no support for a generic in `InstrumentationNodeModuleDefinition` on supported versions:

```typescript
export declare class InstrumentationNodeModuleDefinition implements InstrumentationModuleDefinition {
   ...
}
```

and 

```typescript
export interface InstrumentationModuleDefinition {
  ...
}
```

I checked all of the versions outlined in dependencies and none of them could support the generic.

[Link to file in repo](https://github.com/prisma/prisma/blob/main/packages/instrumentation/package.json)

I am currently explicitly running the following versions in my `package.json`:

```
"@opentelemetry/api": "^1.8.0",
"@opentelemetry/sdk-trace-base": "^1.24.1",
```

and `@opentelemetry/instrumentation@0.51.1` is being used as the implicit dependency in my dependency tree.

All of the dependencies seem to be in line minus `sdk-trace-base`, however the issue is with `@opentelemetry/instrumentation`. I have changed the version of the package multiple times to no success.

The only solution was to revert `@prisma/instrumentation` back to version 15.13.0 where everything worked again.

Current instrumentation file imports and relevant call to `registerInstrumentations`:

```typescript
import * as otel from '@opentelemetry/api';
import * as semcon from '@opentelemetry/semantic-conventions';
import * as logsapi from '@opentelemetry/api-logs';
import {
  LoggerProvider,
  SimpleLogRecordProcessor,
  ConsoleLogRecordExporter,
} from '@opentelemetry/sdk-logs';
import {
  ConsoleSpanExporter,
  NodeTracerProvider,
} from '@opentelemetry/sdk-trace-node';
import {
  BatchSpanProcessor,
  SimpleSpanProcessor,
} from '@opentelemetry/sdk-trace-base';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import { OTLPLogExporter } from '@opentelemetry/exporter-logs-otlp-http';
import { Resource } from '@opentelemetry/resources';

import { registerInstrumentations } from '@opentelemetry/instrumentation';
import { AwsLambdaInstrumentation } from '@opentelemetry/instrumentation-aws-lambda';
import { HttpInstrumentation } from '@opentelemetry/instrumentation-http';
import { DnsInstrumentation } from '@opentelemetry/instrumentation-dns';
import { NetInstrumentation } from '@opentelemetry/instrumentation-net';
import { WinstonInstrumentation } from '@opentelemetry/instrumentation-winston';
import { PrismaInstrumentation } from '@prisma/instrumentation';

/** Skipping rest of file */

registerInstrumentations({
  instrumentations: [
    new DnsInstrumentation(),
    new HttpInstrumentation(),
    new NetInstrumentation(),
    new AwsLambdaInstrumentation(),
    new WinstonInstrumentation(),
    new PrismaInstrumentation(),
  ],
});
```

### How to reproduce

- Install @prisma/instrumentation version 15.14.0 or over along with @opentelemetry/api at ^1.8.0"
and @opentelemetry/sdk-trace-base at version ^1.24.1
- Create otel intsrumentation file with the configuration above.
- Exclude all prisma and otel packages from esbuild bundler

```typescript
[
  '@prisma/client',
  '@opentelemetry/api',
  '@opentelemetry/api-logs',
  '@opentelemetry/resources',
  '@opentelemetry/semantic-conventions',
  '@opentelemetry/sdk-trace-base',
  '@opentelemetry/sdk-trace-node',
  '@opentelemetry/sdk-logs',
  '@opentelemetry/exporter-trace-otlp-http',
  '@opentelemetry/exporter-logs-otlp-http',
  '@opentelemetry/instrumentation-aws-lambda',
  '@opentelemetry/instrumentation-http',
  '@opentelemetry/instrumentation-dns',
  '@opentelemetry/instrumentation-net',
  '@opentelemetry/instrumentation-winston',
  '@opentelemetry/winston-transport',
  '@prisma/instrumentation',
  'winston',
]
```

- Bundle code

I suspect that this error might happen regardless of bundling as the generic does not exist in the supported versions of `@opentelemetry/instrumentation`

### Expected behavior

Code should be able to build and compile with the listed supported versions of `@opentelemetry/instrumentation` on version 15.14.0 onwards.

**Note:** Everything works with 15.13.0 and below and I have the exact same setup in another repository that worked because it was using 15.12.0.

### Prisma information

Issue is not with the client, as the client works properly, adding the base `prisma.schema` configuration here as it was asked.

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["tracing"]
  binaryTargets   = ["native", "rhel-openssl-3.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("IS_PG_DB_URL")
}
```

No errors using prisma client at all, excluding client use.

### Environment & setup

- OS: Ubuntu 22.04.4 LTS x86_64 
- Database: Amazon RDS Instance Postgres 16.1
- Node.js version: nodejs20.x

### Prisma Version

```
prisma                  : 5.15.1
@prisma/client          : 5.15.1
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.12.2
Query Engine (Node-API) : libquery-engine 5675a3182f972f1a8f31d16eee6abf4fd54910e3 (at ../../../.nvm/versions/node/v20.12.2/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 5675a3182f972f1a8f31d16eee6abf4fd54910e3 (at ../../../.nvm/versions/node/v20.12.2/lib/node_modules/prisma/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.15.1-1.5675a3182f972f1a8f31d16eee6abf4fd54910e3
Default Engines Hash    : 5675a3182f972f1a8f31d16eee6abf4fd54910e3
Studio                  : 0.501.0
```

**Comment by SevInf** [comment]
`@opentelemetry/api@1.8.0`  has this generic and `@opentelemetry/api@1.9.0` does not. Looks like we were too generous with our version ranges (but also, looks look otel people did a braking change in semver-minor). Meanwhile, I can confirm that the next Prisma version (5.16.0, planned for next Tuesday, June 25) will not have this generic anymore. 
I'll keep this issue open so we won't forget to revise and test our supported ranges.

**Comment by Marlrus** [comment]
Thank you for the prompt reply and analysis @SevInf 

I will update to 5.16.0 on the 25th!

**Comment by AlexZodov** [comment]
Prisma everything version is 5.22.0
Also had this problem

Solved by adding to package.json file 
`"@opentelemetry/instrumentation": "^0.57.0",` - this exact version has removed problem generic usage
