### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier ".prisma/client/index-browser". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by bbhxwl** [prisma/prisma#24620]
### Bug description

Uncaught TypeError: Failed to resolve module specifier ".prisma/client/index-browser". Relative references must start with either "/", "./", or "../".

![image](https://github.com/prisma/prisma/assets/26525599/793235c8-77fb-46ec-95e4-1da0e4729bcd)

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by SevInf** [comment]
Hi @bbhxwl!
Please, fill out the issue template. Without this information there is no way for us to reproduce the issue and we'll have to close it. Thank you!

**Comment by Weakky** [comment]
Hey @bbhxwl,

This is a friendly ping as we need further information to reproduce your issue. Please have a look at @SevInf's comment so that we can move this forward. Thanks 🙏

**Comment by hymair** [comment]
This happens when you import prisma types on the frontend.

**Comment by SevInf** [comment]
Hey @bbhxwl ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
