### ISSUE TITLE
Relative paths in datasource URL handled differently with prismaSchemaFolder preview feature

### ISSUE THREAD

**Issue by darkv** [prisma/prisma#24647]
### Bug description

When using the _prismaSchemaFolder_ preview feature in an Nx workspace where the prisma related files are located in a library instead of the project root, the base dir used to resolve relative paths within the datasource URL differs between prisma CLI and runtime context.

### How to reproduce

I have an Nx workspace that has a structure like:

```
 ┣ apps
 ┃ ┗ …
 ┣ db
 ┃ ┣ certificate.pem
 ┃ ┗ …
 ┣ libs
 ┃ ┗ prisma-client
 ┃     ┣ prisma
 ┃     ┃ ┣ migrations
 ┃     ┃ ┗ schema
 ┃     ┃     ┣ item.prisma
 ┃     ┃     ┗ schema.prisma
 ┃     ┣ src
 ┃     ┗ …
 ┣ .env
 ┗ …
```

The lib _prisma-client_ contains the prisma directory and is imported in a NestJS application that resides under _apps_. The database URL for prisma is set in the .env file in the project root with

```sh
DATABASE_URL="mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@${MARIADB_SERVER}:${MARIADB_PORT}/${MARIADB_DATABASE}?sslmode=require&sslcert=../../../../db/certificate.pem"
```

Running e.g. the command `npx prisma db push` within _libs/prisma-client_ works. Note that the relative path of _sslcert_ starts on the level of the _schema.prisma_ file.

When starting the NestJS application it fails with the error:

> PrismaClientInitializationError: Can't reach database server at `localhost:3306`
> 
> Please make sure your database server is running at `localhost:3306`.

Changing the relative path within the .env file to `../../../db/certificate.pem` – that is one level less than before – and starting the app succeeds. But now of course the prisma CLI stops working as it cannot resolve that file anymore.

Going back to a single prisma schema file (i.e. not using _prismaSchemaFolder_ feature) fixes the observed discrepancy. Prisma CLI and starting the app are working with the same relative path.

### Expected behavior

The base dir for relative paths should be same regardless of going with a single _schema.prisma_ or using the _prismaSchemaFolder_ preview feature.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["prismaSchemaFolder"]
}

datasource mysql {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Item {
  id   Int    @id @default(autoincrement())
  name String
}
```

### Environment & setup

- OS: macOS
- Database: MariaDB
- Node.js version: v20.13.1

### Prisma Version

```
prisma                  : 5.16.0
@prisma/client          : 5.16.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.13.1
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at ../../../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at ../../../node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
Preview Features        : prismaSchemaFolder
```

**Comment by SevInf** [comment]
Hi @darkv !
We've identified and fixed the issue. Could you try dev snapshot version `5.18.0-integration-fix-config-dir-client.5` and see if the problem still happens for you? We don't recommend using dev snapshot in production, but it is good enough to ensure the fix will work for you when it is released.
Thank you!

**Comment by darkv** [comment]
Hi @SevInf,
Thanks for having a look at that issue! I updated both, prisma and @prisma/client, to that snapshot version and now app and prisma CLI are working as expected with the same relative path 🙂

Thanks a lot! 👍🏻

**Comment by Goop-arsh** [comment]
```

```
