### ISSUE TITLE
Generated JSON query is incorrect

### ISSUE THREAD

**Issue by Aloysius999** [prisma/prisma#24671]
### Bug description

I raised a similar JSON query problem some months ago, and despite several new releases of Prisma in the meantime, the problem persists.

_**This problem is a show-stopper for me.**_

The problem is with the JSON extraction query code generated by Prisma - 

The Prisma MySQL query distils down to 

```
SELECT messageBody FROM testMessage 
WHERE (JSON_UNQUOTE(JSON_EXTRACT(messageBody, '$.messageText'))) LIKE "%test%";
```

**returns 0 records**

switching the order of the JSON functions - to UNQUOTE **before**  EXTRACT

```
SELECT messageBody FROM testMessage 
WHERE (JSON_EXTRACT(JSON_UNQUOTE(messageBody), '$.messageText')) LIKE "%test%";
```

**returns  1+ records,**

![image](https://github.com/prisma/prisma/assets/90618210/a79f3364-a357-4483-ac5b-20b264fd2594)

To verify, I ran these queries in MySQL
![image](https://github.com/prisma/prisma/assets/90618210/dddce5fc-12fc-4d1a-9257-df5058401b78)

and
![image](https://github.com/prisma/prisma/assets/90618210/2f570ff6-ca06-46bf-8458-9849989d7279)

and with UNQUOTE before EXTRACT

![image](https://github.com/prisma/prisma/assets/90618210/bdb58393-71d1-44de-a30e-21cc26708758)

To eliminate any case sensitivity, I tried various combinations of case for messagebody and messagetext.  Only the UNQUOTE before EXTRACT worked.

### Expected behavior

The expected behavior is the return of at least one record.

### Prisma information

```prisma
// Add your schema.prisma
```
model testMessage {
  id Int @id @default(autoincrement()) @db.UnsignedInt
  subject String
  messageBody Json?
}
```
// Add your code using Prisma Client
```

### Environment & setup

```
Windows 10 Pro

npm node -v
10.8.1
 "next": "^14.1.4",

MySQL v8
```

### Prisma Version

```
npm prisma -v
10.8.1

  "@prisma/client": "^5.15.0",
 "prisma": "^5.15.0",
```

**Comment by Aloysius999** [comment]
This issue persists in Prisma version 5.16.1

**Comment by Aloysius999** [comment]
This issue still persists in Prisma version 5.17.0

**Comment by Aloysius999** [comment]
This issue now holding me up and I can not progress with my search feature.

I have tried creating a raw query and for example this query works fine - and yields the expected results:

```
SELECT *
FROM instruments 
WHERE (LOWER(JSON_EXTRACT(JSON_UNQUOTE(instruments.itemData), "$.instrument.description")) LIKE LOWER("%guitar%")
OR
LOWER(JSON_EXTRACT(JSON_UNQUOTE(instruments.itemData), "$.instDescription.manufacturer")) LIKE LOWER("%Martin%")
OR
LOWER(JSON_EXTRACT(JSON_UNQUOTE(instruments.itemData), "$.instDescription.model")) LIKE LOWER("%Prof II%")
OR
LOWER(JSON_EXTRACT(JSON_UNQUOTE(instruments.itemData), "$.instDescription.productCode")) LIKE LOWER("%x123%")
OR
LOWER(JSON_EXTRACT(JSON_UNQUOTE(instruments.itemData), "$.instDescription.description")) LIKE LOWER("%martin%"));

```

Notice the order of `JSON_EXTRACT(JSON_UNQUOTE(`

But I can not use the raw query going forward since my queries are rather complex and had hoped that Prisma Filtering and Sorting features would help me achieve my goal.  If I use similar filtering queries without the filtering on JSON content, the queries work fine.  As soon as I filter on JSON content the query fails because of the` JSON_EXTRACT/JSON_UNQUOTE` problem,

I have looked at the Prisma source in view of making this change myself, but could not locate the code where MySQL statements are generated.  Maybe someone could point me at the place in the code.  I'll fix it myself and push my contribution to Git.

I'd also very much appreciate someone from the dev team taking a look at this issue as soon as possible.

Thanks

**Comment by SevInf** [comment]
You provided query does not match the schema you posted and you provided response does not match the query you are showing us either. Could you please go back to the issue template and fill out all the missing information, ensuring all entries much with each other?

If I have to guess - it looks you are stringifying the data before writing the data to JSON column - you should not do that, prisma will stringify the data for you. Single string is a valid JSON value, so if you supply a string as input, that string would be the value of JSON field, not the JSON value it describes. Could you show us writing code for this?

And just to put an end to the point you are making here - no, `JSON_UNQUOTE` and `JSON_EXTRACT` should absolutely not change places. This will break most of the quoted JSON strings, as in [example here](https://www.db-fiddle.com/f/pgfossBFQdLzVNm3YZS59f/0).

**Comment by SevInf** [comment]
Hey @Aloysius999 ,
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
