### ISSUE TITLE
Prisma not able to migrate in dev in latest version

### ISSUE THREAD

**Issue by haroon-schmrkow** [prisma/prisma#24690]
### Bug description

Since updating from `5.7.1` to `5.16.0`, we are unable to execute migrations in dev and getting a cryptic error:

```
Error: Error in RPC
 Request: {
  "id": 3,
  "jsonrpc": "2.0",
  "method": "evaluateDataLoss",
  "params": {
    "migrationsDirectoryPath": "/.../monorepo/packages/prisma/migrations",
    "schema": {
      "files": [
        {...}]

... redacted ...

Response: {
  "jsonrpc": "2.0",
  "error": {
    "code": -32602,
    "message": "Invalid params: missing field `prismaSchema`."
  },
  "id": 3
}
Invalid params: missing field `prismaSchema`.
```

### How to reproduce

1. use latest prisma package
2. execute migrations

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: MacOS
- Database: PG
- Node.js version: v20.15.0

### Prisma Version

```
prisma                  : 5.16.0
@prisma/client          : 5.16.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.15.0
Query Engine (Node-API) : libquery-engine 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5 (at ../../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5 (at ../../node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5
Studio                  : 0.502.0
```

**Comment by SevInf** [comment]
Hi @haroon-schmrkow.
Looks like your update have not finished correctly. The hash of the engine for 5.16.0 should be `34ace0eb2704183d2c05b60b52fba5c43c13f303`, you have `0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5`, which is half a year older than 5.16.0. Could you try cleaning `node_modules` and caches and updating again? After the update `prisma --version` should output `34ace0eb2704183d2c05b60b52fba5c43c13f303` as a version for both `libquery-engine` and `schema-engine-cli`.

**Comment by haroon-schmrkow** [comment]
That was it @SevInf, thanks!
