### ISSUE TITLE
Prisma client defined in .js file instead of .ts breaks intellisense in vscode

### ISSUE THREAD

**Issue by UROjQ6r80p** [prisma/prisma#24722]
### Bug description

When prisma client instance is defined in .js file with custom extension, VSCode does not provide intellisense at all.

### How to reproduce

```
// prisma.js
const prisma = new PrismaClient().$extends({
  result: {
    user: {
      fullName: {
        // the dependencies
        needs: { firstName: true, lastName: true },
        compute(user) {
          // the computation logic
          return `${user.firstName} ${user.lastName}`
        }
      }
    }
  }
})

export { prisma }
```

```
// example.js
import { prisma } from './prisma.js'

prisma.user // no intellisense at all
```

if extension of prisma file is .ts all works as expected. but i dont use typescript in my project so i cant use client extensions without breaking intellisence in vscode.

### Prisma information

No prisma information, it's related to VSCode

### Environment & setup

Windows 10, VSCode

### Prisma Version

```
5.14.0
```

**Comment by jkomyno** [comment]
Hi @UROjQ6r80p, thanks for the issue, we're already aware of this problem and are tracking it in https://github.com/prisma/prisma/issues/24648.
