### ISSUE TITLE
[SQLite] Bug in `prismaSchemaFolder`: Incorrect Database File Generation and Missing Table Error

### ISSUE THREAD

**Issue by Typeve** [prisma/prisma#24779]
### Bug description

When using Prisma and SQLite in NestJS and the new feature prismaSchemaFolder, with datasource db.url = "file:./dev.db". `prisma db push`, a dev.db file will be generated under prisma/schema. But when the application is running, for example, when accessing an API that uses Prisma Client, a dev.db will be generated under the prisma folder, which is a blank database.an error is reported: The table `main.Project` does not exist in the current database. 
![image](https://github.com/user-attachments/assets/ab875c2f-56dd-412b-89ed-aad8e1d6a7e3)
![image](https://github.com/user-attachments/assets/f19ef09c-7fab-4ac1-a828-4a07bb44b07c)

__

### How to reproduce

1. use prismaSchemaFolder
2. db.url = "file:./dev.db"
3. prisma db push
4. access API with prismaService

### Expected behavior

Use the dev.db file under prisma/schema

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["prismaSchemaFolder"]
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

```

```
@Injectable()
export class AppService {
  constructor(private prisma: PrismaService) {}
  getHello() {
    return this.prisma.project.create({
      data: {
        name: 'test',
        description: 'test',
      },
    });
  }
}

```

### Environment & setup

- OS: Windows11
- Database: SQLite
- Node.js version: v20.15.0

### Prisma Version

```
prisma                  : 5.16.2
@prisma/client          : 5.16.2
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.15.0
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules\.pnpm\@prisma+engines@5.16.2\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules\.pnpm\@prisma+engines@5.16.2\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
Preview Features        : prismaSchemaFolder
```

**Comment by SevInf** [comment]
Hi @Typeve!
We've identified and fixed the issue. Could you try dev snapshot version `5.18.0-integration-fix-config-dir-client.5` and see if the problem still happens for you? We don't recommend using dev snapshot in production, but it is good enough to ensure the fix will work for you when it is released.
Thank you!

**Comment by Typeve** [comment]
> Hi @Typeve! We've identified and fixed the issue. Could you try dev snapshot version `5.18.0-integration-fix-config-dir-client.5` and see if the problem still happens for you? We don't recommend using dev snapshot in production, but it is good enough to ensure the fix will work for you when it is released. Thank you!

Thank you very much, I upgraded both prisma and @prisma/client to the snapshot version, and the problem I encountered was completely fixed!
Does this mean that this fix will be released in version 5.18?

**Comment by SevInf** [comment]
@Typeve thank you for confirmation!
Yes, most likely 5.18.0 will be the first stable version to receive the fix.
In the meantime, you can workaround the issue by explicitly providing DB path when instantiating the client:

```ts
new PrismaClient({ datasourceUrl: `file:${absoultePathToDbFile}` })
```

**Comment by merry75** [comment]
thanks for the workdaround had same issue
