### ISSUE TITLE
createManyAndReturn include do not work with relations defined on other table

### ISSUE THREAD

**Issue by wilau2** [prisma/prisma#24770]
### Bug description

createManyAndReturn include is missing relations that findMany has

### How to reproduce

look at prisma information

### Prisma information

```prisma
model Animal {
  id                  String               @id @default(uuid())
  tenantId            String               @map("tenant_id")
  tenant              Tenant               @relation(fields: [tenantId], references: [id])
  duck Duck?

  @@unique([id, tenantId])
  @@map("apple")
}

model Duck {
  id           String              @id @default(uuid())
  tenantId     String              @map("tenant_id")
  tenant       Tenant              @relation(fields: [tenantId], references: [id])
  animal Animal        @relation(fields: [id, tenantId], references: [id, tenantId])
  name     String              @map("name")

  @@unique([id, tenantId])
  @@map("duck")
}
```

```ts
getPrismaClient.animal.createManyAndReturn({data: [{
id: 'auuid',
tenantId: 'anotherUUid',
duck: {
create: {
 name: 'quack'
}
}
}], include:{tenant:true}});
```
duck is not typed in typescript...

### Environment & setup

- OS: macOs
- Database: PostgreSQL
- Node.js version: 18.19.1

### Prisma Version

```
5.16.2
```

**Comment by jkomyno** [comment]
Hi @wilau2, what you're observing (which I've reproduced with Prisma 5.16.2) is an expected scenario.
In fact, quoting Prisma Docs,

> You **cannot** create or connect relations by using nested `create`, `createMany`, `connect`, `connectOrCreate` queries inside a top-level `createManyAndReturn()` query.

Hope that helps! Thanks
