### ISSUE TITLE
[FEATURE] Prisma: Full Reactive and Scaling Interaction With Databases

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [prisma/prisma#2477]
Absolutely the whole backend should be reactive by default. declarative and reactive. like ReactJS, only on the server. frameworks like Prisma should increase the level of abstraction and add something like reactiveQuery. the reactive backend does not work slower, but FASTER than the usual backend if a sufficiently fine grain of reactivity is made. IMHO

like this:
```javascript
function apiMethod() {
  let user =  prisma.user.get({id})
  if(!admin.admin) return null
  return prisma.user.getAll()
}

prisma.autorun(apiMethod, function(result){
   // result
})
```

and this function autostart when hes dependend changed, using selectors setters and getters prisma will detect depending fields, and if dependents CAN be change, prisma rerun the function. like in Meteor framework. for example, if we make the mutation `admin.admin = true`, then the dependency has changed, and the reactive function will be recall just in case.

Using these basic principles of reactivity, people will be able to build a declarative and reactive backend that will not slow down. since all the optimizations for them will be done by Redis and Prisma

Based on this, it will be possible to build GraphQL live queries and whatever.

we can create a class `Tracker` like this:

```javascript
// add dependency type for sql selectors
Tracker.addDependencyType("selector", class SQLSelectorDependency {
  constructor (dependSelector) {
    this.dependSelector = dependSelector
  }

  maybeChange (sqlMutation){
     // check if sqlMutation CAN change this.dependSelector  result
  }
})


// reactive tracker
tracker = new Tracker()

// when reactive function calls we register dependinigs
tracker.depend("selector", "SQL SELECTOR CODE")


// when mutations
tracker.checkMaybeChange("selector", "SQL MUTATION CODE")
```

and in this way, users can add custom dependencies, as well as manually call them, for example, if a message comes from Redis. thus, even if the user interacts with the database not through Prisma, the Prisma reactivity system will feel it. in reactive systems, you can perform pure reactive functions at any time, just in case, and for optimization we can compare the previous result and the new one, and if they are the same, do not send data to the client. just like React doesn't update DOM =) This is an example concept explaining the overall architecture, in this way Prisma will support reactive work with the database. This killerfeature will make everyone's brain =)

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/298
