### ISSUE TITLE
Create only is applying the migration

### ISSUE THREAD

**Issue by selva-linqhaul** [prisma/prisma#24787]
### Bug description

prisma migrate dev --create-only instead of just creating migration its applying the migration also

```
dotenv -e .env.stage npx prisma migrate dev --create-only 
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Enter a name for the new migration: … ***
Applying migration `20240713092326_***`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20240713092326_***/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (v5.16.2) to ./node_modules/@prisma/client in 257ms
```

### How to reproduce

prisma migrate dev --create-only

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS:  macOS
- Database: PostgreSQL
- Node.js version: v20.14.0

### Prisma Version

```
v5.16.2
```

**Comment by apolanc** [comment]
Hi @selva-linqhaul,

Thanks for providing the details. I can see that: `dotenv -e .env.stage npx prisma migrate dev --create-only` clearly doesn't work. 

Based on the [dotenv-cli doc](https://www.npmjs.com/package/dotenv-cli), you should add the -- between the commands. I confirm that doing:

`dotenv -e .env.stage -- npx prisma migrate dev --create-only` works for me.

Could you please try and let us know if the problem still persist. Thank you

**Comment by ItWorksOnMyMachine** [comment]
@apolanc, this is a problem I'm experiencing also, and I have the -- between the dotenv and npx prisma commands.  Here's the output.  Any thoughts?

PS C:\dev\Workspaces\Personal\test\test\web> dotenv -e .env.development -- npx prisma migrate dev --create-only
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "test", schema "public" at "localhost:5432"

Applying migration `20250108192035_init`

The following migration(s) have been applied:

migrations/
  └─ 20250108192035_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (v6.2.1) to .\node_modules\@prisma\client in 63ms

**Comment by ItWorksOnMyMachine** [comment]
And just to test, I reset everything and tried it without running dotenv and it works as expected.  So, this is an issue with using dotenv along with the --create-only option
