### ISSUE TITLE
One model to multiple database schemas for multi-tenancy

### ISSUE THREAD

**Issue by LucasShaffer** [prisma/prisma#24794]
## Problem

As a developer, I want to be able to build multi tenant databases, so that I can build bigger better apps with ease. The [multi schema database](https://www.prisma.io/docs/orm/prisma-schema/data-model/multi-schema) looks like the closest solution at the moment. The frustration with it is that I would need to have a model with a unique name defined for each tenant. So if I have 25 tables and I need to add a new tenant then I need to duplicate all those models and get a unique name for each of those. Another option that give me frustration is a schema folder for each tenant. Just a log of duplication and modifications needed for each model for each tenant. 

## Suggested solution

To allow for the multiple database schema ("multiSchema") preview feature to support an "apply to all schemas" flag such as @@schema("all") or @@schema("*")

## Alternatives

Allow for the `migrate` and `deploy` commands to have a `--database` or `--database_name` flag. That way I could use a script at deploy time that can run `npx prisma migrate deploy --database tenant_1` for multiple databases. Then I could connect to each one when needed by overriding the datasource using:
```
const prisma = new PrismaClient({
    datasources: {
      db: {
        url: databaseUrl,
      },
    },
  });
```

## Additional context

No additional content.

**Comment by SevInf** [comment]
You can already use environment variables when running `migrate deploy` to override the URL. Provided that your datasource URL is defined as `env("DATABASE_URL")` in your schema:

```sh
DATABASE_URL=postgresql:///example.com/db?schema=tenant1 pnpm prisma migrate deploy
DATABASE_URL=postgresql:///example.com/db?schema=tenant2 pnpm prisma migrate deploy
```

And then override DB url in Prisma constructor like you pointed out. Does that work for you? 
Multi-schema feature is not really designed for your usecase, it's rather targeted for people that have different models in different schemas.

**Comment by LucasShaffer** [comment]
Sorry about the late response. This works for what I need. Thank you!
