### ISSUE TITLE
Prisma client not working.

### ISSUE THREAD

**Issue by KarkiGaurav** [prisma/prisma#24830]
### Bug description

Error: PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in unknown).
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by SevInf** [comment]
Hi @KarkiGaurav.
Looks like you ignored our issue template. Without this information, there is no way for us to diagnose the issue and help you, so I am going to close it. Please, open a new issue, fill the template and provide the rerpoducible example and we'll gladly help.
Thank you!
