### ISSUE TITLE
Incorrect type inferred when using omit + include inside of an include.

### ISSUE THREAD

**Issue by danielluna90** [prisma/prisma#24835]
### Bug description

When using the omit type with an include the inferred type is as intended. However, when using an omit and include inside of an include (nested), the type inferred is not correct. The output of the function is correct and the fields are correctly omitted.

Here is a minimal example:
```prisma
model A {
  id Int @id @default(autoincrement())

  model_b B[]
}

model B {
  id Int @id @default(autoincrement())

  a_id Int
  a    A   @relation(fields: [a_id], references: [id])

  private_field String

  c_id Int
  c    C   @relation(fields: [c_id], references: [id])
}

model C {
  id Int @id @default(autoincrement())

  public_field String
  B            B[]
}
```

Example 4 in my minimal example repository shows that a top-level omit + include is correctly inferred whilst a second-level (nested) omit + include is not correctly inferred. Here is the code used.

```ts
const example_four = await prisma.a.findFirst({
  include: {
    model_b: {
      include: {
        c: true,
      },
      omit: {
        private_field: true,
      },
    },
  },
  omit: { id: true },
});
```

The inferred type is as follows:
```ts
({
  model_b: ({
    c: {
      id: number;
      public_field: string;
    };
  } & {
    id: number;
    a_id: number;
    private_field: string;
    c_id: number;
  })[];
} & {}) | null
```
Notice that `A.id` is omitted in the type but `A.model_b.private_field` is not.

Example 5 is similar to the original case which resulted in me noticing this behavior. It is very similar to example 4. In Example 4 I omit a non-relationship field. In this example I omit the relation field `c_id`. Like in example 4, the type is wrong but the output is correct.

### How to reproduce

1. Go to `https://github.com/danielluna90/prisma-nested-omit-type-inference-min-example`
2. `cd prisma-nested-omit-type-inference-min-example`
3. Set `.env`
4. Run `npm i`
5. Run `npm start`
6. Check type interferences and console output

### Expected behavior

The resultant inferred type generated should not include the omitted fields.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["omitApi"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model A {
  id Int @id @default(autoincrement())

  model_b B[]
}

model B {
  id Int @id @default(autoincrement())

  a_id Int
  a    A   @relation(fields: [a_id], references: [id])

  private_field String

  c_id Int
  c    C   @relation(fields: [c_id], references: [id])
}

model C {
  id Int @id @default(autoincrement())

  public_field String
  B            B[]
}
```

```ts
// This is one of two non-working examples. Three working examples and one more non-working example are available at the GitHub repository linked above.
async function example_four_func() {
  const example_four = await prisma.a.findFirst({
    include: {
      model_b: {
        include: {
          c: true,
        },
        omit: {
          private_field: true,
        },
      },
    },
    omit: { id: true },
  });

  // Property 'id' does not exist on type '{ model_b: ({ c: { id: number; public_field: string; }; } & { id: number; a_id: number; private_field: string; c_id: number; })[]; } & {}'. ts(2339)
  // example_four?.id;

  // No Type Error
  example_four?.model_b[0].private_field;

  console.log("Example Four");
  console.log(example_four);
  console.log(
    "example_four->model_b->private_field:",
    example_four?.model_b[0].private_field
  ); // Returns undefined
  console.log("===================================================");
}
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v21.7.0
- Typescript version: v5.5.3

### Prisma Version

```
prisma                  : 5.17.0
@prisma/client          : 5.17.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.7.0
Query Engine (Node-API) : libquery-engine 393aa359c9ad4a4bb28630fb5613f9c281cde053 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 393aa359c9ad4a4bb28630fb5613f9c281cde053 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.17.0-31.393aa359c9ad4a4bb28630fb5613f9c281cde053
Default Engines Hash    : 393aa359c9ad4a4bb28630fb5613f9c281cde053
Studio                  : 0.502.0
Preview Features        : omitApi
```

**Comment by JackCme** [comment]
Having same problem with select also.
```ts
const designOutputWithRelations = {
  include: {
    DesignVersion: {
      select: { designId: true, version: true },
    },
    User: designOutputUserFields,
    DesignOutputDownloadHistory: {
      select: { userId: true },
      include: {
        User: designOutputUserFields,
      },
    },
  },
} satisfies Prisma.DesignOutputFindManyArgs;

export type DesignOutputWithRelations = Prisma.DesignOutputGetPayload<
  typeof designOutputWithRelations
>;
```

I expected that the inferred type of `DesignOutputWithRelations.DesignOutputDownloadHistory` should only have `User` and selected `userId`, but instead infers as such:

```ts
...
DesignOutputDownloadHistory: ({
        userId: string;
        User: {
            id: string;
            email: string;
            name: string | null;
            avatar: string | null;
            avatarThumbnail: string | null;
        };
    } & {
        id: string;
        designOutputId: string;
        userId: string;
        createdAt: Date;
    })[];
...
```

**Comment by HRM** [comment]
I did a bit of experimentation around this:

First, I made a bit of addition to the findFirst function on the fourth example posted above.
<img width="713" alt="modification" src="https://github.com/user-attachments/assets/e727540e-d9f3-4c8e-b45e-e08ca79ee807">

This way we can get back the type of generic argument.

This is what typescript says about the value of the generic argument.
<img width="874" alt="template_param" src="https://github.com/user-attachments/assets/b915dd61-0dda-4a2a-816a-3f65d6a17960">

Yep, if we uncomment line 22 and we try to compile the code
<img width="848" alt="error" src="https://github.com/user-attachments/assets/c217bc16-aa2c-460e-bdc8-8aa0e2c258b5">
the language server and the compiler agree.

**Here comes the twist**
<img width="871" alt="manual" src="https://github.com/user-attachments/assets/eaa62312-f0d1-4929-abd9-db680d2f8eb5">
If I provide the same value manually to the generic argument.... it works as it should.

Is this a bug in the typescript compiler?

**Comment by JackCme** [comment]
Will this issue be addressed?

**Comment by aqrln** [comment]
> Will this issue be addressed?

Yes.

Just so you know, we now have a public roadmap: https://github.com/prisma/prisma/issues/25794. One of the things we are working on this quarter is shipping five highly-requested features. The exact list is still being finalized but what we definitely commit to is shipping `omitApi` in GA, since https://github.com/prisma/prisma/issues/5042 is the number 1 most popular feature request. Currently this issue is the only thing which is blocking the `omitApi` from moving from Preview to GA, so naturally it is going to be addressed soon.
