### ISSUE TITLE
Please add a flag to disable ALL ADS in my terminal window

### ISSUE THREAD

**Issue by incompletude** [prisma/prisma#24865]
## Problem

Tip: Easily identify and fix slow SQL queries in your app. Optimize helps you enhance your visibility: https://pris.ly/--optimize

## Suggested solution

Add a flag to disable ALL ADS when running prisma commands.

--no-ads

## Additional context

Come on, guys, this is very intrusive. The last place I want to see an ad is in my terminal window. Every time I see it, I want to migrate to another library. This is very disrespectful. Advertise your products on YOUR website, not in MY terminal.

**Comment by apolanc** [comment]
Hello @incompletude,

Thank you for expressing your opinion. Our CLI is our only way to interact with our ORM users. We have recently cleaned up the CLI output to only show relevant information and remove additional output messages. Along with those changes, we have also added some one-line `Tips` about things and products that we feel could be beneficial and bring some value to our users.

Prisma ORM is an open source tool and it is free to use. If the ORM is bringing value to you we're very happy! if it's not, it is ultimately your decision to stop using it.

That being said, our [CLI documentation](https://www.prisma.io/docs/orm/reference/prisma-cli-reference) shows you how to hide hints by just including the `--no-hints` flag in your command.

I hope this answers your questions. Have a nice day!

**Comment by incompletude** [comment]
The CLI is not the only way Prisma have to interact with users. There is newsletter, the website, etc. The `no-hints` should remove it all, period.

I will write a `npm-ad-blocker` package to `post-install` that shit out, and I sure will migrate when other libs get more mature for production.

This is very intrusive and disrespectful, the terminal window is my environment, you have no business advertising here.
