### ISSUE TITLE
Dynamic require of "fs" is not supported

### ISSUE THREAD

**Issue by Pablo-Conte** [prisma/prisma#24889]
### Bug description

Hello everyone,

I'm encountering the error "Dynamic require of 'fs' is not supported" when starting my project.

Here's the scenario:

I am setting up a repository that uses Prisma to manage two database connections. For this, I have two clients in my project: one located in the default Prisma folder (@prisma/client) and another within the repository itself, located at @shared/infra/database/prisma-second.

![image](https://github.com/user-attachments/assets/4b43b84f-0058-40fd-9c5e-6c6c474c6657)

Currently, the project is built with esbuild using the "esm" format, which I cannot change. When switching to cjs, the project runs fine. However, when set to "ES modules [esm]", it fails because the files generated by the Prisma client for the second schema dynamically import modules using require.

It is worth noting that the client generated in the default path does not require such dynamic imports, as it does not generate an index.js with a require("fs") statement. Thus, it doesn’t cause any issues. The problem only arises with the client generated for the second database.

The question is: how can I generate the client in an ESM format without dynamic imports?

My generator client
![image](https://github.com/user-attachments/assets/5ed3632c-1d1d-46be-b161-ab6e4b1ee265)

The default prisma client generated (without the require("fs"):
![image](https://github.com/user-attachments/assets/b83dd006-03cb-44ef-aaf1-aa69156188ea)

The Client generated to the second schema with that command: npx prisma generate --schema=./src/shared/infra/database/prisma-second/schema.prisma
![image](https://github.com/user-attachments/assets/9ca9251b-c0f2-464c-920a-53e300818764)

### Expected behavior

I expected the Prisma client to be generated in the same way as the default one, without any changes, without dynamic requires or anything that could break the ESM format.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator docs {
  provider              = "node node_modules/prisma-docs-generator"
  includeRelationFields = false
}

generator dbml {
  provider            = "prisma-dbml-generator"
  output              = "erd"
  outputName          = "erd.dbml"
  projectName         = "Template"
  projectDatabaseType = "PostgreSQL"
  projectNote         = "Consequat aliqua laborum aliquip amet dolore aliquip. Culpa mollit nulla quis quis. Culpa pariatur culpa mollit commodo minim officia anim ea nostrud. Labore in eiusmod minim minim magna laboris laborum tempor nulla culpa culpa. Nisi non eu laborum culpa consequat nisi incididunt aute aute. Exercitation ea duis mollit cillum."
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl-openssl-3.0.x", "rhel-openssl-1.0.x"]
  output        = "./client"
}

datasource db {
  provider = "postgresql"
  url      = env("DB_DIRECT_1")
}

/// Account
model Account {
  id   String @id @default(uuid())
  name String
}

```

```ts
import { logger } from '@/shared/application/logger';
import { PrismaClientOptions } from '@prisma/client/runtime/library';

import { PrismaClient } from './prisma-second/client';

const shouldDebug = process.env.PRISMA_DEBUG == 'true';

const options = {
    datasources: {
        db: {
            url: process.env.DB_URL_2,
        },
    },
    log: [
        {
            emit: 'event',
            level: 'query',
        },
    ],
} satisfies PrismaClientOptions;

if (!shouldDebug) Reflect.deleteProperty(options, 'log');

export const prismaSecond = new PrismaClient(options);

if (shouldDebug)
    prismaSecond.$on('query', async (e) => {
        logger.info(`${e.query} ${e.params}`);
    });

```

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: 20.10.0

### Prisma Version

```
5.17.0
```

**Comment by Pablo-Conte** [comment]
Hey guys! Today, while studying this error, I managed to fix it!

Basically, we need to add the folder with the generated files (client) to the "external" parameter in esbuild:

```typescript
esbuild
    .build({
        entryPoints: splitStdout,
        allowOverwrite: true,
        minify: true,
        sourcemap: true,
        outdir: 'dist',
        platform: 'node',
        logLevel: 'silent',
        external: [
            ...Object.keys(dependencies),
            ...Object.keys(devDependencies),
            '@internal/client',
        ],
        target: ['node20.10.0'],
        bundle: true,
        resolveExtensions: ['.ts', '.js', '.json'],
        format: 'esm',
    })
``` 

In my case, I changed the Prisma generator client output to the node modules, then added the path to the external parameters. After doing this, the error stopped.

**Comment by hubjongit** [comment]
@Pablo-Conte Are you still using 2 separate clients? What does `@internal` alias to?

**Comment by Pablo-Conte** [comment]
man, sorry for the delay.

I've used that alias to work with different connection on different databases.

because of that I needed to work with two different clients, each one with its models.

**Comment by roshcagra** [comment]
FYI, if you follow all of these steps and are then getting something like

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '{some_path}/node_modules/@prisma/internal/client' is not supported resolving ES modules imported from {some_oath}/main.js
```

I got it working by updating the import in my source code to include `index.js` like this:

```
import { PrismaClient } from './prisma-second/client/index.js';
```
