### ISSUE TITLE
Timed out fetching a new connection from the connection pool

### ISSUE THREAD

**Issue by jpetto** [prisma/prisma#24891]
### Bug description

similar to #24844, all prisma operations begin failing with the error:

> Invalid `prisma.{modelName}.{operationName}` invocation:
> Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 5)

(just to be clear - i manually changed the action model name and operation name to the placeholders above. 😅)

### How to reproduce

we seem to be able to reproduce this only by increasing the load/amount of database operations.

### Prisma information

can provide if necessary

### Environment & setup

- Cloud: AWS ECS
- OS: Alpine Linux 3.19.1
- Database: MySQL (Aurora Serverless 5.7.mysql_aurora.2.11.4)
- Node.js version: v20.12.2

### Prisma Version

```
5.13.0
```

**Comment by jkomyno** [comment]
Hi @jpetto, I'm closing this in favor of #24844, as this new issue doesn't add any information.
Please post a self-contained reproduction in #24844, so that we can investigate further. Thanks
