### ISSUE TITLE
updateMany should be able to update columns which are foreign keys

### ISSUE THREAD

**Issue by royra** [prisma/prisma#2493]
Trying the following:

```typescript
await prisma.invitation.updateMany({
  where: { 
    token,
    expiresAt: { gt: now },
  },
  data: {
    status: InvitationStatus.accepted,
    // ERROR: 'acceptedByUserId' does not exist in type 'InvitationUpdateManyMutationInput
    acceptedByUserId: userId,  
  },
})
```

with schema: 
```
model Invitation {
  id               Int       @id @default(autoincrement())
  token            String    @unique
  expiresAt        DateTime
  acceptedByUserId Int?
  acceptedBy       User?     @relation(fields: [acceptedByUserId], references: [id], name: "invitation_acceptedByUserId")
}
```

## Problem

The `InvitationUpdateManyMutationInput` type does not include the column `acceptedByUserId`.

I don't understand why Prisma can't update columns which also happen to be foreign keys.

I know I can use `update` instead, but it doesn't allow me to specify filters which are not unique like `expiresAt: { gt: now }`.

## Suggested solution

Allow Prisma to update foreign key columns.

**Comment by beeplin** [comment]
it is supposed to use `connect` for foreign key updates: 

```js

await prisma.invitation.updateMany({
  where: { 
    token,
    expiresAt: { gt: now },
  },
  data: {
    status: InvitationStatus.accepted,
    // ERROR: 'acceptedByUserId' does not exist in type 'InvitationUpdateManyMutationInput
    acceptedBy: { connect: { id: userId }, // <-- HERE IT GOES
  },
})
```

**Comment by pantharshit00** [comment]
Yes, you can need to use the connect key if you want to connect a record by a unique field.

Documentation about this here: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/relation-queries/#nested-writes
