### ISSUE TITLE
How do I leverage dynamic return types of a Prisma findFirst/findMany?

### ISSUE THREAD

**Issue by samithjaganath** [prisma/prisma#25000]
### Discussed in https://github.com/prisma/prisma/discussions/24994

<div type='discussions-op-text'>

<sup>Originally posted by **samithjaganath** August 11, 2024</sup>
### Question

I have the following structure in my rest service. 

CrudRepository.ts (A base interface that should be inherited by all models that would need to support crud)
```
export interface CrudRepository {
  getOne(filter: FindFirstFilter, tx?: Prisma.TransactionClient): Promise<WHAT_DO_I_RETURN_HERE>;
  getMany(filter: FindFirstFilter, tx?: Prisma.TransactionClient): Promise<WHAT_DO_I_RETURN_HERE[]>;
}
```

ICarRepository.ts (An interface for the Car repository. Car is a prisma model)
```
export interface ICarRepository extends CrudRepository {
  getOne(
    filter: Prisma.CarFindFirstArgs,
    tx?: Prisma.TransactionClient
  ): Promise<WHAT_DO_I_RETURN_HERE>;
}

```

CarRepository (Implementation class for ICarRepository)
```
@injectable()
export class CarRepository implements ICarRepository {
  constructor(
    @inject(Types.CarModelProvider) private carModelProvider: Factory<StorageModel<'Car'>>
  ) {}

  async getOne(
    filter: Prisma.CarFindFirstArgs,
    tx?: Prisma.TransactionClient
  ): Promise<WHAT_DO_I_RETURN_HERE> {
	return this.carModelProvider(tx).findFirst(filter);
  }
```

While I'm using CarRepository in a Service, I need it to **only return the keys mentioned in my select clause(with types)**. 

I project that this codebase could become large one day. Hence the high reusability targeted with repository functions. 

### Information about Prisma Schema, Client Queries and Environment (optional)

```prisma
// Add your schema.prisma
```

```ts
// Add any relevant Prisma Client queries here
```

- OS: 
- Database: 
- Node.js version: 

- Run `prisma -v` to see your Prisma version and paste it
</div>

**Comment by jkomyno** [comment]
Hi @samithjaganath, please don't open an issue while a discussion is still in progress. @ludralph replied in https://github.com/prisma/prisma/discussions/24994#discussioncomment-10451940, can you please follow up there? Thanks :)
