### ISSUE TITLE
The number of connections in the prisma connection pool suddenly decreased

### ISSUE THREAD

**Issue by youxq** [prisma/prisma#25013]
### Bug description

Through the monitoring system, it was found that the connections in the prisma connection pool would be closed suddenly, resulting in a timeout of fetching the connection, prompting `Timed out fetching a new connection from the connection pool.`

See closing links via netstat
<img width="849" alt="image" src="https://github.com/user-attachments/assets/7234d844-800b-4d04-9427-db2f529b5ed5">

The monitoring system prompts that the number of connections suddenly decreases
<img width="1381" alt="image" src="https://github.com/user-attachments/assets/3114fd63-4980-484d-a1ad-446032b679cf">
<img width="1394" alt="image" src="https://github.com/user-attachments/assets/f845bc3b-d299-41a8-945a-5d8b4f739e0e">

Query latency p95 is very high: ~30s
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/ae83fd9a-d419-4810-aadf-132c765c0309">

### Prisma information

```prisma
// Add your schema.prisma
generator client {
  provider        = "prisma-client-js"
  output          = "./client"
  previewFeatures = ["metrics"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

```

```ts
export const prismaClient = new PrismaClient({
  log: [
    {
      emit: 'event',
      level: 'query',
    },
    {
      emit: 'stdout',
      level: 'error',
    },
    {
      emit: 'stdout',
      level: 'info',
    },
    {
      emit: 'stdout',
      level: 'warn',
    },
  ],
});

const queryTimeout = process.env.QUERY_TIMEOUT
  ? parseInt(process.env.QUERY_TIMEOUT, 10)
  : 500;
prismaClient.$on('query', e => {
  if (e.duration < queryTimeout) return;
  OrmLogger.info(
    `orm operation exceed time limit(${queryTimeout}ms)`,
    'orm-timeout',
    {
      query: e.query,
      params: e.params,
      duration: e.duration,
    }
  );
});
```

### Environment & setup

- OS: CentOS
- Database: PostgreSQL
- Node.js version: v20.12.1

### Prisma Version

```
5.12.1
```

**Comment by jkomyno** [comment]
Hi, we can't reproduce this issue with the information given so far.
Can you please share a self-contained repository with instructions on how to reproduce this? Thanks.

**Comment by youxq** [comment]
Hi @jkomyno ,
I've created a self-contained repository that demonstrates the issue: https://github.com/youxq/prisma-connection-test
Please follow the instructions in the README.md to reproduce the issue. Let me know if you need any further assistance.

Thank you!
