### ISSUE TITLE
Help me, please...

### ISSUE THREAD

**Issue by NopAngel** [prisma/prisma#25056]
### Bug description

Hello, I want to report an error about Prisma and with React, it turns out that I am making an application with React which is a Netflix Clone, when trying to import Prisma and a MySQL database I got an error saying this: "Error: PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `unknown`).
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report
    at Object.get (@prisma_client.js?v=4899fa02:1069:19)
    at a.ts:5:39", maybe here is the capture. Greetings and happy day/night/afternoon!

![Screenshot 2024-08-20 220522](https://github.com/user-attachments/assets/e76d97e1-1c37-46b0-9474-fc3a2891d999)

### Prisma information

```prisma

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?
// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Movies {
  id          Int    @id @default(autoincrement())
  title       String @db.VarChar(100)
  description String @db.VarChar(200)
  movies      Bytes  @db.LongBlob()
  image       Bytes  @db.LongBlob()
}


```

### Environment & setup

- OS: Windows 11
- Database: MySQL
- Node.js version: v20.12.2

### Prisma Version

```
prisma                  : 5.18.0
@prisma/client          : 5.18.0
```

**Comment by geromegrignon** [comment]
Hello @NopAngel,

Prisma is meant to run on the server side in a NodeJS application, not directly in a browser in a frontend application.
You either need a NodeJS application or use a full-stack React solution, like Next.

**Comment by NopAngel** [comment]
Ahh ok, thanks for replying :D**byeee**
