### ISSUE TITLE
PrismaClientInitializationError: Can't reach database server when deploying on Coolify

### ISSUE THREAD

**Issue by Misterbra** [prisma/prisma#25080]
### Bug description

I'm encountering a PrismaClientInitializationError when trying to connect to a Supabase database from a Next.js application deployed on Coolify. The same application works perfectly when deployed on Vercel, suggesting that the issue is specific to the Coolify deployment environment.

Error Message :
PrismaClientInitializationError: Can't reach database server at aws-0-eu-central-1.pooler.supabase.com:6543

### How to reproduce

Clone the minimal reproduction repository: https://github.com/Misterbra/Supabase-Coolify-Connection-Issue-Reproduction
Set up the necessary environment variables for Supabase connection
Deploy the application on Coolify
Attempt to access any route that triggers a database query

### Expected behavior

The application should successfully connect to the Supabase database and execute queries.

### Prisma information

The application fails to connect to the database, throwing a PrismaClientInitializationError.

### Environment & setup

Environment :
Next.js 
Prisma 
Node.js 
Deployment platform: Coolify
Database: Supabase (PostgreSQL)

### Prisma Version

```
"prisma": "^5.17.0"
```

**Comment by jkomyno** [comment]
Hi @Misterbra, have you already tried connecting to the same database via the native `pg` driver from your Coolify environment? If not, can you please try running a generic query like `SELECT 1` via `pg`, and report back with the results? I'm asking because this sounds like a misconfiguration rather than a Prisma issue. Thanks!

**Comment by Misterbra** [comment]
@jkomyno  Thanks for your feedback, it turns out that the problem comes from the fact that I have a special character (or several) in my password for the supabase database. So really, something I would never have suspected. Thank you for taking the time to give me feedback.

**Comment by Misterbra** [comment]
The problem comes from the fact that I have a special character (or several) in my password for the supabase database.
