### ISSUE TITLE
Native Support for PostGIS Spatial Queries (e.g., ST_Distance, ST_MakePoint) in Prisma

### ISSUE THREAD

**Issue by Jeon316upzx** [prisma/prisma#25083]
## Problem

<img width="859" alt="Screen Shot 2024-08-24 at 9 45 29 PM" src="https://github.com/user-attachments/assets/e7027dc9-b723-4d16-a02b-02cd83543885">

I want to be able to not use raw query to do this in the uploaded image

## Suggested solution

 I

**Comment by jkomyno** [comment]
Hi, closing this in favour of an already popular and more general feature request for GIS support: https://github.com/prisma/prisma/issues/2789
