### ISSUE TITLE
No interactive name prompt when running `prisma migrate dev`

### ISSUE THREAD

**Issue by aspfohl** [prisma/prisma#25091]
### Bug description

No prompt, resulting in an empty migration name
<img width="441" alt="Screenshot 2024-08-26 at 3 59 14 PM" src="https://github.com/user-attachments/assets/03997e91-cc2a-4f38-a6b6-d3c91a90d659">

### How to reproduce

Run `prisma migrate dev `

### Expected behavior

Because "--name" was not provided, command should interactively prompt user for the name

### Prisma information

```prisma
// any new model
model MyNewTestObject {
  id String @id @default(uuid())
}

```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.15.0

### Prisma Version

```
prisma                  : 4.16.0
@prisma/client          : 4.10.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.0-66.b20ead4d3ab9e78ac112966e242ded703f4a052c
Default Engines Hash    : b20ead4d3ab9e78ac112966e242ded703f4a052c
Studio                  : 0.484.0
Preview Features        : tracing
```

**Comment by ben-propflo** [comment]
`prisma                  : 4.16.0
@prisma/client          : 4.10.1`

Have you tried upgrading? These versions are over a year old at this point.

**Comment by jkomyno** [comment]
Please upgrade every Prisma dependency to at least to version 5.0.0, thanks!
Here's the blog post with the breaking changes: https://www.prisma.io/blog/prisma-5-f66prwkjx72s

And please read the changelogs from https://github.com/prisma/prisma/releases/tag/5.0.0 to https://github.com/prisma/prisma/releases/tag/5.19.0 to gradually upgrade your app to the latest Prisma version, if that's suitable for you, thanks!
