### ISSUE TITLE
TypedSQL Error while generating client, "prepared statement "n" does not exist" using PostgreSQL NeonTech

### ISSUE THREAD

**Issue by Ivanfvj** [prisma/prisma#25118]
# Context
I've installed the latest prisma version in my project and I'm testing the new preview feature `typedsql`.
I'm using NeonTech PostgreSQL database, with a db connection string (with connection pooling) like this:
`postgresql://[user]:[pass]@[endpoint]-pooler.us-east-2.aws.neon.tech/[db]?sslmode=require&connect_timeout=10`

I've read all the docs prisma offers so far:
- Documentation: https://www.prisma.io/docs/orm/prisma-client/using-raw-sql/typedsql
- Announcement blog post: https://www.prisma.io/blog/announcing-typedsql-make-your-raw-sql-queries-type-safe-with-prisma-orm

# Description
I'm having the following error when running the script `yarn prisma generate --sql`:

```bash
Prisma schema loaded from modules/prisma/schema.prisma
Error: Errors while reading sql files:

ERROR: prepared statement "s2" does not exist
```

This is my `package.json` config. I load envs with dot-env before running any prisma script and I've checked that both the `DATABASE_URL` and `DATABASE_DIRECT_URL` envs are set.

```json
...
 "scripts": {
 ...
    "prisma": "node ../../load-env -- prisma",
    "prisma:generate": "yarn run prisma generate --sql",
 ...
  },
"prisma": {
    "schema": "./modules/prisma/schema.prisma"
  },
...
```

I created an .sql file under the `/prisma/sql` directory with the name `getModelCategories.sql`

```sql
-- getModelCategories.sql file
SELECT DISTINCT
    pi.model,
    c.name AS "categoryName",
    c.slug AS "categorySlug"
FROM 
    public."PromptItem" pi
JOIN 
    public."PromptCategories" pc ON pi.id = pc."promptId"
JOIN 
    public."Category" c ON pc."categoryId" = c.id
ORDER BY 
    pi.model asc, c.name;
```

And my `schema.prisma` file here

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["typedSql"]
}
...
...
datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DATABASE_DIRECT_URL")
}
```

I haven't had any issues with prisma before when generating the schema. I guess this previewFeature needs to connect to the database to validate the .sql query.

I'm sure that my connection string is correct and is currently working in development and production.

I would be grateful if the Prisma team could help me resolve this issue. Any guidance or support would be greatly appreciated!! Thank you in advance for your assistance.

**Comment by Gubiar** [comment]
I have same problem

https://github.com/prisma/prisma/discussions/25106#discussioncomment-10490455

**Comment by Gubiar** [comment]
Here's the fix

https://github.com/prisma/prisma/discussions/25106#discussioncomment-10500102

**Comment by Ivanfvj** [comment]
Thanks @Gubiar! That fixed the issue!

I had my `DIRECT_URL` using a `-pooler` connection string, same as the one I set on the `DATABASE_URL` env.
After removing the `-pooler` string it worked immediately!
