### ISSUE TITLE
PrismaClientRustPanicError: Expected parent IDs to be set when ordering by parent ID

### ISSUE THREAD

**Issue by miroirstudiosrl** [prisma/prisma#25146]
### Bug description

Prisma throws the RustPanicError when the function written below is called.
It seems like there are some records in the db that causes the problem. The weird thing is the following:
If I take 50 elements skipping 0 I get the error. If I take 20 elements skipping 0, 20, 40 and so on (passing the 50th row) I never get the error.
For this reason it's impossible to understand if the problem is caused by a record or some weird prisma's behaviour.

### How to reproduce

If I try running the SQL queries manually on the db I don't get any error. The error seems to be caused by the Prisma Client code.

Example of the weird pagination behaviour.
If I try running the same exact query changing only skip and take I get the following (weird) results:
- skip 0 take 33 -> error
- skip 1 take 32 -> error
- skip 2 take 31 -> error
- skip 3 take 30 -> error
- skip 4 take 29 -> no error
- skip 5 take 30 -> no error
- ... and so on
- skip 0 take 40 -> error
- skip 1(,2,3) take 40 -> error
- skip 0 take 32 (or less) -> no error

Some "rules" I think I've seen:
skip from 0 to 3 taking the 33th row -> error

It seems like row 33 it the problem. However every (I can't really garantuee the "every") skip above 3 that takes that row doen't raise the error...

### Prisma information

schema.prisma
```prisma
model Registrations {
  id                 Int                @id @default(autoincrement())
  identificationCode String             @unique
  registrationStatus RegistrationStatus
  marathon           Marathons          @relation(fields: [marathonName], references: [name])
  marathonName       String
  teamName           String?
  subscribers        Subscribers[]
  payment            Payments?          @relation(fields: [paymentId], references: [id])
  paymentId          Int?               @unique
  createdAt          DateTime           @default(now())
  updatedAt          DateTime           @updatedAt
}

model Payments {
  id                 Int                  @id @default(autoincrement())
  stripeClientSecret String?
  paymentStatus      PaymentStatus
  coupons            Coupons?             @relation(fields: [couponId], references: [code])
  couponId           String?
  registration       Registrations?
  total              Int?
  promotionalPackage PromotionalPackages?
  paymentMethods     PaymentMethods?
  createdAt          DateTime             @default(now())
  updatedAt          DateTime             @updatedAt
}

enum PaymentStatus {
  completed
  failed
  inProgress
}

enum PaymentMethods {
  stripe
  bacs
}

enum RegistrationStatus {
  confirmed
  rejected
  pending
}
```

Function that raises the error
```ts
await prisma.registrations.findMany({
      include: {
        payment: {
          include: {
            coupons: true
            },
          },
        },
      },
      skip: pagination
        ? (pagination.page - 1) * pagination.pageLength
        : undefined,
      take: pagination ? pagination.pageLength : undefined,
    });
```

### Rust stack backtrace
```
0:     0x7ff9f6889abf - napi_register_module_v1
   1:     0x7ff9f5f3e04b - <unknown>
   2:     0x7ff9f687c3c2 - napi_register_module_v1
   3:     0x7ff9f688c01a - napi_register_module_v1
   4:     0x7ff9f688bc0e - napi_register_module_v1
   5:     0x7ff9f688cb88 - napi_register_module_v1
   6:     0x7ff9f688c665 - napi_register_module_v1
   7:     0x7ff9f688c5a9 - napi_register_module_v1
   8:     0x7ff9f688c594 - napi_register_module_v1
   9:     0x7ff9f6a401e7 - napi_register_module_v1
  10:     0x7ff9f6a40802 - napi_register_module_v1
  11:     0x7ff9f65cfc79 - napi_register_module_v1
  12:     0x7ff9f65cfa8d - napi_register_module_v1
  13:     0x7ff9f65cca20 - napi_register_module_v1
  14:     0x7ff9f65c5458 - napi_register_module_v1
  15:     0x7ff9f65c05a7 - napi_register_module_v1
  16:     0x7ff9f65bfd7f - napi_register_module_v1
  17:     0x7ff9f65c6a59 - napi_register_module_v1
  18:     0x7ff9f65c05a7 - napi_register_module_v1
  19:     0x7ff9f65bfd7f - napi_register_module_v1
  20:     0x7ff9f65d06a9 - napi_register_module_v1
  21:     0x7ff9f65c0621 - napi_register_module_v1
  22:     0x7ff9f660b559 - napi_register_module_v1
  23:     0x7ff9f6611bb5 - napi_register_module_v1
  24:     0x7ff9f5e012fe - <unknown>
  25:     0x7ff9f5e03c4b - <unknown>
  26:     0x7ff9f5e2c22c - <unknown>
  27:     0x7ff9f5e24c3b - <unknown>
  28:     0x7ff9f5e0dacc - <unknown>
  29:     0x7ff9f5e822e5 - <unknown>
  30:     0x7ff9f5e5762d - <unknown>
  31:     0x7ff9f5e649a0 - <unknown>
  32:     0x7ff9f68a55df - napi_register_module_v1
  33:     0x7ff9f68b158c - napi_register_module_v1
  34:     0x7ff9f68a8bc2 - napi_register_module_v1
  35:     0x7ff9f68a84ea - napi_register_module_v1
  36:     0x7ff9f68a9c95 - napi_register_module_v1
  37:     0x7ff9f688908b - napi_register_module_v1
  38:     0x7ffa9235257d - BaseThreadInitThunk
  39:     0x7ffa9372af28 - RtlUserThreadStart
```

### Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: 20.13.1

### Prisma Version

```
5.7.0
```

**Comment by aqrln** [comment]
@miroirstudiosrl any chance the `couponId` in `Payments` and `code` in `Coupons` for the affected record differs in capitalization? Does enabling the `relationJoins` preview feature resolve this error for you?

**Comment by jkomyno** [comment]
Hi! To add on what @aqrln said, enabling the [`relationJoins` preview feature](https://github.com/prisma/prisma/discussions/22288) implies upgrading Prisma to a recent version.
For MySQL, that version is Prisma 5.10.0. The latest version of Prisma available is 5.19.1.

**Comment by SevInf** [comment]
Hey @miroirstudiosrl  ,

Did you get a chance to have a look at my collegues comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by miroirstudiosrl** [comment]
> Hey @miroirstudiosrl ,
> 
> Did you get a chance to have a look at my collegues comment? It'd be helpful for us to move your issue forward.
> 
> Without further information, we'll have to close this issue. Thank you 🙏

Hi @SevInf sorry for the late reply. Yep, we can close the issue. Thanks
