### ISSUE TITLE
Timed out fetching a new connection from the connection pool. 

### ISSUE THREAD

**Issue by youxq** [prisma/prisma#25162]
### Bug description

I did some research on https://github.com/prisma/prisma/issues/25013. I found the possible cause of this problem.

Prisma's connection management relies on prisma-engine (rust language), and the mechanism is as follows:
- When obtaining a connection from the connection pool, it will determine whether the idle time of the connection exceeds max_idle_lifetime (default 5 minutes). If so, the connection will be closed and recreated
- One of the steps in creating a connection is to create a tls connector. The specific code is as follows. This step is a synchronous operation, and it has been tested that it is greatly affected by the CPU (~1s is required under a 100m CPU limit)
```
        let mut tls_builder = TlsConnector::builder();

        {
            let ssl_params = url.ssl_params();
            let auth = ssl_params.to_owned().into_auth().await?;

            if let Some(certificate) = auth.certificate.0 {
                tls_builder.add_root_certificate(certificate);
            }

            tls_builder.danger_accept_invalid_certs(auth.ssl_accept_mode == SslAcceptMode::AcceptInvalidCerts);

            if let Some(identity) = auth.identity.0 {
                tls_builder.identity(identity);
            }
        }

        let tls = MakeTlsConnector::new(tls_builder.build()?); // This line of code consumes more CPU resources
        let (client, conn) = timeout::connect(url.connect_timeout(), config.connect(tls)).await?;
```

The picture is the cpu flame graph of tls_builder.build(), The main CPU consumption is PEM_X509_INFO_read_bio_ex, OSSL_DECODER_CTX_new_for_pkey
<img width="1916" alt="image" src="https://github.com/user-attachments/assets/a37ec914-6468-44bb-b7a2-761c1e9b6dfe">

When the connections in the connection pool are idle for a long time, a batch operation is initiated and all the connections in the connection pool need to be recreated. When the CPU pressure is high (CPU steal is high or CPU limit is low), the connection creation will exceed pool_timeout (10s) and connect_timeout (5s) due to the waiting time of TLS operation.

Here are some solutions

**App layer solution**
- Keep the connection active: Use select 1 every 5 minutes to keep the connection active
- Increase pool_time and connect_timeout to reduce the impact of tls timeout

**Prisma layer solution**
- Modify the source code. Since tls may not be used, remove the tls build and use NoTls directly
- Modify the source code and change the tls of each build to be generated by the existing tls.clone() (refer to mobc-postgres)

### Expected behavior

I would like to know if the solution I provided is feasible. Hope you can reply

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: CentOS
- Database: PostgreSQL
- Node.js version: v20.12.1

### Prisma Version

```
5.12.1
```

**Comment by jkomyno** [comment]
Hi @youxq, thanks for this analysis! We've struggled to reproduce this issue in the past, hopefully your input will help us speed this up and fix this. Thanks!

**Comment by jkomyno** [comment]
We actually encourage you to open a PR to modify and test this!

**Comment by youxq** [comment]
@jkomyno Ok, I will open a PR later to try to fix it
