### ISSUE TITLE
Accelerate not accepting `?pgbouncer=true` in connection string

### ISSUE THREAD

**Issue by Tittoh** [prisma/prisma#25161]
### Bug description

I am working on a project using supabase and prisma accelerate. I am trying to add `?pgbouncer=true` to the connection string to fix [ConnectorError: 42P05 #24798](https://github.com/prisma/prisma/issues/24798) but I get the error:

`One or more fields were invalid: [connectionString]`

### How to reproduce

1. Go to `https://console.prisma.io/` > `Accelerate` > `Settings`
2. Change `Database connection string` to include `?pgbouncer=true`
3. Save
4. See error `One or more fields were invalid: [connectionString]` pops up.

### Expected behavior

To prevent Supavisor from erroring, it is necessary to add the following query parameter to your connection strings: `pgbouncer=true` to the Transaction connection string.

This is the only fix for `> “prepared statement \“s#\” does not exist”` error other than restarting by project frequently

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["relationJoins"]
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}

model User {
  id       Int      @id @default(autoincrement())
  email    String   @unique
  name     String
  password String
  ratings  Rating[]
}

model Movie {
  id          Int      @id @default(autoincrement())
  title       String
  releaseDate DateTime
  description String
  genre       String[]
  ratings     Rating[]
}

model Rating {
  id      Int @id @default(autoincrement())
  value   Int
  user  User  @relation(fields: [userId], references: [id])
  userId  Int
  movie Movie @relation(fields: [movieId], references: [id])
  movieId Int
  @@unique([userId, movieId])
}
```

```ts
import { PrismaClient } from '@prisma/client/edge';
import { withAccelerate } from '@prisma/extension-accelerate';

export const prismaClient = new PrismaClient({
  log: process.env.NODE_ENV === 'development' ? ['error', 'warn'] : ['error'],
  transactionOptions: {
    maxWait: 5000, // default: 2000
    timeout: 10000 // default: 5000
  }
}).$extends(withAccelerate());
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL (supabase)
- Node.js version: v21.7.3

### Prisma Version

```
prisma                  : 5.18.0
@prisma/client          : 5.18.0
Computed binaryTarget   : darwin
Operating System        : darwin
Architecture            : x64
Node.js                 : v21.7.3
Query Engine (Node-API) : libquery-engine 4c784e32044a8a016d99474bd02a3b6123742169 (at node_modules/.pnpm/@prisma+engines@5.18.0/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Schema Engine           : schema-engine-cli 4c784e32044a8a016d99474bd02a3b6123742169 (at node_modules/.pnpm/@prisma+engines@5.18.0/node_modules/@prisma/engines/schema-engine-darwin)
Schema Wasm             : @prisma/prisma-schema-wasm 5.18.0-25.4c784e32044a8a016d99474bd02a3b6123742169
Default Engines Hash    : 4c784e32044a8a016d99474bd02a3b6123742169
Studio                  : 0.502.0
Preview Features        : relationJoins
```

**Comment by jess-small** [comment]
Any updates on this? Having the same issue and its causing lots of issues

**Comment by rtbenfield** [comment]
Can you help me understand why the `pgbouncer` setting is being used? Are you using the Supavisor connection string with Accelerate? If so, we recommend using the direct connection to the database instead.

Accelerate operates a built-in connection pooler that is optimized for Prisma ORM queries. The `ConnectorError` may arise when Accelerate is used in conjunction with PgBouncer (and Supavisor), which is effectively stacking a connection pooler on a connection pooler. The `pgbouncer=true` setting will [disable some optimizations](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/pgbouncer#set-pgbouncer-to-transaction-mode) in the Prisma ORM to be compatible with PgBouncer. That's unnecessary with Accelerate's connection pooler, so it's disallowed at the moment.

**Comment by Tittoh** [comment]
Upon further testing, I found out that I was had setup accelerate with supabase `DATABASE_URL`  link instead of `DIRECT_URL` hence the error.
