### ISSUE TITLE
Option to generate types that require a where clause to enforce tenant isolation

### ISSUE THREAD

**Issue by briangottfried** [prisma/prisma#25185]
## Problem

I'm working on a multi-tenant application. I've gone down the route of writing a client extension that automatically filters models by `tenantId`, however, while this works for reads, create operations require `tenantId` in the type for its payload. This means I can't really encapsulate the handling of `tenantId`s completely.

## Suggested solution

I would like a way to tell prisma when it's generating its types, that all models must include a where clause and a column (`tenantId` in my case), that way it's consistent across my CRUD operations.

**Comment by briangottfried** [comment]
I was able to achieve this by just writing my own generator that rewrote the types generated by the prisma client with what I needed.

**Comment by hisabimbola** [comment]
@briangottfried can you share a snippet of the code you used for this? Thanks
