### ISSUE TITLE
Prisma join tables unable to be replicated by default

### ISSUE THREAD

**Issue by sdgluck** [prisma/prisma#25196]
### Bug description

_(Creating an issue from my [comment](https://github.com/prisma/prisma/issues/9434#issuecomment-2295997794) on this closed issue.)_

Due to Prisma relation tables not having a primary key and due to the [default replica identity behaviour](https://www.postgresql.org/docs/current/logical-replication-publication.html) these tables are not able to be replicated without further manual configuration.

Prisma relation tables use a unique index on the two columns A and B and so theoretically the `REPLICA IDENTITY FULL` should be able to perform without issue as this constraint will prevent duplicate records which would impact data consistency.

I see a few options for a resolution:
1. include `ALTER TABLE x REPLICA IDENTITY FULL` in the SQL for creation of these tables in migrations
2. add a primary key on relation tables
3. provide replica identity configuration within the Prisma schema DSL

My preference would be 2 as it is the least effort (for users and Prisma devs) and means future join table schemas will not diverge from the current schema.

### How to reproduce

- Create a join table via eg. many-to-many relation in a Prisma schema
- Configure logical replication for the Postgres schema
- Notice error in logs "...because it does not have a replica identity and publishes deletes..."

### Expected behavior

I would expect Prisma would make some consideration for the scenario of logical replication of join tables such that this error does not occur.

### Prisma information

n/a

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 20

### Prisma Version

```
prisma                  : 5.10.2
@prisma/client          : 5.10.2
Computed binaryTarget   : darwin
Operating System        : darwin
Architecture            : x64
Node.js                 : v20.14.0
Query Engine (Node-API) : libquery-engine 5a9203d0590c951969e85a7d07215503f4672eb9 (at ../../node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Schema Engine           : schema-engine-cli 5a9203d0590c951969e85a7d07215503f4672eb9 (at ../../node_modules/@prisma/engines/schema-engine-darwin)
Schema Wasm             : @prisma/prisma-schema-wasm 5.10.0-34.5a9203d0590c951969e85a7d07215503f4672eb9
Default Engines Hash    : 5a9203d0590c951969e85a7d07215503f4672eb9
Studio                  : 0.499.0
Preview Features        : metrics, views
```

**Comment by jkomyno** [comment]
Hi @sdgluck, thanks for opening this issue, explaining your use case and proposing more than one possible solution.
Replica scenarios are currently under-investigated in Prisma, and adding a Primary Key to relation tables seems like an adequate solution.

Doing so would probably require a new major version though, as it would modify the generated migrations. We'll follow up on this, thanks for your input!
