### ISSUE TITLE
Postgres `db.Decimal(X, 0)` retrieved as floating point

### ISSUE THREAD

**Issue by ksmit799** [prisma/prisma#25212]
### Bug description

I've run into an odd issue when retrieving large decimals with PostgresSQL. The expected behavior of `<field> Decimal db.Decimal(X, 0)` is to store the field as an integer with a length `X` and `0` decimal precision. For example `db.Decimal(39, 0)` should store a 128bit (16 byte) integer without precision loss.

This works fine for storing values, however upon retrieval they are instead floating point numbers (e.g. `4638449322890040259147289221431665` becomes `4.638449322890040259147289221431665e+33`.)

The correct values show up in pgAdmin:
![Screenshot 2024-09-12 155006](https://github.com/user-attachments/assets/15597c4e-84ea-4254-84ea-a01c9eded494)

However both in code and with Prisma Studio, an incorrect value is retrieved:
![Screenshot 2024-09-12 153132](https://github.com/user-attachments/assets/218307d6-a5f6-4422-a8df-4df9ade73203)

### How to reproduce

Run the code within the `Prisma information` section OR attempt to read a `db.Decimal(X, 0)` field in Prisma Studio.

### Expected behavior

JavaScript itself doesn't support such large numbers with the `number` primitive. However, I expect to be able to do the following: `const value = BigInt(prismaObject.txId.toString())`. Instead, I get the following error (due to `toString()` just stringifying the incorrect floating point value): `SyntaxError: Cannot convert 4.638449322890040259147289221431665e+33 to a BigInt`

It seems as if this is some kind of regression (possibly related to Decimal.js?), as the expected behavior has been [reported as working before.](https://github.com/prisma/prisma/issues/19860#issuecomment-1839662082)

### Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Test {
  txId Decimal @id @db.Decimal(39, 0)
}
```

```ts
  await prisma.test.create({data: {txId: "4638449322890040259147289221431665"}});
  await prisma.test.create({data: {txId: "4638449360796155049277845621482705"}});
  await prisma.test.create({data: {txId: "4638449365115847159809326047046303"}});
  await prisma.test.create({data: {txId: "4638449370170574910641017211037647"}});

  const tests = await prisma.test.findMany();
  for (const test of tests) {
    console.log(test.txId.toString());
  }
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: 21.7.1

### Prisma Version

```
prisma                  : 5.19.1
@prisma/client          : 5.19.1
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v21.7.1
Query Engine (Node-API) : libquery-engine 69d742ee20b815d88e17e54db4a2a7a3b30324e3 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 69d742ee20b815d88e17e54db4a2a7a3b30324e3 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.19.1-2.69d742ee20b815d88e17e54db4a2a7a3b30324e3
Default Engines Hash    : 69d742ee20b815d88e17e54db4a2a7a3b30324e3
Studio                  : 0.502.0
```

**Comment by jacek-prisma** [comment]
Hi @ksmit799 @junhoyeo 

I've run your example and the returned value is a `Decimal` from [decimal.js](https://mikemcl.github.io/decimal.js) and not a float. The `Decimal` gets formatted with the exponential notation in `.toString()` because it's something they do for large numbers. You can get the `Decimal` formatted with the notation you want by calling [`.toFixed()`](https://mikemcl.github.io/decimal.js/#toFixed).
