### ISSUE TITLE
SessionTokenError & PrismaClient is not configured to run in Vercel Edge Functions or Edge Middleware

### ISSUE THREAD

**Issue by mirkobozzetto** [prisma/prisma#25234]
### Bug description

PrismaClient fails to initialize in an Edge Runtime environment (Next.js middleware) despite using the recommended configuration with driver adapters and Neon's pooled connections. The error persists even after following the official documentation for Edge compatibility.

### How to reproduce

1. Set up a Next.js project with Prisma and NextAuth.
2. Configure Prisma for Edge compatibility in schema.prisma

```prisma
generator client {
  provider        = "prisma-client-js"
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}
```
3. Set up Prisma client in prisma.ts:

```ts
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };

export const prisma = globalForPrisma.prisma || new PrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
```

4. Configure NextAuth to use PrismaAdapter in an Edge environment.
5. Set up Next.js middleware to use NextAuth.
6. Run the application and attempt to access a route that triggers the middleware.

### Expected behavior

Prisma Client should initialize successfully in the Edge Runtime environment, allowing the middleware to function properly with database access.
Actual behavior
The application throws a PrismaClientValidationError with the message:

```
PrismaClient failed to initialize because it wasn't configured to run in this environment (Edge Runtime (Vercel Edge Functions, Vercel Edge Middleware, Next.js (Pages Router) Edge API Routes, Next.js (App Router) Edge Route Handlers or Next.js Middleware)).
In order to run Prisma Client in an edge runtime, you will need to configure one of the following options:
- Enable Driver Adapters: https://pris.ly/d/driver-adapters
- Enable Accelerate: https://pris.ly/d/accelerate
```

## Schema

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id            String          @id @default(cuid())
  name          String?
  email         String          @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
  Authenticator Authenticator[]

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Account {
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@id([provider, providerAccountId])
}

model Session {
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model VerificationToken {
  identifier String
  token      String
  expires    DateTime

  @@id([identifier, token])
}

model Authenticator {
  credentialID         String  @unique
  userId               String
  providerAccountId    String
  credentialPublicKey  String
  counter              Int
  credentialDeviceType String
  credentialBackedUp   Boolean
  transports           String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@id([userId, credentialID])
}
```

## Prisma Initialisation

```prisma.ts```
```ts
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };

export const prisma = globalForPrisma.prisma || new PrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
```

### Environment & setup

- Next.js version: 14.2.11
- Node.js version: [Please provide]
- Operating System: [Please provide]
- Deployment environment: Vercel (Edge Runtime)
- Database: PostgreSQL (Neon with pooled connections)

### Prisma Version

```
prisma                  : 5.9.1
@prisma/client          : 5.12.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.6.1
Query Engine (Node-API) : libquery-engine 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at ../../../../../opt/homebrew/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at ../../../../../opt/homebrew/lib/node_modules/prisma/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-32.23fdc5965b1e05fc54e5f26ed3de66776b93de64
Default Engines Hash    : 23fdc5965b1e05fc54e5f26ed3de66776b93de64
Studio                  : 0.497.0
```

**Comment by SevInf** [comment]
Neither the schema, nor the code you've posted here actually uses driver adapters. 
Please double check that you've posted correct code and that you actually following the [docs for setting up Neon](https://www.prisma.io/docs/orm/overview/databases/neon#how-to-use-neons-serverless-driver-with-prisma-orm-preview)

**Comment by SevInf** [comment]
Hey @mirkobozzetto  ,

Did you get a chance to have a look at my previous comment? Could you confirm that your issue is solved?

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by mirkobozzetto** [comment]
@SevInf I need to update my previous response with an important discovery.

While the split configuration pattern worked initially, we encountered an issue where static assets (images, SVGs, etc.) were not accessible to unauthenticated users in production. Here's the complete solution that finally resolved both the Edge Runtime and static assets issues:

1. The auth.config.ts now includes explicit static asset handling:
```typescript
export const authConfig = {
  providers: [Google],
  session: { strategy: "jwt" },  // Changed to jwt for consistency
  callbacks: {
    authorized({ auth, request: { nextUrl } }) {
      const isLoggedIn = !!auth?.user;
      const isAuthPage = nextUrl.pathname.startsWith("/auth");
      const isPublicPage = ["/", "/auth/verify-request"].includes(nextUrl.pathname);
      const isApiRoute = nextUrl.pathname.startsWith("/api");
      
      // Critical: Handle all static assets
      const isStaticAsset =
        nextUrl.pathname.startsWith("/_next") ||
        nextUrl.pathname.includes("/public/") ||
        nextUrl.pathname.endsWith(".svg") ||
        nextUrl.pathname.endsWith(".ico") ||
        nextUrl.pathname.endsWith(".png") ||
        nextUrl.pathname.endsWith(".jpg") ||
        nextUrl.pathname.endsWith(".jpeg") ||
        nextUrl.pathname.endsWith(".gif") ||
        nextUrl.pathname.endsWith(".webp") ||
        nextUrl.pathname.endsWith(".mp4") ||
        nextUrl.pathname.includes("/images/");

      if (isStaticAsset) return true;
      // ... rest of the routing logic
    }
  }
}
```

This solution:
- Avoids Prisma Edge Runtime issues completely
- Ensures all static assets are publicly accessible
- Maintains proper authentication flow
- Works consistently in both development and production

Key learnings from this journey:
1. Edge Runtime limitations require careful consideration of static asset handling
2. Sometimes the simplest solution (like proper static asset routing) is better than complex infrastructure changes
3. Production environment can reveal issues not visible in development

Thank you for your guidance on driver adapters. While we took a different approach, your feedback helped us understand the problem better and find an appropriate solution.

**Comment by jkomyno** [comment]
Closing this issue, as OP was not using `driverAdapters`.
