### ISSUE TITLE
Relation referencee `String @id @default(dbgenerated("uuidv7()")) @db.Uuid` make relations crash

### ISSUE THREAD

**Issue by mhammerc** [prisma/prisma#25235]
### Bug description

Hello!

I have the following schema.prisma.

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id String @id @default(dbgenerated("uuidv7()")) @db.Uuid

  tokens UserToken[]

  @@map("user")
}

model UserToken {
  token String @id @default(dbgenerated("uuidv7()")) @db.Uuid

  userId String @map("user_id") @db.Uuid
  user   User   @relation(fields: [userId], references: [id])

  @@map("user_token")
}
```

I have the following seed:

```ts
import {PrismaClient} from '@prisma/client';

const prisma = new PrismaClient();

await prisma.user.create({
  data: {
    tokens: {create: {token: 'devtoken'}},
  },
});
```

The seed make prisma crash with the following error:

```
Inconsistent column data: Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `v` at 3

meta: {
    modelName: 'User',
    message: 'Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `v` at 3'
  }
```

This error comes from `@db.Uuid`.
**If I remove `@db.Uuid` (just a `String`), it works as expected!**

**NOTE**

The following is the SQL definition of the uuidv7 function. I prefer to use it rather than prisma `uuid(7)` because it is a native default of the database. And we use many sql raw queries.

```sql
CREATE FUNCTION uuidv7() RETURNS uuid
AS $$
  -- Replace the first 48 bits of a uuidv4 with the current
  -- number of milliseconds since 1970-01-01 UTC
  -- and set the "ver" field to 7 by setting additional bits
  select encode(
    set_bit(
      set_bit(
        overlay(uuid_send(gen_random_uuid()) placing
	  substring(int8send((extract(epoch from clock_timestamp())*1000)::bigint) from 3)
	  from 1 for 6),
	52, 1),
      53, 1), 'hex')::uuid;
$$ LANGUAGE sql volatile;

COMMENT ON FUNCTION uuidv7() IS
'Generate a uuid-v7 value with a 48-bit timestamp (millisecond precision) and 74 bits of randomness';
```

Example of a generated UUID from the function: `0191fce1-69a5-78b7-84b6-faeb2d33a564`. I validated it succesfully [here](https://uuid7.com).

### Environment & setup

- OS: MacOS
- Database: PostgreSQL 16
- Node.js version: 22

### Prisma Version

```
prisma                  : 5.19.1
@prisma/client          : 5.19.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v22.8.0
Query Engine (Node-API) : libquery-engine 69d742ee20b815d88e17e54db4a2a7a3b30324e3 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 69d742ee20b815d88e17e54db4a2a7a3b30324e3 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.19.1-2.69d742ee20b815d88e17e54db4a2a7a3b30324e3
Default Engines Hash    : 69d742ee20b815d88e17e54db4a2a7a3b30324e3
Studio                  : 0.502.0
```

**Comment by SevInf** [comment]
Hi @mhammerc.
In your schema your specify that the type of the `token` field is `Uuid`. In your seed script you pass value `devtoken` as the UUID. UUID is not just arbitrary string, it has a specific format and `devtoken` is not a valid UUID. In that case it's Postgres that tells you that it is not valid, not Prisma.

If you want to use arbitrary strings as a value for `token` you should remove `@db.Uuid` from your schema.

**Comment by mhammerc** [comment]
> Hi @mhammerc. In your schema your specify that the type of the `token` field is `Uuid`. In your seed script you pass value `devtoken` as the UUID. UUID is not just arbitrary string, it has a specific format and `devtoken` is not a valid UUID. In that case it's Postgres that tells you that it is not valid, not Prisma.
> 
> If you want to use arbitrary strings as a value for `token` you should remove `@db.Uuid` from your schema.

Omg I think you are right! I was confused doing too many things at the same time.
I am sorry to have lost your time.
