### ISSUE TITLE
@prisma/client@5.19.1 has no exported member "PrismaClient"

### ISSUE THREAD

**Issue by K1chel** [prisma/prisma#25241]
### Bug description

![Screen Shot 2024-09-17 at 11 46 37 PM](https://github.com/user-attachments/assets/7e1a595f-346f-4725-92dc-a6fc0ff20ef9)

### How to reproduce

1. Go to package.json
2. Change @prisma/client from 5.19.1 to 5.19.0
3. Run '....'
4. See error (NO ERROR)

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
import { PrismaClient } from "@prisma/client";

declare global {
  var prisma: PrismaClient | undefined;
}

export const db = globalThis.prisma || new PrismaClient();

if (process.env.NODE_ENV !== "production") globalThis.prisma = db;
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
5.19.1
```

**Comment by jpainam** [comment]
Can you`Quit Vs-code` and re-open  it? Some `tsconfig` are causing issue. Don't remember which one.

**Comment by K1chel** [comment]
> Can you`Quit Vs-code` and re-open  it? Some `tsconfig` are causing issue. Don't remember which one. 

Already did that , also uninstalling dependency didn't help. The only one solution for this is to downgrade it to 5.19.0

**Comment by SevInf** [comment]
Hi @K1chel, are you re-running `prisma generate` after update?

**Comment by K1chel** [comment]
> Hi @K1chel, are you re-running `prisma generate` after update?

Yes , as well didn't help. I find one solution that works for me , the solution is to change TypeScript version from "VS Code's Version" to "Workspace Version".

**Comment by SevInf** [comment]
Yea, that VSCode bundled version might've been outdated. I am going to close this issue, please open a new one if it repeats
