### ISSUE TITLE
RethinkDB support

### ISSUE THREAD

**Issue by NetOpWibby** [prisma/prisma#2524]
Don't call it a comeback https://rethinkdb.com/blog/2.4.0-release

**Comment by gabalicious** [comment]
This feature would be awesome!  Any idea what it would take?

**Comment by Sm03leBr00t** [comment]
I would like this too, this could be an easy way to get realtime data

**Comment by muratbeser** [comment]
I was researching about rethinkdb supported stuff. and I would like to have this also.

**Comment by LZL0** [comment]
We need this.

**Comment by forktheweb** [comment]
+1

**Comment by VincentThomas06** [comment]
I would really like this!

**Comment by vko-online** [comment]
👍

**Comment by lautaroramos** [comment]
please!

**Comment by lynsei** [comment]
This would be ideal ... I wonder if I could adapt this like thinky-graphql

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
