### ISSUE TITLE
About the bug of "findMany" function

### ISSUE THREAD

**Issue by chenluhe** [prisma/prisma#25240]
### Bug description

Please look at this code. If the values ​​of username and password are undefined, after executing this function, all records of the tbl_user table will be returned. I think it should return empty results.
```
const userRes = await prisma.tbl_user.findMany({
      where: {
        username: username,
        password: password,
      },
    });
```

### How to reproduce

Environment:
prisma                  : 5.10.2
@prisma/client          : 5.10.2
Node.js                 : v21.5.0

### Expected behavior

 it should return empty results

### Prisma information

prisma                  : 5.10.2

### Environment & setup

prisma                  : 5.10.2

### Prisma Version

prisma                  : 5.10.2

**Comment by vpanyushenko** [comment]
`null` is a value, `undefined` means do nothing. If your values are both `undefined` it's equivalent to not including them:

this:
```js
const userRes = await prisma.tbl_user.findMany({
      where: {
        username: undefined,
        password: undefined,
      },
    });
```

is the same as this:
```js
const userRes = await prisma.tbl_user.findMany({
      where: { },
    });
```

Here are the prisma docs about this: https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/null-and-undefined

If you're looking to have it return no values, you may consider trying something like this:

```js
const userRes = await prisma.tbl_user.findMany({
      where: {
        username: username ?? null,
        password: password ?? null,
      },
    });
```

or 

```js
const userRes = await prisma.tbl_user.findMany({
      where: {
        username: username ?? "",
        password: password ?? "",
      },
    });
```

**Comment by chenluhe** [comment]
Got it, thank you. Personal suggestion: If it is undefined, either return empty data or throw an exception directly.
