### ISSUE TITLE
orderBy deterministic seed (shuffle)

### ISSUE THREAD

**Issue by ElYaiko** [prisma/prisma#25257]
## Problem
To get random rows the only possible way is via a rawQuery, but adding a feature to order by random would not be a solution because other features like take/skip won't work.

## Suggested solution
A way to get "random rows" could be ordering by a seed that internally would use sql functions like md5 or hashtext that always give deterministic values.

The use of this feature could be like:
```
...
orderBy: {
  id: { seed: '*seed*' }
}
```

or
```
...
orderBySeed: {
  id: '*seed*'
}
```

This is useful because could work also with Relations and avoiding to use an additional rawQuery when a shuffle of rows is needed.

What do you think?

**Comment by jkomyno** [comment]
Hi @ElYaiko, can you please describe the use case for retrieving rows in random order in the first place?

I struggled to understand what you meant by
> This is useful because could work also with Relations and avoiding to use an additional rawQuery when a shuffle of rows is needed.

Thanks

**Comment by ElYaiko** [comment]
> Hi @ElYaiko, can you please describe the use case for retrieving rows in random order in the first place?
> 
> I struggled to understand what you meant by
> 
> > This is useful because could work also with Relations and avoiding to use an additional rawQuery when a shuffle of rows is needed.
> 
> Thanks

Retrieving rows in random order can be used in scenarios like displaying a shuffled set of results without repeating, in my case I'm trying to do a pagination (take and skip) with shuffled results, but at the moment is not possible so I have to do first a random deterministic rawQuery the to get the shuffled ids then do a findMany where.in.

What I meant by Relations is to also have the ability to shuffle Related results, for example I would also want to shuffle the Relations of a model but this is not possible at the moment and that is complex to do with a rawQuery only, for example:

I want to return a random set of categories with a random Relation posts, example:
```
category.findMany({
  include: {
    // Relation
    posts: {
      take: 4,
      // Get 4 random posts of each category by seed
      orderBySeed: {
        id: '*seed*'
      },
    }
  },
  // Get random categories by seed
  orderBySeed: {
    id: '*seed*'
  },
})
```

**Comment by SevInf** [comment]
Hi @ElYaiko.
Random ordering is already tracked in #2949.
I am gonna link your usecase there and close issue as duplicate
