### ISSUE TITLE
`prisma format` changes schema semantics

### ISSUE THREAD

**Issue by jwueller** [prisma/prisma#25260]
### Bug description

If I remove a relation on one side and forget to remove it on the other side, Prisma will just silently add it back in under a generated name.

### How to reproduce

1. Declare relation:
   ```prisma
   model Parent {
     id       Int     @id @default(autoincrement())
     children Child[] // (1)
   }
   
   model Child {
     id       Int    @id @default(autoincrement())
     parentId Int
     parent   Parent @relation(fields: [parentId], references: [id])
   }
   ```
3. Remove line `(1)`
4. Run `prisma format` on the schema
5. Prisma generates a new relation property:
   ```prisma
   model Parent {
     id    Int     @id @default(autoincrement())
     Child Child[] // (2)
   }
   ```

### Expected behavior

I think the right move here would be to report the conflict instead of guessing which conflict resolution is correct. The formatter can't know what the author intended, after all. This seems more like a job for a linter to me.

### Prisma information

_n/a_

### Environment & setup

- OS: `Linux 6.10.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 04 Sep 2024 15:16:37 +0000 x86_64 GNU/Linux`
- Database: PostgreSQL 15.3
- Node.js version: v22.9.0

### Prisma Version

```
prisma                  : 5.16.2
@prisma/client          : 5.16.2
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v22.9.0
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
```

**Comment by jkomyno** [comment]
Hi @jwueller, thanks, this is already tracked in https://github.com/prisma/prisma/issues/24227.
