### ISSUE TITLE
Postgres DB DateTime value not stored as datetime, int or text

### ISSUE THREAD

**Issue by ghyath5** [prisma/prisma#2529]
I'm trying to select some fields from prisma via PrismaSelect tool like:

`const select = new PrismaSelect(info).value`
`let data = await ctx.prisma.users.findMany({ ...args, ...select })`
`return data`
this error show me: `DateTime value not stored as datetime, int or text`
when I removed `time` field from select object then it show me this:`Invalid decimal: unknown character`
Knowing that when I was using `includes` instead of `select` there were no errors

**Comment by pantharshit00** [comment]
@ghyath5 Can you please share your prisma schema and your database schema?

Please provide us with enough details so that we can reproduce this issue 🙏

**Comment by janpio** [comment]
Ping for @ghyath5 about Harshit's last followup. We want to move this issue forward, but need your help.
