### ISSUE TITLE
Support for Interface and Union type

### ISSUE THREAD

**Issue by tristancaron** [prisma/prisma#253]
Is it plan to have a direct support of these? Otherwise, documentation about how to handle these scenarios with Prisma.

**Comment by matthewmueller** [comment]
Hi @tristancaron! Thanks for raising this issue. I wish I had a straight answer for you, but I don't. 

Interfaces should be fairly straightforward to support, since they don't need any database backing. This has come up before, but we haven't prioritized it yet.

Unions are very much on our mind. Unions are tricky. Prisma differs from GraphQL in that it's operating at a lower-level. We're talking directly with the database, so we're thinking about ways of introducing these concepts that are backed by the database whenever possible.

Concretely, we're looking into [Table Inheritance](https://www.martinfowler.com/eaaCatalog/) to support Unions.

Do you have a specific use case in mind? Any code or examples would help us to get this right.

**Comment by tristancaron** [comment]
Sure, happy to help.

Here the structure for GraphQL

```
interface Network {
    id: String
    isChecked: Boolean
    isOsStoreLive: boolean
    hasSDK: boolean
    hasAnalyticsAccess: boolean
}

type Campaign {
    network: Network
}

type FbNetwork implements Network {
    id: String
    isChecked: Boolean
    isOsStoreLive: Boolean
    hasSDK: Boolean
    hasAnalyticsAccess: Boolean
    adAccountStatus: AdAccountsStatus
    isLive: Boolean
    hasPrivacyPolicyUrl: Boolean
    hasContactEmail: Boolean
    hasIconUrl: Boolean
    hasIosBundleId: Boolean
}

type IrsNetwork implements Network {
    id: String
    isChecked: Boolean
    isOsStoreLive: Boolean
    hasSDK: Boolean
    hasAnalyticsAccess: Boolean
    accessKey: String
}

input CampaignCreate {
    networkId: String
}
```

My current solution is to have 2 tables. One for each kind of network. 

The schema is the fellowing 

```
model Campaign {
    fbNetwork Network?
    irsNetwork Network?
}

model FbNetwork {
    id String @id @default(uuid())
    isChecked Boolean
    isOsStoreLive Boolean
    hasSDK Boolean
    hasAnalyticsAccess Boolean
    adAccountStatus AdAccountsStatus
    isLive Boolean
    hasPrivacyPolicyUrl Boolean
    hasContactEmail Boolean
    hasIconUrl Boolean
    hasIosBundleId Boolean
}

model IrsNetwork {
    id String @id @default(uuid())
    isChecked Boolean
    isOsStoreLive Boolean
    hasSDK Boolean
    hasAnalyticsAccess Boolean
    accessKey String
}
```

And when a client ask for a result I have a resolver doing this
```
network(source, args, context, info) {
    if (source.fbNetwork != null) return source.fbNetwork
    if (source.irsNetwork != null) return source.irsNetwork
    return null
},
__resolveType(source, context, info) {
    if (source.fbNetwork != null) return 'FbNetwork'
    if (source.irsNetwork != null) return 'IrsNetwork'
    return null
}
```

**Comment by ragnorc** [comment]
Are there any updates on this?

**Comment by matthewmueller** [comment]
Not yet! We'll probably tackle this sometime in the next month or two.

**Comment by ragnorc** [comment]
Thanks! Is there any way we can contribute?

**Comment by janpio** [comment]
Note: Split up into two issues.

**Comment by ragnorc** [comment]
@matthewmueller Is there any possibility to prioritize this? It seems like any non-trivial data model needs those types and 135 thumbs-up on the original [Prisma 1 issue](https://github.com/prisma/prisma/issues/83) are quite indicative.

**Comment by williamluke4** [comment]
I really think this should be a high priority especially with Prisma's focus on GraphQL.

**Comment by joltmode** [comment]
@matthewmueller you mentioned to go with Table Inheritance, would there be an option to switch on a per-relation basis which Table Inheritance model specifically to go with or you are looking to default to one?

**Comment by kripod** [comment]
> Hi @tristancaron! Thanks for raising this issue.
> 
> Interfaces should be fairly straightforward to support, since they don't need any database backing. This has come up before, but we haven't prioritized it yet.
> 
> Unions are very much on our mind. Unions are tricky. Prisma differs from GraphQL in that it's operating at a lower-level. We're talking directly with the database, so we're thinking about ways of introducing these concepts that are backed by the database whenever possible. Concretely, we're looking into [Table Inheritance](https://www.martinfowler.com/eaaCatalog/) to support Unions.
> 
> Do you have a specific use case in mind? Any code or examples would help us to get this right.

As you are asking for specific use cases, I would like to present my own, featuring a heterogeneous collection:

```
model QuizItem {
  id   String       @id @default(cuid())
  quiz Quiz         @relation(onDelete: CASCADE)
  type QuizItemType
  stem String

  t_MultipleOptions MultipleOptionsQuizItemParams?
  t_Numeric         NumericQuizItemParams?
}

enum QuizItemType {
  MULTIPLE_OPTIONS
  NUMERIC
}

model MultipleOptionsQuizItemParams {
  id                   String   @id @default(cuid())
  quizItem             QuizItem @relation(references: id, onDelete: CASCADE)
  options              Option[]
  constraints_minCount Int?     @default(1)
  constraints_maxCount Int?     @default(1)
}

model Option {
  id         String   @id @default(cuid())
  quizItem   QuizItem @relation(onDelete: CASCADE)
  text       String
  isSolution Boolean  @default(false)
}

model NumericQuizItemParams {
  id                   String   @id @default(cuid())
  quizItem             QuizItem @relation(references: id, onDelete: CASCADE)
  solution             Float?
  precision            Float?   @default(0)
  stepSize             Float?   @default(1)
  constraints_minValue Float?
  constraints_maxValue Float?
}
```

`MultipleOptionsQuizItemParams` and `NumericQuizItemParams` would be subclasses of `QuizItem` in an object-oriented environment. The following model would serve as a container for `QuizItem` models, e.g. the aforementioned specializations:

```
model Quiz {
  id                 String     @id @default(cuid())
  author             User       @relation(onDelete: CASCADE)
  createdAt          DateTime   @default(now())
  updatedAt          DateTime   @updatedAt
  isPrivate          Boolean    @default(false)
  title              String
  timeLimitInMinutes Int?
  items              QuizItem[]
}
```

**Comment by janpio** [comment]
Internal Note: We think about this as table inheritance.

**Comment by GaborTorma** [comment]
This is also an important things for me.
Please find my temporary solution:

Schema: `model ClientData { // normaly need to be interface
  id String @default(cuid()) @id
}
model IndividualData { // normaly implemented from ClientData interface
  id           String  @default(cuid()) @id
  name         String?
  zip          String?
  city         String?
  street       String?
}
model CompanyData { // normaly implemented from ClientData interface
  id           String  @default(cuid()) @id
  company         String?
  tax          String?
  regNo         String?
}
model Client {
  id        String     @default(cuid()) @id
  dataId    String?  //normaly need to be ClientData interface (now is store the id from CompanyData and IndividualData)
}
`

Type of client: `
const { objectType, interfaceType, stringArg } = require('nexus')
const { allModel } = require('../utils/allPhoton.js')
const { resolveInterfaceById } = require('../utils/resolveInterface.js')

const Client = objectType({
    name: 'Client',
    definition(t) {
        allModel(t)
        t.field('data', {
            type: ClientData,
            resolve: ({ dataId }, args, ctx, info) =>
                resolveInterfaceById(dataId, ctx, info),
        })
        t.field('result', {
            type: ClientResult,
            args: { type: stringArg() },
            resolve: ({ resultId }, args, ctx, info) =>
                resolveInterfaceById(resultId, ctx, info),
        })
    },
})

const ClientData = interfaceType({
    name: 'ClientData',
    definition(t) {
        t.resolveType(item => item.__typename)
        t.model.id()
    },
})

const ClientData1000 = objectType({
    name: 'ClientData1000',
    definition(t) {
        t.implements(ClientData)
        allModel(t)
    },
})

const ClientResult = interfaceType({
    name: 'ClientResult',
    definition(t) {
        t.resolveType(item => item.__typename)
        t.model.id()
    },
})

const ClientResult1000 = objectType({
    name: 'ClientResult1000',
    definition(t) {
        t.implements(ClientResult)
        allModel(t)
    },
})

module.exports = {
    Client,
    ClientData,
    ClientData1000,
    ClientResult,
    ClientResult1000,
}`

Utils for resolve Interface type from GraphQL query witzh regexp:`
function parsePathKeys(path, keys) {
    if (path.key !== 0) {
        keys.push(path.key)
    }
    if (path.prev) {
        parsePathKeys(path.prev, keys)
    }
    return keys
}

function parseTypeFromQuery(query, path) {
    let regexp = '(?:.{3}\\son)[^A-Z]*(?<type>\\w*)'
    parsePathKeys(path, []).forEach(
        key => (regexp = key + '.*?{(?:.|\\r|\\n)*?' + regexp),
    )
    const match = query.match(new RegExp(regexp))

    if (!match || !match.groups.type) {
        throw new Error(`Interface type not found`)
    }

    return match.groups.type
}

function typeToQueryName(type) {
    return type.charAt(0).toLowerCase() + type.slice(1) + 's'
}

async function resolveInterfaceById(id, { request, photon }, { path }) {
    const type = parseTypeFromQuery(request.body.query, path)
    const query = typeToQueryName(type)
    const item = await photon[query].findOne({
        where: { id },
    })
    return {
        ...item,
        __typename: type,
    }
}

module.exports = {
    parsePathKeys,
    parseTypeFromQuery,
    typeToQueryName,
    resolveInterfaceById,
}
`
An example gql query:`
query {
  clients {
    data {
      ... on ClientData1000 {
        id
        zip
        city
        name
      }
    }
  }
}`

**Comment by ssalbdivad** [comment]
@matthewmueller Would really love to see this prioritized. "Next month or two" was mentioned as a timeline 5 months ago and it's a really critical feature for users trying to adopt prisma who are used to defining types in TS or GraphQL.

**Comment by matthewmueller** [comment]
Note: unassigning myself on things I'm not actively working on. I may pick this up in the future.

**Comment by cr101** [comment]
Another use case for inheritance:

```
type Person {
  id: ID @unique
  name: String
  createdAt: DateTime
  updatedAt: DateTime
}
type Employee extends Person {
  department: String
  role: String
}
type Customer extends Person {
  type: String
}
```

**Comment by erikwien** [comment]
For another use-case, a structure we've struggled to find good solutions for is something to represent rich text with custom block elements that go beyond simple HTML/markdown.

Consider the following GraphQL schema:
```
enum MediaBlockAlignment {
    CENTERED
    LEFT
    RIGHT
}

enum MediaBlockWidth {
    FULL
    HALF
}

type MediaBlock {
    id: ID!
    url: String! # A URL of an image or a video or something
    alignment: MediaBlockAlignment!
    width: MediaBlockWidth!
}

type TextBlock  {
    id: ID!
    text: String # Some kind of structured text, Markdown, HTML, or other structure.
}

union Block = MediaBlock | TextBlock

type BlogPost {
    id: ID!

    headline: String
    abstract: String
    body: [Block!]!

    createdAt: DateTime!
    updatedAt: DateTime!
}
```

This structure is fairly natural in GraphQL (see above) but its surprisingly hard to find a ORM/Headless CMS that can represent this structure easily. Prisma looked extremely promising until we ran into this issue.

**Comment by jide** [comment]
FWIW, this can be implemented at the application level in a resolver, with a custom resolveType. But you loose ability to query the db easily with paging etc on the abstract type.

**Comment by cr101** [comment]
I have two models in my schema `Person` and `Organization` and the issue I came across is that the `shareholders` field in the `Organization` model can be both a `Person` and/or an `Organization`.

```
datasource postgresql {
  provider  = "postgresql"
  url       = env("POSTGRESQL_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id             Int       @id  @default(autoincrement())
  email          String    @unique
  password       String
  firstName      String
  lastName       String  
  role           Role      @default(USER)
  person         Person
  createdBy      User      
  createdAt      DateTime  @default(now())
  updatedAt      DateTime  @updatedAt
}

enum Role {
  USER
  ADMIN
}

model Person {
  id                    Int              @id  @default(autoincrement())
  firstName             String
  lastName              String
  createdBy             User
  user                  User?             @relation(references: [id])
  foundedOrganizations  Organization[]
  createdAt             DateTime          @default(now())
  updatedAt             DateTime          @updatedAt
  # .. other fields
}
```
> // The shareholders in an Organization can be both an Organization and/or a Person.
```
model Organization {
  id              Int             @id      @default(autoincrement())
  name            String          @unique
  description     String?
  founders        Person[]
  shareholders    // STUCK HERE!!!
  createdBy       User           
  createdAt       DateTime       @default(now())
  updatedAt       DateTime       @updatedAt
  # .. other fields
  @@index ([name])
}
```

My use case is similar to the interface/union part of [datamodel 1.1](https://github.com/prisma/prisma1/issues/3407)

**Comment by ledniy** [comment]
Similar use case for Union is EAV model, for example schema: 
![image](https://user-images.githubusercontent.com/1562848/80278583-555b0680-8700-11ea-8a6f-7d6ead3549b5.png)

**Comment by matthewmueller** [comment]
Thanks for your use cases everyone! I'm splitting up this issue.

- We're tracking Interfaces in [this issue](https://github.com/prisma/prisma1/issues/83).
- We're tracking Union in [this issue](https://github.com/prisma/prisma/issues/2505).
