### ISSUE TITLE
.raw errors on date params w/ Postgres

### ISSUE THREAD

**Issue by cap10morgan** [prisma/prisma#2533]
## Bug description

When running a raw SQL query with `prisma.raw` and template literal params, I get the error below when querying on timestamp columns:

```
error: PrismaClientKnownRequestError: Raw query failed. Code: `22P03`. Message: `db error: ERROR: incorrect binary data format in bind parameter 2`
  engine       at NodeEngine.graphQLToJSError (/Users/wmorgan/dev/safe-office/api/node_modules/@prisma/engine-core/dist/NodeEngine.js:590:1)
  engine       at /Users/wmorgan/dev/safe-office/api/node_modules/@prisma/engine-core/dist/NodeEngine.js:498:1
  engine       at process.result (internal/process/task_queues.js:97:5)
  engine       at PrismaClientFetcher.request (/Users/wmorgan/dev/safe-office/api/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:628:13) {
  engine     code: 'P2010',
  engine     meta: {
  engine       code: '22P03',
  engine       message: 'db error: ERROR: incorrect binary data format in bind parameter 2'
  engine     }
  engine   }
  engine }
```

## How to reproduce

1. Create a DB table in Postgres with a timestamp without time zone field.
1. Query it via prisma.raw like this: ``prisma.raw`select * from table where tzfield=${dateValue}` ``
    1. For `dateValue` I tested with both ISO-formatted date strings and JS Date objects.

## Expected behavior

The query works and returns the same data as a query not involving timestamp fields.
## Environment & setup
- OS: macOS
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.5
- Node.js version: v12.16.3

**Comment by pantharshit00** [comment]
I can confirm the issue. My guess is that we are implicitly converting every date into ISO format in the client code. 


Reproduction:
1. Bootstrap postgres database with following SQL:
```sql
DROP TABLE IF EXISTS "public"."example";
-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS example_id_seq;
-- Table Definition
CREATE TABLE "public"."example" (
    "id" int4 NOT NULL DEFAULT nextval('example_id_seq'::regclass),
    "time" timestamp,
    PRIMARY KEY ("id")
);
INSERT INTO "public"."example" ("id", "time") VALUES
('1', '2020-05-29 16:08:54.028741');
```

2. Introspect the database and generate the client
3. Run the following code:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const client = new PrismaClient();

  const date = "2020-05-29T16:08:54.028741+00:00";
  console.log(date);

  const data = await client.raw`select * from example where time = ${date}`;
  console.log(data);
  client.disconnect();
}

main();
```

**Comment by pimeys** [comment]
The client fix is coming later today. From now on when wanting to use dates in raw queries, they should be provided as JavaScript `Date` objects for them to work.

**Comment by timsuchanek** [comment]
And the client part is also merged.
In order to make Date work, you now need to explicitly provide a `Date` instance in JavaScript, otherwise, we can't reliably and fast coerce the type.

**Comment by johhansantana** [comment]
This should be explained somewhere in the [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/raw-database-access#tagged-template-helpers). I didn't see anything relating this there.

**Comment by janpio** [comment]
cc @mhwelander
