### ISSUE TITLE
createManyAndReturn() for SQL Server

### ISSUE THREAD

**Issue by YaakovR** [prisma/prisma#25335]
## Problem

Could you please add [createManyAndReturn()](https://www.prisma.io/docs/orm/prisma-client/queries/crud#create-and-return-multiple-records) for SQL Server?

**Comment by SevInf** [comment]
Hi @YaakovR, feature request is already tracked in #24727

**Comment by YaakovR** [comment]
@SevInf Thanks for catching! I did not notice that earlier.
