### ISSUE TITLE
[Re-Introspection] Keep defaults that are not persisted in the database

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2534]
## Problem
There are multiple default values that are not persisted in the database, most important [`uuid()` and `cuid()`](https://github.com/prisma/specs/tree/master/schema#function). Re-Introspection thus looses them, making it necessary for users to be on the lookout for them and apply them manually again.

## Suggested solution
Use the old schema as input to figure out if these fields were `cuid()` or `uuid()` before and apply those as defaults for the fields again. 

(Additional rules to the possible native field type may apply and might give additional input if the default is still applicable to the field)

---

Related issue that adds these default to the schema on Introspection of a P1 schema in the first place: https://github.com/prisma/prisma/issues/2499

**Comment by do4gr** [comment]
This can not be implemented currently. There are two ways how an `@default` directive made its way into the previous Prisma schema that Re-Introspection uses as input. Depending on which one is true different actions need to be taken. But currently we cannot tell the underlying reasons apart. Having different directives for these would be one remedy.

1. A default value was present in a previous version of the underlying database schema and therefore added to the Prisma schema be a previous introspection run. 
2. There was no default value in the previous database schema, but the user added it manually to the Prisma schema. 

For 1 Re-Introspection should not keep the default value. For 2 it should keep the default value.

**Comment by divyenduz** [comment]
This can also have the following variation: 

There is a default in the database but that is overridden in the schema. Example (see `content` field),

```sql
CREATE TABLE `post` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(191) NOT NULL ,
  `content` varchar(191) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

```prisma
model Post {
  id Int @id @default(autoincrement())
  title String
  content String @default("Please enter content")
}
```

**Comment by janpio** [comment]
We decided to limit this issue to `uuid()` and `cuid()` only which are Prisma level only features and can properly be re-introspected by looking at the previous Prisma schema file.
