### ISSUE TITLE
ArangoDB support

### ISSUE THREAD

**Issue by mikestaub** [prisma/prisma#2535]
This is my favorite NoSQL database. https://arangodb.com

Its like redis + MongoDB + Neo4j all in one engine.

**Comment by mysticaltech** [comment]
And don't forget Search. It's one of the best multi-model DB available to date, Document, Key-Value, Graph and Search. That makes A[rangoDB.com](https://www.arangodb.com/) truly awesome. Support for it would be much appreciated. 

Their official Typescript client https://github.com/arangodb/arangojs is well maintained and quite powerful, it would be very useful in an eventual integration with Prisma.

**Comment by natejgardner** [comment]
Would like this, by far my favorite database.

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
