### ISSUE TITLE
[Prisma Client] Duplicate identifier with models "X" and "XClient"

### ISSUE THREAD

**Issue by dodas** [prisma/prisma#2539]
Consider following datamodel:
```prisma
model Company {
   ...
}

model CompanyClient {
   ...
}
```

Prisma seem to generate `class` for each model, with `Client` appended to its name:
```ts
// this is corresponding to model "Company"
export declare class CompanyClient<T> implements Promise<T> {
  ...
}

//  this is corresponding to model "CompanyClient"
export declare class CompanyClientClient<T> implements Promise<T> {
  ...
}
```

..but it also generates `type` for each model, without appending anything to its name:
```ts
export type Company = {
   ...
} 

export type CompanyClient = {
   ...
} 
```

This leads to typescript error, as `type CompanyClient` is clashing with `class CompanyClient`:
```
Duplicate identifier 'CompanyClient'. ts(2300)
```

Naming convention for "Client" classes should be altered, probably..

---
Prisma CLI / client version: 2.0.0-beta.5

**Comment by pantharshit00** [comment]
I can confirm this bug. Thanks for reporting!

I also think we not add this case to the deny list as this naming pattern seems a bit common.

**Comment by Jolg42** [comment]
It looks like it is already in the denylist. I will double check.
https://github.com/prisma/prisma/blob/ebe1b08ae192006281cfe7ad4f73fe35a31004d7/src/packages/client/src/generation/generateClient.ts#L561

**Comment by Jolg42** [comment]
Thank you for the issue, the "denylist" is now applied to model names as well with tests.

You probably want to rename your models to avoid a conflict here with `@@map`:
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/configuring-the-prisma-client-api#using-map-and-map-to-rename-fields-and-models-in-the-prisma-client-api

**Comment by dodas** [comment]
Does that mean that issue is fixed and I can keep current model names after eventual prisma release?
Thanks!

**Comment by Jolg42** [comment]
@dodas So no it means that out internal list of reserved word just got updated and it will error properly now if you retry with the latest alpha.

So you will need to change the names of your models. And if you already have these models in your database you could use `@@map` to keep them and only change the names for the Prisma Client / Schema.

**Comment by dodas** [comment]
:( that's unfortunate solution.
I think that naming models ,,SomethingClient" can be quite common and having to rename model that corresponds to business domain is not nice thing to do.
Couldn't the ,,Client" classes be named differently instead? Perhaps in a way that they could never clash with data models?
Or maybe they can be defined in different file and prevent duplicate identifier that way?

**Comment by dodas** [comment]
That's unfortunate solution...
I think that naming models ,,SomethingClient" can be quite common and having to rename model that corresponds to business domain is not nice thing to do.
Couldn't the ,,Client" classes be named differently instead? Perhaps in a way that they could never clash with data models?
Or maybe they can be defined in different file and prevent duplicate identifier that way?

**Comment by Jolg42** [comment]
I understand the problem here and I'm also in favor of finding a better solution 👍 
The best would be to open an issue for that, could you do that?

**Comment by pantharshit00** [comment]
I propose prefixing our implementation with internal. I don't know if this will be a breaking change or not:
`${name}InternalClient`


Generally we should prefix out implementation. What are your thoughts @Jolg42 ?

**Comment by pantharshit00** [comment]
I opened: https://github.com/prisma/prisma-client-js/issues/707
