### ISSUE TITLE
EXTRACT SQL function returns Prisma.Decimal instead of number in queryRawTyped with SQL file

### ISSUE THREAD

**Issue by malbaugh** [prisma/prisma#25409]
### Bug description

When using the SQL `EXTRACT` function in a raw query stored in a separate SQL file and executed with Prisma's `queryRawTyped`, the return type is incorrectly inferred as `Prisma.Decimal` instead of `number`. This causes type errors when trying to use the extracted values as numbers in TypeScript.

### How to reproduce

1. Create a Prisma schema with a model that has a date field.
2. Create a separate SQL file with a query using the `EXTRACT` function on the date field.
3. Use Prisma's `queryRawTyped` to execute the query from the SQL file.
4. Observe that the extracted values are typed as `Prisma.Decimal` instead of `number`.

### Expected behavior

The `EXTRACT` function should return a `number` type when used in raw SQL queries executed with `queryRawTyped`, as it does in standard SQL.

### Prisma information

```prisma
// Simplified schema.prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model OrderEntryView {
  id           String   @id @default(uuid())
  issuedAt     DateTime
  totalOrdered Decimal
  // ... other fields
}
```

```sql
-- prisma/sql/getOrdersByQuarter.sql
SELECT 
  EXTRACT(YEAR FROM "issuedAt") AS "year", 
  EXTRACT(QUARTER FROM "issuedAt") AS "quarter", 
  SUM("totalOrdered") AS "totalOrdered"
FROM "OrderEntryView"
WHERE "organizationId" = $1 
  -- ... (additional WHERE clauses)
GROUP BY "year", "quarter"
ORDER BY "year" ASC, "quarter" ASC;
```

Utilizing this data as `Prisma.Decimal` will throw errors.

```ts
// TypeScript code using Prisma Client
import { PrismaClient, Prisma } from '@prisma/client';
import { getOrdersByQuarter } from '@prisma/client/sql';

const prisma = new PrismaClient();

// Type 
interface QuarterlyOrdersQueryResult {
  year: Prisma.Decimal | null;
  quarter: Prisma.Decimal | null;
  totalOrdered: Prisma.Decimal | null;
}

// No type error
async function getQuarterlyOrders(organizationId: string): Promise<QuarterlyOrdersQueryResult[]> {
  return prisma.$queryRawTyped(
    getOrdersByQuarter(organizationId, /* other parameters */)
  );
}

const results = await getQuarterlyOrders('org-id');
const multipliedYears = results.map(r => r.year.toNumber() * 2); // Unexpected error occurs due to wrong type
```

Forcing the type to `number` will work as intended.

```ts
// TypeScript code using Prisma Client
import { PrismaClient, Prisma } from '@prisma/client';
import { getOrdersByQuarter } from '@prisma/client/sql';

const prisma = new PrismaClient();

// Type 
interface QuarterlyOrdersQueryResult {
  year: number | null;
  quarter: number | null;
  totalOrdered: Prisma.Decimal | null;
}

// Type Error: Types of property 'year' are incompatible.
// Type 'Decimal | null' is not assignable to type 'number | null'.
async function getQuarterlyOrders(organizationId: string): Promise<QuarterlyOrdersQueryResult[]> {
  return prisma.$queryRawTyped(
    getOrdersByQuarter(organizationId, /* other parameters */)
  );
}

const results = await getQuarterlyOrders('org-id');
const multipliedYears = results.map(r => r.year * 2); // Type error thrown, but works as intended when casted to number
```

### Environment & setup

- OS: MacOS Sequoia 15.1
- Database: PostgreSQL
- Node.js version: v22.9.0

### Prisma Version

```
prisma                  : 5.20.0
@prisma/client          : 5.20.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v22.9.0
Query Engine (Node-API) : libquery-engine 06fc58a368dc7be9fbbbe894adf8d445d208c284 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 06fc58a368dc7be9fbbbe894adf8d445d208c284 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.20.0-12.06fc58a368dc7be9fbbbe894adf8d445d208c284
Default Engines Hash    : 06fc58a368dc7be9fbbbe894adf8d445d208c284
Studio                  : 0.502.0
Preview Features        : fullTextSearch, views, typedSql
```

**Comment by SevInf** [comment]
Hi @malbaugh.
Typed SQL relies on the types, reported by the Postgres. In case of `EXTRACT` you are unfortunately incorrect, it's return type is `numeric`, not `int`: [proof](https://www.db-fiddle.com/f/4rHURxEEEnwDYVqrz2ZpBk/0).

You can add a typecast to your SQL query and TypedSQL will pick that up:

```sql
EXTRACT(YEAR FROM "issuedAt")::INT AS "year"
```

Let me know if that helps!

**Comment by malbaugh** [comment]
> Hi @malbaugh.
> 
> Typed SQL relies on the types, reported by the Postgres. In case of `EXTRACT` you are unfortunately incorrect, it's return type is `numeric`, not `int`: [proof](https://www.db-fiddle.com/f/4rHURxEEEnwDYVqrz2ZpBk/0).
> 
> 
> 
> You can add a typecast to your SQL query and TypedSQL will pick that up:
> 
> 
> 
> ```sql
> 
> EXTRACT(YEAR FROM "issuedAt")::INT AS "year"
> 
> ```
> 
> 
> 
> Let me know if that helps!

Thank you!
