### ISSUE TITLE
Prisma support for Deno

### ISSUE THREAD

**Issue by LaurenceM10** [prisma/prisma#2541]
Feature requests

Deno was released a few days ago, is there any plan to support it?
https://deno.land/v1

**Comment by Sytten** [comment]
Duplicates of https://github.com/prisma/prisma/issues/2452

**Comment by pantharshit00** [comment]
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #2452 

Thanks @Sytten 🎉
