### ISSUE TITLE
Unique constraint issue while using MongoDB

### ISSUE THREAD

**Issue by aryabhthakur** [prisma/prisma#25423]
### Bug description

I am using NestJS and prisma for mongodb, I started facing this issue since I updated my prisma to v5.20.0

![Screenshot 2024-10-14 114341](https://github.com/user-attachments/assets/37d5a809-6854-48c8-8d75-f3da7faf5b52)
![Screenshot 2024-10-14 121044](https://github.com/user-attachments/assets/9a35c2fb-789b-4ddb-a45b-e7679f9f370d)

### Expected behavior

It will throw an unique constraint error
![Screenshot 2024-10-14 114341](https://github.com/user-attachments/assets/f852220d-7375-4d96-95e1-ff45daaba415)

### Prisma information

```prisma
// Add your schema.prisma
model User {
  uuid                   String                  @id @default(auto()) @map("_id") @db.ObjectId
  email                  String                  @unique
  email_verified         Boolean                 @default(false)
  name                   String
  google_connected       Boolean?                @default(false)
  google_connected_email String?
  @@unique([google_connected_email])
}
```
```ts
// Add your code using Prisma Client (I am using NestJS and it's prisma [recipe ](https://docs.nestjs.com/recipes/prisma))
await this.prisma.user.create({
      data,
      include,
    })
```

### Environment & setup

- OS: Windows 11 Pro
- Database: MongoDB 
- Node.js version: 20.10.0

### Prisma Version

```
5.20.0
```

**Comment by SevInf** [comment]
Hi @aryabhthakur!
Your schema has a unique constraint over `google_connected_email` field. The error basically tells you are trying to create a document which violates this constraint: meaning there is already a document with the same `google_connected_email` you are trying to create. If that's not the case for you, please provide a reproduction repository where we could see it happen. Be sure to include the data present in your DB into reproduction.
Thanks!

**Comment by aryabhthakur** [comment]
@SevInf that's the issue! the database is newly formed. It has no entry, I tried deleted indexes and recreating them using db pull but still same!

![Screenshot 2024-10-14 130750](https://github.com/user-attachments/assets/86e88088-8978-43af-85c0-ae4c09bcb8ff)
![Screenshot 2024-10-14 130730](https://github.com/user-attachments/assets/1c9a3ee4-8f77-409f-bd84-b00f43cc1aaa)

**Comment by SevInf** [comment]
@aryabhthakur could you provide an isolated reproduction repository where we could see the error happening?

**Comment by aryabhthakur** [comment]
Hi @SevInf  seems it was MongoDB's issue!! I create new database and it worked fine init.
