### ISSUE TITLE
Prisma rust not working 

### ISSUE THREAD

**Issue by Riddhiman007** [prisma/prisma#25456]
Hi Prisma Team! The following command just crashed.

## Command

`generate`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.16.0           | 
| Prisma CLI  | 4.8.0              | 
| Engine      | d6e67a83f971b175a593ccc12e15c4a757f93ffe| 

## Error
```
Error: Command failed with exit code 101: C:\Users\Lenovo\AppData\Local\prisma\binaries\cli\4.8.0\d6e67a83f971b175a593ccc12e15c4a757f93ffe\prisma-query-engine-windows.exe --enable-raw-queries cli dmmf
```

**Comment by jkomyno** [comment]
Hi @Riddhiman007, Prisma 4.8.0 is very old, and no longer supported. Can you please upgrade to a recent Prisma version, try again and leave a comment below? The most recent one is Prisma 5.21.1. Thanks!
