### ISSUE TITLE
Issue with Prisma Query Engine Panic: Unable to Export JSON File Due to VRAM Error in Local Environment

### ISSUE THREAD

**Issue by Ganlinniale** [prisma/prisma#25474]
### Bug description

I encountered an issue where I cannot export a conversation history JSON file due to a Prisma Query Engine panic in a local environment setup. The error appears to be related to VRAM allocation for my NVIDIA GPU, possibly connected to Faraday, which I’m using in this setup.

The following message appears in the console:Invalid Vt.modelLayerSamples.upsert() invocation in C:\Users\kenny\AppData\Local\faraday\app-0.30.0\resources\app.asar\dist\server\main.js:1144:63297
...
This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

### Expected behavior

When trying to export a JSON file in my local setup, Prisma crashes due to an invalid invocation of Vt.modelLayerSamples.upsert() during a process involving GPU VRAM allocation. The application (Faraday) attempts to read the GPU’s free and total VRAM but encounters an issue, specifically with fetching accurate VRAM values for NVIDIA GPUs. This results in a Prisma panic, making the operation non-recoverable.

### Prisma information

This issue occurred within an application using Prisma in conjunction with a local environment (Windows) involving VRAM allocation for an NVIDIA GPU (RTX 3070). It involves a large conversation history, which might contribute to the problem. Below is a snippet of the log error I received:Invalid `Vt.modelLayerSamples.upsert()` invocation...
...
This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

### Environment & setup

OS: Windows 10
Processor: Intel i7-11800
GPU: NVIDIA RTX 3070
RAM: 16 GB
Prisma Client: Using Prisma for a local project
Application: Faraday (app-0.30.0)
Other tools: Powershell (used by Faraday to fetch VRAM information), Vulkan

### Prisma Version

```

```
I don't know what version of Prisma it is; I'm using Backyard AI version:v0.30.0

**Comment by aqrln** [comment]
Prisma doesn't use GPU in any way and can't possibly fail with any GPU related errors. Please report this issue to the application this problem happens in. If there is a Prisma issue, please provide an actionable reproduction steps, including the schema and the query that fail and the specific error that originates in Prisma.
