### ISSUE TITLE
Introspection doesn't recognize enums in PostgreSQL

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#2548]
I started with a Prisma 1 data model that had an enum (removed all irrelevant models):

```graphql
type User {
  id: ID! @id
  role: Role! @default(value: CUSTOMER)
}

enum Role {
  ADMIN
  CUSTOMER
}
```

This created this SQL: 

```sql
CREATE TABLE "User" (
  id VARCHAR(25) PRIMARY KEY NOT NULL,
  role TEXT
);
```

I then made it an enum with the statements:

```sql
CREATE TYPE "Role" AS ENUM ('CUSTOMER', 'ADMIN');
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role"
USING "role"::text::"Role";
```

In my DB, this seems to have worked:

```sql
CREATE TABLE "User" (
    id character varying(25) PRIMARY KEY,
    role "Role" NOT NULL,
);
```

But when running introspection I get this warning:

```
*** WARNING ***

These fields were commented out because we currently do not support their types.
- Model "User", field: "role", original data type: "Role"
```

And the resulting Prisma schema shows this:

```prisma
model User {
  id        String    @id
  // This type is currently not supported.
  // role   Role
}
```

Should this enum be recognized by introspection?

**Comment by pantharshit00** [comment]
We don't support enums in the sqlite connector and I think Prisma 1 sqlite enums were enforced on the database level. 


Marking this as a bug but not sure what we can do here right now.

**Comment by nikolasburk** [comment]
Sorry I'm not sure I can follow @pantharshit00, this is about PostgreSQL not SQLite!

**Comment by pantharshit00** [comment]
Oof, missed the detail 🤦. Leftover memory from last issue. 

Anyways this is surely a bug now

**Comment by do4gr** [comment]
I just tried recreating the problem and it now works. There was some change to Enum handling so I assume this got fixed by that. Can you please validate that it now works for you @nikolasburk ?
