### ISSUE TITLE
Suddenly unable to run migrate dev

### ISSUE THREAD

**Issue by onlit** [prisma/prisma#25504]
Hi Prisma Team! The following command just crashed.

## Command

`migrate dev`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v20.13.1           | 
| Prisma CLI  | 4.10.1             | 
| Engine      | aead147aa326ccb985dcfed5b065b4fdabd44b19| 

## Error
```
Error: unreachable
```

**Comment by jkomyno** [comment]
Hi @onlit, we can't help you unless you share more information with us.
What was your `schema.prisma`? What change did you apply before the migration engine crashed?

Also, Prisma 4.10.1 is very old, and unmaintained. Please [upgrade to Prisma 5](https://www.prisma.io/docs/orm/more/upgrade-guides/upgrading-versions/upgrading-to-prisma-5) (currently, the latest version is 5.21.1), try again, and open a new issue if needed. Thanks!
