### ISSUE TITLE
2:15 delay when Prisma generate is used after upgrade from ^5.6.0 to ^5.21.1

### ISSUE THREAD

**Issue by flesler** [prisma/prisma#25527]
### Bug description

I upgraded and now, in the cloud whenever I deploy I get these logs:
```
Oct 28 22:45:36 web: > prisma generate --no-hints
Oct 28 22:45:37 web: Prisma schema loaded from prisma/schema.prisma
Oct 28 22:47:52 web: ✔ Installed the @prisma/client and prisma packages in your project
Oct 28 22:48:00 web: ✔ Generated Prisma Client (v5.21.1) to ./node_modules/@prisma/client in 1.36s
```
See the 2:15 delay between line 2 and 3. It's unusable, happens on every deploy. Note that I have the `tracing` previewFeature!

### How to reproduce

For me, it was simply upgrade and then deploy to the cloud.

### Expected behavior

The deploy takes ~15s as it used to. If I reload the server without deploying, it's fast. Maybe some cache is being busted (like the binary download?)

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native"]
  previewFeatures = ["tracing"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

```ts
import { PrismaClient } from '@prisma/client'
...

const TIMEOUT_SECONDS = 8
const POOL_SIZE = 100

const db = new PrismaClient({
  log: [{ level: 'query', emit: 'event' }],
  errorFormat: 'colorless',
  datasources: { db: { url: `${env.DATABASE_URL}?connection_limit=${POOL_SIZE}&pool_timeout=${TIMEOUT_SECONDS}` } },
})

db.$use(error)
db.$use(ids)
db.$use(softDelete)

export default db
```

### Environment & setup

- OS: Node.js 18 running on 64bit Amazon Linux 2/5.8.6 on AWS ElasticBeanstalk
- Database: PostgreSQL 13 
- Node.js version: ^18.18.0

### Prisma Version

This is in the cloud:
```
prisma                  : 5.21.1
@prisma/client          : 5.21.1
Computed binaryTarget   : linux-arm64-openssl-1.0.x
Operating System        : linux
Architecture            : arm64
Node.js                 : v18.18.0
Query Engine (Node-API) : libquery-engine bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.0.x.so.node)
Schema Engine           : schema-engine-cli bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/schema-engine-linux-arm64-openssl-1.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.21.1-1.bf0e5e8a04cada8225617067eaa03d041e2bba36
Default Engines Hash    : bf0e5e8a04cada8225617067eaa03d041e2bba36
Studio                  : 0.503.0
Preview Features        : tracing
```
This is locally (works fine)
```
prisma                  : 5.21.1
@prisma/client          : 5.21.1
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.18.2
Query Engine (Node-API) : libquery-engine bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.21.1-1.bf0e5e8a04cada8225617067eaa03d041e2bba36
Default Engines Hash    : bf0e5e8a04cada8225617067eaa03d041e2bba36
Studio                  : 0.503.0
Preview Features        : tracing
```

**Comment by jkomyno** [comment]
Hi @flesler, can you please share your actual Prisma schema? The `prisma generate` time tends to grow with the number of models declared in your schema.

Also, when you say that "it works fine" locally, does it mean that `prisma generate` takes a few seconds on your machine, rather than over 2 minutes in your AWS cloud instance?

**Comment by flesler** [comment]
Hi @jkomyno thanks for the quick response. 
> does it mean that prisma generate takes a few seconds on your machine (x64), rather than over 2 minutes in your AWS cloud instance (arm64)?
Exactly, takes a couple of seconds

> can you please share your actual Prisma schema? The prisma generate time tends to grow with the number of models declared in your schema.
It's not a huge schema and locally it's fast. I could share via email or some other private channel. It's from work. If you give me an email I can send. But surely the size is not the culprit, it has 47 models, 64 tables if you add the many-to-many and migrations tables.

**Comment by flesler** [comment]
@jkomyno I was able to make the problem go away. While upgrading I had `prisma` in npm's `dependencies` and also `@prisma/client`. While installing the latter got moved to `devDependencies`. I moved it back and the problem went away, might not be the reason ofc :shrug:
