### ISSUE TITLE
when we use the createMany function 

### ISSUE THREAD

**Issue by attia-moh** [prisma/prisma#25559]
### Bug description

"PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `unknown`).
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report"

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by aqrln** [comment]
Hey @attia-moh, please provide the information required by the issue template and a reproduction and re-open the issue. Right now it's impossible to investigate it without any information whatsoever.
