### ISSUE TITLE
Output notice about Prisma1->Prisma2 upgrade documentation and tool

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2555]
After Introspection we want to output some text (TBD) that links to our Prisma1->Prisma2 upgrade documentation. This should be triggered by https://github.com/prisma/prisma/issues/2424 (and only be shown on `Prisma1` and `Prisma11`).

- [x] Define text that should be shown to users
- [x] Define where the text will be shown to users
- [x] Combine both for implementation

**Comment by timsuchanek** [comment]
> Define where the text will be shown to users
We can show this at the end of our introspection command.

**Comment by Jolg42** [comment]
![image](https://user-images.githubusercontent.com/1328733/82874721-a8f68500-9f36-11ea-87db-bc4d428186c5.png)

Maybe at the end
```
This database was created from Prisma 1.
If you wish yo upgrade to Prisma 2 you can read the documentation here.
```
With link on `read the documentation here`

**Comment by nikolasburk** [comment]
I'd suggest the following output:

```
The database you introspect seems to belong to a Prisma 1 project. If you want to upgrade to Prisma 2.0, please visit the docs here: https://pris.ly/upgrading-to-prisma2
```

**Comment by janpio** [comment]
(We might iterate on the details of the text a bit more tomorrow, but this can already be implemented so we can start testing it.)

**Comment by Jolg42** [comment]
So I didn't remove the "(NonPrisma)" output yet, I guess I can now? (The message will only show for Prisma1 or Prisma11 values but my quick test was to fake it 😄)

This is the new look with latest alpha:
<img width="583" alt="Screen Shot 2020-05-27 at 10 14 10" src="https://user-images.githubusercontent.com/1328733/82995906-86cb3880-a004-11ea-9aa7-4ea59d095666.png">

And --print
<img width="563" alt="Screen Shot 2020-05-27 at 10 21 50" src="https://user-images.githubusercontent.com/1328733/82995923-8b8fec80-a004-11ea-96dc-f5b3a6c64062.png">

**Comment by Jolg42** [comment]
New output tested on Prisma 1 db
<img width="481" alt="Screen Shot 2020-05-27 at 12 09 12" src="https://user-images.githubusercontent.com/1328733/83007084-72db0300-a013-11ea-91fb-92b16e417c63.png">
--print
<img width="442" alt="Screen Shot 2020-05-27 at 12 12 26" src="https://user-images.githubusercontent.com/1328733/83007086-74a4c680-a013-11ea-9bb6-81d7bfe22f51.png">

**Comment by Jolg42** [comment]
<img width="539" alt="Screen Shot 2020-05-27 at 13 13 05" src="https://user-images.githubusercontent.com/1328733/83012661-00225580-a01c-11ea-8dce-64f2c9aff994.png">

**Comment by Jolg42** [comment]
<img width="553" alt="Screen Shot 2020-05-27 at 14 42 29" src="https://user-images.githubusercontent.com/1328733/83020489-d7ed2380-a028-11ea-99fb-ce7abf84954d.png">

**Comment by Jolg42** [comment]
It's in 2.0.0-alpha.1255
