### ISSUE TITLE
@default support for JSON

### ISSUE THREAD

**Issue by AnandChowdhary** [prisma/prisma#2556]
## Bug description

If you add a `@default` in the Prisma schema file with the `Json` data type, it throws an error for native JSON types:

- `@default([])`
- `@default({})`

Using beta 5.

**Comment by pantharshit00** [comment]
Hey @AnandChowdhary 

Sorry for late reply here. Right now we don't support defaults on Json fields on the schema level. So as a workaround you can use `@default(dbgenerated())` and set the default on the database level:
```prisma
model Test {
  id String @id @default(cuid())
  name String @default(dbgenerated())
}
```

**Comment by AnandChowdhary** [comment]
Thanks, @pantharshit00! In `beta.7`, https://github.com/prisma/prisma/issues/2432 was fixed, so let's keep this issue open until we have a fix, hopefully in the next beta?

**Comment by pantharshit00** [comment]
Defaults on Json field is schema level work so this will take some time. Use the workaround that I have specified in the meanwhile.

**Comment by jwld** [comment]
Just to flag a related issue here - running prisma migrate is currently overwriting any defaults that are set on the DB level https://github.com/prisma/migrate/issues/477

**Comment by Weakky** [comment]
Hey folks 👋,

I've just made some tests it seems that the JSON defaults _are_ already supported for both MySQL and Postgres (don't know since when). I might have missed something, but feel free to try the following:

1. Migrate a Prisma Schema with a JSON field.

```prisma
model Item {
  id   Int  @default(autoincrement()) @id
  json Json @default("{ \"name\": \"foo\" }")
}
```

2. Run the following query and observe the default being properly returned

```graphql
mutation {
  createOneItem(data: {}) {
    id
    json
  }
}
```

Notes:
- On Postgres, the default is properly set as the db level
- On MySQL, according to TablePlus, the default isn't set at the db level, yet the `create` operation properly returns the default value
- Limitation: We currently don't support actual JSON as attribute arguments. The JSON default needs to be provided as a string just like in the example

**Comment by AnandChowdhary** [comment]
@Weakky, I can confirm that I've been using this and it works:

![Screen Shot 2021-01-15 at 20 29 17](https://user-images.githubusercontent.com/2841780/104742369-5a6d5380-5770-11eb-8369-ed4d21d466fc.png)

**Comment by iMerica** [comment]
Escaping/quoting JSON is not a acceptable solution. What if we have a massively multi-dimensional JSON value for a default value and want our Prisma schema to be the source of truth? Escaping is not maintainable. 

Please re-open.

**Comment by craigcosmo** [comment]
> @Weakky, I can confirm that I've been using this and it works:
> 
> ![Screen Shot 2021-01-15 at 20 29 17](https://user-images.githubusercontent.com/2841780/104742369-5a6d5380-5770-11eb-8369-ed4d21d466fc.png)

The `@default("[]") ` doesn't do anything, have you check your table after you run that prisma ?

**Comment by LeoDoldan7** [comment]
> Escaping/quoting JSON is not an acceptable solution. What if we have a massively multi-dimensional JSON value for a default value and want our Prisma schema to be the source of truth? Escaping is not maintainable.
> 
> Please re-open.

+1. Please re-open!

**Comment by janpio** [comment]
Can one of you please open a new bug report with the full instructions on how to reproduce this? Json fields do support `@default`, so this feature request is correctly closed. If something does not work, please report it with a reproduction so we can understand and fix this. Thank you.

**Comment by wicahma** [comment]
any update on this?

**Comment by monsterooo** [comment]
any update on this?

**Comment by tameem-rafay-hansel** [comment]
any update on this ?

**Comment by AbbasAlibhaiER** [comment]
any update on this ?

**Comment by crrobinson14** [comment]
@AbbasAlibhaiER There won't be. It's closed.
