### ISSUE TITLE
Prisma postinstall hook doesn't work correctly 

### ISSUE THREAD

**Issue by hadarziv-army** [prisma/prisma#25564]
### Bug description

Prisma post install hook doesn't work correctly because I am using Bun instead of node

### How to reproduce

1. install bun
2. initialize project with prisma
3. run bun install 

### Expected behavior

post install hook should run correctly even if using Bun

### Prisma information

Doesn't matter

### Environment & setup

- OS: Windows
- Database:  PostgreSQL
- Node.js version: **I am using Bun**

### Prisma Version

```
5.19.1
```

**Comment by aqrln** [comment]
According to https://bun.sh/docs/install/lifecycle, you need to allow running postinstall scripts for Prisma by putting it into `trustedDependencies` if you want to use them.
