### ISSUE TITLE
Error: (0 , DSe.isError) is not a function

### ISSUE THREAD

**Issue by karthik-nair-20** [prisma/prisma#25560]
### Bug description

 npx prisma init
Error: (0 , DSe.isError) is not a function

WHEN EVER I USE this command I am getting this error, I am so struck in here,
I read some one mentioned downgrade node version and it would work, BUT IT HAS NOT mate/

I have checked with v20.18.0, v18.20.0 all give the same error

### How to reproduce

npm I prisma
 npx prisma init

### Expected behavior

should install Prisma

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```latest

```

**Comment by karthik-nair-20** [comment]
Solution:

instead if npx Prisma init

directly ran ./node_modules/prisma/index

**Comment by AngeloCodeHub** [comment]
> Solution:
> instead if npx Prisma init
> directly ran ./node_modules/prisma/index

I'm using node.js version 23.11 and this method works
. /node_modules/prisma/build/index.js init

**Comment by AngeloCodeHub** [comment]
> Solution:
> instead if npx Prisma init
> directly ran ./node_modules/prisma/index

I'm using node.js version 23.11 and this method works
. /node_modules/prisma/build/index.js init

**Comment by anuj-pal27** [comment]
@karthik-nair-20 same error while running npx prisma init how to overcome this problem??

**Comment by JATIN-RAGHAV** [comment]
@karthik-nair-20  Yup please tell how you worked your way around the issue.

**Comment by Abir191197** [comment]
@karthik-nair-20  same problem how to solve?

**Comment by YNeKIT** [comment]
> @karthik-nair-20 same problem how to solve?

I downgraded node to version v18.20.4, and it works.

**Comment by newarifrh** [comment]
runs smoothly if using version 22 LTS

**Comment by aqrln** [comment]
Hey everyone, we're aware of the problem on Node.js 23 and will ship a fix for it later. For now you can switch to Node.js 22 LTS to avoid the problem.

Note that as per https://www.prisma.io/docs/orm/reference/system-requirements, we only officially support Node.js LTS releases, and there are no guarantees about running Prisma on the latest Current releases.

I'm going to close this issue as a duplicate of https://github.com/prisma/prisma/issues/25463.

**Comment by aqrln** [comment]
@karthik-nair-20 

> I read some one mentioned downgrade node version and it would work, BUT IT HAS NOT mate/
> I have checked with v20.18.0, v18.20.0 all give the same error
> 
> Solution:
> instead if npx Prisma init
> directly ran ./node_modules/prisma/index

This sounds like the npx you have in `PATH` was not affected by your Node.js version switch. If you run `which npx`, you'll probably see it either pointing at the location of npm bundled with Node.js 23, or perhaps a version installed with your operating system package manager. Hard to tell without knowing how you install and manage Node.js version.

**Comment by sharunkumar** [comment]
When via bunx, the following works:

`bunx --bun prisma init --datasource-provider sqlite`

**Comment by amankrsingh2001** [comment]
I got the same error and this is  how I solved this :-

Step 1 :- Install nvm in the root directory (You will get the command to install nvm in your root directory from here https://codedamn.com/news/nodejs/nvm-installation-setup-guide )
Step 2 :- Change the node version to 20  using (nvm install v20.18.0) in your project directory

and this worked for me.

**Comment by Nikhil79922** [comment]
Here’s the corrected version:

I encountered the same error and solved it as follows:

Step 1: Install nvm in the root directory. You can find the command to install nvm in your root directory 
commands : 
->.   brew install nvm
->.   export NVM_DIR="$HOME/.nvm"
->.   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
->.   mkdir ~/.nvm
->.   export NVM_DIR=~/.nvm
->.   source $(brew --prefix nvm)/nvm.sh
->.   source your_profile_file (.zprofile, .bashrc, .bash_profile, .profile or .zshrc)
->.   nvm ls-remote

Last command ->.  nvm install v20.18.0

Step 2: Now hit the command " npx prisma init"

This solution worked for me!

**Comment by petermazzocco** [comment]
Ran into this same error using bun

`bunx prisma init` returns an error and `bunx --bun prisma init --datasource-provider` doesn't return anything

**Comment by petermazzocco** [comment]
However can confirm downgrading to v20 of node works!

**Comment by devchospre001** [comment]
I can confirm that downgrading node version to v20.18.0 works.

**Comment by ShadowZone** [comment]
It also worked for me by downgrading to v22.12.0.

**Comment by d-zucho** [comment]
Can also confirm that downgrading to **V22.12.0 worked for me.**

**Comment by lucasfcoelho1** [comment]
I can confirm that downgrading node version to v20.11.0 (LTS) works.

**Comment by Mallik-10** [comment]
Why the heck does this bug exist still exist in 2026 i am using it in node v24.12.0
