### ISSUE TITLE
npx prisma generate 403 Forbidden

### ISSUE THREAD

**Issue by theFreedomBanana** [prisma/prisma#25649]
### Bug description

Similar to #23147 and #23667 

Got this error: Failed to fetch sha256 checksum at https://binaries.prisma.sh/all_commits/4bc8b6e1b66cb932731fb1bdbbc550d1e010de81/linux-musl-openssl-3.0.x/migration-engine.sha256. 403 Forbidden.
I have no error locally, only in production. I believe the company is using a firewall and I can't do nothing about it. I can download the file manually though.
Trying to bypass the fetch error using PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1 I get the following error: Forbidden https://binaries.prisma.sh/all_commits/4bc8b6e1b66cb932731fb1bdbbc550d1e010de81/linux-musl-openssl-3.0.x/libquery_engine.so.node.gz

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Linux
- Database: PostgreSQL
- Node.js version: 14 alpine

### Prisma Version

4.15.0

**Comment by MahmoudiBenjamin** [comment]
It was indeed the company's firewall. Seeing it with the support team it is now settle. Sorry for bothering
