### ISSUE TITLE
Debug/info output in Prisma 2.0.0-beta.6

### ISSUE THREAD

**Issue by zapbr** [prisma/prisma#2565]
## Bug description
Every command outputs a debug/info

```
.
.
.
822 ● nexus:server listening  --  url: 'http://localhost:4000/'
  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: '...',
  prisma-client     debug: false,
  prisma-client     datamodelPath: '...',
  prisma-client     prismaPath: undefined,
  prisma-client     generator: {
  prisma-client       name: 'client',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: '.../node_modules/@prisma/client',
  prisma-client       binaryTargets: [Array],
  prisma-client       config: {}
  prisma-client     },
  prisma-client     showColors: false,
  prisma-client     logLevel: undefined,
  prisma-client     logQueries: undefined,
  prisma-client     flags: [],
  prisma-client     clientVersion: '2.0.0-beta.6'
  prisma-client   }
.
.
.
```

## How to reproduce
1. Update the Prisma to 2.0.0-beta.6
2. Run, happens on the start-up and in every command.

## Expected behavior
Some way to disable or disabled by default and some way to enable if it is desired.
It not happens on Prisma to 2.0.0-beta.4

## Prisma information
1. Prisma 2.0.0-beta.6

## Environment & setup
- OS: Mac OS
- Database: MySQL
- Prisma version: Prisma 2.0.0-beta.6
- Node.js version: v12.16.1

**Comment by pantharshit00** [comment]
@zapbr I am unable to reproduce this in the latest version. Also, it looks like that you are using nexus. Can you please make sure that you are on the latest version of nexus? 

If you can still reproduce this, please share your code inside of a git repository

**Comment by zapbr** [comment]
@pantharshit00 I doubled checked the version of nexus, and this is the last stable (0.22.0)

Im using the Nexus server (https://github.com/graphql-nexus/nexus), and to reproduce this, you have to force the usage of this last version on the package.json 

```
"resolutions": {
   "@prisma/client": "^2.0.0-beta.6",
   "@prisma/sdk": "^2.0.0-beta.6",
   "@prisma/cli": "^2.0.0-beta.6"
},
```

**Comment by pantharshit00** [comment]
Looks like a nexus bug then, can you please open an issue about this here: https://github.com/graphql-nexus/nexus

I cannot transfer issue to another organization so please create a new one there as this will be tackled by them.

**Comment by janpio** [comment]
Happy to open this again if we get more information.
