### ISSUE TITLE
New raw functions not exported from @prisma/client

### ISSUE THREAD

**Issue by alexvilchis** [prisma/prisma#2566]
## Bug description
I updated to beta.6 and tried to use `sql` and `join` tags. They, however, don't seem to be exported:
<img width="707" alt="Screen Shot 2020-05-26 at 14 23 47" src="https://user-images.githubusercontent.com/29064411/82941912-cfc7b200-9f5c-11ea-9b59-e4e5aa5c4574.png">

## Environment & setup
- OS: MacOS
- Database: MySQL
- Prisma version: beta.6
- Node.js version: 12.16

**Comment by Sytten** [comment]
A couple of questions:
1. Did you also upgrade the cli when you updated the client?
2. Did you regenerate the client?
Honestly it should work... You can view the diff of the export here: https://github.com/prisma/prisma/pull/2311/files#diff-65510f7215f727807c5679ea0d99d99f

**Comment by alexvilchis** [comment]
Hmm, I updated my dependencies with `npm i --save-dev @prisma/client@latest @prisma/cli@latest` and regenerated the client too 😐

**Comment by alexvilchis** [comment]
This is only a problem when I compile the code, I can use `ts-node-dev` fine.

**Comment by alexvilchis** [comment]
When I open the index.d.ts file inside node_modules I can even see that the utilities are not used:

<img width="758" alt="Screen Shot 2020-05-26 at 19 08 51" src="https://user-images.githubusercontent.com/29064411/82962012-93a84780-9f84-11ea-86ca-3402533b5935.png">

**Comment by GrzegorzWidla** [comment]
As @alexvilchis said: `sql`, `empty`, `join` and `raw` are imported to `node_modules/.prisma/client/index.d.ts` definitions file but not exported.

Clean installs of both `@prisma/client@2.0.0-beta.6` and `@prisma/cli@2.0.0-beta.6` and `npx prisma generate` ran afterwards.

**Comment by Sytten** [comment]
Confirmed, the code is missing here for TS: https://github.com/prisma/prisma/blob/master/src/packages/client/src/generation/TSClient.ts#L123
Most likely a bad merge.

**Comment by timsuchanek** [comment]
Thanks for reporting! We'll look into it

**Comment by pantharshit00** [comment]
I can also confirm the issue

**Comment by Jolg42** [comment]
@timsuchanek needs to fix something here before we can close it 👍
