### ISSUE TITLE
adapter-pg does not work with cockroach db

### ISSUE THREAD

**Issue by adamjuhasz** [prisma/prisma#25691]
### Bug description

When trying to use the driver adapters with CockroachDB we are getting the issue `PrismaClientInitializationError: The Driver Adapter `@prisma/adapter-pg`, based on `postgres`, is not compatible with the provider `cockroachdb` specified in the Prisma schema.`

### How to reproduce

Set the provider to cockroaches

### Prisma information

```
datasource db {
  provider = "cockroachdb"
}
````

### Environment & setup

- Database: CockroachDB

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.22.0
@prisma/client          : 5.22.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.6.0
Query Engine (Node-API) : libquery-engine 605197351a3c8bdd595af2d2a9bc3025bca48ea2 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 605197351a3c8bdd595af2d2a9bc3025bca48ea2 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.22.0-44.605197351a3c8bdd595af2d2a9bc3025bca48ea2
Default Engines Hash    : 605197351a3c8bdd595af2d2a9bc3025bca48ea2
Studio                  : 0.503.0
Preview Features        : metrics, multiSchema, nativeDistinct, tracing, views, prismaSchemaFolder, omitApi
```

**Comment by adamjuhasz** [comment]
I assume this line in the adapter is causing the issue https://github.com/prisma/prisma/blob/a460a746801424e22bea5ade8553ba7b39264e1c/packages/adapter-pg/src/pg.ts#L30

**Comment by jkomyno** [comment]
Hi @adamjuhasz, this is as intended. Despite popular marketing, CockroachDB is not fully compatible with Postgres (which we learnt the hard way before releasing `provider = "cockroachdb"` support.

So we're not currently planning on enabling `@prisma/adapter-pg` for CockroachDB.
We're however open to have someone maintaining a third-party CockroachDB-specific Prisma adapter, kinda like https://github.com/tidbcloud/prisma-adapter is doing for TiDB.
 
Thanks for your understanding.
