### ISSUE TITLE
Error in Schema engine.

### ISSUE THREAD

**Issue by mmcc007** [prisma/prisma#25694]
### Bug description

npx prisma migrate dev --name remove_vector_namespace_unique

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "accelerate.prisma-data.net"

Oops, an unexpected error occurred!
Error in Schema engine.
Reason: [/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ws_stream_tungstenite-0.14.0/src/tung_websocket.rs:540:13] internal error: entered unreachable code: protocol error from tungstenite on send is a bug in ws_stream_tungstenite, please report at http://github.com/najamelan/ws_stream_tungstenite/issues. The error from tungstenite is Sending after closing is not allowed

Please help us improve Prisma by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry

✔ Submit error report › Yes
Submitting...

We successfully received the error report id: 15944

Thanks a lot for your help! 🙏

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by aqrln** [comment]
Hey @mmcc007, thanks for opening the issue. Could you please provide the information required by the issue template so we can investigate? Thank you!

**Comment by nurul3101** [comment]
Hello @mmcc007 👋 

I assume you ran into this issue while trying to run migration on a Prisma Postgres database, correct?

Considering that this repository is for Prisma ORM and not for our commercial offerings.
Do you mind reaching out on support@prisma.io with the email with which you signed up on [Prisma Console](https://console.prisma.io/)?
This would allow me to get details about your project environments and make debugging simple.

**Comment by nurul3101** [comment]
This issue is not related to Prisma ORM but rather pertains to Prisma Postgres. Since this repository is dedicated solely to Prisma ORM-related issues, I’ll be closing it.

Please reach out to us on support@prisma.io and I'll be more than happy to debug this. 🙏

**Comment by tylerhogarth** [comment]
@mmcc007 I wanted to let you know that the team responsible for Prisma Postgres is implementing a retry to make this experience better, you can find more information [here](https://github.com/prisma/prisma/issues/25543#issuecomment-2580187147). Thanks for raising this!
