### ISSUE TITLE
Prisma 6.0.0 client with commonjs crashes on Next.js

### ISSUE THREAD

**Issue by semoal** [prisma/prisma#25761]
### Bug description

After upgrading to 6.0.0, our Next.js with Prisma generated into a custom output folder crashes on dev mode.

The issue is caused by this pull-request : #25734 , Next.js talks about this error here: https://github.com/vercel/next.js/issues/35110#issuecomment-2016567633

<img width="996" alt="Screenshot 2024-12-01 at 16 36 09" src="https://github.com/user-attachments/assets/8450a130-dce3-4f1f-9781-23d089d68480">

The error is caused when we're using `transpilePackages` in `next.config.js` looks like it's also transpiling the prisma client to esm or something like that.

I've checked and removing `type: commonjs` works fine, so not sure how to fix it. 

### Expected behavior

To not crash. 

### Prisma information

Prisma version: 6.0.0, with any prisma schema.

### Environment & setup

- OS:  Mac
- Database:  Any
- Node.js version:  22.11.0

### Prisma Version

```
6.0.0
```

**Comment by aqrln** [comment]
Hey @semoal, thanks for opening the issue, we've just published a patch release (`6.0.1`) to fix this.

**Comment by semoal** [comment]
> Hey @semoal, thanks for opening the issue, we've just published a patch release (`6.0.1`) to fix this.

Just tested and now is working smoothly as usual :) Thanks for the quick release!
