### ISSUE TITLE
Parameter for `prisma init` to supply connection string to be used in `datasource`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2577]
## Problem
Right now we need to tell people to use `prisma init` and then open and edit `prisma/.env` to add their connection string: https://twitter.com/nikolasburk/status/1265617985986801664
![image](https://user-images.githubusercontent.com/183673/83031601-0c66dc80-a035-11ea-9482-4138d4749f1c.png)

This is cumbersome, especially if you just want people to get to a working Introspection as quickly as possible.

## Suggested solution
We could add a param `--database` (or `--connection-string` or `--url` or similar) that takes and validates the connection string, extracts the provider (`mysql://` => `mysql` etc) and persists both in the newly generated `schema.prisma` and `.env` automatically.

## Alternatives
We keep the manual workflow that tells people to edit the file.

**Comment by timsuchanek** [comment]
This is now implemented with `--url`.
