### ISSUE TITLE
Extended client return type

### ISSUE THREAD

**Issue by DreamwareDevelopment** [prisma/prisma#25797]
### Bug description

[Docs](https://github.com/prisma/docs/blob/main/content/200-orm/200-prisma-client/300-client-extensions/index.mdx) say at the bottom that nested reads or writes don't work with the extended client. Can you A: remove this limitation and support nesting. Or B: fix the return type of $extends to remove the nested read/write capability in the type signature?

### How to reproduce

```
export type ExtendedPrismaClient = Awaited<ReturnType<typeof newPrismaClient>>

export async function newPrismaClient() {
  const datasourceUrl = process.env.POSTGRES_PRISMA_URL
  if (!datasourceUrl) {
    throw new Error('POSTGRES_PRISMA_URL is not set')
  }
  const client = new PrismaClient({ datasourceUrl })
  const extendedClient = client.$extends(getSupabaseRLSExtension(client))
  await extendedClient.$connect()
  return extendedClient
}
```
ExtendedPrismaClient type allows for nested reads/writes

### Prisma information

Not needed

### Environment & setup

All

### Prisma Version

```
5.22
```

**Comment by ludralph** [comment]
HI @DreamwareDevelopment 

Unfortunately, I don’t think we have any update on removing the limitation or fixing the return type of `$extends` to remove the nested read/write capability in the type signature. If you want to infer the return type of an extended prisma client then you can do:
```js
const extendedPrismaClient = new PrismaClient().$extends({
  /** extension */
})

type ExtendedPrismaClient = typeof extendedPrismaClient
```

We’ve recently revived our public roadmap, which we will update every three months with the major issues we plan to address. Here’s our first installment: https://github.com/prisma/prisma/issues/25794

We also recently put out the ORM Manifesto which goes into depth on how we want to approach the governance of the ORM. Here’s a link to that: https://github.com/prisma/prisma/discussions/25772

We’re going to continue addressing issues, primarily focusing on those with the most  reactions as it’s the clearest way we have to community need. 

I know that’s probably not the answer you want, but does that make sense? Any other questions I can help answer?

**Comment by DreamwareDevelopment** [comment]
I don't really understand _why_ the nested reads/writes break with the extended client. I wouldn't expect adding extensions to break the underlying client logic regarding nested reads/writes. And from the sound of it the team doesn't plan to fix it unless there's a lot of people encountering this issue.

**Comment by aqrln** [comment]
I think you are misreading what the docs say @DreamwareDevelopment. Nested reads and writes are absolutely supported with extended client, it is a fundamental functionality of Prisma, and hence they are present in types: there's no reason to remove them because they work, and they are obviously supposed to work.

If you know of any case where they break, then please open an issue with a reproduction, that would be a pretty bad bug.

What the part of the docs that you are quoting is saying is that you can't override the behaviour of nested queries using client extensions.

**Comment by DreamwareDevelopment** [comment]
Agreed that it's core functionality that shouldn't break. I haven't hit this recently because I stopped doing RLS w/ Supabase. Will come back here if I encounter this issue again later when I revisit RLS. Focused on shipping, not security right now.
