### ISSUE TITLE
DateTime Column with `@default(now())` is not using database level time when insert query is generated.

### ISSUE THREAD

**Issue by JackCme** [prisma/prisma#25808]
### Bug description

When I check the query produced by the prisma client when creating data, I expected that the column which its default is set to `@default(now())` does not appear in the `INSERT INTO` column queries so that it could use the columns default value, which is actually the database level time.
But it seems that even if `@default(now())` is set to that column, the query generates the time from the Prisma Engine level and includes it in the INSERT INTO statement.

### How to reproduce

1. 
This is a simple schema that I use to reproduce:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Jack {
  id        String   @id @default(uuid()) @db.Uuid()
  name      String   @db.VarChar()
  createdAt DateTime @default(now())
}
```

2. Create a data using the generated client
```ts
await prisma.jack.create({
  data: {
    name: 'jack'
  }
});

// This is the produced query event from the above create statement:
{
  timestamp: 2024-12-06T04:22:08.874Z,
  query: 'INSERT INTO "public"."Jack" ("id","name","createdAt") VALUES ($1,$2,$3) RETURNING "public"."Jack"."id", "public"."Jack"."name", "public"."Jack"."createdAt"',
  params: '["fb3685f6-5a56-4c9a-b814-617b58fe28c8","jack","2024-12-06 04:22:08.866 UTC"]',
  duration: 6,
  target: 'quaint::connector::metrics'
}
```

### Expected behavior

I expected that `createdAt` will not be included in the INSERT INTO statement because 
1. column is explicitly omitted from the `prisma.jack.create` statement's data
2. it has a default value in the schema

expected query:
```json
{
  timestamp: 2024-12-06T04:22:08.874Z,
  query: 'INSERT INTO "public"."Jack" ("id","name") VALUES ($1,$2) RETURNING "public"."Jack"."id", "public"."Jack"."name"',
  params: '["fb3685f6-5a56-4c9a-b814-617b58fe28c8","jack"]',
  duration: 6,
  target: 'quaint::connector::metrics'
}

```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS, Ubuntu
- Database: PostgreSQL
- Node.js version: 20.15.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 6.0.1
@prisma/client          : 6.0.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.15.0
Query Engine (Node-API) : libquery-engine 5dbef10bdbfb579e07d35cc85fb1518d357cb99e (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 5dbef10bdbfb579e07d35cc85fb1518d357cb99e (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.23.0-27.5dbef10bdbfb579e07d35cc85fb1518d357cb99e
Default Engines Hash    : 5dbef10bdbfb579e07d35cc85fb1518d357cb99e
Studio                  : 0.503.0

```

**Comment by jkomyno** [comment]
Hi @JackCme, you can use `@default(dbgenerated("NOW()"))` so that Prisma matches the behavior you'd expect.

Btw, I'm closing this issue as a duplicate in favor of https://github.com/prisma/prisma/issues/1831.
Can I please ask you the use case? What is the current `@default(now())` behavior preventing you to do? Thanks
