### ISSUE TITLE
Error reports do not output error message, but only submit it

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2581]
See report in https://github.com/prisma/prisma/issues/2574

**Comment by pantharshit00** [comment]
Hm, I guess you can get the panic trace by doing `export DEBUG=*`. We need a reproduction here though. Waiting on #2574

**Comment by janpio** [comment]
Is it maybe a problem on _any_ error that triggers the error reporting that the error is not actually output any more? #typescript should be able to give you a way to trigger _any_ error.

**Comment by pantharshit00** [comment]
@janpio Turns out #2574 was not specific to Prisma. Do we want to keep this open?

**Comment by janpio** [comment]
Yes, as error reports hiding error messages would be bad and a fundamental problem that needs to be understood and fixed.

**Comment by yantakus** [comment]
I've found this doc regarding debugging: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/debugging 

But I have no idea where to place this `export DEBUG=*` line.

It says that it should be an environment variable, so tried adding `DEBUG=*` to `prisma/.env` with no effect. Could you please assist?

**Comment by pantharshit00** [comment]
@yantakus You can execute the command like so to enable debug mode:
```
DEBUG=* node index.js
```

If you want your every command to run in debug mode, you can set the debug environment variable for your current shell session. `export` command does that. 
```
export DEBUG=*
node index.js
primsa studio --experimental
```


Note that these commands are specific to POSIX like systems.

On Windows you can do the something like this:
```
set DEBUG "*"
node index.js
```
