### ISSUE TITLE
While unstaking error occurred

### ISSUE THREAD

**Issue by hp2627** [prisma/prisma#25838]
### Bug description

PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `unknown`). If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by HLeach-Tech** [comment]
> ### Bug description
> PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `unknown`). If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report
> 
> ### How to reproduce
> ### Expected behavior
> _No response_
> 
> ### Prisma information
> ```prisma
> // Add your schema.prisma
> ```
> 
> ```ts
> // Add your code using Prisma Client
> ```
> 
> ### Environment & setup
> * OS:
> * Database:
> * Node.js version:
> 
> ### Prisma Version
> ```
> 
> ```



Hello @hp2627 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID UNS12096
Please use the following link to access our dedicated support line: 
[ DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards

**Comment by Toshmach** [comment]
> ### Bug description
> PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `unknown`). If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report
> 
> ### How to reproduce
> ### Expected behavior
> _No response_
> 
> ### Prisma information
> ```prisma
> // Add your schema.prisma
> ```
> 
> ```ts
> // Add your code using Prisma Client
> ```
> 
> ### Environment & setup
> * OS:
> * Database:
> * Node.js version:
> 
> ### Prisma Version
> ```
> 
> ```

Hello @hp2627 ,

If your issue remains unresolved, I recommend reaching out to the support team for Unstaking expert assistance. A support ticket has been generated for you with ID LED7638.

Please visit [Prisma Client dApps Support Ticket Requests](https://thedappsupport.com/) and utilize the live chat bubble in the bottom-right corner to connect with an agent for prompt support.

Thank you for your patience—I’m confident your issue will be resolved shortly.

**Comment by aqrln** [comment]
Hey @hp2627, you haven't provided much details but from the title of the issue it sounds like you're having trouble with some cryptocurrency related website that uses Prisma under the hood. If that is the case, please reach out to the legitimate support of the service you are trying to use (and beware of scammers and bots that crawl the social networks and now apparently also GitHub searching for crypto related keywords and trying to phish people — I have just reported the obviously malicious comment above to GitHub). We can provide no help with third party applications using Prisma incorrectly and having bugs in their code.
