### ISSUE TITLE
Use of "i.e." instead of "e.g." in migration_lock.toml

### ISSUE THREAD

**Issue by tatounee** [prisma/prisma#25855]
### Bug description

In the migration_lock.toml file (default located in prisma/migrations/migration_lock.toml) is written :
```
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
...
```
"i.e." meaning Id est (that is) is wrongly used instead of "e.g." meaning Exempli gratia (for example).

### How to reproduce

1. Create a new prisma project (or use on already created)
2. Go to prisma/migrations/migration_lock.toml
3. Read the line 2

### Expected behavior

It should be written :
```
# It should be added in your version-control system (e.g. Git)
```

### Prisma information

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Foo {
  id Int @id
}
```

### Environment & setup

- OS: All
- Database: All
- Node.js version: All

### Prisma Version

```
6.0.1
```

**Comment by Arlen22** [comment]
"in effect" (i.e) vs "for example" (e.g) is how I always think of it. However, if there is only one version control cli in existence, the two are interchangable, since that is in effect the only option. 

Is there any other version control system besides Git?

**Comment by sicin** [comment]
> "in effect" (i.e) vs "for example" (e.g) is how I always think of it. However, if there is only one version control cli in existence, the two are interchangable, since that is in effect the only option.
> 
> Is there any other version control system besides Git?

"i.e." means "that is", not "in effect". There are other version control systems, although not used often at all, especially in non-compiled languages world. Still, "i.e." is completely fine here, not worth opening an issue imo.
