### ISSUE TITLE
Tracing error in 6.1.0

### ISSUE THREAD

**Issue by khalilsarwari** [prisma/prisma#25885]
### Bug description

There seems to be an intermittent tracing error in latest prisma version

### How to reproduce

1.) Use prisma version 6.1.0
2.) Get this error

```
TypeError: this.getGlobalTracingHelper(...).dispatchEngineSpans is not a function
    at ho.dispatchEngineSpans (/web/node_modules/@prisma/client/runtime/library.js:121:1715)
    at Object.query (/web/node_modules/@prisma/client/runtime/library.js:111:11492)
    at async _r.request (/web/node_modules/@prisma/client/runtime/library.js:112:3726)
```

### Expected behavior

Should not have any type error

### Prisma information

N/A

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: 22.10

### Prisma Version

```
prisma                  : 6.1.0
@prisma/client          : 6.1.0
Computed binaryTarget   : linux-arm64-openssl-1.1.x
Operating System        : linux
Architecture            : arm64
Node.js                 : v22.10.0
Query Engine (Node-API) : libquery-engine 11f085a2012c0f4778414c8db2651556ee0ef959 (at node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 11f085a2012c0f4778414c8db2651556ee0ef959 (at node_modules/@prisma/engines/schema-engine-linux-arm64-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 6.1.0-21.11f085a2012c0f4778414c8db2651556ee0ef959
Default Engines Hash    : 11f085a2012c0f4778414c8db2651556ee0ef959
Studio                  : 0.503.0
Preview Features        : fullTextSearchPostgres, tracing, views, relationJoins, omitApi
```

**Comment by SamuelSmeys** [comment]
I am experiencing the same issue. Are you using observability tools that have a prisma integration? I believe this is due to those observability tools not yet supporting the latest version of the tracing feature. 

We had this issue yesterday with Sentry, when Sentry tracing was turned off it would work fine, when turned on it would crash the prisma client. If this is indeed due to observability tools, I recommend downgrading back to 6.0.1 and waiting for your observability provider to release a version that supports this.

**Comment by khalilsarwari** [comment]
Yes, you are correct this is actually due to a clash with Sentry; I believe we just have to wait as you mentioned (as far as I cal tell):
https://github.com/getsentry/sentry-javascript/pull/14624

**Comment by SunWuyuan** [comment]
Obviously, this issue still exists. I used 6.1.0 without Sentry or other observability tools, but still encountered this error

**Comment by uhrohraggy** [comment]
As a +1, I'm getting this error when using Prisma's Optimize with v6.1.0. In case it's helpful, my `schema.prisma`:

```
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native", "debian-openssl-3.0.x", "linux-arm64-openssl-1.1.x", "rhel-openssl-3.0.x"]
  previewFeatures = ["tracing"]
}

datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("DATABASE_SHADOW_URL")
}
```

**Comment by mdesousa** [comment]
Just created #25978 since we also ran into this issue and it's unrelated to sentry

**Comment by carchrae** [comment]
> Just created #25978 since we also ran into this issue and it's unrelated to sentry

quite interesting that you found this fixed it:  

> We noticed that installing the @prisma/instrumentation package solves this problem.

**Comment by mdesousa** [comment]
@carchrae unfortunately that fix was a false positive... i've edited the original message since we can't get 6.1.0 to work with our monitoring platform. Had to roll back to 6.0.1.

**Comment by halillusion** [comment]
For those still experiencing the issue, the following definition will likely fix it.

```ts
Sentry.init({
  ...
  skipOpenTelemetrySetup: true,
})
```

**Comment by dhedegaard-digisense** [comment]
Please see the release notes for sentry 8.51, which is the official sentry solution for handling instrumentation, until the next major release of sentry:

https://github.com/getsentry/sentry-javascript/releases/tag/8.51.0

**Comment by blasterbug** [comment]
Using Sentry 8.52 and the instrumentation is broken

**Comment by aqrln** [comment]
@blasterbug please read the release notes via the link in the comment above.

**Comment by blasterbug** [comment]
@aqrln  I certainly did and followed the instructions.
