### ISSUE TITLE
Output prepared GitHub issue creation link after reporting error (CLI)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2588]
When we prompt the user to report an error, we show them the error ID and tell them to create an issue on GitHub. We could also just create a handy link for them to click in these cases that already prefills some information as we do after Prisma Client errors.

**Comment by williamluke4** [comment]
Would it be worth searching GitHub for existing issues with the same error before you are prompted to create a new issue?

**Comment by williamluke4** [comment]
Essentially check the similarity of the Rust and JS Stacktrace against existing reports. Then display the most similar issues to the user, allowing them to decide on whether to create a new issue or add to an existing

**Comment by janpio** [comment]
That would be an interesting, new feature yes. (An open source project where I contribute, fastlane, actually does this automatically on all CLI errors. Works rather well. But Prisma has the optional error reporting, which is slightly different) Would need to be verified if it creates good results. Best open a new issue about this and flesh it out a bit.

**Comment by williamluke4** [comment]
Helper Function Allows you insert directely in to the body of an issue, opposed to using a template
```ts
interface Options {
  body?: string;
  title?: string;
  labels?: string[];
  template?: string;
  milestone?: string;
  assignee?: string;
  projects?: string[];
}

function generateGithubIssueUrl(user: string, repo: string, options: Options) {
  const repoUrl = `https://github.com/${user}/${repo}`;
  const url = new URL(`${repoUrl}/issues/new`);

  const types: (keyof Options)[] = [
    "body",
    "title",
    "labels",
    "template",
    "milestone",
    "assignee",
    "projects",
  ];

  for (const type of types) {
    let value = options[type];
    if (value === undefined) {
      continue;
    }

    if (type === "labels" || type === "projects") {
      value = (value as string[]).join(",");
    }

    url.searchParams.set(type, value as string);
  }
  return url.toString();
}
```

**Comment by williamluke4** [comment]
Ideally, I would like to prompt the user if they would like to generate a new issue. If the user agrees then the generated URL is automatically opened using [open](https://www.npmjs.com/package/open).

The reason I propose this is that the generated URL is pretty large and unsightly. See below
 [Test the generated URL](https://github.com/prisma/prisma/issues/new?body=%0A%3C%21--+%0AThanks+for+helping+us+improve+Prisma%21+%F0%9F%99%8F+Please+follow+the+sections+in+the+template+and+provide+as+much+information+as+possible+about+your+problem%2C+e.g.+by+setting+the+%60DEBUG%3D%22*%22%60+environment+variable+and+enabling+additional+logging+output+in+Prisma+Client.%0A%0ALearn+more+about+writing+proper+bug+reports+here%3A+https%3A%2F%2Fpris.ly%2Fd%2Fbug-reports%0A--%3E%0A%0A%23%23+Bug+description%0A%0A%3C%21--+A+clear+and+concise+description+of+what+the+bug+is.+--%3E%0A%0A%23%23+How+to+reproduce%0A%0A%3C%21--%0ASteps+to+reproduce+the+behavior%3A%0A1.+Go+to+%27...%27%0A2.+Change+%27....%27%0A3.+Run+%27....%27%0A4.+See+error%0A--%3E%0A%0A%23%23+Expected+behavior%0A%0A%3C%21--+A+clear+and+concise+description+of+what+you+expected+to+happen.+--%3E%0A%0A%23%23+Prisma+information%0A%0A%3C%21--+Your+Prisma+schema%2C+Prisma+Client+queries%2C+...%0ADo+not+include+your+database+credentials+when+sharing+your+Prisma+schema%21+--%3E%0A%0A%23%23+Environment+%26+setup%0A%0A%3C%21--+In+which+environment+does+the+problem+occur+--%3E%0A%0A-+OS%3A+Windows%0A-+Database%3A+Postgres%0A-+Node.js+version%3A+12.6.2%0A-+Prisma+Information%3A+%0A%60%60%60%0A%0A++++%40prisma%2Fcli++++++++++%3A+2.6.2%0A++++Current+platform+++++%3A+debian-openssl-1.1.x%0A++++Query+Engine+++++++++%3A+query-engine+6a8054bb549e4cc23f157b0010cb2e95cb2637fb+%28at+node_modules%2F%40prisma%2Fcli%2Fquery-engine-debian-openssl-1.1.x%29%0A++++Migration+Engine+++++%3A+migration-engine-cli+6a8054bb549e4cc23f157b0010cb2e95cb2637fb+%28at+node_modules%2F%40prisma%2Fcli%2Fmigration-engine-debian-openssl-1.1.x%29%0A++++Introspection+Engine+%3A+introspection-core+6a8054bb549e4cc23f157b0010cb2e95cb2637fb+%28at+node_modules%2F%40prisma%2Fcli%2Fintrospection-engine-debian-openssl-1.1.x%29%0A++++Format+Binary++++++++%3A+prisma-fmt+6a8054bb549e4cc23f157b0010cb2e95cb2637fb+%28at+node_modules%2F%40prisma%2Fcli%2Fprisma-fmt-debian-openssl-1.1.x%29%0A++++Studio+++++++++++++++%3A+0.272.0%0A++++%0A%60%60%60%0A&title=Bug+Report+Test)
<details>
  <summary>Click to expand!</summary>
 
  `
https://github.com/prisma/prisma/issues/new?body=%0A%3C%21--+%0AThanks+for+helping+us+improve+Prisma%21+%F0%9F%99%8F+Please+follow+the+sections+in+the+template+and+provide+as+much+information+as+possible+about+your+problem%2C+e.g.+by+setting+the+%60DEBUG%3D%22*%22%60+environment+variable+and+enabling+additional+logging+output+in+Prisma+Client.%0A%0ALearn+more+about+writing+proper+bug+reports+here%3A+https%3A%2F%2Fpris.ly%2Fd%2Fbug-reports%0A--%3E%0A%0A%23%23+Bug+description%0A%0A%3C%21--+A+clear+and+concise+description+of+what+the+bug+is.+--%3E%0A%0A%23%23+How+to+reproduce%0A%0A%3C%21--%0ASteps+to+reproduce+the+behavior%3A%0A1.+Go+to+%27...%27%0A2.+Change+%27....%27%0A3.+Run+%27....%27%0A4.+See+error%0A--%3E%0A%0A%23%23+Expected+behavior%0A%0A%3C%21--+A+clear+and+concise+description+of+what+you+expected+to+happen.+--%3E%0A%0A%23%23+Prisma+information%0A%0A%3C%21--+Your+Prisma+schema%2C+Prisma+Client+queries%2C+...%0ADo+not+include+your+database+credentials+when+sharing+your+Prisma+schema%21+--%3E%0A%0A%23%23+Environment+%26+setup%0A%0A%3C%21--+In+which+environment+does+the+problem+occur+--%3E%0A%0A-+OS%3A+Windows%0A-+Database%3A+Postgres%0A-+Node.js+version%3A+12.6.2%0A-+Prisma+Information%3A+%0A%60%60%60%0A%0A++++%40prisma%2Fcli++++++++++%3A+2.6.2%0A++++Current+platform+++++%3A+debian-openssl-1.1.x%0A++++Query+Engine+++++++++%3A+query-engine+6a8054bb549e4cc23f157b0010cb2e95cb2637fb+%28at+node_modules%2F%40prisma%2Fcli%2Fquery-engine-debian-openssl-1.1.x%29%0A++++Migration+Engine+++++%3A+migration-engine-cli+6a8054bb549e4cc23f157b0010cb2e95cb2637fb+%28at+node_modules%2F%40prisma%2Fcli%2Fmigration-engine-debian-openssl-1.1.x%29%0A++++Introspection+Engine+%3A+introspection-core+6a8054bb549e4cc23f157b0010cb2e95cb2637fb+%28at+node_modules%2F%40prisma%2Fcli%2Fintrospection-engine-debian-openssl-1.1.x%29%0A++++Format+Binary++++++++%3A+prisma-fmt+6a8054bb549e4cc23f157b0010cb2e95cb2637fb+%28at+node_modules%2F%40prisma%2Fcli%2Fprisma-fmt-debian-openssl-1.1.x%29%0A++++Studio+++++++++++++++%3A+0.272.0%0A++++%0A%60%60%60%0A&title=Bug+Report+Test
`
</details>

**Comment by janpio** [comment]
> Ideally, I would like to prompt the user if they would like to generate a new issue. If the user agrees then the generated URL is automatically opened using [open](https://www.npmjs.com/package/open).

Sounds like a good idea if this works on all operating systems.

(The other link is output in Prisma Client, so application context. There you can not prompt for anything. But here in the CLI context you can do that.)

**Comment by williamluke4** [comment]
I'll wait for https://github.com/prisma/prisma/issues/3648 to move forward
