### ISSUE TITLE
Error: (0 , KSe.isError) is not a function on prisma init

### ISSUE THREAD

**Issue by SH20RAJ** [prisma/prisma#25909]
### Bug description

shaswatraj@Sh creoyt % prisma init
Error: (0 , KSe.isError) is not a function

### How to reproduce

shaswatraj@Sh creoyt % npx prisma init
Error: (0 , KSe.isError) is not a function
shaswatraj@Sh creoyt % 

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 
v23.5.0

### Prisma Version

```
shaswatraj@Sh creoyt % prisma -v 
prisma                  : 6.1.0
@prisma/client          : 6.1.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v23.5.0
Query Engine (Node-API) : libquery-engine 11f085a2012c0f4778414c8db2651556ee0ef959 (at ../../../../../opt/homebrew/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 11f085a2012c0f4778414c8db2651556ee0ef959 (at ../../../../../opt/homebrew/lib/node_modules/prisma/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 6.1.0-21.11f085a2012c0f4778414c8db2651556ee0ef959
Default Engines Hash    : 11f085a2012c0f4778414c8db2651556ee0ef959
Studio                  : 0.503.0
shaswatraj@Sh creoyt % 
```

**Comment by Olexsandrik** [comment]
I just solved this problem, you need to change the Node version. Try nvm i 22, it worked for me.

**Comment by aqrln** [comment]
Prisma is currently not fully compatible with Node.js 23, please use an even-numbered Node.js LTS (i.e. 18, 20 or 22). We already have an issue about it, so I'll close this one as a duplicate.

**Comment by ahmedkhabar** [comment]
```
nvm install --lts
nvm list
nvm use 22.12.0
```

This is how I solve this issue using Node version manager

**Comment by igo2felipe** [comment]
Como que eu posso resolver esse erro aqui Error: (0 , KSe.isError) is not a function quando eu dou um npx prisma init a versão do Node é 20.17.0 alguém sabe resolver
