### ISSUE TITLE
Configuration to disable update check and message

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#2595]
![image](https://user-images.githubusercontent.com/5013932/83163612-6f3f9d00-a135-11ea-816d-078f46503b14.png)

It should be possible to disable this update check, preferably using an environment variable.

**Comment by janpio** [comment]
Is there a common ENV var naming pattern for this maybe?

I am aware of this very specific example `FASTLANE_SKIP_UPDATE_CHECK`: http://docs.fastlane.tools/advanced/fastlane/#skip-update-check-when-launching-fastlane

**Comment by matthewmueller** [comment]
The easiest would be providing an environment variable that doesn't print out that message. 

This would require a change here: https://github.com/prisma/prisma/blob/54eb47d51181bccc430c3f3ecd30c0b669f999c7/src/packages/cli/src/bin.ts#L194-L205
