### ISSUE TITLE
[Introspection] Defaults set as expressions (as required in MySQL on some column types) not picked up

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2600]
In MySQL this exists:

https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html

> **Handling of Explicit Defaults Prior to MySQL 8.0.13**
> The BLOB, TEXT, GEOMETRY, and JSON data types cannot be assigned a default value.

Fortunately

> **Handling of Explicit Defaults as of MySQL 8.0.13**
> The BLOB, TEXT, GEOMETRY, and JSON data types can be assigned a default value only if the value is written as an expression, even if the expression value is a literal

Unortunately even if you use MySQL >8.0.13 and use a query like this to set the default on the column:

```
alter table CDBreakpoints change xs xs mediumtext not null default('576px');
```

the default will not be picked up by Introspection.

(This causes problems for `prisma-upgrade` which checks if a default is present to give advice how to fix the database and currently only proceeds if it is.)

**Comment by do4gr** [comment]
There are also some cases where we currently take the easy route and specify the default as dbgenerated(). This is not helpful to Migrate though, so I think investing some time into default value recognition would improve migrate and introspection.

**Comment by tomhoule** [comment]
This could be already fixed by `@default(dbgenerated("..."))`. To be confirmed.

**Comment by do4gr** [comment]
I spent some time looking into this. The `db push` direction works, but the `db pull` direction cannot fully work with our current approach.

```
model test {
  id   Int    @id
  test String @db.MediumText @default(dbgenerated("('576px')"))
}
```

The model above will be correctly created in the database and have a working default expression. 

Unfortunately, the content of this expression is not part of the information_schema which `db pull` relies on. It only contains the information that there is a default expression, but not which one. We would need to parse the result of `Show create table` to properly fill the default value. 
```
CREATE TABLE `test` (
  `id` int NOT NULL,
  `test` mediumtext NOT NULL DEFAULT (_utf8mb4'576px'),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

This would be a completely new approach and is therefore currently out of scope. 

We can infer that there is a default though, but the new `dbgenerated("string description")` did not envision a case where we just know that there is a default but not what it's definition is.

We need to think about how to express this case. `dbgenerated()` without string contents is a possibility, although at that point I'd be for using two different concepts. Maybe splitting into `raw("string description")` and `dbgenerated()` without content.
