### ISSUE TITLE
Cannot reset database when seeding with script file

### ISSUE THREAD

**Issue by 2wce** [prisma/prisma#2609]
# Bug Report

**Current behavior**
Passing -r or --reset to the `prisma seed` command will not reset the database if prisma seed uses a script file.
**Reproduction**

1. Use Typescript Advanced boilerplate

2. Make the following changes to prisma.yml
```
seed:
  run: yarn ts-node ./database/seed.ts
```
For any valid seed.ts file, the database is never reset when you run `prisma seed -r`

**Expected behavior?**
Database should be reset before running seed

**Comment by marktani** [comment]
Thanks for bringing this up, @2wce. I will look into a reproduction soon, once https://github.com/graphql-boilerplates/typescript-graphql-server/issues/289 is resolved.

**Comment by marktani** [comment]
Sorry for the delay. This was supposedly fixed here https://github.com/prismagraphql/prisma/pull/2712/files, but I can still reproduce this on `1.13.7`.

**Comment by marktani** [comment]
I can still reproduce this on `1.15-beta-1`.

**Comment by divyenduz** [comment]
I am not able to reproduce this with 

```
divyendusingh [prisma-2609]$ prisma version
prisma/1.19.0-beta.10 (darwin-x64) node-v10.4.0
```
