### ISSUE TITLE
Prisma 2.0.0-beta.7 `npx prisma generate` issue if working directory contains spaces

### ISSUE THREAD

**Issue by maoosi** [prisma/prisma#2612]
Since upgrading to Prisma 2.0.0-beta.7, running `npx prisma generate` fails with the below error:

```bash
Error: Generator at node --max-old-space-size=8096 /Volumes/Macintosh HD - Data/***/node_modules/@prisma/client/generator-build/index.js could not start:

internal/modules/cjs/loader.js:797
    throw err;
    ^
Error: Cannot find module '/Volumes/Macintosh'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

It's working fine when downgrading to 2.0.0-beta.6.

Given the error returned, it seems related to the fact my working directory contains spaces. I've also noticed that the latest release includes a fix for [https://github.com/prisma/prisma/issues/1973](https://github.com/prisma/prisma/issues/1973), so this might be linked?

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
