### ISSUE TITLE
Example for different seeding workflows

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2618]
read https://www.prisma.io/forum/t/example-for-seeding-from-a-js-script/3615?u=nilan for some ideas

**Comment by 2rhop** [comment]
## Hello
I'm starting a new project for automating the seeding on multiples db with **_javascript_** and [knex.js](http://knexjs.org), please have a look at [this ](https://github.com/2rhop/knex-seeder)and let me hear your [**recomends**](https://github.com/2rhop/knex-seeder/issues), thanks

here is a code example:

```javascript
//creating and seeding process
ks.createAndSeed(userTableModel, 10).then(() => {
    //creating the table automatically & seeding ...
    ks.createAndSeed_close(roleTableModel, 10, (table) => { //closes the connection after process
        //creating the table with knex.js fn & and seeding ...
        table.increments(),
            table.string('name'),
            table.string('category'),
            table.timestamps(true, true)
    }).then(()) =>{
        //do something here...
  }
})
```

#### One code to seed them all!
<img src="https://raw.githubusercontent.com/2rhop/knex-seeder/master/assets/logo.png" height=120 /><img src="https://camo.githubusercontent.com/b2c7efaeb746c3fadea6796914a22e8d03bb43c8/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f72656c656173652f3272686f702f6b6e65782d7365656465722f616c6c2e737667" > <img src="https://camo.githubusercontent.com/44e55c99e870e355e1383829f99dc4ec4ff53075/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f6c6963656e73652f3272686f702f6b6e65782d7365656465722e737667" >

**Comment by marktani** [comment]
Thanks for sharing @2rhop, can you elaborate how this is relevant for Prisma? 🙂

**Comment by 2rhop** [comment]
with knex-seeder you can use its api for seeding multiples database, as its based on knex.js, supports many db conn, this is from de knex.js docs

>The primary target environment for Knex is Node.js, you will need to install the knex library, and then install the appropriate database library: pg for PostgreSQL and Amazon Redshift, mysql for MySQL or MariaDB, sqlite3 for SQLite3, or mssql for MSSQL.

I guess that **Prisma** can uses the knex-seeder API for make some seeds into a db or generate some fake data for other purposes

**Comment by jhalborg** [comment]
We have it working with a setup like this:

seed.ts:
```
const db: Prisma = new Prisma({
  secret: process.env.PRISMA_SECRET,
  endpoint: process.env.PRISMA_ENDPOINT, // the endpoint of the Prisma API (value set in `.env`)
});

const seedConfig = {
  numberOfUsers: 200,
  ...
};

const setup = async () => {
  for (let index = 0; index < seedConfig.numberOfUsers; index++) {
    const user = await db.mutation.createUser(
      ...
    );
  }
}

setup();
```

prisma.yml:
```
seed:
  run: yarn ts-node ./database/seed/seed.ts
```

Hope it helps someone
