### ISSUE TITLE
Invalid API schema generated for a specific datamodel

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#2623]
# Bug Report

**Current behavior**
When a service is deployed with a specific datamodel the generated API schema is invalid.

Related issue: https://github.com/graphql-cli/graphql-cli/issues/319

**Reproduction**

https://github.com/divyenduz/graphql-cli-319

**Expected behavior?**
There is an empty `type` generated which should not be generated.

**Comment by terion-name** [comment]
I think this is related #2574

Try to reload Prisma server after deployment — it should work then

**Comment by marktani** [comment]
What do you mean with reloading the Prisma server?

**Comment by terion-name** [comment]
@marktani restart it. in case of kubernetes - recreate the pod

**Comment by FrankSandqvist** [comment]
I get this issue sometimes when I make a type without a scalar field.

Adding one usually works as a workaround. 

Still a bug though...

**Comment by mavilein** [comment]
I have implemented a fix for this in 1.15 which will become available in Beta on August 14th and Stable on August 28th.
