### ISSUE TITLE
"SyntaxError: Unexpected token {" while upgrading Prima to 1.9

### ISSUE THREAD

**Issue by ludovicc** [prisma/prisma#2635]
**Describe the bug**

Error seen while upgrading Prima

**To Reproduce**
1. Upgrade from an older version of Prisma

sudo -H npm install -g --update prisma

2. See error

/usr/bin/prisma -> /usr/lib/node_modules/prisma/dist/index.js

> prisma@1.9.0 postinstall /usr/lib/node_modules/prisma
> prisma init-prisma || echo ""

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Function.promptModule.restoreDefaultPrompts (/usr/lib/node_modules/prisma/node_modules/inquirer/lib/inquirer.js:55:33)
    at Object.inquirer.createPromptModule (/usr/lib/node_modules/prisma/node_modules/inquirer/lib/inquirer.js:65:16)
    at Object.<anonymous> (/usr/lib/node_modules/prisma/node_modules/inquirer/lib/inquirer.js:77:28)

/usr/lib
└─┬ prisma@1.9.0 
  ├─┬ prisma-cli-core@1.0.46 
  │ ├─┬ download-github-repo@0.1.4
  │ │ └─┬ download@6.2.5
  │ │   ├─┬ decompress@4.2.0
  │ │   │ ├─┬ decompress-tarbz2@4.1.1
  │ │   │ │ └─┬ unbzip2-stream@1.2.5
  │ │   │ │   └─┬ buffer@3.6.0
  │ │   │ │     └── ieee754@1.1.12 
  │ │   │ └─┬ decompress-unzip@4.0.1
  │ │   │   └─┬ yauzl@2.9.2 
  │ │   │     └── fd-slicer@1.1.0 
  │ │   ├─┬ ext-name@5.0.0
  │ │   │ └─┬ ext-list@2.2.2
  │ │   │   └── mime-db@1.34.0 
  │ │   └── filenamify@2.1.0 
  │ ├─┬ express@4.16.3
  │ │ └─┬ accepts@1.3.5
  │ │   └─┬ mime-types@2.1.18
  │ │     └── mime-db@1.33.0 
  │ ├─┬ express-request-proxy@2.1.0
  │ │ └─┬ request@2.87.0
  │ │   └─┬ http-signature@1.2.0
  │ │     └── sshpk@1.14.2 
  │ ├─┬ find-up@2.1.0
  │ │ └─┬ locate-path@2.0.0
  │ │   └─┬ p-locate@2.0.0
  │ │     └── p-limit@1.3.0 
  │ ├── js-yaml@3.12.0 
  │ ├── npm-run@4.1.2 
  │ ├── prisma-db-introspection@0.0.14 
  │ ├── prisma-yml@1.0.59 
  │ └─┬ util.promisify@1.0.0
  │   └─┬ object.getownpropertydescriptors@2.0.3
  │     └─┬ es-abstract@1.12.0
  │       └── has@1.0.3 
  └─┬ prisma-cli-engine@1.0.48 
    ├─┬ ansi-styles@3.2.1
    │ └─┬ color-convert@1.9.2 
    │   └── color-name@1.1.1 
    └── jsonwebtoken@8.3.0 

npm WARN optional Skipping failed optional dependency /prisma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.

**Expected behavior**
Installation that completes without reporting any error

**Versions (please complete the following information):**

Ubuntu 16.04

node --version
v6.11.0

npm --version
6.1.0

**Comment by prolink007** [comment]
Also having the same issue with

Ubuntu 16.04
node 4.2.6
npm 3.5.2

**Comment by prolink007** [comment]
Upgrading to the following fixed this issue for me.

node 8.11.3
npm 5.6.0
