### ISSUE TITLE
Tinyints converted to ints and not booleans

### ISSUE THREAD

**Issue by HurricaneDancer** [prisma/prisma#2639]
## Bug description

When following this guide: https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project-node-mysql
npx prisma introspect turns TinyInts into Ints and not Booleans. 

## How to reproduce

1: Create a table with a boolean column 
2: Introspect database 
3: Look at the schema.prisma file and find the column. It will be Int and not Boolean. 

## Expected behavior

TinyInts should be converted to Booleans and not Ints.

## Prisma information

The "banned" property is a tinyint/boolean (or should be) 

model guild {
  account_age_limit    Int?              @default(0)
  banned               Int?              @default(0)
  command_prefix       String?           @default("!")
  discord_id           String            @unique
  id                   Int               @default(autoincrement()) @id
  mute_role            String?           @default("null")
  name                 String
  public               Int?              @default(0)
  registered_timestamp Int
  action_cooldown      action_cooldown[]
  action_log           action_log?
  channel_link         channel_link[]
  guild_module         guild_module[]
  infraction           infraction[]
  pinboard             pinboard[]
  role                 role[]
  subscription         subscription[]
  user_overrides       user_overrides[]
}

## Environment & setup

- OS: Windows
- Database: MySQL
- Prisma version: 2.0.0-beta.7
- Node.js version: 14.3.0

**Comment by pantharshit00** [comment]
I can confirm the behavior but we need to discuss internally if this should be the case.

**Comment by HurricaneDancer** [comment]
Thanks! Please let me know what the outcome is so I know if I should be changing anything :)

**Comment by pantharshit00** [comment]
Ok, so right now if you have `TINYINT(1)` which is tinyint of size one, we will detect that as a boolean otherwise we will detect the TINYINT as Integer.

So please either manually edit the scheme or reduce the size of your boolean tinyint fields.

**Comment by HurricaneDancer** [comment]
Which value will you detect as true and which for false? (eg 1= true and 0 = false)

**Comment by pantharshit00** [comment]
Yes, that is the standard

**Comment by pantharshit00** [comment]
I am going to close this now
