### ISSUE TITLE
Graphql import problem

### ISSUE THREAD

**Issue by OGNeutron** [prisma/prisma#2639]
Graphql import doesn't work.

import FriendsRequestsSubscriptionPayload from "./prisma.graphql" within my schema.graphql
Shows an error: Error: Type "NotificationOrderByInput" not found in document.

When it should just import the type without any issue.

**Versions (please complete the following information):**
 - Windows 10
 - `prisma` CLI: [e.g. `prisma/1.9.0 (darwin-x64) node-v10.4.0`]
 -  latest `graphql-import` `0.5.2`

https://github.com/OGNeutron/Prisma_main_hub - just clone and run it, you'd see the problem, and it you remove the import works fine, so the import is causing problems.

**Comment by marktani** [comment]
What exactly do you mean with running it? Are you able to provide a smaller setup that still reproduces this problem?

**Comment by mponizil** [comment]
Not sure what's going on here, but I think you helped me get my app working.

I have some imports from `generated/prisma.graphql` and others from my own graphql files with custom types. The issue goes away when I move the generated imports to the top.

Before:

```
# import AuthPayload from "./schema/auth.graphql"
# import User from "./schema/auth.graphql"
# import ForgotPasswordOutput from "./schema/auth.graphql"

# import SellerProfile from "./generated/prisma.graphql"
# import BuyerProfile from "./generated/prisma.graphql"
```

After:

```
# import SellerProfile from "./generated/prisma.graphql"
# import BuyerProfile from "./generated/prisma.graphql"

# import AuthPayload from "./schema/auth.graphql"
# import User from "./schema/auth.graphql"
# import ForgotPasswordOutput from "./schema/auth.graphql"
```

Hope this helps!

**Comment by marktani** [comment]
@mponizil can you share a minimal reproduction for this error? :slightly_smiling_face:
