### ISSUE TITLE
Connect Empty DB tutorial unable to deploy

### ISSUE THREAD

**Issue by luetkemj** [prisma/prisma#2642]
**Describe the bug**
Following this [tutorial](https://www.prisma.io/docs/tutorials/setup-prisma/connect-empty-db/postgres-aiy1jewith) for connecting an existing empty Postgres DB. `prisma deploy` fails with the following error: `Error: Variable '$name' expected value of type 'String!' but value is undefined. Reason: Expected non-null value, found null. (line 1, column 27):`

**To Reproduce**
1. Follow the linked tutorial exactly to step 12
2. Run `prisma deploy`

**Expected behavior**
I expect the server to deploy successfully and be able to access the playground at `http://localhost:4466/` and examine the schema, make queries, etc

Currently the playground deploys but I can examine the schema (stuck in a loading state) 

**Screenshots**

**Versions (please complete the following information):**
 - OS: macOS High Sierra 10.13.5
 - `prisma` CLI: `prisma/1.9.0 node-v8.11.3`]

**Additional context**
full error output from cli:

```
  deploy run +0ms
  client Sending query to cluster local +0ms
  client http://localhost:4466/cluster +0ms
  client
  client       query($name: String! $stage: String!) {
  client         project(name: $name stage: $stage) {
  client           name
  client           stage
  client         }
  client       }
  client      +0ms
  client { name: undefined, stage: undefined } +0ms

Creating stage undefined for service undefined...  client Sending query to cluster local +24ms
  client http://localhost:4466/cluster +0ms
  client       mutation addProject($name: String! $stage: String! $secrets: [String!]) {
  client         addProject(input: {
  client           name: $name,
  client           stage: $stage
  client           secrets: $secrets
  client         }) {
  client           project {
  client             name
  client           }
  client         }
  client       }
  client        +0ms
  client { name: undefined, stage: undefined, secrets: null } +0ms
 !
Error: Variable '$name' expected value of type 'String!' but value is undefined. Reason: Expected non-null value, found null. (line 1, column 27):
      mutation addProject($name: String! $stage: String! $secrets: [String!]) {
                          ^: {"response":{"data":null,"errors":[{"message":"Variable '$name' expected value of type 'String!' but value is undefined. Reason: Expected non-null value, found null. (line 1, column 27):\n      mutation addProject($name: String! $stage: String! $secrets: [String!]) {\n                          ^","locations":[{"line":1,"column":27}]},{"message":"Variable '$stage' expected valueof type 'String!' but value is undefined. Reason: Expected non-null value, found null. (line 1, column 42):\n      mutation addProject($name: String! $stage: String! $secrets: [String!]) {\n                          ^","locations":[{"line":1,"column":42}]}],"status":200},"request":{"query":"      mutation addProject($name: String! $stage: String! $secrets: [String!]) {\n        addProject(input: {\n          name: $name,\n          stage: $stage\n          secrets: $secrets\n        }) {\n          project {\n            name\n          }\n        }\n      }\n      ","variables":{"secrets":null}}}
    at GraphQLClient.<anonymous> (/Users/luetkemj/.config/yarn/global/node_modules/graphql-request/src/index.ts:72:13)
    at step (/Users/luetkemj/.config/yarn/global/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/Users/luetkemj/.config/yarn/global/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/Users/luetkemj/.config/yarn/global/node_modules/graphql-request/dist/src/index.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Exiting with code: 1
```

**Comment by marktani** [comment]
Does your `docker-compose.yml` contain this line:

```
    image: prismagraphql/prisma:1.8
```
? Then that's the problem. Update it to `1.9` and restart the docker-compose.

> Update: prisma.yml needs a stage key.

This is unexpected. If this is the current behaviour, it's a bug. Here is the expected behaviour:

Either: `cluster`, `service` and `stage` properties are used (pre 1.7)
Or: `endpoint` property (since 1.7)

**Comment by luetkemj** [comment]
I tried again tonight with a fresh install of prisma-cli and on node 10. Interestingly, this time I was **unable to deploy without both a service and stage key** in prisma.yml. I have created a repo if you want to test it. 

https://github.com/luetkemj/prisma-bug-demo

**Comment by luetkemj** [comment]
I installed `prisma`.

Before the test I ran `npm uninstall -g prisma` followed by `npm install -g prisma`.

I am still experiencing the issue where deploys fail without a stage and service key. if I add those, it works fine.

**Comment by marktani** [comment]
I cannot reproduce the issue. Here's what I do:

```
npm install -g prisma@1.10.1
git clone git@github.com:luetkemj/prisma-bug-demo.git
```

Change `prisma.yml` to 

```
endpoint: http://localhost:4466
datamodel: datamodel.graphql
# stage: dev
# service: default
```

Run `prisma deploy`. It works:

```
prisma deploy
Deploying service `default` to stage `default` to server `local` 420ms
Service is already up to date.
```

If I change `prisma.yml` to

```
endpoint: http://localhost:4466
datamodel: datamodel.graphql
stage: dev
service: default
```

and run `prisma deploy`, it also works:

```
Creating stage dev for service default ✔
Deploying service `default` to stage `dev` to server `local` 186ms

Changes:

  User (Type)
  + Created type `User`
  + Created field `id` of type `GraphQLID!`
  + Created field `name` of type `String!`
  + Created field `updatedAt` of type `DateTime!`
  + Created field `createdAt` of type `DateTime!`

Applying changes 1.1s

Your Prisma GraphQL database endpoint is live:

  HTTP:  http://localhost:4466/default/dev
  WS:    ws://localhost:4466/default/dev
```

This is probably unexpected. `endpoint` and `stage`/`service` should never be used in combination with each other. This is unrelated to your issue and I will create a separate issue for this.
