### ISSUE TITLE
Rename pinnedPlatform to pinnedBinaryTarget

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#2644]
`pinnedPlatform` is a field on the generator block in Prisma schema file. We made a decision to rename it to `pinnedBinaryTarget`. 

Decision: https://prisma-company.slack.com/archives/CEYCG2MCN/p1566475959421300
Spec PR: https://github.com/prisma/specs/pull/474

**Comment by Jolg42** [comment]
We have this message for info

https://github.com/prisma/prisma/blob/ead9e6bc0fb0443b90774d63e65eb627e1fe55c3/src/packages/sdk/src/getGenerators.ts#L322

Should we have the same for `pinnedBinaryTarget`?

**Comment by divyenduz** [comment]
Yes, any instance of the following should be renamed

platforms -> binaryTargets
pinnedPlatform -> pinnedBinaryTarget
