### ISSUE TITLE
Allow EXPERIMENTAL=true through .env

### ISSUE THREAD

**Issue by nahtnam** [prisma/prisma#2645]
## Problem
Currently, if we decide we want to use experimental features, we have to add `--experimental`.

## Suggested solution
It would be great if we could add `EXPERIMENTAL=true` or `PRISMA_CLI_EXPERIMENTAL=true` to the `.env` in the `primsa` folder to have it auto apply

## Alternatives
An even better alternative might be to define it in the `schema.prisma` file itself because `.env` is usually in the gitignore so when you push you have to remember to add `--experimental` to your CI.

EDIT: Also could have a `.prismarc` or something
## Additional context
N/A

**Comment by pantharshit00** [comment]
We decided against any persistent configuration so that each invocation needs an explicit decision.

**Comment by nahtnam** [comment]
I see, I'm not sure I agree with that, but as long as it was considered I'm happy. Thanks!

**Comment by Jolg42** [comment]
Thank you for understanding 🙏
