### ISSUE TITLE
Support introspecting @updatedAt from the database

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#2650]
**Problem**

Currently there's no way to format your database schema so introspection will pickup `@updatedAt`. This breaks automated re-introspection.

**Possible Solution**

In MySQL, it seems like we could add this in a fairly straightforward way:

```sql
ALTER TABLE User MODIFY COLUMN updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
```

In Postgres, the typical way you do this in the database is using triggers:

```sql
-- automatic "updated_at"
create or replace function set_updated_at() returns trigger as $$
begin
  new.updated_at := current_timestamp;
  return new;
end;
$$ language plpgsql;

create table if not exists users (
  id text primary key not null,
  updated_at timestamp with time zone default (now())
);
create trigger updated_at before insert on users for each row execute procedure set_updated_at();
```

I'm not sure about SQLite or Mongo.

**Comment by janpio** [comment]
How is `@updatedAt` currently migrated @tomhoule? I am pretty sure we are not using triggers.

**Comment by nikolasburk** [comment]
> How is `@updatedAt` currently migrated @tomhoule? I am pretty sure we are not using triggers.
> How is `@updatedAt` currently implemented on the Engine level? Is this handled by Prisma itself or does Prisma rely on the database @mavilein or @do4gr?

`@updatedAt` today isn't a DB feature but purely a Prisma-level feature (see docs [here](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/data-model/#overview-1)), I believe it's just ignored by Migrate?!

**Comment by mavilein** [comment]
Niko is right. `@updatedAt` is a pure prisma level feature at the moment. Hence the migration engnine does not do anything about it.

**Comment by janpio** [comment]
This means that it is also unclear if Introspection should work on this. Representing `DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP` with `@updatedAt` would require this to not be a Prisma level feature, otherwise we are mixing two levels together. While it might give the user close to what they expect, it is unclear if this will prevent us from building the right solution in the future.

**Comment by do4gr** [comment]
Our current thinking is to clearly split Prisma level and db level features. In this case we see @updatedAt as a Prisma level feature that is available across all databases and which does not get written to DDL. We also already followed this logic when working on re-introspection.

The DDL level on change would be detected as a db level feature and therefore stay in @default . Currently as dbgenerated() maybe later as a description of the actual statement in DDL.

Separating these two concepts will make it clearer for migrate and introspect to decide what happened when encountering changes in the schema / the db.

**Comment by omar-dulaimi** [comment]
So in 2021, should we use this
```
ALTER TABLE User MODIFY COLUMN updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
```
to persist updatedAt?
(currently using introspection only)

**Comment by pantharshit00** [comment]
@omar-dulaimi You can just use `@updatedAt` and the client will handle this field for you.

**Comment by omar-dulaimi** [comment]
@pantharshit00 But as far as I have read, introspection removes "@updatedAt", so you have to add them back manually
