### ISSUE TITLE
generator client output does not use scope of package.json; docs are misleading

### ISSUE THREAD

**Issue by asktree** [prisma/prisma#2654]
## Bug description
Custom output in schema.prisma generates output relative to prisma folder, not relative to package.json. So if you use `prisma init` to make your project, the docs are misleading. 
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/generating-prisma-client#specifying-the-target-location-for-prisma-client-a-idcustom-outputa

## How to reproduce

specify in schema.prisma:
`generator client {
  provider = "prisma-client-js"
  output   = "./node_modules/.prisma/client"
}`

run `prisma generate` and observe location of client.

## Environment & setup

- OS: Windows & Ubuntu via WSL
- Prisma version: 2.0.0-beta.6
- Node.js version: 10.21.0

**Comment by janpio** [comment]
Can you specify a bit more where you actually see the generated output vs. where you would expect it?

**Comment by janpio** [comment]
Happy to open this again if we get more information.
