### ISSUE TITLE
Dealing with Generator Name Conflicts

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#2656]
I want to start an issue that collects all the naming issues we're encountering with the goal of finding a solution that we can apply across the languages we care about.

### Suggested Goals

**1. Database schemas are not denied due to name conflicts**

Currently we have a large deny list that prevents users from modeling their domain in a way that fits their business

**2. What we generate does not product syntax errors**

We should have either a naming, number, or symbol pattern that can reliably find unused variables & definitions. 

For example, one solution could be if the user uses `model Class`, our names could be `Class1` or `Class_` or `_Class` or `Clss` or `Klass`. If the user has `model _Class`, our names could be `__Class`, etc. We should try and reach a decision on how we want to do this in the various languages so it's relatively consistent.

### Specific Issues: 

- Large deny list restricting people's data modeling: https://github.com/prisma/prisma-client-js/issues/707
- Relation and field with same name causes problems in Go: https://github.com/prisma/prisma-client-go/issues/140

**Comment by steebchen** [comment]
For now, we decided that this is each generator's individual problem, because there are only a few rare cases where conflicts occur in JS, and Go has a specific problem because of the nature of casing in the language.
