### ISSUE TITLE
Unique constraint failed on the fields

### ISSUE THREAD

**Issue by yantakus** [prisma/prisma#2657]
I'm getting the following error: `Unique constraint failed on the fields: ('uid')`

When running the following operation:

```
          prisma.video.update({
            where: { ytId },
            data: {
              bookmarkers: {
                create: {
                  uid: userId,
                },
              },
            },
          })
```

Here's the schema:

```
model Video {
  ytId        String     @id
  uploader    User       @relation("UserVideos", fields: [uploaderId], references: [uid])
  uploaderId  String
  bookmarkers User[]     @relation("UserBookmarks")
}
model User {
  uid       String  @id
  videos    Video[] @relation("UserVideos")
  bookmarks Video[] @relation("UserBookmarks")
}
```

Is this a bug or am I doing something wrong?

**Comment by WellFail** [comment]
Check that you does not have User with uid equals userId thats you provide into request. And why are you setting id for user manually?

**Comment by yantakus** [comment]
@WellFail thank you, my bad. It should be `connect` instead of `create`. The error is not informative enough, so I thought there's a problem with the schema or something else and even didn't think about checking my code for logical errors once again.

**Comment by ludovv** [comment]
> @WellFail thank you, my bad. It should be `connect` instead of `create`. The error is not informative enough, so I thought there's a problem with the schema or something else and even didn't think about checking my code for logical errors once again.

I was facing the same problem and doing the same mistake as you, thanks! :-)
