### ISSUE TITLE
Add minimal integration test for studio

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#2658]
In Beta 7, studio was that broken, that it directly crashed when being opened.
A basic test, that starts studio and just fetches `http://localhost:5555` can already catch that.

**Comment by timsuchanek** [comment]
Just talked about it with @madebysid  - he will add a minimal endpoint so we can just use `fetch` instead of needing to run the whole studio frontend with Puppeteer. He'll earliest work on that next sprint.

**Comment by timsuchanek** [comment]
Closed by https://github.com/prisma/prisma/pull/3079

**Comment by madebysid** [comment]
Created https://github.com/prisma/prisma/issues/3094 as follow up
