### ISSUE TITLE
Downloading Prisma engines for windows Error

### ISSUE THREAD

**Issue by pallemach2** [prisma/prisma#2660]
## Bug description

When using npx or installing prisma with npm install im stuck with downloading the Prisma-engine for windows.

![prisma](https://user-images.githubusercontent.com/56473073/83762688-1792bb80-a678-11ea-98d9-9f8798d67cda.PNG)

**Comment by pantharshit00** [comment]
Hi @pallemach2 

Can you please try again? We have added this missing binary and it should work now.

**Comment by pallemach2** [comment]
Hey @pantharshit00,

yea it's working now! Thank you!

**Comment by santilp95** [comment]
don't work :'c
Downloading Prisma engines for windows [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/b8c35d44de987a9691890b3ddf3e2e7effb9bf20/windows/query-engine.exe.gz.sha256 failed, reason: self signed certificate in certificate chain

**Comment by janpio** [comment]
> reason: self signed certificate in certificate chain

This describes the problem - somewhere in between there is a self signed certificate your computer does not actually trust and hence declines to download the file.

**Comment by walidmourou** [comment]
Me too have the same issue...

**Comment by srinivassunkari** [comment]
![image](https://user-images.githubusercontent.com/59680788/162798908-cfff0d5c-1212-402f-8582-e617a14bbf66.png)
can anyone help on this.

**Comment by janpio** [comment]
> We still wait for a solution.

Is there an issue for this where we are actually tracking the need for a change in any way?

**Comment by walidmourou** [comment]
I think, it is the same issue then here:
https://github.com/prisma/prisma/issues/12457

**Comment by Paladinagapullaiah** [comment]
Downloading Prisma engines for Node-API for windows [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/0362da9eebca54d94c8ef5edd3b2e90af99ba452/windows/introspection-engine.exe.gz.sha256 failed, reason: unable to get local issuer certificate

when I try to execute> npx prisma init --datasource-provider
I have tried the above suggestion as well but could not resolve it, can any one suggest me on it.

**Comment by janpio** [comment]
Open a new issue or discussion please. We can not help here in closed issues.
