### ISSUE TITLE
Remove local and cluster commands and remove cluster API endpoint and clusterInfo

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2666]
* deprecate local and cluster commands was planned for 1.9: https://github.com/prismagraphql/prisma/releases/tag/1.7.0
* deprecate `/cluster` endpoint and `clusterInfo` was planned for 1.10: https://github.com/prismagraphql/prisma/releases/tag/1.8.0

**Comment by divyenduz** [comment]
For
`prisma local start`
`prisma local stop`
`prisma local upgrade`
`prisma local nuke`
`prisma local ps`
`prisma local`
Error message => As mentioned in prisma 1.7 [release notes](https://github.com/prismagraphql/prisma/releases/tag/1.7.0) this command was deprecated and is now removed. You can use `docker-compose` directly to manage the state of local server. 

For 
`prisma cluster list`
`prisma cluster add`
`prisma cluster remove`
`prisma cluster logs`
`prisma cluster`
Error message => As mentioned in prisma 1.7 [release notes](https://github.com/prismagraphql/prisma/releases/tag/1.7.0) this command was deprecated and is now removed. 

Looks good? For `cluster` command(s), the release notes mention that cloud can be used to manage the servers but that is not completely correct yet, hence, I did not add that to the error message.

**Comment by marktani** [comment]
`prisma cluster` has this output:

![image](https://user-images.githubusercontent.com/1780597/42817680-211f1436-89cf-11e8-8d4e-6387f10fbcd1.png)
