### ISSUE TITLE
I'm allowed to include the same field twice in an @@unique declaration

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#2668]
## Bug description

This schema is considered valid for migrations and Client generation, when it shouldn't be:
```
model User {
  id    Int
  name  String
  email String

  @@unique([name, name])
}
```

This leads to migrations & Client generation succeeding, but the query engine fails when you try to run this query:
```
await prisma.user.findOne({
      where: {
        name_name: {
          name: "Something",
        },
      },
    })
```

## How to reproduce

1. Type the above schema in VSCode to see no red squiggly lines
2. Try running `prisma migrate save && prisma migrate up`  against it
3. Try running `prisma generate` against it.

## Expected behavior

The VSCode extension, `prisma migrate` command & the `prisma generate` command should fail saying that the schema is invalid.

## Environment & setup

- OS: macOS
- Database: Postgres
- Prisma version: 
```
@prisma/cli          : 2.0.0-alpha.1299
Current platform     : darwin
Query Engine         : query-engine d88852ac341cdf3c7379a08fa1ebc5c444a4aa67
Migration Engine     : migration-engine-cli d88852ac341cdf3c7379a08fa1ebc5c444a4aa67
Introspection Engine : introspection-core d88852ac341cdf3c7379a08fa1ebc5c444a4aa67
Format Binary        : prisma-fmt d88852ac341cdf3c7379a08fa1ebc5c444a4aa67
```
- Node.js version: v12.16.3

**Comment by pantharshit00** [comment]
I can confirm this. We should throw an error here on generation.

But the typescript typing seem to ignore this duplication:
![image](https://user-images.githubusercontent.com/22195362/84221878-d6752e00-aaf3-11ea-9aa6-48e0190f8b25.png)

As a result typescript doesn't allow you to make the query mentioned in the about description:
![image](https://user-images.githubusercontent.com/22195362/84221901-de34d280-aaf3-11ea-96cb-b71378b136eb.png)


When I try to execute the query the client runtime rejects it:
![image](https://user-images.githubusercontent.com/22195362/84221990-163c1580-aaf4-11ea-93ce-ab75de9d087e.png)


So we need to throw an error in the generation here.

**Comment by pantharshit00** [comment]
Version information:
```
@prisma/cli          : 2.1.0-dev.4
Current platform     : darwin
Query Engine         : query-engine de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/harshit/code/reproductions/issue-2668/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/harshit/code/reproductions/issue-2668/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/harshit/code/reproductions/issue-2668/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/harshit/code/reproductions/issue-2668/node_modules/@prisma/cli/prisma-fmt-darwin)
```
