### ISSUE TITLE
queryRaw Error when calling SP or Function

### ISSUE THREAD

**Issue by nicosampler** [prisma/prisma#2679]
When I try to get the results for an SP or a function like:

`queryRaw("CALL increaseShopCounter()");` or `queryRaw("select callIncreaseShopCounter();")`

it fails with an undescriptive message:
```
prisma:query select callIncreaseShopCounter(
        15, 
        79,
        5
      ) as issuedId
PrismaClientKnownRequestError: Raw query failed. Code: `N/A`. Message: `N/A`
    at PrismaClientFetcher.request (/home/nicosampler/develop/cauda/node_modules/@prisma/client/runtime/index.js:1:148505)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2010',
  meta: { code: 'N/A', message: 'N/A' }
}
```
Both SP and Function return values when executing them directly.

DB: MySql
Prisma:
    "@prisma/cli": "^2.0.0-beta.8",
    "@prisma/client": "^2.0.0-beta.8",

**Comment by timsuchanek** [comment]
Thanks @nicosampler !
Please try using `executeRaw` instead. This happens, because your query probably doesn't return rows, then the db driver errors.
We will improve the error message here.

**Comment by ramirotw** [comment]
I'm seeing the same behavior calling a stored procedure that runs some updates/inserts and then return results, I can't use `executeRaw` as I need the results back and `queryRaw` fails without much info.

**Comment by pimeys** [comment]
Need to see if something is broken in the underlying MySQL crate. At least we need better error messages here.

**Comment by pimeys** [comment]
Tested:

```sql
DELIMITER $$
CREATE PROCEDURE FooBar() BEGIN SELECT 1; END$$
DELIMITER $$
```

using `queryRaw` with `CALL FooBar()`, returns row with one column, holding the value 1. Should be fixed in the dev releases, available later today. Or in 2.1.0, coming in a few weeks.
