### ISSUE TITLE
Flatten single scalar field child results

### ISSUE THREAD

**Issue by kbrandwijk** [prisma/prisma#268]
This query:
```
query
{
  Post(id: "cj3j0ylcmz72w01282yhxbp9r"){
    id
    description
    postItems {
      title
    }
  }
}
```
Returns:
```
{
  "data": {
    "Post": {
      "id": "cj3j0ylcmz72w01282yhxbp9r",
      "description": "Another Cat",
      "postItems": [
        {
          "title": "FirstItem"
        },
        {
          "title": "SecondItem"
        }
      ]
    }
  }
}
```
It would be nice do be able to do:
```
query
{
  Post(id: "cj3j0ylcmz72w01282yhxbp9r"){
    id
    description
    postItems @flatten {
      title
    }
  }
}
```
That would give you:
```
{
  "data": {
    "Post": {
      "id": "cj3j0ylcmz72w01282yhxbp9r",
      "description": "Another Cat",
      "postItems": ["FirstItem", "SecondItem"]
    }
  }
}
```

**Comment by marktani** [comment]
One compliation with the way you've written it down is that fields/nodes are typed and your two queries return would require different types for `postItems`.

This feature request has also been discussed [as a feature request for GraphQL](https://github.com/facebook/graphql/issues/174). Maybe you can add your voice there as well?

**Comment by kbrandwijk** [comment]
Great, will do!

**Comment by grahamegrieve** [comment]
It's extremely tricky, if you use this, to track whether the output of the children should or shouldn't be a list. The simple case is ok, but as you start adding conditions and aliases, it can become pretty difficult to keep track of things

**Comment by grahamegrieve** [comment]
see discussion at https://github.com/ropenscilabs/ronfhir
