### ISSUE TITLE
@prisma/engine-core forces users to enable esModuleInterop

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#2681]
## Bug description

Consumers of `@prisma/client` beta 8 need to have their tsconfig setup with `esModuleInterop: true` OR `skipLibCheck: true`. This was not the case in beta 4.

The source of the issue is not `@prisma/client` but rather `@prisma/engine-core`.

In the screenshot below the `code .` part is when I go enable `esModuleInterop` in the project.

![image](https://user-images.githubusercontent.com/284476/83955147-d50ae380-a81d-11ea-8b54-e9c8b959be5e.png)

## How to reproduce

You can repro on this branch https://github.com/graphql-nexus/nexus-plugin-prisma/pull/137. I have not spent the effort to make a minimal repro yet sorry!

## Expected behavior

As a consumer of `@prisma/client` I expect a modern experience which in part means not being the source of requiring my project to flip the `esModuleInterop` flag in my tsconfig setting.

## Prisma information

Its a tsconfig thing

## Environment & setup

- OS: 
- Database: 
- Prisma version: 
- Node.js version: 

Don't think this matters.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by jasonkuhrt** [comment]
Thanks @timsuchanek! As discussed offline, the issue is consumption of `@prisma/sdk`, not `@prisma/client`.
