### ISSUE TITLE
Clarify case insensitivity for unique fields

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2684]
**Is your feature request related to a problem? Please describe.**
Currently, the [data model docs](https://www.prisma.io/docs/reference/service-configuration/data-model/data-modelling-(sdl)-eiroozae8u#field-constraints) mention:

> Please note that only the first 191 characters in a String field are considered for uniqueness and the unique check is case insensitive. Storing two different strings is not possible if the first 191 characters are the same or if they only differ in casing.

This is not accurate.

**Describe the solution you'd like**

The behaviour actually depends on the database collation, which can be case insensitive (`_ci`) or case sensitive (`_cs`). This should be added to the documentation.

**Additional context**
https://github.com/prismagraphql/prisma/issues/1641#issuecomment-399752411

**Comment by andrewjmead** [comment]
> The behaviour actually depends on the database collation, which can be case insensitive (_ci) or case sensitive (_cs). This should be added to the documentation.

Is there currently a way to customize this behavior as a user of Prisma?
