### ISSUE TITLE
Tutorial: Prisma from scratch

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#2694]
**Describe the content you'd like to see**
A section in documentation that shows how to write `prisma.yml`, graphql config, `datamodel.graphql` and maybe even `docker-compose.yml` without any tools like `prisma init`. Generally, the tools abstract away the working of a system and abstractions are [leaky](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/). 

A section like this will increase the understand of the system amongst its users. 

**Describe alternatives you've considered**
Generally, I had to tinker with the `prisma.yml` and `prisma` CLI to figure out what files, variables, and values are mandatory and their impact. 

**Additional context**
I think that base knowledge of how the CLI interacts with graphql config, `prisma.yml` is essential to production-ize the system or even use it in environments not documented in a first-class way like Travis, CircleCI etc. 

In the past, I wrote such a [post](https://divu.in/prisma-deep-dive-3162dea2820c) about the datamodel/some basic commands and it was received very well.

**Comment by pantharshit00** [comment]
@divyenduz 

I think this can be closed as the current getting started workflow includes this.
