### ISSUE TITLE
Prisma Query Engine process not stopping after completion

### ISSUE THREAD

**Issue by gyash24x7** [prisma/prisma#2695]
## Bug description

I have a graphql server running, that queries data using prisma. For every query or mutation, a process is launched by prisma. After query/mutation completion, the process doesn't die automatically and stays in the memory. After some more queries and mutations, my memory usage touches 90% and my instance crashes. 

I ran htop to investigate which process was consuming memory. Please refer to the screenshot attached. 

`query-engine-debian-openssl-1.1.x` process is the one that is launched on every operation and doesn't die.

## Expected behavior

After the query succeeds, the process should die.

## Environment & setup
- OS: Ubuntu 18.04
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.5
- Node.js version: 12.18

<img width="1257" alt="screenshot" src="https://user-images.githubusercontent.com/38939232/84110183-0663f900-aa42-11ea-9c7e-e7f3725e6b87.png">

**Comment by pantharshit00** [comment]
Hi @gyash24x7 

Can you please share a minimal reproduction? Also, please try using the latest version. Thanks!

**Comment by gyash24x7** [comment]
Hi, @pantharshit00 

I looked into the issue and it turns out that I was creating multiple instances of the PrismaClient in my app that was using up all the memory. The issue itself is resolved but, should there be a check to use existing PrismaClient instance, if any is active?If not, then create a new instance.

**Comment by pantharshit00** [comment]
I am going to close this issue then. 

Your other concern is related to https://github.com/prisma/prisma-client-js/issues/730
