### ISSUE TITLE
Mention that different deployment steps + hooks are not atomic

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2698]
**Describe the content you'd like to see**

For example, if your `seed.graphql` has a problem and you run `prisma deploy`, the deployment will happen, but the seeding will fail.

This is according to the specification, but should be covered explicitely in the documentation.

**Comment by peterschussheim** [comment]
> This is according to the specification, but should be covered explicitly in the documentation.

Where is this specification located?

Regarding the example mentioned (run `prisma deploy` -> seeding hook fails -> result = ok), why is that the current behavior?  Shouldn't an operation like that cause the entire migration (`prisma deploy`) to fail?

**Comment by marktani** [comment]
> Where is this specification located?

Nowhere, hence this feature request to document it 🙂 

> Shouldn't an operation like that cause the entire migration (prisma deploy) to fail?

No, at least not how it works right now. The deployment runs first, only after which seeding is initiated. There is no mechanism right now that would roll back the deployment in case there is a problem with seeding.

If you would like this to change in the future, feel free to open a separate feature request 🙂This issue is about documenting the current behaviour.
