### ISSUE TITLE
Add examples using apollo-server (instead of graphql-yoga)

### ISSUE THREAD

**Issue by peterschussheim** [prisma/prisma#2699]
**Describe the content you'd like to see**

`graphql-yoga` offers many features when first getting started, however, there are legitimate reasons why a user may want to migrate **away** from yoga.  Currently, it is a bit 'opaque' with regard to the steps needed to migrate to an alternative, such as `apollo-express`.

I am proposing that this repo provides a guide similar to how the Apollo team provides (see below for examples).

**Additional context**

A few examples showing (in my opinion) nice migration guides:

- [instructions for migration from `apollo-boost` to `apollo-client` ](https://www.apollographql.com/docs/react/advanced/boost-migration.html), (nice before and after examples)
- [`apollo-server` 2.0 migration ](https://www.apollographql.com/docs/apollo-server/v2/migration-two-dot.html)

**Comment by cpenarrieta** [comment]
Hey @peterschussheim I did a simple boilerplate project using apollo server 2.0 and prisma.
https://github.com/cpenarrieta/prisma-apollo-2.0

**Comment by nklayman** [comment]
@cpenarrieta you should create a full tutorial on Prisma+Apollo server 2.0 and create a PR for it to be in the official docs (also post on medium).

**Comment by karloluis** [comment]
Any news on how this will move forwards?

**Comment by matthewhuang-camelot** [comment]
+1!

**Comment by brentinator0** [comment]
+1!!!!!!!

**Comment by alan345** [comment]
I migrate today to apollo server.
Hope the Prisma team will give us a clear guideline regarding this matter: should we migrate GraphQL Yoga to apollo server?
