### ISSUE TITLE
`Environment variables loaded from` uses wrong directory separator (slashes) on Windows

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2699]
```
C:\Users\Jan\Documents\throwaway\1313>prisma introspect
Environment variables loaded from ./prisma/.env

Introspecting based on datasource defined in prisma\schema.prisma …
Error: P1001
```

**Comment by pizzafox** [comment]
https://github.com/prisma/prisma/blob/0118def34b4105ee1ce8b105efe1eacfef374956/src/packages/cli/src/bin.ts#L80

When working with paths in Node you should always  use `path.join` to avoid quirks like this:

```ts
import { join as joinPaths } from 'path';

dotenv.config({ path: joinPaths('prisma', '.env') });
```

**Comment by timsuchanek** [comment]
Thanks @pizzafox but that line is not the problem.
The Dotenv library under the hood uses the path library and therefore can deal with the `/`.
The problem is just the hardcoded `/` path separator.

Using a simple `path.relative` solves this problem.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
