### ISSUE TITLE
DateTime mixed up with Date

### ISSUE THREAD

**Issue by joneslloyd** [prisma/prisma#2702]
## Bug description

Table field that should be `datetime` is generated as `date`.

## How to reproduce

Use [this](https://gist.github.com/joneslloyd/db7f25cbc1e200178fe990cda21152e7) schema.prisma file. The two date fields are `date` in the database instead of `datetime`.

## Expected behavior

Date fields are `datetime`.

## Prisma information

- [schema.prisma](https://gist.github.com/joneslloyd/db7f25cbc1e200178fe990cda21152e7)
- [Nexus/GraphQL](https://gist.github.com/joneslloyd/7499aebdc71febfa9f6e8a3e5b9ac4cc)

## Environment & setup

- OS: macOS Catalina 10.15.4
- Database: SQLite
- Prisma version: prisma/1.18.1 (darwin-x64) node-v12.16.3
- Node.js version: v12.16.3

**Comment by janpio** [comment]
What exactly is generated where with what command?

**Comment by pantharshit00** [comment]
We store a unix timestamp in the date column. Let us know what behavior you want instead of this.

**Comment by joneslloyd** [comment]
I think something is going wrong with the unix timestamp.

The DateTime I try to store is `2003-03-13T03:34:35+00:00`, yet the unix timestamp is `1047526475000`.

My understanding was that it's because we're trying to put DateTime into a Date column (instead of DateTime column).

But maybe it's broken for some other reason?

**Comment by joneslloyd** [comment]
UPDATE

I think this is a case of the old _user error_!

I forgot that JS timestamps use milliseconds (I come from a back-end background). That'd explain the difference!

**Comment by janpio** [comment]
Still something we could catch and have a nice, user friendly warning or error mesage, right @pantharshit00?

**Comment by pantharshit00** [comment]
No this isn't an error. OP was just questioning the type used by us by default. 


There was a confusion around JS using milliseconds based unix timestamps while sqlite uses seconds based unix timestamp. 

I don't think there is anything actionable for us here.

**Comment by joneslloyd** [comment]
Correct – It was totally user error :)
