### ISSUE TITLE
ENOENT when running prisma with pkg

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#2717]
```
npm i -g pkg
npm i @prisma/cli
pkg node_modules/@prisma/cli

./cli-macos --version
```

results in

```
Error: ENOENT: no such file or directory, copyfile '/home/runner/.cache/prisma/master/dc0f43d1460553447c563479493914279205d48f/debian-openssl-1.1.x/prisma-fmt' -> '/snapshot/node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x'
```

**Comment by steebchen** [comment]
We can test it by pushing to prisma and rebase into https://github.com/prisma/e2e-tests/pull/425

**Comment by steebchen** [comment]
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/5013932/84391176-d0319f80-ac22-11ea-87c9-95689e37d9a5.png">

Seems the issue still exists with dev.12

**Comment by Jolg42** [comment]
@timsuchanek I guess this doesn't work anymore https://github.com/prisma/prisma/blob/1bebe39b5a7299392c15d913af3962083c845f11/src/packages/sdk/src/resolveBinary.ts#L48-L52

**Comment by pantharshit00** [comment]
I can confirm this:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22195362/84897421-2c813d00-b0c3-11ea-8b5c-1ac8ca016db4.png">

version: `2.1.9-dev.29`

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
