### ISSUE TITLE
Generator error hidden

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#2722]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/5013932/84420516-57433f80-ac44-11ea-88f4-afc934399e12.png">

When a generator returns a non-exit status code, the Prisma CLI exits with a status code of zero.

Also, even with a non-zero exit code, the error should be rendered without having to set DEBUG=*.

TODO: provide reproduction

**Comment by dodas** [comment]
I am not sure if this is related, but it looks like `prisma generate` exits without zero exit code even though there is an error.
Log from building my docker image:
```
Step 16/18 : RUN yarn prisma:generate
 
 ---> Running in 622a392152d9
 
yarn run v1.22.4
 
$ prisma generate
 

 
Error: The schema at "/home/node/app/packages/server/prisma/schema.prisma" conta
 
ins reserved keywords.
 
       Rename the following items:
 
         - "model CompanyClient"
 
Done in 1.68s.
 
 ---> 471a242897d3
Removing intermediate container 622a392152d9
Step 17/18 : CMD yarn start
 ---> Running in 3f81e98a76f7
 ---> 4b61f970ca07
Removing intermediate container 3f81e98a76f7
Step 18/18 : EXPOSE 4000
 ---> Running in c5bcadf2c2d2
 ---> 41ff5c6c871c
Removing intermediate container c5bcadf2c2d2
Successfully built 41ff5c6c871c
Successfully tagged ***************/server:latest
Successfully tagged ***************/server:3eb8de1
 ```
I expected the docker build to fail.

**Comment by steebchen** [comment]
@dodas It seems your error is unrelated; can you please try running `yarn prisma generate; echo $?` in your docker file `RUN` command and check what error code is returned?
