### ISSUE TITLE
CI Pipeline: Release stable release from chosen dev instead from current master state

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2724]
Right now a release is done from master which is accidentally also the latest dev - but it might not always be e.g. in the case when we have a broken version etc. what we want is that the release script just takes the exact dev version that should be turned into a real release.

**Comment by timsuchanek** [comment]
This is implemented in the latest pipeline and has already been used for `2.0.1`.
We set the env var `RELEASE_PROMOTE_DEV` to accomplish this.
