### ISSUE TITLE
Support mysql connection string w/ Google Cloud service accounts

### ISSUE THREAD

**Issue by joneslloyd** [prisma/prisma#2728]
## Problem
It's not possible (as far as I know) to create a mysql connection string using a service account.

When I try the method shown [here](https://github.com/prisma/prisma/issues/1508):
```
"mysql://user:psswd@localhost/db?socket=(/cloudsql/project:region:db)"
```

I get the error:
```
Error: undefined: Error querying the database: Error querying the database: No such file or directory (os error 2)
```

Also it's not clear, from the above string, that it's even using the service account (I don't think it is, but some comments implied it might be).

...
## Suggested solution
Possibly offer support for this if there's enough demand and/or make clear that it's not supported.

## Alternatives
Use the normal connection string, which works:
```
"mysql://<username>:<password>@localhost:3306/<database>"
```
## Additional context
N/A

**Comment by pantharshit00** [comment]
Google cloud is using unix domain sockets. They are supported by us. The "normal" connection stirng that you have posted is uses a TCP port. 



Can you please make sure that Cloud SQL admin API is enabled, that seem to be the problem encountered by most of the users so far.

**Comment by joneslloyd** [comment]
It is enabled, yes! – So would it be this? https://www.prisma.io/docs/reference/database-connectors/mysql#connecting-via-sockets

**Comment by pantharshit00** [comment]
The MySQL one there is incorrect unfortunately, it should get fixed. 

The url should like this: `mysql://USER:POST@localhost/database?socket=/var/run/mysql/`


Here is the PR which fixes the docs: https://github.com/prisma/docs/pull/413

**Comment by joneslloyd** [comment]
Thanks!

**Comment by pantharshit00** [comment]
I am closing this then, let me know here if this is still actionable.

**Comment by itsfaqih** [comment]
does it works?
why is it not working for me? am i doing it right?
```
mysql://username:password@localhost/dbname?socket=/cloudsql/project:region:db
```
still get the same error:
```
Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: No such file or directory (os error 2)
```

**Comment by pantharshit00** [comment]
Make sure you have enabled the cloud sql api

**Comment by itsfaqih** [comment]
did you meant the cloud sql admin api? if it is then yes, i have make sure it's enabled.
if the connection string is correct.. i wonder what gone wrong :/

**Comment by pantharshit00** [comment]
Try again with a new database. If you can still reproduce this, open an new issue with steps for reproduction.
