### ISSUE TITLE
Document relation between updateX mutation and unique fields

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2729]
**Describe the content you'd like to see**

For a type like

```graphql
type Action {
  startTimestamp: DateTime!
  endTimestamp: DateTime
  description: String
  gitHash: String
}
```

no update mutation is generated. The reason is that there is no `@unique` property. This should be clearly documented.

**Comment by abhiaiyer91** [comment]
Is there a section where this should be put?

**Comment by marktani** [comment]
I think we can put it in two places: where the `@unique` directive is described, as well as the `updateX` mutations.
