### ISSUE TITLE
Documentation page causes 100% CPU and freezes for 13 seconds before clicking a link responds

### ISSUE THREAD

**Issue by thesunny** [prisma/prisma#2731]
## Bug description

Viewing your documentation page here https://www.prisma.io/docs/ causes CPU to spike to over 100%+ on Google Chrome on Mac OSX (may be happening on other platforms as well). During this time, scrolling is broken, hover links don't change and the page is frozen. Switching to other pages like clicking on "Prisma Client" takes about 13 seconds (counting in my head) to complete and spikes CPU to 100%+ on my iMac Retina (4 GHz Quad-Core Intel Core i7).

![image](https://user-images.githubusercontent.com/469587/84548300-256cc000-acba-11ea-8c1b-15bd7c298d35.png)

## How to reproduce

Go to docs page and click around in the index.

## Expected behavior

Should be able to browse around quickly.

## Prisma information

n/a

## Environment & setup

- Chrome Version 83.0.4103.97 (Official Build) (64-bit)
- OSX Catalina 10.15.4

**Comment by janpio** [comment]
Fascinating this is even possible.

We are aware, and while we thought 3 hours ago we had fixed it we indeed seem not have to - sorry.

I will probably have to disable the search field for now.

**Comment by thesunny** [comment]
@janpio Can confirm the issue doesn't exist anymore.
