### ISSUE TITLE
Instantiating and disconnecting PrismaClient per end-user connection causes hard to track down `Unknown Error`

### ISSUE THREAD

**Issue by thesunny** [prisma/prisma#2733]
## Problem

It is unclear what the best practice is for creating and using `PrismaClient` instances in the documentation and this can cause a hard to track down crash.

It's not unusual to instantiate a Client once per connection to an API endpoint and use that session until the end of the connection. Then it's not an unusual expectation to call `disconnect` at the end of the connection to ensure it is cleaned up properly.

However, this creates a situation that results in `Error: Unknown error in Prisma Client` as per this issue I submitted: https://github.com/prisma/prisma-client-js/issues/723

It's insiduous because the error is `Unknown error` and it's not clear how to find a remedy or where to start looking.

## Suggested solution

Add documentation that recommends a single instance of `PrismaClient` should be used for an app and that connection pooling will handle the rest.

In practice, it appears that each instance of `PrismaClient` acts like a singleton when it comes to `disconnect`. We aren't disconnecting the instance but we are disconnecting all of `Prisma`. I'm not sure if that's what's happening but the bug disappears when I stop disconnecting per instance.

## Alternatives

Allow `PrismaClient` instances to disconnect individually without causing crashes. May require checking if there are any remaining PrismaClient instances before actually disconnecting. However, this doesn't seem to be as good a solution as just updating the documentation.

## Additional context

This error is also tricky because it does not happen on the local setup. This may be due to the database and the client being on the same machine. When deployed to Heroku, the error appears randomly. In such a situation, the initial instinct is that it is due to the platform change.

**Comment by wuichen** [comment]
Wonder if this is related, but sometimes, when i try to delete my db thru pgadmin, it shows me that there are still several connections remaining, even tho i have already shut down my executing terminals.

**Comment by janpio** [comment]
Can you share a minimal reproduction of what you have been experiencing @thesunny? It would be super helpful if we have some code that we just need to execute to get to the same error - then we can find out what _really_ is happening and figure out what we can do to solve it properly.

**Comment by pantharshit00** [comment]
Yes, @thesunny are you like initializing the client per graphql request by passing `new PrismaClient()` the context or you are using it a restful app and manually creating and calling disconnect per request.

**Comment by janpio** [comment]
Happy to open this again if we get more information.
