### ISSUE TITLE
.env not loaded when running `prisma migrate (save | up | down) --schema <file-path>`

### ISSUE THREAD

**Issue by AryanJ-NYC** [prisma/prisma#2735]
## Bug description
When running `prisma migrate (save | up | down)` with a non-default schema path (that is, when providing a `--schema` option value), the `.env` file in the `prisma` directory does not load.

## How to reproduce

1. `git clone https://github.com/AryanJ-NYC/prisma-with-migrate-schema-example`
2. `git checkout env-file-failure`
3. `yarn install`
4. `yarn prisma migrate save --experimental --schema src/prisma/schema.prisma`

## Expected behavior
I expected the `.env` file to be read and loaded.

## Prisma information

`schema.prisma`:
```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```
`.env`:
```
DATABASE_URL="file:./dev.db"
```
## Environment & setup
- OS: Mac OS
- Database: SQLite
- Prisma version: 2.0
- Node.js version: 12.16.3

## Root of Bug
In [`src/packages/cli/src/bin.ts`](https://github.com/prisma/prisma/blob/master/src/packages/cli/src/bin.ts#L53), `arg()` is used to parse the options. Since `migrate` has subcommands (`up`, `down`, `save`), the third-party [`arg`](https://www.npmjs.com/package/arg) package will stop parsing at the subcommand (again, `up`, `down` or `save`) since [`stopPositional`](https://www.npmjs.com/package/arg#stopatpositional) is `true` (and throw the valid options into the `_` array of the result).

This can be solved by being [`permissive`](https://www.npmjs.com/package/arg#permissive) when parsing the `args` and _not_ halting at the first positional argument (the migrate subcommands).

**Comment by pantharshit00** [comment]
Thanks for the PR, cc @Jolg42

**Comment by Jolg42** [comment]
Thank you for this issue and PR, sorry it took a while to merge this time 😄
