### ISSUE TITLE
'take' argument is not available in findMany() and count()

### ISSUE THREAD

**Issue by naveen-bharathi** [prisma/prisma#2742]
## Bug description

When using the **take** argument inside findMany() or count(), it results in an error saying that take is not a valid argument and suggests **last**.

```zsh
Invalid `prisma.store.findMany()` invocation in
/Users/.../store/index.js:58:84

Unknown arg `take` in take for type Store. Did you mean `last`? Available args:
type findManyStore {
  where?: StoreWhereInput
  orderBy?: StoreOrderByInput
  skip?: Int
  after?: StoreWhereUniqueInput
  before?: StoreWhereUniqueInput
  first?: Int
  last?: Int
}
```

## How to reproduce

```prisma
model Store {
  dbID     String  @default(cuid()) @id
  floorID  String
  roomNo   String
  size     Float   @default(0)
}
```

for the above Prisma schema, after generating the the Prisma client, try running the following code.

```javascript
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const stores = prisma.store.findMany({ take: 10 });
```

## Expected behavior

The query should execute without any error and an array of store objects must be returned as value to the stores constant.

## Prisma information

```prisma
model Store {
  dbID     String  @default(cuid()) @id
  floorID  String
  roomNo   String
  size     Float   @default(0)
}
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 2.0.0
- Node.js version: 14.2.0

**Comment by HumbertoAriza** [comment]
what version of prisma cli do u have?

**Comment by Sytten** [comment]
Most likely you did not update the CLI and thus generated old typing.

**Comment by naveen-bharathi** [comment]
@prisma/cli@2.0.0

**Comment by HumbertoAriza** [comment]
the only think that i cant guess is happening is that you didn't update your prisma client with npx prisma generate after update the version of the cli/prisma.

**Comment by naveen-bharathi** [comment]
But I have run that many times to generate the prisma client. 

Before updating to @prisma/cli@2.0.0, I was on @prisma/cli@2.0.0-beta.7

In beta7 the take argument was working fine. When I updated the version to 2.0.0 and ran `prisma generate`, the take argument was missing.

**Comment by naveen-bharathi** [comment]
Oops!! It was a problem with VS Code. It didn’t use the generated new prisma client until a restart.
