### ISSUE TITLE
Error: P4001 The introspected database was empty: 

### ISSUE THREAD

**Issue by aakashkag** [prisma/prisma#2744]
OS: Ubuntu 19.10
Database: Postgres,
prisma/cli": ^2.0.0
prisma/client": ^2.0.0-beta.8
Node.js version: v12.14.0

Getting following error

Error: 
P4001 The introspected database was empty: 

prisma introspect could not create any models in your schema.prisma file and you will not be able to generate Prisma Client with the prisma generate command.

To fix this, you have two options:

- manually create a table in your database (using SQL).
- make sure the database connection URL inside the datasource block in schema.prisma points to a database that is not empty (it must contain at least one table).

Then you can run prisma introspect again.

**Comment by aakashkag** [comment]
When I created table manually(as option suggested in error) in db then it's working fine.

**Comment by janpio** [comment]
What exactly is the problem here @aakashkag you think we should fix? It seems you had an empty database that you tried to introspect, and the command told you about what is going on and how to fix it. Is that not the optimal outcome?

**Comment by sejr** [comment]
@janpio I am seeing this issue with a database I know is not empty.

**Comment by janpio** [comment]
Can you create a new issue please @sejr?
Please include a dump of the DB if possible and the information if you are sure the user you are using has access to these tables.

**Comment by aakashkag** [comment]
@janpio It's fine for me. I can create  table which solve this issue.
