### ISSUE TITLE
Invalid database connection string leads to strange error message

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2748]
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}
```

```
DATABASE_URL="postgresql://foo:bar@host:sdfsdf/chinook"
```

When running `prisma introspect` I get this error message:

```
C:\Users\Jan\Documents\prisma-chinook-express>npx prisma introspect
Environment variables loaded from ./prisma/.env

Introspecting based on datasource defined in prisma\schema.prisma …
Error: Error in connector: Error querying the database: Error querying the database: The specified database url Error parsing database connection string. is invalid
```

![image](https://user-images.githubusercontent.com/183673/84603219-ff4b4980-ae8c-11ea-9c40-a378df515a7a.png)

**Comment by pantharshit00** [comment]
I can confirm this but the message seems fairly accurate to me.

**Comment by janpio** [comment]
`Error: Error in connector: Error querying the database: Error querying the database: The specified database url Error parsing database connection string. is invalid` sounds like gibberish to me.

More useful would be "Port part of connection string ('sdfsdf') is invalid. Should be numbers only." or any less detailed version of that.

Also no "Error: Error in connector: Error querying the database: Error querying the database:".

**Comment by pimeys** [comment]
Query engine does this right:
```
Error parsing connection string: invalid port number
```
Introspection not.
