### ISSUE TITLE
Add prisma format to the CLI

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#275]
Right now we only expose `prisma-fmt` via the VSCode extension. You should also be able to run it from the prisma CLI

```sh
$ prisma format
```

(also `--schema`)

**Comment by madebysid** [comment]
Oh boy can't wait to use this to finally make a Sublime plugin for Prisma!

**Comment by pantharshit00** [comment]
Same, I will add this to my vim plugin :)
