### ISSUE TITLE
MySQL: Unreachable database host leads to unknown error

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2750]
MySQL with wrong connection string:

![image](https://user-images.githubusercontent.com/183673/84603278-6c5edf00-ae8d-11ea-8440-92d347439b3a.png)

```
C:\Users\Jan\Documents\prisma-chinook-express>npx prisma introspect
Environment variables loaded from ./prisma/.env

Introspecting based on datasource defined in prisma\schema.prisma …
Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: No such host is known. (os error 11001)
```

Expected is more something like with Postgres:

```
C:\Users\Jan\Documents\prisma-chinook-express>npx prisma introspect
Environment variables loaded from ./prisma/.env

Introspecting based on datasource defined in prisma\schema.prisma …
Error: P1001

Can't reach database server at `host`:`123`

Please make sure your database server is running at `host`:`123`.
```

![image](https://user-images.githubusercontent.com/183673/84603303-9fa16e00-ae8d-11ea-97e1-025c0939131e.png)

**Comment by pantharshit00** [comment]
I can confirm this, marking as a improvement: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22195362/84894922-415bd180-b0bf-11ea-875d-367b9c5461f5.png">

**Comment by janpio** [comment]
As this does not follow our error spec this is a bug.
