### ISSUE TITLE
Local environment variable wins against value in `prisma/.env` although CLI says it is reading from file

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2751]
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}
```

`prisma/.env`:
```
DATABASE_URL="postgres://dotenvfile:123/chinook"
```

On `prisma introspect` I get the expected error message:

```
C:\Users\Jan\Documents\prisma-chinook-express>npx prisma introspect
Environment variables loaded from ./prisma/.env

Introspecting based on datasource defined in prisma\schema.prisma …
Error: P1001

Can't reach database server at `dotenvfile`:`123`

Please make sure your database server is running at `dotenvfile`:`123`.
```
![image](https://user-images.githubusercontent.com/183673/84603505-4cc8b600-ae8f-11ea-8192-44a6b1332ed3.png)

---

What is confusing is that when I set `DATABASE_URL` in my actual local environment (in this case on Windows with `set DATABASE_URL=postgres://localenvironment:789`) the error message changes, although the output still says it is reading from that file:

```
C:\Users\Jan\Documents\prisma-chinook-express>npx prisma introspect
Environment variables loaded from ./prisma/.env

Introspecting based on datasource defined in prisma\schema.prisma …
Error: P1001

Can't reach database server at `localenvironment`:`789`

Please make sure your database server is running at `localenvironment`:`789`.
```

![image](https://user-images.githubusercontent.com/183673/84603551-813c7200-ae8f-11ea-88cc-fb97a90fbc57.png)

This is confusing to users (see public Slack https://prisma.slack.com/archives/CA491RJH0/p1592164960079700) and me.

**Comment by pantharshit00** [comment]
Local environment variable winning against the ones defined in the env file is correct behavior. 

But we should remove the misleading log.

**Comment by janpio** [comment]
We should probably even make it explicit that the ENV var was overwritten by the system one.

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
