### ISSUE TITLE
Modify Panic Error message to include solution

### ISSUE THREAD

**Issue by thesunny** [prisma/prisma#2755]
## Problem

Prisma throws this error:

`This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.`

As described in issue <https://github.com/prisma/prisma/issues/2754>

The cause was related to an issue with `@prisma/client`. The error was not fixed with `prisma generate`.

The solution is to `yarn remove @prisma/client` then `yarn add @prisma/client` then `prisma generate`.

In my particular use case several hours were spent:

- Renaming Prisma relations
- Renaming columns in the database and related Prisma schema fields
- Following SQL logs
- Generating Prisma clients

The actual solution was unrelated to the things I was trying. It was not obvious that removing @prisma/client and adding it again was a potential solution.

## Suggested solution

Change the error message to read something like:

`This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic. This may be due to an issue in "@prisma/client". Try removing and and adding "@prisma/client".`

## Alternatives

An alternative would be to not have the issue occur; however, it seems that should be in conjunction with this suggestion to augment the error message.

## Additional context

Related issue https://github.com/prisma/prisma/issues/2754

Also led to finding out parallelism issue with errors https://github.com/prisma/prisma/issues/2753

**Comment by janpio** [comment]
> It was not obvious that removing @prisma/client and adding it again was a potential solution.

Technically this is not a valid solution to your problem - I fear your real problem went away here by accident, and you just concluded that this would be a valid solution.

**Comment by janpio** [comment]
I am going to close this now. Happy to take a look again if we get more information.
