### ISSUE TITLE
Prisma format ignores newlines at the end of files

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#2760]
When running `prisma format` and the schema.prisma file has a newline at the end of a file, it gets removed. This gets annoying when the project you're working on enforces newlines at the end of files and prisma format eliminates them.

My suggestion: add a trailing newline every time, everywhere.

**Comment by mavilein** [comment]
Which version of the plugin did you test? Because this feature is already in place. Just verfied it again in my vs code.

**Comment by steebchen** [comment]
latest 2.1.0 and dev 2.2.0-dev.2, there's no newline at the end of the file:

```
❯ yarn prisma format         
yarn run v1.22.4
$ /Users/prisma/scratchpad/photonjs-example/node_modules/.bin/prisma format
Formatted /Users/prisma/scratchpad/photonjs-example/prisma/schema.prisma in 748ms 🚀
✨  Done in 4.77s.

❯ cat prisma/schema.prisma 
generator photon {
  provider = "prisma-client-js"
}

//datasource db {
//  provider = "sqlite"
//  url      = "file:./dev.db"
//}

datasource db {
  provider = "postgresql"
  url      = "postgresql://postgres:prisma@localhost:5432/postgres?schema=sql_load_test"
}

model User {
  firstName  String
  middleName String
  lastName   String
  @@id([firstName, lastName])
  @@unique([firstName, middleName, lastName])
}% // <- NO \n
```

**Comment by mavilein** [comment]
It's using the same component underneath. If you run `cat -e prisma/schema.prisma` new lines will be shown as `$`.

**Comment by steebchen** [comment]
Yes, and that one is missing for the first line. VS Code is probably adding the newline for you – try to just run `prisma format` without having VS Code open.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
