### ISSUE TITLE
Introspection: Use env vars to override introspection binary with --url --print

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#2773]
## Bug description

`prisma introspect --url <url> --print` doesn't seem to pick up the env var `PRISMA_INTROSPECTION_ENGINE_BINARY` either when it is in environment or via `.env` file 

In my understanding CLI only looks for `.env` file when it is next to a `schema.prisma` file

What is a possible way to replace the binary when a `schema.prisma` file is not present?

## How to reproduce

1. Run `prisma introspect --url <url> --print` with a `.env` file that contains path to a custom binary (e.g. `PRISMA_INTROSPECTION_ENGINE_BINARY`)

## Expected behavior

There should be a way to use custom binaries with `prisma introspect` command when using `--url` option. 

## Environment & setup

```
divyendusingh [reintrospection-ci]$ yarn prisma --version                                                                                    1 ↵
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/reintrospection-ci/node_modules/.bin/prisma --version
@prisma/cli          : 2.0.0
Current platform     : darwin
Query Engine         : query-engine de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/divyendusingh/Documents/prisma/reintrospection-ci/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/divyendusingh/Documents/prisma/reintrospection-ci/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/divyendusingh/Documents/prisma/reintrospection-ci/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/divyendusingh/Documents/prisma/reintrospection-ci/node_modules/@prisma/cli/prisma-fmt-darwin)
✨  Done in 3.46s.
```

**Comment by divyenduz** [comment]
I can confirm that it works when there is a `schema.prisma` file next to the `.env` file. 

It doesn't work when we have just a `.env` file. 

Possible solutions from top of my head: 

1. Pick the .env file in `cwd` 
2. `-e` flag to pass a custom `env` file

**Comment by janpio** [comment]
> Possible solutions from top of my head:
> 
> 1. Pick the .env file in `cwd`
> 2. `-e` flag to pass a custom `env` file

Why? Shouldn't it just work as usual?

**Comment by divyenduz** [comment]
> Why? Shouldn't it just work as usual?

Point 1 would be the implementation to make it work as usual. It is specifically implemented to look for `.env` next to `schema.prisma`, afaik, this is how it was implemented.

**Comment by divyenduz** [comment]
> How about it should just honor the ENV var set in the environment?

Oh yes, it should also do that of course

**Comment by janpio** [comment]
Can you please confirm the fix @divyenduz?

**Comment by divyenduz** [comment]
I can confirm that this is work in dev `2.2.0-dev.33`
