### ISSUE TITLE
Ability to use in progress branches in prisma-engines in Prisma CLI

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2775]
When a PR in prisma-engines is unmerged, it is hard to use the features included there in Prisma CLI. To solve that we would have to build and upload prisma-engines branches as well, and give an option to override the binary hash in the CLI manually. If it is set, the CLI would download the specified binaries instead.

**Comment by thebiglabasky** [comment]
This looks like making sense to also help packaging prototypes of sorts without making them part of a release, or at least be one of the requirements to do so, if I'm interpreting this correctly.

**Comment by janpio** [comment]
Yep, afaik we even used that already for the Union Type changes so we might already be there.

**Comment by timsuchanek** [comment]
Closed in https://github.com/prisma/prisma/issues/3556
