### ISSUE TITLE
WebSocket is closed before the connection is established after deployment 

### ISSUE THREAD

**Issue by khoathanglong** [prisma/prisma#2777]
Hi, I followed the instruction on howtographql.com and everythings works well on the localhost:4000. But when I deploy the server using NOW and change the configuration of "ws" in index.js (react), it throws the error "WebSocket connection to 'ws://https//server-cinzrrdniz.now.sh/' failed: WebSocket is closed before the connection is established."  Any ideas to fix this?

here's the code in index.js `(react)`

`import { ApolloProvider } from 'react-apollo'
import { ApolloClient } from 'apollo-client'
import { HttpLink } from 'apollo-link-http'
import { ApolloLink, split } from 'apollo-client-preset'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { BrowserRouter } from 'react-router-dom'
import {AUTH_TOKEN} from './constants'
import { WebSocketLink } from 'apollo-link-ws'
import { getMainDefinition } from 'apollo-utilities'

const httpLink = new HttpLink({ uri: 'https://server-cinzrrdniz.now.sh/' })
//middleware to send token along with each request
const middlewareAuthLink = new ApolloLink((operation, forward) => {
    const token = localStorage.getItem(AUTH_TOKEN)
    const authorizationHeader = token ? `Bearer ${token}` : null
    operation.setContext({
      headers: {
        authorization: authorizationHeader
      }
    })
    return forward(operation)
  })
  
const httpLinkWithAuthToken = middlewareAuthLink.concat(httpLink)

//create websocket connection

const wsLink = new WebSocketLink({
  uri: `ws://server-cinzrrdniz.now.sh/`,
  options: {
    reconnect: true,
    connectionParams: {
      authToken: localStorage.getItem(AUTH_TOKEN),
    }
  }
});

const link = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query)
    return kind === 'OperationDefinition' && operation === 'subscription'
  },
  wsLink,
  httpLinkWithAuthToken,
)

const client = new ApolloClient({
  link,
  cache: new InMemoryCache()
})

ReactDOM.render(
    <BrowserRouter>
        <ApolloProvider client={client}>
            <App />
        </ApolloProvider>
    </BrowserRouter>,
    document.getElementById('root'));
registerServiceWorker();`

**Comment by divyenduz** [comment]
Does `now` support WS?

`ws://https//server-cinzrrdniz.now.sh/` This URL looks incorrect. Shouldn't it be `ws://server-cinzrrdniz.now.sh/`

Please let me know if this works?
