### ISSUE TITLE
Transition package for npm package `prisma`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2778]
To avoid problems like this one: https://github.com/prisma/prisma/issues/2777

Output could mention that they landed on the Prisma 1 package, and depending on what they want they should use `@prisma/cli` (for Prisma 2) or `prisma1`/`prisma@1` (for Prisma 1).

Can we detect `npx` usage consistently? Then we could use that as input.

**Comment by matthewmueller** [comment]
This is WIP. It's being tracked elsewhere.
