### ISSUE TITLE
Add support for Date scalar (without time component)

### ISSUE THREAD

**Issue by marceloverdijk** [prisma/prisma#2783]
I have a Postgresql `date` column which is mapped to a Prisma `DateTime`.
A  [Postgresql `date` data type](https://www.postgresql.org/docs/9.5/datatype-datetime.html) has not notion of a time, so it would be nice if this could be reflected in Prisma as well.

**Comment by Sytten** [comment]
Just to be clear, that would still be a `DateTime` in JS because there is no concept of `Date`.

**Comment by pantharshit00** [comment]
I think this will be tackled with #446

**Comment by marceloverdijk** [comment]
Thanks for the reference @pantharshit00 ! Let's close this one.

**Comment by AnandChowdhary** [comment]
Hey @pantharshit00, is there any place where this is still tracked? #466 leads to #3447 which is closed since v2.17.0 
but adds DateTime, not Date (without time). Thanks!

**Comment by janpio** [comment]
`Date` is also supported as a native type that you can use to qualify `DateTime`: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#postgresql-6 (example for PostgreSQL)

**Comment by janpio** [comment]
Yes, that is exactly how it is supported right now. The DateTime types expect a `Date` from Javascript.

**Comment by smaspe** [comment]
> Yes, that is exactly how it is supported right now. The DateTime types expect a Date from Javascript.

Why, though? The underlying sql engine can take care of the "is this a date" validation if the value is passed as a string, can't it?

**Comment by janpio** [comment]
"Because that's the way it is" is the best answer I can give for that right now. I am in no way saying that it _should_ be like this, or that this is in any way optimal.
