### ISSUE TITLE
mixing uuid's with strings

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma#2784]
## Bug description

Prisma throws an error when mixing uuid's with plain strings

![image](https://user-images.githubusercontent.com/19697099/84870490-05177980-b09d-11ea-8c84-5f9735035bb5.png)

## How to reproduce

1. Schema

```prisma
model User {
  id Int @id @default(autoincrement())
  values String[]
}
```

2. Add data

```ts
const items = [
  'sample 1 string',
  '7fb1aef9-5250-4cf6-92c7-b01f53862822',
  'sample 3 string',
  '575e0b28-81fa-43e0-8f05-708a98d55c14',
  'sample 5 string',
]

 await prisma.user.create({
    data: {
      values: {
        set: items,
      },
    },
  })
```

Prisma throws the above error (screenshot)

## Expected behavior

It should insert the strings correctly

## Environment & setup

- OS: Debain
- Database: Postgres
- Prisma version: 2.0.0
- Node.js version: 12.17.0

**Comment by pantharshit00** [comment]
I can confirm this issue, thanks for the detailed report.

**Comment by chrisdrackett** [comment]
thanks so much @ryands17!

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
