### ISSUE TITLE
[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.

### ISSUE THREAD

**Issue by nampdn** [prisma/prisma#2787]
**Describe the bug**
Messy log display every 30s seconds.
`[Metrics] No Prisma Cloud secret is set. Metrics collection is disabled.`
<img width="803" alt="screen shot 2018-07-19 at 09 41 17" src="https://user-images.githubusercontent.com/26531658/42918647-d2ff2262-8b38-11e8-90e1-b15323d3371a.png">

**To Reproduce**

**Expected behavior**
Show up a way to setup prisma secret cloud.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 
 - `prisma` CLI: [e.g. `prisma/1.9.0 (darwin-x64) node-v10.4.0`]
 - Prisma Server: [e.g. `1.9.0`]
 - `graphql-cli`, `prisma-binding`, `graphql-yoga`, etc. if applicable

**Additional context**
Prisma is an awesome product. But this messy log make developing experience very bad.

**Comment by morajabi** [comment]
What can we do for now? Any way to set a cloud secret or perhaps bypass it?

**Comment by jonsharratt** [comment]
Would be good to show this message once on startup rather than it happening every 30 seconds or not show it at all. Starts to fill up logs 🙈

**Comment by divyenduz** [comment]
Hey! we are aware of this and we will work on a resolution soon. I will get back with more accurate estimates soon.

**Comment by rimiti** [comment]
This log should be removed, it's not really useful... 😕

**Comment by morajabi** [comment]
@divyenduz Please remove it in the next patch if it's not going to be ready soon :)

**Comment by do4gr** [comment]
Our suggested solution is to only log state changes. This means that we will write a log message only once, if the Cloud Secret is not set.

Does this alleviate your concerns?

**Comment by hardy613** [comment]
@do4gr Thanks for the update!

**Comment by nugoo1** [comment]
Im getting this same error! is there a solution to this?
