### ISSUE TITLE
Default value for relations

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma#2796]
## Bug description

Adding a default value to the relation field still makes it required while adding records. Reference: https://github.com/prisma/prisma/discussions/2716

## How to reproduce

1. Create the schema

```prisma
model Post {
  id        Int     @default(autoincrement()) @id
  authorId  Int     @default(1)
  content   String?
  published Boolean @default(false)
  title     String
  author    User   @relation(fields: [authorId], references: [id])
}



model User {
  id        Int      @default(autoincrement()) @id
  email     String   @unique
  password  String
  name      String?
  posts     Post[]
}
```

2. Run `migrate` and `generate` commands

3. TypeScript will complain if the relation is not provided

```ts
await prisma.post.create({
   title: 'title',
  content: 'content',
   author: { /* this is required */ }
});
```

4. On making the relation optional it works correctly.

```prisma
model Post {
  id        Int     @default(autoincrement()) @id
  authorId  Int?     @default(1)
  content   String?
  published Boolean @default(false)
  title     String
  author    User?   @relation(fields: [authorId], references: [id])
}
```

## Expected behavior

It should connect by default if the relation field has a default value.

## Environment & setup

- OS: Debian
- Database: PostgreSQL
- Prisma version: 2.0.0
- Node.js version: 12.18.1

**Comment by pantharshit00** [comment]
The schema pasted here is incomplete and I don't want to make assumptions about the user side. Can you please also paste the `User` side here as well

**Comment by ryands17** [comment]
Here us the `User` model:

```prisma
model User {
  id        Int      @default(autoincrement()) @id
  email     String   @unique
  password  String
  name      String?
  posts     Post[]
}
```

**Comment by pantharshit00** [comment]
I can confirm the behaviour but I will consider this more of a new feature. 

But still this is still quite important in my opinion so I am going to mark this as a candidate.
