### ISSUE TITLE
Allow to name a composite primary key @@id

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#2798]
## Problem
Currently when defining a composite primary key with `@@id`, it will automatically create a name for you based on the names of the given fields. This name is usually not very pretty (it uses an underscore for example) and might not express what we want.

## Suggested solution
Change the signature of `@@id` to:
```
@@id(_ name: String?, fields: FieldReference[])
```

## Alternatives
Use the currently autogenerated name.

## Additional context
Originally from this issue: https://github.com/prisma/prisma/issues/2329

**Comment by janpio** [comment]
> it will automatically create a name for you based on the names of the given fields

Who is "it" and where does it put that name? Your DB? Postgres or MySQL?

**Comment by janpio** [comment]
This is a duplicate issue of https://github.com/prisma/prisma/issues/4010
