### ISSUE TITLE
Prisma Deploy stuck at Applying changes

### ISSUE THREAD

**Issue by brandonin** [prisma/prisma#2801]
**Describe the bug**
Currently, my User Schema is 
```
type User {
  stripe: [StripeCard!]! @relation(name: "StripeCard", onDelete: CASCADE)
}

type Stripe {
  user: User! @relation(name: "StripeCard", onDelete: SET_NULL)
}
```
I am trying to change it to:
```
type User {
  stripe: [StripeCard!]! @relation(name: "StripeCard", onDelete: CASCADE)
  orders: [Order!]! @relation(name: "Order", onDelete: CASCADE)
}

type Stripe {
  user: User! @relation(name: "StripeCard", onDelete: SET_NULL)
  order: [Order!]! @relation(name: "PurchaseCard", onDelete: SET_NULL)
}

type Order {
  id: ID! @unique
  charge_id: String!
  amount: Int!
  date: Int!
  currency: String!
  card_id: StripeCard! @relation(name: "PurchaseCard", onDelete: SET_NULL)
  customer: User! @relation(name: "Order", onDelete: SET_NULL)
}
```

it is lagging on Prisma Deploy "Applying Changes."

I've tried going back to it's initial state but it is still stalling.

**To Reproduce**
1. Create a schema with the initial state and do a prisma deploy.
2. Update the schema with new order Schema.
3. It should stall on Prisma Deploy.
**Expected behavior**
It should update the fields and create a new type Order.

**Screenshots**
<img width="769" alt="screen shot 2018-07-23 at 1 20 02 pm" src="https://user-images.githubusercontent.com/10239468/43092424-28c823fc-8e7b-11e8-8169-4777fc275b47.png">

**Versions (please complete the following information):**
 - OS: `OS X High Sierra 10.13.5`,
 - `prisma` CLI: prisma/1.6.3 (darwin-x64) node-v8.11.1
 - Prisma Server: `1.11.1`
 - `graphql-cli`, `prisma-binding`, `graphql-yoga`, `graphql-tag`, `graphql-tools

**Comment by brandonin** [comment]
Looks like the problem fixed itself when I did a 
```Prisma Delete```
```prisma init```
Deleted all the files that they gave me. and then a: 
```prisma deploy```

**Comment by marktani** [comment]
Thanks for the report, @brandonin.

Both your first and last datamodel is not deployable, because it lacks the `StripeCard` type.
Please provide the complete "before" and "after" datamodel, so we can look into a reproduction here.
