### ISSUE TITLE
Improve prismagraphql/prisma on docker hub

### ISSUE THREAD

**Issue by nunovieira** [prisma/prisma#2803]
**Describe the content you'd like to see**
The _overview_ of [prismagraphql/prisma](https://store.docker.com/community/images/prismagraphql/prisma) on docker hub has only one sentence. It could explain the purpose of the image and how to use it.
Also, and more important in my opinion, there's no reference to the Dockerfile used to build the image.

**Describe alternatives you've considered**
Just using the [README.md](https://github.com/prismagraphql/prisma/blob/master/README.md) would add more information. But the _overview_ should explain how to use that docker image. The README.md (or other linked documentation) could have information on how to run prisma on docker.
Presenting the Dockerfile is also very important.

**Additional context**
A good example: [phpmyadmin/phpmyadmin](https://store.docker.com/community/images/phpmyadmin/phpmyadmin)

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @nunovieira, I've just updated the [description on Docker Hub](https://store.docker.com/community/images/prismagraphql/prisma) with various information about the common workflows when using Prisma with Docker.
