### ISSUE TITLE
Make new, possibly unstable functionality available but opt in via feature flags

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2807]
Prisma 2.1.0 and other future Prisma versions will bring some new additional API functionality. As it is new, it is only slightly tested via our team and users of our `dev` tag on Npm (`npm install @prisma/cli@dev`). This means that publishing it in 2.1.0 (or other future Prisma versions) directly might lead to wrong expectations from users and disappointment if we indeed did not get it stable enough on the first try.

To work around this problem we want to introduce feature flags for Prisma Client. 

Similar to `--experimental` on the CLI (for `prisma studio` and `prisma migrate`), this will enable us to not include functionality in the default API that all users get on installing Prisma and Prisma Client. (This will also involve auto completion via our generated types and our VSCode extension.)

But it gives us the ability to "hide" new functionality behind a "feature flag" that users can manually opt in to, when they want to help us by testing this functionality and providing valuable feedback via issues or Slack. Via their testing, we can make sure the feature is actually ready for all of our users.

Only when we remove the feature flag, the feature will be considered part of our stable Prisma release and be documented as such.

**Comment by timsuchanek** [comment]
This is implemented in 2.1.0.
