### ISSUE TITLE
@prisma/engine-core's package.json uses a github url for its version of undici

### ISSUE THREAD

**Issue by ssalbdivad** [prisma/prisma#2808]
## Bug description

Using [rush](https://rushjs.io), this prevented me from building my workspace:

![Screenshot from 2020-06-19 18-05-40](https://user-images.githubusercontent.com/10645823/85186722-a43c9c80-b268-11ea-82c9-0141e667c06d.png)

The error message is total nonsense, but I just updated the version [here](https://github.com/prisma/prisma/blob/d4c85178112cc499648b1b096837c1d75e9b1abc/src/packages/engine-core/package.json#L49) from ```mcollina/undici``` to ```1.0.3``` (latest), and it worked fine.

## Environment & setup

- OS: Debian
- Prisma version:  2.0.1
- Node.js version: 12.18.1

**Comment by timsuchanek** [comment]
Fixed in latest version
