### ISSUE TITLE
Cannot export data with "prisma export" (CLI v1.6.2)

### ISSUE THREAD

**Issue by lohazo** [prisma/prisma#2809]
I trying to export my data with command 'prisma export' but I always got this error after several minute of "Downloading nodes...":

"'ECONNRESET': request to http://localhost:4466/novaon-server/prod/export failed, reason: socket hang up"

![image](https://user-images.githubusercontent.com/6048013/43179521-93f428c8-8ffd-11e8-805d-f70521dc8ae3.png)

 - OS: Ubuntu 16.04
 - `prisma` `CLI: prisma/1.6.2` `node-v9.11.1`
 - Prisma server: 1.6

**Comment by divyenduz** [comment]
Can you please share your prisma server version and other relevant fields from the [issue template](https://github.com/prismagraphql/prisma/issues/new?template=bug_report.md)?

**Comment by lohazo** [comment]
Sorry I forgot prisma server version.
- Prisma Server: 1.6
![1__root_app01-autocontent___etc_kubernetes_manifests__ssh_](https://user-images.githubusercontent.com/6048013/43188117-9019e060-901d-11e8-9e72-d3a3965ca83f.png)

**Comment by divyenduz** [comment]
Thanks! Can you upgrade the server to a later version? We are at 1.12 as the latest version.

**Comment by lohazo** [comment]
I've try to upgrade to latest but, there is no docker-compose file for prisma 1.6.
How can i upgrade without deploy new server and move data ?

**Comment by divyenduz** [comment]
You should be able to change the version in your `docker-compose.yml` file and run `docker-compose up -d` again to update without migrating data.

**Comment by lohazo** [comment]
This is docker-compose.yml i use.
`version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: mysecret123
        port: 4466
        databases:
          default:
            connector: mysql  # or `postgres`
            active: true
            host: db
            port: 3306        # or `5432` for `postgres`
            user: root
            password: prisma
  mysql:  # or `postgres`
    container_name: prisma-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma`

I run `docker-compose up -d` and it proceduce this error.
(I'm not familiar with docker)
![1__root_app01-autocontent___srv_autocontent-backend_database__ssh_](https://user-images.githubusercontent.com/6048013/43297086-5df62bcc-9179-11e8-9f36-cdee006be0b2.png)

**Comment by marktani** [comment]
You might find the troubleshooting tips over here useful: https://github.com/prismagraphql/prisma/issues/2835
