### ISSUE TITLE
Support for configuring referential actions (on delete, on cascade) in Prisma Schema Language

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2810]
## Problem
Currently Prisma Schema does not support a way to define cascading deletes. But people want to use that functionality.

## Suggested solution
Define, implement and document a syntax for cascading deletes.

## Alternatives
Set the cascading deletes on the database manually, but that has problems like https://github.com/prisma/prisma/issues/2057

## Additional Information

- Related, but _very_ outdated specs issues: https://github.com/prisma/specs/issues/328
- Related Migrate feature request: https://github.com/prisma/prisma/issues/4711
- Related bug: https://github.com/prisma/prisma/issues/2057
- Some more issues: https://github.com/issues?q=org%3Aprisma+label%3A%22topic%3A+cascade%22

**Comment by jechazelle** [comment]
Do you know when this feature will be release (milestone) ? Thank you ! :-)

**Comment by janpio** [comment]
No, we do no have a release date yet. But we see the 👍 and will take this into consideration. (We actually just talked about it in a meeting, so it really is top of mind for us.)

**Comment by aakashkag** [comment]
Hello Prisma team.
Any plan to fix this issue. It's pending from long time. and very important feature.
Thanks

**Comment by macrozone** [comment]
i also think that is one of the biggest problem right now in prisma (besides missing migrations)

**Comment by Albert-Gao** [comment]
https://paljs.com

This is the community solution

**Comment by geosigno** [comment]
Hello, any update on that feature?

**Comment by thebiglabasky** [comment]
Hi, this is planned, but will likely be tackled once `migrate` has reached a stable state, which is our biggest priority right now. Since cascade delete lean a lot on the schema changes, we preferred to go this way.
That's high on our list though, so stay tuned!

**Comment by himalayaahuja** [comment]
When will `migrate` reach a stable state ?? :(

**Comment by thebiglabasky** [comment]
We're working hard on this, and will release a preview of it today! :)
This will help gather more input to make it fully stable and look into cascading deletes early next year.

**Comment by scriptcoded** [comment]
> We're working hard on this, and will release a preview of it today! :)
> This will help gather more input to make it fully stable and look into cascading deletes early next year.

Where could I find this preview? I can't seem to find anything about it in any release notes or documentation :)

**Comment by RafaelKr** [comment]
> > We're working hard on this, and will release a preview of it today! :)
> > This will help gather more input to make it fully stable and look into cascading deletes early next year.
> 
> Where could I find this preview? I can't seem to find anything about it in any release notes or documentation :)

@scriptcoded he was referencing to the comment of @himalayaahuja saying "When will migrate reach a stable state?".

The Prisma Migrate Preview was anounced here:
https://www.prisma.io/blog/prisma-migrate-preview-b5eno5g08d0b

**Comment by scriptcoded** [comment]
> > > We're working hard on this, and will release a preview of it today! :)
> > > This will help gather more input to make it fully stable and look into cascading deletes early next year.
> > 
> > 
> > Where could I find this preview? I can't seem to find anything about it in any release notes or documentation :)
> 
> @scriptcoded he was referencing to the comment of @himalayaahuja saying "When will migrate reach a stable state?".
> 
> The Prisma Migrate Preview was anounced here:
> https://www.prisma.io/blog/prisma-migrate-preview-b5eno5g08d0b

I see, then I just misunderstood the comment. Let's just keep our fingers crossed for a preview in Q1 then ^_^

**Comment by Sytten** [comment]
Thing is you can already do cascading delete in the schema but the engine forbids you to do it if the relation is required. See my issue https://github.com/prisma/prisma/issues/4650

**Comment by scriptcoded** [comment]
> Thing is you can already do cascading delete in the schema but the engine forbids you to do it if the relation is required. See my issue #4650

I had the same issues as you did, and that's actually what started my hunt through issues, Notion and code to find any traces of the way Prisma handles migrations. Correct me if I'm wrong though, but as far as I'm aware the schema _doesn't_ support cascading deletes. Prisma has a default way of setting up cascades, but there is no way to configure it.

**Comment by Sytten** [comment]
In reality it's not the job of prisma to cascade delete in a SQL database so I am perfectly happy that they don't start handling that, I just want the check that prevents the database from doing its job to be gone. What they meant above is that you can now configure the cascading behaviour of the DB with the new migration system (in like you can change from ON CASCADE DELETE to something else).

**Comment by scriptcoded** [comment]
@Sytten I'm totally on board with that. Prisma shouldn't be handing cascades at all, since it's something that the database can handle on its own perfectly fine. Prisma Schema and Migrate on the other hand _should_, since the whole point of those in conjunction is to define and build the database structure. 

> What they meant above is that you can now configure the cascading behaviour of the DB with the new migration system

As far as I'm aware this is not possible right now, and that's why this issue is still open. Prisma (Migrate) always sets up cascading delete on all relations as it stands right now, which covers most, but not all cases.

**Comment by Sytten** [comment]
@scriptcoded No the new preview does, just switch from the experimental.

**Comment by scriptcoded** [comment]
@Sytten Is that so? I must have missed that. Would you care to share a link to any documentation so that I can read up on the feature?

**Comment by Sytten** [comment]
Probably the migrate doc? https://www.prisma.io/docs/concepts/components/prisma-migrate

**Comment by scriptcoded** [comment]
@Sytten Are we misunderstanding each other? I'm talking about specifying cascades in the schema file, something like `@relation(onDelete: CASCADE)` as in Prisma 1, a feature that [according to the docs](https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/schema-incompatibilities-postgres#cascading-deletes-are-not-supported-in-prisma-2) does not exist in Prisma 2. The link you provided does not mention such a feature.

**Comment by RafaelKr** [comment]
@scriptcoded you can't specify it in the schema, but you can edit it in the migration file after it is created

**Comment by beeman** [comment]
> @Sytten Are we misunderstanding each other? I'm talking about specifying cascades in the schema file, something like `@relation(onDelete: CASCADE)` as in Prisma 1, a feature that [according to the docs](https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/schema-incompatibilities-postgres#cascading-deletes-are-not-supported-in-prisma-2) does not exist in Prisma 2. The link you provided does not mention such a feature.

I think this is what the issue is about, declaratively defining the cascading deletes:

> Currently Prisma Schema does not support a way to define cascading deletes.


A lot of folks using Prisma try to work with a schema-first/schema-only approach. 

While you might go into your DB or Migration to change stuff manually, this is not a very scalable solution as it requires knowledge of the internals of a DB, something that's not needed with the Prisma Schema (and arguable one of it's biggest benefits).

**Comment by macrozone** [comment]
> > @Sytten Are we misunderstanding each other? I'm talking about specifying cascades in the schema file, something like `@relation(onDelete: CASCADE)` as in Prisma 1, a feature that [according to the docs](https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/schema-incompatibilities-postgres#cascading-deletes-are-not-supported-in-prisma-2) does not exist in Prisma 2. The link you provided does not mention such a feature.
> 
> I think this is what the issue is about, declaratively defining the cascading deletes:
> 
> > Currently Prisma Schema does not support a way to define cascading deletes.
> 
> A lot of folks using Prisma try to work with a schema-first/schema-only approach.
> 
> While you might go into your DB or Migration to change stuff manually, this is not a very scalable solution as it requires knowledge of the internals of a DB, something that's not needed with the Prisma Schema (and arguable one of it's biggest benefits).

agree. Prisma is great for when you don't want to worry about dbs at all, which is important for folks that need to create apps fast. Its very impotant therefore that the db can be expressed declarative

**Comment by scriptcoded** [comment]
Perhaps the conversation between me and @Sytten (as well as this comment) should be hidden as it's rather off-topic?

**Comment by thebiglabasky** [comment]
👋 I edited my comment above to avoid confusion: I was indeed talking about the preview of migrate.
This issue is about supporting declaring cascade delete in the Prisma schema so that one doesn't need to manage that separately. The trick to manually edit migration files is a workaround, but it's not planned to use long-term.
We'll keep this issue updated once we prioritized working on it after migrate is stabilized.

**Comment by JVKdouk** [comment]
Any release date?
I need this feature urgently...
I know you guys are working hard for this!

**Comment by thebiglabasky** [comment]
Hi @JVKdouk, as mentioned above, we'll keep this issue updated once we prioritized working on it after migrate is stabilized. In the meantime, since we naturally can't provide a release date, you will need to lean on defining these manually at the database level.
Thanks

**Comment by Sytten** [comment]
@thebiglabasky It would be nice if we could just have a way to disable the checks that prisma does as a temporary solution and let the DB handle it. Because as of right now I have to use raw SQL to delete.

**Comment by ragokan** [comment]
It will be a great feature!

**Comment by andresribeiro** [comment]
Hey guys, I know you are working on a lot of features, but I think this really has to have a high priority. Almost every project, except for a few small ones, needs a cascading delete. It is horrible to have to delete first the relations and then the object itself. Also when we add a new relation we have to be careful not to break a function that deletes something. Again, I know you are very busy, but if you could just post this as 'WIP' and ask the community for help, many developers just like me would help with development

**Comment by MikaStark** [comment]
Can't wait to see this feature released :).

**Comment by premkumar5012002** [comment]
when this feature will available

**Comment by tomhoule** [comment]
Note that there currently is an open proposal for this feature: https://github.com/prisma/prisma/issues/6996

**Comment by tomhoule** [comment]
Feedback on the linked issue is very much wanted

**Comment by pedrovrima** [comment]
In case someone needs a workaround, here is a light package that doesn't require changes your schema:

https://www.npmjs.com/package/prisma-cascade-delete

**Comment by PS1TD** [comment]
Can't wait for this feature to be released. A lot of complex projects rely heavily on proper cascading deletes including mine. It would be awesome to have this built in instead of having to deal with community workarounds. Keep up the great work Prisma team!

**Comment by janpio** [comment]
Quick update in that direction: We are actively working on implementation of the proposal spelled out in https://github.com/prisma/prisma/issues/6996 - so this is happening. If you can take another look at that proposal and leave your feedback, that would be appreciated.

**Comment by Billano** [comment]
@janpio any idea on when will the feature be release? (a rough estime works) btw, thanks!!

**Comment by janpio** [comment]
No ETA, but definitely more weeks than quarters away.

**Comment by janpio** [comment]
Instructions on how to use this, and a place to give feedback: https://github.com/prisma/prisma/issues/7816

**Comment by FlorianWendelborn** [comment]
@janpio FWIW, [the documentation still points to this issue](https://www.prisma.io/docs/guides/database/advanced-database-tasks/cascading-deletes) instead of the feedback issue. Not sure if that’s expected or not so I’m raising it here.

**Comment by cyrus-za** [comment]
Yep @FlorianWendelborn I came to this issue form docs. I see its in preview now on #7816 but there's no instructions on how to use it.

**Comment by pimeys** [comment]
It is available in the dev channel, but is not tested yet by others than us the devs. There's also the documentation effort going on: this will be a breaking change and users need to understand the change properly before we can talk about it more. It is under the previewFeature flag `referentialActions` in the dev channel, but please keep in mind a possible data loss if just updating without first doing a re-introspection and manually going through all relations, changing the action from cascade to restrict if needed.

So, just wait until next Tuesday's release 2.26.0 for docs and info, or if accepting a risk of data loss, you can try the dev channel...

**Comment by janpio** [comment]
This has now been released as a preview feature behind a preview feature flag. You can read about it in the release notes for 2.26.0: https://github.com/prisma/prisma/releases/tag/2.26.0 If you have any feedback, please use this issue: https://github.com/prisma/prisma/issues/7816
