### ISSUE TITLE
ERROR: Whoops. Looks like an internal server error. Search your server logs for request ID: local:management:c

### ISSUE THREAD

**Issue by abdelrahman-mustafa** [prisma/prisma#2813]
[abdelrahmanmustafa@localhost prisma]$ prisma deploy 
Deploying service `default` to stage `default` to server `local` !

ERROR: Whoops. Looks like an internal server error. Search your server logs for request ID: local:management:cjk2fd7hq00020a897e57g4y8

{
  "data": {
    "deploy": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:management:cjk2fd7hq00020a897e57g4y8",
      "path": [
        "deploy"
      ],
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "requestId": "local:management:cjk2fd7hq00020a897e57g4y8"
    }
  ],
  "status": 200
}

**Comment by abdelrahman-mustafa** [comment]
prisma version 1.12.0 
Linux OS Fedora 28 
N

**Comment by divyenduz** [comment]
Can you please share your `datamodel.graphql`, `prisma.yml`, `docker-compose.yml` and if possible, reproduction steps? Thanks!
