### ISSUE TITLE
Could not connect to server at http://localhost:4467

### ISSUE THREAD

**Issue by gijo-varghese** [prisma/prisma#2820]
I've been following the tutorial from https://www.prisma.io/docs/tutorials/setup-prisma/connect-empty-db/postgres-aiy1jewith

After executing command `prisma deploy` it says: 

> Could not connect to server at http://localhost:4467. Please check if your server is running.

**Comment by divyenduz** [comment]
How did you land on the port number `4467`? The default is `4466`, Did you change it?

**Comment by gijo-varghese** [comment]
Already tried `4467`. That wasn't working. So I tried `447`

**Comment by marktani** [comment]
Also, could you share the result of `docker ps`?

**Comment by niba** [comment]
I have the same problem as the author. Yesterday I did "Build a GraphQL server with Prisma" tutorial and everything was working. Today when I try to launch `prisma deploy` I get:

>  prisma deploy

> Error: Could not connect to server at http://localhost:4466. Please check if your server is running.
>     at Deploy.<anonymous> (C:\Users\niba\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-cli-core\src\commands\deploy\index.ts:127:13)
>     at step (C:\Users\niba\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-cli-core\dist\commands\deploy\index.js:42:23)
>     at Object.next (C:\Users\niba\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-cli-core\dist\commands\deploy\index.js:23:53)
>     at fulfilled (C:\Users\niba\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-cli-core\dist\commands\deploy\index.js:14:58)
>     at <anonymous>
>     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
> Exiting with code: 0

the result of `docker ps`

![image](https://user-images.githubusercontent.com/2017454/43667689-5e8702fe-9779-11e8-9d2b-2eab8c5aae49.png)

Starting another project from scratch doesn't help

**Comment by niba** [comment]
I managed to fix the error. It was caused by Docker. When I was restarting my containers using `docker-compose down` and `docker-compose up` I got:

> ERROR: for prisma  Cannot start service prisma: driver failed programming external connectivity on endpoint docker_prisma_1 (a4c15d3b0047c4db18c54aa042eb0a728c53e0775d45802d58e136d8eb6b283f): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:4466:tcp:172.21.0.2:4466: input/output error
> ERROR: Encountered errors while bringing up the project.

Restarting docker service on windows fixed it.
