### ISSUE TITLE
Typo in a Warning message. Should be `nexusPluginPrisma` instead of `nexusPrismaPlugin`

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma#2826]
## Bug description

I had a project I made in Prisma 5-6 months ago & haven’t touched since. I was just trying to update it to Prisma Stable. There is a warning that says:

> Please add experimentalCRUD: true in the nexusPluginPrisma() constructor if you still wish to enable it.

But instead of `nexusPluginPrisma` it should be `nexusPrismaPlugin` I think.

My code is as follows that is working:

```js
const { nexusPrismaPlugin } = require('nexus-prisma')

const schema = makeSchema({
  plugins: [
    nexusPrismaPlugin({
      experimentalCRUD: true,
    }),
  ],
  ...
})
```

Also, curious if this is the way to go or I have to use https://www.nexusjs.org/#/plugins/prisma in the future?

**Comment by pantharshit00** [comment]
Please open this issue here: https://github.com/graphql-nexus/nexus-schema-plugin-prisma

**Comment by deadcoder0904** [comment]
@pantharshit00 Rather than asking that u can transfer it yourself now: https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

Anyways I opened it here https://github.com/graphql-nexus/nexus-schema-plugin-prisma/issues/728

**Comment by pantharshit00** [comment]
I can't transfer cross organizations. That is limitation of github. Otherwise I would have done that
