### ISSUE TITLE
Many-to-many relation with composite ID does not work

### ISSUE THREAD

**Issue by seed-of-apricot** [prisma/prisma#2831]
## Bug description

As written in prisma/vscode#266. Error report id 7962.

## How to reproduce

Create models referencing the other's composite ID.

## Expected behavior

Would work as described [in the doc](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#many-to-many-relations).

## Environment & setup

- OS: Windows 10 x64
- Database: PostgreSQL
- Prisma version: 2.0.1 (cli/client, packaged with nexus-prisma-plugin)
- Node.js version: 14.3.0

**Comment by pantharshit00** [comment]
Please see: https://github.com/prisma/vscode/issues/266#issuecomment-648813871

You need a explicit relation table here. See https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#relation-tables how you can make one

**Comment by seed-of-apricot** [comment]
@pantharshit00 Thank you, I commented back there.

**Comment by pantharshit00** [comment]
Looks like this was resolved in https://github.com/prisma/vscode/issues/266#issuecomment-648813871. I am going to close this
