### ISSUE TITLE
Restarting prisma container 

### ISSUE THREAD

**Issue by caesarbell** [prisma/prisma#2831]
**Describe the bug**
When I run docker-compose up -d and then run docker ps, container id 3da435f9b9af continues to restart based on this output *Restarting (0) 33 seconds ago*. Not sure why it keeps restarting

**To Reproduce**
1. create Prisma project by running docker run -v `pwd`:/usr/src/app -it node:latest /bin/bash -c "npm install prisma -g; prisma init hello-world; cp -a /hello-world/. /usr/src/app" 
2. select create new database 
3. select postgres 
4. run docker-compose up -d 
5. docker ps 
6. docker container constantly restarts 

**Expected behavior**
should be able to run docker-compose exec prisma /bin/bash which should allow me to enter the running container, so I can run prisma deploy. But I am not able to, because the container continues to restart 

**Screenshots**
output for running containers 

postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | 2018-07-30 13:50:11.223 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2018-07-30 13:50:11.223 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2018-07-30 13:50:11.227 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2018-07-30 13:50:11.238 UTC [69] LOG:  database system was shut down at 2018-07-30 13:50:11 UTC
postgres_1  | 2018-07-30 13:50:11.244 UTC [1] LOG:  database system is ready to accept connections
hello-world_prisma_1 exited with code 0
hello-world_prisma_1 exited with code 0
hello-world_prisma_1 exited with code 0
hello-world_prisma_1 exited with code 0
hello-world_prisma_1 exited with code 0

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`

**Additional context**

**Comment by divyenduz** [comment]
Can you please share your `datamodel.graphql`, `prisma.yml` and `docker-compose.yml` files?

**Comment by caesarbell** [comment]
docker-compose.yml

```version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```

**Comment by caesarbell** [comment]
prisma.yml

```endpoint: http://localhost:4466
datamodel: datamodel.graphql```

**Comment by caesarbell** [comment]
datamodel.graphql

```
type User {
  id: ID! @unique
  name: String!
}
```

**Comment by caesarbell** [comment]
The OS I am using `OS X High Sierra` 10.13.6,  using the latest node (ie note:latest) and for the prisma just running the prisma init command. not sure of the CLI version

**Comment by caesarbell** [comment]
the version of prisma i am using is 
```
root@ef4feba9d584:/usr/src/app# prisma --version
prisma/1.12.0 (linux-x64) node-v9.11.1
```

**Comment by mavilein** [comment]
@caesarbell : Can you run docker as `docker-compose up` and then send us the full log output? The portion of the log you provided is missing the server log output unfortunately.
