### ISSUE TITLE
Strange @@relation error message when running prisma generate 

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#2832]
## Bug description

Given this schema

```prisma
generator js {
  provider = "prisma-client-js"
}

datasource pg {
  provider = "postgresql"
  url      = "postgresql://m@localhost:5432/prisma"
}

model Post {
  content   String?
  createdAt DateTime
  id        String      @id
  published Boolean     @default(false)
  title     String      @default("")
  updatedAt DateTime
  author    User?
}


model User {
  email String  @default("") @unique
  id    String  @id
  name  String?
  post  Post[]
}
```

When I run `./node_modules/.bin/prisma generate`, I get the following error:

```
Error: Schema parsing
error: Error parsing attribute "@@relation": The relation field `author` on Model `Post` must specify the `fields` argument in the @relation directive.
  -->  schema.prisma:17
   |
16 |   updatedAt DateTime
17 |   author    User?
18 | }
   |
```

## Expected behavior

I think I need to add `@relation(fields:[id])` directive, but this error has thrown me off.

## Environment & setup

- OS: OSX
- Database: Postgres
- Prisma version: "@prisma/cli": "2.1.0",
- Node.js version: v12.16.1

**Comment by pantharshit00** [comment]
I can reproduce this. I agree we should improve the error message here.

**Comment by mavilein** [comment]
The easiest fix for this is probably running `prisma format` which will add the missing automatically. So maybe we should suggest that.

**Comment by matthewmueller** [comment]
Yah, I think suggesting that is a good idea. I'd also just remove the line about `@@relation`, that seems unrelated.
