### ISSUE TITLE
Supporting querying distinct rows

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma#2835]
## Problem
Whenever selecting rows using `findMany`, there is no way to remove duplicates from the result set as a raw SQL query using `SELECT DISTINCT` would. This prevents benefiting from performance gains whenever querying a subset of fields or denormalized data.
The current workaround is to select all rows including duplicates, and proceed with programmatically filtering the set afterwards which is resulting in poor performance and additional burden.

## Suggested solution
Expand the API to add support for a `distinct` function, which would translate into a `SELECT DISTINCT` query at engine level.

Example:
```ts
const values: string[] = await prisma.post
  .findMany()
  .distinct({ title: true })
  .title()
// Would translate to "SELECT DISTINCT title from POSTS" and return the list of distinct post titles

type SubSet = { published: boolean; title: string }
const values: SubSet[] = await prisma.post
  .findMany()
  .distinct({ published: true, title: true })
// Would translate to "SELECT DISTINCT published, title from POSTS" and return the list of distinct combinations of post publishing dates and titles
```

## Wouldn't need support in first iteration

Postgres supports a `DISTINCT ON` which could be excluded for now as being provider-specific.

Support for **nested select distinct** could also be postponed depending on complexity.
Considering:
```ts
const result = await prisma.user.findOne({
  where: { id: 1 },
  include: {
    posts: {
      select: {
        published: true,
        title: true,
      },
    },
  },
})
```
we could evaluate proposing:
```ts
const result = await prisma.user.findOne({
  where: { id: 1 },
  include: {
    posts: {
      selectDistinct: {
        published: true,
        title: true,
      },
    },
  },
})
```

## To be defined

- [x] Detail the API surface design (TypeScript)
- [x] Define the translated engines query/queries
- [x] Produce documentation update

## Alternatives
Leave as is.

## Additional context
Mentioned here as well #971

**Comment by timsuchanek** [comment]
The resulting API will look like this:

```ts
const result = await prisma.user.findMany({
  where: {},
  distinct: ['id', 'email']
})
```

It can be enabled by providing the feature flag `distinct` in the schema like so:

```prisma
generator client {
  provider = "prisma-client-js"
  experimentalFeatures = ["distinct"]
}
```

This is already available in the latest dev version: `@prisma/client@dev`

**Comment by chriszrc** [comment]
@timsuchanek According to the docs, this distinct feature doesn't actually generate a distinct query, but filters the result set programmatically. This isn't a great option when there are thousands of records. Is there an open feature request for generating true distinct queries?

https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing#distinct-under-the-hood

**Comment by kibertoad** [comment]
@janpio I've created #14765
