### ISSUE TITLE
Support selections using basic aggregations

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma#2838]
## Problem
As of today, Prisma only allows selecting aggregations using [`count`](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud#count) but doesn't allow for the other basic aggregations listed below:
* `SUM`
* `MIN`
* `MAX`
* `AVG`

Putting it in the context of someone building an application involving products, this prevents from implementing use cases like computing an average rating for products, getting the minimum or maximum price of a set of products, getting the sum of an invoice based on its individual line items' prices...

The workaround is to select the entire dataset and perform the aggregation at application level, which can turn into poor performance.

Note: this problem is separate from the ability to use an aggregation within a where clause (e.g. selecting products which have an average rating >= 4) which should be approached separately.

## Suggested solution
Provide similar functions like `count`, following the same behavior, for `SUM`, `MIN`, `MAX`, `AVG`.
This would come with the same limitations:
* No support for Group By (cf. prisma/prisma-client-js#1)
* No support in filter conditions
* No combination with `distinct`

## Next steps

- [x] Define the final API surface definition
- [x] Define the internal query engine implementation
- [ ] Provide documentation examples

## Alternatives

prisma/prisma-client-js#5 attempts to solve the problem more broadly with a generic `aggregate` approach. This could be considered whenever looking at filter conditions or field selection

## Additional context
N/A

**EDIT:** removed MEDIAN as not being evenly supported by database providers.

**Comment by dpetrick** [comment]
Note: `median` doesn't exist as a simple, straight-forward aggregate on all databases and will not be in the API.

**Comment by timsuchanek** [comment]
This is implemented in `dev` - you can have a look in https://github.com/prisma/prisma/blob/master/src/packages/client/src/__tests__/runtime-tests/aggregations/index.js to see how to use this feature

**Comment by janpio** [comment]
This has been released with [2.2.0](https://github.com/prisma/prisma/releases/tag/2.2.0) and can be tested this way:

```prisma
generator client {
  provider = "prisma-client-js"
  experimentalFeatures = ["aggregateApi"]
}
```

Then you have a new API abailable:

```
const result = await prisma.user.aggregate({
  where: { age: { gt: 5 } }, // optional
  count: true,
  avg: {
    age: true,
  },
  max: {
    age: true,
  },
  min: {
    age: true,
  },
  sum: {
    age: true
  }
})
```

Please let us know if this works for you and if we can promote this feature to production.

**Comment by deadcoder0904** [comment]
@janpio Was wondering why my aggregations aren't working. I tried `experimentalFeatures` & it gave a warning `Error: Schema parsing Invalid feature flag: aggregateApi`.

Then checked Prisma's version using `npx prisma -v` & it turned out `nexus` is using an old version of `prisma` ,i.e, v2.1.3.

Any way I can use v2.2.0 or do I have to wait for a `nexus` release?

**Comment by thebiglabasky** [comment]
Indeed, nexus needs to release an update to incorporate the new version.

**Comment by deadcoder0904** [comment]
Aah, wish they would've not combined packages then as this will happen every time `prisma` releases new features :(

**Comment by pantharshit00** [comment]
You can use yarn resolution if you want to use the latest version right now. 

Read more about it here: https://nexusjs.org/meta/architecture#dependency-philosophy
