### ISSUE TITLE
EPIC: Provide binaries for FreeBSD 12

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#2841]
At least the last two stable versions:

- 12 (latest stable)
- 11 (previous stable)

The thing about BSDs is you very often can't run binaries built for other major version than yours. The good thing about it is the operating system itself provides things like SSL, so our matrix here is the two different major versions.

Subtickets:
- CI should build the binaries. (https://github.com/prisma/prisma-engines/issues/852)
- The client should download the right binary. (https://github.com/prisma/prisma-client-js/issues/752)

Related issue: https://github.com/prisma/prisma/issues/2288

**Comment by dpetrick** [comment]
Preliminary investigation showed that 12 is doable, but I'm unable to get a cross compile image working for 11.

**Comment by pimeys** [comment]
Then I'd say we just do latest stable!

**Comment by pimeys** [comment]
@judehunter Do you want to provide some more context. Would only a build for FreeBSD 12 be enough?

**Comment by judehunter** [comment]
@pimeys I'm rocking v11 so that won't work for me (and I can't upgrade). However, don't let me alone be the reason for you to spend hours on trying to get it to work!
Nevertheless, I would love to see it, because, from my experience, many hosting providers don't use the latest stable and settle on the previous instead.

**Comment by pimeys** [comment]
If you can help @dpetrick here how we could easily implement a cross-compilation pipeline for the Rust binary to our CI (some docker image maybe), that would be super!

It's easy-ish for 12-RELEASE, but not that much for 11-RELEASE...

**Comment by dpetrick** [comment]
I successfully cross compiled working FreeBSD 12 binaries using this image: https://github.com/prisma/engine-images/blob/master/cross/freebsd12.Dockerfile

Unfortunately, my experiments with FreeBSD 11 were not successful (gcc compilation, among other things, failed). I have to drop this for now for more urgent matters.

I encourage anybody willing to give it a shot to take the linked image, change the sources to 11 and just get it to build successfully. The integration work on our side is minimal and can be done ad-hoc.

**Comment by janpio** [comment]
As FreeBSD 11 is more complicated, I split it into a new issue: https://github.com/prisma/prisma/issues/3091

This one will now only cover FreeBSD 12 in both Engines and Client and can be closed when that works.

**Comment by mavilein** [comment]
Just chatted with @dpetrick . This is already done.

**Comment by timsuchanek** [comment]
This is done in the latest dev version - you can check it out in `2.5.0-dev.8`

**Comment by janpio** [comment]
Unfortunately we had to undo this as described in https://github.com/prisma/prisma/issues/3558: We do not build binaries for FreeBSD 12 and provide them for download automatically any more. Please see https://github.com/prisma/prisma-engines#building-prisma-engines and https://www.prisma.io/docs/understand-prisma/under-the-hood#using-custom-engine-binaries how to build and then use a custom binary.
