### ISSUE TITLE
Re-introspection error for renamed relations when there are multiple relations to the same table

### ISSUE THREAD

**Issue by kennytraction** [prisma/prisma#2844]
## Bug description
If you have a table that has two fields that reference the same parent table, re-introspection will throw an error if you manually rename the relations in the Prisma schema. This happens when using the `--experimental-reintrospection` flag.

See error report 8063.

## How to reproduce
Given two tables employee and schedule. The schedule table has two fields that both reference the employee table. 
```
CREATE TABLE "employee" (
"id" uuid NOT NULL DEFAULT uuid_generate_v4(),
"name" varchar(40),
PRIMARY KEY ("id")
);

CREATE TABLE "schedule" (
"id" uuid NOT NULL DEFAULT uuid_generate_v4(),
"morningEmployeeId" uuid NULL REFERENCES "employee" ("id"),
"eveningEmployeeId" uuid NULL REFERENCES "employee" ("id"),
"name" varchar(40),
PRIMARY KEY ("id")
);
```

Initial introspection works fine and will create the models below:
```
model employee {
  id                                            String     @default(dbgenerated()) @id
  name                                          String?
  schedule_employeeToschedule_eveningEmployeeId schedule[] @relation("employeeToschedule_eveningEmployeeId")
  schedule_employeeToschedule_morningEmployeeId schedule[] @relation("employeeToschedule_morningEmployeeId")
}

model schedule {
  eveningEmployeeId                             String?
  id                                            String    @default(dbgenerated()) @id
  morningEmployeeId                             String?
  name                                          String?
  employee_employeeToschedule_eveningEmployeeId employee? @relation("employeeToschedule_eveningEmployeeId", fields: [eveningEmployeeId], references: [id])
  employee_employeeToschedule_morningEmployeeId employee? @relation("employeeToschedule_morningEmployeeId", fields: [morningEmployeeId], references: [id])
}
```
If you rename either of the relations in the employee model, re-introspection will fail with an unexpected error. For example:
```
model employee {
  id                                            String     @default(dbgenerated()) @id
  name                                          String?
  eveningSchedules                              schedule[] @relation("employeeToschedule_eveningEmployeeId")
  schedule_employeeToschedule_morningEmployeeId schedule[] @relation("employeeToschedule_morningEmployeeId")
}
```
Manually renaming the relation fields in the schedule model works as expected and re-introspection keeps the modified name.

## Environment & setup

- OS: Windows
- Database: PostgreSQL
- Prisma version: "@prisma/cli": "2.1.1"
- Node.js version: 12.16.1

**Comment by pantharshit00** [comment]
I can reproduce this. Thanks for the detailed steps:
![image](https://user-images.githubusercontent.com/22195362/86103499-79f5a500-bada-11ea-9290-6e7bb3a2be6b.png)


Report id 8329 for internal use(https://prisma-errors.netlify.app/report/8329)
