### ISSUE TITLE
Prisma query annotation for multi-tenant applications

### ISSUE THREAD

**Issue by florianmartens** [prisma/prisma#2851]
## Problem
Multi-tenant solutions that share one database have become quite popular. However, this requires the ability to enforce strong isolation at the application level. Currently, no node ORM addresses this issue. 

## Suggested solution
The ability to annotate all queries for a model. The annotated model would become a TenantModel and queries like e. g. `findOne()` and `find()` are automatically annotated with an additional where condition e. g. `findOne({ where: { tenantId } })`

This would require all query methods to additionally call a method that can be overwritten like `getQueryset()` or `getQuery()`

**Comment by pantharshit00** [comment]
Please checkout https://github.com/errorname/prisma-multi-tenant which implements some of these features.

**Comment by matthewmueller** [comment]
I think this is a duplicate of #1187 ?

**Comment by pantharshit00** [comment]
Yeah, I am going to close this as a duplicate of #1187
