### ISSUE TITLE
Support Oracle DB

### ISSUE THREAD

**Issue by kanso-git** [prisma/prisma#2853]
## Problem
Support to Oracle db

**Comment by jeveloper** [comment]
+1

**Comment by YElyousfi** [comment]
I noticed that MSSQL is currently a preview feature for Prisma. Is there any timeline for Oracle support?

**Comment by gerwinbrunner** [comment]
+1

**Comment by Gnilherk** [comment]
+1

**Comment by nat-me** [comment]
+1

**Comment by rizkyramadhan** [comment]
We need this support, and willing to pay for it. Can we setup bounty to accelerate this development ?

**Comment by joseviniciusnunes** [comment]
+1

**Comment by chadelofson** [comment]
+1

**Comment by pimeys** [comment]
The biggest problem I see is there's no Rust crate for Oracle that fits well to the current async/await ecosystem (that I know of). Of course we can do it ourselves as we did with SQL Server. The problem with Oracle are the legal issues of building a client from scratch. You can link to their C library with ffi and that is ok for them, but need a permission to do your own library.

The thing why I don't like binding to C from rust is the possibility of memory bugs that are really nasty to solve. So a good way to get this forward is to get some people to write a modern asynchronous Oracle crate for Rust. That's about 40% of the work, then it's about integration from there on.

**Comment by hinogi** [comment]
What about letting users use for example `oracledb` to make the connection on their own?

**Comment by rizkyramadhan** [comment]
There is MIT licensed crate that support executing SQL against oracle using OCI:
https://docs.rs/oci_rs/

Maybe we can wrap it with tokio ?

**Comment by hinogi** [comment]
> 

Guess you then have to check what the Oracle Call Interface license is.

**Comment by rizkyramadhan** [comment]
Quick googling results: 
  - https://en.wikipedia.org/wiki/Oracle_Call_Interface#OCI-based_libraries
  - http://vrogier.github.io/ocilib/

OCILIB is apache licensed and I think it's been around for a while. It encapsulates OCI (Oracle Call Interface), so I think if we create this lib, we can license it similar to OCILIB.

**Comment by joseviniciusnunes** [comment]
I'm interested in helping, what are the steps to integrate the prism with this client made by oracle itself?

https://www.npmjs.com/package/oracledb

**Comment by rizkyramadhan** [comment]
> I'm interested in helping, what are the steps to integrate the prism with this client made by oracle itself?
> 
> https://www.npmjs.com/package/oracledb

I think, the changes should be made on rust side of prisma, and then make sure everything on js side play nice with it...

**Comment by chadelofson** [comment]
I would be interested in helping get this driver done

**Comment by drodsou** [comment]
This would be a much appreciated feature, specially given the free availability of Oracle DBs in the cloud: https://www.oracle.com/cloud/free/#always-free

**Comment by hinogi** [comment]
Maybe just add support for oracle db here for the SQL Query AST and Visitor
https://github.com/prisma/quaint
@joseviniciusnunes @rizkyramadhan @chadelofson

**Comment by hinogi** [comment]
+1

**Comment by charleaux** [comment]
+1

**Comment by hinogi** [comment]
> Prisma raises $40M

Ok can we have a oracle connector now?

**Comment by betopompolo** [comment]
+1

**Comment by derSoerrn95** [comment]
+1

**Comment by leomangueira** [comment]
Is there any prediction of when oracle support will come out?

**Comment by hinogi** [comment]
> Is there any prediction of when oracle support will come out?

When Oracle DB becomes open source :D

**Comment by jifbrodeur** [comment]
+1

**Comment by kelemenbalazs** [comment]
+1

**Comment by kxm827** [comment]
Really bummed to see there's no Oracle support for this, unfortunately, it's a deal breaker and our current use case.

**Comment by hinogi** [comment]
I think it is just a business decision. Which I do understand.

https://github.com/prisma/prisma/discussions/15714

**Comment by jeveloper** [comment]
> Really bummed to see there's no Oracle support for this. Unfortunately, it's a deal breaker for our current use case.

Hey there, I've been following this thread for over 2 years. 
Business question fo you and others interested.

What if I ran a small team to build the support for oracle but charge an annual fee for it? Would you commit? 
Cheers

**Comment by hinogi** [comment]
> > Really bummed to see there's no Oracle support for this. Unfortunately, it's a deal breaker for our current use case.
> 
> Hey there, I've been following this thread for over 2 years. Business question fo you and others interested.
> 
> What if I ran a small team to build the support for oracle but charge an annual fee for it? Would you commit? Cheers

There where already people who offered to make it happen but it is closed source so nobody can.

**Comment by leomangueira** [comment]
correct me if I'm wrong, but I believe that the problem is not why oracle is closed, because while prism does not approve oracle, typeorm and knex have already done that.

**Comment by hinogi** [comment]
I meant the prisma connector api

**Comment by agustindev** [comment]
+1

**Comment by agustindev** [comment]
I can help with the support too

**Comment by koka0012** [comment]
If needed I can allocated a part of my team to help creating this connector.

**Comment by sheen4n** [comment]
Reviving this, does anyone what are the things that we can do to make this connector a reality?

I am sure tons of people are willing to help

**Comment by nicholasvperry** [comment]
I agree and would love to see Oracle support. But for those who are looking for something until it does work, oracledb works very well.

**Comment by viniciussantos45** [comment]
+1

**Comment by vinnicius-martins** [comment]
+1

**Comment by JaffParker** [comment]
Indicating support as well. I'm not an Oracle professional, I've been forced into it by the institute I work for. I'd love to abstract it as much as possible.

**Comment by vancerbtw** [comment]
Is there any formal headway being made on this now?

**Comment by gvenzl** [comment]
Hi all,

I am the Oracle Database Product Manager and working for Oracle.
Thanks all for expressing your interest in having Oracle Database support for this great project.
I too would like to see Prisma support for Oracle Database.

Although I do not fully understand the architecture of Prisma, please forgive my lack of awareness, we do offer a [fully open-source JavaScript driver](https://www.npmjs.com/package/oracledb) and [fully open-source C bindings for our C-based (Oracle Call Interface) drivers, called ODPI-C](https://odpi-c.readthedocs.io/en/latest/user_guide/installation.html).

These C bindings (ODPI-C) are the same that are used for the [open-source, community-built Rust driver oracle](https://docs.rs/oracle/latest/oracle/).

Furthermore, the required C driver libraries are available for free as a package called the [Oracle Instant Client](https://www.oracle.com/database/technologies/instant-client.html) which is licensed under Oracle's [Free Use Terms and Conditions](https://www.oracle.com/downloads/licenses/oracle-free-license.html).

Last but not least, there is also a free-to-use Oracle Database variant called `Oracle Database Free`, which is also licensed under the same Free Use Terms and Conditions.
You can quickly pull a Docker image of that Oracle Database Free image via [`docker pull gvenzl/oracle-free:slim`](https://hub.docker.com/r/gvenzl/oracle-free).

With all that information laid out, are there still any technical or licensing obstacles that would prevent Oracle Database support for Prisma?

Thanks,

**Comment by janpio** [comment]
No, that sounds good. 

Would you say the Rust driver is stable and mature enough to support the full relevant feature set?

Now of course someone "only" has to add an Oracle-compatible SQL dialect to Prisma (provider `oracle` would be the obvious choice), implement the Introspection queries, generation of Migration SQL, and of course all the SQL to run the possible queries from Prisma Client.

**Comment by JaffParker** [comment]
@janpio would you accept contributions despite it not being on your roadmap? It's pretty important for a few, I'm sure we'd chip in.

**Comment by janpio** [comment]
Sure, the code is all on GitHub, so if you can figure it all out, we are willing to either review the PRs at the end or help how to set up a fork that could add support for this new provider.

**Comment by gvenzl** [comment]
> Would you say the Rust driver is stable and mature enough to support the full relevant feature set?

Yeah, the Rust driver that I've linked above is stable and mature. We know the developers, and they are doing great work there. And I'm sure that in the unlikely event that we were to find anything, we could also report any issues to the driver team there and ask them for a fix in a true open-source community spirit.

To @JaffParker's point and earlier comment, a few people here have stated interest in helping to add Oracle Database support, e.g., @joseviniciusnunes, @chadelofson, @agustindev, @koka0012

And I, of course, am willing to provide answers, clarity, and help wherever possible.

**Comment by alexiuscrow** [comment]
👀

**Comment by ThorstenMewesSPK** [comment]
Hi all, just discovered this while searching the web for a reliable oracle orm solution. Would reallly love to see this come to live! We could provide help with generating oracle dialect and sql syntax as requested by @janpio:

> Now of course someone "only" has to add an Oracle-compatible SQL dialect to Prisma (provider `oracle` would be the obvious choice), implement the Introspection queries, generation of Migration SQL, and of course all the SQL to run the possible queries from Prisma Client. Right now that is not on our roadmap.

**Comment by leonardoRocchini** [comment]
It would be great to have an oracle Prisma adapter. There are updates?

**Comment by phabreeze** [comment]
any update on this adapter?

**Comment by janpio** [comment]
No updates or concrete plans right now. This issue is just here to track the demand for this via 👍 reactions to the original issue text.

**Comment by lroal** [comment]
An alternative ORM that supports Oracle is https://github.com/alfateam/rdb

**Comment by hinogi** [comment]
Well there are other ORMs that support oracle, good old typeorm has also support for oracledb. More modern query builder lack support for oracle most of the time.

**Comment by CHSchuepfer** [comment]
Yeah, moved on as well. Just forgot the remove the notification.

**Comment by cjbj** [comment]
One note that may not be known by the non-Oracle user is that node-[node-oracledb 6](https://medium.com/@sharad-chandran/usher-in-a-new-era-with-the-node-oracledb-6-0-pure-javascript-thin-driver-e10e2af693b2) by default is pure JavaScript and is fully open source.  This makes installation and use trivial.  Optional, advanced DB features are available if Oracle Instant Client / Oracle Client is additionally installed with node-oracledb but most users don't need them.

**Comment by maouknayo** [comment]
is there anything new?

**Comment by anandsubbu007** [comment]
any update on this?

**Comment by nilsdacke1** [comment]
Any progress?

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Comment by hinogi** [comment]
4,5 years of asking to oracle support to be implemented or enabling others to implement is clearly not enough to show the importance.

**Comment by hinogi** [comment]
Just to carry over something from discussion https://github.com/prisma/prisma/discussions/15714

https://youtu.be/RAoXdyI_PH4?t=911

**Comment by rizrmd** [comment]
Honestly npm ecosystem sucked for oracle. @hinogi  If I may ask, what do you currently to query oracle ?

**Comment by hinogi** [comment]
since I am not using prisma, I use TypeORM

**Comment by hinogi** [comment]
well typeorm also uses the oracledb client

**Comment by CleilsonAndrade** [comment]
+1

**Comment by catalin2-ctrl** [comment]
So is there any chance that PRISMA to support in 2026 Oracle DB? If not is there a work around, used by someone, in adition to Prisma to have also Oracle supported? (e.g. in paralel with Prisma to use Typeorm? ...or can Typeorm replace Prisma in a project without rewriting my app completely ...or: please help ! ..any ideea will be much appreciated, tks.

**Comment by cjbj** [comment]
It's still under investigation on our (Oracle) end, but whether Prisma accepts a contribution is an unknown.

**Comment by OrionWambert** [comment]
:) +1

**Comment by Himanshu9271** [comment]
+1

**Comment by risalfajar** [comment]
@cjbj is there any update on your team investigation? Or maybe you could also consider sponsoring Drizzle?
