### ISSUE TITLE
Introspection doesn't add or loses trailing new line of schema file

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2854]
## Bug description

When I use [`--experimental-reintrospection`](https://github.com/prisma/prisma/issues/2829#issuecomment-649044648) the trailing new line that I had in my schema file was removed:

```diff
C:\Users\Jan\Documents\throwaway\reinstrospection>git diff
warning: LF will be replaced by CRLF in prisma/schema.prisma.
The file will have its original line endings in your working directory
diff --git a/prisma/schema.prisma b/prisma/schema.prisma
index 4042677..a304d00 100644
--- a/prisma/schema.prisma
+++ b/prisma/schema.prisma
@@ -36,4 +36,4 @@ model User {
   profile Profile?

   @@map("users")
-}
+}
\ No newline at end of file
```

![image](https://user-images.githubusercontent.com/183673/85767492-5ae0c700-b718-11ea-979e-25169e17fd9a.png)

## How to reproduce

Follow https://github.com/prisma/prisma/issues/2425#issuecomment-649709485

## Expected behavior

Trailing new line is kept.

## Prisma information

@prisma/cli          : 2.1.1

**Comment by pantharshit00** [comment]
Same is true for introspection itself. Introspection doesn't add the trailing space.


I tested it out with `2.2.0-dev.15`
