### ISSUE TITLE
Table of ids in Nexus

### ISSUE THREAD

**Issue by TomasMoskala** [prisma/prisma#2859]
## Problem
Cannot have a table of ids with 1 column only referencing id from another table
It creates an empty 
input table_nameUpdateManyDataInput
Which results in errors

## Suggested solution
No clue

## Alternatives
No clue

## Additional context
none

**Comment by pantharshit00** [comment]
@TomasMoskala Please open this issue https://github.com/graphql-nexus/nexus. I can't transfer issue across orgs so you will need to manually recreate it again there.
