### ISSUE TITLE
Re-Introspection is not retaining enum class names

### ISSUE THREAD

**Issue by theneshofficial** [prisma/prisma#2861]
Changes made to enum class name are not retaining when run re-Introspection

I made changes to my enum class name from ```enum user_role``` to ```enum userRole```. Everytime i run introspect it's changing back to ```enum user_role```. I expect it to retain as ```enum userRole```.

## Changes made
```
enum userRole {
  READER
  SUPER_ADMIN
  ADMIN
  EDITOR
}
```

## Re-Introspection output
```
enum user_role {
  READER
  SUPER_ADMIN
  ADMIN
  EDITOR
}
```

## Expected behavior
Retain the changes made to enum class name.

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Prisma version: 2.1.1
- Node.js version: v14.4.0

**Comment by janpio** [comment]
Wouldn't just changing the name mean that you also need to change that in your database?
Have you tried using `@@map` on the enum to keep the connection to the name in the db? (see the last example at https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/data-model#examples-7)

**Comment by theneshofficial** [comment]
Hi @janpio 

> Wouldn't just changing the name mean that you also need to change that in your database?

I'm not changing any fields or table names being reffered on DB. I'm just changing the enum model name which is being referred by another model on Prisma level. Below are the example of schema generated through introspection and the changes I made which I would like to retain with every re-introspection.

## Prisma Introspect Generated Models
```
model user {
  email                String         @unique
  id                   Int            @default(autoincrement()) @id
  name                 String
  role                 user_role       @default(READER)
  username             String         @unique
}

enum user_role {
  READER
  ADMIN
  EDITOR
}
```

## Custom Changes
```diff
model user {
  email                String         @unique
  id                   Int            @default(autoincrement()) @id
  name                 String
- role                 user_role      @default(READER)
+ role                 userRole       @default(READER)
  username             String         @unique
}

- enum user_role {
+ enum userRole {
  READER
  ADMIN
  EDITOR
}
```

Those are the custom changes I would like to retain as well. Currently it's being override by prisma with every re-introspection.

**Comment by janpio** [comment]
Can you try this?

```
model user {
  email                String         @unique
  id                   Int            @default(autoincrement()) @id
  name                 String
  role                 userRole       @default(READER)
  username             String         @unique
}

enum userRole {
  READER
  ADMIN
  EDITOR

  @@map("user_role")
}
```

That should tell Prisma to use the `user_role` enum internally on the database level - and I assume Re-Introspection would also already support that.

**Comment by theneshofficial** [comment]
Hi @janpio, that worked. Thank you.
