### ISSUE TITLE
gRPC for service to service communication

### ISSUE THREAD

**Issue by bazaglia** [prisma/prisma#2862]
This was started by a conversation with @schickling. Existing related issue: #1921.

Well my architecture is really really similar to [this one by Workpop](https://medium.com/open-graphql/graphql-bindings-for-service-to-service-communication-d1e89df66ecd).

But my application business is really complex and sometimes in a single request to the graphql gateway, a service call another one and this call sequence can cause an overhead. While internal http requests with graphql binding is simple, if may have performance cons in many situations.

I don't know if it matches Prisma goals, but the ideal to me is something like still using GraphQL only as a gateway (matching google's [rejoiner](https://github.com/google/rejoiner) approach) and Prisma as a database adapter, but internal services would be gRPC services, and the goal here is to get the get the query AST and pass it to a data abstraction layer (prisma), which would make a performatic query to the database.

**Comment by lilac** [comment]
I like this idea. It is more elegant than graphql as a database abstraction layer.
