### ISSUE TITLE
Add `nodes` field to query multiple objects with unknown type

### ISSUE THREAD

**Issue by Yogu** [prisma/prisma#287]
I'd like to suggest a new field `nodes` on both simple and relay schema's root query types which is just the `node` field in plural form. This could be used to query multiple objects just knowing their id and not their type, then using fragments to distinguish by type.

### Suggested API

```graphql
type Query {
    nodes(ids: [ID!]!): [Node]!
}
```

The result array contains exactly as many items as ids passed in as argument. IDs without existing objects are mapped to `null`. If ids are duplicated, they are duplicated in the result set.

### Use Cases

* Generic references to objects: A user task, issue, ... may be associated with business objects in a generic way. The simplest solution is to store a list of object ids in the user task.
* Abstraction from the graph.cool API: A `nodes` API is much simpler than the `all...` fields with their filters. Thus, objects can be retrieved in a generic way, only knowing the type and ids, via `nodes(ids: $ids) { ...on User { name, role } }`

On could use the `node` field and alias it multiple times once for each id. However, this bloats up the query and is not possible at all if the query needs to be static.

**Comment by sorenbs** [comment]
I think this would be a valuable addition. It's worth noting however that Relay Modern does not rely on the `node` field: https://github.com/facebook/relay/issues/1727
