### ISSUE TITLE
Offline support for GraphiQL

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma#2872]
Basically my internet went off & I couldn't load GraphiQL. It uses some CDN location. Would love to have it bundled.

Not sure if this is the correct repository so lmk :)

**Comment by pantharshit00** [comment]
Please open this issue here: https://github.com/graphql-nexus/nexus if you are using nexus.

Otherwise, open the issue here: https://github.com/prisma-labs/graphql-playground


Prisma doesn't ship with a playground so this is irrelevant here.
