### ISSUE TITLE
Incomplete UUID query support with PostgreSQL

### ISSUE THREAD

**Issue by pedroalves0030** [prisma/prisma#2879]
**Describe the bug**
WhereInput doesn't dispaly ID field when using UUID

**To Reproduce**
1. Init Prisma
2. Create relationship with UUID model
```
type User {
  id: UUID! @unique
  name: String!
  posts: [Post!]!
}

type Post {
  id: UUID! @unique
  body: String!
  author: User!
}
```
4. Start container and deploy
5. Try to find posts by author
```
query($id: ID!) {
  posts(where: { author: { id: $id } }) {
    id
    body
    author {
      id
    }
  }
}
```
![image](https://user-images.githubusercontent.com/30181675/43684331-b8de193a-9874-11e8-8069-de42c6ba9aa2.png)

The same query with the default ID works well.

**Expected behavior**
To behavior as default ID

Versions:
 - Prisma Server: 1.15-alpha

**Additional context**
I'm a bit afraid to use UUIDs with Prisma in these first steps. Although they scale well in my application I do not know if I can find other problems in the future that can lead to data loss or inconsistency.
Any suggestions from the team to avoid complications in the future regarding IDs?

Despite this, the team is being amazing in implementing the project and creating tools to help developers, keep up the good work! 🎉🎉

**Comment by BenoitRanque** [comment]
I'm having the same issue and was unsure wether this is a bug or intended behavior. I can confirm this is still an issue with the latest (1.18) version. Is a workaround available?

**Comment by maarten00** [comment]
Same issue on 1.20. Possible workaround is using varchar instead of UUID on your database, and then using String instead of UUID in your datamodel. But I doubt you'd want to do that..

**Comment by jordyvandomselaar** [comment]
We're having the same issue. For now we've resorted to using `ID`'s like @maarten00 suggested. Shame Prisma doesn't fully support `UUID`'s yet.

**Comment by yckao** [comment]
Any update here?
I'm using prisma with existed postgresql.
It is on production environment, can't migrate the schema.
Also I've tried change prisma SDL from UUID to String, but postgres can't cast character to UUID.

Is there any other workaround?
