### ISSUE TITLE
Error npx prisma introspect to conect MYSQL Server 5

### ISSUE THREAD

**Issue by Daniek3d** [prisma/prisma#2885]
Hello, when connect to Mysql Server 5 with npx prisma introspect to generate schemas it dont work,
In mysql server exist the database his y access in mysql workbench, the string connection y the same in both.

its my config files.

_datasource db {
  provider = "mysql"
  url      = "mysql://root:manager@X.X.X.X:3306/his"
}

generator client {
  provider = "prisma-client-js"
}_

this my debug error:

  _IntrospectionEngine:rpc {
  IntrospectionEngine:rpc   jsonrpc: '2.0',
  IntrospectionEngine:rpc   error: {
  IntrospectionEngine:rpc     code: 4466,
  IntrospectionEngine:rpc     message: 'An error happened. Check the data field for details.',
  IntrospectionEngine:rpc     data: {
  IntrospectionEngine:rpc       is_panic: false,
  IntrospectionEngine:rpc       message: "Error in connector: Error querying the database: Error querying the database: Error querying the database: Server error: `ERROR HY000 (1193): Unknown system variable 'socket''",
  IntrospectionEngine:rpc       backtrace: null
  IntrospectionEngine:rpc     }
  IntrospectionEngine:rpc   },
  IntrospectionEngine:rpc   id: 1
  IntrospectionEngine:rpc } +352ms
Error: Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: Server error: `ERROR HY000 (1193): Unknown system variable 'socket''_

thanks.

**Comment by Chenziang96** [comment]
hello, i get this problem too. how you solve the problem finally, thanks
