### ISSUE TITLE
How to map a schema with inheritance to a schema without inheritance?

### ISSUE THREAD

**Issue by nmaro** [prisma/prisma#2891]
According to https://github.com/prismagraphql/prisma/issues/83 prisma doesn't support interface types yet. We want to support that nonetheless in our app schema and map the requests. So imagine that our model looks like this

```
interface A {
  a: String
}

type B implements A {
  a: String
  b: String
}

type C implements A {
  a: String
  c: String
}
```

The prisma model looks like this

```
type A {
  a: String
  b: String
  c: String
}
```

Now the question is how to globally transform queries with inline fragments by spreading out the fields.

From:

```
query {
  a {
    a
    ... on B { b }
    ... on C { c }
  }
}
```

to something like

```
query { a { a b c } }
```

This has to happen at a certain point before the prisma binding removes those inline fragments.

A way would be to modify the info object, although one would have to do that in every resolver and recursively. We'd prefer a global solution. We unsuccessfully tried to solve this with `transformSchema` from `graphql-tools`, because in the request object we get the inline fragments are already stripped.

Are we approaching this the right way? We suspect there already is some helper function or pattern to do this, but are getting lost in the details.

**Comment by divyenduz** [comment]
Hey! thanks for raising the detailed issue, have you already run into this? https://www.prisma.io/forum/t/feed-with-multiple-types-interfaces-unions-workaround/2450

Do you want to support interfaces natively at Prisma (as you suggested it is tracked by https://github.com/prisma/prisma/issues/83) or is it alright for you to have interfaces at the GraphQL server level? 

Thanks!

**Comment by nmaro** [comment]
We modify the info object with helper functions before passing it to prisma.

Meanwhile I believe that understanding and being able to modify the info object is a requirement for anyone who wants to develop more complex graphql servers, it's just a pity the info object is not officially documented anywhere (it's not prisma's fault). Working with typescript definitely helps.

You can close this.
