### ISSUE TITLE
Re-introspection issues with --experimental-reintrospection flag

### ISSUE THREAD

**Issue by harryttd** [prisma/prisma#2894]
## Bug description

1. For id field, original introspection yields: `id String @default(dbgenerated()) @id`.
I modified it to be `id String @default(uuid()) @id`.
Re-introspecting brings it back to `id String @default(dbgenerated()) @id`.

2. `@updatedAt` on the updatedAt column as it is not set by the original introspection. It needs to be manually set. Re-introspecting removes it.

3. `@unique` attribute is re-ordered to the end of a line for a field. (This could be an issue with other attributes as well, but I did not test)
## How to reproduce

SQL:
```sql
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS public.user (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "user_name" VARCHAR(128) UNIQUE NOT NULL,
);
```

schema.prisma:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model user {
  created_at DateTime @default(now())
  id         String   @default(dbgenerated()) @id
  updated_at DateTime @default(now())
  user_name  String   @unique
}
```

Update model `user` to:
```prisma
model User {
  createdAt DateTime @default(now()) @map("created_at")
  id        String   @default(uuid()) @id
  updatedAt DateTime @updatedAt @default(now()) @map("updated_at")
  userName  String   @unique @map("user_name")

  @@map("user")
}
```

Run: `prisma introspect --experimental-reintrospection`

`User` model result:
```prisma
model User {
  createdAt DateTime @default(now()) @map("created_at")
  id        String   @default(dbgenerated()) @id
  updatedAt DateTime @default(now()) @map("updated_at")
  userName  String   @map("user_name") @unique

  @@map("user")
}
```

Notice three things after running `prisma introspect --experimental-reintrospection`:
1. `uuid()` reverts to `dbgenerated()`
2. `@updatedAt` attribute is gone
3. `@unique` attribute is placed at the end of the line of `userName` field

## Environment & setup

- OS:  Mac
- Database:  Postgres 12.3
- Prisma version:  2.1.3

**Comment by pantharshit00** [comment]
I can reproduce this with version:
```
Environment variables loaded from prisma/.env
@prisma/cli          : 2.2.0-dev.36
Current platform     : darwin
Query Engine         : query-engine a0b56e4a4bc0dc6216e1cb26bd91a4094b868010 (at /Users/harshit/code/reproductions/issue-2894/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli a0b56e4a4bc0dc6216e1cb26bd91a4094b868010 (at /Users/harshit/code/reproductions/issue-2894/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core a0b56e4a4bc0dc6216e1cb26bd91a4094b868010 (at /Users/harshit/code/reproductions/issue-2894/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt a0b56e4a4bc0dc6216e1cb26bd91a4094b868010 (at /Users/harshit/code/reproductions/issue-2894/node_modules/@prisma/cli/prisma-fmt-darwin)
```

**Comment by janpio** [comment]
Is any of this supposed to work already in Re-Introspection @pantharshit00?

**Comment by pantharshit00** [comment]
I would expect it work with reintrospection as the changes doesn't change the database structure. If cases like these are not covered, reintrospection would be full of friction.

**Comment by janpio** [comment]
1 and 2 would probably be covered by https://github.com/prisma/prisma/issues/2534.
3 I am not super sure if we consider this in scop of Re-Introspection as this is covered by normal formatting rules. We will need to figure that out.

**Comment by janpio** [comment]
@harryttd I turned the third thing into a new feature requests: https://github.com/prisma/prisma/issues/2973 1 and 2 are already tracked by #2534, so I will close this issue now. Best subscribe to both to be notified about updates.

Thanks for reporting this!
