### ISSUE TITLE
Circle CI Example

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#2898]
**Describe the content you'd like to see**

An example to use Prisma with Circle CI

**Comment by marktani** [comment]
Here's a ready configuration that can be adapted to an example in this repo: https://github.com/prismagraphql/prisma/issues/2000#issuecomment-399075805

**Comment by Lotafak** [comment]
Hey guys!

Any working example for prisma + Circle CI with `docker` executor type?
To work with docker in this type of execution you have to deal with remote-docker, which makes it impossible to successfully run `prisma deploy` (Well, at least I didn't find a way to do it). I can share my config or more info if needed.

Cheers

**Comment by w0wka91** [comment]
@Lotafak This works!
https://github.com/w0wka91/prisma-circleci/tree/master
