### ISSUE TITLE
Import does not import all relations

### ISSUE THREAD

**Issue by blockformer** [prisma/prisma#2900]
When importing data from one to the other service not all relationships are imported. 

1. Export data using prisma export from service 1
2. Import data using prisma import --data export.zip into service 2
3. Compare the two services.

I was expecting for the data to be the same. ;-) 

![service-1](https://user-images.githubusercontent.com/40200122/43891204-08db9bc2-9bc9-11e8-87fb-6039a8a87a3b.png)
![service-2](https://user-images.githubusercontent.com/40200122/43891202-08bda41e-9bc9-11e8-9db1-21cebc95edfe.png)

- OS: Mac OS Hight Sierra
- CLI: prisma/1.13.7 (darwin-x64) node-v10.4.1
- PRISMA SERVER: (1.11-beta1 export) to (1.13.6 Import)

**Comment by marktani** [comment]
Can you share the datamodel for both services and the exported data?

**Comment by blockformer** [comment]
Datamodel is the same for both services. 

[datamodel.graphql.txt](https://github.com/prismagraphql/prisma/files/2273715/datamodel.graphql.txt)

[export-2018-08-09T09:58:01.655Z.zip](https://github.com/prismagraphql/prisma/files/2273714/export-2018-08-09T09.58.01.655Z.zip)
