### ISSUE TITLE
UUID type generates incorrect schema on MySQL

### ISSUE THREAD

**Issue by holmesmr** [prisma/prisma#2903]
**Describe the bug**
The UUID field type creates columns to store binary UUIDs with the type `CHAR()`, which is not binary-safe as it depends on the encoding of the connection and database.

**To Reproduce**
1. Do a `prisma init` and set up a new MySQL instance as normal.
2. In the generated `datamodel.graphql`, change the default `id` field declaration to `UUID! @unique`.
3. Run `prisma migrate` to deploy the schema.
4. Run `prisma playground` and attempt to use a mutation query to create a new user.

**Expected behavior**
You should be able to use the UUID column as intended without insertion errors. Instead, you will get an error, and the Prisma server will report that the database threw an error for "Incorrect string value".

**Screenshots**
![Screenshot showing Playground reporting error](https://i.imgur.com/IFxvcZx.png)
![docker-compose log output after error](https://i.imgur.com/hKNWlx2.png)

**Versions (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - `prisma` CLI: prisma/1.13.7 (darwin-x64) node-v10.8.0
 - Prisma Server: 1.13.7 (Docker)

**Comment by agonbina** [comment]
Just ran into the same issue 🤦‍♂️

**Comment by fabiancook** [comment]
This also occurs for me on development servers running 1.18-beta-1

**Comment by do4gr** [comment]
That will be fixed with our upcoming datamodel v1.1

**Comment by divyenduz** [comment]
We do not allow `UUID` with MySQL on id fields anymore. 

We do have a separate bug that allows you to deploy UUID to non id fields on MySQL, that is being tracked here: https://github.com/prisma/prisma/issues/4344

I am closing this one, please feel free to open a new issue in case you feel strongly about it.
