### ISSUE TITLE
When connecting to existing Postgres DB, CLI writes wrong Prisma version into generated Docker Compose file.

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#2905]
**Describe the bug**

When connecting to an existing Postgres database with data, the CLI writes wrong Prisma version into generated Docker Compose file. If I see it correctly, it increments the correct version by one.

E.g. today the latest released Prisma version is 1.13, but it writes `image: prismagraphql/prisma:1.14`.

**To Reproduce**

Use the `prisma init` wizard to connect to an existing Postgres DB and inspect the generated `docker-compose.yml`.

**Expected behavior**

It should write the latest released version into `docker-compose.yml`.

**Comment by marktani** [comment]
Related to https://github.com/prismagraphql/prisma/issues/2577.
