### ISSUE TITLE
Support BedrockDB

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2911]
https://bedrockdb.com/

> Bedrock is a simple, modular, WAN-replicated, Blockchain-based data foundation for global-scale applications. 
> ...
> Bedrock was built by Expensify, and is a networking and distributed transaction layer built atop SQLite, the fastest, most reliable, and most widely distributed database in the world.
> ...
> Bedrock supports the MySQL protocol, meaning you can continue using whatever MySQL client you prefer

Might just work out of the box.

**Comment by janpio** [comment]
Doesn't seem to be _that_ easy unfortunately:

```
$ /home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/.bin/prisma migrate save --create-db --experimental
2020-07-01T18:56:56.713Z prisma Environment variables not loaded
Error: Error: undefined: Error querying the database: Error querying the database: Unknown authentication plugin `@BhfHt/-4^Z,'.

    at Object.ensureDatabaseExists (/home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/@prisma/cli/build/index.js:2:2818789)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async MigrateSave.parse (/home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/@prisma/cli/build/index.js:2:2089873)
    at async main (/home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/@prisma/cli/build/index.js:2:1561778)
```

**Comment by cannikin** [comment]
I also found this yesterday—you can't make schema changes on a running instance (so Migrate won't work): https://github.com/Expensify/Bedrock/issues/218

There's a rationale for it in the comment just before mine. Here's the docs for concurrent transactions: https://www.sqlite.org/cgi/src/doc/begin-concurrent/doc/begin_concurrent.md

There's a workaround in the first comment (disable concurrent transactions) which may not be that much of a bottleneck...apparently all COMMITs are serialized anyway, regardless of the transaction type.

**Comment by cannikin** [comment]
> Seems our DB client does not like that there is no authentication at all required.

I haven't tried this yet, but maybe you can just put anything you want into username/password and Bedrock will ignore it and connect? Same for the database name—when I connect with my SQL GUI it sees a single database called `main`, but SQLite doesn't really have named databases, so that may just be there to satisfy MySQL clients.

**Comment by janpio** [comment]
Thanks for this comment @cannikin, I migrated a SQLite database locally, committed it and used that to start Bedrock - and we have passing tests: https://github.com/prisma/e2e-tests/pull/509 🚀 

So Prisma Client works perfectly fine with BedrockDB, it is only Migrate that has a slight problem right now.

**Comment by cannikin** [comment]
Holy cow did you see this @janpio ?? 😮 https://github.com/Expensify/Bedrock/issues/218#issuecomment-660715844

**Comment by janpio** [comment]
A new release is out, but no change for the use of `migrate`: https://github.com/prisma/e2e-tests/pull/610
Still the same error as https://github.com/Expensify/Bedrock/issues/818 though - so there is possible another blocker.

**Comment by janpio** [comment]
Good news: 
It is fixed, but not released yet: https://github.com/Expensify/Bedrock/issues/818#issuecomment-673173943
The PR shows a follow up error though - I think we will look into this when the release happened.

**Comment by janpio** [comment]
And now it is released, and our CI run confirms the same problem: https://github.com/prisma/e2e-tests/pull/610/checks?check_run_id=984394627
```
+ yarn prisma migrate save --create-db --experimental
yarn run v1.22.4
warning ../../package.json: No license field
$ /home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/.bin/prisma migrate save --create-db --experimental
Environment variables loaded from prisma/.env
Error: Error: P1001: Can't reach database server at `127.0.0.1`:`3306`

Please make sure your database server is running at `127.0.0.1`:`3306`.
    at Object.ensureDatabaseExists (/home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/@prisma/cli/build/index.js:2:2818789)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async MigrateSave.parse (/home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/@prisma/cli/build/index.js:2:2089873)
    at async main (/home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/@prisma/cli/build/index.js:2:1561778)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Will investigate later.

**Comment by cannikin** [comment]
@janpio We just found this...https://dqlite.io/

**Comment by janpio** [comment]
Very different beast @cannikin - this has its own "language" you talk to it, so on the Prisma side this would need a new connector (similar to MySQL, PostgreSQL, SQLite and so on).

**Comment by cannikin** [comment]
@janpio We've got another contender!  https://github.com/rqlite/rqlite

**Comment by janpio** [comment]
In my understanding - and that might be wrong, I only skimmed - rqlite also only offers its own data API (and not a standard MySQL API as Bedrock) to talk to it and send queries. That would be a totally different connector then. Here is its node client for example: https://github.com/rqlite/rqlite-js

**Comment by cannikin** [comment]
Huh...does Prisma have any plans to provide an interface, like via the SDK, that would let you create your own adapter to a DB? Then I could just integrate all of these databases myself and stop bugging you guys. 😉

**Comment by cannikin** [comment]
@janpio I was reminded of this issue again today! Any idea if the *new* Migrate stuff can work with Bedrock?

Doesn't look like there's been any movement on this issue, though: https://github.com/Expensify/Bedrock/issues/846

**Comment by janpio** [comment]
No difference with the new Migrate unfortunately:

```
$ /home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/.bin/prisma migrate dev --preview-feature
2021-02-12T20:27:56.285Z tryLoadEnv Environment variables not found at null
2021-02-12T20:27:56.286Z tryLoadEnv Environment variables not found at undefined
2021-02-12T20:27:56.286Z tryLoadEnv No Environment variables loaded
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "bedrock" at "127.0.0.1:3306"

Error: Error: P1001: Can't reach database server at `127.0.0.1`:`3306`

Please make sure your database server is running at `127.0.0.1`:`3306`.
    at Object.ensureDatabaseExists (/home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/prisma/build/index.js:60473:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async MigrateDev2.parse (/home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/prisma/build/index.js:62432:28)
    at async main (/home/runner/work/e2e-tests/e2e-tests/databases/bedrock/node_modules/prisma/build/index.js:105570:18)
```

Error message is indeed still the same as in https://github.com/Expensify/Bedrock/issues/846

**Comment by janpio** [comment]
> Thanks for this comment @cannikin, I migrated a SQLite database locally, committed it and used that to start Bedrock - and we have passing tests: [prisma/e2e-tests#509](https://github.com/prisma/e2e-tests/pull/509) 🚀

After almost a year I have to take this back - turns out in that test I was accidentally connecting directly to the SQLite database we were starting Bedrock on - but not using the Bedrock MySQL API via Prisma. D'oh.

Doing that, we get a similar error as in Migrate:

```
2021-04-30T19:10:39.887Z prisma:engine stdout Encountered error during initialization:
2021-04-30T19:10:39.888Z prisma:engine stderr {"is_panic":false,"message":"Server has closed the connection.","meta":null,"error_code":"P1017"}
2021-04-30T19:10:39.888Z prisma:engine {
  is_panic: false,
  message: 'Server has closed the connection.',
  meta: null,
  error_code: 'P1017'
}
2021-04-30T19:10:39.889Z prisma:client Error: Server has closed the connection.
```

So seems next step again would just to get Bedrock running locally on a SQlite database, and then successfully connect to it via a MySQL CLI or DB UI. If that works, we should also be able to get the same working for Prisma Client.

**Comment by cannikin** [comment]
![image](https://user-images.githubusercontent.com/300/124002551-bdebe600-d98a-11eb-8270-53c01233e6af.png)

Someone just posted this screenshot and I saw a mention of "Bedrock"... is something actually working??

**Comment by janpio** [comment]
No interest from users, so we will not prioritize this - so closing this issue to reflect that.
