### ISSUE TITLE
Smart casing for read operations

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma#2915]
## Problem
In a previous app, users have entered their email with all kinds of capitalizations (e.g. ToothFairy@gmail.com) and that particular casing was saved to the database. With the new app, when the user signs in, all emails are automatically lower-cased (toothfairy@gmail.com), but Prisma cannot find their record (since toothfairy@gmail.com ≠ ToothFairy@gmail.com).

## Suggested solution
So instead of this:
```js
const user = await prisma.user.findOne({
  where: { email: 'toothfairy@gmail.com' }
})
// user === null since user’s email is `ToothFairy@gmail.com`
```
...perhaps we could have something like this:
```js
const user = await prisma.user.findOne({
  where: { email: 'toothfairy@gmail.com' },
  caseAware: false // with the default being `true` for any string values in the `where` object
})
```

## Additional context
Couldn’t think how else to query the database. This is a somewhat urgent matter since existing users who couldn’t find their old email addresses keep creating new accounts and then get upset that their new accounts show up as unpaid 😕

**Comment by pantharshit00** [comment]
This looks like a duplicate of https://github.com/prisma/prisma-client-js/issues/690 to me. 

Feel free to close it if you also feel the same or otherwise comment here if these are different.

**Comment by heymartinadams** [comment]
Great, thanks @pantharshit00. Searched extensively before posting this issue, but somehow missed that one.
