### ISSUE TITLE
Unexpected Playground Answer

### ISSUE THREAD

**Issue by HumbertoAriza** [prisma/prisma#2916]
Im using the property active as published in the examples on this page of prisma docs
 - _Reference / Tools & Interfaces / Prisma Client/ Relation queries_
In the console im getting one element but in playground answers im receiving all of them without the filter.
# Dependencies
   - @nexus/schema": "^0.14.0"
   - @prisma/client": "^2.1.3"
   - graphql-yoga": "^1.18.3"
   - nexus-prisma": "^0.13.0"
   - @prisma/cli": "^2.1.3"
# Resolver
```
const user = await prisma.user.findOne({
          where: { id: ctx.request.userId },
          include: {
            posts: { where: { active: false } }
          }
        })

```
# Console.log(user)
- works fine just brings the post that active is false
# Answer in playground or apollo or wherever u try
```
{ 
...userInfo,
posts: [
        {
          "id": "ckc1jl5al0000pl3x2plqipe8",
          "active": true
        },
        {
          "id": "ckc1jlnl40003pl3xq83hxesa",
          "active": true
        },
        {
          "id": "ckc1k6str0000ou3xu7ae7u2m",
          "active": true
        },
....
        {
          "id": "ckc1l90hu0006ou3xoyb3znd5",
          "active": false        }]
```

# Debug info
I tried to by destructure the property posts.
```
const user = await prisma.user.findOne({
          where: { id: ctx.request.userId },
          include: {
            posts: { where: { active: false } }
          }
        })
const { posts, ...rest }= user
```
# console.log(posts)
```
[ {
          "id": "ckc1l90hu0006ou3xoyb3znd5",
          "active": false        }]
```

- same wrong answer in playground.

# trying return a new object
`return { posts, ...rest }`
- same wrong behavior

# trying write the prisma query different
```
const user = await prisma.user.findOne({
          where: { id: ctx.request.userId }
        }). posts({ where: { active: false })
```

- same wrong behavior

**Comment by pantharshit00** [comment]
@HumbertoAriza Can you please share your code in a git repository so that we can take a look? 

Also, this looks like a nexus issue so it will be better if you open this in the nexus repo: https://github.com/graphql-nexus/nexus

**Comment by HumbertoAriza** [comment]
Error can be found at https://github.com/HumbertoAriza/prisma-bug 
use this mutation at playground 
```
mutation {
  _createUser(
    data: {
      identificationNumber: "1"
      posts: {
        create: [
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: true }
          { active: false }
          { active: false }
          { active: false }
          { active: false }
          { active: false }
          { active: false }
          { active: false }
        ]
      }
    }
  ) {
    id
  }
}
```
 an the query user with the id that is returned should bring just the active:false products

**Comment by pantharshit00** [comment]
@HumbertoAriza Replace https://github.com/HumbertoAriza/prisma-bug/blob/3e6ef9c5594d86bb9d70a75d53e8d07f6a062f9f/src/types/models/userModel.js#L8 with `t.field("posts", { type: "Post", list: true });` so that you don't end up hitting the generated resolver. Otherwise GraphQL JS(which graphql-yoga uses for execution) will call resolver which t.model generated for this field and it will return it without filtering.

**Comment by HumbertoAriza** [comment]
You are completely right. I also have a question with nexus because even if im adding filtering and ordering to true the property take its not created.
The documentation is not update so i ask here

**Comment by pantharshit00** [comment]
Please open an issue at https://github.com/graphql-nexus/nexus
