### ISSUE TITLE
ERROR: relation "CloudSecret" does not exist, ERROR: syntax error at or near "NOT"

### ISSUE THREAD

**Issue by ppwfx** [prisma/prisma#2921]
**Describe the bug**

The prisma container exits and provides the following error message

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: syntax error at or near "NOT"
  Position: 18
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
        at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
        at slick.jdbc.Invoker.first(Invoker.scala:30)
        at slick.jdbc.Invoker.first$(Invoker.scala:29)
        at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:15)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
        at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
org.postgresql.util.PSQLException: ERROR: relation "CloudSecret" does not exist
  Position: 22
```

**To Reproduce**

1. Apply the following kubernetes resource
2. Attach to the logs

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.2-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_DB
          value: database
#        volumeMounts:
#        - mountPath: /var/lib/postgresql/data
#          name: postgres-data
#      volumes:
#      - name: postgres-data
#        hostPath:
#          path: /data/postgres-data-development
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    name: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30001
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma
data:
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: postgres
        host: postgres
        port: 5432
        user: user
        password: password
        database: database
        migrations: true
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prisma
spec:
  template:
    metadata:
      labels:
        name: prisma
    spec:
      containers:
        - name: prisma
          image: 'prismagraphql/prisma:1.12'
          ports:
            - name: prisma
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma
                  key: PRISMA_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: prisma
spec:
  ports:
  - port: 4466
    targetPort: 4466
    protocol: TCP
  selector:
    name: prisma
```

**Versions (please complete the following information):**
 - Prisma Server: [`1.12`, `1.13`]

**Comment by marktani** [comment]
I can't reproduce this on `1.13.7`. `CloudSecret` is a table that's supposed to be in the `management` database, can you confirm that it also exists for you?

![image](https://user-images.githubusercontent.com/1780597/44149800-9e2c3e88-a09d-11e8-8ef1-a2100d5e470e.png)

**Comment by Fabiomad85** [comment]
I had this issue today on heroku after an heroku pg:reset
after restart the dyno I had this error

```
org.postgresql.util.PSQLException: FATAL: permission denied for database "postgres"
Detail: User does not have CONNECT privilege.
```

**Comment by ZenSoftware** [comment]
@pantharshit00 Would you be so kind as to re-open this issue?
I have been getting this since I have started using prisma over the last month.  I've seen this with several deployments while I have been recreating a bunch of production environments.

Prisma: 1.30.0 (this also happened with 1.29.2 &  and I believe maybe 1.27.4)
Postgresql: 10.5 (Azure PostgreSQL)
Connecting with [pgBouncer Sidecar](https://hub.docker.com/_/microsoft-azure-oss-db-tools-pgbouncer-sidecar).

My app seems to execute Prisma Client queries just fine, but in my logs I eventually see:
```
Trying /tmp/jna-3506402/jna7221826073885463238.tmp
Found jnidispatch at /tmp/jna-3506402/jna7221826073885463238.tmp
Looking for library 'jwt_native'
Adding paths from jna.library.path: null
Trying libjwt_native.so
Adding system paths: [/lib64, /usr/lib, /lib]
Trying /lib/libjwt_native.so
Found library 'jwt_native' at /lib/libjwt_native.so
[INFO] {} - Started.
org.postgresql.util.PSQLException: ERROR: relation "CloudSecret" does not exist
  Position: 36
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$queryToDBIO$1(SharedSlickExtensions.scala:17)
	at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$jooqToDBIO$1(SharedSlickExtensions.scala:56)
	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@193a2c6c
```

I verified that "CloudSecrets" table actually exists via pgAdmin dashboard.  I querried the table to see its contents, which simply returns an empty table.

I checked what the "Project" table contained which returns:

| id  | secrets | allowQueries | allowMutations | functions |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| default$default  | []  | true | true| [] |

**Comment by dev-avinash** [comment]
> **EDIT:**
> I discovered that the issue was due to some incompatibilities with pgBouncer transaction pooling and the lack of support of Postgres prepared statements. It was causing some queries to fail, and thus could not access the Cloud Secret table within the Management schema. This issue is resolved for me.
> 
> @pantharshit00 Would you be so kind as to re-open this issue? I have been getting this since I have started using prisma over the last month. I've seen this with several deployments while I have been recreating a bunch of production environments.
> Prisma: 1.30.0 (this also happened with 1.29.2 & and I believe maybe 1.27.4)
> Postgresql: 10.5 (Azure PostgreSQL)
> Connecting with [pgBouncer Sidecar](https://hub.docker.com/_/microsoft-azure-oss-db-tools-pgbouncer-sidecar).
> 
> My app seems to execute Prisma Client queries just fine, but in my logs I eventually see:
> 
> ```
> Trying /tmp/jna-3506402/jna7221826073885463238.tmp
> Found jnidispatch at /tmp/jna-3506402/jna7221826073885463238.tmp
> Looking for library 'jwt_native'
> Adding paths from jna.library.path: null
> Trying libjwt_native.so
> Adding system paths: [/lib64, /usr/lib, /lib]
> Trying /lib/libjwt_native.so
> Found library 'jwt_native' at /lib/libjwt_native.so
> [INFO] {} - Started.
> org.postgresql.util.PSQLException: ERROR: relation "CloudSecret" does not exist
>   Position: 36
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
> 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
> 	at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$queryToDBIO$1(SharedSlickExtensions.scala:17)
> 	at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$jooqToDBIO$1(SharedSlickExtensions.scala:56)
> 	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
> 	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
> 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
> 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> [SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@193a2c6c
> ```
> 
> I verified that "CloudSecrets" table actually exists via pgAdmin dashboard. I querried the table to see its contents, which simply returns an empty table.
> 
> I checked what the "Project" table contained which returns:
> 
> id	secrets	allowQueries	allowMutations	functions
> default$default	[]	true	true	[]

@ZenSoftware how you solved this issue, I am facing same issue with azure + prisma + postgress + pgBouncer Sidecar.

**Comment by dev-avinash** [comment]
@pantharshit00 Would you be so kind as to re-open this issue?

**Comment by ZenSoftware** [comment]
@dev-avinash Hmm, yes I remember struggling with this for a few days.  I had the same setup as you did, using Azure PostgreSQL + pgBouncer Sidecar + Prisma.  I eventually decided to host my own PostgreSQL database in my Kubernetes cluster, instead of using the Azure hosting service.  There were too many issues I was running into.  But I do remember getting things working with the sidecar.  Though I should forewarn you, I discovered under heavy loads, if you did not configure the pgBouncer correctly, pgBouncer will start rejecting your Prisma queries.

I remember that this is where I discovered the root of the problem you are having:
https://www.pgbouncer.org/faq.html#how-to-use-prepared-statements-with-transaction-pooling
> How to use prepared statements with transaction pooling?
> To make prepared statements work in this mode would need PgBouncer to keep track of them internally, which it does not do. So only way to keep using PgBouncer in this mode is to disable prepared statements in the client.

I am not entirely sure how I managed to get it working.  So I provided my Kubernetes deployment YAML that I found in my git history for you.  Hopefully it helps.  Cheers ^_^
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: prisma-configmap
  labels:
    app: prisma
data:
  PRISMA_CONFIG: |
    port: 4466
    databases:
      prisma:
        connector: postgres
        host: 127.0.0.1
        port: 5432
        user: YourAzureUser@databasename
        migrations: true
        connectionLimit: 100
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: prisma
  labels:
    app: prisma
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prisma
    spec:
      containers:
        - name: prisma
          image: prismagraphql/prisma:1.30.1
          ports:
            - name: prisma-4466
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma-configmap
                  key: PRISMA_CONFIG
        - name: azure-pgbouncer-sidecar
          image: mcr.microsoft.com/azure-oss-db-tools/pgbouncer-sidecar:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: configfiles
              mountPath: "/etc/pgbouncer"
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 60
          lifecycle:
            preStop:
              exec:
                command:
                  ["/bin/sh", "-c", "killall -INT pgbouncer && sleep 120"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]
      volumes:
        - name: configfiles
          secret:
            secretName: azure-pgbouncer-config
```

**Comment by AndrewGold** [comment]
I'm in the same boat @dev-avinash @ZenSoftware. Any luck getting this working? Looks like Prisma 2 has the option to force transaction statements, which is meant to address this, but we are on Prisma 1. Any help would be much appreciated.
