### ISSUE TITLE
Relation + enums + pgbouncer fails with a ConnectorError

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#2921]
## Bug description

A schema with relation and enums on both sides of the relation fails with a ConnectorError when used with PgBouncer

## How to reproduce

- Run this SQL on a Postgres database

```sql
DROP TYPE IF EXISTS "public"."UserType";
CREATE TYPE "public"."UserType" AS ENUM ('ADMIN', 'NORMAL');

CREATE TABLE "public"."User" (
    "id" text NOT NULL,
    "userType" "public"."UserType" NOT NULL,
    PRIMARY KEY ("id")
);

DROP TYPE IF EXISTS "public"."WorkType";
CREATE TYPE "public"."WorkType" AS ENUM ('FULL_TIME', 'FREELANCER');

CREATE TABLE "public"."Work" (
    "id" text NOT NULL,
    "userId" text,
    "workType" "public"."WorkType" NOT NULL DEFAULT 'FREELANCER'::"WorkType",
    PRIMARY KEY ("id")
);

ALTER TABLE "public"."Work" ADD FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
```

- Introspect it to get the following schema

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id       String   @id
  userType UserType
  work     Work?
}

model Work {
  id       String   @id
  workType WorkType @default(FREELANCER)
  user     User?    @relation(fields: [userId], references: [id])
  userId   String?  @unique
}

enum UserType {
  ADMIN
  NORMAL
}

enum WorkType {
  FREELANCER
  FULL_TIME
}
```

- Setup local PgBouncer and write the `DATABASE_URL` env var in `prisma/.env`

- Generate the Prisma client with `npx -p @prisma/cli@dev prisma generate`

- Create this `index.js` file:

```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient({
  log: ['query'],
})

const run = async () => {
  const d1 = await prisma.work.findMany()
  console.log({ d1 })

  const d2 = await prisma.user.findMany()
  console.log({ d2 })
}

run().finally(async () => {
  await prisma.disconnect()
})
```

- Run it with `node index.js`, It fails with (tested on DO PgBouncer)

```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("26000"), message: "prepared statement \"s1\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(512), routine: Some("FetchPreparedStatement") }) }) })
    at PrismaClientFetcher.request (/Users/divyendusingh/Documents/prisma/p2-do-bouncer/node_modules/@prisma/client/runtime/index.js:1:185866)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26989) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26989) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment & setup

- Database: DigitalOcean PgBouncer
- Prisma version: `2.2.0-dev.36`

**Comment by pimeys** [comment]
This has been fixed in sqlx branch, but tokio-postgres does something weird with statement names here.

**Comment by pimeys** [comment]
Can confirm this is a bug in `sfackler/rust-postgres` and this simple program can trigger the same error:
```rust
use postgres::{Client, NoTls};

fn main() -> anyhow::Result<()> {
    let mut client = Client::connect(
        "postgresql://postgres:prisma@localhost:6432/postgres",
        NoTls,
    )?;

    client.simple_query("BEGIN")?;
    client.simple_query("DEALLOCATE ALL")?;
    let stmt = client.prepare("SELECT \"public\".\"User\".\"id\", \"public\".\"User\".\"userType\" FROM \"public\".\"User\" WHERE 1=1 OFFSET $1")?;
    dbg!(client.query(&stmt, &[&0i64])?);
    client.simple_query("COMMIT")?;

    client.simple_query("BEGIN")?;
    client.simple_query("DEALLOCATE ALL")?;
    let stmt = client.prepare("SELECT \"public\".\"Work\".\"id\", \"public\".\"Work\".\"workType\" FROM \"public\".\"Work\" WHERE 1=1 OFFSET $1")?;
    dbg!(client.query(&stmt, &[&0i64])?);
    client.simple_query("COMMIT")?;

    Ok(())
}
```

**Comment by pimeys** [comment]
Executive summary: custom types will not work in pgbouncer mode.

For engineers:

This bug needs a bit of an explanation how tokio-postgres works and what causes this.

PostgreSQL uses typed statements, so when preparing them we need to figure out the correct types. Normally this is quite straightforward, we have a list of OID numbers for specific types, e.g. `VARCHAR` is 1043 or `INT8` is 20. Things change when using user-defined types, such as enums. We get OIDs not found in the internal hashmap, such as in our case 71021 for our enum.

So the workflow for the test script above:

- `BEGIN` starts a new transaction, using the `simple_query` which doesn't use statements.
- `DEALLOCATE ALL` clears all statements (empty, so nothing) and also uses `simple_query`.
- `SELECT \"public\".\"User\".\"id\", \"public\".\"User\".\"userType\" FROM \"public\".\"User\" WHERE 1=1 OFFSET $1` is our first real query that gets prepared. This query gets the statement id of `s0`.
- Before we can execute it though, we need to do a few more things. The `userType` is not having a standard `OID`, so the postgres client goes to do a few things first:
  - `SELECT t.typname, t.typtype, t.typelem, r.rngsubtype, t.typbasetype, n.nspname, t.typrelid FROM pg_catalog.pg_type t LEFT OUTER JOIN pg_catalog.pg_range r ON r.rngtypid = t.oid INNER JOIN pg_catalog.pg_namespace n ON t.typnamespace = n.oid WHERE t.oid = $1` first, getting the type info for the `userType` again as a statement, getting the id of `s1`.
 
  - `SELECT enumlabel FROM pg_catalog.pg_enum WHERE enumtypid = $1 ORDER BY enumsortorder` for enum labels, again a statement and the id is `s2`
  - Store the type info of this specific enum to the memory for later use.
- Now we have all the pieces in the puzzle, so we can finally execute the `s0` and continue our lives.
- `COMMIT` as simple query, no statements.
  
All good, nothing breaks until we get to the second part:
- `BEGIN`
- `DEALLOCATE ALL`
- `SELECT \"public\".\"Work\".\"id\", \"public\".\"Work\".\"workType\" FROM \"public\".\"Work\" WHERE 1=1 OFFSET $1` is again the first prepared query, getting the next available statement id `s2`.
- The query holds another enum `workType`, and we don't yet have the type for its OID stored in memory, so we trigger the the `pg_catalog.pg_type` query again.

And then we're in trouble. What tokio-postgres does here is, it optimizes these two catalog queries by storing their statements to a special cache. So now we hit the same query with a different OID and tokio-postgres decides to take the `Statement` from memory, executing it one more time. The statement has the id of `s1`, but us using `DEALLOCATE ALL` we deleted all statements from the memory, clearing the `s1` too. This gives us the error `prepared statement "s1" does not exist`.

So what could we do to fix this?

- When Prisma/SQLx is finally done, it has a bit different architecture. It doesn't have separate caches for the type queries, and relies completely on the LRU cache, skipping preparing if we have a cached statement. For pgbouncer the cache would be off anyhow, and we'd always make a new statement for every query. This is tested and the problem doesn't occur in the SQLx branch of Query Engine.
- We could implement a wrapper type such as the `PgAny` I implemented to SQLx. This holds the OID of 0, meaning the database doesn't typecheck the parameter before executing the query (crashes a bit later in the pipeline if the type is wrong).
- Or then we just cache all type info from the database immediately to the memory when we start the system, using a bit more RAM and skipping the type queries later in the pipeline.
- And finally we can just have a flag for tokio-pg to not cache anything

So in the end it feels like we either get SQLx branch working soon (which I'm a bit doubtful of), or one of the two options with either `PgAny` or caching all type info at once. The last point is a hack that probably will not get accepted as a pull request, but we could fork the crate for us and use it until SQLx is ready.

**Comment by pimeys** [comment]
Did a PR for `tokio-postgres` to get around this issue: https://github.com/sfackler/rust-postgres/pull/636
