### ISSUE TITLE
Add new line checks to integration tests

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#2926]
Due to differences in operating systems / environment, I could not get the recent change of [adding trailing empty lines](https://github.com/prisma/prisma-engines/commit/ea035543e59571161e00ccd4063f5638283bfba7) working in the integration tests.
Instead for now I added a `.trim()` call to those tests to make them work.

We should look into it and find a way to get the tests running without `.trim()`

**Comment by Jolg42** [comment]
Done in #2929
