### ISSUE TITLE
Can not access the docs  "https://www.prisma.io/docs/"

### ISSUE THREAD

**Issue by sessionboy** [prisma/prisma#2928]
hi ,I come from China. 
I can access "https://www.prisma.io", but i can't access "https://www.prisma.io/docs/", it is hang up,I don't know why.
Everything was normal ago.

**Comment by marktani** [comment]
Hi, I'm sorry that you're experiencing this. This seems to be related to our CDN provider.
We will roll out a new version of the docs that doesn't suffer from this next week.

You can read the docs today by following these instructions: https://github.com/prisma/prisma/issues/2911.
