### ISSUE TITLE
Breaking change when updating from Prisma 1.13 to 1.14

### ISSUE THREAD

**Issue by carstenbaumhoegger** [prisma/prisma#2929]
**Describe the bug**
We've updated our backend from Prisma 1.13 to 1.14 and now the data returned has a different format than before, therefore we have to change a lot inside the graphql-yoga resolvers.

**To Reproduce**
1. Update from Prisma 1.13 to 1.14

Have a query like this:
```js
const { article } = await ctx.db.request(query, variables);
if (!article) {
  throw new Error('Article not found');
}
```

with Prisma 1.13 everything worked fine, now you have to do

```js
const { data } = await ctx.db.request(query, variables);
const article = data.article;
if (!article) {
  throw new Error('Article not found');
}
```

**Expected behavior**
Breaking changes are not a big deal but it would be great if they get documented in the release notes so that you can anticipate the changes that need to be made.

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - Prisma CLI:  `prisma/1.14.0 (darwin-x64) node-v10.8.0`
 - Prisma Server: `1.14.0`
 - `prisma-binding`: `2.1.3`, 
- `graphql-yoga`: `1.16.1`

**Comment by mcmar** [comment]
I can't reproduce this. The data format for 1.14 appears the same as 1.13 to me. @carstenbaumhoegger can you verify that this is not an issue related to another component in your stack, such as `graphql-yoga`?

Both 1.13 and 1.14 look like this to me:
```
const { article } = await ctx.db.request(query, variables);
if (!article) {
  throw new Error('Article not found');
}
```

**Comment by mcmar** [comment]
If you call the API directly, the data format of the JSON returned is as such:
```
{
  "data": {
    "users": [ ... ]
  }
}
```

However, if I call using the `request` method of `prisma-bindings`, the result appears like this:
```
const { users } = await primsa.request('{ users { id, email } }');
users.forEach((user) => { ... });
```

**Comment by carstenbaumhoegger** [comment]
hey @mcmar 
You're right, it seems to be related to `prisma-binding`. Sorry for opening the Issue, everything running smoothly now!
Thanks for looking at it!
