### ISSUE TITLE
prisma.io/docs is down (508)

### ISSUE THREAD

**Issue by jesstelford** [prisma/prisma#2931]
Safari, Firefox, and Chrome aren't loading `https://www.prisma.io/docs` - they're returning error 508.

Curiously, `curl -v https://www.prisma.io/docs` returns a 200 + HTML response.

**Comment by w0wka91** [comment]
I also get error 508!

**Comment by phatstackz** [comment]
Can't figure out the meaning of life with this error 508!
Please help!

**Comment by marktani** [comment]
Thanks, we're looking into this. It seems to be an issue with our CDN.

Until we resolved this, you can refer to the new version of the docs [here](https://docs-beta.prisma.io/) or read the old version of the docs [here](https://github.com/prisma/prisma/tree/master/docs).

**Comment by jesstelford** [comment]
Looks like it's back up, and redirecting to https://prisma-docs.netlify.com/docs/
