### ISSUE TITLE
Count and filter seems gives strange count

### ISSUE THREAD

**Issue by louisrli** [prisma/prisma#2934]
## Bug description
Unclear whether this is just me not understanding filter but I've read this documentation.

`StudySchedule` and `ScheduleDay` have a many-to-many relation.

Actual count: Some number in the thousands (like 4600)
Expected count: 35

Code:
```
    const numDays = await prisma.scheduleDay.count({
  1       where: {
  2         StudySchedule: {
  3           every: {
  4             id: schedule.id,
  5           },
  6         },
  7       },
  8     });
 12     console.log(`num days on schedule: ${numDays}`);
 13
```

```
prisma=> select count(*) from "_ScheduleDays" where "B" = 'ck9q2t6ddoxfe0726h0q5804c';
 count
-------
    35
(1 row)
```

Prisma is running this query:
```
prisma:query SELECT COUNT(*) FROM (SELECT "default$default"."ScheduleDay"."id" FROM "default$default"."ScheduleDay" WHERE ("default$default"."ScheduleDay"."id") NOT IN (SELECT "t0"."A" FROM "default$default"."_ScheduleDays" AS "t0" INNER JOIN "default$default"."StudySchedule" AS "j0" ON ("j0"."id") = ("t0"."B") WHERE (NOT "j0"."id" = $1)) OFFSET $2) AS "sub" LIMIT $3
```

I'm looking at [this documentation](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering#retrieve-all-user-records-where-all-posts-are-published-and-a-least-one-related-post-mentions-prisma), by the way.

From the docs:
```
const result = await prisma.user.findMany({
    where: {
      post: {
          every: {
            published: true
          }
```

In English: Retrieve all User records where all posts are published

And so thus, I would assume that my query means:
"Count all schedule days where [all the] schedule IDs are equal to the provided ID"

Could you please clarify if I'm interpreting the documentation wrong or this is a bug? 

## How to reproduce
Not sure, I haven't done a small test case.

## Expected behavior

I expected it to yield the result corresponding to the English description I provided above.

## Prisma information
postgres, latest prisma

## Environment & setup

latest prisma, postgres 11

**Comment by pantharshit00** [comment]
Every key in the conditional works like Javascript `every` methods on Arrays. It makes sure that every subrecord will fulfills the condition and then it returns desired record.

**Comment by pantharshit00** [comment]
So in your case, it will return only if there is one sub record of `ScheduleDay` which has the given id as I am assuming you can't connect in the database level. 


> select count(*) from "_ScheduleDays" where "B" = 'ck9q2t6ddoxfe0726h0q5804c';

The query that is fetching all the records connected which are connected with given id. It does now consider that we are fetching only if one record if the given id is present.
