### ISSUE TITLE
transaction is undefined

### ISSUE THREAD

**Issue by viweei** [prisma/prisma#2936]
![image](https://user-images.githubusercontent.com/1762036/86528247-b5c4ac00-bed8-11ea-8694-264234fe5941.png)

Verision:
    "@prisma/cli": "^2.1.3",
    "@prisma/client": "^2.1.3"

**Comment by pantharshit00** [comment]
You will need to enable the transaction api via the experiemental flags. It is experimental right now.

You can do it via:

```prisma
generator client {
  provider = "prisma-client-js"
  experimentalFeatures = ["transactionApi"]
}
```

Also, please run `npx prisma generate` after adding this.



See https://github.com/prisma/prisma/releases/tag/2.1.0
