### ISSUE TITLE
Use denylist in Introspection already

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#2940]
As of now, during `prisma generate`, the Prisma Client generator checks in its denylist, which model names are disallowed and fails if not possible. This is a good safe guard already, but can break the flow, when coming from introspection:

1. Introspect, get `schema.prisma`
2. Run `prisma generate` - get error that model name is on denylist.

Instead, `introspect` could already rename models which are on the denylist.

**Comment by janpio** [comment]
Alternatively Introspection could at least point out the problematic models to the user to let them fix it themselves (possibly linking to a documentation page showing the approach and common names)

**Comment by dpetrick** [comment]
Merged
