### ISSUE TITLE
Clarify usage of datasource url when using SQLite - `file:` is what works and `sqlite:` `sqlite://` should error

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#2941]
## Problem

This appeared after I noticed that the engines error for an invalid SQLite url value says `"The URL for datasource db must start with the protocol sqlite://"

For SQLite in schema.prisma this works everywhere (Prisma Client JS, Prisma Client Go, Migrate) and is documented:
```
file:./dev.db
file:../dev.db
```

This is not valid (error from engine)
```
sqlite:dev.db
```

This is considered valid & is recommended to be used by the engine's parser but it doesn't work either in clients or Migrate
```
sqlite://dev.db
```
Example error from Prisma Client JS
```
Error in connector: Error querying the database: unable to open database: //dev.db
    at PrismaClientFetcher._request ({..}/runtime/getPrismaClient.ts:999:15)
```

## Suggested solution
- [ ] Engines: update error message in engines "The URL for datasource `db` must start with the protocol `sqlite://`" should replace `sqlite://` by `file:`
- [ ] Engines: make parsing of `sqlite://` and `sqlite:` an error
- [ ] Merge https://github.com/prisma/prisma/pull/3027

Related:
- [ ] [#497 Can not create SQLite database when using protocol `sqlite://`](https://github.com/prisma/migrate/issues/497)
- [ ] [What should be the supported database string/url schemes for SQLite? #385](https://github.com/prisma/specs/issues/385)

## Additional context
[Internal conversation](https://prisma-company.slack.com/archives/CEYCG2MCN/p1594026418374700)

**Comment by janpio** [comment]
As `sqlite:` seems to have worked in the past, we decided to keep this as an alias of `file:` which will be the official, documented way to reference SQLite databases.

**Comment by timsuchanek** [comment]
TypeScript part is done in https://github.com/prisma/prisma/commit/477395a4edcaba8692332cc3981a0ec085fae01d
