### ISSUE TITLE
Cannot run on OpenShift.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [prisma/prisma#2945]
**Describe the bug**
The Docker images cannot be run on OpenShift, or at least not under the defaults.  This might count as a feature, I'm not sure.

**To Reproduce**
1.) `oc cluster up`
2.) `oc new-app --docker-image=prismagraphql/prisma:1.14`
3.) `oc status` will eventually say something like "Errors: pod/prisma-whatever is crash-looping"
4.) `oc logs pod/prisma-whatever` shows "/app/start.sh: line 3: ./app/bin/prisma-local: Permission denied"

**Expected behavior**
It should start up.

**Versions (please complete the following information):**
 - OS: Ubuntu 18 
 - `prisma` CLI: N/A
 - Prisma Server: 1.14

**Additional context**
I think it's just because of the permissions on `app/bin/prisma-local`.  If you run `docker run --entrypoint "whoami" prismagraphql/prisma:1.14` it says the container's running under root user, so maybe it'd be a matter of making it be under a non-root user?

**Comment by Aubron** [comment]
I made this in the meantime
https://github.com/aubron/prisma-openshift
https://hub.docker.com/r/aubron/prisma-openshift/

**Comment by dpetrick** [comment]
The mentioned PR is merged. Reopen or open a new issue if the problem persists.

**Comment by sapkra** [comment]
Should have been released within 1.30.0-beta 20 minutes ago.
