### ISSUE TITLE
Implicit m-n relations have an extra `@relation` field after introspection

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma#2947]
## Bug description

On introspecting a m-n implict relation, an extra `@relation` field is added that isn't added while using Migrate.

## How to reproduce

1. Seed the following SQL in the database

```sql
CREATE TABLE "public"."Student" (
"id" SERIAL,
"name" text  NOT NULL ,
    PRIMARY KEY ("id"))

CREATE TABLE "public"."Course" (
"id" SERIAL,
"name" text  NOT NULL ,
    PRIMARY KEY ("id"))

CREATE TABLE "public"."_CourseToStudent" (
"A" integer  NOT NULL ,
"B" integer  NOT NULL )

CREATE UNIQUE INDEX "_CourseToStudent_AB_unique" ON "public"."_CourseToStudent"("A","B")

CREATE  INDEX "_CourseToStudent_B_index" ON "public"."_CourseToStudent"("B")

ALTER TABLE "public"."_CourseToStudent" ADD FOREIGN KEY ("A")REFERENCES "public"."Course"("id") ON DELETE CASCADE  ON UPDATE CASCADE

ALTER TABLE "public"."_CourseToStudent" ADD FOREIGN KEY ("B")REFERENCES "public"."Student"("id") ON DELETE CASCADE  ON UPDATE CASCADE
```

2. Running `prisma introspect --experimental-reintrospection` produces the following schema:

```prisma
model Course {
  id      Int       @default(autoincrement()) @id
  name    String
  Student Student[] @relation(references: [id])
}

model Student {
  id     Int      @default(autoincrement()) @id
  name   String
  Course Course[] @relation(references: [id])
}
```

3. The below schema works with Migrate without a `@relation` field added.

```prisma
model Student {
  id      Int      @default(autoincrement()) @id
  name    String
  Course Course[]
}

model Course {
  id      Int       @default(autoincrement()) @id
  name    String
  Student Student[]
}
```

## Expected behavior

The relation field shouldn't be explicitly added for implicit m-n relations.

## Environment & setup

- OS: Debian
- Database: PostgreSQL
- Prisma version: 2.2.0
- Node.js version: 12.18.1

**Comment by janpio** [comment]
Conversation with @mavilein and @do4gr showed that this is an outdated opinionation in our renderer that was correct in the past, but is now not any more - those `@realation` attributes do not need to be there any more.
