### ISSUE TITLE
Support for more conditions in findOne

### ISSUE THREAD

**Issue by cannikin** [prisma/prisma#2954]
## Problem

I think Prisma should support "nested where" query syntax. This is where two or more tables that are joined both have a `where` clause against them.

For example, let's say I'm building a CRM where a `User` has many `Contact`s and a `Contact` can have many `Note`s:

```prisma
model User {
  id          Int        @default(autoincrement()) @id
  email       String     @unique
  name        String?
  contacts    Contact[]
}

model Contact {
  id        Int       @default(autoincrement()) @id
  user      User      @relation(fields: [userId], references: [id])
  userId    Int
  name      String?
  email     String?
  notes     Note[]
}

model Note {
  id        Int      @default(autoincrement()) @id
  contact   Contact  @relation(fields: [contactId], references: [id])
  contactId Int
  text      String
}
```

In the simplest case I want to pull a note by ID, but only if the proper user owns that note. So let's say the user is ID `123` and they want to view note `456`. In regular SQL I might do something like

```sql
SELECT Note.*
FROM   Note INNER JOIN Contact ON Note.contactId = Contact.id
WHERE  Note.id = 456 AND Contact.userId = 123
```

So if the `Note.id` is correct, but the proper user doesn't own that note, this will return `null`. Right now when using Prisma I need to manually add a conditional to check the status of that ID, something like:

```js
const note = await db.note.findOne({
  where: { id },
  include: { contact: { select: { userId: true } } },
})

if (note.contact.userId === currentUser.id) {
  return note
} else {
  return null
}
```

(Notice that if I want this function to only return the `note` and not included `contact` detail, I also need to `delete note.contact`).

## Suggested solution

Similar to the ability to add `select` and `include` objects to relations, allowing setting a `where` object that could add that nested `where`. Then the above code then becomes a single statement:

```js
return db.note.findOne({
  where: { id },
  include: { contact: { where: { userId: currentUser.id } } }
})
```

(In this case I would still need to delete the included `note.contact` in order to only return the `note` data.)

**Comment by pantharshit00** [comment]
We already allow you filter `many` to part of relation: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering#filter-within-include

But you are asking for filers for `one` side of `one` to `many` relation(a note has only one contact). 

I don't think filter makes sense here. There will be always one `Contact` record that is connected to the `Note`. So allow you to select fields from that record or including the complete record. 

The `include` properly is meant to for including related record to the result of top where. What you are asking for in include to include the complete result of the query which I think changes the meaning of `include` completely.

**Comment by cannikin** [comment]
I agree, the `include` syntax is not really ideal but I was trying to stick to what's already there (`include` taking additional objects like `select`). A more optimal interface could be something like:

```javascript
db.note.findOne({ where: { id, contact: { userId: currentUser.id } } })
```

Since `Note` already knows how it relates to a `Contact` through the schema it would know it needs to create a join here and provide both `WHERE` clauses.

**Comment by pantharshit00** [comment]
Maybe something like AND on findOne is a more reasonable feature request here:
```js
  return db.note.findOne({
    where: { AND: [{ id }, { contact: { userId: currentUser.id } }] },
    include: { contact: true },
  });

```

I am not sure how we will maintain the uniqueness of findOne here though. This already possible with `findMany` but it will introduce the an additional check as result will be wrapped in an array:
```
// already possible
  let result = client.note.findMany({
    where: { AND: [{ id }, { contact: { userId: currentUser.id } }] },
    include: { contact: true },
  });

 return result.length > 0 ? result[0] : null
```

**Comment by cannikin** [comment]
> I am not sure how we will maintain the uniqueness of findOne here though.

Question: why is this uniqueness constraint part of `findOne` anyway? This isn't a limitation of SQL...are you trying to optimize something in the code itself? Why not just call `findMany` behind the scenes and then return the first result?

This is what Rails ActiveRecord does—`find` (equivalent to `findOne) is just using `where` (equivalent to `findMany`) behind the scenes and then adding `LIMIT 1` so you only ever get 1 result. If it's not the one you were expecting then you weren't selecting by a unique column, but it doesn't **force** you to use a unique column, that's up to you.

**Comment by pantharshit00** [comment]
Yeah, I actually agree with you here. I will raise this internally to the team :)

**Comment by hyochan** [comment]
I think this is somewhat critical to the nested field in `objectType`. Imagine the below query.
```
    t.field(
      'profile',
      {
        type: 'Profile',
        nullable: true,
        resolve: async (user, args, ctx) => {
          const profile = await ctx.prisma.profile.findMany({
            where: {
              userId: user.id,
            },
          });
          return profile[0];
        },
      },
    );
```

If there are many dummy profiles and we want to just take unique one, the field will take all the rows.
Correct me if I am wrong! 🤔

**Comment by cannikin** [comment]
Won't `profile[0]` always make it return a single one, no matter what? If there are multiple records that match the `userId: user.id` clause it will only return a single one—the first one!. WHICH one it returns is up to whatever order the database returns them, but that's a concern for the developer to make sure they're getting back the record they expect.

**Comment by steebchen** [comment]
Quoted by @sorenbs:

> The contract of findOne is:
`Look up record by identity. If a record is returned you know that it is the only record with that entity.`
That enables you to quickly verify that the code is correct without having to first consult the prisma schema to ensure that it is in fact looking up by identity. This is helpful in code reviews and generally when reading through code.
Code readability is much more important than code writability.

For additional information, see https://github.com/prisma/specs/issues/170#issuecomment-535424765

We could also introduce `findFirst`, which behaves like findMany but returns the first result – basically `LIMIT 1`. It is not guaranteed to be unique, so there could be two records and only one is returned; the application would need to make sure this shouldn't happen.

**Comment by hyochan** [comment]
> Won't `profile[0]` always make it return a single one, no matter what? If there are multiple records that match the `userId: user.id` clause it will only return a single one—the first one!. WHICH one it returns is up to whatever order the database returns them, but that's a concern for the developer to make sure they're getting back the record they expect.

What I was worried about was that `findOne` would return the row when the database finds one. However, `findMany` would keep searching for the next rows although we've already get the first row. Wouldn't this decrease the query performance?

**Comment by hyochan** [comment]
> Quoted by @sorenbs:
> 
> > The contract of findOne is:
> > `Look up record by identity. If a record is returned you know that it is the only record with that entity.`
> > That enables you to quickly verify that the code is correct without having to first consult the prisma schema to ensure that it is in fact looking up by identity. This is helpful in code reviews and generally when reading through code.
> > Code readability is much more important than code writability.
> 
> For additional information, see [prisma/specs#170 (comment)](https://github.com/prisma/specs/issues/170#issuecomment-535424765)
> 
> We could also introduce `findFirst`, which behaves like findMany but returns the first result – basically `LIMIT 1`. It is not guaranteed to be unique, so there could be two records and only one is returned; the application would need to make sure this shouldn't happen.

Can you tell me more about it in `soft delete` scenario?
```
export const user = queryField('user', {
  type: 'User',
  args: { id: stringArg() },
  nullable: true,
  resolve: async (parent, { id }, ctx): Promise<UserReturnType> => {
   return  await ctx.prisma.user.findOne({
      where: {
        id,
        deletedAt: null,
      },
    });
  },
});
```

We are currently using above code for soft deleting users. Since, `deletedAt` is not `unique`, we can't use `findOne` in this case. What would be the better approach?

**Comment by cannikin** [comment]
> We could also introduce `findFirst`, which behaves like findMany but returns the first result – basically `LIMIT 1`.

Oooo I like this! This probably makes everyone's lives easier—`findOne` doesn't have to change at all so all the worries about different scenarios/cases are avoided.

**Comment by oceandrama** [comment]
@steebchen `findFirst` looks great, waiting for this feature

**Comment by thebiglabasky** [comment]
Created a separate issue for `findFirst` and candidated this one so we can track implementation if/when we go into it.
https://github.com/prisma/prisma/issues/3676

**Comment by pantharshit00** [comment]
`findFirst` has been implemented and was shipped in release https://github.com/prisma/prisma/releases/tag/2.8.0

I think this can be closed now :)
