### ISSUE TITLE
New operator for [ChildTable]UpdateManyWithout[ParentTable]Input 

### ISSUE THREAD

**Issue by cesarve77** [prisma/prisma#2956]
**Is your feature request related to a problem? Please describe.**
Now if I want to update a array of connection I need to disconnect the previous children and after connect the new ones.

e.g.

My previous records is connected to category 1111 and 2222 and I want to updated to categories 3333 and 4444
```
{
  "where": {"id": "cjl66zfw90jr60862jky2ouvz"},
  "data": {
     "categories":
        {"disconnect":[{"id":"11111"},{"id":"2222"}] ,"connect":[{"id":"3333"},{"id":"4444"}]}
   }
}

```

**Describe the solution you'd like**
My proposal is have a new connector where we don't need disconnect, and all previous records are disconnected automatically 

.e.g.
```
{
  "where": {"id": "cjl66zfw90jr60862jky2ouvz"},
  "data": {
     "categories":
        {"set":[{"id":"3333"},{"id":"4444"}]}
   }
}

```

**Describe alternatives you've considered**
How alternatives we can consider pass a filter conditional  in disconnect
.e.g.
```
{
  "where": {"id": "cjl66zfw90jr60862jky2ouvz"},
  "data": {
     "categories":
        {"disconnect":{category_contains:  "x"},"set":[{"id":"3333"},{"id":"4444"}]}
   }
}

```
**Additional context**
My problem now is, I don't always know the previous connected records, and I need to make an unnecessary call to the database, 

And if this is the solution  the connected records can change between this call and the updated, resulting an unexpected behaviour.

Thanks for considering this options.
and Thanks for this great package
Happy day!

Sorry for my english

**Comment by marktani** [comment]
Thanks a lot for this feature request.
It is similar to this one, so I'm closing it. #2036.
