### ISSUE TITLE
Running graphql get-schema project_name gives an error, because of incorrect relative path of prisma.yml

### ISSUE THREAD

**Issue by artem-korolev** [prisma/prisma#2958]
I have this file structure:

- workspace
   .graphqlconfig
   - servers
   --- prisma
   --- graphql
   - clients
   --- relay-native
   --- react-graphql

**.graphqlconfig**:
```json
{
	"projects": {
		"graphql": {
			"schemaPath": "servers/graphql/src/generated/prisma.graphql",
			"extensions": {
				"prisma": "servers/prisma/prisma.yml"
			}
		}
	}
}
```

So that .graphqlconfig is placed in the root of workspace.
I run this:
```bash
cd servers/graphql
graphql get-schema -p graphql
× servers/prisma/prisma.yml could not be found.
```

if I update my config with this line:
"prisma": "../../servers/prisma/prisma.yml"
everything works okay then.
So I guess its a bug, that should be fixed

**Comment by marktani** [comment]
Thanks for bringing this up, @artem-korolev. I am not sure if this is a bug or not. In any case, could you please report it in this repository instead: https://github.com/graphql-cli/graphql-cli/issues?

Thanks! 🙌

**Comment by artem-korolev** [comment]
yes sure.. actually I reported this into graphql-config month ago.

I think this is bug.. about relative paths... actually I want to have at least 2 applications for one prisma server.. its usually 1) app 2) admin... pretty logical.. different endpoints.. different auth rules, security flows and so on.

so structure to be like that:

- workspace
   .graphqlconfig
   - servers
   --- prisma
   --- app
   --- admin

and I want auto update schemas in all applications when I change prisma schema... current approach support updating only one app.. well.. maybe i'm wrong.. this type of project structure looks to me pretty logical, but i'm not able to configure it properly for some reason.

**Comment by marktani** [comment]
Could you share the link to the issue you already reported?
Let's continue this conversation in that issue, to have all relevant information in one place.

**Comment by artem-korolev** [comment]
https://github.com/graphql-cli/graphql-cli/issues/340
https://github.com/prisma/graphql-config/issues/100
