### ISSUE TITLE
Aggregate function is missing typing for `where`

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma#2959]
In the new aggregate function the types are not generated properly and `where` is missing

<img width="470" alt="Screenshot 2020-07-08 at 13 50 21" src="https://user-images.githubusercontent.com/7753942/86886922-f8c59000-c121-11ea-894c-2b60229ea59a.png">

**Comment by pantharshit00** [comment]
I can confirm this: 
<img width="701" alt="image" src="https://user-images.githubusercontent.com/22195362/87091080-b487dc00-c256-11ea-8f10-af13643f86de.png">


This bug invalidates the examples that is shown in the release notes. We will need to fix this. 

Reproduction:
```prisma
generator client {
  provider             = "prisma-client-js"
  experimentalFeatures = ["aggregateApi"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id   Int    @id
  age  Int
  name String
}

```

Generate client from this model and investigate the types.

**Comment by Jolg42** [comment]
Thanks a lot for reporting 🙏

This issue is fixed in the latest version of @prisma/client: 2.2.1
