### ISSUE TITLE
TypeScript types are not reloaded in editors

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#2962]
When changing the schema and regenerating the client, VSCode and other editors don't pick up the change in the TypeScript types.
This is not necessarily a bug in Prisma, but it significantly affects the developer experience.

## Reproduction
```bash
mkdir repro
cd repro
npx @timsuchanek/auto prisma
// open vscode and open main.ts
// edit schema.prisma
// run prisma generate
// types are not updated
// try to trigger reload by hand like so:
rm -rf node_modules && yarn
// now PrismaClient is even typed `any`

```

**Comment by Jolg42** [comment]
@timsuchanek is that a duplicate of https://github.com/prisma/prisma/issues/2771 ?

**Comment by timsuchanek** [comment]
@Jolg42 no, this is an actionable specific issue with a reproduction that can be closed, while #2771 is a more general issue.

**Comment by carmenberndt** [comment]
This issue is fixed by https://github.com/prisma/language-tools/pull/357 for VSCode.

**Comment by otaviobps** [comment]
Any way to fix it in Webstorm? I'm having the exact same issue, and I have to delete `node_modules` and install again

**Comment by janpio** [comment]
I think this is a workaround for Webstorm: https://github.com/prisma/prisma/issues/2359#issuecomment-739921212

**Comment by pantharshit00** [comment]
I am going to close this as this no longer happens in VSCode. If this is happening for your editor, please open a new issue about that.

**Comment by Jolg42** [comment]
@pantharshit00 I think this still happens with VS Code but is solved by using the Prisma extension:
https://marketplace.visualstudio.com/items?itemName=Prisma.prisma
