### ISSUE TITLE
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again. with Nexus

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma#2963]
## Bug description

I had an old project (~6 months old) which I tried converting to Prisma as of the official release but got a weird bug so I stopped it. Now I updated dependencies again to use aggregation (v2.2.0) & now got this error (I used `DEBUG=*` flag):

```bash
➜ npm run dev

> node-graphql@1.0.0 dev ~/server
> nexus dev

  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +3ms
  express:application set "etag fn" to [Function: generateETag] +2ms
  express:application set "env" to 'development' +5ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +1ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '~/server/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
2129 ● nexus:plugin:nexusPluginPrisma Running generators
 711 ● nexus:dev start  --  version: '0.25.0'
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +2ms
  express:application set "etag fn" to [Function: generateETag] +1ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +1ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '~/server/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +2ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +1ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '~/server/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
1311 ✕ app unhandledRejection
       | error  Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
       |        In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.
       |            at new PrismaClient (~/server/node_modules/nexus-plugin-prisma/node_modules/.prisma/client/index.js:3:11)
       |            at instantiatePrismaClient (~/server/node_modules/nexus-plugin-prisma/dist/framework/lib/prisma-client.js:42:16)
       |            at Object.getPrismaClientInstance (~/server/node_modules/nexus-plugin-prisma/dist/framework/lib/prisma-client.js:56:32)
       |            at Object.run (~/server/node_modules/nexus-plugin-prisma/dist/framework/runtime.js:35:50)
       |            at ~/server/node_modules/nexus/dist/lib/plugin/load.js:32:23
       |            at Array.map (<anonymous>)
       |            at Object.importAndLoadRuntimePlugins (~/server/node_modules/nexus/dist/lib/plugin/load.js:30:10)
       |            at Object.assemble (~/server/node_modules/nexus/dist/runtime/app.js:70:42)
       |            at eval (eval at main (~/server/node_modules/nexus/dist/lib/watcher/runner.js:78:5), <anonymous>:23:20)
       |            at main (~/server/node_modules/nexus/dist/lib/watcher/runner.js:78:5)
```

`~/server` is the folder name :)

## How to reproduce

Idk

## Expected behavior

It should work as it used to. My changes from old `nexus` with new `nexus` are perfect.

## Environment & setup

- OS: Mac OS
- Database: SQLite
- Prisma version: @prisma/cli: 2.2.0
- Node.js version: v14.4.0

**Comment by Jolg42** [comment]
It's probably unrelated but I would recommend to stay on Node.js LTS v12 for now (https://nodejs.org/en/about/releases/)

**Comment by deadcoder0904** [comment]
Used v12.18.2 with https://github.com/Schniz/fnm but still same issue

**Comment by nealoke** [comment]
Same issue, v2.1.3 was working fine (and still is), upgrading to 2.2.0

> You most likely forgot to initialize the Prisma Client. Please run `prisma2 generate` ...

**Comment by Jolg42** [comment]
Could you add which version of `nexus-plugin-prisma` is breaking (and any other Prisma / Nexus related things)?

**Comment by Weakky** [comment]
The reason for this is very likely to be because you have kept your prisma dependencies installed. `nexus-plugin-prisma` bundles its own Prisma dependencies, so you must uninstall all prisma related dependencies from your project

**Comment by jasonkuhrt** [comment]
@deadcoder0904 refer to https://nexusjs.org/nexus-plugins/prisma#installation

**Comment by pantharshit00** [comment]
Without a reproduction, we really can't do anything here. Inspect the prisma version using `yarn why` and make sure you don't have anything worth investigating there

**Comment by janpio** [comment]
`npm list` might also be interesting here so we can get an overview what packages exactly are installed.

**Comment by deadcoder0904** [comment]
@Weakky was right. I did the following & it worked:

```bash
$ npm uninstall @prisma/cli @prisma/client
```

Also, had to prune `node_modules`, installed dependencies again with `npm i` & generated prisma using `prisma generate` to make it work :)

**Comment by sreuter** [comment]
For me it was something else in case somebody still has problems: 

I had to remove `output   = "./generated/client"` from my `schema.prisma`, so `npx prisma generate` actually creates the client in the right location.

**Comment by TeemuKoivisto** [comment]
In my case I was using a custom path for the generated types which didn't update the `@prisma/client`. However, as I am using a monorepo I was able to simply point out the `generated/index.js` and `generated/index.d.ts` as the `"main"` and `"types"` files in my package.json. Then instead of importing `@prisma/client` I would import this package with eg `@my-app/db`.

**Comment by iurymanhaes** [comment]
try this, in settings.json 

"[prisma]": {
        "editor.defaultFormatter": "Prisma.prisma"
    }

**Comment by gurerd2** [comment]
I had the same problem -- I was using Nexus with Prisma.  sreuter's solution worked for me.

**Comment by wereallmonks** [comment]
This solution worked for me using next with prisma https://flaviocopes.com/prisma-fix-initialize-yet-vercel/

**Comment by Furkan-Gulsen** [comment]
Check the database server you have connected. I was using Postgresql and when I was running NestJS I got this error because Postgres server was not up.
So check if the server you are connecting NestJS to is up.

**Comment by Dunsin-cyber** [comment]
yarn run prisma generate --schema=./src/prisma/schema.prisma is all I had to do

**Comment by akunlee** [comment]
well!It's been a long time.first,you should execute `npm install prisma`,remember the prisma's version must the same as '@prisma/client',you can see the version in package.json.and then add the script "postinstall": "prisma generate --schema=./prisma/schema.mysql.prisma" in package.json.at last,you can execute `npm run postinstall`,that's effective for me!

**Comment by iamrosada** [comment]
I had the same problem. I'm using ubuntu 20.10

First I deleted node_modules, then installed it again.


Second, I installed the prism globally.
``npm install -g prisma``

but I did it with ``sudo``, so it was like this ``sudo npm install -g prism``

then I tested the ``prisma ``command, in the terminal to see if everything was ok.

now I must generate the prism client.

I did as follows

``sudo prisma generate``
![Screenshot from 2022-10-29 13-46-19](https://user-images.githubusercontent.com/59142372/198827335-e2393d29-907e-497a-901a-9ce20b93f6f1.png)

**Comment by zaadevofc** [comment]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/93970726/226303089-380a1f4c-d9e7-4495-95d4-4767ca68105f.png">


I got this error while deploying on vercel, is there something wrong with the configuration?

**Comment by TeemuKoivisto** [comment]
@zaadevofc yes you should run `prisma generate` before building your app. If you have a monorepo and prisma is separated into its own package, you should copy the generated client as well to your eg `api` package in `.prisma` folder. You can check how I do it here https://github.com/TeemuKoivisto/sveltekit-monorepo-template

**Comment by zaadevofc** [comment]
> @zaadevofc ya, Anda harus menjalankan sebelum membangun aplikasi Anda. Jika Anda memiliki monorepo dan prisma dipisahkan ke dalam paketnya sendiri, Anda harus menyalin klien yang dihasilkan juga ke paket misalnya Anda di folder. Anda dapat memeriksa bagaimana saya melakukannya di sini https://github.com/TeemuKoivisto/sveltekit-monorepo-template`prisma generate``api``.prisma`

I am very grateful for your help, now my problem is solved 😊🫡

**Comment by gitdev5252** [comment]
Hello guys.
I am getting stress from the following errors.
Please help me so I can eliminate these errors.
"
[Nest] 34080  - 06/15/2025, 9:52:45 AM   ERROR [ExceptionHandler] Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
    at new PrismaClient (E:\projects\nestjs\firesight-backend\node_modules\.prisma\client\default.js:43:11)
    at new PrismaService (E:\projects\nestjs\firesight-backend\src\infrastructure\prisma\prisma.service.ts:10:5)
    at Injector.instantiateClass (E:\projects\nestjs\firesight-backend\node_modules\@nestjs\core\injector\injector.js:373:19)
    at callback (E:\projects\nestjs\firesight-backend\node_modules\@nestjs\core\injector\injector.js:65:45)
    at async Injector.resolveConstructorParams (E:\projects\nestjs\firesight-backend\node_modules\@nestjs\core\injector\injector.js:145:24)
    at async Injector.loadInstance (E:\projects\nestjs\firesight-backend\node_modules\@nestjs\core\injector\injector.js:70:13)
    at async Injector.loadProvider (E:\projects\nestjs\firesight-backend\node_modules\@nestjs\core\injector\injector.js:98:9)
    at async E:\projects\nestjs\firesight-backend\node_modules\@nestjs\core\injector\instance-loader.js:56:13
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (E:\projects\nestjs\firesight-backend\node_modules\@nestjs\core\injector\instance-loader.js:55:9)
"
