### ISSUE TITLE
[Re-Introspection] Keep order of fields of existing Prisma schema

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2968]
When you introspect a database with an existing schema.prisma right now the full datamodel part is replaced. This is quite brutal, especially if I spent some time ordering my fields, as all that is gone now.

We could try to keep the order of fields in the datamodel. That would make it possible to look at a diff that is not so drastic.

**Comment by janpio** [comment]
In the meantime we changed Introspection to actually introspect the order of the columns in the database, which opens the door for Prisma to also support changing this order of columns in the future. So we think that your Prisma Schema should now always follow the order of the columns with the order of the fields.

This makes this feature obsolete, so I am going to close the issue.

**Comment by bkrausz** [comment]
Feedback on this: Postgres provides no mechanism to reorder columns short of removing/readding columns/the table, so the order is an arbitrary based on when columns were added. This seems to preclude the idea of Prisma affecting/utilizing this order.

Given that, I believe alphabetical is better in that it's at least predictable, though preservation would be preferred as it allows grouping of similar columns.

**Comment by janpio** [comment]
Thanks @bkrausz, can you also post this at https://github.com/prisma/prisma/issues/3659? That would help us to not accidentally forget it.
