### ISSUE TITLE
Import types only for front-end code

### ISSUE THREAD

**Issue by stijnvanderlaan** [prisma/prisma#2969]
## Problem

I get the next error when I try to import a enum at the front-end of my code:
```
Module not found: Error: Can't resolve 'child_process' in '/Users/stijn/Workspace/demonsters/videochatly/node_modules/@prisma/client/runtime'
```

## Suggested solution
It would be nice I could import the types only:
```js
import { Status } from '@prisma/client/types'
```

**Comment by ryands17** [comment]
Hey @stijnvanderlaan :wave: 
Unfortunately Prisma cannot be loaded in the frontend so you would either have to replicate those types or use a type generator like [this](https://graphql-code-generator.com/) if you're using GraphQL.
