### ISSUE TITLE
Ongoing doc issue checklist

### ISSUE THREAD

**Issue by corysimmons** [prisma/prisma#2973]
There seem to be a lot of little bugs or missing sections that come and go from the docs in various versions.

Opening up issues tends to distract from actual bugs and in my experience doc issues have a tendency to go stale. Can we collect them here in a checklist (point people to this issue)? I'm happy to confirm bugs in here and maintain the checklist in this comment, then Prisma team can just refer to this issue every now and then to chip off a few checkboxes and keep docs 👌

- [ ] https://www.prisma.io/docs/tutorials/ click on "Connect to Prisma from the frontend" in sidebar, nothing happens. Go to https://www.prisma.io/docs/1.13/tutorials/ click on same link, redirects appropriately.

---

If this isn't an approach you're interested in, feel free to close.

**Comment by nikolasburk** [comment]
Hey @corysimmons, thanks so much for your initiative and thoughts! We're currently reworking our docs workflows for issues and general feedback. Although I really like your suggestions (and also _very much_ appreciate your offer to maintain the issues), for that new workflow, we'll keep using individual GitHub issues to track problems with the docs. Thanks again for thinking along!
