### ISSUE TITLE
How Resolvers resolve user data even though in query we only specify few info, is it looking through the schema ?

### ISSUE THREAD

**Issue by heygema** [prisma/prisma#2984]
I've got extra information when I tried to get user Data from the playground with login mutation

```
async function login(
  root: Root,
  args: LoginArguments,
  context: Context,
  info: Info,
) {
 // here only specify id and password.
  let user = await context.db.query.user(
    {where: {email: args.email}},
    ` { id password} `,
  );

  if (!user) {
    throw new Error('User is not found');
  }

  let valid = await bcrypt.compare(args.password, user.password);

  if (!valid) {
    throw new Error('Invalid Password');
  }

  let token = jwt.sign(
    {
      userId: user.id,
    },
    APP_SECRET,
  );

  return {
    token,
   // here why this has all info e.g firstName, lastName, role, etc ?
    user,
  };
}
export {createUser, login};

```

**Versions (please complete the following information):**
 - OS: OS X High Sierra,
 - CLI:  prisma/1.15.1, node-v10.4.0
 - Prisma Server: 1.13
 - `graphql-cli`, `prisma-binding`, `graphql-yoga`

**Comment by divyenduz** [comment]
Can you please share a minimal reproduction? That I can test at my end. Thanks! 
Ideally, if you are not passing the info object, you should be able to specify the field selection. 

Thanks!

**Comment by heygema** [comment]
Nevermind, I figured if my assumption is correct it actually resolve the all the info options from the Schema definition.

so in schema AuthPayload is defined as 
```
type AuthPayload {
 token: String!
 user: User
}
```
so that's why I'm able to get all the rest of user info, even though I didn't specify it in
```
  let user = await context.db.query.user(
    {where: {email: args.email}},
    ` { id password} `,
  );
```

then I just return 
```
return {
    token,
    user,
  };
```
it knows by itself, that I'm returning a user type, so password won't be able to fetched. because in schema it is not defined.
