### ISSUE TITLE
Improve tests in `cli` (currently using Mocha)

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#2986]
Tests in https://github.com/prisma/prisma/tree/master/src/packages/cli/src/__tests__/

They run on Mocha while we are using Jest everywhere else.
Each new Mocha test now require a manual edit of the package.json.

Maybe it makes sense to keep Mocha for the integration tests but we should use Jest for the rest.

TODO
- [ ] Adding Jest along Mocha
- [ ] Fix doctor test @timsuchanek

**Comment by janpio** [comment]
That should also allow running all tests even though an early one fails if I understood you correctly @Jolg42?

**Comment by Jolg42** [comment]
Yes indeed because we run them like this https://github.com/prisma/prisma/blob/09cb4a26e5e4fb147c29feb3acdecd523df795cf/src/packages/cli/package.json#L129 (npm script) and this is not optimal

**Comment by Jolg42** [comment]
Duplicate of #3004
