### ISSUE TITLE
Prisma playground always opens in browser

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2987]
**Describe the bug**
Running `prisma playground` opens the Playground in the browser when Electron app is installed.

**To Reproduce**

1. Deploy a new Prisma service
2. Run `prisma playground`

**Expected behavior**

Running `prisma playground` when Electron app is installed opens Playground in Electron app.

**Versions (please complete the following information):**
 - `prisma` CLI: `prisma/1.15.1 (darwin-x64) node-v10.8.0`

**Additional context**

Regression from #2919.

**Comment by Huvik** [comment]
😱

**Comment by Huvik** [comment]
🔜

**Comment by timsuchanek** [comment]
This has been fixed.
