### ISSUE TITLE
Create on a model with a required native type fails with "Null constraint violation" 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3007]
## Bug description

If Prisma client "create" is used after introspecting a database with a model that has a required native type. It fails with null constraint violation. 

## How to reproduce

1. Run this SQL (MySQL) on a database. The issue has also been observed in Postgres. 

```
create table n (
  `id` bigint(20) NOT NULL,
  `data` binary(10) NOT NULL,
  PRIMARY KEY (`id`)
);
```

2. Introspect

```
model n {
  id Int @id
  // This type is currently not supported.
  // data binary
}
```

3. Generate client and run

```
const data = await prisma.n.create({
  data: {
    id: 1,
  },
})
```

4. The following error can be observed

```
divyendusingh [p2-native-required]$ node index.js
(node:5919) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.n.create()` invocation in
/Users/divyendusingh/Documents/prisma/p2-native-required/index.js:7:31

   3
   4 const prisma = new PrismaClient()
   5
   6 async function main() {
→  7   const data = await prisma.n.create(
  Null constraint violation on the fields: (`data`)
    at PrismaClientFetcher._request (/Users/divyendusingh/Documents/prisma/p2-native-required/node_modules/@prisma/client/runtime/index.js:1:206978)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5919) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

## Expected behavior

I am not entirely sure if this is even a bug or just a missing feature, the premise of commenting out native types was to move as far in the process as possible. Maybe for the time being, we can document a workaround to make the native types nullable, if possible or show a better error message when we encounter this. 

## Prisma information

```
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/p2-native-required/node_modules/.bin/prisma --version
@prisma/cli          : 2.3.0-dev.12
Current platform     : darwin
Query Engine         : query-engine 68efc71c4b657c5dbd59b177ecf2daf18e5b0201 (at /Users/divyendusingh/Documents/prisma/p2-native-required/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 68efc71c4b657c5dbd59b177ecf2daf18e5b0201 (at /Users/divyendusingh/Documents/prisma/p2-native-required/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 68efc71c4b657c5dbd59b177ecf2daf18e5b0201 (at /Users/divyendusingh/Documents/prisma/p2-native-required/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 68efc71c4b657c5dbd59b177ecf2daf18e5b0201 (at /Users/divyendusingh/Documents/prisma/p2-native-required/node_modules/@prisma/cli/prisma-fmt-darwin)
Done in 1.77s.
```

Test Utils databases affected: 

- postgres/sonarqube

**Comment by regirock365** [comment]
Any updates in this issue?

**Comment by matthewmueller** [comment]
Ah, right. This makes sense. If we don't support a type that contains a not null constraint, you won't be able to create a record on that table. 

The solution is to remove the not null constraint on `data`. This limitation will be lifted as we add support for more native data types.

@regirock365 are you running into this with the binary type? Or some other type? Maybe we can focus on solving your existing problem first.
@divyenduz did the original request come from a user?

**Comment by divyenduz** [comment]
@matthewmueller No, this was a part of the Introspection CI analysis effort in which we ran various CRUD operations on top of Prisma client. It was found to happen in this database: https://github.com/prisma/database-schema-examples/blob/main/postgres/sonarqube/schema.sql

**Comment by regirock365** [comment]
> @regirock365 are you running into this with the binary type? Or some other type? Maybe we can focus on solving your existing problem first.

Turns out my problem was something different. I have it resolved now.

**Comment by matthewmueller** [comment]
This will be solved by: https://github.com/prisma/prisma/issues/1747
