### ISSUE TITLE
Prisma creates incorrect relations if a bogus relation name is set

### ISSUE THREAD

**Issue by ejoebstl** [prisma/prisma#3012]
**Describe the bug**
If the relation name is set to the name of an existing automatically-generated relation, prisma will generate a CRUD schema with incorrect relations types. 

**To Reproduce**
Create a new service with the following datamodel: 

```
type A {
    field: Int
    b: B
}

type B {
    field: Int
    a: A
    c: C @relation(name: "AToB")
}

type C {
    field: Int
    b: B @relation(name: "AToB")
}
```

Prisma will associate `C.b` with `A` instead of `B`. All input types and output types will be generated according to this incorrect association. 

Attempting to create a node of `C` with an associated node of type `B` leads to an internal server error: 

```
mutation test1 {
  createC(data: { field: 10, b: { create: { field: 15 } } }) {
    field
    b {
      field
    }
  }
}
```

**Expected behavior**
It should not be possible to create such a relation, the name should be reserved and the creation should fail with an error.

**Comment by do4gr** [comment]
This was fixed by https://github.com/prisma/prisma/pull/3971
