### ISSUE TITLE
DateTime default functions for Existing PostgreSQL?

### ISSUE THREAD

**Issue by james-ff** [prisma/prisma#3014]
Hi, I'm wondering what the current solution is to this error for an existing postgres db: 
`Invalid value 'CURRENT_DATE' for type DateTime`.
- The name of this field is "date_created" and is used in all of my tables.

Are there plans to support CURRENT_DATE and similar defaults in the near future?
- And until then what do we do in the meantime?

Additional Questions: 
- Does this occurr for other default functions?
- Would it be ok to remove defaults from a datamodel.graphql that doesn't support migrations (i.e. an existing database), as there isn't any need for graphql to know?

Many Thanks.

**Comment by goulderb** [comment]
@james-ff If your use case is just having a field for the date a record was created, prisma automatically adds this to all your schema as "createdAt", even if it isn't in your type declarations. Adding this to your type declarations will expose it and let you use it.

That said, to my knowledge there is no way to specify a dynamic default like CURRENT_DATE in prisma right now. The work around for now would be to enforce this in a layer over top of prisma, such as a graphql-yoga server.

**Comment by james-ff** [comment]
@goulderb I maybe should have made the following clearer, my bad:

My use case is with migrations turned off for an existing database. In this case Prisma does not modify my database schema at all. The date fields I have are set up like this in my database schema and have been introspected into the Prisma type declarations (datamodel.graphql) along with their defaults.

Postgres schema datetime definition:
```sql
date_created DATE NOT NULL DEFAULT CURRENT_DATE
```

Example of Prisma datetime field generated from introspection.
```gql
date_effective: DateTime! @default(value: "CURRENT_DATE")
```

This issue concerns the existence of default functions / expressions in the Prisma type declarations for a non-migration setup of Prisma.

With this setup, is it ok to remove the default decorators in Prisma, and are there any considerations around doing so? And should they be introspected by prisma in the first place.

I guess this issue is for the team at Prisma that is developing the existing postgres use case for Prisma.
