### ISSUE TITLE
Allow alias of scalar types

### ISSUE THREAD

**Issue by chasm** [prisma/prisma#3015]
**Is your feature request related to a problem? Please describe.**

I use a __schema query to provide metadata for CRUD forms. I want to be able to validate on the basis of type. If I have an email address or a URL, for example, I'd like to be able to see that the type is Email or Url rather than just String, so I can validate accordingly.

**Describe the solution you'd like**

`type Email alias String` or something like that.

**Describe alternatives you've considered**

Currently, I have two workarounds. One is to go by the name of the field and disregard the scalar type (e.g., a field `email` would be assumed to be of type Email, even though there is no such type). That's pretty brittle and ugly.

The other workaround is to create an Object type, e.g., 

```
type Html {
  html: String!
}
```

But that adds an unnecessary and painful extra layer. If I'm storing HTML as a string, I'd like to just alias the String scalar as an HTML scalar.

**Additional context**

A good example of this in programming is Haskell's type synonyms.

**Comment by divyenduz** [comment]
@chasm : Thanks for raising this issue. I think what you are suggesting can be resolved by using Custom scalars. While custom scalars are not supported within the Prisma API yet you can do that at the GraphQL server level. 

Here is a related discussion: https://github.com/prisma/graphql-yoga/issues/30

Please let me know if this answers your question.
