### ISSUE TITLE
Should CI trigger e2e tests when releasing? (and maybe wait for the tests to pass)

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#3015]
Right now the e2e tests are continually watching the npm tags to find new ones and then the tests happen.

This works but means that before hitting the release button we have to wait for the e2e tests to start and pass for the `dev` tag and that takes around 20-30 minutes (~ approximately).
Also we only know if the `latest` passes e2e tests after it's released.

I don't know how much work would be needed for that @janpio

**Comment by pantharshit00** [comment]
ping @Jolg42 

Is this still relevant?

**Comment by Jolg42** [comment]
We can close for now I think!
