### ISSUE TITLE
[Re-Introspection] After renaming table only some of its relations are renamed

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma#3018]
## Bug description

When renaming one table and running retrospection, the result will be invalid, as only some (tables that depend on the renamed table?) get their relation name changed.

## How to reproduce

1) Create schema/DB:
```graphql
model Cart {
  cartID        Int        @default(autoincrement()) @id
  endPeriodID   Int
  startPeriodID Int
  PeriodEnd     Period     @relation("Cart_endPeriodIDToPeriodWithWrongName", fields: [endPeriodID], references: [periodID])
  PeriodStart   Period     @relation("Cart_startPeriodIDToPeriodWithWrongName", fields: [startPeriodID], references: [periodID])
}

model PeriodWithWrongName {
  periodID        Int          @default(autoincrement()) @id
  CartEndPeriod   Cart[]       @relation("Cart_endPeriodIDToPeriodWithWrongName")
  CartStartPeriod Cart[]       @relation("Cart_startPeriodIDToPeriodWithWrongName")

  @@map("obdobi")
}
```
2) Rename table `PeriodWithWrongName` to `Period` (using map)
3) run `prisma introspect --experimental-reintrospection`
```graphql
model Cart {
  cartID        Int        @default(autoincrement()) @id
  endPeriodID   Int
  startPeriodID Int
  PeriodEnd     Period     @relation("Cart_endPeriodIDToPeriod", fields: [endPeriodID], references: [periodID])
  PeriodStart   Period     @relation("Cart_startPeriodIDToPeriod", fields: [startPeriodID], references: [periodID])
}

model Period {
  periodID        Int          @default(autoincrement()) @id
  CartEndPeriod   Cart[]       @relation("Cart_endPeriodIDToPeriodWithWrongName")
  CartStartPeriod Cart[]       @relation("Cart_startPeriodIDToPeriodWithWrongName")

  @@map("PeriodWithWrongName ")
}
```

## Expected behavior

Running `prisma introspect --experimental-reintrospection` should not break the schema.

## Prisma information

above

## Environment & setup

- OS: Win
- Database: MySQL
- Prisma version: 2.2.2
- Node.js version: 14

**Comment by do4gr** [comment]
Hey, @Akxe,

I tried reproducing your issue here https://github.com/prisma/prisma-engines/pull/945 . 
I created two relations between the same models, renamed one of the models using `@@map` and then ran Re-Introspection which returned the expected result. 

Can you provide a minimal example including a SQL dump maybe? Then I can look into this further.

**Comment by janpio** [comment]
Ping @Akxe

**Comment by Akxe** [comment]
Hi, sorry I was too busy. As I tested it now, it no longer applies. Not sure what changed, but you fixed it, hurry! 😀

**Comment by janpio** [comment]
Perfect answer, thanks :D
