### ISSUE TITLE
CLI to specify which prisma.yml

### ISSUE THREAD

**Issue by patrickdevivo** [prisma/prisma#3029]
**Is your feature request related to a problem? Please describe.**
Not a huge problem, but if I have a `datamodel.graphql` that I'd like to deploy to multiple prisma endpoints (say, a dev and prod), I have to manually edit (comment/uncomment) the `endpoint` in my `prisma.yml` (unless someone has a better workaround)

**Describe the solution you'd like**
It would be awesome if there were a way to pass in a flag to the cli such as `--config` or similar to let me specify which `yaml` file to use for the prisma config. Such as `prisma deploy --config prisma.dev.yml`

**Describe alternatives you've considered**
Maybe this is possible through env vars already? It also seems possible by passing the `-n` flag and manualy entering a different endpoint (but this is a bit clumsy)

**Additional context**
N/A

**Comment by jhalborg** [comment]
You should use environment variables for this, i.e.

```
endpoint: ${env:PRISMA_ENDPOINT}
secret: ${env:PRISMA_SECRET}
```

Then, for example in your `.env.local`, you might have
```
PRISMA_ENDPOINT="http://127.0.0.1:4466"
PRISMA_SECRET="someapisecret"
```

and maybe a script like this:
`"prisma-deploy:local": "yarn prisma deploy -e .env.local",`

**Comment by patrickdevivo** [comment]
Hi @jhalborg, I see that's very helpful. I take it the `prisma cli` is then parsing the `.env` file and rendering it into the yaml for me?

**Comment by dannysofftie** [comment]
For anyone having the same issue, the docs specify how to pass config file to use to generate prisma client.

```bash
npx prisma1 generate -p path/to/prisma.test.yml
```

Refer [docs here](https://www.prisma.io/docs/1.34/prisma-cli-and-configuration/cli-command-reference/prisma-generate-xcv2/) for more.
