### ISSUE TITLE
Split up `prisma.graphql` and `prisma.ts` into multiple files

### ISSUE THREAD

**Issue by jhalborg** [prisma/prisma#3033]
**Is your feature request related to a problem? Please describe.**
As the project grows and changes are made to the data models, `prisma.ts` and `prisma.graphql` grows fast to thousands of lines, making versioning and handling them cumbersome. For example, Sourcetree hangs for several seconds each time it has to process changes to these files. 

**Describe the solution you'd like**
The files generated in the `/generated` folder could be slit up by models and imported to an `index` file for each, making managing changes to the files much easier on the developer and his/her computer 😄 

**Describe alternatives you've considered**
Not having generated files in VCS, but we prefer it in our team.

**Comment by timsuchanek** [comment]
This suggestion has been taken into account and is already the default in the latest version!
