### ISSUE TITLE
Docs crash when typing in search bar

### ISSUE THREAD

**Issue by liamdanielduffy** [prisma/prisma#3035]
**Describe the bug**
When I begin to type in the search bar at the top of the docs, the docs disappear and display ""An unexpected error has occurred.

**To Reproduce**
1. Go to Prisma Docs (new) https://www.prisma.io/docs/
2. Begin typing in search bar
3. See error

**Expected behavior**

**Screenshots**
<img width="878" alt="screen shot 2018-09-06 at 6 11 36 pm" src="https://user-images.githubusercontent.com/7659261/45158115-ac952600-b200-11e8-8ad5-e65bd835c470.png">

**Comment by brikou** [comment]
Seems like algolia widget is broken...

**Comment by timsuchanek** [comment]
Thanks for reporting! We just deployed a fix.
