### ISSUE TITLE
Prisma Client is generated twice when `output` is specified on `generator`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3036]
When a custom `output` is specified for the `generator` block, Prisma Client gets generated twice:

- the target location specified by `output`
- `node_modules`

For example, I have this generator definition:

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../src/generated/prisma"
}
```

Now I have Prisma Client in both locations `../src/generated/prisma` and `node_modules`. I can, therefore, import it from two locations as well:

```ts
import { PrismaClient } from './src/generated/prisma'
// or
import { PrismaClient } from '@prisma/client'
```

**Comment by pantharshit00** [comment]
I can confirm this. CLI will also try to install `@prisma/client` if I already have the cli and output is also specified.

**Comment by timsuchanek** [comment]
> CLI will also try to install @prisma/client if I already have the cli and output is also specified.

Can you elaborate on that / create reproducible steps please? This doesn't sound like it should be

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by pantharshit00** [comment]
@timsuchanek 

Have the following package.json and try generating the client:
```json
{
  "name": "prisma-sqlite",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@prisma/cli": "2.4.0-dev.2"
  },
  "devDependencies": {
    "@types/node": "^13.11.1",
    "ts-node": "^8.8.2",
    "typescript": "^3.8.3"
  },
  "scripts": {
    "start": "ts-node main.ts",
    "generate": "prisma generate"
  }
}
```

It will try to install `@prisma/client` which should not happen

**Comment by janpio** [comment]
> It will try to install `@prisma/client` which should not happen

Why should that not happen? How is this related to the folder where the files are output to?

**Comment by pantharshit00** [comment]
@janpio The output is also specified, so it should not install the `@prisma/client` as that won't be used anyways.

**Comment by janpio** [comment]
`@prisma/client` is the generator package that is required to generate Prisma Client in the first place.

**Comment by pantharshit00** [comment]
Oh, I wasn't aware it was moved there. It used to be just facade package. No need for this change now 👍
