### ISSUE TITLE
Some (Array?) Relationships Lost on Import/Export

### ISSUE THREAD

**Issue by aaronbolyard** [prisma/prisma#3036]
**Describe the bug**
When importing (or exporting?) a database, some array relationships are lost. (See the example data model at the end). I'm not sure if I'm only getting a partial database export or it's only performing a partial import or if it's certain relationships in the data model.

**To Reproduce**
1. Run `prisma export` on the source server
2. Run `prisma import` on the destination server

**Expected behavior**
I expect the data on the destination server to be identical to the data on the source server, but nested array relationships are lost.

**Versions (please complete the following information):**
 - OS: Windows 10
 - `prisma` CLI: I don't know what information this is requesting.
 - Prisma Server: 1.15

The source server is running on prisma.io. The destination server is a local Docker container on Windows 10 using the docker-compose generated by `prisma init`. I have tried using both Postgres and MySQL as back ends, no change.

**Additional context**
Here is the relevant portion of the data model:

```
type Page {
  id: ID! @unique
  name: String!
  type: PAGE_TYPE! @default(value: DEFAULT)
}

enum PAGE_TYPE {
  DEFAULT
  PREP_SHEET
  WEEK_PAGE
}

type Week {
  id: ID! @unique
  name: String!
  prepSheet: Page @relation(name: "PrepOnWeek", onDelete: CASCADE)
  days: [Day!]! @relation(name: "DaysOnWeek", onDelete: CASCADE)
  hasGameDay: Boolean @default(value: "true")
}

type Day {
  id: ID! @unique
  name: String!
  pages: [Page!]! @relation(name: "PagesOnDay", onDelete: CASCADE)
}
```

After running this query between import/export:

```
query {
  weeks {
    days {
      id,
      pages {
        id,
        name
      }
    }
  }
}
```

It gives this:

```
{
  "data": {
    "weeks": [
      {
        "days": [
          {
            "id": "cjlqoo5rd006q09047xv3h4zj",
            "pages": []
          },
          {
            "id": "cjlqoo5rr007a090418wc9qpj",
            "pages": []
          }
        ]
      },
      /* .... */
```

The `pages[]` arrays are empty when they shouldn't be. The data is lost. Furthermore, the missing pages from the import/export are also missing from the database itself.

**Comment by aaronbolyard** [comment]
I will try my best to produce a small sample, or otherwise censor a selection of our current data and provide that.

**Comment by marktani** [comment]
In your exported `zip` folder, does the `lists` folder include the expected list data?

> prisma CLI: I don't know what information this is requesting.

This is asking about your Prisma CLI version: `prisma version`. The CLI and the server are two separate components with potentially different versions.

> Prisma Server: 1.15

Note that the demo server's version is currently `1.17-beta-1`. I assume that with `1.15`, you are referring to your local Prisma server.

**Comment by aaronbolyard** [comment]
The lists folder includes an empty JSON file.

I'll check what Prisma CLI version I have at work.

**Comment by marktani** [comment]
Ok, this means that your data is either not there in the original service, or the export is not successful.

**Comment by aaronbolyard** [comment]
The data is there in original service.

What would cause the export to fail and why would I not be warned the export failed?

**Comment by marktani** [comment]
I have not seen this before, this is on us to find out together 🙂

The first thing I would like to learn more about: is this caused by an inconsistency to your specific service, or can this be reliably reproduced with the same datamodel on a different server + database combination.

**Comment by aaronbolyard** [comment]
I need to get permission but if I do, I'll write a script to create bogus data to populate an empty database to see if the problem persists. I'll get back later today.

**Comment by Nedomas** [comment]
@aaronbolyard Did you manage to solve the problem?

We have a similar problem in another app, but when I try to recreate it in a clean prisma app - the bug does not reoccur. Here's a small example where the scenario is exactly as yours, but the bug DOES NOT happen: https://github.com/Nedomas/prisma-nested-export-example

Makes me wonder if this is actually related to the way relationships are set up.
