### ISSUE TITLE
the text on the error notifications in the playgraound is invisible when using firefox

### ISSUE THREAD

**Issue by lidorcg** [prisma/prisma#3037]
**Describe the bug**
The text on the error notifications in the playgraound is invisible when using firefox

**To Reproduce**
1. open the playground with firefox
2. write an errorsome query
3. point the pointer to the error

**Expected behavior**
If you color the text black it appears

**Screenshots**

![transperant-text-bug](https://user-images.githubusercontent.com/11412645/45181503-538cb880-b227-11e8-98ed-f556d1a1ed63.jpg)

**Versions (please complete the following information):**
 - OS: `Ubuntu 18.04`
 - `prisma` CLI: [`prisma/1.15.3 (linux-x64) node-v10.9.0`]

**Comment by captDaylight** [comment]
Maybe makes sense to add this to https://github.com/prisma/graphql-playground instead.

**Comment by divyenduz** [comment]
@lidorcg : Did you move this issue to playground? If so, please link that here and close this one. Thanks. 🙌

**Comment by lidorcg** [comment]
moved to:
[#832](https://github.com/prisma/graphql-playground/issues/832)
