### ISSUE TITLE
No warning is printed when `@prisma/cli` and `@prisma/client` have different versions in `package.json`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3037]
It's possible to specify different versions of the `@prisma/cli` and `@prisma/client` in `package.json` and users will not get a warning that they did this and might run into weird behaviour because of this (it's also unclear which version of Prisam Client would be generated when the packages have different versions). For example, I have this `package.json`:

```json
{
  "name": "script",
  "license": "MIT",
  "devDependencies": {
    "@prisma/cli": "2.0.0",
    "ts-node": "8.10.2",
    "typescript": "3.9.6"
  },
  "scripts": {
    "dev": "ts-node ./script.ts"
  },
  "dependencies": {
    "@prisma/client": "2.2.2",
    "@types/node": "13.13.14"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}
```

When running `npm install` and `npx prisma generate`, the CLI output looks normal and doesn't give me a heads-up that the packages have different versions. After the client generation, I'm also not sure if the client is now on version `2.2.2` or `2.0.0`.

**Comment by thebiglabasky** [comment]
Is that trivial to achieve? Are there precedents in doing these kinds of things?

I agree that can happen, and don't argue this could be a nice improvement, but wonder if we should handle that ourselves.
If it's trivial to do, we could definitely consider it, otherwise I would rather park that as this is more a general dependency management problem than a Prisma problem per se.

One main consideration: should that be done only upon `prisma generate`, a subset of other commands (e.g. `prisma doctor`) or all commands?

**Comment by timsuchanek** [comment]
Until now, we don't have a practical reason to do this.
The Prisma Client can tell the CLI, which versions of the binaries it needs and downloads the correct ones.
Once that protocol has a breaking change, we can start adding this.

**Comment by thebiglabasky** [comment]
Couldn't that simply warn? I don't think we'd need to go as far as downloading etc. Just checking the version number would be enough?

**Comment by timsuchanek** [comment]
Yes it could also warn, then we would just not rely on the preexisting tools and conventions (peer dependencies) for that anymore.

**Comment by timsuchanek** [comment]
I think peer dependencies just give a warning anyway

**Comment by thebiglabasky** [comment]
After further discussion, it looks like the binary version of the client is not correctly resolved. This should be qualified as a bug and fixed.
We can reconsider adding warnings if this still happens after fixing that.

**Comment by Med5KDB** [comment]
I want to know if this warn may lead to unexpected behavior ?

**Comment by janpio** [comment]
Which warn exactly? Mismatch of Prisma CLI and Prisma Client? Yes, there are combinations where this is not desirable. We suggest to upgrade so both versions match.

**Comment by Med5KDB** [comment]
> Which warn exactly? Mismatch of Prisma CLI and Prisma Client? Yes, there are combinations where this is not desirable. We suggest to upgrade so both versions match.
If no upgrade to match both versions is done and this warn stopped being displayed? What does it mean? Do you still suggesting to upgrade?

**Comment by janpio** [comment]
You should be getting a warning on `prisma generate` on mismatching versions.
Yes, we suggest to use the same versions for CLI and Client so that the warnings goes away and no problems can occur.
