### ISSUE TITLE
Make datasource dynamically configurable

### ISSUE THREAD

**Issue by asktree** [prisma/prisma#3038]
## Problem
I have 2 deployments: development and production.
Development postgres has an external IP and an internal IP. When I'm developing locally, I use the external IP to run `prisma introspect`. In deployment, the internal IP is used.
Production postgres doesn't even have an external IP. 

It would be very easy for me to configure this if I could just specify the database url in a Node file. Right now, I have to specify a dummy value in `schema.prisma` and then use some workaround. If I want to call `prisma introspect`, I have to remove the dummy value temporarily and put in the (secret) external IP url.

## Suggested solution
Give first-class support to using `process.env.DATABASE_URL = foo`, or the `PrismaClient` options.

## Alternatives
Remove the datasource input from the schema file entirely and move it to some sort of `config.js`. 

These proposals would also provide an escape hatch for when your `.env` system has bugs, which I've spent all day trying to solve to no avail.

**Comment by Simonwep** [comment]
I second this, especially if you already have an established setup with like a `development.json`, `test.json` and `production.json` config file it's way more consisted to just store things there and use something like `"passsword": "<password>"` if properties should be kept private.

It'd be great to just pass these things to the `PrismaClient` as it's done with most database drivers.

**Comment by Zhomart** [comment]
Also, please allow reading from `.env`. Currently prisma-cli only reads from `prisma/.env`. Now I have to maintain two different .env files.

**Comment by janpio** [comment]
Please open a new issue for this @Zhomart - this is not directly related to the initial issue here.

**Comment by Simonwep** [comment]
Okay I'm stupid - should've read the docs, @asktree It **is** possible to pass the db-url to the PrismaClient constructor:
```ts
export const db = new PrismaClient({
    datasources: {
        db: {
            url: config.db.url
        }
    }
});
```

See https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/constructor#datasources

**Comment by divyenduz** [comment]
@asktree You can override the datasource in Prisma client constructor https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/constructor#datasources

Does this answer your question?

**Comment by matthewmueller** [comment]
> These proposals would also provide an escape hatch for when your .env system has bugs, which I've spent all day trying to solve to no avail.

@asktree do you mind sharing what problems you've run into with .env?

**Comment by matthewmueller** [comment]
Closing since you can dynamically configure the datasource in the constructor: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/constructor#datasources

If you're still running into problems @asktree, feel free to re-open. Thanks!
