### ISSUE TITLE
Context for accessing fields from one table

### ISSUE THREAD

**Issue by impowski** [prisma/prisma#3042]
**Is your feature request related to a problem? Please describe.**
I want to be able to access current field values inside mutations.
```typescript
  async someResolver(parent, args, ctx: Context, info) {
    return await ctx.db.mutation.updateUser({
      data: {
        someValue: this.otherValue
      }
    }, info)
  }
```

**Describe the solution you'd like**
It should work primarilly with `updates` I guess, and there should be a context which will give an access to current row fields. I guess it will work the same as:
```postgresql
UPDATE users SET someValue = otherValue
```
And it should be able to work with `where` too, so it will not update everythin, just needed rows.

**Comment by impowski** [comment]
Anything on this?

**Comment by divyenduz** [comment]
Are you implying updating a field like incrementing it? Or something else. Can you please elaborate? I am not clear on what is your target. Thanks :)

**Comment by impowski** [comment]
> Are you implying updating a field like incrementing it? Or something else. Can you please elaborate? I am not clear on what is your target. Thanks :)

Yes, like incrementing it or getting value from one column of the table and using it with another. For example with Sequelize it's done through `literal`.
