### ISSUE TITLE
More descriptive error messages on parse failures when introspecting invalid schemas

### ISSUE THREAD

**Issue by Xetera** [prisma/prisma#3044]
## Problem
Trying to change the prisma schema from default database snake_case to camelCase with `@map` is current extremely difficult. For whatever reason, existing tools out there like https://www.npmjs.com/package/prisma-schema-transformer don't work for me with reinspection and cause the entire schema to be reverted to the original database version and I cannot see what the problem is because the only error is
> *** WARNING ***
> The input datamodel could not be parsed. This means it was not used to enrich the introspected datamodel with previous manual changes.

Now I'm left to edit every single field by hand so when the reinspection fails I can go back and deduce the problem based on a few changes but this is extremely time consuming.

## Suggested solution
Tell the user what went wrong when reintrospection fails so the issue can be fixed without prisma completely resetting the schema (which in itself is probably worth a separate issue of its own).

## Alternatives
Currently, it's possible to convert casing by very tediously going through the entire schema and manually changing all types but of course, this is not a good solution.

## Additional context
@prisma/cli version: 2.1.3

**Comment by janpio** [comment]
Re-Introspection probably is giving you all it knows - that the old `schema.prisma` is invalid already.

Can you share the "before" schema?
What command exactly are you running?

If you are using the previous schema file successfully this is most probably something we can fix if we can understand it.

**Comment by Xetera** [comment]
You're probably right, this might not actually be about re-introspection but validating prisma files, apologies for the confusing issue name.

A simple example I can give for what I'm doing is with a schema file like this

```prisma
model groups {
  id Int @id 
  company_id Int
  company companies @relation(fields: [company_id], references: [id])
}

model companies {
  id Int @id
  current_groups groups[]
}
```
where the field `current_groups` is renamed from something else like `groups`. This is the current introspection you get from a database where all tables and columns are named in snake_case.

As far as I know, there's no way to automatically change from snake_case to camelCase, so if at this point I try to rename my tables from `groups` to `Group` using `@@map` (for me this was to get prisma working properly with graphql-nexus which doesn't support plural table names, but it could be for any reason) and switch field names to camelCase using `@map` for consistency, I end up with a schema like.

```prisma
model Group {
  id Int @id 
  companyId Int @map("company_id")
  company Company @relation(fields: [companyId], references: [id])

  @@map("groups")
}

model Company {
  id Int @id
  currentGroups groups[]
  
  @@map("companies")
}
```

when I now run `prisma introspect --experimental-reintrospection` to make sure that my manually changed schema is consistent with what prisma expects, it's going to fail because I didn't rename the `groups[]` type inside `Company` model and not only is it going to fail with an ambigious error message 

> The input datamodel could not be parsed. This means it was not used to enrich the introspected datamodel with previous manual changes.

it's also going to revert my entire schema back to 

```prisma
model groups {
  id Int @id 
  company_id Int
  company companies @relation(fields: [company_id], references: [id])
}

model companies {
  id Int @id
  groups groups[]
}
```
where all the relationship fields I renamed are reset back to their original introspection including the previously successfully renamed `current_groups` field.

This makes it very difficult to try to manually transform the schema, especially when you're working with a large database. In theory, there's https://github.com/IBM/prisma-schema-transformer which should help with this renaming process but the schema it generates is broken for whatever reason and I have no way of knowing what Prisma is having problems with parsing without manually going through 400+ lines of schema file which is just not possible when you're working with a schema that's had almost every single line changed.

I've spent 3+ hours going through my schema to manually rename fields because I cannot change the database itself so it would be really nice to have error messages that can at least point me in the right direction for what went wrong with the introspection.

I found that using `--print` when introspecting the database makes things slightly less chaotic because the schema isn't reset back when you make a mistake but this is still a very frustrating process :disappointed:

**Comment by janpio** [comment]
Ahhhh, now I think I understand what is going on:

By using `prisma introspect --experimental-reintrospection` you are triggering what we internally call "validation". You can a much better error message but without accidental changes to your schema by running `prisma generate` (which runs validation as a first step to check your schema) or `prisma validate` (which only runs the validation bit):

```
C:\Users\Jan\Documents\throwaway\505>prisma validate
Environment variables loaded from prisma\.env
Error: Schema parsing
error: Type "groups" is neither a built-in type, nor refers to another model, custom type, or enum.
  -->  schema.prisma:23
   |
22 |   id Int @id
23 |   currentGroups groups[]
   |

Validation Error Count: 1
```

![image](https://user-images.githubusercontent.com/183673/87936228-c1949e80-ca92-11ea-8e6a-0d49746ef594.png)

Our VSCode extension will already tell you about this when showing the `schema.prisma` file:

![image](https://user-images.githubusercontent.com/183673/87936288-dbce7c80-ca92-11ea-8241-7bd71ae40642.png)

(Using this will also help you understand what goes wrong with https://github.com/IBM/prisma-schema-transformer I guess - its author is certainly happy about issues that highlight problems with it (or we might help out ourselves to fix it if you can write down what is going wrong in an issue over there.))

We will talk internally if we can surface the actual validation errors better during Re-Introspection, and/or highlight the use of `prisma generate/validate` or the VSCode extension to get the actual reason of the validation errors.

---

I think you will very much looooove https://github.com/prisma/language-tools/pull/338 in our VSCode extension soon by the way.

**Comment by janpio** [comment]
@Xetera, this lead to us understanding a blind spot in Re-Introspection a lot better and we will probably rework that flow a bit for the case that there is an invalid schema: https://github.com/prisma/prisma/issues/3082

So thanks for that already, let's hope my previous comment already helps you fix your problem.

**Comment by Xetera** [comment]
Well, that's embarrassing. I should've definitely looked into validation before this but I'm glad I was able to help. Thanks for the explanation, it does solve my problem. I've run into some other issues that are actually related reintrospection this time but as far as this issue is concerned, `prisma validate` is the answer I was looking for here :pray:

**Comment by janpio** [comment]
No, you did everything right and your misunderstanding showed us what we were doing wrong and now we can fix it 👍 

If you encounter any other problems, just open an issue and we are happy to look into them again.
