### ISSUE TITLE
[EPIC] Bring database in sync with schema while prototyping

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma#3050]
## Problem
While getting started with Prisma or prototyping an idea where the model is not clearly defined, people try out different models, before figuring which one is a fit for what they want to do. During this process, it can be painful to make the database changes so that they reflect what's defined in the Prisma schema.
The current solution relies on `prisma migrate` which is experimental, and requires to produce migration files, and a table in the database every time an iteration on the schema is made. This adds friction to the ideation and prototyping process.

## Suggested solution
Propose a simple command which allows to bring up the database schema at par with the Prisma schema, without generating any migration.

Suggested CLI command:
```
prisma schema push
```
This command would "push" the schema so that it gets reflected on the database.
Optionally, it could offer to force the changes and accept data loss, since the goal is to support prototyping in a development environment where data is not yet critical to keep. An option like `--accept-dataloss` or `--force` could be considered.

## Alternatives
Today, the workflow requires to use prisma migrate, delete the generated migration files and the migration table regularly.

**Comment by tomhoule** [comment]
The migration engine part was merged last week: https://github.com/prisma/prisma-engines/pull/949

Remaining work:

- (product) Decide on command naming and arguments
- (CLI) Implement a CLI wrapper around the migration engine command

cc @albertoperdomo @Jolg42

**Comment by albertoperdomo** [comment]
Deemed out of scope (for now): Dealing with any potential changes made to the DB and not reflected in the Prisma schema file. This could be addressed by a combination of introspection and this workflow, potentially.

**Comment by albertoperdomo** [comment]
Naming and arguments considered:

* `schema push`, `schema apply`, to be validated
* default to non-destructive behavior with interactive prompt, can be overridden by passing a `--force` parameter.

**Comment by tomhoule** [comment]
Update: this is implemented as an experiment. We are going to validate the tool in the coming.

**Comment by mavilein** [comment]
This is done on the engines side.

**Comment by albertoperdomo** [comment]
Released in Preview in 2.10.0

**Comment by Jolg42** [comment]
Check the release notes here 😉 

https://github.com/prisma/prisma/releases/tag/2.10.0
