### ISSUE TITLE
UpdateOne object type is dependent on order of declaration in data model

### ISSUE THREAD

**Issue by ejoebstl** [prisma/prisma#3051]
**Describe the bug**
The order of declaration in the data model changes how the `UpdateOne` input type looks.

If, for a type `A`, the first occurring field referencing `A` is required, the input type `AUpdateOne` will have no disconnect field. If the first occurring field that references `A` is nullable, the `AUpdateOne` input type will have a disconnect field. This is inconsistent behavior.

**To Reproduce**

Create a datamodel: 

```
type A {
    field: Int
}

type B {
    field: Int
    a: A!
}

type C {
    field: Int
    a: A
}
```

The generated type `AUpdateOne` will have no disconnect field.

Create a datamodel: 

```
type A {
    field: Int
}

type B {
    field: Int
    a: A
}

type C {
    field: Int
    a: A!
}
```

The generated type `AUpdateOne` will have a disconnect field.

**Expected behavior**
Consistent behavior, either generate such a field in both cases or don't.

Alternatively, it might be worth creating two distinct input types for these two cases. 

**Additional context**
I guess that occures because of [this check](https://github.com/prisma/prisma/blob/master/server/servers/api/src/main/scala/com/prisma/api/schema/InputTypesBuilder.scala#L270) and the caching of types which were already created.

**Comment by mavilein** [comment]
This is already fixed.
