### ISSUE TITLE
[Re-Introspection] Comments in the schema are removed by re-introspection

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3052]
## Problem

User-defined comments in a schema are removed with re-introspection. 

```
model user {
  id Int @id
  name String
  type user_type
}

/// Default for a user is NORMAL
enum user_type {
  ADMIN
  NORMAL
}
```

On re-introspection, the comment above the enum is removed

## Suggested solution

The comments should persist after re-introspection

**Comment by louisrli** [comment]
Is this fixed?
```
$ /Users/louis/branches/srs/server/node_modules/.bin/prisma --version
@prisma/cli          : 2.6.2
```

I'm still having comments deleted from my schema.

**Comment by janpio** [comment]
This should be fixed indeed. Note that not _all_ comments are kept right now, only the ones before a model or a field as we do not "parse" the other ones at all.

**Comment by louisrli** [comment]
```
 model BundleTopic {
   id                String             @default(cuid()) @id
-  subject           String?
   title             String
-
-  // (this is a comment that has been elided)
+  subject           String?
   MajorStudySubject MajorStudySubject? @relation(fields: [subject], references: [id])
   BundleSection     BundleSection[]
-  ScheduleDay       ScheduleDay[]      @relation(references: [id])
+  ScheduleDay       ScheduleDay[]
 }
```

Example of a git diff post reintrospection

**Comment by louisrli** [comment]
Hm, I think that before the diff this comment is technically before a field (MajorStudySubject). Unless perhaps I'm misinterpreting what you wrote

**Comment by louisrli** [comment]
Ah, it's keeping `///`s but not `//`

**Comment by janpio** [comment]
Right, updated my comment above. We should have documented that here when closing the issue.
