### ISSUE TITLE
Go Client - nil type safety

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3066]
**Is your feature request related to a problem? Please describe.**
Current `Go` client uses pointers all the way.

**Describe the solution you'd like**
The generated Go client should match GraphQL API and null types.

**Comment by gregwebs** [comment]
The situation is much better now. Should this be closed in favor of other issues like #3288

**Comment by divyenduz** [comment]
@gregwebs : Thanks! you are right. Closed via https://github.com/prisma/prisma/pull/3278

This is in stable `1.19.0`. That can be installed via `npm install -g prisma` or `brew install prisma`
