### ISSUE TITLE
Support for multi-dimensional arrays

### ISSUE THREAD

**Issue by onalv** [prisma/prisma#3066]
## Problem
I'm currently working with a table in which the elements from a column are arrays of arrays. When trying to get data in my react app with the prisma/client package I get the error **Some("array contains too many dimensions"**

## Suggested solution
Add support for at least 2-D arrays.

**Comment by janpio** [comment]
@onalv Can you share you model and the data you are trying to insert, and the error message you are getting? This will give us the necessary context to look into implementing this.

**Comment by onalv** [comment]
@janpio yes fo course. The error I get is the following:

`  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(2), cause: Some("array contains too many dimensions") }) })
`

This happens when I tried to get data from a column that contains array of arrays in the following form:
{{120.234, 45.23412}, {140.1245, 23.4534}, {-45.423, 45.4534}, {-120.0012, -120.1241}}

the npx prisma instrospect script detected that column as a Float[]. I get that error only if I request that column, i.e. if targetColumn is false I don't get the error:
`
const data = await prisma.table.findMany({
      select: {
        id: true,
        name: true,
        targetColumn: true,
      }
    });
`

**Comment by pantharshit00** [comment]
I can confirm the behaviour. I am marking it as a feature for now.

**Comment by kurtishouser** [comment]
A bit different...

I also received a similar `too many dimensions` error as noted in [Discussion #2952](https://github.com/prisma/prisma/discussions/2952). There are no 2-D arrays in the fields as in the discussion. However, I am generating one with the Postgres ARRAY[] syntax.
Error:
```
Invalid `prisma.queryRaw()` invocation:
  Raw query failed. Code: `N/A`. Message: `error deserializing column 1: array contains too many dimensions`
```
Query:
```
SELECT shape_id, ARRAY_AGG(ARRAY[shape_pt_lon, shape_pt_lat] ORDER BY shape_id, shape_pt_sequence) AS coordinates
FROM gtfs_shapes
GROUP BY shape_id
ORDER BY shape_id
```
Model:
```
model GtfsShape {
  id                  Int    @id @default(autoincrement()) // non-gtfs field
  shape_id            String
  shape_pt_lat        Float
  shape_pt_lon        Float
  shape_pt_sequence   Int
  shape_dist_traveled Float?

  @@map(name: "gtfs_shapes")
}
```

Sample data:
```
shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
01_shp,37.99537473400005,-121.78034555599999,1,
01_shp,37.99538564300008,-121.78041357799998,2,
01_shp,37.99539701900005,-121.78048147399994,3,
01_shp,37.995409033000044,-121.78054919899995,4,
01_shp,37.99542104600005,-121.78061692199998,5,
01_shp,37.99543306000004,-121.78068464599994,6,
01_shp,37.99544507400003,-121.78075237099995,7,
01_shp,37.99545708800008,-121.78082009499997,8,
01_shp,37.995469101000026,-121.78088781999998,9,
01_shp,37.99548129200008,-121.78095549299996,10,
```
The full dataset can be found at  https://transitfeeds.com/p/bart/58/latest/file/shapes.txt

**Comment by janpio** [comment]
@kurtishouser I think you can extract that into a bug report issue, as it is only topically related to this feature request. Thanks.

**Comment by janpio** [comment]
We have a newer feature request now that has already more 👍 at https://github.com/prisma/prisma/issues/11120 so I am closing this one. @kurtishouser and @onalv maybe take a look if that fully covers what we talked about here, and leave a comment or 👍 over there as well. Thanks.
