### ISSUE TITLE
Disconnect on a null foreign key should not error 

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#3069]
## Bug description

Currently if the client send `disconnect: true` in an `update` and the field is not connected, it will throw an error saying:
```
" The records for relation `ModelToAnotherModel` between the `AnotherModel` and `Model` models are not connected.",
```
It should just ignore the `disconnect` since it's a valid use case where you don't know if the models are connected.

## How to reproduce
Use:
```prisma
model Model {
  id           Int            @default(autoincrement()) @id
  AnotherModel AnotherModel[]
}

model AnotherModel {
  id      Int   @default(autoincrement()) @id
  model   Model? @relation(fields: [modelId], references: [id])
  modelId Int?
}
```

```typescript
await prisma.anotherModel.create({})
await prisma.anotherModel.update({ where: {id: 1}, data: { model: { disconnect: true } } })
```

## Expected behavior
It should not throw an error and just do nothing.

## Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Prisma version: 2.2.2
- Node.js version: 12.X

**Comment by Sytten** [comment]
The current alternative is to fetch the current record, check if it is connected and then proceed to disconnect it. It is not ideal, but at least there is a workaround for now.

**Comment by jahjedtieson** [comment]
Emile -- 

Thank you for reporting this issue.  I was just about to do the same thing! The workaround, 'check if connected and then disconnect', is both inefficient and is not guaranteed to succeed as it will not be atomic -- another request could update the value that you've just checked before your second call is made.  

Under the hood, the SQL for "disconnect: true" is just to write a NULL to that column.  When we say "disconnect", we always want that NULL to be written, even if the value is already NULL.  

Prisma team, please make it easy for us to write clean application logic; don't make us fetch the data first (which really doesn't solve the problem, as noted above) ... and don't require us to come up with other workarounds, which are also ugly and don't solve the problem (such as maintaining a local cache of the state of this column)!

**Comment by narciero** [comment]
It would be great to have (a) `disconnect` _not_ throw if no relation exists as mentioned or (b) allow passing `null` to optional relations in `connect` (similar to how you can pass `null` to foreign keys in the unchecked variants of create/update)

**Comment by dpetrick** [comment]
Disconnect will no longer error for records that are not connected, starting with version 2.21.
