### ISSUE TITLE
Prisma Client 1.17 - error when setting up

### ISSUE THREAD

**Issue by bogdansoare** [prisma/prisma#3078]
**Describe the bug**
I'm following the steps from the docs https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-a002/#configure-your-prisma-api to get the new prisma client up, and I get an error when I try to `prisma init`

**Screenshots**
<img width="1022" alt="screen shot 2018-09-11 at 20 38 09" src="https://user-images.githubusercontent.com/2750170/45377807-54955f80-b604-11e8-9eca-6797f8311d5d.png">

**Versions**
 - OS: OS X High Sierra
 - `prisma` CLI: prisma/1.17.0-beta.2 (darwin-x64) node-v8.11.3

**Comment by divyenduz** [comment]
Thanks for raising this issue. There was a bug in the initial file generation. That was resolved here: https://github.com/prisma/prisma/pull/3086

The fix should be available on the latest beta - `npm install -g prisma@beta`

Please let me know if that works for you? Thanks.

**Comment by bogdansoare** [comment]
it worked, thank you 🙌
