### ISSUE TITLE
Surface schema validation errors during Re-Introspection and change flow

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#3082]
(Currently Re-Introspection is in an experimental state and has its own flag to be activated.)

The command `prisma introspection --experimental-reintrospection` just returns a warning when it receives an invalid Prisma schema (that it needs to work its **Re**-Introspection magic). It then proceeds to run a normal `prisma introspection` and still delivers a valid schema.

This can be annoying for users with big schemas, that make it hard to pinpoint the reason why the schema is invalid. See https://github.com/prisma/prisma/issues/3044#issue-658501552

We should change this behavior to instead error out and return the validation errors for the invalid schema. Additionally, we should introduce a flag that allows the user to ignore the invalid schema (`--clean`, `--fresh`, `--force`, `--overwrite` or similar). 

This is what this would look like:
| CLI Command                                                        | Valid Previous Schema                                          | Invalid Previous Schema               |
|----------------------------------------------------------------|----------------------------------------------------------------|---------------------------------------|
| `prisma introspection --experimental-reintrospection`          | success, enriched schema based on db state and previous schema | error, list schema validation errors  |
| `prisma introspection --experimental-reintrospection --clean` | success, raw schema based on db state                          | success, raw schema based on db state |
| `prisma introspection`                                         | success, raw schema based on db state                          | success, raw schema based on db state |

---

After Re-Introspection leaves the experimental state the commands can be collapsed into: 
| CLI Command                         | Valid Previous Schema                                          | Invalid Previous Schema               |
|---------------------------------|----------------------------------------------------------------|---------------------------------------|
| `prisma introspection`          | success, enriched schema based on db state and previous schema | error, list schema validation errors  |
| `prisma introspection --clean ` | success, raw schema based on db state                          | success, raw schema based on db state |

**Comment by mavilein** [comment]
Internal Note: @do4gr has implemented the engines part. Awaiting integration on CLI side.

**Comment by Jolg42** [comment]
CLI implementation is done in 2.4.0-dev.30, if everything works as expected this could be closed.

**Comment by janpio** [comment]
What error message does a user get when the Re-Introspection fails that tells them to use `--clean`?
