### ISSUE TITLE
UpdateInput have not create/update/upsert properties when relative object have not custom fields

### ISSUE THREAD

**Issue by Fi1osof** [prisma/prisma#3084]
**Describe the bug**

Schema:
```
type User{
  id: ID! @unique
  username: String @unique
  email: String @unique 
  logedin: [LogedIn!]! @relation (name: "UserLogedIn")
}

type LogedIn {
  id: ID! @unique
  User: User! @relation (name: "UserLogedIn")
}
```

**To Reproduce**
1. Create relative type with id and relation only
2. Build schema
We got:
```
input LogedInUpdateManyWithoutUserInput {
  connect: [LogedInWhereUniqueInput!]
  disconnect: [LogedInWhereUniqueInput!]
  delete: [LogedInWhereUniqueInput!]
}
```
3. Update schema:
```
type LogedIn {
  id: ID! @unique
  createdAt: DateTime!
  fake: Boolean @default(value: true)
  User: User! @relation (name: "UserLogedIn")
}
```
4. Rebuild schema. And all OK
```
input LogedInUpdateManyWithoutUserInput {
  create: [LogedInCreateWithoutUserInput!]
  connect: [LogedInWhereUniqueInput!]
  disconnect: [LogedInWhereUniqueInput!]
  delete: [LogedInWhereUniqueInput!]
  update: [LogedInUpdateWithWhereUniqueWithoutUserInput!]
  upsert: [LogedInUpsertWithWhereUniqueWithoutUserInput!]
}
```

I undestand, when type have not custom fields nothing can be updated. But create? Can add at least create? 

**Versions (please complete the following information):**
 - OS: Ubuntu 18
 - `prisma` CLI:  prisma/1.14.2 (linux-x64) node-v9.11.1 
 -  `prisma-binding` 2.1.4

**Comment by mavilein** [comment]
Hey @Fi1osof ,

thanks for reaching out to us and providing such a thorough description! 🙏  I understand your concern, but your suggestion would unfortunately violate the GraphQL specification. In your example the input type `LogedInCreateWithoutUserInput` would contain no input fields. This is explicitly disallowed by the GraphQL spec. The reference implementation `graphql.js` will blow up when parsing such a schema.

Therefore i suggest that you use the approach you already discovered: adding a fake field to the User type.

I am closing this issue therefore now. Happy to reopen this again if i did understand or answer your question correctly.

**Comment by Fi1osof** [comment]
@mavilein , OK, thanks!
