### ISSUE TITLE
Regression in loading .env file from 2.2.0 to 2.2.2 for prisma/cli

### ISSUE THREAD

**Issue by alexnederlof** [prisma/prisma#3086]
## Bug description

When upgrading from @prisma/cli from 2.2.0 to 2.2.2 it does not load the `.env` file from the working directory, like the prisma client does. We already had prisma-client at 2.2.2 because dependabot merged that PR first.

Fun fact: if you put the `DATABASE_URL` from the `.env` file back in the `prisma/.env` file, the client doesn't work any more (because it doesn't have the `DATABASE_URL`) but `npx prisma migrate up` works again 🤷 .

## How to reproduce

Breaking CLI:
1. Upgrade CLI and Client to 2.2.2
1. Place a `.env` file with the `DATABASE_URL` in the working directory, and none in `prisma/`.
1. run regular prisma code -> it works
1. run `npx migrate up --experimental` -> it breaks

Breaking the normal client:
1. Upgrace CLI and Client to 2.2.2
1. Create a `prisma/.env` file with the `DATABASE_URL` and no `.env` file in the working directory.
1. run regular prisma code -> it breaks (using the default empty constructor `new PrismaClient()`)
1. run `npx migrate up --experimental` -> it works again

## Environment & setup

- OS: Mac OS
- Database: Postgres
- Prisma version: `2.2.2`
- Node.js version: 14.4

Related to #2971

**Comment by janpio** [comment]
This should actually be a bugfix from 2.2.1 that fixed wrong behavior introduces in 2.2.0: https://github.com/prisma/prisma/releases/tag/2.2.1

Can you please list out exactly what works when you have what file where? I am not super sure I get it correct right now and am not sure what you are observing that is unexpected. But we sure want to find out.

**Comment by alexnederlof** [comment]
Updated the issue!

**Comment by janpio** [comment]
Are you sure you are not additionally loading the `.env` file with e.g. `dotenv` in your codebase?

**Comment by alexnederlof** [comment]
Yes, we use `dotenv` to load a `.env` file in the workdir. So I guess Prisma notices that and uses it, but prisme CLI does not? In that case, what's the recommended solution. Because I would expect that if I would remove `DATABASE_URL` from the `.env` file, and create a `prisma/.env` file it would work.

**Comment by janpio** [comment]
If you use `dotenv` to load the workdir `.env` file that environment variable is available to the Client - that is what `dotenv` does. The CLI does not have and execute your code using `dotenv`, so does not have the environment variables loaded.

If you only have a `.env` file next to your schema (default: `prisma/.env`) then both the CLI and the Client should pick that up and have the value available indeed (in 2.2.2). Is that not working?

(https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema#using-environment-variables was recently updated to document that better)

**Comment by alexnederlof** [comment]
> If you only have a .env file next to your schema (default: prisma/.env) then both the CLI and the Client should pick that up and have the value available indeed (in 2.2.2). Is that not working?

Well, it works if I put `DATABASE_URL` both in `.env` *and* in `prisma/.env`. But if I only put it in the latter, it doesn't. Maybe this is by design, but I expected prisma to load `prisma/.env` if `DATABASE_URL` is not found in whatever currently is already loaded using dotenv

**Comment by alexnederlof** [comment]
btw I can just fix this by doing

```javascript
config();
config({ path: 'prisma/.env' });
```

**Comment by janpio** [comment]
Can you restate in simple word what exact situation is not working so we can try to reproduce? Thanks.

**Comment by alexnederlof** [comment]
ok, so I load `.env` with `dotenv` at the start of my application, for my general configuration.

I tested three setups: 

Setup 1: 
`DATABASE_URL` in `.env` and have no `prisma/.env`. Now prisma CLI doesn't work (as per documentation).

Setup 2: 
`DATABASE_URL` **not in** `.env`, `DATABASE_URL` in `prisma/.env`. Now prisma CLI works, but the prisma client doesn't.

Setup 3: 
`DATABASE_URL` `.env` **and in**  `prisma/.env`. Now both work, however, we have configuration duplication. 

What I expected: either situation 1 or 2 to work, so I don't have to do 3.

Current workaround: manually force loading both when my application starts:

```javascript
config(); // Now it doesn't have DATABASE_URL
config({ path: 'prisma/.env' }); // And now it does
```

If this is by design, I think the docs need to mention that if you have a `.env` in the root/working dir, the `env` in the prisma folder won't load.

**Comment by janpio** [comment]
In Setup 2, Prisma Client should totally work if you have `env("DATABASE_URL")` in your schema.

If not, can you create a super simple project reproducing the problem and just put it on GitHub so we can verify?

**Comment by alexnederlof** [comment]
Sorry guys haven't found the time to isolate the issue in a GitHub repo. I'll try to do it in the coming weeks, but feel free to close the issue and have me re-open it if I can confirm, if that helps you manage this repo better!

**Comment by Jolg42** [comment]
No problem! I'll close this then and we'll reopen if you can confirm 😃
