### ISSUE TITLE
[new generator] TypeError: prisma_lib_1.makePrismaBindingClass is not a function

### ISSUE THREAD

**Issue by jamesmbowler** [prisma/prisma#3088]
I'm using the instructions here:
https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-a002/

Steps to recreate:

1. Follow instructions in above link up to step 9. When using prisma init, choose mysql, and no existing data.
2. Try to run node index.js and get error "Error: Cannot find module 'prisma-client', and fix by changing, in index.js, this line:
`const { prisma } = require('./prisma-client')`
to this:
`const { prisma } = require('./generated/prisma-client')`

3. Run "node index.js" again, and see error:

> TypeError: prisma_lib_1.makePrismaBindingClass is not a function

extra:
4. In prisma-client-lib I see
```
var makePrismaClientClass_1 = require("./makePrismaClientClass");
exports.makePrismaClientClass = makePrismaClientClass_1.makePrismaClientClass;
```
.. so I change this line

`exports.Prisma = prisma_lib_1.makePrismaBindingClass({`

in generated/prisma/index.js to

`exports.Prisma = prisma_lib_1.makePrismaClientClass({`

.. and I run node index.js and get a different error:

> var fieldName = _a[0], field = _a[1];
>                                       ^
> TypeError: Cannot read property '0' of null

**Expected behavior**
That user Alice would be created.

**Versions (please complete the following information):**
 - OS: `Ubuntu 14.04`
 - prisma/1.17.0-beta.2 (linux-x64) node-v8.10.0
- "dependencies": {
    "graphql": "^14.0.2",
    "prisma-client-lib": "^0.2.48"
  }

**Comment by mikepuglisi** [comment]
+1

**Comment by timsuchanek** [comment]
Thanks for reporting @jamesmbowler  and @mikepuglisi ! We just fixed this and published a new version `prisma@1.17.0-beta.5`.

**Comment by jamesmbowler** [comment]
I just tried the latest version, and success! Thanks

**Comment by ProphetDaniel** [comment]
At least for me, this problem appeared back on prisma@1.18.0.
