### ISSUE TITLE
Error on prisma@1.17 init

### ISSUE THREAD

**Issue by Fi1osof** [prisma/prisma#3091]
**Describe the bug**
prisma init --endpoint http://localhost:4466
File not exists /usr/local/share/.config/yarn/global/node_modules/prisma-cli-core/dist/commands/init/boilerplate/datamodel.prisma

Prisma search datamodel.prisma but exists https://github.com/prisma/prisma/blob/1.17.0-beta/cli/packages/prisma-cli-core/src/commands/init/boilerplate/datamodel.graphql 

File renaming solves this problem.

 
**Versions (please complete the following information):**  

prisma/1.17.0-beta.2 (linux-x64) node-v9.11.1

**Comment by timsuchanek** [comment]
Thanks for repoting @Fi1osof ! It's fixed in the latest beta.
