### ISSUE TITLE
updateManyXXXX not working as expected for complex type in schema

### ISSUE THREAD

**Issue by thanatchakromsang** [prisma/prisma#3100]
**Describe the bug**
Can't `updateManyXXXX` fields null to post types It only work with basic type

**To Reproduce**
1. Deploy this schema
```graphql
type User {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  username: String! @unique
  password: String!
}
```
2. Create User from mutation
3. Add more fields to schema
```graphql
type User {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  username: String! @unique
  password: String!
  post: Post
}

type Post {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  content: String
}

```
4. Now post fields in old user will be null but we want to migrate old data to have post type
```graphql
mutation {
  migration_01: updateManyUsers(
    where: { post: null }
    data: {
      post: {
        create: {
          content: "hello world"
        }
      }
    }
  ) {
    count
  }
}

```

**Expected behavior**
Return post not null and have content = "hello world" for that user instead post will still be null and no content

**Versions (please complete the following information):**
 - OS: Linux archlinux 4.18.5-arch1-1-ARCH
 - `prisma` CLI: `prisma/1.16  node-v8.11.4`
 - Prisma Server: `1.16`

**Comment by vistriter** [comment]
@thanatchakromsang I have same your problem. I want to know a solution for migration this case.

**Comment by marktani** [comment]
I don't understand the expected behaviour you're proposing, can you clarify?

**Comment by marktani** [comment]
I see! This is because nested mutations inside `updateMany` are currently not applied: #2010. Please follow the other issue 🙂

**Comment by thanatchakromsang** [comment]
@marktani Thanks for the head up I got it working by migration script using typescript
```typescript
import { Prisma } from '../generated/prisma'

const prisma = new Prisma({
  endpoint: process.env.PRISMA_ENDPOINT,
  secret: process.env.PRISMA_SECRET,
  debug: false,
})

export const main() = async () => {
  const allUser = await prisma.query.users({
    where: { notificationSetting: null },
  })
  let count = 0
  const updatedUser = await Promise.all(
    allUser.map(async user => {
      count += 1
      console.log(`update user id: ${user.id}`)
      return prisma.mutation.updateUser({
        where: { id: user.id },
        data: {
          post: {
            create: {
              content: "hello world",
            },
          },
        },
      })
    }),
  )
  console.log(`===== updated ${count} users =====`)
}
```
