### ISSUE TITLE
`prisma generate` commit or not commit generated files?

### ISSUE THREAD

**Issue by brikou** [prisma/prisma#3102]
**Describe the bug**

Imagine 2 people are working on the same project, personA works on branA and personB on branchB.
PersonA make a minor change datamodel.graphql, run `prisma generate`
PersonB make also a minor change datamodel.graphql, run `prisma generate`

BranchA is merged, then branchB cannot be merge without running `prisma generate` again. On each `prisma generate`, generated code is shuffled and so conflict happens almost at 100%.

So there is 2 options to prevent collisions:

- don't commit generated files
- prevent as much as possible collision

IMO generated files should be commited, as part of code source (event if generated)

**How to prevent collisions**

In order to prevent collision, we need to sort generated types, scalars, enums by their name. As a bonus point having thing sorted would allow to check generated files, when running `git add --patch`, and so would make any regression detected sooner.
Another thing, if we can expect the result, someone can patch generated files for custom need (like adding tslint, eslint annotation, fe).

WDYT?

**Comment by divyenduz** [comment]
The output of the generation should be same for same input. If that is not the case, it is a bug.

**Comment by marktani** [comment]
Sounds like a great feature request to me, would love to see a PR for this.

**Comment by brikou** [comment]
@marktani I'd be glad to add this feature, but my question is where the sort should be done?
Should I sort response from introspection query, it would allow to have this feature also for other library using this (like graphql-binding), or directly in the printer? maybe @timsuchanek can give me a pointer?

**Comment by brikou** [comment]
Solved by #3137
