### ISSUE TITLE
Documentation covering prisma client schema delegation is incorrect

### ISSUE THREAD

**Issue by Colburn** [prisma/prisma#3103]
The link below is the documentation page for schema delegations in prisma client. I noticed that the resolver syntax was incorrect. Additionally, according to Abhi Aiyer in the slack channel, schema delegations have been removed from prisma client altogether, and so the page should be removed. 

https://www.prisma.io/docs/prisma-client/api-reference/schema-delegation-JAVASCRIPT-pyl7/

**Bad resolver example**
```
const resolvers = {
  Query: {
    users = (root, args, context, info: GraphQLResolveInfo) => {
      return prisma.$delegate.mutation.createUser(
        info,
      })
    }
  }
}
```

**Comment by marktani** [comment]
Thanks for bringing this up, the page has been removed.

**Comment by leohxj** [comment]
so, what's the right way to use delegration with  prisma-client?
