### ISSUE TITLE
Preview feature feedback: `connectOrCreate`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3103]
Please share your feedback about the preview feature `connectOrCreate` that was released in [v2.1.0](https://github.com/prisma/prisma/releases/tag/2.1.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo. 
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma2`](https://app.slack.com/client/T0MQBS8JG/CKQTGR6T0) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by jazerix** [comment]
`connectOrCreate` seems to be working great overall - we ran into an issue when it's trying to `connectOrCreate` on an intermediate table, see https://github.com/prisma/prisma/issues/3612. One of my friends has also been able to replicate this bug on his own machine.

**Comment by homerjam** [comment]
Should it be possible to `connectOrCreate` two fields at the same time?

I seem to get a error when doing the following...

```js
const connectOrCreateUpload = {
  connectOrCreate: {
    where: { id: "myid" },
    create: {
      id: "myid",
      name: "blah blah blah",
    },
  },
};

prisma.asset.create({
  data: {
    uploads: {
      ...connectOrCreateUpload,
    },
    uploadMain: {
      ...connectOrCreateUpload,
    },
  },
});

```

```
Query interpretation error. Error for binding '9': AssertionError("[Query Graph] Expected a valid parent ID to be present for a nested connect on a one-to-many relation.") 
```

**Comment by dpetrick** [comment]
@homerjam Yes that should be possible. I will look into it.

**Comment by brianbancroft** [comment]
I tried connectOrCreate for a single attribute over the weekend. It worked, I like it, and I wished a similar feature existed at the top level CRUD. :taco:

**Comment by pantharshit00** [comment]
`connectOrCreate` is stable now.
