### ISSUE TITLE
Issue Prisma Docs 1.17 - Getting Started Part 2 Step 5

### ISSUE THREAD

**Issue by conradwt** [prisma/prisma#3107]
**Describe the bug**

I’m seeing the following issue Prisma Docs 1.17 - Getting Started Part 2 Step 5, ```/Users/conradwt/graphql.dir/examples/hello-world/index.js:10
      posts: {
      ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
```

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Part 2 Step 5'
2. node index.js

**Expected behavior**

I would expect not to have gotten an error message.

**Versions (please complete the following information):**
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 

```text
macOS Mojave Beta 11
```

 - `prisma` CLI: [e.g. `prisma/1.9.0 (darwin-x64) node-v10.4.0`]

```bash
 $ prisma --version
prisma/1.17.0-beta.11 (darwin-x64) node-v10.10.0
```

 - Prisma Server: [e.g. `1.9.0`]

 $ prisma --version
prisma/1.17.0-beta.11 (darwin-x64) node-v10.10.0

 - `graphql-cli`, `prisma-binding`, `graphql-yoga`, etc. if applicable

```text
not applicable
```

**Comment by marcaaron** [comment]
Can reproduce. There is a syntax error in the example that's causing this issue. There should be a comma after `name: "Bob"`.

```
const { prisma } = require('./prisma-client')

// A `main` function so that we can use async/await
async function main() {

  // Create a new user with a new post
  const newUser = await prisma
    .createUser({
      name: "Bob", <-----
      posts: {
        create: {
          title: "The data layer for modern apps",
        }
      },
    })
  console.log(`Created new user: ${newUser.name} (ID: ${newUser.id})`)

  // Read all users from the database and print them to the console
  const allUsers = await prisma.users()
  console.log(allUsers)

  const allPosts = await prisma.posts()
  console.log(allPosts)
}

main().catch(e => console.error(e))
```
