### ISSUE TITLE
Preview feature feedback: `middlewares`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3107]
Please share your feedback about the preview feature `middlewares`  that was released in [v2.3.0](https://github.com/prisma/prisma/releases/tag/2.3.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo. 
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma2`](https://app.slack.com/client/T0MQBS8JG/CKQTGR6T0) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by madebysid** [comment]
Love the API, this will be so useful to build tooling! ❤️

Although most `params` in the middleware are self-explanatory, I was wondering what the `dataPath` & `headers` params stand for? (Perhaps we should add some documentation for these params?)

**Comment by madebysid** [comment]
From Slack discussion:
> `dataPath` is for example when you do `.user.findone().posts`  - then dataPath is ['posts']
`headers` shouldn’t even be there but are there so you can change the headers for a request to the query engine - only relevant for debugging

**Comment by Sytten** [comment]
Awesome feature. It would be very nice to have some tooling to compare the model against a type instead of a string to avoid mistakes when refactoring/renaming.

**Comment by julienp** [comment]
Great feature! I was hoping to use this to add tracing spans for prisma queries with a middleware similar to this:
```
const _tracer = ...

export async function prismaTracerMiddleware(params, next) {
  const span _tracer.startSpan("prisma-query")
  const result = await next(params)
  span.finish()
  return result
}
```

Tracing libraries such as elastic-apm-node use [async_hooks](https://nodejs.org/api/async_hooks.html) to establish parent-child relations between spans, however it looks like the middleware function don't seem to run inside an asynchronous resource.

Using this middleware
```
export async function asyncContextMiddleware(params, next) {
  console.log({
    executionAsyncId: executionAsyncId(),
    triggerAsyncId: triggerAsyncId(),
  })
  return next(params)
}
```
I can see that `executionAsyncId` and `triggerAsyncId` are always 0. I am not sure what needs to happen to properly propagate the execution context here. The node documentation has some remarks for [running in workers](https://nodejs.org/api/async_hooks.html#async_hooks_using_asyncresource_for_a_worker_thread_pool), but I do not know the details on how queries are executed in prisma.

**Comment by janpio** [comment]
Someone else has a similar idea and seems to have come quite far: https://twitter.com/AbhiAiyer/status/1287126683359698944 + https://github.com/abhiaiyer91/prisma-opentracing-middleware

**Comment by abhiaiyer91** [comment]
@janpio, @julienp and I work together at Gatsby. We are hitting this issue using elastic-apm-node.

**Comment by janpio** [comment]
Ah, got it @abhiaiyer91. Created https://github.com/prisma/prisma/issues/3148 so we can discuss this (cc @julienp )

**Comment by pandaniell** [comment]
The middleware is a nice feature, it would be nice if we could get the result for find queries and manipulate how data gets returned so that we can use the middleware for caching `const someProp = redisClient.get(`${params.args.where.id}:someProp`);`, if the key was found we could then prevent a database hit and return using data from the cache, otherwise we can run the query and save the result in the cache

**Comment by madebysid** [comment]
@pandaniell You should be able to do that already if I understood you correctly. Here's an example:

```
prisma.use(async (params, next) => {
  if (params.model === 'User') {
      return ' No users for you' // Or return something from your cache
  }
  const actualResponse = await next(params),
  // Cache this response
  return actualResponse
})
```

Essentially, requests go out only if you `await` the `next` function. Give that a shot?

**Comment by pandaniell** [comment]
@madebysid Thank you, I didn't think of trying to return something else other than next, working example using Redis
```typescript
prismaClient.use(async (params, next) => {
  if (
    params.model === "GuildSettings" &&
    params.action === "findOne" &&
    params.args.select.prefix
  ) {
    const prefix = await getAsync(`${params.args.where.id}:prefix`);

    if (prefix) {
      return { prefix };
    }
  }

  const queryResult = await next(params);

  redisClient.set(
    `${params.args.where.id}:prefix`,
    queryResult.prefix,
    "EX",
    10
  );

  return queryResult;
});
```

**Comment by madebysid** [comment]
Nice! You should wrap it up in a usable package and add it here if you'd like: https://github.com/catalinmiron/awesome-prisma :D

**Comment by pandaniell** [comment]
Would be a nice alternative to https://github.com/prisma/prisma/issues/3165 - unfortunately I lack the knowledge to make that work but maybe somebody else is interested

**Comment by janpio** [comment]
Open a new issue @pandaniell for "query caching middleware" and we can discuss if this might already be possible, what is missing and so on.

**Comment by abhiaiyer91** [comment]
I implemented a query caching middleware with LRUCache here https://github.com/abhiaiyer91/prisma-lrucache-middleware

**Comment by MichaelHindley** [comment]
Given 
```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["middlewares"]
}
```

When trying to use `prisma.use` in 2.3 or`prisma.$use` in 2.4, the follow error is observed:

```
[ERROR] 12:46:28 Error: In order to use the middlewares api, please enable set previewFeatures = ["middlewares"]
```

**Comment by beeme1mr** [comment]
Is it possible to see the query Prisma generated in the middleware? I would like to use this for monitoring purposes.

**Comment by janpio** [comment]
What exactly do you mean @beeme1mr? The actual SQL queries are one level lower in the Prisma Engine that is executed by the Prisma Client. What you can see in the middleware is the Prisma Client query, which is sent over to the Prisma Engine for generation of SQL query(/ies).

To see the actual SQL queries, you can use logging: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging Via the event based logging, that can be used in a similar way as the middleware: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#event-based-logging

**Comment by beeme1mr** [comment]
@janpio thanks for the info on the logger. That will probably work for now.

It would be nice get the actual SQL query in the middleware though. Could I hook into the Prisma Engine to achieve this? Possibly manually construct a `Document` using middleware params.

**Comment by pantharshit00** [comment]
> Could I hook into the Prisma Engine to achieve this? 

I am not sure that would be possible as engine also combines queries in a batch if they are executed in the same time frame to improve performance. Also, I don't think the client receive a document of generated query, right now when logging is enabled, the engine splits the log on the stdout.

Do you have any specific usecase in mind which you can't do with the current query logging system?

**Comment by janpio** [comment]
> Could I hook into the Prisma Engine to achieve this?

This is exactly what using the logger is doing. You can do whatever you want with these events that are triggered.

**Comment by nikolasburk** [comment]
Thanks a lot for all of your feedback, we've just promoted this future into the latest stable 2.5.0 release 🙌
