### ISSUE TITLE
Introduce new field type Slug

### ISSUE THREAD

**Issue by kbrandwijk** [prisma/prisma#311]
Thanks to @mwickett for bringing up this functionality on Slack.

Based on the discussion on how to generate a unique slug on a Type, I want to suggest a new field type for this, with a server-side implementation to generate a slug based on a field, which is unique across the Type (default) or across all Types.

```
type Blog implements Node {
    id: ID!
    title: String!
    slug: Slug! @basedOn(field: 'title') @isUnique
} 
```
The existing `@isUnique` tag would indicate a globally unique slug, without it, it would be unique for that Type by default.

**Comment by sedubois** [comment]
The unicity across all types is discussed in #24.

Relates a bit to last paragraph of #180's OP.

**Comment by kbrandwijk** [comment]
An example implementation is here: https://github.com/graphcool-examples/functions/issues/24

**Comment by IshanKBG** [comment]
Is this feature added

**Comment by iacobfred** [comment]
Any word on this?
