### ISSUE TITLE
Heroku version of prisma-prod image

### ISSUE THREAD

**Issue by noelebrun** [prisma/prisma#3122]
**Describe the content you'd like to see**
An Heroku version of the prisma-prod image to have the envsubst done on the config.

**Describe alternatives you've considered**
I didn't find any.

**Additional context**
Hello,

How can we use the prisma-prod image with Kubernetes Secrets since there's no Heroku version like the classic prisma image to replace the environment variables in the config?

Thanks!

**Comment by jhalborg** [comment]
Did you solve this @noelebrun ?

**Comment by noelebrun** [comment]
@jhalborg Unfortunately, not. This needs some development on the Prisma projet. I know some additional documentation is planned about the prisma-prod image.
