### ISSUE TITLE
prisma.schema which folder?

### ISSUE THREAD

**Issue by TomasMoskala** [prisma/prisma#3124]
`npx prisma generate` gives message
```
✔ Generated Prisma Client to .\node_modules\@prisma\client in 76ms
```
but the file is in 
```
\prisma-examples-master\typescript\grpc\node_modules\\.prisma\client
```

What is the purpose of 2 folders @prisma and .prisma?

**Comment by janpio** [comment]
This is most probably fixed by now. If not, please open a new issue and provide a full reproduction. Thank you!
