### ISSUE TITLE
Introspection: Secret flag  to disable guardrails

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3128]
Right now we have a bunch of guardrails for Introspection in place that make sure, we do not introspect things into our schema that do not pass validation or would not work in Prisma Client or Query Engine.

We should have a "secret" flag on `introspect` that let's you disable those guardrails, so we can observe and test the behavior if those guardrails are disabled. That way we could from time to time run Introspection CI with this flag enabled, and see what still breaks and what the effect of removing one of those guardrails would be.

**Comment by tomhoule** [comment]
We do not want to do this. This is an old issue, so let's close this.
