### ISSUE TITLE
Improve DX of serverless situation

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma#3137]
Serverless use is increasing due to its simplicity and elegance. Platforms like [Vercel](https://vercel.com/docs/v2/serverless-functions/introduction) or [Netlify](https://www.netlify.com/products/functions/) make it extremely easy to deploy Lambda functions.

Developers usually use Lambda functions to connect with databases and third-party services when writing business logic.

The combination of the combo serverless and Prisma, make developers super productive and confident since they really can focus on the app, instead of dealing with servers and databases in "the old way".

Being said this, Prisma works in serverless mode. However, using Prisma with serverless can bring issues related to database connections at scale. Tools like [PgBouncer](https://www.pgbouncer.org/) or [AWS RDS Proxy](https://aws.amazon.com/rds/proxy/) help mitigate this specific issue. But then developers need to use another tool to solve the new issue.

Due to this situation, sometimes developers refuse to use Prisma in serverless mode. They avoid having to deal with connection poolers and new setups. Instead, they choose Firebase, [FaunaDB](https://fauna.com/), [Sanity](https://www.sanity.io/), or any other headless CMS. What do they have in common? HTTP requests. No need to worry about database connections.

This could create a bad developer experience for some developers at scale, making them drop Prisma in favor of a datastore service or headless CMS.

That's why I strongly suggest that Prisma takes into account services like FaunaDB and similars. Prisma also could become the `graphql-binding` or the [OneGraph](https://www.onegraph.com/) of datastore services, just because people use them as databases.

I see 2 main targets for Prisma:

- Databases (MySQL, PostgreSQL, MongoDB, etc)
- Services (FaunaDB, Azure Cosmos DB, Firebase, Sanity, etc)

As I said in a [tweet](https://twitter.com/jferrettiboke/status/1275868665066459136), **Prisma should become the one database client to rule them all.** Prisma should partnership with database and datastore service providers to create more and more connectors to give support (in the future) across languages (JS/TS, Go, etc).

- ✅ Universal database client
- ✅ Type-safe
- ✅ Auto-generated

**Comment by jferrettiboke** [comment]
@albertoperdomo Thoughts?

**Comment by matthewmueller** [comment]
Just an FYI, we wrote some new documentation on how to use Prisma in serverless environments: https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#serverless-environments-faas

It doesn't solve the connection management issue, but offers workarounds.

**Comment by janpio** [comment]
- Support for many of the connectors mentioned is tracked via their own issues: https://github.com/prisma/prisma/labels/topic%3A%20connector
- General improvements for the situation on serverless is an overarching theme where many feature, improvements and bug fixes contribute to

I am closing this issue, as it is more effective to track individual problems in individual issues 👍
