### ISSUE TITLE
Add ability to configure custom schema location instead of requiring `--schema` arg

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma#3144]
## Problem

For people who use a custom schema location, the current DX is super painful. All of the CLI commands fail unless you explicitly pass `--schema`. When you are using the cli a lot in a project with a custom schema, this gets super annoying having to type `--schema` all the time.

Additionally, using a custom schema means the prisma postinstall hook fails, requiring projects to add their own postinstall hook to manually generate the client.

And then also of course we use a custom schema location in Blitz and abstract most of the prisma CLI commands. But when a user needs to drop down a level and use the prisma cli directly, they often get stuck because they don't know they need to provide `--schema`

## Suggested solution

I want to be able to define prisma config in the `package.json` file. Something like this:

```json
{
  "scripts": {},
  "prisma": {
    "schema": "db/schema.prisma"
  },
  "dependencies": {}
}
```

## Alternatives

An alternative is to add a config file at the repo root, like `.prisma.config.js` or something.

**Comment by janpio** [comment]
I agree that having a way to change the expected standard schema path is useful, vs. having to supply the `--schema` for each command execution. Even though if your framework (like Blitz) uses that internally, it makes your experience a lot worse if you ever want to use `prisma` directly as you probably do not know about this requirement.

Not sure about the suggested solution though - maybe there are other alternatives.

**Comment by timsuchanek** [comment]
Thanks @flybayer for raising this! I totally agree that this makes things quite cumbersome to use.

Before diving into solutions, I would like to understand your situation a bit better.
What is the reasoning for having the schema in a custom location?
It looks like you have it in a folder called `db` instead of prisma.
An option would also be to add `db` to the "watch list" where we check for the file.

**Comment by timsuchanek** [comment]
The reason I don't want to immediately jump into discussing custom solutions: The solutions introduce new challenges.
Let's say we introduce a section in the `package.json` to configure the schema location.
What about the Prisma Go Client? Should it also have a custom location configured? Should go users have a package.json? The Go Client is not part of the official offering yet, but we will have multiple languages at some point. The design of this needs to take that into account.

To get something language agnostic, one could think of a dot file. Like `.prismarc`. That would however introduce more dotfiles to your project root, which can already be quite full sometimes. What would the purpose of the dot file be? As of now just to point to the schema.prisma.

So no matter which solution we will choose, there will be trade-offs.

**Comment by janpio** [comment]
Is reading the schema file a concern of only Prisma CLI and Client or also the Engines directly?
If it really happens only in the Typescript part (in Prisma Client JS), I think using the `package.json` would be a totally valid solution here - and the Go Client would just go with their own appropriate solution.

**Comment by flybayer** [comment]
I would be fine with adding `db` to the watch list, that would solve my particular issue. But I still think it's good to have some way to configure this.

We use `db` for Blitz because Blitz is database client agnostic and we want a standard database client location. So we have a `db` folder that will hold files for whatever db client you are using.

**Comment by matthewmueller** [comment]
**Another thought:** Since .prisma files contain both database configuration and your schema definition. Would supporting imports solve this for you? 

The idea would be that instead of a `prisma.config.js` maybe it's just `config.prisma` (or any file in the root of the project ending in .prisma in the root directory).

```prisma
datasource {
  ...
}

generator {

}

import "./db/*.prisma"
```

I tend to agree that adding some config to `package.json` is easy enough, but I think it would be nice if everyone had a standard location for their prisma schema files. You always know where to look and can assign meaning to a file or directory across projects.

**Comment by flybayer** [comment]
@matthewmueller that would probably work, but doesn't seem ideal. I like adding `db` to the watch list better than that.

**Comment by matthewmueller** [comment]
To keep this moving, I'd suggest we do go ahead and add support for `package.json`. It seems like there's quite a bit of people that want it and I don't see much harm in it.

We may be able to get away with just supporting `package.json`. Later on, when we have imports, that can be our Go-specific solution.

**Comment by janpio** [comment]
Same technical details for the implementation:

- Right now we 1) use `--schema` or 2) fall back to `./prisma/schema.prisma` (or `./schema.prisma`) to find the schema file to load.
- The idea is to in between 1) and 2) add a new step where we look at the location that is defined in the `package.json` file as defined in https://github.com/prisma/prisma/issues/3144#issuecomment-674820240
- Additionally the output the CLI gives you where it loaded the `.env` file from (which is next to the schema file) should also mention the `schema.prisma` file to make that explicit.

Details about documentation of this feature are still figured out, as the schema loading is currently not documented at all directly.

**Comment by timsuchanek** [comment]
This is implemented by @Weakky in the latest dev version.

**Comment by janpio** [comment]
Follow up issue about detail that got missed: https://github.com/prisma/prisma/issues/3647

**Comment by sarink** [comment]
Are there any docs on this?

**Comment by janpio** [comment]
Search for `schema location` on docs.prisma.io brings me to: https://www.prisma.io/docs/concepts/components/prisma-schema#prisma-schema-file-location

**Comment by alphaelf** [comment]
can we use wildcard expression in package.json for schema location? just like: 
```json
"prisma": ["./plugins/**/*.prisma"]
```

**Comment by janpio** [comment]
No, you can only specify exactly the location of the schema file you want it to read.

**Comment by Security2431** [comment]
> This is done? Where are the docs?

See the official documentation:
https://www.prisma.io/docs/orm/prisma-schema/overview/location

**Comment by marcospgp** [comment]
I like that `package.json` was used, I wish more libraries would standardize around it instead of polluting the project root with tons of independent config files

edit: spoke too soon

```
warn The configuration property `package.json#prisma` is deprecated and will be removed in Prisma 7. Please migrate to a Prisma config file (e.g., `prisma.config.ts`).
For more information, see: https://pris.ly/prisma-config
```
