### ISSUE TITLE
Grant target 

### ISSUE THREAD

**Issue by Errorname** [prisma/prisma#3144]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 
 - `prisma` CLI: [e.g. `prisma/1.9.0 (darwin-x64) node-v10.4.0`]
 - Prisma Server: [e.g. `1.9.0`]
 - `graphql-cli`, `prisma-binding`, `graphql-yoga`, etc. if applicable

**Additional context**

**Comment by marktani** [comment]
See #3145.

**Comment by Errorname** [comment]
Woops, sorry for that
