### ISSUE TITLE
Grant target "*" for management auth token does not work

### ISSUE THREAD

**Issue by Errorname** [prisma/prisma#3145]
**Describe the bug**
Using a grant with a target: "\*" in the management auth jwt throws an "*Authentication token is invalid: Contained invalid grant 'Vector(\*)'*" error

**To Reproduce**
1. Deploy Prisma with a managementApiSecret (ex: my-secret-42)
2. Go to the Playground
3. Add an `Authorization` header with a jwt with the following payload:
```
{
  "grants": [
    {
      "target": "*",
      "action": "*"
    }
  ],
  "iat": 1532956915,
  "exp": 1690744915
}
```
Source: https://www.prisma.io/docs/run-prisma-server/authentication-and-security-kke4/
4. Run the following query:
```
{
  listProjects: {
    name
    stage
  }
}
```
5. See the following error:
```
{
  "data": null,
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "listProjects"
      ],
      "code": 3015,
      "message": "Authentication token is invalid: Contained invalid grant 'Vector(*)'",
      "requestId": "local:management:cjm921wbu05dq0900q5h4v3io"
    }
  ]
}
```

**Expected behavior**
There should be no errors, and I should see the list of projects linked to my Prisma instance.

**Versions:**
 - Prisma Server: `1.16`

**Additional context**
Here what I think is the problem:

[AsymmetricManagementAuth.scala#L46](https://github.com/prisma/prisma/blob/master/server/servers/deploy/src/main/scala/com/prisma/deploy/server/auth/AsymmetricManagementAuth.scala#L46):
```
  private def verifyGrant(nameToCheck: String, stageToCheck: String, grant: TokenGrant): Boolean = {
    val (grantedName: String, grantedStage: String) = grant.target.split("/").toVector match {
      case Vector(service, stage) => (service, stage)
      case invalid                => throw InvalidToken(s"Contained invalid grant '$invalid'")
    }

    if (grantedName == "" || grantedStage == "") {
      throw InvalidToken(s"Both service and stage must be defined in grant '$grant'")
    }

    validate(nameToCheck, grantedName) && validate(stageToCheck, grantedStage)
  }

  private def validate(toValidate: String, granted: String): Boolean = granted match {
    case "*" => true
    case str => toValidate == str
  }
```

Looking at the `verifyGrant` method, we see that we need to have a target which contains a `/`. Then, in the `validate` method, we compare with "*" to allow or not the grant.

This means one of those things:
* Either we must use the format: `target: "*/*"` to allow every services/stages, and therefore we must change the [documentation](https://www.prisma.io/docs/run-prisma-server/authentication-and-security-kke4/) to reflect that,
* Or, we must fix this file in order to allow the `target: "*"` format

What should be the solution ?

**Comment by Errorname** [comment]
I just created the PR. Using `target: "*/*"` works for me 👍

**Comment by marktani** [comment]
Thanks so much for your contribution 🙏 💚
