### ISSUE TITLE
Problems with middleware for tracing

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3148]
_Originally posted by @julienp in https://github.com/prisma/prisma/issues/3107#issuecomment-663972312_

Great feature! I was hoping to use this to add tracing spans for prisma queries with a middleware similar to this:
```ts
const _tracer = ...

export async function prismaTracerMiddleware(params, next) {
  const span _tracer.startSpan("prisma-query")
  const result = await next(params)
  span.finish()
  return result
}
```

Tracing libraries such as elastic-apm-node use [async_hooks](https://nodejs.org/api/async_hooks.html) to establish parent-child relations between spans, however it looks like the middleware functions don't seem to run inside an asynchronous resource.

Using this middleware
```ts
export async function asyncContextMiddleware(params, next) {
  console.log({
    executionAsyncId: executionAsyncId(),
    triggerAsyncId: triggerAsyncId(),
  })
  return next(params)
}
```
I can see that `executionAsyncId` and `triggerAsyncId` are always 0. I am not sure what needs to happen to properly propagate the execution context here. The node documentation has some remarks for [running in workers](https://nodejs.org/api/async_hooks.html#async_hooks_using_asyncresource_for_a_worker_thread_pool), but I do not know the details on how queries are executed in prisma.

**Comment by abhiaiyer91** [comment]
We are using this middleware https://github.com/abhiaiyer91/prisma-opentracing-middleware in conjunction with a tracer from `elastic-apm-node-opentracing`

**Comment by janpio** [comment]
Is this using exactly the published code from https://github.com/abhiaiyer91/prisma-opentracing-middleware/blob/master/src/index.ts or how can we best reproduce this @julienp @abhiaiyer91? I played around with the Non-OpenTelementry implementation from Elastic before we implemented Middlewares, and at least manually that worked fine. The different context of the middleware might mess with that though indeed.

**Comment by abhiaiyer91** [comment]
@janpio A good way to reproduce this:

* Setup a local APM server https://www.elastic.co/downloads/apm
* Setup the open tracing middleware in `prisma-opentracing-middleware`
* Set sampling to 1.0

What we see is all spans become transactions. There is no parent associated to them

**Comment by abhiaiyer91** [comment]
Also this illustrates the problem as well

```
export async function asyncContextMiddleware(params, next) {
  console.log({
    executionAsyncId: executionAsyncId(),
    triggerAsyncId: triggerAsyncId(),
  })
  return next(params)
}
```

**Comment by timsuchanek** [comment]
Thanks @abhiaiyer91! We're using ordinary promises, but I'll have a look, why your example is broken.

**Comment by timsuchanek** [comment]
This should be fixed in `@prisma/client@2.4.0-dev.40`.

@abhiaiyer91 can you give it a try?
Unfortunately the APM setup doesn't work for me.
With this code:
```ts
import { PrismaClient } from '@prisma/client'
import { createTracerMiddleware } from 'prisma-opentracing-middleware'
import Tracer from 'elastic-apm-node-opentracing'
import Agent from 'elastic-apm-node'

async function main() {
  const client = new PrismaClient()

  const agent = Agent.start()
  const tracer = new Tracer({
    agent,
  })
  // client.use(createTracerMiddleware(tracer))
  client.use(async (params, next) => {
    const span = tracer.startSpan('prisma-client')
    const res = await next(params)
    span.finish()
    return res
  })

  const data = await client.user.findMany()
  console.log(data)
  client.disconnect()
}

main()
```
I get this error:
```
TypeError: Cannot read property 'ended' of undefined
    at Tracer._startSpan (/Users/tim/code/repros/apm/node_modules/elastic-apm-node-opentracing/lib/tracer.js:43:90)
    at Tracer.startSpan (/Users/tim/code/repros/apm/node_modules/opentracing/src/tracer.ts:92:21)
    at middleware (/Users/tim/code/repros/apm/main.ts:15:25)
```
The same error comes for older Prisma Client versions, so I can't validate it right now.

But the 
```ts
    console.log({
      executionAsyncId: executionAsyncId
    })
```
test works 🙂

**Comment by abhiaiyer91** [comment]
@timsuchanek for your tracer

```
  const agent = Agent.start()
  const tracer = new Tracer(agent)
```

**Comment by timsuchanek** [comment]
Thanks, that works!
Is it now behaving as you would expect it to?

**Comment by timsuchanek** [comment]
This is what I get
![image](https://user-images.githubusercontent.com/1094804/89042425-35626100-d347-11ea-9354-c6a33d9584d1.png)

**Comment by janpio** [comment]
To confirm the problem @abhiaiyer91 described:

> What we see is all spans become transactions. There is no parent associated to them

you would probably manually start a trace for some other code (so put a span around it). Then that span and the span created via the middleware should appear in the same transaction (instead of creating 2 independent transactions).

**Comment by timsuchanek** [comment]
Thanks for the explanation @janpio now I get it.
I did exactly that - create a span around the client with a timeout to validate that the spans are nested. And they are:
![image](https://user-images.githubusercontent.com/1094804/89102163-c4827e00-d406-11ea-8fb1-415060574d0e.png)

Therefore I close this issue 🙂
