### ISSUE TITLE
Better error message for query-ing a table that does not exist

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3149]
https://github.com/prisma/prisma/issues/1385#issuecomment-664528562

`"message": "\nInvalid `prisma.patient.findMany()` invocation in\n/usr/src/app/node_modules/nexus-prisma/src/builder.ts:315:20\n\nError occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: \"ERROR\", parsed_severity: Some(Error), code: SqlState(\"42P01\"), message: \"relation \\\"public.Patient\\\" does not exist\", detail: None, hint: None, position: Some(Original(92)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some(\"parse_relation.c\"), line: Some(1159), routine: Some(\"parserOpenTable\") }) }) })",`

**Comment by pantharshit00** [comment]
This was done

![image](https://user-images.githubusercontent.com/22195362/115724538-a860ab80-a39e-11eb-8d6f-58e23da78592.png)
