### ISSUE TITLE
Use `.executeRaw()` with `.transaction([])`

### ISSUE THREAD

**Issue by pbelbin** [prisma/prisma#3150]
## Bug description

The response type for `.executeRaw()` variants are currently considered incompatible with those expected for use by `.transaction([])`, resulting in this error message:

All elements of the array need to be Prisma Client promises.

This means it's impossible to incorporate raw statement execution as part of a batched set of transactions that have to either all succeed or get rolled back.

## How to reproduce

Using any database model you like, create an array of Prisma requests that are to be batch executed, which includes at least one being `prisma.executeRaw('{valid SQL statement')`, and observe the error is thrown during the `await prisma.transaction([])` usage.

## Expected behavior

The execution of the batched requests should complete without failure.

## Environment & setup

- OS: macOS 10.15.6
- Database: MySQL 5.7
- Prisma version: 2.3.0

**Comment by dpetrick** [comment]
This will be possible with the upcoming 2.10 release.
