### ISSUE TITLE
Incorrect where argument input type for nested to-one relation

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3154]
**Describe the bug**

For this datamodel

```
type Todo {
  id: ID! @unique
  text: String!
  done: Boolean!
  user: User!
}


type User {
  id: ID! @unique
  name: String!
}
```

The generated type for a to-one relation should have `UserWhereUniqueInput` as the input argument type. 
```
type Todo implements Node {
  id: ID!
  text: String!
  done: Boolean!
  user(where: UserWhereInput): User!
}
```

**To Reproduce**
1. Deploy the above datamodel

**Expected behavior**
The generated type for a to-one relation should have `UserWhereUniqueInput` as the input argument type. 

**Versions (please complete the following information):**
 - Prisma Server: `1.16.x`

**Comment by marktani** [comment]
This has been fixed.
