### ISSUE TITLE
prisma deploy error: 'Could not find the relation between the models Post and User in the database'

### ISSUE THREAD

**Issue by jchukwum** [prisma/prisma#3160]
Calling 'prisma deploy' to deploy locally is failing during validation of the data model.

The error message is  **'Could not find the relation between the models Post and User in the database'**

However, the database/datamodel.graphql file has the relation information. 

1. Clone the https://github.com/graphql-boilerplates/node-graphql-server repo
2. Setup the local prisma server this instructions: https://www.prisma.io/docs/get-started/01-setting-up-prisma-existing-database-a003/
3. Call prisma deploy
4. See error: **'Could not find the relation between the models Post and User in the database'**

**Screenshots**
The error:
![screen shot 2018-09-20 at 12 35 09](https://user-images.githubusercontent.com/2135562/45815811-b4110080-bcd1-11e8-86bc-f0b476611dbd.png)

file: database/datamodel.graphql
![screen shot 2018-09-20 at 12 37 16](https://user-images.githubusercontent.com/2135562/45815927-081be500-bcd2-11e8-842f-abc89d53cf9f.png)

**Versions (please complete the following information):**
 - OS: Ubuntu 17.10 
 - `prisma` CLI: prisma/1.16.5 (linux-x64) node-v8.11.3
 - Prisma Server: prisma:1.16

Please help.

**Comment by marktani** [comment]
I can't reproduce this, even by following your instructions. Could you try again on an entirely new setup?

**Comment by jchukwum** [comment]
Not to worry. Thanks for trying, I've since moved on and implemented my own version instead of using prisma. The response took too long to come.

**Comment by zuohuadong** [comment]
> I can't reproduce this, even by following your instructions. Could you try again on an entirely new setup?

@mahkali 

[yangkai.tar.gz](https://github.com/prisma/prisma/files/2859989/yangkai.tar.gz)

`docker-compose up -d `

` prisma deploy `

![image](https://user-images.githubusercontent.com/11203929/52706329-1986c600-2fc0-11e9-93ce-c3a8ac12082f.png)
