### ISSUE TITLE
Postgres introspection does not work reversely

### ISSUE THREAD

**Issue by beeplin** [prisma/prisma#3161]
**Describe the bug**

(from https://github.com/prisma/prisma/issues/1300#issuecomment-423130647)
[Postgres DB schema A] --(introspect)--> [prisma datamodel] --(deploy)--> [Postgres DB schema B]
A !== B

**To Reproduce**
1. create postgres tables (almost same with the example in the docs, only to change `serial` to `varchar(25)`): 
```sql
CREATE TABLE product (
  id           varchar(25) PRIMARY KEY UNIQUE
, description  text NOT NULL
);

CREATE TABLE bill (
  id         varchar(25) PRIMARY KEY UNIQUE
, notes      text NOT NULL
, product_id varchar(25) REFERENCES product (id) ON UPDATE CASCADE
);
```
The generated db structure:

![image](https://user-images.githubusercontent.com/13058150/45817888-acbe1700-bd12-11e8-8fab-585164e8cbf2.png)

PLEASE NOTE the foreign key `product_id` in table `bill`.

2. `prisma introspect`, getting the following datamodel (just like what the docs show, only `Int`  turns into `ID`):

```graphql
type Bill @pgTable(name: "bill") {
  id: ID! @unique
  notes: String!
  product: Product @pgRelation(column: "product_id")
}

type Product @pgTable(name: "product") {
  id: ID! @unique
  bills: [Bill!]!
  description: String!
}
```

3. `prisma deploy` the datamodel to a new postgres database, and here is the new db structure:

![image](https://user-images.githubusercontent.com/13058150/45817986-f149b280-bd12-11e8-97b6-19cc8b7a642f.png)

PLEASE NOTE that the foreign key `product_id` in table `bill` is missing, and there is a new cross table `_BillToProduct`. That means the one-to-many relationship is now linked with a many-to-many table, not a foreign key.

**Versions (please complete the following information):**
 - OS: Windows 10
 - `prisma` CLI:  `prisma/1.16.5 node-v10.10.0`
 - Prisma Server: 1.16
 - Postgresql: 10.5

**Comment by beeplin** [comment]
Related quotes from https://github.com/prisma/prisma/issues/1300#issuecomment-423126993:
> For a one-to-many relation it uses 3 tables (A - AB- B) instead of 2; for a M2M relation with extra fields, 5 tables (A - A(AB) - AB - B(AB) -B) instead of 3. Also see #3060. That harms query performance badly.

**Comment by pantharshit00** [comment]
@beeplin 

This should be fixed in the latest as we have switched to the new datamodel for introspection.
