### ISSUE TITLE
Prisma repository get connection feature

### ISSUE THREAD

**Issue by Q00** [prisma/prisma#3171]
## Problem
is repository exist in prisma? I wanna made base service ( like findOne or getList method )
## Suggested solution
Like type-goose or typeorm, I wanna make repository connection model in prisma

## Alternatives
just I have to type all the code in each service model

## Additional context

![image](https://user-images.githubusercontent.com/31264094/88911472-dc3bf400-d298-11ea-8915-65901e4d7f45.png)
this is typeorm base service.

![image](https://user-images.githubusercontent.com/31264094/88911580-fe357680-d298-11ea-8043-07f975a4cf0f.png)
this is mongo base service with type-goose

**Comment by pantharshit00** [comment]
Sorry for the extremely late reply here. This issue got buried and now it is getting picked up in cleanup. 

Prisma doesn't return a class instance but an plain javascript object so this is not applicable to Prisma. 

You can obviously make a custom class which encapsulates Prisma methods to make your own methods.
