### ISSUE TITLE
Enum property is "undefined" through prisma client

### ISSUE THREAD

**Issue by 4urbanoff** [prisma/prisma#3174]
Hi guys!

**Describe the bug**
I create type User with enum Gender
```gql
enum Gender {
    MALE
    FEMALE
}

type User {
    id: ID! @unique
    name: String!
    gender: Gender!
}
```
Deploy to demo server and client generation passed successful
Next I create new User and want receive gender property
```ts
import { prisma } from './generated/prisma'

async function main() {
    const user = await prisma.createUser({
        name: 'Denis',
        gender: 'MALE'
    })

    console.log(user.gender)
}

main()
```
But `user.gender` is `undefined`, property `gender` not exists in `user`

**To Reproduce**
I create repo with this bug:
1. clone `git@github.com:4urbanoff/prisma-enum-bug.git`
2. run `npm i`
3. run `npm run bug` or `Launch program` in vscode debugger
4. See error 🤪

**Expected behavior**
Expected `user.gender === 'MALE'`

**Screenshots**
![image](https://user-images.githubusercontent.com/9026994/45920818-ab2b5500-beb2-11e8-9156-32a165d9f38d.png)
![image](https://user-images.githubusercontent.com/9026994/45920808-9e0e6600-beb2-11e8-82ab-fb7c870beb40.png)

**Versions**
 - OS: `OS X High Sierra`
 - `prisma` CLI: `prisma/1.17.0-beta.30 node-v8.11.1`
 - Prisma Server: `prisma:1.17-beta-1`
 - `graphql@14.0.2`, `graphql-tools@3.1.1`, `prisma-client-lib@1.17.0-beta.30` 

**Additional context**
The problem is also stably reproduced in the local environment, e.g docker + mysql or docker + postgres.

**Comment by silkyland** [comment]
same here please help

**Comment by marktani** [comment]
Hi, thanks for the great bug report. This is a bug and we'll look into this soon!

**Comment by 4urbanoff** [comment]
Thanks!

**Comment by divyenduz** [comment]
This fix is available in the stable version - 1.18.1 - `npm install -g prisma` 🎉

**Comment by pckhoi** [comment]
This bug has returned in version 1.25.7. I'm using Go client.

**Comment by humariza** [comment]
I had the same problem with user permissions but when my users sign up , i just defined the permission in the data mutation like this:
permissions:{  set:['OWNER']}
and it works correctly. You can just define a const outside from the request and put it there

**Comment by alexdor** [comment]
I'm also facing the same bug, with the go client and it might also be related to #4463 . @pckhoi have you found a solution?

**Comment by pckhoi** [comment]
Not using enum?

**Comment by alexdor** [comment]
That's what I did as well but I meant one using the enum list
