### ISSUE TITLE
How are users utilizing prisma services in test/CI environments?

### ISSUE THREAD

**Issue by peterschussheim** [prisma/prisma#3178]
Every ORM and 'data layer' framework/tool provides a mechanism to correctly migrate data in order to run tests.

Typically, an API is provided that allows devs to implement relatively straightforward **'setup' and 'teardown' steps to be called before and after each test**.

I haven't seen anything in `prisma` that facilitates these workflows.  Are there any prisma team members or users who can share concrete examples of the aforementioned concepts?

**Comment by peterschussheim** [comment]
Thanks Nilan for those steps however it is not as simple as you make it appear.  It would be great if you are someone on the team provided an example that shows these steps in practice, in a real application that users to reference.

**Comment by marktani** [comment]
I didn't make anything appear simple or difficult. I simply stated the tools that you can use to setup or teardown a Prisma service.

Here's a very simple CI/CD setup for Prisma using Travis: https://github.com/prisma/prisma/tree/c60e15c0d458109d18d1e3c424662be1f58b3f89/examples/travis.

I am not aware of a more advanced example. Maybe there is one here: https://github.com/catalinmiron/awesome-prisma?

I agree that such an example would be very useful 👌Maybe you can try to put one together?

**Comment by itaied246** [comment]
I am actually working on this also.
I think using `prisma reset` is a very bad practice since it deletes the whole db !

What I would suggest is doing something like this:
Create a utility function (for tests only) that remove entities based on ids.
For example:

```js
let ids = []

beforeEach( () => {
  ids = insertData(...)
})

afterEach(() => {
  removeData(ids)
})
```

The remove function is just a mutation.
What do you guys think of this?
