### ISSUE TITLE
Input type without connect generated

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3179]
**Describe the bug**
For the datamodel
```
type User {
  id: ID! @unique
  optionalDetailsWithoutConnection: OptionalDetailsWithoutConnection
}

type OptionalDetailsWithoutConnection{
  text: String!
}
```

**To Reproduce**
1. Deploy the datamodel
2. An input type is generated without `connect`

```
input OptionalDetailsWithoutConnectionUpdateOneInput {
  create: OptionalDetailsWithoutConnectionCreateInput
  disconnect: Boolean
  delete: Boolean
  update: OptionalDetailsWithoutConnectionUpdateDataInput
  upsert: OptionalDetailsWithoutConnectionUpsertNestedInput
}
```

**Expected behavior**
Is this expected? 

**Versions (please complete the following information):** 
 - `prisma` CLI: `prisma/1.17.0-beta.24 (darwin-x64) node-v10.4.0`
 - Prisma Server: `1.17.0-beta`

**Comment by do4gr** [comment]
The bottom type does not have a unique property that can be used to connect it. That is why no connect is being generated. If a unique property is added to the type the connect should be created.
