### ISSUE TITLE
Reference to prisma dependency is wrong and potentially not required.

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#3187]
**Describe the bug**

`prisma-generate-schema` currently has a dependency on `prisma-cli@1.0.7`: https://github.com/prisma/prisma/blob/ec2dfb4a06cc6b7e2fdd92649f7d1338dcc3272a/cli/packages/prisma-generate-schema/package.json#L26.

It should be changed to `prisma@1.17`, or removed entirely.

**Comment by lewebsimple** [comment]
I think this issue prevents installing prisma, I'm getting the following error:
```
ENOENT: no such file or directory, chmod '../node_modules/prisma-generate-schema/node_modules/prisma-cli/dist/index.js'
```

**Comment by divyenduz** [comment]
@lewebsimple : Can you please try `rm -rf node_modeules && npm install` again?

**Comment by lewebsimple** [comment]
It had something to do with the globally installed version of prisma, thanks for the tip

**Comment by divyenduz** [comment]
This was resolved and is in stable now.
