### ISSUE TITLE
Add support for field descriptions in Prisma schema

### ISSUE THREAD

**Issue by osterkraft** [prisma/prisma#319]
Adding support for type/field descriptions would add a lot of value when designing and documenting data models. See related Prisma 1 issue: https://github.com/prisma/prisma/issues/2152

**Comment by schickling** [comment]
The semantics of the Prisma schema have changed quite a bit for Prisma 2 compared to Prisma 1. While Prisma 1 was mostly focussed on building GraphQL schemas, the schema in Prisma 2 is all about modeling your data.

@osterkraft can you please clarify the end-to-end behavior you'd like to see when you say "Adding support for type/field descriptions would add a lot of value when designing and documenting data models". The relationship to GraphQL is mostly covered via framework integrations like [nexus-prisma](https://github.com/prisma/nexus-prisma/tree/next/example) today.

**Comment by nelsonpecora** [comment]
I would assume that triple-slash comments in `schema.prisma` would be converted (in `nexus-prisma`) to descriptions. Is that the case? I can't find anything about that in `nexus-prisma`'s documentation.

**Comment by jasonkuhrt** [comment]
The idea of model-level and field-level meta-data such as (namely?) descriptions seems to apply to Prisma 2. There is nothing particular about this idea to GraphQL.

Toolchains should be able to choose how to act on / expose Prisma model meta data (descriptions). For example, it seems obvious to me that `nexus-prisma` would forward Prisma model/field descriptions as defaults for GraphQL obect/field/enum/etc. descriptions.

Is the `data-modelling.md` file herein the authoritative source of truth (aka. spec) for PSL?

**Comment by tvvignesh** [comment]
@schickling @timsuchanek Is this already available or in the roadmap? Wondering how to add comments/descriptions to my schema when defining the table, fields and types. Something along the lines of this: https://www.compose.com/articles/postgresql-tips-documenting-the-database/ where Postgres offers COMMENT to document your database, table and its fields and I am not so sure about the support in other databases but if they don't support it, it can be added as comments (https://dba.stackexchange.com/questions/84280/how-to-format-documentation-in-ms-description-extendedproperties) and restored from there when doing lift/migrate.

**Comment by janpio** [comment]
Internal Note: Reframing this as "general descriptions" instead of "GraphQL descriptions", that could be picked up by nexus and Co.

**Comment by thebiglabasky** [comment]
Is field-level usage of PSL comments like `///` sufficient?
@pantharshit00 has contributed a Docs generator using these which I feel could provide a temporary solution: https://github.com/pantharshit00/prisma-docs-generator

If not, I'd like to understand what is missing there. Thanks!

**Comment by casey-chow** [comment]
> If not, I'd like to understand what is missing there. Thanks!

I think the biggest thing for me is adding JSDoc strings to the generated client so I don't have to back into the PSL to understand the context behind a field.

**Comment by Jolg42** [comment]
Related https://github.com/prisma/prisma/issues/3544

**Comment by tomhoule** [comment]
We are understanding this as a request to add docs to client types through DMMF. Since the comments on fields / models / etc. are already made available there, we think it would be a client feature.

**Comment by janpio** [comment]
I think this was already implemented via https://github.com/prisma/prisma/pull/10248, can you confirm @millsp? 

If so, just close this issue. Other related use cases are tracked via https://github.com/prisma/prisma/issues/8703 or https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+comments%22+sort%3Aupdated-desc
