### ISSUE TITLE
subscription works via mutation queries but not manual pg sql queries

### ISSUE THREAD

**Issue by TakaGoto** [prisma/prisma#3191]
**Describe the bug**
subscription works via mutation queries but not manual sql queries, ex: 'insert into headers () values ();`

**To Reproduce**
1. `prisma init` choose new database with postgres
2. create a schema for a table
3. `prisma deploy`
4.  run a subscription query
5. insert a row to the database via psql console.

**Expected behavior**
expected subscriber to be notified of the insert

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - `prisma` CLI: prisma/1.16.5 (darwin-x64) node-v10.9.0
 - Prisma Server: [e.g. `1.7.4`]

**Additional context**
not sure if subscriptions are only notified by mutation queries. couldnt figure that out with searching the internet.

**Comment by marktani** [comment]
This is expected. Subscriptions are only triggered for mutations through the Prisma API.
