### ISSUE TITLE
Typeorm + prisma error

### ISSUE THREAD

**Issue by renehauck** [prisma/prisma#3202]
## Bug description
I have a nestJs server which also has typeorm installed. Now I would like to use the PrismaClient in parallel. But now I always get this error:
```
Could not load source map from acorn.js.map
Could not load source map from walk.js.map

/home/rene/projekte/prismatest/node_modules/@prisma/client/app/src/node_modules/.pnpm/undici@1.1.0/node_modules/undici/lib/client-base.js:506
    .on(protocol === 'https:' ? 'secureConnect' : 'connect', function () {
^
AssertionError [ERR_ASSERTION]: false == true
    at Socket.<anonymous> (/home/rene/projekte/prismatest/node_modules/@prisma/client/app/src/node_modules/.pnpm/undici@1.1.0/node_modules/undici/lib/client-base.js:506:1)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:150:17)
Waiting for the debugger to disconnect...
Process exited with code 1
```

## How to reproduce

1. Create nestjs server 
2. connect to a database with typeorm 
3. add the Prisma Client
4. start server...see the error

## Environment & setup

- OS:Ubuntu
- Database: PostgreSQL
- Node.js version: v12.18.3
- Prisma version: 2.3.0

```

```

**Comment by pantharshit00** [comment]
Can you please share a reproduction in a git repository? This involves a bit of setup and I am not very experienced with nest + typeorm so it would be very helpful.

**Comment by renehauck** [comment]
@pantharshit00 

i have now created a sample project and cannot reproduce the error. :facepalm:  It seems to be something else, so typeorm is not the problem. Do you have an idea what else it could be? The whole thing happens stupidly in a company project and I can't share the code
Thanks for your help.

**Comment by pantharshit00** [comment]
Hm, without a reproduction, I can't unfortunately help here. The error seem to be coming from the http client library which we use: https://github.com/mcollina/undici

Maybe try removing the node_modules and the package manager lock file and trying again.

**Comment by renehauck** [comment]
hmm, not helping. Really stupid, I'll keep on searching, but close the issue and would just open it again when I found it. 
Thanks for the help! :smiley:
