### ISSUE TITLE
Prisma login should work in environment without a browser, such as codesandbox.io

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma#3205]
**Describe the bug**
When using the Prisma CLI in the new https://codesandbox.io container environment, signing in fails with error code 3. This happens because the login flow requires the CLI to open a browser window, which is not available in the container environment.

To work around the issue, you can manually copy the login url, but because the CLI returns an error, it is not longer listening for the successful login.

**To Reproduce**
1. Get access to the new https://codesandbox.io container environment (currently invite only)
2. Install Prisma
3. Use the CLI to login

**Expected behavior**
Instead of returning an error, the CLI should tell the user to copy/paste the url, and keep listening for successful login.

**Comment by divyenduz** [comment]
This is resolved in `1.25.0-beta.5` (install via `npm install -g prisma@beta`) via this PR https://github.com/prisma/prisma/pull/3842

Here is a sample sandbox that can be used to test it: https://codesandbox.io/s/91qj216zny

**Comment by divyenduz** [comment]
This might still yield this message incorrectly on some operating systems, see https://github.com/sindresorhus/opn/issues/86

However, this won't stop them from logging in.

**Comment by ecker00** [comment]
Thank you, that worked for me! 🎉 With the `@beta` installed. Very useful when running in a headless vm.

**Comment by divyenduz** [comment]
This is available in the latest version `1.25.0`, `npm install -g prisma`. I am closing this issue. Please let me know if the issue still persists via opening a new issue.
