### ISSUE TITLE
Client generation with a custom live endpoint

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3206]
**Is your feature request related to a problem? Please describe.**
Add support for custom endpoint for client generation. 

**Describe the solution you'd like**
This would add the following syntax to cli `prisma generate --endpoint <url>`

**Describe alternatives you've considered**
After https://github.com/prisma/prisma/pull/3203 is merged, we should be able to use the endpoint defined by `prisma.yml` already. 

**Additional context**
Original spec: 
https://github.com/prisma/prisma/issues/3184

**Comment by w0wka91** [comment]
Hey,

I was just looking into that issue and about to create a new branch but it looks like that this https://github.com/prisma/prisma/pull/3203 is not merged into the alpha branch.

**Comment by divyenduz** [comment]
It is merged into `beta` branch. You can use it using `npm install -g prisma@beta`

**Comment by pantharshit00** [comment]
Closing as this is already available.
