### ISSUE TITLE
Routing bug at Prisma Docs

### ISSUE THREAD

**Issue by arin-kwak** [prisma/prisma#3216]
**Describe the bug**
the "get started" page at Prisma Docs shows me 1.18(beta) version of the page(In fact, https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-a002/).
but the version selector at the top left shows 1.17(latest)
![image](https://user-images.githubusercontent.com/29162801/46259278-4efbad00-c512-11e8-980e-85870093da6d.png)

**To Reproduce**
1. Go to https://www.prisma.io/docs/
2. Just click "Get started" at the side bar

**Expected behavior**
I think users who clicked the page should be routed to https://www.prisma.io/docs/1.17/get-started/01-setting-up-prisma-new-database-a002/, not to https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-a002/.
The other pages look good.

**Comment by timsuchanek** [comment]
Thanks for reporting! We just fixed it. If this is still a problem for you, please let us know and we reopen  this issue.
