### ISSUE TITLE
Cannot fetch table names in SQLite

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma#3218]
## Bug description

As per this discussion: https://github.com/prisma/prisma/discussions/3213 the table names in the SQLite DB cannot be fetched via a raw query.

## How to reproduce

1. Create any model and migrations with `sqlite` as the connector.
2. Run this snippet

```ts
const result = await prisma.queryRaw`SELECT name FROM sqlite_master WHERE type = "table";`
console.log(result);
```

This always returns empty.

## Expected behavior

The list of tables should be available

## Environment & setup

- OS: Mac OS
- Database: SQLite
- Node.js version: 12.18.2
- Prisma version: 2.4.0

**Comment by pantharshit00** [comment]
You will need to use the database name in order to get the table names:
```ts
const result = await client.$queryRaw`SELECT name FROM dev.sqlite_master WHERE type = "table";`;
console.log(result);
```

**Comment by pantharshit00** [comment]
Result of the posted query:
![image](https://user-images.githubusercontent.com/22195362/89641779-0eb8a300-d8d0-11ea-8ffd-5968176bbfc0.png)

**Comment by janpio** [comment]
Should the initial query then not return an error @pantharshit00?

**Comment by pantharshit00** [comment]
I am not sure how quaint is handling that. cc @tomhoule or @pimeys(when you are back)

**Comment by tanem** [comment]
> You will need to use the database name in order to get the table names:
> 
> ```ts
> const result = await client.$queryRaw`SELECT name FROM dev.sqlite_master WHERE type = "table";`;
> console.log(result);
> ```

Thanks @pantharshit00! I'll make a note in the original discussion too 👍
