### ISSUE TITLE
prisma npm dependency issue (npx prisma is not runnning)

### ISSUE THREAD

**Issue by ltnscp9028** [prisma/prisma#3222]
npx prisma ~~ and npm install prisma is not running.
is not my local issue, many user have same issue. 

==error message==
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mrmlnc%2freaddir-enhanced - Not found
npm ERR! 404 
npm ERR! 404  '@mrmlnc/readdir-enhanced@^2.2.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'fast-glob'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by ryands17** [comment]
@ltnscp9028 NPM is down
https://status.npmjs.org/

If you have Prisma locally installed then it will work
