### ISSUE TITLE
Remove GraphQL related reserved words

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3223]
Current we are reserving `Query`, `Mutation` and `Subscription` as they are used in the GraphQL protocol between Prisma Client and Engines - and having a model with those names would lead to a clash.

https://github.com/prisma/prisma-engines/blob/b8f18700982efba305ff78db8f5e3c816e6a90b5/libs/datamodel/core/src/transform/ast_to_dml/reserved_model_names.rs#L9-L12

We should confirm if and why those are problematic.

If they are not, we should remove them from the list of reserved words.

If they are, we could probably work around that by e.g. prefixing the generated type for this model with a magic string for the communication, which is then split off again both in Engine and Client again before running queries or returning to the user.

Internal discusssion: https://prisma-company.slack.com/archives/CEYCG2MCN/p1596651950210600

**Comment by janpio** [comment]
Current workaround: Use a different name for you model, and use `@@map("Subscription")` to map it onto the table.

**Comment by matthewmueller** [comment]
Since we don't use `Subscription` in the protocol, could we just support that?

**Comment by mavilein** [comment]
Update:
@dpetrick did an exploratory PR about this topic: https://github.com/prisma/prisma-engines/pull/1084
The gist is that model output types are renamed from `<ModelName>` to `<ModelName>OutputType`. This removes the need for many reserved keywords, check the diff [here](https://github.com/prisma/prisma-engines/pull/1084/files#diff-8f940de32ad7770433016f60cec6d0ae).
@timsuchanek needs to look into this proposal and evluate it. It might be that this renaming would mean a breaking change for users.

**Comment by timsuchanek** [comment]
This is finally done in the latest dev version.
