### ISSUE TITLE
Prisma account randomly downgraded from paid to free. Service degraded.

### ISSUE THREAD

**Issue by obibring** [prisma/prisma#3230]
**Describe the bug**
I was paying $45 / month for a hosted prisma server. Lately, performance has been terrible. I logged back into my account to investigate, and noticed that I was inexplicably no longer on a paid plan.

**Expected behavior**
To still be on a paid plan and not see degraded performance.

**Comment by marktani** [comment]
Thanks for reaching out.
Please send an email from the email address you registered with to `support@prisma.io`.
Our support team will help you to resolve the situation.
