### ISSUE TITLE
Ability to generate json schema via custom generator

### ISSUE THREAD

**Issue by MinimogDev** [prisma/prisma#3230]
## Problem

There are some servers like [fastify](https://www.fastify.io/) that allow to define json schemas in order to provide better performance and input / output data validation. Right now I am using prisma with fastify and have to manually define such schemas. Most of these, however, would match types generated by prisma 1 to 1. I looked around and found few tools like `json-schema-to-typescript` and `typebox` that convert json schemas to types, but nothing that does the opposite.

Besides these servers there are some services like [aws api gateway](https://aws.amazon.com/premiumsupport/knowledge-center/model-api-gateway/) that also utalise such schemas. It would be awesome to have these generated by prisma alongside types (say under a flag in cli?), as I think prisma has all data to do this.

## Suggested solution

Perhaps introduce a new cli flag like `--json-schema` to `prisma generate` command that would output these alongside types so they can be imported an used?

## Alternatives

Right now these have to be written manually.

## Additional context

Example below shows how a simple prisma model can be converted to json schema, there are more examples available at https://json-schema.org/understanding-json-schema that show various data type outputs for json schemas.

**prisma schema**
```graphql
model User {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
  posts     Post[]
}
```

And I believe json schema for this would look as simple as 

**json schema output**
```js
const UserSchema = {
   id: 'number',
   createdAt: 'string',
   email: 'string',
   name: 'string',
   role: {
     type: 'string',
     enum: ['ADMIN', 'AUTHOR']
   },
   posts: {
      type: 'array',
      items: {
         type: 'object',
         properties: {
            id: 'number'
         }
      }
   }
}
```

**Comment by pantharshit00** [comment]
This can be implemented as a custom Prisma generator in the future from the schema.

**Comment by janpio** [comment]
Can you maybe add an example Prisma schema and the equivalent Json schema to the issue description @MinimogDev? A custom generator as @pantharshit00 seems like a great solution here and should be pretty easy to build - if there is an example what this would look like.

**Comment by MinimogDev** [comment]
@janpio sure, something like this:

**prisma schema**
```graphql
model User {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
  posts     Post[]
}
```

And I believe json schema for this would look as simple as 

**json schema output**
```js
const UserSchema = {
   id: 'number',
   createdAt: 'string',
   email: 'string',
   name: 'string',
   role: {
     type: 'string',
     enum: ['ADMIN', 'AUTHOR']
   },
   posts: {
      type: 'array',
      items: {
         type: 'object',
         properties: {
            id: 'number'
         }
      }
   }
}
```

This is a very simple example, but there are a lot of detailed examples available at https://json-schema.org/understanding-json-schema that cover all possible types like arrays / enums / booleans etc... that I thing should map really good to prismas schema models.

**Comment by pantharshit00** [comment]
@MinimogDev If you want to give this a shot, you can make a "Prisma JSON Schema" generator. You can find the generator spec here: https://github.com/prisma/specs/tree/master/generators

You can the docs generator as reference example as well: https://github.com/pantharshit00/prisma-docs-generator

Basically a generator gets a parsed dmmf format over stdin and it manipulate it do things like writing a json schema.

**Comment by valentinpalkovic** [comment]
I would like to give it a try :)

**Comment by pantharshit00** [comment]
Awesome 💯, let us know if we can improve the generator API in any manner :)

**Comment by valentinpalkovic** [comment]
And here it is! https://www.npmjs.com/package/prisma-json-schema-generator

It is my first npm package though. Just give me a hint, if something is not working from the beginning on and create an issue if you miss a functionality or something is not working like expected!

**Comment by pantharshit00** [comment]
Awesome @valentinpalkovic ! Nice work

**Comment by lothemar** [comment]
Is this closed or should I submit a patch?

**Comment by janpio** [comment]
There is a community solution by @valentinpalkovic, see https://github.com/prisma/prisma/issues/3230#issuecomment-697982781, that looks pretty good. If that does not satisfy your needs, you can either collaborate on that one (create a PR etc) or create your own.

**Comment by pantharshit00** [comment]
I will close this for now.
