### ISSUE TITLE
Request adding rpc style syntax into .prisma files

### ISSUE THREAD

**Issue by ericbets** [prisma/prisma#3231]
## Problem
Making database backed microservices is labor intensive busywork. 

## Suggested solution
Allow rpc syntax & pseudo query types in the .prisma file format. For example,
```console
model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields:  [authorId], references: [id])
  authorId  Int?
}

//query types
model PostTitles {
  title String  @references (Post:title)
  content String @references (Post:content)
}

rpc getBlogCatalog(RangeRequest) returns (PostTitles) {}
```

In this scenario, PostTitles is a query type for returning the subset of data required for a specific rpc style query. It turns out that grpc is a nice fit for this because you can use interceptors for rbac & input validation. However the underlying code generated for the interface could be rpc, REST or something else not invented yet.  So this feature request is primarily about allowing lines that start with the word rpc to become a valid Prisma schema keyword, and also to support @references or something similarly flexible to enable 'partially hydrated' types in the database component of the api. The content between {} could be used to encode an arbitrary json object that also might contain js functions. I propose being non prescriptive here about obj format as it creates flexibility for the service template designer. 

## Alternatives
Using .proto files with custom options as the top level schema.

## Additional context
[Prior discussion](https://github.com/prisma/prisma/discussions/3123#discussioncomment-47976)
[Functional dbs blog like post](https://github.com/ericbets/erics-designs/blob/master/funcdb.md)

**Comment by matthewmueller** [comment]
Hey @ericbets, thanks for sharing your perspective. I can totally see the motivation for this, as it's one less schema you need to care about.

I don't think this is a great fit for us though. We're focused primarily on the data modeling layer and aim to work with any RPC, GraphQL, REST API.

We are considering ways for users to customize and extend the Prisma Schema. Maybe this could be an extension you create on top 🙂

There's some more information on the topic here: https://github.com/prisma/prisma/issues/515
