### ISSUE TITLE
Minimize list of reserved words for usage as model names

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3233]
Right now we have a quite extensive list of terms that are "reserved words" that can not be used in model names and similar as they would clash with internal functionality:

- https://github.com/prisma/prisma/blob/c36c1a7a84a5be3fd12522870a2f48cabdb6b833/src/packages/client/src/generation/generateClient.ts#L461-L629
- https://github.com/prisma/prisma-engines/blob/b1c5396ac9832eb8481b3c7f36c393ab1747211d/libs/datamodel/core/src/transform/ast_to_dml/reserved_model_names.rs#L8-L121

As this limits the tables our users can call by the same model name as in their database, we want to minimize this list. Current workaround: Use a different name for you model, and use `@@map("original_name")` to map it onto the table.

This issue tracks the individual issues we are using to investigate this:

- https://github.com/prisma/prisma-client-js/issues/811 - `Aggregate`
- https://github.com/prisma/prisma/issues/3223 - GraphQL terms
- https://github.com/prisma/prisma/issues/3755 – Potential solution

**Comment by matthewmueller** [comment]
@timsuchanek and I chatted about this briefly today. #3755 is looking like a good solution to hide non-model generated types behind a `Prisma` namespace.

#### Problem

_Anything_ we do will be a breaking change, types that you imported before will change. For example,

```ts
// Reserved type Query...
import { Query } from '@prisma/client'

// ... would now be namespaced under Prisma
// to make room for the model Query type...
import { Prisma } from '@prisma/client'
type Query = Prisma.Query
 
// ... and type Query would point to the Query model
// type (if there is one).
import { Query } from '@prisma/client'
```

#### Goal

Get down to only Javascript types being restricted for the model names, `model await`, `model break`

We may even be able to do better than this, for example, `type type = { ... }` is a valid Typescript type, but `type return = { ... }` is not.

#### Next Steps

- [ ] @matthewmueller does some research to try and see how big of a breaking change this will be for people.

**Comment by matthewmueller** [comment]
Went through 50 of 100 pages of public code results containing `from "@prisma/client"`. I've excluded `import { PrismaClient } from "@prisma/client"` which was the most common by far.



<details>
<summary>
<b>Data Collected</b>
</summary>

https://github.com/berkaycimsir/prisma-next/blob/7b308cbca748a0643b90c443a590cc32ad38a932/graphql/types/movie/mutation.ts

```
import { Subset } from '@prisma/client';
import { MovieCreateArgs } from '@prisma/client';
import { Movie } from '@prisma/client';
```

https://github.com/Axon-VetCare-Technologies/knex-prisma/blob/cd086d0345a14cbae186a3f9650940a4ee9f3b41/src/generated/knex-prisma.ts

```
import { PostWhereUniqueInput } from './prisma-client'
import { UserWhereUniqueInput } from './prisma-client'
import { PostWhereInput } from './prisma-client'
import { UserWhereInput } from './prisma-client'
import { PostCreateInput } from './prisma-client'
import { Post } from './prisma-client'
import { UserCreateInput } from './prisma-client'
import { User } from './prisma-client'
import { PostUpdateInput } from './prisma-client'
import { UserUpdateInput } from './prisma-client'
```

https://github.com/Shinyaigeek/blitztwitter/blob/202ec2128fda03c32d0ab6b6c4cb29070bbbc7e9/db/index.ts
https://github.com/panzerstadt/tut-blitz/blob/dfa9bea6f704823ffcc39d05defdb2236dd4fd2f/db/index.ts
https://github.com/abuuzayr/techjobs/blob/acd192ec8f0f144891ab4eac76906dbe2a6bc4a6/db/index.ts
https://github.com/TroyRobinson/blitzjs/blob/93ce1f42ee620cabf006e9033c2b5c9977b97c4e/db/index.ts
https://github.com/flybayer/cincijs-demo/blob/ddf49ee3ab110486ca5976f33596321f502ed0d3/db/index.ts

```
import { PrismaClient } from "@prisma/client"
export * from "@prisma/client"

const prisma = new PrismaClient()

export default prisma
```

https://github.com/duplepie/prisma-server/blob/f0f3a3d022dc822a1a688c42b82b0602be19a9c4/src/utils.ts

```
import { Coin as CoinDb } from '.prisma/client'
```

https://github.com/IAmTheVex/arck/blob/4c9f9b1772e4f4eb89882a82cd6e15c73485124e/packages/prisma/reflection/DMMFProcessor.ts

```
import {PrismaClient} from "@prisma/client";
import {DMMF} from "@prisma/client/runtime";
```

https://github.com/chenaski/taskich-back/blob/381111ae776b6545a040af2715ec3c056d2736de/src/operator/operator.controller.ts

```
import { OperatorCreateInput } from '@prisma/client';
import { Operator } from '@prisma/client';
```

https://github.com/FabienArcellier/spike-orm-python-typescript/blob/676e5d26ce27fb428c0f15959cc8abb6abd89b7a/sportsdb_backend_typescript/src/api/query.ts

```
import { Datasource } from '@prisma/client/runtime';
```

https://github.com/berkaycimsir/prisma-next/blob/b6a6a57367dd21a647e476483587675b99f9f031/graphql/types/movie/movie.ts

```
import { User } from '@prisma/client';
import { UserClient } from '@prisma/client';
```

https://github.com/wSedlacek/prisma-generators/blob/24c30e3b3adfa628a4e3ea221658ad13f20527fe/libs/nestjs/src/dev/write-dmmf.ts

```
import { getDMMF } from '@prisma/client/runtime';
import { DMMF as PrismaDMMF } from '@prisma/client/runtime/dmmf-types';
```

https://github.com/wSedlacek/prisma-generators/blob/24c30e3b3adfa628a4e3ea221658ad13f20527fe/libs/nestjs/tests/helpers/dmmf.ts

```
import * as generatorBuild from '@prisma/client/generator-build';
import { DMMF } from '@prisma/client/runtime/dmmf-types';
import { GetDMMFOptions } from '@prisma/sdk';
```

https://github.com/gabrielcolson/acacia/blob/3bc237992c4439d5d4c44b787a56e4954d6065c2/db/index.ts

```
import { PrismaClient, User, Space, Expense } from "@prisma/client"
```

https://github.com/anyl92/Romi/blob/a5a3d00381a6f69887dd9762a8e6fa040cf9c51b/back-end/redis/robot.ts

```
import { Robot } from '@prisma/client'
```

https://github.com/bylucasxdx/nwl-ecoleta/blob/101168e044ee55b10e1b5279ff819f0a94cc4093/backend/src/modules/points/infra/prisma/entities/Point.ts

```
import { Item } from '@prisma/client';
import { Point } from '@prisma/client';
```

https://github.com/alexandre-poirier/GOLO-Graphql-backend-assignment/blob/ef283edc96114bd5ae609058d8e3c77b6587ad43/backend/src/types.ts

```
import prisma from '@prisma/client';
```

https://github.com/Gabriel2233/Brainstormer/blob/1e8852a3ad83b8d4ce6baf16ad7352d7655f87bb/web/pages/api/brainstorm/create.ts

```
import { StormPieceCreateManyWithoutBrainstormInput } from "@prisma/client";
import { User } from "@prisma/client";
```

https://github.com/matart15/adventure-capitalist-clone/blob/b69057030c11941c3a04bbd65ce646898ccf958c/backend/prisma/seed.ts

```
import { PrismaClient, Business, Asset, AssetCreateInput } from '@prisma/client'
```

https://github.com/peachporn/peach/blob/363c57dddd074b6137f56aedbd48f21c8473a1df/src/tasks/screencaps/type.ts

```
import { MovieGetPayload } from '@prisma/client';
```

https://github.com/tbjgolden/prisma-typegraphql/blob/18a11046a433ad1ece0f3e7e16dae21da0228a68/resolvers/generated/resolvers/outputs/UserSumAggregateOutputType.ts

```
import { JsonValue, InputJsonValue } from "@prisma/client";
```

https://github.com/srdpt/ctklg/blob/8f771ef97be27fac9aa0f402b7bfd0bef269f58c/services/src/widgets/census.types.ts

```
import { JsonObject } from "@prisma/client";
```

</details>

**Analysis**

- Lots of folks import the model types. We probably shouldn't break this
- Lots of Blitz demos. Blitz encourages `exports * from @prisma/client` which is unfortunate
  - Further analysis would need to be done to see what Blitz users import
- Next is input types. This would break quite a few people.
- Long tail of import types that only show up in 1 or 2 public codebases (e.g. JsonValue, JsonObject, Subset?)

**Comment by Jolg42** [comment]
@matthewmueller I think this can be closed now since the Prisma namespace is done?

**Comment by pantharshit00** [comment]
Indeed, I am going to close this.
