### ISSUE TITLE
Support Int with id fields and migrations

### ISSUE THREAD

**Issue by saip92** [prisma/prisma#3233]
**Is your feature request related to a problem? Please describe.**
Currently, the `id` fields can only be either of type `ID` or `UUID`.

For use cases that want auto-increment integers for ids can do so now with `migrations: false` and existing tables.

**Describe the solution you'd like**
Would be great if `Int` were supported as well like this

```
id: Int! @serial @unique
```

**Describe alternatives you've considered**
The alternative to this is having an existing schema with integer, write / generate graphql schema using introspection and deploying to the server with `migrations: false`

**Comment by mavilein** [comment]
I have just published [spec](https://github.com/prisma/prisma/issues/3408) that touches on this topic. We would love to hear your feedback on this one.

**Comment by brafdlog** [comment]
@divyenduz I want to use Int for ids. If I don't want prisma to handle db migrations, is there any other problem with using int for id?

**Comment by mavilein** [comment]
@brafdlog : Not that we know of. Some users are already running this in production.

**Comment by jide** [comment]
So in theory it's possible to use Ints for id fields ? If I do this and deploy I get this error (at least with demo servers) :
```
The field `id` is reserved and has to have the format: id: ID! @unique or id: UUID! @unique.
```

**Comment by pantharshit00** [comment]
@jide The new datamodel will be available in today's beta release under prototype flag in prisma.yml

I think then you will be able to use it.

**Comment by jide** [comment]
That's fantastic !

**Comment by jide** [comment]
So adding :

**Comment by pantharshit00** [comment]
It is current in alpha. Please wait till we release today's beta (1.28-beta)

Then install the alpha version of the cli and use the following config:

```
port: 4466
prototype: true
databases:
  default:
    connector: postgres
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: prisma
    rawAccess: true
```

**Comment by jide** [comment]
I've tried adding prototype to prisma.yml, both with the alpha and since then with the fresh 1.28 beta. But I keep getting the error : 
```
Invalid prisma.yml file
 ▸    prisma.yml should NOT have additional properties. additionalProperty: prototype
```

I use demo servers. Something I overlooked ?

**Comment by pantharshit00** [comment]
@jide

You need to add this to  docker-compose file , not to the prisma.yml

**Comment by jide** [comment]
Ah ok thanks, so I guess demo servers are not concerned atm ? they have this flag off I guess.

**Comment by pantharshit00** [comment]
Yes, demo servers has this off as this is even very new for demo servers

**Comment by jide** [comment]
So I set up a docker instance with 1.28 beta, and the new directives seem to work: I can deploy the datamodel.

But it does not seem to have any effect on the generated graphql API, there is no id field in the create* mutations, ids are still auto-generated. If I try using Int for ids, The server errors.

Mutation works, but the id is auto-generated :
```
type Test {
  id: ID! @id(strategy: NONE)
  title: String!
}

mutation {
  createTest(data: {
    title: "Hello"
  }) {
    id
  }
}
```

Mutation fails ("Whoops. Looks like...etc") :
```
type Test {
  id: Int! @id(strategy: NONE)
  title: String!
}

mutation {
  createTest(data: {
    title: "Hello"
  }) {
    id
  }
}
```

**Comment by jide** [comment]
I'm super confused, why is there no change to the prisma graphql API with the new datamodel ?

**Comment by pantharshit00** [comment]
I think for `Int` you need to define a sequence

```graphql
type Test {
  id: Int! @id(strategy: SEQUENCE) @sequence(name: "MY_SEQUENCE" initialValue:1 allocationSize:100)
  name: String!
}
```

cc @mavilein , please clarify this

**Comment by mavilein** [comment]
`@id(strategy: NONE)` is not implemented yet. Someone will implement it in the next weeks. cc: @do4gr 
The example provided by @pantharshit00 should work.

**Comment by jide** [comment]
Ahhh okay makes sense ! Thank you for the explanation.

**Comment by pantharshit00** [comment]
I think we can close this now as this is already available now.
