### ISSUE TITLE
Prisma Deploy failed 

### ISSUE THREAD

**Issue by shashankn91** [prisma/prisma#3236]
[datamodel-old.prisma.zip](https://github.com/prisma/prisma/files/2437162/datamodel-old.prisma.zip)
For the data model attached I am getting following errors when I am trying to do prisma deploy.

Errors:

  Alert_offer
    ✖ The required field `id` is missing and has to have the format: id: ID! @unique or id: UUID! @unique or id: Int! @unique.

  Checkout_order_offer
    ✖ The required field `id` is missing and has to have the format: id: ID! @unique or id: UUID! @unique or id: Int! @unique.

  Slowmoving
    ✖ The required field `id` is missing and has to have the format: id: ID! @unique or id: UUID! @unique or id: Int! @unique.

  Storemasteroffer
    ✖ The required field `id` is missing and has to have the format: id: ID! @unique or id: UUID! @unique or id: Int! @unique.

  Tagproduct
    ✖ The required field `id` is missing and has to have the format: id: ID! @unique or id: UUID! @unique or id: Int! @unique.

  Checkoutorder
    ✖ The relation field `payment` must specify a `@relation` directive: `@relation(name: "MyRelation")`
    ✖ The relation field `payments` must specify a `@relation` directive: `@relation(name: "MyRelation")`

  Payment
    ✖ The relation field `checkoutorder` must specify a `@relation` directive: `@relation(name: "MyRelation")`
    ✖ The relation field `checkoutorders` must specify a `@relation` directive: `@relation(name: "MyRelation")`

**Comment by shashankn91** [comment]
What is `passive connector` ?

**Comment by marktani** [comment]
Hi @shashankn91, this is actually [a current limitation](https://github.com/prisma/prisma/issues/2377) of the "passive Postgres connector".

> What is passive connector ?

This is the current terminology to talk about a Prisma database connector that uses introspection to automatically generate the datamodel. In constrast to "active connectors" who use the datamodel you create to determine the database schema.

Anyway, I'm quoting the current limitations of the passive Postgres connector:

> Model types must always have an id field. If the name in the schema diverges use the pgColumn directive: id: Int! @unique @pgColumn(name: "my_id_column")

Does this help in your case?

**Comment by shashankn91** [comment]
Yeah it does . I got my errors resolved by putting id field in all tables . It does work well if the application was started with Prisma . But if I am using your feature to generate graphql files with client for existing database it does make it weird because not all tables should have an "id" field . Lets say I am having many to many relationship between a and b which will force me to create an association table with primary_key of "a" and primary key of "b" and they together act as a primary key for the association which makes having one more column with id redundant .
