### ISSUE TITLE
Stuck on Applying Changes Using relation between "Access" and "User"

### ISSUE THREAD

**Issue by kevrat** [prisma/prisma#3237]
**Describe the bug**
Stuck on applying changes if entity "Access" have field user with type "User".
So it's stuck on:
```
AccessToUser (Relation)
  + Created relation between Access and User
```

**To Reproduce**
```
type Access implements Node {
  id: ID! @unique
  user: User!
}
```

```
type User implements Node {
  id: ID! @unique
}
```
**Expected behavior**
Changes applied

**Versions (please complete the following information):**
"prisma": "^1.10.2"
"graphql-cli": "^2.16.3"

**Additional context**
If i remove user field, or rename User or Access then everything is ok.

**Comment by kevrat** [comment]
Sorry, my bad

**Comment by marktani** [comment]
What was the problem?

**Comment by kevrat** [comment]
@marktani 
I can't understand. 
I change "Access" to "Permission" and it all worked. 
Also i experimmented with adding and removing some relations field in Access entity and if i have more than 1 relation it is stuck. But as i say - now, with "Permission" it is worked.
I will reopen this issue if i can understand what is happening.
Maybe it is because before "prisma deploy" i restore my backup from production db and it is like some conflict
