### ISSUE TITLE
List of integers in SQLite introspected as a list even though SQLite doesn't natively support lists

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#3238]
## Given

```sql
create table model (
  col int []  unique
);
```

## Expected

An error saying that sqlite doesn't support scalar lists.

## Actual

```prisma
// The underlying table does not contain a valid unique identifier and can therefore currently not be handled.

// model model {

// This type is currently not supported.

// col int []? @unique

// }
```

Note that the commenting out is because there's no primary key. For this issue though, just look at `col int []?`. 

TODO create an example that illustrates the problem without commenting it out.

**Comment by tomhoule** [comment]
Candidating in order to confirm that this does not happen any more, and fix if it does.

**Comment by do4gr** [comment]
Just confirmed this is not happening anymore.
