### ISSUE TITLE
executeRaw case sensitivity issue

### ISSUE THREAD

**Issue by jleed** [prisma/prisma#3238]
`
mutation {
  executeRaw(
    database: default,
    query: "SELECT * FROM Receipt"
  )
}
`

I getting an error  ERROR: relation \"receipt\" does not exist\n  Position: 15
cause table name is actually "Receipt" and not "receipt"

`
mutation {
  executeRaw(
    database: default,
    query: "SELECT * FROM \"Receipt\""
  )
}
`

also didn't help.

**Comment by mavilein** [comment]
Hi @jleed ,
thanks for reaching out to us and reporting this bug! Can you please follow our bug template and provide the missing pieces? This way we have unfortunately no fix this bug. We need reproduction steps so we can look into it, e.g. what connector are you using?
