### ISSUE TITLE
Support unsigned integers in the schema

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#3239]
Right now schema doesn't carry information about unsigned integers. 

This came out of https://github.com/prisma/prisma/issues/1823.
This could be supported by #446

**Comment by juretopolak** [comment]
Fileds with @id attributes, type of Int or BigInt and autoincrement() attribute function should also be UNSIGNED since the value can't be negative. This way the available range would be doubled.

**Comment by tomhoule** [comment]
Note that these are supported where they exist. `id Int @db.UnsignedInt` works. I added a `docs` label for it to be documented in https://www.prisma.io/docs/concepts/database-connectors/mysql#overview. cc  @mhwelander

**Comment by juretopolak** [comment]
@tomhoule thx... I'm new to Prisma so sorry for requesting the already existing "feature" :D

**Comment by tomhoule** [comment]
No worries, we need this issue because it looks like it isn't documented.

**Comment by Jolg42** [comment]
On MySQL these native types are available 
```
UnsignedSmallInt
UnsignedTinyInt
UnsignedInt
UnsignedMediumInt
UnsignedBigInt
```

like `id Int @db.UnsignedInt`
