### ISSUE TITLE
Add `omit` option for field selection

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma#3246]
## Problem

I've discovered a common issue where you want to select all the fields on a model except for one or few. For example, on a `User` model, I always want to omit the `hashedPassword` field, but retain everything else. 

Currently the only way to do this is to manually `select` each field, but this is prone to bugs because after adding a new field to the schema, it's easy to forget to add that field to the `select` object.

Another not-ideal workaround is this:
```ts
  const {hashedPassword, ...rest} = user
  return rest
```

## Suggested solution

In addition to the `select` parameter, I would like an `omit` parameter to be added.

```ts
const result = await prisma.user.findOne({
  where: { id: 1 },
  omit: {
    hashedPassword: true,
  },
})
```

**Comment by matthewmueller** [comment]
Thanks for your suggestion! This is being tracked in https://github.com/prisma/prisma-client-js/issues/649. I've added your proposal to this issue.
