### ISSUE TITLE
`prisma init` arrow keys not working using Git Bash on Windows 10

### ISSUE THREAD

**Issue by alexanderte** [prisma/prisma#3246]
**Describe the bug**
When running `prisma init` using Git Bash on Windows 10 the arrow indicator doesn’t move when pressing up or down arrow keys. Also the active selection is not shown in a blue color like is shown when running from Command Prompt.

**To Reproduce**
1. Open Git Bash
2. Run `prisma init`
3. Press down arrow
4. See that nothing happens

**Expected behavior**
I would expect it to behave like in Command Prompt.

**Versions (please complete the following information):**
 - OS: Windows 10
 - `prisma` CLI: `prisma/1.17.1 (windows-x64) node-v10.10.0`

**Comment by chasen-bettinger** [comment]
I have this issue as well.

**Comment by ddtxra** [comment]
I have this issue on my mac, even when doing 'prisma introspect', chosing the db is ok, but then it hangs on 'enter database host'

**Comment by saseokjun** [comment]
I have this issue on my mac(iterm) too. It works in the first phase, "Set up a new Prisma server or deploy to an existing server?", but not working in the second phase. Even "Control + C" also not working.

**Comment by chihaby** [comment]
I have the same issue, I can not navigate with the arrow keys.

**Comment by slaughterb** [comment]
I have the same issue on MacOS v 10.13.4; however, it seemed to respond to keys K/J as up/down.

**Comment by ericauv** [comment]
I also have this problem. Cannot navigate with arrow keys

**Comment by theryanclausen** [comment]
me too. Can't navigate with arrows, can't get past enter database host step.

**Comment by nboltn** [comment]
yeah I can't get past `primsa init` at all because of this. is there seriously no fix for this?
