### ISSUE TITLE
$queryRaw should be able to create nested objects

### ISSUE THREAD

**Issue by mohe2015** [prisma/prisma#3248]
## Problem
When creating custom queries it may be benefical to be able to return multiple objects at once.
For example it would be awesome if the following:
```typescript
console.log(await context.db.$queryRaw<RoundWithRunner[]>`SELECT "Round".id AS "id", "Runner".id AS "studentId", "Runner".id AS "student.id" FROM "Round", "Runner" LIMIT 1;`)
```
would result in:
```javascript
[
  {
    id: 'ckdlr23bn121811mlgqpp4g0imp',
    studentId: 'ckdlqzxyr0219mlgqgchjs34c',
    student: {
      id: 'ckdlqzxyr0219mlgqgchjs34c'
    }
  }
]
```
instead of
```javascript
[
  {
    id: 'ckdlr23bn121811mlgqpp4g0imp',
    studentId: 'ckdlqzxyr0219mlgqgchjs34c',
    'student.id': 'ckdlqzxyr0219mlgqgchjs34c'
  }
]
```

## Suggested solution
I think it would be useful if `$queryRaw` would replace dots with nested objects.

## Alternatives
I don't know but you probably have more knowledge of the internals.

**Comment by Sytten** [comment]
I disagree, queryRaw is for pure SQL and the behaviour should not deviate from that with some preprocessing.

**Comment by mohe2015** [comment]
Okay. I also decided to just do it manually (using unflatten)
