### ISSUE TITLE
Querying DateTime sets time to 0:00:00

### ISSUE THREAD

**Issue by danielbuechele** [prisma/prisma#3250]
## Bug description

I am using @prisma/client@2.4.1 together with a SQLite database. One of my columns is defined as type `DateTime` in my prisma.schema. Inserting a JS Date object works fine and a millisecond timestamp is stored in the column reflecting the correct date and time. However, when reading this value the time of the selected row is set to `0:00:00`.

## How to reproduce

```
await prismaClient.session.create({
        data: {
          expires: new Date(),
          token: 1,
          userId: 1,
        },
});

const {date} = await prismaClient.session.findOne({
      where: {
        token: 1,
      },
});

console.log(date);
```

## Expected behavior

The returned Date object should have the correct time.

## Prisma information

```
model Session {
  token   String   @id
  userId  String
  expires DateTime
}
```

## Environment & setup

- OS: macOS
- Database: SQLite
- Node.js version: 14.7.0
- Prisma version: 2.4.1

**Comment by pantharshit00** [comment]
Hey @danielbuechele 

I wasn't able to reproduce it with the reproduction that you provided. I had to modify your script a bit as it wasn't matching the data types used in the schema and names of few fields were also off.

So here is what I used for the reproduction:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const prismaClient = new PrismaClient();
  await prismaClient.session.create({
    data: {
      expires: new Date(),
      token: "1",
      userId: "1",
    },
  });

  const data = await prismaClient.session.findOne({
    where: {
      token: "1",
    },
  });

  console.log(data);
  prismaClient.disconnect();
}

main();
```
Result of execution:
![image](https://user-images.githubusercontent.com/22195362/90200862-d85eb480-ddf6-11ea-87bc-bc2565f872b6.png)


Can you please check once what data you have in your database? Also, if the data in the database in not sensitive, can you please upload the sqlite file here? Thanks!

**Comment by danielbuechele** [comment]
I narrowed this down to a problem with my SQLite database. For some reason, the type of the column was set to `DATE` instead of `DATETIME`. And while the correct timestamp is stored in the table, the time is set to 0:00:00 when querying it, which probably makes sense, because in that case you only want to store the date and not the time?
Here is an example of the DB: https://d.pr/f/qmt9Pq+
While I am not sure what the expected behavior for `DATE` columns, I guess we can close this task because it seems to be a problem with my local database rather than Prisma.
