### ISSUE TITLE
Remove watch mode for deployment

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#3251]
**Is your feature request related to a problem? Please describe.**
`prisma deploy` exposes the `--watch` option. It is not very useful in my opinion, and [doesn't fully work](https://github.com/prisma/prisma/issues/2178).

**Describe the solution you'd like**
Remove the `--watch` option from `prisma deploy`.

**Comment by nunovieira** [comment]
Was trying to use this option for a local development environment and found this issue.
Could the `--watch` option be fixed instead of removed?
Alternatively, how could this functionality be implemented without this option?

**Comment by marktani** [comment]
At the moment, the feature doesn't work, and wasn't intended to be included, so entirely removing it is an improvement.

I am open to discussing to add this feature, but personally I don't see its benefit.

**Comment by nunovieira** [comment]
I've implemented this behaviour using [nodemon](https://github.com/remy/nodemon).
I'm OK with removing it. It's not an essential feature and it can be done by other means.
