### ISSUE TITLE
Middlewars give error they need to be enabled when they are

### ISSUE THREAD

**Issue by MichaelHindley** [prisma/prisma#3255]
## Bug description

Unable to use previewFeature "middlewares"

## How to reproduce

Given 
```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["middlewares"]
}


  prisma = new PrismaClient()
  prisma.use/$use(async (params, next) => {
    console.log('hello')
    const result = await next(params)
    return result
  })
```

When trying to use `prisma.use` in 2.3 or`prisma.$use` in 2.4, the follow error is observed:

```
[ERROR] 12:46:28 Error: In order to use the middlewares api, please enable set previewFeatures = ["middlewares"]
```

## Expected behavior

middlewares to load

## Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["middlewares"]
}


model Product {
  id String @id @default(uuid())
  name String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt() @default(now())
}
```

## Environment & setup

- OS: macos
- Database: postgres
- Node.js version: v12.18.3
- Prisma version:

```
6.14.6
```

**Comment by MichaelHindley** [comment]
false positive, enabling previewFeatures requires running `prisma generate`

**Comment by janpio** [comment]
Good you figured that out.

Internal note: A `doctor` like command would possibly have been able to point that out.
