### ISSUE TITLE
Misleading error message when attempting to overwrite a required relation using "connect"

### ISSUE THREAD

**Issue by jwld** [prisma/prisma#3256]
## Bug description

Say you have a parent-child relation, where the parent field on the child is required:
```
model Booking {
  id           String               @default(cuid()) @id
  subscription PaymentSubscription?
}

model PaymentSubscription {
  booking   Booking @relation(fields: [bookingId], references: [id])
  bookingId String
  id        String  @default(cuid()) @id
}
```

In a situation where the parent already has a child, if you then try and create a second child on that parent using connect, it first tries to disconnect the original child from the parent, triggering the following error:
```
Null constraint violation on the fields: (`bookingId`)
```

The issue is that at first glance this looks like there's an issue with the data _being passed_ when creating the second child. Took me way too long to realise that this parent _already had a child_, and that by trying to create another one it was attempting to disconnect the first child and triggering this error.

## How to reproduce

Repo available [here](https://github.com/jwld/prisma-issue).

## Expected behavior

The error should alert you to the fact that the parent already has a child, so a second one cannot be created without invalidating the first.

## Environment & setup

- OS: Mac OS
- Database: Postgres
- Node.js version: 14.5.0
- Prisma version:

```
2.4.1
```

**Comment by pantharshit00** [comment]
I am unable to reproduce the exact same error message in the latest version `2.5.1`:
![image](https://user-images.githubusercontent.com/22195362/91049812-62025380-e63b-11ea-9ba7-87786bef529d.png)

Now regarding the error on why this is exactly erroring out. The relation between `PaymentSubscription` and `Booking` is 1 to 1 relation according to schema, which mean one `PaymentSubscription` can be connected to `Booking` at any given. This is represented by a unique index on the database level: 
![image](https://user-images.githubusercontent.com/22195362/91049960-9f66e100-e63b-11ea-8a6a-59cbaa4224c9.png)

Now if you will try to connect the same `Booking` record to two different `PaymentSubscription` records, it is just not possible and the engine throws this error. It never tries to disconnect the old one, that would be a very bad behaviour.

**Comment by jwld** [comment]
I can no longer recreate it either (not even with 2.4.1, not sure why). It would be nice if there was a more specific error message for that scenario, but that error message you shared is a bit less misleading so I'll close this.

Thanks!
