### ISSUE TITLE
prisma-client not returning non-required json fields.

### ISSUE THREAD

**Issue by tiagocpontesp** [prisma/prisma#3261]
```graphql
type A {
  y: Json
}
```
`y` won't be returned by the prisma client.

```graphql
type B {
  x: Json!
}
```
`x` will.

**Comment by marktani** [comment]
Hi @tiagocpontesp, I cannot reproduce this error. Can you share a reproduction repository?

For reference, for this datamodel:

```graphql
type User {
  id: ID! @unique
  name: String!
  json: Json
  anotherJson: Json!
}
```

after this mutation

```graphql
mutation b {
  createUser(data: {
    name: "Nilan"
    json: "{ \"a\": 1 }"
    anotherJson: "{ \"a\": 1 }"
  }) {
    id
  }
}
```

this code

```js
const { prisma } = require('./generated/prisma')

const main = async () => {
  const u = await prisma.users()
  console.log(u)
}

main()
```

will reproduce this expected result:

```
[ { id: 'cjn1v7vy90acs0b72x3ujkflz',
    name: 'Nilan',
    json: { a: 1 },
    anotherJson: { a: 1 } } ]
```

I'm on version `1.18.0-beta.22`. Please provide the information as per the [bug report template](https://github.com/prisma/prisma/issues/new?template=bug_report.md).

**Comment by schickling** [comment]
This seems to be fixed. Please comment again to re-open this issue if it still persists for you using the recent version.

**Comment by tiagocpontesp** [comment]
Hi. I apologise @marktani, this got fixed very quickly, and I didn't notice the update.
