### ISSUE TITLE
Enum organization improvement

### ISSUE THREAD

**Issue by pbelbin** [prisma/prisma#3263]
## Problem
Is it possible to have all of the enum definitions that currently occupy the 'top level' of the Prisma namespace be accessible through a hierarchy of model then column, and for that to still be very user-friendly within IDEs?

Having some nesting/structure might make the size of the identifier a little bit longer, but, it might help ensure the correct list of enum options are chosen from.

VSCode has a habit of figuring out what the various enum values decode to, and making them easily selectable, but, this kind of defeats the benefit of using enums, which is, that the mapping of the name -> value allows the value to be changed while the name can be left exactly the same, avoiding having to alter every usage of the underlying value.

## Suggestion
I am not sure I want to break what's already there, but, rather, add a way to also do this:

pseudo schema: 
```
enum PostEmotion {
  MEH
  ANGRY
  HAPPY
}

model Post {
  ...
  emotion PostEmotion?
}
```

something like this perhaps?:
```
import { enums } from '@prisma/client';
...
await prisma.post.create({ data: { 
  ... 
  emotion: enums.post.emotion.HAPPY
}})
```

**Comment by janpio** [comment]
Unfortunately not. Prisma tries to stay close to the structure the database offers, and that is pretty one dimensional usually. We recommend you use the names of the blocks like models and enums to create any hierarchy you might want to.
