### ISSUE TITLE
Prisma Format should enforce opinionation for order of attributes

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#3269]
When rendering a schema we have a specific order in which attributes
 on a field are rendered.

At the moment users can order the attributes however they want when manually defining a schema. When they then run re-introspection they will get noisy diffs because the attributes will be reordered. 

This could be prevented if Prisma format would enforce the same opinionation about attribute orders as the schema renderer.

**Comment by mavilein** [comment]
With this issue we adapted the order of attributes in the Prisma schema.
This is our current order to stable:
* block level: map, unique, index, id
* field level: map, id, unique, default, relation, updatedAt

We changed it to this order to reflect our perceived importance of those attributes:
* block level: id, unique, index, map
* field level  : id, unique, default, updatedAt, map, relation
