### ISSUE TITLE
Cannot find module ps-node in windows

### ISSUE THREAD

**Issue by chakrihacker** [prisma/prisma#3269]
Installed prisma globally and ran prisma init or prisma both are not working

**To Reproduce**
1. Install prisma globally in windows 
2. run prisma init
3. See error cannot find module ps-node

**Expected behavior**
initialize prisma

**Screenshots**
![error-screenshot](https://imgur.com/a/eD5IrdH)

**Versions (please complete the following information):**
 - OS: Widnows 10
 - prisma/1.17.1 (windows-x64) node-v10.11.0

**Comment by marktani** [comment]
Can you share the error screenshot?
Are you aware of the underlying issue, or a potential fix?

**Comment by chakrihacker** [comment]
![prisma_error](https://user-images.githubusercontent.com/5210019/46782693-be5c7280-cd44-11e8-9ca5-fc771b2734f7.png)

this is what I got, If you can point me where the error is I can try to fix it

**Comment by chakrihacker** [comment]
Any update??

**Comment by chakrihacker** [comment]
Thanks @lephenix1234
