### ISSUE TITLE
Duplicate identifier 'Action' in `node_modules/.prisma/client/index.d.ts`

### ISSUE THREAD

**Issue by guog** [prisma/prisma#3272]
## Bug description

When there is `model Action` in `schema.prisma`, the following error occurs when running `tsc` error

## How to reproduce

`schema.prisma`

```
model Action {
  id   String  @id @default(cuid())
  name String?
}
```

`Actions.ts`
```typescript
import { schema } from 'nexus'

schema.objectType({
  name: 'Action',
  definition(t) {
    t.model.id()
    t.model.name()
  }
})
```

run `npx prisma generate && tsc` An error occurred

```
node_modules/.prisma/client/index.d.ts:205:13-error TS2300: Duplicate identifier'Action'.
205 export type Action =
node_modules/.prisma/client/index.d.ts:987:13-error TS2300: Duplicate identifier'Action'
987 export type Action = {
```

`node_modules/.prisma/client/index.d.ts`

```
export type Action =
  | 'findOne'
  | 'findMany'
  | 'create'
  | 'update'
  | 'updateMany'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
// ...

/**
 * Model Action
 */

export type Action = {
  id: string
  name: string
}
```

## Expected behavior

`Action` should not conflict with the type in prisma client

## Prisma information

`schema.prisma`
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["aggregateApi", "distinct", "middlewares"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Action {
  id   String  @id @default(cuid())
  name String?
}
```

## Environment & setup

- OS: Mac OS Catalina
- Database: PostgreSQL
- Node.js version: 14.7.0
- Prisma version:
```
@prisma/cli          : 2.4.1
Current platform     : darwin
Query Engine         : query-engine 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/prisma-fmt-darwin)
Preview Features     : aggregateApi, distinct, middlewares
```

**Comment by WellFail** [comment]
https://github.com/prisma/prisma/issues/3233

**Comment by pantharshit00** [comment]
Hey @guog 

Looks like we are using `Actions` as a reserved word in our typing. It also seems it is not currently in our deny. I think we can easily rename this one to `PrismaActions` cc @timsuchanek 

For now you can remap the field to a different name as a workaround:
```prisma
model _Action {
  id   String  @id @default(cuid())
  name String?
  @@map("Action")
}
```

**Comment by guog** [comment]
@pantharshit00 
Thanks

**Comment by Jolg42** [comment]
Thanks for reporting!
We definitely want to remove as many reserved words as we can so we'll look into that.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
