### ISSUE TITLE
Field names for 1:N relations are lost in the DMMF

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#328]
Steps to reproduce:

1. Have a schema like so:
```
model User {
  id      Int    @id
  myPosts Post[]
}

model Post {
  id     Int  @id
}
```

Photon's typings are correct, but in the DMMF generated, `datamodel.models[0].fields[1].name` is `post`, instead of `myPosts`.

Studio uses this name to generate labels for fields in the Details area.

**Comment by madebysid** [comment]
Also discovered that this happens to 1:1 relations as well.
The following datamodel behaves incorrectly as well:
```
model User {
  id      Int    @id
  myPosts Post
}

model Post {
  id     Int  @id
}
```

**Comment by madebysid** [comment]
Also interesting is that it does not happen for inline relations in tables managed by `prisma1`, which is what I've been introspecting so far for Studio development.

**Comment by pantharshit00** [comment]
This is no longer relevant.
