### ISSUE TITLE
Choosing UUID for the id field breaks create mutations

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#3281]
**Describe the bug**
If you set your `id` field to be of type `UUID`, the create mutation won't work.

**To Reproduce**
1. Add a new type like this to your datamodel:

```graphql
type Test {
  id: UUID! @unique
  test: String!
}
```

2. Deploy
3. Run this mutation:

```graphql
mutation {
  createTest(data: {test: "abc"}) {
    id
  }
}
```

4. You'll receive an internal server error:

> java.sql.SQLException: (conn=820223) Incorrect string value: '\\xAC\\xED\\x00\\x05sr...' for column 'id' at row 1

**Expected behavior**

* Either, we cannot set `UUID` for the `id` field
* Or, when running `createTest` as above, the `id` field is automatically generated.

**Versions (please complete the following information):**
 - Prisma Server: `1.18-beta-1`

**Additional context**
Current workaround: use `id: ID! @unique` instead.

**Comment by mavilein** [comment]
This only happens for the MySQL connector. For Postgres it just works.

**Comment by kshenes** [comment]
Is there a plan to get this resolved?  It makes UUIDs hard to use with MySQL.

prisma 1.23.0

java.lang.Thread.run(Thread.java:748)","message":"(conn=5) Incorrect string value: '\\xAC\\xED\\x00\\x05sr...' for column 'id' at row 1"}}
[Bugsnag - local / testing] Error report: com.bugsnag.Report@76edad95
java.sql.SQLException: (conn=5) Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'id' at row 1
 on fixing this

**Comment by kshenes** [comment]
We have a customer requirement to have every object instance be identified by a UUID so it can be reconciled to its origin when encountered in logs. They are unable to change their existing harvesting system to use the ID format.  Also just to add a data point. In my 20+ years working with distributed system I would say 90% of them relied on UUID/CUID/GUID at some level. Some of them generate the UUID based on the natural keys of the object, so supporting @autogenerate vs @required would also be a bonus.

**Comment by mavilein** [comment]
@kshenes : I agree that not having this inconsistency is better. However we are using JDBC to interact with MySQL and Postgres. But those drivers do not behave consistenly with respect to UUIDs unfortunately. We definitely want to lift this constraint in the future and i am asking those questions just to get a better understanding. So in your case it is rather a matter of integrating with an existing system. Thanks that helps 🙏  👍

**Comment by kshenes** [comment]
OK, we can add secondary uuid fields, quick questions, 1) any time frame on roachDB? 2) secondary/alternate index creation?

**Comment by mavilein** [comment]
@kshenes :
1. What's roachDB?
2. We have a PR for this in the works. We will pick it up at the beginning of the new year again.

**Comment by kshenes** [comment]
sorry for the Brevity. I was speaking about Cockroachdb https://www.cockroachlabs.com/product/cockroachdb/

I thought I heard there was a movement about creating an adapter for it?

**Comment by pantharshit00** [comment]
Datamodel 1.1 allows custom IDs so we can not provide a custom UUID there.

https://github.com/prisma/datamodel-v1.1-feedback

**Comment by divyenduz** [comment]
We do not allow `UUID` with MySQL. I am turning this issue into a feature request as the Prisma server no longer accepts `UUID` in a MySQL datamodel.
