### ISSUE TITLE
Prisma generate for `Flow` client does not import DocumentNode from graphql. v1.18.0-beta.16

### ISSUE THREAD

**Issue by abhiaiyer91** [prisma/prisma#3287]
**Describe the bug**
`prisma generate` for the `flow` client adds a `DocumentNode` type without importing it from `'graphql'`

**To Reproduce**
1. Install Beta: `1.18.0-beta.16`
2. Run `prisma generate` for a flow application
3. Notice that the generated prisma client is missing the import for `DocumentNode`

**Comment by divyenduz** [comment]
@abhiaiyer91 : I wonder how was this working for the `flow-graphql` example in prisma examples.

**Comment by divyenduz** [comment]
This fix is released in `prisma@1.19.0-beta.2`
