### ISSUE TITLE
1:1 relations' `isList` property is incorrect in the DMMF

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#329]
Assume this datamodel:
```
model User {
  id   Int @id
  post Post
}

model Post {
  id Int @id
}
```

In the DMMF, `dmmf.models['User'].fields['post'].isList` is `true`, which is incorrect.

Photon typings are still correct though.

Studio uses this information to make significant decisions about this field.

**Comment by madebysid** [comment]
Also interesting is that it does not happen for inline relations in tables managed by `prisma1`, which is what I've been introspecting so far for Studio development.

**Comment by pantharshit00** [comment]
Not sure on how you are retrieving the dmmf(I don't know this part of the internals), the dmmf that photon exposes has the correct values:
![image](https://user-images.githubusercontent.com/22195362/62490127-34efc280-b7e6-11e9-9932-d17e567f9736.png)

I am going to add `need-info` label for now. Maybe @timsuchanek has some insights.

**Comment by pantharshit00** [comment]
I am using prisma2@2.0.0-alpha.91, binary version: 7b1615a0376f0428948c4410e57a0b61c03d5960

**Comment by madebysid** [comment]
Ah, I generate the DMMF using a helper from Lift, passing in a datamodel/schema generated by introspecting a DB (this only happens in the Electron app).

I'll be a little more explicit about the steps I'm taking:

1. `prisma2 init` in an empty folder, point it to an existing (empty) Postgres DB
2. Change the `schema.prisma` to:
```
model User {
  id   Int @id
  post Post
}

model Post {
  id Int @id
}
```
3. `prisma2 dev` to apply the migrations

I'm then introspecting the Postgres table just created in the Electron app, using `prisma-db-introspection`. Essentially, I'm using prisma2 to create a DB with a few relational columns rather than make it myself.

So now if you introspect this, it yields:
```
{
  "renderer": {},
  "databaseType": "postgres",
  "model": [
    {
      "name": "Post",
      "columns": [
        {
          "name": "id",
          "type": "int4",
          "isList": false,
          "readOnly": false,
          "isUnique": false,
          "isAutoIncrement": false,
          "defaultValue": "0",
          "isNullable": false,
          "comment": null
        },
        {
          "name": "user",
          "type": "int4",
          "isList": false,
          "readOnly": false,
          "isUnique": false,
          "isAutoIncrement": false,
          "defaultValue": null,
          "isNullable": false,
          "comment": null
        }
      ],
      "indices": [],
      "primaryKey": {
        "tableName": "Post",
        "name": "Post_pkey",
        "fields": [
          "id"
        ],
        "unique": true,
        "isPrimaryKey": true
      }
    },
    {
      "name": "User",
      "columns": [
        {
          "name": "id",
          "type": "int4",
          "isList": false,
          "readOnly": false,
          "isUnique": false,
          "isAutoIncrement": false,
          "defaultValue": "0",
          "isNullable": false,
          "comment": null
        }
      ],
      "indices": [],
      "primaryKey": {
        "tableName": "User",
        "name": "User_pkey",
        "fields": [
          "id"
        ],
        "unique": true,
        "isPrimaryKey": true
      }
    }
  ],
  "relations": [
    {
      "sourceColumn": "user",
      "sourceTable": "Post",
      "targetColumn": "id",
      "targetTable": "User"
    }
  ],
  "enums": [],
  "sequences": []
}
```

and the datamodel generated by `isdlToDatamodel2` using this introspection result is:
```
datasource postgres {
  provider = "postgresql"
  url      = "postgresql://siddhant@127.0.0.1:5432/experiments?schema=public"
}

model Post {
  id   Int  @id
  user User
}

model User {
  id   Int    @id
  post Post[]
}
```
which has the wrong relation.

Just looking at these two things, I'd put my money on `isdlToDatamodel2` doing something wrong.

If this issue belongs on the `lift` repo (since that's where isdlToDatamodel2 comes from), please feel free to move it!

**Comment by pantharshit00** [comment]
I can reproduce this behaviour now, but I don't know the internals.

Well I will let @timsuchanek handle this now.

**Comment by pantharshit00** [comment]
This is no longer relevant
