### ISSUE TITLE
No more autocompletions since go-client generator rewrite

### ISSUE THREAD

**Issue by Sach97** [prisma/prisma#3294]
**Describe the bug**
Since #3278 my autocomplete is acting weird.
With the 1.17.1 the code generated on this [repo](https://github.com/Sach97/prisma-go-hackernews) branch master autocompletes without any issue. However with the prisma-1.19.0-alpha21 
cli installed and the[ corresponding branch](https://github.com/Sach97/prisma-go-hackernews/tree/prisma-1.19.0-alpha21) my autocomplete is broken but the server works fine (mutation, queries, etc).

**To Reproduce**
1. `~ $ git clone https://github.com/Sach97/prisma-go-hackernews2/edit/master/README.md ` in your GOPATH
2.` ~ $ cd prisma-go-hackernews2`
3. `prisma-go-hackernews2 $ docker-compose up -d`
4. `prisma-go-hackernews2 $ cd prisma`
5. `prisma $ prisma deploy`
6. Try to modify the code preferably with a relation like User().Votes() to see the that autocomplete is broken (or not)

**Expected behavior**
I would like an autocomplete as I had before the fix (which I still have on the other branch by the way).
See screenshot below : 
![screenshot from 2018-10-10 14-23-48](https://user-images.githubusercontent.com/18029834/46740593-89e4aa00-cca3-11e8-856f-f413f688cca5.png)

**Versions (please complete the following information):**
 - OS: `Ubuntu 18.04`
 - `prisma` CLI: `prisma@1.19.0-alpha.21`
 - `docker-image` : `prismagraphql/prisma:1.17.1`
 - `go-client`
- `go-version` : 1.11.1 linux/amd64

**Additional context**
I tried to clean my docker volumes, my visual studio code cache but no success

**Comment by gregwebs** [comment]
Did you delete the old generate `lib.go` file and then run `dep ensure`? Make sure VSCode believes your generated prisma.go file compiles without error.

**Comment by gregwebs** [comment]
After an initial generation, autocompletion won't work until the prisma library is vendored and that import works in prisma.go

**Comment by Sach97** [comment]
I tried again by following your instruction, and using the prisma-examples/go-graphql. I did a dep ensure and it added those lines to my Gopkg.lock file. Is it normal ? Sorry first time I use dep. 
```
[[projects]]
  branch = "master"
  digest = "1:9375143c4ab1022872156e3b08c482c09b6bb66dfc2ae415fce2ebeb25df0889"
  name = "github.com/prisma/prisma-examples"
  packages = ["go-graphql/prisma-client"]
  pruneopts = "UT"
  revision = "773c80079ab4475f5935eec4d003354149a0786b"
```
Then I did a go build and it builds and runs correctly. But I still don't have **autocompletion**. Here is my vendor package : 
![screenshot from 2018-10-11 12-38-51](https://user-images.githubusercontent.com/18029834/46798742-1a2df800-cd53-11e8-8149-4fadf3790341.png)


> Make sure VSCode believes your generated prisma.go file compiles without error.

The only errors I have are those ones from resolver.go : 

![screenshot from 2018-10-11 12-43-21](https://user-images.githubusercontent.com/18029834/46798873-755fea80-cd53-11e8-86c1-90c44b267be0.png)

**Comment by Sach97** [comment]
Finally got it working it was an issue related to [vscode go extension](https://github.com/Microsoft/vscode-go/issues/1723) apparently, and my upgrade from go version 1.9.7 to 1.11. To solve the issue I did a `go install` in prisma-client folder. If it still doesn't work try in all the subfolder of the vendor folder.
