### ISSUE TITLE
Prisma generate - `Error: write EPIPE` on WSL <-> Windows

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3294]
## Bug description

In the internal introspection CI: https://github.com/prisma/introspection-ci/issues/309#issuecomment-674075918

We ran into `Error: write EPIPE` with MacOS. Here is the internal commit: https://github.com/prisma/introspection-ci/pull/316/commits/392528c430679bfd42ac8d09e98e8d9403c1502c#diff-99e681890513b0f406b692a64ece0ddb

This has been seen before but was closed due to no reproduction: https://github.com/prisma/prisma/issues/1816

Environment: 

- Multiple `prisma generate` commands were running in parallel
- One of the commands has `Error: write EPIPE`
- Some generate commands failed with no output (may or may not be related)

## How to reproduce

- Probably try to run the same command on MacOS as the CI did. Introspection CI, branch `fix_309`

```
yarn -s generator-ci:prepare-generate
yarn -s generator-ci:run-generate
```

## Prisma information

```
@prisma/cli          : 2.5.0-dev.52
Current platform     : darwin
Query Engine         : query-engine 8f08c6fa89afd00710e41d99621786150b7eebbe (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 8f08c6fa89afd00710e41d99621786150b7eebbe (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 8f08c6fa89afd00710e41d99621786150b7eebbe (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 8f08c6fa89afd00710e41d99621786150b7eebbe (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.254.0
```

**Comment by pantharshit00** [comment]
I am unable to run on my tiny macbook as it doesn't have enough memory. My laptop almost crashed when I ran this. 

![image](https://user-images.githubusercontent.com/22195362/90403504-b434f900-e0be-11ea-9cb8-f5994fc49b60.png)

I need a more powerful machine or need to do this in a server. Maybe someone else with a more powerful machine from the team can confirm this instead.

**Comment by Jolg42** [comment]
Could not reproduce 🤷‍♂️ 

This is intense in RAM and takes a few minutes.

<img width="756" alt="Screen Shot 2020-08-17 at 16 19 35" src="https://user-images.githubusercontent.com/1328733/90406447-77a8d380-e0a5-11ea-9f65-c2fcdf221880.png">

**Comment by ForbesLindesay** [comment]
I'm also getting this error, with what looks like the generate command running multiple times in quick succession:

![image](https://user-images.githubusercontent.com/1260646/91184785-eeb51c00-e6e4-11ea-8722-13fb6fd4cb10.png)

**Comment by janpio** [comment]
Can you help us reproduce this @ForbesLindesay? An example project on Github would be gold here.

**Comment by ForbesLindesay** [comment]
It's in a pretty big project so not super easy to extract. It seemed to be watch mode only, and the setup I was using was a  ubuntu docker image. We've disabled watch mode, which seems to have fixed the issue for now.

One suggestion: I think the files may end up appearing to be edited multiple times in quick succession. If you added a short (say 200ms) debounce to the file system watcher you are using, I suspect that would resolve things. Alternatively you could throttle the generate function to only run once at a time using something like https://www.npmjs.com/package/throat

**Comment by Jolg42** [comment]
@ForbesLindesay Indeed something like that is happening probably, thanks for the feedback!

**Comment by AlaaZorkane** [comment]
Any updates on this? I am using Prisma on WSL2 (Ubuntu2020) and each time I update my schema the watcher crashes with `EPIPE`
![image](https://user-images.githubusercontent.com/2952507/103397698-c0839500-4b39-11eb-9aa4-65f68e0b1308.png)

**Comment by pantharshit00** [comment]
Hey @AlaaZorkane 

Does this happen in first save or after leaving it for some time and then trying to save the file?

**Comment by AlaaZorkane** [comment]
Hey @pantharshit00 

Both, leaving it or not.
I tried saving with another editor (vim) and the watcher didn't crash, my theory is that it has something to do with both the Prisma VS code extension trying to lint/format and the watcher trying to read what's being written/updated, wyt?

Also another thing, the watcher crashes even if I make no changes to the file and save (causing it to still be linted/formatted by the prisma extension) so I guess that supports what I think it's happening?

**Comment by pantharshit00** [comment]
I can kind of reproduce this and I think this is related to https://github.com/prisma/prisma/issues/4308

I will wait here for #4308

**Comment by pantharshit00** [comment]
Still blocked by #4308 

I bumped that one.

**Comment by aqrln** [comment]
Haven't reproduced with the watch command yet, however the previous comments mention generating clients in parallel. When multiple instances of `prisma generate` in parallel, I can reliably get another error: `ENOENT: no such file or directory, unlink '/Users/aqrln/prisma/transient-repros/parallel-gen/node_modules/.prisma/client/index.js'` and sometimes `Unexpected end of JSON input`.

**Comment by aqrln** [comment]
When using `prisma generate --watch`, I can't reproduce the `EPIPE` error either with the latest Prisma but I can confirm that we still don't throttle the filesystem events and start regenerating the client in parallel multiple times when the schema file is being saved often. This is something that we should improve regardless of whether this leads to errors because it is suboptimal (and prone to races: I haven't gone as far as to check if it actually happens, but it's quite plausible that one of the generators spawned earlier might sometimes take longer than the ones spawned later and will overwrite the client with one generated for an outdated schema).

**Comment by aqrln** [comment]
The error happens in `GeneratorProcess#sendMessage` when we try call `getManifest` or `generate` but the generator process has exited because of an error or because it was killed.

Reproduced in tests in https://github.com/prisma/prisma/pull/19385. I'll fix it in that PR as well.
