### ISSUE TITLE
Necessary but missing query arguments

### ISSUE THREAD

**Issue by samy-mnasri** [prisma/prisma#3301]
Hi Prisma !

**Problem**
There are some query arguments that I would love to be able to use and that would make Prisma GraphQL API a more complete and really powerful ORM:

**Order by: Random**
I think that it would be very useful to be able to order results randomly. I am not an expert in database querying but I guess you could make it more efficient than doing it client side by our own.

_Example of solution_: { orderBy: RANDOM }

**Case sensitive/insensitive querying**
Now, case sensitivity is not managed by Prisma and if we want we can handle it through database collation, but we have do it manually and that's not very convenient (I expect a minimum of consistency from ORM queries, independently of the database I use). I know that Django allows case sensitivity filtering, and that it would be interesting for Prisma, particularly given that full text search is not yet available.

_Example of solution_: { field__icontains: string }

**Regex query argument**
So far I haven't really encountered a need for regex querying but I guess it could be useful (it is available in Django).

_Example of solution_: { field__regex: regex }

**Comment by schickling** [comment]
Thanks a lot for this opening this issue @samy-mnasri and sorry for the big delay in getting back. 

You've touched on a bunch of different topics here:

- Regarding ordering by random please refer to [this feature request issue](https://github.com/prisma/prisma/issues/114).
- Regarding filtering by providing a regex, please open a [new dedicated feature request issue](https://github.com/prisma/prisma/issues/new/choose).
- Regarding case sensitive/insensitive querying, please open a [new dedicated feature request issue](https://github.com/prisma/prisma/issues/new/choose).

**Comment by sapkra** [comment]
@samy-mnasri @theyeshu I create a ticket for case sensitive/insensitive querying. #3611
