### ISSUE TITLE
Subscription data not according to the bindings

### ISSUE THREAD

**Issue by nunovieira** [prisma/prisma#3305]
**Describe the bug**
I found the data of subscription events is not exactly how it's declared on the generated graphql bindings

**To Reproduce**
Clone [this repo](https://github.com/nunovieira/prisma-subscription-type-safety-problem) and follow instructions in the README.md

**Expected behavior**
In that example, the value of the `IteratorResult` (`result.value`) should be of type `UserSubscriptionPayload`. Instead is of some type `{ user: UserSubscriptionPayload }`.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - prisma/1.18.0 (darwin-x64) node-v10.12.0

**Additional context**
This came from a question in [Prisma Forum](https://www.prisma.io/forum/t/how-to-use-subscriptions-with-prisma-binding/4640/8)

**Comment by marktani** [comment]
You are using generating Prisma Client (`typescript-client` generator `prisma generate` command) and `prisma-binding` (`graphql codegen` command). Is this intended?

Also, `graphql get-schema --project database` and the `graphql-schema` generator are redundant.

Are you actually asking about Prisma Client, or `prisma-binding`? I am not clear on this.

**Comment by nunovieira** [comment]
Yes, I know it's redundant. This is just for experimenting. I can clean it up, but I think it doesn't affect the reproduction.

I'm asking about `prisma-binding`. Not sure if Prisma Client is also affected.

**Comment by nunovieira** [comment]
I've updated the dependencies on the [reproduction repo](https://github.com/nunovieira/prisma-subscription-type-safety-problem). The problem still persists.
