### ISSUE TITLE
Sharing DB between 2 Prisma servers: Server requires a cluster secret

### ISSUE THREAD

**Issue by frandiox** [prisma/prisma#3306]
**Describe the bug**
I'm trying to use the same DB with 2 different apps (different Prisma endpoints). If I use the same Prisma server for both of them everything works fine. However, if I try to create a new Prisma server for the second app (basically copying the Dockerfile from the first server, pointing to the same DB), then `prisma deploy` throws: 

```
 ▸    Server at https://.... requires a cluster secret.
 ▸    Please provide it with the env var PRISMA_MANAGEMENT_API_SECRET
```

Note that playground works well, so the only problem is the management API. I'm pretty sure it gets the env var with the correct value since it's just a copy of the first server.

**To Reproduce**
1. Deploy a Prisma server using the offical docker image (1.14) (setup [like this](https://github.com/develomark/prisma-now))
2. Deploy a second Prisma server with the same DB credentials and secret as the first one
3. Try to deploy a schema using the second server

**Expected behavior**
To my understanding, both prisma servers shouldn't need to communicate since they will be operating with different apps/endpoints, so they both should be considered as "main servers" and be able to use the management API (they manage different things 😕 )

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - `prisma` CLI: `prisma/1.4.0 node-v10.7.0`
 - Prisma Server: `1.4.0`
 - Host: Zeit Now v1

**Additional context**

This is likely related to #2850 . Since Prisma cannot be "easily" scaled horizontally, I was thinking in setting up an instance per app in the same DB... but maybe it's not possible? Or just a bug?
Thanks!

**Comment by do4gr** [comment]
Prisma is using a locking mechanism on the database level to determine which Prisma instance is on deploy duty. This will prevent duplicate deploys. 

Since the lock is on db level you would run into this if running two different Prisma instances. Only one of them would be able to hold the lock and do deploy changes. But the Api actions should work for both.

**Comment by frandiox** [comment]
@do4gr 	Thanks for the explanation. I guess the best way would be implementing horizontal scaling to prevent DB locks. The only problem is that horizontal scaling is fairly challenging until [`prisma` and `prisma-prod` are unified](https://github.com/prisma/prisma/issues/2869) and it supports some other [alternatives to RabbitMQ](https://github.com/prisma/prisma/issues/2850). Or until the Rust/standalone version is available 😅 

The `PRISMA_MANAGEMENT_API_SECRET ` issue was addressed in https://github.com/prisma/prisma/issues/4069
