### ISSUE TITLE
Use dotenv-expand instead of dotenv package to allow variable expressions in the env file

### ISSUE THREAD

**Issue by bre7** [prisma/prisma#3310]
## Problem
Allow env var expansion for schema.prisma
Currently on Heroku, I need to add schema to the DB_URL for the connection to work (e.g. `${DATABASE_URL}?ssl=1&schema=whatever`).
Of course, another solution would be to set `datasources` manually on `PrismaClient`.

## Suggested solution

Minor (non breaking) changes required.

1. Add `dotenv-expand` as a dependency

2. Enable expansion

    ```diff
    import dotenv from 'dotenv'
    + import dotenvExpand from 'dotenv-expand'
    
    - const xxx = dotenv.config(...)
    + const xxx = dotenvExpand(dotenv.config(...))
    ```

    on
    * https://github.com/prisma/prisma/blob/master/src/packages/client/src/runtime/getPrismaClient.ts
    * https://github.com/prisma/prisma/blob/master/src/packages/cli/src/bin.ts

## Alternatives

Current solution (workaround):
```js
const client = new PrismaClient({ datasources: { db: { url: `${process.env.DATABASE_URL!}?ssl=1&schema=schema_name` } } })
```

## Additional context
PR: https://github.com/prisma/prisma/pull/3330

**Comment by pantharshit00** [comment]
For context: https://github.com/motdotla/dotenv-expand

**Comment by matthewmueller** [comment]
Hi @bre7

Do you mind explaining why you need this a bit more? From my (very distant!) past using Heroku, I'd probably try to do:

```sh
heroku config:set myapp DATABASE_URL=postgres://user@pass:hostname:5432/dbname?ssl=1&schema=whatever
```

**Comment by bre7** [comment]
The problem is that env vars set by addons and can change at any given time (e.g. https://devcenter.heroku.com/articles/connecting-to-relational-databases-on-heroku-with-java#connecting-to-a-database-remotely)

**Comment by matthewmueller** [comment]
> Note: it is important to add this paramater in code rather than editing the config var directly. Various automated events such as failover can change the config var, and edits there would be lost.

Ah wow, okay, that makes sense!

**Comment by GGA557** [comment]
I can't get the workaround (the mentioned alternative) to work with or without the datasource in the prisma.schema file. How exactly is that workaround supposed to work?

**Comment by Jolg42** [comment]
@GGA557 this is a 4 years old issue, if you need help please [open a discussion here](https://github.com/prisma/prisma/discussions).
