### ISSUE TITLE
Can't deploy services because the name must start with a letter and may contain up to 30 letters

### ISSUE THREAD

**Issue by vctormb** [prisma/prisma#3313]
**Describe the bug**
When I try to deploy the server in a Demo server, it does not allow me to deploy because I get the error message saying:

> how_to-graphql-tutorial_my_database_01 is not a valid name for a service name. It must start with a letter and may contain up to 30 letters, numbers, underscores and hyphens.

**To Reproduce**
1. Access - how to graphql react-apollo [tutorial](https://www.howtographql.com/react-apollo/1-getting-started/)
2. Clone the server with the following command:
`curl https://codeload.github.com/howtographql/react-apollo/tar.gz/starter | tar -xz --strip=1 react-apollo-starter/server`
3. Access the `server` directory. 
4. Run `yarn install`, `yarn dev` (or npm) and `yarn prisma deploy`.
5. Choose the Demo server / US location / and put a name for the server.
6. See error

**Expected behavior**
To deploy the server correctly.

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/13953703/46952356-f58e9480-d060-11e8-9ffb-ee89b5a57b18.png)  

package.json
![image](https://user-images.githubusercontent.com/13953703/46952512-7057af80-d061-11e8-8cca-163846440d14.png)

**Versions (please complete the following information):**
 - OS: Windows 8.1

**Additional context**
Even if I put a valid name it throws the error.

**Comment by marktani** [comment]
Your service name is too long.
Choose a shorter service name (up to 30 characters).

![image](https://user-images.githubusercontent.com/1780597/46952797-3d76e100-d08c-11e8-877c-26521b0a4554.png)

**Comment by vctormb** [comment]
@marktani Still not working. I've tried with this name "how_to-graphql-tutorial_my_d01".

**Comment by marktani** [comment]
Could you try with this name: "test"?

**Comment by marktani** [comment]
Maybe the stage name counts against the length limit as well 🙂

**Comment by vctormb** [comment]
@marktani Still not working with the name "test".

**Comment by marktani** [comment]
Ah, I think it's related to the `.` in your username 😄Could you please sign up with a new account? 🙂

**Comment by vctormb** [comment]
@marktani Ok. I'll do that.
