### ISSUE TITLE
Change type names to match graphqlgen

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3323]
**Is your feature request related to a problem? Please describe.**
Current types generated by client do not play very well with [`graphqlgen`](https://github.com/prisma/graphql-resolver-codegen)

**Describe the solution you'd like**
Rename `User` -> `UserPromise` and `UserNode` -> `User`

This change would make the types fit together more naturally, currently, type inferences makes it work and this change would make the user experience much better.

**Comment by marktani** [comment]
To be clear, you are talking about the types in the TypeScript Prisma Client, not in the Prisma API, correct?

**Comment by divyenduz** [comment]
Yes, that is correct.
