### ISSUE TITLE
Allow adding FULLTEXT index in the schema

### ISSUE THREAD

**Issue by eddeee888** [prisma/prisma#3325]
## Problem
I am trying to implement full text search in MySQL 5.7.30 because I need to search for a term relevance in multiple fields. This is the query I have to run manually:

```mysql
CREATE FULLTEXT INDEX robot_general_search ON Robot(name,description);
```

This allows me to run something like this:

```node
await prisma.queryRaw`SELECT MATCH(r.name,r.description) AGAINST(${searchTerms}) as relevance FROM Robot r`;
```

The above query allows me to get the relevance of the search terms in `name` and `description` fields of the table.

## Suggested solution

Currently, looks like there is only one way to add index in prisma2:

```yml
@@index([name,description], name:robot_general_search)
```

Maybe we could add the type next to the name? e.g.

```yml
@@index([name,description], name:robot_general_search, type: FULLTEXT)
```

## Alternatives

I guess I could keep the custom index for now but it would be nice if it is in the schema

## Additional context

When I try to do `introspect`, `@@index([name,description], name:robot_general_search)` is the index that appears, so in a sense, this is wrong and can cause queries to crash because `MATCH ... AGAINST ...` only works for `FULLTEXT` indexes

**Comment by tr1stan** [comment]
Currently this is a showstopper for us on MySQL in version `2.20.1`.

We've got a Table with a `text` field named `versionData` that has a `FULLTEXT` index applied to it. When we introspect, the schema is generated with an identified `@@index` but assumes the wrong type of index:

![Screenshot 2021-04-12 at 09 28 27](https://user-images.githubusercontent.com/45169274/114396074-07e7db80-9b95-11eb-812d-4d30bd2651d4.png)

The only way to validate the schema file is to remove the `@@index`, but then the drift detection prevents us from generating new migrations because it wants to drop the index.

**Comment by armaserg** [comment]
This is a problem for our project too :(
I have to recreate manually fulltext index after each new migration.

**Comment by danielbasso** [comment]
Same problem here. Took a while to found this issue. And when migrating, it says it will destroy all current data because the schema is not in sync.

**Comment by stnwk** [comment]
Does anyone know of a workaround here?

**Comment by Doubl3** [comment]
You should notify newcomers of this missing (or not there yet) important functionality here in the doc : https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-limitations-issues

**Comment by janpio** [comment]
This is not a limitation of Migrate, but missing functionality. As you can see at https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3Ateam%2Fmigrations+label%3Akind%2Ffeature that list is pretty long and will also forever be pretty long, as while we implement new features in Prisma, users will of course find new additional functionality that we do not support yet and create issues for that.

**Comment by helderjbe** [comment]
This is also happening in Postgres tsvector columns.

It caused me a massive headache to figure out why this was happening, only to realize that I'll have a bigger headache to change everything once again.

> This is not a limitation of Migrate, but missing functionality. As you can see at https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3Ateam%2Fmigrations+label%3Akind%2Ffeature that list is pretty long and will also forever exist, as while we implement new features in Prisma, users will of course find new additional functionality that we do not support yet and create issues for that.
> 
> At the same time we could of course add a link to that exact search for an easier way for people to discover the missing functionality.

With all due respect, this is definitely a limitation at this point. One thing is not having a native feature supported by the Prisma DSL, another is not being supported at all even with the raw version of SQL (and no alternative provided whatsoever).

**Comment by Doubl3** [comment]
> This is not a limitation of Migrate, but missing functionality. As you can see at https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3Ateam%2Fmigrations+label%3Akind%2Ffeature that list is pretty long and will also forever exist, as while we implement new features in Prisma, users will of course find new additional functionality that we do not support yet and create issues for that.
> 
> At the same time we could of course add a link to that exact search for an easier way for people to discover the missing functionality.

@janpio you're right saying a lot of features are still missing but, IMHO, it seems important that this one must be present in such a product as Prisma if you want to compete against other existing libraries.

The Prisma promise is to help keeping the model in sync with the database & ease its developer usage.
It's pretty common to use full text indexes in today's databases. In the Prisma model/migration tool, the lack of handling this kind of index makes drift the model against the database and impacts a lot of people wanting to go for Prisma.

Maybe the Prisma backlog priority for this missing feature could be set higher ?
A poll on a Prisma Slack channel may help determine that priority ?

As for me, if it could help others, as a workaround I chose to apply this workflow:
> Generate the model from the database (one shot introspection)

1. modify the model
2. generate the migration SQL
3. modify the SQL
4. apply the migration from the SQL (both in dev & production env.)

> never introspect the database again (since the model is commited along with the source code, the model could remain the only source of truth)

Each time a full text search index must be added, I must remind me somewhere else that the index has to be added to the new migration SQL file.

**Comment by do4gr** [comment]
We spelled out a round of index capability additions for the PSL including the addition of FullText indexes. We'd love to get some feedback: https://github.com/prisma/prisma/issues/3387

**Comment by do4gr** [comment]
Since 3.8 the ability to use full text indices and searching them on MySql is now in preview. Please check it out and let us know if there are still capabilities missing for you! Thanks for your patience. 

https://github.com/prisma/prisma/releases/tag/3.8.0

**Comment by floelhoeffel** [comment]
Hello everyone 👋

We are starting design work to improve Prisma's support for **Full Text Search (FTS)**!

If you would like to help, please help us learn about your needs via a short [FTS user research survey](https://prisma103696.typeform.com/fts-survey).

Thank you!

**Comment by janpio** [comment]
As this is [available in preview](https://github.com/prisma/prisma/issues/3325#issuecomment-1019928021) and seems to be working fine for MySQL, I am closing this issue already.
