### ISSUE TITLE
How to reset DB

### ISSUE THREAD

**Issue by steida** [prisma/prisma#3331]
`Applying changes (17/11) ⣾` ... without any progress.

`prisma reset` does not help.

```
docker-compose kill
docker-compose down
docker-compose up -d
```

docker-compose kill etc. does not help either.

What am I doing wrong? To be honest, I am not sure what am I reseting if DB with some tables is still there.

**Comment by ewnd9** [comment]
Try

```sh
$ docker-compose down -v
```

`-v` flag is used to remove volumes

**Comment by steida** [comment]
@ewnd9 My workaround is to remove all types except one, then deploy with force, then put the rest of the model back.

**Comment by mavilein** [comment]
@steida : `prisma reset` only wipes the data and keeps the schema. If you want to also delete the schema, just run `prisma delete` to get rid of the whole service.

**Comment by rootandleaves** [comment]
is there any way to reset only given table instead ```prisma reset``` which resets whole db
