### ISSUE TITLE
Adjust log level in prisma container?

### ISSUE THREAD

**Issue by beeplin** [prisma/prisma#3332]
# Feature Request

**What feature are you missing?**

Now the prisma docker container only logs database `update` operations. Is it possible to see more logs like `select` etc? It is vital in production to locate performance bottlenecks.

**How could this feature look like in detail? Tradeoffs?**

It would be nice to have an option like `logLevel` in the `PRISMA_CONFIG` env to let user tune what to be logged.

**Comment by pantharshit00** [comment]
See https://github.com/prisma/prisma/issues/2833#issuecomment-487035981
