### ISSUE TITLE
Many-Many relations with self relation: New connection doesn't show up for both sides

### ISSUE THREAD

**Issue by JCHHeilmann** [prisma/prisma#3335]
**Describe the bug**
I'm having the same issue filed and fixed before [here](https://github.com/prisma/prisma/issues/2229#issue-315171308) in the current version of prisma (1.18.1). When connecting users via the `FriendRequest` relation the new connection shows up for both users. But when adding a connection to `friends` it only appears for one user.

**To Reproduce**
The `User` type:
```
type User {
  id: ID! @unique
  name: String!
  friendRequestsReceived: [User!]! @relation(name: "FriendRequests")
  friendRequestsSend: [User!]! @relation(name: "FriendRequests")
  friends: [User!]! @relation(name: "Friends")
}
```

I start with two users:
```
{
  "data": {
    "users": [
      {
        "id": "cjn7uuxtm000i08231zkcsse8",
        "name": "Bob",
        "friends": []
      },
      {
        "id": "cjndl2dsg000k0823vgbkimns",
        "name": "Franz",
        "friends": []
      }
    ]
  }
}
```

I want to make them friends:
```
mutation {
  updateUser(
    data: { friends: { connect: { id: "cjndmc388002008238xgtyg3e" } } }
    where: { id: "cjndl2dsg000k0823vgbkimns" }
  ) {
    name
    friends {
      name
    }
  }
}
```
But the connection only shows up in one direction. So Bob gets added to Franz' friend list, but not the other way around:
```
{
  "data": {
    "users": [
      {
        "id": "cjn7uuxtm000i08231zkcsse8",
        "name": "Bob",
        "friends": []
      },
      {
        "id": "cjndl2dsg000k0823vgbkimns",
        "name": "Franz",
        "friends": [
          {
            "name": "Bob"
          }
        ]
      }
    ]
  }
}
```

**Expected behavior**
I would expect Franz to also show up in Bob's friend list.

**Versions:**
 - OS: `OS X High Sierra`
 - `prisma` CLI: prisma 1.18.1
 - Prisma Server: 1.18

Am I doing something wrong, or did this issue come back? 😅

**Comment by marktani** [comment]
This is the expected behaviour, as we're dealing with a single-field self-relation.
For this specific case, you need to set the relation from both sides.

You can read more about this here: https://github.com/prisma/prisma/pull/2515.
