### ISSUE TITLE
Update denylist in engines and client

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#3338]
After the client / dmmf refactoring it looks like we should update the denylist with at least these values below (I probably missed some, do you have an updated list maybe in engines?)

I think some values also got removed from what I could see (not 100% sure)
```
      'QueryMode',
      'BoolFilter',
      'StringNullableFilter',
      'NestedDateTimeFilter',
      'NestedStringNullableFilter',
      'NestedStringFilter',
      'NestedBoolFilter',
      'JsonNullableFilter',
      'NestedJsonNullableFilter',
      'InputJsonValue',
```

Current Client List: https://github.com/prisma/prisma/blob/master/src/packages/client/src/generation/generateClient.ts
Current Engines List: https://github.com/prisma/prisma-engines/blob/master/libs/datamodel/core/src/transform/ast_to_dml/reserved_model_names.rs

**Comment by mavilein** [comment]
The PR on the engines side is ready. I wrote a test and found more reserved words that need to be added: https://github.com/prisma/prisma-engines/pull/1051/files#diff-8f940de32ad7770433016f60cec6d0aeR74-R96
