### ISSUE TITLE
Heroku hosted deploy: Update or delete on table "<table name>" violates foreign key constraint

### ISSUE THREAD

**Issue by jamwil** [prisma/prisma#3340]
deleteNode results in an internal server error being returned. Analysis of Heroku logs provides this error message:

```
2018-10-18T22:32:28.910663+00:00 app[web.1]: org.postgresql.util.PSQLException: ERROR: update or delete on table "Trade" violates foreign key constraint "Trade_vendor_nodeId_fkey" on table "Trade_vendor"
2018-10-18T22:32:28.910665+00:00 app[web.1]:   Detail: Key (id)=(cjnf3t9tw000a09127j58d8p8) is still referenced from table "Trade_vendor".
```

- "Trade" is the name of a node
- "vendor" is a field of type [String!]!

This error seems to only be triggered by list-type fields. The Delete Node button from the Data Browser in the cloud console is non-responsive.

GraphQL Mutation:
```
mutation {
  deleteTrade(where: {id: "cjnf3t9tw000a09127j58d8p8"}) {
    id
  }
}
```

Versions:
 - OS: N/A Heroku
 - Prisma CLI: prisma/1.18.1 (windows-x64) node-v9.4.0
 - Prisma Server: 1.11-beta

**Comment by marktani** [comment]
Can you reproduce this error on a recent version?
You can read how to upgrade your instance on Heroku [here](https://github.com/prisma/prisma-cloud-feedback/issues/202#issuecomment-414095090).

Also, kindly share _how_ you can reproduce this, in all of my projects all `deleteX` mutations work without a problem.

**Comment by marktani** [comment]
This might be related to scalar lists, did you rename `vendor` or did other migrations to that field before that error came up?

**Comment by jamwil** [comment]
Thank-you for pointing me to those upgrade instructions @marktani! I started with a fresh Heroku server and performed the upgrade to 1.19 prior to populating with data. Everything appears to function normally using the same datamodel, so either I screwed something up last time or the issue was resolved in a subsequent update.
