### ISSUE TITLE
Preview feature feedback: `insensitiveFilters`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3340]
Please share your feedback about the preview feature `insensitiveFilters` that was released in [v2.5.0](https://github.com/prisma/prisma/releases/tag/2.5.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo. 
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma2`](https://app.slack.com/client/T0MQBS8JG/CKQTGR6T0) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by timleslie** [comment]
This feature is working exactly how I would want it to, thanks! 🙏

**Comment by dpetrick** [comment]
@saraveti The reason it's only on postgres is that there's no reason to implement it on MySQL-based databases - they're already case insensitive by default in the vast majority of use cases.

**Comment by saraveti** [comment]
> @saraveti The reason it's only on postgres is that there's no reason to implement it on MySQL-based databases - they're already case insensitive by default in the vast majority of use cases.

@dpetrick . Thanks for providing the response. I did verify the case insensitive search with Prisma & MariaDB. Its working. Thanks again.

**Comment by heibel** [comment]
This works perfect! Am using it with `nexus`.
```ts
...
where: {
  OR: [
    { name: { contains: "{keyword}", mode: QueryMode.Insensitive } },
    { city: { contains: "{keyword}", mode: QueryMode.Insensitive } },
  ],
},
```

**Comment by nikolasburk** [comment]
Thank you so much for the feedback everyone! 

Thanks to this, we were able to promote case insensitive filters to stable in today's release 🥳

**Comment by Noitidart** [comment]
Is this possible with json filter?

```
    prisma.subscription.findMany({
      where: {
        attrs: {
          path: ['customer', 'email'],
          equals: email,
          mode: 'insensitive'
        }
```
