### ISSUE TITLE
-bash: /usr/local/bin/prisma: Permission denied

### ISSUE THREAD

**Issue by ducdev** [prisma/prisma#3342]
**Describe the bug**
-bash: /usr/local/bin/prisma: Permission denied

**To Reproduce**
brew tap prisma/prisma
brew install prisma

**Expected behavior**
prisma installed with homebrew should run as well as installed with npm

**Screenshots**
![image](https://user-images.githubusercontent.com/3524016/47236816-72c25c80-d407-11e8-9926-55089504a971.png)

**Versions (please complete the following information):**
 - OS: MacOS Mojave 10.14

**Comment by divyenduz** [comment]
Can you do `chmod +x /usr/local/bin/prisma` and then try to run the command? I am not able to reproduce it.

**Comment by midgethoen** [comment]
same issue for me

**Comment by midgethoen** [comment]
> Can you do chmod +x /usr/local/bin/prisma and then try to run the command? I am not able to reproduce it.

```bash
➜  prisma-test prisma
zsh: permission denied: prisma
➜  prisma-test chmod +x /usr/local/bin/prisma
➜  prisma-test prisma
zsh: exec format error: prisma
```

**Comment by midgethoen** [comment]
> Can you do chmod +x /usr/local/bin/prisma and then try to run the command? I am not able to reproduce it.

```bash
➜  prisma-test prisma
zsh: permission denied: prisma
➜  prisma-test chmod +x /usr/local/bin/prisma
➜  prisma-test prisma
zsh: exec format error: prisma
```

**Comment by midgethoen** [comment]
same issue for me...

> Can you do chmod +x /usr/local/bin/prisma and then try to run the command? I am not able to reproduce it.

```bash
➜  prisma-test prisma
zsh: permission denied: prisma
➜  prisma-test chmod +x /usr/local/bin/prisma
➜  prisma-test prisma
zsh: exec format error: prisma
```

**Comment by midgethoen** [comment]
im having the same issue

chmod also doesn't do the trick for me

```bash
➜  prisma-test prisma
zsh: permission denied: prisma
➜  prisma-test chmod +x /usr/local/bin/prisma
➜  prisma-test prisma
zsh: exec format error: prisma
```

```bash
➜  bin cat prisma
 �Om7��7��'(%
```

(additionally im having issues with posting on GitHub, so excuse me if im posting  doubly)

**Comment by echonox** [comment]
> Can you do `chmod +x /usr/local/bin/prisma` and then try to run the command? I am not able to reproduce it.

jack$ prisma
-bash: /usr/local/bin/prisma: Permission denied
jack$ chmod +x /usr/local/bin/prisma
jack$ prisma
-bash: /usr/local/bin/prisma: cannot execute binary file

**Comment by midgethoen** [comment]
fyi  installing via npm did work for me

**Comment by ducdev** [comment]
> fyi installing via npm did work for me

That's what I was saying on top.

**Comment by echonox** [comment]
npm worked for me too

**Comment by sjortiz** [comment]
he said the issue If we brew, the npm one works, and this issue is about the brew installation working properly.

**Comment by ducdev** [comment]
Yes I know the one from `npm` works but I prefer installing it from `brew`, like `yarn`.

**Comment by haysclark** [comment]
Yeah, I am having the same issue with OSX 10.13.6 (High Sierra).  

```
~/infinitedescent/prisma
☺  brew install prisma
==> Installing prisma from prisma/prisma
==> Downloading https://s3-eu-west-1.amazonaws.com/homebrew-prisma/prisma-1.18.0.tar.gz
Already downloaded: /Users/hays/Library/Caches/Homebrew/downloads/fd62b6dbd245b0e984d6e1e53b939e621f4422f6fb1181bb5cae1521678c3d77--prisma-1.18.0.tar.gz
🍺  /usr/local/Cellar/prisma/1.18.0: 3 files, 1.3KB, built in 5 seconds

~/infinitedescent/prisma
☺  which prisma
prisma not found

~/infinitedescent/prisma
☹  ls -la /usr/local/bin/prisma
lrwxr-xr-x  1 hays  admin  34 Oct 23 12:26 /usr/local/bin/prisma -> ../Cellar/prisma/1.18.0/bin/prisma

~/infinitedescent/prisma
☺  ls -la /usr/local/bin/../Cellar/prisma/1.18.0/bin/prisma
-r--r--r--  1 hays  admin  45 Oct 15 04:29 /usr/local/bin/../Cellar/prisma/1.18.0/bin/prisma
```

The issue seems to be that the _prisma_ executable has only read permissions, not execute.  Here are my permissions for something like _heroku_, just as an example.

```
☺  ls -la /usr/local/bin/../Cellar/heroku/7.16.1/bin/heroku
lrwxr-xr-x  1 hays  admin  21 Oct  2 15:08 /usr/local/bin/../Cellar/heroku/7.16.1/bin/heroku -> ../libexec/bin/heroku
```

WIll use NPM for now. :D

**Comment by divyenduz** [comment]
Please try the following steps and see if that works. 

```
brew untap prisma/prisma
brew uninstall prisma
brew tap prisma/prisma
brew install prisma
```

Thanks!

**Comment by ducdev** [comment]
Somehow the issue is gone after I reinstalled Homebrew and things, that's weird. I will close the issue now but anyone still concerns should re-open it.
