### ISSUE TITLE
Re-Introspection does not output list of fields that `cuid()` was applied to

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3343]
![image](https://user-images.githubusercontent.com/15246526/90569778-4ee71380-e163-11ea-867d-32514e4b9bce.png)

_Originally posted by @alan345 in https://github.com/prisma/upgrade/issues/59#issuecomment-675741019_

**Comment by pantharshit00** [comment]
@janpio Isn't this more of an improvement? I can confirm it though that it doesn't output the list of fields.

**Comment by janpio** [comment]
As the output says "These id fields ..." and then does not list any (and this was actually planned to be implemented with all warnings), I consider this a bug.

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/92024670-1a3aa500-ed7c-11ea-872f-be048284253a.png)

This has been fixed in 2.6
