### ISSUE TITLE
Unique constraint violation without entry in DB (email field)

### ISSUE THREAD

**Issue by vctormb** [prisma/prisma#3344]
**Describe the bug**
I'm receiving the error:  ``GraphQL error: A unique constraint would be violated on User. Details: Field name = email`` even though given email address doesn’t exist in database.  

Yes, it's the same problem as this one: [Unique constraint violation without entry in DB](https://www.prisma.io/forum/t/unique-constraint-violation-without-entry-in-db/2067)

**To Reproduce**
I'm following the [Get Started](https://www.prisma.io/docs/get-started/03-build-graphql-servers-with-prisma-e001/#define-graphql-api) from Prisma documentation.

**Expected behavior**
To not receive the error when the email does not exist in the DB.

**Screenshots**  
``datamodel.prisma``
![image](https://user-images.githubusercontent.com/13953703/47276360-e04bc580-d58c-11e8-856d-7048abe9358f.png)
``resolver``
![image](https://user-images.githubusercontent.com/13953703/47276328-b6929e80-d58c-11e8-863b-076ce19585e0.png)
``package.json``
![image](https://user-images.githubusercontent.com/13953703/47276412-26088e00-d58d-11e8-8db3-0404f56f6ccf.png)

**Comment by marktani** [comment]
This is very likely caused by #3210.

**Comment by vctormb** [comment]
@marktani Interesting, it worked! Why?
Another courious thing that I've noticed is that if I only use ``async`` without ``await`` it works too! Why?
Is the ``context.prisma.createUser()`` already resolving the promise for me?

**Comment by marktani** [comment]
Not exactly sure why this happens, but you can follow #3210 to learn more.
