### ISSUE TITLE
Invalid JS schema for required relation, when reverse relation is a required array is wrong

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3352]
**Describe the bug**
Prisma generate uses `prisma-generate-schema` internally to create a schema for a given datamodel without a live endpoint. This JS based schema generator is not working correctly for this specific datamodel file:-

```graphql
type User {
  id: ID! @unique
  licenses: [License!]!
}

type License {
  id: ID! @unique
  user: User!
}

```

**To Reproduce**
1. Setup a project with Prisma init
2. Update datamodel to match the above one
3. Run `prisma generate`

This generates various deviations as well as an empty input type, in this specific case `LicenseCreateWithoutUserInput` is generated empty (since the relation is required) and should not be generated at all. 

**Expected behavior**
The generated schema from JS schema generator should match the schema generated by Prisma. 

**Versions (please complete the following information):**
 - `prisma` CLI: `prisma/1.20.0-alpha.33 (darwin-x64) node-v10.4.0`
 - Prisma Server: `1.18`

**Additional context**
Current workaround is to use `prisma generate --endpoint` which by passes the JS schema generator and uses a live endpoint (spec https://github.com/prisma/prisma/issues/3184) to generate the client.

**Comment by ejoebstl** [comment]
Fixed by 81f0bac840ecf5d96d81d74bf7f030da048e0060.
