### ISSUE TITLE
`count` throws an error if `include` is specified

### ISSUE THREAD

**Issue by queicherius** [prisma/prisma#3360]
## Bug description

`prisma.model.count(args)` causes an error if `args` includes `include` (e.g. `{ include: { relationship: true } }`):

> Please either use `include` or `select`, but not both at the same time.

## Expected behavior

I'd expect it to either silently ignore the `include` parameter, or throw a TS type error if `include` is defined.

It caught me off-guard, because I pass the same `args` parameter to `findMany` and `count` (like [in this example with baseArgs](https://github.com/devoxa/prisma-relay-cursor-connection#usage))

## Prisma information

It used to work as expected with Prisma 2.0.1, it does no longer work as expected with Prisma 2.4.0.

**Comment by pantharshit00** [comment]
I can confirm this bug in `2.6.0-dev.44`. Thanks for reporting.

**Comment by matthewmueller** [comment]
Note: This is quite an old issue and might not be a problem anymore.

**Comment by millsp** [comment]
This is fixed in the latest version.
