### ISSUE TITLE
Desired behaviour when a given cursor does not exist

### ISSUE THREAD

**Issue by nayaabkhan** [prisma/prisma#3362]
Hello! 👋 I have a question on the usage of `cursor` based pagination.

### Context

We are using cursor-based pagination on a table where it may be possible to delete data. And this data is quite real-time in nature. So, there is a possibility that the cursor we have at hand might be pointing to a now non-existent record.

We are using Prisma with Nexus with `t.connection` to implement cursor-based pagination on the GraphQL side.

### Question and suggested policy

In the given situation, the cursor returns nothing, and pagination stops even though there are more records in the list. Wouldn't it be a more robust policy to take the next available record in such cases?

For now, we've decided not to remove any records and mark them deleted using a timestamp field. Although, there may be use-cases where this workaround is not acceptable for others.

**Comment by pantharshit00** [comment]
This will be a breaking change now so I don't think behaviour should be altered here. If you rather consider this a bug, please open a bug report: https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml
