### ISSUE TITLE
Prisma Client 1.19 and Subscription big problem

### ISSUE THREAD

**Issue by doums** [prisma/prisma#3368]
**Describe the bug**
I really think there is a big problem with prisma client and subscription:
First problem, I notice there is actually no way to return directly the full subscription payload like
```
type PostSubscriptionPayload {
  mutation: MutationType!
  node: Post
  updatedFields: [String!]
  previousValues: PostPreviousValues
}
```
from a subscription like
```
type Subscription {
  posts: PostSubscriptionPayload
}
```
and the resolver
  ```
posts: {
    subscribe: async (parent, args, ctx) => {
      return ctx.prisma.$subscribe.post()
    },
    resolve: payload => {
      console.log(payload) // { mutation: 'CREATE', updatedFields: null }
      return payload
    }
  }
```
In the `resolve` function I get only mutation and updatedFields fields, whatever is the event that trigger the subscription (create, update or delete).

Second problem, and this is a big one because it concerns the DELETE subscription directly. We can't get back the previous value of the deleted node at all!
```
type Subscription {
  deletedPost: PostPreviousValues! // I tested with Post! too, same error
}
```
I get `null`

Note that I console log the payload in the `resolve` function of each subscription resolver like
```
  deletedPost: {
    subscribe: async (parent, args, ctx) => {
      return ctx.prisma.$subscribe.post({ mutation_in: ['DELETED'] }).previousValues()
    },
    resolve: payload => {
      console.log(payload) // null
      return payload
    }
  }
```
So I'm pretty sure the problem comes from prisma Client :zany_face:

```
generate:
- generator: javascript-client
  output: ../src/generated/prisma-client/
- generator: graphql-schema
  output: ../src/generated/
```

**Versions (please complete the following information):**
 - OS: Archlinux
 - `prisma` CLI: 1.19
 - "graphql": "^0.13.2",
 - "graphql-yoga": "^1.16.7",
 - "prisma-client-lib": "^1.19.0"

**Comment by chanlito** [comment]
@doums I'm facing the same issue, using `typescript-client`.

**Comment by ysantalla** [comment]
@doums I have the same insue!!!

**Comment by chanlito** [comment]
I'm using `prisma-binding` as a workaround for this issue FYI.

**Comment by pantharshit00** [comment]
Hi all,

Just noticed this issue. This problem can be easily be solved by using `$fragement` like so:

```js
posts: {
  subscribe: async (parent, args, ctx) => {
    return ctx.prisma.$subscribe.post().$fragment(`
 		fragment EnsurePostFields on Post {
			id
			title
			author
		}
 	  `);
  },
  resolve: payload => {
    console.log(payload.node) // { id: 'xxxx', title: 'xxx', author: { // ... } }
    return payload
  }
}
```
