### ISSUE TITLE
Support BigInt as a data type

### ISSUE THREAD

**Issue by ellipticaldoor** [prisma/prisma#3370]
**Describe the bug**
I can't have big int with current prisma 1.19

**To Reproduce**
Edit your datamodel.prisma to add this type
``` graphql
type User {
	id: ID! @unique
	count: Long
}
```

Run
``` shell
prisma deploy
```
Then you get the error
```
The field `count` has the type `Long` but there's no type or enum declaration with that name.
```

**Expected behavior**
I can have a number bigger than 2147483647

**Versions (please complete the following information):**
 - OS: OS X High Sierra
 - `prisma` CLI: 1.19.0
 - Prisma Server: 1.19

**Comment by marktani** [comment]
Have you tried to use `Float`?

Could you please describe your exact use case here: https://github.com/prisma/prisma/issues/1753? We are looking into supporting native database types but have yet to formally spec it out.

**Comment by ellipticaldoor** [comment]
So it's not there yet!

I thought I was doing something wrong.

Yes!! It works with **Float** 🙂you saved me 😂

I will explain my use on the thread.
