### ISSUE TITLE
Way to create multiply mutations with relations in it

### ISSUE THREAD

**Issue by katemicse** [prisma/prisma#3371]
for example i have:
```
type Good {
  id: ID! @unique
  order: Order!
}
type Order {
  id: ID! @unique
  goods: [Good!]!
}
```

 it would be nice to create the order with good, and perform it in one action

For now the way to do it is: 1- create the order, 2- then create the goods with the id of order in `order` field. 3 - update the order with array of ids of created goods

**Comment by ellipticaldoor** [comment]
Maybe this is what you are looking for?

``` graphql
mutation {
  createOrder(
    data: {
      goods: { create: [{}, {}, {}] }
    }
  ) {
    id
    goods {
      id
    }
  }
}
```
The **order** field since its required inside the **Good** will be populated with the order that you are creating.

**Comment by marktani** [comment]
That's a great suggestion, you can read more about nested mutations here: https://www.prisma.io/docs/prisma-graphql-api/reference/mutations-qwe2/#nested-mutations.
