### ISSUE TITLE
Unable to run 'prisma playground' cmd. Invalid property 'generate'.

### ISSUE THREAD

**Issue by vctormb** [prisma/prisma#3377]
**Describe the bug**
When I try to run ``prisma deploy`` in the folder that has the ``prisma.yml``, an error is shown:  

> prisma.yml should NOT have additional properties. additionalProperty: generate

If I remove the ``generate`` property, it works fine.

**To Reproduce**
1. Run ``prisma playground`` inside the folder that contains the ``prisma.yml``

**Expected behavior**
To execute the prisma playground.

**Screenshots**
``prisma.yml``
![image](https://user-images.githubusercontent.com/13953703/47536292-a3861400-d895-11e8-8f9c-d68adda149d3.png)

``error in the terminal``
![image](https://user-images.githubusercontent.com/13953703/47536260-80f3fb00-d895-11e8-9254-4a9e3d9b9b3d.png)

**Versions (please complete the following information):**
- "node": "v8.12.0"
- "prisma: "1.19.0"
- "prisma-client-lib": "^0.2.59"

**Comment by marktani** [comment]
What's the version of your Playground? I assume it's the Electron app?

**Comment by vctormb** [comment]
That's my ``package.json``

![image](https://user-images.githubusercontent.com/13953703/47606921-2f13b800-d9f0-11e8-9bc3-8105d4b40393.png)
