### ISSUE TITLE
Permission denied for relation Project

### ISSUE THREAD

**Issue by bmik7216** [prisma/prisma#3379]
**Describe the bug**
When trying to run prisma deploy, the error log shows "permission denied for relation Project" in the docker logs

**To Reproduce**
Setup the docker-compose to heroku postgres.
docker-compose up -d
prisma deploy

**Expected behavior**
Allow me to deploy succesfully.

**Screenshots**

**Versions (please complete the following information):**
 - OS: mojave
 - `prisma` CLI: [e.g. `prisma/1.19.0 (darwin-x64) node-v8.12.0`]
 - Prisma Server: `1.9.0`

**Additional context**
Trying to connect to an existing postgresql database

**Comment by marktani** [comment]
Either use CLI version `1.9.x` or server version `1.19.x`.

**Comment by bmik7216** [comment]
Hello @marktani appreciate the quick response.

prisma -v returns

prisma/1.19.0 (darwin-x64) node-v8.12.0

And my prisma image is:

image: prismagraphql/prisma:1.19-heroku

Is this correct?
