### ISSUE TITLE
 Syntax Error: Expected Name, found } when prisma deploy

### ISSUE THREAD

**Issue by Tauri28** [prisma/prisma#3382]
datamodel.prisma:
```
interface Object{
	id: ID! @unique
	created: Int!
}

type User implements Object{
	name: String!
}

type Station implements Object{
	units: [Unit!]! @relation(name: "StationUnits", onDelete: SET_NULL)
}

type Unit implements Object{
	station: Station @relation(name: "StationUnits", onDelete: SET_NULL)
}
```

```
prisma deploy
post-deploy:

Generating schema... 15ms
 !    Syntax Error: Expected Name, found }
```
No errors about missing fields required by interfaces.
Can be fixed by adding field "test: String" to Station and Unit types.

prisma/1.19.0 (windows-x64) node-v9.10.1
graphql 0.13.2

**Comment by leedan77** [comment]
Same problem with
prisma/1.19.0
graphql 0.13.2

**Comment by divyenduz** [comment]
Can you please try to run `prisma generate --endpoint` to generate the schema. Please make sure that the service is live. For context: https://github.com/prisma/prisma/issues/3184

**Comment by schickling** [comment]
Closing in favor of #3407
