### ISSUE TITLE
Allow string/variable interpolation in PSL

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#3382]
Right now there is no templating support in PSL so you can't combine environment variables to form a connection string. 

This feature is useful when you have many database parameters and you want to manage them separately. 

An example implementation can look like:
```prisma
datasource db {
  uri = "postgresql://${env('USER'):${env('PASSWORD')}@yourhost.com/${env('DB')}?sslidentity=${env('SSL_IDENTITY')}"
}
```

**Comment by albertoperdomo** [comment]
This is being tracked at #2559.

**Comment by albertoperdomo** [comment]
Seems there is potentially a new workaround available now. See https://github.com/prisma/prisma/issues/2559#issuecomment-691299199.
