### ISSUE TITLE
go client does not retrieve enum fields

### ISSUE THREAD

**Issue by gregwebs** [prisma/prisma#3385]
**Describe the bug**
The go client supports enums in every way for writing queries, including inserting data. However, it does not return them from the database!

**To Reproduce**

```
enum Letter {
  A
  B
}
type Data {
  id: ID! @unique
  createdAt: DateTime!
  letter: Letter!
}
```

**Expected behavior**
in go, I should see `type Data struct{...}` include `Letter`, but it does no.

**Comment by dominikh** [comment]
Working on it.
