### ISSUE TITLE
One-sided n:m relations 

### ISSUE THREAD

**Issue by phryneas** [prisma/prisma#3385]
In Prisma 1, it was possible to have something like
```
type Translation {
    id: ID! @id
    value: String!
    language: Language!
}
type Post {
    id: ID! @id @unique
    title: [Translation] @relation(name: "PostTitle")
    content: [Translation] @relation(name: "PostContent")
}
```

if I try something similar with the new prisma2 schema, I am getting 

> error: Error validating model "Post": Named relations require an opposite field..

This is what I've tried:

```

model Translation {
    id String @default(cuid()) @id
    value String
    language String
}

model Post {
    id String @id @default(cuid())
    title Translation[] @relation(name: "PostTitle")
    content Translation[] @relation(name: "PostContent")
}
```

It does work when I add oppsite relationships:

```

model Translation {
    id String @default(cuid()) @id
    value String
    language String

    ignore1 Post[] @relation("PostTitle")
    ignore2 Post[] @relation("PostContent")
}

model Post {
    id String @id @default(cuid())
    title Translation[] @relation(name: "PostTitle")
    content Translation[] @relation(name: "PostContent")
}
```

But honestly, I'm not interested in those. Those will just clutter my data model and add methods I do not want to use to my client. Is there any way to avoid that? (Or will it be before prisma2 goes final?)

**Comment by DregondRahl** [comment]
I'm facing a similar issue, where almost every table has a  createdby/updatedby column. Updating the users table with alias's is becoming a bit of a challenge.  Has there been any update on this possibility ?

**Comment by Simonwep** [comment]
Any updates on this one? Is this planned to be implemented?

**Comment by LazerJesus** [comment]
would be valuable

**Comment by cjmyles** [comment]
> https://prisma.slack.com/archives/CKQTGR6T0/p1569787125234100?thread_ts=1569769694.226900&cid=CKQTGR6T0

I can't access this as my email address is not recognised in the Prisma Slack space

**Comment by phryneas** [comment]
Prisma 1 is dead, this will never happen and I'm tired that I'm receiving notifications about this, so I'm closing this issue.
