### ISSUE TITLE
Prisma console breaks when in smaller browser windows

### ISSUE THREAD

**Issue by tienpham94** [prisma/prisma#3389]
**Describe the bug**
Prisma console breaks when in smaller browser windows

**To Reproduce**
1. Go to Prisma console '/services'
2. The layout of the services table breaks, it should at least be horizontally scrollable

**Expected behavior**
The layout of the services breaks, it should at least be scrollable
Fixing: Possible to use `overflow-x: scroll;` for the page (I tested quickly on Chrome devtool and it works, or make the table columns react to viewport size change

**Screenshots**
![image](https://user-images.githubusercontent.com/25751050/47619227-2355ed80-dae5-11e8-8150-98e238056d64.png)

**Versions (please complete the following information):**
 - OS: `OS X Mojave` 
 - `prisma` console

**Comment by Huvik** [comment]
@tienpham94 Can you please create an issue here https://github.com/prisma/prisma-cloud-feedback? Thx!

**Comment by tienpham94** [comment]
Done!
