### ISSUE TITLE
Support read replicas for Postgres & MySQL

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#3389]
We need to do some spec work in order to support this issue https://github.com/prisma/prisma2/issues/172

**Comment by LoriKarikari** [comment]
I've set up a HA PostgreSQL cluster with [Patroni](https://github.com/zalando/patroni). It has one main node with read/write and two read-only replica nodes (these can be scaled out). I've added a load balancer in front of the cluster with two ports. One that points to the main node and one to the replicas. I would love something [ as shown in this other issue](https://github.com/prisma/prisma/issues/172#issuecomment-512195524).

**Comment by albertoperdomo** [comment]
Closed in favor of https://github.com/prisma/prisma/issues/172
