### ISSUE TITLE
Expand @relation configuration to avoid having to describe relationships bi-directionally

### ISSUE THREAD

**Issue by ctrlplusb** [prisma/prisma#3393]
Related discussion: https://prisma.slack.com/archives/CKQTGR6T0/p1576231954347900

**Problem**

There are cases in my schema where I may reuse a model quite extensively across various other models. Typically the reused model will be quite utility in nature, and specifically does not need to have any knowledge of the other models that are "consuming" it.

Here is an arbitrary example:

```groovy
model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(false)
  title     String
  content   String?
  category  Category
  hero      Image? @relation("Hero")
  thumbnail Image? @relation("Thumbnail")
}

model Category {
  id    String @default(cuid()) @id
  name  String
  posts Post[]
  thumbnail Image?
}

model Image {
  id String @default(cuid()) @id
  url String
}
```

Note how `Image` is being reused across `Category` and `Post`.  There is no need for `Image` to know about the models that are utilising it.

However, the above schema will not compile. It produces the following error:

```
Error: Schema parsing
error: Error validating model "Post": Automatic related field generation would cause a naming conflict. Please add an explicit opposite relation field..
  -->  schema.prisma:19
   |
18 |   hero      Image? @relation("Hero")
19 |   thumbnail Image? @relation("Thumbnail")
20 | }
   |
Command failed with exit code 1: node_modules/.bin/prisma2 generate
```

The error message seems to suggest that I would need to perform a bidirectional mapping, adding `Post` to `Image`.  

I don't want to do this. 

**Example**

I have created the following CodeSandbox example showing this error. Note the terminal panel at the bottom right for the error:

https://codesandbox.io/s/charming-leftpad-cqphj

**Proposal**

It would be great if there was an additional mechanism by which we could declare the ownership of a relation, and thereby help the compiler avoid getting into these circumstances.

For example:

```groovy
model Post {
  // ... other fields
  hero      Image? @relation(name: "Hero", owner: true)
  thumbnail Image? @relation(name: "Thumbnail", owner: true)
}
```

Note the **`owner: true`**. I feel like specifying this the compiler would know for sure it would need to bake the foreign key into the respective table for the `Post` model.

I would then expect two fields on the `Post` table: `hero` and `thumbnail` to match the field name in the model. I expect that the @meta helper could be used to rename this, or an additional configuration be added to @relation allowing the definition of the table field name.

**Comment by tizot** [comment]
Hi! 

I am hitting the same issue:
```groovy
model User {
  id: String @id
}

model Content {
  createdBy: User   @relation(fields: [creatorId], references: [id])
  creatorId: String
  updatedBy: User   @relation(fields: [updaterId], references: [id])
  updaterId: String
}
```

I really don't care about the inverse relations in my application, but if I don't add fields of type `Content[]` with named `@relation` in `User`, the schema does not compile. This is a bit cumbersome and it adds noise in the schema... 😕 
It does not seem to me that the schema above is ambiguous. It would be if I had added back-relations without naming them (like in the example of the documentation).

I am quite new to Prisma, and maybe I am missing something here, but I feel that if we need a back-relations, we should state it explicitly (e.g. by specifying the corresponding field name in `@relation()`, or using a named relation).

**Comment by mohsin51** [comment]
+1

**Comment by pantharshit00** [comment]
`prisma format` will automatically expand relations now and create back relation and it is also available via the prisma extension. I think this discussion is outdated now.
