### ISSUE TITLE
Flexible PSL attribute case?

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#3395]
Following up from prisma/specs#86 

### Problem

Our current focus is on JS, a camelCase language. This means our PSL will lead with this form:

```
model Post {
  a   DateTime  @updatedAt
}
```

Rather than:

```
model Post {
  a   DateTime  @updated_at
}
```

This will, in its little way, be alienating toward non-camel-case projects. The kind of unspoken polish many a developer will pick up on but probably say nothing about. Is this a problem worth solving? 

### Proposal
In the context of attribute identifiers, make PSL treat the following as equivalent:

```
aA
```
```
a_a
```

The rule would be: `[A-Z]` means the same thing as `_ + [a-z]`.

#### We get

Allows users to write either style, as they please:

```
model Post {
  a   DateTime  @updatedAt
  b   DateTime  @updated_at
}
```

#### We lose

Impossible to define `@fooBar` and `@foo_bar` as not the same thing. I don't think we care about giving this up.

**Comment by ahmed-rezk-dev** [comment]
Is there any updates about this request?

**Comment by dimino** [comment]
I guess I care less about how the JS/TS/Prisma schema looks, and more about what's happening in the built SQL.  For postgres, I'd really like to not have to throw a `@map(name: "snake_case_column")` on every field, is all.  That seems more doable than trying to support snake_case in the Prisma schema itself.

**Comment by jasonkuhrt** [comment]
@dimino would love to see that too, in addition. Let's have both :D

**Comment by janpio** [comment]
This ship has sailed it seems, if we ever do this it would be in a future major Prisma version that evolves the schema fundamentally.
