### ISSUE TITLE
Introduce sum types, drop enum

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#3396]
I think PSL would benefit from adopting [Sum Types](https://en.wikipedia.org/wiki/Tagged_union) and forgoing the more limited enum.

#### Example:

Before:

```
enum Color {
  Red
  Teal
}
```

After:

```
union Color {
  Red
  Teal
}
```

#### Regarding:

> Enums can include their corresponding value to determine what is stored by the datasource:

Before:

```
enum Color {
  Red  = "RED"
  Teal = "TEAL"
}
```

After:

Idea here is to leverage attributes to express the differing db representation.

```
union Color {
  Red  @as("RED")
  Teal  @as("TEAL")
}
```

#### Advantages of `union` 

* puts PSL in a position to naturally expand support for unions of models or whatever future constructs there are without users having to learn new concepts.
* avoids the overloaded terminology legacy of enum
* PSL already has models which are akin to [product types](https://en.wikipedia.org/wiki/Product_type). Sum types are a natural companion. The presence of both would seem to usher PSL into the realm of [Algebraic Data Types](https://en.wikipedia.org/wiki/Algebraic_data_type) (ADTs). The gist here is that aligning with strong/elegant theory tends to pay dividends later (But, we must clarify what they would/could be, of course. Right now, I am not sure).

---

More motivating examples and rationale to come as I get deeper with Prisma.

**Comment by janpio** [comment]
This ship has sailed it seems, if we ever do this it would be in a future major Prisma version that evolves the schema fundamentally.
