### ISSUE TITLE
Executing a Raw mutation without `rawAccess: true` returns a cryptic error message

### ISSUE THREAD

**Issue by abhiaiyer91** [prisma/prisma#3398]
**Describe the bug**
* Using the MySQL connector
* Prisma 1.19
* No `rawAccess` set in `docker-compose.yml`

Execute this:

```
mutation {
   executeRaw(query: "SELECT * FROM `default@default`.`User`")
}
```

Returns this error:

`ERROR: syntax error at or near \"`\"\n  Position: 15",`

**Comment by divyenduz** [comment]
This should indeed return a clearer error message.

**Comment by do4gr** [comment]
This now returns a Sangria query validation error letting the user now that the field executeRaw is not available. This is probably clear enough?

```
{
  "data" : null,
  "errors" : [ {
    "message" : "Cannot query field 'executeRaw' on type 'Mutation'. (line 3, column 4):\n   executeRaw(query: \"SELECT * FROM `default@default`.`User`\")\n   ^",
    "locations" : [ {
      "line" : 3,
      "column" : 4
    } ]
  } ]
}
```
