### ISSUE TITLE
Adjust type from array to single nullable element when querying for `first: 1` or `last: 1` records

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#3399]
I think it could be nice to adjust the type from an array to a single nullable element when querying for one (or less) records via the `first: 1` or `last: 1` pagination options (either via `findMany` or when using `include` / `select`).

Example:

```ts
const usersArray: User[] = await db.user.findMany()
const nullableUser: User | null await db.user.findMany({ first: 1 })
```

This API would also supersede the `findFirst` or `findMany().first()` API .

While this might be a bit of a controversial API adjustment, I think it would enable a really nice developer experience in these cases.

**Comment by matthewmueller** [comment]
#3676 will address this one
