### ISSUE TITLE
Create a `.gitignore` file on `prisma init`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3400]
Quoting from [this](https://github.com/prisma/prisma2/issues/1481) issue:

> Docs + examples should point out that we strongly recommend to not check in the .env file to their VCS

Should we consider creating a `.gitignore` file for the `init` command?

It would probably be as simple as:

**.gitignore**

```
node_modules
# Keep environment variables out of version control
.env
```

**Comment by pantharshit00** [comment]
I marked this as a feature.
