### ISSUE TITLE
java.sql.SQLException: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by tomitrescak** [prisma/prisma#3401]
**Describe the bug**

I am performing update in a for loop, updating 2-50 records at a time.
During these updates I often (not always) receive following error:

```
Caused by: java.sql.SQLException: Deadlock found when trying to get lock; try restarting transaction
Query is: UPDATE `default@default`.`Role` SET  `description`  = ? , `name`  = ? , `roleId`  = ? , `updatedAt` = ?  WHERE `id` = (SELECT `id` FROM (SELECT * FROM `default@default`.`Role`) IDFROMWHERE WHERE `roleId` = ?), parameters ['Standard user 1234','User','user','2018-11-01 06:17:14.285','user']
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
```
 
I am using MySQL database generated by prisma

**Versions (please complete the following information):**
 - OS: OS X 
 - `prisma` prisma 1.19.0

This is the method that makes problems:

```ts
export const mutation: Mutation = {
  async saveRoles(_parent, { input }, ctx) {
    const systemRoles = await ctx.db.query.roles({});

    // delete removed roles
    let deleted = systemRoles
      .filter(r => input.every(s => r.roleId !== s.roleId))
      .map(r => r.roleId);

    if (deleted.length) {
      await ctx.db.mutation.deleteManyRoles({ where: { roleId_in: deleted } });
    }

    // insert or update missing roles
    for (let role of input) {
      if (!role.roleId) {
        await ctx.db.mutation.createRole({
          data: { roleId: role.name.url(), description: role.description || '', name: role.name }
        });
      } else {
        await ctx.db.mutation.updateRole({
          where: { roleId: role.roleId },
          data: { roleId: role.roleId, description: role.description || '', name: role.name }
        });
      }
    }

    return ctx.db.query.roles({});
  }
};
```

**Comment by mavilein** [comment]
Hey @tomitrescak 👋  ,

is this mutation called concurrently by some other code? Is there a specific reason you are not using the existing `upsert` mutation?

**Comment by tomitrescak** [comment]
@mavilein, no the code is running only from the function above. I am getting deadlocks with upsert as well.

**Comment by brunocascio** [comment]
I'm facing the same

**Comment by tomitrescak** [comment]
Of course the error was on our side, here is what happened:

1. I was running integration tests
2. Before each test I would clear the related tables
3. I perform the test
4. I cleanup tables

What happened, that in the process of the test (3) I would asynchronously launch DB modifications, which would be still happening when already the cleanup (4) would start. 

I am NOT sure why this would lead to deadlock since this is just a simple race condition problem, but there you go. I close it for now if there is a will to investigate from dev I can possibly come up with a 80% repro.
