### ISSUE TITLE
Binaries: Statically link `libssl` for local development

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#3403]
When working on Linux and not having `libssl` installed, the Prisma binaries won't work. 

2 options to improve the UX here:

1. Prompt the user in the CLI to install `libssl` using the platform's package manager. (Not clear if the binary by itself could even be started, but whatever client starts it might handle that)

2. A more seamless experience could be to automatically download a binary version that statically includes `libssl` and print a warning that this is potentially a security issue.

**Comment by janpio** [comment]
Does not seem to be a common issue.
