### ISSUE TITLE
[Errors] New common error from malformed connection string

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#3405]
While implementing the errors spec in the introspection and migration engines, @do4gr and me realized we don't have an error in the spec for connection strings that do not make sense/can't be parsed. This error would only be able to return the connection string and an optional error message.

Maybe something like: "The database connection string `${database_connection_string} could not be parsed.`".

**Comment by tomhoule** [comment]
Note: I just went through https://github.com/prisma/prisma-engines/tree/master/libs/user-facing-errors/src and it looks like we still don't have a user facing error for this. Should we?

**Comment by janpio** [comment]
Yes, it would definitely improve the usability for Prisma in scenarios, where for example the connection string is user supplied and allows potential users of this to skip validating that on their side.
