### ISSUE TITLE
Fluent API of TS client breaks in latest beta

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3410]
**Describe the bug**

Fluent API of TS client breaks in latest beta

**To Reproduce**

Use the latest beta: `prisma/1.20.0-beta.22`

1. Create new project: `prisma init`
2. Generate the TS client and deploy to a Demo server
3. Update the data model to this and deploy afterwards and regenerate the client afterwards:
   ```graphql
    type Post {
      id: ID! @unique
      createdAt: DateTime!
      updatedAt: DateTime!
      title: String!
      published: Boolean! @default(value: "false")
      author: User
      comments: [Comment!]!
    }

    type User {
      id: ID! @unique
      name: String
      email: String! @unique
      role: Role! @default(value: "USER")
      posts: [Post!]!
      comments: [Comment!]!
    }

    type Comment {
      id: ID! @unique
      createdAt: DateTime!
      text: String!
      post: Post!
      writtenBy: User!
    }

    enum Role {
      USER
      ADMIN
    }
   ```
4. Try to run the following TS code in a script:
   ```ts
    import { prisma } from "../generated/prisma-client";

    async function main() {

      const posts = prisma.user({
        email: "alice@priasma.io"
      }).posts()

    }

    main();
   ```
5. It yields the error: `Property 'comments' does not exist on type 'Post'.`

Here's what my `package.json` looks like:

```json
{
  "devDependencies": {
    "ts-node": "^7.0.1",
    "typescript": "^3.1.4"
  },
  "dependencies": {
    "graphql": "0.13",
    "graphql-tools": "^4.0.3",
    "prisma-client-lib": "^1.19.1"
  },
  "scripts": {
    "ts-node": "ts-node",
    "start": "ts-node ./src/index.ts"
  }
}
```

**Expected behavior**

The Fluent API should work.

**Comment by sapkra** [comment]
After I updated my project to `1.20.0-beta.24` I'm getting the following error.

```bash
Cannot find name 'NodePromise'
```

```typescript
export interface Prisma {
    node: (args: { id: ID_Output }) => NodePromise;
}
```

**Comment by lterfloth** [comment]
Having the same problem. Changing NodePromise to Node fixed it for me (at least 'yarn start' starts the server now). BUT as we are not supposed to change the index.ts whatsoever I'm kind of confused what to do. I'm using the 1.21 alpha due to the mongodb support

**Comment by ellipticaldoor** [comment]
I'm having same problem on 1.20 stable, I can't compile my project

**Comment by divyenduz** [comment]
This is fixed in `prisma@1.21.0-beta.2` - please install it via `npm install -g prisma@beta`

**Comment by sapkra** [comment]
@divyenduz Should I create a new ticket for adding tests or do you want to do this in this ticket?
The tests should include generating a prisma-client based on a more complex `schema.graphql` like in [this project](https://github.com/prisma/graphql-prisma-typescript/blob/master/src/schema.graphql). After that the prisma-client should be successfully compiled. The test should fail when the compilation fails.

**Comment by divyenduz** [comment]
@sapkra : Thanks! please create a new issue, also add to that, that we should add executing operations against a live Prisma service in the test suite to test `prisma-client-lib` part and tag me on that issue 🙏
