### ISSUE TITLE
PostgreSQL: Cannot delete from table that contains links to array elements

### ISSUE THREAD

**Issue by tomitrescak** [prisma/prisma#3415]
**Describe the bug**

On mySQL all seems to work well, but when I try to delete from a table that contains array elements, I receive following error:

```
org.postgresql.util.PSQLException: ERROR: update or delete on table "ProcessResource" violates foreign key constraint "ProcessResource_readRoles_nodeId_fkey" on table "ProcessResource_readRoles"
  Detail: Key (id)=(cjnz6smz300320a23u4nr6gqr) is still referenced from table "ProcessResource_readRoles".
```

**To Reproduce**

```graphql
type ProcessResource {
  roles: [String!]!
}
```

Fill the table with some data, then try to delete data and BOOM!

**Versions (please complete the following information):**
 - OS: [e.g. OS X
 - `prisma` 1.19.1

**Comment by do4gr** [comment]
Can you provide some more details please? I tried reproducing it, but it worked for me. 

<img width="1234" alt="bildschirmfoto 2018-11-03 um 18 38 03" src="https://user-images.githubusercontent.com/16278407/47955394-e764d180-df97-11e8-8410-336b778f3a2f.png">
