### ISSUE TITLE
prisma.$connect() is successful with invalid database configuration/credentials

### ISSUE THREAD

**Issue by MichaelHindley** [prisma/prisma#3420]
## Bug description

Given a DATABASE_URL that has invalid credentials,
when calling `prisma.$connect()`,
then I would expect a descriptive error of why prisma cant connect as per https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/connection-management#overview,
instead code execution continues without error,
and fails when a query is run.

Example:

```typescript
prisma = new PrismaClient()

async function bootstrap() {
  console.log('defining server')
  await prisma.$connect() // this should not be successful since it does not connect
  const server = new ApolloServer({
    schema,
    playground: true,
    context: ({ req }: { req: Context['req'] }): Context => {
      const context = {
        req,
        user: req.user,
        prisma,
      }

      return context
    },
  })

  // Start the server
  console.log('starting server')
  try {
    const { url } = await server.listen(PORT)
    console.log(`Server is running, GraphQL Playground available at ${url}`)
  } catch (e: unknown) {
    console.log(JSON.stringify(e, null, 2))
  }
}
```
Server starts successfully, when running a query:

` Error in connector: Error querying the database: db error: FATAL: role \"cake\" does not exist",`

## How to reproduce

Provide invalid credentials as DATABASE_URL and run `prisma.$connect()`.

## Expected behavior

A clear and concise error message.

## Prisma information

prisma v 2.5.1

## Environment & setup

- OS: mac
- Database: postgres
- Node.js version: 12
- Prisma version:
2.5.1
```

```

**Comment by MichaelHindley** [comment]
Workaround:

```typescript
await prisma.$connect() as PrismaClient
await prisma.$executeRaw('SELECT * FROM Something;')
```

**Comment by janpio** [comment]
Related to @divyenduz's observation that `$connect()` does not necessarily create a connection to the database.

**Comment by janpio** [comment]
This should not really be the case any more - please confirm @pantharshit00 👍

**Comment by pantharshit00** [comment]
It works now:
![image](https://user-images.githubusercontent.com/22195362/118520939-2161e180-b758-11eb-8e8e-fc6fb0ceb10c.png)
