### ISSUE TITLE
GraphQL error: Invalid Version: 1.17

### ISSUE THREAD

**Issue by siddhant1** [prisma/prisma#3423]
**Describe the bug**
Prisma cloud should create a new Server

**To Reproduce**
1. Create a new Server using Heruko(I am doing it this way)

**Expected behavior**
Should make a new Server

**Screenshots**

![screenshot 6](https://user-images.githubusercontent.com/30566406/47964288-93bcbb80-e05d-11e8-881c-6f1a41f718a0.png)

**Versions (please complete the following information):**
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 
 - `prisma` CLI: [e.g. `prisma/1.9.0 (darwin-x64) node-v10.4.0`]
 - Prisma Server: [e.g. `1.9.0`]
 - `graphql-cli`, `prisma-binding`, `graphql-yoga`, etc. if applicable

**Comment by phuongthuan** [comment]
@siddhant1 I got the same error. Looking for help.

**Comment by divyenduz** [comment]
This issue is resolved. Thanks for the detailed report.
