### ISSUE TITLE
Aggregate ignores @map value of field, generating an incorrect query

### ISSUE THREAD

**Issue by ConneXNL** [prisma/prisma#3425]
When doing an aggregation on the following field:
`field_name             Int             @map("actual_column_name")`

```
    const result = await prisma.example.aggregate({
        avg: {
            field_name: true
        }
    });
```

An invalid query is generated: 
```SELECT AVG(`field_name`) ```

rather than 
```SELECT AVG(`actual_column_name`)```

(tested in MYSQL)

**Comment by pantharshit00** [comment]
I can confirm this bug. Looks like we are ignoring the map directive.

https://github.com/harshit-test-org/prisma-issue-3425

**Comment by dpetrick** [comment]
Fixed with https://github.com/prisma/prisma-engines/pull/1080, will be in the 2.6 release.
