### ISSUE TITLE
CLI missmatches projects on prisma delete

### ISSUE THREAD

**Issue by kepikoi** [prisma/prisma#3434]
**Describe the bug**
I have two projects on demo-eu1 server and 
`prisma delete project1` removed the wrong service project2:

![image](https://user-images.githubusercontent.com/12378498/48124438-90ebe180-e27c-11e8-8be3-b28ab6fb38d8.png)

**To Reproduce**

In Windows PowerShell:
```
mkdir newproject && cd newproject

prisma init
? Set up a new Prisma server or deploy to an existing server? Demo server
? Choose the region of your demo server info-680cc8/demo-eu1
? Choose a name for your service prisma-demo-1
? Choose a name for your stage dev
? Select the programming language for the generated Prisma client Don't generate

prisma deploy

del *

prisma init 
? Set up a new Prisma server or deploy to an existing server? Demo server
? Choose the region of your demo server info-680cc8/demo-eu1
? Choose a name for your service prisma-demo-2
? Choose a name for your stage dev
? Select the programming language for the generated Prisma client Don't generate

prisma deploy

prisma list

prisma delete prisma-demo-1
```

**Expected behavior**
```prisma delete prisma-demo-1``` musn't remove prisma-demo-2 from my services

**Screenshots**
the repro output:
![prisma-service-name-missmatch](https://user-images.githubusercontent.com/12378498/48125712-a0b8f500-e27f-11e8-8c40-57e93ea10a66.jpg)

**Versions (please complete the following information):**
 - OS: [`Windows 10 1803`] 
 - `prisma` CLI: [`prisma/1.19.3 (windows-x64) node-v10.8.0`]
 - Prisma Server: [`eu-west-1 1.20-beta-1`]
 - Node.js: [`v10.8.0`]
 - npm: [`6.4.1`]

**Additional context**
Prisma also maps the wrong service when used via prisma-binding on e.g.  apollo-server-express. Although  prisma-demo-1 is defined in `prisma.yml` the playground resolves to the datamodels from prisma-demo-2

**Comment by pantharshit00** [comment]
I can confirm this is an issue on mac as well.


![screenshot 2018-12-02 at 8 08 57 pm](https://user-images.githubusercontent.com/22195362/49341057-1ee59d00-f66e-11e8-88d5-74ffd27f4b2e.png)


I think this is a quite a big bug and should be soon fixed.

**Comment by pantharshit00** [comment]
Ya there is current way to pass a parameter to it, we are currently discussing to provide the option. In the meanwhile, you can change project in prisma.yml to delete
