### ISSUE TITLE
Insert missing relation fields when `prisma generate` is invoked

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3434]
The way how relations are modeled often leads to confusions among our users. A big part of these confusions comes from the fact that on a schema-level we allow that only one side of a relation is specified. Just today, there were two instances where this confused users ([case 1](https://github.com/prisma/prisma/discussions/3430), [case 2](https://prisma.slack.com/archives/CKQTGR6T0/p1598430272223600)).

In both cases, users were not aware that Prisma always requires both side of the relation to be present. They didn't know because their schemas didn't show any errors and apparently they weren't using the VS Code extension which auto-inserts the missing relation fields.

A few ideas how this could be handled:

- Show an error in VS Code with a quick fix suggestion of adding the other side of the relation
- When running `prisma generate` (or another command that reads the schema, like `prisma migrate`), we could auto-insert the missing fields and print this as a note in the output of the CLI command
- Throw an error when `prisma generate` is invoked and the second side of a relation is missing

## Confusing example scenarios

Here's one schema that confused a user [here](https://github.com/prisma/prisma/discussions/3430):

```prisma
model User {
  objectId      String @id
  firstName     String
  facilities    Facility[] @relation("UserFacility")
}

model UserFacility {
  objectId      String
  userId        User @relation(fields: [user], references: [objectId])
  user          String
  facilityId    Facility @relation(fields: [facility], references: [objectId])
  facility      String
  @@id([user, facility])
}

model Facility {
  @@map(name: "EnteredFacility") // Had to do this because table name doesn't match field name
  objectId       String @id
  center         String
  department     String
  users          User[] @relation("UserFacility")
}
```

They wanted to create a relation table with the `UserFacility` model but weren't aware of the difference of "implicit" and "explicit" m-n relations in Prisma. The schema itself is invalid because it's missing the "backrelation" fields from `User` to `UserFacility` and `Facility` to `UserFacility`. If they had used Prisma's autoformatting the fields would have been inserted like so which probably would have helped to prevent their confusion:

```diff
model User {
  objectId     String         @id
  firstName    String
  facilities   Facility[]     @relation("UserFacility")
+ UserFacility UserFacility[]
}

model UserFacility {
  objectId   String
  userId     User     @relation(fields: [user], references: [objectId])
  user       String
  facilityId Facility @relation(fields: [facility], references: [objectId])
  facility   String
  @@id([user, facility])
}

model Facility {
  @@map(name: "EnteredFacility")// Had to do this because table name doesn't match field name
  objectId     String         @id
  center       String
  department   String
  users        User[]         @relation("UserFacility")
+ UserFacility UserFacility[]
}
```

---

Another schema that caused similar problems was from a user on [Slack](https://prisma.slack.com/archives/CKQTGR6T0/p1598430272223600):

```prisma
model Project {
  createdAt         DateTime       @default(now())
  id                Int            @default(autoincrement()) @id
  isComplete        Boolean        @default(false)
  name              String         @unique
  members           User[]         @relation("User")
}

model User {
  email             String         @unique
  id                Int            @default(autoincrement()) @id
  projects          Project[]      @relation("Project")
}
```

They weren't aware that the different relation names each denoted an individual relation. If they had used the autoformatting the following fields would have been inserted and probably would have prevented some of the confusion:

```diff
model Project {
  createdAt  DateTime @default(now())
  id         Int      @default(autoincrement()) @id
  isComplete Boolean  @default(false)
  name       String   @unique
  members    User[]   @relation("User")
+ User       User?    @relation("Project", fields: [userId], references: [id])
  userId     Int?
}

model User {
  email     String    @unique
  id        Int       @default(autoincrement()) @id
  projects  Project[] @relation("Project")
+ Project   Project?  @relation("User", fields: [projectId], references: [id])
  projectId Int?
}

```

**Comment by molebox** [comment]
If i understand correctly, in the following example, we can remove the `@relation("UserFacility)` annotation because this is used to disambiguate relations and thats not relavent here? 

```
model User {
  objectId      String @id
  firstName     String
- facilities    Facility[] @relation("UserFacility")
+facilities    Facility[]
}

model UserFacility {
  objectId      String
  userId        User @relation(fields: [user], references: [objectId])
  user          String
  facilityId    Facility @relation(fields: [facility], references: [objectId])
  facility      String
  @@id([user, facility])
}

model Facility {
  @@map(name: "EnteredFacility") // Had to do this because table name doesn't match field name
  objectId       String @id
  center         String
  department     String
  users          User[] @relation("UserFacility")
}
```

This isnt really relavent to the issue at hand, im just wondering

**Comment by tomhoule** [comment]
We do not allow specifying on one side anymore, the formatter will add the second side. Do you think we can close, @nikolasburk ?

**Comment by janpio** [comment]
> * Throw an error when `prisma generate` is invoked and the second side of a relation is missing

This is the option we went a long time ago.

The schema above triggers these validation errors today:

```
PS C:\Users\Jan\Documents\throwaway\1483> npx prisma validate --schema prisma/3434.prisma     
Environment variables loaded from .env
Prisma schema loaded from prisma\3434.prisma

Error: Prisma schema validation - (validate wasm)
Error code: P1012
error: Error validating field `userId` in model `UserFacility`: The relation field `userId` on model `UserFacility` is missing an opposite relation field on the model `User`. Either run `prisma format` or add it manually.
  -->  prisma\3434.prisma:18
   | 
17 |   objectId      String
18 |   userId        User @relation(fields: [user], references: [objectId])
19 |   user          String
   | 
error: Error validating field `facilityId` in model `UserFacility`: The relation field `facilityId` on model `UserFacility` is missing an opposite relation field on the model `Facility`. Either run `prisma format` or add it manually.
  -->  prisma\3434.prisma:20
   | 
19 |   user          String
20 |   facilityId    Facility @relation(fields: [facility], references: [objectId])
21 |   facility      String
   | 

Validation Error Count: 2
[Context: validate]

Prisma CLI Version : 5.14.0
```

Similar applies to the second example schema (although there https://github.com/prisma/prisma/issues/18599 currently still stands in the way of a valid schema after using formatting to fix it).
