### ISSUE TITLE
Certain type names break JS based schema generator

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3437]
**Describe the bug**
Related to this https://github.com/prisma/prisma/issues/2659
In the JS based schema generator, the pluralization should match the pluralization strategy implemented by https://github.com/prisma/prisma/pull/3409/files

**To Reproduce**
1. Setup a project with `prisma init` workflow
1. Create a datamodel with type named `News`
1. Run `prisma generate`

**Expected behavior**
The JS based schema generator should match the actual Prisma schema. 

**Screenshots**
<img width="630" alt="screen_shot_2018-11-07_at_12 04 30_pm" src="https://user-images.githubusercontent.com/746482/48142900-b2c48300-e2d3-11e8-86cc-2aa56a4556f0.png">

**Versions (please complete the following information):**
 - `prisma` CLI: `prisma/1.20.0 (darwin-x64) node-v10.4.0`
 - Prisma Server: `1.20.0`

**Additional context**
Current workaround is https://github.com/prisma/prisma/issues/3184

**Comment by ejoebstl** [comment]
Fixed in 88529f0601f86178234f479d23a43bd062b87de6.
