### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript: src/generated/prisma.ts/index.ts(274,38): error TS2304: Cannot find name 'NodePromise'.

### ISSUE THREAD

**Issue by ysantalla** [prisma/prisma#3439]
**Describe the bug**
When generating the scheme with the prism client in version 1.20, add this line "node: (args: {id: ID_Output}) => NodePromise;" with which you have compilation problems, if I erase everything is fine.

**Screenshots**
// Code generated by Prisma (prisma@1.20.0). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

**Versions (please complete the following information):**
 - OS: [`Ubuntu 18.04`] 
 - `prisma` CLI: [e.g. `prisma/1.20.0 (x64) node-v10.13.0`]
 - Prisma Server: [e.g. `1.20.0`]
 - `prisma-client/1.20.0`

**Additional context**

**Comment by mikesol** [comment]
Same here, had to downgrade to 1.19.0

**Comment by chill5018** [comment]
This should be resolved now.. https://github.com/prisma/prisma/releases/tag/1.20.1

**Comment by schickling** [comment]
Thanks a lot for reporting this @ysantalla. As @chill5018 mentioned, this has been fixed in `1.20.1`. Apologies for the inconvenience.
