### ISSUE TITLE
Fix JSON autocompletion

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#3441]
As mentioned here:
https://github.com/prisma/prisma/issues/3364#issuecomment-680906313

**Comment by MichalLytek** [comment]
@janpio I can't see the fix in `2.6.0` 😕 

![image](https://user-images.githubusercontent.com/10618781/91873339-2e49ae00-ec79-11ea-8469-94ad4fe3fdf7.png)

**Comment by MichalLytek** [comment]
I believe it has to be fixed on DMMF level as otherwise `typegraphql-prisma` would need to make a special filtering case to not expose nested json inputs in mutations.

**Comment by Jolg42** [comment]
Thanks for the feedback, I'll reopen the issue and @timsuchanek will have a look next week then.

**Comment by timsuchanek** [comment]
This needs a change in the DMMF, which is being done by @dpetrick anyway in a bigger refactor right now.

**Comment by timsuchanek** [comment]
Fixed in 2.8.0
