### ISSUE TITLE
Token contained 1 grants but none satisfied the request

### ISSUE THREAD

**Issue by Melv** [prisma/prisma#3445]
**Describe the bug**

Generation a token for `http://localhost:4466/management` with the following claim

```
{
  "iat": 1541685653,
  "exp": 1542290453,
  "grants": [
    {
      "target": "*/*",
      "action": "*"
    }
  ]
}
```
works 

playground:

```
query {
  listProjects {
    name
    stage
  }
}
```
returns this

```
{
  "data": {
    "listProjects": [
      {
        "name": "soon-backend",
        "stage": "dev"
      }
    ]
  }
}
```
Trying this without wildcards in the `target` like this
```
{
  "iat": 1541685653,
  "exp": 1542290453,
  "grants": [
    {
      "target": "soon-backend/dev",
      "action": "*"
    }
  ]
}
```
returns

```
{
  "data": null,
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "listProjects"
      ],
      "code": 3015,
      "message": "Authentication token is invalid: Token contained 1 grants but none satisfied the request.",
      "requestId": "local:management:cjo8pnsd4002c0936954wajkx"
    }
  ]
}
```

**Expected behavior**
Should get the same result as with `"target": "*/*"`

**Versions (please complete the following information):**
 - OS: `Ubuntu 16.04` 
 - `prisma` CLI: prisma/1.18.1 (linux-x64) node-v9.7.1
 - Prisma Server: `1.18.1`

**Comment by timsuchanek** [comment]
Hi @Melv thanks for reporting. As far as I can see, this behavior is correct.
The claim to access server wide information (in this case `listProjects`) must be `*` on both `target` and `action`.

The situation is, that `listProjects` could theoretically cover more than just the service you provided in `target` and Prisma is more conservative in this regard, not allowing anything without `*/*`.

If this doesn't make sense to you, let me know and I'll reopen the issue.
