### ISSUE TITLE
Error when try to query parents data for two types but with one missing in the first type.

### ISSUE THREAD

**Issue by ChRomain** [prisma/prisma#3449]
**Describe the bug**
Error message received from query: "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:{ID}"

**To Reproduce**
## Multiple Path Resolution

*(prisma 15.3 and test with prisma 20.1)*

Received an error when try to query parents data for two types but with one missing in the first type.

Error message received from query: "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:{ID}"

**Repoducibility/Probability :**
  always fail

## To reproduce:
**Clone the repository:**
1. git clone https://github.com/ChRomain/MultiplePathResolution.git
2. cd multiplePathResol/
3. npm install

**Start the server**
npm-run prisma deploy

**get prisma token and copy in the index.js**
npm-run prisma token

**run test**
node index.js

**result of test**

**Test1**
1. Create 1 group with a car and a truck.
2. Create 1 characteristic with the previous car and previous truck.
3. Query the previous group and get the same parents data for the car and truck.
**OK**

**Test2**
1. Create 1 group with a car and a truck.
2. Create 1 characteristic with the previous car and previous truck.
3. Query the previous group and get different parents data for the car and truck.
**KO**

Observe trace  received from Query :
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:cjoa36t7ia8zr0986iat0x0vx",
      "path": [
        "KO",
        "truck",
        "referencedByCharacteristicDatas",
        0,
        "parentCharacteristic",
        "name"
      ],

**Expected behavior**
Expect to receive the same response for the 2 tests

**Versions (please complete the following information):**
 - OS: centos-release-7-4.1708.el7.centos.x86_64 
Linux fdcd67765900 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 - graphql: 14.0.2
 - graphql-cli: 2.16.5
 - graphql-request: 1.8.2
 - graphql-tools: 3.0.4
 - graphql-yoga: 1.16.2
 - log4js: 3.0.5
 - prisma: 1.15.3 and test with 1.20.1
 - prisma-binding: 2.1.5

**Comment by ChRomain** [comment]
@timsuchanek 
I wondered if you have some news about it ? Or if you have some advices/track to resolved it ?
Have you managed to reproduce it ?

**Comment by pantharshit00** [comment]
I can't reproduce it. Here is my output and it is a success:

<img width="916" alt="screenshot 2018-12-04 at 12 25 21 am" src="https://user-images.githubusercontent.com/22195362/49394958-3189d000-f75b-11e8-939c-fac0cac17b9a.png">


I am using prisma version `1.21` so maybe you should upgrade.
