### ISSUE TITLE
Move full `blog-env-postgresql` to e2e tests 

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#3451]
In our integration test suite, we have a test called `blog-env-postgresql`.
That test goes over the timeouts we have built-in and therefore takes a long time to succeed (about 30s).

We should move this full test instead into the e2e tests, which run async from the normal publish process, so we can iterate faster.

It's still valuable to have a minimal postgres test in the integration tests, so this test can be shortened.

**Comment by janpio** [comment]
Internal, does not exist any more in this form.
