### ISSUE TITLE
`npx prisma` loads prisma 1 npm package in certain cases. We could improve developper experience by optimizing prisma1 outputs. 

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#3452]
https://prisma-company.slack.com/archives/CEYCG2MCN/p1598447707057300

## Bug description

`npx prisma` loads prisma 1 npm package in certain cases.

## How to reproduce

When `@prisma/cli` is not installed globally and locally.
When `@prisma/cli` is defined as a dev dependency and only production dependencies are installed. (ie: when deploying to production / Heroku...)

Example here 
https://prisma.slack.com/archives/CKQTGR6T0/p1598437128227900
![image (11)](https://user-images.githubusercontent.com/1328733/91583578-b9613600-e951-11ea-9b96-86897aca6ad0.png)

## Expected behavior

We could improve developer experience by optimizing prisma1 CLI messages.

## Notes 

It's easy to fall in this trap when copy pasting `npx prisma ...` if you didn't install Prisma CLI first.
Also easy to end up there since we recommend to only install Prisma CLI locally, so if you run the command in the wrong folder it will load Prisma 1.
We need to monitor changes coming with npm v7 beta as they are tweaking npx.

**Comment by janpio** [comment]
What would you output exactly in Prisma 1? 
On install or runtime?

Can we somehow differentiate between someone who already has Prisma 1 installed and does `npx prisma` vs. someone who has no package installed and `npx prisma` just falls back to Prisma 1?

**Comment by Jolg42** [comment]
So my guess is that the easiest would be to change this:

```
Get in touch if you need help: htts://slack.prisma.io
To get a more detailed output, run $ export DEBUG="*"
```

to

```
Get in touch if you need help: htts://slack.prisma.io
To get a more detailed output, run $ export DEBUG="*"
This is a message from the Prisma 1 CLI, if you are a using Prisma 2 read this (short link https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-cli/installation)
```

A cleaner change would be to map `prisma generate` command to a nice error like
`The generate command only comes with the Prisma 2 CLI, for more details see https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-cli/installation`

There are many ways we could do things but these 2 seems easier and cover a lot of things already I think.

**Comment by janpio** [comment]
Both great ideas. We often see people using `prisma introspect`, so your first suggestion would definitely apply to that one as P1 does have that command.

**Comment by Karl-EdwardFPJeanMehu** [comment]
I temporarily solved this issue by calling Prisma from *node_modules/.bin/* via a script in package.json

**Comment by pantharshit00** [comment]
We moved our package from `@prisma/cli` to `prisma` so this is addressed.
