### ISSUE TITLE
Run prisma on google cloud app engine 

### ISSUE THREAD

**Issue by ismaelaarab** [prisma/prisma#3463]
Is it possible to run prisma in app engine (standaard environment) without docker?

**Comment by ggprod** [comment]
Is this part of the roadmap?

**Comment by teknolojia** [comment]
@ismaelaarab is this possible?

**Comment by gDelgado14** [comment]
@teknolojia no. App engine standard environments do not support either Scala (v1) nor Rust (v2).

You need to dockerize the prisma runtime if you want to run on GCP App Engine, which is incredibly easy given that they already have an official docker image.

What's the issue with running on a flexible environment?
