### ISSUE TITLE
One-to-one relation should be able to be used in connect without specifying @unique

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#3473]
## Problem
The one-to-one relations are already marked as unique in the database by prisma. They should thus be available in the `connect` as are the normal unique fields.

## Suggested solution
- I think the simplest change would be that the formatter adds a `@unique` automatically. 
- The more complex solution would be for the model to detect that it is unique and use it directly.

## Alternatives
Manually add a `@unique` on the scalar field` 

## Additional context
When you add the `@unique` to an existing relation is renames the index:
```sql
ALTER INDEX "public"."Model_userId" RENAME TO "Model.userId"
```
Not sure if that is because of a new version of migrate or because it is the way the generator detects that a property is unique?

**Comment by albertoperdomo** [comment]
Hello @Sytten,

can you please add schema and resulting client API code vs desired code? Thanks.

**Comment by Sytten** [comment]
This is less important now with `findFirst`, but still:
```prisma
model Availability {
  id     String @default(cuid()) @id
  user   User   @relation(fields: [userId], references: [id])
  // Explicit unique is required until https://github.com/prisma/prisma/issues/3473
  userId String @unique
}

model User {
  availability AvailabilityApp?
  id                String                  @default(cuid()) @id
}
```
In the database, prisma migration already create a unique index for the `userId` field but the query part doesn't pick it up.

**Comment by AhmedElywa** [comment]
Yes you can use `userId` in findOne and don't need to make `findMany` then `[0]` but now you can make `findFirst`

**Comment by do4gr** [comment]
I would assume this got fixed by this PR. https://github.com/prisma/prisma-engines/pull/2262
Since the parser now adds the implicit unique it makes its way into the dmmf and then generate. It should therefore result in the desired client API. Please re-open if that is not the case.
