### ISSUE TITLE
Support filtering on array of scalar fields (Postgres-only) 

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma#3475]
## Problem
Prisma currently supports arrays of scalar field types in Postgres (`String[]`, `Int[]`, `Float[]`, `Boolean[]`, `Json[]`, `DateTime[]`)

However, it is only possible to filter using `equals` on these fields, requiring users to match exactly the contents of the array.
This makes it difficult to realize the full capabilities of this Postgres feature, which are mostly revolving around the following needs:
 * check if the field contains the provided values (`field @> [value1, value2]`): matches our `ContainsEvery<Vec<PrismaValue>>` filter
 * check if the field is contained by the provided values (`field <@ [value1, value2]`): **doesn't seem to match our filters today**
 * check if the field has elements in common with the provided array (`field && [value1, value2]`): matches our `ContainsSome<Vec<PrismaValue>>` filter

[More in Postgres documentation](https://www.postgresql.org/docs/12/functions-array.html)

At the moment, this requires falling back to using raw SQL which defeats the purpose of allowing usage of these field types.

Note: this issue shouldn't be confused with requesting filters on regular scalars like `String` or `Int` and do `in`, `notIn`,  etc. which are supported.

### Scope
At the moment, the most critical need seems to be around (by order of decreasing priority):
 1. `String[]`
 2. `Enum[]`
 3. `Int[]`
 4. `Float[]`

`Boolean`, `DateTime`, and `JSON` don't seem to have obvious use cases at hand. They should be considered in the implementation if possible but could be cut if the complexity increases drastically.

## Suggested solution
Considering the following model:
```
model Post {
  id String @id @default(cuid())
  tags String[]
}
```

and the following data:
```
1 | ['tag1', 'tag2', 'tag3']
2 | ['tag1']
3 | ['tag2']
4 | ['tag3']
5 | ['tag2', 'tag3']
6 | ['absent']
```

The following notations should be possible:
```
 const posts: Post[] = client.post.findMany({
  where: {
    tags: {
		contains: 'tag1'
    }
  } 
})
// Resulting post IDs: 1, 2


 const posts: Post[] = client.post.findMany({
  where: {
    tags: {
		containsEvery: ['tag1']
    }
  } 
})
// Resulting post IDs: 2

 const posts: Post[] = client.post.findMany({
  where: {
    tags: {
		containsSome: ['tag1', 'tag3']
    }
  } 
})
// Resulting post IDs: 1, 2, 4, 5


 const posts: Post[] = client.post.findMany({
  where: {
    tags: {
		containsNone: ['tag1', 'tag3']
    }
  } 
})
// Resulting post IDs: 3, 6


 const posts: Post[] = client.post.findMany({
  where: {
    tags: {
		containedBy: ['tag1', 'tag2', 'tag3', 'tag4', 'tag5']
    }
  } 
})
// Resulting post IDs: 1, 2, 3, 4, 5 (not 6)
```

Equivalents for other field types should be inferred from the above.

**Comment by sorenbs** [comment]
`containedBy` was not immediately obvious to me. Is this a term generally used?

I found a reference in the [Parse documentation](https://parseplatform.org/Parse-SDK-JS/api/2.1.0/Parse.Query.html#containedBy), but don't understand the difference between `containedIn` and containedBy`:
![image](https://user-images.githubusercontent.com/281337/91851886-3e08c880-ec60-11ea-8d7e-88b181114648.png)

[MongoDB seems to call](https://dba.stackexchange.com/questions/203042/mongodb-operator-to-match-arrays-whose-elements-are-all-contained-in-a-specifie) this `setIsSubset`

What exactly is `containedBy` supposed to do? Is the order of elements important for example?

**Comment by thebiglabasky** [comment]
That took me a bit as well, and we should likely consider the name indeed. I find `setIsSubset` actually conveying the meaning better.

The use case is about ensuring you can fetch all elements whose tags are part of an authorized list. It ensures that a Post doesn't have a tag outside of that authorized set, but also doesn't necessarily has all of them.

It is a looser version of the `containsEvery` but a stronger version of the `containsSome`.

**Comment by izziaraffaele** [comment]
What about an array of enums? I believe` ENUM[]` should be included in the scope

**Comment by thebiglabasky** [comment]
@izziaraffaele good point, it's kind of like `String` or `Int` and definitely fits the problem. Added it.
Thanks!

**Comment by matthewmueller** [comment]
**Drive-by thoughts**

- `containsX` could probably be shortened to `hasX`, e.g. `containsSome` => `hasSome`
- I like `hasSubset` or `containsSubset` better than `containedBy`

**Comment by mrkirchner** [comment]
any update on this? i see roadmap label but is there a place to view the current roadmap?

**Comment by defucilis** [comment]
Seconded - I have a bunch of functionality which is waiting on this kind of ability!

One thing that my use-case requires would be to support more than one of these filtering operations on a single column. For example:

```js
 const posts: Post[] = client.post.findMany({
  where: {
    tags: {
		filters: [
                  containsSome: ['tag2', 'tag3'],
                  containsNone: ['tag1']
                ]
    }
  } 
})
//should return post IDs 3, 4 and 5 - notably not 1
```

Where later items in the filters array would override earlier items. The behaviour in the original post should still work (so `tags.containsSome` should be valid, as should `tags.filters.containsSome`)

**Comment by JClackett** [comment]
Hey, just wanted to check to see if this feature is being actively worked on and, if so, what kind of timelines it will be :) Thanks!

**Comment by janpio** [comment]
Not currently being worked on or on the immediate roadmap. Optimally leave a 👍 at the original description, and a comment with your use case below. Thanks.

**Comment by thebiglabasky** [comment]
Oh! Our bad, we actually have released this in [2.15](https://github.com/prisma/prisma/releases/tag/2.15.0)
Here are the [Docs](https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#filter-on-scalar-lists--arrays) and [Reference](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference/#hasevery) for that.

**Comment by JClackett** [comment]
@thebiglabasky Omg - how did I miss this, thanks!! this is perfect

**Comment by janpio** [comment]
Same question I asked myself :) My excuse: I just looked at the history and attributes of this issue and did not use my brain any more on a Friday evening 🤷 Sorry about the misdirection here @JClackett

**Comment by sgentile** [comment]
```
Type '{ hasEvery: readonly number[]; }' is not assignable to type 'number | IntFilter'.
  Object literal may only specify known properties, and 'hasEvery' does not exist in type 'IntFilter'.ts(2322)
index.d.ts(1544, 5): The expected type comes from property 'id' which is declared here on type 'UserWhereInput'
```

**Comment by helloworldcoding** [comment]
> Docs
hasEvery is not  contains operator (<@ ).
