### ISSUE TITLE
Loss of precision on Float fields with many digits

### ISSUE THREAD

**Issue by snake575** [prisma/prisma#3479]
## Bug description

Hi, I found a problem similar to #2903, in this case, the `Float` stored on the database is `1.59283191` but the value returned is `1.5928319100000001`

## How to reproduce

Prisma schema:
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Transaction {
  id       Int    @id @default(autoincrement())
  amount   Float
}
```

Mutation:
```ts
const transaction = await prisma.transaction.create({
  data: {
    amount: 1.59283191,
  },
})
console.log({ transaction })
```

Returns wrong amount:
```js
{ transaction: { id: 1, amount: 1.5928319100000001 } }
```

### Expected behavior

```js
{ transaction: { id: 1, amount: 1.59283191 } }
```

## Environment & setup

- OS: `Debian 11 (WSL2)`
- Database: `Postgres 12.4`
- Node.js version: `v14.5.0`
- Prisma version:

```
@prisma/cli          : 2.6.0-dev.58
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
```

**Comment by pantharshit00** [comment]
Thanks for the detailed reproduction, I can confirm this. This will need a fix on the engines level.

**Comment by pimeys** [comment]
Been digging into this today, findings so far:

- The values are stored with the right precision.
- The values are loaded from the database with the right precision.
- The JSON rendering converts the decimal into a float, which loses the precision.

**Comment by pimeys** [comment]
We could try some different ways maybe when we jump into the JavaScript land. Here one option I tried is to serialize decimals as strings, leading to the correct precision. You see how the float is off, but the string representation is correct:

![Screenshot_2020-09-10 Playground - http localhost 4466 (1)](https://user-images.githubusercontent.com/34967/92711053-ce719800-f347-11ea-93c8-9fa1f17cd7f9.png)
![Screenshot_2020-09-10 Playground - http localhost 4466 ](https://user-images.githubusercontent.com/34967/92711056-cf0a2e80-f347-11ea-85e9-3e0951c7c318.png)

Additionally, to make it a bit nicer for the users, we could maybe use libraries such as the [decimal.js](https://github.com/MikeMcl/decimal.js/) to convert the floats into decimals. This would keep the precision and offer an API to handle the resulting numbers.

**Comment by pimeys** [comment]
Ok, I found a hack that might save us here for now. What I found out from the `Decimal` conversion to `f64` is that the library started using the mantissa algorithm, which is much faster to convert but causes a loss of precision. What we could do here is a conversion to string first and from there to float. This is very slow compared to the mantissa, but would at least save us from inaccuracies...
