### ISSUE TITLE
Report the database version in the migrate/introspection error reports

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#3486]
Please see: https://github.com/prisma/error-reporting-gui/issues/28

Right now we don't collect this information in the error reports but the database version information can be very useful for figuring out what happened. This mostly likely will need some engines work, cli work and changed on the error handling backend.

This issue aims on kickstarting that process.

**Comment by janpio** [comment]
[Initial conversation showed](https://prisma-company.slack.com/archives/C4GCG53BP/p1598956758115500) that we have similar information available in quaint already, so exposing this would just be a question of creating an RPC for it and then calling that during the error report generation.

**Comment by Jolg42** [comment]
Done, needs to happen in prisma/error-reporting-gui#28 for the UI
