### ISSUE TITLE
EM: Error Management Epic

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma#3488]
## Problem
We have seen a certain volume of issues related to error messages, being unformatted, difficult to parse (requiring to match a code in the description...), and generally inconsistent.
This causes the following issues:
 * Users can't reliably react to errors Prisma raise
 * Prisma can't give a good overview of possible errors users could face or should react to
 * Fixing error-related issues individually turns into playing a whack-a-mole game, with marginal value, and benefits difficult to sustain, since improvements on how errors are managed only benefit to the places which got touched, instead of benefiting the whole product

## Suggested solution
Map the various flows through which errors can happen, categorize the kinds of errors, create a repository of fully qualified error codes and messages which can be handled as centrally as possible, so it can be documented, maintained, and improved over time.

## Related issues
 * Formatting, clarity or uncaptured errors
   * https://github.com/prisma/prisma-client-js/issues/846
   * https://github.com/prisma/prisma/issues/3435
   * https://github.com/prisma/prisma/issues/3494
   * https://github.com/prisma/prisma/issues/3493
   * https://github.com/prisma/prisma/issues/3405
   * https://github.com/prisma/prisma/issues/3318

 * Ability to process via code
   * https://github.com/prisma/prisma/issues/3489
   * https://github.com/prisma/prisma/issues/3397

 * Reporting mechanics
   * https://github.com/prisma/prisma/issues/1659

## Additional Context

- Prior work: https://github.com/prisma/specs/tree/master/errors
   - Important section: https://github.com/prisma/specs/tree/master/errors#prisma-sdk (links to code with error messages)
- TypeScript related issue: https://github.com/prisma/prisma/issues/3756

**Comment by Albert-Gao** [comment]
my current use case is:

When use nexus framework + prisma combo, when I have an error from the backend api

```json
{
  "errors": [
    {
      "message": "\nInvalid `ctx.db.user.update()` invocation in\n/Users/AlbertGao/codes/teamingCloud/monorepo/packages/nexus/api/graphql/entities/test.ts:9:28\n\n   5 definition(t) {\n   6   t.field('testPrisma', {\n   7     type: 'User',\n   8     resolve: (_, __, ctx) => {\n→  9       return ctx.db.user.update(\n  Query interpretation error. Error for binding '0': AssertionError(\"Required exactly one parent ID to be present for connect query, found 0.\")",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "testPrisma"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "P2016",
          "meta": {
            "details": "Error for binding '0': AssertionError(\"Required exactly one parent ID to be present for connect query, found 0.\")"
          },
          "stacktrace": [
            "Error: ",
            "\u001b[31mInvalid \u001b[1m`ctx.db.user.update()`\u001b[22m invocation in\u001b[39m",
            "\u001b[31m\u001b[4m/Users/AlbertGao/codes/teamingCloud/monorepo/packages/nexus/api/graphql/entities/test.ts:9:28\u001b[24m\u001b[39m",
            "",
            "\u001b[2m  \u001b[90m 5 \u001b[39mdefinition(t) {\u001b[22m",
            "\u001b[2m  \u001b[90m 6 \u001b[39m  t.field('testPrisma', {\u001b[22m",
            "\u001b[2m  \u001b[90m 7 \u001b[39m    type: 'User',\u001b[22m",
            "\u001b[2m  \u001b[90m 8 \u001b[39m    resolve: (_, __, ctx) => {\u001b[22m",
            "\u001b[31m\u001b[1m→\u001b[22m\u001b[39m \u001b[2m\u001b[90m 9 \u001b[39m      return ctx.db.user.update(\u001b[22m",
            "  Query interpretation error. Error for binding '0': AssertionError(\"Required exactly one parent ID to be present for connect query, found 0.\")",
            "    at PrismaClientFetcher.request (/Users/AlbertGao/codes/teamingCloud/monorepo/packages/nexus/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1212:15)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "testPrisma": null
  }
}
```

Is there any way I can do to identify what kind of error is this without matching hardcode string from the error message?

Isn't something like ErrorCode enum or a const object make it easier? Or I am miss something here.

Thanks :)

**Comment by janpio** [comment]
I moved your problem to its own issue @Albert-Gao: https://github.com/prisma/prisma/issues/3489
