### ISSUE TITLE
Preview feature feedback: `atomicNumberOperations`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3491]
Please share your feedback about the preview feature `atomicNumberOperations` that was released in [v2.6.0](https://github.com/prisma/prisma/releases/tag/2.6.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo. 
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma2`](https://app.slack.com/client/T0MQBS8JG/CKQTGR6T0) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by kennytraction** [comment]
With this change, referenced table updates are now required to use `set`. Is this the expected behavior?

Given the following schema:
```
model contact {
  id                 String              @default(dbgenerated()) @id
  name               String
  contactEmails      contactEmail[]
}
model contactEmail {
  id         String   @default(dbgenerated()) @id
  contactId  String
  email      String
  contact    contact  @relation(fields: [contactId], references: [id])
}
```
I get the following type for updating a contactEmail while updating the contact:
```
export type contactEmailUpdateWithoutContactDataInput = {
  id?: StringFieldUpdateOperationsInput
  email?: StringFieldUpdateOperationsInput
}
```
Why can't `email` be `string | StringFieldUpdateOperationsInput`? Does it negate the reason why this change was made in the first place?

**Comment by pantharshit00** [comment]
Hey @kennytraction 

This is actually a bug in our transformation logic which is planned to be hotfixed. 

Please see: https://github.com/prisma/prisma/issues/3497

**Comment by fchu** [comment]
Just a note so say that we upgraded to 2.6.2, and the feeling of removing swathes of business code (retrieve value, manually incr/decr, commit) while maintaining its logic unaltered thanks to this feature is a great one.

This is what an awesome database toolkit is all about – Keep up the good work!

**Comment by hatchli** [comment]
> Hey @kennytraction
> 
> This is actually a bug in our transformation logic which is planned to be hotfixed.
> 
> Please see: #3497

@pantharshit00  Was this bug not fixed by 2.6.2? I'm facing the same issue still as of 2.6.2 where suddenly all updates and upserts to basic string/int/float fields now require `set`. My app has completely broken, and I don't want to go back adding "set" to every single update/upsert field if it's unnecessary.

`schema.prisma`
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["connectOrCreate"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
...
model Product {
  id                  Int          @default(autoincrement()) @id
  slug                String       @unique
  title               String
  headline            String?
...
}
```
`src/generated/nexus.ts`
```
input ProductUpdateInput {
title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
 slug?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
headline?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
...
}
```

`package-lock.json`
```
    "nexus-plugin-prisma": {
      "version": "0.18.2",
      "requires": {
        "@prisma/cli": "2.6.2",
        "@prisma/client": "2.6.2",
        "@prisma/sdk": "2.6.2",
        "camelcase": "^6.0.0",
        "chalk": "^4.0.0",
        "common-tags": "^1.8.0",
        "dotenv": "^8.2.0",
        "fs-jetpack": "^2.4.0",
        "lodash": "^4.17.19",
        "outdent": "^0.7.1",
        "pluralize": "^8.0.0",
        "prismjs": "^1.20.0",
        "stacktrace-parser": "^0.1.10"
      }
    },
```

**Comment by pantharshit00** [comment]
Hey @hatchli 


Looks like this a problem in nexus, can you please open an issue here with a minimal reproduction: https://github.com/graphql-nexus/nexus-plugin-prisma

**Comment by jasonkuhrt** [comment]
Hey @pantharshit00, @hatchli; This does not represent a bug in the Nexus Prisma plugin but a limitation with the GraphQL specification which does not support unions in input types (it is coming eventually).

Nexus Prisma _could_ have a feature that allows you to disable this Prisma feature and "collapse" the atomic operations back to `string` at the GraphQL schema level where a string would infer a `set` (could be configurable too).

Nexus Prisma _could_ also eventually have rich mapping features that permit ad-hoc customization of how the GraphQL schema maps to the Prisma Client API.

But as it stands today, if you want to upgrade, you're going to _have_ to do exactly this:

> go back adding "set" to every single update/upsert field if it's unnecessary.

You are more than welcome to [make a feature request](https://github.com/graphql-nexus/nexus-plugin-prisma/issues/new) about how you wish the crud system worked instead.

**Comment by nikolasburk** [comment]
Thanks for your feedback everyone, this has been promoted to stable in v2.10.0 🙌
