### ISSUE TITLE
post-deploy hooks failing on windows since 1.20

### ISSUE THREAD

**Issue by pedwards1** [prisma/prisma#3491]
**Describe the bug**
Post-deploy hooks are failing on windows since 1.20 - these were executing fine on 1.19.3.

For example using the following hook for prisma generate fails 
hooks:
  post-deploy:
    - prisma generate

fails with:
_post-deploy:
spawnSync prisma ENOENT
Running prisma generate ×_

However changing 'prisma deploy' to 'prisma.cmd deploy' allows the command to be found and executed. This workaround was not required for 1.19.3. The same error and workaround also applies for other commands such as the graphql cli etc i.e. graphql get-schema fails but works when changed to graphql.cmd

**To Reproduce**
1. add a post deploy script for 'prisma generate' using 1.20.1 prisma cli on windows
2. run prisma deploy

**Expected behavior**
Prisma deploy should execute successfully

**Versions (please complete the following information):**
 - OS: Windiws 10
 - `prisma` CLI: 1.20.1
 - Prisma Server: 1.20.1

**Comment by yaacovCR** [comment]
Regression is because a [recent commit](https://github.com/prisma/prisma/commit/226daa35ee26510c25e4b75a96647846cc75802b) upgraded npm-run to latest version. Fix #2557 had purposely downgraded npm-run to 4.1.2 because of known issue on windows, timoxley/npm-run#19.

**Comment by yaacovCR** [comment]
Pull request timoxley/npm-run#21 will hopefully fix this issue.

**Comment by divyenduz** [comment]
@yaacovCR : Thanks for the detailed insights, you are correct that this is a regression, I will patch this up soon.

**Comment by yaacovCR** [comment]
Thanks and thank you for your work on Prisma!

**Comment by difagume** [comment]
I'm sorry I don't understand what the solution to this error is, someone can explain to me what to do, thank you

**Comment by yaacovCR** [comment]
@difagume, workaround for now is as mentioned above by @pedwards1, to change the `prisma` command on windows within the post-deploy hook to `prisma.cmd`. It seems the eventual fix will be to move back to an older version of npm-run for now, but that has not been released yet.

**Comment by Anthony59273** [comment]
Thanks @pedwards1 !
Same can be done if you're trying to execute `graphql` in your post-deploy then you can replace with `graphql.cmd`.
