### ISSUE TITLE
Relational filters don't work in Go client

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3492]
**Describe the bug**

I want to do the Go-equivalent of this relational filter operation:

```ts
// Fetch all comments  of a particular post 
// that start with "Great"
const comments: Comment[] = await prisma
  .post({
    id: "cjnymovvds3hy0a51xtxyhyh2"
  })
  .comments({
    where: {
      text_starts_with: "Great"
    }
  });
```

The following code compiles but throws an error:

```go
"cjoem7agzqyuq0911h5j42pcl"
filter := "Great"
comments, err := client.Post(prisma.PostWhereUniqueInput{
    ID: &id,
}).Comments(&prisma.CommentsParamsExec{
    Where: &prisma.CommentWhereInput{
        TextStartsWith: &filter,
    },
}).Exec(ctx)

if err != nil {
    panic(err)
}
fmt.Printf("%#v\n", comments)
```

I don't understand why I need to pass the params for filtering the commtens as `CommentsParamsExec` and not just as `CommentsParams`. When trying to adjust `CommentsParamsExec` to `CommentsParams` I get a compiler error:

```
src/script.go:32:3: cannot use "go-code-snippets/generated/prisma-client".CommentsParams literal (type *"go-code-snippets/generated/prisma-client".CommentsParams) as type *"go-code-snippets/generated/prisma-client".CommentsParamsExec in argument to client.Post("go-code-snippets/generated/prisma-client".PostWhereUniqueInput literal).Comments
```

**Comment by dominikh** [comment]
> The following code compiles but throws an error:

What error?

**Comment by dominikh** [comment]
https://github.com/prisma/prisma/issues/3853

**Comment by nikolasburk** [comment]
> What error?

I've posted the error message in the original question as well 🙂 It's this one:

```
src/script.go:32:3: cannot use "go-code-snippets/generated/prisma-client".CommentsParams literal (type *"go-code-snippets/generated/prisma-client".CommentsParams) as type *"go-code-snippets/generated/prisma-client".CommentsParamsExec in argument to client.Post("go-code-snippets/generated/prisma-client".PostWhereUniqueInput literal).Comments
```

**Comment by dominikh** [comment]
@nikolasburk I am refering to `The following code compiles but throws an error:` – presumably it wouldn't show a compile error if it compiled :)

**Comment by nikolasburk** [comment]
🤦‍♂️ My bad, sorry! Let me look into it, I'll try to reproduce it.

**Comment by nikolasburk** [comment]
I'm not able to reproduce the issue any more since I can't add `Comments` after `Post(...)`:

![image 5](https://user-images.githubusercontent.com/4058327/52339612-e798c100-2a0d-11e9-856e-6d1ab6437de7.png)

For refernece, this is my datamodel:

```graphql
type Post {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  title: String!
  published: Boolean!
  author: User!
  comments: [Comment!]!
}

type User {
  id: ID! @unique
  name: String
  email: String! @unique
  accessRole: AccessRole!
  posts: [Post!]!
}

type Comment {
  id: ID! @unique
  createdAt: DateTime!
  text: String!
  writtenBy: User!
  post: Post!
}

enum AccessRole {
  USER
  ADMIN
}
```

**Comment by dominikh** [comment]
@nikolasburk I cannot reproduce that issue, either :-/ Are you sure that you're testing with the latest `master` or `alpha` branches? Either of those should be working correctly. Also make sure it's not just a bug in the auto completion used by your editor.

**Comment by pantharshit00** [comment]
Closing this now :)
