### ISSUE TITLE
updatedAt field is not updated

### ISSUE THREAD

**Issue by prolink007** [prisma/prisma#3505]
**Describe the bug**
The `updatedAt` field on my types is not getting updated when making updates to the database.

**To Reproduce**
I have a model like the following:

```
type Example {
    id: ID! @unique
    createdAt: DateTime!
    updatedAt: DateTime!
    text: String
}
```

I create an `Example`. Then i update the `text` on the created example and `updatedAt` is not updated. It still remains the same as the `createdAt` field.

**Expected behavior**
I would expect `updatedAt` to change when any field is updated on the type.

**Versions (please complete the following information):**
        "prisma-binding": "2.1.6",
        "prisma-yml": "1.19.1",
        "graphql-yoga": "1.16.7",
        "prisma": "1.19.1",

**Comment by prolink007** [comment]
I see other bugs related to this issue, but i am still seeing this as a problem.

**Comment by mavilein** [comment]
@prolink007 : Which connector are you using?

**Comment by prolink007** [comment]
> @prolink007 : Which connector are you using?

I am not sure what you mean by "connector". This is mySql, if that is what you are asking.

**Comment by prolink007** [comment]
Any news on this issue? Still looking for assistance.

**Comment by mavilein** [comment]
@prolink007 : We have a dedicated [test](https://github.com/prisma/prisma/blob/master/server/servers/api/src/test/scala/com/prisma/api/mutations/UpdatedAtShouldChangeSpec.scala) case for this behaviour. I just ran it with the MySQL connector and it passes as expected. Do you have more details that would help me reproduce this? My guess is that you are running with a really old version of the Prisma core.

**Comment by prolink007** [comment]
@mavilein How do i check my prisma core version? I showed you the versions i am using in the original post. Are those the correct versions? Do you need the version of something else?

**Comment by mavilein** [comment]
@prolink007 : Open the url `/management` on your prisma server, e.g.`http://localhost:4466/management` on localhost. Then perform the following query:
```
{
  serverInfo {
    version
    commit
    primaryConnector
  }
}
```

Let's see what this will tell us :-)

**Comment by prolink007** [comment]
@mavilein 
```
{
  "data": {
    "serverInfo": {
      "version": "1.8.4",
      "commit": "86cf1d1adacded29c2b898d2d617b30b86fba483"
    }
  }
}
```

`primaryConnector` was not available so i removed it from the query.

**Comment by mavilein** [comment]
@prolink007 : As i guessed you are running a really old version of the Prisma server. Please upgrade to the latest version and your issue will be fixed :-)

**Comment by prolink007** [comment]
@mavilein How do i upgrade the prisma server? All the versions i have that are prisma related seem to be the latest version.

**Comment by Errorname** [comment]
Prisma server is dockerized. It should be in your docker-compose.yml file I guess ?

**Comment by prolink007** [comment]
Had to update the 
```
services:
  prisma:
    image: prismagraphql/prisma:1.20
```

In my yml file.
