### ISSUE TITLE
Multiple many-many relationships appears to cause an introspection failure.

### ISSUE THREAD

**Issue by ryardley** [prisma/prisma#3507]
## Bug description

Trying to introspect a model with multiple many-many relationships appears to cause an introspection failure.

## How to reproduce

Use migrate to setup a database with the following schema:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id        String  @id @default(dbgenerated())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  String?
  tags      Tag[]
  antitags  Tag[]   @relation("Antitags")
}

model Tag {
  id        String @id @default(dbgenerated())
  label     String
  posts     Post[]
  antiposts Post[] @relation("Antitags")
}

model User {
  id    String  @id @default(dbgenerated())
  email String  @unique
  name  String?
  posts Post[]
}
```

Note the "Antitags" relationship

Running `prisma validate` seems to think the schema is valid. 

Run `prisma introspect`

Note there is an error. 

```
Oops, an unexpected error occured!
[libs/datamodel/core/src/dml/model.rs:166:14] We assume an internally valid datamodel before mutating.
```

## Expected behavior

Introspect should probably not do anything here as the db schema should be setup by migrate. 

## Prisma information

As above but you can checkout the 👉 **[EXAMPLE REPOSITORY](https://github.com/ryardley/prisma-introspect-error-example)** 👈 

## Environment & setup

- OS: MacOS
- Database: Postgres
- Node.js version: 12.16.1
- Prisma version: 

```
@prisma/cli          : 2.6.0
Current platform     : darwin
Query Engine         : query-engine 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.272.0
```

**Comment by ryardley** [comment]
Would love to know what the workaround for managing this is. Currently we are working with knex to manage our migrations until prisma migrate is ready but after going through the complex process for setting up a table I was finding it breaks introspection which is causing big issues with our project.

**Comment by janpio** [comment]
Did you write the initial schema manually or also use `introspect`?
Can you maybe share the SQL schema so we can reproduce this properly?

**Comment by ryardley** [comment]
There is a repo that should serve an example. You can get a dump from the dB there. I took the QuickStart and modified the schema and ran migrate. You can see the commands run in the example repo

**Comment by janpio** [comment]
Thanks, I was missing the context that this is about the quickstart. We should be able to reproduce with that information.

**Comment by ryardley** [comment]
It’s not about the QuickStart just a possible introspection bug I noticed. I adjusted the QuickStart schema created a migration to show the error.
