### ISSUE TITLE
Allow non-unique fields also in the where clause of findOne() besides a mandatory unique field

### ISSUE THREAD

**Issue by aflatoon2874** [prisma/prisma#3519]
## Problem
At present the where clause of a findOne() allows only unique fields. This is very restrictive. Allow non-unique fields also besides a mandatory unique field. For example, I need to fetch a record that has status = 'verified' but prisma does not allow addition of this field in the where clause as it is non-unique. I need to check status explicitly post getting the result from prisma and respond accordingly. 

## Suggested solution
Allow additional non-unique fields in the where clause with the mandatory unique one.

## Alternatives
None

## Additional context
None

**Comment by pantharshit00** [comment]
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma/issues/2954 or https://github.com/prisma/prisma/issues/1924
