### ISSUE TITLE
Subscriptions don't work: "Cannot read property 'selectionSet' of undefined"

### ISSUE THREAD

**Issue by samuela** [prisma/prisma#3520]
**Describe the bug**
The subscriptions as advertised here (https://www.prisma.io/docs/prisma-client/features/realtime-TYPESCRIPT-rsc9/) do not work.

**To Reproduce**
1. Try replicating the example code.
2. Generate the prisma bindings.
3. Try running `ctx.db.$subscribe.foo({ mutation_in: ['CREATED', 'UPDATED'] }).node();`
4. See error:
```
{ TypeError: Cannot read property 'selectionSet' of undefined
    at /Users/skainswo/dev/kumo/node-api/node_modules/prisma-client-lib/src/Client.ts:316:14
    at Array.reduceRight (<anonymous>)
    at Client.generateSelections (/Users/skainswo/dev/kumo/node-api/node_modules/prisma-client-lib/src/Client.ts:231:30)
    at Client.<anonymous> (/Users/skainswo/dev/kumo/node-api/node_modules/prisma-client-lib/src/Client.ts:138:32)
    at step (/Users/skainswo/dev/kumo/node-api/node_modules/prisma-client-lib/dist/Client.js:47:23)
    at Object.next (/Users/skainswo/dev/kumo/node-api/node_modules/prisma-client-lib/dist/Client.js:28:53)
    at /Users/skainswo/dev/kumo/node-api/node_modules/prisma-client-lib/dist/Client.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/skainswo/dev/kumo/node-api/node_modules/prisma-client-lib/dist/Client.js:18:12)
    at Client.processInstructions (/Users/skainswo/dev/kumo/node-api/node_modules/prisma-client-lib/src/Client.ts:134:42)
  message: "Cannot read property 'selectionSet' of undefined",
  locations: [ { line: 2, column: 3 } ],
  path: [ 'buildEvents' ] }
```

**Expected behavior**
The example code to work.

**Screenshots**
n/a

**Versions (please complete the following information):**
 - OS: macOS 10.14.
 - `prisma` CLI: prisma/1.20.6 (darwin-x64) node-v11.1.0
 - Prisma Server: prisma cloud

**Comment by fgreinus** [comment]
Same as #3509

**Comment by timsuchanek** [comment]
As mentioned in #3509, this issue has been fixed in `1.20.7`

**Comment by ducdev** [comment]
I'm on 1.20.7 and it's not fixed.

**Comment by fgreinus** [comment]
> I'm on `1.20.7` and it's not fixed.
> `prisma/1.20.7 (darwin-x64) node-v8.12.0`
> I was trying to run `` console.log(await prisma.user({ email }).$fragment(`fragment UserId on User { id }`)); ``
> ![image](https://user-images.githubusercontent.com/3524016/48563200-5cd08a80-e926-11e8-8484-f977cf4d098b.png)

Did you do `npm i -g prisma` and npm i to update the `prisma-client-lib` dependency (to 1.20.7)? You then have to regenerate the client lib. That worked for me (for a similar problem).

**Comment by ducdev** [comment]
> > I'm on `1.20.7` and it's not fixed.
> > `prisma/1.20.7 (darwin-x64) node-v8.12.0`
> > I was trying to run `` console.log(await prisma.user({ email }).$fragment(`fragment UserId on User { id }`)); ``
> > ![image](https://user-images.githubusercontent.com/3524016/48563200-5cd08a80-e926-11e8-8484-f977cf4d098b.png)
> 
> Did you do `npm i -g prisma` and `npm i` to update the `prisma-client-lib` dependency (to 1.20.7)? You then have to regenerate the client lib. That worked for me (for a similar problem).

Yeah I did exactly the same, but it's still error.
