### ISSUE TITLE
While using PM2 on a prisma related project popus up prisma client cmd terminal on windows 

### ISSUE THREAD

**Issue by rahul3v** [prisma/prisma#3521]
Platform : windows

Steps to produce:
1. Install PM2 in a project using prisma conecting to a database,
2. Now hit the database from front-end and now you will see a **window cmd terminal** poped up

Currently using :
prisma 2.5.1 with postgress database

=======================
poped up again and again even after closing it

![pismaa](https://user-images.githubusercontent.com/24385409/92204964-48b2a000-eea2-11ea-9d8c-f7179157c349.png)

**Comment by janpio** [comment]
What is "PM2"?

**Comment by rahul3v** [comment]
It's a process manager for the JavaScript runtime Node.js, 
To handle multiple process on the server side.

For ref https://www.npmjs.com/package/pm2

**Comment by janpio** [comment]
Can you maybe share an example project created with `prisma init` that includes this in the correct configuration so we can directly reproduce the behavior?

**Comment by rahul3v** [comment]
Do you have any sample project working with prisma on window system, 
if yes then just include few things to test this issue
```
##install PM2 globally
npm install pm2 -g

##inside your project root, just run the cmd to run your nodeJs project (project start file "src/index.js")
pm2 start src/index.js
```
Now your project started as normal (as we use `npm start` or `node  src/index.js` in general cases)

Now query for something that needs database access, either from `graphql playground` or `front-end call`

============
if you still not reproduce then I will create new one from start then send it to you, I hope that's ok

**Comment by rahul3v** [comment]
In simple words,
Just run your prisma project with PM2 instead of running it normally 
then query for something that needs database access. That's it.

**Comment by janpio** [comment]
Hi @rahul3v - I can observe the behavior you are describing. After I start a server with `pm2 start server.js`, when the Query Engine is started, a `Cmd` window is opened and stays open until I stop the server with `pm2 stop server.js`:

![image](https://user-images.githubusercontent.com/183673/92416852-bccd9c00-f15f-11ea-8efb-cf152b477e21.png)

I assume that `pm2` is somehow taking control of processes. What usually happens invisibly in the background (the query engine is started and runs) is for some reason done in a visible Cmd window.

Have you talked to the Pm2 maintainers if this is intended behavior?

**Comment by rahul3v** [comment]
Hi @janpio, well, I didn't  talk to Pm2 maintainers as i thought it might be a problem from your side, as i never got anything like that until now. 
so is it possible to fix it from your side 
(**if not** then you should report the issue to PM2 maintainers as  I'm not able to generalize this issue in simple way to show this issue to them without telling them prisma installation stuffs and all, hope you understand that.)

**Comment by pantharshit00** [comment]
I was able to reproduce this on Windows. 

The problem here is pm2 runs each node process that it has to manage via child_process.fork or similar option with child_process.spawn which runs the script via `cmd` as shell on windows.


So in order to fix this, we will need to set `windowHide` option to true in our engine spawning call in order the hide the window on Windows: https://nodejs.org/dist/latest-v12.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options

We spawn the engine here: https://github.com/prisma/prisma/blob/b1174f2bf175a127065908fcb7cc4538d2c6b545/src/packages/engine-core/src/NodeEngine.ts#L578

I made this demo video to test this theory out and it works: https://www.youtube.com/watch?v=4mjefPol-c4
