### ISSUE TITLE
Allow setting scalar lists without `set`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#3529]
This works:
```
  const resultJsonUpdateWithoutSet = await prisma.post.update({
    where: {
      id: resultJsonArray.id,
    },
    data: {
      coinflips: {
        set: [true, true, true, false, true],
      },
    },
  })
```

This does not:
```
   const resultJsonUpdateWithoutSet = await prisma.post.update({
    where: {
      id: resultJsonArray.id,
    },
    data: {
      coinflips: [true, true, true, false, true]
    },
  })
```
(Note the missing `{  set: ... }` after `coinflips`)

Error message:
```
...
Unknown arg `0` in data.coinflips.0 for type PostUpdatecoinflipsInput. Available args:
type PostUpdatecoinflipsInput {
  set?: List<Boolean>
}
...
```

---
### Possible TODO:
- [ ] fix dmmf transformation (should work with and without an explicit `set:`)
- [ ] un-comment runtime test https://github.com/prisma/prisma/blob/104db729f96f8959cd7e02750baebc7e8c947e25/src/packages/client/src/__tests__/runtime-tests/blog-env-postgresql/index.js#L295
- [ ] update snapshot https://github.com/prisma/prisma/blob/104db729f96f8959cd7e02750baebc7e8c947e25/src/packages/client/src/__tests__/update.test.ts#L263

**Comment by timsuchanek** [comment]
This was never intended to work and therefore is not a regression.
It applies to all scalar lists and is something we should discuss if it's something we want, as this sounds like a valuable addition to the API to me.

**Comment by janpio** [comment]
Note: Probably covered by https://github.com/prisma/prisma-engines/issues/1088 - so no implementation work in Typescript necessary for now.
