### ISSUE TITLE
`prisma init` should ask for all needed properties when connecting to an existing MongoDB

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3533]
When using the `prisma init` command to connected to an **existing** database with the **MongoDB** connector, currently the CLI asks for:

- host
- port
- user & password

It should also ask for:

- name of the MongoDB database (`database` in `PRISMA_CONFIG`)
- name of the [auth source](https://docs.mongodb.com/manual/reference/connection-string/#urioption.authSource) (`authSource` in `PRISMA_CONFIG`)
- which protocol to use (`protocol` in `PRISMA_CONFIG`, `mongodb` or `mongodb+srv`)
- SSL or not (`ssl` in `PRISMA_CONFIG`, `true` or `false`)

**Comment by timsuchanek** [comment]
This is implemented in the latest beta.
