### ISSUE TITLE
Middleware params model should be an enum or union of strings.

### ISSUE THREAD

**Issue by dilizarov** [prisma/prisma#3545]
## Problem

```ts
prisma.$use(async (params, next) => {
  if (params.model === "User") {
    //process
  }
});
```

In the above, params.model is typed as a `string`, when the prisma client generated should be able to deduce the models based on the schema.prisma file and form a union.

## Suggested solution

If a schema.prisma has models User, Project, Task for instance, then `params.model` should be typed as `"User" | "Project" | "Task"`. If we had an enum, it could even `params.model: Model`

Ideally, we'd also have an enum we could leverage:

```ts
import { Model } from "@prisma/client";

Model.User // "User"
Model.Project // "Project"
Model.Task // "Task"

// This would allow for:

prisma.$use(async (params, next) => {
  switch (params.model) {
    case Model.User:
    case Model.Project:
    ...
  }
})
```

This should all be deduced and generated from the schema.prisma.

## Additional context
This is largely a QoL improvement.

**Comment by Sytten** [comment]
I said something similar on another issue, this would be a huge improvement.

**Comment by matthewmueller** [comment]
I agree, let's do it. This would be a compile-time breaking change, but a rather small one.

```ts
// from
type Params = {
  model: string
}

// to
type Params = {
  model: 'User' | 'Post' | ...
}
```

**Comment by LeChatErrant** [comment]
This has been broken during release 2.12 ?
MiddlewareParams.model is back to `string | undefined` instead of `Prisma.ModelName`

**Comment by Sytten** [comment]
Good catch @LeChatErrant 
@timsuchanek  @williamluke4 Seems like it was lost in the refactor of TSClient.
Original PR: https://github.com/prisma/prisma/pull/4161/files#diff-588852e24f23f92be90297901cefe3ee2bce60f10b33270db603561ff877e5a2R570
Current file: https://github.com/prisma/prisma/blob/master/src/packages/client/src/generation/TSClient/PrismaClient.ts#L243
