### ISSUE TITLE
prisma import fails with error "No such column :max"

### ISSUE THREAD

**Issue by baerrach** [prisma/prisma#3550]
**Describe the bug**
Running prisma import is failing on my data when uploading the lists.

```
Uploading lists
[
  "No such column :max"
]
```

Running `docker-compose logs -f --tail="10" prisma` shows the last activity was a node.
Yet when I use MySQL Workbench I can see that some tables that contain list values have rows.

.import/state.json
```{"nodes":50,"lists":1,"relations":0}```

**To Reproduce**
I haven't been able to create a small reproducible test case,

**Expected behavior**
The column `:max` looks like an internal thing.
The prisma server error logs should include something to help debug this.
The error message returned to the client should include something to help debug this.
The primsa server docs should have some links to how the docker image is created so there is some way to add our own debugging when this happens.

**Versions (please complete the following information):**
 - OS: Windows 10
 - `prisma` CLI: CLI
 - Prisma Server: prismagraphql/prisma:1.20

**Comment by do4gr** [comment]
Can you please provide your data model and an import file or a minimal reproduction? Then we can look into this.

**Comment by baerrach** [comment]
I can't provide a small reproduction that's too hard to do with large NDF files.

I can provide the data export and schema files, but not through a github issue.

Can you contact me with an alternative way to provide you with the information?

**Comment by baerrach** [comment]
@do4gr I've created a private github repository with the necessary files for this case and invited you.

**Comment by do4gr** [comment]
Thanks for the report and the reproduction repo. I just kicked of the 1.21.1 release that should fix the issue and allow your import to go through.

**Comment by baerrach** [comment]
@do4gr Thanks.
Trying it now.

Are you able to comment on "The primsa server docs should have some links to how the docker image is created so there is some way to add our own debugging when this happens." As I can find nothing about where the docker-compose.yml docker images are generated from.
