### ISSUE TITLE
Tests / GitHub Actions check why cached download test is really slow

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#3553]
Check why GitHub Action download test is really slow (value on GH Actions: ~4672)

https://github.com/prisma/prisma/blob/adb2116914594bf0d73edcc222e8486201d56dcd/src/packages/fetch-engine/src/__tests__/download.test.ts#L376-L379

**Comment by Jolg42** [comment]
@timsuchanek so what did you find?

It looks like it is still slow based on this comment `if binaries are already there, it should take less than 100ms to check all of them`

**Comment by timsuchanek** [comment]
@Jolg42 it turned out, that it's sufficiently fast, as we're checksumming here multiple hundred mbs of binaries.

**Comment by Jolg42** [comment]
so the code comment is not really valid anymore I guess
