### ISSUE TITLE
scripts/postinstall.js throws error inside docker

### ISSUE THREAD

**Issue by NurbekGithub** [prisma/prisma#3554]
## Bug description

Today when I tried to build docker image from service that uses prisma it started to throw error at ```npm i``` step after ```node scripts/postinstall.js```

> Error: FetchError: request to https://binaries.prisma.sh/all_commits/650b5d0348ec38ae61e1e7db69bb54808418ede4/debian-openssl-1.1.x/migration-engine.gz.sha256 failed, reason: connect ETIMEDOUT 13.33.242.105:443
    at ClientRequest.<anonymous> (/node/node_modules/@prisma/cli/build/index.js:2:2169308)
    at ClientRequest.emit (events.js:228:7)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
## How to reproduce
Here is the Dockerfile I use to build my service
```
FROM node:12.14.1 as base
ENV DEBUG=*
WORKDIR /node
COPY package*.json ./
COPY prisma ./
RUN npm i && npm cache clean --force
COPY . .

# development
FROM base as dev
CMD ["npm", "run", "watch-debug"]
```
1. Create empty folder
2. run `npm init -y`
3. run `npm i @prisma/cli`
4. run `npx prisma init`
5. run `npx prisma generate`
6. Copy Docker file above to the created folder
7. Add node_modules to .dockerignore file
8. run `docker build -t test .`
## Expected behavior
no crashes

## Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: 12.14.1
- Prisma version: 2.6.0

```

```

**Comment by NurbekGithub** [comment]
Update: I got it working with the help of https://github.com/prisma/prisma/issues/2181#issuecomment-621704375
I added
```ENV PRISMA_BINARIES_MIRROR http://prisma-builds.s3-eu-west-1.amazonaws.com```
to my Dockerfile just before `npm i`
I am not sure if this is expected. So I will leave the issue open for now.

**Comment by janpio** [comment]
> Error: FetchError: request to [binaries.prisma.sh/all_commits/650b5d0348ec38ae61e1e7db69bb54808418ede4/debian-openssl-1.1.x/migration-engine.gz.sha256](https://binaries.prisma.sh/all_commits/650b5d0348ec38ae61e1e7db69bb54808418ede4/debian-openssl-1.1.x/migration-engine.gz.sha256) failed, reason: connect ETIMEDOUT 13.33.242.105:443

This error message indicates you can not connect to https://binaries.prisma.sh/ from inside Docker. Does it work outside of it? Anything strange about the internet connection you are using like MITM or censorship or similar going on?

**Comment by NurbekGithub** [comment]
> Does it work outside of it?

Yes, it does.
> Anything strange about the internet connection you are using like MITM or censorship or similar going on

Not 100% sure, but nothing like I have experienced before.
There are similar errors sometimes on my machine when I try `npx prisma init`, though. It would start downloading binaries and stop at 0 or at 50%. This happens ~1/10 times.

**Comment by pantharshit00** [comment]
I am not able to reproduce this on my local setup.

We might need to mirrors in the future if more cases like these comes up in the future.

**Comment by NurbekGithub** [comment]
Ok. Thanks for the reply!
