### ISSUE TITLE
Nested create mutation fails if @embedded is specified

### ISSUE THREAD

**Issue by rainerschuster** [prisma/prisma#3556]
Nested create mutation fails if the nested type has directive `@embedded` declared.

1. prisma init
? Set up a new Prisma server or deploy to an existing server? Create new database
? What kind of database do you want to deploy to? PostgreSQL
? Select the programming language for the generated Prisma client Prisma TypeScript Client
2. Replace datamodel.prisma content with:
```graphql
type User {
  id: ID! @id @unique
  name: String!
}

type Foo {
  id: ID! @id @unique
  x: String!
  bars: [Bar!]!
}

type Bar @embedded {
  y: String
}
```
3. prisma generate
4. docker-compose up -d
5. prisma deploy
6. in the graphql playground execute the mutation:
```graphql
mutation createFoo {
  createFoo(
    data: {
      x: "a"
      bars: {
        create: [
          {
            y: "b"
          }
        ]
      }
    }
  ) {
    id
    bars {
      y
    }
  }
}
```
The console output is:
```json
{
  "data": {
    "createFoo": {
      "id": "cjoopxvxv000d0815gyi8hny1",
      "bars": null
    }
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:cjoopxvuc000b0815mca49yv9",
      "path": [
        "createFoo",
        "bars"
      ],
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "requestId": "local:api:cjoopxvuc000b0815mca49yv9"
    }
  ]
}
```

`docker-compose logs` output:
[foobar.log](https://github.com/prisma/prisma/files/2596884/foobar.log)

**Versions (please complete the following information):**
 - OS: `Ubuntu 18.04` 
 - `prisma` CLI: prisma/1.20.7 (linux-x64) node-v10.13.0`

**Comment by bappr** [comment]
Getting the same issue.
Using `prisma 1.22-alpha`

**Comment by do4gr** [comment]
Thanks for reporting this, I'll look into it.

**Comment by do4gr** [comment]
This should be fixed in the latest alpha version. You can use `docker-compose pull` followed by `docker-compose up -d` to restart the prisma version with the latest docker image.
