### ISSUE TITLE
Passive connector should not delete database when you run `prisma delete`

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma#3563]
**Describe the bug**
Currently running `prisma delete` will delete the underlying database, both for active and passive connectors. This is wrong, as the passive connector should only delete the service from Prisma, and leave the underlying database intact.

**Additional context**
CLI docs for [prisma delete](https://www.prisma.io/docs/reference/cli-command-reference/database-service/prisma-delete-eizai4ahno)

**Comment by do4gr** [comment]
This has been fixed.
