### ISSUE TITLE
Prisma never connects to MySql whereas in documentation it is claimed that it supports MySql

### ISSUE THREAD

**Issue by mrimran** [prisma/prisma#3571]
I see following on terminal when I try to connect to MySql database on my local system.
```
$ prisma init localmysqldb
? Set up a new Prisma server or deploy to an existing server? Use existing datab
ase
? What kind of database do you want to deploy to? MySQL
? Does your database contain existing data? No
? Enter database host localhost
? Enter database port 3306
? Enter database user root
? Enter database password root

Connecting to database !
 ▸    Could not connect to database. Connection terminated unexpectedly

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ export DEBUG="*"

```

Even when I tried to connect with a Heroku MySql database the terminal enters into never ending process.

Here is my Prisma version information:
```
$ prisma --version
prisma/1.20.7 (linux-x64) node-v9.5.0

```
Here is MySql version 
`mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper`

Please don't claim something until it doesn't work or share the solution to fix it.

**Comment by divyenduz** [comment]
@mrimran : You are trying to connect docker container to host mysql i.e. in place of localhost you need to give the IP of your host machine. Please let me know if that works. 

Or you can use the `docker-compose.yml` file generated by the [getting started workflow](https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-JAVASCRIPT-a002/). 

We do support MySQL, Postgres and even MongoDB is in preview now. Getting started experience can be used to set up either of these with docker. 

Please let me know if you have further questions, if you are satisfied, feel free to close this issue. 

Thanks.

**Comment by divyenduz** [comment]
I am closing this one. Please re-open if you think that there is still an issue. Thanks.

**Comment by evilantnie** [comment]
Just want to comment that I believe this ticket is correctly outlining a bug, i've actually run into the same issue mysql. If you look at your code here:

https://github.com/prisma/prisma/blob/1.25.4/cli/packages/prisma-cli-core/src/utils/EndpointDialog.ts#L368

The "if" statement only distinguishes between a mongo connector and the postgres connector. So it's misleading to go through the init steps and ask for mysql connection details when they aren't used.

It looks like there isn't any support for connecting to an existing mysql database (with or without data), so it probably makes sense to remove that path from the init workflow to me.
