### ISSUE TITLE
vercel/pkg errors on windows

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#3572]
NOTE: This is a "draft issue", so it may not be actionable at this time. See below for more info.

## Bug description

```
+ ./cli.exe --version
Error: Command failed with ENOENT: D:\snapshot\node_modules\@prisma\cli\introspection-engine-windows.exe --version
spawn D:\snapshot\node_modules\@prisma\cli\introspection-engine-windows.exe ENOENT
```

## How to reproduce

NOTE: This only happens on GitHub Actions right now.
NOTE: I don't know when this bug was introduced yet, because of [another bug](https://github.com/prisma/prisma/issues/3571).

```
npm i @prisma/cli
npm i -g pkg
pkg node_modules/@prisma/cli -t node12-win
./cli.exe version
```

Also see https://github.com/prisma/e2e-tests/runs/1092141690

## Expected behavior

no error

## Prisma information

--

## Environment & setup

--

**Comment by yoshuawuyts** [comment]
Anna from Node core recently ended up creating a bundler for MongoDB because of issues with other bundlers. In case the Windows issue proves difficult to solve, perhaps https://github.com/mongodb-js/boxednode may be helpful.

**Comment by steebchen** [comment]
Thanks @yoshuawuyts, I'll give that a try this week

**Comment by steebchen** [comment]
Unfortunately, `boxednode` didn't work for me. I believe it doesn't pack in other files yet and can just pick up a single binary.

**Comment by yoshuawuyts** [comment]
> I believe it doesn't pack in other files yet and can just pick up a single binary.

@steebchen not sure I quite follow; can you elaborate on the issue?

**Comment by steebchen** [comment]
Compiling @prisma/cli works but results in this error:


```
❯ ./example --version
node:internal/modules/cjs/loader:903
  throw err;
  ^

Error: Cannot find module '../package.json'
Require stack:
- /Users/prisma/prisma/prisma-client-go/binaries/build/example
```

I realised that the readme says:

> Not supported
> - Multiple JS files

So this is probably out of scope for our use case.

**Comment by yoshuawuyts** [comment]
Ah yeah, it seems you need to use a bundler to concat it into a single file before running boxed node. There should be ways of including a binary through this as well, but then this probably needs a build matrix too. Thinking this through this def sounds trickier than expected, but is probably a requirement for all single-binary creations.

**Comment by steebchen** [comment]
This is the reason I'm using `pkg` currently, since it just magically picks up everything without any extra steps needed and just works (well, except for this specific issue, but it looks like a specific commit in @prisma/cli broke the built binary on windows). The command is really just `pkg node_modules/@prisma/cli` and that's it.
