### ISSUE TITLE
ConversionError when mediumint column is null

### ISSUE THREAD

**Issue by WesCossick** [prisma/prisma#3576]
## Bug description

Prisma throws a `ConversionError` when attempting to retrieve rows from a MySQL database if one of the columns is of type `mediumint` and a row contains a `NULL` value in that column.

## How to reproduce

Create a table that has a column with type `mediumint`. Insert at least one row with `NULL` in the `mediumint` column. Then, use the `.findMany()` function to attempt to retrieve data:

```sql
CREATE TABLE `items` (
  `item_id` int(10) UNSIGNED NOT NULL,
  `problematic_column` mediumint(8) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `items`
  ADD PRIMARY KEY (`item_id`);
```

```sql
INSERT INTO `items` SET `item_id` = 123, `problematic_column` = NULL;
```

```
model Item {
  @@map("items")

  id                Int  @id @map("item_id")
  problematicColumn Int? @map("problematic_column")
}
```

```ts
await prisma.item.findMany();
```

## Expected behavior

No error; `NULL` values in the `mediumint` column should be retrieved like `NULL` values in other column types.

## Prisma information

Client Version 2.5.1
Engine Version c88925ce44a9b89b4351aec85ba6a28979d2658e

## Environment & setup

- OS: Debian
- Database: MySQL 5.7
- Node.js version: Node.js v12
- Prisma version: _see above_

## Other notes

See https://github.com/prisma/prisma/discussions/3537 for a full discussion of the issue.

**Comment by WesCossick** [comment]
An example of the error message it throws:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConversionError(Conversion failed: Value of type Column { payload: [3, 100, 101, 102, 5, 108, 111, 99, 97, 108, 12, 116, 114, 97, 110, 115, 97, 99, 116, 105, 111, 110, 115, 12, 116, 114, 97, 110, 115, 97, 99, 116, 105, 111, 110, 115, 14, 105, 110, 118, 111, 105, 99, 101, 95, 110, 117, 109, 98, 101, 114, 14, 105, 110, 118, 111, 105, 99, 101, 95, 110, 117, 109, 98, 101, 114, 12, 63, 0, 8, 0, 0, 0, 9, 40, 64, 0, 0, 0], schema: (5, 5), table: (11, 12), org_table: (24, 12), name: (37, 14), org_name: (52, 14), column_length: 8, character_set: 63, flags: MULTIPLE_KEY_FLAG | UNSIGNED_FLAG | PART_KEY_FLAG, column_type: MYSQL_TYPE_INT24, decimals: 0 } is not supported with the current configuration) })
    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:1:226583)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by WesCossick** [comment]
Hmmm. I may have boiled the "how to reproduce" down too far versus what we discussed in https://github.com/prisma/prisma/discussions/3537. I'm investigating further to see what needs to change to trigger the error.

**Comment by WesCossick** [comment]
Okay, so it looks like the problem isn't if the `mediumint` column _has_ an integer, it's if the column is set to `NULL`. I've updated the "how to reproduce" section above accordingly.

**Comment by janpio** [comment]
I could reproduce the issue in this PR to our integration tests: https://github.com/prisma/prisma/pull/3583 👍

**Comment by pimeys** [comment]
Whoops. Was an easy fix, merging later today: https://github.com/prisma/prisma-engines/pull/1113
