### ISSUE TITLE
Unsupported column types throw cryptic error message

### ISSUE THREAD

**Issue by WesCossick** [prisma/prisma#3577]
## Bug description

Prisma throws a cryptic `ConversionError` when it encounters a column type it does not support, like `mediumint` (see #3576).

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConversionError(Conversion failed: Value of type Column { payload: [3, 100, 101, 102, 5, 108, 111, 99, 97, 108, 12, 116, 114, 97, 110, 115, 97, 99, 116, 105, 111, 110, 115, 12, 116, 114, 97, 110, 115, 97, 99, 116, 105, 111, 110, 115, 14, 105, 110, 118, 111, 105, 99, 101, 95, 110, 117, 109, 98, 101, 114, 14, 105, 110, 118, 111, 105, 99, 101, 95, 110, 117, 109, 98, 101, 114, 12, 63, 0, 8, 0, 0, 0, 9, 40, 64, 0, 0, 0], schema: (5, 5), table: (11, 12), org_table: (24, 12), name: (37, 14), org_name: (52, 14), column_length: 8, character_set: 63, flags: MULTIPLE_KEY_FLAG | UNSIGNED_FLAG | PART_KEY_FLAG, column_type: MYSQL_TYPE_INT24, decimals: 0 } is not supported with the current configuration) })
    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:1:226583)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## How to reproduce

Follow steps in #3576 (so long as that bug has not been fixed, yet). Otherwise, create a table with a column type that's unsupported, insert at least one row, and use the `.findMany()` function to attempt to retrieve data.

## Expected behavior

Since this is an error that's bound to occur from time-to-time, a more helpful error message should be displayed instead. For example, "Prisma does not currently support the column type `mediumint` for MySQL."

## Prisma information

Client Version 2.5.1
Engine Version c88925ce44a9b89b4351aec85ba6a28979d2658e

## Environment & setup

- OS: Debian
- Database: MySQL 5.7
- Node.js version: Node.js v12
- Prisma version: _see above_

## Other notes

See https://github.com/prisma/prisma/discussions/3537 for a full discussion of the issue.

**Comment by janpio** [comment]
This highly depends on the outcome of https://github.com/prisma/prisma/issues/3576 as there by default should be no "unsupported column types" at all. Depending on what we find out there this here needs a) a better error message indeed or b) will not be reachable at all and make this issue moot. Let's see.

**Comment by WesCossick** [comment]
Upon further investigation in #3576, it appears that `mediumint` columns are at least partially supported, as long as they don't contain `NULL` values. The error message is still cryptic, and therefore may still need addressing.

**Comment by pimeys** [comment]
Fixed in https://github.com/prisma/prisma-engines/pull/1113
