### ISSUE TITLE
Unable to connect Prisma to Postgres via Google VPC/NAT

### ISSUE THREAD

**Issue by seanemmer** [prisma/prisma#3578]
#2892  Bug description

Unable to connect Prisma to Postgres via Google VPC/NAT

## How to reproduce

This is an infrastructure issue so may be difficult to reproduce using purely code.  I am successfully running Prisma in a Google Cloud Function.  I am attempting to route the function egress through a GCP VPC network, which is connected via Google Cloud NAT to the public internet as per the guide below:

https://cloud.google.com/functions/docs/networking/network-settings

## Expected behavior

When running a basic prisma findOne method, I receive the following error:

Error: Error in connector: Error creating a database connection. (Operation timed out (mobc timeout))

I am successfully able to access the public internet inside of this function, so I believe the error is specific to the DB connector.

## Prisma information

Version 2.4.0

## Environment & setup

Google Cloud Functions, PostGresql 12, Node 10
Prisma 2.4.0

**Comment by janpio** [comment]
Did you ever figure this out @seanemmer? If not, can you try with the most recent version again - it should have much better error message now.

**Comment by seanemmer** [comment]
Ok - I won't be able to test this for a couple of weeks so it's cool to
close and I'll reopen if it persists :)

**Comment by janpio** [comment]
Happy to keep around until you had the time - or we find this issue again in a few months and _then_ close it :D

**Comment by pantharshit00** [comment]
I found this again and I will close it this time. 

If anyone else have trouble with this, please reply here
