### ISSUE TITLE
Incorrect SQL generated for Json field { equals: null } filter

### ISSUE THREAD

**Issue by timleslie** [prisma/prisma#3579]
## Bug description

When running a query on a JSON field using `{ equals: null }` in the filter I get the wrong values returned. Investigating the debug logs it appears that Prisma is generating incorrect SQL.

#### `schema.prisma`

```
datasource postgresql {
  url      = env("DATABASE_URL")
  provider = "postgresql"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id       Int     @id @default(autoincrement())
  name     String?
  image    Json?
}
```

#### index.ts

````js
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient({ log: ["query"] });

async function main() {
  const user1 = await prisma.user.create({
    data: { name: "Alice", image: '{"foo":"bar"}' },
  });
  const user2 = await prisma.user.create({
    data: { name: "Bob", image: null },
  });
  console.log({ user1, user2 });
  const nullImages = await prisma.user.findMany({
    where: { image: { equals: null } },
  });
  console.log("Users with a null image: (expect ['Bob'])", nullImages);
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.disconnect();
  });
````

## Expected behavior

When running this script I would expect the `findMany` query to find the user `Bob`. Instead, with full debug output on I see the following:

```
{ user1: { id: 7, name: 'Alice', image: '{"foo":"bar"}' },
  user2: { id: 8, name: 'Bob', image: null } }
  prisma-client Prisma Client call: +12ms
  prisma-client prisma.user.findMany({
  prisma-client   where: {
  prisma-client     image: {
  prisma-client       equals: null
  prisma-client     }
  prisma-client   }
  prisma-client }) +0ms
  prisma-client Generated request: +1ms
  prisma-client query {
  prisma-client   findManyUser(where: {
  prisma-client     image: {
  prisma-client       equals: "null"
  prisma-client     }
  prisma-client   }) {
  prisma-client     id
  prisma-client     name
  prisma-client     image
  prisma-client   }
  prisma-client }
  prisma-client  +0ms
  engine stdout { timestamp: 'Sep 10 10:39:28.191',
  level: 'INFO',
  target: 'quaint::connector::metrics',
  fields:
   { query:
      'SELECT "prisma-issue"."User"."id", "prisma-issue"."User"."name", "prisma-issue"."User"."image" FROM "prisma-issue"."User" WHERE "prisma-issue"."User"."image"::jsonb = $1 OFFSET $2',
     item_type: 'query',
     params: '[null,0]',
     duration_ms: 0,
     result: 'success' } } +6ms
prisma:query SELECT "prisma-issue"."User"."id", "prisma-issue"."User"."name", "prisma-issue"."User"."image" FROM "prisma-issue"."User" WHERE "prisma-issue"."User"."image"::jsonb = $1 OFFSET $2
Users with a null image: (expect ['Bob']) []
```

I would expect the generated SQL query to be `WHERE "prisma-issue"."User"."image"::jsonb IS NULL`, which I have verified returns the correct items.

## Environment & setup

- OS: OSX `10.15.5`
- Database: `psql (PostgreSQL) 12.2`
- Node.js version: `v12.11.0`
- Prisma version: `2.7.0-dev.40`

**Comment by pantharshit00** [comment]
I can confirm this. It another case of `NULL != NULL` in SQL.

**Comment by pimeys** [comment]
This looks like a bug in our javascript code. What it does here (regarding the logs) is a conversion from `null` -> `"null"`, and the query then looks for a string that is null.

I'm playing with the Rust engine directly, and I couldn't reproduce it. Would be great if @timsuchanek could check what the translation does.

**Comment by matthewmueller** [comment]
Hey @timleslie, we're currently discussing how to deal with this issue.

This one is a bit tricky because there are two types of nulls you can have for JSON fields. `NULL` in SQL and `null` in the JSON field.

We're tempted to disable the `jsonField: null` shorthand to avoid any confusion around this ambiguity and instead introduce operations to deal with it.

**This API will change**, but something like:

```json
{
  image: {
    equals: null // JSON field with null value
    is: null // SQL is null case
  }
}
```

Do you like this explicitness or do you prefer we keep the shorthand?

**Comment by timleslie** [comment]
I think the proposed API change makes sense. I'm generally in favour of explicit over implicit, so I think having to explicitly indicate which type of `null` check you want (`is`/`valueEquals`) and removing the shorthand `image: null` option will avoid confusion. It also help raise awareness that this is a thing that devs need to consider when checking for `null` in a `Json` field.
