### ISSUE TITLE
On running generator 'graphql-schema' no information about running it prints in the console

### ISSUE THREAD

**Issue by SilencerWeb** [prisma/prisma#3584]
**Describe the bug**
When I run a command for generating Prisma assets (or Prisma Client) using `graphql-schema` generator, I don't get a message about running it in the console. But for such generators as `javascript-client` and `typescript-client` I get the message about their running (e.g. `Saving Prisma Client (JavaScript) at /Users/appleuser/Documents/work/eslint-config/eslint-config-api/src/generated`) which makes it's all confusing for me: seems like these 2 generators run perfectly but `graphql-schema` does not since there is no information about it.

**To Reproduce**
1. Add generator `graphql-schema` to your `prisma.yml`.
2. Run `prisma generate`.

**Expected behavior**
Should be printed to the console the message like `Saving Prisma Client (GraphQL) at /Users/appleuser/Documents/work/eslint-config/eslint-config-api/src/generated`.

**Screenshots**
![image](https://user-images.githubusercontent.com/20713191/48905219-c13d9d80-ee82-11e8-968c-feb076ea769d.png)

**Versions (please complete the following information):**
 - OS: macOS Mojave
 - `prisma` CLI: prisma/1.20.7 (darwin-x64) node-v11.0.0
 - Prisma Server: 1.20.7
 - `"graphql-yoga": "^1.16.7"`, `"prisma-client-lib": "^1.20.7"`, `"graphql": "^14.0.2"`

**Comment by divyenduz** [comment]
The output of the command can be 

`Saving Prisma GraphQL schema (SDL) at <path>`

**Comment by divyenduz** [comment]
This is available in the latest `beta` - `1.27.0-beta.12`, please install it via `npm install -g prisma@beta`.

**Comment by divyenduz** [comment]
This is available in the latest `stable` - `1.28.0`, please install it via `npm install -g prisma`.
