### ISSUE TITLE
Integration tests for CLI `introspect` with `--force`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3592]
https://github.com/prisma/prisma/issues/3591 shows that we are not fully testing `introspect` and its functionality on a CLI level.

Per @Jolg42 we have tests, but those use the Introspect internals:
https://github.com/prisma/prisma/blob/a6a4591136eeb324c8a10d49458505289ecb030d/src/packages/introspection/src/__tests__/introspect.test.ts#L18-L29

1. Write a test with the Introspection internals that actually needs to use `--force` and tests if that functionality works
1. Write integration tests that really use the CLI as a user would

**Comment by Jolg42** [comment]
It's tested since "a while", new test file location https://github.com/prisma/prisma/blob/39a633817dc7568fbb1bb408d4c5a175f495b206/src/packages/migrate/src/__tests__/DbPull.test.ts#L1
