### ISSUE TITLE
Field must have a sub selection

### ISSUE THREAD

**Issue by vctormb** [prisma/prisma#3594]
**Describe the bug**
I have a graphql server using prisma inside the context object. 
When I try to use a `connection` query in the playground I receive the following message: `Field must have a sub selection`

**For example:** I have the following resolver  
```
const productsConnection = async (parent, args, context) => {
  return await context.prisma.productsConnection({
    ...args,
  });
};
```

When I call this resolver inside the playground, I receive this error:  
```
query ProductsConnection {
  productsConnection {
    edges {
      cursor
    }
  }
}
```

![image](https://user-images.githubusercontent.com/13953703/48984855-60170380-f0e8-11e8-80bf-f961aea5b16f.png)

datamodel is very simple:
```
type Product {
  id: ID! @unique
  imageUrl: String!
  title: String!
  price: Float!
}
```

**To Reproduce**
1. Create a resolver calling a connection query

**Expected behavior**
To see the results without any error.

**Versions (please complete the following information):**
```
"apollo-server": "^2.2.2",
"graphql": "^14.0.2",
"prisma-client-lib": "^1.21.0"
```

**Comment by timsuchanek** [comment]
Thanks for reporting @vctormb for reporting! How does your datamodel look like?
I suspect that the type `Product` doesn't have any scalar field and the subselection generation is broken for that case.

**Comment by vctormb** [comment]
@timsuchanek It's very simple. I've updated the issue with the datamodel.

**Comment by timsuchanek** [comment]
Thanks! Closing this in favor of #3309, as it's a duplicate.

**Comment by vadim-shilov** [comment]
Hello!
What about this case?

The type UserType has only scalar fields:
`
type UserType {
  id: ID! @unique
  code: String! @unique
  name: String
  description: String
  createdAt: DateTime!
  updatedAt: DateTime!
}`

The UserType resolver looks like this:
`module.exports = {
  Query: {
    ...
    getUserTypesConnection(root, params, context, info) {
      return context.prisma.userTypesConnection(params);
    },
    ...
  }
};`

I receive the same error when sending the request below:
`query {
  getUserTypesConnection {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        code
      }
      cursor
    }
    aggregate {
      count
    }
  }
}`

Am I doing something wrong?

Thanks
