### ISSUE TITLE
Initial service seeding should be performed after post-deploy hooks were invoked

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3596]
When seeding a service with initial data using the `seed` property in prisma.yml, the seeding currently gets invoked _before_ `post-deploy` hooks are invoked.

This is problematic for cases where the seeding is based on a script that uses the Prisma client and the client generation happens in a `post-deploy` hook. In that case, the Prisma CLI tries to invoke the seeding before the client was generated.

I suggest the following order:
1. run `prisma deploy`
1. create/update Prisma service on the the server
1. invoke `post-deploy` hooks
1. invoke seeding based on `seed` property

Also note that this is related to https://github.com/prisma/prisma/issues/3579.

**Comment by divyenduz** [comment]
This is available in the latest version `1.25.0`, `npm install -g prisma`. I am closing this issue. Please let me know if the issue still persists via opening a new issue.

**Comment by ajainvivek** [comment]
@divyenduz @nikolasburk How about seeding generated prisma client is that available as part of release `1.25.0` 
reference: https://github.com/prisma/prisma-examples/blob/master/typescript/script/prisma/seed.ts
