### ISSUE TITLE
Relay Subscription on edges giving error.

### ISSUE THREAD

**Issue by ankit5174** [prisma/prisma#3606]
**Describe the bug**
Have a schema USER which has a field addressess. The field addressess is a list of address[type address] associated with User. I have created a subscription, whenever a new user is created i should be able to get the new user details along with the address and display it. However I am getting the below error 

Cannot query field 'edges' on type 'Address'. (line 7, column 9):↵        edges {↵        ^"

Note the field addressess in USER is of types AddressConnection. Therefore the relay compiler is not giving any error.
The subscription schema is as below: 

```graphql
subscription userSubscription {
  User(filter: {mutation_in: [CREATED]}) {
    mutation
    node {
      name
      addresses {
        edges {
          node {
            pincode
            id
          }
        }
      }
      id
    }
  }
}
```

**To Reproduce**
1. Go to https://gitlab.com/ankit5174/relay-subscription-example and clone this app
2. Install and start the project using npm start
3. Go to chrome =>localhost:3000 => f12 => network =>WS => Frames
4. See error in payload as 
`Cannot query field 'edges' on type 'Address'. (line 7, column 9):↵        edges {↵        ^"`

**Expected behavior**
A proper Connection of Web socket should be established

**Screenshots**
![](https://i.ibb.co/C5xD0fW/error.png)

**Versions
 - OS: ``Windows 10`

**Comment by pantharshit00** [comment]
Hi @ankit5174 

Sorry for a very late reply. 

Looks like you are using the query improperly, for relational stuff you don't any relay styled pagination structure. You can directly query them like so:
![image](https://user-images.githubusercontent.com/22195362/55562670-12ec1380-5712-11e9-9abb-e6278d3a38e2.png)


So use the following query:
```
subscription userSubscription {
  User(filter: {mutation_in: [CREATED]}) {
    mutation
    node {
      name
      addresses {
        pincode
        id
      }
      id
    }
  }
}
```
