### ISSUE TITLE
Introspection Mapping to Existing Database (Relation with Extra Columns) returns SQL Error

### ISSUE THREAD

**Issue by epitaphmike** [prisma/prisma#3614]
I am looking at the docs (https://www.prisma.io/docs/data-model-and-migrations/introspection-mapping-to-existing-db-soi1/), because I am having an issue with a specific join type. 

Similar to what is in the docs here

```graphql
type Bill @pgTable(name: "bill") {
  bill: String!
  id: Int! @unique
  bill_products: [Bill_product]
}

type Bill_product @pgTable(name: "bill_product") {
  bill: Bill @pgRelation(column: "bill_id")
  product: Product @pgRelation(column: "product_id")
  some_other_column: String!
}

type Product @pgTable(name: "product") {
  id: Int! @unique
  product: String!
  bill_products: [Bill_product]
}
```
I am trying to access `some_other_column` data when I query

```graphql
query {
  bill(where: { id: 1 }){
    id
    bill_products {
      product {
        id
        product
      }
      some_other_column
    }
  }
}

```

When I run the SQL from the docs, add the types to my `app.prisma` file then run `prisma deploy` I get 3 errors

```bash
Bill_product ✖ The required field 'id' is missing and has to have the format: id: ID! @unique or id: UUID! @unique or id: Int! @unique.

Bill ✖ The relation field ‘bill_products’ has the wrong format: ‘[Bill_product]’ Possible Formats
: ‘Bill_Product’, ‘Bill_product!‘, ‘[Bill_product!]\!’

Products ✖ The relation field ‘bill_products’ has the wrong format: ‘[Bill_product]’ Possible Formats
: ‘Bill_Product’, ‘Bill_product!‘, ‘[Bill_product!]\!’
```

When I resolve these 3 errors and run `prisma deploy` all is well

When I try to query

```graphql
query {
  bill(where: { id: 1 }){
    id
    bill_products {
      product {
        id
        product
      }
      some_other_column
    }
  }
}
```

I get errors in PostgreSQL

```sql
ERROR:  column Alias.id does not exist at character 217
STATEMENT:  select 
  "Alias"."id", 
  "RelationTable"."id" as "__RelatedModel__", 
  "RelationTable"."bill_id" as "__ParentModel__"
from "public"."bill_product" as "Alias"
  join "public"."bill_product" as "RelationTable"
  on "Alias"."id" = "RelationTable"."id"
where "RelationTable"."bill_id" in ($1)
order by "RelationTable"."id" asc
```

**Versions:**
 - OS: `OS X High Sierra`
 - `prisma` CLI: prisma/1.20.7 (darwin-x64) node-v10.10.0
 - Prisma Server: `1.19`
 - `graphql-cli`, `prisma-binding`

**Comment by mavilein** [comment]
@epitaphmike : This is a current limitation of the Postgres connector. The connector requires each specified type to be backed by a table that has an id column. In your example `Bill_product` seems to be a relation table which does not have an id column. We are currently working on lifting this limitation.

**Comment by epitaphmike** [comment]
> In your example Bill_product seems to be a relation table which does not have an id column.

Thanks @mavilein. I do want to point out that this isn't my example. This is an example from the Prisma Docs under `Relations in the generated datamodel > Relation Tables`. 
https://www.prisma.io/docs/data-model-and-migrations/introspection-mapping-to-existing-db-soi1/#relations-in-the-generated-datamodel

**Comment by mavilein** [comment]
@epitaphmike : Oh i wans't aware that it is documented like that. This does not work right now. As i said i am on it though :-)

**Comment by epitaphmike** [comment]
Thanks @mavilein. If there is anything I can do to assist please let me know.
