### ISSUE TITLE
Investigate live reload of Prisma Client with `next dev`

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#3615]
If I have a Next.js project running with Prisma Client and have a change in the `schema.prisma` file, then generated a new Client with `prisma generate`, it would be great, if I don't have to restart the `next dev` process.

Probably clearing the require cache with some code like this would be necessary:

```ts
delete require.cache[require.resolve(clientDir)]
delete require.cache[clientDir]
```

As of now I need to restart the `next dev` process by hand, which is a bit cumbersome.

**Comment by flybayer** [comment]
This is also a main UX issue with Prisma in Blitz. Would be awesome to have this fixed!!

**Comment by williamluke4** [comment]
An Example, Just to clarify
1. **Terminal 1**`blitz start`
1. **Terminal 2**`blitz generate all tag name:string`
1. **Terminal 2**`blitz db migrate`
    These run under the hood
    1. `prisma migrate save --experimental`
    1. `prisma migrate up --experimental`
    1. `prisma generate`
1.  **Terminal 1** Restart `blitz start`
Am I correct in say that this is what you want to be improved

**Comment by flybayer** [comment]
@williamluke4 yes, step 4 should not be needed

**Comment by flybayer** [comment]
There's another issue to consider along with this, that I should have mentioned earlier.

We have to have the following code in our `db/index.ts` file. 

```ts
import { PrismaClient } from "@prisma/client"
export * from "@prisma/client"

let prisma: PrismaClient

if (process.env.NODE_ENV === "production") {
    prisma = new PrismaClient()
} else {
    // Ensure the prisma instance is re-used during hot-reloading
    // Otherwise, a new client will be created on every reload
    globalThis["prisma"] = globalThis["prisma"] || new PrismaClient()
    prisma = globalThis["prisma"]
}

export default prisma
```

Because without that, users get this error after awhile of working on a hot (lots of hot module reloads, etc).

```
Error in connector: Error querying the database: db error: FATAL: sorry, too many clients already
```

It would be amazing to not have to do this.

**Comment by williamluke4** [comment]
@flybayer Yeah, I read through that code yesterday and tried the same thing. I'll have a deeper look at it to that once we have this sorted. 
I've been trying to configure webpack in `next.config.js` to pick up changes to `node_modules/.prisma/client` and have also tried using chokidar to flush the require cache every time it detects changes to `node_modules/.prisma/client` but no luck so far. I'll keep you updated on progress :)

**Comment by flybayer** [comment]
@williamluke4 I tried experimenting with [webpack-clear-require-cache-plugin](https://www.npmjs.com/package/webpack-clear-require-cache-plugin) but no luck there either. Seems to be some issue with how webpack/Next are using the require cache.

**Comment by williamluke4** [comment]
Hey @flybayer @timsuchanek  check out [next-prisma-plugin](https://github.com/williamluke4/next-prisma-plugin). It's still pretty rough around the edges but it works. The only thing it does not do is refresh the page automatically. Let me know your thoughts/ideas

**Comment by harmandeep-singh** [comment]
Hi , Any one try in Typescript , its giving me an error , Please let me know. : 

```
 globalThis['prisma'] = globalThis['prisma'] || new PrismaClient();
prisma = globalThis['prisma'];
```

Error : Element implicitly has an 'any' type because expression of type '"prisma"' can't be used to index type 'typeof globalThis'.
Property 'prisma' does not exist on type 'typeof globalThis'.

**Comment by rvaronos** [comment]
@williamluke4  

I installed the next-prisma-plugin  but I am getting a webpack 5 validation error with Next.js 11. 
I believe this issue should be reopened?

**Comment by pantharshit00** [comment]
@rvaronos Open a new issue instead.

**Comment by forrestwilkins** [comment]
@harmandeep-singh Were you ever able to resolve this?

**Comment by harmandeep-singh** [comment]
> @harmandeep-singh Were you ever able to resolve this?

Hi. @forrestwilkins : I think fixed it by casting to any : ` (globalThis as any)["prisma"]`
