### ISSUE TITLE
Bulk API

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#3619]
Many scenarios require the insertion of a lot of data in bulk where using Prisma's normal create operations are too slow. For cases like these we should add a dedicated bulk API which probably also will become its own query capability.

**Comment by andrejunges** [comment]
@janpio is a bulk API on the roadmap? this would be an amazing addition.

**Comment by xiaoyu-tamu** [comment]
+1

**Comment by pantharshit00** [comment]
We have a createMany operation now: https://www.prisma.io/docs/concepts/components/prisma-client/crud#create-multiple-records

This issue can be closed now.

**Comment by xiaoyu-tamu** [comment]
what about upsertMany? is it on prisma roadmap?

**Comment by pantharshit00** [comment]
@xiaoyu-tamu Follow https://github.com/prisma/prisma/issues/4134 for upsertMany


Right now you can workaround that by filtering with `findMany` and then creating non existent records with `createMany`
