### ISSUE TITLE
Set default of a relationship

### ISSUE THREAD

**Issue by siberian-man** [prisma/prisma#3621]
Lets assume we have the following models:

```
model User {
  id                    ID
  name             String
  createdEvents         Event[]     @relation(name: "userIsCreatorOfEvent")
  organisedEvents       Event[]     @relation(name: "userIsOrganiserOfEvent")
}

model Event {
  id                    ID
  name                  String
  creator               User        @relation(name: "userIsCreatorOfEvent")
  organiser             User        @relation(name: "userIsOrganiserOfEvent")
}
```

I would like to be able to specify that organiser should default to creator. For example:

```
organiser User @relation(name: "userIsOrganiserOfEvent") default(creator)
```

**Comment by janpio** [comment]
This is actually possible with the current way Prisma ORM now defines relations:

```
model User {
  id              String  @id
  name            String
  createdEvents   Event[] @relation(name: "userIsCreatorOfEvent")
  organisedEvents Event[] @relation(name: "userIsOrganiserOfEvent")
}

model Event {
  id         String @id
  name       String
  creatorId  String @default("bar")
  creatorId2 String @default("foo")
  creator    User   @relation(name: "userIsCreatorOfEvent", fields: [creatorId], references: [id])
  organiser  User   @relation(name: "userIsOrganiserOfEvent", fields: [creatorId2], references: [id])
}
```

So just use `@default` on the relation scalar field of the relation with the default "foreign key" value you want to set when a new `Event` is created.

**Comment by stackfuldev** [comment]
@janpio cool! But not what I wanted here, in fact. My goal was to be able to make event.organiser optional and set it to what user.creator points to, if value for user.organiser is not provided. Thus, it's like a dynamic default value, not static.

**Comment by stackfuldev** [comment]
FYI I changed my Github account, but it was my question.

**Comment by stackfuldev** [comment]
@janpio yes, exactly

**Comment by janpio** [comment]
Interesting. 
I don't think that would be something that could be modelled in a database, correct?
Could you maybe solve this in your code before sending the query?

**Comment by stackfuldev** [comment]
@janpio Yes, that's what I do. I imagined it being implemented on Prisma client level. On DB level it could be still a required field. In other words, DB schema could require the field, but if entity is created via Prisma client, a user could provide just the first field, but the second one would default to the first one, while still allowed to be provided, if user needs it.

Also, in fact, at least in regards to PostgreSQL, this seem to be possible with Generated columns:
https://www.postgresql.org/docs/current/ddl-generated-columns.html
