### ISSUE TITLE
Hoist provider names to top level

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#3624]
Originally raised on [team slack ](https://prisma-company.slack.com/archives/CEYCG2MCN/p1570737180059700).

```hcl
generator photonjs {
  provider = "photonjs"
}
```

We currently use an [HCL](https://github.com/hashicorp/hcl) ish design.

But what if we had `generator <provider name>`. What would that win/lose?

### Implicitly Named Blocks

This is a new feature. When the user does not need to name their block, the default name would be that of the generator.

**Simple**

Before:

```hcl
# name = db

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

# name = photon

generator photon {
  provider = "photonjs"
}
```

After:

```hcl
# name = sqlite

datasource sqlite {
  url = "file:dev.db"
}

# name = photonjs

generator photonjs
```

**More complicated**

Before:

```hcl

# name = db

datasource db {
  enabled  = env("SQLITE_URL")
  provider = "sqlite"
  url      = env("SQLITE_URL")
}

# name = db

datasource db {
  enabled  = env("POSTGRES_URL")
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}
```

After:

```hcl
# name = sqlite

datasource sqlite {
  enabled  = env("SQLITE_URL")
  url      = env("SQLITE_URL")
}

# name = postgresql

datasource postgresql {
  enabled  = env("POSTGRES_URL")
  url      = env("POSTGRES_URL")
}
```

### Explicitly Named Blocks

Before:

```hcl

# name = db

datasource db {
  enabled  = env("SQLITE_URL")
  provider = "sqlite"
  url      = env("SQLITE_URL")
}

# name = db

datasource db {
  enabled  = env("POSTGRES_URL")
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}
```

After:

```hcl
# name = db

datasource sqlite db {
  enabled  = env("SQLITE_URL")
  url      = env("SQLITE_URL")
}

# name = db

datasource postgresql db {
  enabled  = env("POSTGRES_URL")
  url      = env("POSTGRES_URL")
}
```

### Benefits

* Better aligns with the principal that a system should scale gracefully to the user's needs. In this case it is scaling down better.

### Caveats

* I don't fully understand this system, pretty sure I have blind spots not accounted for in this design proposal. Please point them out!

* As this would be a breaking change, if we wanted to go ahead with this idea or a version of it, we might want to see if there are other desirable but breaking changes we want to make that we can bundle into a single release.

**Comment by janpio** [comment]
This ship has sailed it seems, if we ever do this it would be in a future major Prisma version that evolves the schema fundamentally.
