### ISSUE TITLE
Add email scalar type

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#3625]
Seems like it would provide a lot of value to have an [email](https://tools.ietf.org/html/rfc5322#section-3.4) scalar type.

**Comment by janpio** [comment]
With native types we would/could support this if it existed in any of the supported databases.

**Comment by jasonkuhrt** [comment]
Would be cool if a generator could contribute new scalars.

**Comment by pantharshit00** [comment]
Related https://github.com/prisma/prisma/issues/7209

I think we will still need to map generator primitive to a database level type so that engines know how to serialize it.

**Comment by jasonkuhrt** [comment]
Or let generators contribute code that can be run by engines to do serialization/deserialization. No idea how to do that. Assume there is some magical way, WASM, stuff. Still, might be a bad idea to polyfill scalars into DBs.

Yet another angle on this: Do DBs have pluggable custom scalar systems? Then Prisma could just be bridging into those systems, no polyfill needed.
