### ISSUE TITLE
Prisma Client: Opinionated Relay Connection implementation

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma#3629]
## Current problem

So far, `client.*Connection` queries aren't working because all fields of `Connection` types aren't scalar, which causes the client to return an empty selection set.

## Proposal

In order to make `Connection` types working, we should introduce the following opinionated changes:

Given the following datamodel:

```graphql
type User {
  id: ID! @id
  name: String!
}
``` 

Prisma generates the following schema (narrowed down to `Connection` related types):

```graphql
type Query {
  usersConnection(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): UserConnection!
}

type User {
  id: ID!
  name: String!
}

type UserConnection {
  pageInfo: PageInfo!
  edges: [UserEdge]!
  aggregate: UserAggregate!
}

type UserEdge {
  node: User!
  cursor: String!
}

type AggregateAttribute {
  count: Int!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}
```

Based on the schema above, `client.usersConnection(...)` should create the following GraphQL query:

```graphql
{
  usersConnection {
    pageInfo {
	  hasNextPage
	  hasPreviousPage
	  startCursor
	  endCursor
    }
	edges {
	  node {
	    ... # All scalar fields of nodes
	  }
	}
  }
}
```

**Comment by timsuchanek** [comment]
This feature is available in the current beta.

**Comment by divyenduz** [comment]
This is an example repository that demonstrates this API and possible escape hatches to get more information: https://github.com/divyenduz/forum-5355

**Comment by divyenduz** [comment]
This is available in the stable version 1.24 onwards.

**Comment by chrisui** [comment]
@divyenduz Using `1.27.3` I see a root `postsConnection` on `Query` type however I do not see `postsConnection` on my `User` type despite having `type User { posts: [post] }`. Is this expected?

**Comment by divyenduz** [comment]
@chrisui Can you please create a new issue with a minimal reproduction? Here: https://github.com/prisma/prisma/issues/new?template=bug_report.md

Thanks

**Comment by chrisui** [comment]
Thanks @divyenduz, have reported in https://github.com/prisma/prisma/issues/4134
