### ISSUE TITLE
PSL: Information about allowed data length is missing

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3629]
Assume this SQL:

```
CREATE TABLE departments (
    dept_no     CHAR(4)         NOT NULL,
    dept_name   VARCHAR(40)     NOT NULL,
    PRIMARY KEY (dept_no),
    UNIQUE  KEY (dept_name)
);
```

This is introspected to:

```
model departments {
  dept_name String @unique
  dept_no   String @id
}
```

The `String` does not include the information that you can only put 4 characters into `dept_no`. That is problematic as Prisma Client can give no indication if the data you are trying to write is valid or if it will cause an error similar to one of these: https://github.com/prisma/prisma-test-utils/issues/19

**Comment by do4gr** [comment]
Since we now have native types as default this information is now part of the PSL. Do you additionally want validations within the client @janpio or can this be closed?

**Comment by do4gr** [comment]
Client side will be handled via a separate issue.
