### ISSUE TITLE
Prisma Flow client should export Prisma interface

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3630]
The TS client exports the `Prisma` interface that defines all API operations available by the Prisma client. 

The Flow client on the other hand does not export a `Prisma` interface. Additionally, the interface that defines all available API operations is called `PrismaInterface` and not `Prisma`.

Ideally, we can:

1. rename `PrismaInterface` to `Prisma`
1. export the newly named `Prisma` interface

**Comment by timsuchanek** [comment]
This is related to https://github.com/prisma/prisma-examples/issues/310

**Comment by divyenduz** [comment]
This is fixed in beta version `1.25.0-beta.4`. Please give it a go via `npm install -g prisma@beta` and let me know if that works for you. Thanks.
