### ISSUE TITLE
Prisma Flow client should generate types instead of interfaces where possible

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3631]
There's currently a weird issue with the Prisma Flow client that can be observed here: https://github.com/prisma/prisma-examples/blob/master/flow/script/src/script.js#L23

It is currently required to explicitly cast a part of the input object to `createPost` to `UserWhereUniqueInput` in order for the Flow typechecker to succeed. This gets solved if you replace the `UserWhereUniqueInput` type definition from being an interface to a type.

**Comment by morajabi** [comment]
Yes please!

**Comment by divyenduz** [comment]
This is fixed in beta version `1.25.0-beta.4`. Please give it a go via `npm install -g prisma@beta` and let me know if that works for you. Thanks.
