### ISSUE TITLE
schema: env values behaviour

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#3632]
The `url` parameter in a datasource accepts environment variables.

```
datasource db {
	provider = "sqlite"
	url      = env("PG_URL")
}
```

There are a few scenarios how they can be used.

1) Provide PG_URL at generation time.

```
PG_URL=postgresql://localhost:5432 prisma2 generate
```

It's dynamic in a sense that you can provide the environment variable on generation time. While this value would be required to run migrations, it's not necessary at this point, because this step just generates photon clients, and they don't need to know about datasource URLs.

```
prismprisma2@2.0.0-preview018.2, binary version: 3c4da1d6caa0c40a0210a346ec982c77f74e18c7
divyendusingh [next-prisma2]$ prisma2 generate
Error: Schema parsing
error: Environment variable not found: PG_URL.
  -->  schema.prisma:7
   |
 6 |   provider = "postgresql"
 7 |   url      = env("PG_URL")
 8 | }
   |
```

Original bug report for this specific issue: https://github.com/prisma/photonjs/issues/318

2) Provide PG_URL at runtime.

This method allows passing an empty PG_URL value at runtime. It's ignored at generation time. For example, this allows generating the client without having the DB secrets on CI systems, and will allow the user to supply the connection string at runtime. Photon clients will need to implement this behavior.

3) Provide PG_URL at either generation or runtime.

This allows the user to provide it whenever they want to. However, this is more work from our side, as this also needs to be implemented in photon clients.

While analyzing this, a broader question arises: 
At what time do we allow setting the environment variable? At generation time, at runtime, or both? This also affects photon clients.

Depending on that, we may allow or disallow empty environment variables at generation time.

**EDIT**: Currently, it seems photonjs can handle both cases, although providing it at generation time is currently required as the datamodel parser expects it, and we would have to rewrite this if we want to change this behaviour, which we currently don't have the capacity for. 

<img width="474" alt="image" src="https://user-images.githubusercontent.com/5013932/71012137-e1c04180-20ee-11ea-9933-2e1a74f9c4bf.png">

---

Related: https://github.com/prisma/prisma2/issues/800

**Comment by janpio** [comment]
Nothing actionable here any more, closing.
