### ISSUE TITLE
Return Single Object From 1 To Many Relation

### ISSUE THREAD

**Issue by iamandyk** [prisma/prisma#3633]
I find myself continually wanting to query just one record from a 1 To Many relationship. For example, say I have the following schema:

```
model User {
  id            String        @default(cuid()) @id @unique
  email         String        @unique
  name          String
  username      String        @unique
  picture       String
  bio           String
  profile_songs ProfileSong[]
  createdAt     DateTime      @default(now())
  updatedAt     DateTime      @updatedAt
}

model ProfileSong {
  id        String   @default(cuid()) @id @unique
  user      User
  thumbnail String
  url       String
  title     String
  artist    String
  provider  String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

I have a separate model for profile songs because I want to keep a history of all profile songs. However, on the user profile page I only want to display the most recently added profile song which would be the user's active and current profile song.

Currently I am querying for that single, current profile song like so: 

```
const GET_USER_PROFILE = gql`
  query userProfile($where: UserWhereUniqueInput!) {
    user(where: $where) {
      id
      name
      username
      bio
      email
      picture
      profile_songs(last: 1) {
        id
        artist
        title
        url
        thumbnail
      }
    }
  }
`;
```

The problem here is that this returns an array which I then have to access like this: 

```
const profile_song = data.user.profile_songs[0]
```

Perhaps it may be nice to have a way to specify that you only want a single item returned. I am not sure what the best way to do that would look like or if it is even the best idea to do so. There seems to be a somewhat related discussion here: https://github.com/graphql/graphql-js/issues/938

**Comment by janpio** [comment]
Closing this, as we think this is not the most intuitive API behavior as you would still et a list of 1 on the nested query. For top level queries we have `findFirst` now for quite some time.
