### ISSUE TITLE
Syntactical separation of DB level and Prisma level functionality

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#3634]
Based on our current work on database [introspection workflows](https://github.com/prisma/specs/issues/44) we've explored some new requirements which raise [some open questions in regards to how the Prisma schema maps to the underlying DB schema](https://github.com/prisma/specs/issues/304) (both conceptually and syntactically). Since we're dealing with a huge level of complexity (both depth and breadth), it's critical to design and communicate clear concepts and mental models according to our design principles.

An idea to more clearly draw the lines in the schema between which functionality is based on a DB feature vs is a "Prisma-added feature" would be to express this syntactically.

**Comment by pantharshit00** [comment]
Issue is from initial days of Prisma. This is a solved problem now. We use scoped directives for mapping database features like `@db.Uuid`
