### ISSUE TITLE
Homebrew installation should be possible without `brew tap`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3637]
Currently two instructions are required when installing Prisma via Homebrew:

```
brew tap prisma/prisma
brew install prisma
```

The first line should be removed and it should just be possible to install Prisma using `brew install prisma`.

**Comment by mifrej** [comment]
https://www.prisma.io/docs/prisma-cli-and-configuration/using-the-prisma-cli-alx4/#installation
This setup instruction should be updated with the proper commands as above.
