### ISSUE TITLE
sql WITH clause

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma#3643]
I would like to do some folders/files relations and I would like to know if you have planned to add the WITH clause support

https://www.codeproject.com/Articles/818694/SQL-Queries-to-Manage-Hierarchical-or-Parent-child

thanks

**Comment by pantharshit00** [comment]
I think you can use a raw query as a workaround for now.

**Comment by yovanoc** [comment]
Yes thats what i'm trying to do :)

**Comment by albertoperdomo** [comment]
Seems related to https://github.com/prisma/prisma/issues/3643, although WITH could have other users beyond recursive joins.

For now, raw query is the best way to deal with this.

**Comment by pantharshit00** [comment]
@albertoperdomo I guess you linked to wrong issue. It is linked to this same issue right now.

**Comment by albertoperdomo** [comment]
Good catch @pantharshit00 - I was going to link to https://github.com/prisma/prisma/issues/3725.
I will update my comment.

**Comment by janpio** [comment]
I am closing this as a duplicate of https://github.com/prisma/prisma/issues/3725 and https://github.com/prisma/prisma/issues/4562. If there are other `WITH` use cases not covered by thee, please open a new issue for them. Thank you!
