### ISSUE TITLE
`npx prisma introspect` invokes Prisma 1 CLI 

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3644]
It [sometimes happens that users accidentally invoke the Prisma 1 CLI](https://prisma.slack.com/archives/CA491RJH0/p1600028460403900) when running `npx prisma`. Most often, this happens because they did not install the Prisma 2 CLI as a dev dependency which is why `npx` defaults to the [`prisma`](https://www.npmjs.com/package/prisma) package on npm (which contains the Prisma 1 CLI).

To fix this, you should install the Prisma 2 CLI locally:

```
npm install @prisma/cli --save-dev
```

Learn more in the [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-cli/installation#local-installation-recommended).

We could improve the situation by adjusting the Prisma 1 CLI output as mentioned here: https://github.com/prisma/prisma/issues/3452

**Comment by Jolg42** [comment]
Since we publish Prisma 2 CLI to `prisma` package, this issue is fixed.

Prisma 1 CLI can be installed with `prisma1` package.
