### ISSUE TITLE
Add a MySQL integration test in client

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#3646]
Most of the tests here are covering SQLite and 2 are covering PostgreSQL:
- https://github.com/prisma/prisma/tree/master/src/packages/client/src/__tests__/integration/happy/blog-env-postgresql
- https://github.com/prisma/prisma/tree/master/src/packages/client/src/__tests__/integration/happy/insensitive-postgresql

Also both PostgreSQL rely on creating the database from raw SQL. It would be great to have it done by migrate instead.

**Comment by janpio** [comment]
We now have quite a few tests for MySQL as well.
