### ISSUE TITLE
MongoDB: Get author from posts (prisma-client example)

### ISSUE THREAD

**Issue by N44PS** [prisma/prisma#3651]
**Describe the bug**
Hello ! I've been using the MongoDB connector and started with the example of posts and author.
I can't get author from post(s) `Cannot return null for non-nullable type author`

**To Reproduce**
1. Use types schema.graphql
```graphql
scalar DateTime

type Query {
  post(id: ID!): Post
  posts: [Post!]!
  filterPosts(searchString: String): [Post!]!
}

type Mutation {
  createDraft(title: String!, content: String, authorEmail: String!): Post
  deletePost(id: ID!): Post
  publish(id: ID!): Post
}

type Post {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  published: Boolean!
  title: String!
  content: String
  author: User!
}

type Query {
  user(id: ID!): User
  users: [User!]!
}

type Mutation {
  signupUser(email: String!, name: String): User
  deleteUser(id: ID!): User
}

type User {
  id: ID!
  email: String!
  name: String
  posts: [Post!]!
}
```

datamodel.graphql
```graphql
type User {
  id: ID! @id
  email: String! @unique
  name: String
  posts: [Post!]! @relation(link: INLINE)
}

type Post {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  published: Boolean! @default(value: false)
  title: String!
  content: String
  author: User!
}

```

The associated resolver for author of post.

```typescript
import { PostResolvers } from '../generated/graphqlgen';

export const Post: PostResolvers.Type = {
  ...PostResolvers.defaultResolvers,

  author: ({ id }, args, ctx) => ctx.prisma.post({ id }).author(),
};
```

2. `prisma deploy` + `prisma generate` + `graphqlgen`
3. `signupUser` a user, `createDraft` then `publish` it.
4. Query the posts
```graphql
query {
  posts {
    author {
      name
    }
  }
}
```

**Expected behavior**
I should have the list of posts (here juste the one I created) and the associated author.

**Screenshots**
<img width="1439" alt="capture d ecran 2018-12-05 a 15 21 20" src="https://user-images.githubusercontent.com/1702207/49519775-15447b00-f8a2-11e8-8c39-7635192f23fb.png">

**Versions (please complete the following information):**
 - OS: MacOS Mojave 10.14.1
 - `prisma` CLI: 1.22.0
 - Prisma Server: 1.22 (docker)
 - `prisma-client-lib`: 1.22.0
- `graphqlgen`: 0.4.0

**Comment by do4gr** [comment]
Hey @N44PS  thanks for reporting this! 

We just did a 1.22.1 release with a relation fix that should also fix this issue. I'm therefore closing this. Let me know if you still run into this error when running 1.22.1
