### ISSUE TITLE
Turn #3590 into integration tests for these errors

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3654]
#3590 includes 3 failing tests. These should be turned into test s for the triggered errors.

**Comment by janpio** [comment]
Yay! Can you link to the integration tests that correspond to what was in #3590 @eemmiillyy?
Afterwards you can also close that PR draft by the way.

**Comment by eemmiillyy** [comment]
Integration tests have been added for these with (https://github.com/prisma/prisma/pull/3683) in (https://github.com/prisma/prisma/commit/cd8361cf5a1e4c8786f40075db9888e188e701c1#diff-6e4bbddeca93b81ae24c82eaef9bbf5e)
