### ISSUE TITLE
Any Client error message should include the Client version

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3662]
Issues like https://github.com/prisma/prisma/issues/3653 include the `prisma -v` output, but not the Client version that was really executed and cause the error message. We should output the Client version as well.

**Comment by Weakky** [comment]
There are a number of ways the client display errors. Either by simply throwing an error, by logging errors coming from the QE, or by console.logging custom errors. Do we have any idea how we want to display the client version in all these variants?

**Comment by janpio** [comment]
No. This was considered from the direction of "User has an error, posts the output they are getting into a GH issue, should include the version as helpful information". So absolutely open to suggestions where this is possible and helpful at all, and what it should or could look like.
