### ISSUE TITLE
Moving `client` to `cli/packages/prisma-client-lib` directory

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#3665]
In order to leverage the benefits of the yarn workspaces, we should move the `client` directory to `cli/packages/prisma-client-lib`. This will make development a lot easier, as the client is then automatically using the latest version of `prisma-datamodel` and on ther other hand `prisma-cli-core` will automatically use the latest version of `prisma-client-lib`.

**Comment by pantharshit00** [comment]
This has been already done.
