### ISSUE TITLE
Unable to connect when connection string contains $

### ISSUE THREAD

**Issue by bre7** [prisma/prisma#3669]
**Present only in Prisma 2.7.0**

🚨 Affects all users, not only the ones using nested env variables.
```env
DATABASE_URL="postgres://user:password@server.host:5432/database?ssl=1&schema=schema$1234"
```

## Bug description

Edge case missing from tests:
If the connection string specifies a schema containing the symbol `$`, only the first component is actually parsed.

Probably not the best idea to use $ in a schema name, Prisma 1 naming is to blame !

## How to reproduce

Use the following `.env`

```env
DOTENV_PRISMA_EXPAND_DATABASE_URL="postgres://user:password@server.host:5432/database"
DOTENV_PRISMA_EXPAND_DATABASE_URL_WITH_SCHEMA="${DOTENV_PRISMA_EXPAND_DATABASE_URL}?ssl=1&schema=schema$1234"
```

Error displayed when performing ANY query (`schema` detected instead of `schema$1234`):
> Error: The table `schema.TableNameHere` does not exist in the current database.

## Expected behavior

Prisma should connect to the specified server, db and schema.

## Prisma information

N/A

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version: 2.7.0

## Notes

The culprit is, most likely, `dotenv-expand`'s parsing (introduced in https://github.com/prisma/prisma/pull/3330).

**Comment by pantharshit00** [comment]
I can confirm this. 

I am not sure why `dotenv-expand` is trying to replace this without `${}`. Anyways this is a regression which need a immediate patch.

**Comment by timsuchanek** [comment]
Thanks for reporting @bre7 ! This has just been fixed in https://github.com/prisma/prisma/releases/tag/2.7.1

**Comment by davidboom95** [comment]
Same problem here, do this fix the problem when the connection string has `$` inside the password?
