### ISSUE TITLE
Implement a `findFirst` API

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma#3676]
## Problem
`findOne` is strict in that it requires a unique constraint (@unique, @id) to find a unique entry. That, however, doesn't allow for more flexible kinds of queries which should also usually return a single result.

## Suggested solution
`findFirst`, doing essentially a `findMany` + `take: 1` under the hood.

## Additional context

* https://github.com/prisma/prisma-client-js/issues/232

**Comment by matthewmueller** [comment]
We talked about this during the Client Weekly.

- This will be essentially a `findMany` + `take: 1` under the hood.
- This will be implemented and tested in the client engine by @dpetrick.

**Comment by matthewmueller** [comment]
@matthewmueller needs to figure out error modes, what do we do when there's no results? `null` or `throw`?

**Comment by dpetrick** [comment]
Update: Implemented on the engine side, might or might not need minor integration work on the TS client side.

**Comment by jwld** [comment]
How about a `findLast` too? 👀

**Comment by thebiglabasky** [comment]
> How about a `findLast` too? 👀

I believe that this would be achieved using `take: -1`, so I wouldn't see necessarily a lot of value in adding another method just for that. If you feel otherwise, feel free to open a new issue. Thanks!

**Comment by jwld** [comment]
Is it not the same thing as `findFirst`, just using `take: -1` instead of `take: 1`? Or is there some other aspect I'm missing that makes `findFirst` more valuable?

**Comment by thebiglabasky** [comment]
`findFirst` was there to accommodate use cases where people would search for a single element but with a more lenient set of constraints than with `findOne` which expected to lean on a unique constraint. For example, finding a user by their login OR their email which people would fill in a single input form in an application.
`findMany` was possible to use, but returned an array, making its use suboptimal for that and not intuitive to read.

findLast doesn't strike me as solving any specific problem, and it feels like using findFirst with a take: -1 for the rare cases that would require that could be done.
We try to keep the API surface limited which is why I don't foresee a need to support something like `findLast`. I hope it makes sense.

**Comment by jwld** [comment]
That does make sense, thank you for the explanation :)

**Comment by nickreynke** [comment]
Another use case to clarify why this is important.

Assume you have `Workspace`s where each `User` is either a simple participant or an owner. Per user input the user now wants to fetch a specific workspace by its `id`.

The `findFirst` comes in pretty handy because I can now find the first workspace where the `id` matches the given one AND the user is either a participant or the owner. This makes fetching the workspaces more secure since, in this case, it will only return those that are also attached to the current user.

**Comment by rootandleaves** [comment]
Currently i am running my head to create query to retrieve first entry of any given table x in db. It would be convenient to have something like FindOldest or FindLastest with FindWithLastUpdatedOn (Based on @createdAt and @updatedAt timestamp)
