### ISSUE TITLE
$executeRaw used in a transaction throws: All elements of the array need to be Prisma Client promises.

### ISSUE THREAD

**Issue by seyaobey** [prisma/prisma#3677]
## Bug description

When you include `$executeRaw` in methods to be run in a transaction
`prisma.$transaction([ fn1, fn2, updateFn ])`

then an exception is throw:
`All elements of the array need to be Prisma Client promises.`

## How to reproduce

Execute a simple `prisma.$executeRaw([myUpdateFunc])` with an executRaw promise
e.g:
```
    const updateFn = this.prisma.$executeRaw(`__update__statement__`);
    await this.prisma.$transaction([updateFn]);
```

## Expected behavior

Transaction should execute without error

## Prisma information
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["transactionApi"]
}
```

## Environment & setup

```
- OS: macOs Catalina 10.15.6
- Database: MySql 5.7 (Heroku JawsDB)
- Node.js version: v14.8.0
- Prisma version:
"@prisma/client": "^2.7.0",
"@prisma/cli": "^2.7.0",
```

**Comment by pantharshit00** [comment]
I can reproduce the behaviour. I will mark this as a bug for now as we need throw a proper error message if we don't allow this.

Simple reproduction script(works with any schema):
```js
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient();

  const test = prisma.$executeRaw`SELECT 1`;
  const data = await prisma.$transaction([test]);
  console.log(data);
  prisma.$disconnect();
}

main();

```

**Comment by janpio** [comment]
Related internal discussion: https://prisma-company.slack.com/archives/CEYCG2MCN/p1600259007031700

**Comment by timsuchanek** [comment]
We, for now, add better error handling for this situation, as it's a feature to allow this.
Here is the tracking issue for the feature request: https://github.com/prisma/prisma/issues/3828
