### ISSUE TITLE
Camel casing of field names is not consistent for certain names

### ISSUE THREAD

**Issue by mks11** [prisma/prisma#3686]
Seems like a bug.

I have a field on a graphql Type : "extraFields"

When I checked I was expecting it to become some_prefix+ExtraFields, but if you look at the screen shot what I get generated.

<img width="548" alt="bug_prisma" src="https://user-images.githubusercontent.com/1414252/49750607-69e85b80-fcd1-11e8-908b-f02428f17638.png">

**Comment by mks11** [comment]
The schema screenshot I have attached is the auto generated code by prisma. I was thinking the autogenerated input type will be like OfferPostCreateExtraFieldsInput instead of OfferPostCreateextraFieldsInput.

notice the "ee" in the middle.

But if the screen-shot doesn't catch your eye, maybe It's not a bug at all. It could just be fine. I wasn't sure so I posted.

**Comment by pantharshit00** [comment]
Oh okay, now I got it. Don't worry about the generated naming it is all internally used and is consistent. We handle all the case for naming should not really be an issue. You should be fine here 👍

**Comment by pantharshit00** [comment]
I think this can be closed now since #4031 is merged
