### ISSUE TITLE
Prisma-fmt panics instead of an error message 

### ISSUE THREAD

**Issue by carmenberndt** [prisma/prisma#3699]
## Bug description

Prisma-fmt panics on a string type in a block attribute instead of giving a validation error.

related https://github.com/prisma/language-tools/issues/481

![Screenshot 2020-09-18 at 16 45 18](https://user-images.githubusercontent.com/30771368/93611244-5b62c400-f9ce-11ea-914b-d0ec54419241.png)

## How to reproduce

Steps to reproduce the behaviour:
Example schema:
```
model User {
  firstName String
  lastName  String
  email     String @unique
  isAdmin   Boolean @default(false)
  @@id(["firstName", lastName])
}
```

Run `prisma-fmt`

## Expected behavior

There should be a nice error message pointing out what type the block attribute expects.

**Comment by pantharshit00** [comment]
This no longer panics with 2.21
