### ISSUE TITLE
Generator Idea: Query engine server/proxy

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#370]
Prisma 1 was based on having a data API proxy server running in front of your database. This was useful for a number of scenarios (e.g. connection pooling for FaaS environments - see #276). An easy way to bring back support for this scenario would be to create another generator that generates (1) a server component which hosts the Prisma query engine (e.g. as Docker image) and (2) a forked version of Photon that doesn't include the query engine but forwards requests to the query proxy.

Things to think through:
- Auth handling (e.g. via JWT)
- How does deployment work? ("immutable infrastructure" vs stateful `prisma deploy` flow)

**Comment by createvo** [comment]
Great idea! I wrote on slack just now something similar. Could be done through the prisma2 CLI for an initial stage. An API endpoint is surely the best option. Like prisma Management.

**Comment by mcmar** [comment]
Really glad to see that this is being reconsidered after it was dropped from Prisma2.

I think this appeals mostly to enterprise or large company use-cases, so `immutable infrastructure` is vastly preferable for that set of users compared to `stateful prisma deploy flow`.

And I know the answer is probably no, but it would be great if the API proxy server spoke GraphQL via the OpenCRUD spec and included support for realtime data via websocket subscriptions and also could call lambda functions in response to data changes

**Comment by janpio** [comment]
This now exists as a hosted product from Prisma: 
https://www.prisma.io/data-platform/proxy + https://www.prisma.io/docs/data-platform/data-proxy
