### ISSUE TITLE
Log when a connection to the database is opened

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3702]
Currently the Query Engine (via Prisma Client) only logs the creation of the connection pool after startup, but not when a connection is actually created (vs. taken as existing from the connection pool) or closed. This makes it hard to observe the behavior of the Query Engine.

We should log every time a connection is opened or closed.

**Comment by dpetrick** [comment]
Opening a connection is done, closing a connection is a lot more difficult and should probably be a separate ticket @janpio

**Comment by janpio** [comment]
Thanks, done in https://github.com/prisma/prisma/issues/3993
