### ISSUE TITLE
Prisma deploy throws an error

### ISSUE THREAD

**Issue by SeanningTatum** [prisma/prisma#3710]
**Describe the bug**
I'm trying to create a prisma service using my newly created SQL Prisma Server but everytime I run `prisma deploy` it gives me this error (I connected to my self hosted GCP sql server)

**To Reproduce**
1. Create primsa server
2. initialize a new prisma project via `prisma init`
3. select your newly created server
4. run `prisma deploy`
5. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26712061/50036975-34809c80-0048-11e9-8860-51f1ae4e1507.png)
![image](https://user-images.githubusercontent.com/26712061/50037051-be306a00-0048-11e9-8bff-c6440eff1e4e.png)

**Versions (please complete the following information):**
 - OS: [`OS X Mojave`] 
 - `prisma` CLI: [e.g. `prisma/1.22.2 (darwin-x64) node-v10.8.0`]
 - Prisma Server: [e.g. `1.22.2`]

**Additional context**

**Comment by pantharshit00** [comment]
Hi @SeanningTatum,

Can you please share the Heroku logs with us. Also, make sure that your database is able to receive connections and they are not being blocked by the firewall.

**Comment by SeanningTatum** [comment]
Hello @pantharshit00, 

My heroku logs
![image](https://user-images.githubusercontent.com/26712061/50053671-1b750a00-0174-11e9-93c4-f9f42a7812e3.png)
 
And making sure my database is able to recieve connections
![image](https://user-images.githubusercontent.com/26712061/50053677-30519d80-0174-11e9-89a3-63023df8ecbe.png)

**Comment by b33son** [comment]
Have you tried it in a local docker container? Also, try prisma introspect -i

**Comment by SeanningTatum** [comment]
@b33son everything works fine in a local docker container, but I'm trying to initialize it to connect to my empty postgresql hosted on google cloud

```
? What kind of database do you want to introspect? PostgreSQL
? Enter database host 35.****.***.***
? Enter database port 5432
? Enter database user ***
? Enter database password ****
? Enter name of existing database prisma
? Use SSL? Yes
? Enter name of existing schema

Error: The provided database doesn't contain any tables. Please provide another database.
```
