### ISSUE TITLE
Remove GraphQLSchema from generated prisma-client/index.ts

### ISSUE THREAD

**Issue by steida** [prisma/prisma#3717]
`import { DocumentNode, GraphQLSchema } from 'graphql';`

It's not used therefore TypeScript in strict mode warns.

**Comment by steida** [comment]
Related to https://github.com/prisma/prisma/issues/3369

**Comment by pantharshit00** [comment]
Hi @steida,

As you have already identified this issue is on our radar and we will fix it very soon.

Closing this as duplicate of #3369
