### ISSUE TITLE
Adjust `prisma init` to write to .env instead of prisma/.env

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#3721]
## Problem

By default when we initialize a Prisma project, we write an environment file to `prisma/.env`. This layout works for us but is unusual and incompatible with projects (e.g. next.js, blitz, redwood, create-react-app projects) that assume `.env` is in the project root.

If you try moving `prisma/.env` into the project root, you'd also need to move `prisma/schema.prisma` to the project root. This approach is [documented](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema#using-env-files), but subtle.

For context, there are two components that rely on `.env`: 

- The CLI when introspecting and migrating.
- The generated database client when connecting to the database.

## Suggested solution

I'd suggest we change our defaults from `prisma/.env` and `prisma/schema.prisma` to `.env` and `schema.prisma`. If someone already has an `.env` file, we append our default environment variable (`DATABASE_URL`) to the bottom of their existing `.env` file.

### Do nothing

Don't change anything. Add a bit of documentation saying how you can make Prisma work with your existing `.env` file.

### Initialize to `.env` and `prisma/schema.prisma`

`prisma init` could also write `.env` and `prisma/schema.prisma` instead of writing both files to the project root. I don't really see a reason to create a subdirectory with only 1 file (by default), but I also don't have strong opinions on this.

## Related

- We should decide on #3720 before deciding on this issue.

**Comment by matthewmueller** [comment]
After we implement #3720, we'll resolve this issue. I talked with @timsuchanek today about it and came up with the following solution. 

- Write .env to the project root by default
	- If there's already a .env file in the project root, we'll try appending `DATABASE_URL="..."` to that file
    - If you already have `DATABASE_URL="..."` in your `.env` file, don't do anything and print a notice.

**Comment by rntjr** [comment]
@matthewmueller will it be applicable in monorepo? I have a .env file in the root directory of my repository.
Example:
![image](https://user-images.githubusercontent.com/48002341/97248571-d6df3e80-17e0-11eb-9934-8eb877efc9c1.png)

**Comment by matthewmueller** [comment]
@rntjr Yes, the project root is defined as wherever your package.json. Is that a problem for your setup?

**Comment by matthewmueller** [comment]
From @timsuchanek's issue in #4293, the implementation will likely be when you run `prisma init` look for `package.json` and either:

- If no `.env` file create one.
- If there is no conflict with the existing env vars, append
- If the env var about to be added already is defined, throw an error
