### ISSUE TITLE
Using MLab Sandbox with MongoDB connector

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#3727]
Currently using a mlab sandbox with the mongo connector results in an authentication error.

This is because prisma needs access to the admin DB as it will create a database named prisma to track all of the deployment and migration histories.

That being said I am able to use a sandbox MongoDB atlas deployment for development. Just use the connection string they give you to login in MongoDB compass, not the one they give you for the application. Give atlas a try [here](https://atlas.mongodb.com)

If you want to use mlab anyways, you will need access to admin DB that means a dedicated box.

You may be aware of the fact that mlab has been acquired by MongoDB Inc and mlab deployment will be moved into atlas soon, so I will recommend using MongoDB atlas. Just make sure you use the right connection string there.

**Comment by thidasapankaja** [comment]
@pantharshit00 Used MongoDB atlas. But still getting the same issue.
