### ISSUE TITLE
Cannot read property 'setPublishableKey' of undefined

### ISSUE THREAD

**Issue by harvey56** [prisma/prisma#3737]
**Describe the bug**
I'm following the tutorial on howtographql. When I `prisma deploy` i get the following error message in chromium (70.0.3538.77) : 
`Failed to load resource: net::ERR_TIMED_OUT`

followed by : 
`Cannot read property 'setPublishableKey' of undefined`
in BillingInformationHOC.tsx, line 12.

In firefox (63.0.3) : 
`Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Versions (please complete the following information):**
 - `prisma` CLI: prisma/1.22.2 (linux-x64) node-v10.9.0
 - Prisma Server: [e.g. `1.9.0`]

**Comment by pantharshit00** [comment]
Hi @harvey56,


Can you provide me additional context so that I may reproduce this issue and observe the bug? A screenshot will be extremely helpful. Also, share the link for the tutorial page link.

**Comment by harvey56** [comment]
Hi @pantharshit00 

Tutorial is here : https://www.howtographql.com/graphql-js/4-adding-a-database/
All I get is in the console, as stated in my OP.
