### ISSUE TITLE
Golang client generates float32 for double-precision float

### ISSUE THREAD

**Issue by rodcorsi** [prisma/prisma#3745]
**Describe the bug**
Golang client generates float32 for Float type, but [graphql.org](https://graphql.org/learn/schema/#scalar-types) defines Float as double-precision, so the correct is float64

**Expected behavior**
Using float64 for Float type

**Versions:**
 - OS: `Windows 10` and `Ubuntu 18.04`
 - `prisma` CLI: `prisma/1.23.0 node-v11.5.0`
 - Prisma Server: `1.23.0`

**Comment by pantharshit00** [comment]
cc @dominikh

**Comment by schickling** [comment]
@dominikh what do you suggest in this case? Sticking with `float32` or going for `float64` as suggested by @rodcorsi?
