### ISSUE TITLE
Introspect result has the invalid name for @relation

### ISSUE THREAD

**Issue by mattdamon108** [prisma/prisma#3746]
**Describe the bug**
`@relation` name args value is generated against the shape [A-Z][a-zA-Z0-9]* after prisma introspect. It shows the error during deploy after introspect.

**To Reproduce**
1. compose docker along with postgres DB setting and run docker container
2. prisma introspect in cli
3. prisma deploy
4. shows error
`ERROR: The provided name: account_messageboxes_receivers is not a valid name for a relation. It can only have up to 54 characters and must have the shape [A-Z][a-zA-Z0-9]*`

**Expected behavior**
I firstly set up DB with Django ORM. Some tables have a relation column each other with option `'related_name='`. I think this is generated to @relation(name: something) into datamodel.prisma. But the problem is the generated result is something like this `@relation(name: account_messageboxes_receivers)`. It is missing the double quote, the first Uppercase letter, and the underscores. I changed it to `@relation(name: "AccountMessageboxesReceivers")` then it is deployed successfully.

**Versions (please complete the following information):**
 - OS: macOS Mojave
 - `prisma` CLI: prisma/1.23.1 (darwin-x64) node-v11.0.0
 - Prisma Server: I don't know how to check Prisma Server version.

**Comment by serranoarevalo** [comment]
Any workaround for this? It's happening to me after introspecting a Postgres database.

**Comment by pantharshit00** [comment]
@matthewpick 

Can you please try this again with the latest version? We have done some introspection improvements there

**Comment by matthewpick** [comment]
@mattdamon108 @pantharshit00 ^^

**Comment by serranoarevalo** [comment]
This is still an issue

**Comment by pantharshit00** [comment]
@serranoarevalo Can you please provide a postgres schema that I can use to reproduce this issue.
