### ISSUE TITLE
[Mongo] mongo connector queries unnecessary fields from mongodb

### ISSUE THREAD

**Issue by beeplin** [prisma/prisma#3748]
**Describe the bug**
In 1.24.beta-2, mongo connector queries unnecessary fields from mongodb

**To Reproduce**
1. edit mongo.conf, add `verbosity: 1`:

```yml
systemLog:
   destination: file
   path: "/etc/mongo/mongod.log"
   logAppend: true
   verbosity: 1
```

2. query from any mongo collections via prisma playground, only asking for `id` field to be returned: 

```gql
query {
  someType(where: { id: "5c1b14a35764540007eda0ca" }) {
    id
  }
}
```

3. although prisma returns only `id` field, when we check mongo logs, we found in fact prisma queries **ALL FIELDS** from the mongo collection:

```
2018-12-20T05:54:58.646+0000 I COMMAND  [conn8] command default_default.A command: find { find: "SomeType", filter: { _id: ObjectId('5c1b14a35764540007eda0ca') }, batchSize: 2147483647, $db: "default_default", $readPreference: { mode: "primaryPreferred" } } planSummary: IDHACK keysExamined:1 docsExamined:1 cursorExhausted:1 numYields:0 nreturned:1 reslen:128 locks:{ Global: { acquireCount: { r: 2 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } protocol:op_msg 0ms
```

**Expected behavior**
It is supposed to only query `id` field from mongo, not all other useless fields, in order to save band width and improve performance.

**Screenshots**

**Versions (please complete the following information):**
 - OS:  `Windows 10`
 - `prisma`: prisma/1.24.0-beta.2 (windows-x64) node-v10.14.2
 - Prisma Server: prisma:1.24-beta-2

**Comment by do4gr** [comment]
Hey @beeplin, thanks for reporting this. This is something we are currently working on and will improve with the next alpha. As the connector is still in Preview we focused on the outward facing functionality first and are now working on internal performance improvements.

**Comment by beeplin** [comment]
sure. :)

**Comment by do4gr** [comment]
I just merged https://github.com/prisma/prisma/pull/3709 into alpha, you can check it out in a bit, it heavily limits the selectivity.
