### ISSUE TITLE
`prisma init` generates wrong datamodel when getting started with new MongoDB 

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3749]
When using `prisma init` and creating a **new** DB with the `mongo` connector with thew interactive wizard, the CLI generates a datamodel that follows the v1 format:

```graphql
type User {
  id: ID! @unique
  name: String!
}
```

It should follow the v2 format:

```graphql
type User {
  id: ID! @id
  name: String!
}
```

**Comment by divyenduz** [comment]
This is available in the latest version `1.25.0`, `npm install -g prisma`. I am closing this issue. Please let me know if the issue still persists via opening a new issue.
