### ISSUE TITLE
Introspection is printing out relation field as nullable when one of composite foreign key field is nullable

### ISSUE THREAD

**Issue by joaopaulobdac** [prisma/prisma#3749]
Hi Prisma Team! My Prisma Client just crashed. This is the report:

## Versions

| Name     | Version              |
|----------|----------------------|
| Node     | v14.8.0              | 
| OS       | debian-openssl-1.1.x |
| Prisma   | 2.5.1                |

## Logs

```
  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: '/home/jp/.../prisma',
  prisma-client     enableDebugLogs: false,
  prisma-client     enableEngineDebugMode: undefined,
  prisma-client     datamodelPath: '/home/jp/.cache/prisma/studio/.../schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     engineEndpoint: undefined,
  prisma-client     generator: {
  prisma-client       binaryTargets: [],
  prisma-client       previewFeatures: [],
  prisma-client       config: [Object],
  prisma-client       name: 'photon',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: '/home/jp/.cache/prisma/studio/...',
  prisma-client       isCustomOutput: true
  prisma-client     },
  prisma-client     showColors: false,
  prisma-client     logLevel: undefined,
  prisma-client     logQueries: undefined,
  prisma-client     flags: [],
  prisma-client     clientVersion: '2.5.1',
  prisma-client     enableExperimental: [],
  prisma-client     useUds: undefined
  prisma-client   }
  prisma-client }  
  plusX Execution permissions of /home/jp/.cache/prisma/studio/.../query-engine-debian-openssl-1.1.x are fine  
  prisma-client Client Version 2.5.1  
  prisma-client Engine Version c88925ce44a9b89b4351aec85ba6a28979d2658e  
  plusX Execution permissions of /home/jp/.cache/prisma/studio/.../query-engine-debian-openssl-1.1.x are fine  
```

```
Generating Prisma Client ... done
Studio started at http://localhost:5555
Error in request:  PrismaClientRustPanicError: PANIC: Application logic invariant error: received null value for field AlarmUser which may not be null
```

```
query: 'prisma.alarmOccurrence.findMany({\n' +
    '  take: 100,\n' +
    '  skip: 0,\n' +
    '  select: {\n' +
    '    id: true,\n' +
    '    time: true,\n' +
    '    alarmId: true,\n' +
    '    sensorId: true,\n' +
    '    acknowledgedAt: true,\n' +
    '    acknowledgedByUserId: true,\n' +
    '    normalizedAt: true,\n' +
    '    AlarmUser: true,\n' +
    '    AlarmSensor: true,\n' +
    '  }\n' +
    '})'
```

## Context

Here are the relevant schema parts:

```sql
CREATE TABLE "Alarm" (
  "id" SERIAL PRIMARY KEY NOT NULL
);

CREATE TABLE "AlarmSensor" (
  "alarmId" INTEGER NOT NULL REFERENCES "Alarm"("id"),
  "sensorId" INTEGER NOT NULL REFERENCES "Sensor"("id"),
  PRIMARY KEY ("alarmId", "sensorId")
);

CREATE TABLE "AlarmUser" (
  "alarmId" INTEGER NOT NULL REFERENCES "Alarm"("id"),
  "userId" INTEGER NOT NULL REFERENCES "User"("id"),
  PRIMARY KEY ("alarmId", "userId")
);

CREATE TABLE "AlarmOccurrence" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "time" TIMESTAMP NOT NULL DEFAULT now(),
  "alarmId" INTEGER NOT NULL,
  "sensorId" INTEGER NOT NULL,
  "acknowledgedAt" TIMESTAMP,
  "acknowledgedByUserId" INTEGER,

  -- Both FKs share the same alarmId,
  -- but I want acknowledgedByUserId to be initially null:

  FOREIGN KEY ("alarmId", "sensorId") REFERENCES "AlarmSensor"("alarmId", "sensorId"),

  -- MATCH SIMPLE: If any of the columns on which a foreign key is defined is NULL,
  -- the foreign key is not enforced.
  FOREIGN KEY ("alarmId", "acknowledgedByUserId")
    REFERENCES "AlarmUser"("alarmId", "userId") MATCH SIMPLE
);
```

Look, I'm not a database design expert. So if you think I could improve this somehow, I would love to learn how to do it!

Using raw SQL, I can create a new `AlarmOccurrence` with `acknowledgedByUserId` initially set to null. But if I open Prisma Studio to view the table row, it throws the error.

Using Prisma to create the `AlarmOccurrence`, both FKs are being marked as required, which is not the desired behavior.

Edit: If I set `alarmId` as NULL, `acknowledgedByUserId` is not marked as required anymore by Prisma. But I still think the default FK behavior should be followed here...

**Comment by joaopaulobdac** [comment]
> I can confirm this. Looks like a bug in introspection where when one of composite id is nullable it still decides to make the relation field nullable.

Thank you for looking into this!
Did you mean "when one of composite id is nullable it still decides to make the relation field **non-nullable**"?

**Comment by pantharshit00** [comment]
This is the introspection result of the database schema:
```prisma

model User {
  id        Int         @default(autoincrement()) @id
  AlarmUser AlarmUser[]
}

model Alarm {
  id          Int           @default(autoincrement()) @id
  AlarmSensor AlarmSensor[]
  AlarmUser   AlarmUser[]
}

model AlarmOccurrence {
  id                   Int         @default(autoincrement()) @id
  time                 DateTime    @default(now())
  alarmId              Int     // <--------- Not nullable
  sensorId             Int
  acknowledgedAt       DateTime?
  acknowledgedByUserId Int?   // <------ Nullable !!!!!!!
  AlarmUser            AlarmUser   @relation(fields: [alarmId, acknowledgedByUserId], references: [alarmId, userId])  // <---------- Not Nullable !!!!! Should be AlarmUser?
  AlarmSensor          AlarmSensor @relation(fields: [alarmId, sensorId], references: [alarmId, sensorId])
}

model AlarmSensor {
  alarmId         Int
  sensorId        Int
  Alarm           Alarm             @relation(fields: [alarmId], references: [id])
  Sensor          Sensor            @relation(fields: [sensorId], references: [id])
  AlarmOccurrence AlarmOccurrence[]

  @@id([alarmId, sensorId])
}

model AlarmUser {
  alarmId         Int
  userId          Int
  Alarm           Alarm             @relation(fields: [alarmId], references: [id])
  User            User              @relation(fields: [userId], references: [id])
  AlarmOccurrence AlarmOccurrence[]

  @@id([alarmId, userId])
}

model Sensor {
  id          Int           @default(autoincrement()) @id
  AlarmSensor AlarmSensor[]
}
```

In the above result you can see `acknowledgedByUserId` is nullable but the relation field(which is virtual and only accessible in prisma, it doesn't exist in the database) is required(all field without `?` are required) which should not be the case one of the foreign keys is nullable. 

You can manually fix this actually by changing `AlarmUser` to `AlarmUser?` in your schema.

**Comment by joaopaulobdac** [comment]
> In the above result you can see `acknowledgedByUserId` is nullable but the relation field is required

That's why I thought you meant to say "it still decides to make the relation field non-nullable" in your comment above :+1:

> You can manually fix this actually by changing `AlarmUser` to `AlarmUser?` in your schema.

Oh damn, I didn't even realize that I could do that after introspection haha

**Comment by do4gr** [comment]
Hey, thanks for reporting this in such detail @joaopaulobdac . 
There is definitely need for action here, we're discussing possible approaches at the moment. I will update again once we agreed on an approach.

**Comment by do4gr** [comment]
I tried modeling your schema slightly differently @joaopaulobdac and am wondering whether that would also serve your needs. I eliminated the intermediate models of AlarmSensor and UserAlarm.

```prisma
model User {
  id                    Int         @default(autoincrement()) @id
  acknowledgedAlarms   AlarmOccurrence[]
}

model Alarm {
  id                    Int           @default(autoincrement()) @id
  occurence             AlarmOccurrence[]
}


model Sensor {
  id                    Int           @default(autoincrement()) @id
  occurence             AlarmOccurrence[]
}

model AlarmOccurrence {
  id                    Int         @default(autoincrement()) @id
  time                  DateTime    @default(now())
  alarmId               Int
  sensorId              Int
  acknowledgedAt        DateTime?
  acknowledgedByUserId  Int?   
  acknowledgingUser     User?    @relation(fields: [acknowledgedByUserId])  
  triggeredAlarm        Alarm    @relation(fields: [alarmId])
  triggeredSensor       Sensor    @relation(fields: [sensorId])
}
```

I think this still gives you the same capabilities that you were looking for. The intermediate models in your example were not holding any additional information. Would this datamodel work for you?

**Comment by joaopaulobdac** [comment]
Thanks for the feedback @do4gr :pray:

The reason I'm using these intermediate models is to "link" the entities together, because an alarm can monitor many sensors and can notify many users. For example: using your schema, how would I find the alarms that an user is subscribed to, or the sensors that an alarm is monitoring?

I actually ended up extracting the acknowledging user to a separate model:

```sql
CREATE TABLE "AlarmOccurrence" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "time" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "alarmId" INTEGER NOT NULL,
  "sensorId" INTEGER NOT NULL,
  "normalizedAt" TIMESTAMPTZ,

  FOREIGN KEY ("alarmId", "sensorId")
    REFERENCES "AlarmSensorLink"("alarmId", "sensorId") MATCH FULL ON DELETE CASCADE
);

CREATE TABLE "AlarmAcknowledgement" (
  "time" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "occurrenceId" INTEGER NOT NULL REFERENCES "AlarmOccurrence"("id") ON DELETE CASCADE,
  "userId" INTEGER NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,

  PRIMARY KEY ("occurrenceId", "userId")
);
```

Unfortunately this means it's not guaranteed that an user who acknowledges an alarm is really linked to the alarm, but it would be guaranteed if I used the double foreign keys on `AlarmOccurrence` because the database would throw an error if the `alarmId` didn't match.

**Comment by miller-productions** [comment]
Hi there, I am experience this issue also.

I have a composite foreign key relationship on a table. **One of the columns in the composite key is nullable**, the other column in the composite key is not nullable. 

The resulting `schema.prisma` file that gets generated has the associated virtual relation field defined as not nullable.

This then doesn't allow me to pass null to that field when creating a row on that table.

Expected behaviour: `schema.prisma` should be generated with the associated virtual relation field as **nullable**. I should be able to create a new row on that table with null for the column associated with the foreign key.

**Comment by miller-productions** [comment]
@pantharshit00 , you mention in [the comment above](https://github.com/prisma/prisma/issues/3749#issuecomment-698013877)...
> 
> In the above result you can see `acknowledgedByUserId` is nullable but the relation field(which is virtual and only accessible in prisma, it doesn't exist in the database) is required(all field without `?` are required) which should not be the case one of the foreign keys is nullable.
> 
> You can manually fix this actually by changing `AlarmUser` to `AlarmUser?` in your schema.

I just tried this approach in my scenario and I was met with the schema validation error message `At least one of those fields is required. Hence the relation field must be required as well.` It didn't let me manually change the schema to make the relation field nullable.

What do you think?

**Comment by pantharshit00** [comment]
Hey @miller-productions 

Sorry for the late reply :pray: 


Can you please share the part of the schema which you are trying to modify? It is difficult to suggest changes without actually seeing the schema.

**Comment by pantharshit00** [comment]
This bug is confirmed anyways so you might as well wait for the fix.

**Comment by pantharshit00** [comment]
The original report no longer triggers a panic for me and #3747 is now closed so I am going to close this. 

Feel free to comment here if you feel this hasn't been addressed.
