### ISSUE TITLE
deployment on VPS error

### ISSUE THREAD

**Issue by bb-art** [prisma/prisma#3753]
##  Bug description

I have a VPS on which I want to deploy my prisma app, but it's giving errors.
I installed the prisma graphql example: https://github.com/prisma/prisma-examples/tree/latest/javascript/graphql
and connected to a mysql database, also hosted on the VPS

Using Migrate I succesfully lifted the schema to the database (assuming db connection is ok)

When I run the app (using node.js extension on Plesk) I can see the graphql playground, but when I post a query, no response is returned.

VPS: linux ubuntu 18
plesk onyx with node 10

```
"@nexus/schema": "0.15.0",
    "@prisma/client": "^2.7.1",
    "graphql": "^15.0.0",
    "graphql-yoga": "^1.16.1",
    "nexus-prisma": "0.13.0"
```

Any help would be very much appreciated!

output from debug:

```
App 25036 output: 2020-09-24T11:15:43.526Z prisma-client Prisma Client call:
App 25036 output: 2020-09-24T11:15:43.529Z prisma-client prisma.post.findMany({
App 25036 output:   where: {
App 25036 output:     published: true
App 25036 output:   }
App 25036 output: })
App 25036 output: 2020-09-24T11:15:43.530Z prisma-client Generated request:
App 25036 output: 2020-09-24T11:15:43.530Z prisma-client query {
App 25036 output:   findManyPost(where: {
App 25036 output:     published: {
App 25036 output:       equals: true
App 25036 output:     }
App 25036 output:   }) {
App 25036 output:     authorId
App 25036 output:     content
App 25036 output:     id
App 25036 output:     published
App 25036 output:     title
App 25036 output:   }
App 25036 output: }
App 25036 output:
App 25036 output: 2020-09-24T11:15:43.532Z engine { cwd: '/var/www/vhosts/quarpa.nl/httpdocs/test1/prisma' }
App 25036 output: 2020-09-24T11:15:43.532Z engine { dotPrismaPath:
App 25036 output:    '/var/www/vhosts/quarpa.nl/httpdocs/test1/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x' }
App 25036 output: 2020-09-24T11:15:43.533Z plusX Execution permissions of /var/www/vhosts/quarpa.nl/httpdocs/test1/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
App 25036 output: 2020-09-24T11:15:43.533Z engine { flags: [ '--enable-raw-queries' ] }
App 25036 output: 2020-09-24T11:15:43.534Z engine port: 36436
App 25036 output: 2020-09-24T11:15:43.545Z engine stderr thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/blocking/pool.rs:214:14
App 25036 output: 2020-09-24T11:15:43.545Z engine stderr stack backtrace:
App 25036 output: 2020-09-24T11:15:43.582Z engine stderr    0: backtrace::backtrace::libunwind::trace
App 25036 output: 2020-09-24T11:15:43.582Z engine stderr              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
App 25036 output: 2020-09-24T11:15:43.582Z engine stderr    1: backtrace::backtrace::trace_unsynchronized
App 25036 output: 2020-09-24T11:15:43.582Z engine stderr              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
App 25036 output: 2020-09-24T11:15:43.582Z engine stderr    2: std::sys_common::backtrace::_print_fmt
App 25036 output: 2020-09-24T11:15:43.582Z engine stderr              at src/libstd/sys_common/backtrace.rs:78
App 25036 output: 2020-09-24T11:15:43.583Z engine stderr    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
App 25036 output: 2020-09-24T11:15:43.583Z engine stderr              at src/libstd/sys_common/backtrace.rs:59
App 25036 output: 2020-09-24T11:15:43.595Z engine stderr    4: core::fmt::write
App 25036 output: 2020-09-24T11:15:43.595Z engine stderr              at src/libcore/fmt/mod.rs:1076
App 25036 output: 2020-09-24T11:15:43.595Z engine stderr    5: std::io::Write::write_fmt
App 25036 output: 2020-09-24T11:15:43.595Z engine stderr              at src/libstd/io/mod.rs:1537
App 25036 output: 2020-09-24T11:15:43.595Z engine stderr    6: std::sys_common::backtrace::_print
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr              at src/libstd/sys_common/backtrace.rs:62
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr    7: std::sys_common::backtrace::print
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr              at src/libstd/sys_common/backtrace.rs:49
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr    8: std::panicking::default_hook::{{closure}}
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr              at src/libstd/panicking.rs:198
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr    9: std::panicking::default_hook
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr              at src/libstd/panicking.rs:217
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr   10: std::panicking::rust_panic_with_hook
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr              at src/libstd/panicking.rs:526
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr   11: rust_begin_unwind
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr              at src/libstd/panicking.rs:437
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr   12: core::panicking::panic_fmt
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr              at src/libcore/panicking.rs:85
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr   13: core::option::expect_none_failed
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr              at src/libcore/option.rs:1269
App 25036 output: 2020-09-24T11:15:43.596Z engine stderr   14: tokio::runtime::blocking::pool::Spawner::spawn
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   15: tokio::runtime::blocking::pool::spawn_blocking
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   16: tokio::runtime::context::enter
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   17: tokio::runtime::builder::Builder::build
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   18: tokio::runtime::Runtime::new
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   19: core::ops::function::FnOnce::call_once
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   20: once_cell::imp::OnceCell<T>::initialize::{{closure}}
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   21: once_cell::imp::initialize_inner
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   22: once_cell::imp::OnceCell<T>::initialize
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   23: std::thread::local::LocalKey<T>::with
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   24: core::ops::function::FnOnce::call_once{{vtable.shim}}
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   25: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
App 25036 output: 2020-09-24T11:15:43.597Z engine stderr   27: std::sys::unix::thread::Thread::new::thread_start
App 25036 output: 2020-09-24T11:15:43.598Z engine stderr              at src/libstd/sys/unix/thread.rs:87
App 25036 output: 2020-09-24T11:15:43.598Z engine stderr   28: start_thread
App 25036 output: 2020-09-24T11:15:43.598Z engine stderr   29: __clone
App 25036 output: 2020-09-24T11:15:43.598Z engine stderr note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[ W 2020-09-24 13:15:45.0030 24953/T4 age/Cor/App/Poo/AnalyticsCollection.cpp:61 ]: ERROR: Cannot fork() a new process: Resource temporarily unavailable (errno=11)
  Backtrace:
     in 'void Passenger::ApplicationPool2::Pool::realCollectAnalytics()' (AnalyticsCollection.cpp:142)
     in 'static void Passenger::ApplicationPool2::Pool::collectAnalytics(Passenger::ApplicationPool2::PoolPtr)' (AnalyticsCollection.cpp:56)

[ W 2020-09-24 13:15:50.0022 24953/T4 age/Cor/App/Poo/AnalyticsCollection.cpp:61 ]: ERROR: Cannot fork() a new process: Resource temporarily unavailable (errno=11)
  Backtrace:
     in 'void Passenger::ApplicationPool2::Pool::realCollectAnalytics()' (AnalyticsCollection.cpp:142)
     in 'static void Passenger::ApplicationPool2::Pool::collectAnalytics(Passenger::ApplicationPool2::PoolPtr)' (AnalyticsCollection.cpp:56)

**Comment by pantharshit00** [comment]
Hey @bb-art 

Can you please tell me which VPS service you are using? 

Also, can you try with this option once, it will enable a different procotol between client and engine as I am assuming runtime is unable to acquire a TCP port:
```ts
const prisma = new PrismaClient({
  __internal:{
    useUds: true
  }
})
```

Let me know if it works with this. Thanks!

**Comment by bb-art** [comment]
Hi Harshit, 

Thanx for thinking along.
The VPS is a linux  ubuntu 18, or do you need other info?

Adding the option resulted in (almost) the same error, see below. The last error (Cannot fork) keeps repeating every 5 seconds

kind regards

App 2818 output: 2020-09-24T14:31:12.772Z prisma-client Prisma Client call:
App 2818 output: 2020-09-24T14:31:12.773Z prisma-client prisma.post.findMany({
App 2818 output:   where: {
App 2818 output:     published: true
App 2818 output:   }
App 2818 output: })
App 2818 output: 2020-09-24T14:31:12.773Z prisma-client Generated request:
App 2818 output: 2020-09-24T14:31:12.773Z prisma-client query {
App 2818 output:   findManyPost(where: {
App 2818 output:     published: {
App 2818 output:       equals: true
App 2818 output:     }
App 2818 output:   }) {
App 2818 output:     authorId
App 2818 output:     content
App 2818 output:     id
App 2818 output:     published
App 2818 output:     title
App 2818 output:   }
App 2818 output: }
App 2818 output:
App 2818 output: 2020-09-24T14:31:12.774Z engine { cwd: '/var/www/vhosts/quarpa.nl/httpdocs/test1/prisma' }
App 2818 output: 2020-09-24T14:31:12.775Z engine {
App 2818 output:   dotPrismaPath: '/var/www/vhosts/quarpa.nl/httpdocs/test1/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x'
App 2818 output: }
App 2818 output: 2020-09-24T14:31:12.776Z plusX Execution permissions of /var/www/vhosts/quarpa.nl/httpdocs/test1/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
App 2818 output: 2020-09-24T14:31:12.776Z engine {
App 2818 output:   flags: [
App 2818 output:     '--enable-raw-queries',
App 2818 output:     '--unix-path',
App 2818 output:     '/tmp/prisma-79a772eb8b6e8b90dd337e1c.sock'
App 2818 output:   ]
App 2818 output: }
App 2818 output: 2020-09-24T14:31:12.787Z engine stderr thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/blocking/pool.rs:214:14
App 2818 output: 2020-09-24T14:31:12.787Z engine stderr stack backtrace:
App 2818 output: 2020-09-24T14:31:12.822Z engine stderr    0: backtrace::backtrace::libunwind::trace
App 2818 output: 2020-09-24T14:31:12.822Z engine stderr              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
App 2818 output: 2020-09-24T14:31:12.823Z engine stderr    1: backtrace::backtrace::trace_unsynchronized
App 2818 output: 2020-09-24T14:31:12.823Z engine stderr              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
App 2818 output: 2020-09-24T14:31:12.823Z engine stderr    2: std::sys_common::backtrace::_print_fmt
App 2818 output: 2020-09-24T14:31:12.823Z engine stderr    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
App 2818 output: 2020-09-24T14:31:12.823Z engine stderr              at src/libstd/sys_common/backtrace.rs:59
App 2818 output: 2020-09-24T14:31:12.833Z engine stderr    4: core::fmt::write
App 2818 output: 2020-09-24T14:31:12.833Z engine stderr              at src/libcore/fmt/mod.rs:1076
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr    5: std::io::Write::write_fmt
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr              at src/libstd/io/mod.rs:1537
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr    6: std::sys_common::backtrace::_print
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr              at src/libstd/sys_common/backtrace.rs:62
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr    7: std::sys_common::backtrace::print
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr              at src/libstd/sys_common/backtrace.rs:49
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr    8: std::panicking::default_hook::{{closure}}
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr              at src/libstd/panicking.rs:198
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr    9: std::panicking::default_hook
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr              at src/libstd/panicking.rs:217
App 2818 output: 2020-09-24T14:31:12.834Z engine stderr   10: std::panicking::rust_panic_with_hook
App 2818 output: 2020-09-24T14:31:12.835Z engine stderr              at src/libstd/panicking.rs:526
App 2818 output: 2020-09-24T14:31:12.835Z engine stderr   11: rust_begin_unwind
App 2818 output: 2020-09-24T14:31:12.835Z engine stderr              at src/libstd/panicking.rs:437
App 2818 output: 2020-09-24T14:31:12.835Z engine stderr   12: core::panicking::panic_fmt
App 2818 output: 2020-09-24T14:31:12.835Z engine stderr              at src/libcore/panicking.rs:85
App 2818 output: 2020-09-24T14:31:12.835Z engine stderr   13: core::option::expect_none_failed
App 2818 output: 2020-09-24T14:31:12.835Z engine stderr              at src/libcore/option.rs:1269
App 2818 output: 2020-09-24T14:31:12.835Z engine stderr   14: tokio::runtime::blocking::pool::Spawner::spawn
App 2818 output: 2020-09-24T14:31:12.835Z engine stderr   15: tokio::runtime::blocking::pool::spawn_blocking
App 2818 output: 2020-09-24T14:31:12.836Z engine stderr   16: tokio::runtime::context::enter
App 2818 output: 2020-09-24T14:31:12.836Z engine stderr   17: tokio::runtime::builder::Builder::build
App 2818 output: 2020-09-24T14:31:12.836Z engine stderr   18: tokio::runtime::Runtime::new
App 2818 output: 2020-09-24T14:31:12.836Z engine stderr   19: core::ops::function::FnOnce::call_once
App 2818 output: 2020-09-24T14:31:12.836Z engine stderr   20: once_cell::imp::OnceCell<T>::initialize::{{closure}}
App 2818 output: 2020-09-24T14:31:12.836Z engine stderr   21: once_cell::imp::initialize_inner
App 2818 output: 2020-09-24T14:31:12.836Z engine stderr   22: once_cell::imp::OnceCell<T>::initialize
App 2818 output: 2020-09-24T14:31:12.836Z engine stderr   23: std::thread::local::LocalKey<T>::with
App 2818 output: 2020-09-24T14:31:12.836Z engine stderr   24: core::ops::function::FnOnce::call_once{{vtable.shim}}
App 2818 output: 2020-09-24T14:31:12.836Z engine stderr   25: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
App 2818 output: 2020-09-24T14:31:12.837Z engine stderr              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
App 2818 output: 2020-09-24T14:31:12.837Z engine stderr   26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
App 2818 output: 2020-09-24T14:31:12.837Z engine stderr              at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
App 2818 output: 2020-09-24T14:31:12.837Z engine stderr   27: std::sys::unix::thread::Thread::new::thread_start
App 2818 output: 2020-09-24T14:31:12.837Z engine stderr              at src/libstd/sys/unix/thread.rs:87
App 2818 output: 2020-09-24T14:31:12.837Z engine stderr   28: start_thread
App 2818 output: 2020-09-24T14:31:12.837Z engine stderr   29: __clone
App 2818 output: 2020-09-24T14:31:12.837Z engine stderr note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[ W 2020-09-24 16:31:15.0039 2793/T3 age/Cor/App/Poo/AnalyticsCollection.cpp:61 ]: ERROR: Cannot fork() a new process: Resource temporarily unavailable (errno=11)
Backtrace:
     in 'void Passenger::ApplicationPool2::Pool::realCollectAnalytics()' (AnalyticsCollection.cpp:142)
     in 'static void Passenger::ApplicationPool2::Pool::collectAnalytics(Passenger::ApplicationPool2::PoolPtr)' (AnalyticsCollection.cpp:56)
[ W 2020-09-24 16:31:20.0020 2793/T3 age/Cor/App/Poo/AnalyticsCollection.cpp:61 ]: ERROR: Cannot fork() a new process: Resource temporarily unavailable (errno=11)
  Backtrace:
     in 'void Passenger::ApplicationPool2::Pool::realCollectAnalytics()' (AnalyticsCollection.cpp:142)
     in 'static void Passenger::ApplicationPool2::Pool::collectAnalytics(Passenger::ApplicationPool2::PoolPtr)' (AnalyticsCollection.cpp:56)

[ W 2020-09-24 16:31:25.0023 2793/T3 age/Cor/App/Poo/AnalyticsCollection.cpp:61 ]: ERROR: Cannot fork() a new process: Resource temporarily unavailable (errno=11)
  Backtrace:
     in 'void Passenger::ApplicationPool2::Pool::realCollectAnalytics()' (AnalyticsCollection.cpp:142)
     in 'static void Passenger::ApplicationPool2::Pool::collectAnalytics(Passenger::ApplicationPool2::PoolPtr)' (AnalyticsCollection.cpp:56)

**Comment by bb-art** [comment]
Hi there, 

Im trying to get past this error, but till now no luck.
Now using the latest versions:
@prisma/cli and client 2.8.1
@nexus/schema: 0.16.0
nexus-plugin-prisma: 0.21.0
graphql: 14.7.0
deployment on a VPS with Ubuntu 18.04 LTS 64bit + Plesk Onyx on a 4CPU 8GB RAM

Remarkably, migration of the schema to the database is successfull, or doesnt this involve the engine?
Error occurs when prisma sends a query, no matter what database connection I use (tried MySQL via localhost and SQLite):

engine stderr thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/blocking/pool.rs:214:14

I found the same error in this issue: https://github.com/prisma/prisma-client-js/issues/697 
can this have something to do with it?

the option with useUds that @pantharshit00 mentioned is no longer available?

Do you have other debug-options?

**Comment by bb-art** [comment]
I switched the VPS to CentOS 7 64bit and now the app runs without errors.

**Comment by pantharshit00** [comment]
I am going to close this as I can't reproduce this in an ubuntu VPS and @bb-art seems to have solved to problem by switching the OS so I suspect there was some problem with the machine which they got allocated.
