### ISSUE TITLE
`prisma init` should not ask if there is existing data if `Use existing database` was selected

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3755]
Currently, the flow for an existing database is like this:

```
$ prisma init test
? Set up a new Prisma server or deploy to an existing server? Use existing database
? What kind of database do you want to deploy to? MongoDB
? Enter MongoDB connection string mongodb+srv://Admin:asd@cluster0-sapwg.mongodb.net/test?retryWrites=true
? Does your database contain existing data? Yes
? Enter name of existing database testdb
```

The question `? Does your database contain existing data?` seems unnecessary since that's exactly what we want to catch with the very first question already. If this is not clear from the very first question, we should rather re-formulate that question instead of asking it again.

**Comment by pantharshit00** [comment]
Closing in favour of #4302
