### ISSUE TITLE
Case-insensitive filtering does not work

### ISSUE THREAD

**Issue by aaronfulkerson** [prisma/prisma#3762]
## Bug description

Case-insensitive filtering doesn't work. Intellisense isn't picking up any properties named 'mode' anywhere in the options for where. Error thrown is "Unknown arg 'mode'"

## How to reproduce

Enable the preview feature in schema.prisma and add mode: 'insensitive' to the query.

```js
return await db.user.findMany({
  where: {
    name: { contains: userName, mode: 'insensitive' }, // throws error
    // also fails inside of OR
    OR: [
      {
        name: { contains: userQuery, mode: 'insensitive' }, // throws error
      },
      {
        email: { contains: userQuery },
      },
    ],
  },
  select: { email: true, id: true, name: true },
})
```

## Expected behavior

Case-insensitive filtering should work.

## Prisma information

It's the latest version. I've enabled the preview feature in schema.prisma.

## Environment & setup

- OS:  macOS
- Database:  PostgreSQL 13
- Node.js version:  14.10
- Prisma version: 2.7.1

```
@prisma/cli          : 2.7.1
Current platform     : darwin
Query Engine         : query-engine 5c2ad460cf4fe8c9330e6640b266c046542c8b6a (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 5c2ad460cf4fe8c9330e6640b266c046542c8b6a (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 5c2ad460cf4fe8c9330e6640b266c046542c8b6a (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 5c2ad460cf4fe8c9330e6640b266c046542c8b6a (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.288.0
```

**Comment by pantharshit00** [comment]
Hi @aaronfulkerson 

I am unable to reproduce this, can you please paste what error the above query is throwing for you?

A screenshot will also be helpful.

**Comment by aaronfulkerson** [comment]
![Screen Shot 2020-09-29 at 12 21 34 PM](https://user-images.githubusercontent.com/31112737/94599994-81019000-024e-11eb-8907-4173b5897a93.png)

**Comment by Sytten** [comment]
If I am not mistaken the feature flag was removed in 2.8.0, since you are still on 2.7.1 you need the feature flag

**Comment by aaronfulkerson** [comment]
I filed this bug before 2.8.0 was released and took that screenshot on 2.7.1. Though I did upgrade to 2.8.0 and remove the previewFeature flag, the error remains.

**Comment by janpio** [comment]
Can you double check your version of `@prisma/client`? Did you regenerate your Client after updating?

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/94664493-90eda280-0328-11eb-8428-2e6384c0e197.png)

I am still unable to reproduce this with `2.8.0` as you can see in the above screenshot. Please make sure you have the latest version. Make sure it by deleting `node_modules`.

If you can still reproduce this, please share a reproduction inside of a git repository.

**Comment by aaronfulkerson** [comment]
@janpio I completely removed node_modules after updating. The postinstall hook is running after install.

@pantharshit00 Could it be something with my environment? I'm on macOS. Maybe the binaries for Darwin are broken or something?

**Comment by pantharshit00** [comment]
@aaronfulkerson I am also on MacOS


Please make a minimal reproduction repository so that we can look into this

**Comment by aaronfulkerson** [comment]
I figured out what was going on. For some reason the datasource provider contained both sqlite and postgres. Removing sqlite so that just postgres remained solved the problem.

**Comment by miguelramirezv** [comment]
Hello @aaronfulkerson , I hope you are doing great! 

I'm having the exact problem as you and I'm using Postgres by Docker so I was wondering that I might have the exact problem that you had. How did you uninstalled SQLite only in that project? (I'm not a big expert in programming)

**Comment by aaronfulkerson** [comment]
@miguelramirezv hello friend, find the file schema.prisma and change the following line:

```
datasource db {
  provider = ["sqlite"] // <-- change "sqlite" to "postgres"
  url      = env("DATABASE_URL")
}
```

**Comment by miguelramirezv** [comment]
Than you friend @aaronfulkerson ! It helped a lot!! 🤩

**Comment by John-Dave** [comment]
MySQL provider
MySQL uses case-insensitive collation by default. Therefore, filtering with Prisma Client and MySQL is case-insensitive by default.

mode: 'insensitive' property is not required and therefore not available in the generated Prisma Client API.

Caveats
You must use a case-insensitive (_ci) collation in order to support case-insensitive filtering. Prisma Client does no support the mode filter property for the MySQL provider.
