### ISSUE TITLE
@unique directive not working on mongo db datamodel  

### ISSUE THREAD

**Issue by bacharSalleh** [prisma/prisma#3765]
Prisma is connected to MongoDb and everything is working good but when I add @unique directive to field and redeploy prisma, then I still can create more than one user with same email.

DataModel:
type User {
id: ID! @id
name: String!
email: String @unique

}

**Comment by pantharshit00** [comment]
Hi @bacharSalleh,


I believe this feature is currently in the beta image of prisma. Please try that using this with the beta image of prisma.
