### ISSUE TITLE
Prisma client - selection set

### ISSUE THREAD

**Issue by affanshahid** [prisma/prisma#3770]
I was previously using prisma bindings which allowed me to specify selection sets coming from the UI. I have migrated to the prisma client and the documentation doesn't specify if selection sets are supported.

So if the UI requests `A, B and C` scalar fields, the prisma client will also load scalar fields `D, E and F` even though they won't be sent to the client. Is this expected or am I missing something?

**Comment by pantharshit00** [comment]
Hi @affanshahid, Great Question!

The general difference between prisma client and bindings is that prisma client doesn't use schema delegation. It now acts as an ORM replacement and the API is great for building a graphql server like so:

```ts
const resolvers = {
  Post:{
    // resolve author here only once
	author: (parent, args, ctx) => {
		return ctx.prisma.post({ id: parent.id }).author();
    }
  },
  Query:{
	getPosts: (parent, args, ctx) => {
		return ctx.prisma.posts();
	},
	getPost: (parent, { id }, ctx) => {
		return ctx.prisma.post({ id });
	}
}
```

The migration from binding to the client feels odd at first but it really pays off later on. If you have any additional questions about this ask them in the forum here: https://prisma.io/forum
