### ISSUE TITLE
Special characters not handled in datamodel

### ISSUE THREAD

**Issue by kjkurtz** [prisma/prisma#3775]
Special characters are not handled in the datamodel. For example, the column name `JOB#` fails due to the `#`. This is a problem particularly with introspection of existing databases where migrations are not an option.

**To Reproduce**
1. `prisma introspect` an existing database. This correctly identifies columns with special characters and inserts it into the datamodel.
2. `prisma deploy` fails with `ERROR: Syntax error while parsing GraphQL query. Invalid input` when special characters are present in the datamodel. In this case, `#`.

**Expected behavior**
The ability to handle or escape special characters for existing (and new) fields.

**Versions (please complete the following information):**
 - OS: `macOS 10.14.2 (18C54)`
 - `prisma` CLI: `prisma/1.23.2 (darwin-x64) node-v10.13.0`
 - Prisma Server: `1.23.2`

**Comment by pantharshit00** [comment]
Hi @kjkurtz,

Unfortunately, the graphql spec doesn't allow any special characters in the name: https://facebook.github.io/graphql/June2018/#sec-Names

We use graphqljs to parse the datamodel which strictly follows the graphql spec so we will not be able to handle this.

You can try to rename the table.

**Comment by do4gr** [comment]
The upcoming data model v2 will allow you to rename names like these using the @db directive: https://github.com/prisma/prisma/issues/3404

**Comment by pantharshit00** [comment]
@kjkurtz The new datamodel is now available. See : https://github.com/prisma/datamodel-v1.1-feedback
