### ISSUE TITLE
API does not respond to Accept-encoding: gzip header

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#378]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Sunday Jun 11, 2017 at 13:59 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/110_

----

The API does not gzip responses, even if Accept-encoding: gzip header is present. For mobile app purposes, or other low bandwidth situations, gzipping responses would really help saving bandwidth.
It's not advised to do it by default, because it slightly increases latency. Adhering to the Accept-encoding header lets the user make the decision..

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Aug 16, 2017 at 00:30 GMT_

----

Any progress on this?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Aug 17, 2017 at 09:10 GMT_

----

Unfortunately not yet 🙂

**Comment by renato** [comment]
Could this issue be reopened?

**Comment by renato** [comment]
Still something interesting to have, I think.

**Comment by pantharshit00** [comment]
This is more related to GCF, so closing now.
