### ISSUE TITLE
Gather example schemas for MS SQL Server

### ISSUE THREAD

**Issue by yoshuawuyts** [prisma/prisma#3780]
In order to test the resiliency of our upcoming MS SQL Server integration we need to gather example schemas to test. The target minimum is 25 schemas.

Ref #2430 

## How can I help?

Help from the community in sourcing example schemas would be very welcome! Either by sharing existing MSSQL schemas, or by converting existing Postgres/MySQL/SQLite schemas to MS SQL Server. Building a resilient implementation is only possible through thorough testing; and sourcing a large corpus of example schemas plays an important part in that.

The preferred format to share schemas is by sharing a link to a gist in this thread.

**Comment by eemmiillyy** [comment]
Would the ideal file type for the example schemas be .bak?

**Comment by eemmiillyy** [comment]
I found this cli tool called mssql-scripter (https://github.com/microsoft/mssql-scripter/blob/dev/doc/usage_guide.md) which might be helpful for us. It allows exporting schema and data separately and also generates .sql files rather than the default .bak

**Comment by pimeys** [comment]
I'd go by storing schemas in `sql` format to the repository.

**Comment by eemmiillyy** [comment]
Opened a draft PR [here](https://github.com/prisma/database-schema-examples/pull/116) with some schemas.

**Comment by martinnormark** [comment]
[Brent Ozar](https://twitter.com/brento) has published the StackOverflow database (as of 2020/06) - huge download, perhaps too big? https://www.brentozar.com/archive/2015/10/how-to-download-the-stack-overflow-database-via-bittorrent/

> 46GB torrent (magnet.) Expands to a ~381GB SQL Server 2008 database. Because it’s so large, I only distribute it with BitTorrent, not direct download links.

**Comment by pimeys** [comment]
@martinnormark oh, cool, I'll get it to my NAS at least so we can take a look into the schema later. Thank you!

**Comment by pimeys** [comment]
Schema added here. https://github.com/prisma/database-schema-examples/commit/60c63d0b3878d8154f0e4cf59fe555e43a2033b9

It's surprisingly simple, they're not even using foreign keys or other indices than the pks...

**Comment by martinnormark** [comment]
Yeah, performance above anything, I guess.

**Comment by yoshuawuyts** [comment]
https://github.com/prisma/database-schema-examples/pull/116 has been merged, with tweaks in https://github.com/prisma/database-schema-examples/commit/a1d66e82ece7a2978b07a4cae3d64753f0e01d7e, bringing us up to 25 schemas total. This is the quota we set out to achieve, and so the issue can be closed. Fantastic work by @eemmiillyy and @divyenduz!

The example schemas can be found in: [prisma/database-schema-examples: mssql/](https://github.com/prisma/database-schema-examples/tree/main/mssql)
