### ISSUE TITLE
I don't understand select and include functionality on filters

### ISSUE THREAD

**Issue by stban94diaz** [prisma/prisma#3783]
For example:
If I have a usersWithDrafts query

![image](https://user-images.githubusercontent.com/20797115/94298362-9f544c80-ff2b-11ea-935e-43c509c55b88.png)

I would suppose that the result will return the users with the publications that are only drafts, however it returns the users with all the unfiltered publications.

![image](https://user-images.githubusercontent.com/20797115/94298707-35887280-ff2c-11ea-82a6-31ed80fa3f08.png)

Is it possible to do this ??

**Comment by ryands17** [comment]
This is more of a Nexus thing. You would need to add this in you models:

```ts
export const User = objectType({
  name: 'User',
  definition(t) {
    t.model.createdAt()
    t.model.id()
    t.model.name()
    t.model.email()
    t.model.posts({
      filtering: true, // this one
    })
  },
})
```

And your query would look like this:

```graphql
query draftts {
  users {
    name
    posts(where: { published: { equals: false } }) {
      id
      published
    }
  }
}
```

Your resolver does not need to include any extra filters.
