### ISSUE TITLE
@prisma/engine-core@2.7.1 use git://github.com/nodejs/undici.git#e76f6a37836537f08c2d9b7d8805d6ff21d1e744

### ISSUE THREAD

**Issue by erishen** [prisma/prisma#3785]
## Bug description

@prisma/engine-core@2.7.1 use git://github.com/nodejs/undici.git#e76f6a37836537f08c2d9b7d8805d6ff21d1e744

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```

```

**Comment by pantharshit00** [comment]
Resolved via https://github.com/prisma/prisma/commit/99c7e7efd8f8fdfc6041d5761ba56aad541482d4 already.

It will be part of `2.8.0` which will planned to be released today.
