### ISSUE TITLE
prisma init connect to existing mongo database does not work

### ISSUE THREAD

**Issue by SeanningTatum** [prisma/prisma#3786]
**Describe the bug**
The error `Error: The provided database doesn't contain any collection. Please either provide another database or choose "No" for "Does your database contain existing data?"` will pop out even though I selected `No` as the option

**To Reproduce**
Steps to reproduce the behavior and screenshot:
![image](https://user-images.githubusercontent.com/26712061/50559844-78a4ba00-0d35-11e9-8c03-3c13edae7f0e.png)

**Expected behavior**
Connect to database

**Versions (please complete the following information):**
prisma/1.23.2 (darwin-x64) 
node-v10.14.2

**Comment by pantharshit00** [comment]
Hi, thanks for reporting this. I can confirm this behavior and somehow this is hitting the introspection flow.

In the meanwhile, you can use these instructions: https://www.prisma.io/docs/get-started/01-setting-up-prisma-existing-database-JAVASCRIPT-a003/

Just skip **STEP 6** in this
