### ISSUE TITLE
Support for `Json` field type in SQLite

### ISSUE THREAD

**Issue by m5nv** [prisma/prisma#3786]
## Problem
SQLite has had support for JSON field type for a while. `Sequelize` [supports this field type](https://sequelize.org/master/class/lib/data-types.js~JSONTYPE.html) on par with Postgres and MySQL. 

Lack of support for this field type by Prisma is preventing us from porting over our project.

SQLite is a great bootstrapping technology that allows developers to quickly prototype applications without introducing new dependencies such as docker or worry about running yet another service in the development flow. JSON field type gives us the option to have a `nosql` database colocated in a `sql` database.

## Suggested solution
Please implement support for this feature. See [JSON ~~Extension~~](https://www.sqlite.org/json1.html) documentation and refer to `Sequelize`'s implementation if required.

## Alternatives
Defer migration to Prisma and stick with `Sequelize`. Maintain status quo.

## Additional context
![Prisma cannot handle json field type](https://user-images.githubusercontent.com/45653160/94524114-cbcfd780-024f-11eb-8250-58833c59b4b2.png)

cc: @ryands17
ref: https://github.com/prisma/prisma/discussions/3575

**Comment by empz** [comment]
Would love to see this implemented in Prisma!

**Comment by am2222** [comment]
Any updates on this?

**Comment by medihack** [comment]
Wich is fixed now 😁

**Comment by proteriax** [comment]
@matthewmueller Is this on the roadmap?

**Comment by proteriax** [comment]
@matthewmueller Is this on the roadmap?

**Comment by proteriax** [comment]
Do you have any update regarding this? Please tell us so those of us who need JSON field type support can decide whether to skip Prisma.

**Comment by davidharting** [comment]
I am interested in this to make Prisma even more viable for interacting with SQLite from an electron app or CLI app.

**Comment by WolffParkinson** [comment]
This is the first result that comes up for `Prisma JSON SQLite` search. Some response on whether this is in near future plans or not would be appreciable from the maintainers, considering this issue is over an year old.

**Comment by Quadr0** [comment]
This would be a great feature, especially for prototyping and hackathons.

**Comment by calumk** [comment]
I'd like to also vote for this feature.
Typeorm solves it with its simple-json feature.

**Comment by dinfer** [comment]
Any plan on this issue?

**Comment by proteriax** [comment]
At this point the lack of response is more concerning than the lack of this feature.

**Comment by janpio** [comment]
We never respond to feature requests unless we concretely work on issues, need more information or similar. 
That this feature request still exists (and was not closed) is our information that we consider it valid and might prioritize it in the future.

**Comment by Philzen** [comment]
With `Json` datatype being available in prisma already for MySql and Postgres, and json being natively supported in SQLite for quite a while now, this would be a huge win for inter-operability. With this issue being over 1 1/2 years standing, it would be lovely to see this on the roadmap in the near future.

Until this lands, is there any workaround that can be used for simple use cases (just querying and writing w/o and fancy filtering functions)? Idea is, that we could use this datatype in schema definitions and implement something like a custom adapter/plugin for local sqlite development to handle the de-/serialization.

**Comment by kof** [comment]
We want to support both Sqlite and PostgreSQL in [Webstudio](https://twitter.com/webstudiois) and while migrating from MongoDB discovered the missing support for JSON type too.

With the recent motion in favor of SQLite serverside by multiple startups and announcement of D1 from cloudflare, this should be a priority for Prisma.

**Comment by zomars** [comment]
Can we sponsor this feature? I'm really interested in offering a `sqlite` version of our DB (calcom/cal.com#3388) so it can be played with out of the box and our only limitation is the lack of JSON fields.

**Comment by janpio** [comment]
Relevant information that changes the situation for this issue:

> The JSON functions and operators are built into SQLite by default, as of SQLite version 3.38.0 (2022-02-22). 
> [...] 
> Prior to version 3.38.0, the JSON functions were an extension that would only be included in builds if the -DSQLITE_ENABLE_JSON1 compile-time option was included. In other words, the JSON functions went from being opt-in with SQLite version 3.37.2 and earlier to opt-out with SQLite version 3.38.0 and later.
> via https://www.sqlite.org/json1.html

🚀!

What could help here right now:
If _someone_ has an application that makes use of a lot of Prisma's Json functionality, it would be awesome if you could collect the queries Prisma generates in PostgreSQL (https://pris.ly/d/logging) for your app and then would try to run these against a SQLite database where you added the Json column by hand. Do they all work out of the box?

**Comment by noxware** [comment]
+1

**Comment by janpio** [comment]
Because JSON was not enabled by default in the past, see the message above.

**Comment by zomars** [comment]
> run these against a SQLite database where you added the Json column by hand.

What do you mean by "add the Json column by hand"? @janpio

**Comment by janpio** [comment]
Prisma can not handle and create JSON columns for SQLite. So to be able to test the queries we use, you would need to add a Json column manually to the SQLite database and then run the queries against that SQLite database with that column present to be able to tell us if they all work, or horribly crash.

**Comment by jimablue** [comment]
hi janpio, appreciate the work! 
I added a JSON column manually and have been using prisma.$queryRaw() method to SELECT and UPDATE that column for the past week. So far everything works out of the box for me! Hope it helps

**Comment by LeonFedotov** [comment]
+1 
would love to use sqlite in dev and need that json type 
please add support

**Comment by biels** [comment]
+1 to this, now JSON is natively supported in SQLite

**Comment by jonasmerlin** [comment]
+1

**Comment by zomars** [comment]
Can we at least enable it under a preview feature flag?

**Comment by janpio** [comment]
If someone does a PR to add it to our codebases under a preview feature flag, sure. To be accepted it will require tests as well though. We currently are working on other things, so this is a not a priority and no one can spend time on it. As soon as this changes, we might tackle this.

**Comment by jonasmerlin** [comment]
@janpio Really don't get why my "+1" comment above was "marked as abuse" (I'm assuming this was done by you or someone else in the Prisma team since I can't seem to report other comments as abuse. If not, I'm sorry.) I sense a mild annoyance with this feature request in general in your comments and to a certain degree I get that, but to quote from the [prisma guidelines for feature requests](https://github.com/prisma/prisma#submit-a-feature-request): 

> If the feature on the roadmap is linked to a GitHub issue, please make sure to leave a +1 on the issue and ideally a comment with your thoughts about the feature!

I didn't add a comment since I felt it wouldn't add much, since the feature was clear and already discussed extensively. I don't know if these reports are something that GitHub tracks about me, but I wouldn't want for this to lead to any issues with my account in the future so I would really appeciate it if you could reverse the report if that is possible.

**Comment by janpio** [comment]
I updated the README to avoid such a misunderstanding, and clarified that issues should get a 👍 reaction. 

`+1` comments are pure noise that keep us from responding to actual issues and comments. We get dozens of these per day, hundreds per week, which led to most colleagues not even reading the comments on feature requests anymore. Users that leave actual comments on issues are complaining that they get notifications and emails for updates - to then nothing useful or helpful. If we don't hide them, we will get more and more and our issues will get less and less useful to us and our users. (And no, those are not reports to GitHub but just a local way to hide comments that do not add anything to the discussion. But I deleted your comment instead so there is not "abuse" label on your comment even in this repository - the mention of this in the issue timeline is why we usually do not do that - it often leads to even _more_ questions that are offtopic to the actual issue).

And that you "sense mild annoyance with this feature request" is you reading too much into what I wrote (or did not write). I am pretty eager to get this feature implemented - just don't have the capacity to prioritize it right now.

**Comment by rogeriorioli** [comment]
the basics of javscript **JSON.stringfy**

model Teste {
  json String
}

{

   data : {
     json :  JSON.stringfy(OBJECT) 
   }
}

**Comment by entrptaher** [comment]
Maybe we can use sqld to mimic postgresql for now, and test prisma against it?

https://github.com/libsql/sqld

**Comment by jdkdev** [comment]
I wanted to add my eagerness for this to be implemented as well, as well as get notified if there is movement on this ticket!

Thanks Prisma team!

**Comment by mikeseese** [comment]
@janpio 

> If someone has an application that makes use of a lot of Prisma's Json functionality, it would be awesome if you could collect the queries Prisma generates in PostgreSQL ([pris.ly/d/logging](https://pris.ly/d/logging)) for your app and then would try to run these against a SQLite database where you added the Json column by hand. Do they all work out of the box?

I'm not sure why it's taken this long for someone to pipe up here, but the answer is simply "no" here. Here are some initial findings with a small subset of the functions, but I didn't bother continuing to research as they just seem like the Prisma implementation of how it handles the JSON queries is just not compatible with SQLite.

My Prisma model is:

``` prisma
model User {
  id String @id @default(uuid())
  data Json
}
```

An `INSERT` using a postgres datasource looks like:

``` SQL
INSERT INTO "public"."User" ("id","data") VALUES ($1,$2) RETURNING "public"."User"."id", "public"."User"."data"
["918bab14-5f26-4ef5-bed9-0661156a09a7",{"foo":"bar"}]
```

but SQLite expects the `$2` param to be text. For example `{"foo":"bar"}` needs to become `'{"foo":"bar"}'`.

Perhaps that's a logging or library manipulation mismatch issue however, so looking at one of the more complicated queries:

``` ts
await prisma.user.findFirst({
  where: {
    data: {
      path: ["foo"],
      equals: "bar"
    }
  }
});
```

looks like:

``` postgresql
SELECT "public"."User"."id", "public"."User"."data" FROM "public"."User" WHERE ("public"."User"."data"#>ARRAY[$1]::text[])::jsonb::jsonb = $2 LIMIT $3 OFFSET $4
["foo","bar",1,0]
```

SQLite errors: `SQLITE_ERROR: unrecognized token: "#"` which makes sense because there is no `#>` or `#>>` operator in the SQLite JSON functions, only `->` and `->>`. Mind you, the `::json` or `::jsonb` tokens would also likely choke.

A comparable call in SQLite would look like:

``` sql
SELECT "User"."id", "User"."data" FROM "User" WHERE "User"."data"->>'$.foo' = '"bar"' LIMIT 1 OFFSET 0
```

or

``` sql
SELECT "User"."id", "User"."data" FROM "User" WHERE "User"."data"->>'$.foo' = 'bar' LIMIT 1 OFFSET 0
```

or removing the `$.` in front of `foo` also works

**Comment by weleo** [comment]
[SQLite’s 3.45.0 release](https://sqlite.org/releaselog/3_45_0.html) introduces changes to JSON data handling, using JSONB as the new internal format for all JSON functions, which now generate binary JSONB under the hood.

This might be a good time to revisit the implementation of JSON field type support in Prisma for >= SQLite 3.45.0.

**Comment by ryantando** [comment]
Is there any temporary solution for this?

**Comment by mikeseese** [comment]
@ryantando I am specifying the type of the field as `String` in the schema and then provide extensions to transform the string to/from JSON in the client creation:

``` typescript
client = new PrismaClient({
  datasourceUrl,
}).$extends({
  result: {
    playerCharacter: {
      metadata: {
        needs: { metadata: true },
        compute(obj) {
          return JSON.parse(obj.metadata as string);
        },
      },
    },
  },
  query: {
    playerCharacter: {
      create({ args, query }) {
        args.data.metadata = JSON.stringify(args.data.metadata);
        return query(args);
      },
      update({ args, query }) {
        if (args.data.metadata !== undefined) {
          args.data.metadata = JSON.stringify(args.data.metadata);
        }
        return query(args);
      },
      updateMany({ args, query }) {
        if (args.data.metadata !== undefined) {
          args.data.metadata = JSON.stringify(args.data.metadata);
        }
        return query(args);
      },
      upsert({ args, query }) {
        args.create.metadata = JSON.stringify(args.create.metadata);
        if (args.update.metadata !== undefined) {
          args.update.metadata = JSON.stringify(args.update.metadata);
        }
        return query(args);
      },
    },
  },
});
```

**Comment by why-not-try-calmer** [comment]
I'd be super happy if this could happen! Is there a pending PR on this?

**Comment by TeemuKoivisto** [comment]
Well isn't this a bummer. I thought I could just switch from Postgres to D1 and keep my ol trusty Prisma and not have to learn any new syntax or framework. Seems I have to reconsider my options. Maybe use another ORM possibly. Writing queries by hand just gets too tedious for me.

**Comment by Noitidart** [comment]
> Well isn't this a bummer. I thought I could just switch from Postgres to D1 and keep my ol trusty Prisma and not have to learn any new syntax or framework. Seems I have to reconsider my options. Maybe use another ORM possibly. Writing queries by hand just gets too tedious for me. Maybe give that Drizzle a shot.

For now I'm treating it as a string, and then just `JSON.parse` when I need to use it. It's worth it to me due to the speed issues with having just Postgres sit in one region.

**Comment by coodoo** [comment]
Out of curiosity why it's taking so long for prisma to support `json1` type for sqlite when it already supports `jsonb` type for postgresql? (not to blame or rush anything, just purely curious)

**Comment by gsxdsm** [comment]
Would like to see this as well

**Comment by Philzen** [comment]
It's unbelievable … 4 years later and Prisma goes en par with sequelize and drizzle on this. Can't wait for 6.2 to release. :rocket: 

Thanks heaps to @jacek-prisma and @jkomyno for finally making this happen. :pray:

**Comment by LazerJesus** [comment]
wonderful! 
any guess whats the eta on the 6.2 release?

**Comment by jkomyno** [comment]
>wonderful!
any guess whats the eta on the 6.2 release?

Thanks! It'll be shipped in ~24 hours or so. This feature is already available on `prisma@dev` (unstable)

**Comment by LazerJesus** [comment]
@jkomyno thank you for the update. I ran the @dev branch and can confirm that my JSON fields are no longer an issue. Altho now my enums are 😆 I did some reading and saw that you're also planning enum support for 6.2. (what a great release!). any idea when /that/ is expected to land on dev?

**Comment by jdkdev** [comment]
I don't know the best place to ask this:

Based on how sqlite handles/stores json and text blobs...

If I update my prisma file like so, is that doable?  Or is there a better way to approach it?
![image](https://github.com/user-attachments/assets/ff8ead11-9636-4319-baf8-fc42bd01da47)

**Comment by a-eid** [comment]
I am still getting `Unsupported type Json for database sqlite`, with latest prisma. when using `prisma generate`.
