### ISSUE TITLE
Implement env var `FORCE_PANIC_INTROSPECTION_ENGINE`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#3788]
In this PR https://github.com/prisma/prisma/pull/3694 @williamluke4 implemented `FORCE_PANIC_MIGRATION_ENGINE`

We could have one for introspection engine.

It will be helpful for this issue https://github.com/prisma/prisma/issues/3779
And https://github.com/prisma/prisma/pull/3790

**Comment by janpio** [comment]
Note: needs a Engine issue for that part of the implementation.

**Comment by timsuchanek** [comment]
Fixed by https://github.com/prisma/prisma/pull/3859
