### ISSUE TITLE
Add support for @default(between([1, 1000]))

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/prisma#380]
I found out about between here → https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#functions

So I did the following in `prisma/schema.prisma`:

```graphql
model Pokemon {
  id      String         @default(cuid()) @id @unique
  number  Int            @default(between([1, 1000000])) @unique
  name    String
  attacks PokemonAttack?
}
```

I thought the `number` field was supposed to work but VSCode extension gives an error.

So I did `prisma2 generate` but it threw this:

```js
Error: Schema parsing error: Function not known: "between".
  -->  schema.prisma:17
   | 
16 |   id      String         @default(cuid()) @id @unique
17 |   number  Int            @default(between([1, 1000000])) @unique
18 |   name    String
```

**Comment by pantharshit00** [comment]
This hasn't been implemented yet

**Comment by matthewmueller** [comment]
I'm going to close this since it's easy to do at the application layer and I don't see a strong reason to put it in the database or prisma-layer. 

If you have a use case for this function please comment below and we'll re-open!
