### ISSUE TITLE
Author relation not created in PostWhereInput struct in Go following the directions for MongoDb

### ISSUE THREAD

**Issue by mahkali** [prisma/prisma#3804]
**Describe the bug**
I have followed the documentation to setup the prisma binding for GraphQL MongoDb for Go. There is a line missing from the generated prisma-client/prisma.go

**To Reproduce**
1. Follow all the steps in the documentation.
2. Here: https://www.prisma.io/docs/1.23/get-started/03-build-graphql-servers-with-prisma-GO-g201/#start-the-graphql-server

$ go run ./server
\# hello-world/server
server/resolver.go:68:4: unknown field 'Author' in struct literal of type "hello-world/generated/prisma-client".PostWhereInput

**Expected behavior**
I would like to see:
$ go run ./server
2019/01/04 01:48:19 Server is running on http://localhost:4000

**Screenshots**
I see:
$ go run ./server
\# hello-world/server
server/resolver.go:68:4: unknown field 'Author' in struct literal of type "hello-world/generated/prisma-client".PostWhereInput

**Versions (please complete the following information):**
 - OS: OS X Mojave
 - `prisma` CLI: prisma/1.23.2 (darwin-x64) node-v8.11.2

Dep files:
[Gopkg.zip](https://github.com/prisma/prisma/files/2725738/Gopkg.zip)

**Additional context**

The following line is missing in ~/go/src/hello-world/generated/prisma-client/prisma.go

`Author             *UserWhereInput  `json:"author,omitempty"`

This is not automatically generated by the cli command `prisma generate`.

I copied this from 
https://github.com/prisma/prisma-examples/blob/master/go/graphql/prisma-client/prisma.go#L646

**Comment by pantharshit00** [comment]
Hi @mahkali,

I am unable to reproduce your problem. I used the following datamodel:

```graphql
type User {
  id: ID! @unique
  email: String @unique
  name: String!
  posts: [Post!]!
}

type Post {
  id: ID! @unique
  title: String!
  published: Boolean! @default(value: "false")
  author: User
}
```
and the following schema to follow along the tutorial:
```graphql
type Query {
  publishedPosts: [Post!]!
  post(postId: ID!): Post
  postsByUser(userId: ID!): [Post!]!
}

type Mutation {
  createUser(name: String!): User
  createDraft(title: String!, userId: ID!): Post
  publish(postId: ID!): Post
}

type User {
  id: ID!
  email: String
  name: String!
  posts: [Post!]!
}

type Post {
  id: ID!
  title: String!
  published: Boolean!
  author: User
}
```

and the server started fine:
![image](https://user-images.githubusercontent.com/22195362/50725285-58a03c80-1121-11e9-9c1d-028bef1571e9.png)

That line does indeed get autogenerated so please check you datamodel and schema:
![image](https://user-images.githubusercontent.com/22195362/50725292-85545400-1121-11e9-81c6-0e8dec4a4523.png)

**Comment by rickbolton** [comment]
@pantharshit00 I've just run into the same issue using MongoDB. Hopefully following this will allow you to replicate as the datemodel you have shared looks to be for SQL.

**Comment by pantharshit00** [comment]
Thanks @rickbolton, Sorry I completely overlooked the part that you are using mongo. I am able to reproduce this now:
![image](https://user-images.githubusercontent.com/22195362/51126958-64d77880-184a-11e9-961f-561baf4f104d.png)

reproduction repository: https://github.com/pantharshit00/prisma-issue-3804


cc @timsuchanek

**Comment by pantharshit00** [comment]
I am no longer able to reproduce this with the new version of Prisma(1.30). Feel free to open a new issue if you are still experiencing this
