### ISSUE TITLE
executeRaw renames returned columns

### ISSUE THREAD

**Issue by jacobpgn** [prisma/prisma#3808]
Prisma Server: 1.23.4 w/ MySQL

When executing "raw" SQL, Prisma renames column rows in the returned dataset to the name of the table column it originally came from.

This behaviour means that:
- any aliased columns lose their aliases
- any duplicate column names (e.g. from a join) are lost, and only one of the values is used (but you won't know which)

### Example query 

```
mutation {
  executeRaw(
    query: "SELECT User.id, Organisation.id AS organisationId, Organisation.name AS organisationName, User.name FROM User LEFT JOIN Organisation ON Organisation.id = User.organisationId "
  )
}
```

That same SQL formatted for easier reading:

```sql
SELECT User.id,
       Organisation.id AS organisationId,
       Organisation.name AS organisationName,
       User.name
FROM   User
       LEFT JOIN Organisation
              ON Organisation.id = User.organisationId 
```
### Actual behaviour 

I'd expect an array of `{ id, organisationId, organisationName, name }` but instead I get an array of `{ id, name }` (I _think_ that's `Organisation.id` and `User.name`, because those were the last in the result set):

Actual response:
```json
{
  "data": {
    "executeRaw": [
      {
        "id": "cxxx-mysteryid",
        "name": "Søren"
      },
      {
        "id": "cyyy-mysteryid",
        "name": "Johannes"
      }
    ]
  }
}
```

### Expected behaviour 

My expected behaviour here would be that the keys of each element would exactly match the columns in the query result, and not be renamed to the underlying table column's name. I'd expect this because the function of "raw database access" implies that the input and output won't be transformed.

Expected response:
```json
{
  "data": {
    "executeRaw": [
      {
        "id": "cyyy-userid",
        "name": "Søren",
        "organisationId": "cxxx-organisationid",
        "organisationName": "Prisma"
      },
      {
        "id": "cwww-userid",
        "name": "Johannes",
        "organisationId": "czzz-organisationid",
        "organisationName": "Amsirp"
      }
    ]
  }
}
```

**Comment by pantharshit00** [comment]
Hi @jacobpgn,

Can you please provide me your datamodel so that I can try to reproduce this bug?

**Comment by jacobpgn** [comment]
Hey @pantharshit00 👋! Here's a working example that doesn't require any particular data model:

**SQL:**
```sql
SELECT User.id,
       Organisation.id AS organisationId,
       Organisation.name AS organisationName,
       User.name
FROM
  (SELECT 'c123' AS id,
          'Harshit' AS name) AS User
INNER JOIN
  (SELECT 'c456' AS id,
          'Prisma' AS name) AS Organisation
```

**The above SQL as an `executeRaw` query:**
```graphql
mutation {
  executeRaw(
    query: "SELECT User.id, Organisation.id AS organisationId, Organisation.name AS organisationName, User.name FROM ( SELECT 'c123' AS id, 'Harshit' AS name ) AS User INNER JOIN ( SELECT 'c456' AS id, 'Prisma' AS name ) as Organisation"
  )
}
```

**Expected result:**
```json
{
  "data": {
    "executeRaw": [
      {
        "id": "c123",
        "organisationId": "c456",
        "organisationName": "Prisma",
        "name": "Harshit"
      }
    ]
  }
}
```
See also [this SQL Fiddle](http://sqlfiddle.com/#!9/9eecb/75125/0) showing what the DB returns.

**Actual result:**
```json
{
  "data": {
    "executeRaw": [
      {
        "id": "c456",
        "name": "Harshit"
      }
    ]
  }
}
```

**Comment by jacobpgn** [comment]
Hey there @pantharshit00!

Just saw that you re-added the "needs info" label – is there something else you need from my side?

**Comment by pantharshit00** [comment]
@jacobpgn We accidentally lost some label data so I added them again via the API. Sorry if it caused any confusion.

**Comment by pantharshit00** [comment]
I can confirm this behavior. Probably some of our internal logic is block fields that are not defined in the schema.

*Internal*: [reproduction repository](https://github.com/pantharshit00/prisma-issue-3808)
