### ISSUE TITLE
Model's `WhereInput` are not behaving as expected

### ISSUE THREAD

**Issue by ivorpad** [prisma/prisma#3813]
**Describe the bug**

Querying fields with `id_contains`, `id_ends_with`, `id_starts_with`, `id_not_contains`, `id_not_ends_with`, `id_not_starts_with` is not working as expected.

Given an ID `5c2eb7d56344590009c22341`, this query returns an empty array.

```graphql
{
  users(where: {id_ends_with: "c22341" }) {
    id
  }
}
```

It is only happening with ID, the rest of the fields are returning the expected results.

**Expected behavior**

It should return an array with a User where ID ends with the provided string.

**Screenshots**

<img width="367" alt="screen shot 2019-01-06 at 09 09 18" src="https://user-images.githubusercontent.com/52452/50736335-c9337180-1192-11e9-9c81-65a6e1ccdedd.png">

<img width="709" alt="screen shot 2019-01-06 at 09 08 02" src="https://user-images.githubusercontent.com/52452/50736317-98ebd300-1192-11e9-88a5-5131dce5993d.png">

**Versions (please complete the following information):**
 - OS: OS X High Sierra
 - `prisma` v1.22

**Comment by pantharshit00** [comment]
Hi @ivorpad,


I believe this feature is properly implemented in the current beta so can you use the `1.24-beta` image.

**Comment by ivorpad** [comment]
Thanks @pantharshit00,

I upgraded my prisma image to `prismagraphql/prisma:1.24-beta` and I'm still having the same issue.

**Comment by mavilein** [comment]
@ivorpad : which connector are you using?

**Comment by do4gr** [comment]
Thanks for reporting this. 

This is a result of us choosing ObjectIds as Ids in Mongo. All the non-functioning filters are implemented as reg-exes and only work on StringIds. 

There seems to be no simple way to make those partial match filters work on ObjectIds, so my preference would be to remove those if ObjectIds are used. Once we allow StringIds we could restore those again.

What is your use case that you need partial matches on ids for if I may ask?

**Comment by ivorpad** [comment]
Thanks @do4gr, 

>What is your use case that you need partial matches on ids for if I may ask?

I was just trying to compose my URLs like so:  `example.com/item/c22341-item-slug` and find the item with `id_ends_with`, there are plenty ways to do this but thought it was a nice little feature of Prisma.

**Comment by pantharshit00** [comment]
@ivorpad 

This looks more this a feature request to me now. Can you please open a new issue and close this one.
