### ISSUE TITLE
Filter based on number / count of relations

### ISSUE THREAD

**Issue by livelo-app** [prisma/prisma#3821]
## Problem
I have an e-commerce platform that requires me to list cities if there is an associated product with that city. However, we have a couple cities that there is currently no products associated with and therefore we don't want those cities to show up.

```prisma
model Locations {
  id                       Int        @default(autoincrement()) @id
  country                  String
  location                 String     @unique
}

model Products {
  id               Int           @default(autoincrement()) @id
  title            String
  city             String
  base_price       Int
  hidden           Boolean       @default(false)
  locations        locations     @relation(fields: [city], references: [location])
}
```

Assuming I have 3 cities: Boston, New York City, Miami.

Boston and New York City both have products. However, Miami does not have a product associated with that location.

On my `prisma.Locations.findMany({})`, I only want to get Boston and New York City since Miami does not have any products associated with it.

How can I go about this?

## Suggested solution
```
    const paths = await prisma.locations.findMany({
      where: {
        Products: {
          not: null // anything to show product relations greater than 0
        }
      }
    })
```

### Additionally
Additionally, another feature would be to not only check if there is a relation but filter it based on relations that I don't want appearing. For example if Miami in this case did have 1 product. But the product appeared as `hidden: true`. I would not want Miami to appear under `prisma.locations.findMany()` because the only product that it has is considered `hidden: true`.

**Comment by kevrat** [comment]
Exactly the same problem

**Comment by pantharshit00** [comment]
@livelo-app Locations are neither nullable nor they are in a one to many or many to many relation so with this schema, it is impossible to have product without a location. Are you sure this is the schema you are using in your application?

**Comment by kokokenada** [comment]
I have the same issue in the opposite way.  A Message table and a MessageEvent table.  I'd like to find messages with no related events.  Something like:
````
message.findMany({where: userId: 'whoever', MessageEvent: {none:{messageId:  <the message id of the parent record>}}....
````

**Comment by kokokenada** [comment]
@livelo-app - maybe with your data model something in your database could be used so the "some" would be true for Boston and New York. https://www.prisma.io/docs/concepts/components/prisma-client/filtering/#filter-on-related-records

**Comment by matthewmueller** [comment]
@kokokenada, does `none` work for your use case? https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#none

**Comment by matthewmueller** [comment]
Closing, but happy to re-open if none or some doesn't work for you.

**Comment by viperfx** [comment]
any reason why this feature request was closed? Filtering or ordering on counts of related fields will be really useful

**Comment by matthewmueller** [comment]
@viperfx I'm under the impression that `none` or `some` would solve this use case: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#some

Happy to re-open if that's not the case. I just need an example to work off of 🙂

**Comment by alimehasin** [comment]
It would be great if we can filter the **users** based on a min and a max number of **posts** (Get all users users that has posts **between 3 and 10**)

**Comment by jsoneaday** [comment]
What about greater than or less than? And contains?

**Comment by janpio** [comment]
If this does not exist yet, please open a new issue as a feature request so we can prioritize it. Does not work with comments on closed issues :D Thanks.
