### ISSUE TITLE
The dropdown doesn't work on the doc link from the npm page

### ISSUE THREAD

**Issue by AndrewRayCode** [prisma/prisma#3822]
https://www.prisma.io/docs/1.16/get-started/01-setting-up-prisma-existing-database-a003/

Clicking the "Prisma 1.16" dropdown doesn't do anything

**Comment by pantharshit00** [comment]
He is referencing to these links. cc @nikolasburk 

![image](https://user-images.githubusercontent.com/22195362/50876936-8e7d4380-13f5-11e9-896f-2ec3e7ded382.png)

(the existing db one)

**Comment by pantharshit00** [comment]
This has been fixed now
