### ISSUE TITLE
Disconnect does not work with UUIDs

### ISSUE THREAD

**Issue by b33son** [prisma/prisma#3823]
**Describe the bug**
When using UUID instead of ID, disconnect silently fails to disconnect and remove the relationship between entities. I believe it's a feature to silently fail, but it should be able to remove IDs which exist. 

**To Reproduce**

Given a list of users with UUIDs. Disconnect from Campaign entity. 

```
ctx.prisma.updateCampaign({
      data: {
        campaignLeads: {
          disconnect: [
            {
              id: "1066c26c-b76b-4b26-afb9-2e5160a486b3",
            },
            {
              id: "1571c0ec-06dc-4ec7-a5ba-2a37dc96d28d",
            },
          ],
        },
      },
      where: {
        id,
      },
    });
```

**Expected behavior**
The users with the two UUIDs above should be disconnected from the Campaign entity. 
 

**Versions (please complete the following information):**
 prisma/1.23.4 (darwin-x64) node-v11.2.0
 "dependencies": {
    "@types/bcrypt": "^3.0.0",
    "@types/jest": "^23.3.10",
    "@types/jsonwebtoken": "^8.3.0",
    "bcrypt": "^3.0.2",
    "graphql-shield": "^4.1.0",
    "graphql-yoga": "^1.16.7",
    "jsonwebtoken": "^8.4.0",
    "prisma-client-lib": "^1.23.0-test.3"
  },
  "devDependencies": {
    "apollo-boost": "^0.1.22",
    "apollo-cache-inmemory": "^1.3.11",
    "apollo-client": "^2.4.7",
    "apollo-link-http": "^1.5.7",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.10.0",
    "graphqlgen": "0.4.0",
    "jest": "^23.6.0",
    "json-stringify-extended": "^2.0.0",
    "moment": "^2.22.2",
    "nodemon": "1.18.7",
    "ts-jest": "^23.10.5",
    "ts-node": "^7.0.1",
    "typescript": "^3.2.1"
  },

**Additional context**
This is likely similar to #3757  #3780  which was fixed 6 days ago in #3793 . But I don't believe the issue affecting disconnect has been identified yet.

**Comment by mavilein** [comment]
@b33son : Which connector are you using?

**Comment by b33son** [comment]
This is happening in the prisma client: 

import { GraphQLServer } from "graphql-yoga";
import { resolvers } from "./resolvers";
**import { prisma } from "./generated/prisma-client";**
import { permissions } from "./permissions";

export const server = new GraphQLServer({
  typeDefs: "./src/schema.graphql",
  resolvers,
  middlewares: [permissions],
  context: (request: any) => {
    return {
      ...request,
      prisma
    };
  }
} as any);

**Comment by mavilein** [comment]
@b33son : By connector i meant database connector. So which database are you using?

**Comment by b33son** [comment]
I’m using Postgres.

**Comment by pantharshit00** [comment]
I am unable to reproduce this in the latest version of prisma `1.24.0`

Things I used:

*Datamodel*:
```graphql
type User {
  id: UUID! @unique
  name: String!
  organisations: [Organisation!]!
}

type Organisation {
  id: UUID! @unique
  name: String!
  user: User
}

```

*index.js*
```js
const { prisma } = require('./generated/prisma-client')

;(async () => {
  const resp = await prisma.updateUser({
    data: {
      organisations: {
        disconnect: [
          { id: '4af18000-7ad0-48a2-b2ed-53bcbffa38ff' },
          { id: '09523839-921a-4ad1-8a6f-f116970f2859' },
        ],
      },
    },
    where: { id: 'b18e020f-f9e9-49e5-9834-96f6910a48b2' },
  })
  console.log(resp)
})()

```

It disconnected them properly:

Before:
![image](https://user-images.githubusercontent.com/22195362/51125236-335cae00-1846-11e9-813b-64c7860e797a.png)

After running index.js:
![image](https://user-images.githubusercontent.com/22195362/51125266-42dbf700-1846-11e9-927c-bfe1f3c4c992.png)

**Comment by b33son** [comment]
I was on 1.23.3. I switched to 1.24 and tried again. I can confirm the issue is now resolved. Thank you. I'm closing this one.
