### ISSUE TITLE
Feature request: Allow `$queryRaw` and `$executeRaw` in transactions

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#3828]
As of today, it's not possible yet, to do the following:

```ts
await prisma.$transaction([ prisma.$queryRaw`SELECT 1` ])
```

This is a feature request to both allow `$queryRaw` and `$executeRaw` being executed in a transaction.

If you have this use-case, please let us know in this issue.

**Comment by zachasme** [comment]
We have a simple schema migration system and wish replace the current `pg` client with `prisma` (which we are using for the rest of the application). The most critical migrations usually require multiple queries so until we can run each migration (which is a set of sql statements) in a transaction we have to keep both PostgreSQL clients.

**Comment by robmurtagh** [comment]
I also have this use case 🙋 .

In principle this would be a workaround [to the missing `createMany` issue](https://github.com/prisma/prisma-client-js/issues/332)

**Comment by pbelbin** [comment]
I too have come across this issue.

**Comment by Sytten** [comment]
My use case is for locks and queries that are not yet supported. Currently I don't have a way to get an advisory lock.

**Comment by dpetrick** [comment]
This will be possible with the upcoming 2.10 release.
