### ISSUE TITLE
Duplicate entry for key 'AB_unique' #2

### ISSUE THREAD

**Issue by vjsingh** [prisma/prisma#3838]
**Describe the bug**
I am seeing this bug again in the (al)most recent version of prisma (1.23.2). Getting an internal server error when attempting to connect a node which already exists.
https://github.com/prisma/prisma/issues/2893

**To Reproduce**
I unfortunately don't have time to create a small reproduction right now, but this is what I am doing in my app:

```
type User {
  id: string
}

type Note {
  users: [User!]!
}

mutation {
 updateNote (
   data:    {
     users: {
       connect:{
         id: “cjiakymv3pq060b73d4oz056p”
       }
     }
   },
   where: {
     id: “cjqh6imbr22xp0831r8581qu4"
   }
 ) {
   id
 }
}
```

**Screenshots**

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server: 1.23.2
 - `prisma` CLI: prisma/1.23.2 (darwin-x64) node-v10.4.0
 - OS: OSX High Sierra

@divyenduz

**Comment by pantharshit00** [comment]
This has been resolved in a slack conversation. The original author was unknowingly using an older version of prisma.

**Comment by vjsingh** [comment]
Fixed by updating the prisma server version in docker-compose.yml, and then running:
`docker-compose down
docker-compose up -d`
