### ISSUE TITLE
Embedded type with user-defined type in it

### ISSUE THREAD

**Issue by soqt** [prisma/prisma#3845]
**Describe the bug**
If we have a data models & relations like below

```graphql
type user  {
  id: @id
  name: String
  acceptedJobs: [Job!]!
}

type Job {
  id: @id 
  title: String
  freelancers: [Freelancer!]!
}

type Freelancer @embedded{
  user: User! @relation(link: INLINE)
  status: ACTIVE
}
```
When I try to deploy these models using mongo connector. I got error a message "The type `Freelancer` specifies the back relation field `user`, which is disallowed for embedded types."
Which makes sense. However, technically Freelancer is an extension to Job type. The only way I tested to solve it is to entirely remove Freelancer embedded type, and write Job type like this
```graphql
type Job {
  id: @id 
  title: String
  freelancers: [User!]! @relation(link: INLINE)
}
```

But I would completely lose "status" field. Is this a bug or are there work arounds?

**Versions (please complete the following information):**
 - Connector:  MongoDB
 - Prisma Server: 1.24.0
 - `prisma` CLI: prisma/1.24.0 (darwin-x64) node-v10.4.0
 - OS: OS X High Sierra

**Comment by pantharshit00** [comment]
I would have used the following model in your case:

```graphql
type User  {
  id: @id
  name: String
  acceptedJobs: [AcceptedJobs!]!
}

enum Status {
  ACTIVE
  INACTIVE
}

type AcceptedJobs{
  user: User!
  Job: Job!
  isFreelancer: Boolean!
  status: Status
}

type Job {
  id: @id 
  title: String
  freelancers: [Freelancer!]!
}
```

If this doesn't solve your use case, please let me know.

**Comment by soqt** [comment]
Thank you!
