### ISSUE TITLE
prisma deploy demo server gives network error

### ISSUE THREAD

**Issue by sophyphreak** [prisma/prisma#3854]
**Describe the bug**
prisma deploy demo server gives `Network error: Unexpected token < in JSON at position 0`

**To Reproduce**
1. In the command line, run `yarn prisma deploy`
2. Select `Demo server`
3. Click `Grant Permission` button
4. See error `Network error: Unexpected token < in JSON at position 0` in upper right corner

**Expected behavior**
To connect to new demo sever

**Screenshots**
![screenshot from 2019-01-12 16-20-16](https://user-images.githubusercontent.com/22810755/51071593-3872ff00-1686-11e9-85e0-c805a91207dc.png)

**Versions (please complete the following information):**
 - Connector: n/a
 - Prisma Server: n/a
 - "prisma": "^1.24.0"
 - OS: elementary OS 0.4.1 Loki
 - other dependencies:     "prisma-client-lib": "^1.22.2"

**Additional context**
Currently working through howtographql tutorial

**Comment by divyenduz** [comment]
Thanks for raising this issue, while we work on fixing this, current workaround is to login on app.prisma.sh before running `prisma login` command. This issue is tracked here: https://github.com/prisma/prisma-cloud-feedback/issues/244

**Comment by pantharshit00** [comment]
This has been fixed now
