### ISSUE TITLE
Prisma CLI outputs wrong information when performing migrations with MongoDB

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3871]
**Describe the bug**

Prisma CLI outputs wrong information when performing migrations with MongoDB

**To Reproduce**

1. Create a new Prisma service with a local MongoDB using the `prisma init` wizard
1. Start the Prisma server with the MongoDB by running `docker-compose up -d`
1. Deploy the Prisma API with the default `User` type by running `prisma deploy`
1. Create a new `User` with the `createUser` mutation in the Playground
1. Rename `User` to `Person` in your datamodel
1. Run `prisma deploy` 

The CLI outputs:

```
Deploying service `default` to stage `default` to server `local` 51ms

Warnings:

  User
    ! You already have nodes for this model. This change will result in data loss.

If you want to ignore the warnings, please deploy with the --force flag: $ prisma deploy --force
Read more about deployment warnings here: https://bit.ly/prisma-force-flag
```

When using Prisma with MongoDB, Prisma will never delete anything during a migration. So that error message is not accurate.

**Expected behavior**

The migration should just work, maybe outputting an additional hint about how migrations are handled with MongoDB and linking to the docs.

**Comment by divyenduz** [comment]
@nikolasburk : For step 5 did you use `@rename`?

**Comment by nikolasburk** [comment]
No, afaik `@rename` doesn't do anything with the Mongo connector // @do4gr

**Comment by nikolasburk** [comment]
No, afaik `@rename` doesn't do anything with the Mongo connector (I think this is what @do4gr told me). In essence, deleting/renaming something in the datamodel should never change anything in the underlying MongoDB (except when renaming, it should create a new collection) but only migrate the Prisma API schema.
