### ISSUE TITLE
Fully test the error reporting in the Introspection Engine

### ISSUE THREAD

**Issue by williamluke4** [prisma/prisma#3873]

**Comment by Jolg42** [comment]
Full test can be done manually using https://github.com/prisma/prisma/blob/master/src/packages/cli/src/utils/test-handlePanic.ts

**Comment by williamluke4** [comment]
As this would require our error reporting setup to be replicated, it is being dropped.

**Comment by Jolg42** [comment]
Sounds good to me! 👍 
Also we just confirmed everything works as expected.
