### ISSUE TITLE
Prisma Import skipping file not yet imported

### ISSUE THREAD

**Issue by danohart** [prisma/prisma#3874]
Heyo, when I try to use prisma import -d to import 1 json file, it skips the file stating that it has already been imported. I also just tried to clean out my database in case there was some weird conflict with my dummy data I was playing around with, but alas it still doesn't work. A screenshot of my failure...
<img width="966" alt="screen shot 2019-01-15 at 10 13 58 am" src="https://user-images.githubusercontent.com/3968717/51193440-7b172000-18ae-11e9-9139-4dc2f542734f.png">
(I named the folder data1 just to see if renaming it would get it to think it's a new file...but at first it was named "data")

At first, I tried many times to import and failed as my json file and folder structure did not meet the requirements for import...but once I gave it what it wanted by learning from the errors thrown, I get to this point where it skips the file.

**To Reproduce**
1. Add json file to folder structure of data/nodes/file.json
2. Run prisma import -d data
3. Import runs but skips file and says complete

**Expected behavior**
Import of data into database from external json file

**Versions (please complete the following information):**
 - Connector: `MySQL`
 - Prisma Server: prisma/1.24.0 (darwin-x64) node-v10.9.0
 - `prisma` CLI: prisma/1.24.0 (darwin-x64) node-v10.9.0
 - OS: `OS X Mojave`

**Comment by danohart** [comment]
This was solved by changing my json file name to something starting with zero and another number, such as 01.json

**Comment by pantharshit00** [comment]
@nikolasburk Can we improve our docs about this?
