### ISSUE TITLE
Querying for empty relations

### ISSUE THREAD

**Issue by mahsohn** [prisma/prisma#3888]
## Problem

There doesn't seem to be a way to find items in a table who's relation field is empty using the where clause

## Suggested solution
the <Model>ListRelationFilter type should have an empty? field

```
export type <Model>ListRelationFilter = {
  every?: <Model>WhereInput
  some?: <Model>WhereInput
  none?: <Model>WhereInput
  **empty?: Boolean**
}
```

So for instance to find all users with no posts you would use:
`prisma.user.findMany({where:{posts:{empty:true}}})`

## Alternatives

I've tried things like `prisma.user.findMany({where:{NOT: {posts: {every: {id: {not:""}}}}}})`
But it definitely seems that any solution like this would be overkill for such a simple query 

## Additional context

This can easily be done in sql using COUNT()

**Comment by izziaraffaele** [comment]
Have you tried something like the following?
`prisma.user.findMany({where:{posts:{none:{}}}})`

**Comment by mavilein** [comment]
The suggestion by @izziaraffaele should work! 🎉

**Comment by mahsohn** [comment]
Thanks, that works, wish it was in the documentation

**Comment by beeman** [comment]
I'm posting this here as a reference, as it might be useful for someone (including future me).

I need a query that lists a specific category, with its children, but only those children that have active listings.

This is what I ended up with: 


```typescript
return this.data.category
  .findUnique({
    where: { id: categoryId },
    include: {
      parent: true,
      children: {
        orderBy: { order: 'asc' },
        where: { listings: { every: { status: ListingStatus.Active } } },
      },
    },
  })
```

**Comment by lcdss** [comment]
Another example to get all notifications for an user:

```ts
prisma.notification.findMany({
  include: {
    userNotifications: {
      select: {
        readAt: true,
      },
    },
  },
  where: {
    OR: [
      // User direct notifications
      {
        userNotifications: {
          some: {
            userId: 'some-user-id',
          },
        },
      },
      // System notifications (not related to any user)
      {
        userNotifications: {
          none: {},
        },
      },
    ],
  },
  orderBy: { createdAt: 'desc' },
  take: 10,
})
```

**Comment by Redskinsjo** [comment]
> Have you tried something like the following? `prisma.user.findMany({where:{posts:{none:{}}}})`

this doesn't seem to work anymore

**Comment by Redskinsjo** [comment]
> Have you tried something like the following? `prisma.user.findMany({where:{posts:{none:{}}}})`

this doesn't seem to work anymore
