### ISSUE TITLE
Cannot deploy Prisma service to Cluster

### ISSUE THREAD

**Issue by RoryKelly** [prisma/prisma#3888]
**Describe the bug**
Cannot deploy to Prisma cluster hosted in Prisma Cloud

**To Reproduce**
1. Login on Cli via `prisma login` 
2. deploy via `prisma deploy -e .env.staging`
3.  prints this  error message
```{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "addProject"
      ],
      "code": 3015,
      "message": "Authentication token is invalid: Token can't be decoded: Invalid signature for this token or wrong algorithm.",
      "requestId": "alpha-curated_curated:cjqzjh334007c0867hfzc6ar7"
    }
  ],
  "status": 200
}
```

**Expected behavior**
Service deploys to cluster correctly

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server:  `1.24.0`
 - prisma : `prisma/1.24.0 (darwin-x64) node-v8.10.0`
 - OS: `OS X High Sierra`

**Additional context**
Originally discovered problem after upgrading cluster, we have auto deployment set up on travis using `PRISMA_CLOUD_SESSION_KEY`. I tried recreating deployment locally and discovered the same issue.

I have also tried taking the PRISMA_CLOUD_SESSION_KEY from the ~/.prisma/.config.yml  and adding it to a playground and hitting the management API. I get the same error as above. 

<img width="1399" alt="screenshot 2019-01-16 at 19 15 28" src="https://user-images.githubusercontent.com/1162214/51272986-83ad4a80-19c3-11e9-8d9c-bfef7dad0189.png">

tried decoding token on http://www.jwt.io it seems to decode correctly

**Comment by RoryKelly** [comment]
I have Prisma Server running locally in docker, running version 1.24.0

I have set the `PRISMA_MANAGEMENT_API_SECRET`  to match the `PRISMA_MANAGEMENT_API_SECRET` in our prisma cloud service. 

I then manually created a  http://www.jwt.io (with wildcard claims) using the docs at `https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4/#management-api-token`

I verified this matched the token generated by `prisma cluster-token`. Because the secrets are the same I should be able to deploy to both services with the same token 

I can deploy to the local service fine with this token. I cant deploy to Prisma Cloud.

**Comment by pantharshit00** [comment]
Hi, 

Are you trying to use the demo server? We don't enable management API on demo server as everyone should be able to deploy to them.

Can you share the workspace name with me(listed under settings in prisma cloud)? You can also share that on Intercom if you are not comfortable sharing this here

**Comment by RoryKelly** [comment]
Ill share everything on intercom.

**Comment by RoryKelly** [comment]
I think i have managed to fix it. 

I think the issue was (correct me if I am wrong) when deploying to the hosted prisma service I do not need to set the environment variable PRISMA_MANAGEMENT_API_SECRET, it seems that this is managed automatically by the prisma cli.

I had the above enviroment variable set in my .env.staging file when I ran prisma deploy. the cli used that secret to sign the bearer token sent to the management API. This started to occur after i upgraded the prisma cluster and the corresponding prisma API.

Does all of this sound correct to you?

"prisma/1.24.0 (darwin-x64) node-v8.10.0"

Ill add the cause and fix to the github ticket

**Comment by donedgardo** [comment]
@RoryKelly Thank you Rorry for sharing, saved me.
