### ISSUE TITLE
Dependency Undici version bump from 2.0.5 to 2.0.7

### ISSUE THREAD

**Issue by Simskii** [prisma/prisma#3896]
Node crashes
node[17]: ../src/node_http_parser_impl.h:529:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.

A bug with dependency version 2.0.5 not working with node 12.19.0.
[https://github.com/nodejs/undici/issues/448#issuecomment-706070229](https://github.com/nodejs/undici/issues/448#issuecomment-706070229)

## How to reproduce
Run prisma with node 12.19.0

## Environment & setup

- OS: Mac OS
- Database: Mysql
- Node.js version: Node 12.19.0
- Prisma version: 2.7.1

**Comment by pantharshit00** [comment]
This is already done via https://github.com/prisma/prisma/pull/3884

This fix be available on the `2.9.0` release which is scheduled for tomorrow. You can also install the dev build via `npm install @prisma/cli@dev @prisma/client@dev` if you urgently want the fix but I would generally advise against running that in production.
