### ISSUE TITLE
Json[] isn't working anymore

### ISSUE THREAD

**Issue by tre-dev** [prisma/prisma#3897]
## Bug description

Error 1: After updating to 2.8.1 (from 2.7.1), `Json[]` isn't working correctly anymore. The compiler automatically stringifies the Json object, but a non-stringifed Json object is expected.

```
Object({"set": String("[{\"status\":\"new\",\"timestamp\":\"2020-10-11T17:19:40.192Z\"}]")}), want: Json]
```

Error 2: Also, I'm able to keep the `Json[]` empty, but when trying to query the created object afterwards, I'm getting `SyntaxError: Unexpected end of JSON input.`

## How to reproduce

```
prisma.user.create({
    data: {name: 'test', timeline: [{status: 'new', timestamp: moment.utc().toDate()}]},
  })
// Results in Error 1
```

```
prisma.user.create({
    data: {name: 'test'},
  })
// Results in Error 2
```

## Expected behavior

1.) It should either stringify it and not throw and error, or keep it as Json.
2.) It should throw an error when `Json[]` is required or allow empty array object and not throw an error when trying to parse a null value. It might also be good to support optional arrays `Json?[]`

## Prisma information

```
model User {
  id String @id @default(cuid())
  name String
  timeline Json[]
}
```

## Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: 13.7.0
- Prisma version:

```
@prisma/cli          : 2.8.1
Current platform     : darwin
Query Engine         : query-engine 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.296.0
Preview Features     : atomicNumberOperations
```

### Notes

I didn't want to go back to 2.7, so I replaced `Json[]` with `Json` for now, as it essentially broke my code.

**Comment by AhmedElywa** [comment]
Also, you will see the same issue for none list JSON

**Comment by tre-dev** [comment]
Hm, I'm able to work just fine with non-list JSON.

**Comment by Sytten** [comment]
I must say `Json[]` is very weird to me because an array is a valid Json. I would make sense if we had a JsonObject type though

**Comment by pantharshit00** [comment]
Hello,

Sorry for the late reply here. 

1. Error 1 

Looks like we are disallowing JS Date objects in a JSON field. TS also throws an error here as typing also don't allow it. I am not sure why that is that case. We should stringify the date internally.


2. Error 2

This one is allowed by the generated type and should not error out. I can confirm this. 


I will mark this as confirmed.
