### ISSUE TITLE
`prisma:download TypeError: Cannot read property 'map' of undefined` 

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#3898]
## Bug description

@albertoperdomo found this error when he added `DEBUG="*"`

<img width="612" alt="Screen Shot 2020-10-12 at 15 47 26" src="https://user-images.githubusercontent.com/1328733/95753689-3f3b0580-0ca2-11eb-81ae-2a1ce2d996b9.png">

```
env DEBUG="*" npx @prisma/cli@dev  prisma:download TypeError: Cannot read property 'map' of undefined
  prisma:download     at /Users/j42/.npm/_npx/84118/lib/node_modules/@prisma/cli/download-build/index.js:44:4146
  prisma:download     at Array.map (<anonymous>)
  prisma:download     at Object.dk [as flatMap] (/Users/j42/.npm/_npx/84118/lib/node_modules/@prisma/cli/download-build/index.js:41:14311)
  prisma:download     at Wk (/Users/j42/.npm/_npx/84118/lib/node_modules/@prisma/cli/download-build/index.js:44:4074)
  prisma:download     at async EP (/Users/j42/.npm/_npx/84118/lib/node_modules/@prisma/cli/download-build/index.js:47:1212) +0ms
```

[From unpkg](https://unpkg.com/@prisma/cli@2.9.0-dev.71/download-build/index.js) I found that it's `options.binaryTargets.map(`, so from this line https://github.com/prisma/prisma/blob/e72b394b175fe739d5c08cac4b2fd428da4755d4/src/packages/fetch-engine/src/download.ts#L121

## How to reproduce

- run `env DEBUG="*" npx @prisma/cli@dev`

## Environment & setup

- OS: Mac OS

**Comment by timsuchanek** [comment]
Fixed by 9be41528457e82a17759c70a3e9c891cfdc130f8
