### ISSUE TITLE
Internal server error on prisma-eu1 server 

### ISSUE THREAD

**Issue by tomermoshe** [prisma/prisma#3905]
Im getting the following error when i try to reach my demo service: "Whoops. Looks like an internal server error. Search your server logs for request ID: eu1:cjr7u9k1108180a133kd3lmjd"

1. Deploy a demo service to prisma-eu1 server
2. Send a graphql request to the service
3. You will get the above error (with different request id)

**Comment by pantharshit00** [comment]
Hi @tomermoshe,

We have some issues going on with demo servers. We will resolve them very soon

Thanks, 
Harshit

**Comment by pantharshit00** [comment]
This has been fixed. Please report if you are still encountering this.
