### ISSUE TITLE
[generate] Wrong template string is generated inside prisma-client

### ISSUE THREAD

**Issue by impowski** [prisma/prisma#3906]
**Describe the bug**
A clear and concise description of what the bug is. Gives an error:
`Project not found: 'project$stage%7D'`

**To Reproduce**
Just run the command `prisma generate`

**Expected behavior**
Should generate a proper file used in the future

**Screenshots**

**Versions (please complete the following information):**
 - Connector: [`Postgres`]
 - Prisma Server: [`1.25.0`]
 - `prisma` CLI: [`prisma/1.25.0 (darwin-x64) node-v11.7.0`]
 - OS: [`OS X High Sierra`, `Ubuntu 18.04`]
 - other dependencies: `prisma-client`, `prisma-binding`

**Additional context**

**Comment by divyenduz** [comment]
@impowski : Can you please share some more parameters, like, are you using local prisma server? and what is your `datamodel.prisma` file? Thanks!

**Comment by impowski** [comment]
@divyenduz it's hosted on DigitalOcean. I just updated to version `1.25` and that fell apart no idea why.

**Comment by parachut-daniel** [comment]
I'm getting a similar error. This happened after the upgrade also. It appears generate is doing this: 

```
export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  models,
  endpoint: `${process.env["PRISMA_ENDPOINT"]}}`,
  secret: `${process.env["PRISMA_SECRET"]}}`
});
export const prisma = new Prisma();
```

should probably be:
```
export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  models,
  endpoint: `${process.env["PRISMA_ENDPOINT"]}`,
  secret: `${process.env["PRISMA_SECRET"]}`
});
export const prisma = new Prisma();
```

**Comment by impowski** [comment]
Found an issue:
https://github.com/prisma/prisma/blob/f6c479644c6fed0b40c51872de689fed3d5da804/cli/packages/prisma-client-lib/src/codegen/Generator.ts#L35

**Comment by impowski** [comment]
I guess the same is here:
https://github.com/prisma/prisma/blob/f6c479644c6fed0b40c51872de689fed3d5da804/cli/packages/prisma-client-lib/src/codegen/generators/flow-client.ts#L86

**Comment by c316** [comment]
I'm also seeing this on my Mac (Mojave) and when I fix the generated file I then get this error. https://github.com/prisma/prisma/issues/3907

**Comment by ludovicgueth** [comment]
updating to prisma 1.25 did the same. (adding some characters after the endpoint in prisma-client)
I downgraded to 1.20 and everything is working fine

**Comment by jiaxi0713** [comment]
I've meeting a similar problem after updating to 1.25.when I exec prisma deploy ,a typeerror occurs:
TypeError: Cannot read property 'steps' of null
I donno where to set the 'steps' property

**Comment by jangerhofer** [comment]
@divyenduz: Seconding @parachut-daniel's observation of the extra `}` at the end of the line:

``` endpoint: `${process.env["PRISMA_ENDPOINT"]}}`,```.

As others have mentioned, this arises from the Prisma CLI version: `prisma/1.25.0 (darwin-x64) node-v11.6.0`.  I'm running the Docker Hub tag `prismagraphql/prisma:1.25` on the Prisma Server side, but this is clearly a CLI/codegen issue per the code highlighted above.

**Comment by divyenduz** [comment]
@ajaymore Thanks, `TypeError: Cannot convert undefined or null to object` is a separate issue and is being tracked here: https://github.com/prisma/prisma/issues/3907

**Comment by ajaymore** [comment]
> @ajaymore Thanks, `TypeError: Cannot convert undefined or null to object` is a separate issue and is being tracked here: #3907

@divyenduz Thank you, that addressed my concern. I am able to get the code running by manually changing the autogenerated template strings.
