### ISSUE TITLE
Rename babylon to babel

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#3912]
We are currently throwing a depreciation warning due to the recent changes in Babel.

![image](https://user-images.githubusercontent.com/22195362/51609644-a221c180-1f40-11e9-890e-626f05b1c46a.png)

Related: https://github.com/babel/babel/pull/7937

Renaming babylon to babel will solve this.

**Comment by divyenduz** [comment]
While this is merged: https://github.com/prettier/prettier/issues/4508
The `@types/prettier` project is still out of sync: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/prettier/index.d.ts#L23

**Comment by divyenduz** [comment]
This is fixed the the latest alpha, `1.31.0-alpha.3`, please install it via `npm install -g prisma@alpha`

**Comment by divyenduz** [comment]
This is available in the latest stable `1.31.1`. Please install this via `npm install -g prisma`.

I am closing this issue, please open a new issue again if necessary.
