### ISSUE TITLE
Create and maintain a `@nrwl/prisma` plugin (nx.dev)

### ISSUE THREAD

**Issue by cyrus-za** [prisma/prisma#3914]
See [nx-plugins](https://nx.dev/latest/react/plugins/overview) and [nx-community](https://nx.dev/nx-community)

Also see this issue https://github.com/nrwl/nx/issues/1922

nx.dev is a monorepo solution that does a lot more than lerna. They got plugins that preconfigure apps with CLI commands (could hook into the prisma cli)

There's a feature request to the nx team to support prisma. Chances are that is not high up on their priority list, so I figured it would be worth asking here if the prisma team (or someone in the broader community) could write a community plugin to support prisma

**Comment by pantharshit00** [comment]
Hey @cyrus-za 

You opened this issue in the Prisma repository instead of nx repository. Can you please double check where you meant to open this?

I will close this for now.

**Comment by beeman** [comment]
@cyrus-za I am working on a [project](https://github.com/nxpm/stack) that is using Prisma in a Nx Workspace. It currently initializes an empty schema, but I have some more plans. I would love to chat about what you would like to see 👍

**Comment by cyrus-za** [comment]
@beeman I only saw this now. I'd love to chat. Drop me a message on the Prisma slack

**Comment by janpio** [comment]
Is this request potentially covered by https://nx-plugins.netlify.app/prisma/ now?
(Found by searching https://nx.dev/plugins/registry for `prisma`)
