### ISSUE TITLE
JSON value truncate floating numbers

### ISSUE THREAD

**Issue by Kerumen** [prisma/prisma#3918]
## Bug description

When I store a JSON value with floating numbers, Prisma seems to **truncate** the number and this leads to loss of precision and incorrect values.

## How to reproduce

```
await prisma.user.create({
  data: {
    color: {
      r: 0.92156863212585449,
      g: 0.34117648005485535,
      b: 0.34117648005485535,
    },
  }
})
```

The logged query is (which makes me think this comes from Prisma and not from the database):

```
{
  timestamp: 2020-10-14T11:52:11.040Z,
  query: 'INSERT INTO "public"."User" ("id","color") VALUES ($1,$2) RETURNING "public"."User"."id"',
  params: '["ckg9c3vha0035qns5jyeyy8pb",{"r":0.9215686321258544,"g":0.34117648005485535,"b":0.34117648005485535}]',
  duration: 0,
  target: 'quaint::connector::metrics'
}
```

Notice the ending of the `r` number, it's truncated. But not for the `b` or `g` value.

## Expected behavior

The stored value for `r` should be `0.92156863212585449` and not `0.9215686321258544`.

## Prisma information

```
model User {
  color Json
}
```

## Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v12.16.2
- Prisma version:

```
@prisma/cli          : 2.8.1
Current platform     : darwin
Query Engine         : query-engine 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.296.0
```

## Related

This could be related
https://github.com/prisma/prisma/issues/3479
https://github.com/prisma/prisma/issues/2903

**Comment by pimeys** [comment]
JavaScript uses a 64-bit floating point values and we're hitting the maximum accuracy here.

In node:

```
❯ node
Welcome to Node.js v15.0.1.
Type ".help" for more information.
> 0.92156863212585449
0.9215686321258545
```

And in Rust:

```
❯ evcxr
Welcome to evcxr. For help, type :help
>> 0.92156863212585449_f64
0.9215686321258545
```

@timsuchanek deployed support for a decimal type recently, which should help here.

**Comment by timsuchanek** [comment]
Thanks @Kerumen for reporting! @pimeys is totally right - it's due to JavaScript not supporting this.
However, we will soon launch a new Prisma type called `Decimal` which supports arbitrary precision. As soon as it's available, we'll update this issue and let you know.

**Comment by Kerumen** [comment]
@pimeys Yes but in your example `0.92156863212585449` is "converted" (rounded) to `0.9215686321258545` which is fine but in Prisma `0.92156863212585449` is "converted" (truncated) to `0.9215686321258544` which is not fine.

@timsuchanek My problem appeared in a `Json` type. Will it work for that also?

**Comment by timsuchanek** [comment]
@Kerumen thanks for the clarification. That then indeed is a bug. The `Decimal` type with not fix this one, as you have to use it outside of `Json`.
We'll further investigate 🙏

**Comment by pimeys** [comment]
There's a fix coming. The problem in general is how JSON doesn't store actual f64's to represent the numbers, so converting them to standard floats may cause accuracy errors and this is what we see here.

Luckily Rust's JSON library has a compile time flag, that uses slower but one to one accurate conversion to and from JSON. This is enough with PostgreSQL.

Then, again, if anybody ever reads this issue, do not try to store floats in MySQL's JSON data type:

```sql
create table foo (id int primary key, data json);
insert into foo (id, data) values (1,'0.9215686321258545');
select data from foo;
```

Returning `0.9215686321258544`...
