### ISSUE TITLE
`set` mutation not available in Prisma client API

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3921]
I'm on Prisma v1.25 (CLI: `prisma/1.25.1 (darwin-x64) node-v10.13.0`) and want to use the new nested mutation `set`.

I can use it in the GraphQL API of my service but it doesn't seem to be part of the client API yet:

![image 3](https://user-images.githubusercontent.com/4058327/51667730-e9e82d80-1fc0-11e9-9389-6d2e934a813b.png)
![image 4](https://user-images.githubusercontent.com/4058327/51667732-e9e82d80-1fc0-11e9-8ba9-3eed0087d4dc.png)

**Comment by Nedomas** [comment]
I understand that `set` is currently implemented for non-relation array fields only. 

`1.25.4` client generates `set` for `simpleField: [ID!]!`, but not for `relation: [Post!]!`

**Comment by pantharshit00** [comment]
This is fixed a while back
