### ISSUE TITLE
Missing erroneous column name in relation table errors.

### ISSUE THREAD

**Issue by sktt** [prisma/prisma#3922]
Hi!

## Bug description

Error messages from join columns in relation tables (many-to-many for example) are unclear.  When a constraint of a join column is not met we get an error like this: `Error: The provided value for the column is too long for the column's type. Column: <unknown>`

## How to reproduce

Our relationship tables had 25 byte wide join columns due an old bug with cuid (https://github.com/prisma/prisma-engines/issues/878) that had not been taken into account in prisma-upgrade. 

1. create dataschema in prisma1 with a table relation.
2. use npx prisma-upgrade to upgrade to p2 and execute those queries it will wrongly ask you to set column type to `character varying(25)` in the relation table (proposed fix here https://github.com/prisma/upgrade/pull/88) but use 30 for the "model tables".
3. create a model with relationship with id as cuid of length 26. 
4. Boom. 

## Expected behavior

We should get information about the erroneous column was (ie. "A" or "B")

## Prisma information

Using a db schema that has been upgraded from prisma1, meaning the join columns have character varying(30) instead of text (which seems to be the result of `migrate up` on a fresh database.

## Environment & setup

```
select version();
PostgreSQL 11.9 (Debian 11.9-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

node -v
v11.9.0

prisma -v 
@prisma/cli          : 2.8.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 439da16b2f8314c6faca7d2dad2cdcf0732e8a9c (at node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.296.0

```

**Comment by pantharshit00** [comment]
Hey @sktt 

Sorry for late reply here. I can reproduce this bug. 

We recently made https://github.com/prisma/prisma/issues/4093 which has more details and exact code default which needed to be changed to so I am going to close this one, please follow the other issue now.
