### ISSUE TITLE
Incorrect migration behavior with rename directive and mysql connector

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3924]
**Describe the bug**
On renaming a type with MySQL connector using the `@rename` directive, a table is generated incorrectly in the migrations table. 

**To Reproduce**
https://github.com/divyenduz/prisma-3924

**Expected behavior**
The migration table should be created in the project database. 

**Screenshots**
![image](https://user-images.githubusercontent.com/746482/51689197-344ac800-201c-11e9-8808-0263eea737b9.png)

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server: `1.25.0`
 - `prisma` CLI: `1.25.3`
 - OS: `OS X Mojave`

**Additional context**
This is the current known reproduction table (unverified by a team member)
```
1.23.4 broken
1.25.3 broken
1.27-alpha fixed
1.26-beta broken
1.19.2 working
1.21 working
1.22 broken
1.22.0 broken
```

**Comment by do4gr** [comment]
I started looking into this but could not reproduce it on current versions. I have seen the error on older versions, but all current versions should be working as expected. 

On 1.25.4 (current master) it works,
On 1.26-beta it works,
On 1.27-alpha it works.
