### ISSUE TITLE
 Could not connect to server at http://192.168.99.100:4466. Please check if your server is running.

### ISSUE THREAD

**Issue by mxsmxm** [prisma/prisma#3927]
windows 10 
docker-toolbox.

follow  prisma.io getstarted->setup prisma ->exsiting database
I use mlab for mongoDB.

here is my prims.yml:

endpoint: http://192.168.99.100:4466
datamodel: datamodel.prisma
databaseType: document

generate:
  - generator: javascript-client
    output: ./generated/prisma-client/

<img width="310" alt="11" src="https://user-images.githubusercontent.com/24431178/51726631-458ae780-20a3-11e9-8938-d9ab572c92c1.png">

here is my err:
![default](https://user-images.githubusercontent.com/24431178/51726664-6ce1b480-20a3-11e9-93a9-ba7c7543e3d7.png)

docker toolbox:
![default](https://user-images.githubusercontent.com/24431178/51726672-7bc86700-20a3-11e9-9f1e-bec223c5b40f.png)

**Comment by domekol** [comment]
This also happens on local machines:

```
$ i18n-database yarn start
yarn run v1.12.3
$ docker-compose --file docker-compose.yml --project-name i18n up --detach
Recreating i18n_prisma_1 ...
Recreating i18n_prisma_1 ... done
✨  Done in 13.24s.

$ i18n-database yarn deploy
yarn run v1.12.3
$ prisma deploy
 ▸    Could not connect to server at http://localhost:4466. Please check if your server is running.

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ export DEBUG="*"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

$ i18n-database yarn deploy
yarn run v1.12.3
$ prisma deploy
Creating stage dev for service db ✔
Deploying service `db` to stage `dev` to server `local` 1.2s
...
```

Only happens, if the deploy command is executed right after the docker-compose.
Seems the server needs bit more time.

**Comment by imgenius0136** [comment]
I face on same issue :(
