### ISSUE TITLE
Introduce `@prisma/engines` package

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#3928]
We want to move all engines into a package called `@prisma/engines`, which is responsible for shipping the Prisma Engines.
This will greatly improve our dependency management with the engines.

**Comment by NMinhNguyen** [comment]
@timsuchanek not sure if I should comment on this issue, or open a new issue at https://github.com/prisma/engines-wrapper but would you please be able to include the licence field in `@prisma/bar`?

**Comment by timsuchanek** [comment]
Thanks @NMinhNguyen! We already had a license field in `@prisma/bar`, but the license was not spelled properly. It was `Apache 2.0` while it has to be `Apache-2.0`. https://unpkg.com/@prisma/bar@0.0.1/package.json
We just updated it https://unpkg.com/@prisma/bar@0.0.1/package.json
The updated version will be released tomorrow in our `2.11.0` release of `@prisma/cli`.

**Comment by timsuchanek** [comment]
And it's released in `2.11.0`!
