### ISSUE TITLE
Standardize the connection string for simple connections

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#3933]
## Problem

Connection strings come in many different formats. This lack of standardization can make it confusing for newcomers to understand how to connect to their database. 

To give you a flavor of the various connection strings out in the wild:

- `jdbc:sqlserver://localhost:1433\MY_INSTANCE`
- `sqlserver://username:password@localhost:1433/database?encrypt=true`
- `Server=localhost,1433;Database=database;User Id=username;Password=password;Encrypt=true Driver=msnodesqlv8;Server(local)\INSTANCE;Database=database;UID=DOMAIN\username;PWD=password;Encrypt=true`

If you're lucky, your database host  provides you a connection string that you can copy and paste into your database client, but this isn't always the case.

## Suggested solution

I think that the URL format is the most familiar format and a good default for basic use cases.

```
schema://username:password@hostname:port/database_name?key=value
```

For Postgres that would look like this:

```
postgresql://username:password@localhost:1433/database?encrypt=true
```

The URL format shouldn't be the only supported format. It would just be our 1 common format across datasources. If a popular database host provides a copy-pasteable connection string that is not a URL, we should also handle that. 

Additionally, sometimes it's unreasonable to enforce a standard URL format, especially when we start talking about replicas across hosts. For example, this isn't a valid URL and that's okay:

```
mongodb://mongodb0.example.com:27017,mongodb1.example.com:27017,mongodb2.example.com:27017/?replicaSet=myRepl
```

So perhaps we could have a list of different connection string parsers to try for a given datasource, so for MSSQL, you could have 3 connection string parsers:

1. `jdbc:sqlserver://localhost:1433\MY_INSTANCE`
2. `sqlserver://username:password@localhost:1433/database?encrypt=true`
3. `Server=localhost,1433;Database=database;User Id=username;Password=password;Encrypt=true Driver=msnodesqlv8;Server(local)\INSTANCE;Database=database;UID=DOMAIN\username;PWD=password;Encrypt=true`

I think it would be nice is if we at least support the (2) format for all of our datasources. Then for the advanced use-cases like (1) and (3), it's datasource-specific.

I'm mostly thinking about this from a user-perspective, less about the tradeoffs. Being consistent for the simple cases would probably be helpful.

**Comment by pimeys** [comment]
We'd be the first ones using `mssql` in the string. The correct version is always `sqlserver`!

**Comment by matthewmueller** [comment]
Edited, thanks.

**Comment by janpio** [comment]
We have moved away from inventing our own things, and just make it work with what is common. There is little value in us adding the overhead of mapping and parsing these formats in our own.

So we will not look further into this.
