### ISSUE TITLE
Prisma Client: generate additional typedefs containing only basic type definitions

### ISSUE THREAD

**Issue by colinmcd94** [prisma/prisma#3938]
**Is your feature request related to a problem? Please describe.**
Prisma Client (TS) generates `index.ts` and `prisma-schema.ts`, but neither of those are suitable for importing directly into the typedefs of a typical "application server".

**Describe the solution you'd like**
I'd like the Prisma Client generate step to create a `prisma-types.ts` that includes just the definitions of the basic types defined in datamodel.schema. Often, the schema exposed by an application server will contain all the same types as the Prisma service with custom queries/mutations. Currently it isn't possible to just import the base types a graphql-yoga server typeDefs so a lot of boilerplate/duplication is required to bring the datamodel over to the yoga server.

**Describe alternatives you've considered**
I could import the typedefs from datamodel.prisma, but I don't want to include the Prisma declaration files in the directory of my Yoga server.

**Comment by colinmcd94** [comment]
Actually, this use case is basically solved now with the release of Nexus and it's Prisma integration: https://github.com/prisma/nexus-prisma. Closing! 🎉

**Comment by zessu** [comment]
lkmnllkmlk
