### ISSUE TITLE
Indexes on relation fields

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#3943]
@pimeys noticed in the course of his benchmarking work that we do not create indexes on `@relation`. Adding them is most of the time a big query performance improvement.

@janpio raised the issue of the _cost_ of indexes (write performance on big tables), and suggested we need to make this behaviour overridable, whichever default we end up settling on.

**Comment by do4gr** [comment]
Since scalar fields backing relations are now explicit, users can now specify whether they want indexes or not. Closing this as implemented.
