### ISSUE TITLE
Better error message when SQL Server connection string is incorrect

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3946]
## Problem

MSSQL's connection string has `;`s in it. It should be quoted when used in bash. 

The following command fails with `Connect timed out` error

```
yarn prisma introspect --url sqlserver://127.0.0.1:1433;database=test;user=SA;password=prisma123;trustServerCertificate=true;encrypt=DANGER_PLAINTEXT
```

```
divyendusingh [p2-mssql]$ yarn prisma introspect --url sqlserver://127.0.0.1:1433;database=test;user=SA;password=prisma123;trustServerCertificate=true;encrypt=DANGER_PLAINTEXT
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/introspection-ci/node_modules/.bin/prisma introspect --url sqlserver://127.0.0.1:1433

Introspecting …
Error: Error in connector: Connect timed out
```

The reason is that the URL is not quoted, the command is interpreted as 

`yarn prisma introspect --url sqlserver://127.0.0.1:1433`

The error message here can be improved. 

## Suggested solution

The error message can suggest that the database component is missing from the connection string or something helpful. 

If MSSQL expects defaults for all these values (like Postgres does) then the error message itself should remain the same. However, we can still annotate it with a warning like "database not provided explicitly"

**Comment by janpio** [comment]
Does not seem to be a user facing problem, so closing for now.
