### ISSUE TITLE
Dummy Update not working 

### ISSUE THREAD

**Issue by Mercurial** [prisma/prisma#3948]
According to docs I can trigger a subscription with a dummy data update

![image](https://user-images.githubusercontent.com/585569/51874044-52a52080-239a-11e9-9827-3225fee083a8.png)

but i seem to get some error when i try it

![image](https://user-images.githubusercontent.com/585569/51874017-3f925080-239a-11e9-9be0-7ddc8b2294d9.png)

My current work around is just update any field with the same value

![image](https://user-images.githubusercontent.com/585569/51874095-8b44fa00-239a-11e9-9508-4c1b65797da7.png)

**Comment by pantharshit00** [comment]
Hi @Mercurial 

I guess you have misinterpreted the docs.

>  Add a dummy: String field to the type

You will require to add this field first.

I am closing this one now, please feel free to reply if this is still not very clear.
