### ISSUE TITLE
Should the schema parser validate that there is no `@default("...")` on TEXT/BLOB native type columns on MySQL?

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#3948]
These defaults [cannot be implemented at the database level](https://dev.mysql.com/doc/refman/5.7/en/blob.html). The migration engine has no choice but to ignore them, which is very confusing for users (todo: link to a user issue with `@default(uuid())` presenting the exact same problem). We can however polyfill these at the query engine level. It is a product decision to make.

Also see: https://github.com/prisma/prisma-engines/issues/1227

**Comment by matthewmueller** [comment]
We talked about this during Client Weekly and concluded that we should continue supporting this. From the Query Engine side, there's nothing to do.
