### ISSUE TITLE
findUniqueOrFail / findFirstOrFail

### ISSUE THREAD

**Issue by P4sca1** [prisma/prisma#3949]
## Problem

Sometimes you query an object from database and require it to exist.

## Suggested solution

Two new methods:`findUniqueOrFail` and `findFirstOrFail`.
If no object is found, an error will be thrown.

## Alternatives

Right now, I see myself often writing code such as:
```ts
// Return type is Machine | null
const machine = await prisma.machine.findUnique({
  where: {
    id: gameServer.machineId,
  },
})

if (machine === null) {
  throw new Error('Machine not found.')
}
```

With the suggested solution the code would just be
```ts
// Return type is Machine
const machine = await prisma.machine.findUniqueOrFail({
  where: {
    id: gameServer.machineId,
  },
})
```

**Comment by AnandChowdhary** [comment]
Maybe an alternate name can be `findOneOrThrow` since `Throw` is more explicit than `Fail`.

**Comment by P4sca1** [comment]
I took the naming from TypeORM, but it can definitely be changed to be more explicit.
If `findOne` is renamed to `findUnique` (see #3697), names should obviously be also changed to `findUniqueOrFail` / `findUniqueOrThrow`.

**Comment by P4sca1** [comment]
Closing as this has been implemented using the `rejectOnNotFound: true` option on `findFirst` and `findUnique`.
