### ISSUE TITLE
Error formatting for connection limit error

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3951]
## Problem

Originally suggested by @janpio. There are two lines before the actual error from the database

```
Invalid \`prisma.queryRaw()\` invocation:


Error in connector: Error querying the database: db error: FATAL: sorry, too many clients already
```

https://github.com/prisma/prisma/blob/5c1039d08545c3bbf41eaad6189a63fc0d2ed518/src/packages/client/src/__tests__/integration/errors/connection-limit/__snapshots__/test.ts.snap

Is that expected? 

## Suggested solution

A single blank line should be enough. 

## Additional context

This might break some snapshot tests etc out there and in that sense, this is a breaking change.

**Comment by janpio** [comment]
Seems to be generally accepted or have been fixed along the way.
