### ISSUE TITLE
[schema] Hidden and read-only fields for models

### ISSUE THREAD

**Issue by kripod** [prisma/prisma#3956]
## Problem

Some model attributes shall not be exposed at any time. For instance, `createdAt` may never be modified programmatically. Or `id` values shall not be returned from the public API.

## Suggested solution

Read-only attributes could make sure not to expose fields like `createdAt` for modification:

```prisma
model User {
  id String @id @default(cuid())
  createdAt DateTime @default(now()) @readonly
  // …
}
```

When querying for them, they would still be present in results, but they may not be updated.

Attributes like `id` may not be exposed by the results of `find*` and other methods, offering safer API results by default. However, hidden attributes like the `id` could still be used in conditions to cater for relations:

```prisma
model User {
  id String @id @default(cuid()) @hidden
  // …
}
```

## Alternatives

The naming of these `@{rules}` may be more explicit. Examples:

- `@access(read)` / `@access(condition)`
- `@unselectable` instead of `@hidden`

Also, hidden fields may be force-selected by specifying them in `select` objects.

## Additional context

This issue is related to the discussion in #2127. While Nexus and other third-party solutions make it possible to constrain the usage of models, Prisma could make typing them way more convenient, especially for rest APIs.

**Comment by flybayer** [comment]
Yes, we definitely need a `@hidden` feature!

Here's a recent post by the Prisma team discussing `@hidden`: https://github.com/prisma/prisma-client-js/issues/649#issuecomment-700776231

And here's a related issue on same problem: #3936

**Comment by kripod** [comment]
@flybayer Thanks for your input! I haven’t encountered those discussions before and they definitely deserve more attention. _(I’m not sure if #3936 was referred correctly, but I would be very curious about that one as well.)_

**Comment by flybayer** [comment]
Oops, I fixed the reference. 3636 instead of 3936.

**Comment by pantharshit00** [comment]
Keeping this issue open for readonly part.

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/3401

**Comment by IdanYekutiel** [comment]
I think the implementation of the ``@hidden`` attribute could be really useful! Being able to hide something like a password by default is what I've been looking for. Realistically, you only need to access the password in a find query on something like a login. In every other situation, it is unnecessary. I end up having to use the select options. Using a feature like this for hiding passwords is my use case, but there are many! 

Just like it was mentioned in the initial suggested solution, being able to hide info like id, emails, and etc are just a few of the many use cases.

**Comment by Hellomik2002** [comment]
hidden it is not writable or readonly
