### ISSUE TITLE
One to Many relationship not querying

### ISSUE THREAD

**Issue by Fh-abeyer** [prisma/prisma#3959]
**Describe the bug**
I have a one to many relationship set up for user permissions to users. When I query the users for their permissions it works fine however when I query user permissions for the users it returns null.

**To Reproduce**
1. Create a one to many relationship that is not required on the one side
2. Create a relationship with both and one that doesn't have a many relationship

**Expected behavior**
Query displays all user permissions with the users associated with them or null if they have none.

**Screenshots**
![one to many query not working](https://user-images.githubusercontent.com/33637390/52004114-616ffe00-2494-11e9-85b1-83e1b2b28403.png)
![user database](https://user-images.githubusercontent.com/33637390/52004145-7482ce00-2494-11e9-8aac-ef54cce6b8c8.png)
![userpermission database](https://user-images.githubusercontent.com/33637390/52004150-777dbe80-2494-11e9-91ae-4627452577fc.png)

**Versions (please complete the following information):**
 - Connector: Demo Server
 - Prisma Server: [e.g. `1.25.0`]
 - `prisma` CLI: [e.g. `prisma/1.25.0 (darwin-x64) node-v10.4.0`]
 - OS: Windows 10

**Additional context**
Here are my models in both the schema and the prisma datamodel
graphql schema
```
type User {
  id: ID!
  email: String!
  first_name: String!
  last_name: String!
  permission: UserPermission!
  companies: [CompanyUser!]!
}

type UserPermission {
  id: ID!
  name: String!
  users: [User]
}
```
prisma schema
```
type User {
  id: ID! @unique
  email: String! @unique
  password: String!
  first_name: String!
  last_name: String!
  permission: UserPermission!
  companies: [CompanyUser!]!
}

type UserPermission {
  id: ID! @unique
  name: String! @unique
  users: [User]
}
```

Here is my UserPermission.js file which is the resolver

```
function users(parent, args, context) {
    return context.prisma.userPermission({ id: parent.id }).users()
}

module.exports = {
    users,
}
```

**Comment by pantharshit00** [comment]
Hi,

There was certain regression around this that was fixed in version `1.25.4` of prisma-client-lib. This issue was tracking that bug #3919

Can you try to upgrade the prisma-client-lib version and try again?

**Comment by Fh-abeyer** [comment]
I upgraded to 1.25.4 and I still am getting the same issue.

**Comment by Fh-abeyer** [comment]
Another weird thing too is this works on another set of tables I have.

```
type User {
  id: ID! @unique
  email: String! @unique
  password: String!
  first_name: String!
  last_name: String!
  permission: UserPermission!
  companies: [CompanyUser!]!
}

type UserPermission {
  id: ID! @unique
  name: String! @unique
  users: [User!]
}

type Price {
  id: ID! @unique
  name: String! @unique
  cost: Float!
  companies: [Company!]!
}

type Company {
  id: ID! @unique
  name: String! @unique
  price: Price!
  members: [CompanyUser!]!
}

type CompanyPermission {
  id: ID! @unique
  name: String! @unique
  users: [CompanyUser!]!
}

type CompanyUser {
  id: ID! @unique
  company: Company!
  company_permission: CompanyPermission!
  user: User!
}
```

It works for the prices, companies, company users even if they do not have any. I dont understand what is different about the user permissions

**Comment by Fh-abeyer** [comment]
I unistalled all of prisma and node and reinstalled and that seemed to work. I dont know if maybe something got messed up on the upgrade or what. You have a reference point if it happens to someone else.
