### ISSUE TITLE
Migration to Float type in the US region of demo server is causing error on data insertion

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#3961]
**Describe the bug**
The prisma demo servers are throwing an error when we migrate an `Int` field to a `Float` and try to insert data in it. 

**To Reproduce**
1. Bootstrap a simple prisma project using the cli(choose US demo servers)
2. Add a field `test: Int` to the datamodel
3. Run prisma deploy
4. Change the type to Float and rerun the deploy
5. Try to insert some data with the `createUser` mutation

**Expected behavior**
Creation of the user should not result in an error

**Screenshots**

![image](https://user-images.githubusercontent.com/22195362/52045810-47551f00-256b-11e9-85e9-198cb2eaf2cb.png)

Log of the failing request from AWS
![image](https://user-images.githubusercontent.com/22195362/52045834-5340e100-256b-11e9-8aab-a3d5696f2bd3.png)

**Versions (please complete the following information):**
 - Connector: MySQL(Demo Server)
 - Prisma Server: Demo Server (ie latest beta 1.26-beta-1)
 - `prisma` CLI: 
 - OS: macOS mojave 10.14.2

**Comment by pantharshit00** [comment]
This is still happening @divyenduz 

![image](https://user-images.githubusercontent.com/22195362/52491785-e2926800-2bed-11e9-92ba-8809c3775a80.png)

**Comment by ianjanicki** [comment]
Can confirm. This goes both ways, including Float -> Int.

**Comment by ianjanicki** [comment]
Easiest workaround for those facing this issue:
* Remove field(s) in question; deploy
* Add fields back in (with proper `Int` or `Float` type); deploy

**Comment by pantharshit00** [comment]
I am no longer able to reproduce this
