### ISSUE TITLE
Running `prisma delete -f` on non-existing service should return without error

### ISSUE THREAD

**Issue by timdebacker** [prisma/prisma#3964]
**Is your feature request related to a problem? Please describe.**
We use `prisma delete -f` in several of our developer scripts (to reset a developer database, to clean up a state before an integration test, etc).

In all these situations we simply want to ensure the service is gone after running the command, irrespective whether it was there or not. 

As a user, I expect the 'force' mode to do exactly that. Very similar to how `rm -f my-file.txt` always returns, even the file was not there.

The fact that `prisma delete -f` throws in when run on a non-existing service is frustrating, since we have to specifically handle a situation in our scripts that we don't care about.

Related to #2076, where something similar was advocated on the side.

**Describe the solution you'd like**
Providing `-f` has two effects:
 - non interactive mode (i.e. the current behavior); _and_
 - returns with exit code 0, even if the service to delete does not exist

The current behavior (non-interactive only) is still possible, but there is a new option `-y` (for 'yes') that triggers this behavior.

**Describe alternatives you've considered**
All are hacky workarounds:
 1. Perform an 'exists test' before running `prisma delete -f`. But this is not failproof of course. You also don't check whether a file exists and then assume that nothing can go wrong when opening it. You open it and handle errors if they occur. 
 2. Capture the `prisma delete -f` exit code. But right now the exit code is always `1`. We would need a specific exit code for a non-critical failure like trying to delete something that isn't there.
 3. Catch and parse the `stderr` of the command. But of course this is pretty ugly.

**Comment by divyenduz** [comment]
This is available in the latest `beta` - `1.27.0-beta.12`, please install it via `npm install -g prisma@beta`.

**Comment by timdebacker** [comment]
Great news. Thanks a lot!

**Comment by divyenduz** [comment]
This is available in the latest `stable` - `1.28.0`, please install it via `npm install -g prisma`. I am closing this issue, please open a new issue, if necessary.
