### ISSUE TITLE
prisma generates invalid typescript syntax

### ISSUE THREAD

**Issue by P4sca1** [prisma/prisma#3964]
## Bug description

When using dots in index names, the generated `prisma-client-js` exports types that includes these dots, which is invalid TypeScript syntax.

**This bug results in the project using prisma not being able to compile with `tsc`, which is a major problem.**

## How to reproduce

1. Run `prisma init` in a fresh directory
2. Copy the `schema.prisma` (see below)
3. Run `prisma generate`
4. Take a look at `node_models/.prisma/client/index.d.ts` and search for types starting with `Game_server_port.`

You will notice 2 issues:
1. The types contain dots which is invalid TypeScript syntax.
2. The types are defined with an uppercase starting letter, but when referenced (in `GameServerPortWhereUniqueInput`), they are used with a lowercase starting letter. This results in `Cannot find name` errors.

## Expected behavior

Since index names with dots inside them are the [prisma default](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/prisma-schema-reference/#arguments-5), these should be supported, e.g. by replacing dots with underscores maybe.
Also the types should be correctly referenced.

## Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model GameServer {
  id                  Int                       @id @default(autoincrement())
  ports               GameServerPort[]
  @@map("game_server")
}

model GameServerPort {
  id           Int                    @id @default(autoincrement())
  /// varchar(32)
  identifier   String
  protocol     GameServerPortProtocol
  /// unsigned smallint, container port
  number       Int
  /// unsigned smallint, host port
  binding      Int
  gameServerId Int
  /// ON UPDATE CASCADE, ON DELETE CASCADE
  gameServer   GameServer             @relation(fields: [gameServerId], references: [id])

  @@unique([gameServerId, binding, protocol], name: "game_server_port.gameServerId_binding_protocol_unique")
  @@unique([gameServerId, identifier], name: "game_server_port.gameServerId_identifier_unique")
  @@unique([gameServerId, number, protocol], name: "game_server_port.gameServerId_number_protocol_unique")
  @@map("game_server_port")
}

enum GameServerPortProtocol {
  TCP
  UDP

  @@map("game_server_port_protocol")
}
```

## Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: 12.16.2
- Prisma version:

```
@prisma/cli          : 2.9.0
@prisma/client       : 2.9.0
Current platform     : darwin
Query Engine         : query-engine 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at ../../.npm/_npx/18009/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at ../../.npm/_npx/18009/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at ../../.npm/_npx/18009/lib/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at ../../.npm/_npx/18009/lib/node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.296.0
```

**Comment by P4sca1** [comment]
Take the following model:
```prisma
model WebAuthnAuthenticator {
  id                 Int                         @id @default(autoincrement())
  registeredAt       DateTime                    @default(now())
  userId             Int
  format             WebAuthnAuthenticatorFormat
  /// unsigned
  counter            Int                         @default(0)
  base64PublicKey    String                      @unique
  base64CredentialId String                      @unique
  lastUsed           DateTime?
  /// varchar(32)
  name               String
  /// varchar(20)
  transports         String?
  /// ON UPDATE CASCADE, ON DELETE CASCADE
  user               User                        @relation(fields: [userId], references: [id])

  @@unique([userId, name], name: "web_authn_authenticator.userId_name_unique")
  @@map("web_authn_authenticator")
}
```

`WebAuthnAuthenticatorWhereUniqueInput` will be generated like so:
```ts
export type WebAuthnAuthenticatorWhereUniqueInput = {
  id?: number
  base64PublicKey?: string
  base64CredentialId?: string
  web_authn_authenticator.userId_name_unique?: Web_authn_authenticator.userId_name_uniqueCompoundUniqueInput
}
```

Why does it even include the index in there?

**Comment by P4sca1** [comment]
The unexpected entry in `WhereUniqueInput` is already included in the `dmmfString` in `index.js`:
```
{\"name\":\"WebAuthnAuthenticatorWhereUniqueInput\",\"constraints\":{\"maxNumFields\":1,\"minNumFields\":1},\"fields\":[{\"name\":\"id\",\"isRequired\":false,\"isNullable\":false,\"inputTypes\":[{\"type\":\"Int\",\"kind\":\"scalar\",\"isList\":false}]},{\"name\":\"base64PublicKey\",\"isRequired\":false,\"isNullable\":false,\"inputTypes\":[{\"type\":\"String\",\"kind\":\"scalar\",\"isList\":false}]},{\"name\":\"base64CredentialId\",\"isRequired\":false,\"isNullable\":false,\"inputTypes\":[{\"type\":\"String\",\"kind\":\"scalar\",\"isList\":false}]},{\"name\":\"web_authn_authenticator.userId_name_unique\",\"isRequired\":false,\"isNullable\":false,\"inputTypes\":[{\"type\":\"Web_authn_authenticator.userId_name_uniqueCompoundUniqueInput\",\"kind\":\"object\",\"isList\":false}]}]}
```

**Comment by P4sca1** [comment]
A temporary workaround is to remove the names on indexes (that are generated by default with `prisma introspect`) from the schema and run `prisma generate` afterwards.

**Comment by janpio** [comment]
For context:
How did your database to have these index names in the first place? Manually or via some tool?

**Comment by P4sca1** [comment]
`prisma migrate` generated them.

**Comment by pantharshit00** [comment]
Hello @P4sca1 

There is also an issue about this problem and there is also a proposal to introduce a map field on indexes to resolve this.

I will close this one in favour of https://github.com/prisma/prisma/issues/3193

**Comment by P4sca1** [comment]
@pantharshit00 Could you clarify why index names are even added to the WhereInput?

**Comment by P4sca1** [comment]
Because when not exposing them to the client (like with @@id or @@unique), the issue does not occur without the need to specify a map property on @@unique.

**Comment by pantharshit00** [comment]
@P4sca1 Multi field indexes are added to `WhereUnique` inputs as you get a unique row by using a unique combination of values of the index fields.

**Comment by do4gr** [comment]
A proper fix for this problem is now available via the `namedConstraints` preview flag since 2.29. See https://www.prisma.io/docs/guides/upgrade-guides/upgrading-to-use-preview-features/enabling-named-constraints`
