### ISSUE TITLE
Is ok new Prisma per request?

### ISSUE THREAD

**Issue by steida** [prisma/prisma#3968]
I would like to run https://www.apollographql.com/docs/apollo-server/servers/micro.html within Now 2 node lambda.

But I am not sure whether is ok to instantiate Prisma per HTTP request.

**Comment by pantharshit00** [comment]
Hi @steida 

Are you talking about the prisma client? If so then it is completely fine to use that in the serverless environments.

**Comment by steida** [comment]
Yes, thank you.
