### ISSUE TITLE
[Mongo] Embedded types generates wrong typescript typing

### ISSUE THREAD

**Issue by domekol** [prisma/prisma#3973]
**Describe the bug**
Currently, if you use embedded types with typescript typings, the typings for that embedded type gets generated as 
`<T= FragmentableArray<S>>() => T`. If you wanna call this Promise it throws an error, cause the embedded type isnt a function.

Example Datamodel:

```
type User {
  firstName: String!
  lastName: String!
  email: String! @unique
  password: String

  isAdmin: Boolean @default(value: false)

  id: ID! @id
}

enum UserPermission {
  READ
  WRITE
  DELETE
}

type AreaAccess @embedded {
  userId: ID! @db(name: "User")
  permission: UserPermission!
}

type Area {
  name: String!

  id: ID! @id
  updatedAt: DateTime
  createdAt: DateTime

  accesses: [AreaAccess!]!
}
```

Generated Area interface:

```
export interface Area {
  name: String
  id: ID_Output
  updatedAt?: DateTimeOutput
  createdAt?: DateTimeOutput
  accesses?: <T = FragmentableArray<AreaAccess>>() => T
}
```

**To Reproduce**
1. Create Datamodel
2. run prisma generate
3. create resolver with ctx.area({ id }).accesses()
4. throws error
5. create resolver with ctx.area({ id }).accesses
6. all fine

**Expected behavior**
Generated interface should look like this:

```
export interface Area {
  name: String
  id: ID_Output
  updatedAt?: DateTimeOutput
  createdAt?: DateTimeOutput
  accesses?: AreaAccess[]
}
```

**Versions (please complete the following information):**
 - Connector: MongoDB
 - Prisma Server: 1.25.4
 - `prisma` CLI: prisma/1.25.4 (darwin-x64) node-v10.5.0
 - OS: OS X High Sierra

**Comment by pantharshit00** [comment]
I am unable to reproduce this in the latest version of prisma-cli `1.25.6`. Please try to upgrade to that.

![image](https://user-images.githubusercontent.com/22195362/52165332-731c0480-2725-11e9-8f2b-12dd4c80c848.png)

If you think this is still now working please provide us with a reproduction repository.

**Comment by domekol** [comment]
Seems to be gone with prisma `1.25.7` didnt test `1.25.6`

**Comment by domekol** [comment]
I was wrong, the error is still there, the typing is also fine, but the execution throws an error. So create the datamodel i posted and run a graphql query to resolve "accesses".

From test:
` Received: {"data": {"organization": null}, "errors": [[GraphQLError: parent.accesses is not a function]]}`

**Comment by domekol** [comment]
My fault still fixed sry guys :( should have read the error message before post such dumb comment and reopen the issue.
