### ISSUE TITLE
Add union type for all available generated model names

### ISSUE THREAD

**Issue by MarvinRudolph** [prisma/prisma#3973]
## Problem

Currently, there is no way to get all generated model names as a union type, so they can be used as keys.
It would be helpful to restrict the keys of an object to available model names like this:

```ts
type AllModelNames = 'User' | 'Post' | 'Comment'
type Foo = Record<AllModelNames, string>

const foo: Foo = {
  User: 'foo',
  Post: 'bar',
  Comment: 'baz'
}
```
This is just a simple example where the value is a string but I'm sure there are much more complex use-cases where this would be helpful for example with a function as value.

## Suggested solution

Add an auto-generated union type when Prisma generates the client. 
Suggestion: See above (`type AllModelNames`).

## Alternatives

Provide some other way to manually get all the model names. It *could* be a rare use-case but I think it would be still cool to have a way to get the names when you need them.

**Comment by MarvinRudolph** [comment]
Since `v2.11.0` the `model` parameter in middlewares is typed and introduces a `const ModelName` & `type ModelName` which now holds all generated model names. So I think this issue can be closed (correct me if I'm wrong). 
Thanks for that! 🚀

**Comment by pantharshit00** [comment]
Indeed this is done. Closing :)
