### ISSUE TITLE
String arrays with MongoDB

### ISSUE THREAD

**Issue by rafakwolf** [prisma/prisma#3975]
Hey guys...

When I create a schema like this:
```
type MyTest {
  id: ID! @id
  arrayField: [String]
}
```

To add data to this `arrayField` I need to use like this ?
```
{
arrayField: {set: ['a', 'b', 'c']}
}
```
 If i try to use like this:

```
{
arrayField: ['a', 'b', 'c']
}
```
I'm facing the error:
```
Reason: 'arrayField' Expected 'MyTestCreatearrayFieldInput', found not an object
```
Thanks!

**Comment by pantharshit00** [comment]
This is expected behavior. We provide more option in `update` mutations like that.

**Comment by NolanChan** [comment]
@pantharshit00 I'm sorry, but can I get some documentation on why this is expected behavior? Or some better information explaining how to properly handle arrays? Closing this as `expected` without further explanation doesn't leave us with much other recourse besides confusion...

**Comment by do4gr** [comment]
The documentation around scalar lists can be found here: 
https://www.prisma.io/docs/prisma-graphql-api/reference/mutations-qwe2/#scalar-list-mutations

**Comment by pantharshit00** [comment]
@NolanChan

Sorry for not providing the documentation. I was guessing that you all can figure this out from the docs and autocompletion of the graphql playground which outlines the API. But still, I apologize for any inconvenience.

**Comment by eudago** [comment]
Try:

{
   arrayField: { set: ['a', 'b', 'c'] }
}
