### ISSUE TITLE
Add "do not edit" warning for top of prisma-schema.ts in the generated folder

### ISSUE THREAD

**Issue by arnabkd** [prisma/prisma#3976]
**Is your feature request related to a problem? Please describe.**
I think it is a bit confusing that only one of the generated files in the typescript prisma-client have a `DO NOT EDIT.` warning on them.  

**Describe the solution you'd like**
One of the below:
-  Have the same warning header that `index.ts` has
- Maybe have a `README.md` in the generated folder that contains the warning

**Describe alternatives you've considered**
This is not a huge problem as common sense dictates that one does not edit generated files, so no alternatives are really necessary. 

**Additional context**

**Comment by divyenduz** [comment]
This is available in the latest `beta` - `1.27.0-beta.12`, please install it via `npm install -g prisma@beta`.

**Comment by divyenduz** [comment]
This is available in the latest `stable` - `1.28.0`, please install it via `npm install -g prisma`. I am closing this issue, please open a new issue, if necessary.
