### ISSUE TITLE
Problem when delete with cascade

### ISSUE THREAD

**Issue by ralvs** [prisma/prisma#3981]
I have two models 

```prisma
model Sale {
  id            String    @id @default(cuid())
  cart          Item[]
}

model Item {
  id                    String  @id @default(cuid())
  name              String
  sale                Sale     @relation(fields: [saleId], references: [id])
  saleId             String
}
```

Looking at `show create table item` on Mysql, I do have

```
  CONSTRAINT `item_ibfk_2` FOREIGN KEY (`saleId`) REFERENCES `Sale` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
```

If I do `delete from sale where id='some id'` it deletes the sale and the items as expected.

But, when I do the same in Prisma `prisma.sale.delete({ where: { id: 'some id' } })`  I got the error bellow

```
Invalid `prisma.sale.delete()` invocation in webpack-internal:///./graphql/customs/MutationSale.js:459:38 The change you are trying to make would violate the required relation 'SaleToItem' between the `Sale` and `Item` models.
```

Am I doing something wrong?

## Environment & setup

- OS: Mac OS
- Database: MySQL 5.7
- Node.js version: 14.9.0
- Prisma version: 2.9.0

**Comment by P4sca1** [comment]
This is because Prisma does not support cascading deletes yet. 

See https://github.com/prisma/prisma/issues/2057  and https://github.com/prisma/prisma/issues/2810

**Comment by ralvs** [comment]
Thanks @P4sca1 
I will keep an eye on these issues

**Comment by heybenchen** [comment]
@P4sca1 Is this different from the Prisma [guide on cascading deletes](https://www.prisma.io/docs/guides/database-workflows/cascading-deletes/postgresql#92-validating-cascade)? My impression from that article is that deletes like this should work.

**Comment by P4sca1** [comment]
@heybenchen Yes, this is actually a bug, so it does not work like explained in the docs.
See https://github.com/prisma/prisma/issues/2057 for more info.

**Comment by ryands17** [comment]
@heybenchen if your foreign key is nullable, then cascade deletes will work fine. It just doesn't work in the issue that @P4sca1 has described above. As per the tutorial, the foreign key is nullable on the `Post` model so cascade deletes should work.
