### ISSUE TITLE
Error when trying to import before export

### ISSUE THREAD

**Issue by polRk** [prisma/prisma#3986]
**Describe the bug**
I'm trying to import my data, from .zip export file.

**To Reproduce**
1. Export
2. import -d .zip

**Expected behavior**
OK

**Output errors**
  "Failure inserting Car with Id: cjqrv1hkz017k07181ax6eo3e. Cause: duplicate key value violates unique constraint \"Car_pkey\"\n  Detail: Key (id)=(cjqrv1hkz017k07181ax6eo3e) already exists.",

  "Failure inserting Car with Id: cjr2duh8t02dk0718qmts502d. Cause: duplicate key value violates unique constraint \"Car_pkey\"\n  Detail: Key (id)=(cjqrv1hkz017k07181ax6eo3e) already exists.",

  "Failure inserting Car with Id: cjr7voo7z03d307182gukd76u. Cause: duplicate key value violates unique constraint \"Car_pkey\"\n  Detail: Key (id)=(cjqrv1hkz017k07181ax6eo3e) already exists.",

  "Failure inserting Car with Id: cjr7vpnv203d707189ce1xkmi. Cause: duplicate key value violates unique constraint \"Car_pkey\"\n  Detail: Key (id)=(cjqrv1hkz017k07181ax6eo3e) already exists.",

  "Failure inserting RelayRow with Id: cjqrv1hkz017k07181ax6eo3e. Cause: duplicate key value violates unique constraint \"_RelayId_pkey\"\n  Detail: Key (id)=(cjqrv1hkz017k07181ax6eo3e) already exists.",

  "Failure inserting RelayRow with Id: cjr2duh8t02dk0718qmts502d. Cause: duplicate key value violates unique constraint \"_RelayId_pkey\"\n  Detail: Key (id)=(cjqrv1hkz017k07181ax6eo3e) already exists.",

  "Failure inserting RelayRow with Id: cjr7voo7z03d307182gukd76u. Cause: duplicate key value violates unique constraint \"_RelayId_pkey\"\n  Detail: Key (id)=(cjqrv1hkz017k07181ax6eo3e) already exists.",

  "Failure inserting RelayRow with Id: cjr7vpnv203d707189ce1xkmi. Cause: duplicate key value violates unique constraint \"_RelayId_pkey\"\n  Detail: Key (id)=(cjqrv1hkz017k07181ax6eo3e) already exists.",

...

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: [e.g. `1.24.0`]
 - prisma/1.23.2 (linux-x64) node-v8.10.0
 -  Ubuntu 18.04.1 LTS

**Comment by pantharshit00** [comment]
Hi @polRk 

Looks like you are trying to import the data into the same database which would not work. Either you need to empty out that database or you need to use a new database.

**Comment by polRk** [comment]
Yes. You are right. But it is not convenient. Delete - restore... Maybe it would be better to update existing, remove unnecessary, create new.

**Comment by pantharshit00** [comment]
Looks like this is more of a feature request now. 

cc @timsuchanek
