### ISSUE TITLE
Advanced SQL Functions

### ISSUE THREAD

**Issue by mikecfisher** [prisma/prisma#3996]
## Problem

I'd like to use Prisma client for everything and not have to use `$queryRaw`. However my app has complex sql functions sometimes and I'm not sure I can do these with the built in Prisma API. Example: 

`select uid, start_date from location WHERE extract(isodow from start_date) = extract(isodow from now())` 
## Suggested solution
Support these advanced query types. 

## Alternatives

Keep using $queryRaw

If there is another way to accomplish this I'd love to hear it!
Thanks!

**Comment by kuvichkamaksim** [comment]
Hello!

Is something like this planned to be implemented or is it rejected? I'd really like to see this feature in Prisma

**Comment by janpio** [comment]
If it was rejected would be closed with a comment. That it is still open means we consider this a valid feature request, looking for more input and feedback on use cases and potential APIs. If you have that, feel free to leave a comment.

**Comment by gblue1223** [comment]
Duplicate https://github.com/prisma/prisma/issues/5560
