### ISSUE TITLE
Include `@@index` and `@map` information in `getDMMF`

### ISSUE THREAD

**Issue by gogoout** [prisma/prisma#3998]
## Problem

Given schema
```
model UserEmailHistory {
  id               Int       @id @default(autoincrement())
  user_alias       String    @map("alias")
  send_count       Int
  historyable_id   Int?
  historyable_type String?
  user_id          Int
  created_at       DateTime?
  updated_at       DateTime? @updatedAt

  @@index([user_id], name: "user_email_history_user_id_foreign")
  @@map("user_email_history")
}
```
using `getDMMF` will dump as

```json
{
  "name": "UserEmailHistory",
  "isEmbedded": false,
  "dbName": "user_email_history",
  "fields": [
    {
      "name": "id",
      "kind": "scalar",
      "isList": false,
      "isRequired": true,
      "isUnique": false,
      "isId": true,
      "isReadOnly": false,
      "type": "Int",
      "hasDefaultValue": true,
      "default": {
        "name": "autoincrement",
        "args": []
      },
      "isGenerated": false,
      "isUpdatedAt": false
    },
    {
      "name": "user_alias",
      "kind": "scalar",
      "isList": false,
      "isRequired": true,
      "isUnique": false,
      "isId": false,
      "isReadOnly": false,
      "type": "String",
      "hasDefaultValue": false,
      "isGenerated": false,
      "isUpdatedAt": false
    },
    {
      "name": "send_count",
      "kind": "scalar",
      "isList": false,
      "isRequired": true,
      "isUnique": false,
      "isId": false,
      "isReadOnly": false,
      "type": "Int",
      "hasDefaultValue": false,
      "isGenerated": false,
      "isUpdatedAt": false
    },
    {
      "name": "historyable_id",
      "kind": "scalar",
      "isList": false,
      "isRequired": false,
      "isUnique": false,
      "isId": false,
      "isReadOnly": false,
      "type": "Int",
      "hasDefaultValue": false,
      "isGenerated": false,
      "isUpdatedAt": false
    },
    {
      "name": "historyable_type",
      "kind": "scalar",
      "isList": false,
      "isRequired": false,
      "isUnique": false,
      "isId": false,
      "isReadOnly": false,
      "type": "String",
      "hasDefaultValue": false,
      "isGenerated": false,
      "isUpdatedAt": false
    },
    {
      "name": "user_id",
      "kind": "scalar",
      "isList": false,
      "isRequired": true,
      "isUnique": false,
      "isId": false,
      "isReadOnly": false,
      "type": "Int",
      "hasDefaultValue": false,
      "isGenerated": false,
      "isUpdatedAt": false
    },
    {
      "name": "created_at",
      "kind": "scalar",
      "isList": false,
      "isRequired": false,
      "isUnique": false,
      "isId": false,
      "isReadOnly": false,
      "type": "DateTime",
      "hasDefaultValue": false,
      "isGenerated": false,
      "isUpdatedAt": false
    },
    {
      "name": "updated_at",
      "kind": "scalar",
      "isList": false,
      "isRequired": false,
      "isUnique": false,
      "isId": false,
      "isReadOnly": false,
      "type": "DateTime",
      "hasDefaultValue": false,
      "isGenerated": false,
      "isUpdatedAt": true
    }
  ],
  "isGenerated": false,
  "idFields": [],
  "uniqueFields": [],
  "uniqueIndexes": []
}
```

the `@@index` and `@map` information are both missing, this make printing dmmf back to schema impossible.

## Suggested solution

Return indexes in Model field just like `uniqueFields` and `uniqueIndexes`.
add `colName` or `fieldName` to show the original db columnName just like `dbName`.

**Comment by janpio** [comment]
Why would that information be helpful for you, what problem does it solve @gogoout?

**Comment by gogoout** [comment]
Hi, thanks for the quick response. My use case is pretty much like this issue here: https://github.com/IBM/prisma-schema-transformer/issues/8
So we use DMMF act kind like a parser and then do some string transform on the model name and field name. That all went well until we want to print the DMMF back to schema. Like the issue I linked, the index will be removed due to lack of index information. 

Current workaround is simply run another `npx prisma introspect` which will bring back all the index, but it would be nice to have the index info at first place.

**Comment by gogoout** [comment]
Another thing I just noticed is missing is the `@map` on the column. This makes the incremental transform (or simply rerun the transform) not possible. Shall I need to open another issue for this or just update this one will be enough?

**Comment by pantharshit00** [comment]
@gogoout If that is very related to this issue, just update the description, otherwise open a new issue.

**Comment by sabinadams** [comment]
This would be an awesome enhancement that would allow for some nice tooling and transforms to be built. 

I'm needing the @map attribute for my library [aurora](https://github.com/sabinadams/aurora) that stitches multiple schema files together.

Currently, the @map attributes on fields are being omitted in the resulting schema file because that data isn't present in the `getDMMF()` output. The @@map and the @map for enums are showing up. There is also an optional key in the `Model.Field`  type for dbName that just isn't getting populated.

**Comment by RobertCraigie** [comment]
I also have a use case for this: https://github.com/RobertCraigie/prisma-client-py/issues/249

Prisma Client Python provides helper methods for casting raw queries back to the standard model classes, e.g.

```py
query = '''
    SELECT *
    FROM User
    WHERE User.id = ?
'''
user = await client.query_first(query, user.id, model=User)
# or just
user = await User.prisma().query_first(query, user.id)
```

This means that the returned records from raw queries are also type safe!

However this does not work for fields that use `@map` as the data returned from the raw query will now refer to a different field name, e.g.

```prisma
model User {
  id      String   @id @default(cuid())
  name    String   @map("username")
}
```

This causes a validation error at runtime (showcased in the aforementioned issue). Having access to the mapped name would allow me to easily solve this bug.

**Comment by gogoout** [comment]
I recommend using https://github.com/MrLeebo/prisma-ast for now until Prisma team complete their dmmf info. 
Ast should give you everything you need from the schema, however, it maybe a bit harder to extract the info from it, you may need to create an abstraction layer on top of it to represent what's in the dmmf.

**Comment by dimaip** [comment]
We also need `@map` information on fields quite desperately! See my usecase https://github.com/prisma/prisma/issues/14087

Shouldn't be a difficult things to fix, right? And would open so many possibilities for better tooling. 🙏

**Comment by RobertCraigie** [comment]
I have another use case for this.

I cannot currently support `DateTime` fields in the Python client that are marked as `@db.Date` because the client generates `datetime.datetime` types which results in failing runtime validation because values such as `2022-01-20` are not a valid datetime format. https://github.com/RobertCraigie/prisma-client-py/issues/657

**Comment by valtyr** [comment]
Hi there. I'm working on a custom generator that generates Kysely types from a Prisma schema. As of right now there's no way for me to support `@map` statements, since they're not returned with the DMMF. This means that users of my library that use `@map` end up with broken types. The only way for me to support this would be to parse the Prisma schema on my own, which although doable seems redundant. I think it would be a great improvement to pass this info along with the DMMF if only for consistency's sake. Here's a link to the issue on my repo: https://github.com/valtyr/prisma-kysely/issues/2

Thanks 😄

**Comment by dvins** [comment]
This is similarly related to #17754 wherein DMMF does not distinguish models or views, either via a distinct collection or at least through an attribute.

These sorts of issues, especially missing metadata in the DMMF, continue to frustrate work arounds and the fostering of a stronger ecosystem for Prisma.

**Comment by aqrln** [comment]
`@map` information was added two years ago in https://github.com/prisma/prisma-engines/pull/3532, and the full index information was added in July in https://github.com/prisma/prisma-engines/pull/4949. I'll go ahead and close the issue.
