### ISSUE TITLE
Go client formatting is whack; consider running gofmt

### ISSUE THREAD

**Issue by dominikh** [prisma/prisma#4008]
As of `fa49ffc20`, the formatting of the generated Go client is, for the lack of a better word, whack. Indentation is all over the place, with some lines being indented way too deep, and others not being indented at all.

I do not remember this being an issue before. Did we use to pipe the output through gofmt? Or did typescript templates behave differently in the past, stripping certain leading whitespace? At any rate, the status quo is a big no. We're looking at code like this: 
![2019-02-06-130120_929x645_scrot](https://user-images.githubusercontent.com/39825/52340175-5e828980-2a0f-11e9-9b55-7c9647982e4d.png)

**Comment by pantharshit00** [comment]
This has been already fixed in the latest version (`1.27.0`).
