### ISSUE TITLE
Invalid characters in type names are not validated during deployment

### ISSUE THREAD

**Issue by afefer** [prisma/prisma#4028]
**Describe the bug**
Naming a type in the database schema with a starting lowercase letter results in an "internal server error" message from the Prisma CLI when running `prisma deploy` with a cryptic `java.util.NoSuchElementException` error in the server logs if any implicit relations exist in the schema. Lack of a clear error message resulted in hours of investigation/debugging.

**To Reproduce**
1. Create a schema with implicit relations between multiple types that start with lowercase letters.
2. Run `prisma deploy`.

**Expected behavior**
Prisma should validate the schema for invalid type names and return a user-friendly error (e.g. "Invalid type name: type must start with an uppercase letter").

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.23.0` (hosted on Heroku via prisma.io)
 - `prisma` CLI: `prisma/1.26.4 (linux-x64) node-v10.15.0`
 - OS: Ubuntu 16.04 (Windows Subsystem for Linux)

**Comment by pantharshit00** [comment]
Hi @afefer 

I am unable to reproduce this issue. Can you please link a small reproduction as a github issue.

**Comment by pantharshit00** [comment]
Please open a new issue if you still able to reproduce this
