### ISSUE TITLE
Prisma generate hangs when using yarn 2 with custom generator

### ISSUE THREAD

**Issue by rizkyramadhan** [prisma/prisma#4033]
# Bug description

Prisma hang when executing `yarn prisma generate`, 

see my issue at https://github.com/MichalLytek/typegraphql-prisma/issues/22

## How to reproduce

1. Clone `basic-1` example from https://github.com/MichalLytek/typegraphql-prisma/tree/main/examples
2. remove package-lock.json
3. install yarn and run yarn set version berry
4. run yarn on that directory
5. run yarn prisma generate

## Expected behavior

`yarn prisma generate` executed succesfully.

## Environment & setup

- OS:  Windows 10
- Database: PostgreSQL, SQLite
- Node.js version: 14.10.1
- Prisma version: 2.8.1 / 2.9.0 / dev

**Comment by pantharshit00** [comment]
@rizkyramadhan 

Yarn 2 is currently not supported with Prisma. I am going to close this in favor of https://github.com/prisma/prisma/issues/1439

**Comment by HairyRabbit** [comment]
@rizkyramadhan Hi, I also got this issue, would you resolved this by some patch? looks something wrong with generator-helper.

**Comment by rizkyramadhan** [comment]
well, yeah... but it's so brittle that I don't consider using prisma again, now i'm using [objection.js](https://vincit.github.io/objection.js/)
