### ISSUE TITLE
Prisma creates a new database instead of using existing one when using mongodb introspection

### ISSUE THREAD

**Issue by julianossc** [prisma/prisma#4040]
**Describe the bug**
The prisma server always creating new mongodb database when I deploy my service, It is not using the existing database.

**To Reproduce**
Connect to existing mongodb database with prisma server. Set up the new service and deploy it on Prisma Server.

**Expected behavior**
The Prisma server should be use the existing database since it already has some data.

**Whats happen**
The prisma server creates a new database based on service name and stage, and don't use the existing database. ALWAYS.

**Comment by pantharshit00** [comment]
@divyenduz

I can confirm this. To reproduce just try to make project using existing data

**Comment by julianossc** [comment]
Ok, I'm waiting for this fix, thank you

**Comment by pantharshit00** [comment]
cc @do4gr

**Comment by ignatif** [comment]
same here
