### ISSUE TITLE
Won't start backup by crontab

### ISSUE THREAD

**Issue by polRk** [prisma/prisma#4042]
**Describe the bug**
I wont to start daily backups at 12 ap.m.

In my crontab -e
```

SHELL=/bin/sh
PATh=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/root/crm

* * * * * root /root/crm/backup.sh
* 0/12 * * * root /root/crm/backup.sh
```

In my backup.sh
```
#!/bin/sh
prisma export
```

In cron logs ( 2 crontab files with the same code, crontab -e and /etc/cron.d/crm )

```
Feb 12 15:03:01 bots CRON[32686]: (root) CMD (root /root/crm/backup.sh) 
Feb 12 15:03:01 bots CRON[32687]: (root) CMD (/root/crm/backup.sh)
```

**Expected behavior**
Make backups by cron cheduller

**Versions (please complete the following information):**
 - Connector: Postgres
 - prisma/1.23.2 (linux-x64) node-v8.10.0
 - OS: Ubuntu 18.04

**Comment by pantharshit00** [comment]
Looks like you are calling root instead of sh or bash, use this

```cron
* * * * * /bin/sh /root/crm/backup.sh
* 0/12 * * * /bin/sh /root/crm/backup.sh
```

Also, cron uses home as default so make sure you use absolute path in it. Also, add `cd` in your script to the path where you want to export 

This issue is unrelated to prisma, closing

**Comment by polRk** [comment]
Not working. Script run, but no logs, no backup file. Prisma didnt start.

**Comment by polRk** [comment]
I Solved it!

In my crontab 
```
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# m h  dom mon dow   command
* * * * * /bin/sh /root/taxicrm/backup.sh
```

In my backup.sh

```
#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
cd /root/taxicrm
prisma export
mv export-*.zip backups/

```
