### ISSUE TITLE
Prisma Cli doesn't resolve an existing ddbb relation

### ISSUE THREAD

**Issue by marticrespi** [prisma/prisma#4044]
**Describe the bug**
Prisma cli doesn't resolve an object which is in a relation with another one.

**To Reproduce**
@pantharshit00 created this repo for another issue. It's the same structure.

https://github.com/pantharshit00/prisma-issue-4019

1. Go to this repo and clone it, then compose and deploy it, and then in some postgresql ide execute these 3 inserts.

````
-- Customer
INSERT INTO billing."Customer"
(code, "name", "createdAt", "updatedAt")
VALUES('TST','Test', clock_timestamp(), clock_timestamp());

-- Contract
INSERT INTO billing."Contract"
(code, enabled, "activationDateTime", "minimumFee", "lookToBook", "customerId", "createdAt", "updatedAt")
VALUES('B2B', false, clock_timestamp(), 0, 0, 1, clock_timestamp() , clock_timestamp());

-- Item
INSERT INTO billing."Item"
(enabled, "specificFreeTrialDays", "createdAt", "updatedAt", "contractId")
VALUES(false, 40, clock_timestamp(),clock_timestamp(), 1);
````

2. Send a request in playground

````
query {
  contracts {
    id
    Items {
      id
      enabled
    }
  }
}
````
There is any item in the contract.

![image](https://user-images.githubusercontent.com/6670879/52718150-15987b00-2fa3-11e9-8cd3-02ed13e8e82d.png)

But if you go to the DDBB IDE you can see the expected result with an inner join.

![image](https://user-images.githubusercontent.com/6670879/52718031-cf431c00-2fa2-11e9-84c0-e588d6e537e0.png)

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.26.4`
 - `prisma` CLI: `1.26.4`
 - OS: `Windows 10`

**Comment by marticrespi** [comment]
Any news about it?

**Comment by marticrespi** [comment]
@pantharshit00 is this on the way to be fixed? It's primordial that working fine to be used. I have updated `prisma-client-lib` and `prisma` to 1.27.1 and it still doesn't work.

**Comment by do4gr** [comment]
You might have heard that we are transitioning to a new datamodel, see https://github.com/prisma/prisma/issues/3408.

For this we will soon start a closed beta. I tested the functionality using that datamodel and there it works. I'll invite you once the beta starts and then it should work for you. Since we are so close to switching over we'll not fix this bug for the old datamodel though.

**Comment by marticrespi** [comment]
Ok, I will wait for this beta, Please let me know once beta version released. I can't release my project to production if these relations don't work. Is there a date to start with this beta? It's only for planning my work about it.

Many thanks!

**Comment by pantharshit00** [comment]
@marticrespi 

Here is the beta of datamodel 1.1: https://github.com/prisma/datamodel-v1.1-feedback

**Comment by marticrespi** [comment]
Hi @pantharshit00 , I have updated my client and server version to 1.34.5 and it happens again.

![image](https://user-images.githubusercontent.com/6670879/62921145-1cfcdd80-bda8-11e9-8dbd-789a7653b71d.png)

![image](https://user-images.githubusercontent.com/6670879/62921160-2b4af980-bda8-11e9-8aae-5ef307b47ce7.png)

This contract has 3 items, but when I run a query it doesn't return its items. Can someone of your prisma 1 team take a look?

Here is my new `datamodel.prisma` generated with 1.34.5 version.

````
type Contract @db(name: "Contract") {
  activationDateTime: DateTime
  code: String! @unique
  Costs: [Cost]
  createdAt: DateTime! @createdAt
  customer: Customer
  enabled: Boolean! @default(value: false)
  GlobalConditions: GlobalCondition! @relation(link: TABLE)
  id: Int! @id(strategy: SEQUENCE) @sequence(name: "Contract_id_seq", initialValue: 1, allocationSize: 1)
  Items: [Item]
}

type Item @db(name: "Item") {
  contract: Contract
  createdAt: DateTime! @createdAt
  enabled: Boolean @default(value: false)
  id: Int! @id(strategy: SEQUENCE) @sequence(name: "Item_id_seq", initialValue: 1, allocationSize: 1)
  specificFreeTrialDays: Int
  updatedAt: DateTime! @updatedAt
}
````

**Comment by marticrespi** [comment]
It doesn't show its items because in the deploy when it's doing the changes from old to new datamodel it sets all FK to null.
