### ISSUE TITLE
Can't pull image

### ISSUE THREAD

**Issue by humbertocruz** [prisma/prisma#4049]
**Describe the bug**
Can't pull image

**To Reproduce**
docker-compose up -d after prisma init

**Expected behavior**
The https://registry-1.docker.io/v2/prismagraphql/prisma/manifests/latest is asking for authorization

**Comment by pantharshit00** [comment]
Hi @humbertocruz 


We current dont publish the latest tag but there is an issue about it #3244 

Please use `1.26` tag right now

**Comment by pantharshit00** [comment]
Closing as a duplicate of #3244
