### ISSUE TITLE
prisma import fails to insert list of strings found within the export

### ISSUE THREAD

**Issue by Inkdpixels** [prisma/prisma#4056]
**Describe the bug**
`prisma import --data export.zip` fails to correctly insert list of strings on most entities even though the data is provided in the `.zip` file on all entities. 

Below you will find a `prisma.zip` which holds the schema / `prisma.yaml` as well as the `export.zip` of the project.

[prisma.zip](https://github.com/prisma/prisma/files/2865806/prisma.zip)
[export.zip](https://github.com/prisma/prisma/files/2865807/export.zip)

**To Reproduce**
1. Unzip the schema and deploy a new service on your Prisma instance, e.g. `CORE_REVISION=1 CORE_PRISMA_HOST=localhost npx prisma deploy`
2. Import the export via `CORE_REVISION=1 CORE_PRISMA_HOST=localhost npx prisma import --data export.zip`
3. Visit your prisma instance and query `{ products { pid, variations { id, vid, images } } }`
4. Inspect the result, the first 30 or so products should contain variations with images but all remaining variations and their `images` property hold an empty list. 
6. Unzip the `export.zip` on your local machine
5. Inspect the IDs of the variations **without** images and find them in the unzipped export folder, they should contain images (e.g. not be an empty list). 

**Expected behavior**
The images should have been imported.

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.26.0`
 - `prisma` `prisma/1.26.4 (darwin-x64) node-v10.15.1`
 - OS: `OS X High Sierra`

**Comment by pantharshit00** [comment]
@Inkdpixels 

I tried to reproduce it but the data you have sent doesn't contain image for those ids so this is expected can you please double check? Sorry for the delay though

![image](https://user-images.githubusercontent.com/22195362/53025805-a7165a00-3487-11e9-8519-bebf8189bd2a.png)
