### ISSUE TITLE
prisma-client Vue example

### ISSUE THREAD

**Issue by ernestomccormick** [prisma/prisma#4058]
It would be nice to have an example of prisma-client with Vue. I want to know if it is possible to write and read data without Apollo (vue-apollo).

**Comment by HokumGuru** [comment]
Prisma-client is meant for server backends when communicating with a Prisma server - not web applications. It is not a replacement for Apollo.

**Comment by pantharshit00** [comment]
As @HokumGuru has already explain that prisma is not meant to be consumed directly via the frontend. You will require to build a graphQL API with prisma and then use apollo to make queries from the frontend.
