### ISSUE TITLE
Understand Prisma $connect behavior

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4068]
## Bug description

`prisma.$connect()` behaviour is unexpected, it blocks to acquire a connection even though a connection is available. 

## How to reproduce

Follow the instructions in this reproduction repro https://github.com/divyendu-test/p2-connect

## Expected behavior

Prisma should be able to acquire a connection when it is available.

**Comment by matthewmueller** [comment]
**Given:**

- Prisma with PgBouncer (MAX_CLIENT_CONN=2) in front of a Postgres (max_connections=1)
- Workload, we attempt to make 2 connections and run a "sleep 20" query with each connection. The query is run async.

**Expected**

```
1st connect
1st sleep 20 query sent async
2nd connect
2nd sleep 20 query sent async
1st query returned
2nd query returned
```

**Actual**

```
1st connect
1st sleep 20 query sent async
1st query returned
2nd connect
2nd sleep 20 query sent async
2nd query returned
```

The Expected is based on node-postgres' Pool implementation. Our pool implementation is slightly different, but working as originally designed:

1. Client 1: Calls $connect()
2. Client 1: $connect() opens a connection to pgBouncer (1 of 2 pgBouncer connections used up)
2. Client 1: $connect() issues a `SELECT 1` healthcheck against the database
3. Client 1: $connect() returns
3. Client 1: Runs sleep for 20 seconds (holding onto 1 of 1 postgres connections)
3. Client 2: Calls $connect()
2. Client 2: $connect() opens a connection to pgBouncer (2 of 2 pgBouncer connections used up)
2. Client 1 is already mid-query, so Client 2 waits until Client 1 is done to call `SELECT 1`.
2. Client 2: $connect() issues a `SELECT 1` healthcheck against the database
3. Client 2: $connect() returns
