### ISSUE TITLE
[EPIC] Microsoft SQL Server (GA)

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma#4081]
## Problem

Iterate on our Microsoft SQL Server connector support to support migrations and alleviate known issues or feedback we'll receive on this.

## Related issues

 - [x] Support for Migrations: https://github.com/prisma/prisma/issues/4074
 - [x] Support for Native Types: https://github.com/prisma/prisma/issues/4077

**Comment by jackytse** [comment]
Do we support older SQL Server versions? Like SQL Server 2008.

**Comment by thebiglabasky** [comment]
Hi,
The versions we test against are listed here: https://www.prisma.io/docs/reference/database-reference/supported-databases/#preview
This doesn't necessarily mean it won't work, but that we don't have end-to-end tests setup for the versions which aren't listed. In the case of SQL Server 2008, since this version is no longer supported by Microsoft, it is unlikely that we'll invest in testing for it.

**Comment by jackytse** [comment]
@thebiglabasky Thanks for your answer, we have to support SQL Server 2008.

**Comment by thebiglabasky** [comment]
Hi @jackytse, that's good to know. Would you be willing to share more details about the context in which you need this? I'm happy to hop on a call: https://calendly.com/labas-prisma/sqlserver-feedback
Thank you

**Comment by jackytse** [comment]
@thebiglabasky I'm so sorry, I can't visit calendly.com in China Mainland. 

we have to support SQL Server 2008, because a few of our customers don't upgrade their  SQL Server 2008, we can't lost them 😕. 

prisma can't support SQL Server 2008, because the SQL Server 2008 don't support the 'OFFSET...FETCH...' syntax.

**Comment by thebiglabasky** [comment]
@jackytse I see. I will be off for the next 2.5 weeks so I would love to schedule some time to chat around January 11th onwards.
Could you reach out to labas@prisma.io to propose some slots so we could discuss?
Thank you

**Comment by janpio** [comment]
Will go GA when we close https://github.com/prisma/prisma/issues/4039

**Comment by silverham** [comment]
I should note that for Primsa version `5.20.0`, using the migration diff command:
```bash
npx prisma migrate diff \
--from-schema-datamodel prisma/schema.prisma \
--to-migrations prisma/migrations \
[...]
```
is not supported for Microsoft SQL Server - getting error <code>Error: \`mssql\` is not a supported connector.</code>.

However, the other migrate diff command does work
```bash
npx prisma migrate diff \
--from-schema-datamodel prisma/schema.prisma \
--to-schema-datasource prisma/schema.prisma \
[...]
```

This issue doesn't seem listed at: https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/limitations-and-known-issues
