### ISSUE TITLE
RangeError: Invalid count value during create

### ISSUE THREAD

**Issue by dpankros** [prisma/prisma#4083]
When performing a transaction-bound create (with a bunch of sub-creates), I'm getting:
```
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at Object.transformLine (/Users/dpankros/Development/workflow-test/server/node_modules/@prisma/client/runtime/src/runtime/utils/printJsonErrors.ts:120:42)
    at /Users/dpankros/Development/workflow-test/server/node_modules/@prisma/client/runtime/src/runtime/utils/stringifyObject.ts:157:30
    at Array.map (<anonymous>)
    at i (/Users/dpankros/Development/workflow-test/server/node_modules/@prisma/client/runtime/src/runtime/utils/stringifyObject.ts:132:12)
    at /Users/dpankros/Development/workflow-test/server/node_modules/@prisma/client/runtime/src/runtime/utils/stringifyObject.ts:144:25
    at Array.map (<anonymous>)
    at i (/Users/dpankros/Development/workflow-test/server/node_modules/@prisma/client/runtime/src/runtime/utils/stringifyObject.ts:132:12)
    at /Users/dpankros/Development/workflow-test/server/node_modules/@prisma/client/runtime/src/runtime/utils/stringifyObject.ts:144:25
    at Array.map (<anonymous>)
```
Unfortunately, I cannot provide a reproducible chunk of code at this point as it is a bit involved, but I do have a theory

[Referencing this bit of code](https://github.com/prisma/prisma/blob/d277ff3e31fec1908d941cef9198b6dc7e2f198e/src/packages/client/src/runtime/utils/printJsonErrors.ts#L160), and reproduced below: 
```javascript
  if (typeof value === 'object') {
    return (
      getLongestLine(`${key}: ${stripAnsi(stringifiedValue)}`) - indent.length. // THIS LINE HERE
    )
  }
```

The only way I can see this error occurring, is if in the referenced line, `getLongestLine` returns a value less than `indent.length` (say, zero).  If that's the case, `getValueLength` returns a negative number, [which is passed as the argument to ](https://github.com/prisma/prisma/blob/d277ff3e31fec1908d941cef9198b6dc7e2f198e/src/packages/client/src/runtime/utils/printJsonErrors.ts#L120)`'~'.repeat()`  and negative values or Infinity passed to `String.repeat`, [cause the 'Invalid count value' error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat#Syntax).

If that theory is correct, a quick guard against this would be:
```javascript
      Math.max(getLongestLine(`${key}: ${stripAnsi(stringifiedValue)}`) - indent.length, 0)
```

### Environment
>$ npx prisma --version
>Environment variables loaded from package.json configuration at src/prisma/.env
>@prisma/cli          : 2.9.0
>@prisma/client       : 2.9.0
>Current platform     : darwin
>Query Engine         : query-engine 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/query-engine-darwin)
>Migration Engine     : migration-engine-cli 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/migration-engine-darwin)
>Introspection Engine : introspection-core 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/introspection-engine-darwin)
>Format Binary        : prisma-fmt 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules/@prisma/cli/prisma-fmt-darwin)
>Studio               : 0.296.0
>Preview Features     : transactionApi

> node --version
> v12.19.0

**Comment by dpankros** [comment]
Update:  
Looks like I passed in a blank array for a an entity-linked property to `.create()`. 
E.g.:
```
{
 ...some props...
  aLinkedProp: { connect: { id: [] }, create: [ [Object], [Object] ] }
}

```

**Comment by timsuchanek** [comment]
Thanks @dpankros! We'll have a look this sprint.

**Comment by timsuchanek** [comment]
You just made it into our sprint planning :D
