### ISSUE TITLE
Incorrect handling of "undefined" in queries

### ISSUE THREAD

**Issue by jebenois** [prisma/prisma#4088]
## Bug description

When using "undefined" for a field in a query, it replaces it with 1=1 which seems to contradict the docs: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/null-and-undefined.

## How to reproduce

Given the following code:

```js
prisma.myTable.findMany({
    where: {
        OR: [{ field1: 'someValue' }, { field2: undefined }],
    },
});
```

The produced query will be:
```
prisma:query 
SELECT "prisma"."MyTable"."id", "prisma"."MyTable"."field1", "prisma"."MyTable"."field2"
FROM "prisma"."MyTable"
WHERE ("prisma"."MyTable"."field1" = $1 OR 1=1) OFFSET $2
```

## Expected behavior

According to the docs, the fields which have an "undefined" value should be ignored.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v12.16.3
- Prisma version: prisma 2.10.0

**Comment by pantharshit00** [comment]
The query looks alright to be. The filter is correctly ignored in the `WHERE` part of the SQL query.

If you are talking about ignore fields in the `SELECT` part of the query, that is not what the docs are trying to describe. `undefined` is ignored on filters, it won't change the default selection set.

If you want to change the default selection set, use the `select` key: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/field-selection#select

**Comment by jebenois** [comment]
The issue is the 1=1, it returns true all the time returning all the rows from the table. It is not ignored.

**Comment by pantharshit00** [comment]
Ohhh, thanks for pointing out. I misinterpreted the problem at first. I can reproduce this and we will need to fix it.
