### ISSUE TITLE
Pagination argument 'after' and 'before' broken since 1.27

### ISSUE THREAD

**Issue by IngoValente** [prisma/prisma#4093]
**Describe the bug**
When I try to query a connection type query with version 1.27 and use the 'before' or 'after' argument, prisma throws an internal server error. When downgrading prisma server to 1.26.4 it works correctly.

**To Reproduce**
1. Clone prisma example with docker & postgres: https://github.com/prisma/prisma-examples/tree/master/node/docker-postgres
2. Follow the steps in the readme to get server and database up and running
3. Run `npm run start` once to populate the db with some posts
4. Copy the first ID return from allPosts query
5. Modify the allPosts query in `src/script.js` to use `prisma.postsConnection` instead of `prisma.posts`, and add the `after` argument with the just copied id. Example:
```
const allPosts = await prisma.postsConnection({
    where: { published: true },
    first: 1,
    after: "cjsj52wxt000s0813o7m3wtpx"
  });
```
6. Run `npm run start` again, this time throwing the internal server error.

**Expected behavior**
Correctly parse the after or before argument to return the next 'paged' results/edges for the query

**Versions (please complete the following information):**
 - Connector: postgres
 - Prisma Server: 1.27
 - `prisma` CLI: 1.27
 - OS: macOS mojave (10.14.3)
 - other dependencies: `prisma-client`, docker

**Additional context**
<details>
  <summary>Example error thrown in 1.27</summary>

{"key":"error/unhandled","requestId":"local:cjsj4ipzw002a084286x5gotb","clientId":"default$default","payload":{"exception":"scala.MatchError: (\"default$default\".\"Sense\".\"id\",\"Alias\".\"id\",asc) (of class scala.Tuple3)","query":"query Cases {\n  sensesConnection(first: 3, after: \"cjm4p7dun00960801kvrjblnx\") {\n    edges {\n      node {\n        id\n        name\n      }\n    }\n  }\n}\n","variables":"{}","code":"0","stack_trace":"com.prisma.api.connector.jdbc.database.CursorConditionBuilder.buildCursorCondition(CursorConditionBuilder.scala:26)\\n com.prisma.api.connector.jdbc.database.CursorConditionBuilder.buildCursorCondition$(CursorConditionBuilder.scala:16)\\n com.prisma.api.connector.jdbc.database.JdbcActionsBuilder.buildCursorCondition(JdbcActionsBuilder.scala:24)\\n com.prisma.api.connector.jdbc.database.NodeManyQueries.modelQuery(NodeManyQueries.scala:47)\\n com.prisma.api.connector.jdbc.database.NodeManyQueries.getNodes(NodeManyQueries.scala:15)\\n com.prisma.api.connector.jdbc.database.NodeManyQueries.getNodes$(NodeManyQueries.scala:14)\\n com.prisma.api.connector.jdbc.database.JdbcActionsBuilder.getNodes(JdbcActionsBuilder.scala:24)\\n com.prisma.api.connector.jdbc.impl.JdbcDataResolver.getNodes(JdbcDataResolver.scala:59)\\n com.prisma.api.resolver.GetNodesDeferredResolver.resolve(GetNodesDeferredResolver.scala:17)\\n com.prisma.api.resolver.DeferredResolverImpl.$anonfun$resolve$3(DeferredResolverImpl.scala:79)\\n scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)\\n scala.collection.immutable.Map$Map1.foreach(Map.scala:125)\\n scala.collection.TraversableLike.map(TraversableLike.scala:233)\\n scala.collection.TraversableLike.map$(TraversableLike.scala:226)\\n scala.collection.AbstractTraversable.map(Traversable.scala:104)\\n com.prisma.api.resolver.DeferredResolverImpl.resolve(DeferredResolverImpl.scala:78)\\n sangria.execution.Resolver.sangria$execution$Resolver$$resolveDeferred(Resolver.scala:766)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$2(Resolver.scala:132)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$2$adapted(Resolver.scala:132)\\n scala.collection.Iterator.foreach(Iterator.scala:937)\\n scala.collection.Iterator.foreach$(Iterator.scala:937)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1425)\\n scala.collection.IterableLike.foreach(IterableLike.scala:70)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:69)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$1(Resolver.scala:132)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$1$adapted(Resolver.scala:131)\\n scala.util.Success.foreach(Try.scala:249)\\n scala.concurrent.Future.$anonfun$foreach$1$adapted(Future.scala:225)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)","message":"(\"default$default\".\"Sense\".\"id\",\"Alias\".\"id\",asc) (of class scala.Tuple3)"}}

</details>

**Comment by pantharshit00** [comment]
@IngoValente 

I am able to confirm this reproduction

Here is the request log

```json
{
  "key": "error\/unhandled",
  "requestId": "local:cjske0pod001p0863qoog1r8i",
  "clientId": "default$default",
  "payload": {
    "exception": "scala.MatchError: (\"default$default\".\"Post\".\"id\",\"Alias\".\"id\",asc) (of class scala.Tuple3)",
    "query": "query ($where: PostWhereInput, $first: Int, $after: String) {\n  posts(where: $where, first: $first, after: $after) {\n    id\n    createdAt\n    updatedAt\n    title\n    content\n    published\n  }\n}\n",
    "variables": "{\"where\":{\"published\":true},\"first\":1,\"after\":\"cjskdz0sh000f086372fxtew6\"}",
    "code": "0",
    "stack_trace": "com.prisma.api.connector.jdbc.database.CursorConditionBuilder.buildCursorCondition(CursorConditionBuilder.scala:26)\\n com.prisma.api.connector.jdbc.database.CursorConditionBuilder.buildCursorCondition$(CursorConditionBuilder.scala:16)\\n com.prisma.api.connector.jdbc.database.JdbcActionsBuilder.buildCursorCondition(JdbcActionsBuilder.scala:24)\\n com.prisma.api.connector.jdbc.database.NodeManyQueries.modelQuery(NodeManyQueries.scala:47)\\n com.prisma.api.connector.jdbc.database.NodeManyQueries.getNodes(NodeManyQueries.scala:15)\\n com.prisma.api.connector.jdbc.database.NodeManyQueries.getNodes$(NodeManyQueries.scala:14)\\n com.prisma.api.connector.jdbc.database.JdbcActionsBuilder.getNodes(JdbcActionsBuilder.scala:24)\\n com.prisma.api.connector.jdbc.impl.JdbcDataResolver.getNodes(JdbcDataResolver.scala:59)\\n com.prisma.api.resolver.GetNodesDeferredResolver.resolve(GetNodesDeferredResolver.scala:17)\\n com.prisma.api.resolver.DeferredResolverImpl.$anonfun$resolve$3(DeferredResolverImpl.scala:79)\\n scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)\\n scala.collection.immutable.Map$Map1.foreach(Map.scala:125)\\n scala.collection.TraversableLike.map(TraversableLike.scala:233)\\n scala.collection.TraversableLike.map$(TraversableLike.scala:226)\\n scala.collection.AbstractTraversable.map(Traversable.scala:104)\\n com.prisma.api.resolver.DeferredResolverImpl.resolve(DeferredResolverImpl.scala:78)\\n sangria.execution.Resolver.sangria$execution$Resolver$$resolveDeferred(Resolver.scala:766)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$2(Resolver.scala:132)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$2$adapted(Resolver.scala:132)\\n scala.collection.Iterator.foreach(Iterator.scala:937)\\n scala.collection.Iterator.foreach$(Iterator.scala:937)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1425)\\n scala.collection.IterableLike.foreach(IterableLike.scala:70)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:69)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$1(Resolver.scala:132)\\n sangria.execution.Resolver.$anonfun$immediatelyResolveDeferred$1$adapted(Resolver.scala:131)\\n scala.util.Success.foreach(Try.scala:249)\\n scala.concurrent.Future.$anonfun$foreach$1$adapted(Future.scala:225)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)",
    "message": "(\"default$default\".\"Post\".\"id\",\"Alias\".\"id\",asc) (of class scala.Tuple3)"
  }
}
```

cc @do4gr @divyenduz

**Comment by pantharshit00** [comment]
I can still reproduce this in 1.27.2

**Comment by do4gr** [comment]
Thanks for reporting this @IngoValente . We'll release a fix today.

**Comment by IngoValente** [comment]
Thank you guys for the quick fix!
