### ISSUE TITLE
Prisma Client doesn't load root .env

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#4096]

**Comment by timsuchanek** [comment]
We're fixing this in `2.10.1`

**Comment by louisrli** [comment]
I think this may have caused a breaking change in my case. For me:
* In my unit tests, I had a few mocking prisma where I asserted that DATABASE_URL was not set (to make sure the tests were hermetic)
* My .env file was being used for a local configuration to my localhost psql database

After 2.10.1 update, I can't control whether prisma client is loading .env anymore or not, it kinda does it without my wanting it to happen. Is there a way to tell the prisma client not to look at .env for my unit tests?
