### ISSUE TITLE
Can't resolve 'fs' in /node_modules/prettier

### ISSUE THREAD

**Issue by deepak-kapoor** [prisma/prisma#4099]
**Describe the bug**
I generated prisma client by running ```prisma generate```

I then copied the generated folder to my next app

After installing prisma-client-lib I get this error when I run my app

Can't resolve 'fs' in /node_modules/prettier

**Comment by riedmann** [comment]
did you solve this?

**Comment by dnlfrst** [comment]
# Problem
I, too, stumbled accross this issue: 

![cannot-resolve-fs](https://user-images.githubusercontent.com/13868083/56082952-4bc96e00-5e1f-11e9-84bd-ed6651d7c2e7.PNG)

# Solution
This following does not seem like a solution but rather is a workaround using your wepack configuration. To avoid the above issue, add

```
node: {
    fs: 'empty'
}
```

to the webpack configuration (`webpack.config.js`/`webpack.config.ts`).
