### ISSUE TITLE
Are there updates over multi tenancy?

### ISSUE THREAD

**Issue by solinad21** [prisma/prisma#4099]
Are there updates over multi tenancy?

_Originally posted by @solinad21 in https://github.com/prisma/prisma/issues/2077#issuecomment-719052669_

**Comment by thebiglabasky** [comment]
Not at the moment, this is something we would reconsider early 2021 as we are heads down into stabilizing migrate, SQL Server, delivering native types, and limiting raw SQL fallbacks by adding support for operations like group by, more filtering, and solutions for transactional use cases.
That's definitely something we want to get to, but meanwhile, you'd have to handle that using https://github.com/Errorname/prisma-multi-tenant
I'll close this issue so we can keep the conversation in the orginal #2077 one.
Thanks!
