### ISSUE TITLE
[1.27.1] Increased timeout breaks existing deploys on Heroku

### ISSUE THREAD

**Issue by k0ff33** [prisma/prisma#4115]
**Describe the bug**
I believe increasing the request timeout in v1.27.1 (22c83ce) breaks Heroku deployments.

After upgrading my Prisma instance from v1.25 to v1.27 on Heroku, I ended up with a non-descriptive `ERROR: GraphQL Error (Code: 503)` when running `prisma deploy` on an existing service. Upon checking the dyno logs, I've discovered an H12 error - "Request timeout". After downgrading to v1.26 deploys worked perfectly. This doesn't effect deploying new services - I was able to run `prisma deploy -n` and created new service without an issue.

Heroku has a hard limit of [30 seconds](https://devcenter.heroku.com/articles/error-codes#h12-request-timeout) for network requests.

**To Reproduce**
1. Upgrade existing Heroku dyno to `1.27-heroku`
2. Run `prisma deploy`
3. See error
4. Downgrade to `1.26-heroku`
5. Run `prisma deploy`
6. See successful deploy message

**Expected behavior**
`prisma deploy` should deploy without any errors.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.27.2`
 - `prisma` CLI: `prisma/1.27.3 (darwin-x64) node-v10.15.1`
 - OS: `OS X Mojave`

**Additional context**
Steps used to update Heroku instance: https://github.com/prisma/prisma-cloud-feedback/issues/202#issuecomment-414095090
Thread on Prisma's slack: https://prisma.slack.com/archives/CA491RJH0/p1551440521070000

Full error message:
> ERROR: GraphQL Error (Code: 503)
> {
>   "error": "<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\t\t<meta charset=\"utf-8\">\n\t\t<title>Application Error</title>\n\t\t<style media=\"screen\">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src=\"//www.herokucdn.com/error-pages/application-error.html\"></iframe>\n\t  </body>\n\t</html>",
>   "status": 503
> }

Dyno log:
> 2019-03-01T11:54:19.348650+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/management" host=awdis-prisma.herokuapp.com request_id=96d815c5-5260-4c76-aec9-5ae1425880e4 fwd="77.96.237.217" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https

**Comment by Fabiomad85** [comment]
I have same problem.

**Comment by HugoLiconV** [comment]
Same

**Comment by cuongw** [comment]
I have a same issue. Have a solution?
