### ISSUE TITLE
TypeError: Cannot read property 'padEnd' of undefined

### ISSUE THREAD

**Issue by royra** [prisma/prisma#4117]
## Bug description

This error happens a few dozen times a day on prod, so I can't easily reproduce it locally.
Example stack trace:

```
TypeError: Cannot read property 'padEnd' of undefined
    at Object.Jf [as getErrorMessageWithLink] (/project/webpack:/engine-core/src/Engine.ts:109:32)
    at yw.handleRequestError (/project/webpack:/engine-core/src/NodeEngine.ts:1209:11)
    at /project/webpack:/engine-core/src/NodeEngine.ts:1007:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at $w.request (/project/webpack:/home/circleci/project/node_modules/@prisma/client/runtime/src/runtime/getPrismaClient.ts:1225:24)
```

We're using webpack, and looks like `os.platform` is `undefined`.
The actual error is not included in the stack, as the error is in the error handling :)

It would be nice if general errors like this could be caught in the error handling flow so the original error stack can be seen.

## Prisma information

Prisma 2.9.0 on Node 12.18 (AWS lambda).

**Comment by pantharshit00** [comment]
Hi @royra 

Thanks for reporting this. I attempted a simple reproduction with webpack and wasn't able to reproduce this.

So I would like to wait for someone who encounters the same and have a proper reproduction so that we can identify the bug.

**Comment by royra** [comment]
@pantharshit00 thanks for the quick response!

Looking at the code again, this may not be related to webpack.

The code at [`NodeEngine.ts` (line 1209)](https://github.com/prisma/prisma/blob/40abb5569f7b1fb623c7f688010301e225486aed/src/packages/engine-core/src/NodeEngine.ts#L1209) is calling `getErrorMessageWithLink` before `this.platform` is initialized - looks like a bug in the error handling. It's masking the actual error which is intermittent.

**Comment by pantharshit00** [comment]
cc @williamluke4

**Comment by williamluke4** [comment]
Will have a look tomorrow :)

**Comment by royra** [comment]
@williamluke4 any progress? we're still affected by this - it masks real errors making debugging on our side difficult. LMK if you want me to try and open a PR to fix.

**Comment by williamluke4** [comment]
Hey @royra, Thank you for reporting this. I've implemented a quick fix which should make it into the next release. Please ping me if this persists after `2.13` is released :)
