### ISSUE TITLE
Error following AWS Fargate tutorial

### ISSUE THREAD

**Issue by romseguy** [prisma/prisma#4124]
CREATE_FAILED error following [the tutorial](https://github.com/prisma/prisma/blob/master/docs/1.9/03-Tutorials2/06-Deploy-Prisma-Servers/05-AWS-Fargate.md#23-wait-%EF%B8%8F) after completing the steps leading to step 2.3.

![err](https://user-images.githubusercontent.com/109238/53763779-e30bdf00-3ecb-11e9-975d-959ffa9d403e.png)

I really doubt I missed a step, but maybe I did?

**Comment by emil-layerise** [comment]
I've just done the tutorial with no error. Try removing all your stacks related to the tutorial and start over.

**Comment by pantharshit00** [comment]
@romseguy 

I am also not experiencing any issue. Can you please try again?

If you are still getting this, please tell us the steps to reproduce this.

**Comment by taikn** [comment]
I've stumbled upon the same error, what helped is this command from step 1.2 (in Note) of the tutorial, which creates a service linked role in IAM:
```bash
aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com
```
though I was using mysql template.

**Comment by romseguy** [comment]
@taikn thank you, I had skipped this instruction because it was beginning with `If you’d like the aurora.yml template instead,`

**Comment by pantharshit00** [comment]
I think this has solved it. Let me know if you are still experiencing some issues.

**Comment by romseguy** [comment]
@pantharshit00 yes, I'm getting following cryptic error on ` prisma deploy ` 

```
$ porygon-prisma-service prisma deploy
  environment FetchError: invalid json response body at http://poryg-publi-19rale09ondd0-1625885604.eu-west-1.elb.amazonaws.com/management reason: Unexpected token < in JSON at position 0
  environment     at /home/x240/n/lib/node_modules/prisma/node_modules/node-fetch/lib/index.js:254:32
  environment     at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
  environment FetchError: invalid json response body at http://poryg-publi-19rale09ondd0-1625885604.eu-west-1.elb.amazonaws.com/management reason: Unexpected token < in JSON at position 0
  environment     at /home/x240/n/lib/node_modules/prisma/node_modules/node-fetch/lib/index.js:254:32
  environment     at process._tickCallback (internal/process/next_tick.js:68:7) +882ms
Error: Could not connect to server at http://poryg-publi-19rale09ondd0-1625885604.eu-west-1.elb.amazonaws.com. Please check if your server is running.
    at Deploy.<anonymous> (/home/x240/n/lib/node_modules/prisma/node_modules/prisma-cli-core/src/commands/deploy/deploy.ts:127:13)
    at step (/home/x240/n/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:45:23)
    at Object.next (/home/x240/n/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:26:53)
    at fulfilled (/home/x240/n/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  util timed out +0ms
Exiting with code: 0
```

**Comment by pantharshit00** [comment]
Can you please open cloud watch and see if there any logs for this?

**Comment by romseguy** [comment]
Only thing I see in cloudwatch (first time I'm using the tool) is an alarm from a few days ago about the database, so pretty unrelated.

**Comment by 5achinJani** [comment]
I'm facing the exact same issue. Any updates on this?

**Comment by 5achinJani** [comment]
![image](https://user-images.githubusercontent.com/23077544/54694509-58271780-4b4e-11e9-8175-007f2283abd5.png)

**Comment by 5achinJani** [comment]
I figured it out the issue was related to the db user name it should be the same that you set in creating the database cloud-formation stack. 
`DatabaseUsername` in the database stack and
`DbUser` in the prisma server stack should be the same. 
Resolved for me. 
@romseguy Can you verify this thing in your stacks if it is still not resolved for you.

**Comment by romseguy** [comment]
@5achinJani thank you but for me both `DatabaseUsername` and `DbUser` were set to `prisma`.

**Comment by pantharshit00** [comment]
@romseguy 

Can you please try redeploying the fargate instance. We recently did some changes in the template.

**Comment by romseguy** [comment]
@pantharshit00 sorry but I recently gave up using AWS for deployment

**Comment by pantharshit00** [comment]
I am going to close then. Anyone facing similar issues, please open a new one
