### ISSUE TITLE
Stabilize transactionApi

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4126]
Stabilize the `transactionApi` preview feature #3104.

**Comment by dpetrick** [comment]
Closed with prisma/prisma-engines#1330

**Comment by timsuchanek** [comment]
Not yet integrated in CLI & Client.

**Comment by matthewmueller** [comment]
This isn't working for me when you run `prisma generate` without the feature flag.

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int    @id @default(autoincrement())
  first String
  last  String
  posts Post[]
}

model Post {
  id     Int    @id @default(autoincrement())
  title  String
  body   String
  user   User   @relation(fields: [userId], references: [id])
  userId Int
}
```

```
npx @prisma/cli@dev generate
```



<img width="607" alt="CleanShot 2020-11-06 at 16 32 16@2x" src="https://user-images.githubusercontent.com/170299/98384140-b0759a80-204d-11eb-9437-62d7cde5d4db.png">

It shows up when I add the feature flag and re-generate.

**Comment by janpio** [comment]
What version are you testing with @matthewmueller?
