### ISSUE TITLE
Add a check command

### ISSUE THREAD

**Issue by ajotaos** [prisma/prisma#4132]
## Problem

We have validation steps before a commit occurs that everything is ok but now have been a couple of times someone at my team pushes an invalid `.prisma` file either because a syntax.

## Suggested solution

Syntax: `prisma generate --check` validates the syntax of the file and maybe a warning that the schema file is out of sync with the node modules generated client if it's there.

**Comment by pantharshit00** [comment]
You can use `npx prisma validate` 

It is not documented as it is internally used but you can use it here. 

Output is the following:
![image](https://user-images.githubusercontent.com/22195362/97968157-44442e00-1de4-11eb-9eb5-0483848a8abf.png)
