### ISSUE TITLE
How can i run the prisma docs website ?

### ISSUE THREAD

**Issue by sessionboy** [prisma/prisma#4135]
Hi guy!
I can't find the code of prisma docs website.
I want to translate it and want to promote it in China.

**Comment by pantharshit00** [comment]
Hi @sessionboy 

The content of our docs is open source but the code the powers the frontend of docs is not open source. You can find the data of our docs here: https://github.com/prisma/prisma/tree/master/docs

FYI: There is already a Chinese translation of our docs: https://prisma.1wire.com/
