### ISSUE TITLE
Relation 1 to 1 return null in graphQL

### ISSUE THREAD

**Issue by geosigno** [prisma/prisma#4139]
The project was initially developed with Prisma 1. Since we migrated on Prisma 2, this issue has occured.

This is a basic one to one relation that return null in one way.

Below is the prisma schema:

```graphql
model Live {
  id                  String               @id @default(cuid())
  questionnaire       Questionnaire?
}

model Questionnaire {
  id                  String               @id @default(cuid())
  liveId              String
  live                Live                 @relation(fields: [liveId], references: [id])
}

```

Here the resolvers:

```js
const resolver: IResolverObject = {
  id: (node: any) => node.id,
  questionnaire: (node: any, args: any, ctx: Context) => ctx.prisma.live.findOne({ where: { id: node.id } }).questionnaire(),
};

const resolver: IResolverObject = {
  id: (node: any) => node.id,
  live: (node: any, args: any, ctx: Context) => ctx.prisma.questionnaire.findOne({ where: { id: node.id } }).live(),
};
```

And the GraphQL schema:

```graphql
type Questionnaire {
    id: ID!
    live: Live
}

type Live @cacheControl(maxAge: 60) {
    id: ID!
    questionnaire: Questionnaire
}
```

The live query returns the questionnaire ID. But the questionnaire query doesn't return the live ID.

<img width="1086" alt="Capture d’écran 2020-11-03 à 12 07 05" src="https://user-images.githubusercontent.com/6083654/97978448-dd1b7f00-1dcd-11eb-86e5-413bb60bce24.png">
<img width="1115" alt="Capture d’écran 2020-11-03 à 12 07 20" src="https://user-images.githubusercontent.com/6083654/97978450-dee54280-1dcd-11eb-8923-1cd1ce9c9c28.png">

I'm having quite a hard time to figure out what is wrong here. Any clue?

I'm using Prisma 2.7.1.

**Comment by pantharshit00** [comment]
Hey @geosigno 

Sorry for the late reply here. Can you please share a minimal reproduction inside of github repository? 

The provided information above doesn't covey fully how you have laid out your resolvers and also doesn't show your root graphql types so it makes quite hard for me to reproduce this problem.

Also, please try again with the latest version once. New releases contains lot of fixes.

**Comment by geosigno** [comment]
I upgraded to Prisma 2.12.1 and recheck, the issue is still there.

So I reproduce my setup in this [repo]( https://github.com/geosigno/prisma-one-to-one) and this is working... The only difference is that my production DB is a postgresql. Could it be the reason?

> The provided information above doesn't covey fully how you have laid out your resolvers and also doesn't show your root graphql types so it makes quite hard for me to reproduce this problem.

What information would you need?

Any clue on what the issue could be? Can it be the DB that is corrupted after a migration that went bad?

**Comment by geosigno** [comment]
The issue was a resolver not imported... Sorry for this fake issue and thanks for you support.
