### ISSUE TITLE
GraphQL CRUD APIs

### ISSUE THREAD

**Issue by medz** [prisma/prisma#4140]
## Problem

At present, Prisma does not have a great advantage in replacing ORM, and it does not conform to the readme description that can easily build GraphQL APIs. I still use Prisma to build GraphQl APIs and still need to define various Resovers myself. The Typing exported by the Prisma client api component itself can be used in GraphQL, but I am now all writing various Resolvers, which does not reduce the development workload compared to other ORMs.
## Alternatives

In addition to generating Prisma client js, you can add a binder to generate GraphQl DSL

## Additional context

I initially used TypeORM for the development of GraphQL APIs, but I found that it was very complicated for me to query related data or filter data based on relationships. Then I was attracted by Prisma. After construction, Prisma is indeed much more convenient than TypeORM relational queries.

But I found that Typing of Prisma client js is relatively GraphQL-friendly. With NestJS, compared to TypeORM, I can use code first to build GraphQL AST, because TypeORM models and NestJS code first GraphQL AST will be easy to build together. After I switched to Prisma, I needed to write a lot of GraphQL AST by hand, and I could only use NestJS's schame first. In fact, it is not easy for Prisma to build GraphQL APIs. On the contrary, it is very simple to build REST full. Hope to increase the GraphQL AST binder, as simple as generating TypeScript typing. In this way, even if we need to write a large number of Resolvers, the mechanical duplication of definition work such as translating Typing into GraphQL AST is reduced.

**Comment by pantharshit00** [comment]
Checkout nexus and nexus-plugin-prisma. I think that is basically what you are asking for. 

Nexus plugin prisma can expose crud operations from the Prisma schema with a single line: https://nexusjs.org/docs/pluginss/prisma/overview#example


Nexus is a graphql schema building implementation maintained by Prisma and it interops with graphql.js based servers. It is a code first approach which encourages type safety as nexus can generate types for the resolvers automatically.

**Comment by medz** [comment]
@pantharshit00 There is a discussion about binding Nexus in the NestJS Issues. The developers of NestJS think that type-graphql uses decorators to be more concise and friendly. https://github.com/nestjs/graphql/issues/139#issuecomment-473653770

I have used various GraphQL generators, so I agree with the NestJS developers.

In fact, I personally hope that the prisma document can explain how the client generator is developed and embedded in the Prisma CLI. At least this way I can write the Client generator myself to meet the definition of type-graphql.

Forgive me for my weak development ability. After reading the Prisma source code for a night, I didn't find the trick to develop a Client generator. After reading the generated source code of prisma-client-js, I know how to deal with it, but I don't know how to embed it in Prisma CLI.

**Comment by beeman** [comment]
@medz check out [this project](https://github.com/valentinpalkovic/prisma-json-schema-generator), it implements a custom generator. 

In this case it generates JSON schema, but I played around with it and managed to get a bunch of NestJS modules/inputs/models/resolvers generated on each `prisma generate`.

**Comment by pantharshit00** [comment]
Here is another example of a generator: https://github.com/pantharshit00/prisma-docs-generator

Basic docs for generator authoring: https://github.com/prisma/specs/tree/master/sdk/generators

This API is not documented right now in the official docs as it still needs some polishing but you can use it to create any client/other output from the prisma schema.

There is already a typegraphql prisma generator which is maintained by the typegraphql author(It is our collaboration project with them): https://typegraphql.com/docs/1.0.0/prisma.html

I think you should use that if you are typegraphql user.

**Comment by medz** [comment]
@pantharshit00 Thanks，I hope that the client generator function can be released as soon as possible, so that Prisma users can build more binding with other frameworks or tools. 🎉

**Comment by janpio** [comment]
The current implementation of the generator is ready to use while using the existing community generators as inspiration and documentation. We will announce when we open that up as a stable API our community can rely on, until then there might be breaking changes from time to time that need minor adaptations.

**Comment by Jaikant** [comment]
@medz do you have any advise on this, I am looking to integrate prisma with nestjs, with some kind of auto code generation.
