### ISSUE TITLE
Composite keys with optional types generate wrong types

### ISSUE THREAD

**Issue by lstwn** [prisma/prisma#4141]
## Bug description

When using composite (primary) keys on an entity, I expect the generated type to a where clause in e. g. an `upsert()` call to accept the cross product of the types of the fields that compose the stated composite key on that entity. 
With optional (i. e. not-mandatory) fields this is not the case. 

## How to reproduce

1. use the schema below
1. run `yarn prisma generate`
1. use a method of the prisma client api that uses a where clause e. g. `prisma.length.upsert(...)`
1. try to pass the following as an argument to the where part:
```
      fixed_variable_fromInclusive_toExclusive: {
        variable: true,
        // undefined (i. e. omitting fields) instead of null does not help
        fixed: null,
        fromInclusive: null,
        // @ts-ignore does also not help, see below
        toExclusive: null,
      }
```

## Expected behavior

To illustrate this, let's consider the example from below with the schema and the generated type.
A possible primary key to a tuple of the entity `Length` could be:
```
variable: true
fixed: null
fromInclusive: null
toExclusive: null
```
or `undefined` instead of `null`, whatever.
This should be a totally valid thing to exist according to the schema definition because of the fields being optional as denoted by the `?`.

However, the generated type does not allow for any of the fields (`variable`, `fixed`, `fromInclusive`, `toExclusive`) to be null or undefined.

Unfortunately, it is not only a problem with the generated type. When disabling typescript checking for that where argument, an error is thrown at runtime instead.

---

*In a nutshell*: The where clause of an entity that has a composite key defined should accept the cross product of the individual types of the fields composing the key, including null, as its key space. In this case, instead of:
```
Boolean X Int X Int X Int
```
it should be:
```
(Boolean | null) X (Int | null) X (Int | null) X (Int | null)

```

| Field | `variable` | `fixed` | `fromInclusive` | `toExclusive` |
|--------|--------------|----------|---------------------|-------------------|
| _is_ | `Boolean` | `Int` | `Int` | `Int` |
| _should be_ | `(Boolean \| null)` | `(Int \| null)` | `(Int \| null)`| `(Int \| null)` |

## Prisma information

Schema: 
```prisma
model Length {
  id            String       @id @default(cuid())
  variable      Boolean?
  fixed         Int?
  fromInclusive Int?
  toExclusive   Int?

  @@unique([fixed, variable, fromInclusive, toExclusive])
}
```
This generates (roughly) the following where type:
```ts
type LengthWhereUniqueInput = {
  id?: string;
  fixed_variable_fromInclusive_toExclusive?: {
    variable: boolean;
    fixed: number;
    fromInclusive: number;
    toExclusive: number;
}
```

## Environment & setup

- OS:  Ubuntu 20.10
- Database:  PostgreSQL
- Node.js version:  v12.18.2
- Prisma version:

```
@prisma/cli          : 2.10.1
@prisma/client       : 2.10.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 7d0087eadc7265e12d4b8d8c3516b02c4c965111 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 7d0087eadc7265e12d4b8d8c3516b02c4c965111 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 7d0087eadc7265e12d4b8d8c3516b02c4c965111 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 7d0087eadc7265e12d4b8d8c3516b02c4c965111 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.304.0
```

**Comment by pantharshit00** [comment]
Hey @lstwn 

Thanks for this well written report. I really appreciate you took the time here :) 


But this is a known problem and a duplicate issues already exists for this with some discussion: https://github.com/prisma/prisma/issues/3197

So I will close this one as a duplicate. Still thanks again!
