### ISSUE TITLE
Field for relation is returning null using Mongo Connector

### ISSUE THREAD

**Issue by ezeikel** [prisma/prisma#4143]
**Describe the bug**
I am using MongoDB with Prisma. I have two types `Post` and `User` and I just want to model the relationship between the two types so that one `User` can have many `Post` and a `Post` can only have one `User`. I create these types and when trying to query aUser's Posts I get back `null`.

**To Reproduce**
My datamodel looks like this:

```
enum Permission {
  ADMIN
  USER
  PERMISSIONUPDATE
}

type User {
  id: ID! @id
  firstName: String!
  lastName: String!
  username: String @unique
  email: String! @unique
  password: String!
  posts: [Post!]! @relation(link: INLINE)
  following: [User!]! @relation(name: "Following", link: INLINE)
  followers: [User!]! @relation(name: "Followers", link: INLINE)
  resetToken: String
  resetTokenExpiry: String
  permissions: [Permission!]!
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
}

type Post {
  id: ID! @id
  caption: String
  image: String
  largeImage: String
  published: Boolean @default(value: false)
  author: User!
  comments: [Comment!]!
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
}

type Comment @embedded {
  text: String!
  writtenBy: User!
}
```

I have a `createPost` resolver to create a new `Post` that looks like this:

```
  createPost(_, args, ctx, info) {
    if (!ctx.request.userId) {
      throw new Error('You must be logged in to do that!');
    }

    return ctx.prisma.createPost({
      author: {
        connect: {
          id: ctx.request.userId
        }
      },
      ...args
    });
  }
```

Which just checks someone is currently logged in and creates a `Post` with the logged in user being the `author`

I can see in Mongo Compass that everything is being created as expected.

Post Collection:
<img width="644" alt="screenshot 2019-03-07 at 10 03 42" src="https://user-images.githubusercontent.com/2964757/53950011-211f2380-40c3-11e9-8c09-cb968cfb5f32.png">

User Collection:
<img width="563" alt="screenshot 2019-03-07 at 10 03 51" src="https://user-images.githubusercontent.com/2964757/53950021-267c6e00-40c3-11e9-8abb-a825b5572eda.png">

However I get the error `Cannot return null for non-nullable field User.posts.` when using this query:

```
{
  users {
    firstName
    posts {
      id
    }
  }
}
```

**Expected behaviour**
What I expect to get is the `User` data plus the `Post` data from the query

**Versions**
`prisma-client-lib/1.27.3`
`prisma CLI/1.26.4`

**Comment by jayarnielsen** [comment]
I'm experiencing the same issue with a similar setup. Interestingly enough, if I refactor to use relations instead of embed, everything works as expected. Would really like to be able to use the embed feature of mongo, though.

**Comment by do4gr** [comment]
I'll look into the issue @ezeikel. 

@jayarnielsen , could you please open a separate issue and describe your issue in detail? The issue here does not seem to be related to embedded types and I think your's might be a separate one that I would need more information on.

**Comment by jentzheng** [comment]
I think I'm not alone

`Mongo Connector`
`prisma/1.28.5 (darwin-x64) node-v8.11.4`
`prisma-client-lib: 1.28.5`

```
# Data Model
type Post {
  id: ID! @id
  user: User! @relation(name: "PostsByUser")
  whatEverType1: WhateverType1
  whatEverType2: WhateverType2
  comments: [Comment!]
  ...restAttrs
}

type WhateverType1 @embedded {  ...attrs }
type WhateverType2 @embedded { ...attrs }
type Comment @embedded { ...attrs }
```

```
# All data persisted in DB 
# In the playground, all embedded fields display null

query {
  evaluation(where{id: "..."}) {
    ...attrs
    user{...attrs}
    
    # Fields below are all display as null... 
    whatEverType1{...attrs}
    whatEverType2{...attrs}
    comments{...attrs}
  }
}

```

**Comment by jentzheng** [comment]
> I think I'm not alone
> 
> `Mongo Connector`
> `prisma/1.28.5 (darwin-x64) node-v8.11.4`
> `prisma-client-lib: 1.28.5`
> 
> ```
> # Data Model
> type Post {
>   id: ID! @id
>   user: User! @relation(name: "PostsByUser")
>   whatEverType1: WhateverType1
>   whatEverType2: WhateverType2
>   comments: [Comment!]
>   ...restAttrs
> }
> 
> type WhateverType1 @embedded {  ...attrs }
> type WhateverType2 @embedded { ...attrs }
> type Comment @embedded { ...attrs }
> ```
> ```
> # All data persisted in DB 
> # In the playground, all embedded fields display null
> 
> query {
>   evaluation(where{id: "..."}) {
>     ...attrs
>     user{...attrs}
>     
>     # Fields below are all display as null... 
>     whatEverType1{...attrs}
>     whatEverType2{...attrs}
>     comments{...attrs}
>   }
> }
> ```

I manually changed the embedded option from `false` to `true` in the generated file, then it works...

**Comment by divyenduz** [comment]
@ezeikel @jayarnielsen @jentzheng Can you please share your `prisma.yml` file as well? How did you obtain that file (using which workflow?) 

Are you using the [`databaseType: document` property](https://www.prisma.io/docs/prisma-cli-and-configuration/prisma-yml-5cy7/#root-properties) in `prisma.yml`. If no, can you please add it and try again to confirm if the generated client is correctly generated? 

To me, it looks like a bug in a codepath that generates `prisma.yml` file for MongoDB.

**Comment by jentzheng** [comment]
> Are you using the [`databaseType: document` property](https://www.prisma.io/docs/prisma-cli-and-configuration/prisma-yml-5cy7/#root-properties) in `prisma.yml`.

Thank you @divyenduz , I was not using `databaseType: document` property in `prisma.yml`. Now, the   generated client is with `embedded: true` and the data result is corrected as I expected.

**Comment by divyenduz** [comment]
@jentzheng Thanks, did you hand write the `prisma.yml` file from some docs or did some workflow generate it for you? Maybe that part of the workflow can be improved?

**Comment by jayarnielsen** [comment]
@divyenduz I ended up refactoring mine to be relational since I couldn't get the embedded type to work. But I didn't have the `databaseType: document` property in my prisma.yml file, so that was most likely the culprit. I think I copied my config from an example somewhere 😬

**Comment by ezeikel** [comment]
I fixed this by adding a field resolver for `posts` on `User`

```
const { GraphQLServer } = require('graphql-yoga');
const Mutation = require('./resolvers/Mutation');
const Query = require('./resolvers/Query');
const { prisma } = require('./generated/prisma-client');

// Create the GraphQL Yoga Server
function createServer() {
  return new GraphQLServer({
    typeDefs: 'src/schema.graphql',
    resolvers: {
      Mutation,
      Query,
      User: {
        posts: parent => prisma.user({ id: parent.id }).posts(),
      }
    },
    resolverValidationOptions: {
      requireResolversForResolveType: false
    },
    context: req => ({ ...req, prisma})
  });
}

module.exports = createServer;
```

**Comment by anthonymetzler** [comment]
I just wanted to second that embedded types aren't working with the Mongo connector. Running Prisma 1.28.5 with the 
I'm getting an error coming back like:
`
"Variable '$data' expected value of type 'LocationCreateInput!' but got: {\"name\":\"adadaaaaa\",\"description\":\"Test 123\",\"owner\":{\"type\":\"USER\",\"ownerId\":\"5c9293a21169c40007692ead\"}}. Reason: 'owner.type' Field 'type' is not defined in the input type 'OwnerCreateOneInput'. (line 1, column 11):\nmutation ($data: LocationCreateInput!) {\n          ^"
`

Prisma.yml file is:
`
endpoint: http://0.0.0.0:4466
datamodel: datamodel.prisma
databaseType: document
generate:
  - generator: javascript-client
    output: ./generated/prisma-client/
hooks:
  post-deploy:
    - prisma generate
`

**Comment by divyenduz** [comment]
@anthonymetzler : Your error looks different than this issue, can you please create a new issue [here](https://github.com/prisma/prisma/issues/new?template=bug_report.md) with a minimal reproduction?
