### ISSUE TITLE
Connected fields do not get an updated by @updatedAt

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#4146]
## Bug description

Consider the following query:
```typescript
await app.prisma.account.create({
    data: {
      name,
      tokens: {
        connect: tokens.map(t => ({ id: t.id })),
      },
    },
  })
```

with the following schema:
```prisma
model Account {
  id         String         @id @default(cuid())
  tokens     Token[]
  updatedAt  DateTime       @updatedAt
}

model Token {
  account      Account? @relation(fields: [accountId], references: [id])
  accountId    String?
  id           String   @id @default(cuid())
  updatedAt    DateTime @updatedAt
}

```

One would expect that the `updatedAt` of the `Token` model would get updated on connect, but it is not the case. The following SQL is executed:
```sql
 UPDATE "public"."Token" SET "accountId" = $1 WHERE "public"."Token"."id" IN ($2,$3)
```

**Comment by pantharshit00** [comment]
I can confirm the behavior. We should fix this as write does happen on the token table.

**Comment by yoshuawuyts** [comment]
This has been resolved in https://github.com/prisma/prisma-engines/pull/1465 and should be part of our next release -- thanks again for reporting @Sytten!
