### ISSUE TITLE
Inverted behavior of GraphQLSchemaAssertions.mustNotContainField

### ISSUE THREAD

**Issue by alban-auzeill** [prisma/prisma#4147]
**Describe the bug**
Looking a the code of GraphQLSchemaAssertions class, the following two methods have the same implementation:
* [mustContainField(typeDef: String, field: String)](https://github.com/prisma/prisma/blob/b27a68d7945aecb891067b88978f2aa0b62831e9/server/servers/api/src/test/scala/com/prisma/util/GraphQLSchemaAssertions.scala#L19)

* [mustNotContainField(typeDef: String, field: String)](https://github.com/prisma/prisma/blob/b27a68d7945aecb891067b88978f2aa0b62831e9/server/servers/api/src/test/scala/com/prisma/util/GraphQLSchemaAssertions.scala#L29)

And it's `mustNotContainField` that has the wrong implemtation.

**Versions:**
 - 1.28.1

**Additional context**
We, developer of SonarScala, use your source code to validate our work :)

**Comment by do4gr** [comment]
Looks like you found some dead code that is not called anymore. We'll clean it up. Thanks for letting us now ;-)
