### ISSUE TITLE
Create codemod for namespace change

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#4150]
The changes related to https://github.com/prisma/prisma/issues/3223 will introduce a breaking change. We want to create a codemod for users to be able to transition their  code.

**Comment by matthewmueller** [comment]
Final result: npx command. Depends on #3223.

**Comment by matthewmueller** [comment]
From @timsuchanek:

> Just go into the project you want to upgrade and execute `npx @prisma/codemods namespace ./src`, where `src` is the directory that has your code.

**Comment by williamluke4** [comment]
https://github.com/prisma/codemods
