### ISSUE TITLE
Relational data lazy loading Keys duplication

### ISSUE THREAD

**Issue by medz** [prisma/prisma#4152]
My code:
```js
const prisma new PrismaClient();

prisma.posts.findMany({ take: 15 }).then(posts => {
    posts.forEach(post => {
        const publisher = prisma.user.findOne({ where: { id: post } });
       /// My more codes...
    });
})
```

SQL: 
```sql
SELECT "public"."User"."*" FROM "public"."User" WHERE "public"."User"."id" IN ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) OFFSET $16

/// Query Params: ["487267d9-305f-4cad-ac6e-8dc887c19ec3","487267d9-305f-4cad-ac6e-8dc887c19ec3","606d5a48-7e72-4b48-9ea3-70925c92d622","487267d9-305f-4cad-ac6e-8dc887c19ec3","487267d9-305f-4cad-ac6e-8dc887c19ec3","487267d9-305f-4cad-ac6e-8dc887c19ec3","8f9a6873-e060-4911-8466-6a3d1a828342","606d5a48-7e72-4b48-9ea3-70925c92d622","487267d9-305f-4cad-ac6e-8dc887c19ec3","487267d9-305f-4cad-ac6e-8dc887c19ec3","487267d9-305f-4cad-ac6e-8dc887c19ec3","8f9a6873-e060-4911-8466-6a3d1a828342","8f9a6873-e060-4911-8466-6a3d1a828342","487267d9-305f-4cad-ac6e-8dc887c19ec3","487267d9-305f-4cad-ac6e-8dc887c19ec3",0]
```
The reason why I need to load the relationship separately asynchronously is GraphQL's Resolver, because GraphQL can't use include for loading like REST. Need to use Resolver for independent loading.

I was going to use DataLoader to solve the problem of too many query statements, and suddenly discovered that Prisma's Promise find automatically merges queries. So I listened to the SQL of the query to see if it was what I thought, and the result was just as I expected.

Prisma has done what I originally wanted to use DataLoader to accomplish, but I found another problem, the delayed loading of the SQL passed into the database has duplicate data.

For example, as imagined above, the last 15 Posts were posted by 3 users, then Lasy find should use IN [ID_1, ID_2, ID_3], but Prisma does not seem to be duplicated. IN 15 IDs, many of which are duplicates Yes, only three IDs will remain after deduplication

**Comment by pantharshit00** [comment]
@medz Yes, only dataloader part is implemented right now for related findOne calls. There is no deduping implemented right now.

Issue for deduping: https://github.com/prisma/prisma/issues/3635

Past dataloader discussions: https://github.com/prisma/specs/issues/242#issuecomment-549338712 (comment related to deduping), https://github.com/prisma/prisma/issues/1470

**Comment by pantharshit00** [comment]
I will actually close this a duplicate. Post your comment in #3635 and leave a +1 there if you want to get this prioritized.
