### ISSUE TITLE
Implicit relation tables always have `onDelete CASCADE`, this should be configurable.

### ISSUE THREAD

**Issue by tomitrescak** [prisma/prisma#4166]
Hi, currently you set the onDelete behaviour of generated associate tables in M:N relationships to CASCADE, e.g.:

```sql
CREATE TABLE "public"."_UserRoles" (
    "A" text NOT NULL,
    "B" text NOT NULL,
    CONSTRAINT "_UserRoles_A_fkey" FOREIGN KEY ("A") REFERENCES "public"."Role"("id") ON DELETE CASCADE,
    CONSTRAINT "_UserRoles_B_fkey" FOREIGN KEY ("B") REFERENCES "public"."User"("id") ON DELETE CASCADE
);
```

It would be great if we could configure it. I have a situation, when I would like to prohibit deletions of a Role if there exists an association to it through UserRole.

**Comment by tomhoule** [comment]
Transferring this to prisma/prisma for consideration by the product team.

**Comment by Jolg42** [comment]
Related https://github.com/prisma/prisma/issues/4711

**Comment by pimeys** [comment]
You can configure this from the next version of Prisma (2.26.0). PR merged today in https://github.com/prisma/prisma-engines/pull/1947

Please read the proposal in https://github.com/prisma/prisma/issues/6996

**Comment by janpio** [comment]
This has now been released as a preview feature behind a preview feature flag. You can read about it in the release notes for 2.26.0: https://github.com/prisma/prisma/releases/tag/2.26.0 If you have any feedback, please use this issue: https://github.com/prisma/prisma/issues/7816
