### ISSUE TITLE
PSL: define the grammar of string literals

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#4167]
This is mostly an issue in `@default("some string here")` directives.

At the moment, escaping has an effect on _parsing_, but not on migrations, nor on what gets inserted by the query engine. The default string the query engine will insert is exactly what is inside the quotes in the schema, including the backslashes used for escaping.

## Illustration

Given the following schema:

```prisma
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id         Int    @id
  name       String @default("Jean Claude")
  secondName String @default("Jean \" \n Claude")
}
```

if you create one user with just the id, leaving the fields with defaults to be inserted by prisma, the response will be (I tested this, on both postgres and sqlite):

```json
{
  "data": {
    "createOneUser": {
      "id": 6,
      "name": "Jean Claude",
      "secondName": "Jean \\\" \\n Claude"
    }
  }
}
```

## Proposed solution

Similar to most languages and formats with string literals (e.g. JSON), define `\` as an escaping character that will be removed from the string during parsing.

Some languages allow a `\` before any character, some ([like JSON](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf)) only as the first token of a recognized escape sequence.

Regarding escape sequences: some string literals cannot be expressed as literals within the current schema parser. The most common example is probably strings containing a newline. Therefore common escape sequences, like `\n`, could be a worthwhile addition. Same goes for a "bare" double quote.

## Related issues

https://github.com/prisma/prisma/issues/1888

**Comment by tomhoule** [comment]
Moving this issue to prisma/prisma since it is about the Prisma Schema Language. This is not critical for the migration engine at the moment, but it would be nice to have a grammar.

**Comment by matthewmueller** [comment]
Non-official grammar, but probably a good starting point:

https://github.com/prisma/prismafile/blob/master/src/parser/index.pegjs

Currently it drives the prisma-upgrade tool.

**Comment by tomhoule** [comment]
Relevant: https://github.com/prisma/prisma-engines/pull/1973

**Comment by Ultra-Instinct-05** [comment]
Is this unofficial grammar present anywhere for viewing ? Right now, https://github.com/prisma/prismafile/blob/master/src/parser/index.pegjs leads to a 404 (which probably means the repo doesn't exist or is private)

**Comment by Ultra-Instinct-05** [comment]
> Is this unofficial grammar present anywhere for viewing ? Right now, https://github.com/prisma/prismafile/blob/master/src/parser/index.pegjs leads to a 404 (which probably means the repo doesn't exist or is private)

@tomhoule Sorry for the ping but anything on this ? Is the PSL grammar file available for others to view ?

**Comment by tomhoule** [comment]
Hi @Ultra-Instinct-05 , sorry I missed your previous comment.

The grammar used inside Prisma is https://github.com/prisma/prisma-engines/blob/main/libs/datamodel/schema-ast/src/parser/datamodel.pest — note however that we apply a bunch of validations on top, so this file defines a grammar that is more permissive than what we actually allow (for example: trailing commas in attributes). Notably, the new grammar for string literals is meant to be an exact implementation of the grammar for string literals from the JSON spec (https://datatracker.ietf.org/doc/html/rfc8259).

**Comment by tomhoule** [comment]
There is no spec-style well defined grammar beyond what the implementation defines, but if this something you would like to have, the best course of action would be to open an issue so we can track interest into that and make prioritization decisions.

**Comment by Ultra-Instinct-05** [comment]
@tomhoule I maintain a Sublime Text package to highlight schema files https://github.com/Sublime-Instincts/PrismaHighlight. It would be nice if there was documentation on the official grammar, so that the package highlights stuff correctly. Right now it works, but I just looked at various example schema files to make the package.

I am pretty sure even VS Code can take advantage of it 🙂
