### ISSUE TITLE
docs missing server-side subscriptions & Prisma GraphQL API

### ISSUE THREAD

**Issue by alexbudure** [prisma/prisma#4176]
The Prisma GraphQL API page has a link on the homepage, but it doesn't take you anywhere. Even though the Prisma client is well documented, I still found that page to be very helpful.

The server-side subscriptions page has been missing for a while, is this something you guys are trying to remove from Prisma?

 I get "Page Not Found" whenever I try to visit an older version of the docs for this info.

**Comment by nikolasburk** [comment]
Hey @alexbudure, thanks a lot for opening this issue. We have indeed consciously removed the GraphQL API docs, you can find the reasoning for why we did that in [this](https://www.prisma.io/blog/prisma-and-graphql-mfl5y2r7t49c/) blog post.

If you need access to the docs, you can still find them in the docs for the older versions of Prisma (< [1.27](https://www.prisma.io/docs/1.27/prisma-graphql-api/)).
