### ISSUE TITLE
CONTRIBUTING.md missing YARN dependency

### ISSUE THREAD

**Issue by muxahuk** [prisma/prisma#4179]
## Bug description

When i was copying repo to contribute i encountered that in order to build "client" package i had to install YARN globally, although in the CONTRIBUTING.md it is not mentioned.
Here's the usage place that was failing for me before i installed YARN:
https://github.com/prisma/prisma/blob/284891a1d04a1d98f358b5cd141c79c0106ed0c3/src/packages/sdk/src/getPackedPackage.ts#L48

## How to reproduce

1. Consider clean npm install (no yarn is installed)
2. Follow CONTRIBUTING.md guide for "client"

## Expected behavior

1) YARN is mentioned in CONTRIBUTING.md
or
2) YARN is not mentioned in CONTRIBUTING.md, but then "client" should be able to build and i can contribute without having YARN

## Environment & setup

- OS: Ubuntu 20.04.1 LTS
- Node.js version: v15.1.0
- NPM version: 7.0.9
- Prisma version: git master branch

**Comment by Jolg42** [comment]
Nice catch! Thanks for reporting it 😃

**Comment by muxahuk** [comment]
@Jolg42 bdw. i haven't found any minimal requirements in the docs. To know what is the minimal node version that prisma supports. in tthe client and cli packages in package.json they mention >=10 node version. But when i installed 10.0.0 pnpm said it cannot be installed and requires minimum 10.13.0 to use it..

What is the official minimal node and npm supported version? should it be mentioned somewhere in the docs? or if i'm blind can u please link to the requirements?:)

**Comment by Jolg42** [comment]
@muxahuk So in the docs it's indeed mentioned sometimes but not always that Node.js 10 minimum is required, [this issue tracks the progress of making it clearer.](https://github.com/prisma/docs/issues/913)

I am not aware of any error mentioning version `10.13.0` minimum, could you paste the error you encountered? It will be good to clarify what is the minimum version, it's possible that a recent feature we shipped requires a certain version of Node 10 🤔)

Recommended versions that are 100% confirmed to work are latest v12 or v14 (latest v10 works too but it is [only in maintenance for a few more months](https://nodejs.org/en/about/releases/) so better to go with 12 minimum.)

**Comment by Jolg42** [comment]
I think this is the error you encountered https://github.com/pnpm/pnpm/blob/86d21759da65326d24f77815a1af25be40e6013e/packages/pnpm/bin/pnpm.js#L5

So indeed to install the latest pnpm version you would need Node `10.13.0` locally.

**Comment by muxahuk** [comment]
> I think this is the error you encountered https://github.com/pnpm/pnpm/blob/86d21759da65326d24f77815a1af25be40e6013e/packages/pnpm/bin/pnpm.js#L5

yep, that's the error.

After i done changes for the related MR i realized that fs.promises might not be supported in older versions of node and was trying to find minimal requirements. After installing node v10 - got error from pnpm and installed 10.13. So i changed the MR to use more common approach for node v10 - promisify..

Thanks for clarifying and adding references.
