### ISSUE TITLE
Prisma2 blocks prisma generate on unsupported platforms, even when providing custom binaries

### ISSUE THREAD

**Issue by BaptisteLongy** [prisma/prisma#4205]
This bug report is following this [conversation bit](https://github.com/prisma/prisma/issues/861#issuecomment-723810121):
> Hello there,
> 
> I'm encountering the issue described [here](https://github.com/prisma/prisma/issues/1505#issuecomment-633802109).
> 
> I understand that you are not going to officially support arm platforms yourselves and that [you just give instructions on how we can do it ourselves](https://github.com/prisma/prisma/issues/861#issuecomment-690574582).
> 
> However it seems you are blocking (probably not on purpose) any execution on non supported platforms and the workaround is to [simply add the name of the platform to a list (or 2)](https://github.com/prisma/prisma/issues/1505#issuecomment-634154657).
> 
> Could you lift that restriction when using custom binaries so we don't have to fork the entire prisma in this situation?
> 
> If needed, I can create a new issue to track this, just tell me 😃

## Bug description

Prisma2 restricts the type of platform it can be used on based on an hardcoded list, preventing the users to even try by raising an error when using `npx prisma generate`:
 ```
 Environment variables loaded from ./prisma/.env
 Warning Precompiled binaries are not available for ARM.
 Warning Precompiled binaries are not available for ARM.
 Error: Unknown binaryTargets arm-openssl-1.1.x
 ```

## How to reproduce

1. Get an unsupported platform (I'm using a raspberry pi - which is an arm platform)
2. Generate binaries for that platform following [prisma instructions](https://github.com/prisma/prisma-engines#building-prisma-engines)
3. Inject those custom binaries inside any prisma project on the said platform following [prisma instructions](https://www.prisma.io/docs/understand-prisma/under-the-hood#using-custom-engine-binaries)
4. Run `npx prisma generate`
5. See the error

## Expected behavior

[From this comment](https://github.com/prisma/prisma/issues/1505#issuecomment-634154657), it appears the blocking is purely based on a list of hardcoded predefined supported platforms.
I see 2 possible behaviours:

- Give the users a way to bypass the check on the architecture being in the list of supported ones (it will become the responsability of the user to know what he is doing) - [@janpio mentionned env var for instance](https://github.com/prisma/prisma/issues/861#issuecomment-724014072) - I don't have any insightful advice on the better method
- Bypass the check altogether as long as the user is providing his onw binaries - if this check is only useful for downloading bianries from prisma repo, and the user is already providing his own, then it is not necessary

I haven't researched into the code to know if the second option is viable.

## Prisma information

Kinda irrelevant here, but you can always have a look at [my own project](https://github.com/BaptisteLongy/shopping-list-v2)...

## Environment & setup

- OS: Raspbian GNU/Linux 10 (buster)
- Database: SQLite
- Node.js version: v14.15.0
- Prisma version:
```
Environment variables loaded from /home/pi/docker-builders/shopping-list-v2/prisma/.env
Warning Precompiled binaries are not available for arm.
@prisma/cli          : 2.10.2
@prisma/client       : 2.10.2
Current platform     : arm-openssl-1.1.x
Query Engine         : query-engine 3cc43e8ee3c92ab17f192e5874968b2b86dd6740 (at ../prisma-engines/target/release/query-engine, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : migration-engine-cli 3cc43e8ee3c92ab17f192e5874968b2b86dd6740 (at ../prisma-engines/target/release/migration-engine, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine : introspection-core 3cc43e8ee3c92ab17f192e5874968b2b86dd6740 (at ../prisma-engines/target/release/introspection-engine, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary        : prisma-fmt 3cc43e8ee3c92ab17f192e5874968b2b86dd6740 (at ../prisma-engines/target/release/prisma-fmt, resolved by PRISMA_FMT_BINARY)
Studio               : 0.304.0
```

**Comment by williamluke4** [comment]
@BaptisteLongy Am I correct in saying that you have set a binary target in your `schema.prisma`. If you have could you try to remove it and try run generate again with the custom env vars set?
