### ISSUE TITLE
documentation about prisma.node ?

### ISSUE THREAD

**Issue by tanekim77** [prisma/prisma#4205]
Please provide your feedback here instead: https://github.com/prisma/prisma-content-feedback/issues/new?template=documentation-feedback.md.

When I see inside the method for prisma object, I see it has node method, that takes id as an argument. What does prisma.node({id:'??'}) does? Why it's there and how do I find which id to use? Thanks!

**Comment by pantharshit00** [comment]
Hi @tanekim77 

This node method is not super helpful. Basically using inline fragment and a node id(node can be any type) you can query the type.

Example:

```graphql
{
  node(id:"someid"){
   ... on User{
        id 
        name
   }
}
```

**Comment by pantharshit00** [comment]
Hi @tanekim77 

This node method is not super helpful. Basically using inline fragment and a node id(node can be any type) you can query the type.

Example:

```graphql
{
  node(id:"someid"){
   ... on User{
        id 
        name
   }
}
```
