### ISSUE TITLE
Preview feature feedback: `uncheckedScalarInputs`

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4209]
Please share your feedback about the preview feature `uncheckedScalarInputs ` that was released in [v2.11.0](https://github.com/prisma/prisma/releases/tag/2.11.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo. 
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma2`](https://app.slack.com/client/T0MQBS8JG/CKQTGR6T0) channel in the [Prisma Slack](https://slack.prisma.io).

### Set foreign keys directly with uncheckedScalarInputs (Preview)

We now support writing foreign keys (also known as [relation scalars](https://www.prisma.io/docs/concepts/components/prisma-schema/relations#annotated-relation-fields-and-relation-scalar-fields)) directly with the `uncheckedScalarInputs` preview feature.

Consider this sample Prisma schema:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["uncheckedScalarInputs"]
}

model User {
  id    Int    @id @default(autoincrement())
  posts Post[]
}

model Post {
  id       Int  @id @default(autoincrement())
  authorId Int
  author   User @relation(fields: [authorId], references: [id])
}
```

Instead of using `connect` when creating a new `Post` record to wire up a relation with a `User` record, you can now directly set the `authorId` value:

```ts
await prisma.post.create({
  data: {
    // You can now set the foreign key directly...
    authorId: 1,
    // ... or connect the relationship...
    // author: {
    //   connect: {
    //     id: 1
    //   }
    // }
    // ... but not both at the same time
  },
});
```

**Comment by matthewmueller** [comment]
This is stable now

**Comment by afonsomatos** [comment]
If I use a connect or create, I can't use a relation id, why is that?
