### ISSUE TITLE
GraphQL endpoint generated invalid schema: Type Query must define one or more fields.

### ISSUE THREAD

**Issue by jordyvandomselaar** [prisma/prisma#4209]
I keep getting this error out of nowhere without altering the datamodel at all when running `./node_modules/.bin/graphql get-schema -p prisma --dotenv "../.env"` I don't know any reproduction steps because it just randomly appeared. I've tried checking out earlier commits in my project and that doesn't solve it.

Prisma image version: prismagraphql/prisma:1.26.6

**Comment by pantharshit00** [comment]
Hi @jordyvandomselaar 

Without a reproduction, it would be very hard for us to identify the problem and fix it. 

btw you don't need graphql-cli to generate the schema. Prisma cli can do that as well using `graphql-schema` generator. See https://www.prisma.io/docs/prisma-cli-and-configuration/cli-command-reference/prisma-generate-xcv2/#prisma-generate

**Comment by jordyvandomselaar** [comment]
Hey @pantharshit00,

> Without a reproduction, it would be very hard for us to identify the problem and fix it.

I totally get it and was wondering if I should create this issue, it was more of a _pray someone else has had it and knows what's up_ thing 😅️

> btw you don't need graphql-cli to generate the schema.

If all else fails I'll give that a shot. Thanks!

**Comment by jordyvandomselaar** [comment]
I'll close this issue as it's resolved 🎉 

I downgraded my Prisma container from `prismagraphql/prisma:1.26.6` to `prismagraphql/prisma:1.25.7` and boom, it's working.
