### ISSUE TITLE
Format multiples schema files with prisma format

### ISSUE THREAD

**Issue by ajotaos** [prisma/prisma#4212]
## Problem

I'm using lint-staged to for format files based on their extension as part of a pre-commit hook. So I wanted to include the schemas as part of this hook. The staged files' paths are passed to the end of the command, in my case I'm using `prisma format --schema`.

My company repo has multiple schema files so we just noticed that when changing two of them, only the first one passed is formatted.

## Suggested solution

Allow multiple schema files to be passed as part of the format command's schema argument, `prisma format --schema menus.prisma vendors.prisma users.prisma`.

## Alternatives

* [A prisma prettier plugin to format through `prettier`](https://github.com/prisma/prisma/issues/1761)
* A .sh script that takes all path arguments and runs `prisma format --schema $[path}` on each of them.

**Comment by codeninja** [comment]
You could simply glob together the schema's and pipe the results to `prisma format` on the command line if you're fragmenting your schema files.

```
yarn prisma format --schema $(find ./libs/data-access/prisma/src -name '*.prisma' | xargs)
```

**Comment by janpio** [comment]
`prisma format` is meant to be used with one schema file (and in the future possibly multiple schema files that form one overall schema file when combined). 

When you want to run it for multiple Prisma schemas, the best way is indeed to use the command multiple times, or write a wrapper script that does so. @shian15810 's suggestion also looks like a good, lint-staged specific, way to achieve this.
