### ISSUE TITLE
Test Azure SQL on macOS

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4238]
The Azure SQL (which is SQL Server 2017 underneath) needs to be tested with a computer running macOS. Since Catalina, Apple has been really picky about [what kind of TLS certificates they accept](https://support.apple.com/en-ca/HT210176).

This means, that any of the following points will cause a TLS error when connecting to the server:

- RSA keys < 2048 bits
- SHA-1 signatures
- DNS Names in certificates

Microsoft has [an article](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15#certificate-requirements) about certificate requirements, and another on [SHA-1 deprecation](http://download.microsoft.com/download/4/5/8/458E1F8C-7A36-4285-8EB2-42E6858D06C1/Microsoft_SHA-1_Guidance_E.pdf).

What needs to be done here is to launch an Azure SQL server, run macOS Catalina and try to see how hard it is to set the TLS requirements so we can connect to the machine. This might also need to be addressed by the documentation team later on.

**Comment by divyenduz** [comment]
Tried a custom certificate that matches the macOS requirements with provider added to the keychain, that didn't work. 

I validate that the certificate is indeed valid for macOS according to https://support.apple.com/en-ca/HT210176

**Comment by Jolg42** [comment]
e2e runs for ubuntu
and macOS: see https://github.com/prisma/e2e-tests/blob/dev/.github/workflows/test.yaml#L570-L578
