### ISSUE TITLE
OneToMany relation working on Prisma Database, but not on server! 😱

### ISSUE THREAD

**Issue by KumarAbhirup** [prisma/prisma#4241]
**NEWBIE ALERT**, I might sound silly and I don't really know if this issue should really exist here or not. Would love your kind suggessions. 😅

In the mutation to create posts, I am using this code:
```js
async function savePost(parent, args, context, info){

  let data = {...args}
  delete data.categories
  delete data.status

  if (!context.request.userId) {
    throw new Error('Please SignIn to continue.')
  }

  const post = await context.prisma.createPost({
    author: {
      connect: { id: context.request.userId }
    },
    categories: {
      set: args.categories,
    },
    status: args.status,
    ...data
  })

  return post

}
```

This connects the post to the author in the database. I got to know this by using Database Playground.

However, when I `console.log` the `postToUpdate`, it returns `author: null`!
When I use `gql` on the client side, the same thing happens. The post does not have an author!

Though the author got saved in the database, I don’t see him/her on client and server side.

Desperate for help. Been debugging this since a day or two!

**Comment by pantharshit00** [comment]
See : https://www.prisma.io/forum/t/onetomany-relation-working-on-prisma-database-but-not-on-server/6453/3?u=pantharshit00

Basically I think you have not implemented type resolvers, that is it is returning null for the author.

**Comment by KumarAbhirup** [comment]
Sorry bro 😅 newbie here. I didn't get the point of that article.
What do you mean by "not implementing a type resolver"?

sorry again, if I sound silly 🎄

**Comment by pantharshit00** [comment]
@KumarAbhirup

I will recommend you to read this article on how graphql resolver works. https://blog.apollographql.com/graphql-explained-5844742f195e

Basically, every field on every type in graphql is backed to a resolver. That resolver is responsible for resolving the type and passing to resolve data to the next type resolver via the parent argument.

So in prisma, for example, to resolve the author in every post, you will need to do something like this:

Given schema
```graphql
type Post{
  id: ID!
  title: String!
  author: User!
}

type User{
 id: ID!
 name: String!
}

type Query{
  allPosts: [Post!]
```

Assuming we have access to prisma via the context:
```js
const resolvers = {
  Query:{
    allPosts: (parent, args, ctx, info) => {
         return ctx.prisma.posts();
     }
  },
  Post: {
    author: (parent, args, ctx, info) => {
      return ctx.prisma.post({ id: parent.id }).author();
     }
   }
}
```


So, when trying to query allPosts and including the author in the selection set like so:
```graphql
{
  allPosts{
   id
   title
   author{
    id
   }
}
```

It will in a recursive fashion run the allPosts resolver which is a field of the Query type. When it's execution is finished, it will run the author resolver of the post type for each post resolved(remember the resolution of query type, in this case, is an array). So for each of the item, this function will run with the resolved value from the previous resolved in the parent argument and then we can query the database and return the appropriate value.

**Comment by KumarAbhirup** [comment]
Okay, so... I see the difference. When using `prisma-binding`'s Prisma API, then we should access the `author` by `post.author.id` and if the Prisma API is provided by `prisma-cli`, use `post.author().id`...

The issue was relating to two different types of contexts 😅
