### ISSUE TITLE
Having # in password fails to parse connection string

### ISSUE THREAD

**Issue by lvegerano** [prisma/prisma#4247]
## Bug description
If your database string has a password with the `#` character it fails to parse

## How to reproduce

1. Create a db with password `foo#bar`
1. Go to `prisma/.env`
2. Change connection string 
3. Run `npx prisma introspect`

## Expected behavior
I should be able to connect to DB without to having to encode `#`

## Prisma information

- OS: Mac OS
- Database: PostgreSQL (Aurora)
- Node.js version: 12.18.3
- Prisma version:
```
@prisma/cli          : 2.10.2
@prisma/client       : Not found
Current platform     : darwin
Query Engine         : query-engine 7d0087eadc7265e12d4b8d8c3516b02c4c965111 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 7d0087eadc7265e12d4b8d8c3516b02c4c965111 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 7d0087eadc7265e12d4b8d8c3516b02c4c965111 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 7d0087eadc7265e12d4b8d8c3516b02c4c965111 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.304.0
```

**Comment by pantharshit00** [comment]
Try replacing `#` with `%23`. We support percent encoding for special characters as mentioned in postgres docs

https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING


https://tools.ietf.org/html/rfc3986#section-2.1

**Comment by kldzj** [comment]
I encountered this issue as well when composing the connection URL from Docker secrets in preparation for Migrate. I guess this can be managed in runtime by setting the datasource details dynamically, but this (obviously) doesn't work when using Migrate. It's a bit impractical having to encode the password in e.g. a bash environment.

**Comment by lvegerano** [comment]
Encoding it works. I just don't think it should be that way.

**Comment by pantharshit00** [comment]
Well encoding is standard way of doing this and it is officially supported by postgres.

Closing this as original problem is solved.
