### ISSUE TITLE
Multiple link relations of the same type will not work

### ISSUE THREAD

**Issue by IngeniousPentaSquid** [prisma/prisma#4251]
When trying to create multiple uni-direction (link: INLINE) attributes, prisma client won't run.

```
type User {
      mum: Parent @relation(link: INLINE)
      dad: Parent @relation(link: INLINE)
 }
 type Parent {
    _id: ID
 }
```

Having such functionality is extremely useful and also can also be used in multiple scenarios but the datamodel will not allow this?

**Comment by pantharshit00** [comment]
Hi @IngeniousPentaSquid 

If you want to make such relations, you will need to provide a name to them so that prisma can uniquely identify them internally.

Try using this:
```graphql
type User {
      mum: Parent @relation(name:"MumtoParent", link: INLINE)
      dad: Parent @relation(name:"DadtoParent", link: INLINE)
 }
 type Parent {
    _id: ID
 }
```
