### ISSUE TITLE
[Mongo] Querying collections with Float results in not Implemented Error

### ISSUE THREAD

**Issue by IngeniousPentaSquid** [prisma/prisma#4252]
Hi all,

**
Prisma Client Lib: 1.29.1
MongoDB DB Version: 4.0.1
**

Attempting to query a collection with a field of Type float causes an internal server error which suggests that the type is not implemented yet. 
Background: Prisma data model generated from an introspected mongo database and a client is successfully generated. Queries on collections which do not have a Float field work perfectly fine.

As far as I can see for the mongo terminal the find query is being accepted appropriately.

> "stack_trace":"scala.sys.package$.error(package.scala:26) com.prisma.api.connector.mongo.extensions.BisonToGC$.apply(MongoExtensions.scala:90)\\n com.prisma.api.connector.mongo.extensions.BisonToGC$.apply(MongoExtensions.scala:65)\\n com.prisma.api.connector.mongo.extensions.DocumentToRoot$.$anonfun$apply$6(MongoExtensions.scala:124)\\n scala.Option.map(Option.scala:146)\\n com.prisma.api.connector.mongo.extensions.DocumentToRoot$.$anonfun$apply$5(MongoExtensions.scala:124)\\n scala.collection.immutable.List.map(List.scala:286)\\n com.prisma.api.connector.mongo.extensions.DocumentToRoot$.apply(MongoExtensions.scala:124)\\n com.prisma.api.connector.mongo.extensions.MongoResultReader.readsPrismaNode(MongoExtensions.scala:102)\\n com.prisma.api.connector.mongo.extensions.MongoResultReader.readsPrismaNode$(MongoExtensions.scala:101)\\n com.prisma.api.connector.mongo.database.MongoActionsBuilder.readsPrismaNode(MongoActionsBuilder.scala:18)\\n com.prisma.api.connector.mongo.database.NodeManyQueries.$anonfun$getNodes$3(NodeManyQueries.scala:20)\\n scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)\\n scala.collection.immutable.List.foreach(List.scala:388)\\n scala.collection.TraversableLike.map(TraversableLike.scala:233)\\n scala.collection.TraversableLike.map$(TraversableLike.scala:226)\\n scala.collection.immutable.List.map(List.scala:294)\\n com.prisma.api.connector.mongo.database.NodeManyQueries.$anonfun$getNodes$2(NodeManyQueries.scala:20)\\n scala.util.Success.$anonfun$map$1(Try.scala:251)\\n scala.util.Success.map(Try.scala:209)\\n scala.concurrent.Future.$anonfun$map$1(Future.scala:288)\\n scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)\\n scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)\\n java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\\n java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\\n java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\\n java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)","message":"Not implemented: com.prisma.shared.models.TypeIdentifier$Float$@552765e3BsonInt32{value=2586}"}}

**Comment by do4gr** [comment]
Hey @IngeniousPentaSquid,

the error shows that Prisma is trying to read a field that is defined in the datamodel as Float, but is finding the value in the database to be of type BsonInt32 which does not align with our mapping of datatypes. 

|  Prisma Datamodel | Mongo Bsontype   |
|---|---|
| Float  | BsonDouble   |
|  Int | BsonInt32  |
|  int | BsonInt64  |

Changing the type in your datamodel to Int manually should enable Prisma to read the field and fix your problem, but I would still like to understand how this happened. 

How did you generated your datamodel? Did you decide to choose the type Float or did the Prisma introspection generate that?

**Comment by Shion093** [comment]
I have the same problem, in my mongodb it is Double and `prisma introspect` generated my datamodel as Int, so I get this message.

```javascript
"exception":"java.lang.RuntimeException: Not implemented: com.prisma.shared.models.TypeIdentifier$Int$@3eeebb8aBsonDouble{value=1.0}
```

if I change my model manually to Double I get this message
```javascript
"exception":"java.lang.RuntimeException: Not implemented: com.prisma.shared.models.TypeIdentifier$Float$@11c48277BsonInt32{value=1}
```

So there is no way around this, any help? 

This is the type in question

```javascript
type BodySupport @embedded {
  id: Int
  label: String
  value: Int
}
```

And the query

```javascript
query exercises {
  exercises(first: 10) {
    _id
    data {
      bodySupport {
        id
      }
    }
  }
}
```
The other values retrieved just fine, but the id throws the error

thanks

**Comment by do4gr** [comment]
Hey @Shion093 , sorry for replying this late. I have a suspicion what is going on in your case. Can you check all values of the value column in your underlying MongoDB? I suspect that some of them are BsonInts and some are BsonDouble. 

When Prisma introspects it if samples the columns. Based on the sampling it probably only found BsonInts and therefore generated INT as type. When you then read from the db it found a field that was actually of type BsonDouble and errors. Changing the type in the datamodel could not fix it since then it errors when it finds the BsonInt while trying to read a FLOAT. 

Prisma expects all instances of a field value to be of the same type. So a solution would be for you to convert all values to the same underlying Bson type. 

I hope that helps.

**Comment by IngeniousPentaSquid** [comment]
Hi sorry for the late reply. 

> Hey @IngeniousPentaSquid,
> 
> the error shows that Prisma is trying to read a field that is defined in the datamodel as Float, but is finding the value in the database to be of type BsonInt32 which does not align with our mapping of datatypes.
> 
> Prisma Datamodel	Mongo Bsontype
> Float	BsonDouble
> Int	BsonInt32
> Changing the type in your datamodel to Int manually should enable Prisma to read the field and fix your problem, but I would still like to understand how this happened.
> 
> How did you generated your datamodel? Did you decide to choose the type Float or did the Prisma introspection generate that?

Hi, extremely sorry for the late reply, but I had that same idea after a while and it did work. I used introspection to generate the datamodel.

**Comment by do4gr** [comment]
Thanks for reporting back, good to know you got it to work!
