### ISSUE TITLE
Subscriptions are not stable. Prisma terminates with a GqlConnectionTerminate error

### ISSUE THREAD

**Issue by THPubs** [prisma/prisma#4253]
I just implemented subscriptions in my API which use `graphql-yoga`. I have one prisma server which have the following config:

    databases:
      default:
        connector: postgres
        host: 
        database: prisma
        port: 5432
        user: admin
        password: ${DB_PASSWORD}
        migrations: true
        rawAccess: true
        ssl: true
        connectionLimit: 5

Note that I have limited the number of connections because I'm connecting to a Google Cloud SQL instance which have limited number of allowed connections. Now I have 4 yoga apps connecting to this one prisma server. The problem is, sometimes the subscriptions work and sometimes it throws the following error (In the playground):

    {
      "error": "Could not connect to websocket endpoint wss://yourapi.com/subscriptions. Please check if the endpoint url is correct."
    }

When I check the prisma container logs, I found this:

    Deployment worker initialization complete.
    Version is up to date.
    [SubscriptionSessionActor] Received unknown message: com.prisma.subscriptions.protocol.SubscriptionProtocolV07$Requests$GqlConnectionTerminate$@494aa66a
    Killed
    Obtaining exclusive agent lock...
    Initializing workers...
    Obtaining exclusive agent lock... Successful.
    Successfully started 1 workers.
    Server running on :4466

My APIs are behind an Nginx proxy:

    server {
      server_name example.com;
      listen 443 ssl http2;

      location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Custom-Referrer "idToken";
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_max_temp_file_size 0;
        proxy_pass http://127.0.0.1:4050;
        proxy_redirect off;
        proxy_read_timeout 240s;
      }

        ssl_certificate ___ # managed by Certbot
        ssl_certificate_key ___ # managed by Certbot
    }

Any idea what's happening?

**Comment by pantharshit00** [comment]
Hi, Sorry for the late response. 

Can you please tell me the subscriptions that you are making. It is kinda impossible to reproduce without them.

**Comment by THPubs** [comment]
No worries. Here's a sample subscription im running in the playground:

    subscription {
      order(where: { node: { status_in: [DONE] } }) {
        mutation
        node {
          id
        }
      }
    }

In the schema.graphql it looks like this:

    type Subscription {
      order(where: OrderSubscriptionWhereInput): OrderSubscriptionPayload
    }

And the actual subscription is like this:

    const Subscription = {
      order: {
        subscribe: async (parent, args, ctx, info) => ctx.db.subscription.order({}, info)
      }
    };

**Comment by pantharshit00** [comment]
I am unable to reproduce this. Can you please create a small repository with a minimal reproduction?

**Comment by cjcaj** [comment]
@THPubs what version of prisma are you running? I'm seeing this on 1.24.0

**Comment by THPubs** [comment]
Right now I'm getting it on `1.29.1`

**Comment by ZakSingh** [comment]
Getting this on 1.30.0 w/ Prisma hosted on Fargate

**Comment by meodemsao** [comment]
i have same issue with prisma 1.32 & grapqhl-yoga^1.16.7

**Comment by meodemsao** [comment]
subscription not stable, sometime can't receive message
