### ISSUE TITLE
PRIVACY: Prisma is tracking on sensitive sites

### ISSUE THREAD

**Issue by MathiasKandelborg** [prisma/prisma#4264]
Hi, I was just looking at the prisma-admin source code and noticed you're registering both GA and Sentry... Even for self-hosted servers. This should at the very least be optional _and_ opt-in.

It should also be stated **clearly** that you are tracking peoples usage of the `_admin` URL in development and production, with a proper explanation of the exact uses. I haven't signed or agreed to anything... I'm using free and open source software, we all are. That is unless we're signed up for your service

I really shouldn't have to make this issue. This is quite violating of peoples privacy, especially when you're doing it without publicly acknowledging it.

**Comment by schickling** [comment]
Thanks a lot for bringing this up @MathiasKandelborg. As a first step, we're currently working on a docs page that provides more transparency. Sorry for the delay on this!
