### ISSUE TITLE
Add `check` Option to `format` CLI Command

### ISSUE THREAD

**Issue by iddan** [prisma/prisma#4267]
## Problem
Currently, one can only format a schema using `prisma format` but can't validate the schema is formatted, in CI for example.

## Suggested solution
Add a `--check` option to the CLI for validating the schema is properly formatted.

## Alternatives
Add integration with Prettier which already has this functionality as described here: https://github.com/prisma/prisma/issues/1761

## Additional context
In https://github.com/amplication/amplication we are currently struggling with keeping consistent formatting of our Prisma Schema file. I can write a script to validate it in our CI but I think this functionality is relevant for more users and would be much simpler to implement if it was part of the CLI.

**Comment by PabloSzx** [comment]
any news on this? :eyes:

**Comment by janpio** [comment]
What exactly should this do? Are you looking for `prisma validate` maybe?

**Comment by iddan** [comment]
I'm looking for both `prisma format` and `prisma validate`

**Comment by janpio** [comment]
Still do not fully get it. Do you want a command that tells you true/false if a schema is already formatted or not? Or something else?

**Comment by iddan** [comment]
In prettier I have a command to validate the code is formatted correctly: `prettier --check`. I thought it would make sense that `prisma format` will have a way to validate the schema is formatted correctly and if not it will return status code 1 (so it can fail CI)

**Comment by mogzol** [comment]
Any update on this? The ability to check if formatting is valid without modifying the files is very useful, every other formatting tool I've used before has that function. I use the functionality both in CI pipelines and in a pre-push git hook to prevent unformatted files from being pushed. Currently there's no way to do that with Prisma.

**Comment by janpio** [comment]
Duplicate: https://github.com/prisma/prisma/issues/12412

**Comment by baileywickham** [comment]
I opened a PR [here](https://github.com/prisma/prisma/pull/24613) to add support for this, let me know if there is anything else I can do to help with this.
