### ISSUE TITLE
Prisma Deploy Authorization Error

### ISSUE THREAD

**Issue by impowski** [prisma/prisma#4284]
**Describe the bug**
Running `prisma deploy` gives this bug:

```console
ERROR: No 'Authorization' header provided.

{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "addProject"
      ],
      "code": 3015,
      "message": "No 'Authorization' header provided.",
      "requestId": "local:cjtvsmn86098l0780lzufje0n"
    }
  ],
  "status": 200
}

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ export DEBUG="*"
```
**To Reproduce**
1. Run `prisma deploy`
2. See error

**Expected behavior**
Should deploy without any errors

**Versions (please complete the following information):**
 - Connector: [`Postgres`]
 - Prisma Server: [`1.30.0-beta`]
 - `prisma` CLI: [`prisma/1.30.0-beta.6 (darwin-x64) node-v11.12.0`]
 - OS: [`OS X Mojave`, `Ubuntu`]

**Comment by MathiasKandelborg** [comment]
The error message is in regards to a header not being sent (you probably already guessed that).

I'm not 100% sure but I think you have set a secret which isn't declared in ENV when running deploy.

Debugging this would be easier with the contents of your `prisma.yml` and `docker-compose.yml` files.

**Comment by cheuk3** [comment]
i got the same problem too

**Comment by impowski** [comment]
@MathiasKandelborg `PRISMA_SECRET` is set in both `.env` and `prisma.yml`

**Comment by pantharshit00** [comment]
Hi @impowski 

Have you set the managementApiSecret in the `PRISMA_MANAGEMENT_API_SECRET` environment variable? It is required for deployment and you can find it in your docker-compose.yml file.

See: https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4/#management-api-secret

**Comment by cheuk3** [comment]
how to set the variable on windows?

**Comment by impowski** [comment]
@pantharshit00 Yes, it's set in `docker-compose.yml` and inside `.env`

**Comment by pantharshit00** [comment]
@impowski Can you please share a minimal reproduction in a repository?

@cheuk3 In windows use `set PRISMA_MANAGEMENT_API_SECRET=yoursecret`

**Comment by cheuk3** [comment]
@pantharshit00 
I did that but still get the same error
ERROR: No 'Authorization' header provided.

**Comment by impowski** [comment]
@pantharshit00 I mean, set a `secret` inside `prisma.yml`, which is a `PRISMA_SECRET` inside `.env`. Then set a `PRISMA_MANAGEMENT_API_SECRET` inside `.env` and inside `docker-compose.yml`. Everything working on version `prisma/1.30.0-beta.3`, starting from `prisma/1.30.0-beta.4` something is wrong.

**Comment by thanhngvpt** [comment]
Try to gen token by `prisma token` then using it in the header

**Comment by impowski** [comment]
I installed the newest version, which is `prisma@1.30.0-beta.8` and it does work.

**Comment by cheuk3** [comment]
@impowski how to install prisma@1.30.0-beta.8 as I tried to install with npm which said "No matching version found for prisma@1.30-beta.8".
Thanks

**Comment by captDaylight** [comment]
I have a nearly identical error on 1.33. Any take aways to resolve Authorization errors?

**Comment by DennisKo** [comment]
What I had to do to update from 1.32 to 1.33:

- in `docker-compose.yml` change image to latest version `image: prismagraphql/prisma:1.3`
- also in `docker-compose.yml` make sure you have the `managementApiSecret` set like that:
```
environment:
      PRISMA_CONFIG: |
        managementApiSecret: mySecret
```
- recreate the docker container: `docker-compose up -d` 
- create a `.env` file in the root dir with content `PRISMA_MANAGEMENT_API_SECRET=mySecret`
- `prisma deploy`

**Comment by smrsan76** [comment]
@DennisKo  The problem is still exists in `v1.34.0` !

**Comment by gihrig** [comment]
I encountered this error. My solution:

1. `$docker-compose down`
2. `DROP DATABASE prisma` (SQL client)
3. `$docker-compose up -d`
4. `$prisma deploy`

Prisma CLI version: prisma/1.34.0 (darwin-x64) node-v12.4.0
Prisma server version: 1.34.0
macOS 10.14.5 (Mojave)

**Comment by leafyshark** [comment]
Hey guys, try `sudo prisma deploy`

I was getting the same issue running `prisma deploy` on a Digital Ocean droplet from [these](https://www.prisma.io/tutorials/deploy-prisma-to-digitalocean-ct12/#4.-start-the-prisma-server) instructions.

Error:

```
ERROR: No 'Authorization' header provided.

{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "addProject"
      ],
      "code": 3015,
      "message": "No 'Authorization' header provided.",
      "requestId": "local:cjwzc8bpi000e077173ikilyp"
    }
  ],
  "status": 200
}
```

directory structure (server root /):

```
docker-compose.yml
/var
/etc
/auvporsche
    prisma.yml
    datamodel.graphql
    .env
```

Prisma v1.34

Removed managementApiSecret from docker-compose.yml, removed secret from prisma.yml, ran `sudo prisma deploy` in /auvporsche and managed to get it to deploy.

**Comment by pantharshit00** [comment]
> Removed managementApiSecret from docker-compose.yml, removed secret from prisma.yml

Please don't do that in production. Your Prisma server will not be secured that way
