### ISSUE TITLE
[Mongo] GraphQL Connection Query Error

### ISSUE THREAD

**Issue by soqt** [prisma/prisma#4290]
With the schema and MongoDB connector
```gql
type User {
    id: ID! @id 
    name: String
    following: [User!]!  @relation('UserToFollow', link: INLINE)
    followers: [User!]! @relation('UserToFollow')
}
```

After created couple users, an error occurs with this query:

```gql
{
  usersConnection(where: {
    followers_some: {
      id: "USER_ID"
    },
  }, first: 2, after: "FOLLOWING_USER_ID") {
    pageInfo {
      endCursor
    }
    edges {
      node {
        id
        name
      }
    }
  }
}
```
The error message seems relate to `$or` which has been removed from MongoDB connector. This error happens specifically with `after` argument included.
```
"message":"Command failed with error 40324 (Location40324): 'Unrecognized pipeline stage name: '$or'' on server mongo:27017. The full response is { \"ok\" : 0.0, \"errmsg\" : \"Unrecognized pipeline stage name: '$or'\", \"code\" : 40324, \"codeName\" : \"Location40324\" }"}}
```

**Versions **
 - Connector: `MongoDB`
 - Prisma Server:`1.29.2`
 - `prisma` CLI: `prisma/1.29.2 (darwin-x64) node-v10.4.0`
 - OS: `OS X High Sierra`
 - other dependencies: `prisma-binding`

**Comment by do4gr** [comment]
Thanks for the detailed reproduction. We have a fix and will release it to master soon.
