### ISSUE TITLE
Transaction Table in v2.11.0

### ISSUE THREAD

**Issue by diegozuber** [prisma/prisma#4299]
## Bug description

Since v2.11.0 was released, you are not able to have a MySQL table called "Transaction". It will conflict with this line in the client:

node_modules/.prisma/client/index.d.ts
```ts
  /**
   * @deprecated renamed to `$transaction`
   */
  transaction: PromiseConstructor['all']
```

## How to reproduce

Create a table named "Transaction" and try to generate the client.

**Comment by divyenduz** [comment]
It shouldn't be possible to have a table with this name even with older version of Prisma right?

**Comment by haroldport** [comment]
I have the same problem  in Prisma 2.11.0 with a table called Transaction in Postgresql
<img width="899" alt="Screen Shot 2020-11-19 at 17 35 45" src="https://user-images.githubusercontent.com/6332287/99732594-c2176300-2a8d-11eb-90f1-27c5d3de34e2.png">

**Comment by haroldport** [comment]
> It shouldn't be possible to have a table with this name even with older version of Prisma right?

In my case, I have this table in older version of Prisma

**Comment by diegozuber** [comment]
> > It shouldn't be possible to have a table with this name even with older version of Prisma right?
> 
> In my case, I have this table in older version of Prisma

Same here. I downgraded to v2.10.2 and there it works fine.

**Comment by timsuchanek** [comment]
Thanks! This is already fixed in `dev` - you can try it out with `@prisma/client@dev`. The stable release for this will go out in `2.12` next week Tuesday.
