### ISSUE TITLE
CLI: delete command should show endpoint of deleted service

### ISSUE THREAD

**Issue by huv1k** [prisma/prisma#4306]
**Is your feature request related to a problem? Please describe.**
Right now `prisma delete` show only `service@stage` of service. This does not reflect changes with `endpoint`. 

![](https://i.imgur.com/cn91N92.png)

**Describe the solution you'd like**
Instead of `service@stage` show `endpoint` of service, what is going to be deleted.

**Comment by divyenduz** [comment]
This is available in stable since 1.33.0.
