### ISSUE TITLE
prisma generate is blocked by query-engine-rhel-openssl-1.0.x opening in Notepad on Windows

### ISSUE THREAD

**Issue by Tobbe** [prisma/prisma#4308]
## Bug description

When I run `prisma generate` two instances of Notepad are launched, which block `prisma generate` from completing until I close them

![image](https://user-images.githubusercontent.com/30793/99726911-809bad80-2ab7-11eb-8329-510d95c45b3e.png)

Until I close those two windows, it will just stand there waiting.

Just as a test I did this, and it did get rid of the problem, but also doesn't generate the binary targets I need...
![image](https://user-images.githubusercontent.com/30793/99726847-5fd35800-2ab7-11eb-99fd-18b43656a5fb.png)

## How to reproduce

This is the command I run

```terminal
$ node_modules/.bin/prisma generate --schema=api/db/schema.prisma
```

This is what my schema looks like

```prisma
datasource DS {
  // optionally set multiple providers
  // example: provider = ["sqlite", "postgresql"]
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
}
```

## Expected behavior

I expect `prisma generate` to run to completion without launching Notepad

## Prisma information

See above

## Environment & setup

- OS: Windows 10 10.0.19041
- Database: SQLite
- Node.js version: 14.4.0
- Prisma version: 2.9.0

```
$ node_modules/.bin/prisma -v
@prisma/cli          : 2.9.0
@prisma/client       : 2.9.0
Current platform     : windows
Query Engine         : query-engine 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 369b3694b7edb869fad14827a33ad3f3f49bbc20 (at node_modules\@prisma\cli\prisma-fmt-windows.exe)
Studio               : 0.296.0
```

**Comment by janpio** [comment]
What command line are you using here?
Does Notepad show the file name that is being opened?

> Just as a test I did this, and it did get rid of the problem, but also doesn't generate the binary targets I need...
What do you mean by that? Don't you need the Windows binaries (as shown in the `prisma -v` output) on Windows?

**Comment by Tobbe** [comment]
> Does Notepad show the file name that is being opened?

![image](https://user-images.githubusercontent.com/30793/99812114-5a711e80-2b46-11eb-8032-e37b27547053.png)

Not sure how familiar you are with Windows, but the title of the window only shows the filename, not the path. But if you chose "Save As" a dialog pops open, generally defaulting to the dir of the file that's open, and if I do that, this is what I see

![image](https://user-images.githubusercontent.com/30793/99812374-ad4ad600-2b46-11eb-95b1-b0269ac4f948.png)

> What command line are you using here?

In the screenshots I'm using ConEmu 201011

Same thing happens with GitBash though

![image](https://user-images.githubusercontent.com/30793/99812915-50035480-2b47-11eb-9205-f233550c9c02.png)

And PowerShell

![image](https://user-images.githubusercontent.com/30793/99813043-7d500280-2b47-11eb-8ca8-0d095129ca99.png)

> What do you mean by that? Don't you need the Windows binaries (as shown in the prisma -v output) on Windows?

I'm sorry, but I'm not fully clear on the details here. As you've probably seen from the screenshots I'm using Prisma through RedwoodJS. And for Prisma 2.9.0 we had to do ["native", "rhel-openssl-1.0.x"]. I think it was to get deployments on Netlify to work.

> What happens if you execute the node_modules\@prisma\cli\query-engine-windows.exe manually?

I can run it, but not sure how to use it
![image](https://user-images.githubusercontent.com/30793/99813823-7675bf80-2b48-11eb-97e6-7eebeae4ca2b.png)

**Comment by janpio** [comment]
Ok, for some reason Prisma is executing not the Windows binary, but the `rhel-openssql-1.0.x` one for you - that is already strange and should not be the case.

Now to the Notepad thing:
My guess is that your machine is configured to open `.x` files with Notepad by default somehow (instead of not knowing what to do with them as it is not a .exe). Can you execute `node_modules\@prisma\cli\query-engine-rhel-openssl-1.0.x` manually and see if Notepad is opened?

**Comment by Tobbe** [comment]
> Can you execute node_modules\@prisma\cli\query-engine-rhel-openssl-1.0.x manually and see if Notepad is opened?

Yes, it is. You are right, .x files are associated with Notepad. 
Same thing happens if I "execute" file.txt, Notepad is opened.

![image](https://user-images.githubusercontent.com/30793/99815806-19c7d400-2b4b-11eb-81e8-5672f336c9db.png)

I can remove the association (it's a pita, but it's doable) and when I do, what happens is that when I run `prisma generate` the "app chooser" dialog flashes open on my screen.
This one

![image](https://user-images.githubusercontent.com/30793/99815939-50055380-2b4b-11eb-8e5e-ccfe06ede4fd.png)

**Comment by janpio** [comment]
Problem solved - it does not open Notepad any more :trollface: 

For real though, that explains why `.x` files open Notepad for you. Now we need to understand why it does not run the Windows binaries for you as it should.

Can you run Prisma as `npx prisma` via the normal `cmd.exe` (or Powershell) in Windows? You can also remove the `binaryTarget` completely from your schema to do that and just let Prisma decide itself what it wants to run.

**Comment by Tobbe** [comment]
> Can you run Prisma as npx prisma via the normal cmd.exe (or Powershell) in Windows?

Same thing

![image](https://user-images.githubusercontent.com/30793/99841605-bf406f00-2b6e-11eb-9671-cfd778e41e90.png)

> You can also remove the binaryTarget completely from your schema to do that and just let Prisma decide itself what it wants to run.

Is this the same thing as ["native"]? Anyway, yes, this does not try to launch the .x file.  But I suspect running without `binaryTarget` specified doesn't work when I deploy (haven't tried though, so can't be 100% sure). Either way, that doesn't explain why it even tries to tell windows to launch that file.

**Comment by pantharshit00** [comment]
I can reproduce this when using prisma with wsl then using on windows with following binary targets:
`binaryTargets = ["native", "debian-openssl-1.0.x"]`

It is more visible with the `--watch` flag as it hands the process.



https://user-images.githubusercontent.com/22195362/104291298-5ed00d00-54e1-11eb-8285-8663febcbda5.mp4

**Comment by pantharshit00** [comment]
This still happens with 2.22 and even with napi. I candidated it.

**Comment by janpio** [comment]
Summary of the problem: For some reason, the wrong binaries are trying to be executed automatically in this situation. As the OS does not understand them, it does random things.

**Comment by millsp** [comment]
I get the same issue on a fresh Windows 10 install, and not on WSL. `binaryTargets = ["native"]` works fine but not `binaryTargets = ["native", "debian-openssl-1.0.x"]`. At very first it seems to work (and it does), but if you generate again _**and**_ the linux binary exists already, then it opens it. Delete the linux binary, and it works again.

![Screenshot from 2021-05-19 18-30-03](https://user-images.githubusercontent.com/18401805/118850091-b1c33200-b8d0-11eb-86e3-7385d22cac32.png)

**Comment by janpio** [comment]
Which means it is something in the `generate` process, that is trying to use the Debian (wrong) binary to execute for something. Wild guess: Probably some getConfig or dmmf or similar.

**Comment by janpio** [comment]
(Debugged a very similar problem for https://github.com/prisma/prisma/issues/7693#issuecomment-868814030 - so took a look at this one as well) 

Turns out it is trying to **get the version** of that binary in the process:
https://github.com/prisma/prisma/blob/ad8f073b83ddd9fd6a57c01fa7ac16d75a69f0a7/src/packages/sdk/src/engine-commands/getVersion.ts#L17-L28

For the Windows one that works of course, but the Rhel or Debian one of course can not be executed on Windows - and that popups opens.

We probably want to add something here that it knows about the current platform and the platform of the binary, and only tries to execute this for the ones that _can_ be executed as they are the same platform.

Possibly that can already happen in the loop that calls the method above in the first place:
https://github.com/prisma/prisma/blob/9c287b3d45ae721f463b682651bd778cfab9d05a/src/packages/client/src/generation/generateClient.ts#L252-L295

If that version check fails, it just copies the file anyway - so on the wrong platform it could just default to that:
https://github.com/prisma/prisma/blob/9c287b3d45ae721f463b682651bd778cfab9d05a/src/packages/client/src/generation/generateClient.ts#L283-L293
(The `catch` makes sure when it can not get a version, it returns null, but of course there the popup is already open)

**Comment by janpio** [comment]
With the "new" Node-API library engine this should not be happening any more optimally.

**Comment by jkomyno** [comment]
As of `prisma@4.3.0`, on Windows 10, neither `prisma generate` nor `set PRISMA_CLIENT_ENGINE_TYPE=binary && prisma generate` attempt to open the `query-engine-rhel-openssl-1.0.x` file (the stdout shows that both `windows` and `query-engine-rhel-openssl-1.0.x` are downloaded).
The same stands for Ubuntu 22.04 running on WSL 2 (where the stdout shows that both `debian-openssl-3.0.x` and `query-engine-rhel-openssl-1.0.x` are downloaded).

**Comment by aqrln** [comment]
Still reproducible with latest Prisma 4.14.0. Also reproducible with Prisma 4.3.0, so I can't confirm the comment above. (@jkomyno were you using PowerShell by any chance? If so, the syntax to set the env var is `$env:PRISMA_CLIENT_ENGINE_TYPE = "binary"` and not the `set` command which is doing something else I guess? There's no error when I try to use it but it doesn't modify the environment variables.)

<img src="https://github.com/prisma/prisma/assets/4923335/dd2e3f91-20e4-49a8-a03d-5dbbd935074b" width="460" height="428">
<p></p>

Schema:

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
  engineType    = "binary"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model A {
  id Int @id
}
```

**Comment by janpio** [comment]
I think my suggestions from above is still valid as a solution: https://github.com/prisma/prisma/issues/4308#issuecomment-868819417

**Comment by jkomyno** [comment]
@aqrln I was using the standard Windows cli (not Powershell)
