### ISSUE TITLE
Can't connect to PostgresQL in cloud.yandex.ru

### ISSUE THREAD

**Issue by dreamniker** [prisma/prisma#4321]
`prisma_1  | Apr 05, 2019 9:12:56 PM org.postgresql.Driver connect
prisma_1  | SEVERE: Connection error: 
prisma_1  | org.postgresql.util.PSQLException: ERROR: Unsupported startup parameter: search_path
prisma_1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
prisma_1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
prisma_1  | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1  | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1  | 	at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1  | 	at org.postgresql.Driver.connect(Driver.java:254)
prisma_1  | 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
prisma_1  | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1  | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1  | 	at java.lang.Thread.run(Thread.java:748)
`
- PostgreSQL 10
 - Connector: [e.g. `Postgres`]
 - Prisma Server: [e.g. `1.25.0`]
 - OS: [`Ubuntu 16.04`]

**Comment by podliy16** [comment]
Seems related to pgbouncer: https://github.com/Athou/commafeed/issues/559

As I know you can't change config of pgbouncer  in Yandex cloud. 

So, is there any way to skip setting search_path in startup and use default?

**Comment by pantharshit00** [comment]
Hi,

Can you please add `schema: public` option in your docker-compose.yml file in the PRISMA_CONIG under the database.default so that it skips setting search_path.

**Comment by dreamniker** [comment]
> Hi,
> 
> Can you please add `schema: public` option in your docker-compose.yml file in the PRISMA_CONIG under the database.default so that it skips setting search_path.

It didn't help, still the same error:(

**Comment by willrbc** [comment]
We are having exactly the same issue connecting to a postgres Digital Ocean Managed Database

``WARNING: SQLException occurred while connecting to xxx-0.db.ondigitalocean.com:25061
prisma_1  | org.postgresql.util.PSQLException: ERROR: unsupported startup parameter: search_path
prisma_1  |     at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
prisma_1  |     at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
prisma_1  |     at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1  |     at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1  |     at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1  |     at org.postgresql.Driver.connect(Driver.java:254)
prisma_1  |     at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
prisma_1  |     at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:68)
prisma_1  |     at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
prisma_1  |     at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
prisma_1  |     at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
prisma_1  |     at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
prisma_1  |     at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
prisma_1  |     at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
prisma_1  |     at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
prisma_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1  |     at java.lang.Thread.run(Thread.java:748)``

**Comment by willrbc** [comment]
Is it possible that newer versions of Postgres and or managed instances like ours at Digital Ocean cannot accept 'search_path' as a startup parameter in the connection URL.

There is an alternative, ``currentSchema``

https://github.com/prisma/prisma/blob/0abb28a6f92e6999139055e5259ab7f7cff23429/server/libs/jdbc-native/src/main/scala/com/prisma/native_jdbc/CustomJdbcDriver.scala#L40

**Comment by podliy16** [comment]
@willrbc Did you manage to run prisma at DO?

**Comment by willrbc** [comment]
@podliy16  no luck yet.

**Comment by coosamatt** [comment]
Same issue... using DO.

**Comment by coosamatt** [comment]
I was able to start and deploy but not using a connection pool but rather the primary DB username/port..
This wouldn't scale up for production but does allow us to play with it. Looks to be a feature of the connection pools and pgbouncer. I've also reached out to Digital Ocean support for any help from them.

**Comment by pantharshit00** [comment]
@coosamatt Can you please share your docker-compose.yml file(just redact any sensitive information)?

I will try to reproduce this after that.

**Comment by pedrojardim** [comment]
I'v used pgbouncer and had the same problem. 

I fix it by passing this command to my pg_bouncer:

environment:
      IGNORE_STARTUP_PARAMETERS: search_path , extra_float_digits

**Comment by Yomanz** [comment]
> 
> 
> I'v used pgbouncer and had the same problem.
> 
> I fix it by passing this command to my pg_bouncer:
> 
> environment:
> IGNORE_STARTUP_PARAMETERS: search_path , extra_float_digits

The issue mainly for people who use managed DBs where there is not enough access to do that

**Comment by alexander-potemkin** [comment]
The issue in on Yandex.Cloud site settings - it's on the roadmap to be rolled out to production databases, at the meantime please feel free to reach me if you need it sooner than that.

**Comment by oem2** [comment]
I am having the same issue and I tried the solution @pedrojardim suggested. I still get the following error:

```
Mar 25, 2020 5:00:56 AM org.postgresql.Driver connect
prisma_1    | SEVERE: Connection error: 
prisma_1    | org.postgresql.util.PSQLException: ERROR: unsupported startup parameter: search_path
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
prisma_1    | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1    | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1    | 	at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1    | 	at org.postgresql.Driver.connect(Driver.java:254)
prisma_1    | 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1    | 	at java.lang.Thread.run(Thread.java:748)
```
