### ISSUE TITLE
uncheckedScalarInputs One relationship unchecked

### ISSUE THREAD

**Issue by DregondRahl** [prisma/prisma#4322]
## Bug description

If we have a table which has two or more relationships, we can't use both the "connect" method and direct id method. Also 'create' relationship won't work on other relationships

## How to reproduce

```
    return this.prisma.zone.create({
      data: {
        facilityId: record.cityId, // direct
        city: {
          connect: {
            id: record.cityId // using connect
          },
        },
      },
    });
```

Create

```
    return this.prisma.zone.create({
      data: {
        facilityId: record.cityId, // direct
        city: {
          create: {
            name: record.city.name, //create
          },
        },
      },
    });
```

## Expected behavior
It should allow both ways for different relationships. Right now with the XOR check its deciding either checked or unchecked input type for the object.

**Comment by pantharshit00** [comment]
Hey @DregondRahl 

Can you please share the datamodel that you are using here? That would help in reproducing this problem. You can also just share these two models which are in question here.

**Comment by DregondRahl** [comment]
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["uncheckedScalarInputs"]
}

model Zone {
  id         Int      @id @default(autoincrement())
  name       String
  city       City     @relation(fields: [cityId], references: [id])
  cityId     Int
  district   District @relation(fields: [districtId], references: [id])
  districtId Int
}

model City {
  id    Int     @id @default(autoincrement())
  name  String?
  zones Zone[]
}

model District {
  id    Int     @id @default(autoincrement())
  name  String?
  zones Zone[]
}
```

```
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const newZone = await prisma.zone.create({
    data: {
      name: "Test",
      cityId: 1,
      district: {
        create: { name: "East" },
      },
    },
  });

  const allZones = await prisma.zone.findMany({
    include: {
      district: true,
      city: true,
    },
  });

  console.dir(allZones, { depth: null });
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

```

**Comment by pantharshit00** [comment]
Hey @DregondRahl 

This is intentional right now. The problem here is if we allow both cases for each foreign key, there will be too many permutations and input generation will blow exponentially. For example with four foreign keys, we will need to generate 2^4=16 input types. 

For now you will need to either choose use one of the syntaxes. My recommendation would be to if you fallback to connect method if you need connect via some other field.

**Comment by DregondRahl** [comment]
Hi @pantharshit00 i can understand if its only connect, but my concern is mostly on the create part also. For example, if we are connecting by 'fk' then what would be the best practice for creating a related element? nested create/update won't work correct?

**Comment by pantharshit00** [comment]
@DregondRahl For that just use the relational syntax using `create`. No need to use uncheckedScalar. 


`uncheckedScalar` is just a shortcut for some very common use cases. You can always resort to old style if you have multiple or nested values.

**Comment by matthewmueller** [comment]
Thanks @pantharshit00, closing. We can re-open if that doesn't work for you @DregondRahl.
