### ISSUE TITLE
Cannot access SSL certificates when deploying to production on Vercel

### ISSUE THREAD

**Issue by dewildio** [prisma/prisma#4324]
## Bug description

I am building a website using Nextjs + Apollo server micro + Apollo client + Prisma, with a GCP Postgresql database. 

When working on my local machine, migrations, queries and mutations work on my local test database and my production database (for example running `yarn prisma migrate up --experimental`).

However after deployment to production, when I trigger a first query, i'm getting this error `Uncaught (in promise) Error: Error opening a TLS connection: cert file not found (No such file or directory (os error 2))`.

<img width="799" alt="Capture d’écran 2020-11-23 à 10 52 46" src="https://user-images.githubusercontent.com/56075210/99948748-326a0100-2d7a-11eb-84de-1ebb4cbd169c.png">

For local development I use `dotenv cli` to manage environments for my DATABASE_URL.
As SSL security is implemented the url looks like this  `DATABASE_URL="postgresql://USER:PASSWORD@IP:PORT/DATABASE_NAME?schema=public&sslmode=required&sslcert=../server-ca.pem&sslidentity=../client-identity.p12&sslpassword=PASSWORD&sslaccept=strict"` as described in [this issue](https://github.com/prisma/prisma/issues/1433) 

For the production build I use the Vercel Secrets feature to store the DATABASE_URL.

I have tried the solution presented [here](https://github.com/prisma/prisma/issues/1286), by using the relative path to the root folder, as well as absolute path with no success.

I have tried logging the database URL on build, and it is showing me the 'correct' URL, (the one I implemented).

My file structure is like this
.
| pages
|— api
|—— graphql.js
| prisma
|— migrations
|— schema.prisma
| server-cert.pem
| client-identity.p12

## Prisma information

I'm using @prisma/client 2.11.0

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL (Google Cloud)
- Node.js version: 14.4.0
- Prisma version:

```
@prisma/cli          : 2.11.0
@prisma/client       : 2.11.0
Current platform     : darwin
Query Engine         : query-engine 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.311.0
```

How the Prisma client is called in my `graphql.js` 

```
import { makeSchema, objectType, stringArg, intArg, asNexusMethod } from '@nexus/schema'
import { GraphQLDate } from 'graphql-iso-date'
import { ApolloServer } from "apollo-server-micro";
import { PrismaClient } from '@prisma/client';
import path from 'path';

export const GQLDate = asNexusMethod(GraphQLDate, 'date')

console.log(process.env.DATABASE_URL)

const prisma = new PrismaClient()

const Depute = objectType({
  name: 'Depute',
  definition(t) {
    t.string('id')
    t.string('first_name')
    t.string('last_name')
  },
})

const Query = objectType({
  name: 'Query',
  definition(t) {
    t.field('depute', {
      type: 'Depute',
      args: {
        id: stringArg({ nullable: false }),
      },
      resolve: (_parent, args, _ctx) => {
        return prisma.depute.findOne({
          where: { id: args.id },
        })
      },
    })
  }, 
})

export const schema = makeSchema({
  types: [Query, Depute, GQLDate],
  outputs: {
    typegen: path.join(process.cwd(), 'pages', 'api', 'nexus-typegen.ts'),
    schema: path.join(process.cwd(), 'pages', 'api', 'schema.graphql')
  },
})


export const config = {
  api: {
    bodyParser: false,
  },
};

export default new ApolloServer({ 
  schema, 
  debug: true
}).createHandler({
    path: '/api/graphql',
});
```

**Comment by mathiasklenk** [comment]
I think I have a very [similar issue](https://github.com/prisma/prisma/issues/4404) like you, where I am able to connect to postgres in local development but not when it's deployed to production on Vercel. I tried the same like you, logging the `DATABASE_URL` which is supposedly working but the client just doesn't make any queries to the db.
Any success for you so far?

**Comment by dewildio** [comment]
Hi @mathiasklenk, I think we're getting different errors if I understand your issue correctly. 
My problem here is related only to SSL certificates not being accesses because the Lambda functions cannot get to the file. 
I have managed a workaround by encoding the files in base64 > storing the keys as env variables > decoding the files > writing the files, but I'm getting another error. Apparently the certificate cannot be verified. 
So I have given up using the /api routes for now and will use a proper server hosted on GCP, bypassing the SSL certificate issue. 

Sorry I could be of no use.

**Comment by pantharshit00** [comment]
@dewildio Hi, sorry for the late reply here.

Simplifying SSL support is part of the roadmap candidates(https://pris.ly/roadmap) and ssl issues with vercel and prisma are documented in this issue https://github.com/prisma/prisma/issues/1673

So I am going to close this one as a duplicate. Please wait while we work on this.

**Comment by NAllred91** [comment]
Would it be possible to modify this error to indicate where the file was expected to be?

**Comment by janpio** [comment]
Yes, if you open a issue with a current reproduction that triggers the error and describe what it could or should output, we are happy to take a look. Shouldn'T be too hard.
