### ISSUE TITLE
Error: Provided String, expected DateTime or DateTimeFieldUpdateOperationsInput

### ISSUE THREAD

**Issue by maoosi** [prisma/prisma#4328]
I'm not entirely sure if this is a bug! If not a bug, then I'm a bit confused with the DateTime type...

Using **Prisma 2.11.0** (with MySQL), I've created a new DateTime field in my `schema.prisma` file as following:

```graphql
model Story {
    lastSavedAt   DateTime    @default(now())
}
```

When trying to update this particular field with the value `2020-11-23T17:41:59+11:00` I'm getting back the following error:

```shell
Argument lastSavedAt: Got invalid value '2020-11-23T17:41:59+11:00' on prisma.updateOneStory. Provided String, expected DateTime or DateTimeFieldUpdateOperationsInput:

type DateTimeFieldUpdateOperationsInput {
    set?: DateTime
}
type DateTimeFieldUpdateOperationsInput {
    set?: DateTime
}
```

The error outlines that I can't use a String, while the TypeScript type returned for `lastSavedAt` is:

```typescript
// From VSCode
lastSavedAt?: string | Date | DateTimeFieldUpdateOperationsInput

// In the node_modules/.prisma/client/index.d.ts file
export type StoryUpdateInput = {
    lastSavedAt?: XOR<Date | string, DateTimeFieldUpdateOperationsInput>
}
```

Am I missing something?

**Comment by navicstein** [comment]
Am also facing this problem, the workaround that worked for me is to convert the string to date with `new Date(...)`

**Comment by maoosi** [comment]
Thanks @navicstein, I'll see if I can use `new Date(...)` as a workaround for now.

Though, I'd be keen to have someone from the Prisma team confirm if this is actually a bug or the intended way to interact with `DateTime` fields? I personally feel like we should be able to use a String.

**Comment by pantharshit00** [comment]
Hey @maoosi 

This is intended. Prisma will only accept DateTime in ISO 8061 format(https://en.wikipedia.org/wiki/ISO_8601). 

If you want use another format, you can should parse it and convert it into a javascript Date object as suggested @navicstein. We will then internally call `toISOString()` on that Date object and pass it to the database.

**Comment by maoosi** [comment]
Thanks for jumping on this @pantharshit00. Just to be clear, in my example above I was already using an ISO 8601 DateTime format - though allow me to expand a bit more around the issue.

I’ve been running a few different tests since my last message and here is what I’ve found:

- Using `.toISOString()` is working as expected.
- Using `new Date()` is working as expected.
- Using the ISO 8601 DateTime format returned by the [date-fns/formatISO](https://date-fns.org/v2.8.1/docs/formatISO) method isn’t working.
- Using the ISO 8601 DateTime format returned by the [AWSDateTime](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) scalar type isn’t working.

Here’s a sandbox showing the issue using [date-fns/formatISO](https://date-fns.org/v2.8.1/docs/formatISO): https://codesandbox.io/s/prismadatetimedatefns-l7i2u?file=/index.ts (open terminal > yarn run test).

For my use case, I'm using Prisma inside a Lambda function, in combination with AWS AppSync. Therefore, my DateTime inputs are coming through as [AWSDateTime](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) scalar type (ISO 8601). In that context, you will understand that using `.toISOString()` or `new Date()` isn’t easily applicable. Ideally, Prisma would accept the ISO 8601 returned by AWS AppSync.

Happy to be proven wrong, but I feel like Prisma isn't supporting the ISO 8601 format entirely. But only in the exact shape returned by `.toISOString()`?

**Comment by navicstein** [comment]
@maoosi @pantharshit00 
Am not sure that Prisma's date-time thingy is working as expected, let's assume I have some data like this

```js
// db data
[
  {
    id: 'a4a0b0aa-a62a-4c47-9ebc-324c59e9d40d',
    date: 2020-12-23T12:45:00.000Z,
    isOccuringFirst: true,
    startTime: '1:45 PM',
    endTime: '3:45 PM',
    eventId: 'd66b5060-2f21-4feb-a6f2-ce8660110346'
  },
  {
    id: '841b1847-85a3-42ae-bad5-ba05daf8e638',
    date: 2021-01-01T03:53:00.000Z,
    isOccuringFirst: true,
    startTime: '4:53 AM',
    endTime: '5:53 AM',
    eventId: 'ec7bae12-22aa-4d45-969b-e11a4899fa9e'
  },
  {
    id: '6d089ee5-43f2-4bf0-88cd-f8e8cdbfea34',
    date: 2020-12-16T10:54:00.000Z,
    isOccuringFirst: true,
    startTime: '5:54 AM',
    endTime: '11:54 AM',
    eventId: '8ed719b6-5096-4aa1-8656-b902d46687de'
  },
  {
    id: '10f28e20-7e19-45b3-8c9c-d0fdb6f64e66',
    date: 2020-12-04T07:01:03.559Z,
    isOccuringFirst: true,
    startTime: '1:00 PM',
    endTime: '4:00 PM',
    eventId: '3375cdb0-6197-4e34-8ddf-a0c2316c5c12'
  },
  {
    id: '3f3c48b6-ab50-412a-802a-6e7f30943614',
    date: 2020-12-04T07:10:02.627Z,
    isOccuringFirst: true,
    startTime: '10:24 AM',
    endTime: '6:24 AM',
    eventId: 'a5fc4601-10d1-4cd8-98db-2c969cce5127'
  }
]
```

Then my query is

```js
// new Date().toISOString() =>  2020-12-04T07:07:30.514Z
  const _dates = await eventDate.findMany({
    where: {
      date: new Date().toISOString(),
    },
  })

```
`_date` should at least match the last two objects in the above result since is still in the range of  `2020-12-04`
 but instead is empty `[]` but... if I omit `.toISOString()`, the entire results will be fetched which is not desired, changing the Prisma type from `DateTime` to `String` and using the query 
```js
...
    where: {
      date: {
        contains: new Date().toISOString(),
      },
...
```
seems to solve this problem, but why's Prisma looking up `DateTime` in strict mode? at least

**Comment by pantharshit00** [comment]
Sorry for the late reply here.

@navicstein 

If you want to filter via dates, you will need to use the date native type. By default `DateTime` maps to `timestamp(3)` in the database which has millisecond precision in match and storing. If you just want to filter, use the `Date` native type like so(native types are in preview):

```prisma
model Event {
  id              String   @id @default(uuid())
  date            DateTime @db.Date
  isOccuringFirst Boolean
  startTime       String
  endTime         String
}

```

![image](https://user-images.githubusercontent.com/22195362/103101613-76cd1300-463e-11eb-84bc-5849b925745b.png)



Now regarding your issue @maoosi. I can confirm that as a bug in our JS validator for dates. 

Here is our date handling code: https://github.com/prisma/prisma-engines/blob/9a901beeaa4d52b23483c02dc9803aadb56f0e28/libs/prisma-value/src/lib.rs#L208 . This looks alright but the JS code doesn't seem to have a proper validator. I think our regular expression is wrong here: https://github.com/prisma/prisma/blob/557aaaddae6c826c0b01fa282d0a28df2fa1011d/src/packages/client/src/runtime/utils/common.ts#L195



Reproduction:
```ts
import { PrismaClient } from "@prisma/client";
import { formatRFC3339 } from "date-fns";

async function main() {
  const prisma = new PrismaClient();
  const _dates = await prisma.event.findMany({
    where: {
      date: formatRFC3339(new Date()),
    },
  });

  console.log(_dates);

  prisma.$disconnect();
}

main();
```

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by maoosi** [comment]
Awesome, thanks!

**Comment by ArcticSpaceFox** [comment]
`new Date().toISOString()` gives me an error stating:
```
Invalid `prisma.user.update()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("22P03"), message: "incorrect binary data format in bind parameter 1", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("postgres.c"), line: Some(1772), routine: Some("exec_bind_message") }) }) })
```

I use prisma with the postgres connector, all up-to-date. Should we format it differently? Docs wheren't to helpful on that

**Comment by pantharshit00** [comment]
@ArcticSpaceFox Please open a new issue with minimal reproduction. This seems unrelated.

**Comment by sandbox-apps** [comment]
I have encountered this issue in prisma 3.0.1? anyone? Im coding with flutter

where my inputs are:
```dart
startDate: DateTime.now().toIso8601String(),
endDate: DateTime.now().toIso8601String(),
```

and outputs in prisma are:
Argument startDate: Got invalid value '2021-09-18T00:39:47.933274' on prisma.createSomething. Provided String, expected DateTime.

Argument endDate: Got invalid value '2021-09-18T00:39:47.936671' on prisma.createSomething. Provided String, expected DateTime.


**Note that I'm passing an ISO8601 string from dart into prisma.**

Can we reopen this?

**Comment by sandbox-apps** [comment]
I also did my validation in my code via npm package `class-validator` and check if my input has passed ISO8601 format and it passed

**Comment by xbtchunky** [comment]
Can confirm `.toISOString()` is not working for me.

datetimeString: '+054598-05-15T03:46:02.244Z'

[2022-08-18 02:48:44] PrismaClientValidationError: Argument inserted_at: Got invalid value '+054598-05-15T03:46:02.244Z' on prisma.createOnetest. Provided String, expected DateTime or Null.

**Comment by glarivie** [comment]
Same problème for me ✋ 

```
Error:
Invalid `prisma.update()` invocation:
Got invalid value '2023-03-15T16:29:56+0000'. Provided String, expected DateTime.
```

But `2023-03-15T16:29:56+0000` is a valid ISO 8601 date string. With `new Date("2023-03-15T16:29:56+0000").toISOString()` I got `2023-03-15T16:29:56.000Z` and `update()` works.

**Comment by lucashfreitas** [comment]
Should be simple to deal with native `Date` objects without having to deal with `DateTime` object and timezone constraints. Most of the ORMs support passing just a `dd-mm-yyyy` or `yyyy-mm-dd` for that, so no issues with timezones.

This issue is opened for over 3 years, so we need to understand that Prisma team might be busy with other high-priority tasks - is not easy to maintain an amazing open source library for this - so massive thanks.

For whoever is looking for alternatives - we had to mess with timezones (`TZ` env variable, or convert the `dd-mm-yyyy` to date for specific timezones and we had  problems), so we have migrated all queries that deal with that to use https://github.com/drizzle-team/drizzle-orm - it has a fantastic type support and developer experience and it's useful to deal with cases where prisma doesn't support native stuff.

**Comment by Sublimetext2264** [comment]
@maoosi https://phps.space/questions/retrieving-data-within-specific-date-boundaries

**Comment by sergiofra98** [comment]
I found a way to do multiple dates similar to:

`
      const remainingOrderItems = await this.prisma.client.orderItem.findMany({
        where: {
          dispatchDate: { in: merchantOrderItemsFilters.dispatchDates },
        },
      })
`

Just use OR instead, im compensating for timezones in this example

`
      const remainingOrderItems = await this.prisma.client.orderItem.findMany({
        where: {
          OR: merchantOrderItemsFilters.dispatchDates.map((date) => ({
            dispatchDate: {
              gte: new Date(new Date(date).setUTCHours(5, 0, 0, 0)),
              lt: new Date(new Date(date).setUTCHours(29, 0, 0, 0)),
            },
          })),
        },
      })
`
