### ISSUE TITLE
Native Types support in Prisma migrate

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/prisma#4330]
## Problem

The new Native Types notation is missing a way to use migrate so that users can define the native type from the Prisma schema and propagate the change down to the database level. This should be made possible in the context of the new `migrate` planned to be released in Preview later this year.

## Suggested solution

Ensure that running prisma migrate with a schema defining specific native types does generate a migration using the corresponding database types.

**Comment by albertoperdomo** [comment]
Prisma Migrate supports native types (in Preview) since 2.15.0. Closing.
