### ISSUE TITLE
$connect doesn't throw error on mysql connector if database is not reachable

### ISSUE THREAD

**Issue by vh13294** [prisma/prisma#4335]
## Problem

I am trying to generate million of rows of database seeders.
I would like to have a way to test connection before creating data to avoid unnecessary error message.

## Suggested solution

Perhaps something like this:

```typescript
try {
        await prisma.$connect()
} catch (error) {
        throw error
}
```

I tried to look in official docs for away to test connection, but found none.

"prisma.$connect()" doesn't trigger error if the DB is offline.

## Version
"@prisma/client": "^2.11.0"

Database: mysql:8

**Comment by pantharshit00** [comment]
Hey @vh13294 

I am unable to reproduce this problem in the 2.11 version. 

![image](https://user-images.githubusercontent.com/22195362/99982177-44768e80-2dd0-11eb-950a-5d7c0510630b.png)

Can you please share where your database is hosted and can you please absolutely make sure that it is offline while you are trying to connect to it.

**Comment by vh13294** [comment]
here is the code

```typescript
import { PrismaClient } from '@prisma/client'
import { customerSeeder } from './script/customer.seeder'

async function main() {
    const prisma = new PrismaClient()

    try {
        await prisma.$connect()
    } catch (error) {
        throw error
    }

    await prisma.$disconnect()
    console.log('seeders generated')
};

main()
```

**Comment by pantharshit00** [comment]
Hey @vh13294 

I am still unable to reproduce this with 2.12. Can you please try again with that? Also, can you please screenshot of error returned by Promise.all call, that doesn't seem alright.

**Comment by vh13294** [comment]
I have a repo with reproducible error.
https://github.com/vh13294/nestjs-inventory

-Instruction 
 -npm install
 -ts-node prisma/seeders/main.seeder.ts

Here is the screenshot of error message
<img width="1354" alt="Screen Shot 2020-12-03 at 8 55 20 PM" src="https://user-images.githubusercontent.com/17086745/101026893-09334700-35aa-11eb-955b-8f54dc6c946b.png">

**Comment by pantharshit00** [comment]
Hey @vh13294 

Looks like this is specific to mysql connector. I can reproduce this in mysql while I can't reproduce this with postgresql. 

Reproduction: https://github.com/harshit-test-org/prisma-issue-4335

I have updated the title to reflect this is specific to mysql. Please include the database version and name in the bug reports from now :pray:

**Comment by vh13294** [comment]
@pantharshit00

Sorry about that I opened this issue as feature request that’s why did not include lots of extra information.

But later, as it turned out to be a bug.

**Comment by pantharshit00** [comment]
I will keep this open for us to investigate.
