### ISSUE TITLE
prisma export not working against remote environment

### ISSUE THREAD

**Issue by flemmingpoulsen** [prisma/prisma#4337]
**Describe the bug**
When i try to run prisma export locally against my own instance. My zipped export gets generated correctly.
Hovever when i try to export from our stage environment i get the following errors:

`ENAMETOOLONG': spawn ENAMETOOLONG`

Some of our data seems to be outputtet into my console and it also seems that i do manage to get some data placed into my .export folder - so it starts out working, but then fails along the way - I cannot see what makes it fail though. The error dosn't make it any clearer.

I find it difficult to debug what happens, because i dont get any more information from Prisma than this.

**To Reproduce**
1. Change my environment file to point to the remote environment
2. run the export command (`prisma export -p mydata.zip`)
3. Wait for `Downloading nodes` to appear and stop working with a red `!` in front.

**Expected behavior**
Expected the export to work the same way as it does locally and create a zip-file for me.

**Screenshots**
The error that occours (theres quite alot of our data which gets outputtet above as well):
![Capture_download_nodes](https://user-images.githubusercontent.com/49432702/55787071-c4de6380-5ab5-11e9-81ca-ea9e5e8fb0ac.PNG)

The amount of data in our nodes, where each line is representing how many of each object-type we got:
![data-set-size](https://user-images.githubusercontent.com/49432702/55787216-18e94800-5ab6-11e9-88ad-c4c73a686f0f.png)

**Versions:**
 - Connector:  `MySQL`
 - Prisma Server: [e.g. `1.28.0`]
 - `prisma` CLI:  prisma/1.28.0 node-v10.13.0`]
 - OS: [`Windows 10`, `MacOS` ] 

**Additional context**
Help 😭

**Comment by pantharshit00** [comment]
Can you share the names of your types? Looks like the CLI tries to write a file with a big name.

**Comment by flemmingpoulsen** [comment]
The issue somehow resolved itself today. I still don't know why it didnt work - It must be related to our specific setup then is my guess.

Thanks though @pantharshit00
