### ISSUE TITLE
Migrating data stored as Json[] in 2.12.0

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4346]
From the [Release Notes](https://github.com/prisma/prisma/releases/tag/2.12.0):

> We fixed how the `Json[]` type is stored in `2.12.0`. Previously we were storing JSON arrays as a string inside a your database's `json` column. Now we properly encode JSON arrays as `json` in the database. This fix will allow us to add database native JSON operations down the line.
>
> If you are using the `Json[]` type in your schema, you'll need to migrate your data. We anticipate this breaking change will only affect a handful of folks. Please reach out to us in this issue and we'll help you with the migration.

If you're one of these unlucky folks, please post your schema here and we'll try to help you migrate.

**Comment by ethansmith91** [comment]
@matthewmueller is there an instruction on migrating the database here? We are the unlucky folks and this has been quite frustrating
