### ISSUE TITLE
CLI: prisma deploy -p [prisma.yml path] prohibits specified env-file with -e [.env path] argument

### ISSUE THREAD

**Issue by Killuah15** [prisma/prisma#4349]
**Describe the bug**
Deploying a prisma service from a different folder via a cli command like `prisma deploy -p ../prisma/prisma.yml -e ../.env` will not load the env-file specified by the -e flag.

**To Reproduce**
1. Get a simple prisma project up and running
2. In the prisma.yml define `secret: ${env: PRISMA_SECRET}`
3. Create a .env file in your project with the value `PRISMA_SECRET=12345`
4. Go into any other folder which is not the one with the `prisma.yml` in
5. Use `prisma deploy -p [relative path to prisma.yml] -e [relative path to .env file]`
6. A `"A valid environment variable to satisfy the declaration [...]"` Warning should appear

**Example**
```
Workspace/
├── .env
├── src/
└── prisma/
    ├── prisma.yml
```
In a folder structure like this, calling prisma deploy from inside `src/` would be:
`prisma deploy -p ../prisma/prisma.yml -e ../.env`

**Expected behavior**
Use the prisma.yml specified by the -p flag in conjunction with the env-file specified by the -e flag

**Screenshots**
![grafik](https://user-images.githubusercontent.com/18482238/55877872-70adaf00-5b9b-11e9-82b9-27e163426902.png)
![grafik](https://user-images.githubusercontent.com/18482238/55877835-5bd11b80-5b9b-11e9-87fc-d8a3d1f21a58.png)

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.29`
 - `prisma` CLI: `prisma/1.30.0 (windows-x64) node-v10.15.0`
 - OS: `Windows 10`

**Additional context**
`cd` into the same folder with `prisma.yml` and then using `prisma deploy -e [relative path to .env file]` works fine.

**Comment by Fabiomad85** [comment]
I have the same behaviour

**Comment by divyenduz** [comment]
Closing this in favor of https://github.com/prisma/prisma/issues/4419 as that has more information and a workaround. Please open a new issue if you think that these issues are separate.
