### ISSUE TITLE
Error on single embedded type

### ISSUE THREAD

**Issue by EfrenSanchez** [prisma/prisma#4353]
Using create for @embedded type is throwing the following error: 
` "Argument 'data' expected type 'PlayerCreateInput!' but got: ... " `

**To Reproduce**

1. Deploy a new prisma server with the following datamodel:

```
type Player {
  id: ID! @id
  nick: String!
  shirtNumber: Int!
  personalInfo: PersonalInfo
}

type PersonalInfo @embedded {
  name: String!
  lastName: String
}
```

2. Run the following mutation

```
mutation {
  createPlayer(
    data: {
      nick: "Tom"
      shirtNumber: 0
      personalInfo: {
        create: {
          name:"Tommy"
          lastName:"Nabo"
        }
      }
    }
  ) {
    id
    nick
    shirtNumber
    personalInfo {
      name
      lastName
    }
  }
}
```

3. See the error

**Expected behavior**
It should not throw an error.

**Screenshots**

![Captura de pantalla 2019-04-10 a las 16 59 27](https://user-images.githubusercontent.com/42469009/55889965-30a5f680-5bb2-11e9-9df1-9b26f02f8171.png)

**Versions (please complete the following information):**
 - Connector: MongoDB
 - `prisma` CLI: 1.30.0 (darwin-x64) node-v11.9.0
 - OS: OS X High Sierra
 - other dependencies: `prisma-binding`, `graphql-yoga`

**Additional context**
If I create a player without  an @embedded type, works!

![Captura de pantalla 2019-04-10 a las 17 05 41](https://user-images.githubusercontent.com/42469009/55890386-e96c3580-5bb2-11e9-819c-4cebe54a371c.png)

**Comment by divyenduz** [comment]
@EfrenSanchez Is this your latest datamodel? The error message suggests that there is a required field `position` of type `PlayerPosition` that is not provided, maybe you did a deploy and did not reload the playground. Can you please confirm?
