### ISSUE TITLE
deploy has no effect

### ISSUE THREAD

**Issue by kgoggin** [prisma/prisma#4355]
**Describe the bug**
Running `prisma deploy` does not actually update the service, although the logging indicates that it has performed changes successfully.

Specifically, I'm deploying changes in my data model to an existing service. I've applied these changes locally to a Prisma instance running in Docker with no issue, and to my dev server (hosted in AWS). When deploying to my production server (a clone of the dev server, also in AWS), the deployment _appears_ to run successfully, but then the server has not actually been updated (verified via the admin console as well as looking at the schema in Playground). 

There are no error messages displayed during the deployment, and each subsequent try to deploy acts as though it's running the same deployment again (as if it'd never been tried before). Even Prisma Cloud shows all my attempts to deploy in the deployment log, with all of the changes that should have run, as if they actually happened.

**To Reproduce**
I'm not sure of a specific way to reproduce. As I mentioned, the exact same changes worked fine locally and on my development server just fine. I've made other deployments to the prod server that worked fine. It seems like this specific one just isn't working for some reason.

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server: 1.29.2
 - `prisma` CLI: 1.29.2
 - OS: running in CI in the official Node 8.11.2 Docker image
 - other dependencies: N/A

**Additional context**
This sounds identical to the problem described here: https://www.prisma.io/forum/t/prisma-deploy-does-not-deploy-and-does-not-show-any-errors/6559. Note that I'm not able to deploy to a new instance (as suggested in that thread) - I'm trying to update my production DB with existing data, so I really need to figure out how to make this work.

**Comment by divyenduz** [comment]
Maybe your deployment is rolling back: https://github.com/prisma/prisma/issues/4351

But you don't see it. If you have access to your database, you should have a `prisma` database in it that has a `Migration` table, look for last few migrations on this project and see if they are a success or in some other state.

**Comment by johnthepink** [comment]
@divyenduz I think this was what @kgoggin and I were seeing. I added some more information over on #4351.

**Comment by divyenduz** [comment]
@kgoggin : Were you able to find the underlying error in `migrations` table?

**Comment by johnthepink** [comment]
@divyenduz we didn't look at the `migrations` table, and we have since cleared that database. But, that is good to know for the future. I added the details we found over on #4351, so this one can probably be closed. Thanks for your help!

**Comment by divyenduz** [comment]
Thanks for informing us.

**Comment by junweipan** [comment]
I run 'prisma delete', and run 'prisma deploy' again, the graphql updated
