### ISSUE TITLE
Postgres Non Super User Connection

### ISSUE THREAD

**Issue by smojtabai** [prisma/prisma#4356]
**Describe the bug**
I created a database on RDS with postgres. When I connect with the admin user created by AWS everything works fine. When I created another user so I don't use the admin user, I get:

Exception in thread "main" org.postgresql.util.PSQLException: ERROR: permission denied for database prisma

Even though I can connect with that user to that DB and run queries against default$default

**To Reproduce**
Create AWS RDS Postgres and create another user with following commands:
CREATE ROLE services_role; 
GRANT USAGE ON SCHEMA "default$default" TO services_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "default$default" TO services_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "default$default" TO services_role;
create user test with encrypted password 'test';
GRANT services_role TO test;

Now I can connect to the db with that user however prisma running on Heroku gives me the error stated in the description.

**Expected behavior**
I should be able to connect.

**Screenshots**

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: Installed on heroku, not sure how to check
 - `prisma` CLI: prisma/1.27.4 
 - OS: OS X High Sierra
 - other dependencies:  None

**Additional context**

**Comment by pantharshit00** [comment]
Hi @smojtabai 

You will also need to provide that access to the management schema in addition to the default$default schema as prisma will require that schema to store the migration metadata and other additional information

**Comment by smojtabai** [comment]
@pantharshit00 great find. However I added the following to the role:

GRANT USAGE ON SCHEMA "management" TO services_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "management" TO 
Services_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "management" TO services_role;

And I still get the:

Exception in thread "main" org.postgresql.util.PSQLException: ERROR: permission denied for database prisma

Although I can connect manually and view both management and default$default tables, thanks in advance for any other advise

**Comment by smojtabai** [comment]
I figured it out, this likely has more to do with my lack of understanding of permissions of postgres but this gets it to work:

CREATE ROLE services_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "default$default" TO services_role;
GRANT ALL PRIVILEGES ON SCHEMA "default$default" TO services_role;
GRANT USAGE ON SCHEMA "default$default" TO services_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "default$default" TO 
services_role;
GRANT CREATE ON DATABASE prisma TO services_role;
GRANT USAGE ON SCHEMA management TO services_role;
GRANT ALL PRIVILEGES ON SCHEMA "management" TO services_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "management" TO 
services_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "management" TO services_role;
