### ISSUE TITLE
Rename findOne in dmmf.schema.outputObjectTypes.prisma Query

### ISSUE THREAD

**Issue by AhmedElywa** [prisma/prisma#4358]
There is one place you need to rename findOne in it.

in `dmmf.schema.outputObjectTypes.prisma` path `Query` object type

![image](https://user-images.githubusercontent.com/4535142/100225822-7b12ed00-2f27-11eb-871b-577d8b1b5df7.png)

**Comment by dpetrick** [comment]
This is solved not via rename but a dedicated protocol-level deprecation mechanism. Protocol change is included in 2.14.
