### ISSUE TITLE
[Documentation-tutorial] Add testing!!!

### ISSUE THREAD

**Issue by guledali** [prisma/prisma#4359]
When I started using GraphQL in my NodeJS project, I struggle with writing tests: I read numerous blogs, searching for the best way. Unfortunately, there didn't seem to be one until I came across this one [EasyGraphQL](https://easygraphql.com/) 

It would be nice if someone would add this to the tutorial section https://www.prisma.io/tutorials 
**How to test your query and mutation and mocking up the response**

**Comment by pantharshit00** [comment]
cc @etelsv

**Comment by guledali** [comment]
1. Having a single tutorial on testing would be nice and helpful but,
2. Consider also making a tutorial on TDD **(red green refactor)**
