### ISSUE TITLE
Prisma init workflow with MongoDB does not introspect

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4361]
**Describe the bug**
`prisma init` workflow with MongoDB does not introspect. 

**To Reproduce**
1. Run `prisma init` and choose existing mongo options, you will always get the default datamodel. 

**Expected behavior**
Prisma init workflow should introspect existing MongoDB

**Versions (please complete the following information):**
 - Connector: `MongoDB`
 - Prisma Server: `1.30`
 - `prisma` CLI: `1.30`

**Comment by 1jerry** [comment]
My workaround: after init but _before_ docker-compose

1. change docker-compose.yml:  change "schema" to "database"
1. now run the docker-compose command 
    1. make sure to stop any previous dockers you just created first
1. _now_ run prisma introspect
1. then run prisma deploy
