### ISSUE TITLE
Hint for codemod should highlight command in backticks and/or colored

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#4373]
Right now we print a hint that people can update their code using the codemod:

![image](https://user-images.githubusercontent.com/4058327/100333001-5d4e9200-2fd2-11eb-9012-6bc615fb0339.png)

I suggest to either:

- add backticks to the suggested command \`npx @prisma/codemods update-2.12 ./`
- color the suggested command so that it stands out a bit more, e.g. in green

We could also consider doing both.

**Comment by timsuchanek** [comment]
We already use colors, so for some reason the color is not visible in your case.
We can just add backticks additionally to make it work in non-color environments.
Action items:
- [ ] Put the `npx` command in new line - easier to copy
- [ ] Add backticks
