### ISSUE TITLE
Prisma generate and post-deploy hook throws an error 

### ISSUE THREAD

**Issue by ahrbil** [prisma/prisma#4374]
**Describe the bug**
Running Prisma generate or when Prisma finishes deployment and running post-deploy hook 
it throws an error and not generates Prisma client or Prisma graphql schema 

**To Reproduce**
run `prisma generate` command or through post-deploy hook

**Expected behavior**
it should generate a pirsma client in specified languages and downloads Prisma graphql schema
**Screenshots**
![Annotation 2019-04-13 210626](https://user-images.githubusercontent.com/16563523/56084776-61975d00-5e38-11e9-99b0-7f9b6ca25cf8.jpg)
**Versions :**
 - Connector: Postgres`
 - Prisma Server: 1.30.1
 - `prisma` CLI: 1.30.1
 - OS: Windows 10

**Additional context**
I tried downgrading to Prisma 1.29.2  things started working as expected,
even 1.30.0 still has this issue for me

**Comment by chanlito** [comment]
@ahrbil I'm using the 1.30 `prisma generate` runs fine for me. Maybe check you should check your code further.

**Comment by ahrbil** [comment]
@chanlito I'm installing Prisma as a dev dependency and that's where the error came 
if I installed it globally it works fine

**Comment by pantharshit00** [comment]
Hi @ahrbil. This looks like a classic graphql version inconsistency issue.

If you are using yarn, you can solve it by adding a resolutions field in your package.json like so:

```json
{
  "resolutions": {
    "graphql": "14.2.1"
   }
}
```

After adding this remove your node_modules and run yarn again.

If you are using npm, try running `npm ls graphql` and check for different versions of graphql(Note that `v0.13.x` is not compatible with `v14.x`). If there is any inconsistency try to pin graphql in your package.json by `npm i graphql@14.2.1`

**Comment by ahrbil** [comment]
@pantharshit00 thank you
