### ISSUE TITLE
1.31.0-beta.5 Forcibly ads createdAt & updatedAt fields.

### ISSUE THREAD

**Issue by Flash619** [prisma/prisma#4382]
**Describe the bug**
Every model is forced to have createdAt and updatedAt fields, even though they are not defined within the data model.

**To Reproduce**
1. Create a data model without createdAt and/or modifiedAt.
2. Run `prisma deploy`
3. Check the database.
4. Both fields exist, the logs show they were added by Prisma during deploy.

**Expected behavior**
If createdAt or modifiedAt are not defined, they should be excluded from the generate database table.

**Screenshots**
![image](https://user-images.githubusercontent.com/1608113/56181679-23cf3b80-5fd4-11e9-9ab9-92e9830ff867.png)
![image](https://user-images.githubusercontent.com/1608113/56181691-36e20b80-5fd4-11e9-90f2-a099837f76a6.png)

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma: 1.31.0-beta.5
 - Node: v10.15.3
 - OS: Windows 10

**Comment by Flash619** [comment]
I was able to somewhat fix the above issue by specifying the prototype flag. However I now have an issue where I cannot remove the updatedAt/createdAt fields on any models even when running `deploy` with `force`.

![image](https://user-images.githubusercontent.com/1608113/56260161-be468200-609b-11e9-8d5e-5181c08c5d77.png)

**Comment by pantharshit00** [comment]
@Flash619 

I can no longer reproduce this with the new datamodel.
![image](https://user-images.githubusercontent.com/22195362/56469025-bd25a400-6451-11e9-86ae-cb5924019d1b.png)


You are getting that warning as you are upgrading to the new datamodel(there is no longer a prototype flag now as it is in the stable release now 1.31). New datamodel allows you to specify the createdAt and updatedAt field's names(See https://github.com/prisma/prisma/issues/3403)

**Comment by Kisepro** [comment]
@Flash619 Same problem, have you found a solution ?

**Comment by Flash619** [comment]
> @Flash619 Same problem, have you found a solution ?

I don't fully recall, I know I did fix it. 

I think I had gone through and made sure everything was on the latest (same) beta Prisma version, and I had to enable the 'prototype' flag in the docker-compose file. However, the prototype flag should no longer be required based on @pantharshit00 comment.
