### ISSUE TITLE
Issue with not closing DB connections

### ISSUE THREAD

**Issue by 15chrjef** [prisma/prisma#4393]
## Bug description

I have a heroku free tier DB and it looks like Prisma is not ending connections after making calls to the hosted DB on heroku.

I am only using my app in basic development, and have never experienced any problems with too many connections, however, now I experience this error every few errors, and it persists even after killing all connections manually.

```
"[GraphQL]  Invalid  invocation:     Error querying the database: db error: FATAL: too many connections for role 
```
## How to reproduce

1. Create Heroku free tier postgresql DB
2. Make some queries involving joins across a few tables
4. See error of max connections being reached

## Expected behavior

DB connections should be killed after requests are complete

## Environment & setup

- OS: MacOs
- Database: PostgreSQL
- Node.js version: v12.10.0
- Prisma versions:
@prisma/cli          : 2.11.0
@prisma/client       : 2.11.0

```

```

**Comment by dayvista** [comment]
I am having this same issue running localhost and querying a Postgres database hosted on DigitalOcean. The error that I receive is:

`Invalid `prisma.user.findMany()` invocation:


  Error querying the database: db error: FATAL: remaining connection slots are reserved for non-replication superuser connections
`

Not sure if this issue will persist into production - it could be related to how localhost and Prisma interact.

**Environment/Setup**
OS: Windows 10
Database: PostgreSQL
Node.js version:  12.19.0
Prisma version:  2.12.0 (@15chrjef mentions being on version 6.x.x - not sure if that's referencing a different library or what)

**Comment by 15chrjef** [comment]
Thanks for adding to this @dayvista! Updated my Prisma versions for clarity.

**Comment by dayvista** [comment]
No problem @15chrjef, glad to see I'm not alone with this issue. I'm also getting a message in the console akin to "Warning: 10 Prisma Clients are already running" after using the dev server for a while. (don't remember the message exactly - I'm away from my computer at the moment).

**Comment by 15chrjef** [comment]
Likewise @dayvista! I have spoken to another dev who also is experiencing this issue on Prisma2. FWIW After updating my Prisma version to 2.12.1, I can also confirm that this issue persists onto Prisma version 2.12.1.

**Comment by kunalgorithm** [comment]
I'm having this error against a hosted postgres instance on Render, as well. It's consumed all 100 connection slots and prevents new connections from being created. 

The error has happened with prisma `2.11.X` and `2.12.1` on various different postgres instances, in development and production.

**Comment by Sytten** [comment]
Are you sure you don't create a client per request by any mean? 
Never seen this issue before unless the dev was recreating the client over and over.

**Comment by 15chrjef** [comment]
@Sytten I am quite sure, but willing to be proven wrong.

My Prisma setup has not changed recently, I only started seeing this issue 3 days ago in a repository I have been using for around a month.

The two files related to creating a prisma client are attached below. I don't see how multiple clients could be getting created.

context.ts
```
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export interface Context {
  prisma: PrismaClient;
}

export function createContext(): Context {
  return { prisma };
}
```

graphql.ts
```
import { ApolloServer } from 'apollo-server-micro';

// we'll create these in a second!
import { schema } from '../../graphql/schema/schema';
import { createContext } from './../../graphql/context';

const apolloServer = new ApolloServer({
  context: createContext,
  schema,
  tracing: process.env.NEXT_PUBLIC_NODE_ENV !== 'production'
});

export const config = {
  api: {
    bodyParser: false
  }
};

export default apolloServer.createHandler({
  path: '/api/graphql'
});
```

**Comment by dayvista** [comment]
@Sytten I am actually creating multiple clients in my app, although only 2 or 3 in the whole codebase. 

Does the use of multiple clients somehow create a loop that creates more clients or fails to destroy used ones? Is there a function/hook I should be running to kill unused clients?

Forgive any ignorance on my part, I'm fairly new to Prisma.

**Comment by mavilein** [comment]
Hey all 👋 ,
thanks for reaching out to us! With free/cheap tiers on any provider you probably need to set the `connection_limit` parameter in your connection string correctly. Have you read and applied this [article](https://www.prisma.io/docs/concepts/components/prisma-client/deployment#setting-the-connection-limit-of-the-prisma-query-engine) from our docs?

**Comment by 15chrjef** [comment]
Hi @mavilein!

Thank you for responding here!

I am using a free DB at the moment with a connection limit of 20.

However, even after taking your advice and updating the DB URL that Prisma uses with a postfix of connection_limit=10, I am still getting this error of too many connections.

I also know @kunalgorithm has a DB instance with a connection limit of 100 but also has a similar issue.

Is there a certain amount of DB connections that you think is required to avoid this problem?

**Comment by Sytten** [comment]
I would say 20 is enough, but you do need to make sure they are closed if you do an auto-restart on your dev machine unless you have many cores (connections = num_physical_cpus * 2 + 1).
Creating a few clients might also be problematic depending on the formula above.
But if this is a new issue, it should be investigated. I upgraded one of my client's installation the other day and didn't notice anything special, @pantharshit00 care to try to reproduce?

**Comment by 15chrjef** [comment]
Thank you ,@Sytten. 

I manually kill all of my connections every half an hour or so as that is how often I get a 'too many connections error'.

**Comment by pantharshit00** [comment]
I was unable to reproduce this. Can you please check from the heroku UI on how many connections are getting used? You can see that under the utilization section of your heroku database dashboard

Also, if you share the actual client call which is causing this, that might also help here.

**Comment by 15chrjef** [comment]
Hi @pantharshit00, here is the Heroku UI for my instance.

![image](https://user-images.githubusercontent.com/18706329/100769559-3923f400-33ca-11eb-802c-c148446d79e1.png)


Here is the network Call
<img width="961" alt="Screen Shot 2020-12-01 at 11 46 12 AM" src="https://user-images.githubusercontent.com/18706329/100770172-fa426e00-33ca-11eb-8d43-51410cc197f0.png">

**Comment by dayvista** [comment]
After adding `?connection_limit=1` to the end of my database string, I am also still getting this error. Here's a screenshot of my database at the moment I received the error:
![Screenshot 2020-12-01 160634](https://user-images.githubusercontent.com/58375683/100807297-0e549280-3400-11eb-93b9-6c78645e246e.png)
Could this be occurring because I'm instantiating 3 Prisma clients in total? That doesn't seem to be the case after implementing the 'connection limit' and seeing @15chrjef and @kunalgorithm experience the same issue under different circumstances. Also, 3 < 22 😅

**Comment by dayvista** [comment]
Also of note is the fact that the DB logs showed around 20 queries being made at the same moment right before the error hit. (unfortunately didn't get a screenshot at the time)

**Comment by Sytten** [comment]
We have to identify if it's a rust issue or a TS issue, can you check if new processes are created? It should have the name query-engine-<YOUR_SYSTEM>. I had instances where the engine didn't want to get killed. If the number of process is sane that means there is a bug in the engine, in which case @mavilein can take over,

**Comment by 15chrjef** [comment]
@Sytten I have 11 instances running on my local machine, and a max_connections limit of 2 on the DB URL, and my Heroku instance only allows for 20 connections. Not sure if that is the information you were looking for.

<img width="718" alt="Screen Shot 2020-12-01 at 10 04 54 PM" src="https://user-images.githubusercontent.com/18706329/100822951-57690e80-3421-11eb-905a-a234169e7d2d.png">

**Comment by Sytten** [comment]
Yes this indicates that the TS code spawns a lot of instances causing the max connection. I would consider moving the code that creates the prisma client to a separate file and export only one instance that is always used. If this fixes the issue that means your implementation was leaking PrismaClient for some reason.

**Comment by 15chrjef** [comment]
@Sytten. I was under the impression that my implementation was already following the rules you outlined of moving the prisma client to a separate file and export only the instance that is used. Do you disagree?

context.ts
```
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export interface Context {
  prisma: PrismaClient;
}

export function createContext(): Context {
  return { prisma };
}
```
graphql.ts

```
import { ApolloServer } from 'apollo-server-micro';

// we'll create these in a second!
import { schema } from '../../graphql/schema/schema';
import { createContext } from './../../graphql/context';

const apolloServer = new ApolloServer({
  context: createContext,
  schema,
  tracing: process.env.NEXT_PUBLIC_NODE_ENV !== 'production'
});

export const config = {
  api: {
    bodyParser: false
  }
};

export default apolloServer.createHandler({
  path: '/api/graphql'
});
```

**Comment by Sytten** [comment]
Not really, but you do seem to have an issue that has been historically linked to having multiple clients created. So I thought it would be worth a shot. Do the engine processes die when you stop your server? What are you using to hot reload the server?

**Comment by 15chrjef** [comment]
@Sytten The processes do die when I stop the server. I use `next` for development.

**Comment by Sytten** [comment]
Check the issue I linked I think this relevant for use case with next

**Comment by 15chrjef** [comment]
Looks like it, thanks!

**Comment by oliviermtl** [comment]
> Check the issue I linked I think this relevant for use case with next
Hi there, I am having the exact same issue. I cannot find the link you mentioned @Sytten

**Comment by timsuchanek** [comment]
We now have a dedicated section in the docs for this situation: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/instantiate-prisma-client#prevent-hot-reloading-from-creating-new-instances-of-prismaclient

Please let me know, if that doesn't solve it for you, then we can reopen this issue.

**Comment by bathientran** [comment]
I've tried to implement the solution above but still get the error. 

I import the following every time I use the prisma client:

`import { PrismaClient } from '@prisma/client';

let prisma = PrismaClient;

if (process.env.NODE_ENV === 'production') {
    prisma = new PrismaClient();
} else {
    if (!global.prisma) {
        global.prisma = new PrismaClient();
    }
    prisma = global.prisma;
}

export default prisma;
`

Anyone got any tips on how this could be fixed?

**Comment by pantharshit00** [comment]
@bathientran Please open a new issue along with your version and minimal reproduction so that we can properly look at it.

**Comment by alaka** [comment]
@bathientran : Have you raised a new issue for this? Were you able to resolve the problem?

**Comment by jeslenbucci** [comment]
Not sure if this will help, but I was having a very similar issue. My database is managed by digital ocean. This issue only happened when I was working locally. The documentation says that the session will terminate once the Node.js process ends. When working locally, my Node.js process was always on. Closing out my terminal fixed the issue and terminated all of the active sessions. 

At least for me, the issue was only persistent working locally because my Node.js process was always running. In a serverless environment, the process should terminate the moment the function has run its course.
