### ISSUE TITLE
Using update operate isn't working in relation model data

### ISSUE THREAD

**Issue by lenLch** [prisma/prisma#4401]
**Describe the bug**
update relational data

**To Reproduce**
here is my data model:
```
type Post @db(name: “posts”) {
id: ID! @id
created_at: DateTime! @createdAt
updated_at: DateTime! @updatedAt
title: String! @unique
content: String!
author: User!
categories: [Category!]! @relation(name: “PostCate”, link: INLINE)
tags: [Tag!]! @relation(name: “PostTag”, link: INLINE)
}

type Category @db(name: “categories”) {
id: ID! @id
name: String! @unique,
posts: [Post!]! @relation(name: “PostCate”)
}

type Tag @db(name: “tags”) {
id: ID! @id
name: String! @unique,
posts: [Post!]! @relation(name: “PostTag”)
}
```

when I using updatePost method, I can change the title and content, but the connect isn't working

```
updatePost: async(parent, { id, title, content, cates, tags }, context) => {
try {
const post = await context.prisma.updatePost({
data: {
title,
content,
categories: { connect: cates },
tags: { connect: tags },
},
where: { id }
})
return post
} catch (err) {
throw err
}
```

**Expected behavior**
change the connect data

**Screenshots**
![1](https://user-images.githubusercontent.com/21274523/56331999-22169b00-61c1-11e9-99fa-3347dbc43e12.png)
![2](https://user-images.githubusercontent.com/21274523/56332002-23e05e80-61c1-11e9-83bc-7fee69c2a5d7.png)

just changed the title and content, the tags and cates were the same

**Versions (please complete the following information):**
 - Connector: [`MongoDB`]
 - Prisma Server: [`1.30.0`]
 - `prisma` CLI: [e.g. `prisma/1.24.0 (darwin-x64) node-v10.4.0`]
 - OS: [`Ubuntu 16.04`]

**Comment by lenLch** [comment]
Today, I saw the documentation is updated today and I check it out. Finally, I found `set`, and it works for me now.
here is the documentation:  https://www.prisma.io/docs/prisma-client/basic-data-access/writing-data-JAVASCRIPT-rsc6/#nested-object-writes

**Comment by pantharshit00** [comment]
Ok, I am closing this issue if it worked.

Reply if this is still persistant
