### ISSUE TITLE
Prisma can't connect to heroku postgres database in production when deployed via vercel

### ISSUE THREAD

**Issue by mathiasklenk** [prisma/prisma#4404]
## Bug description

When I am working locally, everything works fine. I am able to write data to my postgres instance, which is hosted on Heroku. But as soon as I deploy my App to Vercel to prod, and add the`DATABASE_URL` environment variable, it doesn't work and no data is being written to the postgres instance. I first thought it might be related to the environment variable so I started logging it. This is my implementation:

```
import { PrismaClient } from "@prisma/client";
import { Webhook } from "../models/Webhook";

const prisma = new PrismaClient({
  log: ["query", "info", "warn"],
});

export const saveWebhookToDB = async (webhook: Webhook) => {
  console.log("saveWebhookToDB called");
  console.log("Secret: ", process.env.DATABASE_URL);

  await prisma.webhooks.create({
    data: {
      event: webhook.event,
      key: webhook.key,
      status: webhook.status,
      created: webhook.created,
      updated: webhook.updated,
      processed: webhook.processed,
    },
  });

  console.log(`Webhook for key ${webhook.key} saved.`);
};
```

My logs basically show the code stops executing from `await prisma.webhooks.create({` onwards. These are my last logs: 

```
19:43:29:00 [POST] /api/webhooks
saveWebhookToDB called
Secret:  postgres://XXXXX:XXXXXX@XXXXXXXX.eu-west-1.compute.amazonaws.com:5432/XXXXXX
```

So I never reach the last logging statement.

I tried both, the deployment via the Vercel CLI, by adding the secrets like described [here](https://www.prisma.io/docs/guides/deployment/deploying-to-vercel#6-define-vercel-secret-and-expose-to-functions), as well as adding environment variables via the Vercel dashboard. Both lead to the same logging like above, where my App is able to access the correct `DATABASE_URL` pointing to heroku and print it, which makes me believe that something must be wrong with the prisma client. Weirdly enough, I also don't receive an error back that the client or writing failed. Has anyone experienced something similar? Why does this behavior only happen in production not on local development? My postgres instance is default configured, so it can't be IP whitelisting or other stuff. 

## How to reproduce

Try setting up a Next.js App with Prisma and a Postgres instance on Heroku.

## Expected behavior

Correct writing in production like in local development.

## Prisma information

Trying to write to the database and add a row.

## Environment & setup

```
"dependencies": {
    "@material-ui/core": "^4.11.0",
    "@passbase/button": "^3.0.0-rc.11",
    "@passbase/node": "^1.2.3",
    "@prisma/client": "^2.12.1",
    "cors": "^2.8.5",
    "next": "^10.0.3",
    "next-connect": "^0.9.1",
    "pusher": "^4.0.1",
    "pusher-js": "^7.0.1",
    "react": "^16.8.0",
    "react-countdown": "^2.2.1",
    "react-dom": "^16.13.1",
    "react-icons": "^3.11.0",
    "react-is": "^16.8.0",
    "react-lottie": "^1.2.3",
    "styled-components": "^5.1.1"
  },
  "devDependencies": {
    "@prisma/cli": "^2.12.1",
    "@types/node": "^14.6.2",
    "@types/react": "^16.9.49",
    "babel-plugin-styled-components": "^1.8.0",
    "typescript": "^4.0.2"
  },
```

**Comment by mathiasklenk** [comment]
I did more investigation. The problem seems to be related to Vercel. I deployed the same App to Heroku and it seem to have worked now. Suddenly prisma successfully writes to the postgres db which is also hosted on heroku. Leaving this here for others in case they run into the same problem.

**Comment by mleimer** [comment]
@mathiasklenk Did you find a solution and if yes, how?
