### ISSUE TITLE
error TS2694: Namespace '".../node_modules/.prisma/client/index"' has no exported member 'BatchPayload'

### ISSUE THREAD

**Issue by ecpark-danbi** [prisma/prisma#4405]
## Bug description

When I use deleteMany, updateMany. Prisma support type named `BatchPayload` but it has no exported. 

## How to reproduce

1. Make any model, suppose `model Alarms`
2. CRUD model in `@nexus/schema`, `t.crud.deleteManyAlarm();`
3. `tsc --noEmit` or `tsc`
4. `@nexus/schema` generated types
5. Type Error in `BatchPayload: PrismaClient.BatchPayload;`
6. generated PrismaClient has
```
  /**
   * Batch Payload for updateMany & deleteMany
   */

  export type BatchPayload = {
    count: number
  }
```
7. However, I can't import that.

## Expected behavior

```typescript
import * as PrismaClient from ".prisma/client"
```

no error Type namespace with `PrismaClient.BatchPayload`

## Prisma information

```prisma
model Alarm {
  id                Int            @id @default(autoincrement())
  createdAt         DateTime       @default(now())
  updatedAt         DateTime       @updatedAt
  title             String
  contents          String
  important         Boolean        @default(false)
  read              Boolean
  alarmType         AlarmType      @default(ADVERTISEMENT)
  advertisementBy   Advertisement? @relation(fields: [advertisementById], references: [id])
  advertisementById Int?
  notificationBy    Notification?  @relation(fields: [notificationById], references: [id])
  notificationById  Int?
  userBy            User?          @relation(fields: [userById], references: [id])
  userById          Int?
}
```

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: 12.14.0
- Prisma version: 2.12.1
- @nexus/schema: 0.19.2
- nexus-plugin-prisma: 0.25.0

```

```

**Comment by ecpark-danbi** [comment]
I found problem in generated type in `@nexus/schema`

```
--- src/generated/resolverTypes.ts	2020-11-30 12:32:48.000000000 +0900
+++ src/generated/resolverTypes-gen.ts	2020-11-30 12:34:45.000000000 +0900
@@ -23445,7 +23445,7 @@
     user?: NexusGenRootTypes['User'] | null; // User
   }
   Bank: PrismaClient.Bank;
-  BatchPayload: PrismaClient.BatchPayload;
+  BatchPayload: PrismaClient.Prisma.BatchPayload;
   BestBrandGroupStatBoard: PrismaClient.BestBrandGroupStatBoard;
   BestBrandStatBoard: PrismaClient.BestBrandStatBoard;
   Brand: PrismaClient.Brand;
@@ -29340,4 +29340,4 @@
      */
     required?: boolean
   }
-}
\ No newline at end of file
+}
```

**Comment by oliviermattei** [comment]
Can you explain how to use BatchPayload?

**Comment by pantharshit00** [comment]
@oliviermattei `BatchPayload` is the type of result returned by some operations like `deleteMany` or `updateMany`. Its definition is basically the following:
```
  export type BatchPayload = {
    count: number
  }
```

If you looking for some bulk operation api, please follow #3619

**Comment by MaxPiccinno** [comment]
Sorry for necro-posting, I had the same issue and this was the first thread came from google search.

I solved it as follow:
`import {  Prisma } from '@prisma/client'`

then you can reference it as  `Prisma.BatchPayload`.

Problem solved

**Comment by debragail** [comment]
> Sorry for necro-posting, I had the same issue and this was the first thread came from google search.
> 
> I solved it as follow: `import { Prisma } from '@prisma/client'`
> 
> then you can reference it as `Prisma.BatchPayload`.
> 
> Problem solved

nothing wrong with necro-posting - thank you

**Comment by theMogget** [comment]
> Sorry for necro-posting, I had the same issue and this was the first thread came from google search.
> 
> I solved it as follow: `import { Prisma } from '@prisma/client'`
> 
> then you can reference it as `Prisma.BatchPayload`.
> 
> Problem solved

For what it's worth, I find this pretty unintuitive as well. Thank you for posting this!
