### ISSUE TITLE
Support indexing a column partially, i.e. indexing a subset of a text field in MySQL

### ISSUE THREAD

**Issue by chanlito** [prisma/prisma#4414]
## Problem

I'm trying out Prisma new native types feature.

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["nativeTypes"]
}
````

After I introspect the db, I get the following error.

![image](https://user-images.githubusercontent.com/15667259/100601537-4d69e180-3335-11eb-8b72-e1b9b12da7ba.png)

But actually mediumtext can be used as unique if you specify a length to it.

## Suggested solution

Maybe Prisma could support something like the following:

```prisma
model StatusUpdate {
  id         String               @id @db.Char(30)
  uid        String               @unique(191) @db.MediumText
}
```

## Additional context

Prisma 1 `@unique ` uses mediumtext unique with 191 length.

**Comment by kgoggin** [comment]
I ran into this also. Our DB started life with Prisma 1, and so we've got several places where P1 created tables with mediumtext  columns marked as `@unique` that have an index defined that selects a sub part of that field, so that it can be unique:

**Comment by chanlito** [comment]
Any update on this?

**Comment by janpio** [comment]
We are working on better support for index names, which will unblock us to tackle improving index functionality itself.

Here is a super related issue to this one by the way, which uses the official terminology: https://github.com/prisma/prisma/issues/7263

**Comment by do4gr** [comment]
We've just released a proposal for expanded index support in the PSL including index length limits. Please chime in here: https://github.com/prisma/prisma/issues/9577

**Comment by janpio** [comment]
We released support for this in https://github.com/prisma/prisma/releases/tag/3.5.0 - please test it out @kgoggin @chanlito and let us know if this works for you - or not. Thanks!
