### ISSUE TITLE
[Mongo] Count Aggregation Pulls Correct Nodes, Displays Incorrect Node Count

### ISSUE THREAD

**Issue by Shaneprrlt** [prisma/prisma#4414]
**Describe the bug**

This is the first time I'm using the aggregations API, I believe I am doing everything correctly, yet getting 0 back even though I should expect to see 1. The correct list of nodes is coming back though. 

This is my query:

```
query Funnels {
    funnelsConnection(where:{
        shop:{
            id:"5c86a90f24aa9a0008d42d21"
        }
        archived:false
    }) {
        aggregate {
	    count
        }
        edges {
            node {
                id
            }
        }
    }
}
```

This is the response:

```
{
  "data": {
    "funnelsConnection": {
      "aggregate": {
        "count": 0
      },
      "edges": [
        {
          "node": {
            "id": "5ca64a68a7b11b0009cf5687"
          }
        }
      ]
    }
  }
}
````

Clearly `count` should be `1` but is coming back as `0`. Not entirely sure if I'm not using the API correctly or if this is a real bug. Note: Even when I remove the `archived: false` flag, it still returns `0` even though there would be more than 1 node returned in that case. I only experience this issue when querying with an association. 

**To Reproduce**
1. Perform a `count` query on a child resource (Funnel in my case) filtered by a parent resource ID (Shop in my case)

**Expected behavior**
Given the query I've described above, count should be 1. It always returns 0 when filtering by a parent association. 

**Screenshots**

![Screenshot](https://i.imgur.com/nUjyg3D.png "Screenshot")

**Versions (please complete the following information):**
 - Connector: MongoDB
 - Prisma Server: 1.28
 - `prisma` CLI: prisma/1.26.3 (darwin-x64) node-v8.15.0
 - OS: OSX Mojave

**Comment by pantharshit00** [comment]
I was able to reproduce the bug.

![image](https://user-images.githubusercontent.com/22195362/56473223-93867000-6485-11e9-912b-2916dbcc4284.png)


Here is a reproduction: https://github.com/pantharshit00/prisma-issue-4414

cc @do4gr, this issue is specific to mongo, postgres connector doesn't have this issue as seen in the screenshot, maybe use that as a workaround for the time being:
![image](https://user-images.githubusercontent.com/22195362/56473293-b8c7ae00-6486-11e9-84cb-fb192440a4d3.png)

**Comment by do4gr** [comment]
Thanks for the detailed reproduction. We have a fix and will release it to master soon.

**Comment by soqt** [comment]
@do4gr Did this issue fixed in 1.32.0? I still encounter aggregation count error in the latest version.

**Comment by pantharshit00** [comment]
@soqt 

Have you upgraded you prisma instance in your Docker container? You will need to upgrade your cli as well as prisma server.

**Comment by pavelvladimir** [comment]
I upgrade prisma cli, docker image version, client lib and I have a some problem as because. In the latest version.

**Comment by soqt** [comment]
> @soqt
> 
> Have you upgraded you prisma instance in your Docker container? You will need to upgrade your cli as well as prisma server.

Yes I did. For this example, the new version works as expected. However, when "where" selector contains ObjectId, it fails.

For example I have a User & Company datatype
```gql
type User {
  id: ID! @id
  company: Company
}
type Company {
  id: ID! @id
  name: String,
  members: [User!]!
}
```

After create several users and companies, this query results aggregate count 0 although there are one edge.

```gql
{
  usersConnection(where: {
    company: {
      id: "5ccba2f2a7b11b00081e405d"
    }
  }) {
    edges {
      node {
        id
        company {
          id
        }
      }
    }
    aggregate {
      count
    }
  }
}
```
<img width="469" alt="Screen Shot 2019-05-03 at 10 19 43 AM" src="https://user-images.githubusercontent.com/10392539/57117215-07c9e900-6d8d-11e9-811f-a1369a9023be.png">

**Comment by do4gr** [comment]
I can reproduce your error @soqt and will look into it. Thanks for reporting!

**Comment by do4gr** [comment]
I just merged a fix to master and this will be fixed in the next release.
