### ISSUE TITLE
Create happens before set

### ISSUE THREAD

**Issue by cesarve77** [prisma/prisma#4416]
**Describe the bug**

For this model
```
type Family{
  id: ID! @unique
  surname: String!
  places: [Place!]!
}
type Place{
  id: ID! @unique
  name: String!
  type: String!
}
```

I want to create a new place, update other place, and disconnect from all olds no updated places. In one sentence and I use create, update and set, (I don't use disconnect because i don't know the old place ids)

The problem is set run at very last. then the new created place is not connected

**To Reproduce**
Over the above schema run
```
mutation {
  updateFamily(
    data: {
      places: { 
        update: [{where:{id:"place1"}, data:{name:"new name for place 1"}}]
        set: [{id:"place1"}]
        create: [
          { name: "Totally new place"}
        ]
      }
    }
    where: { id: "cjttntcvk02020718u28s67ra" }
  ){
    id
    places{
      id
      name
    }
}

```
**Expected behavior**

I Expect the Family records is connected to 2 places, ids: place1 and the new id

**Versions (please complete the following information):**
- Connector: MySQL
- Prisma Server: 1.29
- prisma CLI: 1.29.2
- OS: [OS X Mojave 10.14.4 ]

**Additional context**
Solution:
In my point of view Update should run first.
Create in second place 
and finally set

Similar issue but for embebed types: https://github.com/prisma/prisma/issues/4327

**Comment by pantharshit00** [comment]
Hi @cesarve77 

As you have already opened an issue around this, opening a new one(even for embedded types) is redundant. 

I am going to close this as a duplicate.
