### ISSUE TITLE
DataModel v1.1 - Integer IDs are incremented even when no node is created

### ISSUE THREAD

**Issue by P4sca1** [prisma/prisma#4420]
**Describe the bug**
I am using the new data model and noticed that ids are incremented even when there are no nodes being created.

**To Reproduce**
datamodel.prisma
```
type User {
  id: Int! @id
  username: String! @unique
}
```

`npx prisma deploy`

Now go the playground and create a user:
```
mutation {
  createUser(data: { username: "Test" }) {
    id
  }
}
```

Try to create the same user a few times. You will get errors because username is already taken.
Create another user called "Test 2". This user will not have id 2, because the users we tried to create earlier raised the id, even when they did not got created, because the username was already taken.

**Expected behavior**
The id should only be raised when the node is actually created.

**Versions (please complete the following information):**
 - Connector: `MySQL`
 - Prisma Server: `1.32.0-beta`
 - `prisma` CLI:`prisma/1.31.1`
 - OS: `OS X High Sierra`

**Additional context**
I've got a question concerning the new datamodel, would be great if it could be answered as part of this issue.
~What does Prisma use under the hood for `Int! @id` fields for the `mysql` connector? And what's the difference when using the `@sequence` directive?~
I found out that Prisma uses `AUTO_INCREMENT` and `PRIMARY KEY` when only using `Int! @id`.
Would be great to get some info regarding `@sequence`.

**Comment by pantharshit00** [comment]
@P4sca1 

This is expected, we send the payload to MySQL and it rejects it as a unique constraint is violated and but the sequence is also incremented(that's how they work).

> I found out that Prisma uses AUTO_INCREMENT and PRIMARY KEY when only using Int! @id.
Would be great to get some info regarding @sequence.

With `@sequence` directive, you can configure the auto-incrementing sequence size, initial value and its name.

**Comment by P4sca1** [comment]
Alright, thank you for the info!
