### ISSUE TITLE
npm -s run generate error - Cannot download query-engine

### ISSUE THREAD

**Issue by shoapeng-redko** [prisma/prisma#4420]
## Bug description

![image](https://user-images.githubusercontent.com/74572500/100633599-24b8fc00-32e3-11eb-8791-77acb2a3ff32.png)

## How to reproduce

npm install

## Environment & setup

- Windows 10 Pro x64

```

```

**Comment by pantharshit00** [comment]
Hello @shoapeng-redko 

Can you please tell me which version of Prisma you are trying to use? Also, please paste the logs here instead of providing a screenshot. 

I was unable to reproduce this using the version 2.12.1

**Comment by janpio** [comment]
Can you access the URL mentioned in the error message in your browser manually?

**Comment by shoapeng-redko** [comment]
Nope, the url is not downloadable.

**Comment by shoapeng-redko** [comment]
Here is the dependency 
"@prisma/client": "2.0.0-beta.8",

**Comment by janpio** [comment]
That is suuuuper old. Please try with a newer version of Prisma CLI and the problem will be gone.
