### ISSUE TITLE
Error: Error in introspection engine: /server/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x

### ISSUE THREAD

**Issue by suryashekhawat** [prisma/prisma#4431]
root@76fd6f05655c:/server# npx prisma introspect
Environment variables loaded from ./prisma/.env
Prisma schema loaded from prisma/schema.prisma

Introspecting based on datasource defined in prisma/schema.prisma …
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at /server/node_modules/@prisma/cli/build/index.js:5052:26
    at new Promise (<anonymous>)
    at IntrospectionEngine3.runCommand (/server/node_modules/@prisma/cli/build/index.js:5007:14)
    at async Introspect.parse (/server/node_modules/@prisma/cli/build/index.js:112647:35) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: Error in introspection engine: /server/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

how fix this issue

Dockerfile

FROM node:14-slim

COPY . /server

WORKDIR /server

RUN npm i

EXPOSE 5000

CMD ["npm", "start"]

**Comment by pantharshit00** [comment]
Hey @suryashekhawat 

Sorry for bit of late reply here. You will need to install `openssl` in linux in order to use Prisma on linux. Usually openssl is already installed in linux distributions as the default ssl library but looks like it is not installed in `node:slim` image. Use the following image:
```
FROM node:14-slim

COPY . /server

WORKDIR /server
RUN apt-get update -y
RUN apt-get install openssl -y
RUN openssl version
RUN npm i

EXPOSE 5000

CMD ["npm", "start"]
```

**Comment by suryashekhawat** [comment]
> Hey @suryashekhawat
> 
> Sorry for bit of late reply here. You will need to install `openssl` in linux in order to use Prisma on linux. Usually openssl is already installed in linux distributions as the default ssl library but looks like it is not installed in `node:slim` image. Use the following image:
> 
> ```
> FROM node:14-slim
> 
> COPY . /server
> 
> WORKDIR /server
> RUN apt-get update -y
> RUN apt-get install openssl -y
> RUN openssl version
> RUN npm i
> 
> EXPOSE 5000
> 
> CMD ["npm", "start"]
> ```

Thanks
