### ISSUE TITLE
Resolver not implemented

### ISSUE THREAD

**Issue by MANJUSAK** [prisma/prisma#4432]
Hello! I am very happy to share, but I made a mistake when using "GraphQL Server with Realtime Subscriptions Example": "Resolver not implemented".

The following is the error message returned by the query result.
`{ "errors": [ { "message": "Resolver not implemented", "locations": [ { "line": 2, "column": 3 } ], "path": [ "accessMenu" ], "extensions": { "code": "INTERNAL_SERVER_ERROR", "exception": { "stacktrace": [ "Error: Resolver not implemented", " at accessMenu (D:\\workspace\\renhe\\venom\\venom-runtime\\src\\generated\\placeholder\\resolvers\\Query.ts:9:11)", " at field.resolve (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql-extensions\\src\\index.ts:267:18)", " at resolveFieldValueOrError (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:480:18)", " at resolveField (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:447:16)", " at executeFields (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:294:18)", " at executeOperation (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:238:122)", " at executeImpl (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:85:14)", " at Object.execute (D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\graphql\\execution\\execute.js:62:35)", " at D:\\workspace\\renhe\\venom\\venom-runtime\\node_modules\\apollo-server-core\\src\\requestPipeline.ts:367:28", " at Generator.next (<anonymous>)" ] } } } ], "data": { "accessMenu": null } }`

**Comment by pantharshit00** [comment]
@MANJUSAK 

Can you please provide a small reproduction?

I am assuming that you have directly copy/pasted the code generated by graphqlgen which out actually implementing the resolver.

**Comment by MANJUSAK** [comment]
@pantharshit00 
thank you for your reply
Here is the code snippet generated by graphqlgen

`import { QueryResolvers } from "../graphqlgen";

export const Query: QueryResolvers.Type = {
  ...QueryResolvers.defaultResolvers,
  menu: (parent, args, ctx) => {
    throw new Error("Resolver not implemented");
  },
  menus: (parent, args, ctx) => {
    throw new Error("Resolver not implemented");
  },
  menusConnection: (parent, args, ctx) => {
    throw new Error("Resolver not implemented");
  },
  node: (parent, args, ctx) => {
    throw new Error("Resolver not implemented");
  }
};`

But every time you execute, you will get the "Resolver not implemented" error.

Please also let me know exactly where I did it wrong.
thank you very much

**Comment by MANJUSAK** [comment]
@pantharshit00

When using the query:
  Menus: (parent, args, ctx) => {
     // throw new Error("Resolver not implemented");
     Console.log('args----->', args)
     Return ctx.prisma.menus(args)
   },
Print the results of args:
Args-----> {}

But when using mutation
The result of printing args is indeed normal:
Args-----> { data: { label: 'send to send', icon: 'send of sunscreen to send' to } }

The following is an example of a query:
"query menus($where: MenuWhereInput) {
   Menus(where: $where) {
     Id
     Label
     Icon
   }
}
{
   "where":{
     "id":"cjurqyfgj00a209666us5fs5l"
   }
}"

Example of creating data:
"mutation createMenu($data: MenuCreateInput!) {
   createMenu(data: $data) {
     Id
   }
}
{
   "data": {
     "label": "Send to send"
     "icon": "Send sunscreen to send to"
   }
}"

Can you tell me how to solve it?
thank you very much
