### ISSUE TITLE
Array of Json [Json] in Datamodel does not generate corectly

### ISSUE THREAD

**Issue by huyqpham** [prisma/prisma#4433]
**Describe the bug**
When input [Json] in Datamodel. The generated prisma-schema.ts does not as expected

**To Reproduce**
1. Create a file datamodel.prima as following:
```graphql
type configuration {
  _id: ID! @id
  attachableFiles: [Json]
}
```
2.  Run: `prisma generate`
3.  The output "prisma-schema.ts" as following
...
```graphql
type configuration {
  _id: ID! @id
  attachableFiles: [Json]
}
```
...
```graphql
input configurationCreateattachableFilesInput {
  set: [Json]
}
```
...
```graphql 
input configurationCreateInput {
  _id: ID
  attachableFiles: configurationCreateattachableFilesInput
}
```
...
```graphql
type configurationPreviousValues {
  _id: ID!
  attachableFiles: [Json!]!
}
```
...
```graphql
input configurationUpdateInput {
  attachableFiles: configurationUpdateattachableFilesInput
}
```
...
```graphql
input configurationUpdateManyMutationInput {
  attachableFiles: configurationUpdateattachableFilesInput
}
```

**Expected behavior**
Should not generate:
```graphql 
input configurationCreateattachableFilesInput {
  set: [Json]
}
```
... 
And correct generated file should be
```graphql
input configurationCreateInput {
  _id: ID
  attachableFiles: [Json]
}
```
...
```graphql
type configurationPreviousValues {
  _id: ID!
  attachableFiles: [Json]
}
```
...
```graphql
input configurationUpdateInput {
  attachableFiles: [Json]
}
```
...
```graphql
input configurationUpdateManyMutationInput {
  attachableFiles: [Json]
}
```

**Versions (please complete the following information):**
 - Connector: [`MongoDB`]
 - Prisma Server: [`1.31`]
 - `prisma` CLI: [`prisma/1.31.0, node-v10.15.3`]
 - OS: [`Windows 10`] 
 - other dependencies: None.

**Additional context**
Please check implementation of Array of Json Data type.

**Comment by pantharshit00** [comment]
Hi @huyqpham 


I don't understand why this is not expected. Json field is a special type in which you will require to provide it with Json in an escaped String Form. It is a custom scalar.
