### ISSUE TITLE
Can't import datamodel into schema.graphql because of directives

### ISSUE THREAD

**Issue by zwhitchcox** [prisma/prisma#4436]
**Describe the bug**
I don't know if this qualifies as a bug, but I [asked the question here](https://www.prisma.io/forum/t/documentation-conflicts-with-answer-on-here/6733), and no one has been able to give me an answer.

  I'm getting the error `Error: Directive unique: Couldn't find type unique in any of the schemas.`, just like the user [here](https://www.prisma.io/forum/t/error-directive-directivename-couldnt-find-type-directivename-in-any-of-the-schemas/5159), and the solution was that you can't use the prisma datamodel in your schema.

That directly conflicts with what it says in the [documentation](https://www.prisma.io/docs/1.20/data-model-and-migrations/data-model-knul/#a-note-on-the-application-schema).

It seems like this was an intended feature because it's in the documentation, but it obviously doesn't work.

It would be really nice not have to redefine everything again in my schema.graphql, as it seems that should be able to be done automatically.

**To Reproduce**
Try to import your datamodel into your graphql-yoga `schema.graphql`

**Expected behavior**
The data model should be added to the schema.graphql automatically

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.31.0
 - `prisma` CLI: Prisma CLI version: prisma/1.31.1 (windows-x64) node-v10.15.0
 - OS: Windows 10
 - other dependencies: `prisma-client`, `prisma-binding`, etc. if applicable

**Comment by pantharshit00** [comment]
Hi @zwhitchcox 

Prisma datamodel is different than the prisma graphql schema.


If you want to import the schema first you will need to generate the graphql schema. Use the graphql schema generator in the prisma.yml file like so:
```yaml
generate:
  - generator: graphql-schema
    output: ./src/generated/graphql/prisma.graphql
```

Now run `prisma generate` to generate your file.

After that you can import anything from this file using [graphql-import](https://github.com/prisma/graphql-import)(supported by graphql-yoga out of the box):

```graphql
# import * from './src/generated/graphql/prisma.graphql'

# you the types in your code
```

Here is a project of mine that uses this: https://github.com/javascript-af/javascript-af/blob/master/packages/backend/src/schema.graphql

https://github.com/javascript-af/javascript-af/blob/master/packages/backend/src/makeExecutableSchema.ts

**Comment by zwhitchcox** [comment]
That's great, ok, I see, I didn't really understand the docs, but I do now that you've explained it.

I would maybe change the part that says 

```
# import Post from "prisma.graphql"```
```

to

```
# import Post from "./generated/graphql/prisma.graphql"
```

Just to make it more clear that you are supposed to import the data model from the generated graphql, like you have in your comment.

And then, I would change 

>Instead, you import them using graphql-import:

to 

>Instead, you import them from the generated graphql using graphql-import:

Just to make that abundantly clear. The docs were correct, but just not explicit enough for me (and possibly others) to understand that they meant from the generated graphql.

**Comment by pantharshit00** [comment]
Thanks for the feedback :)
