### ISSUE TITLE
nextjs Could not open datamodel file "\\schema.prisma"'

### ISSUE THREAD

**Issue by GuyARoss** [prisma/prisma#4451]
## Bug description
I am using yarn berry to build the primsa client into a separate workspace. I am then using the client in two different places, one is a stand-alone web service and the other is a nextjs web app. The prisma client works correctly in the stand-alone web service, but when I try to use it within my nextjs app it throws this when I try to run a query. 
```
  Query engine exited with code 101

thread 'main' panicked at 'Could not open datamodel file "\\schema.prisma"', query-engine\query-engine\src\opt.rs:185:53
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: BaseThreadInitThunk
  24: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at PrismaClientFetcher.request (C:\Users\guyal\Documents\flightv2\packages\web-portal\.next\server\pages\api\resource-secondary-skills.js:79092:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.11.0'
}
```

## How to reproduce
My yarn berry configuration is arranged like so:
```
- packages
  - prisma-client
  - web-service
  - web-app
```

## Environment & setup
- OS: Win 10
- Database: sqlite
- Node.js version: 12.16.1
- Prisma version: 2.11.0

**Comment by pantharshit00** [comment]
@GuyARoss Yarn 2 is not supported right now.

Please follow https://github.com/prisma/prisma/issues/1439

**Comment by GuyARoss** [comment]
@pantharshit00 what do you mean it isn't supported? I can get it to work correctly in my repo by building my client to its own workspace. I pass around this client everywhere in my other packages and it works correctly. The issue that exists is when I try to use that client within nextJS. (assuming it has something to do with nextJS not actually packing the prisma client correctly)

**Comment by pantharshit00** [comment]
@GuyARoss There are known issues(follow the link that I have posted) so that is why it is not currently supported.
