### ISSUE TITLE
Query with nested where doesn't work

### ISSUE THREAD

**Issue by luhovskyi** [prisma/prisma#4452]
**Describe the bug**
When making a query with nested `where` argument I got an empty array with prisma.

**To Reproduce**
1. datamodel.graphql
```
type User {  
  id: ID! @id
  name: String!
  father: User
}
```

2. This is the full users list
![all-users](https://user-images.githubusercontent.com/15964567/57584835-a3273080-74e8-11e9-9966-fdff74c2f2a2.jpg)

3. But when I use where argument to query, I got empty array
![where](https://user-images.githubusercontent.com/15964567/57584837-acb09880-74e8-11e9-8bd1-2a783cd6699b.jpg)

**Expected behavior**
Get all users with provided father id (User 2, User 3).

**Versions:**
 - Connector: Postgres or MySQL
 - Prisma Server: 1.31
 - `prisma` CLI: prisma/1.31.1 (darwin-x64) node-v10.14.0
 - OS: Windows 10

**Comment by pantharshit00** [comment]
I can confirm this, issue is specific to postgres. It can't reproduce it with mongodb connector

**Comment by luhovskyi** [comment]
same issue with MySQL
