### ISSUE TITLE
DB passwords with "@" character get's wrongly parsed in DATABASE_URL

### ISSUE THREAD

**Issue by Oliver-ke** [prisma/prisma#4455]
## Bug description
I had my database URL looking like this  `postgresql://application:#@123njhuts@localhost:5432/portal-db-prod`, on running prima migrate command I get an error "P1001: Can't reach database server at `dbUser`:`5432".
I tried changing my cloud_sql_proxy to a different port but it didn't work, I then tested the db connection with pgAdmin, that worked, 

After different trials, I decided to change the db password, removing the "@" sign and everything worked as expected. 

## How to reproduce
Use a db password that includes an "@" character, then try running Prisma migration

## Expected behavior
"P1001: Can't reach database server at `dbUser`:`5432".

## Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: v14.1.0
- Prisma version: 
"@prisma/client": "^2.8.1"
"@prisma/cli": "^2.8.1",

**Comment by pantharshit00** [comment]
Hello @Oliver-ke 

You will need to percent encode `@` as `%40`. That will allow you to use that character in the uri format.

**Comment by Oliver-ke** [comment]
Okay @pantharshit00 ,
Good to know, it'll be nice to add to the docs or provide a more descriptive error message so that some other person won't go through the same issue.
thanks.

**Comment by pantharshit00** [comment]
Opened: https://github.com/prisma/docs/issues/1057
