### ISSUE TITLE
One field of the type `User` must be marked as the id field with the `@id` directive.

### ISSUE THREAD

**Issue by andrewcodes404** [prisma/prisma#4458]
A brand new project, the generated datamodel.prisma
```
type User {
  id: ID! @unique
  name: String!
}
```
When running  ``$prisma deploy`` to a demo server i get this error

``   ✖ One field of the type `User` must be marked as the id field with the `@id` directive.``

Ok so I change  `` id: ID! @id`` and now it deploys BUT.... now i want to use my Heroku db and server and on deploy..
```The field `id` is reserved and has to have the format: id: ID! @unique ```

🤦‍♂️ Seems like each has a different idea of  what to expect with id : ID, got around this with 
```
type User {
  id: ID! @unique
  anyName: ID! @id
  name: String!
}
```
But it seems a bit foolish to have to have two Id fields?

**To Reproduce**
https://github.com/andrewcodes404/prisma-id-error

**Comment by joltmode** [comment]
Had the same problem, but got around it with just a:
```
type User {
    id: ID! @id
    name: String!
}
```

**Comment by pantharshit00** [comment]
@andrewcodes404 

Can you please share your cli version? The demo server uses the new datamodel format so you will need cli version greater than 1.31 in order to be compatible with the demo server. 

What you are getting right now is a mix of old and new datamodel validation warnings which I suspect are caused by mismatching the version of the CLI and server.

**Comment by andrewcodes404** [comment]
ah yes... prisma/1.30.2 (darwin-x64) node-v10.15.0

**Comment by andrewcodes404** [comment]
how do i get to 1.31 i use ``npm install -g prisma`` but it will only get me to 1.30?

**Comment by pantharshit00** [comment]
try `npm install -g prisma@1.31`

**Comment by timsuchanek** [comment]
Thanks for reporting! We just released `1.31.2`.

**Comment by darrylyoung** [comment]
Hi, @timsuchanek. I just tried using `1.31.2` and I'm having issues. The CLI installed fine but once I set it to that version in `docker-compose.yml` I'm seeing an error.

```
➜ git:(master) ✗ prisma --version
Prisma CLI version: prisma/1.31.2 (darwin-x64) node-v10.15.3
➜ git:(master) ✗ docker-compose up -d
Pulling prisma (prismagraphql/prisma:1.31.2)...
ERROR: manifest for prismagraphql/prisma:1.31.2 not found
```

Am I missing something here? Thanks in advance.

**Comment by pantharshit00** [comment]
@darrylyoung 

Dockerhub is rate-limiting request(that is what caused the graphcool outage) so try again, using 1.31 in the docker-compose file.

**Comment by andrewcodes404** [comment]
ok great it's working on the demo server... but now when I try and create a prod server with Heroku I get the same error
`` ✖ The field `id` is reserved and has to have the format: id: ID! @unique or id: UUID! @unique.``

The Heroku servers are running 1.23.0!  how can i get them to run 1.32?

**Comment by andrewcodes404** [comment]
You'll probably tell me to go here https://github.com/prisma/prisma-cloud-feedback/issues/202#issuecomment-414095090 
But that is way too much, is there a way in https://app.prisma.io ?

**Comment by pantharshit00** [comment]
Sorry @andrewcodes404 but that is the way as the server is not hosted by us. 

It is the standard process for updating a heroku container deploy.

**Comment by andrewcodes404** [comment]
I have no idea what a docker container image is. How can i downgrade the CLI ad Server back to 1.23?

**Comment by pantharshit00** [comment]
If you downgrade, datamodel 1.1 will not be available.

Please message me on slack(slack.prisma.io). I am @harshit there. I will be happy to help you in this regard.

**Comment by thavamm** [comment]
> Had the same problem, but got around it with just a:
> 
> ```
> type User {
>     id: ID! @id
>     name: String!
> }
> ```

I did the same, it works fine. Thank you

**Comment by imyjimmy** [comment]
Hi, I'm following along the [Getting Started > New Database](https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-JAVASCRIPT-a002/) docs, and I'm able to replicate the error, _but only the second time I try_ `prisma deploy` _and afterwards_. 

What happened was, I was playing around with `managementApiSecret` and so was deleting `prisma.yml` and `datamodel.prisma`, then re-doing `prisma init --endpoint http://localhost:4466` and finally redeploying.

It was strange that this error only happened after the first time. I tried deleting and recreating the docker images but this error persisted. Of course, adding `@id` resolved it, but I'm now confused as to why my first attempt was successful in the first place.

**Comment by teddyotieno** [comment]
> ```
> type User {
>     id: ID! @id
>     name: String!
> }
> ```

**Comment by zxzl** [comment]
Just met this issue while using prisma CLI installed from hombrew. I think npm should be introduced as more preferred option to install prisma CLI

**Comment by rutgervanderkraats** [comment]
> Had the same problem, but got around it with just a:
> 
> ```
> type User {
>     id: ID! @id
>     name: String!
> }
> ```

Yes, did the trick!

**Comment by GeeTeeNZ** [comment]
I too had the same problem and did as follows:

type User {
  id: ID! @id @unique
  name: String!
  ...
}

Also, had errors with a createdAt:

...
  createdAT: DateTime! @createdAt
}

Hope this helps someone.
