### ISSUE TITLE
Connection details

### ISSUE THREAD

**Issue by AviBueno** [prisma/prisma#4461]
## Problem

As per discussion #4457 it is currently impossible to access Prisma's connection details such as hostname, port, etc.

## Suggested solution

Add a `PrismaClient.connectionDetails` (maybe `PrismaClient.$connectionDetails`) property with `protocol`, `hostname`, `port`, `dbname` (and maybe `username` as well). 

TBD: Expose an `isConnected` flag as well (constructing a `env("DATABASE_URL")` based PrismaClient when no DATABASE_URL is found in env. vars will instantiate a disconnected object). 

## Alternatives

Instead of a dedicated `connectionDetails` property, these details may alternatively be the return value coming back from `Prisma.$connect`

## Additional context

Having these details at hand will save the trouble of finding the DATABASE_URL source (be it an env. var or the result of a .env file in the root directory, prisma directory or somewhere else).

It will also save the trouble of parsing the various pre-DB-engine connection string formats.

**Comment by janpio** [comment]
We haven't had any additional requests for this in the last 3 years, so it is safe to say that this is not the most pressing need. As we have hundreds of issues where we do get constant feedback and upvotes, it is not realistic for us to prioritize this one any time soon, sorry. 

I am closing this issue for now. If someone has a dire need for this, please comment below or open a new feature request. Thank you.
