### ISSUE TITLE
Triggering Redeploy after renaming Model throws deploy error

### ISSUE THREAD

**Issue by belazer** [prisma/prisma#4467]
**Describe the bug**
We are currently facing the issue with a redeploy error throwing `"Post", "field": null, "description": "You are creating a required field but there are already nodes present that would violate that constraint.` eventhough the only existing entry has all those fields filled out.

**To Reproduce**
**Step 1** Create Post Type:
```
type Post {
#The status of the record
status: Status! @default(value: "DRAFT")
#The time the record was updated
updatedAt: DateTime!
#The time the record was created
createdAt: DateTime!
#The unique identifier
id: ID! @unique
}
```

**Step 2** Add title field:

```
type Post {
#The status of the record
status: Status! @default(value: "DRAFT")
#The time the record was updated
updatedAt: DateTime!
#The time the record was created
createdAt: DateTime!
#The unique identifier
id: ID! @unique

title: String
}
```

**Step 3** Create entry for post:
```
{
  "data": {
    "posts": [
      {
        "id": "cjv27z2erh2ig08719jr3udxx",
        "title": "Testing",
        "status": "DRAFT",
        "createdAt": "2019-04-29T10:28:15.987Z",
        "updatedAt": "2019-04-29T10:28:15.987Z"
      }
    ]
  }
}
```

**Step 4** rename `Post` to `Article` which causes a datamodel redeploy that goes through just fine:
```
type Article @rename(oldName: "Post") {
#The status of the record
status: Status! @default(value: "DRAFT")
#The time the record was updated
updatedAt: DateTime!
#The time the record was created
createdAt: DateTime!
#The unique identifier
id: ID! @unique

title: String
}
```

**Step 5** Trigger a manual redeploy, this time it throws a redeploy error:
```
type Article {
#The status of the record
status: Status! @default(value: "DRAFT")
#The time the record was updated
updatedAt: DateTime!
#The time the record was created
createdAt: DateTime!
#The unique identifier
id: ID! @unique

title: String
}
```
```
"PRISMA_DEPLOY_ERROR", "errors": [{"type": "Article", "field": null, "description": "You are creating a required field but there are already nodes present that would violate that constraint."}, {"type": "Article", "field": null, "description": "You are creating a required field but there are already nodes present that would violate that constraint."}, {"type": "Article", "field": null, "description": "You are creating a required field but there are already nodes present that would violate that constraint."}, {"type": "Article", "field": null, "description": "You are creating a required field but there are already nodes present that would violate that constraint."}]
```

The weird thing being here that if i add another type or field (any stage mutation action), i am able to redeploy just fine.

**Expected behavior**
The manual redeploy after the rename should work just fine, as there are no required fields that aren't filled out

**Versions (please complete the following information):**
 - Connector: `MySQL`
 - Prisma Server: `1.26.4` & tested `1.30.0` locally

**Additional context**
Already pinged @divyenduz in Slack about it, he looked a bit into this already

**Comment by pantharshit00** [comment]
I was unable to reproduce this.

I tried it with the new datamodel, old datamodel and even with the postgres connector and I was still unable to reproduce this at all.
![image](https://user-images.githubusercontent.com/22195362/57017082-143e2c80-6c3b-11e9-8fae-ae1ec11ca9fb.png)


I was not sure about the type of `Status` that is not provided in the repro so I used the following enum:
```graphql
enum Status {
  DRAFT
  PUBLISHED
}

```

**Comment by belazer** [comment]
Seems like we are sending the @rename directive again for the stage redeploy. Thus the issue is actually on our side!
