### ISSUE TITLE
Allow database call (pl/pgsql) in @default

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#4468]
## Problem
With the new migration system and native types, there are new use cases that could be enabled.
It would be nice if we could specify a database function (like pl/pgsql one) in the `@default` that would we used in the `DEFAULT` parameter in the migration and would result in an optional field in the TS type.

My current use case is I want to build sequential UUID (either the proposed [UUIDv6](http://gh.peabody.io/uuidv6/), [ulid](https://github.com/ulid/spec) or [2ndQuadrant type](https://www.2ndquadrant.com/en/blog/sequential-uuid-generators/). I will most likely use a pl/pgsql function for that since most managed databases don't allow random native C based extensions.

## Suggested solution

In the model allow:
```prisma
model Test {
  id String @id @default(generate_uuid_v6())
}
```

## Alternatives

With the new migration system I can add it to the create table, but if I remove the `@default(uuid())` it won't mark it as optional in the TS typing. Not sure what happens if I say `@default(null)`?

EDIT:
Use `@default(dbgenerated())` and change the `DEFAULT` in the SQL migration works!

**Comment by mavilein** [comment]
You can use `@default(dbgenerated())` to indicate to Prisma Client that the default will be handled by the database.

**Comment by janpio** [comment]
And you can use the `dbgenerated` function like `@default(dbgenerated("FOO"))` where `FOO` is put directly as the value of the default definition in the SQL to define the DDL.

https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#dbgenerated

I think this closes this issue then 👍
