### ISSUE TITLE
Add multi-line / block comments to PSL / schema.prisma file

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma#4474]
## Problem

The `schema.prisma` file is becoming large. I’d like to group models by their general categories, as well as add more detailed explanations to each model, and to do that, I generally use block comments. However, these are presently not recognized in the schema file.

## Suggested solution

Let us not only use line comments (which already works):
```prisma
// This is a line comment
```
but also block comments in our `schema.prisma` file:
```prisma
/*
 * This is a block comment, but is currently not recognized as a comment
 */
```

**Comment by ajmnz** [comment]
Prisma team 👋🏼

Any updates about this? Apart from what the OP stated, it would be really useful to implement new docs generators with detailed descriptions of each model.

Thanks!

**Comment by chris-solis9** [comment]
Any movement on this item? Very interested in seeing this.

**Comment by kasir-barati** [comment]
I need this feat too. @janpio can you share some link to see if it is planned to be done in the future

**Comment by janpio** [comment]
There is nothing additional to share. Our roadmap is at https://pris.ly/roadmap, but this is currently not part of it.

**Comment by avin-kavish** [comment]
I'd like this too. Not an expert on Rust, but can't this be trivially implemented by adding to the grammar of the parser?

**Comment by torchsmith** [comment]
bump

**Comment by nick-inkeep** [comment]
+1

**Comment by torchsmith** [comment]
Alternate solution for anyone who needs it since block comments do not seem to be prioritized in any way:

```
// This is a single line comment
```


```
// This is a
// big fat
// block comment
// on multiple lines.
```

**Comment by cseguinlz** [comment]
Yo! dev experience matters ✊🏼, please add block comments, schema it's quickly becoming a mess

**Comment by TFaesen** [comment]
Just found out multi-line comment doesn't work. This feature would be really nice to have.

**Comment by gabrielfernans** [comment]
That would be good.

**Comment by TimKieu** [comment]
RIGHT, we really need block comment support. The best choice is prisma & kysely working together!

**Comment by jeffspurlock** [comment]
Wow. I'm shocked. Can't believe i can't add block comments. I'm not invested in this tool yet; this is my first project using Prisma, but now don't know if i'll actually use it now. It's been 3+ years now and this basic functionality hasn't been added? But honestly what really is off putting is the fact that there isn't even a comment from the devs saying "No, this isn't something we're interested in adding." or "Maybe, but this is very low on our priority list." At least have the courtesy to tell us to go pound sand; going radio silent on the topic for 3+ years is not the right approach.

**Comment by zaber04** [comment]
I **_REALLY REALLY REALLY_** need multiline comment blocks **ASAP**.

**Comment by derfcode** [comment]
would be nice

**Comment by leiDnedyA** [comment]
Please add this, my files are so ugly

**Comment by nftchance** [comment]
Please sers and maams.

**Comment by madx720** [comment]
Any updates on the issue of missing multi line comments in prisma

**Comment by brunobarretofreitas** [comment]
Any updates ?

**Comment by achyu-dev** [comment]
Any updates?

**Comment by sgd2z** [comment]
➕1. 
Would love multiline version for /// comment and // comment

**Comment by triplecasquette** [comment]
Hey Prisma We need your help here 🤣
+1 Too

**Comment by juan1003** [comment]
Hey prisma +1

**Comment by Abdulrahmanelheyb** [comment]
Hey! Prisma, can you hear us

**Comment by tylerkahn** [comment]
I know you guys are now committed to addressing a lot of these longstanding issues. Can we get multiline comments? Should be a pretty simple matter of adding it to the grammar spec?

https://www.prisma.io/blog/prisma-orm-manifesto

**Comment by joachimaok** [comment]
Hey! Prisma, that should good for us, especially for data documentation 📚 
Please 🙏
