### ISSUE TITLE
Couldn't find any versions for "prisma-client-lib" that matches "1.32.0"

### ISSUE THREAD

**Issue by steida** [prisma/prisma#4474]
I think it's a bug.

**Comment by pantharshit00** [comment]
@steida 

Can you tell me how to reproduce this?

Also, it seems this might have occurred while we were releasing the 1.32 and cli got published before client-lib and caused this error.

Tag 1.32 exists on npm: https://www.npmjs.com/package/prisma-client-lib/v/1.32.0

**Comment by steida** [comment]
I thought it was something like that. Working now. Thank you for the response.
