### ISSUE TITLE
Docker latest/alpine version

### ISSUE THREAD

**Issue by guigaoliveira** [prisma/prisma#4478]
**Is your feature request related to a problem? Please describe.**
I think it's a bit bad to have to upgrade the prism to a specific version whenever you're developing.

**Describe the solution you'd like**
In docker hub I think there could be at least the "latest" version for so whenever I download a docker image it will be the most current version. The alpine version would be a bonus.

**Comment by pantharshit00** [comment]
Closing as a duplicate of https://github.com/prisma/prisma/issues/3244

**Comment by SergeiMeza** [comment]
Prisma is at an active development stage right now. They are releasing a new version every two weeks, so to not break your code, it is best practice to set up the tag manually.
