### ISSUE TITLE
Error saving changes in the Prisma Admin when using a UUID as the @id for a model.

### ISSUE THREAD

**Issue by sam-at-work** [prisma/prisma#4487]
**Describe the bug**
When I am providing my own UUID as the @id on a model, I am unable to save updates in the Prisma admin.

**To Reproduce**
Have a model such as
```
type User {
    cognitoSub: UUID! @id(strategy: NONE)a
    cognitoUsername: String!
}
```
When trying to save a change to the `cognitoUsername` in the prisma admin,  I get the following error message:
```
[
  "Syntax error while parsing GraphQL query. Invalid input \"mutation { updateUser_6xxxxxxx-\", expected OperationDefinition, FragmentDefinition or TypeSystemDefinition (line 1, column 1):\nmutation { updateUser_6xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx: updateUser( where: { cognitoSub: \"6xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\" }, data: { cognitoUsername: \"John\" }) { __typename __typename cognitoSub cognitoUsername  }  }\n^"
]
```

Note that changes using a regular graphQL query, eg using the GraphQL playground for the prisma service don't return this error.

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: 1.32.0
 - `prisma` CLI: prisma/1.32.0 (darwin-x64) node-v10.15.3
 - OS: OSX
 - other dependencies: `prisma-client`, `prisma-binding`, etc. if applicable

**Comment by TheBeachMaster** [comment]
I have a similar issue. The error here is : 

```
  "Syntax error while parsing GraphQL query. Invalid input \"mutation { updateUser__User_34dc4bc5-\", expected OperationDefinition, FragmentDefinition or TypeSystemDefinition (line 1, column 1):\nmutation { updateUser__User_34dc4bc5-ef70-48a8-8c87-b807c223f3de: updateUser( where: { id: \"34dc4bc5-ef70-48a8-8c87-b807c223f3de\" }, data: { phoneNumber: \"+25XXXXXXXXXXXX\", password: \"ACXXXXXXXXXXXXXXX\" }) { __typename __typename id phoneNumber password }  }\n^"
```

The model is as shown 
```
type User {
  id: UUID! @id
  username: String!
...
  phoneNumber: String
  password: String
...
}
```
