### ISSUE TITLE
Order in DMMF is unstable

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#4491]
Reported by @MichalLytek, apparently, our DMMF not always has the same order for:
- `outputObjectTypes`: Sometimes `model` comes first, sometimes `prisma`
- `enumTypes`: The order of `model` and `prisma` is also sometimes different

**Comment by pantharshit00** [comment]
I can confirm this. This is can be reproduced by writing output of `getDMMF` to a file and diffing the output. 

I did that in a git repo.

![image](https://user-images.githubusercontent.com/22195362/102380277-bd42c200-3fed-11eb-9bd3-adef2bfa7b55.png)


Reproduction uploaded here: https://github.com/harshit-test-org/prisma-issue-4491
