### ISSUE TITLE
DateTime not persisting in prisma client (MongoDB)

### ISSUE THREAD

**Issue by nicovalencia** [prisma/prisma#4493]
**Describe the bug**
When saving a DateTime field using Prisma Client and MongoDB, the field is not saved/returned.

**To Reproduce**
1. Create resolver to update model with a DateTime field
2. Persist with Prisma Client
3. Observe returned model

In mutation resolver:
```
 updatePerson: async (parent, args, context) => {
    const data = {
      ...args.data,
      birthDate: new Date().toISOString(),
    };
    console.log('data', data);
    const person = await context.prisma.updatePerson({
      where: {
        id: args.where.id,
      },
      data,
    });
    console.log(person);
    return person;
  }
```

Log:
```
data { name: 'katy', birthDate: '2019-05-03T21:16:17.328Z' }
{ id: '5cccaa8a24aa9a000955e414', name: 'katy' }
```

**Expected behavior**
Expected birthDate to be persisted and returned.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - Connector: `MongoDB`
 - Prisma Server: `1.32`
 - OS: `OS Mojave`
 - other dependencies: `prisma-client`

**Additional context**
Schema:
```
type Person {
  id: ID! @unique @id 
  name: String!
  birthDate: DateTime
}
```

**Comment by SergeiMeza** [comment]
You don't need to convert the Date object to a string. Prisma client does this for you.

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/57697797-ab5ea780-7671-11e9-9da3-70c6de50ad25.png)


I can't reproduce this. Can you please share a small repository with a minimal reproduction
