### ISSUE TITLE
Support Yarn 2 without PnP

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#4493]
Yarn 2 without PnP should work with Prisma Client, but it doesn't.
The binary and schema file can't be found.

**Comment by GuyARoss** [comment]
Running into this same issue.

**Comment by adarnon** [comment]
Same here. Getting it to work with Next.js would be great.

**Comment by williamluke4** [comment]
@adarnon @GuyARoss If you add the following to your `.yarnrc.yml`. Everything should work ok. 

#### **`.yarnrc.yml`**
```yml
nodeLinker: node-modules
```
[Working Repo](https://github.com/williamluke4/next-prisma)

Let me know if you are still having problems.
