### ISSUE TITLE
@unique directive not working on mongo db datamodel

### ISSUE THREAD

**Issue by phucdth12a** [prisma/prisma#4497]
Prisma is connected to MongoDb and everything is working good but when I add @unique directive to field and redeploy prisma, then I still can create more than one user with same email.

DataModel:
type User {
id: ID! @id
name: String!
email: String @unique

}

in prisma version 1.32.2

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/57248427-ee13f480-705f-11e9-94d1-d087619431d2.png)


I am unable to reproduce this. Can you please tell me which MongoDB version you are using?

**Comment by phucdth12a** [comment]
Sorry! I fixed. Just delete table and add new table.
