### ISSUE TITLE
prisma introspection generates wrong schema in other projects

### ISSUE THREAD

**Issue by Karnich** [prisma/prisma#4505]
**Describe the bug**
The prisma data models generated by `prisma introspect`are inconsistent across different projects

Migrated the v1.1 datamodel. Everything went fine at first. This was for our main project. We are starting to build smaller projects around it. And when i tried doing `prisma introspect` in another project i received a different result. And the introspection is against the exact same configuration as in the main project and against the exact same docker container running MySQL.

main project:
![image](https://user-images.githubusercontent.com/6881674/57338424-9cd23680-712d-11e9-9126-2deb5134a2fc.png)

side project:
![image](https://user-images.githubusercontent.com/6881674/57338443-aeb3d980-712d-11e9-9d25-c3ed0be21660.png)

these two commands are run exactly after each other and generate the same result when run multiple times. The important part is the difference in models generated. It also seems like relations are not caught correctly. a 1-1 relation will show up as a many to many...

**To Reproduce**
1. run the migration in the main project
2. prisma introspect in main project
3. prisma introspect in some other project which has no previous knowledge of the model/database

**Expected behavior**
i expect exacltly the same models to be generated no matter from where i run `prisma introspect`

**Versions (please complete the following information):**
 - Connector: `mysql:5.7`
 - Prisma Server: `1.31.0`
 - OS: OS X 10.14.4
 - other dependencies: `prisma-client`

**Comment by pantharshit00** [comment]
Can you please share the SQL dumps of your databases(Just the structure, data is not required)?

Also, the number you see in the filename is a timestamp. It is not an SHA that will verify the datamodel integrity.
