### ISSUE TITLE
Ignoring table during introspection

### ISSUE THREAD

**Issue by devalnor** [prisma/prisma#4510]
## Problem

There is no option to ignore table during introspection (`prisma introspect`)
Actually all table are in the schema.

For example `_migrations` tables don't have to be in the schema.

## Suggested solution

I suggest to add a cli argument `--ignoreTablePattern` whose names match a regexp pattern. 
For example, tables whose names begin with an underscore.

`prisma introspect --ignoreTablePattern '^_'`

## Alternatives

If too complexe. The simplest solution can also be `--ignoreUnderscoreTable` but less custom

**Comment by tomhoule** [comment]
The `_Migration` and `_prisma_migration` tables should already be ignored by `prisma introspect`. Can you give us more details on your setup (database, OS, prisma version), in case these aren't ignored?

**Comment by devalnor** [comment]
> The `_Migration` and `_prisma_migration` tables should already be ignored by `prisma introspect`. Can you give us more details on your setup (database, OS, prisma version), in case these aren't ignored?

I my case it won't help. I use several migration tables (one for each nestjs module)

But I did test and it does not work.
introspect generate models for both table

```javascript
// schema.prisma
model Migration {
  id Int @id @default(autoincrement())

  @@map("_Migration")
}

model prisma_migration {
  id Int @id @default(autoincrement())

  @@map("_prisma_migration")
}
``` 

Setup:
* OS: Mac OS 10.14.6
* Database: Postgresql 12.4
* Node.js version: v14.15.1
* Prisma version: 2.13.1

**Comment by albertoperdomo** [comment]
This is going to improve soon with a functionality we are adding to ignore models in the schema. They still would be present in the schema file, but at least they would not be surfaced in the Client API.

**Comment by albertoperdomo** [comment]
In 2.16.0, we added an `@@ignore` attribute for models, which can be used to ignore certain models. This should solve this problem for you. Release notes here: https://github.com/prisma/prisma/releases/tag/2.16.0

If you want to ignore these tables and avoid them surfacing in the schema in the first place, we have a feature request for it here: https://github.com/prisma/prisma/issues/807.

**Comment by QuentinLuc** [comment]
Hey!  @albertoperdomo , I've tried your solution but unfortunately it doesn't work.  It seems tables are still taken into account during the introspect phase.
```
Error: Error: P4002

The schema of the introspected database was inconsistent: Illegal cross schema reference from `public.country` to `cft.country` in constraint `country_ibfk_2`. Foreign keys between database schemas are not supported in Prisma. Please follow the GitHub ticket: https://github.com/prisma/prisma/issues/1175
```

With this configuration
```
model country {
  @@ignore
}
```

**Comment by janpio** [comment]
@QuentinLuc Not directly helpful, but we are actively working on cross schema support, so please make sure your 👍 and use case is persisted in https://github.com/prisma/prisma/issues/1122 (and you are subscribed to that, so you get a notification when we post a comment with how you can test this out soon. Should happen in a few weeks.)

**Comment by analista10SPN** [comment]
https://github.com/prisma/prisma/issues/807#issuecomment-1301358904
