### ISSUE TITLE
selectionSet dont work in prisma-client-lib

### ISSUE THREAD

**Issue by claytonsilva** [prisma/prisma#4510]
**Describe the bug**
Using debug in my queries, i cannot saw difference in my resolver when call queries like:

```javascript
query {
   users {
       id
      name
   }
}
```
and 

```
query {
   users {
       id
   }
}
```

Both debug logs output is 

```javascript
query {
   users {
       id
      name
   }
}
```

and my resolver and Prisma instantiate is

```javascript
const resolvers = {
	Query: {
		users: (root, args, ctx, info) => {
			return ctx.prisma.users(args, info)
		},
	},
	Mutation: {
		createUser: (root, args, ctx, info) =>
			ctx.prisma.mutation.createUser({ data: { name: args.name } }, info),
	},
}

const server = new GraphQLServer({
	typeDefs,
	resolvers,
	context: req => ({
		...req,
		prisma: new Prisma({
                              typeDefs,
                              endpoint: `http://localhost:4466`,
                              debug: true
                 })
	}),
})

server.start(() => console.log('Server is running on http://localhost:4000'))
```

**To Reproduce**
1. Go to 'prisma init and generate javascript example'
2. add code above in `index.js` on root of project 
3. add `graphql-yoga` and `prisma-client-lib` 
4. see logs of the debug on Prisma

**Expected behavior**
Expected same logs with similar development using lib `prisma-binding`

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.32.2
 - `prisma` CLI: prisma/1.32.2 (darwin-x64) node-v11.8.0
 - OS: OS X Mojave 
 - other dependencies: prisma-client-lib:1.32.2

**Comment by pantharshit00** [comment]
This is expected. We have removed the selection set in the prisma client. Use type resolvers instead https://www.prisma.io/tutorials/a-guide-to-common-resolver-patterns-ct08/#scenario-implementing-relations-with-prisma-client

If you want something like older experience, use nexus-prisma: https://github.com/prisma/nexus-prisma
