### ISSUE TITLE
New count functionality

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#4527]
The latest DMMF from the query engine introduced a new feature as a side-effect of working on group by:
Being able to not just count by `*`, but specific columns, which can give a different result, if a column has NULL values.
Right now we don't expose this with the Client, but we should.
Proposal for the API:

```ts
prisma.user.count({
  field: 'id'
})
```

```ts
prisma.user.aggregate({
  count: true
})
```

and

```ts
prisma.user.aggregate({
  count: {
    $all: true
  }
})
```

**Comment by matthewmueller** [comment]
Maybe

```js
prisma.user.aggregate({
  count: {
    '*': true
  }
})
```

?

**Comment by timsuchanek** [comment]
Yes, but how would you then access the result? `result.count['*']` looks a bit clunky.
`_all` should probably also be called `$all` to prevent potential conflicts.

**Comment by Sytten** [comment]
You usually use the count column with the DISTINCT keyword so I would plan a syntax thar would support that eventually without breaking change.

**Comment by timsuchanek** [comment]
Thanks @Sytten, that's definitely a good point!
Our schema validation doesn't allow using underscores for field names:
![image](https://user-images.githubusercontent.com/1094804/103278534-fc005100-49cb-11eb-9ac0-f6904a3cc55d.png)

So it's safe to keep using `_all`. However, to be consistent with the rest of the API, I suggest using a `$all` instead. That also gets validated in the schema:
![image](https://user-images.githubusercontent.com/1094804/103278731-7f21a700-49cc-11eb-8986-2d2e50d86b0f.png)

The `*` would be a bit unnatural to access, as it is not a valid variable name in JS and needs the brackets around it:
```ts
const result = await prisma.user.aggregate({
  count: {
    '*': true
  }
})
result.count['*']
```

With `$all`, we can just access it like this:
```ts
const result = await prisma.user.aggregate({
  count: {
    $all: true
  }
})
result.count.$all
```

Accessing any other field can look like this:
```ts
const result = await prisma.user.aggregate({
  count: {
    name: true,
    city: { distinct: true } // not yet available, just to show it's possible
  }
})
```
The example above also shows, how it could work with distinct.
