### ISSUE TITLE
Self relation where query is not returning results

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#4536]
**Describe the bug**
I have set up a type with a self-relation (see below), with the aim to create a nested folder structure where the top item has no parent, but you can create sub-folders by providing the parent folder id

```graphql
type Folder {
  id: ID! @id
  name: String!
  parent: Folder @relation(name: "FolderRelation", link: INLINE)
}
```

**To Reproduce**
1. Create a top level folder:
```graphql
mutation {
  createFolder(data: {
    name: "Top level"
  }) {
    id
  }
}
```
2. Create a Sub-folder with the previously created folder as the parent
```graphql
mutation {
  createFolder(data: {
    name: "Bottom level",
    parent: {
      connect: {
        id: "cjvkag5n3006d0753eymur5pr"
      }
    }
  }) {
    id
  }
}
```
3. Run the following query using ID of the parent of subfolder
```graphql
query {
  folders(where: {
    parent: {
      id: "cjvkag5n3006d0753eymur5pr"
    }
  }) {
    id
    name
  }
}
```
4. Prisma returns an empty array instead of the folder:
```graphql
{
  "data": {
    "folders": []
  }
}
```

**Expected behavior**
Prisma should return the subfolder:
```graphql
{
  "data": {
    "folders": [
      {
        "id": "cjvnwf64s001m082346rgp74d",
        "name": "Bottom level"
      }
    ]
  }
}
```

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.32.2
 - `prisma` CLI: prisma/1.32.2 (darwin-x64) node-v12.2.0
 - OS:  MacOS 10.14.3 Mojave

**Additional context**
Ref: https://www.prisma.io/forum/t/self-relation-query-is-not-returning-any-results/6971

**Comment by do4gr** [comment]
Can you please check whether this is already fixed in the latest version? I fixed this issue https://github.com/prisma/prisma/issues/4508 which sounds very similar  in 1.33

**Comment by do4gr** [comment]
This is fixed now.
