### ISSUE TITLE
Incorrect PrismaClientKnownRequestError

### ISSUE THREAD

**Issue by vedantroy** [prisma/prisma#4543]
## Bug description

I cannot pass in the following object with the property `semanticType` set to `null` or `undefined` even though in the Prisma Schema, this property is an optional enum:

```
// Data passed into `prisma.extractionRule.create`
{
  data: {
    semanticType: null,
    id: '9f553af6-a6c1-4245-9c5b-22d6e687e6bf',
  }
}
```

I receive the following error:

```
  PrismaClientKnownRequestError3 @PrismaClientKnownRequestError {
    clientVersion: '2.13.0-dev.93',
    code: 'P2011',
    meta: {
      constraint: [
        'semanticType',
      ],
    },
  }
```
## How to reproduce

Look at my schema.

## Expected behavior

I can pass in `semanticType` with the value `undefined` (or `null`, not sure which one) into `extractionRule.create` and I won't get the above error:

## Prisma information

Relevant information:

```
model ExtractionRule {
  id          String    @id
  semanticType SemanticType?
}

enum SemanticType {
    X
    Y
}
```

## Environment & setup

```
@prisma/cli          : 2.13.0-dev.93
@prisma/client       : 2.13.0-dev.93
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine c497f3b49d089965e74485c540eb84ef0fbbcf0d (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli c497f3b49d089965e74485c540eb84ef0fbbcf0d (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core c497f3b49d089965e74485c540eb84ef0fbbcf0d (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt c497f3b49d089965e74485c540eb84ef0fbbcf0d (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.327.0
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this with `2.13.0-dev.98`. 

![image](https://user-images.githubusercontent.com/22195362/101476830-57fb2b00-3974-11eb-8806-db2b90560879.png)


Please try again with the latest version and if you can still reproduce this, please share a reproduction inside of a git repo.

**Comment by vedantroy** [comment]
I can't reproduce -- most likely this is an error on my side. I'll re-open this if I can create a reproduction with a git repository.
