### ISSUE TITLE
Docker-compose mySQL setup error, when using Init

### ISSUE THREAD

**Issue by thomasjensen1194** [prisma/prisma#4556]
**Describe the bug**
When setting up MySQL through the init CLI command, it creates a file with schema in the docker-compose file. However the composed docker container then throws an error saying that "schema" is only usable with PostgreSQL, and "database" should be used for the key instead. So changing the key "schema" to "database" fixed the issue for me.
Also when trying to connect to the docker service with prisma deploy, it will throw the error: `No cluster could be found for workspace '*' and cluster 'default'`

The docker-compose.yml file created through the CLI init command, should have "database" as the key instead of "schema" when MySQL is selected as the database type.

**To Reproduce**
Install version 1.33 of Prisma
Run prisma init and follow the CLI guide.

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server: 1.33
 - `prisma` CLI: 1.33 node-v11.11.0
 - OS: Windows 10

**Comment by divyenduz** [comment]
Is the underlying server protected via a `PRISMA_MANAGEMENT_API_SECRET`? If yes, can you provide that via an environment variable and try again?

**Comment by thomasjensen1194** [comment]
It is not protected, which I don't consider a requirement for a demo project. The exact same error happens when going through the prisma.io cloud setup, and choosing your own database for the prisma server. The deployment to heroku fails when selecting a mySQL database, because of `2019-05-24T17:57:31.650978+00:00 app[web.1]: Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: com.prisma.config.InvalidConfiguration: Only Postgres connectors are allowed to configure schema and database. For others please use database.`
