### ISSUE TITLE
Throw an error when give empty string with non-nullable property

### ISSUE THREAD

**Issue by kingRayhan** [prisma/prisma#4567]
When I put an empty string to a non-nullable string property, Prisma is saving my data, but I expect an error.

![image](https://user-images.githubusercontent.com/7611746/58052088-bd5eaf80-7b75-11e9-89a5-6b8750d325ac.png)

![image](https://user-images.githubusercontent.com/7611746/58052058-a61fc200-7b75-11e9-92be-2ea407651377.png)

**Comment by divyenduz** [comment]
An empty string is a valid string and not equivalent of null. It would fail at `body: null` but this behavior looks expected to me.

**Comment by gustawdaniel** [comment]
@divyenduz I agree with your comment but anyway we can ask question:

How to validate incoming data on prisma to prevent setting empty string. I looking for validator for email address. In framework like symfony 4 we have

> https://symfony.com/doc/current/reference/constraints/Email.html

But in prisma I can't find something analogical.

**Comment by kingRayhan** [comment]
@gustawdaniel 
Currently, I'm using joi for validation. You can use this.
https://github.com/hapijs/joi
