### ISSUE TITLE
Prisma Migrate: Error creating shadow database

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#4571]
## Problem

Users run into this issue if their database user has no privileges to create databases (MySQL / Postgres). This happens because Migrate tries to create a shadow database under the hood.

```
> DATABASE_URL="postgres://prismatest:prismatest@localhost:5432/prismatest" npx prisma migrate dev --preview-feature
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "prismatest", schema "public" at "localhost:5432"
2020-12-08 17:22:21.346 WET [11179] ERROR:  relation "_prisma_migrations" does not exist at character 126
2020-12-08 17:22:21.346 WET [11179] STATEMENT:  SELECT "id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count" FROM "_prisma_migrations" ORDER BY "started_at" ASC
2020-12-08 17:22:21.347 WET [11179] ERROR:  permission denied to create database
2020-12-08 17:22:21.347 WET [11179] STATEMENT:  CREATE DATABASE "prisma_migrations_shadow_database_8e443e23-bb18-4c98-8903-8777da7f625b"
Error: A migration failed when applied to the shadow database:
Database error: Error querying the database: db error: ERROR: permission denied to create database
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:172
   1: sql_migration_connector::sql_database_migration_inferrer::calculate_drift
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:59
   2: migration_core::api::DiagnoseMigrationHistory
             at migration-engine/core/src/api.rs:148
```

Some of the situations where this might be the case:

* Running DBMS locally but user has insufficient privileges -> Possible resolution: grant privileges. We should improve the user-facing error and document this properly
* Using a cloud-hosted DB for development, where creating additional databases is probably not supported -> Possible resolution: make the shadow DB URL configurable

## Additional context 
* [Slack conversation with user on Heroku](https://prisma-company.slack.com/archives/C01FZ9PKQ86/p1607448361115600)

**Comment by Jolg42** [comment]
You can find more info in our docs here https://www.prisma.io/docs/concepts/components/prisma-migrate#shadow-database
<img width="553" alt="Screen Shot 2020-12-10 at 10 51 17" src="https://user-images.githubusercontent.com/1328733/101755855-aaa02880-3ad5-11eb-9d23-72fd8826d097.png">

**Comment by albertoperdomo** [comment]
User-facing error message (draft):

```
Prisma Migrate could not create the shadow database. Please make sure the database user has permission to create databases.  More info: https://pris.ly/d/migrate-shadow
```

The link https://pris.ly/d/migrate-shadow should be added to Prisly and it can point to https://www.prisma.io/docs/concepts/components/prisma-migrate#shadow-database

**Comment by Jolg42** [comment]
https://pris.ly/d/migrate-shadow is live

**Comment by BearJS** [comment]
I am having this issue with a cloud hosted PostgreSQL db hosted on Heroku. I don't have that much knowledge on databases so is anyone able to point me in the right direction for resolving this?

It appears that Heroku hosted PostgreSQL dbs are not able to have superusers https://help.heroku.com/IV1DHMS2/can-i-get-superuser-privileges-or-create-a-superuser-in-heroku-postgres

**Comment by BearJS** [comment]
I am thinking I need to create and connect to a local postgreSQL db, runs `prisma migrate dev --preview-feature` to initialize a new migration history?

**Comment by BearJS** [comment]
For anyone like me who is a newbie to databases and who are using a cloud-hosted db for development, you can fix by doing the following:

1. Set up a local db. I am using PostgreSQL and followed this guide: https://www.codementor.io/@engineerapart/getting-started-with-postgresql-on-mac-osx-are8jcopb
2. Change your prisma .env file to local db
3. Delete prisma/migrations folder
4. Run `npx prisma migrate dev --preview-feature` to start a new migration
5. Change your prisma .env file back to development db
6. Run `npx prisma migrate resolve --applied "{{MIGRATION_NAME_FROM_STEP_4}}"  --preview-feature`


Hope that helps

**Comment by perryraskin** [comment]
@BearJS I got up to step 6 of your instructions, but I'm unfortunately getting this error: `Error: Failed to read migration script`. What was your migration name? I named it "prisma-preview" and I ran the following:

```
npx prisma migrate resolve --applied "prisma-preview" --preview-feature
```

**Comment by tomhoule** [comment]
@perryraskin thanks for sharing the root cause of your problem — we'll look into improving the UX there soon!

**Comment by garytube** [comment]
I find this quite a big issue since not everyone will host an own database server in this "serverless era" we live in now.

We have to  stick to 2.12 in the meantime

**Comment by albertoperdomo** [comment]
For those of you who are unable to use Prisma Migrate because you are using a cloud provider where it's not possible to create a shadow database, @garytube @perryraskin @BearJS.

This is going to be addressed via https://github.com/prisma/prisma/issues/4751, which is the issue you should be tracking.

We are closing #4571 as we shipped a better error message when failing to create the shadow database (available in 2.13.1).

**Comment by nikolasburk** [comment]
I just want to add a quick note for folks coming here from googling the error message that if you are currently prototyping and don't care about the generated migration files, you can also run `prisma db push` instead of the `prisma migrate dev` command:

```
npx prisma db push --preview-feature
```

**Comment by albertoperdomo** [comment]
The required priviliges required for Prisma Migrate to manage the shadow database are documented here: https://www.prisma.io/docs/concepts/components/prisma-migrate#shadow-database-user-permissions

**Comment by Ed344** [comment]
> npx prisma db push --preview-feature

It works. Thanks

**Comment by adeel55** [comment]
I think there should be a parameter like: prisma migrate dev --name prisma-preview --no-shadow-db

**Comment by Jolg42** [comment]
@adeel55 so we now have a doc page about the shadow database, how it works and why it's needed to generate migrations.

See https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database

Note: The shadow database is only required in a development environment (specifically for the prisma migrate dev command).

**Comment by deadcoder0904** [comment]
I'm trying to make Prisma work with [SyncInc](https://syncinc.so) which converts Airtable into Postgres.

Can someone help me with using `npx prisma migrate dev --name init` command? I'm unable to make it work even though I have `CREATE DB` permissions for my user locally.

Here's a sample repro → https://github.com/deadcoder0904/syncinc-prisma

Airtable base link → https://airtable.com/invite/l?inviteId=invvPQbKJ7xRfZ5oX&inviteToken=eeb63530dca64c6c768c735245b5d463f6cbaa44700eabfa05bf0ee8e53e2df8

All you need to do is:

1. Clone the Airtable base to your Airtable account
2. Create an account on SyncInc
3. Clone the repo, change `.env.local` to `.env` & substitute proper values
4. Try running `npx prisma migrate dev --name init`

Will take tops 10 mins. Idk if it's a problem locally or with SyncInc. Sometimes I get insufficient permissions error, sometimes it says drift detected & asks for reset but then when I type `yes`, it says `must be owner of table _sync_meta`.

Idk how to make it work :(

**Comment by janpio** [comment]
Can you put this into a new issue @deadcoder0904? Will play with it later, but would prefer to leave the answer (or follow up question) in a place that is only about this problem and does not notify many other people. Thanks.

**Comment by deadcoder0904** [comment]
@janpio I put it in the correct issue as I get this error only. Do you still want me to open another issue?

**Comment by janpio** [comment]
Yes please @deadcoder0904.

**Comment by deadcoder0904** [comment]
Asked as a discussion → https://github.com/prisma/prisma/discussions/6504 (you can delete my comments here)

**Comment by abdelopx** [comment]
> @abdelopx Did you check https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database maybe?
> 
> 
> 
> If this is still an issue, could you create [an issue here](https://github.com/prisma/prisma/issues/new/choose) or a [discussion here](https://github.com/prisma/prisma/discussions) with more info?
> 
> 

Thanks ! The link fixed it !

**Comment by nrgapple** [comment]
I am getting this same error running a local docker-compose file.

```docker-compose
version: "3.1"

services:
  db:
    image: postgres:13
    restart: always
    container_name: pg
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: prisma
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
volumes:
  postgres: ~
```

```
npx prisma migrate dev --name init   
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "prisma", schema "public" at "localhost:5432"

Error: P1010: User `johndoe` was denied access on the database `prisma.public`
```

This docs say to reference this issue but I don't see any solution.

> If you are developing against a cloud-based database (for example, on Heroku), we recommend that you change to a local web environment (such as running your development database on Docker) for the time being and follow the discussions on GitHub issue #4571.

**Comment by janpio** [comment]
Are you using a current version of Prisma @nrgapple? I think the current ones should have a better error message and link to a useful documentation page.

**Comment by fharaujo** [comment]
> For anyone like me who is a newbie to databases and who are using a cloud-hosted db for development, you can fix by doing the following:
> 
> 1. Set up a local db. I am using PostgreSQL and followed this guide: https://www.codementor.io/@engineerapart/getting-started-with-postgresql-on-mac-osx-are8jcopb
> 2. Change your prisma .env file to local db
> 3. Delete prisma/migrations folder
> 4. Run `npx prisma migrate dev --preview-feature` to start a new migration
> 5. Change your prisma .env file back to development db
> 6. Run `npx prisma migrate resolve --applied "{{MIGRATION_FOLDER_NAME_GENERATED_BY_STEP_4}}"  --preview-feature`
> 
> Hope that helps

I just took one more step here. To update my database.

>7. Run `npx prisma migrate reset`

**Comment by Jolg42** [comment]
Note that this issue is closed, if you are still having some issues with a newer version of Prisma creating a new issue would be greatly appreciated 😃

**Comment by nikolasburk** [comment]
For anyone still running into this issue, you can resolve this by defining the `shadowDatabaseUrl` on the `datasource` block as documented [here](https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database#cloud-hosted-shadow-databases-must-be-created-manually):

```prisma
datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}
```

If you're a cloud provider like Heroku, you can create a second DB there and use it as your shadow DB.

**Comment by ibraim6** [comment]
still dont work with shadowDatabaseUrl

**Comment by janpio** [comment]
Then open a new issue please @ibraim6 and describe the full problem. Usually that works fine.

**Comment by vaclav-stummer** [comment]
Firstly I want to say I am a big Prisma fan. But unfortunately I keep finding out problems which doesn't have solutions.

The original problem is still occurring on version `3.10.0`. I tried all the above including shadow DB suggestions and the problem still persists. Many people these days developing with `docker-compose` and this seems a big issue

https://github.com/prisma/prisma/issues/4571#issuecomment-1046046864

**Comment by janpio** [comment]
Same answer to you then @vaclav-stummer: Please open a new issue and describe the full problem. We are not aware of any reports of problems with the shadow database that still stand after we looked at them.

**Comment by vaclav-stummer** [comment]
New issue created here: https://github.com/prisma/prisma/issues/12100

**Comment by Codigo-Fuentes** [comment]
> For anyone like me who is a newbie to databases and who are using a cloud-hosted db for development, you can fix by doing the following:
> 
> 1. Set up a local db. I am using PostgreSQL and followed this guide: https://www.codementor.io/@engineerapart/getting-started-with-postgresql-on-mac-osx-are8jcopb
> 2. Change your prisma .env file to local db
> 3. Delete prisma/migrations folder
> 4. Run `npx prisma migrate dev --preview-feature` to start a new migration
> 5. Change your prisma .env file back to development db
> 6. Run `npx prisma migrate resolve --applied "{{MIGRATION_FOLDER_NAME_GENERATED_BY_STEP_4}}"  --preview-feature`
> 
> Hope that helps

I love you.

**Comment by tanvir-ux** [comment]
> 

Thanks a lot, bro. I was stuck for 2 days in between docker, windows, prisma and postgresql with 100+ tabs opened. Now, I can move on.

**Comment by tanvir-ux** [comment]
@BearJS Thanks a lot bro. I was stuck for 2 days in between docker, windows, postgresql and prisma with 100+ tabs opened. Finally, I can move on.

For anyone like me who is a newbie to databases and who is using a cloud-hosted db for development, you can fix this by doing the following:

Set up a local db. I am using PostgreSQL and followed this guide: https://www.codementor.io/@engineerapart/getting-started-with-postgresql-on-mac-osx-are8jcopb
Change your prisma .env file to local db
Delete prisma/migrations folder
Run npx prisma migrate dev --preview-feature to start a new migration
Change your prisma .env file back to development db
Run npx prisma migrate resolve --applied "{{MIGRATION_FOLDER_NAME_GENERATED_BY_STEP_4}}" --preview-feature
Hope that helps

**Comment by BenMcLoughlin** [comment]
I was working with a heroku postgres db and was getting this error. So I created two apps in Heroku with two seperate db urls. then I set the second one as the shadow db. 

in my .env 
DATABASE_URL='db_url_from_heroku_app_1"
SHADOW_DATABASE_URL='db_url_from_heroku_app_2"

in the schema.prisma
`datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}`

Then I ran 
` npx prisma db push `

and then 

`npx prisma migrate dev --name init`

and I got my migrations file.

**Comment by shide1989** [comment]
For those like who don't want to search and waste time, in your local env you should use the `shadowDatabaseUrl = env("SHADOW_DATABASE_URL")` config, and setup a second DB in your local env.

This is a new concept, but it's worth it and you won't have anymore problems creating migrations normally.

**Comment by AuthorOfTheSurf** [comment]
I ran into this while attempting to set up a redwood app with an app-specific database user:

I thought that this GRANT would be sufficient

```psql
GRANT ALL PRIVILEGES ON DATABASE my_app_dev TO my_app;
```

But it doesn't actually grant CREATEDB to the `my_app` user

I needed to hop back into `psql` and use ALTER USDER:

```psql
ALTER USER my_app CREATEDB;
```

Can confirm that "Create DB" access has been granted with `\du`:

```psql
                                       List of roles
     Role name     |                         Attributes                         | Member of 
-------------------+------------------------------------------------------------+-----------
 my_app            | Create DB                                                  | {}
 postgres          | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```

In the end I have a local postgres user called `my_app` that can do whatever it wants with `my_app_dev` database. So I am not reliant on the top-level user called `postgres` or `<machine_name>`. This was my intention

P.S. Here is my connection string in case it may help anyone:

```
# The password is "password" in my case
DATABASE_URL=postgres://my_app:password@localhost:5432/my_app_dev
```

**Comment by n5sgg** [comment]
For anyone using MySQL, Prisma creates and drops a bunch of `prisma_migrate_shadow_db_[UUID]` databases. So if your user only has access to the app DB it will fail. Assuming your user configured in .env is johndoe, this will work:
```sql
GRANT CREATE, DROP ON *.* TO johndoe@'%';
```

I have a few issues with this. The command output is not clear at all, because it says "User johndoe was denied access on the database mydb", when in fact it had access to that db, but not to create other dbs. This should be better documented. And an even bigger concern, by allowing CREATE and DROP in all databases, we're compromising the security and not following least privilege principle. In MySQL there's no way to grant create and drop for a particular DB prefix, so the only way it can work is by allowing wildcard.

**Comment by Jolg42** [comment]
@n5sgg Thanks for the feedback. I think in this case, which is probably not obvious in our docs, you could use the `shadowDatabaseUrl` property to define the shadow database name permanently. Meaning, you can then grant permissions for create and drop only for that database, eliminating the security risk of the wildcard.

See https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database#cloud-hosted-shadow-databases-must-be-created-manually
```
datasource db {
  provider          = "mysql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}
```

**Comment by n5sgg** [comment]
Thanks @Jolg42, it worked fine. I've created a hello-prisma repo using mysql and docker-compose in case this helps anyone: https://github.com/n5sgg/hello-prisma

**Comment by LeCongNam** [comment]
if you using mysql with docker. you must using Account **root**. I'm don't know why Prisma required **Root Account**. If using DB from Cloud Share is not fix :)

**Comment by janpio** [comment]
You do not need to use a `root` account. You just need to use an account that can execute `CREATE DATABASE`. Otherwise you can define the `shadowDatabaseUrl` to an already existing database.

**Comment by isaacgr** [comment]
> @n5sgg Thanks for the feedback. I think in this case, which is probably not obvious in our docs, you could use the `shadowDatabaseUrl` property to define the shadow database name permanently. Meaning, you can then grant permissions for create and drop only for that database, eliminating the security risk of the wildcard.
> 
> See https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database#cloud-hosted-shadow-databases-must-be-created-manually
> 
> ```prisma
> datasource db {
>   provider          = "mysql"
>   url               = env("DATABASE_URL")
>   shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
> }
> ```

I did this, but when I run 'npx prisma migrate dev' it still attempts to use the credentials defined for the 'url'. Any  idea why?

**Comment by Jolg42** [comment]
@isaacgr Could you open a new issue with more details about this?

**Comment by isaacgr** [comment]
> @isaacgr Could you open a new issue with more details about this?

https://github.com/prisma/prisma/issues/20690

**Comment by coderunner86** [comment]
You can also run npx prisma db push

**Comment by newerton** [comment]
I had the same problem with migration, downgrading to 5.9.1 worked.

Error with version (5.12.1, 5.12.0, 5.11.0, 5.10.2, 5.10.1 and 5.10.0)
```cli
Error: P1017
Server has closed the connection.
```

Error log
```log
postgresql 21:05:14.77 INFO  ==> ** Starting PostgreSQL **
LOG:  pgaudit extension initialized
LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
LOG:  listening on IPv4 address "0.0.0.0", port 5432
LOG:  listening on IPv6 address "::", port 5432
LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
ERROR:  relation "_prisma_migrations" does not exist at character 126
STATEMENT:  SELECT "id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count" FROM "_prisma_migrations" ORDER BY "started_at" ASC
FATAL:  terminating connection due to administrator command
LOG:  checkpoint starting: immediate force wait
LOG:  checkpoint complete: wrote 7 buffers (0.0%); 1 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.003 s, total=0.033 s; sync files=6, longest=0.002 s, average=0.001 s; distance=4258 kB, estimate=4258 kB; lsn=0/1D52BC0, redo lsn=0/1D52B88
```

Postgres: https://artifacthub.io/packages/helm/bitnami/postgresql
Version: 16.2.0


Prisma Version
```cli
Environment variables loaded from .env
Environment variables loaded from src\_core\@shared\infrastructure\adapters\persistence\database\prisma\.env
prisma                  : 5.9.1
@prisma/client          : 5.12.1
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v18.19.1
Query Engine (Node-API) : libquery-engine 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-32.23fdc5965b1e05fc54e5f26ed3de66776b93de64
Default Engines Hash    : 23fdc5965b1e05fc54e5f26ed3de66776b93de64
Studio                  : 0.497.0
```

**Comment by ben-harris-5** [comment]
@newerton I experienced the same issue too, and reverting to 5.9.1 also worked for me!

**Comment by sadeeabdullah** [comment]
I was confronting the same issue.
 Here is the solution  (https://satisfyhost.com/blog/prisma-migrate-could-not-create-the-shadow-database/) that
 i followed the blog and solved the problem in a moment.

**Comment by Abdulrehman3802** [comment]
> @n5sgg Thanks for the feedback. I think in this case, which is probably not obvious in our docs, you could use the `shadowDatabaseUrl` property to define the shadow database name permanently. Meaning, you can then grant permissions for create and drop only for that database, eliminating the security risk of the wildcard.
> 
> See https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database#cloud-hosted-shadow-databases-must-be-created-manually
> 
> datasource db {
>   provider          = "mysql"
>   url               = env("DATABASE_URL")
>   shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
> }


If you encounter permission issues while creating a shadow database with Prisma, try adding this configuration in your `schema.prisma`. This resolves the problem as some hosting providers restrict DB users from creating new databases. Thanks to @Jolg42 for the helpful tip!

**Comment by luiz00martins** [comment]
> https://pris.ly/d/migrate-shadow is live

Broken link. I assume the new one is: https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/shadow-database.
