### ISSUE TITLE
db error: ERROR: permission denied to create database

### ISSUE THREAD

**Issue by medz** [prisma/prisma#4578]
## Bug description

It is true that the scene does not give the account the right to create a database, at most it gives the right to create a data table. Therefore, the error reported here should not be.

Moreover, the migration file will only generate SQL for creating data tables, and there is no need to create database permissions.

Run: `npx prisma migrate dev --preview-feature`:

```bash
Error: A migration failed when applied to the shadow database:


Database error: Error querying the database: db error: ERROR: permission denied to create database
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:172
   1: sql_migration_connector::sql_database_migration_inferrer::calculate_drift
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:59
   2: migration_core::api::DiagnoseMigrationHistory
             at migration-engine/core/src/api.rs:148
```

**Comment by pantharshit00** [comment]
This is known and will be addressed. Please follow: https://github.com/prisma/prisma/issues/4571

Right now migrate uses a shadow database to apply migrations in a safe way but this setup is not ideal for situations you mentioned so it will be addressed.
