### ISSUE TITLE
Error: Expected [object Object] to be a GraphQL schema.

### ISSUE THREAD

**Issue by KumarAbhirup** [prisma/prisma#4579]
**Describe the bug**
I am seeing this 👇
```
Error: Expected [object Object] to be a GraphQL schema.
--
May 24 2019 07:13:35:271    at invariant (/home/nowuser/src/node_modules/apollo-server-core/node_modules/graphql/jsutils/invariant.js:19:11)
May 24 2019 07:13:35:315    at validateSchema (/home/nowuser/src/node_modules/apollo-server-core/node_modules/graphql/type/validate.js:55:60)
May 24 2019 07:13:35:374    at assertValidSchema (/home/nowuser/src/node_modules/apollo-server-core/node_modules/graphql/type/validate.js:80:16)
May 24 2019 07:13:35:425    at Object.validate (/home/nowuser/src/node_modules/apollo-server-core/node_modules/graphql/validation/validate.js:58:35)
May 24 2019 07:13:35:445    at doRunQuery (/home/nowuser/src/node_modules/apollo-server-core/dist/runQuery.js:111:42)
May 24 2019 07:13:35:466    at /home/nowuser/src/node_modules/apollo-server-core/dist/runQuery.js:21:56
May 24 2019 07:13:35:487    at <anonymous>
May 24 2019 07:13:35:507    at process._tickCallback (internal/process/next_tick.js:188:7)
```

On the PlayGround, I see this 👇
![Screenshot 2019-05-24 at 7 17 10 AM](https://user-images.githubusercontent.com/25429790/58297072-f99f4380-7df3-11e9-95cf-dc09146768bc.jpg)

**To Reproduce**
1. Here's the complete [repository](https://github.com/KumarAbhirup/paprink-backend) to clone
2. Create a `.env` file that contains 👇
```
NODE_ENV="production"
ENDPOINT="https://prodpaprink-5f26e1e0b6.herokuapp.com/paprink-backend/prod"
FRONTEND_URL="."..
PROD_FRONTEND_URL="..."
GOOGLE_LOGIN_APP_ID="..."
JWT_SECRET="..."
GRAPH_ACCESS_TOKEN="..."
FB_APP_SECRET="..."
FB_APP_ID="..."
PRISMA_SECRET="..."
```
3. Run `now --dotenv .env`
4. Visit the deployment and see the error or check the `now logs`

**Expected behavior**
I expected the error to not appear just like it didn't on `heroku`... but due to DNS problems, I am trying to host it on `now`.
The same code works on `heroku` when deployed using GitHub 👉 [https://paprink-server.herokuapp.com](https://paprink-server.herokuapp.com)

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: `1.32.2`
 - `prisma` CLI: `prisma/1.31.1 (darwin-x64) node-v11.4.0`
 - OS: `OSX Mojave`
 - other dependencies: `prisma-client-lib`, `prisma-binding`, `graphql-yoga`, `graphql-cli`, and `graphql`

**Additional context**
Thanks for helping 🙏

**Comment by pantharshit00** [comment]
This is caused by the classic duplicate graphql module compatibility(https://github.com/graphql/graphql-js/issues/491). One of the errors that plagued all of the graphql package users when v14 was released. You are using graphql-cli which asks for graphql v0.13 as a peer dep. GraphQL version `0.13.x` is not compatible with `14.x`. To solve this use yarn and add the following to the package.json:

```js
{
  // ...
  "dependencies":{
      "graphql":"14.3.1"
       // ...
  },
  "resolutions":{
      "graphql": "14.3.1"
   },
}
```

For me, it happened locally as well. So I will also recommend to `rm -rf node_modules && yarn` after you have added these.

Here is working now deploy(I have just re-enabled the playground in prod for demonstration): https://paprink-backend-juieyjlzdf.now.sh/
