### ISSUE TITLE
Prisma as submodule/dependency

### ISSUE THREAD

**Issue by ragnorc** [prisma/prisma#458]
In order to avoid redundant code, I currently have the prisma folder with the schema and the migration files in a separate repo and then add it to projects that use the database as a submodule. Because continuous deployment providers like [Zeit](https://spectrum.chat/zeit/now/problems-with-now-github-when-project-contains-a-submodule~f238f86b-7a42-47f7-a477-0976ca0da1a5?m=MTU0ODg5MTQ0Njk0NA==) or Netlify don't support (private) submodules, I had to make use of subtree, which is also not the cleanest solution to manage dependencies. What is the recommended way of dealing with Prisma as a dependency in multiple projects?

**Comment by schickling** [comment]
Can you elaborate please what you mean by "redundant code" in this case? What would be the complications of keeping the `prisma` folder in the same repo when used with platforms like Zeit or Netlify?

**Comment by ragnorc** [comment]
Assuming that the same database is used in two different applications, I would need to include the `prisma` folder in both applications. 
If I then wanted to change the schema, I would need to synchronise the changes in both repos.

**Comment by matthewmueller** [comment]
Closing in favor of: https://github.com/prisma/prisma/issues/2558
