### ISSUE TITLE
[Telemetry] Warning: Telemetry call failed with javax.net.ssl.SSLHandshakeException: General SSLEngine problem

### ISSUE THREAD

**Issue by VRspace4** [prisma/prisma#4582]
**Describe the bug**
I'm seeing the following warning in the Prisma log, and it repeats almost every minute. I've tried deploying MySQL and Postgres on a local machine as well as through Prisma Cloud (https://www.prisma.io/cloud) with Postgres hosted on Heroku and I'm seeing the same repeating warning:
```
[Telemetry] Warning: Telemetry call failed with javax.net.ssl.SSLHandshakeException: General SSLEngine problem
```

**To Reproduce**
Deploy Prisma using the standard configuration and then view the log, shown below.

```
[INFO] Initializing workers...
[INFO] Obtaining exclusive agent lock...
[INFO] Successfully started 1 workers.
[INFO] Obtaining exclusive agent lock... Successful.
[INFO] Deployment worker initialization complete.
Server running on :53851
[Telemetry] Warning: Telemetry call failed with javax.net.ssl.SSLHandshakeException: General SSLEngine problem
[Telemetry] Warning: Telemetry call failed with javax.net.ssl.SSLHandshakeException: General SSLEngine problem
[Telemetry] Warning: Telemetry call failed with javax.net.ssl.SSLHandshakeException: General SSLEngine problem
[Telemetry] Warning: Telemetry call failed with javax.net.ssl.SSLHandshakeException: General SSLEngine problem
[Telemetry] Warning: Telemetry call failed with javax.net.ssl.SSLHandshakeException: General SSLEngine problem
[Telemetry] Warning: Telemetry call failed with javax.net.ssl.SSLHandshakeException: General SSLEngine problem
```
**Expected behavior**
The warning should not appear.

**Versions (please complete the following information):**
 - Connector: Postgres & MySQL
 - Prisma Server: 1.33
 - `prisma` CLI: N/A
 - OS: N/A (Tried both Windows 10 & one hosted on Heroku through Prisma Cloud)

**Comment by roffe** [comment]
seeing same errors on Prisma in Kubernetes with postgres database no idea where they are comming from

**Comment by jayanth1991** [comment]
I see the same on my local Docker setup.

**Comment by roffe** [comment]
The error has now turned into `[Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed`

I suspect the error is from the spyware part in Prisma where it reports usage statistics etc home.
Maybe the command center server is dead and thats why we are seeing the errors

**Comment by pantharshit00** [comment]
This has been fixed now 🎉

**Comment by uning** [comment]
| [Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.

**Comment by uning** [comment]
it appear now~

**Comment by RamanPndy** [comment]
These logs still coming
[Telemetry] Warning: Telemetry call failed with akka.http.impl.engine.client.pool.SlotState$BusyState$$anon$1: Connection was shutdown.
[Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.
[Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.
[Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.
[Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.
[Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.
[Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.
[Telemetry] Warning: Telemetry call failed with akka.stream.StreamTcpException: Connection failed.
[Telemetry] Warning: Telemetry call failed with akka.http.impl.engine.client.pool.SlotState$BusyState$$anon$1: Connection was shutdown.

**Comment by raeesaa** [comment]
Even we are seeing same error as @RamanPndy .
