### ISSUE TITLE
Your Prisma server and Prisma CLI are currently out of sync. They should be on the same minor version.

### ISSUE THREAD

**Issue by fantasychance** [prisma/prisma#4583]
hi everyone!

 my problem is

"Your Prisma server and Prisma CLI are currently out of sync. They should be on the same minor version." 

i Dont know Whats the problem.. how can i fix it? TT
![012345689](https://user-images.githubusercontent.com/49264769/58380258-dccc6100-7fe9-11e9-999a-c55ee01653a4.png)

Prisma CLI version: prisma/1.33.0 (windows-x64) node-v10.15.3
Prisma server version: 1.32.0-beta

so i try change .. remove prisma 1.33.0 
and i try yarn add prisma @1.32      <Prisma CLI version: prisma/1.33.0 ▶ 1.32.0>

when i "prisma deploy"
still show "Your Prisma server and Prisma CLI are currently out of sync. They should be on the same minor version." and
still i can not see the graphql **endpoint(prayground)** url link and prisma link in VSC terminal

but... it doesn't work TT what can i do.. I do not know what the problem is.
so i again install prisma 1.33.0

but still i have problem
whats the problem?
i want solve this problem
please help me

----

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Connector: [e.g. `Postgres`, `MySQL`, `MongoDB`]
 - Prisma Server: [e.g. `1.24.0`]
 - `prisma` CLI: [e.g. `prisma/1.24.0 (darwin-x64) node-v10.4.0`]
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 
 - other dependencies: `prisma-client`, `prisma-binding`, etc. if applicable

**Additional context**

**Comment by pantharshit00** [comment]
@fantasychance 

This is just a warning and will not affect the CLI. This warning is thrown because sometimes mismatch of the CLI version can lead to unexpected behaviour. 

You can get rid of the warning by matching the prisma server version in the docker-compose.yml file or you can install `npm i -g prisma@<your prisma server version>` eg  `npm i -g prisma@1.24` to mitigate the warning

**Comment by rahulvyas1** [comment]
1. Update your docker file (server) to the latest Prisma version. 
2. Update your Prisma CLI to the latest version (same as the new docker version)

This worked for me.

**Comment by Riseley** [comment]
This is an unresolved bug because the warning itself is wrong. Why close this issue?
