### ISSUE TITLE
Can't upgrade my private hosted server via the Prisma console

### ISSUE THREAD

**Issue by RoryKelly** [prisma/prisma#4595]
**Describe the bug**
I can't upgrade my private hosted server via the Prisma console. I get a success message saying that the upgrade will be scheduled and run in 10 minutes but the upgrade never goes through.

I have been waiting several days. Anyone else have these issues?

trying to upgrade  from 1.24 to 1.33.

**To Reproduce**
1. Go to 'app.prisma.io' 
2. Click on 'upgrade cluster'
3. Receive success message
4. Cluster is never upgraded.

**Expected behavior**
Server upgrades proceed as normal.

**Additional context**
Trying to upgrade to new schema format.

**Comment by pantharshit00** [comment]
@RoryKelly 
Can you please share workspace slug? It is listed under settings

**Comment by RoryKelly** [comment]
curated.

**Comment by RoryKelly** [comment]
@pantharshit00 Any update? I email support and messaged on the Prisma website but have had no response.

**Comment by pantharshit00** [comment]
@RoryKelly 

Sorry for the late reply. We have manually upgraded your server version
