### ISSUE TITLE
ArangoDB support

### ISSUE THREAD

**Issue by thesobercoder** [prisma/prisma#4599]
## Problem

[ArangoDB](https://www.arangodb.com/) is a powerful multi-model database used by a lot of enterprise companies. It would be great addition to Prisma, especially for customers who are trying to adapt FSJAM stack.

## Suggested solution

Add support for ArangoDB in Prisma2 at the database level.

**Comment by janpio** [comment]
Thanks for opening this issue @thesobercoder. We have an earlier one for the same database which you can +1 or comment your use case on: https://github.com/prisma/prisma/issues/2535 I'll close this one as a duplicate.
