### ISSUE TITLE
Error: Error in migration engine. Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\6efc6f6\src\connector\postgres\error.rs:138:29] index out of bounds: the len is 1 but the index is 1 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4606]
Command: `prisma migrate dev --preview-feature`
Version: `2.13.0`
Binary Version: `833ab05d2a20e822f6736a39a27de4fc8f6b3e49`
Report: https://prisma-errors.netlify.app/report/12281 
OS: `x64 win32 10.0.19041`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\6efc6f6\src\connector\postgres\error.rs:138:29] index out of bounds: the len is 1 but the index is 1

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (D:\project\waaw-backend\node_modules\@prisma\cli\build\index.js:59340:23)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

Rust Stacktrace:
```
[C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\6efc6f6\src\connector\postgres\error.rs:138:29] index out of bounds: the len is 1 but the index is 1
```

**Comment by divyenduz** [comment]
From engine's error reporting meeting. The error is from quant, it needs more flexible error parsing (@do4gr)

**Comment by cincrain** [comment]
same here!

**Comment by cincrain** [comment]
command: `npx prisma migrate dev --create-only --preview-feature`
client, cli version: `2.13.0`
os env: `Windows 10 Home x64`

> PS E:\dev-fullstack\bim-server01> npx prisma migrate dev --create-only --preview-feature
> Environment variables loaded from .env
> Prisma schema loaded from prisma\schema.prisma
> Datasource "db": PostgreSQL database "bim", schema "bim" at "localhost:5432"
> 
> Oops, an unexpected error occured!
> Error in migration engine.
> Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\6efc6f6\src\connector\postgres\error.rs:138:29] index out of bounds: the len is 1 but the index is 1


```
// schema.prisma file

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

generator dbml {
  provider = "prisma-dbml-generator"
}

model User {
  id          Int       @id @default(autoincrement())
  email       String    @unique
  password    String?
  firstName   String?
  lastName    String?
  role        RoleType  @default(guest)

  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  deletedAt   DateTime?
}

enum RoleType {
  guest
  user
  premium
  admin
}
```

**Comment by SelfDevTV** [comment]
Same here: 

>Oops, an unexpected error occured!
>Error in migration engine.
>Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint->9f01e008b9a89c14\bc3aa8a\src\connector\postgres\error.rs:138:29] index out of bounds: the len is 1 but the index is 1

>Please create an issue in the migrate repo with
>your `schema.prisma` and the prisma command you tried to use 🙏:
>https://github.com/prisma/migrate/issues/new


It just happens when I use my local postgreSQL db. When I connect to my PostgreSQL AWS Cloud db it works and I don't get this error. 
I tried with: `yarn prisma migrate dev --create-only --preview-feature` and `yarn prisma migrate dev --preview-feature`

**Comment by dundich** [comment]
I had the same problem in Postgres
if template0 || template1 -> deleted or corrupted

just restore (rebuild) template0 (template1) and the migration should work

**Comment by sdoering01** [comment]
I had the same error with my locally installed postgres database. To my surprise it worked with a postgres database in a docker container created like this: `docker run --name prisma-test -e POSTGRES_PASSWORD=postgres -p 5433:5432 -d postgres:11`, only by changing the connection url in the .env file.
