### ISSUE TITLE
Vercel is not running `prisma generate` postinstall hook

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#4612]
## Bug description

When deploying the e2e example to vercel, it crashes on execution as `prisma generate` hook isn't ran by vercel.

![image](https://user-images.githubusercontent.com/22195362/101898555-575fd000-3bd2-11eb-815c-ce3d9de7f784.png)

## How to reproduce

Deploy this example to vercel using the CLI: https://github.com/prisma/e2e-tests/tree/dev/platforms/vercel-api

## Expected behavior

Postinstall hook should run and api should function.

## Workaround

Add `prisma generate` to the vercel-build hook in package.json.

## Environment & setup

- OS: Arch Linux
- Database: Postgres 11 
- Node.js version: 14.5.0 
- Prisma version:

```
Environment variables loaded from .env
@prisma/cli          : 2.14.0-dev.15
@prisma/client       : 2.14.0-dev.15
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 69d24397da64a3401c85f9d8d0ce20e102937255 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 69d24397da64a3401c85f9d8d0ce20e102937255 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 69d24397da64a3401c85f9d8d0ce20e102937255 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 69d24397da64a3401c85f9d8d0ce20e102937255 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.331.0
```

**Comment by timsuchanek** [comment]
This is fixed in the latest version
