### ISSUE TITLE
Nested Connect accept `null` if not required field

### ISSUE THREAD

**Issue by joshhopkins** [prisma/prisma#4613]
When passing a `null` value to `Connect` in nested object writes, Prisma throws an error. Providing the this field isn't required as per data model, Prisma could silently fail to make this connection. This would make it more consistent with other non-required fields.

**Comment by joshhopkins** [comment]
Ah so an empty object doesn't appear to work for either `Create` or `Connect`, but an empty array does. Good to know!

**Comment by pantharshit00** [comment]
Oh ya, for connect you need an empty array.

I think I can close this now

**Comment by joshhopkins** [comment]
Cool. Be good to see this in the docs somewhere.
