### ISSUE TITLE
How to intercept prisma queries to log metrics in to some monitoring system?

### ISSUE THREAD

**Issue by BrunoQuaresma** [prisma/prisma#4616]
I currently want to record some metrics such as query and runtime on a custom metric system. So by reading the docs, I have not seen if the prism-client provides something like an observer or a middleware for this.

**Comment by kshenes** [comment]
If you have a graphql north-bound public API in front of prisma, like Yoga you can use graphql-middleware. Not sure if that meets your needs.

**Comment by BrunoQuaresma** [comment]
It should works. Thanks.
