### ISSUE TITLE
Prisma CLI as a docker image

### ISSUE THREAD

**Issue by paniavula** [prisma/prisma#4618]
## Problem

Currently NodeJS and @prisma/cli needs to be installed to run any prisma CLI commands. This may not be possible in every environment.

## Suggested solution

Providing a docker based image for prisma cli, migrate etc would be quite helpful. Example - https://github.com/flyway/flyway-docker

**Comment by Jolg42** [comment]
I think another approach would be to package a binary of the CLI with Node.js, I think @steebchen does that in https://github.com/prisma/prisma-client-go with `pkg`

**Comment by janpio** [comment]
There does not be a big need for this, so closing for now. Thanks for opening an issue back in the day!
