### ISSUE TITLE
ECONNREFUSED : request to "URL" failed , reason:connect ECONNREFUSED 192.168.99.100:4466

### ISSUE THREAD

**Issue by tanujdoshi** [prisma/prisma#4626]
**Describe the bug**
i have tried prisma deploy 

in this my database name tvd@demo has been created but table user is not created , it will throw error :
 !    'ECONNREFUSED': request to http://192.168.99.100:4466/management failed, reason: connect ECONNREFUSED 192.168.99.100:4466

error::
```
PS C:\Users\DHRUMIT\Desktop\mysql-node\helloworld> prisma deploy
Creating stage demo for service tvd √
Deploying service `tvd` to stage `demo` to server `default` !
 !    'ECONNREFUSED': request to http://192.168.99.100:4466/management failed, reason: connect ECONNREFUSED 192.168.99.100:4466

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ export DEBUG="*"
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Connector: mysql
 - Prisma Server: 1.28.6
 - `prisma` CLI: 1.28.6
 - OS: Windows 10
 - other dependencies: `prisma-client`, `prisma-binding`, etc. if applicable

**Additional context**

**Comment by pantharshit00** [comment]
Hi,

Please make sure you have started your Prisma endpoint and it accessible in the endpoint.

If you are still not able to resolve this, please provide us with a reproduction
