### ISSUE TITLE
Import/export Deadlock Issue

### ISSUE THREAD

**Issue by Alosies** [prisma/prisma#4627]
**Describe the bug**
When I try to import data into prisma using the .zip file obtained through `prisma export`, when it comes to updating relations it throws a series of erros that look like the one below

`"Failure inserting into relationtable Question with ids StringIdGCValue(cjuzc7s4u03lm0869k0uk9tt2) and StringIdGCValue(cjkjgybxv002t0957fcwyh93k). Cause: deadlock detected\n  Detail: Process 76 waits for ShareLock on transaction 2676; blocked by process 75.\nProcess 75 waits for ShareLock on transaction 2681; blocked by process 76.\n  Hint: See server log for query details.\n  Where: while updating tuple (192,3) in relation \"Question\"",`

**To Reproduce**
Steps to reproduce(mostly) the behavior:
1. export a moderate size database through `prisma export`
2. import through `prisma import -d path`
Unfortunately, I am not able to share the exact file as the data is private. 

**Screenshots**
<img width="1440" alt="Screenshot 2019-06-04 at 11 14 04 AM" src="https://user-images.githubusercontent.com/24241029/58854094-ec1e6f00-86b9-11e9-8e2e-f471d147023b.png">

**Versions:**
 - Connector: `Postgres`
 - Prisma Server: `1.34.0`
 - `prisma` CLI: `prisma/1.34.0 (linux-x64) node-v10.16.0`
 - OS:  `Ubuntu Docker 5:18.09.6~3 on 18.04` 
 - other dependencies: `none

**Additional context**
The export.zip file is around 7MB. 
Digital Ocean Droplet with 2GB RAM
Postgres: Digital Ocean Managed Database with 2GB RAM

Any help on troubleshooting this issue is highly appreciated.

**Comment by pantharshit00** [comment]
Hi,

I am unable to reproduce, unfortunately. Right now import/export is also not that stable. We already issued a warning CLI about it. Try using native SQL dumps.

**Comment by Alosies** [comment]
When I try to do pg_restore first, do introspection and then do my queries, I find that a lot of related fields are missing. 

For Example:
```
type QuizLevel @model {
  id: ID! @id
  name: String
  uniqueName: String @unique
  levelOrder: Int
  course: Course @relation(name: "CourseQuizLevel")
  quizzes: [Quiz!]! @relation(name: "QuizLevel")
}
```

Successful query for Scalar fields:

<img width="1310" alt="Screenshot 2019-06-05 at 8 40 18 PM" src="https://user-images.githubusercontent.com/24241029/58967634-2da23d80-87d2-11e9-9a59-6ebf49721da5.png">

Failing Query for Relations:

<img width="1416" alt="Screenshot 2019-06-05 at 8 41 10 PM" src="https://user-images.githubusercontent.com/24241029/58967721-50cced00-87d2-11e9-91b9-408b09890a32.png">



Server Logs:

<img width="1440" alt="Screenshot 2019-06-05 at 8 43 10 PM" src="https://user-images.githubusercontent.com/24241029/58967858-9a1d3c80-87d2-11e9-8c94-e83839d5d69f.png">


The same query in my old server is running fine. 
<img width="1124" alt="Screenshot 2019-06-05 at 8 36 58 PM" src="https://user-images.githubusercontent.com/24241029/58967382-b5d41300-87d1-11e9-97db-29f748d2d4bd.png">

**Old Server and CLI Versions:**
Prisma CLI version: prisma/1.34.0 (darwin-x64) node-v11.6.0
Prisma server version: 1.11-beta-1

I'm trying to move my database from Heroku to Digital Ocean.

**Comment by pedrojardim** [comment]
Hi, I getting the same deadlock problem. 
But, I have a Data exported from GraphCool and I trying to Import on a Prisma Service, that has a Postgres DB.

**Comment by Alosies** [comment]
Where are you hosting the Postgres DB? and what is your prisma server version?

**Comment by Alosies** [comment]
I solved the issue by using prisma@1.30 and using postgres inside Docker.

**Comment by pedrojardim** [comment]
The Postgres DB is on Azure.
Prisma version is 1.34
The zip file has 32 MB.

**Comment by Alosies** [comment]
What is the server version from which you are trying to do the migration of data? Because apparently there is a change of structure from 1.31(I might be wrong about the exact number) onwards.

**Comment by pedrojardim** [comment]
Prisma CLI and Prisma server are the same. 1.34

**Comment by grimunit** [comment]
Getting the same thing but I'm just trying to go from 1.30 to 1.34 since doing the Heroku prisma creation with Prisma Admin forces it to be version 1.34. So it doesn't look like I can deploy to Heroku easily on 1.30.  I was just following along with the youtube video in the blog post and he specifically says to export the data and then it should be able to import to the 1.34. 

However I couldn't just deploy the datamodel output of `prisma introspect` on my 1.30 schema. When I would try to deploy it would tell me I was missing the `link: TABLE` or `link: INLINE` parts of the `@relation(name: "nameHere")` directive. So I had to go manually add `link: TABLE` to one side of the relationships on any of the 1:n relationships, so it ended up looking like so `@relation(link: TABLE, name: "nameHere")`. As I understand it they were all using `link: TABLE` in 1.30 and in graphcool as it mentions in the blog post with this sentence:

>The old datamodel is opinionated about relations in the database schema: they're always represented as relation tables.

My next step at this point is to play around with where I put the `link: TABLE` and try to import again

**Comment by grimunit** [comment]
I realized that I should try doing an export from my local 1.34 database that did successfully get ported into. And then use that export to import into my Heroku instance, I still got all those same errors posted in the picture above just like when I did it locally, but the data went in 😄
