### ISSUE TITLE
migrate reset: run without prompting for confirmation

### ISSUE THREAD

**Issue by cehenriques** [prisma/prisma#4634]
## Problem
When running the "migrate reset" command it asks for confirmation. This stops the execution until an answer is provided.

## Suggested solution
The "migrate reset" command could have a new option to skip the confirmation, thus allowing the execution without prompting for confirmation.
Something like:
--no-confirm
or
--silent

## Alternatives
none at the moment

## Additional context
I'm using migrate reset on my tests, to reset my test database before running the test suite and it's annoying to confirm the operation every time I run the tests.

**Comment by albertoperdomo** [comment]
This will be addressed in #4773. Closing as duplicate.
