### ISSUE TITLE
Manually dropping a table which is referenced in foreign key makes Prisma Migrate Crash

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#4636]
Error report id: 12244

Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.8.0            | 
| Prisma CLI  | 2.13.0-dev.56      | 
| Binary      | 628dcb18c71789926326227b6c41a27f0daa0fc6| 

## Error
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/walkers.rs:302:18] foreign key references unknown table

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

```

**Comment by pantharshit00** [comment]
Hey @albertoperdomo 

Sorry for the late reply. Just noticed this report.

I tried it out and I wasn't able to reproduce the crash when I try to drop a foreign key manually in a Prisma Migration.

![image](https://user-images.githubusercontent.com/22195362/103102636-f230c380-4642-11eb-816f-4cf16c0397a2.png)

Version used
```
Environment variables loaded from prisma/.env
@prisma/cli          : 2.14.0-dev.45
@prisma/client       : 2.14.0-dev.45
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 85cf7930a5fc63cd99fa483153fd33cb35d49cfa (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 85cf7930a5fc63cd99fa483153fd33cb35d49cfa (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 85cf7930a5fc63cd99fa483153fd33cb35d49cfa (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 85cf7930a5fc63cd99fa483153fd33cb35d49cfa (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.332.0
```



Can you please try this again or maybe list out the steps for reproduction?

**Comment by albertoperdomo** [comment]
Note to self: probably need to reproduce by removing the table manually (not using Migrate) and write proper reproduction steps.
