### ISSUE TITLE
migrate deploy: Permission denied ERROR for table _prisma_migrations in `list_migrations`

### ISSUE THREAD

**Issue by paulrostorp** [prisma/prisma#4643]
## Bug description
```sh
$ prisma migrate deploy --preview-feature
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "XXX", schema "public" at "XXX:5432"
Error: Database error: Error querying the database: db error: ERROR: permission denied for table _prisma_migrations
   0: sql_migration_connector::sql_imperative_migration_persistence::list_migrations
             at migration-engine/connectors/sql-migration-connector/src/sql_imperative_migration_persistence.rs:121
   1: migration_core::api::DiagnoseMigrationHistory
             at migration-engine/core/src/api.rs:148
```

## How to reproduce
I'm getting the error above when running `prisma migrate deploy` against my production db using version @2.13. **The database is completely empty**. Prior to doing that I run `SET ROLE "role-name";`, but the above error occurs regardless.
The error message is quite slim, so I don't really know how to deal with it. 

Does anyone know the actual query that this step runs ?

## Expected behavior

I would expect this not to throw, or give me more detailed information about why it does.
## Prisma information
I don't think this is relevant since the error occurs before any attempt to apply the schema.
## Environment & setup

- OS: Mac os & docker alpine
- Database: PostgreSQL
- Node.js version: 14.8.0
- Prisma version: 2.13.0
`npm ls | grep  "@prisma"` =>
├─┬ @prisma/cli@2.13.0
│ ├── @prisma/bar@0.0.1
│ └── @prisma/engines@2.13.0-32.833ab05d2a20e822f6736a39a27de4fc8f6b3e49
├─┬ @prisma/client@2.13.0
│ └── @prisma/engines-version@2.13.0-32.833ab05d2a20e822f6736a39a27de4fc8f6b3e49

**Comment by Jolg42** [comment]
Hi @paulrostorp 

So the `_prisma_migrations` is a database table created and used by Prisma Migrate to manage the migrations state (which migration was applied, successfully or not...)

It sounds like Migrate tries to read the table but get a `permission denied` error here.

Could you check your user permissions on this database and add read/write permissions for the `_prisma_migrations` table? That should fix it I think.

**Comment by paulrostorp** [comment]
I will close this as the error was a side effect of the PG role having cycled. No issue on the prisma side.

**Comment by paulrostorp** [comment]
Additional context: https://github.com/prisma/prisma/issues/4645
