### ISSUE TITLE
`create` field in `connectOrCreate` should be optional

### ISSUE THREAD

**Issue by DewarCG** [prisma/prisma#4648]
## Problem

The "connectOrCreate" is a good feature, but it should mark its "create" field as optional because there are many situations where is not required pass some object in runtime (dynamically).

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If you don't need the `create` part of `connectOrCreate`, I recommend using simply the `connect` attribute of Prisma Client.

---

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
