### ISSUE TITLE
Mapped transactions should not be grouped together

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#4649]
## Bug description
If you do something like:
```typescript
await Promise.all(
    calendars.map(calendar =>
      ctx.prisma.$transaction<any>([...])
))
```

It will actually batch all the operations of the different transactions together. It doesn't seem to matter if I add an await on each transaction request.

## How to reproduce

1. Take any schema
2. Create an array of values to operation on
3. Map that array to a a transaction with one or more operations
4. Check prisma logs, you will see one `BEGIN` and one `COMMIT`

## Expected behavior

Each transaction should be independant.

## Prisma information
```
@prisma/cli          : 2.13.0
@prisma/client       : 2.13.0
Current platform     : darwin
Query Engine         : query-engine 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at ../node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at ../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at ../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at ../node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
```

**Comment by pantharshit00** [comment]
I can reproduce this in the dev channel. Thanks for reporting as always.

Reproduction: https://github.com/harshit-test-org/prisma-issue-4649
