### ISSUE TITLE
uncheckedScalarInputs Cannot use connect with field matching id in name (like uid)

### ISSUE THREAD

**Issue by jpalumickas** [prisma/prisma#4652]
## Bug description

Currently when I try to use 
```js
prisma.userIdentity.create({
  data: {
    user: { connect: { id: user.id } },
    uid,
   }
})
```

I get error `Unknown arg user in data.user for type UserIdentityUncheckedCreateInput. Did you mean userId`

I guess this is because I have field name `uid` which matches `id` in name, but this field is just a string, not using any relation.

## How to reproduce

Written above

## Expected behavior

Allow to use `connect` with not relation fields that matching `id` in name

## Prisma information

```
model UserIdentity {
  id        String   @id @default(dbgenerated())
  userId    String   @map("user_id")
  provider  String
  uid       String
  name      String?
  email     String?
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @default(now()) @updatedAt @map("updated_at")
  user      User     @relation(fields: [userId], references: [id])

  @@unique([provider, uid], name: "index_user_identities_on_provider_and_uid")
  @@index([userId], name: "index_user_identities_on_user_id")
  @@map("user_identities")
}
```

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v15.3.0
- Prisma version: v2.13.0

**Comment by pantharshit00** [comment]
Hello,

I am unable to reproduce this with `2.13` and latest dev version `2.14.0-dev.32`.

![image](https://user-images.githubusercontent.com/22195362/102354234-4b0fb480-3fd0-11eb-852c-3d80d459f447.png)


Can you please share the reproduction inside of a git repository so that I can be sure I am trying to debug the correct code? Thanks!

**Comment by jpalumickas** [comment]
Hey @pantharshit00 🙂 

I think I found a problem. I don't get this error when all fields are provided, but if I don't provide a single required field (for example `uid`), I get this error:

```
Unknown arg `user` in data.user for type UserIdentityUncheckedCreateInput. Did you mean `userId`?
Argument userId for data.userId is missing.
Argument uid for data.uid is missing.
```

maybe it should be only:
```
Argument uid for data.uid is missing.
```

So title and description about this issue is misleading then.

**Comment by pantharshit00** [comment]
I can reproduce the typescript error but I think that is expected. Relation style data input and unchecked scalar inputs are wrapped in an `XOR` in the type system like so:
```
     * The data needed to create a UserIdentity.
    **/
    data: XOR<UserIdentityUncheckedCreateInput, UserIdentityCreateInput>
```


`XOR` basically means they are mutually exclusive, if you provide one style input then you can't provide the other style. If you leave the input empty, typescript will show you all available options.

**Comment by jpalumickas** [comment]
Hey @pantharshit00 

I'm not using TypeScript, this is just Prisma error. But yea, we can close an issue.
