### ISSUE TITLE
Internal server error on prisma docker deploy : java.util.NoSuchElementException: None.get

### ISSUE THREAD

**Issue by PrJasperRothdale** [prisma/prisma#4655]
**Describe the bug**
I am getting an internal server error on deploying the following datamodel with Prisma on a docker container. I saw on another issue that the bug seemed to origin from a problem of relation names so I renamed them all to be sure but it didn't solve it.

**To Reproduce**
Use this datamodel and deploy using prisma deploy : 
```graphql
type Bris @db(name: "bris") {
  id_bris: ID! @id
  date: DateTime!
  idEtat: Etat! @db(name: "id_etat") @relation(name: "BrisEtatRelation")
  idMateriel: Materiel! @db(name: "id_materiel") @relation(name: "BrisMaterielRelation")
}

type Cle @db(name: "cle") @relationTable {
  id_cle: ID! @id
  idLocalisation: Localisation! @db(name: "id_localisation") @relation(name: "CleLocalisationRelation")
  idUser: User! @db(name: "id_user") @relation(name: "CleUserRelation")
}

type Emprunt @db(name: "emprunt") {
  id_emprunt: ID! @id
  date: DateTime!
  idMaterielEmp: String! @db(name: "id_materiel_emp")
  idUserEmprunt: String! @db(name: "id_user_emprunt")
  qte: Int! @default(value: 0)
}

type Etat @db(name: "etat") {
  id_etat: ID! @id
  bris: [Bris] @relation(name: "BrisEtatRelation")
  label: String @default(value: "NULL")
}

type Localisation @db(name: "localisation") {
  id_localisation: ID! @id
  cle: [Cle] @relation(name: "CleLocalisationRelation")
  label: String @default(value: "NULL")
  materiel: [Materiel] @relation(name: "LocalisationMaterielRelation")
}

type Materiel @db(name: "materiel") {
  id_materiel: ID! @id
  bris: [Bris] @relation(name: "BrisMaterielRelation")
  codeMateriel: String! @db(name: "code_materiel")
  description: String @default(value: "'-'")
  idLocalisationMateriel: Localisation! @db(name: "id_localisation_materiel") @relation(name: "LocalisationMaterielRelation")
  idType: Type! @db(name: "id_type") @relation(name: "MaterielTypeRelation")
  label: String!
  lienAchat: String! @db(name: "lien_achat") @default(value: "'-'")
  qteInitiale: Int! @db(name: "qte_initiale") @default(value: 0)
  recommander: Int! @default(value: 0)
  sku: String! @default(value: "'0'")
}

type Privilege @db(name: "privilege") {
  id_privilege: ID! @id
  label: String @default(value: "'-'")
  user: [User] @relation(name: "PrivilegeUserRelation")
}

type Projet @db(name: "projet") {
  id_projet: ID! @id
  dateDebut: DateTime @db(name: "date_debut")
  dateFin: DateTime @db(name: "date_fin")
  userProjet: [UserProjet] @relation(name: "ProjetUserprojetRelation")
}

type Reservation @db(name: "reservation") {
  id_reservation: ID! @id
  idMateriel: String! @db(name: "id_materiel")
  idSource: UserProjet! @db(name: "id_source") @relation(name: "ReservationUserprojetRelation")
  qte: Int @default(value: 0)
}

type Type @db(name: "type") {
  id_type: ID! @id
  label: String @default(value: "NULL")
  materiel: [Materiel] @relation(name: "MaterielTypeRelation")
}

type User @db(name: "user") {
  id_user: ID! @id
  cle: [Cle] @relation(name: "CleUserRelation")
  cpUser: String! @db(name: "cp_user")
  idPrivilegeUser: Privilege! @db(name: "id_privilege_user") @relation(name: "PrivilegeUserRelation")
  mail: String!
  nom: String!
  prenom: String!
  userProjet: [UserProjet] @relation(name: "UserUserprojetRelation")
}

type UserProjet @db(name: "user_projet") {
  id_userprojet: ID! @id
  idProjet: Projet! @db(name: "id_projet") @relation(name: "ProjetUserprojetRelation")
  idUser: User! @db(name: "id_user") @relation(name: "UserUserprojetRelation")
  reservation: [Reservation] @relation(name: "ReservationUserprojetRelation")
}
```

**Expected behavior**
Prisma should deploy with no error from the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/29226060/59296159-a20a3000-8c5b-11e9-9434-d2df6342a28a.png)

**Versions (please complete the following information):**
 - Connector: MySQL (MariaDB)
 - Prisma Server: 1.34
 - `prisma` CLI: Prisma and prisma-client-lib 1.34 on Node
 - OS: Windows 10

**Additional context**

**Comment by pantharshit00** [comment]
Looks like you have accidentally added the `@relationTable` directive to the `Cle` type.

Try the following datamodel:

```graphql
type Bris @db(name: "bris") {
  id_bris: ID! @id
  date: DateTime!
  idEtat: Etat! @db(name: "id_etat") @relation(name: "BrisEtatRelation")
  idMateriel: Materiel! @db(name: "id_materiel") @relation(name: "BrisMaterielRelation")
}

type Cle @db(name: "cle"){
  id_cle: ID! @id
  idLocalisation: Localisation! @db(name: "id_localisation") @relation(name: "CleLocalisationRelation")
  idUser: User! @db(name: "id_user") @relation(name: "CleUserRelation")
}

type Emprunt @db(name: "emprunt") {
  id_emprunt: ID! @id
  date: DateTime!
  idMaterielEmp: String! @db(name: "id_materiel_emp")
  idUserEmprunt: String! @db(name: "id_user_emprunt")
  qte: Int! @default(value: 0)
}

type Etat @db(name: "etat") {
  id_etat: ID! @id
  bris: [Bris] @relation(name: "BrisEtatRelation")
  label: String @default(value: "NULL")
}

type Localisation @db(name: "localisation") {
  id_localisation: ID! @id
  cle: [Cle] @relation(name: "CleLocalisationRelation")
  label: String @default(value: "NULL")
  materiel: [Materiel] @relation(name: "LocalisationMaterielRelation")
}

type Materiel @db(name: "materiel") {
  id_materiel: ID! @id
  bris: [Bris] @relation(name: "BrisMaterielRelation")
  codeMateriel: String! @db(name: "code_materiel")
  description: String @default(value: "'-'")
  idLocalisationMateriel: Localisation! @db(name: "id_localisation_materiel") @relation(name: "LocalisationMaterielRelation")
  idType: Type! @db(name: "id_type") @relation(name: "MaterielTypeRelation")
  label: String!
  lienAchat: String! @db(name: "lien_achat") @default(value: "'-'")
  qteInitiale: Int! @db(name: "qte_initiale") @default(value: 0)
  recommander: Int! @default(value: 0)
  sku: String! @default(value: "'0'")
}

type Privilege @db(name: "privilege") {
  id_privilege: ID! @id
  label: String @default(value: "'-'")
  user: [User] @relation(name: "PrivilegeUserRelation")
}

type Projet @db(name: "projet") {
  id_projet: ID! @id
  dateDebut: DateTime @db(name: "date_debut")
  dateFin: DateTime @db(name: "date_fin")
  userProjet: [UserProjet] @relation(name: "ProjetUserprojetRelation")
}

type Reservation @db(name: "reservation") {
  id_reservation: ID! @id
  idMateriel: String! @db(name: "id_materiel")
  idSource: UserProjet! @db(name: "id_source") @relation(name: "ReservationUserprojetRelation")
  qte: Int @default(value: 0)
}

type Type @db(name: "type") {
  id_type: ID! @id
  label: String @default(value: "NULL")
  materiel: [Materiel] @relation(name: "MaterielTypeRelation")
}

type User @db(name: "user") {
  id_user: ID! @id
  cle: [Cle] @relation(name: "CleUserRelation")
  cpUser: String! @db(name: "cp_user")
  idPrivilegeUser: Privilege! @db(name: "id_privilege_user") @relation(name: "PrivilegeUserRelation")
  mail: String!
  nom: String!
  prenom: String!
  userProjet: [UserProjet] @relation(name: "UserUserprojetRelation")
}

type UserProjet @db(name: "user_projet") {
  id_userprojet: ID! @id
  idProjet: Projet! @db(name: "id_projet") @relation(name: "ProjetUserprojetRelation")
  idUser: User! @db(name: "id_user") @relation(name: "UserUserprojetRelation")
  reservation: [Reservation] @relation(name: "ReservationUserprojetRelation")
}
```

**Comment by PrJasperRothdale** [comment]
The @relationTable directive has been generated by prisma during the prisma init. I tried the datamodel you provided which fixed the None.get error but causes several duplicate column name SQL errors. I tried to empty my database and let prisma generate it but it causes a SQL foreign key constraint error.

**Comment by pantharshit00** [comment]
Yes, please send me a SQL dump if possible.

**Comment by PrJasperRothdale** [comment]
`-- MySQL dump 10.17  Distrib 10.3.14-MariaDB, for Win64 (AMD64)
--
-- Host: 127.0.0.1    Database: liara_inventory
-- ------------------------------------------------------
-- Server version	10.4.5-MariaDB-1:10.4.5+maria~bionic

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `bris`
--

DROP TABLE IF EXISTS `bris`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bris` (
  `id_bris` char(25) NOT NULL,
  `id_materiel_bris` char(25) NOT NULL,
  `id_etat_bris` char(25) NOT NULL,
  `date` datetime NOT NULL,
  PRIMARY KEY (`id_bris`),
  KEY `fk_bris_materiel` (`id_materiel_bris`),
  KEY `fk_bris_etat` (`id_etat_bris`),
  CONSTRAINT `fk_bris_etat` FOREIGN KEY (`id_etat_bris`) REFERENCES `etat` (`id_etat`) ON UPDATE CASCADE,
  CONSTRAINT `fk_bris_materiel` FOREIGN KEY (`id_materiel_bris`) REFERENCES `materiel` (`id_materiel`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `bris`
--

/*!40000 ALTER TABLE `bris` DISABLE KEYS */;
INSERT INTO `bris` (`id_bris`, `id_materiel_bris`, `id_etat_bris`, `date`) VALUES ('1','1','1','2019-06-01 00:00:00');
/*!40000 ALTER TABLE `bris` ENABLE KEYS */;

--
-- Table structure for table `cle`
--

DROP TABLE IF EXISTS `cle`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cle` (
  `id_cle` char(25) NOT NULL,
  `id_localisation_cle` char(25) NOT NULL,
  `id_user_cle` char(25) NOT NULL,
  PRIMARY KEY (`id_cle`),
  KEY `fk_cle_loca` (`id_localisation_cle`),
  KEY `fk_cle_user` (`id_user_cle`),
  CONSTRAINT `fk_cle_loca` FOREIGN KEY (`id_localisation_cle`) REFERENCES `localisation` (`id_localisation`),
  CONSTRAINT `fk_cle_user` FOREIGN KEY (`id_user_cle`) REFERENCES `user` (`id_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `cle`
--

/*!40000 ALTER TABLE `cle` DISABLE KEYS */;
INSERT INTO `cle` (`id_cle`, `id_localisation_cle`, `id_user_cle`) VALUES ('1','1','1');
/*!40000 ALTER TABLE `cle` ENABLE KEYS */;

--
-- Table structure for table `emprunt`
--

DROP TABLE IF EXISTS `emprunt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `emprunt` (
  `id_emprunt` char(25) NOT NULL,
  `id_user_emprunt` char(25) NOT NULL,
  `id_materiel_emp` char(25) NOT NULL,
  `date` datetime NOT NULL DEFAULT current_timestamp(),
  `qte` int(11) NOT NULL DEFAULT 0,
  `est_archive` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_emprunt`),
  UNIQUE KEY `uc_emprunt__user_materiel_date` (`id_user_emprunt`,`id_materiel_emp`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `emprunt`
--

/*!40000 ALTER TABLE `emprunt` DISABLE KEYS */;
INSERT INTO `emprunt` (`id_emprunt`, `id_user_emprunt`, `id_materiel_emp`, `date`, `qte`, `est_archive`) VALUES ('1','1','1','2019-06-01 00:00:00',1,0);
/*!40000 ALTER TABLE `emprunt` ENABLE KEYS */;

--
-- Table structure for table `etat`
--

DROP TABLE IF EXISTS `etat`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `etat` (
  `id_etat` char(25) NOT NULL,
  `label` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id_etat`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `etat`
--

/*!40000 ALTER TABLE `etat` DISABLE KEYS */;
INSERT INTO `etat` (`id_etat`, `label`) VALUES ('1','brise');
/*!40000 ALTER TABLE `etat` ENABLE KEYS */;

--
-- Table structure for table `localisation`
--

DROP TABLE IF EXISTS `localisation`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `localisation` (
  `id_localisation` char(25) NOT NULL,
  `label` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id_localisation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `localisation`
--

/*!40000 ALTER TABLE `localisation` DISABLE KEYS */;
INSERT INTO `localisation` (`id_localisation`, `label`) VALUES ('1','atelier');
/*!40000 ALTER TABLE `localisation` ENABLE KEYS */;

--
-- Table structure for table `materiel`
--

DROP TABLE IF EXISTS `materiel`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `materiel` (
  `id_materiel` char(25) NOT NULL,
  `code_materiel` varchar(80) NOT NULL,
  `label` varchar(100) NOT NULL,
  `description` varchar(300) DEFAULT '-',
  `qte_initiale` int(11) NOT NULL DEFAULT 0,
  `id_type_materiel` char(25) NOT NULL,
  `recommander` int(1) NOT NULL DEFAULT 0,
  `lien_achat` varchar(250) NOT NULL DEFAULT '-',
  `sku` varchar(100) NOT NULL DEFAULT '0',
  `id_localisation_materiel` char(25) NOT NULL,
  `est_archive` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_materiel`),
  KEY `fk_type` (`id_type_materiel`),
  KEY `fk_loca` (`id_localisation_materiel`),
  CONSTRAINT `fk_loca` FOREIGN KEY (`id_localisation_materiel`) REFERENCES `localisation` (`id_localisation`) ON UPDATE CASCADE,
  CONSTRAINT `fk_type` FOREIGN KEY (`id_type_materiel`) REFERENCES `type` (`id_type`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `materiel`
--

/*!40000 ALTER TABLE `materiel` DISABLE KEYS */;
INSERT INTO `materiel` (`id_materiel`, `code_materiel`, `label`, `description`, `qte_initiale`, `id_type_materiel`, `recommander`, `lien_achat`, `sku`, `id_localisation_materiel`, `est_archive`) VALUES ('1','testcodemateriel','matest','test',2,'1',0,'1','0110','1',0);
/*!40000 ALTER TABLE `materiel` ENABLE KEYS */;

--
-- Table structure for table `privilege`
--

DROP TABLE IF EXISTS `privilege`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `privilege` (
  `id_privilege` char(25) NOT NULL,
  `label` varchar(30) DEFAULT '-',
  PRIMARY KEY (`id_privilege`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `privilege`
--

/*!40000 ALTER TABLE `privilege` DISABLE KEYS */;
INSERT INTO `privilege` (`id_privilege`, `label`) VALUES ('0','administateur');
/*!40000 ALTER TABLE `privilege` ENABLE KEYS */;

--
-- Table structure for table `projet`
--

DROP TABLE IF EXISTS `projet`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `projet` (
  `id_projet` char(25) NOT NULL,
  `date_debut` datetime DEFAULT current_timestamp(),
  `date_fin` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id_projet`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `projet`
--

/*!40000 ALTER TABLE `projet` DISABLE KEYS */;
INSERT INTO `projet` (`id_projet`, `date_debut`, `date_fin`) VALUES ('1','2019-06-01 00:00:00','2019-06-14 00:00:00');
/*!40000 ALTER TABLE `projet` ENABLE KEYS */;

--
-- Table structure for table `reservation`
--

DROP TABLE IF EXISTS `reservation`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `reservation` (
  `id_reservation` char(25) NOT NULL,
  `id_source_reservation` char(25) NOT NULL,
  `id_materiel_reservation` char(25) NOT NULL,
  `qte` int(11) DEFAULT 0,
  `est_annule` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_reservation`),
  UNIQUE KEY `uc_reservation_source_materiel` (`id_source_reservation`,`id_materiel_reservation`),
  KEY `fk_source` (`id_source_reservation`),
  CONSTRAINT `fk_source` FOREIGN KEY (`id_source_reservation`) REFERENCES `user_projet` (`id_userprojet`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `reservation`
--

/*!40000 ALTER TABLE `reservation` DISABLE KEYS */;
INSERT INTO `reservation` (`id_reservation`, `id_source_reservation`, `id_materiel_reservation`, `qte`, `est_annule`) VALUES ('1','1','1',1,0);
/*!40000 ALTER TABLE `reservation` ENABLE KEYS */;

--
-- Table structure for table `type`
--

DROP TABLE IF EXISTS `type`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `type` (
  `id_type` char(25) NOT NULL,
  `label` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `type`
--

/*!40000 ALTER TABLE `type` DISABLE KEYS */;
INSERT INTO `type` (`id_type`, `label`) VALUES ('1','empruntable');
/*!40000 ALTER TABLE `type` ENABLE KEYS */;

--
-- Table structure for table `user`
--

DROP TABLE IF EXISTS `user`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `user` (
  `id_user` char(25) NOT NULL,
  `cp_user` varchar(12) NOT NULL,
  `nom` varchar(30) NOT NULL,
  `prenom` varchar(30) NOT NULL,
  `mail` varchar(80) NOT NULL,
  `id_privilege_user` char(25) NOT NULL,
  `est_archive` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_user`),
  KEY `fk_priv_user` (`id_privilege_user`),
  CONSTRAINT `fk_priv_user` FOREIGN KEY (`id_privilege_user`) REFERENCES `privilege` (`id_privilege`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `user`
--

/*!40000 ALTER TABLE `user` DISABLE KEYS */;
INSERT INTO `user` (`id_user`, `cp_user`, `nom`, `prenom`, `mail`, `id_privilege_user`, `est_archive`) VALUES ('1','LACK23129703','LACHAUX','Killian','killian@lachx.com','0',0);
/*!40000 ALTER TABLE `user` ENABLE KEYS */;

--
-- Table structure for table `user_projet`
--

DROP TABLE IF EXISTS `user_projet`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `user_projet` (
  `id_userprojet` char(25) NOT NULL,
  `id_user_userprojet` char(25) NOT NULL,
  `id_projet_userprojet` char(25) NOT NULL,
  PRIMARY KEY (`id_userprojet`),
  UNIQUE KEY `uc_userprojet_user_projet` (`id_user_userprojet`,`id_projet_userprojet`),
  KEY `fk_id_user` (`id_user_userprojet`),
  KEY `fk_id_projet` (`id_projet_userprojet`),
  CONSTRAINT `fk_id_projet` FOREIGN KEY (`id_projet_userprojet`) REFERENCES `projet` (`id_projet`),
  CONSTRAINT `fk_id_user` FOREIGN KEY (`id_user_userprojet`) REFERENCES `user` (`id_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `user_projet`
--

/*!40000 ALTER TABLE `user_projet` DISABLE KEYS */;
INSERT INTO `user_projet` (`id_userprojet`, `id_user_userprojet`, `id_projet_userprojet`) VALUES ('1','1','1');
/*!40000 ALTER TABLE `user_projet` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2019-06-17 10:07:14
`

**Comment by PrJasperRothdale** [comment]
Hey, do you have any updates about why the datamodel is generated that way ?

**Comment by pantharshit00** [comment]
@PrJasperRothdale Can you please try introspecting with Prisma 2(read more here: https://www.prisma.io/blog/announcing-prisma-2-zq1s745db8i5)

We have introspection in Prisma 2
