### ISSUE TITLE
Create on a PostgreSQL table with an after Trigger Function causes error

### ISSUE THREAD

**Issue by miller-productions** [prisma/prisma#4656]
## Bug description

I have a PostgreSQL table that has an after Trigger Function on it to update a history table.

i.e. AFTER you INSERT or UPDATE to `Table` the trigger function fires and inserts relevant fields from the incoming NEW row into `HistoryTable`.

If this trigger is enabled, then when you call a prisma create function to insert a new row on that table, an error occurs.

If this trigger is disabled, everything works fine - no error.

```
"stacktrace": [
            "Error: ",
            "Invalid `prisma.jobType.create()` invocation:",
            "",
            "",
            "  The column `new` does not exist in the current database.",
            "    at PrismaClientFetcher.request (<projectroot>\\node_modules\\@prisma\\client\\runtime\\index.js:78121:15)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
```

## How to reproduce

1. Create a `Table` in a PostgreSQL database
2. Create a corresponding `HistoryTable` that matches `Table`.
3. In your Postgres database, create a Trigger Function that runs After Insert or Update on `Table`

i.e. something along the lines of 

```
BEGIN
    INSERT INTO HistoryTable (
        "field1",
        "field2"
    )
    SELECT 
        NEW."field1",
        NEW."field2";
    RETURN NULL;
END;
```

4. Back in your code, run the equivalent of something along the lines of

```
prisma.table.create({
    data: {
        field1: "some value",
        field2: "some other value,
    },
````

## Expected behavior

Expect that the create should run smoothly, the new row should be inserted into `Table`, the trigger function should also run and a row should also be written to `HistoryTable`.

## Environment & setup

- OS: Windows 
- Database: PostgreSQL 
- Node.js version: 14.14 
- Prisma version: 2.13.0

```

```

**Comment by pantharshit00** [comment]
I am unable to reproduce this with `2.13.1` and the following trigger code:

```sql
CREATE OR REPLACE FUNCTION save_history()
               RETURNS TRIGGER
               LANGUAGE PLPGSQL
            AS $$
            BEGIN
                INSERT INTO "HistoryTable" (
                    "field1",
                    "field2"
                ) SELECT
                    NEW."field1",
                    NEW."field2";
                RETURN NEW;
            END;
            $$
            
CREATE TRIGGER history_for_table
  BEFORE INSERT OR UPDATE
  ON "Table"
  FOR EACH ROW
  EXECUTE PROCEDURE save_history();
```


![image](https://user-images.githubusercontent.com/22195362/102712005-e8762b80-42e3-11eb-91c8-36ab5180c572.png)
![image](https://user-images.githubusercontent.com/22195362/102711999-dbf1d300-42e3-11eb-81f2-6c773111be50.png)
![image](https://user-images.githubusercontent.com/22195362/102712001-e14f1d80-42e3-11eb-8b15-4d78f0e22b49.png)


I think you are returning the new row in your trigger function and just returing `NULl` which didn't work for me when I tried inserting rows in database even without Prisma as database wouldn't get the inserted row and it will throw an error. Please check your trigger code once again.

If you can still reproduce this even after checking this, please share a SQL dump of the database with triggers included.

**Comment by miller-productions** [comment]
Thanks @pantharshit00.

I suspect the issue is actually related to a nested write where there are triggers at two different levels. The trigger at the higher level of the write goes through fine, but the trigger down in a lower nested part of the write fails.

What I might do is close off this issue here for now and then re-open a separate issue in future with a proper schema dump and associated code that reproduces the error.
