### ISSUE TITLE
Instrospection creating relation-less types

### ISSUE THREAD

**Issue by Alosies** [prisma/prisma#4657]
**Describe the bug**
I’m trying to migrate my database from `heroku(Server version- 1.11)` to `Digital ocean(Server version 1.34)`.
I did `pg_restore` and did `introspection`.

The `datamodel.prisma` hence created is significantly different from my original `datamodel.prisma`

For example: The `relations` are missing in each `type`. Below are type College and its related type in the old `datamodel.prisma`

```
type College @model {
  id: ID! @unique
  name: String
  shortName: String
  uniqueName: String @unique
  website: String
  studentCalls: [CollegeCalls!]! @relation(name: "CollegeCallCollege")
}
type CollegeCalls @model {
  id: ID! @unique
  college: College @relation(name: "CollegeCallCollege")
  student: User @relation(name: "CollegeCallStudent")
  year: Year @relation(name: "CollegeCallYear")
  converted: Boolean
  joined: Boolean
}
```

Relevant part from new `datamodel.prisma` after introspection

```
type College {
  id: ID! @id
  createdAt: DateTime! @createdAt
  name: String
  shortName: String
  uniqueName: String @unique
  updatedAt: DateTime! @updatedAt
  website: String
}
type CollegeCall @db(name: "CollegeCalls") {
  id: ID! @id
  converted: Boolean
  createdAt: DateTime! @createdAt
  joined: Boolean
  updatedAt: DateTime! @updatedAt
}
type CollegeCallCollege @db(name: "_CollegeCallCollege") {
  id: ID! @id
  a: String! @db(name: "A")
  b: String! @db(name: "B")
}
```
The scalar fields are fine. But How do I make the relations work?

**To Reproduce**
Unfortunately, the database is private and hence I am not able to share the seed data. 

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server:  `1.34.0`
 - `prisma` CLI: `prisma/1.34.0 (linux-x64) node-v10.16.0`
 - OS:  `Ubuntu 16.04` 

I'm stuck at this database migration for more than a week. Any help on this is highly appreciated.

**Comment by Alosies** [comment]
Hi, as per @pantharshit00's advice, I installed prisma@1.30, but it threw errors, so I tried prisma@1.29, it was ok for a while but started throwing errors on mutations.

For Example, I have a QuizAttempt type

```
type QuizAttempt {
  id: ID! @unique
  createdAt: DateTime!
  currentQuestionIndex: Int
  endTime: DateTime
  questionAttempts: [QuestionAttempt] @pgColumn(name: "QuestionAttempt")
  quiz: Quiz @pgColumn(name: "Quiz")
  quizAttemptState: QuizAttemptState @pgColumn(name: "QuizAttemptState")
  score: Float
  startTime: DateTime
  timeConsumedInSeconds: Int
  timeModified: DateTime
  updatedAt: DateTime!
  user: User @pgColumn(name: "User")
}
``` 
When I do a create mutation, I get an error in playground. 
<img width="1437" alt="Screenshot 2019-06-13 at 2 40 05 AM" src="https://user-images.githubusercontent.com/24241029/59386584-a3834780-8d84-11e9-9c8c-32c9ce415d0a.png">

On checking server logs I could see the following
```
"message":"ERROR: null value in column \"updatedAt\" violates not-null constraint\n  Detail: Failing row contains (cjwtq5l1400a60706cb57xvaw, 2019-06-12 21:06:42.232, null, null, null, null, null, 10.000000000000000000000000000000, null)."}}
```
Isn't updated at a system generated value and needs to be updated automatically? The same problem came with prisma@1.30 also.

**Comment by pantharshit00** [comment]
Well, this is being very hard for me to reproduce. Is there any chance you can just mail me the database schema(without any data). Mail it to `pant@prisma.io`

**Comment by Alosies** [comment]
Hi, 
I found that this is an issue that shows up when I use Digital Ocean's managed Database. When I used a container for the Postgres connection the issue disappeared. 

I was finally able to set up the server and do the migration with prisma@1.30. 

Thanks for the help.
