### ISSUE TITLE
prisma introspect drops some @relation custom names in existing schema

### ISSUE THREAD

**Issue by ashih42** [prisma/prisma#4664]
Hello,

I used Python/Sqlalchemy to define tables in a Sqlite database, and then ran `prisma introspect` together with an existing schema in `prisma/schema.prisma`.  The problem is that `prisma introspect` consistently retains some, but drops other, `@relation` custom names defined in the existing `prisma/schema.prisma`.

Please see this bug demo repo here for details:
https://github.com/ashih42/prisma-introspect-bug-report

**Comment by vleandersson** [comment]
We got the same issue with Prisma `2.13` released last week, reverting relational fields to their original name. Would it be worth considering an @map modifier for relational fields as well?

**Comment by do4gr** [comment]
Hey, thanks for reporting this. This is indeed a regression. We already got reports about this and introduced a fix with this PR https://github.com/prisma/prisma-engines/pull/1457. 
A patch release including the fix should come out either today or tomorrow with 2.13.1.

**Comment by do4gr** [comment]
2.13.1 is now out and this should be fixed. If you are still experiencing issues please open a new issue.
