### ISSUE TITLE
Environment is “non-interactive” when using `prisma migrate dev`

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma#4669]
## Bug description

Something changed in my macOS Terminal environment since I updated NodeJS; I’ve needed to suddenly enable permissions where before none where needed. Likewise, I’m now receiving this strange error when I try to use `prisma migrate`:

`Error: We detected that your environment is non-interactive. Running this command in not supported in this context.`

![image](https://user-images.githubusercontent.com/11673745/102416183-35899300-3fae-11eb-8157-b6e915d46ebf.png)

## How to reproduce

Not sure how to reproduce.

## Expected behavior

Should let me choose to proceed with migration instead of ending the process.

## Prisma information

`2.13.0`

## Environment & setup

- OS: macOS 11.1
- Database: PostgreSQL
- Node.js version: `15.4.0`
- Prisma version:

```
2.13.0
```

**Comment by tomhoule** [comment]
Hi @heymartinadams ! Thanks for reporting this. I unfortunately don't have an immediate solution and I can't diagnose what caused the regression. I flagged the issue so we look into this problem in more details soon.

**Comment by pantharshit00** [comment]
@heymartinadams Can you please try running this in iTerm2 once?

**Comment by heymartinadams** [comment]
Hi @pantharshit00 same result.

**Comment by heymartinadams** [comment]
Figured out the cause, @tomhoule and @pantharshit00: We run most command-line `prisma` commands, including `prisma migrate` via the `shelljs` package inside a JavaScript file — see [here](https://github.com/prisma/prisma/issues/9#issuecomment-745036368).

This means it becomes non-interactive! 🤔 💡

**Comment by Jolg42** [comment]
Indeed that makes sense.

We could add a flag to accept resets so the command could work without interaction.

That would mean that if `dev` asks for a reset it will be accepted and continue.

How do you feel about using dev with some kind of `--accept-reset` flag for example?

**Comment by heymartinadams** [comment]
That would be great, actually!

**Comment by barakcoh** [comment]
same here, when trying to run `migrate dev --preview-feature` using [NX](https://nx.dev/)'s `@nrwl/workspace:run-commands` executor.

would love to have some kind of a workaround for this

**Comment by Jolg42** [comment]
@barakcoh The workaround that I have in mind would be to use `prisma db push` instead, depending of what you want to do, see https://www.prisma.io/docs/reference/api-reference/command-reference#db for more details.

**Comment by barakcoh** [comment]
Thanks for the suggestion @Jolg42 but according to the link you provided, it seems `db push` is only recommended for prototyping during development. Our use case involves using [nx](nx.dev) for both local dev as well as deploying for production, where we would very much like to use proper migration versioning.

**Comment by Jolg42** [comment]
@barakcoh Indeed you are right!

So I'm curious to know if you get the `We detected that your environment is non-interactive` message when using nx in local dev?

Also are you using `prisma migrate dev` in production? This `dev` command is only meant to be used for local dev then you can git commit the migration files and use `prisma migrate deploy` in production.

**Comment by mazzaker** [comment]
We use docker (bitbucket pipeline) to use prisma migrate. Our docker build script is used to provide mysql and postgres migrations but maybe more provider in future (mssql is in test). The mentioned flag would be very nice.

**Comment by Jolg42** [comment]
@mazzaker I'm curious to know if this could work for you as well? ⬇️ 

Use `prisma migrate dev` locally then you can git commit the migration files and use `prisma migrate deploy` in production/bitbucket pipeline.

**Comment by mazzaker** [comment]
We use percona cluster for postgres and mysql. The migration files are only for the administration to upgrade the cluster to the new version, so for me as developer I need an instance of mysql and postgres to create the migration files locally. If it is possible to get migration to work without interaction this would be nice.

**Comment by albertoperdomo** [comment]
Hello @mazzaker,

we have plans to add more interactivity to the migrate dev command, so exposing every option as a flag might turn a bit messy and it might not be possible to encode in advance every possible decision via a flag.

Have you done some research into how to run commands interactively using Docker? IMO, if we find a way to achieve that it would be ideal.

**Comment by Jolg42** [comment]
@mazzaker you could try using this ⬇️ 

```sh
docker run --interactive --tty <image name>
# or
docker -it <image name>

# Example
docker run -it node
```

**Comment by albertoperdomo** [comment]
Hello @mazzaker, did you have time to try out the suggestion from @Jolg42 above?

**Comment by albertoperdomo** [comment]
@heymartinadams Are you still experiencing this issue?

**Comment by albertoperdomo** [comment]
We will add the suggested workaround for Docker to our docs. https://github.com/prisma/docs/issues/1379.
There have been no other complaints about this and the original poster is non-reponsive.

Please reopen or file a new issue if this persists.

**Comment by heymartinadams** [comment]
Haven’t given it a try yet, @albertoperdomo, thanks for checking. Will let you know if we run into any issues.

**Comment by heymartinadams** [comment]
To add one (final) comment — just came across this very issue again — it’s not a problem for us: we use custom scripts to handle migrations for us (scripts check the developer environment, and choose among appropriate actions such as `prisma migrate dev` vs `prisma migrate deploy`); should the need arise, we can do this manually.

**Comment by linbudu599** [comment]
> same here, when trying to run `migrate dev --preview-feature` using [NX](https://nx.dev/)'s `@nrwl/workspace:run-commands` executor.
> 
> would love to have some kind of a workaround for this

Hi pal, did you fix `nx` run-commands with `prisma migrate dev`? I'm now getting this error, too. And have no idea to fix it.

**Comment by Jolg42** [comment]
@linbudu599 Could you check the value of these env vars when you run the command?
```js
console.log('isTTY', process.stdout.isTTY)
console.log('CI', process.env['CI'])
```

**Comment by Martinsos** [comment]
We are having problem with this when using Prisma via https://github.com/wasp-lang/wasp . We programatically call prisma commands from our CLI and we actually forward all stdin and stdout so interactivity is not a problem, it works, however now we get the message that Prisma Migrate has detected that the environment is non-interactive.

It would be great if there was a way to tell it to drop that check and just go with it, so it can be used programmatically. Maybe a flag called `--allow-non-interactive` or smth like that?

**Comment by pantharshit00** [comment]
@Martinsos Best to open a new issue with proposal to add that flag

**Comment by antonioandrade** [comment]
This is a problem for us too, within a NX monorepo... we can work around it but it feels dirty... why did this issue get closed? Did the idea of supporting passing command flags in non-interactive contextes get ditched or just moved into https://github.com/prisma/prisma/issues/7113?

**Comment by janpio** [comment]
The comment before this was closed explained the reasoning back then: https://github.com/prisma/prisma/issues/4669#issuecomment-789611127 It still stands, and #7113 is indeed a feature request that suggests a way to solve this.

**Comment by electrovir** [comment]
Is there a workaround for this issue? (Excluding the docker-specific one.) I just read this whole thread and don't see one.

**Comment by LouisLecouturier** [comment]
Any updates on this ?

**Comment by suhjohn** [comment]
Any updates on this?

**Comment by dukeeagle** [comment]
Also requesting updates!

**Comment by janpio** [comment]
This is a closed issue. So there will be no updates. If you want updates, please subscribe to any open issue that is about the same problem (for example https://github.com/prisma/prisma/issues/7113 if that would suit your needs).

**Comment by bailuo** [comment]
I also got this problem when I wrote my script to do migration. When I simple went with migrate dev, the error occured, but when I ran the "prisma migrate reset --force" first, the error disappeared.

**Comment by nukeop** [comment]
I'm getting this error on Mac, I'm not doing anything out of the ordinary other than trying to run a migration.

**Comment by rujorgensen** [comment]
I added `CI=false` to my .env-file recently, it turned out removing that fixed the issue for me.

**Comment by amplicity** [comment]
+1 to above, `CI=true` causes the same error.

**Comment by riansefriadi** [comment]
In a development environment, Prisma Migrate sometimes prompts you to reset the database. Resetting drops and recreates the database, which results in data loss. The database is reset when:

You call "prisma migrate reset --force" explicitly
then You call "prisma migrate dev --name your name" and Prisma Migrate detects drift in the database or a migration history conflict

**Comment by cd4success** [comment]
### In case anyone comes across this, here are some tips
1. If you use terminal via VSCode, make sure you're using the Powershell, not Git Bash.
2. Both Powershell and CMD are interactive so running `prisma migrate dev --name first_migration` or `npx prisma migrate dev --name first_migration` would work. (Note: "first_migration" is just a name for the migration [use any name you like]. You'd see the result once it's done).
3. Now, once you run `prisma migrate dev --name first_migration` and you have some tables or migrations already in your database, the prompt will ask if you want to overwrite them, do not accept that else the data which you had before running prisma against your db would be wiped off. Just enter N and it'll proceed and leave your previous data intact.
4. I was facing the same issue and did the whole migration successfully via CMD on Windows but mistakingly wiped out a project's production data (fortunately, the data loss didn't cause any financial, personal or environmental loss).

**Comment by ericvtheg** [comment]
Even with `CI=false` I was encountering this, had to delete the `CI` var entirely from my .env file.
