### ISSUE TITLE
FULLTEXT index is removed everytime running: prisma migrate save

### ISSUE THREAD

**Issue by eddeee888** [prisma/prisma#4671]
## Bug description

Because there is no way to add FULLTEXT index in prisma2, I have to manually add it by running something like this:

```sql
CREATE FULLTEXT INDEX robot_general_search ON Robot(name,description);
```

This is needed because I want to run `MATCH ... AGAINST` function in [MySQL 5.7.30](https://dev.mysql.com/doc/refman/5.7/en/fulltext-search.html)

However, when I try to create a new migration file, this index is always removed. This is the command I try to run:

```
yarn prisma migrate save --name new-migration --experimental
```

Running `migrate up` does not clear this index

## How to reproduce

- Create a MySQL database ( I'm using 5.7.30 but I suspect this happens to all DBs )
- Create any table with 1 or 2 `String` fields other than ID
- Run `CREATE FULLTEXT INDEX robot_general_search ON Robot(name,description);` manually in mysql
- Check that the index appears in the table.
- Add a new field to make sure a new migration is created
- Run `yarn prisma migrate save --name new-migration --experimental`
- The `FULLTEXT` index is removed

## Expected behavior

- The `FULLTEXT` index should still be in the table

## Prisma information

```
model Robot {
  id       Int                    @id @default(autoincrement())
  name String
  description String
}
```

## Environment & setup

- OS: MacOS, prisma runs in Docker with base image being `node:12.18.0-alpine3.11`
- Database: MySQL 5.7.30
- Node.js version: 12.18.0
- Prisma version: 2.4.1

```
@prisma/cli          : 2.4.1
Current platform     : linux-musl
Query Engine         : query-engine 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/query-engine-linux-musl)
Migration Engine     : migration-engine-cli 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/migration-engine-linux-musl)
Introspection Engine : introspection-core 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/introspection-engine-linux-musl)
Format Binary        : prisma-fmt 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules/@prisma/cli/prisma-fmt-linux-musl)
Preview Features     : transactionApi, middlewares
```

**Comment by pantharshit00** [comment]
I can reproduce this even when using migrate itself to create the index using the `--create-only` flow.

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/22195362/102759446-25045e80-439a-11eb-8b89-a24e8a30fbb4.png">

**Comment by janpio** [comment]
I think this is covered by this related feature request: https://github.com/prisma/prisma/issues/3325 We are going to track `FULLTEXT` functionality on all levels (schema, query, migrations) there. Thanks for reporting @eddeee888
