### ISSUE TITLE
Can't create table (errno 150 "Foreign key constraint is incorrectly formed")

### ISSUE THREAD

**Issue by gabrielbusarello** [prisma/prisma#4690]
When I execute the `prisma migrate up --experimental` command, I get an error like this:
![image](https://user-images.githubusercontent.com/25415068/83087217-1acdec00-a067-11ea-993d-3fb6934bc9fc.png)
The report id are 6340.

If you and more informations, please make me know :D.

Thank you for the tools!!

**Comment by tomhoule** [comment]
Candidating for reproduction with a recent version of migrate.

**Comment by gabrielbusarello** [comment]
Hi. I believe that do not occurs anymore in newer versions, prisma migrate have changed a lot since then, I created this issue to help you to find errors, but the newer version of prisma migrate is really good.

**Comment by SUPERTEMPO** [comment]
I'm still faced with this error, any available solution?

**Comment by tomhoule** [comment]
@SUPERTEMPO  comments in closed issues tend to be missed, please open a new issue with as much detail as possible and we can look into it :)
