### ISSUE TITLE
prisma-init  hangs in multiple places

### ISSUE THREAD

**Issue by madhured-anugu** [prisma/prisma#4690]
When I use prisma init, it allows me to navigate to the first step, then it asks to set up a new Prisma server or deploy to an existing server?, What ever I do in the next step, in the command line it hangs, The following is the screenshot if I select Use existing database, even if I select demo server it is havinn same issue

![image](https://user-images.githubusercontent.com/51799968/59949995-56fdd300-943a-11e9-9fec-7350126f49f0.png)

**Please post usage questions or broader discussions in the [Forum](https://www.graph.cool/forum/)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/graphcool/prisma/issues/new?template=feature_request_old.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/graphcool/prisma/issues/new?template=bug_old.md)

**Comment by mrmoonman** [comment]
I'm getting the same issue, I have been able to do these tasks before but when setting up a new project it is failing.

**Comment by RealPrismaDeveloper** [comment]
Hey! Real Prisma Developer here! I know this issue has been reported on multiple platforms for the past few days but we don't give a shit! You should try one of our competitors/alternatives to get your application up and running. Hope you have a great day!

**Comment by madhured-anugu** [comment]
Work around is to uninstall prisma and used prisma@1.24 instead of current 1.34 and it is working. I am not sure when it is broken but some time after 1.24

**Comment by pantharshit00** [comment]
I can unable to reproduce this. 

Can you please share the output of the command with `export DEBUG=*`. That way we can see the detailed logs and potentially identify this issue.

**Comment by madhured-anugu** [comment]
Folks, I upgraded to prisma and this issue is resolved now, Please close it now
