### ISSUE TITLE
Rename table's column

### ISSUE THREAD

**Issue by ricardoalmeida** [prisma/prisma#4694]
## Problem

After renaming a column in schema.prisma, _Prisma Migrate_ executes the following steps:

1 - ALTER TABLE ... DROP COLUMN
2 - ADD COLUMN ...

It loses the data.

## Suggested solution

Console prompt suggestion (Are you renaming the column?):

```
Checking the datasource for potential data loss...
? Are you renaming the column? › (y/N) N
⚠️  There will be data loss:
  • You are about to drop the column `secondarySkus` on the `Bundle` table, which still contains 1 non-null values.
? Are you sure you want to apply this change? › (y/N)
```

In case it's a renaming, the prompt doesn't show the ⚠️ warning and performs rename:

ALTER TABLE ... RENAME COLUMN TO NEWCOLUMN

## Alternatives

Command-line option

`npx prisma migrate up --experimental --rename`

**Comment by tomhoule** [comment]
In the new preview version of migrate (2.13.0), migrate will produce SQL migration files that you can edit to do renamings if you want. We are happy to get any feedback on renaming workflows, though. Thanks for opening this issue.

**Comment by tomhoule** [comment]
Here's an example of how you would do it in current migrate: https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-flows#drafting-a-migration

**Comment by lastmjs** [comment]
I've got a question about this. It seems very dangerous and not intuitive to me that the default behavior when renaming a column in the prisma schema is to drop the column and add it again.

Why is renaming the column in the generated migration sql not the default?

**Comment by janpio** [comment]
Fundamentally because Prisma does not know if you really just renamed a column, or if you added a new one and removed the old one. Two very different things if you have data in the old column already. So right now we default to assuming you added and removed, and you can update the SQL manually to rename a column instead.

Prisma Migrate will hopefully be able to help you with this in the future.

**Comment by marcospgp** [comment]
@janpio the issue is not fundamental, as drizzle already fixes it by simply asking the user when running the migration generation command

> So right now we default to assuming you added and removed, and you can update the SQL manually to rename a column instead.

except `prisma migrate dev` will create the migration and deploy it all at once, not giving you a chance to edit it.
