### ISSUE TITLE
Error: Error in migration engine. Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\d023a05\src\connector\mysql\error.rs:129:43] index out of bounds: the len is 1 but the index is 1 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4700]
Command: `prisma migrate up --experimental`
Version: `2.9.0`
Binary Version: `369b3694b7edb869fad14827a33ad3f3f49bbc20`
Report: https://prisma-errors.netlify.app/report/11672 **(Note: to see the `schema.prisma` file, please click the report, credentials are in 1password)**
OS: `x64 win32 10.0.18363`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\d023a05\src\connector\mysql\error.rs:129:43] index out of bounds: the len is 1 but the index is 1

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (C:\Users\abdel$\Documents\shopify_back_end\prod\prisma2.0\node_modules\@prisma\cli\build\index.js:412:153)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
[C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\d023a05\src\connector\mysql\error.rs:129:43] index out of bounds: the len is 1 but the index is 1
```

**Comment by pantharshit00** [comment]
Hey @RinatGumarov  @cudba 


Can you please try this again in the new preview version of migrate? A lot of things have changes since the report was received so please try this again.

**Comment by mervinjin** [comment]
@pantharshit00 

Prisma Mirgations only works well on local database. When I try to load the remote database, there will be an error.

## Usage

Command: `prisma migrate dev --preview-feature` or `prisma migrate deploy --preview-feature`

schema.prisma：

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

// ...Models
```

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v15.5.1            | 
| Prisma CLI  | 2.14.0             | 
| Binary      | 5d491261d382a2a5ffdc71de17072b0e409f1cc1| 

## Error
```
Error: Error in migration engine.
Reason: [/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/bc3aa8a/src/connector/mysql/error.rs:129:43] index out of bounds: the len is 1 but the index is 1

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/prisma/issues/new

```

**Comment by pantharshit00** [comment]
Hey @mervinjin 


Can you please tell us where the remote database is hosted?

**Comment by albertoperdomo** [comment]
Related to https://github.com/prisma/prisma/issues/4606

**Comment by albertoperdomo** [comment]
Closed via https://github.com/prisma/prisma-engines/pull/1570.
Should be fixed now.
