### ISSUE TITLE
Mutation query works differently when setting prisma endpoint

### ISSUE THREAD

**Issue by hyochan** [prisma/prisma#4704]
**Describe the bug**
I am not sure if this is a `bug` or `expected`. I've just found strange behavior when setting `prisma` endpoint. When I don't set prisma `endpoint`, my mutation query `request` direct `params` like below which is expected.
![image](https://user-images.githubusercontent.com/27461460/60268641-d2beba80-9927-11e9-91f8-35aa81975c62.png)

However, when I set my endpoint like below,
![image](https://user-images.githubusercontent.com/27461460/60268882-66908680-9928-11e9-8a25-d21b878a835a.png)

Now it requests `data` param and I have to put my other `params` inside `data`.
![image](https://user-images.githubusercontent.com/27461460/60268599-b753af80-9927-11e9-92c0-0582086dbc3f.png)

**To Reproduce**
1. Set `endpoint`.
2. Test the `mutation` query like above.

**Expected behavior**
No `data` param and put `params` directly into `method` defined.

**Screenshots**
Posted above.

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: `1.34.0`
 - `prisma` CLI: `prisma/1.34.0`
 - OS: [`OS X Mojave`] 
 - other dependencies: `prisma-client`, `prisma-binding`, etc. if applicable
    ```
    "prisma-binding": "^2.3.13",
    "prisma-client-lib": "^1.34.0
    ```

**More detail**
Actually, I know that `endpoint` shouldn't be set as I did previously. However, I figured out myself that by using `endpoint`, I can access to different `prisma` container such as local, dev, production instances. I just want to know how does these affect to my `endpoint` and changing the `query`. Is it right that this shouldn't be used directly?

**Comment by pantharshit00** [comment]
Well, you are basically hitting the Prisma Server's GraphQL API when you goto `localhost:4466` and when you are not hitting this endpoint, you are hitting your custom GraphQL server.

This is totally expected.
