### ISSUE TITLE
Windows (MySQL) migrate up doesn't work when table names are case sensitive

### ISSUE THREAD

**Issue by Parilar** [prisma/prisma#4712]
Steps top reproduce :

-Get a windows machine
-Using MySQK 5.7
-prisma2 init
-add a random model
-prisma2 lift save
-prisma2 lift up

The migration is created but 'prisma2 lift up' looked like it worked but not tables are created.
The solution is to set  **lower_case_table_names** to 2 (default 1) 

What's the problem ?
on windows all tables and databases will be created in lower case letters (_migration instead of _Migration), prisma2 can't handle that and get an exception.

**Comment by tomhoule** [comment]
Other users confirmed this problem is fixed for them in newer versions. Please open a new issue if something else comes up. Thanks for the report :)
