### ISSUE TITLE
Resolvers Are Unbearably Slow

### ISSUE THREAD

**Issue by mortenbo** [prisma/prisma#4712]
**Describe the bug**
I have a custom resolver that returns 25 nodes. Fetching the nodes using the Prisma CLI is fast and stable. However, when I return the 25 nodes in the resolver performance worsens a lot.

**To Reproduce**
## Datamodel
```
type LocalBusiness {
    id: ID! @id
    createdAt: DateTime! @createdAt
    updatedAt: DateTime! @updatedAt
    externalId: String
    business: Business! @relation(link: INLINE)
    name: String
    websiteLink: String
    latitude: Float!
    longitude: Float!
    countryCode: String!
    streetAddress: String!
    city: String
    postalCode: String
}

type Business {
    id: ID! @id
    createdAt: DateTime! @createdAt
    updatedAt: DateTime! @updatedAt
    name: String!
    isEligible: Boolean! @default(value: true)
    countryCode: String!
    localeCode: String!
    currencyCode: String!
    localBusinesses: [LocalBusiness!]!
    primaryColor: String! @default(value: "#ffffff")
    websiteLink: String
    shortDescription: String
    positiveLogotype: Image @relation(name: "PositiveLogotypeToBusiness", link: INLINE)
    negativeLogotype: Image @relation(name: "NegativeLogotypeToBusiness", link: INLINE)
}

type Image {
    id: ID! @id
    createdAt: DateTime! @createdAt
    updatedAt: DateTime! @updatedAt
    path: String! @unique
    filename: String!
    mimetype: String!
    md5sum: String!
}
```

## Resolver

```javascript
module.exports = async (root, args, ctx) => {
    const nodes = await ctx.prisma.localBusinesses({
        where: {
            id_in: [
                'cjxkgd86zdk2q0892yobwq3um',
                'cjxkgcqwpcp6k08922xf1uu04',
                'cjxkgcr5gcpm80892w1eh31oq',
                'cjxkgcrf5cq1n08923hqv2eqi',
                'cjxkgcrfmcq2m0892o4glhk8c',
                'cjxkgcrfycq2x089220m83t2t',
                'cjxkgcrgscq3w089268jtvbui',
                'cjxkgcrhjcq5l0892qymmqvaj',
                'cjxkgcrk8cqap08921tfjwkdz',
                'cjxkgcrkbcqbn0892f3gnh4b0',
                'cjxkgcs1vcr830892w4h5uhpe',
                'cjxkgcs2ncr900892bqgrwol9',
                'cjxkgcs4hcrd3089266n6v9ef',
                'cjxkgcs4icrd408924h12xe5p',
                'cjxkgcs5fcrf208925hsoag4i',
                'cjxkgct2uct1u0892rivw9vut',
                'cjxkgct9xctf50892c6nhwrw2',
                'cjxkgctrpcuda0892z21fexua',
                'cjxkgctu2cuhv0892p8m981xa',
                'cjxkgctuucujg0892wgmvij68',
                'cjxkgctv9cukq0892fp5awd3l',
                'cjxkgctz7curl0892zmccnby3',
                'cjxkgcu5lcv500892zptqdb8r',
                'cjxkgcu8wcv9t0892hhnvbbev',
                'cjxkgcuybcwib0892tca5we2z'
            ]
        }
    }).$fragment(`fragment Test on LocalBusiness {
        id
        vampireSquidId
        name
        streetAddress
        postalCode
        city
        longitude
        latitude
        externalId
        business {
            countryCode
            name
            vampireSquidId
            positiveLogotype {
                path
            }
            negativeLogotype {
                path
            }
            primaryColor
            websiteLink
            shortDescription
        }
    }`);

    return nodes;
};
```

# Lua Test

```lua
wrk.method = "POST"
wrk.body   = [[{
  "query": "query Stores {  searchLocalBusinesses() {    nodes {      id      name      streetAddress      postalCode      city      longitude      latitude      externalId      business {        countryCode        name        positiveLogotype {          url(width: 160, height: 45)        }        negativeLogotype {          url(width: 160, height: 45)        }        primaryColor        websiteLink        shortDescription      }    }  }}",
  "operationName": "Stores"
}]]
wrk.headers["Content-Type"] = "application/json"
wrk.headers["X-Api-Key"] = "Foo"
```

Command: `wrk -t4 -d10s -c30 '--latency' --script local-business-search.lua --timeout 2s "http://localhost:4000/v3"`

Running this command gives me the following results:

```└─ $ ▶ wrk -t4 -d10s -c30 '--latency' --script local-business-search.lua --timeout 2s "http://localhost:4000/v3"
Running 10s test @ http://localhost:4000/v3
  4 threads and 30 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.80s   166.03ms   2.00s    64.71%
    Req/Sec     7.49      8.55    39.00     87.01%
  Latency Distribution
     50%    1.85s
     75%    1.94s
     90%    1.97s
     99%    2.00s
  130 requests in 10.02s, 3.34MB read
  Socket errors: connect 0, read 0, write 0, timeout 45
Requests/sec:     12.97
Transfer/sec:    340.82KB
```

And `docker stats` while it was running:

<img width="1385" alt="Screen Shot 2019-07-02 at 11 07 18" src="https://user-images.githubusercontent.com/499100/60500014-df416b00-9cb9-11e9-82a1-64b8927ed0d8.png">

In other words, really poor performance. However, if I don't `return nodes;` at the bottom and instead `return [];` my results are:

```
└─ $ ▶ wrk -t4 -d10s -c30 '--latency' --script local-business-search.lua --timeout 2s "http://localhost:4000/v3"
Running 10s test @ http://localhost:4000/v3
  4 threads and 30 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   206.48ms   50.60ms 484.93ms   79.03%
    Req/Sec    34.22     14.75    70.00     60.53%
  Latency Distribution
     50%  196.87ms
     75%  225.62ms
     90%  262.55ms
     99%  400.71ms
  1352 requests in 10.10s, 331.40KB read
Requests/sec:    133.86
Transfer/sec:     32.81KB
```

Those results are great and acceptable (however, nothing gets returned to the end-user even though I fetch the nodes using the CLI). `docker stats` while it was running:

<img width="1401" alt="Screen Shot 2019-07-02 at 11 09 49" src="https://user-images.githubusercontent.com/499100/60500058-f5e7c200-9cb9-11e9-8ad4-de32e02146a3.png">

Not a big difference compared to the other test.

**Expected behavior**
I would expect that my response times are the same when `return nodes;` since I've already fetched the data I need. For some reason, returning the nodes to the outer resolver slows everything down.

Can this really be true or am I doing something wrong here? I'm seeing the exact same thing on AWS so it's not related to my local setup and Docker. I have around 70k LocalBusiness' and 1k Business'.

Also, I've tested this on all three DB connectors: Postgres, MySQL and Mongo. All the same results.

**Versions (please complete the following information):**
 - Connector: Postgres+MySQL+Mongo
 - Prisma Server: 1.34
 - `prisma` CLI: prisma/prisma/prisma: stable 1.34.0, Mac, HomeBrew, node v10.16.0
 - OS: macOS Mojave

**Comment by pantharshit00** [comment]
re

**Comment by pantharshit00** [comment]
(Ignore the accidental closing)


Can you please tell me where your Prisma Server and database is hosted?

**Comment by mortenbo** [comment]
> (Ignore the accidental closing)
> 
> Can you please tell me where your Prisma Server and database is hosted?

My tests are run locally with Docker and then I have it set up on AWS using Postgres RDS too. Both give same results.

**Comment by mortenbo** [comment]
I also just tried to create a completely new Prisma project to isolate the issue and I have the same issue there.

**Comment by pantharshit00** [comment]
I can't reproduce this and I don't think we have got any reports of this kind of slowness before. I don't have the exact data you have so it is difficult to reproduce the exact situation.

Also just noticed, you have a syntax error in the query in your work test
```diff
 wrk.body   = [[{
-  "query": "query Stores {  searchLocalBusinesses() {    nodes {      id      name      streetAddress      postalCode      city      longitude      latitude      externalId      business {        countryCode        name        positiveLogotype {          url(width: 160, height: 45)        }        negativeLogotype {          url(width: 160, height: 45)        }        primaryColor        websiteLink        shortDescription      }    }  }}",
  "operationName": "Stores"
}]]
 wrk.body   = [[{
+  "query": "query Stores {  searchLocalBusinesses {    nodes {      id      name      streetAddress      postalCode      city      longitude      latitude      externalId      business {        countryCode        name        positiveLogotype {          url(width: 160, height: 45)        }        negativeLogotype {          url(width: 160, height: 45)        }        primaryColor        websiteLink        shortDescription      }    }  }}",
  "operationName": "Stores"
}]]
```

It contained an empty argument list.

Let me know if this is still slow for you. If yes, we can try increasing the queue size and log queries in using the PRISMA_CONFIG.

**Comment by mortenbo** [comment]
Can you check this out and run `./load-test.sh`: https://github.com/mortenbo/prisma-resolver-slowness

What results do you get? This is my results: ```Running 10s test @ http://localhost:4000
  4 threads and 30 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   824.20ms  271.98ms   1.80s    71.56%
    Req/Sec    11.77      9.04    50.00     84.07%
  Latency Distribution
     50%  747.82ms
     75%    1.02s
     90%    1.19s
     99%    1.65s
  334 requests in 10.10s, 0.93MB read
Requests/sec:     33.07
Transfer/sec:     93.88KB
Response count: 	0```

**Comment by pantharshit00** [comment]
Thanks for the repository. Now I understand it fully.

This issue is partly related to #3599 as current we use network-based batching which ends up calling the database per type resolver. Alias-based(which is already implemented in Prisma 2) will solve this but it is a bit hard to implement.

Right now what you can do to speed things up is to either increase the queueSize like so in your docker-compose file like so:
```yaml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            queueSize: 10000
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
```

Results with this change:
![image](https://user-images.githubusercontent.com/22195362/60606454-03479e00-9dd9-11e9-94cf-0ac8f2e50772.png)


But what I will recommend is to use the `$fragment` for resolving relations. That way all of the relations are a single call to the database:

```js
const { prisma } = require('./generated/prisma-client')
const { GraphQLServer } = require('graphql-yoga')

const resolvers = {
  Query: {
    localBusinesses(root, args, context) {
      return context.prisma.localBusinesses({first: 25}).$fragment(`
        fragment IncludeBusiness on LocalBusiness {
          id
          name
          business {
            id
            name
          }
        }
      `)
    }
  },
  Mutation: {
  },
}

const server = new GraphQLServer({
  typeDefs: './schema.graphql',
  resolvers,
  context: {
    prisma,
  }
})
server.start(async () => {
  await prisma.createBusiness({
      name: 'Business A',
      localBusinesses: {
        create: [{
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }, {
            name: 'Field'
        }, {
            name: 'Field 2'
        }]
      }
  });

  console.log('Server is running on http://localhost:4000');
});
```

Result with this change:
![image](https://user-images.githubusercontent.com/22195362/60606635-56215580-9dd9-11e9-9088-9f927bfefa9a.png)


So, for now, I will close this issue as a duplicate of #3599

**Comment by mortenbo** [comment]
@pantharshit00 Increasing `queueSize` doesn't change anything. Adding a fragment only slightly improves performance:

```
└─ $ ▶ ./load-test.sh
Running 10s test @ http://localhost:4000
  4 threads and 30 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   342.03ms   49.37ms 567.30ms   72.74%
    Req/Sec    20.87     11.07    50.00     74.58%
  Latency Distribution
     50%  338.22ms
     75%  369.67ms
     90%  402.40ms
     99%  477.72ms
  807 requests in 10.09s, 2.42MB read
Requests/sec:     79.99
Transfer/sec:    245.51KB
Response count: 	0
```

So I don't consider this issue closed yet. There's something off here. And I don't understand why the Prisma server is using 300% CPU where Postgres only uses 50-70%. Shouldn't Postgres be doing all the work?

Also, Docker has 6 cores to work with and I'm running on one of the latest 15" MacBook Pro's.

**Comment by pantharshit00** [comment]
Can you please test fragment solution again? I am getting over 400 req/sec with it. 


`queueSize` wasn't affecting anything. That's why I have deleted that part in my comment

**Comment by mortenbo** [comment]
It doesn't really help anything with fragments for me:

```
└─ $ ▶ ./load-test.sh
Running 10s test @ http://localhost:4000
  4 threads and 30 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   422.11ms   89.97ms 766.14ms   69.36%
    Req/Sec    17.91     10.67    50.00     71.43%
  Latency Distribution
     50%  407.27ms
     75%  476.83ms
     90%  553.67ms
     99%  661.58ms
  656 requests in 10.09s, 1.97MB read
Requests/sec:     65.01
Transfer/sec:    199.54KB
Response count: 	0
mbor @ mr ~/Desktop/prisma-resolver-slowness master
└─ $ ▶ ./load-test.sh
Running 10s test @ http://localhost:4000
  4 threads and 30 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   376.79ms   60.51ms 579.25ms   68.21%
    Req/Sec    19.45     10.69    60.00     87.46%
  Latency Distribution
     50%  367.07ms
     75%  418.53ms
     90%  459.28ms
     99%  535.04ms
  733 requests in 10.09s, 2.20MB read
Requests/sec:     72.66
Transfer/sec:    223.02KB
Response count: 	0
```

And while running the test this is what `docker stats` is saying:

<img width="1366" alt="Screen Shot 2019-07-04 at 10 59 44" src="https://user-images.githubusercontent.com/499100/60653707-dcc24b00-9e4a-11e9-9ecd-f7ecf4aac368.png">

Isn't it weird all the work is on the Prisma server and not Postgres?

**Comment by pantharshit00** [comment]
Memory usage is overhead of JVM. We have eliminated JVM and we are using Rust now in Prisma v2.

But still, I am unable to reproduce this after using `$fragment` syntax. Can you please share your code?

![image](https://user-images.githubusercontent.com/22195362/60656908-fb860900-9e6d-11e9-94ab-b975895bc490.png)

![image](https://user-images.githubusercontent.com/22195362/60656933-06d93480-9e6e-11e9-9fcf-c1292743a852.png)

**Comment by pantharshit00** [comment]
Also, Remeber to *REMOVE* type resolvers if you are using `$fragment` otherwise it is of no use.

**Comment by mortenbo** [comment]
> Memory usage is overhead of JVM. We have eliminated JVM and we are using Rust now in Prisma v2.

Memory usage is fine. I was referring to CPU usage.

> Also, Remeber to **REMOVE** type resolvers if you are using `$fragment` otherwise it is of no use.

Aha, that was the missing link:
```
└─ $ ▶ ./load-test.sh
Running 10s test @ http://localhost:4000
  4 threads and 30 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    91.85ms   14.42ms 161.50ms   70.22%
    Req/Sec    75.96     12.99   111.00     63.75%
  Latency Distribution
     50%   89.88ms
     75%  100.03ms
     90%  110.89ms
     99%  134.34ms
  3049 requests in 10.05s, 9.14MB read
Requests/sec:    303.30
Transfer/sec:      0.91MB
Response count: 	0
```

This helps! I just have one final question then: this isolated project I've made for you uses `typeDefs`. In reality, I'm using Nexus Prisma, which automatically handles relation fetching. How do I disable that so that I return fragments instead? Otherwise, performance will be bad still.

**Comment by Hebilicious** [comment]
@mortenbo did you find a way to do that ?

**Comment by mortenbo** [comment]
No - not yet 👎

**Comment by pantharshit00** [comment]
Hi,

Sorry for the late response. Currently, this is not possible with nexus prisma.

The only solution that currently fully takes advantage of Prisma v1 server is prisma-binding.

**Comment by mortenbo** [comment]
> Hi,
> 
> Sorry for the late response. Currently, this is not possible with nexus prisma.
> 
> The only solution that currently fully takes advantage of Prisma v1 server is prisma-binding.

Okay. Thanks for the reply. I really wish this was flagged on the Nexus page. If I had known performance would be a bottleneck when using Nexus Prisma I'd never use it. Now, everything in my code uses Nexus 😞

I'll close the issue - thanks for your input.

**Comment by pantharshit00** [comment]
I am really sorry for this trouble. We have a new nexus prisma API coming up with Prisma 2 which will solve this issue.

https://nexus.js.org/docs/database-access-with-prisma-v2

**Comment by hajnalben** [comment]
Hi,

I have found a workaround for the issue.

You can grab the query and the variables from the request and call the prisma with the raw values:
```javascript
import { prismaExtendType } from 'nexus-prisma'
import decorateArgsWithUserId from '../../utils/decorateArgsWithOwner';

export const Query = prismaExtendType({
  name: 'Query',
  type: 'Query',
  definition: t => {
    t.field('files', {
      ...t.prismaType.files,
      async resolve(root, args, ctx, info) {
        const res = await ctx.prisma.$graphql(ctx.request.body.query, ctx.request.body.variables)

        ctx._rawPrismaQuery = true

        return res.files
      }
    })
  }
})
```

Then create a field decorator: 
```javascript
export default function checkLocalResolution(type, t) {
  return {
    ...t.prismaType[type],
    resolve(root, args, ctx, info) {
      if (ctx._rawPrismaQuery) {
        return root[type]
      }

      return t.prismaType[type].resolve(root, args, ctx, info)
    }
  }
}
```
Then decorate the related fields:

```javascript
import { prismaObjectType } from 'nexus-prisma'
import checkLocalResolution from '../../utils/checkLocalResolution';

export const File = prismaObjectType({
  name: 'File',
  definition: t => {
    t.prismaFields([
      'id',
      'createdAt',
      'updatedAt',
      'cloudId',
      'type',
      'mimeType'
    ])

    t.field('owner', checkLocalResolution('owner', t))
    t.field('projects', checkLocalResolution('projects', t))
    t.field('attributes', checkLocalResolution('attributes', t))
    t.field('cloud', checkLocalResolution('cloud', t))
  }
})
```

Depending on your query you may have to decorate the relation fields of the nested objects as well.
