### ISSUE TITLE
Ability to sensibly migrate column and table names

### ISSUE THREAD

**Issue by robmurtagh** [prisma/prisma#4714]
I've been playing around with Migrate quite a bit and one thing I know we'll need to do in future - but which looks quite tricky - is renaming columns and tables in the database.

## Columns

Considering the following `schema.prisma` diff:

```gql
model Foo {
  - fieldName  String  @map("foo")
  + fieldName  String  @map("bar")

  @map("foo_table")
}
```

This will become something like:

```sql
ALTER TABLE foo_table DROP COLUMN foo
ALTER TABLE foo_table ADD bar varchar(...)
``` 

When it could just be:

```sql
RENAME TABLE program_entity TO program_focus
```

## Tables

Considering the following `schema.prisma` diff:

```gql
model Foo {
  fieldName  String  @map("foo")

-  @map("foo_table")
+  @map("bar_table")
}
```

This will become something like:

```sql
DROP TABLE foo_table
CREATE TABLE bar_table
```

When it could just be:

```sql
RENAME TABLE foo_table TO bar_table
```

## Solutions?

Either, Migrate could understand these situations itself (although I can see that understanding the semantics of a diff could become quite challenging). Or, could there be a solution where you allow users the opportunity to write a custom SQL statement so they can continue to us Lift migrations in some of these more involved edge cases?

**Comment by tomhoule** [comment]
There are plans for interactive renames, we'll close this issue, since it is referring to old versions of migrate.
