### ISSUE TITLE
Prisma generating a NUMERIC(65, 30) for PostgreSQL, doesn't match docs

### ISSUE THREAD

**Issue by pizzafox** [prisma/prisma#4719]
Prisma 2 migrate autogenerated a column of Prisma's `Float` type as a PostgreSQL Numeric with a precision of 65 and a scale of 30.

1. [The documentation says](https://github.com/prisma/specs/tree/master/schema#core-data-type-to-connector) that this should be a `real` type in PostgreSQL, not a numeric
2. Why is Prisma making such a precise column? This will result in massively more data consumption and will make calculations wildly slow compared to any other number type (see [PostgreSQL documentation 8.1.2. Arbitrary Precision Numbers](https://www.postgresql.org/docs/12/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL))

Edit:
The generated migration Markdown file says it was attempting to create a `Decimal(65,30)`, which I believe is just an alias for the `Numeric` type.
Perhaps look through source code for that string?

**Comment by albertoperdomo** [comment]
When using the `nativeTypes` feature (in Preview) fields of type Float in Prisma are now mapped to `Double` on PostgreSQL and MySQL. This is eventually going to be the default behavior once nativeTypes is GA and the default behavior for everyone.

Does this address your problem @pizzafox ?

**Comment by pizzafox** [comment]
Doing that means using a preview feature and modifying my Prisma schema, which would work but seems unreasonable given the issues that arise from using `decimal(65, 30)`. However, changing the default behavior at this stage may be a breaking change so native types might be the only viable option.

**Comment by albertoperdomo** [comment]
I think you could wait for Migrate to be GA (really soon). Once this is GA you can decide which underlying column type to use:

* If you don't make any changes to your schema, Prisma Migrate will generate a migration to change the existing Decimal fields from Decimal(65,30) to Double.
* If you manually (or via introspection) change the scalar type of these fields to Decimal in the Prisma schema, then no migration is neededand the existing Decimal column type is preserved.
* Any new Float fields added to your schema will be created as Double in the DB via Prisma Migrate.

Does this make sense?

**Comment by pizzafox** [comment]
The idea that a migration could be created when the schema hasn't changed, and that precision in stored data could be lost seems like a Bad Idea.
Changing default behavior in the future seems like the best idea, provided that documentation describing this change is made.

**Comment by albertoperdomo** [comment]
>The idea that a migration could be created when the schema hasn't changed, and that precision in stored data could be lost seems like a Bad Idea.

This is going to be indeed a breaking change we will have to carefully communicate to our users but we believe it's for the best, because in the future we will be providing a better default. The way around the precision loss is indeed to introspect, which could be considered to some extent a codemod.
