### ISSUE TITLE
Error while creating a migration with postgresql locally installed

### ISSUE THREAD

**Issue by mbush92** [prisma/prisma#4725]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.15.1           | 
| Prisma CLI  | 2.11.0             | 
| Binary      | 58369335532e47bdcec77a2f1e7c1fb83a463918| 

## Error
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/postgres.rs:125:44] could not get columns

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

```

**Comment by janpio** [comment]
Related error reporting issue was closed as there were no recent reports any more: https://github.com/prisma/prisma/issues/3608#issuecomment-790657938
