### ISSUE TITLE
Add types for `$on('beforeExit')`

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#4733]
The types for `$on('beforeExit')` don't exist, hence the API is not discoverable and useable from TypeScript.

**Comment by ecker00** [comment]
Why doesn't this type also include `query`, only `beforeExit`? As this code runs fine, but not valid to typescript.
```ts
// @ts-ignore
client.$on('query', (event: Client.Prisma.QueryEvent) => { /*…*/ });
```
