### ISSUE TITLE
Error with Multiple Use of Embedded Type

### ISSUE THREAD

**Issue by seed-of-apricot** [prisma/prisma#4737]
**Describe the bug**
Bug? Expected?

I get an error when I use the same embedded type in one type. 

**To Reproduce**
Create:
```
type Hoge @db(name: "hoge") {
  id: ID! @id
  name: String!
  foo: Fuga
  bar: Fuga
}

type Fuga @embedded {
  value: Int!
  time: DateTime! @createdAt
}
```
and `prisma deploy`. Then will get

```
Hoge
    × The relation field `foo` must specify a `@relation` directive: `@relation(name: "MyRelation")`
    × The relation field `bar` must specify a `@relation` directive: `@relation(name: "MyRelation")`
```

**Expected behavior**
I believe it should be like
```
Hoge: {
  id: "someId",
  name: "hogehoge",
  foo: {
    value: 100,
    time: "someTime"
  },
  bar: {
    value: 200,
    time: "certainTime"
  }
}
```

**Versions (please complete the following information):**
 - Connector: `MongoDB`
 - Prisma Server: `1.35-beta`
 - OS: `Windows 10 x64`
 - other dependencies: `"nexus": "^0.12.0-beta.6", "nexus-prisma": "^0.3.7", "prisma-client-lib": "^1.34.0"`

**Comment by divyenduz** [comment]
Can you please name the relations like shown in the error message? with a @relation directive? 
There are ambiguous relations that need manual resolution. 

```
Hoge
    × The relation field `foo` must specify a `@relation` directive: `@relation(name: "MyRelation")`
    × The relation field `bar` must specify a `@relation` directive: `@relation(name: "MyRelation")`
```

Please refer to this section of docs: https://www.prisma.io/docs/datamodel-and-migrations/datamodel-MYSQL-knul/#the-@relation-directive

**Comment by do4gr** [comment]
Hey, 

we used to do this internally by generating names, but ran into situations where it was not possible to infer the users intentions during datamodel changes if the relations were not explicitly named. Since we do not want to write into your datamodel files we now require the user to name ambiguous relations.

**Comment by seed-of-apricot** [comment]
Hmm that makes sense, understood. Thanks for the info.

**Comment by divyenduz** [comment]
@seed-of-apricot Thanks, please feel free to close the issue if you think that your issue is resolved. Thanks.
