### ISSUE TITLE
Heroku Upscaling Downtime

### ISSUE THREAD

**Issue by chris-gith** [prisma/prisma#4740]
**Describe the bug**

Upscaling Dynos of the Heroku app container for the Prisma integrated Postgres database results in downtime of approximately 15 minutes.

Fatal errors cause the application to crash with the Heroku 'Application error' displayed.

There is no downtime experienced when downscaling.

Heroku Support have diagnosed the issue as being caused by errors in the Prisma Heroku Intergration code supplied and maintained by Prisma.

**To Reproduce**

Upscale the Heroku app that contains the Prisma integrated Postgres database to 3 or more Dynos.

**Expected behavior**

Dyno upscaling should occur without any downtime.

**Versions:**

 - Connector: Postgres
 - `prisma` CLI: 1.20.7
 - OS: OS X Mojave
 - `prisma-binding`: 2.1.6

**Additional context**

2X Dynos are required for the container app due to memory usage.

**Comment by pantharshit00** [comment]
If you want to upscale Prisma, this is a bit different process as you will need to use RabbitMQ as well.
Refer: https://github.com/prisma/prisma/issues/2850 

You will need to use `prisma-prod` image and you will require a master dyno that will host the management API and others node with this API disabled. RabbitMQ is required to communicate subscriptions among nodes and propagate schema changes.

Here is a great article on that: https://techblog.commercetools.com/prisma-horizontal-scaling-a-practical-guide-3a05833d4fc3
