### ISSUE TITLE
Prisma cli error query-engine-debian-openssl-1.1.x: error while loading shared libraries

### ISSUE THREAD

**Issue by shivamsingha** [prisma/prisma#4741]
## Bug description

I'm trying to run `npx prisma migrate dev --name init --preview-feature` but I'm getting this error
> Error: Get config /home/digit449/.npm/_npx/12788/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

## How to reproduce

1. `npm install @prisma/cli --save-dev`
2. `npx prisma init`
3. Edit schema and .env as required
4. `npx prisma migrate dev --name init --preview-feature`

## Expected behavior

Migration should finish successfully

## Environment & setup

- OS: CloudLinux 7.9
- Database: PostgreSQL
- Node.js version: 14.15.1
- Prisma version: Most likely 2.13.1 but I get error on `prisma -v`

> Error: Command failed with exit code 127: /home/digit449/.npm/_npx/19277/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version
/home/digit449/.npm/_npx/19277/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by Dko1905** [comment]
I have just experienced the issue, may I ask why you closed the issue?
```
Error: Get config /home/daniel/Documents/ts-todo/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by pantharshit00** [comment]
@Dko1905 

This error happens when your distro doesn't have openssl. You can install it on ubuntu like so:
```
sudo apt install libssl-dev
```

**Comment by Dko1905** [comment]
Thank you for the explanation.
I am currently running [Void Linux](https://voidlinux.org/), I have libressl installed including dev dependencies, and it doesn't work. The package version is `libssl48-3.1.5_2` and `libressl-3.1.5_2`
Would you recommend opening a new issue?

**Comment by pantharshit00** [comment]
Yeah sure, open it. I am not entirely sure prisma works with libressl. 

Try compile from source for now: https://github.com/prisma/prisma-engines#building-prisma-engines

https://www.prisma.io/docs/concepts/overview/under-the-hood#using-custom-engine-binaries

**Comment by Dko1905** [comment]
I will create an issue.

**Comment by shivamsingha** [comment]
@Dko1905 The VPS I was using some old enterprise linux based on CentOS and didn't have the latest version of OpenSSL.
