### ISSUE TITLE
Invalid argument type with this.$on(...) in an extended class of PrismaClient

### ISSUE THREAD

**Issue by devalnor** [prisma/prisma#4746]
## Bug description

Typescript return `Argument of type 'string' is not assignable to parameter of type 'never'` when we want to use `this.$on()`in a extend class of PrismaClient

## How to reproduce

Bug can be reproduce based  on official starter 

`curl -L https://pris.ly/quickstart | tar -xz --strip=2 quickstart-master/typescript/starter`

```ts 
// index.ts
class Test extends PrismaClient {
  constructor() {
    super({
      log: [
        {
          emit: 'event',
          level: 'info',
        },
      ],
    });
    // Return Argument of type 'string' is not assignable to parameter of type 'never'.
    this.$on('info', (e) => {
      console.log(e);
    });
    this.post.findMany()
  }
  
  test() {
    // Return Argument of type 'string' is not assignable to parameter of type 'never'.
    this.$on('info', (e) => {
      console.log(e);
    });
  }
} 
```

## Expected behavior

 `this.$on()` may accept  strings `info`,`query` or `warn` as log level like it does with `prisma.$on()`

More info: https://www.prisma.io/docs/concepts/components/prisma-client/logging#the-log-option

## Environment & setup

- OS: Mac OS 10.14.6
- Database:SQLite
- Node.js version: v14.15.1
- Prisma version: 2.13.1

```

```

**Comment by pantharshit00** [comment]
@devalnor 

Do this:
```ts
import { PrismaClient, Prisma } from "@prisma/client";

class Test extends PrismaClient<Prisma.PrismaClientOptions, "info"> {
  constructor() {
    super({
      log: [
        {
          emit: "event",
          level: "info",
        },
      ],
    });
    // Return Argument of type 'string' is not assignable to parameter of type 'never'.
    this.$on("info", (e) => {
      console.log(e);
    });
    this.post.findMany();
  }

  test() {
    // Return Argument of type 'string' is not assignable to parameter of type 'never'.
    this.$on("info", (e) => {
      console.log(e);
    });
  }
}
```


You need to pass generics yourself as our types can't infer that from usage here. We have these generics in place as you limit type of first argument of `$on` which is only enabled when user passes some option to the client.

**Comment by devalnor** [comment]
It work!
Thank you @pantharshit00

**Comment by nikelborm** [comment]
May be related https://github.com/prisma/prisma/pull/24133
