### ISSUE TITLE
Prisma `migrate dev` prompts for migration name when running after --create-only

### ISSUE THREAD

**Issue by webnoob** [prisma/prisma#4748]
Suppose you create your migration files using:

`prisma migrate dev --create-only --preview-feature`

Then when you run `prisma migrate dev --preview-feature` to apply the changes (without changing the SQL), you are prompted for a migration name. Once entered, everything applies but you end up with a migration file that just drops and adds FK's.

I assume this is because you're expecting `--create-only` to only be used as a precursor to manual sql changes being made to the generated SQL files but that's not the case with me - it's just easier to build into my flow and I also like to check the SQL before it's applied.

If the SQL hasn't changed, I wouldn't expect to be prompted to enter a new migration name.

**Comment by pantharshit00** [comment]
Hey @webnoob 

Can you please paste your schema and what you added to the `--create-only` migration? I am unable to reproduce this. The next execution doesn't generate a migration for me which drops and adds FKs

**Comment by webnoob** [comment]
Sorry for the delay, have been deep in a sprint.
Will do this ASAP.

**Comment by albertoperdomo** [comment]
Hello @webnoob, have you had any chance to look into this so that we have more info for reproduction?

**Comment by webnoob** [comment]
Sorry, I've been stuck in a refactor. I'll do it on Monday and post back for you.

**Comment by webnoob** [comment]
Can you remind me of the email address I can use to send schema to please? I've just tested it and it's still happening.

**Comment by pantharshit00** [comment]
@webnoob It's schemas@prisma.io. Please comment here as well after you have sent the details :)

**Comment by webnoob** [comment]
Email sent. Issue is in the subject.

**Comment by pantharshit00** [comment]
Hey @webnoob 


Sorry for the late reply here. I wasn't able to reproduce this with your schema as well. I did the following:
```bash
npx prisma migrate dev --preview-feature # to create an inital migration from the schema
npx prisma migrate dev --create-only --preview-feature # making custom migration and leaving it empty
npx prisma migrate dev --preview-feature # to apply the migrations again
```



It didn't generate the migrate which dropped the FKs:
![image](https://user-images.githubusercontent.com/22195362/106272434-12156180-6257-11eb-9333-d3efb1ca1677.png)


If I got something wrong, please let me know. Otherwise please try this again with the latest version once.

**Comment by webnoob** [comment]
@pantharshit00 

Ok, I'm running 2 commands, not 3:

1: `npx prisma migrate dev --create-only --preview-feature`
2: `npx prisma migrate dev --preview-feature`

In that order. First is to create the file, second is to apply it.

What happens?

Run (1) then it asks for a migration name, I enter `Init`. Migration is created as expected. 
Run (2) and it applies the `Init_xxx` migration. It then immediately asks me for another migration name. If I enter a migration name here, I get a migration which just _drops_ and then _recreates_ the FK's. Basically, it's doing nothing. I think the issue stems from the fact that it shouldn't be asking for a migration at this point. If I escape out of the process then the second migration file isn't created but I don't like doing this as the command should be allowed to complete.

I'm on windows 10 with mysql server 8.0

**Comment by albertoperdomo** [comment]
I think this is related to the issue where foreign keys are not preserved, but dropped and re-created. https://github.com/prisma/prisma/issues/5244

**Comment by webnoob** [comment]
> I think this is related to the issue where foreign keys are not preserved, but dropped and re-created. #5244

Yes BUT it shouldn't be prompting me for another migration after applying one with no changes.

**Comment by Jolg42** [comment]
Maybe this comment helps https://github.com/prisma/prisma/issues/5244#issuecomment-773317394

**Comment by webnoob** [comment]
I could do with knowing whether my issue has been recreated or not before investing more time into this ticket. I see a thumbs up on my description of how to reproduce by @pantharshit00 but I don't know if that means it's recreated :)

That being said, I see a few other issues opening up for this kind of issue now so it's becoming more apparent there is an underlying issue around this.

**Comment by pimeys** [comment]
Taking a look today to see if we still have an issue, or is it fixed already.

**Comment by pimeys** [comment]
Ok, I couldn't reproduce this with Prisma version 2.17.0. My steps:

```sh
> mkdir migration-4748
> cd migration-4748
> npm init -y
# don't worry about typescript, I won't be using any of it here
> npm install prisma@2.17.0 typescript ts-node @types/node --save-dev
> npx prisma init
# here we edit the .env to point to the correct database
> npx prisma migrate dev --create-only --preview-feature

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "bug_4748" at "localhost:3307"

MySQL database bug_4748 created at localhost:3307

✔ Name of migration … test
Prisma Migrate created the following migration without applying it 20210219141457_test

You can now edit it and apply it by running prisma migrate dev --preview-feature.

> npx prisma migrate dev --preview-feature

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "bug_4748" at "localhost:3307"

The following migration(s) have been applied:

migrations/
  └─ 20210219141457_test/
    └─ migration.sql


Running generate... (Use --skip-generate to skip the generators)

up to date, audited 1 package in 2s

found 0 vulnerabilities

added 4 packages, and audited 5 packages in 2s

found 0 vulnerabilities

✔ Generated Prisma Client (2.17.0) to ./node_modules/@prisma/client in 407ms

Everything is now in sync.
```

As you can see, we ask for a name for the migration in the first run with `--create-only`, then the second run just executes correctly to the database. Could you try out this with the latest version and see if you still get a new migration, or is your problem solved? If you want to talk to me directly, you can find me from our public slack, please send me a message if you need more help.

**Comment by webnoob** [comment]
Ok, this looks more like my scenario - excellent.

I'll get the upgrade done next week. There are _more_ breaking changes between .14 and .16 so I've been holding off.

I'll come back to you ASAP.

**Comment by webnoob** [comment]
I've tried this on 2.17.0 and am seeing the same results as I was originally.

Are you testing using the Windows platform?

**Comment by webnoob** [comment]
In fact, it's even worse now. It won't even apply the migration:
![image](https://user-images.githubusercontent.com/10404747/108705307-09861300-7505-11eb-8eae-dccea8a9e1e1.png)

**Comment by tomhoule** [comment]
@webnoob there is a known regression with windows installations of MySQL in 2.17.0. We are considering shipping a patch, but in the meantime the right move is to revert to 2.16.0. We planned time to look into your issues before 2.18.0, help is coming.

**Comment by tomhoule** [comment]
@webnoob I spent some time trying to reproduce your issue — I think it's something tied to MySQL on windows specifically, I'll attempt a fix to be released in 2.18.0, but can't guarantee it will solve everything.

**Comment by webnoob** [comment]
Windows does seem to cause some issues in Prisma.

Thanks for the update - I'll be ready to test when it's available (if you let me know when things are pushed to dev, I can try that).

**Comment by pimeys** [comment]
It's more the Windows installation of MySQL and the default case-sensitivity settings. Running MySQL in Docker on Windows works much better, but of course doesn't help if your production server is MySQL running on Windows.

**Comment by pimeys** [comment]
I booted to my Windows partition today to debug this on that side. I can reproduce the issue with 2.17.0 by installing MySQL 5.6 with the Windows installer, and making sure the case-insensitive identifiers setting is set to `1`.

Now, testing again with 2.18.0-dev.49, and it doesn't have this issue, meaning it was fixed during this sprint.

The problem of testing this is that this setting seems to be Windows-only, and our whole CI setup is based on Docker and Linux.

**Comment by pimeys** [comment]
2.18.0 should be out tomorrow btw.

**Comment by webnoob** [comment]
Ok, that's good to know. I'll upgrade and test as soon as it's released - thanks for your work.

> The problem of testing this is that this setting seems to be Windows-only, and our whole CI setup is based on Docker and Linux.
I understand, but windows testing would be useful. This essentially broke the entire migration system for this release :(

**Comment by pimeys** [comment]
We've discussed this today with @tomhoule and I fully agree with you. It's not very common to run MySQL services on Windows with the default settings, so we're mostly covering the biggest use cases: meaning docker/linux and as a sideline, macos. We're discussing though to have some test setup that could run on Windows, and would not take a week to build.

**Comment by webnoob** [comment]
I can confirm this particular issue is now resolved on 2.18.0 🥳 

Thanks @tomhoule and @pimeys

**Comment by sibeliuz** [comment]
Got this bug in 2.19.

**Comment by webnoob** [comment]
@sibeliuz Are you sure it's the same? I was being prompted for another migration file following the first creation. It just looks like you have 2 migrations called init.

If you clear your migrations folder and start again, do you end up with 2 migration files?

**Comment by sibeliuz** [comment]
It prompts for migration name two times, one at
npx prisma migrate dev --create-only
and one at following
npx prisma migrate dev 
Generated sql script was not changed between calls.
It also creates two migrations in the migration folder (migration folder was deleted before).
Schema on which it always happens:

`generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["groupBy", "orderByRelation", "createMany"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model example {
  id             String                 @id @db.Uuid
  typeId         String                 @map("type_id") @db.Uuid @default("00000000-0000-0000-0016-000000000004")
}
`
Interestingly, the first migration file here it creates is:

`-- CreateTable
CREATE TABLE "example" (
    "id" UUID NOT NULL,
    "type_id" UUID NOT NULL DEFAULT E'00000000-0000-0000-0016-000000000004',

    PRIMARY KEY ("id")
);
`

and the second is:

`-- AlterTable
ALTER TABLE "example" ALTER COLUMN "type_id" SET DEFAULT E'00000000-0000-0000-0016-000000000004';
`

So the problem is that it tries to re-create  default.

**Comment by sibeliuz** [comment]
Should it be posted as a new issue or i don't understand something?
