### ISSUE TITLE
Port introspection connector to Rust

### ISSUE THREAD

**Issue by aknuds1** [prisma/prisma#4749]
Port introspection connector from TypeScript to Rust, for now scoped to introspection of Postgres/MySQL/SQLite. TypeScript implementation can be found [here](https://github.com/prisma/prisma/tree/master/cli/packages/prisma-db-introspection/src/databases/relational).

- [x] Implement `IntrospectionConnector` trait for SQLite
- [ ] Consider supporting the AUTOINCREMENT variety of primary key in SQLite
- [x] Implement indices discovery for SQLite
- [x] Implement `IntrospectionConnector` trait for Postgres
- [x] Ensure all Postgres types are supported.
- [x] Implement `IntrospectionConnector` trait for MySQL
- [x] Test/support foreign keys with multiple columns
- [x] Support `ON_DELETE` setting for foreign keys (SET_NULL, CASCADE etc)
- [x] Make DatabaseSchema serializable - combine with snapshot tests to ensure backwards compatibility is kept over time
- [x] Fix detection of `ON DELETE` actions for SQLite
- [x] Handle schema names with hyphens for MySQL and SQLite
- [x] Implement generating of model from introspection results (should basically be inverse operation of [this](https://github.com/prisma/prisma/blob/alpha/server/prisma-rs/migration-engine/connectors/sql-migration-connector/src/database_schema_calculator.rs))

**Comment by do4gr** [comment]
Just dropping this here, since we might want to use this later on for the Mongo introspection. Not sure if you already knew this repo. 

https://github.com/mongodb-rust/mongodb-schema-parser

**Comment by aknuds1** [comment]
> Just dropping this here, since we might want to use this later on for the Mongo introspection. Not sure if you already knew this repo.
> 
> https://github.com/mongodb-rust/mongodb-schema-parser

@do4gr Thanks, wasn't aware of this schema, no. But concentrating on the three aforementioned DBs for now :)

**Comment by aknuds1** [comment]
Closing in favour of individual issues.
