### ISSUE TITLE
[Introspection] `uuid()` inference/detection with older MySQL versions or application generated IDs

### ISSUE THREAD

**Issue by robmurtagh** [prisma/prisma#475]
DB Version: `MySQL 5.7.14`

I used `prisma introspect` to create a `schema.prisma` file.

The following column:

![Screenshot 2019-08-30 at 17 20 23](https://user-images.githubusercontent.com/5772846/64036294-bf5be580-cb4a-11e9-9967-e3b171cd84ec.png)

Was introspected as:

```
model Program {
  uuid  String  @default("") @id
}
```

I think it should have been:

```
model Program {
  uuid  String  @default(uuid()) @id
}
```

**Comment by pantharshit00** [comment]
I can confirm this but it is a hard pass. Since MySQL < 8.0.13 doesn't support expression in default values, it is hard to guess that ID type without analysing the data(unlike postgres which supports a native uuid column type).

Can you please tell me the type of uuid column. In my reproduction, I used `varchar(36)` value.

**Comment by robmurtagh** [comment]
Thanks @pantharshit00. Yes, in our DB the column is `varchar(255)`.

Just checking, what do you mean by _hard pass_?

Completely understand, I don't think this one is a deal breaker at all, it definitely threw us for a little while though.

**Comment by pantharshit00** [comment]
> Just checking, what do you mean by hard pass?

Right now we inferring everything from the database schema. We will need to change our strategy to infer this from the data if we want to support this. 

By the way, I want to know how you are inserting the UUIDs. Are you using a trigger, or using the `uuid()` function in the SQL string or inserting them in runtime calls.

**Comment by robmurtagh** [comment]
Ok, thanks, that makes sense.

I think the UUIDs are being generated by the application-layer at runtime (i.e. not the database)

**Comment by janpio** [comment]
@pantharshit00 Please do make sure this feature request gets its own issue with proper description and everthing.

**Comment by janpio** [comment]
This is to tricky, as it could have so many side effects.
Please apply `@default(uuid())` yourself in the schema file.
