### ISSUE TITLE
Prisma Migrate: Better UX when referencing migrations in resolve command

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#4750]
## Problem

prisma migate resolve requires the migration directory as a parameter, but this is not obvious and some users are using the migration name without the timestamp prefix

When Prisma migrate fails to find the right migration it throws this user-facing error message:

```
Error: Failed to read migration script
```

## Suggested Solution

Improve the error message, by stating that it should be the directory name of the migration, including the timestamp, i.e. `"20201207184859_initial_migration" `

## Additional Context

* https://github.com/prisma/prisma/issues/4571#issuecomment-748686678

**Comment by do4gr** [comment]
So this is mostly work on the migration engine side. 
We'll need to make sure that we only proceed if name without the timestamp prefix identifies a unique subfolder.

On the CLI side we need to handle the two new ErrorVariants MigrationNotUnique and MigrationNotFound that the engine could return.
