### ISSUE TITLE
Prisma Migrate: Support for configuring the shadow DB URL

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#4751]
## Problem

The `migrate dev` or `migrate reset` commands in Prisma Migrate require a shadow database. Prisma Migrate assumes the same credentials used for the development database can be used to create it. When using a local DBMS, this can be achieved by granting the user privileges to create new databases.

Some of our users develop on the cloud and don't run their DBMS locally. This prevents these users from using Prisma Migrate in development unless they switch to using a local DBMS.

## Solutions

We could allow users to provide a URL to a shadow database that can be used as the shadow database. Example: a user could provision two Postgres databases on Heroku, one for the development another the shadow database.

In order to do this, we'd need to enable a way to supply this configuration, i.e., config file, env variable, etc.

**Comment by albertoperdomo** [comment]
Update: after carefully considering multiple options, we have decided that this configuration would be made via the Prisma schema file, by adding one more field to the `datasource` block.

We don't think it's very elegant but it works and is consistent with the way the main database URL is configured. We hope we are able to revisit at some point the entire configuration topic at a high level, this would be one more configuration bit that would be taken into account.

**Comment by perryraskin** [comment]
@albertoperdomo will v2.15 have it set up that way and ready to use? I really need to update and have `groupBy` abilities!

**Comment by albertoperdomo** [comment]
@perryraskin Unfortunately not, but hopefully we can release it in 2.16.0. Thanks for your patience while we figure out the best solution.

**Comment by Jolg42** [comment]
@tomhoule Looks like it would be a good thing to add a check at runtime to verify that the db url and shadow db url database are different.

**Comment by JasonEtco** [comment]
👋 Thanks for working on this! I wanted to clarify something, and ask a question about alternatives.

> Some of our users develop on the cloud and don't run their DBMS locally. 

This implies that the `prisma migrate` command is intended for development-only; if that's the case, what's the correct way to update a **production** database? In other words, once I've run `prisma migrate` locally and generated the `migration.sql` files, what's the correct way to run that migration? Is it through `prisma db push`?

**Comment by tomhoule** [comment]
Hi @JasonEtco , indeed it is `deploy`. Thanks for the feedback!

**Comment by Jolg42** [comment]
@JasonEtco I just created https://github.com/prisma/prisma/issues/5531 to mention it, great idea! Thanks!

**Comment by albertoperdomo** [comment]
This feature is now live in 2.17.0 - https://github.com/prisma/prisma/releases/tag/2.17.0

For feedback, please post on https://github.com/prisma/prisma/issues/4531.
