### ISSUE TITLE
prepared statement \"s0\" already exists when connecting to pgbouncer with ssl

### ISSUE THREAD

**Issue by s-kris** [prisma/prisma#4752]
## Bug description
I'm connecting to postgres on digital ocean with pgbouncer as guided here: https://www.prisma.io/docs/concepts/database-connectors/postgresql#configuring-an-ssl-connection. And also appended `pgbouncer=true&statement_cache_size=0` as suggested by @ryands17 

`ConnectorError: prepared statement \"s0\" already exists when connecting to pgbouncer with ssl` is thrown for every query.

**Full error:**
```
PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]:
Invalid `prisma.siteMember.findMany()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s0\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(463), routine: Some("StorePreparedStatement") }) }) })
    at PrismaClientFetcher.request (/XXXXXXXXXXX/node_modules/@prisma/client/runtime/index.js:78125:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.13.0'
}
```

## How to reproduce
1. Setup a managed database on digital ocean.
2. Create pgbouncer pool.
3. Connect with SSL config the above.
4. Run any query

## Expected behavior
Prisma queries should be executed normally when connected to a pgbouncer pool'd db.

## Prisma information
Connection string: `postgres://<XXXXXXXXXXXX>/default?sslmode=require&&sslcert=db-ssl.crt&sslpassword=<XXXXX>&sslidentity=db-ssl.p12&pgbouncer=true&statement_cache_size=0`

## Environment & setup

- OS:  Mac OS 10.15.4
- Database: PostgreSQL 12 
- Node.js version: 14.4.0 
- Prisma version: 2.13.0

```
@prisma/cli          : 2.13.0
@prisma/client       : 2.13.0
Current platform     : darwin
Query Engine         : query-engine 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
```

# Complete Debug Log
```
  tryLoadEnv Environment variables not found at null +0ms
  tryLoadEnv Environment variables not found at undefined +0ms
  tryLoadEnv No Environment variables loaded +1ms
  tryLoadEnv Environment variables not found at null +10ms
  tryLoadEnv Environment variables not found at undefined +0ms
  tryLoadEnv No Environment variables loaded +0ms
  prisma-client { clientVersion: '2.13.0' } +0ms
  prisma-client Prisma Client call: +77ms
  prisma-client prisma.siteMember.findMany({
  prisma-client   where: {
  prisma-client     userId: 1
  prisma-client   },
  prisma-client   include: {
  prisma-client     site: {
  prisma-client       include: {
  prisma-client         posts: {
  prisma-client           select: {
  prisma-client             title: true
  prisma-client           }
  prisma-client         }
  prisma-client       }
  prisma-client     }
  prisma-client   },
  prisma-client   orderBy: {
  prisma-client     createdAt: 'desc'
  prisma-client   }
  prisma-client }) +2ms
  prisma-client Generated request: +0ms
  prisma-client query {
  prisma-client   findManySiteMember(
  prisma-client     where: {
  prisma-client       userId: 1
  prisma-client     }
  prisma-client     orderBy: [
  prisma-client       {
  prisma-client         createdAt: desc
  prisma-client       }
  prisma-client     ]
  prisma-client   ) {
  prisma-client     id
  prisma-client     siteId
  prisma-client     userId
  prisma-client     role
  prisma-client     createdAt
  prisma-client     updatedAt
  prisma-client     addedBy
  prisma-client     site {
  prisma-client       id
  prisma-client       name
  prisma-client       createdAt
  prisma-client       updatedAt
  prisma-client       posts {
  prisma-client         title
  prisma-client       }
  prisma-client     }
  prisma-client   }
  prisma-client }
  prisma-client  +0ms
  engine {
  engine   cwd: '/Users/XXXXXXX/prisma'
  engine } +0ms
  engine Search for Query Engine in /Users/XXXXXXX/node_modules/.prisma/client +1ms
  plusX Execution permissions of /Users/XXXXXXX/node_modules/.prisma/client/query-engine-darwin are fine +0ms
  engine {
  engine   flags: [
  engine     '--enable-raw-queries',
  engine     '--unix-path',
  engine     '/tmp/prisma-ccda131f44c9c5e83960f619.sock'
  engine   ]
  engine } +1ms
  engine stdout {
  timestamp: 'Dec 21 16:17:46.726',
  level: 'INFO',
  fields: { message: 'Starting a postgresql pool with 1 connections.' },
  target: 'quaint::pooled'
} +48ms
  engine stdout {
  timestamp: 'Dec 21 16:17:48.659',
  level: 'INFO',
  fields: {
    message: 'Started http server on http+unix:///private/tmp/prisma-ccda131f44c9c5e83960f619.sock'
  },
  target: 'query_engine::server'
} +2s
  engine Search for Query Engine in Users/XXXXXXX/node_modules/.prisma/client +5ms
  plusX Execution permissions of /Users/XXXXXXX/node_modules/.prisma/client/query-engine-darwin are fine +2s
  engine Client Version 2.13.0 +25ms
  engine Engine Version query-engine 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 +0ms
  engine {
  engine   error: PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s0\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(463), routine: Some("StorePreparedStatement") }) }) })
  engine       at NodeEngine.graphQLToJSError (/Users/XXXXXXX/node_modules/@prisma/client/runtime/index.js:27363:14)
  engine       at /Users/XXXXXXX/node_modules/@prisma/client/runtime/index.js:27285:24
  engine       at /Users/XXXXXXX/node_modules/@risingstack/react-easy-state/dist/cjs.es6.js:243:63
  engine       at Object.batchedUpdates$1 (/Users/XXXXXXX/node_modules/react-dom/cjs/react-dom.development.js:21856:12)
  engine       at batch (/Users/XXXXXXX/node_modules/@risingstack/react-easy-state/dist/cjs.es6.js:243:30)
  engine       at Object.apply (/Users/XXXXXXX/node_modules/@risingstack/react-easy-state/dist/cjs.es6.js:264:16)
  engine       at runMicrotasks (<anonymous>)
  engine       at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  engine     clientVersion: '2.13.0'
  engine   }
  engine } +280ms
  prisma-client Error: Error occurred during query execution:
  prisma-client ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s0\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(463), routine: Some("StorePreparedStatement") }) }) })
  prisma-client     at NodeEngine.graphQLToJSError (/Users/XXXXXXXnode_modules/@prisma/client/runtime/index.js:27363:14)
  prisma-client     at /Users/XXXXXXX/node_modules/@prisma/client/runtime/index.js:27285:24
  prisma-client     at /Users/Users/XXXXXXX/node_modules/@risingstack/react-easy-state/dist/cjs.es6.js:243:63
  prisma-client     at Object.batchedUpdates$1 (/Users/XXXXXXX/node_modules/react-dom/cjs/react-dom.development.js:21856:12)
  prisma-client     at batch (/Users/XXXXXXX/node_modules/@risingstack/react-easy-state/dist/cjs.es6.js:243:30)
  prisma-client     at Object.apply (/Users/XXXXXXX/node_modules/@risingstack/react-easy-state/dist/cjs.es6.js:264:16)
  prisma-client     at runMicrotasks (<anonymous>)
  prisma-client     at processTicksAndRejections (internal/process/task_queues.js:97:5) +2s
PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]:
Invalid `prisma.siteMember.findMany()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s0\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(463), routine: Some("StorePreparedStatement") }) }) })
    at PrismaClientFetcher.request (/Users/XXXXXXX/node_modules/@prisma/client/runtime/index.js:78125:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.13.0'
}
```

**Comment by pantharshit00** [comment]
Hey @s-kris 

I was unable to reproduce this. I think you are using the database credentials here instead of pgbouncer credentials. Digitalocean provides different credentials for pgbouncer and you should use them when querying your database. The direct database credentials will not work and only use them for migrating the database structure. 

Get the connection details for the pool from here:
![image](https://user-images.githubusercontent.com/22195362/103139012-d1797400-46fd-11eb-82f8-f3cb762cf827.png)

Also, please absolutely make sure that you selected transaction mode here. 

![image](https://user-images.githubusercontent.com/22195362/103138999-adb62e00-46fd-11eb-9ac6-7de8f928b141.png)


Other modes are not supported.

**Comment by s-kris** [comment]
@pantharshit00 I'm using pgbouncer credentials in transaction mode only. I just reverified now.

**Comment by viperfx** [comment]
I have a similar issue. Exact same setup, using DO with bouncer and Transaction mode. Prisma is using the credentials from DO bouncer too.

**Comment by AlessandroA** [comment]
It's working for me. I use prisma/client 2.12.1 and the following `DATABASE_URL`:

```
postgresql://username:password@db_host:5432/dbname?schema=public&pgbouncer=true&sslmode=require
```

(note the `pgbouncer` and `sslmode` options)

**Comment by viperfx** [comment]
@AlessandroA are you using a DO hosted postgres DB? and using their connection pool credentials?

**Comment by AlessandroA** [comment]
Yes! It's a DigitalOcean PostgreSQL database and I connect through a connection pool. I configured it in transaction mode.

I don't know if this changed recently, but the credentials for pooled and non-pooled connections are exactly the same. The only difference is the db port.

**Comment by viperfx** [comment]
OK awesome. Just added that extra flag and it works for me too.

**Comment by pantharshit00** [comment]
@s-kris Can you please double check as well?

**Comment by benatkin** [comment]
pgbouncer=true is the flag?

**Comment by pantharshit00** [comment]
Yes, sample uri `postgresql://user:pass@host:5432/mydb?schema=public&pgbouncer=true`

**Comment by OriginalEXE** [comment]
I have had this exact same issue. Adding `&pgbouncer=true` to the end of the connection string fixed the issue.

Is this something that should be fixed on the DO side, or on the Prisma side?

**Comment by janpio** [comment]
None of both - this just needs to be documented better on our side and possibly be caught as an error message. If you want to use pgBouncer, you need to supply that parameter in Prisma. No way around it right now.

**Comment by s-kris** [comment]
@pantharshit00 sorry for delayed response. 
Yes, I added the flag. I double checked. Triple checked.

**Comment by pantharshit00** [comment]
I guess we should wait for next release here. Unfortunately without a reproduction it is not feasible for us to investigate this further.

**Comment by s-kris** [comment]
@pantharshit00 sure. I'll try to create a demo shortly.

**Comment by nahtnam** [comment]
I'm starting to get this error as well, anything I can do to help?

Here are some traces I got:
```
Datasource "db": PostgreSQL database "my-db-name", schema "public" at "my-connection-url"
Error: undefined: Database error: Error querying the database: db error: ERROR: prepared statement "s0" already exists
   0: sql_migration_connector::flavour::postgres::ensure_connection_validity
           with self=PostgresFlavour { url: PostgresUrl { url: Url { scheme: "postgresql", host: Some(Domain("my-connection-url")), port: Some(25061), path: "/my-db-name", query: Some("sslmode=require&pgbouncer=true&statement_cache_size=0"), fragment: None }, query_params: PostgresUrlQueryParams { ssl_params: SslParams { certificate_file: None, identity_file: None, identity_password: <HIDDEN>, ssl_accept_mode: AcceptInvalidCerts }, connection_limit: None, schema: "public", ssl_mode: Require, pg_bouncer: true, host: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(5s), statement_cache_size: 0 } }, features: BitFlags<MigrationFeature>(0b0) } connection=Connection(Postgres(PostgresUrl { url: Url { scheme: "postgresql", host: Some(Domain("my-connection-url")), port: Some(25061), path: "/my-db-name", query: Some("sslmode=require&pgbouncer=true&statement_cache_size=0"), fragment: None }, query_params: PostgresUrlQueryParams { ssl_params: SslParams { certificate_file: None, identity_file: None, identity_password: <HIDDEN>, ssl_accept_mode: AcceptInvalidCerts }, connection_limit: None, schema: "public", ssl_mode: Require, pg_bouncer: true, host: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(5s), statement_cache_size: 0 } }))
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:120
   0: sql_migration_connector::flavour::postgres::ensure_connection_validity
           with self=PostgresFlavour { url: PostgresUrl { url: Url { scheme: "postgresql", host: Some(Domain("my-connection-url")), port: Some(25061), path: "/my-db-name", query: Some("sslmode=require&pgbouncer=true&statement_cache_size=0"), fragment: None }, query_params: PostgresUrlQueryParams { ssl_params: SslParams { certificate_file: None, identity_file: None, identity_password: <HIDDEN>, ssl_accept_mode: AcceptInvalidCerts }, connection_limit: None, schema: "public", ssl_mode: Require, pg_bouncer: true, host: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(5s), statement_cache_size: 0 } }, features: BitFlags<MigrationFeature>(0b0) } connection=Connection(Postgres(PostgresUrl { url: Url { scheme: "postgresql", host: Some(Domain("my-connection-url")), port: Some(25061), path: "/my-db-name", query: Some("sslmode=require&pgbouncer=true&statement_cache_size=0"), fragment: None }, query_params: PostgresUrlQueryParams { ssl_params: SslParams { certificate_file: None, identity_file: None, identity_password: <HIDDEN>, ssl_accept_mode: AcceptInvalidCerts }, connection_limit: None, schema: "public", ssl_mode: Require, pg_bouncer: true, host: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(5s), statement_cache_size: 0 } }))
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:120
```
Ignore any inconsistencies, I tried to manually replace sensitive info

**Comment by pantharshit00** [comment]
@nahtnam Use `pgbouncer=true` only with the client. Omit when using with migrate. Also, we don't recommend running migrate over pgbouncer. Run it directly over your database connection as it is one off operation everytime

**Comment by viperfx** [comment]
Any particular reason why migrations should not be run over the pooled connection? Does this apply to the new preview migrate command too?

It's worth noting that most applications have a single DATBASE_URL - so just ommiting it is not so easy. Larger applications are also likely to run migrations as part of the deployment too.

**Comment by s-kris** [comment]
I was able to connect to pool with SSL. The change I did was to remove sslidentity and sslpassword from connection string. Was able connect to DO cluster using .crt file.


DATABASE_URL=`postgres://XXXXXXXXXXXXXX?connection_limit=3&sslmode=require&&sslcert=ssl.crt&pgbouncer=true&connect_timeout=10&pool_timeout=30`

**Comment by linojon** [comment]
Had similar issues, solved it by naming the connection pool the same as the database. No need to use ca_certificate. Found this here https://www.digitalocean.com/community/questions/how-to-set-up-client-certificates-for-managed-postgres

**Comment by lassegit** [comment]
Having the same issue on Digitalocean using connection pool with NextJS and Postgres. To fix this I did the following: 

- added `DATABASE_URL_MIGRATE` environment variable with a regular database connection 
- added `DATABASE_URL` environment variable with database connection pool

Created a `migrate.js` script in the root:

```js
#!/usr/bin/env node

'use strict';

const { execSync } = require('child_process');
const { DATABASE_URL_MIGRATE } = process.env;

try {
  // Run the migrate with database connection not using pooling
  // See: https://github.com/prisma/prisma/issues/4752
  execSync(`DATABASE_URL=${DATABASE_URL_MIGRATE} yarn prisma migrate deploy`);
} catch (error) {
  console.error(error);
  process.exit(1);
}
```

Invoke the script before every deployment from the `package.json`:

```json
"scripts": {
  "start": "yarn migrate && next start",
  "migrate": "node ./migrate.js",
  }
```

This should solve it.

**Comment by janpio** [comment]
@lassegit You can probably skip the redirection to a js file, and just do `"migrate": "DATABASE_URL=\"$DATABASE_URL_MIGRATE\" yarn prisma migrate deploy",` instead (The `yarn` in the script command might even be not necessary - not sure).

**Comment by kno-raziel** [comment]
> Having the same issue on Digitalocean using connection pool with NextJS and Postgres. To fix this I did the following:
> 
> * added `DATABASE_URL_MIGRATE` environment variable with a regular database connection
> * added `DATABASE_URL` environment variable with database connection pool
> 
> Created a `migrate.js` script in the root:
> 
> ```js
> #!/usr/bin/env node
> 
> 'use strict';
> 
> const { execSync } = require('child_process');
> const { DATABASE_URL_MIGRATE } = process.env;
> 
> try {
>   // Run the migrate with database connection not using pooling
>   // See: https://github.com/prisma/prisma/issues/4752
>   execSync(`DATABASE_URL=${DATABASE_URL_MIGRATE} yarn prisma migrate deploy`);
> } catch (error) {
>   console.error(error);
>   process.exit(1);
> }
> ```
> 
> Invoke the script before every deployment from the `package.json`:
> 
> ```json
> "scripts": {
>   "start": "yarn migrate && next start",
>   "migrate": "node ./migrate.js",
>   }
> ```
> 
> This should solve it.


On Windows I had to use:

```javascript 
require('dotenv').config();
const { execSync } = require('child_process');
const { DATABASE_URL_MIGRATE } = process.env;

try {
  // Run the migrate with database connection not using pooling
  // See: https://github.com/prisma/prisma/issues/4752
  execSync(`cross-env DATABASE_URL=${DATABASE_URL_MIGRATE} npx prisma db pull`, { stdio: 'inherit' });
} catch (error) {
  console.error(error);
  process.exit(1);
}
```

🤷‍♂️

**Comment by leerobert** [comment]
> @lassegit You can probably skip the redirection to a js file, and just do `"migrate": "DATABASE_URL=\"$DATABASE_URL_MIGRATE\" yarn prisma migrate deploy",` instead (The `yarn` in the script command might even be not necessary - not sure).

Specifically for me with NextJS/vercel & a managed digitalocean postgres database, in the `package.json`:

`"vercel-build": "prisma generate && DATABASE_URL=\"$DATABASE_URL_MIGRATE\" prisma migrate deploy && next build",`

Where `DATABASE_URL_MIGRATE` is in the form: `postgresql://user:pass@host:25060/db?sslmode=require&prepareThreshold=0&connection_timeout=60&connection_limit=1`

**Comment by saurabh-codeword** [comment]
make sure your user is set to inbound user

![output-onlineimagetools](https://user-images.githubusercontent.com/46310779/210346051-28b2122f-7678-40e2-a336-bd9c820231a5.png)

**Comment by frontsideair** [comment]
My current problem is that I've started using the Vercel integration and the generated connection string environment variable doesn't have `?pgbouncer=true`. When I manually add it, `prisma migrate` starts failing with `ERROR: prepared statement "s0" already exists` error.

**Comment by janpio** [comment]
`prisma migrate` does not work with PgBouncer, you should use a direct connection string for that or you will hit this error.

**Comment by frontsideair** [comment]
I had to come up with a way to set the environment variable, such that during build I migrate can run, while at runtime it connects with pgbouncer. I provide a `datasources` parameter to the `PrismaClient` with the database url environment variable and concatenate `?pgbouncer=true` to it.

Note that this may be highly specific to my Vercel+Neon setup with the official integration.

**Comment by janpio** [comment]
We have `directUrl` that overrides the `url` for the CLI commands: https://www.prisma.io/docs/data-platform/data-proxy/prisma-cli-with-data-proxy (This also applies for Pgbouncer, not only Data Proxy - we will have to update that docs page)

**Comment by frontsideair** [comment]
That sounds better, overriding prod values didn’t sit right. I’ll change my approach, thanks for the heads up.

**Comment by itsjavi** [comment]
Prisma Studio UI seems to not use the directUrl, so it has these issues.
