### ISSUE TITLE
unique and relation together on datamodel.prisma

### ISSUE THREAD

**Issue by codingfunwoody** [prisma/prisma#4755]
type Product {
  id: ID! @id
  component: Component @relation(link: INLINE) @unique
}

I deploy successfully but actually it doesn't unique.

### Edit
I am using Prisma 1.3.4 and using mongoDB connector. 
I am sorry about that i misunderstand the problem. Actually it's work for @relation(link: INLINE) @unique together. 
But I encountered the problem is the graphql schema of mutation, The update product mutation doesn't allow me to use unique componentId to filter the product. For example, 

```
mutation {
  updateProduct(
    where: { id: "productId" }
    data: {
      component: {
        update: {
          where: { 
             componentId: "I want tp put componentId here, but schema doesn't allow it. It's appear when i changed to "@unique" without "@relation" "
          }
          data: { 
            component: { connect: { id: "componentId" } 
          }
        }
      }
    }
  ) {
    id
  }
}
```

**Comment by developerk786** [comment]
try using @unique

like this:
`type Product {
  id: ID! @id @unique
}
`

**Comment by codingfunwoody** [comment]
It doesn't same...
for example, 
It doesn't help me delete if i change to @relation(link: cascade).

**Comment by pantharshit00** [comment]
@codingfunwoody 

Can you please tell me which connector you are using and what is your Prisma version?

I am using 1.34.3 with postgres connect and constraint is properly created in the database.

![image](https://user-images.githubusercontent.com/22195362/62158284-bbab2800-b32c-11e9-9ccc-7c23749cb703.png)

**Comment by codingfunwoody** [comment]
@pantharshit00 

I am using Prisma 1.3.4 and using mongoDB connector. 
I am sorry about that i misunderstand the problem. Actually it's work for @relation(link: INLINE) @unique together. 
But I encountered the problem is the graphql schema of mutation, The update product mutation doesn't allow me to use unique componentId to filter the product. For example, 

mutation {
  updateProduct(
    where: { id: "productId" }
    data: {
      component: {
        update: {
          where: { 
             componentId: "**I want put componentId here, but schema doesn't allow it. It's appear when i changed to "@unique" without "@relation" **"
          }
          data: { 
            component: { connect: { id: "componentId" } }
        }
      }
    }
  ) {
    id
}

**Comment by pantharshit00** [comment]
This doesn't sound very intuitive to me as you are trying to update a product using the mutation.

I think you shouldn't be able to filter here. The `component` available in the update input is the one connected the `product`. The best here is to separate out the mutations.
