### ISSUE TITLE
Exported dump does not looks as NDF (Export API)

### ISSUE THREAD

**Issue by ujja** [prisma/prisma#4758]
Hi,

I have exported my prisma DB using export API, but I'am not able to import it using import API.:

```
{  
   "errors":[  
      {  
       "message":"JsResultException(errors:List((/valueType,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/values,List(JsonValidationError(List(error.path.missing),WrappedArray())))))",
         "requestId":"local:cjyifij7l000z0790dg5yt6lt"
      }
   ]
}

```
I suppose the exported data is not an NDF:

```
{
  "out": {
    "jsonElements": [
      {
        "_typeName": "Tag",
        "id": "cjxonc1jl00d507906zc49ep5",
        "createdAt": "2019-07-04T12:28:36.177Z",
        "updatedAt": "2019-07-04T12:28:36.177Z",
        "name": "Demo"
      }
    ],
    "size": 135577
  },
  "cursor": {
    "table": -1,
    "row": -1,
    "field": -1,
    "array": -1
  },
  "isFull": false
}

```

[doc of 1.28](https://www.prisma.io/docs/1.28/prisma-cli-and-configuration/data-import-and-export-jsw9/) says:

> The structure for a JSON document in NDF is an object with the following two keys:
> 
> valueType: Indicates the value type of the data in the document (this can be either "nodes", "lists" or "relations")
> values: Contains the actual data (adhering to the value type) as an array

Do I have to convert it to NDF?

**Comment by pantharshit00** [comment]
Can you please provide us with your datamodel? If possible also provide us with a SQL dump of your database

**Comment by ujja** [comment]
I made the first step of prisma get started (https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-JAVASCRIPT-a002/) So i have a user table with one user.
```
type User {
  id: ID! @unique
  name: String!
}
```

Then made an export using Postman (http://localhost:4466/export, used no project, because there is no project in "get started")

result:
```
{
  "out": {
    "jsonElements": [
      {
        "_typeName": "User",
        "id": "cjylgclbj00030737jl1k4wfg",
        "name": "Alice",
        "updatedAt": "2019-07-27T11:29:28.278Z",
        "createdAt": "2019-07-27T11:29:28.278Z"
      }
    ],
    "size": 146
  },
  "cursor": {
    "table": -1,
    "row": -1,
    "field": -1,
    "array": -1
  },
  "isFull": false
}
```

I created my user and schema using prisma using Prisma CLI 1.28, Prisma Server 1.25.4. Tried server 1.28, and 1.34 too, with same results. (I did not change the schema and the data)

**Comment by pantharshit00** [comment]
`prisma export` command actually converts the data received from that endpoint to the NDF.

I don't think you directly export the data using the endpoint without conversion.

There are also a few other bugs in the export command. So we recommend using native SQL dumps now.

**Comment by ujja** [comment]
We would like to export/import programatically. 

We know that the CLI converts it. Our alternative plan was to externalize the conversion.

We are searching for a long term solution. What is the plan with export/import endpoints? Is NDF support dropped forever?

**Comment by pantharshit00** [comment]
The endpoint will not be dropped but certainly will not be maintained.

I guess you should check out the source code of the CLI to see what it does under the hood.

**Comment by pantharshit00** [comment]
https://github.com/prisma/prisma/blob/b23bc459f2ae1e1bcad4466fbe4903e2dc872a3e/cli/packages/prisma-cli-core/src/commands/export/Exporter.ts

**Comment by ujja** [comment]
thank you!

**Comment by ujja** [comment]
And is it documented what are the bugs with this export/import API?

**Comment by pantharshit00** [comment]
This is one of the main issues. https://github.com/prisma/prisma/issues/4627

It is hard to reproduce so difficult to fix. That is why we are recommending SQL dumps as they are battle tested.

**Comment by ujja** [comment]
Thank you!
