### ISSUE TITLE
can not find project through nginx

### ISSUE THREAD

**Issue by Fled8617** [prisma/prisma#4765]
**Describe the bug**

**To Reproduce**
1. Go to https://www.lsz8617.com/prisma
2. Click on f12

**Expected behavior**
get is ok ,but post will report an error

**Screenshots**
![image](https://user-images.githubusercontent.com/35049517/62009186-fd9e6780-b18e-11e9-871f-0ad76e65d390.png)
nginx conf
![image](https://user-images.githubusercontent.com/35049517/62009191-13139180-b18f-11e9-8d5b-6b2eceb05e2a.png)

**Versions (please complete the following information):**
 - Connector:  `MySQL`
 - Prisma Server: [e.g. `1.24.0`]
 - `prisma` CLI: [e.g. `prisma/1.3.0
 - OS: [e.g. `Windows 10`, `OS X High Sierra`, `Ubuntu 16.04`] 
 - other dependencies: `prisma-client`, `prisma-binding`, etc. if applicable

**Additional context**

**Comment by pantharshit00** [comment]
You will need to add a trailing slash in order strip admin or /prisma_admin to be passed to localhost. Prisma server uses URLs to resolve various projects so you will need to strip /admin.

```nginx
location /prisma {
  proxy_pass http://localhost:4466/;
}

location /prisma_admin {
  proxy_pass http://localhost:4466/_admin/;
}
```

Going to close this as this is more related to nginx than Prisma. Reply if you are unable to find a solution.
