### ISSUE TITLE
npx prisma will use a Prisma server version: 1.32.0-beta

### ISSUE THREAD

**Issue by jjoselv** [prisma/prisma#4769]
**Describe the bug**
When using npx to login, init and deploy (I should have installed it though, I know) it uses the version 1.32.0-beta for the server, and when using the cli after installing it globally, it says this:

Warning: Your Prisma server and Prisma CLI are currently out of sync. They should be on the same minor version.
  
Prisma CLI version: prisma/1.34.3 (darwin-x64) node-v8.11.3
Prisma server version: 1.32.0-beta
  
For further information, please read: http://bit.ly/prisma-cli-server-sync

**To Reproduce**
1. npx prisma login
2. npx prisma init
3. npm i -g prisma
4. npx prisma deploy
5. prisma deploy

**Expected behavior**
To have the same version on npm i -g prisma as on npx prisma (maybe?)

**Screenshots**

**Versions (please complete the following information):**
 - Prisma CLI version: prisma/1.34.3 (darwin-x64) node-v8.11.3
 - Prisma server version: 1.32.0-beta
 - npm: 6.5.0

**Additional context**

**Comment by pantharshit00** [comment]
Unable to reproduce this at all. Can you please try again after cleaning your npm cache(`npm cache clean`).

if you still able to reproduce this, it is a bug in npx not in prisma.

**Comment by theRocket** [comment]
`➜  ~ which prisma
/Users/rjr/.nvm/versions/node/v8.15.1/bin/prisma
➜  ~ nvm use 10.16
Now using node v10.16.0 (npm v6.9.0)
➜  ~ which prisma
/Users/rjr/.nvm/versions/node/v10.16.0/bin/prisma
➜  ~ prisma -v
Prisma CLI version: prisma/1.34.5 (darwin-x64) node-v10.16.0


   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 1.34.0 → 1.34.5   │
   │    Run npm i -g prisma to update     │
   │                                      │
   ╰──────────────────────────────────────╯
`
