### ISSUE TITLE
Introspection removes enums and replaces with DB column type

### ISSUE THREAD

**Issue by robertcoopercode** [prisma/prisma#4770]
## Bug description

When specifying enums as the values on a prisma model, those enums get replaced with a `String` type after running introspection.

Before introspection:

```prisma
model Goal {
  id              Int            @id @default(autoincrement()) @db.Integer
  type            GoalType       @db.Text
  @@map("goals")
}

enum GoalType {
  DEBT
  SAVING
}
```

After introspection:

```prisma
model Goal {
  id              Int            @id @default(autoincrement()) @db.Integer
  type            String         @db.Text
  @@map("goals")
}
```

Here is the `CREATE TABLE` expression for the `goals` table. Take special note that the `type` column is not a PostgreSQL enum, but rather a `text` column with a `CHECK` constraint.

```sql
CREATE TABLE "public"."goals" (
    "id" int4 NOT NULL DEFAULT nextval('goals_id_seq'::regclass),
    "type" text NOT NULL CHECK (type = ANY (ARRAY['DEBT'::text, 'SAVING'::text])),
    CONSTRAINT PRIMARY KEY ("id")
);
```

## Expected behavior

I would expect that if running introspection on a column that is already defined by the prisma schema and the column type is defined by a custom enum (the enum being specified in the prisma schema), that the introspection would not replace the enum type to a `String` type.

## Environment & setup

- Prisma CLI v2.13.0
- Prisma Client v2.13.1
- PostgreSQL v12.2

**Comment by pantharshit00** [comment]
Hey @robertcoopercode 

I can reproduce this but this is expected. The type of text is not an enum but text in the schema with a check constraint. 


Postgres enums generates a new type on the schema: https://www.postgresql.org/docs/9.1/datatype-enum.html. We support introspecting them as enums.

Issue tracking check constraints: https://github.com/prisma/prisma/issues/3388

So I think this is expected and maybe we can even close this if you add your comment in the above mentioned issue.

**Comment by robertcoopercode** [comment]
Fair enough. Perhaps I will migrate over to use native Postgres enums instead of check constraints then. I'll add a comment to #3388 as you suggested.
