### ISSUE TITLE
Ability to use `prisma migrate reset` in non-interactive environments

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#4773]
## Problem

`prisma migrate reset` was designed to be used in interactive environments only.
It seems some users would like to script its execution, i.e. resetting the database when running tests.

## Suggested solution

We limited usage to interactive environments, to protect users from accidentally dropping the wrong database. Perhaps we could include a mechanism that is only triggered if the env is non-interactive where the DB name needs to be passed as an option.

## Additional context

* [Thread in community Slack](https://prisma.slack.com/archives/CBFFY3066/p1608223382077800 )

**Comment by Jolg42** [comment]
We could have something like a `--force` flag to say "yes I am sure I want to reset" instead of the interactive prompts.
