### ISSUE TITLE
Empty objects in `where`-clause make the query return nothing

### ISSUE THREAD

**Issue by PhilippMolitor** [prisma/prisma#4784]
## Bug description

I craft a where-clause for my query by transforming my own filter type from a GraphQL resolver into the Prisma format.
When my filter (which is an array of objects) is only an empty objects, the query returns no results.

## How to reproduce

My code works like this:
```typescript
// I have a model named "Permissions" which i craft the where-clause for
// "filters" is my simple list of custom filter objects

const filter: Prisma.PermissionWhereInput = {
  OR: filters?.map(
    (f): Prisma.PermissionWhereInput => ({
      AND: {
        identifier: filterString(f.identifier),
        timeCreated: filterDateTime(f.timeCreated),
        timeModified: filterDateTime(f.timeModified),
      },
    })
  ),
};

// I apply that filter to my query
const data = await database.permission.findMany({
  // filtering
  where: filter,
});
```

## Expected behavior

The documentation says that queries containing objects with `undefined` as values for their keys are ignored.

When not defining "filters" at all, this is the resulting query filter:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/68352974/103106164-7da25880-4633-11eb-8f62-e7c88e012df5.png">
The query log contains this as the where-clause: `WHERE 1=1`

When defining `filters` as an empty object, this is the resulting query filter:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/68352974/103106212-d4a82d80-4633-11eb-8a17-30cb753bde9a.png">
The query log now contains an always-false where-clause: `WHERE 1=0`,
even though I'd expect it to still filter as if there was no filter at all.

This behavior is also appearing for other models from my PrismaClient.

## Environment & setup

- OS: macOS
- Database: PostgreSQL inside docker
- Node.js version: 15
- Prisma version:
```
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : darwin
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
```

**Comment by pantharshit00** [comment]
Hey @PhilippMolitor 

Can you please try the dev version once? `npm install @prisma/cli -D`. I remember we have recently fixed a similar bug.

**Comment by PhilippMolitor** [comment]
@pantharshit00 I tried it with both packages of version `2.14.0-dev.60` (built 2 days ago according to npm).
This did not alter the behavior in any way.

**Comment by PhilippMolitor** [comment]
The new release did not fix this issue either.

**Comment by matthewmueller** [comment]
Thanks @PhilippMolitor. I can confirm this is unexpected behavior. We should either fix it or update the docs.

```ts
const posts = await prisma.post.findMany({
  where: {
    OR: undefined
  }
})

// returns all posts
console.log(posts)
```

**Comment by PhilippMolitor** [comment]
@matthewmueller Very interesting finding! Indeed it seems like that is the root cause of my issue.

**Comment by matthewmueller** [comment]
Okay, I learned a bit more. Conditionals with no values are ambiguous, OR/AND nothing could mean return everything or it could mean return nothing. I don't think this is worth changing now because people that rely on the current behavior will be very surprised. 

Here are the rules:

| Name |     0 Filter      |        1 Filter        |       2 Filter       |
| :--: | :---------------: | :--------------------: | :------------------: |
|  OR  | return empty list | validate single filter | validate all filters |
| AND  | return all items  | validate single filter | validate all filters |
| NOT  | return all items  | validate single filter | validate all filters |

I've open an issue to document this: https://github.com/prisma/docs/issues/1315
