### ISSUE TITLE
findFirst and findUnique do not return null according to types

### ISSUE THREAD

**Issue by hgezim** [prisma/prisma#4787]
## Bug description

I have a user entity where the `findFirst` and `findUnique` always returns the entity and never null.

## How to reproduce

1. Clone https://github.com/hgezim/prisma-error-find
2. Open `src/user/user.service.ts`
3. `findOrCreate` has return type of `Promise<User>` 
4. TypeScript throw no errors

## Expected behavior

TypeScript should throw an error since the function returns the results of `userOne()` or `userUnique()` which both
can have no results. However, that's not what the prisma client types say:

![CleanShot 2020-12-25 at 16 28 37](https://user-images.githubusercontent.com/124675/103143224-08846100-46cf-11eb-85ee-2a39e1a364e5.png)
![CleanShot 2020-12-25 at 16 28 25](https://user-images.githubusercontent.com/124675/103143226-0b7f5180-46cf-11eb-8e7d-79c319609900.png)

## Prisma information

```
async findOrCreate(data: Prisma.UserCreateInput): Promise<User> {
    const userUnique = await this.prisma.user.findUnique({
      where: { facebookId: data.facebookId },
    });

    const userOne = await this.prisma.user.findFirst({
      where: { facebookId: data.facebookId },
    });

    return userUnique || userOne;
  }
```

## Environment & setup

- OS: Mac OS 
- Database: SQLite 
- Node.js version: v12.20.0 
- Prisma version:

```
@prisma/cli@2.13.1
@prisma/client@2.13.1
```

**Comment by oceandrama** [comment]
You should set `strict: true` in your `tsconfig.json`

**Comment by pantharshit00** [comment]
Indeed, nice catch by @oceandrama 

Either enable `strictNullChecks` or `strict` (which implicitly enables `strictNullChecks` and other good TS options). Then you will get a TS error like so:
![image](https://user-images.githubusercontent.com/22195362/103206523-1e3d9480-4922-11eb-88df-c26046982d00.png)
