### ISSUE TITLE
Environmental variables conflict

### ISSUE THREAD

**Issue by pearwb1235** [prisma/prisma#4789]
I'm Taiwanese, and I am not good at English.

## Bug description

use "port" env

**FreePort & EnvPort conflict**
https://github.com/prisma/prisma/blob/master/src/packages/engine-core/src/NodeEngine.ts#L648

## How to reproduce

1. Clone https://github.com/pearwb1235/PrismaIssue4789.git
2. CMD Command: `npm i`
3. Set "DATABASE_URL" env
4. CMD Command: `npx prisma migrate dev --preview-feature`
5. CMD Command: `npm start`

## Expected behavior

I use "port" env to setting http port.

----------

Change env name "port" to "PORT" resolve this bug.

**Comment by pantharshit00** [comment]
Hey @pearwb1235 


I checked your example and failed to understand what sort of conflict you are running into. The Prisma Engines spawns a Unix Domain Socket by default and it is not an open port but it is accessed via file in the `/tmp` directory as seen in this screenshot of your example.

![image](https://user-images.githubusercontent.com/22195362/103414750-4852b900-4ba5-11eb-9524-670754004f75.png)


We used to use simple TCP port before 2.13 release. If this is about that then, please share a screenshot which shows the conflict as I also tried that and it doesn't seem to conflict.

**Comment by pearwb1235** [comment]
I retry reproduce.

I use VSCode terminal can reproduce error.

![image](https://user-images.githubusercontent.com/46672356/103513651-fad89380-4ea5-11eb-8455-bcf581f96be5.png)

```
PS D:\Documents\NodeJS\PrismaIssue4789> npm start

> prismaissue@1.0.0 start D:\Documents\NodeJS\PrismaIssue4789
> node index.js

prisma:info  Starting a mysql pool with 9 connections.
prisma:info  Started http server on http://127.0.0.1:12345
(node:10712) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.user.findFirst()` invocation:


  Started http server on http://127.0.0.1:12345

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma-client-js/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v14.15.1+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+windows++++++++++++%7C%0A%7C+Prisma+Client+++%7C+2.13.1+++++++++++++%7C%0A%0A%23+Description%0A%60%60%60%0AsignalCode%3A+null+%7C+exitCode%3A+null+%7C+killed%3A+false%0AError%3A+connect+ECONNREFUSED+127.0.0.1%3A5274%0A++++at+TCPConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28net.js%3A1146%3A16%29%0AExit+code%3A+undefined%0AStarted+http+server+on+http%3A%2F%2F127.0.0.1%3A12345%0A%60%60%60%0A%0A%23%23+Logs%0A%60%60%60%0A++prisma-client+%7B+clientVersion%3A+%272.13.1%27+%7D++%0A%60%60%60&title=Started+http+server+on+http%3A%2F%2F127.0.0.1%3A12345&template=bug_report.md

If you want the Prisma team to look into it, please open the link above �🙏

    at PrismaClientFetcher.request (D:\Documents\NodeJS\PrismaIssue4789\node_modules\@prisma\client\runtime\index.js:78125:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10712) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:10712) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

But Windows PowerShell couldn't.

![image](https://user-images.githubusercontent.com/46672356/103513935-91a55000-4ea6-11eb-8284-891a03dc8898.png)

**Comment by pantharshit00** [comment]
Thanks for the additional details I can reproduce this on my windows machine but not on my mac so this is windows specific. 

Reproduction steps are pretty accurate so I feel this is actionable now. Thanks for reporting. 

![image](https://user-images.githubusercontent.com/22195362/104326255-8a69ec00-550f-11eb-8419-2b97cd064d95.png)
