### ISSUE TITLE
Query Postgres Table with UUID as ID raises error

### ISSUE THREAD

**Issue by yim77** [prisma/prisma#479]
If I try to query a row from a postgres table with a id of type UUID prisma raises an error.

**Postgres version:** PostgreSQL 11.1 (Debian 11.1-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

**Prisma2 version:** 2.0.0-alpha.159

**DB Script:**
```sql
CREATE TABLE public."User"
(
    age integer,
    name text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    id uuid NOT NULL DEFAULT uuid_generate_v1(),
    CONSTRAINT id PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."User"
    OWNER to postgres;
```

**Schema**:
```gql
model User {
id   String @default(uuid()) @id
age  Int?
name String
post Post[]
}
```

**Code:**
```javascript
const MyFunc = async function() {
  const MyUser = await photon.users.findOne({where: {id: "936958ea-cb04-11e9-bcba-0242ac110002"},});
  console.log(MyUser);
}

MyFunc()
```

**Error:** Reason: Error in connector: Error querying the database: error serializing parameter 0: cannot convert to or from a Postgres value of type `uuid`

Queries on same table with findMany() is working perfect.

**Comment by pantharshit00** [comment]
I can confirm this. 

Also, the thing to note that when I use lift to bootstrap this, it created the column as `text` for uuid.

**Comment by pantharshit00** [comment]
Created an issue in the lift repository for the related issue: https://github.com/prisma/lift/issues/114

**Comment by benjamincanac** [comment]
Any update on this? I encounter the same problem.

Thanks!

**Comment by divyenduz** [comment]
Internal note: link this to custom type EPIC issue, dropping from this sprint

**Comment by pantharshit00** [comment]
I believe fix for this was released a long time ago, please comment if someone is still experiencing this.

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/103486930-6f202200-4e27-11eb-978b-213e2b9ccd40.png)


Confirmed as well :)
