### ISSUE TITLE
Array relation unpack error

### ISSUE THREAD

**Issue by pearwb1235** [prisma/prisma#4791]
## Bug description

A --> B     One To Many

use `await client.A().B().A()` will return undefined

**unpack description**
https://github.com/prisma/prisma/blob/master/src/packages/client/src/runtime/getPrismaClient.ts#L1434

**client.A().B()**   ->  **B: [{...}, {...}, {...}, ...]**       -(unpack)->  **B: [{...}, {...}, {...}, ...]**
`select B` -> `B`

**client.A().B().A()**  ->  **B: [{A: {...}}, {A: {...}}, {A: {...}}, ...]**  -(unpack)->  **undefined**
`select B select A` -> `B A`

## Environment & setup

- OS: Windows10
- Database: MySQL
- Node.js version: v14.15.1
- Prisma version: v2.13.1

**Comment by timsuchanek** [comment]
Thanks for reporting @pearwb1235!
This is how I understand your issue:
You have a 1:n relation between A and B. In my example A is `User`, B is `Post`:
```prisma
model Post {
  id        Int      @default(autoincrement()) @id
  createdAt DateTime @default(now())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model User {
  id      Int      @default(autoincrement()) @id
  email   String   @unique
  name    String?
  posts   Post[]
}
```

This is possible:
```ts
  const data = await prisma.user
    .findUnique({
      where: {
        email: '',
      },
    })
    .posts()
```

This isn't possible with the current TypeScript types:
```ts
  const data = await prisma.user
    .findUnique({
      where: {
        email: '',
      },
    })
    .posts()
    .user()
```

Are you doing this in pure JavaScript?
Optimally you could share your schema and query 🙏

**Comment by pearwb1235** [comment]
Use your example.
I print `prisma.user.findFirst().posts()` saw user property.
**I don't notice the doc not has user property.**

If `prisma.user.findFirst().posts().user()` isn't possible with the current version, I don't have any other questions.
Thanks for your reply.

**Comment by pantharshit00** [comment]
Indeed `prisma.user.findFirst().posts().user()` is not possible as you can't use fluent chain api with lists. Use `select` or `include` here. https://www.prisma.io/docs/concepts/components/prisma-client/field-selection#select
