### ISSUE TITLE
"TypeError: Cannot read property 'datasources' of undefined" after command "prisma db reset"

### ISSUE THREAD

**Issue by etiennekintzler** [prisma/prisma#4792]
Using prisma client 2.13.1 the issue https://github.com/prisma/migrate/issues/653 remains.

The issue was (see link for more details) :
```sh
$ yarn blitz db reset 
yarn run v1.22.5
$ /PATH_TO_MY_APP/node_modules/.bin/blitz db reset
You are using alpha software - if you have any problems, please open an issue here:
    https://github.com/blitz-js/blitz/issues/new/choose

✔ Loading your database
✔ Are you sure you want to reset your database and erase ALL data? (y/N) · true
  tryLoadEnv Environment variables loaded from /PATH_TO_MY_APP/.env +0ms
  tryLoadEnv Environment variables loaded from /PATH_TO_MY_APP/.env +2ms
  prisma-client { clientVersion: '2.13.1' } +0ms
    TypeError: Cannot read property 'datasources' of undefined
Done in 4.54s.

```

My new env:

 ```sh
$ ./node_modules/.bin/prisma -v
Environment variables loaded from .env
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.329.0
Done in 1.94s.

$ node -v
v14.15.3
```

**Comment by pantharshit00** [comment]
Hey @etiennekintzler 

Can you please provide a minimal reproduction for this? Looks like you are using Prisma via blitz so please share a reproduction so that we can also verify that isn't an issue with blitz implementation. Thanks!

Most like I still think you are using older version here. So please make sure you have `_prisma_Migration` table in your database.

**Comment by Jolg42** [comment]
It sounds like the datasource block is missing in the schema, it would be useful if you could share the contents of the `schema.prisma` file here

**Comment by etiennekintzler** [comment]
Hey @Jolg42 

> It sounds like the datasource block is missing in the schema, it would be useful if you could share the contents of the `schema.prisma` file here

- The schema I used is in the link I provided (in the original issue) : https://github.com/prisma/migrate/issues/653 . The header of the schema is :

```javascript
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

the variable `"DATABASE_URL"` is well defined in `.env`.

- I try `datasources` instead of `datasource` but the result is the same.

**Comment by Jolg42** [comment]
It looks like the problem is from Blitz's implementation here https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts#L261-L301

It's using some parts of Prisma that are undocumented / reserved for internal use and something is probably not working as expected.

I think this issue needs to be opened in Blitz's repo https://github.com/blitz-js/blitz/issues/new/choose

**Comment by etiennekintzler** [comment]
> It looks like the problem is from Blitz's implementation here https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts#L261-L301

Yes you're right. 

I should have check on blitz before posting the issue here. Actually the issue has been adressed https://github.com/blitz-js/blitz/issues/938 (didn't find it through google though).

I am closing the issue here. Thanks for your help 👍

**Comment by Jolg42** [comment]
Nice! 👍
