### ISSUE TITLE
relation for borth friend

### ISSUE THREAD

**Issue by CGerAJ** [prisma/prisma#4801]
## Bug description
```
firend table has two userid

```

## How to reproduce

 Run 'export DEBUG="*" &&  npx prisma migrate dev --preview-feature'
See error

## Expected behavior

```
Error: Error: Database error: Error querying the database: Server error: `ERROR HY000 (1822): Failed to add the foreign key constraint. Missing index for constraint 'friends_ibfk_1' in the referenced table 'Users''
   0: migration_core::api::ApplyMigrations
             at migration-engine/core/src/api.rs:102
```

## Prisma information

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema
```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Users {
  id        Int       @id @default(autoincrement())
  name      String
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  Friends   Friends[]
}

model Friends {
  id           Int      @id @default(autoincrement())
  userId       Int
  friendUserId Int
  Users        Users    @relation(fields: [userId, friendUserId], references: [id, id])
  status       Boolean  @default(true)
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}
```

## Environment & setup

- OS: `macOS 10.15.7`
- Database: `MySQL`
- Node.js version: `v14.0.0`
- Prisma version:

`@prisma/cli          : 2.13.0`
`@prisma/client       : 2.13.0`

`@prisma/cli          : 2.13.1`
`@prisma/client       : 2.13.1`

```

```

**Comment by pantharshit00** [comment]
Hey @CGerAJ 


I am not sure what you are trying to refer here in the model. On a database level, you can't refer set it like that without a composite id on the User table. 

If you want two sets of user, you can do something like this:
```prisma
model Users {
  id                Int       @id @default(autoincrement())
  name              String
  createdAt         DateTime  @default(now())
  updatedAt         DateTime  @updatedAt
  userFriends       Friends[] @relation(name: "users")
  friendUserFriends Friends[] @relation(name: "friend_users")
}

model Friends {
  id           Int      @id @default(autoincrement())
  userId       Int
  friendUserId Int
  Users        Users    @relation(name: "users", fields: [userId], references: [id])
  FriendUsers  Users    @relation(name: "friend_users", fields: [friendUserId], references: [id])
  status       Boolean  @default(true)
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt

  @@unique([userId, friendUserId])
}

```

**Comment by CGerAJ** [comment]
ID | user_id | friend_id
-- | -- | --
1 | 1 | 2
2 | 1 | 3
3 | 2 | 3

User 1 has user 2 friends
User 1 has user 3 friends
User 2 has user 3 friends

user 1 friend is user 2 and user3
User 2's friend is user 3 and user 1
User 3's friend is user 1 and user 2

like this， can i do it, tks～

**Comment by pantharshit00** [comment]
The following model creates the required tables:
```prisma
model Users {
  id                Int       @id @default(autoincrement())
  name              String
  createdAt         DateTime  @default(now())
  updatedAt         DateTime  @updatedAt
  userFriends       Friends[] @relation(name: "users")
  friendUserFriends Friends[] @relation(name: "friend_users")
}

model Friends {
  id        Int      @id @default(autoincrement())
  user_id   Int
  friend_id Int
  user      Users    @relation(name: "users", fields: [user_id], references: [id])
  friend    Users    @relation(name: "friend_users", fields: [friend_id], references: [id])
  status    Boolean  @default(true)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@unique([user_id, friend_id])
}
```

You can also introspect(https://www.prisma.io/docs/concepts/components/introspection) the database if you are more comfortable in writing the schema in sql first.

**Comment by CGerAJ** [comment]
Solved the problem, TKS

**Comment by detronetdip** [comment]
Can anyone tell me how to query the friends table to get the friends details from the user table based on friends id from the friends table?

**Comment by janpio** [comment]
Probably not - close issues do not get any attention. Optimally open a new discussion and include your schema you are asking about.

**Comment by detronetdip** [comment]
@janpio ok
