### ISSUE TITLE
Prisma Migrate cannot reset the database when the user has insufficient privileges - this makes Prisma Migrate incompatible with some hosted cloud providers

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#4803]
## Problem

This is the current error message
```
Error: Database error: Error querying the database: db error: ERROR: must be owner of schema public
   0: migration_core::api::Reset
             at migration-engine/core/src/api.rs:232
```

## Suggested solution

- We could make it a "known error"
- Improve the text, suggestion: `The database's user privileges are insufficient, the user must be owner of the "public" schema`

## Additional context

The current error `must be owner of schema public` is not super helpful if you don’t know it’s about the user privileges and that the schema name is `public`.

So we could improve the message to make it clear to the users what the problem is.

In this case the solution is to grant the "owner" privileges to the db user.

**Comment by talentlessguy** [comment]
"In this case the solution is to grant the "owner" privileges to the db user."

could you please show how to do it? I'm not sure if making the db user `postgres` a superuser is a good idea

**Comment by do4gr** [comment]
We can turn this into a nicer error with a comment how to fix this.

**Comment by nikolasburk** [comment]
We might also want to consider pointing people low-key to `prisma db push` in that case. I suspect that many people will be running into this when they're just exploring/prototyping so they don't _really_ care about migrations. So maybe adding a sentence at the end of the error message like: 

```
If you are just prototyping and don't need to generate migration files, you can run the following command to update your schema:
npx prisma db push

Learn more: <LINK_TO_DOCS>
```

**Comment by maoosi** [comment]
To add to the discussion, I just ran into that particular issue trying to run: `npx prisma migrate dev --preview-feature` (using Prisma 2.13.1).

I am using a PostgreSQL managed database on DigitalOcean and from what I could find so far, it doesn’t seem possible to set owner privileges on the public schema when using managed database services like DigitalOcean.

The suggested command `ALTER USER user_name CREATEDB CREATEROLE LOGIN;` is also blocked as it requires superuser privileges.

**Comment by albertoperdomo** [comment]
Note to add this to documentation too.

**Comment by maoosi** [comment]
I would have hopped about a way to make migrate work across more providers instead, by potentially changing the way it is trying to reset the database in PostgreSQL. 

For example, the below works on Digital Ocean without the need for too much privileges:

```sql
-- Drop All Tables (Prisma models)
DO $$
DECLARE tablenames text;
BEGIN    
    tablenames := string_agg('"' || tablename || '"', ', ') 
        FROM pg_tables WHERE schemaname = 'public';
    EXECUTE 'DROP TABLE ' || tablenames;
END; $$;

-- Drop All Types (Prisma enums)
DO $$
DECLARE typenames text;
BEGIN    
    typenames := string_agg('"' || typname || '"', ', ') 
        FROM pg_type JOIN pg_enum ON pg_enum.enumtypid = pg_type.oid;
    EXECUTE 'DROP TYPE ' || typenames;
END; $$;
```

Any thoughts?

**Comment by Jolg42** [comment]
@maoosi Thanks for the suggestion, actually I think error happens because of the required shadow database & rights needed for it for `prisma migrate reset` https://www.prisma.io/docs/concepts/components/prisma-migrate#shadow-database

**Comment by Jolg42** [comment]
We need to check what we can do for cases like Digital Ocean

**Comment by BjoernRave** [comment]
@maoosi With this approach the schema get's deleted as well, right? How do you go about restoring that?

**Comment by albertoperdomo** [comment]
We could perhaps fallback to truncating the database if dropping the schema fails. This is quite complex though and there are chances we leave something behind (e.g. stored procedures, extensions, etc.). We should always attempt dropping the schema first if possible as it's the cleanest solution.

**Comment by albertoperdomo** [comment]
This feature is now live in 2.17.0 - https://github.com/prisma/prisma/releases/tag/2.17.0

For feedback, please post on https://github.com/prisma/prisma/issues/4531.
