### ISSUE TITLE
"prisma init" vs. "graphql create"

### ISSUE THREAD

**Issue by walame** [prisma/prisma#4807]
In some video tutorials around the web, I saw that previous versions of `prisma init` had the ability to generate a boilerplate (basic, advance with auth, etc). Now, the documentation says to use `graphql create` instead. 

**My question**: does `graphql create` replace `prisma init`, in that it will bootstrap a full prisma server? Or do I still need to run `prisma init` after `graphql create`

I am confused at to why the feature was removed... based on the tutorials I saw, it was so incredibly easy to start on prisma with this feature!

**Comment by pantharshit00** [comment]
GraphQL cli was used to quickly create a boilerplate before the Prisma Client was introduced.

You can still use it bootstrap a development project, but the boilerplates are very outdated right now. Fortunately, the guild has taken over the maintenance of the graphql-cli so I expect that the boilerplates might get updated soon(https://www.prisma.io/blog/the-guild-takes-over-oss-libraries-vvluy2i4uevs)

So, what I will recommend you is if you want to bootstrap a Prisma 1 project right now, please use the prisma cli. It will get you set up with a project using the Prisma Client. GraphQL CLI is fairly out of date in the current form.
