### ISSUE TITLE
Inconsistent DMMF for relation lists

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma#4808]
## Bug description

The return type from prisma client is not-nullable:

![image](https://user-images.githubusercontent.com/10618781/103269644-8b026e80-49b6-11eb-859d-167884690441.png)

But the one-to-many relations (lists) in Prisma DMMF are marked as optional:

![image](https://user-images.githubusercontent.com/10618781/103269656-8fc72280-49b6-11eb-90d5-2c9f0a266abd.png)

Which is inconsistent comparing to other fields definitions.

## How to reproduce

Create a prisma schema with one-to-many relation.

## Expected behavior

The relation field list type should be non-nullable, as it returns empty array if no relation.

## Prisma information

```prisma
model User {
  posts  post[]  @relation("posts")
}
```

## Environment & setup

- OS:  Ubuntu 20.04
- Database:  MySQL
- Node.js version:  `v15.3.0`
- Prisma version:

```
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.329.0
Done in 3.81s.
```

**Comment by pantharshit00** [comment]
Looks like lists are marked is "isRequired": false in dmmf at every place. I think this is false as engine always returns `[]` for empty lists.
