### ISSUE TITLE
Can not import INLINE relation (from data export)

### ISSUE THREAD

**Issue by littleguppies** [prisma/prisma#4808]
**Describe the bug**
i have this model
```graphql
type User {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  handle: String! @unique
  name: String
  tweets: [Tweet!]!
}

type Tweet {
  id: ID! @id
  createdAt: DateTime! @createdAt
  text: String!
  owner: User!
  location: Location!
}

type Location {
  id: ID! @id
  latitude: Float!
  longitude: Float!
}
```
when i run export data then import data into new database relation between **Tweet->location is null.**
![image](https://user-images.githubusercontent.com/22710371/63044830-45e0b800-bef9-11e9-9a74-6e42540aec20.png)

But when i modify something like this
```graphql
type User {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  handle: String! @unique
  name: String
  tweets: [Tweet!]!
}

type Tweet {
  id: ID! @id
  createdAt: DateTime! @createdAt
  text: String!
  owner: User!
  location: Location! @relation(name: "TweetHasLocation", link: TABLE)
}

type Location {
  id: ID! @id
  latitude: Float!
  longitude: Float!
}
```
This working
Can anyone explain to me. what happen is going on here.
Say Thanks.

**Comment by divyenduz** [comment]
@littlemonster00 Can you please share a small reproduction? Which database are you using?

**Comment by littlemonster00** [comment]
@divyenduz  This is my test model for export data in prisma, it's real. i'm using postgresql for my db

**Comment by pantharshit00** [comment]
Can you please tell me whether your data was exported when you were using datamodel v1?

I am assuming that the relation name got changed hence the relations in the exported data are no longer being picked up.

Try the following datamodel once:
```graphql
type User {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  handle: String! @unique
  name: String
  tweets: [Tweet!]!
}

type Tweet {
  id: ID! @id
  createdAt: DateTime! @createdAt
  text: String!
  owner: User!
  location: Location! @relation(name: "TweetHasLocation", link: INLINE)
}

type Location {
  id: ID! @id
  latitude: Float!
  longitude: Float!
}

```

That way the relation will be named and the import tool might pick it up.
