### ISSUE TITLE
Prometheus / metrics endpoint down causing Prisma instance to crash

### ISSUE THREAD

**Issue by timchambers** [prisma/prisma#4813]
**Describe the bug**

I have a Prisma 1.34.5 instance deployed on Fargate, and beginning last night, it's been responding with internal server errors after a short period of time. If I manually restart the instance, it works again for a while before failing again.

Looking at the logs, I'm seeing a lot of these recently, where it looks like a metrics endpoint that Prisma posts to is returning a 502 error, and when that happens a few times in a row, the instance stops working:
```
Push to Prometheus Gateway failed with:
com.prisma.akkautil.http.FailedResponseCodeError: Server responded with 502
akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [metrics-eu1.prisma.io:443], no bytes passed in the last 30 seconds
```

Can I disable these Prometheus pings until the endpoint is working again? Are there any other workarounds?

**To Reproduce**
I haven't isolated repro steps yet, but I think this may be caused by the metrics endpoint responding with a 502 error

**Expected behavior**
I expect my Prisma server will not run crash if the 3rd party metrics endpoint goes down

**Versions (please complete the following information):**
 - Connector: `MySQL`
 - Prisma Server: `1.34.5`
 - `prisma` CLI: `prisma/1.34.5 (darwin-x64) node-v12.8.0`
 - OS: `OS X High Sierra`

**Additional context**
Hosting on AWS Fargate, one task/service running, connecting to AWS Aurora Serverless MySQL

**Comment by pantharshit00** [comment]
This has been fixed.
