### ISSUE TITLE
Update error message for prisma client bindings when top level field is not supplied

### ISSUE THREAD

**Issue by nicovalencia** [prisma/prisma#4814]
**Is your feature request related to a problem? Please describe.**
When calling an update method using prisma client bindings, if no where clause is supplied, the error message states there is a missing [whichever field is first]. This leads the developer to think they aren't supplying that field on the actual update/data object, rather than forgetting to select a record with the where field.

**Describe the solution you'd like**
I'm thinking it would be helpful to have an error like `where field missing on updateUser call` when the entire where attribute is not supplied by mistake.

**Describe alternatives you've considered**
Alternatives: probably just not making the mistake. It's not a huge deal, just something to make potential mistakes easier to fix. Perhaps something globally that errors on specifically which top level field `where`/`data`/etc. is missing.

**Additional context**
I'd love to add this in a few weeks when I have some open time, just can't get to it at the moment.

**Comment by pantharshit00** [comment]
Can you please provide an example of this?

Right now we are not taking any new feature requests for Prisma 1 but we can surely implement this feedback in Prisma 2(https://github.com/prisma/prisma2) if applicable.

**Comment by nicovalencia** [comment]
Ah good point, all the error bindings are probably different in Prisma 2. I'll check to see if this is applicable, and update on v2 when I get around to it. Thanks @pantharshit00
