### ISSUE TITLE
prisma deploy is really slow, event apply changes or apply nothing

### ISSUE THREAD

**Issue by hiepxanh** [prisma/prisma#4815]
**Describe the bug**
As I describe, I clone new but it very slow

**To Reproduce**
1. clone `git clone git@github.com:prisma/prisma-examples.git`
2. `cd prisma-examples/node/docker-postgres && npm i`
3. `docker-compose up -d`
4. `prisma deploy`

**Expected behavior**
It should take 1s to deploy
**Screenshots**
The problem:
![image](https://user-images.githubusercontent.com/16970990/63214271-5df64880-c140-11e9-8756-3ae1d3313af6.png)
it should be fast like this: 
![image](https://user-images.githubusercontent.com/16970990/63214277-72d2dc00-c140-11e9-9d3f-829a14e405ca.png)
![image](https://user-images.githubusercontent.com/16970990/63214299-cc3b0b00-c140-11e9-8eef-4a3699f64992.png)
![image](https://user-images.githubusercontent.com/16970990/63214303-d2c98280-c140-11e9-94a2-18a9de24bfe7.png)
![image](https://user-images.githubusercontent.com/16970990/63214304-d6f5a000-c140-11e9-8f59-f81fee27f459.png)
![image](https://user-images.githubusercontent.com/16970990/63214309-e07f0800-c140-11e9-8304-c3e0fd1a252e.png)
relate link: [udemy issue 1](https://www.udemy.com/graphql-bootcamp/learn/lecture/11838298#questions/7688098)
[udemy issue 2](https://www.udemy.com/graphql-bootcamp/learn/lecture/11838298#questions/7169924)
[udemy issue 3](https://www.udemy.com/graphql-bootcamp/learn/lecture/11838298#questions/6972556)
**Versions (please complete the following information):**
 - Connector:Postgres
 - Prisma Server: `1.34.5`
 - prisma: `prisma/1.34.5 (windows-x64) node-v10.16.2`
 - OS: `Windows 10`

**Additional context**
- it could not be my computer hardware: I have `32gb ram` and `ryzen 5 1600`
- it could not be the network
- it could be docker problem
- it could be prisma problem

**Comment by pantharshit00** [comment]
@hiepxanh 

Are you using a database that is inside the docker VM or you are using an external database?


Deploy time depends on the latency to the database and the amount of data in the database. Let me know which database you are using and where it is hosted and how much data it has.

**Comment by hiepxanh** [comment]
I'm using `Docker for desktop` and database is pulling from heroku inside a docker. I don't know why, because I use the same database that deployed to the host server is event faster than this one running locally on `window desktop`. The next monday, I will try to use test on the Mac to the anything different. Maybe I can guest the problem to describe to you. And saving other window user :D

**Comment by AbdusamadTurdiev** [comment]
I have the same problem on windows 10 and postgres db deployed to heroku
![image](https://user-images.githubusercontent.com/33511684/64937362-69d64700-d873-11e9-9af3-66cfb2c7e126.png)

**Comment by adrianoresende** [comment]
+1
