### ISSUE TITLE
Introspection crash when relation name is only used on one side. 

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#4822]
<img width="997" alt="Bildschirmfoto 2020-12-30 um 12 14 29" src="https://user-images.githubusercontent.com/16278407/103347923-b9f11100-4a98-11eb-9d6d-ef62c9ba8af7.png">

The handwritten schema is detected as valid by the schema validation in VS Code, but crashes later. Trigger is the usage of the optional relation name on one side but not the other. 

We successfully received the error report id: 12442

**Comment by albertoperdomo** [comment]
Related to https://github.com/prisma/prisma-engines/issues/1537

**Comment by do4gr** [comment]
This should be solved by us splitting the parsing and formatting step here https://github.com/prisma/prisma-engines/pull/1662
