### ISSUE TITLE
Use pgtyped to handle raw queries

### ISSUE THREAD

**Issue by Newbie012** [prisma/prisma#4829]
## Problem

Since Prisma can't guarantee type safety for raw SQL queries, I decided to use [pgtyped](https://pgtyped.now.sh/) for the raw queries, while using Prisma for the other queries.

In order to run a query, I need to create a new pg client, connect to it, run the query and then close the connection:

```ts
// taken from https://pgtyped.now.sh/docs/sql-file-intro
async function main() {
  await client.connect();
  const books = await findBookById.run(
    {
      bookId: 42,
    },
    client,
  );
  console.log(`Book name: ${books[0].name}`);
  await client.end();
}
```

The thing is, since Prisma has already created a new client, I get the following error in runtime:

```
Error: sorry, too many clients already

at Parser.parseErrorMessage (../node_modules/pg-protocol/src/parser.ts:357:11)
```

## Suggested solution

Expose pg client outside.

## Alternatives

Set the maximum connections to be fixed

## Additional context

https://github.com/prisma/prisma/issues/3991 Possible related

**Comment by Xetera** [comment]
The connection limit issue is coming from postgres, not prisma, so that's not really a limit they can increase. I imagine you can create a connection pool to handle just pgTypes queries although it's weird that you'd get an error like that with 2 connected clients in the first place.

I'm not sure if Prisma would be able to expose the client safely since the entire point is to be an abstraction over multiple database drivers.

**Comment by Newbie012** [comment]
@Xetera regarding the error, you're right. It doesn't make sense and apparently, it happened because I didn't end the connections on failed tests.

About exposing the client, I understand the whole idea of abstraction and the motives, but by not exposing it, we're fully dependent on Prisma's API which still missing crucial operations. I will fully understand even if they will expose it as `prisma.__unsafeConnection.client` or something that will make all of the engines happy.

In any case, I'm closing this issue since it's solved.
