### ISSUE TITLE
How can I replicate ID generation

### ISSUE THREAD

**Issue by KennethGomez** [prisma/prisma#4839]
Hey

I have a HTTP API built in node with prisma and a game server in Java.
This server is connected with the database directly, so my question is:

How can I replicate the prisma ID generation to insert new data into database directly from the Server? Is there any function on the source code to convert it to Java code?

**Comment by pantharshit00** [comment]
We use CUID of ID creation.

You can find the java library for cuid here: https://github.com/prisma/cuid-java

If you want a nodejs cuid library, you can find there here: https://github.com/ericelliott/cuid
