### ISSUE TITLE
DATABASE_URL not working

### ISSUE THREAD

**Issue by calidion** [prisma/prisma#4844]
## Bug description

DATABASE_URL not working

```
Error: Error in datamodel: Diagnostics { errors: [EnvironmentFunctionalEvaluationError { var_name: "DATABASE_URL", span: Span { start: 160, end: 179 } }], warnings: [] }
```

## How to reproduce

1.  define DATABASE_URL inside `.env`
export DATABASE_URL="mysql://user:password@localhost:3306/db"

2. run 
```
npx prisma introspect
```

## Expected behavior

run successfully

## Prisma information

when not `export` in `.env`
```
Error: Error in datamodel: Diagnostics { errors: [SourceValidationError { message: "The URL for datasource `db` must start with the protocol `postgresql://`.", datasource: "db", span: Span { start: 160, end: 179 } }], warnings: [] }
```

when add `export` in `.env`

```
Error: Error in datamodel: Diagnostics { errors: [EnvironmentFunctionalEvaluationError { var_name: "DATABASE_URL", span: Span { start: 160, end: 179 } }], warnings: [] }

```
## Environment & setup

- OS:   Ubuntu 20.04
- Database:   Mysql
- Node.js version:   v14.4.0
- Prisma version:

```
@prisma/cli          : 2.13.1
@prisma/client       : Not found
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.329.0

```

**Comment by pantharshit00** [comment]
@calidion 

This is expected. The first case without the export is throwing error because you are providing a `mysql` url while the schema likely has `postgresql` set as the database provider.

Secondly `export` is not the correct format. We use https://github.com/motdotla/dotenv to parse the env files and the correct format is `NAME=VALUE`. So please double check here. If you can still reproduce this, maybe share a tiny git repository with a reproduction.

**Comment by calidion** [comment]
thanks.  it works now.
