### ISSUE TITLE
Add --non-interactive to @prisma/migrate

### ISSUE THREAD

**Issue by Newbie012** [prisma/prisma#4845]
## Problem

I have a script that seeds the database with fake data. But before it does, it first checks that I'm not running this in production env/DB (😅) and after that, It tries to run `prisma migrate reset --preview-feature` like so:

```ts
const prismaBinary = join(__dirname, "..", "node_modules", ".bin", "prisma");

execSync(`${prismaBinary} migrate reset --preview-feature`, {
  env: {
    ...process.env,
    DATABASE_URL: config.DATABASE_URL,
  },
});
```

The thing is, when it tries to run it, I get the following error:

```
Error: We detected that your environment is non-interactive. Running this command is not supported in this context.
Error: Command failed: /home/eliya/projects/screendow/packages/server/node_modules/.bin/prisma migrate reset --preview-feature
```

## Suggested solution

Add a flag `--non-interactive` or `--force`

## Alternatives

run the reset manually and only then run the seed script

## Additional context

None

**Comment by albertoperdomo** [comment]
This will be addressed in #4773. Closing as duplicate.
