### ISSUE TITLE
Hide datamodel field in graphql schema

### ISSUE THREAD

**Issue by jpvanoosten** [prisma/prisma#4847]
**Is your feature request related to a problem? Please describe.**
Prevent a field from being returned in a graphql query.

Is there a way to prevent the `password` field of a user record from being returned in a graphql query?

For example, in the datamodel.prisma file:
```
type User {
  id: ID! @id
  name: String!
  email: String! @unique
  password: String!
}
```
Is there any way to tell the generator not to expose the `password` field in the graphql schema?
I don't want the password to be exposed in the Query.user or Query.users (or any generated type that could expose the `password` field.

**Describe the solution you'd like**
The ability to hide fields from the graphql query schemas.

**Describe alternatives you've considered**
I've tried adding the `@password`, `@private` directives to the `password` field, but these have no effect on the resulting graphql schema.

**Comment by pantharshit00** [comment]
This is much simpler to achieve if you use nexus-prisma using the `t.prismaField` method.

See https://nexus.js.org/docs/database-access-with-prisma#5-hide-fields-of-a-model

**Comment by jpvanoosten** [comment]
Thanks @pantharshit00.

I'm pretty new to graphql and prisma. 

I looked into nexus-prisma but I've solved this by making a resolver on the password field to always return an empty string. I'm not sure if this handles all cases or if it has other side-effects that I'm not thinking of right now.

I'll look further at nexus-prisma if this is a better method of solving this issue.
