### ISSUE TITLE
Annotated relation field doesn't appear to be required for 1-n relations

### ISSUE THREAD

**Issue by hgezim** [prisma/prisma#4850]
## Bug description

It seems to suffice that a field be marked as an array to another model for the migration to create a 1-n relationship.

## How to reproduce

0. Install docker and docker-compose.
1. `git clone git@github.com:hgezim/prisma-rl.git`
2. `docker-compose run api /bin/sh -c 'npm install && npm run prisma:run'`
3. Modify `prisma/schema.prisma` by adding this model:

```
model PostableEntity {
  id String @id
  accessToken String
  category String
  name String
}
```

4. In the existing `Post` model add this field: `postableEntities PostableEntity[]`
5. Run `docker-compose run api /bin/sh -c 'npm run prisma:generate'` to create a migration without running it.
6. Enter a name when prompted
7. Look at the SQL (`cat prisma/migrations/<date+name>/migration.sql`) for the migration generate. Notice how it creates a foreign key to the `Post` table.

```
-- CreateTable
CREATE TABLE "PostableEntity" (
    "id" TEXT NOT NULL,
    "accessToken" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "postId" INTEGER,

    PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "PostableEntity" ADD FOREIGN KEY("postId")REFERENCES "Post"("id") ON DELETE SET NULL ON UPDATE CASCADE;
```

## Expected behavior

This behavior contradicts the documents which state that

> 1-1 and 1-n relations require one side of the relation to be annotated with the @relation attribute, they're therefore commonly referred to as annotated relation fields.

https://www.prisma.io/docs/concepts/components/prisma-schema/relations#annotated-relation-fields-and-relation-scalar-fields

I expect it to throw an error if this is invalid. It appears to be the philosophy of prisma is **everything is explicit** in which case this shouldn't happen.

## Environment & setup

- OS: Ubuntu
- Database: Postgresql
- Node.js version: v12.20.0
- Prisma version: 

```
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.329.0
```

**Comment by pantharshit00** [comment]
I can confirm this as a bug, we should be throwing an error here.

**Comment by do4gr** [comment]
This should be solved by us splitting the parsing and formatting step here https://github.com/prisma/prisma-engines/pull/1662
