### ISSUE TITLE
Can not deploy model schema

### ISSUE THREAD

**Issue by j4nos** [prisma/prisma#4852]
Do you have any idea what is wrong with my schema? Following video tutorial on main page. https://www.prisma.io

<img width="573" alt="Képernyőfotó 2019-08-23 - 17 24 56" src="https://user-images.githubusercontent.com/11924475/63604008-0dad3980-c5cb-11e9-9f34-c0f0b214bfe5.png">

**Comment by pantharshit00** [comment]
Looks like that example is out of date 😅 

You will need to tell Prisma how to store the relation in datamodel 1.1(the example uses datamodel 1.0)

```graphql
type User {
  id: ID! @id
  email: String! @unique
  posts: [Post!]!
}

type Post {
  id: ID! @id
  title: String!
  author: User! @relation(link: INLINE)
}
```

**Comment by j4nos** [comment]
Worked, thanks! :)
