### ISSUE TITLE
Panic: Did not find a relation for model

### ISSUE THREAD

**Issue by brielov** [prisma/prisma#4854]
I'm using prisma `2.13.1`.

```prisma
model Movie {
  id       String           @id @default(cuid())
  title    String
  slug     String           @unique
  synopsis String
  year     Int
  runtime  Int
  imdb     String           @unique
  rating   Float
  poster   String
  genres   String[]
  cast     ActorsOnMovies[] @relation("ActorsOnMovies")

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Actor {
  id     String           @id @default(cuid())
  imdb   String           @unique
  name   String
  movies ActorsOnMovies[] @relation("ActorsOnMovies")

  createdAt DateTime @default(now())
  updtedAt  DateTime @updatedAt
}

model ActorsOnMovies {
  actorId   String
  actor     Actor  @relation("ActorsOnMovies", fields: [actorId], references: [id])
  movieId   String
  movie     Movie  @relation("ActorsOnMovies", fields: [movieId], references: [id])
  character String


  @@id([actorId, movieId])
}
```

Then I run `prisma db push --force --preview-feature` and I get:

```
Running generate... (Use --skip-generate to skip the generators)
Error: Schema parsing
thread 'main' panicked at 'Did not find a relation for model Actor and field movies', libs/prisma-models/src/datamodel_converter.rs:80:29
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: prisma_models::datamodel_converter::DatamodelConverter::convert_fields::{{closure}}::{{closure}}
   3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   4: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: prisma_models::datamodel_converter::DatamodelConverter::convert
   6: query_engine::main::main::{{closure}}::main::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: async_io::driver::block_on
  11: tokio::runtime::context::enter
  12: tokio::runtime::handle::Handle::enter
  13: std::thread::local::LocalKey<T>::with
  14: std::thread::local::LocalKey<T>::with
  15: async_std::task::builder::Builder::blocking
  16: query_engine::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by do4gr** [comment]
Thanks for reporting this!

To me it looks like that datamodel should not have passed validation in the first place. The relation name `ActorsOnMovies ` is used four times. This is invalid since it should uniquely identify one relation between two fields. 

I'll see whether we need to adjust our validation steps to detect this earlier.

**Comment by brielov** [comment]
@do4gr The relation name is indeed used four times, but I didn't do that manually, it was auto-generated by the prisma formatter. The only thing I changed was the fields name.

**Comment by albertoperdomo** [comment]
Probably several bugs: formatter as well as schema validator.

**Comment by mic1983** [comment]
Hi i had similar issue. MIgrations are generated corectly.
Error
`Prisma schema loaded from prisma/schema.prisma
Error: Schema parsing
thread 'main' panicked at 'Did not find a relation for model mldata and field alternativelmdata', libs/prisma-models/src/datamodel_converter.rs:80:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:391
  13: prisma_models::datamodel_converter::DatamodelConverter::convert_fields::{{closure}}::{{closure}}
  14: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  15: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  16: prisma_models::datamodel_converter::DatamodelConverter::convert
  17: query_engine::main::main::{{closure}}::main::{{closure}}
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: std::thread::local::LocalKey<T>::with
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: async_io::driver::block_on
  22: tokio::runtime::context::enter
  23: async_global_executor::reactor::block_on
  24: std::thread::local::LocalKey<T>::with
  25: async_std::task::builder::Builder::blocking
  26: query_engine::main
  27: std::rt::lang_start::{{closure}}
  28: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  29: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  30: std::panicking::try
             at src/libstd/panicking.rs:325
  31: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  32: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  33: main`
Schema
`model mldata {
  id            Int  @default(autoincrement()) @id
  job           job
  pod           assetpod
  service       service
  start         Int? //changed to BigInt in migration
  endf          Int? //changed to BigInt in migration
  content       String? //changed to Text in migration
  confidence    Float?
  parents       parentmldata[] @relation(name: "ParentMlData")
  alternative   alternativelmdata[] @relation(name: "AlternativeMlData")
  createdat     DateTime @default(now())
  updatedat     DateTime @updatedAt @default(now())
}

model parentmldata {
  id            Int  @default(autoincrement()) @id
  mldataid      Int
  mldata        mldata @relation(name: "TheMlData", fields: [mldataid], references: [id])
  parentid      Int
  parent        mldata @relation(name: "ParentMlData", fields: [parentid], references: [id])
}

model alternativelmdata {
  id            Int     @default(autoincrement()) @id
  mldataid      Int
  mldata        mldata  @relation(name: "TheMlData", fields: [mldataid], references: [id])
  alternativeid Int
  alternative   mldata @relation(name: "AlternativeMlData", fields: [alternativeid], references: [id]) 
}`

**Comment by tomhoule** [comment]
We improved validation and the formatter a lot in the last few releases. Please try again with 2.18.0 or later, and open a new issue if you notice anything wrong. Thanks for reporting!

**Comment by schwarzsky** [comment]
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb", "fullTextSearch"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model editedmessages {
  id          String   @id @default(auto()) @map("_id") @db.ObjectId
  userId String
  oldMessage String
  newMessage String
  editDate String
  messageID String
  user   users   @relation("users", fields: [userId], references: [userId], onDelete: NoAction, onUpdate: NoAction)
  users  users[]
}

model stafftags {
  id          String   @id @default(auto()) @map("_id") @db.ObjectId
  v           Int      @map("__v")
  fullMessage String
  type        String[]
  userId      String
}

model statistics {
  id    String @id @default(auto()) @map("_id") @db.ObjectId
  v     Int    @map("__v")
  date  String
  total Int
  type  String
}

model users {
  id               String           @id @default(auto()) @map("_id") @db.ObjectId
  v                Int              @map("__v")
  avatarURL        String
  firstMessage     String
  lastMessage String?
  userId           String           @unique(map: "userId_1")
  username         String           @unique(map: "username_1")
  statistics       userstatistics   @relation(fields: [userId], references: [userId])
  userstatistics   userstatistics[] @relation("users")
  message       editedmessages   @relation(fields: [userId], references: [userId])
  editedmessages   editedmessages[] @relation("users")
}

model userstatistics {
  id     String  @id @default(auto()) @map("_id") @db.ObjectId
  v      Int     @map("__v")
  total  Int
  userId String
  user   users   @relation("users", fields: [userId], references: [userId], onDelete: NoAction, onUpdate: NoAction)
  users  users[]
}

model webusers {
  id       String  @id @default(auto()) @map("_id") @db.ObjectId
  username String
  password String
  email    String
  admin    Boolean
}
```

Throws an error, 
```
❯ npx prisma format
Prisma schema loaded from prisma\schema.prisma
thread '<unnamed>' panicked at 'Did not find a relation for model users and field editedmessages', query-engine\prisma-models\src\builders\internal_dm_builder.rs:122:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Unexpected token D in JSON at position 0
```

**Comment by janpio** [comment]
I split this into a new issue @schwarzsky: https://github.com/prisma/prisma/issues/13193
