### ISSUE TITLE
Prisma website features list inaccuracy

### ISSUE THREAD

**Issue by pierreyves-lebrun** [prisma/prisma#4863]
The homepage of prisma website says:
> Latest ES7 features (e.g. async/await)

Async/await is not an ES7 but an ES8 feature.

**Comment by gustawdaniel** [comment]
There are different opinions :)

+ [Javascript ES7 Async Await Tutorial
](https://medium.com/@habibridho/javascript-es7-async-await-tutorial-64275c81ce2e)
+ [Javascript — ES8 Introducing `async/await` Functions](https://medium.com/@_bengarrison/javascript-es8-introducing-async-await-functions-7a471ec7de8a)

Bu you are right

+ [Async/await was introduced in 2017](https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9)
+ [And this is called ES8](https://medium.com/@madasamy/javascript-brief-history-and-ecmascript-es6-es7-es8-features-673973394df4)

**Comment by pierreyves-lebrun** [comment]
Yes, async/await was originally planned for ES7, which is why there are a lot of old articles talking about it as a ES7 feature
