### ISSUE TITLE
Server at * requires a cluster secret. Please provide it with the env var PRISMA_MANAGEMENT_API_SECRET

### ISSUE THREAD

**Issue by ken-nah** [prisma/prisma#4866]
**Describe the bug**
My first time trying Instant Prisma server deployment with  Heroku integration.  But when i run prisma deploy i get the following error **Server at * requires a cluster secret. Please provide it with the env var PRISMA_MANAGEMENT_API_SECRET.**  After adding the PRISMA_MANAGEMENT_API_SECRET in the .env file i get another new error **cluster secret in env var PRISMA_MANAGEMENT_API_SECRET does not match for cluster default**

Am running on Ubuntu **19.04** and running prisma version **1.34.8**

**Comment by gustawdaniel** [comment]
In version **1.34.7** released some days ago there was a bug in native Scala implementation of the authentication module.

It was resolved in https://github.com/prisma/prisma/issues/4860 but I did not tested it yet.

In my case back to **1.34.6** was solution. Try come back to this version it is possible that this bug still require some work.

**Comment by ken-nah** [comment]
> In version **1.34.7** released some days ago there was a bug in native Scala implementation of the authentication module.
> 
> It was resolved in #4860 but I did not tested it yet.
> 
> In my case back to **1.34.6** was solution. Try come back to this version it is possible that this bug still require some work.

@gustawdaniel It now works. Thanks mate.!
