### ISSUE TITLE
[Typescript client] Generated "WhereUniqueInput" type is incompatible with nexus-prisma-generate

### ISSUE THREAD

**Issue by trungtin** [prisma/prisma#4870]
**Describe the bug**
prisma generated this:
```
type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];
type Maybe<T> = T | undefined | null;

type _______WhereUniqueInput = AtLeastOne<{
  id: Maybe<ID_Input>;
}>
```

while the nexus-prisma-generate, with using prismaFields to expose all fields, generated this instead:
```
interface _______WhereUniqueInput {
  id?: string | null
}
```

The prisma version is without the "?" optional, from here 
https://github.com/prisma/prisma/blob/62cfeaa5930ef25eab45ef249b222ccac15e59fe/cli/packages/prisma-client-lib/src/codegen/generators/typescript-client.ts#L801-L805

The point is if the field has Maybe type should we keep the `optional ? mark`

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.34.8
 - `prisma` CLI: 1.34.8
 - OS: OS X 
 - other dependencies: nexus-prisma-generate v0.3.7

**Additional context**

**Comment by jordan-burnett** [comment]
@trungtin - Don't suppose you ever found a workaround to this? I'm running into the same issue

**Comment by trungtin** [comment]
For these kind of workaround I use patch-package to modify the source directly
