### ISSUE TITLE
Confused on why my prisma.graphql  isn't being regenerated

### ISSUE THREAD

**Issue by Dinnall** [prisma/prisma#4871]
Hi there,

I haven't been able to generate a new prisma.graphql for a week.
When I run `npm run deploy` I receive a message that it's updated but I  still see old code

PLEASE ANY HELP IS APPRECIATED
I've set up my package.json that I only need to run `npm run deploy`.

Here is my  **prisma.yml** set up 

    endpoint: ${env:PRISMA_ENDPOINT}
    datamodel: datamodel.prisma
    # secret:  ${env:PRISMA_SECRET}
    hooks:
      post-deploy:
          - graphql get-schema -p prisma

**.graphqlconfig.yml**

    projects:
      app:
        schemaPath: "src/schema.graphql"
        extensions:
          endpoints:
            default: "http://localhost:4444"
      prisma:
        schemaPath: "src/generated/prisma.graphql"
        extensions:
          prisma: prisma.yml

my **package.json** scripts object so I can use `npm run deploy` in the terminal

      "scripts": {
        "start": "nodemon -e js,graphql -x node src/index.js",
        "dev": "nodemon -e js,graphql -x node --inspect src/index.js",
        "test": "jest",
        "deploy": "prisma deploy --env-file variables.env"
      },

**Comment by alchematrix0** [comment]
Hi @Dinnall, I have the same issue at times. What I've done in the passed is to revert to an old copy of my datamodel file and then apply each update one by one. Eventually, I get to a place where something fails and that usually gives me a clue as to either something is not formatted right, or something is buggy with how relations are being handled. I totally agree, this is very annoying as no indication of why it failed is to regen the file locally is provided.

For reference, my terminal says this after the list of changes:

```
Applying changes 721ms

post-deploy:
- 
- project prisma - No changes

Running graphql get-schema -p prisma...
project prisma - No changes
Running graphql get-schema -p prisma ✔
```

and sure enough, the generated file is not updated BUT my deployment history in Prisma console shows that the updates were made to the database.

**Comment by Dinnall** [comment]
@alchematrix0 I've tried this approach before its odd but I still don't see any change. I also started to think it was because of relation with my database.

**Comment by alchematrix0** [comment]
Hey I also found this which worked for me, added it to my prisma.yml file

```
generate:
   - generator: graphql-schema
     output: ./src/generated/prisma.graphql
```

then I could run `prisma generate`, the output option might be different for you depending where you want it to end up, but it did create an SDL document based on my current datamodel 💯 

Also, strangely, once I deleted the generated file, `prisma deploy` started working again?! Madness.

**Comment by RoMay** [comment]
The schema is also generated for me, but there is missing Node-interface implementation.
Is it supported by Prisma graphql-schema generator?

**Comment by Karl-EdwardFPJeanMehu** [comment]
@Dinnall I've also added Prisma commands to my package.json file. However, I also changed the directory to where the prisma.yml file is located. So your script command would look like:
 `` "deploy": "cd [prisma location] && prisma deploy --env-file variables.env"``
