### ISSUE TITLE
Deletion of object with non-nullable type field leads to "Cannot return null for non-nullable type" error

### ISSUE THREAD

**Issue by jpmoss3** [prisma/prisma#4872]
**Description**
While deleting object whose model contains a non-nullable type, concurrent query on existing object is done.
The result query may produce error "Cannot return null for non-nullable type" as if the deletion was not transactional.

**To Reproduce**
- Use the project https://github.com/jpmoss3/non-nullable_type.git
- follow steps to reproduce in readme.md
- see console results

**My Schema**
```graphQL
type Foo {
  id: ID! @id
  name: String!
  bar: Bar @relation(name:"BetweenBarAndFoo")
}

type Bar {
  id: ID! @id
  name: String!
  foo: Foo! @relation(name:"BetweenBarAndFoo" link: TABLE onDelete:CASCADE)
}
```

**Expected behavior**
As deletion is supposed to be transactional, querying existing (Bar) object should only give consistent objects with non null value on (foo) non-nullable field 

**Screenshots**
```
      {
        "message": "Cannot return null for non-nullable type (line 2, column 17):\n  bars {id name foo {id name}}\n                ^",
        "path": [
          "bars",
          6,
          "foo"
        ],
        "locations": [
          {
            "line": 2,
            "column": 17
          }
        ]
      },
```

**Versions:**
 - Postgres: 10.6
 - Prisma Server: 1.34.8
 - Prisma CLI version: prisma/1.34.8 (linux-x64) node-v8.15.0
 - OS:  CentOS Linux 7
 - other dependencies: `graphql-request 1.8.2`

**Comment by mjamelot** [comment]
Hi,
We have find the same problem

**Comment by slg1** [comment]
Is there anything new about this issue ?

**Comment by slg1** [comment]
any news about this issue ?

**Comment by jpmoss3** [comment]
I'm still hoping for solution
