### ISSUE TITLE
Prisma Admin console doesn't load

### ISSUE THREAD

**Issue by jayanth1991** [prisma/prisma#4882]
**Describe the bug**
The prisma Admin console does not load and there seem to be no errors in the console either. I rolled back to Prisma Server: 1.33 but that also has the same issues.

**To Reproduce**
1. Go to 'http://localhost:4466/_admin'

**Expected behavior**
The admin console should load.

**Screenshots**

![image](https://user-images.githubusercontent.com/1319597/64994171-f4379e80-d8a5-11e9-8228-6b1981f2a427.png)
![image](https://user-images.githubusercontent.com/1319597/64994224-0dd8e600-d8a6-11e9-870d-dc3ffeb10ba6.png)

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server: 1.34.8
 - `prisma` CLI: `prisma/1.34.8 (windows-x64) node-v10.16.2`
 - OS:  `Windows 10`

**Comment by jwld** [comment]
Same issue here. Has the entirety of prisma 1 been abandoned by the devs? 😢

**Comment by jayanth1991** [comment]
Still has the issue, not stale.

**Comment by jayanth1991** [comment]
Not stale -- still has the same issue

**Comment by jwld** [comment]
@jayanth1991 I had this problem when I deleted a service and then created a new one with the same name. Possibly some caching issue - once I created a new one with a different name it was fine.

**Comment by jayanth1991** [comment]
hey @jwld its happening on my local, i am not sure if its browser caching (tried it on incognito as well) or app caching either because it happens on all of my colleague machines as well.
