### ISSUE TITLE
Slow Nested Queries - taking 2 seconds plus

### ISSUE THREAD

**Issue by SelfDevTV** [prisma/prisma#4884]
## Bug description

Hi guys,

I'm building a reddit clone right now with `Prisma` + `AWS` (as PostgreSQL Hoster) + `Next.js`. I'm fetching a subreddit with all details on it (mainly posts and subscribed users) in `getServerSideProps`. I make a fetch request to my api and in my api I make a call to my prisma database (hosted on Amazon AWS - PostgreSQL). This maybe related to #2481

Here is the working live example (just select a subreddit in the dropdown). Next.js has some posts, learnprogramming hasnt: https://reddit-clone-teal.vercel.app/

Is that slow / fast to you? For me it's a bit slow with that little data (Vercel Analytics = 3 seconds) 😢 

**Here is the api (`/api/subreddit/findSubreddit`)**

```
const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  try {
    const sub = await prisma.subreddit.findUnique({
      where: { name: String(req.query.name) },
      include: {
        posts: {
          include: { subreddit: true, user: true },
        },
        joinedUsers: true
      },
    });

    console.log("here is the sub", sub);

    if (!sub) {
      return res.status(500).json({ error: "No sub was found with this name" });
    }

    res.json(sub);
  } catch (e) {
    res.json(e);
  }
};
```

So nothing too crazy right (it's 3 posts total)? Or am I including too much in the call?
Anyway when I transition to a subreddit and this function runs (there are currently 3 dummy posts in the db) it takes sometimes 1.5 - 2 seconds after the page has loaded in.
With such little data this should be much less loading time am I right?

I'm using `swr` and here is how a subreddit page looks like:

**First the `getServerSideProps` function:**

```
export async function getServerSideProps(ctx) {
  const url = `${process.env.NEXTAUTH_URL}/api/subreddit/findSubreddit?name=${ctx.query.sub}`;
  const fullSub = await fetchData(url);

  return {
    props: {
      fullSub,
    },
  };
}
```

**And then on the page itself (`/pages/subReddits/[sub]`):**

```
const { data: fullSub, error } = useSWR(
    `/api/subreddit/findSubreddit?name=${sub}`,
    fetchData,
    {
      initialData: props.fullSub,
    }
  );
```

**Here is the log from prisma when I hit this api:**

>prisma:query SELECT "public"."Subreddit"."id", "public"."Subreddit"."name", "public"."Subreddit"."displayName", >"public"."Subreddit"."infoBoxText", "public"."Subreddit"."createdAt" FROM "public"."Subreddit" WHERE >"public"."Subreddit"."name" = $1 LIMIT $2 OFFSET $3
>prisma:query SELECT "public"."Post"."id", "public"."Post"."title", "public"."Post"."body", "public"."Post"."subredditId", >"public"."Post"."userId", "public"."Post"."createdAt", "public"."Post"."updatedAt" FROM "public"."Post" WHERE >"public"."Post"."subredditId" IN ($1) OFFSET $2
>prisma:query SELECT "public"."users"."id", "public"."users"."name", "public"."users"."email", "public"."users"."email_verified", >"public"."users"."image", "public"."users"."created_at", "public"."users"."updated_at" FROM "public"."users" WHERE >"public"."users"."id" IN ($1) OFFSET $2
>prisma:query SELECT "public"."_SubredditToUser"."A", "public"."_SubredditToUser"."B" FROM "public"."_SubredditToUser" WHERE >"public"."_SubredditToUser"."A" IN ($1)
>prisma:query SELECT "public"."users"."id", "public"."users"."name", "public"."users"."email", "public"."users"."email_verified", >"public"."users"."image", "public"."users"."created_at", "public"."users"."updated_at" FROM "public"."users" WHERE >"public"."users"."id" IN ($1) OFFSET $2

Here a screenshot from Vercel Analytic:

![image](https://user-images.githubusercontent.com/48333000/103637252-7b050480-4f4b-11eb-9d44-a597607fc3bb.png)

Can you figure it out? Any ideas why this might long load and not cache? The db is hosted in frankfurt (on AWS) don't know if that's important to you. But im located in Austria and my ping to Frankfurt is 45ms. 
The api request is faster when opened on my local machine (localhost) (project running locally i mean), but also not "fast"

Full link to my repo: https://github.com/SelfDevTV/reddit-clone

If you need **Anything** please let me know I will test it out. 

Thank you so much!
_**PS: Prisma rocks!**_

## How to reproduce

Go to my link and try it out: https://reddit-clone-teal.vercel.app/

## Expected behavior

It should be way faster to load the 3 posts on my site.

## Environment & setup

- OS: Windows 10 latest
- Database: PostgreSQL hosted on AWS (Frankfurt EU)
- Node.js version: v14.15.1
- Prisma version:

```
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : windows
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.329.0
```

**Comment by SelfDevTV** [comment]
## Update:

I kinda replicated the same query with mongo db using `mongo atlas` which uses `aws` also an frankfurt gateway. 
This is the queue I run on the same api (everything is the same as above):

```
Subreddit.findById(id)
    .populate({
      path: "posts joinedUsers",
      populate: {
        path: "subreddit",
      },
    })
    .exec(function (err, sub) {
      if (err) return res.json({ error: "error", err });

      console.log("The author is %s", sub);
      res.json(sub);
      // prints "The author is Ian Fleming"
    });
```

Here is the data that gets returned:

```
{
    "posts": [
        {
            "comments": [],
            "_id": "5ff4aba5a63be920148b441b",
            "title": "Test123",
            "body": "12544",
            "subreddit": {
                "posts": [
                    "5ff4aa28058f296f30047512"
                ],
                "joinedUsers": [],
                "_id": "5ff4a7255182867884d708e8",
                "name": "Test123",
                "displayName": "adsfadsf",
                "__v": 0
            },
            "__v": 0
        }
    ],
    "joinedUsers": [
        {
            "comments": [],
            "_id": "5ff4aba5a63be920148b441a",
            "title": "joined",
            "body": "joined",
            "__v": 0
        }
    ],
    "_id": "5ff4aba6a63be920148b441c",
    "name": "Test123",
    "displayName": "adsfadsf",
    "__v": 0
}
```

The response time after testing it about 50 times is ALWAYS under 180ms

**Comment by SelfDevTV** [comment]
## Update 2:

I installed pgAdmin and tried to run this query:

`SELECT * from "Post" INNER JOIN "Subreddit" ON "Subreddit".id = "Post"."subredditId" INNER JOIN "Vote" ON "Vote"."postId" = "Post".id INNER JOIN users ON users.id = "Post"."userId"`

This runs for 122ms every time (so very fast). I'm fairly new to raw SQL Queries and don't know if it's 1:1 the same but here is the data I get back from it:

![image](https://user-images.githubusercontent.com/48333000/104073275-8d15ca00-520d-11eb-9730-1bcc37c047d4.png)

Please let me know if you can look into it. Thx guys

**Comment by pantharshit00** [comment]
Hello @SelfDevTV 

I am pretty sure this is a deployment issue. I deployed your app to vercel and with a digitalocean database(pgbouncer enabled and it is hosted in the San Francisco region) here: https://prisma-issue-4884.vercel.app/

Repository: https://github.com/harshit-test-org/prisma-issue-4884

If you inspect this deployment, you will see it is as fast as the database numbers that you are sharing.

![image](https://user-images.githubusercontent.com/22195362/104188938-fc730000-543f-11eb-849e-289497495831.png)


Vercel deploys all the lambdas to SFO1 region of AWS by default. You can confirm this by logging `VERCEL_REGION` environment variable as you can see in the above screenshot. 


So please make sure your database is hosted in the same region as your vercel lambda deployments. Otherwise network will add heavy latency. 

Here is the result of the performance route(https://prisma-issue-4884.vercel.app/api/performance?name=nextjs):
![image](https://user-images.githubusercontent.com/22195362/104190279-e0705e00-5441-11eb-946e-9b8379b47ca5.png)


I will also post the vercel analytics result for this deployment once their dashboard updates. Right now it show 100 for the home route: 
![image](https://user-images.githubusercontent.com/22195362/104190460-24fbf980-5442-11eb-8524-664d60611e85.png)

**Comment by SelfDevTV** [comment]
@pantharshit00 thank you so much for your answer 👍 That makes sense. 
I try to go to AWS and change the gateway to San Franciso instead of Frankfurt and report back if this fixes the error.

BUT: Your deployment is way faster then my local project. When I run this locally it takes longer then your deployment to San Francisco while I'm located in austria. How is this even possible?

**Comment by pantharshit00** [comment]
@SelfDevTV I think that might be the database difference. I am using a $15 digitalocean postgres deployment along with pgbouncer(which is free on digitalocean) so it has enough connection and good networking for this use case. 

Pgbouncer(or a connection pooler like RDS proxy) is required for this to scale as this is a serverless deployment and every new lambda instance will create a separate connection pool without it causing connection exhaustion.

**Comment by SelfDevTV** [comment]
@pantharshit00 Interesting. That might be the problem. I'm on a free tier, but never imagined that this would decrease the performance of this db by that much. I mean there are worlds between my local project and your deploy to vercel on San Francisco. And I'm on the other side of the planet pretty much wtf. 

I will test some things and will report back. Thx for your help! It's much appreciated!

**Comment by SelfDevTV** [comment]
Hi @pantharshit00 I can confirm deploying to Digital Ocean with pgbouncer (never knew that even existed) got me the same nice performance as you: https://reddit-clone-gwtmyjifs.vercel.app/api/performance?name=nextjs

The only disadvantage is that performance is not not the best on localhost, because of the way from EU to San Francisco. But that's how it is and not a bug from `prisma`. Now I love it even more!
I think this issue can be closed since this is not a fault from `prisma`. 

Should I close it?

**Comment by pantharshit00** [comment]
Thanks for the confirmation

**Comment by SelfDevTV** [comment]
@pantharshit00 Thank you so much for taking the time and to try it out. Keep up the good work. Greetings from Austria!
