### ISSUE TITLE
No documentation to pass in postgres ssl certificate

### ISSUE THREAD

**Issue by EarthBug** [prisma/prisma#4888]
How do we pass in the certificate for ssl connections while using postgres connector?

**Comment by EarthBug** [comment]
My environment has option for postgres or mongo. But both of them require me to pass a certificate to authenticate. Is it possible to use prisma in my scenario?

**Comment by yesprasad** [comment]
@mavilein @do4gr @nikolasburk @timsuchanek Can one of you please take some time and help us answer this query. Even I have the same issue. Our database needs to be called with certificates and when I pass these certificates there is nothing that happens. Looks like Prisma drops these certificates and thus no connection gets established. Can you help us out here?

**Comment by mavilein** [comment]
@yesprasad : Thanks for pinging. 🙏 We currently don't support SSL certificates but we are working on it right now: https://github.com/prisma/prisma2/issues/568

**Comment by EarthBug** [comment]
Hope to see this in prisma2
