### ISSUE TITLE
Preview feature feedback: `groupBy`

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4893]
Please share your feedback about the preview feature `groupBy ` that was released in [v2.14.0](https://github.com/prisma/prisma/releases/tag/2.14.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo. 
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma2`](https://app.slack.com/client/T0MQBS8JG/CKQTGR6T0) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by Sytten** [comment]
So a few things:
- The `ModelGroupByOutputType` puts all keys as nullable even if they are not nullable in the database.
- The `groupBy` method parameter is pretty ugly, can you create an alias like `AggregateTicketArgs` and others like it.

**Comment by matthewmueller** [comment]
Thanks for the feedback!

> The ModelGroupByOutputType puts all keys as nullable even if they are not nullable in the database.

Asking about this one. I'll get back to you early next week.

> The groupBy method parameter is pretty ugly, can you create an alias like AggregateTicketArgs and others like it.

Which method parameter? The name of the type declaration? Can you share some code?

**Comment by Sytten** [comment]
@matthewmueller  you can see the difference
<img width="971" alt="Screen Shot 2021-01-07 at 2 39 18 PM" src="https://user-images.githubusercontent.com/2366731/103936991-25b92680-50f6-11eb-9591-b1470da442c2.png">

**Comment by matthewmueller** [comment]
Thanks for the response! I hopefully can see the difference, do you mean you'd like for the 2nd and 3rd generic type parameters to have aliases? 

Something like:

```ts
export type HasSelectOrTake = HasSelectOrTake extends Or<
  Extends<'skip', Keys<T>>,
  Extends<'take', Keys<T>>
>

export type OrderByArg = OrderByArg extends True extends HasSelectOrTake
  ? { orderBy: GroupByAgentArgs['orderBy'] }
  : { orderBy?: GroupByAgentArgs['orderBy'] },
  OrderFields extends Keys < MaybeTupleToUnion < T['orderBy'] >>,
    ByFields extends TupleToUnion < T['by'] >,
      ByValid extends Has < ByFields, OrderFields >,
        HavingFields extends GetHavingFields < T['having'] >,
          HavingValid extends Has < ByFields, HavingFields >,
            ByEmpty extends T['by'] extends never[] ? True : False,
              InputErrors extends ByEmpty extends True
                ? `Error: "by" must not be empty.`
                : HavingValid extends False
                  ? {
                    [P in HavingFields]: P extends ByFields
                      ? never
                      : P extends string
                        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                        : [
                          Error,
                          'Field ',
                          P,
                          ` in "having" needs to be provided in "by"`,
                        ]
                  }[HavingFields]
                  : 'take' extends Keys<T>
                    ?'orderBy' extends Keys<T>
                    ?ByValid extends True
                    ? {}
                    : {
                      [P in OrderFields]: P extends ByFields
                        ? never
                        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                    }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                    : 'skip' extends Keys<T>
                    ?'orderBy' extends Keys<T>
                    ?ByValid extends True
                    ? {}
                    : {
                      [P in OrderFields]: P extends ByFields
                        ? never
                        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                    }[OrderFields]
                    : 'Error: If you provide "skip", you also need to provide "orderBy"'
                    : ByValid extends True
                    ? {}
                    : {
                      [P in OrderFields]: P extends ByFields
                        ? never
                        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                    }[OrderFields]

```
?

**Comment by Sytten** [comment]
Nothing specifically yet but when you cmd+click on the name ita pretty ugly where the other methods are clean. So mostly for consistency. I also usually do that to navigate to the arguments parameters when I forget what I can input.

**Comment by matthewmueller** [comment]
> The ModelGroupByOutputType puts all keys as nullable even if they are not nullable in the database.

FYI, we'll be working on this one in #4987. Thanks for spotting this @Sytten!

**Comment by zackify** [comment]
I don't see any way to order by the highest count, this seems to be the only missing feature?

```
 let casesByCode = await appDb.caseCode.groupBy({
    by: ['code', 'id'],
    count: {
      code: true,
    },
    take: 6,

  //no way to do this:
  orderBy: {
   count: true
  }
  })
```

So if I want to group a table by a column, and i want only the most used 'code's in this case, i cant control ordering by the amount that were grouped?

In raw sql i would select count(*) and then order by count

**Comment by pseuyi** [comment]
small feature request if it doesn't exist. one thing i need to do is to be able to group by year extracted from a string in the timestamp column. i'm using postgres as my db and the raw sql for what i'm describing is this:
```
GROUP BY
	“report”.source,
	EXTRACT(YEAR FROM “report”.timestamp)
```
i don't see a way to be able to generate the `EXTRACT` using the `groupBy` arg, `by: []`.

**Comment by uncvrd** [comment]
Agreed with @zackify above! Would love to be able to `orderBy` count while performing a `groupBy`.

For example, I have the follow raw query I'd be interested in moving to Prisma syntax instead:

```
const topArtists = await ctx.db.$queryRaw<{ artistId: number }[]>`SELECT "artistId"
        FROM "UserArtist"
        GROUP BY "artistId"
        ORDER BY COUNT(*) DESC
        LIMIT 10`
```

However I cannot fully translate this query due to the fact that I cannot `orderBy` count!

**Comment by matthewmueller** [comment]
Hey @zackify and @uncvrd, thanks for sharing your use cases. That's indeed a limitation right now. I've opened an issue for this feature: https://github.com/prisma/prisma/issues/5464. The workaround for now is to sort in your application.

@pseuyi we don't yet support arbitrary expressions like this. It's on our radar, but solving it requires quite a bit of internal refactoring. We'd also like to solve it in a much broader way. In the meantime, raw is the way to go. Sorry about that!

**Comment by matthewmueller** [comment]
This one will be stabilized in `2.20.0`. Thanks for the comments everyone! We'll continue in separate issues.
