### ISSUE TITLE
Introspect Error

### ISSUE THREAD

**Issue by Nou-r** [prisma/prisma#4894]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v12.18.3           | 
| Prisma CLI  | 2.14.0             | 
| Binary      | 5d491261d382a2a5ffdc71de17072b0e409f1cc1| 

## Error
```
Error: [libs/datamodel/connectors/dml/src/datamodel.rs:172:14] Every RelationInfo should have a complementary RelationInfo on the opposite relation field.
```

**Comment by albertoperdomo** [comment]
Hello @Nou-r,

can you please share the schema that you are using that is triggering this behavior? Thanks!
