### ISSUE TITLE
Using Amazon MQ instead of Rabbit MQ for horizontal scaling

### ISSUE THREAD

**Issue by itdataguy** [prisma/prisma#4900]
Asking this question here for clarity.  I have read https://github.com/prisma/prisma/issues/2850 and noted that to horizontally scale the Prisma server I need to provide Rabbit MQ for state sync between nodes.

Can Amazon MQ be used if using the AMQP Connection for Prisma?

**Comment by grimunit** [comment]
@itdataguy Did you ever end up trying using Amazon MQ? Or did you just go with CloudAMQP? Or did you end up moving to Prisma 2?

**Comment by grimunit** [comment]
I'll give an update since I happen to come across this issue again, I was able to successfully using Amazon MQ no problem, was super easy to setup. It just give you a URL that you put in the Prisma config and done.
