### ISSUE TITLE
Ruunig prisma container outside the server is not working

### ISSUE THREAD

**Issue by EhsanSarshar** [prisma/prisma#4906]
I have a linux centos 7 vps which is running prisma container. I can successfully query databases from inside the vps. But when I want access the prisma outside the vps in my pc, it just show me the playground, but querying will result to "project not found prisma_default"

Vps: centos7
Database: mongodb 
Reverse proxy: nginx

**Comment by kalm42** [comment]
What solved this? I'm having the same error.
