### ISSUE TITLE
Cannot read property 'isCanceled' of undefined

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#4906]
## Bug description

```
/Users/luca/projects/ws-backend/node_modules/@prisma/client/runtime/index.js:26190
        if (this.currentRequestPromise.isCanceled) {
                                       ^
TypeError: Cannot read property 'isCanceled' of undefined
    at NodeEngine.handleRequestError (/Users/luca/projects/ws-backend/node_modules/@prisma/client/runtime/index.js:26190:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at /Users/luca/projects/ws-backend/node_modules/@prisma/client/runtime/index.js:26855:25
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## How to reproduce

I really don't know, since this seems to happen very rarely and not consistently. :(

Since there are no stack traces, I can only guess where it originated. From my own logs I had at the time the error occurred, it looks like it happened with `prisma.$transaction`.

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```
@prisma/cli          : 2.14.0
@prisma/client       : 2.14.0
Current platform     : darwin
Query Engine         : query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.332.0

```

**Comment by net-caster** [comment]
Yep, started happening after upgrading to **2.14.0** over here as well.

**Comment by Dreamystify** [comment]
Im still getting this on **2.16.1**

**Comment by pantharshit00** [comment]
@Dreamystify Please open a new issue with a minimal reproduction.

**Comment by Dreamystify** [comment]
> @Dreamystify Please open a new issue with a minimal reproduction.

It seemed random and unable to reproduce, but after persisting, I found that using a findMany() with 2 properties in the where clause I replaced with a findUnique() with 1 where clause and a check for the second property after solved it.

the 2 where clauses was the id and active field, I just got the row with the id and checked the active field on the result and the issue disappeared, no idea but might be useful for solving for you guys and others that may come across this

**Comment by janpio** [comment]
Can you create a new issue please @Dreamystify? This sounds like a good enough reproduction that we could try it.

**Comment by hariria** [comment]
Yes still getting this as well

**Comment by hariria** [comment]
*edit: was resolved for me when I upgraded from `"@prisma/cli": "2.14.0" -> "2.17.0"` and `"@prisma/client": "2.14.0" -> "2.17.0"`

**Comment by Dreamystify** [comment]
> Can you create a new issue please @Dreamystify? This sounds like a good enough reproduction that we could try it.

Sorry for late reply, I haven't had time for it but it looks like the update to 2.17 helped me also
