### ISSUE TITLE
2.12 > 2.14 migration issue

### ISSUE THREAD

**Issue by MariuzM** [prisma/prisma#4908]
Updated to v2.14 and i can't do migration. So I've deleted the migration folder and only have the schema.
Then i run `yarn prisma generate` and i get 
```
✔ Generated Prisma Client (2.14.0) to ./node_modules/@prisma/client in 279ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

warn Prisma 2.12.0 has breaking changes.
You can update your code with
`npx @prisma/codemods update-2.12 ./`
Read more at https://pris.ly/2.12
```

Why does it say still 2.12?

So then i tried `prisma migrate dev --preview-feature`  and i get:
```
Error: A migration failed when applied to the shadow database:

P3014
Prisma Migrate could not create the shadow database. Please make sure the database user has permission to create databases.  More info: https://pris.ly/d/migrate-shadow. Original error: 
Database error: Error querying the database: db error: ERROR: permission denied to create database
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:174
   1: sql_migration_connector::sql_database_migration_inferrer::calculate_drift
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:59
   2: migration_core::api::DiagnoseMigrationHistory
             at migration-engine/core/src/api.rs:109
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My db is hosted on heroku, i know 2.13 had this issue and 2.12 did not but i thought 2.14 fixed them?

**Comment by net-caster** [comment]
I think your DB user needs (root) permissions to create/destroy databases.

P.S. It shows the current **Prisma** version in the first line *Generated Prisma Client (2.14.0) to...*, so you have upgraded successfully.

**Comment by Jolg42** [comment]
Indeed Prisma Migrate evolved (https://www.prisma.io/blog/prisma-migrate-preview-b5eno5g08d0b) and is now using a shadow database in development, see https://pris.ly/d/migrate-shadow for the user rights requirements for the `prisma migrate dev` command.

I suggest you add more privileges to the database user, does that work for you?

**Comment by Jolg42** [comment]
About the `2.12` message, it's because 2.12 introduced a breaking change and we created a codemod to do the upgrade, it will go away in 2.15, you can ignore it if you already used the codemod or didn't use a version < 2.12

**Comment by MariuzM** [comment]
@Jolg42 problem with Heroku is that we don't have access to these kind of rights management. There was a ticket can't remember when 2.13 was release had this issue. https://github.com/prisma/prisma/issues/4571

**Comment by Jolg42** [comment]
So if you want to use an Heroku remote database with `migrate dev` you can track this issue that we plan to tackle for 2.15.0 https://github.com/prisma/prisma/issues/4751 😃 

Thanks for reporting!
