### ISSUE TITLE
Add support for "has-many-through" relationship

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma#4910]
It would be great to have a "has-many-through" relationship in Prisma, similar to Laravel.

The Prisma Client should make this easy for us.

[Read this](https://laravel.com/docs/8.x/eloquent-relationships#has-many-through) for more info about the "has-many-through" relationship in Laravel.

**Comment by albertoperdomo** [comment]
I think this is a duplicate of https://github.com/prisma/prisma/issues/2186

**Comment by janpio** [comment]
It is indeed a duplicate for the same problem and solution, and as it has no additional upvotes or comments, I am closing this now.

Thanks for opening the issue back in the day @jferrettiboke!
