### ISSUE TITLE
Prisma Client Node-API Support

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#4911]
Currently the Prisma Client communicates with the Query Engine over HTTP or Unix Domain Sockets. After some experimentation we realized we can cut this overhead down significantly with [Node-API](https://napi.rs). 

Node-API binds the Query Engine into the Prisma Client directly, so calling into the Query Engine is no different than calling a Node.js function.

@pimeys has been shown in https://github.com/pimeys/napi-test it's possible to connect from Node.js to the query engine via the Node-API.

**Comment by pimeys** [comment]
This depends on: https://github.com/prisma/quaint/issues/231

**Comment by pimeys** [comment]
Also, this would require some more research on error handling, what we can do with napi is to return a `napi::Error` that takes a status:

```
pub enum Status {
    Ok,
    InvalidArg,
    ObjectExpected,
    StringExpected,
    NameExpected,
    FunctionExpected,
    NumberExpected,
    BooleanExpected,
    ArrayExpected,
    GenericFailure,
    PendingException,
    Cancelled,
    EscapeCalledTwice,
    HandleScopeMismatch,
    CallbackScopeMismatch,
    QueueFull,
    Closing,
    BigintExpected,
    DateExpected,
    ArrayBufferExpected,
    DetachableArraybufferExpected,
    WouldDeadlock,
    Unknown,
}
```
and a reason as a string. Our error mechanics are a bit more fine-grained than that, so we should discuss what would be the best way to transfer this information. We could always encode json to the reason (rhymes), but is it the most ergonomic way on the javascript side?

Also what to do with panics, should we catch them in the rust layer and convert them to javascript errors, or just panic, crash and burn?

There's some nice integrations between serde and javascript objects in the crate we could use.

The docs and the API are, well, you should know what's going on under the surface to understand the api, it's quite C++ style. Luckily whatever this wrapper would be would not be more than one or two files and a few hundred lines of code, mostly type conversions.

**Comment by pimeys** [comment]
Docs and philosophy of napi for people interested: https://napi.rs/

Another interesting link is the N-API version matrix: https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix

Now we do need some more recent features, mainly the threadsafe function support to be able to run tokio futures and convert them to javascript promises. This requires the `napi_threadsafe_function`, which was introduced in node.js 10.6 and N-API version 4.

**Comment by Brooooooklyn** [comment]
> Also what to do with panics, should we catch them in the rust layer and convert them to javascript errors, or just panic, crash and burn?

`napi` already catch the `panic!` from `Rust`, and transform it into `JsError`, see https://github.com/napi-rs/napi-rs/blob/main/test_module/src/error.rs#L18

**Comment by pimeys** [comment]
> `napi` has already caught the `panic!` from `Rust`, and transform it into `JsError`, see https://github.com/napi-rs/napi-rs/blob/main/test_module/src/error.rs#L18

Thanks for the info and thank you for a great project @Brooooooklyn. 

Now I'm planning to do the first test integrating Query Engine and N-API beginning of next week. We need to upgrade all our crates to Tokio 1.0 first, and the last missing piece is async-std so it can emulate tokio for our HTTP server. That should happen tomorrow in the next version, and I can do a bigger test with some benchmarks on Monday.

**Comment by pimeys** [comment]
Here's the first test version: https://github.com/prisma/prisma-engines/pull/1544

It's about 60 lines of N-API specific code, and even though it's the first test, it's not quite far from being all the work that's needed to finish this on Rust side.

**Comment by matthewmueller** [comment]
Reopening as integration still is WIP and we're working out a few remaining issues around logging.

**Comment by matthewmueller** [comment]
Closing in favor of https://github.com/prisma/prisma-engines/issues/1627

**Comment by matthewmueller** [comment]
Rust work needed in https://github.com/prisma/prisma-engines/issues/1627

**Comment by Jolg42** [comment]
Reopening as it's currently missing tests

**Comment by janpio** [comment]
This will ship in the next release.
