### ISSUE TITLE
Reserved index names in SQLite cannot be migrated

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#4914]
When introspecting an SQLite schema, in certain cases the database can have constraints with reserved name. Let's imagine a data model:

```prisma
model results {
  election_id  Int
  candidate_id Int
  party_id     Int
  votes        Int
  
  @@unique([election_id, candidate_id, party_id], name: "sqlite_autoindex_results_1")
}
```

This is from a [different bug ticket](https://github.com/prisma/prisma/issues/4778), but when I tried to push the schema to my local database I got this error:

```
Error: Connector error: Database error: Error querying the database: object name reserved for internal use: sqlite_autoindex_results_1


Caused by:
    0: Database error: Error querying the database: object name reserved for internal use: sqlite_autoindex_results_1

    1: Database error
    2: Error querying the database: object name reserved for internal use: sqlite_autoindex_results_1
```

**Comment by pantharshit00** [comment]
I can reproduce this as well:
![image](https://user-images.githubusercontent.com/22195362/104728710-5421ac00-575d-11eb-8cf2-564450d883bb.png)

**Comment by Jolg42** [comment]
Closing as the error message is clear enough.
