### ISSUE TITLE
MSSQL Prisma Introspection not working: Server name cannot be determined

### ISSUE THREAD

**Issue by alexandra-c** [prisma/prisma#4916]
When running `npx prisma init` command after executing all the steps presented in "Start from scratch with SQL Server" chapter, i get this error:

![image](https://user-images.githubusercontent.com/46926675/103922379-52803480-511c-11eb-99c3-708414e67ac6.png)

My SQL server is in Azure, i tried with both host name and IP Address and same result.

This is my .env file:
``
DATABASE_URL="sqlserver://incubsqlmi.public.somecodeicannotshare.database.windows.net:3342;database=mydb;user=user;password=password;trustServerCertificate=true"
``

and this is my schema:

```
datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["microsoftSqlServer"]
}
```

I haven't found this in known issues or other opened or closed issues, can someone help me with this please?
Thank you!

**Comment by pimeys** [comment]
Hey, you are running this on Azure SQL, so they kind of enforce you to add the server name to the username.

The server name is in the hostname, so if you connect to `meowmeow.database.windows.net`, your server name is `meowmeow`. Now, with Azure, they want you to set your user as `user@meowmeow` instead of `user`, meaning the connection string would look like:

` DATABASE_URL="sqlserver://meowmeow.database.windows.net:3342;database=mydb;user=user@meowmeow;password=password;trustServerCertificate=true"`

Also, please be sure you set the Azure firewall correctly. You can find more info from [the redirection ticket](https://github.com/prisma/tiberius/issues/88).

**Comment by alexandra-c** [comment]
So we narrowed it down to one possible issue, which is that the client introspection is not working with Azure SQL Managed Instance. We made a few tests, and tried with both Azure SQL Database and Managed Instance, the first one works fine with @pimeys's suggestion, but the last one doesn't...
I'm very interested in this subject because i was eagerly waiting for the MSSQL connector for Prisma Client to promote Prisma in our company. I'm actually talking to my superiors about this for a year now 😊. 
I really hope you guys can find a solution for my issue, i'm willing to contribute if i can 😊.

**Comment by pimeys** [comment]
Would be great if @pantharshit00 could make a reproduction of this. We can maybe do it in the next sprint.

**Comment by janpio** [comment]
> So we narrowed it down to one possible issue, which is that the client introspection is not working with Azure SQL Managed Instance. We made a few tests, and tried with both Azure SQL Database and Managed Instance, the first one works fine with @pimeys's suggestion, but the last one doesn't...

Side note: The error message indicates that this is not a problem in Introspection, but before when it tries to the server. You would probably get the same error message when you run any other Prisma command or code after you manually created a `schema.prisma` file that represents the database schema.

But we will need to figure out why that is happening.

**Comment by pimeys** [comment]
Now when I'm digging into this, it feels like the [same issue](https://github.com/prisma/tiberius/issues/88) we have with redirection handling. When we solve this, we also can support redirection on Azure.
