### ISSUE TITLE
Prisma consumes 100% of cpu

### ISSUE THREAD

**Issue by LyhengTep** [prisma/prisma#4916]
**Describe the bug**
Prisma consumes 100% of CPU while there are only around 20 users in my office.

<img width="1537" alt="Screen Shot 2019-10-17 at 3 59 10 PM" src="https://user-images.githubusercontent.com/22426004/66995779-c094a200-f0f9-11e9-847c-1fb77b58ffbf.png">

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server:1.25
 - `prisma` CLI: [e.g. `prisma/1.24.0 (darwin-x64) node-v10.4.0`]
 - OS:Ec2 instance ubuntu 18.04 (vcpu 2 ram 8gb)

**Comment by raeesaa** [comment]
@LyhengTep Did you find any solution for this?
