### ISSUE TITLE
Where clause type generation

### ISSUE THREAD

**Issue by keonik** [prisma/prisma#4917]
## Bug description

TypeScript types for where clause limit to just id. I'm trying to use `upsert` to update or create a user and I am using the `where` clause to compare an incoming email address.

### Note

First experience using prisma, so I may be missing something. Hoping to get some much-needed help 🤞🏼 

## How to reproduce

1. Starter Next TS Project
2. npm install @prisma/cli typescript ts-node @types/node --save-dev 
3. Update tsconfig based on docs suggestions 
```json
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "lib": ["esnext"],
    "esModuleInterop": true
  }
}
```
4. npx prisma init
5. Create schema
```json
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model users {
  id               Int           @id @default(autoincrement())
  username         String
  position         String
  start_date       String
  email            String
  profile_pic      String
  slack_id         String
  manager          String
  onboarding_buddy String
  admin            Boolean       @default(false)
  created          DateTime      @default(now())
  updated          DateTime      @updatedAt
}
```
6. Create Tables using migrate 
```bash
npx prisma migrate dev --name init --preview-feature
```
7. Try to build upsert out
```ts
import { PrismaClient, usersCreateArgs } from '@prisma/client';

const prisma = new PrismaClient();

const upsertUser = (email: string) => {
  const record = {
    email,
    manager: 'Jane Doe',
    onboarding_buddy: 'John Doe',
    position: 'SE',
    profile_pic: '',
    slack_id: '',
    start_date: Date.toString(),
    username: email,
  };
  prisma.users.upsert({
    update: record,
    create: record,
    where: {
        // only id available
    }
  });
};
```
8. Investigate inputs generated
```ts
  export type usersWhereUniqueInput = {
    id?: number
  }
```

## Expected behavior

```ts
  prisma.users.upsert({
    update: record,
    create: record,
    where: {
         email: inputEmail
    }
  });
```
no ts errors. Problem child where clause 

## Workaround

Using findFirst to get an id. Weird that that one has access to email but the others don't right? I thought so at least

```ts
export async function updateUser(user: User) {
    const record: Prisma.usersCreateInput = {
        username: `${user.name}`,
        email: `${user.email}`,
        profile_pic: `${user.image}`,
    };
    const userFound = await getUser(`${user.email}`);

    if (!userFound) {
        const newUser = await prisma.users.create({ data: record });
        return newUser;
    }

    const result = await prisma.users.update({ data: record, where: { id: userFound.id } });

    return result;
}

export async function getUser(email: string) {
    const user = await prisma.users.findFirst({ where: { email: `${email}` } });
    return user;
}
```
## Environment & setup

- OS: Mac OS
- Database: PostgreSQL and  SQLite
- Node.js version: v12.18.3

@prisma/cli          : 2.14.0
@prisma/client       : 2.14.0
Current platform     : darwin
Query Engine         : query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.332.0

**Comment by williamluke4** [comment]
Hey @keonik, you just need to add `@unique` to your email field in your schema and then regenerate. 🙂

**Comment by keonik** [comment]
That worked! Thanks @williamluke4

**Comment by keonik** [comment]
That worked! Thanks @williamluke4
