### ISSUE TITLE
prisma deploy timeout

### ISSUE THREAD

**Issue by slg1** [prisma/prisma#4918]
I'm facing a 300s timeout issue when prisma deploy is executed with the following trace:

ERROR: GraphQL Error (Code: 503)\n\n{\n  \"error\": \**"The server was not able to produce a timely response to your request.**\\r\\nPlease try again in a short while!\",\n  \"status\": 503\n}\n\nGet in touch if you need help: https://www.prisma.io/forum/\nTo get more detailed output, run $ export DEBUG=\"*\"\n"

**Context:**
- database with 90000 items.
- schema is modified: optional field becoming mandatory

**Question**:
Is it possible to modify this 300s timeout in Prisma. If yes, how can I do it ?

Versions:

Postgres: 10.6
Prisma Server: 1.34.8
Prisma CLI version: prisma/1.34.8 (linux-x64) node-v8.15.0
OS: CentOS Linux 7
other dependencies: graphql-request 1.8.2

**Comment by ahmad2smile** [comment]
Prisma 1.30.0, facing same issues on Heroku 503
