### ISSUE TITLE
Error when querying the Node

### ISSUE THREAD

**Issue by t03jam8** [prisma/prisma#4931]
**Describe the bug**
An internal service error occurs when querying the node. 
```
prisma.node({id: "some users  id"})
```
This returns the error: 
```
Error: Could not find argument where for type Node
```

**To Reproduce**
Steps to reproduce the behaviour:
1. git clone https://github.com/t03jam8/prisma-bug.git
2. cd prisma-bug
3. yarn 
4. docker-compose up -d
5. npx prisma deploy // also seeds the DB 
6. yarn start 

**Expected behaviour**
prisma.node({id: "some id"}) should return the node with that id. 

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma: 1.34.10

**Additional context**
The recreated issue is on my personal Github however the problem is actually on our Kubernetes server for work. We want to implement a node resolver that will return any node in the DB where we have the id.

**Comment by sgwilym** [comment]
Have exactly the same issue here, seems strange that a core API like this doesn’t work.
