### ISSUE TITLE
N:M Relation over a table with two @relation(link: INLINE)

### ISSUE THREAD

**Issue by alber70g** [prisma/prisma#4932]
Not sure if it's a bug or something that's just impossible, _or_ I'm doing something wrong.

I'd like to create a N:M relation based on a tables' content. I've used [these docs](https://www.prisma.io/docs/datamodel-and-migrations/datamodel-MYSQL-knul/#relation-table) that shows how to use @relationTable

User 1:N Item
- User has n Items
- Item has 1 Owner

Item 1:n Product
- Item can be 1 product
- Product can be n Items

Product N:M Owners
- Product _can_ have owners over Item.product and Item.owner
- Owners _can_ have Products (if a Product is linked) over Item.owner and Item.product

I tried to make this happen, but it doesn't seem to work.

Am I doing something wrong here or is this not supported?

```graphql
type User {
  id: ID! @id
  items: [Item!]! @relation(name: "OwnerRelation")
}

type Item @relationTable {
  id: ID! @id
  owner: User! @relation(link: INLINE, name: "OwnerRelation")
  product: Product @relation(link: INLINE, name: "ItemProductRelation")
}

type Product {
  id: ID! @id 
  items: [Item!]! @relation(name: "ItemProductRelation")
  
  # this N:M from Product > Item.product - Item.owner > User doesn't work
  owners: [User!]! @relation(link: TABLE, name: "Item")
}

```

**Comment by avansteijn** [comment]
Have had some similar issues and thoughts when I tried to convert the same mechanics from Prisma1 to Prisma2. Found that your problem might be in your last @relation. If there are issues in Prisma1 I think you must find a way around the @relation(link: TABLE, name: "Item")

But... although it might be too risky for your current project, I would suggest to test your model in Prisma2 (or Photon). Just use this model, it seems to work according to your needs. Make sure to use the latest Beta version.

`generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model User {
  id            String      @default(cuid()) @id
  items         Item[]      @relation(name: "OwnerRelation")
}

model Item  {
  id            String      @default(cuid()) @id
  owner         User        @relation(name: "OwnerRelation")
  product       Product     @relation(name: "ItemProductRelation")
}

model Product {
  id            String      @default(cuid()) @id
  items         Item[]      @relation(name: "ItemProductRelation")
  owners        User[]      
}`
