### ISSUE TITLE
Duplicated unique constraint name leads to unexpected panic during migration

### ISSUE THREAD

**Issue by farisk** [prisma/prisma#4934]
## Bug description
If repeat the name of a constraint twice I get the following error:
Oops, an unexpected error occured!
Error in migration engine.
Reason: [libs/datamodel/core/src/transform/ast_to_dml/validate.rs:226:34] called `Option::unwrap()` on a `None` value

Rather than some nice error message.

## How to reproduce
1. Create a schema  like so
```
model User {
    id String @id @default(uuid())


}
model UserConfig {
    id String @id @default(uuid())
    userId String
    User     User   @relation(fields: [userId], references: [id])
     @@unique([userId], name: "userId_fkey")
}
```

2. Create the initial migration, run it.
3. Add the following to the schema:
```
model UserSubscription {
    id String @id @default(uuid())
    userId String
    User     User   @relation(fields: [userId], references: [id])
     @@unique([userId], name: "userId_fkey")
}
```
4. Create and run the migration. 
yarn run prisma migrate dev --name add_subscription_table --preview-feature

and you will get a error that looks like a rust panic like so:
```
Oops, an unexpected error occured!
Error in migration engine.
Reason: [libs/datamodel/core/src/transform/ast_to_dml/validate.rs:226:34] called `Option::unwrap()` on a `None` value

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/prisma/issues/new
````

## Expected behavior
A nice error message that tells you that it is erroring because a constrain name is already taken.

## Prisma information
Prisma version 2.14

## Environment & setup

- OS: Linux
- Database: postgresql
- Node.js version: 15
- Prisma version:

```
@prisma/cli          : 2.14.0
@prisma/client       : 2.14.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.332.0
Done in 2.46s.
```

**Comment by pantharshit00** [comment]
I can confirm this panic. Thanks for reporting. 

Related: https://github.com/prisma/prisma/issues/4678

**Comment by tomhoule** [comment]
@farisk I tried to reproduce the crash with the current prisma version (2.19.0) and couldn't make it happen. Can you also confirm on your end that it is fixed?
