### ISSUE TITLE
Prisma go client cannot query nil values

### ISSUE THREAD

**Issue by chris-rock** [prisma/prisma#4936]
**Describe the bug**

Define a model like:

type Test {
  id: ID! @id
  lastDate: String
}

where last date can be a string or null. Prisma's graphql queries to the database work without any issue:
```
{
  testConnection(
    first: 10,
    where: {   
      lastDate: null
    }
  ) {}
}
```

You cannot query the same results from the go client

**To Reproduce**

see above

**Expected behavior**

null values can be queried via go

**Screenshots**
n/a

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.34
 - `prisma` CLI: n/a
 - OS: n/a
 - other dependencies: `prisma-client`, `prisma-binding`, etc. if applicable

**Additional context**
n/a

**Comment by timotew** [comment]
String can't be `nil` you should try `""`.

**Comment by chris-rock** [comment]
If you define the `lastDate: String`, it can have null, "" and a filled string. The generated prisma go client does not generate the correct graphql query. Therefore "" will only return empty strings but not the null elements.
