### ISSUE TITLE
Prisma deploy not working after changing the field type in the graphql schema

### ISSUE THREAD

**Issue by Foxford13** [prisma/prisma#4937]
After adding a new table into our schema i started getting  warnings on our staging server.
```  LegacyGraph
    ! You already have nodes for this model. This change may result in data loss.
    ! You are changing the type of a required field. The fields will be pre-filled with the value: ``.
```
After using --force command prisma claimed to have created the tables,  however, the database was left untouched and still with the old schema. It turned out that the issue was not related  to the new table, but to a field that used to have UUID type that got changed into a String a while back. There was no information about why it could be failing from prisma and it required some heavy digging to figure out what was the problem.

**To reproduce** 
1. Have a column in the database that has a type set to UUID in the schema  and have some entries for it.
2. Change the type of the column in datamodel.graphql to String.
3. Run 'prisma deploy' to get the the the warnings, then run 'prisma deploy --force' to see the message that tables were created.

**Expected behavior**
What I would expect to happen would be a more detailed warning what the issue is about.
What fields might be affected or why there might be a an issue. Also, after having used '--force' argument I do not feel that prisma should claim that it has created table if its clearly failing at some point.

**Versions (please complete the following information):**
 - Connector: postgres 10.6
 - Prisma Server: 1.34.8.
 - other dependencies: docker 18.06.1-ce

**Comment by digitalhank** [comment]
Also experiencing something similar. After changing a field from [String!]! to [Json!]! (and successfully deploying with --force flag) the field is broken and just returns null and 
`Whoops. Looks like an internal server error`. Running prisma reset didn't help.

**Comment by omarragi** [comment]
@Foxford13  
I have an integer field  and I decided to convert it to astring, any clue how to achieve this without breaking things?

- I was planning to copy value to a temporary field
- delete old one 
- create it back
- copy from temp to the new
- delete temp
any easier method?
