### ISSUE TITLE
Can I use prisma instead of Apollo?

### ISSUE THREAD

**Issue by YankeeTube** [prisma/prisma#4939]
I understood that Prima and Apollo were playing different roles.
But we also understood that prisma can perform gql through servers and clients.

1. Is it necessary to introduce apolo?
2. how to use prisma client on nuxt or vue?

**Comment by SergeiMeza** [comment]
Prisma is used to bind your database to your server. 
On the other hand, Apollo is used to bind your server to your client.

1. If you want to do some adjustments to your data on your server before saving to your database I recommend you to use Apollo with Prisma.
2.  You can use Prisma client to save data directly to your database from your client. In this way, your Prisma endpoint would be exposed though. It is good when prototyping or in early development. For production, I'd recommend using Apollo with Prisma

**Comment by YankeeTube** [comment]
Thank you @SergeiMeza! I realized about this but I forgot to close issue.
