### ISSUE TITLE
Connecting to existing mysql database with prisma is not working. Unable to add or retrieve the data using Graphql

### ISSUE THREAD

**Issue by kans-vine** [prisma/prisma#4944]
**Describe the bug**
I have been connecting to existing mysql database with prisma. I have generated the datamodel and schema.js everything using prisma configuration. However, when I try to insert the data to the database, I am getting an below error in the api resonse:

 "message": "Variable '$_data' cannot be non input type 'MigrationCreateInput!'. (line 1, column 19):\nmutation ($_data: MigrationCreateInput!) {\n                  ^",

**Expected behavior**
I should be able to insert the data into the database

**Docker logs**
No log level set, defaulting to INFO.
[INFO] {} - Starting...
[INFO] {} - Start completed.
[INFO] {} - Starting...
[INFO] {} - Start completed.
[INFO] {} - Shutdown initiated...
[INFO] {} - Shutdown completed.
[INFO] Obtaining exclusive agent lock...
[INFO] Obtaining exclusive agent lock... Successful.
[INFO] Initializing workers...
[INFO] Successfully started 1 workers.
[INFO] Deployment worker initialization complete.

**Versions (please complete the following information):**
 - Connector: MySQL, 
 - Prisma CLI version: prisma/1.34.10 (darwin-x64) node-v10.16.0
 -  Prisma server version: 1.34.10
 - OS: OS X High Sierra
 - Node 10.16.0 with React + Typescript
 

**Additional context**
**docker-compose.yml**
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: myhost
            user: myusername
            database: mydatabasename
            password: password
            rawAccess: true
            port: 3306
            migrations: true

**prisma.yml**

endpoint: http://localhost:4466
datamodel: datamodel.prisma

generate:
  - generator: typescript-client
    output: ./generated/prisma-client/

I have both prisma-schema.ts and index.ts file under /generated/prisma-client directory

**Below is the snippet code which I am using to create the data in the db:**

import { prisma, MigrationCreateInput } from '../../generated/prisma-client';

**export const demo = async () => {
    const migrationInput: MigrationCreateInput = {
        migration: "Helllo"
    }
    const newMigration = await prisma.createMigration(migrationInput);
    console.log(newMigration);
}**

**Comment by AlexanderProd** [comment]
I've noticed this as well, Prisma ignores the defined database name. It always tries to connect to the default database called `prisma`.
