### ISSUE TITLE
Multiple (almost) identical SELECT statements

### ISSUE THREAD

**Issue by mhwelander** [prisma/prisma#4947]
## Bug description

When you `deleteMany`, there are multiple `SELECT` statement that *look* as though they're doing the same thing.

Internal context: https://prisma-company.slack.com/archives/CEYCG2MCN/p1610373011220500

## How to reproduce

This query:

```
  const deleteUsers = await prisma.post.deleteMany({
    where: {
      id: {
        in: [7, 8, 9, 10]
      }
    }
  })
```

Outputs this to logs:

```
{
  timestamp: 2021-01-11T13:46:47.196Z,
  query: 'BEGIN',
  params: '[]',
  duration: 1,
  target: 'quaint::connector::metrics'
}
{
  timestamp: 2021-01-11T13:46:47.201Z,
  query: 'SELECT "public"."Post"."id" FROM "public"."Post" WHERE "public"."Post"."id" IN ($1,$2,$3,$4) OFFSET $5',
  params: '[7,8,9,10,0]',
  duration: 3,
  target: 'quaint::connector::metrics'
}
{
  timestamp: 2021-01-11T13:46:47.204Z,
  query: 'SELECT "public"."Post"."id" FROM "public"."Post" WHERE "public"."Post"."id" IN ($1,$2,$3,$4)',
  params: '[7,8,9,10]',
  duration: 3,
  target: 'quaint::connector::metrics'
}
{
  timestamp: 2021-01-11T13:46:47.207Z,
  query: 'DELETE FROM "public"."Post" WHERE "public"."Post"."id" IN ($1,$2,$3,$4)',
  params: '[7,8,9,10]',
  duration: 2,
  target: 'quaint::connector::metrics'
}
{
  timestamp: 2021-01-11T13:46:47.210Z,
  query: 'COMMIT',
  params: '[]',
  duration: 2,
  target: 'quaint::connector::metrics'
}
```

There are two `SELECT` statements that do the same thing, but one includes an (unused) offset. 

## Environment & setup

- Database: PostgreSQL

**Comment by pantharshit00** [comment]
I can also reproduce this. Might be a bug in the logger. I will mark it is as confirmed and let someone who works on that part have a look.

**Comment by timsuchanek** [comment]
It may look weird, but this is working as intended.

**Comment by dpetrick** [comment]
We are aware of a lot of optimization opportunities and rest assured it _will_ be addressed. We'll open epics when the time is right.
