### ISSUE TITLE
Change parameter type of prisma.$transaction

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#4949]
## Problem

The parameter of `prisma.$transaction` is `any[]`.

## Suggested solution

 I think it would be great if this would be changed to a type to only accept prisma client promises.

**Comment by millsp** [comment]
https://gist.github.com/millsp/7fe06273f9350908b0fdcc025e08eefe

**Comment by williamluke4** [comment]
Thank you @millsp, You are a wizard :mage:
