### ISSUE TITLE
Subscriptions don't show relations in updatedFields

### ISSUE THREAD

**Issue by Hitabis** [prisma/prisma#4958]
Subscriptions don't fire updatedFields on relations. **Only tested in Mongo**.
(updatedFields_contains in where also don't work with relation fields)

**To Reproduce**
This model given
```
type A {
  id: ID! @id
  name: String!
}

type B {
  id: ID! @id
  name: String!
  a: A  @relation(link: INLINE)
}
```
this subscription
```
subscription {
  b {
    mutation
    updatedFields
    node {
      name
      id
    }
  }
}
```
fires  on an update of a given b
```
mutation {
  updateB(
    where: { id: "5de9149dd06a490007fe2ffe" }
    data: {  a: { connect: { id: "5de91631d06a490007fe3000" } } }
  ) {
    id
  }
}
```
with empty `updatedFields`
```
{
  "data": {
    "b": {
      "mutation": "UPDATED",
      "updatedFields": [],
      "node": {
        "name": "B",
        "id": "5de9149dd06a490007fe2ffe"
      }
    }
  }
}
```

**Expected behavior**
The subscription message schould be `"updatedFields": ["a"]`

Or is there any workaround for this? I need this information.

**Comment by Hitabis** [comment]
Please don't close this issue stale-bot

**Comment by HugoLiconV** [comment]
Same problem!

**Comment by Hitabis** [comment]
Please don't close this issue stale-bot

**Comment by borasumer** [comment]
I always get empty updatedFields array as well, not sure what is going on.
