### ISSUE TITLE
Automatically add server name to the username when connecting to Azure SQL

### ISSUE THREAD

**Issue by 2color** [prisma/prisma#4961]
## Problem

When users try to connect to an Azure SQL, they must add the server name to the username in the connection URL. 

For example, the following won't work:
```
DATABASE_URL="sqlserver://meowmeow.database.windows.net:3342;database=mydb;user=user;password=password;trustServerCertificate=true"
```

Instead, it should be:
```
DATABASE_URL="sqlserver://meowmeow.database.windows.net:3342;database=mydb;user=user@meowmeow;password=password;trustServerCertificate=true"
```

## Suggested solution

As suggested by @pimeys, we should automatically detect if you're trying to connect to Azure SQL in quaint, and if so, add the database name to the username. 

This is in line with the JDBC driver which does this too.

## Additional context

Related issue: https://github.com/prisma/prisma/issues/4916
Related discussion: https://prisma-company.slack.com/archives/C0110LHCCDB/p1610379428147800

**Comment by pimeys** [comment]
Yeah, we should do this. But due to migrate/native types GA I'd drop it from this sprint and implement it next week?

**Comment by pimeys** [comment]
We might not need this anymore. See: https://github.com/prisma/tiberius/pull/122

**Comment by 2color** [comment]
@pimeys Can we close this then?

**Comment by pimeys** [comment]
I think so. Let's re-open if we get reports from users.

**Comment by janpio** [comment]
Which version was this released? Please assign the Milestone to this issue so we can understand in the future when exactly this happened.

**Comment by srigi** [comment]
Will be the **tiberius** patch available to Javascript users?
