### ISSUE TITLE
Weird required array typing

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#4964]
## Bug description
Currently the typing for a **required** array is:
```typescript
type CalendarEventCreateattendeesInput = {
    set: Enumerable<InputJsonValue>
  }

type CalendarEvent {
  ...
  attendees?: CalendarEventCreateattendeesInput | Enumerable<InputJsonValue>
}
```

## Expected behavior

The typing should be: 
```typescript
type CalendarEventCreateattendeesInput = {
    set: Enumerable<InputJsonValue>
  }

type CalendarEvent {
  ...
  attendees: CalendarEventCreateattendeesInput | Enumerable<InputJsonValue>
}
```

## Environment & setup

- OS: MacOs
- Database: PostgreSQL
- Node.js version: 14
- Prisma version: 2.14.0

**Comment by timsuchanek** [comment]
Thanks for reporting! Just candidated it, we can have a look next sprint.

**Comment by Sytten** [comment]
It seems correct since the generated mutation is a nullable array column.
So it's a deeper issue than just typing.

**Comment by timsuchanek** [comment]
@Sytten could you provide the schema and the mutation you want to call? That would help us looking into it.

**Comment by Sytten** [comment]
The root cause is that all arrays are nullable in prisma, which arguably is a bug (already reported elsewhere). This is not specific to my schema.

**Comment by pantharshit00** [comment]
List being nullable got patched here today: https://github.com/prisma/prisma/issues/4808

**Comment by Sytten** [comment]
Did it get patched in the migration engine? Aka will it trigger an alter table for existing arrays.

**Comment by pantharshit00** [comment]
No, this is just a DMMF change.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/client`.
You can try it out with `npm i @prisma/client@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
