### ISSUE TITLE
Is it possible to declare multi-dimensional array in Prisma?

### ISSUE THREAD

**Issue by Riseley** [prisma/prisma#4965]
I am not sure if this is a bug or missing feature.

From here:
https://github.com/MichalLytek/type-graphql/issues/277
and
https://github.com/graphql/graphql-spec/issues/423
it seems that it is possible to declare multi-dimensional array in GraphQL.

However, when I tried to do this
`type SomeType {
    someField: [[String]] @scalarList(strategy: RELATION)
}`
 in datamodel.prisma, Prisma simply changes it to [String].

If it is already [String] and you change to [[String]], it will completely disregard the change and say Prisma is already up-to-date without giving any warning.

**Comment by HumbertoAriza** [comment]
You can create a new type that contain the type objects that you want and create an array of that new type that you recently created. Now you have your multi-dimensional array
