### ISSUE TITLE
`prisma migrate reset` fails if the db is not already initialized

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma#4974]
## Bug description

`prisma migrate reset` fails if the db is not already initialized. This is a problem because this reset command is heavily used in test environments on the test DB. The test DB may or may not exist. And currently if it doesn't, this command fails.

So now we have to run `prisma migrate dev && prisma migrate reset` in our test scripts which just isn't great 😅 

## How to reproduce

1. Run `prisma migrate reset` in a project without the database set up

## Expected behavior

Should not fail on the first step (delete DB), and then continue on with setting up a new clean DB.

## Prisma information

Prisma 2.14.0

**Comment by Jolg42** [comment]
The current `migrate reset` command only checks if it can connect to the database but does not create it.

These commands create the database if it does not exist:
- `db push`
- `migrate deploy`
- `migrate dev`

It could make sense to to that here too, thanks for the issue!

**Comment by flybayer** [comment]
That was fast 🔥🔥🔥🔥🔥
