### ISSUE TITLE
”Could not connect to server at http://localhost:4466. ” while deploying prisma

### ISSUE THREAD

**Issue by yiruka114514** [prisma/prisma#4976]
```
!    Could not connect to server at http://localhost:4466. Please check if your server is running.

Get in touch if you need help: https://slack.prisma.io
To get more detailed output, run $ export DEBUG="*"
(node:10252) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```
**Describe the bug**
I tried to connect existing MySQL database. When I execute command like ` prisma deploy`, it threw out that error. And I have checked that my docker container was running on port 4466. 

**Steps to reproduce the behavior:**
```
? Set up a new Prisma server or deploy to an existing server? Use existing database
? What kind of database do you want to deploy to? MySQL
? Does your database contain existing data? Yes
? Enter database host localhost
? Enter database port 3306
? Enter database user root
? Enter database password [hidden]
Introspecting database test 148ms
Created datamodel definition based on 10 tables.
? Select the programming language for the generated Prisma client Prisma JavaScript Client
```
`cd ppppp`
`docker-compose up -d`
`prisma deploy`

**Versions (please complete the following information):**
 - Connector: MySQL
Prisma CLI version: prisma/1.34.10 (windows-x64) node-v12.13.1
Prisma server version: 1.34.10
 - OS: Windows 10
 
How to solve this problem???

**Comment by hcmuleva** [comment]
> To get more detailed output, run $ export DEBUG="*"

This could be due to proxy issue. In my office network it does not allowed . So I removed proxy and connected with personal network. I am able to connect.

**Comment by yiruka114514** [comment]
@hcmuleva I knew what caused this problem now. It is the configuration in docker docker-compose.yml. `schema` should be changed into `database`. lol
