### ISSUE TITLE
The slack invite form and slack.prisma.io seems to be down

### ISSUE THREAD

**Issue by mruzekw** [prisma/prisma#4985]
Not loading: https://slack.prisma.io/

Slack invite form doesn't work: https://www.prisma.io/community/

**Comment by andersonba** [comment]
It is loading now but it doesn't work.
I'm not receiving the invitation email, I tried with my personal/work email but none arrive.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/1501013/72038551-bc5fc700-3299-11ea-8746-b89ab7b2184a.png">

**Comment by aliahmad-code** [comment]
Running into the same issue too.
