### ISSUE TITLE
Migrating from old datamodel syntax warning

### ISSUE THREAD

**Issue by thesubway** [prisma/prisma#4986]
Note that I hadn't deployed in several months, so I am behind on the latest changes.

I ran
$ prisma deploy

and received the following warning:

  Global
    ! You are migrating from the old datamodel syntax to the new one. Make sure that you understand the listed changes because the semantics are different now. Then perform the deployment with the `--force` flag.

So if I force a deployment, will my server calls still work? I have not changed the code in my server.js file recently.

**Comment by sapkra** [comment]
When you've migrated the datamodel correctly they will still work or you can just use `prisma deploy --no-migrate` I guess.

You can find more information here:
https://www.prisma.io/docs/1.31/releases-and-maintenance/features-in-preview/datamodel-v11-b6a7/#upgrading-to-datamodel-v11

PS: I would double check the changes which are generated by the `prisma introspect` command.
