### ISSUE TITLE
Grouping by required fields should be not have nullable output type

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4987]
## Problem

```prisma
type User {
  id Int @id
  name String
}
```

```ts
const user = prisma.user.groupBy({
  by: ['name']
})
user[0].name // string | null

```

## Suggested solution

If `name` can't be null in the schema, then the name field in the result set can't be null. It should be:

```ts
user[0].name // string
```

## Original Ticket

#4893

**Comment by pantharshit00** [comment]
I was about to open this same bug report 😅. I can confirm this.

**Comment by timsuchanek** [comment]
Fixed in latest `dev` version
