### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#4989]
```ts
for await (const post of prisma.posts().$stream()) {
  console.log(post)
}

const postStreamWithPageInfo = await prisma
  .posts()
  .$stream()
  .$withPageInfo()

for await (const posts of prisma.users
  .findOne('bobs-id')
  .posts({ first: 50 })
  .batch({ batchSize: 100 })) {
  console.log(posts) // 100 posts
}

// Configure streaming chunkSize and fetchThreshold
prisma.posts({ first: 10000 }).$stream({ chunkSize: 100, fetchThreshold: 0.5 /*, tailable: true*/ })

// Buffering
const posts = await prisma
  .posts({ first: 100000 })
  .$stream()
  .toArray()

// Shortcut for count
const userCount = await prisma.users.count({
  where: {
    age: {
      gt: 18,
    },
  },
})
```

**Comment by kn0ll** [comment]
is it premature for comment? this would have saved my team a lot time from writing custom implementations! db/sql is not my strong point so please forgive any silly questions...

1. what is the default behavior for chunking? my understanding is that chunking is not really native to streams, and is probably almost a side effect of interacting with a DB as your primary data source? in my experiments, it wasn't really obvious what the optimal chunk size for some given task, and it seemed like there were "sweet spots" you had to find. i also know prisma is database ambiguous, but i'm wondering if it could be optimized if the db has something like [single-row-mode](https://www.postgresql.org/docs/9.2/libpq-single-row-mode.html)?

2. assuming i can do standard `where` type clauses on a stream query, how will the stream behave if i mutate results? so if i stream `20 where foo = 'bar' limit 10 order by id asc`... while updating `foo` inside the result handler? will that end up changing the results returned by the stream later on?

2.

**Comment by janpio** [comment]
Closing as duplicate of https://github.com/prisma/prisma/issues/5055
