### ISSUE TITLE
Thoughts regarding namings

### ISSUE THREAD

**Issue by siberian-man** [prisma/prisma#4994]
Instead of 'Where' you could use 'Criteria', and instead of 'WhereUnique' - 'Identifier'. Sounds better in my opinion. E.g. UserCriteriaInput and UserIdentifierInput. UserWhereInput and UserWhereUniqueInput sounds a little bit confusing. Nouns are, probably, clearer. I suppose, you decided to use 'Where', because it is used by relational databases, in SQL. But since you are going to support other databases, it doesn't matter. In neo4j there is no 'Where' clause, for example.

**Comment by timsuchanek** [comment]
Thanks for sharing the idea.
This would be a breaking change, that we don't want to introduce anymore, as we are already in GA with Prisma Client.
