### ISSUE TITLE
Order by related fields

### ISSUE THREAD

**Issue by rohitghatol** [prisma/prisma#4996]
Example: a User has many Posts. Should be possible to order the Posts by User name.

Maybe:

```
query {
  allPosts(orderByRelated: [user_name_ASC]) {
    id
  }
}
```

Copy of https://github.com/prisma/prisma1/issues/95

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/5008 as it has more reactions.
