### ISSUE TITLE
weird behaviour with filter 

### ISSUE THREAD

**Issue by ahmedB7r** [prisma/prisma#4996]
**Describe the bug**
when I filter my records and need first 10 it gave me 5 and the count is more than 17000 and in my DB I only have 3000 records!!!

**To Reproduce**
make this query
![image](https://user-images.githubusercontent.com/47532216/72434546-90b27480-37a4-11ea-935e-2c7782677a8e.png)

**Expected behavior**
I expected to filter my records and gave me the first 10
**Screenshots**

**Versions (please complete the following information):**
 - Connector: [ `MongoDB`]
 - Prisma Server: [e.g. `1.34.0`]
 - `prisma` CLI: [e.g. `prisma/1.34.0 (darwin-x64) node-v10.4.0`]
 - OS: [ `Ubuntu 16.04`] 
 - other dependencies: `prisma-client`, `prisma-binding`, gave me same results with the both

**Comment by omarragi** [comment]
Plus 1
