### ISSUE TITLE
Add support for 64-bit integers

### ISSUE THREAD

**Issue by nickreynke** [prisma/prisma#5001]
**Problem**

Lots of database support 64-bit integers. We don't support them yet because not all databases support them. 

**Possible Solution**

In the databases that support 64-bit integers, we add [datasource-specific attributes](https://github.com/prisma/prisma/issues/194) to define 64-bit types.

> **Original Issue**
> 
> Prisma1 did not support `Long` integers (64-Bit). Will Prisma2 support `Long` (64-Bit) in parallel to `Int` (32-Bit)?

**Comment by pantharshit00** [comment]
You can now query BigInts in the native types preview: https://www.prisma.io/docs/concepts/components/preview-features/native-types#additional-prisma-types

I will keep this open as migrate still need native type support.

**Comment by timsuchanek** [comment]
Closing as it can be achieved like @pantharshit00 noted.
