### ISSUE TITLE
[BREAKING CHANGE] Disconnect/connect (for relations) throws errors needlessly

### ISSUE THREAD

**Issue by jhalborg** [prisma/prisma#5005]
## Problem

Currently when you try to connect or disconnect relationships, you need to be needlessly cautious that you haven't done it before, otherwise the command will throw.

It's weird that it throws, seeing as the state of the data afterwards is as the request wanted it in the first place anyway.

Here's an example:

```ts
await prisma.user.update({
    where: {
      id: 'u123',
    },
    data: {
      Post: {
        connect: {
          id: 'p123',
        },
      },
    },
  })

// will throw
await prisma.user.update({
    where: {
      id: 'u123',
    },
    data: {
      Post: {
        connect: {
          id: 'p123',
        },
      },
    },
  })
```

The same applies for disconnect.

**Additional Context:** https://prisma.slack.com/archives/CKQTGR6T0/p1568120850240700?thread_ts=1567958862.225000&cid=CKQTGR6T0

## Suggested Solution

Don't throw. Allow connects and disconnects to either apply the change or ignore the action.

**Comment by matthewmueller** [comment]
Next Step:

- Check that this works

**Comment by matthewmueller** [comment]
This now works, if you try to connect an already connected relation, it's a no-op.
