### ISSUE TITLE
Managing DB connections for Prisma Client JS (e.g. in serverless environments)

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#5007]
The query engine that's powering the Prisma Client JS API is maintaing a database connection pool. In serverless environments (or when running your application in containers, e.g. using Kubernetes), this connection pool might loose its effectiveness due to the infrastructure it's being deployed on. You can read more about this topic in the [docs](https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/deployment.md).

As of now, the recommended workaround is to use a tool like [PgBouncer](https://pgbouncer.github.io/faq.html). We are further exploring some options, such as [enabling a "DB proxy server"](https://github.com/prisma/prisma2/issues/370) (e.g. using a specific generator that generates a Docker image to host Prisma's query engine) that manages the connection pool for you (similar to the the Prisma 1 architecture).

Also note that there some cloud offerings start to have solutions for connection pooling out-of-the-box, such as [AWS Aurora Serverless (Data API)](https://aws.amazon.com/blogs/aws/new-data-api-for-amazon-aurora-serverless/).

**Comment by PierreCrb** [comment]
```
import { PrismaClient } from '@prisma/client'

let prisma: PrismaClient

try {
  if (process.env.NODE_ENV === 'production') {
    prisma = new PrismaClient()
  } else {
    if (!global.prisma) {
      global.prisma = new PrismaClient()
    }
    prisma = global.prisma
  }
} finally {
  prisma.$disconnect()
}

export default prisma
```
This works for me ! 🥳

**Comment by matthewmueller** [comment]
We just wrote some new documentation on how to use Prisma in serverless environments: https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#serverless-environments-faas

I'm going to close this issue because it's a bit broad, if you have more specific problems with serverless, please open new issues!

**Comment by dborstelmann** [comment]
I'm having a similar issue where even on a local db using serverless offline the time to instantiate prisma client on first request (and subsequent requests) is like 1-2 seconds.  It should be like basically negligible (and is for me on other projects using serverless in production).  This is on a greenfield app with one empty database table.  My old projects use yoga but I switched to apollo-server-lambda for this one which is failing.  Apollo-server plain works fine.

It's the same amount of latency whether I store prisma in the context or just import the global and use it in a resolver.  It makes things quickly overflow in prod, but even running locally it's unbelievably slow (and if you use apollo studio explorer where it polls every second it overloads).

It also doesn't seem to be reusing the connection.  Here is running 3 queries in a row right after each other:
```
offline: POST /local/api (λ: graphql)
prisma:info Starting a postgresql pool with 1 connections.
prisma:query SELECT "public"."Location"."id", "public"."Location"."createdAt", "public"."Location"."updatedAt", "public"."Location"."name" FROM "public"."Location" WHERE 1=1 OFFSET $1
[]
offline: (λ: graphql) RequestId: ckvlyo79g0002a3956o6850jb  Duration: 1099.52 ms  Billed Duration: 1100 ms

offline: POST /local/api (λ: graphql)
prisma:info Starting a postgresql pool with 1 connections.
prisma:query SELECT "public"."Location"."id", "public"."Location"."createdAt", "public"."Location"."updatedAt", "public"."Location"."name" FROM "public"."Location" WHERE 1=1 OFFSET $1
[]
offline: (λ: graphql) RequestId: ckvlyoc730005a3955yye1fk7  Duration: 1024.40 ms  Billed Duration: 1025 ms
^[[D^[[C^[[C
offline: POST /local/api (λ: graphql)
prisma:info Starting a postgresql pool with 1 connections.
prisma:query SELECT "public"."Location"."id", "public"."Location"."createdAt", "public"."Location"."updatedAt", "public"."Location"."name" FROM "public"."Location" WHERE 1=1 OFFSET $1
[]
offline: (λ: graphql) RequestId: ckvlyofhr0008a3959gtd3hwx  Duration: 1024.67 ms  Billed Duration: 1025 ms
```
If I comment out the line with the prisma.location.findMany() from my code it drops to 125ms for the whole query.  The database table is empty and on my machine lol, I can't figure this out for the life of me.

**Comment by janpio** [comment]
@dborstelmann Please open a separate issue or discussion for this so we can properly debug without notifying all the people that previously interactive with this now closed issue. Thanks.

**Comment by MateusPitura** [comment]
Sorry for re-sending message to a closed issue. For people looking for how to apply @brandonweiss' solution using PrismaService:
```
export class PrismaService extends PrismaClient implements OnModuleInit {
  private prisma: PrismaClient;

  constructor() {
    super();
    if (process.env.NODE_ENV === 'production') {
      this.prisma = new PrismaClient();
    } else {
      if (!global.prisma) {
        global.prisma = new PrismaClient();
      }
      this.prisma = global.prisma as PrismaClient;
    }
  }
}
```
