### ISSUE TITLE
Reflection (Dynamic code on the fly in-memory)

### ISSUE THREAD

**Issue by KrishnaPG** [prisma/prisma#5009]
Was reviewing the tutorials and documentation. Somewhere ( [here ](https://www.prisma.io/blog/announcing-prisma-2-zq1s745db8i5)) it is indicated as 'next-gen' database access framework, replacing ORMs. Which is fine, honestly, but given the current work-flow, I would not consider it as next-gen, since except for the code-generation (from schema) part everything else seem to be same as the "old generation" (ORM).

To illustrate the point, consider the below:

- User creates a schema and generates the client code.
- Now, the code that was generated is just ORM code for schema objects / classes. For any CRUD operations specific to the App, user still has to write the code that accesses the entities in the schema (e.g. `await prisma.user({ id: '<USER_ID>' })` etc.)

The problem with this approach is, if the names of the fields or tables change in the schema, the user has to comeback and still change his query code in the App (apart from the usual recompiling and regenerating ORM layer).

This is not the ideal solution. Since the human-written code is still tied to the schema directly (despite the presence of machine-generated code, which should have abstracted away that dependency, but is not doing currently).

Rather, what is required, for something to be called next-generation, is:

- Complete separation from schema to the App access code

i.e. changing the schema should **not** require any change to the app code (only regenerating the middleware / ORM client part should be enough).

An example ideal flow for a next-generation DB access middleware is:
- Accept schema as string input (say, from a web text-box, or file read content from disk or network)
- Convert the schema into middleware accessor functions (in-memory), returning an object with callable functions (e.g. CRUD functions)
- User provides the queries as string input (again, from html text-box or file content or network io, or dynamically constructed from web ui controls), and executes the queries against one of those compiled functions available from the schema CRUD
- The result rows/data is bound to the HTML UI with dynamic component binding in Vue/React, or saved to file or written out network IO

The idea is that no where in the flow the app should be aware of what the names of the tables are, or the fields are, or the data source or query syntax. Changing any of them should not require changing the app code or db access code.

Achieving this may require some slightly innovative approach, such as adding the "list of possible queries" directly in the data model definition file (along with data source, types, user also specifies the queries in the definition file). The `types` in the definition file get mapped to ORM classes, and `queries` get mapped to executable functions that the app code can invoke (and the app will not be able to invoke anything beyond those queries, which is good for security / safety). A convention may be required to be able to discover / list the available queries / functions from the definition, dynamically at runtime for the app.

The syntax of the query specification in the definition file allows "variables" (which will be replaced by actual data values during the query function invocation, with safe-guards against query injection attacks).  Thus the query specification could be similar to GraphQL for complex queries (or follow the stored procedures standards). 

The bottomline is, user specifies the queries in the definition file, and not in the code. Hence everything related to data, i.e. the source, type, and queries stay in single place, and no need to change the app code when the definition file changes (only rebuilding the machine ORM layer should be enough).

**Comment by janpio** [comment]
Thanks @KrishnaPG, we - and most of our users - are quite happy how Prisma and Prisma Client work right now. But thanks for writing up your thoughts here in the past, that certainly triggered some thinking on our side back then.
