### ISSUE TITLE
Expressions using field names

### ISSUE THREAD

**Issue by milroyfraser** [prisma/prisma#5013]
```prisma
model Project {
    id           Int @id
    name         String?
    dueAt        DateTime
    completedAt  DateTime
}
```

How to query projects where `completedAt` > `dueAt`?

```
const projects = await photon.projects.findMany({
  where: {
    // ... ???
  }
})
```

**Comment by nikolasburk** [comment]
I think this issue could be closed as a duplicate of https://github.com/prisma/prisma/issues/5048 since #5084 seems to include this use case. cc @matthewmueller

**Comment by janpio** [comment]
This has been implemented in the meantime: https://www.prisma.io/docs/orm/reference/prisma-client-reference#compare-columns-in-the-same-table
