### ISSUE TITLE
Shorten/simplify client type signature for readability

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#5021]
The Prisma Client for JS/TS provides an extremely powerful type-safe API which enables a great developer experience and robust applications. However, there's also currently a flip-side to this which is that the way the type signature (for most operations) is constructed/formatted makes the API type signature quite "intimidating" and hard to read. Additionally it also massively reduces the visible space for our generated JSDocs to be displayed in editors (e.g. VSCode) as seen here:

![image](https://user-images.githubusercontent.com/1567498/73292710-d179a700-4202-11ea-9ca3-8e50caa57506.png)

I'd love to explore whether there are "better" ways (i.e. simpler/less characters) for us to layout the type signature (e.g. by using type aliases).

**Comment by pantharshit00** [comment]
It is much simpler now as return type is properly resolved now. 

![image](https://user-images.githubusercontent.com/22195362/104485050-050a3880-55f0-11eb-8b24-efc932eef901.png)


I am going to close this.
