### ISSUE TITLE
Task slick.basic.BasicBackend$DatabaseDef error

### ISSUE THREAD

**Issue by cfree** [prisma/prisma#5026]
# Bug Report
I cannot access the dev browser (in any of my workspaces) in the Prisma Admin nor can I access data from my app.

**Current behavior**
Whenever I log into the Prisma Admin and try to visit the data browser, the spinner never ceases to spin. In the console, there's a 500 error to a POST request at `https://us1.prisma.sh/four-players-co/four-players-co/dev`:
```
Uncaught (in promise) Error: {
  "message": "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@2850f5a4 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@cfc0ea7[Running, pool size = 1, active threads = 0, queued tasks = 1000, completed tasks = 497]",
  "requestId": "us1:ck743cdcw2i8i0b90jtm8xuar"
}
```

This is a prisma-us1 server (1.32.0-beta version) and the status says Healthy with 0 requests in the last hour.

I did a hard refresh a handful of times, only one of those times resulted in the data browser partially loading:

![Screen Shot 2020-02-27 at 1 53 20 PM](https://user-images.githubusercontent.com/1138762/75485883-c41e1c80-5968-11ea-9803-a73e6833986d.png)

The error message says `Connection unsucsessful, Incorrect access token provided.` but I don't know how to provide an access token for the Admin.

**Expected behavior**
I can access the data browser and my app can access data.

**Comment by gaudreaujacksoncharles** [comment]
+1 I am also experiencing this issue

**Comment by cfree** [comment]
Closing because this appears unrelated to the prisma package and the problem has finally been resolved.

> dpetrick:cloud:  4 hours ago  The US cluster has been upgraded to latest prisma1.

Ref: https://prisma.slack.com/archives/CA491RJH0/p1582769345086100
