### ISSUE TITLE
Provide pre-instantiated client instance as default export

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#5029]
Given that the instantiating a `new PrismaClient()` doesn’t have any side-effects (e.g. query engine is not starting yet etc) and that the vast majority of applications doesn’t have to configure the Client instance, I suggest to export a pre-instantiated PrismaClient instance as the default export.

This would remove the following line of code boilerplate from the majority of applications.

**Before**:

```ts
import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()
const result = await db.post.findMany()
```

**After**:
```ts
import db from '@prisma/client'

const result = await db.post.findMany()
```

Note that the previous syntax/use-case still is possible but usually is just used for advanced use cases.

**Comment by timsuchanek** [comment]
Closing this due to the reason mentioned in the previous comment.
