### ISSUE TITLE
Add update of non-existent node to known errors

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#5032]
For this Prisma Client code:
```ts
  const result = await client.user.update({
    where: {
      id: 123012938,
    },
    data: {},
  })
```

As of now, we get an error like this:

```
PrismaClientUnknownRequestError: 
Invalid `prisma.users.update()` invocation:

Error occurred during query execution:
InterpretationError("Error for binding \'0\': RecordNotFound(\"Record to update not found.\")")
```

We should add that to the known errors and return an error code.

**Comment by matthewmueller** [comment]
Next step: @timsuchanek double-check

**Comment by timsuchanek** [comment]
We now have this beautiful error:
```
An operation failed because it depends on one or more records that were required but not found. Record to update not found.
```

**Comment by Cretezy** [comment]
Is there a way to disable this error checking?

Our use case is an update, but it's possible the record doesn't exist (which would be a no-op). We don't care in this case that the record doesn't exist. Ideally, a argument to `update` such as `ignoreMissing` would be the solution here.

**Comment by PierreAndreis** [comment]
> Is there a way to disable this error checking?
> 
> Our use case is an update, but it's possible the record doesn't exist (which would be a no-op). We don't care in this case that the record doesn't exist. Ideally, a argument to `update` such as `ignoreMissing` would be the solution here.

I would like that as well, but does `updateMany` resolve this for you?

**Comment by elie222** [comment]
> We now have this beautiful error:
> 
> ```
> An operation failed because it depends on one or more records that were required but not found. Record to update not found.
> ```

Would be great to know which record is required.

**Comment by janpio** [comment]
@elie222 Open a new issue if non exists yet and we can take a look 👍

**Comment by vijay-rathod-relata** [comment]
Hi, is there any update on this feature request?

> Is there a way to disable this error checking?
> 
> Our use case is an update, but it's possible the record doesn't exist (which would be a no-op). We don't care in this case that the record doesn't exist. Ideally, a argument to `update` such as `ignoreMissing` would be the solution here.

**Comment by janpio** [comment]
This is a closed improvement from 3 years ago. If there is some feature missing, please open a new feature request that we can look into. Thanks.
