### ISSUE TITLE
A database name is required in the connection string for mysql

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma#5033]
### Description

Given the following datasource

```prisma
datasource db {
  provider = "mysql"
  url      = "mysql://root:mysql@localhost:4567"
}
```

The Prisma Client will fail when querying with the following error:

```
No database found in connection string
    at PrismaClientFetcher.request (/private/var/folders/wt/rlkwn4mn2872qwqjyykz191m0000gn/T/42370039614111343/mysql/node_modules/@prisma/client/index.js:92:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I believe it should use the default database when none in inputted (namely, `mysql`)

### Notes

- It does work with `prisma2 migrate` without a database name, and does migrate to the default `mysql` database

**Comment by pantharshit00** [comment]
We throw this error now with migrate which I believe sums it up why we shouldn't do this. I am going to close this:
![image](https://user-images.githubusercontent.com/22195362/117015602-84db2080-ad0f-11eb-8311-3720d982d01d.png)

**Comment by janpio** [comment]
What does Client do here? Seems like we are actually defaulting to `mysql` as the database, and only Migrate has a fail safe for that case - protecting the user from harm.

**Comment by pantharshit00** [comment]
@janpio Client doesn't throw anything and which is fine. It is alright to read from this table but it is not good to alter these tables like with migrate.
