### ISSUE TITLE
Add rejectOnNotFound to findOne/findFirst

### ISSUE THREAD

**Issue by mohsen1** [prisma/prisma#5047]
## Problem
Instead of returning a nullable result when calling `model.findOne`, accept a new argument (`rejectOnEmpty`) that makes the returning type non-nullable and throws an error when the row was not found

## Suggested solution

```ts
const person = await prisma.person.findOne({ where: { id } })

if (person) {
  // do stuff
}
```

Will be:

```ts
const person = await prisma.person.findOne({ where: { id }, rejectOnEmpty: true })

// do stuff
```

`rejectOnEmpty` will accept either boolean or an `Error` so the thrown error can be customized:

```ts
const person = await prisma.person.findOne({ 
  where: { id }, 
  rejectOnEmpty: new MyCustomNotFoundError(`person with id=${id} was not found`)
})
```

## Additional context

This API is stolen from Sequelize

**Comment by flybayer** [comment]
@timsuchanek I see `rejectOnNotFound` is added in `2.15.0`, but only for one-off invocations (vs setting globally during prisma client instantiation) and without the ability the customize the error, as described above.

Will those be coming in the next release? 🤔

**Comment by williamluke4** [comment]
Hey @flybayer, they should both possible in 2.15 for `findUnique` and `findFirst`. 

Passing in just a `rejectOnEmpty: new Error()` was removed in favour of  `rejectOnEmpty: () => new Error()`


```ts
// Sets the default behavior of findUnique
PrismaClient({rejectOnEmpty: true})
PrismaClient({
	rejectOnEmpty: () => new MyCustomNotFoundError(`person with id=${id} was not found`)
})
PrismaClient({
	rejectOnEmpty: {
		findUnique: true
	}
})
// Sets the default behavior of findUnique but only on specified models
PrismaClient({
	rejectOnEmpty: {
		findUnique: {
			  User:  () => new MyCustomNotFoundError(`person with id=${id} was not found`),
			  Post: true
		},
		findFirst: true
	}
})

// Allows you to set the behaviour on a per request basis 
await prisma.person.findUnique({ where: { id }, rejectOnEmpty: true })
await prisma.person.findUnique({ 
	where: { id }, 
	rejectOnEmpty:  () => new MyCustomNotFoundError(`person with id=${id} was not found`) 
})
```

**Comment by flybayer** [comment]
Ah, thanks!

Bummer it doesn't affect the result type yet. Waiting until that is fixed to use it.

**Comment by MaerF0x0** [comment]
For those looking for ^^ in 2023 it's been [deprecated](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#rejectonnotfound) and [replaced](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#findfirstorthrow)
