### ISSUE TITLE
PANIC: 1

### ISSUE THREAD

**Issue by cyrus-za** [prisma/prisma#5072]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.5.0            | 
| OS              | darwin             |
| Prisma Client   | 2.13.1             |

## Logs
```
prisma-client { clientVersion: '2.13.1' }
plusX Execution permissions of /Users/pieter/Invisible/invisible/node_modules/.prisma/client/query-engine-darwin are fine
plusX Execution permissions of /Users/pieter/Invisible/invisible/node_modules/.prisma/client/query-engine-darwin are fine
```

**Comment by timsuchanek** [comment]
As it's a duplicate of #995, we're closing this.
