### ISSUE TITLE
Add a `push` method to scalar list update input in addition to set

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#5078]
## Problem

Right now we only provide a `set` method for scalar lists

For example, lets say we have this model:
```prisma
model User {
  id         String   @id @default(cuid())
  permission String[]
}
```

We generate the following update type:
```ts
export type UserUpdatePermissionsInput = {
  set?: Enumerable<string> | null
}
```

This is not ideal when you want to push items to the array. For that right now you will need to read the whole record and add the previous items to the old array and then set it which costs a db request and it is not the best DX.

## Suggested solution
Add a push key to the update input which will add the new item instead of resetting the `set`
```ts
export type UserUpdatePermissionsInput = {
  set?: Enumerable<string> | null
  push?: Enumerable<string> | null
}
```

Under the hood this can be backed by the `||` postgres operator or the `array_append` method

## Alternatives
I am not sure how we can provide a better way of doing this right now.

## Additional context
Suggested by @kitze in his livestream

**Comment by pantharshit00** [comment]
Here is the example:

In this example, I want to make the user admin so I need to append the admin permission to the user. Here is how you would do it right now.

```ts
const existingRecord = await prisma.user.findOne({ where: { id });
const updatedUser = await prisma.user.update({ where: { id }, data: { permission : { set: existingRecord.permission.push("ADMIN") });
```

You will need to read the record if you want to just add another item to the scalar list. 

vs if we had a push method

```ts
const updatedUser = await prisma.user.update({ where: { id }, data: { permission : { push: ["ADMIN"] }); // push can be enumerable
```


We already implemented some additional scalar list filters so I think we can also add some write helpers here if we have the capacity.

**Comment by kladnik** [comment]
This would come in very handy. This would simplify things quite a bit.

**Comment by jakeleventhal** [comment]
What do folks in this thread think about adding a "pushUnique"

which essentially would skip duplicates

**Comment by David-crypto919** [comment]
How can this functionality be achieved in a MongoDB database?

**Comment by Viriatto** [comment]
> How can this functionality be achieved in a MongoDB database?

> What do folks in this thread think about adding a "pushUnique"
> 
> which essentially would skip duplicates
> 
> Update: #19370

In MongoDB it's called [$addToSet](https://www.mongodb.com/docs/manual/reference/operator/update/addToSet/)
