### ISSUE TITLE
Generate from `postinstall` hook is not working

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#5084]
## Bug description

Implicit generate from `postinstall` hook is not working. 

We figured this out because the CSB E2E test didn't have an explicit generate and that E2E test was failing with 

```
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again
```

CSB test was fixed via https://github.com/prisma/e2e-tests/pull/848

## How to reproduce

1. Setup a Prisma project with `schema.prisma`
2. yarn/npm install Prisma client
3. See logs for `postinstall` hook execution, the logs are dynamic and get removed by yarn, so you have to see it when it is happening
4. Write a script that uses the client (without manually running generate) and import client etc. It should not have been generated yet. 

## Expected behavior

Implicit generate should work. 

## Prisma information

`2.9.0-dev.71`

We understand that this broke in `2.9.0-dev.69` https://github.com/prisma/prisma/pull/3886 (not confirmed)

**Comment by NMinhNguyen** [comment]
Unfortunately can't share my project but I started getting this issue after upgrading from 2.14.0 to 2.15.0. Works locally but doesn't work on CI (Jenkins). What's the best way to get Yarn to print out `postinstall` logs because I think that by default it doesn't show them? :/

**Comment by divyenduz** [comment]
@NMinhNguyen Do you `yarn install` anything after running `prisma generate`?

**Comment by NMinhNguyen** [comment]
> @NMinhNguyen Do you `yarn install` anything after running `prisma generate`?

No, I'm not, I'm running `yarn` first. But don't worry, I think my issue is different to this anyway.

**Comment by Jolg42** [comment]
@divyenduz can this be closed maybe?
