### ISSUE TITLE
Error message clarification

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma#5094]
## Bug description

Getting following error: `AssertionError("[Query Graph] Expected a valid parent ID to be present for a nested connect on a one-to-many relation.`

However, it doesn’t let me know:

- the relation

- the models involved

- the invalid ID

## How to reproduce

Not sure how to reproduce at the moment since I have no idea what the error is or where I can find it.

## Expected behavior

A clear and concise description of the error :)

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 12.6.0
- Prisma version:
```
2.11.0
```

**Comment by janpio** [comment]
Hey, closing this for now as we most probably improved that in the last 3+ years.
If we have not, please open a new issue with a reproduction of how to get to this error message and we are happy to take another look.

Thank you!
