### ISSUE TITLE
PANIC: index out of bounds: the len is 1 but the index is 1

### ISSUE THREAD

**Issue by andresggarcia** [prisma/prisma#5095]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v10.16.0           | 
| OS              | darwin             |
| Prisma Client   | 2.12.0             |

## Logs
```
  prisma-client { clientVersion: '2.12.0' }  
  plusX Execution permissions of /Users/agarciag/Documents/Repos/point-shipping-providers/node_modules/.prisma/client/query-engine-darwin are fine  
  plusX Execution permissions of /Users/agarciag/Documents/Repos/point-shipping-providers/node_modules/.prisma/client/query-engine-darwin are fine  
```

**Comment by Weakky** [comment]
We're no longer able to reproduce that specific error (the panic). A different error was reproducible though, which is fixed by https://github.com/prisma/prisma-engines/pull/1620
