### ISSUE TITLE
PANIC: index out of bounds: the len is 1 but the index is 1

### ISSUE THREAD

**Issue by kimyh03** [prisma/prisma#5099]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.3           | 
| OS              | windows            |
| Prisma Client   | 2.13.1             |

## Logs
```
  prisma-client { clientVersion: '2.13.1' }  
```

everything is working perfectly in wsl2(ubuntu 18.04) with same code

but in windows "npx prisma migrate dev --preview-feature" and send any query or mutation via gql playground

I've got this error PANIC: index out of bounds: the len is 1 but the index is 1

(I follow the document of nestjs  and prisma-nest git exmple repo)

please cheak my github repo (https://github.com/kimyh03/prisma-nestjs-graphql-windows-error)

## src/app.module.ts
```javascript
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { join } from 'path';
import { PrismaService } from './prisma.service';
import { UserResolver } from './resolvers.user';
@Module({
  imports: [
    GraphQLModule.forRoot({
      autoSchemaFile: join(process.cwd(), 'src/schema.gql'),
    }),
  ],
  controllers: [],
  providers: [PrismaService, UserResolver],
})
export class AppModule {}

```
## src\prisma.service.ts
```javascript
import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService
  extends PrismaClient
  implements OnModuleInit, OnModuleDestroy {
  async onModuleInit() {
    await this.$connect();
  }

  async onModuleDestroy() {
    await this.$disconnect();
  }
}
```
## prisma\schema.prisma
```javascript
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```
## src\resolvers.user.ts
```javascript
import 'reflect-metadata';
import {
  Resolver,
  Query,
  Mutation,
  Args,
  InputType,
  Field,
} from '@nestjs/graphql';
import { Inject } from '@nestjs/common';
import { User } from './user';
import { PrismaService } from './prisma.service';

@InputType()
class SignupUserInput {
  @Field({ nullable: true })
  name: string;

  @Field()
  email: string;
}

@Resolver(User)
export class UserResolver {
  constructor(@Inject(PrismaService) private prismaService: PrismaService) {}

  @Mutation(() => User)
  async signupUser(@Args('data') data: SignupUserInput): Promise<User> {
    return this.prismaService.user.create({
      data: {
        email: data.email,
        name: data.name,
      },
    });
  }

  @Query(() => User, { nullable: true })
  async user(@Args('id') id: number) {
    return this.prismaService.user.findUnique({
      where: { id: id },
    });
  }
}

```
## src/user.ts
```javascript
import 'reflect-metadata';
import { ObjectType, Field, ID } from '@nestjs/graphql';

@ObjectType()
export class User {
  @Field(() => ID)
  id: number;

  @Field()
  email: string;

  @Field(() => String, { nullable: true })
  name?: string | null;
}

```
![1](https://user-images.githubusercontent.com/59421544/103145083-a92e5b80-4777-11eb-9d21-0744aa1b1fec.jpg)
![2](https://user-images.githubusercontent.com/59421544/103145085-acc1e280-4777-11eb-9af6-cc4b08260be3.jpg)

**Comment by do4gr** [comment]
Hi thanks for reporting this!
 
We improved our database error parsing in 2.16 which was the root cause of this error. You should now get the underlying error from the database (it could be something like a constraint violation for example). Please try to reproduce the error again and if the database error does not make sense open a new issue please.
