### ISSUE TITLE
Too many instances of PrismaClient

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma#5103]
## Bug description

I’m getting the classic `FATAL: remaining connection slots are reserved for non-replication superuser connections` error for my Postgres DB because there are too many `PrismaClient` instances going on.

Problem is, I’m using REST API routes (using [NextJS](https://github.com/vercel/next.js/tree/master/examples/api-routes-rest/pages)) and not [GraphQL](https://github.com/prisma/prisma/issues/2143#issuecomment-611481435), so each time there’s an incoming request to a route (and there are many), I’m instantiating a `PrismaClient`, which results in the aforementioned error.

Is there a way to avoid this?

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 12.6.0
- Prisma version:
```
2.11.0
```

**Comment by matthewmueller** [comment]
Hey Martin, we've documented the `next dev` workflow here: https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices

**Comment by heymartinadams** [comment]
@matthewmueller can we somehow maintain autocompletion (e.g. in VSCode) even if we import from a global variable?

Currently I need to:

```js
// import prisma from 'lib/api/prisma'
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

While working on a file, then remove that before testing.

```js
import prisma from 'lib/api/prisma'
```

**Comment by hughcrt** [comment]
I get this error when using the code from  https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices.
`TypeError: Duplicate declaration "prisma"`

Which I fixed by replacing `let prisma: PrismaClient` by `let prismaClient: PrismaClient`.

I'm not an expert in Typescript but you might need to modify your article

**Comment by OliverGilan** [comment]
> Works like a charm, @vladandrei0.
> 
> ## module
> ```js
> import { PrismaClient } from '@prisma/client'
> 
> // See here: https://github.com/prisma/prisma-client-js/issues/228#issuecomment-618433162
> let prisma
> 
> if (process.env.NODE_ENV === 'production') {
> 	prisma = new PrismaClient()
> }
> // `stg` or `dev`
> else {
> 	if (!global.prisma) {
> 		global.prisma = new PrismaClient()
> 	}
> 
> 	prisma = global.prisma
> }
> 
> export default prisma
> ```
> 
> ## API
> e.g. `/api/payments/create`
> 
> ```js
> import prisma from 'lib/utils/prisma'
> 
> const ApiPaymentsCreate = async (req, res) => {
>   ...
>   return await prisma.payment.create({...})
> }
> 
> export default ApiPaymentsCreate
> ```
> 
> However, a drawback is that referencing Prisma Client indirectly stops the auto-completion (at least in VS Code). A workaround is to temporarily enable while creating the API:
> 
> ```js
> // import prisma from 'lib/utils/prisma'
> import { PrismaClient } from '@prisma/client'
> const prisma = new PrismaClient()
> ```
> 
> and then to disable it once done:
> 
> ```js
> import prisma from 'lib/utils/prisma'
> ```

I understand how and why this works during development but why is the issue not present for production? Why is it okay to create a new prisma client each time while running in production?

**Comment by sergioengineer** [comment]
For those having problems with the autocompletion while using plain JS: just let VSCode know the type of the variable through JSDoc.

```
/** @type {PrismaClient} */
let prisma

if (process.env.NODE_ENV === "production") {
  prisma = new PrismaClient()
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient()
  }
  prisma = global.prisma
}

prisma.$connect()
export default prisma
```

**Comment by janpio** [comment]
Where are you using that plain JS example @sergioengineer? We should probably add it to our documentation equivalent to the Next.js example.

**Comment by sergioengineer** [comment]
I was specifically answering [this comment](https://github.com/prisma/prisma/issues/5103#issuecomment-780227535) complaining that he was loosing auto-completion by caching Prisma's instance in a variable.

The solution is to let VS Code know the type of the variable as soon as it is instantiated inside the lib file where people are pasting the workaround.

```
/** @type {PrismaClient} */
let prisma
```

This is also a solution to this [issue](https://github.com/prisma/language-tools/issues/810).

**Comment by janpio** [comment]
Ah ok, so it also applies for TypeScript - then this is probably something we just want to add to the example in the docs for everyone? Should improve the life of _many_ people then.

**Comment by therobhrt** [comment]
Has anyone encountered an issue when Next.js build some number of static pages during the build, which require DB calls, and due to (assumed) high parallelization of these static page builds, there are multiple DB connections spawned simultaneously, tightly correlated with the number of pages being built.

The solution for hot reload does not seem to help in such case, as we always had it in our codebase.

Basically if we pre-build say 10 pages into static, through the build process the nextjs builder opens 10 connections to DB. The bigger problem is that these connections seem to stale, and it's unclear where to edit the code to force terminate them.

**Comment by sergioengineer** [comment]
I've never had this kind of problem before. Do you perhaps use getInitialProps somewhere in your App or Document file?
Do you have a smaller repository, which you could share with us, where we could reproduce the same issue?

Seems like a fun issue to solve.

**Comment by janpio** [comment]
A reproduction of what you are seeing and observing always helps. Feel free to create a bug issue for that then or a discussion, so we can take a look and potentially help out.

**Comment by Sufiyan-dev** [comment]
> Works like a charm, @vladandrei0.
> 
> ## module
> ```js
> import { PrismaClient } from '@prisma/client'
> 
> // See here: https://github.com/prisma/prisma-client-js/issues/228#issuecomment-618433162
> let prisma
> 
> if (process.env.NODE_ENV === 'production') {
> 	prisma = new PrismaClient()
> }
> // `stg` or `dev`
> else {
> 	if (!global.prisma) {
> 		global.prisma = new PrismaClient()
> 	}
> 
> 	prisma = global.prisma
> }
> 
> export default prisma
> ```
> 
> ## API
> e.g. `/api/payments/create`
> 
> ```js
> import prisma from 'lib/utils/prisma'
> 
> const ApiPaymentsCreate = async (req, res) => {
>   ...
>   return await prisma.payment.create({...})
> }
> 
> export default ApiPaymentsCreate
> ```
> 
> However, a drawback is that referencing Prisma Client indirectly stops the auto-completion (at least in VS Code). A workaround is to temporarily enable while creating the API:
> 
> ```js
> // import prisma from 'lib/utils/prisma'
> import { PrismaClient } from '@prisma/client'
> const prisma = new PrismaClient()
> ```
> 
> and then to disable it once done:
> 
> ```js
> import prisma from 'lib/utils/prisma'
> ```

hey I believe this is the solution but it has security issues to all access of prsima client as global

**Comment by kareemjeiroudi** [comment]
> @bbbryan14 how, specifically, would it be done with NextJS (not NestJS) REST APIs? As far as I know, each API is called individually at various times. Even if I separate it into modules, won’t a new Prisma Client be instantiated each time an API is called? Like this?
> 
> ## module
> ```js
> // Prisma
> import { PrismaClient } from '@prisma/client'
> const prisma = new PrismaClient()
> 
> export default prisma
> ```
> 
> ## API 1
> e.g. `/pages/api/payments/initiate`
> 
> ```js
> import prisma from 'lib/utils/prisma'
> 
> const ApiPaymentsInitiate = async (req, res) => {
>   ...
> }
> 
> export default ApiPaymentsInitiate
> ```
> 
> ## API 2
> e.g. `/pages/api/payments/confirm`
> 
> ```js
> import prisma from 'lib/utils/prisma'
> 
> const ApiPaymentsConfirm = async (req, res) => {
>   ...
> }
> 
> export default ApiPaymentsConfirm
> ```

Did this work @heymartinadams? I reckon this should be enough, because I don't think that hot-reloading would instantiate another client. However, I haven't tested this solution yet.

**Comment by heymartinadams** [comment]
@kareemjeiroudi → https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices#solution

**Comment by junaid33** [comment]
@robhrt7 I'm having the same issue and here is the reproduction: https://github.com/openshiporg/openfront. Were you able to figure out how to use prisma inside generateStaticParams and not get FATAL: too many connections?

Essentially, we are using the prisma client inside generateStaticParams to get our product data and create the product pages statically. Issue is that this creates a lot of connections to our database and the fetches fail eventually. Since the queries are done in parallel during next build and the connections created are never closed, we can't use prisma.
