### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#5129]
## Problem

Due to Prisma being quite of a black box, I suggest adding a metrics functionality to the client, allowing users to get a snapshot of the current state of the Query Engine.

## Suggested solution

We'd have a method `prisma.metrics()` that'd return an object with information about the underlying engine, for example:

- Current maximum connections
- Current connections in use
- Requests processed so far
- Number of errors
- Histogram data of response times

## Alternatives

People might say structured logs are an alternative for metrics, but it's more of an addition. With logs, users can detect and inspect events in the system, with metrics, they can observe the general status of the system. Also stats like histograms are easier to do with metrics than from structured logs. And structured logs are useful for investigating failures.

Logs are also expensive to store and transfer, which means storage over a few days is costing a lot of money. Metrics can be stored for some months with the same money.

## Additional context

Prisma should provide an object of the current status. Users can then convert this to a Prometheus endpoint, or additionally send the data to timescale databases such as InfluxDB to be graphed with Grafana.

Metrics are one of the key points of monitoring a running system, and we should provide as much data as possible from Prisma for our users to graph.

**Comment by Sytten** [comment]
As I am building graphmetrics.io, I am also looking at histograms for GraphQL servers. I boiled down my choice to DDsketch or circonus histogram. Feel free to reach out on slack if you want to discuss histograms. Check also the opentelemetry issue about that https://github.com/open-telemetry/opentelemetry-specification/issues/982. I think it could be nice if prisma was opentelemetry compliant.

**Comment by pimeys** [comment]
I think telemetry is another topic. They serve different needs, but what I'm describing here is to get a snapshot from different parts of the system.

Telemetry would be more like seeing how this one query here performs and where time is spent. We should maybe have another issue for that, and one for structured logging?

**Comment by Sytten** [comment]
Make sense, but histogram of response time doesn't tell much if its not per model or per query since you can't really act on it. But then storing many good histograms can also be costly, thus the need for a specialized algo.

**Comment by pimeys** [comment]
Yeah. I'd like to first get these crucial metrics for people, like number of connections in use. We're making error messages better for these kind of stupid timeout errors, now you know exactly what timed out and can react accordingly. Better would be if our users would get a graph for reserved connections, and could react to possible problems beforehand by adding more instances of the app or increasing the connection limit.

**Comment by pimeys** [comment]
And, not to discard your suggestion, telemetry is extremely important to tackle as well as metrics and structured logs.

**Comment by janpio** [comment]
Uh, we have this already! 

It's called Prisma Client Metrics and documented here: https://www.prisma.io/docs/concepts/components/prisma-client/metrics 
Right now it also is a preview feature `metrics` and we are collecting feedback at https://github.com/prisma/prisma/issues/13579

**Comment by pimeys** [comment]
Yay, thank you for the team for the hard work to make this happen. I'll try it ASAP.
