### ISSUE TITLE
[Bug] Find Unique: Query engine exited with code 255 - Could not canonicalize path dir

### ISSUE THREAD

**Issue by Stormtv** [prisma/prisma#5133]
## Bug description
I recently updated from prisma 2.9.0 to 2.14.0 and I am now seeing the following error when using findUnique

```
app | 2021-01-14 17:15:54 22:15:54.928Z ERROR App-Backend:
app | 2021-01-14 17:15:54   Query engine exited with code 255
app | 2021-01-14 17:15:54   PANIC in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.15.0/src/listener/unix_listener.rs:152:22
app | 2021-01-14 17:15:54   Could not canonicalize path dir
app | 2021-01-14 17:15:54   --
app | 2021-01-14 17:15:54   Error: Query engine exited with code 255
app | 2021-01-14 17:15:54   PANIC in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.15.0/src/listener/unix_listener.rs:152:22
app | 2021-01-14 17:15:54   Could not canonicalize path dir
app | 2021-01-14 17:15:54       at PrismaClientFetcher.request (/app/backend/node_modules/@prisma/client/runtime/index.js:78136:15)
app | 2021-01-14 17:15:54       at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Any idea what is happening here? This doesn’t seem to happen to me locally on my macbook but does occur when on my alpine linux docker container

I am planning on turning on the debug env var and getting more log data as well as update the version from 2.9.0 -> 2.10.0 etc to determine which version broke the build. 

## How to reproduce
Run a Node.js Alpine docker container (see dockerfile below) and attempt to use the findUnique command.

## Expected behavior
Service to return the user with the appropriate id

## Prisma information
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model waitlist {
  id         Int        @id @default(autoincrement())
  email      String     @unique
  createdAt  DateTime   @default(now()) @map("created_at")
  referrerId Int?       @map("referrer_id")
  score      Int        @default(100000)
  referrer   waitlist?  @relation("waitlistTowaitlist", fields: [referrerId], references: [id])
  referrals  waitlist[] @relation("waitlistTowaitlist")
}
```

```
  const { id } = req.params
  const user = await prisma.waitlist.findUnique({
    where: {
      id: Number(id),
    },
    select: {
      id: true,
      score: true,
      referrals: true,
    },
  })
```

```
FROM node:12-alpine

EXPOSE 4000

ADD . / app/
WORKDIR /app

RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++ \
    && npm install --cache .npm --no-audit --prefer-offline --prefix ./frontend \
    && npm install --cache .npm --no-audit --prefer-offline --prefix ./backend \
    && npm run generate:docker --prefix ./backend \
    && npm run build --prefix ./frontend \
    && npm run build --prefix ./backend \
    && apk del build-dependencies

CMD ["node", "backend/build/index.js"]
```
Note the `npm run generate:docker` is the command that generates the prisma client for this project.

## Environment & setup

- OS: Alpine Linux
- Database: PostgreSQL
- Node.js version: 12
- Prisma version: v2.14.0

**Comment by Stormtv** [comment]
@pantharshit00 This seems to have been fixed when I updated to v2.15. Thanks

Not sure how to get my host operating system but when running  `cat /etc/os-release` I get this

```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.7
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by pantharshit00** [comment]
I am going to close this for now as we have closed the other UDS related issues in 2.15. 

By "host" I mean which OS your machine is running which is running the docker image and not the OS of the docker image.

**Comment by zwanzigg** [comment]
Any updates on this issue? I struggling the same right now. I would appreciate any help.

**Comment by pantharshit00** [comment]
@zwanzigg This is should not happen in the latest version. If you experiencing this on the latest version, please share a reproduction.
