### ISSUE TITLE
> For those having this issue, I solved it by creating a singleton:

### ISSUE THREAD

**Issue by tobkle** [prisma/prisma#5139]
> For those having this issue, I solved it by creating a singleton:
> 
> ```ts
> import { PrismaClient } from '@prisma/client'
> 
> class DBClient {
>   public prisma: PrismaClient
>   private static instance: DBClient
>   private constructor() {
>     this.prisma = new PrismaClient()
>   }
> 
>   public static getInstance = () => {
>     if (!DBClient.instance) {
>       DBClient.instance = new DBClient()
>     }
>     return DBClient.instance
>   }
> }
> 
> export default DBClient
> ```
> 
> Then wherever I used the client I did:
> 
> ```ts
> import DBClient from '../../database/client'
> const prisma = DBClient.getInstance().prisma
> ```
> 
> You can then use it like normal.

Just to note, after a day of using this I once again received: "Fatal: sorry, too many clients already"

_Originally posted by @juanzgc in https://github.com/prisma/prisma/issues/1983#issuecomment-742275801_

Did the above, but still receive that Error. Any ideas?

**Comment by ruslanguns** [comment]
@tobkle I still receive that error. I see you closed this issue, Did you figured that out? I am having issues on E2E testing.

**Comment by ruslanguns** [comment]
I solved it by just disconecting after each acceptant criteria. BUT I dont understand why with singleton this issue is not rip

**Comment by ptrkvsky** [comment]
```tsx
import { PrismaClient } from '@prisma/client';

const DBClient = {
  instance: new PrismaClient(),
};

export type IDBClient = typeof DBClient;

Object.freeze(DBClient);

export default DBClient;
```

You can do it in a simpler way 
https://www.patterns.dev/posts/singleton-pattern/

**Comment by Behrad96** [comment]
Here is a simpler way.

```js
/* lib/db.js */
import { PrismaClient } from "@prisma/client";

if (!global.prisma) {
    global.prisma = new PrismaClient();
}
export default global.prisma;
```

```js
/* pages/api/users.js */
import prisma from '../../lib/db';

export default async function handler(req, res) {
  const users = await prisma.user.findMany()
  return res.status(200).json({ users })
}
```

**Comment by Arun12Muralidharan** [comment]
Hi @Behrad96 

It worked.. thanks a lot....

**Comment by Samueljh1** [comment]
Use this for typescript:

```ts
/* lib/db.js */
import { PrismaClient } from "@prisma/client";

declare global {
  var prisma: PrismaClient
}

if (!global.prisma) {
    global.prisma = new PrismaClient();
}

export default global.prisma;
```

**Comment by VinayakVispute** [comment]
@Samueljh1 Thanks for this 😁

**Comment by CodecAnuj** [comment]
can also use this for typescript + nextjs

/* lib/db.ts */
import { PrismaClient } from "@prisma/client";

const globalForPrisma = global as unknown as { prisma: PrismaClient };

const client  = globalForPrisma.prisma || new PrismaClient();

export default client 

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = client;


/* app/api/user/route.ts */
import client from "@/db";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  const body = await req.json();
  await client.user.create({
      data: {
        username: body.username,
        password: body.password,
      },
    });
    return NextResponse.json({
      body,
    },
      {
        status: 200,
      });

**Comment by CodecAnuj** [comment]
### can also use this for typescript + nextjs

```
/* lib/db.ts */
import { PrismaClient } from "@prisma/client";

const globalForPrisma = global as unknown as { prisma: PrismaClient };

const client = globalForPrisma.prisma || new PrismaClient();

export default client

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = client;
```


```
/* app/api/user/route.ts */
import client from "@/db";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
const body = await req.json();
await client.user.create({
data: {
username: body.username,
password: body.password,
},
});
return NextResponse.json({
body,
},
{
status: 200,
});

```

**Comment by Abhinavpatra** [comment]
This is a slightly safer approach for ts + prisma for a client.ts file

```typescript
import { PrismaClient } from "@prisma/client";

declare global {
  var prisma: PrismaClient | undefined;
}

const prisma = global.prisma ?? new PrismaClient();

if (!global.prisma) {
    global.prisma = prisma;
}

export default prisma;
```
