### ISSUE TITLE
Type 'UnEnumerate<TK>' does not satisfy the constraint 'object'.

### ISSUE THREAD

**Issue by EduardoBautista** [prisma/prisma#5142]
## Bug description
When trying to compile my typescript I get these errors:

```
node_modules/.prisma/client/index.d.ts:276:64 - error TS2344: Type 'UnEnumerate<TK>' does not satisfy the constraint 'object'.
  Type 'unknown' is not assignable to type 'object'.

276       ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
                                                                   ~~~~~~~~~~~~~~~

node_modules/.prisma/client/index.d.ts:785:66 - error TS2344: Type 'UnEnumerate<TK>' does not satisfy the constraint 'object'.
  Type 'unknown' is not assignable to type 'object'.

785         ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
                                                                     ~~~~~~~~~~~~~~~


Found 2 errors.
```

## How to reproduce

1. Compile app with `tsc`

## Expected behavior

It should compile the app

## Prisma information

@prisma/client 2.14.0

## Environment & setup

- OS: MacOS Big Sur
- Database: Postgres
- Node.js version: 14.1.0
- Prisma version: 2.14.0

**Comment by EduardoBautista** [comment]
Don't know what happened but my code is now working...closing.

**Comment by Jolg42** [comment]
Just encountered the same issue in the Prisma Public Slack and the problem was that the global `typescript` dependency was too old.

Check the output of `tsc -v` for the version.

Update your local or / and global `typescript` version to >4.1 or latest.

Because 2.14 requires typescript >4.1
https://github.com/prisma/prisma/releases/tag/2.14.0

**Comment by EduardoBautista** [comment]
@Jolg42 Thanks for the tip!

**Comment by Jolg42** [comment]
Note: This is where we keep the requirements up-to-date https://www.prisma.io/docs/reference/system-requirements/
