### ISSUE TITLE
DB seed does not work with custom schema location

### ISSUE THREAD

**Issue by flybayer** [prisma/prisma#5213]
## Bug description

The new `prisma db seed` command does not work with a custom schema location.

With schema location of `db/schema.prisma`, the seed file should also be looked for at `db/seed.ts`.

## How to reproduce

Set custom schema location and a `seed.ts` file beside that schema.

## Expected behavior

Should be able to have a `seed.ts` file as a sibling of a custom schema location.

## Prisma information

`2.15.0`

**Comment by flybayer** [comment]
@Jolg42 this was not fixed. Only `--schema` flag was added, not what I requested in this isssue

**Comment by janpio** [comment]
Seems @Jolg42 understood that `--schema` would solve the use case you described, and possibly forgot that the schema location can also be configured via the `package.json` file: https://www.prisma.io/docs/concepts/components/prisma-schema#prisma-schema-file-location Is that was you initially meant @flybayer?

**Comment by flybayer** [comment]
@janpio yes! Using `package.json` schema config. Sorry, that wasn't super clear 😅

**Comment by Jolg42** [comment]
Got it!

I'm closing this issue and opened https://github.com/prisma/prisma/issues/5483
