### ISSUE TITLE
1-n many relation works implicitly without specifying the foreign key

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#5216]
I'm not sure we would consider this a bug but it certainly seems a bit strange that this is functional so I wanted to raise it here on GitHub. The following schema creates a correct 1-n relation in the DB without the foreign key being specified in the Prisma schema:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["nativeTypes"]
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://nikolasburk:nikolasburk@localhost:5432/testdb1"
}

model user {
  id             String        @id @default(uuid()) @db.Uuid()
  email          String        @unique
  password       String
  createdAt      DateTime      @default(now()) @map("created_at")
  organization   organization? @relation(references: [id])
}
model organization {
  id        String   @id @default(uuid()) @db.Uuid()
  name      String
  createdAt DateTime @default(now()) @map("created_at")
  users     user[]
}
```

Running `prisma migrate dev` creates the following SQL:

```sql
-- CreateTable
CREATE TABLE "user" (
    "id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT,
    "password" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "organizationId" UUID,

    PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "organization" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "user.email_unique" ON "user"("email");

-- AddForeignKey
ALTER TABLE "user" ADD FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
```

My understanding is that foreign keys should be made explicit in the Prisma schema and specified via `references` inside the `@relation` attribute. If the case above should be allowed, we probably should document this approach too.

**Comment by pantharshit00** [comment]
I would also say this schema should be rejected by that validator. I have candidated this issue so that we can have a look into this in the next planning.

**Comment by matthewmueller** [comment]
Yah, I tend to agree. We should enforce the foreign key, it reduces the number of invalid states a schema can be in.

```diff
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["nativeTypes"]
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://nikolasburk:nikolasburk@localhost:5432/testdb1"
}

model user {
  id             String        @id @default(uuid()) @db.Uuid()
  email          String        @unique
  password       String
  createdAt      DateTime      @default(now()) @map("created_at")
- organization   organization? @relation(references: [id])
+ organization   organization? @relation(fields: [organizationId], references: [id])
+ organizationId String?
}
model organization {
  id        String   @id @default(uuid()) @db.Uuid()
  name      String
  createdAt DateTime @default(now()) @map("created_at")
  users     user[]
}
```

**Comment by do4gr** [comment]
Agree, I stumbled over the logic for this in the datamodel code (that is making up the scalar field necessary to back the relation).  I also did not know we allowed this and had extra logic handling it. I find it weird that without re-introspecting you would not have the scalar field in your schema.

**Comment by matthewmueller** [comment]
@pimeys will look into this at the same time as https://github.com/prisma/prisma/issues/5069

**Comment by pimeys** [comment]
We should not run the standardizer on migration or query engine paths, but instead just error out. On prisma-fmt we should still run this, but also fix the problems what the code does in certain cases:

https://github.com/prisma/prisma/issues/5540

**Comment by pimeys** [comment]
This needs planning and I'm re-candidating the ticket after having a meeting with the migrations team. We should change how and where we modify the schema. When it happens during the validation, we get all kinds of errors like this. Something for next sprint maybe?

**Comment by pimeys** [comment]
@do4gr is currently solving this with the standardizer changes.

**Comment by do4gr** [comment]
This should be solved by us splitting the parsing and formatting step here https://github.com/prisma/prisma-engines/pull/1662
