### ISSUE TITLE
Test support for PlanetScale/Vitess

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#5219]
Setup the test suite similar to Yuga and Cockroach. Check to see where we're at. If there's any small fixes we can make, let's do it. If it requires a lot more work, we'll schedule that work separately.

**Comment by yoshuawuyts** [comment]
I've attempted to approach this like we did for Yuga / Cockroach, and the setup is quite different. I tried integrating both the `vitess/base` and `vitess/lite` docker images into our CI, but both are rather involved to setup and I don't think we're in a position where we could maintain them without allocating substantial resources to it.

After discussing this with @matthewmueller, we decided it was best to pivot into investigating the PlanetScale hosted option, mostly to get a sense for compability with Prisma client, and provide feedback on what's missing to see this through to success. However apparently @timsuchanek also been looking into this, so today we've agreed he'll continue his investigation into PlanetScale, and take note of any incompatibilities that arise along the way. I believe an incompatibility around the `SHOW` query has already surfaced.

But to conclude my investigation: it seems that if we want to add support for Vitess / PlanetScale to Prisma Engines, we'll need to either have expert support on configuring and maintaining the CI setup, or rely on a hosted option to test against.

**Comment by matthewmueller** [comment]
Sprint is quite packed. We'll try to push this forward in a minimal way though.

**Comment by janpio** [comment]
Some internal context: https://prisma-company.slack.com/archives/CGMCB82N8/p1612340668093300

**Comment by pimeys** [comment]
Tom enables migration engine here for planetscale: https://github.com/prisma/prisma-engines/pull/1613

**Comment by pimeys** [comment]
Initial tests done https://www.notion.so/prismaio/PlanetScale-tests-30c94c15c9ff48049aa2da7e714dc923

**Comment by timsuchanek** [comment]
This issue is about running the whole Rust and TypeScript test suite once.
When we have that done, we can close this issue.

**Comment by janpio** [comment]
Internal writeup on compatibility of QE to Vitess by @pimeys: https://prisma-company.slack.com/archives/C01N3V81YAG/p1615905999006500 (Summary: Kinda works, a few things we need to talk to Vitess)

Steps open for QE + Vitess:
- [ ] Make a PR that can be merged that puts Vitess into our normal CI
- [ ] Add Vitess MySQL 8 as well and make sure nothing else breaks there

Future work:
- Validating Migration and Introspection Engine with Vitess
- Further Planetscale Cloud validation (tbd, around shadow database and similar)
