### ISSUE TITLE
Undici timeouts reintroduced

### ISSUE THREAD

**Issue by TheAschr** [prisma/prisma#5225]
I get the following error when running large transactions:

**Headers Timeout Error**

This was fixed in this merge:

https://github.com/prisma/prisma/pull/4156

However it seems headers timeout was removed here:

https://github.com/prisma/prisma/commit/ee107f16fc342113d5c0386c0edfbebb1a106c43#diff-57b53d00294e65834dd71a27493f9f35d60abc4e6afcae19a22a28a6d67f9584

https://github.com/prisma/prisma/blob/23a21b316f83c3faaa6d8ec378bf594ecc83245c/src/packages/engine-core/src/undici.ts#L8-L12

https://github.com/prisma/prisma/blob/7eacb7a25808e2259a5d3f71c94cc1f5e5148408/src/packages/engine-core/src/NodeEngine.ts#L697-L704

https://github.com/prisma/prisma/blob/7eacb7a25808e2259a5d3f71c94cc1f5e5148408/src/packages/engine-core/src/NodeEngine.ts#L707

**Comment by williamluke4** [comment]
`maxKeepAliveTimeout` was renamed to keepAliveMaxTimeout and it also appears that `maxKeepAliveTimeout: 0` is no longer supported
