### ISSUE TITLE
Squash all local migrations into a single migration file before deployments

### ISSUE THREAD

**Issue by dan003400** [prisma/prisma#5226]
I constantly find myself avoiding running `prisma migrate dev` to keep things consolidated and clean, in the past I come from the Rails world where I could easily squash all my migrations into one before deploying 28 migration files.

Seems like this should be a simple addition to the CLI that would keep prisma projects much cleaner and easier to work with.

**Comment by dan003400** [comment]
I know there has been some improvements to the migrations, is it possible to achieve some kind of squash before the first deployment with the local schema?

Basically take the local schema and generate the SQL migrations from scratch?

**Comment by tomhoule** [comment]
Hi @dan003400 , yes this is possible, although a bit manual at the moment. The way I would do this, assuming you want to squash the migrations _at the end of your migrations history_, and that the migrations haven't been applied outside of your dev environment, is the following:

- Delete the relevant migration folders
- Run `migrate dev` again. It will ask you to reset the database, then create the squashed migration
- In case one of the squashed migrations was applied outside of your dev machine, you will need to baseline (`migrate resolve --applied <name-of-the-squashed-migration>` there.

Note that this will regenerate the migration, so if you manually changed the SQL, these changes will be gone. You could also manually squash (move all the SQL in a single migration) if this is what you need.

It's not the most readable resource, but we do also have [internal tests](https://github.com/prisma/prisma-engines/blob/53dc252c7ac8d195ff6a341612b538c91de5982e/migration-engine/migration-engine-tests/tests/migrations/squashing_tests.rs) that make sure this process of squashing works. It's definitely something we can make more ergonomic in the future, it's just a matter of making plans and executing on them :)

**Comment by Jolg42** [comment]
Closing this issue as we also have https://github.com/prisma/prisma/issues/5714 (subscribe there for updates!)
