### ISSUE TITLE
TS2305: Module '"../../node_modules/@prisma/client"' has no exported member 'UrlCreateInput'.

### ISSUE THREAD

**Issue by gnorbsl** [prisma/prisma#5241]
## Bug description

I setup a new Project following the getting started guide, I installed and generated the client. I can Import my Models but I can't import the generated CreateInput types.

I can find the types in .prisma/client though.

I'm not sure what I'm doing wrong.

## Expected behavior

I use Prisma in another Setup and there I can import everything with 

`import { User, UserCreateInput, UserUpdateInput } from '@prisma/client';`

so I expect to be able to do the same in the new project.

## Environment & setup

- OS: MacOS
- Database: MariaDB 10.5
- Node.js version: v14.15.4
- Prisma version:

```
@prisma/cli          : 2.15.0
@prisma/client       : 2.15.0
Current platform     : darwin
Query Engine         : query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.340.0

```

**Comment by rafael-abuawad** [comment]
I ran into the same problem a few days ago, I think **that in Prisma version 2.15 the generated types are under the Prisma namespace**, so to use them you just have to import Prisma as a namespace, and get the types from there, like this:
```typescript
import { Prisma } from '@prisma/client';

async create(data: Prisma.UserCreateInput) {
  /*.... */
}
```

**Comment by oleksiipysanko** [comment]
I've noticed a move to `Prisma.` namespacing straight away (my code build was failing), so I had to move the likes of `PrismaClientKnownRequestError` and `InputJsonValue` under it which resolved the issue. It isn't specified anywhere in docs though, from what I can see now, but maybe it is a work in progress. 

But the original problem still remains, there are no input/where/etc. custom model types generated in prisma client output. I've tried to reverse to 2.14 version with no success.

**Comment by pantharshit00** [comment]
This is expected. We introduced this deprecation in 2.12 (https://github.com/prisma/prisma/releases/tag/2.12.0). Now we have removed deprecated types and methods from 2.15 and you will need to use the namespace.

We have a codemod which you can use to do this automatically: https://github.com/prisma/codemods
