### ISSUE TITLE
RHEL error after updating Prisma to 2.15.0

### ISSUE THREAD

**Issue by NMinhNguyen** [prisma/prisma#5243]
## Bug description

After updating Prisma from 2.14.0 to 2.15.0, I started getting TypeScript errors about `.prisma/client` not exporting types (but only on CI), so I thought I'd manually run `npx prisma generate` but it throws an error:

```
yarn workspace foo prisma generate
yarn workspace v1.22.4
yarn run v1.22.4
$ /usr/src/app/jenkins/workspace/foo/node_modules/.bin/prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Get config /usr/src/app/jenkins/workspace/foo/node_modules/@prisma/cli/query-engine-rhel-openssl-1.0.x: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/src/app/jenkins/workspace/foo/node_modules/@prisma/cli/query-engine-rhel-openssl-1.0.x)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/src/app/jenkins/nodejs/12.18.4/linux_x64/bin/node
Arguments: /usr/src/app/jenkins/workspace/foo/bin/yarn-1.22.4.js prisma generate
Directory: /usr/src/app/jenkins/workspace/foo/services/foo
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

Locally I use Ubuntu and there's no error thrown. In the changelog I saw something about RHEL, so could be related?

> We've upgraded our RHEL base image from CentOS 6 to Amazon Linux 2. CentOS 6 reached end-of-life on November 30th, 2020. This may affect machines still running Amazon Linux 1. If you run into problems with this upgrade, please don't hesitate to [reach out](https://github.com/prisma/prisma/issues/new/choose).

## How to reproduce

1. Update Prisma from 2.14.0 to 2.15.0
2. Run `npx prisma generate`
3. See above error

## Expected behavior

No error.

## Environment & setup

- OS: Red Hat Enterprise Linux Server release 7.9 (Maipo) (`cat /etc/redhat-release`)
- Database: MariaDB
- Node.js version: 12.18.4
- Prisma version: 2.15.0. Running `prisma -v` also throws the above error.

**Comment by pantharshit00** [comment]
Thanks for reporting, we did have some build pipeline changes as CentOS 6 went EOL. We will further investigate this now.

**Comment by NMinhNguyen** [comment]
> What is is your installed glibc version (on the server where the error is thrown)? `ldd --version`

```
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by nicksrandall** [comment]
I also have this issue and we are running RHEL7 which only supports `glibc 2.17`. It would be great if we could continue to support that version of glibc. Thanks for all you do!

**Comment by get6** [comment]
AWS EC2 t3.micro also cannot complete npx prisma generate. 😭
`
Error: Get config /home/ec2-user/myproject/node_modules/@prisma/cli/query-engine-rhel-openssl-1.0.x: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/ec2-user/myproject/node_modules/@prisma/cli/query-engine-rhel-openssl-1.0.x)
`

**Comment by matthewmueller** [comment]
@get6 do you know what distro you used? RHEL 6, RHEL 7, Amazon Linux 1?

**Comment by get6** [comment]
> @get6 do you know what distro you used? (e.g. RHEL 6, Centos 7, Amazon Linux 1)

@matthewmueller  Sorry, I already terminated a spot instance. 😅

So, I'm not sure it was Amazon Linux 1 or 2. But It was Amazon Linux.

It is the Requested instance type.
`
t2.micro $0.014, t3a.micro $0.012, t3.micro $0.013
`

**Comment by CGerAJ** [comment]
CentOS Linux release 7.9.2009 (Core)
```
ldd --version
ldd (GNU libc) 2.17
```
prisma version 2.15.0

same mistake too

**Comment by chanlito** [comment]
Is there a **workaround** for this? So frustrated every time we upgrade Prisma. From types missing, to generate bug, and a random now RHEL error 😭

Okay frustration aside:

I'm trying to upgrade to 2.15 on Amazon Linux 1

**Comment by dpetrick** [comment]
I rebased the RHEL binary build to CentOS 7 for now and lowered the required glibc version to 2.17 again. This will be available with 2.16 tomorrow. Reopen if you face any issues afterwards.

**Comment by Radmehr-aghdam** [comment]
I use prisma v2.24.1 and have this issue. I cant upgrade glibc because I use centOS7.
Is it possible use a specific version of prisma with glibc 2.17 ?

I don't want to change my Hosting :)

**Comment by janpio** [comment]
Please open a new issue with full description (including where you host for example) - then we can try to reproduce and hopefully get to a solution.

**Comment by Radmehr-aghdam** [comment]
> > prisma v2.24.1 and have this issue. I cant upgrade glibc because I use centOS7.
> > Is it possible use an specific version of prisma with glibc 2.17 ?
> 
> @Radmehr-aghdam did you found a prisma version comptible with glibc 2.17 ?

No!
I had to change my OS to Ubuntu 20.04 .  Because if you even fix glibc, you will see a bunch of problems in the futur.
Think about changing the OS.
