### ISSUE TITLE
Can not introspect after upgrade to 2.15.

### ISSUE THREAD

**Issue by nicksrandall** [prisma/prisma#5249]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v15.4.0            | 
| Prisma CLI  | 2.15.0             | 
| Binary      | e51dc3b5a9ee790a07104bec1c9477d51740fe54| 

## Error
```
Error: [libs/datamodel/connectors/dml/src/datamodel.rs:162:14] Every RelationInfo should have a complementary RelationInfo on the opposite relation field.
```

**Comment by pantharshit00** [comment]
Hey @nicksrandall 

Can you please share your database schema? I have seen this error message pop up in other place but would appreciate a reproduction.

**Comment by nicksrandall** [comment]
It turned out to be a local issue. Sorry, I forgot to close this.
