### ISSUE TITLE
Document, how to use Prisma in a wrapper function

### ISSUE THREAD

**Issue by BjoernRave** [prisma/prisma#5258]
This issue is the result of a discussion on the blitz slack: https://blitzjs.slack.com/archives/C011EQ0J75M/p1611259993025500

@timsuchanek asked me to create this, so it will be easier to work with advanced prisma typing.

**Comment by matthewmueller** [comment]
Next steps: 

- Document wrapping types
- Maybe making the types easier

E.g. 
```ts
function findById({ id } ) {
  prisma.user.find({ where: Object.assign(where, id))
}
```

**Comment by matthewmueller** [comment]
Thanks @BjoernRave for the context. Closing in favor of #7161
