### ISSUE TITLE
TypeScript deploy "Cannot find module `.prisma/client`"

### ISSUE THREAD

**Issue by croossin** [prisma/prisma#5266]
## Bug description

When trying to deploy Prisma client to Elastic Beanstalk, I am seeing the following errors:

```bash
Error: Cannot find module '.prisma/client'
Require stack:
- /var/app/current/node_modules/@prisma/client/index.js
- /var/app/current/dist/utils/Prisma.js
- /var/app/current/dist/config/passport.js
- /var/app/current/dist/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
at Function.Module._load (internal/modules/cjs/loader.js:690:27)
at Module.require (internal/modules/cjs/loader.js:852:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/var/app/current/node_modules/@prisma/client/index.js:1:16)
at Module._compile (internal/modules/cjs/loader.js:959:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
at Module.load (internal/modules/cjs/loader.js:815:32)
at Function.Module._load (internal/modules/cjs/loader.js:727:14)
at Module.require (internal/modules/cjs/loader.js:852:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/var/app/current/node_modules/@prisma/client/index.js',
'/var/app/current/dist/utils/Prisma.js',
'/var/app/current/dist/config/passport.js',
'/var/app/current/dist/index.js'
]
}
```

## How to reproduce

Follow along [this prisma tutorial](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-typescript-postgres) and attempt to deploy to AWS Elastic Beanstalk

## Expected behavior

It to deploy properly.

## Prisma information

`Package.json` :
```
...
"@prisma/cli": "2.15.0",
"@prisma/client": "2.15.0",
...
```

`tsconfig.json`
```javascript
{
    "compilerOptions": {
      "lib": ["esnext"],
      "outDir": "dist",
      "moduleResolution": "node",
      "esModuleInterop": true,
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "skipLibCheck": true,
      "forceConsistentCasingInFileNames": true,
    }
  }
  
```

I will say I have tried all different variations of tsconfig as well...

**Comment by jimthedev** [comment]
Seeing this in Blitz canary, too.

**Comment by timsuchanek** [comment]
@jimthedev are you also deploying to Elastic Beanstalk?

**Comment by timsuchanek** [comment]
And another question: Does this also happen in `2.14.0`?

**Comment by croossin** [comment]
I haven’t tried with 2.14.0 but I certainly can and report back.

**Comment by timsuchanek** [comment]
Thanks, that would be awesome. I'm trying to reproduce now as well.

**Comment by croossin** [comment]
@timsuchanek Can confirm that 2.14.0 has the same issues.

**Comment by timsuchanek** [comment]
Ok good to know! We'll let you know here once it's fixed.

**Comment by jimthedev** [comment]
> @jimthedev are you also deploying to Elastic Beanstalk?

Sorry. No. I am running this locally on MacOS X Catalina with Blitz cli source code linked using yarn link.

**Comment by timsuchanek** [comment]
Ok good to know, then I have another possible reproduction :+1:

**Comment by timsuchanek** [comment]
And @jimthedev did this start appearing in `2.15.0` or did you see this earlier already?

**Comment by jimthedev** [comment]
> And @jimthedev did this start appearing in `2.15.0` or did you see this earlier already?

This is a brand new app so I don’t know but previous versions of Blitz apps worked using prisma so I suspect this is new.

**Comment by timsuchanek** [comment]
I suspect we have completely separate causes here, both in Elastic Beanstalk and Blitz, but I'll find out soon.

**Comment by croossin** [comment]
@timsuchanek Let me know if you need me to test anything on my side. Very excited to get this deployed!

**Comment by timsuchanek** [comment]
@jimthedev do you think you could create a reproduction repo? That would help a lot!

**Comment by flybayer** [comment]
@jimthedev I'm 95% sure this is just because the prisma postinstall hooks don't fire properly in yarn workspaces. So you have to manually run `blitz prisma generate` to generate the client. Then restart the server

**Comment by croossin** [comment]
@flybayer At least for the EB scenario - we are using npm when deploying.

**Comment by timsuchanek** [comment]
@croossin I can now reproduce in EB :) 
The fix will take a bit, but should come this sprint (until next Tuesday)

**Comment by timsuchanek** [comment]
@flybayer if you would have a repro, where generate doesn't work in a workspace, we would be more than happy to fix it 🙏

**Comment by croossin** [comment]
@timsuchanek That's great to hear!  When you say next Tuesday, is that the start of the sprint or the end (and when the fix would be ready)? 

Also, I think a tutorial in your docs page on deploying to EB would be an awesome addition, I can see lots of devs being interested in the recommended setup from prisma -> EB.  Thanks again for looking into it!

**Comment by flybayer** [comment]
@timsuchanek 

1. Clone https://github.com/blitz-js/blitz
2. `yarn`
3. `yarn build`
4. `cd examples/auth`
5. `blitz start` 
6. Open page in browser
7. See `Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.`

**Comment by timsuchanek** [comment]
Awesome, thanks @flybayer, will try out.

@croossin I look into it in this sprint and this sprint goes until next week Tuesday, so until then we'll have this fixed.
Yes, we should add a tutorial, example and I'll also add a [test to our e2e test suite](https://github.com/prisma/e2e-tests), to make sure this always works.
Will also add an e2e test for Brandon's use-case.

**Comment by timsuchanek** [comment]
Ok, after a bit more investigation, it turned out, that EB is not allowing any `postinstall` hook to write to the filesystem.
There are 2 ways to fix this:

## 1. `.npmrc`
Create a `.npmrc` file with this content: `unsafe-perm=true`
This let's the postinstall hook write into the filesystem as is the case in a normal npm installation.

## 2. Add `prestart` hook
Unfortunately, EB doesn't run the `postinstall` hook of the main application.
However, you can add a `prestart` hook that runs prisma generate like so:
```json
{
  "name": "eb-test",
  "scripts": {
    "start": "node ./bin/www",
    "prestart": "prisma generate"
  }
}
```

I suggest using the `prestart` hook to be on the safe side.

**Comment by timsuchanek** [comment]
The issue that @jimthedev and @flybayer face is separate and will be tracked here: https://github.com/prisma/prisma/issues/5299

**Comment by timsuchanek** [comment]
We will add some documentation around this, but apart from that you, unfortunately, have to go with one of the fixes described above.

If this doesn't work for you @croossin , please let me know and I'll reopen the issue.
