### ISSUE TITLE
TypeScript No Exported Member "join"

### ISSUE THREAD

**Issue by mloberg** [prisma/prisma#5268]
## Bug description

When upgrading to 2.15, I get the following error:

`Module '"../../node_modules/@prisma/client"' has no exported member 'join'.`

## How to reproduce

1. Upgrade to 2.15
2. Compile and see error

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.15.1
- Prisma version: 2.15.0

**Comment by pantharshit00** [comment]
This is expected as deprecation we introduced in https://github.com/prisma/prisma/releases/tag/2.12.0 (Prisma namespace one) got removed in 2.15. You can now import helpers like so:
```ts
import { Prisma } from '@prisma/cli';

const test = await prisma.queryRaw`${Prisma.join(/* ..... */)}`;
```

**Comment by belgattitude** [comment]
I would reopen the issue cause the doc is misleading:

![image](https://user-images.githubusercontent.com/259798/106142741-24699f80-6172-11eb-8740-a0dd5ffcb06a.png)


https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#tagged-template-helpers

**Comment by pantharshit00** [comment]
@belgattitude That will be addressed via https://github.com/prisma/docs/issues/1232. I informed the people working on docs yesterday already.
