### ISSUE TITLE
Prisma not combining queries for GraphQL server, leading to N+1 issues

### ISSUE THREAD

**Issue by dickfickling** [prisma/prisma#5274]
## Bug description
I've created a small server running Prisma, Apollo, and type-graphql with a few entities. A simple fetch that traverses multiple edges on the graph causes N+1 db queries when I'd have expected Prisma to combine them.

## How to reproduce

Check out https://github.com/dickfickling/prisma-n1 for a repro. I'm not sure whether the culprit is within prisma, type-graphql, typegraphql-prisma, or somewhere in the way i'm structuring my code. Regardless if you install deps and run npm run test in this example, you'll see the test creates 10 users with 10 posts each, and then fetches the feed, which should return all 100 posts and their attached users.  The test passes, but you see a massive number of queries logged.

There's a github action workflow that demonstrates this as well.

## Expected behavior

I'd expect a constant number of db queries to run

## Prisma information

prisma 2

## Environment & setup

- OS: debian/ubuntu
- Database: mysql
- Node.js version: reproduced on 14 and 15
- Prisma version: 2.15.0

**Comment by sahildeliwala** [comment]
I'm facing the same issue with same environment setup. Prisma's `findUnique` just runs queries individually with `SELECT .... WHERE user.id = 2` instead of batching them like `SELECT... WHERE user.id in [1,2,3,4]`

**Comment by timsuchanek** [comment]
Thanks for reporting! We'll have a look.
Related: https://github.com/prisma/prisma-examples/issues/2464

**Comment by janpio** [comment]
2 more cases were reported in https://github.com/prisma/prisma/issues/5485 - one was explicitly confirmed to be the same problem as described above.

**Comment by timsuchanek** [comment]
Thanks everyone for reporting. We just implemented a fix for this. It's available in `@prisma/client@2.17.0-dev.40`.
Please let us know if that fixes it for you!
@dickfickling in your project I also needed to add the `prisma` for the typegraphql generator.

**Comment by dickfickling** [comment]
it works! thanks @timsuchanek

**Comment by timsuchanek** [comment]
Awesome @dickfickling! Thanks again for the reproduction and also for getting back to me!
That's not a given.

**Comment by janpio** [comment]
Can confirm that the reproduction from https://github.com/prisma/prisma/issues/5485 is also back to normal performance with `2.17.0-dev.67` 👍
