### ISSUE TITLE
Argument M is out of range for Native type NVarChar(4000) of SQL Server

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#5287]
## Bug description

`prisma introspect` with native types produces invalid schema. 

## How to reproduce

1. Deploy this SQL

```sql
CREATE TABLE [dbo].[ErrorLog](
	[ErrorLogID] [int] IDENTITY(1,1) NOT NULL,
	[ErrorMessage] [nvarchar](4000) NOT NULL,
 CONSTRAINT [PK_ErrorLog_ErrorLogID] PRIMARY KEY CLUSTERED 
(
	[ErrorLogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

2. Run `prisma introspect` (with `nativeTypes` flag)

3. Generated `schema.prisma`

```
model ErrorLog {
  ErrorLogID   Int    @id @default(autoincrement()) @db.Int
  ErrorMessage String @db.NVarChar(4000)
}
```

4. Run `prisma validate`

```
Error: Error: Schema parsing
error: Argument M is out of range for Native type NVarChar(4000) of SQL Server: Length can range from 1 to 2000. For larger sizes, use the `Max` variant.
  -->  schema.prisma:13
   | 
12 |   ErrorLogID   Int    @id @default(autoincrement()) @db.Int
13 |   ErrorMessage String @db.NVarChar(4000)
14 | }
```

-->

## Prisma information

```
(base) divyendusingh [prisma-explitit-panic]$ yarn prisma --version                                                                                                                  130 ↵
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/triage/prisma-explitit-panic/node_modules/.bin/prisma --version
  tryLoadEnv Environment variables not found at null +0ms
  tryLoadEnv Environment variables not found at undefined +1ms
  tryLoadEnv No Environment variables loaded +0ms
@prisma/cli          : 2.16.0-dev.17
@prisma/client       : 2.16.0-dev.17
Current platform     : darwin
Query Engine         : query-engine d621d9b01ebb4c8fcd3adeaf3421e0149c676c58 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli d621d9b01ebb4c8fcd3adeaf3421e0149c676c58 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core d621d9b01ebb4c8fcd3adeaf3421e0149c676c58 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt d621d9b01ebb4c8fcd3adeaf3421e0149c676c58 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.343.0
Preview Features     : nativeTypes
```

Databases where this happens: 

- https://github.com/prisma/database-schema-examples/blob/main/mssql/adventureWorks2012/schema.sql
- https://github.com/prisma/database-schema-examples/blob/main/mssql/adventureWorks2016/schema.sql
- https://github.com/prisma/database-schema-examples/blob/main/mssql/adventureWorks2014/schema.sql
- https://github.com/prisma/database-schema-examples/blob/main/mssql/adventureWorks2017/schema.sql
- https://github.com/prisma/database-schema-examples/blob/main/mssql/adventureWorks2019/schema.sql
- https://github.com/prisma/database-schema-examples/blob/main/mssql/sonarqube/schema.sql

**Comment by tomhoule** [comment]
@pimeys do you have an idea how this can happen?

**Comment by tomhoule** [comment]
Candidating this so we can research a bit more

**Comment by albertoperdomo** [comment]
Should be fixed now? Let's confirm @pimeys

**Comment by janpio** [comment]
Note: We can also confirm looking at Introspection CI results where this came from.

**Comment by pimeys** [comment]
This was fixed in https://github.com/prisma/prisma-engines/pull/1585 and is fixed in Prisma version 2.16. Tested following @divyenduz steps here, and here's the `prisma validate` output:

```bash
❯ npx prisma validate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
The schema at /home/pimeys/code/bug-reproductions/migration-5287/prisma/schema.prisma is valid 🚀
```

**Comment by janpio** [comment]
For @divyenduz to confirm as well this does not appear in Introspection CI any more at all.

**Comment by divyenduz** [comment]
No longer present in the Introspection CI.
