### ISSUE TITLE
`ALTER TYPE` enum migrations fail in PostgreSQL

### ISSUE THREAD

**Issue by defrex** [prisma/prisma#5290]
## Bug description

Using migrations from version `2.14`, I updated an enum to add a few more values.

That generated the following migration.

```sql
-- AlterEnum
ALTER TYPE "account_type_enum" ADD VALUE 'Giving';
ALTER TYPE "account_type_enum" ADD VALUE 'Parent';
ALTER TYPE "account_type_enum" ADD VALUE 'Saving';
ALTER TYPE "account_type_enum" ADD VALUE 'Spending';

-- AlterTable
ALTER TABLE "account" ALTER COLUMN "type" SET DEFAULT E'Spending';
```

Unfortunately, when running this, I get the following error from Postgres.

```
Database error: Error querying the database: db error: ERROR: ALTER TYPE ... ADD cannot run inside a transaction block
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:174
   1: sql_migration_connector::sql_database_migration_inferrer::validate_migrations
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:89
   2: migration_core::api::DiagnoseMigrationHistory
             at migration-engine/core/src/api.rs:109
```

I can confirm that reducing the migration to a single `ALTER TYPE` solves the issue.

## How to reproduce

1. Use Postgres
2. Create an enum
3. Add multiple new values
4. Generate a migration
5. Run the migration

## Expected behavior

New enum values should be added.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL 11
- Node.js version: 4.15
- Prisma version:
```
@prisma/cli          : 2.14.0
@prisma/client       : 2.14.0
Current platform     : darwin
Query Engine         : query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.332.0
```

**Comment by tomhoule** [comment]
Hi @defrex! Migrate will not run migration scripts in a transaction by default, so it is not clear to me how this error happens. Did you add a `BEGIN` to the SQL migration script? If not, we have to investigate this

**Comment by kuskoman** [comment]
I have similiar problem- it is happening only on environment inside k8s cluster and I can't replicate it on localhost

migration causing the problem-
```sql
-- AlterTable
ALTER TABLE "AuthTokens" ADD COLUMN     "valid" BOOLEAN NOT NULL DEFAULT true;
```

**Comment by tomhoule** [comment]
Hi @kuskoman , can you give us more details on the setup? Postgres version and whether you run some proxy like pgbouncer would be interesting

**Comment by kuskoman** [comment]
@tomhoule I am using this helm chart: https://github.com/bitnami/charts/tree/master/bitnami/postgresql with version 10.2.1 (it's chart version, not postgres version), which is using postgres [11.10.0-debian-10-r52](https://hub.docker.com/r/bitnami/postgresql)

guess it may be some kind of configuration problem on my side, but since I saw a similar issue from just few days I felt like my problem may be useful for someone, so I added the comment.

```
        "@prisma/client": "2.15.0",
```

**Comment by tomhoule** [comment]
Thanks for the details, I added labels to the issue so we can prioritize it next week :)

**Comment by pimeys** [comment]
My first test and findings with Prisma 2.16:

We can define a data model:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Test {
  id Int @default(autoincrement()) @id
  a  A
}

enum A {
  B
}
```

This migrates correctly, and generates the following SQL:

```sql
-- CreateEnum
CREATE TYPE "A" AS ENUM ('B');

-- CreateTable
CREATE TABLE "Test" (
    "id" SERIAL NOT NULL,
    "a" "A" NOT NULL,

    PRIMARY KEY ("id")
);
```

Now, we add more variants to the enum, the new data model being:

```prisma
model Test {
  id Int @default(autoincrement()) @id
  a  A
}

enum A {
  B
  C
  D
  E
  F
}
```

This generates, again, kind of correct SQL:

```sql
-- AlterEnum
ALTER TYPE "A" ADD VALUE 'C';
ALTER TYPE "A" ADD VALUE 'D';
ALTER TYPE "A" ADD VALUE 'E';
ALTER TYPE "A" ADD VALUE 'F';
```

We can even execute them in psql, but running the migrations against PostgreSQL 13 on Docker gives:

```
Migration `20210203171713_more_enums` failed to apply cleanly to a temporary database.
Error:
Database error: Error querying the database: db error: ERROR: ALTER TYPE ... ADD cannot be executed from a function or multi-command string
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:192
   1: sql_migration_connector::sql_database_migration_inferrer::validate_migrations
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:70
   2: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:100
```

What we try to do here is to execute the whole file as-is in one PostgreSQL query using the text protocol. PostgreSQL doesn't allow this, and we need to find some product decision how we handle them. Stay tuned.

**Comment by pimeys** [comment]
We can of course combine these type changes into one statement, as described in the manual.

https://www.postgresql.org/docs/current/sql-altertype.html

I will try that out tomorrow.

**Comment by pimeys** [comment]
It seems that this restriction is not valid anymore for PostgreSQL versions higher than 11. On versions 12 and 13 I can successfully execute this migration.

**Comment by albertoperdomo** [comment]
Created https://github.com/prisma/prisma/issues/5543 for us to add a comment with a warning, suggesting users of PostgreSQL 11 and earlier versions to only add one ENUM value at a time in each migration.
