### ISSUE TITLE
uncheckedScalarInputs: XOR not working?

### ISSUE THREAD

**Issue by wminshew** [prisma/prisma#5294]
## Bug description

The XOR functionality to allow either unchecked scalars xor regular prisma relations doesn't appear to be working for me

the function:
```
export const createInvestor = ({ input: { companyId, email } }) => {
  return db.investor.create({
    data: {
      company: {
        connect: { id: companyId },
      },
      investor: {
        connectOrCreate: {
          where: { email },
          create: { email },
        },
      },
    },
  })
}
```

the error:
```
api | Error:
api | Invalid `prisma.investor.create()` invocation:
api |
api | {
api |   data: {
api |     company: {
api |     ~~~~~~~
api |       connect: {
api |         where: {
api |           companyId: 'dc7085fb-62e0-405c-bb0f-a4d33fa6bcae'
api |         }
api |       }
api |     },
api |     investor: {
api |     ~~~~~~~~
api |       connectOrCreate: {
api |         where: {
api |           email: 'test@gmail.com'
api |         },
api |         create: {
api |           email: 'test@gmail.com'
api |         }
api |       }
api |     },
api | +   investorId: String,
api | +   companyId: String,
api | ?   createdAt?: DateTime,
api | ?   updatedAt?: DateTime
api |   }
api | }
api |
api | Unknown arg `company` in data.company for type InvestorUncheckedCreateInput. Did you mean `companyId`?
api | Unknown arg `investor` in data.investor for type InvestorUncheckedCreateInput. Did you mean `investorId`?
api | Argument investorId for data.investorId is missing.
api | Argument companyId for data.companyId is missing.
```

## Expected behavior

Prisma should recognize I'm not using unchecked scalars

## Prisma information

```
model Investor {
  investor    User  @relation(fields: [investorId], references: [id])
  investorId    String
  company    Company  @relation(fields: [companyId], references: [id])
  companyId    String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@id([investorId, companyId])
}
```

## Environment & setup

- OS: MacOS 10.15.5
- Database: Postgres 12.5
- Node.js version: 14.15.4
- Prisma version: 2.11.0 [used through redwoodjs]
- Redwood version: 0.23

Happy to provide further information if helpful, have not yet tried to re-create in a minimal repo

**Comment by LoriKarikari** [comment]
I'm having the same issue with Prisma 2.15.

**Comment by DustinJSilk** [comment]
I'm having this same issue now. I cant get my nested updates to work. Is there a work around I'm missing here?

**Comment by thrant** [comment]
Same here, just upgraded to 2.15 and Creates & Updates that were previously working started hitting the types **<type>Unchecked<Create/Update>Input** instead of expected **<type><Create/Update>Input** 

Perhaps related to the "uncheckedScalars" coming out of preview stage? Any way to disable that feature?

**Comment by chrissisura** [comment]
I agree that this shortcut causes some really weird behaviour in the typescript compiler. 
1. You sometimes have to cast to the normal CreateInput Type in order to not get an error message 
2. The error messages coming from the XOR are unreadable (due to the exclusive without listing in the error message) 
3. The upside is really low as mentioned in another post for the simple reason that you can not mix unchecked with normal in a single model, which makes it hard to use, since you then sometimes have to rewrite the entire query just to add something

**Comment by wminshew** [comment]
@chrissisura just to confirm, if using vanilla javascript there's no way to explicitly cast here right?

**Comment by chrissisura** [comment]
@wminshew there is not. But in my experience when I got runtime error messages like the log from thrant I made a mistake in my code somewhere in the nested objects (i.e. using the wrong key) which can be confusing, since the error messages show the highlight the mistake in the highest layer

**Comment by chrissisura** [comment]
@wminshew but judging from your code it doesn't look like it since you're mostly only connecting ids

**Comment by nsebs** [comment]
I'm having the same problem. I'm using NestJS.

This is the schema (part)
```ts
model Post {
  id          String      @id @default(cuid())
  createdAt   DateTime    @default(now())
  title       String
  published   Boolean     @default(false)
  author      User        @relation(fields: [authorId], references: [id])
  authorId    String
  categories  Category[]  @relation(references: [id])
}

model Category {
  id          String      @id @default(cuid())
  name        String
  posts       Post[]      @relation(references: [id])
}
```
This are the generated types:
```ts
  export type PostUpdateArgs = {
    select?: PostSelect | null
    include?: PostInclude | null
    data: XOR<PostUncheckedUpdateInput, PostUpdateInput>
    where: PostWhereUniqueInput
  }
```

This is the controller:
```ts
  @Put(':id')
  update(
    @Param('id') where: Prisma.PostWhereUniqueInput,
    @Body() data: Prisma.PostUpdateInput,
  ): Promise<Posts> {
    return this.prisma.post.update({ where, data });
  }
```

And this is the error thrown by prisma:

```text
Invalid `prisma.post.create()` invocation:

{
  data: {
    title: 'Sword fighting',
    authorId: 'ckkosq7kc0014hlt2s3f18ljx',
    categories: [
    ~~~~~~~~~~
      'ckkp6apog0025ukt25igvcro1'
    ]
  }
}

Unknown arg `categories` in data.categories for type PostUncheckedCreateInput. Available args:

type PostUncheckedCreateInput {
  id?: String
  createdAt?: DateTime
  title: String
  published?: Boolean
  authorId: String
}
```
Prisma env:
```text
❯ npx prisma --version     
Environment variables loaded from .env
prisma               : 2.16.0
@prisma/client       : 2.16.0
Current platform     : rhel-openssl-1.1.x
Query Engine         : query-engine 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/query-engine-rhel-openssl-1.1.x)
Migration Engine     : migration-engine-cli 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-rhel-openssl-1.1.x)
Introspection Engine : introspection-core 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.1.x)
Format Binary        : prisma-fmt 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-rhel-openssl-1.1.x)
Studio               : 0.346.0
```
I made this project to check if the error can be reproduced and I'm always able to reproduce it when trying to create or update a model with a many-to-many relation, regardless of how that relation is defined (implicit, explicit, with or without the `@relation()` attribute).

**Comment by wminshew** [comment]
@nsebs I might be wrong but afaict `uncheckedScalars` doesn't handle "many" relationships at all -- no arrays of IDs etc, only single connection cases (so in your case not a bug but you could open a feature request). Since you have a many relationship to `categories`, you will have to make sure you use `PostCreateInput` type which will prevent you from using `authorId`. You may have to cast it explicitly if its still giving you problems

**Comment by nsebs** [comment]
But I am using `PostCreateInput` as the type of data passed to `prisma.post.create()`... or I don't understand the docs.

@wminshew Maybe my issue is only *related* to yours since I'm not trying to use the left side of the `XOR` in this case (the unchecked version). But the problem as I understand it is that the `XOR` doesn't properly check for all the types... unless that's not how it's supposed to be used and I understood it wrong :thinking:.

This is how I'm using it:
```ts
  @Put(':id')
  update(
    @Param('id') id: string,
    @Body() data: Prisma.PostUpdateInput,    //  <-- here I'm specifying the type
  ): Promise<Posts> {
    return this.prisma.post.update({ where: { id }, data });
  }
```
And when I request the resource update:
```bash
curl -X PUT \
  http://localhost:3000/posts/ckkovbwyp0003kvt20bdm0a72 \
  -H 'Content-Type: application/json' \
  -d '{"categories": ["ckkp6a4ud0016ukt2imimid4t"]}'
```
the error thrown appears to indicate that only the left side of the `XOR` was considerer; it doesn't mention that I passed the wrong data/info/type to `categories` or something along the lines, but that the argument `categories` itself doesn't exist:
```text
Unknown arg `categories` in data.categories for type PostUncheckedUpdateInput. Available args:

type PostUncheckedUpdateInput {
  id?: String | StringFieldUpdateOperationsInput
  createdAt?: DateTime | DateTimeFieldUpdateOperationsInput
  title?: String | StringFieldUpdateOperationsInput
  published?: Boolean | BoolFieldUpdateOperationsInput
  authorId?: String | StringFieldUpdateOperationsInput
}
```

If I remove the `@relation` attribute, this are the generated types:
```ts
export type PostUpdateArgs = {
  select?: PostSelect | null
  include?: PostInclude | null
  data: XOR<PostUncheckedUpdateInput, PostUpdateInput>    //  <-- the right side of the `XOR` is my specified type
  where: PostWhereUniqueInput
}

export type PostUncheckedUpdateInput = {
  id?: StringFieldUpdateOperationsInput | string
  createdAt?: DateTimeFieldUpdateOperationsInput | Date | string
  title?: StringFieldUpdateOperationsInput | string
  published?: BoolFieldUpdateOperationsInput | boolean
  authorId?: StringFieldUpdateOperationsInput | string
}

export type PostUpdateInput = {
  id?: StringFieldUpdateOperationsInput | string
  createdAt?: DateTimeFieldUpdateOperationsInput | Date | string
  title?: StringFieldUpdateOperationsInput | string
  published?: BoolFieldUpdateOperationsInput | boolean
  author?: UserUpdateOneRequiredWithoutPostsInput
  categories?: CategoryUpdateManyWithoutPostsInput
}

export type CategoryUpdateManyWithoutPostsInput = {
  create?: XOR<Enumerable<CategoryUncheckedCreateWithoutPostsInput>, Enumerable<CategoryCreateWithoutPostsInput>>
  connectOrCreate?: Enumerable<CategoryCreateOrConnectWithoutpostsInput>
  upsert?: Enumerable<CategoryUpsertWithWhereUniqueWithoutPostsInput>
  connect?: Enumerable<CategoryWhereUniqueInput>
  set?: Enumerable<CategoryWhereUniqueInput>
  disconnect?: Enumerable<CategoryWhereUniqueInput>
  delete?: Enumerable<CategoryWhereUniqueInput>
  update?: Enumerable<CategoryUpdateWithWhereUniqueWithoutPostsInput>
  updateMany?: Enumerable<CategoryUpdateManyWithWhereWithoutPostsInput>
  deleteMany?: Enumerable<CategoryScalarWhereInput>
}
```

**Comment by nsebs** [comment]
After reading more of the docs I realized that I was trying to use the types in the wrong way:

https://www.prisma.io/docs/concepts/components/prisma-client/working-with-generated-types#problem-using-variations-of-the-generated-model-type

The `PostUpdateInput` and `PostCreateInput` are misleading because they're not going to contain the relation with `categories` because is not include by default, even when is explicit on the signature of the type :confused: 

Which means that we cannot use the generated types as DTOs :disappointed:

**Comment by wminshew** [comment]
from what I've seen elsewhere, if you have any error in your types it'll only flag the first type of the XOR in the message (which, as you've noted, is unfortunately not very helpful)

In your case, I think the issue might be that you're missing a `connect` or `create` or `connectOrCreate`. I would expect the below to work:

```
categories: {
  create: {
    id: 'ckkp6apog0025ukt25igvcro1'
  }
}
```

related to your last point, yes I don't think these types are usable as DTOs

**Comment by nsebs** [comment]
Yes, exactly.

Sorry about the noise in this issue.

**Comment by meirianto** [comment]
I am also having this issue. Tried a workaround by casting everything as the normal type and not the new `unchecked type` when passing to the `create` field.
const customerCreate: Prisma.CustomerCreateInput = {
    user: {
      create: userCreate as Prisma.UserCreateWithoutCustomerInput,
    },
    }

**Comment by meirianto** [comment]
I am also having this issue. It defaults to assuming I'm using the unchecked type instead of the checked type.

```
const customerCreate: Prisma.CustomerCreateInput = {
    status: "prospect",
    user: {
      create: userCreate,
    },
    details: {
      create: customerDetailsCreate,
    },
    programs: {
      create: customerProgramCreate,
    },
  };
 const newCustomer = await ctx.db.customer.create({
    data: customerCreate,
  });
  ```

**Comment by meirianto** [comment]
> Yes, exactly.
> 
> Sorry about the noise in this issue.

I don't think you are wrong, you should be able to use `PostUpdateInput` as DTO with `categories` as a field.

**Comment by thrant** [comment]
Anyone found a way to disable this "uncheckedScalarInputs" feature totally? (since it's not a switchable preview feature anymore since 2.15).

Or how to force using the Checked models only, I think it was mentioned in some discussion but couldn't find instructions for it in the Prisma docs yet.

I personally don't really see any benefit to them in my current project (I'm totally happy doing "Object: { connect: { id: id } }" instead of "objectId: id"), and they are really making debugging the actual models a PITA since the error messages are all wrong.

**Comment by janpio** [comment]
> they are really making debugging the actual models a PITA since the error messages are all wrong.

Are there any issues for these? We would love to fix them.

**Comment by tommypater** [comment]
Hello, for me, it's ok but if one of id is undefined in my array of tags, i have the same error.

```javascript
connectOrCreate: tags.map((tag) => ({
  where: { id: tag.id || undefined },
  create: {
    color: tag.color,
    label: tag.label,
  },
})),
```
```javascript
tags: {
~~~~      connectOrCreate: [
  {   
    where: { id: undefined },   
    create: { color: '#fe5000', label: 'ff' }
    }
],

Unknown arg `category` in data.category for type ArticleUncheckedUpdateInput.
Did you mean `categoryId`? Available args:type ArticleUncheckedUpdateInput { 
id?: Int | IntFieldUpdateOperationsInput 
createdAt?: DateTime | DateTimeFieldUpdateOperationsInput 
updatedAt?: DateTime | DateTimeFieldUpdateOperationsInput
seoTitle?: String | NullableStringFieldUpdateOperationsInput | Null 
seoDescription?: String | NullableStringFieldUpdateOperationsInput | Null 
title?: String | StringFieldUpdateOperationsInput 
slug?: String | StringFieldUpdateOperationsInput 
image?: String | NullableStringFieldUpdateOperationsInput | Null 
content?: String | StringFieldUpdateOperationsInput 
authorId?: Int | IntFieldUpdateOperationsInput 
categoryId?: Int | IntFieldUpdateOperationsInput}
```

**Comment by timsuchanek** [comment]
Thanks for all the comments! Just to clarify, the `XOR` is unrelated to the errors you are seeing, as they are all runtime errors coming from the Prisma Client type checker, not the TypeScript compiler.

I tried out to reproduce the first comment, but it's a bit hard, as the whole schema and context is missing.

Could someone create a reproduction in a little repo? That would help us a lot to fix this!

**Comment by nsebs** [comment]
@timsuchanek sorry to bother you, but I would love to confirm if it's wrong or not to think that we can use the generated types as DTOs (as I was trying in this example: https://github.com/prisma/prisma/issues/5294#issuecomment-772846373).

The more I read the more I get confused because some docs/issues/talks/names of stuff/etc lead me to believe it's ok, and then reading more (or trying it) make me think it's not ok, and at this point I'm just lost :sweat_smile:.

**Comment by timsuchanek** [comment]
@nsebs nothing to bother, that's a good question! Could you create a separate issue please?
Because it seems unrelated to this one.

**Comment by timsuchanek** [comment]
Thanks everyone for reporting!
We just released a fixed version in `@prisma/client@dev`. Please check it out! If this is not fixed for you, please let us know and we reopen the issue.

**Comment by jagoncalves14** [comment]
Hi @timsuchanek!

I think I'm running with this exact same issue.

This is the error I get when I try to create a Post.
![image](https://user-images.githubusercontent.com/17235977/114003491-af8fa180-9855-11eb-81d6-9dd077c3b0b1.png)

Weirdly enough, I'm able to **Update** a post with categories, but can't **Create**.

Here are the informations related to the Create Post:

## Create Post

### Types in Prisma's `index.d.ts`:

```
export type PostCreateInput = {
    createdAt?: Date | string
    published?: boolean
    title: string
    content?: string
    author: UserCreateNestedOneWithoutPostsInput
    categories?: CategoryCreateNestedManyWithoutPostsInput
    tags?: TagCreateNestedManyWithoutPostsInput
}

export type PostUncheckedCreateInput = {
    id?: number
    createdAt?: Date | string
    authorId: number
    published?: boolean
    title: string
    content?: string
}
```

### Mutation:

```
const CreatePost = z
  .object({
    title: z.string(),
    content: z.string(),
    published: z.boolean(),
    categories: z.array(
      z.object({
        name: z.string(),
        id: z.number().int(),
      }),
    ),
  })
  .nonstrict()

export default resolver.pipe(
  resolver.zod(CreatePost),
  resolver.authorize(),
  async ({id, ...data}) => {
    const payload = {
      ...data,
      categories: {
        connectOrCreate: data.categories.map((cat) => ({
          where: {id: cat.id},
          create: {
            name: cat.name,
          },
        })),
      },
    }

    return await db.post.create({
      data: payload,
    })
  },
)
```


## Update Post

### Types in Prisma's `index.d.ts`:

```
export type PostUpdateInput = {
    createdAt?: DateTimeFieldUpdateOperationsInput | Date | string
    published?: BoolFieldUpdateOperationsInput | boolean
    title?: StringFieldUpdateOperationsInput | string
    content?: StringFieldUpdateOperationsInput | string
    author?: UserUpdateOneRequiredWithoutPostsInput
    categories?: CategoryUpdateManyWithoutPostsInput
    tags?: TagUpdateManyWithoutPostsInput
}

export type PostUncheckedUpdateInput = {
    id?: IntFieldUpdateOperationsInput | number
    createdAt?: DateTimeFieldUpdateOperationsInput | Date | string
    authorId?: IntFieldUpdateOperationsInput | number
    published?: BoolFieldUpdateOperationsInput | boolean
    title?: StringFieldUpdateOperationsInput | string
    content?: StringFieldUpdateOperationsInput | string
}
```

### Mutation:

```
const UpdatePost = z
  .object({
    id: z.number().int(),
    title: z.string(),
    content: z.string(),
    published: z.boolean(),
    categories: z.array(
      z.object({
        name: z.string(),
        id: z.number().int(),
      }),
    ),
  })
  .nonstrict()

export default resolver.pipe(
  resolver.zod(UpdatePost),
  resolver.authorize(),
  async ({id, ...data}) => {
    delete data.authorId

    const payload = {
      ...data,
      categories: {
        set: [],
        connectOrCreate: data.categories.map((cat) => ({
          where: {id: cat.id},
          create: {
            name: cat.name,
          },
        })),
      },
    }

    return await db.post.update({where: {id}, data: payload})
  },
)
```


## And here is the Model Schema:
```
model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  authorId  Int
  published Boolean  @default(false)
  title     String
  content   String   @default("")

  author     User       @relation(fields: [authorId], references: [id])
  categories Category[]
  tags       Tag[]
}

model Category {
  id   Int    @id @default(autoincrement())
  name String

  posts Post[]
}
```

I can't understand why this is working in Update and not on Create when both Types are the same regarding to the `categories` field.
Maybe I'm doing something obviously wrong. Can someone help me out?

**Comment by janpio** [comment]
Best open a new issue with a full description of your situation and including the filled out issue template - much easier for us to handle @jagoncalves14 - thanks.

**Comment by omar-dulaimi** [comment]
@thrant Thanks a lot.

**Comment by aledalgrande** [comment]
FYI, I ran into the same case as https://github.com/prisma/prisma/issues/5294#issuecomment-769741760 where the error says it cannot recognize the input attribute:

1. didn't pass all of the required attributes to the `create` section of `connectOrCreate` by mistake
2. XOR tried checkedInputs (which has the relationship I was trying to connect or create, let's call it `x`)
3. checkedInputs failed, because the subschema for `x` was not respected
4. went to use uncheckedInputs, but that doesn't have rel `x` in it
5. XOR failed with unrecognized attribute error

This makes it very confusing and wouldn't have been able to find the source of the error if it wasn't for this thread.
