### ISSUE TITLE
Improvement: Optionally skip seeding during migrate reset

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#5317]
## Problem

Some users want to opt-out from seeding during migrate reset.
This has been suggested by a user [here](https://github.com/prisma/prisma/issues/4531#issuecomment-768718760)

## Suggested solution

Add a `--skip-seed` flag to `prisma migrate dev` or `prisma migrate reset` 

## Alternatives

No known alternatives or workarounds if there is a seed file

## Additional context

* https://github.com/prisma/prisma/issues/4531#issuecomment-768718760

**Comment by Jolg42** [comment]
To do:
- [ ] create a PR to update docs
