### ISSUE TITLE
Timeout error when attempting to get a connection from the database

### ISSUE THREAD

**Issue by calebbriggs** [prisma/prisma#5334]
## Bug description

Timeout error when attempting to get a connection from the database
Error:
Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter (https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#connection-pool). Current limit: 250, amount of connections currently in use: 21.

## How to reproduce

Load test any operation or query to the database

## Expected behavior

either have a higher threshold of a timeout or better connection management to be able to use the available connections

## Environment & setup

- OS:Linux
- Database: PostgreSQL
- Node.js version: v14.8.0
- Prisma  '2.15.0'

```

```

**Comment by janpio** [comment]
The `amount of connections currently in use: 21.` part of this error message is unfortunately wrong and will be removed in the next version. But the rest of the error message indicates that you are hitting a timeout when a query is waiting for a connection from the connection pool.

What kind of code are you running? Are you running many Prisma queries in parallel via `Promise.all` or similar?

You could try to add `pool_timeout=30` to your connection string to increase the timeout to 30 seconds (from a current default of 5 seconds) (or even `pool_timeout=0` to completely disable this).

**Comment by calebbriggs** [comment]
yea we are using a batch promises function  to where it basically does a promise.all for the batch size which is 250 queries at a time then on the the next 250. I am testing a throat library now that i found in one of your issues which in theory could be a better scenario but any fee. thanks for the pool_timeout that is extremely useful and must have missed that.

**Comment by janpio** [comment]
> thanks for the pool_timeout that is extremely useful and must have missed that.

It's a new, undocumented feature - so you did not. Please let me know if it helps with your use case or if you encounter other follow up problems.
