### ISSUE TITLE
Introspection from SQL dump

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#534]
A use case for a brownfield project can be availability of an SQL dump (but no running/existing database). 

A meaningful workflow can be to run introspection against the DB dump to generate a Prisma schema file and continue the normal development workflow from there. 

If the data is required though, at some point it will need to be imported into the database.

**Comment by matthewmueller** [comment]
Adding 2¢:

Just turning an SQL dump into a prisma schema would take a lot of work. We'd need to be able to parse raw SQL which we don't currently do. I'd propose that instead either run or instruct the use to run something like `pg_dump` against their database or our own and then use the database's introspection tools to get a Prisma schema.

**Comment by janpio** [comment]
Current idea: Tiny webservices that takes SQL dump and returns connection string, to be used in e.g. website that does SQL schema -> Prisma Schema conversion. Could also be used for normal Introspection of course (tell people via docs).
