### ISSUE TITLE
Prisma seed - add config for custom seed.ts file path

### ISSUE THREAD

**Issue by homoky** [prisma/prisma#5362]
Prisma 2.15.0

I have folder structure:
- package.json
- schema.prisma
- seed.ts

When I run `prisma db seed --preview-feature` it says `Create a seed.ts, .js, .sh or .go file in the prisma directory.`.

But I have prisma as a package with custom build dir so when I want to get prisma seed working I need to create another prisma folder and put seed.ts in it.

It would be greate to specify seed file path like `prisma db seed --path ./seed.ts --preview-feature`

**Comment by flybayer** [comment]
Related: https://github.com/prisma/prisma/issues/5213 (closed by not fixed)

**Comment by janpio** [comment]
@homoky How did you tell Prisma about the path of your `schema.prisma` file when you run e.g. `prisma generate`?

**Comment by homoky** [comment]
@janpio It works out of box, noo need to specify the path. In new prisma version this is fixed with `--schema` flag:

```
prisma db seed --preview-feature --schema=./schema.prisma
```

**Comment by janpio** [comment]
https://www.prisma.io/docs/guides/database/seed-database#how-to-seed-your-database-in-prisma

**Comment by Jarrodsz** [comment]
I also would like to set a custom path to a seed file since I have multiple seed files.

Why its the only simple way to do this is removed:
prisma:warn The "--schema" parameter is not used anymore by "prisma db seed" since version 3.0 and can now be removed.

Is there a workaround?
