### ISSUE TITLE
Prisma introspect not written delete_rule CASCADE  to schema.prisma

### ISSUE THREAD

**Issue by aldyrifaldi** [prisma/prisma#5364]
## Bug description
prisma introspect cannot write delete_rule CASCADE in schema.prisma file

## How to reproduce
1. Create Table used other migration library or .sql file  with relation column rule cascade on delete
2. after that, run `npx prisma introspect` 
3. and check the schema.prisma at relation column `ON DELETE CASCADE` not writen.

## Expected behavior
While run `npx prisma introspect` can write delete_rule in information_schema.REFERENTIAL_CONSTRAINTS

#### In other migration library
![image](https://user-images.githubusercontent.com/52684373/106356709-2f6c2d80-6334-11eb-8c5a-ec10885e83c5.png)
#### in mysql information_schema.REFERENTIAL_CONSTRAINTS
![image](https://user-images.githubusercontent.com/52684373/106356642-e0be9380-6333-11eb-8ab0-56312a8a0743.png)
#### result after run `npx prisma introspect`. This file schema.prisma
![image](https://user-images.githubusercontent.com/52684373/106356671-0350ac80-6334-11eb-9725-211de456f8dd.png)

## Environment & setup

- OS:  Debian (deepin v20.1)
- Database:  MariaDB
- Node.js version:  v14.15.3 LTS
- Prisma version: v2.15.0
- (Other migration) db-migrate: v0.11.12
- Express:  v4.16.1

```

```

**Comment by janpio** [comment]
Yes, Prisma schema does not support cascading deletes yet in any way: https://github.com/prisma/prisma/issues/2810
