### ISSUE TITLE
Allow to control field type

### ISSUE THREAD

**Issue by lcswillems** [prisma/prisma#5399]
## Problem

I have a table `Post` with a field `publishedAt` of time `DateTime`. The Javascript type given to this field is `Date`. However, I would like it to be string or even number (timestamp). How could I do this without having to manually map the field?

## Additional context

I use Next.js. In `getServerSideProps`, I request latest posts and return them. However, as the `publishedAt` field is of type Date, I get an error from Next.js saying it is not able to stringify it.

**Comment by Jolg42** [comment]
So Next.js cannot serialize dates, you'll need to use https://github.com/blitz-js/superjson#using-with-nextjs (there is a Next.js example in the docs).

Related https://github.com/vercel/next.js/discussions/11498#discussioncomment-146987

That should work, let me know if if this should be opened again.

**Comment by lcswillems** [comment]
Thank you @Jolg42 for your answer! It is what I ended up doing.
