### ISSUE TITLE
ConnectorError issue happening irregularly 

### ISSUE THREAD

**Issue by cypcz** [prisma/prisma#5418]
## Bug description
Lately, we started to experience DB connection issues in production. We're not sure what's causing the problem as the error message is not very descriptive. We have a suspicion it might caused by too many DB connections, but we're not sure. The error message is following:

```
"Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) }) Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
    at PrismaClientFetcher.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:79359:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

I was able to identify piece of code for which it's happening sometimes. It's a simple DB call:
```
  const updatedOrder = await prisma.order.update({
    where: { id: orderId },
    data: { shortId: orderShortId, tookanTaskId },
    include: {
      timeslot: true,
      braintreeTransactions: true,
    },
  })
```

## How to reproduce
Happens randomly.

## Environment & setup

- OS: Google Cloud Run
- Database: PostgreSQL
- Node.js version: 12
- Prisma version: 2.12.1

**Comment by pantharshit00** [comment]
@cypcz Can you please tell me where your database is hosted and whether you are using a connection pooler like pgbouncer with it?

**Comment by cypcz** [comment]
@pantharshit00 the database is hosted on GCP (Cloud SQL) as PostgreSQL 12, we're not using any connection pooler.

**Comment by tre-dev** [comment]
Got the same error today, hosted on AWS Aurora Serverless. Not using a connection pooler.

**Comment by cypcz** [comment]
We found out, that the error is happening even when our server and database aren't under heavy load (e.g. during the night).

@pantharshit00 do you have any idea, what might be the cause, please? I'd like to help with the resolution as this very troublesome issue.

**Comment by pantharshit00** [comment]
That is really odd. I just noticed you are using 2.12. Can you try again with latest version? We have tweaked that area a bit which should resolve the issue.

**Comment by cypcz** [comment]
Thanks, we're already working on the update. I'll post here if it helped or not.

**Comment by janpio** [comment]
Information about the PR that closed this:
https://github.com/prisma/prisma/issues/6329#issuecomment-815012006

Feel free to reply here again if the problem is not solved/better for you and we can reopen the issue of course.
