### ISSUE TITLE
prisma db `seed` command Not Exist (2.14.0)

### ISSUE THREAD

**Issue by Arkamis** [prisma/prisma#5421]
## Error on documentation
Hello, I tried following the steps explained on the [seeding your database with prisms client guide](https://www.prisma.io/docs/guides/prisma-guides/seed-database#set-up-seeding-in-javascript) but I got the following results when I tried the step 3.
![Image explaining the output when tried the command prisma db seed](https://user-images.githubusercontent.com/37283793/106607252-b84bba80-6528-11eb-9c8f-9f7d5becf8b2.png)

Following [this issue](https://github.com/prisma/docs/issues/1170) I notice that probably there is an error in the documentation. 

@Jolg42 [Provided an example for JS](https://github.com/Jolg42/prisma-seed-example/tree/main/javascript) that says that I need to create the seed command on the _package.json_ file instead of the `prisma db seed` command
![image shows the seed command example](https://user-images.githubusercontent.com/37283793/106608659-4aa08e00-652a-11eb-8938-431955d15157.png)

**Comment by Jolg42** [comment]
Hi @Arkamis sorry for the confusion, let me know if this is better:

We actually added the "integrated" seed flow into migrate with 2.15.0 so you'll need to upgrade (more info in release notes https://github.com/prisma/prisma/releases/tag/2.15.0)

With 2.15 `db seed` should work without the need of a "seed" script in your package.json.

**Comment by Jolg42** [comment]
I'll close this for now, but I'm happy to reopen or answer questions if needed.
