### ISSUE TITLE
Error using totvs database: `Couldn\'t parse default value`

### ISSUE THREAD

**Issue by JaimersonCabral** [prisma/prisma#5423]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.15.4           | 
| Prisma CLI  | 2.15.0             | 
| Binary      | e51dc3b5a9ee790a07104bec1c9477d51740fe54| 

## Error
```
Error: [libs/sql-schema-describer/src/mssql.rs:264:30] called `Result::unwrap()` on an `Err` value: "Couldn\'t parse default value: `CREATE DEFAULT DEF_DLOGICONULL AS 0\r\n`"
```

**Comment by Jolg42** [comment]
Hi @JaimersonCabral 

Could you add your schema?

Also which command did you run?

**Comment by tomhoule** [comment]
note: should be @default(dbgenerated("..."))

**Comment by pimeys** [comment]
Looking into this today.

**Comment by pimeys** [comment]
I can replicate the bug. There seems to be another way of setting default values in SQL Server. Typically, we create defaults like this:

```sql
create table cats (
    id int identity primary key,
    name nvarchar(255) constraint DF_cat_name DEFAULT 'musti'
);
```

There is another way of creating default values too in SQL Server, you can define them beforehand, and use a stored procedure to set them to a column:

```sql
CREATE DEFAULT catcat AS 'musti';

CREATE TABLE cats (
    id INT IDENTITY PRIMARY KEY,
    name NVARCHAR(255)
);

sp_bindefault 'catcat', 'dbo.cats.name';
```

So, this kind of makes our migrations a bit problematic. We'd like to have the default values in the data model, and then point to them from the column declaration to get the correct result. I need to discuss this a bit with the team, if we could find a nice and easy solution, or will this stretch to a complete new feature.

**Comment by pimeys** [comment]
Our decision for now is to ignore the default values during introspection for these fields. This means, that in the data model the field will not have `@default` attribute. If you later on want to change the default value in the data model, the migration needs to be done manually to the database.

We might introduce something to represent this kind of default values later on, but I wouldn't expect it that quickly.

**Comment by pimeys** [comment]
Documentation change for this: https://github.com/prisma/docs/pull/1348
