### ISSUE TITLE
Error in migration engine: `[libs/datamodel/core/src/transform/helpers/value_validator.rs:202:26] Should only be empty or single String.`

### ISSUE THREAD

**Issue by muradap786** [prisma/prisma#5424]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`migrate dev --name init --preview-feature`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.15.1           | 
| Prisma CLI  | 2.16.0             | 
| Binary      | a973e24a4e5194f8fe3301bfa7ff982b24f97c05| 

## Error
```
Error: Error in migration engine.
Reason: [libs/datamodel/core/src/transform/helpers/value_validator.rs:202:26] Should only be empty or single String.

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

```
Reason: [libs/datamodel/core/src/transform/helpers/value_validator.rs:202:26] Should only be empty or single String.

**Comment by Jolg42** [comment]
Hi @muradap786 

Could you post your schema.prisma here so we can try to reproduce?
