### ISSUE TITLE
Ability to index longText columns

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#5434]
## Problem

MySQL does not support indexing long string field, e.g. text. There is an option to partially index the column (first n characters) but Prisma does not support this.
 
## Suggested solution

TBD

## Alternatives

TODO

## Additional context

* https://github.com/prisma/prisma/issues/5288

**Comment by pimeys** [comment]
Alternative: https://dev.mysql.com/doc/refman/5.7/en/fulltext-search.html

**Comment by do4gr** [comment]
We just released a proposal on adding index capabilities to the PSL including length limits. We'd love to get some feedback: https://github.com/prisma/prisma/issues/9577
