### ISSUE TITLE
Order by relation aggregate (like count)

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#5439]
## Problem

We support ordering by a relation field, but not order by a relation aggregate.

For example: get all users, order by post count.

```ts
prisma.user.findMany({
  orderBy: {
    count: {
      post: 'asc'
    }
  }
})
```

## Additional context

- same request but for groupby: https://github.com/prisma/prisma/issues/5464
- order by relation field: https://github.com/prisma/prisma/issues/5008

**Comment by xbjfk** [comment]
Is there an equivalent for the other aggregates such as max, min and avg, or should I open a new issue?

**Comment by janpio** [comment]
Definitely a new issue if this does not exist yet.

**Comment by egeste** [comment]
oof

**Comment by mdarifulislamroni521** [comment]
> Definitely a new issue if this does not exist yet.
we need nested orderBy like:
`orderBy:{
     reviews:{
     rating:true  // rating is a number field it contain 0-5 . it should sort by good rating 
  }
}`
