### ISSUE TITLE
Allow to control JSON field type

### ISSUE THREAD

**Issue by lcswillems** [prisma/prisma#5449]
## Problem

I opened this issue recently: https://github.com/prisma/prisma/issues/5399 A workaround had been found in this particular case, but I encounter the same issue again.

I have a JSON field and I would like to assign a specific type I would have defined.

**Comment by luxaritas** [comment]
How much would your use case overlap with #3219?

**Comment by lcswillems** [comment]
It is exactly this use case but more general!

**Comment by janpio** [comment]
Closing this then, see you over at #3219
