### ISSUE TITLE
"set" does not replace relations in update

### ISSUE THREAD

**Issue by jalik** [prisma/prisma#5456]
## Bug description

Following the doc: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference/#set
I could not use the `set` query as intended, the request is passing with no error but the relations are not created in database.

## Expected behavior

The items passed to the `set` query should update the items in database.

## Prisma information

My models:
```
model Prospecting {
  id          Int                  @id @default(autoincrement())
  createdAt   DateTime             @default(now())
  modifiedAt  DateTime             @default(now())
  transaction String
  type        String
  minPrice    Int?
  maxPrice    Int?
  equipped    Boolean?
  furnished   Boolean?
  bedrooms    Int?
  archivedAt  DateTime?
  cities      ProspectingAndCity[] @relation("ProspectingTo_ProspectingAndCity")
}
```

```
model ProspectingAndCity {
  prospectingId Int
  cityId        Int
  City          City        @relation("CityTo_ProspectingAndCity", fields: [cityId], references: [id])
  Prospecting   Prospecting @relation("ProspectingTo_ProspectingAndCity", fields: [prospectingId], references: [id])

  @@id([prospectingId, cityId])
  @@map("_ProspectingAndCity")
}
```

```
model City {
  id                 Int                  @id @default(autoincrement())
  name               String
  linkedTo           String?
  ProspectingAndCity ProspectingAndCity[] @relation("CityTo_ProspectingAndCity")
}
```

The update query:
```js
await prisma.prospecting.update({
  where: { id: 2 },
  data: {
    'transaction': 'L',
    'type': 'M',
    'minPrice': null,
    'maxPrice': null,
    'equipped': null,
    'furnished': null,
    'bedrooms': null,
    'archivedAt': null,
    'cities': {
      'set': [
        {
          'prospectingId_cityId': {
            'prospectingId': 5,
            'cityId': 54,
          },
        },
        {
          'prospectingId_cityId': {
            'prospectingId': 5,
            'cityId': 10,
          },
        },
      ],
    },
  },
});
```

## Environment & setup

- OS: `KDE neon User Edition 5.20 x86_64`
- Database: `PostgreSQL 12.5 (Debian 12.5-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit`
- Node.js version: `v15.8.0`
- Prisma version:
```
2.16.0
```

**Comment by jalik** [comment]
As a complement I have currently workaround this issue by changing the query like this (hopefully it's working perfectly):
```js
await prisma.prospecting.update({
  where: { id: 2 },
  data: {
    'transaction': 'L',
    'type': 'M',
    'minPrice': null,
    'maxPrice': null,
    'equipped': null,
    'furnished': null,
    'bedrooms': null,
    'archivedAt': null,
    'cities': {
      // delete existing relations
      'deleteMany': {},
      // create new relations
      'create': [
        {
          'prospectingId_cityId': {
            'prospectingId': 5,
            'cityId': 54,
          },
        },
        {
          'prospectingId_cityId': {
            'prospectingId': 5,
            'cityId': 10,
          },
        },
      ],
    },
  },
});
```

**Comment by pantharshit00** [comment]
I think this is intended, `set` overrides the relation with existing entities and doesn't create them. You are trying to create entities in `ProspectingAndCity` while set only takes existing records and overrides the relation.  Are you trying to set records which already belongs to other records and you need to query them by the compound id? 


Can you please tell me what exactly you are trying to do here?

**Comment by jalik** [comment]
@pantharshit00 I may have misunderstood the docs then, but the `set` instruction looked to be what I was looking for.

In the given code I have a many-to-many relation, so I need to replace previous relations with the new existing one when I submit the form, since we're talking about a relation table, it's almost always create or delete to link or unlink records.

I thought that the `set` instruction would first delete any city relations of a prospecting, then create new ones.
So when I want to get all cities linked to a prospecting, I use a single query with include :

```js
const rows = prisma.prospecting.find({
  where: { id: 2 },
  include: {
    cities: { include: { City: true } }
  }
});

rows.forEach((row) => {
  // Get included cities
  const cities = row.cities.map((relation) => relation.City.name);
});
```

**Comment by richardwardza** [comment]
I think I have a similar issue where I'm trying to update a record and create new related records, discarding the existing related records at the same time - https://github.com/prisma/prisma/issues/6261

**Comment by jalik** [comment]
@richardwardza see my workaround above : https://github.com/prisma/prisma/issues/5456#issuecomment-772994699
Maybe we could ask for a new feature for that, like adding a `replace` instruction. Do you know if that would be possible/easy to implement ? @pantharshit00 
```js
await prisma.prospecting.update({
  where: { id: 2 },
  data: {
   ...attributes,
    'cities': {
      // this would remove any links between cities and this prospecting, and create new relations.
      'replace': [
        {
          'prospectingId_cityId': {
            'prospectingId': 5,
            'cityId': 54,
          },
        },
        {
          'prospectingId_cityId': {
            'prospectingId': 5,
            'cityId': 10,
          },
        },
      ],
    },
  },
});
```

**Comment by pantharshit00** [comment]
@jalik Sorry for the late reply here. 

Sure go ahead with the feature request. I am going to close this one here.
