### ISSUE TITLE
migration errors

### ISSUE THREAD

**Issue by ken1800** [prisma/prisma#5459]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v10.19.0           | 
| Prisma CLI  | 2.15.0             | 
| Binary      | e51dc3b5a9ee790a07104bec1c9477d51740fe54| 

## Error
```
Error: Error in migration engine.
Reason: [/root/build/migration-engine/core/src/commands/diagnose_migration_history.rs:101:26] Failed to read migration script: ReadMigrationScriptError(Os { code: 2, kind: NotFound, message: "No such file or directory" }, SpanTrace [{ target: "migration_connector::migrations_directory", name: "read_migration_script", fields: "self=MigrationDirectory { path: \"/home/proff/kenny/work/Todo/prisma/migrations/20210203181735_\" }", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 235 }, { target: "migration_connector::migrations_directory", name: "matches_checksum", fields: "self=MigrationDirectory { path: \"/home/proff/kenny/work/Todo/prisma/migrations/20210203181735_\" } checksum_str=\"5320c8e324b3aca93addab93769ee83caf383eff165e54ef533ff9d6ed2afc0\"", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 209 }, { target: "migration_core::api", name: "DevDiagnostic", file: "migration-engine/core/src/api.rs", line: 100 }])

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/prisma/issues/new

```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by tomhoule** [comment]
Hi @ken1800  — starting in 2.17.0, we will return a better error there. This happens when the migration.sql was deleted but not the parent folder. The solution is to delete the empty folder. Thanks for reporting this!
