### ISSUE TITLE
Order by aggregate (like count) in groupBy

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#5464]
## Problem

Right now groupBy doesn't support ordering by an aggregate. 

```prisma
model User {
  id     Int   @id @default(autoincrement())
  town   String
}
```

List of towns, ordered by number of users in each town. 

```sql
select town, count(town) 
from user
group by town
order by count(town) asc
```

## Suggested solution

```ts
client.user.groupBy({
  orderBy: {
    _count: {
      town: 'desc'
    }
  }
})
```

## Additional context

- First mentioned in: https://github.com/prisma/prisma/issues/4893#issuecomment-766146759
- There's a similar, but distinct feature request for ordering by relation: https://github.com/prisma/prisma/issues/5439

**Comment by zackify** [comment]
Will this feature support grouping by included (relationship) columns as well? Seems to fit my use case perfectly if so!

**Comment by matthewmueller** [comment]
Maybe! Can you share your use case?

**Comment by zackify** [comment]
It's the usecase described here: https://github.com/prisma/prisma/issues/4893#issuecomment-766146759

I have a "cases" table. Each case can have many "codes" attached to it. 

I want the "codes" that are used the most often. 

So i want to grab the total number of "cases" grouped by the "code" and ordered by the count. Using your example above, something like:

```
client.case.groupBy({
  by: ["CaseCode.code"],
  count: {
    CaseCode: {
      code: true
    }
  },
  orderBy: {
    count: true
  }
})
// result

[{code: 'test', count: 200}, {code: 'another code, count: 100}]
```

**Comment by matthewmueller** [comment]
Ahh got it! For some reason I thought those columns were in the same table. We talked about group by across tables, but it's pretty complicated. This is a separate feature that I can open an issue for. 

To help me with writing the issue, can share the Prisma Schema? 

Something like:

```prisma
model Case {
  id    Int    @id
  CaseCode CaseCode[]
}

model CaseCode {
  id     Int  @id
  code   Int
  case   Case @relation(fields: [caseId], references: [id])
  caseId Int
}
```

Also if you have the equivalent SQL that would be very helpful :-)

**Comment by zackify** [comment]
I have the full sql in the comment I linked to above, I can send the schema later today! Thanks

**Comment by zackify** [comment]
Just want to follow up, with the latest version of prisma, you can almost do this. But not quite:

```
const users = await prisma.user.findMany({
  include: {
    _count: {
      select: { posts: true },
    },
  },
})
```
You can do the above, but I need to be able to group by the highest count, and take only a few. Something like:

```
const users = await prisma.user.findMany({
  include: {
    _count: {
      select: { posts: true },
    },
  },
  orderBy: {
    _count: {
      posts: 'desc'
    }
  },
  take: 6
})
```

This would grab a count of posts on a user, ordered by the users with the most posts, and then take the highest 6

**Comment by Weakky** [comment]
Hey @zackify,

This seems like a different feature you're asking. Would you mind opening another issue for that?

I'm closing this issue for now as it's been implemented by https://github.com/prisma/prisma-engines/pull/1794.

Thanks

**Comment by simontaisne** [comment]
> This would grab a count of posts on a user, ordered by the users with the most posts, and then take the highest 6

Hmmm never mind, I guess another way to achieve it would be to do the following.

```ts
const users = await prisma.user.findMany({
  include: {
    _count: {
      select: { posts: true },
    },
  },
  orderBy: {
    posts: {
      _count: 'desc'
    }
  },
  take: 6
})
```

**Comment by edersonlucas** [comment]
> > This would grab a count of posts on a user, ordered by the users with the most posts, and then take the highest 6
> 
> Hmmm never mind, I guess another way to achieve it would be to do the following.
> 
> ```ts
> const users = await prisma.user.findMany({
>   include: {
>     _count: {
>       select: { posts: true },
>     },
>   },
>   orderBy: {
>     posts: {
>       _count: 'desc'
>     }
>   },
>   take: 6
> })
> ```

You saved me a lot now, thank you!!!!
