### ISSUE TITLE
create method performance issues.

### ISSUE THREAD

**Issue by yousufhasan** [prisma/prisma#5474]
When passing a very large object e.g. 1 million records with many sub entities to create method. It doesn't start running queries for few minutes and only after taking few minutes it starts running the queries. I can't see any thing on my terminal until after few minutes which impacts the performance badly. It doesn't take that longer if the object size is smaller. 

proivder:  postgresql
 binaryTargets   = ["native", "linux-musl"]

Version: PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

**Comment by Jolg42** [comment]
Related https://github.com/prisma/prisma/issues/5475

**Comment by pantharshit00** [comment]
Hey @yousufhasan 

Was this working in older version? 


Please try enabling unix domain socket transport once for data between prisma engine. Here is how you can do that:
```ts
const prisma = new PrismaClient({
  __internal:{
    useUds: true
  }
} as any); // remove as any if you are using js
```

**Comment by Jolg42** [comment]
I would be interesting to confirm which version of Prisma you are running, from https://github.com/prisma/prisma/issues/5475 it seems it's `2.16.0`?

**Comment by yousufhasan** [comment]
Still getting the error: 
`
"Error: Invalid prisma.aspData.create() invocation: connect ECONNREFUSED /tmp/prisma-c6e52d6e564849db55f91ce1.sock"
`

Yes the version is 2.16.0

**Comment by pantharshit00** [comment]
Ok, this seems unrelated to uds. Would it be possible for you share your schema here so that we can look into the data structure and try reproducing this?

**Comment by yousufhasan** [comment]
Here is the data, You can duplicate it like 20,000 organizations each having 20 metas and 20 subOrganisations each having 15 metas.

Apart from getting this error. the other issue is because createMany doesn't work with nesting and create generates single query for each record. the performance is very bad when we compare it with other ORMs like TypeORM. also since $transactions doesn't support dependent entities we can not do it inside transactions as well. That is why support of nested queries with createMany is essential.

```json
{
  "code": "3434",
  "name": "test1",
  "createdDate": "2021-02-10T01:06:45.074Z",
  "updatedDate": "2021-02-10T01:06:45.074Z",
  "organisations": {
    "create": [
      {
        "name": "test1",
        "createdDate": "2021-02-10T01:06:45.074Z",
        "updatedDate": "2021-02-10T01:06:45.074Z",
        "metas": {
          "createMany": {
            "data": [
              {
                "key": "dfdffd",
                "value": "dfdff",
                "createdDate": "2021-02-10T01:06:45.074Z",
                "updatedDate": "2021-02-10T01:06:45.074Z"
              },
              {
                "key": "dfdffd",
                "value": "dfdff",
                "createdDate": "2021-02-10T01:06:45.074Z",
                "updatedDate": "2021-02-10T01:06:45.074Z"
              }
            ]
          }
        },
        "subOrginsations": {
          "create": [
            {
              "name": "test1",
              "createdDate": "2021-02-10T01:06:45.074Z",
              "updatedDate": "2021-02-10T01:06:45.074Z",
              "metas": {
                "createMany": {
                  "data": [
                    {
                      "key": "dfdffd",
                      "value": "dfdff",
                      "createdDate": "2021-02-10T01:06:45.074Z",
                      "updatedDate": "2021-02-10T01:06:45.074Z"
                    },
                    {
                      "key": "dfdffd",
                      "value": "dfdff",
                      "createdDate": "2021-02-10T01:06:45.074Z",
                      "updatedDate": "2021-02-10T01:06:45.074Z"
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    ]
  }
}

```

**Comment by pantharshit00** [comment]
We have a createMany method now which addressed this. I am going to close this.
