### ISSUE TITLE
getting read ECONNRESET when creating records with v large object.

### ISSUE THREAD

**Issue by yousufhasan** [prisma/prisma#5475]
when trying to call .create method with v.large object e.g. 1million+ records with many nested entities, i m getting following error since  v.2.1.6
error: "Error: Invalid `prisma.accounts.create()` invocation: read ECONNRESET"

DB: PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

**Comment by pantharshit00** [comment]
Closing as duplicate of #5474 as it discusses the same problem.
