### ISSUE TITLE
[libs/datamodel/core/src/transform/helpers/value_validator.rs:202:26] Should only be empty or single String.

### ISSUE THREAD

**Issue by cbetz** [prisma/prisma#5476]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db push --preview-feature`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v15.3.0            | 
| Prisma CLI  | 2.16.0             | 
| Binary      | a973e24a4e5194f8fe3301bfa7ff982b24f97c05| 

## Error
```
Error: Error in migration engine.
Reason: [libs/datamodel/core/src/transform/helpers/value_validator.rs:202:26] Should only be empty or single String.

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

```

Happy to send the schema.prisma file privately or through a private gist if helpful. Also getting the same error on `prisma generate`

**Comment by janpio** [comment]
That would be quite amazing @cbetz - schemas@prisma.io and a link to this issue should be enough for us to connect the dots.
