### ISSUE TITLE
Can we manage Prisma1 and prisma2 migration in one MYSQL url. 

### ISSUE THREAD

**Issue by rahulybisen** [prisma/prisma#5489]
I am having one application with prisma1  there i am deploying schema to MYSQL.

**Comment by albertoperdomo** [comment]
Hello @rahulybisen,

can you please provide additional context on your request or report? Is this about being able to run Prisma 1 and Prisma 2 side by side on the same database?

**Comment by janpio** [comment]
Same question asked here: https://github.com/prisma/prisma/discussions/5492
