### ISSUE TITLE
Default function not working

### ISSUE THREAD

**Issue by baba43** [prisma/prisma#5518]
I've set the default value for a MySQL column to `left(uuid(),8)`.

After using `prisma introspect && prisma generate` I get the following schema:

```
model game {
  id         String    @id @default("left(uuid(),8)")
}
```
Now, when using `game.create` prisma writes _left(uuid(),8)_ into the id column. 

I've tried setting id to `null` or `undefined` explicitly, but neither worked.

Is there any workaround for this? 

Thanks.

**Comment by janpio** [comment]
Can you please share the SQL required to set up the table so we can reproduce what `introspect` creates from that? Thanks.

**Comment by janpio** [comment]
Some more information now that I got the full picture internally:

`@default` right now only supports static values or some special functions: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference/#default So `@default("left(uuid(),8)")` turning into exactly that string (!) `left(uuid(),8)` is fully expected.

There is a **preview** of a feature called _Native Types_ that includes the ability to define any SQL as the `DEFAULT` value - which would apply to the function `left(uuid(),8)` for example. But it is behind a feature flag `nativeTypes` that needs to explicitly be enabled **and** also requires the value to be inside a `dbgenerated()` function as well:

```prisma
generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["nativeTypes"]
}

[...]

model game {
  id         String    @id @default(dbgenerated("left(uuid(),8)"))
}
```

https://www.prisma.io/docs/concepts/components/preview-features/native-types/native-types-mappings#dbgenerated

---

Are you using that feature flag @baba43? And Introspection still created the schema with that `@default` as you posted it above? If so, this might be a bug that we need to investigate.

**Comment by tomhoule** [comment]
Hi @baba43 — the syntax you used is for defining _string_ defaults. If you want an expression as a default, you can use `@default(dbgenerated("left(uuid(),8)")`. I'd be curious to know if that works for you!

**Comment by baba43** [comment]
Thank you for your reply and sorry for that late reply.

Maybe the problem in my case is also that this field should be ID. This is my schema when trying to use `dbgenerated`:

```
model game {
  id         String    @id @default(dbgenerated("left(uuid(),8)"))
  created_at DateTime? @default(now())
}
```

And it results in: `PANIC in query-engine\connectors\sql-query-connector\src\database\operations\write.rs:72:22
Could not figure out an ID in create`

Also, when using `prisma introspect`, the schema is converted back to the original state:
```
model game {
  id         String    @id @default("left(uuid(),8)")
  created_at DateTime? @default(now())
}
```

**Comment by tomhoule** [comment]
Thanks for the extra info @baba43 — I'll look into fixing the introspection part at least.
