### ISSUE TITLE
$transaction not working

### ISSUE THREAD

**Issue by wmwart** [prisma/prisma#5527]
## Bug description

Transactions are not working as expected and as stated in the documentation. [https://www.prisma.io/docs/concepts/components/prisma-client/transactions#the-transaction-api](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#the-transaction-api)

> Prisma Client will ensure that either all three create-operations or none of them succeed.

## How to reproduce
use transactions as in the documentation

my code: 

```
  const [project, trash] = await context.prisma.$transaction([
        context.prisma.project.update({
            select: select.item.select,
            where,
            data: { deleted: true },
        }),
        context.prisma.trashItem.create({
            select: { id: true },
            data: {
                typeId: where.id,
                typeName: "Project",
                name: previous.name,
                description: previous.description,
                deletedBy: { connect: { authId: context.auth.id } },
                searchIndex: previous.searchIndex,
            },
        })
    ])
```

a mistake is made in the context.prisma.trashItem.create mutation. And she flies into the console.
However, when I open the database, it turns out that the first honor of the transaction is completed and the database is written `Project deleted: true `

## Expected behavior

The whole transaction is rolled back

## Environment & setup

- OS: Windows 10
- Database: PostgreSQL
- Node.js: v12.18.2
- Prisma version:
```
prisma               : 2.16.0
@prisma/client       : 2.16.0
Current platform     : windows
Query Engine         : query-engine 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules\@prisma\engines\query-engine-windows.exe)       
Migration Engine     : migration-engine-cli 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.346.0
Preview Features     : orderByRelation
```

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/client`.
You can try it out with `npm i @prisma/client`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
