### ISSUE TITLE
Mention `prisma migrate deploy` in `migrate dev` non interactive error message for better discoverability.

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#5531]
## Problem

`prisma migrate dev` is only for development and errors on non interactive environments 
https://github.com/prisma/prisma/issues/4669

This error will show if you try to run this command in unattended environments like CI/CD.

Current error message:

```
We detected that your environment is non-interactive. Running this command in not supported in this context.
```      

## Suggested solution

Mention `prisma migrate deploy` in error message for better discoverability.

## Additional context

https://github.com/prisma/prisma/issues/4751#issuecomment-773784835

**Comment by albertoperdomo** [comment]
Suggested message for migrate dev:

```
Prisma Migrate has detected that the environment is non-interactive, which is not supported.
`prisma migrate dev` is an interactive command designed to create new migrations and evolve the database in development.
To apply existing migrations in deployments, use `prisma migrate deploy`.
```

Suggested message for migrate reset:

```
Prisma Migrate has detected that the environment is non-interactive. It is recommended to run this command in an interactive environment. Use `--force` to run this command without user interaction.   
```
