### ISSUE TITLE
Prisma format and issues with implicit relations

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#5540]
When we validate the data model, we make certain implicit assumptions on how relations should work. We can demonstrate it with a simple data model:

```prisma
datasource chinook {
  provider = "sqlserver"
  url      = "jdbc:sqlserver://"
}

model Code {
  id          String  @id
  userId      String?
  user        User?
}

model User {
  id     String  @id
  name   String?
  codes  Code[]
}
```

Here we can format the code with `cat dm.prisma | cargo run --bin prisma-fmt -- format`, which outputs the correct relation attributes:

```prisma
datasource chinook {
  provider = "sqlserver"
  url      = "jdbc:sqlserver://"
}

model Code {
  id     String  @id
  userId String?
  user   User?   @relation(fields: [userId], references: [id])
}

model User {
  id    String  @id
  name  String?
  codes Code[]
}
```

Or we can remove the `userId` from our datamodel, and the formatter will add it back. We'll get into trouble though when we have two relations to the same model:

```prisma
datasource chinook {
  provider = "sqlserver"
  url      = "jdbc:sqlserver://"
}

model Code {
  id          String  @id
  user        User?
  createdBy   User?
  userId      String?
  createdById String?
}

model User {
  id    String  @id
  name  String?
  codes Code[]
}
```

Running this through `prisma-fmt` will give the exact same model back. The relation columns are not added, but the data model passes the validation just to result in broken migrations later on.

**Comment by matthewmueller** [comment]
Thanks for creating this issue! We talked about it on a call, but just want to be explicit:

- We don't want to remove formatter from adding `@relation` and foreign key, this is a beloved feature.
- We want the validator to ensure that `@relation` always exists and links to a valid field.
- If the formatter is unable to correctly add `@relation` (e.g. user & createdBy), it shouldn't try. The validator will just tell you that you're missing `@relation` and need to add them in by hand to resolve the issue.

**Comment by do4gr** [comment]
This should be solved by us splitting the parsing and formatting step here https://github.com/prisma/prisma-engines/pull/1662
