### ISSUE TITLE
@prisma/client version 2.16.x spams [dotnev][DEBUG] logs

### ISSUE THREAD

**Issue by danielmahon** [prisma/prisma#5562]
## Bug description

After upgrading to version 2.16.x `[dotenv][DEBUG]` logs started spamming the console with "did not match key" and "overwrite" warnings

```
[dotenv][DEBUG] did not match key and value when parsing line 32:
[dotenv][DEBUG] did not match key and value when parsing line 37:
[dotenv][DEBUG] did not match key and value when parsing line 40:
[dotenv][DEBUG] did not match key and value when parsing line 43:
[dotenv][DEBUG] did not match key and value when parsing line 47:
[dotenv][DEBUG] "NODE_ENV" is already defined in `process.env` and will not be overwritten
[dotenv][DEBUG] "BUILD_TARGET" is already defined in `process.env` and will not be overwritten
[dotenv][DEBUG] "PORT" is already defined in `process.env` and will not be overwritten
[dotenv][DEBUG] "LOG_LEVEL" is already defined in `process.env` and will not be overwritten
[dotenv][DEBUG] "LOG_DIFFERENCE" is already defined in `process.env` and will not be overwritten
[dotenv][DEBUG] "DEBUG" is already defined in `process.env` and will not be overwritten
...many more
```

## How to reproduce

Upgrade from 2.15.0 to 2.16.x
Have existing `DEBUG` env variable set to unrelated namespace
Logs spam during nexus schema generation and logs spam during server start

```
// .env

DEBUG="app*"
```

## Expected behavior

No logs

## Prisma information

```ts
"prisma": "2.16.1",
"@prisma/client": "2.16.1",
// or
"prisma": "2.16.0",
"@prisma/client": "2.16.0",
```

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```

```

**Comment by Jolg42** [comment]
I can confirm the current spamming, I'll check with my colleague what we want to do 👍 

> @Jolg42 This is causing log spam (see #5562) because any truthy value causes the dotenv debug to show. I know they use the env `DEBUG` as an example for setting the config option but it should really be `DOTENV_CONFIG_DEBUG=true` to enable internal logging... that will allow those of us using the `debug` package to use the `DEBUG` env without triggering `dotenv` logs.
> 
> See `dotenv` environmental config recommendations here: [https://github.com/motdotla/dotenv/blob/master/README.md#preload](https://github.com/motdotla/dotenv/blob/master/README.md?rgh-link-date=2021-02-11T17%3A57%3A24Z#preload)
> 
> Please consider changing:
> 
> https://github.com/prisma/prisma/blob/19783dc0d381e79d36a68f5f07a50c63abebfde7/src/packages/sdk/src/utils/tryLoadEnvs.ts#L136
> 
> to
> 
> ```ts
> debug: Boolean(process.env.DOTENV_CONFIG_DEBUG) || undefined,
> ```

**Comment by Jolg42** [comment]
Thanks @danielmahon, so I just changed the logic to enbable dotenv debug only if `process.env.DEBUG.startsWith('prisma')` or `process.env.DEBUG === '*'`

That should get rid of the spam ✔️
