### ISSUE TITLE
Prisma Migrate crashes when regenerating migration after deleting it

### ISSUE THREAD

**Issue by iquabius** [prisma/prisma#5564]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`migrate dev --name adios-appsync --preview-feature`

I ran this right after unstaging, and consequently deleting, the migration SQL and lock files. That's because I wanted to regenerate the migration after adding a `@default()` directive I forgot.

If I delete the migrations directory as well then the error doesn't occur. The command completes successfully after asking me if I want to reset the database. I deleted the whole thing but I think the problem is the empty directory `prisma/migrations/123hash321_adios_appsync`.

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.4.0            | 
| Prisma CLI  | 2.16.1             | 
| Binary      | 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03| 

## Error
```
Error: Error in migration engine.
Reason: [/root/build/migration-engine/core/src/commands/diagnose_migration_history.rs:101:26] Failed to read migration script: ReadMigrationScriptError(Os { code: 2, kind: NotFound, message: "No such file or directory" }, SpanTrace [{ target: "migration_connector::migrations_directory", name: "read_migration_script", fields: "self=MigrationDirectory { path: \"/home/iqb/Code/Sogni/zaula/apps/data-graph/src/prisma/migrations/20210209153345_adios_appsync\" }", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 233 }, { target: "migration_connector::migrations_directory", name: "matches_checksum", fields: "self=MigrationDirectory { path: \"/home/iqb/Code/Sogni/zaula/apps/data-graph/src/prisma/migrations/20210209153345_adios_appsync\" } checksum_str=\"fe375d41e47b86b5fbe3d26be5db83d8f39ee2b34b56da5c769da42c172b9ec\"", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 207 }, { target: "migration_core::api", name: "DevDiagnostic", file: "migration-engine/core/src/api.rs", line: 100 }])

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

```

**Comment by tomhoule** [comment]
Hi @iquabius — this is indeed an error we noticed, and the error message will be improved in 2.17.0.Please not however that it will still not work, you have to delete the entire folder, not just the `migration.sql`. Is there a particular reason why you would want to keep the folder? Thanks for reporting.

**Comment by iquabius** [comment]
> Is there a particular reason why you would want to keep the folder?

No reason! I deleted the files through git UI in VS Code, and it wasn't obvious the directory was left around.

It made me confused for a bit, but my next intuition was to check the file explorer.

I only reported it because Prisma CLI made it very easy :tada:

**Comment by tomhoule** [comment]
Awesome — thanks for the issue again. I think we can close then, there will be a much better error and no crash in tomorrow's release :)
