### ISSUE TITLE
All helper types are under the Prisma namespace

### ISSUE THREAD

**Issue by gmenih341** [prisma/prisma#5573]
## Bug description

I was following the docs on **[Advanced usage of generated types](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-generated-types)**, and found out that my generated types are not exported from `@prisma/client`, but are actually under a `Prisma` namespace, so they have to be used as `Prisma.PromiseReturnType`.. 

It seems that only the "entity" types are exported directly, and all auto generated ones, such as `UserCreateInput`, `UserCreateArgs`, etc.. all have to be prefixed with `Prisma.`.

Is this intentional? Should the documentation be updated then, or this a regression? I have a test project where I first tried Prisma with version `2.11.0`, where the types were exported directly, without the namespace.

## How to reproduce

1. Init a prisma project with the latest version (`2.16.1`)
2. Create a model and generate the client from it
3. See that all helper types are under `Prisma` namespace

## Expected behavior

I expect the helper types to be imported from `@prisma/client`

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v12.19.1
- Prisma version:

```
prisma               : 2.16.1
@prisma/client       : 2.16.1
Current platform     : darwin
Query Engine         : query-engine 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.346.0
```

**Comment by Jolg42** [comment]
Hi @gmenih341 

So it's an intended breaking change, we had a warning about that in previous versions.

This breaking change happened with `2.12.0` and is easy to fix with our provided codemod:

From https://github.com/prisma/prisma/releases/tag/2.12.0

Prisma codemods help upgrading your codebase

With today's release, we took the opportunity to cleanup some rough edges in the Prisma Client API which partially results in breaking changes. To help you with upgrading your codebase to 2.12.0, we're introducing @prisma/codemods.

The @prisma/codemods package provides a powerful CLI that scans your codebase and automatically updates the code to the new API calls from the provided version.

The upgrade workflow looks like this:
```
cd my-app
npm install @prisma/cli @prisma/client
npx @prisma/codemods update-2.12 ./
```

**Comment by gmenih341** [comment]
Thanks @Jolg42.. I was setting up a new project, so I'm already at the latest version. I was just curious why this change, as I am now aliasing all types, so I don't have to use the `Prisma` namespace everywhere :) 

But it's not an issue. Thanks for replying :)

**Comment by Jolg42** [comment]
Oh ok got, it reopening :)

**Comment by Jolg42** [comment]
The Prisma namespace was introduced because of https://github.com/prisma/prisma/issues/3233

So to avoid clashes in the namespace - model vs. internal class.
