### ISSUE TITLE
`npx prisma -v` on Windows returns: Error: Get config Error: Command failed with exit code 3221225781

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#5597]
> Hello!
> 
> When running "**prisma -v**" (version 2.16.1) on my cmd i get this error: 
> Environment variables loaded from .env
> Environment variables loaded from prisma\.env
> Prisma schema loaded from prisma\schema.prisma
> _Error: Get config Error: Command failed with exit code 3221225781: D:\Sites\xxx\server\node_modules\\@prisma\cli\query-engine-windows.exe cli get-config --ignoreEnvVarErrors 
> error Command failed with exit code 1._ 
> 
> **Update:** 
> I also tried reinstalling prisma as a global package, still having the same issue.
> When running "**prisma -v**" (version 2.16.1) on my cmd i get this error: 
> _Error: Command failed with exit code 3221225781: C:\Users\xxx-003\AppData\Local\Yarn\Data\global\node_modules\\@prisma\engines\introspection-engine-windows.exe --version_
> 
> 
> I think this is something wrong on my WINDOWS machine cause my friend tried in MacOS and worked well.
> 
> Does anyone knows how to solve this issue?
> 
> 
> **System Information:**
> OS Name:                   Microsoft Windows 10 Pro
> OS Version:                10.0.18363 N/A Build 18363
> OS Manufacturer:           Microsoft Corporation
> OS Configuration:          Standalone Workstation
> OS Build Type:             Multiprocessor Free
> Original Install Date:     1/17/2021, 4:05:55 PM
> System Boot Time:          11/10/2020, 7:28:01 AM
> System Manufacturer:       LENOVO
> System Model:              20A8S05K00
> System Type:               x64-based PC
> Processor(s):              1 Processor(s) Installed.
>                            [01]: Intel64 Family 6 Model 69 Stepping 1 GenuineIntel ~1895 Mhz
> BIOS Version:              LENOVO GRET45WW (1.22 ), 8/31/2015
> Windows Directory:         C:\WINDOWS
> System Directory:          C:\WINDOWS\system32
> Boot Device:               \Device\HarddiskVolume2
> System Locale:             en-us;English (United States)
> Input Locale:              en-us;English (United States)
> Time Zone:                 (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague
> Total Physical Memory:     8,072 MB
> Available Physical Memory: 1,764 MB
> Virtual Memory: Max Size:  15,080 MB
> Virtual Memory: Available: 4,796 MB
> Virtual Memory: In Use:    10,284 MB
> 
> 
> **Node Environment:**
> node version: v14.15.4
> npm version: 6.14.10
> yarn version: 1.22.5
> prisma version: 2.16.1

_Originally posted by @dibranhoxha in https://github.com/prisma/prisma/discussions/5595_

**Comment by janpio** [comment]
This exit code is usually when Ctrl+C is used:
https://github.com/clinicjs/node-clinic-doctor/commit/96a79c2c6ea8a15bfe9a7c39ca024eb8197a36ef
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55?redirectedfrom=MSDN
I assume you are not doing that really but this just happens when you execute `prisma -v`?

For context: I can run the command just fine on my Windows machine.

**Comment by Jolg42** [comment]
Note: It seems from the docs you found @janpio that the error code is 
```
0xC0000135   STATUS_DLL_NOT_FOUND | {Unable To Locate Component} This application has failed to start because %hs was not found. Reinstalling the application might fix this problem.
-- | --
```

**Comment by dibranhoxha** [comment]
@Jolg42 Can you tell me what application should be reinstalling please?  I have some trouble understanding this. 
Do you mean to reinstall 'Prisma' or what?

**Comment by Jolg42** [comment]
I found this in the docs, I do not know what this means exactly, it's the first time I see it.

Only thing I can suggest at the moment is to uninstall the globally installed `@prisma/cli` from yarn and retry, so:
```
yarn global remove @prisma/cli
npx prisma -v
``` 

Maybe that helps.

**Comment by dibranhoxha** [comment]
Thanks @Jolg42 and @janpio i solved this issue after  removing _@prisma/cli_ and reinstalling it and i have also installed windows build tools using _npm install --global windows-build-tools_ and restarting my machine. So i think you can close this issue.

**Comment by Jolg42** [comment]
Awesome!

**Comment by janpio** [comment]
> Note: It seems from the docs you found @janpio that the error code is
> 
> ```
> 0xC0000135   STATUS_DLL_NOT_FOUND | {Unable To Locate Component} This application has failed to start because %hs was not found. Reinstalling the application might fix this problem.
> -- | --
> ```

You are right, the code I linked to is actually about another error code. I missed that.

`windows-build-tools` should totally not be necessary to run the Windows binaries. Let's hope this does not happen more often.

**Comment by dhatGuy** [comment]
I'm facing this issue. 
```
Error: Get config: Error: Command failed with exit code 3221225781: C:\path\npm\node_modules\prisma\query-engine-windows.exe cli get-config --ignoreEnvVarErrors
```

**Comment by janpio** [comment]
Please open a new issue and provide as much information as possible. Thanks.
