### ISSUE TITLE
Cannot log in when DATABASE_URL contains '#' (e.g. in username or password)

### ISSUE THREAD

**Issue by midgleyc** [prisma/prisma#5612]
## Bug description

When the username or password (and presumably host and database) contains a `#` character, prisma incorrectly interprets the url and fails to log in.

## How to reproduce

1. In mysql, run `create user 'user' identified by 'password#' `
1. Run `npx prisma init`
2. In the `.env` file, change the `DATABASE_URL` to `"mysql://user:password#@localhost/test"`
3. Run `npx prisma introspect`
```
Error: Error parsing connection string: invalid port number in `mysql://user:password#@localhost/test`)
```

## Expected behavior

Should correctly log in with user "user" and password "password#".

## Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

## Environment & setup

- OS: Ubuntu
- Database: MariaDB
- Node.js version: v14.15.5
- Prisma version:

```
prisma               : 2.16.1
@prisma/client       : Not found
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.346.0
```

**Comment by midgleyc** [comment]
Ah, I see I have to escape these characters using URL encoding, so '#' becomes '%23'.

Would you mind adding a note to the documentation accordingly? I checked https://www.prisma.io/docs/reference/database-reference/connection-urls and https://www.prisma.io/docs/concepts/database-connectors/mysql but didn't see anything about this.

**Comment by matthewmueller** [comment]
Good point. We should document this. Closing in favor of: https://github.com/prisma/docs/issues/1057.
