### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine\cli\src/main.rs:68:41] called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" } 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#5614]
Command: `prisma migrate dev --preview-feature`
Version: `2.16.0`
Binary Version: `854c8ba7f0dce66f115af36af24e66989a8c02a1`
Report: https://prisma-errors.netlify.app/report/12944 
OS: `x64 win32 10.0.19041`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine\cli\src/main.rs:68:41] called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

    at ChildProcess.<anonymous> (C:\Users\kaTeilX\AppData\Roaming\npm\node_modules\prisma\build\index.js:54621:23)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

Rust Stacktrace:
```
[migration-engine\cli\src/main.rs:68:41] called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }
```

**Comment by safinsingh** [comment]
Rust `String`s must contain valid UTF-8, and judging by [this code](
https://github.com/prisma/prisma-engines/blob/master/migration-engine/cli/src/main.rs#L68), it seems like your schema contained invalid UTF-8. Verify the character encoding of the file.

**Comment by pantharshit00** [comment]
@safinsingh Yes, we are aware of that. Issue is automatically collected from the cli so @divyenduz is not the user here. 

We are more concerned about the panic. Engine should never happen as we try to handle all errors gracefully.

**Comment by safinsingh** [comment]
Perhaps instead of unwrapping, you could use something like anyhow to gracefully handle errors with additional context?

**Comment by pantharshit00** [comment]
Yeah, that is what we will do but we also need to propagate this upto the javascript client. We have some macros in the codebase for that.

**Comment by do4gr** [comment]
We would like to have a better error message here telling users that we only support UTF-8.

**Comment by pimeys** [comment]
Actually panic here is more than fine, it is a completely illogical state for us, and we have no other way but to exit. Having a backtrace is really nice too with this.

What I'm changing is a better error message, saying what we were trying to do and why it failed.

**Comment by jkomyno** [comment]
[Here](https://prisma-errors.netlify.app/report/14175) is another error reporting pointing to this.

**Comment by janpio** [comment]
Should we reopen as that report is with 4.1.0?

**Comment by jkomyno** [comment]
@janpio actually, I have just tried to reproduce this locally with `Prisma 4.1.0` on `darwin` and it works fine with the schema copied from [this](https://prisma-errors.netlify.app/report/14175) error report. Maybe this is a Windows-only error?

**Comment by janpio** [comment]
The error you link to literally shows the improved error message that @pimeys added in #2897. So I don't really think there is anything to do, besides maybe disagreeing that this should be a panic that is reported in our system and instead make this a known error. But that would be a new issue.
