### ISSUE TITLE
$transaction doesn't rollback in case any transaction fails

### ISSUE THREAD

**Issue by codeslayer1** [prisma/prisma#5616]
## Bug description
I am trying to use Prisma transactions as specified [here](https://www.prisma.io/docs/guides/prisma-guides/prisma-client-transactions-guide/#can-i-perform-multiple-nested-writes---for-example-create-two-new-teams-and-assign-users). My transaction is not rolling back in case of an error.

**Example**
```ts
const txn1 = this.prisma.table1.create({
      data: {
        name: `Test 1`
      },
    });
const txn2 = this.prisma.table1.create({
  data: {
    name: undefined //`Test 2`,
  },
});
const transactionResults = await this.prisma.$transaction([txn1, txn2]);
```
`name` is a mandatory column so when I send undefined, `txn2` fails but `txn1` still creates a record in the table even though it should rollback as `txn2` failed.

## How to reproduce

Sample code shared above. Try to execute it with a test table.

## Expected behavior
Transaction 1 insert should rollback as transaction 2 failed.

## Environment & setup

- OS: MacOS Catalina 10.15.1, Running inside docker `node:14.15.4-alpine`
- Database: PostgreSQL 
- Node.js version: v14.15.4 
- Prisma version:

```
prisma               : 2.16.0
@prisma/client       : 2.16.0
Current platform     : linux-musl
Query Engine         : query-engine 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/query-engine-linux-musl)
Migration Engine     : migration-engine-cli 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine : introspection-core 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary        : prisma-fmt 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-linux-musl)
Studio               : 0.346.0
Preview Features     : nativeTypes, createMany
```

**Comment by Jolg42** [comment]
Could be related to this report by another user on public Slack
https://prisma.slack.com/archives/CKQTGR6T0/p1612273504412300
It has a reproduction:
https://github.com/revivalme/nestjs-prisma-transaction-test

**Comment by codeslayer1** [comment]
Any timeline or workaround to this @Jolg42? We are in the middle of a production sprint and kind of stuck due to this transaction issue.

**Comment by Jolg42** [comment]
Unfortunately I do not know when the client team will fix it, they will look into the issue soon.
It will likely be fixed in the next official release, 2.18.0, that should happen on March 2nd.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/client`.
You can try it out with `npm i @prisma/client@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by codeslayer1** [comment]
Thanks for the quick fix @timsuchanek. Tested it on 2.17 and its working as expected.

**Comment by sreuter** [comment]
@timsuchanek I'm running into this myself with `2.19` now. 

**Code** 

```  const deleteItemInfosOp = prisma.itemInfo.deleteMany({
    where: {
      formId: questPrototypeId,
    },
  });

  const deleteItemsOp = prisma.itemPrototype.deleteMany({
    where: {
      formId: questPrototypeId,
    },
  });

  const insertItemsOp = prisma.formPrototype.update({
    where: {
      id: questPrototypeId,
    },
    data: {
      items: {
        create: itemsData,
      },
    },
  });

  const [
    deleteItemInfosOpRes,
    deleteItemsOpRes,
    insertItemsOpRes,
  ] = await prisma.$transaction([
    deleteItemInfosOp,
    deleteItemsOp,
    insertItemsOp,
  ]);```

It runs the first two operations, with the third one failing because of a bad invocation (`Invalid `prisma.formPrototype.update()` invocation:\n\n`. I know how to fix the 3rd operation in this case (it's because of a missing migration), but I wonder if users wouldn't expect Prisma to always try to rollback, even on "prisma internal" issues.

**Comment by pantharshit00** [comment]
@sreuter Please open a new issue with minimal reproduction

**Comment by janpio** [comment]
To repeat what @pantharshit00 wrote: Please open a new issue @sreuter - I absolutely agree with your stance here and we should definitely improve this. Super important actually.

**Comment by baddah-development** [comment]
i am facing the same issue in nest js when a transaction fail it dosent roll back the changes in the database

**Comment by quantik-git** [comment]
After a timeout error on a transaction, there is no changes rollback.
Using nextjs 16 on development build
clientVersion: '6.19.2'
