### ISSUE TITLE
Internal: Send Slack message for each CLI release

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#5618]
Right now we are not notified of CLI releases in any way, you have to watch the build pipeline. and go into the logs to find out the version name (for `dev` releases for example).

We want to send a Slack message to a `#feed-prisma-releases` Slack channel including the version name and release pipeline link. It should probably be implemented as the final step of the current "Publish" job.

**Comment by timsuchanek** [comment]
Implemented!
