### ISSUE TITLE
Prisma seed incompatible with Nextjs et al. projects

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#5622]
## Problem

TS projects that use an ESM value for compiler option "module" (such as any Nextjs project) will result in Prisma seed failing because the `ts-node` invocation will pass off ESM modules to Node:

<img width="1416" alt="Screen Shot 2021-02-11 at 5 27 50 PM" src="https://user-images.githubusercontent.com/284476/107770645-bbecf780-6d07-11eb-9313-76a0c2828f52.png">

## Suggested solution

The user should be able to customize how Prisma invokes `ts-node`.

For example in Nextjs projects I have have this npm script to make for a functioning `ts-node` in the project:

```
"ts-node": "ts-node --compiler-options '{\"module\":\"CommonJS\"}'",
```

I suggest `prisma` look for a `ts-node` script in the package and if found use that instead of calling `ts-node` directly.

## Alternatives

1. There could be a `prisma` config block in the package json like this:

```json
  "prisma": {  "ts-node": "teach prisma how to invoke ts-node" }
```

I don't think we could support `prisma.config.ts` because chicken-egg problem here about how to invoke `ts-node`. And it it would be weird if users were forced to use a JS file to configure Prisma.

2. Prisma could be smart enough to recognize that `ts-node` will never succeed with certain kinds of tsconfig settings, such as ESM module. Internally just always force CJS modules via `--compiler-option` flag.

## Additional context

I think the solutions should not try to be 100%, include opt-out flags etc. The easiest way to opt-out is for user to `--skip-seed` and then run seed manually.

**Comment by Jolg42** [comment]
Related https://github.com/prisma/prisma/issues/5161
