### ISSUE TITLE
Prisma ClientInitialization Error on production

### ISSUE THREAD

**Issue by indahud** [prisma/prisma#5636]
## Bug description
I am using NextJS and vercel for deployment. My code is working locally but not after deploying to the production. 
I have added my `DATABASE_URL` Environment Variable in vercel. But deployment build logs is showing me this error. 

```Unhandled error during request: PrismaClientInitializationError2 [PrismaClientInitializationError]: error: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `postgresql://`.```

## How to reproduce
1. Create NextJS app on Vercel
2. Install prisma and dependencies
3. Populate DB with some data
4. Add your Environment Variables in vercel
4. Deploy it on vercel

## Expected behavior
Deployment should be sucessful.

## Environment & setup

- OS: Manjaro 
- Database: PostgreSQL
- Node.js version: 15.8.0
- Prisma version: 2.16.1

**Comment by Jolg42** [comment]
Maybe that helps:
- So make sure your database url is starting with `postgresql://` for the env var
- Check the `.env` file if you have one (is it also deployed?)
- Generate the client again

**Comment by indahud** [comment]
Storing the envoirnment veriable inside vercel.json worked for me.

**Comment by nterol** [comment]
I have had the same issue today. I leave it here in case someone stumbled on the same issue: 
vercel does not read composed env variables.
If you have something like
```env
DATABASE_PASSWORD= yourpassword
DATABASE_URL=postgres://postgres:${DATABASE_PASSWORD}/...
