### ISSUE TITLE
migration error: Error accessing result set, column not found: datetime_precision

### ISSUE THREAD

**Issue by dimoff66** [prisma/prisma#5637]
## Bug description

trying to migrate or just push schema into new database, but get an error in terminal

_Database error: Error accessing result set, column not found: datetime_precision
   0: migration_core::api::SchemaPush
             at migration-engine\core\src\api.rs:166_

## How to reproduce

1) created simple schema in nodejs project

```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Category {
  id          Int       @id @default(autoincrement())
  name        String    @unique
  parentId    Int?
}

model Product {
  id          Int       @id @default(autoincrement())
  name        String    @unique
  categoryId  Int
  category    Category
}
```

2) Set database url variable in .env file
DATABASE_URL="mysql://root:@localhost:3306/PrismaDB"

3) in mysql manager created db with the name "PrismaDB"

4) In terminal run command
**npx prisma migrate dev**
or
**npx prisma db push**

## Expected behavior

Expected tables to be created from schema

## Prisma information

_Database error: Error accessing result set, column not found: datetime_precision
   0: migration_core::api::SchemaPush
             at migration-engine\core\src\api.rs:166_

## Environment & setup

- Windows
- MySQL 5.5-x64
- v 10.15.3
- Prisma version: 2.16.1

**Comment by tomhoule** [comment]
Hi @dimoff66, thanks for the report! Prisma does not suppport MySQL 5.5, we only test on MySQL 5.6 and up. Do you have the option to upgrade?

**Comment by dimoff66** [comment]
> Hi @dimoff66, thanks for the report! Prisma does not support MySQL 5.5, we only test on MySQL 5.6 and up. Do you have the option to upgrade?

Yes, upgrading solves the problem, sorry for disturb

**Comment by tomhoule** [comment]
No worries — glad you managed to make it work :)

**Comment by malltdev** [comment]
I don't understand how you guys don't support mysql 5.5, it's a big hassle connecting to an external database. I don't want to install mysql on my machine, but a simple task of connecting an external db is a problem, I've never had problems with sequelize, typeorm among others, just prism with this problem, I think it's time to leave the throne of the kingdom and work hard to find efficient solutions for your constant db connection errors

**Comment by fabio460** [comment]
no meu caso estou tentando migrar para um banco remoto e me dar esse erro
Error in connector: Error querying the database: Error querying the database: Error accessing result set, column not found: datetime_precision
