### ISSUE TITLE
`import { PrismaClient }` not provided & `Environment Variable not found: DATABASE_URL`

### ISSUE THREAD

**Issue by Tricky-Ricky** [prisma/prisma#5639]
## Bug description
Import and try to use Prisma Client with the following:

```
import { PrismaClient } from '@prisma/client'; 
const db = new PrismaClient();
```

Returns an error saying that '@prisma/client` does not provide an export named PrismaClient.
This is how it tells you too import it, after running npx prisma generate (With the exception of the const name change).

To rectify this, I did:
```
import Prisma from '@prisma.client'; 
const { PrismaClient } = Prisma; 
const db = new PrismaClient;`
```

However following from that I would get:

`Error: Environment variable not found: DATABASE_URL`

It would then show the provider and url from schema.prisma:
```
(node:18348) Error: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   |
 6 |   provider = "mysql"
 7 |   url      = env("DATABASE_URL")
   |
```

## Expected behavior
It should output the table when querying, as it has already populated the schema.prisma with the database models.
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Account {
  id       Int    @unique @default(autoincrement())
  userName String @unique
  isBanned Int?   @default(0)

  @@id([id, userName])
}
```

## Prisma information

```
async function main() {
        const accounts = await db.account.findMany();
        console.log(accounts);
    }

    main()
        .catch((e) => {
            if (e) throw e;
        })
        .finally(async () => {
            await db.$disconnect();
        });
```

## Environment & setup

- OS: Windows OS -> Linux Server
- Database: MySql
- Node.js version:  v14.15.4
- Prisma version: 

```
prisma               : 2.16.1
@prisma/client       : 2.16.1
Current platform     : windows
Query Engine         : query-engine 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.346.0
```

**Comment by Tricky-Ricky** [comment]
Not sure if this is relevant.

looking at the index.js under node_modules/.prisma/client it outputs this:
```
const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  warnEnvConflicts,
  getPrismaClient,
  debugLib,
  sqltag,
  empty,
  join,
  raw,
  Decimal
} = require('@prisma/client/runtime')

const path = require('path')
const debug = debugLib('prisma-client')


const Prisma = {}

exports.Prisma = Prisma
```
It never exports `PrismaClient` - Which is contradictory to what the terminal outputs:

```
✔ Generated Prisma Client (2.16.1) to .\node_modules\@prisma\client in 107ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

```

**Comment by pantharshit00** [comment]
@Tricky-Ricky 

The client export is part of re export of `.prisma/client` folder. This is done in that way in order to save the client from deletion from the pruning done by package managers like npm or yarn. 


The warning suggests that you haven't set `DATABASE_URL` in your environment variables or in the `.env` file. It is described here in your schema `  url      = env("DATABASE_URL")`. So please make sure you are providing prisma the database variable.

**Comment by Tricky-Ricky** [comment]
@pantharshit00 As stated in the post, It has already successfully connected and populated the schema.prisma file using the 
`DATABASE URL`  in the environment variables, when using `prisma introspect`, so it is a bug that seems to happen. Tried on 3 different fresh installations, and errored twice on `prisma generate`.

The `.prisma/client` folder within the package manager `prisma-client`  also does not have the export `PrismaClient` either.
After running `prisma generate` the console tells you to use `import { PrismaClient } from '@prisma/client';` But this is not the case, tried and tested on three different installs with `PrismaClient` being not found on all three.

**Comment by Tricky-Ricky** [comment]
Here is a vary broken down repo using Prisma 2.18 - Which is a default install, with no modified files.

It imports PrismaClient, how prisma tells you too in the console from a default install, and fails.

It will return:
```
import { PrismaClient } from "@prisma/client";
         ^^^^^^^^^^^^
SyntaxError: Named export 'PrismaClient' not found. The requested module '@prisma/client' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@prisma/client';
const { PrismaClient } = pkg;
```

https://github.com/Tricky-Ricky/Prisma-test

**Comment by pantharshit00** [comment]
Ah, thanks for sharing an example. We don't officially support ESM right now and we have this pending PR: https://github.com/prisma/prisma/pull/4920

We will review your PR next week now. Initially I thought you were using TS.

**Comment by pantharshit00** [comment]
More details here: https://github.com/prisma/prisma/pull/4920#issuecomment-756805461

**Comment by janpio** [comment]
Possible this already got fixed? The reproduction indeed fails, but when upgrading to 4.14.0 it does not any more and can successfully connect to the database.

**Comment by janpio** [comment]
Ping @Tricky-Ricky

**Comment by Jolg42** [comment]
Closing as we didn't hear back, we're happy to reopen it if this issue still exists in a recent version of Prisma.
