### ISSUE TITLE
DB_URL in Prisma Client's Environment Setup Guide should be changed to MySQL.

### ISSUE THREAD

**Issue by show-coco** [prisma/prisma#5642]
## Problem
I would like to participate in the development of Prisma.

When I was building the Prisma client environment, I found a difference between the database specified in [src/packages/client/fixtures/blog/prisma/schema.prisma](https://github.com/prisma/prisma/blob/bca072630eafdf0987ae7bae1dcaa760f02cae8b/src/packages/client/fixtures/blog/prisma/schema.prisma#L2) and the database specified in the [environment building guide](https://github.com/prisma/prisma/blob/master/CONTRIBUTING.md#developing-prisma-client-js).

In schema.prisma, mysql is specified, but in the guide, it is specified as `YOUR_POSTGRES_DB_URL`.

## Suggested solution
I want to change the guide as follows
```
- 4. export DB_URL=YOUR_POSTGRES_DB_URL
+ 4. export DB_URL=YOUR_MYSQL_DB_URL
```

## Alternatives
The environment builder can look up the specified DB by looking at schema.prisma by himself.

## Additional context
This is my first OSS activity. And I am not a high level developer. Therefore, I may be wrong, so please consider it carefully.

**Comment by Jolg42** [comment]
Thanks @show-coco!

So this is part of the fixtures folder, it's like a sandbox where we change things / develop locally.

So it was probably postgres but someone changed it to mysql I guess to try something there.
Feel free to change it to run things.

I edited the guide to make it more generic
https://github.com/prisma/prisma/commit/dc716810edad0456010ae901b94d7bd5b7a9fbbd
