### ISSUE TITLE
Error serializing `.posts` returned from `getStaticProps` in "/backend/dashboard/posts". Reason: `object` ("[object Promise]") cannot be serialized as JSON. Please only return JSON serializable data types.

### ISSUE THREAD

**Issue by Elshir** [prisma/prisma#5644]
## Bug description
Here's a wired situation:
In [Prisma site](https://www.prisma.io/nextjs),  there is an example using Next.js and Prisma playing with database:
```
// Fetch all posts (in /pages/index.tsx)
export async function getStaticProps() {
  const prisma = new PrismaClient()
  const posts = await prisma.post.findMany()
  return {
    props : { posts }
  }
// Display list of posts (in /pages/index.tsx)
export default ({posts}) =>
  <ul> 
   {posts.map(post => (
     <li key={post.id}>{post.title}</li>
    ))}
  </ul>
);
```
But when I put these codes to my project, it will return an error:
`Error: Error serializing `.posts` returned from `getStaticProps` in "/backend/dashboard/posts".
Reason: `object` ("[object Promise]") cannot be serialized as JSON. Please only return JSON serializable data types.`

Why is this happening? 

## Prisma information
I'm using latest Prisma and next.js

**Comment by Elshir** [comment]
fixed with superjson.

**Comment by Gabsys** [comment]
> fixed with superjson.

Hi, you are able to fix it just by installing superjson & adding it to .babelrc?

**Comment by Elshir** [comment]
> > fixed with superjson.
> 
> Hi, you are able to fix it just by installing superjson & adding it to .babelrc?

Yes, just that simple.

**Comment by Fiewor** [comment]
> > fixed with superjson.
> 
> Hi, you are able to fix it just by installing superjson & adding it to .babelrc?

Noob here. Please can you explain what exactly you did and how you added it to .babelrc? 

I'm building a Next.js app for the first time and I don't see a .babelrc file

**Comment by shobiianis** [comment]
> // Fetch all posts (in /pages/index.tsx)
> export async function getStaticProps() {
>   const prisma = new PrismaClient()
>   const posts = await prisma.post.findMany()
>   const posts=await post.json() // use this line here and it willn work
>   return {
>     props : { posts }
>   }
> // Display list of posts (in /pages/index.tsx)
> export default ({posts}) =>
>   <ul> 
>    {posts.map(post => (
>      <li key={post.id}>{post.title}</li>
>     ))}
>   </ul>
> );
