### ISSUE TITLE
Error P1001 Can't reach database server at AWS RDS (MySQL)

### ISSUE THREAD

**Issue by sunnysid3up** [prisma/prisma#5652]
## Bug description

I am trying to migrate my models to an AWS RDS (MySQL) database, but I am encountering this error:
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "dbname" at "hostname.rds.amazonaws.com:3306"

MySQL database dbname created at hostname.rds.amazonaws.com:3306

Error: P1001

Can't reach database server at `hostname.rds.amazonaws.com`:`3306`
```

## How to reproduce

1. Run `npm install prisma --save-dev`
2. Run `prisma init` and write a model
3. Run `prisma migrate dev --name m1 --preview-feature`

## Expected behavior

I expect it to create a database table with Prisma Migrate. It does create the database, but not the table.

## Prisma information

```
// .env

DATABASE_URL=mysql://username:password@hostname.rds.amazonaws.com:3306/dbname

// .schema.prisma

datasource db {
  provider = "mysql"
  url = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model ModelName {
  id                 Int               @default(autoincrement()) @id
  createdAt          DateTime          @default(now())
}
```

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v14.5.0
- Prisma version:
```
prisma               : 2.16.1
@prisma/client       : 2.16.1
Current platform     : darwin
Query Engine         : query-engine 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.346.0
```

**Comment by pantharshit00** [comment]
Can you please make sure your AWS instance has open ports and firewall is not blocking inbound connection. 

Try connecting to the database using cli or a gui first.

**Comment by sunnysid3up** [comment]
Hi, I've double checked and the AWS instance does have open ports and firewall is not blocking inbound connection.

Also, Prisma was able to create the database "dbname" in the instance. The error occurs when it tries to create a table in the newly created database.

**Comment by janpio** [comment]
Can you confirm again that running `prisma migrate dev --name m1 --preview-feature` really creates the database, but not the tables? That does not really make sense to me as that should happen using the same database connection - and the error message you reported points to it not being able to create such a connection to the database.

**Comment by sunnysid3up** [comment]
Hi, I just ran the command again and can confirm Primsa did create the database, but not the tables.

**Comment by pantharshit00** [comment]
Hey @sunnysid3up 

Can you please try with the 2.17 release once? I wasn't able to reproduce with my test run.

**Comment by sunnysid3up** [comment]
Hi, I am unable to check this right now, but I'll try it next week!

**Comment by sunnysid3up** [comment]
Hi @pantharshit00

I tried with the 2.17 release, and the same error occurs.

**Comment by pantharshit00** [comment]
@sunnysid3up Are you using a proxy in front of database like the RDS proxy? This is really strange and I am unable to reproduce even after multiple attempts. Can you also tell me your RDS instance details like its size and exact db driver version.

**Comment by ceefour** [comment]
Not only with prisma migrate, but prisma studio also doesn't work:

```
Message: Error in Prisma Client request: 

Error: Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter (https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#connection-pool). Current limit: 9.
    at cb (/home/ceefour/.cache/prisma/studio/cd7c74d3/runtime/index.js:79166:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/ceefour/project/tamrah/tamrah-work/node_modules/prisma/build/index.js:99343:25
    at async /home/ceefour/project/tamrah/tamrah-work/node_modules/prisma/build/index.js:99326:22
    at async PCW.request (/home/ceefour/project/tamrah/tamrah-work/node_modules/prisma/build/index.js:99374:40)
    at async PrismaService.respond (/home/ceefour/project/tamrah/tamrah-work/node_modules/prisma/build/index.js:99580:38)
    at async /home/ceefour/project/tamrah/tamrah-work/node_modules/prisma/build/index.js:101749:35

Query:
prisma.nonprofit.findMany({
  take: 100,
  skip: 0,
  select: {
    id: true,
    createdAt: true,
    email: true,
    name: true,
  }
})
```

**Comment by ceefour** [comment]
Tried in Windows with same result, so this isn't OS specific issue:

```
..\..\node_modules\.bin\prisma version       
Environment variables loaded from .env
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : windows
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at ..\..\node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at ..\..\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at ..\..\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at ..\..\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.356.0
```

**Comment by ceefour** [comment]
I found the problem, this was due to the AWS RDS server latency is high (in different region than my location).

Solution: Add `?connect_timeout=15` (or higher seconds) to `DATABASE_URL`

**Comment by pantharshit00** [comment]
Ah, so you were hitting the timeout. I can confirm we have tinkered with that in the recent release to solve other issues. @sunnysid3up Can you also try this? 

That also make sense why I can't reproduce as I was using the nearest AWS datacenter to me.

**Comment by ceefour** [comment]
@pantharshit00 I'd request that since there are several timeouts, to make error messages like:

- Connect timeout exceeded (5 seconds)
- Pool timeout exceeded (5 seconds)
- Socket timeout exceeded (5 seconds)

to make the clue and next action clearer, and make error messages more unique for googling. Instead of just "Can't reach..." which has multiple causes.

**Comment by janpio** [comment]
> _If_ I had read "Connect timeout exceeded (5 seconds)" at first try, I would already have thought that hey maybe it needs longer timeout since I'm connecting from Indonesia to Bahrain.

That unfortunately was not the case, as the pool timeout triggered a few miliseconds earlier. The connection timeout did not even happen any more - which is a nasty problem. We are increasing the default pool timeout to 10s to work around that and will monitor what errors people will receive afterwards to potentially fix that further.

**Comment by sunnysid3up** [comment]
@pantharshit00 I'm not using a proxy. The RDS instance class is db.t3.medium and db driver version is 5.7.31.

I tried ceefour's solution, but it didn't fix my issue :/

**Comment by janpio** [comment]
Any update on this @sunnysid3up? Many people are using RDS and similar databases in their Prisma projects, and it is working perfectly fine for them.

**Comment by sunnysid3up** [comment]
Hello. There isn't an update. You can close this issue though since no one else seems to have this problem. I'll update the thread if anything changes. Thank you :)

**Comment by armandoborge** [comment]
Facing the same exact issue, my port is open on AWS! I'll continue researching and I'll get back if I can solve it! None of the solutions above worked for me.

**Comment by armandoborge** [comment]
Solved by disabling using sslmode=disable parameter according the docs: https://www.prisma.io/docs/concepts/database-connectors/postgresql and also making sure my AWS config allows inbound connections over the PostgreSQL DB port
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Troubleshooting.html#CHAP_Troubleshooting.Connecting

I still not totally happy though, I'll keep researching to use sslmode enabled

**Comment by janpio** [comment]
Optimally open a new issue @armandoborge, if you can not figure it out soon. We should improve our documentation if something is not optimal there and does not work out of the box.

**Comment by armandoborge** [comment]
@janpio everything is working well with the SSL, thanks for your reply!

**Comment by Victor-Timi** [comment]
Here is the solution that worked for me

After copying the DATABASE_URL from Prisma, you will need to adjust the connection URL slightly to point to your own database.

Basically here is the format 

```mysql://USER:PASSWORD@HOST:PORT/DATABASE```

```DATABASE_URL="mysql://myusername:mypassword@server.us-east-2.psdb.cloud/mydb?*ssl={"rejectUnauthorized":true}*"```

I had to change what was initially written on my Db_Url by adding this **sslaccept=strict** and removing what was written before.

So Your Database_Url should look like this: ```DATABASE_URL="mysql://myusername:mypassword@server.us-east-2.psdb.cloud/mydb?sslaccept=strict"```

**Comment by sidharthhhh** [comment]
PS C:\Users\Sidharth shukla\Desktop\nextecommerce-admin> npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "ecommerce" at "aws.connect.psdb.cloud"

Error: P1001: Can't reach database server at `aws.connect.psdb.cloud`:`3306`

Please make sure your database server is running at `aws.connect.psdb.cloud`:`3306`.


how can i resolve this issue? continously comming in my code base?????????

**Comment by sidharthhhh** [comment]
i verify the connection, url , almost everything but still error is comming?...anyone help me out to resolve this problem....

**Comment by janpio** [comment]
Does it help when you add `?connect_timeout=30` add the end of your connection string? (or `&connect_timeout=30` if you already have a `?` query parameter)?

**Comment by tsdineshjai** [comment]
@janpio  thank you for all the provided solutions, it helped to clear my doubts.

**Comment by JxJPu9bD** [comment]
try  appent ```&pool_timeout=0```
