### ISSUE TITLE
Improve on autogenerated bug report urls

### ISSUE THREAD

**Issue by supermooshman** [prisma/prisma#5656]
## Problem

Autogenerated bug report Github url can get too long for Github because of the included log making it unusable. 
![Screenshot 2021-02-15 at 11 01 39](https://user-images.githubusercontent.com/12500559/107931913-383c4080-6f7d-11eb-98ce-b4e5436aa119.png)
## Suggested solution

Instead of providing a url which includes the markdown file as a parameter, print out just the markdown to be copied into the bugreport.  Or alternatively provide a better error message.

## Alternatives

    Invalid `prisma.role.findUnique()` invocation:
    
    
      PANIC in query-engine/core/src/response_ir/internal.rs:348:26
    Application logic invariant error: received null value for field role which may not be null
    
    This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

    If you want the Prisma team to look into it, please paste the snippet below at htttps://github.com/prisma/prisma/issues/new.
    To increase the chance of success, please post your schema and a snippet of
    how you used Prisma Client in the issue. 

    
    Hi Prisma Team! My Prisma Client just crashed. This is the report:
    ## Versions
    
    | Name            | Version            |
    |-----------------|--------------------|
    | Node            | v14.3.0            | 
    | OS              | darwin             |
    | Prisma Client   | 2.14.0             |
    | Query Engine    | query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1|
    | Database        | undefined|
    
    
    
    ## Query
    ```
    {"X":false}
    ```
    
    ## Logs
    ```
    Some really long log
    ...
    ...
    ```

**Comment by williamluke4** [comment]
Hey @supermooshman, It appears that you are on an old version of `prisma`. Could you try to upgrade, as I believe this has been addressed in later versions.

**Comment by williamluke4** [comment]
Closing, this should be resolved in the latest versions.
