### ISSUE TITLE
Prisma Migrate - Drift detected error on each migrate run even when nothing changes in DB/Schema

### ISSUE THREAD

**Issue by codeslayer1** [prisma/prisma#5687]
## Bug description
Reopening #5282 with only the drift detected issue. 

I get drift detected error every time I run Prisma migrate dev command even without making a single change to my schema. I migrated my existing database to Prisma and introspected it. Also created an init migration using SQL dump so that my schema, migrations and database all are in sync. Everything works fine for me including migrations creation using prisma migrate but the drift detected comes up every time.

## How to reproduce
Not sure. Have already shared my schema file earlier with @pimeys 

## Expected behavior
Shouldn't get drift detected error since everything is in sync

## Environment & setup

- OS: MacOS Catalina 10.15.1, Running inside docker `node:14.15.4-alpine`
- Database: PostgreSQL 
- Node.js version: v14.15.4 
- Prisma version:

```
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : linux-musl
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/query-engine-linux-musl)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/prisma-fmt-linux-musl)
Studio               : 0.353.0
Preview Features     : createMany
```

**Comment by pimeys** [comment]
Is there anything else than index drift happening? We fixed the foreign keys, but your SQL schema had custom constraint names for uniques, and the schema had `field Int @unique`, which we already discussed with you earlier how you could fix them.

**Comment by codeslayer1** [comment]
No other issue than drift. All the constraint/unique indexes issues are fixed. But drift issue still remains.

**Comment by codeslayer1** [comment]
@Jolg42 Any update on this? It's becoming really difficult for our team to use migrate dev feature since the db gets reset every time. Any directions as to what could be done to fix this?

**Comment by tomhoule** [comment]
@codeslayer1 I spent some time trying to reproduce the drift from the information in the previous issue, and I can't see any drift. I'll see with @pimeys  about the full schema. One more bit of information would be helpful: if you accept the drift diagnostic, say yes to the reset, and create a new migration, what does the next migration contain?

**Comment by codeslayer1** [comment]
Hey @tomhoule . No migration is created post reset since nothing changes between resets. It's just that the drift comes up every time.

**Comment by tomhoule** [comment]
Hi @codeslayer1 — @pimeys provided me with the schema and the migrations and I spent some time reproducing your issue. The problem is that your first migration redefines the Prisma migrations table. If you delete this part of the migration, the drift goes away:

```
CREATE TABLE IF NOT EXISTS public._prisma_migrations (
    id character varying(36) NOT NULL,
    checksum character varying(64) NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) NOT NULL,
    logs text,
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    applied_steps_count integer DEFAULT 0 NOT NULL
);
```

**Comment by codeslayer1** [comment]
Hey @tomhoule. This worked. Thanks a lot. Couldn't have guessed this fix 😅
