### ISSUE TITLE
$transaction should fallback to union if it can't give unwrap a proper output

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#5688]
## Problem

Given a function like:
```typescript
type BuildSubscriptionsUpdatesInput = {
  calendarId: string
}
type BuildSubscriptionsUpdatesOutput =
  | Prisma.Prisma__CalendarSubscriptionClient<CalendarSubscription>
  | PrismaPromise<Prisma.BatchPayload>
export default (
  app: Application,
  input: BuildSubscriptionsUpdatesInput
): BuildSubscriptionsUpdatesOutput[] => {
...
}
```

and usage like:
```typescript
const operations = buildSubscriptionsUpdates(app, { calendarId })
const result = await app.prisma.$transaction(operations)
```

The current type of result is `never[]`.

## Suggested solution
I think it it should be a union: `CalendarSubscription | BatchPayload` so at least the developers can use the result.

## Alternatives
Currently need to cast the result before using it. It also used to work fine in the previous versions.

## Additional context
Prisma: 2.17

**Comment by williamluke4** [comment]
Thanks for reporting this @Sytten, Yeah that sounds like a solid solution for a fallback.

**Comment by Sytten** [comment]
Another annoyance found when migrating a client. I use https://github.com/marchaos/jest-mock-extended in my tests and I now have to cast my mock to never:
```typescript
    const prisma = mockDeep<PrismaClient>(),
    prisma.$transaction.mockImplementation(
      (values) => Promise.all(values) as never
    );
``` 
Before the output used to default to `any`.
