### ISSUE TITLE
Log streaming interface for n-api

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#5690]
In order to consume the logs of the n-api query engine bridge, we need to think about an interface there, as we can't just forward stdout directly to the node process anymore.
Related: https://github.com/napi-rs/napi-rs/issues/470

**Comment by pimeys** [comment]
Rust side is merged, @williamluke4 has tested it on the client and can close the ticket when he think it's done.

**Comment by matthewmueller** [comment]
Done
