### ISSUE TITLE
Connection pool issue when deploying to Google Cloud Run/Cloud SQL

### ISSUE THREAD

**Issue by shwethashyam1** [prisma/prisma#5691]
## Bug description

This error happens when I run my scheduler functions on my express app, every minute, and deploy it to GCP:

```
PrismaClientInitializationError2 [PrismaClientInitializationError]: Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter (https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#connection-pool). Current limit: 20.
 ```
 
## How to reproduce
1. Add a scheduler function to an express server: 
	  ```
	  cron.schedule('* * * * *', () => {
	    await updateDB.updateIsExpiredColumn(); (// updateDB reference a .js which calls a prisma instance from prisma client)
	  ```
2. Build and deploy through docker
3. On psql connection string, call out connection limit parameter explicitly to 20. In addition, I also have a 4-CPU set up on GCP where this is running.
PSQL connection string: postgres://username:password@publicIP/dbname?connection_limit=20&host=/cloudsql/my-project-id:us-central1:production

## Expected behavior

1. scheduler function should run every minute and should not have connection pool issues
## Prisma information

prisma schema --
```generator client {
  provider      = "prisma-client-js"
  output        = "../functions/models/prisma-client"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

updateDB.js --
```require('dotenv').config();
const prisma = require('./prismaClient');

const updateIsExpiredColumn = async() => {
  const currentTimeISO = new Date().toISOString();
  const twoHoursPriorTimestamp = Date.now() - (60000*60*2);
  const twoHoursPriorISOString = new Date(twoHoursPriorTimestamp);

  console.log('current time ====', currentTimeISO);
  console.log('two hours prior ====', twoHoursPriorISOString);

  await prisma.caravansmsinstance.updateMany({
    where: {
      createdat: {
        lte: twoHoursPriorISOString,
      },
      AND: {
        isTwilioNoExpired: {
          equals: false,
        },
      },
    },
    data: {
      isTwilioNoExpired: {
        set: true,
      },
    },
  });
 await prisma.$disconnect();
}
```

prismaClient.js --
```require('../../config/config');
const { PrismaClient } = require('./prisma-client');

const url = process.env.DATABASE_URL;
let prisma;

if (process.env.NODE_ENV === "production") {
  prisma = new PrismaClient({
    datasources: { db: { url } },
  })
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient({
      datasources: { db: { url } },
    })
  }
  prisma = global.prisma
}

module.exports = prisma;
```

## Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: runtime: nodejs12 (Dockerfile)
- Prisma version: 2.16.1

```

```

**Comment by janpio** [comment]
This error happening indicates that all connections are still busy when they are trying to be used again. How long does the query run?

You can probably work around this by setting `&pool_timeout=0` on your connection string. But this will mean, that the queries will wait indefinitely until a connection is available in the connection pool.

**Comment by shwethashyam1** [comment]
Thanks @janpio I just checked and the time taken to run the query is about 34000ms if no other queries are running. When other queries are running, takes up to 80000ms. What happens if there are 100 users on my app? Does that mean the requests they send to my endpoint will take some time to execute if a connection is not available? Should I increase the connection_limit parameter?.

**Comment by janpio** [comment]
If your database can accept more connections, and your server hosting your app can handle more outgoing connections, then it can make sense to give Prisma more connections - yes. Then it can definitely run more queries in parallel without waiting for the connections to free up. But it is very hard to make blanket statements in regard to connection scaling. 

> What happens if there are 100 users using my app concurrently?

That depends. If all of them visit an endpoint that sends one or multiple queries, then the query might wait a bit longer. With queries that only take a few miliseconds it is very easy for Prisma to broker the connection between the different queries. With long running queries, that is a much bigger challenge. Often it makes sense to protect normal user traffic from background tasks by running them separately - different server, different Prisma CLient instance with a different connection limit or similar.

**Comment by shwethashyam1** [comment]
Thanks @janpio. I am not seeing this error anymore. I also deployed my scheduled functions to google cloud scheduler, so that appears to be working too.

**Comment by janpio** [comment]
Nice. Keep us updated 👍
