### ISSUE TITLE
db seed command line option for custom seed file location

### ISSUE THREAD

**Issue by jameynakama** [prisma/prisma#5692]
## Problem

There isn't a way to use a custom seed file right now. It's a common use case to have different seeds for different environments or needs. For example, a seed for local development, tests, special cases, etc.

Currently, I have to rename files or create one giant seed file with special instructions.

## Suggested solution

The `db seed` command should have a parameter for the seed file location, like `prisma db seed --seed=./prisma/testSeed.js`.

## Alternatives

The command could also use a positional arg and default to the current one. E.g., `prisma db seed ./prisma/testSeed.js --preview-feature`.

**Comment by codeslayer1** [comment]
I have configured `seed.ts` to load multiple seed files from a folder (code shared below). Basically it reads all files inside `/seeds/scripts` directory and runs them one by one. Make sure that you name your files with an ID or timestamp like `1_file` , `2_file` so that the loading sequence is maintained. You can also add different folders based on your environment by adding a check in the main function. Hope this helps.

```
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
import * as fs from 'fs';

async function main() {
  const scriptsDir = __dirname + '/seeds/scripts/';
  fs.readdir(scriptsDir, async function (err, files) {
    if (err) {
      console.error(err);
      throw err;
    }
    for (const file of files) {
      const sqls = fs
        .readFileSync(scriptsDir + file)
        .toString()
        .split('\n')
        .filter((line) => line.indexOf('--') !== 0)
        .join('\n')
        .replace(/(\r\n|\n|\r)/gm, ' ') // remove newlines
        .replace(/\s+/g, ' ') // excess white space
        .split(';');
      for (const sql of sqls) {
        await prisma.$executeRaw(sql);
      }
    }
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```

**Comment by jameynakama** [comment]
I'm doing something like this right now, using CLI env vars to do the trick. Multiple functions that can be used from the `seed` command, and a separate export for tests to use during test setup.

Might use your `fs` stuff to split it up a bit. Thanks.

```javascript
async function main(prisma) { ... }

async function randomizedData(prisma) { ... }

async function localData(prisma) { ... }

if (require.main === module) {
  const prisma = new PrismaClient();
  const mainMap = {
    "main": main,
    "random": randomizedData,
    "local": localData
  };
  let mainFunc = mainMap[process.env.SEED];
  if (!mainFunc) {
    mainFunc = mainMap.main
  }
  console.log(`>>> Using seed func [${mainFunc.name}]`);
  mainFunc(prisma)
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}

async function seedTests(prisma) {
  // Tests disconnect their own prisma client
  await main(prisma).catch((e) => {
    console.error(e);
    process.exit(1);
  });
}

module.exports = seedTests;
```

**Comment by janpio** [comment]
With the rework of `db seed` this is not valid any more, you now define the seed command in your `package.json` file instead.

**Comment by Jarrodsz** [comment]
> With the rework of `db seed` this is not valid any more, you now define the seed command in your `package.json` file instead.

Have this same problem, can you somehow supply multiple seed files and call prisma db seed <option1/option2> somehow?

**Comment by yugesh84** [comment]
I will also plus one this. Can we reopen this issue to satisfy the use case where I would be able to seed different data to different environments? My use case requires light data for local environments, additional test data for higher test environments, and actual enums, etc., for production environments.

**Comment by Jolg42** [comment]
@yugesh84 could you open a new feature/improvement issue and add context about your use case?

I think, at the moment, you could use the current `package.json` configuration and handle the different cases in the script itself?
https://www.prisma.io/docs/guides/migrate/seed-database#how-to-seed-your-database-in-prisma

Though https://github.com/prisma/prisma/issues/9403 would make this easier, I think.
