### ISSUE TITLE
Incorrect Promise typing from Prisma__UserClient

### ISSUE THREAD

**Issue by gleant** [prisma/prisma#5699]
## Bug description

Using prisma.[model].[method] within $transaction is generating error with types.

I have the following code 

```typescript
prisma.$transaction([prisma.user.create({
      select: {
          id: true,
      },
      data: {
          firstname,
          lastname,
          email,
      },
  })])
```

Which gives me this error

```typescript
Type 'Prisma__UserClient<{ id: string; }>' is not assignable to type 'PrismaPromise<any>'.
  Type 'Prisma__UserClient<{ id: string; }>' is missing the following properties from type 'Promise<any>': all, any, asCallback, bind, and 38 more.
```

I think that the problem is that $transaction is expecting PrismaPromise which is a union with Promise but Prisma__UserClient is not implementing all methods of Promise.

## Expected behavior

There should not be an error.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v12.16.3
- Prisma version: 2.17.0

**Comment by williamluke4** [comment]
Hey @gleant, I just tried to reproduce this and could not. What typescript version are you using?

**Comment by gleant** [comment]
Hi,

I'm using typescript version 4.1.5.

**Comment by williamluke4** [comment]
Hmm, don't think it's that then. Could you provide a minimal reproduction and I'll take a look

**Comment by gleant** [comment]
I found the issue and it was an old version of the bluebird library types.

Thank you for your time in investing in this.

**Comment by gferr-menezes** [comment]
i have some problem

**Comment by gferr-menezes** [comment]
i have same problem
