### ISSUE TITLE
Getting lots of errors in node_modules/.prisma/client/index.d.ts after upgrading to 2.17

### ISSUE THREAD

**Issue by codeslayer1** [prisma/prisma#5702]
## Bug description
After upgrading to 2.17 I am suddenly seeing a lot of errors in `node_modules/.prisma/client/index.d.ts` and my nest js build step is failing. Here are a few screenshots.

I tried rebuilding prisma, also deleted node_modules, cleared npm cache and tried rebuilding the whole thing but still getting errors both in local as well as Docker build.
 
<img width="723" alt="Screenshot 2021-02-17 at 10 45 10 AM" src="https://user-images.githubusercontent.com/11829647/108173999-e20a0180-7124-11eb-80e3-2735510e9812.png">
<img width="725" alt="Screenshot 2021-02-17 at 1 29 38 PM" src="https://user-images.githubusercontent.com/11829647/108174008-e6ceb580-7124-11eb-98c6-40d9535f43c9.png">

## How to reproduce
Not sure. Can share my schema file and generated ts file on Slack.

## Environment & setup

- OS: MacOS Catalina 10.15.1, Running inside docker `node:14.15.4-alpine`
- Database: PostgreSQL 
- Node.js version: v14.15.4 
- Prisma version:

```
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : linux-musl
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/query-engine-linux-musl)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/prisma-fmt-linux-musl)
Studio               : 0.353.0
Preview Features     : createMany
```

**Comment by Jolg42** [comment]
[Originally posted in public Slack](https://prisma.slack.com/archives/CCWDULGUW/p1613539035068300)

**Comment by Jolg42** [comment]
From Slack
```
Looks like I have found the issue. Reverting to old version helped fixed the issue.
Here is the difference between generated types in 2.16 vs 2.17.
2.16
export type payroll_kw_wallet_transactionsTypeSourceInvoice_idStatusCompoundUniqueInput = {
    type: payroll_kw_wallet_transactions_types
    source: payroll_kw_wallet_transaction_source
    invoice_id: string
    status: payroll_transaction_status
}
2.17
export type payroll_kw_wallet_transactionsPayroll_kw_wallet_transactions.type_source_invoice_id_status_unCompoundUniqueInput = {
    type: payroll_kw_wallet_transactions_types
    source: payroll_kw_wallet_transaction_source
    invoice_id: string
    status: payroll_transaction_status
}
Look at the difference in the names. Typescript isn't allowing . in the type name and hence the issue. (edited) 
```

>Just one more update so that it helps you debug the issue. This doesn't look to be an issue with Prisma version. The problem was that I introspected my schema just to make it in sync with existing DB. So in my schema the unique constraints got changed from @@unique([type, source, invoice_id, status]) to @@unique([type, source, invoice_id, status], name: "payroll_kw_wallet_transactions.type_source_invoice_id_status_un")  which on being generated by Prisma is leading to this incorrect type naming issue in both the versions. This was the reason reverting only the version earlier didn't help.
Please let me know when a fix is available. For now I will remove the naming from my schema.

>Also this is only happening with compound unique constraints. Single unique constraints seem to be working fine even with . in the name

**Comment by matthewmueller** [comment]
Thanks for the details. Through lots of discussion, we realized this wasn't actually a regression between 2.15 and 2.16, but actually an outstanding bug. We have a couple possible solutions being tracked here: https://github.com/prisma/prisma/issues/3193
