### ISSUE TITLE
Postgres Migration Bug after making schema changes (P3006 Error)

### ISSUE THREAD

**Issue by jbroomer** [prisma/prisma#5711]
## Bug description
Migrations don't appear to be working as expected when using **postgresql** (tried on both 12.6 and 13). Specifically, running the first migration works fine. However, when I make new changes to the `schema.prisma` file, Prisma doesn't pick up on the changes and it instead tries reapplying the migration already there and I get a `P3006` error stating the relations are already created.

## How to reproduce
1. Set up some temp postgres DB using 12.6 or 13
1. Start with boilerplate prisma schema code
1. Run first migration `npx prisma migrate dev --name init --preview-feature`
1. Make some change to the `prisma.schema` file (add new model, change a column name, etc)
1. Run migration again: `npx prisma migrate dev --name change --preview-feature`

<details>
<summary>Console Error</summary>

```
Error: P3006

Migration `20210217161456_init` failed to apply cleanly to a temporary database. 
Error:
Database error: Error querying the database: db error: ERROR: relation "User" already exists
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:270
   1: sql_migration_connector::sql_database_migration_inferrer::calculate_drift
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:40
   2: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:79
```
</details>

## Expected behavior

I expected Prisma to generate a _new_ migration file with the new name based on the diff and apply the changes from the diff.

## Prisma information
This issue can be reproduced using the simple boilerplate prisma schema.

<details>
<summary>Schema for 1st Migration</summary>

```
datasource db {
  url           = env("DATABASE_URL")
  provider = "postgresql"
}
generator client {
  provider = "prisma-client-js"
}
model User {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?  
}
```
</details>

<details>
<summary>Altered Schema for 2nd Migration</summary>

```
datasource db {
  url      = env("DATABASE_URL")
  provider = "postgresql"
}
generator client {
  provider = "prisma-client-js"
}
model User {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
}
// CHANGED: Added new table to DB
model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(false)
  title     String   @db.VarChar(255)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}
```
</details>

## Environment & setup

- OS: MacOS 
- Database: PostgreSQL (12.6 and 13)
- Node.js version: v14.1.1
- Prisma version: 2.17

**Comment by chelog** [comment]
Same here on mysql (actually mariadb). In case-insensitive OS'es like Windows `create table User` makes `user` table and prisma treats that as drift, trying to create new table which already exists. Rolled back to 2.16.0 for now

**Comment by tomhoule** [comment]
@chelog we have code to diff case-insensitively on mysql on windows — if it doesn't work, it's a separate problem. Could you please open an issue?

**Comment by tomhoule** [comment]
@chelog I think I found what could have broken. An issue would still be helpful :)

**Comment by tomhoule** [comment]
@chelog last update — I have a PR [here,](https://github.com/prisma/prisma-engines/pull/1663) it does look like we broke the MySQL case sensitivity setting detection recently, and didn't notice because we don't run CI on windows MySQL installations.

**Comment by tomhoule** [comment]
@jbroomer I couldn't spend a lot of time on it, but I did try to reproduce the issue, and couldn't observe the bug you reported. Is there anything specific about your setup that could be relevant? Are you using postgres in docker or natively installed?

**Comment by jbroomer** [comment]
I think it may have been a DB permissions issue for me. I had some others try it out and they were able to perform the 2nd migration. It, also, worked when I specified a shadow DB (even though I shouldn't have had to since I was running locally with a superuser).

Thank you for looking into this though!

**Comment by MikeYermolayev** [comment]
Experiencing the same with Heroku free postgresql.

Error occurs even with separate shadow database

**Comment by AHBruns** [comment]
Seeing this as well. I'm using managed Postgresql DBs on Digital Ocean.

**Comment by tomhoule** [comment]
@MikeYermolayev do you have more details that could help us reproduce the issue? Would it be possible to share your schema? Please open a new issue, comments in closed issues tend to not be seen.

**Comment by MikeYermolayev** [comment]
@tomhoule the schema is really simple, was just playing around.

Right now the issue is gone for me. I swapped shadow database with the main and now it works. So I'll probably open a new issue if it ever occurs again

```
datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
  // needed only when using heroku
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Car {
  id           Int    @id @default(autoincrement())
  manufacturer String
  model        String
  bodyType     String
  engineType   String
  transmission String
  year         Int
  generation   String
  vin          String
  odometer     Json // {unit: string, value: int}
}

```
