### ISSUE TITLE
Add TypeScript version check

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#5728]
We need at least TypeScript 4.1 to run `@prisma/client`. This should be enforced to prevent bad surprises.

**Comment by realSaddy** [comment]
This warning did not appear for me when my global typescript was ^4.1, but my local typescript was not. Silly mistake on my side, but it is something that could be improved if possible.

**Comment by pantharshit00** [comment]
I can reproduce this. There was no warning thrown when I had `3.9.9` locally
