### ISSUE TITLE
when case-insensitive mode enabled in where clause, unnecessarily LOWER() function and ILIKE operator is used at the same time

### ISSUE THREAD

**Issue by gifuhabu** [prisma/prisma#5748]
## Bug description
I build a api that have full text search feature, and I use full text search engine named [PGroonga](https://pgroonga.github.io/tutorial/)  in PostgreSQL.
If you want to use PGroonga, installation proceess is  simply installing and adding index.

I found query is too slow when using ILIKE (case-insensitive), but normal LIKE (case-sensetive) is very fast because pgroonga index makes LIKE/ILIKE very very faster .
It seems when case-intensive search mode enabled, LOWER() function and ILIKE operator is used at the same time. only tested in PostgreSQL
and LOWER function is the cause of the slow query problem. If I strip the lower function, query is very fast. Of course case-insensitively. There is no need to use it with ILIKE operator if you want to search case insensitively. 

Why both of which is used at the same time? It is a specification?

If it is a specification, it is very wrong. Performance is very bad. Because unnecessary conversion is performed twice.
 
I suggest LOWER function should be removed because ILIKE is fastable when using index like PGroonga or pg_trgm or gin, on the other hand, LOWER function doesn't make fastable. no index to it.
If you want to cross db platform,  please remove LOWER() only in PostgreSQL. it is not needed bacause Postgres definitely has ILIKE operator.

Please reference this.
https://stackoverflow.com/a/20337500

## How to reproduce
```
    const posts = await this.prisma.post.findMany({
      where: {
        message: {
          contains: 'foo',
          mode: 'insensitive'
        }
      },
```
It produces following select query. (Abbreviated)
```
 SELECT * WHERE LOWER("public"."post"."message") ILIKE $1
```

## Expected behavior

instead
```
 SELECT * WHERE LOWER("public"."post"."message") ILIKE $1
```
no need to use lower() and ILIKE at the same time ! 
```
 SELECT * WHERE "public"."post"."message" ILIKE $1
```
Because ILIKE is fastable when using index.

LOWER() and ILIKE used, 553ms
```
SELECT COUNT(*) FROM (SELECT "public"."post"."id" FROM "public"."post" WHERE LOWER("public"."post"."message") ILIKE '%foo%') AS "sub"
```
ONLY ILIKE , 3ms
```
SELECT COUNT(*) FROM (SELECT "public"."post"."id" FROM "public"."post" WHERE "public"."post"."message" ILIKE '%foo%') AS "sub"
```

## Environment & setup

- OS: WSL
- Database: only tested in PostgreSQL
- Node.js version: 15
- Prisma version:  2.16.1

## note
I also commented in this issue. If this feature is implemented, No need to fix  this issue's bug. Because I can control whole where query as we like.
https://github.com/prisma/prisma/issues/5560

related
https://github.com/prisma/prisma-client-js/issues/690

## ps
I found case-insensitive feature is only available in PostgreSQL in doc.
https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#case-insensitive-filtering

So, please remove lower() function when using ILIKE operator.

https://github.com/prisma/prisma-engines/pull/1011/files#diff-c829ffd620610a11ae51ea659beb120b547ce913dc0632213d7477845bf826f3R399-R404

place where ilike is used
https://github.com/prisma/prisma-engines/pull/1011/files#diff-c829ffd620610a11ae51ea659beb120b547ce913dc0632213d7477845bf826f3R399-R404

place where unnecessary lower() function is used
https://github.com/prisma/prisma-engines/pull/1011/files#diff-c829ffd620610a11ae51ea659beb120b547ce913dc0632213d7477845bf826f3R141
https://github.com/prisma/prisma-engines/pull/1011/files#diff-c829ffd620610a11ae51ea659beb120b547ce913dc0632213d7477845bf826f3R157

and I also suggest when equal() and notEquals()
It produces following query.
```
SELECT * WHERE LOWER("message") = LOWER("foo");
```
Same applys, no need to use slower LOWER function, insetead
```
SELECT * WHERE message ILIKE "foo";
```
is way more faster when using index.

**Comment by gifuhabu** [comment]
I build prisma-engines following diff. simply removing lower() function and make match the default case.
```
$ git diff | cat
diff --git a/query-engine/connectors/sql-query-connector/src/filter_conversion.rs b/query-engine/connectors/sql-query-connector/src/filter_conversion.rs
index 00f63dc56..6255ab4cc 100644
--- a/query-engine/connectors/sql-query-connector/src/filter_conversion.rs
+++ b/query-engine/connectors/sql-query-connector/src/filter_conversion.rs
@@ -139,7 +139,7 @@ impl AliasedCondition for ScalarFilter {
             (Some(alias), ScalarProjection::Single(field)) => {
                 let comparable: Expression = match self.mode {
                     QueryMode::Default => field.as_column().table(alias.to_string(None)).into(),
-                    QueryMode::Insensitive => lower(field.as_column().table(alias.to_string(None))).into(),
+                    QueryMode::Insensitive => field.as_column().table(alias.to_string(None)).into(),
                 };

                 convert_scalar_filter(comparable, self.condition, self.mode, &[field])
@@ -156,7 +156,7 @@ impl AliasedCondition for ScalarFilter {
             (None, ScalarProjection::Single(field)) => {
                 let comparable: Expression = match self.mode {
                     QueryMode::Default => field.as_column().into(),
-                    QueryMode::Insensitive => lower(field.as_column()).into(),
+                    QueryMode::Insensitive => field.as_column().into(),
                 };

                 convert_scalar_filter(comparable, self.condition, self.mode, &[field])
                 
$ cargo build --release
```

and copy the binary to node_modules/.prisma/client/query-engine-debian-openssl-1.1.x

it results removing LOWER function and it works! it makes 15x faster. (305ms -> 20ms)

I realized this fix breaks equal() and notEqual() function with case-insensibility, because without LOWER() = operator is case sensitive.
But I replace equal() with ILIKE operator like 'WORD' without %. full match with case-insensitive

I'm glad you're considering this kind of fix.

**Comment by pantharshit00** [comment]
Thanks for hunch @gifuhabu. This seems an easy win so I have marked this as a candidate.
