### ISSUE TITLE
Prisma Client returns incompatible BigInt type for fields

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma#5750]
## Bug description

When we use JS BigInt feature from ES2020, TypeScript uses the lowercase `bigint` primitive type, just like `number` vs. `Number`:

![image](https://user-images.githubusercontent.com/10618781/108538957-ab2c1b00-72df-11eb-8133-2561c3dbf27c.png)

However, Prisma Client returns `BigInt` interface, which is incompatible with that `bigint` type:

![image](https://user-images.githubusercontent.com/10618781/108539255-08c06780-72e0-11eb-846e-c097b1c68253.png)

## How to reproduce

Create a Prisma model with `BigInt` columns and use Prisma Client method like `.findFirst()` to get the data.
Then try to assign to a property/variable of `bigint` primitive type.

## Expected behavior

Prisma Client should return primitive `bigint` type, just like it do with `string` or `number`.

## Prisma information

```prisma
model reveal {
  operation_id      BigInt          @id
  fee               BigInt
}
```

## Environment & setup

- OS:  Ubuntu 20.04
- Database:  PostgreSQL
- Node.js version:  15.8
- Prisma version:

```
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.353.0
Preview Features     : orderByRelation
```

**Comment by pantharshit00** [comment]
Looks like a mapping mistake, we should fix this.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/client`.
You can try it out with `npm i @prisma/client@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by eamonbanta-exwzd** [comment]
This is still not working for me using "@prisma/client": "^2.23.0". Is this still dev only?

**Comment by bluedge** [comment]
I'm using the last version of Prisma/client and I'm seeing the same issue using BitInt (MySQL)
```
"@prisma/client": "3.6.0",
"prisma": "3.6.0"
```

Result on simple Select query:
``` 
productId: 4570552959233n,
variantId: 42122478125313n,
```

Schema
```
model Transfers {
	id 					Int			@id @default(autoincrement())
	productId			BigInt
	variantId			        BigInt
	qty					Int
	expectedArrival		DateTime
	purchaseOrderNumber	String
	received			        Boolean		@default(false)
	createdAt			DateTime	@default(now())
	updatedAt			DateTime	@updatedAt
}
```

**Comment by janpio** [comment]
Please open a new issue @bluedge. Thanks. 

On the other hand what you posted does not actually look like the original problem here, but the normal console.log output of a BigInt: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/toString

**Comment by bluedge** [comment]
@janpio Thank you for your answer.
I'm not sure it makes much sense for PRISMA to return BIGINT following the exact Schema (MySQL) format when retuning data that have to be used as a JS object. (even if BIGINT exit in JS) It is a bit impractical to have to parse them later down the road. It might be a nice option to be able to return another format (String, Integer,..).
Prisma is Amazing, We love it!

**Comment by rode093** [comment]
Facing same trouble with latest version of prisma. Older version is working good

**Comment by janpio** [comment]
Please open a new issue and describe your problem in detail @rode093.

**Comment by giladv** [comment]
same issue with latest version.

**Comment by espired** [comment]
Same here @giladv

**Comment by janpio** [comment]
https://github.com/prisma/prisma/issues/5750#issuecomment-1200285673
