### ISSUE TITLE
to enabled env for provider in prisma.schema

### ISSUE THREAD

**Issue by calidion** [prisma/prisma#5755]
## Problem

to enabled env for provider.

## Suggested solution

```
datasource db {
  provider = env("DATABASE_PROVIDER")
  url      = env("DATABASE_URL")
}
```

**Comment by pantharshit00** [comment]
This has been deprecated: https://github.com/prisma/prisma/issues/3834

Changing datasource provider dynamically is not really feasible as different datasource support different native types and it can render a schema ambiguous if one datasource used the feature which is not offered by other datasource.
