### ISSUE TITLE
Support for index hints

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#579]
It can happen that the same set of database index can make one query optimal while another query less optimal. 

Datasources (SQL/document) has index feature hints to modify this behavior: 

MySQL: https://dev.mysql.com/doc/refman/8.0/en/index-hints.html
Mongo: https://docs.mongodb.com/manual/reference/operator/meta/hint/
Postgres (doesn't have it but considering): https://wiki.postgresql.org/wiki/OptimizerHintsDiscussion

This issue tracks this idea around Prisma 2.

**Comment by terrierscript** [comment]
Is this resolved?
How can I use index hint on MySQL?

**Comment by janpio** [comment]
Back in the day you could not close as "not planned", which we would use today. 
Prisma does not support this today. If you need it, please open a new feature request issue for it. Thanks!
