### ISSUE TITLE
Rust client

### ISSUE THREAD

**Issue by ArcticSpaceFox** [prisma/prisma#5790]
Currently there are only Js, Ts and Go clients. Can we have a rust version as well?

**Comment by pantharshit00** [comment]
Checkout our SQL abstraction for Rust for now: https://github.com/prisma/quaint/

It is more primitive than prisma but it might help you in your projects if you don't want to use SQLx

**Comment by ArcticSpaceFox** [comment]
Thanks I just love prisma sooo much, the schema and everything just makes db stuff so easy. Just want it for rust, thanks for the tip. I will keep an eye on this issue tho 😄👍

**Comment by auderer** [comment]
Prisma would be amazing for Rust. Are there any plans to build this out in the future?

**Comment by Milo123459** [comment]
Any updates?

**Comment by fivethreeo** [comment]
There is the unofficial https://github.com/seunlanlege/prisma-client-rs

**Comment by Brendonovich** [comment]
There is also my library [prisma-client-rust](https://github.com/Brendonovich/prisma-client-rust) which has an alternative syntax to [prisma-client-rs](https://github.com/seunlanlege/prisma-client-rs)

**Comment by merelinguist** [comment]
It seems there is now no longer a Go client either https://github.com/prisma/prisma-client-go/issues/707#issuecomment-1000239342

**Comment by VaZark** [comment]
With the team currently focussing exclusively on the JS/TS environment, I don't see this happening anytime soon. 

That being said, I'd love to see if it'd possible to have a primitive rust crate that handles migrations and re-exposes quaint as a querybuilder for the moment.

**Comment by JonathanWilbur** [comment]
One thing I just thought of that I wanted to share: I know the Prisma engine itself is written in Rust. Would there be any way to just support rust clients by binding directly / statically linking the Prisma engine? Forgive me if that's a stupid question. I only barely understand that the TS client sends GraphQL queries to the engine. It just seems like this could be bypassed entirely by a rust client.

**Comment by JonathanWilbur** [comment]
Not to mention, if a single compiled programming language is supported, it would be easier for all other compiled languages (including Go) to just link to it as well, so you'd kind of have support for many languages all for the cost of one.

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community.

If you want the familiar Prisma experience in Rust, I'd recomment checking out the third-party projects that were mentioned above.

---

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
