### ISSUE TITLE
Some raw queries break on older versions of Postgres

### ISSUE THREAD

**Issue by tsiege** [prisma/prisma#5791]
## Bug description
I use Postgres `ltree` type to handle some needed graph capabilities. [Ltree is not currently supported in the Prisma API](https://github.com/prisma/prisma/discussions/2494#discussioncomment-15214), and when attempting to use a raw query I get an error about binary input not being supported. I have done some research on this and found a similar [bug reported in the npgsql project](https://github.com/npgsql/npgsql/issues/878). It seems that while the ltree module has been in postgres from at least 8.3, binary queries for it has only just started being supported in [version 13](https://www.postgresql.org/docs/13/release-13.html). I'm guessing this is more an issue for the Prisma Engine, but I'm wondering if it'd be possible to have string query fallback support for older versions of Postgres as I'm unable to upgrade to Postgres version 13 at the moment. I understand if this isn't possible, but wanted to raise the issue.

## How to reproduce
Running any raw ltree query will produce this error
```ts
const path = 'a.b.f.g'
await prisma.$queryRaw`select * from "nodes" where path @> ${path}`
```

## Expected behavior
It does not error due to a binary query

## Prisma information
```
  Error: [
  {
    "message": "\nInvalid `prisma.queryRaw()` invocation:\n\n\n  Raw query failed. Code: `42883`. Message: `db error: ERROR: no binary input function available for type ltree`",
    "locations": [
      {
        "line": 4,
        "column": 11
      }
    ],
    "path": [
      "commentById",
      "ancestors"
    ],
    "extensions": {
      "code": "INTERNAL_SERVER_ERROR",
      "exception": {
        "code": "P2010",
        "clientVersion": "2.17.0",
        "meta": {
          "code": "42883",
          "message": "db error: ERROR: no binary input function available for type ltree"
        }
      }
    }
  }
]
```

## Environment & setup

- OS: 10.15.2 (19C57)- Database: PostgreSQL 12.3 on x86_64-apple-darwin19.4.0, compiled by Apple clang version 11.0.3 (clang-1103.0.32.59), 64-bit
- Node.js version: v13.11.0
- Prisma version: 2.16.1

**Comment by TSiege** [comment]
I'll add a addendum to this, casting the field as a string and using Prisma to simply fetch this field on a normal query also breaks because of lack of binary support for ltree.

**Comment by pantharshit00** [comment]
This is reproducible and I think this is blocked by https://github.com/prisma/prisma/issues/3337

**Comment by hyusetiawan** [comment]
does this mean, `ltree` cannot be used in any way (raw query or otherwise)?

**Comment by pantharshit00** [comment]
@hyusetiawan Yes, unfortunately that is the case right now.

**Comment by jkomyno** [comment]
Hi @tsiege, I'm closing this issue in favor of https://github.com/prisma/prisma/issues/3337.
Moreover, you can monitor our support for the `ltree` extension in https://github.com/prisma/prisma/issues/2568.

@hyusetiawan, I believe `ltree` can currently be used via raw queries without problems starting from Postgres 13. Could you please check?
