### ISSUE TITLE
Inconsistent Migrate Schema created

### ISSUE THREAD

**Issue by maxweld** [prisma/prisma#5801]
## Bug description

A prisma migration produced alter statements that were inconsistent. Specifically an explicit M:M relationship table was created with both key columns set as NOT NULL, then an ALTER statements created a FK which had an 'ON DELETE SET NULL' clause. During execution, this then failed.

## How to reproduce

Sadly, in trying to sort myself out, I tweaked the schema.prisma file, and cannot now reproduce the problem. 

I believe that I corrected a partial relationship definition in the schema.prisma file, something like:

`colname Model   @relationship("some_name") `

but I am not really sure and I have been unable to backtrack my modifications and so cannot reproduce the error.

## Expected behavior

I now know that I had some issues with my relationship definitions. In particular I had crossed my two required relationships so that addressId referenced the id field of the Person model, and personId referenced the id field of the  Address model. That is an error of mine, but was logically correct, and thus the 2 FK Relationships set up were correct although would have given me problems later when I tried to debug problems. I do not expect that Prisma could detect this sort of problem during migration.

Then a third FK relationship was constructed by the migration. This FK had an 'ON DELETE SET NULL' clause, despite the table definition setting the column to NOT NULL. This is clearly inconsistent, and should therefore not be possible. At least it should be picked up by Prisma during preparation of the migration SQL, and not at execution time, as in a production system this could leave the application needing a DB restore.

Sadly, in trying to sort this out, I have modified the schema.prisma file and can no longer reproduce the error. @tom requested that I submit a bug report nevertheless.

As a thought, it would be nice if a) the schema.prisma file was copied to the directory with the corresponding migration.sql as a reference, and b) if it was possible to build the migration.sql file, and then stop the migration at this point so the SQL could be reviewed. Subsequently the migration could be restarted from that point.  

## Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: v14.15.0
- Prisma version: 2.17.0

```

```

**Comment by Jolg42** [comment]
Originally posted in Public Slack https://prisma.slack.com/archives/CKQTGR6T0/p1614067634134400

**Comment by tomhoule** [comment]
Note that there is a regression on MySQL on windows in 2.17.0. It will be fixed in 2.18.0. Does reverting to 2.16.0 fix your problem?

**Comment by maxweld** [comment]
Sadly as I can no longer reproduce the issue, I cannot say whether it would be fixed by reverting. If it reoccurs, I will definitely try 2.16.0 and let you know.

**Comment by pantharshit00** [comment]
I will close this for now to clean up things. Feel free to comment here if this reoccurs.
