### ISSUE TITLE
Postgres unique constraint querying broken

### ISSUE THREAD

**Issue by lucasjohnston** [prisma/prisma#5821]
## Bug description

Cannot query by unique constraints despite being able to in the Client.

## How to reproduce

Create a `@@unique()` relation and try to query it.

## Expected behavior

It not to be broken.

## Prisma information

```
Error: Invalid `prisma.user.findUnique()` invocation:

{
  where: {
    User_unique_email: {
    ~~~~~~~~~~~~~~~~~
      email: 'email@goes.here',
      deleted: false
    },
    deleted: false
  },
}

Unknown arg `User_unique_email` in where.User_unique_email for type UserWhereInput. Available args:
[every database param that's not unique goes here]
```

## Environment & setup

- OS: macOS 11.2
- Database: PostgreSQL
- Node.js version: v14.15.5
- Prisma version:

```
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : darwin
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at ../../../.config/yarn/global/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at ../../../.config/yarn/global/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at ../../../.config/yarn/global/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at ../../../.config/yarn/global/node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.353.0
```

**Comment by janpio** [comment]
False alarm @lucasjohnston?

**Comment by lucasjohnston** [comment]
yeah :)
i switched to using soft deletes and had adopted middleware from the docs to account for this, but was still hitting an error when trying to query. initially i thought this was a prisma bug, but realised this was actually because prisma doesn't recognise `null` as a unique field (have added my voice to the issue #3387) so i couldn't use `deleted: Date` and have `@@unique()` properties.

i got around it by adding two fields, a `deleted: bool` and `deletedAt: Date?` and now manually create unique constraints with sql migrations.

**Comment by euclid1990** [comment]
@lucasjohnston 
I have been modify Soft delete middleware as the [doc](https://www.prisma.io/docs/concepts/components/prisma-client/middleware/soft-delete-middleware#step-2-soft-delete-middleware) for support findUnique with alias:

```typescript
import { assign, forOwn, isObject } from 'lodash';

...
      if (params.action == 'findUnique') {
        forOwn(params.args?.where, (value, key) => {
          // If the field is a compound unique index
          if (isObject(value)) {
            delete params.args.where[key];
            params.args.where = assign(params.args.where, { ...value });
          }
        });
        // Change to findFirst - you cannot filter
        // by anything except ID / unique with findUnique
        params.action = 'findFirst';
        // Add 'deletedAt' filter
        // ID filter maintained
        params.args.where['deletedAt'] = null;
      }
...
```
Although it losing the nice guarantees of uniqueness, but working fine !
Sorry because I live lodash, so I use some utilities of lodash alternative native javascript 😢
