### ISSUE TITLE
syntax highlighting and auto-formatting for neovim

### ISSUE THREAD

**Issue by yamatsum** [prisma/prisma#5828]
## Problem
Looking at the following document, I created a PR because neovim is not included in the target editor.
https://www.prisma.io/docs/concepts/more/editor-setup

I want you to support  syntax highlighting and auto-formatting on neovim

## Suggested solution
Since version 0.5, neovim supports treesitter as standard.
I hope prisma also supports treesitter.
https://github.com/nvim-treesitter/nvim-treesitter

## Additional context
Extensions for vim (not treesitter)
https://github.com/pantharshit00/vim-prisma

language server using the above
https://github.com/pantharshit00/coc-prisma

unofficial Prisma language parsing
https://github.com/victorhqc/tree-sitter-prisma

**Comment by pantharshit00** [comment]
I can give this a go when I get some free time but I haven't personally switched to nvim 0.5 as it is not stable yet.

**Comment by yamatsum** [comment]
@pantharshit00 
0.5 released!
https://github.com/neovim/neovim/releases/tag/v0.5.0

**Comment by pantharshit00** [comment]
https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/prismals.lua

Prisma LSP is already added into the lspconfig repo which you can use.

**Comment by yamatsum** [comment]
@pantharshit00 
Are there any plans for syntax highlighting by treesitter?

**Comment by yamatsum** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/1958

**Comment by pantharshit00** [comment]
Awesome! That is great news.
