### ISSUE TITLE
Support for concatenation in Prisma file

### ISSUE THREAD

**Issue by siberian-man** [prisma/prisma#584]
I would like to do something like this:

```
datasource db {
  provider = env("DB_PROVIDER")
  url      = `${env("DB_PROVIDER")}://${env("DB_USER")}@${env("DB_HOST")}:${env("DB_PORT")}/${env("DB_NAME")})`
}
```

I need to have all the parts of the Connection URL to be stored separately, because some tools, like pgtool npm package, doesn't support connection URLs. Thus all the parts, like username, hostname or port, should be passed separately.

As a workaround, currently I parse Connection URL using `new URL(connectionUrl)` and extract all the parts after that. But anyway, I suppose this feature may be required by other similar use-cases, where this workaround will not be suitable.

**Comment by pantharshit00** [comment]
This actually belongs here

**Comment by janpio** [comment]
Another use case would be if your database connection string needs to be concatenated depending on your ENV vars, to for example enable or disable SSL (independent on the connection string itself)

**Comment by albertoperdomo** [comment]
The feature request is now being tracked at https://github.com/prisma/prisma/issues/2559.
Please subscribe and comment on that issue for this topic.
