### ISSUE TITLE
Docs: Migrate advisory locking mechanism

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#5843]
Migrate has an advisory locking mechanism since 2.17 implemented by @tomhoule

see https://github.com/prisma/prisma-engines/issues/1118

Why a locking in Migrate?
Because migrations should not be running concurrently on the same database.

I think it would be great to document this and have an answer for
- What happens if two migrate deploy command run simultaneously? One gets the lock and the other fails?
- Does it uses timeouts? Is it configurable?

It's an important detail to know for deployments I think.

Tom would be the best person to write about how it works.

When we have the details we can open an issue for the docs [here](https://github.com/prisma/docs/issues/new?assignees=&labels=docs&template=doc_request.md&title=Doc+request%3A)

**Comment by tomhoule** [comment]
Planning to discuss this, then document (also look at what other migration tools document)

**Comment by albertoperdomo** [comment]
Closed in favor of https://github.com/prisma/docs/issues/1381
