### ISSUE TITLE
Prisma fails to migrate in dev after git reset

### ISSUE THREAD

**Issue by eloiqs** [prisma/prisma#5850]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`migrate --preview-feature dev`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v12.17.0           | 
| Prisma CLI  | 2.16.1             | 
| Binary      | 8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03| 

## Error
```
Error: Error in migration engine.
Reason: [/root/build/migration-engine/core/src/commands/diagnose_migration_history.rs:101:26] Failed to read migration script: ReadMigrationScriptError(Os { code: 2, kind: NotFound, message: "No such file or directory" }, SpanTrace [{ target: "migration_connector::migrations_directory", name: "read_migration_script", fields: "self=MigrationDirectory { path: \"/Users/eloi/development/dsi-ing/server/prisma/migrations/20210225183705_options_units_on_quote_items_with_defaults\" }", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 233 }, { target: "migration_connector::migrations_directory", name: "matches_checksum", fields: "self=MigrationDirectory { path: \"/Users/eloi/development/dsi-ing/server/prisma/migrations/20210225183705_options_units_on_quote_items_with_defaults\" } checksum_str=\"a6398bef174ab2202a9758e831ffc14f5c7d8bee9dc2fa917053642be19f4d9f\"", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 207 }, { target: "migration_core::api", name: "DevDiagnostic", file: "migration-engine/core/src/api.rs", line: 100 }])

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

```

Hey there, I was just prototyping some feature on my local machine and decided I wanted to drop my work. Now it looks like prisma migrate fails to lookup the prototype migration I had worked on and crashes. 

I don't care if prisma does not find it because it was just a prototyping exercise.

**Comment by eloiqs** [comment]
Just found the issue: git reset did not delete the `20210225183705_options_units_on_quote_items_with_defaults` folder, only its contents. Deleting it manually fixes the issue, but maybe prisma could be a bit more smart about this!

**Comment by tomhoule** [comment]
Since 2.17.0, we return a much better error in that scenario that explains how to solve the problem. Thanks for opening the issue!
