### ISSUE TITLE
Override setting search_path and NAMES on every connection to avoid connection pinning with RDS Proxy

### ISSUE THREAD

**Issue by f0rr0** [prisma/prisma#5864]
## Problem

Not sure where this belongs so I am referencing this as a feature request here. Apologies if that's not right.

https://github.com/prisma/prisma-engines/issues/1692

Setting `search_path` and `NAMES` for every new connection causes connections to be pinned with RDS Proxy. 

## Suggested solution

An option to ignore/skip setting these for every connection by overriding the connection behaviour.

## Additional context

https://github.com/prisma/prisma-engines/issues/1692

**Comment by janpio** [comment]
Yep, I moved that other issue over here so that one will be enough to be looked into.
