### ISSUE TITLE
Feature request - Migrate: When Drift Detected -> give more Details than just the rollback script

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#5873]
## Problem

The CLI reports some "Drift", it's not clear what it is.

## Suggested solution

Provide more insight about the drift detected. Is it a column property, or entire tables that are missing?

**Comment by janpio** [comment]
Example from internal discussion: https://prisma-company.slack.com/archives/CGMCB82N8/p1617885743151100

**Comment by tomhoule** [comment]
Scheduling this for this cycle to come up with a proposal, along with related issue: https://github.com/prisma/migrations-team/issues/223

**Comment by albertoperdomo** [comment]
In the Slack thread commented above, the motivation to understand drift is for troubleshooting. The user had added a table and it was unclear to him/her, why Prisma Migrate was reporting any drift.

There are different ways this drift could be surfaced:
* abstracted: a summary of the diff, e.g. tables/columns missing, unexpected tables/columns found, difference in expected types or default values.
* detailed: a DDL script describing the changes that would required to remove the drift.

**Comment by deloreanz** [comment]
This is pretty crucial for feedback on how to resolve the issue manually.  A step further could be an option to generate a migration to get the database back in line with the Prisma schema, but currently I'd be delighted just to be able to see the detected drift.

**Comment by deloreanz** [comment]
Prisma is still detecting a drift despite the fact that my Postgres structural diff detects no changes.  Hopefully when more verbose detected drift feedback is available it can list exactly what it doesn't like, even when other compare tools see no diff.

**Comment by tomhoule** [comment]
https://github.com/prisma/prisma-engines/pull/2002 means that the next release (and dev releases very soon) will have human-readable drift summaries. They will probably be a bit rough at the beginning, but we will improve them over time.

**Comment by Jolg42** [comment]
You can now try 2.25.0 and let us know what you think 😉
