### ISSUE TITLE
ENUM in prisma migration

### ISSUE THREAD

**Issue by BogdanBalcau** [prisma/prisma#5883]
## Bug description

Whenever I try to migrate from a schema where there is an ENUM to a schema where there are no ENUMS, I get an error and the migration does not complete: "db error: ERROR: cannot drop type ... because other objects depend on it"

## How to reproduce

SAVE and UP on a migration with an ENUM, SAVE and UP on a migration without ENUMS.

**Comment by jrvidotti** [comment]
I can confirm this behavior...
