### ISSUE TITLE
Getting a "Cannot read property 'xxx' of undefined" running jest tests

### ISSUE THREAD

**Issue by aabedraba** [prisma/prisma#5896]
## Bug description

When running jest tests directly over typescript, and having mocked prisma, I get an error of `Cannot read property 'xxx' of undefined`

The way the test is written is the same way it was written with prisma version 2.10, but after upgrading typescript to 4.1 and prisma to 2.17, I started getting this error.

## How to reproduce

Created a repro repo here with the instructions: https://github.com/aabedraba/prisma-jest-repro

## Expected behavior

The test should run successfully. 

## Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id   Int    @id @default(autoincrement())
  name String
}
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.15.5
- Prisma version:
```
Environment variables loaded from .env
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : darwin
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.353.0
```

**Comment by aabedraba** [comment]
Hey folks! Any update to this? 

I have worked on it for sometime and didn't get any further.

The main route I tracked down is jest mocking of ES6 classes, but nothing that allows the automatic jest mock https://jestjs.io/docs/en/es6-class-mocks#automatic-mock

**Comment by pantharshit00** [comment]
@aabedraba Please refer to https://github.com/prisma/prisma/discussions/2083#discussion-901 for creating a mocked prisma client instance. Let me know if that worked for you.

**Comment by aabedraba** [comment]
Thanks @pantharshit00 for your response, although that is not the path that I'd like to solve this issue. 

If you could give me hints on why this happened, I could find an alternative solution. 

This is the CI pipeline test running with the same test files [ unsuccessfully on 2.18](https://github.com/aabedraba/prisma-jest-repro/runs/2107181913) and [successfully with 2.12](https://github.com/aabedraba/prisma-jest-repro/runs/2107203565)

**Comment by aabedraba** [comment]
Took the solution and successfully implemented it using jest-mock-extended library. 

Thanks @pantharshit00 !
