### ISSUE TITLE
MICROSOFT SQL CONNECTOR - CONNECTION LIMIT

### ISSUE THREAD

**Issue by marcelommss** [prisma/prisma#5897]
Hi,

I'm testing the **MICROSOFT SQL CONNECTOR** in prisma with a SQL DATABASE hosted on AZURE and it's working fine in local environment.
But when I deploy to _VERCEL_, there is the problem: Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `**connection_limit**` parameter (https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#connection-pool). Current limit: 5.

The problem is there is no way to set connection_limit in the MSSQL connection string.

There is no way to procede using Prisma and Microsoft SQL with this limitation.

Please, help!

**Comment by pimeys** [comment]
I guess that's not documented properly. In SQL Server the parameter is `connectionLimit=10`. I'm fixing the docs.

**Comment by marcelommss** [comment]
Hi pimeys, i tried putting it in the end of the connection string and it's worked.
