### ISSUE TITLE
Tests: add tests for `prisma format` cli command

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#5910]
https://github.com/prisma/prisma/blob/master/src/packages/cli/src/Format.ts could use some tests

**Comment by Iamshankhadeep** [comment]
hey @Jolg42 I will love to work on this.

**Comment by Jolg42** [comment]
@Iamshankhadeep Sure! Thanks!

So actually a test is already here
https://github.com/prisma/prisma/blob/fc68127b51c5d51684211978b057a019569051a9/src/packages/cli/src/__tests__/format.test.ts

So it could be improved with more tests on different schemas:

Like these maybe, they can be added to this folder https://github.com/prisma/prisma/tree/fc68127b51c5d51684211978b057a019569051a9/src/packages/cli/src/__tests__/fixtures/example-project/prisma

`missing-backrelation.prisma`
```
generator client {
  provider = "prisma-client-js"
  output   = "../generated/client"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model Post {
  id     Int @id
  user   User
}

model User {
  id     Int @id
  posts  Post[]
}
```

@do4gr any other schema we could test for?

It could also be interesting to test for broken schemas like this and expect an error

`broken.prisma`
```
this is a broken schema
```

I could also see a big/complex schema test like copied from https://github.com/prisma/prisma/blob/fc68127b51c5d51684211978b057a019569051a9/src/packages/migrate/src/__tests__/fixtures/nativeTypes-postgresql/prisma/schema.prisma
maybe named `native-types-postgresql.prisma`
