### ISSUE TITLE
📝 Help us improve our release notes on GitHub

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#5913]
Hey Prisma friends 👋 

We want to ensure our [release notes](https://github.com/prisma/prisma/releases) are as helpful as possible to all of you. If you want to help us improve the release notes, it would be great if you could answer the questions below!

Also, if you have any other questions or comments about our release notes or general inspiration and suggestions for improvements, feel free to drop them in this issue as a comment!

--- 

**How often do you read Prisma's release notes on GitHub?**

[![](https://api.gh-polls.com/poll/01EZPPQEWH8W5CX9G26S9962D0/Always)](https://api.gh-polls.com/poll/01EZPPQEWH8W5CX9G26S9962D0/Always/vote)
[![](https://api.gh-polls.com/poll/01EZPPQEWH8W5CX9G26S9962D0/Sometimes)](https://api.gh-polls.com/poll/01EZPPQEWH8W5CX9G26S9962D0/Sometimes/vote)
[![](https://api.gh-polls.com/poll/01EZPPQEWH8W5CX9G26S9962D0/Never)](https://api.gh-polls.com/poll/01EZPPQEWH8W5CX9G26S9962D0/Never/vote)

---

**How thoroughly do you read Prisma's release notes on GitHub?**

[![](https://api.gh-polls.com/poll/01EZPYTV3RH60G6Z824JSXAG8Z/I%20read%20all%20of%20them%20very%20thoroughly)](https://api.gh-polls.com/poll/01EZPYTV3RH60G6Z824JSXAG8Z/I%20read%20all%20of%20them%20very%20thoroughly/vote)
[![](https://api.gh-polls.com/poll/01EZPYTV3RH60G6Z824JSXAG8Z/I%20read%20only%20the%20parts%20that%20I'm%20interested%20in)](https://api.gh-polls.com/poll/01EZPYTV3RH60G6Z824JSXAG8Z/I%20read%20only%20the%20parts%20that%20I'm%20interested%20in/vote)
[![](https://api.gh-polls.com/poll/01EZPYTV3RH60G6Z824JSXAG8Z/I%20only%20skim%20over%20them)](https://api.gh-polls.com/poll/01EZPYTV3RH60G6Z824JSXAG8Z/I%20only%20skim%20over%20them/vote)

--- 

**Do you _generally_ prefer longer or shorter release notes?**

[![](https://api.gh-polls.com/poll/01EZPYYDC39TNPPJFC5J0007BZ/Shorter)](https://api.gh-polls.com/poll/01EZPYYDC39TNPPJFC5J0007BZ/Shorter/vote)
[![](https://api.gh-polls.com/poll/01EZPYYDC39TNPPJFC5J0007BZ/Longer)](https://api.gh-polls.com/poll/01EZPYYDC39TNPPJFC5J0007BZ/Longer/vote)

 --- 

**How do you learn about new releases?**

[![](https://api.gh-polls.com/poll/01EZQ8FPNCNZDDE5WMP8MDVVYT/Slack%20announcement)](https://api.gh-polls.com/poll/01EZQ8FPNCNZDDE5WMP8MDVVYT/Slack%20announcement/vote)
[![](https://api.gh-polls.com/poll/01EZQ8FPNCNZDDE5WMP8MDVVYT/Twitter%20announcement)](https://api.gh-polls.com/poll/01EZQ8FPNCNZDDE5WMP8MDVVYT/Twitter%20announcement/vote)
[![](https://api.gh-polls.com/poll/01EZQ8FPNCNZDDE5WMP8MDVVYT/I%20actively%20check%20GitHub%20for%20a%20new%20release)](https://api.gh-polls.com/poll/01EZQ8FPNCNZDDE5WMP8MDVVYT/I%20actively%20check%20GitHub%20for%20a%20new%20release/vote)
[![](https://api.gh-polls.com/poll/01EZQ8FPNCNZDDE5WMP8MDVVYT/Other)](https://api.gh-polls.com/poll/01EZQ8FPNCNZDDE5WMP8MDVVYT/Other/vote)

**Comment by Ezard** [comment]
Firstly, I'd just like to say that it's awesome that the Prisma team puts so much effort into the release notes 👏 

As a suggestion though, might it be an idea to keep the release notes shorter on GitHub (i.e. list of features, fixes and breaking changes), and then link to the detailed release notes on a webpage?

This allows people to get a quick overview of what a release contains on GitHub, and but also means that they have access to the super-detailed notes if they're interested

As an alternative, you could use `details`/`summary` tags in the GitHub release notes to hide the details by default (like in [this gist](https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287))

**Comment by puchm** [comment]
I have to say I really like your release notes. Providing examples is a very good thing. Also separating the changes into major stuff and Fixes & Improvements is great.

One thing I would improve is to provide a little introduction. Maybe write one sentence about what your focus with the release was or what the most important feature you added is (e.g. _"This release mainly focuses on migrations"_). 
Then provide a brief list of the major changes. That list should just be bullet points with the headings from the major changes section. Pretty much the same thing you already have on Twitter but at the top of the release notes as well.
