### ISSUE TITLE
Precision issue when persisting Decimal.js objects

### ISSUE THREAD

**Issue by eemelipa** [prisma/prisma#5925]
## Bug description

Persisting `new Prisma.Decimal('8.7')` to db results in `8.699999999999999` being saved to db. Same happens with `new Decimal('8.7')` and `8.7` (plain js number).

Same issue happens with a few other numbers:
```
8.8 => 8.800000000000001
9.2 => 9.199999999999999
```

## How to reproduce

Reproduce with repo https://github.com/eemelipa/prisma-test/tree/prisma-decimals branch "prisma-decimals".

Run
```
npm run db:up
npm install
npm run migrate:dev
npm run start
```

See error logs in console and printed object

## Expected behavior

Persisting any of the following

```
    price1: 8.7,
    price2: new Decimal('8.7'),
    price3: new Prisma.Decimal('8.7'),
    price4: '8.7',
```

should result in `8.7` saved to db without precision issues. Currently only passing the value as a string (price4) works as expected.

## Prisma information

See https://github.com/eemelipa/prisma-test/tree/prisma-decimals

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL (at least)
- Node.js version: v14.15.4 
- Prisma version:

```
Environment variables loaded from .env
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : darwin
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.353.0
```

## Debug Logs

[debug-logs.txt](https://github.com/prisma/prisma/files/6064283/debug-logs.txt)

**Comment by eemelipa** [comment]
Reproduces in prisma 2.18.0:

```
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : darwin
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.356.0
```

**Comment by pantharshit00** [comment]
I can reproduce this. Thanks for the reproduction repository.

**Comment by borovik96** [comment]
Any updates? It is very critical issue

**Comment by timpetri** [comment]
Does anyone have some kind of a workaround for this?

**Comment by ravi0lii** [comment]
> Does anyone have some kind of a workaround for this?

You can pass the Decimal instances with `.toString()` instead of passing the Decimal object
