### ISSUE TITLE
Order that rows are created in a nested create

### ISSUE THREAD

**Issue by olliechick** [prisma/prisma#5935]
## Bug description

When doing a nested create, rows are not created in the order specified in the `create` field.

## How to reproduce

1. Run a nested create, for example, if there is a house model which can contain many residents:
```ts
await prisma.house.create({
  data: {
    residents: {
      create: [
        { name: 'Ollie' },
        { name: 'Mia' },
        { name: 'Noah' }
      ]
    }
  }
});
```
2. See the order that items were added to the database.

## Expected behavior

I expect them to be added in the order they are in the `create` field. For example, if `create` is `[{name: "Ollie"}, {name: "Mia"}, {name: "Noah"}]`, then I would expect `{name: "Ollie"}` to be created first, then `{name: "Mia"}`, then `{name: "Noah"}`. However, from a few queries I've tried  they appear to get created in the opposite order (I'm not sure if I could rely on this though, or if this is just an artifact of the underlying architecture).

**Comment by olliechick** [comment]
Or is this functionality available by using a nested `createMany`? If so, it should be added to the [docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#createmany-preview-1).

**Comment by pantharshit00** [comment]
@olliechick Order is not guaranteed here. This is expected. If you want to retrieve records by order, store a position column or you can order by cuid as they are binary searchable.
