### ISSUE TITLE
regression: Running multiple findUnique's in parallel causes both to return null

### ISSUE THREAD

**Issue by CDDelta** [prisma/prisma#5941]
## Bug description

It appears as though issue #4438 has regressed and reappeared in Prisma version 2.17.

## How to reproduce

Outlined in #4438. I tested this out with Prisma 2.17 using this repo: https://github.com/harshit-test-org/prisma-issue-4438

## Expected behavior

Parallel `findUnique()` queries should not cause both to return null.

## Prisma information

N/A

## Environment & setup

- OS: Mac OS
- Database: SQLite (I personally ran the test repo using SQLite)
- Node.js version: v15.8.0
- Prisma version: v2.17.0

**Comment by pantharshit00** [comment]
I can also reproduce this again with 2.18 and latest dev `2.19.0-dev.21`. We need to look into this again.
