### ISSUE TITLE
Unknown arg error when it is in the schema

### ISSUE THREAD

**Issue by cyates81** [prisma/prisma#5949]
## Bug description

I have a schema with a field called emailVerificationToken on the User model. I am trying to use findUnique on that field but I'm getting an unknown arg error. It's saying only id? and email? are available args.

I tried running npx prisma generate

## How to reproduce

Run the query below with the schema.

## Expected behavior

Expected to return a user.

## Prisma information

schema:
```
model User {
  id                        Int       @default(autoincrement()) @id
  createdAt                 DateTime  @default(now())
  email                     String    @unique
  emailVerified             Boolean   @default(false)
  emailVerificationToken    String
  username                  String?
  status                    String
}
```
query:
```
const user = await prisma.user.findUnique({ 
    where: { emailVerificationToken: req.body.emailVerificationToken }
  })
```
error:
```
{ Error: 
Invalid `prisma.user.findUnique()` invocation:

{
  where: {
    emailVerificationToken: 'testtoken'
    ~~~~~~~~~~~~~~~~~~~~~~
  }
}

Unknown arg `emailVerificationToken` in where.emailVerificationToken for type UserWhereUniqueInput. Available args:

type UserWhereUniqueInput {
  id?: Int
  email?: String
}


    at Document.validate (/Users/chris/Projects/tendiefi/node_modules/@prisma/client/runtime/index.js:76461:19)
    at NewPrismaClient._executeRequest (/Users/chris/Projects/tendiefi/node_modules/@prisma/client/runtime/index.js:78299:17)
    at resource.runInAsyncScope (/Users/chris/Projects/tendiefi/node_modules/@prisma/client/runtime/index.js:78234:52)
    at AsyncResource.runInAsyncScope (async_hooks.js:188:21)
    at NewPrismaClient._request (/Users/chris/Projects/tendiefi/node_modules/@prisma/client/runtime/index.js:78234:25)
    at Object.then (/Users/chris/Projects/tendiefi/node_modules/@prisma/client/runtime/index.js:78354:39)
    at process._tickCallback (internal/process/next_tick.js:68:7) clientVersion: '2.17.0' }
```

## Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: 10.18.0
- Prisma version:

```
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : darwin
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.356.0
```

**Comment by shrugs** [comment]
you'll have to indicate that the verification token is unique with an index (`@unique`). or, if it's not unique, you could use `findFirst`, which will construct something like `WHERE token = $1 LIMIT 1`

**Comment by cyates81** [comment]
Okay, thanks, I apologize if I missed that explanation in the docs. If not, then it's something that should probably be added.

I also experienced something unexpected for me when I changed to findFirst. The value I was comparing emailVerificationToken to was undefined. I would expect it to return null, but instead it returned a record, not exactly sure how it selected that record as it had a value in that column.

As you can tell I just started using Prisma yesterday. Thanks again.

**Comment by shrugs** [comment]
if i understand correctly what's happening there is that prisma is seeing `{ token: undefined }` and will basically ignore that condition when generating the query. if you'd like to search for null tokens, you can use `{ token: null }`

**Comment by cyates81** [comment]
Yeah, it appears that's the case. I think that could introduce rather destructive behavior as a runtime bug if query values aren't checked for undefined.
