### ISSUE TITLE
Vim Plugin

### ISSUE THREAD

**Issue by dan003400** [prisma/prisma#5957]
A lot of VSCode code plugins have also been ported to vim and vim-coc.

It would be nice that prisma did not only have the best developer experience in just a single editor.

**Comment by pantharshit00** [comment]
Checkout: https://github.com/pantharshit00/coc-prisma
Syntax: https://github.com/pantharshit00/vim-prisma

**Comment by dan003400** [comment]
Thanks @pantharshit00 but I actually have both of these already installed and they are working.

The reason I added this issue was due to the suggestion in other issues that my syntax should have shown errors, but I was not receiving any errors within my editor. The way I understand it is the editor will display errors from the typescript compiler, but in some cases there is no error in typescript but it is not properly formatted prisma client calls.

https://github.com/prisma/prisma/discussions/5929#discussioncomment-424410

What is different about these vim plugins and the vscode extension that is supposedly catching these errors without any typescript errors?

**Comment by pantharshit00** [comment]
The Prisma vscode extension only works on `.prisma` file, same as the vim extension. They use the same language server under the hood. 

In order to get typescript errors. in your extension, install typescript language server extension which would be `coc-tsserver` in this case.
