### ISSUE TITLE
Allow `findUnique` to just take an ID value

### ISSUE THREAD

**Issue by ldiqual** [prisma/prisma#5963]
## Problem

I believe that the following:

```
await prisma.users.findUnique({ where: { id: 1 } })
```

is very verbose for such a common operation.

## Suggested solution

Allow `findUnique` to take an ID:

```
await prisma.users.findUnique(1)
```

**Comment by valiknows** [comment]
It feels more natural with me dealing with prisma's  current functions like model.function(object) vs model.function(value)

**Comment by pantharshit00** [comment]
We can have a look but I personally I am against having multiple overloads for same things .

**Comment by jkomyno** [comment]
Hi, I'm closing this issue as adding this kind of overload would unfortunately introduce unnecessary complications on our side + possible confusion on the users' side. Thanks for understanding!
