### ISSUE TITLE
Prisma migrate CLI overrides the NODE_ENV env var and always sets it to production

### ISSUE THREAD

**Issue by sbalay** [prisma/prisma#5990]
## Bug description

I'm using prisma with a postgres database, and when connecting to it I set the schema according to the NODE_ENV variable. To do so, my `.env` file looks like this:

```
DATABASE_URL="postgresql://postgres:example@localhost:5432/postgres?schema=${NODE_ENV}"
```

The problem is, when running the cli command to create migrations, NODE_ENV is always set to `production` for some reason, despite me setting it before running the command:

```
$ npm run migrate-dev

> prisma-v2-getting-started@1.0.0 migrate-dev /Users/sebastianbalay/projects/prisma-v2-getting-started
> NODE_ENV=development prisma migrate dev --preview-feature

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "production" at "localhost:5432"
```

Note how schema is set to production in the logs above ☝️ 

## How to reproduce

The issue is easy to reproduce:

1. Set up the starter project as recommended in https://www.prisma.io/docs/getting-started/quickstart-typescript
```bash
curl -L https://pris.ly/quickstart | tar -xz --strip=2 quickstart-master/typescript/starter 
```
2. Change `.env` file with the following content:

```
DATABASE_URL="file:./${NODE_ENV}.db"
```

3. Run the migrate command setting `dev` as `NODE_ENV` to match the existing sqllite db file: `NODE_ENV=dev npx prisma migrate dev --preview-feature`

4. Note that prisma tries to create a new migration given that it didn't work against the `dev.db` file but tried to use `production.db` instead:

```bash
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "production.db" at "file:./production.db"

SQLite database production.db created at file:./production.db
```

## Expected behavior

Following the instructions above, prisma should have used `dev.db` as datasource when running the migration command

## Prisma information

Same as starter project

## Environment & setup

- OS: Mac OS
- Database: SQLite (but happens with any db)
- Node.js version: 14.15.4
- Prisma version:
```
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : darwin
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.356.0
```

**Comment by sbalay** [comment]
Personally, I don't think this issue is a big deal. I just changed the env variable name to `SERVER_ENV` or something like that. 

The real problem is the time that it takes to realise what is going on, and why things are not working as expected.

**Comment by janpio** [comment]
This _could_ be relevant: https://github.com/prisma/prisma/blob/e72fb11e9096241c0102204142f735f612dea76f/src/packages/cli/src/bin.ts#L31-L39

**Comment by pantharshit00** [comment]
> This could be relevant:

We don't use ink anymore so we don't depend on react so we can get rid of this imo.

**Comment by Jolg42** [comment]
Also agree that this code could go away since ink is not used in CLI
