### ISSUE TITLE
Add tests for platforms.ts

### ISSUE THREAD

**Issue by anishagg17** [prisma/prisma#5993]
## Problem

https://github.com/prisma/prisma/blob/master/src/packages/get-platform/src/platforms.ts lacks unit tests.

## Additional context

If this issue is approved, I would like to work upon this issue.

**Comment by Jolg42** [comment]
Indeed! You can create a PR, I'll be happy to review it 👍

**Comment by steebchen** [comment]
Some additional inspiration from the Go client tests: https://github.com/prisma/prisma-client-go/blob/master/binaries/platform/platform_test.go

**Comment by anishagg17** [comment]
Hi @steebchen thanks for sharing, my unit test file looks similar to this.

Is there any specific point/pattern that I have missed?

**Comment by Jolg42** [comment]
Note: it was a day off yesterday in Berlin 😃 

I think what @steebchen is pointing is about this code https://github.com/prisma/prisma/blob/6ac5151af1ab52a0efe39215dc8d7b154354d73e/src/packages/get-platform/src/getPlatform.ts#L70

**Comment by anishagg17** [comment]
@Jolg42 should this be also closed?

**Comment by Jolg42** [comment]
We can close this I think too, also `parseDistro` tests are here https://github.com/prisma/prisma/blob/07f23435b777ba54bd6c7b79ec7e198c3c7f435b/src/packages/get-platform/src/__tests__/parseDistro.test.ts maybe we could more cases.
