### ISSUE TITLE
Frequent Timed out fetching a new connection from the pool with v2.18.0

### ISSUE THREAD

**Issue by s-kris** [prisma/prisma#6014]
## Bug description

As discussed here: https://github.com/prisma/prisma/issues/5977#issuecomment-791637028

`Error: Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter (https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#connection-pool). Current limit: 3`

I migrated from 2.13.1 to 2.18.0 and since then, the connection limit errors are occurring during my dev very frequently - at least once per 'yarn dev', I have to restart the dev. It never happened in 2.13.1. Never. So, I'm temporarily downgrading until there's some clarity on this. Thank you.

## Note:
1. I use Nextjs 10.0.3
2. I'm using custom server because query time seemed higher in serverless approach. (I'll open a detailed issue on this soon).
3. I always instantiate prisma client as mentioned here: https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices#problem

## Code: 

```
const prisma = getPrismaInstance();

app.prepare().then(() => {
    createServer((req, res) => {
        const parsedUrl = parse(req.url!, true);
        req.prisma = prisma; // retrieve prisma object in the api routes via req object
        handle(req, res, parsedUrl);

    }).listen(port);

    console.log(
        `> Server listening at http://localhost:${port} as ${
            dev ? 'development' : process.env.NODE_ENV
        }`,
    );
});
```

## How to reproduce
1. Clone nextjs-custom-server: https://github.com/vercel/next.js/tree/canary/examples/custom-server
2. Initialise prisma as above
3. Write some queries 
4. Wait for the error

## Expected behavior
There shouldn't be freqent connection limit errors

## Environment & setup

- OS:  macOS Catalina 10.15.7
- Database:  Postgres
- Node.js version:  14.4.0
- Prisma version: 

```
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : darwin
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
```

**Comment by janpio** [comment]
There might be another error hiding behind the "connection pool" one. Can you disable the connection pool timeout by adding `pool_timeout=0` to your connection string or increase the timeout from the default of 5s by e.g. setting `pool_timeout=10` via the connection string and lets us know if this changes anything? Thanks.

**Comment by s-kris** [comment]
Hi @janpio by adding this error `pool_timeout=0` or `pool_timeout=30` this error didn't happen for whatever amount of time I tested.

**Comment by s-kris** [comment]
Nope. No errors :)

**Comment by janpio** [comment]
Awesome, so this was just an overlap in error messages leading to confusing output.
If you encounter any error messages again, please let us know by opening a new issue 👍
