### ISSUE TITLE
Do not use console.error to show query log of Prisma Client

### ISSUE THREAD

**Issue by peteralbert** [prisma/prisma#6019]
## Bug description

When running a query with Prisma client using `log: ['query']`, the SQL query is shown using `console.error`. As this is actually not an error, the output is confusing and somewhat misleading, as the console.error statement comes in red and with a stack trace.

I know it is first and foremost my own stupidity for not recognizing it in the first place, but I just spend multiple hours trying to debug the alleged error until I realized my blunder! So showing it differently will probably save other developers from falling into the same trap!

I would suggest to map Prisma's log levels to console, i.e.:

- `error` -> `console.error`
- `warn` -> `console.warn`
- `info` -> `console.info`
- `query` -> `console.log` or `console.info`

## Environment & setup

- OS: Win
- Database: MS SQL Server 2019
- Node.js version: v14.15.1
- Prisma version: 

```
prisma               : 2.18.0 (also for 2.17 and 2.16)
@prisma/client       : 2.18.0
Current platform     : windows
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.356.0
```

**Comment by pantharshit00** [comment]
I think we just changed it to use `console.log` cc @williamluke4 so this should be fixed in the next release.

**Comment by pantharshit00** [comment]
Closing as this was already resolved.
