### ISSUE TITLE
Enum description

### ISSUE THREAD

**Issue by vidz1979** [prisma/prisma#6033]
It would be nice if Prisma enum declaration could hold a description to be exported to client apps.

```
enum InventoryStatus {
  OPEN
  LOCKED
  CANCELLED
}
```

```
query {
  __type(name: "InventoryStatus") {
    name
    enumValues {
      name
      description
    }
  }
}
```

```
{
  "data": {
    "__type": {
      "name": "InventoryStatus",
      "enumValues": [
        {
          "name": "OPEN",
          "description": null
        },
        {
          "name": "LOCKED",
          "description": null
        },
        {
          "name": "CANCELLED",
          "description": null
        }
      ]
    }
  }
}
```

**Comment by janpio** [comment]
We haven't had any additional requests for this in the last 3 years, so it is safe to say that this is not the most pressing need. As we have hundreds of issues where we do get constant feedback and upvotes, it is not realistic for us to prioritize this one any time soon, sorry. 

I am closing this issue for now. If someone has a dire need for this, please comment below or open a new feature request. Thank you.
