### ISSUE TITLE
Introspection does not recognize Default Expressions

### ISSUE THREAD

**Issue by mnengwa** [prisma/prisma#6035]
Hi, I usually start by developing my database model on the Mysql workbench. However, Prisma's introspection would not respect some of my SQL commands/statements. I am aware building a full-featured ORM is not a small task/feat. Please see to this issue as it fails to meet what I would expect.

## Bug description
The introspection feature should reverse engineer what it is given when using an existing database

## How to reproduce
1. Install MySQL 8 on Windows 10
2. Install MySQL workbench
2. Create a database 
3. Create a table using this SQL statement on the previous database
```sql
CREATE TABLE `account` (
    `id` BINARY(16) NOT NULL DEFAULT(UUID_TO_BIN(UUID(), 1)),
    `name` VARCHAR(255) NOT NULL,
    `MSISDN` VARCHAR(15) NOT NULL,
    `email_address` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE INDEX `account.name_unique`(`name`),
UNIQUE INDEX `account.MSISDN_unique`(`MSISDN`),
UNIQUE INDEX `account.email_address_unique`(`email_address`),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```
4. Install prisma & prisma client
5. Setup up the database credentials on .env
6. Run ```npx prisma introspect```
7. Run ``` npx prisma migrate dev --name init --preview-feature```

## Expected behavior
I would expect the introsception feature to reproduce the schema below:
```sql
CREATE TABLE `account` (
    `id` BINARY(16) NOT NULL DEFAULT(UUID_TO_BIN(UUID(), 1)),
    `name` VARCHAR(255) NOT NULL,
    `MSISDN` VARCHAR(15) NOT NULL,
    `email_address` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE INDEX `account.name_unique`(`name`),
UNIQUE INDEX `account.MSISDN_unique`(`MSISDN`),
UNIQUE INDEX `account.email_address_unique`(`email_address`),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

However, this is the SQL that gets generated. When I create a migration after the introspection.
```sql
-- CreateTable
CREATE TABLE `account` (
    `id` BINARY(16) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `MSISDN` VARCHAR(15) NOT NULL,
    `email_address` VARCHAR(255) NOT NULL,
    `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` DATETIME(0) DEFAULT CURRENT_TIMESTAMP(0),
UNIQUE INDEX `account.name_unique`(`name`),
UNIQUE INDEX `account.MSISDN_unique`(`MSISDN`),
UNIQUE INDEX `account.email_address_unique`(`email_address`),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

## Prisma information
```package.json```

```JSON
 "dependencies": {
    "@prisma/client": "^2.18.0",
    "apollo-server": "^2.21.0",
    "eslint": "^7.21.0",
    "graphql": "^15.5.0"
  },
  "devDependencies": {
    "prisma": "^2.18.0"
  }
```

## Environment & setup

- OS: Windows 10
- Database: MySQL 8.0.23
- Node.js version: v14.15.4
- Prisma version:
```
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : windows
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules\@prisma\engines\migration-engine-windows.exe)  
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.356.0
```

**Comment by janpio** [comment]
Can you share the `schema.prisma` file that is created by `prisma introspect` on your database?
The most important difference seems to be the missing default in the `id`, `DEFAULT(UUID_TO_BIN(UUID(), 1))`, correct?

**Comment by do4gr** [comment]
Hi, 

thanks for reporting this! I looked into the issue, and the problem is that the default on the id column is an expression. Prisma introspect uses the information_schema tables to gather information about the database and unfortunately default expressions are not represented in there with all the necessary information. At some point we might start to extract that information from `Show Create Table` but this is not currently planned since that would require us to add SQL DDL parsing. 
So on the introspection side I'm afraid we won't support that in the near future. 

On the migrate side you can manually add `@default(dbgenerated("(UUID_TO_BIN(UUID(), 1))"))` to the id column, then Prisma Migrate should correctly create the expression default value for you in the database.

**Comment by do4gr** [comment]
Related issue https://github.com/prisma/prisma/issues/2600

**Comment by tomhoule** [comment]
https://github.com/prisma/prisma-engines/pull/1743 could be relevant (see also the other issue)

**Comment by mnengwa** [comment]
Hi, I have seen that actually, the support for MySQL expressions has improved. Nice job, But there's a bit of odd behaviour, still on the part of using an expression as a default value. It first creates the column without the default value and on the subsequent migration, it alters the same column to the right "description". Oddly it's when the datatype is set to BINARY(16).

`schema.prisma`
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Bytes  @id @default(dbgenerated("(UUID_TO_BIN(UUID(), 1))")) @db.Binary(16)
  name  String @db.VarChar(255)
  phone String @unique @db.VarChar(15)
  email String @unique @db.VarChar(255)
}

model Person {
  id    String @id @default(dbgenerated("(UUID())"))
  name  String @db.VarChar(255)
  phone String @unique @db.VarChar(15)
  email String @unique @db.VarChar(255)
}

model Human {
  id    Bytes  @id @default(dbgenerated("(UUID_TO_BIN(UUID(), 1))")) @db.Binary(16)
  name  String @db.VarChar(255)
  phone String @unique @db.VarChar(15)
  email String @unique @db.VarChar(255)
}

model Thing {
  id    Bytes  @id @default(dbgenerated("(UUID_TO_BIN(UUID(), 1))")) @db.Binary(16)
  name  String @db.VarChar(255)
  phone String @unique @db.VarChar(15)
  email String @unique @db.VarChar(255)
}

```

1. migration created for the User model
```
-- CreateTable
CREATE TABLE `User` (
    `id` BINARY(16) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(15) NOT NULL,
    `email` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `User.phone_unique`(`phone`),
    UNIQUE INDEX `User.email_unique`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

```

2. Migration created for the Person model
```
-- AlterTable
ALTER TABLE `User` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), 1));

-- CreateTable
CREATE TABLE `Person` (
    `id` VARCHAR(191) NOT NULL DEFAULT (UUID()),
    `name` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(15) NOT NULL,
    `email` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `Person.phone_unique`(`phone`),
    UNIQUE INDEX `Person.email_unique`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

```

3. Migration created for the Human model
```
-- AlterTable
ALTER TABLE `User` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), 1));

-- CreateTable
CREATE TABLE `Human` (
    `id` BINARY(16) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(15) NOT NULL,
    `email` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `Human.phone_unique`(`phone`),
    UNIQUE INDEX `Human.email_unique`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

```

4. Migration created for the Thing model
```
-- AlterTable
ALTER TABLE `Human` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), 1));

-- AlterTable
ALTER TABLE `User` MODIFY `id` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), 1));

-- CreateTable
CREATE TABLE `Thing` (
    `id` BINARY(16) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(15) NOT NULL,
    `email` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `Thing.phone_unique`(`phone`),
    UNIQUE INDEX `Thing.email_unique`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

```

**Comment by mnengwa** [comment]
Hi,
Hope you are doing well. Good to hear from you, I have seen the progress on
the matter. I have added an observation as a comment on the same issue. You
can look at it here:
https://github.com/prisma/prisma/issues/6035#issuecomment-881732136

**Comment by janpio** [comment]
Optimally open a new issue, this could be a bug that we should look into. Thanks.

**Comment by mnengwa** [comment]
> Optimally open a new issue, this could be a bug that we should look into. Thanks.

I have opened a new [issue](https://github.com/prisma/prisma/issues/8328)
