### ISSUE TITLE
error report id: 13104

### ISSUE THREAD

**Issue by tsdexter** [prisma/prisma#6040]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`introspect`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v12.16.1           | 
| Prisma CLI  | 2.18.0             | 
| Binary      | da6fafb57b24e0b61ca20960c64e2d41f9e8cff1| 

## Error
```
Error: [libs/sql-schema-describer/src/getters.rs:21:14] called `Result::unwrap()` on an `Err` value: "Getting view_sql from Resultrow ResultRow { columns: [\"view_name\", \"view_sql\"], values: [Text(Some(\"wp_fulltext_search\")), Text(None)] } as String failed"
```

**Comment by tomhoule** [comment]
Thanks for reporting this! We will fix it soon.
