### ISSUE TITLE
Cannot read property 'collectErrors' of null

### ISSUE THREAD

**Issue by oceandrama** [prisma/prisma#6052]
## Bug description

There is a regression or a breaking change: if you pass `null` in `findMany` method, it falls with error `Cannot read property 'collectErrors' of null`

## How to reproduce

Create any schema, for example with model `User`
Try to call next code
```
prisma.user.findMany({where: {AND: [null, {}]}})
```

## Expected behavior

All users are returned like it was in `2.17.0`, if this is a regression. Or correct error is shown, if this is a breaking change

## Environment & setup

- OS: Windows
- Database: Postgres
- Node.js version: 14.15.4
- Prisma version: 2.18.0

**Comment by pantharshit00** [comment]
The error is reproducible but we disallow this in TS typings. We should define the behavior and fix the crash.
