### ISSUE TITLE
`prisma migrate deploy` sometimes errors with `Database error: Error querying the database: db error: ERROR: prepared statement "s0" does not exist` with pgbouncer

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#6053]
## Bug description

https://prisma.slack.com/archives/CA491RJH0/p1615370492400800?thread_ts=1614161039.079900&cid=CA491RJH0 
User says:
Funny things is that when i redeploy once or twice it works :man-shrugging: always running the same `NODE_ENV=production blitz prisma migrate deploy --preview-feature` - prisma & prisma-client are at 2.18.0 I just tested prisma for a few weeks so i only tested 2.17 - 2.18
Db is hosted on digital-ocean(london 1) with pgBouncer enabled.

Actually it seems to be two errors - in most cases it’s just
```
21:35:05.746  	Error: P1002
21:35:05.746  	The database server at `xx.xxx.xx.xxx`:`25061` was reached but timed out.
```

But at least once it also was:
```
Response: Database error: Error querying the database: db error: ERROR: prepared statement "s0" does not exist
```

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```

```

**Comment by Jolg42** [comment]
Note: The error message looks similar in this issue from client side  https://github.com/prisma/prisma/issues/4752

**Comment by tomhoule** [comment]
I think we would need help from the user to debug this — we explicitly disable prepared statement caching in the migration engine to avoid this scenario. We also haven't seen it happen anywhere before (no report of this).

**Comment by Jolg42** [comment]
This error is not well identified at the moment, we'll need to get to a reproduction, any help will be appreciated here!

**Comment by sakulstra** [comment]
Hello, i'm the user who originally reported this on slack and stepped over this: https://prisma.slack.com/archives/CA491RJH0/p1615542278459300?thread_ts=1615542036.459200&cid=CA491RJH0
> Dont run the migration through the bouncer. Run the migration directly through the database url.

I can't verify it that's a solid fix as i'm no longer using prisma in production, but i did a few test deployments of the old codebase and non of them failed, so this might have been the cause for the first issue.

**Comment by Jolg42** [comment]
Indeed! Thanks! I think we can close then since a reproduction would be needed to go further.
