### ISSUE TITLE
duplicate property names in models can be generated

### ISSUE THREAD

**Issue by btodorce** [prisma/prisma#6062]
## Bug description

Multiple database field names at  with the same name can lead to models with identical property names to be generated if they contain an underscore _ or a number as the foremost letter in the field name

## How to reproduce

1. create database table with id and _id fields OR
2. create database table with fields 60_rate, 95_rate, 100_rate
2. run introspect 
3. run prisma generate
4. prisma generate would fail

## Expected behavior

duplicate property names should not be generated 

## Environment & setup

- OS: Windows
- Database: mariadb
- Node.js version: 14.5.4
- Prisma version:2.17.0

**Comment by janpio** [comment]
Are you not getting a validation error with that schema on generation?
What happens when you run `prisma validate` explicitly?

**Comment by btodorce** [comment]
The schema at x\schema.prisma is valid �

**Comment by btodorce** [comment]
Error: Schema parsing
error: Field "x" is already defined on model "x".

**Comment by janpio** [comment]
That is fundamentally expected and be pointed out in the schema, and then be surfaced via the validation error. As far as I know we used to have the validation error on `prisma generate` as well - seems that got lost somehow. Can you confirm that?

**Comment by Jolg42** [comment]
Potential regression to confirm ⬆️

**Comment by matthewmueller** [comment]
This is actually for introspection to add a @map to these fields

- create database table with id and _id fields OR
- create database table with fields 60_rate, 95_rate, 100_rate

Prisma generate is based off the schema.

**Comment by janpio** [comment]
Actually: Introspection should already have logic to detect the naming problem of `_id` and notice that somehow (warning, commenting out field or similar.) This needs to be confirmed, as it should effectively make this bug impossible.

**Comment by pantharshit00** [comment]
Related: https://github.com/prisma/prisma/issues/6680

**Comment by janpio** [comment]
Nothing in this issue really makes sense and fits together.

Is this still a problem @btodorce? If so, please open a new issue. Thanks.
