### ISSUE TITLE
Migration error when trying to add some enum members

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#6073]
## Bug description

Attempting to migrate with this change:

<img width="1349" alt="Screen Shot 2021-03-11 at 9 25 55 PM" src="https://user-images.githubusercontent.com/284476/110883253-29f9ef80-82b1-11eb-8593-af519aec9241.png">

Getting this error:

![image](https://user-images.githubusercontent.com/284476/110883303-426a0a00-82b1-11eb-87fd-2ca1315c9d00.png)

## How to reproduce

Not sure

## Expected behavior

I can migrate additions to an enum

## Prisma information

2.18

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```

```

**Comment by tomhoule** [comment]
I think you added multiple values to an enum in one migration on postgres. There should be a comment in your migration file explaining that this is not possible with raw SQL migrations, and how to work around it. If the comment is not there, it's a bug. Can you confirm?

**Comment by jasonkuhrt** [comment]
Will look!

**Comment by jasonkuhrt** [comment]
![image](https://user-images.githubusercontent.com/284476/110950541-f8654080-8311-11eb-8bb5-404f028cf3b2.png)

Confirmed!

**Comment by tomhoule** [comment]
We'll look into it in planning next week to see if we can make the warning more visible in the CLI. Thanks for the feedback :)

**Comment by tomhoule** [comment]
Decision: we'll make it more visible through the CLI.

**Comment by floelhoeffel** [comment]
We now have a warning in place.

**Comment by jasonkuhrt** [comment]
@floelhoeffel Not sure I follow. There is already a warning in the SQL? So what's needed was something like a warning exposed through CLI feedback?

**Comment by tomhoule** [comment]
Yep, my understanding is that we had a warning in the SQL migration before the issue was opened, and we thought about adding it to the CLI output to make it even more visible, but never got to it. Now we probably want to revisit the CLI output as part of the migrate DX initiative, so it may make sense to revisit in that context.

**Comment by tomhoule** [comment]
https://github.com/prisma/migrations-team/issues/327
