### ISSUE TITLE
Add runtime test(s) for useUds (unix domain sockets) in client

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#6088]
## Problem

We need to add a test with 
```
const prisma = new PrismaClient({
  __internal: {
    useUds: true
  }
} as any); // remove as any if you are using js
```

uds is off by default but still used by some people when they have problems with default approach.

**Comment by toshi1127** [comment]
I would like to tackle this issue.

**Comment by Jolg42** [comment]
Hi @toshi1127 
I only saw your message today.

Let me know if you are still interested.

What you could do is copy this folder
https://github.com/prisma/prisma/tree/a949fdb477c1f3b8431c4064bc8ea89b4648ea02/src/packages/client/src/__tests__/integration/happy/blog

maybe name it `uds` and make it more minimalist with PrismaClient instance like 
```ts
const prisma = new PrismaClient({
  __internal: {
    useUds: true
  }
} as any);
```

**Comment by paularah** [comment]
Hi @Jolg42
I opened a PR for this.

**Comment by Jolg42** [comment]
@paularah Thanks for the PR! 💚 I checked it out, it looks good! Just wanted to have Will's review before merging!

**Comment by pantharshit00** [comment]
Looks like PR is merged so I am closing this.
