### ISSUE TITLE
nx angular project can't compile prisma auto generated types

### ISSUE THREAD

**Issue by SirBr4him** [prisma/prisma#6100]
## Bug description

when I import prisma generated types in my angular project it doesn't compile properly, I get this error:

Error: node_modules/.prisma/client/index.d.ts:11:117 - error TS1005: '(' expected.

11   [K in keyof Tuple]: K extends `${number}` ? Tuple[K] extends PrismaPromise<infer X> ? X : UnwrapPromise<Tuple[K]> : UnwrapPromise<Tuple[K]>

 i'm using version:
prisma: 2.18.0
@angular/cli: 11.0.0
@nrwl/cli: 11.5.1
eslint: 7.10.0

basicly i use the default configurations generated by nx cli for .eslintrc.json and tsconfig.json.

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```

```

**Comment by kraglalbert** [comment]
I believe the version of Prisma that you have requires at least TypeScript version `4.1.5`, so you could try updating that in your `package.json`. I had the same (or very similar) issue and that fixed it for me!

**Comment by SirBr4him** [comment]
I was using typescript version 4.0.3 because the nx cli generated the project with that version.
Updating typescript to version 4.1.5 resolved the issue.
Thank you @kraglalbert.

**Comment by janpio** [comment]
Next release of Prisma will provide a runtime check for the required Typescript version to surface this to you - sorry we only added this recently.
