### ISSUE TITLE
Explicit self referenced many-to-many relationships

### ISSUE THREAD

**Issue by TheRealThor** [prisma/prisma#6111]
Hello guys,

that's an impressive work you guys have done. I am coming from a PHP/Laravel background, where SQL is as well abstracted with the famous[ Eloquent Relationships](https://laravel.com/docs/8.x/eloquent-relationships) of that framework. 
I am thinking of switching to nodejs with  Prisma.  However when I was playing with the Prisma Schema I stumbled on an issue.  Per the documentation implicit relationships are possible with the following notation

```
model User {
  id          Int      @id @default(autoincrement())
  name        String?
  followedBy  User[]   @relation("UserFollows", references: [id])
  following   User[]   @relation("UserFollows", references: [id])
}
```

I din't find a way to change that to an **explicit relationship** where I can add columns/fields to describe that relationship further. I tried to define an extra model to represent a relation table:

```
 model User {
  id          Int      @id @default(autoincrement())
  name        String?
  followedBy  UserOnUser[]   
  following   UserOnUser[]   
}

model UserOnUser {
    child   User @relation(fields: [childId], references: [id])
    childId Int

    parent   User @relation(fields: [parentId], references: [id])
    parentId Int

   following_type  String

   @@id([childId, parentId])

}
```

But this did not work  and I got the following errors: 

```
Error validating model "User": Ambiguous relation detected. The fields `children` and `parents` in model `Person` both refer to `PersonOnPerson`. Please provide different relation names for them by adding `@relation(<name>).

Error validating model "UserOnUser": Ambiguous relation detected. The fields `child` and `parent` in model `PersonOnPerson` both refer to `Person`. Please provide different relation names for them by adding `@relation(<name>).
```

Is it possible to define explicit self referenced many-to-many relationships with Prisma (yet)?

_Originally posted by @TheRealThor in https://github.com/prisma/prisma/discussions/6104_

**Comment by do4gr** [comment]
Hey, I think what you're trying will work, you just need to name the relations. You will however have to traverse the intermediate table when using the client to go from User -> UserOnUser -> User. With the implicit syntax this is abstracted away, but as you know you can then not have extra fields on the intermediate table.

```
 model User {
  id          Int      @id @default(autoincrement())
  name        String?
  followedBy  UserOnUser[]   @relation("FollowedBy")
  following   UserOnUser[]    @relation("Following")
}

model UserOnUser {
    child   User @relation("FollowedBy",  fields: [childId], references: [id])
    childId Int

    parent   User @relation("Following", fields: [parentId], references: [id])
    parentId Int

   following_type  String

   @@id([childId, parentId])

}
```

**Comment by TheRealThor** [comment]
Hello Matthias,

thanks for the tip with naming the relations. It did produce the exact correct migrations tables. 
I thought initially naming the relations will put the relation in a different table with that name.
