### ISSUE TITLE
Case sensitivity issue on Mysql during Introspection

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#6117]
If you have very similar names for tables / columns in your db all MySQL versions except MySQL 8 can produce wrong introspection results. Sample schema: 

```
model ADDRESS {
   ADDRESSID Int @id
}
          
model Address {
  AddressID Int @id @default(autoincrement())
}
            
model address {
  addressid Int @id
}
```

**Comment by janpio** [comment]
This also causes the order of the models in the generated schema file to be random and changing with each time you run Introspection.
