### ISSUE TITLE
Add test for `findMany count selection` feature flag `selectRelationCount`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#6119]
## Problem

Related https://github.com/prisma/prisma-engines/pull/1734

This feature is gated with flag `selectRelationCount` and tested in engines but could use a test here too.

**Comment by williamluke4** [comment]
@timsuchanek Added tests for this here
- [integration/happy](https://github.com/prisma/prisma/blob/master/src/packages/client/src/__tests__/integration/happy/selectRelationCount/test.ts)
- [types](https://github.com/prisma/prisma/blob/master/src/packages/client/src/__tests__/types/selectRelationCount/test.ts)
