### ISSUE TITLE
Watch mode for Introspection

### ISSUE THREAD

**Issue by omar-dulaimi** [prisma/prisma#6126]
## Problem

Hello,
While using the introspection workflow, It's possible that sometimes one might forget to run prisma introspect after changes have been done on the database schema.
## Suggested solution

So what we were thinking is if it was possible to run introspection in watch mode; so that prisma could re-introspect on database schema changes.

## Alternatives

The alternative is to count on the human memory to re-introspect after every database change.

**Comment by Jolg42** [comment]
So to understand your workflow:
- You modify the database directly (with a GUI or command line tool maybe?)
- You introspect to update the schema
- You repeat until you are satisfied (when the feature is done?)

Is that your ideal workflow or could you consider using Prisma Migrate maybe? (it's now Generally Available, ready for production since 2.19)?

**Comment by omar-dulaimi** [comment]
Yeah that is the workflow that we intend on following for the next couple of months. We're considering migrate, But I don't think we're going to use it this early although it has hit GA.

**Comment by Jolg42** [comment]
@omar-dulaimi What's blocking you to use Migrate now? Curious to see if I can help 😃

**Comment by janpio** [comment]
@omar-dulaimi The problem about having a watch mode for Introspection is that there is nothing that our CLI can "watch" to trigger a new run of Introspection. The only thing that changes when you update the database schema via an external tool is the _content_ of the schema - and to learn about that change we need to actually run Introspection already. 

So the only "watch" we could build is to run Introspection automatically every second or so - and that is not really watching anything. You can probably do that yourself with a small bash script: https://www.cyberciti.biz/faq/bash-infinite-loop/ Would that satisfy your use case?

**Comment by omar-dulaimi** [comment]
@janpio I'm not sure about the shell script really. I was thinking if it was possible for prisma to listen for the binrary logs and run introspection accordingly. Binary logs are used a lot in migration tools, so it should be possible with prisma.

**Comment by omar-dulaimi** [comment]
@Jolg42 To be honest we want to give migrate a couple of months until it finally stabilizes, matures from extensive community usage + promoting push and pull to GA as well. So until then, we're going to stick to introspection.

**Comment by Jolg42** [comment]
@omar-dulaimi using `watch` command seems like a good workaround maybe?
https://unix.stackexchange.com/a/10650/67990

Like this, it will repeat the command every 20 seconds until turned off
```
watch -n20 -x npx prisma -v
```

**Comment by omar-dulaimi** [comment]
@Jolg42 Yeah that should work fine for now. Thank you.
