### ISSUE TITLE
rejectOnNotFound configuration parameter to apply for other functions that have the "where" property

### ISSUE THREAD

**Issue by carlos-moreira** [prisma/prisma#6129]
I'd like to know if there are plans to make the [rejectOnNotFound](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#rejectonnotfound) configuration parameter to apply for other functions that have the "where" property, like: update, delete, etc. Today it only applies for [findUnique](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference/#findunique) and [findFirst](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference/#findfirst).

To capture the error, for example for the update function, I'm doing this:

```
//...
catch (e) {
    if(e?.meta?.cause === "Record to update not found.") {
        //...error treatment
    }
}
```

What is not ideal because it might change with future updates of Prisma.

P.S.: I'm not trying to do an upsert operation, instead a plain update operation that would throw an error if the record is not found.

I had to do worst on the case of the delete function:

```
//...
catch (e) {
    if(typeof e?.message === "string" && e.message.includes("Record to delete does not exist.")) {
        //...error treatment
    }
}
```

**Comment by janpio** [comment]
`rejectOnNotFound` has actually be removed from our API completely, and we now have standalone methods for these use cases: https://www.prisma.io/docs/orm/reference/prisma-client-reference#rejectonnotfound

I am confident to say that we will _not_ add it to other methods. 
If you think similar methods should be added for other API methods, please open a new issue. 
Thank you.
