### ISSUE TITLE
Introspection failed: Getting definition from Resultrow ResultRow { columns: [\"name\", \"definition\"], values: [Text(Some(\"sp_helpdiagrams\")), Text(None)] } as String failed

### ISSUE THREAD

**Issue by androsj** [prisma/prisma#6134]
Hi! I was facing a similar issue to https://github.com/prisma/prisma/issues/6040
The fix was released today in 2.19.0, but I'm now experiencing a different error while introspecting (db pull).

I selected both the 'submit error report' and 'create Github issue' options from the CLI, but I couldn't find it so I'm creating this one... excuse me if it's duplicated.

error report id: 13132

## Bug description
This is the full error log using the DEBUG env variable:

``` 
prisma:introspectionEngine:stderr {"is_panic":true,"message":"[libs\\sql-schema-describer\\src\\getters.rs:21:14] called `Result::unwrap()` on an `Err` value: \"Getting definition from Resultrow ResultRow { columns: [\\\"name\\\", \\\"definition\\\"], values: [Text(Some(\\\"sp_helpdiagrams\\\")), Text(None)] } as String failed\"","backtrace":"   0: <unknown>\n   1: <unknown>\n   2: <unknown>\n   3: <unknown>\n   4: <unknown>\n   5: <unknown>\n   
6: <unknown>\n   7: <unknown>\n   8: <unknown>\n   9: <unknown>\n  10: <unknown>\n  11: <unknown>\n  12: <unknown>\n  13: <unknown>\n  14: <unknown>\n  15: <unknown>\n  16: <unknown>\n  17: <unknown>\n  18: <unknown>\n  19: <unknown>\n  20: <unknown>\n  21: <unknown>\n  22: <unknown>\n  23: <unknown>\n  24: <unknown>\n  25: <unknown>\n  26: <unknown>\n  27: <unknown>\n  28: <unknown>\n  29: <unknown>\n  30: BaseThreadInitThunk\n  31: RtlUserThreadStart\n"}
```

## How to reproduce

Run `prisma db pull`

## Expected behavior

Expected prisma schema to update from target db.

## Environment & setup

- OS: Windows
- Database: SQL Server
- Node.js version: 14.6.0
- Prisma version: 2.19.0

**Comment by tomhoule** [comment]
Thanks for reporting! We'll look into this

**Comment by janpio** [comment]
Same installation reported 13125 and 13126 with 2.18.0, which was the same error as https://github.com/prisma/prisma/issues/6040 - might be a follow up of that change in theory.
