### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Closed, cause: None } when using Prisma with NestJS in Google Cloud Run

### ISSUE THREAD

**Issue by sporkspatula** [prisma/prisma#6139]
## Bug description

Running a nest-js application in google cloud run. It leverages prisma `2.18.0`. On cold start we routinely see this error:
`Error in PostgreSQL connection: Error { kind: Closed, cause: None }` .

## Expected behavior

We expect the prisma client to connect and disconnect to the database onModuleInit and onModuleDestroy as defined in our prisma service. See: 

```
import {
  Injectable,
  Logger,
  OnApplicationShutdown,
  OnModuleDestroy,
  OnModuleInit,
} from '@nestjs/common';
import { PrismaClient } from 'generated/client';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class PrismaService
  extends PrismaClient
  implements OnModuleInit, OnApplicationShutdown {
  logger: Logger = new Logger(PrismaService.name);

  constructor(configService: ConfigService) {
    super({
      ...(configService.get('STAGE') !== 'local' && {
        datasources: {
          db: {
            url: configService.get('GCP_DATABSE_URL'),
          },
        },
      }),
    });
  }

  async onModuleInit() {
    this.logger.log('Attempting to spin up a new prisma connection');
    await this.$connect();
    this.logger.log('Successfully made a prisma connection');
  }

  async onApplicationShutdown() {
    this.logger.log('Attempting to disconnect the current prisma connection');
    await this.$disconnect();
    this.logger.log('Successfully disconnected the prisma connection');
  }
}
```

## Environment & setup

- OS: Linux
- Database: PostgreSQL
- Node.js version: 
- Prisma version: 2.18.0

Has anyone seen this / have any idea what might be going on?

**Comment by janpio** [comment]
What exactly do we need to do to be able to reproduce this with the code above?

**Comment by Ezard** [comment]
@janpio I've just seen the same thing happen for me today, also using PostgreSQL on Google Cloud with Nest.js. However, we're using Google Kubernetes Engine and not Cloud Run

Our containers had been running for ~1hr when this happened. Everything was working as expected before this occurred, and then after seeing this error repeatedly for ~1m, everything resumed working as expected (including the exact same database queries that the errors occurred on)

This is the first time that we've seen this in our several months of using Prisma

There were no database operations (e.g. upgrades, backups, etc) being run at the time that the error occurred

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.19.0             |
| Query Engine    | query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|
| Database        | undefined|

Happy to put this into a separate issue if you want, but figured it might be related to this one

**Comment by janpio** [comment]
Open a new issue pls but link to this one - this could very well have the underlying cause - but also not. We will try to investigate. If you can give us any pointers what might have been happening we would be more than thankful @Ezard.

**Comment by narciero** [comment]
fwiw, I have also started seeing a large number of these errors popup randomly on Google Cloud Run, they started after updating to 2.18.0 (from 2.17.0) and are still occurring on 2.19.0. I am using Prisma with `nexus` and these errors happen regardless of cold-starts.

Unfortunately i'm not sure how to reproduce other than running a service in GCR and just waiting for it to happen. It happens randomly on both reads + writes.

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | linux-musl         |
| Prisma Client   | 2.19.0             |
| Query Engine    | query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|
| Database        | undefined|

**Comment by janpio** [comment]
Information about the PR that closed this:
https://github.com/prisma/prisma/issues/6329#issuecomment-815012006

Feel free to reply here again if the problem is not solved/better for you and we can reopen the issue of course.
