### ISSUE TITLE
Improve constraint/index name mapping by supporting explicit names

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#6143]
## Problem

* When index and constraint names don't match the defaults used by Prisma, unnecessary migrations are generated to drop and re-create them
* When introspecting an existing database with non-default constraint/index names to initialize a new migration history (brown-field scenario), migrations are generated based on the local names and will fail on the production database
* Inconsistent ability to name constraint and index names

## Solution

Iterate constraint index naming capabilities exposed in PSL

**Comment by do4gr** [comment]
This is now available via the `namedConstraints` preview flag since 2.29. See https://www.prisma.io/docs/guides/upgrade-guides/upgrading-to-use-preview-features/enabling-named-constraints
