### ISSUE TITLE
One to one relation not working - opposite field complaint

### ISSUE THREAD

**Issue by noire-munich** [prisma/prisma#6147]
## Bug description

I'm modelling a User with roles such as 'student', 'customer'.
A student can be tied to one customer in a "tutoring" ( mentoring? ) relationship.
A customer can tutor several students.

This is my model:
```
model User {
  id            Int @id @default(autoincrement())
/** irrelevant fields... */
  roles         Role[]
  tutorId       Int?
  tutor         User? @relation(name: "StudentCustomer", fields: tutorId, references: id)
  // students      User[] @relation("CustomerStudent", references: [id]) // buggy so commented out.
}
```

This is the error message I get any time I run a migration:

```
Error: Schema parsing
error: Error validating field `tutor` in model `User`: The relation field `tutor` on Model `User` is missing an opposite relation field on the model `User`. Either run `prisma format` or add it manually.
  -->  schema.prisma:148
   | 
147 |   tutorId       Int?
148 |   tutor         User? @relation(name: "StudentCustomer", fields: tutorId, references: id)
149 |   // students      User[] @relation("CustomerStudent", references: [id])
   | 
```

## Expected behavior

A no error migration? I've tried naming/not naming the relation, having the fields and references in and out array, having tutorId after/before tutor, none works.
I've also tried the documentation's example:

```
  successorId Int?
  successor   User?   @relation("BlogOwnerHistory", fields: [successorId], references: [id])
```

This is not working either.

Ultimately I need to be able to store multiple self relation to the User model.

## Environment & setup
```
Prisma 2.17
RedwoodJS v0.27
nvm 14.0.0
```

**Comment by njilrem** [comment]
You missed the third needed field which is in case of documentation is
````javascript
model User {
  id             Int     @default(autoincrement()) @id
  successorId Int?
  successor   User?   @relation("BlogOwnerHistory", fields: [successorId], references: [id])
  predecessor User?   @relation("BlogOwnerHistory")
}
````

**Comment by noire-munich** [comment]
@njilrem thanks for the answer.
I'm not sure I follow, `predecessor` is necessary in the case of the documentation but how is it relevant in my use case? Does it mean that named relations would require a third field, only identified as a part of the relation through `@relation("name")` ?

**Comment by noire-munich** [comment]
Ok, got it now, fixed.

**Comment by leanbkhcm** [comment]
> Ok, got it now, fixed.

how to fix, Can you please share your code? thanks

**Comment by noire-munich** [comment]
@leanbkhcm  can't recall if that was enough, but this is the bit that's related to this issue in my current code and it's since been working with it:

```
model User {
  # ... some fields
  tutorId       Int?
  tutor         User? @relation("CustomerStudents", fields: tutorId, references: id)
  # ... some other fields
}
```

If it can help.

**Comment by janpio** [comment]
Please open a new issue @RafaelCss - this issue is closed.

**Comment by dsz411** [comment]
References should exist on both sides, this code that I wrote:

`model User {
  id String @id @default(auto()) @map("_id") @db.ObjectId
  email String
  name String?
  username String @unique
  password String
  profileImage String?

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  **refreshToken RefreshToken[]**
}

model RefreshToken {
  id String @id @default(auto()) @map("_id") @db.ObjectId
  token String @unique

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  userId String @db.ObjectId
  **user User @relation(fields: [userId], references: [id])**
}`
