### ISSUE TITLE
Migrations that update index field types will drop the index and not recreate

### ISSUE THREAD

**Issue by garth** [prisma/prisma#6149]
## Bug description

Changing the types of fields that are part of an index will implicitly drop the index but not recreate it.

## How to reproduce

Step 1: create a model with an index.

```prisma
model Event {
  id              Int      @id @default(autoincrement())
  aggregateType   String?
  aggregateId     String?
  @@index([aggregateType, aggregateId])
}
```

Step 2: create and apply a migration

Step 3: update the model by changing one of the types used in the index

```prisma
model Event {
  id              Int      @id @default(autoincrement())
  aggregateType   String?
  aggregateId     Int?
  @@index([aggregateType, aggregateId])
}
```

Step 3: create and apply a new migration.  Notice that the migration drops and recreates the changed column. Implicitly the index will also be dropped. So after applying the migration the index is missing.

```sql
-- AlterTable
ALTER TABLE "event" DROP COLUMN "aggregate_id",
ADD COLUMN     "aggregate_id" INTEGER;
```

The problem will be picked up the next time that a migration is created. Prisma will think the index is new and add it. But until the next migration is created the index is missing, and the prisma schema is not in sync with the database schema.

## Expected behavior

Prisma should probably explicitly drop and recreate indexes in migrations when any of the fields used by the index are modified.

## Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.16.0
- Prisma version:

```
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : darwin
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.358.0
```

**Comment by pantharshit00** [comment]
I can confirm this with ` 2.20.0-dev.11`. Thanks for the detailed report.
