### ISSUE TITLE
Rename `SKIP_GENERATE` from Client postinstall script to `PRISMA_SKIP_POSTINSTALL_GENERATE`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#6151]
## Problem

https://github.com/prisma/prisma/blob/aac667e011979fd13772fcbbb9ae4bc79251d158/src/packages/client/scripts/postinstall.js#L151

We should prefix this like the other env var with `PRISMA_`

## Suggested solution

`PRISMA_SKIP_POSTINSTALL_GENERATE`

## Additional context

Migrate has an env var called `MIGRATE_SKIP_GENERATE` (not prefixed with `PRISMA_`) that could be renamed too

**Comment by Iamshankhadeep** [comment]
hey @Jolg42 can I work on this?
