### ISSUE TITLE
error prisma migrate

### ISSUE THREAD

**Issue by alan345** [prisma/prisma#6152]
Hello, 

I have an existing project using pPrisma. Im trying `prisma migrate`. And I got this Error. How can I debug that?

```
npx prisma migrate dev --name init
Environment variables loaded from .env
Environment variables loaded from prisma/.env
prisma:warn @prisma/cli has been renamed to prisma.
Please uninstall @prisma/cli: npm remove @prisma/cli
And install prisma: npm i --save-dev prisma
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "nacho@prod" at "localhost:3306"

✔ Drift detected: Your database schema is not in sync with your migration history.

We need to reset the MySQL database "nacho@prod" at "localhost:3306".
Do you want to continue? All data will be lost. … yes


Error: Database error: Error querying the database: Server error: `ERROR 42000 (1061): Duplicate key name 'userId''
   0: migration_core::api::ApplyMigrations
             at migration-engine/core/src/api.rs:75

```

**Comment by Jolg42** [comment]
Hi @alan345 

So:
- Is this your production database? Does it has data already in it (that you care about, don't want to lose)
- Are you using version 2.19.0?
- It looks like it's not your first migration? Did you edit the migration.sql file maybe?

**Comment by alan345** [comment]
Hello
- Yes I care about data. But I ran it in localhost. So I accept to delete
all data.
- yes the latest. 2.19.0
- no it's my first migration. Why do you think it is not? No I did not
change the sql file

Thanks

**Comment by Jolg42** [comment]
So because you already have a database with data you care about I recommend you to read these docs about the baselining flow:
>Baselining is for introducing Prisma Migrate to existing databases / brownfield projects. Concretely it's to tell Prisma Migrate to assume that one or more migration(s) were already executed so the generated migration(s) won't fail when they will try to create tables that already exist.
https://www.prisma.io/docs/guides/prisma-guides/add-prisma-migrate-to-a-project

If you have any feedback/questions let me know!

**Comment by tomhoule** [comment]
Please open a new issue if other problems arise, thanks!
