### ISSUE TITLE
Count queries are very inefficient and costly

### ISSUE THREAD

**Issue by robertt** [prisma/prisma#6153]
## Bug description

First of all, thanks for all the awesome work on Prisma! It's a pleasure to work with.

I was debugging a massive database throughput lock in production, and I figured out the cause:

When executing `.count()` on a model (in our case, this)
```ts
content: await db.content.count(),
contentLastDay: await db.content.count({ where: { createdAt: { gte: lastDay } } }),
youtube: await db.channel.count({ where: { platform: Platform.YOUTUBE } }),
twitch: await db.channel.count({ where: { platform: Platform.TWITCH } }),
twitter: await db.channel.count({ where: { platform: Platform.TWITTER } }),
tiktok: await db.channel.count({ where: { platform: Platform.TIKTOK } }),
```
Prisma executes it like this:
![image](https://user-images.githubusercontent.com/18425863/111514640-d6bcec80-8749-11eb-9807-57a07eaee3c4.png)

As you can see, it's selecting everything in a subquery then counting it, meaning in our case it was loading 2m+ rows entirely into memory, then counting them instead of counting them as it looks through.

I'm going to switch these queries over to raw queries for now, would be awesome if this is fixed soon though as this becomes a big issue when counting large tables.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14
- Prisma version: 2.19.0

**Comment by pantharshit00** [comment]
I won't mark this as a bug but definitely we can improve the performance here. I am going to candidate this for now.

**Comment by matthewmueller** [comment]
@robertt quick question, does concurrently running the counts improve your performance? Also could you run `EXPLAIN` on the SQL queries and share the query plan?

**Comment by robertt** [comment]
They've always been run concurrently, here's the query plan: 
![image](https://user-images.githubusercontent.com/18425863/113175611-84002c00-9243-11eb-9b4b-157f94fb9e0b.png)

**Comment by Weakky** [comment]
Hey @robertt, would you mind sharing on which Postgres version you're running these queries?

I just compared the query plan of these two queries on Postgres 10.15:

```sql
EXPLAIN SELECT COUNT(*) FROM "User" WHERE "User"."name" = 'A'
```

```
Aggregate  (cost=38.28..38.29 rows=1 width=8)
"  ->  Seq Scan on ""User""  (cost=0.00..38.25 rows=11 width=0)"
"        Filter: (name = 'A'::""Test"")"
```

vs.

```sql
EXPLAIN SELECT
  COUNT(*)
FROM
  (
    SELECT
      "public"."User"."id"
    FROM
      "public"."User"
    WHERE
      "public"."User"."name" = 'A' OFFSET 0
  ) AS "sub"
```

```
Aggregate  (cost=38.39..38.40 rows=1 width=8)
"  ->  Seq Scan on ""User""  (cost=0.00..38.25 rows=11 width=4)"
"        Filter: (name = 'A'::""Test"")"
```

And the query plans end up being exactly the same, but also different than yours.

Also, as @matthewmueller pointed out, if the code you're running looks exactly the same as the one you shared, then your queries aren't running concurrently. You are awaiting every one of your queries, meaning they end up being run sequentially.

If you want to run them concurrently, you need to use something like `await Promise.all([...])`.

**Comment by robertt** [comment]
Hey @Weakky, I'm running on Postgres 12.5 (full output of `SELECT version()`:  `PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit`.)

This is the query plan for `SELECT COUNT(*) FROM "Content"`
![image](https://user-images.githubusercontent.com/18425863/113772896-342ad480-971d-11eb-8420-b1e9bf6f9e75.png)
This is the query plan for `EXPLAIN SELECT COUNT(*) FROM (SELECT id FROM "Content" WHERE 1=1) as "sub"`:
![image](https://user-images.githubusercontent.com/18425863/113773160-8bc94000-971d-11eb-8fb1-ab67114a2d20.png)

Looks like they're exactly the same - you're right. I'd be happy to close this issue if needed, but if it's not too big of a change it might be worthwhile still making this change incase other SQL engines don't optimise this query like Postgres does.

Regarding concurrency, I changed around the code I put in the issue (none of the queries are different, just for readability purposes.)

**Comment by Weakky** [comment]
Thanks for your answer @robertt, which confirms our initial assumptions. I've tried with MySQL and SQLite and the result is the same. We're therefore closing this issue as it was intentionally designed this way for better maintainability of the codebase.

Thanks for reporting this issue to us regardless 🙏
