### ISSUE TITLE
Connection error with pgBouncer and programmatically setting connection URL

### ISSUE THREAD

**Issue by DmiPet** [prisma/prisma#6157]
## Bug description

_Note: some connection URL details like password and host have been redacted for security reasons_

When trying to use `pgbouncer=true` in a connection string for Postgres ([programmatically set](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference/#datasources)) the following error results

```
19:34:50.116 | Invalid `prisma.series.findMany()` invocation:
19:34:50.116 | Database `fi-postgres-pool-preview-1.public` does not exist on the database server at `xxxxxxxxxx-xxxxxxxx-0.b.db.ondigitalocean.com:25060`.
```

It appears that `.public` is added to the end of the database/pool name, perhaps this is the crux of the issue?

## How to reproduce

The application this issue is appearing with is a Next.js app hosted on Vercel. The Postgres database is a DigitalOcean managed instance.

Here is the connection URL specified in an environmental variable and used by `prisma/schema.prisma`

```
POSTGRES_URL="postgresql://preview:xxxxxxxxx@xxxxxxxxxx-xxxxxxxx-0.b.db.ondigitalocean.com:25060/preview?sslmode=require"
```

`prisma/schema.prisma` (excluding models)
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["createMany"]
}

datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}
```

The consensus I gleaned from other issues and Slack threads was that `prisma deploy` and `prisma generate` should not use a connection string with `pgbouncer=true`, so that flag is omitted in the env variable and the regular database is used.

When instantiating the client in Next.js, here is the code used
```
prismaClient = new PrismaClient({
      datasources: {
        db: {
          url: `postgresql://preview:xxxxxxxxx@xxxxxxxxxx-xxxxxxxx-0.b.db.ondigitalocean.com:25060/fi-postgres-pool-preview-1?sslmode=require&pgbouncer=true`,
        },
      },
    });
  }
```

I have attempted to forego programmatically changing the database URL and instead applying appropriate environmental variables through the postinstall/prebuild/build/postbuild chain, but the same issue arose. It seems that the format of the connection string and/or potentially DigitalOcean-specific issues are at play here – _I suspect_.

## Expected behavior

Successful connection to the Digital Ocean Postgres connection pool via pgbouncer.

## Environment & setup

- OS: Linux (Vercel)
- Database: PostgreSQL
- Node.js version: 12.x
- Prisma version: 2.19.0

**Comment by Jolg42** [comment]
Thanks for the report!

Note: I think you mean `prisma migrate deploy`

@pantharshit00 can try to reproduce and confirm

**Comment by janpio** [comment]
I am not sure that what you are trying to achieve is possible this way @DmiPet.

I took at a look at the PgBouncer e2e test we have:
- This is the normal connection string of a DO hosted database: `postgresql://doadmin:show-password@e2e-postgres-pgbouncer-do-user-123-0.db.ondigitalocean.com:25060/defaultdb?sslmode=require`
- And this is the Connection pool connection string: `postgresql://doadmin:show-password@e2e-postgres-pgbouncer-do-user-123-0.db.ondigitalocean.com:25061/e2e-postgres-pgbouncer?sslmode=require`

Note the difference in port and database name (for the connection pool it is the pool name).

Did you take this into account in your code? From what you posted above, you might be using the same port in your Next.js code. Please double check with the DO interface.

**Comment by DmiPet** [comment]
@janpio Ack, what a silly error on my side! Frustratingly DigitalOcean displays `25060` for the port in the connection details on the instance _Overview_ tab when selecting the connection pool in the picker, but it's `25061` as you said when looking at the connection details in the _Connection Pools_ tab.

All seems to be working well now, thank you! Glad it was an easy fix 😅

Appreciate the help @janpio @Jolg42, closing the issue

**Comment by janpio** [comment]
Oh, I know because I wasted half a day with this as well :D The port also being so close together doesn't help with uncovering this.

Glad I could help. I like your solution as well, might be a workaround to document.
