### ISSUE TITLE
Getting encoding error with prisma2 against sql server

### ISSUE THREAD

**Issue by jerryhikel-r** [prisma/prisma#6169]
Here is the error - tried a few things but no luck yet.

```
{
  "errors": [
    {
      "message": "\nInvalid `prisma.dummy.findMany()` invocation:\n\n\n  Error occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Encoding(\"encoding: unspported encoding\")) })",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "dummy"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "clientVersion": "2.17.0",
          "stacktrace": [
            "Error: ",
            "Invalid `prisma.dummy.findMany()` invocation:",
            "",
            "",
            "  Error occurred during query execution:",
            "ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Encoding(\"encoding: unspported encoding\")) })",
            "    at cb (C:\\Dev\\Code\\EcoUi\\fimm-datacore\\master1\\webserver\\node_modules\\@prisma\\client\\runtime\\index.js:78693:17)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": null
}

**Comment by janpio** [comment]
Can you share the information the issue template asks for?
https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=
Especially the schema and query you are executing would be interesting.

**Comment by jerryhikel-r** [comment]
I can't share some specifics but it is a standard Windows 10 build running a node js server using prisma 2 latest and type-graphql and typegraphql-prisma along with apollo on top, although i'm not sure that matters other than that I am using the prisma client. Backend is SQL Server version 13.0.5698.0. Tables are very standard, primary keys, nothing clustered, foreign keys, varchar and numeric and bits and ints. Is that sufficient? If not perhaps I can send you more specifics directly.

**Comment by pantharshit00** [comment]
Hey @jerryhikel-r 

Please send a minimal reproduction or failing call with schema to schemas@prisma.io. Without sufficient information it is extremely hard to tick all assumptions and make a reproduction for this error.

**Comment by jerryhikel-r** [comment]
I was able to fix it by changing all varchar fields to nvarchar fields.

**Comment by pimeys** [comment]
I'm adding more info to this error so we can debug further what's going on... https://github.com/prisma/tiberius/pull/138

But, it looks like the server gives us a code page we don't recognize.
