### ISSUE TITLE
SQL Server Introspection fails on Tables with Geography Data Type

### ISSUE THREAD

**Issue by richardkeller411** [prisma/prisma#6176]
It fails on Tables with Geography Data Type.

**Comment by janpio** [comment]
How does it fail? 
Did you get an error message? 
Could you submit an error report to our system and did you get an error report ID?

**Comment by pimeys** [comment]
We do not support the geography types due to not supporting PostGIS either on PostgreSQL. But, I'd like to take a look a bit what it would mean for us to add support at least on SQL Server...

**Comment by janpio** [comment]
This should not fail, but work similar to how unknown types are introspected with MySQL and PostgreSQL for now.

**Comment by pimeys** [comment]
Introspection will work for geometry in the next version. You'll get an unsupported type to your schema, but you can write your queries as raw if you need the data. Just remember to return data that maps to some of the existing prisma types.
