### ISSUE TITLE
Error when bundling with webpack

### ISSUE THREAD

**Issue by ericyd** [prisma/prisma#6188]
## Bug description

When using webpack 4 to bundle a file that imports `PrismaClient`, requiring the resulting bundle throws an error.

My use case is, we bundle our lambdas with webpack into a zero-dependency bundle and then deploy those to AWS.

This bug is specific to Prism 2.19.0, 2.18.0 works fine.

throws error:
```
/Users/me/dev/prisma-bundle-error/dist/index.js:129
const debug = debugLib('prisma-client')
              ^

TypeError: debugLib is not a function
    at Object../node_modules/.prisma/client/index.js (/Users/me/dev/prisma-bundle-error/dist/index.js:129:15)
    at __webpack_require__ (/Users/me/dev/prisma-bundle-error/dist/index.js:20:30)
    at Object../node_modules/@prisma/client/index.js (/Users/me/dev/prisma-bundle-error/dist/index.js:282:16)
    at __webpack_require__ (/Users/me/dev/prisma-bundle-error/dist/index.js:20:30)
    at Object../main.js (/Users/me/dev/prisma-bundle-error/dist/index.js:96:26)
    at __webpack_require__ (/Users/me/dev/prisma-bundle-error/dist/index.js:20:30)
    at Object.0 (/Users/me/dev/prisma-bundle-error/dist/index.js:35151:18)
    at __webpack_require__ (/Users/me/dev/prisma-bundle-error/dist/index.js:20:30)
    at /Users/me/dev/prisma-bundle-error/dist/index.js:84:18
    at Object.<anonymous> (/Users/me/dev/prisma-bundle-error/dist/index.js:87:10)
```

## How to reproduce

You kinda need a whole environment so I made a repo with code that reproduces this issue: https://github.com/ericyd/prisma-bundle-error

As described in the repo, steps to reproduce are:

```
git clone https://github.com/ericyd/prisma-bundle-error.git
cd prisma-bundle-error
npm i
npx webpack build
node -r ./dist/index.js
```

## Expected behavior

You should be able to require the file

## Prisma information

See linked repo, above

Node version: v14.15.5 NPM version: 6.14.11 OS: Mac OSX Catalina 10.15.7

## Environment & setup

- OS: Mac OSX Catalina 10.15.7
- Node version: v14.15.5
- NPM version: 6.14.11 OS: 
- Database: PostgreSQL 12.5
- Prisma version:

```
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : darwin
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.358.0
Preview Features     : createMany
```

**Comment by meeq** [comment]
In the resulting `client/runtime/index/js`, the `debugLib` is attached as a read-only property of `exports`:
```js
// src/runtime/index.ts
__markAsModule2(exports);
__export2(exports, {
  DMMF: () => import_generator_helper.DMMF,
  DMMFClass: () => DMMFClass,
  Decimal: () => import_decimal3.default,
  Engine: () => import_engine_core.Engine,
  PrismaClientInitializationError: () => import_engine_core.PrismaClientInitializationError,
  PrismaClientKnownRequestError: () => import_engine_core.PrismaClientKnownRequestError,
  PrismaClientRustPanicError: () => import_engine_core.PrismaClientRustPanicError,
  PrismaClientUnknownRequestError: () => import_engine_core.PrismaClientUnknownRequestError,
  PrismaClientValidationError: () => PrismaClientValidationError,
  RawValue: () => import_sql_template_tag.RawValue,
  Sql: () => import_sql_template_tag.Sql,
  Value: () => import_sql_template_tag.Value,
  debugLib: () => import_debug2.default,
  empty: () => import_sql_template_tag.empty,
  getPrismaClient: () => getPrismaClient,
  join: () => import_sql_template_tag.join,
  makeDocument: () => makeDocument,
  raw: () => import_sql_template_tag.raw,
  sqltag: () => import_sql_template_tag.sqltag,
  transformDocument: () => transformDocument,
  unpack: () => unpack,
  warnEnvConflicts: () => warnEnvConflicts
});
```
...And then at the bottom of that same file...:
```js
// src/runtime/index.ts
var import_decimal3 = __toModule2(require_decimal());
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  DMMF,
  DMMFClass,
  Decimal,
  Engine,
  PrismaClientInitializationError,
  PrismaClientKnownRequestError,
  PrismaClientRustPanicError,
  PrismaClientUnknownRequestError,
  PrismaClientValidationError,
  RawValue,
  Sql,
  Value,
  debugLib,
  empty,
  getPrismaClient,
  join,
  makeDocument,
  raw,
  sqltag,
  transformDocument,
  unpack,
  warnEnvConflicts
});
```
...`debugLib` is accessed as if it were in scope, but it is not (as shown above). This access should be `debugLib: exports.debugLib` or `debugLib` should be in scope.

**Comment by meeq** [comment]
The plot thickens.

I added this line to the top of the generated `prisma/client/index.js`: 
```js
console.log("This is the value of `require('./runtime')", require('./runtime'))
```

And here's what I got:
```
This is the value of `require('./runtime') <ref *1> [Function: Decimal4] {
  ROUND_UP: 0,
  ROUND_DOWN: 1,
  ROUND_CEIL: 2,
  ROUND_FLOOR: 3,
  ROUND_HALF_UP: 4,
  ROUND_HALF_DOWN: 5,
  ROUND_HALF_EVEN: 6,
  ROUND_HALF_CEIL: 7,
  ROUND_HALF_FLOOR: 8,
  EUCLID: 9,
  set: [Function: config],
  config: [Function: config],
  clone: [Function: clone],
  isDecimal: [Function: isDecimalInstance],
  abs: [Function: abs],
  acos: [Function: acos],
  acosh: [Function: acosh],
  add: [Function: add],
  asin: [Function: asin],
  asinh: [Function: asinh],
  atan: [Function: atan],
  atanh: [Function: atanh],
  atan2: [Function: atan2],
  cbrt: [Function: cbrt],
  ceil: [Function: ceil],
  cos: [Function: cos],
  cosh: [Function: cosh],
  div: [Function: div],
  exp: [Function: exp],
  floor: [Function: floor],
  hypot: [Function: hypot],
  ln: [Function: ln],
  log: [Function: log2],
  log10: [Function: log10],
  log2: [Function: log22],
  max: [Function: max],
  min: [Function: min],
  mod: [Function: mod],
  mul: [Function: mul],
  pow: [Function: pow],
  random: [Function: random],
  round: [Function: round],
  sign: [Function: sign],
  sin: [Function: sin],
  sinh: [Function: sinh],
  sqrt: [Function: sqrt],
  sub: [Function: sub],
  tan: [Function: tan],
  tanh: [Function: tanh],
  trunc: [Function: trunc],
  precision: 20,
  rounding: 4,
  toExpNeg: -7,
  toExpPos: 21,
  maxE: 9000000000000000,
  minE: -9000000000000000,
  modulo: 1,
  crypto: false,
  Decimal: [Circular *1],
  default: [Circular *1]
}
```

Somehow the runtime module became the `Decimal` module?

**Comment by pantharshit00** [comment]
Same error message as https://github.com/prisma/prisma/issues/6051 so I will consider this blocked by that issues. It should be resolved when we fix that imo. But I will keep this open for now.

**Comment by pantharshit00** [comment]
Referring to this specific comment for the error message btw: https://github.com/prisma/prisma/issues/6051#issuecomment-801835387

Initial description of that issue doesn't reflect it.

**Comment by MohannadBahaa** [comment]
@omar-dulaimi

**Comment by millsp** [comment]
This might already have been fixed in 2.20.1, can you please check this out? Thanks!

**Comment by ericyd** [comment]
The issue is fixed.

Does the Prisma team find it concerning that their build tool (esbuild) broke webpack builds (which ostensibly also broke netlify deployments) by updating a minor version? https://github.com/prisma/prisma/pull/6260

**Comment by Jolg42** [comment]
@ericyd esbuild is great but relatively new. Still in v0 and has breaking changes regularly.
So I'm not so surprised that an esbuild update could potentially break something.

We opened an issue for updating esbuild and having a regression test here:
https://github.com/prisma/prisma/issues/6461

**Comment by ericyd** [comment]
I think a regression test is a great idea for this.

I appreciate what you are doing with Prisma, but for an ORM I think a little more focus on stability and a little less emphasis on cutting edge might be a worthwhile trade-off. Or, perhaps consider adding a footnote in the docs to the effect that Prisma maintainers favor cutting edge over stability and things may break without warning.

I really don't mean this as a criticism, just that these types of things can be pretty critical for organizations trying to choose an ORM, which is a pretty fundamental layer of most applications. My org ended up dropping prisma after this bug because we deemed the risk too great. Prisma does a good job adhering to semver but in this case a minor update caused catastrophic failure - something most people don't expect with a minor version bump.

**Comment by Jolg42** [comment]
Actually, we definitely want to minimize breaking changes since Prisma 2 is generally available and recommended for production use.

This was an unexpected breaking change because our tests didn't catch it, I think we should add one for sure because we want to be confident when hitting the release button that we don't break anything.

I'm a bit surprised you dropped Prisma completely for this issue (fixed in the following release in 2.20.0).
I think the misunderstanding is that Prisma doesn't fully adhere to semver, see this for more details https://www.prisma.io/docs/about/releases#versioning

Does that help? Hope you can consider using Prisma again 😃

**Comment by 2color** [comment]
> I appreciate what you are doing with Prisma, but for an ORM I think a little more focus on stability and a little less emphasis on cutting edge might be a worthwhile trade-off. Or, perhaps consider adding a footnote in the docs to the effect that Prisma maintainers favor cutting edge over stability and things may break without warning.

First of all, thank you for your feedback. We take user feedback seriously and I understand your frustration.

At Prisma, we keep on iterating and improving Prisma's feature set without compromising on stability. Our development process includes extensive testing efforts (from unit tests, all the way to end-to-end tests for different deployment platforms) to prevent such things from happening. But inevitably, errors do pop up every once in a while, and when they do we improve our tests to cover these cases and prevent them from happening again.

One of the reasons we switched to esbuild because it reduced Prisma's build times significantly and made us more productive. 

If I understand your case correctly, you would have been able to detect this automatically by using Renovate to create a PR for package upgrades in combination with a simple CI pipeline to run a build for your project. 

I hope this helps. If you have any other feedback, feel free to reach out.

**Comment by ericyd** [comment]
Thank you both for the thoughtful replies, I can tell that the Prisma team is passionate which is probably why Prisma is on the whole a really excellent product.

I over-simplified by stating that this bug caused us to drop Prisma. There were a few discussions we had as a team and the two predominant factors in deciding to switch ORMs were general stability and reversible migrations. I know that reversible migrations are on the roadmap but we felt it presented too large a business risk for us at this time.

For context, we are extremely early-stage and did not have a lot of code depending on Prisma already. This gave us less incentive to stay with Prisma - not because of any inherent flaws in the product but because it meant that it was fairly easy for us to switch at this stage, but we knew that switching in a few months would be exponentially harder.

For what it's worth, my development team universally agreed that Prisma's tooling and API were the best of the ORMs we sampled. We just felt that a higher level of stability was worth the trade-off for our team.

The note about versioning is indeed helpful, that information might have been useful to us earlier in our decisioning process.
