### ISSUE TITLE
Issue when inserting/updating a float which value is 0.1

### ISSUE THREAD

**Issue by jebenois** [prisma/prisma#6189]
## Bug description

It looks like Prisma is not handling the 0.1 value correctly when doing insertion or updates.

## How to reproduce

Run a query inserting or updating a float:

```js
prisma.myTable.create({
  data: {
    someNumber: 0.1,
  },
});
```

It will create a row where someNumber value is set to 0.0999999999999 instead of 0.1.

_Note: Using a raw query works:_

```js
prisma.$queryRaw`
    INSERT INTO "prisma"."MyTable" ("someNumber")
    VALUES (${0.1})
`;
```
=> someNumber will be set to 0.1.

## Expected behavior

someNumber should be set to 0.1 instead of 0.0999999999999.

## Prisma information

```
model MyTable {
  id                     String    @id @default(dbgenerated())
  someNumber Float?
}
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v12.16.1
- Prisma version: v2.17.0

**Comment by dominichadfield** [comment]
We are also having these issues when inserting floats.

**Comment by jebenois** [comment]
Glad to hear I am not alone, it is quite an issue for us.

**Comment by jebenois** [comment]
I feel like it should be bug/0 level. It can be quite dangerous for a business app dealing with money (my case).

**Comment by janpio** [comment]
The numbers do not signify a priority here - but used to order the labels: `0-needs-info`, `1-repro-available`, `2-confirmed`. So you actually want to have `bug/2-confirmed` here as that means someone from the team successfully reproduced and this can directly be tackled by someone to fix. (I assigned @pantharshit00 to get to that state quickly).

**Comment by pantharshit00** [comment]
I can reproduce this. Thanks for detailed report. We should patch this. cc @pimeys
