### ISSUE TITLE
Postinstall fails when installing @prisma/client on node v11.9.0

### ISSUE THREAD

**Issue by adamshiervani** [prisma/prisma#6208]
## Bug description
The postinstall script throws `ReferenceError: globalThis is not defined` when installing `@prisma/client@2.19.0` on node version v11.9.0. 

```sh
➜  prisma-node-version-bug npm install @prisma/client@2.19.0

> @prisma/client@2.19.0 postinstall Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/client
> node scripts/postinstall.js

Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:14729
  module2.exports = typeof queueMicrotask === "function" ? queueMicrotask.bind(globalThis) : (cb) => (promise || (promise = Promise.resolve())).then(cb).catch((err) => setTimeout(() => {
                                                                               ^

ReferenceError: globalThis is not defined
    at __commonJS (Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:14729:80)
    at Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:6:5
    at __commonJS (Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:14738:27)
    at Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:6:5
    at __commonJS (Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:14853:15)
    at Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:6:5
    at __commonJS (Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:15056:17)
    at Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:6:5
    at __commonJS (Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:15380:21)
    at Workspace/Code/tmp/prisma-node-version-bug/node_modules/@prisma/engines/dist/index.js:6:5
```

## How to reproduce
```sh
nvm install v11.9.0
node -v # v11.9.0
npm install @prisma/client@2.19.0
```

## Expected behavior
A more descriptive error message. I was moving from prisma 2.10.0 to 2.19.0, which had many breaking changes. Fixed all of them locally and then deployed to staging. Was faced with this strange error message which took some time to solve. Would've been great if there was clearer error message in the output.

## Prisma information
Nothing else is required to reproduce the bug.

## Environment & setup
- OS: Mac OS Big Sur
- Database: Postgres
- Node.js version: v11.9.0
- Prisma version: 2.19.0

**Comment by Jolg42** [comment]
Thanks for this report 👍 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis seems to have landed in Node 12.0.0 only

As a workaround, I would suggest that you pick an LTS version of Node.js which we fully test against, like 10, 12 or 14 (12 or 14 are recommended).
Also, only LTS/even versions are fully tested in the ecosystem and get security patches.

**Comment by pantharshit00** [comment]
This is reproducible but I am not sure we want to patch this as node 10 went EOL and node 11 was not a stable release. Still marking this as confirmed bug.

**Comment by Jolg42** [comment]
We need to drop Node 10 (and 11) soon so I guess we can close as a wontfix.
