### ISSUE TITLE
Detect absense of openssl and inform the user about it

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#6211]
## Problem

Right now we don't detect presence of openssl on the CLI but it is dynamically linked dependency for the engines on linux. This can lead to undefined behaviour like CLI trying to download the binaries with no idea about openssl version leading to platform detection like `linux-arm-openssl-undefined` or spawning errors when node tries to spawn query-engine.  

## Suggested solution

Detect openssl presence on the CLI on linux and inform the user about openssl requirement. 

## Alternatives

Statically link/Vendor OpenSSL. This might be actually a requirement for upcoming napi preview. 

## Additional context

I hit this when trying to prisma studio on m1 mac docker which was using the node alpine image.

**Comment by maxxafari** [comment]
Did you manage to solve this problem?
```
FROM node:15-alpine
...
RUN apk add --no-cache openssl 
```
Did not do the trick for me. Do I need to specify a specific version?

**Comment by pantharshit00** [comment]
@maxxafari This is just an improvement about warning. If your imagine isn't working, open a new issue describing the full problem.

**Comment by Jolg42** [comment]
I think this can be closed with the changes you made @jkomyno ?
