### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Closed, cause: None } when in Google Kubernetes Engine

### ISSUE THREAD

**Issue by Ezard** [prisma/prisma#6213]
## Bug description

For a period of ~1m, all database queries failed with the error: `Error in PostgreSQL connection: Error { kind: Closed, cause: None }`. This error has not previously occurred over the several months that we've already been using Prisma, and has not occurred in the few hours since.

The application code uses the Nest.js framework, and runs in Google Kubernetes Engine. The database is a PostgreSQL 13 Cloud SQL instance, connected via Google Cloud's VPC. SSL is used when connecting to the database.

Our containers had been running for ~1hr when this happened.

There were no database operations (e.g. upgrades, backups, etc) being run at the time that the error occurred.

There were no long-running queries in progress when the error occurred.

## How to reproduce

Currently unknown

## Expected behavior

Unsure, as I don't actually know what the cause of the problem is - if Google Cloud is the cause of the connection being closed then I guess there isn't much that Prisma can do.

## Prisma information

n/a

## Environment & setup

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.19.0             |
| Query Engine    | query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|
| Database        | undefined|

## Possibly-related issues

* #5418
* #5976
* #5977
* #6139

**Comment by janpio** [comment]
Information about the PR that closed this:
https://github.com/prisma/prisma/issues/6329#issuecomment-815012006

Feel free to reply here again if the problem is not solved/better for you and we can reopen the issue of course.

**Comment by belgattitude** [comment]
@janpio 

I've updated to latest prisma 2.20.0 and 2.21.2 and still have the same issue... Aurora database and pgbouncer on top of it

After ~1minute, the connection is signaled as closed.

![image](https://user-images.githubusercontent.com/259798/116084792-6eddb800-a69e-11eb-829e-e0a21f3a0768.png)

The pgbouncer log says something like:

```
pgbouncer 2021-04-26 12:30:59.052 UTC [1] LOG C-0x55dc7b1a6f40: postgres/publicapp@x.x.x.x:39124 closing because: client unexpected eof (age=60s)
```

I tested with pgbouncer param and without (in local dev ubuntu and will with vercel lambdas)

```
DATABASE_URL=postgres://xxx/postgres?schema=public&sslmode=require&pgbouncer=true
// AND/OR
DATABASE_URL=postgres://xxx/postgres?schema=public&connection_limit=5&sslmode=require
```

It might be a config issue as well, but if you have an idea I'm available to try it out or help.

**Comment by pimeys** [comment]
You'll get one error, the connection should be then thrown away. If you have multiple connections in the pool in a closed state, then you'll get it a few times until the connections are kicked out.

We do not do connection reaping yet, but this might be a case for it in the future.

**Comment by janpio** [comment]
@belgattitude Have a look at this retry middleware: https://github.com/prisma/prisma/issues/6329#issuecomment-816954832 This should help you to avoid bad effects for exactly these errors. Unfortunately we can not do anything about the actual errors, as they _are_ happening on your database.
