### ISSUE TITLE
PrismaClient is unable to be run in the browser. 

### ISSUE THREAD

**Issue by fugohan** [prisma/prisma#6219]
## Bug description
I'm getting an Error: PrismaClient is unable to be run in the browser. 

![Selection_013](https://user-images.githubusercontent.com/46691165/112229651-abe40400-8c33-11eb-8a9b-1a89e0170863.png)

## How to reproduce

1. Create new Node Project with ```npm init -y```
2. install dependencies ```npm i next react react-dom```
3. install prisma with ```npm i -D primsa``` and then ```npm i @prisma/client```
4. init prisma with ```npx primsa init``` 
5. change schema to : 
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    String?
}

```
6. push schema to postgresql with ```npx prisma db push --preview-feature```
7. create index.js like: 
```
import {PrismaClient} from "@prisma/client"
export {PrismaClient} from "@prisma/client"

const prisma = new PrismaClient()

export default function Page(){
        return <div>Hello World</div>
}





```
8. run server 
9. getting error 

## Expected behavior

Displaying Hello World but getting an error 

## Environment & setup

- OS: Ubuntu 20.4 
- Database: PostgreSQL on Heroku
- Node.js version: v10.19.0 
- Prisma version:2.19.0

```

```

**Comment by pantharshit00** [comment]
@fugohan You are trying to use Prisma on frontend which is not possible. Either use it in next js api routes: https://nextjs.org/docs/api-routes/introduction or use it in getServerSideProps or getStaticProps: https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering

**Comment by fugohan** [comment]
> getStaticProps

Thank you :smile:

**Comment by ninest** [comment]
I was having a similar issue. I think a solution is to only initialize the client **once** and on the **server only**.

```ts
import { Prisma, PrismaClient } from "@prisma/client";

declare global {
  namespace NodeJS {
    interface Global {
      prisma: PrismaClient;
    }
  }
}

let prisma: PrismaClient;

if (typeof window === "undefined") {
  if (process.env.NODE_ENV === "production") {
    prisma = new PrismaClient();
  } else {
    if (!global.prisma) {
      global.prisma = new PrismaClient();
    }

    prisma = global.prisma;
  }
}

export default prisma;
```

**Comment by baronnoraz** [comment]
I was able to accomplish this similarly by creating a `global.d.ts` file with
```javascript
import { PrismaClient } from '@prisma/client';

declare global {
  var prisma: PrismaClient;
}
```
And using the same initialization.
```javascript
import { PrismaClient } from "@prisma/client";

let prisma: PrismaClient;

if (typeof window === "undefined") {
  if (process.env.NODE_ENV === "production") {
    prisma = new PrismaClient();
  } else {
    if (!global.prisma) {
      global.prisma = new PrismaClient();
    }

    prisma = global.prisma;
  }
}

export default prisma;
```

However, I would get the error...
```
TS2454: Variable 'prisma' is used before being assigned.
```

I adjusted the code to initialize the variable to null, but that caused typing errors elsewhere.
```javascript
let prisma: PrismaClient | null = null;
```

Doing this led to `TS2531: Object is possible 'null'` warnings in my API code (in my case NextJS API route)
```javascript
  return await prisma.user.findFirst ({
    where: {
      accessCode: accessCode
    }
  });
```

I ended up adding a `@ts-ignore` to the `export default prisma;` line.  I'm not sure if that's really the right way to do it, but I wanted to share in case someone like me encountered Typescript errors following this approach and wanted to resolve them.

**Comment by bogordesaincom** [comment]
same issue

**Comment by josiext** [comment]
Fallow this official guide: [Link](https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices)

**Comment by abdessamadelhamdany** [comment]
I had this same issue inside `getInitialProps` when using import, as fix i am using `require` inside `getInitialProps`:

```javascript
const db: PrismaClient = require('../lib/prisma').default
```
the `lib/prisma` file is from the docs as @josiext  mentioned

**Comment by arnaringig** [comment]
I encountered this error in my Nextjs ts project and was puzzled. Then I saw that I was exporting a function that I was using on the client from my custom 'utilities' directory, and from the same 'utilities'  directory I was exporting the prisma client. So I moved the prisma client ( and other serverside modules ) to a custom 'services' directory. After that the error went away.  (anecdotal/mayhelpsomeone).

**Comment by Jawmo** [comment]
This was necessary for me for me in Next.js:

```
if (typeof window === "undefined") {
...
}
```

```
if (typeof window === "undefined") {
if (process.env.NODE_ENV === "production") {
    prisma = new PrismaClient();
  } else {
    if (!global.prisma) {
      global.prisma = new PrismaClient();
    }
    prisma = global.prisma;
  }
}
```

**Comment by officialrajdeepsingh** [comment]
You call the `PrismaClient()` into `getStaticProps`, and your error is solved. When you call the `PrismaClient()` component, you face an error.

```
import { PrismaClient } from '@prisma/client'



export async function getStaticProps() {
  const prisma = new PrismaClient()

  return {
    props : { }
  }
}
```

**Comment by jereloh** [comment]
Facing same issue, with the help of the suggestions above... and the new docs I found [here](https://github.com/prisma/docs/blob/main/content/300-guides/050-database/880-troubleshooting-orm/100-help-articles/400-nextjs-prisma-client-dev-practices.mdx) this is my /lib/prisma.ts in next.js

```
import { PrismaClient } from '@prisma/client'
declare global {
  // allow global `var` declarations
  // eslint-disable-next-line no-var
  var prisma: PrismaClient | undefined
}

let prisma: PrismaClient

if (typeof window === 'undefined') {
  if (process.env.NODE_ENV === 'production') {
    prisma = new PrismaClient()
  } else {
    if (!global.prisma) {
      global.prisma = new PrismaClient()
    }

    prisma = global.prisma
  }
}
//@ts-ignore
export default prisma
```

Example usage: `import prisma from '../lib/prisma'`

**Comment by Standaa** [comment]
Thought I'd chime in as my solution is different.
Essentially the above sugggestions were breaking my tests. Jest seemed unable to infer that the prisma var declared and the let were the same variable resulting in a `Duplicate declaration prisma` error.
I also wanted to be able to export the variable itself rather than export default to keep import type-checking.
I had to update the declaration and was able to remove all the typescript and eslint exceptions:

```
import { PrismaClient } from '@prisma/client';

declare const global: Global & { prisma?: PrismaClient };

export let prisma: PrismaClient;

if (typeof window === 'undefined') {
  if (process.env['NODE_ENV'] === 'production') {
    prisma = new PrismaClient();
  } else {
    if (!global.prisma) {
      global.prisma = new PrismaClient();
    }
    prisma = global.prisma;
  }
}
```

**Comment by psycho-baller** [comment]
## another possible solution without `//@ts-ignore`: 
```tsx
import { PrismaClient } from '@prisma/client'

// PrismaClient is attached to the `global` object in development to prevent
// exhausting your database connection limit.
//
// Learn more:
// https://pris.ly/d/help/next-js-best-practices

declare global {
  var prisma: PrismaClient | undefined
}

const prisma = global.prisma || new PrismaClient({
  log: ['error']
})

if (process.env.NODE_ENV !== 'production') global.prisma = prisma

export default prisma
```
src: https://github.com/2color/next-prisma-data-proxy/blob/main/lib/prisma.ts
PS: I also think that u should also either use getStaticProps or getServerSideProps or API nextjs API routes as [this](https://github.com/prisma/prisma/issues/6219#issuecomment-808055698) comment said

**Comment by maikeg-alves** [comment]
> Pensei em entrar na conversa, pois minha solução é diferente. Essencialmente, as sugestões acima estavam quebrando meus testes. Jest parecia incapaz de inferir que o prisma var declarado e o let eram a mesma variável resultando em um `Duplicate declaration prisma`erro. Eu também queria poder exportar a própria variável em vez de exportar o padrão para manter a verificação de tipo de importação. Eu tive que atualizar a declaração e consegui remover todas as exceções typescript e eslint:
> 
> ```ts
> import { PrismaClient } from '@prisma/client';
> 
> declare const global: Global & { prisma?: PrismaClient };
> 
> export let prisma: PrismaClient;
> 
> if (typeof window === 'undefined') {
>   if (process.env['NODE_ENV'] === 'production') {
>     prisma = new PrismaClient();
>   } else {
>     if (!global.prisma) {
>       global.prisma = new PrismaClient();
>     }
>     prisma = global.prisma;
>   }
> }
> ```

thanks, work for my

**Comment by chipit24** [comment]
I had the `experimental-edge` runtime enabled in my Next.js config. None of the above solutions worked for me until I disabled that. At the time of writing I'm using the latest version of `next` (12.3.1) and `@prisma/client` (4.4.0). I did not need to use dynamic imports or a `typeof window` guard.

I didn't know that I needed extra setup to get `@prisma/client` working with Next.js's edge runtime. After going through the instructions at https://www.prisma.io/docs/data-platform/data-proxy, things are working now with the `experimental-edge` runtime enabled 🥳 But I still had to make sure I didn't have `fallbackNodePolyfills: false` set as well.

Trying to use Prisma in edge functions without the data proxy (or being able to use both versions in the same app) doesn't yet seem to be supported: https://github.com/prisma/prisma/issues/9928.

**Comment by olserra** [comment]
> 

Hello. I am trying to use that solution but prisma obj gets undefined when I call it :(

`import prisma from '../lib/prisma'

export async function getStaticProps(user: any) {
  console.log('user >>>', user)
  console.log('prisma', prisma)
  try {
    await prisma.user.create({
      data: {
        email: user.email,
        name: user.name,
      },
    })
  }
  catch (err) {
    console.error('Could not createUser >>>', err)
    process.exit?.(1)
  }
  finally {
    async () => {
      await prisma.$disconnect()
    }
  }
}`

**Comment by tyrads** [comment]
I am getting this error in node 16 in production.

**Comment by olserra** [comment]
Hello!

Who is there? Sorry.

How did you get this error?

**Comment by tyrads** [comment]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/108784253/215670761-7e243c78-f67f-43c4-85e3-559411b9159a.png">

when i import both of these modules inside an index.ts file inside db folder, and then in my other code i try to `import { MainDBClient }  from "@db"` and then the error "is unable to run in browser" is thrown. I have overcome it by directly writing like this where ever i
` need import { PrismaClient as MainDBClient } from "@db/main/prisma/generated/mainDB";
` 
@olserra

**Comment by olserra** [comment]
I think I know why. I removed your access. Sorry that I didn't say
anything. I am restricting it only to the partners now.

**Comment by chipit24** [comment]
@olserra You're replying to a public issue thread. Details about access restrictions aren't relevant to this issue; be careful not to post any sensitive info here.

**Comment by olserra** [comment]
Sorry, I haven’t noticed.

**Comment by CondorW** [comment]
Is there also a solution for this in svelte (Sveltekit)?

**Comment by RavenWits** [comment]
None of the suggestions above are not working on Next.js v.13.2 :(

**Comment by RadasLove** [comment]
> None of the suggestions above are not working on Next.js v.13.2 :( api routes transferred under App directory on this version.

Have you somehow fix this ? :-)

**Comment by VipanExertica** [comment]
> You call the `PrismaClient()` into `getStaticProps`, and your error is solved. When you call the `PrismaClient()` component, you face an error.
> 
> ```
> import { PrismaClient } from '@prisma/client'
> 
> 
> 
> export async function getStaticProps() {
>   const prisma = new PrismaClient()
> 
>   return {
>     props : { }
>   }
> }
> ```

And It Works when I Try this

**Comment by shihfu** [comment]
@pantharshit00, can we reopen this issue?

> None of the suggestions above are not working on Next.js v.13.2 :( api routes transferred under App directory on this version.

**Comment by janpio** [comment]
No. Open a new issue or discussion and describe your problem precisely, and fill the full issue template please so we have the information we need. Thank you.

**Comment by rahul8864** [comment]
### I just got an error "Error: PrismaClient is unable to be run in the browser" in Nextjs.

I just console log all the data come infinite times in my database. and again throw an error like in this picture. I already fix this problem ?

![Screenshot 2023-07-14 221506](https://github.com/prisma/prisma/assets/74202040/ffe075e9-464c-4670-a62c-c0541fbc9df7)

I solve this problem

![Screenshot 2023-07-14 221846](https://github.com/prisma/prisma/assets/74202040/0fda173b-5413-40fe-ac30-77bf9fbdfd74)

im using "use client" but prisma render in server side render so i remove "use client" it's work for me.

**Comment by k-kaundal** [comment]
import { PrismaClient } from "@prisma/client";

declare global {
  var prisma: PrismaClient | undefined;
}

const prisma = global.prisma || new PrismaClient();

if (process.env.NODE_ENV === "development") global.prisma = prisma;

export default prisma;



try this one

**Comment by ramkole** [comment]
@jacklynch00 
**prisma render in server side render so i remove "use client" it's work for me too.** - Thanks

> > ### I just got an error "Error: PrismaClient is unable to be run in the browser" in Nextjs.
> > I just console log all the data come infinite times in my database. and again throw an error like in this picture. I already fix this problem ?
> > ![Screenshot 2023-07-14 221506](https://user-images.githubusercontent.com/74202040/253633428-ffe075e9-464c-4670-a62c-c0541fbc9df7.png)
> > I solve this problem
> > ![Screenshot 2023-07-14 221846](https://user-images.githubusercontent.com/74202040/253633488-0fda173b-5413-40fe-ac30-77bf9fbdfd74.png)
> > im using "use client" but prisma render in server side render so i remove "use client" it's work for me.
> 
> You can't use the "use client" directive and also use prisma. Must do one or the other, likely you want to turn this into a React Server Component and still use prisma.

**Comment by brunomatosdev** [comment]
> Thought I'd chime in as my solution is different. Essentially the above sugggestions were breaking my tests. Jest seemed unable to infer that the prisma var declared and the let were the same variable resulting in a `Duplicate declaration prisma` error. I also wanted to be able to export the variable itself rather than export default to keep import type-checking. I had to update the declaration and was able to remove all the typescript and eslint exceptions:
> 
> ```ts
> import { PrismaClient } from '@prisma/client';
> 
> declare const global: Global & { prisma?: PrismaClient };
> 
> export let prisma: PrismaClient;
> 
> if (typeof window === 'undefined') {
>   if (process.env['NODE_ENV'] === 'production') {
>     prisma = new PrismaClient();
>   } else {
>     if (!global.prisma) {
>       global.prisma = new PrismaClient();
>     }
>     prisma = global.prisma;
>   }
> }
> ```

This was the only solution that worked for me

**Comment by JuniorCalva40** [comment]
I realized that the issue occurred because I forgot to use `'use server'`, as I was running a server action with Prisma.

**Comment by itsgreylolol** [comment]
> > Thought I'd chime in as my solution is different. Essentially the above sugggestions were breaking my tests. Jest seemed unable to infer that the prisma var declared and the let were the same variable resulting in a `Duplicate declaration prisma` error. I also wanted to be able to export the variable itself rather than export default to keep import type-checking. I had to update the declaration and was able to remove all the typescript and eslint exceptions:
> > ```ts
> > import { PrismaClient } from '@prisma/client';
> > 
> > declare const global: Global & { prisma?: PrismaClient };
> > 
> > export let prisma: PrismaClient;
> > 
> > if (typeof window === 'undefined') {
> >   if (process.env['NODE_ENV'] === 'production') {
> >     prisma = new PrismaClient();
> >   } else {
> >     if (!global.prisma) {
> >       global.prisma = new PrismaClient();
> >     }
> >     prisma = global.prisma;
> >   }
> > }
> > ```
> 
> This was the only solution that worked for me

Trying this in a vite app, and `prisma` is always undefined. Do you have an example of project where this works I can use as reference?

**Comment by ckhatton-pvfscaffolding** [comment]
Anyone stumbling across this in 2025, this can also be caused by Prisma not generating the Prisma Client properly.

It isn't mentioned in the documentation as a step, but you need to change the generated "output" value for "client" in the `schema.prisma` file; you either omit it or change it to `../node_modules/.prisma/client`. The documented default value `node_modules/.prisma/client` ([source](https://www.prisma.io/docs/orm/reference/prisma-cli-reference#arguments)) is incorrect, because it outputs to the `./prisma` folder 🤦

`prisma/schema.prisma`:

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/.prisma/client"
}
```

> **Note:**
> Come `v7.0.0`, the output and, with that, a shadow database will be mandatory.
