### ISSUE TITLE
Packaging for homebrew + zeit/pkg

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#623]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 05, 2017 at 18:38 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/155_

----

It should be possible to install the cli without having Node.JS installed

**Comment by kbrandwijk** [comment]
I'm not sure how well that works with regards to versioning. The npm route is a proven, cross platform way to install global modules and CLI packages.
Also, having the CLI as executable comes with PATH issues, that npm already deals with, and also prevents using the CLI directly from code, unless that's published as a separate package. However, this will increase overhead.

**Comment by schickling** [comment]
I think you're right. We'll probably not make this the default way to install the CLI however I'm curious how Zeit deals with the issues you've mentioned. Maybe @leo can share his thoughts on this?

**Comment by leo** [comment]
We're basically letting `npm` handle everything related to PATH, placing the binary in the correct destination and making it accessible (we're writing to a binary file in the `postinstall` step).

[More details](https://github.com/zeit/now-cli#why-ship-a-pkg-ed-binary)

**Comment by schickling** [comment]
Closing in favor of #1480.
