### ISSUE TITLE
Dynamic column types

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#623]
aka variable length column types

This issue also covers "how to alter opinionated Prisma behavior" for a type that has some opinion baked in. 

This covers multiple datatypes but let us define the essence of the issue by talking about this specific issue: https://github.com/prisma/lift/issues/116

Summary: To support 4 byte unicode with MySQL, we need to limit the size of a variable to 191 characters to be in the limit for max MySQL index key prefix size of 747 bytes as 191*4 = 764 or run MySQL in non-strict mode and truncate index. This is an opinion baked into Prisma. 

It should however be configurable to define the size of a type in the Prisma schema OR alter this default behavior. 

This configuration needs product + spec work.

**Comment by albertoperdomo** [comment]
This is being addressed in https://github.com/prisma/prisma/issues/3447.

**Comment by janpio** [comment]
How do we handle the index limit size that Divy describes above in #3447 actually @albertoperdomo?

**Comment by albertoperdomo** [comment]
@janpio I think handling index limit size is an implementation detail involved in solving #3447.
