### ISSUE TITLE
DataLoaders not combining findUnique queries that can be combined

### ISSUE THREAD

**Issue by XiNiHa** [prisma/prisma#6236]
## Bug description

When calling separate `findUnique()` calls, Prisma combines all the queries very well, thanks to the DataLoader.
This works well even when the `where` clause of the `findUnique()` calls are different, by using `IN`.
However, I found that it doesn't combine queries that have the `include` field.
I have logged the queries and found that the exact same two queries were getting fired.
I know that there is a plan to resolve `include`s using joins and that will make this useless. However if implementing this isn't that big deal, I want to see it implemented soon.

## How to reproduce

```ts
const prisma = new PrismaClient({ log: ['query] })

prisma.someTable.findUnique({ where: { id: 1 } }).then(console.log)
prisma.someTable.findUnique({ where: { id: 1 } }).then(console.log)
prisma.someTable.findUnique({
  where: { id: 1 },
  include: { someRelation: true }
}).then(console.log)
```

Then total 3 queries are fired(for `findUnique()` calls without `include`, for `findUnique()` calls with `include`, and for the relation).

## Expected behavior

The number of queries can be reduced to 2 if the issue is resolved, and eventually can be 1 if joins are implemented.

## Environment & setup

- OS:  macOS 11.2.3 ~~Does this even matter~~
- Database: MySQL 5.7
- Node.js version: v15.5.0
- Prisma version:

```
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : darwin
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../../node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at ../../node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.358.0
```

**Comment by pantharshit00** [comment]
I think the behaviour is expected. 
Dataloader is batching the first two queries and using `IN` and perform two queries for the third to load relations:
```
prisma:query SELECT "public"."User"."id", "public"."User"."email", "public"."User"."name" FROM "public"."User" WHERE "public"."User"."id" IN ($1,$2) OFFSET $3
prisma:query SELECT "public"."User"."id", "public"."User"."email", "public"."User"."name" FROM "public"."User" WHERE "public"."User"."id" = $1 LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."title", "public"."Post"."content", "public"."Post"."published", "public"."Post"."authorId" FROM "public"."Post" WHERE "public"."Post"."authorId" IN ($1) OFFSET $2
```

If you are asking why it performs the second query, its because we don't have any deduplication.

**Comment by XiNiHa** [comment]
I have expected deduplication to happen. Looks better to just move to #3635 then.
