### ISSUE TITLE
`prisma migrate` set field as unique automatically

### ISSUE THREAD

**Issue by mrmntte** [prisma/prisma#6239]
## Bug description

When I use a model (pivot table) to create a relation of 3 models, the field that stores a foreign key is set to unique automatically.

See the bottom of the image. `EntityOnCategory_categoryId_unique`

![image](https://user-images.githubusercontent.com/49642108/112453367-9cdd7e80-8d25-11eb-999a-2f6d4da71b78.png)

## Expected behavior

It should not be unique unless specified using `categoryId BigInt? @unique` or `@@unique([categoryId])`

## Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["createMany"]
}

datasource db {
  provider = "postgresql"
  url = env("DATABASE_URL")
}

model Post {
  id BigInt @id @default(autoincrement())
  title String
  categories EntityOnCategory[]
}

model Project {
  id BigInt @id @default(autoincrement())
  name String
  categories EntityOnCategory[]
}

model Category {
  id BigInt @id @default(autoincrement())
  name String
  entity EntityOnCategory?
}

// pivot model
model EntityOnCategory {
  id BigInt @id @default(autoincrement())
  categoryId BigInt? // 🚨 This field is set as unique automatically. 🚨
  postId BigInt?
  projectId BigInt?
  addedAt DateTime?

  post Post? @relation(fields: [postId], references: [id])
  project Project? @relation(fields: [projectId], references: [id])
  category Category? @relation(fields: [categoryId], references: [id])
}
```

## Environment & setup

- OS: macOS Big Sur
- Database: PostgreSQL
- Node.js version: 14.5.0
- Prisma version: 2.19.0

**Comment by tomhoule** [comment]
Hi @mrmntte — this is something we noticed and have been thinking about recently.

The reason there is a unique index there is that the field defines a 1 to 1 relation between `EntityOnCategory` and `Category`. Migrate adds the unique index to make sure it does not end up as a one-to-many relation in the database. This is something that was necessary with the old relation syntax (until a year ago approximately). I personally think we should make that index explicit, and validate the schema so you _have_ to manually write `@unique` if you have a 1:1 relation. Would that solve the issue for you?

**Comment by mrmntte** [comment]
You are right, I changed:
`entity EntityOnCategory?`
to
`entities EntityOnCategory []`
And it works as it should.

Thank you Tom.

**Comment by Hassan247** [comment]
I am encountering the same issue. A unique constraint is automatically added to a foreign key column when creating a one-to-many relationship between User and Order.

`model User {
  id                     String       @id @default(cuid())
  email                  String       @unique
  password               String
  orders                 Order[]
}`

`model Order {
  id            String     @id @default(cuid())
  amount        Float
  userId        String      
  user          User       @relation(fields: [userId], references: [id])
}
`

**Comment by janpio** [comment]
Can you be more precise @Hassan247? What happens to what field exactly that is unexpected to you?
I suggest you open a discussion instead of commenting in an old, closed issue by the way - much better for us to debug your problem together.
