### ISSUE TITLE
Security Issue: Request for contact

### ISSUE THREAD

**Issue by pwntester** [prisma/prisma#6241]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

Kind regards,
A

**Comment by janpio** [comment]
Hi @pwntester, thanks for contacting us. Someone will do as suggested and reach out.

**Comment by pantharshit00** [comment]
You can find our security email address here https://github.com/prisma/prisma#security

It is `security@prisma.io`

**Comment by Jolg42** [comment]
Thank you for contacting us.
We'll look into adding a Security Policy like you mentioned to make the process easier.

**Comment by pwntester** [comment]
Thanks, sorry I missed the security alias in the README doc, will send you the details there.
