### ISSUE TITLE
Prisma Migrate fails with geospatial types

### ISSUE THREAD

**Issue by garretteklof** [prisma/prisma#6256]
## Bug description

When trying to initialize migrations on an existing project with geospatial types the migration fails with `ERROR: type "geometry" does not exist.`
## How to reproduce

Create Postgis database and table with column type "geometry" and run `prisma migrate dev`
## Expected behavior

To initialize the migration history.
## Prisma information

Example of a model in the Prisma schema that was generated via introspection.
```prisma
model clu {
  id                 String                  @id
  state_id           String                  @db.Char(2)
  county_id          String                  @db.Char(5)
  township_id        String
  geometry           Unsupported("geometry")
  acres              Float?
  @@index([county_id], name: "clu_county_idx")
}
```
## Environment & setup

- OS:  Mac OS
- Database:  PostgreSQL
- Node.js version:  15.6
- Prisma version: 2.19

<img width="883" alt="Screen Shot 2021-03-26 at 1 37 23 AM" src="https://user-images.githubusercontent.com/4140229/112592576-32cfe280-8dd4-11eb-9889-dbad353d1367.png">

**Comment by garretteklof** [comment]
Ah, duh. Yep.. that's more than likely the error (will verify and then close soon). Idk why I was assuming Prisma would honor the previously installed extensions when the DB was being reset. 

So kind of a silly question, but to clarify the flow for handling this would be to first create a draft (`prisma migrate dev --create-only`) and then add all the database boilerplate (extensions, Postgres functions, etc) - then run the migration? And this flow carries through for other migrations when including database functionality outside what is handled with `prisma.schema`?

**Comment by tomhoule** [comment]
Hi @garretteklof — yes this is exactly the expected workflow. In general, the right mental model is that migrate will execute all the SQL in your migrations, and only the SQL in your migrations, so it has to include things like `CREATE EXTENSION` statements. This is both for databases after a `reset` and the shadow database, so it is important.
