### ISSUE TITLE
Error when trying to use @db.Time(0) to save data with the format 00:00 using a String

### ISSUE THREAD

**Issue by xanxuz** [prisma/prisma#6264]
## Bug description

Use of @db.Time(0) in a DateTime field to save data with the format 00:00 results in an error asking for a DateTime instead of a String.

## How to reproduce

1. Create the model:
```
model TimeRangeTest {
  id    String  @id @default(uuid())
  from DateTime @db.Time(0)
  to DateTime @db.Time(0)
}
```
2. Create seed file and insert on main function:
```
const result = await prisma.timeRangeTest.create({
    data: {
      from: '12:30',
      to: '14:30'
    }
  })

  console.log(result)
```
3. Push the changes
`prisma db push --preview-feature`

4. Seed DB
` prisma db seed --preview-feature`

5. Get error
![image](https://user-images.githubusercontent.com/11968584/112638242-6b43e080-8e15-11eb-9680-881e9a505d67.png)

## Expected behavior

Save values using a String with the format 00:00 when using @db.Time (0) in a DateTime field

## Prisma information

```
Environment variables loaded from .env
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : windows
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.358.0
Preview Features     : createMany

```

## Environment & setup

- OS: Windows 10
- Database: PostgreSQL
- Node.js version: v14.15.1

**Comment by pantharshit00** [comment]
I am unable to reproduce this with `2.23.0-dev.28`. Can you please try this again with the latest version of Prisma. 

![image](https://user-images.githubusercontent.com/22195362/118408570-c7074900-b6a3-11eb-83be-8dad16d5437b.png)
