### ISSUE TITLE
Error when introspecting Azure SQL Server database

### ISSUE THREAD

**Issue by willianhf** [prisma/prisma#6269]
I started a new Prisma project from scratch and followed the [Microsoft SQL Server connector guide](https://www.prisma.io/docs/concepts/components/preview-features/sql-server/#limitations-and-known-issues) then I ran the introspect command and the following error was thrown.

## Error
```
Error: [libs/sql-schema-describer/src/getters.rs:21:14] called `Result::unwrap()` on an `Err` value: "Getting data_type from Resultrow ResultRow { columns: [\"column_name\", \"data_type\", \"character_maximum_length\", \"column_default\", \"is_nullable\", \"is_identity\", \"table_name\", \"constraint_name\", \"numeric_precision\", \"numeric_scale\"], values: [Text(Some(\"location\")), Text(None), Integer(Some(-1)), Text(None), Boolean(Some(true)), Integer(Some(0)), Text(Some(\"carg_client_origins\")), Text(None), Integer(None), Integer(None)] } as String failed"
```

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v15.11.0           | 
| Prisma CLI  | 2.19.0             | 
| Binary      | c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|

**Comment by janpio** [comment]
Can you share some information about your database schema? Then we could try to reproduce your problem.

We have end to end tests for running against Azure SQL Server at https://github.com/prisma/e2e-tests/tree/dev/databases/sqlserver-azure-sql, so we know that it fundamentally works.

**Comment by willianhf** [comment]
This is the schema of the table that is throwing error when trying to introspect:

```SQL
create table carg_client_origins
(
	id int identity
		primary key,
	address nvarchar(255),
	number int,
	complement nvarchar(255),
	zip_code nvarchar(255),
	province nvarchar(255),
	created_at datetime,
	updated_at datetime,
	location geography,
	city nvarchar(255)
)
go
```

**Comment by pimeys** [comment]
Introspection will work for geometry in the next version. You'll get an unsupported type to your schema, but you can write your queries as raw if you need the data. Just remember to return data that maps to some of the existing prisma types.
