### ISSUE TITLE
Support `BIN_TO_UUID` and `UUID_TO_BIN` in MySQL

### ISSUE THREAD

**Issue by MattGson** [prisma/prisma#6275]
## Problem

In MySQL, `uuid()` and `cuid()` are only compatible with String type fields.
To efficiently store uuids in MySQL we need to store as `Binary(16)` and convert using `BIN_TO_UUID` and `UUID_TO_BIN`
functions.

## Suggested solution

Add a native type for MySQL String fields `@db.Uuid` or `@db.UuidBinary`. When this type is specified, Prisma treats the column as Binary(16) and uses the uuid conversion functions when reading and writing to the column. 

This should not require that the default value is set to `uuid` or `cuid` as we may want to manually generate ids in some cases.

## Alternatives

Try and write middleware to convert buffer on read/write and manually alter the generated TS types to return `string` for the Binary(16) uuid fields.

## Additional context

Without this, MySQL uuids are pretty much un-usable as the indexes are enormous when stored as char(36)

**Comment by janpio** [comment]
What already works right now that includes these 2 MySQL functions you mentioned, is to have primary key of type `Bytes` (which translates to a `Binary` in MySQL) and a default that generates an appropriate value via `uuid_to_bin(uuid())`. You can see an example here, in an issue that describes a _current_ problem with migrating these: https://github.com/prisma/prisma/issues/10715

**Comment by cprieto** [comment]
- Duplicated (see https://github.com/prisma/prisma/issues/7010)

**Comment by cprieto** [comment]
- Duplicated (see https://github.com/prisma/prisma/issues/7010)
- It is already implemented since Prisma 3.10 (and swapped UUIDs in 3.15, see https://github.com/prisma/prisma/issues/12850)

**Comment by freshFishForAndroid** [comment]
When i try to convert uuid to bin by uuid_to_bin,it report a error--FUNCTION lucky_turntable.UUID_TO_BIN does not exist.How can i solve it?

**Comment by janpio** [comment]
Open a new discussion and describe your problem fully please @freshFishForAndroid. Thanks.
