### ISSUE TITLE
Error when using `join` raw query helper with SQL Server

### ISSUE THREAD

**Issue by androsj** [prisma/prisma#6276]
## Bug description

Hello, this is most likely MS SQL Server specific.

I'm trying to run a raw query with an `IN` clause for which I'm using the `Prisma.join()` helper, as shown [here](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#tagged-template-helpers).

I get the following error:
```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]:
Invalid `prisma.queryRaw()` invocation:


  Raw query failed. Code: `245`. Message: `Conversion failed when converting the nvarchar value '{"values":[1,2,3],"strings":["",",",",",""],"text":"$1,$2,$3","sql":"?,?,?"}' to data type int.`
```

## How to reproduce

1. Connect to an sql server database
2. Run a raw query with the following bit in the `where` clause: `IN (${Prisma.join(ids)})` - where `ids` is an array of numbers.

## Expected behavior

Expected the query to return results.

## Environment & setup

- OS: Windows 10
- Database: Microsoft SQL Server
- Node.js version: 14.16.0
- Prisma version: 2.18.0

**Comment by androsj** [comment]
hi! just want to add that I now ran an actual test query with the same results: **It tries to convert an object to int**
It was late on Friday when I ran into this issue and didn't have time to confirm it. 😅

**Comment by pantharshit00** [comment]
This is still reproducible in 2.21-dev.38. Marking this as a candidate. 

![image](https://user-images.githubusercontent.com/22195362/114552064-cb45de00-9c81-11eb-837b-ac6925c9e592.png)

**Comment by pimeys** [comment]
This is an incorrect query translation in the typescript layer. What it does:

```sql
SELECT * FROM [User] WHERE id IN (@P1)
```
And passing the ids as one param. Instead it should be doing:
```sql
SELECT * FROM [User] WHERE id IN (@P1, @P2, @P3, ...)
```
passing the parameters separately.

**Comment by janpio** [comment]
Internal discussion with context: https://prisma-company.slack.com/archives/C016KUHB1R6/p1618821647052800

**Comment by millsp** [comment]
Hey @androsj, sorry that you experienced trouble. There are two problems here:
1. From the error shown, it seems that your model has an `id` of type `String`, but you are querying with `number`s. Could you try to map your `ids` to strings and let us know?
2. Prepared statements were not working correctly as @pimeys kindly pointed out. This is fixed in the linked PR.

**Comment by janpio** [comment]
@androsj This is now released with 2.26.0 - can you maybe take another look and let us know if this now works as expected?

**Comment by chriszrc** [comment]
@janpio I'm using prisma 3.12.0, and with postgres, when I run a query like this:

```sql
select * from test
WHERE test_id = ANY(ARRAY[${Prisma.join(ids)}])
```

it fails with: 
```
Raw query failed. Code: `42883`. Message: `db error: ERROR: operator does not exist: integer = text
HINT: No operator matches the given name and argument types. You might need to add explicit type casts.`
```

But ids is already a number[] in js, so you'd expect it to work. It does however run when I add the explict type casts:

```sql
select * from test
WHERE test_id = ANY(ARRAY[${Prisma.join(ids)}]::int[])
```

**Comment by janpio** [comment]
Please open a new issue about this @chriszrc - this olf issue was about SQL Server specifically. You are hitting a different problem here. THanks.
