### ISSUE TITLE
Mysql Decimal type still has JS rounding errors?

### ISSUE THREAD

**Issue by unimatrix27** [prisma/prisma#6284]
Hi, I upgraded to prisma 2.19 go use the native types to get rid of issues with javascript number rounding errors.

My Mysql DB has a field DECIMAL(20,10) which is introspected correctly as decimal type.

If i create a new record with the value 607013.31 into the table, then it actually inserts 607013.3100000001. I have checked the mysql logs and it actually is something in the query, not the DB. changing the value to e.g. 607013.32 leads to the error disappearing. 

prisma version 2.19.0, nodejs 14.13.1

**Comment by tarazena** [comment]
I think its related to  #6049

**Comment by unimatrix27** [comment]
> I think its related to #6049

yes but I am happy to use decimal.js. Conversions between number and decimal and back are correct and dont have this problem. The whole point of decimal.js is to avoid the floating point issues. so it seems to be somewhere in the prisma adaption of decimal.js when converting into the INSERT query string

**Comment by janpio** [comment]
Could you quickly recreate your issue following the issue template @unimatrix27 from https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=? Then we are happy to reproduce this and confirm if we can - and then of course try to fix it. Thanks!
