### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kladnik** [prisma/prisma#6318]
Hi Prisma Team! My Prisma Client just crashed. 

I currently have issues with Prisma that is deployed on Google App Engine. There is clearly a memory leak and I get a lot of errors from prisma - **Error in PostgreSQL connection: Error { kind: Closed, cause: None }**. I am using a single prisma client to access everything and couldn't find any issues, so any help would be appreciated.

The memory usage starts at 400MB (normal) goes all the way to 1.5GB at which point the instance resets since the memory exceeded the threshold. Memory usage picture below. I already got more than 2.5k `My Prisma Client just crashed` errors like below in less than 24h (most of them at the time of the restart) out of cca 100k read/writes.

![image](https://user-images.githubusercontent.com/11619663/112988452-2517b580-9164-11eb-88f6-60203995fe1b.png)

Before implementing prisma, the memory usage was around 500MB.

Let me also note that I catching a lot of expected prisma errors (50k+ in 24h) like:
- NotFoundError: No User found Error: NotFoundError: No User found 
- Invalid `prisma.user.update()` invocation: An operation failed because it depends on one or more records that were required but not found. Record to update not found. 
- Invalid `prisma.lessonActivity.create()` invocation: Foreign key constraint failed on the field: `LessonActivity_userId_fkey (index)` 

Since this was just deployed to write new data, while old will be migrated if everything is fine. **Are maybe the errors the problem?** But since they are getting handled, it shouldn't be an issue.

The report is below:

## Versions
| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.21.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.19.0             |
| Query Engine    | query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|
| Database        | unknown|
## Query
```
query {
  findUniqueUser(where: {
    id: "X"
  }) {
    progress
  }
}
```
There are a lot of different queries in the errors (I just copied one), so I don't think this matters that much
## Logs
```
Fetched a connection from the pool
prisma:engine stdout  Unknown error
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/workspace/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/workspace/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async cb (/workspace/node_modules/@prisma/client/runtime/index.js:34744:26) {
    clientVersion: '2.19.0'
  }
}
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  Unknown error
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
      at NodeEngine.graphQLToJSError (/workspace/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/workspace/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    clientVersion: '2.19.0'
  }
}
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  Unknown error
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/workspace/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/workspace/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async cb (/workspace/node_modules/@prisma/client/runtime/index.js:34744:26) {
    clientVersion: '2.19.0'
  }
}
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  Unknown error
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
      at NodeEngine.graphQLToJSError (/workspace/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/workspace/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    clientVersion: '2.19.0'
  }
}
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  Unknown error
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/workspace/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/workspace/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async cb (/workspace/node_modules/@prisma/client/runtime/index.js:34744:26) {
    clientVersion: '2.19.0'
  }
}
Error in PostgreSQL connection: Error { kind: Closed, cause: None }&template=bug_report.md
```

**Comment by janpio** [comment]
Can you possibly share your application or is it closed source?
If it is closed, can you describe how you use Prisma in that app?

> Since this was just deployed to write new data, while old will be migrated if everything is fine. **Are maybe the errors the problem?** But since they are getting handled, it shouldn't be an issue.

Just to clarify: The errors are expected, and handled, and you are asking if those could lead to memory problems - correct?

**Comment by kladnik** [comment]
Hi @janpio, thanks for the reply.

> Can you possibly share your application or is it closed source?

This is a closed source project, so sadly I cannot share the code.
Here is the code for how my prisma client is initialized.

```ts
import { PrismaClient } from '@prisma/client';
import { logger } from './winston';

const prisma = new PrismaClient({
    errorFormat: 'pretty',
    log: [
        { emit: 'event', level: 'query' },
        { emit: 'event', level: 'error' },
        { emit: 'stdout', level: 'error' },
        { emit: 'stdout', level: 'info' },
        { emit: 'stdout', level: 'warn' },
    ],
});

// prisma.$on('query', (e) => {
//     console.log('Query: ' + e.query);
//     console.log('Duration: ' + e.duration + 'ms');
// });

prisma.$on('error', (e) => {
    logger.error(e.message);
});

export default prisma;
```
Every read/write is using the above prisma client. It's currently also the only connection to db (except when I manually run few queries).

> Just to clarify: The errors are expected, and handled, and you are asking if those could lead to memory problems - correct?

Correct, I'm just throwing out ideas, since I am not sure what could be the culprit. 

> Where is the database hosted? Do you also have metrics from that, possibly about open connections, restarts and similar?

Oh, sorry, totally forgot to mention this. It's also with google - Cloud SQL. We're using default connection limit and timeout. I did try increasing both, but it didn't change anything. 
I just checked and everything looks good in DB dashboard. Some stats (last 24h):
- max connection is less than 10 with avg of 6
- read/writes max cca 90/s with avg of 32/s
- cpu not even at 5%
- around 180MB current size

**Comment by janpio** [comment]
We have a few issues about Cloud SQL and `connection closed` or `Error { kind: Closed, cause: None }` - so that was interesting information. 

We have not heard about memory leaks in that context though, so I am a bit puzzled.

Your code obviously looks good. We'll have to investigate.

You do not by chance have a test suite, load test or similar, that can trigger the same behavior and problems?

**Comment by kladnik** [comment]
I do not have any test suite, but it's pretty straight forward. The following code (different queries though) just happens over multiple places:

```ts
handleTryCatch(prisma.user.update({ data: { referral: referralCode }, where: { id: uid } }));

export const handleTryCatch = async (promise: Promise<any>) => {
    try {
        return await promise;
    } catch (err) {
        logger.error(err);
    }
};
```
I am using a temporary helper function currently just to log errors and not block current app flow with errors/exceptions - I do not wait for any response. 
If needed I can happily assist you with some more examples over Slack or something else.

One thing I can tell is that locally it works fine, I was running a big test migration of 250k items over multiple hours and there were zero errors (I honestly didn't check memory usage back then). So the issue does seem with GAE.

It is annoying since it's basically blocking production release.
I will try updating to `2.20.0` and commenting out all error logging to see if this helps and report back.

**Comment by kladnik** [comment]
> I will try updating to `2.20.0` and commenting out all error logging to see if this helps and report back.

This didn't solve anything.
One thing I noticed is that once the memory rises it never goes back down to normal even when the app is not used. Is Prisma client memory intensive? How much memory is needed for it run properly (maybe 1GB is not enough)?

**Comment by kladnik** [comment]
@janpio I did some testing and it's not just a Google App Engine issue, I could easily reproduce it locally on my machine.

I was sending a batches of 1k requests to my API and after I got response from all I repeated this 10x for total of 10k requests. Then I waited for all the requests to finish processing (cca 5min) and I ran the complete flow 3 more times without restarting the instance.

This is the result of the first test where Prisma is reading and writing alongside Firebase:
```
prisma on, firestore on
10000 requests - 200MB -> 1.4GB -> 650MB
10000 requests - 650MB -> 1.5GB -> 900GB
10000 requests - 900MB -> 1.8GB -> 1.3GB
```
We can clearly see that the RAM keeps getting bigger and bigger even when there are no new requests being sent.

I ran the same flow again without the prisma code  out and this is the result:
```
prisma off, firestore on
10000 requests - 150MB -> 1.1GB -> 260MB
10000 requests - 260MB -> 1.0GB -> 270MB
10000 requests - 270MB -> 1.1GB -> 270MB
```

This is the code that was commented out:
```js
handleTryCatch(prisma.lessonActivity.create({ data: activity }));
prisma.user.findUnique({ where: { id: uid }, select: { lessonProgress: true } }).then((user) => {
    const lessonProgress = user?.lessonProgress || {};
    lessonProgress[lessonId] = { progress: 1, index: 1 };
    handleTryCatch(prisma.user.update({ data: { lessonProgress }, where: { id: uid } }));
});
```

**Comment by janpio** [comment]
Thank you for testing that out, that of course makes it a much "easier" target to reproduce. Do you think we can get to a simple reproduction easily in a new repository? That would be the absolute best for us if we just have a project we can run and see what is going on. Otherwise we will now have to start the process of trying to get there on our own.

**Comment by kladnik** [comment]
I was doing some more testing and finally found the culprit. It was `@google-cloud/debug-agent` and apparently it's a known issue: https://github.com/googleapis/cloud-debug-nodejs/issues/811. Sorry for creating a bit of confusion regarding this.

That out of the way the memory is stable, but yet I am still seeing `Error { kind: Closed, cause: None }` every hour or so. I initially though this was because of the memory leak, but it is in fact a separate issue.

I also see that this is known: https://github.com/prisma/prisma/issues/6329 
So I'll close this issue and we can continue the discussion there.

**Comment by janpio** [comment]
Wow, this is amazing news. I was worried a bit there.
Left a +1 on that Google Debugger issue.

As you can see in the other (and more issues with the same label) we are working on that, actively, and will hopefully have it figured out and fixed soon.

**Comment by kladnik** [comment]
Yea I can see that! Thanks for all the help @janpio!

**Comment by kevinsimper** [comment]
For other people coming from google searches on "jest prisma memory leak", then there is a ongoing a memory issue in #12370
