### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Closed, cause: None }

### ISSUE THREAD

**Issue by narciero** [prisma/prisma#6329]
Since upgrading to `2.18.0` (now on `2.19.0`) I have been experiencing a large number (10+/day per ~1k req/day) of the below error, my application is running on Google Cloud Run and I am using Postgres 12 via Cloud SQL.

These errors happen for all different queries/mutations and there is no discernible pattern that triggers the error, they happen regardless of cold-start, mem/cpu usage, etc.

Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | linux-musl         |
| Prisma Client   | 2.19.0             |
| Query Engine    | query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|
| Database        | postgres 12 (Cloud SQL)|

## Query
```
mutation {
  updateOneBooking(
    where: {
      id: "X"
    }
    data: {
      status: Reserved
      events: {
        create: []
      }
      jobs: {
        upsert: [
          {
            where: {
              id: "X"
            }
            create: {
              id: "X"
              type: Email
              payload: "X"
            }
            update: {

            }
          }
        ]
      }
    }
  ) {
    id
    ...
  }
}
```

## Logs
```
ing the database: connection closed
      at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34744:26)
      at async Object.getCurrentUser (/usr/src/app/dist/services/auth.js:65:43)
      at async ApolloServer.createContext [as context] (/usr/src/app/dist/context.js:43:20) {
    clientVersion: '2.19.0'
  }
}
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34744:26)
      at async Object.onBookingPayment (/usr/src/app/dist/services/booking/index.js:472:9)
      at async onPaymentIntentSucceeded (/usr/src/app/dist/webhooks/stripe.js:118:5)
      at async stripeWebhook (/usr/src/app/dist/webhooks/stripe.js:59:13) {
    clientVersion: '2.19.0'
  }
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34744:26)
      at async Object.onBookingPayment (/usr/src/app/dist/services/booking/index.js:472:9)
      at async onPaymentIntentSucceeded (/usr/src/app/dist/webhooks/stripe.js:118:5)
      at async stripeWebhook (/usr/src/app/dist/webhooks/stripe.js:59:13) {
    clientVersion: '2.19.0'
  }
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34744:26)
      at async Object.onBookingPayment (/usr/src/app/dist/services/booking/index.js:472:9)
      at async onPaymentIntentSucceeded (/usr/src/app/dist/webhooks/stripe.js:118:5)
      at async stripeWebhook (/usr/src/app/dist/webhooks/stripe.js:59:13) {
    clientVersion: '2.19.0'
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by janpio** [comment]
Thanks, we seems to have _some_ problem there in relation to Google Cloud's _something_, see the labels I applied to this issue and the issues in there. It has been pretty spotty in the past, but seems to be more present now. We have a hunch that it is about connection management with the Cloud SQL instance, and are working on a fix already - but as we have no real reproduction (which we can reproduce all the time, reliably) this is pretty hard.

**Comment by kevinsimper** [comment]
We have also the same hunch as you @janpio, we have been using Cloud Run for 9 months and only within the last month began sawing this issue. We had some problems upgrading to newest prisma, but we did so yesterday.

There is a case that Google Cloud Run only allows 100 connections to Cloud SQL from Cloud Run. So with Prisma doing 2  connections per container, that is 50 containers. With max-container set 30 we are still seeing Google creating more containers than that.

@janpio Does Prisma try to reconnect the connection if it sees it was closed?

**Comment by kevinsimper** [comment]
> We recommend using a client library that supports connection pools that automatically reconnect broken client connections.
https://cloud.google.com/sql/docs/mysql/connect-run#connection-pools

**Comment by narciero** [comment]
Thanks for the detailed follow up, I will upgrade to 2.20.x and see if we notice any differences.

Our Cloud Run service only has a max instance count of 4 so it's likely due to one of the other issues you mentioned.

Thanks for all the hard work!

**Comment by kladnik** [comment]
Having the same issue with Google App Engine and can confirm that upgrading to `2.20.1` didn't resolve it.

**Comment by Sytten** [comment]
Yes the operation is not retried if the connection fails.

**Comment by kevinsimper** [comment]
Could a quick solution be to set connection_limit=1 and then add a setInterval to do a `SELECT 1;` every 1 minute?

**Comment by Sytten** [comment]
That will limit your performances quite a lot, I don't recommend it. If you are in a serverless environment there is not much you can do at the moment. Non serverless environments should not really this issue.

**Comment by narciero** [comment]
> We are aware of that problem and are working on a fix, part of that fix was released in 2.20 so if you can test that it would be appreciated. To recap for everybody (since it is a complex problem with multiple sources):
> 
> 1. The first issue was that [mobc](https://github.com/importcjj/mobc) (the library managing the pool) didn't have a proper FIFO queue for requests and did not handle returns of connections to the pool properly. This was reported in #5977 and fixed in [importcjj/mobc#53](https://github.com/importcjj/mobc/pull/53). This is part of the 2.20 release.
> 2. Cloud Run uses App Engine under the hood, I had a discussion with a PM of Cloud Run and an engineer here: https://issuetracker.google.com/issues/181655427. Basically the gist that you need to remember is that sockets are closed after 2m. However, prisma by default uses a 5m idle connection lifetime and this is being fixed by [prisma/quaint#267](https://github.com/prisma/quaint/pull/267) (should be in 2.21, didn't have time to work on it for 2.20). Basically, you will be have to set your own lifetime.
> 3. That still leaves us with one last problem, if the connection is bad it will stay in the pool until the next health check of that connection (which happen every 15s). This used to crash the whole engine and was reported in #5976, but in more recent versions in returns an error `Error { kind: Closed, cause: None }`. There an issue tracking a possible solution to that [prisma/quaint#273](https://github.com/prisma/quaint/issues/273) and @pimeys will be working on that.
> 
> As for the connection limit of 100 and the calculation you are doing. From my personal experience, Google allows a surge to go over the limit when deploying a new version of the application. I had some issues on smaller databases (staging) of connection exhaustion. So just be conservative with the upper limit or put a pgbouncer between your instances and the DB (unfortunately there is no managed service for that on Cloud SQL, but aiven has one).

Just to follow up, I am still seeing the issue with prisma `2.20.1` on Google Cloud Run with an instance count of 4.

**Comment by kevinsimper** [comment]
I also updated to newest 2.20.1

I also did "connection_limit=1 and then add a setInterval to do a SELECT 1; every 1 minute", but we are still seeing `Error { kind: Closed, cause: None }` unfortunate.

So even when I am 100% sure that the connection is active at least every minute we are still seeing 1000's of theses cases.

**Comment by Sytten** [comment]
I mean a setInterval on cloud run is a bit useless since the CPU is all but frozen in between calls @kevinsimper.
For other projects I used the [uptime check](https://cloud.google.com/monitoring/uptime-checks) feature to keep my containers warn (cheaper than setting a minimum instance of 1) and you can use that to ping the DB then.
How much load do you have, like I maintain two applications in production and I don't see that many errors even if they do pop-up once in a while.

**Comment by narciero** [comment]
@Sytten I use the uptime check as well on Cloud Run and for an application handling ~5-10k req/day I see at least 10+ of these errors per day.

**Comment by Sytten** [comment]
I pushed the fix for problem 2 today, so next dev build will allow new connections parameters so we can set the idle lifetime to 2m, it should help a bit but won't solve all issues. Problem 3 is still being worked on.

**Comment by kevinsimper** [comment]
If you have enabled Query Insights, this is maybe relevant for you:

I found out through help from Google Cloud Customer support that Query Insights if enabled have crashed databases.

Our logs was showing that our database was `the database system is in recovery mode`

```
resource.type="cloudsql_database"
resource.labels.database_id="XXXX:XXXXX"
severity="ALERT"
```

**Comment by pimeys** [comment]
Ok, so the upcoming update will change the following:
- When a query triggers a closed connection, the connection is marked broken and the query results into `P1017: Server has closed the connection.`
- The caller will get an error for this query, and can decide to either retry, or restart the app (depending on the use-case)
- This specific connection is then never given back from the pool, but thrown away and we'll eventually start a new connection, if needed.

**Comment by kladnik** [comment]
> If you have enabled Query Insights, this is maybe relevant for you:
> 
> I found out through help from Google Cloud Customer support that Query Insights if enabled have crashed databases.
> 
> Our logs was showing that our database was `the database system is in recovery mode`

Wow, this actually solved it. No errors in the past 15h, this will do great until the next update. Thanks!

**Comment by janpio** [comment]
Can you elaborate what you did exactly @kladnik? I might be missing some GCloud context, but would not know what exactly changed how - other people might be in the same position.

**Comment by kladnik** [comment]
I disabled `Query Insights` in Google Cloud SQL database. Just go into DB settings and turn off the settings there (refer to the picture): 
![image](https://user-images.githubusercontent.com/11619663/113997171-2c237f80-9858-11eb-8653-753456e70bbd.png)

You do lose Query monitoring, which does seem like a very nice feature, but not as important as stability. Hopefully with next version I can enable it again.

**Comment by Sytten** [comment]
Since I suspect many here will want to retry on failed connections, I wrote a prisma middleware for that:
```typescript
import { Prisma } from "@prisma/client";

const DEFAULT_MAX_RETRIES = 3;
const DEFAULT_MIN_BACKOFF = 5;
const DEFAILT_MAX_BACKOFF = 30;

type BackoffOptions = {
  min?: number;
  max?: number;
}

type RetryOptions = {
  maxRetries?: number;
  backoff?:
    | boolean
    | BackoffOptions;
};

const sleep = (min: number, max: number) => {
  const ms = Math.floor(Math.random() * (max - min + 1) + min);
  return new Promise((resolve) => setTimeout(resolve, ms));
};

export class PrismaRetryError extends Error {
  constructor() {
    super()
    this.name = 'PrismaRetryError';
  }
}

export const Retry = (options?: RetryOptions): Prisma.Middleware => {
  const maxRetries = options?.maxRetries ?? DEFAULT_MAX_RETRIES;
  const backoff = options?.backoff ?? true;
  const minBackoff = (options?.backoff as BackoffOptions | undefined)?.min ?? DEFAULT_MIN_BACKOFF;
  const maxBackoff = (options?.backoff as BackoffOptions | undefined)?.max ?? DEFAILT_MAX_BACKOFF;
  if (minBackoff > maxBackoff) {
    throw new Error('Minimum backoff must be less than maximum backoff')
  }

  return async (params, next) => {
    let retries = 0;
    do {
      try {
        const result = await next(params);
        return result;
      } catch (err) {
        if (
          err instanceof Prisma.PrismaClientKnownRequestError &&
          err.code === "P1017"
        ) {
          retries += 1;
          if (backoff) {
            await sleep(minBackoff, maxBackoff)
          }
          continue;
        }
        throw err;
      }
    } while (retries < maxRetries);
    throw new PrismaRetryError()
  };
};
```

I tested extensively with the next release (2.21) and it works as expected. @janpio might want to add it somewhere else so other users find it.

You can use it like: 
```typescript
import { Retry } from './retry';
prisma.$use(Retry())
```

**Comment by sievins** [comment]
For those wanting to use @Sytten's [retry middleware solution](https://github.com/prisma/prisma/issues/6329#issuecomment-816954832) using Prisma's extensions:

```ts
import { RetryExtension } from './retry';

prismaClient.$extends(RetryExtension());
```

```ts
import { Prisma } from "@prisma/client";

const DEFAULT_MAX_RETRIES = 3;
const DEFAULT_MIN_BACKOFF = 5;
const DEFAULT_MAX_BACKOFF = 30;

type BackoffOptions = {
  min?: number;
  max?: number;
};

type RetryOptions = {
  maxRetries?: number;
  backoff?: boolean | BackoffOptions;
};

const sleep = (min: number, max: number) => {
  const ms = Math.floor(Math.random() * (max - min + 1) + min);
  return new Promise((resolve) => setTimeout(resolve, ms));
};

export class PrismaRetryError extends Error {
  constructor() {
    super("Prisma retry limit exceeded.");
    this.name = "PrismaRetryError";
  }
}

interface AllOperationsParams<TArgs = unknown, TResult = unknown> {
  args: TArgs;
  query: (args: TArgs) => Promise<TResult>;
}

/**
 * Creates a Prisma client extenstion that will retry the query should it have
 * failed because the DB server closed the connection.
 */
export const RetryExtension = (options?: RetryOptions) => ({
  name: "retry extension",
  query: {
    $allModels: {
      async $allOperations<TArgs = unknown, TResult = unknown>({
        args,
        query,
      }: AllOperationsParams<TArgs, TResult>): Promise<TResult> {
        const maxRetries = options?.maxRetries ?? DEFAULT_MAX_RETRIES;

        const backoff = options?.backoff ?? true;

        const minBackoff =
          // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
          (typeof options?.backoff === "object" && options.backoff.min) ||
          DEFAULT_MIN_BACKOFF;
        const maxBackoff =
          // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
          (typeof options?.backoff === "object" && options.backoff.max) ||
          DEFAULT_MAX_BACKOFF;

        if (minBackoff > maxBackoff) {
          throw new Error("Minimum backoff must be less than maximum backoff");
        }

        let retries = 0;
        do {
          try {
            return await query(args);
          } catch (err) {
            if (
              err instanceof Prisma.PrismaClientKnownRequestError &&
              err.code === "P1017" // Server has closed the connection.
            ) {
              console.warn(
                "Prisma: DB server has closed the connection. Retrying.",
              );
              retries++;
              if (backoff) {
                await sleep(minBackoff, maxBackoff);
              }
              continue;
            }
            throw err;
          }
        } while (retries < maxRetries);
        throw new PrismaRetryError();
      },
    },
  },
});
```

**Comment by yancoltro** [comment]
Sorry, I don't know if it will make sense to comment on this here, but I'm getting this error right now, since I updated from version **5.16.1** to version **6.5.0**

**message**: ```Error in PostgreSQL connection: Error { kind: Closed, cause: None }```
**stackTrace**:   ```
at Object.$c (/var/app/node_modules/@prisma/client/runtime/library.js:21:432)
    at EventEmitter.<anonymous> (/var/app/node_modules/@prisma/client/runtime/library.js:130:4348)
    at EventEmitter.emit (node:events:530:35)
    at Bt.logger (/var/app/node_modules/@prisma/client/runtime/library.js:112:1511)
    at /var/app/node_modules/@prisma/client/runtime/library.js:112:983```


| Name | Version |
| -------- | ------- |
| Node | 22.14.0 |
| Prisma Client | 6.5.0 |
| Database | Aurora PoestgreSQL 16.9 (AWS RDS) |

**Comment by nqnminh** [comment]
I'm using version 6.8.2 and getting the same error on both production and staging.

```prisma:error Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }```

**Comment by allhailcheese** [comment]
Started getting this in production too. Prisma 6.15.0 using prisma-client generator

**Comment by delight-ven** [comment]
reopen this bug please

**Comment by juliussneezer04** [comment]
Facing this too. Prisma 6.16.3 with Cloud Run + Supabase PostgreSQL

**Comment by vamsi80** [comment]
prisma:error Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:error Error in PostgreSQL connection: Error { kind: Closed, cause: None }

can any one help with this error pls
