### ISSUE TITLE
Support for cross-table writes (update & delete)

### ISSUE THREAD

**Issue by supermacro** [prisma/prisma#6342]
## Problem

Our team is looking for somewhat granular access control to our data and we need to implement essentially Row Level Security / "ACLs on a per row basis".

Here's a blog post that I've used heavily for inspiration: 

https://cazzer.medium.com/designing-the-most-performant-row-level-security-strategy-in-postgres-a06084f31945

Our use case is actually quite common:

We have a "regular" user and we have a "super admin" user - both of which access the same data set (let's say `cars` table for this example). 

So both "regular" and "super admin" users use the same app and both want to see a list of cars. 

The difference is that regular users only see cars that they own or are "shared" with them, wheras admins see all cars, irrespective of what relationship they may have with those cars.

In addition, "regular" users will be able to `UPDATE` their own cars, but not the cars that are shared with them (in this case, they only have read access to those cars).

The point being that RBAC on HTTP endpoints isn't sufficient to say whether you can perform an operation or not; there's an additional layer that needs to deal with data ownership and relationships between entities and their corresponding data.

Therefore, I am going down the route of implementing an ACL system ([heavily copied from the aforementioned blog post](https://cazzer.medium.com/designing-the-most-performant-row-level-security-strategy-in-postgres-a06084f31945)) whereby each "protected entity" has a corresponding table that tracks *who* has access to that entity and *to what extent* (read, or read_write).

On reads I need to do `JOINS` such as:

```typescript
const { car } = await prisma.carsRolesAndPermissions.findFirst({
  where: {
    // this is the user id whose car we want to retrieve
    // they may own the car or it may have been shared with them
    user_id: 12345,
    permission: 'read',
  },
  select: {
    car: true,
  }
})
```

Which, works, but it's kind of weird because I need to query via the roles / permissions table to access a row's corresponding car. Not the best UX. But I can't complain.

**The limitation is currently with updates / deletes**: 

I cannot do a `JOIN` such as the above in order to conditionally update a row based on it's associated permissions that live in a referencing table.

The query I need to perform is as follows:

```sql
UPDATE cars
INNER JOIN cars_roles_permissions on cars.id = cars_roles_permissions.car_id
SET (color) values ("red")
WHERE
  cars_roles_permissions.user_id = $uid AND
  cars_roles_permissions = "write"  
```

In MySQL, this is referred to as a [update-join](https://www.mysqltutorial.org/mysql-update-join) and [Postgres has similar functionality](https://www.postgresqltutorial.com/postgresql-update-join/).

## Suggested solution

Extend the `prisma.myModel.update` syntax to allow for relational filters in the `where` field. 

```typescript
prisma.cars.update({
  data: {
    color: 'red',
  },
  where: {
    carsRolesAndPermissions: {
      userId: 12345,
      permission: 'write'
    }
  }
})
```

## Alternatives

Raw sql queries at the moment.

## Additional context

I am using MySQL, soooo if you do end up implementing this, please do it for MySQL first haha 🙂

**Comment by supermacro** [comment]
Here's an example of a cross-table insert:

```sql
START TRANSACTION;
  INSERT INTO case (uid, blah, bleh, bluh) values ($cuid, ....) -- using pre-computed cuid

  INSERT INTO health_case_acls (
    user_id,
    permission,
    case_id
  )
  SELECT
    users.email,
    "ReadWrite",
    $cuid
  FROM users
  JOIN super_admins ON users.email = super_admins.user_id
COMMIT;

```

**Comment by janpio** [comment]
If you are still around @supermacro:
Did you get your approach working?
If so, can you share an example Prisma schema for the cases you mentioned above?

**Comment by supermacro** [comment]
We ended up just "escape-hatching" to using raw-sql. That being said, I would highly advice people from hand-rolling their own ACL system like we did ... not worth it at all!

Better to use a proven tool like Oso: https://www.osohq.com/

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

I'd recommend using https://zenstack.dev/blog/supabase-alternative#aclaccess-control-layer-is-the-core, which uses Prisma under the hood.

---

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
