### ISSUE TITLE
Count property name collision

### ISSUE THREAD

**Issue by Xample** [prisma/prisma#6344]
## Bug description

With the new introduction of count in prisma 2.2.0, I do now have a naming collision on the count property

![image](https://user-images.githubusercontent.com/944605/113196298-9ee29880-9263-11eb-901e-77c42dbbae62.png)

## How to reproduce

make a schema.prisma file with a model having a `count` property

```prisma

model Example {
  id        String                      @id @default(cuid())
  count     Int
}
```

Then generate
```shell
prisma generate
```

## Expected behavior

Since now, I had no conflict with the count. But the new agregation did type the count and creates 2 properties with the same name. I would expect prisma not to have too many reserved properties

## Prisma information

see above

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v15.11.0
- Prisma version:
```
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : darwin
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by Xample** [comment]
The current workaround I am using is to replace my `count` property with `countValue`

**Comment by janpio** [comment]
Similar bug, with reproduction by Daniel: https://github.com/prisma/prisma/issues/6706#issuecomment-824738190

**Comment by matthewmueller** [comment]
Thanks for opening this issue. We fixed this in https://github.com/prisma/prisma/releases/tag/2.23.0.
