### ISSUE TITLE
Please make a macro to derive Prisma schema from Rust structs

### ISSUE THREAD

**Issue by bionicles** [prisma/prisma#6350]
## Problem

I like Rust lately and want to use it. But I also want to use Prisma to migrate the DB. Problem is, then I have two sources of truth on my schema. Both extremely similar purpose. Rust structs and  Prisma schema... this causes maintenance issues (we all know how that can be...)

## Suggested solution

If Prisma had a simple Rust crate with 1 macro, to `#[derive(prisma)]` from structs. It can just loop over the fields and map the rust types onto the prisma types and write them to a file.

Indeed, more ways to codegen Prisma schema from various languages' type systems, would make your project much more compelling

## Alternatives

Suck it up and maintain rust structs for the server, a prisma schema for SQL and typescript types for front end. Yikes

## Additional context
https://doc.rust-lang.org/rust-by-example/custom_types/structs.html
https://doc.rust-lang.org/book/ch19-06-macros.html

**Comment by janpio** [comment]
Hey @bionicles, we don't think this would be a good match for Prisma itself. 

Prisma ORM uses components written in Rust, but that is an internal implementation details. Your request might be better suited as a standalone project (which might or might not user any of our internal API from prisma-engines) or maybe as part of a custom client, like e.g. [Prisma Client Rust](https://prisma.brendonovich.dev/).

I am closing this issue now to signal that we are not considering building this. Thanks for opening it though!
