### ISSUE TITLE
Prisma.upsert() should support the value of null in where condition.

### ISSUE THREAD

**Issue by xuqingkuang** [prisma/prisma#6359]
## Bug description
Prisma supports creating the nullable value for the table, but not support the null value in where condition of `upsert()` method.

## How to reproduce
I wrote a simple reproducible example - https://github.com/xuqingkuang/prisma-null-foreignkey

Please follow the README.

## Expected behavior

upsert() accepts a null input as an option value.

## Environment & setup

- OS: CentOS 8
- Database: MySQL and Sqlite
- Node.js version: v14.15.4
- Prisma version:
```
❯ npx prisma -v
Environment variables loaded from .env
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : rhel-openssl-1.1.x
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/query-engine-rhel-openssl-1.1.x)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/migration-engine-rhel-openssl-1.1.x)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.1.x)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/prisma-fmt-rhel-openssl-1.1.x)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by matthewmueller** [comment]
Hey @xuqingkuang thanks for the detailed reproduction. This is working as designed, but we may want to revisit the design. It's a bit of a larger topic unfortunately.

For now, you may need to use `$queryRaw` or a 2-3 queries in your application for now. We'll have a closer look though.

**Comment by xuqingkuang** [comment]
> Hey @xuqingkuang thanks for the detailed reproduction. This is working as designed, but we may want to revisit the design. It's a bit of a larger topic unfortunately.
> 
> For now, you may need to use `$queryRaw` or a 2-3 queries in your application for now. We'll have a closer look though.

Sure, I use a 0 instead of null and dropped the foreign key for a workaround, but still looking forward to the issue will be fixed.

**Comment by dpetrick** [comment]
That is entirely by design. Prisma has 2 core query concepts: Operate on a list of records or operate on a single record. Upsert falls into the single record category with the semantics being: "Find a single record and if that record exists, update it with the provided data, else create it with the provided data". We categorize it strictly like that because a narrow definition allows us to implement queries without considering a larger class of edge cases that introduce uncertain behavior into Prisma.

So, to implement upsert we need to pin exactly one record in the database. IDs and uniques are the to do that in Prisma, any other (non-unique) condition would potentially result in a list of records and it is not clear which record to update (or update all, which breaks the semantics of the operation). Sidenote: "The first one" is also not acceptable because without an explicit ordering, there's no guarantee that the first one is always the first one, among other edge cases.

Now the question is why we allow `@@unique` on nullable fields - that's an SQL tradeoff we made so far. Your unique index in SQL is (in most cases) not really "unique" as we'd intuitively understand it, because you can totally have two identical `title`s with NULL as the `authorId` in the row (because in SQL, NULL != NULL, that's why). However, the construct is so common  that we had to include it, but as the interface _requires_ you to find exactly one, we must require the input field and can't accept null values, which is why there's a deviation.

We may consider loosening restrictions in the future, but we will only do so after careful consideration when we are absolutely sure we understand all the use cases and problems it introduces.

**Comment by matthewmueller** [comment]
@ahathaway are you able to workaround this issue using the method @xuqingkuang described?

**Comment by Jolg42** [comment]
Can reproduce with provided repo.
Using our internal dev version `4.4.0-dev.25` the error changes for `========== Prisma.upsert with null error: ==========`
Full logs:
```
> prisma-null-foreignkey@1.0.0 start /Users/j42/Repros/prisma-null-foreignkey
> ts-node ./src/index.ts

========== One books should exist  ==========
[
  {
    id: 1,
    title: 'The Old Man and the Sea',
    authorId: null,
    author: null
  }
]
========== Two books should exist  ==========
[
  {
    id: 1,
    title: 'The Old Man and the Sea',
    authorId: null,
    author: null
  },
  { id: 2, title: 'A Farewell to Arms', authorId: null, author: null }
]
========== Prisma.upsert with null error: ==========
PrismaClientKnownRequestError

Invalid `prismaClient.book.upsert()` invocation in
/Users/j42/Repros/prisma-null-foreignkey/src/index.ts:53:31

  50 {
  51   const title = "For Whom the Bell Tolls";
  52   try {
→ 53     await prismaClient.book.upsert(
Missing a required value at `Mutation.upsertOneBook.where.BookWhereUniqueInput.title_authorId.BookTitleAuthorIdCompoundUniqueInput.authorId`
Error: 
Invalid `prismaClient.book.upsert()` invocation in
/Users/j42/Repros/prisma-null-foreignkey/src/index.ts:53:31

  50 {
  51   const title = "For Whom the Bell Tolls";
  52   try {
→ 53     await prismaClient.book.upsert(
Missing a required value at `Mutation.upsertOneBook.where.BookWhereUniqueInput.title_authorId.BookTitleAuthorIdCompoundUniqueInput.authorId`
    at RequestHandler.handleRequestError (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:30850:13)
    at RequestHandler.request (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:30833:12)
    at PrismaClient._request (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:31805:16)
========== Prisma.upsert with non-exists foreign got foreign key constraint error ==========
PrismaClientKnownRequestError

Invalid `prismaClient.book.upsert()` invocation in
/Users/j42/Repros/prisma-null-foreignkey/src/index.ts:80:31

  77 {
  78   try {
  79     const title = "For Whom the Bell Tolls";
→ 80     await prismaClient.book.upsert(
Foreign key constraint failed on the field: `foreign key`
Error: 
Invalid `prismaClient.book.upsert()` invocation in
/Users/j42/Repros/prisma-null-foreignkey/src/index.ts:80:31

  77 {
  78   try {
  79     const title = "For Whom the Bell Tolls";
→ 80     await prismaClient.book.upsert(
Foreign key constraint failed on the field: `foreign key`
    at RequestHandler.handleRequestError (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:30850:13)
    at RequestHandler.request (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:30833:12)
    at PrismaClient._request (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:31805:16)
```

Before
```
========== Prisma.upsert with null error: ==========
PrismaClientValidationError

Invalid `prisma.book.upsert()` invocation:

{
  where: {
    title_authorId: {
      title: 'For Whom the Bell Tolls',
      authorId: null
                ~~~~
    }
  },
  update: {},
  create: {
    title: 'For Whom the Bell Tolls',
    authorId: null
  }
}

Argument authorId: Got invalid value null on prisma.upsertOneBook. Provided null, expected Int.


Error: 
Invalid `prisma.book.upsert()` invocation:

{
  where: {
    title_authorId: {
      title: 'For Whom the Bell Tolls',
      authorId: null
                ~~~~
    }
  },
  update: {},
  create: {
    title: 'For Whom the Bell Tolls',
    authorId: null
  }
}

Argument authorId: Got invalid value null on prisma.upsertOneBook. Provided null, expected Int.


    at Document.validate (/home/xqkuang/github/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:32548:19)
    at NewPrismaClient._executeRequest (/home/xqkuang/github/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:34481:17)
    at /home/xqkuang/github/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:34416:52
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (/home/xqkuang/github/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:34416:25)
    at Object.then (/home/xqkuang/github/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:34536:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

After
```
========== Prisma.upsert with null error: ==========
PrismaClientKnownRequestError

Invalid `prismaClient.book.upsert()` invocation in
/Users/j42/Repros/prisma-null-foreignkey/src/index.ts:53:31

  50 {
  51   const title = "For Whom the Bell Tolls";
  52   try {
→ 53     await prismaClient.book.upsert(
Missing a required value at `Mutation.upsertOneBook.where.BookWhereUniqueInput.title_authorId.BookTitleAuthorIdCompoundUniqueInput.authorId`
Error: 
Invalid `prismaClient.book.upsert()` invocation in
/Users/j42/Repros/prisma-null-foreignkey/src/index.ts:53:31

  50 {
  51   const title = "For Whom the Bell Tolls";
  52   try {
→ 53     await prismaClient.book.upsert(
Missing a required value at `Mutation.upsertOneBook.where.BookWhereUniqueInput.title_authorId.BookTitleAuthorIdCompoundUniqueInput.authorId`
    at RequestHandler.handleRequestError (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:30850:13)
    at RequestHandler.request (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:30833:12)
    at PrismaClient._request (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:31805:16)
```

Type Error
<img width="566" alt="Screenshot 2022-09-06 at 12 35 38" src="https://user-images.githubusercontent.com/1328733/188614179-a19689ff-9add-445a-9e77-59ea3013ac35.png">

**Comment by heyask** [comment]
I want to find records that don't have field.
In mongodb, there is `$exists` operator which is `{ field: { $exists: <boolean> } }`.
but in prisma, `{ fieldName: { equals: null } }` does not find records don't have field. 
but `{ fieldName: { not: null } }` condition find records have field.

**Comment by MarieMinasyan** [comment]
Hello,
I have a use case with a unique constraint on 3 columns, one of which is nullable.
With the unique constraint, I still have only one record where the first two columns have specific values and the third one is null.
I'd like to be able to upsert into my table with:
```
where:
   {
       firstColumn_secondColumn_thirdColumn: {
           firstColumn: "value",
           secondColumn: "value",
           thirdColumn: null,
       }
   }
```
Is there a way to do this?
Thanks you.

**Comment by Jolg42** [comment]
@MarieMinasyan could you open a discussion [here](https://github.com/prisma/prisma/discussions)?
Because this issue is closed for a long time now.

**Comment by ctoma** [comment]
Personally I don't think that Prisma should be gatekeeping what is perfectly valid SQL. It's up to the user to decide if it suits their use case or not.

This stance is also more puzzling given that Postgres 15 brings `NULLS NOT DISTINCT` which eliminates entirely the "problem". 

Could someone from the Prisma team take a look at this again/consider reopening the issue? @garrensmith
