### ISSUE TITLE
Migrate: If DB password contains an @-symbol, part of the password is printed in migrate log

### ISSUE THREAD

**Issue by radicand** [prisma/prisma#6362]
I'm using migrate with a database that has the @-symbol as part of the password - as a result, the connection string has two @'s. This is valid, and works fine.

I noticed today however that when I execute migrations, part of the printed log looks like the below. Assume the password is `lulz@truncated-password-here` for sake of demonstration, and a full connection string would be similar to: `mysql://user-name:lulz@truncated-password-here@database-host-here:database-port-here`

```
Datasource "db": MySQL database "database_name_here" at "truncated-password-here@database-host-here:database-port-here"
```

I believe the platform is chopping off at the first `@`, when in fact it should chop at the last `@` instead.

**Comment by janpio** [comment]
Special characters in passwords need to be encoded here - that probably includes `@` similar to `#`. @tomhoule can probably provide a link to how exactly the encoding needs to look like.

**Comment by tomhoule** [comment]
There are two separate issues at play:

- The `@` character does need to be url-encoded. I don't have a specific tutorial/reference document to recommend, but there are a variety of resources. `@` would be encoded as `%40`. We could treat this as first issue about ergonomics.
- The parser used by the Typescript CLI parses that without throwing and leaks passwords in the process. This is the more serious issue.

**Comment by tomhoule** [comment]
Fixed by https://github.com/prisma/prisma/pull/6546
