### ISSUE TITLE
[Sql Azure] migrate gets stuck without a shadow DB

### ISSUE THREAD

**Issue by luisrudge** [prisma/prisma#6371]
## Bug description

When I use prisma migrate with SQL Azure, the command gets stuck.

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/941075/113338381-6a241f00-92ff-11eb-9971-644bf82ee44c.png">

It also tries to create a database on SQL Azure, which might cause all sorts of issues (including billing) for people that don't know what's going on.

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/941075/113338699-d4d55a80-92ff-11eb-8bd7-5ac8f88b5683.png">

## How to reproduce

- `npx prisma migrate dev --name init`

## Expected behavior

A migration is created and applied. If there's an error, I should see a clear message on what went wrong.

## Fix

In order to fix this, one has to use the [Shadow Database](https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database) configuration to make it work.

## Prisma information

```prisma
datasource db {
  provider          = "sqlserver"
  url               = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["microsoftSqlServer"]
}

model User {
  id              Int       @id @default(autoincrement())
  createdAt       DateTime  @default(now())
  updatedAt       DateTime  @updatedAt
  name            String
  }
```

## Environment & setup

```
Environment variables loaded from .env
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : darwin
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
Preview Features     : microsoftSqlServer
```

**Comment by luisrudge** [comment]
Hi, friends. Just so you know how critical this is, I got my billing for the last period...
![image](https://user-images.githubusercontent.com/941075/113589852-42d39780-9608-11eb-85b3-dc96abf77a07.png)

Because I didn't know what was happening, I only looked at my resource group after 1 or 2 hours since I started playing with prisma, that's when I saw all the databases created. I didn't pay too much attention, because I imagined they'd be created in the same 'database plan' that I had my original database (Basic, $6/mo).

But, when I saw the costs associated with the databases, I realized that they're probably using the default Azure plan for databases, which is almost $600/mo.

**cost of databases created**
![image](https://user-images.githubusercontent.com/941075/113590104-9a720300-9608-11eb-8ffc-0c814973a5ad.png)

**default azure database plan**
![image](https://user-images.githubusercontent.com/941075/113590115-a067e400-9608-11eb-9e5b-bea59f0939dd.png)
![image](https://user-images.githubusercontent.com/941075/113590132-a5c52e80-9608-11eb-8e2d-27e364c7c27d.png)

**Comment by pantharshit00** [comment]
I wasn't able to reproduce it getting stuck but yes creating new database without consent on azure is a problem as you are billed per database, not the by database server on azure. 

I think we can add a warning for azure which will warn the user about this. We can do this my check for `windows.net` in the hostname.

**Comment by tomhoule** [comment]
@luisrudge Sorry for the delay in working on this. I checked the code, and it looks like we already return a hard error when we fail to clean up a database that was created in `prisma migrate dev`. Can you confirm that it's possible you could have missed the error messages? If it failed silently, it's definitely a problem that we have do dig deeper into. Thanks for reporting this.

**Comment by luisrudge** [comment]
@tomhoule Hi, Tom. This is exactly what my terminal was showing:
![](https://user-images.githubusercontent.com/941075/113338381-6a241f00-92ff-11eb-9971-644bf82ee44c.png)

There were no extra messages

**Comment by luisrudge** [comment]
@tomhoule Great, thanks! I think the most important part is: don't create any resource without asking for approval 😬 if that means failing fast, perfect. I think the issue here is that you assume we're running on a regular sql server, so creating a new database is free. But, in SQL Azure, the create database operation actually creates an Azure SQL Database, which is paid. Even worse: Azure uses the default database plan, which is crazy expensive 😝

**Comment by tomhoule** [comment]
I agree this Azure behaviour is terrible and we should try to protect prisma users from it, but we'll have to find a way to do this without compromising the experience in the majority case where creating a shadow database is perfectly fine or not possible at all.

**Comment by luisrudge** [comment]
@tomhoule Absolutely! I think all Azure Sql Databases are hosted under `MYDB.database.windows.net`, so maybe you could check for that? Just an idea, of course.

**Comment by tomhoule** [comment]
@luisrudge I went with your suggestion of checking the host in this PR: https://github.com/prisma/prisma-engines/pull/1964 — it's a small change so it will probably make it in tomorrow's release, and it can then be tested in the field. We should still investigate why prisma gets stuck on Azure SQL, but it's probably a bit harder to fix.
