### ISSUE TITLE
Decimal value stored in MySql DB with floating point error

### ISSUE THREAD

**Issue by unimatrix27** [prisma/prisma#6381]
## Bug description

Decimal value stored with floating point error in mysqldb. Using a DECIMAL(20,10) field type in mysql and inserting the value 607013.31, in fact 607013.3100000001 is inserted. Checked the mysql logs and the error is already in the INSERT statement generated by prisma

## How to reproduce

`git clone https://github.com/unimatrix27/prismaissue`
`cd prismaissue`
`docker-compose up`

This demo repo is a minimal environemt to demonstrate only this bug. Using docker-compose it sets up a mysql server, creates the demotable and runs NODE with the demoapp to show the bug

## Expected behavior

The decimal value should be stored without floating point issues

## Prisma information

prisma version 2.20, introspected DB, simplistic demo environment with no other code

## Environment & setup

- OS: Docker NODE:15
- Database: MySql 5.7 (also tested 8.0)
- Node.js 15
- Prisma version: 2.20

```
const { PrismaClient } = require('@prisma/client')
var prisma =  new PrismaClient({ log: ['query', 'info', 'warn'] })
    
var enterTestData = prisma.demotable.create({
  data: {demofield: 607013.31}
    }).then(r => {
        console.log(r.demofield)
        // this console.log results in 607013.3100000001
    }
)
```

```
model demotable {
  id        Int      @id @default(autoincrement()) @db.UnsignedInt
  demofield Decimal? @db.Decimal(20, 10)
}
```
#6284

**Comment by janpio** [comment]
Can you try with latest Prisma to make sure this is not fixed yet? Thanks.

**Comment by unimatrix27** [comment]
upgraded to 2.20 also in the test repo, same result

**Comment by eemelipa** [comment]
Might be same issue as in https://github.com/prisma/prisma/issues/5925

**Comment by pantharshit00** [comment]
I can reproduce. Since value is different will mark this as separate bug for now as might be a different conversion bug.

**Comment by pimeys** [comment]
So, conversions between Decimal and 64-bit floating point values are not very stable. Especially with arbitrary precision, the result you get here is by the book correct, but probably not really what you want. Now, you have some ways to move forward from here, let me show some example code for you:

```javascript
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({
    log: ['query', 'info', 'warn', 'error']
})

async function main() {
    const firstRound = await prisma.demotable.create({
        data: {dec: 607013.31, flo: 607013.31}
    });

    console.log(firstRound); // dec: 607013.3100000001, flo: 607013.31

    const secondRound = await prisma.demotable.create({
        data: {dec: "607013.31", flo: 607013.31}
    });

    console.log(secondRound); // dec: 607013.31, flo: 607013.31
}

main()
    .catch((e) => {
        throw e
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
```

See what I did there? Here's the data model:

```prisma
model demotable {
  id        Int      @id @default(autoincrement()) @db.UnsignedInt
  dec       Decimal? @db.Decimal(20, 10)
  flo       Float?
}
```

Summarizing: if using decimal in the database, try not to convert from or to a floating point. String to decimal is stable and should not cause rounding errors. There's a thing we could do is to convert the given float to string first, then to decimal. This would get rid of the error here, and might introduce another one with another float elsewhere. And adding one more layer of conversions! So either switch to a double on MySQL, or pass your decimals as strings down the pipe.

**Comment by unimatrix27** [comment]
thanks for this feedack. for my usecase its actually possible to avoid numbers and just convert from string so this already helps me a lot

**Comment by pimeys** [comment]
This is still super confusing. We're having a meeting about floatish values tomorrow, hopefully we make it simpler to use in the future.

You're not the first one having trouble... :)
