### ISSUE TITLE
Migrate: @dbgenerated with @db.Time(0) keeps generating new migrations

### ISSUE THREAD

**Issue by daniellwdb** [prisma/prisma#6382]
## Bug description

Whenever you use a schema field decorated with `DateTime  @default(dbgenerated("\"00:00:00\"")) @db.Time(0)` and run `npx prisma migrate dev`, you are asked for a new migration name but the generated migration is always the same

## How to reproduce

Create a model
```
model A {
  id      Int       @id @default(autoincrement()) @db.UnsignedInt
  from    DateTime  @default(dbgenerated("\"00:00:00\"")) @db.Time(0)
}
```
Run `npx prisma migrate dev`, after that another time, it keeps asking for a new migration name

## Expected behavior

There should be no prompt for a new migration since the output is always the same

## Environment & setup

- OS: Windows (WSL2, Ubuntu 20.04)
- Database: MySQL 8
- Node.js version: v15.12.0
- Prisma version: 

```
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by tomhoule** [comment]
Thanks for reporting this! We'll work on it as soon as possible.

**Comment by simonv3** [comment]
I'm still seeing this in prisma 5

The schema line:

```
  emailConfirmationExpiration         DateTime?                @default(dbgenerated("NOW() + interval '10 min'"))
```

and the generated migration

```
-- AlterTable
ALTER TABLE "User" ALTER COLUMN "emailConfirmationExpiration" SET DEFAULT NOW() + interval '10 min';
```

Is included in every migration and also creates a migration if there are no other changes

**Comment by janpio** [comment]
Open a new issue then please and include all the information the issue template asks for. Thank you.
