### ISSUE TITLE
Timestamp with Timezone (`@db.Timestamptz`) in PostgreSQL Returns Incorrect Time Offset

### ISSUE THREAD

**Issue by rahadi23** [prisma/prisma#6384]
## Bug description

PostgreSQL has an ability to store timestamp with timezone offset, e.g. 2021-04-02T20:10:00+07:00 (or 2021-04-02T13:10:00+00:00). In prisma, we set the field as `@db.Timestamptz`. Using `create()`, I was able to insert the timestamp correctly although it will be converted to +00:00 offset by prisma. So when I do:

```
prisma.myTable.create({
  data: {
    id: 1,
    user_id: 1234321,
    timestamp: new Date(); // 2021-04-02T20:10:00+07:00 since the server timezone is set to +07:00
  }
})
```

It will be stored as follows:

| id | user_id | timestamp |
| -- | -- | -- |
| 1 | 1234321 | 2021-04-02T13:10:00+00:00 |

Which is actually fine since the stored timestamp is equivalent, although I prefer to be able to set prisma to always store it to the database in +07:00 offset.

Since the field is a timestamp with timezone offset, I can manually insert this value just fine to the database:

`INSERT INTO my_table(id, user_id, timestamp) VALUES (2, 1234321, '2021-04-02T20:10:00+07:00')`

but this time, it will be stored by PostgreSQL in +07:00 offset. Thus the table becomes:

| id | user_id | timestamp |
| -- | -- | -- |
| 1 | 1234321 | 2021-04-02T13:10:00+00:00 |
| 2 | 1234321 | 2021-04-02T20:10:00+07:00 |

However, things started to go wrong when I am trying to get these fields. Thus, when I do:

```
prisma.myTable.findMany({
  where: {
    user_id: 1234321
  }
})
```

The returned data will be as follows:

```
[
  {
    id: 1,
    user_id: 1234321,
    timestamp: '2021-04-02T13:10:00Z'
  },
  {
    id: 2,
    user_id: 1234321,
    timestamp: '2021-04-02T20:10:00Z'
  }
]
```

The first row, which is stored in the database with +00:00 offset, returned correctly as `2021-04-02T13:10:00Z`. But the problem happened in the second row, as the timestamp will be returned as `2021-04-02T20:10:00Z`, despite it is stored in the database with +07:00 offset. It should be returned as `2021-04-02T20:10:00+07:00` or, at least `2021-04-02T13:10:00Z`.

## How to reproduce

1. Create a table with `@db.Timestamptz`
2. Insert a row using `create()`
3. Insert a row manually with another timezone offset, e.g. +07:00
4. Get the data using `findMany()`

## Expected behavior

Returns the timestamp fields in the correct value and offset

## Prisma information

```
model MyTable {
  id         Int       @id @db.Integer
  user_id    Int       @db.Integer
  timestamp  DateTime @default(now()) @db.Timestamptz

  @@map("my_table")
}
```

## Environment & setup

- OS:  Ubuntu
- Database:  PostgreSQL 11
- Node.js version:  v14.16.0
- Prisma version:

```
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : linux-musl
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/query-engine-linux-musl)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/prisma-fmt-linux-musl)
Studio               : 0.358.0
Preview Features     : createMany
```

**Comment by matthewmueller** [comment]
This for opening this issue. This looks eerily similar to https://github.com/prisma/prisma/issues/5051#issuecomment-783495269 but for Postgres

**Comment by rahadi23** [comment]
@matthewmueller, thanks for the reply. Yes it looks similar to the issue you mentioned. I am aware and also looked into that issue before opening this issue. However, there is a slighty different problem I wanted to highlight.

In MySQL, there is no way to set the time stored in a different timezone for each row. For example, if the server is set to have an offset of +7, it applies for all rows. Whereas in PostgreSQL, there is an ability to set the time offset explicitly for each row with `timestamp with timezone`. So we are able to store, for example timestamp with -1 offset and +7 offset simultaneously.

With that in mind, I think that prisma should also accomodate such behavior of PostgreSQL, that is to read the timestamp with its timezone and return it correctly.

As for now, if I store a timestamp with an offset rather than UTC, prisma will always treat the value and return it as UTC time regardless of the offset.

| Stored value | Expected return from prisma query | Currently returned value | Correct? |
|---|---|---|---|
| 2021-04-14T14:04Z | 2021-04-14T14:04Z | 2021-04-14T14:04Z | Yes |
| 2021-04-14T21:04+07:00 | 2021-04-14T21:04+07:00 or 2021-04-14T14:04Z | 2021-04-14T21:04Z | No |

I hope I explain this issue clearly and hopefully it can be addressed in the near future. Thanks.

**Comment by pantharshit00** [comment]
This is reproducible in latest dev version `2.22.0-dev.13` and Postgres 12 instance.

**Comment by dpetrick** [comment]
I tried Pg 10 - 12 and wasn't able to reproduce the issue. In fact, when I insert the second row manually in SQL exactly like you described it PG stores it as UTC, so the +7 (or +2 in my case) doesn't show up on the second row and it's directly converted.

Now there might be a number of reasons why that is the case. I used the unaltered postgres docker containers for testing, which are UTC configured by default (confirmed with `SHOW TIMEZONE`). I changed the Timezone on the container to +7 and retried everything. 

After inserting with `create` and the manual create, I had the following:
```
 id | user_id |         timestamp
----+---------+----------------------------
  1 | 1234321 | 2021-04-22 18:44:15.311+07
  2 | 1234321 | 2021-04-02 20:10:00+07
```

That looks correct. Prisma also returned these correctly:
```
    {
        "id": 1,
        "timestamp": "2021-04-22T11:44:15.311Z"
      },
      {
        "id": 2,
        "timestamp": "2021-04-02T13:10:00.000Z"
      }
```

Now, what happens if I insert something in a timezone the server isn't configured in manually?
`INSERT INTO my_table(id, user_id, timestamp) VALUES (3, 1234321, '2021-04-02T20:10:00+04:00');`
```
 id | user_id |         timestamp
----+---------+----------------------------
  1 | 1234321 | 2021-04-22 18:44:15.311+07
  4 | 1234321 | 2021-04-02 20:10:00+07
  3 | 1234321 | 2021-04-02 23:10:00+07
```

This also looks correct, both displayed in PG and returned in Prisma:
```
    {
        "id": 3,
        "timestamp": "2021-04-02T16:10:00.000Z"
      }
```

I probably missed something or didn't think of something obvious. Maybe you can retry/retrace these exact steps, checking your timezone in between on server, PG instance.

**Comment by pantharshit00** [comment]
@rahadi23 Can you please read the above comment and retry this?

**Comment by rahadi23** [comment]
@pantharshit00 After doing some rechecking, turns out there was timezone configuration difference between node and postgres instance in my current environment.

I used `node:14-alpine` image to deploy my apps and left the container's timezone to its default as UTC. Whereas the postgres instance was running locally in my machine (not a container) that had +07 timezone.

This is clearly something I didn't consider upon deployment and didn't think that this can lead to such an issue. So the (temporary/permanent?) solution for now I think is just match the machine's and container's timezone. I'm sorry for this if this is a silly mistake coming from me.

I think this issue doesn't seem to be a bug anymore, but more like a deployment notes and it is probably nice to have it in the documentation.

**Comment by pantharshit00** [comment]
I am going to close in that case.
