### ISSUE TITLE
`outputDir.endsWith` is not a function

### ISSUE THREAD

**Issue by ecpark-danbi** [prisma/prisma#6394]
https://github.com/prisma/prisma/blob/8ec737432ef8db46b26cb9eed14916d5329f6125/src/packages/client/src/generation/generateClient.ts#L112

Error in `generate`

I checked `outputDir` is not a string, an object type.

`outputDir` was 
```ts
{
  value: '...myproject/node_modules/@prisma/client',
  fromEnvVar: null
}
```

Am I the only one getting this error?

**Comment by ecpark-danbi** [comment]
I found in `src/packages/client/src/generator.ts`

```
      // CLI versions < 2.20.0 still send a string
      // CLIs >= 2.20.0 send an `EnvValue`
```

CLI version and client one should be matched.

```json
{
  "dependencies": {
    "@prisma/client": "^2.20.1"
   },
  "devDependencies": {
    "prisma": "2.20.1"
  }
}
```

**Comment by janpio** [comment]
This is indeed true, and something we should improve upon. I created an issue: https://github.com/prisma/prisma/issues/6535
