### ISSUE TITLE
@prisma/migrate 2.20.0 and 2.20.1 depend on 0.0.0 versions of other Prisma packages

### ISSUE THREAD

**Issue by mitchellhamilton** [prisma/prisma#6422]
## Bug description

@prisma/migrate depends on 0.0.0 versions of @prisma/debug and @prisma/get-platform.

## How to reproduce

See the dependencies at https://unpkg.com/browse/@prisma/migrate@2.20.1/package.json

## Expected behavior

@prisma/migrate should depend on the correct versions of the other Prisma packages

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version: 2.20.0 and 2.20.1

```
prisma               : 2.20.0
@prisma/client       : 2.20.0
Current platform     : darwin
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by timsuchanek** [comment]
Thanks for reporting @mitchellhamilton! We just released a @prisma/migrate@2.20.2 with [the correct dependency versions](https://unpkg.com/browse/@prisma/migrate@2.20.2/package.json).
