### ISSUE TITLE
Improve error on default values when `@db.ObjectId` isn't present

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#6429]
_(MongoDB is not publicly available yet. This issue is for the development build.)_

## Problem

Given the following Prisma Schema

```prisma
datasource db {
  provider = "mongodb"
  url      = "mongodb://localhost:27017/mydb"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    String @id @default(dbgenerated("")) @map("_id")
  email String @unique
}
```

This is a valid schema according to `prisma validate`:

```sh
$ prisma validate --schema client/fixtures/mongo/prisma/schema.prisma 
Prisma schema loaded from client/fixtures/mongo/prisma/schema.prisma
The schema at client/fixtures/mongo/prisma/schema.prisma is valid 🚀
```

Unfortunately, when you run the following:

```ts
import { PrismaClient } from './@prisma/client'

const client = new PrismaClient()

async function main() {
  console.time('connect')
  await client.$connect()
  console.timeEnd('connect')
  console.time('create')
  const user = await client.user.create({
    data: {
      email: 'max@gmail.com',
    },
  })
  console.log(user)
  console.timeEnd('create')
}

main()
  .catch(console.error)
  .finally(() => client.$disconnect())
```

You get the following error:

```sh
$ DEBUG=prisma:client ts-node index.ts 
  prisma:client clientVersion: local +0ms
connect: 149.264ms
  prisma:client Prisma Client call: +183ms
  prisma:client prisma.user.create({
  prisma:client   data: {
  prisma:client     email: 'max@gmail.com'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   createOneUser(data: {
  prisma:client     email: "max@gmail.com"
  prisma:client   }) {
  prisma:client     id
  prisma:client     email
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client Error: Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.
  prisma:client     at NodeEngine.graphQLToJSError (/Users/m/dev/src/github.com/prisma/prisma/src/packages/engine-core/src/NodeEngine.ts:1184:12)
  prisma:client     at NodeEngine.request (/Users/m/dev/src/github.com/prisma/prisma/src/packages/engine-core/src/NodeEngine.ts:963:22)
  prisma:client     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  prisma:client     at cb (/Users/m/dev/src/github.com/prisma/prisma/src/packages/client/src/runtime/getPrismaClient.ts:1542:26)
  prisma:client     at main (/Users/m/dev/src/github.com/prisma/prisma/src/packages/client/fixtures/mongo/index.ts:10:16) +38ms
PrismaClientUnknownRequestError: 
Invalid `prisma.user.create()` invocation:


  Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.
    at cb (/Users/m/dev/src/github.com/prisma/prisma/src/packages/client/src/runtime/getPrismaClient.ts:1595:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at main (/Users/m/dev/src/github.com/prisma/prisma/src/packages/client/fixtures/mongo/index.ts:10:16) {
  clientVersion: 'local'
}
```

## Suggested Solution

We validate that you need `@db.ObjectId` and don't allow a generated client in this state or provide a better error informing users to supply `@db.ObjectId`.

**Comment by xdave** [comment]
I've been using plain strings as primary keys ("_id") in mongodb for quite some time, so I would prefer if we didn't force the use of ObjectID. You can technically put anything you want in that field.

**Comment by dpetrick** [comment]
At first I was unsure why that's the case, as in theory the ID get's returned on create just fine. However, the issue is not the create operation, it's the subsequent read required by the createOne operation. All the query core has after the create is for example a String of "608197d600f21c5d0085e524". Querying with that string to retrieve the record after the write completed will fail because the driver needs to know that it's a Bson ObjectID, not a string. Querying with a string will not return anything, because there's no document with a Bson::String ID.

That's a tough one to validate. The best one I can think of is to require a native type annotation on `@id` db generates, but that may have hidden edge cases.

**Comment by janpio** [comment]
Note: Unclear if this can really be validated as an error, or if a similar schema to OP could actually be a valid case:

```prisma
model User {
  id    String @id @default("") @map("_id")
  email String @unique
}
```

As long as a custom id is provided on create, everything would probably be fine.

**Comment by pimeys** [comment]
The schema in the original message validates:

![2022-02-11_13-02-1644584394](https://user-images.githubusercontent.com/34967/153595813-d1574a34-0ef8-4a8e-8f20-a64c343b39a3.png)

So let's try again with `auto()`:

![2022-02-11_14-02-1644584420](https://user-images.githubusercontent.com/34967/153595853-aaee6753-4e1c-4eee-bd86-5dbf60cf9e2d.png)

This was fixed a while ago when we switched to `auto()` from `dbgenerated()`.
