### ISSUE TITLE
Fail on usage of outdated/wrong preview feature flags

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6443]
Right now an outdated, misspelled or wrong preview feature flag is just ignored by Prisma Client. It would be good to have a way (e.g. an env var `PRISMA_VALIDATE_PREVIEW_FEATURE_FLAGS` or similar) to activate a mode that fails on usage of a currently invalid preview feature flag. 

We could use that in examples and e2e tests, to make sure we are not documenting and showing outdated preview feature flags that users copy without knowing why. With the removal of a feature flag, code that is still using them would fail and could be fixed (when also using that env var).

Internal discussion: https://prisma-company.slack.com/archives/C016KUHB1R6/p1617042259141200

**Comment by janpio** [comment]
Maybe not actually required?

```
Get config 
error: The preview feature "foo" is not known. Expected one of: microsoftSqlServer, orderByRelation, napi, selectRelationCount
  -->  schema.prisma:8
   | 
 7 |     provider        = "prisma-client-js"
 8 |     previewFeatures = ["foo"]
   | 

Validation Error Count: 1
```

**Comment by matthewmueller** [comment]
Next Steps:

- See if this will be solved by @dpetrick's feature flag consolidation PR

**Comment by dpetrick** [comment]
Depending on what @janpio expects to happen here, this may be closed. Can you check with the latest version?

**Comment by janpio** [comment]
Of course.

Confirmed for https://github.com/prisma/prisma-examples/blob/latest/databases/sql-server/prisma/schema.prisma, which uses the outdated `connectOrCreate`.

```
codespace ➜ /workspaces/prisma-examples/databases/sql-server (dev) $ npx prisma generate
Prisma schema loaded from prisma/schema.prisma
warn Preview feature "connectOrCreate" is deprecated. The functionality can be used without specifying it as a preview feature.
info The preview flag "connectOrCreate" is not needed anymore, please remove it from your schema.prisma
```

So I have no way to make any tests for this project fail, triggering me to remove the outdated feature flag and make sure our examples are clean and do not show outdated stuff.

(For the case of an invalid feature flag `foo` I get a validation error - see https://github.com/prisma/prisma/issues/6443#issuecomment-814819880 - so that is covered)

As we do not want to change this behavior for all users (as that would make removing a feature flag a breaking change for their projets), I suggest we add an ENV var that can make this an outdated feature flag a validation error. We would then use that env var in our e2e tests and examples to enforce that we clean up these projects properly.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
