### ISSUE TITLE
DB_URL not found when adding sslmode

### ISSUE THREAD

**Issue by rvlewerissa** [prisma/prisma#6457]
## Bug description

I received the following error when running `prisma migrate deploy`:
```
Prisma schema loaded from prisma/schema.prisma
Error: Schema Parsing P1012

Get config 
error: Environment variable not found: DB_URL.
  -->  schema.prisma:5
   | 
 4 |   provider = "postgresql"
 5 |   url      = env("DB_URL")
   | 
```

It happens only when I add `sslmode` to the `DB_URL` as follows:
`postgresql://user:password@host:port/dbName?sslmode=require`

It works just fine without adding the `sslmode`.
Adding other arguments like `connection_limit` works tho.

## Environment & setup
- OS: Ubuntu 20.04 (LTS) x64  
- Database: PostgreSQL 12
- Node.js version: 10.17.0
- Prisma version: 
`@prisma/client": "^2.19.0"`
`"prisma": "^2.19.0"`

**Comment by tomhoule** [comment]
@pantharshit00 If you have time, an attempt at reproducing this would help the migrations team

**Comment by pantharshit00** [comment]
@rvlewerissa Can you please tell me where is your postgres instance is hosted? I wasn't able to reproduce this in my local machine.

**Comment by rvlewerissa** [comment]
@pantharshit00 Sorry I forgot to mention that it works on my local machine too. But it doesn't work when I host it on DigitalOcean (I use DigitalOcean's Managed Database).

**Comment by pantharshit00** [comment]
I am still unable to reproduce this with a Digitalocean managed postgres instance. Can you try again with the latest version of Prisma once?

**Comment by rvlewerissa** [comment]
@pantharshit00 Okay will do, thank you!

**Comment by janpio** [comment]
Are you using an `.env` file to supply the env var @rvlewerissa or does it really come from the environment?
