### ISSUE TITLE
prisma 2.20.1: migration create duplicate migration.sql to alter table

### ISSUE THREAD

**Issue by Bjoernstjerne** [prisma/prisma#6458]
## Bug description

With version 2.20.1 prisma migrate dev generate duplicate migration.sql files to alter tables if enums with default value are used in schema.prisma.

## How to reproduce

clone https://github.com/mazzaker/prisma_migrate_issue
You need a local mysql and change the URL string in prisma.schema file.
use yarn/npm initDb
a new migration will be created, the same sql as the migration files added before.

## Expected behavior

I think an empty migration file is the default behavior.

## Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = "mysql://root:@127.0.0.1:3306/testPrismaMigrate"
}

enum Role {
  Guest
  Incomplete
  Blocked
  Deleted
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
  role  Role    @default(Guest)
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String
  content   String?
  published Boolean  @default(false)
  viewCount Int      @default(0)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}
```

## Environment & setup

- OS: Windows 10 Pro with WSL 2 Debian 10.8
- Database: mysql  Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- Node.js version: 14.7.0
- Prisma version: 2.20.1

**Comment by mazzaker** [comment]
the changes in the migration file is:
```
-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('Guest', 'Incomplete', 'Blocked', 'Deleted') NOT NULL DEFAULT 'Guest';

```

**Comment by tomhoule** [comment]
Thanks for reporting this, we'll work on it asap!

**Comment by tomhoule** [comment]
I tried reproducing the problem both with 2.20.1 in your reproduction repo and with the latest version of prisma, and couldn't reproduce the problem (no new migration is created after the first one, without change to the schema). Does it still happen with 2.22.0 on your end?

**Comment by mazzaker** [comment]
Sorry for the late reply. Tested with 2.23.0 and still get a migration file including 
```-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('Guest', 'Incomplete', 'Blocked', 'Deleted') NOT NULL DEFAULT 'Guest';
``` after running yarn initDb second time.

**Comment by Bjoernstjerne** [comment]
Sorry for the late response, this issue happened with an older version of mariaDb I do not know the version anymore but did not raised with version: mariadb  Ver 15.1 Distrib 10.5.12-MariaDB

**Comment by janpio** [comment]
Thanks for the update.
