### ISSUE TITLE
[DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated in Node `12.22.0`

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#6460]
When running Prisma Client (any of the last 10 major versions) in Node `12.22.0`, which has been released on March 30, I get this warning:
```
[DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated in Node.
```

The source of the problem actually is the dependency `undici`: https://github.com/nodejs/undici/issues/702

They will release a new version next week with a fix.
Until then, the only option to disable the warning I found was this:

```ts
process.removeAllListeners('warning')
```

**Comment by GGAlanSmithee** [comment]
@timsuchanek I am very thankful for this fix. However, a next.js app with prisma on netlify still seems to be affected by this (I think).

I have tried to:

* upgrade prisma to the latest version
* downgrade prisma to a recent version that I'm fairly certain used to work (guess netlify bumped NodeJS version?)
* re-deploy app with cache cleared to netlify
* re-generated the prisma client
* I also tried with the `process.removeAllListeners('warning')` hack, but that didn't work either

But nothing seems to work. I did notice that the referenced package `undici` isn't precent in `package-lock.json` or the `node_modules` folder. Maybe manually installing it to a later version could help?

Also, I used to get the `[DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated in Node.` error, but now it just fails silently, not sure which of my attempted fixes caused this to happen.

Sorry for the lack of substantive information, but I am a bit limited by the available information that I get from netlify. Everything works as expected locally (even when connected to the same remote heroku-hosted DB as on netlify) on node version `v12.18.1`. 

If you have any clue as to what could be causing this, any pointer would be much appriciated.

Thanks.

**Comment by janpio** [comment]
> Also, I used to get the `[DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated in Node.` error, but now it just fails silently, not sure which of my attempted fixes caused this to happen.

This issue was about this error message specifically. If you are not getting this one again, we will not reopen this issue but ask you to open a new bug report issue with all the information you can give us about your problem. We are happy to look into that in a new issue. Bonus points if you can provide a reproduction repository. Thanks.

**Comment by GGAlanSmithee** [comment]
@janpio understandable, thanks for your reply
