### ISSUE TITLE
Schema validation does not accept absolute Windows style paths for SQLite database

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6472]
This is valid to the schema validation:
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "sqlite"
  url      = "file:C:/Users/Jan/Documents/throwaway/sqliteAbsolute/prisma/schema.prisma"
}

generator client {
  provider = "prisma-client-js"
}
```

But this is not:
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "sqlite"
  url      = "file:C:\Users\Jan\Documents\throwaway\sqliteAbsolute\prisma\schema.prisma"
}

generator client {
  provider = "prisma-client-js"
}
```

```
C:\Users\Jan\Documents\throwaway\sqliteAbsolute>npx prisma validate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: Schema parsing
error: Error validating: This line is not a valid definition within a datasource.
  -->  schema.prisma:6
   | 
 5 |   provider = "sqlite"
 6 |   url      = "file:C:\Users\Jan\Documents\throwaway\sqliteAbsolute\prisma\schema.prisma"
 7 | }
   | 

Validation Error Count: 1
```

**Comment by pantharshit00** [comment]
Still relevant.

**Comment by Wondermarin** [comment]
> This is valid to the schema validation:
> 
> ```prisma
> // This is your Prisma schema file,
> // learn more about it in the docs: https://pris.ly/d/prisma-schema
> 
> datasource db {
>   provider = "sqlite"
>   url      = "file:C:/Users/Jan/Documents/throwaway/sqliteAbsolute/prisma/schema.prisma"
> }
> 
> generator client {
>   provider = "prisma-client-js"
> }
> ```
> 
> But this is not:
> 
> ```prisma
> // This is your Prisma schema file,
> // learn more about it in the docs: https://pris.ly/d/prisma-schema
> 
> datasource db {
>   provider = "sqlite"
>   url      = "file:C:\Users\Jan\Documents\throwaway\sqliteAbsolute\prisma\schema.prisma"
> }
> 
> generator client {
>   provider = "prisma-client-js"
> }
> ```
> 
> ```
> C:\Users\Jan\Documents\throwaway\sqliteAbsolute>npx prisma validate
> Environment variables loaded from .env
> Prisma schema loaded from prisma\schema.prisma
> Error: Schema parsing
> error: Error validating: This line is not a valid definition within a datasource.
>   -->  schema.prisma:6
>    | 
>  5 |   provider = "sqlite"
>  6 |   url      = "file:C:\Users\Jan\Documents\throwaway\sqliteAbsolute\prisma\schema.prisma"
>  7 | }
>    | 
> 
> Validation Error Count: 1
> ```

**Workaround**
If the database file already exists at the specified path, there will be no error.

_When the database file does not exist:_
```sh
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "test.db" at "file:C:\Users\Wondermarin\AppData\Roaming\app\database\test.db"

Error: P1012: error: Error validating: This line is not a valid definition within a datasource. 
  -->  schema.prisma:4
   |
 3 |                 provider = "sqlite"
 4 |                 url = "file:C:\Users\Wondermarin\AppData\Roaming\app\database\test.db"
 5 |             }
    |
```

_When the database file exists:_
```sh
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "test.db" at "file:C:\Users\Wondermarin\AppData\Roaming\app\database\test.db"

Already in sync, no schema change or pending migration was found.

✔ Generated Prisma Client (3.1.1) to .\node_modules\@prisma\client in 44ms
```

Is there any news about fix this error?

**Comment by do4gr** [comment]
This is caused by us interpreting the backslashes as string escaping. We could improve the error message to let the user know that this is what failed. The solution would then be for them to escape the backslashes.
