### ISSUE TITLE
Better error messages when Migrate Transactions fail

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6483]
## Problem

Right now when a migration fails, you often only get an error message about a transaction failing.

## Suggested solution

No idea.

## Alternatives

No idea.

**Comment by jasonkuhrt** [comment]
I think @tomhoule had an idea here. We noticed that TablePlus sends the SQL one statement at a time, thus allowing for error feedback per statement. IIUC right now Prisma Migrate sends the whole SQL and loses this chance of catching a specific error.

**Comment by janpio** [comment]
We haven't had any additional requests for this in the last 3 years, so it is safe to say that this is not the most pressing need. As we have hundreds of issues where we do get constant feedback and upvotes, it is not realistic for us to prioritize this one any time soon, sorry. 

I am closing this issue for now. If someone has a dire need for this, please comment below or open a new feature request. Thank you.
