### ISSUE TITLE
Override database connection string for Migrate (and other commands)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6485]
## Problem

When using a connection pooler like PgBouncer, you need to use a non pooled connection URL for running Migrations. That is inconvenient, as Prisma Client and Migrate use the same datasource definition (with the same ENV var defining the connection string). So if you want to use the pooled connection for Prisma Client, running a Prisma Migrate command by default fails (see e.g. https://github.com/prisma/prisma/issues/6480).

The same is true when you want to use a different user for your Prisma Client that does not have permissions to CREATE, DROP or ALTER tables for example. As Prisma Client and Migrate use the same datasource definition (with the same ENV var defining the connection string), this is not trivial to get right and can lead to quite some confusion on the user side.

## Suggested solution

We could have a dedicated ENV var that Migrate uses to override whatever is defined in the datasource. Naming could be `PRISMA_MIGRATIONS_URL` or similar. Then we could tell people to set that to the un-pooled connection string when using a pooled connection for Prisma Client.

## Alternatives

- Set a different ENV var value only when running Migrate

## Additional context

Internal discussion: https://prisma-company.slack.com/archives/CL0AJEVSA/p1617976543036600

**Comment by dac09** [comment]
This might come in very useful in other situations too, e.g. preventing accidental migrations when running builds on CI for pull requests

**Comment by janpio** [comment]
Added another use case besides PgBouncer to the issue description.

**Comment by dac09** [comment]
Hi @janpio - just wanted to follow up on this again :) Any chance this could get prioritised? Would make migrations a lot easier.

The workaround I was thinking of for now, is to override the database url in the migrate command only like:

in my CI
```
DATABASE_URL=$MIGRATE_DB_URL yarn prisma migrate prod
```

**Comment by chrisj-back2work** [comment]
For those reporting this issue, can you say what your deployment environment looks like?

I've been running migrates in my kubernetes cluster via a pgBouncer connection with no issues.

I wonder if I've just been lucky, or if our environments are different enough to affect the operation.

**Comment by MentalGear** [comment]
I agree, adding an env var for migration sounds simple enough.

**Comment by bingomanatee** [comment]
You could simply have a different host in the db definition as in 
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  migration_url      = env("MIGRATION_DATABASE_URL")
}
```

**Comment by Erbros** [comment]
After I got the same issue, I saw several places in the docs saying that migration can't use pooling, but no simple way of doing this. I've for now changed pool mode to session, but this is a temporary fix as far as I can see. A (optional) different env for migration would be really appreciated.

**Comment by Gresliebear** [comment]
bump for solutions I am using prisma in redwood

**Comment by ZetiMente** [comment]
bump for solutions I am using prisma in supabase

**Comment by hmbanan666** [comment]
Yandex Cloud Managed DB PostgreSQL 14 problem, there is only one connection string. Prisma Client v 4.3.1

```
Migration engine error:
db error: ERROR: prepared statement "s0" does not exist
```

**Comment by janpio** [comment]
This is now available as `directUrl`: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#fields It can be used for our own Data Proxy, but all other connection poolers can also benefit from it. Also if you have a Client connection string that does not actually allow you do modify the database structure, you can use `directUrl` for one that does.

**Comment by b0kic4** [comment]
This is how I fixed the problem that occurred while prisma migrations and prisma/supabase pooling:

So when using postgresql with supabase and postgresql pooling. For url -> env("DATABASE_URL")  you should use the Transcation mode for pooling that has the port of 6543 and add ?pgbouncer=true on the end.
And for directUrl you should use port 5432 (session mode) without ?pgbouncer=true 

`datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_DATABASE_URL")
}`
