### ISSUE TITLE
Allow findUnique to accept more than one search parameter

### ISSUE THREAD

**Issue by edilson** [prisma/prisma#6486]
## Problem

Currently findUnique function only accepts one parameter when where is called, I believe it could be better if this function accepted more than one parameter to search, the Prisma docs recommends using findFirst but this function calls findMany as the same docs describe.

## Suggested solution

Allow findUnique function to accept more than one parameter at Where.

## Additional context

This: 
```
const result = await prisma.user.findUnique({
  where: {
    email: 'alice@prisma.io',
  },
})
```

Could turn into this:

```
const result = await prisma.user.findUnique({
  where: {
    email: 'alice@prisma.io',
    active: true
  },
})
```

**Comment by ADrejta** [comment]
I think the findUnique method is used to only search on fields that are unique in a table like emails or IDs (or any unique attribute in a table) regardless of other attributes of that row that you want to search.

So if you have a table that has an ID field or another unique field (like emails) you can use findUnique only with one those unique fields in the table

With that in mind I think it would defeat the purpose of the method if non-unique parameters would be present in the where object.

Is there something else why you are pointing this out? Maybe some performance issues. (Btw I'm not from the prisma team just trying to help 😄  )

**Comment by pantharshit00** [comment]
I agree with @ADrejta 

If you are already providing like an email field to findUnique, providing additional constraints won't narrow down the result. 


`findFirst` on the other hand is just a `findMany` with `limit: 1` and it flattens the result if there is any result. So it can accept all the filters. 


I am going to close this. If you have other concerns, please feel free to comment.

**Comment by edilson** [comment]
@pantharshit00 you're right but maybe the findUnique could at least accept the soft delete parameter used, still even flattening the result is still loading a findMany.

**Comment by pantharshit00** [comment]
> you're right but maybe the findUnique could at least accept the soft delete parameter used,

Can you please elaborate what you mean here? If you store a soft delete column like `is_deleted`, it will return a list of return if you filter by it.

**Comment by edilson** [comment]
```
const result = await prisma.user.findUnique({
  where: {
    email: 'alice@prisma.io',
    active: true
  },
})
```

Something like this, I'm using findUnique to get a user by its email but also checking to see if the user is still valid. The column I use for that is ```active``` but it could be ```is_deleted```.

**Comment by IdanYekutiel** [comment]
This is something I have been trying to figure out too.

**Comment by ArthurThornton** [comment]
@edilson and @IdanYekutiel - for this case you can define a compound uniqueness constraint on your model so you can query against multiple fields as a single unique entity; this is only really appropriate/applicable if your database has this limitation as well. If your database already has a unique on `email` then you might as well get the user based on this and just check if `result.active` isn't `true`.

See https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference/#unique-1 for docs on compound uniqueness.
