### ISSUE TITLE
Can not use Prisma from project using Vite

### ISSUE THREAD

**Issue by tbillington** [prisma/prisma#6491]
## Bug description

Using Prisma with [Vite](https://vitejs.dev/) does not work. It errors during dev server and during build.

During dev command:

```
2:28:07 pm [vite] Error when evaluating SSR module /node_modules/.pnpm/@prisma+client@2.20.1_prisma@2.20.1/node_modules/@prisma/client/index-browser.js:
ReferenceError: require is not defined
    at /node_modules/.pnpm/@prisma+client@2.20.1_prisma@2.20.1/node_modules/@prisma/client/index-browser.js:1:16
    at instantiateModule (/Users/choc/code/sp/kit/node_modules/.pnpm/vite@2.1.5/node_modules/vite/dist/node/chunks/dep-66eb515d.js:69030:166)
```

During build command:

```
> Using @sveltejs/adapter-node
> Cannot find module '/Users/choc/code/sp/kit/node_modules/.prisma/client/index-browser' imported from /Users/choc/code/sp/kit/.svelte/output/server/app.js
Did you mean to import /Users/choc/code/sp/kit/node_modules/.prisma/client/index-browser.js?
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/choc/code/sp/kit/node_modules/.prisma/client/index-browser' imported from /Users/choc/code/sp/kit/.svelte/output/server/app.js
Did you mean to import /Users/choc/code/sp/kit/node_modules/.prisma/client/index-browser.js?
    at new NodeError (node:internal/errors:329:5)
    at finalizeResolution (node:internal/modules/esm/resolve:323:11)
    at moduleResolve (node:internal/modules/esm/resolve:758:10)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:869:11)
    at Loader.resolve (node:internal/modules/esm/loader:88:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:241:28)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:57:40)
    at link (node:internal/modules/esm/module_job:56:36)
 ERROR  Command failed with exit code 1.
```

It seems there may be something to do with how Prisma package is done that is causing issues with Vite.

I saw an issue on the Vite repo with some information but from what they're saying it looks like it's because of how Prisma uses commonjs? Things might work if Prisma used es modules instead?

[This issue talked about how prisma needed node builtins which broke the build](https://github.com/vitejs/vite/issues/728)

## How to reproduce

Following this Prisma guide: [Add to existing project](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project-typescript-postgres).

Generate a [Svelte Kit](https://kit.svelte.dev/) app (runs on Vite).

```
mkdir my-app
cd my-app
npm init svelte@next
npm install
npm run dev
```

Install Prisma: `npm install -D prisma`, `npx prisma init`, `npm install @prisma/client`, `npx prisma generate`

Import prisma client and try something.

```typescript
import { PrismaClient } from '@prisma/client';

const pc = new PrismaClient();
pc.user.findMany().then(console.log);
```

## Expected behavior

Print users, error connecting to db, etc.. usual Prisma behaviour.

## Prisma information

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v15.14.0
- Prisma version:

```
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : darwin
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/.pnpm/@prisma+engines@2.20.0-26.60ba6551f29b17d7d6ce479e5733c70d9c00860e/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/.pnpm/@prisma+engines@2.20.0-26.60ba6551f29b17d7d6ce479e5733c70d9c00860e/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/.pnpm/@prisma+engines@2.20.0-26.60ba6551f29b17d7d6ce479e5733c70d9c00860e/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/.pnpm/@prisma+engines@2.20.0-26.60ba6551f29b17d7d6ce479e5733c70d9c00860e/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by madebysid** [comment]
Hi @tbillington, I haven't played around with SvelteKit a lot, so please correct me if I'm wrong anywhere:

As I understand it, Vite's dev server is only built for frontend assets. Prisma Client currently needs Node to work. Even if it used ESM, things would still break because Node built-ins cannot work in the browser. (I see that `@prisma/client`'s `package.json` has a `browser` field, so that may be leading you to believe otherwise)

Of course, you can make things work during `vite build`, since that'll use Rollup, but I don't think that's what you're trying to achieve!

If you're trying to make this work, you'll have to find a way to tell SvelteKit to only run Prisma Client things on the server (this seems like a good place to start your investigation: https://kit.svelte.dev/docs#modules-app-env)

As it stands, your issue is not something that can be supported right now. Let me know if I misunderstood though!

**Comment by tbillington** [comment]
Thanks @madebysid that makes a lot of sense! I guess having SvelteKit do SSR gave me hope that it could run code relying on Node things, and maybe it can. I'll have to dig into how exactly it runs the server side code, I assumed it was using Vite for that too but I am probably incorrect.

Feel free to close this :)

**Comment by benmccann** [comment]
SvelteKit's default config was bugged. I imagine if you remove `ssr.noExternal` from your `svelte.config.cjs` that it should work as that's fixed the issue when I've seen it with other libraries

**Comment by tbillington** [comment]
Didn't fix it unfortunately but I appreciate the suggestion @benmccann!

I did this see this info (https://github.com/sveltejs/kit/issues/612) on the sveltekit repo, pertaining to the new error after trying to remove the 'noexternal' config value (suggested by people in sveltekit community).

```
> Using @sveltejs/adapter-node
> Directory import '/Users/choc/code/sp/kit/node_modules/@prisma/client/runtime' is not supported resolving ES modules imported from /Users/choc/code/sp/kit/.svelte/output/server/app.js
Did you mean to import @prisma+client@2.21.2_prisma@2.21.2/node_modules/@prisma/client/runtime/index.js?
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/choc/code/sp/kit/node_modules/@prisma/client/runtime' is not supported resolving ES modules imported from /Users/choc/code/sp/kit/.svelte/output/server/app.js
Did you mean to import @prisma+client@2.21.2_prisma@2.21.2/node_modules/@prisma/client/runtime/index.js?
    at finalizeResolution (internal/modules/esm/resolve.js:272:17)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)
 ERROR  Command failed with exit code 1.
```

---

Apparently this fix (https://github.com/firebase/firebase-js-sdk/pull/4767) mentioned in this similar issue on the firebase repo (https://github.com/firebase/firebase-js-sdk/issues/4725#issuecomment-827789946) can fix the newer error message I'm getting in upstream packages by adding export fields to the package.json file. I don't really have the context to know what this means or how it could possibly work with the prisma project.

**Comment by didier** [comment]
Hi, I know this issue is closed, but I may have found a solution that somehow fixes Prisma for me in SvelteKit. Initialising Prisma like this makes it work in both dev and prod for me :) 
```js
// Prisma (workaround until Prisma fully supports ESM)
// This works in DEV
import * as Prisma from '@prisma/client'

// This works in PROD
import { default as ProdPrisma } from '@prisma/client'

let { PrismaClient } = Prisma
if (!dev) PrismaClient = ProdPrisma.PrismaClient

export const prisma = new PrismaClient()
```

**Comment by pepa-linha** [comment]
Is there working method today? I still have the same problem but workaround from @didier does not work now. I get error "exports is not defined" ... at /prisma/client/index-browser.js

**Comment by benmccann** [comment]
Prisma has some packaging issues that you can see with publint:
- https://publint.dev/prisma@4.12.0
- https://publint.dev/@prisma/client@4.12.0

**Comment by qamarabbax** [comment]
> @custom-prisma/client

hi @everyone this solution by @jonas1812st  helped me fix my problem, thankyou bud.

**Comment by omerman** [comment]
Well I re-visited this, I needed to create a standalone bundle..
e.g `ssr: { target: 'node', noExternal: true }`

I managed to do so by overriding rollup's _interopNamespaceDefault, and only then would prisma work correctly.
If someone is getting some wierd `cannot read properties of undefined (reading 'get')` while trying to bundle prisma as standalone.. give me a ping I'll dig up my code.

Happy coding..
