### ISSUE TITLE
Typescript validation error when using groupBy

### ISSUE THREAD

**Issue by DennieMello** [prisma/prisma#6494]
## Bug description

Using groupBy and not specifying a fixed value for the having attribute results in several typescript validation errors. Errors occur both when assigned as "Prisma.CategoryGroupByArgs" and "any".

![Снимок экрана 2021-04-10 в 12 59 55](https://user-images.githubusercontent.com/39631512/114266240-e7394d80-99fd-11eb-9cde-d060e27a4158.jpg)

## Expected behavior

No validation error occurs

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14.15.4
- Prisma version: 2.20.1

# Error
`src/api/categories/categories.service.ts:53:18 - error TS2615: Type of property 'AND' circularly references itself in mapped type '{ [K in keyof { AND?: Enumerable<CategoryScalarWhereWithAggregatesInput>; OR?: Enumerable<CategoryScalarWhereWithAggregatesInput>; ... 15 more ...; parentId?: number | IntNullableWithAggregatesFilter; }]: Or<...> extends 1 ? { ...; }[K] extends infer TK ? GetHavingFields<...> : never : {} extends FieldPaths<...> ? n...'.

53     return await this.prisma.category.groupBy(data);
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/api/categories/categories.service.ts:53:18 - error TS2615: Type of property 'NOT' circularly references itself in mapped type '{ [K in keyof { AND?: Enumerable<CategoryScalarWhereWithAggregatesInput>; OR?: Enumerable<CategoryScalarWhereWithAggregatesInput>; ... 15 more ...; parentId?: number | IntNullableWithAggregatesFilter; }]: Or<...> extends 1 ? { ...; }[K] extends infer TK ? GetHavingFields<...> : never : {} extends FieldPaths<...> ? n...'.

53     return await this.prisma.category.groupBy(data);
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/api/categories/categories.service.ts:53:18 - error TS2615: Type of property 'OR' circularly references itself in mapped type '{ [K in keyof { AND?: Enumerable<CategoryScalarWhereWithAggregatesInput>; OR?: Enumerable<CategoryScalarWhereWithAggregatesInput>; ... 15 more ...; parentId?: number | IntNullableWithAggregatesFilter; }]: Or<...> extends 1 ? { ...; }[K] extends infer TK ? GetHavingFields<...> : never : {} extends FieldPaths<...> ? n...'.

53     return await this.prisma.category.groupBy(data);
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/api/categories/categories.service.ts:53:47 - error TS2345: Argument of type 'CategoryGroupByArgs' is not assignable to parameter of type '({ where?: CategoryWhereInput; orderBy?: Enumerable<CategoryOrderByInput>; by: ("id" | "createdAt" | "updatedAt" | "published" | ... 10 more ... | "parentId")[]; ... 7 more ...; max?: CategoryMaxAggregateInputType; } & { ...; } & `Error: Field "${any}" used in "having" needs to be provided in "by".`) | ({ ...; } & ....'.
  Type 'CategoryGroupByArgs' is not assignable to type '{ where?: CategoryWhereInput; orderBy?: Enumerable<CategoryOrderByInput>; by: ("id" | "createdAt" | "updatedAt" | "published" | ... 10 more ... | "parentId")[]; ... 7 more ...; max?: CategoryMaxAggregateInputType; } & { ...; } & [...]'.
    Type 'CategoryGroupByArgs' is not assignable to type '{ orderBy: Enumerable<CategoryOrderByInput>; }'.
      Property 'orderBy' is optional in type 'CategoryGroupByArgs' but required in type '{ orderBy: Enumerable<CategoryOrderByInput>; }'.

53     return await this.prisma.category.groupBy(data);`

**Comment by pantharshit00** [comment]
Please install typescript greater than or equal to version `4.1`. See: https://www.prisma.io/docs/reference/system-requirements#unable-to-use-groupby-preview-feature

**Comment by pantharshit00** [comment]
It might be the case you are running the global `tsc` instance and it is out of date so update that via `npm install -g typescript@latest`

**Comment by DennieMello** [comment]
> It might be the case you are running the global `tsc` instance and it is out of date so update that via `npm install -g typescript@latest`

I have tested it with version 4.2.3 and I keep getting the error on several different devices. Please check this code yourself to make sure the error occurs.

`  async groupBy(data: Prisma.CommentGroupByArgs) {
    return await this.prisma.comment.groupBy(data);
  }`

**Comment by pantharshit00** [comment]
Oh hey sorry I misread this at first first. You can type a function which takes groupBy like so:


```ts
async groupBy(data: Prisma.CommentGroupByArgs & { orderBy: Prisma.CommentGroupByArgs["orderBy"] }) { return await this.prisma.comment.groupBy(data); }
```

Make orderBy required or optional according to your usage.

**Comment by DennieMello** [comment]
> Oh hey sorry I misread this at first first. You can type a function which takes groupBy like so:
> 
> ```ts
> async groupBy(data: Prisma.CommentGroupByArgs & { orderBy: Prisma.CommentGroupByArgs["orderBy"] }) { return await this.prisma.comment.groupBy(data); }
> ```
> 
> Make orderBy required or optional according to your usage.

It doesn't seem to be helping. The error is associated with the "having" attribute. Error text:
`Error: Field "${any}" used in "having" needs to be provided in "by". | [...]>(args: {
    ...; } & ... 1 more ... & (Error: Field "${any}" used in "having" needs to be provided in "by". | [...])): `

![Снимок экрана 2021-04-15 в 14 13 46](https://user-images.githubusercontent.com/39631512/114860868-306e1080-9df5-11eb-82cd-b18b82b9e192.jpg)

**Comment by rfermann** [comment]
Same issue here, with global and local typescript versions both being 4.2.4. Behaviour is the same as for @DennieMello. 

Can you please reopen the issue and investigate?

**Comment by matthewmueller** [comment]
Closing in favor of https://github.com/prisma/prisma/issues/7183
