### ISSUE TITLE
Offer unique constraint per related node

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#65]
For example, post titles are only unique per user. Two users can have two separate posts with the same title.

**Comment by cullan** [comment]
It would be nice if any two fields could be marked as being unique when taken together.
If one field is a relation it would do what you suggest but it could also be generalized to accommodate the same kind of thing within one model.

Django's ORM does this with the unique_together option. [Link to Django docs](https://docs.djangoproject.com/en/1.10/ref/models/options/#unique-together)

**Comment by schickling** [comment]
Hi @cullan. This feature is available as a beta feature. Please reach out to us via Intercom/Slack for enabling it for you.

**Comment by marktani** [comment]
#90 would be a nice addition for this

**Comment by marktani** [comment]
This feature is now work in progress and no more beta spots are available.

**Comment by marktani** [comment]
After our initial tests, we're back to the design board.

**Comment by joealden** [comment]
Has there been any progress on the implementation of this feature?

**Comment by sorenbs** [comment]
@joealden please see #1300 for current discussion
