### ISSUE TITLE
Query Engine running when Netlify build finishes

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6502]
I got a report of a Netlify deployment problem, that also included this interesting bit:

```
8:48:52 PM: ​
8:48:52 PM: The build completed successfully, but the following processes were still running:
8:48:52 PM: ​
8:48:52 PM:    - /opt/build/repo/node_modules/.prisma/client/query-engine-debian-openssl-1.0.x --enable-raw-queries --port 41637
8:48:52 PM: ​
8:48:52 PM: These processes have been terminated. In case this creates a problem for your build, refer to this article for details about why this process termination happens and how to fix it.
```
(full output via internal Slack link below)

Our own Netlify CI end to end tests do not show this output (but differ in Node version, configuration and project of course)

Why is a QE running during deployment?
Is this a Redwood or user project thing somehow?

- Internal discussion where this was reported: https://prisma-company.slack.com/archives/CL0AJEVSA/p1618085131114500?thread_ts=1618082186.100800&cid=CL0AJEVSA
- Ongoing internal discussion about details of this: https://prisma-company.slack.com/archives/CL0AJEVSA/p1618086466123100 

Next steps:
- Understand project
- Possibly build "Netlify and Redwood" e2e test to have better own reproduction

**Comment by janpio** [comment]
Note: Redwood has built in data migration tool that uses Prisma Client. Possibly that connection is not explicitly disconnected when done, causing this output.

Next: Confirm with Redwood.

**Comment by pantharshit00** [comment]
@janpio Any updates from Redwood here?

**Comment by janpio** [comment]
Sorry, forgot to update here: Everything _should_ be closed/finished from their side. We should try to reproduce this ourselves and figure out what is going on. Probably worth rereading the Slack discussion to get all the details what is going on.
