### ISSUE TITLE
Receiving this error: Command failed with exit code 3221225781

### ISSUE THREAD

**Issue by ahmedosama5200** [prisma/prisma#6508]
## Bug description

I am following [this guide](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-typescript-postgres) to setup a prisma project.
When I run the prisma migrate command `npx prisma migrate dev --name init`, I receive this error:
```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: Get config: Error: Command failed with exit code 3221225781: C:\Users\ahmed\Desktop\hello-prisma\node_modules\@prisma\engines\query-engine-windows.exe cli get-config
```
I also tried other commands like `npx prisma dub push --preview-feature` and `npx prisma generate` and I am receiving the same error above.
I tried deleting all the cache in `%AppDate%` related to prisma and npm and also tried reinstalling node.js, tried using a sqlite database instead of postgres but nothing worked.

In addition to that error, also the prisma formatting extension is not working and gives me this error:
```
prisma-fmt error'd during formatting. To get a more detailed output please see Prisma Language Server output. To see the output, go to View > Output from the toolbar, then select 'Prisma Language Server' in the Output panel.
```
and this is output I get in vscode output window:
```
prisma-fmt error'd during formatting. Please report this issue on [Prisma Language Tools](https://github.com/prisma/language-tools/issues).

[Info  - 12:03:44 PM] Prisma plugin prisma-fmt installation succeeded.
[Info  - 12:03:44 PM] Installed version  of 'prisma-fmt' using path: c:\Users\ahmed\.vscode\extensions\prisma.prisma-2.20.1\node_modules\@prisma\language-server\dist\src\prisma-fmt\prisma-fmt.60ba6551f29b17d7d6ce479e5733c70d9c00860e.exe
[Error - 12:03:44 PM] Language Server failed while downloading url https://binaries.prisma.sh/all_commits/60ba6551f29b17d7d6ce479e5733c70d9c00860e/windows/prisma-fmt.exe.gz with fmtPath c:\Users\ahmed\.vscode\extensions\prisma.prisma-2.20.1\node_modules\@prisma\language-server\dist\src\prisma-fmt\prisma-fmt.60ba6551f29b17d7d6ce479e5733c70d9c00860e.exe.
[Error - 12:03:44 PM] [object Object]
[Error - 12:03:44 PM] Cannot install prisma-fmt: EBUSY: resource busy or locked, copyfile 'C:\Users\ahmed\AppData\Local\Temp\ce5080633ae91aaa2f26d7f695b36a06\partial' -> 'c:\Users\ahmed\.vscode\extensions\prisma.prisma-2.20.1\node_modules\@prisma\language-server\dist\src\prisma-fmt\prisma-fmt.60ba6551f29b17d7d6ce479e5733c70d9c00860e.exe'. Please:
1. Check your network connection and run `Prisma: Restart Language Server`, or
2. Manually download and uncompress the archive file, then set the path in `prisma.prismaFmtBinPath`

The achieve file can be acquired at:
  https://binaries.prisma.sh/all_commits/60ba6551f29b17d7d6ce479e5733c70d9c00860e/windows/prisma-fmt.exe.gz


[Error - 12:03:44 PM] prisma-fmt error'd during linting.
```

So, yeah, everything related to prisma is broken for me and I really need to start this project as soon as possible.

## How to reproduce

[this guide](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-typescript-postgres)
## Expected behavior

[this guide](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-typescript-postgres)
## Prisma information

[this guide](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-typescript-postgres)
## Environment & setup

- OS: Windows
- Database: PostgreSQL/SQLite
- Node.js version: v14.16.1
- Prisma version: 

```
2.20.1
```

**Comment by janpio** [comment]
What Windows version?
Any special software running on the computer (Enterprise stuff, antivirus maybe)?
You can use other Node tooling as usual?

**Comment by ahmedosama5200** [comment]
> What Windows version?

Windows 10
> Any special software running on the computer (Enterprise stuff, antivirus maybe)?

Avast Antivirus, I disabled it but still the problem is the same
> You can use other Node tooling as usual?

yeah, node and npm are working just fine
> Anything with Docker in your toolchain you are using here? WSL?

I am not using docker to run the prisma code, I am only using it to run the postgresql database. As I said I also tried with sqlite and it's the same problem

**Comment by janpio** [comment]
Can you download https://binaries.prisma.sh/all_commits/60ba6551f29b17d7d6ce479e5733c70d9c00860e/windows/prisma-fmt.exe.gz, unpack it (e.g. using 7zip) and execute it in a command line windows? Does that work for you? (Should get a nice output)

Same for pls as well https://binaries.prisma.sh/all_commits/60ba6551f29b17d7d6ce479e5733c70d9c00860e/windows/query-engine.exe.gz. (Should get a specific error message `{"is_panic":false,"message":"Datamodel should be provided either as path or base64-encoded string."," ...`)

> exit code 3221225781

This implies a missing DLL, see similar search results like https://github.com/arduino/arduino-pro-ide/issues/210. 

> [Error - 12:03:44 PM] Cannot install prisma-fmt: EBUSY: resource busy or locked, copyfile 'C:\Users\ahmed\AppData\Local\Temp\ce5080633ae91aaa2f26d7f695b36a06\partial' -> 'c:\Users\ahmed\.vscode\extensions\prisma.prisma-2.20.1\node_modules\@prisma\language-server\dist\src\prisma-fmt\prisma-fmt.60ba6551f29b17d7d6ce479e5733c70d9c00860e.exe'. Please:

This on the other hand could mean that something is blocking the file from being accessed.

Both would be pretty weird - so trying to download manually seems like the obv next step before we can figure out what is causing this.

**Comment by ahmedosama7450** [comment]
I manually downloaded these two files and ran them from the command line in the same folder of the project and to my surprise the formatting extension now works and the `npx prisma migrate dev` command now gives the same error but with a path to a different file
```
Error: Command failed with exit code 3221225781: C:\Users\ahmed\Desktop\hello-prisma\node_modules\@prisma\engines\migration-engine-windows.exe cli --datasource file:./dev.db create-database
```
I guess I will have to keep downloading these files manually and It will work in the end but this is really tedious.
What could be the reason for that ? Why can't it automatically download those files ?

**Comment by ahmedosama5200** [comment]
I manually downloaded these two files and ran them from the command line in the same folder of the project and to my surprise the formatting extension now works and the `npx prisma migrate dev` command now gives the same error but with a path to a different file
```
Error: Command failed with exit code 3221225781: C:\Users\ahmed\Desktop\hello-prisma\node_modules\@prisma\engines\migration-engine-windows.exe cli --datasource file:./dev.db create-database
```
I guess I will have to keep downloading these files manually and It will work in the end but this is really tedious.
What could be the reason for that ? Why can't it automatically download those files ?

**Comment by pantharshit00** [comment]
I am unable to reproduce this. I use windows as my main os and never had this issue. 


Can you tell the exact windows version. Follow these steps to know the exact windows version:
1. Press Win + R
2. Type winver in the Run Prompt and Press Enter


It should show you the exact version like so:
![image](https://user-images.githubusercontent.com/22195362/114375930-cd853b00-9ba2-11eb-8d41-69e9583b4871.png)

**Comment by ahmedosama5200** [comment]
![Capture2](https://user-images.githubusercontent.com/31630951/114382553-c6533280-9b8c-11eb-8927-a50867daaa04.PNG)

**Comment by janpio** [comment]
> I guess I will have to keep downloading these files manually and It will work in the end but this is really tedious.
> What could be the reason for that ? Why can't it automatically download those files ?

This is not the expected behavior of course. Downloading these exact files will only work this time, with other versions you will get the wrong binary. So this is not a solution, just a way to figure out what is going on.

So your system can fundamentally run the files that you downloaded manually. This means nothing is really wrong with your DLLs and Windows itself I think.

Can you please upload some of the files that are _not_ working for you, so e.g. the `C:\Users\ahmed\Desktop\hello-prisma\node_modules\@prisma\engines\migration-engine-windows.exe`? If you do not have those any more, can you create a new project and just normally download these files? I wonder how they are different from the manually downloaded ones.

**Comment by ahmedosama5200** [comment]
I am really sorry I forgot to mention that when I manually downloaded those files and ran them, I had this error about a missing DLL file
![Capture](https://user-images.githubusercontent.com/31630951/114433638-565f9f00-9bc2-11eb-9256-8f3123b1cf7b.PNG)
Then I downloaded this DLL file manually and included everything in the same folder and It worked.

I thought that my windows is broken, so, I reinstalled it. Sadly, that didn't fix anything. so, It's probably not a problem with my windows system.

**Comment by ahmedosama5200** [comment]
Also, It's worth mentioning that I have used prisma before a couple of months ago (at the time of prisma 2.14, I guess) and I didn't have this issue. I was just trying it out back then and everything was working just fine.

**Comment by janpio** [comment]
> Then I downloaded this DLL file manually and included everything in the same folder and It worked.

Where exactly did you put this file? It probably belong in some system folder to work all the time.



> I thought that my windows is broken, so, I reinstalled it. Sadly, that didn't fix anything. so, It's probably not a problem with my windows system.

The missing DLL indeed points to something with your system being broken or missing, for whatever reason.

**Comment by ahmedosama5200** [comment]
> Where exactly did you put this file? It probably belong in some system folder to work all the time.

I put it in the same folder of my project along with the executable file that I manually downloaded

> The missing DLL indeed points to something with your system being broken or missing, for whatever reason. Maybe some software you use causes this file to be missing or invalid.

I am not really sure if this is the case because I reinstalled my windows from scratch and I haven't installed any software yet except for `nodejs`, `git` and `vs code`.

**Comment by ahmedosama5200** [comment]
I just updated my windows and update my outdated drivers but nothing changed

Also, I searched for this DLL file in the C drive and here is what I found
![Capturddde](https://user-images.githubusercontent.com/31630951/114451009-04754400-9bd7-11eb-85a0-5ccf1e103982.PNG)

The DLL file is indeed there within my system files in `C:\Windows\System32\DriverStore\FileRepository\iclsclient.inf_amd64_75ffca5eec865b4b\lib`
Also a very similar file named `vcruntime140_clr0400.dll` exists in `C:\Windows\System32` and `C:\Windows\SysWOW64`

Also, It's worth noting that Mozilla Firefox includes this DLL file in `Program Files`. So, maybe you should also include it with prisma binaries.
I am pretty sure that there is nothing wrong with my system files, though.

**Comment by janpio** [comment]
> So, maybe you should also include it with prisma binaries.

We had 0 reports of similar problems with our many hundred or thousand Windows users, including me with >5 different Windows machines. So I am pretty confident this is not a common problem on Windows.

Googling for the file name I could find installation instructions on how to really fix this:
https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/vcruntime140dll-and-msvcp140dll-missing-in-windows/220f1caf-8eb9-413d-a7fe-1b13df1bfa5d
https://www.bleepingcomputer.com/tutorials/fix-missing-vcruntime140dll-dll-error-in-windows/
https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_install-winpc/vcruntime140dll/b1a15b0e-e389-41a3-bc49-f4fc85bac575

Please let us know if this fixes the problem.

**Comment by ahmedosama5200** [comment]
Alright, I installed `Microsoft Visual C++ 2015 Redistributable` and It worked

But still, This leaves me confused.
Do you have this program installed on your windows machine? If so, then, Does it come preinstalled with your windows installation or did you manually install it?

I think that this is something the the rust team should be aware of.

Any way, Thank you so much, my problem is solved and everything is working fine now.

**Comment by janpio** [comment]
I tried hard but could not find any Windwos computer in this household where the problem you described occured.

If we ever get another report of this, I will remember this issue and come back to this and reopen it. Until then, I am happy we could fix this for you.

**Comment by olegKusov** [comment]
Prisma schema loaded from prisma\schema.prisma
Error: Get config: Error: Command failed with exit code 3221225781: C:\Users\olegk\projects\okusov.ru\backend\node_modules\prisma\query-engine-windows.exe cli get-config --ignoreEnvVarErrors

**Comment by olegKusov** [comment]
Install Visual C++ redistributable and error will be fixed

**Comment by edw-lee** [comment]
> Install Visual C++ redistributable and error will be fixed

This still works in 2026
