### ISSUE TITLE
Add Support for Sentry Tracing

### ISSUE THREAD

**Issue by nahtnam** [prisma/prisma#6519]
## Problem

Sentry.io has a new feature called "Tracing" which is essentially an APM. They have a `postgres` integration, however this does not work with Prisma

## Suggested solution

Either make a PR to fix the postgres integration to support prisma or create a separate prisma integration

## Alternatives

N/A

## Additional context

See: https://github.com/getsentry/sentry-javascript/issues/3143

**Comment by stnwk** [comment]
I took a look at how this is implemented for the pg integration: https://github.com/getsentry/sentry-javascript/blob/master/packages/tracing/src/integrations/postgres.ts and applied prisma's middleware concept to it: https://www.prisma.io/docs/concepts/components/prisma-client/middleware

Here's what worked for me:

```tsx
  import { PrismaClient } from "@prisma/client";
  import { getCurrentHub, Severity } from "@sentry/nextjs"; // whatever package you're using

  prisma.$use(async (params, next) => {
    const { model, action, runInTransaction, args } = params;
    const description = [model, action].filter(Boolean).join(".");
    const data = {
      model,
      action,
      runInTransaction,
      args,
    };

    const scope = getCurrentHub().getScope();
    const parentSpan = scope?.getSpan();
    const span = parentSpan?.startChild({
      op: "db",
      description,
      data,
    });

    // optional but nice
    scope?.addBreadcrumb({
      category: "db",
      message: description,
      data,
    });

    const result = await next(params);
    span?.finish();

    return result;
  });
```

Maybe a good starting point?

**Comment by ACPK** [comment]
@stnwk Thanks for sharing the awesome script. On a side node, it was smart of you to post the script on the related Github issue for Sentry's javascript package.

Have you seen any performance issues when tracking every query via middleware? 

> Middleware executes for every query, which means that overuse has the potential to negatively impact performance [Prisma Docs](https://www.prisma.io/docs/concepts/components/prisma-client/middleware).

**Comment by stnwk** [comment]
> Thanks for sharing the awesome script. On a side node, it was smart of you to post the script on the related Github issue for Sentry's javascript package.

You're welcome & thanks :)

> Have you seen any performance issues when tracking every query via middleware?

So far, the impact has been nothing to worry about for us

**Comment by Noitidart** [comment]
Thanks @stnwk this is super cool! Would be awesome to see this in official one day, but probably Sentry would have to add it to their package right? Not Prisma?

**Comment by stnwk** [comment]
As far as I know Sentry has added official support for prisma: https://github.com/getsentry/sentry-javascript/issues/3143

I think this issue here could probably be closed

**Comment by Noitidart** [comment]
Dang the Sentry version doesn't include the `runInTransaction` or the `args` which would be very helpful - https://github.com/getsentry/sentry-javascript/pull/4931/files#diff-1299d6ad2dcb1bc219acbc53ed90550ab15c6240e54efd6bd007692864ddcd3fR78-R79

**Comment by aqrln** [comment]
This has been available for years both as a custom integration by Sentry and built into Prisma via OpenTelemetry protocol under the `tracing` preview feature (that Sentry also supports). `tracing` goes GA in the next Prisma release. I'll go ahead and close this stale issue.
