### ISSUE TITLE
Preview feature feedback: Order by an Aggregate in groupBy (`orderByAggregateGroup`)

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#6545]
Please share your feedback about the `orderByAggregateGroup` functionality released in [v2.21.0](https://github.com/prisma/prisma/releases/tag/2.21.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo.
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma-client`](https://prisma.slack.com/archives/CCWDULGUW) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by 2color** [comment]
Closing this now that this has been released to General Availability in the [3.0.1 release](https://github.com/prisma/prisma/releases/tag/3.0.1)
