### ISSUE TITLE
Support CockroachDB in Introspection

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#6552]
## Problem

As a first step to enable full CockroachDB compatibility, we want to make it possible for developers to use Prisma with CockroachDB via introspection.

## Additional context

* [Main CockroachDB support issue](https://github.com/prisma/prisma/issues/2523)
* [CockroachDB support in Migrate](https://github.com/prisma/prisma/issues/4702)

**Comment by tomhoule** [comment]
Scheduled for this sprint to see if the minimal support is feasible.

**Comment by SKopsap** [comment]
if this gets implemented I am a cockroach and prisma user for life!

**Comment by JuniorDEVed** [comment]
Wondering if there are any updates on this?

**Comment by floelhoeffel** [comment]
Released in 3.9.0
