### ISSUE TITLE
Bundling fails on 2.21.0

### ISSUE THREAD

**Issue by prescience-data** [prisma/prisma#6564]
## Bug description

After upgrading to `2.21.0` and running ESBuild to bundle, a new error occurs:
```
> ../../common/temp/node_modules/.pnpm/@prisma+client@2.21.0_prisma@2.21.0/node_modules/@prisma/client/runtime/index.js:24152:23: 
error: Could not resolve "_http_common" (mark it as external to exclude it from the bundle)
24152 │   var common = require("_http_common");
```
and

```
"var runtimeRequire = 
  typeof __webpack_require__ === 'function' ? 
     __non_webpack_require__ : require // eslint-disable-line"
```

## How to reproduce

 
1. Install Prisma and [ESBuild](https://esbuild.github.io/getting-started/#bundling-for-node) using [PNPM](https://pnpm.io/).
2. Run `prisma generate`
3. Run `esbuild app.js --bundle --platform=node --target=node14`
 
## Expected behavior

Prior to `2.21.0` bundling was successful.

## Prisma information

```
// Datasources
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// Generators
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["debian-openssl-1.1.x", "linux-musl", "windows", "darwin"]
}
```

## ESBuild config

```js
module.exports = {
  bundle: true,
  minify: false,
  format: "cjs",
  keepNames: true,
  sourcemap: true,
  platform: "node",
  logLevel: "error",
  target: ["node14"],
  external: ["fsevents"],
  outfile: "dist/run.js",
  entryPoints: ["src/index.ts"],
  metafile: false,
  loader: { ".prisma": "file" },
}

```

## Environment & setup

- OS: Windows
- Database:  Postgres
- Node.js version: v14.16.0
- Prisma version: v2.21.0

**Comment by matthewmueller** [comment]
Can you share an example script on how to reproduce this?

**Comment by larrybek** [comment]
I have a similar issue with @m-abdelwahab Im using `serverless-bundle` which uses webpack it was trying to find a module to bundle I needed to ignore the package `_http_common` for bundling so it work.

**Comment by matthewmueller** [comment]
A repro we could clone and try out ourselves would be greatly appreciated!

**Comment by matthewmueller** [comment]
Next steps:

- Try upgrading undici and see if that fixes it.

**Comment by larrybek** [comment]
@matthewmueller is a private project but I can refer to the core issue, `webpack` tries to find a package in `package.json` but without result, as it's a native node.js module and it generates its own package.json where the version of "_http_common" is empty (as it didn't find a package there). 
`serverless-bundle` on a build flow uses `yarn install --non-interactive --frozen-lockfile` and as the version is missing it crashes.
Ignoring helped just not add it to `package.json` with an empty string for a version. This way I solved the issue but it's a hack than a solution.

**Comment by prescience-data** [comment]
> A repro we could clone and try out ourselves would be greatly appreciated!

Lol sorry, I left the `<!--` in the original ticket, just removed it now.

1. Install Prisma and ESBuild using PNPM.
2. Run `prisma generate`
3. Run `esbuild app.js --bundle --platform=node --target=node14`
4. See error

**Comment by prescience-data** [comment]
> @matthewmueller is a private project but I can refer to the core issue, `webpack` tries to find a package in `package.json` but without result, as it's a native node.js module and it generates its own package.json where the version of "_http_common" is empty (as it didn't find a package there).
> `serverless-bundle` on a build flow uses `yarn install --non-interactive --frozen-lockfile` and as the version is missing it crashes.
> Ignoring helped just not add it to `package.json` with an empty string for a version. This way I solved the issue but it's a hack than a solution.

I thought this had solved it for me as well, but one of the modules in my monorepo is actually instantiating a `http` node server, so it breaks now as the native Node `http` module has been excluded.

**Comment by JamesForan** [comment]
> I have a similar issue with @m-abdelwahab Im using `serverless-bundle` which uses webpack it was trying to find a module to bundle I needed to ignore the package `_http_common` for bundling so it work.

@larrybek , I have the same issue. New to webpack though. can you advise how you ignore the package?

Thanks

James

**Comment by larrybek** [comment]
@JamesForan I have been using `serverless-bundle` which has initial functionality called `forceExclude` but I know that its underneath is using webpack so there's an option that this parameter is somehow passed to webpack. You can have a look on it, and it may give you some idea.

**Comment by millsp** [comment]
We are waiting for `undici` to release `v4`, in the meantime you could mark their internal dependency as external with `--external:_http_common`.

**Comment by trivigy** [comment]
@millsp Any recommendations of a workaround in the meantime?

**Comment by softmarshmallow** [comment]
How should i be dealing with my webpack.config? (using serverless + prisma)

**Comment by mubaidr** [comment]
^ `target: 'serverless'` is not supported. what webpack version are u using?

```
Error: Unknown target 'serverless'
```

**Comment by pantharshit00** [comment]
@mubaidr It is for next js. Ignore it if you are not using next js.

**Comment by millsp** [comment]
In your `webpack.config.js`, add `externals: ['_http_common', 'encoding'],`

**Comment by trivigy** [comment]
@millsp I run prisma on electron. The suggest workaround seems to work. Thanks. I just upgraded to `v2.23.0`. If I encounter any more issues related to this specific problem I will follow up. Are those dependencies not used `undici`? Or are they used by `undici` but the functionality that prisma needs from `undici` does not invoke those dependencies? Just trying to understand the scope of possible issues to come. I am guessing by defining them external, they are not being bundled which may cause various problem down the line.

**Comment by pantharshit00** [comment]
`_http_common` is a private module built into node js itself, just like `fs` or `util`. It is not a publicly documented API. It was used by `undici` to improve http parsing performance but looks like they no longer need it in the latest release candidate version. `undici` is maintained by Node JS folks so they know about this undocumented private module pretty well. So that is why you don't need to bundle it as it is built into the runtime.

**Comment by matthewmueller** [comment]
**Workaround for you today**
- Mark _http_common external. It will still work as expected

**Permanent Fix**
- [ ] Wait until [undici@4](https://github.com/nodejs/undici/milestone/4) is out
- [ ] Bump to unidici 4, test and try again

**Comment by doei** [comment]
With webpack 5, simply adding `'_http_common'` to an array in the `externals` build option wasn't enough for me, I had to specify it this way:
```javascript
{
  // ...
  externals: {
    "_http_common": "commonjs2 _http_common",
  }
}
```

**Comment by ra-kesh** [comment]
> With webpack 5, simply adding `'_http_common'` to an array in the `externals` build option wasn't enough for me, I had to specify it this way:
> 
> ```js
> {
>   // ...
>   externals: {
>     "_http_common": "commonjs2 _http_common",
>   }
> }
> ```

thank you...I was really struggling with this issue while using turbo repos with next js..but this resolved it.....

**Comment by millsp** [comment]
Hey everyone, this has been fixed in `@prisma/client@dev` if you want to give it a try. Please let us know if you find anything unexpected. Thanks.

(cc @prescience-data @ra-kesh @trivigy)

**Comment by jamesbluecrow** [comment]
I can confirm that `"@prisma/client": "^3.12.0-dev.28"` works. Thanks @millsp !
