### ISSUE TITLE
Track prisma engine binary size

### ISSUE THREAD

**Issue by luhagel** [prisma/prisma#6566]
## Problem
Over prisma 2's lifespan, the binary size of the bundled engines has been increasing at a steady rate as new features are added. `query-engine-debian-openssl-1.1.x` went from ~12mb around preview.10, to 24 at `2.11`, to now 38mb with `2.20.1` and napi enabled. While this is usually not a problem in traditional server environments it's becoming increasingly troubling in a serverless environment, where the bundled `.zip` need to stay below a certain size.

## Suggested solution
I'd like to propose to add an internal monitoring of the binary size, and maybe dedicating some time into thinking how we could reduce it. I hope that moving napi to stable can reduce some engine networking code and dependencies, and maybe having more finegrained builds with or without certain features ( no need to bundle a sqlite adapter when only postgres support is needed) could help as well, though I'm not sure how technically feasible that is.

**Comment by janpio** [comment]
Thanks Luca, we are aware of the problem and connected challenges, and we are internally indeed tracking the sizes of different artifacts. Besides different platform binaries, that are for example the client `index.js` or `index.d.ts`, the complete `@prisma/client` package or `.prisma/client` generation output.

We are of course also considering and investigating mechanisms to reduce the size of all these artifacts where possible.

If our current package or binary size causes an problem for you or anyone else, please let us know with an issue so we can investigate and see if we can do something.

**Comment by janpio** [comment]
This monitoring exists for some time now: https://prisma.github.io/prisma/dev/bench/

**Comment by ShanonJackson** [comment]
Any chance of reviving this? I think 40MB is excessive and it without knowing the complexities of reducing it I'm hoping that it can be reduced anyway by a large margin.

I think the differences between Azure and AWS here are huge, AWS on this front download size doesn't seem like too much of a factor to cold start on AWS but on Azure we're seeing like 7s cold starts with serverless applications on consumption plans that basically just have prisma and a few other dependencies compared to like 150-200ms without.

**Comment by janpio** [comment]
Just open a new issue about this and provide some (optimally reproducible) information @ShanonJackson. We are obviously aware of the general problem of the binary size, but are currently not prioritizing it as we have many other things to spend time with. A new issue with proper data could fix that.

**Comment by ShanonJackson** [comment]
@janpio thanks, it's in the chain above.
