### ISSUE TITLE
Improvements to relation field names during introspection

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#6569]
## Problem

Prisma introspection currently uses a simple heuristic to name relations by using the name of the related model. Some users have expressed that they don't like the generated relation names.

## Suggested solution

No suggested solution.

## Alternatives

* Some users have pointed out that a substring of the relation scalar field name could be used instead.
* This could be an option via introspection configuration - https://github.com/prisma/prisma/issues/1184

## Additional context

Feedback from @Tajnymag via https://github.com/prisma/prisma/issues/3659#issuecomment-706719604

>What I've found to be deal-breaking for me, is the way relation naming is handled. It seems prisma uses the referenced table name as the field name. What I would expect, would be to use the relation name from sql field `{{relationName}}_id`.

**Comment by janpio** [comment]
Nothing actionable, so closing.
