### ISSUE TITLE
Integrate feature flag changes in Prisma Client

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#6575]
Integrate the changes introduced in this PR: https://github.com/prisma/prisma-engines/pull/1849

**Comment by janpio** [comment]
This broke preview feature flags (see e2e tests).

Internal discussion: https://prisma-company.slack.com/archives/C013RMLGE72/p1619106682048900

**Comment by williamluke4** [comment]
> This broke preview feature flags (see e2e tests).
This was fixed [here](https://github.com/prisma/prisma/pull/6742)
