### ISSUE TITLE
Connecting prisma to custom data sources, instead of database

### ISSUE THREAD

**Issue by joekryzak** [prisma/prisma#6576]
## Problem

I would like to use a custom designed interface for a data source, as opposed to dumping that data source to a database.

## Suggested solution

An interface that is allow for connection to real time systems as well as standard data repositories. 

## Alternatives

Create intermediate method to port data from custom sources to a database, eventually integrating into prisma.

## Additional context

for instance, would like to monitor current and voltage from a solar array without a database.

**Comment by janpio** [comment]
I would consider this generally out of scope for Prisma. If we build custom database connectors in the future, that our users like you can build themselves, you might be able to make a live API look like a database this way - but we have no concrete plans for that.

Closing the issue for now.
