### ISSUE TITLE
model with the names "Session" and "SessionCount" has a name clash

### ISSUE THREAD

**Issue by wyozi** [prisma/prisma#6580]
## Problem

Specific table names might cause generated Typescript type clashes that are not immediately obvious. E.g. `Session` and `SessionCount` table names would cause TS errors, because there are two types generated for `SessionCountArgs`

## Suggested solution

Check whether such clashes exist in schema generator and print an error

**Comment by pantharshit00** [comment]
This is reproducible and I will label this as a bug. We shouldn't need to warn but actually avoid this situation in the first place. Name collisions are not ideal and we have made efforts in past of eliminate them but looks like this corner is missing so we should patch it.

**Comment by juanrgm** [comment]
Why not use a namespace by model?
