### ISSUE TITLE
Confusing error message when delete failure because of relationship

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#6596]
## Problem

Current error message:

```
Error: Error occurred during query execution:
InterpretationError("Error for binding \'5\'", Some(QueryGraphBuilderError(RelationViolation(RelationViolation { relation_name: "AccountToUser", model_a_name: "Account", model_b_name: "User" }))))
    at /Users/jasonkuhrt/projects/prisma/cloud/node_modules/@prisma/client/runtime/index.js:27525:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Code:

```ts
await prisma.$transaction([
  prisma.user.delete({
    where: {
      id: user1Data.user.id,
    },
  }),
  prisma.account.delete({
    where: {
      id: user1Data.user.accounts.create.id,
    },
  }),
])
```

Schema: https://github.com/prisma/cloud/blob/317e3dcd8b16c49854b5c3b53ae7bac64ec3da1c/prisma/schema.prisma#L60-L74

## Suggested solution

The solution was I had to change the order of the operations, first delete accounts, then delete users.

Being told that would be nice.

## Alternatives

Thinking more deeply, I just want to be able to delete the things and it "just work". It would be nice to not think about order at all.

**Comment by pantharshit00** [comment]
I can reproduce. We need to make this a known error. This might also be partly related to cascade delete support because you really don't need to do that if we had that but that is separate talk.

**Comment by jasonkuhrt** [comment]
@pantharshit00 is there a cascade delete issue to link to here?

**Comment by janpio** [comment]
Probably one of these: https://github.com/prisma/prisma/labels/topic%3A%20cascade

**Comment by pantharshit00** [comment]
Yeah I am talking about general cascade delete support in Prisma (PSL, client, migrate etc)

**Comment by pantharshit00** [comment]
Doesn't seem to be an issue if you enable referential actions
