### ISSUE TITLE
When `boolean` (rather than explicit `true` or `false`) values are used in `select` or `include`, infer result type as an optional field

### ISSUE THREAD

**Issue by supermacro** [prisma/prisma#6615]
## Bug description

I have a model in prisma that looks conceptually like this (simplifying for the sake of this report):

> note that acl stands for "access control list"

```
model SchoolClassroom {
  id              String @id 
  scalar_1         String @db.VarChar(1000)
  scalar_2         String @db.VarChar(50)
  scalar_3        String @db.VarChar(200)

  students Student[]
  lessons  Lesson[] 

  acl_rules       SchoolClassroomAcl[]
}

model SchoolClassroomAcl {
  user_id String

  read_permission  Boolean
  write_permission Boolean

  resource_id String
  resource    SchoolClassroom

  user User
}

model User {
  email      String @id
  first_name String
  last_name  String

  principal  Principal? @relation("principal_to_user")
  teacher    Teacher?    @relation("teacher_to_user")
  assistant  Assistant? @relation("assistant_to_user")

  classroom_acl    SchoolClassroomAcl[]    @relation("user_to_classroom_acl")
}
```

So the point is that I have the following foreign key relationships:

```
  user <--- classroom_acl --> school_classroom
   ^
   |
   | --- principals
   |
   | --- teachers
   |
   | --- assistants
```

Which means that if I want to `include` the teachers that belong to a particular classroom when I query for a `classrom` I have to do a query like this:

```typescript
prisma.schoolClassroom.findFirst({
  where: {
     id: 123,
  },
  include: {
      acl_rules: {
        include: {
          user: {
              include: {
                 teacher: true
              }
           }
         }
      }
  }
})
````

which works just fine. 

However, I need to dynamically generate the above query.

So sometimes I would like to include the `teachers` but other times I would like to specify: 

```typescript
prisma.schoolClassroom.findFirst({
  where: {
     id: 123,
  },
  include: {
    acl_rules: false
  }
})
```

Therefore, I created a type to represent this relationship:

```typescript

type SchoolClassroomInclude = {
  acl_rules: false | {  // <----- !!! NOTE THE UNION TYPE HERE !!!!
    include: {
      user: {
        include: {
          teacher: true
        }
      }
    }
  }
}
```

But unfortunately, the type returned when I call a prisma method (i.e. `findFirst`, `findMany`) with this kind of object, is:

```typescript
SchoolClassroom & {
  acl_rules: SchoolClassroomAcl[] // <---- Where's the `user` and `teacher` nested objects?
}
```

As you can see from above, the acl_rules doesn't take into consideration the fact that I am performing joins to get at the `teacher` object. 

## How to reproduce

Dynamically generate queries that either have a `false` field or a nested include as shown above. 

## Expected behavior

The return type should be nested in accordance with the nested include clause I specified in my prisma query.

## Prisma information

Prisma + prisma/client version 2.19

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v12.16.1
- Prisma version:

```
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : darwin
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.358.0
```

**Comment by supermacro** [comment]
Hey could I get some feedback on this issue please? Does what I wrote make sense, or is it confusing?

**Comment by millsp** [comment]
Hey @supermacro, we don't currently support type distribution in our TS mapped types. But this might be something we'll want to add in the future. We do provide support for your use-case in our [documentation](https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety/operating-against-partial-structures-of-model-types#problem-using-variations-of-the-generated-model-type).

In your case, you would define it in two distinctive types. I assumed that your data model is something like:
```prisma
model Classroom {
  id   Int    @id @default(autoincrement())
  acl  Acl[]
  user User[]
}

model Acl {
  id          Int       @id @default(autoincrement())
  read        Boolean
  write       Boolean

  user        User      @relation(fields: [userId], references: [id])
  userId      Int

  classroom   Classroom @relation(fields: [classroomId], references: [id])
  classroomId Int
}

model User {
  id    Int    @id @default(autoincrement())
  email String

  classroom   Classroom @relation(fields: [classroomId], references: [id])
  classroomId Int

  acl     Acl?
  teacher Teacher[]
}

model Teacher {
  id Int @id @default(autoincrement())

  user   User @relation(fields: [userId], references: [id])
  userId Int
}
```

We have a `Prisma.validator` that is a type-specific tool. It allows one to get the base types that would get yielded by `find` methods. Please take note that it is the base type, it is not an array type, you would have to add `[]` as needed:

```ts
const classroomAclUserTeacher = Prisma.validator<Prisma.ClassroomArgs>()({
    include: {
        acl: {
            include: {
                user: {
                    include: {
                        teacher: true,
                    },
                },
            },
        },
    },
});
```

```ts
type ClassroomAclUserTeacher = Prisma.ClassroomGetPayload<typeof classroomAclUserTeacher>;

const classroomOnly = Prisma.validator<Prisma.ClassroomArgs>()({
    include: {
        acl: false, // you can omit this line
    },
});

type ClassroomOnly = Prisma.ClassroomGetPayload<typeof classroomOnly>;
```

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
