### ISSUE TITLE
Netlify deploy does not pick up changes to schema file

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6634]
1. Create a repository with a minimal, mysql Prisma project
2. Create a model in the schema and migrate the DB to contain the schema (via `db push` for example)
3. Create a minimal serverless function `netlify/functions/invocation-count.js` that reads the empty table for example
4. Test everything locally via `netlify dev`
2. Create a new site in Netlify that connects to this repo
3. Set a MySQL `DATABASE_URL` env var and deploy
4. Test that the deployed function works as expected
5. Update the Netlify env var to be a PostgreSQL database (that also has the table via `db push`)
5. Update the `schema.prisma` file to use a `postgresql` provider
6. Watch Netlify deploy the updated project
7. Try the function again

I got an error telling me that the env var should have a different protocol, still `mysql://`.

Somehow it seems that the Client did not generated again when I only changed the schema file in the repository. Deplying again to Netlify with clearing the cache avoided the problem.

Reason probably is that `prisma generate` by default is only run via `npm install`, and as cache is used on a normal deploy that is not necessary. But for Prisma it kinda is, for the schema changes to becomes active in a new generated Client.

**Comment by pantharshit00** [comment]
I can reproduce this. I need to `Clear cache and redeploy` after making a change like this or add `prisma generate` to `postinstall`

**Comment by pantharshit00** [comment]
Here is the reproduction: https://serene-shannon-d8288d.netlify.app/.netlify/functions/invocation-count

**Comment by Jolg42** [comment]
I think I found why this happens:
It's mentioned in https://answers.netlify.com/t/busting-the-node-modules-cache-when-certain-files-change/45492/2

The code is here
When a project has a package.json, Netlify will create a shasum of it.
https://github.com/netlify/build-image/blob/524714d1a66d1a967316f5c39465e22c77fdd56c/run-build-functions.sh#L287
On the next build the following function will find out that the current hash of the package.json and the previous hash are the same, 
https://github.com/netlify/build-image/blob/524714d1a66d1a967316f5c39465e22c77fdd56c/run-build-functions.sh#LL93C9-L93C9
which will skip the `npm install`
https://github.com/netlify/build-image/blob/524714d1a66d1a967316f5c39465e22c77fdd56c/run-build-functions.sh#L274

This looks specific to npm, yarn and pnpm do not use that `install_deps` function.

**Comment by millsp** [comment]
Related https://github.com/prisma/docs/issues/3590
