### ISSUE TITLE
additional arguments for Prisma CLI to override datasource

### ISSUE THREAD

**Issue by rwitchell** [prisma/prisma#6652]
## Problem

When running jest, the ideal process would be to run each test separately. This means each test creating it's own PrismaClient. The PrismaClient would need to connect to it's own database (or easier, it's own database schema within a database) to run it's test, and then clean up by deleting the data.
There are two issues currently: 
1. The `datasources` arg within `PrismaClient()` does not seem to accept the 'schema' on `datasources.db.url`;
2. executing `prisma db push` uses the DB url within schema.prisma and cannot currently be overridden with a dynamic variable

## Suggested solution

Basing my code on the nexusjs tutorial, something similar to the below would be helpful:

Notes are:
- my database URL can have a dynamic database schema appended
- prisma CLI will use this database URL when interacting with the datasource

```js
// generate a random schema ID
  const databaseSchemaName = Math.random().toString(36).substr(2, 9)
  return {
    async before() {
      const databaseUrl = `${process.env.DATABASE_URL}?schema=${databaseSchemaName}&connection_limit=1`
      // Run the migrations to ensure our schema has the required structure
      execSync(`${prismaBinary} --datasource.db.url=${databaseUrl} db push --preview-feature`)

      // Construct a new Prisma Client connected to the generated schema
      prismaClient = new PrismaClient({
        datasources: {
          db: {
            url: databaseUrl,
          },
        },
      })

      return prismaClient
    },
    async after() {
      // Drop the schema after the tests have completed
      // await database.close()
      await prismaClient?.$executeRaw(
        `DROP SCHEMA IF EXISTS ${databaseSchemaName};`
      )

      // Release the Prisma Client connection
      await prismaClient?.$disconnect()
    },
  }
```

**Comment by janpio** [comment]
You should indeed be able to to dynamically provide a data source URL to `PrismaClient`:
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#programmatically-override-a-datasource-url
```
const prisma = new PrismaClient({
  datasources: {
    db: {
      url: 'file:./dev_qa.db',
    },
  },
})
```
If you are using Postgres or MySQL the value of course would be the connection string.

> The datasources arg within PrismaClient() does not seem to accept the 'schema' on datasources.db.url;

Do I understand you message correctly that this is not working correctly? (Note that `db` is the name of your `datasource` block in your `schema.prisma` file and you could potentially have a different name defined there.)

---

That of course does not help with `prisma db push` and other CLI commands. There the best approach is using an env variable in the schema file, and then changing that value when executing the command. This is one approach: https://www.prisma.io/docs/concepts/components/prisma-schema#example-set-the-database_url-environment-variable-in-an-env-file + https://www.prisma.io/docs/concepts/components/prisma-schema#via-command-line

---

Being able to supply a specific datasource.db.url via a CLI parameter is an interesting idea though, and I think you could open a feature request issue about this: https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=feature_request.md&title= Seems a bit more practical than our current solution even!

**Comment by rwitchell** [comment]
Hi Jan,

RE: `?schema` - i've realised I had a bug, now working correctly.


Also, with the CLI commands, as i'm altering the env variable during runtime, the CLI command is looking at the original env file. As you mention, I will manipulate the `process.env` directly. One note with this method: the database URL needs to be stored in a different var, otherwise concurrency will keep appending onto previous values (`?schema=a1?schema=a2`).

Ideally, supplying a specific value via CLI parameter might be nice.

it's working nicely as below:

```
.env.test
ORIGINAL_DATABASE_URL="postgres://user:pass@db_url.com:5432/database_name"
DATABASE_URL="this-is-written-via-a-script"
```

```js
// generate a random schema ID
  const databaseSchemaName = Math.random().toString(36).substr(2, 9)

  return {
    async before() {
      const databaseUrl = `${process.env.ORIGINAL_DATABASE_URL}?schema=${databaseSchemaName}&connection_limit=1`
      process.env.DATABASE_URL = databaseUrl

      // Run the migrations to ensure our schema has the required structure
      execSync(
        `DATABASE_URL="${databaseUrl}" ${prismaBinary} db push --preview-feature`
      )

      // Construct a new Prisma Client connected to the generated schema
      prismaClient = new PrismaClient({
        datasources: {
          db: {
            url: databaseUrl,
          },
        },
      })

      return prismaClient
    },
    async after() {
      // Drop the schema after the tests have completed
      // await database.close()
      await prismaClient?.$executeRaw(
        `DROP SCHEMA IF EXISTS "${databaseSchemaName}" CASCADE;`
      )

      // Release the Prisma Client connection
      await prismaClient?.$disconnect()
    },
  }


```

**Comment by janpio** [comment]
Open that feature request issue, and we can make sure this is being tracked long term 👍 

But great that you figured out a way that works for you, and also worked around the bumps along the way with variables and so on - it is easy to get this stuff slightly wrong.
