### ISSUE TITLE
Nextjs function can't find binary on Netlify

### ISSUE THREAD

**Issue by pedrosousa13** [prisma/prisma#6654]
## Bug description

Nextjs project deployed to netlify give giving me error on function. I already cleared the cache on my build process and added.

Build step `prisma generate && next build` using yarn.

## Prisma information

```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

## Environment & setup

- OS: Debian (netlify)
- Database: MySQL
- Prisma version: 2.21.2

```
PrismaClientInitializationError2 [PrismaClientInitializationError]: Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/query-engine-rhel-openssl-1.0.x")

Searched Locations:

  /.prisma/client
  /opt/build/repo/node_modules/@prisma/client
  /
  /var/task/node_modules/.prisma/client
  /var/task
  /tmp/prisma-engines
  /var/task/node_modules/.prisma/client

You already added the platforms "native", "rhel-openssl-1.0.x" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new
    at cb (/var/task/src/nextPage/index.js:40268:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.21.2',
  errorCode: undefined
}
```

I am also using the db.ts specified in the next instructions:

```
declare global {
  namespace NodeJS {
    interface Global {
      prisma: any;
    }
  }
}

let prisma: PrismaClient

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient()
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient()
  }
  prisma = global.prisma
}
export default prisma
```

**Comment by janpio** [comment]
Where exactly are you getting this error message - during build or in the deployed Netlify function?

**Comment by millsp** [comment]
This issue is being tracked here https://github.com/prisma/prisma/issues/6051

**Comment by pedrosousa13** [comment]
@janpio I'm getting whenever I try to access the function via any http request.

**Comment by millsp** [comment]
Netlify's bundling tool `zip-it-and-ship-it` includes your dependency files into the zip file by looking at your imports. Since `next` rewrites all imports with `webpack`, `zip-it-and-ship-it` will not see the import and files such as binaries won't be bundled. Netlify is working on a general solution for these kind of issues, but without any concrete date yet. I propose this workaround, where we simply exclude `@prisma/client` from being bundled:

*next.config.js*
```ts
module.exports = {
    webpack: (config, { isServer } ) => {
        if (isServer) {
            config.externals.push('@prisma/client')
        }

        return config
    },
    target: "serverless"
}
```

**Comment by pantharshit00** [comment]
I am going to close this. Please follow the latest netlify deployment guide from the documentation here now.
