### ISSUE TITLE
Oops, an unexpected error occured! error: Error validating: The relation field `user` uses the scalar fields userId. At least one of those fields is required.  Hence the relation field must be required. report id 13238            

### ISSUE THREAD

**Issue by JeevantheDev** [prisma/prisma#6665]
```
Oops, an unexpected error occured!
error: Error validating: The relation field `user` uses the scalar fields userId. At least one of those fields is required. 
Hence the relation field must be required as well.
  -->  schema.prisma:12
   | 
11 |   id                        Int               @default(autoincrement()) @id
12 |   user                      User?             @relation(fields: [userId], references: [id])
13 |   userId                    Int               
```

**Comment by janpio** [comment]
Hi @JeevantheDev - your issue title indicates this is connected to error report 13238 - which I could also find in our system and matches the error you are posting here.

Usually this should just be a validation error though, and means you should fix something in your schema.

Can you maybe post the complete output you are getting when running the CLI command?

I also see from the error report that you are using CLI `2.1.1`. That is _reeeeeeaaaaaally_ old. Can you please upgrading your CLI and Prisma Client to a more recent version? Thanks.

**Comment by JeevantheDev** [comment]
Ya ya I got it @janpio I have to upgrade the CLI.
Thanks for reply.
