### ISSUE TITLE
ScaleGrid PostgreSQL clusters only allow access via PgBouncer or directly, not both at the same time

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6701]
We are currently recommending people to use a non PgBouncer connection to migrate their database. This is based on our knowledge of setting up PgBouncer ourselves, and commercial offerings like DigitalOcean.

Unfortunately it seems that [ScaleGrid's PostgreSQL](https://scalegrid.io/postgresql.html) offering behaves slightly different in that it turns of direct access when you enable PgBouncer:

![image](https://user-images.githubusercontent.com/183673/115618957-9fff6680-a2f3-11eb-9914-374601d314b3.png)

After enabling PgBouncer, on connection with the old working credentials you get an error like this:

```
FATAL: no pg_hba.conf entry for host "...", user "sgpostgres", database "postgres", SSL off
```

Similar thing happens when disabling PgBouncer again:

![image](https://user-images.githubusercontent.com/183673/115622034-9f68cf00-a2f7-11eb-97fe-099b8adeb534.png)

This is a problem, as our recommended workaround on how to get Migration and Introspection Engine to work with a pooled setup does not work.

**Comment by janpio** [comment]
## Workaround

After communication with ScaleGrid, they let us know that they understand this use case and are happy to re-enable communication with the direct database connection on port 5432 when people reach out to their support via E-Mail or support chat widget 👍 Thanks Scalegrid! ❤️ 

They also explained why they by default disable the direct communication: 

> we turn off communication on port 5432 whenever PgBouncer is enabled to avoid overflow of connections to PostgreSQL unknowingly from the client-side

This makes a lot of sense as well and is actually pretty good for users, so they can not make the mistake of using the wrong connection string in the wrong context.

**Comment by tomhoule** [comment]
That's good news! Does it mean this issue can be closed?

**Comment by janpio** [comment]
Yes, but let's add this to documentation first and then link from here.
And keep the issue around here, so people can find it in the repo (and via Google).

**Comment by pantharshit00** [comment]
This is documented now
