### ISSUE TITLE
Prisma doesn't solve N+1 in basic scenario

### ISSUE THREAD

**Issue by liadmat** [prisma/prisma#6703]
## Bug description

Often (especially in GraphQL) we want to request resources that are related to some other resource, e.g. tasks that belong to a user.

When querying the resources using `findMany({ where: { ... } })`, Prisma doesn't optimize for N+1.

## How to reproduce

Reproduction: https://github.com/liadmat/prisma-repro/blob/main/src/index.ts

## Expected behavior

Prisma should be able to optimize this as it does with nested read API.

**Comment by janpio** [comment]
Thank you for the reproduction, we are tracking this at https://github.com/prisma/prisma/issues/1477 already. I will add your message as a comment there though as it provides a nice reproduction.
