### ISSUE TITLE
Shared query-engine instances for integration testing

### ISSUE THREAD

**Issue by MattGson** [prisma/prisma#6707]
## Problem

When integration testing, it is common to isolate test suites to each run their own setup.
In fact Jest enforces this behaviour making it impossible to share runtime data between different suites.

This has many benefits but means that every suite duplicates the required resources to run the tests.
With integration tests, this includes app instances, database pools etc.

When creating a Prisma client instance, it starts a corresponding query-engine. This engine normally uses in the realm of 100-300MB of memory. 

During integration tests, each test suite will start a new query-engine. Sometimes more than one i.e. one used in tests for seeding etc, one in a testing app instance (i.e. supertest).

When running many test suites the memory consumed by the query-engines can quickly cripple even a large CI server.

## Suggested solution

Prisma client instances should be able to be created with either a `share engine` option or a `engine id` option.
This would allow multiple clients to communicate with the same query-engine.

![Screen Shot 2021-04-17 at 2 32 36 PM](https://user-images.githubusercontent.com/20088009/115656058-970ca480-a388-11eb-8052-b03f8958251c.png)

**Comment by pantharshit00** [comment]
@MattGson Can you try the NAPI preview here once? That method of communication won't spawn the binary and instead node will directly call the Rust functions.

Check it out here: https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#enable-the-n-api-preview

Preview feature umbrella issue: https://github.com/prisma/prisma/issues/6301

**Comment by janpio** [comment]
This is a good point @MattGson - the preview feature that Harshit linked to certainly might help here. 

Is this also a problem is you ramp down the QE after each test with `prisma.$disconnect()`?
Generally reusing the same binary process, which you are suggesting, might have side effects on your tests unfortunately because of connection state (although in 99.999% this will not affect you).)

**Comment by MattGson** [comment]
@pantharshit00 I will give it a go but I believe some of my colleagues have tried it and found it wasn't ready for our use case yet.

@janpio I have actually been using `prisma.$disconnect()` without any luck. I think I might have cracked it using a combination of `prisma.$disconnect()` , and `--runInBand` flag with jest. A key thing was also to remove the `--forceExit` flag. I believe this flag may have been killing the node process before the $disconnect actually completed leaving the query engine process running.

**Comment by janpio** [comment]
We do not have a Query Engine _binary_ any more unless using a non default configuration, so I think we can close this. Thanks for opening an issue back in the day!
