### ISSUE TITLE
MongoDB: Support for embedded documents

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#6708]
## Problem

One of the major features of MongoDB is how you can store embedded data within a record. MongoDB also offers rich querying capabilities to work with this data.

Currently the Prisma Client supports writing embedded documents with the Json type

```prisma
model User {
  name String
  address Json
}
```

```typescript
prisma.user.create({
  data: {
    name: "Alice"
    address: {
      street: "1234 Wonderland Ave"
      zip: "12351"
    }
  }
})
```

Unfortunately this isn't type-safe. Nothing stops you from adding another random field to the address or writing "street" as "st".

Additionally, we currently only support a few operations on the Json type for MongoDB.

## Goal

- We'd like to introduce a new way to store and query embedded data in a type-safe way.
- We'd like to be able to apply this new approach to other DBs with JSON support like Postgres.

## Suggested solution

Add support for embeds. Potentially introduce an `embed` keyword in the Prisma schema

```prisma
model User {
  name String
  address Address
}

embed Address {
  street String
  zip String
}
```

## Alternatives

While above feels clean, one issue is that embed seems to be an attribute of the Address, not a defining feature of the Address. You might want Address to be embedded in some model, but relational in others. That makes me think that the caller should decide, not the definer.

```prisma
model User {
  name String
  address Address @embed
}

model Address {
  street String
  zip String
}
```

The upside to this is that there's no new blocks either.

## Additional context

- Original [MongoDB issue](https://github.com/prisma/prisma/issues/1277)

**Comment by coyotte508** [comment]
Just chiming in that the `@embed` approach seems necessary, at least in addition to the first approach.

In case we have projects, milestones, and tasks:

```prisma
model Project {
  type ProjectType
  milestones Milestone[] @embed
}

model Milestone {
  type ProjectType
  tasks Task[] @embed
}

model Task {
  name string
  action: Action
  doneAt Date?
}
```

In our case `Task` would always be embedded, but Milestones will live in their own collection / be duplicated into a project when the project is created.

The duplication is purposeful: we can edit the milestones / tasks of a project (add custom tasks,  mark them as done...). We can also edit the default milestones without impacting the already created projects.

**Comment by PinkaminaDianePie** [comment]
What about the case when I do not want the model to be available outside of its parent? With such solution
```prisma
model User {
  name String
  address Address @embed
}

model Address {
  street
  zip
}
```
It will be possible to add an address to the separate collection, and that's a side effect of `@embed` in that case.
Another issue that API will be not intuitive, consider the case:
```js
prisma.user.create({ data: { name: 'foo', address: { /* what should be here? */ } } })
```
should I put `connect`? probably no, because the existence of `address` collection is a side effect, so even having such an option in auto-complete is misleading in my case. `create`? I have no idea if it will just embed it into the `user`, or create a new entry in `address` collection and then embed it as well. Still, creating a separate entry is a side effect in my case. `connectOrCreate`? Don't even ask how will it work in the case of mongo. Old API is just too hard to reason about here.

Now, what about the case, when I want to both embed the address and keep it as a separate entry? In this case, if `Address` model will have lots of heavy data, we might want to embed only part of it to the user. That's common for mongo, we embed only things we need, not everything. For example, we might want to embed an object with just an id and a few fields we need to show address in the UI, not entire data about building construction date and type of the soil under it. Again, we will need 2 separate models, one for embedding, and one for storing complete data. But when we go back to the first issue, how will it work with `create`? Will it just create a separate collection to store the copies of embedded data? We don't want it.

I don't see any other options but to stick with solution #1. I don't know how it works under the hood/how hard will it be to implement, but my proposal is:
```prisma
model User {
  name String
  address Address
}

embed Address {
  street
  zip
}

model Address {
  street
  zip
  // lots of other heavy data
}
```
in such case it will work like that:

- in case if we wanna ONLY to embed something, we use the keyword `embed`.
- If we wanna both embed and store separately - we create 2 models with the same name but using `embed` and `model` at the same time.
- Fields in `model` should be a superset of fields in `embed`, so we can add additional fields, but not change them.
- `create` in the case of having only `embed` will only embed. `connect` and `connectOrCreate` won't be exposed at all.
- in case of having both `model` and `embed` - create will accept data for `model` (all fields), create an entry in `Address` collection, but embed only parts of it, since `embed` data are a subset of `model` data.
- in case of `connect` - will get a subset of data, specified in `embed` from entry in Address collection and embed it.
- connectOrCreate - same as above, full data, embed only part of it, create an entry by a full data if necessary

**Comment by teddybee** [comment]
I ran into this problem few minutes ago. I have a field that contains array of items, but I wouldn`t store them in different collections with id-s (similarly complicated that the Address type above). I just want store the array as plain json array in a document.

**Comment by dimaip** [comment]
Oh wow, just stumbled upon this and I'm pretty surprised with the lack of support for this... I mean, what's the point of supporting a document-oriented database without support for actual documents? :-)
This is a blocker for us (and I'm sure for many other projects) so I'm really hoping it would get worked on soon!

Any estimates when there's a chance it would get implemented?

**Comment by matthewmueller** [comment]
Hey everyone, thanks for the very thoughtful discussion! 

@dimaip yep, we're aware that it prevents lots of teams from using MongoDB right now. It's the next project we'll be working on for MongoDB.

**Comment by uptownhr** [comment]
@embed would be awesome for defining JSONB columns as well.

**Comment by matthewmueller** [comment]
Yep, you can use the Json type in Mongo. See: https://github.com/prisma/prisma/releases/tag/2.24.0

**Comment by macrozone** [comment]
this should be also available for other dbs if possible to make it consistent.

but its first and foremost important for prisma1-mongodb users to migrate to prisma2

see also https://github.com/prisma/prisma/issues/3014

**Comment by matthewmueller** [comment]
Hey everyone! I just want to share that we've come up with a design for this. Please let me know what you think and if you have any questions!

Also if you feel like discussing the proposal in more detail, you can schedule a short call with me here: https://calendly.com/matthewmueller/embedded-documents.

# Overview of the solution

This solution extends the Prisma Schema to support defining your own custom types. 

In the following example, we define `Address` and `Pet` embedded types that we use within our `User` model:

```groovy
type Address {
  zip     Int
  street  String 
  country String
}

type Pet {
  type  String
  breed String
  name  String
}

model User {
  id      String @id @default(dbgenerated()) @db.ObjectId @map("_id")
  name    String
  address Address
  pets    Pet[]
}
```

# Outcome

This solution has the following design goals:

- Embedded data access has the same API as relational data access
- Introspecting embedded data will be possible to add in the future with this design
- Migrating embedded data will be possible to add in the future with this design
- General enough to eventually support Typed JSON for SQL databases

By achieving these goals, developers using MongoDB will be able to work with embedded documents in the same way they can work with relational documents. There won't be anything new to learn and you get a new way of storing and accessing data.

This can solution can be ported to SQL databases that support a `json` column, giving developers a type-safe embedded data access for relational databases.

Lastly, this may give us a way to "mixin" types with models, allowing developers to [reuse fields inside a model](https://github.com/prisma/prisma/issues/2371).

# FAQ

- **Is it a property of the "relation" or a property of the embedded model itself?**

    In Prisma1, it was basically both - a relation to a model annotated with embed

- **Do embeds need IDs?**

    No, embed aren't addressable on their own. They are always reached from a model which does have an ID.

- **What about uniques in embeds?**

    Depends on the underlying capability. If it's possible in the underlying source it should be possible. However, it doesn't seem like it's currently possible [https://joegornick.com/2012/10/25/mongodb-unique-indexes-on-single/embedded-documents/](https://joegornick.com/2012/10/25/mongodb-unique-indexes-on-single/embedded-documents/)

- **Do embeds have backrelations (e.g. accessing posts from authors)?**

    No. Since the embeds are not a top-level, standalone model, there isn't a case where you have an embed and need to reach the model.

- **Can embeds have relations to other models?**

    If the underlying datasource can define a foreign key on the embedded type, it should be possible, but this would be out of scope for the first iteration. You could always pull the foreign key and lookup the relation in a separate query.

- **Can an embed be nested within another embed (type in a type)?**

    Nothing should prevent this, but not a high priority for the first iteration of the solution.

- **Embeds as an ID?**

    This should be possible because MongoDB supports objects as primary keys, but supporting this use case is low priority.

- **Do embeds need to be uniquely named?**

    Yes, for now because it simplifies the solution. Since types are a purely Prisma construct and not tied to the database, you could have a type name that's also a model name. 

# References

- MongoDB Embedded Documents: [https://github.com/prisma/prisma/issues/6708](https://github.com/prisma/prisma/issues/6708)
- SQL @embed objects: [https://github.com/prisma/prisma/issues/3014](https://github.com/prisma/prisma/issues/3014)
- Option to select inside JSON fields: [https://github.com/prisma/prisma/issues/2431](https://github.com/prisma/prisma/issues/2431) (tangent)
- Prisma 1 Embeds: [https://v1.prisma.io/docs/1.34/releases-and-maintenance/features-in-preview/mongodb-b6o5/#data-modeling](https://v1.prisma.io/docs/1.34/releases-and-maintenance/features-in-preview/mongodb-b6o5/#data-modeling)

**Comment by macrozone** [comment]
> Hey everyone! I just want to share that we've come up with a design for this. Please let me know what you think and if you have any questions!
> 
> Also if you feel like discussing the proposal in more detail, you can schedule a short call with me here: https://calendly.com/matthewmueller/embedded-documents.
> 
> # Overview of the solution
> This solution extends the Prisma Schema to support defining your own custom types.
> 
> In the following example, we define `Address` and `Pet` as embedded types that we use within our `User` model:
> 
> ```groovy
> type Address {
>   zip     Int
>   street  String 
>   country String
> }
> 
> type Pet {
>   type  String
>   breed String
>   name  String
> }
> 
> model User {
>   id      String @id @default(dbgenerated()) @db.ObjectId @map("_id")
>   name    String
>   address Address
>   pets    Pet[]
> }
> ```
> 
> # Outcome
> This solution has the following design goals:
> 
> * Embedded data access has the same API as relational data access
> * Introspecting embedded data will be possible to add in the future with this design
> * Migrating embedded data will be possible to add in the future with this design
> * General enough to eventually support Typed JSON for SQL databases
> 
> By achieving these goals, developers using MongoDB will be able to work with embedded documents in the same way they can work with relational documents. There won't be anything new to learn and you get a new way of storing and accessing data.
> 
> This can solution can be ported to SQL databases that support a `json` column, giving developers a type-safe embedded data access for relational databases.
> 
> Lastly, this may give us a way to "mixin" types with models, allowing developers to [reuse fields inside a model](https://github.com/prisma/prisma/issues/2371).
> 
> # FAQ
> * **Is it a property of the "relation" or a property of the embedded model itself?**
>   In Prisma1, it was basically both - a relation to a model annotated with embed
> * **Do embeds need IDs?**
>   No, embed aren't addressable on their own. They are always reached from a model which does have an ID.
> * **What about uniques in embeds?**
>   Depends on the underlying capability. If it's possible in the underlying source it should be possible. However, it doesn't seem like it's currently possible https://joegornick.com/2012/10/25/mongodb-unique-indexes-on-single/embedded-documents/
> * **Do embeds have backrelations (e.g. accessing posts from authors)?**
>   No. Since the embeds are not a top-level, standalone model, there isn't a case where you have an embed and need to reach the model.
> * **Can embeds have relations to other models?**
>   If the underlying datasource can define a foreign key on the embedded type, it should be possible, but this would be out of scope for the first iteration. You could always pull the foreign key and lookup the relation in a separate query.
> * **Can an embed be nested within another embed (type in a type)?**
>   Nothing should prevent this, but not a high priority for the first iteration of the solution.
> * **Embeds as an ID?**
>   This should be possible because MongoDB supports objects as primary keys, but supporting this use case is low priority.
> * **Do embeds need to be uniquely named?**
>   Yes, for now because it simplifies the solution. Since types are a purely Prisma construct and not tied to the database, you could have a type name that's also a model name.
> 
> # References
> * MongoDB Embedded Documents: [MongoDB: Support for embedded documents #6708](https://github.com/prisma/prisma/issues/6708)
> * SQL @embed objects: [@embed objects #3014](https://github.com/prisma/prisma/issues/3014)
> * Option to select inside JSON fields: [Option to select inside JSON fields #2431](https://github.com/prisma/prisma/issues/2431) (tangent)
> * Prisma 1 Embeds: https://v1.prisma.io/docs/1.34/releases-and-maintenance/features-in-preview/mongodb-b6o5/#data-modeling

this sounds really simple and great! If you can pull this off, i will be very happy. Hope it makes its way to postgres as well!

**Comment by mikerudge** [comment]
Really looking forward to this. Any kinda estimate of when this would out (even in a beta)?

**Comment by loicnestler** [comment]
Any updates / ETA on this? Really looking forward into this feature!

**Comment by matthewmueller** [comment]
@andefred I'd love to chat! Do you mind scheduling some time here? https://calendly.com/matthewmueller/embedded-documents

**Comment by matthewmueller** [comment]
Hey all, I just wanted to share that Embedded Document support for MongoDB is now in Preview!

It's easy to get started. If you're not already, add the `mongoDb` preview feature flag:

```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}
```

Then you'll have a new `type` keyword in your Prisma Schema, for example:

```
model Order {
  id              String   @id @default(auto()) @map("_id") @db.ObjectId
  product         Product  @relation(fields: [productId], references: [id])
  color           Color
  size            Size
  shippingAddress Address
  billingAddress  Address?
  productId       String   @db.ObjectId
}

type Address {
  street String
  city   String
  zip    String
}
```

Once you run `prisma generate`, you'll have a new type-safe API for working with these types.

For example, here's how you'd create a new Order:

```ts
const order = await prisma.order.create({
  data: {
    // Normal relation
    product: { connect: { id: 'some-object-id' } },
    color: 'Red',
    size: 'Large',
    // Composite type
    shippingAddress: {
      street: '1084 Candycane Lane',
      city: 'Silverlake',
      zip: '84323',
    },
  },
})
```

This is just the tip of the iceberg. Dive deeper in [our documentation](https://www.prisma.io/docs/concepts/components/prisma-client/composite-types). 

If you have any feedback for us, I'd love to jump on [a call with you](https://calendly.com/matthewmueller/embedded-documents). 

We're actively working towards getting MongoDB production ready, so now's the time to give this a try and share your thoughts!

**Comment by willemmulder** [comment]
Nice work! And thanks for the update!

**Comment by matthewmueller** [comment]
Closing since this now in 3.10.0.

Please give this a go! Then let's [schedule a quick call](https://calendly.com/matthewmueller/embedded-documents) or drop a comment in [this issue](https://github.com/prisma/prisma/issues/8241) with your thoughts.

🍻
