### ISSUE TITLE
Prisma Client: expose a ObjectID() method to generate a valid Mongo ObjectID

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#6718]
## Problem

Given this schema that has `@db.ObjectId`
```schema.prisma
datasource db {
    provider = "mongodb"
    url      = env("DATABASE_URL")
}

generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["mongodb"]
}

model User {
  id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  email String @unique
  name  String?
}
```

If you want to first create an `id` and then do operations (useful during testing for example) the `id` needs to be a valid Mongo ObjectID

Example, setting it to `randommongoid1234` returns
```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.user.create()` invocation:
  Inconsistent column data: Malformed ObjectID: Odd number of digits.
    at cb (/home/runner/work/e2e-tests/e2e-tests/databases/mongodb-atlas/node_modules/@prisma/client/runtime/index.js:34780:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2023',
  clientVersion: '2.22.0-dev.13',
  meta: { message: 'Malformed ObjectID: Odd number of digits.' }
}
```

Example code used for [tests](https://github.com/prisma/e2e-tests/blob/91d99a286b0813eb6aac021d53c1fc7fcf6ceba5/databases/mongodb-atlas/script.ts)
```js
  const objectId = '6d795f757365725f69643030'

  await client.user.create({
    data: {
      id: objectId,
      email: 'alice@prisma.io',
      name: 'Alice',
    },
  })

  const user = await client.user.findUnique({
    where: {
      id: objectId,
    },
  })

  const expect = JSON.stringify({
    id: objectId,
    email: 'alice@prisma.io',
    name: 'Alice',
  })

  if (JSON.stringify(user) !== expect) {
    console.error('expected', expect, 'got', user)
    process.exit(1)
  }
```

## Suggested solution

Expose an ObjectID() method, for example like:
```js
  const { PrismaClient, Prisma } = require('@prisma/client')
  const myRandomObjectID = Prisma.ObjectID().toString()
```

## Alternatives

Installing Mongo Node.js driver and using the method there:
```js
 const ObjectID = require('mongodb').ObjectID;
 const objectId = new ObjectID().toString();
```

**Comment by dpetrick** [comment]
> If you want to first create an id and then do operations (useful during testing for example) the id needs to be a valid Mongo ObjectID

That is not required. You can easily do:
```prisma
model User {
  id    String @id @map("_id")
  email String @unique
  name  String?
}
```
And send explicit ids along. Or use ints, etc.

**Comment by Jolg42** [comment]
@dpetrick Though in the case where you want valid Mongo ObjectID (existing db or else) I would prefer to keep `@db.ObjectId`

Docs from ObjectId https://docs.mongodb.com/manual/reference/method/ObjectId/

    The 12-byte ObjectId value consists of:
    a 4-byte timestamp value, representing the ObjectId's creation, measured in seconds since the Unix epoch
    a 5-byte random value
    a 3-byte incrementing counter, initialized to a random value

These properties can be interesting to keep in general I guess, rather than switching to a custom id.

**Comment by dpetrick** [comment]
In that case the client should pull in `bson-js` as needed and directly send a valid ObjectID. ObjectID is specific to MongoDB and not generally applicable like other functionaility available for defaults (`cuid`, `uuid`), so I'm reluctant to add it as the odd one out.
