### ISSUE TITLE
Error when running prisma+mongodb with connection string with no database name (using Azure Cosmos DB With Mongo API)

### ISSUE THREAD

**Issue by luisrudge** [prisma/prisma#6726]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v15.11.0           | 
| OS              | darwin             |
| Prisma Client   | 2.21.2             |
| Query Engine    | query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d|
| Database        | undefined|

## Query
```
mutation {
  createOneStore(data: {
    name: "X"
    url: "X"
  }) {
    id
    createdAt
    updatedAt
    name
    url
  }
}
```

## Logs
```
ne stderr  [query-engine/connectors/mongodb-query-connector/src/error.rs:28] &self = DriverError(  +3s
  prisma:engine stderr      Error {  
  prisma:engine stderr          kind: CommandError(  
  prisma:engine stderr              CommandError {  
  prisma:engine stderr                  code: 73,  
  prisma:engine stderr                  code_name: "InvalidNamespace",  
  prisma:engine stderr                  message: "Database name can\'t be empty.",  
  prisma:engine stderr                  labels: [],  
  prisma:engine stderr              },  
  prisma:engine stderr          ),  
  prisma:engine stderr          labels: [],  
  prisma:engine stderr      },  
  prisma:engine stderr  )  
  prisma:engine stdout  PANIC in query-engine/connectors/mongodb-query-connector/src/error.rs:104:63
not yet implemented  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/luisrudge/code/prismamongo/node_modules/@prisma/client/runtime/index.js:25205:24)
  prisma:engine       at Socket.emit (node:events:390:22)
  prisma:engine       at Socket.EventEmitter.emit (node:domain:470:12)
  prisma:engine       at endReadableNT (node:internal/streams/readable:1307:12)
  prisma:engine       at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:64078
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 64078
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/Users/luisrudge/code/prismamongo/prisma' }  
  prisma:engine Search for Query Engine in /Users/luisrudge/code/prismamongo/node_modules/.prisma/client  
  plusX Execution permissions of /Users/luisrudge/code/prismamongo/node_modules/.prisma/client/query-engine-darwin are fine  +3s
  prisma:engine {
  prisma:engine   flags: [
  prisma:engine     '--enable-experimental=mongodb,mongodb',
  prisma:engine     '--enable-raw-queries',
  prisma:engine     '--port',
  prisma:engine     '64108'
  prisma:engine   ]
  prisma:engine }  
  prisma:engine stdout  Started http server on http://127.0.0.1:64108  
  prisma:engine Search for Query Engine in /Users/luisrudge/code/prismamongo/node_modules/.prisma/client  
  plusX Execution permissions of /Users/luisrudge/code/prismamongo/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.21.2  
  prisma:engine Engine Version: query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d  
  prisma:engine Active provider: mongodb  
  prisma:engine stderr  [query-engine/connectors/mongodb-query-connector/src/error.rs:28] &self = DriverError(  +1s
  prisma:engine stderr      Error {  
  prisma:engine stderr          kind: CommandError(  
  prisma:engine stderr              CommandError {  
  prisma:engine stderr                  code: 73,  
  prisma:engine stderr                  code_name: "InvalidNamespace",  
  prisma:engine stderr                  message: "Database name can\'t be empty.",  
  prisma:engine stderr                  labels: [],  
  prisma:engine stderr              },  
  prisma:engine stderr          ),  
  prisma:engine stderr          labels: [],  
  prisma:engine stderr      },  
  prisma:engine stderr  )  
  prisma:engine stdout  PANIC in query-engine/connectors/mongodb-query-connector/src/error.rs:104:63
not yet implemented  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/luisrudge/code/prismamongo/node_modules/@prisma/client/runtime/index.js:25205:24)
  prisma:engine       at Socket.emit (node:events:390:22)
  prisma:engine       at Socket.EventEmitter.emit (node:domain:470:12)
  prisma:engine       at endReadableNT (node:internal/streams/readable:1307:12)
  prisma:engine       at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  await prisma.$connect();

  // Create the first post
  await prisma.store.create({
    data: {
      name: "Test Store",
      url: "https://test.com",
    },
  });

  // Read all the posts
  const stores = await prisma.store.findMany();

  // Log our posts showing nested structures
  console.dir(stores, { depth: Infinity });
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());

```

## Schema
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

model Store {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name      String
  url       String
}
```

**Comment by luisrudge** [comment]
I know that this is probably an edge case between different mongodb versions, but it'd be great if we could use prisma+cosmos db, since it's supposed to share most of mongo's apis. Here's the specs:
https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-feature-support-40

**Comment by luisrudge** [comment]
Ops, nevermind. My fault not using the correct connection string. For future reference, if you're copy/pasting the connection string from the Azure Portal, make sure you add the database name to the connection string.

When you copy from the Azure Portal, you'll get something like this:
`mongodb://aaa:bbb@ccc.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@ddd@`

You can add your database name before the query string, like this:
`mongodb://aaa:bbb@ccc.mongo.cosmos.azure.com:10255/YOUR_DB_NAME_HERE?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@ddd@`

more info here: https://docs.microsoft.com/en-us/azure/cosmos-db/connect-mongodb-account

**Comment by janpio** [comment]
We usually default to some database name per connector I think, and have a much better error message here - so I think this is a valid issue where we can improve the situation. Thanks @luisrudge!

**Comment by matthewmueller** [comment]
Thanks for your repro! I think this one is similar (or the same?) as #6431. I think it's worth keeping open as a reminder to also check CosmosDB (which is MongoDB-wire compatible).

**Comment by xdave** [comment]
It's technically possible to connect without selecting a database in the connection string.  Other mongodb clients support selecting different databases inside of the same connection.

For many, this could be a required use case, for multi-tenant applications.

**Comment by pantharshit00** [comment]
I will mark as confirmed bug for now. Behavior is but undefined for the client here whether we should require this or not.

**Comment by janpio** [comment]
Some research:

For relational databases Prisma defaults to specific database names if non is provided in the connection string:
- MySQL: `mysql` (but prevent Migrations)
- PostgreSQL: `postgres`
- SQL Server: `master`
- SQLite: n/a

On MongoDB:
- MongoDB seems to have 3 of these default databases: `admin`, `local` and `config`: https://docs.mongodb.com/manual/reference/system-collections/ + https://docs.mongodb.com/manual/reference/local-database/ + https://docs.mongodb.com/manual/reference/config-database/
- MongoDB tooling itself seems to connect to `test` by default if no specific database name is provided: https://docs.mongodb.com/mongodb-shell/connect/#connect-to-a-specific-database

**Comment by janpio** [comment]
We think that erroring out when no database name is supplied is the right thing to do - but it should happen much earlier to be less confusing. This work is being tracked in https://github.com/prisma/prisma/issues/11909

**Comment by pimeys** [comment]
Made a clear error in https://github.com/prisma/prisma-engines/pull/2702

**Comment by janpio** [comment]
![image](https://user-images.githubusercontent.com/183673/155535020-51fb38e6-4316-433c-bf29-82303f5687f6.png)

**Comment by sergomen** [comment]
> Ops, nevermind. My fault not using the correct connection string. For future reference, if you're copy/pasting the connection string from the Azure Portal, make sure you add the database name to the connection string.
> 
> When you copy from the Azure Portal, you'll get something like this: `mongodb://aaa:bbb@ccc.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@ddd@`
> 
> You can add your database name before the query string, like this: `mongodb://aaa:bbb@ccc.mongo.cosmos.azure.com:10255/YOUR_DB_NAME_HERE?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@ddd@`
> 
> more info here: https://docs.microsoft.com/en-us/azure/cosmos-db/connect-mongodb-account

Thank you, a lot! I love you! I just tryed to connect prisma with mongodb, but I used db connection string for another old collection. Didn't expect that. And didn't know that I can to use <dbname>. :)
