### ISSUE TITLE
MongoDB: @unique constraint not working

### ISSUE THREAD

**Issue by luisrudge** [prisma/prisma#6727]
## How to reproduce

Create a schema with @unique and add two objects with non-unique values.

## Expected behavior

Throw an error

## Environment & setup

- OS: Mac OS
- Database: MongoDB (using Azure CosmosDB with Mongo API)
- Node.js version: 15.11.0
- Prisma version: 2.21.2

```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
Preview Features     : mongodb
```

### Schema & code

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

model User {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  email     String   @unique
}
```

```ts
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  await prisma.$connect();
  await prisma.user.create({
    data: {
      email: "test@example.com",
    },
  });
  await prisma.user.create({
    data: {
      email: "test@example.com",
    },
  });
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());

```

#### Result

```
➜  prismamongo npx ts-node index.ts
[
  {
    id: '6081b778001e4db9009f1569',
    createdAt: 2021-04-22T17:50:48.444Z,
    updatedAt: 2021-04-22T17:50:48.445Z,
    email: 'test@example.com'
  },
  {
    id: '6081b779001e4db9009f156a',
    createdAt: 2021-04-22T17:50:49.237Z,
    updatedAt: 2021-04-22T17:50:49.238Z,
    email: 'test@example.com'
  }
]
```

**Comment by matthewmueller** [comment]
Right now `@unique` isn't enforced by the database. In the future, we'd like for `prisma migrate` to be able to manage unique constraints.

You can workaround this limitation by adding unique indices outside of Prisma and then writing @unique by hand to enable certain API features like findUnique in the client.

**Comment by floelhoeffel** [comment]
Should be fixed by https://github.com/prisma/prisma/releases/tag/3.4.0

**Comment by hyperidx** [comment]
here we go again

**Comment by janpio** [comment]
Can you provide some more information @hyperidx? Is `@unique` not working for you?

**Comment by SLTN98** [comment]
It doesn't work for me either. Model is:
`model Account {
  id             String           @id @default(auto()) @map("_id") @db.ObjectId
  address        String           @unique
  user           User?
  AllowlistEntry AllowlistEntry[]
  createdAt      DateTime         @default(now())
  updatedAt      DateTime         @default(now())
}`

**Comment by janpio** [comment]
Did you run `npx prisma db push` to create the index on the database @SLTN98?

**Comment by SLTN98** [comment]
I created it with prisma.user.create{ account: { create: { address: "123" } } }

**Comment by amerikan** [comment]
@janpio would it be useful to add that info about not being enforced by Prisma here: https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-a-unique-field I too was under the impression it was not working.

**Comment by janpio** [comment]
What do you mean @amerikan? Unique indexes are enforce if they are pushed to the database.

**Comment by abhishekchalla-cmd** [comment]
> Did you run `npx prisma db push` to create the index on the database @SLTN98?

This worked

**Comment by MrSharpp** [comment]
so will it only enforce @unique constraint when pushing to db and not when creating a record?

**Comment by janpio** [comment]
No, you have to have pushed the unique constraints to the database (so it knows a field is supposed to be unique) before the database can enforce the uniqueness when creating a record. As long as you have not done that, MongoDB will let you write whatever you want to the database.

**Comment by leshax1** [comment]
So now it not possible to make a column unique with prisma migrate dev, only npx prisma db push should be used, even on production?

**Comment by janpio** [comment]
There is no support for Prisma mIgrate for MongoDB databases: https://www.prisma.io/docs/concepts/database-connectors/mongodb#no-support-for-prisma-migrate

**Comment by tariq-khan9** [comment]
> Did you run `npx prisma db push` to create the index on the database @SLTN98?

it worked for me as well.

**Comment by tariq-khan9** [comment]
run npx prisma db push. before running it,  make sure your mongodb doesn't have duplicate entries for unique fields.

**Comment by coderwala1** [comment]
it works: `npx prisma db push`

**Comment by anhtuanlee** [comment]
it work: shuold npx prisma db push first, after create

**Comment by lugonpedro** [comment]
Right now I'm facing the same issue, with prisma and client in v5.12.0, someone is having this kinda problem?

**Comment by Websites21** [comment]
Delete all collections and then run: npx prisma db push

**Comment by ecomerciostore** [comment]
with mongodb not working, `db pull` not supported.

**Comment by HyoAkira** [comment]
awww, im working with thousand of files to do prototype. Used faker to create sample data... just learned they have duplicated...

really
