### ISSUE TITLE
updateMany and deleteMany don't delete more than one record.

### ISSUE THREAD

**Issue by yassinebridi** [prisma/prisma#6732]
## Bug description

The `updateMany` and `deleteMany` operations don't pass the data arguments if you provide a `where` argument with two or more arguments.
Here is an example:
First case where it runs the operations successfully:
```ts
await this.prismaService.brand.updateMany({
  data: { isTrash: { set: false } },
  where: { AND: [{ id: { equals: 'some_id' } }] },
});
```
And you get this database query:
```sql
prisma:query BEGIN
prisma:query SELECT "public"."Brand"."id" FROM "public"."Brand" WHERE "public"."Brand"."id" = $1
prisma:query UPDATE "public"."Brand" SET "updatedAt" = $1, "isTrash" = $2 WHERE "public"."Brand"."id" IN ($3)
prisma:query COMMIT
```

But if you specify more than two `where` `AND` arguments:
```ts
await this.prismaService.brand.updateMany({
  data: { isTrash: { set: false } },
  where: {
    AND: [
      { id: { equals: 'some_id' } },
      { id: { equals: 'some_other_id' } },
    ],
  },
});
```
You get this resultant database query
```sql
prisma:query BEGIN
prisma:query SELECT "public"."Brand"."id" FROM "public"."Brand" WHERE ("public"."Brand"."id" = $1 AND "public"."Brand"."id" = $2)
prisma:query COMMIT
```

**Note**: The same issue is happening with the `deleteMany` operation
## How to reproduce
Run the above operations.

## Expected behavior

For the `updateMany` and `deleteMany` to remove many records by their ids

## Environment & setup

- OS: Linux arch
- Database: PostgreSQL
- Node.js v14.16.1
- Prisma version: 2.20.1

**Comment by janpio** [comment]
Isn't that expected? This first query will not return any results as there are no Brands with id `some_id` _AND_ `some_other_id` at the same time, so there is nothing to update. Are you looking for an `OR` there?

**Comment by yassinebridi** [comment]
You are right i misunderstood the AND argument, thanks.
