### ISSUE TITLE
Enum type support for MongoDB

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#6751]
## Problem

Enums are useful when you have a known number of possible inputs, like order statuses.

Our MongoDB driver doesn't currently support enums. This issue is to add them.

## Suggested solution

Mongo doesn't natively support enums, but we could easily enforce them in the Query Engine.

**Comment by janpio** [comment]
Concrete example with code sample was posted in https://github.com/prisma/prisma/issues/6731 - was closed as duplicate of this one here 👍

**Comment by willin** [comment]
Besides, raw query is useful.

**Comment by matthewmueller** [comment]
This one is working! I think it's secretly tucked away in 2.23.0, but if not, you can access it using prisma@dev or waiting until 2.24.0 (tomorrow).

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

model User {
  id        Int    @id @map("_id")
  firstName String
  lastName  String
  status    Status @default(Active)
}

enum Status {
  Active
  Inactive
}
```

```ts
  const user = await prisma.user.create({
    data: {
      id: 3,
      firstName: "Bob",
      lastName: "Alice",
      status: "Active",
    },
  })
  console.dir(user, { depth: Infinity })
```

```js
{
  id: 3,
  firstName: 'Bob',
  lastName: 'Alice',
  status: 'Active'
}
```
