### ISSUE TITLE
getting read ECONNRESET when executeRaw

### ISSUE THREAD

**Issue by volkankorkmaz** [prisma/prisma#6767]
## Bug description

We are using Prisma 2.20.1. 
Our DB (Postgre 13.1 R1) runs on Amazon AWS RDS. 

```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]:
Invalid prisma.queryRaw() invocation:

read ECONNRESET
at cb (..\node_modules@prisma\client\runtime\index.js:34862:17)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async resolve (..\src\query\abc.js:18:23) {
code: 'ECONNRESET',
clientVersion: '2.20.1',
meta: undefined
}
```

## How to reproduce

When we execute a function as below code, the Prisma gives the above error.

```
 const oos = await ctx.prisma
            .$queryRaw`SELECT * FROM func_get_dashboard(${userAuth.storeId})`;
```

## Expected behavior

The code should be work normally.

## Environment & setup

- OS: Windows 10
- Database:  Postgre 13.1 R1
- Node.js version: Latest
- Prisma version: 2.20.1

**Comment by volkankorkmaz** [comment]
What do you expect from me about this issue?

**Comment by volkankorkmaz** [comment]
Hi,

Do you have any idea about this issue? 

Thx

**Comment by janpio** [comment]
No, we will need to look into reproducing this ourselves. We will let you know when we got to this.

Is `func_get_dashboard` a general PostgreSQL function or something custom from you?
Can you share this function so we can reproduce?

**Comment by volkankorkmaz** [comment]
I created that function. It is very basic.

Select col1, col2, col3 from table1

**Comment by janpio** [comment]
Can you share the complete code? Only then it will be possible for us to really recreate your experience - otherwise we might fail because of getting it slightly wrong.

**Comment by volkankorkmaz** [comment]
I'll share it asap. Thx for your quick response..

**Comment by volkankorkmaz** [comment]
I found the cause of the issue. I have been closed the authentication accidentally.

Thx for your help.

Have a good day.
