### ISSUE TITLE
Query-Engine-Windows not compatible in Windows 7,32 bit.

### ISSUE THREAD

**Issue by elitexp** [prisma/prisma#6771]
Query-Engine-Windows is not executable in windows 7, 32 bit.

**Comment by pantharshit00** [comment]
Microsoft has already ended support for Windows 7: https://www.microsoft.com/en-in/microsoft-365/windows/end-of-windows-7-support

I dont't know we will be supporting that now. 

Can you please the error here which you are getting anyways here?

**Comment by pantharshit00** [comment]
Ah, 32 bit. Just noticed! 

We only ship 64bit binaries. If you want to get 32 bit binaries, you need to compile Prisma yourself. 

Here is the engine source with build instructions in the README: https://github.com/prisma/prisma-engines

Here is how you can use the custom binaries: https://www.prisma.io/docs/concepts/components/prisma-engines#using-custom-engine-binaries
