### ISSUE TITLE
Generate log file with Drift detected info for troubleshooting purpose

### ISSUE THREAD

**Issue by simonppg** [prisma/prisma#6776]
## Problem
It's not clear whats the problems when a drift is detected.

## Suggested solution
generate a /prisma/logs/drift_errors/log.txt file with a report with all the difference between the actual tabase and the shadow database

## Additional context
I have a database in postgres that I've been using with knex, I want to migrate to prisma but keeping my actual schema and data, I used `prisma introspect` to generate the prisma schema, everything works find until I want to generate the first migration with keeping the data, I used `prisma migrate dev --name introspected_change --create-only` I got a message like this:

```
❯ npx prisma migrate dev --name introspected_change --create-only
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "mydatabase", schema "public" at "localhost:5432"

? Drift detected: Your database schema is not in sync with your migration history.

We need to reset the PostgreSQL database "mydatabase" at "localhost:5432".
Do you want to continue? All data will be lost. › (y/N)
```
answering no, just does nothing, I keep my data but can't go ahead with the migrattion from knex to prisma. On the other side answering yes, deletes extensions, funcitons and all data, try to recreate the data but fails becase it didn't add the extension need for uuid   `uuid            String    @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid`. If I edit the migration with `CREATE EXTENSION "uuid-ossp";` at the begining of the file, the migration can be appliend but istill I lost the data and functions, I don't care about the functions since I'm planing to stop using them any way, but I can't lost the data and I don't know how many difference there are in the schema.

if I was able to know, I could continue using knex migrations to change the schema to the point prisma can countine (like delete all the stored functions) but since I don't know what the real problem is, I'm unable to fix it.

for confidential reasons I can't share the db schema but I hope I add enogh information, I case something else is needed I could add more, please let me know.

**Comment by tomhoule** [comment]
https://github.com/prisma/prisma-engines/pull/2002 means that the next release (and dev releases very soon) will have human-readable drift summaries. They will probably be a bit rough at the beginning, but we will improve them over time.
