### ISSUE TITLE
Can't deploy to fly.io: postinstall.js EOF error

### ISSUE THREAD

**Issue by ryanflorence** [prisma/prisma#6779]
## Bug description

Deploying to [fly.io](fly.io) fails with the following error (this is the fly.io output):

```
[Parsing package.json]
[INFO] Parsing package.json
[INFO] No file to start server
[INFO] Using npm v6.14.12 from Node
[INFO] Installing node modules from ./package-lock.json

> @prisma/client@2.21.2 postinstall /workspace/node_modules/@prisma/client
> node scripts/postinstall.js

Prisma schema loaded from prisma/schema.prisma
Error executing lifecycle: unexpected EOF
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

Would be nice to know which file has the EOF issue but no logs indicate it.

## How to reproduce

Here's a repo: https://github.com/ryanflorence/fly-prisma

1. Set up a simple prisma "getting started" app (https://www.prisma.io/docs/getting-started/quickstart-typescript)
2. Follow the fly.io deploy instructions:
    ```sh
    flyctl launch
    flyctl deploy
    ```
3. You'll get the error.

## Prisma information

My prisma stuff runs fine locally, just followed the getting started guide.

## Environment & setup

- OS: I assume fly.io is some *nix variety, uses heroku build pack
- Database: tried both postgres and sqlite, but you really don't even get that far
- Node.js version: 14.16.1
- Prisma version: 2.21.2

(cc @mrkurt from fly.io)

**Comment by janpio** [comment]
I can reproduce this when running `flyctl launch` already. We will look into this, trying to figure out what is going wrong here.

**Comment by ryanflorence** [comment]
Note that @mrkurt thinks this is a problem on fly's end. I'm thinking if we just knew which file is throwing the EOF everybody will go "oh! we need to [do something relatively simple]."

https://github.com/superfly/flyctl/issues/405#issuecomment-826818864

**Comment by janpio** [comment]
Ok, subscribing to that issue and will ask some related questions there.

**Comment by jeromegn** [comment]
I think this might need re-opening, but the issue appears to be related specifically to building prisma with the `heroku/buildpacks:20`.

Specifically, it gets stuck on this step:

```
Prisma schema loaded from prisma/schema.prisma
2021-04-26T14:02:14.823Z prisma:download copying /home/heroku/.cache/prisma/master/e421996c87d5f3c8f7eeadd502d4ad402c89464d/debian-openssl-1.1.x/query-engine to /workspace/node_modules/prisma/query-engine-debian-openssl-1.1.x
```

at which point the node process is stuck in `epoll_wait`.

To reproduce this, with Docker, [install the `pack` CLI](https://buildpacks.io/docs/tools/pack/) and run:

```
# while in the fly-prisma directory
pack build prismatest --builder heroku/buildpacks:20 -e DEBUG="*"
```

Building with a Dockerfile appears to work as intended.

**Comment by pantharshit00** [comment]
Hey, I wasn't able to reproduce this with the steps mentioned.

![image](https://user-images.githubusercontent.com/22195362/117345578-55214980-aec4-11eb-92d3-11bb666f296c.png)

I used windows for this reproduction but I guess that should not matter. Maybe can you try this again. 

My docker version:
```
Docker version 20.10.5, build 55c4c88
```
Pack version: `0.18.1+git-b5c1a96.build-2373`

**Comment by jeromegn** [comment]
Mine fails consistently on Linux.

Docker version is `20.10.6`, pack version `0.18.1+git-b5c1a96.build-2373`.

Seems to be working for some of my colleagues. This is a weird issue.

**Comment by jeromegn** [comment]
I have 3 linux computers, 2 of them are working fine, but 1 is showing the issue. They have various linux kernel versions, upgrading the kernel on the failing computer didn't help (it's now on 5.10 LTS).

It fails on my M1 Mac (sometimes with a segfault, but that's probably a problem with Docker for Mac).

It also fails on some of our Fly.io image builders.

It's a very odd failure. I couldn't find anything that the failing environments had in common. They have various kernel versions, various disk types and sizes, they're running on various OSes, etc.

**Comment by janpio** [comment]
We have something similar, where installation in Docker just "hangs": https://github.com/prisma/prisma/issues/5304 Maybe this is related somehow. It is also the same step, so my tingle senses go on here. But no `Error executing lifecycle: unexpected EOF` there.

**Comment by janpio** [comment]
Oh look at this: https://winter-meadow-5740.fly.dev/prisma 
Prisma running on a fly.io deployment <3 
Thanks so much for the collaboration on this @jeromegn. We will add an e2e test for this soon: https://github.com/prisma/e2e-tests/issues/1656

@ryanflorence If you want, you can try your initial project again - that should work now as well.
