### ISSUE TITLE
Block generating the package json dependencies

### ISSUE THREAD

**Issue by ajotaos** [prisma/prisma#6783]
## Problem

I'm using a monorepo with a root package that handles all development dependencies (like `prisma`) and the nested folders that contain the packages. The package has a prisma schema with a custom output.

When I'm running the `prisma generate` on my package, it generates on the package's `package.json` two dependencies: `prisma` and `@prisma/client`. The thing is that I don't save my dev dependencies at this level and in theory, I wouldn't need `@prisma/client` because of the custom output but is till getting created.

## Suggested solution

A way to block or flag the edit of the `package.json` and `package-lock.json` when running `prisma generate`

## Additional context

OS: macOS 11.2.3
Node: 15
Prisma: 2.21.2

**Comment by williamluke4** [comment]
Hey @ajotaos, [this](https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_generate_skip_autoinstall) should solve your problems

**Comment by ajotaos** [comment]
Thank you very much captain 👨‍✈️ That's great 😁

**Comment by janpio** [comment]
Something to be documented?
