### ISSUE TITLE
MongoDB: Support introspection

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#6787]
## Problem

Without introspection, we ask applications developers to write their schema by hand. 

There are two problems with this:

1. It's error-prone especially if you have a large schema
2. It's impossible if your data types are not consistent (e.g. payment is sometimes a number, sometimes a string).

## Suggested solution

- For the first problem, we could try and sample the data and generate a schema from the sample.
- The second problem is much harder, but it could involve detecting and prompting the developer to cleanup data that has inconsistent types.

## Alternatives

- We make our schema more flexible to handle type unions. Perhaps just for Mongo, but maybe for SQL too.

## Open Questions

- Are there good reasons why an application's data types are inconsistent? Is it feasible to fix these data inconsistencies?

**Comment by RyKilleen** [comment]
Just wanted to note that this would be an absolute killer feature, that's probably the major barrier of entry for getting Prisma into a few projects I wish it was a part of. (I'm also sure it's a massive undertaking.)
