### ISSUE TITLE
Missing inheritance functionality

### ISSUE THREAD

**Issue by yardenshoham** [prisma/prisma#6808]
## Bug description
When running `prisma db pull` (`prisma introspection`) on a PostgreSQL database that has tables created with the `INHERITS` keyword the schema is bad and a warning message is printed:

![image](https://user-images.githubusercontent.com/20454870/116153661-59917980-a6f0-11eb-9153-597865a27999.png)

## How to reproduce

1. Create a table using `INHERITS`
2. Run `prisma db pull`
3. See warning

I also created a repo: https://github.com/yardenshoham/prisma-inheritence-issue

## Expected behavior
I'd expect prisma to support inheritance in PostgreSQL seeing as the website says it does
![image](https://user-images.githubusercontent.com/20454870/116154135-f522ea00-a6f0-11eb-845c-aec064690045.png)

## Prisma information

SQL script:
```sql
-- https://www.postgresql.org/docs/current/tutorial-inheritance.html
CREATE TABLE cities (
  name       text,
  population real,
  elevation  int     -- (in ft)
);

CREATE TABLE capitals (
  state      char(2) UNIQUE NOT NULL
) INHERITS (cities);
```

The schema that gets generated:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model capitals {
  name       String?
  population Float?  @db.Real
  elevation  Int?
  state      String  @unique @db.Char(2)
}

/// The underlying table does not contain a valid unique identifier and can therefore currently not be handled by the Prisma Client.
model cities {
  name       String?
  population Float?  @db.Real
  elevation  Int?

  @@ignore
}
```

## Environment & setup

- OS: Ubuntu 20.04 on WSL2
- Database: PostgreSQL 13
- Node.js version: v12.20.2
- Prisma version:

```
prisma               : 2.21.2
@prisma/client       : Not found
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

**Comment by tomhoule** [comment]
Since this is a documentation issue, let's track progress in https://github.com/prisma/docs/issues/1783
