### ISSUE TITLE
queryRaw cannot handle some numbers

### ISSUE THREAD

**Issue by CGamesPlay** [prisma/prisma#6818]
## Bug description

Prisma cannot properly send numbers to the database using the raw query API. Note that in the simple test case below, Prisma has corrupted the float value and converted the integer to a string.

## How to reproduce

```javascript
  const results = await prisma.$queryRaw`SELECT ${1}::float8 AS "fOne", ${0.1}::float8 AS "fPointOne", ${1} as "iOne", ${"1"} as "sOne"`;
  console.log("Results from Prisma", results);
```

## Expected behavior

```
Results from Prisma [ { fOne: 1, fPointOne: 0.1, iOne: 1, sOne: '1' } ]
```

## Actual behavior

```
Results from Prisma [ { fOne: 5e-324, fPointOne: 0.1, iOne: '1', sOne: '1' } ]
```

## Environment & setup

- OS: MacOS (Prisma), Docker (Postgres)
- Database: Postgres
- Node.js version: v15.6.0
- Prisma version:
- 
```prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

## Workaround

I was able to find a workaround by manually converting the value to a string, then double-converting it in the query:

```javascript
  const results = await prisma.$queryRaw`SELECT cast(${"1"}::text as double precision) AS "fOne"`;
  console.log("Results from Prisma", results);
```

```
Results from Prisma [ { fOne: 1 } ]
```

**Comment by pantharshit00** [comment]
This is reproducible in `2.23.0-dev.28`

**Comment by jhnns** [comment]
This happens also when querying columns with specific numeric types.

In my case, the underlying column has `numeric(5, 4)`. An example value would be `0.5377`.
Using `$queryRaw` I get `0.5377000000000001`.

**Comment by Weakky** [comment]
Hey,

This issue was fixed by https://github.com/prisma/prisma-engines/pull/2847. It will be available in the next release under the `improvedQueryRaw` feature flag.

Beware that enabling `improvedQueryRaw` is a breaking change. Release notes will contain information as to how to upgrade (so will the documentation).

Thanks for reporting 🙏
