### ISSUE TITLE
Ordering By Relation count incorrectly orders 0 count

### ISSUE THREAD

**Issue by temuujin-nat** [prisma/prisma#6824]
## Bug description

When I try to sort Users by count of their Posts, Users with 0 Posts are ordered as if it is +infinity posts. In other words, when I order ascending, it is **correctly** in an ascending order just except the Users with 0 posts are at the end. Vice versa is true in descending order. 

## How to reproduce

This issue can be reproduced with the most basic Prisma example and small dummy data, but I also have tried this with many users and many posts, and the problem is still there.
1. Create a simple prisma schema with just one 1-n relationship (e.g. User and Post) and enable preview feature `orderByRelation`
2. Make 2 dummy User, and 1 Post attributed to one user in prisma Studio
3. Get all the users in **ascending** order of Posts using query below in Prisma Information

The result (_count enabled to demonstrate wrongness):
```
[
  { id: 1, _count: { posts: 1 } },
  { id: 2, _count: { posts: 0 } }
]
```
## Expected behavior

It should treat 0 as a value less than 1 but right now it is infinity. The result should look like: 
```
[
  { id: 2, _count: { posts: 0 } },
  { id: 1, _count: { posts: 1 } }
]
```
## Prisma information

Prisma Schema (appropriate preview features enabled in client): 
```
model User {
  id        Int    @id @default(autoincrement())
  posts  Post[]        
}

model Post {
  id        Int   @id @default(autoincrement())
  user    User  @relation(fields: [userID], references: [id])
  userID  Int        
}
```
Prisma Client Query:
```
const users = await prisma.user.findMany({
    orderBy: {
      posts: {
        count: 'asc',
      },
    },
};
console.log(users);
```

## Environment & setup

- OS: Ubuntu 20.04 LTS
- Database: PostgreSQL
- Node.js version: 14.16.1
- Prisma version:  2.21.2

```
2.21.2
```

**Comment by pantharshit00** [comment]
I can confirm this bug, we should patch this.
