### ISSUE TITLE
Re-introspection overwrites manually added @relation columns

### ISSUE THREAD

**Issue by pjadavies** [prisma/prisma#6827]
## Bug description

When I re-run `prisma introspect` my manually added `@relation` fields disappear from `schema.prisma`. I understood from the documentation at https://www.prisma.io/docs/concepts/components/introspection#introspection-with-an-existing-schema that they should be maintained.

I'm assuming I'm adding the relationships incorrectly (though they worked, which was exciting!) so please forgive any naiveté... 

## How to reproduce

1. Introspect existing database for the first time with `npx prisma introspect`
2. Add 1-1 relation fields eg the `owner` field below which references my user table
```
model Stream {
  ...
  owner_id            String    @db.VarChar(32)
  owner               User      @relation(fields: [owner_id], references: [id])
  ...
}
```

I subsequently ran `npx prisma format` to add corresponding relation field in the User table:

```
model User {
  ...
  Stream                    Stream[]
  ...
}
```

3. Make changes to underlying postgres schema (eg add new table or new column)
4. Re-introspect `npx prisma introspect` and the owner field added above has been removed. Introspection is successful, models have warning:
```
✔ Introspected 17 models and wrote them into prisma/schema.prisma in 1.96s

*** WARNING ***

These models were enriched with `@@map` information taken from the previous Prisma schema.
- Model "AbcIds"
...
```
... but no comment about the missing `@relation` fields

## Expected behavior

The manually added relationship fields should be preserved and merged with the new introspection.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 15.11.0
- Prisma version: 

```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

**Comment by janpio** [comment]
> I understood from the documentation at [prisma.io/docs/concepts/components/introspection#introspection-with-an-existing-schema](https://www.prisma.io/docs/concepts/components/introspection#introspection-with-an-existing-schema) that they should be maintained.

That is unfortunately a misunderstanding:

> Introspection maintains the following manual changes:
> - ...
> - Custom `@relation` names

Easy one to make though: This applies only to the `name` attribute of `@relation`, not complete relations. That is variable and can be changed by the user. The existence of a relation depends on the database schema instead.

Do you know why your existing relations are not picked up by Prisma Introspection in the first place? Do you now have foreign keys in place maybe? Then the better solution would probably be to add these - and then Prisma should pick those up properly in the beginning already.

**Comment by pjadavies** [comment]
Ah well that explains it :) Thanks for the explanation.

As you suspected, I hadn't declared the foreign keys when I first set up the schema in Postgres, and for some reason assumed that doing so in Prisma would be enough. I will go back and do them in the db so they can persist.

Perhaps it could be clearer in the section on relations that these should ideally be set in the database? Thanks so much.

**Comment by pantharshit00** [comment]
Opened: https://github.com/prisma/docs/issues/1702

I am going to close this one in favour of the docs issue.
