### ISSUE TITLE
Trying to introspect a .sqlite generated from a .xlsx with `id` as first column

### ISSUE THREAD

**Issue by wocdamjack** [prisma/prisma#6834]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`introspect`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.16.1           | 
| Prisma CLI  | 2.21.2             | 
| Binary      | e421996c87d5f3c8f7eeadd502d4ad402c89464d| 

## Error
```
Error: [libs/datamodel/core/src/transform/ast_to_dml/lift.rs:387:73] called `Option::unwrap()` on a `None` value
```

**Comment by wocdamjack** [comment]
I needed to fiddle with the sqlitebrowser and make the id a PK !  thanks

**Comment by janpio** [comment]
Uh, that crash is still unexpected though. Can you maybe share the Sqlite database in its original, broken state? We would be very interested in reproducing and fixing that crash.

**Comment by pantharshit00** [comment]
ping @wocdamjack

**Comment by janpio** [comment]
ping @wocdamjack again - without a reproduction we can not improve this error message unfortunately and will have to close this issue without any change 😢
