### ISSUE TITLE
Expose native types mapping to DMMF

### ISSUE THREAD

**Issue by unlight** [prisma/prisma#6844]
## Problem

We have model with defined native type 
```
model Post {
  id         Int    @id
  title      String @db.VarChar(200)
}
```
Custom generators may want to use this additional information:
- varchar
- 200 (limit)

But this information is missing, checked `node_modules/.prisma/client/index.js` @ `dmmfString`

## Suggested solution

Expose db field attributes data/info to DMMF.

**Comment by janpio** [comment]
I am closing this as we now have an issue at https://github.com/prisma/prisma/issues/10252 with active discussion about this. Thanks for creating it.
