### ISSUE TITLE
_count not working with typescript

### ISSUE THREAD

**Issue by euberdeveloper** [prisma/prisma#6856]
## Bug description

The new introduced `_count` property does not work with the generated Typescript

## How to reproduce

This is a portion of the schema:

```prisma
model Contratto {
    id Int @id @default(autoincrement()) @map("id")

    dataInizio DateTime @map("data_inizio")
    dataFine   DateTime @map("data_fine")

    dataFirmaContratto     DateTime? @map("data_firma_contratto")
    dataChiusuraAnticipata DateTime? @map("data_chiusura_anticipata")

    checkout Float?   @map("checkout")
    cauzione Float?   @map("cauzione")
    tipoRata TipoRata @map("tipo_rata")

    idTariffa Int     @map("id_tariffa")
    tariffa   Tariffa @relation(fields: [idTariffa], references: [id])

    idTipoContratto Int           @map("id_tipo_contratto")
    tipoContratto   TipoContratto @relation(fields: [idTipoContratto], references: [id])

    idQuietanziante Int           @map("id_quietanziante")
    quietanziante   Quietanziante @relation(fields: [idQuietanziante], references: [id])

    note String? @map("note")

    contrattiSuOspite ContrattoSuOspite[]

    bollette Bolletta[]
    @@map("contratto")
}
```

This is what I have if I want to get the number of "bollette" of a contract:

![image](https://user-images.githubusercontent.com/33126163/116616952-91d9c780-a93d-11eb-8a6f-87b640c96419.png)

## Expected behavior

I would expect to be able to use it, if _count is actually what I think it is.

## Environment & setup

- OS:Ubuntu 20
- Database: Postgres
- Node.js version: 15
- Prisma version: 2.21.2

```

```

**Comment by chl03ks** [comment]
I have the same issue.

**Comment by chl03ks** [comment]
i've found the solution for the bug, just delete the Prisma client folder on your node_modules and install the latest version of the Prisma client and Prisma and run generate again

**Comment by gmanno** [comment]
Having the same issue too. Just installed 2.22.1.

**Comment by pantharshit00** [comment]
I am unable to reproduce this.

![image](https://user-images.githubusercontent.com/22195362/118276485-574b5f80-b4e5-11eb-9c09-1cf5460b8fa6.png)


Can you please make sure you enabled the `selectRelationCount` preview feature flag like so in the schema:
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["selectRelationCount"]
}
```

After adding this you need to regenerate the client using `prisma generate`.

**Comment by euberdeveloper** [comment]
I did not add selectRelationCount, thanks

**Comment by janpio** [comment]
@gmanno, what about you?

**Comment by gmanno** [comment]
Works for me too. Thanks for the support.

**Comment by achraf-boussaada** [comment]
This doesn't work for prisma 2.23.0. I added the preview feature mentioned and rerun prisma generate but `_count` still not recognizable.

**Comment by BrunoS3D** [comment]
The problem still exists here. I have already changed the prism version to previous versions, and in all of them I ran the command `npx prisma generate`

package.json
```json
// ...
"dependencies": {
    "@prisma/client": "^2.29.1",
},
"devDependencies": {
    "prisma": "^2.29.1",
}
```

prisma/schema.prisma
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["selectRelationCount"]
}

// ...
```

![image](https://user-images.githubusercontent.com/21183964/130382686-1e07921b-67a5-4f15-b8fc-cd3d8a451812.png)

**Comment by pantharshit00** [comment]
@BrunoS3D Open a new issue with the full query.
