### ISSUE TITLE
NAPI: ` thread '<unnamed>' panicked at 'Application logic invariant error: received null value for field author which may not be null', query-engine/core/src/response_ir/internal.rs:395:26`

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#6867]
A strange, uncatched? error found in logs for napi Preview feature

https://github.com/prisma/prisma/pull/6864/checks?check_run_id=2475650183#step:7:688

```
 thread '<unnamed>' panicked at 'Application logic invariant error: received null value for field author which may not be null', query-engine/core/src/response_ir/internal.rs:395:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

@williamluke4 knows more about this.

**Comment by pimeys** [comment]
This might be that we just log the panic from a tokio thread. We still catch it and I see no tests failing. Is this a problem?

**Comment by Jolg42** [comment]
So it doesn't cause any problem I know of but it was unexpected for me to see it.

@williamluke4 what do you think?

**Comment by pimeys** [comment]
It's very probably also happening in the separate binary, but the log gets sucked somewhere.

**Comment by pantharshit00** [comment]
@Jolg42 Can we extract this reproduction out of CI easily?

**Comment by Jolg42** [comment]
That's a question for @williamluke4 I don't know from which test it's from 👀

**Comment by Jolg42** [comment]
Closing, I don't see it anymore, if someone sees it we can reopen
