### ISSUE TITLE
Optimistic Concurrency Control pattern from documentation sometimes lets conflicting writes go through?

### ISSUE THREAD

**Issue by calebmer** [prisma/prisma#6904]
## Bug description

Context: I’m building a one-time-password login scheme that generates a 6 digit password and emails it to the user. To prevent brute force attacks, I’m locking an account for 24 hours after 5 failed attempts. So it’s really important that attackers don’t get more attempts to crack a password if they send a lot of requests concurrently.

I’m using the Optimistic Concurrency Control pattern shared [in the documentation](https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide#optimistic-concurrency-control). But seeing that when I write a simple test that makes a bunch of attempts to login concurrently, some conflicting updates are allowed through.

## How to reproduce

Repo with code to reproduce the problem: https://github.com/calebmer/prisma-optimistic-concurrency-control-pattern-conflict-repro

Run `node repro.js` a couple times. I have an assert with the expected output and it fails for me maybe 2 out of 3 times.

I tried to make a minimal reproducing case, but didn’t remove my domain model. (So the repro is still in the context of one-time-password login.)

## Expected behavior

The repro code attempts to login 16 times with incorrect passwords. We should only expose to an attacker that the password was incorrect 5 times and then tell the attacker the account is locked 11 times. (An assert encodes this expectation.)

I don’t have the code for a “successful” login, but it also uses the Optimistic Concurrency Control pattern and is subject to the same conflicting write issue (which I’ve observed in local tests), effectively giving attackers more attempts to crack the password.

## Prisma information

(Prisma schema, version, and queries included in the repro.)

## Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v15.0.1
- Prisma version:

```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

**Comment by matthewmueller** [comment]
Thanks for the awesome repro @calebmer! I've reproduced it and will investigate.

**Comment by matthewmueller** [comment]
Quick thought without thinking too much about the race condition yet:

```diff
const updateAccountResult = await prisma.account.updateMany({
  where: {
    id: account.id,
    // Include `failedOneTimePasswordLoginAttempts` in our `where` clause
    // because if it changed concurrently then the account may actually
    // be locked so we’ll want to skip the update.
    failedOneTimePasswordLoginAttempts:
      account.failedOneTimePasswordLoginAttempts,
  },
  data: {
    // Safe to not use the atomic `increment` operator because we won’t
    // update `failedOneTimePasswordLoginAttempts` if it has changed
    // concurrently (see `where` clause).
+    failedOneTimePasswordLoginAttempts: account.failedOneTimePasswordLoginAttempts + 1,
-    failedOneTimePasswordLoginAttempts: {
      increment: 1,
    },
  },
});
``` 

This passes your expectation and is what we recommend in the guide: https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide#optimistic-concurrency-control

Your comment is making me question it a bit though. I think the problem with `account.failedOneTimePasswordLoginAttempts +1` is that it's using the old `account.failedOneTimePasswordLoginAttempts` whereas uses the current `failedOneTimePasswordLoginAttempts` in the DB.

**Comment by calebmer** [comment]
Updated my local example to `{increment: 1}` and ran the program 10 times. It failed 4/10 times. Do you see similar pass/fail rates? (Although that is better than the current version which fails 9/10 times.)

Regardless of whether `{increment: 1}` works, let’s say the value was a string I wanted to append to, an array I wanted to push to, or any other type which doesn’t have atomic operators (yet?). I’d expect this pattern to work for safe concurrent updates.

**Comment by calebmer** [comment]
For more details on my actual code, the “successfully verified password branch” looks something like this:

```ts
const updateAccountResult = await prisma.account.updateMany({
  where: {
    id: account.id,
    // Include `failedOneTimePasswordLoginAttempts` in our `where` clause
    // because if it changed concurrently then the account may actually
    // be locked so we’ll want to skip the update.
    failedOneTimePasswordLoginAttempts:
      account.failedOneTimePasswordLoginAttempts,
  },
  data: {
    // Unset the one time password after it has been successfully used to
    // guarantee it won’t be used again.
    oneTimePasswordLoginHash: null,
    // Reset failed login attempt fields after successful login.
    failedOneTimePasswordLoginAttempts: 0,
  },
});
```

So it uses the same OOC “check” in the where clause but doesn’t need to “atomically” update any values. I’ve also observed this branch incorrectly fire when testing locally. (Naturally this is the dangerous branch to incorrectly fire since it logs the attacker in.)

**Comment by calebmer** [comment]
(Side question: When debugging this I wanted to see the PostgreSQL queries being executed since I’m comfortable working directly with PostgreSQL. I tried the `DEBUG` env variable but that showed intermediate GraphQL-style queries. Is there a way to see the SQL being executed besides turning on transaction logging at the database level?)

**Comment by matthewmueller** [comment]
PR: https://github.com/calebmer/prisma-optimistic-concurrency-control-pattern-conflict-repro/pull/1

**Comment by calebmer** [comment]
(Will respond here instead of the PR.)

So this depends on observing `failedOneTimePasswordLoginAttempts` after the update. Which works fine for incorrect passwords, but not for my correct password code. Reminder on what the code looks like (with your proposed modification):

```ts
if (account.failedOneTimePasswordLoginAttempts >= 5) {
  throw new Error('Account locked');
}

if (!isCorrectOneTimePassword) {
  const updatedAccount = await prisma.account.update({
    where: {id: account.id},
    data: {
      failedOneTimePasswordLoginAttempts: {increment: 1},
    },
  });

  // Retroactively reject if `updatedAccount` has more than 5 failed attempts.
  if (account.failedOneTimePasswordLoginAttempts > 5) {
    throw new Error('Account locked');
  }
} else {
  const updatedAccount = await prisma.account.update({
    where: {id: account.id},
    data: {
      oneTimePasswordLoginHash: null,
      failedOneTimePasswordLoginAttempts: 0,
    },
  });

  // We reset to 0. We don’t know if `updatedAccount` had more than 5 failed attempts and can’t retroactively reject.
  // How do we reject if the account had more than 5 failed attempts at the time of update?
}
```

So let’s say an attacker makes 100 requests at the same time where one has the correct password. If we captured a stale `account` then we’ll execute the correct password branch and ignore the fact the attacker has more than 5 failed login attempts which is bad.

**Comment by calebmer** [comment]
I understand how to use the atomic operators if all I care about is simple addition/subtraction/multiplication/deletion.

When I have a more complex need for an atomic update like adding to a string/array atomically or resetting a counter atomically respecting the last value (like in this case) the documentation recommends Optimistic Concurrency Control which I think is a good pattern.

What I discovered when trying to apply the OOC pattern is it doesn’t always work. I’d expect my repro to work as written after reading the docs (even though there exists an atomic operator specifically for the pattern in my repro and using OOC instead of that operator is silly). Is that not the right expectation?

**Comment by matthewmueller** [comment]
> So let’s say an attacker makes 100 requests at the same time where one has the correct password. If we captured a stale account then we’ll execute the correct password branch and ignore the fact the attacker has more than 5 failed login attempts which is bad.

Yep good point! There would need a way to drop it back to 0 after you do get locked out.

> What I discovered when trying to apply the OOC pattern is it doesn’t always work. I’d expect my repro to work as written after reading the docs (even though there exists an atomic operator specifically for the pattern in my repro and using OOC instead of that operator is a bit silly). Is that not the right expectation?

OCC builds off of simple atomic primitives like increment/decrement. You should be able to do the more complex use cases by building off the primitives. One issue I see here is that we've coupled the password attempts with a row version. The version should only ever go up. I can definitely update the documentation if that's unclear.

To solve the issue above, I'd suggest splitting password attempts from version number. Version number goes up and when you need to modify the account model, you should also be checking and atomically incrementing this version number.

**Comment by matthewmueller** [comment]
> So let’s say an attacker makes 100 requests at the same time where one has the correct password. If we captured a stale account then we’ll execute the correct password branch and ignore the fact the attacker has more than 5 failed login attempts which is bad.

Could you clarify this? I think you're talking about the first line `account.failedOneTimePasswordLoginAttempts >= 5`. This can be stale and that's okay. The check after update is the real check.

But that's a good point about resetting it to 0. There's currently no way to drop it back to 0 after you do get locked out.

> What I discovered when trying to apply the OOC pattern is it doesn’t always work. I’d expect my repro to work as written after reading the docs (even though there exists an atomic operator specifically for the pattern in my repro and using OOC instead of that operator is a bit silly). Is that not the right expectation?

OCC builds off simple atomic primitives like increment/decrement. You should be able to do the more complex use cases by building off the primitives. One issue I see here is that we've coupled the password attempts with a row version. The version should only ever go up. I can update our documentation if that's unclear.

To solve the dropping back to 0, I'd suggest splitting password attempts from version number. When you need to modify the account model, you should also be checking and atomically incrementing this version number.

**Comment by matthewmueller** [comment]
Closing. Happy to re-open if needed though.
