### ISSUE TITLE
npx prisma generate does not generate type definitions for include

### ISSUE THREAD

**Issue by GGAlanSmithee** [prisma/prisma#6919]
## Bug description

`npx prisma generate` does not generate type definitions for `include`

## How to reproduce

1. create a new folder
2. run `npm init -y`
3. run `npm i prisma @prisma/client`
4. run `npx prisma init`
5. in file `schema.prisma`, add a model:
    * ![image](https://user-images.githubusercontent.com/11805103/116964104-f3d25e00-acaa-11eb-8e8c-cd7cc3a74f5c.png)
6. run `npx prisma generate`
7. inspect file `node_modules/.prisma/client/index.d.ts`, for example, the `TestFindManyArgs`
    * ![image](https://user-images.githubusercontent.com/11805103/116964264-63484d80-acab-11eb-8f62-7ed5a4abd2bc.png)

## Expected behavior

There should be a `include` property generated, but there is not.

Looking at an older project, using the same setup, it seems to be generated properly. No obvious differences that I can see

![image](https://user-images.githubusercontent.com/11805103/116964396-b7533200-acab-11eb-94e6-a169972c7736.png)

### package-lock.json

![image](https://user-images.githubusercontent.com/11805103/116964453-d782f100-acab-11eb-995e-f0befc4f3943.png)

### schema.prisma

![image](https://user-images.githubusercontent.com/11805103/116964588-347ea700-acac-11eb-9021-eb71c9d0b5af.png)

## Environment & setup

* os
    * ![image](https://user-images.githubusercontent.com/11805103/116964780-9f2fe280-acac-11eb-9624-1fc5e8274332.png)
* db
    * postgres
* node
    * ![image](https://user-images.githubusercontent.com/11805103/116964641-57a95680-acac-11eb-803b-07f80c9fe68e.png)
* prisma
    * ![image](https://user-images.githubusercontent.com/11805103/116964694-71e33480-acac-11eb-8ee8-e865dc4dd3e0.png)

**Comment by GGAlanSmithee** [comment]
nvm I'm stupid :)

**Comment by GGAlanSmithee** [comment]
for future googlers I had simply missed to declare the navifation properties, which makes `prisma` (I would guess correctly) omit the `include` property from the query builder typings.

correct setup;

![image](https://user-images.githubusercontent.com/11805103/116971521-f8ead980-acb9-11eb-9177-28a306eca5ae.png)

which generates:

![image](https://user-images.githubusercontent.com/11805103/116971558-0acc7c80-acba-11eb-85f8-e60cca4d124e.png)

**Comment by pantharshit00** [comment]
I am glad you were able to sort it out! Self closing issues are always the best 🎉
