### ISSUE TITLE
`db push` / `migrate` is hiding the binary download process during `generate`, leading to confusion

### ISSUE THREAD

**Issue by carlitorweb** [prisma/prisma#6926]
## Bug description

When you enable _Napi_ and try `npx prisma db push --preview-feature` the process stuck running the generators.

## How to reproduce

1. Enable Napi by adding `previewFeatures = ["napi"]` to your schema.prisma
2. Run `npx prisma db push --preview-feature`
3. The process then stuck at: `Running generate... (Use --skip-generate to skip the generators)`

## Expected behavior

Generators finish successful

## Prisma information

```js
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["napi"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Posts {
  id        Int      @id @default(autoincrement())
  title     String
  content   String   @db.VarChar(500)
  creator   User     @relation(fields: [authorId], references: [id])
  authorId  Int
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model User {
  id       Int     @id @default(autoincrement())
  posts    Posts[]
  name     String
  email    String  @unique
  password String
  status   String  @default("I am new!")
}
```

## Environment & setup

- OS: LTS Ubuntu
- Database: MySQL - MariaDB (Docker image: `linuxserver/mariadb:latest`)
- Node.js version: LTS (but also tested with v16 with same result)
- Prisma version: 2.21.2
```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
Preview Features     : napi
```

**Comment by janpio** [comment]
Can you run `npx prisma generate` on its own successfully with `napi` enabled?
(What you had posted in https://github.com/prisma/prisma/issues/6926 before indicated the Migrations were fine, but the Client generation afterwards failed)

**Comment by carlitorweb** [comment]
@janpio after run `npx prisma generate` is start to **Downloading Prisma engines for debian-openssl-1.1.x...** ....I'm bit confuse now with this :/ ...will let you know when finish the download what happen.

**Comment by carlitorweb** [comment]
It finish successfully

**Comment by carlitorweb** [comment]
Running again `npx prisma db push --preview-feature` and it finish now successfully. So, seen the problem was on my side, right?

**Comment by janpio** [comment]
I think that was also running in the background when it got stuck - and waiting a bit more would probably have succeeded as well (Can you maybe nuke your `node_modules`, run `npm install` and then try again?). But of course we are hiding this progress output in `migrate dev` here - which I would consider a usability problem.

**Comment by carlitorweb** [comment]
@janpio is correct, after remove the `node_modules`, and run `npm install` the process was running in the background. 

Today I install v2.21.2, and I see a script downloaded already the engine, so this problem will not repeat from new install.

**Comment by janpio** [comment]
Thanks, so we should really make sure this is more visible to users and they/you will not be confused about this any more.
