### ISSUE TITLE
Warns when there are pending migrations

### ISSUE THREAD

**Issue by jasonlimantoro** [prisma/prisma#6940]
## Problem

Users may forget to run migrate after changing the schema. Even if they remember, users still need to manually check the database to see whether there are any migrations to be applied.

## Suggested solution

Prisma should warn when there are any pending migrations on the application level (when starting the server) and instructs the user to run the migrate command.

## Alternatives

None.

## Additional context

This is similar to how Django handles it. If you used Django before, the following logs may be familiar
```
Performing system checks...

System check identified no issues (0 silenced).

You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, contenttypes, frontend, sessions.
Run 'python manage.py migrate' to apply them.

May 05, 2021 - 15:19:20
Django version 2.1.1, using settings 'app.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

**Comment by tomhoule** [comment]
Thanks for this feature request! Let's use this issue for discussion. Could using `prisma migrate status` before the app start be an alternative in your case?

**Comment by jasonlimantoro** [comment]
That's a viable alternative solution, didn't know that command exists 👍.
