### ISSUE TITLE
`getDMMF` stopped supporting preview features

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma#6946]
## Bug description

The recent feature flag changes (https://github.com/prisma/prisma/issues/6575) caused `getDMMF` function from `@prisma/client/generator-build` to stop producing proper Prisma DMMF with some preview features enabled. The options are ignored and the generated DMMF is a standard one.

I've refactored my code to use new `GetDMMFOptions` property name (from `enableExperimental` to `previewFeatures`) but it still produces standard, not featured Prisma DMMF.

I've checked the PRs and I suspect the bug is located here:
https://github.com/prisma/prisma/pull/6714/files#diff-fe4f294696857fc7c07d9598c24d1bbee820d036f969da70193b84278c2b8316R86

`previewFeatures` option in `getDMMF` function from `src/packages/sdk/src/engineCommands.ts` is used only to warn about removed preview features but it's not actually passed to the query engine.

## How to reproduce

Try to use `getDMMF` function from `@prisma/client/generator-build` and provide `previewFeatures` option.

## Expected behavior

It should work like in 2.21.

## Environment & setup

- OS:  Ubuntu 20.04
- Database:  PostgreSQL
- Node.js version:  15.8
- Prisma version:

```
prisma               : 2.22.0
@prisma/client       : 2.22.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at ../node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at ../node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at ../node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at ../node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

**Comment by MichalLytek** [comment]
As spoken with @williamluke4, Query Engine now uses `previewFeatures` from the prisma client generator block in datamodel. So it's rather undocumented change than a bug.

So leaving up to you guys if you want to handle that somehow to support the old behavior or just have a minor breaking change.

**Comment by dpetrick** [comment]
The underlying protocol, including the type information of the DMMF, is undocumented and subject to change without notice. Changes on the DMMF are not considered breaking changes for Prisma if it doesn't surface on the API.
However, I understand any annoyance that may arise from that - for what it's worth, we plan on making a pass over the DMMF to open up the generator ecosystem, which will stabilize the API and make it subject to versioning and breaking change control in the future. 

That said, the old behavior will not be restored, we do not want to start down the path of preserving legacy behavior before a formal stabilization of DMMF.
