### ISSUE TITLE
Prisma WhereUniqueInput typings within node_modules are incorrect/broken

### ISSUE THREAD

**Issue by alanlichen** [prisma/prisma#6953]
## Bug description
Prisma's typings in node modules for the update function (UserScoresWhereUniqueInput) are wrong. It isn't including everything from my schema, only the id. 
I have attempted to reinstall prisma, completely remove the node_modules, and run `npx prisma generate` again, but none of them succeeded in updating the typings correctly. The schema in the database looks correct, just not in the typings.

## How to reproduce
Generate a prisma schema, put something similar to
```prisma
model UserScores {
	id           Int    @id @default(autoincrement())
    guildId      String
    userId       String
    globalPoints Int
    weeklyPoints Int
}
```
in it, and try npx prisma generate. The d.ts file in .prisma where it says UserScoresWhereUniqueInput should only include the id.

## Expected behavior
I expect UserScoresWhereUniqueInput to contain the rest of the things on the model, like guildId and userId.

## Prisma information
Full schema:

```prisma
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}

model settings {
    id      Int     @id @default(autoincrement())
    guildId String
    prefix  String
}

model userScores {
    id           Int    @id @default(autoincrement())
    guildId      String
    userId       String
    globalPoints Int
    weeklyPoints Int
}
```

Database query that is erroring (typescript)
```ts
            await prisma.userScores.update({
                where: {
                    userId: message.author.id,
                    guildId: message.guild!.id,
                },
                data: {
                    globalPoints: 0,
                },
            });
```

## Environment & setup

- OS:  Windows 10
- Database:  Postgresql
- Node.js version:  v14.16.0
- Prisma version: 

```
prisma               : 2.22.0
@prisma/client       : 2.22.0
Current platform     : windows
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\prisma-fmt-windows.exe)  
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

**Comment by alanlichen** [comment]
Also, I'm not 100% sure if this is related, but whenever I run `tsc -w` I get a bunch of errors from node_modules. 
![image](https://user-images.githubusercontent.com/40917647/117188646-2440f780-ad92-11eb-90ec-5dbd7339956b.png) Also, I've looked at previous issues and seen that you need a higher ts version but mine is at `^4.2.4` so it doesn't seem to be the issue.

**Comment by alanlichen** [comment]
I have just realized that this also happens with the delete function, and any function that uses where. ex:
```js
		await prisma.userScores.delete({
			where: {
				guildId: guild.id,
				userId: member.user.id,
			},
		});
```

**Comment by AlaaZorkane** [comment]
Can you make sure that you're running the latest typescript compiler globally? run `tsc --version` directly in your terminal

**Comment by alanlichen** [comment]
First, I use yarn... Second, I didn't realize that I didn't update my global tsc :p It was still 4.0... Thanks for the heads up!
However, that still doesn't fix my original problem. I am still facing the issue where WhereUniqueInput only contains an ID.

**Comment by alanlichen** [comment]
Any updates? This is basically stopping development since I can't compile anymore :(

**Comment by bertrandmc** [comment]
Having the same issue, here is an example, for this model:
```
model ListItem {
  id                  Int      @id @default(autoincrement())
  reference           String   @default(uuid()) @unique
  createdAt           DateTime @default(now())
  updatedAt           DateTime @updatedAt

  type                String
  jsonData            Json? 
  isApproved          Boolean @default(false)
  isPublished         Boolean @default(false)
  isBlocked           Boolean @default(false)

  @@index([type, isApproved, isPublished, isBlocked])
}
```

The generated `ListItemWhereUniqueInput` is:
```
export type ListItemWhereUniqueInput = {
    id?: number
    reference?: string
}
```
Which is missing all the indexes `@@index([type, reference, isApproved, isPublished, isBlocked])` and the `jsonData` property.

When I try to update/find etc I get the error if I filter with any property besides id and reference. 

![Screenshot 2021-05-07 at 11 23 37](https://user-images.githubusercontent.com/2582353/117436695-2daf9880-af27-11eb-9254-4d3f1e545ffd.png)


Prisma Version: 2.22.1
Typescript Version: 4.2.4

**Comment by janpio** [comment]
There are not other reports of this, so please make sure your environment is not messed up in any way. Best approach to make sure is probably to create a new project and add your code slowly. If the default project already fails, you know it is not connected to Prisma - because generally Prisma is not broken right now or we would have a _lot_ more reports here.

**Comment by pantharshit00** [comment]
@alanlichen This is not reproducible. Please make sure you don't have outdated typescript compiler installed globally.

**Comment by alanlichen** [comment]
I will try to make a new project and try to reproduce it, if I cant reproduce it myself well then I'll close the issue.

**Comment by abriginets** [comment]
@janpio @alanlichen just ran into this issue too. It appears that to be able to search by any other column you must make it `@unique`. It kinda makes sense because searching by unindexed varchar column is really slow and should be avoided, but it's also frustrating when you are not able to find anything about this in the docs. Maybe I was not paying attention but thank God I didn't miss my relational databases lessons in university 😆

**Comment by alanlichen** [comment]
Ah ok, thanks, let me try to fix my code to see if it works now. I almost forgot about this issue lol

**Comment by janpio** [comment]
> @janpio @alanlichen just ran into this issue too. It appears that to be able to search by any other column you must make it `@unique`. It kinda makes sense because searching by unindexed varchar column is really slow and should be avoided, but it's also frustrating when you are not able to find anything about this in the docs. Maybe I was not paying attention but thank God I didn't miss my relational databases lessons in university 😆

I think you are misunderstanding here @abriginets. You can totally search for all fields - just not with the expectation to get a unique item returned (which the `WhereUNiqueInput` is for). `findMany` works fine for whatever you want to search for.

**Comment by alanlichen** [comment]
> I think you are misunderstanding here @abriginets. You can totally search for all fields - just not with the expectation to get a unique item returned (which the `WhereUNiqueInput` is for). `findMany` works fine for whatever you want to search for.

The `where` part is the `UserWhereUniqueInput` type: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#reference-9
![image](https://user-images.githubusercontent.com/40917647/133183229-2dcc57c8-401d-45c7-a135-5c8660aafbe8.png)

Does this mean that I need to add `@unique` to my userId col? However, that would be completely unfeasible since that means I also need to make the guildId column unique too, but it is not unique. The `UserWhereUniqueInput` only contains my id, which has an autoincrement on it. The rest are not.
```ts
  export type UserScoresWhereUniqueInput = {
    id?: number
  }
```
```prisma
model UserScores {
	id           Int    @id @default(autoincrement())
    guildId      String @map("guild_id")
    userId       String @map("user_id")
    username     String
    globalPoints Int    @map("global_points")
    uLevel       Int    @map("u_level")
    weeklyPoints Int    @map("weekly_points")
    globalRank   Int    @map("global_rank")
    weeklyRank   Int    @map("weekly_rank")

	@@map("user_scores")
}
```
![image](https://user-images.githubusercontent.com/40917647/133183814-7f561d8c-e025-448b-a5ce-f765c8fd78aa.png)

The code, once again:
```ts
		await prisma.userScores.delete({
			where: {
				userId: member.user.id,
				guildId: guild.id,
			},
		});
```

**Comment by janpio** [comment]
If you do not have a unique guarantee on the field you want to filter for, you need to use `deleteMany` or `updateMany` and it should let you filter as you are trying to.

**Comment by alanlichen** [comment]
Oh thats confusing. IN sql, you just need to `DELETE ... WHERE x=y`, and I don't think it needs to be unique. That's what confused me, thanks!

**Comment by janpio** [comment]
Any suggestions how we could make that clearer or surface it at the right time?

**Comment by LabLamb** [comment]
I have colleagues that asked me the same question. I think it is perfectly fine to use `updateMany` if we dont use `uniqueWhere`, one DX improve can be adding a suggestion/tip saying:

> Do you mean `updateMany`?

**Comment by LabLamb** [comment]
@janpio 

> Any suggestions how we could make that clearer or surface it at the right time?

I have colleagues that asked me the same question. I think it is perfectly fine to use `updateMany` if we dont use `uniqueWhere`, one DX improve can be adding a suggestion/tip saying:

> Do you mean `updateMany`?

**Comment by fuedgabriel** [comment]
Would there be a solution to this problem that relates the two ids and makes them unique, but only if there are these two ids, if it is the same id and a different one, it is no longer unique. This via schem.prisma


I had the same problem, since the table is not unique. Code below with the problem.
`const watchedAlreadyExists = await prisma.watched.findUnique({
        where: {
            userId: userId,
            episodeId: episodeId
        }
    }
);`
`The type '{ userId: string; episodeId: string; }' cannot be assigned to type 'WatchedWhereUniqueInput'.
   The type '{ userId: string; episodeId: string; }' cannot be assigned to type '{ id: string; } & { id?: string | undefined; AND?: WatchedWhereInput | WatchedWhereInput[] | undefined; OR?: WatchedWhereInput[] | undefined; ... 9 more ...; episode?: (Without<...> & EpisodesWhereInput) | ... 1 more ... | undefined; }'.
     Property 'id' is missing in type '{ userId: string; episodeId: string; }', but it is mandatory in the type '{ id: string; }'.ts(2322)
index.d.ts(6518, 5): The expected type comes from the 'where' property, which is declared here in the type '{ select?: WatchedSelect<DefaultArgs> | null | undefined; include?: WatchedInclude<DefaultArgs> | null | undefined; where: WatchedWhereUniqueInput; }`






Solution:
`const watchedAlreadyExists = await prisma.watched.findFirst({
        where: {
            userId: userId,
            episodeId: episodeId
        }
    }
);`
The solution is to place a findFirst, but there will not be another element like this in the table. I think this solution is due to bad programming practices
