### ISSUE TITLE
Prisma types are not regeneraetd until Visual Studio Code restarts

### ISSUE THREAD

**Issue by theowiersema** [prisma/prisma#6958]
## Bug description

When adding a new model to my schema, Visual Studio Code fails to realize that I can use this as a property on the prisma object until I restart the program. Perhaps this is a Visual Studio Code bug instead? Sorry if so and feel free to close. 

## How to reproduce

1. Open schema and a .ts file in Visual Studio Code
2. Add a model to your schema, or change the name of your schema
3. Try to find the new or renamed schema in your .ts file
4. It cannot

## Expected behavior

I would expect the new schema values to be available in my .ts files. 

## Prisma information

No special schema in place. You can reproduce this with this simple code in your .ts file:

``const test = await prisma.schemaName.findMany();``

## Environment & setup

- OS: Mac OS
- Database: SQLite
- Node.js version: v14.4.0
- Prisma version

```
2.21.2
```

**Comment by janpio** [comment]
Did you `npx prisma generate` a new Prisma Client after changing the schema? (after step 2, before step 3)
Are you using the Prisma VSCode extension?

**Comment by theowiersema** [comment]
Sorry, I should have included that in the steps in my question. Yes, I'm running `npx prisma generate` in between steps 2 and 3. I also have the Prisma VsCode extension installed. 

The specific versions are as follows: 

Prism extension 2.22.0
VsCode 1.56.0
macOS Big Sur 11.4

**Comment by theowiersema** [comment]
Ok so this is weird. It's working now. I'm baffled as I have no idea what I changed!

Thanks for the help regardless!

**Comment by janpio** [comment]
VSCode and Typescript are not super big friends when it comes to reload type definitions. We actually do some fancy stuff in our VSCode extension to try to work around that, but it does not work _all_ the time (and unfortunately there is no way for us to recognize). Maybe you hit one of these cases.

**Comment by theowiersema** [comment]
Hmm. Well if I ever come across another reproducible case I'll attempt to document it. In the meantime, when in doubt I can just `npx prisma generate` excessively ;)
