### ISSUE TITLE
Inconsistent table names in migrations

### ISSUE THREAD

**Issue by macjuul** [prisma/prisma#6962]
## Bug description

The capitalization for generated table names appears to be inconsistent. When creating new tables, the migrations contain the capitalized and correct version of the table names, however altering the model causes an alter migration to be created with a fully lowercase version of the table name. This causes issues where migrate fails because it cannot find the right table.

Creation migration:
![image](https://user-images.githubusercontent.com/7606171/117281214-b2d17980-ae63-11eb-93a3-10b2dc0124b3.png)

Alter migration:
![image](https://user-images.githubusercontent.com/7606171/117281259-c086ff00-ae63-11eb-9c30-7e0176250034.png)

This causes my production setup to break with `The underlying table for model 'report' does not exist.`

## How to reproduce

1. Create a migration adding a new table
2. Create a migration that alters the previously created table
3. The generated alter query will use a lowercase version of the table name

## Expected behavior
The migration files should contain the actual model names, which in my case are capitalized

## Environment & setup

- OS: Windows 10
- Database: MariaDB
- Node.js version: v12.18.4
- Prisma version:

```
prisma               : 2.22.0
@prisma/client       : 2.22.0
Current platform     : windows
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at  node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
Preview Features     : orderByRelation
```

**Comment by janpio** [comment]
Can you maybe show the full cycle - initial schema, generated migration file, adapted schema file (with modified model), and then the next migration file that uses the wrong casing? That would help us understand what is going on.

MariaDB on Windows is most probably the culprit here, there are funny things going on with MySQL like databases on Windows quite often which we are partially already handling - probably that is one of the things we are not.

**Comment by macjuul** [comment]
I've managed to reproduce it with a simple example

Initial schema:
```prisma
generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["orderByRelation"]
}

datasource db {
    provider = "mysql"
    url      = env("DATABASE_URL")
}

model User {
    id   Int    @id @default(autoincrement())
    name String
}
```

Which generates the following migration:
```sql
-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

If I now add a new `status` field to my `User` model like so:
```prisma
model User {
    id     Int    @id @default(autoincrement())
    name   String
    status String @default("active")
}
```

The following migration will be generated, this time with a lowercase table name:
```sql
-- AlterTable
ALTER TABLE `user` ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'active';
```

**Comment by pantharshit00** [comment]
Hmm I wasn't able to reproduce this. This is what I get when I generate the migration:
```sql
ALTER TABLE `User` ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'active';
```

Can you please tell me whether your database is running inside of docker or it is running directly in Windows? MySQL on windows does have some text case related quirks so this might be related to that.

**Comment by janpio** [comment]
Maybe also see if you can share your MariaDB configuration, especially around things like https://mariadb.com/docs/reference/mdb/system-variables/lower_case_table_names/

How is the table shown in some other database GUI - lower or uppercase?

**Comment by macjuul** [comment]
After some more testing it does actually look like my local Windows installation is handling the difference in capitalization correctly, however I'm only experiencing issues on my Ubuntu production server

![image](https://user-images.githubusercontent.com/7606171/117310814-ed4b0e80-ae83-11eb-8f53-5e95de26d9ec.png)

While locally on Windows running `SHOW TABLES` returns all tables in lowercase, on Ubuntu it shows up capitalized. I did check the config files (there seem to be quite a few on ubuntu) however I could not find any reference to the setting, so presumably it is using the default value

**Comment by pantharshit00** [comment]
Yeah this is known, by default windows mariadb lowercase everything. I will suggest you run the database in docker for now for development so that it can match the production environment.

**Comment by macjuul** [comment]
Running my local MariaDB has indeed solved the problem and generates correct migration files. Thanks!

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/6972
