### ISSUE TITLE
Doesn't throw an error if the schema is wrong during development 

### ISSUE THREAD

**Issue by kolserdav** [prisma/prisma#6978]
### Bug description

Hello! After updating to version `2.22.0`, I had a confusion, when `schema.prisma` was composed incorrectly, `prisma migrate dev` worked and `prisma migrate deploy ` did not work. Previously, in this case, it gave an error already at `prisma migrate dev`. 

### How to reproduce

Example `schema.prisma`:
```
model First {
  id           Int        @id @default(autoincrement())
  secondId Int // Required parameter
  Second   Second? @relation(fields: [secondId], references: [id]) // Optional parameter
}

model Second {
  id           Int        @id @default(autoincrement())
  First First[]
}
```

### Expected behavior

Should give an error if the parameters are incorrectly specified in the circuit after `prisma migrate dev`

### Prisma information

version 2.22.0

### Environment & setup

OS Arch linux  
node.js v14.16.0
```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

**Comment by pantharshit00** [comment]
Hey @kolserdav 

I am unable to reproduce this. The schema you provided is valid. You can have an optional relation with non optional id, but not the other way around.
