### ISSUE TITLE
Feature: expose dmmf information on Prisma client

### ISSUE THREAD

**Issue by stalniy** [prisma/prisma#6979]
## Problem

I'm author of https://casl.js.org/  (permission management library) and working on integrating prisma with casl. This requires translation of MongoDB Query dialect into Prisma WhereInput. To do, so I'd like to overload some of the Mongo operators. For example, in Mongo `$in` can be used for both arrays and scalars but in Prisma there are separate operators: `in` for scalars and `has` & co for arrays. 

## Suggested solution

By having access to `prisma._dmmf.modelMap` I can implement this overload because I can check the field type and if it's an array convery `$in` to `hasSome` and if it's a scalar to `in`

## Alternatives

I can use `prisma._dmmf.modelMap` but it's not reliable as it can go away in any next release. Alternative solution for me is to implement PrismaQuery interpreter in JavaScript, this is doable but requires more dancing with Prisma types. I will describe it in another issue.

**Comment by stalniy** [comment]
looks like `Prisma.dmmf` contains what I need

**Comment by janpio** [comment]
Be aware that `Prisma.dmmf` is not a public, stable API so it is not uncommon for this to be changed with short or no notice. 

Are you using a Slack community regularly? Then we could create a shared channel with our community at slack.prisma.io for the cases where you have questions etc.

When you are done, please also let us know over at https://github.com/prisma/e2e-tests/ so we can create an end to end test. Those are tested with each of our development versions to catch regressions and mismatches early.

**Comment by stalniy** [comment]
Yes. I’m using slack. I’ve just joined prisma slack. A separate channel for questions would be very helpful!

thank you

**Comment by stalniy** [comment]
I decided to go into another direction, instead of translating mongodb query to prisma query, I created a js runtime interpreter for prisma query. 

But even in that case I need dmmf details in order to overload `equals` operator because it can be use for scalars, json, arrays and for relation queries

**Comment by janpio** [comment]
I think I invited you to a channel, if that was not you please ping me @janpio
