### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by BishoyNarouz** [prisma/prisma#7003]
### Bug description

```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("26000"), message: "prepared statement \"s87\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(502), routine: Some("FetchPreparedStatement") }) }) })
```

### Environment & setup

- OS: ubuntu
- Database: PostgreSQL
- Node.js version: 14
- Prisma version: 2.22.0

```

```

**Comment by janpio** [comment]
Can you provide some more information @BishoyNarouz?
Seems like you are using PostgreSQL and for some reason one of the prepared statement names was already taken - this should not really happen. Are you using a pooled connection, e.g. via PgBouncer or similar? If so, did you enable the [PgBouncer mode in Prisma](https://www.prisma.io/docs/guides/performance-and-optimization/connection-management/configure-pg-bouncer)?

**Comment by BishoyNarouz** [comment]
Currently i'm using PostgreSQL version 12 hosted on **DigitalOcean**, and i'm already enabled **PgBouncer** on **transaction mode** in the connection string and created connection pool with 22 connection. 

To be more details, once the application start i found that the reserved connection up to 6 and sometime up to 9 and this number of connections never closed after the query finished. 

On the other side, i'm using the Prisma/Client based on the primsa documentation as like below 

```
import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit, OnModuleDestroy {
	async onModuleInit() {
		await this.$connect();
	}

	async onModuleDestroy() {
		await this.$disconnect();
	}
}

```

Should I close the connection after each query? If yes, i tired it and i always got a message said "Closed By Other Side"

**Comment by BishoyNarouz** [comment]
I’m using pgbouncer as per the documentation but i just need to add that i’m hosted the application on Digitalocean App Platform service is this might the cause of the issue. DigitalOcean using the same way like Heroku for deploying the application.
