### ISSUE TITLE
Unable to use dbgenerated uuid_to_bin for ID field: "Could not figure out an ID in create"

### ISSUE THREAD

**Issue by mahesh-neu-edge** [prisma/prisma#7010]
Hi Team,
I am facing an issue where I am unable to use `dbgenerated` for mysql8 function uuid_to_bin to associate with my default id . I am getting error as below. I have attached my schema  and probably other related details that might be required. Let me know if i am doing this wrong  , i did not find anything relevant in documentation that can help.

```
PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22
Could not figure out an ID in create

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | rhel-openssl-1.1.x |
| Prisma Client   | 2.22.1             |
| Query Engine    | query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c|
| Database        | undefined|

## Schema
```
model User {
 
  id      Bytes    @id @db.Binary(16) @default(dbgenerated("(uuid_to_bin(uuid()))"))
  email   String   @unique @db.VarChar(320)
  name    String?
  contact String   @db.VarChar(15)
}
```

## Query
```
mutation {
  createOneUser(data: {
    name: "X"
    email: "X"
    contact: "X"
  }) {
    id
    email
    name
    contact
  }
}
```

## Logs
```
  prisma:tryLoadEnv Environment variables loaded from /home/xxx/xxx/prisma-test/.env  
  prisma:tryLoadEnv Environment variables loaded from /home/xxx/xxxt/.env  
  prisma:client clientVersion: 2.22.1  
  prisma:engine { cwd: '/home/xxx/xxx/prisma-test/prisma' }  
  prisma:engine Search for Query Engine in /home/xxx/xxx//prisma-test/node_modules/.prisma/client  
  prisma:engine Search for Query Engine in /home/xxx/xxx//prisma-test/node_modules/.prisma/client  
  plusX Execution permissions of /home/xxx/xxx/prisma-test/node_modules/.prisma/client/query-engine-rhel-openssl-1.1.x are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '43487' ] }  
  plusX Execution permissions of /home/xxx/xxx//prisma-test/node_modules/.prisma/client/query-engine-rhel-openssl-1.1.x are fine  
  prisma:engin

**Comment by mahesh-neu-edge** [comment]
Yes , I ran the introspect to get that schema. 
You are right on the part about uuid_to_bin() but it is not trying to convert Prisma's uuid function but rather leaving the autogeneration of PK to underlying mysql db.

**Comment by janpio** [comment]
Thanks for the clarification. 

Can you maybe share the SQL of that table - then we can just try ourselves with Introspection, and run a query ourselves to reproduce the problem.

I think the Logs in your initial post are also truncated unintentionally. It would be super helpful if you still had the Prisma Client query that was executed there.

**Comment by mahesh-neu-edge** [comment]
It seems the issue is with the dbgenerated itself , I ran into something similar while trying to create a schema with dbgenerated for created_at field as well, Maybe this would be a different topic but thought to mention it here. 
Sorry about the logs , i only used the autogenerated link in the console to create this issue . I will try to see if i can add anything  more if you are unable  to use below data to reproduce it.

I could reproduce the same issue with a small subset of this table , here is the SQL query 
```
-- CreateTable
CREATE TABLE `IdTest` (
    `id` BINARY(16) NOT NULL DEFAULT (uuid_to_bin(uuid())),
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

```

Schema

```
model IdTest {
  id      Bytes    @id @default(dbgenerated("(uuid_to_bin(uuid()))")) @db.Binary(16) 
  created_at          DateTime  @default(now())
}
```

and you can simply do this to get this recreated
```
await prisma.idTest.create({
  data: {

}
})

```

**Comment by pantharshit00** [comment]
Thanks for the clear reproduction @mahesh-neu-edge. I can confirm this bug and it does cause an engine crash.

**Comment by maheshmahadevan** [comment]
Great , glad i could help .. I was hoping I could use this feature to reduce the amount of storage i need to keep all the uuid keys across the application i am making by making use of Binary fields. Hoping that you could give a patch for this soon :)

**Comment by mahesh-neu-edge** [comment]
Hi Guys, sorry to bug you with this , but is there is plan to fix this in any upcoming release or as a patch. I am not sure if there are any workarounds possible here. I am in last stages of finalizing my db schema for the application and do not want to go over the pain of migrating all of these columns to binary once the changes are in. I would really like to use binary columns for my uuid to begin with.
Thanks in advance

**Comment by wjdqhry** [comment]
I have a similar issue....

**Comment by janpio** [comment]
Related issue about current problems migrating a schema that can cause the error that is talked about here: https://github.com/prisma/prisma/issues/10715

**Comment by janpio** [comment]
Can you @maheshmahadevan @iRoachie @wjdqhry or @mahesh-neu-edge maybe try the `prisma@dev` and `@prisma/client@dev` packages to confirm this now works as expected? Thanks.

**Comment by iRoachie** [comment]
@janpio can confirm it works using the dev packages:

```json
"devDependencies": {
  "prisma": "^3.10.0-dev.31"
},
"dependencies": {
  "@prisma/client": "^3.10.0-dev.31"
}
```

**Comment by plattenbrand** [comment]
Same issue, not working on prisma v 3.11.1
Looks like the id field is sent with the query causing a Null constraint violation on the fields: (`id`)

**Comment by janpio** [comment]
Can you please open a new issue @plattenbrand? The previous posters here had their problem fixed, so if you are still having something like this we need a separate issue so we can properly investigate. Thanks!
