### ISSUE TITLE
Typings in Prisma client only work for the first model in the schema

### ISSUE THREAD

**Issue by tgrander** [prisma/prisma#7014]
### Bug description

Typings in Prisma client only work for the CRUD operations of the first model in `node_modules/.prisma/client/index.d.ts`.

The typings for the first model in the schema work fine. i.e. `prisma.user.createMany()` are auto completed with TS as I type. Hovering over `createMany` brings me to the typed definition in prisma client `index.d.ts` file. 

The same is not true for all other models in the schema. i.e. `prisma.property.createMany` stops auto completing after `.property` and hovering over `createMany` displays type `any`. 

If I go to `node_modules/.prisma/client/index.d.ts` I see that `Prisma.PropertyDelegate` has TS error of `node_modules/.prisma/client/index".Prisma' has no exported member 'PropertyDelegate'`. 

![Screen Shot 2021-05-10 at 11 13 01 AM](https://user-images.githubusercontent.com/15262143/117683262-e4a75080-b181-11eb-8fc0-1d264a2442b4.png)

However, `PropertyDelegate` DOES exist in the file. The code will run successfully but I get none of the benefits of using TS with Prisma client. 

**Why would all `XDelegate` types after the first model appear to TS as not existing?**

### How to reproduce

I created a repo to reproduce the error
1. Go to https://github.com/tgrander/prisma-heroku-ts
2. Download repo
3. Run `npm install`
4. Try to use prisma client for the post model, i.e.`prisma.post.createMany` - it will not work
5. Try to use prisma client for the user model, i.e.`prisma.user.createMany` - it will work because it is first model in schema

### Expected behavior

I expect prisma client typings to work for all models - not just the first model in the schema. 

## Schema
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  email String  @unique
  id    Int     @id @default(autoincrement())
  name  String?
  posts Post[]
}

model Post {
  authorId  Int?
  content   String?
  id        Int     @id @default(autoincrement())
  published Boolean @default(false)
  title     String
  author    User?   @relation(fields: [authorId], references: [id])
}

```

### Typings work and autocomplete for model
```
await prisma.user.deleteMany({
      where: {
        email: "jane@prisma.io",
      },
    });
```
### Typings DO NOT work or autocomplete for model
```
await prisma.post.deleteMany({
      where: {
        author: {
          email: "jane@prisma.io",
        },
      },
    });
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: tried on 14.6 and 16.0
- Prisma version: prisma 2.22, @prisma/client 2.22

**Comment by janpio** [comment]
Ok, that is _really_ weird. I know this sounds stupid, but have your fully restarted your VSCode and possibly computer? The language server sometimes is a bit stubborn...

**Comment by tgrander** [comment]
Hi @janpio, thanks so much for taking the time to get back to me. It _is_ weird! I upgraded and quit VSCode, restarted computer, deleted node_modules, npm installed and ran `npx prisma generate`... but the error persists. Have not been able to find any other issues or questions online about this particular problem, which makes me believe it may in fact be my machine. Such a strange and impeding error to have... any other ideas?

**Comment by janpio** [comment]
Not yet, but someone will soon try to use your reproduction and see if it happens for them as well.

**Comment by tgrander** [comment]
@janpio I tried it on a different machine and the problem persisted. Seems that it is not my local machine after all. The repos I tried were the prisma example repos for graphql-express and heroku deployment. Same exact problem with both repos on both of my machines: only the first model in the schema can make use of the Prisma client typings. All subsequent models are untyped with the same error described in my original issue.

**Comment by pantharshit00** [comment]
I am unable to reproduce this:
![image](https://user-images.githubusercontent.com/22195362/118279554-e73ed880-b4e8-11eb-907b-9d71386c8766.png)


Can you please check the version of global typescript compiler installation if any that you have in your system and whether vscode is using that or not?

**Comment by tgrander** [comment]
WOW. Thank you for pointing out the obvious @pantharshit00!!! Problem solved.

**Comment by pantharshit00** [comment]
Ah, I'm glad that solved the issue, Thanks!

**Comment by janpio** [comment]
Can we do anything to catch this @pantharshit00? Either in our tooling or VSCode?

**Comment by longyarnz** [comment]
What did you do to fix this @tgrander exactly?

**Comment by pantharshit00** [comment]
There is already an issue about this: https://github.com/prisma/prisma/issues/5728

It will block the generator process when it detects user is using the wrong TS version .

**Comment by netojose** [comment]
Probably you're using Docker, and inside container, the generated types aren't present. You can fix this mapping the directory `node_modules/.prisma` to volume
