### ISSUE TITLE
Redis Data Connector

### ISSUE THREAD

**Issue by chrisui** [prisma/prisma#7025]
## Problem

As a user I would like to be able to have schema driven and type safe data storage using a redis API. In particular a use case could be to use Upstash which provides a durable, serverless data storage using the standard redis API.

## Suggested solution

Provide a Redis connector in addition to MySQL, PostgreSQL etc..

## Alternatives

None afaict.

**Comment by blazestudios23** [comment]
I want to be able to use Prisma with Postre and Redis at the same time. This would be amazing.

**Comment by omertoast** [comment]
As @blazestudios23 said, using Prisma with Postre and Redis would be awesome. Prisma ecosystem can make using Redis much more productive and easier.

**Comment by Nditah** [comment]
This will be super-cool.

**Comment by jdgamble555** [comment]
**RedisGraph** specifically would be great!

**Comment by ansh** [comment]
Definitely would want this.

**Comment by lukeclifton** [comment]
Yes this would make a lot of sense. Love Prisma so far.

**Comment by steven-tey** [comment]
Would be amazing to be able to use Prisma + Redis Cloud!

**Comment by itsdevcoffee** [comment]
Any updates or plans to implement Redis? I've been using RedisOM as my primary database and I feel a Prisma implementation would be superior

**Comment by WilderDev** [comment]
Bumping to see progress on this to build out Redis + Postgres w/ Prisma. Will help if the project has been started!

**Comment by chronark** [comment]
I would also want to help as a contribution from Upstash

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
