### ISSUE TITLE
[MongoDB] Smooth out the workflow for updating your schema

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#7030]
Follow-up to the original issue https://github.com/prisma/prisma/issues/6688 and https://github.com/prisma/prisma/issues/6715 which improves the error.

## Problem 

You have a schema

```prisma
model Post {
  title String
}
```

Then you:

- You generate a client
- You insert a record
- You run prisma.post.findMany() all good.

Now you're ready to expand your schema. You add a title:

```prisma
model Post {
  title String
  slug String
}
```

Then you:
- You generate a client
- You run prisma.post.findMany() .

You'll run into an error. At the time of writing that error is:

```
Attempted to serialize scalar 'null' with incompatible type 'String'.
```

Your previous insert doesn't have the required title. This is technically correct because your schema is describing an invalid shape of your actual data, but it's super easy to run into.

**Update:** This is also a problem if you add a default.

```prisma
model Post {
  title String
  slug String @default("")
}
```

Re-generate the client and run `prisma.post.findMany()` again:

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: 
Invalid `prisma.posts.findMany()` invocation:


  Attempted to serialize scalar 'null' with incompatible type 'String'
    at cb (/Users/m/dev/src/github.com/prisma/mongo-compare/node_modules/@prisma/client/runtime/index.js:35102:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runPrisma (/Users/m/dev/src/github.com/prisma/mongo-compare/index.js:22:17)
    at async main (/Users/m/dev/src/github.com/prisma/mongo-compare/index.js:75:5) {
  clientVersion: '2.22.1'
}
```

## How Users Deal with this in other systems

- "I generally need to write the migrations manually, though"
- "when adding fields, usually if it is nullable, no migration is necessary.  only if there needs to be a new default value."
- "I use Mongoose, and so we add the field to the model. If we can apply a default we do and then when the record is loaded it will include that default if there is no value in the database. If required, we write a script to supply a value for the new field."
- "It would be ideal if that default actually updated the database record itself, if no value currently exists in a particular record."
-  "the data in the database is updated overtime. From an application perspective when supplying a default, the data is manipulated by mongoose in between loading and passing the data to the application."
- "The other thing to consider is using MongoDB aggregations in Mongoose. When you do that via Mongoose you loose the benefits of the default data being applied by Mongoose so its often handy to just go ahead and make sure the database actually has the default data you require"

**Comment by matthewmueller** [comment]
Looked at how Mongoose deals with it. The short answer is that they don't follow a strict schema on past data:

```diff
 const Post = mongoose.model("Post", {
   title: { type: String },
+  slug: { type: String, required: true },
 })
```

Added a required field after you've already inserted some data results, then if you try finding it with `await Post.find()`, you'll get:

```json
[
  {
    "_id": "609a85773e3b2d30b885ba79",
    "title": "Mongoose Title!",
    "__v": 0
  },
  {
    "_id": "609a85db1d7ed331b6ca1d93",
    "title": "Another post",
    "slug": "another-post",
    "__v": 0
  }
]
```

In other words, slug is `string | undefined` despite the schema saying it's a required string.

**Comment by matthewmueller** [comment]
Still running into this unfortunately.

**1. Given the following Prisma Schema:**
```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

model User {
  id        Int    @id @map("_id")
  firstName String
}
```

**2. Run `npx prisma generate` and then write the following script**

```ts
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  await prisma.$connect()
  await prisma.user.create({
    data: {
      id: 1,
      firstName: "Matt",
    },
  })
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
```

**3. Run the script with `ts-node index.ts` to write some data**
**4. Adjust the `schema.prisma`**

```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

model User {
  id        Int    @id @map("_id")
  firstName String
  lastName String // Also doesn't work with @default("")
}
```

**5. Run `npx prisma generate`**
**6. Adjust `index.ts` script to find old data**

```
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  await prisma.$connect()
  console.log(await prisma.user.findMany())
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
```

**6. Run the script again `ts-node index.ts`** 

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: 
Invalid `prisma.user.findMany()` invocation:


  Attempted to serialize scalar 'null' with incompatible type 'String' for field lastName.
    at cb (/Users/m/dev/src/github.com/prisma/qa-may-31/node_modules/@prisma/client/runtime/index.js:35201:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at main (/Users/m/dev/src/github.com/prisma/qa-may-31/index.ts:7:15) {
  clientVersion: '2.24.0-dev.34'
}
```


Environment Information

```
npx prisma -v
Environment variables loaded from .env
prisma               : 2.24.0-dev.34
@prisma/client       : 2.24.0-dev.34
Current platform     : darwin
Query Engine         : query-engine 3e7fd9395fd522da21025ecfd731803bae72fd2f (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 3e7fd9395fd522da21025ecfd731803bae72fd2f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 3e7fd9395fd522da21025ecfd731803bae72fd2f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 3e7fd9395fd522da21025ecfd731803bae72fd2f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 3e7fd9395fd522da21025ecfd731803bae72fd2f
Studio               : 0.397.0
Preview Features     : mongoDb
```

**Comment by dpetrick** [comment]
Current dev (and later 2.24) introduces that Mongo will fill in `@default("test")` constants (not generators like `cuid()`) for required fields on read.

**Comment by matthewmueller** [comment]
Nice, `@default` works in the latest dev! 

I'll be curious if people also want non-defaults to work, for example:

```diff
model Log {
  id      String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  level   Level
  message String
  meta    Json
+  version Int
}
```

If you add a version later and it's required without a default, that won't work, you need to add a default:

```diff
model Log {
  id      String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  level   Level
  message String
  meta    Json
+  version Int @default(1)
}
```

This feels okay to me to be explicit, but it does diverge from Mongoose which is the most popular Mongo ORM by a long shot. Mongoose returns undefined, we could return zero values to maintain our schema's integrity.

Food for thought. Closing this one, if we hear people wanting non-default we can open a new issue.
