### ISSUE TITLE
PrismaClientValidationError on a Valid Query

### ISSUE THREAD

**Issue by jvcmarcenes** [prisma/prisma#7094]
### Bug description

In a next.js app, a call to findUnique is returning throwing a PrismaClientValidationError
the query:
```typescript
  let user = await prisma.user.findUnique({
    where: { 
      uid: body.uid
    }
  })
```
this is the error log:
```
PrismaClientValidationError:
Invalid `prisma.user.findUnique()` invocation:

{
  where: {
?   uid?: String,
?   email?: String
  }
}

Argument where of type UserWhereUniqueInput needs at least one argument. Available args are listed in green.

Note: Lines with ? are optional.

    at Document.validate (E:\joao\code-web\next-firebase-auth\node_modules\@prisma\client\runtime\index.js:32780:19)
    at NewPrismaClient._executeRequest (E:\joao\code-web\next-firebase-auth\node_modules\@prisma\client\runtime\index.js:34717:17)
    at E:\joao\code-web\next-firebase-auth\node_modules\@prisma\client\runtime\index.js:34652:52
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (E:\joao\code-web\next-firebase-auth\node_modules\@prisma\client\runtime\index.js:34652:25)
    at Object.then (E:\joao\code-web\next-firebase-auth\node_modules\@prisma\client\runtime\index.js:34772:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  clientVersion: '2.22.1'
}
```

### How to reproduce

1. Instantiate a prisma client
2. Make a call to findUnique

repo: https://github.com/jvcmarcenes/next-firebase-auth

### Expected behavior

The query seems correct, it does not make sense for the error to be thrown since a unique field was provided

### Prisma information

Schema:
```prisma

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  uid      String   @id
  email    String?  @unique
  name     String?
  provider String?
  photoUrl String?
  posts    Post[]
  comments Comment[]
}

model Post {
  id        String    @id @default(cuid())
  author    User      @relation(fields: [authorId], references: [uid])
  authorId  String
  title     String
  content   String
  createdAt DateTime  @default(now())
  comments  Comment[]
}

model Comment {
  id       String @id @default(cuid())
  author   User   @relation(fields: [authorId], references: [uid])
  authorId String
  content  String
  post     Post   @relation(fields: [postId], references: [id])
  postId   String
}
```
Query:
```typescript
  let user = await prisma.user.findUnique({
    where: { 
      uid: body.uid
    }
  })
```

### Environment & setup

- OS: Windows 8.1
- Database: SQLite
- Node.js version: 14.15.4
- Prisma version:
```
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : windows
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

**Comment by Karl-EdwardFPJeanMehu** [comment]
@jvcmarcenes Have you checked whether `body.uid` is indeed returning a value and that it is of type `string`?

**Comment by jvcmarcenes** [comment]
@Karl-EdwardFPJeanMehu yes, body.uid is returning a string
I've had a similar issue before, where actually setting both of the unique fields I had in the model made it work, that's not intended behavior tho

**Comment by Karl-EdwardFPJeanMehu** [comment]
I believe you need to regenerate the client. You seemed to have previously made the `uid` field optional. It is shown as optional in the error but not matching your model. You must have made it required field in your model.

**Comment by jvcmarcenes** [comment]
@Karl-EdwardFPJeanMehu I haven't changed my model since I first set it.
It is saying it is optional in the query attribute, since I could also query by the other unique field 'email'

**Comment by Karl-EdwardFPJeanMehu** [comment]
Anyhow, the query is fine. I tried it and I had no errors.

**Comment by jvcmarcenes** [comment]
That's odd, you tried it in the reproduction repo?
I believe it could be an issue with running the queries through a Nextjs app then

**Comment by pantharshit00** [comment]
@jvcmarcenes Can you make sure that `body.uid` is not undefined? If that is the case, prisma will omit that field from the query and it will throw that error(https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined)

So, if that can be `undefined`, you will need to handle that before you make the db call.

**Comment by jvcmarcenes** [comment]
I'm sorry, upon revisiting the issue I realized I simply forgot to parse the body.
The query is working
