### ISSUE TITLE
Migration checksum EOL-independent

### ISSUE THREAD

**Issue by andreamatt** [prisma/prisma#7101]
## Problem

Migrations have a checksum that depends on the EOL char.
I generate migrations on linux, push them, then my collegue on windows has a "migration modified after it was applied" issue.
Our current workaround is adding a .gitattributes so that git treats migrations' sql as binary (without changing newline on checkout).

## Suggested solution

Replace the newline char to LF before performing the checksum, so that the checksum is EOL-independent.

**Comment by Jolg42** [comment]
[A fix](https://github.com/prisma/prisma-engines/commit/10a1beca097abd55b7d4a40e6a1035985ba4e219) just got released in the dev channel on npm (not recommended for production).

If you can try this specific version `2.29.0-dev.20` to confirm it's fixing the issue for you and let us know it will be greatly appreciated! 💚 

It will be released next Tuesday in our biweekly release.

**Comment by andreamatt** [comment]
Great news, but I'm not sure how to test this without breaking my old migrations.
How will this handle migrations that are already applied to a db? Will it use the old checksum for them?

**Comment by Jolg42** [comment]
@andreamatt I checked with @do4gr and this should be backward compatible so it should not break the old migrations. It calculates several checksums and if any matches it will be ok.

https://github.com/prisma/prisma-engines/commit/10a1beca097abd55b7d4a40e6a1035985ba4e219#

**Comment by Jolg42** [comment]
Fix included in 2.29 release planned for tomorrow, August 10.

**Comment by krthush** [comment]
just to chime in (as a windows user) been experiencing this problem many times, even tho no changes made at all to the migrations - currently just ignoring all the warnings... for example this is vercel:
![image](https://user-images.githubusercontent.com/33790334/128760487-20384462-fec0-4a4f-b652-56e1f1aa5928.png)
and then locally:
![image](https://user-images.githubusercontent.com/33790334/128760717-b1dc4cd1-def8-431b-9d1d-26cf72400fe1.png)

hopefully the fix tomorrow will deal with this (and is backward compatible as you mentioned such that these warnings will go away) - will test and post back

**Comment by krthush** [comment]
Amazing just updated prisma and the warnings are gone :D Should hopefully work for anyone else who had the same issue as I and the others...

![image](https://user-images.githubusercontent.com/33790334/128915388-0c5cfb10-12db-400b-841c-b92401555141.png)

Thanks guys for this! 🚀
