### ISSUE TITLE
MongoDB: Many to many relation issue

### ISSUE THREAD

**Issue by shahriar-shojib** [prisma/prisma#7119]
### Bug description

> see schema below

when I try to create a new record using the following code:

```typescript
const doc = await this.prisma.book.create({
			data: {
				price,
				title,
				category: {
					connect: { id: categoryID[0] },
				},
				authorID: undefined,
				author: { connect: { id: authorID } },
			},
		});
```

### How to reproduce

1. Create a prisma schema using the provided schema and use mongo db
2. Try to add categories to book and author at the same time
3. See typescript error when you try to add authorId and category at the same time, when using the connect options, record inserts but get panic from prisma engine.
4. Cannot query books anymore after a failed insertion

### Expected behavior

It should create a collection to store the relation which is not getting created and gets an error instead

```
PANIC in query-engine\connectors\mongodb-query-connector\src\root_queries\write.rs:219:74
called `Option::unwrap()` on a `None` value
```

### Prisma information

```prisma
model Author {
    id        String @id @default(dbgenerated()) @map("_id") @db.ObjectId
    firstName String
    lastName  String
    Book      Book[]
}

model Category {
    id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
    title String
    slug  String @unique
    books Book[]
}

model Book {
    id       String     @id @default(dbgenerated()) @map("_id") @db.ObjectId
    title    String
    author   Author     @relation(fields: [authorID], references: [id])
    category Category[]
    price    Int
    authorID String     @db.ObjectId
}
```

### Environment & setup

- OS Windows 10
- Mongodb 4.4 local install
- Nodejs 14 lts
- prisma version 2.22.1(mongodb early access)

### Prisma Version

```
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : windows
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
Preview Features     : mongoDb
```

**Comment by dpetrick** [comment]
Mongo many-to-many relations work differently than the implicit many-to-many relations for the SQL providers. We're lacking validations right now to surface this, but here it goes:
```prisma
model Author {
  id           String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  firstName    String
  lastName     String
  category_ids String[] @db.Array(ObjectId)
  Book         Book[]   @relation(fields: [category_ids])
}

model Category {
  id       String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  title    String
  slug     String   @unique
  book_ids String[] @db.Array(ObjectId)
  books    Book[]   @relation(fields: [book_ids])
}
// ...
```

Note the array fields to hold related IDs and the relation annotations on the relation fields.
This is not set in stone and may change in future implementations of the Mongo provider, but use this to make many-to-many work for now.

**Comment by crazydev901** [comment]
Here is my schema and it produces an error.
`model User {
  id             String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt      DateTime @default(now())
  updatedAt      DateTime @updatedAt
  ...
  favProjects    Project[]  @relation(fields: [favProjectsIds])// Worker's favorite projects
  favProjectsIds String[] @db.Array(ObjectId)
  ...
}

model Project {
  id                String     @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt         DateTime   @default(now())
  updatedAt         DateTime   @updatedAt
  ...
}`
Error message:
`npx prisma format schema.prisma 
Environment variables loaded from ../.env
Prisma schema loaded from schema.prisma
Error: Schema parsing
error: Error validating field `favProjects` in model `User`: The relation field `favProjects` on Model `User` is missing an opposite relation field on the model `Project`. Either run `prisma format` or add it manually.
  -->  schema.prisma:42
   | 
41 |   limitPerDay    Int            @default(10) // Max number of proposals to be applied by talent per day
42 |   favProjects    Project[]      @relation(fields: [favProjectsIds]) // Worker's favorite projects
43 |   favProjectsIds String[]       @db.Array(ObjectId)
   | 

Validation Error Count: 1`
Could you let me know what's wrong in my schema? @dpetrick

**Comment by matthewmueller** [comment]
@crazydev901 this is a duplicate of: https://github.com/prisma/prisma/issues/6717

The workaround now is to manually write something like:

```diff
model User {
  id             String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt      DateTime @default(now())
  updatedAt      DateTime @updatedAt
  ...
  favProjects    Project[]  @relation(fields: [favProjectsIds])// Worker's favorite projects
  favProjectsIds String[] @db.Array(ObjectId)
  ...
}

model Project {
  id                String     @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt         DateTime   @default(now())
  updatedAt         DateTime   @updatedAt
  ...
+  user    User   @relation(fields: [userId], references: [id])
+  userId  String @db.ObjectId
}
```

**Comment by crazydev901** [comment]
> @crazydev901 this is a duplicate of: #6717 where we don't auto-fix the relations yet.
> 
> The workaround now is to manually fill in the relation. Something like:
> 
> ```diff
> model User {
>   id             String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
>   createdAt      DateTime @default(now())
>   updatedAt      DateTime @updatedAt
>   ...
>   favProjects    Project[]  @relation(fields: [favProjectsIds])// Worker's favorite projects
>   favProjectsIds String[] @db.Array(ObjectId)
>   ...
> }
> 
> model Project {
>   id                String     @id @default(dbgenerated()) @map("_id") @db.ObjectId
>   createdAt         DateTime   @default(now())
>   updatedAt         DateTime   @updatedAt
>   ...
> +  userIds String[] @db.Array(ObjectId)
> +  users   User[]   @relation(fields: [userIds])
> }
> ```
> 
> FYI, the linked issue won't auto-fix M:N, but rather it will auto-fix the relation to be 1:N, then you can tweak it to be M:N. This is how we do it with SQL database support right now.

Thanks
I want to reference itself inside the same model. For example, a User model have specific fields that contain sibling users.
```model User {
...
favTalents User[]
...
}```
Any idea on this?

**Comment by matthewmueller** [comment]
Should be the same process

```diff
model User {
  id             String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
 +  favTalentIds String[] @db.Array(ObjectId)
+  favTalents   User[]   @relation(fields: [favTalentIds])  ...
}
```

Does that work for you?

**Comment by crazydev901** [comment]
> Should be the same process
> 
> ```diff
> model User {
>   id             String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
> +  favTalentIds String[] @db.Array(ObjectId)
> +  favTalents   User[]   @relation(fields: [favTalentIds]) 
> }
> ```
> 
> Does that work for you?
https://stackoverflow.com/questions/65162657/one-to-many-self-relation-in-prisma-schema - this worked for me, but I don't know how it is  ;)

**Comment by BoraALAP** [comment]
I have the similar issue: 

`
model User {
  id                    String     @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt             DateTime   @default(now())
  updatedAt        DateTime   @updatedAt
  email                 String     @unique
  firstName             String
...
  rsvpedSessions        Session[]  @relation("Rsvped", fields: [rsvpedSessionId])
  rsvpedSessionId       String[]   @db.Array(ObjectId)
  notRespondedSessions  Session[]  @relation("notResponded", fields: [notRespondedSessionId])
  notRespondedSessionId String[]   @db.Array(ObjectId)
  declinedSessions      Session[]  @relation("Declined", fields: [declinedSessionId])
  declinedSessionId     String[]   @db.Array(ObjectId)


model Session {
  id                 String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt          DateTime @default(now())
  updatedAt    DateTime @updatedAt
  title              String
  ...
  rsvpedUsers        User[]   @relation("Rsvped", fields: [rsvpedUserId])
  rsvpedUserId       String[] @db.Array(ObjectId)
  notRespondedUsers  User[]   @relation("notResponded", fields: [notRespondedUserId])
  notRespondedUserId String[] @db.Array(ObjectId)
  declinedUsers      User[]   @relation("Declined", fields: [declinedUserId])
  declinedUserId     String[] @db.Array(ObjectId)
`

when I create the session by adding the user to the notResponded. I can see the user in not responded array but, on  User I can't get the session under notRespondedSessions. It just links user to the session but it doesn't link session to the user. 

I create the session with 
`
return await prisma.session.create({
        data: {
          ...args,
          notRespondedUserId: args.userID,
        },
      });
`

do you have any idea what might be the reason?
