### ISSUE TITLE
Provider flag for `init`

### ISSUE THREAD

**Issue by eternalmoon1234** [prisma/prisma#7126]
## Problem

When I'm using Prisma and run the `init` command, it always defaults to using PostgreSQL. It would be nice if you could choose your provider through the init command. 

## Suggested solution

Perhaps on the `prisma init` command there could be a flag such as `--postgresql` or `--sqlite`, or `--provider-postgresql`. This would just configure the Prisma project for that provider on initialization.

## Additional context

This might already exist, and I'm not aware of it, or it might have been implemented some other way. Thanks!

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/1854

**Comment by eternalmoon1234** [comment]
Thanks, should I close this now?

**Comment by janpio** [comment]
I closed the other ones, as you actually had a concrete suggestion.

From the other issue:

Small note: you can use this cli for reproductions: https://github.com/timsuchanek/auto

It basically does the same thing described but also install deps and setup a reproduction script.

_Originally posted by @pantharshit00 in https://github.com/prisma/prisma/issues/1854#issuecomment-824942541_

**Comment by eternalmoon1234** [comment]
Thanks

**Comment by janpio** [comment]
In the last 2 years this actually got implemened: `prisma init --datasource-provider sqlite` changes the `provider` and the default value of `DATABASE_URL`.
