### ISSUE TITLE
Preview feature feedback: Filtering `Json` fields (`filterJson`)

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#7135]
Please share your feedback about the `filterJson` functionality released in [v2.23.0](https://github.com/prisma/prisma/releases/tag/2.23.0) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo.
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma-client`](https://prisma.slack.com/archives/CCWDULGUW) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by matthewmueller** [comment]
**For Postgres users:** you should always use `path: string[]` syntax. Right now we support `path: string`, but this will be disabled in the future to avoid the expectation that Postgres supports dot notation.

Postgres doesn't support:

```
{ path: "key.inner.most"}
```

Instead it supports:

```
{ path: ["key", "inner", "most"]}
```

Issue: https://github.com/prisma/prisma/issues/7136

**For MySQL Users:** MySQL does support dot notation

```
{ 
  path: "$.key.inner.most" 
}
```

For maximum query flexibility, we pass the query paths directly into the database engines. The tradeoff is that the syntaxes are different.

**Comment by andrewtran1995** [comment]
Loving this feature so far! ❤️  The Prisma client documentation specifies that [filtering on an object key inside of an array](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-object-key-value-inside-array) is only currently supported for the MySQL database connector.

Are there plans to expand this to other connectors as well, particularly PostgreSQL?

**Comment by wyozi** [comment]
Great feature. Supporting JSON object containment check (`@>` in Postgres) would allow me to stop relying on custom SQL for search query filtering. My usecase is querying rows where metadata (a shallow JSONB object with arbitrary keys and non-object values) contains specific subset of key-value pairs.

**Comment by janpio** [comment]
(Make sure there is an issue for this @wyozi - sounds like a good feature request)

**Comment by tre-dev** [comment]
Similar to @andrewtran1995, it would be great if I'd be able to filter JSON fields within a JSON[] using PostgreSQL.

**Comment by Songkeys** [comment]
Hi. I saw this issue was closed because filterJson is not in preview anymore. But has the feature request "case insensitivity" been taken into consideration?

**Comment by cprieto** [comment]
Sorry @Songkeys, this issue must be opened for feedback in the feature preview and I closed it by accident, I think it will be better (for tracking) if once the release is out a new ticket is created with the case insensitivity in JSON filtering as a feature (it is easier for us to plan and track instead of having just a huge list of comments in a single ticket). Would that work for you?

**Comment by Songkeys** [comment]
@cprieto Yes! Definitely sounds great. Thank you so much for the work. 👍🏻

**Comment by semurgx** [comment]
It would be great, if Prisma would support Postgres's @> operator for JSON filtering.

**Comment by muhammad-Osman** [comment]
"questions_and_answers": [
            {
                "assessment_id": "3440fca4-4652-4d50-a786-afb824ac9a73",
                "question_id": "048ee0b7-2dd0-45ec-b7ba-308e5e87e0f7",
                "answer": {
                    "ans": "yes"
                },
                "label": "QR1"
            },
     ]

i want to filter JSON on the base of label but once i give path under where condition it is giving me error

**Comment by ajhollowayvrm** [comment]
Another bump on this for support Postgres JSON filtering and even other JSONB operators like JSONB_Insert.

**Comment by rohanrajpal** [comment]
> Similar to @andrewtran1995, it would be great if I'd be able to filter JSON fields within a JSON[] using PostgreSQL.

I was also figuring out a way to do this, were you able to figure it out or is it yet to be implemented?

**Comment by janpio** [comment]
Filtering on a `Json` field has been GA for a while now since 4.0.0, Jun 28, 2022: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filter-on-a-json-field

If you still have some cases that are not covered, please open a new issue. Thank you.
