### ISSUE TITLE
Revisit prisma.$queryRaw("...") vs. prisma.$queryRaw template literal

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#7142]
## Problem

Right now it's really easy to write a raw query that's susceptible to SQL injections

```js
// Raw query. Susceptible to SQL injections! 
prisma.$queryRaw(`SELECT \* FROM User WHERE email = ${email}`);

// Prepared query. Not susceptible to SQL injections.
prisma.$queryRaw`SELECT \* FROM User WHERE email = ${email}`;
```

The difference is in the `(` and `)`. This is far too subtle and there's no warning about which is which.

## Suggested solution

- [x] Investigate: Can we differentiate between `prisma.$queryRaw("...")` and the prisma.$queryRaw template literal?

If so, 

- [x] Rename `prisma.$queryRaw("...")` to something else. Perhaps `$queryDangerouslyRaw`.
    
    I think there are since there are places where you can't use a prepared statement (e.g. CREATE TABLE "${table}"). If so, I don't think we want to disallow the capability entirely.

- [ ] Consider writing a codemod for `npx @prisma/codemods` to rename function calls (not template literals) to the new method

If not,

- Consider other alternatives for clearly separating these two behaviors

## Other Ideas

- Maybe it's possible for our VS Code extension to detect it and return a warning.
- Or maybe it's possible at runtime to detect that it's used the wrong way and throw an error?

**Comment by pantharshit00** [comment]
Related: https://github.com/prisma/prisma/issues/7095

**Comment by matthewmueller** [comment]
_Internal Note:_ we consider this breaking change before the next major release.

**Comment by matthewmueller** [comment]
The design of this change is the following:

### Narrowed `$queryRaw` **(breaking change)**

- `$queryRaw` now only supports a template literal. 
- This is always a parameterized query and therefore not susceptible to SQL injections. 
- The signature is prisma.$queryRaw\`query\`. 
- For example, prisma.$queryRaw\`select * from users where email = ${email}\`

### Added `$queryRawUnsafe`

- `$queryRawUnsafe` is new function that can be a string or template string. 
- The signature is prisma.$queryRawUnsafe(query, args...). 
- This allows you to pass a raw template string in. For example, `prisma.$queryRawUnsafe("create table ${table}"). `
- You could still have a parameterized query. For example, `prisma.$queryRawUnsafe("select * from users where email = $1", "alice@prisma.io")`. This is mostly to make the upgrade path easier

### `$queryRaw` to `$queryRawUnsafe` codemod

We plan to add a codemod to https://github.com/prisma/codemods that will turn all `$queryRaw` functions into `$queryRawUnsafe` functions. It will ignore $queryRaw tagged templates, since those work as is.

**Comment by Sytten** [comment]
Discussed it with @millsp on slack, but basically I got into the code of a pretty large customer that uses prisma  and I found a lot of sql injections due to improper use of prisma raw queries. So I support that 100%.

Basically I want the following to fail:
```typescript
let query = `SELECT * FROM table`
if (id) {
  query += `WHERE id = ${id}`
}
prisma.$queryRaw(query)
```

But this should still work:
```typescript
let query = sql`SELECT * FROM table`
if (id) {
  query = sql`${query} WHERE id = ${id}`
}
prisma.$queryRaw(query)

**Comment by matthewmueller** [comment]
Closing since we've learned this will be possible.

Remaining tasks are tracked in: https://github.com/prisma/prisma/issues/8628
