### ISSUE TITLE
ts-node-dev hangs when creating PrismaClient

### ISSUE THREAD

**Issue by mgummelt** [prisma/prisma#7148]
### Bug description

When I construct a `PrismaClient` at the top level of my express server:

```
const prisma = new PrismaClient();
```

My server no longer restarts running under `ts-node-dev` when source files change.  And if I try to manually `kill` the process via a `SIGTERM`, the process hangs.

I've confirmed the issue is caused by some interaction of `ts-node-dev` and `PrismaClient`, because when I run the same server with `ts-node`, I can `kill` the process just fine. 

### How to reproduce

Run a long-running server with a `PrismaClient` under `ts-node-dev`

### Prisma information

N/A

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL, but my DATABASE_URL is empty when observing this bug
- Node.js version: 10.19.0

### Prisma Version

```
Environment variables loaded from .env
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

**Comment by Jolg42** [comment]
Hi!
Could you check the version of `ts-node-dev` / update to latest with `npm i -g ts-node-dev`?

**Comment by mgummelt** [comment]
@Jolg42 

I just upgraded from 1.0.0-pre.43 to 1.1.6, but I'm still experiencing the same problem.

**Comment by Sytten** [comment]
ts-node-dev is pretty unreliable/bad in general, there used to have a lot of concurrency issues causing trouble but most of them have been fixed. I do experience issues sometime when multiple processes are running with prisma. Can you try to add the `--exit-child` flag to see if it helps? If that doesn't help, maybe try to enable the `napi` feature flag so prisma doesn't create a children process. I found that sometimes ts-node-dev in combination with your code (if you use an apollo server they automatically catch the SIGTERM) can lead to zombie processes, causing issues on reload.

**Comment by mgummelt** [comment]
@Sytten 

Adding --exit-child does in fact work.  Thank you!

I don't understand why it works, unless prisma is somehow blocking SIGTERM, and this option overrides that.

I'm happy to switch to a more reliable solution than `ts-node-dev` if you have any suggestions.  By accounts I've read, `nodemon` is too slow, since it recompiles the entire typescript project.

**Comment by mgummelt** [comment]
After some investigation, it looks like both prisma and ts-node-dev handle SIGTERM, and only exit if there are no other listeners.  So both seem to be yielding to the other, and the process never exits.

**Comment by Sytten** [comment]
Nice investigation that seems right.

**Comment by ryands17** [comment]
@mgummelt 👋 

One option that could be checked out is [ts-eager](https://github.com/mhart/ts-eager). I have tried it with nodemon as well like [this](https://github.com/ryands17/fastify-prisma/blob/main/nodemon.json).

**Comment by Jolg42** [comment]
Closing, since this issue is resolved by using `ts-node --exit-child` 😃

**Comment by janpio** [comment]
Is the SIGTERM behavior of Prisma expected or at fault here for requiring that?

**Comment by Jolg42** [comment]
Prisma Client does listen on 
```      
	  hookProcess('beforeExit')
      hookProcess('exit')
      hookProcess('SIGINT', true)
      hookProcess('SIGUSR1', true)
      hookProcess('SIGUSR2', true)
      hookProcess('SIGTERM', true)
```

Because we found out that we needed to hook into these events to "kill" the Prisma Query Engine properly. Without this users can run into cases where the engine is not "killed", which can eat a lot of RAM if you start/stop the client.

**Comment by Sytten** [comment]
I also know that apollo server changed their sigterm handler per my request, https://github.com/apollographql/apollo-server/issues/4931. That might affect some users since the new implementation doesn't yield to other handlers. That would explain why my worker needs the flag to properly shutdown but not my api.

**Comment by nghiepit** [comment]
Although `--exit-child` solved the problem. But I think it's only a temporary solution and this issue should be reopened.

**Comment by pantharshit00** [comment]
@nghiepit I disagree, that is how it is implemented in `ts-node-dev` and I don't think we can change anything to change that here. 

Alternatively, try using the Node-API preview which doesn't spawn a child process preventing this altogether: https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#enable-the-node-api-n-api-preview

**Comment by craigcosmo** [comment]
so we just let it hang like that? man gotta tackle it.
