### ISSUE TITLE
filterJson string filtering throws error "field does not exist on enclosing type"

### ISSUE THREAD

**Issue by wyrd-code** [prisma/prisma#7170]
Trying to use the new json filters, but they don't seem to work.

My schema:
```prisma
model Article {
  id           String   @id @default(cuid())
  content      Json
}
```

Using a query like

```js
await client.article.findFirst({
          where: {
            content: {
               path: [ 'slug' ],
               string_contains: 'a-blog-post' 
            },
          },
        })
```

Throws an error:

```js
Invalid `prisma.article.findFirst()` invocation:
  Failed to validate the query: `Field does not exist on enclosing type.` at `Query.findFirstArticle.where.ArticleWhereInput.content.JsonNullableFilter.path` 
 Error: 
Invalid `prisma.article.findFirst()` invocation:


  Failed to validate the query: `Field does not exist on enclosing type.` at `Query.findFirstArticle.where.ArticleWhereInput.content.JsonNullableFilter.path`
    at cb (/data/wyrd/social/node_modules/@prisma/client/runtime/index.js:35101:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Service.handler (/data/wyrd/social/wyrd/resource/services/resource.service.ts:240:22)
    at Service.callAction (/data/wyrd/social/node_modules/moleculer-web/src/index.js:588:16)
    at /data/wyrd/social/node_modules/moleculer-web/src/index.js:420:22 
Data:
```

I tried using `equals` instead of `string_contains`, tried using a simple string path (instead of an array), but it throws the same error.

I am using Postgres 12.6 on Ubuntu.

**Comment by pantharshit00** [comment]
Hey @wyrd-code 

I am unable to reproduce this:
![image](https://user-images.githubusercontent.com/22195362/118978438-f2847f00-b994-11eb-8ed8-c5852fa89b7f.png)


Can you please make sure you enables the `filterJson` preview feature flag and ran `prisma generate` after enabling that? 
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["filterJson"]
}
```


Also, please make sure you are using the latest 2.23 release as that contains this new feature. 


If you can still reproduce this, please share a minimal reproduction inside of a git repository.

**Comment by wyrd-code** [comment]
I will try to add a reproduction once I get some sleep.

**Comment by wyrd-code** [comment]
Hi, just to report I am unable to reproduce now myself. At the time I had some strange issues with Postgres, and since reinstalling this seems to work ok. I will close the ticket. Thanks for your suggestion (I had the feature enabled already, it was something low level, probably to do with postgres). Cheers
