### ISSUE TITLE
Error permalinks 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#718]
Content links that back each error code from the errors spec: https://github.com/prisma/specs/tree/master/errors

The error message will contain a clickable link to each error. 

To discuss: Initially, this can be `pris.ly` links backed by the spec itself.

**Comment by nikolasburk** [comment]
Update: Waiting for implementation.

**Comment by janpio** [comment]
Internal Note: Dropping because docs writing has priority.

**Comment by janpio** [comment]
Errors and error codes now have permanent links at https://www.prisma.io/docs/reference/api-reference/error-reference - but they really just show the same text as the actual error message right now, no additional information.
