### ISSUE TITLE
Shadow vs. main database check does not consider the port

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7216]
```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}

```

and
```
DATABASE_URL="mysql://root:@127.0.0.1:3306/fk-test"
SHADOW_DATABASE_URL="mysql://root:root@127.0.0.1:3316/fk-test"
```

leads to

```
Error: Error: The shadow database you configured appears to be the same as as the main database. Please specify another shadow database.
```

This is wrong, as 3306 is my remote Planetscale DB via proxy, and 3316 is my local MySQL 8.

Seems the check for this is missing to consider the port:

https://github.com/prisma/prisma-engines/blob/340b485a62f6fd071bcd47a33a5263db491df86f/migration-engine/connectors/sql-migration-connector/src/flavour/mysql.rs#L77-L79
https://github.com/prisma/prisma-engines/blob/fd7b031cb9e9ac89b2d15c29f39f704f672da00b/migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs#L48-L50
https://github.com/prisma/prisma-engines/blob/c1113c6285960eb54d71be971738abe600727268/migration-engine/connectors/sql-migration-connector/src/flavour/mssql.rs#L61-L63

PS: Can be worked around by using `127.0.0.1` and `localhost` as hostnames :)

**Comment by pantharshit00** [comment]
I can confirm this.
