### ISSUE TITLE
Nova editor extension for syntax highlighting and auto-formatting

### ISSUE THREAD

**Issue by Hazeman28** [prisma/prisma#7223]
## Problem

Currently there is no extension for the [Nova editor](https://nova.app) that supports  syntax highlighting and auto-formatting for the Prisma Schema Language.

## Suggested solution

Create an extension that supports these features.

**Comment by janpio** [comment]
https://nova.app/ I assume?

**Comment by Hazeman28** [comment]
> https://nova.app/ I assume?

Yes, sir. Update description too 😄

**Comment by janpio** [comment]
- Extensions are listed at https://extensions.panic.com/ and can be published from there as well. 
- Documentation is at https://docs.nova.app/extensions/, https://github.com/apexskier/nova-typescript might be close to what Prisma needs.
- Prismas language tools (and VSCode extension) live at https://github.com/prisma/language-tools

**Comment by pantharshit00** [comment]
@Hazeman28 

Do you have any idea on what syntax format it uses? Like TextMate grammer or treesitter?

**Comment by pantharshit00** [comment]
Ok, it uses something else: https://docs.nova.app/syntax-reference/syntaxes/

**Comment by Hazeman28** [comment]
Since the extension has been added to Nova's extensions library, I'm resolving this.

**Comment by janpio** [comment]
Nice:
https://extensions.panic.com/extensions/robb-j/robb-j.Prisma/
https://github.com/robb-j/nova-prisma
