### ISSUE TITLE
MySQL Poor performance (when not using `$queryRaw`)

### ISSUE THREAD

**Issue by DakotaLarson** [prisma/prisma#7230]
### Bug description

This is a weird one.  I recently migrated from MariaDB 10 to MySQL 8. When I query the DB using the helper functions (i.e. `Model.findMany`), the queries take a long time and the mysql process on my machine takes at least a minute to process the query. Disk usage is also high for the mysql process.  When I use `$queryRaw`, the results are returned quickly as expected.

### How to reproduce

If I run:
```
debugger;
// this is fast.
await DB.prisma.$queryRaw("SELECT `cryptick`.`Trade`.`marketId`, `cryptick`.`Trade`.`id`, `cryptick`.`Trade`.`amount`, `cryptick`.`Trade`.`price`, `cryptick`.`Trade`.`buyerMaker`, `cryptick`.`Trade`.`externalId`, `cryptick`.`Trade`.`time` FROM `cryptick`.`Trade` WHERE `cryptick`.`Trade`.`marketId` = 7 ORDER BY `cryptick`.`Trade`.`id` DESC LIMIT 1 OFFSET 0");
debugger;
// This is slow.
await DB.prisma.trade.findMany({
  where: {
    marketId: 7
  },
  orderBy: {
    id: "desc",
  },
  take: 1,
});
debugger;
```

I found the generated query for the second call and copied that into `$queryRaw` using `SHOW FULL processlist;`.

The first query will take first will take under a second and the second will take more than a minute. 

Here is the data model for this table: 
```
model Trade {
  marketId   Int      @db.SmallInt
  id         Int
  amount     Float    @db.Float
  price      Float    @db.Float
  buyerMaker Boolean
  externalId String   @db.VarChar(255)
  time       DateTime @db.Timestamp(6)
  Market     Market   @relation(fields: [marketId], references: [id])

  @@id([marketId, id])
}
```

Which currently has 27 GB of data (millions of records). Also if I use `prisma.trade.findMany`, I have the same issue, even though the generated query found by `SHOW FULL processlist;` runs quickly on its own.

### Expected behavior

I would expect this query to take the same amount of time.

### Prisma information

See above schema

### Environment & setup

- OS: Windows 10
- Database: MySQL 8
- Node.js version: 14.15

### Prisma Version

```
v2.23.0 
Also experienced this with 2.22.x, but haven't downgraded further.
```

Not sure how this can happen since I always thought the query was simply sent to the DB where all optimizations are generated by MySQL. The same query generated by 2 different functions has very different performance results.

I have uninstalled built files and node_modules repeatedly. Any help is appreciated.

**Comment by janpio** [comment]
Uh indeed a weird one. But interesting. 

Might be that Prisma Client is running some _additional_ queries? Confirm with https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging which gives you the Prisma view vs. the database view.

Is the data of the `$queryRaw` already typed the exact same way as the `findMany`?

We will try to reproduce this of course.

**Comment by DakotaLarson** [comment]
I didn't see any additional queries. It just seems to lag then outputs the log of the select query.

I have thought more about this issue and it may be related to #7232. The delete query, at least on mysql 8, was having poor performance. Perhaps the table is locked which would result in the wait.

**Comment by janpio** [comment]
Any idea how we could create similar ~27GB of data for that model you shared? Without that a reproduction will be very hard I guess.

**Comment by henriqueantonio** [comment]
This is happening with me as well. At the time i'm rewriting all my queries with raw SQL.
For a simple database with only 10 rows, a findMany with 2 relations it's taking about 1.3 seconds.

**Comment by janpio** [comment]
Ping @DakotaLarson. I realize it has been some time, but could you still provide additional information here? Otherwise we will need to close this as just do not have enough information about how to reproduce this with adequate effort. Thank you.
