### ISSUE TITLE
Ability for a generator to log after its default success message

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#7270]
## Problem

https://github.com/prisma/nexus-prisma/issues/46#issuecomment-843268529

Instead of this:

```
You can now start using Nexus Prisma in your code. Reference: https://pris.ly/d/nexus-prisma

✔ Generated Prisma Client (2.22.0) to ./node_modules/@prisma/client in 122ms

✔ Generated Nexus Prisma to ./node_modules/nexus-prisma/dist/runtime in 3.26s
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```

It should be:

```
✔ Generated Prisma Client (2.22.0) to ./node_modules/@prisma/client in 122ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

✔ Generated Nexus Prisma to ./node_modules/nexus-prisma/dist/runtime in 3.26s
You can now start using Nexus Prisma in your code. Reference: https://pris.ly/d/nexus-prisma
```

## Suggested solution

When a generator logs, put the info after the success message. Or better yet maybe offer a log API that is given to generators that they use instead of just raw `process.stdout`. then Prisma generator system gets all the input and has high degree of control on how to manage this.

Also a generator logger would ensure all generators use the same log style. For example the Prisma logger given to generators could include things like `log.error` `log.success` etc. so that these semantic things are all sharing the same DX for the community across generators.

Anyways, right now I just want the right log order! :D

**Comment by jasonkuhrt** [comment]
CC @Jolg42 we can continue the discussion here

**Comment by janpio** [comment]
I am pretty sure we have an issue somewhere already that the `You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client` output is in the wrong place and should always happen after the `✔ Generated Prisma Client ...` line.
