### ISSUE TITLE
Vercel: Schema only change does not invalidate build cache

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7291]
Switching `provider` from `postgresql` to `mysql` does not cause Prisma Client to be regenerated.

Deploy project with this first, observe error:
```
datasource db {
  provider = "postgresql"
  url      = "mysql://root:@127.0.0.1:3306/e2e-tests"
}
```

Switch to this and keep seeing the _same_ error:
```
datasource db {
  provider = "mysql"
  url      = "mysql://root:@127.0.0.1:3306/e2e-tests"
}
```

**Comment by pantharshit00** [comment]
I can reproduce this. Here is the reproduction deployment which is our vercel account: https://issue-7291-drigger-prisma.vercel.app

**Comment by janpio** [comment]
Users are obviously also experiencing this problem: https://github.com/prisma/prisma/discussions/8312#discussion-3463379

**Comment by millsp** [comment]
Related https://github.com/prisma/docs/issues/3590
