### ISSUE TITLE
Support databases without foreign keys

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7293]
## Problem

There are databases that do not use foreign keys, for example [PlanetScale](https://github.com/prisma/prisma/issues/7292) that disallows them to be able to support Non Blocking Schema changes, MySQL MyISAM that just is to old and works well without, and many user databases where a choice was made not to use foreign keys as a concept for various reasons (Rails did not do a great job with them for quite some time and worked fine without, some people prefer to handle the referential integrity and actions manually in their app, for example to improve performance).

Right now Prisma does not work well with these database: Prisma Migrate will try to create foreign keys for relations by default, and Introspection will only introspect relations based on foreign keys. You can theoretically add relations to your Prisma schema without the backing foreign keys as long as the correct fields are present, but any Re-Introspection would remove these manually added relations from the schema file again.

## Suggested solution

Introduce a configuration that allows Prisma to not user foreign keys. Prisma Migrate should not create them, Introspection should not drop relations if there are no foreign keys. Prisma Client should work the same as it does when using foreign keys.

## Alternatives

- Use another ORM instead of Prisma 
- Try to manually manage the relations in the schema file as described above

## Additional context

Referential integrity and actions are closely related to this topic, but separate.

**Comment by pimeys** [comment]
Migrations part done in here: https://github.com/prisma/prisma-engines/pull/2212
