### ISSUE TITLE
2.23.0 can not recognize `binaryTargets: env("..")` inside `generator client` section

### ISSUE THREAD

**Issue by hehex9** [prisma/prisma#7295]
### Bug description

`prisma [format|generate]` is not working with `env("BINARY_TARGETS")` in latest prisma (2.23.0) 😢

**ERROR** 👇
```
Error: Schema Parsing P1012

Get config
error: Expected a String value, but received functional value "env".
  -->  schema.prisma:8
   |
 7 |   provider      = "prisma-client-js"
 8 |   binaryTargets = env("BINARY_TARGETS")
   |
```

@janpio 

### How to reproduce

just run `prisma format` or `prisma generate` with schema below

### Expected behavior

should works

### Prisma information

```prisma
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = env("BINARY_TARGETS")
}

model User {
  id Int @id
}
```

### Environment & setup

- OS: Mac OS
- Database: all
- Node.js version: v14.16.0

### Prisma Version

```
prisma               : 2.23.0
@prisma/client       : 2.23.0
Current platform     : darwin
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
```
--- 
parent https://github.com/prisma/prisma/issues/6830

**Comment by pantharshit00** [comment]
I can confirm this regression. This broke from `2.22` to `2.23`. 

Validator output in 2.22:
![image](https://user-images.githubusercontent.com/22195362/119772983-a29a4080-bedd-11eb-96a1-2c27dfacaad5.png)

(Nothing means schema is valid)

Validator output in 2.23:
![image](https://user-images.githubusercontent.com/22195362/119772999-acbc3f00-bedd-11eb-882c-379a64f52e1b.png)

**Comment by janpio** [comment]
Thanks for reporting this @hehex9 - we will fix this. Until then, you probably want to stay on 2.22.

**Comment by tomhoule** [comment]
I just opened a PR to address this (https://github.com/prisma/prisma-engines/pull/1965), thanks for reporting the issue. This will cause a small breaking change in the shape of the DMMF, so I will try to get this merged before tomorrow's release, but it needs some coordination.

**Comment by janpio** [comment]
Will only happen after the release, as the change was too big to just get through the pipeline.
We will hopefully have a `dev` version early with 2.25.0 though so you can test this @hehex9.

**Comment by hehex9** [comment]
no problem 👍 , thanks for working on this, will definitely try it out then
