### ISSUE TITLE
Slow queries with Prisma + Nexus + GraphQL on Vercel due to lambda cold starts

### ISSUE THREAD

**Issue by styxlab** [prisma/prisma#7303]
### Bug description

My Next.js app is deployed to Vercel and uses a lambda route for a GraphQL server (apollo-server-micro) that is configured with Prisma + Nexus. Lambda cold starts on Vercel lead to slow queries that take **approximately 7 seconds**.

I have reproduced the issue on simple example that shows cold start times of **approximately 2,5 seconds**. I have not managed to find the influencing factors, but Prisma + Nexus (and the resulting function size) seems to play a role. Here is the deploy output for the serverless functions:

```

00:04:49.070 | Serverless function size info
-- | --
00:04:49.071 | Serverless Function's page: api/graphql.js
00:04:49.074 | Large Dependencies                          Uncompressed size  Compressed size
00:04:49.074 | node_modules/.prisma/client                             47 MB          16.4 MB
00:04:49.074 | node_modules/prettier/parser-typescript.js            3.18 MB           817 kB
00:04:49.074 | node_modules/prettier/index.js                        1.72 MB           396 kB
00:04:49.074 | node_modules/prettier/parser-flow.js                  3.11 MB           310 kB
00:04:49.074 | node_modules/@prisma/client                           1.17 MB           243 kB
00:04:49.074 | node_modules/busboy/deps                               618 kB           196 kB
00:04:49.075 | node_modules/micro/node_modules                        360 kB           190 kB
00:04:49.075 | node_modules/encoding/node_modules                     329 kB           179 kB
00:04:49.075 | node_modules/lodash/lodash.js                          544 kB          96.4 kB
00:04:49.075 | All dependencies                                      63.5 MB          20.2 MB
00:04:49.163 | Created all serverless functions in: 43.168s
```

I see the cold starts after approx. **10 minutes inactivity**, but that could vary.

I put some simple timestamps into the app, both on the client and the server. From those timestamps, you can see that in the case of a cold start the total query time is governed by the waiting time between query initiation and endpoint function invocation (`start request` - `before fetching`). Only Vercel would be able to debug further into what happens exactly within this time-span.

Some screenshots from the example:
![image](https://user-images.githubusercontent.com/19638263/119804282-7e8c2e80-bee0-11eb-8104-77a6eaf468ee.png)
![image](https://user-images.githubusercontent.com/19638263/119804501-b09d9080-bee0-11eb-9d6d-44c9766c11b8.png)
![image](https://user-images.githubusercontent.com/19638263/119804567-c0b57000-bee0-11eb-9c81-d5ecb26cb7bb.png)
![image](https://user-images.githubusercontent.com/19638263/119804664-da56b780-bee0-11eb-8c0a-91dfc651e03b.png)
![image](https://user-images.githubusercontent.com/19638263/119804781-f4909580-bee0-11eb-89f0-b01368fa11af.png)

### How to reproduce

1. Clone project [lambda-cold-start](https://github.com/styxlab/lambda-cold-start) and deploy to Vercel
2. You can inspect it right away under https://lambda-cold-start.vercel.app (but better deploy yourself, so you can control the inactivity).

### Expected behavior

I know that cold starts cannot be fully eliminated, but cold start times of 2 - 7 seconds are a problem for me. I can accept cold start time of roughly 1 second. Thus, I expect the follwoing help from this issue:

1. Understand the role Prisma + Nexus plays in building up long cold starts
2. Understand the influencing factors (hopefully something can improved)
3. Based on the analysis, maybe some ideas for viable remedies (warm-up strategies).

I will also open an issue @Vercel, so hopefully their infra team can also give some insight.

### Prisma information

You can find `package.json` and prisma schema on the linked repo. Note that the example takes out any calls to the database (all prisma queries are taken out the the GraphQL resolvers). This is to show that we are indeed dealing with a cold start issue and not database latency.

### Environment & setup

- Issue only exists when deployed to Vercel
- Also tried to deploy to Netlify but got build errors I was not able to fix (any hints welcome).

### Prisma Version

```
prisma               : 2.23.0
@prisma/client       : 2.23.0
```

**Comment by styxlab** [comment]
also opened issue https://github.com/vercel/vercel/issues/6292

**Comment by janpio** [comment]
What is the equivalent time without the Prisma dependency?
What is the equivalent time without Prisma and Nexus (and Nexus Plugin Prisma) so something else returned?

A note: Your dependencies include Nexus and @nexus/schema which is in theory mutually exclusive, as it is the same library but different versions.

**Comment by janpio** [comment]
Clone of the repo with no changes:
![image](https://user-images.githubusercontent.com/183673/120053457-80fa9f80-c02a-11eb-822c-fc6125ab2a60.png)

With `prisma`, `@prisma/client` and `nexus-plugin-prisma` dependency removed:
![image](https://user-images.githubusercontent.com/183673/120052732-fa908e80-c026-11eb-895d-d4f8b7aca517.png)

So looks to me that Prisma + Nexus-Plugin-Prisma adds 0.4 seconds cold start time to the project. That is not great, but sounds pretty reasonable to me right now.

---

Or from another angle:

This is a plain `create-next-app` project deployed to Vercel:
![image](https://user-images.githubusercontent.com/183673/120053675-e4d19800-c02b-11eb-9f0c-e8a097c16554.png)

And this is the same project with Prisma and Prisma Client added as dependencies:
![image](https://user-images.githubusercontent.com/183673/120053695-0468c080-c02c-11eb-839f-2e46ee0fe4b7.png)

Again roughly 0.4 seconds difference.

**Comment by styxlab** [comment]
@janpio Thanks so much for looking into the issue.

I will make some more tests with adding/removing dependencies along the same lines as you did. If only 0.4 seconds can be attributed to Prisma + Nexus, then this would be acceptable. What still doesn't add up for me: 

- Your tests of my reproduction example only show 1.7 sec cold start times vs 2.5 secs which I get consistently: This is already a 0.8 secs difference

- I haven't quite managed to replicate my prod example where I see 7 secs cold starts, so I expect Prisma + Nexus footprint to be larger in real world examples, but I have to show that to you, I know.

Thanks for pointing out Nexus and @nexus/schema deps, I will look into that too.

**Comment by janpio** [comment]
> * Your tests of my reproduction example only show 1.7 sec cold start times vs 2.5 secs which I get consistently: This is already a 0.8 secs difference

What you are measuring is not really cold start time though, it is cold start + invocation (function execution) + network in both directions, or is it?

> * I haven't quite managed to replicate my prod example where I see 7 secs cold starts, so I expect Prisma + Nexus footprint to be larger in real world examples, but I have to show that to you, I know.

If you connect to the database and actually run a query, the times can fluctuate a lot depending on your databases's mood and network conditions. The less close it is to your Vercel function location, the more impacted it might be. If you run multiple queries, that of course multiplicates and becomes worse. But that really is normal and a given unfortunately, still something to look out for an optimize if possible.

**Comment by styxlab** [comment]
Regarding the timings. You are correct, that "cold start" time the example displays is cold start + invocation (function execution) + network in both directions.

I have taken a time series of "warm" times (=invocation (function execution) + network in both directions.) and the mean is 0.22 secs from my location. Thus, it doesn't change the fact that I see ~ 2 secs that I think are due to "cold starts". I am aware that those 2 secs might come from something that is not strictly AWS lambda cold start times, there could be other influencing factors in the Vercel infra.

**Comment by janpio** [comment]
If you have the time, you can try Netlify and AWS Lambda directly. They run on the same infrastructure (AWS Lambda) but package it slightly different (In AWS Lambda plain you can get much better numbers on everything). It is an interesting problem to investigate, which is also why I created https://github.com/prisma/prisma/issues/7336 - we do not know _enough_ about this topic yet and should get a much better natural feeling for what is going on and why.

**Comment by styxlab** [comment]
Here are some additional findings:

1. The initially reported 7 secs cold-startup were caused by functions that were calling other endpoints that also experienced cold-start delays so the times accumulated.

2. Initially I was measuring total round-trip times which included the network delays from my location. As the warm function times are around 500ms, this can be substracted to get the time that should be attributed to the cold starts.

3. Finally, I am left with 2 - 3 secs of "cold start" delays on Vercel. When testing only 1 endpoint, cold-start times are around 2 secs, but if I fire many requests at the same time, cold start times increase to approx 3 secs per endpoint.

4. The cold start time are related to the function size (which is mostly determined by the included modules/packages). So the reported times refer to a function size of ~ 20 MB (60 MB uncompressed).

5. I played with "warming" the endpoint by issuing a dummy request every 3 minutes. This helps in 90% of all cases, but interestingly, not always. It helps but does not fully mitigate the problem.

6. Thanks for your note on nexus/schema. I was able to remove that dependency. However, it has no influence on the timings.

7. I tried to deploy to Netlify, but there were some errors caused by prisma deps that I couldn't get rid of easily. Will look into this another time.

**Comment by styxlab** [comment]
One more question: How did you remove the packages and still be able to deploy the function on Vercel? The biggest footprint of the total package size is coming from @prisma/client: If that dependency could be removed/reduced I think it could help.

**Comment by janpio** [comment]
> The biggest footprint of the total package size is coming from node_modules/.prisma/client, of which query-engine-rhel-openssl-1.1.x makes up the biggest chunk. If that dependency could be removed/reduced I think it would have a big effect.

That unfortunately is the binary that Prisma uses to talk to the database - so that is not an option. 

You can use `NEXT_DEBUG_FUNCTION_SIZE=1` on Vercel when deploying a Next project so it tells you the setup of your uploaded serverless functions. Maybe there is more, unexpected stuff in there that you can get rid of.

**Comment by styxlab** [comment]
I published that output in my first post, so you can see that all other packages are ~ 4MB (vs 16 MB prisma), so there is not much that can be improved here. I did not get any feedback from Vercel, but my preliminary conclusion is:

1. Either use a warmup scheduler hitting the needed endpoints approx every 4 minutes with two caveats: (a) it only works in 70 - 80% of my test cases so it's not possible to get entirely rid of cold starts with this method and (b) it leads to unnecessary traffic (and costs).

2. Opting out of serverless, by proxying the "slow" prisma endpoints to a node server, e.g. on a DigitalOcean droplet.

From Prisma side, I don't think you can do much except reducing the binary (which may not be possible) with possible gains on the order of 100ms. Real cold start issue on the order of second(s) remains.

Thanks so much for looking into this - you can close this issue from my side.

**Comment by janpio** [comment]
Can do. We will still try to improve this of course.

One possible aventua: Can you please try the `nApi` preview documented at https://prisma.io/docs/concepts/components/prisma-engines/query-engine#enable-the-n-api-preview with latest version `2.24.1` (Run `prisma generate` after you enable the flag in your schema.)? This should not _really_ influence the startup time, but seeing results with Node API integration which doesn’t spawn the query engine binary would be interesting still.
