### ISSUE TITLE
Issue with Yarn Workspace Monorepo: Query engine binary for current platform could not be found.

### ISSUE THREAD

**Issue by j0hnm4r5** [prisma/prisma#7311]
Hi all —

I have a monorepo set up with a few services, namely an "`api`" service, which contains all of the Prisma stuff, and an "`app`" service, which is a Next.js app that also needs minimal access the Prisma client (via a [`next-auth`](https://next-auth.js.org/adapters/prisma) adapter).

The file structure looks like this:

```
project/
  ├─ package.json
  ├─ node_modules/
  |
  └─ services/
      ├─ app/                             <-- main app
      |   ├─ node_modules/
      |   └─ pages/api/[next-auth].ts     <-- next-auth api function
      |
      └─ api/                             <-- database & api
          ├─ node_modules/
          |   ├─ .prisma/client           <-- generated client
          |   └─ @prisma/client           <-- installed by yarn
          └─ prisma/
              └─ schema.prisma
```

The `package.json` in the root of the project has `nohoist`, to stop the prisma client from getting hoisted to the root node_modules.

When `next-auth` attempts to do its thing, Prisma throws errors that it has an `Invalid prisma.session.findUnique() invocation`, and that the `Query engine binary for current platform "darwin" could not be found`. Following its instructions to add "darwin" to the binaryTargets field in the generator block yields the same results, albeit with a notification that it can tell I added the target, but something still went wrong and that I create an issue here.

It also says that the client looked in these locations:

```
(Prisma Client looked in "/path/to/project/services/app/.next/server/pages/api/auth/query-engine-darwin")

Searched Locations:

  /path/to/project/services/app/.next/server/.prisma/client
  /path/to/project/services/api/node_modules/@prisma/client
  /path/to/project/services/app/.next/server/pages/api
  /path/to/project/services/app/.next/server/pages/api/auth
  /path/to/project/services/app/.next/server/pages/api/auth
  /path/to/project/services/app/.next/server/pages/api/auth
```

**Comment by ryands17** [comment]
@j0hnm4r5 👋 
Do you have a repo where I could test this? In a normal [mono-repo](https://github.com/ryands17/auth-flow) it does find the client.

**Comment by j0hnm4r5** [comment]
@ryands17 here's a reproduction repo that clearly shows what's going on (with instructions): https://github.com/j0hnm4r5/example-prisma-next-auth-monorepo

@millsp is also talking a look at #6899.

**Comment by millsp** [comment]
@j0hnm4r5 have you tried with the latest version?

**Comment by j0hnm4r5** [comment]
@millsp I just tried it again with `prisma@2.24.1` (and `next-auth@3.26.1`) to no avail. It's still the same error.

```
You already added the platforms "native", "darwin" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.
```

Is there anything else I should try?

**Comment by belgattitude** [comment]
@j0hnm4r5 Don't know if it helps but I had to setup a monorepo that isolate a [prisma package](https://github.com/belgattitude/nextjs-monorepo-example/tree/main/packages/db-main-prisma) and here's what I found till now...

- The nohoist road was a dead end with prisma... and anyway removed in yarn 3.0.0.
- Setting the binaryTarget is not helpful in this case, the engine is well there but not where the prisma client expects it, the engine is actually needed in the root node_modules folder 
- So I created a postinstall script that generates the client in the consuming app (https://github.com/belgattitude/nextjs-monorepo-example/blob/ed1fc6b8f294195884a0dc8d3d75d29c916902a8/apps/web-app/package.json#L47)

Somehow it ended up working (local, ci, vercel, docker)... it was based on an older prisma version I'll see if I can get rid off those hacks. But doing so I also have the limitation of having only one prisma schema for the monorepo (which is okay for now).


Link there: https://github.com/belgattitude/nextjs-monorepo-example

**Comment by millsp** [comment]
@j0hnm4r5 I was able to get it to work, I think, by updating to the latest Prisma + Next.js https://github.com/millsp/example-prisma-next-auth-monorepo. The repro is kinda hard to set up, I'd appreciate if you can give me a simpler one.

**Comment by millsp** [comment]
Hey @belgattitude could you please provide us with steps to reproduce this in your current repo?

**Comment by millsp** [comment]
I took the time to take @j0hnm4r5 reproduction and reproduced it. With the latest version of `@prisma/client`, you will get an error letting you know that the schema was not found.

The error that is reported in the repro is the engine not being found, not the schema. This shows that our `findSync` logic was indeed finding a schema, but not the one of the generated client, hence the engine could not be found. Both of these have been recently improved, and you will get better error messages. To fix this, you will need to use `@prisma/nextjs-monorepo-workaround-plugin`.

**Comment by rj-au** [comment]
For anyone looking for an answer in 2025:

Part 1)
Edit all your projects in your monorepo and add to your prisma.schemas:
```prisma
  output          = "./node_modules/.prisma/client"
```

Part 2)
Ensure Yarn installs the correct version in the project directories, if not, use "peerDependency" in package.json - start with the root pcakge.json
