### ISSUE TITLE
Prisma errors when not using the major.minor.patch versioning system

### ISSUE THREAD

**Issue by ghost** [prisma/prisma#7317]
### Bug description

I recently changed my versioning system to use architecture.major.minor.patch instead of the usual major.minor.patch. When I did this and run npx prisma introspect, it errors with "Invalid version" 

![HZfj3D](https://user-images.githubusercontent.com/44342932/119945227-2c402180-bf63-11eb-99e0-92c3fe4b84ac.png)

It does not make any sense that prisma would complain about this. 

### How to reproduce

1. Go to package.json
2. Change "version" to "0.1.0.0" 
3. Run npx prisma introspect 
4. See error "Invalid version" 

### Expected behavior

Prisma should be able to accept a versioning system that is not the usual major.minor.patch, so long as it is a string. 

### Prisma information

Not required

### Environment & setup

- OS: Windows 10
- Database: MySQL 
- Node.js version: 16.1.0

### Prisma Version

```
prisma               : 2.23.0
@prisma/client       : 2.22.1
Current platform     : windows
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
```

**Comment by pantharshit00** [comment]
I can confirm this bug.

**Comment by pantharshit00** [comment]
```
code/reproductions/issue_7317 is 📦 v0.1.0.0 via  v14.17.0
❯ DEBUG=* prisma introspect
  prisma:loadEnv project root found at C:\Users\harshit\code\reproductions\issue_7317\package.json +0ms
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables loaded from ./prisma/.env +1ms
Environment variables loaded from prisma\.env
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Error: Error: Invalid version: "0.1.0.0"
    at Object.fixVersionField (C:\Users\harshit\AppData\Roaming\npm\node_modules\prisma\build\index.js:9584:15)
    at C:\Users\harshit\AppData\Roaming\npm\node_modules\prisma\build\index.js:9900:40
    at Array.forEach (<anonymous>)
    at normalize (C:\Users\harshit\AppData\Roaming\npm\node_modules\prisma\build\index.js:9899:17)
    at module2.exports (C:\Users\harshit\AppData\Roaming\npm\node_modules\prisma\build\index.js:9926:26)
    at async Object.module2.exports [as default] (C:\Users\harshit\AppData\Roaming\npm\node_modules\prisma\build\index.js:9957:20)
    at async getSchemaPathFromPackageJson (C:\Users\harshit\AppData\Roaming\npm\node_modules\prisma\build\index.js:10017:21)
    at async getSchemaPathInternal (C:\Users\harshit\AppData\Roaming\npm\node_modules\prisma\build\index.js:10008:36)
    at async DbPull2.parse (C:\Users\harshit\AppData\Roaming\npm\node_modules\prisma\build\index.js:63731:24)
    at async main (C:\Users\harshit\AppData\Roaming\npm\node_modules\prisma\build\index.js:109791:18)
```

**Comment by Jolg42** [comment]
Seems that the function `fixVersionField` is from `normalize-package-data` pkg which is a dependency of `read-pkg-up` which is used here https://github.com/prisma/prisma/blob/7084c81699e6b4b963679c3fb45f4ce77d4fe0c5/src/packages/sdk/src/cli/getSchema.ts#L5

**Comment by janpio** [comment]
This is definitely unexpected @HurricaneDancer - a side effect of a library we are using. We will try to get rid of that. Sorry.

**Comment by HurricaneDancer** [comment]
> 
> 
> This is definitely unexpected @HurricaneDancer - a side effect of a library we are using. We will try to get rid of that. Sorry.

Thanks!

**Comment by peschee** [comment]
The issue is that it is not a valid semver version. Not sure why prisma is looking at the version in `package.json`, but I'm also not sure whether ANY version (string) should be accepted. Any invalid non-semver version renders your entire `package.json` invalid.

**Comment by Jolg42** [comment]
Note: this still happens in the latest version, like I mentioned earlier, the root cause is that the function `fixVersionField` throws from `normalize-package-data` which is a dependency of `read-pkg-up` which is used in https://github.com/prisma/prisma/blob/468fd2a462a67146ba45b6ca830c50cc3ab635e2/packages/internals/src/cli/getSchema.ts#L6

This code path is triggered by calling `getSchemaPath()` in our code.
