### ISSUE TITLE
Aggregate on non-indexed fields

### ISSUE THREAD

**Issue by binary64** [prisma/prisma#7330]
## Problem

I wish to perform a SUM() against all results of a query.

Suppose I have `query { findManyStaff(where:{...}) { hours_worked } }`, is there a way I can get the SUM of all hours_worked for that where clause?

## Suggested solution

```
prisma.staff.aggregate({where:{...},sum:{_nonIndexed:{hours_worked: true}}})
```
would return
```
{ hours_worked_sum: 1234 }
```
using SQL
```
SELECT SUM(hours_worked) AS hours_worked_sum FROM Staff WHERE ...
```

## Alternatives

Raw sql is always an option, but that isn't why I chose Prisma.

## Additional context

Awesome work, thank you

**Comment by pantharshit00** [comment]
We already support aggregates on non index fields: https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing

If this doesn't address you case, please let us know.
