### ISSUE TITLE
Understand and improve Vercel serverless function cold start impact (of currently 0.4 seconds)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7336]
Prisma and Prisma Client add roughly 0.4 seconds to a standard Vercel serverless function cold start time.

This is a plain `create-next-app` project deployed to Vercel:
![image](https://user-images.githubusercontent.com/183673/120053675-e4d19800-c02b-11eb-9f0c-e8a097c16554.png)

And this is the same project with Prisma and Prisma Client added as dependencies:
![image](https://user-images.githubusercontent.com/183673/120053695-0468c080-c02c-11eb-839f-2e46ee0fe4b7.png)

We could try to understand and maybe even improve that cold start impact.

---

Repository: https://github.com/janpio/vercel-nextjs-test
Original: https://github.com/janpio/vercel-nextjs-test/tree/main
With Prisma: https://github.com/janpio/vercel-nextjs-test/tree/prisma (https://github.com/janpio/vercel-nextjs-test/pull/1)

**Comment by remorses** [comment]
In my case a cold request of https://vercel-nextjs-test-git-prisma-janpio.vercel.app/api/hello takes 4.5 seconds and a warm request takes 200ms average

I am from Italy, Europe

**Comment by janpio** [comment]
Internal document: https://www.notion.so/prismaio/Investigation-of-adding-Prisma-to-a-NextJS-Vercel-project-6b6ae2ac11dd4427b1cf7ec6bd493128

**Comment by janpio** [comment]
We understand, and improved this considerably as did Vercel/Lambda with the upgrade to newer Node versions. We don't see a problem here any more for now.
