### ISSUE TITLE
Validator accepts arbitrary properties in `generator` and `datasource` blocks

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7342]
### Bug description

This schema is happily accepted:

```
generator client {
  provider        = "prisma-client-js"
  foo             = bar
}

datasource db {
  provider          = "mysql"
  url               = env("DATABASE_URL")
  shadowUrlDatabase = env("SHADOW_DATABASE_URL")
  foo               = bar
}
```

That is unfortunate, as `shadowUrlDatabase` should really be `shadowDatabaseUrl` instead, and `foo` of course does nothing as it is not a known property.

### Prisma Version

2.23.0

**Comment by do4gr** [comment]
For datasources we only allow a specific set of properties. And for the prisma-client-js generator as well.

**Comment by pimeys** [comment]
We do have an arbitrary key/value storage in the generator. I don't want to touch those validations, but datasource we know and can validate what should not be there.

**Comment by janpio** [comment]
> We do have an arbitrary key/value storage in the generator

If `provider        = "prisma-client-js"` then we also have a defined list of properties that are possible. If we can scope this validation to this `generator.provider` value, we can give our users value.

**Comment by janpio** [comment]
Follow up in https://github.com/prisma/prisma/issues/11825
