### ISSUE TITLE
Wrong 1-n relation nullable inference

### ISSUE THREAD

**Issue by MikaStark** [prisma/prisma#7348]
Hello there :)

Giving this schema on Prisma 2.23.0, posts always have an author. An an author (user) have many posts (typical 1-n relation). But when generating prism client and using it for creating posts, the author is considered as nullable which is incorrect.

It means [this guide](https://nexusjs.org/docs/plugins/prisma/removing-the-nexus-plugin-prisma#1-n-relations) is broken :/

```prisma
model User {
  id       Int     @id @default(autoincrement())
  posts    Post[]
}

model Post {
  id        Int      @id @default(autoincrement())
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

```ts
context.prisma.post
  .findUnique({
    where: { id: post.id },
  })
.author() // it returns Prisma.Prisma__UserClient<User | null> instead of Prisma.Prisma__UserClient<User>
```

**Comment by ryands17** [comment]
@MikaStark 👋 

This seems like an issue. I would suggest creating one [here](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml) so that we can look into this.

**Comment by MikaStark** [comment]
Hello @ryands17 

Issue posted here : https://github.com/prisma/prisma/issues/7348
