### ISSUE TITLE
Ability to set MongoDB optional fields to `undefined`

### ISSUE THREAD

**Issue by PinkaminaDianePie** [prisma/prisma#7368]
## Problem

Currently, optional fields in MongoDB have the type `T | null`, while sometimes we want to have really optional field, so it should be `T | undefined`. It would be nice to have some mechanism to distinguish between `null` and `undefined`

**Comment by matthewmueller** [comment]
Interesting, we'll need to verify the types optionals are unhandled with SQL. I'd suggest we follow suit.

**Comment by matthewmueller** [comment]
@PinkaminaDianePie , when do you decide to store undefined and when do you decide to store null in your application

**Comment by PinkaminaDianePie** [comment]
I personally thought about not actually storing undefined, but removing property when undefined is explicitly passed

**Comment by dpetrick** [comment]
FYI follow-up for telling `null` and `undefined` apart: https://github.com/prisma/prisma/issues/12555
