### ISSUE TITLE
Handle error `ERROR HY000 (1105): direct DDL is disabled`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7385]
PlanetScale or Vitess (with `enable_direct_ddl=false`) throws the following error if you try to run DDL statements on the `main` branch, as you are supposed to only run these in branches and deploy them via "deploy requests":

```
ERROR HY000 (1105): direct DDL is disabled
```

To reproduce: Run any DDL statement on a `main` branch on a PlanetScale database.

We should catch this and output a known error message with the following message text:

```
Direct execution of DDL (Data Definition Language) SQL statements is disabled on this database. Please read more here how to handle this: https://pris.ly/d/migrate-no-direct-ddl
```

(The link currently points to a rather general issue, but will be updated to point to a specific issue or documentation later)

The Vitess instances we are testing against do _not_ show this behavior by default, but can be configured to do so via `ENABLE_DIRECT_DDL: false` in `docker-compose.yml`.

**Comment by bigint** [comment]
I'm still getting this error but in this video, by @nickvanw it seems like working 🤔 

https://www.youtube.com/watch?v=M5Uq6Gu51Xo

![image](https://user-images.githubusercontent.com/69431456/124601422-6e735180-de85-11eb-9185-26cff80dee0f.png)

**Comment by tomhoule** [comment]
@bigint I think this is probably because you are pushing to the main branch. Pushing to any other branch should work. We haven't implemented special handling for this error yet.

**Comment by bigint** [comment]
> @bigint I think this is probably because you are pushing to the main branch. Pushing to any other branch should work. We haven't implemented special handling for this error yet.

Ahh gotcha thanks!

**Comment by janpio** [comment]
This issue is about exactly implementing that special handling so the error message tells you what to do (don't migrate on the main branch, not going to work on PlanetScale) - so thanks for confirming that this is _exactly_ what we are missing here 😆 

Current instructions for PlanetScale can be found at https://github.com/prisma/prisma/issues/7292

**Comment by bigint** [comment]
So how can we going to handle in production? Instead of main branch we need to create branch called production?

**Comment by janpio** [comment]
That depends on how you want to use PlanetScale. You can either do that, but I am not sure if branches get the same guarantees re stability as the main branch. Or you use their branching system and merge the PR changes from the branch where you applied the migration, to your main branch (instead of using `migrate deploy` as you would in the normal Prisma only workflow).

**Comment by janpio** [comment]
This works in `dev` indeed:

```
C:\Users\Jan\Documents\throwaway\pscaleMigrationTable>npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "migration-table-3" at "127.0.0.1:55625"

√ Enter a name for the new migration: ... dafs
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20210709234927_dafs

Database error code: 1105

Database error:
Direct execution of DDL (Data Definition Language) SQL statements is disabled on this database. Please read more here how to handle this: https://pris.ly/d/migrate-no-direct-ddl

Please check the query number 1 from the migration file.
```

![image](https://user-images.githubusercontent.com/183673/125145382-3daf4880-e121-11eb-869f-caeb88522c26.png)

**Comment by gshwebdev** [comment]
> @bigint I think this is probably because you are pushing to the main branch. Pushing to any other branch should work. We haven't implemented special handling for this error yet.

The problem really lies in this, I spent a couple of hours until I came across your comment. Thank you!

**Comment by phoenixeliot** [comment]
Just commenting in case it helps someone else in my situation: I was getting this error because I actually had a ghost `pscale connect` process in the background and the connection I thought I had open to a dev branch was not actually the one I was connected to. Had to kill that process and reconnect again, then things were fine.

**Comment by octopyth** [comment]
I connect to a non prod branch and validate the connection in the Audit log https://app.planetscale.com/<database>/settings/audit-log
I get the following error message:

```
Error: direct DDL is disabled
   0: sql_migration_connector::apply_migration::migration_step
           with step=CreateTable { table_id: TableId(5) }
             at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:21
   1: sql_migration_connector::apply_migration::apply_migration
             at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:10
   2: migration_core::state::SchemaPush
             at migration-engine/core/src/state.rs:433

error Command failed with exit code 1.
```

**Comment by janpio** [comment]
How would it know the branch? Doesn't the Planetscale connection string look the same?

**Comment by octopyth** [comment]
Indeed with Planetscale it's hard to know the branch, the only indication I guess could be the username, as it's different for every branch, right? It would be good to have something indicating explicitly what's going on, as the getting started tutorials wouldn't mention the DATABASE_URL system var is used for connecting, which makes running an open connection to the dev branch in a different terminal unnecessary.
I was particularly following this guide to execute succeeding Prisma migrations:
https://planetscale.com/docs/tutorials/automatic-prisma-migrations#execute-succeeding-prisma-migrations-in-planetscale

**Comment by janpio** [comment]
Yeah, the environment variables are sometimes "magic" if not explicitly called out what is happening. Maybe suggest to Planetscale to add a sentence where the value comes from and how that works in this tutorial.
