### ISSUE TITLE
Dropping Node v10 support (LTS reached EndOfLife)

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#7394]
For Prisma Client / Prisma CLI we need to drop Node.js v10 (now old LTS)

Its End Of Life was on April 30 (for Security Support) and Active Support was dropped last year in May 2020.

Happy to do it/pair on this since I know where changes are needed.

The outcome will be that we support Node >=12.2.X and >=14.X (v16 is supported but not LTS yet, not recommended for production)

See current version https://www.prisma.io/docs/reference/system-requirements

## Additional context
https://prisma-company.slack.com/archives/C1FPU5FPT/p1621436107007300

**Comment by matthewmueller** [comment]
Can you share why? Is supporting Node 10 holding us back in some way? Is there cruft in our code as a result of supporting Node 10??

**Comment by Jolg42** [comment]
@matthewmueller we have more info in [internal thread](prisma-company.slack.com/archives/C1FPU5FPT/p1621436107007300) I mentioned

**Comment by matthewmueller** [comment]
Awesome, thanks!

> Because
> - We have an increasing number of dependencies that dropped v10 already so staying up-to-date requires us to drop v10 too
> - Prisma Client will need to upgrade it’s undici dependency soon and latest is only >=v12
> - Will be nice to drop this in our CIs

About 2% usage
