### ISSUE TITLE
need to run db push twice in order to apply changes

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#7411]
### Bug description

It happened many times to me already that I run db push, it says “:warning: We found changes that cannot be executed:” and “The PostgreSQL database “db” from “localhost:5340" was successfully reset.“,  then I type y, and it says “Your database is now in sync with your schema.“.
However nothing changed. The changes are not applied.
Then I run db push again, it says once again “Your database is now in sync with your schema”, but now it actually is in sync, and some tables are correctly dropped.

### How to reproduce

- set up prisma project
- run db push
- introduce breaking change
- run db push, should migrate successfully judging by the message but no changes applied in db
- run db push again, shows success again but this time it actually applied the changes in the db

### Expected behavior

changes to be applied immediately after running `db push`

### Prisma information

```prisma
datasource db {
        provider = "postgresql"
        url      = "postgresql://postgres:pw@localhost:5340/db"
}

generator db {
        provider = "prisma-client-js"
}

model User {
        id       String  @id @default(cuid())
        email    String
        name     String?
}
```

### Environment & setup

- OS: 
- Database: PG 
- Node.js version: 

### Prisma Version

```
❯ go run github.com/prisma/prisma-client-go ver
sion 
Environment variables loaded from .env
prisma               : 2.23.0
@prisma/client       : Not found
Current platform     : darwin
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../../../Library/Caches/prisma/binaries/cli/2.23.0/adf5e8cba3daf12d456d911d72b6e9418681b28b/prisma-query-engine-darwin, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../../../Library/Caches/prisma/binaries/cli/2.23.0/adf5e8cba3daf12d456d911d72b6e9418681b28b/prisma-migration-engine-darwin, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../../../Library/Caches/prisma/binaries/cli/2.23.0/adf5e8cba3daf12d456d911d72b6e9418681b28b/prisma-introspection-engine-darwin, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../../../Library/Caches/prisma/binaries/cli/2.23.0/adf5e8cba3daf12d456d911d72b6e9418681b28b/prisma-prisma-fmt-darwin, resolved by PRISMA_FMT_BINARY)
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
```

**Comment by pantharshit00** [comment]
I can reproduce this. Looks like it clears the tables but doesn't recreate them in the first run. 

Exact reproduction steps.

1. Start with the following datamodel and create database using `db push`:
```prisma
model User {
        id       String  @id @default(cuid())
        email    String
        name     String?
}
```

2. Use `npx prisma studio` to create some records with have `name` as `null`
3. Change the datamodel to following:
```prisma
model User {
        id       String  @id @default(cuid())
        email    String
        name     String
}
```
4. Run `npx prisma db push`. It will say drift detected and ask you to reset the database. Agree to the prompt and proceed with the migration.
5. Check the database, there should be no tables recreated.

**Comment by tomhoule** [comment]
Just for context, this happens because the CLI reapplies migrations after you reset, instead of `db push`-ing.
