### ISSUE TITLE
Seed data causing intermittent engine crashes and SQL errors in node 15

### ISSUE THREAD

**Issue by viperfx** [prisma/prisma#7419]
### Bug description

There are intermittent issues when trying to seed the data in node 15. Node 14 works fine and causes no errors.

The errors can vary:

```
Unique constraint failed on the fields: (`email`)

or 

Unique constraint failed on the fields: (`slug`,`teamId`)
```

Error logs with debug enabled and the last 5 SQL statements executed.
https://gist.github.com/viperfx/39390c9f891aa7c4bcd82c86791763a0

@janpio and I have been in contact via Slack and he has everything needed to run the code and reproduce the conditions.

### How to reproduce

We use redwoodjs internally and run the seed/reset command with `DEBUG=* yarn rw prisma migrate reset --force > debug.log 2>&1`. However, I am unsure if redwood is a factor here - just thought I would mention.

1. Use the seed.js and schema.prisma file
2. Create a firebase project, enabled authentication module with username/password auth. 
3. Store the firebase serviceAccountKey JSON blob as the env variable FIREBASE_CREDENTIALS
4. Setup a local docker postgres instance with version 12.6 or a hosted version such as supabase and set credentials to DATABASE_URL. (I have been able to reproduce this locally and in supabase - their postgres version is 12.6).
5. Use node15 and run the seed script. 
6. Script may not exit at the end, so use ctrl-c after output has ended. 

### Expected behavior

1. Runs successfully in node 15 similar to node 14.

### Prisma information
@janpio has the seed.js and prisma.schema file to reproduce the issue.

### Environment & setup

- OS: Windows WSL2 using Ubuntu (have also reproduced with OSX)
- Database: Postgres 12.6
- Node.js version:  v15.14.0

### Prisma Version

```
2.21.2
```

**Comment by pantharshit00** [comment]
Hey @viperfx 

Sorry for late reply here. Can you still reproduce this with the latest version? Node also released v16 so please try again with that.

**Comment by Jolg42** [comment]
🗒️ We heard the feedback and we are planning a redesign of `db seed` (currently planned to be released early September)

How it will work is that a `prisma.seed` property in the package.json of your project will be required if you want to use `prisma db seed`.

This property is where you will be able to put any command you want to execute your seed script.

More info/details & how to try it out now in:
https://github.com/prisma/prisma/issues/8732

**Comment by janpio** [comment]
The redesign of `db seed` was released with Prisma 3. Please try it, this problem should be gone.
