### ISSUE TITLE
Easy workflow to reset all data

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#742]
## Problem

There currently doesn't seem to be a way to easily reset a database.

## Suggested solution

Provide a way to reset the database (via CLI, SDK, Studio). This should delete the database, re-create it from the schema and finally seed it (if there is a seed).

## Additional context

Popular frameworks like Ruby on Rails have integrated tools to manage the lifecycle of a database:

* `db:create` creates the database for the current env
* `db:create:all` creates the databases for all envs
* `db:drop` drops the database for the current env
* `db:drop:all drops` the databases for all envs
* `db:migrate` runs migrations for the current env that have not run yet
* `db:migrate:up` runs one specific migration
* `db:migrate:down` rolls back one specific migration
* `db:migrate:status` shows current migration status
* `db:rollback` rolls back the last migration
* `db:forward` advances the current schema version to the next one
* `db:seed` (only) runs the db/seed.rb file
* `db:schema:load` loads the schema into the current env's database
* `db:schema:dump` dumps the current env's schema (and seems to create the db as well)

## Original issue

>There currently doesn't seem to be a way to easily reset all data. This should be possible via Studio, CLI and/or SDK.

**Comment by janpio** [comment]
Clarification: First step here would be to create a spec that defines how this might work and what it might be called.

**Comment by janpio** [comment]
Internal Note: Move to specs

**Comment by schickling** [comment]
First step: Implement this functionality in Studio (See issue https://github.com/prisma/studio/issues/237).

After that we'll investigate further whether/how to expose this functionality via other tools (e.g. CLI, SDK, ...)

**Comment by timsuchanek** [comment]
Internal Note: Dropping, because of Studio only thing.

**Comment by pantharshit00** [comment]
Internal note: Candidating this because of another duplicate issue that refered to same feature was candidated by @schickling

**Comment by frandiox** [comment]
We use Prisma v1 CLI to prepare the database for e2e and for integration tests. It's really handy to do `prisma reset && prisma seed -e .env.[e2e|int]`.
What would be the equivalent in Prisma 2?

**Comment by Sytten** [comment]
Agreed, we did a custom script to do this but its not ideal (I can share if someone needs). One thing to keep in mind is to also reset the sequences so the ID are stable.

**Comment by maoosi** [comment]
Agreed with @frandiox, the ability to do a reset via the CLI is really handy - especially for testing purpose.

@Sytten I'm interested about your custom script if you're still happy to share it?

**Comment by Sytten** [comment]
```typescript
import { PrismaClient } from '@prisma/client';

const tableNames = [
  'User',
  'Store'
];

export default async () => {
  const prisma = new PrismaClient();

  try {
    for (const tableName of tableNames) {
      await prisma.raw(`DELETE FROM "${tableName}";`);

      if (!['Store'].includes(tableName)) {
        await prisma.raw(
          `ALTER SEQUENCE "${tableName}_id_seq" RESTART WITH 1;`
        );
      }
    }
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error(err);
  } finally {
    await prisma.disconnect();
  }
};
```

**Comment by dardub** [comment]
Hi @schickling .

I've just started trying out Redwood JS. They have a layer of db commands on top of prisma cli, and I've already found myself wishing we were able to run `yarn rw db reset` and similar commands for local development.

It would be great if this could be made available outside of Prisma Studio.

**Comment by terrierscript** [comment]
I found workaround with use reset schema

```
// prisma/reset.prisma
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}
generator client {
  provider = "prisma-client-js"
}

model Reset {
  id        Int     @id @default(autoincrement())
}
```

and execute

```
$ prisma db push --preview-feature --force --schema=./prisma/reset.prisma; prisma db push --force --preview-feature
```

**Comment by BjoernRave** [comment]
so now this is possible with `prisma migrate reset --preview-feature` right? Is there are also way to programmatically reset the db as part of a testing suite?

**Comment by Jolg42** [comment]
@BjoernRave Indeed though this command assumes you are using migration files.

We are thinking about a `prisma migrate drop` or `truncate` that could fit any needs.

**Comment by adarnon** [comment]
It is possible with `prisma migrate reset`, but it's not very performant and would take very long if all you want to do is truncate.

**Comment by nephix** [comment]
> It is possible with `prisma migrate reset`, but it's not very performant and would take very long if all you want to do is truncate.

It also requires user confirmation, last time I checked

**Comment by adarnon** [comment]
They added a `--force` flag in 2.15.

**Comment by Jolg42** [comment]
Here is a manual truncate example that could help for now for PostgreSQL ([example from Keystone](https://github.com/keystonejs/keystone/blob/119f3f791ad072eef49719a2c8c8db10ed93611c/packages/adapter-prisma/lib/adapter-prisma.js#L232-L248)):
```
        // Special fast path to drop data from a postgres database.
        // This is an optimization which is particularly crucial in a unit testing context.
        // This code path takes milliseconds, vs ~7 seconds for a migrate reset + db push
        for (const { tablename } of await this.prisma.$queryRaw(
          `SELECT tablename FROM pg_tables WHERE schemaname='${this.dbSchemaName}'`
        )) {
          await this.prisma.$queryRaw(
            `TRUNCATE TABLE \"${this.dbSchemaName}\".\"${tablename}\" CASCADE;`
          );
        }
        for (const { relname } of await this.prisma.$queryRaw(
          `SELECT c.relname FROM pg_class AS c JOIN pg_namespace AS n ON c.relnamespace = n.oid WHERE c.relkind='S' AND n.nspname='${this.dbSchemaName}';`
        )) {
          await this.prisma.$queryRaw(
            `ALTER SEQUENCE \"${this.dbSchemaName}\".\"${relname}\" RESTART WITH 1;`
          );
        }
```

**Comment by albertoperdomo** [comment]
We have `prisma migrate reset` now, which:

1. drops the database
2. creates the database
3. applies migrations
4. seeds the database.

We are closing this issue.


For those who are interested in truncating tables over dropping and re-creating the database, which is tracked here: https://github.com/prisma/prisma/issues/5596

**Comment by beeman** [comment]
> We have `prisma migrate reset` now, which:
> 
>     1. drops the database
> 
>     2. creates the database
> 
>     3. applies migrations
> 
>     4. seeds the database.
> 
> 
> We are closing this issue.
> 
> For those who are interested in truncating tables over dropping and re-creating the database, which is tracked here: #5596

You folks are amazing!!  🙏

**Comment by chinanderm** [comment]
@Jolg42 Yep, that works great. Thank you!

**Comment by Jolg42** [comment]
@chinanderm Note that if you're already using migrations files I would recommend to use 
```
prisma reset --force --preview-feature && prisma migrate deploy --preview-feature
```
Why? Because `db push` creates the SQL on the fly while you could have extra SQL that it could not guess (like if you edited the migration.sql files).
So using reset + deploy makes sure you have the same end-state as in production (minus the data).

**Comment by simonjcarr** [comment]
Has it all changed again??????
```
npx prisma reset

! Unknown command "reset"
```

**Comment by Athar-ali-siddiqui** [comment]
I have used this strategy to ensure the database is cleaned up before executing each test.
```
await this.$queryRaw(
            Prisma.sql`
            do $$DECLARE
            begin 
                EXECUTE 
                (SELECT 'TRUNCATE TABLE '
                    || string_agg(format('%I.%I', schemaname, tablename), ', ')
                    || ' CASCADE'
                FROM   pg_tables
                WHERE  tableowner = 'postgres'
                AND    schemaname = 'public'
                AND    hastriggers = true
                );
            END$$;`
        );
```

**Comment by campellcl** [comment]
If you are trying to get this working from inside a `.ts` file (for instance `seed.ts`) you can:
```
import { exec, execSync } from "child_process";
import { promisify } from "util";

export default async function clearDatabase() {
  const execAsync = promisify(exec)
  try {
    const {stdout, stderr} = await execAsync('pnpm prisma db push --force-reset')
    console.log(`stdout: ${stdout}`)
    console.error(`stderr: ${stderr}`)
  } catch (error) {
    console.error(`error: ${error}`)
  }
}
```

In the invoker (i.e. `jest` testing script):
```
  beforeAll(async () => {
    // Reseed the database before running the tests
    await clearDatabase()
    await seed()
  })
```

**Comment by s14051sa-png** [comment]
All the evidence must be clear.
