### ISSUE TITLE
Do not use Node-API library on M1 Macs or 32bit Node, add warning that library is not currently supported, use binary instead

### ISSUE THREAD

**Issue by williamluke4** [prisma/prisma#7431]
On M1 ARM Mac until we a native build for M1:

- Use binary even when instructed via preview feature (or later default) to use Node API libary
- Output note that this is happening, so people can be aware
- Also needs to be tested somewhere, somehow (optional e2e test via MacStadium machine?)

**Comment by janpio** [comment]
The same logic can probably be used for disabling the Node API library on Windows 32 bit Node as well, which is also not supported by our implementation and build - so this might be a quick win.

**Comment by janpio** [comment]
Update: Blocking these first during the preview phase: https://github.com/prisma/prisma/issues/7560 
This will be implemented later.

**Comment by janpio** [comment]
Not doing this now, as we will jsut build the binaries instead: https://github.com/prisma/prisma/issues/5245
