### ISSUE TITLE
`notIn` filter operator returns invalid data

### ISSUE THREAD

**Issue by YEriin** [prisma/prisma#7434]
Suppose you have one `User` table and query like this:
```js
  const result = await prisma.user.findMany({
    where: {id: {notIn: Array.from({length: 6000}, (v, idx) => idx.toString())}}
  })
  const total = await prisma.user.findMany({
    where: {}
  })
```

prisma will execute 2 sql and return the merged result:
```sql
select xxx where xxx not in ($1,$2, ..., $5000)
select xxx where xxx not in ($1000,$2, ..., $6000)
```

So the final result will contain the intersection of each single sql result and it's not as expected.

**Comment by pantharshit00** [comment]
Hmm, looks like we should refactor this as we can't really use batching here but not really sure if people will filter out 5000+ keys. 

But still that is not an excuse and we should fix this.

**Comment by victortelevet** [comment]
If its only a few values you could use:
prisma.service.findMany({
  where: {
    OR: [
      {
        rawPimsValue: {
          path: ["type"],
          equals: "Inventory",
        },
      },
      {
        rawPimsValue: {
          path: ["type"],
          equals: "OtherType1",
        },
      },
      {
        rawPimsValue: {
          path: ["type"],
          equals: "OtherType2",
        },
      },
    ],
  },
});
