### ISSUE TITLE
Prisma 2.24.0 throws error `Query engine exited with code 101 - thread 'main' panicked at 'Could not open datamodel file "/schema.prisma"...'`

### ISSUE THREAD

**Issue by cyrus-za** [prisma/prisma#7439]
### Bug description

<img width="884" alt="image" src="https://user-images.githubusercontent.com/1845861/120661245-60966f00-c488-11eb-9ded-9edd56e90fb0.png">

Everything works fine in 2.23.0

I am using [nx](github.com/nrwl/nx) with [next](https://github.com/vercel/next.js) and hosting on [vercel](https://vercel.com)

### How to reproduce

Not sure I'll be able to setup a minimal reproduction, but @janpio has access to our code to reproduce simply by upgrading to 2.24.0

### Prisma information

Query runs during next build to do SSG. I don't believe the actual schema is relevant

### Environment & setup

- OS: Debian (on vercel)
- Database: PostgreSQL, MySQL, MariaDB or SQLite
- Node.js version: 14.16.0

### Prisma Version

```
2.24.0
```

**Comment by janpio** [comment]
I can confirm this in the reproduction we have.

**Comment by wuichen** [comment]
i think this happens specifically when you add output to prisma.schema's generator client section. i am facing the same issue when pointing client generation at a different path. i think this is also the issue blocking other multi-data sources prisma access in monorepo.

**Comment by janpio** [comment]
Do you have a reproduction @wuichen or can create one? The project from @cyrus-za is pretty complicated, so having something as simple as possible that shows the same problem would be _very_ welcome.

**Comment by wuichen** [comment]
@janpio mines kind of complicated as well. i was using pal.js for my project when i encountered the error. i was using the multi data source template. you should be able to check it without any change after setuping up. i think its better for you to setup yourself and get a better understanding of how it hooked up the prisma.dmmf to repo. paljs takes less than a min to setup a fullstack project. and some places to keep an eye on is server/context, package.json, pal.js, and nexusSchema

**Comment by janpio** [comment]
If doing that triggers this error, please do so and put it on GitHub so we have something we _know_ causes this to happen, and we do not go wasting multiple hours trying to make it break this way.

**Comment by wuichen** [comment]
hi i cannot repro this specific error message. in fact, its showing other errors. i have put together the paljs repo i mentioned about with single prisma and multi prisma cases on different branch. the single prisma repo has a _http_common package cant resolve error. where as the multi prisma case just doesnt load the result. https://github.com/wuichen/prisma-isse-7439
![Screen Shot 2021-06-14 at 3 26 32 PM](https://user-images.githubusercontent.com/6353587/121854707-17b2a600-cd25-11eb-8142-4ed8b271915a.png)

**Comment by janpio** [comment]
Here are two issues about the `_http_common` thing: https://github.com/prisma/prisma/issues/6564 + https://github.com/prisma/prisma/issues/6925 (There are a bunch of workarounds in the comments like https://github.com/prisma/prisma/issues/6564#issuecomment-849685096)
