### ISSUE TITLE
prisma generate error v2.24.1

### ISSUE THREAD

**Issue by zhangyj1998** [prisma/prisma#7449]
### Bug description

```
Error: Schema parsing
error: Native types can only be used if the corresponding feature flag is enabled. Please add this field in your generator block: `previewFeatures = ["nativeTypes"]`
```

Again, the previous version was v2.21.2. Error running `prisma generate` after upgrading to v2.24.1.This previewFeatures should have been deprecated in previous versions.

### How to reproduce

```
datasource db {
  provider      = "postgresql"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
  url           = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

`npx prisma generate`

### Prisma information

```
datasource db {
  provider      = "postgresql"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
  url           = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model ReserveApplication {
  id              String                       @id @default(uuid())
  createdAt       DateTime                     @default(now())
  updatedAt       DateTime?                    @updatedAt
  clientWeight    Decimal                      @db.Decimal(65, 30)


  @@map("reverse_application")
}
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v13.11.0

### Prisma Version

```
prisma               : 2.24.1
@prisma/client       : 2.24.1
Current platform     : darwin
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0

**Comment by Jolg42** [comment]
Hi!

`nativeTypes` flag is not needed anymore in latest version (2.24) so this error means that you likely have an older version.

Could you check the output of `npx prisma -v`?

**Comment by zhangyj1998** [comment]
> npx prisma -v

prisma               : 2.24.1
@prisma/client       : 2.24.1
Current platform     : darwin
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0

**Comment by zhangyj1998** [comment]
My previous version is 2.21.2.I run `npm i --save-dev prisma` and  `npm i @prisma/client` to updata.But when I run `npx prisma generate`,it throw the error _Native types can only be used if the corresponding feature flag is enabled._

**Comment by Jolg42** [comment]
I think somehow the update didn't work in your project 🤔 

Maybe try 
- deleting `node_modules` folder
- set `2.24.1` version in package.json for both Prisma dependencies
- run `npm i`

**Comment by Jolg42** [comment]
If that doesn't work, could you share your package.json file here?
