### ISSUE TITLE
Decrease prisma client start up time.

### ISSUE THREAD

**Issue by Saeid-Za** [prisma/prisma#7457]
## Problem
Hello, i've been using prisma in my backend projects and been enjoying it so far!
Today i decided to give prisma a shot on an electron app, where start up time matters and has direct influence on perceived performance of application. 
unfortunately, importing the generated `@prisma/client` takes 4 to 5 seconds to fully load (parse and execute)
For developer to be able to use prisma as an ORM in UI Applications, it should take a short time to fully load.

## Suggested solution
The generated `runtime` has more than 32K lines of code, which i doubt that all of them are executed when imported, but still a huge file with a lot lines of code. Could it be decreased? or Could the execution be differed when needed (executing lazily)? 

## Additional context

Running The following code on:
- Kubuntu 20.04
- Linux(5.4.0-74-generic) - linux/x64
- Node 14.16.1
- 16G of Ram
- CPU  i7-4700MQ (2.4GHz)

using this code to measure: 
```js
const { performance, PerformanceObserver } = require("perf_hooks");
const perfObserver = new PerformanceObserver((items) => {
  items.getEntries().forEach((entry) => {
    console.log(entry);
  });
});

perfObserver.observe({ entryTypes: ["measure"], buffer: true });

async function prismaLoad() {
  performance.mark("start");
  const PrismaClient = require("@prisma/client").PrismaClient;
  performance.mark("load");
  const prisma = new PrismaClient();
  performance.mark("create");
  await prisma.$connect();
  performance.mark("connect");
  await prisma.$disconnect();
}

async function mesaure() {
  await prismaLoad();
  performance.measure("Load Time", "start", "load");
  performance.measure("Creation Time", "load", "create");
  performance.measure("Connection Time", "create", "connect");
}

mesaure();

```

sample output: 
```
PerformanceEntry {
  name: 'Load Time',
  entryType: 'measure',
  startTime: 47.753599,
  duration: 8976.801972
}
PerformanceEntry {
  name: 'Creation Time',
  entryType: 'measure',
  startTime: 9024.555571,
  duration: 16.806016
}
PerformanceEntry {
  name: 'Connection Time',
  entryType: 'measure',
  startTime: 9041.361587,
  duration: 82.600379
}
```

using Primsa Model from [Here](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model). (fairly simple model)

**Comment by pantharshit00** [comment]
Hey, 

Can you please try the `nApi` preview here once with latest version `2.24.1`? https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#enable-the-n-api-preview


We will obviously investigate this a bit more but seeing results with Node API integration which doesn’t spawn the query engine binary would be interesting

**Comment by Saeid-Za** [comment]
Hello,
After trying `nApi` with the latest version (`2.24.1`) I didn't see any tangible difference.
Please do note that the previous results that were reported were on `2.24.1` too.

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/8178
