### ISSUE TITLE
How do I run this join query using prisma?

### ISSUE THREAD

**Issue by facinick** [prisma/prisma#7473]
I'm learning graqhql with apollo and prisma.

let's talk about DB first, I have two basic tables, `users` and `friends`. `friends` have follow `senderId`, follow `receiverId` at them minimum and a composite `id` as well. Below is the prisma schema I've created while learning:

```prisma
    model User {
      name         String  
    
      // foregin key NUser -> MFriends
      iFollowList     Friends[]   @relation("iFollowList")
      followsMeList    Friends[]   @relation("followsMeList")

      id           Int      @id @default(autoincrement())
    }
    
    // all the rows in this table whose receiverId is same as id, are friends (i am sending requests)
    // all the rows in this table whose senderId is same as id, are slaves (i am receiving requests)
    
    model Friends {
      // foregin key User->User
      senderId      Int
      // foregin key User->User
      receiverId     Int
      // for prisma client
      sender        User @relation(name: "followsMeList", fields: [senderId], references: [id])
      receiver       User @relation(name: "iFollowList", fields: [receiverId], references: [id])
      // unique followerId followingId combination
      @@id([senderId, receiverId])
    }
```

so great, the prisma level relations and database level relations work perfectly. Now I want to run this simple query:

QUERY: **Get all the followers (basically an array of user) for user with `id = 1`.**

and this is my prisma query for the same(here I'm trying to find followers of user with id = 1 let's say) : *(the query is for user, and i user the root.id to write a resolver for it's followers)*
```ts
    const _user = await prisma.friends.findMany({
        where: {
            receiverId: _root.id,
        },
        include: {
            sender: true
        },
    });
    

    // I DON't WANT TO DO THIS
    const _followers = _user.map(queryResult => ({
        id: queryResult.sender.id,
        name: queryResult.sender.name,
    }));
    
    return _followers;
```
now this is working but,

You see, by doing "include", the result comes as a list of records from "friends" table with prisma joining the sender for me, so result is something like:

    [{
        senderId,
        receiverId,
        id,
        sender: {
            ...the user object
            for sender 1
        }
    },
    {
        senderId,
        receiverId,
        id,
        sender: {
            ...the user object
            for sender 2
        }
    }...]

and then I manually extract an array of users by using js's array.prototype.map function.

What I want is just an array of objects from Users table that are the followers. 

How do I perform this? Please let me know if you need anything else apart from what's mentioned.. it's been over 2 weeks and I'm not able to move past this.

following is what i believe the query I want, not a 100% sure though.
```sql
    select * from users
    where users.id in (select senderId from friends where receiverId = 1)
```

**Comment by ryands17** [comment]
@facinick 👋 

Prisma currently returns the fields exactly as specified in the relation, so you would have to map this in your application logic itself.

**Comment by facinick** [comment]
and How do I run orderBy on the included part then?

**Comment by facinick** [comment]
Hi @Ryan, Thanks but I also want to know how do I run "orderBy" inside "Include" part of the query, basically I want the "findMany" to return results in the order based on keys of the included relation, if you're getting what Im trying to say...

**Comment by ryands17** [comment]
Answered here: https://github.com/prisma/prisma/discussions/7486

**Comment by pantharshit00** [comment]
Awesome, then I will close this. We can follow this up in the discussion itself
