### ISSUE TITLE
Unified Logging

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma#749]
This issue describes a unified way to collect, store and consume logs from a Graphcool Cluster.

## Log Format

All logs are collected in json format. The framework can include converters to default formats such as syslog.

### Functions

Graphcool has a pluggable function runtime. All function runtimes should report logs in the same format.

Function execution logs should contain the following information:

- timestamp
- serviceName
- functionName
- requestId (if initiated by a request)
- duration

Function logging logs should contain the following information:

- timestamp
- serviceName
- functionName
- requestId (if initiated by a request)
- message

### Requests

Request logs should include the following information:

- timestamp
- serviceName
- requestId
- sourceIp
- query
- variables
- status
- duration

### Cluster Status

Cluster status logs contain information about the health of the cluster

- timestamp
- component
- message

## Log Storage

The Graphcool framework does not store logs. It simply collects logs in a unified format and enables other components to stream and filter logs.

One or more log consumers can be configured to ship logs to a central system such as syslog or CloudWatch Logs.

## CLI

The CLI can act as a log consumer by streaming logs in real time. It should be able to filter by log source as well as the content of individual fields in a log message.

**Comment by James-Firth** [comment]
Hey @sorenbs has there been any progress or discussion elsewhere on this since October?

I see @marktani had the idea to stream logs to a service in #586 and we would definitely appreciate having that functionality!

Unified logging would also be beneficial for those who are looking at dealing with different audit/recordkeeping requirements.
