### ISSUE TITLE
prisma.$executeRaw(`DELETE FROM "${table}";`) does not work

### ISSUE THREAD

**Issue by felixhaeberle** [prisma/prisma#7510]
### Bug description

Hey folks, I'm currently writing my jest integration tests and getting:

`Invalid prisma.user.create() invocation: Unique constraint failed on the fields: (id)`

This is because a call to empty the database after each tests isn't working properly.

This is the code which should execute, but doesn't, the data doesn't get deleted and therefore the unique constraint error is fired when adding the new (but becuase not deleted equal) seed data for the next test.

```
// Inspired by prisma/docs#451
async function emptyDatabase() {
  const tables = Prisma.dmmf.datamodel.models.map(
    (model) => model.dbName || model.name
  );

 await Promise.all(
    tables.map((table) => prisma.$executeRaw(`DELETE FROM "${table}";`))
  );
}
```

This is the error.
```
yarn run v1.22.4
$ jest
 FAIL  src/server/graphql/Team/test.ts
  ● createTeam › should create team
    Invalid `prisma.user.create()` invocation:
      Unique constraint failed on the fields: (`id`)

      37 | async function seedDatabase({ users = [], projects = [], teams = [] }: SeedData) {
      38 |   // Insert users
    > 39 |   await Promise.all(
         |   ^
      40 |     users.map((user) =>
      41 |       prisma.user.create({
      42 |         data: user

      at cb (node_modules/@prisma/client/runtime/index.js:79160:17)
          at async Promise.all (index 0)
      at seedDatabase (src/test/seed/index.ts:39:3)
      at reseedDatabase (src/test/seed/index.ts:81:3)
      at Object.<anonymous> (src/test/jest-setup.ts:6:3)

 PASS  src/server/graphql/User/test.ts

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 3 passed, 4 total
Snapshots:   6 passed, 6 total
Time:        3.023 s
Ran all test suites.
```

### How to reproduce

```
// Inspired by prisma/docs#451
async function emptyDatabase() {
  const tables = Prisma.dmmf.datamodel.models.map(
    (model) => model.dbName || model.name
  );

 await Promise.all(
    tables.map((table) => prisma.$executeRaw(`DELETE FROM "${table}";`))
  );
}
```

### Prisma information

This is the seeding code which fails because the database isn't empty. 

```
async function seedDatabase({ users = [], projects = [], teams = [] }: SeedData) {
  // Insert users
  await Promise.all(
    users.map((user) =>
      prisma.user.create({
        data: user
      })
    )
  );

  // Insert projects & connect them to their users
  await Promise.all(
    projects.map((project) =>
      prisma.project.create({
        data: {
          ...project,
          users: {
            connect: project.users?.map((id) => ({ id })),
          },
        },
      })
    )
  );

  // Insert Teams
  await Promise.all(
    teams.map((team) =>
      prisma.team.create({
        data: {
          ...team,
          users: {
            connect: team.users?.map((id) => ({ id })),
          },
          projects: {
            connect: team.projects?.map((id) => ({ id })),
          }
        },
      })
    )
  );
}
```

### Environment & setup

macOS 10.15.7

### Prisma Version

I'm running on `"jest": "^26.6.3",` and `"@prisma/client": "~2.18.0",`

**Comment by pantharshit00** [comment]
Hello @felixhaeberle 

Sorry for late reply here. 

I tried to reproduce this and I wasn't able to reproduce this with 2.28. The error you provided is also constraint violation which also seems unrelated with the delete. Can you please upgrade to latest version and try this again? 

If you can still reproduce this, please share a minimal reproduction inside of git reproduction.

**Comment by jtlindsey** [comment]
I was able to reproduce the problem with just the following code and [postgresql](https://www.postgresql.org/docs/8.2/sql-droptable.html):

create.test.ts
```
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

beforeAll(async () => {
  await prisma.$executeRaw`DROP TABLE user`;
  // await prisma.$executeRaw('TRUNCATE TABLE user RESTART IDENTITY CASCADE;');
});

test('should random test ', async () => {
  expect(3).toBe(3);
});
```

and run `npm run test` and get:

```
    Invalid `prisma.executeRaw()` invocation:


      Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "user"`

      at cb (node_modules/@prisma/client/runtime/index.js:35943:17)
```

**Comment by janpio** [comment]
@jtlindsey: Might your case actually be a slightly different version of https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#alter-limitation-postgresql? There are limitations around `ALTER`, maybe there are also around `DROP table`? Or is that only the minimal example you came up with?

**Comment by jtlindsey** [comment]
@janpio This is a minimal example to reproduce the issue. I'm running pg `v13.2`. I don't see any documentation at that link that the first syntax or the following (which produces the same error) is prohibited: 

`await prisma.$executeRaw('TRUNCATE TABLE user RESTART IDENTITY CASCADE;');`
or `await prisma.$executeRawUnsafe('DROP TABLE user');` after upgrading to the latest (`3.0.2`) and get the same error.

**Comment by janpio** [comment]
Documentation can be wrong and missing special cases.

Optimally, can you create a new issue about this and provide all the information the template asks for? I think as you are getting a different error message as the original poster, this is most probably not the same problem.

**Comment by Weakky** [comment]
Hey folks,

@jtlindsey Your error happens because you're missing the quotes surrounding your table name 👇

```ts
await prisma.$executeRaw`DROP TABLE "user"`;
```

@felixhaeberle I'm unable to reproduce your issue mostly because your DELETE query is invalid in the first place. Identifiers (table or column names) can not be passed as parameters of prepared statements.

You should be using `$executeRawUnsafe` for what you're trying to achieve. Below is a working example of what I think you're trying to do 👇:

```ts
import { PrismaClient, Prisma } from "@prisma/client";

const prisma = new PrismaClient();

async function emptyDatabase() {
  const tables = Prisma.dmmf.datamodel.models.map(
    (model) => model.dbName || model.name
  );

  return Promise.all(
    tables.map((table) => prisma.$executeRawUnsafe(`DELETE FROM "${table}";`))
  );
}

afterEach(async () => {
  await emptyDatabase();
});

test("create user 1", async () => {
  let { id } = await prisma.user.create({
    data: { id: 1 },
  });
  expect(id).toBe(1);
});

test("create user 2", async () => {
  let { id } = await prisma.user.create({
    data: { id: 1 },
  });
  expect(id).toBe(1);
});

test("create user 3", async () => {
  let { id } = await prisma.user.create({
    data: { id: 1 },
  });
  expect(id).toBe(1);
});

test("create user 4", async () => {
  let { id } = await prisma.user.create({
    data: { id: 1 },
  });
  expect(id).toBe(1);
});

test("create user 5", async () => {
  let { id } = await prisma.user.create({
    data: { id: 1 },
  });
  expect(id).toBe(1);
});
```
