### ISSUE TITLE
[migrate] Custom index with pg_trgm gets removed immediately and causes drift

### ISSUE THREAD

**Issue by 0xsven** [prisma/prisma#7515]
## Problem

I am creating a migration script with `npx prisma migrate dev --create-only`:

My `migration.sql` file:
```sql
CREATE EXTENSION IF NOT EXISTS pg_trgm;

DROP INDEX IF EXISTS index_on_profile_name_trigram;
CREATE INDEX index_on_profile_name_trigram ON "Profile" using gin (name gin_trgm_ops);
```

Then I am running `npx prisma migrate dev`. 

Two outcomes:
1. Prisma-migrate detects a drift and empties my database content (`Drift detected: Your database schema is not in sync with your migration history.`)
2. Prisma-migrate creates a second migration file that removes the index again.

Auto-generated `migration.sql`:
```sql
-- DropIndex
DROP INDEX "index_on_profile_name_trigram";
```

## Suggested solution

Both "outcomes" described above should **not** happen.
Instead prisma-migrate should only apply my migration script.

## Alternatives

- Deleting the automatically generated `migration.sql` file everytime I add a new migration
- Also it will detect a drift everytime, and require me to import my database content again
This is very inconvenient.

## Additional context

I have asked around in the slack channel and got asked to create this PR:

![Screenshot 2021-06-07 at 16 47 09](https://user-images.githubusercontent.com/973379/121037792-0b23d000-c7b0-11eb-9c3d-53deda4dd66d.png)

**Comment by tomhoule** [comment]
Hi @0xsven ! Thanks for the issue. Have you tried adding `@@index([name])` to the model? We want to support the full variety of postgres indexes in the future, but adding `@@index([name])` on the model should at least prevent migrate from dropping it, for now.

**Comment by jackbravo** [comment]
I tried doing this. Adding `@@index([name])` and then modifying the migration to create a `gin` index instead of the regular index, and this seems to be working.

**Comment by tomhoule** [comment]
Happy to read you found a workaround @jackbravo  — of course it's not ideal, but we are planning to enrich what you can say about indexes in the Prisma schema relatively soon (I can't give dates, but I think it's high on the list of priorities).

**Comment by manV** [comment]
To anyone who is having same issue, this worked for me

```
@@index([columnName(ops: raw("gin_trgm_ops"))], type: Gin)
```

and manually adding `CREATE EXTENSION` statement in the migration file before index creation.

**Comment by janpio** [comment]
Quick question: What happens if you `db pull` when this index is already present, either with the schema you already have or a new, empty one? Would be interesting to know if this index is picked up, and if so how.

**Comment by janpio** [comment]
I just took a look at this again, and can confirm that manually modifying the migration that adds the index to also activate the extension should be enough to properly use `pg_trgm` and the `gin_trgm_ops` operator class:

1. Create a minimal schema:
	```prisma
	generator client {
	  provider = "prisma-client-js"
	}
	
	datasource db {
	  provider = "postgresql"
	  url      = env("DATABASE_URL")
	}
	
	model Profile {
	  id   Int    @id
	  name String
	}
	```
2. Create an initial migration with `npx prisma migrate dev`
3. Now add the index to `Profile` in the schema file:
	```prisma
	model Profile {
	  id   Int    @id
	  name String
	
	  @@index([name(ops: raw("gin_trgm_ops"))], type: Gin)
	}
	```
4. Use `npx prisma migrate dev --create-only` to create a migration you can edit before it is executed
5. Add the `CREATE EXTENSION` command to the generated migration:
	```sql
	-- CreateIndex
	CREATE EXTENSION IF NOT EXISTS pg_trgm;
	
	CREATE INDEX "Profile_name_idx" ON "Profile" USING GIN ("name" gin_trgm_ops);
	```
6. Execute the modified migration file with `npx prisma migrate dev`
7. Observe how everything succeeded, and `npx prisma db pull` does not modify the Prisma schema file, and how `npx prisma migrate dev` does not create any migration that drops an index or similar.
So from my perspective this is all resolved. Do you agree @jackbravo?

Going to close the issue for now 🚀
