### ISSUE TITLE
Make a smaller prisma node_module dependency

### ISSUE THREAD

**Issue by kivi** [prisma/prisma#7520]
## Problem

Prisma is always a part of some bigger implementation. When I check the file size in node_modules, it seems by size the most prominent one. Not only it is the largest, but it is huge, so it slows down build processes. It influences your structure, hence you have many micro services, then each microservice containing prisma would need at least 250MB. 

107M    ./node_modules/@prisma

3.8M    ./node_modules/@prisma/client
102M    ./node_modules/@prisma/engines
1.1M    ./node_modules/@prisma/sdk

183M    ./node_modules/prisma

14M     ./node_modules/prisma/build
137M    ./node_modules/prisma/node_modules
3.8M    ./node_modules/prisma/prisma-client

## Suggested solution

I don't know how prisma is structured, but documentation and maybe other things could be separated. I can imagine that there is a lot of unnecessary sub dependencies, that could be cleaned up.

**Comment by janpio** [comment]
The sizes you are seeing are a bit weird indeed. Prisma is big as it ships with a bunch of binaries, but usually not _that_ big.

Can you list the contents of `./node_modules/@prisma/engines` and `./node_modules/prisma/node_modules` please? Are you using `binaryTargets` in your Prisma Schema?

**Comment by kivi** [comment]
For my initial issue description I installed "blitz.js", which includes Prisma. And I am using Windows. But I deploy with Docker on Linux.

`./node_modules/prisma/node_modules`
```
137M    ./node_modules/prisma/node_modules/@prisma/engines

646   Apr 12 15:46 package.json
3.4M Jun  8 10:18 prisma-fmt-windows.exe
30M Jun  8 10:18 query-engine-windows.exe
13M Jun  8 10:18 introspection-engine-windows.exe
23M Jun  8 10:18 migration-engine-windows.exe

1.2M    ./node_modules/prisma/node_modules/@prisma/engines/download
68M     ./node_modules/prisma/node_modules/@prisma/engines/node_modules/.cache
68M     ./node_modules/prisma/node_modules/@prisma/engines/node_modules
```


Content of  `node_modules/prisma/node_modules/@prisma/engines/node_modules/.cache/prisma/master/60ba6551f29b17d7d6ce479e5733c70d9c00860e/windows/`
```
13M Jun  8 10:18 introspection-engine
64 Jun  8 10:18 introspection-engine.gz.sha256
64 Jun  8 10:18 introspection-engine.sha256
23M Jun  8 10:18 migration-engine
64 Jun  8 10:18 migration-engine.gz.sha256
64 Jun  8 10:18 migration-engine.sha256
3.4M Jun  8 10:18 prisma-fmt
64 Jun  8 10:18 prisma-fmt.gz.sha256
64 Jun  8 10:18 prisma-fmt.sha256
30M Jun  8 10:18 query-engine
64 Jun  8 10:18 query-engine.gz.sha256
64 Jun  8 10:18 query-engine.sha256
```
And the list above is pretty similar for  `./node_modules/@prisma/engines/node_modules/.cache/prisma/master/c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d/windows`


files in `./node_modules/@prisma/engines/`
```
13M Jun  8 10:18 introspection-engine-windows.exe
16M Jun  8 10:18 migration-engine-windows.exe
3.4M Jun  8 10:18 prisma-fmt-windows.exe
19M Jun  8 10:18 query-engine-windows.exe
```

**Comment by kivi** [comment]
These are the contents of a production build. The schema is configured for a Postgressql

```bash
root@1cc811fe5550:/app/node_modules# du -h -d 2 ./@prisma | grep M
1.5M    ./@prisma/sdk
1.2M    ./@prisma/engines/download
73M     ./@prisma/engines
1.3M    ./@prisma/client/runtime
2.6M    ./@prisma/client/generator-build
3.9M    ./@prisma/client
79M     ./@prisma
root@1cc811fe5550:/app/node_modules# du -h -d 2 ./prisma | grep M
103M    ./prisma/node_modules/@prisma
103M    ./prisma/node_modules
1.3M    ./prisma/prisma-client/runtime
2.6M    ./prisma/prisma-client/generator-build
3.9M    ./prisma/prisma-client
3.4M    ./prisma/build/public
7.5M    ./prisma/build
155M    ./prisma
```

`ls -lha prisma/node_modules/\@prisma/engines/`
```sh
total 101M
-rw-r--r-- 1 root root  537 Jun  7 17:52 README.md
drwxr-xr-x 2 root root 4.0K Jun  7 17:53 dist
drwxr-xr-x 2 root root 4.0K Jun  7 17:53 download
-rwxr-xr-x 1 root root  19M Jun  7 17:53 introspection-engine-debian-openssl-1.1.x
-rwxr-xr-x 1 root root  33M Jun  7 17:53 migration-engine-debian-openssl-1.1.x
-rw-r--r-- 1 root root  646 Jun  7 17:52 package.json
-rwxr-xr-x 1 root root 8.3M Jun  7 17:53 prisma-fmt-debian-openssl-1.1.x
-rwxr-xr-x 1 root root  42M Jun  7 17:53 query-engine-debian-openssl-1.1.x
```

`ls -lha \@prisma/engines`
```
total 71M
drwxr-xr-x  4 root root 4.0K Jun  7 17:53 .
drwxr-xr-x 11 root root 4.0K Jun  7 17:53 ..
-rw-r--r--  1 root root  537 Jun  7 17:52 README.md
drwxr-xr-x  2 root root 4.0K Jun  7 17:53 dist
drwxr-xr-x  2 root root 4.0K Jun  7 17:53 download
-rwxr-xr-x  1 root root  18M Jun  7 17:53 introspection-engine-debian-openssl-1.1.x
-rwxr-xr-x  1 root root  21M Jun  7 17:53 migration-engine-debian-openssl-1.1.x
-rw-r--r--  1 root root  661 Jun  7 17:52 package.json
-rwxr-xr-x  1 root root 7.3M Jun  7 17:53 prisma-fmt-debian-openssl-1.1.x
-rwxr-xr-x  1 root root  25M Jun  7 17:53 query-engine-debian-openssl-1.1.x
```




The initial Comment was based on a fresh installed Blitz.js project, wich comes with Prisma. I am using Windows 10, so binaries of Prisma for Windows were also included.

This current comment is showing directory sizes of a real life project in production. I used `node:14-buster-slim` as the base image.

235MB, so 15MB less than initially said. Still bulky imho.

**Comment by kivi** [comment]
As a comparison I just downloaded the [starter project](https://www.prisma.io/docs/getting-started/quickstart) on windows and installed node_modules with `yarn`

```
146M    node_modules/@prisma

3.8M    node_modules/@prisma/client
142M    node_modules/@prisma/engines
0       node_modules/@prisma/engines-version


42M     node_modules/prisma

7.5M    node_modules/prisma/build
16K     node_modules/prisma/install
44K     node_modules/prisma/preinstall
3.8M    node_modules/prisma/prisma-client
0       node_modules/prisma/scripts

```

188MB, which is 62MB smaller than I said in the beginning. But it is just the starter and therefore not much representable for a real world project. Still too big in my opinion and even if we would reduce 15MB by building on Linux (here I am using Windows again and it is not a production build)

**Comment by janpio** [comment]
There are a few problems with these projects:

- https://github.com/prisma/prisma/issues/7520#issuecomment-857199228: The Windows project seems to contain all the Engines twice (once in an unexpected `.cache` folder) which on Linux and macOS is not _inside_ the project but a global location. We might be able to optimize that away. 
- The Linux production build containing `@prisma/engines` twice is also totally unnecessary and should not be the case really: https://github.com/prisma/prisma/issues/7520#issuecomment-857213910 In general the _production_ build should not include the CLI at all in normal circumstances, we might need to look into why Blitz decided to include the CLI as a dependency and not a development dependency - but this might make total sense based on their use case. 
- https://github.com/prisma/prisma/issues/7520#issuecomment-857221113 Finally the Windows starter project also double the size it should be - can you check if there is also a `.cache` directory that just contains the identical Engines?

**Comment by janpio** [comment]
Yeah, `.cache` is the zipped archives downloaded with the checksums etc, while the unpacked variation is in the real node_modules folders. As mentioned before in Linux and Mac that cache folder is outside of the project, so does not affect you. The library we are using to manage these cache folders defaults to _this_ behavior on Windows unfortunately. We might need to investigate if we can change/override that and see if we need the cache folder in the first place.

**Comment by janpio** [comment]
> I wonder if it would be possible to have a very tiny production version, with just one engine or a list of engines of your choice and no tools like introspection.

If you put the Prisma CLI dependency as a dev dependency, you should already only have the Query Engine in your production deployment. That is what happens for all serverless deployments for example when configured correctly. Still ~45 MB - but that is the size of the Query Engine right now. 

This should also happen for the starter project if you do not install the dev dependencies, e.g. with `npm ci` or `npm install --production`. Is that not the cas?

> I have installed on Linux node v14.17.0 and used `yarn` for the starter project. Here you can see the file size, which is in total 160MB still a lot. How about set a max to 25MB?

Without doing magic, this just will not be possible. The files have a certain size, and that will be almost impossible to bring under 25MB in total.

To be honest it is also not something we optimize for right now. We optimize for developer experience and usability when using Prisma Client and the CLI - so we are making certain trade offs in that direction.

One of these is for example that the Query Engine will be duplicated in your project, once in Prisma CLI and once in Prisma CLient. That is intentional for the reasons outlined above (that you can actually deploy a project without the CLI really and just include the Client).

**Comment by kivi** [comment]
> What is your use case that you worry about the size of the dependencies so much?

My docker has a total size of 1.2 GB. That affects quotas, transfer time and build time.
Sizes of my node_modules vary between 600MB and 950MB and in all of them Prisma is the heaviest consumer.

**Comment by kivi** [comment]
There is more Prisma cache. I am playing around with Dockerfile and trying to figure out how to reduce total size of the image. And voila ... Prisma resides also **outside** of `node_modules`

```
du -h -d 1 /root/.cache/prisma/master/ | grep M
71M     /root/.cache/prisma/master/c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d
101M    /root/.cache/prisma/master/18095475d5ee64536e2f93995e48ad800737a9e4
171M    /root/.cache/prisma/master/
```

**Comment by janpio** [comment]
Ha yes, that is the Linux behavior I mentioned. I forgot that this might apply to your Docker image indeed.

It might be worth to get an env var or that triggers a cleanup of this after it has been used. In normal situations this is not a problem to have these around, as we expect people to create another Prisma project most of the time - and then this saves you the additional download of these files again. But in your case that is probably not the case, is it?

**Comment by nikolaz111** [comment]
I think trying to make the final build as small as possible is part of the developer experience. In my case, now I'm messing around with webpack in order to eliminate the duplicate binaries that prisma is generating in the final build. AWS wont allow for bigger builds in lambdas.

**Comment by nikolaz111** [comment]
By the way I'm using prisma as a devDependency and it is still included in the final build.

**Comment by janpio** [comment]
Then something should be changed about that build process. A normal `npm install` also installs dev dependencies unless some additional tooling is used, and that is up for you to figure out and apply. Vercel and Netlify (who also deploy to AWS Lambda) do that by default, most versions of Serverless Framework help with that as well.

**Comment by iRoachie** [comment]
Hey @janpio is there any plans to make a smaller `rhel-openssl-1.0.x` binary? 

My use case is that I work with AWS Lambda where the total size of code + dependencies actually affects the start time for invocations.

On a brand new project using `rhel-openssl-1.0.x`, the size of `libquery_engine-rhel-openssl-1.0.x.so.node` is 43.5mb.

**Comment by janpio** [comment]
Generally yes, but it is not easily possible unfortunately. If you have an experiment that shows the clear performance impact of this one ~43MB size file, please post it - that would make it easier for us to put priority on working on this.

**Comment by RomainBillot** [comment]
```Dockerfile
# Builder
FROM node:16-alpine AS builder

WORKDIR /opt/api

COPY . .
RUN npm i
RUN npm run build
RUN npm run prisma:generate:ci

# Runner
FROM node:16-alpine AS runner

WORKDIR /opt/api
ENV NODE_ENV production

# take build output
COPY --from=builder /opt/api/dist ./dist
# take prisma files
COPY ./prisma ./prisma

COPY package*.json ./

RUN npm ci

# take prisma client
COPY --from=builder /opt/api/node_modules/@prisma/client ./node_modules/@prisma/client

USER node

EXPOSE 3000

CMD [ "npm", "run", "start" ]
```

This image is >500mb in major part due to prisma.

Here is the content of my node_modules/@prisma:
![Screenshot 2021-11-30 at 11 30 54](https://user-images.githubusercontent.com/93139728/144030980-3c2ed89a-57f1-4289-b482-603eda71384e.png)

And the content of node_modules/prisma:
![Screenshot 2021-11-30 at 11 32 08](https://user-images.githubusercontent.com/93139728/144031151-18cce9dc-d5c8-4bab-b736-f6a601c85caf.png)

These two packages are taking 82% of my node_modules size. Insane, no?

**Comment by EldinHb** [comment]
> ```Dockerfile
> 
> # Builder
> 
> FROM node:16-alpine AS builder
> 
> 
> 
> WORKDIR /opt/api
> 
> 
> 
> COPY . .
> 
> RUN npm i
> 
> RUN npm run build
> 
> RUN npm run prisma:generate:ci
> 
> 
> 
> # Runner
> 
> FROM node:16-alpine AS runner
> 
> 
> 
> WORKDIR /opt/api
> 
> ENV NODE_ENV production
> 
> 
> 
> # take build output
> 
> COPY --from=builder /opt/api/dist ./dist
> 
> # take prisma files
> 
> COPY ./prisma ./prisma
> 
> 
> 
> COPY package*.json ./
> 
> 
> 
> RUN npm ci
> 
> 
> 
> # take prisma client
> 
> COPY --from=builder /opt/api/node_modules/@prisma/client ./node_modules/@prisma/client
> 
> 
> 
> USER node
> 
> 
> 
> EXPOSE 3000
> 
> 
> 
> CMD [ "npm", "run", "start" ]
> 
> ```
> 
> 
> 
> This image is >500mb in major part due to prisma.
> 
> 
> 
> Here is the content of my node_modules/@prisma:
> 
> ![Screenshot 2021-11-30 at 11 30 54](https://user-images.githubusercontent.com/93139728/144030980-3c2ed89a-57f1-4289-b482-603eda71384e.png)
> 
> 
> 
> And the content of node_modules/prisma:
> 
> ![Screenshot 2021-11-30 at 11 32 08](https://user-images.githubusercontent.com/93139728/144031151-18cce9dc-d5c8-4bab-b736-f6a601c85caf.png)
> 
> 
> 
> These two packages are taking 82% of my node_modules size. Insane, no?
> 
> 
> 
> Edit: This is a real issue for us. We are charged according to image size, we followed best practise to reduce size (use alpine image, only install production dependency, etc..), but that only makes a small difference because prisma is way to heavy. I understand the need of an optimized binary built with Rust, but that shouldn't affect size that way.
> 
> 
> 
> Or at least we should be able to specify with binary we need like, only migration or introspection and query engine.

I would also like to know what we can safely delete ourselves to keep the size down.

**Comment by kivi** [comment]
@RomainBillot, @EldinHb 

Yes it is an annoying fact, that it needs so much space.
But you could make use of multi stage builds: https://docs.docker.com/develop/develop-images/multistage-build/

Here is a little more complex example than yours: https://github.com/kivi/blitz-docker-example/blob/main/Dockerfile

I am starting with "base" stage and finally copying from build stage only what I need to for final stage. And I am even deleting some apt packages from base. And deleting npm cache and devDependencies manually.
https://github.com/kivi/blitz-docker-example/blob/main/Dockerfile#L19

With buster-slim (maybe outdated for your use cage, so check out: https://hub.docker.com/_/node/) I got better results than for alpine, plus I think I needed dependencies from a more complete linux.

**Comment by keponk** [comment]
is there more documentation about what items could we manually remove? I'm strugling with >200MB in the prod build using multistage docker.

```
/app/node_modules # du -h .prisma/
8.0K	.prisma/client/deno
40.1M	.prisma/client
40.1M	.prisma/
/app/node_modules # du -sh .prisma/
40.1M	.prisma/
/app/node_modules # du -sh prisma/
53.4M	prisma/
/app/node_modules # du -sh @prisma/
125.6M	@prisma/
```

the `libquery_engine-linux-musl.so.node` is triplicated in each of these 3 folders. Does someone have a link on docs that say which could i safely remove in a prod build so I can at least remove them manually in the dockerfile? Such documentation could be added to the official docs and/or disclaimer.

**Comment by janpio** [comment]
We will fix the problem soon, working on that right now.

**Comment by pencilcheck** [comment]
<img width="1276" alt="Screenshot 2023-01-19 at 4 29 30 AM" src="https://user-images.githubusercontent.com/116532/213443255-2caa7d09-5c7f-4386-91f5-103f1e824d58.png">
Why is prisma bundled with prisma/client? I specifically put prisma in dev dep? Also the size is huge it is exceeding the upload limit for vercel

**Comment by janpio** [comment]
Yes, that is roughly the expected current size of Prisma Client with the Query Engine @pencilcheck.

**Comment by janpio** [comment]
As written before, we have reduced the size of our engines a lot and as far as we know, this solved this problem for most our user and their use cases. Hence I am closing this issue for now.

If you and your project are still having problems because of the remaining size of our engines, please open a new issue and describe your situation - we are happy to take a look and hopefully fix that. Thanks!
