### ISSUE TITLE
Azure Functions Linux: ENV variable values not available to Node-API Query Engine (e2e test `azure-functions-linux`)

### ISSUE THREAD

**Issue by williamluke4** [prisma/prisma#7522]
- ENV VARS are present in Node but are not present on the rust side

### Current Workaround
Pass the connection string to the Client Constructor
```ts
const client = new PrismaClient({
	datasources: {
		db: {
			url: process.env.AZURE_FUNCTIONS_LINUX_PG_URL,    
		},
	}  
})
```

**Comment by janpio** [comment]
We can remove the workaround now from the tests and then confirm this works @williamluke4

**Comment by janpio** [comment]
Fixed via https://github.com/prisma/prisma-engines/pull/2004
