### ISSUE TITLE
Prisma Multiple Data Sources Setup on Heroku Error [generated, binaryTargets]

### ISSUE THREAD

**Issue by kfbfarley** [prisma/prisma#7525]
Hey there,

I am having a problem while trying to use multiple data sources with Prisma.

Everything works fine on localhost, but it's not working on Heroku.

 
This is my **client** Postgresql schema
```
generator client {
  provider = "prisma-client-js"
  output   = "generated/client"
  binaryTargets = ["native"]
}

datasource server {
  provider = "postgresql"
  url      = env("CLIENT_URL")
}
```
This is my **server** Postgresql schema
```
generator client {
  provider = "prisma-client-js"
  output   = "generated/server"
  binaryTargets = ["native"]
}

datasource server {
  provider = "postgresql"
  url      = env("SERVER_URL")
}
```
This is what comes up on the Heroku console logging section

```
PrismaClientInitializationError2 [PrismaClientInitializationError]: Query engine binary for current platform "debian-openssl-1.1.x" could not be found
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/app/prisma/generated/server_schema/runtime/query-engine-debian-openssl-1.1.x")
You already added the platform "native" to the "generator" block but something went wrong. That's suboptimal.
```

**Comment by janpio** [comment]
Thanks for the issue. Can you tell us a bit more about the project? What Prisma version are you using? How is it set up? How do you deploy it? 

Can you maybe easily create a minimal reproduction in a new repository that only includes the required things to be able to reproduce this error? We would love to see the error on our own deployment so we can debug it.

**Comment by janpio** [comment]
Ping @kfbfarley

**Comment by kfbfarley** [comment]
> Ping @kfbfarley

I'll check the code again, will get back to you to check if the problem persists.

**Comment by pantharshit00** [comment]
I am going to close this for now @kfbfarley 

Please comment if this is still relevant for you
