### ISSUE TITLE
Help us improve Prisma by sharing your SQL schemas 🙏

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#757]
Hey everyone 👋 

In an effort of making Prisma 2 available for existing applications (_brownfield_), **we're currently collecting database schemas (SQL)** 🕵 

It would be a tremendous help for us if you could share a database schema of any project you're working on, or have been working on in the past! This can be a _side-project_ or a _production application_, **any schema is an incredibly helpful contribution to make Prisma more resilient in brownfield projects**!

Please submit your database schemas to [schemas@prisma.io](mailto:schemas@prisma.io).

---

Also note that **we're happily signing NDAs if your schemas need to be treated confidently**! If you like Prisma and want to see it succeed, please consider sharing your schema or talking to your boss if that's needed to be able to share your DB schema! :slightly_smiling_face:

---

Thanks for helping us making Prisma 2 better 🙌

**Comment by wtrocki** [comment]
Would some schemas will be made public? 
Asking as there is market for testing other tools using public schemas. Example: https://github.com/graphql/graphql-js/issues/2172

**Comment by henrykempo** [comment]
The best references I have found for large schemas are Spectrum and Shopify. I know Graphql and not Prisma schemas, perhaps an adaptation of them would be helpful to the community?

**Comment by wtrocki** [comment]
Well known list of "graphql-schemas" https://github.com/APIs-guru/graphql-apis

**Comment by pantharshit00** [comment]
> Well known list of "graphql-schemas" APIs-guru/graphql-apis

We actually want database schemas :)

**Comment by gregbenner** [comment]
If someone translated a wordpress schema to wordpress that would be a game changer. I might try if I get the time :)

**Comment by tvvignesh** [comment]
@divyenduz I am building my application using Prisma 2 and I have built out all the schemas for the same and will be launching it to public on Dec 30th (More here: https://medium.com/timecampus/timecampus-goes-live-on-december-30th-2019-mark-your-calendars-more-info-below-1cd1a113137c) 

Once that is done, I will share the schema across to your team privately.

**Comment by Sm03leBr00t** [comment]
I have two sideprobjects.
The first one was a chat I wanted to do, the second one is a rowing competition project I am working on right now.
```
type User {
  id: ID! @id
  name: String! @unique
  email: String! @unique
  channelSubs: [Channel!]! @relation(name: "ChannelRelation",link: INLINE)
}

type Message {
  id: ID! @id
  text: String!
  channel: Channel! @relation(link: INLINE)
  author: User! @relation(link: INLINE)
}

type Channel {
  id: ID! @id
  name: String! @unique
  followers: [User!]! @relation(name: "FollowRelation",link: INLINE)
  messages: [Message!]!
}
```
and this one :
```
type User {
  id: ID! @id
  name: String!
  email: String! @unique
  birthDate: DateTime!
  adminClub: Club @relation(name: "Admin")
  club: Club @relation(name: "Member")
}

type Club {
  id: ID! @id
  name: String!
  admins: [User!]! @relation(name: "Admin",link: INLINE)
  members: [User!]! @relation(name: "Member",link: INLINE)
  competitions: [Competition!]! 
}

type Competition {
  id: ID! @id
  name: String!
  club: Club! @relation(link: INLINE)
  start: DateTime!
  end: DateTime!
  races: [Race!]! @relation(link: INLINE)
}

type Race {
  id: ID! @id
  sortId: Int @default(value: 0)
  category: Category! @relation(link: INLINE)
  boats: [Boat!]! @relation(link: INLINE)
  run: [Run!]! @relation(link: INLINE)
}

type Run {
  id: ID! @id
  sortId: Int @default(value: 0)
  boats: [Boat!]! @relation(link: INLINE)
}

type Boat {
  id: ID! @id
  club: Club! @relation(link: INLINE)
  racers: [User!]! @relation(link: INLINE)
}

type Category {
  id: ID! @id
  name: String! @unique
  birthYear: DateTime!
  creator: User! @relation(link: INLINE)
}
```

I hope that helps and that the cool T-shirts are looking good :D Love your effort and hope you guys keep up the extraoridinary work :+1:

**Comment by dohaicuong** [comment]
I currently working on a project which have a service with similar functionality like google form.
Hope this schema helps!

Wait to see prisma2 in our production :)

```
type Form {
  id: ID! @id

  title: String
  description: String

  reports: [Report!]
  cards: [FormCard!] @relation(name: "FormCard")
}

type FormCard {
  id: ID! @id

  order: Int!
  card: Card @relation(name: "CardInFormCard")

  form: Form! @relation(name: "FormCard")
}

type Card {
  id: ID! @id

  title: String
  grid: Int! @default(value: 12)

  formCard: [FormCard!] @relation(name: "CardInFormCard")
  fields: [CardField!] @relation(name: "CardField")
}

type CardField {
  id: ID! @id

  order: Int!
  field: Field @relation(name: "FieldInCardField")

  cards: [Card!] @relation(name: "CardField")
  groups: [Field!] @relation(name: "GroupFields")
}

type Field {
  id: ID! @id

  grid: Int! @default(value: 12)
  type: FieldType! @default(value: TEXT_FIELD)

  label: String!
  name: String

  rows: Int
  rowsMax: Int
  groupFields: [CardField!] @relation(name: "GroupFields")

  value: String
  valueFrom: String
  options: [FieldOption!]

  cardField: [CardField!] @relation(name: "FieldInCardField")
}

enum FieldType {
  INFO_FIELD
  TEXT_FIELD
  TEXT_AREA_FIELD
  SELECT_FIELD
  SWITCH_FIELD
  FILE_FIELD
  DATETIME_FIELD
  GROUP_FIELD
}
type FieldOption {
  id: ID! @id

  label: String!
  value: String!
}
```

**Comment by Sm03leBr00t** [comment]
Do we still get the shirts 😅
