### ISSUE TITLE
SQL Server Introspection lists XML indices which are then rejected by schema validation

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#7571]
### Bug description

Introspection detects indices on XML columns and renders them into the datamodel. When re-parsing the datamodel the datamodel validation rejects it since it does not allow for indices on XML on SQLServer. 

### How to reproduce

Introspection CI adventureworks2016 db exhibits this behaviour.  

### Expected behavior

Until we have PSL support for special indices, introspection should just ignore XML indices. 

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

2.24

**Comment by janpio** [comment]
Can you please check this is fixed in Introspection and Migration CI @do4gr? Thanks.
