### ISSUE TITLE
Running `prisma generate` doesn't install prisma client 2.24.x

### ISSUE THREAD

**Issue by m-abdelwahab** [prisma/prisma#7579]
### Bug description

Running `prisma generate` should install `@prisma/client` if not present

### How to reproduce

1. Install the [quickstart](https://www.prisma.io/docs/getting-started/quickstart) example from the quickstart guide.
2. Remove `@prisma/client` from the dependencies
3. Run `npm install`
4. Run `npx prisma generate`

This is the output:

```bash
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (2.24.1) to ./node_modules/prisma/prisma-client in 130ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

```

However, `@prisma/client` doesn't get installed.

### Expected behavior

`@prisma/client` should be automatically installed

https://user-images.githubusercontent.com/27310414/121517584-d8681a80-c9ef-11eb-92d3-2fc6c7612d57.mp4

### Prisma information

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}


```

### Environment & setup

SQLite,  Mac OS Big Sur version 11.4 

### Prisma Version

```
prisma               : 2.24.1
@prisma/client       : Not found
Current platform     : darwin
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0

```

**Comment by janpio** [comment]
I can confirm this :(

**Comment by Jolg42** [comment]
@millsp I think it's from your recent change in `getPrismaClientDir` function which is using your new `findUp` method.

https://github.com/prisma/prisma/blob/d21072bc450bf638340f3b3257cb82d8385402b3/src/packages/sdk/src/predefinedGeneratorResolvers.ts#L28-L46

My best guess is that it finds the bundled `prisma-client` in CLI and then never install `@prisma/client` here https://github.com/prisma/prisma/blob/d21072bc450bf638340f3b3257cb82d8385402b3/src/packages/sdk/src/predefinedGeneratorResolvers.ts#L65

**Comment by MARVELGARR** [comment]
i solved it by going in to node_module and deliting prisma/client folder 
![step 3](https://github.com/prisma/prisma/assets/75810831/9b407891-f111-45ec-8926-1ba241c80fac)
![step1](https://github.com/prisma/prisma/assets/75810831/ca475109-de1b-40d3-9ce8-63404cba5bf2)
![step2](https://github.com/prisma/prisma/assets/75810831/b1423c11-7dc1-487b-b2c1-671cc499d58e)
and now doing the prisma generate .. it worked
