### ISSUE TITLE
Prisma Client is returning undefined for all but one model.

### ISSUE THREAD

**Issue by krishnapaul242** [prisma/prisma#7625]
### Bug description

I have setup a ReST API project from [typescript-express-starter](https://www.npmjs.com/package/typescript-express-starter) with Prisma as ORM. It has a basic 'user' model and authentication setup. It works well but when I followed the given 'user' model and created two more models. These are generated in database and types too, but when I call the model methods from Prisma Client it returning undefined. I have also asked it in [stackoverflow](https://stackoverflow.com/questions/67774292/how-to-fix-prisma-client-getting-undefined-for-custom-model) but no working answers. Here is the [Github Repo](https://github.com/krishnapaul242/server-16ab/). It is containerized. 

### Expected behavior

The request to the localhost:3000/offers and localhost:3000/users should be similar.

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id       Int    @id @default(autoincrement())
  email    String @unique
  password String
}

model Product {
  id              Int     @id @default(autoincrement())
  name            String  @unique
  veg             Boolean
  price           Int
  image           String
  discountedPrice Int
  description     String
}

model Offer {
  id    Int    @id @default(autoincrement())
  name  String
  image String
}
```

### Environment & setup

I am running it in docker container with the help of docker-compose.
If you're trying to run prisma commands in docker container, make sure to change the hostname from 'mysql' to 'localhost' in the .env file.

### Prisma Version

```
prisma               : 2.23.0
@prisma/client       : 2.24.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
```

**Comment by pantharshit00** [comment]
@krishnapaul242 

Sorry for late reply here. Can you please fill out the how to reproduce section? Simply tell us which route to look at otherwise your codebase looks decently sized. 

Also, try this again with the latest version.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this solved.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
