### ISSUE TITLE
Query engine binary for current platform \"linux-musl\" could not be found.

### ISSUE THREAD

**Issue by babdo-dev** [prisma/prisma#7627]
Hi there,
I got the following error after executing a query in my dockersized application. 

```
Query engine binary for current platform \"linux-musl\" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in \"/usr/src/app/node_modules/@prisma/client/runtime/query-engine-linux-musl\")

Searched Locations:

  /usr/src/app/node_modules/.prisma/client
  /Users/babdo/coding/project/node_modules/@prisma/client
  /usr/src/app/node_modules/@prisma/client
  /usr/src/app/node_modules/.prisma/client
  /usr/src/app/prisma
  /tmp/prisma-engines
  /usr/src/app/node_modules/.prisma/client

You already added the platform \"native\" to the \"generator\" block
in the \"schema.prisma\" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.
Please create an issue at https://github.com/prisma/prisma/issues/new
```

My Docker file:
```
FROM node:14.17-alpine
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install
COPY . .
EXPOSE 4000
CMD ["npm", "start"]
```

My prisma client generation:
```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "linux-musl"]
}
```

- Using MacOs Big Sur Version 11.4
- prisma: "^2.24.1",
- @prisma/client": "^2.24.1

**Comment by babdo-dev** [comment]
I just found out adding a `RUN npx prisma generate` to the Docker file resolved the issue. Not sure if that a valid approach or how I could resolve in a better way.

**Comment by ryands17** [comment]
Either that or include copying your `prisma` folder before `npm install` as it automatically runs `prisma generate`.

**Comment by janpio** [comment]
(Right now `npm install` would also try to run `prisma generate`, but fail as there is not Prisma schema present that can be used to generate a Client - which includes the binaries. You _should_ have gotten a warning message during `npm install` about this.)
