### ISSUE TITLE
Environment variable not found

### ISSUE THREAD

**Issue by oceandrama** [prisma/prisma#7629]
### Bug description

Since version `2.24.0` I got next error while making requests to my graphql server
```
"Error: Context creation failed: ",
"Invalid `prisma.user.findUnique()` invocation:",
"  error: Environment variable not found: DATABASE_URL.",
"  -->  schema.prisma:3",
"   | ",
" 2 |   provider = \"postgresql\"",
" 3 |   url      = env(\"DATABASE_URL\")",
"   | ",
```
Commands like `prisma migrate` works correctly

I have next file structure
```
├── prisma
│   └── schema.prisma
├── src
│   └── server.ts
├── .env
```
In version `2.23.0` everything works as expected

### How to reproduce

1. Create graphql-server with `apollo-server` and `prisma`
1. Add `PrismaClient` to context
1. Make graphql request

### Prisma information

My `schema.prisma` file starts like this

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["orderByRelation", "selectRelationCount"]
}
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js: 14.15.4
- apollo-server-express: 2.25.1

### Prisma Version

```
2.24.0
```

**Comment by janpio** [comment]
Can you share a minimal reproduction of your problem? Having a ready to use example would make it much easier for us to reproduce and then hopefully fix. Thanks.

**Comment by ljosberinn** [comment]
I'm seeing the same issue beginning with version 2.24.0. In my case, it's due to different behaviour leading up to `/sdk/utils/tryLoadEnvs`.

v2.23.0:

![image](https://user-images.githubusercontent.com/29307652/121790856-2fcedc00-cbe4-11eb-9a66-7cd26e161a4c.png)
![image](https://user-images.githubusercontent.com/29307652/121790863-36f5ea00-cbe4-11eb-8736-5487d20aa2ca.png)

Notice the `schemaEnvPath` being `'C:\\Users\\gerr.it\\Desktop\\dev\\keystone-heroes\\packages\\@keystone-heroes\\db\\.env'` and debug statements being present.

v2.24.0

![image](https://user-images.githubusercontent.com/29307652/121790923-b7b4e600-cbe4-11eb-82cc-a2eac31e13b1.png)
![image](https://user-images.githubusercontent.com/29307652/121790919-aff54180-cbe4-11eb-8752-31c1d0322528.png)

Notice the line difference which in the code screenshot indicating the changes between the versions, although this function wasnt touched and how `schemaEnvPath` now is `'C:\\Users\\gerr.it\\Desktop\\dev\\keystone-heroes\\node_modules\\.prisma\\client\\packages\\@keystone-heroes\\db\\.env'`.

It's late right now, I'll try to whip up a repro tomorrow.

**Comment by ljosberinn** [comment]
looks like this change broke it: https://github.com/prisma/prisma/pull/7111/files#diff-50adf06d2a48eab1e1d445e88452099acac1e58a1edb3115531a96c1a5e3b264L55

**Comment by janpio** [comment]
Yes, that was quite a high risk change where it seems we got a few things wrong unfortunately 😢 If you can get to a reproduction, we will prioritize looking into and hopefully fixing that. Right now we are a bit lost.

**Comment by ljosberinn** [comment]
I've added a reduced version of my branch [here](https://github.com/ljosberinn/keystone-heroes/tree/prisma-repro) with a short readme. Let me know if you run into issues setting it up, I hope I've thought of everything.

**Comment by janpio** [comment]
I can confirm the bug in your reproduction:

```
C:\Users\Jan\Documents\throwaway\keystone-heroes\packages\@keystone-heroes\wcl (prisma-repro -> origin)
λ yarn introspection
yarn run v1.22.0
$ ts-node -r tsconfig-paths/register src/queries/introspection.ts --project tsconfig.json
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables not found at C:\Users\Jan\Documents\throwaway\keystone-heroes\packages\@keystone-heroes\wcl\packages\@keystone-heroes\db\.env +4ms
  prisma:tryLoadEnv No Environment variables loaded +1ms
  prisma:tryLoadEnv Environment variables not found at null +2ms
  prisma:tryLoadEnv Environment variables not found at C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\.prisma\client\packages\@keystone-heroes\db\.env +1ms
  prisma:tryLoadEnv No Environment variables loaded +0ms
  prisma:client clientVersion: 2.24.1 +0ms
  prisma:client:napi internalSetup +0ms
  prisma:client Prisma Client call: +443ms
  prisma:client prisma.wCLAuth.findFirst(undefined) +3ms
  prisma:client Generated request: +2ms
  prisma:client query {
  prisma:client   findFirstWCLAuth {
  prisma:client     id
  prisma:client     token
  prisma:client     expiresAt
  prisma:client   }
  prisma:client }
  prisma:client  +2ms
  prisma:client:napi Search for Query Engine Library in C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\.prisma\client +454ms
  prisma:client:napi loadEngine +2ms
  prisma:client Error: error: Environment variable not found: DATABASE_URL.
  prisma:client   -->  schema.prisma:8
  prisma:client    |
  prisma:client  7 |   provider = "postgresql"
  prisma:client  8 |   url      = env("DATABASE_URL")
  prisma:client    |
  prisma:client
  prisma:client Validation Error Count: 1
  prisma:client     at NAPIEngine.loadEngine (C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\@prisma\client\runtime\index.js:22975:21)
  prisma:client     at NAPIEngine.internalSetup (C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\@prisma\client\runtime\index.js:22909:18)
  prisma:client     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  prisma:client     at NAPIEngine.start (C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\@prisma\client\runtime\index.js:23055:7)
  prisma:client     at NAPIEngine.request (C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\@prisma\client\runtime\index.js:23135:9)
  prisma:client     at cb (C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\@prisma\client\runtime\index.js:35193:26)
  prisma:client     at Object.getGqlClient (C:\Users\Jan\Documents\throwaway\keystone-heroes\packages\@keystone-heroes\wcl\src\client.ts:49:18)
  prisma:client     at loadSchema (C:\Users\Jan\Documents\throwaway\keystone-heroes\packages\@keystone-heroes\wcl\src\queries\introspection.ts:9:18) +24ms
PrismaClientInitializationError2 [PrismaClientInitializationError]:
Invalid `prisma.wCLAuth.findFirst()` invocation:


  error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:8
   |
 7 |   provider = "postgresql"
 8 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
    at cb (C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\@prisma\client\runtime\index.js:35229:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.getGqlClient (C:\Users\Jan\Documents\throwaway\keystone-heroes\packages\@keystone-heroes\wcl\src\client.ts:49:18)
    at loadSchema (C:\Users\Jan\Documents\throwaway\keystone-heroes\packages\@keystone-heroes\wcl\src\queries\introspection.ts:9:18) {
  clientVersion: '2.24.1',
  errorCode: undefined
}
Done in 6.76s.
```

I also see a duplication of paths when trying to read the `.env` file: `prisma:tryLoadEnv Environment variables not found at C:\Users\Jan\Documents\throwaway\keystone-heroes\packages\@keystone-heroes\wcl\packages\@keystone-heroes\db\.env +4ms`. The file is actually located at `C:\Users\Jan\Documents\throwaway\keystone-heroes\packages\@keystone-heroes\db\.env` of course (or `...packages\@keystone-heroes\env\.env` where I created it and then copied it over to `db`).

The other path `  prisma:tryLoadEnv Environment variables not found at C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\.prisma\client\packages\@keystone-heroes\db\.env` is is trying to read doesn't make any sense - no `.env` file anywhere in `C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\.prisma\client`.

With 2.23.0 the command will indeed work correctly and Prisma searches in another folder for the `.env`:

```
λ yarn introspection
yarn run v1.22.0
$ ts-node -r tsconfig-paths/register src/queries/introspection.ts --project tsconfig.json
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\keystone-heroes\packages\@keystone-heroes\db\.env +3ms
  prisma:tryLoadEnv Environment variables not found at null +2ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\keystone-heroes\packages\@keystone-heroes\db\.env +1ms
[dotenv][DEBUG] "DATABASE_URL" is already defined in `process.env` and will not be overwritten
  prisma:client clientVersion: 2.23.0 +0ms
  prisma:client:napi internalSetup +0ms
  prisma:client Prisma Client call: +224ms
  prisma:client prisma.wCLAuth.findFirst(undefined) +2ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findFirstWCLAuth {
  prisma:client     id
  prisma:client     token
  prisma:client     expiresAt
  prisma:client   }
  prisma:client }
  prisma:client  +1ms
  prisma:client:napi Search for Query Engine Library in C:\Users\Jan\Documents\throwaway\keystone-heroes\node_modules\.prisma\client +230ms
  prisma:client:napi loadEngine +1ms
  prisma:client Error: error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  prisma:client   -->  schema.prisma:8
  prisma:client    |
  prisma:client  7 |   provider = "postgresql"
  prisma:client  8 |   url      = env("DATABASE_URL")
  prisma:client    |
  ...
 ```

**Comment by oceandrama** [comment]
@janpio Yes, I use Yarn Workspaces in my project
