### ISSUE TITLE
issue with connection pool ?

### ISSUE THREAD

**Issue by mdespriee** [prisma/prisma#7644]
### Bug description

Hello,

I'm trying to diagnose a connection pool problem we have in production.
The DB is a timescaleDB, but viewed from Prisma, it's simply a postgresql. 
(The DB is hosted at a DBaaS provider, and we don't have as much logs and diag as we would like unfortunately).

The symptom is the following: after a few hours of uptime, we start to see these errors growing:
```
Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter (...). Current limit: 25, amount of connections currently in use: 16.
```
First, I don't see why there's a timeout fetching a connection, since the max is not reached.
And then the connection pool seems already pretty oversized to me: 600 query/mn, ~500ms per query in avg, and we have 2 parallel instances. So 25 should be plenty.

The problem just worsen and worsen until we reboot the service, and everything goes back to normal.

It looks like some connections are not re-used, as if they were waiting for the server or something. What can I do, application-side, to better diagnose the problem ?

### Prisma information

not  query specific

### Environment & setup

- docker based, 2 containers running in AWS ECS Fargate.
- timescaleDB (postgresql 12.7)
- Node.js 12.13

### Prisma Version

```
@prisma/cli          : 2.15.0
@prisma/client       : 2.15.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e51dc3b5a9ee790a07104bec1c9477d51740fe54 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.340.0
```

**Comment by Sytten** [comment]
You have a very old version of prisma, if you search for issues on the pool many have been fixed since then. You can check https://github.com/prisma/prisma/issues/6329#issuecomment-811097812 for more details. I suggest you update prisma first and try again to reproduce.

**Comment by mdespriee** [comment]
Hello Sytten, 
Thanks for your feedback. We updated to version 2.24.1, and still have the problem.

It seems it's leaking connections.
The scenario is always the same. It starts with some DB overload (or any other glitch), then connections start to stack up, then it seems the pool becomes full of connections that are never reused. And the system never recovers naturally from this. 

As an example, here's the volume of logs "Timed out fetching a new connection from the connection pool".
![image](https://user-images.githubusercontent.com/1590580/122539797-492eb880-d028-11eb-844a-dbffe163db95.png)

If you have any recommendation to better trace/understand what's going on, we're interested !

**Comment by Sytten** [comment]
Do you work in a serverless environment or in a "normal" environment.
If you have a big spike in demand that takes up all the connections they are not recycled currently I am pretty sure.
In my case I had the inverse problem because in serverless connections are closed all the time.
I opened an issue I will fix it for the next release (https://github.com/importcjj/mobc/issues/58).
In the meantime you can use the undocummented URL parameter `max_connection_lifetime` (see https://github.com/prisma/docs/issues/1657).

**Comment by mdespriee** [comment]
ok, thanks. It's running in docker container (so not serverless)

**Comment by janpio** [comment]
@mdespriee Are you still getting the same error with more recent messages? (The max amount in the error message you were getting was a red herring in that old version, confusing people and leading them in the wrong direction.) What does the connection usage on the server look like for the same time span?

**Comment by Sytten** [comment]
What I find weird on this is it should still respond to requests for connection, it's just that the pool won't go down in size. And if the database is at saturation for its pool, then usually it throws an error to the client. So I am not really sure if my fix will fix this particular issue.
@mdespriee if you can monitor the number of connections on the server side that would be helpful. Usually you get that metric out of the box in SaaS providers but otherwise you can run:
```sql
select * from pg_stat_activity;
```
@pimeys What is the status on using r2d2 or another pool instead of mobc? This particular issue smells again like a pool exhaustion (unsure why I thought I fixed it last time :S)

**Comment by Sytten** [comment]
Interesting this morning I got a similar error for a client.
Since the engine is lazy loaded it might be that the pool is slow on startup? @janpio unsure if that is related or is another issue.
```
2021-06-21 12:45:07.084 EDT yarn run v1.22.5
2021-06-21 12:45:07.127 EDT $ node ./scripts/downloadSecrets.js && ./node_modules/env-cmd/bin/env-cmd.js -f ./config/production.env node -r tsconfig-paths/register src/server.js
2021-06-21 12:45:10.980 EDT "🚀 Worker started"
2021-06-21 12:45:11.149 EDT "Incoming request: POST /job"
2021-06-21 12:45:11.150 EDT "Received new job"
2021-06-21 12:45:11.151 EDT "Job: GENERATE_ORDER_PDF"
2021-06-21 12:45:11.154 EDT "Generating order xxxxx pdf"
2021-06-21 12:45:25.460 EDT "Route failure: Timed out fetching a new connection from the connection pool. (More info: http://pris.ly/d/connection-pool, Current connection limit: 10)"
2021-06-21 12:45:25.461 EDT "Request completed"
2021-06-21 12:45:25.474 EDT POST 500 696 B 19.031 s APIs-Google; (+https://developers.google.com/webmasters/APIs-Google.html) https://xxxxxxxxxxxxxx.a.run.app/job
2021-06-21 12:45:38.992 EDT "Incoming request: POST /job"
2021-06-21 12:45:38.992 EDT "Received new job"
2021-06-21 12:45:38.992 EDT "Job: GENERATE_ORDER_PDF"
2021-06-21 12:45:38.993 EDT "Generating order 79136 pdf"
2021-06-21 12:45:41.487 EDT "Job finished"
2021-06-21 12:45:41.489 EDT "Request completed"
2021-06-21 12:45:41.489 EDT POST 200 689 B 2.502 s APIs-Google; (+https://developers.google.com/webmasters/APIs-Google.html) https://xxxxxxxxxxxxxx.a.run.app/job
```

**Comment by Sytten** [comment]
Interesting this morning I got a similar error for a client.
Since the engine is lazy loaded it might be that the pool is slow on startup? @janpio unsure if that is related or is another issue.
```
2021-06-21 12:45:07.084 EDT yarn run v1.22.5
2021-06-21 12:45:07.127 EDT $ node ./scripts/downloadSecrets.js && ./node_modules/env-cmd/bin/env-cmd.js -f ./config/production.env node -r tsconfig-paths/register src/server.js
2021-06-21 12:45:10.980 EDT "🚀 Worker started"
2021-06-21 12:45:11.149 EDT "Incoming request: POST /job"
2021-06-21 12:45:11.150 EDT "Received new job"
2021-06-21 12:45:11.151 EDT "Job: GENERATE_ORDER_PDF"
2021-06-21 12:45:11.154 EDT "Generating order xxxxx pdf"
2021-06-21 12:45:25.460 EDT "Route failure: Timed out fetching a new connection from the connection pool. (More info: http://pris.ly/d/connection-pool, Current connection limit: 10)"
2021-06-21 12:45:25.461 EDT "Request completed"
2021-06-21 12:45:25.474 EDT POST 500 696 B 19.031 s APIs-Google; (+https://developers.google.com/webmasters/APIs-Google.html) https://xxxxxxxxxxxxxx.a.run.app/job
2021-06-21 12:45:38.992 EDT "Incoming request: POST /job"
2021-06-21 12:45:38.992 EDT "Received new job"
2021-06-21 12:45:38.992 EDT "Job: GENERATE_ORDER_PDF"
2021-06-21 12:45:38.993 EDT "Generating order xxxxx pdf"
2021-06-21 12:45:41.487 EDT "Job finished"
2021-06-21 12:45:41.489 EDT "Request completed"
2021-06-21 12:45:41.489 EDT POST 200 689 B 2.502 s APIs-Google; (+https://developers.google.com/webmasters/APIs-Google.html) https://xxxxxxxxxxxxxx.a.run.app/job
```

**Comment by mdespriee** [comment]
fwiw, in our case it's not related to a slow start. We are in docker env, the problem is not related to startup phase.

**Comment by benoitguigal** [comment]
Have you get a chance to solve the problem by setting the `max_connection_lifetime` parameter ? 
We are experiencing the same exact issue here: every two or three days (sometimes more), all our prisma requests encounter the `Timed out fetching a new connection from the connection pool` error and it won't recover by itself, we have to restart our API. We are running prisma 2.29.1. Not sure it is related, but the problem has appeared after we migrated our API from a docker setup to a PaaS setup.

**Comment by Sytten** [comment]
@benoitguigal there are two undocumented parameters you can use to reduce that (see prisma/docs#1657). It is not perfect because the reaper is not consistent so you might still get some timeout. I suggest you add a retry middleware like here: https://github.com/prisma/prisma/issues/6329#issuecomment-816954832
The pool needs to be rewritten IMO, it was started but it is not an easy job.

**Comment by benoitguigal** [comment]
Thanks @Sytten. I am not sure to understand why a retry middleware may help. Do throwing an error in the middleware will cause the connections to be reset ? 
What will be a good value for `max_connection_lifetime` ?

**Comment by Sytten** [comment]
Because currently the connection reaper only works when you request a connection (see https://github.com/importcjj/mobc/pull/60), so a retry might help with freeing connections. I personally set it between 1h and 1 day depending on the stability of the connections (in seconds if you pass it as a query parameter).

**Comment by benoitguigal** [comment]
Ok we will try to add a retry. Setting the `max_connection_lifetime`, even to a very low value like 5 minutes did not help. Attached a graph of the response time to our server. All the incoming requests suddenly hit the connection pool timeout error until a restart of the application occurs. 

![Capture d’écran 2021-09-10 à 14 31 02](https://user-images.githubusercontent.com/2269165/132853560-aa54acfd-e494-4a65-961e-7eb54dfcebe4.png)

**Comment by garrensmith** [comment]
This is fixed. The full information can be found here https://github.com/importcjj/mobc/issues/63
This will be out in the next release. You can test it now with prisma@dev

**Comment by benoitguigal** [comment]
Thanks @garrensmith for the heads-up, we will migrate to the new version as soon as it is released
