### ISSUE TITLE
Model named "Check" is incorrectly typed

### ISSUE THREAD

**Issue by mohamedGamalAbuGalala** [prisma/prisma#7655]
### Bug description

I have a model called `Check`, after running `Prisma generate`. There will be 2 different types with the same key `CheckSelect` one used by the Prisma client itself and the other is generated to give the ability to select properties while querying the Check model.

### How to reproduce

1. open this [sandbox](https://codesandbox.io/s/jolly-chaplygin-d9fwx?file=/prisma/schema.prisma)
1. `npm run db:generate`
2. `npm run build` 

### Expected behavior

`Check` should be a valid name for a model with no duplicate types with its name

### Environment & setup

- OS: Debian
- Database: Any of those[PostgreSQL, MySQL, MariaDB or SQLite]
- Node.js version: v14.16.1

### Prisma Version

```
2.24.1
```

**Comment by mohamedGamalAbuGalala** [comment]
After a look in the issues section. I found that it belongs to the label: "topic: reserved words"

**Comment by pantharshit00** [comment]
I can confirm this bug, thanks for reporting.

**Comment by SevInf** [comment]
This is fixed and the fix will be published as a part of 5.1 release. You can also check out `5.1.0-dev.25` dev snapshot - we do not recommend using dev snapshots in production, but it should be enough to verify the fix.
