### ISSUE TITLE
Prisma error with redwood js (Node = v 12.18.4 , Yarn >= v 1.22.10, , Prisma = 6.14.6 , Win 7 , 32 bit )

### ISSUE THREAD

**Issue by InquisitiveAboutReact** [prisma/prisma#7660]
### Bug description

Hi All - I have been facing prisma error while working with redwood js while running the below commands ,
Any help would be appreciated. Thanks in advance !! :)

**yarn rw dev**
![image](https://user-images.githubusercontent.com/85705446/121951698-e237a800-cd78-11eb-8a7d-6a33e6d08d4d.png)
**yarn rw prisma migrate dev**
![image](https://user-images.githubusercontent.com/85705446/121951724-ea8fe300-cd78-11eb-9db2-37441dd0225c.png)
**yarn rw dataMigrate up**
![image](https://user-images.githubusercontent.com/85705446/121951747-f24f8780-cd78-11eb-837b-dd4f12e94dfd.png)

### How to reproduce

1. Go to  - ' redwood project root folder' 
2. Open command prompt 
3.  Run  any of the commands **yarn rw dev ,  yarn rw prisma migrate dev, yarn rw dataMigrate up**

### Prisma information

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = "native"
}

### Environment & setup

- OS: **Win 7 , 32 bit**
- Database: **SQLite**
- Node.js version: **12.18.4**

### Prisma Version
**6.14.6**

**Comment by janpio** [comment]
> Not able to run prisma -v . Getting error
You should be able to run `npx prisma -v` in your Redwood project.

**Comment by InquisitiveAboutReact** [comment]
Hi @janpio - Thanks. I did run  < npm prisma -v > = **6.14.6**

**Comment by janpio** [comment]
Note the `x` here to make it `npx` instead of `npm` - `npx prisma -v`.

**Comment by pantharshit00** [comment]
I don't think we compile for 32bit Windows. We only compile for `x86_64-pc-windows-msvc` and not for `i686-pc-windows-msvc`

I don't think we are going to have official support for any 32bit OS and Windows 7 was out of support officially from Microsoft from January 14, 2020 so you should really upgrade here. 

You can also try compiling the engines yourself: https://github.com/prisma/prisma-engines#building-prisma-engines and https://www.prisma.io/docs/concepts/components/prisma-engines#using-custom-engine-binaries

**Comment by janpio** [comment]
That is unfortunately indeed the case. The error message is a bit suboptimal though. Optimally we would just catch that and tell the user about it.

**Comment by livthomas** [comment]
I've also run into this issue. I use Prisma inside an Electron app with a local SQLite database. First, I got an error saying the `library` engine type doesn't work with 32-bit Node.js. When I changed it to `native`, I got the same error as @janpio.

It would be nice if you listed what versions of various operating systems you support. There is no mention of it in the [System requirements](https://www.prisma.io/docs/reference/system-requirements) section of the documentation.

**Comment by janpio** [comment]
`native` is not a valid engine type @livthomas. Do you mean `binary` maybe? 

Using the engine type `binary` should in theory work for 32 bit Node on Windows (which is the only case which we do _not_ support, and hence have that nice error message you got to tell you how to fix it).

**Comment by livthomas** [comment]
@janpio Yes, I meant `binary`. Sorry for the confusion.

And yes, I got a nice error message saying what I need to change when I used `library` engine type. However, when I switched to `binary` engine type, I got a similar error to the one in the description of this issue. It was saying something like `spawn UNKNOWN` and its surroundings didn't tell me much about what went wrong.

So does Prisma work on 32-bit Windows 7 or not? Because from the previous comments it looks like it doesn't. But if it should work there and you think this is actually a bug, I can create a new issue with more details. Otherwise, it would be nice to get a better error message in this case and also have this mentioned in the documentation.

**Comment by janpio** [comment]
Prisma does work with 32bit Node.js on current supported Windows versions.
What happens on 32bit Windows 7 I am not sure - it might be worth for you to create a bug report indeed and supply the full information you get. Maybe we can add a more helpful error message there. (I would not expect us to be able to make it run there though - just getting a build machine for 32bit Windows might not be that easy)
