### ISSUE TITLE
Latest Prisma (2.24.x) version breaks some pnpm projects when generating models

### ISSUE THREAD

**Issue by mpolitowski-iws** [prisma/prisma#7661]
### Bug description

I have a `pnpm` project and was running fine on Prisma 2 v2.23.x and lower.  But when I upgraded to 2.24.1 my project broke and was unable to resolve the models after running `npx prisma generate`.

I will share some simple examples of how to reproduce.  But simply put if you run `npx prisma generate` in a `pnpm` project that has subprojects that by default hoist dependencies, the latest version does not seem to correctly place the generated `@prisma/client` code in the correct place, thus the project does not know any of the generated models anymore.  I'm not sure what broke between versions but it's only in 2.24.x where this happens.

NOTE: I asked about this in the Prisma Slack channel and was advised to post this as a bug in Github.  Someone had thought a change to path resolution in 2.24.x might be the culprit.

### How to reproduce

1.  Switch to Prisma 2.24.x 
2. type `npx prisma generate`

You'll then see the following response (note the main difference in responses from 2.23.x and earlier to 2.24.x is that 2.24.x replies with `.node_modules/xxx` where 2.23.x and earlier response with `../../node_modules/xxx`):

````
➜  api git:(MyGitBranch) ✗ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
✔ Generated Prisma Client (2.24.1) to ./node_modules/@prisma/client in 185ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
```` 

### Expected behavior

`npx prisma generate` will correctly place the generated file in the root `node_modules` directly like so and no broken links the project will exist:

````
➜  api git:(MyGitBranch) ✗ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
✔ Generated Prisma Client (2.24.1) to ./../../node_modules/.pnpm/@prisma/client@2.24.1_prisma@2.24.1/node_modules/@prisma/client in 640ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
````

### Prisma information

Not sure this matters...

### Environment & setup

- OS: any
- Database: PostgreSQL
- Node.js version: v14.15.4

### Prisma Version

```
➜  api git:(mygitbranch) ✗ npx prisma -v
Environment variables loaded from .env
prisma               : 2.24.1
@prisma/client       : 2.24.1
Current platform     : darwin
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at ../../node_modules/.pnpm/@prisma/engines@2.24.1-2.18095475d5ee64536e2f93995e48ad800737a9e4/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at ../../node_modules/.pnpm/@prisma/engines@2.24.1-2.18095475d5ee64536e2f93995e48ad800737a9e4/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at ../../node_modules/.pnpm/@prisma/engines@2.24.1-2.18095475d5ee64536e2f93995e48ad800737a9e4/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at ../../node_modules/.pnpm/@prisma/engines@2.24.1-2.18095475d5ee64536e2f93995e48ad800737a9e4/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0
```

**Comment by millsp** [comment]
Hey @mpolitowski-iws, sorry that you are experiencing trouble. Would you mind sharing your setup? From what I know, this is an intended change. Let's assume that you have multiple packages (or services), and each of them use a different database, generate a different `prisma` client.
 
You are using `pnpm`, which hoists the package to the root of your project. This could lead to problems if you had many clients to generate, they would overwrite themselves into the root (hoisted) `node_modules`. If your root is project is empty, you should not be able to run `generate`.

Now instead, we recommend that you run your `pnpx prisma generate` into the sub-projects's folder. It will generate the client into the `node_modules` of your sub-projects. However, I get the feeling that our setups differ so could you please put up a minimal project so that I can take a look? Thanks.

**Comment by janpio** [comment]
@mpolitowski-iws We just talked about this again, and are not suuuper sure what the way forward here would be. A minimal of what your setup looks like would help a lot, even if it is pretty simple - then we do not waste our time with more complicated problems. 

A few additional questions:
Are you using your Prisma Client in multiple sub projects? 
Do you have multiple Prisma Clients?

**Comment by millsp** [comment]
@mpolitowski-iws I propose you this workaround, please let me know if it works:
```ts
import { PrismaClient } from '.prisma/client'
```

**Comment by MarvinRudolph** [comment]
> @mpolitowski-iws I propose you this workaround, please let me know if it works:
> 
> ```ts
> import { PrismaClient } from '.prisma/client'
> ```

I can confirm that it works. Thanks!

**Comment by mpolitowski-iws** [comment]
I'll do my best here, please advise if you need more information.

Our environment is a mono repo/project with pnpm.  Our structure looks something like this:

```
/OurApp
   node_modules
   package.json
   /apps
      /api   <-- this is the pnpm project that uses Prisma
      node_modules
      package.json
      /web
      node_modules
      package.json
```

In our project our dependencies are hoisted to the root (ie `/OurApp/node_modules` )

I could dig a bit deeper - but it seemed that in 2.24.0 was writing only to say `/OurApp/app/api/node_modules` and our project with hoisting looks to `/OurApp/node_modules`.

Before this gets "fixed" (if it does) - I do want to state that I was curious how we would implement Prisma in another subproject (ie like `/OurApp/app/web` above) - would `npx prisma generate` overwrite the models for `/OurApp/app/api`?).  Maybe this change in 2.24.0 addresses this if I have the app look in `.prisma/client` instead of `@prisma/client`.

**Comment by mpolitowski-iws** [comment]
> @mpolitowski-iws I propose you this workaround, please let me know if it works:
> 
> ```ts
> import { PrismaClient } from '.prisma/client'
> ```

I tried this as well @millsp and the compiler ofc accepted it but when I went to runtime I got this error message:

```
[INFO] 12:23:47 ts-node-dev ver. 1.0.0 (using ts-node ver. 9.1.1, typescript ver. 4.3.2)
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/Users/me/GitProjects/OurApp/node_modules/.pnpm/@prisma/client@2.25.0_prisma@2.25.0/node_modules/.prisma/client/index.js:3:11)
    at Object.<anonymous> (/Users/me/GitProjects/OurApp/apps/api/src/prisma.client.ts:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/Users/me/GitProjects/OurApp/node_modules/.pnpm/source-map-support@0.5.19/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/gt/0s4g281s01gdcmmt13n5jd_80000gn/T/ts-node-dev-hook-14929767482859146.js:57:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at require.extensions.<computed> (/private/var/folders/gt/0s4g281s01gdcmmt13n5jd_80000gn/T/ts-node-dev-hook-14929767482859146.js:59:20)
    at Object.nodeDevHook [as .ts] (/Users/me/GitProjects/OurApp/node_modules/.pnpm/ts-node-dev@1.0.0/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[ERROR] 12:23:52 Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
```

Also Pierre as I wrote in Slack, I'm really busy atm but when I have some time I can try to put together a simple project that demonstrates this bug.

**Comment by mpolitowski-iws** [comment]
> @mpolitowski-iws I propose you this workaround, please let me know if it works:
> 
> ```ts
> import { PrismaClient } from '.prisma/client'
> ```

After working with @millsp in Slack (thank you Millsp!) I found I additionally was importing PrismaClient from `@primsa/client` (instead of `.prisma/client`). After this change my app was working with preliminary tests - which is awesome so thank you all.  I am testing in 2.25.0 but I assume this would also test well for 2.24.0.

I should note that the only change I had to make was changing my model and PrismaClient imports from `@prisma/client` to `.prisma/client`.  And talking to @millsp in Slack, this definitely should fix the issue where PNPM fully hoisted mono repos before could only have one project with Prisma (because multiple subprojects would compete/overwrite their model defs with `prisma generate` in the root `node_modules` directory).  This fix and solution might fix that.  Just my 2c here.

Anyway again thank you all for your help and an awesome product!

**Comment by janpio** [comment]
@MarvinRudolph That sounds bad, can you please create a separate issue as a bug report for this and include as much information as possible? We should definitely look into this.

**Comment by bryanmig** [comment]
I am experiencing the same issue here.  I have a [Rushstack](https://rushstack.io/) based monorepo using `pnpm` and I've created a repro here: https://github.com/bryanmig/prisma-7661-repro
```

**Comment by janpio** [comment]
Thanks for the additional information @bryanmig - the initial intention was to support multiple clients, but we definitely did not want to break other projects along the way so we will need to look into this and see if there is a way to make both worlds happy. I hope so.

**Comment by hedwiggggg** [comment]
Having the same issue with pnpm, nextjs, next-auth and prisma.

```
> prisma "generate"

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (2.25.0) to ./node_modules/.pnpm/@next-auth+prisma-legacy-adapter@0.0.1-canary.127_bc343d57fda392526ca013a606ba56f4/node_modules/@prisma/client in 96ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

vs.

```
> prisma "generate"

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (2.23.0) to ./node_modules/.pnpm/@prisma+client@2.23.0_prisma@2.23.0/node_modules/@prisma/client in 94ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
