### ISSUE TITLE
Improve NodeJS <> Rust language binding

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma#767]
Prisma Client is a JavaScript library that calls out to the query engine, which is a Rust binary.

Currently the interface between the two is http on a local port. Moving to FFI might provide benefits such as

- lower latency / less memory consumption
- a simpler model
- better maintainability

This could be implemented using the [Neon Bindings](https://neon-bindings.com) project.

internal reference: [project](https://www.notion.so/prismaio/Neon-better-engine-node-integration-df537a620ff44df19899ee0645218815)

**Comment by janpio** [comment]
This is happening via https://github.com/prisma/prisma/issues/6301
