### ISSUE TITLE
`db seed` keeps open handle even when seeding has finished on Ubuntu

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7679]
See https://github.com/prisma/e2e-tests/pull/1807, needed `jest --forceExit` to work.

**Comment by Jolg42** [comment]
🗒️ We heard the feedback and we are planning a redesign of `db seed` (currently planned to be released early September)

How it will work is that a `prisma.seed` property in the package.json of your project will be required if you want to use `prisma db seed`.

This property is where you will be able to put any command you want to execute your seed script.

More info/details & how to try it out now in:
https://github.com/prisma/prisma/issues/8732

**Comment by janpio** [comment]
The redesign of db seed was released with Prisma 3. Please try it, this problem should be gone.
