### ISSUE TITLE
Model.idFields list is empty in generator

### ISSUE THREAD

**Issue by benkroeger** [prisma/prisma#7681]
### Bug description

When running a (custom) generator, the `idFields` property on a `Model` instance is just an empty array. When going through the individual `Model.fields`, you can still find the one that has `Field.isId = true`.

### How to reproduce

- run a prisma generator
- read `dmmf` from [options](https://github.com/prisma/prisma/blob/master/src/packages/generator-helper/src/types.ts#L75) passed to [onGenerate](https://github.com/prisma/prisma/blob/master/src/packages/generator-helper/src/generatorHandler.ts#L10) function
- inspect `options.dmmf.datamodel.models[].idFields` property

### Expected behavior

expecting that list to contain all names of `Model.fields[]` that have the `isId` property set to `true`

### Prisma information
```prisma
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

// this one is not released yet but shouldn't actually matter since the issue can be reproduced even before the generator does anything
generator nestjsDto {
  provider                  = "prisma-generator-nestjs-dto"
  includeRelationFields     = "true"
  includeRelationFromFields = "true"
}

/// documentation on `Response`
model Response {
  id String @id @default(uuid())
}
```

### Environment & setup

- OS: Mac OS
- Database: SQLite - but doesn't matter really
- Node.js version: v16.3.0

### Prisma Version

```
prisma               : 2.24.1
@prisma/client       : 2.24.1
Current platform     : darwin
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0
```

**Comment by pantharshit00** [comment]
I can reproduce this in 2.28
```
code/reproductions/issue_7681 is 📦 v1.0.0 via  v14.17.0
❯ npx prisma generate
Prisma schema loaded from prisma\schema.prisma
[
  {
    name: 'Response',
    isEmbedded: false,
    dbName: null,
    fields: [
      {
        name: 'id',
        kind: 'scalar',
        isList: false,
        isRequired: true,
        isUnique: false,
        isId: true,
        isReadOnly: false,
        type: 'String',
        hasDefaultValue: true,
        default: { name: 'uuid', args: [] },
        isGenerated: false,
        isUpdatedAt: false
      }
    ],
    isGenerated: false,
    documentation: 'documentation on `Response`',
    idFields: [],
    uniqueFields: [],
    uniqueIndexes: []
  }
]

✔ Generated Sample Generator to .\prisma\test in 4ms
```

**Comment by janpio** [comment]
We should add that sample generator to our tests and snapshot what you output there @pantharshit00

**Comment by pantharshit00** [comment]
You mean in e2e tests or test suite in this repository?

**Comment by janpio** [comment]
Test in this repository that is run as part of the normal test suite.

**Comment by prisis** [comment]
Hey :), i have kind of the same issue, but the `idFields` is gone in version 2.29.1

```
{
  name: 'Files',
  isEmbedded: false,
  dbName: null,
  fields: [
    {
      name: 'id',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: true,
      isReadOnly: false,
      type: 'String',
      hasDefaultValue: true,
      default: [Object],
      isGenerated: false,
      isUpdatedAt: false
    },
    {
      name: 'name',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      type: 'String',
      hasDefaultValue: false,
      isGenerated: false,
      isUpdatedAt: false
    },
    {
      name: 'location',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      type: 'String',
      hasDefaultValue: false,
      isGenerated: false,
      isUpdatedAt: false
    },
    {
      name: 'storage',
      kind: 'enum',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      type: 'FileStorageType',
      hasDefaultValue: false,
      isGenerated: false,
      isUpdatedAt: false
    },
    {
      name: 'mime',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      type: 'String',
      hasDefaultValue: false,
      isGenerated: false,
      isUpdatedAt: false
    },
    {
      name: 'size',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      type: 'Int',
      hasDefaultValue: false,
      isGenerated: false,
      isUpdatedAt: false
    }
  ],
  isGenerated: false,
  primaryKey: null,
  uniqueFields: [],
  uniqueIndexes: []
}
```

Now im getting a error in the model.js file line 197 \`model.idFields.length > 0\`

**Comment by aqrln** [comment]
Still reproducible. `idFields` does not exist anymore, however `primaryKey` has been introduced instead, and it always seems to be `null` for me. Additionally, `uniqueFields` is also always an empty array even if I have unique fields in the model.

**Comment by aqrln** [comment]
Actually this is intentional and not a bug.

Looking at [[1]](https://github.com/prisma/prisma-engines/blob/d4bfbd099ee1f53a5840044671a3e05956a00b08/query-engine/dmmf/src/ast_builders/datamodel_ast_builder.rs#L114), [[2]](https://github.com/prisma/prisma-engines/blob/d4bfbd099ee1f53a5840044671a3e05956a00b08/query-engine/dmmf/src/ast_builders/datamodel_ast_builder.rs#L136) and [[3]](https://github.com/prisma/prisma-engines/blob/d4bfbd099ee1f53a5840044671a3e05956a00b08/query-engine/dmmf/src/ast_builders/datamodel_ast_builder.rs#L142), `primaryKey`, `uniqueFields` and `uniqueIndexes` fields in the DMMF only include the attributes defined on the model and directly on the field.

Indeed, with the following model
```prisma
model A {
  id Int @id
}
```
`datamodel.models[0].primaryKey` is `null`, but with the following model:
```prisma
model A {
  id Int
  @@id(id)
}
```
`datamodel.models[0].primaryKey` is `{ "name": null, "fields": ["id"] }`.

You need to consider both both the the `isId` properties in the `fields` array and the `primaryKey` when determining the id fields.
