### ISSUE TITLE
Node-API on Windows: window asking how to execute `.node` file

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7693]
Running `npx prisma generate` on Windows with set `PRISMA_FORCE_NAPI=true` set shortly opens weird window asking how to execute `.node` file (but generates Client successfully anyway and windows goes away again): 

![image](https://user-images.githubusercontent.com/183673/122106516-4eb6b380-ce1a-11eb-8950-4acd9d16f90c.png)

Is this trying to somehow execute this file in a way that does not actually work, like with the binary?

**Comment by millsp** [comment]
Possibly related https://github.com/prisma/prisma/issues/4308#issuecomment-844344765

**Comment by janpio** [comment]
"Debugged" this via `process.exit(1)` in the built Client... 

And here is the reason:
https://github.com/prisma/prisma/blob/ad8f073b83ddd9fd6a57c01fa7ac16d75a69f0a7/src/packages/sdk/src/engine-commands/getVersion.ts#L17-L28
This goes into the wrong arm of the conditional because the string it is comparing to does not match the Windows Node-API library engine file name:
https://github.com/prisma/prisma/blob/ad8f073b83ddd9fd6a57c01fa7ac16d75a69f0a7/src/packages/fetch-engine/src/download.ts#L35-L41
The value of `binaryName` is `query-engine` here for some reason - although it should be `libquery-engine-napi`.

It has that value, as that is the default of the function if only 1 param is supplied:
https://github.com/prisma/prisma/blob/ad8f073b83ddd9fd6a57c01fa7ac16d75a69f0a7/src/packages/sdk/src/engine-commands/getVersion.ts#L12-L15

And we are indeed only calling it with 1 param here:
https://github.com/prisma/prisma/blob/9c287b3d45ae721f463b682651bd778cfab9d05a/src/packages/client/src/generation/generateClient.ts#L283-L287

**Comment by janpio** [comment]
Fixed by https://github.com/prisma/prisma/pull/7898
