### ISSUE TITLE
Polish Node-API library implementation

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7694]
- ~~Clean up NapiEngine https://github.com/prisma/prisma/pull/7595~~
- Engines
	- Change filename of library file (no `napi`, better naming pattern, same file name basis for all platforms [currently `libquery` on linux and macos, but only `query` on windows]) ([internal Slack](https://prisma-company.slack.com/archives/C02232M9CP8/p1621423775006500))
	- Update codebase to use less `napi` but `node-api` (or similar) instead
- CLI/Client
	- Clean up `-v` output: Replace `N-API Query Engine` wording, Suggestion `Query Engine (Node-API)`
	- Feature: Download progress bar should include information if which engine type is being downloaded (for debugging)
	- All occurrences of `N-API` in codebase (NOT `useNAPI` as that will be ripped out soon)
	- Maybe: NodeEngine => BinaryEngine, NapiEngine => LibraryEngine
- Review `prisma:*` log output

**Comment by pimeys** [comment]
what about cleaning up the topic label for node api?

**Comment by janpio** [comment]
All done via the PRs linked above.
