### ISSUE TITLE
Review all tests for engine types

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7695]
- GH Actions
- Buildkite
 
Are we testing the same things for both engine types?
Where does it make sense to differ?
Do we have any skip or exclusions?

**Comment by Jolg42** [comment]
## Buildkite

Test = separate tests in 3 jobs (using BUILDKITE_PARALLEL_JOB)
https://github.com/prisma/prisma/blob/master/src/.buildkite/test/run.sh#L65
https://buildkite.com/prisma/prisma2-test

Logic of splitting https://github.com/prisma/prisma/blob/master/src/scripts/ci/publish.ts#L857-L880
Job 0 - All except client
Job 1 - Only client
Job 2 - Node-API with `PRISMA_FORCE_NAPI=true` for '@prisma/sdk', '@prisma/client', 'prisma', '@prisma/integration-tests'

Publishing = test + run publish in one job
https://github.com/prisma/prisma/blob/master/src/.buildkite/publish/run.sh
https://buildkite.com/prisma/prisma2-publish

## GitHub Actions
https://github.com/prisma/prisma/blob/master/.github/workflows/test.yml

With napi/binary matrix
- client (without slow types test)
- integration-tests
- sdk
- migrate
- cli-commands

Without napi matrix
- client-types (only types test)
- others (debug, engine-core, fetch-engine, generator-helper, get-platform)

**Comment by janpio** [comment]
Do Buildkite and GH Actions thus run effectively the same tests? Or are some only run on one of these? 
From naive reading above, it seems that `migrate` and `cli-commands` are only run with Node-API on GH Actions?

**Comment by Jolg42** [comment]
> Do Buildkite and GH Actions thus run effectively the same tests? Or are some only run on one of these?

Because we do splitting in GitHub Actions, meaning we create a job per package (exception for client-types), the logic is hardcoded and can drift from just running `pnpm run test` at the root like done in Buildkite.

They should run the same tests, should be in sync but for Node-API: ⬇️ 
 
> From naive reading above, it seems that migrate and cli-commands are only run with Node-API on GH Actions?

Indeed, that's what it looks like.

**Comment by janpio** [comment]
> > Do Buildkite and GH Actions thus run effectively the same tests? Or are some only run on one of these?
> 
> Because we do splitting in GitHub Actions, meaning we create a job per package (exception for client-types), the logic is hardcoded and can drift from just running `pnpm run test` at the root like done in Buildkite.

In e2e tests we have a special job to make sure all the necessary tests are run: https://github.com/prisma/e2e-tests/blob/dev/.github/workflows/lint.yaml (there the requirements are defined by the projects that exist, here it would probably be about test files covered by the existing commands or similar)

> > From naive reading above, it seems that migrate and cli-commands are only run with Node-API on GH Actions?
> 
> Indeed, that's what it looks like.

That should be simple enough to fix by adding these to the Buildkite definition thing.

**Comment by Jolg42** [comment]
Actually CLI is already tested, only migrate was missing, create a PR https://github.com/prisma/prisma/pull/7788
