### ISSUE TITLE
Invalid `prisma.post.findMany()` invocation: connect ECONNREFUSED ::1:50413

### ISSUE THREAD

**Issue by siemah** [prisma/prisma#7697]
### Bug description

I upgrade my project from `@prisma/cli`(version 2.13.1) and `@prisma/client`(version 2.13.1) to `prisma`(version 2.24.1) and `@prisma/client`(version 2.24.1) respectively and when i ran `npx prisma studio` or using prisma client this error appeared to me:

```shell
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.category.findMany()` invocation:


  connect ECONNREFUSED ::1:50281
    at cb (/path-to-app-folder/node_modules/@prisma/client/runtime/index.js:35223:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ECONNREFUSED',
  clientVersion: '2.24.1',
  meta: undefined
}
```

The same error appeared when i use the ** Quickstart**(with sqlite).

***Note***:
After i added this `{ __internal: { useUds: true }} as any` to PrismaClient constructor it work but **prisma studio** still not working

### Prisma information

Prisma schema for **Mysql**

```prisma
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

model Post {
  id                Int        @id @default(autoincrement())
  title             String     @db.VarChar(256)
  content           String?    @db.MediumText
  published         Boolean?   @default(true)
  publisher         String?    @db.VarChar(256)
  publisher_favicon String?    @db.VarChar(256)
  source_article_id String?    @unique
  link              String?    @db.VarChar(256)
  image_link        String?    @db.VarChar(256)
  language          Language?  @default(en)
  createdAt         DateTime   @default(now())
  updatedAt         DateTime   @default(now()) @updatedAt
  Category          Category[]
  categoryId        Int?
}

model Category {
  id        Int      @id @default(autoincrement())
  code      String   @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name      String?
  posts     Post[]
}

enum Language {
  en
}
```

Prisma schema for **sqlite**

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}
```

### Environment & setup

- OS: Mac OS(Catalina)
- Database: MySQL and SQLite
- Node.js version: v12.18.3

### Prisma Version

```
prisma               : 2.25.0
@prisma/client       : 2.25.0
Current platform     : darwin
Query Engine         : query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : c838e79f39885bc8e1611849b1eb28b5bb5bc922
Studio               : 0.402.0
```

**Comment by ZosoDerGoldene** [comment]
I do have a similar issue with a postgresql db on linux. Everything works fine (introspect, migrate, ...), but the first query against the client causes it to panic/crash (I guess) and I get a ECONNREFUSED on varying ports.

Prisma Schema for **postgresql**:

`generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model players {
  id            Int       @id @default(autoincrement())
  email         String    @unique @db.VarChar(255)
  password_hash String    @db.VarChar(255)
  display_name  String    @unique @db.VarChar(255)
}`

**Environment & Setup**

- OS: Linux (opensuse tumbleweed)
- Database: Postgresql 13
- Node.js version: v16.4.1

**Prisma version**
`prisma               : 2.27.0
@prisma/client       : 2.27.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : cdba6ec525e0213cce26f8e4bb23cf556d1479bb
Studio               : 0.410.0
`

**Comment by pantharshit00** [comment]
@siemah 

Can you please provide a reproduction here? 


You can also try using the Node API preview which will be the default engine communication method in the future and studio will work fine with it: https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#enable-the-node-api-n-api-preview

**Comment by siemah** [comment]
Hey @pantharshit00 

Sorry about the delay, there is a [repo](https://github.com/siemah/prisma-7697) follow these instructions:

- Install dependencies using `yarn` or `npm i`
- Run `npx prisma studio`

**Comment by pantharshit00** [comment]
This should be automatically resolved now in Prisma v3 since we don't use a sidecar binary process anymore.
