### ISSUE TITLE
Performance comparison of Photon vs Knex

### ISSUE THREAD

**Issue by robmurtagh** [prisma/prisma#770]
Hi Prisma Team, just as a follow up to a discussion on Prisma slack with @johannesschobel.

We tested 2 implementations of our real-world app using `Photon` and `Knex` on top of a MySQL DB. We then ran an existing test suite that spins up a `localhost` Apollo server and runs a number of GraphQL queries in sequence. Each query might cross a number of DB operations, but I have categorised them by their primary workload for the DB connection e.g. `UPDATE`, `GET`, `DELETE` etc.

I'm attaching the results for the operations. The test is probably not perfect, but currently Prisma is quite a bit slower than the straightforward `Knex` query. I'm sharing these results just as an example of a real world usecase, hoping that it might be helpful to you as a marker in your continuing development efforts.

Thanks again for all your hardwork! And good luck getting this toward General Availability.

[Results as a .xlsx](https://github.com/prisma/prisma2/files/3735350/test-timings-for-prisma.xlsx)

**Comment by pantharshit00** [comment]
Thanks for this benchmark.

These timings are but expected as the query-engine runs on top of HTTP right now. We are looking forward to switching HTTP with native bindings which would increase the timings. Details here: https://github.com/prisma/prisma2/issues/767

**Comment by pimeys** [comment]
Query optimization has not even started yet, now focusing on IO primitives and execution model...

We have a ticket for it though and it would help if you'd share the prisma queries used in the benchmark.

**Comment by johannesschobel** [comment]
Dear @robmurtagh , thanks a lot for this valuable insights into your performance measures. I am very interested to see performance stats with newer prisma2 versions. AFAIK, the performance optimization has not even started yet. So i am quite interested in how this will work out in 2 months+ :)

All the best

**Comment by robmurtagh** [comment]
Hey, thanks for the discussion around this Issue, really appreciate how responsive the Prisma team are.

@pimeys, completely understand that you're in the early stages of query engine implementation. I can imagine you want to build some solid foundations then there will be lots of space for optimisation.

Unfortunately it will be hard for me to share the exact Prisma queries as they are quite spread throughout the codebase, which we need to keep confidential. Essentially we migrated a DB from Mongo to MySQL, and at the same time experimented with Photon (which is our preferred solution) before falling back to Knex (until `prisma2` hits GA).

We have a range of query patterns, most of which are fairly vanilla. The most common patterns are e.g.:

```js
photon.entity.findOne(..by primary key)
photon.entity.findMany(..by condition)
photon.entity.update({ ...by primary key, data });
photon.entity.findOne(..by primary key).entity2(...by condition, select)
```

I wasn't actually a `prisma1` user, so I'm not sure about relative performance there. When it comes to benchmarking (and I mean this only constructively! 😄 ) but would comparison to e.g. Knex (or any other DB client lib) be more beneficial than comparison to `prisma1`? I love the project and want it to succeed a lot, so just wanted to share these numbers as even just anecdotally it did seem like running with Photon took query took queries from the order of ~10ms to the order of ~100ms in some cases.

Anyways, sure you have plenty of benchmarking, so keep up the good work!

**Comment by pimeys** [comment]
Ok. We have a large sample database now for tests, but it's for PostgreSQL. @do4gr informed me how he was able to trigger certain really slow queries using that dataset, so I'm already waiting to test the new codebase using that dataset.

With MySQL 5.7 certain windowing tricks might definitely cause slowness and I have some ideas where we can easily pick some low-hanging fruits. Also I think we should limit those tricks to version 5.7 and for everybody running a newer version, they could use the same codebase that PostgreSQL and SQLite uses.

Thanks for the good insights!

**Comment by pimeys** [comment]
Btw, I'm mostly always testing against the Rust binary, but there should be a switch where you set `PRISMA_LOG_QUERIES=y` in your environment and it should spit out the SQL and the time spent running it in the database. I don't remember is the photon client already displaying these, maybe @timsuchanek could help here.

**Comment by pimeys** [comment]
Some notes for this. We don't by default generate indices to foreign keys, which makes even the basic joins very slow. We're trying to find a solution that works the best for everybody.

Additional issue to follow: https://github.com/prisma/specs/issues/280

When I added the indices manually, the query execution times went down from 600-1000ms to 0.5-2ms.

**Comment by robmurtagh** [comment]
Hi, I just wanted to follow up on this one after conversation with @janpio [on Twitter](https://twitter.com/Sujan/status/1305551551411486721).

I'll close this issue now based on my following comment from that thread:

> _I don’t still have that codebase around that I originally used for benchmarking. If it’s helpful, we did end up migrating to Prisma now it’s GA, and so far we’ve been really happy. (Our app is quite large though and is internal, so we probably favour typesafety/correctness over performance atm)_

Thanks again to the team for all the hard work!
