### ISSUE TITLE
`migration-engine-rhel-openssl-1.0.x` is not downloaded when running `Prisma generate`, trying to deploy to AWS with AWS CDK

### ISSUE THREAD

**Issue by Albert-Gao** [prisma/prisma#7711]
### Bug description

migration-engine-rhel-openssl-1.0.x will not be downloaded
query-engine-rhel-openssl-1.0.x can be find at `node_modules/.prisma/client`, but not at `node_modules/@prisma/engines`

actually, no `node_modules/@prisma/engines` folder at all

### How to reproduce

1. `mkdir a`
2. `cd a`
3. `npx prisma init`
5. put your local db link in `.env`
6. `yarn add @prisma/client`
7. `yarn generate`
8. No `node_modules/@prisma/engines` created
9. No `migration-engine-rhel-openssl-1.0.x` anywhere

### Expected behavior

all `rhel-openssl-1.0.x` drivers should be downloaded in `node_modules/@prisma/engines`

TBH, I do not know if this is the expected way to work with AWS Lambda, because the documentation does not really show us the steps and necessary steps. Just trying xD

### Prisma information

```yaml
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native","rhel-openssl-1.0.x"]
}

model User {
  id String @id
}
```

### Environment & setup

OS X: 11.3.1
PostgreSQL: 13
DATABASE_URL=postgres://AlbertGao@localhost:5432/test

### Prisma Version

    "@prisma/client": "^2.25.0"

**Comment by Jolg42** [comment]
This behavior is actually expected since the `binaryTargets` parameter only applies to the generator, so the Query Engine.

You can try adding this env var which will be read during `npm install` and the corresponding binaries will be downloaded for the CLI:
```
PRISMA_CLI_BINARY_TARGETS=native,rhel-openssl-1.0.x
```
https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_cli_binary_targets

I think the documentation could be better for this.

**Comment by janpio** [comment]
What are you trying to do on Lambda that you need the Migrations Engine binary @Albert-Gao?
What error message are you getting when you run it anyway?

**Comment by janpio** [comment]
Ping @Albert-Gao

**Comment by janpio** [comment]
Ping @Albert-Gao a last time, or we will need to consider this solved with the link that Joel shared.
