### ISSUE TITLE
`db push` does not create missing foreign keys for `@relation`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7722]
Source: https://prisma.slack.com/archives/CBFFY3066/p1623931975049600

How to reproduce:
- Create a schema with relation
- `db push` it to an empty, new database
- Observe how it created foreign keys
- Drop them
- Run `db push` again
- Observe if the foreign keys are added again or not
- If not, this bug is confirmed

**Comment by kyoungduck** [comment]
In my case, this error occurred in the following cases

1. The database schema was set up without foreign keys.(I was trying to migrate prisma from typeorm)
2. run `prisma init` and `prisma introspect`
3. `@relation` manually specified in schema.prisma.
4. run `prisma db push`
![image](https://user-images.githubusercontent.com/16463746/122498795-b2173000-d02a-11eb-80b1-606acd351b55.png)
5. but it says `The database is already in sync with the Prisma schema.` And foreign key wasn't crated at database

This is my environment
- NodeJS Version: 14.10.1
- Prisma Version: 2.25.0
- Database: MySQL 8.0

sample schema.prisma(The schema of my actual case is different, but this sample has the same problem)
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Article {
  id      BigInt  @id @default(autoincrement())
  title   String? @db.VarChar(255)
  content String? @db.Text

  Comment Comment[]

  @@map("article")
}

model Comment {
  id        BigInt  @id @default(autoincrement())
  articleId BigInt  @map(name: "article_id")
  content   String? @db.Text

  article Article @relation(fields: [articleId], references: [id])


  @@index([articleId], name: "ix_article_id")
  @@map("comment")
}
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this with 2.28. Foregin key was recreated after I ran db push with database that didn't have it.

**Comment by janpio** [comment]
I can not reproduce this either @kyoungduck. With a schema without foreign keys I get the correct schema via `db pull` (Introspection). When I add `@relation` in there, any next `db push` or `migrate dev` will create the foreign key correctly.

Can you help us by giving the concrete SQL and Prisma schema you are using to cause this? Thanks.

**Comment by kyoungduck** [comment]
@janpio 

I also can't reproduce what I did 3 months ago. I had deleted the project directory that was checked when I opened this issue.

I'm not sure, but maybe checked wrong this issue 3 months ago(maybe my mistake).
I'm very sorry about saying this.

**Comment by janpio** [comment]
Don't worry, that is exactly what issues are here for! So thanks for originally opening this, but as we can not reproduce it any more, we just consider it a fluke and close this issue. If it ever happens again, either comment on this issue or open a new one. 🥳
