### ISSUE TITLE
Unable to run Prisma on Netlify with SvelteKit

### ISSUE THREAD

**Issue by didier** [prisma/prisma#7728]
Hi all, 

I'm using Prisma with SvelteKit on Netlify. I'm not sure if the following has anything to do with SvelteKit however, as it seems like a platform binary error.

```
Invalid `prisma.profile.findFirst()` invocation:


  Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/var/task/query-engine-rhel-openssl-1.0.x")

Searched Locations:

  /.prisma/client
  /opt/build/repo/node_modules/@prisma/client
  /var
  /var/task
  /var/task
  /tmp/prisma-engines
  /var/task

You already added the platforms "native", "rhel-openssl-1.0.x" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new
```

**Comment by janpio** [comment]
Do you know where the query engine `query-engine-rhel-openssl-1.0.x` actually is located?
Did this work before?
Can you create a minimal reproduction for this and out it into a repo maybe?

**Comment by millsp** [comment]
A SvelteKit user had a very similar issue, please take a look at his comment https://github.com/prisma/prisma/issues/7019#issuecomment-841079492. Please let me know if it worked for you.

**Comment by didier** [comment]
@janpio I don't know. This is on Netlify, where I don't have filesystem access personally. This is the first time trying Prisma out on Netlify, and thus the first time I've encountered this.

**Comment by didier** [comment]
I don't think I'm able to make a reproduction repo, as this would require a hosted database somewhere.

**Comment by didier** [comment]
> A SvelteKit user had a very similar issue, please take a look at his comment [#7019 (comment)](https://github.com/prisma/prisma/issues/7019#issuecomment-841079492). Please let me know if it worked for you.

@millsp Do you have a code example or explanation of your fix? I find the linked answer rather vague. Netlify docs aren't too helpful in this case either.

**Comment by millsp** [comment]
@didier It would be helpful if you could provide a repro - no worries for the db.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
