### ISSUE TITLE
Better diffs for `schema.prisma` files

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7729]
This is 1 of many models diffs in a rather big Prisma Schema file (82 models) via the VSCode Git integration:

![image](https://user-images.githubusercontent.com/183673/122460467-70e33980-cfb2-11eb-9d80-0bc02f05d81e.png)

As you can see, the full model is detected as changed, as the formatting changed with the longer relation field names.

But even if I work around that by adding a faked relation to my "before" schema to get the same indentation for types, the resulting diff is pretty useless:

![image](https://user-images.githubusercontent.com/183673/122460872-efd87200-cfb2-11eb-8683-e573e13583ae.png)

It would be great if Prisma could support users better here with better tooling and developer experience.

Note: No fields were added, removed or really modified between these two schemas. The model fields were just re-sorted and relations were added.

**Comment by janpio** [comment]
Note: We used to have an internal tool that would count models, fields, type of fields, amount of types used and so on - this could already be interesting here as a first approximation if the schemas are identical in the important areas.

**Comment by maoosi** [comment]
@janpio to extend on this, one thing that would increase a lot my productivity would be a way to quickly diff between two Prisma Schema files locally (without having to run migrate commands or even touch the database) and directly output the result as SQL.

For example:

```shell
# input command
prisma diff schema1.prisma schema2.prisma --sql

# example output
ALTER TABLE Post ADD COLUMN `title` text;
```

This could also be extended to other output formats:

```shell
# input command
prisma diff schema1.prisma schema2.prisma --json

# example output
{
    "post": {
        "__new": [{
            "field": "title",
            "type": "text"
        }]
    }
}
```

**Comment by tomhoule** [comment]
Hi @maoosi — I also think that would be great, and the way migrate is implemented, it is definitely possible. It just needs some work going into figuring out the exact API, then implementation. Since perceived interest in a feature is an important factor for prioritization, opening a feature request issue would be a meaningful next step towards getting this worked on.

**Comment by maoosi** [comment]
> Hi @maoosi — I also think that would be great, and the way migrate is implemented, it is definitely possible. It just needs some work going into figuring out the exact API, then implementation. Since perceived interest in a feature is an important factor for prioritization, opening a feature request issue would be a meaningful next step towards getting this worked on.

Thanks @tomhoule, I have opened a new feature request: https://github.com/prisma/prisma/issues/7738

**Comment by Jolg42** [comment]
An easy workaround here is to pass the "Ingore whitespace" into your diff tool, most of them have this I think, for VS Code I found:
```
Add on your setting.json:
"diffEditor.ignoreTrimWhitespace": true,
```
https://stackoverflow.com/a/42038876/1345244

**Comment by janpio** [comment]
And that is about it, the spaces Prisma uses and diffing are fundamentally incompatible.
