### ISSUE TITLE
Not being able to use column in one to many relationship

### ISSUE THREAD

**Issue by jlorezz** [prisma/prisma#7735]
So the issue I am currently having is I can't actually find the column on my table that I am looking for. I am not sure if this is an issue or not. Could someone maybe help me?

This is my model that I currently created, and I somehow need to find the strategy used within my response.
![image](https://user-images.githubusercontent.com/29343633/122521246-e253d400-d014-11eb-8c0d-0bdf0c84ff35.png)

This is currently how I get the content from prisma.
![image](https://user-images.githubusercontent.com/29343633/122521435-18915380-d015-11eb-820d-ced08045f54d.png)

the issue is now that I can't actually access strategy on that response itself. 
![image](https://user-images.githubusercontent.com/29343633/122521575-48405b80-d015-11eb-8e8b-44609e61a361.png)

The error itself is this: 
`any
Property 'Strategy' does not exist on type 'User'.ts(2339)`

Why is this happening? Thanks for anyone giving feedback.

**Comment by ryands17** [comment]
You need to use `include` in `findUnique` as `Strategy` is a relation field. You can read more how to query relation fields here: https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#include-all-fields-for-a-specific-relation

**Comment by jlorezz** [comment]
Hey @ryands17, 
Thank you so much! I was on this problem for like 4 days now, wasn't sure what it was.
All the best, Florian.
