### ISSUE TITLE
Introspection error format has additional ' and bad error message for missing database on PlanetScale

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7736]
When the database does not exist on a MySQL server:

```
C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview>npx prisma introspect
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "migrationtest" at "127.0.0.1:56093"

Introspecting based on datasource defined in prisma\schema.prisma …
Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: Server error: `ERROR HY000 (1105): unknown database 'migrationtest''
```

1. See the additonal `'` at the end of the error string
2. "Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: Server error: "

**Comment by pantharshit00** [comment]
Hmm, I wasn't able to reproduce this on macOS:
```
╭─     ~/code/reproductions/issue-7736                                                        ✔  14.15.1    2.69G   ─╮
╰─ npx prisma introspect                                                                                                       ─╯
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "issue_7736" at "localhost:3306"

Introspecting based on datasource defined in prisma/schema.prisma …
Error: P1003

Database `issue_7736` does not exist on the database server at `localhost:3306`.
```

The error message is pretty different so are you implying the mysql schema doesn't exists on the database server or the database server doesn't exists altogether. I also wasn't able to reproduce for both of these cases.

**Comment by janpio** [comment]
I was testing against a database from Planetscale, with the connection opened via `pscale connect`. That produces different error messages and could be the cause for this problem. I accidentally had mistyped the database name.

**Comment by janpio** [comment]
This is still reproducible: Sign up to planetsacle, create a database, copy the connection string (remove the not needed anymore `sslcert` query parameter). Then introspect the empty database to see it succeed. Now type some random characters in the middle of the database name, and observe exactly the problems I described above.

**Comment by aqrln** [comment]
I can't reproduce this with latest Prisma using the steps in https://github.com/prisma/prisma/issues/7736#issuecomment-922055524, the error now looks like this:

```
✖ Introspecting based on datasource defined in prisma/schema.prisma

Error: VT05003: unknown database 'gh1-7736' in vschema
```

---

Unrelated to the original issue, but this step:
> remove the not needed anymore sslcert query parameter

did not work for me, removing this parameter leads to the following error:
```
Error: unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS
```
Adding `?sslaccept=strict'` back fixed that problem.
