### ISSUE TITLE
CLI command to output SQL diffs between Prisma Schema files

### ISSUE THREAD

**Issue by maoosi** [prisma/prisma#7738]
## Problem

Right now, there is no quick way to output SQL diffs between two Prisma Schema files.

Using Prisma across multiple environments and doing lots of experiments, I often find myself having to compare and update multiple Prisma Schema files - as well as writing associated SQL migration commands manually. Which is both time-consuming and error-prone.

## Suggested solution

Extend Prisma CLI to include a diff command such as:

```shell
# input command
prisma diff schema1.prisma schema2.prisma --sql

# example output
ALTER TABLE Post ADD COLUMN `title` text;
```

For my use case, the SQL output is what's most relevant, but we can imagine this working with other formats:

```shell
# input command
prisma diff schema1.prisma schema2.prisma --json

# example output
{
    "Post": {
        "__add": [{
            "column_name": "title",
            "data_type": "text"
        }]
    }
}
```

## Alternatives

The only alternative is using Prisma Migrate to generate a SQL migration file, however, it implies touching the database (as opposed to simply comparing local Schema files) and is not an efficient way to address the problem.

**Comment by floelhoeffel** [comment]
Hey @maoosi  - we have a proposal that also includes a command to diff schemas. Would be awesome if you would take a look and give us some feedback: https://github.com/prisma/prisma/issues/10561
