### ISSUE TITLE
Waiting "too long" to input migration name leads to error message

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7742]
When running a migration I forgot about it and only came back later to input the migration name. Then I got this error message:

```
C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview>npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "migratetest" at "127.0.0.1:61127"

√ Enter a name for the new migration: ... init
Error: Database error
Error querying the database: Server error: `ERROR 70100 (1317): held locks released: vttablet: rpc error: code = Aborted desc = transaction 1624011168192823451: ended at 2021-06-18 10:15:37.590 UTC (exceeded timeout: 20s) (CallerID: unsecure_grpc_client)'
   0: migration_core::api::ApplyMigrations
             at migration-engine\core\src\api.rs:73
```

**Comment by janpio** [comment]
Why are we even locking before we know the name of the local migration to create?

**Comment by sorenbs** [comment]
I have trained myself to decide on migration name before running `npx prisma migrate dev`, and then write is super fast to not hit the 20 second limit :-)

I wonder if this 20 second limit only applies to PlanetScale?

**Comment by janpio** [comment]
Related/Duplicate: https://github.com/prisma/prisma/issues/10997

**Comment by tomhoule** [comment]
Starting with next tuesday's release, we won't be taking locks on planetscale anymore.
