### ISSUE TITLE
Default enum generated by prisma migrate produces incorrect SQL

### ISSUE THREAD

**Issue by styxlab** [prisma/prisma#7753]
### Bug description

If you have defined an enum type in your schema and and add a default value for your enum field, prisma migrate produces incorrect SQL.

### How to reproduce

1. Schema:
```
enum Role {
  USER
  ADMIN
}
model User {
  id      Int      @default(autoincrement()) @id
  email   String   @unique
  name    String?
  role    Role     @default(USER)
}
```
2. npx prisma migrate dev --name init
3. produces:
```
-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN');

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "role" "Role" NOT NULL DEFAULT E'USER',

    PRIMARY KEY ("id")
);
```

How does the additional 'E' character come in?

### Expected behavior

prism migrate produces syntactically correct sql.

### Prisma Version

```
prisma               : 2.25.0
@prisma/client       : 2.25.0
```

**Comment by tomhoule** [comment]
String literals of the form `E'...'` are string literals with C-style escaping on postgres. You can read about them [in the official docs](https://www.postgresql.org/docs/9.2/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE). As far as I know they do work on all the versions we support. Did the database return an error or did something unexpected happen when you ran the migration?

**Comment by styxlab** [comment]
@tomhoule Thanks for the info, I didn't know it conforms to the standard.

The database I am using does have a problem with enums, but it turns out it's not due to the C - style SQL Syntax.
