### ISSUE TITLE
Prisma fails to generate artifacts with NodeJS Alpine image on M1 Mac

### ISSUE THREAD

**Issue by uncvrd** [prisma/prisma#7755]
### Bug description

Following the request from Jan [here](https://github.com/prisma/prisma/issues/5245#issuecomment-864247304), I've created this as a new ticket.

While attempting to build/run prisma using a NodeJS Alpine image, prisma fails to generate artifacts during the `postinstall` script, as a result, running the application cannot find generated models and typescript type-checking fails.

When observing the `npm install` logs, I note the following error:

`Error: Unknown binaryTarget linux-arm-openssl-undefined and no custom binaries were provided`. Which has been tracked before, but according to recent posts, this should still work within `Rosetta 2` emulation, right?

I should note, that if I run a general `FROM node:14`, the project builds no problem, using `FROM node:14-slim or alpine` fails. 

I've attached the docker build logs so you can see the failing script line here:

[build-output.txt](https://github.com/prisma/prisma/files/6679354/build-output.txt)

### How to reproduce

1. Use M1 Mac
2. Clone the following NestJS Prisma repo I've created: https://github.com/uncvrd/prisma-alpine-docker
3. Build the image using: `docker build -t [IMAGE TAG] --target development --no-cache --progress plain .`
4. Run the built image locally and observe the missing generated files

### Expected behavior

I expect to be able to build and run using `NodeJS Alpine` on M1 Mac. I can confirm that this `Dockerfile` works as expected on an Intel Mac so I guess the `Rosetta 2` emulation is not running as expected?

### Prisma information

Prisma schema etc. is referenced in the repository above.

### Environment & setup

- OS: Mac OS Big Sur 11.4
- Database: PostgreSQL
- Node.js version: 14 (in docker image)

### Prisma Version

```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```
^ ran this inside the docker container, I do find it interesting that it shows `darwin` as this is an `alpine` image running in the docker container?

**Comment by janpio** [comment]
Do you have another machine where you could try to run it in the same Docker image as here and see if this is indeed related to the Apple Silicon M1 you are running this on vs. the Docker image? (It can very well be the combination, but we better dig a bit before assuming that.)

**Comment by uncvrd** [comment]
Hey @janpio I have now tested on 3 different devices using the referenced repo:

- iMac M1: Fails during postinstall hook `Error: Unknown binaryTarget linux-arm-openssl-undefined and no custom binaries were provided`
- Macbook Pro M1: Fails during postinstall hook `Error: Unknown binaryTarget linux-arm-openssl-undefined and no custom binaries were provided`
- Macbook Pro Intel: Succeeds

Hope that helps, What can I help with next?

**Comment by janpio** [comment]
Not much, that sounds like it is indeed caused by using Apple Silicon and we will need to investigate.

Maybe one last thing, can you just create a local project on the M1 Mac and see if that works as it should?

**Comment by uncvrd** [comment]
@janpio sure! Running `npm install` locally (without a docker build) works perfectly, as in, it generates the artifacts upon postinstall as expected on the M1 Macbook.

![image](https://user-images.githubusercontent.com/25097099/122637284-98b1ca80-d0a2-11eb-981b-0b6b856d0746.png)

^ Artifacts generated properly on local npm install on M1 Macbook

May be helpful to remind that running a regular `FROM node:14` builds perfectly in docker, but the `node:14-alpine` does not.

**Comment by janpio** [comment]
Yep, we had problems with that in the past (related to OpenSSL or something), so this is probably a recurrence of that when running on Apple Silicon only (as you tested in Macbook Pro Intel, and it worked just fine with that image). From the error messages you are getting, I see that our code picking up the OpenSSL version is possibly broken here.

(Fair warning, this will not have our top priority to fix as it is an edgecase of and edgecase - although you are right in the middle of that unfortunately. But we will try to get to a reproduction soon, so we are sure this is worth for a developer to look at some time.)

**Comment by uncvrd** [comment]
Absolutely understand the low priority, luckily it's not much of a blocking issue, in the mean time I'll look in to building these images in the cloud.

**Comment by Brooooooklyn** [comment]
`node:lts-alpine` on m1 mac need `aarch64-unknown-linux-musl` target binary, and `node:lts` need `aarch64-unknown-linux-gnu` target. 

See: https://github.com/Brooooooklyn/snappy/blob/main/.github/workflows/CI.yaml#L58-L62

**Comment by janpio** [comment]
Wow thanks for that @Brooooooklyn, as usual. So seems we would need to build some more binaries... *sigh

**Comment by pantharshit00** [comment]
The platform matrix never seems to end 😅

**Comment by Tridie2000** [comment]
> so this is probably a recurrence of that when running on Apple Silicon only

I'm running into a similar issue on an Intel Mac. I'm trying to build an arm64 image so I can eventually run it on a Raspberry Pi. The following command `docker buildx build --platform linux/arm64 .`fails with the following error: `Error: Unknown binaryTarget linux-arm-openssl-undefined and no custom binaries were provided`.

This error only occurs when the Dockerfile extends from `node:12-alpine`, `node:12` builds fine.

**Comment by Satont** [comment]
Same here via `docker buildx build --platform linux/arm64 .`

**Comment by pantharshit00** [comment]
I think you need to install openssl using apk if the image doesn't contain openssl. Openssl is requirement for running Prisma. 

https://pkgs.alpinelinux.org/package/edge/main/x86/openssl

**Comment by Satont** [comment]
@pantharshit00 that's what i tried. Not a big deal use buster, to be honest.

**Comment by stingalleman** [comment]
Not using Alpina will result in really large Docker images, so it would be helpful if binaries get made for this situation.

**Comment by pantharshit00** [comment]
I think we need to build arm binaries with musl if we want to support this like we build x86 musl binaries.

**Comment by thvozdovic** [comment]
I was using the `node:16-slim` image, after changing it to `node:16` the error disappeared.

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/8478

**Comment by jrood** [comment]
> I think you need to install openssl using apk if the image doesn't contain openssl. Openssl is requirement for running Prisma.
> 
> https://pkgs.alpinelinux.org/package/edge/main/x86/openssl

I tried `apk add openssl`, and it got me a step further. Openssl seemed to need a file from `libc6-compat`, so I added that too, but then it still failed with a `__res_init: symbol not found` error.

As others have reported, this is only an issue for me using Alpine on M1. Debian on M1 seems to work fine.

**Comment by rodrigovenancioverissimo** [comment]
Try remove package-lock.json and build again

**Comment by greenchapter** [comment]
> Try remove package-lock.json and build again

No man not really, that is a problem with the base image…

**Comment by tianhuizhou** [comment]
Seems like relate to which version of Node docker image you use. I build it with some version like -slim or bullseye-slim, they all fail. But just regular version, it is fine

**Comment by greenchapter** [comment]
> Seems like relate to which version of Node docker image you use. I build it with some version like -slim or bullseye-slim, they all fail. But just regular version, it is fine

In my opinion when you would like to run anything within a docker container on production you should always decide to use an alpine version, e.g. node-alpine to reduce security issues.

**Comment by tianhuizhou** [comment]
Yea, I agree.

**Comment by gamenic-dipendra** [comment]
I was also facing the same issue with my **Mac M1**, and resolved by adding `--platform-linux/amd64` right after `FROM` in respective **dockerfile**.
```
FROM --platform=linux/amd64 node:14.19.0-alpine3.14
```
