### ISSUE TITLE
Relative `PRISMA_QUERY_ENGINE_BINARY` does not work in both CLI and Client

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7779]
If you use a relative path for `PRISMA_QUERY_ENGINE_BINARY` (like e.g. just the file name) it will either work in the CLI or the Client, but not in both:

1. Create folder, go into it, `npm init -y`, `npm install -D prisma`, `npm install @prisma/client`
2. `npx prisma -v`
2. Copy query engine into the project directly (e.g. `cp node_modules\@prisma\engines\query-engine-windows.exe query-engine-windows.exe`)
3. `npx prisma init`
4. `npx prisma generate`, add suggested model to schema file, `npx prisma generate` again
5. Set `PRISMA_QUERY_ENGINE_BINARY` to filename where you copied the file to (not absolute path)
6. Run `npx prisma -v` again to confirm CLI can use the binary
6. Create `script.js`:
	  ```
	  const PrismaClient = require('@prisma/client').PrismaClient
	  async function main() {
	    const prisma = new PrismaClient()
	    await prisma.$connect()
	  }
	  main()
	  ```
7. Set `DEBUG=*`
7. Run `node script.js`
8. Observe how the CLI tries to resolve the binary relative to the `prisma` subfolder and fails:
	  ```
	  λ node script.js
	    prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\relativeRepro\.env +0ms
	    ...
	    prisma:client clientVersion: 2.25.0 +0ms
	    prisma:engine { cwd: 'C:\\Users\\Jan\\Documents\\throwaway\\relativeRepro\\prisma' } +0ms
	    prisma:engine { flags: [ '--enable-raw-queries', '--port', '61969' ] } +129ms
	  (node:7604) UnhandledPromiseRejectionWarning: Error: spawn query-engine-windows.exe ENOENT
	      at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	      at onErrorNT (internal/child_process.js:465:16)
	      at processTicksAndRejections (internal/process/task_queues.js:80:21)
	  (Use `node --trace-warnings ...` to show where the warning was created)
	  (node:7604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
	  (node:7604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
	  ```

The `cwd` is set to the `prisma` folder, but for the CLI the actual folder where you are running the command is used as the starting point to find the query engine binary.

**Comment by pantharshit00** [comment]
I can reproduce this on a Mac.

**Comment by janpio** [comment]
Thanks for the quick repro, while you did that I figured out that relative paths do not seem to work at all in Client for this env var :( 

https://github.com/prisma/prisma/issues/7780

I am closing this here then as the other one seems to be the underlying reason.
