### ISSUE TITLE
Investigate and remove usage of `--forceExit`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7795]
- [ ] migrate
- [x] E2E
- [x] sdk
- [x] client
- [x] integration-tests
- [x] workflows

https://sourcegraph.com/search?q=context:global+repo:github.com/prisma/prisma+--forceExit+count:1000&patternType=literal
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/prisma/e2e-tests%24+forceExit&patternType=literal

Especially if introduced for Node-API, this is something we should try to get rid of again before GA.

**Comment by janpio** [comment]
Opened 2 PRs that show what is happening when you do this:
https://github.com/prisma/prisma/pull/7871
https://github.com/prisma/e2e-tests/pull/1853

**Comment by janpio** [comment]
- prisma: the `migrate` tests time out: https://github.com/prisma/prisma/pull/7871/checks?check_run_id=2915976895 + https://github.com/prisma/prisma/pull/7871/checks?check_run_id=2915976946
- e2e-tests: test-runners/jest-with-multi-gen times out for the binary (not node-api): https://github.com/prisma/e2e-tests/pull/1853/checks?check_run_id=2915975499

**Comment by millsp** [comment]
Work has begun over here https://github.com/prisma/prisma/pull/7989

**Comment by millsp** [comment]
Still need to do this for `migrate` and `E2E`.

**Comment by janpio** [comment]
Previous work on e2e: https://github.com/prisma/e2e-tests/pull/1853

**Comment by Jolg42** [comment]
Reopening, still need to investigate something with migrate dev tests.

**Comment by janpio** [comment]
Note-API part done then 🙇‍♀️
