### ISSUE TITLE
The starter project missing package `@types/node`

### ISSUE THREAD

**Issue by chenkai0520** [prisma/prisma#7800]
### Bug description

https://www.prisma.io/docs/getting-started/quickstart the starter project missing package `@types/node`

### How to reproduce

1. curl -L https://pris.ly/quickstart | tar -xz --strip=2 quickstart-master/typescript/starter
2. cd starter && npm install
3. npm run dev

```
Error: Cannot find module '@types/node/package.json'
```

### Environment & setup

- OS:  Mac O
- Database: SQLite
- Node.js version: v12.19.0

### Prisma Version

```
2.25.0
```

**Comment by janpio** [comment]
Fixed via https://github.com/prisma/quickstart/commit/68fd9589b5d1ce277f4ba5d8a1a298b0fec91cee

Thanks for the report!
