### ISSUE TITLE
Support for application_name argument in connection URL for postgres

### ISSUE THREAD

**Issue by vtdiep** [prisma/prisma#7804]
## Problem

I would like to identify which connection prisma is making to a postgres database, but it seems as though application_name is ignored in the connection URL.

## Suggested solution

Please support the application_name argument in the connection URL for postgres.

## Additional context

![image](https://user-images.githubusercontent.com/42816933/122920430-4082fe80-d316-11eb-81f2-a18701949027.png)
I believe that prisma is the first connection in the list, but even though the connection URL used has an application_name argument, it doesn't show up.

**Comment by Jolg42** [comment]
It's now possible to use in 2.28.0 release, Issue/PR can be found at https://github.com/prisma/tiberius/issues/159

>Available from Config method application_name and in the JDBC and ADO.net strings either with Application Name or
ApplicationName (case-insensitive).

**Comment by janpio** [comment]
No it is not, as that only applies to SQL Server @Jolg42 unfortunately.

**Comment by Jolg42** [comment]
Indeed, good catch! Added a candidate label.

**Comment by thebiglabasky** [comment]
Will need to look into the Postgres driver once we open that one up.
