### ISSUE TITLE
triggerPanic for Node-API Library

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7810]
To be able to test the error reporting mechanisms of the CLI, we will need to also support `triggerPanic` in the Node-API library as we do in the binary.

https://github.com/prisma/prisma/blob/120f04c6f833721ea9109379b299bb67b22dfcbc/packages/client/src/__tests__/integration/errors/error-link/test.ts#L8-L11

https://github.com/prisma/prisma/blob/fc7b272bfa7ee030c2c8dbede73e0da4963f4c67/packages/client/src/runtime/getPrismaClient.ts#L856-L886

**Comment by janpio** [comment]
Analysis:
- To allow usage of `triggerPanic`, `__internal.engine.enableEngineDebugMode` needs to be activated.
- When that is the case the binary Engine gets `--debug` on startup.
- `enableEngineDebugMode` does nothing like that in `LibraryEngine`.
- 1. We need a way to tell the engine about that on startup/instantiation  (similar to https://github.com/prisma/prisma/blob/50cd1526f0faf23feff9e9b950fe379b9a1515e1/packages/engine-core/src/library/LibraryEngine.ts#L367 maybe? Possibly even already exists as `debug` [from `--debug`]?)
- 2. In the Engine, an incoming `query` needs to check for the headers (in `headersStr`) similar to the binary

**Comment by janpio** [comment]
Binary side implementation:
https://github.com/prisma/prisma-engines/blob/36af3f44e00e1f6ae2ef08ebf105fb0120b43a66/query-engine/query-engine/src/server/mod.rs#L209-L229
https://github.com/prisma/prisma-engines/blob/36af3f44e00e1f6ae2ef08ebf105fb0120b43a66/query-engine/query-engine/src/server/mod.rs#L105-L109

**Comment by janpio** [comment]
Something got implemented, but it works a bit different and does not enable testing like implemented yet.

**Comment by Jolg42** [comment]
We could probably have a conditional on the test result here.
