### ISSUE TITLE
Node-API library and multiple PrismaClient instances

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7814]
How does Node API engine deal with multiple PrismaClient instances? Another “instance” of the lib with its own connection pool? What does this mean for the user? Change in behavior? Do we still need the "10 instances" warning?

https://github.com/prisma/prisma/blob/2680a44466ae0aed93c9665e7b2d437fbaec45ac/src/packages/engine-core/src/NodeEngine.ts#L267-L278

**Comment by janpio** [comment]
1 running app can create many `PrismaClient` instances. Each of those instances get their own Query Engine. Each Query Engine has its own connection pool of connection to the database.

**Comment by Ardian-Hoti** [comment]
> Basically everything is as before: One running app can create many `PrismaClient` instances. Each of those instances get their own Query Engine. Each Query Engine has its own connection pool of connection to the database.

Can I run multiple studios, like an app to store many database connection URL and for each db to run a prisma studio (in different ports if running multiple at the same time) and view/edit data for that db?
