### ISSUE TITLE
Serverless deployments: Just making a schema level change to a repository does not invalidate `node_modules` cache that contains generated Client

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7818]
This is more a theory than a bug report, but this could explain why sometimes deployments to Netlify and other deployment providers do not actually deploy a new schema.

Example: https://github.com/netlify/build-image/blob/d51b4da41df1087448804e27626a32d83f50380f/run-build-functions.sh#L184-L197 `npm install` is only run if the sha of `package.json` is different, which it does not have to be if you only updated your schema. No `npm install` means not post install hook, means no `prisma generate`.

We should get a better overview here by designing a few test setups, and testing them at a few of these potentially affected providers to see how they handle that.

**Comment by pantharshit00** [comment]
Most platforms provide a manual postinstall hook which can be used as a workaround here.

**Comment by janpio** [comment]
We should find a way to trigger that automatically or tell affected users about this, to avoid general confusion. This is one of the cases where we do not get issues, as "just try it again" often makes it work in the eyes of the user.

**Comment by millsp** [comment]
Related https://github.com/prisma/docs/issues/3590
