### ISSUE TITLE
DB pull & migration doesn't work for MongoDB

### ISSUE THREAD

**Issue by samayun** [prisma/prisma#7849]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.15.5           | 
| Prisma CLI  | 2.25.0             | 
| Binary      | c838e79f39885bc8e1611849b1eb28b5bb5bc922| 

## Error
```
Error: [/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/ed93633/src/single.rs:159:18] not implemented: Supported url schemes: file or sqlite, mysql, postgresql or jdbc:sqlserver.
```

**Comment by tomhoule** [comment]
Thanks for reporting this. There should be a better error message, because indeed, there is no migrate/db pull/db push on mongo.
