### ISSUE TITLE
"This is required as the NAPI library is not downloaded by default"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7873]
https://github.com/prisma/prisma/blob/9c287b3d45ae721f463b682651bd778cfab9d05a/src/packages/client/src/utils/generateInFolder.ts#L103-L114
https://github.com/prisma/prisma/blob/fdaec57bb8f0eb091600dbc6edf92da32542931b/src/packages/client/src/utils/getTestClient.ts#L51-L61

Why does this exist? Should it possibly only exit for the preview feature flag, which does not apply to the CLI? Or not at all, as the download will happen on demand if it is missing?

**Comment by janpio** [comment]
Both files seems to be for internal testing purposes (although for the first one, the name does not really imply it, but the uses of the function do), so this is probably because in the _normal_ Client generation the correct binary would be downloaded, but here it is not because this is special and hacked together in some way.

**Comment by Jolg42** [comment]
They are only used for tests indeed

**Comment by Jolg42** [comment]
Both are just for tests

Let’s make that clear in file and method names and we can close this.

**Comment by janpio** [comment]
Replaced by https://github.com/prisma/prisma/issues/8845
