### ISSUE TITLE
Generate snake_case SQL

### ISSUE THREAD

**Issue by Chrg1001** [prisma/prisma#7888]
Is there any way to get snake_case SQL from camelCase Prisma Schema?

For example,
I have Prisma Schema like this:

```prisma
model Post {
  @@map(post)
  id        Int     @id @default(autoincrement())
  isActive  Boolean @default(false) @map("is_active")
  author    User?   @relation(fields:  [authorId], references: [id])
  authorId  Int?    @map("author_id")
}
```

and I want to get SQL like this:

```SQL
CREATE TABLE post (
    id INT NOT NULL AUTO_INCREMENT,
    is_active BOOL DEFAULT false,
    author_id INT(11),
   PRIMARY KEY ( id )
);
```

however prisma generate  's output is like that:

```SQL
CREATE TABLE Post (
    id INT NOT NULL AUTO_INCREMENT,
    isActive BOOL DEFAULT false,
    authorId INT(11),
   PRIMARY KEY ( id )
);
```

I know Prisma has @map, @@map API, but they cannot fulfill my purpose because they do not affect generated SQL ( ex. new model, CREATE TABLE).

In short, I want to get snake_case SQL and camelCase Prisma Client from camelCase Prisma Schema.

I am using TypeORM now, and there is the way to achieve this issue (with Typeorm namig strategies), however I would like to migrate my project to Prisma.

Thank you,

**Comment by tomhoule** [comment]
Hi @Chrg1001 , `@map` and `@@map` should work with migrate and generate the right model names. If it doesn't it's a bug. We can check that, but maybe you can confirm?

**Comment by Chrg1001** [comment]
@tomhoule Sorry, this is my fault. There was a part where I forgot to write @map. It seems `map` works fine!!

**Comment by tomhoule** [comment]
Glad to read that it works :) Please don't hesitate to open issues if anything doesn't make sense or you have ideas for improvements. I'm going to close this issue, but feel free to reopen if it needs more attention.
