### ISSUE TITLE
Prepared statement needs to be re-prepared with sql views

### ISSUE THREAD

**Issue by jemink** [prisma/prisma#7906]
I created sql views with two tables called `Draft`
```
CREATE VIEW `Draft` AS
    SELECT company.address as address, company.id as id
    FROM `company`, `admin`
    WHERE `company`.`company_id` = `admin`.`id`;
```
Then added Draft model inside the schema.prisma like below
```
model Draft {
  id      Int    @unique
  address String
}
```

But when I run this query in playground I am getting below error with node js and with playground 
```
const data = await ctx.prisma.draft.findMany({})
 ```
![image](https://user-images.githubusercontent.com/28702189/123632446-90415880-d835-11eb-8975-90b37d73f9ac.png)

**Comment by janpio** [comment]
Can you share the SQL required for `company` so we can easily reproduce the full thing? That sounds a a bit weird.

What Prisma version and database are you using?

**Comment by ryands17** [comment]
@janpio related discussion: https://github.com/prisma/prisma/discussions/7924

**Comment by janpio** [comment]
Thanks, so SQL and models are posted in https://github.com/prisma/prisma/discussions/7924#discussioncomment-937903

Version information is:
```
"@prisma/client": "2.23.0",
"prisma": "2.23.0",

mariadb: 10.4.18-MariaDB-1:10.4.18+maria~focal
``

**Comment by binary64** [comment]
I wonder if this is relevent:
```
Also seems to be an equivalent bug in MariaDB 10.0, 10.1, 10.2, 10.3, 10.4, 10.1.34: jira.mariadb.org/browse/MDEV-17124 with similar workarounds (increase table_definition_cache to be larger than or equal to table_open_cache). – Jordan Rieger May 6 '20 at 19:02 
```
Source: https://stackoverflow.com/questions/4380813/how-to-get-rid-of-mysql-error-prepared-statement-needs-to-be-re-prepared

**Comment by pantharshit00** [comment]
Yeah does sound related, @jemink can you try the workaround posted?

I wasn't to reproduce with mysql and only with mariadb so does look like a mariadb bug.
