### ISSUE TITLE
groupBy is not usable with $transaction

### ISSUE THREAD

**Issue by leumasme** [prisma/prisma#7918]
### Bug description

Trying to use the unawaited return value of a prisma.<type>.groupBy(...) in a prisma.$transaction([...]) will result in a typescript Type error:

```
Type 'GetOrderGroupByPayload<{ by: "vendorId"[]; _sum: { price: true; }; }>' is not assignable to type 'PrismaPromise<any>'.
  Property '[prisma]' is missing in type 'Promise<(PickArray<OrderGroupByOutputType, "vendorId"[]> & { _sum: { price: number | null; }; })[]>' but required in type '{ [prisma]: true; }'
```
 It seems that all values passed into $transaction must have a property with a Symbol called prisma set to true. This is not the case for groupBy, but works for other queries/mutate actions like findMany, deleteMany, findUnique, ...

### How to reproduce

Using below minimal demo schema, this code errors:
```ts
 await db.$transaction([
    db.order.groupBy({
      by: ["vendorId"],
      _sum: {
        price: true,
      }
    })
  ])
```

### Expected behavior

$transaction should properly accept groupBy queries, running them as a transaction with other queries.

### Prisma information

```prisma
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Vendor {
  id     Int     @id
  Orders Order[]
}

model Order {
  id       Int    @id
  price    Float
  Vendor   Vendor @relation(fields: [vendorId], references: [id])
  vendorId Int
}
```

### Environment & setup

- OS: Windows 10
- Database: MySQL
- Node.js version: v14.15.4
- Typescript version: Version 4.3.2

### Prisma Version

```
prisma               : 2.25.0
@prisma/client       : 2.25.0
Current platform     : windows
Query Engine         : query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : c838e79f39885bc8e1611849b1eb28b5bb5bc922
Studio               : 0.402.0
```

**Comment by pantharshit00** [comment]
I can confirm this, looks like we forgot to use `PrismaPromise` type which we use to make sure people only pass prisma client calls to `$transaction`. 

cc @millsp 

Call actually works fine so disable typechecking using `//@ts-ignore` for now which is fix this.

**Comment by leumasme** [comment]
What's the status on this? It was added to the 2.28 milestone but wasnt updated since, and 2.28 is already out

**Comment by janpio** [comment]
As long as the issue is not closed, it is not done. Most probably other priorities took over in the team. (Internally I can see this needs another review/look and QA before we know if this is fixed or not)

**Comment by habhabsafi** [comment]
storing the prisma.groupBy batch in a constant and calling it in the transaction array works fine
the problem is that i am not sure if the batch gets executed when storing in the constant and then gets executed again inside the transaction

**Comment by millsp** [comment]
Hey @habhabsafi, could you share a code example?

**Comment by habhabsafi** [comment]
const countDataQuery = this.prisma.delivery.groupBy({
      by: ["status"],
      _count: {
        _all: true,
      },
      where: {
        createdAt: {
          gte: start_date,
          lte: end_date,
        },
        confirmedByAdmin: {
          sub: user.sub,
        },
        status: {
          not: {
            in: newDeliveryArrayOfStatus,
          },
        },
      },
    });
    const newDeliveriesQuery = this.prisma.delivery.count({
      where: {
        createdAt: {
          gte: start_date,
          lte: end_date,
        },
        status: { in: newDeliveryArrayOfStatus },
      },
    });
    const [newDeliveries, countData] = await this.prisma.$transaction([
      newDeliveriesQuery,
      countDataQuery,
    ]);

**Comment by millsp** [comment]
Yes, if I understood correctly your question: No prisma queries only get executed if you await them or pass them through a transaction. So in your case, it only executes once for each query via `$transaction`.

**Comment by Jolg42** [comment]
See https://github.com/prisma/docs/issues/800 (it's only mentioned once in the docs)

**Comment by Malachite40** [comment]
getting the same issue

**Comment by Jolg42** [comment]
@Malachite40 this issue was closed 2 years ago. 

Please open a new issue if you want us to look at your problem.
