### ISSUE TITLE
Ability to include non-db data in results returned by Prisma

### ISSUE THREAD

**Issue by Alwigi** [prisma/prisma#7922]
## Problem

It appears that appending/manipulating data return by Prisma currently is currently only handled by raw sql or manual data updates at application level.
Both these methods have disadvantages ie. raw sql means losing most ORM benefits and an inconsistent query language across the application, manual updates mean a secondary loop through the data which doesn't seem necessary.

The idea is to be able to change returned data the same way that the sql as below would do:
    select 'abc' + field1, field2 from users

## Suggested solution

Build this feature into Prisma's query language, perhaps something similar to:

      const res = await context.prisma.user.findUnique({
        where: {
          userid: id
        },
        transform: {
	  field1: 'abc'+field1,
          field2: field1+' '+field2
	}
      })

**Comment by janpio** [comment]
Could Prisma Middlewares be an answer to your question? https://www.prisma.io/docs/concepts/components/prisma-client/middleware

**Comment by Alwigi** [comment]
> Could Prisma Middlewares be an answer to your question? https://www.prisma.io/docs/concepts/components/prisma-client/middleware

Yes @janpio I guess middleware could be an option, it does feel like an overkill to run through this for every query just to update one field tho.

I did find this option too which is great, although it would only be for graphql: https://v1.prisma.io/tutorials/a-guide-to-common-resolver-patterns-ct08/#scenario:-add-a-custom/computed-field-to-a-prisma-model-via-the-application-schema-prisma-bindings

**Comment by janpio** [comment]
I think middlewares are made exactly for that - to modify the query parameters or to modify the returned data. 

(Unfortunately just adding additional fields is not as easy even with the middlewares, as the types are precomputed and would not include that field. I am not 100% if that is what you want to achieve.)

On the API level, you can do whatever you want of course - if e.g. your GraphQL setup allows you to change the data you get from Prisma, nothing is stopping you.

**Comment by Alwigi** [comment]
Thanks @janpio I can accept that middelware is the solution then due to the reasons you mention.
The computed field option suits me better so I'm using that for now.

**Comment by pantharshit00** [comment]
We already have an issue for virtual/computed fields so I am going to close this: https://github.com/prisma/prisma/issues/3394
