### ISSUE TITLE
2.26.0 and `pnpm` do not play well together

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7934]
> Is it possible to take a look at what is going on trying to use 2.26.0 with pnpm? version 2.23.0 works just fine and in every project I use prisma I had to pin the version to 2.23.0
>
> Minimal repo reproducing this issue with some instructions and screenshots in the README:
>
> https://github.com/PabloSzx/pnpm-prisma-bug

_Originally posted by @PabloSzx in https://github.com/prisma/prisma/discussions/7925#discussioncomment-939511_

**Comment by janpio** [comment]
Related discussion in Slack: https://prisma.slack.com/archives/CA491RJH0/p1624987952326500

**Comment by janpio** [comment]
Working version to be able to see it succeed, and test version upgrades in between: https://github.com/PabloSzx/pnpm-prisma-bug/tree/working-version

**Comment by Jolg42** [comment]
Could be related to
https://github.com/prisma/prisma/issues/5340

**Comment by PabloSzx** [comment]
The pr #7942 seems to have fixed it, tested it in a couple projects and everything works correctly 🎉 

You can also test it with these versions in your projects
```
"prisma": "2.27.0-integration-fix-sdk-pnpm.1",
"@prisma/client": "2.27.0-integration-fix-sdk-pnpm.1",
```
