### ISSUE TITLE
How can I set connection_limit and pool_timeout in my connectionstring when my database is MySQL?

### ISSUE THREAD

**Issue by jahanalem** [prisma/prisma#7935]
I tested these connectionstrings but they didn't work.
"mysql://root@localhost:3306/gamma_db&connection_limit=40&pool_timeout=20"
"mysql://root@localhost:3306/gamma_db?connection_limit=40?pool_timeout=20"

**Comment by janpio** [comment]
URL parameters are usually separated with `?` for the first one, then `&` for all the following:
```
mysql://root@localhost:3306/gamma_db?connection_limit=40&pool_timeout=20
```

**Comment by pantharshit00** [comment]
Looks like this is resolved.
