### ISSUE TITLE
Undo "skip flaky referentialActions sql server test"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7936]
https://github.com/prisma/prisma/pull/7907

**Comment by janpio** [comment]
This might already have happened? 
https://github.com/prisma/prisma/blob/main/packages/client/src/__tests__/integration/happy/referentialActions-onDelete-cascade-sqlserver/test.ts

**Comment by Jolg42** [comment]
This is not the same test.

It is still skipped here
https://github.com/prisma/prisma/blob/main/packages/client/src/__tests__/integration/errors/referentialActions-onDelete-default-foreign-key-error-sqlserver/test.ts#L7-L10

I'll open a PR
