### ISSUE TITLE
Prisma Client is really slow

### ISSUE THREAD

**Issue by YassinEldeeb** [prisma/prisma#7937]
I've tried using prisma-client to get all the users from a local postgres database which is running in a docker container, but when I looked at how much time prisma took to get the data, it's around 200ms however the generated sql was perfectly fine.

![Screenshot 2021-06-30 004619](https://user-images.githubusercontent.com/72823042/123877969-7e97a800-d93e-11eb-9ae9-72b542bb6684.png)

I searched for any popular node.js client to test my postgres database if the problem was from it, then I chose node-postgres and copied the sql prisma used to get the data and paste it and surprisingly it took 2ms.

![Screenshot 2021-06-30 004756](https://user-images.githubusercontent.com/72823042/123878118-c28aad00-d93e-11eb-8ccd-36ac72c9546e.png)

I don't know what is slowing prisma client, please anyone who can explain what's slowing it that much or give me solutions if there was a problem cause I'm completely new to prisma.

**Comment by janpio** [comment]
Does https://github.com/prisma/prisma/issues/6301 help?

**Comment by YassinEldeeb** [comment]
> 
> 
> For Prisma you are measuring both the time to connect to the database, and run the query. For the Node Pg Client you are doing a connect() outside your measurement. If you move that in, you should get numbers that are closer together.
> 
> As soon as you do multiple requests at the same time, Prisma will use an internal connection pool to reuse connections, while your Postgres Client implementation will open a new connection each time (although the library of course also has a mode to pool connections).
> 
> Additionally: Does #6301 improve the Prisma numbers a bit?

**Comment by YassinEldeeb** [comment]
I tested it again, after inserting a bunch of users twice to let prisma establish the pool connection then I requested all users and measured how much does prisma took to get the data and surprisingly it took 7-9ms and when I enabled napi in my prisma-client now it's taking 4-5ms after two operations and 35ms from the first one which is a lot better.

**Comment by danil-iglu** [comment]
@YassinEldeeb you can speed it up with [https://www.npmjs.com/package/prisma-sql](https://www.npmjs.com/package/prisma-sql)
