### ISSUE TITLE
MongoDB Introspection

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7965]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`introspect`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.17.0           | 
| Prisma CLI  | 2.26.0-dev.49      | 
| Binary      | 9b816b3aa13cc270074f172f30d6eda8a8ce867d| 

## Error
```
Error: [/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/9f5860e/src/single.rs:159:18] not implemented: Supported url schemes: file or sqlite, mysql, postgresql or jdbc:sqlserver.
```

error report id: 13392

**Comment by tomhoule** [comment]
Closing as a duplicate of https://github.com/prisma/prisma/issues/7849
