### ISSUE TITLE
Inconsistent errors with different commands

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#8013]
### Bug description

The error output differs in color and pacing with different migration and introspection commands.
![2021-07-02_15-07-1625233718](https://user-images.githubusercontent.com/34967/124284298-24b8fd00-db4d-11eb-93fa-eb528e12c343.png)

- `db pull` is completely red.
- `db push` has the `Error:` in red, other text in white. Missing whitespace after the Datasource.
- `db migrate dev` is like `db push`, but has whitespace after the Datasource.

### How to reproduce

```shell
npx prisma db pull
npx prisma db push
npx prisma migrate dev
```

### Expected behavior

Some consistency would be great here.

### Environment & setup

Every OS in the world.

### Prisma Version

```
2.26.0
```

**Comment by pimeys** [comment]
![2021-07-02_15-07-1625234360](https://user-images.githubusercontent.com/34967/124285719-7c0b9d00-db4e-11eb-8902-fe7edabf26d7.png)

moar

**Comment by pantharshit00** [comment]
I can reproduce this. 

![image](https://user-images.githubusercontent.com/22195362/126970466-e4a9cc14-1de4-4546-8dd0-2628b1666308.png)

**Comment by Jolg42** [comment]
Fun fact, mongodb error comes from engine (similar one is in TS as well)
https://github.com/prisma/prisma-engines/blob/master/introspection-engine/core/src/rpc.rs#L80

With PR looks like 
<img width="573" alt="Screen Shot 2021-09-29 at 14 43 08" src="https://user-images.githubusercontent.com/1328733/135270674-f3122893-d1c5-404e-8a8b-39fcfc4523e8.png">
