### ISSUE TITLE
`db seed` error messages talk about `in the prisma directory`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8030]
https://github.com/prisma/prisma/blob/30773b7ca34f104b2dc50581cf5e1046cbd27bf1/src/packages/migrate/src/__tests__/DbSeed.test.ts#L25
https://github.com/prisma/prisma/blob/30773b7ca34f104b2dc50581cf5e1046cbd27bf1/src/packages/migrate/src/__tests__/DbSeed.test.ts#L43
https://github.com/prisma/prisma/blob/30773b7ca34f104b2dc50581cf5e1046cbd27bf1/src/packages/migrate/src/__tests__/DbSeed.test.ts#L58

The seed files should be located next to the schema file though.

**Comment by Jolg42** [comment]
Closing, because redesign of db seed removes that https://github.com/prisma/prisma/pull/8146
