### ISSUE TITLE
Advisory Locking doesn't timeout after 10s

### ISSUE THREAD

**Issue by meotimdihia** [prisma/prisma#8038]
### Bug description

The documentation said advisory locking has timeout 10s
https://www.prisma.io/docs/concepts/components/prisma-migrate#advisory-locking
But it is not on my server.
![fPlpeNo 1](https://user-images.githubusercontent.com/300961/124349653-7f6c5a80-dc1a-11eb-8d3e-2c5d46020a08.png)

### How to reproduce

`yarn prisma migrate resolve --applied 20210702045017_auth_migration`

### Expected behavior

Timeout is 10s

### Environment & setup

- OS: Ubuntu 20
- Database: PostgreSQL 13
- Node.js version: 14

### Prisma Version

```
2.26
```

**Comment by meotimdihia** [comment]
It seems I can't fix this problem :(
```
Error: P1002

The database server at `localhost`:`5432` was reached but timed out.

Please try again.

Please make sure your database server is running at `localhost`:`5432`.

Context: Timed out trying to acquire a postgres advisory lock (SELECT pg_advisory_lock(72707369)). Elapsed: 10000ms. See https://pris.ly/d/migrate-advisory-locking for details.
```

**Comment by tomhoule** [comment]
For the last message @meotimdihia there is a connection holding the lock — if you stop the migrate process that has the lock, it will be released automatically. I think the lock behavior was documented a bit hastily, we should make sure we align the implementation and the documented behaviour.

**Comment by meotimdihia** [comment]
@tomhoule: this message always happen, even though I killed processes holding the lock.

**Comment by meotimdihia** [comment]
I have used this query to check
![WindowsTerminal_2021-07-04_15-23-30](https://user-images.githubusercontent.com/300961/124378512-e0a83280-dcdb-11eb-9070-c76bba652c42.png)
:

**Comment by tomhoule** [comment]
Are you starting the process that is timing out manually? Is it possible that the method you are using is starting multiple migrate processes, so that they lock each other out? If it keeps happening, we should definitely look more into this. Otherwise running `SELECT pg_advisory_unlock_all();` in psql should release all the locks.

**Comment by meotimdihia** [comment]
@tomhoule thanks 🙏, it works after I run command `SELECT pg_advisory_unlock_all();`
I think I didn't understand how migration work. I am creating migrations for the existing database. 
I think we could close the issue.

**Comment by pantharshit00** [comment]
I opened a docs issue and I am closing this.

**Comment by pantharshit00** [comment]
https://github.com/prisma/docs/issues/2056

**Comment by meotimdihia** [comment]
Hi, the query `SELECT pg_advisory_unlock_all();` doesn't work for me now. I have to restart Postgresql to fix this bug.

**Comment by meotimdihia** [comment]
The problem seems to happen when I forgot and run `migration deploy` with Pgbouncer port.

And then it doesn't work even though I run query `SELECT pg_advisory_unlock_all();` . And run again with Postgresql port.

Currently, I have to manually switch to PostgreSQL port when run `prisma migrate`.

...

**Comment by pantharshit00** [comment]
That is kind of expected. I don't that you can acquire a advisory lock over pgbouncer. We should probably add this to FAQ or some other docs
 section

**Comment by janpio** [comment]
https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-limitations-issues#prisma-migrate-and-pgbouncer
