### ISSUE TITLE
Broken link on Prisma website

### ISSUE THREAD

**Issue by miketromba** [prisma/prisma#8048]
### Bug description

Hello, I stumbled on a broken link on the Prisma website. I would submit a PR but I couldn't find the prisma.io website repo. 

### How to reproduce

It appears [this page](https://www.prisma.io/graphql) when you click the "[Nexus (code-first)](https://gyazo.com/31b57c24c616fac8fdb7b5d91beef322)" tab and scroll to the bottom where it says "[nexus-plugin-prisma](https://gyazo.com/95131e7af12506bff9f29559d35b848e)."

### Expected behavior

The link should point to: 
https://nexusjs.org/docs/plugins/prisma/overview
(one "s" in /plugins/ instead of two)

Instead of:
https://nexusjs.org/docs/pluginss/prisma/overview

### Prisma information

N.a

### Environment & setup

N.a

### Prisma Version

N.a

**Comment by janpio** [comment]
Thanks for the report, quickly fixed it. The link used to be called like this but is not any more now.
