### ISSUE TITLE
Different error message after upgrade to 2.26.0 and enabling `referentialActions` preview feature flag

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8054]
This is from a user report (https://prisma.slack.com/archives/CA491RJH0/p1624978739315200), minimized and reproduced here:

### Initial repro setup
- Clone starter project: https://www.prisma.io/docs/getting-started/quickstart/#1-download-the-starter-project
- Change prisma version to 2.25.0 in `package.json` 
- Run `npm i`
- Add this data model to `schema.prisma`:
	```prisma
	  model Buyer {
	    id           String        @id
	    buyerGroupId String
	    buyerGroup   BuyerGroup @relation(fields: [buyerGroupId], references: [id])
	  }
	  
	  model BuyerGroup {
	    id     String     @id
	    buyers Buyer[]
	  }
	```
- Create a migration and run it with `npx prisma migrate dev`
- Observe create SQL migration:
   ```sql
	  -- CreateTable
	  CREATE TABLE "Buyer" (
	      "id" TEXT NOT NULL PRIMARY KEY,
	      "buyerGroupId" TEXT NOT NULL,
	      FOREIGN KEY ("buyerGroupId") REFERENCES "BuyerGroup" ("id") ON DELETE CASCADE ON UPDATE CASCADE
	  );
	  
	  -- CreateTable
	  CREATE TABLE "BuyerGroup" (
	      "id" TEXT NOT NULL PRIMARY KEY
	  );
   ```
- Update `script.ts` to contain this code:
   ```ts
	  const prisma = new PrismaClient({
	    log: ['query', 'info', `warn`, `error`],
	  })
	  
	  async function main() {
	    console.log('deleted buyers:', await prisma.buyer.deleteMany())
	    console.log('deleted buyerGroups:', await prisma.buyerGroup.deleteMany())
	  
	    await prisma.buyer.create({
	      data: {
	        id: 'Buyer A',
	        buyerGroup: {
	          create: { id: 'Group A' },
	        },
	      },
	    })
	  
	    try {
	      await prisma.buyerGroup.delete({
	        where: {
	          id: 'Group A'
	        }
	      })
	    } catch(e) {
	      console.log(e)
	    }
	  }
   ```
- Now you are in position to reproduce

### Behavior with old version

- Run the script to try deleting a record with a required relation, `npx ts-node script.ts`
- Observe error P2014:
```
C:\Users\Jan\Documents\throwaway\refActionsError>npx ts-node script.ts
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.buyerGroup.delete()` invocation:


  The change you are trying to make would violate the required relation 'BuyerToBuyerGroup' between the `Buyer` and `BuyerGroup` models.
    at cb (C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\@prisma\client\runtime\index.js:33816:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'P2014',
  clientVersion: '2.25.0',
  meta: {
    relation_name: 'BuyerToBuyerGroup',
    model_a_name: 'Buyer',
    model_b_name: 'BuyerGroup'
  }
}
```
✅ This is the expected behavior of this version - the `Buyer` would become invalid with the `BuyerGroup` not existing any more, so it is blocked by the old Query Engine.

### Behavior with 2.26.0 without preview feature

- Delete `node_modules`
- Change version in  `package.json` to 2.26.0
- `npm i`
- Run the script again to delete, get the same error:
```
C:\Users\Jan\Documents\throwaway\refActionsError>npx ts-node script.ts
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.buyerGroup.delete()` invocation:


  The change you are trying to make would violate the required relation 'BuyerToBuyerGroup' between the `Buyer` and `BuyerGroup` models.
    at cb (C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\@prisma\client\runtime\index.js:33896:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'P2014',
  clientVersion: '2.26.0',
  meta: {
    relation_name: 'BuyerToBuyerGroup',
    model_a_name: 'Buyer',
    model_b_name: 'BuyerGroup'
  }
}
```

✅ This is the expected behavior of the new version as well - without the preview feature flag the behavior should stay unchanged.

### Behavior with 2.26.0 with preview feature enabled (no database upgrade)

- Add preview feature flag `previewFeatures = ["referentialActions"]`to `generator client` in `schema.prisma`
- Generate Client with `npx prisma generate`
- Run the script again, this time the entry is deleted without error

✅ This is the expected behavior of this version as well - with the preview feature flag but no database update the old `ON DELETE CASCADE` SQL default becomes active and the data is deleted (see warnings in release notes ⚠️ ).

### Behavior with 2.26.0 with preview feature (after database upgrade)

- Now run `npx prisma migrate dev` to update the database to reflect the new `onDelete` default (as there is no explicit `onDelete` in the schema.)
- Observe the SQL schema change:
   ```sql
	  -- DropForeignKey
	  ALTER TABLE "Buyer" DROP CONSTRAINT "Buyer_buyerGroupId_fkey";
	  
	  -- AddForeignKey
	  ALTER TABLE "Buyer" ADD FOREIGN KEY ("buyerGroupId") REFERENCES "BuyerGroup"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
   ```
- Run the script again and now get this new error:
```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]:
Invalid `prisma.buyerGroup.delete()` invocation:


  Foreign key constraint failed on the field: `Buyer_buyerGroupId_fkey (index)`
    at cb (C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\@prisma\client\runtime\index.js:33896:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'P2003',
  clientVersion: '2.26.0',
  meta: { field_name: 'Buyer_buyerGroupId_fkey (index)' }
}
```

❓ Technically this behavior is expected as by running `migrate dev` (or `db push`) the user put the new defaults in his database. They were still surprised, as this is not explicitly called out in the release notes that the _error messages_ of something might change.

**Comment by albertoperdomo** [comment]
Created https://github.com/prisma/docs/issues/1974 for us to cover this in our documentation.

**Comment by pantharshit00** [comment]
Closing as related issue was fixed.
