### ISSUE TITLE
No way to create migration file without working database connection

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8056]
I wanted to just see the SQL for a SQL Server schema, but Migrate has no command that works for that without a working database connection:

```
C:\Users\Jan\Documents\throwaway\sqlServerCycles>npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db" - SQL Server

Error: Migration engine error:       
Database error
Error creating a database connection.


C:\Users\Jan\Documents\throwaway\sqlServerCycles>npx prisma migrate dev --create-only
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db" - SQL Server

Error: Migration engine error:       
Database error
Error creating a database connection.


C:\Users\Jan\Documents\throwaway\sqlServerCycles>npx prisma db push                  
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db" - SQL Server
Error: Migration engine error:
Database error
Error creating a database connection.
```

**Comment by pantharshit00** [comment]
Is this even possible? I believe migrate diffs against the shadow database to generate the migrations but I am not sure.

**Comment by janpio** [comment]
That is exactly the use case not supported - I have a schema file, and I want to see the SQL that Migrate would create in a file to look at. Without a working (empty) database, that is just not possible right now.

**Comment by Jolg42** [comment]
Related https://github.com/prisma/prisma/issues/7738

**Comment by m1212e** [comment]
Any progress on this? There are definietly some use cases where this could become handy. In my current CI/CD this feature would be very helpful!

**Comment by Jolg42** [comment]
Hi @m1212e, so we are working on a set of primitives for Migrate, see https://github.com/prisma/prisma/issues/10561
Your feedback will be very welcome there, I think `prisma migrate diff` would be something that could work for you.

If you have more details on the use cases you mentioned we are definitely interested.

**Comment by tomhoule** [comment]
`prisma migrate diff --from-empty --to-schema-datamodel ./prisma/schema --script` :magic_wand:

**Comment by Evilu** [comment]
> `prisma migrate diff --from-empty --to-schema-datamodel ./prisma/schema --script` 🪄

King.
