### ISSUE TITLE
Better error message for "Value out of range for the type. The column rolled_back_at contained an invalid datetime value with either day or month set to zero."

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8060]
Follow up from: https://github.com/prisma/prisma/issues/7747

When encountering a zero datetime value, we should output a more helpful error message with a pris.ly link to https://github.com/prisma/prisma/issues/5006 This way users will be able to learn what is going on and why and adapt there Prisma schema. (Later this could be replaced with a documentation link of course that explains our limitation better.)

**Comment by tomhoule** [comment]
This is already a message we (I) wrote, we are already catching this in quaint. It would only be a matter of changing the message for that particular instance. I removed `topic: migrate dev` because it would affect Client and the whole product surface as well.

**Comment by laurinenas** [comment]
Thanks for the comment @janpio

What do you think if we also include some context to given error, such as table name or the values causing the error to happen?

You mentioned that changing that in [quaint](https://github.com/prisma/prisma-engines/blob/473ed3124229e22d881cb7addf559799debae1ab/quaint/src/connector/mysql/native/conversion.rs#L274) would affect the whole product surface.

Would you be so kind and elaborate a bit more on what those downstream changes are?
As user of prisma I see a lot of value in this and would really appreciate bits of more information in the error message, so it would help the debug process. Therefore, it would be nice to know if the effort is worthwhile.

I would be happy to open a PR, should you say this still has a chance.

Thank you very much for your answer in advance.

**Comment by janpio** [comment]
That sounds like a great suggestion @laurinenas. Improving this error message could indeed help, so please just open a quick issue with your suggestion and @ mention me in there and then I can give the 👍. I see nothing speaking against us improving this error message. (Optimally we also have some test cases for it then of course)
