### ISSUE TITLE
Drift detection makes CLI output where bold

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8063]
![image](https://user-images.githubusercontent.com/183673/124385149-df273c00-dcd4-11eb-9b9b-03c46236f639.png)

Intended that the full output is bolded?

**Comment by tomhoule** [comment]
That's a question for @Jolg42  — I like the attention drawing bold font for dev diagnostics personally, but I don't know if it's intentional.

**Comment by Jolg42** [comment]
The bold text here is from `devDiagnostic.action.reason`
<img width="676" alt="Screen Shot 2021-07-06 at 17 50 23" src="https://user-images.githubusercontent.com/1328733/124630381-a9c05100-de82-11eb-9dee-f097f6587949.png">

It's printed as part of the prompt here https://github.com/prisma/prisma/blob/15e1ca308c3e4fe3036d9326f83c27ed1a40c0c9/src/packages/migrate/src/commands/MigrateDev.ts#L322

From what I see the bold comes from passing the text to the "prompts" lib which adds bold to all the text passed.

So not intended I think. We could print the reason independently as console.info and then do the prompt.

**Comment by janpio** [comment]
Similar is true for the `reset`:
![image](https://user-images.githubusercontent.com/183673/125143068-b90cfc00-e119-11eb-84af-515e5019af5d.png)

**Comment by rubiagatra** [comment]
Let me help with this one, already made the PR at #9329
