### ISSUE TITLE
Postinstall generate failure error message might be misleading

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8066]
```
remote:        Environment variables loaded from .env
remote:        Prisma schema loaded from prisma/schema.prisma
remote:        info The postinstall script automatically ran `prisma generate`, which failed.
remote:        The postinstall script still succeeds but won't generate the Prisma Client.
remote:        Please run `prisma generate` to see the errors.
```

Does this _actually_ mean it ran `prisma generate`? Or did it run the same code that would run when running the appropriate `prisma generate` command?

If so, we should find a better way to express this. The current working leads people to investigate what happens when you run `prisma generate`, which often will indeed be a failure (but for very other reasons): https://github.com/prisma/prisma/discussions/8065#discussion-3445068

**Comment by pantharshit00** [comment]
I would mark this as an improvement instead.

**Comment by janpio** [comment]
> Does this _actually_ mean it ran `prisma generate`? Or did it run the same code that would run when running the appropriate `prisma generate` command?

Current code indeed runs `prisma generate` but via the CLI script, not `npx prisma` or similar.
