### ISSUE TITLE
CLI: Add deprecation notice to prisma introspect (renamed db pull)

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/prisma#8078]
prisma introspect is being replaced with prisma db pull.
We should add a deprecation notice so that users are aware that the command will eventually go away in the future (not set date for sunsetting yet, we'll provide enough time).

**Comment by janpio** [comment]
Note: Notice should be both in help output and when using the command. We should also double check if the command `introspect` is mentioned anywhere else (error messages, help output, and so on so it is really _gone_ and invisible unless you use it because you know about it.)
