### ISSUE TITLE
Simple insertOrUpdate (insert ... on duplicate key update)

### ISSUE THREAD

**Issue by dotMortis** [prisma/prisma#8134]
## Problem

I want to create an ez "insert ... on duplicate key update" query.
I see no reason why this should only be possible via a raw query.

```typescript
prisma.myTable.insertOrUpdate({data: {a: 1, b: 2, c: 3}, overwrite: {a: true, c: true}})
```

**Comment by pantharshit00** [comment]
Doesn't upsert solve this for you: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#upsert

Upsert basically will insert if `where` condition is not met, otherwise it will update the record which sounds like what you are describing.

**Comment by Haruki-Mortis** [comment]
@pantharshit00 Thank you for your answer.
Sure, it works, as far as I can see.
But why not use the native function from the database? :D
Would be nice to see this in a future release.

**Comment by janpio** [comment]
Isn't `upsert`, that @pantharshit00 linked to, doing exactly that? What is the difference you are hoping to see here?

**Comment by shtse8** [comment]
> Doesn't upsert solve this for you: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#upsert
> 
> Upsert basically will insert if `where` condition is not met, otherwise it will update the record which sounds like what you are describing.

Does `upsert` cannot work in `$transaction`? as it returns ` Prisma.Prisma__DataClient<Data>` instead of `PrismaPromise`.
I tried to use `upsert` in transaction, but the executed `upsert` before error didn't roll back.

**Comment by Akxe** [comment]
The upsert solves this for a single row, but upsert many are still missing and thus, doing something like refreshing imported data is very complex of must be done manually.

`INSERT ... ON DUPLICATE KEY UPDATE` would solve this.
(related: https://github.com/prisma/prisma/issues/10362)

**Comment by leafyshark** [comment]
@Akxe suppose I have an API that allows car dealerships to post their stock feed to my website. I want my API to be in sync with their website, so when they mark a car as sold, it is also marked as sold on my website. Any idea how to achieve this with Prisma in its current form?

Thanks in advance!

**Comment by janpio** [comment]
I am closing this for now, please open a new issue if you need MySQL's `INSERT ... ON DUPLICATE KEY UPDATE` specifically (support for PostgreSQL's `ON CONFLICT` will be added in 4.6.0, an update will be posted in https://github.com/prisma/prisma/issues/3242)

**Comment by leafyshark** [comment]
Actually I managed to achieve what I was looking for using create/update in nested writes within a for... of loop.

I will take a look into POSTGRESQL ON CONFLICT. Thanks!

**Comment by rolfen** [comment]
> @pantharshit00 Thank you for your answer. Sure, it works, as far as I can see. But why not use the native function from the database? :D Would be nice to see this in a future release.

Because you are using Prisma
