### ISSUE TITLE
Prisma Client  crashed when provided incorrect data in entity's create() method.

### ISSUE THREAD

**Issue by janconc** [prisma/prisma#8155]
Hi Prisma Team! My Prisma Client just crashed. This is the report:

## User's note:
bellow is the generated error and I could find the problem in it - I was trying to create an entity, providing accidentally `id` of type UniqueIdentifier with a string data (hence `Conversion failed when converting from a character string to uniqueidentifier`). I was supposed to provide `bookId` of type string in the creation `data` instead (and that works). So on my side problem solved but I thought you may still want to see the ugly crash report.

Note: somewhat surprising to see GraphQL/terminology in the context of ORM. But let's not go into implementation details here... :)

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.26.0             |
| Query Engine    | query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d|
| Database        | undefined|

## Query
```
mutation {
  createOneBookAccess(data: {
    id: "X"
    groupOid: "X"
  }) {
    id
    groupOid
    bookId
  }
}
```

## Logs
```
78m
  prisma:engine Engine Version: query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d  
  prisma:engine Active provider: sqlserver  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  Commit transaction  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine stdout  Begin transaction  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  Conversion failed when converting from a character string to uniqueidentifier.  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  The transaction active in this session has been committed or aborted by another session.  
  prisma:engine stdout  The server failed to resume the transaction. Desc:4200000002.  
  prisma:engine stdout  Unknown error  
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: 'The server failed to resume the transaction. Desc:4200000002.' on server 99eb2c6695a5 executing  on line 1 (code: 3971, state: 1, class: 16)
  prisma:engine       at BinaryEngine.graphQLToJSError (/work/git/idt/node_modules/@prisma/client/runtime/index.js:28062:14)
  prisma:engine       at BinaryEngine.request (/work/git/idt/node_modules/@prisma/client/runtime/index.js:27958:24)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:93:5)
  prisma:engine       at cb (/work/git/idt/node_modules/@prisma/client/runtime/index.js:33866:26)
  prisma:engine       at Context.<anonymous> (/work/git/idt/src/metadata-management/time-series-site.spec.ts:107:9) {
  prisma:engine     clientVersion: '2.26.0'
  prisma:engine   }
  prisma:engine }  
  prisma:engine stdout  Fetched a connection from the pool

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by janconc** [comment]
Hi, I am sorry for late reply. Unfortunately I am not able to assist with this issue any more. Let's close it.
