### ISSUE TITLE
Validate `referentialActions` with Introspection and Migration CI

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8176]
Use internal tools Introspection and Migration CI to validate functionality of `referentialActions` preview feature.

**Comment by janpio** [comment]
First approach: https://github.com/prisma/introspection-ci/pull/386 
(Has to be manually updated to be kept up to date with Prisma releases)

**Comment by Jolg42** [comment]
@janpio since 2.28 is released we could update it, what are the update steps?

**Comment by janpio** [comment]
Update the dependency in the branch - there is just no automated script that takes care of this in the `feat/` branches as there is for the `automated/*` ones.

**Comment by Jolg42** [comment]
Updating introspection-ci to `2.29.0-dev.17` and one change appeared see https://prisma-company.slack.com/archives/C01778YKS00/p1627988088000800

**Comment by Jolg42** [comment]
Migrations-CI attempt in `referentialActions` branch with commit https://github.com/prisma/migrations-ci/commit/7f700c7b24f8e7e16538c5b7d1b17d844c0e11ff

Needs a workflow dispatch from https://github.com/prisma/migrations-ci/actions/workflows/analyse.yml

Running in https://github.com/prisma/migrations-ci/actions/runs/1094195521

**Comment by Jolg42** [comment]
Result from updating introspection-ci to `2.29.0-dev.17` see https://github.com/prisma/introspection-ci/commit/6ea059e351f0fd9b660e09dd12633cf344c253ee

**Comment by Jolg42** [comment]
Result from updating introspection-ci to `2.30.0-dev.35` see https://github.com/prisma/introspection-ci/commit/71f4b13d78794418a8d6258b3c79857b6a821a52

Analysis in Slack thread
https://prisma-company.slack.com/archives/C01778YKS00/p1629708269000900

**Comment by Jolg42** [comment]
Result from updating migrations-ci to 2.30.0-dev.35 see https://github.com/prisma/migrations-ci/commit/d1bfadd2fd4d037dd245c056a46166972f6f831b

Analysis in Slack thread
https://prisma-company.slack.com/archives/C01G8CK1D9N/p1629711592000100

**Comment by tomhoule** [comment]
Introspection and migrations CI look good :+1:
