### ISSUE TITLE
PANIC in query-engine\core\src\response_ir\internal.rs:334:86called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by fnaysee** [prisma/prisma#8202]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.3           | 
| OS              | windows            |
| Prisma Client   | 2.25.0             |
| Query Engine    | query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922|
| Database        | undefined|

## Query
```
query {
  aggregateTransactions(where: {
    OwnerId: "X"
  }) {
    _count {
      _all
    }
  }
}
```

## Logs
```
7m
  prisma:engine stdout  PANIC in query-engine\core\src\response_ir\internal.rs:334:86
called `Option::unwrap()` on a `None` value  +21s
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:53339
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 53339
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: 'D:\\pobel-backend-node\\src\\prisma' }  
  prisma:engine Search for Query Engine in D:\pobel-backend-node\node_modules\.prisma\client  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:53339
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 53339
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:53339
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 53339
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:53339
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 53339
  prisma:engine   }
  prisma:engine }  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '53403' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:53403  
  prisma:engine Search for Query Engine in D:\pobel-backend-node\node_modules\.prisma\client  
  prisma:engine Client Version: 2.25.0  
  prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in query-engine\core\src\response_ir\internal.rs:334:86
called `Option::unwrap()` on a `None` value  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```js
let items = await prisma.transactions.findMany({
            select: {
                ReferenceDataset: { Id: true, Name: true, Type: true},
            },
            where,
            orderBy: {
                CreatedAt: 'desc',
            },
            take: parseInt(Limit),
            skip: Skip
        })
```

## Schema
```prisma
model Transactions {
  Id                 String    @id @default(uuid())
  CreatedAt          DateTime  @default(now())
  UpdatedAt          DateTime? @updatedAt
  OwnerId            String
  Owner              User      @relation(fields: [OwnerId], references: [Id])
  DebitAmount        Float     @db.DoublePrecision
  CreditAmount       Float     @db.DoublePrecision
  Reason             Int
  ReasonDescription  String?
  ReferenceDatasetId String?
  ReferenceDataset   Datasets? @relation(fields: [ReferenceDatasetId], references: [Id])
}
```

If I replace the  `ReferenceDataset: { Id: true, Name: true, Type: true},` with ReferenceDataset: true, It doesn't crash

**Comment by pantharshit00** [comment]
Can you please also share the `Datasets` model?

**Comment by wp-src** [comment]
```prisma
model Datasets {
  Id                       String                @id @default(uuid())
  CreatedAt                DateTime              @default(now())
  UpdatedAt                DateTime?             @updatedAt
  Name                     String?
  Description              String?
  Type                     Int
  LabelingStatus           Int
  AnswerType               Int                   @default(0)
  IsActive                 Boolean               @default(false)
  Transactions             Transactions[]
}
```
Note: I have removed unnecessary fields.

**Comment by pantharshit00** [comment]
I am unable to reproduce this with 2.26 and a postgresql database. 

The query you are doing is wrong, you need the add a select key in order to select keys from the nested relation:
```ts
  let items = await prisma.transactions.findMany({
    select: {
      ReferenceDataset: {
        select: {  // <----- this select is missing from the reported query
          Id: true,
          Name: true,
          Type: true,
        },
      },
    },
    where: {
      Id: "test",
    },
    orderBy: {
      CreatedAt: "desc",
    },
    take: parseInt("1"),
    skip: 10,
  });
```

Even if I omit the select, I get a runtime error telling me that I am missing the select:
```
yarn run v1.22.5
$ ts-node main.ts
(node:27324) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.transactions.findMany()` invocation:

{
  select: {
    ReferenceDataset: {
      Id: true,
      ~~
      Name: true,
      ~~~~
      Type: true
      ~~~~
    }
  },
  where: {
    Id: 'test'
  },
  orderBy: {
    CreatedAt: 'desc'
  },
  take: 1,
  skip: 10
}

Unknown arg `Id` in select.ReferenceDataset.Id for type Datasets.
→ Did you forget to wrap it with `select`? e.g. { select: { Id: true } }
Unknown arg `Name` in select.ReferenceDataset.Name for type Datasets.
→ Did you forget to wrap it with `select`? e.g. { select: { Name: true } }
Unknown arg `Type` in select.ReferenceDataset.Type for type Datasets.
→ Did you forget to wrap it with `select`? e.g. { select: { Type: true } }


    at Document.validate (C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:33530:19)
    at NewPrismaClient._executeRequest (C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:35637:17)
    at consumer (C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:35582:23)
    at C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:35584:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:35584:25)
    at Object.then (C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:35692:39)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodej
s.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)(node:27324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.60s.
```

I believe you are reporting the wrong snippet which triggered the crash. Do you have any `aggregate` queries with `_count` which might be running? The error report points to that.

**Comment by wp-src** [comment]
> 
> 
> I am unable to reproduce this with 2.26 and a postgresql database.
> 
> The query you are doing is wrong, you need the add a select key in order to select keys from the nested relation:
> 
> ```ts
>   let items = await prisma.transactions.findMany({
>     select: {
>       ReferenceDataset: {
>         select: {  // <----- this select is missing from the reported query
>           Id: true,
>           Name: true,
>           Type: true,
>         },
>       },
>     },
>     where: {
>       Id: "test",
>     },
>     orderBy: {
>       CreatedAt: "desc",
>     },
>     take: parseInt("1"),
>     skip: 10,
>   });
> ```
> 
> Even if I omit the select, I get a runtime error telling me that I am missing the select:
> 
> ```
> yarn run v1.22.5
> $ ts-node main.ts
> (node:27324) UnhandledPromiseRejectionWarning: Error:
> Invalid `prisma.transactions.findMany()` invocation:
> 
> {
>   select: {
>     ReferenceDataset: {
>       Id: true,
>       ~~
>       Name: true,
>       ~~~~
>       Type: true
>       ~~~~
>     }
>   },
>   where: {
>     Id: 'test'
>   },
>   orderBy: {
>     CreatedAt: 'desc'
>   },
>   take: 1,
>   skip: 10
> }
> 
> Unknown arg `Id` in select.ReferenceDataset.Id for type Datasets.
> → Did you forget to wrap it with `select`? e.g. { select: { Id: true } }
> Unknown arg `Name` in select.ReferenceDataset.Name for type Datasets.
> → Did you forget to wrap it with `select`? e.g. { select: { Name: true } }
> Unknown arg `Type` in select.ReferenceDataset.Type for type Datasets.
> → Did you forget to wrap it with `select`? e.g. { select: { Type: true } }
> 
> 
>     at Document.validate (C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:33530:19)
>     at NewPrismaClient._executeRequest (C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:35637:17)
>     at consumer (C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:35582:23)
>     at C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:35584:47
>     at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
>     at NewPrismaClient._request (C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:35584:25)
>     at Object.then (C:\Users\harshit\code\reproductions\issue_8202\node_modules\@prisma\client\runtime\index.js:35692:39)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:27324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
> ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To termin
> ate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodej
> s.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)(node:27324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> Done in 1.60s.
> ```
> 
> I believe you are reporting the wrong snippet which triggered the crash. Do you have any `aggregate` queries with `_count` which might be running? The error report points to that.

1. Yes you are right. The snippet that I posted here is wrong but my real snippet produces same thing as your code. So I'm sure it is correct.
2. Yes I have _count in another api. This is my scenario: Each dataset has many datasetItems. And client can request to get datasets with count of their items.
But I'm sure that one is not being called in this api call.

The last thing that I can add to this is that in my scenario when I login the user and then try to fetch transactions prisma crashes. But when user is logged in and I restart the server prisma doesn't crash and fetches the results correctly as expected.

I hope my explanation help you find the bug!

**Comment by andresribeiro** [comment]
I have the same error

**Comment by pantharshit00** [comment]
@wp-src The crash you have shared specially mentions the use the `_count` api so it can't be the call that you are sharing which is triggering the panic. We need the call which triggers the panic in order to pin point the bug. 

@andresribeiro Can you please share a minimal reproduction?

**Comment by andresribeiro** [comment]
@pantharshit00 sure. Should I post here or open another issue?

**Comment by pantharshit00** [comment]
Here will be fine.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
