### ISSUE TITLE
Field applied_steps_count in table _prisma_migrations equals Null insted of 1

### ISSUE THREAD

**Issue by Nikitoring** [prisma/prisma#8204]
Hi. When I create migration npx prisma migrate dev --name name-migration like in  docs https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate#create-migrations
field applied_steps_count in table _prisma_migrations equals Null insted of 1. How can I fix it?

**Comment by janpio** [comment]
Can you please show the full error message you are getting?

**Comment by tomhoule** [comment]
Hi @MurzNN, thanks for reporting! Could it be the same problem as https://github.com/prisma/prisma/issues/8234?
