### ISSUE TITLE
'Plans for MSSQL supported db'

### ISSUE THREAD

**Issue by lisaconnect1234** [prisma/prisma#8252]
## Problem

I see MSSQL is in preview feature state, what are your plans for full support of MSSQL?

**Comment by tomhoule** [comment]
This is still being actively worked on, and getting closer to release. We don't have a fixed date for the stable release yet, however.

**Comment by lisaconnect1234** [comment]
> This is still being actively worked on, and getting closer to release. We don't have a fixed date for the stable release yet, however.

This is on the roadmap and the plan is to support MSSQL, correct?  Can you check on potential release dates?
