### ISSUE TITLE
"Mongo is not yet supported" in databaseTypeToConnectorType()

### ISSUE THREAD

**Issue by timleslie** [prisma/prisma#8261]
### Bug description

When calling `createDatabase` from `@prisma/sdk` we get the error `Mongo is not yet supported`, which comes from https://github.com/prisma/prisma/blob/d36742652efa8fffb7fe6e75281654893f0e049d/src/packages/sdk/src/convertCredentials.ts#L198

This is preventing us from using the migrations SDK in [Keystone](https://github.com/keystonejs/keystone/pull/6102).

### How to reproduce

The failure can be seen happening here: https://github.com/keystonejs/keystone/runs/3062577041?check_suite_focus=true

### Expected behavior

The `@prisma/sdk` package should support MongoDB.

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
2.27.0
```

**Comment by felixbuchholz** [comment]
Just wanted to leave a note of support. Would be spectacular if Keystone could use the MongoDB connector! :) 
Also do not completely understand why an error would be thrown, when the connector is already in preview mode.

**Comment by Jolg42** [comment]
You can try our dev version (not recommended for production) `2.29.0-dev.25` @timleslie @felixbuchholz 😉 

It will part of the `2.29.0` planned for Tuesday.
