### ISSUE TITLE
Make the MongoDB Replica Set Requirement Optional in Development

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#8266]
## Problem

MongoDB only allows you to start a transaction on a replica set. Prisma uses transactions internally to avoid partial writes on nested queries. 

This means we inherit the requirement of needing a replica set configured. This makes our getting started experience more cumbersome.

## Suggested solution

We should find a way to make this requirement optional, at least during development. In production, most people will host their MongoDB instance with the replica set configured.

## Alternatives

Right now we recommend that you use [MongoDB Atlas](https://www.mongodb.com/cloud/atlas) to launch a free instance that has replica set support out of the box.

There's also an option to run the replica set locally with this guide: https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/

**Comment by 2color** [comment]
The challenge I see with this is that local development environments won't replicate the transactional behaviour as in production. So while this may improve DX, it might lead to false assumptions that only become visible in production.

**Comment by ppbl** [comment]
@matthewmueller  I would like to ask, is the single node replica set Limited？
（I'm not very familiar with mongodb）

**Comment by tvarwig** [comment]
I cannot use an offline local development with mongodb and prisma. I have poor internet where I live. I can't use atlas and be productive.

**Comment by matthewmueller** [comment]
A couple ideas:


### 1. Try to connect to the `replicaSet` first

We could always try connecting to the `replicaSet`, then failover to the non-replicaSet. For cases where it fails over, we should probably print a warning that transactions are not supported in this mode and we only recommend this mode for development.

#### Cons
- Logging warning at runtime is always a bit annoying
- Code with $transaction would succeed or fail at runtime depending on the environment

### 2. Use a query parameter in the connection string to adjust how we connect*
 
This would be similar to how when you run Postgres locally you have:

```
postgres://localhost:5432/mydb?sslmode=disable
```

While in production:

```
postgres://app.123124123.us-west-2.rds.amazonaws.com/mydb?sslmode=require
```

For MongoDB, we could have a `replicaSet` query parameter to tweak behavior

```
mongodb://localhost:5432/mydb?replicaSet={disable,prefer,require}
```

- **disable:** don't try connecting to the replica set
- **prefer:** try connecting to the replica set, fallback to default
- **require:** try connecting to the replica set, fail if unable to.

#### Cons
- New non-standard query parameter
- Code with $transaction would succeed or fail at runtime depending on the environment

**Comment by matthewmueller** [comment]
Next steps:
- We like **1. Always try to connect to the replicaSet first**
- Dom will bring this up in PSL working group to decide on API.

**Comment by matthewmueller** [comment]
Just re-purposed this issue for the actual work.

**Comment by mgcrea** [comment]
Starting a local single-instance replicaSet is pretty easy and I really don't think you should waste some time or add code complexity to handle a non-replicaSet environment for development purposes.

For instance this `docker-compose.yml` does the job for me:

```yml
version: '3'

services:
  mongo:
    container_name: joonca_mongo
    hostname: joonca-mongo
    image: mongo:4
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./data/mongo:/data/db
```

You just have to run the following command once:

```sh
docker-compose exec mongo mongo --eval "rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongo:27017'}]});"
```

And that's it.

Selfishly, I'd rather want jsonSchema support for actual production workloads! (see https://github.com/prisma/prisma/issues/8135)!

**Comment by pantharshit00** [comment]
We also provide a docker image now to even further simplify this: https://hub.docker.com/r/prismagraphql/mongo-single-replica

**Comment by matthewmueller** [comment]
Thanks for letting us know @mgcrea! We're going to give this a shot as a potential solution.

**Comment by matthewmueller** [comment]
So we tested this and it does indeed work! I still think it makes sense to improve since it reduces the barrier of giving MongoDB a shot for people that just want to try it out.

We also ran a poll internally and about 56% of respondents use docker-compose regularly. The rest: sometimes, occassionally and never.

We'll definitely get to JSON Schema support in good time though!

**Comment by dannysmc95** [comment]
> Starting a local single-instance replicaSet is pretty easy and I really don't think you should waste some time or add code complexity to handle a non-replicaSet environment for development purposes.
> 
> For instance this `docker-compose.yml` does the job for me:
> 
> ```yaml
> version: '3'
> 
> services:
>   mongo:
>     container_name: mongo
>     image: mongo:4
>     command: --replSet rs0
>     ports:
>       - '27017:27017'
>       - '28017:28017'
>     volumes:
>       - ./data/mongo:/data/db
> ```
> 
> You just have to run the following command once:
> 
> ```shell
> docker-compose exec mongo mongo --eval "rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongo:27017'}]});"
> ```
> 
> And that's it.
> 
> Selfishly, I'd rather want jsonSchema support for actual production workloads! (see #8135)!

What connection URL do you use to connect to this? Sorry I just stumbled across this, and I tried to connect but it keep saying the following:

```
PrismaClientInitializationError: Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: mongo:27017, Type: Unknown, Error: failed to lookup address information: Name or service not known }, ] }
```

I have tried this: https://hub.docker.com/r/prismagraphql/mongo-single-replica but it always throws an error, saying it couldn't connect, so at this point, I am stuck because either I use Atlas (which I don't want to do for development) or switch away from Prisma entirely, so any help is appreciated.

**Comment by mgcrea** [comment]
@dannysmc95 I'm using `DATABASE_URL="mongodb://localhost:27017/sandbox"` (I think you have to drop the `+src` iirc. Also I do have `127.0.0.1	localhost redis mongo` in my `/etc/hosts` but I don't think it changes anything (but in case it still does not work you could try that).

**Comment by dannysmc95** [comment]
@mgcrea so that addition in the `/etc/hosts` fixed the issue, before the connection would hang, but now it works! So thank you!! I will not go insane!

**Comment by mgcrea** [comment]
@dannysmc95 indeed its the `rs.initiate` command that should use `localhost` instead of `mongo` (somehow thought it would resolve the local service inside the docker network but it does not seem to work that way).

So:

```sh
docker-compose exec mongo mongo --eval "rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]});"
```

**Comment by dannysmc95** [comment]
> @dannysmc95 indeed its the `rs.initiate` command that should use `localhost` instead of `mongo` (somehow thought it would resolve the local service inside the docker network but it does not seem to work that way).
> 
> So to have it work without `/etc/hosts` tweaks:
> 
> ```shell
> docker-compose exec mongo mongo --eval "rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]});"
> ```

Ahh okay, that makes a lot more sense, I was so confused, again thank you for your help!

**Comment by AlvaroBrasilia** [comment]
I fixed this issue inserting this in mongodb.config file:

````
replication:
  replSetName: rs0
```` 

aws ubuntu > /etc/mongodb.confic
MacOs > /usr/local/etc/mongod.conf 

Restart the mongodb service  :)

**Comment by matthewmueller** [comment]
Thanks @AlvaroBrasilia! I think our solution is going to be to document this. The alternatives seem like we're asking for people to go into production with a disabled replicaset.

**Comment by matthewmueller** [comment]
Closing in favor of: https://github.com/prisma/docs/issues/2795

**Comment by blazestudios23** [comment]
The above isn't working for me. I get the
```
Prisma needs to perform transactions, which requires your MongoDB server to be run as a replica set.
```


Honestly would be really nice if there was a local mode, as dealing with this issues is a large waste of time. No mutations work in my API.

**Comment by Jolg42** [comment]
The replica setup can be indeed tricky. 

Are you trying to setup the replica set on macOS?
Did you check the logs? it can sometimes be helpful.

See https://github.com/prisma/docs/issues/2795 for a docker-compose way of doing it.
Would using docker-compose work for you?

**Comment by blazestudios23** [comment]
@Jolg42 I got working using the the recommendations in the issues you link.

**Comment by masterbater** [comment]
For anyone wanting to spin up a single node replica set for development use this 
Using a verified docker image from bitnami

docker-compose.yml
```
version: '3.8'
services:
  
  database:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=anyuser
      - MONGODB_ROOT_PASSWORD=anypassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-db:/bitnami/mongodb'

volumes:
  mongo-db:

```

**Comment by q-rault** [comment]
Just wanted to try out Prisma with MongoDB and ran into this issue.
This thread was really useful. What did it for me was @mgcrea 's insight on `rs.initiate()` options, thank you !

Here is my issue walkthrough regarding this (basically [mongodb](https://www.mongodb.com/docs/manual/tutorial/convert-standalone-to-replica-set/)'s tutorial with examples) :

1. Make sure you shut down mongod's instance beforehand with `brew services stop mongodb-community@5.0`(on MacOS+Homebrew). 
2. Start mongod (configured for replication) with the command below :

```
mongod --port 27017 --dbpath /path/to/mongodb --replSet rs0 --bind_ip localhost,CustomHostName

#on MacOS (Homebrew)
mongod --port 27017 --dbpath /opt/homebrew/var/mongodb/ --replSet rs0 --bind_ip localhost,HomeHost
```

3. While mongod is running, open a new terminal & run `mongosh`, then :

```
rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]});
``` 

I hope this helps someone !

**Comment by dsvgit** [comment]
@q-rault thanks it was helpful, I did almost the same, but changed second step with the following actions
- update mongo config `/usr/local/etc/mongod.conf` file with `replication` props:
```
systemLog:
  destination: file
  path: /usr/local/var/log/mongodb/mongo.log
  logAppend: true
storage:
  dbPath: /usr/local/var/mongodb
net:
  bindIp: 127.0.0.1
replication:
  replSetName: "rs0"
```
- and start mongo service again `brew services start mongodb-community@5.0`

**Comment by sergiobarria** [comment]
thanks @q-rault @dsvgit - I was able to make it work with your solution!!

**Comment by jrCleber** [comment]
> For anyone wanting to spin up a single node replica set for development use this Using a verified docker image from bitnami
> 
> docker-compose.yml
> 
> ```
> version: '3.8'
> services:
>   
>   database:
>     image: 'bitnami/mongodb:latest'
>     environment:
>       - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
>       - MONGODB_REPLICA_SET_MODE=primary
>       - MONGODB_ROOT_USER=anyuser
>       - MONGODB_ROOT_PASSWORD=anypassword
>       - MONGODB_REPLICA_SET_KEY=replicasetkey123
>     ports:
>       - '27017:27017'
>     volumes:
>       - 'mongo-db:/bitnami/mongodb'
> 
> volumes:
>   mongo-db:
> ```
> 
> You can also use docker mongo but I had a hard time setting it up, they dont support the configuration out of the box so you need to make your own entrypoint scripts

It didn't work for me! I can connect through mongoose but not prism!
The error below occurs.

Error: Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: 127.0.0.1:27017, Type: Unknown, Error: No connections could be made because the target machine actively refused them. (the errors 10061) }, ] }

**Comment by jrCleber** [comment]
> > For anyone wanting to spin up a single node replica set for development use this Using a verified docker image from bitnami
> > docker-compose.yml
> > ```yml
> > version: '3.8'
> > services:
> >   
> >   database:
> >     image: 'bitnami/mongodb:latest'
> >     environment:
> >       - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
> >       - MONGODB_REPLICA_SET_MODE=primary
> >       - MONGODB_ROOT_USER=anyuser
> >       - MONGODB_ROOT_PASSWORD=anypassword
> >       - MONGODB_REPLICA_SET_KEY=replicasetkey123
> >     ports:
> >       - '27017:27017'
> >     volumes:
> >       - 'mongo-db:/bitnami/mongodb'
> > 
> > volumes:
> >   mongo-db:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can also use docker mongo but I had a hard time setting it up, they dont support the configuration out of the box so you need to make your own entrypoint scripts
> 
> It didn't work for me! I can connect through mongoose but not prism! The error below occurs.
> 
> Error: Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: 127.0.0.1:27017, Type: Unknown, Error: No connections could be made because the target machine actively refused them. (the errors 10061) }, ] }

<hr>

# SORTED OUT!

It managed to connect me with the following string:

```mongodb
mongodb://<USER>:<PASSWORD>@<HOST>:<PORT>/<DATABASE>?authSource=admin&directConnection=true
```

**Comment by awilderink** [comment]
> > > For anyone wanting to spin up a single node replica set for development use this Using a verified docker image from bitnami
> > > docker-compose.yml
> > > ```yaml
> > > version: '3.8'
> > > services:
> > >   
> > >   database:
> > >     image: 'bitnami/mongodb:latest'
> > >     environment:
> > >       - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
> > >       - MONGODB_REPLICA_SET_MODE=primary
> > >       - MONGODB_ROOT_USER=anyuser
> > >       - MONGODB_ROOT_PASSWORD=anypassword
> > >       - MONGODB_REPLICA_SET_KEY=replicasetkey123
> > >     ports:
> > >       - '27017:27017'
> > >     volumes:
> > >       - 'mongo-db:/bitnami/mongodb'
> > > 
> > > volumes:
> > >   mongo-db:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can also use docker mongo but I had a hard time setting it up, they dont support the configuration out of the box so you need to make your own entrypoint scripts
> > 
> > 
> > It didn't work for me! I can connect through mongoose but not prism! The error below occurs.
> > Error: Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: 127.0.0.1:27017, Type: Unknown, Error: No connections could be made because the target machine actively refused them. (the errors 10061) }, ] }
> 
> # SORTED OUT!
> It managed to connect me with the following string:
> 
> ```
> mongodb://<USER>:<PASSWORD>@<HOST>:<PORT>/<DATABASE>?authSource=admin&directConnection=true
> ```

For people using Apple Silicon, the latest version of `bitnami/mongodb` (>5) does not run. Use `bitnami/mongodb:4.4` instead

**Comment by bgavas** [comment]
For Apple M1 users, homebrew config file is at `/opt/homebrew/etc/mongod.conf`

**Comment by bgavas** [comment]
> @q-rault thanks it was helpful, I did same things, but changed second step with the following actions
> 
> * update mongo config `/usr/local/etc/mongod.conf` file with `replication` props:
> 
> ```
> systemLog:
>   destination: file
>   path: /usr/local/var/log/mongodb/mongo.log
>   logAppend: true
> storage:
>   dbPath: /usr/local/var/mongodb
> net:
>   bindIp: 127.0.0.1
> replication:
>   replSetName: "rs0"
> ```
> 
> * and start mongo service again `brew services start mongodb-community@5.0`

For Apple Silicon users (M1, M2, etc.), brew config file is at `/opt/homebrew/etc/mongod.conf`

**Comment by akinncar** [comment]
> Closing in favor of: https://github.com/prisma/docs/issues/2795

@matthewmueller you said that it was closed in favor of another issue, but another issue it was not even discussed the point of this issue
is there a way to disable transactions in prima? why not? is it possible to have this implementation?

**Comment by Jolg42** [comment]
Hi @akinncar 
Could you tell us what is the pain point for you?
Is it only a problem during development, or also for production?

There is no currently no way to disable transactions in Prisma on MongoDB, at the moment all writes use a transaction.
It's possible that this changes in the future, probably best to follow this issue https://github.com/prisma/prisma/issues/12814 for now.

**Comment by thanductrung** [comment]
> @q-rault thanks it was helpful, I did same things, but changed second step with the following actions
> 
> * update mongo config `/usr/local/etc/mongod.conf` file with `replication` props:
> 
> ```
> systemLog:
>   destination: file
>   path: /usr/local/var/log/mongodb/mongo.log
>   logAppend: true
> storage:
>   dbPath: /usr/local/var/mongodb
> net:
>   bindIp: 127.0.0.1
> replication:
>   replSetName: "rs0"
> ```
> 
> * and start mongo service again `brew services start mongodb-community@5.0`

Thanks for this awesome tip, @dsvgit! 
I got it working but still unable to do anything when accessing the database by running this command in a terminal `mongo "mongodb://localhost:27017/test"`
It keeps showing the below error with whatever command I ran (`show collections` for example)
```
        "errmsg" : "not master and slaveOk=false",
        "code" : 13435,
        "codeName" : "NotPrimaryNoSecondaryOk",
```

**Comment by jcampbell05** [comment]
I'm currently having a pain point where reads are taking a long time and then failing to find a document as if MongoDB isn't ready to make it available until propagated  and it's failing to replicate the written content despite directConnection being set to true.

**Comment by brunoandradebr** [comment]
For those trying prisma + mongo with docker

1 - start a mongo container
``
docker run --name mongodb -d -p 27017:27017 mongo mongod --replSet rs0
``

2 - After your mongodb container is up and running, enter mongosh
``
docker exec -it mongodb mongosh
``

3 - Inside mongosh, initiate replica set
``
rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]})
``

And you're good to go. Just stop and run your node app again 👍

**Comment by vaclav-stummer** [comment]
> For those trying node + prisma + mongo with docker on localhost
> 
> 1 - start a mongo container `docker run --name mongodb -d -p 27017:27017 mongo mongod --replSet rs0`
> 
> 2 - After your mongodb container is up and running, enter mongosh `docker exec -it mongodb mongosh`
> 
> 3 - Inside mongosh, initiate replica set `rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]})`
> 
> And you're good to go. Just stop and run your node app again 👍

I am getting:
```
~/p/p/pnyx-monorepo ❯❯❯ npx ts-node index.ts

   7 // Connect the client
   8 await prisma.$connect()
   9 // ... you will write your Prisma Client queries here
→ 10 const allUsers = await prisma.user.findMany(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: AuthenticationFailed { user: "SCRAM failure: Authentication failed." }, transient: false })
    at Zr.handleRequestError (/Users/vaclavstummer/projects/pnyx/pnyx-monorepo/node_modules/@prisma/client/runtime/library.js:171:6587)
    at Zr.handleAndLogRequestError (/Users/vaclavstummer/projects/pnyx/pnyx-monorepo/node_modules/@prisma/client/runtime/library.js:171:5948)
    at Zr.request (/Users/vaclavstummer/projects/pnyx/pnyx-monorepo/node_modules/@prisma/client/runtime/library.js:171:5786)
    at async t._request (/Users/vaclavstummer/projects/pnyx/pnyx-monorepo/node_modules/@prisma/client/runtime/library.js:174:10455) {
  clientVersion: '4.11.0'
}
```

What can be the issue?

**Comment by vaclav-stummer** [comment]
> Try to set authSource=admin flag
> 
> `DATABASE_URL=mongodb://username:password@localhost:27017/db_name?authSource=admin`

Yea I have it as so: DATABASE_URL=mongodb://admin:admin@localhost:27017/main?authSource=admin

And is there an easy way how to put it together with docker-compose so it can be run as one command?

docker-compose.yml
```yml
version: '3.1'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
    command: mongod --replSet rs0

```

I really love prisma 2. I worked extensively with Prisma 1. But it seems that prisma2 is lacking on local configuration on both PostgreSQL and Mongo. My current project needs to be as Mongo. So I am trying to find simple out of the box and replicable solution on different machines for local development without any extra fiddling with bash

**Comment by brunoandradebr** [comment]
I'm experimenting prisma and learning docker yet. I'm just running with docker terminal commands, I'm moving to docker compose soon. Previous answers did not help ? Try @mgcrea answer https://github.com/prisma/prisma/issues/8266#issuecomment-966618742, he is running with docker-compose. I think you r not initiating replicas.

**Comment by suerta-git** [comment]
Can use this script to start mongo by one command:

```bash
#! /bin/bash

if [ "$(docker ps -a -q -f name=mongodb)" ]; then
    docker start mongodb
else
    docker run --name mongodb -d -p 27017:27017 mongo:latest mongod --replSet rs
    docker exec -d mongodb mongosh --eval "rs.initiate({_id: 'rs', members: [{_id: 0, host: 'localhost:27017'}]})"
fi

docker attach mongodb
```

**Comment by Hellomik2002** [comment]
what about  security.keyFile ?

**Comment by jedwards1211** [comment]
`?authSource=admin&directConnection=true` isn't working for me so far...I still get SCRAM auth failed when trying to do anything that uses NextAuth...

Prisma should really just provide a working example repo using docker-compose for running MongoDB locally.  Recommending signing up for a freemium cloud service isn't great...

**Comment by vaclav-stummer** [comment]
> `?authSource=admin&directConnection=true` isn't working for me so far...I still get SCRAM auth failed when trying to do anything that uses NextAuth...
> 
> Prisma should really just provide a working example repo using docker-compose for running MongoDB locally. Recommending signing up for a freemium cloud service isn't great...

+1 on this one. The tutorial should ideally not depend on 3rd party services and agnostic. So it seems that docker-compose is the best way to do it

**Comment by go-maple** [comment]
I saw a lot of issues about docker-compose file, I found nothing about  which is useful docker-compose about mongo.

**Comment by Jolg42** [comment]
Could you try the following example? https://github.com/prisma/docs/issues/3040

This should work well for development with MongoDB v4 or v5 but won't work with v6.

**Comment by kmrk** [comment]
> Just wanted to try out Prisma with MongoDB and ran into this issue. This thread was really useful. What did it for me was @mgcrea 's insight on `rs.initiate()` options, thank you !
> 
> Here is my issue walkthrough regarding this (basically [mongodb](https://www.mongodb.com/docs/manual/tutorial/convert-standalone-to-replica-set/)'s tutorial with examples) :
> 
> 1. Make sure you shut down mongod's instance beforehand with `brew services stop mongodb-community@5.0`(on MacOS+Homebrew).
> 2. Start mongod (configured for replication) with the command below :
> 
> ```
> mongod --port 27017 --dbpath /path/to/mongodb --replSet rs0 --bind_ip localhost,CustomHostName
> 
> #on MacOS (Homebrew)
> mongod --port 27017 --dbpath /opt/homebrew/var/mongodb/ --replSet rs0 --bind_ip localhost,HomeHost
> ```
> 
> 3. While mongod is running, open a new terminal & run `mongosh`, then :
> 
> ```
> rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]});
> ```
> 
> I hope this helps someone !

That’s what I need.  Thank you !

**Comment by samrocksc** [comment]
i'm not gonna force junior devs to go through this to setup a local environment.

**Comment by vaclav-stummer** [comment]
But then you force more senior devs to spend hours and hours or days, just find out how to make it run on local env. It would be great to do maybe some article about it. For example, this approach made me change my mind about Prisma. I wanted to use it for my project with Mongo. But I decided to use [mongoose](https://mongoosejs.com/) and [nextJS](https://nexusjs.org/) because of this. Yes, it is a bit more code, but now I think it is even better than Prisma because it is way much easier to set up and you don't have so much tied hands like with Prisma. 

For me, it is Prisma for:
- PostgreSQL: yes
- Mongo: not worth the hustle around it

**Comment by hryashik** [comment]
> For those trying node + prisma + mongo with docker on localhost
> 
> 1 - start a mongo container `docker run --name mongodb -d -p 27017:27017 mongo mongod --replSet rs0`
> 
> 2 - After your mongodb container is up and running, enter mongosh `docker exec -it mongodb mongosh`
> 
> 3 - Inside mongosh, initiate replica set `rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]})`
> 
> And you're good to go. Just stop and run your node app again +1

It's working, but if you wanna to use the compose, you cant write flag "--replSet rs0" for container. So that have to use image prismagraphql/mongo-single-replica. That's modified version of the official Mongo image and he takes exactly the same  env variables, so that's comfortable

**Comment by hryashik** [comment]
> For those trying node + prisma + mongo with docker on localhost
> 
> 1 - start a mongo container `docker run --name mongodb -d -p 27017:27017 mongo mongod --replSet rs0`
> 
> 2 - After your mongodb container is up and running, enter mongosh `docker exec -it mongodb mongosh`
> 
> 3 - Inside mongosh, initiate replica set `rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]})`
> 
> And you're good to go. Just stop and run your node app again +1

It's working, but i prefer to use the image[ prismagraphql/mongo-single-replica](https://hub.docker.com/r/prismagraphql/mongo-single-replica). That's modified version of the official Mongo image and he takes exactly the same env variables. That image is already configured, so that's comfortable

**Comment by danhab99** [comment]
Hey all, just looking for an update because I've been going through this for weeks. I can't change how mongodb is deployed locally, I have to change prisma.

**Comment by Jolg42** [comment]
Note that this issue is old (2021) and closed since early 2022.

If you want to discuss this, please create a new discussion:
https://github.com/prisma/prisma/discussions

And if you have a feature request or a bug, create an issue here: https://github.com/prisma/prisma/issues/new/choose

I created a discussion here:
I'm curious to hear what you think about using a docker compose config approach I mentioned a long time ago.
I updated it recently and made it easy to switch the MongoDB version, see:
https://github.com/prisma/prisma/discussions/22442

**Comment by davidquintard** [comment]
I just wanted to migrate typorm to prisma. 
But i see that this replica set is impossible to disable.
Too bad
