### ISSUE TITLE
prisma extension request for sublime text 4

### ISSUE THREAD

**Issue by paras594** [prisma/prisma#8300]
## Problem

I didn't find sublime text 4 in prisma docs for editor setup. It would be nice if sublime text 4 also get an extension for prisma.

**Comment by pantharshit00** [comment]
We have syntax highlighting support for sublime text: https://github.com/prisma/sublimeText3

There is no LSP support currently though.

**Comment by Ultra-Instinct-05** [comment]
https://github.com/prisma/prisma/discussions/12316

**Comment by janpio** [comment]
I think we can clsoe this issue, the new packages are also documented here: https://www.prisma.io/docs/guides/development-environment/editor-setup#sublime-text
