### ISSUE TITLE
Node-API lost coloring/formatting of error messages

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8308]
https://github.com/prisma/prisma/pull/8286/checks?check_run_id=3080909038 vs https://github.com/prisma/prisma/pull/8286/checks?check_run_id=3080909177

![image](https://user-images.githubusercontent.com/183673/125866091-c74f3003-14f0-4e4d-80a2-0c079364c71d.png)
![image](https://user-images.githubusercontent.com/183673/125866096-f4a241a9-3540-4816-a376-b534e71e7ae6.png)

**Comment by williamluke4** [comment]
I have tried to reproduce this and could not.
