### ISSUE TITLE
prisma:getConfig fails with "Could not parse migration engine response: SyntaxError: Unexpected end of JSON input"

### ISSUE THREAD

**Issue by mericano1** [prisma/prisma#8310]
### Bug description

When trying to run `prisma migrate deploy` on a production server I get the following error.

```
2021-07-16T09:19:08.582Z prisma:getConfig Using Query Engine Binary at: /node_modules/.prisma/client/query-engine-linux-arm-openssl-1.1.x
Error: Error: Could not parse migration engine response: SyntaxError: Unexpected end of JSON input
    at parseJsonFromStderr (/node_modules/prisma/build/index.js:40881:15)
    at Object.canConnectToDatabase3 (/node_modules/prisma/build/index.js:40911:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.ensureDatabaseExists (/node_modules/prisma/build/index.js:61883:24)
    at async MigrateDeploy2.parse (/node_modules/prisma/build/index.js:64375:28)
    at async main (/node_modules/prisma/build/index.js:110386:18)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
command terminated with exit code 1
```

### How to reproduce

1. Build a docker image using node:16.4-buster-slim. 
2. Specify the env variables `PRISMA_QUERY_ENGINE_BINARY` , `PRISMA_MIGRATION_ENGINE_BINARY`, `PRISMA_INTROSPECTION_ENGINE_BINARY`, `PRISMA_FMT_BINARY`. This is because I ran into an issue with `linux-arm-openssl-undefined`. The application is running fine with those env variable now.
3. run `prisma migrate deploy`

### Expected behavior

The migration happens successfully 

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["filterJson"]
  binaryTargets   = ["native","linux-arm-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: Debian 
- Database: Postgresql
- Node.js version: v16.4.2

### Prisma Version

```
prisma               : 2.27.0
@prisma/client       : 2.27.0
Current platform     : linux-arm-openssl-undefined
Query Engine         : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/.prisma/client/query-engine-linux-arm-openssl-1.1.x, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/.prisma/client/query-engine-linux-arm-openssl-1.1.x, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/.prisma/client/query-engine-linux-arm-openssl-1.1.x, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary        : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/.prisma/client/query-engine-linux-arm-openssl-1.1.x, resolved by PRISMA_FMT_BINARY)
Default Engines Hash : cdba6ec525e0213cce26f8e4bb23cf556d1479bb
Studio               : 0.410.0
Preview Features     : filterJson

```

**Comment by tomhoule** [comment]
It looks like you are pointing to the query engine within the `PRISMA_MIGRATION_ENGINE_BINARY` env var. These are different binaries, so that explains the error. For reference, here is what `prisma version` returns for me:

```
erewhon.tom.~/tmp/migrate-qa λ prisma version                                                                   
Environment variables loaded from prisma/.env
prisma               : 2.27.0-dev.63
@prisma/client       : 2.20.0-dev.41
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.node_modules/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.node_modules/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.node_modules/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.node_modules/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : cdba6ec525e0213cce26f8e4bb23cf556d1479bb
Studio               : 0.410.0
```

**Comment by janpio** [comment]
> 2\. Specify the env variables `PRISMA_QUERY_ENGINE_BINARY` , `PRISMA_MIGRATION_ENGINE_BINARY`, `PRISMA_INTROSPECTION_ENGINE_BINARY`, `PRISMA_FMT_BINARY`. This is because I ran into an issue with `linux-arm-openssl-undefined`. The application is running fine with those env variable now.

Did you open an issue for this problem @mericano1?

**Comment by mericano1** [comment]
Hey, thanks for the quick answer. @janpio - No I didn't create an issue for that. I found one similar ticket but it didn't seem to have a solution other than "create a docker image with `buildx`" which is not my issue as I am using the same architecture to build and run the docker image. Also and the workaround _seemed_ to work. Should I create a new ticket ?

**Comment by mericano1** [comment]
> It looks like you are pointing to the query engine within the `PRISMA_MIGRATION_ENGINE_BINARY` env var. These are different binaries, so that explains the error. For reference, here is what `prisma version` returns for me:
> 
> ```
> erewhon.tom.~/tmp/migrate-qa λ prisma version                                                                   
> Environment variables loaded from prisma/.env
> prisma               : 2.27.0-dev.63
> @prisma/client       : 2.20.0-dev.41
> Current platform     : debian-openssl-1.1.x
> Query Engine         : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.node_modules/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
> Migration Engine     : migration-engine-cli cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.node_modules/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
> Introspection Engine : introspection-core cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.node_modules/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
> Format Binary        : prisma-fmt cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.node_modules/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
> Default Engines Hash : cdba6ec525e0213cce26f8e4bb23cf556d1479bb
> Studio               : 0.410.0
> ```

How do I get the other engines in there ?

```ls -la /node_modules/.prisma/client/'
total 43088
drwxr-xr-x 2 root root      149 Jul 16 08:59 .
drwxr-xr-x 3 root root       20 Jul 16 08:59 ..
-rw-r--r-- 1 root root     5327 Jul 16 08:59 index-browser.js
-rw-r--r-- 1 root root   334254 Jul 16 08:59 index.d.ts
-rw-r--r-- 1 root root   647243 Jul 16 08:59 index.js
-rw-r--r-- 1 root root      110 Jul 16 08:59 package.json
-rwxr-xr-x 1 root root 43116168 Jul 16 08:59 query-engine-linux-arm-openssl-1.1.x
-rw-rw-rw- 1 root root     3875 Jul 16 08:59 schema.prisma```

**Comment by mericano1** [comment]
nevermind. I found them under `@prisma/engines`. I will try to update the paths to use those.

```
ls -la /node_modules/@prisma/engines'
total 104544
drwxr-xr-x 4 root root      240 Jul 16 09:00 .
drwxr-xr-x 5 root root       58 Jul 16 08:59 ..
drwxr-xr-x 2 root root      123 Jul 16 08:59 dist
drwxr-xr-x 2 root root       42 Jul 16 08:59 download
-rwxr-xr-x 1 root root 21257704 Jul 16 08:59 introspection-engine-linux-arm-openssl-1.1.x
-rwxr-xr-x 1 root root 34354488 Jul 16 08:59 migration-engine-linux-arm-openssl-1.1.x
-rw-r--r-- 1 root root      651 Jul 16 08:59 package.json
-rwxr-xr-x 1 root root  8314016 Jul 16 08:59 prisma-fmt-linux-arm-openssl-1.1.x
-rwxr-xr-x 1 root root 43116168 Jul 16 08:59 query-engine-linux-arm-openssl-1.1.x
```

**Comment by janpio** [comment]
> I found one similar ticket but it didn't seem to have a solution other than "create a docker image with `buildx`" which is not my issue as I am using the same architecture to build and run the docker image. Also and the workaround _seemed_ to work. Should I create a new ticket ?

Please definitely add your voice to that issue, and make sure it is clear that you experiencing this as well. If you fix this, maybe also leave a comment here on how the workaround really is supposed to be used.

**Comment by mericano1** [comment]
BTW - Changing the variables to point to the right engines worked. Thanks for your support. 

@janpio I added a comment to the other issue that was closed ☝️
