### ISSUE TITLE
database seeding doesnt function

### ISSUE THREAD

**Issue by chachew** [prisma/prisma#8323]
Running Prisma 2.27.0 and while doing exactly what is shown in the [documentation](https://www.prisma.io/docs/guides/database/seed-database) using javascript seed.js file the database never gets seeded. The console states that the seed operation was successful, but nothing is ever seeded into the db.

```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Running seed from "prisma\seed.js" ...

Your database has been seeded.
```

**Comment by ryands17** [comment]
@chachew 👋 

I cannot reproduce this. Here's the seed running successfully and with data being added to the db:

![image](https://user-images.githubusercontent.com/19697099/126111291-17a82a6d-4669-4349-9011-93ab8a901537.png)

[test-seed.zip](https://github.com/prisma/prisma/files/6838364/test-seed.zip)

**Comment by tomhoule** [comment]
Note that db seed is currently [being completely redesigned](https://github.com/prisma/prisma/pull/8146) — there is an integration release you can try in the PR comments, feedback is more than welcome.

**Comment by chachew** [comment]
> @chachew 
> 
> I cannot reproduce this. Here's the seed running successfully and with data being added to the db:
> 
> ![image](https://user-images.githubusercontent.com/19697099/126111291-17a82a6d-4669-4349-9011-93ab8a901537.png)
> 
> [test-seed.zip](https://github.com/prisma/prisma/files/6838364/test-seed.zip)

Interesting, when i run your project on my machine, it doesnt work either.

**Comment by tobiasdiez** [comment]
Might be the same as https://github.com/prisma/prisma/issues/7176

**Comment by janpio** [comment]
@chachew Are you on Windows? The backslashes indicate so, and then this would indeed be the same as https://github.com/prisma/prisma/issues/7176
