### ISSUE TITLE
npx prisma generate --watch

### ISSUE THREAD

**Issue by sandbox-apps** [prisma/prisma#8327]
## Problem
Every changes to the `schema.prisma` need to rerun the command `npx prisma generate`

## Suggested solution
Automatically generate the prisma client (generators) while on development upon file save watched via `npx prisma generate --watch` command.

**Comment by pantharshit00** [comment]
We already have this implemented.

```
❯ npx prisma generate --help
Environment variables loaded from prisma\.env

Generate artifacts (e.g. Prisma Client)

Usage

  $ prisma generate [options]

Options

  -h, --help   Display this help message
    --schema   Custom path to your Prisma schema
     --watch   Watch the Prisma schema and rerun after a change

Examples

  With an existing Prisma schema
    $ prisma generate

  Or specify a schema
    $ prisma generate --schema=./schema.prisma

  Watch Prisma schema file and rerun after each change
    $ prisma generate --watch
```

See the `--watch` flag.

**Comment by sandbox-apps** [comment]
Thanks @pantharshit00 ! When was this release?

**Comment by pantharshit00** [comment]
As far as I remember we have this since the beginning. This was implemented with `generate` itself.
