### ISSUE TITLE
Allow setting scalar list default values

### ISSUE THREAD

**Issue by casey-chow** [prisma/prisma#8330]
## Problem

I'm currently migrating a schema which has a non-empty string default. My schema looks like this:

```
model Person {
  emails String[]
}
```

This is how it is generated from `prisma introspect`, decided from #1110. However, when running `prisma migrate dev`, the generated migration then attempts to remove the default, generating:

```sql
ALTER TABLE "Person" ALTER COLUMN "emails" DROP DEFAULT;
```

Removing this and attempting to add a default using `dbgenerated` leads to the following error:

```
Error parsing attribute "@default": Cannot set a default value on list field.
```

## Suggested solution

As far as I can tell, this error is entirely artificial at this point because the release of [2.16.0](https://github.com/prisma/prisma/releases/tag/2.16.0) introduced a workable syntax for scalar lists via `dbgenerated`. I'd like to propose simply removing this check:

https://github.com/prisma/prisma-engines/blob/215319b1f112e9e5b5a1f2d2b0553982d2669776/libs/datamodel/core/src/transform/ast_to_dml/db/attributes.rs#L320-L322

## Alternatives

None considered, as I haven't found any drawbacks to this proposal.

**Comment by pantharshit00** [comment]
Thanks for bringing this up, I agree we should finally decide on how we can support defaults for scalar lists.

**Comment by pantharshit00** [comment]
Can you also try adding `@default(dbgenerated())` which might prevent the faulty migration.

**Comment by casey-chow** [comment]
> Can you also try adding `@default(dbgenerated())` which might prevent the faulty migration? (We might be actually blocking this no harm in trying)
> 
> ```prisma
> model Person {
>   emails String[] @default(dbgenerated())
> }
> ```

No dice, same error 😞

**Comment by nicklloyd** [comment]
This one is a bit painful... 

We're running: 

```
version "3.8.1"
```

Updating migration.sql to include the default doesn't help either are seems like any prisma migrate run also generates a new migration to drop the default... 

Any other work arounds?

**Comment by nicklloyd** [comment]
Last sentence https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-scalar-lists-arrays#null-values-in-arrays states: 

> To work around this issue, you can set the default value of array fields to {} at a database level

But have been unable to use migrate without it reseting, even if I alter the table in PG itself

**Comment by janpio** [comment]
Open an issue about migrations not picking that up correct please and provide all the information the issue template asks for @nicklloyd . If that is the case, it is not intended.

**Comment by janpio** [comment]
Internal note: 
There are some more similar issues collected in this column in a project board: https://github.com/orgs/prisma/projects/64#column-17788443
