### ISSUE TITLE
Use _id for mongodb ids

### ISSUE THREAD

**Issue by shash7** [prisma/prisma#8338]
## Problem
I'm migrating an existing mongodb database to use Prisma. Problem is, Prisma insists on using id field instead of _id. If I were to switch, all my existing models would break.

## Suggested solution
I'm fine if Prisma internally stores id but when I do crud operations, I want to be able to pass objects with _id field

**Comment by shash7** [comment]
Bump

**Comment by pantharshit00** [comment]
You can use `@map`. 

```prisma
model User {
  id String @id @db.ObjectID @map("_id")
}
```

There is also undocumented schema feature which lets you create a specific id type:
```prisma
type MongoID = String @id @default(dbgenerated()) @map("_id") @db.ObjectId

model User {
  id MongoID
}
```

(This is undocumented as this is subject to change. We can rename to `alias` instead of `type`)

I would close this as duplicate of https://github.com/prisma/prisma/issues/6839

**Comment by shash7** [comment]
Not sure why this is closed. There's literally no way to use _id with an existing mongodb database. If I use @map("id"), prisma generate throws an error:
` Error validating field 'id': MongoDB model IDs must have a @map("_id") annotation, found @map("id")`

**Comment by pantharshit00** [comment]
Oh, thats what you mean. 

> , Prisma insists on using id field instead of _id

I interpreted this incorrectly. I will reopen this.

**Comment by janpio** [comment]
@shash7 What do you models in MongoDB look like? The error message you posted indicates you did not use what @pantharshit00 suggested (`id String @id @db.ObjectID @map("_id")`) but did the opposite of trying to use `@map("id")` - which indeed can not work if you data itself uses `_id`.

**Comment by shash7** [comment]
I did some testing and it turns out that there's no way to set _id
Basically something like this won't work:
```
let user = {
                _id : 'someid',
		name: '',
		metrics: {
			accountType:''
		},
	};

	const newUser = await prisma.user.create({
		data: user,
	});
```
@janpio if there's a way around this let me know otherwise I get it - Prisma doesn't allow setting _id field(it has to be a id field)

**Comment by pantharshit00** [comment]
It will still be stored as `_id` in the database. The schema spec doesn't allow identifiers to start with `_` so that's why you use a `@map` there. 

What I initially though you meant that you are trying to store ids as `id` field in the database instead of `_id` in mongodb. 

You will use `id` in the client in and it map to `_id` in the database. If you need to use `id` field in the database as well without `_` then this is a valid feature request.

**Comment by janpio** [comment]
> @janpio if there's a way around this let me know otherwise I get it - Prisma doesn't allow setting _id field(it has to be a id field)

Exactly. The Client code can not handle `_id` (as this is not a valid identifier in that world) so you use `@map` in the schema to make a `id` available that is persisted as `_id` in the database as it is required for MongoDB.

**Comment by shash7** [comment]
I got it. Thanks guys.

@janpio btw any way we can use a custom validator instead of the objectid validator? For instance, I create my record with the id field prefilled by another library(nanoid) and Prisma won't accept that as it is using the objectid validator(generating a objectid by myself and setting it as the id field works fine)

**Comment by janpio** [comment]
I don't think that is possible right now, but might be worth creating a new issue for with some additional explanation so the  team working on MongoDB support can look at it explicitly and see if we can do something about that.

**Comment by shash7** [comment]
Yeah exactly, that's why I closed this one.

Btw some custom apps do use custom ids for mongodb and even for postgresql.
