### ISSUE TITLE
Prisma Schema support for complex @default values

### ISSUE THREAD

**Issue by sandbox-apps** [prisma/prisma#8339]
## Problem

Prisma schema doesnt support yet adding complex default values. They are usually just simple primitive values like int 0, 1, 2..., String values and boolean = true or false but for some scenario it must be like this

```ts
const redditScore = new RedditScore(appConstant.MONGO_BASE_DATE);
const wilsonScore = require('wilson-score-rank');

return this.prisma.groupContent.create({
    data: {
        groupId: 'some-group-id',
        userId: 'some-user-id',
        text: 'Hello World',
        hotIndex: redditScore.hot(0, 0, new Date()),
        topIndex: wilsonScore.lowerBound(0, 0, { confidence: 0.95, correction: false }),
    },
});
```

Lets focus on this line
```ts
hotIndex: redditScore.hot(0, 0, new Date()),
topIndex: wilsonScore.lowerBound(0, 0, { confidence: 0.95, correction: false }),
```

This should be/can be just computed default when inserting content.
What does this benefit if implemented?
Imagine content has many subtypes like `text`, `link`, `poll`, `video`
This would make our code DRY and centralized as we dont need to implement the index property for all of this when creating subtype.

## Suggested solution
Add prisma schema ability to input complex default values.
Example:

```graphql
// prisma imports of JS/TS library

const redditScore = new RedditScore(appConstant.MONGO_BASE_DATE);
const wilsonScore = require('wilson-score-rank');

model Content {
  hotIndex Int @default(redditScore.hot(0, 0, new Date()))
  topIndex Int @default(wilsonScore.lowerBound(0, 0, { confidence: 0.95, correction: false }))
})
```

**Comment by pantharshit00** [comment]
The schema is meant to represent database/datasource features. I don't think we can easily add support for defaults where we will need to run javascript.

**Comment by sandbox-apps** [comment]
I think I should close this. Your right about how this represents database...
But if somethings comes up to this I still willing to have a support for that use case above.
