### ISSUE TITLE
`mysql2 is not a supported database URL scheme`

### ISSUE THREAD

**Issue by seed-of-apricot** [prisma/prisma#8344]
### Bug description

The error `mysql2 is not a supported database URL scheme` is shown when I use certain settings with planetscale database.

Full error in the playground: 

```graphql
{
  "errors": [
    {
      "message": "\nInvalid `prisma.article.findMany()` invocation:\n\n\n  The provided database string is invalid. Error parsing connection string: mysql2 is not a supported database URL scheme. in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "articles"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "clientVersion": "2.26.0",
          "stacktrace": [
            "Error: ",
            "Invalid `prisma.article.findMany()` invocation:",
            "",
            "",
            "  The provided database string is invalid. Error parsing connection string: mysql2 is not a supported database URL scheme. in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.",
            "    at cb (C:\\Users\\apricot\\src\\kemakino\\3RFM-ITS-Davis\\publication-manager\\server\\node_modules\\@prisma\\client\\runtime\\index.js:33902:17)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

Edit: Is it possible that the error is caused by not having prisma itself in my global scope?

### How to reproduce

1. Install planetscale CLI
2. Have the schema (details below)
3. Connect and run the program by using `-execute` option of the CLI.
4. Navigate to the playground and run any queries.

### Expected behavior

The prisma client successfully connects the planetscale database, using `mysql://~~~` connection string.

### Prisma information

prisma schema:
```prisma
datasource db {
  provider          = "mysql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
  planetScaleMode   = true
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["planetScaleMode"]
}

model User {
  id    String @id @default(uuid())
  name  String
  email String @unique
}

...
```

package.json:
```json
"dependencies": {
    "@prisma/client": "^2.26.0",
    "..."
  },
"scripts": {
    "build": "npx prisma generate",
    "format": "npx prettier --write './**/*.{ts,md}'",
    "dev": "pscale connect publication next --execute \"ts-node-dev --transpile-only --no-notify api/app.ts\"",
    "start": "pscale connect publication next --execute \"ts-node --transpile-only api/app.ts\"",
    "seed": "ts-node prisma/seed.ts"
  },
```

### Environment & setup

- OS: Windows
- Database: MySQL (planetscale)
- Node.js version: v12.18.3
- planetscale CLI version: 0.57.0

### Prisma Version

```cmd
C:\Users\apricot\src\kemakino\3RFM-ITS-Davis\publication-manager\server>npx prisma -v
Environment variables loaded from prisma\.env
prisma               : 2.27.0
@prisma/client       : 2.26.0
Current platform     : windows
Query Engine         : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ..\..\..\..\..\AppData\Roaming\npm-cache\_npx\35080\node_modules\prisma\node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ..\..\..\..\..\AppData\Roaming\npm-cache\_npx\35080\node_modules\prisma\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ..\..\..\..\..\AppData\Roaming\npm-cache\_npx\35080\node_modules\prisma\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ..\..\..\..\..\AppData\Roaming\npm-cache\_npx\35080\node_modules\prisma\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : cdba6ec525e0213cce26f8e4bb23cf556d1479bb
Studio               : 0.410.0
Preview Features     : planetScaleMode

C:\Users\apricot\src\kemakino\3RFM-ITS-Davis\publication-manager\server>prisma -v
'prisma' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by seed-of-apricot** [comment]
I found that when I directly write `"mysql://root@127.0.0.1:3306/[database]"` in prisma.schema and generate it it does not cause the error above, so it is the workaround for now.

**Comment by pantharshit00** [comment]
Yeah, we don't support `mysql2` in the connection string and you need to change it to `mysql`. 

We might support it as an alias though so I am keeping this open as a feature request. 

Also, see https://github.com/prisma/prisma/issues/7292 for planetscale

**Comment by seed-of-apricot** [comment]
Thanks for referring to the summary issue. I meant though when I write `mysql://` in .env it doesn't work but when I write it in the prisma schema directly it works, so I believe there's something wrong in the env parser.

**Comment by pantharshit00** [comment]
Yeah, that is expected. Planetscale sets up `DATABASE_URL` as `mysql2://<.........>` which is not support by our connection string parser. We only support `mysql://<....>` at the moment.

**Comment by seed-of-apricot** [comment]
But even if I write the `mysql://` string in the .env file it seems to be parsed to `mysql2://` when the program runs. How would this occur?

**Comment by pantharshit00** [comment]
That is because `DATABASE_URL` set by pscale cli take precedence over the `.env` file.

**Comment by seed-of-apricot** [comment]
OK so I changed the variable name in the .env file and then it worked, which could be the best workaround for now.

**Comment by Jp6776** [comment]
Thankyoh


Sent from my Huawei phone


-------- Original message --------
From: "seed.of.apricot" ***@***.***>
Date: Fri, 23 Jul 2021, 02:58
To: prisma/prisma ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [prisma/prisma] `mysql2 is not a supported database URL scheme` (#8344)

Closed #8344<https://github.com/prisma/prisma/issues/8344>.

**Comment by janpio** [comment]
PlanetScale was so nice to add `execute-protocol` to the `pscale connect` command so you can make it generate a `DATABASE_URL` that works with Prisma:

> `pscale connect e2e-tests main --execute-protocol 'mysql' --execute-env-url 'PLANETSCALE_DATABASE_URL' --execute 'yarn test' --debug`
https://github.com/prisma/e2e-tests/blob/3e622af41f3fab968c1b45748fd79cce3be25008/databases/planetscale/test.sh#L6

(Note that `--execute-env-url 'PLANETSCALE_DATABASE_URL'` is not necessary and enables you to use another env var name than `DATABASE_URL` that `connect --execute` sets by default)

**Comment by seed-of-apricot** [comment]
@janpio That's a nice feature indeed, thanks. Could you then please update the summary of #7292? If someone uses the example shown in list 4 they'll get the same error.

**Comment by janpio** [comment]
Good point, updated both 1) and 4) in that issue and posted a small update https://github.com/prisma/prisma/issues/7292#issuecomment-889068924

PlanetScale will soon have a connection string themselves, so this will be simplified a lot.

**Comment by seed-of-apricot** [comment]
Great, thank you!
