### ISSUE TITLE
Comparison between fields in `where` selector

### ISSUE THREAD

**Issue by Marcados** [prisma/prisma#8391]
## Problem

I'm always frustrated when it comes to fetch object according to a comparison between its own fields.

## Suggested solution

It would be great to have a way to compare a field of an object with an other field of the same object, and use this operation as a "where" selector.

## Alternatives

`prisma.user.findMany({ where : { equal: [firstname, lastname] } }) `

**Comment by matthewmueller** [comment]
Hey @Marcados, thanks for creating this issue. Could you provide an example? I'm having a bit of a hard time following what you mean.

**Comment by Marcados** [comment]
Het @matthewmueller ! Here is an example:

I want to find every users whose firstname equals lastname. 
Today, the solution is to fetch every users, and for each, make a manual comparison:

`const users = await prisma.user.findMany()
const usersWithFirstnameEqualsLastame = []
users.forEach((user) => {
if (user.firstname === user.lastname) {
usersWithFirstnameEqualsLastame.push(user)
}
})
`

The suggestion is to make it possible to specify this kind of research in the where selector directly.

Tell me if this is still unclear.

**Comment by t1nky** [comment]
Related: https://github.com/prisma/prisma/issues/5048

**Comment by janpio** [comment]
I think this is implemented already, and generally available since Prisma 5:
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#compare-columns-in-the-same-table
