### ISSUE TITLE
onDelete cascade parent relation record is not removed if child records are all deleted  

### ISSUE THREAD

**Issue by ridhwaans** [prisma/prisma#8397]
### Bug description

Tested this on a `2.26` schema  

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialActions","orderByRelation"]
}

model Deck {
	id      				Int		@id @default(autoincrement())
	product_id		       String	@unique
	cards                               Card[]
        artists				Artist[]
}

model Card {
	id      				Int      	@id @default(autoincrement())
	deck_product_id              String
	deck    				Deck    	@relation(fields: [deck_product_id], references: [product_id], onDelete: Cascade)
	product_id                       String		@unique
}

model Artist {
	id      				Int		@id @default(autoincrement())
	decks                              Deck[]
}
```  

A Deck has many Cards and has at least one Artist. There are multiple Decks    
the expectation is that if all card records are deleted, the corresponding Deck record should also be deleted, as cascade is enabled.   
In other words if a Deck has empty Cards after the last Card is deleted, it should also be deleted.    
Is Deck not getting removed because it has at least one Artist?  Artist has no other dependency except Deck   

### How to reproduce

1. Use Prisma Client 2.26 with preview features
2. Reproduce schema

### Prisma information

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialActions","orderByRelation"]
}

model Deck {
	id      				Int		@id @default(autoincrement())
	product_id		       String	@unique
	cards                               Card[]
        artists				Artist[]
}

model Card {
	id      				Int      	@id @default(autoincrement())
	deck_product_id              String
	deck    				Deck    	@relation(fields: [deck_product_id], references: [product_id], onDelete: Cascade)
	product_id                       String		@unique
}

model Artist {
	id      				Int		@id @default(autoincrement())
	decks                              Deck[]
}
```  

### Environment & setup

- OS: Ubuntu Linux WSL2 (Windows 10) 
- Database: SQLite
- Node.js version: v16.3.0

### Prisma Version

```
"@prisma/client": "^2.26.0",
 "prisma": "^2.26.0"
```

**Comment by pantharshit00** [comment]
This is expected. Cascade only works from parent to child not the other way around. You won't be able to even create a `Deck` if it automatically deleted before adding any children.

**Comment by ridhwaans** [comment]
if Deck needs to be removed you need to perform an additional query and check for parents everytime a child is removed?  
at present, if a child has more than one parent, will the child still get cascade deleted if one of its parent is deleted?

**Comment by dpetrick** [comment]
Generally: Cascades perform exactly as the underlying database handles them, the behavior you want can't be achieved only with foreign keys in SQL (which is what Prisma uses), but you'd need additional constructs like triggers. As you said, extra queries are an option that you can do either with every delete or that you run periodically to clean up records with no related records - depends on your requirements.

> at present, if a child has more than one parent, will the child still get cascade deleted if one of its parent is deleted?

That depends where the foreign key is located that has the cascade defined. If you say "child has many parents" then I assume the key is on the parent like this (you can't do differently):

```prisma
model Parent {
  // ...
  child_id String
  child Child @relation(fields: [child_id], references: [id], onDelete: Cascade)
}

model Child {
  // ...
  p Parent?
}
```

The above means that if a child is deleted, the parent will also be deleted. This _does not_ mean that the inverse is true. If you delete a Parent, the child is unaffected here.

**Comment by ridhwaans** [comment]
Just following up on this, sorry for the late response
Key definition is like this
```
model Parent {
  // ...
  children Child[]
}

model Child {
  // ...
  p Parent @relation(fields: [parent_unique_id], references: [unique_id], onDelete: Cascade)
}
```
Your point is correct, should I move the relation and test? The parent has to be deleted if its child collection is empty. Parents cannot be deleted directly and a child cannot exist without a parent connection.
Thanks

**Comment by SevInf** [comment]
@ridhwaans I don't think what you want is doable with cascades. If you want to delete `Parent` when all children are deleted, do a separate query for that. 
I am going to close this now, since cascades work as expected.
