### ISSUE TITLE
mysql数据类型是BigInt时，返回的数据带n

### ISSUE THREAD

**Issue by 18124772589** [prisma/prisma#8430]
### Bug description

使用prisma客户端的API查询mysql里的数据时，数据类型是BigInt时，数据带n，直接返回会报错：TypeError: Do not know how to serialize a BigInt

### How to reproduce

1. 
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
       try {
            const userList = prisma.user_coupon.findMany()
            return res.status(200).json({
                status: 200,
                message: '成功',
                data: userList
            })
        } catch (err) {
            console.log("getUserList...err...", err)
            return res.status(400).send(err)
        }
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```
2. See error

### Expected behavior

希望bigint类型能正常的返回数据，不希望带n，也不希望报错

### Prisma information

@prisma/client: 2.27.0
prisma:  2.27.0
express:  4.17.1

### Environment & setup

Prisma 客户端查询

### Prisma Version

"@prisma/client": "version": "2.27.0",
"prisma": "version": "2.27.0",

**Comment by pantharshit00** [comment]
Please keep the issue in English. 

What I can infer is you are trying to serialize BigInt which javascript `JSON.stringify` function can't do. 

Try using this library here: https://github.com/blitz-js/superjson#readme

**Comment by imyangyong** [comment]
![CleanShot 2021-07-30 at 19 44 21@2x](https://user-images.githubusercontent.com/42476396/127648506-5b7e5a8b-e4c8-4bb5-81ed-9a70e4e95057.png)

The data returned by bigint type with an incorrect "n" string

**Comment by pantharshit00** [comment]
That is expected. BigInt's are represented using `n`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

You big is related to calling `.json` on BigInts. BigInts can't be serliazed by javascript JSON functions: https://dev.to/benlesh/bigint-and-json-stringify-json-parse-2m8p
