### ISSUE TITLE
`@prisma/sdk` can't find query-engine binary (Vercel + Next.js)

### ISSUE THREAD

**Issue by Ovyerus** [prisma/prisma#8441]
### Bug description

When deploying a Next.js project to Vercel that makes use of `@prisma/sdk` directly (parsing DMMF, formatting a string, etc.), code using it fails with a `Could not find query-engine binary. Searched in ...` error.

I've tried some stuff from other issues like marking it as an external, or disabling Webpack 5 or downgrading the SDK, but nothing's work so far.

### How to reproduce

Minimal reproduction available at https://github.com/Ovyerus/prisma-sdk-vercel-repro, or https://prisma-sdk-vercel-repro.vercel.app/ for an already deployed version.

1. Make a Next.js project.
2. Add `@prisma/sdk` as a dependency
3. Make an API route or `getServerSideProps` that uses functionality from `@prisma/sdk`
4. Deploy to Vercel.
5. Navigate to page/route containing `@prisma/sdk` calls.

### Expected behavior

Prisma SDK successfully locates the query-engine binary and works as normal.

### Environment & setup

- OS: N/A (Vercel)
- Database: N/A
- Node.js version: 14.17.3 (I presume)

### Prisma Version

```
From yarn.lock

@prisma/sdk: 2.27.0
@prisma/engines: 2.27.0-43.cdba6ec525e0213cce26f8e4bb23cf556d1479bb
```

**Comment by janpio** [comment]
Via `NEXT_DEBUG_FUNCTION_SIZE` on Vercel I get this output:
```
22:18:03.172  	Serverless function size info
22:18:03.172  	Serverless Function's page: api.js
22:18:03.177  	Large Dependencies                  Uncompressed size  Compressed size
22:18:03.177  	node_modules/encoding/node_modules             329 kB           179 kB
22:18:03.177  	node_modules/@prisma/engines                   629 kB           129 kB
22:18:03.178  	All dependencies                               3.9 MB          1.22 MB
22:18:03.288  	Created all serverless functions in: 4.286s
```
So the generated and uploaded function definitely does _not_ include the correct Engine(s) which are >10MB uncompressed.

When I run `npm install` on the project locally, I indeed do get the files (even twice as I am on Windows and the cache folder is in the project folder) which leads to this working: 
![image](https://user-images.githubusercontent.com/183673/127222593-f8eb1b7f-c6d4-4015-95cd-dacac0d83531.png)

I would say that we in Prisma CLI and Client usually do some magic to tell Vercel's function packaging tool to include the engines - which we probably/possibly do not do in the SDK package itself as that is indeed a bit of an uncommon use case (and not fully supported yadda yadda).

I will ask the right people internally how this can be fixed - I think with a few lines of code in your project you can easily make it pick up the Query Engine as well and upload it to Vercel's serverless function.

**Comment by janpio** [comment]
And found a solution: https://github.com/Ovyerus/prisma-sdk-vercel-repro/pull/1

What is weird here on Prisma side, is that the error message actually pointed us to a _different_ path (in `@prisma/sdk`) than to where it is really loaded from (`@prisma/engines`) - this might be a bug on our side we could look at.

**Comment by Ovyerus** [comment]
Confirmed that solution fixed the issue in the project I initially discovered this in.

The message pointing to a different path not relating to `@prisma/engines` definitely sounds suspect.

**Comment by janpio** [comment]
I'll open a new issue about the error message.
