### ISSUE TITLE
Add hooks functionality or make middlewares work with both incoming and outcoming data

### ISSUE THREAD

**Issue by mateusbds** [prisma/prisma#8442]
## Problem

Nowadays the laws of encrypting user data are getting stronger, so if even someone get access to the database, they will only see encrypted strings. In prisma I can use middlewares to intercept the query, but it only works for incoming queries (if I recall correctly).
I was not able to implement this feature using middlewares, and ended up doing this encryption and decryption before and after updating the data, which makes the code very verbose, since I have to go through a lot of diferent tables.

A piece of code as example:
```
async update(patientId: string, profileDto: ProfileDTO): Promise<Profile> {
  const encrypted = encryptColumns(PROFILE_COLUMNS, profileDto);

  const profile = await this.prismaService.profile.upsert({
    where: { patientId },
    create: { ...encrypted, patientId },
    update: { ...encrypted },
  });

  return decryptColumns(PROFILE_COLUMNS, profile);
}
```

Another problem that I'm facing is that the encryption process forces everything to be string, making hard to work with another types that are not string in the schema, like booleans for example, I will need to cast everything after the decryption in each iteration with the database.

## Suggested solution

I think that some kind of hook, that would work like middlewares, could help filling both needing listed above, something like:

```
beforeCreate(data) {
  encryptColumns(PROFILE_COLUMNS, data);
}

afterCreate(data) {
  return decryptColumns(PROFILE_COLUMNS, data);
}
```

or something [like Laravel does](https://laravel.com/docs/8.x/eloquent-mutators#accessors-and-mutators):

```
getAttribute($value) {
  return $value;
}

setAttribute($value) {
  $value;
}
```

Thanks in advance and sorry if I missed something. ☺

**Comment by janpio** [comment]
Middlewares can influence both the parameters to the query, and the data that is being returned: https://www.prisma.io/docs/concepts/components/prisma-client/middleware Just do your manipulation _after_ calling `await next()`. 

(As long as you only modify the data you can do what ever you want, when you want to touch the _structure_ it gets a bit more complex as the types can not dynamically be updated.)

Does this solve your problem already?

**Comment by mateusbds** [comment]
> 
> 
> Middlewares can influence both the parameters to the query, and the data that is being returned: https://www.prisma.io/docs/concepts/components/prisma-client/middleware Just do your manipulation _after_ calling `await next()`.
> 
> (As long as you only modify the data you can do what ever you want, when you want to touch the _structure_ it gets a bit more complex as the types can not dynamically be updated.)
> 
> Does this solve your problem already?

It does! Thank you very much for the clarification.
