### ISSUE TITLE
An optional one-to-many relationship still creates a foreign key constraint

### ISSUE THREAD

**Issue by sam-bunger** [prisma/prisma#8447]
### Bug description

The [prisma docs](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-many-relations#required-and-optional-relation-fields-in-one-to-many-relations) here say that optional one-to-many relationships are possible. When it test this myself, a foreign key constraint keeps getting generated, preventing me from creating rows that don't have a reference.

### How to reproduce

1. Copy prisma schema from down below
2. Run `prisma db push`
3. Run `create` query from down below 
4. Run `createMany` query from down below

You should be getting this error on the second query:
```
Invalid `prisma.contacts.createMany()` invocation:
Foreign key constraint failed on the field: `contacts_contact_fkey (index)`
```

### Expected behavior

The `contacts` table in this schema is meant to store a list of contacts for each user that can potentially point to other user profiles if they exist in the database. `contact_holder` points to the primary key of the `profiles` table and `contact` will optionally point to `phone_number` in the `profiles` table if a user with that number exists. 

According to the docs, this should allow me to add a number that doesn't exist yet:
``` prisma
contact            String
contact_ref        profiles? @relation(fields: [contact], references: [phone_number])
```

However when I run `prisma db push` a foreign key called `contacts_contact_fkey` is being generated that prevents me from doing this.

### Prisma information

This is the schema that i'm using. The relationship I noticed this issue with is between `profile.phone_number` and `contacts.contact`
```prisma
model profiles {
  id               String          @id
  first_name       String?
  last_name        String?
  phone_number     String          @unique
  phone_number_ref contacts[]
  holder_ref       contacts[]      @relation("contactHolder")
}

model contacts {
  contact            String
  contact_ref        profiles? @relation(fields: [contact], references: [phone_number])
  contact_holder     String
  contact_holder_ref profiles  @relation("contactHolder", fields: [contact_holder], references: [id])

  @@id([contact_holder, contact])
}
```
This query will work, but is needed to get the right error on the second query.
```typescript
await prisma.profiles.create({
  data: {
    id: '1234',
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '1234567899'
  }
});
```
This query should fail:
```typescript
await prisma.contacts.createMany({
    data: [{
        contact_holder: '1234', 
        contact: '1238008001' //A user with this phone number does not exist yet in profiles table
    }],
    skipDuplicates: true
  });
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.15.3

### Prisma Version

```
prisma               : 2.27.0
@prisma/client       : 2.27.0
Current platform     : darwin
Query Engine         : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : cdba6ec525e0213cce26f8e4bb23cf556d1479bb
Studio               : 0.410.0
```

**Comment by pantharshit00** [comment]
@sam-bunger You are marking the relation optional but the field that you are using to maintain the relation is not optional. `contact` should be `String?` instead of `String`.

**Comment by sam-bunger** [comment]
Hey @pantharshit00, apologies for the late response. In this case `contact` isn't optional, but it's relationship to `phone_number` in the `profiles` table is. So, there is the chance that a phone number will appear in the `contact` field that doesn't correspond to any `phone_number`. Is this possible at all?

**Comment by goleary** [comment]
I'm having the same issue.

models here:
```
model User {
  idStr String @id 
  name String?
  statuses Status[]
}

model Status {
  idStr String @id
  userIdStr String
  user User? @relation(fields: [userIdStr], references: [idStr])
}
```
I'd like to be able to insert `Status` records for which there are no corresponding `User` records.

There _is_ a `userIdStr` for every `Status`, but there may not be a `User` record for that `userIdStr`.

(I don't think `kind/support` is a valid tag for this issue).

**Comment by robertteevans** [comment]
I too have this exact same issue. What's the reason this hasn't been labeled a bug?

**Comment by sam-bunger** [comment]
prisma/prisma-engines#2221 fixes this issues
