### ISSUE TITLE
Add flag to return .createMany output as .findMany output

### ISSUE THREAD

**Issue by sandbox-apps** [prisma/prisma#8448]
## Problem
Using createMany returns output as a the count of row inserted

## Suggested solution
Add a boolean flag to support to return the added values instead of row count added. It should have the option to return response just like the findMany output

**Comment by ulo** [comment]
+1
having the return values (IDs) would also help to get a workaround for the lack of nested createMany https://github.com/prisma/prisma/issues/5455

**Comment by janpio** [comment]
Closing as duplicate of #8131 indeed. Leave a 👍 there if you have not yet.
