### ISSUE TITLE
`config.datasources[0].provider` from GetConfig needs to be a string and not a string[]

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#8467]
### Problem

```
const config = await getConfig({
	datamodel: schema,
})

// this `provider` value was a string before 2.22.0 but is now an array of string
config.datasources[0].provider
```

This is the related commit that introduced the regression:
https://github.com/prisma/prisma-engines/commit/b096a80dd515ef7c3a598867d307f729dcc0712b 

In this commit it looks like we removed the array from the datasource but added it to the serialization.
<img width="491" alt="Screen Shot 2021-07-27 at 16 40 35" src="https://user-images.githubusercontent.com/1328733/127189554-c08a04cc-7eab-4e51-8a51-8ddba074d8c2.png">
<img width="468" alt="Screen Shot 2021-07-27 at 16 40 11" src="https://user-images.githubusercontent.com/1328733/127189561-c90e1c0d-b66e-4b25-bdb4-09317d73b37f.png">

Rust Type found in https://github.com/prisma/prisma-engines/blob/master/libs/datamodel/core/src/configuration/datasource.rs#L12-L13
```
    /// The provider string
    pub provider: String,
```

the tests also show it’s currently an array of strings with only one string https://github.com/prisma/prisma-engines/blob/master/libs/datamodel/core/tests/config/datasources.rs#L16

### Suggestion

I think it should be a string and not an array returned here by the Rust code. 

I could monkey patch in the CLI but it seems wrong because we have a datasource[] array and each datasource can only have one provider.
It looks like some legacy from the multi provider array feature deprecated a while ago.

[Internal Slack Thread here](https://prisma-company.slack.com/archives/CC59J6VEY/p1626793129000400)

**Comment by thebiglabasky** [comment]
We'll for now research places where this fix on `getConfig` would have an impact to ensure we don't break unexpectedly shortly before releasing.
Next step is to share the outcome of the research here before deciding how to fix this.
People to speak to: @madebysid (Studio), @millsp and/or @williamluke4

**Comment by madebysid** [comment]
Studio doesn't use `getConfig` directly anymore, so we're good there. If the `getGenerators` function behaves the same as before, Studio will not need any changes.

**Comment by Jolg42** [comment]
Found these lines using it, we can easily fix them after the engine fix:
- https://github.com/prisma/prisma/blob/7a6ad37daa6f91a3bff5522c1527fa25ba3acdf8/packages/sdk/src/engine-commands/getConfig.ts#L56
- https://github.com/prisma/prisma/blob/7a6ad37daa6f91a3bff5522c1527fa25ba3acdf8/packages/sdk/src/getGenerators.ts#L154-L162
- https://github.com/prisma/prisma/blob/7a6ad37daa6f91a3bff5522c1527fa25ba3acdf8/packages/migrate/src/utils/ensureDatabaseExists.ts#L110
- https://github.com/prisma/prisma/blob/7a6ad37daa6f91a3bff5522c1527fa25ba3acdf8/packages/migrate/src/utils/ensureDatabaseExists.ts#L76

Tried the hacky patch on TS side and can confirm it works.

**Comment by pimeys** [comment]
Reopening, so @Jolg42 can close it if nothing breaks in the clients.

**Comment by Jolg42** [comment]
Closing, small changes were made in https://github.com/prisma/prisma/pull/8556

Thanks! 💚
