### ISSUE TITLE
default naming conventions in schema indexes generated by introspection produce improper types

### ISSUE THREAD

**Issue by traviseden** [prisma/prisma#8495]
### Bug description

Note: this is solved and low priority

I am using blitzjs but looking through their code they just wrap around prisma so I am pretty sure this generalizes beyond blitzjs.

I introspected a database and got a schema with indexes where names included periods (like the docs say):

```
model Channel {
  id           Int       @id @default(autoincrement())
  meetingSlug  String
  title        String
  categorySlug String
  category     Category  @relation(fields: [categorySlug], references: [slug])
  meetings     Meeting[]

  @@unique([categorySlug, meetingSlug], name: "Channel.categorySlug_meetingSlug_unique")
}
```

I ran `prisma generate` and got types that worked fine up until I went to build my project where I got typescript errors in `node_modules/.prisma/client/index.d.ts` like this one:

```
Type error: Property or signature expected.

  8517 |   export type ChannelWhereUniqueInput = {
  8518 |     id?: number
> 8519 |     Channel.categorySlug_meetingSlug_unique?: ChannelChannel.categorySlug_meetingSlug_uniqueCompoundUniqueInput
       |     ^
  8520 |   }
```

At first I messed with `index.d.ts` and got it to build but changing code in `node_modules` won't work in a production pipeline. So I edited the schema by changing all the periods to underscores. Then I went with double underscores because the period was meant to differentiate table from field names. Not just `@@index` but also `@@unique`.

I am all set but figured I would share in case it's worth changing this convention. I thought about making a PR but I have only dabbled in Rust and you may have reasons for the naming convention that go beyond my understanding.

Thanks for all your hard work, Prisma team. This is an incredibly useful project.

### How to reproduce

1. `prisma introspect` a database with indexes
2. `prisma generate` types for your given schema
3. attempt to deploy

### Expected behavior

I expected to be able to introspect and generate without having to mess with the types or schema.

### Prisma information

see: bug description

### Environment & setup

Ubuntu 20.04.2 LTS
PostgreSQL 12.7
node: 16.5.0
typescript: 4.3
prisma: 2.27.0

### Prisma Version

```
2.27.0

```

**Comment by pantharshit00** [comment]
Thanks for reporting! This is definitely a bug. 

We are working on https://github.com/prisma/prisma/issues/6680 right now which will introduce `map` in indexes and it will enable renaming the index for the client without changing its name in the database.

**Comment by matthewmueller** [comment]
Next step:
- Check with @do4gr that this is fixed

**Comment by do4gr** [comment]
A fix for this issue is now available via the `namedConstraints` preview flag since 2.29. See https://www.prisma.io/docs/guides/upgrade-guides/upgrading-to-use-preview-features/enabling-named-constraints
