### ISSUE TITLE
.gitignore is being overwrittern by `prisma init`

### ISSUE THREAD

**Issue by BenjaminGuzman** [prisma/prisma#8496]
### Bug description

When you run `npx prisma init` everything executes without problems but the `.gitignore` file is being overwritten with the following content mentioned in Issue #3400

### How to reproduce

1. Create an empty `npm` project
2. Create and add some contents to `.gitignore`
3. Run `npx prisma init`
4. Open the `.gitignore` file and notice it was overwritten

### Expected behavior

The expected behavior may be simply not overwrite the `.gitignore` if it already exists, instead just output some message like: *Be sure to exclude node_modules and .env files inside .gitignore*.

### Prisma information

Nothing. I'm just starting prisma

### Environment & setup

- OS: Fedora
- Database: I don't think this is relevant
- Node.js version: v14.17.0

### Prisma Version

```
prisma               : 2.28.0
@prisma/client       : Not found
Current platform     : rhel-openssl-1.1.x
Query Engine         : query-engine 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/query-engine-rhel-openssl-1.1.x)
Migration Engine     : migration-engine-cli 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/migration-engine-rhel-openssl-1.1.x)
Introspection Engine : introspection-core 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.1.x)
Format Binary        : prisma-fmt 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/prisma-fmt-rhel-openssl-1.1.x)
Default Engines Hash : 89facabd0366f63911d089156a7a70125bfbcd27
Studio               : 0.417.0
```

**Comment by ShubhankarKG** [comment]
What should be the expected behavior if .gitignore exists? Is it as suggested by OP or something else as well?

**Comment by pantharshit00** [comment]
@ShubhankarKG If a `.gitignore` already exists we should not override it and maybe print a warning.

**Comment by mustofa-id** [comment]
modify/append the content seems much better.

**Comment by janpio** [comment]
Yes, but the complexity of that is much higher for a edgecase feature. Choosing the simpler way to just skip the file sounds perfectly fine in this case - and is much less to maintain.

**Comment by dlandry-siesde** [comment]
Came here from adding Prisma to an existing project. The "[Prisma Getting Started: Add to an existing project](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases-typescript-postgres#set-up-prisma)" guide instructs to run `npx prisma init`.

**Comment by janpio** [comment]
There is an open PR at https://github.com/prisma/prisma/pull/8509 that should solve the `.gitignore` problem. That was definitely not intended.

**Comment by janpio** [comment]
New PR: https://github.com/prisma/prisma/pull/8946
