### ISSUE TITLE
Passwords for MySQL and PostgreSQL cannot contain the `#` character

### ISSUE THREAD

**Issue by lbogerd** [prisma/prisma#8498]
### Bug description

Currently passwords (and maybe assume other strings?) may not contain the # character. I assume it's not correctly being escaped. 

I tried using all escape characters I could think of: `\` `'` `"`  `backtick` (which I ironically cannot get to show as \` formatted as code on GitHub). 
I tried the mentioned characters when setting the URL directly in the schema as well as a variable in `.env`

### How to reproduce

1. Set url to `mysql://user:pass#word@localhost:3306/mydb` in `.env`
2. Run `npx prisma introspect`
3. Receive the following error `Error parsing connection string: invalid port number in database URL`
5. Same result when removing/adding `"`
6. Same result when setting url directly in the schema
7. Remove the `#` and notice the error is now the following, indicating that the string was parsed successfully: 
`P1001`
`Can't reach database server at localhost:3306`
`Please make sure your database server is running at localhost:3306.`

### Prisma information

```
datasource db {
  provider = "mysql"
  url = "mysql://user:pass#word@localhost:3306/mydb"
}

generator client {
  provider = "prisma-client-js"
}
```

### Environment & setup

- OS: Windows and Ubuntu 20.04 (run via WSL2)
- Database: MySQL and also PostgreSQL based on my quick tests, **_not_** MSSQL though. Did not test SQLite and MongoDB
- Node.js version: 14.17.3 on Windows, 14.17.4 on Ubuntu

### Prisma Version

```
prisma               : 2.28.0
@prisma/client       : Not found
Current platform     : windows
Query Engine         : query-engine 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 89facabd0366f63911d089156a7a70125bfbcd27
Studio               : 0.417.0
```

and 

```
prisma               : 2.28.0
@prisma/client       : Not found
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 89facabd0366f63911d089156a7a70125bfbcd27
Studio               : 0.417.0
```

**Comment by pantharshit00** [comment]
@lbogerd You will need to use percent encoding here. `#` in percent encoding is `%23` so the connection string will look `mysql://user:pass%23word@localhost:3306/mydb`

Ref:
https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html

https://tools.ietf.org/html/rfc3986#section-2.1

**Comment by pantharshit00** [comment]
Here is our docs section on this: https://www.prisma.io/docs/reference/database-reference/connection-urls/#special-characters

**Comment by lbogerd** [comment]
Not sure how I completely missed this obvious solution. Thank you for taking the time to answer!
