### ISSUE TITLE
Prisma with LevelDB

### ISSUE THREAD

**Issue by hanumanjiblog** [prisma/prisma#8526]
is Prisma support LevelDB, how? please send some code.

https://github.com/google/leveldb

**Comment by pantharshit00** [comment]
No, we don't currently support leveldb.

**Comment by hanumanjiblog** [comment]
Please take a Future Request, LevelDB is a Key Value database, It easy to implement and development.

**Comment by GildedPleb** [comment]
https://github.com/GildedPleb/relational-leveldb

Though it is far from complete (and doesn't have any tests, YOLO!), it scaffolds an MVP: Persistent and embedded Relational Data in LevelDB as defined by a `schema.prisma` file, with a generated client exposing basic, but typed, CRUD operations in a  Prisma Client-like style. 

Also, as far as I am aware, and unless someone can invalidate the claim, it may be the first relational mapping for LevelDB. Graph mappings exist, but nothing quite like a Prisma ORM. LevelDB was not made for this use case, so you probably shouldn't use this and don't need it. But if you want something embedded other than SQLite, well, here you go. In before "Your scientists were so preoccupied with whether or not they could, they didn’t stop to think if they should."

Most of the heavy lifting is done by the `prisma.prisma` extension for VS Code and the @prisma/internals.getDMMF which validates and maps the relations before any code is generated. Naturally, this implementation doesn't include any of the really awesome features, like robust query syntax, migrations, or studio. 

All that said, it would be awesome to get full LevelDB integration in Prisma to get a second natively-embedded option. After all, people tell me LevelDB is fast.

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
