### ISSUE TITLE
error client version 

### ISSUE THREAD

**Issue by rismantrdr** [prisma/prisma#8527]
i got the error when post method

{
    "error": {
        "clientVersion": "2.28.0"
    }
}

![image](https://user-images.githubusercontent.com/68155110/127762553-6a2a7c27-20da-42e5-913e-29ecbe38f35b.png)

**Comment by pantharshit00** [comment]
Can you please open a new issue and fill out the issue template? Currently you don't provide any information which can help us reproduce this.
