### ISSUE TITLE
'Submit feature request'

### ISSUE THREAD

**Issue by ahmedmogahed** [prisma/prisma#8530]
## Problem
Querying and modifying multiple schemas in a single database is not possible as far as I know. The datasource is connected to a single database as well as a single schema (e.g., public). 

## Suggested solution
A model could be mapped to a table as well as a schema inside the connected database:

@@map(name: "users", schema: "web")

**Comment by janpio** [comment]
This has been requested before: https://github.com/prisma/prisma/labels/topic%3A%20multiple%20datasources
