### ISSUE TITLE
Auto-reconnect not working when failover on google cloud.

### ISSUE THREAD

**Issue by casperstr** [prisma/prisma#8561]
### Bug description

When testing google clouds failover with HA servers the prisma client will first throw a "Server has closed the connection" error. After that all queries sent to prisma will result in " Timed out fetching a new connection from the connection pool." errors. 

### How to reproduce

1. Setup google cloud postgresql instance with HA
2. Invoke failover
3. Send queries to Prisma

### Prisma information

Prisma 2.23.0

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: 16

### Prisma Version

```
2.23.0

```

**Comment by janpio** [comment]
Prisma currently has not built in retry on failure - you need to handle that yourself.

But the resulting `Timed out fetching a new connection` is weird, as a connection error like `Server has closed the connection` indeed should remove the existings connection from the pool of course.

Can you try with the latest Prisma version please before we try to reproduce?

**Comment by janpio** [comment]
Did you ever get to trying this again @casperstr?

**Comment by janpio** [comment]
Are you also on Google Cloud and having this because of failover?

**Comment by leoShabalkin** [comment]
Yes, I use GloudeSql through PgBouncer. Problems occur only when the connection is lost.

**Comment by garrensmith** [comment]
Hi, we have made changes around the connection pool and reconnections. Would you be able to test this with `prisma@dev` to see if this issue is resolved?

**Comment by garrensmith** [comment]
@leoShabalkin I'm going to close this issue. Please open it again if you still getting this issue.
