### ISSUE TITLE
NativeScript support

### ISSUE THREAD

**Issue by darkyelox** [prisma/prisma#8578]
Would be great to open to other bridge frameworks like NativeScript (Angular, Vue, Svelte, React and plaint JS or TypeScript framework), it already has a nativescript-sqlite plugin that is used by TypeORM as a driver for SQLite databases, works good (at least till v0.2.24 😢  )

**Comment by jkomyno** [comment]
Hi there,

As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
