### ISSUE TITLE
Programmatically create a MongoDB database

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#8582]
## Situation

The internal package `@prisma/sdk` supports a `createDatabase` function. This `createDatabase` function is used by `prisma migrate dev` to create databases. For example:

```
npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "zzz", schema "public" at "localhost:5432"

PostgreSQL database zzz created at localhost:5432
```

`createDatabase` is also used in the wider community with projects like https://keystonejs.com. ([source](https://github.com/keystonejs/keystone/blob/6b0bb3d1080994fc2f6a68e202729e45ed0cf3fe/packages/keystone/src/lib/migrations.ts#L2))

## Problem

Right now we support programmatically creating local Postgres, MySQL, and SQLite databases, but not MongoDB. If you try running `npx prisma migrate dev`, you'll get the following error:

```
Error: "mongodb" provider is not supported with this command. For more info see https://www.prisma.io/docs/concepts/database-connectors/mongodb
```

## Suggested solution

`createDatabase` should also be able to create local MongoDB databases.

## Additional context

This issue will likely be addressed by https://github.com/prisma/prisma/issues/7305.

Original context in a [private Slack thread](https://prisma.slack.com/archives/CHF8JBRV2/p1626934419006900).

**Comment by matthewmueller** [comment]
Added as "Nice to Have". I do like this idea because:
- It will help Keystone
- It will simply the MongoDB getting started experience (see: https://github.com/prisma/prisma/issues/8266)

**Comment by floelhoeffel** [comment]
Let's spend 1-2 hours on a spike to find out what / if to do something.

**Comment by Jolg42** [comment]
I think it might not be needed like @tomhoule pointed out in our planning as:

I can confirm that with the dev version `3.10.0-dev.1` (and also with `3.9.0` and `3.8.0`)
- when running `prisma db push` a  non-existing database is automatically created though no lines are printed like for PostgreSQL `PostgreSQL database zzz created at localhost:5432`

**Comment by matthewmueller** [comment]
Ah interesting! Does that use `createDatabase` under the hood? The original discussion with Keystone is in this [private slack thread](https://prisma.slack.com/archives/CHF8JBRV2/p1626934419006900). 

They mentioned using `createDatabase` from the SDK and would like the same support for MongoDB.

**Comment by tomhoule** [comment]
If I remember correctly, just connecting to a non-existing database will create it automatically.

**Comment by Jolg42** [comment]
So no `createDatabase` is not used at all for `mongodb` here.

**Comment by matthewmueller** [comment]
@tomhoule great point, maybe it's as simple as defining createDatabase as a noop.

**Comment by pimeys** [comment]
I did some tests with this. This is how MongoDB works: If you connect to a database, nothing gets created. What you have to do is to create a collection to the database, and add some documents to the collection. At this point the database gets created automatically.

The question is what should happen in the `createDatabase` call. If we just do a no-op, it's a bit deceptive for the user, because nothing actually gets created...

**Comment by janpio** [comment]
The SDK could just return `true` (or whatever inidcates success) and log `MongoDB database will be created on first use` or similar. This way the SDK users can leave their code unchanged, and what is really happening is even communicated.
