### ISSUE TITLE
Provide precompiled binaries for ARM

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#861]
Currently, we do not have any precompiled binaries for the ARM platform.

Now that Windows is supported, we should look into compiling for ARM. That would enable users to Prisma 2 on Raspberry Pi and other all sorts of ARM-based devices.

This will also include adding ARM to the binaries spec: https://github.com/prisma/specs/tree/master/binaries#binary-files

Ref: https://github.com/prisma/prisma2/issues/132

**Comment by radicand** [comment]
This bit me post-dev as I got to the deployment pipeline stage of my project. Happy to see this is on the roadmap, is there a target timeline?

**Comment by schickling** [comment]
No concrete timeline target yet but building the binary yourself should already work.

@radicand can you provide some context for what your deployment setup looks like?

**Comment by radicand** [comment]
@schickling I'll see if I can do that; thanks for the info. My target deployment is on a Raspberry Pi ARM64 [k3s](http://k3s.io) cluster. In my container image for the backend, I have it execute `lift up` and also create the database if not present (for bootstrapping). Without the working binaries, these steps don't execute. I'll attempt to build manually to include in the image and follow up.

**Comment by radicand** [comment]
I've managed to cross-compile aarch64 (arm64) binaries (with some headache); once I've got them generated, what is the recommended step to make them usable? E.g., should I copy them somewhere specific; is there configuration to change, etc?

**Comment by radicand** [comment]
Is there a way to suppress the downloading of the engine binaries? In attempting to create an arm64 docker image, both `npm i` and `prisma2 build` will try to download the (non-existent) binaries and fail, even with the above ENV set.

**Comment by pantharshit00** [comment]
@radicand I would consider that as a bug that we need to fix. Can you please open a new issue about that?

**Comment by Suniron** [comment]
I can't generate prisma2 client on Raspberry pi 3b+: `node_modules/prisma2/query-engine-debian-openssl-1.1.x: cannot execute binary file`.. :'(

**Comment by janpio** [comment]
Open a new issue with the full error message and what instructions you are trying to follow please @Suniron.

**Comment by brielov** [comment]
I have a raspberry pi 4 development box and it would be awesome to have ARM support.

**Comment by janpio** [comment]
For now we document how to build yourself and how to use the built binaries at these links:
https://github.com/prisma/prisma-engines#building-prisma-engines 
https://www.prisma.io/docs/understand-prisma/under-the-hood#using-custom-engine-binaries

**Comment by sbonami** [comment]
In the interim, our friend @fabianmoronzirfas seemed to solve this and shared extensive instructions [here](https://github.com/prisma/prisma/issues/1505#issuecomment-634154657):
> Finally I got this working by (for future reference):
> 
> * installing rust and [compiling](https://github.com/prisma/prisma-engines#building-prisma-engines) the binaries directly on the Raspberry Pi
> * adding the 4 environment variables to `./prisma/.env` and made them point to my compiled binaries
> 
> ```
> PRISMA_QUERY_ENGINE_BINARY=/home/pi/bin/query-engine
> PRISMA_INTROSPECTION_ENGINE_BINARY=/home/pi/bin/introspection-engine
> PRISMA_MIGRATION_ENGINE_BINARY=/home/pi/bin/migration-engine
> PRISMA_FMT_BINARY=/home/pi/bin/prisma-fmt
> ```
> 
> * forking and cloning the whole prisma package
> * ran through first steps in [CONTRIBUTING.md](https://github.com/prisma/prisma/blob/master/CONTRIBUTING.md) to get this setup
> * added  `'arm-openssl-1.1.x'` to `const knowPlatforms: Platform[]=[…`in `src/packages/engine-core/src/NodeEngine.ts`
> * added `'arm-openssl-1.1.x'` to `type Platform = …` and `export const platforms = […` in `src/packages/get-platform/src/platforms.ts`
> * ran through first steps in [CONTRIBUTING.md](https://github.com/prisma/prisma/blob/master/CONTRIBUTING.md) again to build all packages
> * adapted my project to use `pnpm`
> * linked the cli to my project `pnpm link ../../prisma/prisma-fork/src/packages/cli`
> * ran my generate commands
> * got a beer from the fridge
> * padded my back
> 
> See my changes [github.com/fabianmoronzirfas/prisma/tree/feature-raspberry-pi](https://github.com/fabianmoronzirfas/prisma/tree/feature-raspberry-pi)

**Comment by radicand** [comment]
FWIW I also have a pipeline setup that builds the binaries using Cross. I haven't done as good a job at keeping up to date with releases, but the pipeline and artifacts are here: https://gitlab.com/npappas/prisma-engines/pipelines

**Comment by Chaphasilor** [comment]
Any updates on this? I managed to compile the binaries myself, but I'm having a hard time integrating them into another project that uses Prisma internally...

**Comment by jcmcneal** [comment]
I'd also like to show my support for this request. I'm trying to deploy on the RPI4 (arm64) and it's a real blocker. Any prisma command results in this error.

```
Prisma Schema loaded from db/schema.prisma
Error: Get config Error: Command failed with Unknown system error -8: /app/node_modules/@prisma/cli/query-engine-linux-musl cli get-config
```

Thanks!

**Comment by radicand** [comment]
To add another voice of support: I've had a difficult time since 2.8 compiling the binaries - I have not yet been successful on arm64 since then. I'm still trying, but have been getting errors at the linker stage. It'd would be great it they just came out of the box.

**Comment by jcmcneal** [comment]
@radicand I was able to successfully compile the binaries on my RPI4 this morning. I created a docker image of it and made it accessible to copy the binaries straight from it, rather than rebuilding all the time (it took an hour to compile). Here's a repo documenting how you can use it.

https://github.com/jcmcneal/prisma-arm64

Let me know if you have any luck with it!

**Comment by dutzi** [comment]
Hey @jcmcneal, thanks for the detailed solution!
I'm trying to run the Dockerfile on my RPI4, but I get the following error:

```
dpkg: error processing archive direnv.deb (--install):
 package architecture (arm64) does not match system (armhf)
Errors were encountered while processing:
 direnv.deb
```

I have a 32 bit Raspebian Lite installed, is that the issue?

**Comment by jcmcneal** [comment]
@dutzi That makes sense. I'm running 64bit Ubuntu 20 and dotenv would not install via `apt-get`. If you get that to build successfully then I can add you as a collaborator on docker hub and you can push up the build for arm32.

**Comment by dutzi** [comment]
I'm not too familiar with Docker but I don't mind trying, I'm @dutzi at docker hub.

**Comment by dutzi** [comment]
Well, I got it built, and I changed `node_modules/@prisma/cli/build/index.js` by hand, to quickly fix the missing `arm-openssl-1.1.x`, but now when I run `npx prisma generate`, I get the following error message:

Environment variables loaded from current directory
Warning Precompiled binaries are not available for arm.
Prisma Schema loaded from schema.prisma
Warning Precompiled binaries are not available for arm.
Warning Precompiled binaries are not available for arm.
Error:
TypeError: mappings.filter is not a function
    at getMappings (/home/dutzi/repos/project-wi/node_modules/@prisma/client/generator-build/index.js:9716:19)
    at externalToInternalDmmf (/home/dutzi/repos/project-wi/node_modules/@prisma/client/generator-build/index.js:9712:15)
    at getPrismaClientDMMF (/home/dutzi/repos/project-wi/node_modules/@prisma/client/generator-build/index.js:9740:10)
    at buildClient (/home/dutzi/repos/project-wi/node_modules/@prisma/client/generator-build/index.js:11337:21)
    at generateClient (/home/dutzi/repos/project-wi/node_modules/@prisma/client/generator-build/index.js:11393:45)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)```

**Comment by jcmcneal** [comment]
I'm running `generate` on my RPI4 just fine, but maybe because it's arm64 OS. If you run `prisma -v` does it point to your custom binaries? I don't have to do anything other than put the `.env` file next to my schema file.

**Comment by dutzi** [comment]
Hey, sorry, I gave up on Raspebian, it was too much a headache... I just installed Ubuntu Server 64. 🤷‍♂️

**Comment by dutzi** [comment]
Regarding your question, I did put the .env file inside the folder where the schema file was. It ran for sure, but wasn't happy with the setup.

**Comment by jcmcneal** [comment]
Sweet, hopefully you see better performance on 64 bit Ubuntu. Yeah, I tried doing some cross compiling of prisma for arm32 and it was also a headache. We ought to just leave that to the prisma team but I doubt they'll support it anytime soon. For now I'll just leave my repo as is for anyone who wants to use it and get back to developing my website 😄

**Comment by radicand** [comment]
> @radicand I was able to successfully compile the binaries on my RPI4 this morning. I created a docker image of it and made it accessible to copy the binaries straight from it, rather than rebuilding all the time (it took an hour to compile). Here's a repo documenting how you can use it.
> 
> https://github.com/jcmcneal/prisma-arm64
> 
> Let me know if you have any luck with it!

Thanks - I specifically build for Alpine, and I suspect if I was using glibc it'd be working given your success with no hackarounds. I'll keep trying and see if I can determine what the issue is.

**Comment by BaptisteLongy** [comment]
Hello there,

I'm encountering the issue described [here](https://github.com/prisma/prisma/issues/1505#issuecomment-633802109).

I understand that you are not going to officially support arm platforms yourselves and that [you just give instructions on how we can do it ourselves](https://github.com/prisma/prisma/issues/861#issuecomment-690574582).

However it seems you are blocking (probably not on purpose) any execution on non supported platforms and the workaround is to [simply add the name of the platform to a list (or 2)](https://github.com/prisma/prisma/issues/1505#issuecomment-634154657).

Could you lift that restriction when using custom binaries so we don't have to fork the entire prisma in this situation?

If needed, I can create a new issue to track this, just tell me 😃

**Comment by janpio** [comment]
New issues sounds like a good idea @BaptisteLongy - maybe also add a suggestion on how you would achieve that from a user perspective (env var?).

**Comment by MichalLytek** [comment]
Will ARM be supported now as we have Apple M1 CPUs on dev machines? 🤔

**Comment by pantharshit00** [comment]
@MichalLytek Right now you can use Prisma on M1 Macs via Rosetta. We haven't added the native compilation for Apple ARM targets to the pipeline yet.

**Comment by gregkonush** [comment]
I could not find a good guide on how to compile my own binaries with steps for arm64, preferably some copy-paste commands 😄 . I have a use case where I tried to use Prisma on the AWS graviton processors and it fails to do any of the CLI commands because it looks for binary.

**Comment by jcmcneal** [comment]
@gregkonush You should be able to use my Dockerfile to generate the binaries for arm64. FYI, you also have to rebuild anytime you update the prisma client in your app. It's quite annoying so I ditched my RPI4 for a cheap intel mini pc.

https://github.com/jcmcneal/prisma-arm64

**Comment by radicand** [comment]
I don't believe this issue got updated, but in 2.14.0, the Prisma team released Linux ARM64 binaries natively: https://github.com/prisma/prisma/releases/tag/2.14.0 - in the release notes.

**Comment by matthewmueller** [comment]
Yep as @radicand mentioned, Linux ARM support is available in `2.14.0`.

We don't yet support Mac ARM. We'll track that in https://github.com/prisma/prisma/issues/5245

**Comment by Xample** [comment]
Hi, just to mention I also have building problems, I proudly build my backend using prisma within a docker.

My Dockerfile looks like this

```
FROM node:15.12.0-buster-slim AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run prisma:client:gen
RUN npm run build
```
Because the client is built into the `nodes_module` and that one to be excluded from docker, I generate the files at the docker build time. BUT… I get the following error
``` 
Error: Unknown binaryTarget linux-arm-openssl-undefined and no custom binaries were provided
```
ha… okay I am using a mac mini m1, which mean the dockerized linux seems to be recognized as an arm ?!?

adding the following line to schema.prisma
```prisma
binaryTargets = ["linux-arm-openssl-1.1.x"]
```
did not help neither. By the way, my cloud is running x86, it's probably a bad idea to build dockers images on a m1 for now.

I am not the only one to try the impossible, however a guy did it successfully:
https://medium.com/swlh/building-x86-64-docker-containers-on-apple-silicon-a6d868a18f37

What should the prisma team do ? Provide a kind of universal `query-engine` ? Or rewrite the query engine in AssemblyScript ? ;-)

**Comment by Xample** [comment]
Another guy is having the same problem:
https://stackoverflow.com/questions/66530969/docker-compose-up-issue-using-docker-apple-m1

Do anyone knows if this is fixable yet ?

**Comment by janpio** [comment]
If your questions are about M1 support @Xample, you should post in https://github.com/prisma/prisma/issues/5245 instead of this closed issue. Those tend to be ignored.

**Comment by Xample** [comment]
well, actually node:15 is a multi arch image, it therefore builds and runs under linux-arm, to fix this I need to use [docker buildx](https://docs.docker.com/buildx/working-with-buildx/) and force using x86

**Comment by pantharshit00** [comment]
2.14 only added 64 bit binaries for ARM. I believe your Pi is running a 32bit OS. Please follow: https://github.com/prisma/prisma/issues/5379

**Comment by gespispace** [comment]
@Rem0ld you use node alpine? if i move on FROM node:16 all work

**Comment by Rem0ld** [comment]
> @Rem0ld you use node alpine? if i move on FROM node:16 all work

No finally I installed Ubuntu 20.04, and with this system there is no problem. And for my usage it's completely fine.

**Comment by mcihadkurel** [comment]
> Hi, just to mention I also have building problems, I proudly build my backend using prisma within a docker.
> 
> My Dockerfile looks like this
> 
> ```
> FROM node:15.12.0-buster-slim AS builder
> WORKDIR /app
> COPY . .
> RUN npm install
> RUN npm run prisma:client:gen
> RUN npm run build
> ```
> 
> Because the client is built into the `nodes_module` and that one to be excluded from docker, I generate the files at the docker build time. BUT… I get the following error
> 
> ```
> Error: Unknown binaryTarget linux-arm-openssl-undefined and no custom binaries were provided
> ```
> 
> ha… okay I am using a mac mini m1, which mean the dockerized linux seems to be recognized as an arm ?!?
> 
> adding the following line to schema.prisma
> 
> ```prisma
> binaryTargets = ["linux-arm-openssl-1.1.x"]
> ```
> 
> did not help neither. By the way, my cloud is running x86, it's probably a bad idea to build dockers images on a m1 for now.
> 
> I am not the only one to try the impossible, however a guy did it successfully:
> https://medium.com/swlh/building-x86-64-docker-containers-on-apple-silicon-a6d868a18f37
> 
> What should the prisma team do ? Provide a kind of universal `query-engine` ? Or rewrite the query engine in AssemblyScript ? ;-)

Did you fix this?

**Comment by Xample** [comment]
I am building it on m1, deploy it on X86 using the builx build command. Here is my script (where of course the DOCKER_IMAGE_NAME is an environment variable holding the build name)

sh```
echo "Building Docker image '${DOCKER_IMAGE_NAME}'"
# we target linux/amd64 to prevent the default arm64 to be taken on mac os
# buildx is an experimental feature (31/03/2021) and must be manually enabled.
# https://docs.docker.com/engine/reference/commandline/dockerd/
# here is a possible docker configuration file
# {
#   "debug": true,
#   "experimental": true
# }

docker buildx build --platform linux/amd64 --push -t ${DOCKER_IMAGE_NAME} .
```

**Comment by mericano1** [comment]
FYI - I also ran into this issue even though the architecture on which I build images is the same as the one I ran them (ARM64). I eventually managed to get it running by using the env variables pointing to the right binaries. 

Also see [this](https://github.com/prisma/prisma/issues/8310)

**Comment by Pkmmte** [comment]
I, too, ran into this issue when trying to build an `arm64` Docker image with `node-alpine` as the base.

In the end, I was able to solve it by installing openssl via my Dockerfile before running `prisma generate` and specifying `binaryTargets = ["native", "linux-arm-openssl-1.1.x"]` inside my `schema.prisma`. Also had to switch from alpine to slim to use apt install.

Here's my simple Dockerfile:

```
FROM node:16-slim

RUN apt-get update
RUN apt-get install -y openssl

WORKDIR /usr/src/app

COPY package.json ./
COPY *.lock ./
RUN yarn install

COPY . .

RUN yarn run build

EXPOSE 8080

CMD [ "yarn", "start" ]
```

In this example, by `build` command calls `prisma generate` which was erroring out before.

**Comment by yss14** [comment]
@Pkmmte Thanks! For me it worked by just switching to `node:14-slim` and installing openssl. No need to specify `binaryTargets` in the prisma schema.

**Comment by miclill** [comment]
In my particular case (raspberry pi 4) I needed to modify `/boot/config.txt`:
`arm_64bit=1`, reboot, wait.

`uname -a` to ensure we are running 64-bit.

Then use docker  image `arm64v8/node:lts-slim`

**Comment by mericano1** [comment]
> @Pkmmte Thanks! For me it worked by just switching to `node:14-slim` and installing openssl. No need to specify `binaryTargets` in the prisma schema.

yes, make sure you install openssl if using the slim images. I experienced this problem again cause I was missing openssl

**Comment by abernier** [comment]
My feedback on mac m1 arm64.

I managed to `prisma generate` with `node:slim` + `openssl`.
But it failed once running `prisma migrate deploy`:
```
Unknown binaryTarget linux-arm64-openssl-undefined and no custom binaries were provided
```

👉🏻 My solution was to add `--platform=linux/amd64` in my `Dockerfile`:
```
FROM --platform=linux/amd64 node:16-alpine
```

Really slower, but at least working 🤷‍♂️

**Comment by baptisteArno** [comment]
> My feedback on mac m1 arm64.
> 
> I managed to `prisma generate` with `node:slim` + `openssl`. But it failed once running `prisma migrate deploy`:
> 
> ```
> Unknown binaryTarget linux-arm64-openssl-undefined and no custom binaries were provided
> ```
> 
> 👉🏻 My solution was to add `--platform=linux/amd64` in my `Dockerfile`:
> 
> ```
> FROM --platform=linux/amd64 node:16-alpine
> ```
> 
> Really slower, but at least working 🤷‍♂️

Same here... But adding `--platform=linux/amd64` makes it really slow and for some reason it crashes at some point 😢

**Comment by janpio** [comment]
Please make sure there are standalone issues for things we do not support right now. Thanks.

**Comment by ianlancaster** [comment]
I too was getting the `Unknown binaryTarget linux-arm64-openssl-undefined and no custom binaries were provided
` error when trying to run prisma in docker alpline on an M1 machine. The suggestion below worked for me:

https://github.com/prisma/prisma/issues/12417#issuecomment-1074733176

**Comment by noorvir** [comment]
@abernier's link does work and I've been using it for a few months, however, the resulting build while installing dependencies with `yarn dev` takes *very* long. I expect it's because docker has to do `qemu` emulation for the underlying architecture. I see my image build time balloon from 35 seconds on ARM (which fails on running the container) to 300 seconds with the `--platform=linux/amd64` option.

Is there any upcoming fix for running on a `linux/arm64` machine in docker

**Comment by janpio** [comment]
If there is not not-closed issue for it, it is definitely not on our radar. Check the `arm` label issues maybe as a start: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+arm%22+sort%3Aupdated-desc

**Comment by AndrewSouthpaw** [comment]
For me, the error about `-undefined` went away when switching from

```
FROM node:14.17.6-bullseye-slim # didn't work
FROM node:14.17.6 # worked
```

**Comment by younes-alouani** [comment]
I have the same problem using Prisma on AWS ARM PROCESSORS with Docker. 

`RUN npx prisma generate`

Results in an error ! 

`Unknown binaryTarget linux-arm64-openssl-undefined and no custom engine files were provided`
`The command '/bin/sh -c npx prisma generate' returned a non-zero code: 1`

**Comment by janpio** [comment]
How can we minimally reproduce this @younes-alouani?

**Comment by jcampbell05** [comment]
@janpio  I've recreated it with the following minimal setup.

Dockerfile

```
ARG FUNCTION_DIR="/var/task"
FROM node:16-slim

# Include global arg in this stage of the build
ARG FUNCTION_DIR

WORKDIR ${FUNCTION_DIR}
COPY . ${FUNCTION_DIR}

RUN yarn add prisma
RUN yarn prisma generate
```

prisma.schema
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["rhel-openssl-1.0.x", "linux-arm64-openssl-1.0.x"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
   objectID  String   @id @default(auto()) @map("_id") @db.ObjectId
}
```

docker-compose.yml
```
version: "3.9"
services:
  api:
    build: .
    volumes:
      - ./:/var/task
```

When running `docker compose build` you should get this error

```
Error: Unknown binaryTarget linux-arm64-openssl-undefined and no custom engine files were provided                               
#0 1.446 error Command failed with exit code 1.
```

**Comment by janpio** [comment]
Moved this into https://github.com/prisma/prisma/issues/16232
