### ISSUE TITLE
Generated index.d.ts has > 100k lines and IDE Intellisense is not working

### ISSUE THREAD

**Issue by programmatix** [prisma/prisma#8624]
## Problem

Using prisma 2.20.0.

My database has around 50 tables, with one of them having nearly 1,000 columns.  Prisma generates a single index.d.ts which is over 100k lines lone.  My IDE (IntelliJ 2020.3) seems to struggle with this.  Intellisense rarely works, significantly limiting the utility of Prisma.  Just opening the file takes significant time.  With smaller databases, everything is fine.

## Suggested solution

I am not sure if the problem for IntelliJ is the sheer amount of output (100k lines), or that it's in a single file.  There isn't anything n the IDE logs to help.  Since in other contexts IntelliJ is perfectly happy with large Typescript projects, I suspect it's the single file causing issues.  If Prisma could output into multiple files, and then import them all from index.d.ts, that will likely fix this.  And also make for more readable generated source.

## Alternatives

I could probably write a script that would do this, but it seems useful to have it in Prisma core.

**Comment by cheaprYang** [comment]
me to

**Comment by pantharshit00** [comment]
Closing in favor of https://github.com/prisma/prisma/issues/4807
