### ISSUE TITLE
Go like tags for Prisma schema

### ISSUE THREAD

**Issue by bene** [prisma/prisma#8642]
## Problem

In multiple projects now I have encountered the same problem. First you define your Prisma schema, which perfectly describes the structure of the app's data. Then you add GraphQL to create an API and [JSON Schema](https://json-schema.org/) to validate inputs and create an UI. And although Prisma generators provides a great way to generate other things out of the Prisma schema, I always end up adding some messy code to modify the generated output; e.g. to exclude fields from the API or add validation data to the JSON schema.

## Suggested solution

To solve this I would really like to be able to add tags to the Prisma schema. I think Go does a good job at this and could act as a paragon. In the following example, the tag on the `password` field tells my `API generator` to remove the field. The tag on the `name` field tells my `validator generator` that the minimum length is three and the maximum 12.

```
model User {
  id       Int     @id @default(autoincrement())
  email    String  @unique
  password String                                `api="-"`
  name     String?                               `validation="minLength=3,maxLength=12"`
  bio String?                                    `api="omitempty"`
}
```

This is just one small example, but I think tags could be handy in so many use cases and would allow the Prisma schema to become the single source of truth, out of which you generate many other things - GraphQL schema, JSON Schema and even whole UIs.

**Comment by janpio** [comment]
I think we have been mostly talking about this under the term "custom attributes" until now: https://github.com/prisma/prisma/issues/4002

**Comment by bene** [comment]
Sorry, my mistake! I missed this one while looking for similar suggestions. I'll add my thought there.
