### ISSUE TITLE
Query engine binary for "debian-openssl-1.1.x" could not be found, already added engine to prisma schema

### ISSUE THREAD

**Issue by Siah-All** [prisma/prisma#8648]
### Bug description

I use github workflows to generate packages with software.
Github workflows works on linux:ubuntu and package docker images on node:15.
According to the instructions in the schema.prisma file, I have added line
`generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}`

after regenerating packages i have issue:
```
 error [N/A] Query engine binary for current platform "debian-openssl-1.1.x" could not be found.
 This probably happens, because you built Prisma Client on a different platform.
 (Prisma Client looked in "/app/query-engine-debian-openssl-1.1.x")

 Searched Locations:

   /.prisma/client
   /__w/shop-managment-tools/shop-managment-tools/node_modules/@prisma/client
   /
   /app
   /app
   /tmp/prisma-engines
   /app

You already added the platforms "debian-openssl-1.1.x", "debian-openssl-1.1.x" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new
```

tested on versions prisma: 2.28, 2.21.2

### How to reproduce

Create schema.prisma with 
 `binaryTargets = ["native", "debian-openssl-1.1.x"]`
generate client on ubuntu
build docker image with node:15 (debian-openssl-1.1.x)
copy node_modules to image
try conection to database from inside docker image

### Expected behavior

working prisma client

### Prisma information

```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "mysql"
  url      = env("MYSQL_ROOT_URL")
}

enum ProductStatus {
  IN_STOCK
  ON_SALE
  OUT_OF_STOCK
  ARCHIVED
}
```

### Environment & setup

- OS: Linux   Ubuntu 20.04.2 LTS --> github workflows
- Database: MariaDB:10.6
- Node.js version: node:15 --> docker image

### Prisma Version

```
$ yarn prisma -v
yarn run v1.22.10
$ /home/siah-all/Repos/Bushido-Games/shop-managment-tools/node_modules/.bin/prisma -v
prisma               : 2.28.0
@prisma/client       : 2.28.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 89facabd0366f63911d089156a7a70125bfbcd27
Studio               : 0.417.0
Done in 1.85s.
```

**Comment by pantharshit00** [comment]
Hello,

Can you please share the contents of the docker image?

**Comment by Siah-All** [comment]
I just figured out this bug. The docker container actually does not have binaries, and I fixed this error by manually copying the file "node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x" to my `/app/` directory. 
github/workflow builds several docker images from different scopes, so I have to force copying binaries to each package before building or give the builder to evry Dockerfile.
