### ISSUE TITLE
Fix name of arm64 platform from `linux-arm` to `linux-arm64`

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#8653]
### Bug description

We have wrongly named our 64 bit arm platform for linux as `linux-arm` instead of `linux-arm64` (please note that Mac arm64 name is correct `darwin-arm64`)

This has caused bugs around detection of 32 bit ARM devices and it lead to https://github.com/prisma/prisma/issues/8575

This can also cause other confusion down the road.

### How to reproduce

See https://github.com/prisma/engines-wrapper/blob/e0f2a284b4f6bc8ca225d6e2cf044e7d86e671b3/packages/get-platform/src/getPlatform.ts#L201-L203

### Expected behavior

arm64 target should be called `linux-arm64`. Also, please note while fixing this, add `linux-arm` (32 bit arm) to known but ignored platforms.

**Comment by janpio** [comment]
Related code:
https://github.com/prisma/engines-wrapper/search?q=arm
https://github.com/prisma/engineer/search?q=arm
https://github.com/prisma/engine-images/search?q=arm

**Comment by pantharshit00** [comment]
This was done in `3.1.0-dev.12`
