### ISSUE TITLE
db seeds not being generated using named function, sqlite, nextjs

### ISSUE THREAD

**Issue by AlexKMarshall** [prisma/prisma#8685]
I've tried to set up a seeding file per the instructions on https://www.prisma.io/docs/guides/database/seed-database

My seed is exporting a named `seed` function. When I run it, the CLI says that the script runs ok, but the seed function is not getting called.

I have a minimal reproduction at https://github.com/AlexKMarshall/next-prisma-starter/tree/prisma-seeds on the `prisma-seeds` branch

**Comment by Jolg42** [comment]
Maybe try to use the "script" approach as a workaround?

**Comment by Jolg42** [comment]
🗒️ We are planning a redesign of `db seed` (currently planned to be released early September)

How it will work is that a `prisma.seed` property in the package.json of your project will be required if you want to use `prisma db seed`.

This property is where you will be able to put any command you want to execute your seed script.

More info/details & how to try it out now in:
https://github.com/prisma/prisma/issues/8732

**Comment by janpio** [comment]
The redesign of `db seed` was released with Prisma 3. Please try it, this problem should be gone.
