### ISSUE TITLE
Using UpdateMany or ExecuteRaw to update column using an array on id column

### ISSUE THREAD

**Issue by paulm17** [prisma/prisma#8686]
### Bug description

Firstly many thanks for resolving the binary issue for 2.29.0! 💯 

I'm having an issue where I'm trying to update a column using an array for the id.

I'm trying to achieve this in 1 of two ways:

1) UpdateMany

```
const query = db.damFile.updateMany({
        data: {
          deletedAt: DateTime.utc().toString(),
        },
        where: {
          id: {
            in: VALUE,
          },
        },
      })
```

For value, I have tried:

- ids
- [ids]
- Prisma.join(ids)

I'm getting a variation of this typescript error:

```
Type '{ in: Buffer[][]; }' is not assignable to type 'Buffer | BytesFilter | undefined'.
  Object literal may only specify known properties, and 'in' does not exist in type 'Buffer | BytesFilter'.ts(2322)
(property) in: Buffer[][]
```

No problem I think, I'll try the executeRaw route.

2) ExecuteRaw

```
const query = db.$executeRaw(
	`
		update DamFile
		set deletedAt = ?
		where id in (?)
	`,
	DateTime.utc().toString(),
	Prisma.join(VALUE)
)

const result = await db.$transaction([query])
```

For value, I have tried:

- ids.join(",")
- Prisma.join(ids)

Note I was told by Ryan in Slack to use Prisma.join for both examples, although I'm not sure if it's correct.

I have also tried:

```
const query = db.$executeRaw`
   update DamFile
   set deletedAt = ${DateTime.utc().toString()}
   where id in (${ids.join(",")})
`
```

Finally, here is the output for the executeRaw queries:

```
[ 0 ]
```

No matter what I try, I keep on getting 0 changed rows.

Let me know if you need any additional information.  Or if I am doing anything wrong, appreciate any corrections.

### How to reproduce

Here is some data you can try:

01FB6VB2G907FMJ91P88VXGA4S
01FB6VB4XWA2YKJWVZ7KADQF56
01FB6VB6W349W5SHTNSE39674X
01FB6VB95R8QB2SXAX87GVC7KY
01FB6VBAYKAYG0Y80DKJ4SQXQN

### Expected behavior

Expect to see a number higher than 0 for changed rows and the database updated.

### Prisma information

```
model DamFile {
   id                Bytes     @id @db.Binary(26)
   deletedAt         DateTime?
}
```

### Environment & setup

- OS: OSX Mavericks
- Database: mysql  Ver 15.1 Distrib 10.5.11-MariaDB, for osx10.14 (x86_64) using readline 5.1 
- Node.js version: v14.15.4

### Prisma Version

```
Environment variables loaded from .env
prisma               : 2.29.0
@prisma/client       : 2.29.0
Current platform     : darwin
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
```

**Comment by pantharshit00** [comment]
Hello @paulm17 

I was able to perform this using the following: 
```ts
  const query = await prisma.$executeRaw`
		update DamFile
		set deletedAt = ${new Date()}
		where id in (${Prisma.join([
      "01FB6VB2G907FMJ91P88VXGA4S",
      "01FB6VB4XWA2YKJWVZ7KADQF56",
    ])})
	`;
```

The above is safe from sql inject as the query generated is the following:
```sql
Query: update DamFile
                set deletedAt = ?
                where id in (?,?)
Params:         [2021-08-17 14:28:54.444 UTC,"01FB6VB2G907FMJ91P88VXGA4S","01FB6VB4XWA2YKJWVZ7KADQF56"]
```


The raw query helpers are based on https://github.com/blakeembrey/sql-template-tag where you can refer to its usage. Let me know if the above works for you. 


Also, I think having `in` natively for `Bytes` is a valid feature request. If you have some time, please also open a new feature request pasting the above sample.

**Comment by paulm17** [comment]
Ah.  Seems, I wasn't thorough enough.  😄 

I can confirm the following works:

```
        const query = db.$executeRaw`
        update DamFile
        set deletedAt = ${DateTime.utc().toString()}
        where id in (${Prisma.join(ids)})
      `
```

Although seems a bit weird why () does not work whereas `` does?  I will be cognisant of this next time.

Many thanks.

I will follow up with another issue with respect to bytes, as this is my preferred method.

**Comment by pantharshit00** [comment]
> Although seems a bit weird why () does not work whereas `` does? I will be cognisant of this next time.
That one doesn't work as it can't replace `?` single prepared varible with multiple `(?,?,?)`. Mostly a decision taken by that sql templating library.

**Comment by cholcool** [comment]
Why is it called updateMany when it can't be done?
