### ISSUE TITLE
`Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.` on AWS Amplify

### ISSUE THREAD

**Issue by MarleyDabb** [prisma/prisma#8690]
### Bug description

Hi, I'm getting the following error when deploying to AWS Amplify

`error: "Query engine binary for current platform "rhel-openssl-1.0.x" could not be found. This probably happens, because you built Prisma Client on a different platform. (Prisma Client looked in "/var/task/chunks/query-engine-rhel-openssl-1.0.x") Searched Locations: /.prisma/client /codebuild/output/src380855201/src/tentest/node_modules/@prisma/client /var/task /var/task/chunks /var/task/chunks /tmp/prisma-engines /var/task/chunks You already added the platform "rhel-openssl-1.0.x" to the "generator" block in the "schema.prisma" file as described in https://pris.ly/d/client-generator, but something went wrong. That's suboptimal. Please create an issue at https://github.com/prisma/prisma/issues/new"`

Here is what my schema looks like:

``` 
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["rhel-openssl-1.0.x", "native"]
}


model Post {
    id Int @id @default(autoincrement())
    title String
    body String
}
```

Need help

### Expected behavior

Show my API result

### Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["rhel-openssl-1.0.x", "native"]
}


model Post {
    id Int @id @default(autoincrement())
    title String
    body String
}
```

### Environment & setup

- OS: I'm on a mac, not sure what the OS is of the amplify server
- Database: PostGres
- Node.js version: 16.6.1

### Prisma Version

```
prisma               : 2.28.0
@prisma/client       : 2.29.0
Current platform     : darwin
Query Engine         : query-engine 89facabd0366f63911d089156a7a70125bfbcd27 (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 89facabd0366f63911d089156a7a70125bfbcd27 (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 89facabd0366f63911d089156a7a70125bfbcd27 (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 89facabd0366f63911d089156a7a70125bfbcd27 (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 89facabd0366f63911d089156a7a70125bfbcd27
Studio               : 0.417.0

```

**Comment by janpio** [comment]
Can you tell us a bit more about how you are deploying there?
How can we reproduce this? Assume we know very little about AWS Amplify.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this solved.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
