### ISSUE TITLE
sslmode=require without an sslcert=<path> won't enforce SSL mode

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#8697]
### Bug description

This popped up while chatting with the PlanetScale folks.

Right now if you add `sslmode=require` to your connection string, but don't specify a `sslcert=<path>`, we will allow non-SSL connections. 

This is confusing since you explicitly set `sslmode=require`. Perhaps `sslmode` defaults to `prefer` or `disabled`?

For example:

```
mysql://USER:PASSWORD@HOST:PORT/DATABASE?sslmode=require
```

### How to reproduce

1. Get a connection string for a database that supports SSL
2. Try connecting to it without providing an SSL certificate

	  ```sh
	  $ DATABASE_URL="mysql://user:pass@host:3306/prisma?sslmode=require" npx prisma db push
	  Environment variables loaded from .env
	  Prisma schema loaded from prisma/schema.prisma
	  Datasource "db": MySQL database "prisma" at "host:3306"
	  Error: undefined: Database error
	  Error querying the database: Server error: `ERROR HY000 (1105): unknown error: Code: UNAVAILABLE
	  server does not allow insecure connections, client must use SSL/TLS
	  ```

3. With a `sslcert=cert.pem`

	  ```sh
	  $ DATABASE_URL="mysql://user:pass@host:3306/prisma?sslmode=require&sslcert=/etc/ssl/cert.pem'"
	  npx prisma db push
	  Environment variables loaded from .env
	  Prisma schema loaded from prisma/schema.prisma
	  Datasource "db": MySQL database "prisma" at "host:3306"
	  
	  🚀  Your database is now in sync with your schema. Done in 2.49s
	  
	  ✔ Generated Prisma Client (2.25.0) to ./node_modules/@prisma/client in 498ms
	  ```

**Note:** For PlanetScale you can use `DATABASE_URL="mysql://user:pass@host:3306/prisma?sslmode=require&sslcert=/etc/ssl/cert.pem`, where `/etc/ssl/cert.pem` (e.g. on MacOS) refers to the system certificate store as their certificate is via Let's Encrypt.

**Note:** We can talk to PlanetScale to get a password to reproduce

### Expected behavior

A couple options:

1. We don't try to connect and throw an error saying that `sslmode=require` must include `sslcert=<path>`
2. We try to load the operating system's default certificate (some conte)

## Context

- [Internal discussion](https://prisma-company.slack.com/archives/C01CUJDJ7UN/p1628696494011900)

**Comment by janpio** [comment]
Note: Example connection string to test this with available in internal discussion, https://prisma-company.slack.com/archives/C01CUJDJ7UN/p1628773204021000?thread_ts=1628696494.011900&cid=C01CUJDJ7UN

**Comment by janpio** [comment]
Someone from PlanetScale played around with `mysql_async`, and observed this:

> So I did a little testing, and `mysql_async` provides really nice defaults for this when using it directly with no need to configure Root CAs etc.
> The `mysql_async::SslOpts::default()` object already returns what we need here. It enforces hostname validation and uses system roots (pretty much like how https works).
> ```
> #[tokio::main]
> async fn main() -> Result<(), mysql_async::Error> {
>     let url = "mysql://pqe0bj2i4h9u:pscale_pw_X@uxht6i2xcb2t.eu-west-2.psdb.cloud/test";
>     let builder = mysql_async::OptsBuilder::from_opts(mysql_async::Opts::from_url(url).unwrap());
>     let pool = mysql_async::Pool::new(builder.ssl_opts(mysql_async::SslOpts::default()));
>     let _conn = pool.get_conn().await?;
>     println!("Successfully connected to PlanetScale!");
>     Ok(())
> }
> ```

https://prisma-company.slack.com/archives/C01CUJDJ7UN/p1628762626020200?thread_ts=1628696494.011900&cid=C01CUJDJ7UN

**Comment by dbussink** [comment]
I have opened https://github.com/prisma/quaint/pull/312 which I think greatly improves the user experience here. It means the URL still needs `sslaccept=strict` (which I think should also be documented, I only found that flag looking at the code). 

Ideally I'd argue that `sslaccept=strict` should be the default mode for when SSL is enabled and that folks will have to opt into unsafe behavior explicitly, but I don't know how breaking that would be for the Prisma community and you all can probably better judge that.

**Comment by janpio** [comment]
Quick research update here: 
It looks like https://www.prisma.io/docs/concepts/database-connectors/mysql#configuring-an-ssl-connection is wrong, our MySQL connector currently does not even support a `sslmode` parameter at all but that is a PostgreSQL only thing (and how the broken documentation probably came to be). Will investigate a bit further and see what actually _does_ exist and how it works before making suggestions on how to proceed here.

**Comment by dbussink** [comment]
@janpio My PR also fixes honoring `sslmode` more like in the documentation, except that it removes `preferred` as an option since the from what I could find the underlying driver doesn't support that.

**Comment by janpio** [comment]
- The PlanetScale problem got "fixed" in context of https://github.com/prisma/prisma/issues/8843.
- There is no `sslmode` for MySQL, so the documentation was updated to not contain that any more.
