### ISSUE TITLE
MongoDB ConnectorError: `Command failed (IllegalOperation): This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.)`

### ISSUE THREAD

**Issue by 12ain** [prisma/prisma#8713]
### Bug description

When I use Prisma to connect to MongoDB, there seems to be a problem. My connection URL is `mongodb://localhost:27017/dao`, it works well in `2.26.0`. But after that version, like `2.27.0` or the latest version, It can't connect my mongodb. As the information indicates, i make URL like `mongodb://localhost:27017/dao?retryWrites=false`, It also like that. 

```
PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: 
Invalid `prisma.user.create()` invocation:

  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawError { code: "unknown", message: "Command failed (IllegalOperation): This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.)" } })
    at cb (/Users/rain/WhiteMatrix/demo/prisma/dist/runtime/index.js:35947:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/Users/rain/WhiteMatrix/demo/demo/demo.js:7:17) {
  clientVersion: '2.29.0'
}
```

### How to reproduce

1. Create schema
2. RUN `yarn prisma generate`
3. Run `node demo.js`

### Prisma information

```
datasource db {
  provider = "mongodb"
  url      = "mongodb://localhost:27017/dao?retryWrites=false"
}

generator client {
  provider        = "prisma-client-js"
  // MacOS Alpine Ubuntu18/Debian10+ Centos7+
  binaryTargets   = ["darwin", "linux-musl", "debian-openssl-1.1.x", "rhel-openssl-1.0.x"]
  previewFeatures = ["mongodb", "referentialActions"]
  output          = "./dist"
}

enum UserRole {
  Admin
  Member
}

model User {
  id       String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  username String   @unique
  passwd   String
  role     UserRole
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt
}
```

### Environment & setup

- OS: Mac OS
- Database: MongoDB 5
- Node.js version: v16.4.0

### Prisma Version

```
prisma               : 2.29.0
@prisma/client       : 2.29.0
Current platform     : darwin
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
Preview Features     : mongoDb, referentialActions
```

**Comment by pantharshit00** [comment]
Related to #8266 

You currently need a mongodb instance with replica set in order to use Prisma. You can use the free tier atlas cluster or the mongodb docker image.

**Comment by AlvaroBrasilia** [comment]
I fixed this issue inserting this in mongodb.config file:

````
replication:
  replSetName: rs0
```` 

aws ubuntu > /etc/mongodb.confic
MacOs > /usr/local/etc/mongod.conf 

Restart the mongodb service  :)

**Comment by Shigetorum635** [comment]
I am also experiencing this

**Comment by matthewmueller** [comment]
This is due to the replicaSet not being configured. We're working on docs for this and [a better error message](https://github.com/prisma/prisma/issues/8719), but for now either:

- Use a Free MongoDB Atlas instance
- Configure it locally: https://github.com/prisma/prisma/issues/11860#issuecomment-1044568777
- Use our Docker file: https://github.com/prisma/prisma/blob/main/docker/docker-compose.yml

**Comment by Jolg42** [comment]
Indeed, if you modified the `mongodb.config` file like @AlvaroBrasilia 

You then need to initiate the replica set with the additional commands:
- restart the service, `brew services restart mongodb-community` on macOS
- `mongo` opens a mongo shell
- `rs.initiate({_id: "rs0", members: [{_id: 0, host: "127.0.0.1:27017"}] })`
- optionally check on the status with `rs.status()`
- Enjoy!

**Comment by fatihmert** [comment]
> I fixed this issue inserting this in mongodb.config file:
> 
> ```
> replication:
>   replSetName: rs0
> ```
> 
> aws ubuntu > /etc/mongodb.config MacOs > /usr/local/etc/mongod.config
> 
> Restart the mongodb service :)

Windows path: `C:\Program Files\MongoDB\Server\<version>\bin`

And MongoDB Compass solution worked for me, https://dba.stackexchange.com/a/211626/248643
