### ISSUE TITLE
Interactive transactions not working with `$queryRaw` and `$executeRaw` in 2.29.0

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#8717]
### Bug description

The `transactionId` cannot get passed down from the proxied client to `$queryRaw` and `$executeRaw`'s custom promises.

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
2.29.0
```

**Comment by Jolg42** [comment]
Fix now available in the `2.29.1` patch just released a minute ago.
