### ISSUE TITLE
Calling `.catch()` or `.finally()` on a prisma client model query does not fire the request in 2.29.0

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#8718]
### Bug description

await `prisma.user.create({data: {email: 'test@test.io'}}).catch(() => {})` doesn't fire the request anymore in `2.29.0`

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
2.29.0
```

**Comment by PabloSzx** [comment]
is 2.29.1 going to be released with the fix of https://github.com/prisma/prisma/pull/8720?

**Comment by millsp** [comment]
Yes

**Comment by Jolg42** [comment]
Fix now available in the `2.29.1` patch just released a minute ago.
