### ISSUE TITLE
Better error message for MongoDB replica sets

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma#8719]
### Bug description

As per this discussion: https://github.com/prisma/prisma/discussions/8701 we need to have a better error message than `ConnectorError(ConnectorError { user_facing_error: None, kind: RawError` and possibly add the message that **the MongoDB server to be run as a replica set to be able to perform transactions, as opposed to standalone server**

Related SO answer: https://stackoverflow.com/questions/58589631

### How to reproduce

- Steps above

### Environment & setup

- OS: any
- Database: MongoDB
- Node.js version: any

### Prisma Version

2.29.0

**Comment by matthewmueller** [comment]
Thanks for this issue. This could be solved by #8266, but if we can't solve that issue, we should definitely improve the error message.

**Comment by matthewmueller** [comment]
This error is definitely misleading. We should make it clear that you need to have the replica set enabled.
