### ISSUE TITLE
[MySQL] Can't migrate m2m self-relation when relation name has an "-"

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma#8721]
## Overview

**Reproduced only on MySQL 5.7. Needs to be confirmed on other versions of MySQL**

Given this datamodel:

```prisma
model User {
  id        Int    @id @default(autoincrement())
  name      String
  followers User[] @relation(name: "approved-followers")
  following User[] @relation(name: "approved-followers")
}
```

Running the migration engine result in the following error:

```
Error querying the database: Server error: `ERROR 42S01 (1050): Table './prisma/_approved@002dfollowers' already exists'
```

It does work when the relation name doesn't include a "-".

## Expected behavior

I suppose we should either:
- Get this to work if possible
- Have an early datamodel validation that prevents the migration from running altogether if it can't work
- Improve the runtime error if none of the options above are possible

**Comment by tomhoule** [comment]
Can the issue be closed then?

**Comment by pimeys** [comment]
I'd say we fix it when we a user is complaining about it. Now we have @Weakky that can go around the restrictions...

It's also a super weird problem, and the fix should be sanitizing some of the names, that would with our current architecture leak to the other versions of MySQL too where it is not needed.

**Comment by tomhoule** [comment]
Note that we have both `name` and `map` arguments on `@@unique` now, so we have more room for fixing things if they are really broken.
