### ISSUE TITLE
table `tenderentry` does not exist in the current database: table names case problem

### ISSUE THREAD

**Issue by terion-name** [prisma/prisma#8722]
### Bug description

I use @prisma/client on it's own, in my applications, like an ORM, with my own migration system and all other stuff. Till 2.26.0 everything was fine. On 2.28.0 (skipped 2.27.0) all was broken: client now tries to query tables named in lowercase, not in case like models are named. E.g. :
```prisma
model TenderEntry {
  id String @id @default(cuid())  
}
```
previously requests like `prisma.tenderEntry.findFirst()` queried table name `TenderEntry`, now — `tenderentry`.

If this is a bug (what I hope it is) — please fix asap. 

If not — it is a HUGE breaking change that must be only in major version (besides WHY change this??) and there is even nothing about this in changelogs! You've broke all old apps at once or locked them to old client version without possibilty to upgrade client without rewriting migrations and changing tables!

### How to reproduce

create any studly cased model, e.g.:
```prisma
model TenderEntry {
  id String @id @default(cuid())  
}
```
and a table:
```sql
CREATE TABLE `TenderEntry` (
  `id` varchar(25) NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

run any query (e.g. `prisma.tenderEntry.findFirst()`) and see "table `tenderentry` does not exist in the current database"

### Expected behavior

query should run over `TenderEntry` table

### Prisma information

@prisma/client@2.28.0

### Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v14.13.1

### Prisma Version

```
n/a
```

**Comment by janpio** [comment]
This is definitely not a change we made in Prisma.

Can you share the full error message you are getting?

Are you running this on the same database server than the old version? There are MySQL configurations which cause problems like this, where table name casing is changed dynamically.

**Comment by terion-name** [comment]
@janpio 
```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.tenderEntry.deleteMany()` invocation:


  The table `tenderentry` does not exist in the current database.
    at cb (.../node_modules/@prisma/client/runtime/index.js:34800:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'P2021',
  clientVersion: '2.28.0',
  meta: { table: 'tenderentry' }
}
```

Yes, the exact same DB as old. 

After downgrading the client to 2.26.0 everything started to work again.

**Comment by janpio** [comment]
That is _weird_.

Can you please enable logging and debugging and post the full output you get when running that query?
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging/ + https://www.prisma.io/docs/concepts/components/prisma-client/debugging

**Comment by terion-name** [comment]
I'll try tomorrow. Already rolled back my framework so this will take time to return to that state

**Comment by terion-name** [comment]
@janpio the most weird thing that I've rolled back, after new install 2.29.0 kicked in, and with it everything worked fine.
set resolution to 2.27.0 — works
set resolution to 2.28.0 — works

Tried different combos and variants — no luck to reproduce.

Maybe this was a heisenbug during client generation that time... Strange :(

**Comment by janpio** [comment]
That makes me happy any confused at the same time.

I'll close this for now then, but as soon as you see something like this again (or anyone else!) please comment here again and we will reopen and happily investigate. Weiiiiird.
