### ISSUE TITLE
prisma init command override existing .gitignore

### ISSUE THREAD

**Issue by mittalyashu** [prisma/prisma#8734]
### Bug description

On running `npx prisma init` commmand inside an existing project, prisma overrides the content to add `.env`, although `.env` was added in `.gitignore`.

<img width="304" alt="CleanShot 2021-08-13 at 18 40 10@2x" src="https://user-images.githubusercontent.com/29014463/129362151-306a7c1f-4045-445e-b985-a7977a4c7606.png">

### How to reproduce

1. Scaffold a `.gitignore` file
2. Run `npx prisma init` command
3. See `.gitignore` file

### Expected behavior

It should not override/remove the existing content from `.gitignore` file.

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v16

### Prisma Version

```
v2.29.0
```

**Comment by janpio** [comment]
Thanks, we are aware and tracking over at https://github.com/prisma/prisma/issues/8496 - there is already a PR open so should be fixed with next minor version.
