### ISSUE TITLE
Error when using `nApi` preview feature flag: `Can't modify an already connected engine.`

### ISSUE THREAD

**Issue by mostafa7904** [prisma/prisma#8741]
### Bug description

Hi.
A while ago I made this [issue](https://github.com/prisma/prisma/issues/8225) about nApi. And because I couldn't use it, I removed nApi from my project. But I started using it again a couple of days ago.

Since I started using it again. I haven't had a problem with production and no errors like the issue above. But I started getting a new error in development on my own PC (windows 10).

Error: 
```bash
(node:5568) UnhandledPromiseRejectionWarning: 
Error: {
"is_panic":false,
"message":"Can't modify an already connected engine.",
"backtrace":"   0: napi_register_module_v1\n  
 1: napi_register_module_v1\n   2: napi_register_module_v1\n   3: <unknown>\n   4: <unknown>\n   5: <unknown>\n   6: <unknown>\n   7: <unknown>\n   8: <unknown>\n   9: napi_register_module_v1\n  10: napi_register_module_v1\n  11: napi_register_module_v1\n  12: napi_register_module_v1\n  13: napi_register_module_v1\n  14: napi_register_module_v1\n  15: napi_register_module_v1\n  16: napi_register_module_v1\n  17: napi_register_module_v1\n  18: napi_register_module_v1\n  19: napi_register_module_v1\n  20: BaseThreadInitThunk\n  21: RtlUserThreadStart\n"}
```

I use nodemon (v 2.0.9) with express (v 4.17.1). 

My main database is Postgress (which I use Prisma for), and redis with node-redis (v 3.1.2) which runs in a windows Ubuntu (WSL) terminal.

I use the integrated git bash for vscode as my main terminal (where I run nodemon).

### How to reproduce

1. open an express project that uses postgress Prisma and nApi
2. open git bash in vscode + ubuntu (WSL) terminal that runs redis with node-redis
3. run the project with nodemon
4. stop nodemon using CTRL+C
5. start it immediately after
6. see error

### Expected behavior

Connect to the already existing engine instead of throwing this error.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["selectRelationCount", "nApi"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

...

```

### Environment & setup

- OS: Windows 10 Pro version 21H1
- Database: PostgreSQL 13
- Node.js version 14.17.2
- Nodemon version 2.0.9
- Git bash version 2.32.0.2

### Prisma Version

```
prisma               : 2.29.0
@prisma/client       : 2.29.0
Current platform     : windows
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
Preview Features     : selectRelationCount, nApi
```

**Comment by pantharshit00** [comment]
Hello

Can you share your nodemon config and a screenshot of the reproduction? I tried this multiple times but I wasn't able to reproduce this. 

Also, try this again with `2.29.1` once.

**Comment by janpio** [comment]
ping @mostafa7904 - we are pushing a bit here as we are planning to make Node-API the default engine in the next release, so understanding this would be highly valuable and important for us.

**Comment by janpio** [comment]
The error itself indeed comes from the Node-API Engine: https://github.com/prisma/prisma-engines/blob/5b5cbfdb08c2eae663b99e7c5acb12794ecadf3c/query-engine/query-engine-node-api/src/error.rs#L20-L21
https://github.com/prisma/prisma-engines/blob/36af3f44e00e1f6ae2ef08ebf105fb0120b43a66/query-engine/query-engine-node-api/src/engine.rs#L232

**Comment by pimeys** [comment]
Yep. Somebody is calling the `connect` method from the Rust engine more than once. You have to disconnect first to be able to reconnect. The error does nothing, it's just an indicator from the backend to not call `connect` anymore. It is safe to be just skipped, or maybe logging a warning if needed.

**Comment by mostafa7904** [comment]
Hi, sorry for the late response.
Well I'm still getting the same error.
The nodemon config is the default. I never changed it. 
I've also tried this in PowerShell and I'm getting the same error. That's all the info I have so far.
The Vue app that I have sends multiple requests at the same time, but the `$prisma.connect()` method is only called once when server is started.
```js
const startServer = async () => {
  try {
    await db.$connect();
    app.listen(port, () => {
      logger.info(`Server running in ${environment} mode on port ${port}`);
    });
  } catch (e) {
    logger.info("An error occurred while starting server.");
    logger.info(`Port: ${port}`);
    logger.info(`Env: ${environment}`);
    logger.info("Error: ");
    logger.error(error);
    throw e;
  } finally {
    await db.$disconnect();
  }
};
```
`startServer` method is only called once.
As I said this error isn't permanent. It goes away after a couple of restarts.

**Comment by mostafa7904** [comment]
This is the DB connection file.
```js

const { PrismaClient } = require("@prisma/client");

const url =  process.env.DATABASE_URL 
const prisma = new PrismaClient({
  datasources: {
    db: {
      url,
    },
  },
});

module.exports = prisma;
```

**Comment by pimeys** [comment]
Yeah, from our side this is our client calling the `connect` of the rust method more than once. The error though is not serious, it should be only an internal message for our TS side to not call the method more than once.

We should maybe in the TS side just try/catch this and never display it to the user.

**Comment by mostafa7904** [comment]
So there will never be fix for this? just a warning?
Or will there be fix in future?

**Comment by pimeys** [comment]
For sure at least we should not bubble that error up. I'd expect next release, which should be the GA for Node API to not show the error for the user.

**Comment by janpio** [comment]
@pimeys is talking about inner workings, where we also have a method called `connect`. Your code looks pretty fine really @mostafa7904.

Can you maybe create a small reproduction project with the minimal code required to trigger this error? Having some code and setup that we just need to download and run would make reproducing this much easier.

**Comment by mostafa7904** [comment]
I'm not really able to make a reproduction now. It might take a while since I'm busy on a project. I'm saying this cause you seemed to be in a rush to get this in the next version.

**Comment by janpio** [comment]
That's fine, thanks for letting us know. We will see if we can get this fixed (or worked around).
