### ISSUE TITLE
Prisma Installation Fails On `npx prisma generate`

### ISSUE THREAD

**Issue by JotaStar** [prisma/prisma#8751]
### Bug description

Installing prisma for first time get the error:

`Error: ENOENT: no such file or directory, realpath 'D:\Source\CryptoSource\api\node_modules\@prisma\client'`

### How to reproduce

1. `npm install prisma --save-dev` => OK
2. `npx prisma init` => .env & schema.prisma OK
3. Edit `schema.prisma` y `.env` with my config
4. `npx prisma migrate dev --name init` => 
    - Create folder for migrations and migration => OK
    - DB created without error. => OK
    - Installing @prisma/client => OK, but the last message: 
    
`    Error: ENOENT: no such file or directory, realpath 'D:\Source\CryptoSource\api\node_modules\@prisma\client'`

`npx prisma generate` => Same error

App fail with message:

```
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
```

### Expected behavior

Successful Installation

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model pair {
  pairAddress String @db.VarChar(255)
  token0      String @db.VarChar(255)
  token1      String @db.VarChar(255)

  @@id([pairAddress, token0, token1])
}

model token {
  address  String  @db.VarChar(255)
  chainId  String  @db.VarChar(255)
  decimals Int?
  symbol   String? @db.VarChar(255)
  name     String? @db.VarChar(255)

  @@id([address, chainId])
}

model user {
  id             Int     @id @default(autoincrement())
  email          String  @unique @db.VarChar(255)
  emailConfirmed Int     @default(0) @db.TinyInt
  phoneNumber    String? @db.VarChar(255)
  token          String? @db.VarChar(255)
  password       String  @db.VarChar(255)
  image          String? @db.VarChar(255)
  privateKey     String? @db.VarChar(255)
}
```

### Environment & setup

OS: Win 10
Node.js: v14.17.0
Nestjs: 8.0.0 (7.6.0 tested too)

### Prisma Version

```
prisma: 2.29.1
@prisma/client: 2.29.1

npm prisma -v
6.14.9
```

**Comment by janpio** [comment]
What does your `package.json` file look like? Does it list both Prisma dependencies?
Does it help to delete `node_modules` folder and run `npm install` anew?

**Comment by mudassir912** [comment]
@JotaStar I got same error but after installation of Microsoft Visual C++ Redistributable my error was resolved

**Comment by janpio** [comment]
Thanks for the issue, but we could never reproduce this. 
As we don't have any idea what could have been going wrong here, I am closing this issue.

If someone still has this issue in the future, please open a new issue so we can take a look. Thanks!
