### ISSUE TITLE
Interactive Transaction not allowed by typescript

### ISSUE THREAD

**Issue by jessevdp** [prisma/prisma#8761]
### Bug description

The following (simple) usage of the interactive transaction (as documented [here](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions)) produces a nasty typescript error that I can not seem to get around. (My actual transaction contains more logic but I was able to reproduce the error this way.)

```ts
const p: Paragraph = await prisma.$transaction(async (prisma) => {
  return prisma.paragraph.create({ data: data });
});
```

```
Argument of type '(prisma: any) => Promise<any>' is not assignable to parameter of type 'PrismaPromise<any>[]'.
  Type '(prisma: any) => Promise<any>' is missing the following properties from type 'PrismaPromise<any>[]': pop, push, concat, join, and 27 more.ts(2345)
```

It seems to expect the simpler `$transaction` API:

```ts
const [posts, totalPosts] = await prisma.$transaction([
  prisma.post.findMany({ where: { title: { contains: 'prisma' } } }),
  prisma.post.count(),
])
```

### How to reproduce

Schema:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialActions"]
}

model Paragraph {
  id      String @id @default(uuid())
  content String
}
```

Code:

```ts
const p: Paragraph = await prisma.$transaction(async (prisma) => {
  return prisma.paragraph.create({ data: data });
});
```

### Expected behavior

Expected to behave as the [interactive transaction documentation](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions) describes.

### Prisma information

See 'how to reproduce'.

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v16.4.2
- Typescript version: 4.3.5

### Prisma Version

```
prisma               : 2.27.0
@prisma/client       : 2.27.0
Current platform     : darwin
Query Engine         : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : cdba6ec525e0213cce26f8e4bb23cf556d1479bb
Studio               : 0.410.0
```

**Comment by jessevdp** [comment]
Typescript config:

```json
{
  "compilerOptions": {
    "strict": true,
    "sourceMap": true,
    "target": "es2019",
    "module": "commonjs",
    "lib": [
      "esnext"
    ],
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
  }
}
```

**Comment by ryands17** [comment]
@jessevdp 👋 

Works fine for me:
![image](https://user-images.githubusercontent.com/19697099/129549857-7b7289fa-5b3d-4de0-a46c-45cd92446522.png)
![image](https://user-images.githubusercontent.com/19697099/129549875-d461d588-269d-4135-88c3-a5e5dbf7173d.png)

My `tsconfig.json`:

```json
{
  "compilerOptions": {
    "sourceMap": true,
    "module": "commonjs",
    "target": "ES2018",
    "outDir": "dist",
    "lib": [
      "esnext",
    ],
    "strict": true,
    "noImplicitAny": false,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "noUnusedParameters": false
  },
}
```

**Comment by mkreuzmayr** [comment]
@ryands17 What typescript version are you using?

In my NextJS project with typescript version 4.3.5 i can reproduce the error.

**Comment by ryands17** [comment]
You don't have it added to the `previewFeatures` in your schema which is why it's not working:
https://github.com/prisma/prisma/releases/tag/2.29.0

**Comment by pantharshit00** [comment]
Indeed, try again with the feature flag and run `prisma generate` after adding the flag. I am going to close this. 

If this is still a problem, comment and we will take another look.

**Comment by jessevdp** [comment]
Ah, it's a preview feature. I did not see this mentioned in the docs, perhaps an opportunity to improve them?

- https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions
- https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide/#interactive-transactions

Not specified in either of those places. I found both docs organically through Google.

The docs on referential actions—for example—do clearly specify that it is a preview feature, along with an explanation on how to enable it. https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions/

**Comment by pantharshit00** [comment]
Good catch! Opened: https://github.com/prisma/docs/issues/2162
