### ISSUE TITLE
Unable to run `prisma migrate` with both `microsoftSqlServer` and `referentialActions` preview features enabled

### ISSUE THREAD

**Issue by molebox** [prisma/prisma#8764]
### Bug description

Using SQL server (preview) as my database, i create a model with a self relation. This gives me the expected error that i have cyclic relations. To fix this i enable the referential actions preview feature and add `onDelete: NoAction, onUpdate: NoAction` to one of my relations. 

I then try and run an initial migration, but i get an error from sql server instead and am unable to do the migration.

```terminal
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve    

Migration name: 20210816094950_init

Database error code: 1785

Database error:
Introducing FOREIGN KEY constraint 'FK__Chicken__chickenId' on table 'Chicken' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.   
```

### How to reproduce

This repo and its read me have the steps to reproduce: https://github.com/molebox/cylic-ref-action-bug

### Expected behavior

I should be able to run a successful migration once the cyclic relations issue is fixed using referential actions

### Prisma information

```prisma

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["microsoftSqlServer", "referentialActions"]
}

model Chicken {
  id        Int      @id @default(autoincrement())
  cock      Chicken? @relation(name: "a_self_relation", onDelete: NoAction, onUpdate: NoAction)
  hen       Chicken? @relation(name: "a_self_relation", fields: [chickenId], references: [id])
  chickenId Int?
}
```

### Environment & setup

- OS: Windows 10
- Database: Microsoft SQL Server
- Node.js version: v14.15.1

### Prisma Version

```
prisma               : 2.29.1
@prisma/client       : Not found
Current platform     : windows
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
Preview Features     : microsoftSqlServer, referentialActions
```

**Comment by pantharshit00** [comment]
Thanks, I can reproduce this with 2.29.1

When you try to migrate the schema, it fails when the cycle detection error but it saves the migration to file system and to the `_prisma_migrations` table. 

After this when you run migrate again, you will get `New migrations cannot be applied before the error is recovered from`

![image](https://user-images.githubusercontent.com/22195362/129554278-d467aa64-d0e4-40a2-8a2c-f7206268e311.png)

**Comment by pimeys** [comment]
Will this still be an issue when referential actions are out from preview? Isn't this only an issue if you don't have `referentialActions` enabled in the data model when you create a migration?

**Comment by pimeys** [comment]
Ok, so the error here is in the model:

```prisma
model Chicken {
  id        Int      @id @default(autoincrement())
  cock      Chicken? @relation(name: "a_self_relation", onDelete: NoAction, onUpdate: NoAction)
  hen       Chicken? @relation(name: "a_self_relation", fields: [chickenId], references: [id])
  chickenId Int?
}
```

You cannot define the actions in any side of the relation, but only if the relation field is singular and it also defines `fields` and `references` in the `@relation` attribute. I added a validation to this to the PSL code, so you should get an error for the invalid definition in the future.

**Comment by pimeys** [comment]
Correct way to define this would be:

```prisma
model Chicken {
  id        Int      @id @default(autoincrement())
  cock      Chicken? @relation(name: "a_self_relation")
  hen       Chicken? @relation(name: "a_self_relation", fields: [chickenId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  chickenId Int?
}
```

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma-engines/pull/2168 adds an error like this below, nice!
```
Error parsing attribute "@relation": The relation field `cock` on Model `Chicken` must not specify the `onDelete` or `onUpdate` argument in the @relation attribute. You must only specify it on the opposite field `hen` on model `Chicken`.
```
