### ISSUE TITLE
Error: Get config: Error: Command failed with exit code 3221225781

### ISSUE THREAD

**Issue by dhatGuy** [prisma/prisma#8827]
### Bug description

Trying to run `npx prisma -v` returns error

`Error: Get config: Error: Command failed with exit code 3221225781: C:\Users\user\AppData\Roaming\npm\node_modules\prisma\query-engine-windows.exe cli get-config --ignoreEnvVarErrors`

### How to reproduce

1. `npx prisma -v`

fail message: 
```
Error: Get config: Error: Command failed with exit code 3221225781: C:\Users\user\AppData\Roaming\npm\node_modules\prisma\query-engine-windows.exe cli get-config --ignoreEnvVarErrors
```

### Expected behavior

Show prisma version

### Environment & setup

- OS: Windows 10
- Database: PostgreSQL
- Node.js version: v14.17.5

### Prisma Version

```
prisma: 2.29.1
@prisma/client: 2.29.1
```

**Comment by janpio** [comment]
Is this running on Windows directly or on Docker?

**Comment by dhatGuy** [comment]
Windows directly

**Comment by janpio** [comment]
Can not reproduce unfortunately:

```
C:\Users\Jan\Documents\throwaway\issue8827  (issue8827@1.0.0)
λ npx prisma -v
prisma               : 2.29.1
@prisma/client       : 2.29.1
Current platform     : windows
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0

C:\Users\Jan\Documents\throwaway\issue8827  (issue8827@1.0.0)
λ node -v
v14.17.5
```

**Comment by dhatGuy** [comment]
My pc was stolen few days ago, so I decided to borrow a friend's pc to complete what I was working on. I only installed node, vscode and git. I'm not sure if I'm meant to installed anything else.

**Comment by janpio** [comment]
I know you already tried https://github.com/prisma/prisma/issues/5597#issuecomment-777623817, and that it didn't help. There is another issue https://github.com/prisma/prisma/issues/6508 about the same error, but that also does not include very concrete steps to a solution - sorry.

**Comment by dhatGuy** [comment]
I have checked for Visual C++ Redistributable for Visual Studio 2015 before and even repaired it but still no luck. 

For now, I'll use the online vscode. Thanks

**Comment by dhatGuy** [comment]
I have been able to solve the problem. I uninstalled node and reinstalled it with this option this time.
![image](https://user-images.githubusercontent.com/51405947/130191440-5b3d2fa3-cc71-475f-a002-aa97aebaba40.png)

**Comment by janpio** [comment]
Nice, thanks for keeping us updated.

**Comment by ShinyCoconut** [comment]
Installing Visual C++ 2015 Redistributable solved here.
