### ISSUE TITLE
Bump Node.js requirement from to >=12.2 to >=12.6

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#8839]
It looks like the current Node-API requirement for Node.js is >=12.6 based on https://github.com/prisma/prisma/issues/7621

We should bump, especially since Node-API will be the default.

And let's update the docs as well.

**Comment by janpio** [comment]
We should see if Node-API makes our tests fail in any way before merging the requirement change. In theory e2e tests should cover this - and if not we should add tests for that.

**Comment by janpio** [comment]
PR at https://github.com/prisma/prisma/pull/9049
