### ISSUE TITLE
Error: P1001: Can't reach database server (PlanetScale)

### ISSUE THREAD

**Issue by abriginets** [prisma/prisma#8875]
### Bug description

Hello, I'm trying out Prisma with PlanetScale and it's not going so smooth because I'm getting the following error after typing `npx prisma migrate dev`:
```
  prisma:loadEnv project root found at /home/goodwin/flaut-nextjs/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /home/goodwin/flaut-nextjs/.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Created by Vercel CLI
[dotenv][DEBUG] did not match key and value when parsing line 19: 
Environment variables loaded from .env
  prisma:engines using Node API: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig Using Query Engine Binary at: /home/goodwin/flaut-nextjs/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +0ms
Datasource "db": MySQL database "flautru" at "g8oms8wlmppb.eu-west-2.psdb.cloud:3306"

  prisma:getDMMF Using Query Engine Binary at: /home/goodwin/flaut-nextjs/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +0ms
  prisma:getConfig Using Query Engine Binary at: /home/goodwin/flaut-nextjs/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +34ms
  prisma:getConfig Using Query Engine Binary at: /home/goodwin/flaut-nextjs/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +11ms
Error: Error: P1001: Can't reach database server at `g8oms8wlmppb.eu-west-2.psdb.cloud`:`3306`

Please make sure your database server is running at `g8oms8wlmppb.eu-west-2.psdb.cloud`:`3306`.
    at ensureDatabaseExists (/home/goodwin/flaut-nextjs/node_modules/prisma/build/index.js:63712:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async _MigrateDev.parse (/home/goodwin/flaut-nextjs/node_modules/prisma/build/index.js:65680:28)
    at async main (/home/goodwin/flaut-nextjs/node_modules/prisma/build/index.js:105366:18)
```

I've been able to establish successfull connection with both MySQL Workbench GUI for Windows and `mysql-client` for Linux (WSL2). The only thing that is failing is Prisma.

### How to reproduce

1. Create database via app.planetscale.com
2. Create new branch out of `main`
3. Copy both `main` and `dev` branch URLs to Vercel
4. Execute `vercel pull` to get env variables (so now prod URL points to `main` and shadow database URL points to `dev` branch)
5. Make schema changes to `schema.prisma`
6. Execute `npm prisma migrate dev`

### Prisma information

- 

### Environment & setup

- OS: Windows 10, WSL2
- Database: PlanetScale MySQL
- Node.js version: v12.22.1

### Prisma Version

```
prisma               : 2.29.1
@prisma/client       : 2.29.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
Preview Features     : planetScaleMode, nApi
```

**Comment by janpio** [comment]
Can Prisma connect to other databases?

**Comment by abriginets** [comment]
I don't think so. I just tried to swap `DATABASE_URL` and `SHADOW_DATABASE_URL` values and run migration command and it seems to be going further but ends up with the same error:
```
  prisma:migrateEngine:rpc starting migration engine with binary: /home/goodwin/flaut-nextjs/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"/home/goodwin/flaut-nextjs/prisma/migrations"}} +2ms
  prisma:migrateEngine:stderr {"timestamp":"2021-08-23T19:44:55.270662300+00:00","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"1be4cd60b89afa04b192acb1ef47758a39810f3a"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:rpc {
  prisma:migrateEngine:rpc   jsonrpc: '2.0',
  prisma:migrateEngine:rpc   error: {
  prisma:migrateEngine:rpc     code: 4466,
  prisma:migrateEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:migrateEngine:rpc     data: {
  prisma:migrateEngine:rpc       is_panic: false,
  prisma:migrateEngine:rpc       message: "Can't reach database server at `g8oms8wlmppb.eu-west-2.psdb.cloud`:`3306`\n" +
  prisma:migrateEngine:rpc         '\n' +
  prisma:migrateEngine:rpc         'Please make sure your database server is running at `g8oms8wlmppb.eu-west-2.psdb.cloud`:`3306`.',
  prisma:migrateEngine:rpc       meta: [Object],
  prisma:migrateEngine:rpc       error_code: 'P1001'
  prisma:migrateEngine:rpc     }
  prisma:migrateEngine:rpc   },
  prisma:migrateEngine:rpc   id: 1
  prisma:migrateEngine:rpc } +947ms
Error: Error: P1001

Can't reach database server at `g8oms8wlmppb.eu-west-2.psdb.cloud`:`3306`

Please make sure your database server is running at `g8oms8wlmppb.eu-west-2.psdb.cloud`:`3306`
```

**Comment by nwidynski** [comment]
Maybe related? - #8878

**Comment by janpio** [comment]
Are you copying the PlanetScale connection string from their web UI? What is the value of `sslcert`? Does that file exist in your WSL environment?

**Comment by abriginets** [comment]
Yes, I'm copying the URL from PlanetScale UI and `sslcert` value corresponds to `/etc/ssl/certs/ca-certificates.crt` which indeed exists in my WSL environment. That's for the `SHADOW_DATABASE_URL`. `DATABASE_URL` have a different value which corresponds to `/etc/pki/tls/certs/ca-bundle.crt` (according to PlanetScale documentation it's required for Vercel deployment), not sure if that's relevant to  the issue though.

**Comment by janpio** [comment]
`prisma migrate dev` run locally also uses `DATABASE_URL`, so it would have to be a value that exists on the local system. Unfortunately that means that you have to set a different value locally than for Vercel. (https://github.com/prisma/prisma/issues/8843 will improve on that soon hopefully)

**Comment by abriginets** [comment]
Yep, replacing `/etc/pki/tls/certs/ca-bundle.crt` with `/etc/ssl/certs/ca-certificates.crt` for local environment solved the issue. The solution for me at this point would be having four different URLs at Vercel environment variables list (two with `/etc/ssl/certs/ca-certificates.crt` for local and two with `/etc/pki/tls/certs/ca-bundle.crt` for preview and prod). Thank you for your help.

**Comment by janpio** [comment]
Thanks for the feedback, and sorry this was so confusing and required you to actually create an issue here. I opened https://github.com/prisma/prisma/issues/8890 to hopefully make the error message a bit more insightful.
