### ISSUE TITLE
Prisma Binary CDN is blocked in China

### ISSUE THREAD

**Issue by lzuliuyun** [prisma/prisma#8886]
Downloading Prisma engines for rhel-openssl-1.0.x so slow，spend about 5 minute.

![image](https://user-images.githubusercontent.com/6896562/130605020-1dbd3c6b-1da1-437b-8f4c-f7d4ccc49c43.png)

sometime load .env file to long time
![image](https://user-images.githubusercontent.com/6896562/130618279-8323d7db-3ccf-406f-99d4-6a5624d77131.png)

sometime throw error:
![image](https://user-images.githubusercontent.com/6896562/130605122-cd2fd801-9edf-4ae2-b223-be467f052d13.png)

**Comment by pantharshit00** [comment]
Can you please tell us where you are located? We have got reports of our CDN url being blocked in China.

**Comment by jan4984** [comment]
> Can you please tell us where you are located? We have got reports of our CDN url being blocked in China.

How prisma users work this out from China?

**Comment by pantharshit00** [comment]
@jan4984 You might need to build the engines from source while we figure out the CDN situation: https://github.com/prisma/prisma-engines#building-prisma-engines

Here is how you can consume your engines build: https://www.prisma.io/docs/concepts/components/prisma-engines#using-custom-engine-libraries-or-binaries


Follow for China CDN updates: https://github.com/prisma/prisma/issues/7106

**Comment by lzuliuyun** [comment]
> Can you please tell us where you are located? We have got reports of our CDN url being blocked in China.

tks for reply.

we are in shenzhen. we solved by use another network.

**Comment by guog** [comment]
https://github.com/guog/download-prisma-engines

**Comment by longfeiyu127** [comment]
事实上，`github ` 并没有被禁止，只是ip不合适。如果修改合适的ip，是可以正常下载的。可以尝试通过一些手段修改`hosts `。

**Comment by jan4984** [comment]
> In fact, Github isn't banned, it's just inappropriate IP. If you change the appropriate IP address, it can be downloaded normally. You can try to modify the 'hosts' by some means.

It's not github, but aws S3, for download.

**Comment by janpio** [comment]
This should be fixed.
