### ISSUE TITLE
[wrong error msg]: Transactions are not supported by this deployment

### ISSUE THREAD

**Issue by duyquoc1508** [prisma/prisma#8953]
### Bug description

When I use Prisma to connect to MongoDB replica set, there seems to be a problem. My connection URL is mongodb://root:prisma@localhost:27017/prisma-mongo. It can't connect my mongodb. I received an error like that.
```
PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]:
Invalid `prisma.user.create()` invocation:


  Error in connector: Database error. error code: unknown, error message: Transactions are not supported by this deployment
    at cb (E:\Desktop\tessttttttt\prisma-examples\databases\mongodb\node_modules\@prisma\client\runtime\index.js:36378:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.29.1'
}
```
After that, I researched and changed my connection URL to mongodb://root:prisma@localhost:27017/prisma-mongo?authSource=admin&retryWrites=true&w=majority,  it works fine. I realized that the error was caused by my connection missing `authSource=admin`.

Docker image run Mongo replica set [here](https://hub.docker.com/r/prismagraphql/mongo-single-replica).

### How to reproduce

1. Run Mongo replica set on Docker
2. Create schema
3. Run npx prisma generate
4. Run node demo.js
5. See error

### Expected behavior

Maybe I should be received an **authentication error** instead of transactions are not supported by this deployment. Because my connection URL is missing `authSource=admin` which is not related to transaction in db.

### Prisma information

```
datasource db {
  provider = "mongodb"
  url      = env("mongodb://root:prisma@localhost:27017/prisma-mongo")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

model User {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  createdAt DateTime @default(now())
  firstName String
  lastName  String?
  email     String   @unique
}

```

### Environment & setup

- OS: Windows 10
- Database: MongoDB
- Node.js version: v12.18.4
- Docker version: 19.03.13, build 4484c46d9d

### Prisma Version

```
prisma               : 2.29.1
@prisma/client       : 2.29.1
Current platform     : windows
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
Preview Features     : mongoDb
```

**Comment by pantharshit00** [comment]
Hmm, wasn't able to reproduce this error message. I get the following: 
```
❯ yarn start
yarn run v1.22.5
$ ts-node main.ts
(node:1788) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.user.findMany()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: AuthenticationFailed { user: "SCRAM failure: Authentication failed." } })
    at cb (C:\Users\harshit\code\reproductions\issue_8953\node_modules\@prisma\client\runtime\index.js:36940:17)
    at main (C:\Users\harshit\code\reproductions\issue_8953\main.ts:6:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.55s.
```

**Comment by janpio** [comment]
@duyquoc1508 Can you help us reproduce this error?

**Comment by matthewmueller** [comment]
Based on your error message @duyquoc1508 it seems like the MongoDB docker container doesn't have the replicaset enabled, maybe try this comment: https://github.com/prisma/prisma/issues/8266#issuecomment-966618742

**Comment by duyquoc1508** [comment]
@janpio Sorry you can't reproduce the exact error I got, but I'm still getting the error as mentioned if the database connection string is missing `authSource=admin`.
Here is the docker-compose.yml file that I used to create a MongoDB replica instance. Hope it can help you to reproduce the error
```yml
version: '3.7'
services:
  mongodb_container:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongo-replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - '37017:27017'
      - '27017:27017'
    volumes:
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d

```

**Comment by Jolg42** [comment]
We do not recommend using the docker image `prismagraphql/mongo-single-replica`

Using a configured replica set without `?authSource=admin` will show this error
```
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: AuthenticationFailed { user: "SCRAM failure: Authentication failed." } })
```

I cannot reproduce `Transactions are not supported by this deployment`

Check this approach, for testing purposes only: https://github.com/prisma/docs/issues/3040
