### ISSUE TITLE
MongoDB Index Management

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#8954]
## Problem

Right now indices aren't enforced in the database. You may add an index to a field or model in the Prisma Schema Language, but it won't be enforced unless you manually create the index outside of Prisma.

Where this comes up most often is with `@unique` attributes in the Prisma Schema Language. If you don't manually create a unique index in MongoDB (using a tool like Compass), there's nothing stopping you from inserting duplicate records into your MongoDB database, despite what your schema says. Furthermore, the Prisma Client throws exceptions if you've labeled a column as unique but it's not actually unique.

- People work around this by adding unique indices outside of Prisma and then writing `@unique` by hand to enable certain API features like `findUnique` in the client
- With Mongoose, you can create unique indexes at runtime when the schema is initialized. There's some pitfalls with creating an index on boot, so they also offer a way to disable this.
    - From my understanding, people usually run this once with Mongoose then maybe comment it out or disable it once you have the index setup .

## Suggested solution

Ideally `prisma db push` is able to manage unique constraints and indexes. 

My hope is that this can be split off from the larger topic of #7305 because this has a more immediate need and should be less complicated.

## Additional context

- https://github.com/prisma/prisma/issues/6727
- https://github.com/prisma/prisma/issues/7305
- https://github.com/prisma/prisma/issues/8788

**Comment by floelhoeffel** [comment]
Should be fixed with https://github.com/prisma/prisma/releases/tag/3.4.0

**Comment by emimarz** [comment]
I have version 3.10.0 and this problem continues

**Comment by floelhoeffel** [comment]
Hey @emimarz - could you maybe elaborate what is not working and how to reproduce? Thanks!

**Comment by SantiagoPaak** [comment]
Hello, working with Prisma 4.2.1 and the Unique constraint isn't working in MongoDB.

- Created a new schema with a value String with the Unique constraint
- Added one document
- Added again the same document. However, Unique didn't work and created a new document with the same @unique data

**Comment by SantiagoPaak** [comment]
Ah, my mistake then. Didn't knew I had to do that. Works correctly then!

**Comment by nickty** [comment]
npx prisma db push 

The above command solved my problem as well.

**Comment by aayushchugh** [comment]
working after using `prisma db push`
