### ISSUE TITLE
Next & Netlify: Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.

### ISSUE THREAD

**Issue by abereghici** [prisma/prisma#8979]
### Bug description

I'm using next@11.1.0 with prisma@2.30.0 and I'm trying to deploy it on Netlify (serverless). Locally is working okay, but when I'm deploying it I have the following error:

```
{
message: "Query engine binary for current platform "rhel-openssl-1.0.x" could not be found. This probably happens, because you built Prisma Client on a different platform. (Prisma Client looked in "/var/task/netlify/functions/next_api_views/nextPage/chunks/query-engine-rhel-openssl-1.0.x") Searched Locations: /var/task/netlify/functions/.prisma/client /home/runner/work/bereghici.dev/bereghici.dev/common/temp/node_modules/.pnpm/@prisma+client@2.30.0_prisma@2.30.0/node_modules/@prisma/client /var/task/netlify/functions/next_api_views/nextPage /var/task/netlify/functions/next_api_views/nextPage/chunks /var/task/netlify/functions/next_api_views/nextPage/chunks /tmp/prisma-engines /var/task/netlify/functions/next_api_views/nextPage/chunks You already added the platforms "debian-openssl-1.1.x", "rhel-openssl-1.0.x" to the "generator" block in the "schema.prisma" file as described in https://pris.ly/d/client-generator, but something went wrong. That's suboptimal. Please create an issue at https://github.com/prisma/prisma/issues/new"
}
```

You can see the error here: https://6128d3ecc5a191be338765d7--development-bereghicidev.netlify.app/api/views

Source code: https://github.com/abereghici/bereghici.dev/tree/prisma/apps/blog 

### How to reproduce

Deploy a simply nextjs & prisma app to netlify

### Expected behavior

Prisma client should work on Netlify.

### Prisma information

```
datasource db {
  provider = "mysql"
  url = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
  planetScaleMode = true
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["planetScaleMode"]
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

model views {
  id    BigInt @id @default(autoincrement())
  slug  String @db.VarChar(1024)
  count BigInt @default(0)
}

```

### Environment & setup

- OS: MacOS 
- Database:  MySQL ( planetscale )
- Node.js version: v14.17.2

### Prisma Version

```
2.30.0
```

**Comment by janpio** [comment]
We have tests for Next.js deployments, and Netlify deployments, but not both (yet). Anything special in your project that we should take into consideration when creating our reproduction of this?

**Comment by abereghici** [comment]
@janpio I'm using Netlify with Essential NextJS plugin auto installed (from their dashboard ) https://github.com/netlify/netlify-plugin-nextjs 

You can see the `netlify.toml` file here: https://github.com/abereghici/bereghici.dev/blob/prisma/apps/blog/netlify.toml

Also I moved `_http_comon` externally for server build: https://github.com/abereghici/bereghici.dev/blob/prisma/apps/blog/next.config.js#L89 
because of this issue: https://github.com/prisma/prisma/issues/6899

Also, I'm using pnpm with rush.js monorepo.

I'll try to create a simple repository to reproduce it.

**Comment by abereghici** [comment]
@janpio  Here is a repo where I'm able to reproduce the error: 

https://github.com/abereghici/nextjs-prisma-test

**Comment by abereghici** [comment]
@janpio I was able to use Prisma on Netlify by configuring `next target` to `experimental-serverless-trace`. The issue appears only when I'm using the `serverless` target. 
It can be easily reproduced using this repo https://github.com/abereghici/nextjs-prisma-test

**Comment by pantharshit00** [comment]
Hello @abereghici 

Your deployment doesn't throw any error: https://next-prisma-test.netlify.app/api/views
![image](https://user-images.githubusercontent.com/22195362/132176792-31ba055c-797f-40fc-9be4-19f231c990e8.png)

Did you manage to fix this already?

**Comment by abereghici** [comment]
@pantharshit00 In my last test I used `experimental-serverless-trace` and it worked ( https://github.com/abereghici/nextjs-prisma-test/blob/main/next.config.js#L4 ), the issue appears when you deploy it with `serverless` target.

**Comment by abereghici** [comment]
@pantharshit00 I redeployed with `serverless` target, now you should be able to see the error here: https://next-prisma-test.netlify.app/api/views

**Comment by garrensmith** [comment]
@abereghici sorry to get back to you after so long. Did you manage to resolve this?

**Comment by janpio** [comment]
[next-prisma-test.netlify.app/api/views](https://next-prisma-test.netlify.app/api/views) still returns an error:
```
{"message":"Query engine binary for current platform \"rhel-openssl-1.0.x\" could not be found.\nThis probably happens, because you built Prisma Client on a different platform.\n(Prisma Client looked in \"/var/task/.netlify/functions-internal/next_api_views/nextPage/chunks/query-engine-rhel-openssl-1.0.x\")\n\nSearched Locations:\n\n  /var/task/.netlify/functions-internal/.prisma/client\n  /Users/abereghici/Development/nextjs-prisma-test/node_modules/@prisma/client\n  /var/task/.netlify/functions-internal/next_api_views/nextPage\n  /var/task/.netlify/functions-internal/next_api_views/nextPage/chunks\n  /var/task/.netlify/functions-internal/next_api_views/nextPage/chunks\n  /tmp/prisma-engines\n  /var/task/.netlify/functions-internal/next_api_views/nextPage/chunks\n\nYou already added the platforms \"darwin\", \"rhel-openssl-1.0.x\" to the \"generator\" block\nin the \"schema.prisma\" file as described in https://pris.ly/d/client-generator,\nbut something went wrong. That's suboptimal.\n\nPlease create an issue at https://github.com/prisma/prisma/issues/new"}
```

Locally my fork of https://github.com/abereghici/nextjs-prisma-test indeed sends a query as intended.

Deployment to Netlify required an edit in `netlify.toml` to change `publish = "out"` to `publish = ".next"`. Afterwards I get a working query though:

Function logs:
```
Jan 27, 02:41:57 AM: INIT_START Runtime Version: nodejs:16.v11	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:ee071345fbee0f4751fcbcd47a5784052d8f7d4256ca7f31e6056b294cee515c
Jan 27, 02:42:00 AM: 39c73a5e INFO   prisma:query SELECT SUM(`count`) FROM (SELECT `harlequin_alpaca`.`views`.`count` FROM `harlequin_alpaca`.`views` WHERE 1=1) AS `sub`
Jan 27, 02:42:00 AM: 39c73a5e INFO   [GET] /api/views (SSR)
Jan 27, 02:42:00 AM: 39c73a5e Duration: 2297.32 ms	Memory Usage: 150 MB	Init Duration: 171.53 ms	
Jan 27, 02:42:19 AM: 354df11f INFO   prisma:query SELECT 1
Jan 27, 02:42:19 AM: 354df11f INFO   prisma:query SELECT SUM(`count`) FROM (SELECT `harlequin_alpaca`.`views`.`count` FROM `harlequin_alpaca`.`views` WHERE 1=1) AS `sub`
Jan 27, 02:42:19 AM: 354df11f INFO   [GET] /api/views (SSR)
Jan 27, 02:42:19 AM: 354df11f Duration: 204.33 ms	Memory Usage: 150 MB	
```

Live URL: https://main--gleeful-seahorse-12eb52.netlify.app/api/views

**Comment by abereghici** [comment]
@janpio Thanks for the investigation. I'll try to change `publish = ".next"` for this test project. 
In the original project, where I encountered the issue, I was able to make it work by adding `"@prisma/engines-version"` in `package.json`. In `netlify.toml` I still have `publish = "out"`. This might be related to `pnpm` and `rushjs`, how it resolves the dependencies. 
https://github.com/abereghici/nextjs-bereghici-dev/blob/main/apps/blog/package.json#L38

**Comment by janpio** [comment]
Hmmm. Optimally you could provide some reproduction code that you _know_ is not working, and then we will be able to also show it not working (with the error you reported). Otherwise this will be hard to impossible for us to debug and fix.

**Comment by millsp** [comment]
Hey @abereghici, we recently started displaying useful errors that might have led you to this error. In some cases, when Netlify caches your dependencies, it can cause the engine no to be found. And with Next.js, it is possible that some files are not bundled correctly. For both cases, we are now displaying helpful errors and how to get things working. We were also not able to reproduce this, so I am marking this issue closed. Feel free to open a new one if you encounter any problem. Thanks.
