### ISSUE TITLE
Implement missing Mongo referential actions emulation

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma#9014]
Some emulations are missing. Implement:
- [ ] onUpdate: Cascade
- [ ] onUpdate: Restrict
- [ ] onUpdate: SetNull
- [ ] onUpdate: Restrict
- [ ] onUpdate: NoAction

The onDelete emulations are also missing hooks into the onUpdate emulation (required for example for SetNull propagation).

**Comment by matthewmueller** [comment]
Note: This blocks migrate from releasing "no foreign key" mode
