### ISSUE TITLE
Log output of Node-API library engine is different

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9039]
When starting a Prisma Client, you get an info log about the starting of the pool with x connections. This log is different when you consume it as an event:

`library`:
```
      Array [
        Object {
          message: Starting a sqlite pool with 5 connections.,
          target: undefined,
        },
      ]
```

`binary`:
```
      Array [
        Object {
          message: Starting a sqlite pool with 5 connections.,
          target: target: quaint::pooled,
        },
      ]
```

I assume similar differences exist across the board.

Related: https://github.com/prisma/prisma/issues/7605 + https://github.com/prisma/prisma/pull/9037

**Comment by aqrln** [comment]
Related tech debt task: https://www.notion.so/prismaio/Client-events-are-not-type-safe-f57c86c66a9647338e7bdf4f78b204fe
