### ISSUE TITLE
Jest spawns quite a many binaries

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#9042]
- Take a look into the repo in https://github.com/pimeys/prisma-leaks
- Check that the `nApi` feature is NOT enabled.
- Run `yarn test --maxWorkers=1 --logHeapUsage`
- You'd expect it to run query engine due to having only one worker. 
- On my machine I see 42 query-engine processes up and running.

**Comment by pimeys** [comment]
Oh, and try to get that prisma schema pushed too, see that the database works.

**Comment by janpio** [comment]
With recent Prisma and Jest versions this is not reproducible anymore when using `engineType = "binary"`.

(Seems in the provided combination there was a Jest bug around `ReferenceError: AbortSignal is not defined` that prevented the Query Engine process to be stopped.)
