### ISSUE TITLE
Real-time Database Events

### ISSUE THREAD

**Issue by bitsmyth** [prisma/prisma#905]
Coming from Hasura, it has a event trigger system which can be executed async on serverless functions when a value changes in the database. I think that this feature comes in handy if you have a lot of analytics and notifications running.

As prisma offers subscription to the database we could mimic this behavior (out of scope of graphQL resolvers) and I am wondering if anybody is doing this already and what your experiences are with it?

**Comment by pantharshit00** [comment]
There are plans for a separate events engine(https://github.com/prisma/prisma2/issues/298) which might handle this use case.

**Comment by jmarbutt** [comment]
I think this makes sense to stay in a product like Hasura, because it seems out of scope for a product like Prisma. I am doing the same approach and just using Hasura as an eventing system.

**Comment by Korayem** [comment]
I am using Supabase where [they have multiple options](https://supabase.com/blog/2021/07/30/supabase-functions-updates) to implement that

Coupled with Prisma as my ORM running on nextjs vercel edge, I couldn't be happier

**Comment by sorenbs** [comment]
If Prisma were to support this as part of our cloud product, would you prefer to have Prisma deploy a serverless function that receives the Database Change Event. Or would you prefer us to trigger a webhook?

**Comment by AsafKaravani** [comment]
Webhook +1

**Comment by matanzg** [comment]
Webhooks+1

**Comment by TasinIshmam** [comment]
Hi folks 👋, 

Tasin from Prisma here. 

We are launching a [Design Partner Program](https://prismaio.notion.site/Prisma-Design-Partner-Program-a286c25e47fb44e199038ca71dce36a1) where external teams can collaborate with us to shape Prisma's future. In this program, we will collaborate with you on defining solutions to the following problems: 

- **Listening and reacting to database changes in real-time**
- Data projections for denormalization or data integration purposes
- Caching
- Serverless workflow orchestration

**If you’re struggling with real-time event triggers, especially in a serverless environment, you might be a great fit for this program!**  Your team can take advantage of new Prisma features that you won’t have to build or maintain yourselves. As you invest time in partnering with us, we will also offer you free credits once anything coming out of this program reaches production.

**You can [check out the program in more detail](https://prismaio.notion.site/Prisma-Design-Partner-Program-a286c25e47fb44e199038ca71dce36a1) to see the kinds of activities we’re planning. To apply to this program, [fill out the form](https://docs.google.com/forms/d/e/1FAIpQLSdfadMO7qVOMlOgmeYevpM-olpjku2-3sVzMvVQiHITmZf4dA/viewform)**.

We’re looking forward to hearing from you!

**Comment by nikolasburk** [comment]
Hey everyone 👋 thanks a lot for the lively discussion in this issue 🙏

As you may have seen, we recently released [Prisma Pulse](https://www.prisma.io/blog/prisma-pulse-introducing-delivery-guarantees-for-database-change-events), a managed Change Data Capture service that'll deliver database change events to your application in real-time and with delivery guarantees.

While not a "native" ORM feature, it has a first-class integration with Prisma Client via the `@prisma/extension-pulse` package:

```ts
import { PrismaClient } from "@prisma/client";
import { withPulse } from "@prisma/extension-pulse";

const prisma = new PrismaClient()
  .$extends(withPulse({ apiKey: process.env.PULSE_API_KEY }));
```

You can then subscribe to new database events like this:

```ts
// Stream all change events from the `User` table
const stream = await prisma.user.stream() 

// Wait for any events happening on the `User` table
for await (const event of stream) {
  // Log every event to the console
  console.log(`An event happened in the database: \n`, event)
}
```

You can learn more and get started with Prisma Pulse [here](https://www.prisma.io/pulse).

If you prefer an approach to trigger events that's purely ORM-based and happens on the application layer without using additional infrastructure, you can use [Prisma Client extensions](https://www.prisma.io/docs/orm/prisma-client/client-extensions) for this as well by hooking into the query lifecycle and executing custom logic before or after a query hits the database.

As part of our effort to clean up this GitHub repo, we're closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto

**Comment by Prism117** [comment]
And then it was removed.

**Comment by rsodre** [comment]
I implemented a custom solution using query logs on my next.js server.
it only works because all my keys are unique @default(uuid())

```js
import { PrismaClient } from '@prisma/client';

export const prisma = new PrismaClient({
  log: [{ emit: 'event', level: 'query' }],
});
```

```js
// /api/database/events/sub

import { NextResponse } from 'next/server';
import { databaseEvents } from './database-events';

export const dynamic = 'force-dynamic';
export const maxDuration = 60; // Helper for Vercel/Next.js to allow long requests

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const commandsParam = searchParams.get('commands');
  const valuesParam = searchParams.get('values');

  if (!commandsParam || !valuesParam) {
    return NextResponse.json({ success: false, error: 'Missing commands or values' }, { status: 400 });
  }

  const commands = commandsParam.split(',');
  const values = valuesParam.split(',');

  try {
    // Wait for 50 seconds max to allow some buffer before browser/server timeout
    // The client hook loop handles reconnection
    const result = await databaseEvents.waitForQuery(commands, values, 50000);
    return NextResponse.json(result);
  } catch (error: any) {
    console.error('Database subscription error:', error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
```

```js
import { EventEmitter } from 'events';
import { prisma } from '@popsy/database';

class DatabaseEventEmitter extends EventEmitter {
  private static instance: DatabaseEventEmitter;
  private initialized: boolean = false;

  private constructor() {
    super();
    // Increase limit if we expect many concurrent waiters, though typical for this use case
    // might be low. 
    this.setMaxListeners(50);
  }

  public static getInstance(): DatabaseEventEmitter {
    if (!DatabaseEventEmitter.instance) {
      DatabaseEventEmitter.instance = new DatabaseEventEmitter();
    }
    return DatabaseEventEmitter.instance;
  }

  public init() {
    if (this.initialized) return;

    // @ts-ignore - Prisma types might need specific configuration for $on if not globally properly typed with emit
    prisma.$on('query', (e: any) => {
      // Re-emit the query event as a local event
      this.emit('query', e);
    });

    this.initialized = true;
  }

  /**
   * Waits for a query that matches specific commands or values.
   * Resolves when such a query is detected.
   */
  public waitForQuery(commands: string[], values: string[], timeoutMs = 60000): Promise<any> {
    if (!this.initialized) {
      this.init();
    }

    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.removeListener('query', handler);
        // We resolve with null or reject? 
        // Typically strict actions might want to know it timed out, 
        // but for a "subscribe" stream it often just closes. 
        // Let's resolve with specific timeout result or error.
        resolve({ timeout: true });
      }, timeoutMs);

      const handler = (e: any) => {
        const queryParams = e.params || '[]';
        // params is typically a string representation of array in recent prisma versions or actual array depending on provider
        // It is often safer to stringify to check simple inclusions if we don't want to parse strict JSON
        const paramString = typeof queryParams === 'string' ? queryParams : JSON.stringify(queryParams);
        const queryString = e.query || '';

        // Check command match (usually part of the query string like "INSERT", "UPDATE", "SELECT")
        const commandMatch = commands.some(cmd =>
          queryString.startsWith(cmd.toUpperCase())
        );

        // Check values match
        const valueMatch = values.some(val =>
          paramString.includes(val)
        );

        // Requirement: at least one command AND at least one value
        if (commandMatch && valueMatch) {
          clearTimeout(timer);
          this.removeListener('query', handler);
          resolve({ success: true, event: { query: queryString, params: queryParams } });
        }
      };

      this.on('query', handler);
    });
  }
}

export const databaseEvents = DatabaseEventEmitter.getInstance();
```

```js
import { useEffect } from "react";

export function useDatabaseEvent({
  commands,
  values,
  callback,
  enabled,
}: {
  commands: string[];
  values: string[];
  callback: (event: any) => void;
  enabled?: boolean;
}) {

  useEffect(() => {
    let isMounted = true;

    const poll = async () => {
      try {
        if (!isMounted) return;

        const params = new URLSearchParams();
        params.set('commands', commands.join(','));
        params.set('values', values.join(','));

        const response = await fetch(`/api/database/events/sub?${params.toString()}`);
        
        if (!response.ok) {
             throw new Error(`Subscription failed: ${response.statusText}`);
        }

        const result = await response.json();

        if (isMounted && result) {
          if (result.success && result.event) {
            callback(result.event);
          }
          if (result.error) {
            console.error("Database event error:", result.error);
             // Verify if it's a timeout error vs actual error before adding delay? 
             // Ideally api returns { timeout: true } or similar on clean timeout
          }
        }
      } catch (error) {
        console.error("Database event exception:", error);
      } finally {
        if (isMounted) {
          // setTimeout(() => { if (isMounted) poll(); }, 100);
          poll();
        }
      }
    };

    if (enabled) {
      poll();
    }

    return () => {
      isMounted = false;
    };
  }, [enabled, commands.join(','), values.join(',')]);
}
```
