### ISSUE TITLE
`InteractiveTransaction`: Middleware param `runInTransaction` set to `false`

### ISSUE THREAD

**Issue by rodrigo4244** [prisma/prisma#9073]
### Bug description

When using `interactiveTransaction` preview feature alongside with a middleware you won't get the `runInTransaction` parameter set to `true`.

![image](https://user-images.githubusercontent.com/8367325/131761534-ce07de30-c6a3-4776-95f1-ef126c06cc2f.png)

Despite the above issue I would want the ability to have access to the `transactionPrismaClient` or an `afterCommit` hook in `params`. That way I can run logic only after the transaction is committed.
Sequelize equivalent of this would be: https://sequelize.org/master/manual/transactions.html#the--code-aftercommit--code--hook

### How to reproduce

```ts
// schema.prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Car {
  model String
}

// middleware.ts
export const middleware = (prisma: PrismaClient) => {
  prisma.$use(async (params, next) => {
 	console.log('params', params) // params.runInTransaction = false -> should be true
  })
}

// prisma.ts
import { middleware } from './middleware'

const prisma = new PrismaClient()
middleware(prisma)

export { prisma }

// main.js
import { prisma } from './prisma.ts'

const main = async () => {
	await prisma.$transaction(async (tPrisma) => {
		return tPrisma.car.create({ data: { model: 'abc' } })
	})
}
```

### Prisma information

in `How to reproduce` I wrote an example

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: Node v14

### Prisma Version

```
prisma               : 2.29.1
@prisma/client       : 2.29.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
Preview Features     : interactiveTransactions
```

**Comment by BarrySJL** [comment]
I have the same problem

**Comment by pantharshit00** [comment]
This is expected. The middleware logs you are seeing are for each client call you are making and not for `$transaction` block as they don't trigger middlewares.

Can you please tell us why you need a specific hook for this? I think just use `.then` block. If the `.then` block is called it would mean transaction is successful. Sequelize only provides for unmanaged transaction API as far as I know where you handle commits yourself which is not offered by Prisma right now.

**Comment by pantharshit00** [comment]
> I have the same problem

Can you please elaborate and maybe present a minimal reproduction?

**Comment by pepoirot** [comment]
Our team has the same problem as we applied the solution presented in https://github.com/prisma/prisma/issues/5128#issuecomment-848890199.

**Comment by kevinmamaqi** [comment]
This is still happening in Prisma 3.14.0

**Comment by janpio** [comment]
Please provide more information, or let us know if the exact same reproduction from above is still showing this behavior @kevinmamaqi. From our perspective this is fixed.

**Comment by millsp** [comment]
Hey @kevinmamaqi we have an example reproduction for this
https://github.com/prisma/prisma/blob/93cecb2a4cbd0db3127cafc5880d4708407c7b12/packages/client/src/__tests__/integration/happy/interactive-transactions-sqlite/test.ts/#L400-L419

**Comment by kevinmamaqi** [comment]
Thanks @millsp and @janpio 

It is fixed indeed. I must have missed a step, or had another error as now it is working as expected.
