### ISSUE TITLE
"Error: Command failed" wile executing "npx prisma migrate dev"

### ISSUE THREAD

**Issue by danieleguglietti** [prisma/prisma#9102]
When I try to run `migrate dev` this error shows up: 
```
Error: Get config: Error: Command failed with exit code 3221225477: D:\Progetti\IglesiasCraft\bot-discord\node_modules\@prisma\engines\query-engine-windows.exe cli get-config
```

I don't have any idea what could it be…

**Comment by danieleguglietti** [comment]
Sorry, error found, i didn't had dotenv installed...

**Comment by janpio** [comment]
dotenv or .NET? You should not need to install anything to be able to run that command.

**Comment by danieleguglietti** [comment]
> dotenv or .NET? You should not need to install anything to be able to run that command.

dotenv, the npm package. Until I installed it, it didn't work

**Comment by janpio** [comment]
That is super weird. If you can reproduce this again, please let us know. We should investigate then.
