### ISSUE TITLE
Internal GraphQL schema marks JsonFilter types as DateTime

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9117]
### Discussed in https://github.com/prisma/prisma/discussions/9116

<div type='discussions-op-text'>

<sup>Originally posted by **RobertCraigie** September  3, 2021</sup>
While looking into adding support for `Json` types to https://github.com/RobertCraigie/prisma-client-py I looked through the generated GraphQL schema and noticed that the `JsonFilter` type takes values of `DateTime` type, I would've expected to see either `Json` or `String`. Should be noted that this happens with and without the preview feature enabled. 

Just curious as to whether or not this is intentional.

```graphql
input JsonFilter {
  equals: DateTime
  not: DateTime
}

input JsonWithAggregatesFilter {
  equals: DateTime
  not: DateTime
  _count: NestedIntFilter
  count: NestedIntFilter
  _min: NestedJsonFilter
  min: NestedJsonFilter
  _max: NestedJsonFilter
  max: NestedJsonFilter
}
```</div>

**Comment by janpio** [comment]
Can you share a simple Prisma schema we can use to reproduce this? Thanks.

**Comment by RobertCraigie** [comment]
@janpio here's the schema I used to test it.

```prisma
datasource db {
  provider = "postgres"
  url      = env("POSTGRES_URL")
}

generator db {
  provider        = "prisma-client-py"
  previewFeatures = ["filterJson"]
}

model User {
  id         String   @id @default(cuid())
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt
  name       String
  meta       Json
}
```

However, it will fail to generate as Prisma Client Python doesn't support `Json` and will error, I can provide installation steps to patch it though, if that would help.

**Comment by janpio** [comment]
I thought you were talking about the generated types of Prisma Client JS, but those looks just right to me:

```
  export type JsonFilter = 
    | PatchUndefined<
        Either<Required<JsonFilterBase>, Exclude<keyof Required<JsonFilterBase>, 'path'>>,
        Required<JsonFilterBase>
      >
    | OptionalFlat<Omit<Required<JsonFilterBase>, 'path'>>

  export type JsonFilterBase = {
    equals?: InputJsonValue
    not?: InputJsonValue
  }

[...]

  export type JsonWithAggregatesFilterBase = {
    equals?: InputJsonValue
    not?: InputJsonValue
    _count?: NestedIntFilter
    /**
     * @deprecated since 2.23 because Aggregation keywords got unified to use underscore as prefix to prevent field clashes.
     * 
    **/
    count?: NestedIntFilter
    _min?: NestedJsonFilter
    /**
     * @deprecated since 2.23 because Aggregation keywords got unified to use underscore as prefix to prevent field clashes.
     * 
    **/
    min?: NestedJsonFilter
    _max?: NestedJsonFilter
    /**
     * @deprecated since 2.23 because Aggregation keywords got unified to use underscore as prefix to prevent field clashes.
     * 
    **/
    max?: NestedJsonFilter
  }
```

(This is from a recent `dev` version)

Can you clarify where I should look for this?

**Comment by RobertCraigie** [comment]
Oh no sorry, I meant the query engine API, I didn't test whether or not it actually works, just that the generated API schema has the types as DateTime instead of JSON or String.

I found it in the GraphQL playground.

**Comment by janpio** [comment]
Ah ok, one level deeper then. We usually treat this as an internal implementation detail - if there is something weird, we will of course still look at it.

**Comment by janpio** [comment]
https://github.com/prisma/prisma-engines/pull/2152 got merged that should fix it 👍
