### ISSUE TITLE
`generator.engineType` is not validated

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9120]
The Node-API library stabilization introduced a new property `engineType` with valid values `binary` and `library` to the PSL. Right now this property is not validated, and you can input any value you want, as for example `["binary"]` instead of the expected string.

We should validate the _type_ of the value to make sure it is a string. (We do not want to validate the exact strings as an Enum as we want to stay flexible in how we expand the Client. (VSCode extension will suggest the available strings by default via auto completion and documentation)

**Comment by matthewmueller** [comment]
I believe Prisma Format is mostly being supported by the Migrations Team right now.
