### ISSUE TITLE
SelectAll and Exclude for select query

### ISSUE THREAD

**Issue by IRediTOTO** [prisma/prisma#9122]
## Problem

Hi, not a problem here, fine with Prisma select now, work as my dream. Just wonder can you add this function?

## Suggested solution

```
prisma.user.findMany({
select:{
    selectAll:true
    exclude:{password:true} 
}
})
```

**Comment by janpio** [comment]
There is a popular feature request about this at https://github.com/prisma/prisma/issues/5042 - so I am going to close this issue here as a duplicate. Add a 👍 on the other issue @IRediTOTO.
