### ISSUE TITLE
findMany returns all objects when `where` is undefined.

### ISSUE THREAD

**Issue by alucardu** [prisma/prisma#9124]
### Bug description

```
    const movies = await prisma.movie.findMany({
      where: {userId: req.userId},
    });
```

If `req.userId` is undefined prisma returns all movie objects.

### How to reproduce

create a query that uses a `where` and make the value undefined.

### Expected behavior

If the `where` value is undefined no objects should be returned

### Prisma information

```
model Movie {
  id                Int     @id @default(autoincrement())
  original_title    String
  tmdb_id           Int
  poster_path       String @default("")
  user              User[] @relation("UserAddedMovies", fields: [userId], references: [id])
  userId            Int
}
```

### Environment & setup

Windows 10
Postgress
Node: v14.17.6
NPM: 6.14.15

### Prisma Version

```
prisma                : 2.30.0
@prisma/client        : 2.30.0
Current platform      : windows
Query Engine (Binary) : query-engine 60b19f4a1de4fe95741da371b4c44a92f4d1adcb (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine      : migration-engine-cli 60b19f4a1de4fe95741da371b4c44a92f4d1adcb (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine  : introspection-core 60b19f4a1de4fe95741da371b4c44a92f4d1adcb (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary         : prisma-fmt 60b19f4a1de4fe95741da371b4c44a92f4d1adcb (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash  : 60b19f4a1de4fe95741da371b4c44a92f4d1adcb
Studio                : 0.422.0
```

**Comment by ADrejta** [comment]
That is the way it is intended to work based on this [guide](https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined).

You should probably send null instead of undefined in this case (or not make a call to the database at all).

**Comment by pantharshit00** [comment]
Yes, this is working as expected. Passing `undefined` to a filter is equivalent to passing no filter at all. You will need to cast it if you receive `undefined` from your client. Guide which @ADrejta explains this in detail.
