### ISSUE TITLE
thread '<unnamed>' panicked at 'Every RelationInfo should have a complementary RelationInfo on the opposite relation field.'

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9141]
`prisma validate/format` crash on this schema:

```prisma
datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Test {
  id         Int        @id
  fk         Int
  testparent TestParent @relation(fields: [fk], references: [id])
}

model TestParent {
  id    Int    @id
  tests Test[]

  fk   Int
  self TestParent @relation(fields: [fk], references: [id])
}
```

with:

```
thread '<unnamed>' panicked at 'Every RelationInfo should have a complementary RelationInfo on the opposite relation field.', libs\datamodel\connectors\dml\src\datamodel.rs:165:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Unexpected token E in JSON at position 0
```

This is surprising, as usually the missing backrelation validation works fine, e.g. when you only have the second model without the relation to the first one:
```prisma
model TestParent {
  id    Int    @id
  fk   Int
  self TestParent @relation(fields: [fk], references: [id])
}
```

**Comment by janpio** [comment]
Here is a user report with a schema that is causing this in the wild: https://github.com/prisma/prisma/issues/9238#issue-995387425

**Comment by ChipClark** [comment]
The schema reported in #9328 is mine. 

If I run prisma migrate (which resets the schema) I do not get the error, but then I don't have the relationships. 
Once I add the relationships, I get the error.

**Comment by ChipClark** [comment]
upgraded to 3.1.1 still getting an error, but the error has changed: 

`Error: Schema parsing
error: Error parsing attribute "@relation": The given constraint name `PersonRelationship_RelatedPersonID_fkey` is already in use in the data model. Please provide a different name using the `map` argument.
  -->  schema.prisma:602
   |
601 |   ValidToDate          DateTime
602 |   RelatedPerson        Person          @relation(name: "RelatedPerson", fields: [RelatedPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)
603 |   SupportedPerson      Person          @relation(name: "SupportedPerson", fields: [RelatedPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)
   |
error: Error parsing attribute "@relation": The given constraint name `PersonRelationship_RelatedPersonID_fkey` is already in use in the data model. Please provide a different name using the `map` argument.
  -->  schema.prisma:603
   |
602 |   RelatedPerson        Person          @relation(name: "RelatedPerson", fields: [RelatedPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)
603 |   SupportedPerson      Person          @relation(name: "SupportedPerson", fields: [RelatedPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)
604 |   Person               Person          @relation(name: "PrimaryPerson", fields: [PKPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)`

Made changes to the scheme to attempt to resolve the issue with map

`model PersonRelationship {
  PersonRelationshipID Int              @id @default(autoincrement())
  PKPersonID           Int
  RelationshipTypeID   Int
  RelatedPersonID      Int
  Description          String?          @db.VarChar(Max)
  Active               Boolean
  ActiveFromDate       DateTime         @db.Date
  ModifiedDate         DateTime         @db.DateTime
  ModifiedBy           String           @db.VarChar(30)
  ValidFromDate        DateTime
  ValidToDate          DateTime
  RelatedPerson        Person          @map(name: "RelatedPerson")
  SupportedPerson      Person          @map(name: "SupportedPerson")
  RelatedPerson        Person          @relation(fields: [RelatedPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)
  SupportedPerson      Person          @relation(fields: [RelatedPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)
  Person               Person          @relation(name: "PrimaryPerson", fields: [PKPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)

  RelationshipType     RelationshipType @relation(fields: [RelationshipTypeID], references: [RelationshipTypeID])
  
  @@unique([PKPersonID, RelatedPersonID, RelationshipTypeID], name: "nclunq_PersonRelationship_PKPersonID_RelatedPersonID_RelationshipTypeID")
}`

now getting the following error: 

`Error: Schema parsing
error: Field "RelatedPerson" is already defined on model "PersonRelationship".
  -->  schema.prisma:604
   |
603 |   SupportedPerson      Person          @map(name: "SupportedPerson")
604 |   RelatedPerson        Person          @relation(fields: [RelatedPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)
   |
error: Field "SupportedPerson" is already defined on model "PersonRelationship".
  -->  schema.prisma:605
   |
604 |   RelatedPerson        Person          @relation(fields: [RelatedPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)
605 |   SupportedPerson      Person          @relation(fields: [RelatedPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)`

not sure if there is a better way to reference/map these fields.

**Comment by ChipClark** [comment]
I was able to get passed this error modifying the scheme as follows: 

`model PersonRelationship {
  PersonRelationshipID Int              @id @default(autoincrement())
  PKPersonID           Int
  RelationshipTypeID   Int
  RelatedPersonID      Int
  Description          String?          @db.VarChar(Max)
  Active               Boolean
  ActiveFromDate       DateTime         @db.Date
  ModifiedDate         DateTime         @db.DateTime
  ModifiedBy           String           @db.VarChar(30)
  ValidFromDate        DateTime
  ValidToDate          DateTime
  RelatedPerson        Person          @relation(name: "RelatedPerson", fields: [RelatedPersonID], map: "RelatedPersons", references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)
  SupportedPerson      Person          @relation(name: "SupportedPerson", fields: [RelatedPersonID], map: "SupportedPersons", references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)
  Person               Person          @relation(name: "PrimaryPerson", fields: [PKPersonID], references: [PKPersonID], onDelete: NoAction, onUpdate: NoAction)

  RelationshipType     RelationshipType @relation(fields: [RelationshipTypeID], references: [RelationshipTypeID])
  
  @@unique([PKPersonID, RelatedPersonID, RelationshipTypeID], name: "nclunq_PersonRelationship_PKPersonID_RelatedPersonID_RelationshipTypeID")
}
`

**Comment by tomhoule** [comment]
https://prisma-errors.netlify.app/report/13513 <- new occurrence

**Comment by pimeys** [comment]
Nice.
