### ISSUE TITLE
MongoDb with prisma showing error

### ISSUE THREAD

**Issue by bytesagar** [prisma/prisma#9153]
### Discussed in https://github.com/prisma/prisma/discussions/9152

<div type='discussions-op-text'>

<sup>Originally posted by **bytesagar** September  7, 2021</sup>
``` Invalid `prisma.user.create()` invocation:

  Error in connector: Database error. error code: unknown, error message: Transactions are not supported by this deployment ```

I am getting this error.</div>

**Comment by janpio** [comment]
This will be responded to in the discussion.
