### ISSUE TITLE
`prisma 3.0.1` warns about breaking changes.

### ISSUE THREAD

**Issue by Zn4rK** [prisma/prisma#9171]
### Bug description

It probably should warn about breaking changes, but this check:
https://github.com/prisma/prisma/blob/40783e17b07d24c3576e863abe6344b6d9d7a9a7/packages/cli/src/Generate.ts#L219

Is not correct since the switch to semver.

### How to reproduce

Install `prisma`@`3.0.1` and re-run `prisma generate`.

### Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Something {
  id        String @id @default(cuid())
  name      String
}
```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v14.17.1

### Prisma Version

```
prisma                  : 3.0.1
@prisma/client          : 3.0.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by Zn4rK** [comment]
I don't understand the title change. This is a clean/new install. It shouldn't warn about breaking changes at all. The original title was correct.

**Comment by janpio** [comment]
This is what I am seeing on a clean install:

```
C:\Users\Jan\Documents\throwaway\9171>npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (3.0.1) to .\node_modules\@prisma\client in 63ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

warn Prisma 2.12.0 has breaking changes.
You can update your code with
`npx @prisma/codemods update-2.12 ./`
Read more at https://pris.ly/2.12
```

Is that what you are seeing as well @Zn4rK?

**Comment by Zn4rK** [comment]
@janpio Yep, exactly.

**Comment by janpio** [comment]
Ok, so this is comparing the previous version in the project with the current version - and on a new project this now seems to return a number < 12 - which makes sense on `3.0.1` of course. What is missing is the confirmation that the old version was also major `2`.

Then we can _additionally_ also think if we should output a warning that reminds people to look at the breaking changes in 3.x if they upgrade from 2.x.

Does that make sense?

**Comment by janpio** [comment]
Thanks for reporting this @Zn4rK - a draft PR is up and we are now looking at if this is all correct, covered, if we can and should do more and so on. The message is really nothing to worry about of course really.

**Comment by pantharshit00** [comment]
Sorry for the title change that I did. I misread the issue and though you were asking for a warning about breaking changes. Looks like this is already handled now.
