### ISSUE TITLE
Prisma unable to load glibc with 3.0.1

### ISSUE THREAD

**Issue by lohnsonok** [prisma/prisma#9174]
### Bug description

After updating Prisma from 3.0.0 to 3.0.1, I started getting TypeScript errors about .prisma/client locally (not on CI), so I thought I'd manually run npx prisma generate but it throws an error:

``` 
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Unable to require(`/home/linux/Documents/prisma-api/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`)
 /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /lib/x86_64-linux-gnu/libcrypto.so.1.1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Locally I use Ubuntu. In the changelog I saw something about RHEL, so could be related?

### How to reproduce

1. Update Prisma from 2.30.3 to 3.0.0
2. Run npx prisma generate
3. See above error

### Expected behavior

No error.

### Prisma information

No problem related to my prisma schema or queries

### Environment & setup

- OS: Ubuntu 20.04
- Database: PostgresQL
- Node.js version: 14.17.3

### Prisma Version

v3.0.0

### Other Information
Checking my libc version by running `file /snap/core/current/lib/x86_64-linux-gnu/libc.so.6` in terminal
```
Result :
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: symbolic link to libc-2.23.so
```

**Comment by pantharshit00** [comment]
I don't think you use `snap` libc as a shared package as snap has some isolation layer. 

Can you try installing `glibc` once? I will actually recommend installing whole `build-essential` package if you using the machine for software development.

```terminal
sudo apt update
sudo apt install build-essential -y
```

**Comment by lohnsonok** [comment]
> I don't think you use `snap` libc as a shared package as snap has some isolation layer.
> 
> Can you try installing `glibc` once? I will actually recommend installing whole `build-essential` package if you using the machine for software development.
> 
> ```
> sudo apt update
> sudo apt install build-essential -y
> ```
> 
> (I removed RHEL from the title as you are not using a red hat machine and there is mention of RHEL in the error)

build-essential was already installed (latest version: 12.8ubuntu1.1) but I get the same error
I think that a forced update to glibc 2.25 or higher should be able to fix the problem but how to do it, I don't know

**Comment by pantharshit00** [comment]
@lohnsonok The ubuntu machine that I have has GLIBC at 2.31. You can check by running `ldd --version`. 

Ubuntu package repos also have `libc6` package at `2.31-0ubuntu9.2` (Check by running `apt-cache policy libc6`)
![image](https://user-images.githubusercontent.com/22195362/132713863-79f292b2-a9d0-4201-8c47-b98d9600e451.png)

Maybe just try running to make sure it is up to date:
```
sudo apt install libc6
```

**Comment by lohnsonok** [comment]
> @lohnsonok The ubuntu machine that I have has GLIBC at 2.31. You can check by running `ldd --version`.
> 
> Ubuntu package repos also have `libc6` package at `2.31-0ubuntu9.2` (Check by running `apt-cache policy libc6`)
> ![image](https://user-images.githubusercontent.com/22195362/132713863-79f292b2-a9d0-4201-8c47-b98d9600e451.png)
> 
> Maybe just try running to make sure it is up to date:
> 
> ```
> sudo apt install libc6
> ```

same error

**Comment by janpio** [comment]
Did you resolve the problem @lohnsonok?

**Comment by lohnsonok** [comment]
> Did you resolve the problem @lohnsonok?

No. I think it relative to version 3 of prisma due to some openssl requirements
Version 2.30 working fine

**Comment by lohnsonok** [comment]
For a clear and understandable view, I have shared the captures of the last 3 versions

v.2.30.3
![Capture d’écran du 2021-09-11 13-33-31](https://user-images.githubusercontent.com/60504466/132948552-2233c8d3-a9e8-439a-a483-e08932a24ee5.png)

v.3.0.1
![Capture d’écran du 2021-09-11 13-40-19](https://user-images.githubusercontent.com/60504466/132948625-6424df5d-3e52-481a-9e67-b25912d8dd43.png)

v.3.0.2
![Capture d’écran du 2021-09-11 13-35-59](https://user-images.githubusercontent.com/60504466/132948671-c6404cd0-424c-4d33-aa5b-fd7969d65cd6.png)

As you can see, only version 2.30.3 works normally while the last two versions have the same problem. So I think the problem is related to prisma openssl engine

**Comment by janpio** [comment]
Yes, that makes sense. To confirm I will look up how we could enable Node-API in that version and then you can try that and see if that also caused the same problem already.

It does not seem to be very common, or we would have had more reports of that fortunately.

**Comment by lohnsonok** [comment]
Solved

> Yes, that makes sense. To confirm I will look up how we could enable Node-API in that version and then you can try that and see if that also caused the same problem already.
> 
> It does not seem to be very common, or we would have had more reports of that fortunately.

Solved by removing Snapd then reinstall nodejs latest without snap and it worked correctly

**Comment by pantharshit00** [comment]
@lohnsonok Awesome, I will keep this in mind if someone else reports this. Looks like snap is packaging node with an old glibc

**Comment by klausbadelt** [comment]
Removing snapd is not a solution - would have to remove lots of packages (1password, vscode, ffmpeg, gimp, mediaingo, remmina, subtitleedit, vlc... ) and reinstall from elsewhere.

Any other idea? This shouldn't be closed.

**Comment by klausbadelt** [comment]
Solved by `snap remove node`, then install node manually from [NodeSource](https://github.com/nodesource/distributions/blob/master/README.md#deb). I'm on Ubuntu 21.04.

**Comment by lohnsonok** [comment]
Ok, I reopen the issue for a better solution

**Comment by janpio** [comment]
Do you have a different suggestion what Prisma can do to fix a broken environment @klausbadelt? I do not really see an option here for us how we could fix this for our users unfortunately.

What might actually be useful, would be to try to switch to the binary engineType on a _broken_ system and let us know if the problem also appears there, of it is only affecting the library engineType: https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_cli_query_engine_type + https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#prisma_client_engine_type That would be pretty helpful.

**Comment by klausbadelt** [comment]
Switching back to the old engine "solves" it for us too.

**Comment by janpio** [comment]
Ok, so this is a "new" requirement for the Node-API library - which is not a good thing.

What is the easiest way to get a machine/image with the exact versions or setup that you are testing with?

**Comment by Brooooooklyn** [comment]
You could always build linux-gnu binary in `node:lts/node:lts-slim` image or `debian:9` to keep maximum compatibility.

**Comment by pantharshit00** [comment]
We don't have a reproduction but yeah as mentioned by @Brooooooklyn we can change our base image to improve compatibility. Something for @dpetrick to look into.

**Comment by startwarfields** [comment]
> Solved by `snap remove node`, then install node manually from [NodeSource](https://github.com/nodesource/distributions/blob/master/README.md#deb). I'm on Ubuntu 21.04.

Thank you!! This method worked to resolved my issue! 

I ran into a similar glibc error running Pop!_OS 22.04 LTS:
```sh
- error unhandledRejection: Error: Unable to require(`/home/orangeslices/Github/my-t3-app/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node`).
Prisma has detected an incompatible version of the `glibc` C standard library installed in your system. This probably means your system may be too old to run Prisma. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcrypto.so.3)
    at Gr.loadLibrary (/home/orangeslices/Github/my-t3-app/node_modules/@prisma/client/runtime/library.js:77:1075)
    at async Zt.loadEngine (/home/orangeslices/Github/my-t3-app/node_modules/@prisma/client/runtime/library.js:105:538)
    at async Zt.instantiateLibrary (/home/orangeslices/Github/my-t3-app/node_modules/@prisma/client/runtime/library.js:104:1838) {
  digest: undefined
}
```
 
I'm bumping this thread with details of my error to help future users 😄.

**Comment by genagurbanguliyev** [comment]
> Solved by `snap remove node`, then install node manually from [NodeSource](https://github.com/nodesource/distributions/blob/master/README.md#deb). I'm on Ubuntu 21.04.
Thank you so much ! This method resolved my issue !

**Comment by ripassorker2** [comment]
> > Solved by `snap remove node`, then install node manually from [NodeSource]
> > (https://github.com/nodesource/distributions/blob/master/README.md#deb). I'm on Ubuntu 21.04.
> 
> [#9174 (comment)](https://github.com/prisma/prisma/issues/9174#issuecomment-921558437)
> 
> Thank you!! This method worked to resolved my issue!
> 
> I ran into a similar glibc error running Pop!_OS 22.04 LTS:
> 
> ```shell
> - error unhandledRejection: Error: Unable to require(`/home/orangeslices/Github/my-t3-app/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node`).
> Prisma has detected an incompatible version of the `glibc` C standard library installed in your system. This probably means your system may be too old to run Prisma. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements
> 
> Details: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcrypto.so.3)
>     at Gr.loadLibrary (/home/orangeslices/Github/my-t3-app/node_modules/@prisma/client/runtime/library.js:77:1075)
>     at async Zt.loadEngine (/home/orangeslices/Github/my-t3-app/node_modules/@prisma/client/runtime/library.js:105:538)
>     at async Zt.instantiateLibrary (/home/orangeslices/Github/my-t3-app/node_modules/@prisma/client/runtime/library.js:104:1838) {
>   digest: undefined
> }
> ```
> 
> I'm bumping this thread with details of my error to help future users 😄.

thanks man,, it work...

**Comment by bmsptra24** [comment]
> Solved
> 
> > Yes, that makes sense. To confirm I will look up how we could enable Node-API in that version and then you can try that and see if that also caused the same problem already.
> > It does not seem to be very common, or we would have had more reports of that fortunately.
> 
> Solved by removing Snapd then reinstall nodejs latest without snap and it worked correctly

I use ubuntu 22.04.3, and this work for me, just install the current version of nodejs
in my case i use nvm to change the node version from `v.18` to `v.20`

_How to Update Node.js to Latest Version with nvm {Linux, Windows, and macOS}_
https://phoenixnap.com/kb/update-node-js-version

**Comment by JoshDLane** [comment]
I am on ubuntu 22.04 (deploying on railway.app) and coming across a similar issue. My attempts to install node manually haven't worked.
<img width="834" alt="Screen Shot 2023-09-25 at 4 14 13 PM" src="https://github.com/prisma/prisma/assets/65191963/5028f93c-7bd4-453c-b4e5-93df5f5dbce8">

**Comment by mahmudulmurad** [comment]
just upgrade node version into newest (v 20.xx.xx),

**Comment by isaac-svg** [comment]
Updating the node version to 20.x.x fixed my issue.
