### ISSUE TITLE
warn Prisma 2.12.0 has breaking changes.

### ISSUE THREAD

**Issue by PatElder** [prisma/prisma#9179]
### Bug description

When running npx prisma migrate deploy I get a warning message I did not receive in previous 2.3? release.

### How to reproduce

![image](https://user-images.githubusercontent.com/36389749/132579102-475dc76c-ba2d-4384-9907-4addbe111774.png)

### Expected behavior

No warning message

### Environment & setup

- OS:Windows 10
- Database: PostgreSQL
- Node.js version: 14.17.4

### Prisma Version

```

```
3.0.1

**Comment by janpio** [comment]
Thanks, also has been reported at https://github.com/prisma/prisma/issues/9171 and will be fixed soon.
