### ISSUE TITLE
ETIMEOUT during download of custom binaries

### ISSUE THREAD

**Issue by tobilg** [prisma/prisma#9186]
### Bug description

When running the following in our CI/CD processes, we often (not always!) receive an ETIMEOUT error:

```
$ npx prisma generate
Error: request to https://binaries.prisma.sh/all_commits/9b816b3aa13cc270074f172f30d6eda8a8ce867d/linux-musl/introspection-engine.gz.sha256 failed, reason: connect ETIMEDOUT 18.66.112.53:443
```

What the best way to mitigate this?

### How to reproduce

Our CI/CD process run this on every push. Sometimes it fails, sometimes it doesn't. We cannot really reproduce the problem.

### Prisma information

v2.26.0

### Environment & setup

Install in a Alpine Linux container, running in a CI/CD process. Node v14

### Prisma Version

```
prisma               : 2.26.0
@prisma/client       : 2.26.0
Current platform     : darwin
Query Engine         : query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 9b816b3aa13cc270074f172f30d6eda8a8ce867d
Studio               : 0.408.0
```

**Comment by janpio** [comment]
What is the "custom binaries" part of this isse? The URL you posted seems to be our usual CDN hosting our standard provided engine files.

**Comment by Jolg42** [comment]
I'll close this since it seems old and missing information.

Feel free to open a new issue if that happens with a more recent version of Prisma
