### ISSUE TITLE
Prisma does not support Mongodb SCRAM-SHA-256 authentication mechanism 

### ISSUE THREAD

**Issue by fuergaosi233** [prisma/prisma#9193]
### Bug description

My Db uses SCRAM-SHA-256 as the authentication mechanism. I can connect to it using Mongo Compass, but Prisma cannot connect.
![image](https://user-images.githubusercontent.com/22197568/132817137-988974ae-8ebf-437c-81ea-98ee24fdecc2.png)

### How to reproduce

1. set the environment variable `DATABASE_URL="mongodb://*****:*****@*.*.*.*:3051/message_db&authSource=message_db&authMechanism=SCRAM-SHA-256?authSource=message_db&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false"`
2. `npx prisma studio`
3. ![image](https://user-images.githubusercontent.com/22197568/132816938-42b07ab2-26e3-4e2a-b4bc-42e394d627a9.png)

### Prisma information

The normal operation
```
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 
OS: Debian
Database: Mongo
Node.js version: v14.17.5

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.0.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../../../../.npm/_npx/3091863/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../../../../.npm/_npx/3091863/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../../../../.npm/_npx/3091863/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../../../../.npm/_npx/3091863/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
Preview Features        : mongoDb
```

**Comment by matthewmueller** [comment]
Hey @fuergaosi233, thanks for opening this issue.

Just curious. Did you try it outside of Studio as well?

**Comment by pantharshit00** [comment]
I wasn't able to reproduce this. SCRAM is the default for mongodb so I don't really think we do not support this as the mongodb rust driver we use internally does support this. 

@fuergaosi233 Were you able to reproduce this when you trying to connect to your mongo db app using Prisma in code instead of studio?

**Comment by fuergaosi233** [comment]
![image](https://user-images.githubusercontent.com/22197568/141113027-3348d6ae-99a0-484c-9abe-603677d9fbc5.png)
I tried to link directly with the code and the query gives an error

**Comment by fuergaosi233** [comment]
> I wasn't able to reproduce this. SCRAM is the default for mongodb so I don't really think we do not support this as the mongodb rust driver we use internally does support this.
> 
> @fuergaosi233 Were you able to reproduce this when you trying to connect to your mongo db app using Prisma in code instead of studio?

By the way, I'm using  SCRAM-SHA-256 not SCRAM.

**Comment by fuergaosi233** [comment]
I think I found the problem.
![image](https://user-images.githubusercontent.com/22197568/141247294-7c285171-e304-40c6-90fa-c98415f3146f.png)
I change the & of my Url to ? then the service can be accessed normally.

**Comment by pantharshit00** [comment]
Yes, you specify parameters in the connection string format after `?` and join multiple of them using `&`. 

Looks like this is resolved then.
