### ISSUE TITLE
$queryRaw doesn't allow for typecasts

### ISSUE THREAD

**Issue by creativiii** [prisma/prisma#9197]
### Bug description

As suggested in the [discussion I opened](https://github.com/prisma/prisma/discussions/9190), I'm opening this as a possible bug.

Using variables in `$queryRaw` doesn't seem to allow for typecasts. Queries that work without variables fail with variables, this is especially a problem for **Postgres** functionality that requires typecasting like `generate_series`.

### How to reproduce

The following query will reproduce the problem.
```
      return await prisma.$queryRaw`
        SELECT
          d::date as key
        FROM generate_series(
          ${"2021-01-01 00:00:00"},
          ${"2021-01-31 00:00:00"},
          '1 day'
        ) AS gs(d)
        GROUP BY
          gs.d
        ORDER BY 
          d::date ASC
      `;
```

### Expected behavior

This should generate an array of dates between the two variables. It's extremely useful for graphs and the such.

If you run this with date strings, Postgres will complain about it:
```
function generate_series(unknown, unknown, unknown) is not unique\n' +
            'HINT: Could not choose a best candidate function. You might need to add explicit type casts.
```
`generate_series` does not work with date strings unless you specifically cast the strings to `timestamps`. Unfortunately if I try to do so in any of these ways:
```
${"2021-01-01 00:00:00"}::timestamp
CAST( ${"2021-01-01 00:00:00"} as timestamp)
```

The prisma query will fail with:
```
db error: ERROR: incorrect binary data format in bind parameter 1
```

Casting those variables works when using `$queryRawUnsafe`, so I assume the issue has something to do with the way variables are replaced.

### Prisma information

Query doesn't use live database data.

### Environment & setup

- OS: Windows with WSL
- Database: PostgreSQL
- Node.js version: 16.5.0

### Prisma Version

```
3.0.2
```

**Comment by Weakky** [comment]
Hey,

This issue was fixed by https://github.com/prisma/prisma-engines/pull/2847. It will be available in the next release under the `improvedQueryRaw` feature flag.

Beware that enabling `improvedQueryRaw` is a breaking change. Release notes will contain information as to how to upgrade (so will the documentation).

Thanks for reporting 🙏
