### ISSUE TITLE
Separate prisma files to manage models

### ISSUE THREAD

**Issue by hyochan** [prisma/prisma#92]
In `prisma1`, I used to import multiple datamodels in `prisma.yml` like below.
```
  - datamodel.prisma
  - datamodel2.prisma
  - datamodel3.prisma
```

How can I do this in `Prisma2` when there is only one file `project.prisma` when I generated the boilerplate. 

![image](https://user-images.githubusercontent.com/27461460/60642415-b3b1b280-9e6a-11e9-9561-93e802fdc12e.png)

**Comment by pantharshit00** [comment]
Hi,

It is the datamodel spec: https://github.com/prisma/rfcs/blob/0002-datamodel-2/text/0002-datamodel.md#multiple-prisma-in-the-same-directory-get


However, this hasn't been implemented yet.

**Comment by schickling** [comment]
@hyochan we've updated the schema spec with a concrete syntax proposal to support importing from other `.prisma` files. [You can see the spec here](https://github.com/prisma/specs/tree/master/prisma-schema#importing-schemas).

I've copied over the snippet for convenience. I'd love to hear your thoughts whether this is what you're looking for or whether you have other suggestions/requirements. 🙏 

**schema.prisma**
```
import "./post.prisma"

model User {
	posts Post[]
}
```

**post.prisma**

```
model Post {
	title String @pg.varchar(42)
	body  String
}
```

**Comment by steebchen** [comment]
Since the schema is global anyway, why not do it the v1 way and include multiple prisma files in the config and maybe even supporting globs? This should also be easier to implement, as the files just have to be joined together, no import/parsing/require/resolve stuff needed. I also think that with a huge schema it can get cumbersome to import several types, especially considering that the IDE/editor can't parse and help with those imports (for now I guess).

**Comment by matthewmueller** [comment]
Hey @steebchen!

So we're not planning on re-introducing the `prisma.yml` file for Prisma 2 because we want to have the option to consolidate all the Prisma-related configuration into one file. As I see it, this leaves us with the following options:

1.  Pass in schema file paths / globs via the CLI everywhere we need the schema (basically every command)
2. Introduce Go-style imports where folders gets concatenated together. We'd also need someway to bring in base schemas from other folders.
3. Introduce a `import "user.schema"` to the schema.

**Comment by HosseinAgha** [comment]
@matthewmueller could you explain how Go-style import work in this scenario?

**Comment by matthewmueller** [comment]
@HosseinAgha yep,

```
prisma/
  base.schema
  post/
    video.schema
    picture.schema
    text.schema
```

In this scenario, `post/video.schema`, `post/picture.schema`, `post/text.schema` would all be joined as one schema without any additional syntax, so you can reference models and types within the `post/` as if it's in one file.

We'd still probably need to introduce syntax to support things like `base.schema` importing the post package. 

Something like:

```groovy
import "./post"
```

Which would pull in the models from the whole `./post` directory.

**Comment by jmadson** [comment]
In addition to what @matthewmueller mentioned above, would it be possible to support doing the import in the format of a node glob string?
For example, if I were to organize my code into separate folders with one model per file:
```
models/person.prisma
models/address.prisma
...
```
Or into feature-specific "modules" directory of some sort:
```
modules/person/model.prisma
modules/person/object-type.ts
modules/address/model.prisma
modules/address/object-type.prisma
```

Then in the root `schema.prisma` file, it would be nice to be able to pull in all of the `*.prisma` files using a glob string such as:
`import models/*.prisma` or `import modules/**/*.prisma`

We have over 400 tables so splitting them out and then importing them with a single glob string would be ideal.

**Comment by Aperrix** [comment]
Still no news regarding the development of this feature or an alternative?
I love everything that has been done on prisma2, i would really like to migrate 😞

**Comment by scriptcoded** [comment]
The links to the docs above seem to be broken, and I can't seem to find any info about this in the docs. Is there any other information on this anywhere?

**Comment by EndyKaufman** [comment]
I write on nestjs and use modular architecture, i want separate prisma schema for each module, i want this feature :pray:

**Comment by emroot** [comment]
Ditto here.

**Comment by thebigredgeek** [comment]
Any updates here?

**Comment by albertoperdomo** [comment]
Hello everyone!

the original request is to bring back the option of loading multiple PSL files via a YAML config file, the way it was handled in Prisma 1.

We are planning to enable having multiple schema files, but we don't know which implementation path we may end up choosing.

I've created #2377 to describe the high-level problem and I'll be closing this issue. Feel free to subscribe to #2377 to keep track of its progress and for feedback. 🙏

**Comment by bdombro** [comment]
I'm using this bash script to implement modularization, which seems pretty simple to me. It basically just builds a schema using grok.

```
#!/bin/bash

DEST=schema.prisma

# Ensure we are in this files directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

echo "// This file generated by schemaGen.sh" > $DEST
cat datasource.prisma >> $DEST
find ../src -type f -name "*.prisma" -exec cat {} >> $DEST \;

echo "SUCCESS: Prisma Schema Generated"
```

**Comment by maxgfr** [comment]
+1

**Comment by nikita-fuchs** [comment]
Two years later, a team of 10 still has to mess around in 1 schema file. What could possibly go wrong.

**Comment by marcelinhov2** [comment]
`cat` command did the tricky for me.

![image](https://user-images.githubusercontent.com/232648/124980562-eb7c0380-e00a-11eb-9adb-6469ebeabd37.png)
![image](https://user-images.githubusercontent.com/232648/124980587-f33ba800-e00a-11eb-9fc0-c9c311bd984a.png)

just run `cat src/prisma/docs.prisma src/prisma/schema.prisma > src/prisma/schema.prisma.new && mv src/prisma/schema.prisma.new src/prisma/schema.prisma` before `prisma generate` command.

**Comment by deyvisonborges** [comment]
`package.json`
```bash
  "scripts": {
    "gen:schema": "cd ./prisma/schemas && cat *.prisma >> ../schema.prisma && npx prisma format"
  }
```
![image](https://user-images.githubusercontent.com/35538358/157167095-dc5acf62-565a-45e3-8f52-d25a6b65951e.png)

**Comment by khuezy** [comment]
> `package.json`
> 
> ```shell
>   "scripts": {
>     "gen:schema": "cd ./prisma/schemas && cat *.prisma >> ../schema.prisma && npx prisma format"
>   }
> ```
> 

Thanks! Probably want to use the single ">" right? Otherwise it'll amend the same models.

**Comment by deyvisonborges** [comment]
@khuezy 
`>` redirects output to a file, overwriting the file.

`>>` redirects output to a file appending the redirected output at the end.

**Comment by khuezy** [comment]
But if you ran the script 2x, you'd get duplicate entries and `prisma format` would complain.
This also doesn't work too well if you have the prisma VSCode extension b/c it'll complain that `String[]`: "The current connector does not support lists of primitive types" because of the missing  datasource db provider.

**Comment by bdombro** [comment]
@khuezy you need to use '>>' so that the files are combined. Otherwise they would overwrite each other. You'd prob want to delete the file first so that old entries are cleared. Also, if you run it and leave the schema VS should be happy I would think.

```
"scripts": {
    "gen:schema": "cd ./prisma/schemas && rm -rf ../schema.prisma && cat *.prisma >> ../schema.prisma && npx prisma format"
  }
```

**Comment by khuezy** [comment]
`cat *.prisma > ../schema.prisma` would combine all the .prisma content into a single `schema.prisma` file, so you wouldn't need to delete the `schema.prisma` file right? Or am I missing something.

I ended up moving all my models into a single `schema.prisma` until prisma adds support for separate files. I was still getting syntax errors in VSCode.

**Comment by bdombro** [comment]
You may be right

**Comment by deyvisonborges** [comment]
other method
`awk 1 ./prisma/schemas/*.prisma >> ./prisma/schema.prisma && npx prisma format`

**Comment by RafaelKr** [comment]
> other method `awk 1 ./prisma/schemas/*.prisma >> ./prisma/schema.prisma && npx prisma format`

@deyvisonborges as already stated by @khuezy above you should use `>` instead of `>>`
`>>` will **append** the output to an existing file. So if you run it 5 times you will have all models 5 times in your schema.prisma.
`>` will **"overwrite"** the contents of schema.prisma <= this is what you want.

There is a detailed description of output redirection: https://linuxhandbook.com/redirection-linux/

**Comment by leafyshark** [comment]
@matthewmueller is this something in the pipeline?

**Comment by btd1337** [comment]
```
// directory structure

prisma
  |_ schemas
  |   |_ client.prisma
  |   |_ db.prisma
  |   |_ model1.prisma
  |   |_ model2.prisma
  |   |_ model3.prisma
  |_ schema.prisma
```

```json
// package.json

{
  "scripts": {
    "gen:schema": "awk 1 ./prisma/schemas/*.prisma > ./prisma/schema.prisma && npx prisma format",
  }
}
```

> Single `>` character to recreate `schema.prisma` file without duplicate over the next generates

**Comment by btd1337** [comment]
```
// directory structure

prisma
  |_ schemas
  |   |_ client.prisma
  |   |_ db.prisma
  |   |_ model1.prisma
  |   |_ model2.prisma
  |   |_ model3.prisma
  |_ schema.prisma
```

```json
// package.json

{
  "scripts": {
    "gen:schema": "awk 1 ./prisma/schemas/*.prisma > ./prisma/schema.prisma && npx prisma format",
  }
}
```

> Single `>` character to recreate `schema.prisma` file without duplicates over the next generates

**Comment by Nomia** [comment]
> ```
> // directory structure
> 
> prisma
>   |_ schemas
>   |   |_ client.prisma
>   |   |_ db.prisma
>   |   |_ model1.prisma
>   |   |_ model2.prisma
>   |   |_ model3.prisma
>   |_ schema.prisma
> ```
> 
> ```json
> // package.json
> 
> {
>   "scripts": {
>     "gen:schema": "awk 1 ./prisma/schemas/*.prisma > ./prisma/schema.prisma && npx prisma format",
>   }
> }
> ```
> 
> > Single `>` character to recreate `schema.prisma` file without duplicates over the next generates

but, how do u relate each other if there is relation between in different files?

**Comment by mdarifulislamroni521** [comment]
Any official updates here?

**Comment by janpio** [comment]
The feature request is being tracked here: https://github.com/prisma/prisma/issues/2377
