### ISSUE TITLE
On database reset in a new project, I get a seeding configuration warning

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9203]
I have a new project. Running `migrate dev` detects drift, and prompts me to reset the database. If I do, I get a seed warning by default:

````
C:\Users\Jan\Documents\throwaway\sethRepro>npx prisma migrate dev --create-only
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "fancy.db" at "file:./fancy.db"

√ Drift detected: Your database schema is not in sync with your migration history.

...


We need to reset the SQLite database "fancy.db" at "file:./fancy.db".
Do you want to continue? All data will be lost. ... yes

prisma:warn To configure seeding in your project you need to add a "prisma.seed" property in your package.json with the command 
to execute it:

1. Open the package.json of your project
2. Add one of the following examples to your package.json:

TypeScript:
```
"prisma": {
  "seed": "ts-node ./prisma/seed.ts"
}
```
And install the required dependencies by running:
npm i -D ts-node typescript @types/node

JavaScript:
```
"prisma": {
  "seed": "node ./prisma/seed.js"
}
```

Bash:
```
"prisma": {
  "seed": "./prisma/seed.sh"
}
```
And run `chmod +x prisma/seed.sh` to make it executable.
More information in our documentation:
https://pris.ly/d/seeding

? Enter a name for the new migration: »
````

I think this is unexpected and should probably not be shown via implicit seeding.

**Comment by tomhoule** [comment]
I am still seeing this with `3.2.0-dev.48` (which I think includes the commit above).	****

**Comment by Jolg42** [comment]
Weird, I'll try to reproduce then

**Comment by Jolg42** [comment]
@tomhoule do you have a reproduction case? I can't reproduce.

**Comment by Jolg42** [comment]
This was a case where it happened and it doesn't anymore (legacy seed) https://github.com/prisma/prisma/pull/9484/files#diff-c266a026f47d4de125b7139076b575b33fb6dcb0207110c4a9a0f78304097b41L812-L855

**Comment by tomhoule** [comment]
I made a repro in this repository: https://github.com/prisma/migrate-dev-reset-message-repro

**Comment by Jolg42** [comment]
Turns out it's also showing with `migrate reset`, I'll remove as well there like for dev

**Comment by Jolg42** [comment]
@tomhoule out in latest dev `3.2.0-dev.52`
