### ISSUE TITLE
Unable to initialize a new migration history

### ISSUE THREAD

**Issue by ihassanalattas** [prisma/prisma#9206]
### Bug description

I'm facing a problem when I want to connect the local postgreSQL db to initialize a new migration history

.env file :
`DATABASE_URL="postgresql://hassan:123@localhost:5432/prismadb?schema=public"`

schema.prisma file :

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

```

```
"dependencies": {
    "@prisma/client": "2.30.3",
    "prisma": "2.30.3"
  },

```

`npx prisma -v `
`Environment variables loaded from .env
prisma                : 2.30.3
@prisma/client        : 2.30.3`

`npx prisma migrate dev --name init`

```
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "prismadb", schema "public" at "localhost:5432"

Error: P3014

Prisma Migrate could not create the shadow database. Please make sure the database user has permission to create databases. Read more about the shadow database (and workarounds) at https://pris.ly/d/migrate-shadow

Original error: 
Database error
Error querying the database: db error: ERROR: permission denied to create database

   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:375
   1: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:89
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v12.20.0

### Prisma Version

```
2.30.3
```

**Comment by janpio** [comment]
> Prisma Migrate could not create the shadow database. Please make sure the database user has permission to create databases. Read more about the shadow database (and workarounds) at https://pris.ly/d/migrate-shadow

Did you read the error message, follow the link and do what it tells you to do? That should fix the problem.

**Comment by ihassanalattas** [comment]
Thanks , this fix the problem

```
postgres=# ALTER ROLE hassan CREATEDB;
ALTER ROLE
```
I had only had LOGIN option.
