### ISSUE TITLE
[Feature request] Seeding with arguments

### ISSUE THREAD

**Issue by SevenOutman** [prisma/prisma#9212]
## Problem

I have a seeding process that involves several tables. Sometimes my seeding process may fail due to flaky scripts, and after I fixed the scripts, I want to re-run the seeding but don't run those tables which are already seeded.

## Suggested solution

Maybe the seed command can receive arguments which are passed to the seeding script so that I can control what to do in the seeding process.

For example,

    prisma db seed --skip-users

And I get

```ts
interface SeedInput {
  skipUsers?: boolean;
}

async function seed(input: SeedInput) {
  if (!input.skipUsers) {
    await seedUsersTable();
  }
}
```

**Comment by jackHedaya** [comment]
As of prisma 3.0, the `seed` command simply calls `"prisma"."seed"` in `package.json`. This means you could make your custom seeding file as a Node script that accepts arguments, just as you described.

**Comment by pantharshit00** [comment]
Yes, as mentioned by @jackHedaya seeding system was redesigned in 3.0 so that it can allow more flexibility. 

Read more about it in the release notes: https://github.com/prisma/prisma/releases/tag/3.0.1
