### ISSUE TITLE
Test with MongoDB 4.0

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#9231]
Try it and if you get stuck, let us know.

Another consideration: Most people rely on Atlas, which heavily update their MongoDB distribution. Developers need to keep up.

**Comment by tomhoule** [comment]
Migration and introspection engine test suites are passing. The query engine test suite fails with a bunch of `[2022-02-21T16:38:07Z] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ServerSelection { message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: test-db-mongodb-4-0:27015, Type: Unknown, Error: Connection refused (os error 111) }, ] }" }, labels: {} }', /root/build/migration-engine/qe-setup/src/mongodb.rs:17:10`.

For the full logs with the errors and which tests failed: https://buildkite.com/prisma/test-prisma-engines/builds/12507#13e469aa-0360-4ce7-a387-c8ab57d8fd9c

**Comment by tomhoule** [comment]
Branch: https://github.com/prisma/prisma-engines/pull/2708

**Comment by tomhoule** [comment]
@janpio I think we can close this one. The conclusion is that we support 4.2 and up, if I am not mistaken.

**Comment by Jolg42** [comment]
This is what we document (4.2+)
https://www.prisma.io/docs/reference/database-reference/supported-databases
