### ISSUE TITLE
Downgrading from v3 yields a generate error

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#9251]
### Bug description

When doing the upgrade to v3, I found that downgrading from v3 to v2.26 yields an error. This is super important but can be annoying for the small time where you are upgrading to v3. This happened in yarn classic monorepo with one package containing the prisma and generating it for two other packages.

```
$ yarn workspace my-workspace prisma generate
yarn workspace v1.22.5
yarn run v1.22.5
$ prisma generate
Prisma schema loaded from prisma/schema.prisma
Error: Could not convert engine type libqueryEngine
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/Sytten/.nvm/versions/node/v14.17.6/bin/node
Arguments: /usr/local/Cellar/yvm/4.1.4/versions/v1.22.5/lib/cli.js prisma-generate
Directory: /Users/Sytten/Projects/my-project/packages/my-workspace
```

You have to delete the node_modules (or at least the prisma folder) manually to make it work.

### How to reproduce

1. Upgrade to v3
2. Run yarn
3. Downgrade to v2.26
4. Run yarn
5. Try to generate

### Expected behavior

Works without issue

### Environment & setup

- OS: MacOS
- Database: Postgres
- Node.js version: 14.17.6

**Comment by Sytten** [comment]
Meaning changing the version in `package.json` from `3.0.2` back to `2.26.0` and rerunning yarn.

**Comment by pantharshit00** [comment]
I wasn't able to reproduce on my test attempt. Did you add `engineType` to your schema by any chance after upgrading?

**Comment by chaostheory** [comment]
I'm not sure whether or not to create a new issue, but I'm experiencing this problem after I upgraded from 2.x to 3.x. 

- I also do not have an engineType declared in my schema. 
- Other commands like format still work fine.
- I only had this error "_Could not convert engine type libqueryEngine_"
- I use npm and not yarn

**Comment by Sytten** [comment]
My solution was to delete node_modules and it went away. Bit annoying but yeah :/

**Comment by chaostheory** [comment]
@Sytten Thanks for the help, but unfortunately that didn't work in my case

This is literally my entire schema.

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "sqlite"
  url      = "file:./test.db"
}

generator client {
  provider = "prisma-client-js"
}

model Patrol {
  id              Int                         @id @default(autoincrement())

  createdAt       DateTime                    @default(now())
  lastUpdatedAt   DateTime                    @default(now())
}
```

My sqlite database is also empty. Everything worked fine before the installing version 3

**Comment by pantharshit00** [comment]
@chaostheory Can you share a git repo with a minimal reproduction? That would help here a lot.

**Comment by pantharshit00** [comment]
I think this is not relevant anymore.
