### ISSUE TITLE
Error opening a TLS connection.

### ISSUE THREAD

**Issue by jebnascimento** [prisma/prisma#9258]
### Bug description

```
Error: P1011

Error opening a TLS connection: The TLS settings didn't allow the connection to be established. Please review your connection string. (error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1913: (self signed certificate))
```

### How to reproduce

After running:  
`npx prisma db pull
`
### Expected behavior

pull all the tables out from database and populate `schema.prisma`

### Prisma information

```
datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

`DATABASE_URL="sqlserver://localhost:1401;database=bdccr;user=SA;password=myPassword;encrypt=true"
`

### Environment & setup

- OS: SQL Server running on Docker(mcr.microsoft.com/mssql/server:2017-latest)
- Database: SQL Server
- Node.js version: v14.17.6

### Prisma Version

```
3.0.2
```

**Comment by pimeys** [comment]
Can you try to add `TrustServerCertificate=true` to the connection string?

**Comment by jebnascimento** [comment]
> Can you try to add `TrustServerCertificate=true` to the connection string?

that worked man, thank you!!

**Comment by pimeys** [comment]
Yep, so we should focus a bit of documenting common TLS issues. What happened here is how we, by default, do not trust a certificate the server gives us, which is a safe default. When connecting to a local server, the certificate by definition is not valid. This means the TLS library gives us an error. You can of course connect with the `TrustServerCertificate` set to `true`, dictating that yes, I do trust this certificate, and the connection should be working after that.

**Comment by victormatia** [comment]
> Can you try to add `TrustServerCertificate=true` to the connection string?

Thanks very much man, I was having this problem for hours.

**Comment by temrb** [comment]
this can also happen if your db instance was autopaused
