### ISSUE TITLE
Prisma Migrate crashed

### ISSUE THREAD

**Issue by fh17488** [prisma/prisma#9296]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db push --schema ./src/prisma/schema.prisma`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.17.0           | 
| Prisma CLI  | 3.0.2              | 
| Binary      | 2452cc6313d52b8b9a96999ac0e974d0aedf88db| 

## Error
```
Error: Error in migration engine.
Reason: Starting migration engine RPC server
Performing a TLS handshake
Trusting the server certificate without validation.
TLS handshake successful
Turning TLS off after a login. All traffic from here on is not encrypted.
Database change from 'CenturionDevV2' to 'master'
Changed database context to 'CenturionDevV2'.
SQL collation change from None to windows-1252/windows-1252
Microsoft SQL Server�� version 957349903
Packet size change from '4096' to '4096'
Starting a mssql connection.

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

**Comment by janpio** [comment]
Any other information available? Is this reproducible?
Can you enabled logging and debugging to see if other interesting information is output? https://pris.ly/d/logging + https://pris.ly/d/debugging

**Comment by tomhoule** [comment]
Candidating this also for us to fix the error message (it's the engines error message + all the logs, it should be just the error message).

**Comment by tomhoule** [comment]
The migrations team will wait for a repro for now

**Comment by janpio** [comment]
Here is a reproducible instance of the to elaborate error message: https://github.com/prisma/prisma/issues/10138

**Comment by Jolg42** [comment]
Closing as we don't have any info to reproduce and we track the improvement for the error message in https://github.com/prisma/prisma/issues/10138
