### ISSUE TITLE
Naming an entity "Query" leads to an error

### ISSUE THREAD

**Issue by dirk-hofmann** [prisma/prisma#9307]
### Bug description

Naming an entity "Query" in prisma.schema leads to an error when trying to start such a project. The console output will not contain clear information about what's wrong. The auto-generated file _\node_modules\.prisma\client\index.d.ts_ contains errors after naming an entity "Query".

### How to reproduce

1. Set up the prisma quickstart project [https://www.prisma.io/docs/getting-started/quickstart](https://www.prisma.io/docs/getting-started/quickstart) 
2. In schema.prisma, change the name of the entity "Post" to "Query" wherever it occurs
3. Run a migration (that regenerates the client as well)
4. Run "npm run dev" and see the console error output
5. open \node_modules\.prisma\client\index.d.ts and see the TypeScript errors

### Expected behavior

The app starts without error and outputs an empty array to the console since it's the prisma quickstart project with an empty database (after our migration).

### Prisma information

[schema.prisma.txt](https://github.com/prisma/prisma/files/7186264/schema.prisma.txt)

### Environment & setup

I have run into this error on Windows 10, Node 14.17.6 and Prisma 3.0.2

### Prisma Version

```
Prisma 3.0.2
```

**Comment by SevInf** [comment]
This issue is fixed and will be available in Prisma 5.1
