### ISSUE TITLE
`db pull --url` with connection string containing `&` leads to unexpected executed of query param as program

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9312]
This is a weird observation:

On Windows, `npx prisma db pull --url "mysql://localhost:1234/database?foo=1&bar=2"` leads to the following output:

```
λ npx prisma db pull --url "mysql://localhost:1234/database?foo=1&bar=2"

Introspecting …
Error: P1001

Can't reach database server at `localhost`:`1234`

Please make sure your database server is running at `localhost`:`1234`.

'bar' is not recognized as an internal or external command,
operable program or batch file.
```

Why does it try to execute `bar`? Is this something on the terminal level, or something Prisma does?

**Comment by pantharshit00** [comment]
@janpio Which shell you are using? I wasn't able to reproduce with my terminal setup on windows.

**Comment by janpio** [comment]
`cmd.exe` has this for me:
```
C:\Users\Jan\Documents>cmd -v

Microsoft Windows [Version 10.0.19043.1237]
(c) Microsoft Corporation. All rights reserved.
```

**Comment by pantharshit00** [comment]
Can't reproduce on cmd either:
![image](https://user-images.githubusercontent.com/22195362/135838918-424d0434-1ad0-4097-b114-22aa7513a99d.png)

**Comment by janpio** [comment]
Both cmd.exe and via Windows Terminal:
![image](https://user-images.githubusercontent.com/183673/135874738-a817e0d4-30d2-41ab-be83-c16c9b9e35db.png)
![image](https://user-images.githubusercontent.com/183673/135874774-74aea83f-708f-4297-ac71-d203991b80ff.png)
