### ISSUE TITLE
Using datasource property that requires preview feature, highlights only value and not property in validation error

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9314]
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  planetScaleMode = true
}

generator client {
  provider = "prisma-client-js"
  
}
```

leads to:

```
C:\Users\Jan\Documents\throwaway\7722>npx prisma validate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: Schema parsing
error: Error validating datasource `db`: 
The `planetScaleMode` option can only be set if the preview feature is enabled in a generator block.

Example:

generator client {
    provider = "prisma-client-js"
    previewFeatures = ["planetScaleMode"]
}

  -->  schema.prisma:7
   | 
 6 |   url      = env("DATABASE_URL")
 7 |   planetScaleMode = true
   | 

Validation Error Count: 1
```

![image](https://user-images.githubusercontent.com/183673/133851289-cb400338-4e95-4726-8be2-150f4befeb32.png)
![image](https://user-images.githubusercontent.com/183673/133851313-49d14232-c481-4eb4-a0fb-05d074f74288.png)

More correct would be to also highlighting and underlining the `planetScaleMode` property itself.

**Comment by pantharshit00** [comment]
@janpio We removed the planetscale flag in favor of the new referential integrity flag. I wonder if this issue is still relevant?

**Comment by janpio** [comment]
I assume the same logic error will apply to any data source property that requires a preview feature in the generator block to be valid.
