### ISSUE TITLE
Allow for User Specified JSON Types in TypeScript

### ISSUE THREAD

**Issue by fny** [prisma/prisma#9319]
## Problem

When a model is created with a JSON field, the generated TypeScript returns the type `Prisma.JsonArray` or `Prisma.Json`. As a dev, I'd like to be able to specify my own type at the ORM level rather than type cast manually every time I interact with that model through Prisma.

```
model Post {
  id Int @id @defualt(autoincrement())
  data Json
}
```

## Suggested solution

```
new PrismaClient<{ Post: { data: PostData } }>()
```

## Alternatives

```
model Post {
  id Int @id @defualt(autoincrement())
  data Json @typescript(PostData)
}
```

## Other Context

I know the above answer is contrived, but suffice it to say it's reasonable to want typing for JSON fields! Thanks for the awesome library.

**Comment by janpio** [comment]
Would this be covered by something like https://github.com/prisma/prisma/issues/3219 as well?

**Comment by fny** [comment]
Same issue, different solutions. I'll close and suggest the changes there.
