### ISSUE TITLE
Raw query failed when trying to insert batch of data

### ISSUE THREAD

**Issue by PedramRZM** [prisma/prisma#9326]
### Bug description

I have a `rawInsert` function which is in charge of executing a raw query to insert multiple rows in a table. Function header looks like this: 

`export default async <T extends Record<string, any>>(
  table: string,
  fields: DistributiveKeyof<T>[],
  values: T[],
  opts?: { onConflict?: { target: (keyof T)[]; action: 'update' } },
): Promise<number>`

When I try to load test my API  using [k6](https://k6.io) this function throws an error. This error happens when my batch size gets more than ~5000 rows.
Error:
```
Raw query failed. Code: `N/A`. Message: `N/A`
```

### How to reproduce

1. generate a query like below and execute it using `executeRaw`. make sure you insert more than 5000 rows in this query.
`INSERT INTO table_name (col1, col2, col3, col4, col5, col6)
VALUES
    ($1, $2, $3, $4, $5, $6),
    ($7, $8, $9, $10, $11, $12),
    ...`
2. run a load test over this query using [k6](https://k6.io). iterating through this also reproduces this error.
3. run the exact same query using `pg` driver and everything is working just fine.

### Expected behavior

To have a clear error message and insert all of my batch data rows into table.

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["selectRelationCount"]
}

datasource db {
  provider = "postgresql"
}
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version :v14.17.6

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : Not found
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../.npm/_npx/52649/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../.npm/_npx/52649/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../.npm/_npx/52649/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../.npm/_npx/52649/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by pantharshit00** [comment]
Hello,

Can you please share an exact reproduction with us? I tried a simplified load test setup but wasn't able to reproduce this.

Also, it won't hurt if you can try again with the latest version of Prisma.

**Comment by PedramRZM** [comment]
Hey

This problem happens when I want to insert 10K rows or more back to back using raw query. One simple way to reproduce this error is to insert 10k+ rows using raw query in a for loop.

I will try again with the latest version and I will let you know.

Thanks

**Comment by PedramRZM** [comment]
Hello
so forget about load test it was a bit confusing.
create an array of objects with more than 5000 items in it. then try inserting those 5000 rows using raw query. this error should be reproduced.

updating Prisma to its latest version didn't help.

**Comment by millsp** [comment]
I can reproduce this with the following code
```ts
async function main() {
    const prisma = new PrismaClient({
      log: ["query"],
    })

    let insertValues = Prisma.sql`INSERT INTO "public"."Resource" ("fieldA", "fieldB", "fieldC", "fieldD", "fieldE", "fieldF") VALUES (${0}, ${0}, ${0}, ${0}, ${0}, ${0})`
    
    for (let i = 0; i < 5500; i++) {
      insertValues = Prisma.join([insertValues, Prisma.sql`(${0}, ${0}, ${0}, ${0}, ${0}, ${0})`], ',')
    }

    await prisma.$executeRaw(insertValues)
  }
```

If you log the query, you can see that the amount of parameters for the prepared statement is exceeded:
```
...854, $32855, $32856),($32857, $32858, $32859, $32860, $32861, $32862),($32863, $32864, $32865, $32866, $32867, $32868),($32869, $32870, $32871, $32872, $32873, $32874),($32875, $32876, $32877, $32878, $32879, $32880),($32881, $32882, $32883, $32884, $32885, $32886),($32887, $32888, $32889, $32890, $32891, $32892),($32893, $32894, $32895, $32896, $32897, $32898),($32899, $32900, $32901, $32902, $32903, $32904),($32905, $32906, $32907, $32908, $32909, $32910),($32911, $32912, $32913, $32914, $32915, $32916),($32917, $32918, $32919, $32920, $32921, $32922),($32923, $32924, $32925, $32926, $32927, $32928),($32929, $32930, $32931, $32932, $32933, $32934),($32935, $32936, $32937, $32938, $32939, $32940),($32941, $32942, $32943, $32944, $32945, $32946),($32947, $32948, $32949, $32950, $32951, $32952),($32953, $32954, $32955, $32956, $32957, $32958),($32959, $32960, $32961, $32962, $32963, $32964),($32965, $32966, $32967, $32968, $32969, $32970),($32971, $32972, $32973, $32974, $32975, $32976),($32977, $32978, $32979, $32980, $32981, $32982),($32983, $32984, $32985, $32986, $32987, $32988),($32989, $32990, $32991, $32992, $32993, $32994),($32995, $32996, $32997, $32998, $32999, $33000),($33001, $33002, $33003, $33004, $33005, $33006)

Invalid `prisma.$executeRaw()` invocation:


Raw query failed. Code: `N/A`. Message: `N/A`
```

This is normal because ``` queryRaw`...` ``` uses prepared statement, and I assume `pg` does not. You can use `executeRawUnsafe`, but it does not prevent sql injection. The amount of prepared statement parameters is limited to about 32000 on Postgres. We should probably surface a better error message.

**Comment by millsp** [comment]
Internal conversation https://prisma-company.slack.com/archives/C040N0UADF0/p1662679627797069
Reproduction https://github.com/prisma/prisma/pull/15246
Todo Update snapshots once fix landed in the engines

**Comment by jkomyno** [comment]
Hi, we discovered this issue was due to a validation check in the Postgres driver we use that we didn't expect.
Specifically, even though prepared statements in Postgres support up to `65535` parameters (also known as bind variables), the driver we currently use supports half that parameters (one can create prepared SQL statements in Prisma via e.g. `$executeRaw` and `$queryRawUnsafe`).
This caused us to fall back to the generic error message:

> Raw query failed. Code: `N/A`. Message: `N/A`

With the latest release, `prisma@4.4.0`, we now show a clearer error message (with error code `P2035`) when the Prisma client prepares more than `32767` bind variables:

> Assertion violation on the database: `too many bind variables in prepared statement, expected maximum of 32767, received ...`

Thus, we now consider this issue solved.

## Example

Given this schema:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

model Tag {
  id Int @id
  @@map("tag")
}
```

Here's an example of a query that fails with error code `P2035` due to hitting the maximum amount of bind variables:

```ts
const n = 32768

// [1, 2, ..., 32768]
const ids = Array.from({ length }, (_, i) => i + 1)

const data = ids.map((id) => ({ id }))
await prisma.tag.createMany({
  data,
})

// ['$1', '$2', ..., '$32768']
const idsParams = ids.map((paramIdx) => `\$${paramIdx}`)

const tags = await prisma.$queryRawUnsafe<unknown[]>(
  `
  SELECT *
  FROM tag
  WHERE "id" IN (${idsParams.join(', ')})
`,
  ...ids,
)

expect(tags.length).toBe(n)
```

The same query with `n <= 32767` succeeds.

**Comment by acosonic** [comment]
I am getting N/A on MySQL when I run query which returns lots of rows, and it works only if I add LIMIT or use LIMIT and OFFSET to fetch my data...
