### ISSUE TITLE
Prisma should check for generator binaries in $PATH

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#934]
When writing custom generators, you can specify an absolute or relative binary path for the "provider" value. However, the path resolution does not respect binaries in $PATH, which would make things easier for custom generators, because they can depend on globally installed binaries.

The following generator configuration does not work:

```groovy
generator photon {
	provider = "photongo"
	output = "./photon/photon_gen.go"
	package = "photon"
}
```

![image (1)](https://user-images.githubusercontent.com/5013932/68789333-88737700-0645-11ea-900d-f34f05ac00a5.png)

**Comment by matthewmueller** [comment]
internal note: dropping for now

**Comment by janpio** [comment]
Internal Note: Dropping from current sprint, and picking up later.
