### ISSUE TITLE
Deprecated model fields

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#9343]
## Problem

Want to deprecate model fields:

```prisma
model Foo {
  a String // <-- deprecated
}
```

So that in TS they are shown as deprecated or simply hidden from the API completely.

## Suggested solution

```prisma
model Foo {
  a String @deprecated(description: "...", effect: hidden | deprecated)
}
```

- `description` Allows human readable instructions on what developers should do now.
- `description` should be optional
- `effect` Allows removing the field from PC api OR just emitting `@deprecated` onto the field (letting  the IDE warnings kick in).
- `effect` default should be `deprecated`
- Make this available in the DMMF so tools like Nexus Prisma can take advantage

## Alternatives

🤷‍♂️

## Additional context

This is useful in multi-phase migrations. We ship a commit that stops using the deprecated db column. Then in another commit we do the final db column removal (migration).

**Comment by janpio** [comment]
More popular issue: https://github.com/prisma/prisma/issues/13027
