### ISSUE TITLE
Prisma incorrectly exiting process on SIGUSR1

### ISSUE THREAD

**Issue by jaridmargolin** [prisma/prisma#9345]
### Bug description

According to the [Node.js documentation on signal events](https://nodejs.org/dist/latest-v16.x/docs/api/process.html#process_signal_events), prisma is incorrectly calling [`process.exit()` on`SIGUSR1`](https://github.com/prisma/prisma/blob/2333361757714c00c53cc1c01587af93eaf1a54e/packages/engine-core/src/library/LibraryEngine.ts#L736).

> 'SIGUSR1' is reserved by Node.js to start the debugger. It's possible to install a listener but doing so might interfere with the debugger.

### How to reproduce

Call the [undocumented `process._debugProcess(process.pid)`](https://remysharp.com/2018/03/03/last-minute-node-debugging#turning-on-the-debugger-on-a-running-node-process) after instantiating a PrismaClient instance. 

### Expected behavior

Based on my interpretation of the Node.js documentation, I believe the `SIGUSR1` listener should be removed from `initHooks`.

### Prisma information

N/A

### Environment & setup

- OS: macOS
- Node.js version: v16.9.1

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../../node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../../node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by janpio** [comment]
Related code:
- https://github.com/prisma/prisma/blob/2333361757714c00c53cc1c01587af93eaf1a54e/packages/engine-core/src/library/LibraryEngine.ts#L736
- https://github.com/prisma/prisma/blob/2333361757714c00c53cc1c01587af93eaf1a54e/packages/engine-core/src/binary/BinaryEngine.ts#L1275

**Comment by pantharshit00** [comment]
I agree with @jaridmargolin and marking this as a confirmed bug.
