### ISSUE TITLE
_count not being detected by TS (prior Prisma 3)

### ISSUE THREAD

**Issue by zomars** [prisma/prisma#9348]
The problem still exists here. I have already changed the prism version to previous versions, and in all of them I ran the command `npx prisma generate`

package.json
```json
// ...
"dependencies": {
    "@prisma/client": "^2.29.1",
},
"devDependencies": {
    "prisma": "^2.29.1",
}
```

prisma/schema.prisma
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["selectRelationCount"]
}

// ...
```

![image](https://user-images.githubusercontent.com/21183964/130382686-1e07921b-67a5-4f15-b8fc-cd3d8a451812.png)

_Originally posted by @BrunoS3D in https://github.com/prisma/prisma/issues/6856#issuecomment-903399364_

**Comment by zomars** [comment]
Another example: 

![image](https://user-images.githubusercontent.com/3504472/134097798-4ce06203-947e-412a-b2cc-0f2eb4b6bf78.png)

**Comment by pantharshit00** [comment]
Hmm, I wasn't able to reproduce this with 3.1. Can you please try again ?

**Comment by pikiaboy** [comment]
![image](https://user-images.githubusercontent.com/9708708/151510045-9cba4cfa-e7e5-43ad-bda2-f47b8b342510.png)

You have to up your version of prisma.

**Comment by zomars** [comment]
@pikiaboy you can see that my config should work since I'm using `2.29.1` and with the `selectRelationCount` preview feature enabled.

**Comment by janpio** [comment]
@zomars Can you try this with a newer version of Prisma please as @pantharshit00 asked? Thanks.

**Comment by zomars** [comment]
3.0 and up works just fine. But we should remove from the docs that it works for v2.20 and up if that's the case.

**Comment by janpio** [comment]
Thanks, knowing it works now of course lowers the priority for us to prioritize a lot.

Updating the documentation is a fair suggestion.

**Comment by millsp** [comment]
Ping @andrew-walford-prisma @tanberry

**Comment by andrew-walford-prisma** [comment]
I'll update the docs today

**Comment by garrensmith** [comment]
I'm going to close this issue. We have updated our docs with this.
