### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by GNVageesh** [prisma/prisma#9351]
### Bug description

I started writing a Database Model in Prisma for an express API, but unfortunately when I ran `yarn prisma migrate dev --name "Initial Data Model"` i am getting an Error

Here is the complete version

```
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'D:\\APIs\\Randize\\node_modules\\prisma\\query_engine-windows.dll.node'".
info If you think this is a bug, please open a bug report with the information provided in "D:\\APIs\\Randize\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Command failed with exit code 1: yarn add -D prisma@3.0.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Kindly Help me out with this!

Operating System: Windows 11 Beta
Yarn: 1.22.10
Prisma: 3.0.2
Editor: Visual Studio Code

### Environment & setup

- OS: Windows 11 Beta
- Database: PostgreSQL
- Node.js version: v14.16.1

### Prisma Version

```
3.0.2
```

**Comment by GNVageesh** [comment]
I got it fixed by prisma client separately by `yarn add @prisma/client`. So does this mean that this is a Windows Error since it works fine on Linux (Manjaro 21.1.2)

**Comment by janpio** [comment]
Thanks, already reported at https://github.com/prisma/prisma/issues/9184

**Comment by GNVageesh** [comment]
Ok sir.. thank u
