### ISSUE TITLE
Missing `$` from `executeRaw` in error message "Invalid \`prisma.executeRaw()\` invocation:"

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#9388]
Take this example from https://github.com/prisma/prisma/blob/2b6319588bd384a1ca37d0022879ca589d974bd9/packages/client/src/__tests__/integration/happy/interactive-transactions/test.ts#L325

```ts
      await prisma.$executeRaw`INSERT INTO User (id, email) VALUES ("1", "user_1@website.com")`,
      await prisma.$executeRaw`INSERT INTO User (id, email) VALUES ("1", "user_1@website.com")`,
```

It will throw:

```
Invalid \`prisma.executeRaw()\` invocation:


  Raw query failed. Code: \`2067\`. Message: \`UNIQUE constraint failed: User.email\`
`)
```

The $ is required now in front of `executeRaw` (we used to support without the $ at some point)

Here the small fix would be to add the $ like `prisma.$executeRaw()` in the error message.

This probably also applies to `queryRaw`.

**Comment by janpio** [comment]
This is actually from the Client, not the engine: https://github.com/prisma/prisma/blob/ba74c81fdbc9e6405946fdc6f9d42d103d008dc2/packages/client/src/runtime/utils/printStack.ts#L190
