### ISSUE TITLE
TS doesn't returns selects and includes types when creating

### ISSUE THREAD

**Issue by zomars** [prisma/prisma#9389]
### Bug description

Whenever creating a new record with included/selected fields, the data exists, but the TypeScript definitions are missing.

### How to reproduce

```
const booking = prisma.booking.create({
  include: {
    user: true,
  },
  data: {
    title: "title",
    user: {
      connect: {
        id: "user-id",
      },
    },
  },
});

// The data exists, but TS says it's not:
// Property 'user' does not exist on type 'Booking'
console.log(booking.user)
```

### Expected behavior

The returned type to include the `user` typings.

### Prisma information

```
model User {
  id                  Int                @id @default(autoincrement())
  bookings            Booking[]
}

model Booking {
  id          Int                @id @default(autoincrement())
  uid         String             @unique
  user        User?              @relation(fields: [userId], references: [id])
  userId      Int?
  title       String
}
```

### Environment & setup

- OS: Mac OS 11.5.2
- Database: PostgreSQL
- Node.js version: v14.16.1

### Prisma Version

```
 2.30.3
```

**Comment by pantharshit00** [comment]
@zomars I wasn't able to reproduce this. The reproduction you shared was a bit incomplete, it was missing the `uid` field and type of user id specified was wrong.

After I corrected with the above mentioned change, I wasn't able to reproduce this: 
![image](https://user-images.githubusercontent.com/22195362/135846477-d208ca5a-c778-4b41-a961-db261c626a0a.png)


```ts
  const booking = await prisma.booking.create({
    include: {
      user: true,
    },
    data: {
      title: "title",
      uid: "test",
      user: {
        connect: {
          id: 1,
        },
      },
    },
  });

  const t = booking.user;

```

Can you please try this again with the latest version? If you can still reproduce this, it would be best to share a minimal working reproduction inside of git repository.

**Comment by zomars** [comment]
Ok I've pinpointed my error, turns out I was also doing a `createMany` with invalid data and it was messing with the types. Fixed the data and the types started working normally again. Feel free to close this issue. Thank you! 🙏🏽
