### ISSUE TITLE
I have not been able to use this app. It keep saying open the setting and allow access to the photos, but my phone is already allowed access. I do not know how to fix this problem.

### ISSUE THREAD

**Issue by HassanShivarani** [prisma/prisma#9391]

**Comment by HassanShivarani** [comment]
Once I click on Prisma, it says open the setting. I open the setting, it says allow Prisma to access. But the access is already granted !! So I am stcuk not knowing how to make this app work for me.

**Comment by pantharshit00** [comment]
This repository deals with Prisma ORM and you are talking about Prisma photo editing app which we are not related to. Please contact support of the app here: https://prisma-ai.com/
