### ISSUE TITLE
Pass extra arguments to `prisma db seed` to the seed command

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#9403]
## Problem

I can't pass extra arguments to the command defined in `prisma.seed` in the package.json to the seed command.

## Suggested solution

`prisma db seed -- --extra-args=extra-values`

## Alternatives

Env vars work as well but are not as nice.

**Comment by JameelKhan9** [comment]
+1 to this issue.

Usage: for the development environment, we would want args passed to allow for development data to be seeded. For production, we may want some basic production metadata. For now, we will also use an environment variable.
