### ISSUE TITLE
Full-Text Search Index support for MySQL

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#9412]
_(follow-up from #1684)_

## Problem

In [2.30.0](https://github.com/prisma/prisma/releases/tag/2.30.0), we shipped Full-Text Search support for Postgres in Preview.

We have plans to also support MySQL full-text search. One of the prerequisites for this features is being able to manage indices in Migrate and Introspection.

Client implementation is split out into: https://github.com/prisma/prisma/issues/10415

## Suggested solution

It should have the [same Full-Text Search API](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search).

**Comment by pimeys** [comment]
Closed with https://github.com/prisma/prisma-engines/pull/2431 and https://github.com/prisma/prisma-engines/pull/2434

**Comment by hckhanh** [comment]
How about full text index for Postgres. I am still waiting

**Comment by janpio** [comment]
That is tracked in https://github.com/prisma/prisma/issues/10386 If you can post there use case, and maybe some example SQL how that looks in your database - that would be helpful. Thanks.

**Comment by hckhanh** [comment]
Thanks, @janpio, I am really waiting for this one :D

**Comment by floelhoeffel** [comment]
Hello everyone 👋

We are starting design work to improve Prisma's support for **Full Text Search (FTS)**!

If you would like to help, please help us learn about your needs via a short [FTS user research survey](https://prisma103696.typeform.com/fts-survey).

Thank you!
