### ISSUE TITLE
Type of `_count` key of relation count is nullable

### ISSUE THREAD

**Issue by mitsuru-kasai-exwzd** [prisma/prisma#9416]
### Bug description
Hi there.
I love prisma and am grateful for release of 3.0!
Then, I found nits around relation count.

I get object with **nullable** `_count` key using `relation count` feature, but [I heard](https://github.com/prisma/prisma/discussions/9374#discussioncomment-1377195) `_count` key will never be null.

Because of nullability, I need needless null check or non-null-assertion.

### How to reproduce

Reproduction code is [here](https://github.com/mitsuru-kasai-exwzd/prisma-count-nullable)

===

1. making models with relation
https://github.com/mitsuru-kasai-exwzd/prisma-count-nullable/blob/master/prisma/schema.prisma
1. `npx prisma generate`
1. fetch model with relation count
https://github.com/mitsuru-kasai-exwzd/prisma-count-nullable/blob/master/index.ts

### Expected behavior

`_count` key will be not nullable.

### Schema
https://github.com/mitsuru-kasai-exwzd/prisma-count-nullable/blob/master/prisma/schema.prisma
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int    @id @default(autoincrement())
  posts Post[]
}

model Post {
  id       Int  @id @default(autoincrement())
  author   User @relation(fields: [authorId], references: [id])
  authorId Int
}
```

### Query
https://github.com/mitsuru-kasai-exwzd/prisma-count-nullable/blob/master/index.ts
```ts
const prisma = new PrismaClient()
prisma.user.findFirst(
    {
        include: { _count: { select: { posts: true } } },
        rejectOnNotFound: true
    }
).then(user => {
    user._count // this is nullable
})
```

### Environment & setup

- OS: Mac OS Big Sur 11.4
- Database: Not depend database
- Node.js version: v16.6.2

### Prisma Version

```
prisma                  : 3.1.1
@prisma/client          : 3.1.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : c22652b7e418506fab23052d569b85d3aec4883f
Studio                  : 0.423.0
```

**Comment by pantharshit00** [comment]
Thanks for reporting this. I can confirm this issue. We need to adjust the typings.

**Comment by mitsuru-kasai-exwzd** [comment]
Thanks for your confirmation!

I'm looking forward to update. :)
