### ISSUE TITLE
Prisma does not recover from PrismaClientInitializationError

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma#9420]
### Bug description

When the database is not available on startup, calling `prisma.$connect()` throw `PrismaClientInitializationError`.

However, when the database becomes available, all the repetive calls of `prisma.$connect()` or normal Prisma Client queries fails with the same `PrismaClientInitializationError`.

### How to reproduce

1. Turn off your database server (e.g. disconnect from VPN).
2. Start the Node app which calls `prisma.$connect()` every e.g. 10 seconds.
3. See it throws `PrismaClientInitializationError`
4. Turn on your database server (e.g. connect to VPN).
5. The Node app is still running in the background.
6. See it still throws `PrismaClientInitializationError`.
7. Restart the app and see it can now easily connect to the database.

### Expected behavior

It should try to reconnect instead of throwing `PrismaClientInitializationError` when the database becomes available.

### Environment & setup

- OS:  Ubuntu 20.04
- Database:  Postgres
- Node.js version:  v16.9.1

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by MichalLytek** [comment]
When I drop the connection in runtime, it throws `PrismaClientKnownRequestError` with `P1001` but when I reestablish the connection, it gets back to working properly without any issues 😉

**Comment by timgriffin89** [comment]
Hi folks, we're experiencing this issue too. Is there any update on this bug? Is there a way to work around it in the meantime (other than restarting the application)?

**Comment by s-montigny-desautels** [comment]
Hi, we are experiencing this issue too. For now, we are creating a new instance of PrismaClient when having an error on the first connect. I don't know if it's the best solution, but it solve our problem for now.

```ts
let prisma = new PrismaClient();

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

(async () => {
  while (true) {
    try {
      await prisma.$connect();
      break;
    } catch {
      await sleep(1000);
      prisma = new PrismaClient();
    }
  }
})();

```

**Comment by Miladiir** [comment]
I am also experiencing this error. Additionally no error is logged when used with `new PrismaClient({ log: [{ emit: "stdout", level: "error" }] ])`.

**Comment by garrensmith** [comment]
https://github.com/prisma/prisma/pull/12066 fixes this. 
You can test it out with `prisma@dev` and will be out in the next release

**Comment by AndrewSouthpaw** [comment]
This appears to have regressed at least in 4.13.0:
- https://github.com/prisma/prisma/issues/19182
- https://github.com/prisma/prisma/issues/18071
