### ISSUE TITLE
Commented out env var values from `.env` are logged via `DEBUG=*`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9428]
Imagine I have two `DATABASE_URL`s I switch between in my `.env` file, and I comment them in and out to enable or disable and get the wanted one active.

This leads to logging output with `DEBUG=*` like the following:
```
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\prisma-dataproxy-test\.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: #DATABASE_URL=postgresql://estell:BbS...MS1@pg-db-provision.cm0mkpwj8arx.eu-central-1.rds.amazonaws.com:5432/blush_snail
```

Note how the commented out line is fully logged as it is not a valid definition for the tool we are using for this 😢

**Comment by Jolg42** [comment]
We `enableDebug` for dotenv when `DEBUG="*"` here https://github.com/prisma/prisma/blob/joel/client-mongo-test/packages/sdk/src/utils/tryLoadEnvs.ts#L127-L129

**Comment by Jolg42** [comment]
Opened a discussion in https://github.com/motdotla/dotenv/issues/569 to see if authors/contributors of dotenv would like to stop printing the content of comments.

So our options to move this forward
- wait for this discussion and agree on a PR and a dotenv release
- fork dotenv to have this done faster
- stop enabling debug for dotenv with `process.env.DEBUG` and replace this with for example `process.env.DOTENV_DEBUG`

@janpio I think the last option could make sense here, what do you think?

**Comment by janpio** [comment]
Option 3 already exists if we choose to use that and could surface that in our documentation: https://github.com/motdotla/dotenv/blob/7301ac9be0b2c766f865bbe24280bf82586d25aa/lib/env-options.js#L14-L16

**Comment by Jolg42** [comment]
@janpio Thanks Jan I forgot about that one!

**Comment by Jolg42** [comment]
I’ll create a PR today to fix 

Currently if you set `DEBUG=anything` we also enable the “debug” feature of the `dotenv` library which prints what it does and leaks comments (and therefore potentially secrets to the terminal)

The same feature will be available after through setting `DOTENV_CONFIG_DEBUG=anything` so it’s more specific and only enabled if you want it.
