### ISSUE TITLE
Connector timeout error when I use promise.all

### ISSUE THREAD

**Issue by jsun969** [prisma/prisma#9465]
### Bug description

I encountered a timeout error when operating with SQLite multiple times with `Promise.all`

### How to reproduce

My schema is
```prisma
datasource db {
  provider = "sqlite"
  url      = "file:./db.db"
}

model Friend {
  id          Int      @id @default(autoincrement())
  order       Int      @default(0)
}
```
and I want to update with a array include ids and orders like
```ts
const orders=[{id:2, order:5}, {id:3, order:4}]
```
This is how I update data
```ts
await Promise.all(
  orders.map(({ id, order }) => {
    return prisma.friend.update({
      where: { id },
      data: { order },
    });
  })
);
```
I got error
```
Error: 
Invalid `prisma.friend.update()` invocation:
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.) })
```

### Prisma information

Error: 
Invalid `prisma.friend.update()` invocation:
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.) })

### Environment & setup

- OS: Arch Linux
- Database: SQLite
- Node.js version: v16.6.1

### Prisma Version

```
3.1.1
```

**Comment by macjuul** [comment]
Running into the same issue as it's causing [prisma-session-store](https://www.npmjs.com/package/@quixo3/prisma-session-store) as well as my own code to break. Can confirm removing Promise.all() fixes the issue.

**Comment by jsun969** [comment]
I use `for` to execute each operation independently

**Comment by woen4** [comment]
Try use `Promise.allSettled` instead `Promise.all`
