### ISSUE TITLE
Create a Dart Prisma Client (prisma-client-dart) for server-side Dart.

### ISSUE THREAD

**Issue by danielmahon** [prisma/prisma#9473]
## Problem

I've been using Dart server-side more and more lately, and I have a few NodeJS microservices that I would love to test converting to Dart. The AOT compiler in Dart has the enticement of making these services much simpler/faster/smaller than with NodeJS. As it stands, Prisma only provides generated clients for Javascript, and Go.

## Suggested solution

I would love to see a Dart generated client, ie "prisma-client-dart".

## Alternatives

Maybe a community guide for client generator creation (if one doesn't already exist). So that the community at large can more easily create client generators for other languages.

## Additional context

This would allow more developers who use Flutter/Dart on the front-end to simplify their stack and remove NodeJS from the back-end (even though I still love it). This would allow for full-stack dart development with Prisma.

**Comment by medz** [comment]
I also have the same needs, or the official document for creating a client is provided by us.

**Comment by medz** [comment]
+1

**Comment by AndryHTC** [comment]
Would be a Great

**Comment by mhadaily** [comment]
+1

**Comment by Devd0** [comment]
+1

**Comment by akshay-sha** [comment]
+1

**Comment by anandsubbu007** [comment]
+1

**Comment by Ali1Ammar** [comment]
https://github.com/Ali1Ammar/prisma-client-dart

**Comment by medz** [comment]
> https://github.com/Ali1Ammar/prisma-client-dart

https://pub.dev/packages/orm

**Comment by medz** [comment]
> https://github.com/Ali1Ammar/prisma-client-dart

Interested in developing together? I have done most of the functionality. Writing a client generator. I plan to add dylib and data proxy after the Binary query engine is written.
I'm relatively familiar with the Rust language, and writing prisma engines for c api for Dart is easy.
A data proxy is a plain http request.

https://github.com/odroe/prisma

**Comment by danielmahon** [comment]
@medz @Ali1Ammar Woah, it's awesome to see solid progress on this front. My current project isn't using Prisma, but I will definitely be watching your projects.

**Comment by Ali1Ammar** [comment]
@medz why not let work together

**Comment by medz** [comment]
> @medz why not let work together

@Ali1Ammar I just want to work with you on Prisma for Dart. I have emailed you yesterday. I'll set you up in Prisma for Dart Admin role later.

**Comment by Hecalion** [comment]
Amazing! This is what I was looking for! As I'm working more and more on Flutter/Dart, I wanted to use Dart on backend as well.
Keep it up, I'm cheering for you!

**Comment by gabsn** [comment]
We definitely need this. Coming from react to flutter, the dart ecosystem is lacking so many essentials...

**Comment by medz** [comment]
> We definitely need this. Coming from react to flutter, the dart ecosystem is lacking so many essentials...

@gabsn In development, will be released soon, see https://github.com/prismaorm/dart

**Comment by medz** [comment]
🎉Happy to announce that Prisma ORM for Dart is available in version 2.0.0-dev.4. But still the following problems:

1. `db pull` has not been completed
2. Model deserialization has not been completed yet, the current model code returns `dynamic` type

More available check out the version on pub.dev 👉https://pub.dev/packages/orm/versions/2.0.0-dev.4

**Comment by alestiago** [comment]
@janpio , this issue requested a "community guide for client generator creation". Is there any available? Are there any plans to write one?

**Comment by janpio** [comment]
No, that does not exist. Currently it is also not a high priority to write one.
Generally I would suggest looking at how other Clients work, or how Prisma Client itself works.

**Comment by alestiago** [comment]
Thanks @janpio for the quick reply. It's a shame that it does _yet_ not exist. 

I understand it not being a high priority. Is there a way I can track the priority given to this issue 🙌 ? For example, the Flutter team [assigns labels](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+p3) to indicate the priorities, another option is using an open [GitHub Project board](https://github.com/orgs/VeryGoodOpenSource/projects/1).

**Comment by janpio** [comment]
No, we do not communicate any commitments. We do have our public roadmap at https://pris.ly/d/roadmap, but that is pretty high level.

This issue for us also does not track the community guide (which is listed as a potential alternative), but the Dart Client. If you want  such a community guide, I suggest you open a new issue that is explicitly for that request. Thanks.

**Comment by StevenKamwaza** [comment]
you can also check this [https://prisma.pub/docs/](uhttps://prisma.pub/docs/rl)

**Comment by danielmahon** [comment]
I'm going to close this since a community solution exists now 🚀
