### ISSUE TITLE
Can't type fields with types that are created outside of prisma schema file

### ISSUE THREAD

**Issue by AlexandrosMelissas** [prisma/prisma#9496]
## Problem

There is no import functionality in prisma file. Let's say i want to have an enum in my database and i want to type it. In order to have a clean architecture and large scalability, i prefer declaring my enum types outside of the schema file. So i need to import them to type my fields. Same problem with typing json files.

## Suggested solution

``` 
import { EnumType } from 'somewhere'

model Application {
    id String @default(uuid()) @id
    type EnumType
}
```
## Additional context

I know the problem is the schema file is only controlled by prisma and is not a javascript/ts file. But we need to find a solution because this is very limiting. I could, potentially, make a duplicate class extending Application type of prisma but that would be very annoying having duplicate code everywhere. Everytime i would make a change in the schema, i would have to apply the changes to the outside class as well. It would be perfect if the prisma file was the single source of truth.

**Comment by janpio** [comment]
Your suggestion is unfortunately not an option, as the Prisma schema file needs to include the definition of the enum, not just the Typesscript type that will be used to reflect that. If that is actually what you are asking for, your request should be covered by https://github.com/prisma/prisma/issues/2377.

Thanks for opening the issue!
