### ISSUE TITLE
MDBI: Show a helpful error message when developers try to re-introspect a MongoDB database

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#9557]
Perhaps linked to https://github.com/prisma/prisma/issues/9585 where people can upvote and discuss this feature.

**Comment by janpio** [comment]
We already have logic to use `--force` when the existing schema is invalid - maybe that can be reused (and would also give people a way to _ignore_ the message and create a new schema without manually deleting the old one, but using `--force` as well)
