### ISSUE TITLE
Create prisma console, a REPL similar to rails console

### ISSUE THREAD

**Issue by joshwilsonvu** [prisma/prisma#9563]
## Problem

When I work with Rails, I am able to type `$ rails console` and immediately get a REPL environment where I can run queries
and mutations, which is helpful for experimentation and testing ideas. The interactivity helps me **quickly** build up the 
query I want one step at a time until I ultimately have a query I'm ready to put in real code. It's like a backdoor to the DB; 
if I need to, I can even run queries on staging/production databases and use a real programming language to do what I 
want with it.

Currently, it's not as quick and easy to experiment or run one-off commands with Prisma. The closest you 
can get now is running `node` (or `ts-node`), importing the Prisma client, and going from there. However, 
for the `async` APIs to be friendly, you need top-level-`await` in the REPL:

- `node --experimental-repl-await` for versions v10.0.0 through v16.6.0, or more recent `node`
- `ts-node` v10.2.0 or newer with TypeScript version is 3.8 or higher and target is ES2018 or higher

This excludes a lot of people from being able to use Prisma in a REPL. And for those that can, it's still not
obvious how to do it.

## Suggested solution

I'd like to help build a new CLI command, `$ prisma console`, that 
- preloads the Prisma client
- handles top-level-`await` either natively or through transpilation
- supports TypeScript syntax when a `tsconfig.json` is detected, for consistency with real projects
- supports niceties like tab-completion and [custom commands](https://nodejs.org/api/repl.html#repl_replserver_definecommand_keyword_cmd) for running other Prisma CLI commands without context switching or closing the REPL
- automatically keeps up to date without restarting when the Prisma client is regenerated
- supports evaluating string contents or scripts at the command line, for scripting or automation
- potentially supports a "Sandbox" mode, where DB alterations are rolled back when the REPL exits

The ultimate goal would be to encourage experimentation and quick commands by being fast and simple to use.

## Alternatives

As mentioned, users can manually set up the `node` or `ts-node` REPL, but that can get complicated and just takes
a lot of keystrokes to set up when it is possible.

Prisms Studio solves some of the same problems, but it's not CLI. 

Users can write full `.js`/`.ts` files using Prisma and run them, evaluate results, edit the files, and rerun them, but
this is a slower process not well suited to experimentation.

Blitz.js users can use `$ blitz console` ([docs](https://blitzjs.com/docs/cli-console)) to interact with Prisma and other
parts of their apps. This is very similar to `$ rails console`. These users wouldn't have much of a use case for 
`$ prisma console`. Whereas the Blitz.js console is focused on the full backend/full stack, a Prisma console would 
be focused on the DB layer only.

## Additional context

https://github.com/prisma/prisma/discussions/6300
[Rails console docs](https://guides.rubyonrails.org/command_line.html#bin-rails-console)
[Rails console tips and tricks](https://pragmaticstudio.com/tutorials/rails-console-shortcuts-tips-tricks)

**Comment by axhamre** [comment]
This would be amazing! 🙌

**Comment by tak1n** [comment]
Something similar already exists https://github.com/egoist/prisma-repl

**Comment by joshwilsonvu** [comment]
So there is! Thank you, that seems to cover everything I mentioned.

**Comment by pencilcheck** [comment]
Doesn't work for me, i can't run the prisma-repl, it is missing a file '~home/.npm/_npx/176ae59c25f9a6a5/node_modules/prisma-repl/dist/cli.js'
