### ISSUE TITLE
ReferenceError: prisma is not defined when building a next.js project

### ISSUE THREAD

**Issue by faisalsayed10** [prisma/prisma#9567]
### Bug description

I’m trying to deploy my nextjs project containing prisma to vercel, it works fine locally but i’m getting this error when in production:

```
ReferenceError: prisma is not defined
    at Object.1ygI (/Users/fayd/Projects/libook/.next/server/pages/api/auth/[...nextauth].js:127:10)
    at __webpack_require__ (/Users/fayd/Projects/libook/.next/server/pages/api/auth/[...nextauth].js:23:31)
    at Module.KMLI (/Users/fayd/Projects/libook/.next/server/pages/api/auth/[...nextauth].js:145:69)
    at __webpack_require__ (/Users/fayd/Projects/libook/.next/server/pages/api/auth/[...nextauth].js:23:31)
    at Object.1 (/Users/fayd/Projects/libook/.next/server/pages/api/auth/[...nextauth].js:99:18)
    at __webpack_require__ (/Users/fayd/Projects/libook/.next/server/pages/api/auth/[...nextauth].js:23:31)
    at /Users/fayd/Projects/libook/.next/server/pages/api/auth/[...nextauth].js:91:18
    at Object.<anonymous> (/Users/fayd/Projects/libook/.next/server/pages/api/auth/[...nextauth].js:94:10)
```

Also tried building nextjs locally to test if it’s regarding vercel but i’m getting the same error when I’m doing `yarn build` and then `yarn start`. here is my package.json:

```
{
  "name": "name",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "yarn migrate:deploy && next build",
    "start": "next start",
    "migrate:dev": "prisma migrate dev",
    "migrate:deploy": "prisma migrate deploy",
    "migrate:status": "prisma migrate status",
    "postinstall": "prisma generate"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    // .......
    "@prisma/client": "2.30.3",
    "axios": "^0.21.1",
    "next": "^10.0.0",
    "next-auth": "^3.27.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
  },
  "devDependencies": {
    // .......
    "css-loader": "^5.2.6",
    "prisma": "2.30.3",
    "typescript": "4.2.4"
  }
}
```

### How to reproduce

1. Simply try building a next.js project containing prisma and run it using `yarn start`

### Prisma information

prisma version -> 2.30.3
prisma schema:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id            Int       @id @default(autoincrement())
  name          String?
  email         String?   @unique
  emailVerified DateTime? @map(name: "email_verified")
  image         String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
  updatedAt     DateTime  @default(now()) @map(name: "updated_at")
  lists         List[]

  @@map(name: "users")
}

model Account {
  id                 Int       @id @default(autoincrement())
  compoundId         String    @unique @map(name: "compound_id")
  userId             Int       @map(name: "user_id")
  providerType       String    @map(name: "provider_type")
  providerId         String    @map(name: "provider_id")
  providerAccountId  String    @map(name: "provider_account_id")
  refreshToken       String?   @map(name: "refresh_token")
  accessToken        String?   @map(name: "access_token")
  accessTokenExpires DateTime? @map(name: "access_token_expires")
  createdAt          DateTime  @default(now()) @map(name: "created_at")
  updatedAt          DateTime  @default(now()) @map(name: "updated_at")


  @@index([providerAccountId], name: "providerAccountId")
  @@index([providerId], name: "providerId")
  @@index([userId], name: "userId")
  @@map(name: "accounts")
}

model Session {
  id           Int      @id @default(autoincrement())
  userId       Int      @map(name: "user_id")
  expires      DateTime
  sessionToken String   @unique @map(name: "session_token")
  accessToken  String   @unique @map(name: "access_token")
  createdAt    DateTime @default(now()) @map(name: "created_at")
  updatedAt    DateTime @default(now()) @map(name: "updated_at")

  @@map(name: "sessions")
}

model VerificationRequest {
  id         Int      @id @default(autoincrement())
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now()) @map(name: "created_at")
  updatedAt  DateTime @default(now()) @map(name: "updated_at")

  @@map(name: "verification_requests")
}

model List {
  id          String   @id @default(uuid())
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  name        String
  type        ListType @default(normal)
  description String   @default("")
  books       Book[]
  author      User     @relation(fields: [authorId], references: [id])
  authorId    Int

  @@map("lists")
}

model Book {
  id            String   @id @default(uuid())
  gbookId       String   @unique @map(name: "gbook_id")
  title         String
  description   String   @default("")
  authors       String[]
  publishedDate String   @map(name: "published_date")
  previewLink   String   @map(name: "preview_link")
  imageLinks    Json     @map(name: "image_links")
  lists         List[]

  @@map("books")
}

enum ListType {
  normal
  wantToRead
  currentlyReading
  alreadyRead
}
```

### Environment & setup

- OS:  MacOS Big Sur
- Database:  PostgreSQL
- Node.js version:  v14.17.1
 

### Prisma Version

```
2.30.3
```

**Comment by pantharshit00** [comment]
@faisalsayed10 

Can you please share a complete reproduction inside of a git repository? Provided information is not sufficient for us to try to replicate this locally.

**Comment by faisalsayed10** [comment]
this is my git repository: https://github.com/faisalsayed10/libook
you can just setup the env file referring the .env.example, (only DATABASE_URL, NEXTAUTH_URL and SECRET are required here), do `yarn build` and then `yarn start`.
If you open http://localhost:3000 now, you should see the above mentioned error in the console.
But if you open dev server using `yarn dev` we don't get this issue.

**Comment by faisalsayed10** [comment]
Alright so i fixed this issue by tweaking `prisma.ts` file and now everything works!
`prisma.ts` before:
```
import { PrismaClient } from "@prisma/client";

declare global {
  var prisma: PrismaClient;
}

if (process.env.NODE_ENV === "production") {
  prisma = new PrismaClient();
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient();
  }
  prisma = global.prisma;
}
export default prisma;
```

`prisma.ts` which works:
```
import { PrismaClient } from "@prisma/client";

declare global {
	var prisma: PrismaClient | undefined;
}

const prisma = global.prisma || new PrismaClient({ log: ["info"] });
if (process.env.NODE_ENV !== "production") global.prisma = prisma;

export default prisma;
```

**Comment by ayush4345** [comment]
> Alright so i fixed this issue by tweaking `prisma.ts` file and now everything works! `prisma.ts` before:
> 
> ```
> import { PrismaClient } from "@prisma/client";
> 
> declare global {
>   var prisma: PrismaClient;
> }
> 
> if (process.env.NODE_ENV === "production") {
>   prisma = new PrismaClient();
> } else {
>   if (!global.prisma) {
>     global.prisma = new PrismaClient();
>   }
>   prisma = global.prisma;
> }
> export default prisma;
> ```
> 
> `prisma.ts` which works:
> 
> ```
> import { PrismaClient } from "@prisma/client";
> 
> declare global {
> 	var prisma: PrismaClient | undefined;
> }
> 
> const prisma = global.prisma || new PrismaClient({ log: ["info"] });
> if (process.env.NODE_ENV !== "production") global.prisma = prisma;
> 
> export default prisma;
> ```

can u give little bit explanation why this works not the previous one

**Comment by stivncastillo** [comment]
I have managed to solve this issue by using the following:

```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

export default prisma;
```

**Comment by purfectliterature** [comment]
For those who stumbled upon this like I did, allow me to provide a plausible solution and explanations.

## Missing `prisma` declaration

Theoretically, the code that @faisalsayed10 provided [here](https://github.com/prisma/prisma/issues/9567#issuecomment-933269929) are pretty much equivalent, _except_ the `ReferenceError` happened because it's missing `let prisma: PrismaClient;` before the if statement. I believe the "before" code was adapted from [Next.js's tutorial](https://vercel.com/guides/nextjs-prisma-postgres#:~:text=Now%2C%20add%20the%20following%20code%20to%20this%20file%3A). The full code reads as follows.

```ts
import { PrismaClient } from '@prisma/client';

let prisma: PrismaClient;      // <-- you're missing this!

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient();
} else {
  if (!global.prisma) {
    global.prisma = new PrismaClient();
  }
  prisma = global.prisma;
}

export default prisma;
```

The "after" code that "works" actually performs the same as the above code. I believe it was adapted from [Prisma's help article on instantiating `PrismaClient` in Next.js](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices).

Both codes basically prevents the reinstantiation of `PrismaClient` because otherwise it will keep on spawning new connections to the database.

## Missing `prisma` explicit import

If after all this, you still get the `ReferenceError`, then most probably you are using `prisma` somewhere without explicitly importing `prisma`.

```ts
import prisma from '@/lib/prisma';  // <-- you should have this in a file...

const users = await prisma.user.findMany({ ... });  // <-- ...anytime you do this!
```

I know you might be thinking. "Who would miss that?" It's actually more subtle than you think. You see, tutorials and Prisma's recommendation is to put `PrismaClient` in the `globalThis` object. To do this gracefully in TypeScript, you need to augment `global` with the `prisma` property—only then can you do `globalThis.prisma = new PrismaClient()`.

But by doing so, you'll notice that in any TypeScript files, `prisma` is always available even without an explicit import! You might have even typed `await pris` and <kbd>Enter</kbd> on the IntelliSense without realising Visual Studio Code did not add `import prisma from '@/lib/prisma';` for you.

So, do an audit. Go to Search in Files and make sure that for every file that has at least one `await prisma` or references the Prisma client, you have an explicit import for it.

## Conclusion

It's not Prisma's or Next.js' fault. It's ours. Oopsie.

**Comment by pulak-sarmah** [comment]
@purfectliterature  Thanks a bunch for making me realize I spent 6 hours chasing ghosts instead of checking my own code. Your solution was like a slap in the face with a wet fish - painful but effective!

**Comment by moitorrijos** [comment]
Thank you very much!

**Comment by EuvhenRight** [comment]
@purfectliterature Thanks a lot!

**Comment by victaphu** [comment]
Thank you so much!

The problem I had was exactly that, I didn't import prisma ...

Awesome stuff thanks

**Comment by pavanjadhaw** [comment]
Above solutions work but since prisma is available without explicit import because we are adding it to the global namespace
```
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const globalForPrisma = global as unknown as { prisma: typeof prisma };

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}

export default prisma;
```

This works and in files where you are using prisma it will give you an import error

**Comment by machado-developer** [comment]
prisma:info Starting a mysql pool with 5 connections.
Error during authorization: ReferenceError: prisma is not defined
    at s (C:\Users\anton\Documents\metalica\v2\.next\server\app\api\admin\clientes\[id]\route.js:1:3558)
    at Object.authorize (C:\Users\anton\Documents\metalica\v2\.next\server\app\api\admin\clientes\[id]\route.js:1:4220)
    at async Object.c (C:\Users\anton\Documents\metalica\v2\.next\server\chunks\4189.js:30:97484)
    at async _ (C:\Users\anton\Documents\metalica\v2\.next\server\chunks\4189.js:9:17704)
    at async a (C:\Users\anton\Documents\metalica\v2\.next\server\chunks\4189.js:22:24373)
    at async e.length.t (C:\Users\anton\Documents\metalica\v2\.next\server\chunks\4189.js:22:25815)


No  meu caso, continuo com o mesmo erro.
Mas notei que o erro acontece apenas em subrotas.

app/admin/clientes/routes.ts
app/admin/clientes/[id]/routes.ts

mas em rotas de primeiro nivel, funciona:
app/admin/route.ts

segue aqui um trecho do codigo:
**_rota: app/admin/clientes/[id]/route.ts_**

`
import  prisma  from "@/lib/prisma";
import { z } from "zod";
import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import logAction from "@/services/auditService";
import ClienteUpdateSchema from "./schmema";


export async function GET(
    req: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {

    try {
        const id = (await params).id; // Await the params promise to get the id

        const session = await getServerSession(authOptions);

        if (!session || session.user.perfil !== "ADMINISTRADOR") {
            return NextResponse.json({ error: "Acesso não autorizado" }, { status: 403 });
        }

        const cliente = await prisma.cliente.findUnique({
            where: { id },
            include: {
                projetos: true,
                gestores: true,
            },
        });

        if (!cliente) {
            return NextResponse.json({ error: "Cliente não encontrado" }, { status: 404 });
        }

        return NextResponse.json(cliente);
    } catch (error) {
        console.error("Error details:", {
            message: (error as any).message,
            stack: (error as any).stack,
            name: (error as any).name,
            ...(error as any),
        });
        return NextResponse.json({ message: "Internal server error" }, { status: 500 });
    }
}

export async function PUT(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
    const session = await getServerSession(authOptions);
    if (!session || session.user.perfil !== "ADMIN") {
        return NextResponse.json({ error: "Acesso negado" }, { status: 403 });
    }

    const body = await req.json();
    const parsed = ClienteUpdateSchema.safeParse(body);

    if (!parsed.success) {
        return NextResponse.json({ error: parsed.error.format() }, { status: 400 });
    }
    const id = (await params).id; // Await the params promise to get the id
    const { empresa, nome, ...rest } = parsed.data;
    console.log("Antes DE ACTUAL", parsed.data);

    const updated = await prisma.cliente.update({
        where: { id },
        data: {
            nome: empresa, ...rest
        }
    });

    console.log("DEPOIS DE ACTUAL", updated);


    return NextResponse.json(updated);
}

export async function DELETE(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
    try {
        const session = await getServerSession(authOptions);

        if (!session?.user || session.user.perfil !== "ADMIN") {
            return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
        }
        const id = (await params).id; // Await the params promise to get the id
        const cliente = await prisma.cliente.findUnique({
            where: { id },
        });

        if (!cliente) {
            console.log("USERS=>", cliente);

            return NextResponse.json({ message: "Usuário não encontrado" }, { status: 404 });
        }

        if (cliente.email === "geral@difp.com") {
            return NextResponse.json({ message: "Não é possível apagar este usuário!" }, { status: 403 });
        }


        await prisma.cliente.delete({
            where: { id },

            // Soft delete: apenas marca como deletado
        });
        await logAction(session.user.id, "Cliente DELETADO", `nome: ${cliente.nome},`);

        return NextResponse.json({ message: "Usuário arquivado com sucesso" }, { status: 200 });
    } catch (error) {
        console.error("Error details:", {
            message: (error as any).message,
            stack: (error as any).stack,
            name: (error as any).name,
            ...(error as any),
        });
        return NextResponse.json({ message: "Internal server error" }, { status: 500 });
    }
}
** lib/prisma.ts**
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma = globalForPrisma.prisma ?? new PrismaClient({ log: ["info"] });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;

export default prisma;
`


**next.config.js**
`
/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: { unoptimized: true },
};

module.exports = nextConfig;



** tsConfig.json **

{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`



packege.json

`
{
  "name": "sistema-de-gestao-interno",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "postinstall": "prisma generate"
  },
  "prisma": {
    "seed": "ts-node prisma/seed.ts"
  },
  "dependencies": {
    "@hookform/resolvers": "^3.9.0",
    "@next-auth/prisma-adapter": "^1.0.7",
    "@next/swc-wasm-nodejs": "13.5.1",
    "@prisma/client": "^6.4.1",
    "@radix-ui/react-accordion": "^1.2.0",
    "@radix-ui/react-alert-dialog": "^1.1.1",
    "@radix-ui/react-aspect-ratio": "^1.1.0",
    "@radix-ui/react-avatar": "^1.1.0",
    "@radix-ui/react-checkbox": "^1.1.1",
    "@radix-ui/react-collapsible": "^1.1.0",
    "@radix-ui/react-context-menu": "^2.2.1",
    "@radix-ui/react-dialog": "^1.1.1",
    "@radix-ui/react-dropdown-menu": "^2.1.1",
    "@radix-ui/react-hover-card": "^1.1.1",
    "@radix-ui/react-icons": "^1.3.2",
    "@radix-ui/react-label": "^2.1.0",
    "@radix-ui/react-menubar": "^1.1.1",
    "@radix-ui/react-navigation-menu": "^1.2.0",
    "@radix-ui/react-popover": "^1.1.1",
    "@radix-ui/react-progress": "^1.1.0",
    "@radix-ui/react-radio-group": "^1.2.0",
    "@radix-ui/react-scroll-area": "^1.1.0",
    "@radix-ui/react-select": "^2.1.1",
    "@radix-ui/react-separator": "^1.1.0",
    "@radix-ui/react-slider": "^1.2.0",
    "@radix-ui/react-slot": "^1.1.0",
    "@radix-ui/react-switch": "^1.1.0",
    "@radix-ui/react-tabs": "^1.1.0",
    "@radix-ui/react-toast": "^1.2.1",
    "@radix-ui/react-toggle": "^1.1.0",
    "@radix-ui/react-toggle-group": "^1.1.0",
    "@radix-ui/react-tooltip": "^1.1.2",
    "@types/bcryptjs": "^2.4.6",
    "@types/jsonwebtoken": "^9.0.6",
    "@types/nodemailer": "^6.4.17",
    "@types/nodemailer-express-handlebars": "^4.0.5",
    "@types/react": "18.2.22",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.15",
    "bcryptjs": "^2.4.3",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "cmdk": "^1.0.0",
    "date-fns": "^3.6.0",
    "date-fns-tz": "^3.2.0",
    "embla-carousel-react": "^8.3.0",
    "eslint": "8.49.0",
    "eslint-config-next": "13.5.1",
    "file-saver": "^2.0.5",
    "framer-motion": "^12.4.7",
    "input-otp": "^1.2.4",
    "jsonwebtoken": "^9.0.2",
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^5.0.2",
    "lucide-react": "^0.446.0",
    "next": "^15.1.7",
    "next-auth": "^4.24.7",
    "next-themes": "^0.3.0",
    "nodemailer": "^6.10.0",
    "nodemailer-express-handlebars": "^7.0.0",
    "papaparse": "^5.5.2",
    "postcss": "8.4.30",
    "react": "18.2.0",
    "react-countup": "^6.5.3",
    "react-day-picker": "^8.10.1",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.53.0",
    "react-resizable-panels": "^2.1.3",
    "react-responsive": "^10.0.1",
    "react-responsive-carousel": "^3.2.23",
    "recharts": "^2.12.7",
    "setup": "^0.0.3",
    "socket.io": "^4.7.5",
    "socket.io-client": "^4.7.5",
    "sonner": "^1.5.0",
    "tailwind-merge": "^2.5.2",
    "tailwindcss": "3.3.3",
    "tailwindcss-animate": "^1.0.7",
    "vaul": "^0.9.9",
    "winston": "^3.17.0",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@types/file-saver": "^2.0.7",
    "@types/node": "^22.13.9",
    "@types/papaparse": "^5.3.15",
    "prisma": "^6.5.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.8.2"
  }
}
`
