### ISSUE TITLE
[PSL] Expanded Index Capabilities

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma#9577]
We want to enable more fine-grained control about database indexing and are proposing the following addtions to the Prisma Schema language. We're happy to collect feedback about this proposal, so please chime in in the comments.  

```prisma
model Unique {
  // Optional Uniques  
  one       Int?    @unique

  // Sort Order
  two       String  @unique(sort: Asc|Desc) 

  //MySql allows specification of index length
  three     String  @unique(length: 191)
  @@index([two(length: 10, sort: Desc), three(length: 10, sort: Desc)]) 

  // The other dbs only need to be able to specify the sort order per field. 
  @@index([two(sort: Desc), three(sort: Desc)])

  // Index Type  
  @@index([two], type: BTree|Hash|GiST|GIN)
}

model IdForMySqlOnly {
  one       String    @id(length: 12)
}

model CompoundIdForMySqlOnly {
  one       String 
  two       String   

  @@id([one(length: 15), two(length: 100)])
}
```

## Null Handling in Optional Unique Constraints
Our supported databases differ in how they treat nulls in unique constraints: 
- One null allowed: SqlServer, MongoDB
- Multiple nulls allowed: Postgres, MySql, Sqlite

None of the dbs seem to have a simple toggle to switch between behaviours. Defining the other behaviour is possible but requires workarounds with special indexes. All the dbs seem to be solidly tied to their policy. Therefore we won't introduce a PSL feature for this, but will rather have tooltips in VSCode and documentation that explain what unique means for that provider.

Since the client API on SQL will always return nothing for a `where: {field:null}` filter in line with the SQL behaviour the difference between allowMultipleNulls and rejectMultipleNulls does not matter there. If we were to introduce an analog to the SQL `where is null` the client API would need to differentiate between allowMultipleNulls and rejectMultipleNulls:
- On a provider with allowMultipleNulls a unique optional field would not expose a isNull option.
- On a provider with rejectMultipleNulls a unique optional field with an isNull filter would be a valid WhereUniqueArgument since only one can return even for null.

MongoDb does not make the distinction between `isNull` and `equalsNull` and only allows for one null value. So a `where: {field:null}` filter should only ever return one value. 

## Sort Order

Index sort order influences when the index can be used if a sort order is requested (at least on compound indexes).
The options here are Asc / Desc, but there is the order of nulls in addition to that. Since that is only supported on Postgres, 
we can leave that out for now and go with the Postgres default. The SQL dbs seem to agree on ASC as the default, Mongo always requires the explicit annotation so has no default. 

We decided on ASC as the common default which we will not render. 

## Length Restrictions

The length argument which only applies to MySQL, determines how many chars at the beginning of a Text/Blob type are indexed. This is needed since otherwise you cannot index text columns on MySql. The allowed values for the limit are dependant on column length and datatype and Mysql itself does not have a default but forces you to spell it out. 

We will not implement a default here.  The value will need to be explicit if required. 

## Common Index Types 

The supported index types depend on chosen database provider, data type uniqueness etc.  We will need to add a lot of db specific validation in order not to produce invalid SQL. Ideally the code completion would only propose valid index types based on previous choices. I.E. if you start with @@unique, only BTREE would be valid on Postgres. 

The QE would need to be aware of at least the FullText indices, since some of them are needed to unlock FullText operations at the db level. It can than expose the correct client API.

The Default that is not rendered is BTREE across databases. So in most cases (i.e. all indices currently created by migrate) we would not need to render this type information.

**Comment by do4gr** [comment]
Only feedback received so far was positive, but asking for an escape hatch for custom indices. This is something we want to introduce but will first want to think about in a bigger context. 

The goal there would be to be able to specify in the PSL that there exists an index at the db level that migrate should not drop or change even though it's exact definition is not in the datamodel. This can happen if it is created via manual SQL additions in the migration files for example. The QE should still be able to pick up relevant information about these from the datamodel (uniqueness for example, or Fulltext coverage).

We will come up with a separate proposal for this.

**Comment by do4gr** [comment]
We decided to split out the index type part into a separate issue to reduce the implementation scope a bit. It can be found here: https://github.com/prisma/migrations-team/issues/281

**Comment by chris-braidwell** [comment]
You said `None of the dbs seem to have a simple toggle to switch between behaviours` regarding uniqueness of nulls in indexes. As of Postgres v16, `Specifying NULLS NOT DISTINCT on unique indexes / constraints will cause NULL to be treated as not distinct`. In other words, you can decide per-index whether NULLs are distinct or not.
