### ISSUE TITLE
Re-introspection support using `db pull` with MongoDB

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#9587]
Introspection support for MongoDB (Preview) was shipped with Prisma version 3.2.0 without re-introspection.

Meaning that during re-introspection some information will be lost (relations, comments, mapped fields...)

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/9585

**Comment by Jolg42** [comment]
Ok nice, closing as duplicate of 9585
