### ISSUE TITLE
Electron: Unclear how to generate Prisma Client on the fly for a schema

### ISSUE THREAD

**Issue by TasinIshmam** [prisma/prisma#9620]
## Problem
The [ASAR file format](https://github.com/electron/asar) is an archive used to package the source code and dependencies of an application in [Electron](https://www.electronjs.org/). 

When generating the Prisma client, ```getGenerators``` (and accompanying code in @prisma/client that actually does the generation) heavily relies on modifying the ```node_modules``` directory. This will not be possible with an ASAR archive, because it is read-only. 

Unpacking all of the dependencies out of the archive is also not a solution as it undermines many of the advantages of using the archive (performance, security, windows compatibility, etc). 

*Most applications* only have one schema and don't need to support multiple/dynamic schemas that change on the fly. So for such use cases, *this is not an issue*. These applications can generate the Prisma Client for the schema before packaging the application. 

## Suggested solution

The solution for applications that do need to support multiple schemas is unclear. 

## Additional Context

The [Prisma Studio](https://www.prisma.io/studio) electron app also ships Prisma and has support for dynamic schemas. The details for how this was implemented have been omitted here. @madebysid  may be able to provide details. 

**Related Issues/Discussions**: 
- #9613

**Comment by janpio** [comment]
Closing this for now as we had no further requests for this functionality. 

If **you** want to use Prisma in Electron (or similar) context, and would benefit from this functionality please leave a comment or open a new issue. Thanks.
