### ISSUE TITLE
SQLITE: npm workspaces hoisting breaks relative file path resolving

### ISSUE THREAD

**Issue by hpohlmeyer** [prisma/prisma#9649]
### Bug description

The hoisting behavior of [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) are resulting in different path resolving behaviors between the prisma cli and the generated prisma client.

The prisma client will resolve relative connection urls (`file:./dev.db`) relative to the generated client in the `node_modules` folder, while the prisma cli resolves the path relative to the `schema.prisma`.

### Reproduction Repo
A reproduction can be found at https://github.com/hpohlmeyer/prisma-bug

---

### Short version (try it out yourself)

1. Check out `https://github.com/hpohlmeyer/prisma-bug.git`
1. Run `npm install`
2. Run `cd backend`
3. Run `npx prisma generate`
4. Run `npx ts-node index.ts`
5. See the resulting error

---

### Long version (with observations)

I have a monorepo that uses [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces).
Running `npm install` results in the `prisma` and `@prisma/client` packages being hoisted to the project root.

My file structure looks like this now:
```
.
├── node_modules
│   ├── @prisma/client
│   ├── prisma
│   └── ...
├── backend
│   ├── prisma
│   │   └── schema.prisma
│   ├── index.ts
│   └── package.json
└── package.json
```

The `schema.prisma` looks like this:

```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int     @default(autoincrement()) @id
  email String  @unique
  name  String?
}
```

Afterwards I initialize the db by running `npx prisma migrate dev --name init`. The database will be created next to my `schema.prisma` file in the `prisma` directory, as I would have expected. At the same time a `.prisma` folder will be generated in both the root and the the backend directories node_modules folders.

```
.
├── node_modules
│   ├── .prisma <----- here
│   ├── @prisma/client
│   ├── prisma
│   └── ...
├── backend
│   ├── node_modules
│   │   └── .prisma <----- here
│   ├── prisma
│   │   ├── dev.db
│   │   ├── schema.prisma
│   │   └── ...
│   ├── index.ts
│   └── package.json
└── package.json
```

Next up I want to use my generated prisma client. The `index.ts` looks like this:
```ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log(await prisma.user.count());
}

main()
  .catch((e) => { throw e })
  .finally(async () => await prisma.$disconnect())
```

Calling it (`npx ts-node index.ts`) from the backend folder results in the following error:

```
<path-to-repo>/node_modules/@prisma/client/runtime/index.js:38735
          throw new import_engine_core3.PrismaClientKnownRequestError(message, e.code, this.prisma._clientVersion, e.meta);
                ^
PrismaClientKnownRequestError: 
Invalid `prisma.user.aggregate()` invocation:


  The table `main.User` does not exist in the current database.
    at cb (/Users/henno/Development/prisma-bug/node_modules/@prisma/client/runtime/index.js:38735:17)
    at async main (/Users/henno/Development/prisma-bug/backend/index.ts:6:15) {
  code: 'P2021',
  clientVersion: '3.2.0',
  meta: { table: 'main.User' }
}
```

The reason for that is, that prisma creates a new database relative to the prisma client in the `node_modules` folder:

```
.
├── node_modules
│   ├── .prisma
│   ├── @prisma/client
│   ├── prisma
│   └── ...
├── backend
│   ├── node_modules
│   │   └── .prisma
│   │       └── client
│   │           ├── dev.db <------ here
│   │           └── ...
│   ├── prisma
│   │   ├── dev.db
│   │   ├── schema.prisma
│   │   └── ...
│   ├── index.ts
│   └── package.json
└── package.json
```

The new db is empty, so the error message is correct, but the database is wrong.

### Expected behavior

Both the prisma cli and the prisma client should resolve relative file path connection urls relative to the `schema.prisma`.

### Prisma information

Schema:

```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int     @default(autoincrement()) @id
  email String  @unique
  name  String?
}
```

Client query file:

```ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log(await prisma.user.count());
}

main()
  .catch((e) => { throw e })
  .finally(async () => await prisma.$disconnect())
```

### Environment & setup

- OS: Mac OS
- Database: SQLite
- Node.js version: 16.6.1
- npm version: 7.23.0

### Prisma Version

```
prisma                  : 3.2.0
@prisma/client          : 3.2.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine afdab2f10860244038c4e32458134112852d4dad (at ../node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli afdab2f10860244038c4e32458134112852d4dad (at ../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core afdab2f10860244038c4e32458134112852d4dad (at ../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt afdab2f10860244038c4e32458134112852d4dad (at ../node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : afdab2f10860244038c4e32458134112852d4dad
Studio                  : 0.435.0
```

**Comment by dborstelmann** [comment]
This is also currently blocking me setting up prisma on multiple services

**Comment by pantharshit00** [comment]
Thanks for reporting. I can confirm this bug.

**Comment by phorcys420** [comment]
Can reproduce in own project.
![image](https://user-images.githubusercontent.com/57866459/148786460-570f4314-b433-47e6-8a28-ff9f1e2a4136.png)

**Comment by SamCB** [comment]
Can confirm it also happens with yarn workspaces. Can't reproduce @phorcys420's fix.

**Comment by pfried** [comment]
Have you tried a [no-hoisting config](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) in your root `package.json`?

```
{
  ...
  "workspaces": {
    "packages" : [
      "backend/*",
    ],
    "nohoist": [
      "**/prisma",
      "**/@prisma/client"
    ]
  }
}
````

**Comment by SamCB** [comment]
Looks like that works. Thanks! Didn't know it was a thing. Very interesting.

**Comment by hpohlmeyer** [comment]
> Have you tried a no-hoisting config in your root package.json?

I have not tried yet, but a quick search for `nohoist` brings up an [RFC for it](https://github.com/npm/rfcs/issues/287), but it does not seem it has been implemented yet.

**Comment by tomasgvivo** [comment]
I found a dirty fix...
```json
  "scripts": {
    "preinstall": "npm install --legacy-bundling --ignore-scripts; npm run postinstall",
    "postinstall": "npm run db:generate;",
    "db:generate": "prisma generate"
  }
```

Still waiting for `nohoist` to be implemented in NPM.
I would like to remove this from my `package.json` as soon as I can.

**Comment by ruyadorno** [comment]
@tomasgvivo while `--legacy-bundling` will get the package into its expected place, it's a too drastic of a change to force every dependency to be duplicated and nested within a `node_modules` folder of the dependent package.

When stumbling into this in a small example project I'm working on ahead of a talk on **npm workspaces**, a workaround to get **prisma** packages working as intended (similar to `noHoist`) was to place a dummy package (using [`npm` aliases](https://docs.npmjs.com/cli/v8/commands/npm-install)) in the root `package.json` thus forcing **npm** to duplicate the prisma libraries within the `node_modules` of each workspace that depends on them, effectively achieving a similar result as to using `noHoist`.

For reference (the relevant bits of) my setup looks like:

```
$ cat ./package.json
{
  "devDependencies": {
    "prisma": "npm:abbrev@1",
    "@prisma/client": "npm:abbrev@1"
  }
}
$ cat ./workspace-a/package.json
{
  "dependencies": {
    "@prisma/client": "^3.10.0"
  },
  "devDependencies": {
    "prisma": "^3.10.0"
  }
}
```

In my example above, [`abbrev`](https://www.npmjs.com/package/abbrev) is just this very simplistic package maintained by the npm team but you can use npm aliases to point to any published package you'd like.

**Comment by zgriesinger** [comment]
As a shameless plug I wanted to use @ruyadorno's workaround but was weary of adding any extra dependencies or potential for `npm audit` vulnerabilities so I created a package just for this purpose:
https://github.com/zgriesinger/noist

Essentially it warns you and errors if you try to import it and has a (somewhat 😛) descriptive name when you read it from your package.json

**Comment by millsp** [comment]
Hey, thanks for the reproduction. We have fixed such hoisting issues a while ago when we also fixed hoisting issues with `pnpm` I have tried it with the latest `@prisma/client`, and can confirm the repro works on `@prisma/client@4.14`. I am therefore closing this.

**Comment by rj-au** [comment]
For anyone looking for an answer in 2025:

Part 1)
Edit all your projects in your monorepo and add to your prisma.schemas:
```prisma
  output          = "./node_modules/.prisma/client"
```

Part 2)
Ensure Yarn installs the correct version in the project directories, if not, use "peerDependency" in package.json - start with the root pcakge.json
