### ISSUE TITLE
MDBGA: Support MongoDB Atlas Serverless

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#9659]
MongoDB provides [Serverless instances](https://www.mongodb.com/cloud/atlas/serverless) of Atlas. We should check to see if we support this. If not, we should try to support this.

## References

- Introspection does not work: https://github.com/prisma/prisma/issues/9680
- Can not query data with Prisma Client: https://github.com/prisma/prisma/issues/9682
- Issue for E2E: https://github.com/prisma/e2e-tests/issues/2115 + PR draft https://github.com/prisma/e2e-tests/pull/2116

**Comment by matthewmueller** [comment]
@jsefiani, still needs to be tested. It seems like the Todos are done, so just need to try it again.

**Comment by janpio** [comment]
One indication: https://github.com/prisma/e2e-tests/tree/dev/databases/mongodb-atlas-serverless is ✅

**Comment by matthewmueller** [comment]
Just tested it manually, this is working as expected 😊
