### ISSUE TITLE
Improve Connection Pool Timeout error message

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9662]
Currently our pool timeout error message is this:
```
Timed out fetching a new connection from the connection pool. (More info: http://pris.ly/d/connection-pool, Current connection limit: {connection_limit})
```

We should also output the `pool_timeout` value there:

```
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: {pool_timeout}, connection limit: {connection_limit})
```

This would help us understand users reporting problems with the connection pool timeout a lot.

**Comment by philippbosch** [comment]
One addition: clicking the pris.ly link in the error message leads to a 404 because the trailing comma is part of the URL (http://pris.ly/d/connection-pool,).

**Comment by janpio** [comment]
That is unfortunately part of how your local terminal parses URLs I think, not something we control afaik.
Buuut the new message would also fix that.

**Comment by philippbosch** [comment]
This is in the browser, not in the terminal. But maybe some kind of automatic linking is happening there as well.

**Comment by janpio** [comment]
Can you share a screenshot? For me here in the issue everything is fine. Let's make sure I know what you refer to.
