### ISSUE TITLE
Detect schema drift helper / `migrate dev --exit-code`

### ISSUE THREAD

**Issue by KATT** [prisma/prisma#9707]
## Problem

I want to add a CI-job to make sure no schema changes have been done without corresponding migration files have been added. Had a near-miss today where we could’ve borked a whole table since the autogenerated migration later contained a drop column.

## Suggested solution

Add an `--exit-code` that would fail `migrate dev` if there are changes (similar to `git diff --exit-code`)

## Alternatives

Another command, i.e. `migrate detect-drift`

## Additional context

I was asked to create this ticket on Slack - https://prisma.slack.com/archives/CBFFY3066/p1633945797065100

**Comment by KATT** [comment]
Can be done with further scripting, of course, and see if the created migration is an empty migration. Howver, it's a really flaky solution. I'd rather just have a command from prisma that could do this reliably and `exit 1`.

**Comment by floelhoeffel** [comment]
- `--create-only` flag is not a good option to detect pending migrations (it creates empty migration files if migration history and prisma schema are in sync)
- there is a workaround via `migrate status` to detect if a pending migration hasn't been generated yet
  - as it doesn't return exit codes, a bash script (as shown in the PR) can be used to detect state
- implementing an exit code flag seems like a vlid improvement to the DX

**Comment by floelhoeffel** [comment]
hey @KATT - as you mentioned #11514 as a potential fix to this issue, we actually dont return an exit code as of now with diff. However, we want to change that this sprint, see [#11566](https://github.com/prisma/prisma/issues/11566)

**Comment by Jolg42** [comment]
We added the `--exit-code` flag to `migrate diff` in the `3.11.0` release 🎊 

See https://github.com/prisma/prisma/releases/tag/3.11.0

**Comment by tobiasdiez** [comment]
For reference, the following command seems to do the job `prisma migrate diff --preview-feature --exit-code --from-migrations <path to migrations> --to-schema-datamodel <path to schema> --shadow-database-url <database connection string>`

**Comment by floelhoeffel** [comment]
> For reference, the following command seems to do the job `prisma migrate diff --preview-feature --exit-code --from-migrations <path to migrations> --to-schema-datamodel <path to schema> --shadow-database-url <database connection string>`

Thanks for confirming @tobiasdiez

**Comment by marcus13371337** [comment]
> For reference, the following command seems to do the job `prisma migrate diff --preview-feature --exit-code --from-migrations <path to migrations> --to-schema-datamodel <path to schema> --shadow-database-url <database connection string>`

I can't get this to work. When I run this command it outputs basically ALL changes that have been made since the init-migration. Running the DB in a local docker container
The steps I've taken:
```
prisma migrate reset
prisma migrate diff --from-schema-datamodel ./prisma/schema.prisma --to-migrations ./prisma/migrations --exit-code --shadow-database-url "postgresql://postgres:postgres@localhost:5432/postgres?schema=public"
# Fails with a lot of differences
```

Other approach:
```
prisma db pull
prisma migrate dev // Nothing to migrate
prisma migrate diff --from-schema-datamodel ./prisma/schema.prisma --to-migrations ./prisma/migrations --exit-code --shadow-database-url "postgresql://postgres:postgres@localhost:5432/postgres?schema=public"
```

What am I doing wrong?

**Comment by marcus13371337** [comment]
Confirmed found a bug with the:
```
  previewFeatures = ["multiSchema"]
```

Removing that and all models living in that schema fixes my issues with the diff command,

**Comment by janpio** [comment]
Open a new issue please and describe the full problem, optimally in a way that will let us reproduce the problem @marcus13371337. Thanks!
