### ISSUE TITLE
"Field does not exist on enclosing type" when trying to create a record

### ISSUE THREAD

**Issue by antonnes** [prisma/prisma#9717]
### Bug description

Having this model: 

```
model videos {
  id                  Int     @id @default(autoincrement()) @db.UnsignedInt
  title               String  @db.VarChar(255)
}
```

and this code in my service files: 

```
this.prismaService.videos.create({
            data: {
              title: 'test123'
            },
          }).then(data => {
            console.log(data);
        }).catch(error => {
            console.log(error);
        });
```

getting this error: 

```
 Failed to validate the query: `Field does not exist on enclosing type.` at `Mutation.createOnevideos`
    at cb (....\apps\videos-api\webpack:\apps\videos-api\node_modules\@prisma\client\runtime\index.js:38735:1) {
  code: 'P2009',
  clientVersion: '3.2.0',
  meta: {
    query_validation_error: 'Field does not exist on enclosing type.',
    query_position: 'Mutation.createOnevideos'
  }
}
```

The raw query produces no issues and creates a record in the database with no problem. 
The `findMany()` query also works properly;

### How to reproduce

1. Followed this guide - https://docs.nestjs.com/recipes/prisma
2. Run prisma.create method
3. See error

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["windows"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model videos {
  id            Int     @id @default(autoincrement()) @db.UnsignedInt
  title         String  @db.VarChar(255)
}
```

### Environment & setup

- OS: Windows 10
- Database: MySQL
- Node.js version: 14.17.1
- @nestjs/core": "^7.0.0"
- "prisma": "^3.2.0".

### Prisma Version

```
3.2.0
```

**Comment by janpio** [comment]
I can not reproduce this error in an isolated project. I could `db push` the schema, and then execute the script to created data just fine.

Is this the exact code that is failing for you?
Can you gather some more information via pris.ly/d/logging and pris.ly/d/debugging please?
Can you maybe even create a minimal reproduction?

**Comment by janpio** [comment]
Ping @antonnes - Please have a look at https://github.com/prisma/prisma/issues/9553#issuecomment-979383561
