### ISSUE TITLE
Concurrent relation upserts conflict

### ISSUE THREAD

**Issue by dariusj18** [prisma/prisma#9751]
### Bug description

Running multiple upserts concurrently and receiving the error:

```
PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]: 
Invalid `prisma.post.upsert()` invocation:


  Unique constraint failed on the fields: (`name`,`type`,`userId`)
    at cb (C:\PROJECTFOLDER\node_modules\@prisma\client\runtime\index.js:36063:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 5) {
  code: 'P2002',
  clientVersion: '2.30.2',
  meta: { target: [ 'name', 'type', 'userId' ] }
}
```

### How to reproduce

https://github.com/dariusj18/prisma_playground/tree/prisma_9751

1. Initialize database
2. Run npm start

### Expected behavior

No errors, upserts happen as expected

### Prisma information

```prisma
datasource db {
  url      = env("DATABASE_URL")
  provider = "postgres"
}

generator client {
  provider = "prisma-client-js"
  // previewFeatures = ["interactiveTransactions", "selectRelationCount", "referentialActions"]
}

model User {
  id       String @id @default(uuid()) @db.Uuid
  username String @unique

  type UserType

  profiles Profile[]
  tags     Tag[]

  publishedPosts Post[]

  @@unique([username, type])
}

enum UserType {
  PUBLISHER
  AUTHOR
  EDITOR
}

model Profile {
  id  String @id @default(uuid()) @db.Uuid
  bio String

  user   User   @relation(fields: [userId], references: [id])
  userId String @db.Uuid
}

model Tag {
  id   String @id @default(uuid()) @db.Uuid
  name String

  type TagType

  user   User   @relation(fields: [userId], references: [id])
  userId String @db.Uuid

  posts PostTag[]

  @@unique([name, type, userId])
}

enum TagType {
  CATEGORY
  POSTTYPE
  LANGUAGE
}

model Post {
  id    String @id @default(uuid()) @db.Uuid
  title String

  user   User   @relation(fields: [userId], references: [id])
  userId String @db.Uuid

  tags PostTag[]
}

model PostTag {
  post   Post   @relation(fields: [postId], references: [id])
  postId String @db.Uuid

  tag   Tag    @relation(fields: [tagId], references: [id])
  tagId String @db.Uuid

  @@id([postId, tagId])
}
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: 14.16.0

### Prisma Version

```
prisma                : 2.30.2
@prisma/client        : 2.30.2
Current platform      : windows
Query Engine (Binary) : query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine      : migration-engine-cli b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine  : introspection-core b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary         : prisma-fmt b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash  : b8c35d44de987a9691890b3ddf3e2e7effb9bf20
Studio                : 0.422.0
```

**Comment by matthewmueller** [comment]
Since it's all in one block, you should be able to stick this in a transaction `prisma.$transaction([...])`

We do have a problem when you're unable to stick the code in a block and the block is concurrent, see #3242 .

**Comment by dariusj18** [comment]
So, this must be a fundamental flaw with Prisma and how it works, because I get this error when I run this across multiple requests and the actual upsert is inside a transaction.  And the idea that "Hey folks, this is expected behavior" is the response in #3242 is pretty ridiculous.

This was also added as a milestone for 2.19 and seems to have been left behind?

**Comment by SevInf** [comment]
Reproduction: https://github.com/prisma/reproductions/tree/main/gh-9751

**Comment by pimeys** [comment]
Can still reproduce this with 4.3.1. Logs:

https://gist.github.com/pimeys/f3831809ac388a6c9b6ef8a720d8dce9

**Comment by garrensmith** [comment]
Prisma Upserts are very powerful and support very nested upserts. This can lead to a Unique constraint error being thrown. We have updated our [docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#unique-key-constraint-errors-on-upserts) with why this happens and what to do in that situation. 
We have also added support for `INSERT .. ON CONFLICT .. UPDATE` see the [docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#database-upserts) on when it will be used.

**Comment by chientrm** [comment]
Just wrap the `upsert` with a  `$transaction`:
```ts
[settings] = await prisma.$transaction([
  prisma.settings.upsert({
    where: { sub },
    update: {},
    create: { sub },
  }),
]);
```

**Comment by janpio** [comment]
Open a new issue or discussion please instead of commenting on a closed bug report. Thanks.

**Comment by chris-activewrite** [comment]
For those who are reporting concurrency issues, it would help if you noted what isolation level you're running in. Obviously that has a big effect on concurrency in general, and that needs to be used when reproducing your problems.
