### ISSUE TITLE
Ignore incorrect orderBy attribute

### ISSUE THREAD

**Issue by gas0324** [prisma/prisma#9753]
I want to implement front-end control sorting, but how should I filter incorrect orderBy attributes?
And, when the orderBy attribute is incorrect, the console will throw an exception, and the global exception filter of nestjs cannot catch the exception

```
  31   where?: Prisma.UserWhereInput;
  32   orderBy?: Prisma.UserOrderByWithRelationInput;
  33 }): Promise<User[]> {
→ 34 return this._prisma.user.findMany({
       skip: 0,
       take: 10,
       cursor: undefined,
       where: {
         AND: {
           role: {
             equals: undefined
           },
           username: {
             contains: undefined
           },
           nickname: {
             contains: undefined
           }
         }
       },
       orderBy: {
         a: 'asc'
         ~
       }
     })
```

**Comment by gas0324** [comment]
Or how to intercept the problem and return the front-end error message

**Comment by jkomyno** [comment]
Hi @gas0324, if I understand correctly, you would like Prisma client to accept input that breaks our type constraints?
I'm afraid this feature request is out of scope, as type-safety is one of the core features of Prisma.

As a rule of thumb, I'd suggest you to validate user-facing inputs before passing them to Prisma.
For instance, the `orderBy` object in the example above should only accept `user`'s fields as key properties.

Closing this as out of scope, but please leave a comment in case we have misinterpreted this issue.
