### ISSUE TITLE
Prisma db migration always altering my table contains mysql TIME data type inside of it

### ISSUE THREAD

**Issue by erzhae** [prisma/prisma#9769]
### Bug description

Prisma DB migration file generator always altering my table contains Mysql TIME data type inside of it.

### How to reproduce

I have a schema.prisma that one of my table contains MySQL TIME
```
model Agenda {
  id Int @id @default(autoincrement())
  name String @db.VarChar(128)
  dateStart DateTime @db.Date @map("date_start")
  dateEnd DateTime @db.Date @map("date_end")
  timeStart DateTime? @db.Time @map("time_start")
  timeEnd DateTime? @db.Time @map("time_end")
}

```
[Problem] Every time I edit my schema.prisma and generate a migration file, the generated file always altering my table which contains Mysql TIME, like:
```
ALTER TABLE `school_agenda` ADD COLUMN `testMigration` VARCHAR(191),
    MODIFY `time_start` TIME,  // << Always generated
    MODIFY `time_end` TIME;   // << Always generated`

```

### Prisma information

```
model Agenda {
  id Int @id @default(autoincrement())
  name String @db.VarChar(128)
  dateStart DateTime @db.Date @map("date_start")
  dateEnd DateTime @db.Date @map("date_end")
  timeStart DateTime? @db.Time @map("time_start")
  timeEnd DateTime? @db.Time @map("time_end")
}
```

### Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: Node.js 14.17.5

### Prisma Version

```
{
  "prisma": "^3.2.1",
  "@prisma/client": "^3.2.1"
}
```

**Comment by pantharshit00** [comment]
Thanks for the report, I can reproduce this.

**Comment by RicckVale** [comment]
There's a fix? I have the same problem.

**Comment by janpio** [comment]
No, this is a confirmed bug that we could not work on. We will update the issue if that changes.
