### ISSUE TITLE
Running out of memory with bulk insertion and createMany in postgres

### ISSUE THREAD

**Issue by panchopoliti** [prisma/prisma#9772]
### Bug description

Hey everyone 👋 !

We are receiving the next error when running createMany to insert around 1 million records of data, or more, in our Postgresql database:

```
RangeError: Invalid string length at JSON.stringify (<anonymous>) at BinaryEngine.requestBatch (/var/task/node_modules/@prisma/client/runtime/index.js:28895:37) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5) { clientVersion: '2.27.0' }
```

We are running this code in AWS Lambda and is reaching the memory capacity when making bulk insertions. With fewer records, it runs perfectly.

Things we've already tried but did not work:
- We set the Lambda memory up to 10GB, but then this memory was reached as well.
- We tried setting the `statement_cache_size` parameter in our database URL like this: `statement_cache_size=50`. Still, we did not see any change

Even though most of the times the error in these cases is the previous one, sometimes this Error from AWS Lambda is being thrown
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 0x563809fc4d33 node::Abort() [/var/lang/bin/node]
2: 0x563809fc55ae node::OnFatalError(char const*, char const*) [/var/lang/bin/node]
3: 0x56380a17635e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/var/lang/bin/node]
4: 0x56380a1766df v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool)
5: 0x56380a390cf8 [/var/lang/bin/node]
6: 0x56380a391b39 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/var/lang/bin/node]
7: 0x56380a3a2046 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) 
```

Any idea how to solve this 🙏 ?

### How to reproduce

Running:

```
db.contact.createMany();
db.contactsEvents.createMany();
db.$transaction();
```

### Expected behavior

To run createMany without errors

### Prisma information

Here are the two tables that we are inserting data in a transaction

Connection String: mysql://username:password@host/database?connection_limit=4&pool_timeout=30

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Contact {
  id                        String                      @id @default(uuid())
  contactId                 String
  accountId             String
  email                     String?
  adquiredAt                DateTime?
  firstName                 String?
  lastName                  String?
  ContactsEvents            ContactsEvents[]

  @@unique([accountId, contactId], name: "contactId_accountId")
  @@unique([accountId, email], name: "email_accountId")
}

model ContactsEvents {
  eventId        Int         @default(autoincrement())
  accountId      String
  contactId      String?
  contactEmail   String
  eventType      String?
  timestamp      DateTime
  contact        Contact?    @relation(fields: [contactId, accountForeign], references: [contactId, accountId])


  @@id([accountId, eventId])
}
```

### Environment & setup

- OS: Amazon Linux 2 in AWS Lambda
- Database: PostgreSQL
- Node.js version: 14.15

### Prisma Version

```
2.27.0
```

**Comment by panchopoliti** [comment]
Hey @janpio, thank you so much for your quick answer. I completely agree with you that is a Node level problem.

We decided to split the calls to smaller batches of data to avoid this error, and now it works. We haven't tried it with prisma's latest version, though.

Thanks for the help!

**Comment by panworapol** [comment]
I found solution, Sometime you might forgot to using dotenv -e .env prisma generate -- --schema ./schemapath

I stuck this problem all day and I solve it by my brain lol lol
