### ISSUE TITLE
Defining a model with name Middleware generates the wrong type definitions in .prisma/client

### ISSUE THREAD

**Issue by Alchemicas** [prisma/prisma#9773]
### Bug description

Most of what the title says, if you define a model with name Middleware in the schema.prisma file and then generate its types, they will make use of the internal Prisma.Middleware interface rather than using the root Middleware one that is correctly exported.

Little example:

schema.prisma
```
model Middleware {
  id String
}
```

index.ts
```
import { Middleware, PrismaClient } from '.prisma/client'

const client = new PrismaClient()
client.middleware.findUnique({ where: { id: '' } }).then((middleware: Middleware | null) => console.log(middleware))
```

The index.ts code won't compile because middleware is not of type Middleware but of type Prisma.Middleware.

### How to reproduce

1. Define a model with name Middleware
2. Try to run any query related to it and the type will be Prisma.Middleware rather than Middleware

### Expected behavior

I expect that the Middleware type in any scenario/query is always of type Middleware and not Prisma.Middleware.

### Prisma information

Not needed.

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v16.10.0

### Prisma Version

```
prisma                  : 3.2.1
@prisma/client          : 3.2.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c
Studio                  : 0.435.0
```

**Comment by SevInf** [comment]
This issue is now fixed and the fix will be published as a part of `5.1` release. If you'd like to verify fix earlier, you can use dev snapshot `5.1.0-dev.24`. We don't recommend using it in production, but it should be enough to verify the fix.
