### ISSUE TITLE
Connect field upsert doesnt give target field error meta

### ISSUE THREAD

**Issue by sooxt98** [prisma/prisma#9781]
### Bug description

Trying to upsert with connect, but when connect failed it doesnt give error target field about which causing it

```
PrismaClientKnownRequestError:
Invalid `prisma.user.upsert()` invocation:


  The required connected records were not found. Expected 1 records to be connected after connect operation on one-to-many relation 'CourseFeedbackToUser', found 0.
    at cb (/Users/sheldon/Dev/Work/sxt/node_modules/@prisma/client/runtime/index.js:36940:17) {
  code: 'P2018',
  clientVersion: '3.0.2',
  meta: {
    details: "Expected 1 records to be connected after connect operation on one-to-many relation 'CourseFeedbackToUser', found 0."
  }
}
```

**Comment by millsp** [comment]
Hey @sooxt98, could you please provide us a schema and the query to reproduce this? Also could you show us what you'd expect if that worked as you want. Thanks.

**Comment by millsp** [comment]
Hey @sooxt98,

Did you get a chance to have a look at my previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏
