### ISSUE TITLE
Error: [libs\sql-schema-describer\src\lib.rs:171:32] Column id not found in Table videos 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#9791]
Command: `prisma db pull`
Version: `3.2.1`
Binary Version: `b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c`
Report: https://prisma-errors.netlify.app/report/13544 
OS: `x64 win32 10.0.19043`

JS Stacktrace:
```
Error: [libs\sql-schema-describer\src\lib.rs:171:32] Column id not found in Table videos
    at ChildProcess.<anonymous> (C:\<Jan'sComputer>\9717\node_modules\prisma\build\index.js:43135:28)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: BaseThreadInitThunk
  28: RtlUserThreadStart

```

**Comment by tomhoule** [comment]
Let's create a feature request issue for that. Scope has expanded considerably.

**Comment by tomhoule** [comment]
New error report: https://prisma-errors.netlify.app/report/13559

**Comment by tomhoule** [comment]
Yet another: https://prisma-errors.netlify.app/report/13561

**Comment by janpio** [comment]
Are we 100% sure these are all connected to permission problems on the database user?
Could we catch these and just output a helpful error as a smaller scoped feature to implement (vs. the grant checks mentioned before)?
