### ISSUE TITLE
Prisma logging configuration at runtime

### ISSUE THREAD

**Issue by revmischa** [prisma/prisma#9794]
## Problem

I want to enable query logging for a prisma client constructed by a plugin (prisma-appsync)

## Suggested solution

Exposing the log config would be nice. Would be cool to be able to do something like 

```ts
logQueries(async () => {
    await prisma.user.findMany({})
})
```

## Additional context

Logging queries is very useful for debugging and performance tuning.

I usually add a `DUMP_SQL` environment var that enables it for testing.

**Comment by janpio** [comment]
ping @revmischa

**Comment by revmischa** [comment]
Is there any way to change the log levels of prisma after the client has been constructed? Just temporarily?

**Comment by janpio** [comment]
That is an interesting question. I don't think so right now, unless you use the event based logging and then route that through a function maybe. What is your use case? But I would say that is definitely worth a new issue we can turn into a feature request.

**Comment by revmischa** [comment]
In the time since I posted this I stopped using prisma-appsync so for me it's not really needed anymore.
