### ISSUE TITLE
Can't ran 'npx prisma init'

### ISSUE THREAD

**Issue by DianeKL** [prisma/prisma#9805]
Hello!
I need some help with installation Prisma. 

When I run the command "npx prisma init", I get an error like this 
`Downloading Prisma engines for Node-API for windows [                    ] 0%Error: request to https://binaries.prisma.sh/all_commits/b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c/windows/migration-engine.exe.gz.sha256 failed, reason: self signed certificate in certificate chain`
 in the console.
 
I downloaded binaries and ran scripts:
 `"prismaEngine": "set PRISMA_MIGRATION_ENGINE_BINARY=.C:/Users/myPath/migration-engine.exe.gz set PRISMA_INTROSPECTION_ENGINE_BINARY=.C:/Users/myPath/introspection-engine.exe.gz set PRISMA_QUERY_ENGINE_BINARY=.C:/Users/myPath/query_engine.dll.node.gz set PRISMA_FMT_BINARY=.C:/Users/myPath/prisma-fmt.exe.gz"`
 
 I get: `Process finished with exit code 0`
 
 And then I tried to ran "npx prisma init" again. And caught the same error.

**Comment by janpio** [comment]
> When I run the command "npx prisma init", I get an error like this
> `Downloading Prisma engines for Node-API for windows [ ] 0%Error: request to https://binaries.prisma.sh/all_commits/b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c/windows/migration-engine.exe.gz.sha256 failed, reason: self signed certificate in certificate chain`
> in the console.

This sounds like a local problem with your environment. Any idea where this self signed certificate comes from?

> "prismaEngine": "set PRISMA_MIGRATION_ENGINE_BINARY=.C:/Users/myPath/migration-engine.exe.gz set PRISMA_INTROSPECTION_ENGINE_BINARY=.C:/Users/myPath/introspection-engine.exe.gz set PRISMA_QUERY_ENGINE_BINARY=.C:/Users/myPath/query_engine.dll.node.gz set PRISMA_FMT_BINARY=.C:/Users/myPath/prisma-fmt.exe.gz"

The downloaded file needs to be extracted. The file to set as the env var is a `.exe` or `.dll.node` file. (The `.dll.node` needs to be set as `PRISMA_QUERY_ENGINE_LIBRARY`, not `..._BINARY`.

**Comment by janpio** [comment]
@eric79 's actual issue is at https://github.com/prisma/prisma/issues/12162

**Comment by eric79** [comment]
And just to save someone from needing to read through that other thread, here was the answer to my above question:

The way to configure prisma (and many other npm modules) to accept another CA is to set the environment variable NODE_EXTRA_CA_CERTS to the path to your .pem file.

**Comment by janpio** [comment]
Let's close this then and figure out next stes in #12162.
