### ISSUE TITLE
`db pull` errors with `Error: [libs/datamodel/connectors/dml/src/model.rs:174:64] Could not find relation field User on model Team.`

### ISSUE THREAD

**Issue by BoraALAP** [prisma/prisma#9807]
Hi Prisma Team! Prisma Migrate just crashed. 

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.15.1           | 
| Prisma CLI  | 3.2.1              | 
| Engine      | b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c| 

## Error
```
Error: [libs/datamodel/connectors/dml/src/model.rs:174:64] Could not find relation field User on model Team.
```

**Comment by janpio** [comment]
Probably duplicate of: https://github.com/prisma/prisma/issues/10453

**Comment by janpio** [comment]
@BoraALAP Hey, can you give us some more information on this?

**Comment by Weakky** [comment]
Hey @BoraALAP,

Did you get a chance to have a look at @janpio's comment? It'd be helpful for us to move your issue forward.

Thank you 🙏

**Comment by jharrell** [comment]
@BoraALAP 

Following up: we'd love to move forward here but are unable to reproduce without a schema and small reproduction repository. Are you still having this issue? 

Thanks!

**Comment by jharrell** [comment]
Hi again, 

Unfortunately without further info we'll need to close this issue. If you have a similar issue, please drop a comment or open a new issue. Thank you!
