### ISSUE TITLE
Use short commit hash instead of full hash

### ISSUE THREAD

**Issue by schickling** [prisma/prisma#981]
We're currently using the full commit hash to indicate the version of the included Prisma binaries. To make things less "intimidating", I'd suggest to use the short commit hash version (7 digit) instead.

![image](https://user-images.githubusercontent.com/1567498/69506077-d4de7280-0ee1-11ea-8afd-6ea6cc507489.png)

**Comment by matthewmueller** [comment]
internal note: dropping for now

**Comment by matthewmueller** [comment]
Closing. We can revisit once the product stabilizes further and it's more clear what SHAs we should shorten.
