### ISSUE TITLE
Checking if a relation is established

### ISSUE THREAD

**Issue by i0x0** [prisma/prisma#9811]
## Problem

I have a schema which looks like this 
```prisma
model UserProfile {
  createdAt           DateTime        @default(now())
  updatedAt           DateTime        @updatedAt
  id                  String          @id @default(cuid())
  username            String          @unique
  name                String          @default("New User")
  following           UserProfile[]   @relation("UserFollows")
  followers           UserProfile[]   @relation("UserFollows")
}
```
I want to be able to tell if there's a relation between two models but with the current client, I really can't do that.

## Suggested solution

```ts
let relationCheck: boolean = await prisma.userProfile.relationCheck({
  following: {
    from: {
      username: "test1"
    },
    to: {
      id: "(a cuid)"
    }
  }
})

// relationCheck would either return true or false if the relation is or isn't established
```

## Alternatives

If there could be any other way to do this with `findUnique`

**Comment by janpio** [comment]
A `relationCheck` API could now be implemented with a [Client Extension](https://www.prisma.io/docs/orm/prisma-client/client-extensions), which would then under the hood just do the suggest `find` queries and then respond with `true` or `false` instead of returning the potentially found data.
