### ISSUE TITLE
 Packaging and distributing the Prisma CLI beyond npm (e.g. Homebrew)

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#9820]
## Problem

Right now, it's only possible to use the Prisma CLI via npm (or in Go via go run `github.com/prisma/prisma-client-go prisma <command>`). 

As Prisma Migrate is in GA and it being a really useful migration tool, I was wondering if it would make sense to consider distributing the Prisma CLI in other ways so that other language ecosystems can benefit from Prisma Migrate as well without needing to use the Node.js development tools. 

## Suggested solution

With Prisma 1, we also distributed the CLI via Homebrew: https://v1.prisma.io/docs/1.34/prisma-cli-and-configuration/using-the-prisma-cli-alx4/#homebrew

**Comment by janpio** [comment]
We have not heard any requests for this, so we are currently not considering this.
