### ISSUE TITLE
pnpm: Can not `prisma generate` when `@prisma/client` is not installed in project

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma#9848]
### Bug description

<img width="663" alt="image" src="https://user-images.githubusercontent.com/7302317/137945765-d35f7f63-4f93-4de1-b464-ebb15123609c.png">

### How to reproduce

Just add Prisma to pnpm workspace

### Prisma information

package.json

```json
{
  "name": "adonis",
  "type": "module",
  "license": "MIT",
  "engines": {
    "node": ">=16.0.0"
  },
  "scripts": {
    "clean": "pnpm dlx rimraf \"**/{node_modules,dist,lib,lib-types}\"",
    "build": "bob-esbuild tsc && pnpm prepack -r",
    "test": "pnpm build && pnpm --prefix packages/ai start",
    "lint": "eslint \"./**/*.{ts,tsx}\"",
    "run": "node --experimental-specifier-resolution=node --loader ts-node/esm",
    "prisma": "cross-env NODE_ENV=${NODE_ENV:-development} dotenv-flow -- prisma",
    "migrate:dev": "pnpm prisma migrate dev",
    "migrate:dev:create": "pnpm prisma migrate dev --create-only",
    "migrate:deploy": "pnpm prisma migrate deploy",
    "migrate:reset": "pnpm prisma migrate reset",
    "migrate:resolve": "pnpm prisma migrate resolve",
    "prisma:generate": "pnpm prisma generate",
    "prisma:generate:watch": "pnpm prisma generate --watch",
    "prisma:seed": "pnpm prisma db seed",
    "prisma:studio": "pnpm prisma studio"
  },
  "devDependencies": {
    "@types/node": "^16.11.1",
    "@typescript-eslint/eslint-plugin": "^5.1.0",
    "@typescript-eslint/parser": "^5.1.0",
    "cross-env": "^7.0.3",
    "dotenv-flow-cli": "^1.0.0",
    "esbuild": "^0.13.8",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "prettier": "^2.4.1",
    "prisma": "^3.2.1",
    "ts-node": "^10.3.0",
    "typescript": "^4.5.0-dev.20211018"
  },
  "dependencies": {
    "bob-esbuild": "^2.0.1",
    "bob-esbuild-cli": "^2.0.0"
  }
}

```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: 16.11.1

### Prisma Version

```
prisma                  : 3.3.0
@prisma/client          : 3.3.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/.pnpm/@prisma+engines@3.3.0-30.33838b0f78f1fe9052cf9a00e9761c9dc097a63c/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/.pnpm/@prisma+engines@3.3.0-30.33838b0f78f1fe9052cf9a00e9761c9dc097a63c/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/.pnpm/@prisma+engines@3.3.0-30.33838b0f78f1fe9052cf9a00e9761c9dc097a63c/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/.pnpm/@prisma+engines@3.3.0-30.33838b0f78f1fe9052cf9a00e9761c9dc097a63c/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 33838b0f78f1fe9052cf9a00e9761c9dc097a63c
Studio                  : 0.437.0
```

**Comment by aladinflux** [comment]
I'm having the same issues with `prisma@3.2.1`. Using pnpm in a workspace, I get that `npm` issue. I'm suspecting it's the `node` version (16) which might be incompatible.

```zsh
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! Tracker "idealTree:inflate:" already exists

npm ERR! A complete log of this run can be found in:
npm ERR!     /path/to/.npm/_logs/2021-10-20T04_24_23_448Z-debug.log
Error: Command failed with exit code 1: npm install -D prisma@3.2.1
```

**Comment by aladinflux** [comment]
I switched to `node@14` using `nvm` and it seems to work fine.

**Comment by yovanoc** [comment]
You're right but too bad to rollback to node14...

**Comment by yovanoc** [comment]
Oh yes I just figured it out. You have to add @prisma/client too in dependencies at the root of your workspace if this is the place where you run prisma otherwise it tries to install it and fail

**Comment by janpio** [comment]
The missing `@prisma/client` triggers automatic installation of said package when running `prisma generate` (as that package is required) using `npm install`. Seems with the specific versions you are testing this is failing.

Can you please repeat the exact Npm and Node versions you are having these problems? Hopefully we can reproduce with that information and investigate a fix.

**Comment by MarcusCemes** [comment]
I'm trying to create a docker image with pnpm and prisma, and I'm running into the implicit creation of a `package-json.lock` file, which leads me to belive that npm is being run.

I have a Docker based reproduction:

```Dockerfile
FROM node:17-alpine
WORKDIR /app

COPY prisma prisma
RUN npm i -g pnpm
RUN pnpm add prisma @prisma/client
RUN pnpm i -P
RUN rm -rf node_modules
RUN pnpm i -P
```

The trick is that there must be a `pnpm-lock.yaml` file present, if there isn't it works fine (no `package-lock.json`). The Dockerfile above will create one, delete `node_modules` and then install dependencies again (you must have a prisma folder in your local project).

```sh
$ docker build --tag repro .
$ docker run -it repro sh
/app $ ls
node_modules       package-lock.json  package.json       pnpm-lock.yaml     prisma
```

I'm trying to create a small image for production, running `npm` alongside `pnpm` doesn't help with that. I wouldn't be against the idea of converting the `pnpm` lock file to an `npm` one for the final image, but I can't find a safe way to do that.

This is a terminal example of what happens in my own build process:

```sh
/app $ ls
package.json    pnpm-lock.yaml  prisma  dist
/app $ pnpm install --prod
...
node_modules/.pnpm/@prisma+client@3.3.0_prisma@3.3.0/node_modules/@prisma/client: Running postinstall script, done in 1m 4.6s
# This step takes a while, but with no output
...
/app $ ls
node_modules       package-lock.json  package.json       pnpm-lock.yaml     prisma
```

**Comment by aqrln** [comment]
I can confirm that Prisma doesn't seem to detect pnpm and tries to install `@prisma/client` with npm, which, fortunately, breaks (could have been worse if it npm silently rewrote `node_modules` ignoring `pnpm-lock.yaml`). Manually installing `@prisma/client` before running any Prisma commands prevents that.

**Comment by aqrln** [comment]
@MarcusCemes to make things reproducible and have everything in lockfile, you can add the same versions of `prisma` to `devDependencies` and `@prisma/client` to `dependencies` and use full `pnpm install`. There really isn't any specific reason to install `@prisma/client` as a separate step.

**Comment by MarcusCemes** [comment]
That was my original intention, and how I believe it should work. But as I stated above, the reason I'm doing that nasty extra step is because it doesn't seem to play nicely with pnpm. `@prisma/client` runs npm in the `postinstall` hook, generates an unwanted `package-lock.json` and increases my image (node_modules folder) by +25% (200MB).

**Comment by aqrln** [comment]
@MarcusCemes that sounds like a different issue, albeit one that I can't reproduce, unlike the original one in this thread. I feel like there might be some confusion about what happens here, though.

**Comment by janpio** [comment]
Another user hit this in this discussion: https://github.com/prisma/prisma/discussions/12501

**Comment by ErlanBelekov** [comment]
I have a Dockerfile, and it doesn't help me to add prisma before pnpm install
```
FROM node:16-alpine as setup

WORKDIR /app

# install pnpm
RUN npm install -g pnpm

COPY .npmrc package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./

COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/prettier-config/package.json ./packages/prettier-config/
COPY packages/web/package.json ./packages/web/
COPY packages/shared-utils/package.json ./packages/shared-utils/

# copy prisma schema
COPY packages/server/prisma/schema.prisma ./packages/server/prisma/

COPY packages/shared-utils ./packages/shared-utils/

RUN cd packages/shared-utils && pnpm add @prisma/client@3.15.2 prisma@3.15.2

RUN pnpm install --frozen-lockfile --ignore-scripts

# run custom generate script(pnpm prisma generate)
RUN pnpm --filter "@hub/shared-utils" generate
```
this is package.json of shared-utils
```
{
  "name": "@hub/shared-utils",
  "version": "1.0.0",
  "main": "dist/src/index.js",
  "types": "dist/src/index.d.ts",
  "private": true,
  "license": "MIT",
  "scripts": {
    "build": "rm -rf dist && tsc --build",
    "test": "jest",
    "precommit": "eslint --ext .ts \"*/**/*\" --fix && prettier --write .",
    "generate": "pnpm prisma generate",
    "postinstall": "pnpm prisma generate"
  },
  "dependencies": {
    "currency.js": "^2.0.4",
    "@prisma/client": "3.15.2",
    "date-fns": "^2.28.0"
  },
  "devDependencies": {
    "@hub/eslint-config": "1.0.0",
    "@hub/prettier-config": "1.0.0",
    "prisma": "3.15.2"
  },
  "prisma": {
    "schema": "../server/prisma/schema.prisma"
  },
  "prettier": "@hub/prettier-config",
}
```

**Comment by tal-rofe** [comment]
Same here..

**Comment by millsp** [comment]
Hey folks, we have just improved our `pnpm` detection logic to fix this issue, and we will release this in our `4.13.0` release. That said, you can try it now by installing our `dev` version. `npm install prisma@dev`. Feedback welcome!

**Comment by lake2** [comment]
prisma  4.14.1  did not work

> Hey folks, we have just improved our `pnpm` detection logic to fix this issue, and we will release this in our `4.13.0` release. That said, you can try it now by installing our `dev` version. `npm install prisma@dev`. Feedback welcome!

**Comment by lake2** [comment]
it fails when prisma was hosted to pnpm workspace root node_modules

**Comment by DavidVaness** [comment]
I have the same issue as @lake2 😞 
Did this issue get created?

**Comment by janpio** [comment]
It is not linked here, so probably not, unfortunately. Feel free to do so.
