### ISSUE TITLE
dataProxy - more verbose https request logging or server-side dataProxy logs

### ISSUE THREAD

**Issue by irvinebroque** [prisma/prisma#9914]
## Problem

When PrismaClient can't connect to the dataProxy, with all debug options enabled (`DEBUG="*"`, `  log: ["query", "info", "warn", "error"]`), it outputs the following logs:

```
prisma:info Calling https://aws-us-east-1.prisma-data.com/3.3.0/<id>/graphql?id=395 (n=0)
prisma:info Schema (re)uploaded (hash: <id>)
prisma:warn Retrying after 224ms
prisma:info Calling https://aws-us-east-1.prisma-data.com/3.3.0/<id>/graphql?id=395 (n=1)
[2021-10-22 20:23:41] POST roundtrip-development.roundtrip.workers.dev/api/report-csp HTTP/1.1 200 OK
prisma:info Schema (re)uploaded (hash: <id>)
prisma:warn Retrying after 464ms
prisma:info Calling https://aws-us-east-1.prisma-data.com/3.3.0/<id>/graphql?id=395 (n=2)
prisma:info Schema (re)uploaded (hash: <id>)
prisma:warn Retrying after 861ms
prisma:info Calling https://aws-us-east-1.prisma-data.com/3.3.0/<id>/graphql?id=395 (n=3)
prisma:info Schema (re)uploaded (hash: <id>)
prisma:warn Retrying after 2352ms
```

This _suggests_ that PrismaClient can't reach the proxy endpoint, and is therefore retrying. But it's not actionable, because it provides no way to see the http status code of the attempted requests or other error information.

## Suggested solution

Either of the following would help:

1. More verbose logging in PrismaClient. It looks like adding a more verbose log line here would address this:
https://github.com/prisma/prisma/blob/9ea8b99332ed1810a71d53b20e8db43fb33ae244/packages/engine-core/src/data-proxy/DataProxyEngine.ts#L166-L170

2. Allow dataProxy users to provide a logging endpoint that the dataProxy will forward logs to (ex: Datadog, etc.).

## Alternatives

- It's certainly possible to modify the `@prisma/client` module to debug this, but because so much of the code is generated and transpiled, it's tricky to do this well locally. Exporting simpler, ESmodule builds in the future will probably help.

**Comment by janpio** [comment]
Next steps:
- @aqrln gets an overview of the HTTP API calls and retries
- Make suggestions on how to better output error states

**Comment by aqrln** [comment]
More verbose logs have been added since the issue was reported, the error is printed before retrying. Do we want to log HTTP status codes too?

**Comment by janpio** [comment]
As those include useful information per https://www.notion.so/prismaio/Data-Proxy-and-Prisma-Client-58a356f504c0496d971b20c991a52c77#f44f0ad0063249e194e2d65b3c253c59 I would say yes.
