### ISSUE TITLE
Allow specifying "raw" where clause

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma#9930]
## Problem

Most of the time, I cannot use Prisma for a query/update it is because I am unable to recreate the WHERE clause: Here is an example:

```ts
prisma.$executeRaw`UPDATE carrierInPeriodSET XZ = ${true} WHERE (offerID, periodID, carrierID) IN (${
  req.body.wanted.map(({offerID, periodID, carrierID}) => `(${offerID}, ${periodID}, ${carrierID})`).join(',')
})`;

prisma.carrierInPeriod.updateMany({
  data: {
    wanted: true,
  },
  where: { ??? },
});
```

## Suggested solution

```ts
prisma.carrierInPeriod.updateMany({
  data: {
    wanted: true,
  },
  where: {
    $raw: /* WHERE */ `(offerID, periodID, carrierID) IN (${ ... })`,
  },
});
```

## Alternatives

The current solution is the alternative...

**Comment by janpio** [comment]
Thanks for this feature request.

Maybe open a discussion just asking about the "How can I represent this as a Prisma Client Query?" part to see if someone can come up with a solution. (The feature request if of course separate and still valid)

**Comment by nikolasburk** [comment]
I think this might be a duplicate of https://github.com/prisma/prisma/issues/5560 cc @matthewmueller

**Comment by Akxe** [comment]
Closing as duplicite
