### ISSUE TITLE
Prisma engines can't run on fresh installation of Windows without MSVCR

### ISSUE THREAD

**Issue by Dramex** [prisma/prisma#9940]
### Bug description

```
Prisma schema loaded from prisma\schema.prisma
Error: Unable to require(`C:\Users\emad-\code\api_v3\node_modules\prisma\query_engine-windows.dll.node`)
 The specified module could not be found.
\\?\C:\Users\emad-\code\api_v3\node_modules\prisma\query_engine-windows.dll.node
```

### How to reproduce

```
npm install prisma --save-dev
npx prisma generate

```

### Prisma information

will be shared later if needed.,

### Environment & setup

- OS:  Windows 11
- Database: Mysql 
- Node.js version:v14.18.1

### Prisma Version

latest version, running `prisma -v` output 
`Error: Command failed with exit code 3221225781: C:\Users\emad-\code\api_v3\node_modules\@prisma\engines\introspection-engine-windows.exe --version`

tho

**Comment by AliEmad0** [comment]
> The other issue suggest installing `Microsoft Visual C++ 2015 Redistributable` would fix this so please try installing that.

Thank you so much!

**Comment by drewid25** [comment]
> The other issue suggest installing `Microsoft Visual C++ 2015 Redistributable` would fix this so please try installing that.

Thanks , this truly works .

**Comment by nandumoura** [comment]
> > The other issue suggest installing `Microsoft Visual C++ 2015 Redistributable` would fix this so please try installing that.
> 
> That fixed it, Thank you so much!
> 
> i was trying to fix this for days without luck, i even searched in the issues. weird that i didn't get the issue you mention!

thank you I had the same problem and solvs

**Comment by lleobap** [comment]
> The other issue suggest installing `Microsoft Visual C++ 2015 Redistributable` would fix this so please try installing that.
I was having the same problem on my windows 10, installing the visual c++ package solved the problem! thank you so much :)

**Comment by Chetan77verma** [comment]
Thanks a lot , you saved me @pantharshit00

**Comment by CriandoGames** [comment]
> O outro problema sugere que a instalação corrigiria isso, então tente instalar isso.`Microsoft Visual C++ 2015 Redistributable`



thanks ,

**Comment by JeffPatricio** [comment]
> The other issue suggest installing `Microsoft Visual C++ 2015 Redistributable` would fix this so please try installing that.

Thank you so much!

**Comment by tzn-dev** [comment]
Thank you so much!

**Comment by VanderleiKs** [comment]
> The other issue suggest installing `Microsoft Visual C++ 2015 Redistributable` would fix this so please try installing that.

Thanks, my problem was solved.

**Comment by AdamJamiu** [comment]
> 

after installing Microsoft Visual C++ 2015 Redistributable, the issue was fixed. thanks so much

**Comment by kevincantstop** [comment]
Upgrade Node.js from v18.7.0 to v20.5.1 works to me as well in 2023
