### ISSUE TITLE
`Error: Prisma Migrate has detected that the environment is non-interactive, which is not supported.` with NX monorepo

### ISSUE THREAD

**Issue by goofiw** [prisma/prisma#9943]
## Problem

I'm trying to create a project based script to run prisma commands using nx (see nx.dev for more info).  The problem is prisma detects the shell command as non interactive.

Specifically, I'm trying to change a column to be unique, but I can't with what I've set up because I get the above error.  Created the initial migration using the shell executor actually worked fine.

## Suggested solution

1.  Allow migrations to be created, but not run when conflicts or failure may occur when using --create-only (we already get the nice warning in the created migration)
2.  add a --allowReset to allow a reset

**Comment by janpio** [comment]
Which command are you actually trying to run, `prisma migrate dev`?

**Comment by janpio** [comment]
ping @goofiw

**Comment by luxaritas** [comment]
Just ran into this with `prisma migrate dev`. Set up an nx target like:
```
"prisma-migrate": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "command": "prisma migrate dev --schema apps/api/prisma/schema.prisma"
      }
}
```
Then `nx prisma-migrate` gets the non-interactive error

**Comment by EcksDy** [comment]
Hey guys, 
was there any progress on the topic? I get the same behaviour when running local migrate through NX, with a similar setup as above.
Are there any workarounds besides running the script not through NX?

**Comment by ahmadalfy** [comment]
Same issue here as well

**Comment by ObaidQatan** [comment]
I have just went through the same and, deleting the "prisma_migrations" table on my database solved the issue.

**Comment by kieran-osgood** [comment]
Thought I'd link my issue here: #16003 incase it works for anyone else
I found that my script didn't work as expected with 
`prisma migrate reset --force`
Changing it to the following worked however:
 `prisma migrate reset -- --force`

**Comment by SevInf** [comment]
Hello everyone!
This is an issue with NX, not with `prisma`. See nrwl/nx#8269. It also has a bunch of workarounds for the problem - you might find out that one of them would work out for you.

You can also follow a feature request for allowing `migrate dev` to run in non-interactive shell in #7113.

Thanks everyone for feedback. I am going to close this issue either in favor of `nx` issue and or aforementioned feature request.
