### ISSUE TITLE
Prisma with Azure PostgreSQL/AD connection

### ISSUE THREAD

**Issue by danielweil** [prisma/prisma#9954]
Is there any way to use Prisma with Azure PostgreSQL with AD connection? It needs to use a access token as credential for the connection and I was wondering how to proceed with this kind of login, due to the fact the connection string is set as a static config in the schema file.

Any way to manage this?

Faithfully,

**Comment by janpio** [comment]
How long is the access token valid @danielweil? If it is not rotated frequently (as the example in #7869), you could probably just use an env var in your schema file and then update the env var with the access token once. When you update the env var for a new token, you have to stop your Prisma Client instance inside your app for the new env var to be picked up.

**Comment by danielweil** [comment]
Every Hour.

**Comment by danielweil** [comment]
Yes it is. Do you have any solution to this problem?

**Comment by janpio** [comment]
No, that feature request issue is tracking suggestions on how to solve this and will be closed when something is implemented.

I am going to close this issue here not to avoid duplicates. Thanks.
