### ISSUE TITLE
DB connection retry not happening

### ISSUE THREAD

**Issue by dmateus-patra** [prisma/prisma#9967]
### Bug description

I'm using a prisma setup in nest.js very similar to this example:
https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nestjs
If I start the application when the DB is down, even after starting the DB, I keep getting an "Error creating a database connection" error when calling prisma. It requires an application restart to recover from this.
```
Error:
"\nInvalid `prisma.workOrder.create()` invocation:\n\n\n  Error creating a database connection. (Error creating a database connection.)"
```

### How to reproduce

1. Shut down the DB.
2. Start the nest.js application with the prisma setup as explained in the docs, similar to this example: https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nestjs.
3. Make a prisma call and get the "Error creating a database connection" error.
4. Start the DB, make sure it's running properly.
5. Make the prisma call again and you still get the "Error creating a database connection" error.

Note: I've tried both the explicit and lazy approach to start the connection (implementing or not the OnModuleInit) and both have the same issue. 

### Expected behavior

Even if the DB is down at application startup, I'd expect prisma to be able to connect to the DB once the DB is started, without an application restart.

Note: I've noticed prisma is able to recover from a database shutdown/restart without having to restart the application, if - and only if - the DB was up and running when the application started.

### Prisma information

I'm adding part of the relevant code here (prisma schema includes object definition, just not showing it here):
![image](https://user-images.githubusercontent.com/83661516/138989185-f7053463-5802-40ad-9bf5-4af731860253.png)

Note: I've tried implementing and not implementing the onModuleInit.
![image](https://user-images.githubusercontent.com/83661516/138990358-5cabc25e-3877-405c-b31e-f2655ddc6f5f.png)

![image](https://user-images.githubusercontent.com/83661516/138988978-8bffce70-8fa9-44d9-94bb-eff698685aa2.png)

### Environment & setup

- OS: Windows 10
- Database: Microsoft SQL Server 15.0.2000.5
- Node.js version: 14.16.0

### Prisma Version

```
prisma                  : 3.0.1
@prisma/client          : 3.0.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\query_engine-windows.dll.node)        
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\migration-engine-windows.exe)    
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\introspection-engine-windows.exe)  
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by janpio** [comment]
Thanks for the report. We will try to reproduce this.

Do you think the rest-nestjs app has influence on this specifically or if this is a general Prisma thing?

**Comment by garrensmith** [comment]
https://github.com/prisma/prisma/pull/12066 fixes this. 
You can test it out with `prisma@dev` and will be out in the next release
