### ISSUE TITLE
Output better error message than `...query_engine-windows.dll.node  The specified module could not be found.` or `Command failed with exit code 3221225781`

### ISSUE THREAD

**Issue by CarmeloDascola** [prisma/prisma#9975]
### Bug description

I am trying to set up an existing project in a new device running Win10. I install the dependencies (including "@prisma/client": "^3.3.0"). When I try to run `prisma generate` I get this:
```
Prisma schema loaded from prisma\schema.prisma
Error: Unable to require(`C:\Users\carme\AppData\Roaming\npm\node_modules\prisma\query_engine-windows.dll.node`)
 The specified module could not be found.
\\?\C:\Users\carme\AppData\Roaming\npm\node_modules\prisma\query_engine-windows.dll.node
```
query_engine-windows.dll.node is in my project node_modules/prisma folder, but it doesn't appears in node_modues/.prisma

If I try to run `prisma -v` I get:
```
Error: Command failed with exit code 3221225781: C:\Users\carme\AppData\Roaming\npm\node_modules\prisma\node_modules\@prisma\engines\introspection-engine-windows.exe --version
```

Tried deleting node_modules, manually reinstalling @prisma/client, rebooting the system, but no success. Any idea? thanks.

### How to reproduce

In my case just running `prisma generate` causes the issue.

### Environment & setup

OS: Windows 10
Database: PostgreSQL
Node.js version: v16.13.0

### Prisma Version

```

```

**Comment by janpio** [comment]
Same error message: https://github.com/prisma/prisma/discussions/14128

**Comment by Davidflm** [comment]
> Hi @CarmeloDascola and thanks for your report! Could you please check if installing [Microsoft Visual C++ Redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe) fixes the issue?

Resolveu o meu problema. Muito Obrigado. (Solved my Problem. Thanks.)

**Comment by leitecsleite** [comment]
@aqrln Thank you very much, it solved my problem.

**Comment by elioenays** [comment]
> Hi @CarmeloDascola and thanks for your report! Could you please check if installing [Microsoft Visual C++ Redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe) fixes the issue?

solve for me, thanks 👍✔

**Comment by adnahl** [comment]
Fix my problem [Visual C++ Redistributable for Visual Studio](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by aqrln** [comment]
@BONDbATIF

> It would be really good to Prisma can document it somewhere

It is currently documented in the system requirements page: https://www.prisma.io/docs/reference/system-requirements#windows-runtime-dependencies
