### ISSUE TITLE
`JsonNullValueInput` problem in Prisma 3 with nexus-plugin-prisma

### ISSUE THREAD

**Issue by ecpark-danbi** [prisma/prisma#9986]
### Bug description

From prisma-example (https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-nextjs)
Just added `Json` field. Prisma 2 and nexus-plugin-prisma mutation CRUD worked. However after upgrading prisma@3, GraphQL schema only has `JsonNullValueInput` enum type only.

### How to reproduce

1. From prisma-example (https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-nextjs), Database changed to MySQL by using docker.
2. Just added `Json` field named `address` in `User`
```prisma
model User {
  email   String  @unique
  id      Int     @id @default(autoincrement())
  name    String?
  address Json
  posts   Post[]
}
```
3. Make schema
adding `GQLJson` scalar
```ts
export const schema = makeSchema({
  types: [GQLDate, GQLJson, Query, Mutation, Address, Post, User],
  plugins: [nexusPrisma({
    prismaClient: ctx => ctx.prisma = prisma,
    experimentalCRUD: true,
    paginationStrategy: "prisma",
  })],
  sourceTypes: {
    modules: [
      {
        module: "@prisma/client",
        alias: "prisma",
      },
    ],
  },
  outputs: {
    typegen: path.join(process.cwd(), 'generated/nexus-typegen.ts'),
    schema: path.join(process.cwd(), 'generated/schema.graphql'),
  },
  contextType: {
    module: path.join(process.cwd(), "context/index.ts"),
    export: "Context",
  },
})
```
4. ObjectType and CRUD type
add nexus model `address`
```ts
const User = objectType({
  name: 'User',
  definition(t) {
    t.int('id')
    t.string('name')
    t.model.address()
    t.string('email')
    t.list.field('posts', {
      type: 'Post',
      resolve: (parent) =>
        prisma.user
          .findUnique({
            where: { id: Number(parent.id) },
          })
          .posts(),
    })
  },
})
```

```ts
const Mutation = objectType({
  name: 'Mutation',
  definition(t) {
    t.field('signupUser', {
      type: 'User',
      args: {
        name: stringArg(),
        email: nonNull(stringArg()),
      },
      resolve: (_, { name, email }, ctx) => {
        return prisma.user.create({
          data: {
            name,
            email,
            address: { address1: "a", address2: "b" }
          },
        })
      },
    })

    t.nullable.field('deletePost', {
      type: 'Post',
      args: {
        postId: stringArg(),
      },
      resolve: (_, { postId }, ctx) => {
        return prisma.post.delete({
          where: { id: Number(postId) },
        })
      },
    })

    t.field('createDraft', {
      type: 'Post',
      args: {
        title: nonNull(stringArg()),
        content: stringArg(),
        authorEmail: stringArg(),
      },
      resolve: (_, { title, content, authorEmail }, ctx) => {
        return prisma.post.create({
          data: {
            title,
            content,
            published: false,
            author: {
              connect: { email: authorEmail },
            },
          },
        })
      },
    })

    t.nullable.field('publish', {
      type: 'Post',
      args: {
        postId: stringArg(),
      },
      resolve: (_, { postId }, ctx) => {
        return prisma.post.update({
          where: { id: Number(postId) },
          data: { published: true },
        })
      },
    })
    t.crud.createOneUser();
  },
})
```

5. Run and open Apollo studio
```graphql
mutation CreateOneUserMutation($data: UserCreateInput!) {
  createOneUser(data: $data) {
    name
    address
    email
  }
}
```
variables: address type was `JsonNullInput`
```
{
  "data": {
    "email": "eunchurn@gmail.com",
    "name": "eunchurn",
    "address": "JsonNull"
  }
}
```
6. Error
```
"message": "Cannot return null for non-nullable field User.address.",
```
7. How can I add `Json` data via GraphQL with `nexus-plugin-prisma` by using experimentalCRUD?

### Expected behavior

Add JsonObject data in Json field without Error by using `nexus-plugin-prisma` experimentalCRUD

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["filterJson"]
}

datasource db {
  provider      = "mysql"
  url           = env("DATABASE_URL")
}

model User {
  email   String  @unique
  id      Int     @id @default(autoincrement())
  name    String?
  address Json
  posts   Post[]
}

model Post {
  authorId  Int?
  content   String?
  id        Int     @id @default(autoincrement())
  published Boolean @default(false)
  title     String
  author    User?   @relation(fields: [authorId], references: [id])
}
```

### Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: 16.11.1

### Prisma Version

```
prisma                  : 3.3.0
@prisma/client          : 3.3.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 33838b0f78f1fe9052cf9a00e9761c9dc097a63c
Studio                  : 0.437.0
Preview Features        : filterJson
```

**Comment by janpio** [comment]
Is this a Prisma question, or a `nexus-plugin-prisma` question?

**Comment by ecpark-danbi** [comment]
> Is this a Prisma question, or a `nexus-plugin-prisma` question?

Yes, it is. `nexus-plugin-prisma` question. But we build our GraphQL API with `nexus-plugin-prisma` with lots of complex endpoints. This required CRUD. However, after upgrading to Prisma 3 version, the above error occurs for Json type. In the Prisma example, `nexus-plugin-prisma` is also used, but in Prisma 3 and `nexus-plugin-prisma`, `Json` generates an error, so I do not know what to do with this part. It's almost impossible to migrate CRUD directly from `nexus`. Should we wait for the CRUD function, which is specified as a long-term roadmap for [`nexus-prisma`](https://nexus.prisma.io/roadmap#longterm)?

I made a report here to see if there is a workaround that can be supported in Prisma 3 as well.

**Comment by janpio** [comment]
Prisma ORM (the CLI and Client library) unfortunately can not do anything about making `nexus-plugin-prisma` support this. You should definitely create an issue over at https://github.com/graphql-nexus/nexus-plugin-prisma, there is is much more probably that people interested in that plugin (that might have the same question and problem) could see your issue.

**Comment by ecpark-danbi** [comment]
I see, thank you for your support.

**Comment by entrptaher** [comment]
I have faced this while trying to convert a prisma v2 to prisma v3 project. 

I believe this is coming from prisma itself, and not from `nexus-prisma-plugin`. The generated `@prisma/client` has `const dmmfString = ` which has `Json` on prisma version 2.28. But on the 3.0.1 and onwards, the same fields are replaced by `JsonNullableFilter`. One possible reason could be the `filterJson` feature getting directly into the codebase and not having it optional.

This makes it hard to upgrade to prisma v3.
