### ISSUE TITLE
Update does not enforce type on `data`

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma#9988]
### Discussed in https://github.com/prisma/prisma/discussions/9957

> <div type='discussions-op-text'>
> 
> <sup>Originally posted by **GuiSim** October 26, 2021</sup>
> Hello! 
> 
> I'm new to Prisma and testing it out. I encountered an issue today where an `update` statement would not raise any type issue on an invalid `data` object.
> 
> ```
> prisma.mything.update({
>   where: { id: '1' },
>   data: { invalidField: 42 }, // Does not compile as `invalidField` is not a valid field on `mything`
> });
> 
> const data = { invalidField: 42 };
> prisma.mything.update({
>   where: { id: '1' },
>   data: data, // Compiles without issues. Why?
> });
> ```
> 
> Can you help me understand why?</div>

**Comment by Jolg42** [comment]
See https://github.com/prisma/prisma/issues/22445
